### ISSUE TITLE
Ivy: Can't set default value for 'select' when options are generated dynamically through ngFor

### ISSUE THREAD

**Issue by alexzuza** [angular/angular#34470]
### Is this a regression?

Yes, it works in ViewEngine

### Description
While working with Ivy I noticed one incompatibility with ViewEngine.
Let's say we want to dynamically generate options for select and also assign default value

```
<select [value]="3">
  <option [value]="item" *ngFor="let item of [1,2,3]">{{ item }}</option>
</select>
```

ViewEngine will render 3 as selected value(https://ng-run.com/edit/rn9WBjLKXzXUEI8CSE3d) but in Ivy the first item will be selected(https://ng-run.com/edit/TXJC0ZhJTzrN8aYgUmtH?aot=true).

It's happening because the order of checking is different.In ViewEngine updateDirectives is called first(which triggers ngFor directive to render all options) and then updateRenderer is called which sets value to the select.
Ivy checks template from top to bottom so that it first sets default value and since there is no any options rendered it doesn't actually set it. And after that options are rendered.

ViewEngine behavior looks rational for me so I wonder if it's need to be fixed for Ivy. The workaround is using `selected` binding on `option` tag.

Please do note that similar React code(https://codesandbox.io/s/priceless-pare-lynml)

```
<select value={3}>
 {[1, 2, 3].map(item => <option value={item}>{item}</option>)}
</select>
```

works the same way as in ViewEngine

## 🔬 Minimal Reproduction

ViewEngine https://ng-run.com/edit/rn9WBjLKXzXUEI8CSE3d
Ivy 9.0.0-rc.6 https://ng-run.com/edit/TXJC0ZhJTzrN8aYgUmtH?aot=true

**Comment by pkozlowski-opensource** [comment]
> ViewEngine behavior looks rational for me so I wonder if it's need to be fixed for Ivy.

@alexzuza with ivy we've made a deliberate choice to change bindings order. There are various reasons for this but the long story short is that VE order was somehow arbitrary - a user would have to have deep understanding of the internal implementation to understand the order of bindings.

Still, I totally agree that this particular case "just worked" in VE and is problematic in ivy. At the same time there are many other cases that don't "just work" in VE so order of bindings is a tricky subject that we still debate internally.

For v9 with ivy we are going to mark it as a breaking so your work-around of "using selected binding on option tag" is the right one for both VE and ivy compatibility. Having said this the whole topic of "binding order" is not closed and I would expect more design / changes in the future.

**Comment by theodorejb** [comment]
Possibly related: #23784. I'm still hoping this can be fixed in v9.
