### ISSUE TITLE
Ivy breaks with local npm directory dependency with error: TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by arobinson** [angular/angular#34478]
# 🐞 bug report

### Affected Package
Ivy and ngcc

### Is this a regression?
A regression from Angular 7, but the issue may have always been present in Ivy?

### Description
I'm trying to get our companies application ported to Angular 9 from Angular 7. I've already made many fixes, and came across this one:
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property '1' of null
TypeError: Cannot read property '1' of null
    at providersResolver (core.js:27364)
    at Object.definition.providersResolver (core.js:27662)
    at resolveDirectives (core.js:14641)
    at elementStartFirstCreatePass (core.js:23429)
    at ɵɵelementStart (core.js:23467)
    at Module.ɵɵelement (core.js:23547)
    at TestComp2Component_Template (test-comp2.component.html:2)
    at executeTemplate (core.js:13974)
    at renderView (core.js:13774)
    at renderComponent (core.js:15214)
    at resolvePromise (zone-evergreen.js:793)
    at resolvePromise (zone-evergreen.js:752)
    at zone-evergreen.js:854
    at ZoneDelegate.invokeTask (zone-evergreen.js:400)
    at Object.onInvokeTask (core.js:41410)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:570)
```

The template code that is failing is:
```
        <div [froalaEditor]="frOptions" formControlName="NWTTextEditor" id="NWTTextEditor"
          [NwRecordingValueDirective]="{
            actionType: 'setValue',
            configuration: { dataItem: 'NWTTextEditor'},
            actions: ['formChange']
          }">
        </div>
```
Inside of this function:
```
export function providersResolver<T>(
    def: DirectiveDef<T>, providers: Provider[], viewProviders: Provider[]): void {
  const lView = getLView();
  const tView: TView = lView[TVIEW];
  if (tView.firstCreatePass) {
    const isComponent = isComponentDef(def);

    // The list of view providers is processed first, and the flags are updated
    resolveProvider(viewProviders, tView.data, tView.blueprint, isComponent, true);

    // Then, the list of providers is processed, and the flags are updated
    resolveProvider(providers, tView.data, tView.blueprint, isComponent, false);
  }
}
```
The `lView` that is returned is null. Since the error is not clear, I am not yet sure of the cause. Once I find it, I'll leave a comment here.

I have `angular-froala-wysiwg` imported locally (fork of https://github.com/froala/angular-froala-wysiwyg) since they don't have a release that works in Angular 9 yet (they latest release is still using the remove Angular Renderer). Package.json contents:
```
...
"angular-froala-wysiwyg": "file:../angular-froala-wysiwyg/dist",
...
```

The issue seems to be coming from ngcc. If I change Angular to use a tgz file instead of the dist directory, it works.

## 🔬 Minimal Reproduction

Repo:
https://github.com/arobinson/angular-bug-34478

Steps:

1. First build and run the app:
```
git clone git@github.com:arobinson/angular-bug-34478.git
cd angular-bug-34478/test-app
npm i
ng s -o
```
2. Open the chrome developer tools console
3. Click on `Go to comp 2`
4. Notice the error (page loads blank)

### Example of it working

Run this to see it working from the `test-app` directory:
```
git checkout WorkingWithNpmPack
npm run rebuild.froala
ng s -o
```

Now it works. The main difference in the two branches this change to `package.json`:
```
@@ -24,7 +26,7 @@
     "@angular/platform-browser": "~9.0.0-rc.5",
     "@angular/platform-browser-dynamic": "~9.0.0-rc.5",
     "@angular/router": "~9.0.0-rc.5",
-    "angular-froala-wysiwyg": "file:../angular-froala-wysiwyg/dist",
+    "angular-froala-wysiwyg": "file:../angular-froala-wysiwyg/dist/angular-froala-wysiwyg-3.0.6.tgz",
     "froala-editor": "^3.0.6",
     "rxjs": "~6.5.3",
     "tslib": "^1.10.0",
```

## 🔥 Exception or Error
<pre><code>
ERROR Error: Uncaught (in promise): TypeError: Cannot read property '1' of null
TypeError: Cannot read property '1' of null
    at providersResolver (core.js:27364)
    at Object.definition.providersResolver (core.js:27662)
    at resolveDirectives (core.js:14641)
    at elementStartFirstCreatePass (core.js:23429)
    at ɵɵelementStart (core.js:23467)
    at Module.ɵɵelement (core.js:23547)
    at TestComp2Component_Template (test-comp2.component.html:2)
    at executeTemplate (core.js:13974)
    at renderView (core.js:13774)
    at renderComponent (core.js:15214)
    at resolvePromise (zone-evergreen.js:793)
    at resolvePromise (zone-evergreen.js:752)
    at zone-evergreen.js:854
    at ZoneDelegate.invokeTask (zone-evergreen.js:400)
    at Object.onInvokeTask (core.js:41410)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:570)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.5
Node: 12.13.1
OS: darwin x64

Angular: 9.0.0-rc.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.5
@angular-devkit/build-angular      0.900.0-rc.5
@angular-devkit/build-ng-packagr   0.900.0-rc.5
@angular-devkit/build-optimizer    0.900.0-rc.5
@angular-devkit/build-webpack      0.900.0-rc.5
@angular-devkit/core               9.0.0-rc.5
@angular-devkit/schematics         9.0.0-rc.5
@angular/cdk                       9.0.0-rc.4
@angular/cli                       9.0.0-rc.5
@ngtools/webpack                   9.0.0-rc.5
@schematics/angular                9.0.0-rc.5
@schematics/update                 0.900.0-rc.5
ng-packagr                         9.0.0-rc.2
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2
</code></pre>

**Anything else relevant?**

I'm using
* node 12 LTS (12.13.1)
* npm 6.12.1

**Comment by arobinson** [comment]
Just found the cause and the latest updates reflect the issue. When a local library is imported by NPM via a relative path, the Ivy compiler does not work correctly.

**Comment by arobinson** [comment]
Although not the same issue, https://github.com/angular/angular/issues/33395 also is referencing issues with ngcc and relative directories.

**Comment by arobinson** [comment]
Work-arounds for anyone else having this problem
1. Use `npm pack` and install the `tgz` file in your `package.json` as shown above
2. Turn on Ivy in your `tsconfig.json` for your library
```
  "angularCompilerOptions": {
    ...
    "enableIvy": true
  }
```
3. Manually run `ngcc` with `--target` pointing to the `dist` directory of your library after building it.

**Comment by hevans90** [comment]
Same error when `yarn link`ing to an npm package, from an app using Ivy.

**Comment by seanlandsman** [comment]
I had something very similar (using `npm link`) and the my solution was to add paths to `tsconfig.app.json`:

```
    "paths": {
      "@angular/*": [
        "./node_modules/@angular/*"
      ],
```

**Comment by vnesterovsky** [comment]
I resolved similar issue with following fix in angular.json of project:

```
 "build": {
   "builder": "@angular-devkit/build-angular:browser",
   "options": {
     "vendorSourceMap": true,
     "preserveSymlinks": true,
```

**Comment by petebacondarwin** [comment]
ngcc does not follow symlinks so you should not expect Angular libraries linked via `npm link` into an Ivy application project to work. The workaround is to follow @arobinson 's comment here: https://github.com/angular/angular/issues/34478#issuecomment-567579719
