### ISSUE TITLE
Link external stylesheet to a single component in angular 6

### ISSUE THREAD

**Issue by sincy123** [angular/angular#34491]
I want 2 components in an angular 6 application

I wish first component to use bootstrap min.css file , and the other not

how can i implement this

**Comment by EmaGht** [comment]
You can use the `styleUrls: ["./bootstrap-min.css"],` in the component declaration for the file you want to use bootstrap in.

Next time you have this kind of support request make sure to ask them in the proper channel tho (a.k.a StackOverflow)

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
