### ISSUE TITLE
Implement Service Worker

### ISSUE THREAD

**Issue by OsborneDS** [angular/angular#34507]
Hello everyone, My name is Osborne D'Silva. I am trying to implement Service Workers for an existing angular project and am facing issues when implementing it. 

The issue is that the angular app disconnects from the node js server in production mode and starts throwing cors error in the console. Currently because it is causing issues I have disabled it. While I was searching on how to implement service workers in angular, I found an article which says that to implement service worker I need to have the latest version of Angular Cli. My current angular project configuration is as follows:-

![Angular config](https://user-images.githubusercontent.com/58810638/71233342-5972b400-231b-11ea-897c-a4371333e3bb.png)

My question is whether it is really required to have the latest version of Angular Cli to implement service workers or what issues it could cause if it is implemented on a older version of Angular Cli. Any suggestions or articles would be of great help. Thanks in advance.

**Comment by Karamuto** [comment]
Hello @OsborneDS ,

I guess usually questions are asked on stackoverflow, but a short search has brought me to this site:

https://pwa.ng/

There they have used the cli in version 6, so it should be doable.
I should also mention, that you should target an update of you angular version in the future as v6 has already run out of LTS.

**Comment by OsborneDS** [comment]
Thanks @Karamuto.
I have another query, I have added pwa to the existing project but am unable to register the service worker file. Is there any other guide I should follow to implement service workers in Angular 7?

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
