### ISSUE TITLE
Angular routing doesn't work as expected

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular#34504]
app.module.ts
```
const routes: Routes = [
  
  {
    path: ":type",
    loadChildren: () =>
      import("./content/content.module").then(m => m.ContentModule)
  },

 ....
];
```

content.module.ts
```
const routes: Routes = [
  { path: ":item", component: ContentComponent } //item =  id-slug
];
```

let's test this routing configurations:
http://localhost:4200/articles/123-slug  -> {type: articles, item: 123-slug} OK
http://localhost:4200/articles/123          -> {type: articles, item: 123} OK
http://localhost:4200/articles                  -> {type: null, item: articles} NOT OK expected: {type: articles, item:null}

**Comment by Airblader** [comment]
I would actually expect this to not match any route, but I do agree it's odd. Does it work when you add an empty route to the content module (path empty, pathMatch full)?

**Comment by patrick-entinux** [comment]
Not sure if this is what you are looking for or not, but when I want to do something like this, I usually add an empty string route, like this: 

```
const routes: Routes = [
  { path: "", component: ContentComponent } //item =  id-slug
  { path: ":item", component: ContentComponent } //item =  id-slug
];
```
