### ISSUE TITLE
Sanitizing through createHTMLDocument() does not work on Opera Presto

### ISSUE THREAD

**Issue by Abradoks** [angular/angular#34519]
# 🐞 bug report
Merely opening https://about.google/ produces alert(1) on Opera 12.18. That's caused by `inertBodyElement.innerHTML = '<svg><p><style><img src="</style><img src=x onerror=alert(1)//">';` line in https://github.com/angular/angular/blob/master/packages/core/src/sanitization/inert_body.ts#L41

I think the issue is specific to the `<img>` tag, which gets loaded in Opera.

**Comment by atscott** [comment]
Closing as unsupported. See https://angular.io/guide/browser-support
