### ISSUE TITLE
Renderer2 insertBefore()

### ISSUE THREAD

**Issue by sztok7** [angular/angular#34511]
# 📚 Docs or angular.io bug report

### Description

I)n the insertBefore() method, it says that refChild preceedes the new node, but it doesn't, it comes after, hence the name insertBEFORE.

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. Closing this ticket since PR #34547 that contains the necessary changes was merged. Thank you.
