### ISSUE TITLE
Change in angularjs 2.0 DISPLAYING DATA document, class FriendsService has to be defined before appInjector.

### ISSUE THREAD

**Issue by deepakshrma** [angular/angular#3452]
According to issue: angular/angular#1655 
FriendsService has to be defined before appInjector. It is very irritating to resolve this kind of error. If i have just started how you can expect i will resolve this kind of issue with my own.
https://angular.io/docs/js/latest/guide/displaying-data.html

**Comment by gdi2290** [comment]
in your code, can you change `appInjector` to `hostInjector` (actually soon to be changed to `bindings` in the next release)  

The API changed so I'm not sure if the website is outdated or a problem with the inline source docs

**Comment by ericmartinezr** [comment]
@deepakshrma This will help you https://angular.io/docs/js/latest/api/di/forwardRef-function.html

**Comment by deepakshrma** [comment]
@gdi2290 Thank for the quick reply. However I am not looking for the answer. I already got answer. I want correction in document. As novice, I don't want such issue in initial phase of my learning.

**Comment by mhevery** [comment]
We are working on e2e tests for all examples in the docs. This will catch this error. We are not going to collect one off issues like that, so I am going to close this.
