### ISSUE TITLE
When will angular 9 release？

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular#34523]
Could I use angular 9 in production now？

**Comment by CaerusKaru** [comment]
There is currently no set release date. Please see [this tweet](https://twitter.com/jules_kremer/status/1206645952548720640).

**Comment by spock123** [comment]
@xiaoxiangmoe I am using latest RC in production, I guess it all depends... it's pretty stable now for most people..

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
