### ISSUE TITLE
Validator which relies on multiple form fields

### ISSUE THREAD

**Issue by firecube** [angular/angular#3453]
Is it possible to create a validator which can use multiple values to decide if my field is valid?

e.g. if the customer's preferred contact method is by email then the email field should be required.

Thanks.

**Comment by pkozlowski-opensource** [comment]
@firecube please use an appropriate support channel for those types of questions: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Thnx!

**Comment by firecube** [comment]
Done.  Sorry for posting here.

http://stackoverflow.com/questions/31788681/angular2-validator-which-relies-on-multiple-form-fields
