### ISSUE TITLE
Consider adding `DidActivateGuard` and so on

### ISSUE THREAD

**Issue by benelliott** [angular/angular#34546]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/router

### Description

`CanActivateGuard` and its relatives are handy for implementing speculative navigation functionality such as blocking navigation based on authorisation. But they are less good at updating UI state such as breadcrumbs, because they do not offer a guarantee that the component _will_ be activated after `CanActivate` is called.

This means that in order to implement UI breadcrumbs using router guards correctly, you should keep a reference to "uncommitted" (de-)activation events, which are cancelled if the navigation event cancels or errors, and which are only applied after the navigation actually ends.

### Describe the solution you'd like

For my own project, I ended up implementing this pattern in an abstract guard superclass which exposes methods like `DidActivate`, `DidDeactivate` and so on. These hooks provide a guarantee that they will only be called if the navigation actually completed. But I think it is a concept that could be useful in a more general sense and thus could be considered a new feature for `@angular/router`.

The name "DidActivateGuard" is probably a bit non-sensical as it's not actually _guarding_ anything, but it's just for illustration.

### Describe alternatives you've considered

I have considered implementing breadcrumbs by monitoring router events, but it's hard to keep the code as DRY as with guards.

**Comment by Airblader** [comment]
I'm not speaking in favor or against of this feature, but to comment on the use case:

> I have considered implementing breadcrumbs by monitoring router events, but it's hard to keep the code as DRY as with guards.

In our project we have a breadcrumbs and a breadcrumb component (which you nest) that you use in the routed component. There's a global service the components talk to in order to append and remove the breadcrumbs as the component gets created and destroyed. 

This works really well especially since often breadcrumbs soll contain dynamic data (Home > Projects > Project 123 > Overview) and that data is usually already present in the routed component anyway (eg to also set the window title for which we have another directive working similarly).

**Comment by benelliott** [comment]
@Airblader That sounds quite similar to what I've got, in terms of the `breadcrumbs` outlet component and a singleton service for breadcrumb state. The main difference is that the guard is responsible for adding and removing the breadcrumbs, and part of the reason for this is to decouple the components from their route configuration.

When one of your components passes a breadcrumb config to your service, does it also pass the route that you want it to link to? In that case is there a lot of repeated boilerplate across all your routed components or is this abstracted somehow? For a while I tried a similar approach using a superclass but I didn't like having to add `super` calls in all of my lifecycle hooks.

**Comment by Airblader** [comment]
> When one of your components passes a breadcrumb config to your service, does it also pass the route that you want it to link to?

Yes, indeed. But this isn't an issue to us and solutions for that also exist (eg pipes to get the appropriate link from some object such as the project).

BTW, a not so well known feature of `router-outlet` are its (de)activate events. You could put together your wanted feature (DidActivate, DidDeactivate) using that with a bit of elbow grease (using the generic data field on the route config to define the guard service). 

(Again, this isn't to say this request isn't valid / useful, just a hint)

**Comment by benelliott** [comment]
Thanks, I didn't know about those! Although I think it would be a lot of plumbing if I want this behaviour across different route outlets, it's good to know that they exist.

**Comment by djleonskennedy** [comment]
@benelliott Hi, guard have to prevent route, if you need specific router state use `router events`
https://angular.io/api/router/Router#events

**Comment by benelliott** [comment]
@djleonskennedy I know about events, as mentioned in the OP. In fact I had to use them to implement the workaround I described. My suggestion is to add a `DidActivate` hook in a guard-like way, so that they can be declared as part of the router config.
