### ISSUE TITLE
Keyboard events on div are not fired

### ISSUE THREAD

**Issue by canbax** [angular/angular#34543]
# 🚀 feature request

### Description
I want to add keyboard events to **div** elements. Not **input**. This will be used to implement hotkeys in an application.

There are closed issues that ask exactly the same thing I wanted. I read and couldn't reach a solution. https://github.com/angular/angular/issues/5168 https://github.com/angular/angular/issues/523

### Describe alternatives you've considered
 I can use JQuery. This functionality is implemented there.

**Comment by GuillaumeVerdon** [comment]
Hi !

Did you try using `@HostListener`

https://stackoverflow.com/questions/43157820/angular2-templates-how-to-bind-keydown-arrow-to-whole-div-instead-of-only-contr

Regards

**Comment by canbax** [comment]
see my comment to that answer https://stackoverflow.com/questions/43157820/angular2-templates-how-to-bind-keydown-arrow-to-whole-div-instead-of-only-contr/43158345#comment105096565_43158345

**Comment by indraraj26** [comment]
With Renderer2 you will able to achieve but you will have to add tabIndex in order to listen keydown and keyup event.

press tab then press any key
Here is the example for you : https://stackblitz.com/edit/angular-x5rwzx?file=src%2Fapp%2Fapp.component.ts

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
