### ISSUE TITLE
Schematics - Need to Provide Admin Template and Web App Template 

### ISSUE THREAD

**Issue by prabhakarand7** [angular/angular#34558]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
As of now we have Schematics like dashboard, left menu, tables like that but developer like me expect to get full UI like admin template, basic web page templates.

We can provide more templates as developer wants. I know it's little bit complicated but we need to work on this. If we provide this feature many developers and entrepreneur like our technology, more company they will use our technology 

### Describe alternatives you've considered
If we thing any technology like .Net they are providing more templates to the developers to make their work easy like they are providing lot's of templates with CURD operation, minimual cod elike Entity Framework, Build in UI designs.

So we need to give more on UI designs to users then lot of developer like our Angular Technology

**Comment by santoshyadav198613** [comment]
I think you are referring to Angular/components https://github.com/angular/components

**Comment by Splaktar** [comment]
Yes, this issue should be moved to the Angular Components repo.

**Comment by gkalpak** [comment]
Since I don't have access to move this to `angular/components`, I am going to close this.
Please, open an issue in https://github.com/angular/components.

**Comment by prabhakarand7** [comment]
Sure I'll open this issue in angular components


Thanks
Prabhakaran D
91-7639434464
