### ISSUE TITLE
Adding ng-file-upload to angular 8 app. App stop working on IE11.

### ISSUE THREAD

**Issue by manojmaity** [angular/angular#34559]
We have an angular 8 app. App was properly working upon on IE11 after deployment. We have added a package ng-file-upload, for file uploading. After the package being added, what we observed that app is not working on IE11.

Any help shall be appreciated. 

Thank you!

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
