### ISSUE TITLE
ivy: issue with export * from '3rd-party-library'

### ISSUE THREAD

**Issue by kamilkisiela** [angular/angular#34560]
Angular Compiler v9 has some trouble with:

```ts
// public_api.ts

export { Thing } from './thing.ts';
export * from 'library-from-npm' // <-- this is causing the error. When I comment it out, my app compiles...
```

# 🐞 bug report

### Affected Package
Not sure but the issue might be caused by package @angular/compiler-cli

### Is this a regression?

No idea

### Description

My use case is to export everything from `@apollo/client` library in my own library called `apollo-angular`. I want to improve the Developer Experience. Right now people have to import types from `@apollo/client` and Angular related things from `apollo-angular` but I want them to use only the latter.

## 🔬 Minimal Reproduction
https://github.com/kamilkisiela/angular-9-export-all ([`export * from`](https://github.com/kamilkisiela/angular-9-export-all/blob/master/projects/apollo-angular/src/public-api.ts#L7))

```bash
$ yarn install
$ yarn start
```

## 🔥 Exception or Error
<pre><code>
Compiling apollo-angular : es2015 as esm2015

ERROR in Cannot read property 'length' of undefined
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.7
Node: 10.16.3
OS: darwin x64

Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.7
@angular-devkit/build-angular      0.900.0-rc.7
@angular-devkit/build-ng-packagr   0.900.0-rc.7
@angular-devkit/build-optimizer    0.900.0-rc.7
@angular-devkit/build-webpack      0.900.0-rc.7
@angular-devkit/core               9.0.0-rc.7
@angular-devkit/schematics         9.0.0-rc.7
@ngtools/webpack                   9.0.0-rc.7
@schematics/angular                9.0.0-rc.7
@schematics/update                 0.900.0-rc.7
ng-packagr                         9.0.0-rc.3
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2
</code></pre>

**Comment by petebacondarwin** [comment]
Quick update on this. I debugged into the ngcc processing and found that the problem is when the `TypeScriptReflectionHost` tries to find the declaration of `Observable` which is exported from the `@apollo/client/core` package.

**Comment by kamilkisiela** [comment]
@petebacondarwin thanks for looking at it. If there's something I could help with? Maybe you have an idea of how to fix it, I could do this AST-related logic :)
