### ISSUE TITLE
possible error in the tutorial

### ISSUE THREAD

**Issue by Hardcore-fs** [angular/angular#34562]
https://angular.io/start

when you get down to the section
components "output"
part 3
`export class ProductAlertsComponent {
  @Input() product;
  @Output() notify = new EventEmitter();
}`
should that not say "export class ProductAlertsComponent implements OnInit {"
and if not... there is no other "export class ProductAlertsComponent {"

up until that part the demo works fine, but following the steps after that the demo does not trigger the correct responses

**Comment by gkalpak** [comment]
Good catch!

When a component is generated (as instructed in a previous step), it comes with the `OnInit` interface and empty `constructor()` and `ngOnInit()` method. Since they are not used in this examples, they are "silently" removed (thus the latesr snippet does not include the `imlements OnInit` part.

We should either keep them or explicitly mention in the guide that they can be removed, since they are not used in this component.

**Comment by Hardcore-fs** [comment]
The example does not work…..
best idea would be to  implement a fix to get it working …….

**Comment by gkalpak** [comment]
Could you be more specific? What exactly is not working? What is the expected and what the actual behavior?

**Comment by Hardcore-fs** [comment]
The button action is not functioning,
when you reach that stage the button will not put up the message as per the tutorial for that stage.

**Comment by ajitsinghkaler** [comment]
@gkalpak Should we remove ngOnInit or add a message what do you think is better should we add ngOnInit in the following place for consistency

![Angular - Getting Started with Angular  Your First App](https://user-images.githubusercontent.com/39260684/71616625-3d092e00-2bdd-11ea-9e63-dd770da50cfc.png)

@Hardcore-fs It is working for me can you please tell in detail what is not working for you.

**Comment by gkalpak** [comment]
> Should we remove ngOnInit or add a message what do you think is better

I'll leave it to the docs team to decide :wink:
It depends on what is done in other similar cases in the docs.

**Comment by Hardcore-fs** [comment]
I followed the tutorial exactly adding & removing items...
then when I got to that stage the messages did not display.... on the button click..

Wanted to throw it to some students, but thought i should check it first.....

**Comment by kapunahelewong** [comment]
@ajitsinghkaler a note might be good explaining what @gkalpak said [here](https://github.com/angular/angular/issues/34562#issuecomment-569490453) or that they are unused in the current example. We do often have snippets without all the code from the class in them saying something like "x removed for brevity" or clarity, etc.

@Hardcore-fs could you share a stackblitz of your issue? If we could look at the code, maybe something would stand out.
