### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by suri66** [angular/angular#34565]
### Description

 I tried to use extension .htm instead of .html, but it won't allowing.

WHY?

Below is my code.
```
@Component({
  selector: 'app-root',
  templateUrl: './app.component.htm',
  styleUrls: ['./app.component.less']
})

```
### I am getting this error

```
ERROR in ./app.component.htm 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
<p>
  app component works!
</p>
｢wdm｣: Failed to compile. 

```

**Angular Version:**
<pre><code>

Angular 7

</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by AndrewKushnir** [comment]
Hi @suri66, it looks like you already created a ticket in CLI repo as @ericmartinezr suggested (https://github.com/angular/angular-cli/issues/16540), so I'm closing this ticket. Thank you.
