### ISSUE TITLE
Scroll Position Restore not working while using RouteReuseStrategy

### ISSUE THREAD

**Issue by jigneshInd** [angular/angular#34563]
### Description

Using RouteReuseStrategy for retrieving loaded results using infinite scroll when using browser back button, through its works perfect, but as I have a scenario where I want to clear all stored routes and reset RouteReuseStrategy while the user makes login from popup, so not able reset it while using popup. so anyone can help with this? 

How to reset RouteReuseStrategy manually while using the login popup model and provide a refreshed route?

## 🌍  Your Environment

**Angular Version:**
7.3.9
</code></pre>

**Comment by ajitsinghkaler** [comment]
I think this is a problem with your code. If you can single out the problem and create a Stackblitz example then we can help you otherwise these type of questions are better asked on Stackoverflow with tag Angular there people can better hep you.

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
