### ISSUE TITLE
Multiple canActivate guards problem when one returns undefined or null

### ISSUE THREAD

**Issue by evgenyfedorenko** [angular/angular#34569]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression? 
I am not sure, I discovered it in v8.

### Description

Based on the official angular documentation for [route guards](https://angular.io/guide/router#milestone-5-route-guards):
"If any guard returns false, pending guards that have not completed will be canceled, and the entire navigation is canceled."
This is the interface
```
export declare interface CanActivate {
    canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean | UrlTree> | Promise<boolean | UrlTree> | boolean | UrlTree;
}
```
If the guard returns an `Observable<undefined>` or `Observable<null>` the navigation is not cancelled by the guard. Issue can be only replicated when the route has more than one guard.
That is if one of the guards returns `Observable<undefined> | Observable<null> | undefined | null` and the rest of the guards return `Observable<true> | true` navigation proceeds and completes. I was expecting that `undefined` or `null` guard return value should result in the route NavigationCancel event regardless of the number of guards controlling the route.

I am willing to submit a PR with a fix if it is ok. 
Please, let me know if you need more information.
Thank you.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/can-activate-bug

## 🌍  Your Environment

**Angular Version:**
<pre> <code>
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.2
@angular-devkit/build-angular     0.802.2
@angular-devkit/build-optimizer   0.802.2
@angular-devkit/build-webpack     0.802.2
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.3.19
@angular/cdk                      7.3.7
@angular/cli                      8.3.19
@ngtools/webpack                  8.2.2
@schematics/angular               8.3.19
@schematics/update                0.803.19
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0
</code></pre>

**Comment by Airblader** [comment]
These should both throw an error since neither one is allowed by the type signature of the guard.

**Comment by LayZeeDK** [comment]
For reference, setting `compilerOptions.strictNullChecks` or `compilerOptions.strict` to `true` in `tsconfig.json` breaks the build when returning `Observable<null | undefined> | Promise<null | undefined> | null | undefined` in `canActivate`.

**Comment by atscott** [comment]
It appears this behaves as expected; Observable<null> and Observable<undefined> are not supported per the method signature. As @LayZeeDK mentioned, try turning strict null checks on for your project.
