### ISSUE TITLE
CSS variable defined with !important flag disappears in angular production mode

### ISSUE THREAD

**Issue by MiselKING** [angular/angular#34561]
# 🐞 bug report

### Is this a regression?
I don't think so, I tried this in both Angular 7 and Angular 8 and the issue was present on both versions.

### Description

There is an issue with CSS variable (defined using `var()` syntax) with `!important` flag disappearing when Angular project is build in production mode (using `ng build --prod`). Specifically, in my `scss` file I have something like this:
```ts
.all-borders {
  border: 3px solid var(--primary) !important;
  // in "development" build this is correctly compiled to:  "border:1px solid var(--primary)!important"
  // in "production" build this is incorrectly compiled to: "border:1px solid!important"
}

.window {
  height: 100px;
  width: 100px;
  background-color: cadetblue;
}
```
and in `html` file I have defined a simple `div` element like this:
```ts
<div class="all-borders window"></div>
```
and when I run `ng serve` (so build in `dev` mode) I can see that border is correctly compiled and applied on my `div` element. But, when I build in `prod` mode then my border becomes black and I can see in inspector that style has been compiled to `border: 1px solid!important` (notice that `var(...)` disappeared).

Weirdly enough, writing _border_ style like this `border: var(--primary) 1px solid !important` works fine so this looks like a problem with CSS variable next to `!important` flag in shorthand property.

## 🔬 Minimal Reproduction

How it looks in _dev_ mode:
https://stackblitz.com/edit/angular-h6utmv

How it looks in _prod_ mode:
https://test-border-right-css-vars.firebaseapp.com/

To reproduce just check the border color on the _div_ element, it should be orange but in production version it is black.

## 🔥 Exception or Error
<pre><code>
There is no exception, this is just a weird and unexpected behavior.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.21
Node: 12.8.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.21
@angular-devkit/build-angular     0.803.21
@angular-devkit/build-optimizer   0.803.21
@angular-devkit/build-webpack     0.803.21
@angular-devkit/core              8.3.21
@angular-devkit/schematics        8.3.21
@angular/cli                      8.3.21
@ngtools/webpack                  8.3.21
@schematics/angular               8.3.21
@schematics/update                0.803.21
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

I don't think this is browser specific since I tested in both Chrome v79.0.3945.88 and Firefox v71.0 and the issue was present on both versions.

**Comment by loadingwyn** [comment]
I meet this problem too

**Comment by neofuture** [comment]
This is the same issue 

https://github.com/angular/angular-cli/issues/16123

**Comment by MiselKING** [comment]
Yes, you are right. I will close this issue and let's track progress there (from what I see it should be fixed in Angular v9)...
