### ISSUE TITLE
input type file with change action can send the right index

### ISSUE THREAD

**Issue by dbdel** [angular/angular#34579]
I have an issue with angular version 8, this problem is the same in the version 6, when i use input type file in an ngfor loop the method in the change action in the input file always retrieve the index as zero.

<li  *ngFor="let file of files; let i = index">
<input type="file" name="addPiece" id="addPiece" (change)="uploadFile($event,i)">
</li>

When i log the i in the typescript file i always get 0 whenever i click

**Comment by ajitsinghkaler** [comment]
Can you please create an isolation of this on stackblitz

**Comment by dbdel** [comment]
It was an issue due to input type file with a label for styling the icon, i had to change dynamically the name and the for attribute with the same value for getting it work
