### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by ahmedfou** [angular/angular#34576]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

when i run ng build --prod iv got this problem

 10% building 3/7 modules 4 active ...le-line-icons\css\simple-line-icons.cssBrowserslist: caniuse-lite is outdated. Please run next command `npm update`
 90% chunk assets processing
<--- Last few GCs --->

[8248:000002039B6BE9E0]   209164 ms: Mark-sweep 1333.3 (1427.0) -> 1332.7 (1426.5) MB, 725.7 / 0.0 ms  (average mu = 0.130, current mu = 0.030) allocation failure scavenge might not succeed
[8248:000002039B6BE9E0]   209919 ms: Mark-sweep 1333.7 (1426.5) -> 1332.9 (1426.5) MB, 741.3 / 0.0 ms  (average mu = 0.077, current mu = 0.019) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0000005017FDC5C1]
Security context: 0x03d1a171e6e9 <JSObject>
    1: __nestBlockScope [0000030FB6382689] [C:\axeane_project\ge-commerciale-fr\node_modules\eslint-scope\lib\scope-manager.js:~204] [pc=000000501C4CA5DE](this=0x027b62bcf8c9 <ScopeManager map = 000000622135E141>,node=0x020d791d19a9 <Node map = 000000C6C2B9D589
>)
    2: BlockStatement [0000031264AFF821] [C:\axeane_project\ge-commerciale-fr\node_modules\esl...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6B0A2F04A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+5114
 2: 00007FF6B0A0A0C6 node::MakeCallback+4518
 3: 00007FF6B0A0AA30 node_module_register+2032
 4: 00007FF6B0C920EE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF6B0C9201F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF6B11B2BC4 v8::internal::Heap::MaxHeapGrowingFactor+9556
 7: 00007FF6B11A9C46 v8::internal::ScavengeJob::operator=+24310
 8: 00007FF6B11A829C v8::internal::ScavengeJob::operator=+17740
 9: 00007FF6B11B0F87 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF6B11B1006 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF6B0D6CDB7 v8::internal::Factory::NewFillerObject+55
12: 00007FF6B0E02CC6 v8::internal::WasmJs::Install+29414
13: 0000005017FDC5C1

C:\axeane_project\ge-commerciale-fr>

any solution plz i am stack here

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by ericmartinezr** [comment]
Please open this issue in [angular-cli's repo](https://github.com/angular/angular-cli), and also see the already existing ones https://github.com/angular/angular-cli/search?q=JavaScript+heap+out+of+memory&type=Issues

**Comment by AndrewKushnir** [comment]
Hi @ahmedfou, as @ericmartinezr mentioned, there are some existing issues in [angular-cli's repo](https://github.com/angular/angular-cli) that describe similar errors. Please look at existing issues there to see if you can find a solution. If not, please open a ticket in [CLI repo](https://github.com/angular/angular-cli), so that the team can look into that. Thank you.
