### ISSUE TITLE
Inlined SVG animation don't listen 'duration' attribute.

### ISSUE THREAD

**Issue by xuxicheta** [angular/angular#34575]
### Description
Inlined svg not respond on 'duration' attribute

## 🔬 Minimal Reproduction
Here is a normal svg spinner https://jsfiddle.net/melchiorio/2Lh4rext/

I want to use it in inlined-svg component. 

And then https://stackblitz.com/edit/angular-dhur2u

git repo https://github.com/xuxicheta/svg-no-duration

## 🌍  Your Environment
**Angular Version:**
8.3.21

**Anything else relevant?**
In Firefox all is ok.

**Comment by pkozlowski-opensource** [comment]
This appears to be fixed in the latest Angular 9.x running ivy: https://stackblitz.com/edit/angular-5wketj?file=src%2Fapp%2Fapp.module.ts

One can see that it was View Engine specific bug by switching between ivy and VE in the settings.
