### ISSUE TITLE
Angular service worker keeps refreshing browser on visiting in production build

### ISSUE THREAD

**Issue by kolllor33** [angular/angular#34578]
# 🐞 bug report

### Description

After implementing the angular service worker and pwa than building my project in production With
ng build --prod. If I serve my code on firebase hosting or with http-server the service worker is getting registered but the page keeps reloading.

## 🔬 Minimal Reproduction
You can visit the site: [https://calender-manager.firebaseapp.com](https://calender-manager.firebaseapp.com) to see the "bug" in action
The code of the project you can find here: [github](https://github.com/kolllor33/calnedarManager/tree/masterGithub)

## 🌍  Your Environment

**Angular Version:**
<pre>Angular CLI: 8.3.20
Node: 10.16.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.20
@angular-devkit/build-angular     0.803.21
@angular-devkit/build-optimizer   0.803.21
@angular-devkit/build-webpack     0.803.21
@angular-devkit/core              8.3.20
@angular-devkit/schematics        8.3.20
@angular/cli                      8.3.20
@angular/fire                     5.2.3
@angular/pwa                      0.803.21
@ngtools/webpack                  8.3.21
@schematics/angular               8.3.20
@schematics/update                0.803.20
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2</pre>

**Comment by ajitsinghkaler** [comment]
Can you please isolate this issue to make sure that that this is an angular problem, not your code problem
