### ISSUE TITLE
ngIf with async pipe causes new template type checking errors when template variables are used in rc.5

### ISSUE THREAD

**Issue by Splaktar** [angular/angular#34572]
# 🐞 bug report

### Affected Package
`@angular/common`

### Is this a regression?

Yes, it wasn't an issue in Angular `9.0.0-rc.4`.

#### Template
```html
<ng-container *ngIf="componentViewer.componentDocItem | async; let docItem">
  <span class="cdk-visually-hidden" tabindex="-1" #initialFocusTarget>
    Examples for {{docItem.id}}
  </span>
  <example-viewer *ngFor="let example of docItem.examples"
                  [example]="example"></example-viewer>
</ng-container>
```
There are errors for
```
src/app/pages/component-viewer/component-examples.html:3:20 - error TS2531: Object is possibly 'null'.

3     Examples for {{docItem.id}}
                     ~~~~~~~~~~

  src/app/pages/component-viewer/component-viewer.ts:132:16
    132   templateUrl: './component-examples.html',
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ComponentExamples.
src/app/pages/component-viewer/component-examples.html:5:34 - error TS2531: Object is possibly 'null'.

5   <example-viewer *ngFor="let example of docItem.examples" [example]="example"></example-viewer>
                                   ~~~~~~~~~~~~~~~~

  src/app/pages/component-viewer/component-viewer.ts:132:16
    132   templateUrl: './component-examples.html',
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ComponentExamples.
```

#### Solutions?

It's complaining about `docItem.id` and `docItem.examples` where `docItem` might be `null` in these cases. But it seems to be ignoring the fact that this template won't be rendered if `docItem` is `null`. It appears that the type narrowing is not working properly in this case?

The tests in PR https://github.com/angular/angular/pull/33997 don't cover the use case where the Async Pipe is used with `let`. But `<ng-container *ngIf="componentViewer.componentDocItem | async as docItem">` also seems to trigger this error.

How do you recommend developers solve this very common use case?
- Answer so far is that this is a bug that needs to be resolved for `v9`.

## 🔬 Minimal Reproduction
Here is the [workaround](https://github.com/angular/material.angular.io/commit/f813cc6d0c12bc52dab5237922403fcde4108e72) that I had to apply to get our repo building again after the breaking change in Angular `9.0.0-rc.5`. 

## 🔥 Exception or Error
```
src/app/pages/component-viewer/component-examples.html:3:20 - error TS2531: Object is possibly 'null'.

3     Examples for {{docItem.id}}
                     ~~~~~~~~~~

  src/app/pages/component-viewer/component-viewer.ts:132:16
    132   templateUrl: './component-examples.html',
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ComponentExamples.
src/app/pages/component-viewer/component-examples.html:5:34 - error TS2531: Object is possibly 'null'.

5   <example-viewer *ngFor="let example of docItem.examples" [example]="example"></example-viewer>
                                   ~~~~~~~~~~~~~~~~

  src/app/pages/component-viewer/component-viewer.ts:132:16
    132   templateUrl: './component-examples.html',
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ComponentExamples.
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.6
Node: 12.13.0
OS: darwin x64

Angular: 9.0.0-rc.7
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.6
@angular-devkit/build-angular      0.900.0-rc.6
@angular-devkit/build-optimizer    0.900.0-rc.6
@angular-devkit/build-webpack      0.900.0-rc.6
@angular-devkit/core               9.0.0-rc.6
@angular-devkit/schematics         9.0.0-rc.6
@angular/cdk                       9.0.0-rc.5
@angular/cdk-experimental          9.0.0-rc.5
@angular/cli                       9.0.0-rc.6
@angular/components-examples       9.0.0-rc.5-sha-8796d7cc6
@angular/google-maps               9.0.0-rc.5
@angular/material                  9.0.0-rc.5
@angular/material-experimental     9.0.0-rc.5
@angular/material-moment-adapter   9.0.0-rc.5
@angular/youtube-player            9.0.0-rc.5
@ngtools/webpack                   9.0.0-rc.6
@schematics/angular                9.0.0-rc.6
@schematics/update                 0.900.0-rc.6
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2
</code></pre>

**Anything else relevant?**

@JoostK has been investigating this and has posted some comments about this here
- https://github.com/angular/material.angular.io/pull/689#issuecomment-566371176
- https://github.com/angular/material.angular.io/pull/689#issuecomment-567629433

**Comment by alexzuza** [comment]
I've added support for TypeScript strict options for Ivy on ng-run.com


Reproduction:

[Ivy 9.0.0-rc.7 ](https://ng-run.com/edit/KBXlhimru6BCig38hdP5?aot=true)

**__ng_typecheck__.ts**
```
import * as i1 from '@angular/common';


var _pipe1: i1.AsyncPipe = (null!);
const _ctor1: <T = unknown>(init: Pick<i1.NgIf<T>, "ngIf" | "ngIfThen" | "ngIfElse">) => i1.NgIf<T> = (null!);

/*tcb1*/
function _tcb1(ctx: i0.AppComponent) { if (true) {
    var _t1 = document.createElement("h2") /*0,18*/;
    "" + (ctx).name /*26,30*/;
    var _t2 = _ctor1({ "ngIf": (_pipe1.transform((ctx).obs$ /*60,65*/) /*60,73*/) /*53,80*/, "ngIfThen": (null as any), "ngIfElse": (null as any) }) /*39,81*/;
    var _t3: any = (null!);
    if (i1.NgIf.ngTemplateContextGuard(_t2, _t3) /*39,81*/ && _pipe1.transform((ctx).obs$ /*60,65*/) /*60,73*/ /*ignore*/) {
        var _t4 = _t3.ngIf /*53,80*/;
        var _t5 = document.createElement("ng-container") /*39,81*/;
        "" + (_t4 /*87,90*/).id /*87,94*/; // Object is possibly 'null'
    }
} }

export const IS_A_MODULE = true;
```

[Ivy 9.0.0-rc.4 ](https://ng-run.com/edit/GvVB2FTcC5OrIOH2bFL0?aot=true)

**__ng_typecheck__.ts**

```
import * as i1 from '@angular/common';


var _pipe1: i1.AsyncPipe = (null!);
const _ctor1: (init: Pick<i1.NgIf, "ngIf" | "ngIfThen" | "ngIfElse">) => i1.NgIf = (null!);

/*tcb1*/
function _tcb1(ctx: i0.AppComponent) { if (true) {
    var _t1 = document.createElement("h2") /*0,18*/;
    "" + (ctx).name /*26,30*/;
    var _t2 = _ctor1({ "ngIf": (_pipe1.transform((ctx).obs$ /*53,58*/) /*53,66*/) /*53,80*/, "ngIfThen": (null as any), "ngIfElse": (null as any) }) /*39,81*/;
    var _t3: any = (null!);
    if (_pipe1.transform((ctx).obs$ /*53,58*/) /*53,66*/) {
        var _t4 = _t3.ngIf /*53,80*/;
        var _t5 = document.createElement("ng-container") /*39,81*/;
        "" + (_t4 /*87,90*/).id /*87,94*/;
    }
} }

export const IS_A_MODULE = true;
```

**Comment by alxhub** [comment]
I'm bouncing this over to `comp: common`. The compiler's type-checking is correct here; the issue is that `NgIf`'s type is not quite covering this use case. As was pointed out above, @JoostK has some ideas on how to fix this.

**Comment by vladimiry** [comment]
I'm facing the same issue having enabled all the extended strict template compilations options (I didn't check which exact flag is responsible for the discussed check since I want all of them to be enabled).

```typescript
type StrictTemplateOptions
                    = NoExtraProperties<Required<import("@angular/compiler-cli/src/ngtsc/core/api").StrictTemplateOptions>>;
const strictTemplateOptions: StrictTemplateOptions = {
	strictAttributeTypes: true,
	strictContextGenerics: true,
	strictDomEventTypes: true,
	strictDomLocalRefTypes: true,
	strictInputTypes: true,
	strictNullInputTypes: true,
	strictOutputEventTypes: true,
	strictSafeNavigationTypes: true,
	strictTemplates: true,
};
```

> Here is the workaround that I had to apply to get our repo building again after the breaking change in Angular 9.0.0-rc.5.

There is another ugly workaround (using 2 `ngIf` checks):
```html
<ng-container *ngIf="componentViewer.componentDocItem | async; let docItem">
    <ng-container *ngIf="docItem">
	  <span class="cdk-visually-hidden" tabindex="-1" #initialFocusTarget>
		Examples for {{docItem.id}}
	  </span>
        <example-viewer *ngFor="let example of docItem.examples"
                        [example]="example"></example-viewer>
    </ng-container>
</ng-container>
```

**Comment by IMM9O** [comment]
I'm facing the same issue

**Comment by thw0rted** [comment]
Just to be clear, because I haven't had a chance to test all the permutations, `*ngIf="foo"` means that in the embedded view, `foo` will be narrowed to exclude `undefined` / `null`, but `*ngIf="foo$ | async; let foo` *should* narrow but doesn't.  Is that right?

**Comment by vladimiry** [comment]
Can confirm issue resolving in 9.0.5, thanks @JoostK.
