### ISSUE TITLE
cursor position issue

### ISSUE THREAD

**Issue by kudeshiyah** [angular/angular#34588]
[package.zip](https://github.com/angular/angular/files/4007523/package.zip)

Hey Team
we are facing the weird issue:-

https://www.loom.com/share/ca7a8f08da064a5ebc6d5b223f1f9d5c
when dragging the card
1. cursor moves far from card as i drag to right
2. its not scrolling to right, so that i can drop it in hidden board

somewhat same issue is here
https://www.loom.com/share/c0c06628b7bb4c2aaef5803893694cde
1. i started from left, as i m moving to right cursor is moving far from current position

this issue is only coming in chrome
package.json added, plz help

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
