### ISSUE TITLE
unexpected server building otput

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular#34593]
I'm using Angular universal whitch uses express.
so a 'server.ts' file is created in my project's root.

when I run  `webpack --config webpack.server.config.js` it creates `dist/server.js` contains my express code as expected, but it also contains too many codes related to webpack (as I think) that is not exists in my server.ts file, causing that the outputted file (i.e dist/server.js) is too much big.

and this is my [repo](https://github.com/goblins-tech/almogtama3)

**Comment by sonukapoor** [comment]
Hello, the issue doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag angular.

If you are wondering why we don't resolve support issues via the issue tracker, please check out this [explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
