### ISSUE TITLE
Location now uses PlatformLocation directly for the new getState() api instead of going through LocationStrategy.

### ISSUE THREAD

**Issue by statop** [angular/angular#34603]
# 🐞 bug report

### Affected Package
@angular/router

### Is this a regression?

yes

### Description

Location now uses PlatformLocation directly for the new getState() api instead of going through LocationStrategy.

See https://github.com/angular/angular/blob/8.0.x/packages/common/src/location/location.ts#L95

Prior to version 8 LocationStrategy was the api to implement to customize how the router stored/manipulated the url and state.

Now you must wrap PlatformLocation somehow in addition to providing a LocationStrategy.

This breaks the api contract that was implied.

## 🔬 Minimal Reproduction
none

## 🔥 Exception or Error
none

## 🌍  Your Environment

**Angular Version:**
7, upgrading to 8

**Anything else relevant?**

I suggest you add getState to LocationStrategy.

**Comment by atscott** [comment]
Hi @statop, can you explain a bit more what your use-case is here?  What are you doing with Location that requires it to not depend on `PlatformLocation` directly? If I understand correctly, you're suggesting we instead call `getState` through `LocationStrategy`, which would in turn call `PlatformLocation.getState`.

**Comment by statop** [comment]
Yes, that is what I'm suggesting. 

It's not just my use case that needs this change, it's use cases that are very common-

- mocking the location strategy
- Implementing a custom location strategy

**Comment by IgorMinar** [comment]
I think this is legit. `LocationStrategy` should be the place to control all `window.location` interactions.

Specifically the following apis should be used by Location:
- `LocationStrategy#pushstate` - https://next.angular.io/api/common/LocationStrategy#pushstate
- `LocationStrategy#replacestate` - https://next.angular.io/api/common/LocationStrategy#replacestate

@statop this should be a relatively small change, would you be interested in [contributing it](https://github.com/angular/angular/blob/master/CONTRIBUTING.md)?

**Comment by atscott** [comment]
Fixed by https://github.com/angular/angular/pull/45648
