### ISSUE TITLE
Allow angular elements to extend other element classes

### ISSUE THREAD

**Issue by Hypercubed** [angular/angular#34607]
# 🚀 feature request

### Relevant Package
Requesting changes to @angular/elements

### Description
The custom elements API for `customElements.define` supports extending elements other than `HTMLElement` using the `extends` option.  For example:

```
class WordCount extends HTMLParagraphElement {
  ...
}
customElements.define('word-count', WordCount, { extends: 'p' });
```

can be invoked in HTML as:

```
<p is="word-count"></p>
```

However, this will not work with angular elements since the `createCustomElement` method, by design, generates a custom element that extends from `HTMLElement`.

### Describe the solution you'd like
I am requesting the ability to pass a base class to `createCustomElement` to support extending other elements.  Possible API:

```
const WordCount= createCustomElement(WordCountComponent, {injector, extends: HTMLParagraphElement});
customElements.define('word-count', WordCount, { extends: 'p' });
```

### Describe alternatives you've considered
For the most part extending `HTMLElement` is fine for most components.  However, in several cases there is an advantage to extending other base classes.  Two I can think of are `<template>` and `<a>`.  With with these we could do amazing things like:

```
<template is="syntax-highlighter"> ... </template>
<a is="router-link" router-link="...">...</a>
```

### PS
Looking at the angular elements code I don't see any technical reason this cannot be supported.  I'm willing and able to submit a PR if there is support for this feature.

**Comment by gkalpak** [comment]
For reference, #42427 has some relevant discussion (esp. https://github.com/angular/angular/issues/42427#issuecomment-855004310).

**Comment by gkalpak** [comment]
Thank you for submitting this feature request. We reviewed it and decided not to move forward with it.

The fact that a major browser does not support the feature is a significant downside. Additionally, given the low demand for this feature and the higher priority of other work, we are unlikely to get to it in the foreseeable future.

(We might revisit this decision if browser-support or user demand change in the future.)
