### ISSUE TITLE
App-Shell/Ivy: Cannot read property 'moduleType' of undefined

### ISSUE THREAD

**Issue by EigenTheory** [angular/angular#34601]
# 🐞 bug report

### Affected Package

ng run **`project-name`**:app-shell
ng run **`project-name`**:app-shell:production

### Is this a regression?

This has never worked for me anytime I have tried to enable Ivy.

### Description

When generating a new Angular application with `--enableIvy` and adding the app shell, the application fails to load.

- This occurs for both `dev` and `prod` builds.
- This goes away if building a project without `--enableIvy`.

## 🔬 Minimal Reproduction

`ng new repro-app --enableIvy --routing --style=scss`
`ng generate app-shell --client-project repro-app --universal-project server-app`
`ng run repro-app:app-shell`

https://github.com/EigenTheory/repro-app/

## 🔥 Exception or Error
`Cannot read property 'moduleType' of undefined`

![image](https://user-images.githubusercontent.com/1594192/71601582-aa538b00-2b19-11ea-8498-ee6b3348934e.png)

## 🌍  Your Environment

**Angular Version:**
![image](https://user-images.githubusercontent.com/1594192/71602073-05867d00-2b1c-11ea-94c1-2e398b4ed8b8.png)

**Anything else relevant?**

**Comment by AndrewKushnir** [comment]
Hi @EigenTheory, thanks for reporting the issue. Could you please try to reproduce the issue with the most recent RC version (`9.0.0-rc.7`) and let us know if the problem still exists? Thank you.

**Comment by alan-agius4** [comment]
This should be addressed in Angular FW and Angular-CLI version 9. 

Try updating using 
```
ng update @angular/core @angular/cli —-next
```

**Comment by EigenTheory** [comment]
I will give this a try and update accordingly! Thanks!

**Comment by EigenTheory** [comment]
Does setting the compiler option `--enableIvy` no longer work?

This doesn't work anymore...
`ng new repro-app --enableIvy --routing --style=scss`

Error: **`Unknown option: '--enableIvy'`**

**Comment by alan-agius4** [comment]
@EigenTheory, `enableIvy` flag is not longer provided with `ng new` command as now Ivy is the default.

**Comment by EigenTheory** [comment]
Confirmed this is FINALLY working in `9.0.0-rc.7`!

**Comment by EigenTheory** [comment]
Confirmed this is FINALLY working in `9.0.0-rc.7`!
