### ISSUE TITLE
Dynamic loaded routes not working with Ivy

### ISSUE THREAD

**Issue by wilzad** [angular/angular#34609]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Its working fine with <code>"enableIvy": false</code>

### Description

 I am trying to load two modules based on the browser user agent, for mobile i will load the mobile compatible module and for desktop, the desktop compatible one. i did this by injecting the routes using a factory method to the ROUTES provider (i inject the user agent via nodejs in case of server side), without ivy this is working fine, but when Ivy enabled, i am getting error: Invalid configuration of route ''. One of the following must be provided: component, redirectTo, children or loadChildren. seems like the factory method never called to get the routes. 

## 🔬 Minimal Reproduction

 https://github.com/wilzad/ivydynamicloading

## 🔥 Exception or Error
<pre><code>

Error: Invalid configuration of route ''. One of the following must be provided: component, redirectTo, children or loadChildren
    at validateNode (router.js:1273)
    at validateConfig (router.js:1228)
    at Router.resetConfig (router.js:7297)
    at new Router (router.js:6797)
    at Object.setupRouter [as useFactory] (router.js:9799)
    at Object.factory (core.js:17000)
    at R3Injector.hydrate (core.js:16831)
    at R3Injector.get (core.js:16598)
    at injectInjectorOnly (core.js:734)
    at Module.ɵɵinject (core.js:744)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.21
Node: 12.13.0
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.21
@angular-devkit/build-angular              0.803.21
@angular-devkit/build-optimizer            0.803.21
@angular-devkit/build-webpack              0.803.21
@angular-devkit/core                       8.3.21
@angular-devkit/schematics                 8.3.21
@angular/cli                               8.3.21
@ngtools/webpack                           8.3.21
@nguniversal/express-engine                8.2.6
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        8.3.21
@schematics/update                         0.803.21
rxjs                                       6.4.0
typescript                                 3.5.3
webpack                                    4.39.2

</code></pre>

**Anything else relevant?**

**Comment by tieppt** [comment]
Your code is wrong. Remove useValue, then it should work.
![image](https://user-images.githubusercontent.com/7151365/71714029-c3707a80-2e3e-11ea-8544-e1c8949579ce.png)

**Comment by wilzad** [comment]
Thanks, It worked
