### ISSUE TITLE
SSR server runtime error

### ISSUE THREAD

**Issue by ksuhiyp** [angular/angular#34608]
@nguniversal/express-server

I am not able to run SSR server due to the following errors, I've attached the main.js file and the error log

Steps I've followed to produce main build
`npm run build:ssr`

error when running the server were
```
`/home/suhayb/repos/hisas/web-app/dist/web-app-server/main.js:4680
dayjs_1.default.extend(relativeTime_1.default);
                ^
TypeError: Cannot read property 'extend' of undefined
```
[2020-01-02T01_13_15_068Z-debug.log](https://github.com/angular/angular/files/4014732/2020-01-02T01_13_15_068Z-debug.log)

[main.zip](https://github.com/angular/angular/files/4014729/main.zip)

**Comment by ksuhiyp** [comment]
[conf files.zip](https://github.com/angular/angular/files/4014740/conf.files.zip)

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
