### ISSUE TITLE
Possible typo in Tour of Heros (toh-pt4)

### ISSUE THREAD

**Issue by omahane** [angular/angular#34612]
# 📚 Docs or angular.io bug report

### Description

Currently, the "Tour of Heroes" services page (toh-pt4) says:

> Instead of creating that service with new, you'll rely on Angular dependency injection to inject it into the HeroesComponent constructor. 

In the first phrase, the "new" does modify any other word, which it should. I don't quite know what it should say but "new [something]."

### What's the affected URL?**
 https://angular.io/tutorial/toh-pt4

### Reproduction Steps**

Visit the page.
Find the 2nd paragraph under "Why Services"
Read the 2nd sentence

### Expected vs Actual Behavior**

It should say but "new [something]."

## 📷Screenshot

![Screenshot 2020-01-02 07 33 46](https://user-images.githubusercontent.com/766573/71669432-43f58500-2d32-11ea-879c-7134c6245dc0.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by axrae** [comment]
It means that the service is injected as opposed to being manually instantiated with the `new` keyword. It's not exactly wrong, but I certainly see how the sentence or lack of formatting could be confusing.

**Comment by sonukapoor** [comment]
Is that better?

> Instead of using an object initializer (`const service = new HeroService()`) to create the service,
you'll rely on Angular [*dependency injection*](guide/dependency-injection) to inject it into the `HeroesComponent` constructor.

**Comment by omahane** [comment]
It makes sense that “new” is a keyword in that sentence. 
I wondered about that.
