### ISSUE TITLE
Spread operator argument not supported by static module functions

### ISSUE THREAD

**Issue by Noeldesarrollo** [angular/angular#34615]
Due to lack of support for basic operations inside static module functions (using AOT mode). It's not posible to use spread operator. Desired behaviour is:
![image](https://user-images.githubusercontent.com/12170049/71679853-de80b300-2d88-11ea-974a-e3723c74a965.png)

**Comment by alxhub** [comment]
Which version of Angular are you using?

**Comment by Noeldesarrollo** [comment]
> Which version of Angular are you using?

I'm using 7.2 version

**Comment by JoostK** [comment]
Although the issue is a bit light on details, this is no longer an issue in Ivy as of Angular 9.0.
