### ISSUE TITLE
ToFixed() method not working properly

### ISSUE THREAD

**Issue by kuldeep738** [angular/angular#34628]
When we code like (5.15).toFixed(1) it will return 5.1 instead of 5.2 and same case in 5.55 it will return 5.5. Instead of 5.6 , we can put any thing at integer part the issue is only at decimal point

**Comment by JoostK** [comment]
I'm sorry but this issue is not caused by Angular. [This is standard browser API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed), not Angular behavior.
