### ISSUE TITLE
Remove ViewSplitter from pre-compiled apps

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#3462]
It should run as part of transformer and not an runtime.

**Comment by rolandjitsu** [comment]
@yjbanov does this and others ([3461](https://github.com/angular/angular/issues/3461), [3460](https://github.com/angular/angular/issues/3460), [3459](https://github.com/angular/angular/issues/3459)) apply to Dart apps only, or will this be working with TS apps as well?

**Comment by yjbanov** [comment]
@rolandjitsu with the issues in question we are tackling Dart initially, but these is no reason why similar pre-compilation cannot be done for TS in the future.

**Comment by mhevery** [comment]
I think #3605 will make this issue obsolete. @tbosch can you confirm and close as dup?

**Comment by tbosch** [comment]
Yes, and we will remove even more: the template parser, the code for generating change detection, ...

**Comment by yjbanov** [comment]
Two things need to be done:

1. stop using it
1. don't include it in the app code

Both require explicit effort. Will #3605 fix both? If so, feel free to reclose this issue.

**Comment by tbosch** [comment]
After my change we will only use it during transformation.
And it should get correctly tree shaken as well.

**Comment by yjbanov** [comment]
Cool. Let's keep this issue open to make sure it actually is tree shaken (I doubt it will happen automatically). Marking as blocked by #3605.

**Comment by tbosch** [comment]
We don't have the class `ViewSplitter` in our codebase any more...
