### ISSUE TITLE
inconsistent __processed_by_ivy_ngcc__ order breaks caching

### ISSUE THREAD

**Issue by jbedard** [angular/angular#34635]
# 🐞 bug report

### Affected Package
`@angular/*`, `@angular/bazel` users especially

### Is this a regression?

Yes, in ivy at least.

### Description

#32427 made the `ngcc` tasks run in parallel (FYI @gkalpak 👋). I assume this is what causes the `__processed_by_ivy_ngcc__` entries in `package.json` to be defined in a random order, causing inconsistent `package.json` content. Tools such as bazel which use file hashes for caching purposes will then get cache misses (almost) every time `ngcc` runs on a package.

## 🔬 Minimal Reproduction

Run `yarn install` a couple times and observe the `package.json` files being inconsistent.

If using bazel you can use `--execution_log_json_file=executions.log` on a clean build a few times and see the difference, the hashes of many `@angular/*` `package.json` files changes.

**Angular Version:**

9.0.0-rc.7, I think it also existed back to rc.0 and earlier.

**Comment by petebacondarwin** [comment]
@jbedard - can you give some more details of what you mean by "causing inconsistent package.json content."? What is different in the content per run? Each `package.json` should only be touched once, whether ngcc is running in parallel mode or not.

Are you saying that the order of the entry-points within the `__processed_by_ivy_ngcc__` is different? If so, then a simple fix might be to sort these entry-points alphabetically to ensure they are stable?

**Comment by gkalpak** [comment]
Yes, that's what's happening. The fix is indeed to sort the properties in `__processed_by_ivy_ngcc__` alphabetically. (I was going to work on this today.)

**Comment by jbedard** [comment]
Yeah that's correct, and simply sorting them before writing to package.json would fix it.

@petebacondarwin each package.json is touched once per fresh node_modules. Locally that's not often, but across machines it is. So a bazel cache shared between devs becomes useless (or at least not a "shared" cache anymore). Or in our case our CI didn't retain any state between runs so there was a fresh node_modules between runs, and those npm packages are near the root of the dep tree so them changing breaks almost all caching...

**Comment by gkalpak** [comment]
I was a little reluctant to order everything alphabetically (and thus modify the `package.json`s so significantly), so I implemented a more conservative approach in #34870, ensuring that the relative properties added to mark an entry-point as processed is deterministic (i.e. independent of the order in which each format's processing completes).

If you want to try it out, you can get the build artifacts from [here][1], @jbedard.
<sub>(Instructions on how to use them can be found [here][2].)</sub>

[1]: https://circleci.com/gh/angular/angular/591403#artifacts/containers/0
[2]: https://github.com/angular/angular/blob/e0ad9ecda/docs/DEVELOPER.md#getting-packages-from-build-artifacts
