### ISSUE TITLE
Ivy doesn't pick up translation files

### ISSUE THREAD

**Issue by fetis** [angular/angular#34633]
# 🐞 bug report

### Affected Package
probably `@angular/localize`

### Is this a regression?
in comparison to v8, yes

### Description

I'm not sure is it a bug or problem with my configuration. I'm testing new translation features from v9 and set up a  small application following this guide https://next.angular.io/guide/i18n#merge-the-completed-translation-file-into-the-app

I don't have any error but the compiler says that translation is missed for all string, despite the fact that I provided xlf-file with translation. 

Another interesting observation is that string ids are different from the specified in xlf-files, even the string with the fixed id `resetButton` has another id `"resetButton␟878de3ad44e634ecaf219427d948689bd975e1af␟1029122298839770722"` in the message.

It looks like ids change every build and that's probably the reason why compuler is unable to find translations, but it's only my gues

## 🔬 Minimal Reproduction
Here's the test application I'm playing with
https://github.com/fetis/ng9translation

Try `ng serve -c=ru` to see the problem. The locale is set to Russian but none of the strings are translated.

The same result for `ng build --prod` or `ng build -c=ru`

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 9.0.0-rc.7
Node: 12.4.0
OS: darwin x64

Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.7
@angular-devkit/build-angular     0.900.0-rc.7
@angular-devkit/build-optimizer   0.900.0-rc.7
@angular-devkit/build-webpack     0.900.0-rc.7
@angular-devkit/core              9.0.0-rc.7
@angular-devkit/schematics        9.0.0-rc.7
@angular/localize                 9.0.0-rc.0
@ngtools/webpack                  9.0.0-rc.7
@schematics/angular               9.0.0-rc.7
@schematics/update                0.900.0-rc.7
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

**Comment by mstawick** [comment]
I had the same problem. It turned out that `ng add` added some old rc0 version of @angular/localize. Upgrading to rc7 fixed the issue for me. Also it seemed to work with xlf2 format, even with the old @angular/localize version.

**Comment by fetis** [comment]
@mstawick thanks. you were correct. Besides that, I had to manually update packages to RC7 it seems `ng update` failed did correctly. After that, `ng serve` works as expected.

**Comment by horinf** [comment]
Yeah, the same for me. Once I upgraded to the same versions, build passed. Now I have two folders for two different languages. But they the same! I mean no errors, but no translation as well.. 
Just like it explained here: https://github.com/angular/angular/issues/32311
"the application works, except no translations are injected in the templates. Both during ng serve and production builds."
Does it work for you? Or is it still not implemented?

**Comment by mstawick** [comment]
@horinf It works fine for me (RC8). You need to be careful not to mix "old" and "new" configuration options for i18n, otherwise, it won't work. Can you show us your angular.json?

**Comment by horinf** [comment]
Sure. It actually new project with ssr and i18n. I can share whole project if necessary.
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "toolstoliveClientApp": {
      "projectType": "application",
      "schematics": {},
      "root": "",
      "sourceRoot": "src",
      "i18n": {
        "sourceLocale": "en",
        "locales": {
          "ru": "src/locale/messages.ru.xlf"
        }
      },
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/browser",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": true,
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "src/styles.css"
            ],
            "scripts": [
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
            ]
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "localize": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "10kb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "toolstoliveClientApp:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "toolstoliveClientApp:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "toolstoliveClientApp:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": []
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json",
              "e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "toolstoliveClientApp:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "toolstoliveClientApp:serve:production"
            }
          }
        },
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/server",
            "main": "src/main.server.ts",
            "tsConfig": "tsconfig.server.json"
          },
          "configurations": {
            "production": {
              "outputHashing": "media",
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "sourceMap": false,
              "optimization": true
            }
          }
        }
      }
    }
  },
  "defaultProject": "toolstoliveClientApp",
  "cli": {
    "analytics": "5936d1a6-56f6-42b0-b188-6ef1a1b2267d"
  }
}

**Comment by horinf** [comment]
I build it with "npm run build:ssr" command. And deploy two versions using pm2 and nginx as reverse-proxy. It works perfectly, except it is not translated..

**Comment by mstawick** [comment]
OK, I don't know if it works with Universal/SSR. Make sure IVY is enabled (which it should be by default). If you run `ng build --prod`, it should produce localized bundles (since you have `"localize": true` in your configuration). Your file looks good. 

If you want to test it with `ng serve`, you'll need to add a dedicated configuration as described in `https://next.angular.io/guide/i18n`. 

Sorry, nothing else that comes up my mind.

**Comment by horinf** [comment]
https://github.com/horinf/angular9_i18n_ssr/tree/master/frontend/toolstoliveClientApp
That's the project

**Comment by horinf** [comment]
with ng serve ... it works. So, will try to find out what happens with ssr
