### ISSUE TITLE
i18n and processing of '&'

### ISSUE THREAD

**Issue by mstawick** [angular/angular#34632]
# 🐞 bug report

### Affected Package
@angular/localize

### Is this a regression?
Not sure.

### Description
Processing of `&` character seems to be broken in some cases. 

Consider this snippet:
```
    <span i18n>Post&notify</span><br />
    <span i18n>Post & notify</span><br />
    <span i18n>Post &amp; notify</span><br />
    <span i18n>Post &amp;&amp; notify</span><br />
    <span i18n>Post && notify</span><br />
    <span>Post & notify</span><br />
```

It renders as:

```
Post&notify
Post &amp; notify
Post &amp; notify
Post && notify
Post && notify
Post & notify
```

So it seems that rendering of single & is broken. In xlf file, it's properly extracted and translated using `&amp;`

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.7
Node: 12.14.0
OS: linux x64

Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.7
@angular-devkit/build-angular      0.900.0-rc.7
@angular-devkit/build-optimizer    0.900.0-rc.7
@angular-devkit/build-webpack      0.900.0-rc.7
@angular-devkit/core               9.0.0-rc.7
@angular-devkit/schematics         9.0.0-rc.7
@angular/cdk                       9.0.0-rc.6
@angular/material                  9.0.0-rc.6
@angular/material-moment-adapter   9.0.0-rc.6
@ngtools/webpack                   9.0.0-rc.7
@schematics/angular                9.0.0-rc.7
@schematics/update                 0.900.0-rc.7
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2
</code></pre>

**Comment by AndrewKushnir** [comment]
Hi @mstawick, I tried to reproduce the problem, but was unable to replicate the behavior you described. Could you please create a repository with a repro, so that we can perform further investigation? Thank you.

**Comment by mstawick** [comment]
It was my fault. Sorry to waste your time.
