### ISSUE TITLE
Automatically creating Angular code [Code review request]

### ISSUE THREAD

**Issue by polterguy** [angular/angular#34646]
For those having a couple of hours to spare, I'd love to have an additional set of eyes scrutinising the output of my HTTP REST database scaffolding Angular code, presented in this video.

https://www.youtube.com/watch?v=7zNh4Ekd67c

I am not too experienced with Angular development myself, and I want to make sure the resulting code I am producing is at least to some extent considered close to being _"best practices"_ ...

The system basically automatically creates an HTTP REST Web API wrapping your database with all CRUD operations, for then to automatically scaffold up its entire Angular frontend code. I have tested it on a database with 122 tables, and it created almost 100 KLOC for me _automagically_ ...

Thank you for your time :)

**Comment by mmrath** [comment]
I just accidentally saw this issue. I have not seen your video, so I can't tel if this good or not. But the use case is something I am familiar with. But what I have done is a bit different than generating code individually for all tables. Instead I had generic component which took metadata about table. 

Say you have a table `product` with columns `id` and `name` the meta data will provide that info. I then use the meta data to drive how the CRUD form and list looks like. I had forms to edit metadata about table. 

Some properties of meta data were at table level
- editable (to say if we should allow edit on the table)
- insetable
- deletable

column level I had metadata like, `title`, `hidden`, `updateable`, `insertable`, `type`, `regex` etc.

This meta data is also used to generate insert/update statements in the back-end. This a bit more in that more dynamic changes can be accommodated.

just my 2c

**Comment by polterguy** [comment]
Hi @mmrath, I initially explored that approach, but I concluded with that users would want too many possible customisations for me to accommodate for such an approach. Don't get me wrong, I think your approach is kick-ass cool, and probably an amazing generic tool and table - But since I do have the _option_ of generating one component for each table, scaffolding an entire mat-table for each db entity, I think it is a more flexible choice _for me_ ... :)

However, having access to also a generic table, would probably be a nice addition I imagine - So I don't think we're stepping on each others toes here ...

Still, even with a generic table, I'd still need one component for each table, with its associated HTML/CSS/SCSS files etc, to allow for customising the router links.

You should really watch the video. It's generating router links, a nav-bar, one (customisable) component for every database table, etc, etc, etc - In addition to that it takes care of authentication and authorisation - And generates the backend code.

But you made me curious. Have you shared your generic table somewhere ...?

**Comment by gkalpak** [comment]
Regardless how cool, this doesn't fall into the bug report or feature request category, so I am going to close the issue.

Perhaps you could continue the discussion on [Gitter][1] (on a private channel or the [Angular channel][2]) or the issue tracker of your project.

[1]: https://gitter.im/
[2]: https://gitter.im/angular/angular

**Comment by polterguy** [comment]
NP @gkalpak :)

> Regardless how cool

Could I quote you ...? ;)

(Kidding!!)

Thx :)
