### ISSUE TITLE
The HttpClient prefixes absolute URLs with the value of the base attribute

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular#34645]
This SO post has the description:

https://stackoverflow.com/questions/59605333/not-using-the-base-attribute-when-making-domsanitizer-api-calls/59605790#59605790

The summary is that even though we are making absolute URL requests like this:

```
this.matIconRegistry.addSvgIcon(
        "fs",
        this.domSanitizer.bypassSecurityTrustResourceUrl('https://github.com/fireflysemantics/images/blob/master/fsalpha/logo/fsalpha-logo-optimized.svg'));

```

Angular will still prefix the URL:

```
https://github.com/fireflysemantics/images/blob/master/fsalpha/logo/fsalpha-logo-optimized.svg'
```

With the URL in the `base` attribute.

The SO post contains links to a medium article and another Stackblitz that shows this happening in a live environment.

**Comment by tieppt** [comment]
I don't see any bug here. The stackblitz is missing closing head tag. This one is working without bug:

https://stackblitz.com/edit/angular-material-custom-icon-with-base-zavkvw?file=src/index.html
image
![image](https://user-images.githubusercontent.com/7151365/71811256-c9689480-30a6-11ea-9289-90b0268090c9.png)

**Comment by fireflysemantics** [comment]
I may have goofed the Stackblitz demo, but the bug is there.  I'll attach a screenshot of it here.
![Screenshot from 2020-01-06 08-59-57](https://user-images.githubusercontent.com/25155787/71826528-c1d3cc00-3063-11ea-9251-1b0faebfd94f.png)

**Comment by fireflysemantics** [comment]
@tieppt 
The images I'm loading are at locations like this one:

https://fireflysemantics.github.io/images/google/logo/Google.svg

So I specify that as the absolute URL.  When using the DomSanitizer.bypassSecurityTrustResourceUrl(...) the call will prefix the `base` attribute value and strip the `https://` from the absolute URL I have specified.

So the URL ends up being:

```
https://fsalpha-canary.fireflysemantics.com/fireflysemantics.github.io/images/google/logo/Google.svg
```

Instead of:

```
https://fireflysemantics.github.io/images/google/logo/Google.svg
```

**Comment by fireflysemantics** [comment]
My Angular version info:

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.0-rc.7
Node: 12.6.0
OS: linux x64

Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.7
@angular-devkit/build-angular     0.900.0-rc.7
@angular-devkit/build-optimizer   0.900.0-rc.7
@angular-devkit/build-webpack     0.900.0-rc.7
@angular-devkit/core              9.0.0-rc.7
@angular-devkit/schematics        9.0.0-rc.7
@angular/cdk                      8.2.3
@angular/material                 8.2.3
@ngtools/webpack                  9.0.0-rc.7
@schematics/angular               9.0.0-rc.7
@schematics/update                0.900.0-rc.7
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

**Comment by tieppt** [comment]
Did you double check you're not using interceptor to include prefix?

**Comment by fireflysemantics** [comment]
@tieppt  I created a MCVE here:

https://github.com/fireflysemantics/angular-http-bug

You can clone and run it locally and it will fetch the SVG resources just fine.  The interceptor logs the URLs being fetched.

It's also deployed here:

https://fireflysemantics.github.io/angular-http-bug/

If you open the developer console you will see that the base attribute is included in the URLs:

```
THE URL IS:  https:/fireflysemantics.github.io/images/fsalpha/logo/fsalpha-logo-optimized.svg
main-es2015.39efdbaf8bdd6deb645e.js:1 THE URL IS:  https:/fireflysemantics.github.io/images/google/logo/Google.svg
```

The relevant application code is the interceptor service:

https://github.com/fireflysemantics/angular-http-bug/blob/master/src/app/interceptor.service.ts

And the asset service:

https://github.com/fireflysemantics/angular-http-bug/blob/master/src/app/assets.service.ts

You can see in the assets service that the image URLs being loaded are absolute.

**Comment by tieppt** [comment]
I've changed your service to the following image (using concatenate string instead of using `path`). This work well both `ng serve` and `ng build --prod`

![image](https://user-images.githubusercontent.com/7151365/71877314-6422ab00-315b-11ea-9037-0d576fed70ca.png)

**Comment by fireflysemantics** [comment]
Ah so `path` was causing it ... Thanks - Good call!

**Comment by AndrewKushnir** [comment]
@fireflysemantics it looks like the problem was resolved and it was not specific to the framework. I'm closing this ticket, feel free to reopen if I misunderstood the issue and the problem still exists.
