### ISSUE TITLE
Instructions to update angular cli from 5 to 6 are incorrect

### ISSUE THREAD

**Issue by RohanHart** [angular/angular#34654]
# 📚 Docs or angular.io bug report

### Description

The update documentation for 5->6 is incorrect. The step ng `update @angular/cli@6` does not migrate and displays `Invalid rule result: null`. The correct instruction should be `ng update @angular/cli --migrate-only --from=1.7.4`.

The issue is that the logic which determines which package to migrate does not strip off the version requested.

### What's the affected URL?**
https://update.angular.io/#5.0:6.0

### Reproduction Steps**

1. Create a new angular 5 project
1. Try to update it to 6 using the instructions from https://update.angular.io

### Anything else relevant?

npm 6.11.3

**Comment by mgechev** [comment]
@RohanHart thanks for reporting the issue! Looks like this is already under the radar in the update guide https://github.com/StephenFluin/angular-update-guide/issues/64.

Feel free to add further details if there's anything missing.
