### ISSUE TITLE
Bazel integration not working with Bazel 1.0.1

### ISSUE THREAD

**Issue by arobinson** [angular/angular#34650]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
https://github.com/angular/angular/blob/master/packages/bazel/src/ng_package/ng_package.bzl

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
No

### Description

 A clear and concise description of the problem...
https://github.com/angular/angular/blob/master/packages/bazel/src/ng_package/ng_package.bzl uses `@build_bazel_rules_nodejs//internal/npm_package:npm_package.bzl` but that is not a valid target with Bazel 1.0.1

## 🔬 Minimal Reproduction

 https://stackblitz.com/...
1. Download this repository:
https://stackblitz.com/edit/angular-issue-repro2-zh4dnz
2. Extract the zip file (to `/tmp/angular-issue-repro2-zh4dnz` for example)
3. cd into `angular-issue-repro2-zh4dnz`
4. Run `npm i`
5. Run `ng b`

Output:
<pre><code>
Starting local Bazel server and connecting to it...
ERROR: Skipping '//src:prodapp': error loading package 'src': Label '@build_bazel_rules_nodejs//internal/web_package:web_package.bzl' is invalid because 'internal/web_package' is not a package; perhaps you meant to put the colon here: '@build_bazel_rules_nodejs//internal:web_package/web_package.bzl'?
WARNING: Target pattern parsing failed.
ERROR: error loading package 'src': Label '@build_bazel_rules_nodejs//internal/web_package:web_package.bzl' is invalid because 'internal/web_package' is not a package; perhaps you meant to put the colon here: '@build_bazel_rules_nodejs//internal:web_package/web_package.bzl'?
INFO: Elapsed time: 65.469s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
    Fetching @npm_bazel_terser; fetching
    Fetching @npm_angular_bazel; fetching
/private/tmp/angular-issue-repro2-zh4dnz/node_modules/@bazel/bazel/node_modules/@bazel/bazel-darwin_x64/bazel-2.0.0-darwin-x86_64 failed with code 1.
</code></pre>

## 🔥 Exception or Error
<pre><code>

ERROR: Skipping '//src:prodapp': error loading package 'src': in /private/var/tmp/_bazel_andrew/8ed9780ae4c62a4730fa5efe8fbe12e9/external/npm_angular_bazel/index.bzl: in /private/var/tmp/_bazel_andrew/8ed9780ae4c62a4730fa5efe8fbe12e9/external/npm_angular_bazel/src/ng_package/ng_package.bzl: Label '@build_bazel_rules_nodejs//internal/npm_package:npm_package.bzl' is invalid because 'internal/npm_package' is not a package; perhaps you meant to put the colon here: '@build_bazel_rules_nodejs//internal:npm_package/npm_package.bzl'?
WARNING: Target pattern parsing failed.
ERROR: error loading package 'src': in /private/var/tmp/_bazel_andrew/8ed9780ae4c62a4730fa5efe8fbe12e9/external/npm_angular_bazel/index.bzl: in /private/var/tmp/_bazel_andrew/8ed9780ae4c62a4730fa5efe8fbe12e9/external/npm_angular_bazel/src/ng_package/ng_package.bzl: Label '@build_bazel_rules_nodejs//internal/npm_package:npm_package.bzl' is invalid because 'internal/npm_package' is not a package; perhaps you meant to put the colon here: '@build_bazel_rules_nodejs//internal:npm_package/npm_package.bzl'?
INFO: Elapsed time: 0.085s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
    Fetching @bazel_skylib; fetching
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.0-rc.7
Node: 12.13.1
OS: darwin x64

Angular: 9.0.0-rc.7
... animations, bazel, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.7
@angular-devkit/build-angular      0.900.0-rc.7
@angular-devkit/build-ng-packagr   0.900.0-rc.7
@angular-devkit/build-optimizer    0.900.0-rc.7
@angular-devkit/build-webpack      0.900.0-rc.7
@angular-devkit/core               9.0.0-rc.7
@angular-devkit/schematics         9.0.0-rc.7
@angular/cdk                       9.0.0-rc.6
@bazel/bazel                       2.0.0
@bazel/hide-bazel-files            1.0.1
@bazel/ibazel                      0.11.0
@bazel/karma                       1.0.1
@bazel/protractor                  1.0.1
@bazel/rollup                      1.0.1
@bazel/terser                      1.0.1
@bazel/typescript                  1.0.1
@ngtools/webpack                   9.0.0-rc.7
@schematics/angular                9.0.0-rc.7
@schematics/update                 0.900.0-rc.7
ng-packagr                         9.0.0-rc.3
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2
</code></pre>

**Anything else relevant?**

Mac OSX 10.15.1
node 12.13.1

**Comment by literalpie** [comment]
It looks like there is [an open PR for this](https://github.com/angular/angular/pull/34589)

**Comment by gregmagolan** [comment]
Yes. Once https://github.com/angular/angular/pull/34589 lands this will be resolved on the next release.

In the meantime, you can apply the @angular/bazel patch from the rules_nodejs angular example (https://github.com/bazelbuild/rules_nodejs/blob/master/examples/angular/patches/%40angular%2Bbazel%2B9.0.0-rc.7.patch) to work with @angular/bazel-9.0.0-rc.7

**Comment by jelbourn** [comment]
Closing this since it seems like Greg's PR to fix it was merged.
