### ISSUE TITLE
dartdocgen process fails due to multiple exports of RenderElementRef

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#3466]
See http://www.dartdocs.org/buildlogs/b-7b0c733494e60b302c13e55430878-startupscript.log for logs -- alpha-33 never made it to pub. 

Looks like RenderElementRef exported from both render.dart and core.dart is the culprit? Can we resolve this for alpha-34?

**Comment by yjbanov** [comment]
Fixed by 280d8f3148ea41c5d8feb4483f1ac0139d2d975d
