### ISSUE TITLE
Error in getting started documentation

### ISSUE THREAD

**Issue by Dragorniak** [angular/angular#34669]
# 📚 Docs or angular.io bug report

### Description

 Bad path at src/app/product-list/product-alerts.component.ts at the Set up the new product alerts component to receive a product as input:

    Import Input from @angular/core.

it should be src/app/product-alerts/product-alerts.component.ts

and the same for the one down of this.
src/app/product-list/product-alerts.component.ts  >>> src/app/product-alerts/product-alerts.component.ts
### What's the affected URL?**
 https://angular.io/start

## 📷Screenshot

 
![image](https://user-images.githubusercontent.com/47112109/71944300-22692300-31a2-11ea-87cc-5cdcf772244f.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by ericmartinezr** [comment]
Fixed by https://github.com/angular/angular/pull/34321, you can see the change live in https://next.angular.io/start

**Comment by kapunahelewong** [comment]
Thanks for this, @Dragorniak. Would you mind if I close it since it's fixed and should be live soon on angular.io? Thanks for referencing the PR, @ericmartinezr!

**Comment by Dragorniak** [comment]
I closed  it, but you can close it! thanks for feedback! :)
