### ISSUE TITLE
animation event bindings support `animate-` prefix

### ISSUE THREAD

**Issue by ivanwonder** [angular/angular#34673]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/animations

### Description
 Now the animations property bindings support `@` and `animate-`(I don't find any info about this one on public documentation) prefix. But the animation event bindings don't support `animate-` prefix.

### Describe the solution you'd like
 It's better to support `animation-` prefix for the animation event bindings because Angular have support `bind-`, 'on-', etc.

### Describe alternatives you've considered
 Or stop support `animation-` for animations property bindings and remove from @angular/compiler code. After all, the document hasn't mentioned the `animation-`.

**Comment by ayazhafiz** [comment]
@ivanwonder can you elaborate on the solution that you would expect from this request? Alternatively, the framework could remove the `animate-` prefix (though this might be a breaking change).
