### ISSUE TITLE
want build of each input field as a component , what is the disadvantage and pos ??

### ISSUE THREAD

**Issue by Mohammadnemer** [angular/angular#34674]
The construction of each input field as a component, what is the disadvantage and positives of this matter in a large project, what impact on building more than once at the same time  ??

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
