### ISSUE TITLE
DOM change in ngIf cancels submit event

### ISSUE THREAD

**Issue by gabrielguerrero** [angular/angular#34678]
# 🐞 bug report

### Affected Package
Not sure I suspect is rendering issue so I imagine in core
@angular/core

### Is this a regression?
I have noticed it  since version 7.2.6, I have use angular since 2 but not sure if it was happening before

### Description
Given the following html 
```
<form [formGroup]="contactForm" (ngSubmit)="onSubmit()">
  <input
    name="message"
    formControlName="message"
    (focus)="focus = true"
    (blur)="focus = false"
  />
  <br />
  <div *ngIf="focus">
    <p>Focus</p>
  </div>
  <input type="submit" value="Send" />
</form>
```
The idea is that a message is shown when you focus on the text field, and hides on blur
The problem is a specific case where the ngSubmit does not get fired by clicking the button this happens if you focus the text and then immediately click on the button, any other case hitting submit button will work correctly.
The problem seems to be with the ngIf been next to the input, if you remove the ngIf it works correctly , also if you move the ngIf either after the button or outside of the form it also works

## 🔬 Minimal Reproduction
To reproduce:
- Open the https://stackblitz.com/edit/angular-8-dom-change-cancels-event?file=src%2Fapp%2Fapp.component.html
- Open the stackblitz console
- Click on the text field and then click on the submit button, a submit message should be logged but it doesn't

## 🔥 Exception or Error
No exception or error is displayed

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.0.7
Node: 10.14.1
OS: darwin x64
Angular: 8.0.0
... common, compiler, core, forms, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@angular/compiler-cli             7.0.4
@angular/language-service         7.0.4
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.5.4
typescript                        3.1.6
webpack                           4.19.1

</code></pre>

**Anything else relevant?**
Nothing else, it seems to happen in Chrome and Safari at least , I have not tested other browsers

**Workarounds**
Adding a `(mousdedown)="onSubmit()" to the button will make the submit work again but has other consequences like in some cases double submission

**Comment by JoostK** [comment]
What happens is that the button is repositioned during the `mousedown` event, as that is when the button gets focused. Only when the `click` event is created, which only occurs after the `mouseup` event, will the browser perform a hit-test of which element was clicked, which will not be the button as it has been repositioned.

You can clearly see this happening when you long-press: by postponing the `click` event, you can see the button getting focus but also moving up a bit, causing the mouse to no longer hit the button. If you then release, the browser figures out that the button is no longer under the cursor, so it doesn't initiate the submit. This is similar to the case where you long-press a button and then decide to cancel the click by moving your cursor away from the button before releasing.

I don't think this is a framework issue, but rather normal browser behavior. As such I'm closing this issue. You can probably resolve the problem using an Angular directive to toggle the `focus` flag but only after `mouseup` has been observed, not immediately during `mousedown`. Using banana-in-a-box syntax to two-way-bind the `focus` variable and a `@HostListener` within the directive, this can be done in a rather nice Angular-y way.

**Comment by gabrielguerrero** [comment]
@JoostK You are completely right thanks for checking so fast, worst thing was in one of my test investigating this I tested that but I realize now that when I tested I by mistake left a (mousedown)="onSubmit()" workaround in the button that I did not notice :S, thanks again is been long day
