### ISSUE TITLE
Add consistent release tags for Angular npm packages

### ISSUE THREAD

**Issue by CarstenLeue** [angular/angular#34672]
# 🚀 feature request

### Description

Please add a consistent release tag to the angular packages published to npm. Some packages already use release tags (e.g. @angular/core has `v5-lts` and `v4-lts` but no `v6-lts`, `v7-lts`, `v8-lts`). 
Other packages such as `@angular-devkit/schematics` have `v6-lts` but none of the other tags.

### Describe the solution you'd like
For each package that belongs to the angular ecosystem, please add a consistent release tag. This could then be used to more easily reference a consistent version of Angular in custom projects, in particular if they are not using the CLI.

**Comment by JoostK** [comment]
Tagging LTS releases accordingly is part of recent release automation scripts and release instructions, and the tags seem to have been applied on NPM as well.
