### ISSUE TITLE
when i trigger material tabs switch,page back to top.

### ISSUE THREAD

**Issue by 513205785Xie** [angular/angular#34688]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please read https://angular.io/guide/security#report-issues on how to disclose security related issues.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
When the following conditions are met:
1. page has scroll bar
2. material tabs component header not out of page
3. material tabs component content out of range
problems occur when clicking toggling tabs.
Like this：
![image](https://user-images.githubusercontent.com/22184621/72029291-68b4a400-32c0-11ea-9d43-10df81882d23.png)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Report this issue in https://github.com/angular/components please :+1:
