### ISSUE TITLE
BrowserViewportScroller to support dynamic div instead of window always

### ISSUE THREAD

**Issue by sthan001** [angular/angular#34685]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/common of class ViewportScroller

### Description
 Right now the ViewportScroller implemented by BrowserViewportScroller always has reference to window object. it would be nice to allow any internal deep down(3+ level from body) as part of router or component initialization.

Because if a application set overflow hidden at body level and enabled auto for div which is down, then window scroll most likely not going to work. Because window is not scroll able. The div is the one which is scroll able.

class ViewportScroller {
}
// De-sugared tree-shakable injection
// See #23917
/** @nocollapse */
/** @nocollapse */ ViewportScroller.ngInjectableDef = ɵɵdefineInjectable({
    token: ViewportScroller,
    providedIn: 'root',
    factory: (/**
     * @nocollapse @return {?}
     */
    () => new BrowserViewportScroller(ɵɵinject(DOCUMENT), window, ɵɵinject(ErrorHandler)))
});

### Describe the solution you'd like
 Request is to allow user to change the scroll object based on selection. Also deep ask is to allow relative scroll option as well. If header present, no point in putting the anchor's start under header to user.

### Describe alternatives you've considered
 Not yet, this is not a mandatory feature. Looks angular framework is pretty neat to do end to end design. This is one exploration team can do to support the injection.

**Comment by cormickjbrowne** [comment]
@courtney-regis

**Comment by manzonif** [comment]
Same need. 
I use ngx-scrollbar for my app and, on navigate back, I not be able to have the correct scroll event position.  
It's always [0,0].

**Comment by bevkoski** [comment]
Achieved this with a workaround.

In the template:

```html
<div #container>
```

In the component:

```typescript
@ViewChild('container') containerRef: ElementRef;
```

Whenever scrolling is needed:

```typescript
this.containerRef.nativeElement.scroll(0, 100); // Scroll 100px vertically
```

**Comment by crisbeto** [comment]
We talked through this and we decided to close it, because the default implementation isn't meant to cover every single case, just the most common one. You can customize the behavior by providing your own `ViewportScroller`:

```
providers: [{
  provide: ViewportScroller,
  useClass: YourViewportScroller
}]
```
