### ISSUE TITLE
Destructuring in metadata and language service

### ISSUE THREAD

**Issue by waterplea** [angular/angular#34691]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/language-service

### Description
 When you have directives sharing some similarities you could store some metadata info like exportAs or inputs array in constants and then use destructuring like this:

```
@Directive({
    selector: '[myDirective]',
    exportAs,
    inputs: ['someInput', ...COMMON_INPUTS],
})
```

Or even have a metadata factory function like so:

```
@Directive(
    metadataFactory('[myDirective]', ['someInput'])
)
```

Unfortunately autocomplete in templates doesn't work and language service shows errors even though it all compiles this way.

### Describe the solution you'd like
 It would be great if language service could figure out such things, at least destructuring. I realize predicting function results might be out of scope of the service, even if the function is pure.

### Describe alternatives you've considered
 Copy pasting :(

**Comment by JoostK** [comment]
As the Ivy language service is now based on the compiler, the syntax that is supported is identical to what is supported in AOT builds. Spread syntax is supported, so from that perspective there is nothing for the language service to support. I do get autocomplete for these inputs and no errors are reported, although I also didn't get errors using the View Engine-based language service (I only confirmed that autocomplete did not work).

Closing as resolved in the Ivy language service.
