### ISSUE TITLE
Error with datepicker of ngx-bootstrap@latest After upgrading to version 9.0.0-rc.8

### ISSUE THREAD

**Issue by waseem-isaac-BBN** [angular/angular#34693]
`ERROR in Symbol BsDaterangepickerInlineContainerComponent declared in X/node_modules/ngx-bootstrap/datepicker/themes/bs/bs-daterangepicker-inline-container.component.d.ts is not exported from ngx-bootstrap (import into X)`

**Comment by waseem-isaac-BBN** [comment]
I think the problem with `ivy` 
it works after adding
 ```
"angularCompilerOptions": {
    "enableIvy": false
  },
```
in `tsconfig.app.json` file

**Comment by gkalpak** [comment]
We have a very basic `ngx-bootstrap` project in [angular/ngcc-validation][1], but it doesn't use any components, so we might be missing some failures.

Could you post a minimal reproduction demonstrating the error?
(If you could update the project in `angular/ngcc-validation` to trigger the error, that would be super-cool (but not necessary) :wink:)

[1]: https://github.com/angular/ngcc-validation/tree/79691d628/projects/ngx-bootstrap-ngcc

**Comment by petebacondarwin** [comment]
I'm going to try to reproduce.

**Comment by petebacondarwin** [comment]
Here is the reproduction: https://github.com/angular/ngcc-validation/pull/779

**Comment by thecp** [comment]
FYI it should work (at least does for me) if you change the import from `import { BsDatepickerModule } from 'ngx-bootstrap';` to `import { BsDatepickerModule } from 'ngx-bootstrap/datepicker';`

**Comment by petebacondarwin** [comment]
I concur with @thecp - I compiles and runs correctly with the deep import.

There is actually an issue on the library for this - https://github.com/valor-software/ngx-bootstrap/issues/5585

Closing as the Angular compiler is actually working as expected in this case.
