### ISSUE TITLE
Authorization token can not be forwarded into server side correctly

### ISSUE THREAD

**Issue by winterchipmunk** [angular/angular#34704]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

I implemented AuthTokenInterceptor as below. My problem is that the Authorization token can not be forwarded into server side correctly. I am sure that I can get authentication token by request.headers.get("Authorization") right before I pass the request into next.handler().

I found that the request had been sent twice, the first one had no Authorization header but the second one had the header.

I removed the retry from pipe, but there are still two requests sent to the server side.

There is a special case for my project. I used a third-party i18n tool and it requires old HttpModule from '@angular/http'. So I import both HttpModule and HttpClientModule.

```
  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {

    if (this.authService.getAccessToken()) {
      request = this.addToken(request);
    }

    return next.handle(request).pipe(catchError(error => {
      if (error instanceof HttpErrorResponse 
        && ( error.status === 401 || error.status == 403) ) {
        if ( error.status == 401 )
          return this.handle401Error(error, request, next);
        else
          return this.handle403Error(error, request, next);
      } else {
        return throwError(error);
      }
    }));
  }

  private addToken(request: HttpRequest<any>): HttpRequest<any> {
    const tokenName = this.authService.getAuthorizationTokenName();
    const tokenValue = this.authService.getAuthorizationTokenValue();

    // Clone the request and replace the original headers with
    // cloned headers, updated with the authorization.
    const authReq = request.clone({
      headers: request.headers.set(tokenName, tokenValue)
    });
    return authReq;
  }

```

Please help us process issues more efficiently by filing an
issue using one of the following templates:

https://github.com/angular/angular/issues/new/choose

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
