### ISSUE TITLE
APP_INITIALIZER

### ISSUE THREAD

**Issue by mswilson4040** [angular/angular#34703]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...
In the [docs](https://angular.io/api/core/APP_INITIALIZER), the APP_INITIALIZER is mentioned. However, there is only a single sentence and that's it. The sentence says:

> A function that will be executed when an application is initialized.

Based on many other 3rd party articles (such as Medium, SOF, etc..), everyone talks about the APP_INITIALIZER as the place to put code that you need to be loaded before your application is initialized. However, the sentence in the documentation makes it seem like it's a function that runs when the app is initialized.

There are other important parts of information such as what you can put inside the function. Does it have to return anything specific? A Promise? An Observable? Anything?

I've been working with angular for 6 years now and just ran into this. It's going to solve a lot of my problems if it does what the 3rd party articles say it does. It would be very helpful if more documentation was provided by the Angular team on how to actually use it the right way. This feature is very hidden. It would be nice if this was included in the Tour of Heroes as there is almost always something that needs to be pre-fetched to make the app work. In my case, it's the router configuration.

### What's the affected URL?**
 https://angular.io/...
https://angular.io/api/core/APP_INITIALIZER

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by thefliik** [comment]
I also didn't know about this. Just looking at the [source code](https://github.com/angular/angular/blob/8.2.14/packages/core/src/application_init.ts#L19-L72) (linked to from the API docs), it looks like you can provide multiple `APP_INITIALIZER`s (`multi: true`) and, if any app initializers return a promise, the application will wait for all promises to resolve.

The `APP_INITIALIZER` injection token's type signature is actually somewhat confusing, as it is typed as `Array<() => void>`:

```ts
export const APP_INITIALIZER = new InjectionToken<Array<() => void>>('Application Initializer');
```

`() => void` makes it seem like Angular will ignore the `APP_INITIALIZER`'s return when, in fact, Angular checks to see if a promise is returned and, if so, waits for it to resolve. If the return type was `Array<() => void | Promise<void>>` it would be more clear.

**Comment by smnbbrv** [comment]
> Based on many other 3rd part articles (such as Medium, SOF, etc..), everyone talks about the APP_INITIALIZER as the place to put code that you need to be loaded before your application is initialized. However, the sentence in the documentation makes it seem like it's a function that runs when the app is initialized.

Actually, that's true and not true. The function will be called **while** the app is being initialised. Not before, not after.

If the app is initialised then it's too late to change something and `APP_INITIALIZER` does not make sense anymore. However at this moment the `platformBrowserDynamic().bootstrapModule(AppModule)` is already called; so it already started the init step.

Another thing that should be well documented: if you really want to do something before the app init you should look at this issue https://github.com/angular/angular/issues/23279 and perform actions in your `main.ts`.

**Comment by ChristopherKiss** [comment]
It's important to note, that the APP_INITIALIZER does not wait for observables, only promises. This caught me out originally as I was using observables to match Angular patterns, but had to revert to promises for just the initializer.

**Comment by kapunahelewong** [comment]
Closed per https://github.com/angular/angular/pull/34760
