### ISSUE TITLE
Angular component is not compiling with “--prod” option: Object is of type “unknown”

### ISSUE THREAD

**Issue by usarskyy** [angular/angular#34700]
### Affected Package
Not sure

### Is this a regression?
Not sure

### Description
This is a copy-paste from https://stackoverflow.com/questions/59667441/angular-component-is-not-compiling-with-prod-option-object-is-of-type-unknow

I am trying to compile my Angular application for production ("--prod" option) but I get lots of weird errors like:

> blah.component.html(15,11): Object is of type 'unknown'

Template code that produces these errors is following:

```
<tbody>
<tr *ngFor="let item of items$ | async">
<td>{{item.name}}</td>
<td>{{item.code}}</td>
</tr>
</tbody>
```

`items$` variable defined as following:

`public item$: Observable<ListItem[]>;`

What I don't understand is why I am receiving these error messages as almost same code on my private laptop compiles as expected!

I would be appreciated for any help!

**UPDATE 1:**

Another error, that I haven't noticed earlier, points to `ngFor` statement and says:

> blah.component.html(14,11): Type 'ListItem[] | null' is not assignable to type 'ListItem[] | Iterable | undefined'.

Why Angular compiler thinks that `items$` property can be either array, or null? It is explicitely defined as `Observable<ListItem[]>`.

When I changed my template as shown below, these error messages dissapeared:

```
<ng-container *ngIf="items$ | async as tmp">
<tr *ngFor="let item of tmp">
<td>{{item.name}}</td>
...
```

## 🔬 Minimal Reproduction
Just create a simple component with `ngFor="let item of items$ | async"`

## 🔥 Exception or Error

> blah.component.html(14,11): Type 'ListItem[] | null' is not assignable to type 'ListItem[] | Iterable | undefined'.

> blah.component.html(15,11): Object is of type 'unknown'

## 🌍  Your Environment

**Angular Version:**

- Angular CLI: 8.3.22
- Angular: 8.2.14
- Node: 11.12.0
- typescript: 3.5.3

**Ivy and AOT are enabled.**

**Anything else relevant?**

Similar code **compiles as expected on another laptop** with same version of Angular packages!

**Comment by usarskyy** [comment]
I've disabled Ivy and these error messages vanished.

**Comment by atscott** [comment]
Hi @usarskyy, we need more information to reproduce the issue. Can you provide a reproduction in a minimal github project?

**Comment by spock123** [comment]
@usarskyy 

How about 

`let item of ( items$ | async) `

**Comment by usarskyy** [comment]
@atscott not sure if this is reproducable. As I wrote before, similar code is compiling fine on another laptop. But I will try to create you an example project with same issues.

**Comment by spock123** [comment]
> @spock123 with yours it is creating subscription for each iteration and unsubscribing one by one. It is not good way.

You are right

**Comment by usarskyy** [comment]
@atscott I managed to create a sample app: https://github.com/usarskyy/ngforissue
What is weird: I've tried to create same app from scratch but it compiled as expected. So, I assume, error message is wrong and the root problem is related to one of the referenced packages

**Comment by alxhub** [comment]
@usarskyy this project is set up to use Angular 8.x, which has not received updates to its Ivy implementation since 9.0 entered RC. Ivy in 8.x is therefore unsupported.

I upgraded your reproduction to Angular 9.x (rc.9), and patched one issue with the code (use of `namespace` which doesn't compose well with ES module projects - all Angular projects use ES modules). The build works as expected, even under the new `strictTemplates` type-checking.
