### ISSUE TITLE
LOCALE_ID is being set before APP_INITIALIZER finish execution - [ng serve only]

### ISSUE THREAD

**Issue by TomaszCz** [angular/angular#34701]
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes. It is a breaking change.

### Description
LOCALE_ID is being set before APP_INITIALIZER function finish execution.
Interestingly, this behavior can be observed only with ng serve. Both repositories will work fine on stackblitz.

## 🔬 Minimal Reproduction
Here is the reproduction repo:
https://stackblitz.com/github/TomaszCz/angular-ivy-LOCALID
and the same repo after **ng update @angular/core @angular/cli --next** 
https://stackblitz.com/github/TomaszCz/angular-ivy-LOCALID/tree/angular9

clone and run **ng serve** the updated one will not work - the locale value will be undefined.

## 🔥 Exception or Error
After update:
![image](https://user-images.githubusercontent.com/20865719/72070824-b80fca00-32ea-11ea-9d8e-215f7fcf8ee8.png)

Before the update:
![image](https://user-images.githubusercontent.com/20865719/72071400-ff4a8a80-32eb-11ea-9fa7-ce62fee1da47.png)

## 🌍 Your Environment
Before update:
<pre><code>
C:\a\AngularPOC\angular>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.3.22
Node: 12.3.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.22
@angular-devkit/build-angular     0.803.22
@angular-devkit/build-optimizer   0.803.22
@angular-devkit/build-webpack     0.803.22
@angular-devkit/core              8.3.22
@angular-devkit/schematics        8.3.22
@angular/cli                      8.3.22
@ngtools/webpack                  8.3.22
@schematics/angular               8.3.22
@schematics/update                0.803.22
rxjs                              6.5.4
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

After update:
<pre><code>
C:\a\AngularPOC\angular>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.0-rc.8
Node: 12.3.1
OS: win32 x64

Angular: 9.0.0-rc.8
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.8
@angular-devkit/build-angular     0.900.0-rc.8
@angular-devkit/build-optimizer   0.900.0-rc.8
@angular-devkit/build-webpack     0.900.0-rc.8
@angular-devkit/core              9.0.0-rc.8
@angular-devkit/schematics        9.0.0-rc.8
@ngtools/webpack                  9.0.0-rc.8
@schematics/angular               9.0.0-rc.8
@schematics/update                0.900.0-rc.8
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

I see similar closed issue
https://github.com/angular/angular/issues/31465
and the fix https://github.com/angular/angular/pull/31983/commits/08c449dd746bae31ba228164054b90c8402de20f

https://github.com/angular/angular/pull/31983

**Comment by petebacondarwin** [comment]
The problem is indeed that we are setting the locale (for ivy) before the application initialisers run.
We had to do this (at the moment) because the `$localize` messages are processed when the module loads (i.e. the es6 module) which require the locale to be set.

If we move the `$localize` calls inside a closure that only gets run when the template is being processed then this restriction is removed and we could put the initialisation of the locale later in the bootstrap (i.e. after the initializers have run).

**Comment by petebacondarwin** [comment]
This PR (https://github.com/angular/angular/issues/31465) effectively fixed it  for non-ivy because the getting of `LOCALE_ID` via the injector is only done under ivy. But there is a test there which is incorrectly passing under ivy: https://github.com/angular/angular/blob/86e1e6c0823a6a8cf4314a655eaa6aef14a474b8/packages/core/test/application_ref_spec.ts#L346-L359

**Comment by TomaszCz** [comment]
I can confirm it is working now on 9.0.0-rc.10. Thank you!
