### ISSUE TITLE
Support decorators

### ISSUE THREAD

**Issue by blacksonic** [angular/angular#3470]
Im transpiling my code with Babel, which uses the decorators proposal. My current code:
```
@ComponentAnnotation({
  selector: 'hello-cmp'
})
@ViewAnnotation({
  template: 'Hello World!'
})
class HelloComponent {}
```
is transpiled to
```
var _HelloComponent = HelloComponent;
HelloComponent = _angular.ViewAnnotation({
  template: 'Hello World!'
})(HelloComponent) || HelloComponent;
HelloComponent = _angular.ComponentAnnotation({
  selector: 'hello-cmp'
})(HelloComponent) || HelloComponent;
return HelloComponent;
```
The problem is when the annotation function gets invoked they return ```undefined```.
Is it possible to check if the annotation constructor is called with the new keyword and if its not, it returns a function that puts itself onto the classes annotation property?
This way Angular would support annotations AND the proposal also.

**Comment by pkozlowski-opensource** [comment]
@blacksonic Angular2 already supports both annotations and decorators. If you want to use decorators just do `@Component` instead of `@ComponentAnnotation`. Here is the example with Babel: http://plnkr.co/edit/GohfcaiNrwVRn8Hq42tM?p=preview
