### ISSUE TITLE
Obscure ERROR in component is missing a template message

### ISSUE THREAD

**Issue by mikejpoole** [angular/angular#34725]
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes, the previous version in which this bug was not present was: 8.3.22

### Description
It is possible to build the app without errors in Angular 8 but when I try to build in the Angular 9 RC an obscure error message is provided. If this error message was to specify which component has a missing template it would be more useful.

## 🔬 Minimal Reproduction
I ran `ng build`

## 🔥 Exception or Error
<pre><code>
ERROR in component is missing a template
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-rc.8
Node: 12.14.1
OS: win32 x64

Angular: 9.0.0-rc.8
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.8
@angular-devkit/build-angular     0.900.0-rc.8
@angular-devkit/build-optimizer   0.900.0-rc.8
@angular-devkit/build-webpack     0.900.0-rc.8
@angular-devkit/core              9.0.0-rc.8
@angular-devkit/schematics        9.0.0-rc.8
@ngtools/webpack                  9.0.0-rc.8
@schematics/angular               9.0.0-rc.8
@schematics/update                0.900.0-rc.8
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Comment by crisbeto** [comment]
Is that the full error log you're getting? You should get something like this that highlights the place that's causing the error:

```
test.ts:4:9 - error NG2001: component is missing a template

4         @Component({selector: 'test'})
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by mikejpoole** [comment]
Hi @crisbeto, no there was no detail beside the error message. That is why I thought it was worth reporting because other errors that the CLI has generated provided such errors but this error did not.

**Comment by AndrewKushnir** [comment]
Hi @mikejpoole, thanks for reporting the issue. We were able to reproduce it and will investigate it further. Thank you.

**Comment by mikejpoole** [comment]
Many thanks for that @AndrewKushnir . Keep up the good work.
