### ISSUE TITLE
Update timing of formcontrol and formgroup is confusing

### ISSUE THREAD

**Issue by dummdidumm** [angular/angular#34723]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/forms

### Is this a regression?

No

### Description

The update timing of formcontrol and formgroup is confusing. The formcontrol emits its value changes before the formgroup has the new value set:

1. Value is set (either on formgroup or formcontrol)
2. `valueChanges` of formcontrol emits its new value
3. Value is propagated to formgroup.

This means that this happens:

```ts
this.form.controls.name.valueChanges.subscribe(value => {
      console.log(
        "control value change coming in. value on control:",
        value, // will be the new value
        "value on form:",
        this.form.value // is still the old value
      );
    });
```

I would expect the formvalue to be consistent with the control value.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-m1xphx?file=src/app/app.component.ts

## 🌍  Your Environment

**Angular Version:**
latest 8, also 9.

## Possible cause

I think the problem is the function `updateValueAndValidity` in https://github.com/angular/angular/blob/master/packages/forms/src/model.ts#L612 .

```ts
  updateValueAndValidity(opts: {onlySelf?: boolean, emitEvent?: boolean} = {}): void {
    this._setInitialStatus();
    this._updateValue();

    if (this.enabled) {
      this._cancelExistingSubscription();
      (this as{errors: ValidationErrors | null}).errors = this._runValidator();
      (this as{status: string}).status = this._calculateStatus();

      if (this.status === VALID || this.status === PENDING) {
        this._runAsyncValidator(opts.emitEvent);
      }
    }

    // -------------- here the new value is emitted ...
    if (opts.emitEvent !== false) {
      (this.valueChanges as EventEmitter<any>).emit(this.value);
      (this.statusChanges as EventEmitter<string>).emit(this.status);
    }

    // ------------- .. and here, only afterwards, the parent is notified of the change
    if (this._parent && !opts.onlySelf) {
      this._parent.updateValueAndValidity(opts);
    }
  }
```

If you change the order of the emit and the parent propagation it would work as expected I think.

This is likely also the cause of #29273

**Comment by Airblader** [comment]
If you switch the order you get the issue the other way around: listening for group changes will get you the old value when accessing the control directly.

**Comment by lazarljubenovic** [comment]
Maybe I'm misunderstanding something, but if you update everything before emitting anything, you won't get any sort of issues, right? 

1. Update self.
2. Propagate the change to update all ancestors.
3. Emit changes, either bottom-down or bottom-up, but be consistent.

Switching the order in the 3rd step would indeed have the same problem, but based on what OP says, the current flow is 1 -> 3 -> 2 (-> 3 -> 2 -> 3), where (3) happens multiple times, whenever a tree node is updated.

**Comment by AndrewKushnir** [comment]
Closing this ticket based on the replies above. Feel free to reopen if the problem still exists.
