### ISSUE TITLE
Arbritrary bootstrap import is rewritten

### ISSUE THREAD

**Issue by TedSander** [angular/angular#3473]
If an application has a import that ends in bootstrap.dart then it will be rewritten to the boostrap_static.dart import.

Internal b/22943477

**Comment by mhevery** [comment]
I don't think this is P1, as there is an easy work around. demoting to P2. Change if you don't agree.

**Comment by TedSander** [comment]
I think it is more than a P2, but the fix was easy. So I just sent a pull request instead.
