### ISSUE TITLE
New topic: Improving application performance

### ISSUE THREAD

**Issue by aikithoughts** [angular/angular#34735]
# 📚 Docs or angular.io bug report

### Description

We current do not have any documentation about how developers can improve their application's performance. Specifically, we don't discuss bundle sizes and how to analyze them.

Developers would benefit from a new topic that addresses this issue. The topic tentatively would be **Improving application performance** and it would reside under the **Dev Worklow** section.

**Comment by clydin** [comment]
There’s currently a section in the deployment guide touching on these topics: https://angular.io/guide/deployment#measure-performance

**Comment by jbogarthyde** [comment]
Here's another optimization topic (referenced from the `change detection` glossary definition): https://web.dev/faster-angular-change-detection/

**Comment by fr0** [comment]
The section regarding `source-map-explorer` is incorrect for an Angular 9 app.

https://angular.io/guide/deployment#measure-performance

`node_modules/.bin/source-map-explorer dist/main.*.bundle.js`

In an out-of-the-box Angular 9 app, there are no `main.*.bundle.js` files.

```
3rdpartylicenses.txt
favicon.ico
index.html
main-es2015.410f67bfcab58f7f73a1.js
main-es2015.410f67bfcab58f7f73a1.js.map
main-es5.410f67bfcab58f7f73a1.js
main-es5.410f67bfcab58f7f73a1.js.map
polyfills-es2015.8442499f8bb6452f6615.js
polyfills-es2015.8442499f8bb6452f6615.js.map
polyfills-es5.aee0f88bb4fac09c716f.js
polyfills-es5.aee0f88bb4fac09c716f.js.map
runtime-es2015.9788cecebf012972cc0c.js
runtime-es2015.9788cecebf012972cc0c.js.map
runtime-es5.9788cecebf012972cc0c.js
runtime-es5.9788cecebf012972cc0c.js.map
styles.d175786af40bebc98b21.css
styles.d175786af40bebc98b21.css.map
```

**Comment by kapunahelewong** [comment]
Docs team would benefit from engineering input on documenting application performance best practices.

**Comment by jelbourn** [comment]
A point for this doc so I don't forget later: making sure long-stack-traces is off for zones.
