### ISSUE TITLE
can not use template ref from another component because ngAfterViewInit is not getting called because component only has templates

### ISSUE THREAD

**Issue by Jeet-s** [angular/angular#34740]
# 🐞 bug report

### Description

templates.component.html =>
  <ng-template #anchorHeaderTemplate let-column="column">
    <a routerLink="" class="blue_text">{{column.title}}</a>
  </ng-template>

templates.component.ts =>
  import { Component, OnInit, ViewChild, TemplateRef } from '@angular/core';

@Component({
  selector: 'app-templates',
  templateUrl: './templates.component.html',
  styleUrls: ['./templates.component.scss']
})
export class TemplatesComponent implements OnInit {

  @ViewChild("anchorHeaderTemplate", {static: false}) anchorHeaderTemplate: TemplateRef<any>;

  constructor() { }

  ngOnInit() {
  }

  ngAfterViewInit(){
    console.log('template');
  }

}

i am trying to use this template in another component using component resolver but it is not working with static false but working with statuc true

**Comment by Naxirdan** [comment]
Hi @Jeet-s 

I think so you to create a template and use this template inside a component working like _"Components container"_ so, I will say how I use templates with ViewChild:

templates.component.html =>
```
<ul>
    <li *ngFor="let product of products">{{product.name}}</li>
</ul>
```

Then configure the templates.component.ts =>
```
import { AddProuctContainer } from '../add-product-container.component';
import { Component, OnInit, ViewChild, TemplateRef } from '@angular/core';

@Component({
selector: 'app-templateissue',
templateUrl: './templateissue.component.html',
styleUrls: ['./templateissue.component.scss']
})
export class TemplateissueComponent implements OnInit {

@ViewChild(AddProductContainer, {static: false}) anchorHeaderTemplate: AddProductContainer;

constructor() { }

ngOnInit() {
}

  ngAfterViewInit(){
  console.log('template');
  }
}
```

And finally I can use this template like:
`<app-templateissue></app-templateissue>`

This work for me

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
