### ISSUE TITLE
Meta Class not adding Meta lines to DOM timely enough for Discord Link-type Embed

### ISSUE THREAD

**Issue by Nephera** [angular/angular#34744]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

I believe the issue lies in @angular/platform-browser, but I'm not sure that anything can be done.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

I've never been able to get this to work.  

### Description

 A clear and concise description of the problem...

Discord supports Open Graph to display rich embed for links.  The 4 properties that it works with are: og:title, og:site_name, og:description, and og:image.  I've not been able to successfully use Meta.addTag(...) or Meta.addTags(...) to get these properties to add to the DOM in a timely enough manner for the Discord crawler -- which they use to gather the rich embed meta data -- to catch said data.  The only way I've been able to get it to catch the meta data is when it's hard-coded into index.html; and I'd rather not do that, as I'd like it to be possible to display rich embed data in Discord that changes based on the state of the application for a better user experience.  Maybe this issue isn't with Angular as much as it's a problem with the Discord crawler bot, but I don't see the Discord team being willing to make changes to their bot to account for Angular applications.

## 🔬 Minimal Reproduction

 
https://angular-issue-repro2-g7yj9k.stackblitz.io

Though pasting this link into discord doesn't display any metadata; if I were to host it on my personal web server, all I would see is "SITE NAME", as it's hard coded into index.html

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.21
Node: 10.15.3
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.21
@angular-devkit/core         8.3.21
@angular-devkit/schematics   8.3.21
@schematics/angular          8.3.21
@schematics/update           0.803.21
rxjs                         6.4.0

But the project is on 7.3.9, as we have some issues with forms that are not Angular 8 ready.

</code></pre>

**Anything else relevant?**

**Comment by pshurygin** [comment]
Crawlers typically do not execute any Javascript code on a website, that is why we need SSR for them to work correctly with any Javascript based app.
I suggest you to use Angular Universal to implement server side rendering for your application. It will also help with Google crawler and SEO meta tags.

**Comment by Nephera** [comment]
Thank you; I'm confident that SSR will resolve this issue.
