### ISSUE TITLE
Initial Changedetection not working with DynamicComponentLoader

### ISSUE THREAD

**Issue by frickt** [angular/angular#3474]
Changes to newly created Components with DynamicComponentLoader are not detected.

Angular Version alpha.33

An easy example you can find here:

index.ts

    bootstrap(App).then((appRef:ApplicationRef)=>{
        var appComp:Promise<App> = appRef.injector.get(App);
        appComp.then((app) =>{
            app.createLoginView();
        });
    }).catch((e)=>{console.log(e)});

app.html

    <div>
        <div #main>{{msg}}</div>
    </div>

app.ts

    @Component({
        selector: 'app',
        injectables: [DynamicComponentLoader, Injector, ElementRef]
    })
    @View({
        templateUrl: 'src/component/app/app.html',
        styleUrls: ['src/component/app/app.css']
    })
    export class App {
    
        componentLoader:DynamicComponentLoader;
        injector:Injector;
        elementRef:ElementRef;
        msg:string = "Foo";
    
        constructor(loader:DynamicComponentLoader, injector:Injector, elementRef:ElementRef) {
            this.componentLoader = loader;
            this.injector = injector;
            this.elementRef = elementRef;
        }
    
        createLoginView():void {
            this.componentLoader.loadIntoLocation(Login, this.elementRef, "main").then(componentRef=> {
                this.msg = "Bar";
            }).catch(e=>console.log(e));
        }
    }

The provided "Bar" string is not loaded to the app.html and "Foo" is still displayed (Change was not detected). As soon the first event is triggered by any component, the "Bar" msg will shows up. It seems to be an issue within:

            this.componentLoader.loadIntoLocation(Login, this.elementRef, "main").then(componentRef=> {
                this.msg = "Bar";
            }).catch(e=>console.log(e));

If I call createLoginView() from the App constructor and not from the bootstrap Promise, the app.html displays the correct "Bar" msg.

Is there something I'm doing wrong? Thx

**Comment by Fincodr** [comment]
Having this same issue with alpha 34. Can't really use DynamicComponentLoader to load any complex component.

**Comment by ericmartinezr** [comment]
I've found the same behavior in alpha 46 but with `loadAsRoot` (`loadIntoLocation` and `loadNextToLocation` works fine).

Check this plnkr http://plnkr.co/edit/jzeBka8ixDEcDIapWt1B?p=preview

See that `loadIntoLocation` and `loadNextToLocation` prints correctly, but `loadAsRoot` prints nothing. If you uncomment the timeout in `DynamicComponent` constructor it will work.

**Comment by VinnyVicious** [comment]
Any news on this? Lot's and lot's of people having issues as well #6223, #6306.

**Comment by oliverjanik** [comment]
Same problem in beta.0

**Comment by Andy1605** [comment]
The problem still exists in beta7! The router shows the same behavior as well (which uses the DynamicComponentLoader afaik)

**Comment by frickt** [comment]
With RC0 I've switched to the Implementation with ComponentResolver and ViewContainerRef now the issue is resolved and can be closed.

Below my implementation. Is there a better way to work with the parent Injector?

```
  createView(component, viewContainerRef: ViewContainerRef, viewModel: ServerResponse, resolver: ComponentResolver, parentComponentRef: ComponentRef) {
    var injector = ReflectiveInjector.fromResolvedProviders(ReflectiveInjector.resolve([
      provide(ServerResponse, { useValue: viewModel })]),
	  parentComponentRef.injector);

    return this.resolver.resolveComponent(component).then((factory: ComponentFactory<any>) => {
      var componentRef: ComponentRef<any> = viewContainerRef.createComponent(factory, -1, injector);
      return componentRef.instance;
    });
  }
```

**Comment by pkozlowski-opensource** [comment]
The same issue and potential solutions are discussed in #9293. Closing as a duplicate.
