### ISSUE TITLE
Tour of Heroes (toh-pt6): Misleading information on HTTP request response type

### ISSUE THREAD

**Issue by pepiku** [angular/angular#34746]
# 📚 Docs or angular.io bug report

### Description

In section "HttpClient.get() returns response data" the tutorial says:
"HttpClient.get() returns the body of the response as an untyped JSON object by default. Applying the optional type specifier, <Hero[]> , gives you a typed result object."

For me this sentence was very misleading when learning Angular. I was expecting to be able to provide a class type and would get an object instance including all the members of the class - specifically I would be able to call mehods defined in the class.

The class type is only used for syntax check / code-completion, however, during runtime the object returned by the get() method is a plain javascript object as received with the JSON response from the server, with the prototype being "Object". It does not contain any further members of the class.

The tutorial should explain this in more detail, and if there is any best practices on how to transform from the JSON object to a real typed object, this should also be explained or pointed to.

The functionality/feature that a plain JSON object is returned despite of the type being specified is for example discussed here:
https://github.com/angular/angular/issues/20770

### What's the affected URL?**
https://angular.io/tutorial/toh-pt6#httpclientget-returns-response-data

**Comment by ajitsinghkaler** [comment]
@kapunahelewong Can I take this.

**Comment by kapunahelewong** [comment]
Certainly, thank you, @ajitsinghkaler!! 🌸💫

**Comment by kapunahelewong** [comment]
@pepiku does @ajitsinghkaler's PR #34845 clarify it fully for you?

**Comment by pepiku** [comment]
Thanks @ajitsinghkaler @kapunahelewong
