### ISSUE TITLE
ɵrenderComponent with angular forms

### ISSUE THREAD

**Issue by abishekram** [angular/angular#34754]
# 🐞 bug report

In Angular 9,

Instead of  bootstrapping module,

<pre><code>
platformBrowserDynamic().bootstrapModule(BootstrapModule)
</code></pre>

I am rendering components with

<pre><code>
renderComponent(TestFormCompositeComponent
</code></pre>

getting following error

`Cannot inject Renderer2 when the application uses Renderer3!`

TestFormCompositeComponent contains angular reactive form directives. Getting error on injecting directives.

**Comment by pkozlowski-opensource** [comment]
`renderComponent` is _not_ a public API but rather an experimental one that we _might_ open up in the future (in the current or modified form). Please don't use this API for anything else then rough experiments (and expect changes to this API at any point in time).

I'm going to close this issue as you are using non-public API that doesn't support (and is not designed to support) your use case. Thnx for understanding!
