### ISSUE TITLE
Prevent situation where commits on master break downstream projects (google3)

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#3476]
We would like to extend the current presubmit setup to also run some google3 tests with TAP. This could make the job of the syncmaster easier, because breaking changes would be identified and resolved a lot earlier.

At minimum, we want to report the results back to the committer so they know that downstream breakage exists and start to fix.

Next step to improve it is to avoid these commits going on master. @mhevery and I designed this a bit, and currently the best guess is that each presubmit branch posts the `.tgz` of the dist folder to GCP, then some custom process running internally would fetch this, create the CL, test with TAP, and submit to google3 on pass. If the change is breaking, then a core team member has to patch that CL, fix the downstream breakages, then submit. After submit to google3, these changes would be automatically merged to master, so google3 is source of truth and master is lagging.

This is not a great design because of the amount of manual stuff we have to maintain. An alternative is to keep a different github repo (call it `angular-dist`)containing the dist folder (or selected subset) for each presubmit-* branch as well as master. Travis can update `angular-dist` as soon as the build succeeds (doesn't need to run tests) and then we could maybe use more standard tooling like MOE to do the rest of the merging and testing. However, this is a problem because the `angular-dist` can't be re-based like the original sources can, so it's hard to keep it up-to-date with respect to moving master.

**Comment by gdi2290** [comment]
can I have nightly builds?

**Comment by alexeagle** [comment]
we already publish snapshot builds to Google Cloud Storage, but they are keyed by commit SHA. Does that help you?
For example the last commit on angular/angular was 450d3630cc2eb5afdbb535334d647a830badf91c

And you can get the JS build result from

https://storage.googleapis.com/angular2-snapshots/450d3630cc2eb5afdbb535334d647a830badf91c/js/dist.tgz

**Comment by alexeagle** [comment]
Note, we've abandoned this for now, because we are doing a weekly manual sync process, and because we didn't  figure out a good solution for re-basing the `angular-dist` repo.

**Comment by alexeagle** [comment]
Would also help to have some open-source users on the nightly/hourly build to catch problems sooner.

**Comment by mhevery** [comment]
closing per https://github.com/angular/angular/issues/3476#issuecomment-140135737
