### ISSUE TITLE
Consolidate tutorials and make them IDE independent.

### ISSUE THREAD

**Issue by aikidave** [angular/angular#34766]
# 📚 Docs or angular.io bug report

### Description

The Angular documentation has two tutorials, each covering much of the same functionality. As a new Angular developer, it's very confusing to do one tutorial, only to discover another one. In addition, the Tour of Heroes tutorial states in the introduction: "You don't have to do this, but Tour of Heroes is all through the rest of the docs, so you should probably read about it anyway." (I'm paraphrasing, of course. :) )

We should consolidate our getting started tutorials from two to one. In addition, we should make them IDE independent, so the user can choose if they want to use StackBlitz, VS Code, or any other environment. 

My initial recommendation is that we should revamp Tour of Heroes, unless there is statistical evidence that suggests the Phone App tutorial is better received by the community.

**Comment by kapunahelewong** [comment]
Status: This is part of an ongoing effort to improve the doc set.

**Comment by aikidave** [comment]
Closing this issue not because we shouldn't still consider it, but because having the two tutorials isn't (at present) causing any struggles within the Angular community. And we did move the Tour of Heroes tutorial to a separate section.
