### ISSUE TITLE
ngModel/formControl for Programatically created components

### ISSUE THREAD

**Issue by fkolar** [angular/angular#34780]
# 🚀 feature request

### Description

Even there is a API  (`ComponentFactoryResolver`, `ViewContainerRef `) to create programatically component as of now there is no way to hook in Form API, just like you would use it traditionally. 

Right now I am more refering to a Form Input components that needs to be instantiated from the code and even I can connect each and every binding there is no clean way to attach `ngModel` or `formControl`.

just like you would this:

```html
<my-input [(ngModel)]="object.name"></my-input>
```

You shoudl be able to achive the same programatically. In other words add ngModelDirective from code

Are there any plans for this? 

### Describe the solution you'd like

Ideally it should be treated as any other bindings.

**Comment by neofuture** [comment]
I think this is the same as my issue 

https://github.com/angular/angular/issues/33654

**Comment by fkolar** [comment]
@neofuture neofuture You are right this is the same thing. Even I do bind ngModel in NG8 but this is more hackish way where I manually instantiate NgModel but its bad, it shoudl be supported as this is one of the elementary thing you can think of.

**Comment by mlc-mlapis** [comment]
@fkolar To bind to what? That component and its template work as pairs. The template can bind only to the public properties/methods of it component class.

**Comment by fkolar** [comment]
@mlc-mlapis Let me give example:

When working programatically with components (e.g I have Custom Input Components), you use:
1. ComponentFactoryResolver to create a `ComponentFactory`
2. You can use this one, to get hold of all the `@Inputs` and `@Outputs` metadata
3. And then interate over each given input to set your data

For Example I have component like this. 

```
@Component(select:"my-super-input"  ..)
class MySuperSmartTextArea implement ControlValueAccessor {..}
```

- Since its implements `ControlValueAccessor ` it supports Form API  which allows me to do someting like this, if I would use this component in the template directly (but where are instantiating it and placing into the view from code)

```
  <my-super-input  [(ngModel)]="myValue">
</<my-super-input>
```
  To set a ngModelDirective that acts just like another bindings since my Component implements `ControlValueAccessor`

- Before next steps 4 which would be 
  4.  Use viewContainer to add Component to the View

You want to set this programatically. In other words you want to have a way to set ngModelDirective from Code. 

This is what is this ticket about.

**Comment by neofuture** [comment]
There is a repo on the other thread that shows this in action, not working as it should

**Comment by fkolar** [comment]
> There is a repo on the other thread that shows this in action, not working as it should

This is what I was about to coment, your things is a bit different you try to instantiate a whole component which has a template with the ngModel, I try I want to attach ngModel directive to the a component from Code.

**Comment by mlc-mlapis** [comment]
@fkolar Hmm, you are saying that you want to use directives programmatically, right? This feature has never been a part of Angular. So this is not an issue, but a new feature request. This theme was and is discussed and is on the plan, but it was decided that it'll be implemented after the new Ivy renderer will be stabilized in the stable version. It means that it won't be Angular 9.0 for sure. Probably some 9.x, not sure exactly which one.

**Comment by fkolar** [comment]
Yes, this why this is feature! Even I have a solution to this, I dont like it as it can break anytime since its not standard API or anything. 

I have discussed this several times with team long time ago. but now its we have a new compiler it might be something to think about. 

We can think of generic support to have API to attach directives or this might be special case to connect only Form API

**Comment by mlc-mlapis** [comment]
@fkolar I think it has to be a generic API, the ability to attach any directive to any component.

**Comment by rojasjandro89** [comment]
This is a long-needed feature (not exactly this scenario but the ability to attach directives to dynamically instantiated components)... I'm sorry I miss the vote 😞

**Comment by lukeyt** [comment]
I managed a workaround (for anyone else that needs something like the original) - my use case was to be able to mark dirty / touched / errors for a custom component that would propagate up to the parent form, where the custom component was added dynamically.   

In the component definition I added     `viewProviders: [{ provide: ControlContainer, useExisting: NgModelGroup }]`

So anything in the component would propagate up (you could switch NgModelGroup for NgForm).  Then in the component template I added another ngModelGroup wrapping the rest of the template.  Using this approach, and with an `@ViewChild` reference in the code I could at least programmatically call `markAsDirty()` or `setErrors` and this gave me what I needed.

**Comment by dylhunn** [comment]
Closing due to not enough votes/community interest.
