### ISSUE TITLE
does V9 actually exists?

### ISSUE THREAD

**Issue by gmareater** [angular/angular#34785]
At first, I thought you are holding back to release v9 as a gift for new year, 
but now i feel we need Jesus hand for this version to be delivered. 

V9 dream is turning to V9 RC nightmare

would you at least, provide some info for us?

**Comment by mlc-mlapis** [comment]
@gmareater Why are you so impatient?

**Comment by DaSchTour** [comment]
I think it's better if some have a RC nightmare and not everybody having an upgrade nightmare 😄

**Comment by neofuture** [comment]
The RC versions have been great, and im willing to wait for a good release instead of a rushed release

**Comment by neofuture** [comment]
@gmareater is a typical script kiddie, all his repo's are forked from some one else's work, and yet he has the gumption to come here and complain to the @angular team, disgusting... maybe people like you should be made to pay for it !

**Comment by pkozlowski-opensource** [comment]
We are going to cut the final v9 release as soon as we are satisfied with its non-regression testing results (ex.: no more important issues reported on GitHub). I understand that everyone would like to get v9 ASAP and we want to release as soon as possible - but not before we are confident that people will have good time upgrading to it.

If anyone wants to help out with getting v9 out of the doors please take the latest RC for a test ride and report issues if you bump into any problems.

I'm going to close this issue as there is no additional actions here for us (on top of the work we are already doing).

**Comment by vitaly-t** [comment]
@gmareater How dare you come here and stump upon sensitive character of angular masters! They can PR you out of GitHub, and commit the unthinkable on your grave for your free thinking.

**Comment by neofuture** [comment]
Im using RC9 myself as we speak, i still have the constant repainting issue with [ngStyle] and [ngClass] hoping that will be fixed soon as its still open 

https://github.com/angular/angular/issues/34336

**Comment by pkozlowski-opensource** [comment]
@neofuture we've got a PR (#34307) in review to fix #34336 - should be part of the next RC release.

**Comment by neofuture** [comment]
Thanks @pkozlowski-opensource cant wait, excellent work

**Comment by gmareater** [comment]
> @gmareater is a typical script kiddie, all his repo's are forked from some one else's work, and yet he has the gumption to come here and complain to the @angular team, disgusting... maybe people like you should be made to pay for it !

so you are here to insult and judge other people, good for you

**Comment by gmareater** [comment]
> We are going to cut the final v9 release as soon as we are satisfied with its non-regression testing results (ex.: no more important issues reported on GitHub). I understand that everyone would like to get v9 ASAP and we want to release as soon as possible - but not before we are confident that people will have good time upgrading to it.
> 
> If anyone wants to help out with getting v9 out of the doors please take the latest RC for a test ride and report issues if you bump into any problems.
> 
> I'm going to close this issue as there is no additional actions here for us (on top of the work we are already doing).

thanks for your answer, whole point is, "I'm sure you are working hard and we appreciate it and it would be nice if you _more communicate_ and let us know there will be delay"

**Comment by Splaktar** [comment]
@gmareater there has been some communication about the delay through various channels like https://twitter.com/jules_kremer/status/1206645952548720640. It's understandable that more widely available communication through official channels could be desirable for portions of the community.

@neofuture while he was complaining and opening a GitHub issue asking for updates is not recommended (please use Gitter, Twitter, devrel@angular.io, etc) that does not give you license to insult or personally attack him. Please make sure that you follow the [Code of Conduct](https://github.com/angular/angular/blob/master/CODE_OF_CONDUCT.md).

**Comment by spock123** [comment]
FWIW I think we are super close now.. you can tell by the short bugfix list on RC10... this is a classic sign of good things to come very soon.

**Comment by neofuture** [comment]
Im using RC10 and you can get by thats for sure, there is a small issue which i believe is sorted, which will be in next RC but its good to go in my opinion, i can develop in it
