### ISSUE TITLE
Automate the creation of presubmit-* branches

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#3478]
Discussed a design with @mhevery where we could speed up angular developers a bit, by reacting to the creation of the `PR: merge` label.

The idea is to run a small AppEngine app, and register it as a webhook on github for the issue modification event. If the modification is that the merge label was added, AND it was added by a trusted party (a core contributor and/or maybe a googler), then we'd create the presubmit branch pointed at the SHA that was 'approved' in this way. We can do this with a simple HTTP API call to github, creating the ref (as we do currently to create and move the g3sync branch ref)

**Comment by btford** [comment]
:+1:

**Comment by mhevery** [comment]
DONE: https://github.com/mhevery/angular2-automation and WORKING: https://github.com/angular/angular/pull/3552
