### ISSUE TITLE
Re-navigating to a the same url during an active navigation causes cancellation without a new navigation starting

### ISSUE THREAD

**Issue by mitchellwills** [angular/angular#34795]
# 🐞 bug report

### Affected Package
`@angular/router`

### Is this a regression?
No

### Description

While the router is in the route activation phase if it receives another navigation request that results in the same url the active navigation will be canceled, but the new navigation won't start. This only occurs when `onSameUrlNavigation=false` (the default). I would expect that a NavigationEnd event would be emitted for either the first or replacement navigation, but currently one is never emitted.

## 🔬 Minimal Reproduction
https://angular-fz4k5d.stackblitz.io
Click the "Test" link to navigate to navigate to `/test?query=someText`

```
NavigationStart {id: 1, url: "/", navigationTrigger: "imperative", restoredState: null}
RoutesRecognized {id: 1, url: "/", urlAfterRedirects: "/404", state: RouterStateSnapshot}
GuardsCheckStart {id: 1, url: "/", urlAfterRedirects: "/404", state: RouterStateSnapshot}
ChildActivationStart {snapshot: ActivatedRouteSnapshot}
ActivationStart {snapshot: ActivatedRouteSnapshot}
GuardsCheckEnd {id: 1, url: "/", urlAfterRedirects: "/404", state: RouterStateSnapshot, shouldActivate: true}
ResolveStart {id: 1, url: "/", urlAfterRedirects: "/404", state: RouterStateSnapshot}
ResolveEnd {id: 1, url: "/", urlAfterRedirects: "/404", state: RouterStateSnapshot}
ActivationEnd {snapshot: ActivatedRouteSnapshot}
ChildActivationEnd {snapshot: ActivatedRouteSnapshot}
NavigationEnd {id: 1, url: "/", urlAfterRedirects: "/404"}
Scroll {routerEvent: NavigationEnd, position: null, anchor: null

### Click test link
NavigationStart {id: 2, url: "/test?query=someText", navigationTrigger: "imperative", restoredState: null}
RoutesRecognized {id: 2, url: "/test?query=someText", urlAfterRedirects: "/test?query=someText", state: RouterStateSnapshot}
GuardsCheckStart {id: 2, url: "/test?query=someText", urlAfterRedirects: "/test?query=someText", state: RouterStateSnapshot}
ChildActivationStart {snapshot: ActivatedRouteSnapshot}
ActivationStart {snapshot: ActivatedRouteSnapshot}
GuardsCheckEnd {id: 2, url: "/test?query=someText", urlAfterRedirects: "/test?query=someText", state: RouterStateSnapshot, shouldActivate: true}
ResolveStart {id: 2, url: "/test?query=someText", urlAfterRedirects: "/test?query=someText", state: RouterStateSnapshot}
ResolveEnd {id: 2, url: "/test?query=someText", urlAfterRedirects: "/test?query=someText", state: RouterStateSnapshot}

### navigate from component constructor loaded through route activation triggers previous navigation to cancel
### This navigation is also to /test?query=someText
NavigationCancel {id: 2, url: "/test?query=someText", reason: "Navigation ID 2 is not equal to the current navigation id 3"}

### I think these are left over from id=2
ActivationEnd {snapshot: ActivatedRouteSnapshot}
ChildActivationEnd {snapshot: ActivatedRouteSnapshot}

### No NavigationEnd event fires for navigating to /test?query=someText (for id=2 nor id=3)
### No Navigation events fire for id=3
```

## 🌍  Your Environment

**Angular Version:**
`8.2.14`

**Comment by atscott** [comment]
Bumping frequency to medium as this could be somewhat common for guards to cause re-navigations to the same URL.

**Comment by LanderBeeuwsaert** [comment]
Copying this from 34051:

we use the URL to pass parameters to be able to deep link.
So each time you change to another component the URL parameters get updated.
If you have 3 nested components, it means you have 3 URL parameters.

If you then go to another component, where the 3 nested components are destroyed, it should clean up the URL parameters in the ngOnDestroy of the components.

You could of course start to get fancy and create a specific service to do this, and let that service do the clean sequentually with setTimeouts, but that is complicating things unneccesarily and should not be necessary in my opinion.

**Comment by benelliott** [comment]
This causes problems for us as we use router guards to add and remove UI breadcrumbs. When a route is activated, the breacrumb is added. When a route is deactivated, the breadcrumb is removed. A cancel event is (rightly IMO) interpreted as an aborted deactivation and so the breadcrumb is not deactivated. The current behaviour of `@angular/router` leaves dangling breadcrumbs which due to the cancel event are not removed even though the navigation completed successfully.

**Comment by ammarvehbi** [comment]
any update on the issue?

**Comment by sparkeplug** [comment]
Any updates or workarounds for this issue ?

**Comment by YogliB** [comment]
This is still happening on Angular@10, when re-navigation is triggered from inside of a Guard.

**Comment by LucasLopesr** [comment]
any update on the issue?

**Comment by zhengsansan** [comment]
这个问题有解决方案吗？

**Comment by zhengsansan** [comment]
> 这个问题有解决方案吗？
原因分析：
经过跟踪代码，我发现是因为在组件ngOnDestroy的时候重复调用了一次路由跳转的方法，然而this.router.navigate每执行一次navigationId就会+1，这样就造成了navigationId不匹配，路由事件被取消；
解决办法：
删除组件中ngOnDestroy里重复调用navigate的方法，问题解决之。同理，其它类似的问题也因该是路由的重复调用引起的，建议大家仔细排查代码，删除重复的里有调用即可。

**Comment by andreyjamer** [comment]
In #42273 @atscott proposed a workaround:
You can navigate inside a `setTimeout` or `Promise.resolve.then(...)`: [https://stackblitz.com/edit/angular-ivy-um7fof?file=src%2Fapp%2Fpage.service.ts](https://stackblitz.com/edit/angular-ivy-um7fof?file=src%2Fapp%2Fpage.service.ts)
