### ISSUE TITLE
[DecimalPipe] support compact decimals like goog.i18n.NumberFormat

### ISSUE THREAD

**Issue by jermowery** [angular/angular#34790]
# 🚀 feature request

### Relevant Package
@angular/common
DecimalPipe

### Description
The DecimalPipe does not support compact decimals eg, "10K" instead of "10,000" in English (US) or "10 mil" in Portuguese (Brazil). goog.i18n.NumberFormat does support this (https://google.github.io/closure-library/api/goog.i18n.NumberFormat.html). Can more formatting options similar to COMPACT_SHORT and COMPACT_LONG from goog.i18n.NumberFormat be supported in the DecimalPipe?

### Describe the solution you'd like
The ability to specify a format for compact decimals.

### Describe alternatives you've considered

Use goog.i18n.NumberFormat instead of DecimalPipe

**Comment by petebacondarwin** [comment]
This is not a trivial addition and would add to the size of `@angular/common`. I am not sure it would be easy to tree-shake out for users of the DecimalPipe...
