### ISSUE TITLE
Ivy rebuild regression in AOT

### ISSUE THREAD

**Issue by SebastianPodgajny** [angular/angular#34796]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this problem was not present was: 9.0.0-rc.2

### Description

In rc.2 ivy rebuild time in aot was much smaller 
main.ts ~6s
app.component.ts ~6s
app.component.html ~6s
component-in-some-large-module.ts ~11s
component-in-some-large-module.html ~6s
component-in-some-large-module.less ~6s
some-small-lib.service.ts ~9s
component-in-small-module.ts ~6s
component-in-small-module.html ~5s
component-in-small-module.less ~6s

I think during beta phase rebuild time was even smaller, currently rebuild is ~20s no matter what I change in project

Here is benchmark for rc.9, 4th rebuild of main.ts
```
AngularCompilerPlugin._createOrUpdateProgram.ng.createProgram: 673.898ms
TypeChecker.gatherDiagnostics.ng.getNgSemanticDiagnostics: 31997.621ms
TypeChecker.message: 42739.608ms
AngularCompilerPlugin._createOrUpdateProgram.ng.loadNgStructureAsync: 11908.510ms
AngularCompilerPlugin._listLazyRoutesFromProgram.listLazyRoutes: 0.008ms
AngularCompilerPlugin._emit.ng.getNgStructuralDiagnostics: 0.004ms
AngularCompilerPlugin._emit.ng.gatherDiagnostics.ng.getTsSyntacticDiagnostics: 0.704ms
AngularCompilerPlugin._emit.ng.emit: 268.480ms
AngularCompilerPlugin._emit: 269.340ms
AngularCompilerPlugin._update._emit: 269.373ms
AngularCompilerPlugin._update: 13207.579ms
AngularCompilerPlugin._make: 13207.612ms
ngcLoader+/app/src/main.ts+.ngcLoader.AngularCompilerPlugin: 12065.946ms
ngcLoader+/app/src/main.ts+: 12066.811ms

Date: 2020-01-15T20:34:10.851Z - Hash: a7f06110bf2383093fdc
21 unchanged chunks
chunk {main} main.d2ddedbc0eb7b60a0ccf.js, main.d2ddedbc0eb7b60a0ccf.js.map (main) 24.8 MB [initial] [rendered]
Time: 18985ms
: Compiled successfully.
TypeChecker._update: 0.144ms
TypeChecker._createOrUpdateProgram.ng.createProgram: 360.438ms
TypeChecker.gatherDiagnostics.ng.getTsSemanticDiagnostics: 9293.606ms
```

Above numbers are for large monorepo app which source code contains about 160k typescript lines of code and 950 Components

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.8
Node: 12.10.0
OS: darwin x64

Angular: 9.0.0-rc.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.6
@angular-devkit/build-angular      0.900.0-rc.8
@angular-devkit/build-ng-packagr   0.900.0-rc.8
@angular-devkit/build-optimizer    0.900.0-rc.6
@angular-devkit/build-webpack      0.900.0-rc.8
@angular-devkit/core               9.0.0-rc.8
@angular-devkit/schematics         9.0.0-rc.8
@angular/cdk                       9.0.0-rc.4
@angular/cli                       9.0.0-rc.8
@ngtools/webpack                   9.0.0-rc.8
@schematics/angular                8.0.1
@schematics/update                 0.900.0-rc.8
ng-packagr                         9.0.0-rc.7
rxjs                               6.5.4
typescript                         3.6.4
webpack                            4.41.2

Model Name:	MacBook Pro
Processor Name:	6-Core Intel Core i7
Processor Speed:	2,2 GHz
Memory:	16 GB
macOS 10.15.1 (19B88)
</code></pre>

**Anything else relevant?**

**Comment by SebastianPodgajny** [comment]
benchmark for VE AOT on rc.9 4th change of main.ts
```
AngularCompilerPlugin._createOrUpdateProgram.ng.createProgram: 1.015ms
AngularCompilerPlugin._createOrUpdateProgram.ng.loadNgStructureAsync: 11496.472ms
AngularCompilerPlugin._listLazyRoutesFromProgram.listLazyRoutes: 0.509ms
AngularCompilerPlugin._emit.ng.getNgStructuralDiagnostics: 0.008ms
AngularCompilerPlugin._emit.ng.gatherDiagnostics.ng.getTsSyntacticDiagnostics: 2.206ms
AngularCompilerPlugin._emit.ng.emit: 7585.733ms
AngularCompilerPlugin._emit: 7588.128ms
AngularCompilerPlugin._update._emit: 7588.151ms
AngularCompilerPlugin._update: 19241.541ms
AngularCompilerPlugin._make: 19241.581ms
ngcLoader+/app/src/main.ts+.ngcLoader.AngularCompilerPlugin: 19084.047ms
ngcLoader+/app/src/main.ts+: 19084.862ms
ngcLoader+/node_modules/@angular/router/router.ngfactory.js+.ngcLoader.AngularCompilerPlugin: 483.996ms
ngcLoader+/node_modules/@angular/router/router.ngfactory.js+: 484.290ms
TypeChecker._update: 1.571ms
TypeChecker._createOrUpdateProgram.ng.createProgram: 0.626ms

Date: 2020-01-16T08:50:56.938Z - Hash: 92efc5b02292a55b70e0
23 unchanged chunks
chunk {main} main.bf125d761389c42d9d2e.js, main.bf125d761389c42d9d2e.js.map (main) 33.4 MB [initial] [rendered]
Time: 22919ms
: Compiled successfully.
```

**Comment by elvisbegovic** [comment]
Hi,

Did you move from RC2 directly to RC9 and observe that ? If you can't share your project or make a repro, can you maybe try to determine what version right after rc2 you get the slowness ?

As I know rc2 release was not quite correct. 

I did same error: your issue is on `angular/angular` can you instead complete your measures with `ngc` command (CLI does others stuff). Run `ngc -p your.tsconfig.app.json --watch --diagnostics`

Another good thing you can do for the team is share a `.cpuprofiler` file of a rebuild with **RC9**. If  you don't know  (thanks to @filipesilva) you can follow his instruction here https://github.com/angular/angular-cli/issues/8259#issue-269908550
The only difference is the point :
- In your package.json, add the following NPM script:

Where you must have this command `"debug": "node  --max-old-space-size=8192 --inspect-brk ./node_modules/@angular/compiler-cli/src/main.js --watch -p tsconfig.app.json"`

note: When you click START and when your rebuild complete, it is good to wait aproximately 10s before click STOP to be sure all is finished adn to get isolated capture of a rebuild. (if on top of that you do this with rc2 too i think it is even better)

You can inspire by some instructions here too https://github.com/angular/angular/issues/33986

**Comment by alxhub** [comment]
Without a reproduction, it's very hard to investigate issues like this one. We'll run some tests, but an example repo of the same shape (even if the components aren't terribly complex) for which the problem triggers would go a long way.

**Comment by SebastianPodgajny** [comment]
@angular/* rc.9 including CLI
`node  --max-old-space-size=8192 ./node_modules/.bin/ngc -p tsconfig.app.json --watch --diagnostics`

```
Time for diagnostics: 27097ms.
Emitted in 41712ms
- 2456 user ts files
- 1716 generated ts files
- 1947 generated json files
Total time: 69s

Time for diagnostics: 24250ms.
Emitted in 6795ms
- 1 user ts files
- 0 generated ts files
- 971 generated json files
Total time: 31s

Time for diagnostics: 20838ms.
Emitted in 6669ms
- 1 user ts files
- 0 generated ts files
- 0 generated json files
Total time: 28s

Time for diagnostics: 21941ms.
Emitted in 8021ms
- 1 user ts files
- 0 generated ts files
- 0 generated json files
Total time: 30s

Time for diagnostics: 23601ms.
Emitted in 6732ms
- 1 user ts files
- 0 generated ts files
- 0 generated json files
Total time: 30s

Time for diagnostics: 23056ms.
Emitted in 6620ms
- 1 user ts files
- 0 generated ts files
- 0 generated json files
Total time: 30s

Time for diagnostics: 23517ms.
Emitted in 5861ms
- 1 user ts files
- 0 generated ts files
- 0 generated json files
Total time: 29s
```

**Comment by SebastianPodgajny** [comment]
@angular/* rc.9 including CLI
`node --max-old-space-size=8192 ./node_modules/.bin/ngc -p tsconfig.app.json --watch --diagnostics`

```
Time for diagnostics: 48646ms.
Total time: 90s

Time for diagnostics: 32206ms.
Total time: 33s

Time for diagnostics: 38384ms.
Total time: 39s

Time for diagnostics: 34005ms.
Total time: 34s

Time for diagnostics: 45613ms.
Total time: 47s

Time for diagnostics: 38707ms.
Total time: 39s

Time for diagnostics: 36567ms.
Total time: 37s
```
CPU profile
https://drive.google.com/file/d/1tQs-Lqz1_hu4j8aV4zTqb3HHMCFwaHfk/view?usp=sharing

**Comment by JoostK** [comment]
Hi @SebastianPodgajny,

thanks for the CPU profile, this gives some insight in where time is being spent. What's hard about having only a CPU profile is that the effect of improvements cannot be easily measured, and being able to see the results of a certain optimization is key in pursuing the right optimizations. Do you see any possibility to share (privately) your repo or parts of it? That would be hugely beneficial to address performance bottlenecks.

**Comment by SebastianPodgajny** [comment]
Unfortunately it is not possible, I hope #34867 will fix my issue. Thanks for trying to help
