### ISSUE TITLE
ngtools2.ts file missing in Angular 9.0.x

### ISSUE THREAD

**Issue by rahulroykumar** [angular/angular#34803]
# 🐞 bug report

### Affected Package
package angular/packages/compiler-cli/

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....8.2.x

### Description

 A clear and concise description of the problem...
ngTools2 file is missing from angular/compiler-cli package Has the file been moved?

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>
Cannot find module '@angular/compiler-cli/ngtools2'
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.8
Node: 10.16.3
OS: win32 x64

Angular: 9.0.0-rc.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.0-rc.8 (cli-only)
@angular-devkit/core         9.0.0-rc.8 (cli-only)
@angular-devkit/schematics   9.0.0-rc.8 (cli-only)
@angular/cdk                 9.0.0-next.2
@angular/material            9.0.0-next.2
@schematics/angular          9.0.0-rc.8 (cli-only)
@schematics/update           0.900.0-rc.8 (cli-only)
rxjs                         6.5.3
typescript                   3.6.4
webpack                      3.12.0

</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Could you please provide a minimum repro in a form of GitHub repository and also list a set of commands you used to reproduce the problem? Thank you.

**Comment by rahulroykumar** [comment]
I may not be able to provide github repo due to security reasons. But can provide a sample repo as to where I am using ngTools 2

const ngTools2 = require("@angular/compiler-cli/ngtools2");
  const host = ngTools2.createCompilerHost({ options });

  const program = ngTools2.createProgram({
    rootNames: entryPoints,
    host,
    options
  });

  const emitResult = program.emit();

**Comment by JoostK** [comment]
Indeed, ngtools2 API has been removed in #33242. Please update your imports to point to just `@angular/compiler-cli` as the API you're using is exported from there.

Please note that the `@angular/compiler` and `@angular/compiler-cli` packages are not considered "public" API in the sense that they can be considered stable. [You can read more about the public API guarantees here](https://github.com/angular/angular/blob/master/docs/PUBLIC_API.md).

**Comment by rahulroykumar** [comment]
Thank you . Yes I just noticed. I was wondering how can I then use functions like createCompilerHost(options:any) , createProgram(pgm:any) and formatDiagnostics(diagnostics:any) which could be easily used from ngTools2 api?
