### ISSUE TITLE
Property '_currentLine' implicitly has type  'any'

### ISSUE THREAD

**Issue by pshurygin** [angular/angular#34807]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler

### Is this a regression?

Yes, the previous version in which this bug was not present was: 9.0.0-rc.8

### Description

rc9 introduces build error with ng serve due to incorrect typings with noImplicitAny enabled.

## 🔬 Minimal Reproduction

I guess any app with rc9+Ivy+noImplicitAny should be affected and the issue is probably not dependent on application code.

## 🔥 Exception or Error
<pre><code>
ERROR in node_modules/@angular/compiler/src/output/abstract_emitter.d.ts:23:17 - error TS7033: Property '_currentLine' implicitly has type
 'any', because its get accessor lacks a return type annotation.

23     private get _currentLine();
                   ~~~~~~~~~~~~
node_modules/@angular/compiler/src/output/abstract_emitter.d.ts:42:17 - error TS7033: Property 'sourceLines' implicitly has type 'any', be
cause its get accessor lacks a return type annotation.

42     private get sourceLines();
                   ~~~~~~~~~~~
node_modules/@angular/compiler/src/output/source_map.d.ts:26:17 - error TS7033: Property 'currentLine' implicitly has type 'any', because
its get accessor lacks a return type annotation.

26     private get currentLine();
                   ~~~~~~~~~~~
</code></pre>


## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.0-rc.9
Node: 10.16.0
OS: win32 x64

Angular: 9.0.0-rc.9
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.900.0-rc.9
@angular-devkit/build-angular              0.900.0-rc.9
@angular-devkit/build-optimizer            0.900.0-rc.9
@angular-devkit/build-webpack              0.900.0-rc.9
@angular-devkit/core                       9.0.0-rc.9
@angular-devkit/schematics                 9.0.0-rc.9
@angular/cdk                               9.0.0-rc.7
@angular/material                          9.0.0-rc.7
@ngtools/webpack                           9.0.0-rc.9
@nguniversal/module-map-ngfactory-loader   9.0.0-next.9
@schematics/angular                        9.0.0-rc.9
@schematics/update                         0.900.0-rc.9
rxjs                                       6.5.3
typescript                                 3.6.4
webpack                                    4.41.2

</code></pre>

**Comment by JoostK** [comment]
Fix here: #34798

**Comment by JoostK** [comment]
Closing as #34798 has just been merged, will be available in the next RC. For now, you'll have to set the `skipLibCheck` compiler error to `false` to avoid the error.

**Comment by marcj** [comment]
Setting `"skipLibCheck": false` under `compilerOptions` in `tsconfig.json` does not avoid that error.

**Comment by JoostK** [comment]
> Setting `"skipLibCheck": false` under `compilerOptions` in `tsconfig.json` does not avoid that error. You have to set it to `true`.

Thanks for clearing that up, Marc! I changed the comment. Inverse logic hurts my brain :-)

**Comment by Splaktar** [comment]
We ran into this while updating material.angular.io as well. Glad to see the quick turnaround on the fix!

I wonder if it will be 6 more days before another RC? 🤔
