### ISSUE TITLE
[ivy] ngClass can clash with other class setters, resulting in invalid "[MAP]" class

### ISSUE THREAD

**Issue by henry-alakazhang** [angular/angular#34802]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core or @angular/common 9.0.0-rc.8

### Is this a regression?
Yes, it works with Ivy disabled.

### Description
Using the `[ngClass]` directive alongside other class setters can result in the class becoming (or containing) an invalid `[MAP]` value.

For example, the following components:
```ts
export class ChildComponent {
  @HostBinding("class.FromChild") isChild = true;
}
```
```html
<app-child [ngClass]="{ FromParent: true }"></app-child>
```

One would expect both `FromChild` and `FromParent` classes to be applied. This is the case in View but not Ivy.

In VE:
![image](https://user-images.githubusercontent.com/8922125/72481890-f9a2f680-384f-11ea-9aca-9f8c4f4228b8.png)

In Ivy:
![image](https://user-images.githubusercontent.com/8922125/72481697-75507380-384f-11ea-9eb0-eace2c9371a2.png)

The same thing _can_ also happen for `class` attribute bindings, but I couldn't get a simple reproduction and it's fairly easy to avoid. Host-bound classes are useful for shared components and UI libraries though so this seems like a more valid use case to me.

This can be worked around by only setting attributes in `HostBinding`s and using attribute selectors for css instead. If that's the accepted solution feel free to close this ticket as working as intended.

## 🔬 Minimal Reproduction
This branch of this repo:
https://github.com/henry-alakazhang/angular-ivy-repros/tree/ngclass-hostbinding-clash

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.8
Node: 12.4.0
OS: linux x64

Angular: 9.0.0-rc.8
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.8
@angular-devkit/build-angular     0.900.0-rc.8
@angular-devkit/build-optimizer   0.900.0-rc.8
@angular-devkit/build-webpack     0.900.0-rc.8
@angular-devkit/core              9.0.0-rc.8
@angular-devkit/schematics        9.0.0-rc.8
@angular/localize                 9.0.0-rc.0
@ngtools/webpack                  9.0.0-rc.8
@schematics/angular               9.0.0-rc.8
@schematics/update                0.900.0-rc.8
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Comment by alexzuza** [comment]
Can be also reproduced on rc9 https://ng-run.com/edit/ozFjyRhVdmmLaxFJL6nt?open=app%2Fapp.module.ts&aot=true

**Comment by pkozlowski-opensource** [comment]
I _believe_ that it will be fixed with https://github.com/angular/angular/pull/34804 as this PR rolls back all the changes we did to `NgClass`. We need to confirm, of course, but I'm tempted to say that we've got a PR for this issue.

**Comment by pkozlowski-opensource** [comment]
This was fixed in v9 RC.11
