### ISSUE TITLE
Reactive forms do not work with ControlValueAccessor when ControlValueAccessor's type is array.

### ISSUE THREAD

**Issue by jvanheesch** [angular/angular#34800]
Reproducer can be found here: https://stackblitz.com/github/jvanheesch/angular-reactive-forms-array-model

Explanation:
We have a legacy codebase with custom form components such as CustomFormComponentComponent.
This component works perfectly fine with ng-model & template-driven forms [see in reproducer: select 'Template driven' choice].

Our codebase is now transitioning from template-driven forms to reactive forms.
However, when passing an array to CustomFormComponentComponent using formControlName, somehow (to our surprise) the ControlValueAccessor's val is set to the first element in the array.
This breaks the component, as its ngFor requires an array rather than a regular object.

We really don't want to change our existing custom components, but so far the only workaround we came up with is CustomFormComponentWorkAroundComponent [see in reproducer: select 'Template driven' choice].
Instead of passing an array, we now pass an object containing a single property containing the array.

Could anyone please confirm whether or not this is a bug?
If it's not a bug (i.e. "working as intended"), we'd love to hear if there's an appropriate way to get the desired result (working with reactive forms) without modifying our existing components (ControlValueAccessors).

**Comment by Airblader** [comment]
You need to either use `FormBuilder#array` or wrap the values into an array:

```
records: [[{text: 'ghi'}, {text: 'jkl'}]],
```

Also note that your CVA is implemented incorrectly as a model->view change should not trigger the change/touch handlers.

**Comment by jvanheesch** [comment]
I cannot believe I didn't think about wrapping it in an array...
Thank you for your quick response, it was very helpful and solved my issue.

**Comment by AndrewKushnir** [comment]
Hi, it looks like the question is resolved, so I'm closing this ticket. Thank you.
