### ISSUE TITLE
[i18n] docs for @angular/localize

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular#34822]
# 📚 Docs or angular.io bug report

### Description

It would be great if documentation for `@angular/localize` is available.

**Comment by klemenoslaj** [comment]
It would be nice if the documentation in regards to Angular Libraries (_generated trough `ng generate library` command_) would be included in the documentation.

Commonly we should be importing `@angular/localize/init` into the `polyfills.ts` that's clear.
It becomes interesting in case we develop a library with the usage of `$localize` should each library be importing `@angular/localize/init` as well since otherwise it fails building?
The same for the `test.ts` file of libraries - tests fail to execute if the import is not there.

**Comment by petebacondarwin** [comment]
If you are using Angular CLI then for v9.0.0 you just need to be aware of whether your app or any of the libraries it depends upon at `i18n` tags to their templates. If so, then you will need `$localize` support. 

It should be enough to just run `ng add @angular/localize` (note that until 9.0.0 you need to do `ng add @angular/localize@next` to get the correct version). The schema that is supplied with this package will update the `polyfills.ts` to ensure that the app works correctly.

This is explained in the i18n docs. See https://next.angular.io/guide/i18n.  Please post a specific issue if there is something missing, confusing or incorrect in that guide. (Note that once 9.0.0 is released this information will be available in the stable docs site at https://angular.io/guide/i18n).

Other than that for v9.0.0, the new `$localize` features are all internal and so are not supposed to be used directly by the application/library developer, for now.

**Comment by klemenoslaj** [comment]
@petebacondarwin will the library that needs localization even build individually without having `@angular/localize/init` import as well?

**Comment by miki995** [comment]
How to build app in multiple languages, how to set default language build folder to be in root?
@petebacondarwin 

Look at my problem: https://github.com/angular/angular/issues/35518

**Comment by xiaoxiangmoe** [comment]
@petebacondarwin  Is there any document for `loadTranslations`?

**Comment by petebacondarwin** [comment]
> Other than that for v9.0.0, the new $localize features are all internal and so are not supposed to be used directly by the application/library developer, for now.

As I said none of this is a public API at this stage. So if you want to try playing with it, then you are definitely outside of what is supported. The best way to do this is to look at the source code https://github.com/angular/angular/blob/master/packages/localize/src/translate.ts#L19-L36
