### ISSUE TITLE
[ivy] using a template reference before its declaration causes ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by Shijir** [angular/angular#34821]
# 🐞 bug report

### Affected Package
Angular 9-rc.9 with Ivy

### Is this a regression?

This issue is present only when Ivy is enabled. I have to say that I am not 100% sure it's a bug. It could be the pattern we have been using might not have been supported by Angular in the first place. But I have my own doubts as I explained below.

### Description

Below is a simplified reproduction of the pattern that's causing the `ExpressionChangedAfterItHasBeenCheckedError` error. The following snippet would work just in any Angular version as long as Ivy is not enabled:
```html
<h1>Greetings, {{hello.name}}!</h1>
<hello-comp #hello [name]="'John'"></hello-comp>
```
As you can see, I'm simply template-referencing a component and interpolating its `name` property right above it. 

One thing to note here is that if you move the interpolation down below the `hello-comp`, I see there is no error:
```html
<hello-comp #hello [name]="'John'"></hello-comp>
<h1>Greetings, {{hello.name}}!</h1>
```

So basically, Ivy is not happy when the template reference is used before its declaration. However, we had been using this pattern without any issues before Ivy. Also, I suspected that this pattern (using a template reference before its declaration) could have been something Angular has never supported. But in the documentation, I read these:

- _The scope of a reference variable is the entire template._
- _You can refer to a template reference variable anywhere in the component's template_

So it seems to me at least using a template reference before its declaration has always been supported/allowed. But when Ivy is enabled, it starts throwing the error. As such, I am suspecting this could be another ivy related bug.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-8-template-reference-interpolation

**Comment by pkozlowski-opensource** [comment]
@Shijir thank you for the issue report and the minimal / clear description of the problem.

Indeed with ngIvy we've changed the order in which bindings are evaluated. As you've rightly observed:

> So basically, Ivy is not happy when the template reference is used before its declaration.

With ngIvy we've decided to change the binding evaluation order. This was mostly done to have a simpler / more predictable evaluation order where users can _know_ what is going to happen (previous order was hard to predict and implement in the framework).

>  However, we had been using this pattern without any issues before Ivy.

Right. While it _used to work_ before it wasn't really _intended_. Still, it seem like you really on this behaviour in your application(s) and we would like to better understand your use-case. I guess that the example you've provided is a "proxy" for a real life-use case. Would you mind sharing more details, describing real-life use-cases where ivy approach gives you headaches? You are totally right that technically it _is_ a breaking change and we still debate internally bindings order. As such real-life usages data would help us better understand the severity of this change. Thnx!

**Comment by Airblader** [comment]
@pkozlowski-opensource Would this also make something like this fail (this is a real-life scenario in our apps, unfortunately I cannot test them with Ivy RC at the moment):

```
<button appMenuTrigger [appMenu]="myMenu"></button>

<!-- … -->

<app-menu #myMenu>
    <button appMenuItem>…</button>
</app-menu>
```

**Comment by pkozlowski-opensource** [comment]
@Airblader I would _tend_ to say "it should be fine" as you referencing an _instance_ of `<app-menu>` and this one is available in the create pass (so before bindings are evaluated). Having said this, it is _really_ impossible to tell without testing the exact scenario in its "full glory". Could you please test things on your end and open a new issue if it doesn't? I want to make sure that we keep the discussion focused and it _seems_ to me like your scenario is different from the originally reported. Thnx!

@Shijir wonder if you would have time to share more details about your scenario. Having more info about real-life usage patterns would help us determine the severity of this issue. Thnx!

**Comment by Shijir** [comment]
Hi @pkozlowski-opensource, sorry for not following up sooner. 

To answer your question regarding a real-life use, I've noticed this issue in our Clarity Datagrid component. This is the excerpt of the [template API](https://v2.clarity.design/datagrid/server-driven) that's related to the issue: 

```html
<clr-dg-footer>
        {{pagination.firstItem + 1}} - {{pagination.lastItem + 1}}
        of {{total}} users
        <clr-dg-pagination #pagination [clrDgTotalItems]="total"></clr-dg-pagination>
</clr-dg-footer>
```

As you can see,  the pagination reference expressions are used before its declaration. So because of the Ivy issue, we need to deprecate this API now. Luckily for our users, the following would work just fine and produces the same result without any issues: `clr-dg-pagination`: 

```html
<clr-dg-footer>
        <clr-dg-pagination #pagination [clrDgTotalItems]="total">
               {{pagination.firstItem + 1}} - {{pagination.lastItem + 1}}
        of {{total}} users
        </clr-dg-pagination>
</clr-dg-footer>
```

I think this issue might be just _very specific to component framework/library builders_. So to sum it all up, the template API on our doc would no longer work properly with Ivy enabled, which would make it a breaking change for our users. Therefore, we just need to update the doc and be explicit about this change. But it's not too bad, as our users will be offered another easy way to achieve the same result. This is definitely not a blocking issue for us. It's just that we are trying to limit the number of breaking changes for our users.

**Comment by pkozlowski-opensource** [comment]
@Shijir thnx so much for more details. The way I understand this use-case (and how we've discussed this internally) is that a directive (`<clr-dg-pagination>` in your case) has 2 "roles":
* process inputs and display UI (here: pagination) _based on the inputs_;
* _expose data_ (that is, take inputs, transform those somehow and make available for other expressions to consume);

"expose data" part is what throws a wrench into the whole machinery. At the same time I can see how this could be a useful pattern.

Just to set expectations: I don't think we will be able to "fix" it for v9 with ivy (even if I completely agree that this _is_ a breaking change as compared to VE). I'm saying this that, while this particular use-cases used to work, we are aware of other cases where bindings order is problematic and didn't work well in VE (mostly around forms usage). So we want to take a bit more time and think about the nature of this problem and possible "correct" solutions. As such I would suggest working-around this particular issue for v9. I know that this is not ideal, but I believe that we need to think a bit more to come up with the system that solves your (and other!) issues. 

Again, thnx for sharing your use-case and input - this _is_ super helpful and gives us more data points to make Angular better!

**Comment by acohenOT** [comment]
This error happens when using route animations using the sample code provided [https://angular.io/guide/route-animations#router-outlet](https://angular.io/guide/route-animations#router-outlet)

outlet is used before it's declared
```
<div [@routeAnimations]="prepareRoute(outlet)" >
  <router-outlet #outlet="outlet"></router-outlet>
</div>
```

**Comment by acohenOT** [comment]
More details on the route animation error:

ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for '@routeAnimations': 'undefined'. Current value: 'HomePage'.
```
<div [@routeAnimations]="prepareRoute(outlet)" >
  <router-outlet #outlet="outlet"></router-outlet>
</div>
```
```
  prepareRoute(outlet: RouterOutlet) {
    return outlet && outlet.activatedRouteData && outlet.activatedRouteData['animation'];
  }
```

![debugger_breaks](https://user-images.githubusercontent.com/34688558/75468259-ef017400-595a-11ea-8ae0-50c0716a8a84.jpg)
![debugger_breaks2](https://user-images.githubusercontent.com/34688558/75468263-f0cb3780-595a-11ea-83c9-c5650a557681.jpg)

**Comment by ajitsinghkaler** [comment]
@gkalpak I think we can close this the relevant documentation and why this is the new behavior was added in #36643

**Comment by gkalpak** [comment]
My understanding (by reading this thread above) is that we might want to fix this in the future (not just documenting it as a breaking change). This is not my area of extertise, so I will leave it up for @pkozlowski-opensource or someone else to comment on that.

**Comment by AndrewKushnir** [comment]
Closing this ticket for now since this behavior was documented in #36643. Will reopen if there is a plan to change that in the future. Thank you.
