### ISSUE TITLE
2.0.0-alpha.33 core.js not include bootstrap module?

### ISSUE THREAD

**Issue by kittencup** [angular/angular#3482]
npm install angualr2 .. version 2.0.0-alpha.33 

import {bootstrap} from 'angular2/core';

error....

 import {bootstrap} from 'angular2/angular2';

correct...

**Comment by pkozlowski-opensource** [comment]
Right, this was changed via 329a6e00dca792731748f34e6731de14fe85e9cd. I guess this was deliberate change, although I'm not sure what the motivation was (@mhevery ?). 

@kittencup is it causing any problems for you or is it just about noting a breaking change? Keep in mind that we are still in alpha, so you need to expect several shifts in the public API.

**Comment by kittencup** [comment]
@pkozlowski-opensource  thks.

**Comment by mhevery** [comment]
All imports should be from angular2/angular2. (core is internal API)
