### ISSUE TITLE
Usage of async before-each is wrong or at not described sufficiently

### ISSUE THREAD

**Issue by mmben** [angular/angular#34833]
# 📚 Docs or angular.io bug report

### Description

On the Testing Guide, in section 'Component Test Basics/Component DOM testing/CLI generated tests' there is an example that shows an initial spec file for the banner-external component.
This test contains two before-each() declarations, one of them being async. However, there is nothing inside that is being awaited, thus it is very confusing why the async version of before-each() is used or needed. 
The describing text doesn't mention anything either.

### What's the affected URL?**
https://angular.io/guide/testing

### Reproduction Steps**

https://github.com/angular/angular/blob/master/aio/content/guide/testing.md
https://github.com/angular/angular/blob/master/aio/content/examples/testing/src/app/banner/banner-external.component.spec.ts

### Expected vs Actual Behavior**

Actual:
beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ BannerComponent ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(BannerComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

Expected:

  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [ BannerComponent ]
    })
    .compileComponents();
    fixture = TestBed.createComponent(BannerComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by gkalpak** [comment]
Note, that this is not the `async` JS keyword. It is a regular function named `async` ([docs][1]), which is imported from @angular/core/testing` [here][2]. 

I agree that we might need to clarify this, if it is not explained in the guide.

[1]: https://angular.io/api/core/testing/async
[2]: https://github.com/angular/angular/blob/f2df1c79d/aio/content/examples/testing/src/app/banner/banner-external.component.spec.ts#L3

**Comment by mmben** [comment]
Oh my, what subtile but significant difference!! I did indeed not see that until you pointed it out. Thanks a lot for clarifying.

**Comment by kapunahelewong** [comment]
Chatted with @sonukapoor who would like to take this one. Thank you, @sonukapoor!!

**Comment by JiaLiPassion** [comment]
I also think maybe we need to rename async to asyncTest to avoid such confusion.

**Comment by sonukapoor** [comment]
@JiaLiPassion Do you mean to provide an alias in the import; e.g: `import { async as asyncTest } from '...'`? I imagine renaming the `async` function in `@angular/core/testing` would be a breaking/big change.

**Comment by JiaLiPassion** [comment]
@sonukapoor, yeah, it will be a breaking change, we can still keep `async`, and maybe make it deprecated at some point.
