### ISSUE TITLE
Routing error

### ISSUE THREAD

**Issue by blacksonic** [angular/angular#3483]
Im getting the following error:
``` ORIGINAL STACK: Error: No base href set. Either provide a binding to "appBaseHrefToken" or add a base element. ```
I have the following ``` RouteConfig ```
```
@RouteConfig([
  { path: '/',       as: 'home',   component: HomeComponent },
  { path: '/login',  as: 'login',  component: LoginComponent }
])
```
What am i doing wrong?

**Comment by jessegood** [comment]
See https://github.com/angular/angular/pull/3122
Basically add a base element `<base href="/">` although note that there is another bug currently *TypeError: baseElement.attr is not a function* so scroll down to see the workaround also.

**Comment by blacksonic** [comment]
It solved the error, thanks
