### ISSUE TITLE
When switching from ":id" to ":id", route animation is not triggered

### ISSUE THREAD

**Issue by delongZhai** [angular/angular#34836]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/animations: "~8.2.9",

### Is this a regression?

  Not so Sure

### Description

 A clear and concise description of the problem...
Having a problem to have route animation working when going from a path that is associated with one id to a path that  is associated with another one.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-jgeepe

## 🔥 Exception or Error
<pre><code>

No errors
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.19
Node: 12.13.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.19
@angular-devkit/build-angular     0.803.22
@angular-devkit/build-optimizer   0.803.22
@angular-devkit/build-webpack     0.803.22
@angular-devkit/core              8.3.19
@angular-devkit/schematics        8.3.19
@angular/cdk                      8.2.3
@angular/cli                      8.3.19
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.3
@ngtools/webpack                  8.3.22
@schematics/angular               8.3.19
@schematics/update                0.803.19
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

**Comment by breningham** [comment]
Are we talking about the :id on the same route e.g `/users/2` => `/users/2` if so, the reason this happens is because the component doesnt get destroyed or hidden, it is reused. 

i have in the past gotten around this by implementing a custom routeReuseStrategy, that i can share if you like.

**Comment by delongZhai** [comment]
I kind of realize that I misunderstand when it come to routing. Thought ‘/user/3’ and ‘user/4’ are different routes, actually they are the same. So I need to subscribe to the activated route’s param and trigger the animations. Thank you @breningham.
