### ISSUE TITLE
NgFor won't bind data from http call if it is recieved after the pages is loaded

### ISSUE THREAD

**Issue by edmirjano** [angular/angular#34841]
<img width="1091" alt="Screenshot 2020-01-18 at 12 34 39 AM" src="https://user-images.githubusercontent.com/48261411/72653337-a7b2bb80-398a-11ea-99d4-c22674816a98.png">

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
