### ISSUE TITLE
Pipes.extend in bootstrap method?

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#3485]
It looks like it is not possible to declare a new pipe in the bootstrap method (in alpha.33).  

See https://github.com/angular/angular/blob/master/modules/angular2/src/change_detection/pipes/pipes.ts#L76

It is a bit weird. as it is the place where we declare everything that can be used by the entire app. So when I want a pipe to be available everywhere I was thinking it would be the right place to declare it.

In alpha.33, we can do:

```
@Component({
  selector: 'my-app',
  hostInjector: [Pipes.extend({ fromNow: [new FromNowPipe()] })]
})
@View({ template: `<div>{{ birthday | fromNow }}</div>`})
export class MyApp { }
```

And I'd like to do:

    bootstrap(MyApp, [ Pipes.extend({ fromNow: [new FromNowPipe()] }) ]);

**Comment by gdi2290** [comment]
You're probably looking for Pipes.create

**Comment by cexbrayat** [comment]
Thanks for your answer. I had given it a try, but, maybe I'm making a mistake, it is really verbose:

    bind(Pipes).toValue(Pipes.create({ fromNow: [new FromNowPipe()] }, defaultPipes))

And the job of `extend` is pretty much to call `create`, so I thought it would be easier.

Maybe instead of throwing if used in `bootstrap` method, `extend` could use the defaultPipes?

**Comment by mhevery** [comment]
Pipes are getting redo this week, so this will all be moot. Closing since pipes will be treated as Directives, and this issue will become obsolete.
