### ISSUE TITLE
Missing html mark-up

### ISSUE THREAD

**Issue by pasha-bolokhov** [angular/angular#34850]
The following markup is missing
```
<p>The following is coming from content. It doesn't get to see the puppy because the puppy is declared inside the view only.</p>
```
# 📚 Docs or angular.io bug report

### Description
The above markup is missing above `<ng-content></ng-content>`
in the quotation of `providers-viewproviders/src/app/child/child.component.html`
It is present in the Stackblitz example, it is quoted as part of the rendered result, but not in the blockquote of code which the doc is asking to insert into that file

### What's the affected URL?**
https://angular.io/guide/hierarchical-dependency-injection

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by sonukapoor** [comment]
@pkozlowski-opensource I will take this one.

**Comment by sonukapoor** [comment]
@pasha-bolokhov / @pkozlowski-opensource The documentation and example are actually fine as is. The `ng-content` element is supposed to be empty. The content will be projected into the `ng-content` which is what the second section after the code shows.

**Comment by kapunahelewong** [comment]
Per offline conversation, @sonukapoor and I determined that the snippet is correct. @pasha-bolokhov I'll close this issue, but if you still have questions, please feel free to reopen. Thank you for looking out and filing your concern. :)
