### ISSUE TITLE
Reference Error : Google is undefined, Google charts

### ISSUE THREAD

**Issue by IrresistibleImran** [angular/angular#34859]
i've installed google charts via npm.
I'm trying to use google charts in my angular project and unable to go past this error:

ReferenceError: "google is not defined" at line 39

Code: 
```
import { ElementRef, AfterViewInit } from '@angular/core';
import { Component, OnInit, ViewChild } from '@angular/core';
import { setTimeout } from 'timers';


declare var google: any;

@Component({
  selector: 'payment-chart',

  template: '<div #pieChart style="width: 100vw; height: 100vh;"></div>',
  styleUrls: ['./payment-chart.component.scss']
})
export class PaymentChartComponent implements AfterViewInit {
  @ViewChild('pieChart', {static:true}) pieChart: ElementRef

  drawChart = () => {

  const data = google.visualization.arrayToDataTable([
    ['Task', 'Hours per Day'],
    ['Work', 11],
    ['Eat', 2],
    ['Commute', 2],
    ['Watch TV', 2],
    ['Sleep', 7]
  ]);

  const options = {
    title: 'My Daily Activities',
    legend: {position: 'top'}
  };

  const chart = new google.visualization.PieChart(this.pieChart.nativeElement);

  chart.draw(data, options);
}

  ngAfterViewInit() {
    setTimeout( ()=> {
      google.charts.load('current', { 'packages': ['corechart'] });
      google.charts.setOnLoadCallback(this.drawChart);
    },3000);
    
  }

}
```
```

**Comment by IrresistibleImran** [comment]
As seen above, I've even set timeout allowing the dependencies to load first.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
