### ISSUE TITLE
Scrolling to top in angular8 after route change not working

### ISSUE THREAD

**Issue by fpichlou** [angular/angular#34869]
I've build an Angular application, I have a few components, from my home page when I go to out services page, and scroll down, and go back to home page, the scroll is set to bottom of page.

I would like to set my scroll to top every time I open up a component.

I am using Angular8.2, I tried using the option available in router, {scrollPositionRestoration : 'enabled'} but it didn't work on Chrome nor on Chrome mobile or on Edge.

Other than that, I tried to set a listener on router and using window.scrollTo(0,0) in the ngAfterViewChecked() method of app.component.ts file, that didn't work either!
I just want my scroll bar at top. Its such a naive thing but it has frustrated me now!

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by fpichlou** [comment]
@ericmartinezr Thanks eric.
