### ISSUE TITLE
NGC rebuild performance improvements (Ivy & AoT)

### ISSUE THREAD

**Issue by elvisbegovic** [angular/angular#34867]
# 🚀 feature request

### Relevant Package
This feature request is for **@angular/compiler-cli**

### Description
Thanks to the team my issue https://github.com/angular/angular/issues/33986 was fixed in 9rc4 build. 
I open this feature request to ask (prioritize) others impovements regarding `ngc rebuild`, actually in large project 8-15s rebuild (on each file change) is pretty long.

### Repro
I think I succeed to repro a rebuild slowness by multiply by 2 the number of components (now 817) in my last issue repro [ng-speed-rebuild](https://github.com/elvisbegovic/ng-speed-rebuild)
Clone `master` branch, create `ngcc` ivy entry points, run `npm run ngc` to start the project.
Here's [ngc-9rc9.cpuprofile](https://drive.google.com/open?id=1YAo9yzNtU-2kv8w18bMVkDP-Ins5VpWp) of an isolated rebuild of the repro.

### Describe the solution you'd like
Out of scope to me. From what I've learned/heard the long phase is: emitting and reparse all components on each rebuild

### Describe alternatives you've considered
1. I tried on two differents hardware (VM ubuntu & win10) rebuild time is pretty same.
2. I can't be sure if ng-speed-rebuild repro is reflecting our private project because we have a lot of imports/exports/shared components.  On our private project we have 850 components, if it can help here you are a `.cpuprofile` of an isolated ngc rebuild of our private project [private-project-ngc-9rc9.cpuprofile](https://drive.google.com/open?id=1sKsde1Mv-CQD7iarjOg1nM9H87OWKM-9)
3. NOTE: With CLI 9rc9 `ng serve` rebuild is weird and really longer https://github.com/elvisbegovic/ng-speed-rebuild#ng-serve-9rc9-rebuild--83s---7s---5s---15s---17s---14s

### Other
Might be related to https://github.com/angular/angular/issues/34796 (wait repro)

**Comment by alxhub** [comment]
@elvisbegovic thank you so much for the reproduction! These kinds of examples are invaluable in diagnosing performance issues. I've already found a couple interesting issues from this repo:

1. The way we implement template type-checking triggers "safe modules" reuse in TypeScript, which is slower than "complete" program reuse. I have an idea for how to avoid this, which I'll play around with.

2. In this repo, during incremental build steps TypeScript does reports that a number of `.d.ts` files have changed between builds. This causes us to deopt and not reuse any parts of Angular analysis or previous emit results. It's a huge performance hit and is only marginally faster than a full fresh build. Ouch.

3. The dependency graph seems to require the re-emit of all the components when the one you suggested is changed anyway. This seems excessive, and I need to dig into why the graph is shaped as such. Perhaps there's room for improvement here.

I'll dig into these. Thanks!

**Comment by alan-agius4** [comment]
I also took some benchmarks for this projects

```
ng build --no-source-map --watch --aot
[benchmark] Process Stats
[benchmark]   Elapsed Time: 9079.40 ms (11799.00, 8110.00, 7702.00, 9059.00, 8727.00)
[benchmark]   Average Process usage: 2.00 process(es) (2.00, 2.00, 2.00, 2.00, 2.00)
[benchmark]   Peak Process usage: 2.00 process(es) (2.00, 2.00, 2.00, 2.00, 2.00)
[benchmark]   Average CPU usage: 28.13 % (35.55, 21.64, 20.84, 33.20, 29.44)
[benchmark]   Peak CPU usage: 139.38 % (226.60, 86.00, 79.70, 140.70, 163.90)
[benchmark]   Average Memory usage: 3312.76 MB (2877.79, 2812.30, 3043.68, 3626.54, 4203.47)
[benchmark]   Peak Memory usage: 3470.22 MB (3017.85, 2869.65, 3197.11, 3785.73, 4480.79)

ng build --source-map --watch --aot
[benchmark] Process Stats
[benchmark]   Elapsed Time: 10563.20 ms (13275.00, 9435.00, 9333.00, 11817.00, 8956.00)
[benchmark]   Average Process usage: 2.00 process(es) (2.00, 2.00, 2.00, 2.00, 2.00)
[benchmark]   Peak Process usage: 2.00 process(es) (2.00, 2.00, 2.00, 2.00, 2.00)
[benchmark]   Average CPU usage: 34.50 % (22.77, 46.09, 46.32, 35.17, 22.16)
[benchmark]   Peak CPU usage: 370.34 % (129.70, 721.80, 731.50, 189.00, 79.70)
[benchmark]   Average Memory usage: 4720.29 MB (4245.61, 4839.92, 5295.19, 4877.43, 4343.27)
[benchmark]   Peak Memory usage: 5038.48 MB (4487.37, 4970.58, 5536.08, 5761.92, 4436.47)

ng build --watch --source-map --no-aot
[benchmark] Process Stats
[benchmark]   Elapsed Time: 5404.00 ms (5856.00, 6241.00, 4502.00, 4625.00, 5796.00)
[benchmark]   Average Process usage: 2.00 process(es) (2.00, 2.00, 2.00, 2.00, 2.00)
[benchmark]   Peak Process usage: 2.00 process(es) (2.00, 2.00, 2.00, 2.00, 2.00)
[benchmark]   Average CPU usage: 39.86 % (25.02, 99.87, 21.52, 20.64, 32.27)
[benchmark]   Peak CPU usage: 298.48 % (157.90, 1062.50, 81.30, 81.20, 109.50)
[benchmark]   Average Memory usage: 2013.82 MB (1767.12, 1947.30, 2013.87, 2190.03, 2150.77)
[benchmark]   Peak Memory usage: 2048.96 MB (1821.60, 1981.15, 2030.72, 2227.80, 2183.51

```

**Comment by JoostK** [comment]
Hi @elvisbegovic,

if you get a chance, could you have a go with Angular 10.1.2 and report your experience here? A lot of performance improvements have come together in this release and I'm seeing promising numbers (see also https://github.com/angular/angular/issues/37293#issuecomment-694491621) but would like to check in with you regarding your repo. There is still a performance penalty in incremental compilations compared to JIT builds, but I expect the total time spent recompiling to have improved quite a bit.

**Comment by Splaktar** [comment]
I re-ran the original tests on my MacBook Pro 2014 and also ran against 10.2.4 for comparison.

Results: https://github.com/Splaktar/ng-speed-rebuild/blob/master/README.md

- The initial `ngc` was ~32% slower in v10
- The initial `ng serve` was ~26% slower in v10
- I wasn't able to reproduce the original AOT rebuild perf issues, v10 was slower but almost within the margin of error

That said, I am able to reproduce these AOT rebuild perf issues in a real world project and the times that I see in v9 and v10 are around 5-8s for JIT and 22-35s for AOT. But that seems to be tracked pretty well in https://github.com/angular/angular/issues/37293.

**Comment by elvisbegovic** [comment]
Hey guys, this is cool.

[Click here to see stats/diff between Angular 11.2.1 VS 11.2.6 on Google Sheet 
](https://docs.google.com/spreadsheets/d/1_GU8BHMWkaT9WMCxTCZoJIMBg0SIpydfNhOd8CCZNrE/edit?usp=sharing)

[Click here to download isolated .cpuprofile of a rebuild on Angular 11.2.1](https://drive.google.com/file/d/1FRFgSTvHuVSpOcaR4cc4iUfp9Hgt8vfh/view?usp=sharing)

[Click here to download isolated .cpuprofile of a rebuild on Angular 11.2.6](https://drive.google.com/file/d/1nmivkVM2KGj9eN1t4rb-TXizVIlOyixq/view?usp=sharing)

cc/ @JoostK
