### ISSUE TITLE
Scrolling to top in angular8 after route change not working

### ISSUE THREAD

**Issue by fpichlou** [angular/angular#34879]
I've build an Angular application with server side rendering mode (SSR), I have a few components, from my home page when I go to out services page, and scroll down, and go back to home page, the scroll is set to bottom of page.

I would like to set my scroll to top every time I open up a component.

I am using Angular8.2, I tried using the option available in router, `{scrollPositionRestoration : 'enabled'}` or `{scrollPositionRestoration : 'top'}` but it didn't work on Chrome nor on Chrome mobile or on Edge.

Other than that, I tried to set a listener on router and using `window.scrollTo(0,0)` in the `ngAfterViewChecked()` method of app.component.ts file, that didn't work either!
I just want my scroll bar at top. Its such a naive thing but it has frustrated me now!

**Comment by fpichlou** [comment]
The height: 100% of body and html element cause it! What do I do now?

**Comment by fpichlou** [comment]
The style of `body: overflow-x:hidden` cause it!

**Comment by OmarioHasan** [comment]
did you try to use  `anchorScrolling: 'enabled'` inside RouterModule.forRoot configuration ? 
it nay be like this 
`RouterModule.forRoot(appRoutes, {
      anchorScrolling: 'enabled'    
    })`
and make an anchor on the top of the page and try to scroll to it

**Comment by fpichlou** [comment]
@OmarioHasan Yep.
It resolved after removing body overflow.
