### ISSUE TITLE
Datepiacker Component Does Not Honor `updateOn` Configuration When No Year Is Present

### ISSUE THREAD

**Issue by zakmac** [angular/angular#34873]
# 🐞 bug report

### Affected Package
The issue _may be_ caused by package @angular/forms

### Is this a regression?
No information.

### Description
When `MatDatepickerComponent` is coupled to a `FormControl`, and said `FormControl` has a configuration with the option `updateOn: 'blur'`, the `updateOn` is not honored in certain cases. One such instance I have discovered is when editing the date with a keyboard, if the year is removed `valueChanges` will fire on the field with (almost) every keystroke.

## 🔬 Minimal Reproduction (open console)
https://stackblitz.com/edit/angular-dxyamu?file=src/app/datepicker-start-view-example.ts

![matdatepicker valuechanges](https://user-images.githubusercontent.com/2379809/72750090-b6f35e00-3b70-11ea-85d7-5758a9a970e9.gif)

## 🔥 Exception or Error
<pre><code>
// Not applicable
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
  "dependencies": {
    "@angular/animations": "^8.2.9",
    "@angular/cdk": "~8.2.2",
    "@angular/common": "^8.2.9",
    "@angular/compiler": "^8.2.9",
    "@angular/core": "^8.2.9",
    "@angular/forms": "^8.2.9",
    "@angular/material": "~8.2.2",
    "@angular/material-moment-adapter": "~8.2.2",
    "@angular/platform-browser": "^8.2.9",
    "@angular/platform-browser-dynamic": "^8.2.9",
    "@angular/router": "^8.2.9"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.8",
    "@angular/cli": "^8.3.8",
    "@angular/compiler-cli": "^8.2.9",
    "@angular/language-service": "^8.2.9"
  }
</code></pre>

**Anything else relevant?**
Tested in Chrome and FireFox the issue is present in both browsers with slightly different behavior in each:
* FireFox - After removing the year, every keystroke fires `valueChanges`
* Chrome - After removing the year, deleting a slash, adding a slash, or deleting the last character to the right of a slash (when 2 or more characters were originally present) will fire `valueChanges`

This is demonstrable both on StackBlitz (Angular ~8), as well as our organization's own application (Angular ~7).

**Comment by ericmartinezr** [comment]
Can you reproduce the same problem without material? Otherwise this should be reported in [angular component's repo](https://github.com/angular/components) :+1:

**Comment by zakmac** [comment]
> Can you reproduce the same problem without material? Otherwise this should be reported in [angular component's repo](https://github.com/angular/components) 👍

@ericmartinezr, it appears to not be reproducible without Material. I will create a new ticket in the appropriate repo. Thanks.
