### ISSUE TITLE
Inputs listed inside @Component decorators are not recognized

### ISSUE THREAD

**Issue by tx8821** [angular/angular#34874]
If one has the following component:

```
@Component({
  selector: 'my-input',
  templateUrl: './my-input.component.html',
  styles: [],
  inputs: ['label', 'hint', 'icon', 'type', 'id', 'placeholder', 'disabled', 'readonly', 'required']
})
export class MyInputComponent implements OnInit {
```

Those inputs declared as an `inputs` array of `@Component` decorator argument, are not recognized in the template, i.e. following errors are given in template:

> [Angular] Identifier 'label' is not defined. The component declaration, template variable declarations, and element references do not contain such a member

If I declare those inputs with `@Input` decorators as fields inside the component definition, then obviously they are correctly recognized. If this behavior is by design/unavoidable, at least that should be documented somewhere.

**Comment by ayazhafiz** [comment]
This was fixed some time ago. Adding a regression test for this issue now.
