### ISSUE TITLE
angular 9 with transitive template projection fails

### ISSUE THREAD

**Issue by gillerr** [angular/angular#34881]
# 🐞 bug report

### Affected Package
This issue is most probably caused by `@angular/core`, `@angular/cli` and `@angular/compiler-cli` or a combination of the above.

### Is this a regression?

This is a regression, it works well with Angular 8 and appears at least with angular **9.0.0-next.0**, **9.0.0-rc.0** and **9.0.0-rc.9** (I'haven't tested the other releases).

### Description

A template (`<ng-tempate #tpl>Hello</ng-template>`) is projected into a child component that itself projects the template farther to a grand child. The grand child then tries to display the template with `ngTemplateOutlet` but nothing is shown.

## 🔬 Minimal Reproduction

As I wasn't able to reproduce the problem on StackBlitz, I set up a minimal GitHub repo at https://github.com/gillerr/ngTemplateoutlet.

The **master** branch (https://github.com/gillerr/ngTemplateoutlet/tree/master/src/app) has been created with `ng new ngTemplateoutlet` and cleaned up of anything irrelevant. It features Angular 8 and works as expected.

The **angular9** branch (https://github.com/gillerr/ngTemplateoutlet/tree/angular9/src/app) contains the exact same code, I only executed 
`ng update @angular/core@9.0.0-next.0 @angular/cli@9.0.0-next.0` and pushed relevant files (`angular.json`, `package.json`, `package-lock.json` and `tsconfig.app.json`). I also had to manually update `typescript`.

The **workaround** branch (https://github.com/gillerr/ngTemplateoutlet/tree/workaround/src/app) shows a workaround that solves the problem but not in a way that satisfies me. The templates are passed through an `Input` instead of being projected.

## 🔥 Exception or Error
No error are shown, the templates' content simply is not displayed.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.0-rc.9
Node: 10.17.0
OS: linux x64

Angular: 9.0.0-rc.9
... cli, common, compiler, compiler-cli, core, platform-browser
... platform-browser-dynamic
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.9
@angular-devkit/build-angular     0.900.0-rc.9
@angular-devkit/build-optimizer   0.900.0-rc.9
@angular-devkit/build-webpack     0.900.0-rc.9
@angular-devkit/core              9.0.0-rc.9
@angular-devkit/schematics        9.0.0-rc.9
@ngtools/webpack                  9.0.0-rc.9
@schematics/angular               9.0.0-rc.9
@schematics/update                0.900.0-rc.9
rxjs                              6.4.0
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

I don't think this is relevant, but I'm on Ubuntu 18.04.3 LTS that runs in a virtual machine

**Comment by AndrewKushnir** [comment]
Hi @gillerr,

It looks like the problem is related to the changes in Ivy where @ContentChildren queries only match direct children by default (you can find [more information here](https://next.angular.io/guide/ivy-compatibility-examples#content-children-descendants)).

In your [example](https://github.com/gillerr/ngTemplateoutlet/blob/angular9/src/app/child.component.ts#L11), the `<ng-template #tpl>` is wrapped into `<ng-container>`, i.e.:

```
  <app-grand-child>
    <ng-container *ngFor="let template of templates">
      <ng-template #tpl>...</ng-template>
    </ng-container>
  </app-grand-child>
```

and as a result, the `@ContentChildren` query [defined in GrandChildComponent here](https://github.com/gillerr/ngTemplateoutlet/blob/angular9/src/app/grand-child.component.ts#L13) doesn't find projected elements. Could you please try to update the `@ContentChildren` query to include the `{descendants: true}`, test the behavior again and let us know if the problem still exists?

Thank you.

**Comment by pkozlowski-opensource** [comment]
As an alternative to the @AndrewKushnir suggestion, the following should work as well (just drop `<ng-container> which is less code and should be a tiny bit faster!)`:

```html
 <app-grand-child>
      <ng-template *ngFor="let template of templates" #tpl>...</ng-template>
  </app-grand-child>
```

**Comment by gillerr** [comment]
@AndrewKushnir, yes, adding `{descendants: true}` did solve the problem. I understand why the behavior has been altered, but IMHO, this is a breaking change and should be listed as such in the CHANGELOG.

@pkozlowski-opensource, your solution also works. I don't know why I haven't implemented it this way in the first place.

Thanks to both of you, this issue is solved

**Comment by pkozlowski-opensource** [comment]
@gillerr thnx so much for coming back to us with the confirmation.

> IMHO, this is a breaking change and should be listed as such in the CHANGELOG.

Totally! I believe that we've got it in the ivy migration already but yeh, I guess we need to make sure that a list of v9 breaking changes is more visible.

Again, thnx for reporting the issue and trying out our suggestions!
