### ISSUE TITLE
ERROR in Cannot read property 'members' of undefined

### ISSUE THREAD

**Issue by mgechev** [angular/angular#34886]
# 🐞 bug report

After running `ng serve` in [this project](https://github.com/mgechev/ngx-charts/tree/compiler-bug), I get:

```
ERROR in Cannot read property 'members' of undefined
```

### Affected Package

```
@angular/compiler
```

### Is this a regression?

Looks like it is. I noticed it in the latest Ivy RC.

### Description

The project references missing symbols. If you open `tooltip.module.ts`, you'll notice that the `TooltipModule` imports `TooltipContentComponent` which does not exist. Trying to compile the project using `tsc` reveals this error. Running `ng serve`, however, throws the generic `ERROR in Cannot read property 'members' of undefined`.

## 🔬 Minimal Reproduction

Available [here]([this project](https://github.com/mgechev/ngx-charts/tree/compiler-bug)) (notice the branch).

## 🔥 Exception or Error

```
ERROR in Cannot read property 'members' of undefined
```

## 🌍  Your Environment

**Angular Version:**

```
@angular/cli@9.0.0-rc.7
@angular/compiler@9.0.0-rc.7
```

**Comment by JoostK** [comment]
Interestingly it appears to succeed building the library even with the View Engine compiler in v12. And with v12 now allowing libraries to be compiled with the Ivy compiler, I'm closing this as resolved.
