### ISSUE TITLE
this is error coming on my site and ads are not running

### ISSUE THREAD

**Issue by deepakkumar1987** [angular/angular#34893]
Uncaught TypeError: Cannot redefine property: day
    at Function.defineProperty (<anonymous>)
    at fg (VM18 runtime.js:130)
    at VM18 runtime.js:130
    at VM18 runtime.js:782
fg @ runtime.js:130
(anonymous) @ runtime.js:130
(anonymous) @ runtime.js:782

**Comment by naingaungphyo** [comment]
I think no one can help your problem according to your error log. You should give more informations.
And please follow [guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md).

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
