### ISSUE TITLE
apply universal angular 7 to projects folder in workspace

### ISSUE THREAD

**Issue by LarozeMultiservices** [angular/angular#34895]
My angular 7.1.4 project structure is like this:
```
MyMulti
----node_modules
----projects
-------projA
-------projA-e2e
-------projB
-------projB-e2e
angular.json
package.json
```
I am able to apply Universal successfully to a single project. How to apply universal to all the projects in "MyMulti"? Is there any website reference which has an example or any tutorial? I could not get the configuration right. Any help would be appreciated.

**Comment by matsko** [comment]
Sorry to close this, but please open a new issue and follow the steps in the issue body so we can reproduce and fix the issue.
