### ISSUE TITLE
Angular 8 doesn't work with tslint v6.x

### ISSUE THREAD

**Issue by mhp-borisbojic** [angular/angular#34897]
# 🐞 bug report

### Affected Package
Angular v8.2.14 / @angular-devkit/build-angular v0.803.23

### Description

Running tslint 6.x with Angular 8 (@angular-devkit/build-angular) throws out an error message.

It seems Angular 8 doesn't expect tslint to be anything higher then v5.5.x?

## 🔥 Exception or Error
<pre><code>
[error] Error: TSLint must be version 5.5 or higher.
    at _loadTslint (********************/node_modules/@angular-devkit/build-angular/src/tslint/index.js:26:15)
    at async _run ((********************//node_modules/@angular-devkit/build-angular/src/tslint/index.js:43:27)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.23
Node: 12.14.1
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.23
@angular-devkit/build-angular     0.803.23
@angular-devkit/build-optimizer   0.803.23
@angular-devkit/build-webpack     0.803.23
@angular-devkit/core              8.3.23
@angular-devkit/schematics        8.3.23
@angular/cli                      8.3.23
@ngtools/webpack                  8.3.23
@schematics/angular               8.3.23
@schematics/update                0.803.23
rxjs                              6.5.4
typescript                        3.5.3
webpack                           4.39.2
    

</code></pre>

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular-cli/pull/16058, but I see that that PR was merged for 
 [v9.0.0-rc.2](https://github.com/angular/angular-cli/releases/tag/v9.0.0-rc.2). Also this should go in cli's repo :+1:

**Comment by mhp-borisbojic** [comment]
As tslint is deprecated, why isn't it changed to eslint anyway?

**Comment by mlc-mlapis** [comment]
@mhp-borisbojic There are other relations, but there are already prepared steps for migration to eslint. It's related to Angular 10, during this year.

**Comment by ericmartinezr** [comment]
Migration related: https://github.com/angular/angular-cli/issues/13732

**Comment by cexbrayat** [comment]
Closing this one, as this is an issue with the CLI.

I already fixed a while ago, but this is merged only in v9, not in v8.
As there might be other things to do for the CLI, I opened https://github.com/angular/angular-cli/issues/16733 to track it.
