### ISSUE TITLE
angular.io tap targets not sized appropriately

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#34901]
# 📚 Docs or angular.io bug report

### Description

lighthouse reports SEO issue due to tap target sizing:

<img width="989" alt="Screen Shot 2020-01-22 at 7 05 28 AM" src="https://user-images.githubusercontent.com/216296/72905714-d233aa00-3ce5-11ea-827d-2838f0280085.png">
<img width="1680" alt="Screen Shot 2020-01-22 at 7 05 49 AM" src="https://user-images.githubusercontent.com/216296/72905717-d2cc4080-3ce5-11ea-93bd-5bb7e497b77a.png">
<img width="902" alt="Screen Shot 2020-01-22 at 7 05 57 AM" src="https://user-images.githubusercontent.com/216296/72905718-d2cc4080-3ce5-11ea-883b-33277c4c9e9d.png">
<img width="910" alt="Screen Shot 2020-01-22 at 7 06 03 AM" src="https://user-images.githubusercontent.com/216296/72905720-d2cc4080-3ce5-11ea-94cb-846689d22700.png">

### What's the affected URL?**
 https://next.angular.io/...

### Reproduction Steps**

run lighthouse audit on next.angular.io

**Comment by ajitsinghkaler** [comment]
@gkalpak can I take this.

**Comment by gkalpak** [comment]
Sure, @ajitsinghkaler. That would be great.
