### ISSUE TITLE
another typo in docs

### ISSUE THREAD

**Issue by pasha-bolokhov** [angular/angular#34906]
# 📚 Docs or angular.io bug report

### Description

"the the" right at
https://angular.io/guide/http#making-a-jsonp-request

### What's the affected URL?**
https://angular.io/guide/http#making-a-jsonp-request

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by sonukapoor** [comment]
Weird. While I can see the double `the` in the above URL, I am not able to see the problem in the .md file or in the downloaded source code 😕

**Comment by naingaungphyo** [comment]
I found out that someone already did the [job!](https://github.com/angular/angular/pull/33978/commits/c4b77acdf52031d141b3b177a21050cc27cd7b07)

**Comment by naingaungphyo** [comment]
@sonukapoor 
I think it will be ready in next version! not in current one!

**Comment by gkalpak** [comment]
Exactly. YBTW, you can see the latest docs (deployed from the master branch) on https://next.angular.io/.

**Comment by gkalpak** [comment]
Closing the issue, since it has already be fixed on master. Thx again for eporting this, @pasha-bolokhov :+1:
