### ISSUE TITLE
Docs: Show output from examples

### ISSUE THREAD

**Issue by btesser** [angular/angular#3490]
Modify the dgeni documentation generation implementation so that it shows the rendered output next to each example.  This would be extremely useful as a guide for the angular component library that I'm working on.

**Comment by mhevery** [comment]
could you provide more details. The request here is very vague, and so it is not an actionable issue.

**Comment by btesser** [comment]
Sorry @mhevery.  In the angular 1 docs, @example allowed you to have examples which ran directly in the browser, for example a radio button you can click on to show and hide a component.  With the doc setup for angular 2, this behavior is not included.

**Comment by mhevery** [comment]
Yes, that is part of the overall docs effort. Currently WIP. We are not tracking individual items until we have the rewrite done, so I am going to Close for now.
