### ISSUE TITLE
Typo in CrisisDetailResolver decription

### ISSUE THREAD

**Issue by pasha-bolokhov** [angular/angular#34905]
# 📚 Docs or angular.io bug report

### Description

At https://angular.io/guide/router#fetch-data-before-navigating

Import the Crisis *model*, CrisisService, and the Router so you can navigate elsewhere if you can't fetch the crisis.

you meant *module*, right?

### What's the affected URL?**
https://angular.io/guide/router#fetch-data-before-navigating

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by ajitsinghkaler** [comment]
No here they are talking about the crisis model 

import { Crisis } from './crisis'; This line the examples here they import crisis model.

**Comment by ajitsinghkaler** [comment]
@kapunahelewong we can close this issue

**Comment by kapunahelewong** [comment]
Thank you for the heads up, @ajitsinghkaler!
