### ISSUE TITLE
yet another typo in docs

### ISSUE THREAD

**Issue by pasha-bolokhov** [angular/angular#34907]
# 📚 Docs or angular.io bug report

### Description
"The update resolver service looks like this:"
the *updated* resolver you meant probably

https://angular.io/guide/router#fetch-data-before-navigating

### What's the affected URL?**
https://angular.io/guide/router#fetch-data-before-navigating

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by gkalpak** [comment]
Thx for filing all these issues, @pasha-bolokhov :heart:

(I might be stating the obvious, but you know you are more than welcome to submit fixes for them too, right? In case you're interested, there is little "pencil" icon-button at the top right corner of each guide that will get you started (and we're always happy to help if you run into issues down the line).)

**Comment by aravindfz** [comment]
@gkalpak I'll fix this over this weekend

**Comment by aravindfz** [comment]
@gkalpak  fix is in a PR
