### ISSUE TITLE
Build WebWorker files with lib.webworker.d.ts

### ISSUE THREAD

**Issue by jteplitz** [angular/angular#3492]
Typescript provides a lib.workers.d.ts that we should be using for WebWorker files instead of lib.core.d.ts since it correctly types the WebWorker environment.

To implement this we need to modify tools/broccoli/broccoli-typescript to accept a WebWorker argument in options and use the correct defaultLibFileName for WebWorkers. Then we need to modify our broccoli builds to compile the web-workers/worker directory separately.

**Comment by jteplitz602** [comment]
Currently blocked on Typescript issue: https://github.com/Microsoft/TypeScript/issues/4015

**Comment by jteplitz602** [comment]
Looks like this will become unblocked with TypeScript 1.6

**Comment by mhevery** [comment]
obsolote
