### ISSUE TITLE
Why Angular 8 router is not working in Cordova IOS with WkWebView ?

### ISSUE THREAD

**Issue by sasensi** [angular/angular#34924]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 No, it is not working neither with Angular 7.

### Description

 
I can't make a simple `Angular 8` app with routing work within a `Cordova` app bundled for `IOS`, using `WkWebView`. The app loads as expected but nothing renders after the `<router-outlet>` element and navigation doesn't work.  
In order to use `WkWebView`, I use Cordova [cordova-plugin-wkwebview-engine](https://github.com/apache/cordova-plugin-wkwebview-engine) plugin.

Note that the exact same app is working when using the deprecated `UIWebView` instead.

## 🔬 Minimal Reproduction

 
Here is the [app](https://stackblitz.com/edit/angular-simple-routing-for-cordova-issue) code.  
And here is the [repository](https://github.com/sasensi/cordova-ios-angular) to reproduce the issue.  
Here are the steps to follow (require having node, npm and cordova installed globally):
1. clone repository: `git clone https://github.com/sasensi/cordova-ios-angular.git`
2. move to repository directory: `cd cordova-ios-angular`
3. install dependencies: `npm i`
4. create cordova project: `cordova create cordova com.demo.app DemoApp`
5. build Angular app: `npm run build`
6. move to cordova directory: `cd cordova`
7. add WkWebView plugin: `cordova plugin add cordova-plugin-wkwebview-engine`
8. add `<preference name="WKWebViewOnly" value="true"/>` in `./config.xml`
9. add cordova IOS platform: `cordova platform add ios`
10. open `platforms/ios/DemoApp.xcodeproj` in `XCode` (10.1)
11. run with `IPhone X` simulator
12. See that routing doesn't work: nothing is rendered below the navigation section (whereas there should be the current page content)

As mentioned earlier, everything is working as expected when using `UIWebView` (skipping steps `7.` and `8.`).

## 🔥 Exception or Error
<pre><code>

I can't see any error in XCode or Safari.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.4
Node: 10.16.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.4
@angular-devkit/core         8.3.4
@angular-devkit/schematics   8.3.4
@schematics/angular          8.3.4
@schematics/update           0.803.4
rxjs                         6.4.0
</code></pre>

**Anything else relevant?**

I am running `IPhone X` simulator from `XCode 10.1` in a `macOs Sierra 10.12` VM run from a `Windows 10` machine.

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by sasensi** [comment]
If someone else have the same issue, I posted it here on [StackOverflow](https://stackoverflow.com/questions/59866439/why-angular-8-router-is-not-working-in-cordova-ios-with-wkwebview/59900360#59900360).
