### ISSUE TITLE
Can't resolve all parameters warning in Build aot

### ISSUE THREAD

**Issue by ernestbofill** [angular/angular#34925]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 No

## 🔬 Minimal Reproduction

1. Add a service with a factory function like this:
```ts
import { Injectable } from '@angular/core';

@Injectable({ providedIn: 'root', useFactory: () => new TestService('a') })
export class TestService {
  value: any;
  constructor(value: string) {
    this.value = value;
  }
}
```

2. run `ng build -aot`

The build succeeds with a warning message:
`Warning: Can't resolve all parameters for TestService in C:/Projects/.../test.service.ts: (?). This will become an error in Angular v6.x`

Interestingly enough I'm using Angular 7.2

## 🔥 Exception or Error
<pre><code>
Warning: Can't resolve all parameters for TestService in C:/Projects/.../test.service.ts: (?). This will become an error in Angular v6.x
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.9
Node: 10.16.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/flex-layout              7.0.0-beta.24
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
I am able to reproduce in Angular 7 and 8 using the default View Engine compiler, but switching to Ivy in Angular 9 does not show these warnings. As such, closing as fixed in Ivy.
