### ISSUE TITLE
Usage of @angular/localize in Angular Libraries

### ISSUE THREAD

**Issue by klemenoslaj** [angular/angular#34920]
# 🐞 bug report

### Affected Package

The issue is caused by package `@angular/localize`

### Is this a regression?

No, `@angular/localize` is new in Angular 9.

### Description

I have already added my comment in a corresponding issue of documentation. If this is indeed just a documentation issue and I misunderstood the situation, please feel free to close the issue.

Documentation comment: https://github.com/angular/angular/issues/34822#issuecomment-577605603

---

Currently, it's quite unclear to me, how we are supposed to use the localization features in the libraries. Commonly we are importing @angular/localize/init into the polyfills.ts, but with libraries, I have very quickly identified some confusing situations:

- should each library be importing `@angular/localize/init` as well since otherwise it fails building?
- should each library import it to `test.ts` file as well - tests fail to execute if the import is not there?
- if some library imports `@angular/localize/init` all its dependents will successfully build. Therefore, if this library removes the import its dependants will start failing.

In my opinion the last one is the most confusing.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.9
Node: 12.13.1
OS: darwin x64

Angular: 9.0.0-rc.9
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.9
@angular-devkit/build-angular      0.900.0-rc.9
@angular-devkit/build-ng-packagr   0.900.0-rc.9
@angular-devkit/build-optimizer    0.900.0-rc.9
@angular-devkit/build-webpack      0.900.0-rc.9
@angular-devkit/core               9.0.0-rc.9
@angular-devkit/schematics         9.0.0-rc.10
@angular/cdk                       9.0.0-rc.8
@angular/flex-layout               8.0.0-beta.27
@angular/material                  9.0.0-rc.8
@angular/pwa                       0.900.0-rc.10
@ngtools/webpack                   9.0.0-rc.9
@schematics/angular                9.0.0-rc.10
@schematics/update                 0.900.0-rc.9
ng-packagr                         9.0.0-rc.7
rxjs                               6.5.4
typescript                         3.6.4

</code></pre>

**Comment by petebacondarwin** [comment]
For v9.0.0 (until further notice but at the earliest 9.1.0) you should not be doing anything special in your libraries for ivy. This includes worrying about `$localize` support. Just build your library via ViewEngine as normal.

But from your issue, I assume that you are (at least locally) building and testing your library with ivy turned on. In that case you need to know whether your build/test jobs are doing compile-time inlining of the `$localize` calls. If yes, then you should not need to do anything special. If not then you do need to add `$localize` to the global context at runtime, which is indeed done by importing `@angular/localize/init`. If it is just for tests then you could add this in `test.js`.

Applications that depend upon your library that are built with ivy turned on, should enable the `$localize` or do compile-time inlining. The Angular CLI takes care of all of this from v9.0.0, so there should be nothing for the application developer to do.
