### ISSUE TITLE
Make sure AOT vs AoT is used consistently in docs

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#34930]
# 📚 Docs or angular.io bug report

### Description
One of the initialisms we use is AOT - Ahead of Time compilation.

In our press kit we tell people to use AOT:  https://angular.io/presskit

Wikipedia says it's AOT: https://en.wikipedia.org/wiki/Ahead-of-time_compilation

Some places in our docs say "AoT" like our Nav.
![image](https://user-images.githubusercontent.com/165056/73016850-852e0180-3dd3-11ea-9d82-1482eb868f57.png)

I'd love to fix them all to say AOT, or at least be consistent.

**Comment by arswaw** [comment]
I like the small 'o' better but yeah, it's better to be consistent regardless.

**Comment by sonukapoor** [comment]
@StephenFluin I will fix this one.

**Comment by sonukapoor** [comment]
This can be closed now.

**Comment by cexbrayat** [comment]
Thx @sonukapoor for this PR! 👍  I'm closing the issue (you can add `Fixes #34930` to your commit message next time, and it will close the issue automatically and add a link in the changelog 🙂 )
