### ISSUE TITLE
Adding external scss file to the styles array breaks routing. 

### ISSUE THREAD

**Issue by cosmoKenney** [angular/angular#34939]
# 🐞 bug report

### Affected Package
Seems like the router.

### Is this a regression?

Not sure. This is happening in a new project.

### Description

Add a scss style sheet from outside (above) the angular root to the styles array in angular.json and it breaks routing:
```
	"styles": [
		"src/styles.scss",
		"../SharedStyles/Brand.scss"
	],
```
So if I `ng new` into the `/ClientApp` folder and the `/SharedStyles` folder is at the same level as `/ClientApp`, and I try to include `/SharedStyles/Brand.scss` in my `styles` array, the build completes and the page is rendered correctly with the new styles. However clicking on a link (`routerLink`) breaks with the error shown below. If I simply remove the reference to the scss file, then clicking the link works.

## 🔬 Minimal Reproduction
This repro shows the code that works. But if you un-comment the extra style sheet the build doesn't work. It seems like stackblitz doesn't like the extra folder:

https://stackblitz.com/edit/angular-issue-repro2-uph9xd?embed=1&file=src/index.html

However, on my machine the build does work with the same folder structure. 

## 🔥 Exception or Error
<pre><code>
[HttpException]: The controller for path &#39;/search&#39; was not found or does not implement IController.
   at System.Web.Mvc.DefaultControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType)
   at System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController& controller, IControllerFactory& factory)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.23
Node: 11.12.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.23
@angular-devkit/build-angular     0.803.23
@angular-devkit/build-optimizer   0.803.23
@angular-devkit/build-webpack     0.803.23
@angular-devkit/core              8.3.23
@angular-devkit/schematics        8.3.23
@angular/cli                      8.3.23
@ngtools/webpack                  8.3.23
@schematics/angular               8.3.23
@schematics/update                0.803.23
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**
_NOTE:_ I do have a `baseHref` set to `/dist/ClientApp` and `outputPath` is set to `../dist/ClientApp`.

**Comment by ericmartinezr** [comment]
This works

```
"styles": [
              "src/styles.css",
              "SharedStyles/Brand.css"
            ],
```
`SharedStyles` and `src` are at the same level, and that's what stackblitz is waiting for apparently. Can you share a repo with the problem? That would make it easier to investigate.

**Comment by cosmoKenney** [comment]
@ericmartinezr sorry about that. I guess I cannot repro on stackblitz. I'll have to try to make a repo tomorrow.

**Comment by cosmoKenney** [comment]
@ericmartinezr Hmm... I **cannot** repro in this minimal repository:
https://github.com/cosmoKenney/ng-routing-issue.git
As far as I can tell everything is the same in my real project. But it just behaves differently when that external scss file is present. I can reproduce the behavior in my real project by removing the entry in the `styles` array and refreshing the build. Routing works. If I add the entry back to `styles` routing breaks.

I can't imagine that anything in the scss file could effect routing. But who knows? Maybe I'll try an empty scss file in the real project.

**Comment by cosmoKenney** [comment]
**Update:** I tried a basically empty scss file in my real project. It's in the same location as the Brand.scss file. 

I just added the one line to the file: `body { background-color: yellow; }`. 

With that file in place the project routes as expected. 
What kind of things in the scss file would cause routing to break? This is weird.

**Comment by cosmoKenney** [comment]
**Update #2:** after commenting out all css rules in Brand.scss and adding them back in one-by-one, I found that something in this rule breaks routing!:
```css
html, body, #form1 {
	height: 100%;
	width: 100%;
	-webkit-box-sizing: border-box;
	-moz-box-sizing: border-box;
	-ms-box-sizing: border-box;
	box-sizing: border-box;
}
```

**Comment by cosmoKenney** [comment]
After commenting out all css rules in Brand.scss and adding them back in one-by-one, I found the problem. The router-outlet was pushed off the screen and I was looking at the wrong output window when I was seeing the error in listed in the original post. @ericmartinezr thanks for taking the time to answer. I'm closing this now.
