### ISSUE TITLE
TypeError from FormArray on patchValue with undefined

### ISSUE THREAD

**Issue by Aidan-Chey** [angular/angular#34935]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

 No, example stackblitz is using v6, discovered bug in v8

### Description

 Attempting to patchValue a FormArray with the value undefined results in a typeError being thrown inside "model.ts:1718"

## 🔬 Minimal Reproduction

 https://angular-issue-repro2-jwhsq2.stackblitz.io
[stackblitz edit link](https://stackblitz.com/edit/angular-issue-repro2-jwhsq2)

## 🔥 Exception or Error
<pre><code>

ERROR TypeError: Cannot read property 'forEach' of undefined
    at FormArray.patchValue (model.ts:1718)
    at new AppComponent (app.component.ts:18)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.21
Node: 12.13.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.21
@angular-devkit/build-angular      0.803.21
@angular-devkit/build-optimizer    0.803.21
@angular-devkit/build-webpack      0.803.21
@angular-devkit/core               7.2.4
@angular-devkit/schematics         7.2.4
@angular/cdk                       8.2.3
@angular/cli                       8.3.21
@angular/flex-layout               8.0.0-beta.27
@angular/material                  8.2.3
@angular/material-moment-adapter   8.2.3
@angular/pwa                       0.12.4
@ngtools/webpack                   8.3.21
@schematics/angular                7.2.4
@schematics/update                 0.803.21
rxjs                               6.5.4
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Anything else relevant?**

Should be fixable by adding a small check before the "forEach" of the input array. Some thing like Array.isArray(value)

**Comment by StrangeAmey** [comment]
**casting it as FormArray** and then using for each function on it will work and fix this issue @Aidan-Chey

**Comment by Aidan-Chey** [comment]
> **casting it as FormArray** and then using for each function on it will work and fix this issue 

In the example Repo, the variable that is patched is a "new FormArray" so it should already be a FormArray and not need to be cast.

So we should ideally not [patchValue a FormArray](https://angular.io/api/forms/FormArray#patchvalue) directly, in the off chance that `undefined` is passed into it; Instead do a forEach on the formArray's abstractControls, patching each individually. 

I don't know... could you give an example, I've made an [attempt to replicate](https://stackblitz.com/edit/angular-issue-repro2-xbo39a) your suggestion. It seems like such an idea bypasses the point of having a patchValue function for a FormArray altogether.

**Comment by Aidan-Chey** [comment]
> **casting it as FormArray** and then using for each function on it will work and fix this issue

I don't understand. Are you refering to a way of correcting the problem in the `patchValue` implementation of the angular files?

Or a way to get around the error thown by the `patchValue` function when supplied undefined as a value?

Either way, you can't do a `forEach` directly on a `FormArray` as it's a type of `AbstractControl` and breaks typescript.

**Comment by AndrewKushnir** [comment]
Hi @Aidan-Chey, thanks for creating this issue.

The `patchValue` method accepts only arrays, see here:
https://github.com/angular/angular/blob/a62c1c441c67616ce5eacc7e8dcfe169316d4552/packages/forms/src/model.ts#L1890
So providing different type should result in TypeScript error. For some reasons Stackblitz doesn't trigger type error, but I've created [a repro using TypeScript playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBCkFNoG8BQ0PQCYHsDKOAtggC4AWAlgHYDmAFAG5ggCuCAXNGFQJ4CUnBjgpYUAXwDcqMalShIMACIIAThQYJRCAB4kEVLDHgQkaTNnxFSlWo2ZtO3HgG0AugOhCR4qTNQhSaG1oAF5oKgQAd2hlNQ0sOj4pbQA6XAJicmp6FgMEADNqTSSgA) to illustrate it. Given that `undefined` is not a valid type from the `patchValue` function perspective, it doesn't seem like adding extra checks at runtime is required (the error should be caught by TypeScript).

I will close this ticket for now, feel free to reopen if the problem still exists in your app (and may be provide a minimum repro in a form of Github repository, so we can try to build it using CLI).

Thank you.
