### ISSUE TITLE
Implement ImageDemo example in Dart

### ISSUE THREAD

**Issue by jteplitz602** [angular/angular#3493]

**Comment by jteplitz602** [comment]
Currently blocked on https://github.com/dart-lang/sdk/issues/24011

**Comment by mhevery** [comment]
Could you provide more description? What is an ImageDemo, and why is it part of Angular?

**Comment by jteplitz602** [comment]
ImageDemo is an examples inside of our examples/web-workers directory that shows how to build a proper WebWorker application as well as the performance benefits that you can gain from using WebWorkers.

Currently it's not fully functional in dartium because we can't load the FileReader API inside of an isolate.
