### ISSUE TITLE
Formatting problem in a code snippet

### ISSUE THREAD

**Issue by pasha-bolokhov** [angular/angular#34942]
# 📚 Docs or angular.io bug report

### Description

The code snippet right at 
https://angular.io/guide/route-animations#querying-the-view-containers
has problems with formatting (the topmost `query()` should be aligned).

May confuse the reader as to what is nested into what...

However — this snippet is the continuation of the code from
https://angular.io/guide/route-animations#styling-the-host-and-child-components
and notice that the `transition('HomePage <=> AboutPage'...` function call is torn between the two snippets, which makes it even less consistent and readable

May be more readable to reproduce the whole piece in the bottom snippet, that piece is long anyway. Or, title it as `src/app/animations.ts  (continued)` at least

### What's the affected URL?**
https://angular.io/guide/route-animations#querying-the-view-containers

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by kapunahelewong** [comment]
@sonukapoor is willing to take this one. Thank you, @sonukapoor! 🏆

**Comment by sonukapoor** [comment]
@pasha-bolokhov / @kapunahelewong Unfortunately, our code-example component is not adhering to the indentation for a new section. It always aligns the code to the left.  Therefore, I have simply added the `Continuation from above` into the code section header. I hope this clarifies that section a little bit better.

**Comment by pasha-bolokhov** [comment]
fair enough

**Comment by kapunahelewong** [comment]
Sounds good to me. Thank you, @sonukapoor!
