### ISSUE TITLE
`[class]` bindings have different behavior with input/template bindings when ExpressionChangedAfterChecked 

### ISSUE THREAD

**Issue by vthinkxie** [angular/angular#34943]
# 🐞 bug report

### Affected Package
`@angular/core` render3 with ivy

`@angular/core/src/render3/instructions/styling.ts`

### Is this a regression?

no

### Description

Set an object to the same value(creating another new instance) in the `ngAfterViewInit`, the `[class]` binding would report ExpressionChangedAfterChecked error.

it should have the **same behavior** with the template/input binding, which should not report ExpressionChangedAfterChecked error

related to https://github.com/angular/angular/commit/9d1175e2b2b8bc8b282b15f56daac01e0537a5bf#diff-0c1dbc9c91289ccc01bde8bbb4777691R373-R377

## 🔬 Minimal Reproduction

ivy can not work in stackblitz now, here is the repo

https://github.com/vthinkxie/ng-class-binding-bug/blob/master/src/app/app.component.ts

```ts
import { AfterViewInit, Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    {{ classMap | json }}
    <!-- this won't report error -->
    <app-test [classMap]="classMap"></app-test>
  `,
  host: {
    // this would report error
    '[class]': 'classMap'
  }
})
export class AppComponent implements AfterViewInit {
  classMap = {
    test: true
  };
  ngAfterViewInit(): void {
    this.classMap = {
      test: true
    };
  }
}

```
## 🔥 Exception or Error
<pre><code>
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '[object Object]'. Current value: '[object Object]'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect         0.900.0-rc.10
@angular-devkit/build-angular     0.900.0-rc.10
@angular-devkit/build-optimizer   0.900.0-rc.10
@angular-devkit/build-webpack     0.900.0-rc.10
@angular-devkit/core              9.0.0-rc.10
@angular-devkit/schematics        9.0.0-rc.10
@ngtools/webpack                  9.0.0-rc.10
@schematics/angular               9.0.0-rc.10
@schematics/update                0.900.0-rc.10
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

related to https://github.com/angular/angular/commit/9d1175e2b2b8bc8b282b15f56daac01e0537a5bf#diff-0c1dbc9c91289ccc01bde8bbb4777691R373-R377

cc @kara @AndrewKushnir

**Comment by pkozlowski-opensource** [comment]
> Set an object to the same value in the ngAfterViewInit,

Wait, but in your example you _are_ creating a _new_ instance of a bound object (!), here:

```javascript
 ngAfterViewInit(): void {
    this.classMap = {
      test: true
    };
  }
```

This is a different case from `<app-test [classMap]="classMap"></app-test>` since here `classMap` expression points to the _exact same instance_ of an object.

I feel like I'm misunderstanding the point you are trying to make and / or expected vs. actual behaviour. Are you saying that you would expect the `ExpressionChangedAfterItHasBeenCheckedError` _not_ to be thrown? This would be surprising for me since my understanding here (but quite frankly, didn't dig too deep into it!) is that this error _should_ be thrown.

Also, it is not clear to me if this is an error that you are facing in your app or something that you've bumped into while trying out / experimenting with ivy? If this is a real app, what would be the concrete use-case?

Oh, and probably the most important piece of info: we've got substantial update to the `[class]` binding logic in the works (#34804) so things might change a bit here and there.

Anyway, would be great to have more info here as for me it "works as expected" for now :-)

**Comment by vthinkxie** [comment]
Hi @pkozlowski-opensource 
I would expect `ExpressionChangedAfterItHasBeenCheckedError` not to be thrown since it would not be thrown in `<app-test [classMap]="classMap"></app-test>` or `{{classMap}}`.

**Comment by pkozlowski-opensource** [comment]
@vthinkxie oh, I see what you are saying now... It is so confusing that we are not throwing when the object reference changes....

Anyway, I believe that this particular issue will be "fixed" with #34804 as there we unify  `ExpressionChangedAfterItHasBeenCheckedError` checks between styling and other places. 

Having said this I'm still confused since mutating model in `ngAfterViewInit()` is a big no-no.... I _suspect_ that this "works" for you only by pure chance (something to do with the way report errors _end_ execute host bindings....) but I want to dig into it a bit more / confirm.  

Thnx so much for providing more info / all the details. Let me dig into it and I will come back to you.

**Comment by vthinkxie** [comment]
thanks @pkozlowski-opensource 
I fully understand the `mutating model in ngAfterViewInit() is a big no-no`, but as a lib author, sometimes we have no way but to mutate the model in `ngAfterViewInit` or `ngAfterContentInit` 😖
I would like to give a very common situation when we integrate between projection components and the parent component

https://stackblitz.com/edit/ng-tw-contentchildren?file=src/app/parent/parent.component.ts

**Comment by vthinkxie** [comment]
here is another real app issue here, in our grid directive, we have to use the renderer instead of the `[style]` binding since we have to do it in the `ngAfterViewInit`
https://github.com/NG-ZORRO/ng-zorro-antd/blob/5133c3f7827761593334cdc9e649d4697a74d6bc/components/grid/col.directive.ts#L128

**Comment by pkozlowski-opensource** [comment]
@vthinkxie yeh, as hinted above, I think that the following is going on:
* currently we don't have great story for setting "dynamic" class / styles on a host (in a non-destructive way) - things will get better with ivy, but this is not the end of it...
* our `ExpressionChangedAfterItHasBeenCheckedError` is not super consistent and sometimes this error is not thrown where (IMO) it should - this is what I've meant by "things working by chance".

Again, thnx for the use-cases, let me dig into it a bit more and comment back on the issue with the findings.

**Comment by vthinkxie** [comment]
got it, thanks for your quick response

**Comment by pkozlowski-opensource** [comment]
@vthinkxie I believe that the conditions for throwing `ExpressionChangedAfterItHasBeenCheckedError` were relaxed in the rc.11 release so your particular scenario:

```typescript
import { AfterViewInit, Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `...`,
  host: {
    // this would report error
    '[class]': 'classMap'
  }
})
export class AppComponent implements AfterViewInit {
  classMap = {
    test: true
  };
  ngAfterViewInit(): void {
    this.classMap = {
      test: true
    };
  }
}
```

should not throw this error in rc.11. Could you please try the latest RC release and let us know how it goes?

Having said this I would still want to highlight the fact that mutating model in `ngAfterViewInit` is _way_ too late - put simply those changes won't be taken into account in the current change detection cycle (doing mutation in `ngAfterContentInit` is fine, though). In this sense having this error thrown or not is somehow irrelevant - model mutation happens "too late" and the actual update to the DOM happens later than you would expect, I guess.

I would be really interested in better understand the forces that push you into doing model mutation in the `ngAfterViewInit` lifecycle hook. Do you need to have component's template rendered to get some info (ex. elements sizing) and add / remove CSS classes based on this?

**Comment by vthinkxie** [comment]
Hi @pkozlowski-opensource 

> I believe that the conditions for throwing ExpressionChangedAfterItHasBeenCheckedError were relaxed in the rc.11 release so your particular scenario:

it does not throw this error in rc.11, thanks a lot.

> I would be really interested in better understand the forces that push you into doing model mutation in the ngAfterViewInit lifecycle hook. Do you need to have component's template rendered to get some info (ex. elements sizing) and add / remove CSS classes based on this?

Yes, we need some data after components' template rendered, it should be a very common situation.

For example

1. in the table component, we need to add className based the element.scrollWidth

https://github.com/NG-ZORRO/ng-zorro-antd/blob/4c8032b28c54e42bea784b153e750def829855a5/components/table/nz-table.component.ts#L287 

2.in the sider component, we need to update the template binding according to the `window.matchMedia` 
https://github.com/NG-ZORRO/ng-zorro-antd/blob/4c8032b28c54e42bea784b153e750def829855a5/components/layout/sider.component.ts#L126

**Comment by pkozlowski-opensource** [comment]
> We use `renderer.addClass` or `Promise.resolve().then()` to skip the `ExpressionChangedAfterItHasBeenCheckedError`

Right, at the moment those are the best options you've got (I would say that `renderer.addClass` is the preferred one as it won't trigger change detection.

The conceptual problem we are facing here is that you are trying to use _result_ of rendering to... decide on what should be rendered (!). Angular works best when UI to be rendered can be expressed in terms of model (data). Here you face a different situation where you use model as _initial_ rendering but _then_ you use this initial rendering to _refine_ it. Put simply, the final rendering result _does_ depend (conceptually _and_  technically) on the "previous" rendering result. If we think about the problem in those terms it is _not_ surprising that you need "2 rounds of rendering"...

I'm afraid that we are reaching limits here of what can be expressed in terms of model-driven, uni-directional data flow frameworks (and this is _not_ specific to Angular, at leat the way I understand it).

I will discuss this with the rest of the team but don't hold your breath - I _think_ that the "official" solution will be to use  `renderer.addClass`...

**Comment by vthinkxie** [comment]
I got your point Pawel Kozlowski, Thanks for your quick response!

> I will discuss this with the rest of the team but don't hold your breath - I think that the "official" solution will be to use renderer.addClass...

renderer.`addClass` `removeClass` `setStyle` `removeStyle` works but there are too many boilerplate code when we want to set the class/style dynamicly.

it would be better if `renderer` could provide equivalent functionality to template className and style binding (like `[class]` and `[style]`).

**Comment by mhevery** [comment]
close by https://github.com/angular/angular/pull/34804
