### ISSUE TITLE
Trying To Install "tslib" -- Facing Error

### ISSUE THREAD

**Issue by Mukesh-Lekhrajani** [angular/angular#34949]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

I am trying to install "tslib" and the command i am using is - `npm i tslib`

I am getting the following errors : 

npm WARN ng-helper-components@1.0.0 requires a peer of @angular/animations@^5.1 but none is installed. You must install peer dependencies yourself.
npm WARN ng-helper-components@1.0.0 requires a peer of @angular/common@^5.1 but none is installed. You must install peer dependencies yourself.
npm WARN ng-helper-components@1.0.0 requires a peer of @angular/compiler@^5.1 but none is installed. You must install peer dependencies yourself.
npm WARN ng-helper-components@1.0.0 requires a peer of @angular/core@^5.1 but none is installed. You must install peer dependencies yourself.
npm WARN ng-helper-components@1.0.0 requires a peer of @angular/forms@^5.1 but none is installed. You must install peer dependencies yourself.
npm WARN ng-helper-components@1.0.0 requires a peer of @angular/http@^5.1 but none is installed. You must install peer dependencies yourself.
npm WARN ng-helper-components@1.0.0 requires a peer of @angular/platform-browser@^5.1 but none is installed. You must install peer dependencies yourself.
npm WARN ng-helper-components@1.0.0 requires a peer of @angular/platform-browser-dynamic@^5.1 but none is installed. You must install peer dependencies yourself.
npm WARN ng-helper-components@1.0.0 requires a peer of @angular/router@^5.1 but none is installed. You must install peer dependencies yourself.
npm WARN ng-helper-components@1.0.0 requires a peer of rxjs@~5.5.6 but none is installed. You must install peer dependencies yourself.

npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path J:\JavaScript\AngularJS\angular-hello-world\node_modules\tslib
npm ERR! dest J:\JavaScript\AngularJS\angular-hello-world\node_modules\.tslib.DELETE
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'J:\JavaScript\AngularJS\angular-hello-world\node_modules\tslib' -> 'J:\JavaScript\AngularJS\angular-hello-world\node_modules\.tslib.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HOME\AppData\Roaming\npm-cache\_logs\2020-01-24T14_07_26_485Z-debug.log

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by gkalpak** [comment]
The error that you get is not related to Angular. It looks like an issue with npm (or your local npm setup).
Closing the issue, since there is not something we can do on the Angular side.
