### ISSUE TITLE
angular 7 universal to workspace

### ISSUE THREAD

**Issue by LarozeMultiservices** [angular/angular#34947]
My angular 7.1.4 project structure is like this:

MyMulti
----node_modules
----projects
-------projA
-------projA-e2e
-------projB
-------projB-e2e
angular.json
package.json

I am able to apply Universal successfully to a single project. How to apply universal to all the projects in "MyMulti"? Is there any website reference which has an example or any tutorial? I could not get the configuration right. Any help would be appreciated.

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/34895

**Comment by AndrewKushnir** [comment]
Closing as a duplicate of #34895.
