### ISSUE TITLE
Change `@proxy()` to `@proxy`

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#3494]
https://github.com/angular/angular/commit/3c58878b19b015b14d2d223a063efc25ea7f1419#diff-a7b00ed9077569881da8d1f71374e836 caused a regression in Dart output. `@proxy()` is an incorrect way to use `proxy`. It must be `@proxy` as it is a predefined constant.

/cc @jelbourn

**Comment by alexeagle** [comment]
Why didn't any of our tests catch this defect?

**Comment by yjbanov** [comment]
Probably some combination of the following:

- we do not run Dart analyzer on the offending code (or it passes the analyzer check)
- we do not compile our unit tests to JS
- Dart VM doesn't care to eval `@proxy` because this annotation is not used at runtime (it's used for static analysis only) and therefore never fails any of our tests

**Comment by alexeagle** [comment]
Is it because we don't run Dartium in checked mode for our testing? Can you
fix that?
