### ISSUE TITLE
parse5_adapter requires parse5 and css, but they are not listed as dependencies

### ISSUE THREAD

**Issue by uber5001** [angular/angular#3495]
angular2/src/dom/parse5_adapter.ts uses npm modules `parse5` and `css`, but these are not part of the npm package's dependencies. 

This is only an issue when using angular2 in node.

My hack to solve this was to require it as a dependency of my own module

    myModule
        angular2
        parse5
        css

This falls apart once someone tries to use my module AND angular2:

    othersModule
        angular2
        myModule
            angular2 (deduped away during npm install)
            parse5
            css

If the versions of angular2 are the same, `npm install` will not install angular2 in myModule anymore, which means it can no longer `require('parse5')` again.

This can be solved by adding `css` and `parse5` to angular2's package.json.

Are there any issues with adding dependencies that will never be used in the browser?

**Comment by mhevery** [comment]
obsolete
