### ISSUE TITLE
Multiple Errors While Creating Angular CLI Project

### ISSUE THREAD

**Issue by Mukesh-Lekhrajani** [angular/angular#34950]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

I am creating a new project with command = `ng new frmRegister -skip-git`

**Output of the command -** 

? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
CREATE frmRegister/angular.json (3726 bytes)
CREATE frmRegister/package.json (1298 bytes)
CREATE frmRegister/README.md (1029 bytes)
CREATE frmRegister/tsconfig.json (543 bytes)
CREATE frmRegister/tslint.json (1953 bytes)
CREATE frmRegister/.editorconfig (246 bytes)
CREATE frmRegister/.gitignore (631 bytes)
CREATE frmRegister/browserslist (429 bytes)
CREATE frmRegister/karma.conf.js (1023 bytes)
CREATE frmRegister/tsconfig.app.json (270 bytes)
CREATE frmRegister/tsconfig.spec.json (270 bytes)
CREATE frmRegister/src/favicon.ico (948 bytes)
CREATE frmRegister/src/index.html (297 bytes)
CREATE frmRegister/src/main.ts (372 bytes)
CREATE frmRegister/src/polyfills.ts (2838 bytes)
CREATE frmRegister/src/styles.css (80 bytes)
CREATE frmRegister/src/test.ts (642 bytes)
CREATE frmRegister/src/assets/.gitkeep (0 bytes)
CREATE frmRegister/src/environments/environment.prod.ts (51 bytes)
CREATE frmRegister/src/environments/environment.ts (662 bytes)
CREATE frmRegister/src/app/app-routing.module.ts (246 bytes)
CREATE frmRegister/src/app/app.module.ts (393 bytes)
CREATE frmRegister/src/app/app.component.spec.ts (1113 bytes)
CREATE frmRegister/src/app/app.component.ts (1510 bytes)
CREATE frmRegister/src/app/app.component.css (0 bytes)
CREATE frmRegister/e2e/protractor.conf.js (808 bytes)
CREATE frmRegister/e2e/tsconfig.json (214 bytes)
CREATE frmRegister/e2e/src/app.e2e-spec.ts (644 bytes)
CREATE frmRegister/e2e/src/app.po.ts (262 bytes)
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

> core-js@3.2.1 postinstall J:\JavaScript\AngularJS\NewAngular\frmRegister\node_modules\core-js
> node scripts/postinstall || echo "ignore"

> core-js@2.6.11 postinstall J:\JavaScript\AngularJS\NewAngular\frmRegister\node_modules\karma\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

> @angular/cli@8.3.23 postinstall J:\JavaScript\AngularJS\NewAngular\frmRegister\node_modules\@angular\cli
> node ./bin/postinstall/script.js

npm WARN karma-jasmine-html-reporter@1.5.1 requires a peer of jasmine-core@>=3.5 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\karma\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\@angular\compiler-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1167 packages from 1048 contributors and audited 19053 packages in 257.484s

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

    **Successfully initialized git.**  --------------- (inspite of using -Skip-git)

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by spock123** [comment]
Isn't it --skip-git ?

**Comment by gkalpak** [comment]
This is probably because you are using `-skip-git` instead of `--skip-git` (two leading dashes).
If this is not the issue, please, report it on the [angular/angular-cli][1] repo.

[1]: https://github.com/angular/angular-cli
