### ISSUE TITLE
Pipe Chain Aliasing

### ISSUE THREAD

**Issue by ike18t** [angular/angular#34951]
# 🚀 feature request

### Relevant Package
@angular/core

### Description
Currently there is no reusable way to declare a pipe chain w/o creating a new pipe and using DI to inject the pipes so you can then call the transforms directly. This approach seems a bit convoluted for the problem it is trying to solve.

### Describe the solution you'd like
Pipe chain aliases. A quick way to reference a specific chain of pipes.

**Comment by Airblader** [comment]
A pretty simple pattern used by Angular's own DatePipe and DecimalPipe is for the pipe to only call a function which is exported itself as well. Then you can create a simple alias pipe which doesn't require injecting (or worse, providing) any other pipes.

**Comment by ike18t** [comment]
That's also working on the assumption that they are your pipes and not from a lib.

**Comment by alxhub** [comment]
Closing due to insufficient votes. The demand for this doesn't seem to be high, and the complexity would be very large compared to the potential benefit.
