### ISSUE TITLE
No matching version found for @angular/cli@8.2.14.

### ISSUE THREAD

**Issue by LarozeMultiservices** [angular/angular#34964]
Stable angular/cli version 8.2.14 is not installing. Angular documentation shows only stable version, see https://angular.io/docs. But in the github no matching version in release notes. I need to install latest stable version. Which angular/cli version to choose?

**Comment by tieppt** [comment]
Angular and Angular CLI align only major vesion.
The latest Angular CLI version is 8.3.23
https://www.npmjs.com/package/@angular/cli
The version in Angular.io is the Angular framework, not the CLI.

**Comment by sankety** [comment]
When you run `npm install -g @angular/cli` it will always pull the latest stable version.

**Comment by AndrewKushnir** [comment]
Hi, I'm closing this ticket, since the original question is addressed by the comments in this thread. Thank you.
