### ISSUE TITLE
Error when @Inject is being used inside function.

### ISSUE THREAD

**Issue by haschu** [angular/angular#34975]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core (?)

### Is this a regression?

It is working in Angular 8.0.0 but fails in 8.2.3

### Description

Sometimes (e.g. for frameworks) it might be useful to automatically generate InjectionTokens for providers, e.g.:

```ts
/** Generates the token name */
export function getGeneratedToken(type: Type<any>) {
  return type.name + 'generated-stuff';
}

/** Injects with a generated token name */
export function InjectGenerated(type: Type<any>) {
  return Inject(getGeneratedToken(type))
}
```

When `Inject` isn't used directly within the constructor but inside `InjectGenerated`,
Angular throws this error:

`Uncaught TypeError: annotationCls is not a constructor`.

```ts
@Injectable()
class MyService {
  constructor(
    // This fails
    @InjectGenerated(SomeService) service: SomeService 
  ) {}
}
```

Calling Inject directly works:

```ts
@Injectable()
class MyService {
  constructor(
    @Inject(getGeneratedToken(SomeService)) service: SomeService 
  ) {}
}
```

See also [this](https://github.com/haschu/annotation-cls-error/blob/master/src/app/app.component.ts) example.

I don't know if this is an actual bug or related to a breaking change introduced into the angular compiler. But it would be great if there is least a workaround to fix this :blush:.

## 🔬 Minimal Reproduction
https://github.com/haschu/annotation-cls-error

## 🔥 Exception or Error
<pre><code>
Uncaught TypeError: annotationCls is not a constructor
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.23
@angular-devkit/build-angular     0.803.23
@angular-devkit/build-optimizer   0.803.23
@angular-devkit/build-webpack     0.803.23
@angular-devkit/core              8.3.23
@angular-devkit/schematics        8.3.23
@angular/cdk                      8.2.3
@angular/cli                      8.3.23
@angular/material                 8.2.3
@ngtools/webpack                  8.3.23
@schematics/angular               8.3.23
@schematics/update                0.803.23
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Comment by mhevery** [comment]
We don't support calling and or using annotation outside of their intended use. (This would break in AoT)
