### ISSUE TITLE
`limitTo' pipe: lower and optional upper bound

### ISSUE THREAD

**Issue by ShMcK** [angular/angular#3497]
Allow multiple limitTo's.

`<li *ng-for="#item of list | limitTo: 3 | limitTo: -7">{{item}}</li>`

Throws the following error:

`Uncaught Cannot find 'limitTo' pipe supporting object '3' in [list | limitTo: 3 | limitTo: -7 in null]`

Use case: Any pagination directive, where the listed items must be between two values in an array.

**Comment by pkozlowski-opensource** [comment]
Apart from the pb with chaining pipes here, we should change the `limitTo` pipe so it takes lower and upper bound as arguments (or even better - start index and no of elements). This functionality was introduced wayyy to late in ng1 and it was lacking a lot.

**Comment by ShMcK** [comment]
+1 to `limitTo` with a lower & optional upper bound. 
+1 to a default `skip` or `start index` pipe. Either method would achieve the same goal.

**Comment by mgcrea** [comment]
Maybe it's time to replace the legacy `limitTo` filter with a more intuitive `slice` pipe following the native Array API?

**Comment by pkozlowski-opensource** [comment]
Agree with @mgcrea - actually I didn't realise that we've got this pipe already landed - we should definitively rename / change the API before getting out of alpha.

**Comment by itslenny** [comment]
@pkozlowski-opensource @mgcrea 

What about strings? The legacy `limitTo` supports strings and arrays.

Should it be `slice` and `substr`? or should we keep `limitTo` for strings and use `slice` for arrays?

**Comment by itslenny** [comment]
I'm thinking `substring` and `slice` since those map to the native javascript API and they both work the same way (startingIndex, endingIndex)

**Comment by gkalpak** [comment]
Why not `slice` for both (using the same pipe) ?

**Comment by pkozlowski-opensource** [comment]
This was fixed by d890c4f8276c9979837a4f4c5928750121d4dd2a
