### ISSUE TITLE
Unable to load SVG file from remote location path using Object element

### ISSUE THREAD

**Issue by rammohangowd** [angular/angular#34977]
Hi, I am trying to load SVG file from remote shared folder path in Object element in my angular 8 application, below is the code snippet.

`<object id="svg1" xmlns:xlink="http://www.w3.org/1999/xlink" type="image/svg+xml" xmlns="http://www.w3.org/2000/svg" data="file://machinename/svg/test.svg"></object>`

But when run application I am getting an error like "Not allowed to load local resource: file://machinename/svg/test.svg" in console.

Note: I am able to access the path from browser address bar directly: "file://machinename/svg/test.svg"

Is there anyway that I can resolve this issue.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by rammohangowd** [comment]
ok. Thank you!
