### ISSUE TITLE
Events page hasn't been updated.  All events are in the past.

### ISSUE THREAD

**Issue by bileschi** [angular/angular#34971]
https://angular.io/events

![image](https://user-images.githubusercontent.com/547150/73129772-448fdd00-3fb9-11ea-8802-cd45f609853d.png)

**Comment by kapunahelewong** [comment]
@sonukapoor would like to do this one. Thank you, @sonukapoor!! 🌺

**Comment by sonukapoor** [comment]
@kapunahelewong / @gkalpak / @StephenFluin Have these events passed or they just in the wrong year and are happening this year?

**Comment by gkalpak** [comment]
The events have passed (and need to be moved to the "already presented" section.

@StephenFluin knows which are the upcoming events we are presenting at. I know of ng-conf for sure (see #35019).

**Comment by sonukapoor** [comment]
@StephenFluin do you have an excel file or something else with the events that you can share with me?

**Comment by gkalpak** [comment]
While working on a different change, I realized that https://next.angular.io/events _is_ updated, so I ported the changes over to the 8.2.x branch (to be deployed to https://angular.io/) as part of #35040 😇
