### ISSUE TITLE
Appears in the NgModule.imports of <MyLibrary>, but could not be resolved to an NgModule class

### ISSUE THREAD

**Issue by kaito3desuyo** [angular/angular#34983]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler 9.0.0-rc.11

### Is this a regression?

 Yes. In v8.2.14 it worked properly.

### Description

at my app, I using library built by me with angular v8.0.3 and @angular/material v.8.1.2 and ng-packagr.
then, error occured after update app to angular v9.0.0-rc.11.

```
ERROR in Failed to compile entry-point my-library (es2015 as esm2015) due to compilation errors:
vendor/my-library/dist/mylibrary-shared-feedback-dialog/node_modules/@angular/material/dialog/typings/dialog-module.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of MyLibrarySharedFeedbackDialogModule, but could not be resolved to an NgModule class

8 export declare class MatDialogModule {
```

A similar error occurs for the imported Angular Material Module.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.0-rc.10
Node: 12.14.0
OS: linux x64

Angular: 9.0.0-rc.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.10
@angular-devkit/build-angular      0.900.0-rc.10
@angular-devkit/build-optimizer    0.900.0-rc.10
@angular-devkit/build-webpack      0.900.0-rc.10
@angular-devkit/core               9.0.0-rc.10
@angular-devkit/schematics         9.0.0-rc.10
@angular/cdk                       9.0.0-rc.8
@angular/cli                       9.0.0-rc.10
@angular/flex-layout               8.0.0-beta.27
@angular/material                  9.0.0-rc.8
@angular/material-moment-adapter   9.0.0-rc.8
@ngtools/webpack                   9.0.0-rc.10
@schematics/angular                9.0.0-rc.10
@schematics/update                 0.900.0-rc.10
rxjs                               6.5.3
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Comment by mlakmal** [comment]
having same issue. we have following scenario.

shared libraries built and published using rc11.
seperate app that consumes those libraries also in rc11. 

i have a private repo with ability to recreate this issue. let me know if anyone wants to have access to troubleshoot the issue.

**Comment by mathistar** [comment]
same issue occurs in rc12. 
I have a library with disabling Ivy and consume that library in another angular project where enabling Ivy throws the below error.

ERROR in node_modules/@ex/ui/input/uiinput.module.d.ts:7:22 - error NG6002: Appears in the NgModule.imports of <ownmodule>, but could not be resolved to an NgModule class
    
in package referring the library - "@ex/ui": "file:../<libfolder>/dist/ui",
But this issue not occurs when we publish the library to npm  and access it - "@ex/ui": "^1.0.0"

**Comment by Phil147** [comment]
The error message is the same we got in #34755 but that closed unfortunately because the error at that time during RC8 was a different. You can find a reproduction sample in #34755

We have a local monorepo setup with a library that gets published, an internal library and an application that consumes both libraries. Using the build results of the libraries from the dist folder 
for the application build we get this error. If I point to the sources of the libraries with the tsconfig paths the application gets buiilt fine.

**Comment by mlakmal** [comment]
> having same issue. we have following scenario.
> 
> shared libraries built and published using rc11.
> seperate app that consumes those libraries also in rc11.
> 
> i have a private repo with ability to recreate this issue. let me know if anyone wants to have access to troubleshoot the issue.

i was able to resolve this issue on our npm libraries.
added "importHelpers": true to the tsconfig for lib builds. then remove the "__processed_by_ivy_ngcc__" section from package.json under build library artifacts before npm publish.

**Comment by VedantKarpe** [comment]
Added Angular Material 9 to Angular 9 project and received the same error:

![image](https://user-images.githubusercontent.com/29578397/74084850-2803a280-4a99-11ea-8a55-2951d6c1171b.png)

Package JSON Dependencies:

  "dependencies": {
    "@angular/animations": "~9.0.0",
    "@angular/cdk": "^9.0.0",
    "@angular/common": "~9.0.0",
    "@angular/compiler": "~9.0.0",
    "@angular/core": "~9.0.0",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "~9.0.0",
    "@angular/material": "^9.0.0",
    "@angular/platform-browser": "~9.0.0",
    "@angular/platform-browser-dynamic": "~9.0.0",
    "@angular/router": "~9.0.0",
    "@ngrx/schematics": "^8.6.0",
    "@ngrx/store": "^8.6.0",
    "@ngrx/store-devtools": "^8.6.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.1",
    "@angular/cli": "^9.0.1",
    "@angular/compiler-cli": "~9.0.0",
    "@angular/language-service": "~9.0.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.7.5"
  }

**Comment by ARTWINPRO** [comment]
Guys, i have some solution but im not sure how currect it is.

```
1. "buildOptimizer": false,
2. "enableIvy": true
3. "aot": false,
```

Before do this refactoring, application size is: 18 440KB;
After: 17 887KB

**Comment by stevethemacguy** [comment]
Please see my issue #35399 for a minimal reproduction repo. Thank you.

**Comment by maxisam** [comment]
I have been fighting with this issue the whole day. I finally figured it out. Apparently, it has something to do with tsconfig.

Make sure your tsconfig is like this

tsconfig.json
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "my-lib": [
        "dist/my-lib/my-lib",
        "dist/my-lib"
      ]
    }
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
```

tsconfig.lib.json
```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/lib",
    "target": "es2015",
    "declaration": true,
    "inlineSources": true,
    "types": [],
    "lib": [
      "dom",
      "es2018"
    ]
  },
  "angularCompilerOptions": {
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "enableResourceInlining": true
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts"
  ]
}
```

I think  `"importHelpers": true` is the one making the difference.

**Comment by gkalpak** [comment]
I haven't really looked at the error, but if `importHelpers: true` is what it takes to fix the issue, then there is a good chance that #35191 will fix it.

Can you try with the build artifacts from [here][1]? (See [there][2] for details on how to use them.)

[1]: https://circleci.com/gh/angular/angular/623221#artifacts/containers/0
[2]: https://github.com/angular/angular/blob/b2222e7e0/docs/DEVELOPER.md#getting-packages-from-build-artifacts

**Comment by stevethemacguy** [comment]
Using "importHelpers": true has no effect for me, but I'm not using the (angular) CLI.

**Comment by kaito3desuyo** [comment]
I tried "importHelpers: true" but unfortunately it didn't work.
However, updating the Angular library to Angular 9.0.0 and rebuilding it worked fine.

Angular v9 App - Angular v8 library →  **didn't work**
Angular v9 App - Angular v9 library → work
Angular v8 App - Angular v9 library → **didn't work**

**Comment by houdass** [comment]
Hi guys, I figured out what going wrong, I had a Angular 8 project (containing a library project) that I have upgraded to Angular 9 (with a lib also: ng generate library core) try at first creating a new angular 9 project I figured out that there is some things missing, here is the steps I followed:
- Delete node_modules
- Delete dist folder
- In the Angular 9 project lib there is a new file called: tsconfig.lib.prod.json 
```
{
  "extends": "./tsconfig.lib.json",
  "angularCompilerOptions": {
    "enableIvy": false
  }
}
```
- In your angular.json add the following:
```
{
  ...
  "projects": {
     ...
     "configurations": {
            "production": {
              "tsConfig": "projects/core/tsconfig.lib.prod.json"
             }
      }
  ...
  }
}
```
- run ng build --prod, and everything will work :D

PS: in this case the library is called "core"

**Comment by gkalpak** [comment]
Just a note:
If you do not provide a (minimal) reproduction, there pretty much nothing we can do to investigate, fix or verify a potential fix for your usecase 🤷‍♂

**Comment by kaito3desuyo** [comment]
https://github.com/kaito3desuyo/ng-v9-app
I tried to make a very small sample, but unfortunately I could not reproduce the problem.
So this repository is a sample that works properly with Angular v8 library in Angular v9 app.
In the project where the problem occurs, I feel like I specified dependencies for "dependencies" in package.json in library, which may be the cause.

Continue trying to reproduce.

**Comment by VedantKarpe** [comment]
Hi,

Created a new Angular 9 project and added angular material 9 from: [](https://material.angular.io/guide/getting-started) using the command **ng add @angular/material**

I then followed the steps mentioned in the link to display a simple checkbox using Angular Material.
The checkbox is displayed fine. However, the cli complains with the below error:

![image](https://user-images.githubusercontent.com/29578397/74581921-59212d00-4fdb-11ea-93a5-253ef9999215.png)

I then deleted the node_modules and did a npm install again. It seems to have fixed the issue. 

Could you please try the following:
1. Delete node_modules
2. npm install 

Repo: [](https://github.com/VedantKarpe/angular9)

**Comment by steve-gombos** [comment]
@VedantKarpe This worked for me.

**Comment by kaito3desuyo** [comment]
In conclusion, the cause was that you specified @angular/core etc. in the "dependencies" of the library.
I moved them to "peerDependencies" and rebuilt them and they worked fine.

So close this question.
