### ISSUE TITLE
Error: 'NgStyleR2Impl' is neither 'ComponentType' or 'DirectiveType'.

### ISSUE THREAD

**Issue by neofuture** [angular/angular#34989]
# 🐞 bug report

### Affected Package
Angular 9 RC 11

### Is this a regression?

Yes

### Description

running ng build --prod and running Build version shows error and will not run

## 🔥 Exception or Error
<pre><code>
Error: 'NgStyleR2Impl' is neither 'ComponentType' or 'DirectiveType'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.10
Node: 10.18.0
OS: darwin x64

Angular: 9.0.0-rc.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.10
@angular-devkit/build-angular     0.900.0-rc.10
@angular-devkit/build-optimizer   0.900.0-rc.10
@angular-devkit/build-webpack     0.900.0-rc.10
@angular-devkit/core              9.0.0-rc.10
@angular-devkit/schematics        9.0.0-rc.10
@angular/cdk                      8.2.3
@angular/cli                      9.0.0-rc.10
@angular/pwa                      0.803.19
@ngtools/webpack                  9.0.0-rc.10
@schematics/angular               9.0.0-rc.10
@schematics/update                0.900.0-rc.10
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Comment by pkozlowski-opensource** [comment]
@neofuture I'm afraid that we will need more info (ideally a reproduce scenario, the full error message as the minimum). I would suspect versions mismatch and / or an import to the private API _somewhere_ - but it is impossible to say without more details / reproduce scenario....

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
