### ISSUE TITLE
TypeError: Cannot assign to read only property 'tView' of object '[object Object]' with Ivy

### ISSUE THREAD

**Issue by tonivj5** [angular/angular#34993]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.2.14

### Description
I have upgrade from latest `v8.2.14` to `v9 rc11` and I have this error, it seems that `tView` property is created as non-writtable...

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/7110786/73179606-078c2d80-4114-11ea-9aed-3ceda05465e8.png)

<pre><code>
core.js:5809 ERROR TypeError: Cannot assign to read only property 'tView' of object '[object Object]'
    at getOrCreateTComponentView (core.js:11800)
    at createRootComponentView (core.js:25350)
    at ComponentFactory$1.create (core.js:32855)
    at ViewContainerRef.createComponent (core.js:15150)
    at RouterOutlet.activateWith (router.js:8939)
    at RouterOutlet.ngOnInit (router.js:8846)
    at callHook (core.js:3873)
    at callHooks (core.js:3837)
    at executeInitAndCheckHooks (core.js:3778)
    at refreshView (core.js:11586)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.10
Node: 13.0.1
OS: linux x64

Angular: 9.0.0-rc.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.10
@angular-devkit/build-angular     0.900.0-rc.10
@angular-devkit/build-optimizer   0.900.0-rc.10
@angular-devkit/build-webpack     0.900.0-rc.10
@angular-devkit/core              8.3.23
@angular-devkit/schematics        8.3.23
@angular/cdk                      8.2.3
@angular/cli                      9.0.0-rc.10
@angular/localize                 9.0.0-rc.0
@ngtools/webpack                  9.0.0-rc.10
@schematics/angular               9.0.0-rc.10
@schematics/update                0.900.0-rc.10
rxjs                              6.5.4
typescript                        3.6.5
webpack                           4.41.2
    
Done in 0.42s.
</code></pre>

**Anything else relevant?**
It works if I disable Ivy

**Comment by AndrewKushnir** [comment]
@tonivj5 thanks for reporting this issue. Could you please also provide a small repro (in a form of Github repo), so we can investigate the problem?

**Comment by tonivj5** [comment]
Hi, thanks for interest. I will try to create a repro :+1:

**Comment by tonivj5** [comment]
Here it's https://github.com/tonivj5/angular-issue-34993 (it was hard to find it :sweat_smile:). I have found that the error is produced by `@ngrx/router-store`. This error is not present using `ngrx/router-store` and Angular with VE.

I don't know if this error should be followed by Angular's core or ngrx team. I have found a closed issue https://github.com/ngrx/platform/issues/2109.

**Comment by AndrewKushnir** [comment]
Hi @tonivj5, thanks for additional information and a repro. I performed further investigation and it turned out that Ngrx freezes actions recursively, which also freezes Ivy defs generated by compilers. As a result, Ivy runtime fails to write to component def. I left more detailed reply in https://github.com/ngrx/platform/issues/2109#issuecomment-582689060. 

There are no action items on framework side atm, so I will close this ticket and continue discussion in the mentioned thread in Ngrx repo.

Thank you.

**Comment by nhhockeyplayer** [comment]
receiving this with same frameworks
hoping for workaround or patch soon
can someone advise how to disable IVY the way mentioned in this thread?
great work on a9 team, it will go further than java did
thanks
