### ISSUE TITLE
Color or filename in error report is too light

### ISSUE THREAD

**Issue by gempain** [angular/angular#34990]
# 🚀 Feature request

### Command (mark with an `x`)
- [ ] new
- [x] build
- [x] serve
- [x] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint (**maybe**)
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
![Screenshot 2020-01-27 at 13 39 39](https://user-images.githubusercontent.com/13135149/73175570-ce02f480-410a-11ea-97d2-c03d03001462.png)

In the above Angular CLI build error, the file name is too bright to be easily read. I haven't verified this scientifically using contrast checkers, but I'm pretty sure it wouldn't pass.

### Describe the solution you'd like
Could you use a darker color ?

### Describe alternatives you've considered
Manually filtering colors through the terminal, but this is cumbersome. Colors are too useful to be disabled.

PS: I know `_string` isn't a valid Typescript type 😉 Just had to find a way to create an error.

**Comment by alxhub** [comment]
The colors are from the TypeScript API function `ts.formatDiagnosticsWithColorAndContext`, which is used in the main TS compiler as well. I would suggest filing an issue at https://github.com/Microsoft/TypeScript as we have no control over the colors.
