### ISSUE TITLE
Setting ViewChild property in parent accessor causes error

### ISSUE THREAD

**Issue by ViktorSlavov** [angular/angular#34992]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?
Yes, t[his works](https://stackblitz.com/edit/component-accessor-v8?file=src%2Fapp%2Fapp.component.html) in Angular 8.x

### Description
When an `@Input` property has a setter and tries to update a property of a `@ViewChild`, the app errors

## 🔬 Minimal Reproduction

`CustomDirective` is a simple directive w/ a single property: `public id: string`;
`CustomComponent` is a simple component.
`CustomComponent` has an instance of `CustomDirective` in its view and a reference to that instance.
`CustomComponent` has a single `@Input` property w/ `get` and `set` accessors. The `set` accessor manipulates the `id` property of `this.directive`:
```
@ViewChild(CustomDirective)
private directive: CustomDirective

  @Input()
  public get id(): string {
    return this._id;
  }

  public set id(val: string) {
    this._id = val;
    this.directive.id = val;
  }
```
[Github](https://github.com/ViktorSlavov/angular-viewchild-error)

When you run the app, there is an error in the console.

## 🔥 Exception or Error
<pre><code>
core.js:5809 ERROR TypeError: Cannot set property 'id' of undefined
    at CustomComponent.set id [as id] (custom.component.ts:22)
    at setInputsFromAttrs (core.js:12816)
    at instantiateAllDirectives (core.js:12521)
    at createDirectivesInstances (core.js:11761)
    at ɵɵelementStart (core.js:20789)
    at Module.ɵɵelement (core.js:20847)
    at AppComponent_Template (app.component.html:1)
    at executeTemplate (core.js:11721)
    at renderView (core.js:11507)
    at renderComponent (core.js:13016)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.10
Node: 12.14.1
OS: win32 x64

Angular: 9.0.0-rc.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.10
@angular-devkit/build-angular     0.900.0-rc.10
@angular-devkit/build-optimizer   0.900.0-rc.10
@angular-devkit/build-webpack     0.900.0-rc.10
@angular-devkit/core              9.0.0-rc.10
@angular-devkit/schematics        9.0.0-rc.10
@angular/cli                      9.0.0-rc.10
@ngtools/webpack                  9.0.0-rc.10
@schematics/angular               9.0.0-rc.10
@schematics/update                0.900.0-rc.10
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Comment by pkozlowski-opensource** [comment]
@ViktorSlavov yes, indeed, we've changed the order of inputs settings from static attributes (it is done much earlier now, when a directive is instantiated and before change detection runs / queries are resolved). We've seen reports of this issue before and we are tracking it in #34227

I would say that the best solution / work-arround right now would be to move directive property setting to a lifecycle hook (`ngOnChanges`?), if you can.

But yeh, we were discussing already a change where we move inputs setting to the later stage. Let's centralise the discussion in #34227 - closing as a duplicate
