### ISSUE TITLE
Animations metadata is not inherited to sub-classed components

### ISSUE THREAD

**Issue by andrewseguin** [angular/angular#34999]
In Ivy, the `@Component({...})` metadata is inherited from a parent class. However, it appears that `animations` is not included.

This causes an issue when a parent class component defines animations host bindings and an animations definition, but the subclassed component only receives the host bindings.

The renderer throws an error but it is not helpful:
`Found the synthetic property @state. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.`

Reproduction: https://stackblitz.com/edit/ivy-ejv3ha?file=src/app/hello.component.ts

**Comment by AndrewKushnir** [comment]
Hi, PR #35105 with the changes to inherit animations metadata is now merged to master and will be available in 9.0.3 version of the framework. Thank you.
