### ISSUE TITLE
Travis: test with more platforms

### ISSUE THREAD

**Issue by vicb** [angular/angular#35]
What about testing with more browsers:
- IE,
- Safari,
- Firefox,
- Chrome

I had been working on testing angular.dart on those platforms with SauceLabs, ref https://github.com/angular/angular.dart/pull/1288

**Comment by ericwj** [comment]
Even if you will test other browsers later, it'd be nice to get some issues out of the way perhaps - simple things such as vendor prefixes?

For example would you like me to patch elementMatches in browser_adapter.ts? It calls Element.matches(string) which is still prefixed as msMatchesSelector in IE and Edge and that breaks my template that uses <content select="[ding]"/> in those browsers and everything else comes down as a result as well.

**Comment by pkozlowski-opensource** [comment]
We've got a PR for this already: https://github.com/angular/angular/pull/2347

**Comment by mhevery** [comment]
@mlaval  is already working on this.
