### ISSUE TITLE
ng-click called twice

### ISSUE THREAD

**Issue by tenaz3** [angular/angular#350]
I was using google chrome canary and Angular 1.3.8
I realize when I created a single ng-click and logged in console, the click was triggered twice.
.html
```
<div data-ng-click="open()"></div>
```
.js :controller
```
$scope.open = function(){
console.log('click');
}
```
output: 
click appears twice

This is a bug??? 
When I removed ngTouch module from project was worked normally

**Comment by pkozlowski-opensource** [comment]
Wrong repo: https://github.com/angular/angular.js
