### ISSUE TITLE
CHECKOUT PAYPAL PROBLEM ON SANDBOX TESTING WITH ANGULAR JS WITH ERROR TOKENIZING IN BRAINTREE

### ISSUE THREAD

**Issue by abhizeet007** [angular/angular#35007]
![D](https://user-images.githubusercontent.com/50789510/73275205-caf02d00-420c-11ea-8932-f8e391bf3e53.jpeg)
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please file any Angular Components issues at: https://github.com/angular/components/issues/new

For the time being, we keep Angular Components issues in a separate repository.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
