### ISSUE TITLE
Compiler not allowing property named 'default'

### ISSUE THREAD

**Issue by ryboucher** [angular/angular#35023]
# 🐞 bug report

### Affected Package

 
    "@angular/compiler-cli": "~8.2.3",

### Description

When I try to use a function to create a model, it has an irrelevant error populating because the property is called 'default'. If you change the name to 'isDefault' this error does not show up. So, this error "':' expected." is preventing me from creating a model with a property named default. You are allowed to declare a model with property named 'default', no errors involved. But as soon as you try to use that property in a function it provides an error. If this is intended behavior then why would the compiler allow a model with a property named 'default'?

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-issue-repro2-3mcvxr?file=src/app/app.component.ts

## 🔥 Exception or Error
<pre><code>

':' expected.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.1
Node: 10.16.3
OS: win32 x64
Angular: 8.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.1
@angular-devkit/build-angular     0.803.1
@angular-devkit/build-optimizer   0.803.1
@angular-devkit/build-webpack     0.803.1
@angular-devkit/core              8.3.1
@angular-devkit/schematics        8.3.1
@angular/cdk                      8.2.0
@angular/cli                      8.3.1
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.2.0
@ngtools/webpack                  8.3.1
@schematics/angular               8.3.1
@schematics/update                0.803.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.39.2
</code></pre>

**Comment by ericmartinezr** [comment]
I would say this a [TypeScript](https://www.typescriptlang.org/v2/en/play#code/DYUwLgBAJiBmCGBXYkC8EBEAJExgHsIB3fAJ2CgwG4g) thing since default is a [reserved keyword](https://github.com/Microsoft/TypeScript/issues/2536)

**Comment by alxhub** [comment]
Agreed. Closing as unresolvable.
