### ISSUE TITLE
Can't bind to 'dataSource' since it isn't a known property of 'table'

### ISSUE THREAD

**Issue by testengine999** [angular/angular#35032]
core.js:6014 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'dataSource' since it isn't a known property of 'table'. ("

<div class="mat-elevation-z8">
  <table mat-table [ERROR ->][dataSource]="dataSource" matSort>

    
"): ng:///AdminLayoutModule/DashboardComponent.html@5:19
Can't bind to 'matHeaderRowDef' since it isn't a known property of 'tr'. ("
    </ng-container>

    <tr mat-header-row [ERROR ->]*matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row *matRowDef="let row; columns: displayedColu"): ng:///AdminLayoutModule/DashboardComponent.html@31:23
Property binding matHeaderRowDef not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
    </ng-container>

    [ERROR ->]<tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row *matRowDef="let row; col"): ng:///AdminLayoutModule/DashboardComponent.html@31:4
Can't bind to 'matRowDefColumns' since it isn't a known property of 'tr'. ("

    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row [ERROR ->]*matRowDef="let row; columns: displayedColumns;">
    </tr>
  </table>
"): ng:///AdminLayoutModule/DashboardComponent.html@32:16
Property binding matRowDefColumns not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("

    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    [ERROR ->]<tr mat-row *matRowDef="let row; columns: displayedColumns;">
    </tr>
  </table>
"): ng:///AdminLayoutModule/DashboardComponent.html@32:4
Can't bind to 'pageSizeOptions' since it isn't a known property of 'mat-paginator'.
1. If 'mat-paginator' is an Angular component and it has 'pageSizeOptions' input, then verify that it is part of this module.
2. If 'mat-paginator' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  </table>

  <mat-paginator [ERROR ->][pageSizeOptions]="[5, 10, 25, 100]"></mat-paginator>
</div>"): ng:///AdminLayoutModule/DashboardComponent.html@36:17
'mat-paginator' is not a known element:
1. If 'mat-paginator' is an Angular component, then verify that it is part of this module.
2. If 'mat-paginator' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
  </table>

  [ERROR ->]<mat-paginator [pageSizeOptions]="[5, 10, 25, 100]"></mat-paginator>
</div>"): ng:///AdminLayoutModule/DashboardComponent.html@36:2
Error: Template parse errors:
Can't bind to 'dataSource' since it isn't a known property of 'table'. ("

<div class="mat-elevation-z8">
  <table mat-table [ERROR ->][dataSource]="dataSource" matSort>

    
"): ng:///AdminLayoutModule/DashboardComponent.html@5:19
Can't bind to 'matHeaderRowDef' since it isn't a known property of 'tr'. ("
    </ng-container>

    <tr mat-header-row [ERROR ->]*matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row *matRowDef="let row; columns: displayedColu"): ng:///AdminLayoutModule/DashboardComponent.html@31:23
Property binding matHeaderRowDef not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
    </ng-container>

    [ERROR ->]<tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row *matRowDef="let row; col"): ng:///AdminLayoutModule/DashboardComponent.html@31:4
Can't bind to 'matRowDefColumns' since it isn't a known property of 'tr'. ("

    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row [ERROR ->]*matRowDef="let row; columns: displayedColumns;">
    </tr>
  </table>
"): ng:///AdminLayoutModule/DashboardComponent.html@32:16
Property binding matRowDefColumns not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("

    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    [ERROR ->]<tr mat-row *matRowDef="let row; columns: displayedColumns;">
    </tr>
  </table>
"): ng:///AdminLayoutModule/DashboardComponent.html@32:4
Can't bind to 'pageSizeOptions' since it isn't a known property of 'mat-paginator'.
1. If 'mat-paginator' is an Angular component and it has 'pageSizeOptions' input, then verify that it is part of this module.
2. If 'mat-paginator' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  </table>

  <mat-paginator [ERROR ->][pageSizeOptions]="[5, 10, 25, 100]"></mat-paginator>
</div>"): ng:///AdminLayoutModule/DashboardComponent.html@36:17
'mat-paginator' is not a known element:
1. If 'mat-paginator' is an Angular component, then verify that it is part of this module.
2. If 'mat-paginator' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
  </table>

  [ERROR ->]<mat-paginator [pageSizeOptions]="[5, 10, 25, 100]"></mat-paginator>
</div>"): ng:///AdminLayoutModule/DashboardComponent.html@36:2

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by crisbeto** [comment]
It's probably because you haven't imported the `MatTableModule` in your `NgModule`. Closing since it doesn't match the issue template.
