### ISSUE TITLE
forms: two-ways ng-model sometimes fail to update field value

### ISSUE THREAD

**Issue by cghislai** [angular/angular#3503]
If I set the [(ng-model)]  property of an input field to an object value accessed through its properties array, the field value is sometimes not updated.

for instance, imagine the following model:
```javascript
class LocaleText: {
 id: number;
 textMap: {};
}
FormModel {
  locale: string;
  description: LocaleText;
}
```
If I setup the form template like this:

```html
<div>
<span *ng-for="#locale of allLocales">
  <input type="radio" name="locale"
    [checked]="locale == formModel.locale"
    (change)="onLocaleSelected(locale)"
    [attr.id]="locale">
    <label [attr.for]="locale">
      {{ locale }}
    </label>
</span>
</div>
<div>
<input [(ng-model)]="formModel.locale">
<input [(ng-mode)]="formModel.description.textMap[formModel.locale]">
<div>
 locale description: {{ formModel.description.textMap[formModel.locale] }}
</div>
</div>
```

Then, after the formModel.locale field is updated in the "onLocaleSelected(locale)" function, the first input field will correctly show the updated locale value, but the second one will (sometimes) fail to update. The locale description text in the last div is correctly updated as well.

I observed different non-predictable behaviour in the following cases:
- the object property does not exist (model['property'] returns undefined) or it exists but is mapped to an undefined value.
- the input field is an `<input>` or `<textarea>`

I noticed the model always gets updated if I enter some value in the field, but it fails to be displayed  correctly when changing the locale.

While debugging I noticed the NgModel's viewModel field already (or still) contained the new value, and that although the change.previousValue was correct, isPropertyUpdated returned false and the view did't receive the update.

**Comment by cghislai** [comment]
I made a plunker to demonstrate the issue. The problem arise when ng-model is bound through an object key (`[(ng-model)]="keyedValue[key]"` and the value is null `keyedValue.hasOwnProperty(key)==true; keyedValue[key] == null;`

http://plnkr.co/edit/Kl1cXKKZT1qpjKuvqKdX?p=preview

If you select english, then enter some text, the value is correctly updated in the model, but angular fails to update the input field value if you switch to another language then back to english. The title is correctly updated though.

**Comment by cghislai** [comment]
After a bit more testing, accessing alues through object properties does not seem to be the issue.
 I updated the plunk to reflect that. ng-model is bound to a string field. Editing the text input then switching languages leads to unpredictable behaviour. If you don't edit the input, it works well.

**Comment by kara** [comment]
Thanks for reporting!  It looks like this issue is pretty stale, and hasn't seen updates in almost a year.  Likely code has changed a lot since then.  If you're still seeing this issue in rc.1, please open an issue with an updated plunker.
