### ISSUE TITLE
ControlValueAccessor and ExpressionChangedAfterItWasCheckedError

### ISSUE THREAD

**Issue by gempain** [angular/angular#35048]
# 🐞 bug report

### Affected Package
- @angular/core

### Is this a regression?
No

### Description

I noticed that `registerOnChange` is called after `ngOnInit` by logging the registered function. My issue is that in `ngOnInit`, I set some things in my component and want to call the `onChange` function. So, I decided to use a `ReplaySubject(1)` to store emitted values. When an `onChange` function gets registered, I subscribe to the stream of values and emit a change on each value received. This causes Angular to throw `ExpressionChangedAfterItWasCheckedError`.

## 🔬 Minimal Reproduction
- clone [this demo repo](https://github.com/gempain/angular-kxwkry)
- `npm start` and open the console; you should see this:
![image](https://user-images.githubusercontent.com/13135149/73408241-e128e680-42fb-11ea-9649-86329e23b588.png)

The first two console logs show that `ngOnInit` is called before `registerOnChange`, so the first value emitted by the `my-control-sync` is not propagated to the parent. The second log shows the error, thrown after the on change function is called in `my-control-async`.

## 🔥 Exception or Error
<pre><code>
core.js:5809 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '{
  "sync": null,
  "async": null
}'. Current value: '{
  "sync": null,
  "async": "val"
}'.
    at throwErrorIfNoChangesMode (core.js:8009)
    at bindingUpdated (core.js:19509)
    at interpolation1 (core.js:19652)
    at Module.ɵɵtextInterpolate1 (core.js:23573)
    at AppComponent_Template (app.component.ts:7)
    at executeTemplate (core.js:11721)
    at refreshView (core.js:11568)
    at refreshComponent (core.js:13003)
    at refreshChildComponents (core.js:11298)
    at refreshView (core.js:11620)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular/* 9.0.0-rc.9
</code></pre>

**Comment by AndrewKushnir** [comment]
Hi @gempain, thanks for providing a repro. I've noticed that there is a reference to [the Stackblitz app](https://stackblitz.com/edit/angular-1citlk), so I copied it and updated all dependencies to the latest versions and enabled Ivy. Here is the link to my app: https://stackblitz.com/edit/angular-forms-exp-changed-error-35048. I don't see any errors that you mentioned. Please try to upgrade your app on Stackblitz, enable Ivy (click the "Settings" icon to open the list of config options including Ivy switch) and test the app once again. Please let me know if the problem still exists. Thank you.

**Comment by gempain** [comment]
Hi @AndrewKushnir and thanks for kicking in ! I just updated the dependencies and pushed to [my example repo](https://github.com/gempain/angular-kxwkry), but I still see the error locally. Indeed the error doesn't show up on Stackblitz, but have you tried to clone the repo, `npm install` and check locally ?

![Screen Shot 2020-07-14 at 09 43 19](https://user-images.githubusercontent.com/13135149/87398656-7b34d080-c5b6-11ea-8eed-e97c40769f25.png)

Ivy is enabled by default in the 9.x release, so there's no need to enable it:

![Screen Shot 2020-07-14 at 09 46 35](https://user-images.githubusercontent.com/13135149/87398938-ee3e4700-c5b6-11ea-9a20-ee9ef52d41e9.png)

**Comment by AndrewKushnir** [comment]
Hi @gempain, thanks for updating the repro. I tested it locally and was able to repro the issue. It looks like the problem was caused by the sequence of operations triggered by the RxJS operators usage when the onChange function is called when the current change detection cycle is completed (thus triggering the `ExpressionChangedAfterItWasCheckedError` error). I think you can try to store the values obtained/calculated inside the `ngOnInit` to a new class field (separate field) and use them later (in `writeValue` and other functions). Please let me know if updating the `MyControlAsyncComponent` class as I described works for your use-case. Thank you.
