### ISSUE TITLE
Getting started guide typo

### ISSUE THREAD

**Issue by meridsa** [angular/angular#35058]
# 📚 Docs or angular.io bug report

### Description
On the getting started guide: https://angular.io/start
Steps 3a and 3b have path guides with the wrong path

Current: src/app/product-list/product-alerts.component.ts
Should be: src/app/product-alerts/product-alerts.component.ts

This will cause some people to not be able to complete the getting started guide if they follow it exactly.

## 🔬 Minimal Reproduction
Doc error

### What's the affected URL?**
https://angular.io/start

### Reproduction Steps**
Not applicable.

### Expected vs Actual Behavior**
3 a, 3b path guides:

Expected: src/app/product-alerts/product-alerts.component.ts
Actual: src/app/product-list/product-alerts.component.ts

## 📷Screenshot
<img width="1064" alt="Screenshot 2020-01-30 at 16 08 20" src="https://user-images.githubusercontent.com/35993351/73461869-2b9d7800-437b-11ea-99b2-1e04edb2e8f3.png">

## 🔥 Exception or Error
Not applicable

## 🌍  Your Environment
Not applicable

### Browser info
Not applicable

### Anything else relevant?
No

**Comment by ericmartinezr** [comment]
Fixed by https://github.com/ajitsinghkaler/angular/commit/88a52bb925bb674cad5fc879b4ebeacdf77c77e0, see https://github.com/angular/angular/issues/34320#issuecomment-564957992
