### ISSUE TITLE
Angular 9.0.0-rc.8 and newer fail to compile with Ivy enabled

### ISSUE THREAD

**Issue by luthor77** [angular/angular#35054]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9.0.0-rc.7

### Description

 When Ivy is enabled in angular 9.0.0-rc.8 and newer, it fails on compilation.

## 🔬 Minimal Reproduction
 https://github.com/luthor77/angular-ivy-compilation-error
I couldn't reproduce the same error in stackblitz, the error occurs just installing the dependencies and running ng serve.

## 🔥 Exception or Error
<pre>ERROR in The target entry-point "@fullcalendar/angular" has missing dependencies:
 - @fullcalendar/core/types/input-types
 - @fullcalendar/core/datelib/env
 - @fullcalendar/core/datelib/duration
 - @fullcalendar/core/datelib/formatting
 - @fullcalendar/core/datelib/date-range
 - @fullcalendar/core/datelib/locale
 - @fullcalendar/core/validation
 - @fullcalendar/core/structs/event-source<code>
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.11
@angular-devkit/build-angular     0.900.0-rc.11
@angular-devkit/build-optimizer   0.900.0-rc.11
@angular-devkit/build-webpack     0.900.0-rc.11
@angular-devkit/core              9.0.0-rc.11
@angular-devkit/schematics        9.0.0-rc.11
@ngtools/webpack                  9.0.0-rc.11
@schematics/angular               9.0.0-rc.11
@schematics/update                0.900.0-rc.11
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2<code>
</code></pre>

**Anything else relevant?**
This error occurred with mobiscroll too, they fixed the error, but after fixed, started with fullcalendar, so I'm creating here.
https://github.com/acidb/mobiscroll/issues/475

**Comment by petebacondarwin** [comment]
I think this really is a bug in the `@fullcalendar/angular` package. 
See here (https://github.com/fullcalendar/fullcalendar-angular/blob/master/projects/fullcalendar/src/lib/fullcalendar.component.ts#L17-L23) that this package does an import from` @fullcalendar/core/types/input-types`.

**Comment by luthor77** [comment]
So, this is not a bug, is a change that they should adapt?

**Comment by petebacondarwin** [comment]
The source code of that package is incorrect - I am not sure why it would work in non-ivy TS builds. But in any case it is not something that we can solve on the ngcc/ngtsc side of things.

**Comment by alxhub** [comment]
It's probably possible to work around this with an `ngcc.config.js` file.

**Comment by luthor77** [comment]
Thanks for your help and explanation.
