### ISSUE TITLE
Confusing statement in testing documentation

### ISSUE THREAD

**Issue by bampakoa** [angular/angular#35056]
# 📚 Docs or angular.io bug report

### Description

In the **Frequently Asked Questions** section of the testing guide, there is a statement that tries to explain why not rely on E2E tests of DOM integration. I have read it many times but I find it really confusing to understand its meaning. At first glance, it seems that it tries to explain the same thing as the following section **Why not defer DOM integration tests to end-to-end (E2E) testing?**.

### What's the affected URL?**
https://angular.io/guide/testing#why-not-rely-on-e2e-tests-of-dom-integration

## 📷Screenshot

![image](https://user-images.githubusercontent.com/7170892/73454409-b760d580-4376-11ea-9ca8-ed3f993d56bf.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by gkalpak** [comment]
Thx for bringing it up! TBH, I don't even understand the meaning of the question :grin:

**Comment by spock123** [comment]
Funny I stumpled upon that sentence yesterday myself .

**Comment by kapunahelewong** [comment]
Thank you for bringing this up, @bampakoa. @sonukapoor is going to take it and try to rework those headers to make them clearer. Thank you, @sonukapoor!

**Comment by sonukapoor** [comment]
@kapunahelewong I am reviewing this now. Can you please assign it to me, so its easier to find it for me? Thanks

**Comment by kapunahelewong** [comment]
Sure thing, @sonukapoor. Thank you!
