### ISSUE TITLE
Ang9 Ivy to leave alone package.json in nested node_modules

### ISSUE THREAD

**Issue by mikekov** [angular/angular#35065]
# 🚀 feature request

### Relevant Package
This feature request is for @angular Ivy compiler

### Description
In my Angular project I have two node_modules folders: one at the root and a second one inside "src" folder. The one in src is for module "overrides". I keep a few libraries there that I had to modify (fixes or some larger changes; all in source control).  This setup works because of module resolution rules.

Ang9 RC breaks this setup, as it modifies project.json inside node_modules. I can always recreate libs at the root, but changing files inside "src" is more problematic. I cannot git-ignore them for instance.

### Describe the solution you'd like

I'd like to request that Ivy leaves files under "src" intact. Either that, or that it stops modifying package.json and instead relies on some newly created file, like "ivy-build-version-xyz.json" that I can git-ignore.

### Describe alternatives you've considered

* Where applicable, submit PR to project owners to fix issues (make take a while).
* Create a script that copies my libs into root node_modules and avoid nested node_modules.

**Comment by alxhub** [comment]
Unfortunately this is working-as-intended as far as ngcc goes - its job is to compile anything in `node_modules`.

You might be able to work around this with a `ngcc.config.js` file, by telling ngcc to ignore your overridden modules.
