### ISSUE TITLE
Binding error in "hostProperties of null"

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#3506]
Say I create a component:
```ts
@Component({
  selector: 'md-tile',
  host: {
    '[style.top]': 'style.top',
    '[style.left]': 'styl.left', // <<< typo here
  },
})
@View(...)
class MdTile {}
```

Run this component and you get
```
TypeError: Cannot read property 'left' of undefined in [styl.left in hostProperties of null]
```

The error here is decent, but the `hostProperties of null` part seems like it should actually be providing the name of the Component.

**Comment by pkozlowski-opensource** [comment]
@jelbourn what was the version of ng2 that you've tested with? I've just tried with alpha.34 and can't reproduce: http://plnkr.co/edit/OkCgExYNbKgCQ77VOuay?p=preview

The error I'm getting is the correct one:
> TypeError: Cannot read property 'left' of undefined in [styl.left in hostProperties of Hello]

Could you try to amend the plunk to reproduce?

**Comment by jelbourn** [comment]
@pkozlowski-opensource On master, you can reproduce this by modifying `grid_list.ts` to have a typo in the bindings for  `MdGridTile`, then run `gulp serve.js.dev` and hit [`http://localhost:8000/examples/src/material/grid_list/`](http://localhost:8000/examples/src/material/grid_list/)

**Comment by mhevery** [comment]
Verified, still happens on master.

**Comment by vicb** [comment]
on latest master the error is `"VM372 platform-browser.umd.js:1900 ORIGINAL EXCEPTION: TypeError: Cannot read property 'top' of undefined"` (RC4.5)
