### ISSUE TITLE
How to define tasks in an Angular-Node.JS web application project?

### ISSUE THREAD

**Issue by rezaee** [angular/angular#35064]
I am a new learner in web application field using Angular and Node.JS technologies. I watched some courses on Coursera for months and could create a Not-Bad web application for myself, but want I wish to do is to start a startup and create a new and big web application for my business. I exactly know what I want and maybe even I can speak about the technical details like what modules better to use and how design the database, etc. 

But I don't know how to split the project into the daily oe even hourly tasks and give it to developers to do. I tried to see Agile- Scrum videos but couldn't get my answer there. Please help me to know how should I do it and give me links of tutorials about what I want to learn. Thanks you in advanced!

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
