### ISSUE TITLE
Code error in productlist.component.html

### ISSUE THREAD

**Issue by Ishika86** [angular/angular#35075]
In the productlist.component.html there is a syntax error because of which product details can't be fetched on product description page. I 'm attaching the correct code which will work properly.There should be product.productId to fetch the product details

 <h3>
    <a [title]="product.name + ' details'" [routerLink]="['/products', product.productId]" routerLinkActive="active">
      {{ product.name }}
    </a>
  </h3>

**Comment by roelofjan-elsinga** [comment]
This seems to be a bug with your own application. This is not the right place for this bug.

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
