### ISSUE TITLE
Angular Router does not break on build-time when component is in a module

### ISSUE THREAD

**Issue by dkosasih** [angular/angular#35074]
# 🐞 bug report

### Affected Package
I am not sure which package is affected, but, I am guessing is @angular/compiler

### Description
The repo attached does not break even on prod build, but, after `ng serve` and run the app, it will break with the below exception. :(

## 🔬 Minimal Reproduction
https://github.com/dkosasih/angular-compiler-bug-replication.git

<!--
## 🔥 Exception or Error
Only on runtime:
<pre><code>
Component HelloComponent is not part of any NgModule or the module has not been imported into your module.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.24                                               
Node: 10.16.3                                                     
OS: win32 x64                                                     
Angular: 8.2.14                                                   
... animations, common, compiler, compiler-cli, core, forms       
... language-service, platform-browser, platform-browser-dynamic  
... router                                                        
                                                                  
Package                           Version                         
-----------------------------------------------------------       
@angular-devkit/architect         0.803.24                        
@angular-devkit/build-angular     0.803.24                        
@angular-devkit/build-optimizer   0.803.24                        
@angular-devkit/build-webpack     0.803.24                        
@angular-devkit/core              8.3.24                          
@angular-devkit/schematics        8.3.24                          
@angular/cli                      8.3.24                          
@ngtools/webpack                  8.3.24                          
@schematics/angular               8.3.24                          
@schematics/update                0.803.24                        
rxjs                              6.4.0                           
typescript                        3.5.3                           
webpack                           4.39.2    
</code></pre>

**Comment by tieppt** [comment]
Clearly, your `TestComponent` do not declare in any NgModule

```ts
// app-routing.module.ts
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { TestComponent } from './test/test.component';


const routes: Routes = [{ path: 'test', component: TestComponent }];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```
```ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { TestComponent } from './test/test.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

You should declare the Component like below:

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { TestComponent } from './test/test.component';

@NgModule({
  declarations: [
    AppComponent,
   TestComponent // <= this one
  ],
  imports: [
    BrowserModule,
    AppRoutingModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by dkosasih** [comment]
And that's exactly why I'm reporting it. Because in my opinion, it should break in compilation time, not runtime.

**Comment by alxhub** [comment]
This is actually an Ivy feature - components without `NgModule`s are perfectly legal. It's incredibly useful in tests and for small dynamic things.

I'm going to close this as WAI for now. In the future we might explore better ways to statically differentiate components that are likely to be broken at runtime due to a missing module context from intentional module-less components.
