### ISSUE TITLE
Correct way to render @ContentCnildren QueryList

### ISSUE THREAD

**Issue by IhorVimmi** [angular/angular#35088]
Hi! I have an issue with rendering components
Here is example of code. 
```javascript
<my-component>
  <ng-template *ngFor="let item of data">
    <child-component>
      <div>
        {{ data.title }}
      </div>
    </ngx-apple-maps-annotation>
  </ng-template>
</ngx-apple-maps>
```
in the my-component.ts
```javascript
 @ContentChildren(TemplateRef) template: QueryList<TemplateRef<any>>;
```

```javascript
ngAfterContentInit(): void {
  this.template.forEach(item => {
     const template = this.viewTemplateRef.createEmbeddedView(item);
     template.detectChanges();
  });
}
```
When i push something into `data` i need to display a new child component. If i try to do something like that:

```javascript
this.template.changes.subscribe((result) => {
    this.template.forEach(item => {
       this.viewTemplateRef.createEmbeddedView(item);
    });
});
```
I've got infinity loop. What the correct way to do this?

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
