### ISSUE TITLE
Can't use $localize in ts component

### ISSUE THREAD

**Issue by sinegovsky-ivan** [angular/angular#35084]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/localize

### Is this a regression?
I don't know

### Description

I'm using $localize method in my .ts component:
```
text = $localize`:@@loginError:`;
```

I have this key in my xlf file:

```
      <trans-unit id="loginError">
        <source>test stub</source>
        <target>Invalid login or password :(</target>
      </trans-unit>
```
But my message is not translated when i serve app 

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.0-rc.10
Node: 13.6.0
OS: darwin x64

Angular: 9.0.0-rc.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.10
@angular-devkit/build-angular     0.900.0-rc.10
@angular-devkit/build-optimizer   0.900.0-rc.10
@angular-devkit/build-webpack     0.900.0-rc.10
@angular-devkit/core              9.0.0-rc.10
@angular-devkit/schematics        9.0.0-rc.10
@angular/cdk                      8.2.0
@angular/cli                      9.0.0-rc.10
@angular/material                 8.2.0
@ngtools/webpack                  9.0.0-rc.10
@schematics/angular               9.0.0-rc.10
@schematics/update                0.900.0-rc.10
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
my package.json
<code>
  "dependencies": {
    "@angular/animations": "^9.0.0-rc.11",
    "@angular/cdk": "^8.2.0",
    "@angular/common": "~9.0.0-rc.11",
    "@angular/compiler": "~9.0.0-rc.11",
    "@angular/core": "~9.0.0-rc.11",
    "@angular/forms": "~9.0.0-rc.11",
    "@angular/localize": "9.0.0-rc.11",
    "@angular/material": "^8.2.0",
    "@angular/platform-browser": "~9.0.0-rc.11",
    "@angular/platform-browser-dynamic": "~9.0.0-rc.11",
    "@angular/router": "~9.0.0-rc.11",
    "@types/rx": "^4.1.1",
    "hammerjs": "^2.0.8",
    "mobx": "^5.11.0",
    "mobx-angular": "3.0.3",
    "ngx-ace-wrapper": "^8.0.0",
    "ngx-socket-io": "^2.1.1",
    "rxjs": "~6.5.4",
    "rxjs-compat": "^6.5.2",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
</code>

**Comment by mstawick** [comment]
@sinegovsky-ivan This might help you:
https://github.com/angular/angular-cli/issues/16375

**Comment by petebacondarwin** [comment]
The framework side of this works fine. See https://github.com/petebacondarwin/localize-global-id-test
Perhaps you need to modify your CLI configuration?

**Comment by TimBailey-pnk** [comment]
Hi I can confirm this is working well for me.... in the form 
`this.error = $localize`:@@login.validation:Please enter valid email Id and password`;`

But, I'm trying to get my page titles to be set on navigate and only getting partial success....
In my case the string is only known at runtime....
So I have this code in app.component.ts
```
  ngOnInit() {
    this.navEnd.subscribe(evt => {
      const data = this.findRouteData(this.activatedRoute)

      if (data && data.title) {
        // Need to use the "Tagged Template" in function mode to allow passing a computed string
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
        const stringArray = [data.title] as any;
        stringArray.raw = [data.title];

        this.titleService.setTitle('MyApp | ' + $localize(stringArray as TemplateStringsArray, []))
      } else {
        this.titleService.setTitle('MyApp')
      }
    });
  }
```
* `findRouteData` just scans the routes for data objects where I store the title.  data.title returns this string `:@@business.reports:Reports`

This works well when I run in dev mode, and I nicely see the document title change as expected.
When I try and build with locales I get an error
>ng build --prod --localize
Generating ES5 bundles for differential loading...
ES5 bundle generation complete.
Generating localized bundles...
Localized bundle generation failed: Unexpected messageParts for `$localize` (expected an array of strings).

I understand that direct use of the $localize tag/function is not supported, but any clues on why the localize process fails?

Thanks

**Comment by petebacondarwin** [comment]
@TimBailey-pnk - the problem is that `$localize` is replaced at compile-time with the translated strings. In your case you are passing it a variable that is only known at runtime. `$localize` is not designed for this kind of runtime behaviour. You have a couple of options:

1) if the text that changes is part of the business logic of the application then I would argue that `$localize` is not the right tool for the job. As an extreme example, `translate.google.com` would not use `$localize` to display the text that is being translated for the user. In that case you own logic should replace the text at runtime using your own code. That being said you could probably load up the translation files that `$localize` is using and use it in your own logic to access the same translation strings if that was helpful.

2) if the bit of the text that needs to change at runtime is not critical to selecting the translation then you could use interpolation within the translation string. I.E. 
```
$localize `some text ${someRuntimeValue} more text`;
```

I appreciate that in this scenario neither of these is probably going to fit.  One question is where does this `data.title` come from? Is it hard coded into each route's configuration somehow? If so perhaps you could apply the `$localize` at that point rather than inside the component?

**Comment by juanjinario** [comment]
Performing an 
`ng xi18n --output-path src / locale `
does not create trans-units by taking the id's in $ localize.

I have the following:
`return $ localize`: @@ home_title: test text`;`
when doing the extraction the translation key has not been created


I have an additional question, if I have the following trans-unit
```
<trans-unit id="summary_hotel_tax" datatype="html">
    <source>En <x id='INTERPOLATION' equiv-text='{{ citiesList }}'/> have taxes</source>
    <target>A <x id='INTERPOLATION' equiv-text='{{ citiesList }}'/> si deve pagare tassa turistica</target>
   </trans-unit>
```

How do i use the $ localize to send the citiesList variable?

I have tried to do the following:
$ localize`: @@ summary_hotel_tax: In $ {citiesList} there is a small tourist tax to pay at the hotel`;

But it does not work


I get the error

`ERROR in There is a placeholder name mismatch with the translation provided for the message "summary_hotel_tax" ("En {$PH} hay una pequeña tasa turística a abonar en el hotel").The translation contains a placeholder with name INTERPOLATION, which does not exist in the message`.

**Comment by petebacondarwin** [comment]
@juanjinario - the current translation extraction only works for `i18n` tags in templates, not `$localize` tagged strings in code.

In your second question, the translation has a placeholder called `INTERPOLATION` while in the `$localize` unnamed placeholders are called `PH`, `PH_1`, `PH_2` etc. You can name your placeholders. For example:

```
$localize`:@@summary_hotel_tax: In ${citiesList}:INTERPOLATION: there is a small tourist tax to pay at the hotel`;
```

**Comment by juanjinario** [comment]
It would be important to include what you have told me in the Angular i18n documentation.
I haven't found it anywhere else.

**Comment by petebacondarwin** [comment]
@juanjinario - well the thing is that `$localize` is not yet a publicly supported API :-) So there is no documentation on it yet.
