### ISSUE TITLE
Image Download issue

### ISSUE THREAD

**Issue by chandan123sahoo** [angular/angular#35094]
Hey Everyone.. 
I want to generate a id card and download it in angular .  
i can successfully generate it but while download it it showing nothing. Can any one help me out with this codes i used and help me out 
// code of front end 
 <div class="row" id="Idcardtoimage">
                        <div  class="col-md-4 offset-md-4" attr.id="{{cards.id}}" *ngFor="let cards of cardaray">
                            <mat-card class="id-card">
                              <mat-card-header>
                                <div class="row">
                                  <div class="col-md-3"><img src="assets/images/mudl.png" class="img-responsive" alt="image"></div>
                                  <div class="col-md-6"><h6>Header</h6></div>
                                  <div class="col-md-3"><img src="assets/images/logo.png" class="img-responsive" alt="image"></div>
                                  <div class="col-md-12">
                                    <h6>Header2<br>TExt</h6>
                                  </div>
                                </div>
                              </mat-card-header>
                              <mat-card-content>
                                <div class="row">
                                  <div class="col-md-6 offset-md-3">
                                    <div class="photo-holder"><img src="assets/images/icon-user.png" class="img-responsive" alt="image"></div>
                                  </div>
                                </div>
                                <div class="content-holder">
                                  <p class="text-right"><span>{{cards.name}}</span><strong> : name</strong></p>
                                  <p class="text-right"><span>{{cards.position}}</span><strong> :Position</strong></p>
                                  <p class="text-right"><span>({{cards.gozar}})</span> <strong> : Gozar </strong> <span>({{cards.nahia}}) </span> <strong> : Nahia</strong> <span>({{cards.city}}) </span> <strong>: City</strong></p>
                                </div>
                                <div class="bg-holder">
                                  <p><strong>Name : </strong><span>{{cards.name}}</span></p>
                                  <p><strong>Position in CTU : </strong><span>{{cards.position}}</span></p>
                                  <p><strong>City : </strong> <span>({{cards.city}} )</span> <strong>Nahya : </strong> <span>({{cards.nahia}} )</span> <strong>Gozar : </strong> <span>({{cards.gozar}})</span></p>
                                  <p class="text-right"><span></span> <strong>Issue date </strong> &nbsp;&nbsp;&nbsp; <span>{{cards.cardno}}</span> <strong> : Cardno</strong></p>
                                </div>
                              </mat-card-content>
                              
                            </mat-card>
                        </div>

                        <div class="col-md-4 text-right">
                            <input type ="button" value="Download image" class="btn btn-sm btn-primary-outline" (click)="hello()">
                        </div>
                      </div>
// ts file codes

// code to get data for bind in the html
  getarrayfromdata(dataarray: string[],municipality:string,nahia :string,gozar: string) {
    dataarray.map((item,index) => {
      return {
        id: index,
        name : item['ctucname'],
        position : item['ctucposition'],
        city: municipality,
        nahia : nahia,
        gozar : gozar,
        cardno : item['ctucID']
      }
    }).forEach(item => this.cardaray.push(item));
console.log(this.cardaray);
  }
// Code to download 

  hello()
  {
    for (let index = 0; index < this.cardaray.length; index++) {
      console.log(this.cardaray[index].id);

      const doc = document.getElementById(this.cardaray[index].id);
      console.log(doc);
      html2canvas(doc).then(function(canvas){
        const generateImage =canvas.toDataURL("image/png");
        //.replace("image/png","image/octet-stream")
        const FileSaver = require('file-saver');
        FileSaver.saveAs(generateImage, "image.jpg");
        console.log(canvas);
        console.log(generateImage);
      });
    }

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
