### ISSUE TITLE
Remove unnecessary *Wrapper classes, replace with ts2dart façades

### ISSUE THREAD

**Issue by mprobst** [angular/angular#3509]
See the wrapper slaying list here:
https://docs.google.com/spreadsheets/d/1GPmnUj7XPwnf-5_gMRvIw12bHWSH9Q-5vOdZ-gGkeik/edit#gid=0

**Comment by rkirov** [comment]
I talked with Misko a bit about this issue. The biggest win from this change is making community contributions easier. There are performance improvements but most likely not substantial.

@mprobst, @alexeagle  How do you feel about giving this issue to the community? How mechanical is the task vs needing understanding how ts2dart works. I want to make sure that that doesn't backfire and we have to respond to a lot of obscure issues?

**Comment by mprobst** [comment]
The problem is that you need some understanding of TypeScript, then you
need a change in t2dart, then you have to upgrade ts2dart in the Angular
repo, and then you can change the code there. This might blow the
complexity/coordination budget for external contributions.

Rado Kirov <notifications@github.com> schrieb am Di., 18. Aug. 2015 um
02:00 Uhr:

**Comment by vicb** [comment]
no more applicable
