### ISSUE TITLE
Documentation on Bazel does not work

### ISSUE THREAD

**Issue by crh225** [angular/angular#35107]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

I want to use bazel on a new project with angular 8 or add it to an existing project
## 🔬 Minimal Reproduction
`ng new --collection=@angular/bazel`
This is enough to give me the error
### What's the affected URL?**
 https://angular.io/...
https://angular.io/guide/bazel
### Reproduction Steps**

Run Cmd
type in ng new --collection=@angular/bazel
### Expected vs Actual Behavior**

![image](https://user-images.githubusercontent.com/19475195/73609780-95de3480-4596-11ea-9e2d-bee18b333075.png)
H:\angular>ng new --collection=@angular/bazel
Schematic "application" not found in collection "@angular/bazel".
Error: Schematic "application" not found in collection "@angular/bazel".
    at SchematicEngine.createSchematic (C:\Users\Chris\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\engine\engine.js:155:23)
    at CollectionImpl.createSchematic (C:\Users\Chris\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\engine\collection.js:12:29)
    at Object.getSchematic (C:\Users\Chris\AppData\Roaming\npm\node_modules\@angular\cli\utilities\schematics.js:36:23)
    at NewCommand.getOptions (C:\Users\Chris\AppData\Roaming\npm\node_modules\@angular\cli\models\schematic-command.js:195:40)
    at NewCommand.initialize (C:\Users\Chris\AppData\Roaming\npm\node_modules\@angular\cli\commands\new.js:48:21)
    at Object.<anonymous> (C:\Users\Chris\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js:87:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Chris\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js:4:58)

## 🌍  Your Environment
Windows 10
### Browser info

chrome
### Anything else relevant?

When trying to add bazel to an existing application, I faced a number of issues when trying to follow the 'documentation' on Angular.Io

For example, as of now, I need bash installed on windows.

`set PATH=C:\msys64\usr\bin;%PATH%
set BAZEL_SH=C:\msys64\usr\bin\bash.exe`
If not I get this error:
![image](https://user-images.githubusercontent.com/19475195/73609838-ff5e4300-4596-11ea-8c2c-e96eaefe74bb.png)

Maybe have a disclaimer that it wont be very easy to get custom material theme to work:
https://github.com/bazelbuild/rules_sass/issues/98

I was unable to use yarn and had to switch to npm  on existing angular application when trying to build with bazel.
https://github.com/angular/angular/issues/30350

In the angular-metadata.tsconfig.json I had to add the line to exclude @angular/cli
```  "exclude": [
    "node_modules/@angular/cli/**",
    "node_modules/@angular/bazel/**",
    "node_modules/@angular/**/schematics/**",
    "node_modules/@angular/**/testing/**",
    "node_modules/@angular/compiler-cli/**",
    "node_modules/@angular/common/upgrade*",
    "node_modules/@angular/router/upgrade*"
  ]```

**Comment by manklu** [comment]
@crh225 There are several open issues with bazel on windows.

IMO its currently the best to use WSL 2 for bazel.
https://docs.microsoft.com/en-us/windows/wsl/wsl2-index

**Comment by crh225** [comment]
The bash script is one point of many of bazel not working is my point. The documentation, as is, makes it seem like it takes 5 minutes or less to enable bazel.

**Comment by kapunahelewong** [comment]
Status: Docs Team needs engineering input to know how to document bazel implementation correctly.

**Comment by crh225** [comment]
@kapunahelewong did bazel get killed? https://github.com/angular/angular/blob/master/packages/bazel/src/schematics/README.md

**Comment by kyliau** [comment]
Bazel support in `@angular/angular` has been [deprecated](https://angular.io/guide/deprecations#bazel-builder-and-schematics) in version 10.
As part of the cleanup, we now redirect https://angular.io/guide/bazel to the [migration doc](https://github.com/angular/angular/blob/master/packages/bazel/src/schematics/README.md).
The Bazel effort is now wholly owned by the Bazel [community](https://github.com/bazelbuild/rules_nodejs/tree/master/examples/angular).
As mentioned in the migration doc, if you need help, please reach out to folks in the #angular channel in http://slack.bazel.build/
