### ISSUE TITLE
The `isNode()` detection in the animations module is not precise enough

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#35117]
While profiling the issue reported in  #35029  it turned out that [the isNode() detection method](https://github.com/angular/angular/blob/4d36b2f6e9a1a7673b3f233752895c96ca7dba1e/packages/animations/browser/src/render/shared.ts#L22-L24), present in the animation module, is not precise enough and can execute in a browser, leading to the performance problems.

![Screenshot 2020-01-31 at 14 41 41](https://user-images.githubusercontent.com/973550/73641995-2be68d80-4671-11ea-807f-49d50effce6a.png)

Looking at the profiling picture captured in a browser we can notice that `writeStyleAttribute` function is executed, [even if is supposed to execute in the Node environment only](https://github.com/angular/angular/blob/b0834fe962b96fc84e5ffbcdb5283b25f74a5c47/packages/animations/browser/src/util.ts#L176-L187)!

 This is unfortunate since the  `writeStyleAttribute` is relatively slow (see #35116) - but the point of this issue here is that it should not execute in a browser at all!

**Comment by gkalpak** [comment]
BTW, a similar issue (caused by `isNode()` not doing the right thing) was discussed in #24769 (see for example https://github.com/angular/angular/issues/24769#issuecomment-405498008).

OOC, did you see this on a CLI project with `build-optimizer` turned on (because my understanding was that `build-optimizer` mitigates this)?

**Comment by pkozlowski-opensource** [comment]
> OOC, did you see this on a CLI project with build-optimizer turned on

Nope, I saw this based on the scenario from  #35029 and there a user was using a custom build (no CLI).

**Comment by gkalpak** [comment]
One should be able to fix this in their bundler config (e.g. https://github.com/angular/angular/issues/24769#issuecomment-467130018), but we can definitely improve things here (e.g. implement something like https://github.com/angular/angular/issues/24769#issuecomment-536320302 or at least document this gotcha).
