### ISSUE TITLE
EventEmitter.emit() should only accept T, not T | undefined.

### ISSUE THREAD

**Issue by hmil** [angular/angular#35119]
# 🐞 bug report

### Affected Package

@angular/core

### Is this a regression?

No

### Description

The signature of `EventEmiter.emit` was modelled according to the signature of rxjs' `Subject.next` (see #10058 ). But the signature of `Subject.next` has a [design flaw](https://github.com/ReactiveX/rxjs/issues/2852) which has been copied to `EventEmitter.emit`.

This issue is essentially the same as https://github.com/ReactiveX/rxjs/issues/2852 , but applied to angular's EventEmitter. See repro below for details.

## 🔬 Minimal Reproduction

```ts
const em = new EventEmitter<string>();
em.asObservable().subscribe(s => {
    s.substring(0, 1); // boom
});
em.emit();
```

### Expected behavior

A compile error at line 5

### Actual behavior

A runtime error at line 3

### Details

The signature of `emit` allows emitting `undefined` on an event emitter which declares a non-nullable type.
This defeats the whole purpose of typescript's --strictNullCheck flag.

## 🔥 Exception or Error

No error, that's the problem.

## 🌍  Your Environment

All versions since #10058

## 🔧 Suggested fix

The suggested fix is simple enough, but it is a breaking change:
- Make the parameter of `emit` non-optional. One can still write `em.emit()` provided the EventEmitter is of type `EventEmitter<void>`.
- Make the default type of T `void` instead of `any` (see [this](https://github.com/ReactiveX/rxjs/issues/5066#issuecomment-581462164)) for details.

```diff
diff --git a/packages/core/src/event_emitter.ts b/packages/core/src/event_emitter.ts
index 07143d9774..eaf84b7ad0 100644
--- a/packages/core/src/event_emitter.ts
+++ b/packages/core/src/event_emitter.ts
@@ -61,7 +61,7 @@ import {Subject, Subscription} from 'rxjs';
  * @see [Observables in Angular](guide/observables-in-angular)
  * @publicApi
  */
-export class EventEmitter<T extends any> extends Subject<T> {
+export class EventEmitter<T extends any = void> extends Subject<T> {
   /**
    * @internal
    */
@@ -83,7 +83,7 @@ export class EventEmitter<T extends any> extends Subject<T> {
    * Emits an event containing a given value.
    * @param value The value to emit.
    */
-  emit(value?: T) { super.next(value); }
+  emit(value: T) { super.next(value); }
 
   /**
    * Registers handlers for events emitted by this instance.
```

**Comment by JeanMeche** [comment]
The new `output()` function fixes this issue.  This is what we'll recommend if you're looking for a type-safe alternative.
