### ISSUE TITLE
writeStyleAttribute performance issues

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#35116]
While profiling the issue reported in #35029 it turned out that the significant amount of time is spent in the [writeStyleAttribute](https://github.com/angular/angular/blob/b0834fe962b96fc84e5ffbcdb5283b25f74a5c47/packages/animations/browser/src/util.ts#L139-L158) function.

Here is the picture visible under profiler:
![Screenshot 2020-01-31 at 14 41 41](https://user-images.githubusercontent.com/973550/73641342-29cfff00-4670-11ea-8d71-49826de81000.png)

We can notice several things here:
* `writeStyleAttribute` takes most of the time spent in the `_beforeAnimationBuild`;
* was majority of time is spent evaluating a regular expression from `camelCaseToDashCase`;
* it is strange that we iterate over style properties multiple times.

The writeStyleAttribute implementation should be reviewed and improved from the performance point of view.

**Comment by JoostK** [comment]
Going to close this as the code was removed in #49630
