### ISSUE TITLE
AnimationPlayer does not clear transform after animation ends

### ISSUE THREAD

**Issue by wnvko** [angular/angular#35124]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/platform-browser/animations

### Is this a regression?
This is reproducible in Angular 8 and in Angular 9-rc13.

### Description
I am animating DOM element with AnimationPlayer. After animation end the inline style of the animated element is corrupted.

Note: this happens when animation is started via `keydown` handler. Issue does not reproduce if animation is started via button click

## 🔬 Minimal Reproduction

The issue is not reproducible in StackBlitz. Here is a [repo](https://github.com/wnvko/AngularAnimationsIssue) showing the issue.
Run the app and press `esc` key. This should start the animation. After animation ends the `#content` element's style contains `transform: matrix(1, 0, 0, 1, 0, -456.363);`.

## 🔥 Exception or Error

There is no exceptions, nor errors, but the element inline style is poluted.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.24
Node: 12.13.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms     
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------     
@angular-devkit/architect         0.803.24
@angular-devkit/build-angular     0.803.24
@angular-devkit/build-optimizer   0.803.24
@angular-devkit/build-webpack     0.803.24
@angular-devkit/core              8.3.24
@angular-devkit/schematics        8.3.24
@angular/cli                      8.3.24
@ngtools/webpack                  8.3.24
@schematics/angular               8.3.24
@schematics/update                0.803.24
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**
Happens only on Chrome 79.0.3945.130

Does not reproduce on:
Opera 66.0.3515.44
Firefox 72.0.2
Microsoft Edge 44.18362.449.0

**Comment by matsko** [comment]
@wnvko can you verify that it occurs on Chrome 80?

**Comment by wnvko** [comment]
@matsko no it is still broken in Google Chrome Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by dario-piotrowicz** [comment]
As far as I can tell this issue doesn't happen anymore

I have copied the repo's code and run it locally (on Chrome 104) with v14 and after the animation (triggered by pressing `esc` as instructed) no transform property is present in the element's styles:
![Screenshot at 2022-08-21 11-23-23](https://user-images.githubusercontent.com/61631103/185786681-00f00dac-d63c-49dd-a3bd-2bfaf15779a4.png)
![Screenshot at 2022-08-21 11-23-42](https://user-images.githubusercontent.com/61631103/185786683-46e4afae-065c-469c-b29b-de3329daf0d8.png)

**Comment by wnvko** [comment]
@dario-piotrowicz 
I cannot reproduce it also with latest Chrome. Closing the issue now.
