### ISSUE TITLE
'Your First App' instructions discrepancy 

### ISSUE THREAD

**Issue by blakemade** [angular/angular#35128]
# 📚 Docs or angular.io bug report

### Description

 

Section [Managing Data - Display the cart items- step 4] specifies to put the items setting method within the ngOnInit function definition, but section [Forms - Define the checkout form model - step 4] specifies that the items setting method and formBuilder group model setting method should both be in the constructor function definition.

### What's the affected URL?**
 https://angular.io/start/forms

### Expected vs Actual Behavior**

Instructions should specify why one should put these setting actions in either the constructor or in ngOnInit.

## 📷Screenshot

![image](https://user-images.githubusercontent.com/12532990/73682910-23448600-4676-11ea-978d-f29193f04024.png)

![image](https://user-images.githubusercontent.com/12532990/73683030-6272d700-4676-11ea-86a1-c90e0f54ee71.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by santoshyadav198613** [comment]
Hi @blakemade , 
Thanks for reporting this issue,its taken care in next version https://next.angular.io/start/forms please check, if you think it needs some changes let us know.

**Comment by blakemade** [comment]
This solves the discrepancy, but perhaps there should be a mention of using the constructor for class property initialization, while ngOnInit is a 'lifecycle hook' utilized for functionality other than property initialization such as change detection or consuming services.

If the Angular team feels this level of detail doesn't belong in a 'Your First App' -level of tutorial, that is understandable, in which case the issue should be closed.

Thanks

**Comment by aikidave** [comment]
Hi @blakemade! Thanks for your feedback! 

Your suggestion of briefly describing when to use the constructor and when to use ngOnInit is a good one. The other writers and I will look into this further!

Best,

aikidave, your friendly neighborhood technical writer

**Comment by zarend** [comment]
Thanks for reporting this issue. Luckily it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
