### ISSUE TITLE
ngClass/ngStyle are evaluated before exported directives

### ISSUE THREAD

**Issue by Andy1605** [angular/angular#35140]
# 🐞 bug report

### Affected Package
@angular/core 8.x

### Is this a regression?
The behaviour seemed different in Angular 6 (7 was never testet). Hard to say because a refactoring to onPush strategy was made simultaniously. Sorry for that.

### Description
I used to have a little helper directive which caches values inline in the template by using the exportsAs technique. This directive only holds a value property, is selected via "store-value" attribute and exports as "store".
The usage is as follows:
```html
<div #metaInfoStore=store [store-value]="getItemMeta(item)">{{metaInfoStore.value.name}} {{metaInfoStore.value.description}}</div>
```

Simple and works like a charm without having to implement anything in ngDoCheck().
The issue starts when i use the store value within class bindings (ngClass).

```html
<div #metaInfoStore=store [store-value]="getMeta()" [ngClass]="{'locked': metaInfoStore.value.locked}">{{metaInfoStore.value.name}} {{metaInfoStore.value.description}}</div>
```

When using the onPush change detection strategy, the ngClass directive is evaluated BEFORE the store directive is. I did not change any of my code, but updated to angular 8 and set change detection strategy to OnPush.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-1xr6cb
The div Element should receive the 'locked' class which it doesn't.

Thanks in advance.

**Comment by mhevery** [comment]
The stackblitz repo you sent is running in ViewEngine not Ivy, so I am not sure what the actual repro should be. 

PS: A slightly modified version of the repro: https://stackblitz.com/edit/angular-zcnw6a

**Comment by kara** [comment]
@mhevery From what I can tell, it looks like @Andy1605 is trying to file a bug report about Angular 8, which is View Engine by default. I don't think this is an Ivy issue.

**Comment by Andy1605** [comment]
@mhevery : @kara is right.
Did i declare smth wrong?

**Comment by pkozlowski-opensource** [comment]
> I used to have a little helper directive which caches values inline in the template by using the exportsAs technique. 

@Andy1605 out of curiosity - was the technique mostly performance-motivated (so, in your example, you don't have to call `getMeta()` repeatedly)? 

I don't think we want to commit to any order of directive bindings execution (as a public API) so your technique might be rather fragile wrt internal (framework) implementation choices. But more than anything, I would like to better understand the use-case / problem you are trying to solve. Would very much appreciate more info!

**Comment by Andy1605** [comment]
Thanks for your reply @pkozlowski-opensource .

Ok. The initial Use-Case is of-course a bit more than i showed here, since i stripped it down to the relevant core issue.
The main motivation is, to not need to pre-calculate stuff for a rendered item in the ngDoCheck().

One of many examples:
If you render a tree and you get the children of the item dynamically from a function which can be overwritten via template binding (also dynamically, e.g. on the tree component [item-children-function]="myItemChildrenGetter"). So i would, for example, ask the controller of my tree component for the child items of the current item visited by the template. Some bindings like ngIf, ngClass and ngFor within a rendered item are then also accessing the children list of each item.
To solve that i would have to implement the ngDoCheck() method, traverse the entire tree and set a property to remember the current children of each item, regardless of whether they are rendered at all (yes one could also restrict that here i know). I can save that seperate step and runtime, since the template visits each item anyways for rendering and binding checks, so it was always a nice and convenient way to achieve that.

Regardless of my "weird" use cases:
First: The behaviour between onPush and "check always" is behaving different, which i would classify as a bug on its own.
Second: An exported Directive could always calculate something or fetch any kind of information about the element itself, which i could never use in the ngClass directive.
Third: As of now i would have to nest the whole thing into a separate template node to achieve the same thing just because i switched the change detection mode.

Thank you.

**Comment by jelbourn** [comment]
Revisiting old issues- closing this since it's always been the case that Angular doesn't guarantee any particular evaluation order for directives on the same element.
