### ISSUE TITLE
Accessing angular 8 component from external project

### ISSUE THREAD

**Issue by athulya-ratheesh19** [angular/angular#35141]
I have 2 projects A & B . I need to access a angular component(8)created in A to B . How can we access angluar 8 component from an external hmtlpage/project.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
