### ISSUE TITLE
Use `Array` instead of `List`

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#3514]
And maybe always use the short syntax like `number[]`

**Comment by alexeagle** [comment]
I'm not currently working on this, it would be a good community contribution.

**Comment by yanivefraim** [comment]
@alexeagle - I would love to help, need some help starting with this. 10x!

**Comment by alexeagle** [comment]
Misko is already working on it, sorry!

**Comment by mhevery** [comment]
FYI: Part of this work: https://github.com/angular/angular/pull/3889/commits
