### ISSUE TITLE
@angular/bazel peer-depends on deprecated rollup packages

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#35149]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/bazel

### Is this a regression?

 No

### Description

`rollup-plugin-commonjs` and `rollup-plugin-node-resolve` packages that `@angular/bazel` peer-depends on have been deprecated. We should switch our peer deps to the new `@rollup/*` packages.

## 🔬 Minimal Reproduction

```
mkdir tmp
cd tmp
npm init -y
npm install typescript@~3.7.4 rxjs@^6.5.3 zone.js@~0.10.2 @bazel/typescript@^1.0.0 rollup@^1.20.0 rollup-plugin-commonjs@^9.0.0 rollup-plugin-node-resolve@^4.2.0 rollup-plugin-sourcemaps@0.4.0 @angular/{animations,bazel,common,compiler,compiler-cli,core,elements,forms,language-service,localize,platform-browser,platform-browser-dynamic,platform-server,platform-webworker,platform-webworker-dynamic,router,service-worker,upgrade} --save
```

## 🔥 Exception or Error
```
npm WARN deprecated rollup-plugin-commonjs@9.3.4: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.
npm WARN deprecated rollup-plugin-node-resolve@4.2.4: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>

@angular/bazel@@9.0.0-rc.14

</code></pre>

**Anything else relevant?**

**Comment by IgorMinar** [comment]
I'm marking this as a "breaking change" because the fix will require a change to our peer deps which is a breaking change.

**Comment by alexeagle** [comment]
Do you plan to deprecate and stop publishing the `@angular/bazel` package? I would expect this and a bunch of other issues could be closed.

**Comment by jbedard** [comment]
I've started having issues with `ng_package` crashing with modern versions of rollup. Things like `@bazel/rollup` and `ng-packagr` depend on a modern version where `@angular/bazel` depends on ancient versions of rollup and the plugins as mentioned here.

Could we up the peer-dep version to rollup v2 along with the plugins? I can open a PR to upgrade along with a 1-line change in `@angular/bazel` where the rollup API changed. This would be a breaking change so doing it soon for v12 would be nice...

**Comment by jbedard** [comment]
Actually fixing the crash is simple and non-breaking: #41101

Updating the deps + integration tests would still be nice though...

**Comment by JoostK** [comment]
Done in #43431 (the one that changes everything)
