### ISSUE TITLE
Inconsistent template references with and without Ivy (ViewChild vs template reference variable)

### ISSUE THREAD

**Issue by PeterBenko** [angular/angular#35161]
# 🐞 bug report

### Affected Package
 The issue is probably caused by the ivy compiler / in correlation with @angular/core

### Is this a regression?
Not that I'm aware of (introduced by Ivy)

### Description
Without Ivy enabled, elements injected with a ViewChild decorator === elements captured with a template reference variable, but this isn't the case when Ivy is enabled.

## 🔬 Minimal Reproduction
Without Ivy:
The TemplateRef of the same ng-template is identical when captured by @ViewChild and when captured as a template reference variable in the template.html

With Ivy:
The TemplateRefs captured in the above described way don't pass the identity check

**Examples**: 
I hope ng-run is acceptable instead of StackBlitz - I couldn't get Ivy to run there.
No Ivy: https://ng-run.com/edit/QUbQmAW7zPiu8qhuISEo
Ivy: https://ivy.ng-run.com/edit/9eCbebOKJTAUJAYbPViJ

## 🔥 Exception or Error
/

## 🌍  Your Environment

**Angular Version:**
Observed on 8.2.6 as well, not just the versions used on `ng-run.com`

**Anything else relevant?**
A side note/workaround. The wrapped nativeElements (in contrast to the TemplateRefs themselves) *are* identical, meaning:
`viewChild.elementRef.nativeElement === templateReference.elementRef.nativeElement`
returns true with or without Ivy.

**Comment by JoostK** [comment]
This change is mentioned [in the Ivy compatibility guide](https://v9.angular.io/guide/ivy-compatibility):

> Special injection tokens (such as TemplateRef or ViewContainerRef) return a new instance whenever they are requested (previously, instances of special tokens were shared if requested on the same node). This primarily affects tests that do identity comparison of these objects.

**Comment by PeterBenko** [comment]
Huh, I missed that doc, thanks! It describes the issue extremely well.
