### ISSUE TITLE
Ivy compiling: Could not be resolved to an NgModule class

### ISSUE THREAD

**Issue by bthieblot** [angular/angular#35169]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core@9.0.0-rc.14 and earlier versions as well.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular 8.2.14

### Description

 I'm trying to add a package (ng-json-view) but it's not working as expected.

## 🔬 Minimal Reproduction

https://ng-run.com/edit/14a544kjZ4BafWAg7BUr?open=app%2Fapp.component.ts&aot=true

## 🔥 Exception or Error
<pre><code>
error TS-996002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class
</code></pre>

**Comment by alexzuza** [comment]
ng-run doesn't run ngcc compilation on 3rd-party libraries. 

Can you please recreate the issue in github repository?

**Comment by Phil147** [comment]
Hi @alexzuza 
we are seeing this error for a long time now.
Reproduction: https://github.com/Phil147/ngcc-monorepo/tree/master

**Comment by air-Design** [comment]
I just updated my angular nx project to ng9 and all my modules of the my nx libs are showing this error.
Please help, or maybe i should rollback to ng8 for now.
```
libs/media/play-ui/src/lib/play-ui.module.ts:70:14 - error NG6002: Appears in the NgModule.imports of ActivityModule, but itself has errors

70 export class PlayUiModule { }
                ~~~~~~~~~~~~
libs/media/blog-ui/src/lib/blog-ui.module.ts:35:14 - error NG6002: Appears in the NgModule.imports of ActivityModule, but itself has errors

35 export class BlogUiModule { }
                ~~~~~~~~~~~~
libs/media/ui/src/lib/ui.module.ts:226:14 - error NG6002: Appears in the NgModule.imports of MessageModule, but itself has errors
```

**Comment by petebacondarwin** [comment]
It is not clear to me that this is the same issue as #34755. The ng-run example is not a monorepo.

**Comment by petebacondarwin** [comment]
I can reproduce this locally. The problem is that ngcc is not compiling the `ng-json-view` package correctly. Initially it looks like the `JsonViewComponent` class is not being exported publicly from the package but it is being referenced by the `JsonViewModule`.

I thought that ngcc should be able to actually add additional exports to the index.js for this but perhaps it is not able to for this CommonJS format?

**Comment by ARTWINPRO** [comment]
Guys, i have some solution but im not sure how currect it is.

```
1. "buildOptimizer": false,
2. "enableIvy": true
3. "aot": false,
```

Before do this refactoring, application size is: 18 440KB;
After: 17 887KB

**Comment by bthieblot** [comment]
Concerning this issue, the repo wasn't up to date, so now, with [ng-json-view@3.0.0](https://www.npmjs.com/package/ng-json-view/v/3.0.0), the problem is fixed. But I don't know how ngcc treat old libraries..

**Comment by petebacondarwin** [comment]
Thanks for the update @bthieblot. Glad it is now working.
If there is a latest version of a library that has been fixed to work with Angular v9 then we will not be trying to support older versions.
