### ISSUE TITLE
Add end to end tests for api search functionality

### ISSUE THREAD

**Issue by ajitsinghkaler** [angular/angular#35170]
# 📚 Docs or angular.io bug report

### Description

Add end to end tests for api search functionality on https://angular.io/api. On adding a new status in search by status found out we are testing it only by unit tests @gkalpak suggested that we should have some e2e tests for testing this functionality created this issue to keep tabs on that.
https://github.com/angular/angular/pull/34981#discussion_r374853453

### What's the affected URL?**
 https://angular.io/api

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by ajitsinghkaler** [comment]
@gkalpak there seems to be no file for end to end tests for api page should I create a new file for that

**Comment by gkalpak** [comment]
If it is just a couple of tests, then you can put them in [app.e2e-spec.ts][1]. Otherwise, you can create a new file, yes.

[1]: https://github.com/angular/angular/blob/b2222e7e0/aio/tests/e2e/src/app.e2e-spec.ts
