### ISSUE TITLE
document providedIn: any and platform

### ISSUE THREAD

**Issue by santoshyadavdev** [angular/angular#35179]
# 📚 Docs or angular.io bug report

### Description

Angular 9 introduces providedIn: any and platform for provided scope, which is not documented.

### What's the affected URL?**
https://next.angular.io/guide/providers#provider-scope

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by santoshyadav198613** [comment]
Hi @kapunahelewong ,

Let me know if you are working on something, or i can start updating the doc.

**Comment by kapunahelewong** [comment]
Good question, @santoshyadav198613. I'm not sure who might be writing this. Let's see what @aikidave might have in mind.

**Comment by santoshyadav198613** [comment]
Cool, @aikidave let me know, I would love to get it started. If it's not in your queue.

**Comment by santoshyadav198613** [comment]
I am working on this.

**Comment by vkvarma** [comment]
How to share the angular service between two angular elements using platform injector ?

**Comment by bitbaggi** [comment]
Anything new on @vkvarma asked question?
I need this feature, too.

**Comment by santoshyadav198613** [comment]
Hi @bitbaggi ,
There is another issue logged please follow https://github.com/angular/angular/issues/35429.
