### ISSUE TITLE
Implement ng-upgrade

### ISSUE THREAD

**Issue by mhevery** [angular/angular#3517]
https://docs.google.com/document/d/1xvBZoFuNq9hsgRhPPZOJC-Z48AHEbIBPlOCBTSD8m0Y

**Comment by mhevery** [comment]
done

**Comment by david-gang** [comment]
Hi,
Will the upgrade library be available in alpha 45?
Thanks,
David

**Comment by mhevery** [comment]
not sure when, but it should make it into a bundle in next few weeks.

**Comment by david-gang** [comment]
How will i know when it is released?
Will you drop here a message?
Are there other ways to know this?

Thanks

**Comment by PascalPrecht** [comment]
I think the easiest way is to follow this repo and check everyday what's happening. Releases go out almost on a weekly basis. Other than that some ppl in the community tweet about new releases (me included)

**Comment by rolandjitsu** [comment]
@PascalPrecht the team could have a [webhook](https://github.com/jamesseanwright/travis-twitter-webhook) that posts on Twitter every time there is a new release.
