### ISSUE TITLE
Better error handling for template variable redefinitions

### ISSUE THREAD

**Issue by villanyibalint** [angular/angular#35186]
# 🚀 Feature request: Better error handling for template variable redefinitions

### Command

- [ ] new
- [x] build
- [x] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
The new Ivy pipeline handles template variable redefinitions differently than in previous Angular versions. It would be great if issues stemming from this user error could be better highlighted at development stages with the Angular Language Service in editors or at compile time with a better error description from the compiler.

#### Incorrect code sample
This issue occurs if you redefine a template variable, like so:
![image](https://user-images.githubusercontent.com/9078166/73932569-e7f6c100-48da-11ea-8cb1-4b59ccad9486.png)
Component:
![image](https://user-images.githubusercontent.com/9078166/73934949-c4824500-48df-11ea-9ad7-86c0ea1d2887.png)
Notice that both loop variables are called _i_. Now obviously this is a user error and it is not an intended use of the loop variables.
However neither the Angular Language Service in VS Code or the compiler handle it well.
- The language service:
  - Doesn't highlight the variable redefinition, even as a warning.
  - Does highlight the property accessor being incorrect
  - Thinks that the latter defnition takes precedence over the former, since it thinks _i_ is going to be a number in this scope:
![image](https://user-images.githubusercontent.com/9078166/73932966-b9c5b100-48db-11ea-8f9e-29ce7dc54514.png)
    When in fact before Ivy this code did not produce any errors whatsoever, instead at runtime the loop variable held the former value and correctly iterated over the collection in the component and accessed the individual properties. Here is the rendered page for the above template:
![image](https://user-images.githubusercontent.com/9078166/73933267-5d16c600-48dc-11ea-91e4-05821e8659b1.png)
- The compiler:
  - After Ivy, the above template produces a compiler error. It produces:
    - no error when calling `ng build` in any version or configuration
    - a runtime error when calling `ng serve` with AOT turned off and Ivy turned on in Angular 8
    - a compile time error when calling `ng serve` with  both AOT and Ivy turned on in Angular 8
    - a compile time error when calling `ng serve` in Angular 9
    - a compile time error when calling `ng test` in Angular 9
![image](https://user-images.githubusercontent.com/9078166/73933965-d95dd900-48dd-11ea-87df-6a848fec5307.png)
![image](https://user-images.githubusercontent.com/9078166/73934065-03170000-48de-11ea-97e6-3656d839b05c.png)
This error message does not allow for effective debugging, since it does not mention in which template the problem occured. In fact it does not even state explicitly that it is a template error. The only way I managed to find the component was by modifying the compiler code and writing extra information to the console.

#### Updating to Ivy
Since previous Angular versions did not break on this error we only found it when upgrading a medium/large sized app to Angular 9 and suddenly a completely cryptic compiler error message prevented both testing and compiling. This feature might come in handy for others planning to update to Angular 9.

### Describe the solution you'd like
- The compiler should create a more verbose template error (template parse error?)
- The Angular Language Service should warn about variable redefinitions

### Describe alternatives you've considered
No real alternatives to consider.

### Sample
I have attached a sample component and template for testing in a completely new project:
[app.component.ts.txt](https://github.com/angular/angular-cli/files/4164894/app.component.ts.txt)
[app.component.html.txt](https://github.com/angular/angular-cli/files/4164893/app.component.html.txt)

**Comment by doliG** [comment]
I've got the same problem and finally understand that it's a template error by reading the source code.

Totally agree with the OP.
