### ISSUE TITLE
When all the children form controls are disabled, the parent becomes disabled

### ISSUE THREAD

**Issue by Mewster** [angular/angular#35184]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/forms

### Is this a regression?
Couldn't check.

### Description
Adding only disabled AbstractControl to a FormGroup or a FormArray disables their parent.
Moreover, the "value" field changes its behaviour when all the controls are disabled (showing all of them instead of only the enabled ones)

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-136pgu

## 🌍  Your Environment
**Angular Version:**
Angular CLI: 8.3.5
Node: 10.16.3
OS: linux x64
Angular: 8.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.5
@angular-devkit/build-angular     0.803.5
@angular-devkit/build-optimizer   0.803.5
@angular-devkit/build-webpack     0.803.5
@angular-devkit/core              8.3.5
@angular-devkit/schematics        8.3.5
@angular/cdk                      8.2.3
@angular/cli                      8.3.5
@ngtools/webpack                  8.3.5
@schematics/angular               8.3.5
@schematics/update                0.803.5
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

**Comment by Tidiane0843** [comment]
@Mewster don't know why but can't visualize your code with this link https://angular-yiry8u.stackblitz.io, because the page stayed blank.
Can you show your code here or provide another way to visualize please?

**Comment by Mewster** [comment]
@Tidiane0843 Sorry, I didn't understand how stackblitz work. Here is the correct link: https://stackblitz.com/edit/angular-yiry8u

**Comment by Bil0** [comment]
@Mewster, I think this is the default behavior.

if you want to disable specific `formControl` without propagation you need to set `onlySelf` to `true`

for more info check [disable method](https://angular.io/api/forms/AbstractControl#disable)

**Comment by Mewster** [comment]
> if you want to disable specific `formControl` without propagation you need to set `onlySelf` to `true`

That doesn't work too. Adding example to the stackblitz

**Comment by TidianeRol** [comment]
@Mewster I think the problem is the behavior of the field value. Because if you have a form which contains only disabled controls, the form should also be disabled. 
But the field value should only contain the enabled controls value while the getrawvalue contains all value (enabled or not). 
I fixex the behavior of the field value.
Hope it'll help

**Comment by Mewster** [comment]
@TidianeRol I don't think that a form that contains only disabled controls should be disabled; in case the parent form has a validator, it should still be able to validate (even a simple Validators.required wouldn't work this way).
In my case I had a formarray that must contain (through a size validator) at least a specific number of children, that don't have to be valid in that specific moment and therefore disabled. But if they were all disabled, the children count validator wouldn't work.

**Comment by yelhouti** [comment]
I'm facing the same problem here, with a FormArray with disabled controls/children I want it's validation.required to keep working, but since it get's disabled two, required is ignoredm I agree that disabling the parent, should disable it's children, but why the other way around?
Also this results on adding other elements to the parent having them get disabled two...

**Comment by AndrewKushnir** [comment]
Hi @Mewster, thanks for reporting the issue and providing a repro. It looks like the current logic works as expected. If your use-case require having a Form in a valid (i.e. not disabled) state, you can do that by using `FormGroup.enable()` API. I've created a copy of your repro and added an "Enable Form" button to illustrate that ([see here](https://stackblitz.com/edit/angular-136pgu-paezsg?file=src%2Fapp%2Fapp.component.ts)). Thank you.

**Comment by Mewster** [comment]
Having to re-enable manually the form after adding a disabled control to an empty enabled form seems more a workaround than an expected working logic, to me...

**Comment by Mewster** [comment]
Uh... @AndrewKushnir your stackblitz is wrong since you are enabling the form and all their children, while the issue I opened was about having the parent form enabled (and its' validator checked), while the children have to still be disabled.
