### ISSUE TITLE
I can't create dynamic FormGroup  manually

### ISSUE THREAD

**Issue by MuhammadAbdelsalam** [angular/angular#35189]
this code not work fine at first time page load and fire exception

component.ts
    this.contactForm = new FormGroup({
      name: new FormControl(),
       phones: new FormArray([new FormGroup({Phone: new FormControl('')})])
         });

component.html
<div formArrayName="phones">
            <div *ngFor="let item of phones.controls; let phoneIndex = index" [formGroupName]="phoneIndex">
                <label>
                    Phone: <input formControlName="phone" />
                </label>
                <button type="button" (click)="deletePhone(phoneIndex)">Delete Phone</button>
            </div>
            <button type="button" (click)="addPhone()">Add Phone</button>
        </div>

Exception :
Cannot find control with path: 'phones -> 0 -> phone'

if I used formbuilder, it will work fine 
 this.contactForm = this.fb.group({
      name: '',
      address: '',
      note: '',
      phones: this.fb.array([this.fb.group({phone:''})])
    });

Angular CLI: 8.3.23
Node: 12.14.1
OS: win32 x64

**Comment by Airblader** [comment]
You used Phone instead of phone in the manual version. Also, this is an issue tracker, not a support forum.
