### ISSUE TITLE
Unclear documentation about Changing your app's location

### ISSUE THREAD

**Issue by valgussev** [angular/angular#35187]
# 📚 Docs or angular.io bug report

### Description

In the [documentation](https://angular.io/guide/service-worker-devops#changing-your-apps-location) it is written 
> To remedy this, you may need to kill the old worker using one of the above techniques (Fail-safe or Safety Worker).

By **this** an error `The script resource is behind a redirect, which is disallowed.` is meant.

How can [Safety Worker](https://angular.io/guide/service-worker-devops#safety-worker) technique help here if according to 

> If you setup a redirect from the old location (for example example.com) to the new location (for example www.example.com) the worker will stop working

it is not possible to install a new service worker?

**Comment by kapunahelewong** [comment]
Status:  Docs team Needs engineering advice on how to correct this point in the documentation.

**Comment by josephperrott** [comment]
Closing as this is actually covered in the Safety Worker section.

>It's important to note that you cannot register this worker directly, as old clients with cached state may not see a new index.html which installs the different worker script. Instead, you must serve the contents of safety-worker.js at the URL of the Service Worker script you are trying to unregister, and must continue to do so until you are certain all users have successfully unregistered the old worker.
