### ISSUE TITLE
operators definition conflicting with ReactiveX/rxjs definition. "They return a function" vs "should return an observable"

### ISSUE THREAD

**Issue by ghuser** [angular/angular#35183]
# 📚 Docs or angular.io bug report

### Description

 
In the section https://angular.io/guide/rx-library#operators there is a definition of an operator: 

> ..Operators take configuration options, and **they return a function that takes a source observable**.

But in [rxjs guidelines](https://github.com/ReactiveX/rxjs/blob/master/doc/operator-creation.md#guidelines) about operation creation they say: 

> Operators should always return an Observable. [...]If you create a **method that returns something other than an Observable, it's not an operator**, and that's fine.

Clearly there is a conflicting definition: "they return a function"" vs "should always return an observable".

### What's the affected URL?**
 
https://angular.io/guide/rx-library#operators

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by BioPhoton** [comment]
Dear @ghuser 
> If you create a method that returns something other than an Observable, it's not an operator, and that's fine.

IMHO the whole sentence is useless. :D

What you should fouse about is:
- creation of `Observable`
- creation of `OperatorFunction`

**Observable:**

Static:
```typescript
const arr = [1,2,3,4];
const o = new Observable((subscriber => {
  arr.foeEach(n => subscriber.next(n))
  subscriber.complete()
}));
```
Creation Function:
```typescript
const arr = [1,2,3,4];
function createObserfableFromArray(arr) => {
  return new Observable((subscriber => {
    arr.foeEach(n => subscriber.next(n))
    subscriber.complete()
  }));
}
const o =createObserfableFromArray = (arr) ;
```
**Operators**

Static:
```typescript
function log(observable) => {
  return observable.pipe(tap(value => console.log(value)));
}

observable.pipe(
  log
)
```


Creation Function:
```typescript
function logCreation(param) {
  return function(observable) => {
    return observable.pipe(
     tap(value => console.log(param, value))
   );
  }
}

observable.pipe(
  logCreation('value: ')
)
```

---

To sum up:

Operators are functions that take an Observable and return an observable:
- `(o: Observable) => Observable`
If you wrap them in a function to create them they are configurable:
- `(cfg) => (o: Observable) => Observable`

Observables can be created by using instantiating a new one:
- `new Observable`
or by a function:
- `(arg?: any) => Observable`

---

Let me know if this helps.

Best,
Michael

**Comment by kapunahelewong** [comment]
Thank you so much, @BioPhoton!! @ghuser, does that help you? We can also clear up the docs on this point.

**Comment by ghuser** [comment]
@BioPhoton

It is more clear now, though this syntax confused me:

`function createObserfableFromArray(arr) => {`

and

`const o =createObserfableFromArray = (arr) ;`

**Comment by kapunahelewong** [comment]
Status: Docs Team can use the excellent explanation by @BioPhoton to update the documentation.
