### ISSUE TITLE
HashLocationStrategy and NavigationExtras.fragment clash

### ISSUE THREAD

**Issue by PRR24** [angular/angular#35181]
If NavigationExtras.fragment is used together with HashLocationStrategy, the URL created will look smth like: https://site.com/#/route?query=param#fragment e.g. the URL contains two #-symbols.
I am not fully sure whether this is a valid URL according to RFC, but in practice GMail, Apple Mail and possibly more applications destroy it by escaping second #.

If double-hashed URLs **are** valid according to the standard, please consider this as a feature request to use different symbol (or make configurable) for fragment separation.
If these URLs are **not** valid, please consider it as a bug report.

**Comment by atscott** [comment]
Having multiple hashes in the url isn't specifically invalid. Everything after the first `#` is part of the fragment.

> A fragment identifier component is indicated by the presence of a number sign ("#") character and terminated by the end of the URI.

Documentation for the `HashLocationStrategy` states
> A LocationStrategy used to configure the Location service to represent its state in the hash fragment of the browser's URL.

It seems reasonable what the router does when providing a fragment in `NavigationExtras` with `HashLocationStrategy`. Using a different symbol for 'fragment' wouldn't align with the RFC (calling a thing in the URI a 'fragment' and then not using the specified symbol) so this doesn't seem like an option. Additionally, it feels like you could accomplish this same behavior by putting this into a query param instead: `?fragment=abc`. Another option that could work for you is implementing your own `LocationStrategy`. All things considered, I'm inclined to say that this is working as intended.
