### ISSUE TITLE
angular2_material should expose libraries from /lib

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#3518]
It currently only exposes libraries from `/lib/src`, which, by convention, is private in Dart. This currently prevents us from generating API docs for material components.

**Comment by jelbourn** [comment]
Who wants to generate API docs? Nobody should be using these components for real now, and none of the classes actually have any public API.

**Comment by yjbanov** [comment]
dartdocs.org generates API docs for every package hosted on pub automatically and right now it [fails to generate them](http://www.dartdocs.org/buildlogs/b-0914a33b24cea9f1be97b39571e09-startupscript.log) for our material components.

What do you mean by saying that components don't have public API? They are imported (to be listed in `directives`) and they can also be loaded dynamically, in which case instead of template bindings users would call setters directly.

**Comment by yjbanov** [comment]
That said, feel free to deprioritize. I only logged it so I could reference something in my TODO so people not wonder why we are excusing material library from API docs.

**Comment by jelbourn** [comment]
I'm bumping this down to P4 since these components aren't going to be meant to actual consumption until much later.

**Comment by pkozlowski-opensource** [comment]
I guess this one belongs more to https://github.com/angular/material2 now
