### ISSUE TITLE
Ivy compiler doesn't work with secondary entry points in libraries using dist folder

### ISSUE THREAD

**Issue by jeripeierSBB** [angular/angular#35188]
# 🐞 bug report

### Affected Package
@angular/compiler@9.0.0 (ngcc)

### Is this a regression?
Not known

### Description
We have a monorepo managed with the Angular CLI with several libraries, each with secondary entry points, and a showcase. We build the libraries using the ViewEngine compiler and the showcase with Ivy. Once we build the showcase, Ivy seems to fail to compile imported symbols in secondary entry points, which results in the error code NG6002 (See error below).

We used the following guide for secondary entry points: https://github.com/ng-packagr/ng-packagr/blob/v9.0.0/docs/secondary-entrypoints.md
The built library artifacts reside in the dist folder (default Angular CLI configuration)

Strangely enough, when we copy the build artifacts into node_modules and remove the `compilerOptions.paths` entry in tsconfig.json, ngcc seems to compile it successfully.
If we leave it in dist, ngcc seems to stop compiling secondary entrypoints after the first/entry file.

## 🔬 Minimal Reproduction
1. clone https://github.com/jeripeierSBB/lib-with-secondary-entry-points
2. `ng build my-lib --prod`
3. `ng build showcase --prod` (or `ng serve`)

## 🔥 Exception or Error
<pre><code>
ERROR in dist/my-lib/my-feature/my-feature.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

1 export declare class MyFeatureModule {

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0
Node: 13.7.0
OS: darwin x64

Angular: 9.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0
@angular-devkit/build-angular      0.900.0
@angular-devkit/build-ng-packagr   0.900.0
@angular-devkit/build-optimizer    0.900.0
@angular-devkit/build-webpack      0.900.0
@angular-devkit/core               9.0.0
@angular-devkit/schematics         9.0.0
@ngtools/webpack                   9.0.0
@schematics/angular                9.0.0
@schematics/update                 0.900.0
ng-packagr                         9.0.0
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2

</code></pre>

**Anything else relevant?**

## Workaround
1. `ng build my-lib --prod`
2. copy content of dist folder to node_modules
3. remove `compilerOptions.paths` in tsconfig.json
4. `ng build showcase --prod` (or `ng serve`)
5. compiles successfully

**Comment by jeripeierSBB** [comment]
updated this issue and reproduction from Angular version 9.0.0-rc.14 to version 9.0.0

**Comment by petebacondarwin** [comment]
This is a bug in our `TargetedEntryPointFinder` inside the `computePackagePath()` function, shown below for reference. The problem is that when the target is `my-lib/my-feature` it computes that the package path is `my-lib/my-feature` rather than `my-lib`.

This leads to ngcc creating the special "ngcc folder" that contains the processed files in the secondary entry-point rather than the primary package folder, which is where the CLI build is configured to look for it. In other words we create `lib-with-secondary-entry-points/dist/my-lib/my-feature/__ivy_ngcc__` rather than `lib-with-secondary-entry-points/dist/my-lib/__ivy_ngcc__`.

https://github.com/angular/angular/blob/d3650ce3d849634a3a8ffb8e34d9d3e99b378e5d/packages/compiler-cli/ngcc/src/entry_point_finder/targeted_entry_point_finder.ts#L97-L142

**Comment by petebacondarwin** [comment]
Hopefully #35227 will fix this. I am just building and trying out on the reproduction from above.

**Comment by petebacondarwin** [comment]
I can confirm that, locally, this PR fixes the repro.

**Comment by jeripeierSBB** [comment]
@petebacondarwin Many Thanks, looking forward to the release :-)
