### ISSUE TITLE
Ivy enabling

### ISSUE THREAD

**Issue by EKashpersky** [angular/angular#35198]
To enable ivy for **ng serve** I have to set **enableIvy** to **false**

At least when I do that **vendor.js** shrinks >10 times 

Everything is updated to **Angular 9**

**Comment by EKashpersky** [comment]
There're also errors saying "*.ngfactory.js not found"
![image](https://user-images.githubusercontent.com/10428637/73984432-48204e00-4941-11ea-8182-d9124a4bc53d.png)

**Comment by AndrewKushnir** [comment]
Hi @EKashpersky, could you please provide a minimum repro (in a form of Github repo), so that we can perform further investigation? Thank you.

**Comment by EKashpersky** [comment]
@AndrewKushnir I've figured it out.
The thing is I have an error while serving with Ivy.

I've just migrated ngx-admin to Angular9, enabled ivy and also got an error while serving.

The vendor bundle has exact same size(340kb), which I concluded to be related, so I'm closing the ticket.
