### ISSUE TITLE
Docs: Interfaces/Classes don't show types

### ISSUE THREAD

**Issue by btesser** [angular/angular#3519]
The generated docs of typescript files don't show the type of class and interface members.

**Comment by mhevery** [comment]
Could you be more descriptive? The example I am looking at shows types. Can you give what you see and what you would like to see?

**Comment by btesser** [comment]
Within a class or interface, member functions include argument types, but instance properties show no types.  This isn't just a lack of inline documentation or lack of used types within typescript as I've applied your docs build process to my application and I've seen the same thing.

Here's a few examples from the live docs site that demonstrate this (as well as a picture)
https://angular.io/docs/js/latest/api/forms/AbstractControlDirective-class.html
https://angular.io/docs/js/latest/api/forms/ControlContainer-class.html
https://angular.io/docs/js/latest/api/forms/NgControlName-class.html

![image](https://cloud.githubusercontent.com/assets/830336/9187086/8f036fb0-3f9a-11e5-8119-8e2a060d3ad2.png)

**Comment by mhevery** [comment]
Good point.

**Comment by mhevery** [comment]
Duplicate of #3571
