### ISSUE TITLE
Support TypeScript 3.8

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular#35204]
# 🚀 feature request

### Relevant Package

@angular/core

### Description

TypeScript 3.8-rc was released today. It includes plenty of useful new features, like Type-Only Imports and Export,  ECMAScript Private Fields,  and `export * as ns` Syntax. Angular should support it.

**Comment by alxhub** [comment]
Hello @xiaoxiangmoe, thank you for the suggestion!

Angular only upgrades its TypeScript version on major releases (because it's always a potentially breaking change for users). v9.0 which was released yesterday brought us to TypeScript 3.7. So Angular v10 will upgrade to 3.8 (or even 3.9 if it's out by then).

We also don't typically upgrade to -rc versions of TS, as they're not fully stable yet.

That said, nothing prevents yourself as a project author from trying TypeScript 3.8 with Angular and seeing how it works. If you find bugs, feel free to file them and we will fix them if possible - we will always try to be compatible, even if our version requirement is pinned to a lower version.

Thanks,
Alex

**Comment by EatonZ** [comment]
@alxhub Is that a new policy? Angular 8.2, a minor release, brought TypeScript 3.5 support, so it would seem logical that 9.1 would bring 3.8 support.

BTW, Microsoft [has this to say](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-rc/) about 3.8 RC, so it's probably safe to start working on it now:

> Between this RC and our final release, we expect no changes apart from critical bug fixes.

**Comment by fr0** [comment]
> Angular only upgrades its TypeScript version on major releases (because it's always a potentially breaking change for users). v9.0 which was released yesterday brought us to TypeScript 3.7. So Angular v10 will upgrade to 3.8 (or even 3.9 if it's out by then).

If this is true, it is definitely a new policy.

TypeScript 3.5 support was added in Angular 8.2.
TypeScript 3.2 support was added in Angular 7.2.

**Comment by Lonli-Lokli** [comment]
My 2c, Typescript 3.7 has been included into current 9.0 just because of failed deadlines for delivering Ivy.

**Comment by EatonZ** [comment]
[3.8 now released](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8/) FYI.

**Comment by EatonZ** [comment]
@alxhub Can you re-open this? Even if you don't plan on implementing it soon, it should remain open for tracking (it's been like this for all previous TS requests).

**Comment by bbarry** [comment]
> That said, nothing prevents yourself as a project author from trying TypeScript 3.8 with Angular and seeing how it works. If you find bugs, feel free to file them and we will fix them if possible - we will always try to be compatible, even if our version requirement is pinned to a lower version.

Maybe this is a documentation problem? When I attempt to force an update to typescript:

    > npm outdated
    Package     Current  Wanted  Latest  Location
    typescript    3.7.5   3.7.5   3.8.3  myregistry

    > ng update typescript
    Using package manager: 'npm'
    Collecting installed dependencies...
    Found 46 dependencies.
    Fetching dependency metadata from registry...
    × Migration failed: Incompatible peer dependencies found.
    Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
    You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
      See "C:\Users\bbarry\AppData\Local\Temp\1\ng-lIuUni\angular-errors.log" for further details.

    > ng update typescript --force
    Using package manager: 'npm'
    Collecting installed dependencies...
    Found 46 dependencies.
    Fetching dependency metadata from registry...
                      Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=3.6 <3.8", would install "3.8.3").
        Updating package.json with dependency typescript @ "3.8.3" (was "3.7.5")...
    UPDATE package.json (2162 bytes)
    √ Packages installed successfully.


    > ng build --aot --prod --subresource-integrity
    WARNING in webpack-subresource-integrity: Cannot determine asset for chunk scripts, computed="undefined", available=scripts.584061c84cca79c079f4.js. Please report this full error message along with your 
    Webpack configuration at https://github.com/waysact/webpack-subresource-integrity/issues/new

    ERROR in The Angular Compiler requires TypeScript >=3.6.4 and <3.8.0 but 3.8.3 was found instead.
    npm ERR! code ELIFECYCLE
    ...

and here I am stuck?

**Comment by Brian611** [comment]
facing the same issue as @bbarry

**Comment by crfrolik** [comment]
You should try using the `disableTypeScriptVersionCheck` option as mentioned here: https://github.com/angular/angular-cli/issues/16071#issuecomment-551614783

However, you may encounter other issues after you do this, see also ttps://github.com/angular/angular-cli/issues/17104

**Comment by EatonZ** [comment]
@alxhub Thanks for reconsidering.😁
Someone can close this now ince [it just landed](https://github.com/angular/angular/pull/35864).

**Comment by Brian611** [comment]
@EatonZ thats great so how do we pull this? is it a global fix that can be sorted up with an ng update?

**Comment by EatonZ** [comment]
@Brian611 Just upgrade to 9.1.0-next.4. That's the first one with it.

**Comment by gkalpak** [comment]
Fixed by #35864.
