### ISSUE TITLE
The ngForm component has a '_directives' property. This returns the ngModel associated with the form. The '_directives' property is a private property. Is it safe to access this property? 

### ISSUE THREAD

**Issue by akshaykmr080** [angular/angular#35206]
The '_directives' property holds the ngModel array reference.
Is there a possibility that the '_directives' private property will be removed in the future?

Is there a better way to access the ngModel associated with the form. The ngModel has a valueAccessor property. I am looking to access this property

**Comment by Airblader** [comment]
Private properties are not public API and what isn't public API is prone to change at any point in time.

You should describe what you're actually looking to do, but not here and rather on StackOverflow. You can get the CVA of a component from its injector.

**Comment by pkozlowski-opensource** [comment]
As commented by @Airblader all private members are _not_ part of the public API and can change at any time without notification.
