### ISSUE TITLE
ngDoBootstrap doesn't fire on Angular 9

### ISSUE THREAD

**Issue by wellwind** [angular/angular#35205]
# 🐞 bug report

### Description

After update Angular CLI 9 and create a new project, I found `ngDoBootstrap()` doesn't fire.

## 🔬 Minimal Reproduction

https://github.com/wellwind/ng9-ngdobootstrap-not-fired

1. npm install -g @angular/cli
2. ng new ng9-ngdobootstrap-not-fired
3. open `app.module.ts`
4. add this code into AppModule class
```
  ngDoBootstrap() {
    console.log('test');
  }
```
5. `npm start`
6. open the browser and F12, didn't see and output.

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 9.0.1
Node: 12.13.0
OS: win32 x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

**Comment by alexzuza** [comment]
It works for me the same way as it was in Angular 8 ViewEngine.
You need to comment [bootstrap ](https://github.com/wellwind/ng9-ngdobootstrap-not-fired/blob/2c631fd5ab8807096f97edd99d5b12edf29b6c61/src/app/app.module.ts#L14) section

```
// bootstrap: [AppComponent]
```

**Comment by wellwind** [comment]
It works now by commenting `bootstrap: []` section, thank you.

> It works for me the same way as it was in Angular 8 ViewEngine.
> You need to comment [bootstrap ](https://github.com/wellwind/ng9-ngdobootstrap-not-fired/blob/2c631fd5ab8807096f97edd99d5b12edf29b6c61/src/app/app.module.ts#L14) section
> 
> ```
> // bootstrap: [AppComponent]
> ```
