### ISSUE TITLE
sometime form .get return null

### ISSUE THREAD

**Issue by mix5003** [angular/angular#35219]
# 🐞 bug report
sometime form .get return null. i have no idea why? 
for example in my code i just add `withholdingTax.items` in to form and i try to subscribe valueChanges but it said i try to access valueChanges of null value 
![valueChangesOfNull1](https://user-images.githubusercontent.com/1129524/74016932-d76f4500-49c5-11ea-993d-9d40e933d9c7.png)
![valueChangesOfNull2](https://user-images.githubusercontent.com/1129524/74016939-d9390880-49c5-11ea-9a8d-625d0e15ebba.png)

After i try to find a re-produce step to fix it i found that sometime `form.get` will return null. as you can see in next screenshot line 195 and 199 is same code (`console.log(this.form.get('withholdingTax.items'));` and not touch any controls in the form but result is different 
![valueChangesOfNull3](https://user-images.githubusercontent.com/1129524/74017193-5f554f00-49c6-11ea-9a9c-9d69be955d14.png)
 
list of error that i found
- `Cannot read property 'controls' of null`
- `Cannot read property 'valueChanges' of null`
- `Cannot read property 'setValue' of null`
- `Cannot read property 'value' of null`
- `Cannot find control with name`
- `Cannot read property 'length' of null` (FormArray)

### Affected Package
i think it should be `@angular/forms`

### Description

 A clear and concise description of the problem...
```
TypeError: Cannot read property 'valueChanges' of null
    at FormPaymentVoucherComponent.push../src/app/purchase/payment-voucher/form-payment-voucher/form-payment-voucher.component.ts.FormPaymentVoucherComponent.initForm (form-payment-voucher.component.ts:193)
    at FormPaymentVoucherComponent.push../src/app/component/base-form/base-form.component.ts.BaseFormComponent.ngOnInit (base-form.component.ts:36)
    at FormPaymentVoucherComponent.push../src/app/purchase/shared/base-purchase-form/base-purchase-form.component.ts.BasePurchaseFormComponent.ngOnInit (base-purchase-form.component.ts:49)
    at FormPaymentVoucherComponent.push../src/app/purchase/payment-voucher/form-payment-voucher/form-payment-voucher.component.ts.FormPaymentVoucherComponent.ngOnInit (form-payment-voucher.component.ts:99)
    at checkAndUpdateDirectiveInline (core.js:21096)
    at checkAndUpdateNodeInline (core.js:29494)
    at checkAndUpdateNode (core.js:29456)
    at debugCheckAndUpdateNode (core.js:30090)
    at debugCheckDirectivesFn (core.js:30050)
    at Object.eval [as updateDirectives] (FormPurchaseComponent.html:256)


  | push../src/app/shared/error-handler.ts.RavenErrorHandler.handleError | @ | error-handler.ts:110
-- | -- | -- | --
  | (anonymous) | @ | core.js:27136
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke | @ | zone.js:391
  | push../node_modules/zone.js/dist/zone.js.Zone.run | @ | zone.js:150
  | push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular | @ | core.js:26214
  | push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick | @ | core.js:27136
  | (anonymous) | @ | core.js:26997
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke | @ | zone.js:391
  | onInvoke | @ | core.js:26255
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke | @ | zone.js:390
  | push../node_modules/zone.js/dist/zone.js.Zone.run | @ | zone.js:150
  | push../node_modules/@angular/core/fesm5/core.js.NgZone.run | @ | core.js:26169
  | next | @ | core.js:26997
  | schedulerFn | @ | core.js:23734
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub | @ | Subscriber.js:192
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next | @ | Subscriber.js:130
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next | @ | Subscriber.js:76
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next | @ | Subject.js:47
  | push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit | @ | core.js:23718
  | checkStable | @ | core.js:26224
  | onHasTask | @ | core.js:26268
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.hasTask | @ | zone.js:443
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate._updateTaskCount | @ | zone.js:463
  | push../node_modules/zone.js/dist/zone.js.Zone._updateTaskCount | @ | zone.js:291
  | push../node_modules/zone.js/dist/zone.js.Zone.runTask | @ | zone.js:212
  | drainMicroTaskQueue | @ | zone.js:601
  | push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask | @ | zone.js:502
  | invokeTask | @ | zone.js:1693
  | globalZoneAwareCallback | @ | zone.js:1719
```
</code></pre>

## 🌍  Your Environment
```Angular CLI: 8.3.3
Node: 10.19.0
OS: linux x64
Angular: 8.2.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.3
@angular-devkit/build-angular     0.803.3
@angular-devkit/build-optimizer   0.803.3
@angular-devkit/build-webpack     0.803.3
@angular-devkit/core              8.3.3
@angular-devkit/schematics        8.3.3
@angular/cdk                      7.3.0
@angular/cli                      8.3.3
@ngtools/webpack                  8.3.3
@schematics/angular               8.3.3
@schematics/update                0.803.3
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
```

</code></pre>

**Anything else relevant?**
i think this is browser specific issue. my issue tracker said this issue appear on
- Chrome Version 80.0.3987.87 (Official Build) (64-bit) on Linux Mint 19 Cinnamon
- Chrome 80.0.3987 on Windows 7,8,10
- Chrome 81.0.4044 on Windows 7,10
- Chrome Mobile 80.0.3987 on Android 10
 
i am not sure is this same issue with #35214 or not

**Comment by michalma** [comment]
I think it's the same issue like reported in #35214. `formGroup.get('foo')` returns `null` randomly (but the field `foo` exists).

- Angular 8.2.3
- Chrome 80.0.3987
- Windows 7,8,10
- Mac OS X 10.15.1

Some of the errors i have:
`Cannot read property 'valueChanges' of null`
`Cannot find control with name: 'foo'`
`Cannot find control with unspecified name attribute`

**Comment by swftvsn** [comment]
This is really serious bug and should be dealt with immediately.

**Comment by skyquartam** [comment]
We have the same bug in Production site, Angular (and Material) v7, it happens only on Chrome 80

**Comment by gultyaev** [comment]
Also have experienced this bug. By some reason it happens on a first start of app. If you can repeat the process after the error occurred it doesn't happen again.

**Comment by noobed7** [comment]
It's a production show stopper for at the moment. Could you give an ETA of any kind about chrome fix or an official work around?

**Comment by mix5003** [comment]
i found someone found relate bug in other issue  https://github.com/angular/angular/issues/35190#issuecomment-583341817

https://bugs.chromium.org/p/chromium/issues/detail?id=1049982

**Comment by swftvsn** [comment]
so a quick fix would be to release a version of angular that does not use `Array.reduce()`. 

How long will it take for the chromium fix to trickle down for end users?

**Comment by sphela02** [comment]
What if we replaced Array.prototype.reduce() with a function that didn't fail?  Even if it was a bit slower.

**Comment by mix5003** [comment]
@sphela02 problem may solved. at least my sentry didn't report anything about this for 4 hours.

**Comment by shravan20084312** [comment]
> @sphela02 problem may solved. at least my sentry didn't report anything about this for 4 hours.

Was there any particular workaround applied? can you please share, if so.

**Comment by rodolfojnn** [comment]
It was happening in Chrome Canary a few weeks ago, but I thought it was something related to that version

**Comment by mix5003** [comment]
@shravan20084312 it quick dirty fix so i just add this to main.ts
```
(function () {
  function getChromeVersion() {
    const raw = navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);

    return raw ? parseInt(raw[2], 10) : false;
  }

  const chromeVersion = getChromeVersion();
  if (chromeVersion && chromeVersion >= 80) {
    Array.prototype.reduce = function (callback /*, initialValue*/) {
      'use strict';
      if (this == null) {
        throw new TypeError('Array.prototype.reduce called on null or undefined');
      }
      if (typeof callback !== 'function') {
        throw new TypeError(callback + ' is not a function');
      }
      let t = Object(this), len = t.length >>> 0, k = 0, value;
      if (arguments.length === 2) {
        value = arguments[1];
      } else {
        while (k < len && !(k in t)) {
          k++;
        }
        if (k >= len) {
          throw new TypeError('Reduce of empty array with no initial value');
        }
        value = t[k++];
      }
      for (; k < len; k++) {
        if (k in t) {
          value = callback(value, t[k], k, t);
        }
      }
      return value;
    };
  }
})();
```

i grab this code from https://gist.github.com/lski/0eae0d2738831b6b0ec2b88a8a603952

**Comment by shravan20084312** [comment]
> @shravan20084312 it quick dirty fix so i just add this to main.ts
> 
> ```
> (function () {
>   function getChromeVersion() {
>     const raw = navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);
> 
>     return raw ? parseInt(raw[2], 10) : false;
>   }
> 
>   const chromeVersion = getChromeVersion();
>   if (chromeVersion && chromeVersion >= 80) {
>     Array.prototype.reduce = function (callback /*, initialValue*/) {
>       'use strict';
>       if (this == null) {
>         throw new TypeError('Array.prototype.reduce called on null or undefined');
>       }
>       if (typeof callback !== 'function') {
>         throw new TypeError(callback + ' is not a function');
>       }
>       let t = Object(this), len = t.length >>> 0, k = 0, value;
>       if (arguments.length === 2) {
>         value = arguments[1];
>       } else {
>         while (k < len && !(k in t)) {
>           k++;
>         }
>         if (k >= len) {
>           throw new TypeError('Reduce of empty array with no initial value');
>         }
>         value = t[k++];
>       }
>       for (; k < len; k++) {
>         if (k in t) {
>           value = callback(value, t[k], k, t);
>         }
>       }
>       return value;
>     };
>   }
> })();
> ```
> 
> i grab this code from https://gist.github.com/lski/0eae0d2738831b6b0ec2b88a8a603952

As a workaround, we are seeing this to resolve the issue for now, until we get a stable fix from Angular/chrome.

**Comment by rodolfojnn** [comment]
I´m using this as a workaroung:

```
(function() {
	const arrayReduce = Array.prototype.reduce;
	let callback;
	Object.defineProperty(Array.prototype, 'reduce', {
		value: function(cb, ...args) {
			callback = cb;
			return arrayReduce.call(this, callback, ...args);
		}
	});
})();
```

**Comment by sphela02** [comment]
It looks like @shravan20084312 might have done it more elegantly than us (s*he checks Chome version), but here's what we did.

We created this as a polyfill, and we're including it with our other polyfills.

```
Array.prototype.reduce = function(callback /*, initialValue*/) {
  'use strict';
  if (this === null) {
    throw new TypeError('Array.prototype.reduce called on null or undefined');
  }
  if (typeof callback !== 'function') {
    throw new TypeError(callback + ' is not a function');
  }
  var t = Object(this), len = t.length >>> 0, k = 0, value;
  if (arguments.length == 2) {
    value = arguments[1];
  } else {
    while (k < len && !(k in t)) {
      k++; 
    }
    if (k >= len) {
      throw new TypeError('Reduce of empty array with no initial value');
    }
    value = t[k++];
  }
  for (; k < len; k++) {
    if (k in t) {
      value = callback(value, t[k], k, t);
    }
  }
  return value;
}; 

```

**Comment by shravan20084312** [comment]
> I´m using this as a workaroung from https://bugs.chromium.org/p/chromium/issues/detail?id=1049982
> 
> ```
> (function() {
>   const arrayReduce = Array.prototype.reduce;
>   let callback;
>   Object.defineProperty(Array.prototype, 'reduce', {
>     value: function(cb, ...args) {
>     callback = cb;
>       return arrayReduce.call(this, callback, ...args);
>     }
>   });
> })();
> ```

did this work as well @rodolfojnn

**Comment by jeroenheijmans** [comment]
We've used the smaller version...

```typescript
// TODO: Remove when things are fixed upstream (or in the browser?).
// Workaround for Angular issue: https://github.com/angular/angular/issues/35219
// and underlying Chromium bug:https://bugs.chromium.org/p/chromium/issues/detail?id=1049982
(function () {
    const arrayReduce = Array.prototype.reduce;
    let callback;
    Object.defineProperty(Array.prototype, 'reduce', {
        value: function (cb, ...args) {
            callback = cb;
            return arrayReduce.call(this, callback, ...args);
        }
    });
})();
```

...and **included it in `polyfills.ts` so that it works in both `.spec.ts` tests and in the browser. (Whereas `main.ts` didn't fix things in specs for us.)

**Comment by brunoesperanca** [comment]
> We've used the smaller version...
> 
> ```ts
> // TODO: Remove when things are fixed upstream (or in the browser?).
> // Workaround for Angular issue: https://github.com/angular/angular/issues/35219
> // and underlying Chromium bug:https://bugs.chromium.org/p/chromium/issues/detail?id=1049982
> (function () {
>     const arrayReduce = Array.prototype.reduce;
>     let callback;
>     Object.defineProperty(Array.prototype, 'reduce', {
>         value: function (cb, ...args) {
>             callback = cb;
>             return arrayReduce.call(this, callback, ...args);
>         }
>     });
> })();
> ```
> 
> ...and **included it in `polyfills.ts`** so that it works in both `.spec.ts` tests and in the browser. (Whereas `main.ts` didn't fix things in specs for us.)

Same answer as @rodolfojnn

**Comment by Nikitikitavi** [comment]
Have same issue on my Angular8 app.

After including this to `main.ts` or to `polyfills.ts`

> // TODO: Remove when things are fixed upstream (or in the browser?).
// Workaround for Angular issue: https://github.com/angular/angular/issues/35219
// and underlying Chromium bug:https://bugs.chromium.org/p/chromium/issues/detail?id=1049982
(function () {
    const arrayReduce = Array.prototype.reduce;
    let callback;
    Object.defineProperty(Array.prototype, 'reduce', {
        value: function (cb, ...args) {
            callback = cb;
            return arrayReduce.call(this, callback, ...args);
        }
    });
})();

it fixes problem locally.  But I still have it in prod build( 
Can anyone advice what should be done to prevent it in prod?

**Comment by jeroenheijmans** [comment]
@Nikitikitavi That should fix it in production too, at least it did for us, and given the general chatter around the issue it did so too for others I believe. Are you sure it's landing on your prod environment properly?

**Comment by jeroenheijmans** [comment]
Also note that **the Chromium team made this "priority 0"** in [the abovementiond Chromium bug 1049982](https://bugs.chromium.org/p/chromium/issues/detail?id=1049982). As I write this it seems the fixes have landed in Chrome Canary already, and if I understand that thread correctly they're also **aiming to patch Chrome 80**.

So the Angular team might not need to do anything (except for perhaps leaving this issue open for visibility, until the Chromium patch has landed properly in Chrome and Edge)...

**Comment by Nikitikitavi** [comment]
> @Nikitikitavi That should fix it in production too, at least it did for us, and given the general chatter around the issue it did so too for others I believe. Are you sure it's landing on your prod environment properly?

Yeah, I even found this code in my main-es2015.hash.js bundle file

**Comment by mix5003** [comment]
@Nikitikitavi i think user still use cached version or use version that before patched becuase browser already loaded before you deploy new version. so you need to find a way to make user refresh that page

**Comment by cexbrayat** [comment]
https://github.com/angular/angular/pull/35349 landed, so we'll have a new Angular patch version that we can use that does not rely on `Array.reduce` (while we are waitin for the next Chrome version that should fix the underlying issue).

**Comment by florentcm** [comment]
A new chrome update, version 80.0.3987.106, seems to solve the issue.

**Comment by cexbrayat** [comment]
Closing, as v9.0.1 includes a fix, and the latest Chrome release does not have the underlying issue anymore.

**Comment by TheoLechemia** [comment]
Is a patch is planned on Angular 7.X version ?

**Comment by SamVerschueren** [comment]
> Is a patch is planned on Angular 7.X version ?

No, it will not be fixed in earlier versions https://github.com/angular/angular/pull/35349#issuecomment-585916367

**Comment by mlc-mlapis** [comment]
@TheoLechemia Since Chrome 80.0.3987.106 the bug has been eliminated.
