### ISSUE TITLE
Angular 9 migration :Error Cannot assign value "undefined" to template variable "confirm". Template variables are read-only. compiler.umd.js

### ISSUE THREAD

**Issue by pyrrhicman** [angular/angular#35218]
Hi,  i tried to migrate but after fixing all of errors and removing and reinstalling node_modules folder still I'm getting this error which i have no idea what to do.

ERROR in Error: Cannot assign value "undefined" to template variable "confirm". Template variables are read-only.
at _AstToIrVisitor.visitPropertyWrite (--/hpk-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:8617:31)
at PropertyWrite.visit (--/hpk-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:7459:28)
at convertActionBinding (--/hpk-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:8224:49)
at prepareEventListenerParameters (--/hpk-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:16861:27)
at Object.params (--/hpk-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:17952:24)
at --/hpk-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:17725:94
at Array.map (<anonymous>)
at --//hpk-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:17725:60
at--/hpk-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:17014:87
at Array.map (<anonymous>)
 at TemplateDefinitionBuilder.buildTemplateFunction (--/hpk-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:17014:60)
at --/hpk-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:17558:60
at --/hpk-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:16992:81
at Array.forEach (<anonymous>)
at TemplateDefinitionBuilder.buildTemplateFunction (--/hpk-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:16992:37)
at --/hpk-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:17558:60

Angular Live Development Server is listening on localhost:8443, open your browser on https://localhost:8443/ **
 angular.json

> {
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "hpk": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {
        "@schematics/angular:component": {
          "styleext": "scss"
        }
      },
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "aot": true,
            "outputPath": "dist/hpk",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets",
              "src/ngsw-worker.js",
              "src/manifest.webmanifest"
            ],
            "styles": [
              {
                "input": "node_modules/@angular/material/prebuilt-themes/indigo-pink.css"
              },
              "src/app/_global-stylesheets/full-calendar.scss",
              "src/app/_global-stylesheets/material_theme.scss",
              "src/app/_global-stylesheets/flex.scss",
              "src/app/_global-stylesheets/material-config.scss",
              "src/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "serviceWorker": true,
              "ngswConfigPath": "ngsw-config.json"
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "hpk:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "hpk:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "hpk:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              {
                "input": "node_modules/@angular/material/prebuilt-themes/indigo-pink.css"
              },
              "src/app/_global-stylesheets/full-calendar.scss",
              "src/app/_global-stylesheets/material_theme.scss",
              "src/app/_global-stylesheets/flex.scss",
              "src/app/_global-stylesheets/material-config.scss",
              "src/styles.scss"
            ],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets",
              "src/manifest.webmanifest"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "hpk-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "hpk:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "hpk:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "hpk"
}

My tsconfig.ts

> {
  "compileOnSave": false,
  "compilerOptions": {
    "module": "esnext",
    "paths": {
      "core-js/es7/reflect": [
        "node_modules/core-js/proposals/reflect-metadata"
      ]
    },
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es6",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}

My package.json

>   "dependencies": {
    "@angular-devkit/schematics": "^9.0.1",
    "@angular/animations": "^9.0.0",
    "@angular/cdk": "^9.0.0",
    "@angular/common": "^9.0.0",
    "@angular/compiler": "^9.0.0",
    "@angular/core": "^9.0.0",
    "@angular/forms": "^9.0.0",
    "@angular/material": "^9.0.0",
    "@angular/platform-browser": "^9.0.0",
    "@angular/platform-browser-dynamic": "^9.0.0",
    "@angular/router": "^9.0.0",
    "@angular/service-worker": "^9.0.0",
    "@fullcalendar/core": "^4.3.1",
    "@fullcalendar/daygrid": "^4.3.0",
    "@fullcalendar/interaction": "^4.3.0",
    "@schematics/angular": "^9.0.1",
    "@uiowa/digit-only": "^1.3.0",
    "bson-objectid": "^1.2.4",
    "chart.js": "^2.9.3",
    "core-js": "^3.6.4",
    "date-fns": "^2.9.0",
    "hammerjs": "^2.0.8",
    "mapbox-gl": "^1.7.0",
    "ngx-cookie-service": "^2.3.0",
    "ngx-image-cropper": "^2.1.2",
    "ngx-mapbox-gl": "^4.3.0",
    "ngx-material-timepicker": "^5.3.0",
    "rxjs": "^6.5.4",
    "rxjs-compat": "^6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.1",
    "@angular/cli": "^9.0.1",
    "@angular/compiler-cli": "^9.0.0",
    "@angular/language-service": "^9.0.0",
    "@types/chart.js": "^2.9.11",
    "@types/jasmine": "^3.5.2",
    "@types/jasminewd2": "^2.0.8",
    "@types/mapbox-gl": "^1.6.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "^3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "^3.1.0",
    "karma-coverage-istanbul-reporter": "^2.1.1",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.5.1",
    "prettier": "^1.19.1",
    "protractor": "^5.4.3",
    "ts-node": "^8.6.2",
    "tslint": "^5.20.1",
    "typescript": "^3.7.5"
  }

**Comment by gultyaev** [comment]
Most likely you've got a template variable same as component prop and this causes an error

**Comment by pyrrhicman** [comment]
> Most likely you've got a template variable same as component prop and this causes an error

Thank you. It wasn't saying that it's from my code  😄 that's why i got confused.
But I found the problem as you said and fixed it.
seems no more template variables.
i was using *ngIf="true;let confirm=true" and i used this confirm variable in element. but now i transferred them all to typescript file
