### ISSUE TITLE
Angular PWA falls out of package.json after cli update to Angular 9

### ISSUE THREAD

**Issue by simon-sharp** [angular/angular#35220]
# 📚 Docs or angular.io bug report

### Description

First of all thank you very much for Angular 9. You have done great work.
I have immediately installed Angular 9 by running "ng update @angular/cli" and this has transformed the application correctly into a running application with no issues.

On close inspection of the package.json I have seen that @angular/pwa has been removed.

The line that was removed was

`"@angular/pwa": "^0.12.4",`

I have not seen anything in the documentation that indicates a fundamental change in the way PWA should be set up. So the question is if that is a bug in the update process or the step is correct and the PWA functionality has moved to another place. Could you please make a short clarification on this matter?

I also have reverted the update and ran the update again. The deletion was not accidental from my side.

Other files like ngsw-config.json or the manifest.json are not touched

## 🔬 Minimal Reproduction
Install an Angular 8 app. Install @angular/pwa and update to Angular 9. I guess.

**Comment by alan-agius4** [comment]
Hi @simon-sharp, this is expected because `@angular/pwa` is only needed one time to scaffold the PWA.

Since version 9 when running `ng add @angular/pwa` the PWA package will be installed temporary and will no longer be added as a dependency.
