### ISSUE TITLE
Length, minLength, maxLength not working in Form/Validators 

### ISSUE THREAD

**Issue by EndUserR** [angular/angular#35222]
phone: ['', [Validators.required, Validators.minLength(10)]]
in this kind of uses that inbuilt Validators are not working.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
