### ISSUE TITLE
Info needed regarding size of Hello world Angular app

### ISSUE THREAD

**Issue by goodmite** [angular/angular#35234]
First of all, happy to see v9 and thanks for the hard work you guys have put into v9 and into Ivy.

In 2018 there was a lot of talk about reducing size of the hello world angular App. As of v7 it was 120kb Gzip and but it was said that in future versions it would be cut down a lot. Kara gave a Google IO talk and said that future version will have Hello world size around 2.7Kb gzipped ([Link](https://youtu.be/jnp_ny4SOQE?t=2264), pls see 37:53 mark). Rob had a [Github repo](https://github.com/robwormald/ivy-code-size) of size < 4kb. I remember that being said in many conferences as well and celebrating "cake size" of <10kb. However lately, I don't see anyone in the community talking about it. V9 sizes are around 60kb gzipped for main.js. This has led to some confusion for me and other devs.

My question is: **are we still pursuing the goal of hello world being 10kb gzipped ( or 2.7kb gzipped)?**
Can we expect that in future versions?

**Comment by StephenFluin** [comment]
We have an experimental API called `renderComponent` that is about 16KB. https://github.com/angular/angular/blob/master/integration/_payload-limits.json#L11

`renderComponent` has major backward incompatible changes for existing apps that we don't have automated migrations. We're working to continue making Angular smaller using what we have enabled with Ivy. v9 is just the beginning.
