### ISSUE TITLE
Angular 9 with fullTemplateTypeCheck and strictTemplates enabled: Property "foo" does not exist on "Type"

### ISSUE THREAD

**Issue by cesco69** [angular/angular#35236]
# 🐞 bug report

## 🔬 Minimal Reproduction

1. enable  `fullTemplateTypeCheck` and `strictTemplates` in `tsconfig.json` (see https://angular.io/guide/template-typecheck)

2. create a simple component

```ts
import { Component } from '@angular/core';

interface ItemBaseType {
   foo: boolean;
}

interface ItemType extends ItemBaseType {
   bar: boolean;
}

@Component({
  selector: 'ac-foo',
  template: `<div *ngIf="item.bar">Hello</div>`,
})
export class FooComponent {
   public item: ItemType;
}

```

3.  add the component in the app component

```html
<ac-foo></ac-foo>
```

4. run 

```shell
ng serve
```

The console show the error

> Error occurs in the template of component FooComponent.
> Property 'bar' does not exist on type 'ItemBaseType'
>     
> <div *ngIf="item.bar">Hello</div>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.1
Node: 12.15.0
OS: win32 x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.1
@angular-devkit/build-angular      0.900.1
@angular-devkit/build-optimizer    0.900.1
@angular-devkit/build-webpack      0.900.1
@angular-devkit/core               8.3.8
@angular-devkit/schematics         8.3.8
@angular/cli                       9.0.1
@angular/material-moment-adapter   8.2.3
@ngtools/webpack                   9.0.1
@schematics/angular                8.3.8
@schematics/update                 0.900.1
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2

</code></pre>

**Comment by JoostK** [comment]
I can't quite reproduce in a compiler testcase, using the sample you provided plus an NgModule:

```ts
import { CommonModule } from '@angular/common';
import { Component, NgModule } from '@angular/core';

interface ItemBaseType {
   foo: boolean;
}

interface ItemType extends ItemBaseType {
   bar: boolean;
}

@Component({
  selector: 'ac-foo',
  template: `<div *ngIf="item.bar">Hello</div>`,
})
export class FooComponent {
   public item: ItemType;
}

@NgModule({
  declarations: [FooComponent],
  imports: [CommonModule],
})
export class Module {}
```

This results in zero errors reported.

**Comment by tomamatics** [comment]
got this one when trying to reproduce

> Cannot read property 'bar' of undefined

You may use a null conditional operator in your ngIf declaration
`<div *ngIf="item?.bar">Hello</div> `

**Comment by alxhub** [comment]
Closing as no reproduction was provided.
