### ISSUE TITLE
defaultEncapsulation not working in Ivy

### ISSUE THREAD

**Issue by xuxicheta** [angular/angular#35230]
Angular 9.0.0
### Description
`defaultEncapsulation` option in `platformBrowserDynamic().bootstrapModule` don't work.
## 🔬 Minimal Reproduction
Just minimal CLI project with 
`platformBrowserDynamic().bootstrapModule(AppModule, { defaultEncapsulation: ViewEncapsulation.None })
  .catch(err => console.error(err));`

## 🌍  Your Environment
<pre>
Angular CLI: 9.0.1
Node: 13.7.0
OS: linux x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</pre>

**Comment by pkozlowski-opensource** [comment]
@xuxicheta could you provide a bit more info before we investigate? When you say "don't work", what do you mean, exactly:
* errors are thrown during compilation / runtime? 
* specified encapsulation is not applied? 
* something else? 

Also, what is the exact CLI command that leads to troubles?

**Comment by xuxicheta** [comment]
@pkozlowski-opensource, Sorry for unclearance.
I set `defaultEncapsulation: ViewEncapsulation.None` 
and have `<app-root _nghost-ruf-c11="" ng-version="9.0.0"> ... </app-root>` like as when Emulated encapsulation set on.
ViewEncapsulation.ShadowDom also have no effect. 
So _specified encapsulation is not applied_

No errors
It appears in builded project and in served by Angular CLI both.

**Comment by gcirone** [comment]
With AOT it never worked the `defaultEncapsulation` if I remember good :)

**Comment by alxhub** [comment]
This doesn't need a reproduction, I know off the top of my head that it doesn't work anymore. This is due to the JIT compilation via decorators in Ivy, which no longer have any dependency on `platformBrowserDynamic.bootstrapModule()`.

There may be some fix we can put into place here.

**Comment by nikoudel** [comment]
Is this supposed to work in 9.1.0? It doesn't seem to be the case.

```
$ ng --version

Angular CLI: 9.1.0
Node: 13.11.0
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
```

With this code in main.ts
```
...
platformBrowserDynamic().bootstrapModule(AppModule, {
  defaultEncapsulation: ViewEncapsulation.ShadowDom
})
...
```
And commented-out option in a component:
```
@Component({
    //encapsulation: ViewEncapsulation.ShadowDom,
  selector: 'my-popup',
```
the styles look like this:

![image](https://user-images.githubusercontent.com/1636683/78174438-ec1a0780-7461-11ea-92b6-f1c61be0c3a4.png)

but when uncommenting the `encapsulation: ViewEncapsulation.ShadowDom` component option, it looks as expected:

![image](https://user-images.githubusercontent.com/1636683/78174657-44e9a000-7462-11ea-8ce0-5ccc96f1d270.png)

**Comment by JoostK** [comment]
@nikoudel Can you share a repro? According to CI tests it is working. It is included in 9.1.0 per e342ffd855ffeb8af7067b42307ffa320d82177e so yes, it should work.

**Comment by nikoudel** [comment]
@JoostK please see the last commit [here](https://bitbucket.org/nikoudel/ng-test-one/commits/).

**Comment by JoostK** [comment]
@nikoudel Thanks. I realized it is because the app gets built in AOT mode by default, in which case any options passed to `bootstrapModule` cannot be taken into account. There's #12251 as a feature request to add support for AOT compilations.

If I disable AOT (search for `"aot"` in the `angular.json` file) it works, confirming that the options are properly taken into account in JIT mode.

**Comment by xuxicheta** [comment]
@JoostK
So problem is not solved, but issue is closed.
Maybe point about AOT must be mentioned in documentation?
