### ISSUE TITLE
Inconsistencies in API names

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#3524]
- interfaces should be `FooBarThing Interface` not `IFooBarThing Interface` (http is inconsistent)
- variables should start with a capital letter `Attribute Var` (http is inconsistent, test is inconsistent)
- variable should not be in allcaps (?) eg `IS_DARTIUM` and `ELEMENT_PROBE_CONFIG` in test may be wrong?
- constants should start with a lowercase letter e.g. `foo Const`
- what should we do about functions that are exported as var, and thus appear as `Component Var: Component factory function`?
- should functions start with uppercase or lowercase? (test is inconsistent.)
- functions should begin with an initial lowercase letter. Should they innercap? (test is inconsistent)

See list of classes as-of alpha-33: https://docs.google.com/document/d/1v5an5CkD88yJkfqbRaok3ItjIgRV97KdebiA5v_bbB8/edit#

**Comment by naomiblack** [comment]
@mhevery I'm marking as P1 because these are renames and potentially breaking changes. Can we come up with consistent guidelines and make the changes in alpha-35 do you think?

**Comment by mhevery** [comment]
- Interface should not start with `I`
- var / const / functions are complicated
  - normal  instances / vars / functions should start with lower case letters
  - Type should start with upper case letter. So `var Component = ..` is OK
  - const should be all uppercase `const PI = 3.1414`

So far you are describing kind of the opposite of what it should be and all your examples are actually correct.

**Comment by martinmcwhorter** [comment]
+1 For @mhevery's suggestion that vars and functions start with lower case letter. They should be camelCase names. 

This is consistent with idiomatic JavaScript and TypeScript.

**Comment by jessegood** [comment]
I'm just an outsider, by surely https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines would be a good guideline to follow.

**Comment by naomiblack** [comment]
Thanks @jessegood. We follow most of these except the one about not using _ for private (which we do for consistency with Dart). We also want all const to be UPPERCASE_WITH_UNDERSCORES

**Comment by mhevery** [comment]
Cleanup PR: https://github.com/angular/angular/pull/3581

**Comment by mhevery** [comment]
I think this is resolved now. Should we close?

**Comment by mhevery** [comment]
Closing, Please reopen if you think we still have missing renames.
