### ISSUE TITLE
CSS styles not being applied when using an Entry Component

### ISSUE THREAD

**Issue by mdmoura** [angular/angular#35243]
I have an HTML/CSS Modal working as expected ([StackBlitz example](https://stackblitz.com/edit/modal-angular-flex-2)).

The Modal basic markup is:

```
<div class="cover">
  <div class="modal">
    <div class="head">head</div>
    <div class="body">
      <div class="view">body</div>
    </div>
    <div class="foot">foot></div>
  </div>
</div>
```

I created a Modal service that opens a Modal with a given component being its body content:

When using the Modal Service a `<content>` tag is added:

```
<div class="cover">
  <div class="modal">
    <content>
      <div class="head">head</div>
      <div class="body">
        <div class="view">body</div>
      </div>
      <div class="foot">foot></div>
    </content>
  </div>
</div>
```

This breaks the Modal and it seems the `.cover` and `.modal` styles are not being added.

The consequence is that the Modal now does not resize vertically ([StackBlitz example](https://stackblitz.com/edit/modal-angular-flex-2)).

Can this be solved? Is it a bug or an Angular's limitation?

**Angular Version:**
Angular CLI: 8.3.17
Node: 13.5.0
OS: darwin x64
Angular: 8.2.13

**Comment by pkozlowski-opensource** [comment]
> When using the Modal Service a <content> tag is added:

Yes, this is expected. In Angular every component unrolls its content (template) into a its host element.  In case of entry component a host element is being created based on the component's selector.

Sounds like you need to adjust your CSS accordingly?

**Comment by mdmoura** [comment]
>> Sounds like you need to adjust your CSS accordingly?

How? Can you, please, clarify?

I was reading and trying ::host and ::ng-deep. 

It does something but I wasn't able to solve it completely.

Note that the `<content>` tag is being applied because I am passing that component to modal.

But I could pass another component which would have another tag.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
