### ISSUE TITLE
Official link error

### ISSUE THREAD

**Issue by ARTWINPRO** [angular/angular#35256]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

Hey guys - please do some think...

![image](https://user-images.githubusercontent.com/16427316/74087083-d4418b00-4a91-11ea-84fe-5ee9d7234e77.png)

**Comment by JoostK** [comment]
The ngcc compiler is not run on ng-run.com, so the external `ng-json-view` library will not be compiled for Ivy. Looking at the sources of that library it does follow a proper distribution structure, so could you try again on a local machine instead of ng-run? Thanks!

**Comment by lazarljubenovic** [comment]
> Hey guys - please do some think...

You've gotta be kiddnig. You skipped the whole issue template, completely ignored it, left everything blank, pasted a screenshot and told us guys to _think_?
