### ISSUE TITLE
better visualization of errors origin compiling templates

### ISSUE THREAD

**Issue by lucamorelli** [angular/angular#35258]
I'm facing a problem migrating a running application from angular 8 to 9.
I upgraded using ng commands, updated al the packages, but when I try to run the application I obtain the error message explained in this stackoverflow question

https://stackoverflow.com/questions/60128458/strange-problem-migrating-angular-8-app-to-9

I suppose the error is some component, but the compiler output is not of help at all troubleshooting the problem that is locking my migration

**Comment by JoostK** [comment]
Please see https://github.com/angular/angular/issues/35139#issuecomment-581850479. The location of this error is uncovered when enabling template type checking, but when that's disabled it will not be detected in a nice way, instead resulting in a compiler crash.

**Comment by lucamorelli** [comment]
thanks.
  I was using an old project and the angularCompilerOptions was not present. adding it I was able to find the problem.
  It's in the template of an instance of the @swimlane/ngx-datatable component, where I add this

```
        <ng-template ngx-datatable-cell-template let-value="value" #customValue  let-rowIndex="rowIndex"let-row="row" >
          <input
            autofocus
            (change)="updateValue($event, rowIndex)"
            type="number"
            [(ngModel)]="value"
          />
        </ng-template>
        <ng-template ngx-datatable-header-template>
          rma          
        </ng-template>
      </ngx-datatable-column> -->

```

I don't  understand why is telling me this error message

>  Cannot assign value "$event" to template variable "value". Template variables are read-only.

but at least commenting it now I can compile the app.

**Comment by mlc-mlapis** [comment]
@lucamorelli The problem with it is related to the `two-ways` logic of `[(ngModel)]` and the declaration of `value` template variable, that has only `one-way` logic.

![image](https://user-images.githubusercontent.com/5693835/74089775-f85a9780-4aa4-11ea-992f-529f80cfdb88.png)

**Comment by lucamorelli** [comment]
thanks, changing it solved the problem
