### ISSUE TITLE
Angular web app rejected in mobile navigators

### ISSUE THREAD

**Issue by rudyhadoux** [angular/angular#35257]
Hi,

I do not understand why my responsive Angular web apps are rejected in mobile navigators.
The websites are hosted by AWS Amplify Console.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
