### ISSUE TITLE
Optional routeparams

### ISSUE THREAD

**Issue by sumigoma** [angular/angular#3525]
Angular 1.x router had support for optional route params with /:id? syntax. Will there be similar functionality in the new router?

**Comment by mhevery** [comment]
@btford Can you comment and triage appropriately?

**Comment by avoivo** [comment]
unofficial workaround in dart 

config router like this
'''
@RouteConfig(const [
const Route(path: '/customer/:id', component: CustomerComponent, as : 'customer'),
  const Route(path: '/customer', component: CustomerComponent, as : 'newcustomer')
])
'''

and then inject the RouteParams in the components and check if value is null

'''
class CustomerComponent{
  RouteParams _routeParams;
  bool _isNew = false;

  CustomerComponent(this._routeParams){

    String id;

    if(_routeParams.params.containsKey('id'))
        id = _routeParams.get('id');


  }

}

'''

**Comment by sumigoma** [comment]
Yep, this is what I'm doing now, though eventual support would be nice to have!

**Comment by btford** [comment]
I'm going to mark this as "nice to have" since it's essentially just syntax sugar for two different configs that point to the same component. It's a reasonable feature, but not likely to happen until higher priority issues have been addressed.

**Comment by e-oz** [comment]
So it means if I need to put 3 variables to URL (for example: position of pagination, opened tab, search query), I need to declare 4 similar routes? Well... Can't say it's DRY enough. Please reconsider priority of this task.

**Comment by e-oz** [comment]
There is conflict already with just 2 optional arguments:
```
  {path: '/leads/', component: LeadsCmp, as: 'Leads'},
  {path: '/leads/:page', component: LeadsCmp, as: 'LeadsPage'},
  {path: '/leads/:tab', component: LeadsCmp, as: 'LeadsTab'}, // Exception: Configuration '/leads/:tab' conflicts with existing route '/leads/:page'
  {path: '/leads/:page/:tab', component: LeadsCmp, as: 'LeadsPageTab'},
```
so there is no way to compose URL without mentioning "page" argument at all, if I want to point only tab in URL...

AngularJS UI-Router has very handy syntax for optional arguments (aka [query parameters](https://github.com/angular-ui/ui-router/wiki/URL-Routing#query-parameters)) - please think about if ng2 router could use this advantage too (or something similar).

**Comment by e-oz** [comment]
For future readers: as a temporary (I hope ;)) workaround I use this code to get and set URL params:
https://gist.github.com/e-oz/5a95f50336e68623f9e0

**Comment by johnsteele** [comment]
Is it possible to pass a route an arbitrary object?

**Comment by mdudek** [comment]
I found that same route data is passed to both defined routes in this case:

{path: '/login', component: ViewLogin, name: 'Login', data: {param1: true} },
{path: '/login/:force', component: ViewLogin, name: 'LoginForce'},

and no data are passed for following configuration:

{path: '/login', component: ViewLogin, name: 'Login' },
{path: '/login/:force', component: ViewLogin, name: 'LoginForce', data: {param1: true}},

It seems that router gets route data from first definition for all routes. Tested on Angular2.beta.0

**Comment by cghislai** [comment]
You can already provide route parameters in your links
```
[routerLink]="['MyRoute',  {page: 1, length:10}]"
```
If these parameters are not present in the route declaration, they will be added as query parameters, which seems is what you are looking for.

**Comment by mdudek** [comment]
Route parameters works fine, but this issue is related to route data. I want to pass data to component by route configuration.

**Comment by cghislai** [comment]
Sorry it was in reply to @e-oz who reopened this issue, which is related to route parameters, not route data.

**Comment by gustavolira** [comment]
Hi,
Any news about this feature?

**Comment by monfa-red** [comment]
This works for me as of @angular/router v3 beta-2
export const LeaguesRoutes: RouterConfig = [
  {
    path: 'page/:id',    
    children: [
      { path: '', component: LeaguesHeaderComponent, outlet: 'header' }, // header outlet!
      { path: 'home', component: LeagueHomeComponent }, // /page/:id/home
      {
        path: 'list',
        children: [
          { path: '**', component: LeaguePlayersComponent } // /page/:id/list & /page/:id/list/x/y/...
        ]
      }
    ]
  }
];

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

Handled by the new router.
