### ISSUE TITLE
ng new when run gives "Uncaught TypeError: Cannot read property 'ApplicationRef' of undefined in console

### ISSUE THREAD

**Issue by AngularianUK** [angular/angular#35250]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/cire

### Is this a regression?

 Yes, the previous version in which this bug was not present was: v8

### Description

When you create a new application using the information in the documentation the starter page is automatically generated and although it appears to work the console log shows an Uncaught TypeError.  The error should not occur (clutters up the console) and previous versions of Angular did not display this error

## 🔬 Minimal Reproduction

Just create a new project with ng new and then run it in Chrome

## 🔥 Exception or Error
<pre><code>

Angular is running in the development mode. Call enableProdMode() to enable the production mode.
VM13 polyfills.js:185 Uncaught TypeError: Cannot read property 'ApplicationRef' of undefined
    at Object.t.toggleTracing (VM41 tracer.js:1)
    at Object.toggle (VM41 tracer.js:1)
    at VM41 tracer.js:1
    at ZoneDelegate.invokeTask (VM13 polyfills.js:413)
    at Zone.runTask (VM13 polyfills.js:181)
    at ZoneTask.invokeTask [as invoke] (VM13 polyfills.js:494)
    at invokeTask (VM13 polyfills.js:1609)
    at globalZoneAwareCallback (VM13 polyfills.js:1646)
VM15 vendor.js:81284 [WDS] Live Reloading enabled.
Navigated to http://localhost:4200/

</code></pre>

## 🌍  Your Environment
Windows 10
**Angular Version:**
<pre><code>

     _                      _                 ___
    / \   _ __   __ _ _   _| | __ _ _ __     / __
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |  
  / ___ \| | | | (_| | |_| | | (_| | |      | |__
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \___
                |___/                            
                                                 
                                                 
Angular CLI: 9.0.1                               
Node: 12.15.0                                    
OS: win32 x64                                    
                                                 
Angular: 9.0.0                                   
... animations, common, compiler, compiler-cli, c
... language-service, platform-browser, platform-
... router                                       
Ivy Workspace: Yes                               
                                                 
Package                           Version        
-------------------------------------------------
@angular-devkit/architect         0.900.1        
@angular-devkit/build-angular     0.900.1        
@angular-devkit/build-optimizer   0.900.1        
@angular-devkit/build-webpack     0.900.1        
@angular-devkit/core              9.0.1          
@angular-devkit/schematics        9.0.1          
@angular/cli                      9.0.1          
@ngtools/webpack                  9.0.1          
@schematics/angular               9.0.1          
@schematics/update                0.900.1        
rxjs                              6.5.4          
typescript                        3.7.5          
webpack                           4.41.2         
</code></pre>

**Anything else relevant?**

Firefox does not display the error, Chrome does - all versions I've tried. Currently v80.0.3987.87 (Official Build)

**Comment by alexzuza** [comment]
The Google Chrome extension which you're using doesn't support Angular 9 version

**Comment by petebacondarwin** [comment]
@alexzuza - how do you tell that @AngularianUK is using a Chrome extension?

**Comment by alexzuza** [comment]
@petebacondarwin That's my extension

**Comment by petebacondarwin** [comment]
👍 thanks for the info @alexzuza !

Closing as it appears that this is not an issue with the Angular framework.
