### ISSUE TITLE
Dynamically created component with dependency from lazy-loaded module throw an error NullInjectorError: R3InjectorError

### ISSUE THREAD

**Issue by KhaydarshinAleksandr** [angular/angular#35268]
# 🐞 bug report

### Description
Dynamically created component with dependency of service provided in lazy-loaded module throws an error. If declare `provideIn: 'root'` in that service, then all works fine, but i don't be sure, that it necessary.

## 🔬 Minimal Reproduction
**steps**: 

1. Create component that will be dynamically creating some other components through resolveComponentFactory and createComponent. (DynamicComponent in my repo). Declare this in AppModule.
2. Create lazy-load module, provide to them some service (LazyService in my repo) and declare component, that will be use provided service (TestComponent).
3. Try to create component dynamically in lazy-loaded component.

**repo**:  https://github.com/KhaydarshinAleksandr/lazy-load-providers

## 🔥 Exception or Error
<pre><code>
core.js:5828 ERROR NullInjectorError: R3InjectorError(AppModule)[LazyService -> LazyService -> LazyService]: 
  NullInjectorError: No provider for LazyService!
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.1
Node: 12.4.0
OS: darwin x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by tieppt** [comment]
I'm suppose you're provide `LazyService` only in `LazyModule`. Therefore, `DynamicComponentsModule` do not have anything called `LazyService`.
And because `DynamicComponentsService` injected `ComponentFactoryResolver`, this is belong to `DynamicComponentsModule` then`TestComponent` will become apart of `DynamicComponentsModule`.

So you can passing a `NgModuleRef` with your `LazyService`, then everything will work as expected.

```ts
@Injectable()
export class LazyService {
  test() {
    console.log('Service from lazy module successfully injected to dynamically created component');
  }
}
```
```ts
@Injectable()
export class DynamicComponentsService {
  instance: DynamicComponentsComponent;
  componentRef: ComponentRef<DynamicComponentsComponent>;

  private rootEl: ViewContainerRef;

  constructor(private cfr: ComponentFactoryResolver, private appRef: ApplicationRef) { }

  create(component: Type<any>, ngModuleRef?: NgModuleRef<any>) {
    this.rootEl = this.appRef.components[0].instance.viewContainerRef;
    const cfr = ngModuleRef ? ngModuleRef.componentFactoryResolver : this.cfr;

    const componentFactory = cfr.resolveComponentFactory(DynamicComponentsComponent);
    this.componentRef = this.rootEl.createComponent(componentFactory);

    this.componentRef.hostView.detach();

    this.instance = this.componentRef.instance as DynamicComponentsComponent;
    this.instance.component = component;

    this.componentRef.hostView.reattach();
  }
}
```
```ts
@Component({
  template: `
    <div>
      <button (click)="create()">Create component</button>
    </div>
  `,
})
export class LazyComponent {
  constructor(private dynamicComponentsService: DynamicComponentsService, private ngModuleRef: NgModuleRef<LazyModule>) {}

  create() {
    this.dynamicComponentsService.create(TestComponent, this.ngModuleRef);
  }
}
```

**Comment by KhaydarshinAleksandr** [comment]
@tieppt, thanks for your answer, it helped me understand my problem. But instead passing a `NgModuleRef<LazyModule>` i can pass `componentFactoryResolver`, that looks more clear.

Can i find necessary resolver inside `DynamicComponentsService` instead passing it?

**Comment by tieppt** [comment]
@KhaydarshinAleksandr I think no, only child injector know their parent. From your code: `DynamicComponentsModule` is merge into AppModule. It's know nothing about `LazyModule`.
