### ISSUE TITLE
Mat select in lazy loaded component throws a no provider error

### ISSUE THREAD

**Issue by RogierdeRuijter** [angular/angular#35264]
# 🐞 bug report

### Affected Package
@angular/material and maybe more

### Is this a regression?

Not sure

### Description

Importing MatSelectModule into a lazy-loaded component created with the component factory resolver throws an error.

```
ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[InjectionToken mat-select-scroll-strategy -> InjectionToken mat-select-scroll-strategy -> InjectionToken mat-select-scroll-strategy]: 
  NullInjectorError: No provider for InjectionToken mat-select-scroll-strategy!
```

## 🔬 Minimal Reproduction
**Steps:**
- Create component A
- Create component B
- Lazy load component B with the component resolver factory into component A
- Import MatSelectModule in component B
- Use `<mat-select>` in component B

**Result**
Error: No provider for InjectionToken mat-select-scroll-strategy! 

**Repo**
https://github.com/RogierdeRuijter/lazy-load-component-mat-select

## 🌍  Your Environment

**Angular Version:**
Angular 9.0.0

**Comment by tieppt** [comment]
Hi, because you're lazy load component (LazyComponent) with this solution:
```ts
this.mobileContentContainer.createComponent(mobileContentFactory, null, this.injector);
```
Therefore, the component became a part of `AppModule`, but the NgModule don't have any provider for `MAT_SELECT_SCROLL_STRATEGY`.

To fix the problem, I can provide 2 solutions:
1. Import `MatSelectModule` into `AppModule`.
2. export `NoNameNeeded` and compile it with compiler:
```ts
@NgModule({
  declarations: [LazyComponent],
  imports: [
    CommonModule,
    MatSelectModule
  ]
})
export class NoNameNeeded { }
```
```ts
constructor(
  private componentFactoryResolver: ComponentFactoryResolver,
  private injector: Injector,
  private compiler: Compiler
) {}
public async ngOnInit(): Promise<void> {
  const { LazyComponent, NoNameNeeded } = await import('./lazy/lazy/lazy.component');
  const factory = await this.compiler.compileModuleAsync(NoNameNeeded);
  const ref = factory.create(this.injector);

  const mobileContentFactory = this.componentFactoryResolver.resolveComponentFactory(LazyComponent);
  this.mobileContentContainer.createComponent(mobileContentFactory, null, this.injector, [], ref);
}
```

**Comment by RogierdeRuijter** [comment]
He,

Thanks for your response!

I will use the 2nd approach you mentioned.

Cheers
