### ISSUE TITLE
Updates to bazel.angular.io

### ISSUE THREAD

**Issue by SiddAjmera** [angular/angular#35261]
# 📚 Docs or angular.io bug report

### Description

I recently started looking into the ABC Initiative. And I'm really interested in digging deep. :) And so I frequently visit the [ABC Website](https://bazel.angular.io/) Website to check for Tutorials, Videos, Training, etc.

Something that I noticed is that it has been quite some time since the last update to the [site](https://bazel.angular.io/).

I just wanted to know if Is it currently undergoing an update. If not, can someone guide me on how can I start updating it?

I think the landing page is from [here](https://github.com/angular/angular-bazel-example/blob/master/src/index.html)

But the repo is achieved and moved to the [rules_nodejs](https://github.com/bazelbuild/rules_nodejs/tree/master/examples/angular) repository. So just wanted to be sure.

### What's the affected URL?**

https://bazel.angular.io/

**Comment by manekinekko** [comment]
So that page was actually moved to https://github.com/bazelbuild/rules_nodejs/tree/master/examples/angular.

@mgechev @gregmagolan @alexeagle is this marketing page still being deployed?

**Comment by kapunahelewong** [comment]
Thanks for this, @SiddAjmera. Mind if I close this as your PR was merged? It looks resolved. If you still have questions, please feel free to re-open.

**Comment by alexeagle** [comment]
@SiddAjmera it's manually deployed and no I haven't done it in a long time.
