### ISSUE TITLE
ivy: library with services and target 'es5'  is throwing error in runtime

### ISSUE THREAD

**Issue by roopeshreddy** [angular/angular#35269]
# 🐞 bug report

### Is this a regression?

 
Yes, this is working in v8.x.
Yes, this is working in v9.x, if it's target to `es2015` in `tsconfig` and enableIvy:  true

v9.x - target: 'es5', enableIvy: true --> It's not working.
v9.x - target: 'es2015', enableIvy: true --> Working as expected.

### Description

 
Angular Library, with a component depends on a service which that service depends on other service is throwing error if we set target to `es5` in `tsconfig`. Basically it looks like this -

Component 
    | 
Service      
    |
Service     

## Library
https://github.com/roopeshreddy/angular-lib-demo
## App
https://github.com/roopeshreddy/ivy-bug-app
##  Npm link
https://www.npmjs.com/package/ngx-lib-ivy-bug

## 🔥 Exception or Error
The below error shouldn't happen! It should work as normally.
<pre><code>

Uncaught TypeError: Cannot set property ɵfac of function PageSpinnerComponent() {
    } which has only a getter
    at ngx-lib-ivy-bug.js:284
    at Module../node_modules/ngx-lib-ivy-bug/__ivy_ngcc__/fesm5/ngx-lib-ivy-bug.js (ngx-lib-ivy-bug.js:313)
    at __webpack_require__ (bootstrap:79)
    at Module../src/app/app-routing.module.ts (main.js:98)
    at __webpack_require__ (bootstrap:79)
    at Module../src/app/app.module.ts (app.component.ts:9)
    at __webpack_require__ (bootstrap:79)
    at Module../src/main.ts (environment.ts:12)
    at __webpack_require__ (bootstrap:79)
    at Object.0 (main.ts:12)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

ngular CLI: 9.0.1
Node: 10.15.0
OS: darwin x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cdk                      8.2.3
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

NO. I tested in both latest Chrome & Firefox.

**Comment by IgorMinar** [comment]
Can you please help me understand why are you setting the targwt to es5? That will make your library impossible to optimize and serve with the benefits of differential loading.

**Comment by roopeshreddy** [comment]
@IgorMinar  If I didn't set the target to 'es5', then the differential polyfill bundle is not getting generated. We have a requirement to support IE11 browser.

**Comment by roopeshreddy** [comment]
@IgorMinar 

Also, if we run ng build --prod with "aot": true, then 

`
ERROR in node_modules/ngx-lib-ivy-bug/lib/modules/commonutil/commonutil.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

1 export declare class CommonutilModule {
`
Same issue -
[https://github.com/angular/angular/issues/35255](https://github.com/angular/angular/issues/35255)

**Comment by roopeshreddy** [comment]
> Can you please help me understand why are you setting the targwt to es5? That will make your library impossible to optimize and serve with the benefits of differential loading.

Hey @IgorMinar  I was under impression that the differential loading was applied ONLY to ployfills. I didn't realize the browserlist file which helps this differential loading. 

This may be becasue we're uprading the codebase from Angular 6.x and the `ng update` sometimes files, and we ended up manually bumping the versions and proceed.

Now, I've realized that, the differential loading is helping to create `es2015` & `es5` chunks separately based on the browserlist file, it all makes sense with your comment.

Now, my issue boils down to this error -

> Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

I've already referenced the existing issue - #35255 

To give, bit of background here -  We're building enterprise Angular library which contains the App Shell, which is used with in our organization. We've our store for these libraries and consumers are with our organization without pushing to public repository.

This was working fine with Angular v8.x and breaking with v9.x applications. 

**NOTE**: We're still following Angular guidelines of - Building the library with Angular v8.x and disabling Ivy. The consuming application is Angular v9.x and Ivy enabled. If we disable the Ivy, then Angular v9.x is working fine.

I hope this makes sense now!

Thank you for your time.

**Comment by IgorMinar** [comment]
Thanks for the info. We need to rereview this issue.

**Comment by petebacondarwin** [comment]
@roopeshreddy - thanks for the updates. It looks like you no longer need to target ES5 and that your new issue is already being tracked in #35255, so I propose to close this issue and move the discussion to that issue. If you feel there is something further (different from #35255) that needs to be addressed then please post here and I will re-open this issue.
