### ISSUE TITLE
doc links broken for KeyValueChanges

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#3527]
We have doc links to `{@link KeyValueChanges}` but the doc for them (previously in `pipes/keyvalue_changes.ts`) has been removed.

Please update the API docs that mention KeyValueChanges. 

See https://github.com/angular/angular/blob/3cda7128d0a74661511390f4713682973e63b1fc/modules/angular2/src/change_detection/pipes/keyvalue_changes.ts#L13

Marking as P1 because this throws API doc errors in alpha-34.

**Comment by vsavkin** [comment]
Will be fixed by https://github.com/angular/angular/pull/3581

**Comment by vsavkin** [comment]
Fixed by #3581
