### ISSUE TITLE
Add explanation to why a css component budget is added in ng update to v9

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#35272]
# 📚 Docs or angular.io bug report

### Description

The `ng update` command will add this code to the `angular.json` file. People might want to know why.

Here is why ...

- this budget will throw an error if any component has style > 6kb. but it WONT raise an warning  if global styles are huge
-  it will be a “warning” not an “error” cause in this case the budget has not been configured to error out.
- This budget is only checked against individual component styles.
- Filipe says "We just wanted to prevent individual 100k component css" 

```
            {
              type: 'anyComponentStyle',
              maximumWarning: '6kb',
              maximumError: '10kb',
            },
```
https://github.com/angular/angular-cli/blob/9de282ca3209c3c8895dcfc1da36c30e4a05fc67/packages/schematics/angular/application/index.ts#L227-L231

**Comment by kapunahelewong** [comment]
Thank you for this and the info so we can update it correctly, @johnpapa! 🌈

**Comment by wojteko22** [comment]
I noticed that `anyComponentStyle` works only for css styles, warnings and errors don't appear if component has scss styles

**Comment by aikidave** [comment]
Closing as this issue was created 2 releases ago.
