### ISSUE TITLE
After upgrading to Angular 9, ngFor and ngIf are unknown

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#35273]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

1. upgrade a project to angular 9 using the terminal in vs code
1. Open a template with `ngFor` or `ngIf` in VS Code.
1. Notice the errors (red squiggly lines) in the template over an `ngFor`

## 🔥 Exception or Error
<pre><code>
Property binding ngForOf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations".ng(0)
</code></pre>

This goes away if I `ng build` *AND* reload vs code.

**Comment by AndrewKushnir** [comment]
Closing this ticket based on the comment from Andrew above. Please reopen if the problem still exists. Thank you.
