### ISSUE TITLE
Write data into local json file

### ISSUE THREAD

**Issue by manikandanb975121** [angular/angular#35279]
Can any one help,

How to write a data into local json file in angular 8

**Comment by santoshyadav198613** [comment]
Browsers don't have access to file system API. Also you can post such questions on Stackoverflow, as only framework related issues are taken care on GitHub, or feel free to join gitter channel.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
