### ISSUE TITLE
Status update on single component applications?

### ISSUE THREAD

**Issue by alshdavid** [angular/angular#35275]
# 🚀 feature request

A while ago there was a talk hosted by Rob Wormald surrounding the idea of single component applications, where the potential for brining the old beta syntax of providers and imports back to the component decorator was mentioned.

```html
<html>
  <body>
    <app-my-component></app-my-component>
  </body>
</html>
```

```typescript
@Component({
  selector: 'app-my-component',
  imports: [ BrowserModule ],
  declarations: [ BComponent ],
  providers: [ MyService ],
  template: /*html*/`
    <div>Hello World</div>
    <app-b-component></app-b-component>
  `
})
class MyComponent {

}

platformBrowserDynamic()
  .bootstrapComponent(MyComponent)
```

### Description
Including the capability for components to describe their dependencies and be bootstrapped independently of a module.

**Comment by gkalpak** [comment]
Related: https://github.com/angular/angular/issues/35234#issuecomment-583648883

**Comment by pkozlowski-opensource** [comment]
Agree that at this point it is hard to offer more info in addition to https://github.com/angular/angular/issues/35234#issuecomment-583648883
Some of the relevant discussion also happened during the v9 "release party": https://www.youtube.com/watch?v=hnKeNTZp7q0

In short: yes, we want to go more towards "component as the first-class citizen model", got different ideas and APIs sketched but nothing definitive yet. Stay tuned, we are as exited as you about new possibilities opened by ivy :-)
