### ISSUE TITLE
Update the deployment instructions in getting started

### ISSUE THREAD

**Issue by mgechev** [angular/angular#35274]
# 📚 Docs or angular.io bug report

### Description

With the tighter integration of `@angular/fire` with Angular CLI and the `ng deploy` command that we introduced, we can simplify the deployment section in the getting started [guide](https://angular.io/start/deployment#deployment).

### What's the affected URL?**

https://angular.io/start/deployment#deployment

### Expected vs Actual Behavior**

Expected:
```
ng add @angular/fire
ng deploy
```

Skip part of the steps [here](https://angular.io/start/deployment#hosting-an-angular-app-on-firebase).

**Comment by sonukapoor** [comment]
@mgechev / @pkozlowski-opensource  I can help with this.  Please assign the task to myself.
