### ISSUE TITLE
ERROR Error: inject() must be called from an injection context when using inheritance in a library

### ISSUE THREAD

**Issue by sherif-elmetainy** [angular/angular#35277]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?
Yes. Worked in version 8

### Description
In a minimal angular app, with a minimal angular library. The library has a pipe that inherits from an abstract class which also has a constructor that injects a service. 

```typescript
import { Injectable, PipeTransform, Pipe } from '@angular/core';

@Injectable({
    providedIn: 'root',
})
export class SayHelloService {
    public sayHello(name: any): string {
        return `Say ${name}.`;
    }
}

@Injectable()
export abstract class ParentPipe {
    constructor(
        protected readonly sayHelloService: SayHelloService
    ) {

    }
}

@Pipe({
    name: 'sayHello',
})
export class SayHelloPipe extends ParentPipe implements PipeTransform {
    transform(value: any, ...args: any[]) {
        return this.sayHelloService.sayHello(value);
    }
}
```
When I build the library, and try to use the pipe it in the app. I get an "Error: inject() must be called from an injection context" (exception details below).

I tried to move the code from my library, to the main app, same error. Then I tried to add a `@Pipe` dectorator to the ParentPipe class.

```typescript
@Pipe({
    name: ''
})
export abstract class ParentPipe {
    constructor(
        protected readonly sayHelloService: SayHelloService
    ) {
    }
}
```
It worked in the app, but when I tried to move the code back to the library with --prod option I got the error 
<pre><code>
ERROR: Cannot determine the module for class ParentPipe in D:/Temp/testapp/projects/testlib/src/lib/say-hello.pipe.ts! Add ParentPipe to the NgModule to fix it.

An unhandled exception occurred: Cannot determine the module for class ParentPipe in D:/Temp/testapp/projects/testlib/src/lib/say-hello.pipe.ts! Add ParentPipe to the NgModule to fix it.
See "C:\Users\sherif\AppData\Local\Temp\3\ng-NIqaLb\angular-errors.log" for further details.
</pre></code>

This scenario was working well in version 8, 7, etc. Previously the `@Injectable` on the parent abstract class with constructor injecting service was enough. Now it is broken for abstract classes, blocking the migration of a library I have to support version 9. 

Now I can refactor the code, and make the parent class not abstract, add the parent class in the module without exporting it, but is this the way to do that? And does that mean that inheriting from an abstract class is not supported in version 9?

## 🔬 Minimal Reproduction
https://github.com/sherif-elmetainy/testapp

Clone the repo
run:<pre><code>
yarn
yarn build testlib --prod
yarn start
</code></pre>
## 🔥 Exception or Error
<pre><code>
core.js:5828 ERROR Error: inject() must be called from an injection context
    at injectInjectorOnly (core.js:899)
    at Module.ɵɵinject (core.js:915)
    at ParentPipe_Factory (testlib.js:17)
    at SayHelloPipe_Factory (testlib.js:27)
    at Module.ɵɵpipe (core.js:36106)
    at AppComponent_Template (app.component.ts:13)
    at executeTemplate (core.js:11841)
    at renderView (core.js:11627)
    at renderComponent (core.js:13143)
    at renderChildComponents (core.js:11430)
defaultErrorLogger @ core.js:5828
main.ts:12 Error: inject() must be called from an injection context
    at injectInjectorOnly (core.js:899)
    at Module.ɵɵinject (core.js:915)
    at ParentPipe_Factory (testlib.js:17)
    at SayHelloPipe_Factory (testlib.js:27)
    at Module.ɵɵpipe (core.js:36106)
    at AppComponent_Template (app.component.ts:13)
    at executeTemplate (core.js:11841)
    at renderView (core.js:11627)
    at renderComponent (core.js:13143)
    at renderChildComponents (core.js:11430)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect          0.900.1
@angular-devkit/build-angular      0.900.1
@angular-devkit/build-ng-packagr   0.900.1
@angular-devkit/build-optimizer    0.900.1
@angular-devkit/build-webpack      0.900.1
@angular-devkit/core               9.0.1
@angular-devkit/schematics         9.0.1
@angular/cli                       9.0.1
@ngtools/webpack                   9.0.1
@schematics/angular                9.0.1
@schematics/update                 0.900.1
ng-packagr                         9.0.0
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2

</code></pre>

**Anything else relevant?**

**Comment by djleonskennedy** [comment]
`@Injectable()
export abstract class ParentPipe {
    constructor(
        protected readonly sayHelloService: SayHelloService
    ) {
    }
}`

Injectable in abstract class ?

**Comment by sherif-elmetainy** [comment]
@djleonskennedy 

> Injectable in abstract class ?

Yes, it worked fine in V8 and without it, injection for child classes didn't work.

**Comment by osahner** [comment]
same for abstract Components when ivy is disabled.

```ts
@Component({
  template: ''
})
export abstract class SomeAbstractComponent {
...
}
```

```
ERROR in Cannot determine the module for class SomeAbstractComponent in .../some-abstract.component.ts! Add SomeAbstractComponent to the NgModule to fix it.
```
