### ISSUE TITLE
Angular Router tutorial little issue

### ISSUE THREAD

**Issue by GaetanoPiazzolla** [angular/angular#35285]
# 📚 Docs or angular.io bug report

### Description

Following the tutorial, there is a problem on routing session: https://angular.io/start/routing
If you check this code, the routerLink has been set to put "productId" value on routing, but the id is not present in the file "product.ts" generated in the first part of the tutorial.

![image](https://user-images.githubusercontent.com/20367555/74144230-a3319980-4bfc-11ea-8541-32fb71eb12e6.png)

**Comment by santoshyadav198613** [comment]
Hi @GaetanoPiazzolla,

We are not defining the productId in model, if you notice the code 
'index as productId' we are treating index value as productid, in which case we don't need to create any productid, and it will be unique for each row.

You can refer https://angular.io/guide/structural-directives#inside-ngfor for more details on index and other properties in ngFor.

If you still think, something is causing confusion, let us know will get it sorted.

**Comment by GaetanoPiazzolla** [comment]
Oh my bad, I've skypped the additional information on ***ngFor** template directive.

I don't know if it should be better to not include the show-up of this feature in a tutorial about routing; in addition this kind of ID usually comes from rest calls, so maybe it should be better to include it in JSON file?

Anyway thank you very much for the detailed response.
