### ISSUE TITLE
Since Angular 9 ng build --prod runs in an error.

### ISSUE THREAD

**Issue by Raidri** [angular/angular#35280]
Since I updated to Angular 9. I can't do an ng build --prod. At the point where the css webpack optimization starts I get the following error:

92% chunk asset optimization optimize-css-webpack-plugin
An unhandled exception occurred: postcss-svgo: Error in parsing SVG: Invalid character in tag name
Line: 0
Column: 10
Char: =

This only happends with ng build --prod. ng build and ng serve works.

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by MarcusCalidus** [comment]
@Raidri  have you already found a solution for that? I'm running into exactly the same problem. Unfortunately the build process does not tell me which SVG is involved. So there is no possibility to debug. Can you please post your package.json? So we can narrow down on the packages we both use. That would be awesome. 

I suspect FontAwesome, NG-Zorro or any of my own SVGs

Here's mine:

```
 "dependencies": {
        "@angular/animations": "^8.0.0",
        "@angular/common": "^8.0.0",
        "@angular/compiler": "^8.0.0",
        "@angular/core": "^8.0.0",
        "@angular/forms": "^8.0.0",
        "@angular/platform-browser": "^8.0.0",
        "@angular/platform-browser-dynamic": "^8.0.0",
        "@angular/router": "^8.0.0",
        "@ewsjs/xhr": "1.4.1",
        "@fortawesome/fontawesome-pro": "^5.12.1",
        "@types/express": "^4.17.2",
        "classlist.js": "^1.1.20150312",
        "cluster": "^0.7.7",
        "colors": "^1.4.0",
        "ews-javascript-api": "^0.10.0",
        "express": "^4.17.1",
        "html-entities": "^1.2.1",
        "httpntlm": "^1.7.6",
        "json-circular-stringify": "0.0.1",
        "memory-cache": "^0.2.0",
        "moment": "^2.24.0",
        "ng-zorro-antd": "^8.5.2",
        "node-flags": "^0.1.9",
        "node-html-parser": "1.1.16",
        "pg-monitor": "^1.3.1",
        "pg-promise": "^10.4.4",
        "rxjs": "~6.5.4",
        "tslib": "^1.11.1",
        "utf8": "^3.0.0",
        "web-animations-js": "^2.3.2",
        "xml2json": "^0.12.0",
        "zone.js": "~0.10.2"
    },
```

**Comment by Raidri** [comment]
@MarcusCalidus Since angular 9.0.4 and some version updates of my dependencies. 
I was able to get rid of the error.

Before the version updates I could solve the problem by doing change the settings in the angular.json file. For me it was enough to set the optimization styles to false:

```
"production": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "optimization": {
                "scripts": true,
               "styles": false
              }
              .....
}

```
Maybe it helps you too.

**Comment by MarcusCalidus** [comment]
thank you @Raidri . That worked.

**Comment by KhaledGabr** [comment]
I am facing the same issue here. setting style optimization to false did the trick for me.
@Raidri  However, what updates have you made on your dependencies to get it to work.

I am currently,  on angular    9.0.6

**Comment by SteffiStuffel** [comment]
I'm facing the same issue and don't want to turn off style optimizations. 
Updating package did not work for me. Is there any other option?

**Comment by MarcusCalidus** [comment]
@SteffiStuffel This is, what "fixed" the problem for me.

Following assumptions:

- the SVG optimization works just fine
- some SVG in some part of my code is broken somehow
- I'll have to find the broken SVG, fix it and be fine

This is what I did:
Step 1: Prep `node_modules/svgo/lib/svgo.js` to tell me which SVG exactly is causing the problem

```
SVGO.prototype.optimize = function(svgstr, info) {
// some important code I will omit
// around line 36

optimizeOnceCallback = (svgjs) => {
                if (svgjs.error) {
                    reject(svgjs.error + '\nInput SVG Data: ' + svgstr); // <-- Fix this line to tell you which SVG Code breaks the rules
                    return;
                }

// rest of the code
```

Step 2: Try to build again. Likely you will get the broken SVG like so

```
An unhandled exception occurred: postcss-svgo: Error in parsing SVG: Invalid character in tag name
Line: 0
Column: 10
Char: =
Input SVG Data: <svgwidth='14'height='14'xmlns='http://www.w3.org/2000/svg'xmlns:xlink='http://www.w3.org/1999/xlink'><defs><rectid='a'width='14'height='14'rx='2'/></defs><gfill='none'fill-rule='evenodd'><usefill='#F4F5F7'xlink:href='#a'/><rectstroke='#DFE1E5'x='.5'y='.5'width='13'height='13'rx='2'/></g></svg>
```

In my case all spaces were missing in some external CSS I absolutely have to load

Step 3: Find the broken SVG in your code
Step 4: Fix the SVG

Aaaaand you're good. Hope this helps.
