### ISSUE TITLE
After updating angular 9 cannot find module issue 

### ISSUE THREAD

**Issue by arunaxxl** [angular/angular#35287]
I am using 

Angular 9.0.0
Angular CLI 9.0.1

**Comment by arunaxxl** [comment]
<img width="637" alt="Screenshot_6 jpeg" src="https://user-images.githubusercontent.com/54522898/74146451-18b25f80-4c27-11ea-8ac6-4bfbac9f349b.png">

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
