### ISSUE TITLE
Universal TOH is out of date

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#35289]
# 📚 Docs or angular.io bug report

### Description
Sample code is out of date in universal guide is out of date and doesn't reflect Angular 9.
https://angular.io/guide/universal

## 🔬 Minimal Reproduction
Clone https://angular.io/generated/zips/universal/universal.zip this is not the same structure as if you do.
```
ng new demo
cd demo
ng add @nguniversal/express-engine
```

**Comment by santoshyadav198613** [comment]
Hi @kapunahelewong ,
Please assign this to me, I am also planning to update the universal docs, will do that as part of another PR.

**Comment by santoshyadav198613** [comment]
Hi @alan-agius4 , @kapunahelewong ,

I can see all examples still uses Angular 8, is there any PR to upgrade them or can I go ahead and update it.

**Comment by santoshyadav198613** [comment]
It's already in progress https://github.com/angular/angular/pull/34374 ignore my comments.
