### ISSUE TITLE
Angular 9 confuses literal null with undefined when wrapped in object in input

### ISSUE THREAD

**Issue by bgoscinski** [angular/angular#35298]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/.... I guess compiler

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8.2.14

### Description

Angular 9 confuses literal `null` with `undefined` in inputs when the literal is wrapped in object and there are at least 2 instances of given component. In my project this breaks routing because there is a difference between

```html
<a [routerLink]="['', { outlets: { aux: null } }]"></a>
<a [routerLink]="['', { outlets: { aux: undefined } }]"></a>
```

## 🔬 Minimal Reproduction

1. execute following:

   ```sh
   git clone https://github.com/bgoscinski/angular-bug-repro1.git
   cd angular-bug-repro1
   npm install
   ng serve
   ```

1. observe the difference: 
![image](https://user-images.githubusercontent.com/5730169/74160355-8e193280-4c1d-11ea-9842-a8f31c6af147.png)

1. see https://github.com/bgoscinski/angular-bug-repro1/blob/master/src/app/app.component.html#L17-L22

## 🌍 Your Environment

**Angular Version:**

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.1
Node: 12.7.0
OS: win32 x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

I guess the easiest workaround is to declare property on component instance and set its value to `null` and use it instead of literal `null` in templates

**Comment by ysdidenko** [comment]
We have noticed the same behavior for 9.0.1
