### ISSUE TITLE
Property 'value' does not exist on type 'EventTarget'

### ISSUE THREAD

**Issue by sysmat** [angular/angular#35293]
tsconfig.json:
"angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictTemplates": true
  }

# 🚀 feature request

### Relevant Package
angular 9

### Description
Casting in html template

`(keyup)="filter($event.target.value)"`

### Describe the solution you'd like
(keyup)="filter(($event.target as HTMLInputElement).value)"

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by alxhub** [comment]
Hello @sysmat,

Unfortunately casting in templates isn't really possible at this point. There is no way to import types within a template and it's not likely that Angular will gain that ability in the near future.

There are three potential approaches here:

1) use an explicit cast to `any`:

```html
<input (keyup)="filter($any($event.target).value)">
```

2) Globally tell Angular not to check the type of DOM event bindings by disabling `strictDomEventTypes`:

```json
{
  "angularCompilerOptions": {
    "strictTemplates": true
    "strictDomEventTypes": false,
  }
}
```

3) Use a component method to implement the cast:

```typescript
@Component({
  selector: '...',
  template: '<input (keyup)="filter(target($event).value)">',
})
export class SomeCmp {
  target(event: KeyboardEvent): HTMLInputElement {
    if (!(event.target instanceof HTMLInputElement)) {
      throw new Error("wrong target");
    }
    return event.target;
  }
}
```

**Comment by topce** [comment]
Hi @sysmat @pkozlowski-opensource and @alxhub 

According Angular  documentation passing event is a dubious practice:
[passing event is a dubious practice](https://angular.io/guide/user-input#passing-event-is-a-dubious-practice).
There they advise to use template ref

Is it documentation still relevant !?
