### ISSUE TITLE
benchpress: integrate with desktop firefox

### ISSUE THREAD

**Issue by tbosch** [angular/angular#353]
Firefox webdriver needs to get:
- performance log
- command for forcing gc

**Comment by tbosch** [comment]
Maybe see here: https://github.com/auchenberg/remotedebug-firefox-bridge

**Comment by juliemr** [comment]
@hankduan is taking a look at this.

**Comment by hankduan** [comment]
Findings so far captured here: https://docs.google.com/document/d/17f9q9yOM4Z705Gj2RsC2KNY2kQDtbIsxMydYpM1YEBU/edit?usp=sharing

You can also see https://github.com/hankduan/firefoxExtension for some sample code.

**Comment by tbosch** [comment]
This sounds great!

**Comment by hankduan** [comment]
As noted in the doc, running the tests via a webdriver server prevents access to chrome authority and the file sdk (used for file I/O). Future directions for investigations are:
- Firefox Driver
- Protractor's direct connect with firefox
- Marionette (https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette)

**Comment by hankduan** [comment]
See https://github.com/hankduan/firefoxExtension for an update. 

The extension exposes 3 functions: `startProfiler`, `stopAndRecord`, and `forceGC`, which can be called via protractor (see https://github.com/hankduan/firefoxExtension/blob/master/spec.js). 

The functions should achieve approximately what is desired. However, I don't know what is the expected format for the profile JSON. Here's an example (corresponding to the spec.js mentioned): https://gist.githubusercontent.com/hankduan/c8496aebf77a0de7fa90/raw/gistfile1.json

**Comment by tbosch** [comment]
So you solved the problem that you can now access these functions also
during webdriver tests?

**Comment by hankduan** [comment]
Yes, although I'm not certain what I did to fix it. It might be a browser upgrade or a config change.

**Comment by tbosch** [comment]
So the plugin should just forward the original data from Firefox to keep it
as simple as possible. We will then add a new WebDriverExtension class to
benchpress that does the transformation outside of the plugin.

What would you think how long it takes to move the plugin to the Angular2
repo and add unit and integration tests to it?

**Comment by hankduan** [comment]
How do you want the data forwarded? Right now it just saves the data to a specified file. 
In terms of tests, I can add an integration test fairly quickly. Unit tests don't make much sense since this is just a wrapper over core firefox

**Comment by hankduan** [comment]
See https://github.com/angular/angular/pull/1976

**Comment by tbosch** [comment]
Done via 0949a4b045a6729008d34b06257c2134e6548eee. Thanks @hankduan !!
