### ISSUE TITLE
Angular 9: unable to create dynamic module at runtime

### ISSUE THREAD

**Issue by DenysVuika** [angular/angular#35301]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?
regression, works fine with Angular 8

### Description

the following block of code won't compile anymore:

```ts
private createComponentFactorySync(compiler: Compiler, metadata: Component, componentClass: any): ComponentFactory<any> {
        const cmpClass = componentClass || class RuntimeComponent {
        };
        const decoratedCmp = Component(metadata)(cmpClass);

        @NgModule({ imports: [], declarations: [decoratedCmp] })
        class RuntimeComponentModule {
        }

        const module: ModuleWithComponentFactories<any> = compiler.compileModuleAndAllComponentsSync(RuntimeComponentModule);
        return module.componentFactories.find((x) => x.componentType === decoratedCmp);
    }
```

Error output:

```
error NG1010: Value at position 0 in the NgModule.declarations of RuntimeComponentModule is not a reference: [object Object]

@NgModule({ imports: [], declarations: [decoratedCmp] })
```

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.1
Node: 13.4.0
OS: darwin x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.1
@angular-devkit/build-angular      0.900.1
@angular-devkit/build-ng-packagr   0.900.1
@angular-devkit/build-optimizer    0.900.1
@angular-devkit/build-webpack      0.900.1
@angular-devkit/core               7.3.9
@angular-devkit/schematics         9.0.1
@angular/cli                       9.0.1
@angular/flex-layout               9.0.0-beta.29
@angular/material-moment-adapter   8.2.3
@ngtools/webpack                   9.0.1
@schematics/angular                9.0.1
@schematics/update                 0.900.1
ng-packagr                         9.0.0
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Anything else relevant?**

**Comment by alexzuza** [comment]
It's a ngtsc compiler error that's coming from https://github.com/angular/angular/blob/81241af7ac1d320ad17feba1b69fd34f04ac278a/packages/compiler-cli/src/ngtsc/annotations/src/ng_module.ts#L577-L580

This means that ngtsc tries to collect annotations for your runtime generated code and it doesn't support such dynamic definitions.

What you can do is to rewrite your code a little:
```
const moduleClass = class RuntimeComponentModule {
};
const decoratedNgModule = NgModule({ imports: [], declarations: [decoratedCmp] })(moduleClass);

const module: ModuleWithComponentFactories<any> = compiler.compileModuleAndAllComponentsSync(decoratedNgModule);
```

**Comment by DenysVuika** [comment]
Great, thanks for help, @alexzuza.
