### ISSUE TITLE
ng build --watch doesn't watch more than one time

### ISSUE THREAD

**Issue by netdjw** [angular/angular#35303]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8.2.13

### Description

If I run the `ng build --watch` command the build is run, get some error messages, but not detecting my file cahnges. Sometimes it detect one change, sometimes not detect any changes. I can't figure out what depends on.

## 🔬 Minimal Reproduction

I have no idea how can you reproduct this bug.

## 🔥 Exception or Error
This is the output (I think nothing wierd, just my normal errors. All error messages are valid and true.)
<pre><code>
ng build --watch

chunk {main} main.js, main.js.map (main) 620 bytes [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 675 bytes [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 518 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 149 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 939 kB [initial] [rendered]
Date: 2020-02-10T13:51:08.624Z - Hash: 86e1e2264f79392cb72e - Time: 30090ms

ERROR in src/app/components/certificate/certificate-generic-create-edit/settings/certificate-generic-settings/certificate-generic-settings.component.html:18:29 - error TS2339: Property 'deviza_exchange_rate' does not exist on type 'CertificationInterface'.

18   <div class="col" *ngIf="!!certificate.deviza_exchange_rate">
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/app/components/certificate/certificate-generic-create-edit/settings/certificate-generic-settings/certificate-generic-settings.component.ts:17:16
    17   templateUrl: './certificate-generic-settings.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component CertificateGenericSettingsComponent.
src/app/components/product/category/product-category-tree-list/product-category-tree-list.component.html:35:41 - error TS2345: Argument of type 'DataTreeInterface<ProductCategoryInterface>' is not assignable to parameter of type 'ProductCategoryTreeInterface'.
  Type 'DataTreeInterface<ProductCategoryInterface>' is missing the following properties from type 'ProductCategoryTreeInterface': getValidatedErrorFields, removeNullOrEmptryArray, is_disabled_to_add_product, description, and 22 more.

35         type="delete" (confirm)="delete(_productCategoryTree)"></app-confirm-dialog>
                                           ~~~~~~~~~~~~~~~~~~~~

  src/app/components/product/category/product-category-tree-list/product-category-tree-list.component.ts:17:16
    17   templateUrl: './product-category-tree-list.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ProductCategoryTreeListComponent.
</code></pre>

Meanwhile I fiex all my issues and now I get this error:

<pre><code>
ERROR in Error: Internal Error: Unexpected interpolation
    at error (d:\Code\angular\node_modules\@angular\compiler\bundles\compiler.umd.js:2721:15)
    at _AstToIrVisitor.interpolationFunction (d:\Code\angular\node_modules\@angular\compiler\bundles\compiler.umd.js:17789:179)
    at _AstToIrVisitor.visitInterpolation (d:\Code\angular\node_modules\@angular\compiler\bundles\compiler.umd.js:8498:29)
    at Interpolation.visit (d:\Code\angular\node_modules\@angular\compiler\bundles\compiler.umd.js:7572:28)
    at convertPropertyBinding (d:\Code\angular\node_modules\@angular\compiler\bundles\compiler.umd.js:8274:52)
    at TemplateDefinitionBuilder.convertPropertyBinding (d:\Code\angular\node_modules\@angular\compiler\bundles\compiler.umd.js:17789:44)
    at d:\Code\angular\node_modules\@angular\compiler\bundles\compiler.umd.js:17711:39
    at Object.params (d:\Code\angular\node_modules\@angular\compiler\bundles\compiler.umd.js:13685:49)
    at Object.value (d:\Code\angular\node_modules\@angular\compiler\bundles\compiler.umd.js:17709:34)
    at d:\Code\angular\node_modules\@angular\compiler\bundles\compiler.umd.js:17739:42
    at Array.map (<anonymous>)
    at d:\Code\angular\node_modules\@angular\compiler\bundles\compiler.umd.js:17738:38
    at d:\Code\angular\node_modules\@angular\compiler\bundles\compiler.umd.js:17016:83
    at Array.map (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (d:\Code\angular\node_modules\@angular\compiler\bundles\compiler.umd.js:17016:56)
    at d:\Code\angular\node_modules\@angular\compiler\bundles\compiler.umd.js:17558:60
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.1
Node: 12.15.0
OS: win32 x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by alxhub** [comment]
Hi @netdjw,

We'd love to investigate this for you, but we'll need a reproduction - a link to a Github repository with clear instructions on how to produce the problem. Without that it's really hard for us to deduce from the report + error messages what's going on.

If you make a change to a template and get that crash ("Unexpected interpolation"), the text of that template would be very useful for us in at least attempting to reproduce the problem.

**Comment by netdjw** [comment]
I investigated what is the code what is causing this misterious error message:

```
<div class="color-container" style="background-color: {{ item.color }};"></div>
```
It would be nice if the compiler could be tell me minimum the file name, but better if the filename, and the exact position of the error.

I fixed it with deleting the line of code.

**Comment by pkozlowski-opensource** [comment]
The "Unexpected interpolation" error is tracked in #33575

**Comment by alxhub** [comment]
Tested and this error no longer occurs as of the latest Angular. Closing as fixed!
