### ISSUE TITLE
Strange issue with router.navigate after upgrading to Angular 9

### ISSUE THREAD

**Issue by javiercampos** [angular/angular#35302]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?

Yes, it worked in 8.x (or so it seemed), with non-lazy loaded modules at least

### Description

The issue is a bit weird, and I can't really make an specific reproduction because it seems to depend on the speed on how the router is initialized somehow.

We have some components that use `router.navigate(['series', 'of', 'commands'])` on click events. These work just fine when the application is loaded. However **sometimes**, if we reload the page on a deep route, then change the route to any "parent" route (by clicking on something) and then do a `router.navigate` of those mentioned above, sometimes, one of the commands passed to `navigate` gets "duplicated" on the target url.

For example, say I want:
```typescript
/// custromerId is a string
this.router.navigate(["main", "customers", customerId, "profile"]);
```

When this happens, I may end up with the router trying to navigate to: `/main/main/customers/<the-customer-id>/profile` (notice the duplicated `main`).

Other times (not sure exactly when, or why, but seems to be consistent: meaning it's always the same "command" that gets duplicated), I could get: `/main/customers/customers/<the-customer-id>/profile`.

I've enabled tracing on the router and it doesn't seem to be generating extra events: the `NavigateStart` event goes directly to that wrong URL with nothing in-between (it's not as if something was loading).

Note that changing the `navigate` calls to `navigateByUrl` and constructing the whole URL itself works perfectly fine: it seems to be an issue with just `navigate`

This is the strangest part: this fails if I press F5 on say:
- /main/something
- Then navigate to:
  - /main/otherthing _(works fine)_
  - Then navigate to:
    - /main/otherthing/something/something _(fails here with the strange duplication of one of the commands)_

Then it fails, **but only if I do it very quickly**... if I wait some time (say 5/10 seconds), it works correctly. I've checked the timeline on the developer tools and everything seems loaded pretty quickly (even async and xhr requests), nothing seems changed on those 5/10 seconds that wouldn't happen on the first two seconds (when it fails).

Note that everything works generally smoothly, and it only fails on that specific scenario

It's also "more or less" consistent, however strangely random:
- It happens almost always in Edge Chromium
- Happens many times in Firefox
- Happens many times in Chrome
- Can't really get it to happen in Brave

We have been really scratching our heads with this, and trying to make a small reproduceable example but couldn't really get into it. The project is a bit large and a bit complicated to reproduce on a small scale, however, it used to work fine on 8.x and we didn't seem to find the problem on the 9-rc's (however nobody was looking for the problem, which was noticed a few days ago only, so it might reproduce on the rc's... or even on 8.x and nobody did notice during development).

The biggest change of course has been going to IVY and importing the routes lazily... but again, everything seems to work all the time except on the specific case (pressing F5 on an inner route, going back then navigating). The same code, same router traces, same everything.

Has anyone suffered anything remotely related to this?

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.1
Node: 12.14.1
OS: win32 x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

If you are able to determine that this is in fact a bug in Angular and can provide a reproduction, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template that include info on how to create a reproduction using our template.
