### ISSUE TITLE
NgIf inside NgIf doesn't work

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#3531]
With alpha.34

If an `NgIf` with a true condition on a `p` element is inside an `NgIf` with a false condition on another `p` element, it is displayed anyway:

```
<p *ng-if="false">
  Inside first ngIf
  <p *ng-if="true">Inside second ngIf</p>
</p>
```

produces:

``` 
Inside second ngIf
```

Whereas it should not as the englobing `NgIf` is false.

May be related to #3521 ?

**Comment by chrisoverzero** [comment]
`p` has an omittable end tag, so it cannot be nested like that. The first `ng-if` ends just before the second begins. Does this still happen if you use `div` instead?

**Comment by cexbrayat** [comment]
No, you're right, I did not think about that, thanks.
