### ISSUE TITLE
Getting ERROR Error: The selector "app-root" did not match any elements

### ISSUE THREAD

**Issue by athulya-ratheesh19** [angular/angular#35319]
I am getting error 
**"ERROR Error: The selector "app-root" did not match any elements
    at t.selectRootElement (angular8-demo.js:3)
    at e.create (angular8-demo.js:3)
    at t.bootstrap (angular8-demo.js:3)
    at angular8-demo.js:3
    at Array.forEach (<anonymous>)
    at t._moduleDoBootstrap (angular8-demo.js:3)
    at angular8-demo.js:3
    at t.invoke (angular8-demo.js:2)
    at Object.onInvoke (angular8-demo.js:3)
    at t.invoke (angular8-demo.js:2) "**

while importing angular 8 component to an external html file.

**Comment by athulya-ratheesh19** [comment]
Also i had done with exporting an individual component to and external html page, but the component was not fully loaded. some of its fields are missing.

**Comment by santoshyadav198613** [comment]
Can you provide a gihub repo to check?

**Comment by athulya-ratheesh19** [comment]
Here i had added a component called as general request and also tried to call that component in an external file called test.html . Bt now it was not working properly.
[angular8-charts.zip](https://github.com/angular/angular/files/4184519/angular8-charts.zip)

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
