### ISSUE TITLE
Can't update complete because of that `ng update @angular/cli @angular/core --next`

### ISSUE THREAD

**Issue by PterPmnta** [angular/angular#35315]
Try to update angular  8.x to 9, i find with this

Using the commend `ng update @angular/cli @angular/core `, this message appear

![Screenshot_1](https://user-images.githubusercontent.com/3231405/74205901-34c5f900-4c47-11ea-8795-e6e166ffe3d0.png)

I just update in the folder user PC, is necessary do it that into the folder, in my case github folder have the angular projects?

**Comment by Airblader** [comment]
You need to run these commands in the root folder of your Angular project (for each project you have). The update migrates code so it cannot be executed globally in your system.

**Comment by PterPmnta** [comment]
@Airblader  thnaks for your answer, i think after that, maybe this the solution
