### ISSUE TITLE
Stackblitz generator breaks getting started tutorial.

### ISSUE THREAD

**Issue by ezekeal** [angular/angular#35324]
# 📚 Docs or angular.io bug report

### Description
Getting started docs do not work as written.

The Getting started portion of the docs assumes that the Stackblitz generator will add a component to app.module.ts. It does not.

Any user unfamiliar with this necessity will be completely lost on why the beginner tutorial does not work when they add the "Notify Me" component.

## 🔬 Minimal Reproduction
Follow the getting started instructions exactly as written up to the point when the "Notify Me" button should display.

### What's the affected URL?**
https://angular.io/start

### Reproduction Steps**
Follow the getting started instructions exactly as written up to the point when the "Notify Me" button should display.

### Expected vs Actual Behavior**
expected: "Notify Me" button will display
actual: "Notify Me" button will not display and there will be an error displayed.

## 📷Screenshot
N/A

## 🔥 Exception or Error
<pre><code>
Error in /turbo_modules/@angular/compiler@8.2.14/bundles/compiler.umd.js (2603:21)
Template parse errors:
Can't bind to 'product' since it isn't a known property of 'app-product-alerts'.
</code></pre>

### Browser info
Chrome 79, Mac 10.14.6

### Anything else relevant?
N/A

**Comment by Roopa2188** [comment]
I started working on this Sample project of stackblitz. i am also getting same error. 
Stackblitz generator is not adding any component created to app.module.ts.

**Comment by sonukapoor** [comment]
@kapunahelewong i can take a look at this one. Please assign to me

**Comment by glezjose** [comment]
Yup, this just happened to me, as I tried to fork the project.

**Comment by glezjose** [comment]
I saw the problem, the tutorial never specificates to import and declare the component class inside the app.module file, so the project doesn't know where to find the selector.

**Comment by kapunahelewong** [comment]
Thanks for bringing this up, @ezekeal and thanks got @sonukapoor for volunteering to take it.

**Comment by sonukapoor** [comment]
@ezeikel / @Roopa2188 / @glezjose I have followed the exact steps and did not come across the same error. The app is working fine. 

You can view my copy here:

https://stackblitz.com/angular/ybmvyemqokb?file=src%2Fapp%2Fproduct-alerts%2Fproduct-alerts.component.ts

Can one of you please share your stackblitz with me?

**Comment by Roopa2188** [comment]
@sonukapoor  I am unable to view your copy of product-alerts component. its showing only product list component

**Comment by sonukapoor** [comment]
@Roopa2188 It seems my version was not saved at all. I will retry and get back to you soon.

**Comment by sonukapoor** [comment]
@ezeikel / @Roopa2188 / @glezjose I followed the steps again and was able to get it working without any issues. Please see below:

https://stackblitz.com/edit/angular-start-1?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.html

**Comment by sonukapoor** [comment]
@ezekeal Let us know if you are able to get this working.

**Comment by ezekeal** [comment]
Yes, new generated components are now being added automatically to app.module.ts.
