### ISSUE TITLE
[build] test.unit.js takes 30 secs to trigger

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#3532]
After merging 643c71740e9e0a325f2f3b8431eb5f67cd84ba56 there is ~30 secs lag between file change and test run trigger. Changing `noEmitOnError` back to `false` in https://github.com/angular/angular/blob/ff1b110ae15962f01b9b3c4d42fca8f20bab8b55/tools/broccoli/trees/browser_tree.ts#L103 gets the situation back to normal (< 2s).

I would vote for flipping this flag to `false` till we can figure out what causes this slowdown (unless someone has an idea how to fix this slowdown without removing type checks).

**Comment by IgorMinar** [comment]
I filed two issues with Typescript related to this:
- https://github.com/Microsoft/TypeScript/issues/4282
- https://github.com/Microsoft/TypeScript/issues/4287

**Comment by pkozlowski-opensource** [comment]
Thnx @IgorMinar!

**Comment by IgorMinar** [comment]
fyi with node 4 upgrade we improved `!broccoli.js.dev` time from 20706ms to 12127ms.

there is more we can do still.. (create a separate core src compilation unit, and a bunch of auxilary compilation units for router, http, examples, etc).

**Comment by pkozlowski-opensource** [comment]
I think that this one is obsolete with all the build changes. Will open a new issue if there are new productivity killers.
