### ISSUE TITLE
[ivy] 'ngClass' + 'dynamic [class] = undefined | null' completely clears out 'static class binding'

### ISSUE THREAD

**Issue by Gretam11** [angular/angular#35335]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core or @angular/common 9.0.0

### Is this a regression?
It works fine when Ivy is opted-out.

### Description
I'm not sure whether this is a real bug, but it's indeed behavior which some libraries depend on. If the `static class binding` is specified with `NgClass` directive and with `dynamic class binding equals null or undefined`, all values from static class binding are being cleared out.
In case if any string (even empty) is specified in dynamic binding, it just merges all classes as expected.

## 🔬 Minimal Reproduction
I couldn't turn on ivy on stack-blitz, so here is the link on `ng-run` of minimal reproduction:
https://ng-run.com/edit/LKHMmMPIRiZmgFFqMt15
It's handy to turn on/off Ivy there. 

## 🌍  Your Environment

**Angular Version:**
<pre>Angular CLI: 9.0.1
Node: 12.13.0
OS: win32 x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2<code>

**Comment by cagataycivici** [comment]
Thank you, it was a showstopper for us to release PrimeNG 9.0.0
