### ISSUE TITLE
Outdated i18n example

### ISSUE THREAD

**Issue by santam85** [angular/angular#35334]
# 📚 Docs or angular.io bug report

### Description

The example i18n project referenced in the latest documentation is using old (<9) style localization configuration, and the source code does not match the documented instructions

### What's the affected URL?**
https://angular.io/guide/i18n#translate-attributes

### Expected vs Actual Behavior**
Would have expected a section in the angular.json similar to:

```
"i18n": {
      "sourceLocale": "en-US",
      "locales": {
        "fr": "src/locale/messages.fr.xlf"
      }
    }
```

**Comment by javiermarinros** [comment]
The current docs also indicates to use the parameter `--i18nLocale` with `ng serve` or `ng build` that is no longer available since v9

[https://angular.io/guide/i18n#i18n-pipes](https://angular.io/guide/i18n#i18n-pipes)

**Comment by kapunahelewong** [comment]
Status: @rockument69 is currently working on a rewrite of this doc in https://github.com/angular/angular/pull/36082

Fyi, @rockument69

**Comment by rockument69** [comment]
I need engineering input to fix the example. I will contact the appropriate person.

**Comment by rockument69** [comment]
This is now in progress in PR [36924](https://github.com/angular/angular/pull/36924).

**Comment by rockument69** [comment]
PR [36924](https://github.com/angular/angular/pull/36924) (docs: Refactor-i18n-DOCS-758) closes this issue.
