### ISSUE TITLE
ViewChild "static" doc incorrect.

### ISSUE THREAD

**Issue by bicarlsen** [angular/angular#35345]
# 📚 Docs or angular.io bug report

### Description

The [documentation for ViewChild's](https://angular.io/api/core/ViewChild) `static` metadata property states 
> static - True to resolve query results before change detection runs, false to resolve after change detection. Defaults to false.

Which seems to impy that this is an optional argument. However, the call signature is `selector: Type<any> | Function | string, opts: { read?: any;  static: boolean;}): any;`

## 🔬 Minimal Reproduction
ViewChild( 'selector', {} );

### What's the affected URL?**
https://angular.io/api/core/ViewChild.

**Comment by kara** [comment]
The link you provided is from the version 9 docs, where `static` is indeed optional. The signature in v9 is `(selector: Type<any>|Function|string, opts?: {read?: any, static?: boolean}): any;`.

If you want the version 8 docs, change the prefix to v8.angular.io
