### ISSUE TITLE
Angular 8 vs 9 Size Comparison 

### ISSUE THREAD

**Issue by webtrainer-in** [angular/angular#35351]
Hi Team 

I have just created two default applications one with Angular 8 and another one is with Angular 8 CLI. But Angular 9 Size is more than Angular 8 as shown in below screen shot

![NG8 vs NG9 Size](https://user-images.githubusercontent.com/42771352/74294411-cc206e80-4d63-11ea-9a67-f82b713fca4b.png)

Could you please guide me on this, I was expecting lesser size with Angular 9.

**Comment by gmareater** [comment]
that's not right way for comparision, you should compare compiled output
simply run: ng build --prod
and compare these two, not the whole working directory

**Comment by webtrainer-in** [comment]
Thanks now I can see the size is decreased by 14% with angular 9

**Comment by webtrainer-in** [comment]
When I build two different "Hello world" app, one with Angular 8 and one with Angular 9 cli, I can see 14% decrease in size. 

But when I build  same Angular 9 app with "enableIvy":false I got build app size is 420 kb

And I got build size 475 kb If i have enabled Ivy

Why so?

**Comment by spock123** [comment]
@webtrainer-in 
To be honest, I don't think you should look much into payload sizes with Angular9. This version is mostly about introducing IVY and keeping backwards compatibility. You can actually still use both rendering engines. Once the older engine is deprecated and now that IVY is in "production", the team can focus more on reducing payload sizes and adding new features that were previously impossible/very difficult pre-IVY.

About payload sizes now is that you might find payload size for your main bundle to actually increase a small bit (depends on your application size and structure), but the feature modules will probably have decreased in size a bit.

Payload size will decrease once we get larger adoption of IVY and once the team can focus on improving IVY and not just get compatibility and migration nailed. NG9 was mostly about this process, and it's been a smooth ride afaik.

FWIW our production application has 44 bundles when compiled. Main bundle size increased by 2% and generated bundles decreased on average 20% in size. Bootstrapping our application has however has improved 20% in startup time compared to the Ng8 renderer.

We also support 3 languages and we have now been able to completely drop dependency upon 3rd party libraries for translation (ngx-translate) and can now do build-time translation in templates, components and services/store etc. Amazing stuff.

**Comment by webtrainer-in** [comment]
Thanks for your detailed reply,  just was curious to know if I am doing
something wrong here that why I am not getting reduced size so that I can
show to my students.

So this version is most on keeping it compatible and easy for migration and
still moving to new rendering engine. So we will see lesser size of build
in upcoming versions.

Thanks again for your valuable insight and good work.

**Comment by spock123** [comment]
@webtrainer-in there are still many new features in ng9, but of course the main "dish" is the IVY renderer. 

I'm not involved with development, I'm just a visitor :)

Cheers

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
