### ISSUE TITLE
Remove @IMPLEMENTS, replace with TypeScript `implements`

### ISSUE THREAD

**Issue by mprobst** [angular/angular#3535]

**Comment by mprobst** [comment]
@vsavkin I think you had some mocking practice that interfered with not using `@IMPLEMENTS`, right? Any update on that?

**Comment by vsavkin** [comment]
@mprobst I created two files: spies.ts and spies.dart. We define all new spies there. It turned out to be much simpler than trying to make one class work well in TS and Dart. 

We should move all spy classes there, and then remove `@IMPLEMENTS`.

**Comment by mprobst** [comment]
@vsavkin awesome! Are you going to do the removal?

**Comment by vsavkin** [comment]
@mprobst sure, I can do it.
