### ISSUE TITLE
Cache busting issues with angular template files

### ISSUE THREAD

**Issue by kaushiksamanta** [angular/angular#35353]
```ng build --output-hashing=all```

This should handle cache busting by default. The compiled js-file-names contain a hash-number for every version so that files won't be cached. And the html should be included in the javascript-files. Still old template-stuff seems to be cached.

**Comment by ericmartinezr** [comment]
Please report cli issues in cli's repo https://github.com/angular/angular-cli/issues, and also respect the issue template 👍

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
