### ISSUE TITLE
node_modules\@angular\core\__ivy_ngcc__\fesm5\core.js as it exceeds the max of 500KB.

### ISSUE THREAD

**Issue by kurubavinodkumar** [angular/angular#35358]
ng build 

while running ng build i am seeing below note in red color 
please provide fix 

**node_modules\@angular\core\__ivy_ngcc__\fesm5\core.js as it exceeds the max of 500KB.**

![image](https://user-images.githubusercontent.com/36882248/74306944-04d33e80-4d8a-11ea-84e4-f903681e57ad.png)

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
