### ISSUE TITLE
viewBindings is not documented in CHANGELOG.md

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#3536]
I just noticed that [CHANGELOG.md](https://github.com/angular/angular/blob/master/CHANGELOG.md#200-alpha34-2015-08-07) is not documenting `viewInjector` as being renamed to `viewBindings` which is a breaking change.

**Comment by ericmartinezr** [comment]
I think they should add too the change from Ancestor to Host/Host SkipSelf

**Comment by mhevery** [comment]
Sorry about that. Unfortunently we don't have plans on rewriting past history, we are planning on getting better about breaking changes in the future. Closing since no action.
