### ISSUE TITLE
Typo in template-syntax example 

### ISSUE THREAD

**Issue by dtaylor84** [angular/angular#35368]
# 📚 Docs or angular.io bug report

### Description
In the "Passing in an object" section, the text describes the ListItemComponent as having a property item of type Item.

However, the code example src/app/list-item.component.ts shows ListItemComponent having a property items of type Item[].

&lt;code-example path="property-binding/src/app/list-item/list-item.component.ts" region="item-input" header="src/app/list-item.component.ts"&gt;

### What's the affected URL?
https://angular.io/guide/template-syntax#return-the-proper-type

**Comment by sonukapoor** [comment]
@pkozlowski-opensource I can take this one. Please assign to me.

**Comment by kapunahelewong** [comment]
Thank you so much, @sonukapoor!
