### ISSUE TITLE
Angular Cli 9.0.0 Getting Error when import HttpClientModule

### ISSUE THREAD

**Issue by hotdev6m** [angular/angular#35361]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please file any Angular CLI issues at: https://github.com/angular/angular-cli/issues/new

For the time being, we keep Angular CLI issues in a separate repository.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

I am getting below error when I try to use HttpClientModule.
![image](https://user-images.githubusercontent.com/54219053/74316218-d161d580-4dc4-11ea-9c30-833a3d0c2e27.png)

I am using the below versions on Windows 10.
node version:  12.16.0
npm version: 6.13.4
Angular CLI: 9.0.1

Please let me know how can I fix this issue.
Regards.

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Comment by chris13524** [comment]
@hotdev6m I'm also experiencing this issue. Are you symlinking your node_modules by chance?
