### ISSUE TITLE
template-syntax stackblitz example doesn't work

### ISSUE THREAD

**Issue by dtaylor84** [angular/angular#35364]
# 📚 Docs or angular.io bug report

### Description

The stackblitz example for the template-syntax page does not work.

A closed issue suggests this may be because stackblitz doesn't support some aspect of the example: https://github.com/angular/angular/issues/31537#issuecomment-511087692

However, having a link to a broken example is confusing and frustrating. If it can't be fixed I would suggest removing the link, or at least adding a note to the page that it is currently unavailable.

## 🔬 Minimal Reproduction
https://angular.io/generated/live-examples/template-syntax/stackblitz.html

### What's the affected URL?**
https://angular.io/guide/template-syntax

### Expected vs Actual Behavior**
Expected: live example works
Actual: ERR_CONNECTION_RESET

**Comment by sonukapoor** [comment]
@pkozlowski-opensource i can take a look. Can you please assign to me?

**Comment by sacgrover** [comment]
@dtaylor84  this link is working for me:
https://angular.io/generated/live-examples/template-syntax/stackblitz.html

**Comment by dtaylor84** [comment]
Hmm, working for me now too -- sorry for the noise.

(Other examples were working, so not sure what was going wrong with that one!)
