### ISSUE TITLE
[Ivy] angular 9 compiler `Internal Error: The name <name> is already defined in scope to be [object Object]`

### ISSUE THREAD

**Issue by djleonskennedy** [angular/angular#35369]
# 🐞 bug report

### Affected Package
@angular/compiler

### Is this a regression?
Yes, we're migrating from `7.1.x`, in 7's version no error in aot mode

### Description
if we accidentally duplicate let expression in template we'll get an error

```
<ng-template #tmps let-obj let-obj="obj">
  {{obj | json}}
</ng-template>
<ng-container 
  [ngTemplateOutlet]="tmps" 
  [ngTemplateOutletContext]="{$implicit: {a: 2}"
</ng-container>
```
this is correct behavior, but during migration it's quite hard to investigate where actually error is.
Cause of error message `The name <name> is already defined in scope to be [object Object]`
due to [object Object] it's not understandable

## Minimal Reproduction
https://github.com/djleonskennedy/ng9-repro
- `npm i`
- `npm run build --prod`

NOTE - issue cannot be reproduced in stackblitz

## 🔥 Exception or Error
<pre><code>
ERROR in Error: Internal Error: The name obj is already defined in scope to be [object Object]
    at error (/home/project/src/santander/misc/example/node_modules/@angular/compiler/bundles/compiler.umd.js:2721:15)
    at BindingScope.set (/home/project/src/santander/misc/example/node_modules/@angular/compiler/bundles/compiler.umd.js:18154:17)
    at TemplateDefinitionBuilder.registerContextVariables (/home/project/src/santander/misc/example/node_modules/@angular/compiler/bundles/compiler.umd.js:17051:32)
    at /home/project/src/santander/misc/example/node_modules/@angular/compiler/bundles/compiler.umd.js:16967:59
    at Array.forEach (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (/home/project/src/santander/misc/example/node_modules/@angular/compiler/bundles/compiler.umd.js:16967:23)
    at /home/project/src/santander/misc/example/node_modules/@angular/compiler/bundles/compiler.umd.js:17558:60
    at /home/project/src/santander/misc/example/node_modules/@angular/compiler/bundles/compiler.umd.js:16992:81
    at Array.forEach (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (/home/project/src/santander/misc/example/node_modules/@angular/compiler/bundles/compiler.umd.js:16992:37)
    at Object.compileComponentFromMetadata (/home/project/src/santander/misc/example/node_modules/@angular/compiler/bundles/compiler.umd.js:18643:58)
    at ComponentDecoratorHandler.compile (/home/project/src/santander/misc/example/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/component.js:534:34)
    at _loop_2 (/home/project/src/santander/misc/example/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:542:53)
    at TraitCompiler.compile (/home/project/src/santander/misc/example/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:572:21)
    at IvyVisitor.visitClassDeclaration (/home/project/src/santander/misc/example/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/transform.js:51:40)
    at /home/project/src/santander/misc/example/node_modules/@angular/compiler-cli/src/ngtsc/util/src/visitor.js:77:93

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! example@0.0.0 build: `ng build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the example@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yuriy_yakovenko/.npm/_logs/2020-02-12T10_41_09_828Z-debug.log
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.1
Node: 12.13.1
OS: linux x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
Could be related: https://github.com/angular/angular-cli/issues/14663

Regards Yuriy!

**Comment by AndriiDidkivsky** [comment]
Same issue

**Comment by alex3174** [comment]
Same issue

**Comment by Juliojss** [comment]
Same issue

**Comment by sandervanteinde** [comment]
Same issue

**Comment by djleonskennedy** [comment]
@sandervanteinde read carefully

**Comment by slo-ge** [comment]
I had a similar error today. The problem was that I had a broken  definition in any of my templates, which was okay with ng8 compiler but not with ng9. 

```html 

        <div *ngFor="let place of related$ | async as place">
            <app-place [place]="place"></app-place>
        </div>

```

see the `*ngFor` statement, I had to remove the `as place` part, then it worked as expected. 
You may have a similar problem...

**Comment by Juliojss** [comment]
After a week ... I managed to solve this problem. I changed the <names> of the variables in NgFor. In my case, the variable was 'i'

**Comment by kavindraD** [comment]
I have same issue with ngFor as i am using like 
*ngFor="let i of itemInfo; let i=index " 
With angular 7 its not throwing any error (as we can't declare same variable name using let in same scope) but with 9 its causes above error.
So update that to -
*ngFor="let i of itemInfo; let j=index "
resolve this error.

**Comment by n4bb12** [comment]
@kavindraD you're declaring the variable `i` twice.

```html
*ngFor="let i of itemInfo; let i=index "
            A                  A
```

Try changing it to

```html
*ngFor="let info of itemInfo; let i=index "
```

**Comment by kavindraD** [comment]
Its done @n4bb12 , my concern to get some information with error stack trace so that we can easily update such code. 

Thank you for your quick response @n4bb12 .

**Comment by bryanrideshark** [comment]
Thankfully Ivy seems to be reporting poor programming practices in HTML templates. I'm very happy with this behavior, the only thing that could be improved is the error message.

**Comment by petebacondarwin** [comment]
Agreed - this was also reported here https://github.com/angular/angular/issues/35186 and there is a fix coming here https://github.com/angular/angular/pull/35674
