### ISSUE TITLE
Improve docs for the `ngDefaultControl` directive

### ISSUE THREAD

**Issue by astrobob** [angular/angular#35375]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/material.

### Is this a regression?

Yes, the previous version in which this bug was not present was: ....

### Description

Before I could use the following syntax

      <div formArrayName="roles">
        <div *ngFor="let role of editUserForm?.get('roles')?.controls; let i=index">
          <br />
          <mat-checkbox [formControl]="role">{{ rolesOptions[i]?.name }}</mat-checkbox>
        </div>
      </div>

With the new version of Angular 9, the following message appears:
ERROR Error: No value accessor for form control with unspecified name attribute

The only solution I have is to remove mat-checkbox as follow:

      <div formArrayName="roles">
        <div *ngFor="let role of editUserForm?.get('roles')?.controls; let i=index">
          <br />
          <input type="checkbox" [formControl]="role" />{{ rolesOptions[i]?.name }}
        </div>
      </div>

[type="checkbox"]:not(:checked), [type="checkbox"]:checked {
  position: relative;
  opacity: 1;
  pointer-events: all;
  margin-right: 10px;
}

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version: 9.0.0
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by jensweigele** [comment]
Have you tried adding the attribute "ngDefaultControl"? (see: https://stackoverflow.com/questions/46465891/what-is-ngdefaultcontrol-in-angular)

**Comment by azamanaza** [comment]
> Have you tried adding the attribute "ngDefaultControl"? (see: https://stackoverflow.com/questions/46465891/what-is-ngdefaultcontrol-in-angular)

This fixed it for me as well. But I believe it should be a default behavior.

**Comment by AndrewKushnir** [comment]
Thanks for creating this ticket. As it was mentioned in the comments above, adding `ngDefaultControl` should help.

I think it'd be great to add more docs for `ngDefaultControl` directive, so I've updated the title to mention that.
