### ISSUE TITLE
CLI builder examples are not OS agnostic

### ISSUE THREAD

**Issue by bampakoa** [angular/angular#35373]
# 📚 Docs or angular.io bug report

### Description

The examples of the CLI Builders in the Techniques section are highly dependent on the Linux operating system. Particularly the commands `ls` and `touch` are not recognized in the Windows environment. Since not all of us work on a Linux machine, it would be great if it could be updated to use an OS agnostic example.

### What's the affected URL?**
https://angular.io/guide/cli-builder

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Anything else relevant?

I would be more than happy to help with this. I have already created a CLI builder for the needs of our company that injects a script tag in the `index.html`. You can find more details [here](https://www.npmjs.com/package/ng-builder-google-maps). I think that this is a good case for a simple example on how to create a builder. Let me know your thoughts 🙏

**Comment by dblVs** [comment]
@bampakoa it's depending on shell not the OS. You can use native linux shell on windows as well. That aside this repo is for angular issues, not CLI.

**Comment by JoostK** [comment]
This repo is the correct place for angular.io docs reports.

**Comment by dblVs** [comment]
@JoostK should the CLI be moved in this repo then?

**Comment by JoostK** [comment]
@dblVs let's not go into that in this thread, as it's not relevant for this issue.

**Comment by dgp1130** [comment]
Taking this on for the docs fixit. We don't have any exiting infra for showing Linux/Mac/Windows commands and letting users flip between them, however this doc doesn't really need that since the example is just invoking arbitrary subcommands. I'll see if I can come up with a better example which isn't platform-dependent to begin with.
