### ISSUE TITLE
is not added html component dynamically

### ISSUE THREAD

**Issue by Ohunjon** [angular/angular#35377]
hi everyone! i am using angular v7 - and now I am trying to add html element to component but it is added but (not showing correctly or ignored style .. ) ; 
(for example -- I want to add img html element inside my div element on click button)
I try like this :
  $(this.mydivcontent.nativeElement).append(htmlElement);
    this.mydivcontent.nativeElement.innerHTML = htmlElement;

 ... and i added  
  encapsulation: ViewEncapsulation.None,
still not working, I searched but i could not find any workfull variant
Please help me  ... 
thanks in advance

**Comment by mlc-mlapis** [comment]
@Ohunjon You should not modify those DOM parts which are under Angular abstraction model control. It's simply not a way to go.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
