### ISSUE TITLE
running an app in a webworker

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#3537]
I am not sure if I use the npm distribution and I set up an app using web workers, do I need the [zone-microtask-web-workers.js](https://github.com/angular/angular/blob/master/modules/examples/src/assets/zone-microtask-web-workers.js) that is used in the examples folder?

Because I am a bit confused about [SCRIPTS.js](https://github.com/angular/angular/blob/master/tools/broccoli/js-replace/SCRIPTS.js) `importScripts` which does import the script I mentioned above and I cannot seem to find it within the npm distribution.

**Comment by jteplitz602** [comment]
Glad to hear you're working on a WebWorker app! WebWorker support is still a work in progress, but I'd be more than happy to help you out with it.

We try to keep all github issues directly related to issues with the code, so can you please repost this on our forum (https://groups.google.com/forum/m/?fromgroups#!forum/angular), and I'll help you out there :)

**Comment by rolandjitsu** [comment]
@jteplitz602 yeah, I was thinking I should have an example app running in a web worker. Great, I already started implementing on an existing sample [app](https://github.com/rolandjitsu/ng2-play), but the Router seems to not be working.

I'll post a question on the forum, hope you'll be able to help.
