### ISSUE TITLE
Redirect to lazy loaded module

### ISSUE THREAD

**Issue by Akxe** [angular/angular#35370]
# 🐞 bug report

### Affected Package

* @angular/routing

### Is this a regression?

No, but it was bug even before #32814

### Description

Having a lazily routed module that gets to be redirected to ends in the `Maximum call stack` error.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-issue-repro2-yjywh8

## 🔥 Exception or Error
<pre><code>
ERROR RangeError: Maximum call stack size exceeded
    at MergeMapSubscriber.OuterSubscriber.notifyError (OuterSubscriber.ts:16)
    at InnerSubscriber._error (InnerSubscriber.ts:21)
    at InnerSubscriber.Subscriber.error (Subscriber.ts:115)
    at MapSubscriber.Subscriber._error (Subscriber.ts:145)
    at MapSubscriber.Subscriber.error (Subscriber.ts:115)
    at CatchSubscriber.Subscriber._error (Subscriber.ts:145)
    at CatchSubscriber.Subscriber.error (Subscriber.ts:115)
    at CatchSubscriber.error (catchError.ts:121)
    at TapSubscriber._error (tap.ts:126)
    at TapSubscriber.Subscriber.error (Subscriber.ts:115)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
const routes: Routes = [
	{
		path: '',
		redirectTo: 'lazy',
		pathMatch: 'full',
	},
	{
    path: 'lazy',
		loadChildren: () => import('./lazy.module').then(m => m.LazyModule),
	},
];
</code></pre>

**Anything else relevant?**
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.1
Node: 12.6.0
OS: win32 x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```

**Comment by sacgrover** [comment]
This is not an angular issue. There were no RoutingModule in  LazyModule. After adding it, It's working fine 
https://stackblitz.com/edit/angular-issue-repro2-nepwlb

**Comment by Akxe** [comment]
@sacgrover I'll look into it more tomorrow. Keep it open just till then thanks

**Comment by Akxe** [comment]
@sacgrover Why? Why does it need that? I liked my routes in one file :/

Also, the call stack error should be prevented and it should be presented to user in some more understandable way.

**Comment by sacgrover** [comment]
> @sacgrover Why? Why does it need that? I liked my routes in one file :/
> 
> Also, the call stack error should be prevented and it should be presented to user in some more understandable way.

@Akxe In your lazy module, there is no route defined. You can do that in a single file but you have to define the routes to tell which component to load.

**Comment by Akxe** [comment]
@sacgrover any documentation or resource to read it up? Also, why isn't the default single route as default? 

```
RouterModule.forChild([{
  path: '',
  pathMatch: 'full',
  component: LazyComponent
}]),
```
----
Will the error get handeled, or shall we close this?

**Comment by sacgrover** [comment]
Let it be open until a member of this project reply back.

**Comment by atscott** [comment]
The error message here should probably be improved, but like @sacgrover pointed out, the issue is that you have no routes set up for the lazy loaded module. Adding the `RouterModule.forChild` in the lazy module resolves this issue.

**Comment by spock123** [comment]
Just for the sake of it I'll chime in: if you find yourself needing to import tons of modules in your lazy loaded modules, consider creating one "LazyLoadedRootModule" or something which does all that.

Then in your lazy loaded modules you only load in one module - the "LazyLoadedRootModule"

Just don't bloat that module with tons of stuff you "might" need in the lazy loaded modules..

**Comment by indraraj26** [comment]
I had similar error can we expect this fix in ng11

**Comment by Akxe** [comment]
The issue is that the error is not helpful at all. You need to create a routing module for the lazy-loaded module too.

Example of lazy module:
```ts
@NgModule({
    declarations: [
        OfferingsComponent,
    ],
    imports: [
        CommonModule,
        MatToolbarModule,
        CdkTableModule,
        RouterModule.forChild([
            {
                path: '',
                component: OfferingsComponent,
                pathMatch: 'full',
            },
        ]),
    ],
})
export class OfferingsModule { }
```

-----

For the Angular team:

The absence of routing module in the lazy-loaded module should result in:
* An runtime error like `The module {{moduleName}} does not have defined routes`. Along with this, there should be this exact error message in documentation (for google searches), that would immediately tell the user how to fix it.

Along with possible fixes: 
* Automatic fix by generating the default route with path `*` and component... named with the same prefix as the module? Bit a stretch, but doable and probably reasonable.
* Compile error from the `angular-language-service`.
  * If the module is referenced in a routing module, it must define the routing module. The syntax is very specific and should not be hard to find.
