### ISSUE TITLE
Localized bundle generation failed: Unexpected messageParts for `$localize` (expected an array of strings).

### ISSUE THREAD

**Issue by miki995** [angular/angular#35376]
# 🐞 bug report

### Affected Package
@angular/*

 The issue is caused by package @angular/localized

### Is this a regression?

 No, we didn't have this fetaure in angular 89: ....

### Description

 
When I run ng build --configuration=production --localize I get this error:
`Localized bundle generation failed: Unexpected messageParts for `$localize` (expected an array of strings).
`

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-issue-repro2-r8en56.

## 🔥 Exception or Error
<pre><code>

 `Localized bundle generation failed: Unexpected messageParts for `$localize` (expected an array of strings).
`

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular 9
</code></pre>

**Anything else relevant?**

If I set optimizer to false in configuration production everything works perfectly

**Comment by kuijt001** [comment]
I've ran into the exact same problem earlier. Running the ng build command with --verbose showed a lot of warnings and errors on the TerserPlugin part of the build. 

Eventually I stumbled upon this issue: [Issue 13939](https://github.com/angular/angular-cli/issues/13939)
This comment in specific was what I needed to get it fixed: [Comment](https://github.com/angular/angular-cli/issues/5618#issuecomment-450151214)

By default the memory limit in Node. js is 512 mb, to solve this issue you need to increasing the memory limit use command —- max-old-space-size . 

I've added the following line to my package.json
`"ng-high-memory": "node --max_old_space_size=8000 ./node_modules/@angular/cli/bin/ng",`

From the comment on [Issue 13939](https://github.com/angular/angular-cli/issues/13939) :

> When you use have that script, you can use `npm run ng-high-memory --` followed by the arguments instead of `ng` inside that project. Always use the double dash before arguments, otherwise they might not be parsed correctly.

**Comment by miki995** [comment]
That is not solution, that is hack :D. If someone can answer if this is a bug inside angular?

**Comment by miki995** [comment]
@petebacondarwin maybe you can have a look here?

**Comment by PierreDuc** [comment]
Setting the optimizer to false "resolves" this indeed, the `--max_old_space_size` does not work for me. I tried to dig a bit deeper into what might be causing it and the place where it expects an array of strings, it actually receives an object which looks a bit like this:

```
{
  "type":"LogicalExpression",
  "start":2396140,
  "end":2396472,
  "loc": {
    "start": {
      "line":1,
      "column":2396140
    },
    "end":{
      "line":1,
      "column":2396472
    }
  },
  "left": {
    "type":"Identifier",
    "start":2396140,
    "end":2396142,
    "loc": {
     // etc etc etc, lots of more info
    "extra":{
      "rawValue":":␟999aec8f47d7
6b8e0bbd0dd4e13170bb1b687e93␟867601126266312330:The actual string that's inside the i18n tag",
   // etc etc etc, even more stuff
}
```
The faulting i18n tag does not have anything special, and when I comment out the tag it will just fail over another one in a completely different component. I've tried to look for a pattern between them, but couldn't find any.

**Comment by petebacondarwin** [comment]
Can you provide a reproduction of the problem? Ideally a runnable project or at least steps in how to produce one. It is difficult to debug without this

**Comment by petebacondarwin** [comment]
It sounds to me that one of the more aggressive terser optimisations is modifying the `$localize` calls in a way that the `@angular/localize` tooling cannot understand. Is it possible to build the app without localization and then find where there are instances of `$localize` in the built JS files?

**Comment by miki995** [comment]
> Can you provide a reproduction of the problem? Ideally a runnable project or at least steps in how to produce one. It is difficult to debug without this

@petebacondarwin It was mentioned at beginning, in **Minimal Reproduction section**, the url is [this](https://stackblitz.com/edit/angular-issue-repro2-r8en56)

**Comment by petebacondarwin** [comment]
@miki995 - I looked at that Stackblitz project but I couldn't see how it reproduces your error. There are no templates that use `i18n`, there is no code that calls `$localize` and moreover the dependencies on Angular are at version 6.1.9. How do I reproduce the actual error that you are reporting?

**Comment by miki995** [comment]
@petebacondarwin true, the stackblitz that angular github issue creator offered, goes to angular 6, I will create repo on github, just few minutes please :D

**Comment by PierreDuc** [comment]
@petebacondarwin In our current project we do not yet use the $localize calls, and only import the `import '@angular/localize/init';` in the polyfills. So there are no dynamic translations yet, but we still get the error. It's difficult to make a reproduction, because it happens at random places where there is an i18n attribute

**Comment by petebacondarwin** [comment]
@PierreDuc - wherever there is an `i18n` tag in a template, the Angular compiler now creates a call to `$localize`. I assume that you are sure that the versions of `@angular/localize`, `@angular/compiler`, `@angular/compiler-cli` all line up?

**Comment by PierreDuc** [comment]
This is the output for `ng --version`. On a side note, same thing happens on the CI build and on linux, if that's relevant :)

```
PS C:\projects\xxx> ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.2
Node: 12.13.0
OS: win32 x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.2
@angular-devkit/build-angular      0.900.2
@angular-devkit/build-optimizer    0.900.2
@angular-devkit/build-webpack      0.900.2
@angular-devkit/core               9.0.2
@angular-devkit/schematics         9.0.2
@angular/cdk                       9.0.0
@angular/cli                       9.0.2
@angular/fire                      6.0.0-rc.1
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.0.0
@angular/material-moment-adapter   9.0.0
@ngtools/webpack                   9.0.2
@schematics/angular                9.0.2
@schematics/update                 0.900.2
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
```

**Comment by petebacondarwin** [comment]
OK so we need to work out what the optimizer is doing to the compiled `$localize` code that is stopping the translation tooling from reading it correctly.

**Comment by PierreDuc** [comment]
This is the compiled part of main.js where optimization is set to false, and where the localization fails when it's set to true. Doesn't really look anything different then other translation parts in the file, but perhaps you can see something, or give me some pointers where else I could look:

```
var I18N_0;
if (typeof ngI18nClosureMode !== "undefined" && ngI18nClosureMode) {
    var MSG_EXTERNAL_867601126266312330$$_________SRC_SOME_PATH_TO_A_COMPONENT_TS__1 = goog.getMsg("The actual string that's inside the i18n tag");
    I18N_0 = MSG_EXTERNAL_867601126266312330$$_________SRC_SOME_PATH_TO_A_COMPONENT_TS__1;
}
else {
    I18N_0 = "The actual string that's inside the i18n tag";
}
function SomeComponent_div_11_Template(rf, ctx) {
    if (rf & 1) {
        _angular_core__WEBPACK_IMPORTED_MODULE_2__["ɵɵelementStart"](0, "div", 7);
        _angular_core__WEBPACK_IMPORTED_MODULE_2__["ɵɵi18n"](1, I18N_0);
        _angular_core__WEBPACK_IMPORTED_MODULE_2__["ɵɵelementEnd"]();
    }
}
```

**Comment by PierreDuc** [comment]
Another small update. When you set the optimizer to true, but you set the `buildOptimizer` to false, the bundling and localize works and you do get a minified bundle with the terser plugin (because that still spits out a great amount of warnings), with the proper localization. So it seems like the issue is in the build optimizer.

**Comment by petebacondarwin** [comment]
This line in your output:

```
I18N_0 = "The actual string that's inside the i18n tag";
```

Is after the compile-time translation has occurred, which removes the `$localize` call and just leaves the translated (or not in this case) text.

**Comment by petebacondarwin** [comment]
Can you debug into the point where the exception is thrown (as I assume you did earlier to get the AST), and then go up one level, which should be inside `unwrapMessagePartsFromLocalizeCall(call)`. Then can get hold of the result of `call.getSource()`, which should contain the source code that is being processed. In there can you look for calls to `$localize`?

**Comment by PierreDuc** [comment]
The `call.getSource()` returns:

```
$localize(iR||(GI=[":\u241f999aec8f47d76b8e0bbd0dd4e13170bb1b687e93\u241f867601126266312330:The actual string that's inside the i18n tag"],WI=[":\u241f999aec8f47d76b8e0bbd0dd4e13170bb1b687e93\u241f867601126266312330:The actual string that's inside the i18n tag"],Object.defineProperty?Object.defineProperty(GI,"raw",{value:WI}):GI.raw=WI,iR=GI))
```
I don't know how to make that more readable for you ;)

**Comment by petebacondarwin** [comment]
Awesome that is perfect. Let me dig into that.

**Comment by petebacondarwin** [comment]
So this can be written (slightly more readably) as:

```
$localize(
  iR||
  (
    GI=[
      ":\u241f999aec8f47d76b8e0bbd0dd4e13170bb1b687e93\u241f867601126266312330:The actual string that's inside the i18n tag"
    ],
    WI=[
      ":\u241f999aec8f47d76b8e0bbd0dd4e13170bb1b687e93\u241f867601126266312330:The actual string that's inside the i18n tag"
    ],
    Object.defineProperty?
      Object.defineProperty(GI,"raw",{value:WI}):
      GI.raw=WI,iR=GI
  )
)
```

which is obviously TypeScript/terser/build-optimizer's latest incantation of how to transform:

```
$localize `:\u241f999aec8f47d76b8e0bbd0dd4e13170bb1b687e93\u241f867601126266312330:The actual string that's inside the i18n tag`
```

into ES5 code.

We have a test for a slightly similar arrangement in our codebase already:

```
    it('should handle cached helper calls', () => {
      const diagnostics = new Diagnostics();
      const input =
          `$localize(cachedObj||(cachedObj=__makeTemplateObject(['try', 'me'],['try', 'me'])),40 + 2)`;
      const output = transformSync(input, {plugins: [makeEs5TranslatePlugin(diagnostics, {})]}) !;
      expect(output.code).toEqual('"try" + (40 + 2) + "me";');
    });
```

But this has another level of complication...  I'll put together a PR.

**Comment by PierreDuc** [comment]
Great, thanks for the quick responses and resolve time :)

**Comment by PierreDuc** [comment]
I've applied your fix and it works for our case, everything is compiled properly now, thanks again
