### ISSUE TITLE
Input with name "class" and host binding for class have a different behaviour in ng8 and ng9

### ISSUE THREAD

**Issue by wis-ekubesh** [angular/angular#35383]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?
Yes, in angular before version 9 this bug was not presented.
Before ng9 @Input properties don't be affected with host.class.

### Description

```
@Component({
  ...
  host: { class: 'attributes' },
})
export class SomeComponent {
  @Input('class')
  public klass: string;
}
```

In angular before ng9 for pice of code above we had a bit different behaviour.

In case, when we use our component like `<some-component class="test"></some-component>` for angular 8, after ngOnInit, we had only "test" in "klass" variable. But for angular 9 we have concatenated input property with host.class and now it equals klass === "attributes test" for example above.

It looks strange and logically at the same time. Possibly, there is feature of Ivy, but I want to clarify and be sure that its not a bug of Ivy and ng9.

My examples for reproduction is totally the same with only one thing different - angular version.

## 🔬 Minimal Reproduction
For angular version 8 and early: https://ng-run.com/edit/urRUMm5njGb9EAOsgtuh

For angular version 9: https://ng-run.com/edit/y5YZ2sHv9uC0N900mHAz

## 🔥 Exception or Error
I expect that it works like before. So, @Input('class') doesn't affected with host.class

## 🌍  Your Environment

**Angular Version:**

angular 8.2.14 and angular 9.0

**Comment by ericmartinezr** [comment]
Probably related https://github.com/angular/angular/pull/34938, otherwise ignore.

**Comment by mhevery** [comment]
Same issue as (https://github.com/angular/angular/issues/35577)

**Comment by mhevery** [comment]
See for explanation:
https://github.com/angular/angular/blob/master/packages/core/src/render3/instructions/styling.ts#L253-L267

**Comment by kara** [comment]
Discussed offline: we are going to discuss this one more internally.

**Comment by pkozlowski-opensource** [comment]
A slightly simpler / cleaned up repro to make it easier to understand: https://ng-run.com/edit/VdKnp2SsVSCHOJPvpuA7?open=app%2Fapp.component.ts
