### ISSUE TITLE
Using the CommonModule for NgClass inside an Angular elements setup using Ivy with renderComponent yields an "Uncaught Error: Cannot inject Renderer2 when the application uses Renderer3!"

### ISSUE THREAD

**Issue by Armenvardanyan95** [angular/angular#35382]
# 🐞 bug report

### Affected Package
The issue is probably caused by package @angular/common

### Is this a regression?

This is an entirely new problem

### Description

 A clear and concise description of the problem...

I was trying to migrate an existing Angular Web Component to a new setup with Ivy using the ɵrenderComponent function. While for the most part it worked, the usage of `ngClass` completely breaks the custom element. I suppose it comes from this [line](https://github.com/angular/angular/blob/master/packages/common/src/directives/ng_class.ts#L49), but I can be very wrong. If I understand correctly, `NgClass` uses the `Renderer2` class for setting and removing class names, but somehow in Ivy Renderer2 should not be used (or whatever). So this breaks existing functionality.

## 🔬 Minimal Reproduction
[This repository](https://github.com/Armenvardanyan95/ng-class-issue-reproduction) contains a minimal reproduction of the issue. It is very straightforward: It contains  an Angular component, a minimal web component setup that just renders the Angular component using the ɵrenderComponent function, and a module that imports the Angular CommonModule. The import works fine. Other directives from the module like NgForOf seem to work fine, and only NgClass breaks, as far as I have seen. The build finishes without exceptions. 

## 🔥 Exception during runtime:
<pre><code>
core.js:15511 Uncaught Error: Cannot inject Renderer2 when the application uses Renderer3!
    at getOrCreateRenderer2 (core.js:15511)
    at injectRenderer2 (core.js:15527)
    at push../node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js.Renderer2.__NG_ELEMENT_ID__ (core.js:27320)
    at getOrCreateInjectable (core.js:5361)
    at Module.ɵɵdirectiveInject (core.js:20759)
    at NodeInjectorFactory.NgClass_Factory [as factory] (common.js:3878)
    at getNodeInjectable (core.js:5598)
    at instantiateAllDirectives (core.js:12645)
    at createDirectivesInstances (core.js:11881)
    at Module.ɵɵelementStart (core.js:20943)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular: 9.0.0
... common, compiler, compiler-cli, core, elements
... language-service
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

The issue is not browser-specific

**Comment by pkozlowski-opensource** [comment]
`renderComponent` is highly experimental API that we don't want to open up publicly / support at the moment - for now this API just has too many limitations (as you've just noticed...). 

We are debating good user story with `renderComponent` but as today it is not ready for the prime time. You are free to play with it and explore possibilities but this is not what we want to advertise / support at the moment. 

Stay tuned to the ironed-out story :-)
