### ISSUE TITLE
NullInjectorError: No provider for TestComponentRenderer!

### ISSUE THREAD

**Issue by zabomate** [angular/angular#35386]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/* Unit-testing

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.*

### Description

 We have upgraded our project from angular 8 to 9 and everything went smooth until the unit test part. We have about 1200 unit tests in the project and If we run all of the unit tests a bunch of them fails with this error message:
`NullInjectorError: No provider for TestComponentRenderer`  
The problem is that when I run only a smaller parts of the tests about 100 at the time everything is fine and every tests pass. When all of the tests are running the number of failed tests varies and the tests which fails also varies.
Do you have any idea what can cause this type of error?

## 🔥 Exception or Error
<pre><code>
NullInjectorError: R3InjectorError(CompilerModule)[TestComponentRenderer -> TestComponentRenderer]: 
  NullInjectorError: No provider for TestComponentRenderer!
error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'TestComponentRenderer', 'TestComponentRenderer' ] })
    at <Jasmine>
    at NullInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm5/core.js:902:1)
    at R3Injector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm5/core.js:11181:1)
    at R3Injector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm5/core.js:11181:1)
    at NgModuleRef$1.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm5/core.js:24104:1)
    at TestBedRender3.inject (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm5/testing.js:1959:1)
    at TestBedRender3.createComponent (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm5/testing.js:2001:1)
    at Function.TestBedRender3.createComponent (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm5/testing.js:1892:1)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.1
Node: 13.2.0
OS: win32 x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by splincode** [comment]
please create github repo with reproduce

**Comment by levsim2016** [comment]
Well, i have this error too on windows 10, but tests run by jest. I don't think that problem with jest, cause my сolleagues on mac os x use jest, and all tests run perfectly

**Comment by pkozlowski-opensource** [comment]
Sadly we haven't heard back with the reproduce scenario so it is impossible for us to investigate / act on the issues. As such I'm going to close it for now. Please open a new issue if / when you've got a reproduce scenario.
