### ISSUE TITLE
ChangeDetectionStrategy.OnPush - subscribe with unsubscribeAll, take time to reflect change on screen

### ISSUE THREAD

**Issue by GlauberF** [angular/angular#35391]
# 🐞 bug report
when I subscribe to the following lines below, it takes time to reflect the change on screen.
```javascript
this.result$
            .pipe(takeUntil(this._unsubscribeAll))
            .subscribe(res => {
                this.noResultsFound = !(res && res.length);
            })
```

and re remove the `.pipe(takeUntil(this._unsubscribeAll))`, the change reflects correctly.

**Note** my ngOnDestroy
```javascript
ngOnDestroy(): void {
        super.ngOnDestroy();

        // Unsubscribe from all subscriptions
        this._unsubscribeAll.next();
        this._unsubscribeAll.complete();
    }
```

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 8.3.23
Node: 10.15.3
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.23
@angular-devkit/build-angular              0.803.23
@angular-devkit/build-optimizer            0.803.20
@angular-devkit/build-webpack              0.803.23
@angular-devkit/core                       8.3.23
@angular-devkit/schematics                 8.3.23
@angular/cdk                               8.2.3
@angular/cli                               8.3.23
@angular/flex-layout                       8.0.0-beta.27
@angular/material                          8.2.3
@angular/material-moment-adapter           8.2.3
@ngtools/webpack                           8.3.23
@nguniversal/express-engine                8.2.6
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        8.3.23
@schematics/update                         0.803.23
rxjs                                       6.5.4
typescript                                 3.5.3
webpack                                    4.39.2

**Comment by vladimiry** [comment]
What about replacing the `takeUntil` stuff with explicit unsubscribing? Like:

```typescript
import {Subscription} from "rxjs";

@Component
export class MyComponent {
  private readonly onDestroyCleanupSubscription = new Subscription();

...

  this.onDestroyCleanupSubscription.add(
    this.result$.subscribe(res => {
      this.noResultsFound = !(res && res.length);
    }),
  );

...
  
  ngOnDestroy(): void {
    super.ngOnDestroy();
    this.onDestroyCleanupSubscription.unsubscribe();
  }
}

```

**Comment by mstawick** [comment]
If you're using OnPush, shouldn't you mark your component for change detection? Ie. inject `ChangeDetectorRef` and invoke `markForCheck()`? Otherwise your change will be visible only if something else triggers change detection.

**Comment by vladimiry** [comment]
> If you're using OnPush, shouldn't you mark your component for change detection? Ie. inject ChangeDetectorRef and invoke markForCheck()

Normally yes, direct change detection triggering is needed. Another option is to use async pipe in the template, like (async pipe [marsk for check internally](https://github.com/angular/angular/blob/c3b5ce4bb27e964d1a9472a3b9d82d172c038872/packages/common/src/pipes/async_pipe.ts#L143) when new value comes into the stream):
```html
<ng-template *ngIf="(this.result$ | async)?.length; else noResultsFoundTpl">
...
<ng-template>
<ng-template #noResultsFoundTpl>
...
</ng-template>
```

**Comment by GlauberF** [comment]
ok, I know I can use `markForCheck ()`, but the initial problem is another, why I need to do a markForCheck, when I use the idea of `.pipe (takeUntil (this._unsubscribeAll))` and if removing this, everything works perfectly.

In other words, the problem is in making a subscribe and then in ngOnDestroy, unsubscribe.

I don't think it would be an interesting approach to use `markForCheck ()`, because I'm using these things inside an autocomplete component, imagine that every time the user does a search, I will do a `markForCheck ()`.

**Comment by pkozlowski-opensource** [comment]
I'm going to close this issue as we haven't heard back with a reproduce scenario.
