### ISSUE TITLE
Incorrect typings for JitCompilerFactory

### ISSUE THREAD

**Issue by timsawyer** [angular/angular#35397]
# 🐞 bug report

### Affected Package
@angular/platform-browser-dynamic

### Is this a regression?
Unsure

### Description
According to docs, defaultOptions is a required parameter to the the constructor of JitCompilerFactory. However, typings define no parameters and cause error. 
https://angular.io/api/platform-browser-dynamic/JitCompilerFactory

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-5uedpx

## 🔥 Exception or Error
<pre><code>
Expected 0 arguments, but got 1.
</code></pre>

## 🌍  Your Environment
<pre><code>
Angular CLI: 9.0.1
Node: 12.14.1
OS: darwin x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core
... elements, forms, language-service, material
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.1
@angular-devkit/build-angular      0.900.1
@angular-devkit/build-ng-packagr   0.900.1
@angular-devkit/build-optimizer    0.900.1
@angular-devkit/build-webpack      0.900.1
@angular-devkit/core               9.0.1
@angular-devkit/schematics         9.0.1
@angular/cli                       9.0.1
@angular/fire                      5.4.2
@ngtools/webpack                   9.0.1
@schematics/angular                9.0.1 (cli-only)
@schematics/update                 0.900.1
ng-packagr                         9.0.0
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.38.0

</code></pre>

**Comment by alxhub** [comment]
`JitCompilerFactory`'s constructor isn't declared in the `.d.ts` file at all, because it's a private API (most constructors in Angular are, because classes are created with DI instead of by direct constructor call).

It is an unfortunate aspect of our .d.ts generation though that `@internal` constructors are removed rather than transformed to `private`. That's something we should take a look at.
