### ISSUE TITLE
benchpress: integrate with iOS Safari

### ISSUE THREAD

**Issue by tbosch** [angular/angular#354]
[Appium](http://appium.io/) and [iOS Driver](https://github.com/ios-driver/ios-driver) already support reporting performance logs for iOS Safari.

However, forcing gc is missing in both projects.

For Appium we should actually contribute a little more:
- update [ios-webkit-debug-proxy](https://github.com/google/ios-webkit-debug-proxy), as it throws errors right now when using ios8 and needs to be periodically restarted (see [this workaround in appium](https://github.com/appium/appium/blob/master/bin/ios-webkit-debug-proxy-launcher.js) )

**Comment by tbosch** [comment]
Also need to control CPU frequency (set it to a fixed value) and prevent the device from sleeping (similar to how we did it with Android)

**Comment by tbosch** [comment]
The initial idea was to send a command like `collectGarbage` via [WebInspectorService](https://github.com/ios-driver/libimobiledevice-wrapper/blob/master/src/main/java/org/libimobiledevice/ios/driver/binding/services/WebInspectorService.java) of libimobiledevice to the iOS device. This command exists in the [chrome remote debug](https://chromium.googlesource.com/chromium/blink/+/master/Source/devtools/protocol.json).

BUT: It does not seem to exist in the webkit remote debugger protocol ([here](https://github.com/WebKit/webkit/blob/master/Source/WebInspectorUI/Versions/Inspector-iOS-8.0.json) and [here](https://github.com/WebKit/webkit/tree/master/Source/JavaScriptCore/inspector/protocol)).

**Comment by tbosch** [comment]
@juliemr Do you know of some other way? Or a person that we could talk to?

**Comment by tbosch** [comment]
Initial version with ios-driver is almost working.

**Comment by tbosch** [comment]
For forcing gc, maybe we can get to https://github.com/WebKit/webkit/blob/master/Source/WebCore/bindings/js/GCController.h somehow...

**Comment by splincode** [comment]
@tbosch Is the issue relevant?
