### ISSUE TITLE
`extractCss` adds unclosed `link` tag, breaks XHTML index pages

### ISSUE THREAD

**Issue by MilesBHuff** [angular/angular#35404]
# 🐞 bug report

### Affected Package

`angular.json` (Webpack)

### Is this a regression?

No

### Description

The `extractCss` setting in `angular.json` adds an unclosed `link` tag to the DOM.  This breaks XHTML index pages.

## 🔬 Minimal Reproduction

1. In `angular.json`, set `extractCss` to `true` for all builds.
2. Make sure your `index.xhtml` file is valid polyglot HTML5/XML.
3. Start the dev server.

## 🔥 Exception or Error

    XML Parsing Error: mismatched tag. Expected: </link>.
    Location: http://localhost:4200/
    Line Number ##, Column 45:
        <link rel="stylesheet" href="styles.css"></head>

## 🌍  Your Environment

**Angular Version:** `9.0.0`

**Anything else relevant?** No, this issue's pretty simple.

**Comment by santoshyadav198613** [comment]
This issue should be raised in CLI, but what i can see is polyglot HTML5/XML does not allow an self-closing tags.
So this is not even a bug, should me marked as feature.

**Comment by MilesBHuff** [comment]
Where do you see that polyglot XHTML5 doesn't allow self-closing tags?  I use them all the time without issue.  The `link` tag in this issue is not self-closing -- that's what the problem is.

I'll move the issue to Angular/CLI.

**Comment by MilesBHuff** [comment]
https://github.com/angular/angular-cli/issues/16964
