### ISSUE TITLE
Ivy: ChangeDetection not running on transplanted views

### ISSUE THREAD

**Issue by antoinebrault** [angular/angular#35400]
# 🐞 bug report

### Affected Package
ivy in 9.0.x

### Is this a regression?
Yes, it fails to update templateRef in ivy, but works in VE.

### Description
TemplateRef doesn't update in a dynamic Component created by an external js lib (ag-grid, using appendChild) in Ivy. (exemple 1)

TemplateRef doesn't update in a child Component of an OnPush Component in Ivy. (exemple 2)

exemple 3 & 4 work fine

1. TemplateRef -> Component OnPush -> Component -> dynamic Component with ngTemplateOutlet **(fails)**
2. TemplateRef -> Component OnPush -> Component with ngTemplateOutlet **(fails)**
3. TemplateRef -> Component -> Component OnPush with ngTemplateOutlet **(works)**
4. TemplateRef -> Component OnPush -> dynamic Component with ngTemplateOutlet **(works)**

## 🔬 Minimal Reproduction
1. https://stackblitz.com/edit/cdr-ivy
2. https://stackblitz.com/edit/cdr-ivy-2
3. https://stackblitz.com/edit/cdr-ivy-3
4. https://stackblitz.com/edit/cdr-ivy-4

Full example using ag-grid:
https://github.com/antoinebrault/angular-ivy-cdr

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.3
Node: 12.16.0
OS: win32 x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core
... language-service, platform-browser, platform-browser-dynamic
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cli                      9.0.3
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by Achilles1515** [comment]
@mhevery I thought this behavior was ["fixed"](https://github.com/angular/angular/issues/33393)?

**Comment by antoinebrault** [comment]
> @mhevery I thought this behavior was ["fixed"](https://github.com/angular/angular/issues/33393)?

I've been trying to reproduce it without ag-grid, but couldn't. Maybe it's a weird timing/behavior in the lib. 
https://stackblitz.com/edit/ivy-dmawrg

**Comment by antoinebrault** [comment]
@Achilles1515 finally got a simple working example https://stackblitz.com/edit/cdr-ivy

**Comment by kykint** [comment]
Easier example:

**Comment by kykint** [comment]
Easier example https://stackblitz.com/edit/cdr-ivy-4saiuy
There are three components: 
In component1 we declare ng-template and pass it to component2
In component2 we just pass templateRef to component3
in component3 we just show template in ngTemplateOutlet.

After that the change detection will break. 
Wery important note:
component1 and component2 are OnPush strategy and component3 is Default.

WA: Make component3 OnPush strategy and everything works fine

**Comment by antoinebrault** [comment]
@kykint you're right, it could be simpler. 
component 1 (OnPush) -> component 2 (ngTemplateOutlet) doesn't work too.

https://stackblitz.com/edit/cdr-ivy-2

**Comment by antoinebrault** [comment]
@atscott @pkozlowski-opensource Do you guys have any plans on merging the PR soon?
