### ISSUE TITLE
Create guide for debugging with ng

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#35401]
# 📚 Docs or angular.io bug report

### Description

See details here of some
Things we can do https://dev.to/azure/debug-angular-9-in-60-seconds-5h8k

**Comment by kapunahelewong** [comment]
Nice article! Thank you, @johnpapa!

**Comment by aikidave** [comment]
Thanks @johnpapa! I will look into adding this as a tutorial or topic!

**Comment by mgechev** [comment]
Looks like duplicate of https://github.com/angular/angular/issues/35407#issuecomment-1074530265.
