### ISSUE TITLE
Need reference Template Variable To FormControl

### ISSUE THREAD

**Issue by tranthoai** [angular/angular#35403]
- I am working with large and complex Nested Reactive Form. In many case, i want to get reference from Template Variable to Form Control to pass to Function Parametter. But Angular now do not support it. For Example:

test.component.html

<input formControlName="testControl" #test="testControl" />

I knew that, i can pass form FormControlGroup or #test="ngForm" or #test="ngModel" but it's not good in this case. I want to reference to specify FormControl.

Thank you. Many people in my team and in the world also need that Feature. ^^

**Comment by djleonskennedy** [comment]
‘const testControl = this.form.get(“testControl”);’
Close issue, don’t use issue tracker for “ho to ...” use stackoverflow

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by tranthoai** [comment]
Formcontrol in FormGroup, that FormGroup in FormArray, this FormArray in FormGroup (form).
We can not use this.form.get(“testControl”);’
