### ISSUE TITLE
Refresh token functionality

### ISSUE THREAD

**Issue by vinod26** [angular/angular#35406]
Below is the code which i have wrote in interceptor:

if (err.status === 412) { // token expire check
            new Promise((resolve, reject) => {
              this.cachedRequests.push(authReq);
              this.authService.refreshToken();
              resolve(this.cachedRequests);
            }).then((result) => {
              const token = JSON.parse(localStorage.getItem('dj-user_auth')).access_token;
              const setAuthHeader = `bearer ${token}`;
              if (setAuthHeader) {
                // Clone the request to add the new header.
                // Pass on the cloned request instead of the original request.

                if (req.url === 'users/usermanager/resetpassword' ||
                  req.url === 'api/usermanager/user' ||
                  req.url === 'api/lbpadmin/user' ||
                  req.url === 'lbpadmin/resetpassword' ||
                  req.url === 'api/lbpmanagerstaff/list'
                ) {
                  authReq = req.clone({ url: environment.oAuth.ssoUrl + req.url, setHeaders: { 'X-AUTH-TOKEN': setAuthHeader } });
                } else {
                  authReq = req.clone({ url: environment.apiUrl + req.url, setHeaders: { 'X-AUTH-TOKEN': setAuthHeader } });
                }
              } else {
                if (req.url.startsWith('api/change_password')) {
                  authReq = req.clone(
                    {
                      url: environment.apiUrl + req.url,
                      setHeaders: { 'X-AUTH-TOKEN': 'Bearer ' + this.cookieService.get('dj-activation-code') }
                    }
                  );
                } else {
                  authReq = req.clone({ url: environment.apiUrl + req.url });
                }
              }
              return next.handle(authReq);
            }).catch(() => {
              this.authService.logout();
            });

--------------------------------------------------------------------------------------------------------
Refresh token API call

  public refreshToken = () => {
    const refreshTokenData = new RefreshTokenEntity();
    this.http.post(`auth/login`, refreshTokenData.requestFormat)
      .subscribe(
        (res) => {
          this.jwtToken = {
            access_token: res['result'].token,
            expires_in: TOKEN_DATA.expiresIn,
            scope: TOKEN_DATA.scope,
            refresh_token: '',
            token_type: TOKEN_DATA.type,
            'user': ''
          };
          this.getUserToken(this.jwtToken, this.router.url);
          this.setRefreshToken(res['result'].refreshToken);
          window.location.reload();
        },
        (err) => {
        }
      );
  }
---------------------------------------------------------------------------------------
**Problem in above code is that i've to reload the page i.e (window.location.reload())**

How to reload or refresh the component when it this condition comes, But here i don't want to reload the whole page because if i does this whole app will get load, which i don't want, Kindly provide me better and feasible solution.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
