### ISSUE TITLE
Create docs for debugging with ng

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#35407]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please file any Docs or angular.io issues at: https://github.com/angular/angular/issues/new/choose

For the time being, we keep Angular AIO issues in a separate repository.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by johnpapa** [comment]
Here is another article I wrote with debugging examples. Feel feee to use any of this that may be helpful. https://dev.to/azure/debugging-angular-9-interacting-with-components-5053

**Comment by ajitsinghkaler** [comment]
@kapunahelewong @aikidave can I take this one

**Comment by kapunahelewong** [comment]
Thanks for volunteering, @ajitsinghkaler. I'll have to defer to @aikidave on this one.

**Comment by kapunahelewong** [comment]
Status: Docs team needs to determine where to add this into project list.

**Comment by aikidave** [comment]
Thanks for this! The blog you linked to would make great source material for a tutorial, I think! I'll investigate putting that together. I can do something similar to what we did for this tutorial, if that meets with your approval, @johnpapa:

https://angular.io/guide/routing-with-urlmatcher

**Comment by mgechev** [comment]
We're currently using these APIs in Angular DevTools, which is our recommendation for debugging apps. I'd suggest to keep the `ng` methods outside the docs for now to not grow the perceived API surface.
