### ISSUE TITLE
Testability.findProviders() returning [] always

### ISSUE THREAD

**Issue by Coly010** [angular/angular#35418]
# 🐞 bug report

### Affected Package

`@angular/core/src/testability`

### Is this a regression?

In previous version, `ng.probe` had a method of getting the injected providers for the app
```ts
const rootElements = window.ng.probe(this.window.getAllAngularRootElements()[0]);
const providers = rootElements.injector.view.root.ngModule._providers;
```

### Description

With Ivy, `ng.probe` has been removed in favour of the Testability class:
https://github.com/angular/angular/blob/master/packages/core/src/testability/testability.ts

Majority of this works perfectly. 

However, the method `findProviders` is yet to be implemented.
https://github.com/angular/angular/blob/d6bc63fa38b6a55073118a8b5640252317419856/packages/core/src/testability/testability.ts#L221

With `ng.probe` removed, is there an alternative method to getting these providers at runtime from external JS or do we have to wait until the `findProviders` method is implemented?

**Comment by DanWahlin** [comment]
I know it’ll take some time to get findProviders() implemented and pushed out. In the meantime is there a recommended workaround given that ng.probe() was removed with v9 and Ivy? This change breaks functionality in a library I publish so a “band aid” fix is fine in the short-term. In sum, I need a way to get to global providers like Router. I’ve been digging through the objects returned from the new options, but haven’t seen a way to get to providers for things like Router. Thanks for any info.

**Comment by DanWahlin** [comment]
Any update on this? Since it's a breaking change I'm hoping there is either a workaround that's possible or that work on it has already started. I know you are all extremely busy, but any info is appreciated. :-)

**Comment by selangley-wa** [comment]
The method TODO comment references @juliemr of the Protractor team. 
Hard to tell what she's up to these days: 
https://twitter.com/somejulie

Maybe we need to wait for the next version of Protractor which is TBD.

**Comment by DanWahlin** [comment]
Yeah - not sure who would be the person to get that implemented. I'd be happy with a workaround in the meantime. I just need to know what I should be looking for in the information that `getAllAngularRootElements()` returns. Specifically, I need to be able to get to the router like we could do with Angular < 9. This is what I *think* it'll be like once findProviders is implemented:

```typescript
onst testabilities = this.window.getAllAngularTestabilities()[0];
 this.router = testabilities.findProviders(this.window.getAllAngularRootElements()[0], 'Router');
```

**Comment by atscott** [comment]
Hi folks (@Coly010, @DanWahlin, @selangley-wa),

I see that `view` is a private property of `Injector_` and that `_providers` is in turn documented as internal on the `NgModuleRef_`. While there's no guarantee of support non-public methods and properties, I would still like to find a suitable replacement for you. I realize accessing private properties is probably an indication that our public API is missing support for a certain use-case. 

Could you provide a bit more context about what your use-cases are? In terms of a replacement for retrieving an `Injector` instance, we have [ng.getInjector](https://angular.io/api/core/global/ngGetInjector), though I'm guessing this doesn't fully serve your needs or you would have already been using `Injector.get`.

**Comment by DanWahlin** [comment]
Hi Andrew. Thanks for the response....really appreciate it.

With Angular 8 I'm using the ng object to get to the Router service. That's used along with the Redux Devtools to handle routing changes as people step through time. Here's the specific code where I need to get the Router:

https://github.com/DanWahlin/Observable-Store/blob/master/modules/observable-store-extensions/angular/angular-devtools-extension.ts#L25

Would ng.getinjector be able to handle getting the Router with Angular 9 and Ivy? I'm not sure what I'd pass into it, but let me know your thoughts. Thanks again!

**Comment by atscott** [comment]
Hi @DanWahlin, 

I did some digging and it would require a fair bit of work and design to add this to the debugging tools. I'm keeping this bug open to track the request; we do also have a document to track debugging APIs that would be useful and this is now on it.

 For now, your best option might be to add a note to your top-level readme. Users will need to provide the `Router` and `NgZone` (that's also a private property where you're getting it now) tokens on the window so that you can retrieve them in your devtools extension.

```
import { environment } from './environments/environment';
import { NgZone } from './@angular/core';
import { Router } from '@angular/router';

if (!environment.production) {
    window['__tokensForReduxDevToolsExtension__'] = {router: Router, ngZone: NgZone};
    ObservableStore.addExtension(new ReduxDevToolsExtension());
}
```

and update your devtools extension to use 
```
const injector = this.window.ng.getInjector(this.window.getAllAngularRootElements()[0]);
this.router = injector.get(window['__tokensForReduxDevToolsExtension__'].router);
this.ngZone = injector.get(window['__tokensForReduxDevToolsExtension__'].ngZone);
```

**Comment by DanWahlin** [comment]
Thanks Scott. I think what you propose above works fine. Easy to document that and gives the user complete control over if they want to do it or not to enable the redux tools in this scenario.

I really appreciate your time in looking into it more. Thanks a ton!

**Comment by DanWahlin** [comment]
Thanks again....I tried this out @atscott. The next challenge is I'm getting "No provider found" for Router:

![2020-05-11_18-28-50](https://user-images.githubusercontent.com/1767249/81628445-8cded980-93b5-11ea-98cd-f39676fcd296.png)

Is it being injected too early in the startup lifecycle? I don't know anything about the `_lView` and `_tNode` data returned from the `this.window.ng.getInjector(this.window.getAllAngularRootElements()[0])` call and when providers are officially registered within the app.

![2020-05-11_18-31-36](https://user-images.githubusercontent.com/1767249/81628557-d6c7bf80-93b5-11ea-87bf-5e7fbb744bf8.png)

The correct symbol is being passed in to `getIinjector()` but it looks like the provider hasn't been registered at this point. I know how to fix the error with "standard" Angular but do you happen to know if there's anything else I can do with the code at this level to get past that error? Not sure how to define a provider but hoping it can be done with some type of window.ng.xxxx call.

**Comment by atscott** [comment]
Hi @DanWahlin, could you create a reproduction so I can take a look? I was [testing this in stackblitz](https://stackblitz.com/edit/angular-ivy-1vpj5o?file=src%2Fmain.ts) inside the `bootstrapModule` promise resolve and it seemed to be working
![image](https://user-images.githubusercontent.com/479713/81632981-72f6c400-93c0-11ea-8fc8-7614dbf8d9c9.png)

**Comment by DanWahlin** [comment]
Thanks for putting that together @atscott. I can run yours fine. I tried the exact code in my project and still get the provider error.

To start from scratch, I created a new StackBlitz Angular project, copied the code from your main.ts into it, and get the provider not found error for some reason. The only thing I can see that's different between yours and this new one is a few package versions (they're newer in mine only because it was created tonight). 

https://stackblitz.com/edit/angular-ivy-8oq2n1?file=src%2Fmain.ts

I'm hoping I'm just missing something stupid but let me know if you see any difference when you can. I'm baffled as to why yours works and mine doesn't (both StackBlitz and my real project).
