### ISSUE TITLE
guide/aot-compiler docs not up to date

### ISSUE THREAD

**Issue by daniel-seitz** [angular/angular#35415]
# 📚 Docs or angular.io bug report

### Description

The docs have outdated information: In v9 Ivy was introduced along with the aot=true flag in angular.json. As far as I understand, ng build (and ng serve?) now compile with aot enabled. The documentation should be adapted for this.

The guide shows **JIT compilation is the default**

And to me it is not 100% clear if ng serve behaves like this as well since there is no aot=true option in angular.json inside of the serve-section... what about ng test.

### What's the affected URL?**
https://angular.io/guide/aot-compiler

Not sure if there are plans to adapt this already, at least in branch with tag 9.1.0-next.0 nothing shows up, yet.

Thank you and keep up the great work!
Daniel

**Comment by SebastianPodgajny** [comment]
Would be awesome if compiler team could write some tips how to write code that will compile fast in AOT even in large scale application. Maybe some patterns and antipatterns or what can affect build time negatively

**Comment by santoshyadav198613** [comment]
Thanks for raising this up, I will start working on this soon, @kapunahelewong @aikidave is something in your queue, or I will start updating this as AOT is default now with Ivy.

**Comment by aikidave** [comment]
Not in our queue at the moment! Feel free to take this issue. Let me know if I can provide assistance!

**Comment by santoshyadav198613** [comment]
Cool @aikidave will start working on it.

**Comment by daniel-seitz** [comment]
Thank you

**Comment by JoostK** [comment]
Addressed in #35487.
