### ISSUE TITLE
Typo in angular/docs/PR_REVIEW.md (reseting -> resetting)

### ISSUE THREAD

**Issue by YooInKeun** [angular/angular#35419]
It's a very simple issue.
There is a typo in "angular/docs/PR_REVIEW.md", line 44.
The typo is "reseting".
I suggest to modify "reseting" with "resetting" like below.

> Knowing `pr/24623_top` and `pr/24623_base` makes it convenient to refer to different SHAs in PR when rebasing or reseting.

> Knowing `pr/24623_top` and `pr/24623_base` makes it convenient to refer to different SHAs in PR when rebasing or **resetting**.

Thank you!

**Comment by santoshyadav198613** [comment]
Hey @YooInKeun ,
Would you like to make your first contribution, i can help you with it. Let me know if you are interested in taking this up.

**Comment by santoshyadav198613** [comment]
Hey @YooInKeun ,
The PR is raised to merge it into your own local branch.

**Comment by YooInKeun** [comment]
Thank you for the answer.
I will try again!

**Comment by santoshyadav198613** [comment]
> Thank you for the answer.
> I will try again!

Just added the steps to follow, let me know of you get any issues.

**Comment by YooInKeun** [comment]
I'm done!
Could you check my PR?

**Comment by santoshyadav198613** [comment]
> I'm done!
> Could you check my PR?

Perfect just sing the CLA and you are done.

**Comment by santoshyadav198613** [comment]
> I'm done!
> Could you check my PR?

PR is done, the only problem is commit message. Let's discuss on PR.

**Comment by ajitsinghkaler** [comment]
@aikidave this has already been completed just the commit message did not contain fixes #issue number 

I think we can close this issue as corresponding pr resolves it

**Comment by kapunahelewong** [comment]
Thank you, @ajitsinghkaler!!
