### ISSUE TITLE
routerLink with absolute path and round brackets parsed incorrectly

### ISSUE THREAD

**Issue by wibimaster** [angular/angular#35414]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router: ~8.3.23

### Is this a regression?

Don't know

### Description

When using the secondary routes feature, I cannot create an absolute routerLink with it. Parenthesis are encoded.

## 🔬 Minimal Reproduction

Example :

`<a routerLink="/page(some:thing)">try me</a>`

Gives the link `"/page%28some:thing%29"` instead of `"/page(some:thing)"`

Same bug if I use `[routerLink]="myLink"` with `this.myLink = '/page(some:thing)'`

I know that Angular try to encode URL following the standards, but parenthesis are special chars needed for secondary routes. They shouldn't be encoded.

I see a lot of issues reported with parenthesis, and I want to re-open #32718

If you want a stackblitz (that was the reason for closing the other ticket) :

https://stackblitz.com/edit/angular-9qzcmh

**Angular Version:**
<pre><code>
Angular CLI: 8.3.23
Node: 12.14.1
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.23
@angular-devkit/build-angular     0.803.23
@angular-devkit/build-optimizer   0.803.23
@angular-devkit/build-webpack     0.803.23
@angular-devkit/core              8.3.23
@angular-devkit/schematics        8.3.23
@angular/cli                      8.3.23
@ngtools/webpack                  8.3.23
@schematics/angular               8.3.23
@schematics/update                0.803.23
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Comment by TidianeRolland** [comment]
@atscott I will work on it

**Comment by wibimaster** [comment]
Just fix the doc ?
Could you tell me how to make correct routerLink with secondary route ?

Thanks !
