### ISSUE TITLE
PortalModule Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

### ISSUE THREAD

**Issue by splincode** [angular/angular#35411]
### Affected Package
The issue is caused by package @angular/cdk

### Exception

```
Error
node_modules/@angular/cdk/portal/portal-directives.d.ts(87,22): error TS-996002: 
Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class
```

## 🔬 Minimal Reproduction

Angular 8

https://ng-run.com/edit/zaAPf6quR1mHzvqLCyUm?open=app%2Fapp.component.html

Angular 9

https://ng-run.com/edit/t3b4kSE3FAvM6L3QFc0F?open=app%2Fapp.component.ts

## 🌍  Your Environment

Angular 9

**Comment by ericmartinezr** [comment]
There are a few possible duplicates: https://github.com/angular/angular/issues/35255, https://github.com/angular/angular/issues/34983 and https://github.com/angular/angular/issues/35399

**Comment by alxhub** [comment]
`ng-run` doesn't support running `ngcc` as far as I know, so it doesn't make sense as a reproduction here. Please provide a reproduction in the form of a Github repository.

That said, this error typically means that `ngcc` hasn't run or hasn't been able to successfully compile a dependency. We're going to work on improving the error message.

I'm going to close this as we already have a number of open issues for this error message. If you uncover a specific issue with `ngcc` when compiling `@angular/cdk/portal`, please feel free to open a new one. It should work, though - we do test `@angular/cdk` :)

**Comment by splincode** [comment]
@alexzuza it’s true? ng-run.com do not support ngcc?

**Comment by alexzuza** [comment]
@splincode It didn't support ngcc on 3rd-party libraries. Now it does. At least it tries all its best:)
Your example should work
