### ISSUE TITLE
*ngIf doesn't work in Ivy compiled libraries

### ISSUE THREAD

**Issue by darress** [angular/angular#35410]
# 🐞 bug report

### Affected Package
@angular/common

### Is this a regression?
ngIf worked fine in libraries before upgrading to Angular 9 and Ivy, didn't test Angular 8 with Ivy.

### Description
If a library is build with Ivy, ngIf bound to a simple bool doesn't work in the following component:
```typescript
@Component({
  selector: 'lib-my-lib',
  template: `
      <div id="content of testBool">{{testBool}}</div>
      <div *ngIf="testBool">TEST 1</div>
      <div *ngIf="testBool === true">TEST 2</div>
      <div *ngIf="testBool !== false">TEST 3</div>
      <div *ngIf="!!testBool">TEST 4</div>
      <div *ngIf="$any(testBool)">TEST 5</div>
      <div *ngIf="!testBool">TEST NEG</div>
  `,
  styles: []
})
export class MyLibComponent{

  public testBool = true;

  constructor() { }
}
```

None of the *ngIf divs will display.

## 🔬 Minimal Reproduction
https://github.com/darress/angular9_lib_ngif_bug

Build the library with `ng build my-lib` than build the application with `ng build`.

## 🔥 Exception or Error
None.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.2
Node: 10.14.2
OS: win32 x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.2
@angular-devkit/build-angular      0.900.2
@angular-devkit/build-ng-packagr   0.900.2
@angular-devkit/build-optimizer    0.900.2
@angular-devkit/build-webpack      0.900.2
@angular-devkit/core               9.0.2
@angular-devkit/schematics         9.0.2
@angular/cli                       9.0.2
@ngtools/webpack                   9.0.2
@schematics/angular                9.0.2
@schematics/update                 0.900.2
ng-packagr                         9.0.0
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Anything else relevant?**
Tested with Chrome, IE, Firefox.

**Comment by dawidgarus** [comment]
You can't use `NgIf` without importing `CommonModule`

**Comment by darress** [comment]
Thanks for the response, you are right, I forgot that. Although it would be nice if the compiler would show an error for that.

The minimal repro project works with that change, the big application that I'm working on is not though, and CommonModule was imported there. I'll continue to try to reproduce the problem in the former project.

**Comment by darress** [comment]
It turned out, this bug appears in our application only if optimization is turned on. If I turn that off and leave anything else be, ngIf works as usual.
Unfortunately, I still cannot reproduce it in the minimal project.

**Comment by darress** [comment]
It turned out it was a side-effect of something else. (I commented out everything else from the component and ngIf works.)

**Comment by darress** [comment]
The cause of the *ngIf problem was this: https://github.com/angular/angular/issues/35602
