### ISSUE TITLE
guide/dependency-injection-providers is confusing

### ISSUE THREAD

**Issue by dtaylor84** [angular/angular#35413]
# 📚 Docs or angular.io bug report

### Description

1. The section starts discussing an object that "conforms to the AppConfig interface", but the sample code never defines AppConfig as an interface, or at all.

2. There are then two solutions presented

* One alternative is to provide and inject the configuration object in an NgModule like AppModule.

* Another solution to choosing a provider token for non-class dependencies is to define and use an InjectionToken object. The following example shows how to define such a token.

Both solutions appear to be exactly the same, except the first fails to explain what the APP_CONFIG dependency token is before using it.

### What's the affected URL?
https://angular.io/guide/dependency-injection-providers#non-class-dependencies

**Comment by kapunahelewong** [comment]
Agreed, @dtaylor84. This should be cleared up. Thank you for filing the issue.

**Comment by kapunahelewong** [comment]
Status: Docs team can clarify the original copy.

**Comment by aikidave** [comment]
I think this content has been updated and this issue has been fixed! Closing!
