### ISSUE TITLE
`as` syntax marks template as TS/JS instead of HTML

### ISSUE THREAD

**Issue by tonivj5** [angular/angular#35424]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/language-service

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.x.x

### Description

If I use `as` syntax in a directive, the template is recognized as TS/JS instead of HTML + angular syntax
![image](https://user-images.githubusercontent.com/7110786/74463272-e6586a80-4e91-11ea-8842-612c92f746f2.png)

## 🔬 Minimal Reproduction
https://github.com/tonivj5/angular-issues-35424-and-35426

## 🔥 Exception or Error
None

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.2
Node: 13.7.0
OS: linux x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by mattrichard** [comment]
As a workaround you can add a `;` to the end of the ngIf.

![image](https://user-images.githubusercontent.com/2396016/74466661-89869100-4e4c-11ea-8d2d-8ac22a8a95f4.png)

This also affects ngFor in a slightly different way.

ngFor without ending in `;`
![image](https://user-images.githubusercontent.com/2396016/74466711-a4590580-4e4c-11ea-9395-1d3de6dd99d8.png)

ngFor with ending in `;`
![image](https://user-images.githubusercontent.com/2396016/74466735-b3d84e80-4e4c-11ea-8a65-ffa61f5d97f0.png)

**Comment by ChristopherKiss** [comment]
This is a known issue already.

https://github.com/angular/vscode-ng-language-service/issues/575

And there is a PR already open to fix it, however it is quite large and is still in review.

https://github.com/angular/vscode-ng-language-service/pull/609

**Comment by ayazhafiz** [comment]
Thanks for the mention of the existing issues. I am closing this issue so we can keep the tracking in one place. Please feel free to open another issue if you see any other problems!
