### ISSUE TITLE
Angular 9 Upgrade Erroring on cdk-high-contrast mixin

### ISSUE THREAD

**Issue by SEAjamieD** [angular/angular#35425]
# 🐞 bug report

### Affected Package
The issue is caused by package:
@angular/material/_theming.scss, in mixin `cdk-high-contrast`
@angular/material/_theming.scss, in mixin `mat-badge-theme`
@angular/material/_theming.scss, in mixin `angular-material-theme`

### Is this a regression?
Yes, Working fine in Angular 8.3.21

### Description
We are currently upgrading from Angular 8.3.21 to Angular 9 alongside Angular Material and are hung up an issue pertaining to `cdk-high-contrast` when running `ng-build`.  The specific output is that we're providing the wrong number of arguments for `cdk-high-contrast`, currently providing 2 but we should be providing 1.  We haven't touched any of the Angular code ourselves and this was working previously.

I've looked into both https://github.com/angular/angular/issues/34731 and https://github.com/angular/components/issues/18147 and can't completely deduce if they are related - at first glance it appears this is separate but wondering if there may be a link somewhere.

## 🔬 Minimal Reproduction
repo: https://github.com/chef/automate/tree/ms/angular-9-upgrade

To Reproduce:
1. cd components/automate-ui
2. npm install
3. ng build

## 🔥 Exception or Error
<pre><code>
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/dist/cjs.js??ref--15-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: wrong number of arguments (2 for 1) for `cdk-high-contrast'
        on line 1934 of node_modules/@angular/material/_theming.scss, in mixin `cdk-high-contrast`
        from line 1934 of node_modules/@angular/material/_theming.scss, in mixin `mat-badge-theme`
        from line 5112 of node_modules/@angular/material/_theming.scss, in mixin `angular-material-theme`
        from line 47 of src/styles/chef-theme.scss
        from line 5 of /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/src/styles.scss
>>     @include cdk-high-contrast(active, off) {
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.1
Node: 12.13.1
OS: darwin x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@nguniversal/common               9.0.0
@nguniversal/express-engine       9.0.0
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**
No other relevant information at this time.

**Comment by gkalpak** [comment]
This sounds like an issue with [Angular Material][1] or the [Angular CLI][2] (not the Angular core framework).

Can you try separating the update of Angular Material, Angular CLI and the framework Angular packages to see where this error comes from?

[1]: https://github.com/angular/components
[2]: https://github.com/angular/angular-cli

**Comment by SEAjamieD** [comment]
Thanks for the quick response!  We're gonna give that a shot and I'll report back on what happens.

**Comment by msorens** [comment]
@gkalpak Per your request, we redid the upgrade process to v9, this time paying attention as to when the `cdk-high-contrast` first manifested.

Upgrades were applied in this order:

- @angular/core -- no build error
- @angular/cli -- no build error
- @angular/cli -- build error occurred!

So it appears that the issue is with the Angular Material upgrade.

**Comment by gkalpak** [comment]
Thx for getting back! Since it seems to be related with Angular Material, please open an issue in the [angular/components repo][1].

[1]: https://github.com/angular/components
