### ISSUE TITLE
Cryptic error when # included in templateUrl

### ISSUE THREAD

**Issue by jessegood** [angular/angular#3543]
Not sure how common this will be but I ran into a cryptic error when a `#` is included in the string to `templateUrl`. Simple example:

    @Component({
      selector: 'app',
     })
    @View({
      templateUrl: `
        <p #p>Hello</p>
      `
    })
    export class App {}

In the above example, it was just a goof and I forgot to change `templateUrl` to `template`.
Without the `#` you get a nice error message:
> EXCEPTION: Failed to load the template for "App" : Failed to fetch url "http://127.0.0.1:8080/
    <p>Hello</p>

With the `#` you get this:
Firefox:
> EXCEPTION: TypeError: parts is null

Chrome:
> EXCEPTION: TypeError: Cannot read property '1' of null

From what I've found the same error happens with any string that has a `#` in it.

**Comment by pkozlowski-opensource** [comment]
In reality it is a combination of # and a new line in the URL. Dart version doesn't suffer from this pb, as a URL gets encoded before matching. Will try to do the same on JS side to bring 2 implementations to the same level.
