### ISSUE TITLE
Undefined value being passed to getNgModuleDef in render3/definition.ts

### ISSUE THREAD

**Issue by chris13524** [angular/angular#35438]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?

Yes, the previous version in which this bug was not present was: 0.7.x

### Description

We are getting variations of the error below. Tracking this back to source it comes from `getNgModuleDef` from `render3/definition.ts` line 761. So it seems `type` is undefined? One level up we are at `render3/ng_module_ref.ts` line 46.

## 🔬 Minimal Reproduction

Not sure, haven't been able to reproduce it locally but we've gotten 7 error reports so far.

## 🔥 Exception or Error

```
Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'e[K]')
Ke@https://givingtools.com/main-es2015.e6fb09898d8d83818872.js:1:199366
Up@https://givingtools.com/main-es2015.e6fb09898d8d83818872.js:1:339856
Zm@https://givingtools.com/main-es2015.e6fb09898d8d83818872.js:1:362918
Km@https://givingtools.com/main-es2015.e6fb09898d8d83818872.js:1:362969
https://givingtools.com/main-es2015.e6fb09898d8d83818872.js:1:688086
_tryNext@https://givingtools.com/main-es2015.e6fb09898d8d83818872.js:1:69962
_next@https://givingtools.com/main-es2015.e6fb09898d8d83818872.js:1:69881
next@https://givingtools.com/main-es2015.e6fb09898d8d83818872.js:1:73023
https://givingtools.com/main-es2015.e6fb09898d8d83818872.js:1:106896
onInvoke@https://givingtools.com/main-es2015.e6fb09898d8d83818872.js:1:365369
run@https://givingtools.com/polyfills-es2015.6ee990200b10f2104e36.js:1:11565
https://givingtools.com/polyfills-es2015.6ee990200b10f2104e36.js:1:22446
onInvokeTask@https://givingtools.com/main-es2015.e6fb09898d8d83818872.js:1:365262
runTask@https://givingtools.com/polyfills-es2015.6ee990200b10f2104e36.js:1:12184
y@https://givingtools.com/polyfills-es2015.6ee990200b10f2104e36.js:1:18766
invokeTask@https://givingtools.com/polyfills-es2015.6ee990200b10f2104e36.js:1:17845
p@https://givingtools.com/polyfills-es2015.6ee990200b10f2104e36.js:1:29774
f@https://givingtools.com/polyfills-es2015.6ee990200b10f2104e36.js:1:30014
b@https://givingtools.com/polyfills-es2015.6ee990200b10f2104e36.js:1:21673
b@https://givingtools.com/polyfills-es2015.6ee990200b10f2104e36.js:1:21207
https://givingtools.com/polyfills-es2015.6ee990200b10f2104e36.js:1:22481
onInvokeTask@https://givingtools.com/main-es2015.e6fb09898d8d83818872.js:1:365262
runTask@https://givingtools.com/polyfills-es2015.6ee990200b10f2104e36.js:1:12184
y@https://givingtools.com/polyfills-es2015.6ee990200b10f2104e36.js:1:18766
invokeTask@https://givingtools.com/polyfills-es2015.6ee990200b10f2104e36.js:1:17845
p@https://givingtools.com/polyfills-es2015.6ee990200b10f2104e36.js:1:29774
f@https://givingtools.com/polyfills-es2015.6ee990200b10f2104e36.js:1:30014
```

Including persistent version of [main-es2015.e6fb09898d8d83818872.js](https://gist.github.com/chris13524/9249b904f6d28887eef55b70a0700e70) in case we update it.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.1
Node: 10.16.0
OS: linux x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        8.0.0
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@nguniversal/builders             9.0.0
@nguniversal/common               9.0.0
@nguniversal/express-engine       9.0.0
@schematics/angular               8.0.0
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

Seems to occur predominately on iOS and macOS devices, but that could be within margin of error.

**Comment by AndrewKushnir** [comment]
Hi @chris13524, could you please provide a repro in a form of Github repository, so that we can investigate the problem? Thank you.

**Comment by chris13524** [comment]
@AndrewKushnir I can't reproduce the issue even when running our application locally so I don't see how a repo would help.

**Comment by chris13524** [comment]
Figured out the cause of this. I am wrapping my `loadChildren` in a function to intercept load errors and display a JS `alert()` so the user actually sees what happened (vs. it silently getting logged to the console). The handler is `catch`ing the error like this:

```
{ path: "...", loadChildren: () => import("./module").then(m => m.MyModule).catch(e => alert("Could not load the page, try refreshing.")) }
```

I'm not sure why this triggers the Angular error, but this is how to reproduce it.

Prior to v9 I was using a custom `NgModuleFactoryLoader` which is now deprecated.

Ideally, Angular would support a method to catch load errors. `catch()` in this instance may be a way to do that.

Closing to yield discussion to #12289.
