### ISSUE TITLE
The example that is demonstrated in the documentation, it is to be done parallely in the StackBlitz environment, but on the initial stages the stack space on StackBlitz finishes and the tutorial in the documentation can not be finished. How to get past the "Stack space full" to finish building the entire project on StackBlitz that is demonstrated in the documentation?

### ISSUE THREAD

**Issue by cognitive137** [angular/angular#35442]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: 
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
Angular: Can't reproduce (v2)
