### ISSUE TITLE
Updating getting started topics to avoid duplicate topic names

### ISSUE THREAD

**Issue by aikidave** [angular/angular#35456]
# 📚 Docs or angular.io bug report

### Description

In our documentation, we have two deployment.md files. One in the Getting Started section, the other in the rest of the Guide.

This can be confusing to users. To fix this, we should:

Rename all getting started topics to prepend `start-` to the filename.

Retitle all getting started topics to have "Getting started with Angular: " (same as the first topic).

Update navigate.json accordingly.

### What's the affected URL?**
angular.io/docs/start

### Reproduction Steps**
Search for Angular deployment

### Expected vs Actual Behavior**
You could get two topics: one for getting started, the other more general.

## 📷Screenshot
N/A

## 🔥 Exception or Error
N/A

### Browser info
N/A

### Anything else relevant?
Nope!

**Comment by kapunahelewong** [comment]
Closing this as the PR has merged. @aikidave, please feel free to re-open if there are any outstanding points (I think you got them, right?). Thanks!
