### ISSUE TITLE
Add content type indicators to topics

### ISSUE THREAD

**Issue by aikidave** [angular/angular#35453]
One way we could help users find content they need is to add icons in the left nav and in the topics themselves. Each icon would represents something like:

- Task-based guide
- Concept
- Reference

Another option is to add icons that would represent a path users could follow. Perhaps even one path: the beginner’s path. Just a thought.

**Comment by petebacondarwin** [comment]
@aikidave - is this something you still want? How can we prioritise this work over other? If it is just a nice to have and not really necessary, then I would prefer to close this.
