### ISSUE TITLE
Update landing page to provide better information about Angular.io content

### ISSUE THREAD

**Issue by aikithoughts** [angular/angular#35450]
# 📚 Docs or angular.io bug report

### Description
The current landing page for the documentation has a minimum of information. It would help users greatly if we added more content so users have a better idea of what sections of the documentation are best suited for them.

### What's the affected URL?**
 https://angular.io/

### Reproduction Steps**
n/a

### Expected vs Actual Behavior**
n/a

## 📷Screenshot
n/a

## 🔥 Exception or Error
n/a

### Browser info
n/a

### Anything else relevant?
n/a

**Comment by petebacondarwin** [comment]
I feel like this is a content issue. The homepage is a markdown file (like a guide). Moving this to `docs` rather than `docs-infra`. If when implementing this, there turns out to be something that needs to be implemented on docs-infra then a new specific issue should be created.
