### ISSUE TITLE
docs: text in tables are covered by TOC if sidenav is open 

### ISSUE THREAD

**Issue by kapunahelewong** [angular/angular#35460]
# 📚 Docs or angular.io bug report

### Description

Text in tables are covered by TOC if sidenav is open, which is the default, so they are cut off and not fully visible.

### What's the affected URL?**

There are multiple instances in this page, but here's one example:
https://angular.io/guide/ajs-quick-reference#bootstrapping

## 📷Screenshot

![image](https://user-images.githubusercontent.com/4116963/74566699-1101fc00-4f42-11ea-98c9-0e7ae1d2e637.png)

![image](https://user-images.githubusercontent.com/4116963/74566703-13fcec80-4f42-11ea-9f23-1e80dce28073.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Anything else relevant?
Screenshots are from 15" macbook pro.

**Comment by sonukapoor** [comment]
@kapunahelewong I can take a look. Can you assign this to me please?

**Comment by gkalpak** [comment]
FWIW, I cannot reproduce this. What is the window size when this happens, @kapunahelewong?

**Comment by sonukapoor** [comment]
@gkalpak is right. It's very responsive to me as well. I also tried to zoom in/out. The content/code never cuts off for me.

**Comment by kapunahelewong** [comment]
Oh psh. Chrome was zoomed in. Thanks @gkalpak and @sonukapoor. I'll close now haha
