### ISSUE TITLE
No pipe found with name 'async'

### ISSUE THREAD

**Issue by sarir38** [angular/angular#35467]
Hi, 
I have upgraded to angular 9 form angular 8 i am getting the follow errors
No pipe found with name 'async',
built in pipes and custom pipes are not working
  {{employee?.getPersonalInfo().getOfficialName() | nameValuePipe }}<span></span>

error NG8004: No pipe found with name 'async'.
<div class="error times-font" style="padding:2rem;z-index:1000">{{this.orgTeamSession.error|async}}</div>

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

---

Please follow the issue template and provide a reproduction, either through StackBlitz, ng-run.com or a Github repo.
