### ISSUE TITLE
Typo in docs ("only")

### ISSUE THREAD

**Issue by pasha-bolokhov** [angular/angular#35465]
# 📚 Docs or angular.io bug report

### Description

A bit too insistent "only" in https://material.angular.io/guide/theming &mdash; I get it, it's important
```
Remember to only ever include the @mat-core mixin only once; it should not be included for each theme.
```
### What's the affected URL?**
https://material.angular.io/guide/theming

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by sacgrover** [comment]
This is part of angular/components project. Raise PR for it.
https://github.com/angular/components/pull/18510

**Comment by alan-agius4** [comment]
Closing as it was addressed in https://github.com/angular/components/pull/18510
