### ISSUE TITLE
Additional deprecation information about entryComponents in the guide

### ISSUE THREAD

**Issue by ghost** [angular/angular#35478]
# 📚 Docs or angular.io bug report

### Description
 A clear and concise description of the problem...
As it is no longer required to declare **entryComponents** when using Ivy compiler documentation should clearly state this information upfront. 

### What's the affected URL?**
https://angular.io/guide/entry-components

### Expected vs Actual Behavior**

Documentation on entryComponents should contain a simmilar note the same way as TestBed.get has a note in the Testing section.
![image](https://user-images.githubusercontent.com/49555915/74599696-e2de0280-508e-11ea-893a-3e659f420e46.png)

**Comment by jeroenouw** [comment]
In the deprecation section it is [mentioned](https://angular.io/guide/deprecations#entrycomponents-and-analyze_for_entry_components-no-longer-required ).

**Comment by petrikas** [comment]
@jeroenouw I guess the question is - Should the documentation inform new comers about deprecated APIs?
Imagine you are a new user who has started learning Angular, do you need really need to know about entryComponents? 
The idea behind this PR is to inform the user about redundancy of this knowledge upfront.

**Comment by JoostK** [comment]
This was addressed in #35479.
