### ISSUE TITLE
SVG classes no longer work as expected

### ISSUE THREAD

**Issue by claridgicus** [angular/angular#35475]
# 🐞 bug report
### Affected Package
I assume this is related to the IVY renderer, not sure

### Is this a regression?
Yes this used to work fine in literally every other version of angular

### Description
Applying a class to an svg causes nothing to happen, specifically reloading

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-px5oex

## 🔥 Exception or Error
None, just doesnt work

## 🌍  Your Environment
**Angular Version:**
as per the stackblitz - 9 latest

**Comment by pkozlowski-opensource** [comment]
@claridgicus I'm afraid that we will need more info. In the issue description you've indicated:
> as per the stackblitz - 9 latest

but the stackblitz you've shared runs on Angular v8: https://stackblitz.com/edit/angular-px5oex?file=src%2Fapp%2Fapp.component.html

> Yes this used to work fine in literally every other version of angular

Hmm, it seems like it "doesn't work" in v8 as per your stackblitz. And when I run in Angular v9 I'm seeing the same visual output: https://ng-run.com/edit/aqwoOJTvjPaMz96FnUkN - in both cases I can see the "class" attribute being applied to the svg element.

Could you please help us understand this issue better? 
* could you share 2 examples (a working and _non_ working one) so we can see the regression?
* it is not clear to me what you mean by "Applying a class to an svg causes nothing to happen, specifically reloading" - it would be great to have a live reproduce case for both "working" and "non-working" versions so we can really see what you mean?

**Comment by manklu** [comment]
@claridgicus Since your shape is symmetric, it has no visual difference if you rotate it by 180 degrees around the y axis.

**Comment by pkozlowski-opensource** [comment]
I'm going to close this one for now as for me it works as expected (that it, expected HTML is generated) and we haven't heard back with more info.
