### ISSUE TITLE
Style with hostbinding doesn't work like before in Ivy

### ISSUE THREAD

**Issue by maxisam** [angular/angular#35476]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?

Yes, it works before Ivy.

https://stackblitz.com/edit/angular-oqwzqb?file=src%2Fapp%2Fhostbinding-test.directive.ts

### Description

This doesn't work like it used to be. 
```ts
@HostBinding("style")
style: SafeStyle = this.sanitizer.bypassSecurityTrustStyle(
    "background: red; color: white; display: block;"
  );
```

It does work if we do it like this 

```ts
@HostBinding("style.background")
styleBackground: SafeStyle = this.sanitizer.bypassSecurityTrustStyle("red");
```

## 🔬 Minimal Reproduction

https://github.com/maxisam/angular-ivy-style-issue 

if we set "enableIvy: false", it works.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.2
Node: 10.16.0
OS: win32 x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

don't think so

**Comment by dann95** [comment]
so this was fixed? ^.-
