### ISSUE TITLE
Angular PWA fails to reload when goes offline - Receiving 504 error

### ISSUE THREAD

**Issue by datphan126** [angular/angular#35477]
### Affected Package
@angular/pwa

### Is this a regression?

I'm not sure

### Description

If I reload my page while I'm offline either by turning on the simulated Offline mode in Chrome Devs Tool or by physically disconnecting my machine from the Internet, I get a 504 error.

## 🔬 Minimal Reproduction
This is the live site where I encounter the problem: `http://sojinvn.github.io/`
And, this is my codebase: `https://github.com/sojinvn/pwa_book_store`
I'm building the project with: `npm run buildGHP`

## 🔥 Exception or Error
```
This page isn’t working
sojinvn.github.io took too long to respond.
HTTP ERROR 504
```

## 🌍  Your Environment

```
**Angular Version:**
Angular CLI: 8.3.25
Node: 12.10.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.25
@angular-devkit/build-angular     0.803.25
@angular-devkit/build-optimizer   0.803.25
@angular-devkit/build-webpack     0.803.25
@angular-devkit/core              8.3.25
@angular-devkit/schematics        8.3.25
@angular/cdk                      8.2.3
@angular/cli                      8.3.25
@angular/material                 8.2.3
@angular/pwa                      0.803.25
@ngtools/webpack                  8.3.25
@schematics/angular               8.3.25
@schematics/update                0.803.25
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
```

**Comment by datphan126** [comment]
When I ran `/ngsw/state`, I got the following response:
```
NGSW Debug Info:

Driver state: EXISTING_CLIENTS_ONLY (Degraded due to: Response not Ok (cacheBustedFetchFromNetwork): cache busted request for https://datphan126.github.io/index.html returned response 504 Gateway Timeout
Error: Response not Ok (cacheBustedFetchFromNetwork): cache busted request for https://datphan126.github.io/index.html returned response 504 Gateway Timeout
    at PrefetchAssetGroup.<anonymous> (https://datphan126.github.io/ngsw-worker.js:692:35)
    at Generator.next (<anonymous>)
    at fulfilled (https://datphan126.github.io/ngsw-worker.js:320:62))
Latest manifest hash: 319d9f838b654caa10ef7e8a58dce3336cd545d7
Last update check: never

=== Version 319d9f838b654caa10ef7e8a58dce3336cd545d7 ===

Clients: 

=== Idle Task Queue ===
Last update tick: 7s710u
Last update run: 2s710u
Task queue:


Debug log:

[7s701u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://datphan126.github.io/)
[2s697u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://datphan126.github.io/ngsw.json?ngsw-cache-bust=0.25983846981151903)
[2s697u] Check for update aborted. (Client or server offline.) 
[2s657u] Error(Response not Ok (cacheBustedFetchFromNetwork): cache busted request for https://datphan126.github.io/index.html returned response 504 Gateway Timeout, Error: Response not Ok (cacheBustedFetchFromNetwork): cache busted request for https://datphan126.github.io/index.html returned response 504 Gateway Timeout
    at PrefetchAssetGroup.<anonymous> (https://datphan126.github.io/ngsw-worker.js:692:35)
    at Generator.next (<anonymous>)
    at fulfilled (https://datphan126.github.io/ngsw-worker.js:320:62)) initializeFully for 319d9f838b654caa10ef7e8a58dce3336cd545d7
[2s642u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://datphan126.github.io/ngsw.json?ngsw-cache-bust=0.8376700912653154)
[2s642u] Check for update aborted. (Client or server offline.) 
```

**Comment by jadams88** [comment]
When are you running the `fix-sw.js`? 

I'm not familiar with the issue it is referring to but on a very quick glance it looks to be modifying `ngsw-worker.js` and `index.html` after the build process.

Maybe try updating to v9 and removing any post processing steps and see if the problem still persists?

**Comment by datphan126** [comment]
> When are you running the `fix-sw.js`?
> 
> I'm not familiar with the issue it is referring to but on a very quick glance it looks to be modifying `ngsw-worker.js` and `index.html` after the build process.
> 
> Maybe try updating to v9 and removing any post processing steps and see if the problem still persists?

**Comment by datphan126** [comment]
@jadams88 I don't use the fix-sw.js anymore since it doesn't help me resolve this issue.

I just updated Angular to v9:
```
Angular CLI: 9.0.2
Node: 12.10.0
OS: win32 x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cdk                      9.0.0
@angular/cli                      9.0.2
@angular/material                 9.0.0
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2 (cli-only)
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```
and rebuilt my project, but the problem still persists.

**Comment by jadams88** [comment]
Hmm, I just cloned and built a standard build with `ng build --prod` and then servers with `http-server -p 8080 -c-1 dist/book/store` as per the angular docs and the service worker worked fine offline. Did you give the new SW a chance to activate after re-deploying?

It potentially could be a github pages issue? I had issues initially when configuring the SW with firebase as well.

**Comment by datphan126** [comment]
@jadams88 Thanks for looking into this!

The local deployment also worked for me but still it doesn't work when deployed on GitHub Pages. I did give SW some time to activate and re-deploying.

I tried deploying this compiled code on my GitHub pages and it worked fine offline:
https://github.com/zelite/markdown-previewer/tree/gh-pages
However, if I build the code myself and deploy it on GitHub Pages, it doesn't work:
https://github.com/zelite/markdown-previewer/tree/master
(The codebase is not mine)
So, I think it's a build issue rather than a GitHub Pages issue.

**Comment by datphan126** [comment]
After removing the index.html entry from the hashTable in ngsw.json, my GitHub Pages site is working now. I don't really know what really happened behind the scene but I'll use this workaround for now.

**Comment by gkalpak** [comment]
The hash mismatch means that there is a difference in the two files (it could be a non-visible one, such as zero-width whitespace or newline characters). Maybe some newline characters were replaced by git while pushing to a remote (during the `gh-pages` operations).

##
I am going to close this, because there is no indication that something is wrong on the Angular side and you were able to work around your problem, but feel free to continue the discussion below.

**Comment by datphan126** [comment]
It turns out a VSCode extension for formatting HTML files caused the problem. After removing the extension, I had to create a new index.html by creating a new Angular project, modify the file's content, and replace the old index.html with the new one. Basically, you need to remove the extension and create a new index.html since there are some invisible characters in the old/corrupted index.html that could not be fixed.
