### ISSUE TITLE
ngSwitch is an attribute directive or structural directive

### ISSUE THREAD

**Issue by OmarioHasan** [angular/angular#35484]
# 📚 Docs or angular.io bug report

### Description
Surfing the documentation and found 2 description for ngSwitch
in https://angular.io/guide/template-syntax#the-ngswitch-directives : 
i found it attribute directive
in the others i found it as structural directive 

is thers something i didnt understand well ?

### What's the affected URL?**
https://angular.io/guide/template-syntax#the-ngswitch-directives

## 📷Screenshot
![Annotation 2020-02-17 041234](https://user-images.githubusercontent.com/8146344/74618758-bdf39900-513b-11ea-949d-06c229c58c9f.png)
![Annotation 2020-02-17 041234](https://user-images.githubusercontent.com/8146344/74618785-e2e80c00-513b-11ea-9bc9-3b405d473fa8.png)

**Comment by santoshyadav198613** [comment]
Hi @OmarioHasan, 

Thanks for pointing this out, we will get it sorted.

@kapunahelewong,
Can you assign this to me.

**Comment by OmarioHasan** [comment]
> Hi @OmarioHasan,
> 
> Thanks for pointing this out, we will get it sorted.
> 
> @kapunahelewong,
> Can you assign this to me.

Have all of luck santosh
Regards
