### ISSUE TITLE
Allow to enable native form validation globally

### ISSUE THREAD

**Issue by reda-alaoui** [angular/angular#35488]
# 🚀 feature request

### Relevant Package

@angular/forms

### Description

When using FormsModule, in order to enable native form validation,we are forced to add `ngNativeValidate` to each form.

### Describe the solution you'd like

Please provide a way to enable native form validation globally.

**Comment by dylhunn** [comment]
While we appreciate your contribution, there doesn't seem to be much community demand for this feature. We're hesitant to expand this API like this without a stronger signal, given there is already a way for apps to do this.
