### ISSUE TITLE
Angular 9 error No component factory found for TestDialogComponent. Did you add it to @NgModule.entryComponents?

### ISSUE THREAD

**Issue by aford22** [angular/angular#35482]
### Description

Angular 9. Calling `const dialogRef = this.dialog.open(TestDialogComponent, dialogConfig)` produces error "No component factory found for TestDialogComponent. Did you add it to @NgModule.entryComponents?"

This worked under Angular 8 with an entryComponent defined in my module. However I have removed the entryComponent statement from the module since this should be no longer needed in Angular 9 as per: https://angular.io/guide/deprecations#entrycomponents-and-analyze_for_entry_components-no-longer-required

## 🔥 Exception or Error
<pre><code>
message:"No component factory found for TestCredentialDialogComponent. Did you add it to @NgModule.entryComponents?"
ngComponent:class TestCredentialDialogComponent { … }
ngDebugContext:DebugContext_ {view: Object, nodeIndex: 8, nodeDef: Object, …}
ngErrorLogger:function () { … }
stack:"Error: No component factory found for TestCredentialDialogComponent. Did you add it to @NgModule.entryComponents?\n    at noComponentFactoryError (http://localhost:4200/vendor.js:93165:19)\n    at CodegenComponentFactoryResolver.resolveComponentFactory (http://localhost:4200/vendor.js:93230:19)\n    at CodegenComponentFactoryResolver.resolveComponentFactory (http://localhost:4200/vendor.js:93227:36)\n    at CdkPortalOutlet.attachComponentPortal (http://localhost:4200/vendor.js:24048:43)\n    at MatDialogContainer.attachComponentPortal (http://localhost:4200/vendor.js:137945:35)\n    at MatDialog._attachDialogContent (http://localhost:4200/vendor.js:138624:48)\n    at MatDialog.open (http://localhost:4200/vendor.js:138492:32)\n    at EditUserComponent.testCredential (http://localhost:4200/pages-users-users-module.js:382:39)\n    at Object.eval [as handleEvent] (ng:///UsersModule/EditUserComponent.ngfactory.js:627:27)\n    at handleEvent (http://localhost:4200/vendor.js:108774:122)"
</code></pre>

**Comment by JoostK** [comment]
You seem _not_ to be using Ivy in Angular 9, so that `entryComponents` is still required. Were you having issues with Ivy that you disabled it?

**Comment by aford22** [comment]
I did not deliberately disable Ivy, no. I merely followed the upgrade instructions (https://update.angular.io/#8.2:9.0l2) to take by Angular project from 8.2 to 9.0. I am using "ng serve" to run the Angular app - I have no idea why this is not using Ivy!

**Comment by JoostK** [comment]
Having the `"enableIvy": false` configured there will indeed use the ViewEngine pipeline, not Ivy. That flag has been around for a while and its default has been changed to `true` in Angular 9, so there is no reason to include that flag at all when running Ivy. I am guessing that maybe someone tried using Ivy at an earlier stage and then kept the `"enableIvy"` flag set to `false` in the configuration? Maybe your version control history can tell how that got there ;)

As a start, removing that flag should indeed be enough to enable Ivy.

**Comment by aford22** [comment]
Indeed @JoostK , that fixed it. Thanks so much for your help
