### ISSUE TITLE
Access the assets folder when running ng build --prod --base-href './project1'

### ISSUE THREAD

**Issue by sajidit** [angular/angular#35485]
My client want me to deploy multiple projects on the same ngnix server with the following configuration.

location /project1/ {
    alias /usr/local/var/www/project1/;
    try_files $uri$args $uri$args/ /project1/index.html;
}
In the above configuration I could not access the assets folder as it's in the project1 folder and I try to access it from the root of the domain example src:

url('/assets/fonts/texta/Texta-Regular/Texta-Regular.eot')

When I change the path with src: url('./assets/fonts/texta/Texta-Regular/Texta-Regular.eot') I'm getting following problem when building the production build

ERROR in ./src/styles.scss Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js): ModuleError: Module Error (from ./node_modules/postcss-loader/src/index.js): (Emitted value instead of an instance of Error) CssSyntaxError: /Users/Desktop/personal/projects/example/src/styles.scss:10115:13: Can't resolve './assets/fonts/texta/Texta-Regular/Texta-Regular.eot%3F' in '/Users/Desktop/personal/projects/example/src'

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
