### ISSUE TITLE
Custom path in tsconfig in library is considered as external module

### ISSUE THREAD

**Issue by ArnaudDenoyelle** [angular/angular#35499]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core or @angular/common

### Is this a regression?

Yes, the previous version in which this bug was not present was @angular/core 8.2.14

It started to fail after migrating to angular 9 following instructions on [update.angular.io](update.angular.io)

### Description

In an angular project, I create a library.
In the tsconfig of the library (projects/my-lib/tsconfig.lib.json), I define a custom path : 

```
"compilerOptions": {
  [...]
  "paths": {
    "baseUrl": [ "./" ],
    "@env/*": [ "projects/my-lib/src/environments/*" ]
  }
}
```
Then I use this path in a component : 

```
import { environment } from '@env/environment';
```
At compilation of the library, I get a warning hinting me that this path might be misinterpreted as an external module : 

```
WARNING: No name was provided for external module '@env/environment' in output.globals – guessing 'environment'
```

Then, I import the only module of this library in a project and I get this error at compilation : 

```
ERROR in The target entry-point "my-lib" has missing dependencies:
 - @env/environment
```

## 🔬 Minimal Reproduction

[Ready-to-use SSCCE here](https://github.com/ArnaudDenoyelle/sscce-angular9-paths)

1- Create a new project : `ng new acme` with simplest options (no routing, css)
2- Create a library : `ng generate library my-lib`
3- under `projects/my-lib/src`, create a folder `environments` with 2 files: `environment.ts` and `environments.prod.ts`
4- Configure `projects/my-lib/tsconfig.lib.json` like this (I just added the `paths` block):

```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/lib",
    "target": "es2015",
    "declaration": true,
    "inlineSources": true,
    "types": [],
    "lib": [
      "dom",
      "es2018"
    ],
    "paths": {
      "baseUrl": [ "./" ],
      "@env/*": [ "projects/my-lib/src/environments/*" ]
    }
  },
  "angularCompilerOptions": {
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "enableResourceInlining": true
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts"
  ],
}
```
5- In `projects/my-lib/src/lib/my-lib.component.ts`, add `import { environment } from '@env/environment';` and create this property : `isProduction = environment.production;`
6- compile the library : `ng build my-lib` (this gives the warning)
7- Also, import MyLibModule in AppModule then try to build the project : `ng build` (this gives the error message)

## 🔥 Exception or Error

Warning when trying to build the library : 
<pre><code>
`WARNING: No name was provided for external module '@env/environment' in output.globals – guessing 'environment'`
</code></pre>

Error message when trying to build the project
<pre><code>
ERROR in projects/my-lib/src/lib/my-lib.component.ts:2:29 - error TS2307: Cannot find module '@env/environment'.

2 import { environment } from '@env/environment';
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.2
Node: 10.19.0
OS: linux x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.2
@angular-devkit/build-angular      0.900.2
@angular-devkit/build-ng-packagr   0.900.2
@angular-devkit/build-optimizer    0.900.2
@angular-devkit/build-webpack      0.900.2
@angular-devkit/core               9.0.2
@angular-devkit/schematics         9.0.2
@angular/cli                       9.0.2
@ngtools/webpack                   9.0.2
@schematics/angular                9.0.2
@schematics/update                 0.900.2
ng-packagr                         9.0.0
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Anything else relevant?**
I don't think so

**Comment by flash-me** [comment]
Hi,

1. you defined the path `my-lib` but directly import your module in [app.module](https://github.com/ArnaudDenoyelle/sscce-angular9-paths/blob/master/src/app/app.module.ts#L5)
2. Yes, this is what paths are for. It doesn't matter if angular handles it as an external module or not. 

Despite I completely do not understand why you map @env to a path, which is already in `projects/my-lib`, here maybe some help:
- You compile your my-lib with a tsconfig which maps @env/* --> projects/my-lib/src/environments/* [tsconfig.lib.json]
- Now you compile your app together with your my-lib using a tsconfig without a mapping. [tsconfig.app.json]
- Compiler reaches a point @env/*  [tsconfig.app.json]
- Compiler has no mapping for this [tsconfig.app.json]
- Compiler fails.

Maybe this logical issue helpes. Its not recommended to use path mappings for libaries.

Solution: 
1. Either you remove the mapping
2. Or you add a mapping to tsconfig.app.json

Cheers
flash ⚡️

**Comment by alan-agius4** [comment]
@flash-me did a great investigation and summed it all. 

Note: that `baseUrl‘ is not a child property of `paths` but rather it’s a property of `compilerOptions`.

That said, I think this issue can be closed as path mappings in a library were never supported, and shouldn’t have ever worked and in your case it seems that they worked because of ts configuration leaking from the library to your application.

See: https://github.com/ng-packagr/ng-packagr/pull/1502 for more context.

**Comment by ArnaudDenoyelle** [comment]
Thank both of you for the quick answer. 

I was using `enviroment.ts` in order to be able to change library parameters from the `environment.ts` of the application. Now, I better understand how it works and I also understand that using `environment.ts` like this was a terrible idea. 

I refactored the code and replaced `environment.ts` with parameters injected with an `InjectionToken`. Now, it works like a charm :+1:
