### ISSUE TITLE
export 'DOCUMENT' (imported as 'i10') was not found in '@angular/platform-browser' while ng build --prod

### ISSUE THREAD

**Issue by singhawanish** [angular/angular#35492]
I faced this issue while migrating to angular 8.x.x . Actually 'DOCUMENT' has been deprecated from '@angular/platform-browser' and is now part of '@angular/common'. Older plugin still try to import document from '@angular/platform-browser' . Just check in the .js and .js.map files under 'fesm5' as well as 'fesm2015' folder of the plugin in node_modues section.

Better to update the specific plugin to latest angular compatible version.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
