### ISSUE TITLE
NPM Libary leads to error:  Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

### ISSUE THREAD

**Issue by chrisaige** [angular/angular#35495]
We have a libary that is published on npm and code can be found here (https://github.com/porscheinformatik/material-addons)

I have created a demo project that I am unable to build with the above error.
I published an example project here:
https://github.com/chrisaige/angular-ivy-example

I think we are building our library wrong? But what are we doing wrong?
It seems tobe related to https://github.com/angular/angular/issues/30972 but I don't think we are minifying our libary.

**Comment by flash-me** [comment]
Hi,

can you try to set `importHelpers: true` for you [tsconfig.lib.json](https://github.com/porscheinformatik/material-addons/blob/master/projects/material-addons/tsconfig.lib.json)?

Und viele Grüße an das MIB3 Infotainment Projekt :) 

cheers
flash :zap:

**Comment by gkalpak** [comment]
@chrisaige, @flash-me: Can you try with the build artifacts from [here][1]? (See [there][2] for details on how to use them.)
Does it fix your issues?

[1]: https://circleci.com/gh/angular/angular/623221#artifacts/containers/0
[2]: https://github.com/angular/angular/blob/b2222e7e0/docs/DEVELOPER.md#getting-packages-from-build-artifacts

**Comment by chrisaige** [comment]
Seems like importHelpers solved this issue for me.

Now I seem tobe getting this issue. Possible regression? I'll make a new issue
https://github.com/angular/angular-cli/issues/2034

**Comment by flash-me** [comment]
> Now I seem tobe getting this issue. Possible regression? I'll make a new issue
> [angular/angular-cli#2034](https://github.com/angular/angular-cli/issues/2034)

Typo? #2034 is from 2016

Cheers
flash :zap:

**Comment by chrisaige** [comment]
No it really looks exactly like this error.
He is unable to import a d.ts file (only when building PROD. AOT works). I'm fiddling with the tsconfig to try to find the issue. I am not able to reproduce it with my example. Seems like something in our angular library structure goes wrong.
I'll try to make a reproducible example.

**Comment by chrisaige** [comment]
https://github.com/angular/angular-cli/issues/4874 seems more like this. When I rename my generated d.ts files to ts everything works. Weird. I'll try to create a repo
