### ISSUE TITLE
ERROR in The given rootPath undefined is not a file of the program.

### ISSUE THREAD

**Issue by dolanmiu** [angular/angular#35504]
When upgrading to Angular 9:

![Screenshot 2020-02-17 at 16 52 39](https://user-images.githubusercontent.com/2917613/74672804-ee701d00-51a5-11ea-8cdd-866c2e851329.png)

**Comment by sacgrover** [comment]
@dolanmiu Need more details to reproduce.

**Comment by JoostK** [comment]
Where the error says `undefined` it _should_ have mentioned an actual path, but there's a bug here https://github.com/angular/angular/blob/5b42084912f6bc8bdc419b0893fe3e25351719dc/packages/compiler-cli/ngcc/src/host/esm2015_host.ts#L2068 so that the error becomes of little value.

Could you provide a repro, preferably a repository on Github? There may be some library that is causing an issue here but we'd more details to be able to investigate.

It might also be helpful to add a `console.log(bundle.path);` in `node_modules/@angular/compiler-cli/ngcc/src/host/esm2015_host.js` just before that error is thrown, so that the path is properly shown somewhere.

**Comment by spencerfontein** [comment]
I have same issue

**Comment by aubweb9** [comment]
Same issue here also after updating my project to Angular 9

**Comment by krishnakant4** [comment]
ERROR in The given rootPath undefined is not a file of the program.

**Comment by dolanmiu** [comment]
I tried to add the console log in, but it doesn't log anything to the console. Are you sure ` node_modules/@angular/compiler-cli/ngcc/src/host/esm2015_host.js` is the right file?

![Screenshot 2020-02-18 at 10 47 57](https://user-images.githubusercontent.com/2917613/74729330-304ba280-523c-11ea-9bb8-fabff9f38e9e.png)

![Screenshot 2020-02-18 at 10 49 17](https://user-images.githubusercontent.com/2917613/74729408-57a26f80-523c-11ea-956e-ed90ef24cc86.png)

**Comment by dolanmiu** [comment]
Can someone else publish their repo?? I can't publish mine as it is company proprietary code.

**Comment by tgangso** [comment]
Also having this issue after upgrading, building w/o ivy works fine.

**Comment by dolanmiu** [comment]
> Also having this issue after upgrading, building w/o ivy works fine.
> 
> bundle.path refers to angular-sortablejs/dist/index

I use `angular-sortablejs`, maybe thats the culprit?

**Comment by tgangso** [comment]
I can confirm it compiles after removing angular-sortablejs

**Comment by EmaGht** [comment]
> 
> 
> @JoostK I tried to add the console log in, but it doesn't log anything to the console. Are you sure ` node_modules/@angular/compiler-cli/ngcc/src/host/esm2015_host.js` is the right file?
> 
> Can someone else try this?
> 
> ![Screenshot 2020-02-18 at 10 47 57](https://user-images.githubusercontent.com/2917613/74729330-304ba280-523c-11ea-9bb8-fabff9f38e9e.png)
> 
> ![Screenshot 2020-02-18 at 10 49 17](https://user-images.githubusercontent.com/2917613/74729408-57a26f80-523c-11ea-956e-ed90ef24cc86.png)

Instead of using console.log(), just substitute "rootFile" with "bundle.path" in the exception throw

**Comment by tgangso** [comment]
Builds fine after replacing angular-sortablejs with ngx-sortablejs.

**Comment by dolanmiu** [comment]
> > @JoostK I tried to add the console log in, but it doesn't log anything to the console. Are you sure ` node_modules/@angular/compiler-cli/ngcc/src/host/esm2015_host.js` is the right file?
> > Can someone else try this?
> > ![Screenshot 2020-02-18 at 10 47 57](https://user-images.githubusercontent.com/2917613/74729330-304ba280-523c-11ea-9bb8-fabff9f38e9e.png)
> > ![Screenshot 2020-02-18 at 10 49 17](https://user-images.githubusercontent.com/2917613/74729408-57a26f80-523c-11ea-956e-ed90ef24cc86.png)
> 
> Instead of using console.log(), just substitute "rootFile" with "bundle.path" in the exception throw

I replaced rootFile with bundle.path, and yes! I found the problem. Thank you very much

![Screenshot 2020-02-18 at 12 31 24](https://user-images.githubusercontent.com/2917613/74736447-a6570600-524a-11ea-84dd-97f04a2fccad.png)

**Comment by dolanmiu** [comment]
I can confirm that upgrading `angular-sortablejs` to `ngx-sortablejs` fixed the problem!!!

**Comment by petebacondarwin** [comment]
Thanks for the update @dolanmiu .
