### ISSUE TITLE
document angular 2 expression syntax

### ISSUE THREAD

**Issue by skybrian** [angular/angular#3550]
There seems not to be any documentation for the grammar of an Angular 2 expression. (For example, the value of *ng-for or *ng-if.)

**Comment by pkozlowski-opensource** [comment]
@skybrian the general template syntax is documented here: https://github.com/angular/angular/blob/master/modules/angular2/docs/core/01_templates.md and individual directives got their docs with syntax examples here:
* https://angular.io/docs/js/latest/api/directives/NgFor-class.html
* https://angular.io/docs/js/latest/api/directives/NgIf-class.html
* more generally: https://angular.io/docs/js/latest/api/directives/

We are going for sure to improve docs, but if there are particular points that you don't see clarified in the linked docs, it would be great if you could send us more specific suggestions (or better yet - a pull request).

**Comment by skybrian** [comment]
Thanks, that's helpful.

I was looking on angular.io for something similar to the "Expressions, Statements and Formatters" section in the the first document you linked to. (I didn't think to look for documentation on github and it didn't show by searching for "expression" or "expressions" on angular.io.)

In Angular 1 documentation there is a page about expressions here:
https://docs.angularjs.org/guide/expression

However, the problem is that it's a list of design principles about the expression language, rather than actually explaining the expression grammar.

The specific thing I was trying to do was to write an if statement inside a for loop. Specifically, what goes in place of ??? in this snippet:

<li *ng-for="#line of tokenLines">
<template [ng-if]="???  == cursorTokenLine">
*
</template>
<span *ng-for="#token of line.tokens">{{ token }} </span>
</li>

I tried "line" and "#line" and neither one worked. Without any documentation about what's legal in an expression or which variables are in scope, I don't know what else to try, so I implemented it a different way.

**Comment by pkozlowski-opensource** [comment]
@naomiblack is there any particular reason for not publishing https://github.com/angular/angular/tree/master/modules/angular2/docs on https://angular.io? 

While not perfect, those docs would be very useful, IMO - especially that it is rather hard to read them on GH

**Comment by mhevery** [comment]
@naomiblack can you comment on https://github.com/angular/angular/issues/3550#issuecomment-129362284

**Comment by nkwood** [comment]
:+1: on @pkozlowski-opensource's comment as a user trying to get up to speed. Personally it took me an embarrassingly long time to realize the docs in the modules/angular2/docs tree were different (and appeared to be far more up to date) than those at https://angular.io.

**Comment by naomiblack** [comment]
We now have a guide to Template Syntax (https://angular.io/docs/ts/latest/guide/template-syntax.html) and a Cheat Sheet (http://angular.io/cheatsheet) that address this need.

**Comment by skybrian** [comment]
I don't think this is finished yet for Dart. If I change the "Angular 2 for Typescript" pulldown to "Angular 2 for Dart, it directs to [1]. I was also under the impression that the expression language is somewhat different for Dart.

[1] https://angular.io/docs/dart/latest/guide/
