### ISSUE TITLE
Force single quote for *.ts files in .editorconfig

### ISSUE THREAD

**Issue by HoTKreeZy** [angular/angular#35519]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....

### Description
When saving typescript files, my editor format my code and change single quoted string to double quote.
I use Prettier and tslint extensions and I didn't change anything in my vs-code settings.

### Describe the solution you'd like
It would be simple to force single quote within `.editorconfig` file.
Just add: 
```md
[*.ts]
quote_type = single
```

**Comment by ericmartinezr** [comment]
Please open cli issues in cli's repo https://github.com/angular/angular-cli 👍

**Comment by HoTKreeZy** [comment]
Okay, I did it. Sorry for that..
