### ISSUE TITLE
bug in $location.search()

### ISSUE THREAD

**Issue by vahidalvandi** [angular/angular#3551]
my url is
mysite.com#/?userID=abc

i need get userID parameters and use 

params_get_from_url = ($location.search().userID);

in console::
params_get_from_url.lenght   >>> ' 3'

while should '1' array Instead  '3 '

please help me.

**Comment by pkozlowski-opensource** [comment]
@vahidalvandi this is wrong repo, I guess you are looking for https://github.com/angular/angular.js

Having said this I'm not sure while you are considering this a bug...  `$location.search().userID` would return string `abc` which has length 3... So I'm not sure what your problems is and as a consequence it is not easy to help you. 

In any case, this sounds like a support question and as such should be asked using an appropriate support channel, see: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by vahidalvandi** [comment]
ok abc is string whit 3 lenght but if url have two parameters it return 2 Namely it is array whit 2 object

for example 
mysite.com#/?userID=abc
return abc

for example
mysite.com#/?userID=abc&userID=def
return ['abc','def']

i need return ['abc'] for  mysite.com#/?userID=abc 


please help me
