### ISSUE TITLE
Language Service: Template Binding Parser

### ISSUE THREAD

**Issue by ayazhafiz** [angular/angular#35512]
# 🚀 feature request

### Relevant Package

@angular/language-service 

## Description

Today, the Language Service relies entirely on the Angular compiler for parsing of template source code. In most cases, this is the ideal solution. A notable exception is the parsing of template bindings -- while the compiler preserves _template semantics_ of parsed bindings, it does not preserve their _expression semantics_. This distinction is now elaborated.

A template semantic refers to the semantic of the template binding in relation to the rest of the template. For example, given the expression

```html
<div *ngFor="let num of nums; index as i; trackBy: hasher"></div>
```

a run of the `ngFor` template attribute through the template binding parser gives a set of ASTs looking something like

```typescript
TemplateBinding {
  key: "*ngForOf",
  name: null,
  expression: {ast: PropertyRead {
    name: "nums",
    receiver: "$implicit", // note that the variable "num" is not preserved in this AST!
  } },
}
```

```typescript
TemplateBinding {
  key: "i",
  name: "index",
  keyIsVar: true, // gets transformed into a variable later
  expression: null,
}
```

```typescript
TemplateBinding {
  key: '*ngForTrackBy',
  keyIsVar: false,
  name: null,
  expression: {ast: PropertyRead {
      receiver: "$implicit", // note that the target 'trackBy' is not preserved here either
      name: 'hasher',
  } },
}
```

So while these ASTs preserve semantics of bindings in terms of how they impact an evaluation of a template, they do not preserve the semantic of the expression itself -- by looking at the first AST, for example, it is not clear that the template binding is a `let .. of ..` expression that targets the `num` variable from the `nums` container.

A lack of preserved expression semantics has proven inconvenient for the Language Service. Today, to provide useful completions for template bindings, the Language Service largely performs string matching on a variety of conditions. One extreme example of this is #35096. This solution is unpleasant and rather brittle.

This issue proposes creating a module in the Language Service for parsing template bindings in a manner that preserves their expression semantic, replacing existing string matching hacks for template binding operations in the Language Service with operations on these new template binding ASTs, and potentially backporting the ASTs to the compiler if they are mutually advantageous.

Ideally, the ASTs will implement the [microsyntax grammar](https://gist.github.com/mhevery/d3530294cff2e4a1b3fe15ff75d08855).

I propose the following AST structure:

```typescript
TemplateBinding = Expression | LetBinding | AsBinding | KeyExpressionBinding
Expression = (Angular expression)

// let num of nums
// let i = index
LetBinding {
  span: Span,
  lhs: string & Span, // TODO: better name
  rhs: string & Span, // string & Span just means we will keep track of both a string name and the span location
  operator: string & Span, // 'of' or '=', for example
}

// index as i
AsBinding {
  span: Span
  lhs: string & Span, // TODO: better name
  rhs: string & Span,
}

// trackBy: trackFn
KeyExpressionBinding: {
  span: Span,
  lhs: string & Span, // TODO: better name
  rhs: string & Span,
}
```

Given the expression

```html
*ngFor="let num of nums; index as i; trackBy: hasher"
```

the resultant AST would look something like

```typescript
MicrosyntaxAttribute {
  name: "*ngFor",
  bindings: [
    LetBinding {lhs: "num", rhs: "nums", operator: "of"},
    AsBinding {lhs: "index", rhs: "i"},
    KeyExpressionBinding {lhs: "trackBy", rhs: "hasher"},
  ],
}
```

With these ASTs, it is still possible to reconstruct the name of the input to a structural directive from looking at the expression AST. For example, given a `LetBinding` with operator `of` and knowing that this binding belongs to a `MicrosyntaxAttribute` of name `ngFor`, we can deduce that the binding input is `ngForOf`.

### Needs Discussion

- Should we store the targeted input name on the AST?
- How can these ASTs be improved?
- Compiler team: can you provide more insight on how `let ... of ...` bindings work? From my experimentation the `of` operator can actually be any identifier. Is there additional information we should be aware of here other than the existing template binding source code?

cc @alxhub @kyliau @andrius-pra @ivanwonder 

# __Comments from all are highly appreciated!__

**Comment by kyliau** [comment]
According to the docs that Misko wrote, I don't think there's actually a rhs to `let` binding.
For example, the following is a valid template:
```
<div *ngFor="let x, let y; of items; let z">
  <p>x = {{x}}, y = {{y}}, z = {{z}}</p>
</div>
```
In this case, all variables `x`, `y`, and `z` are the iterators of `items`.
It is still the case they get bound to `items`, but that's more of the template semantics rather than the expression semantics.

I am not sure how exactly the symbols get bound to the target, because while the example above is a valid template, the one below is not, even though it adheres to the grammar.
```
    <div *ngFor="of items; let z">
      <p>z = {{z}}</p>
    </div>
```

**Comment by ivanwonder** [comment]
> I am not sure how exactly the symbols get bound to the target, because while the example above is a valid template, the one below is not, even though it adheres to the grammar.
> 
> ```
>     <div *ngFor="of items; let z">
>       <p>z = {{z}}</p>
>     </div>
> ```

The example above is not a valid template.
```
*:prefix="( :let | :expression ) (';' | ',')? ( :let | :as | :keyExp )*"
```
The valid template must start with `:let` or `:expression`, but `of items;` is a `:keyExp`.

**Comment by ivanwonder** [comment]
> for example, it is not clear that the template binding is a `let .. of ..` expression that targets the `num` variable from the `nums` container.

I think the `let ... of ...` is two separate expressions, and the type of `num` is retrieved by the `ngTemplateContextGuard ` which is used by the Ivy template type-check compiler.
https://angular.io/api/common/NgForOf#ngtemplatecontextguard

**Comment by ayazhafiz** [comment]
> The valid template must start with `:let` or `:expression`, but `of items;` is a `:keyExp`.

> I think the `let ... of ...` is two separate expressions

@ivanwonder Yes, in fact it is a LetExpression followed by a KeyExpression. This was not at all clear to me, but your first comment helped realize it. Thank you.

> According to the docs that Misko wrote, I don't think there's actually a rhs to `let` binding.

@kyliau You're right; this suggests that the linked docs are somewhat inaccurate. We will need to get consensus on the grammar of a LetExpression in this case. In any case, what I hope to exemplify is that by differentiating the variable binding (what is typically the "LHS") and the value (what is typically the "RHS") in a template binding AST, the language service will have an easier of way of locating where exactly in a LetExpression it is. This makes conditional generation of completions a more streamlined process. Of course, as you mention, the RHS may not always exist.

**Comment by ivanwonder** [comment]
> Given the expression
> 
> ```
> *ngFor="let num of nums; index as i; trackBy: hasher"
> ```
> 
> the resultant AST would look something like
> 
> ```ts
> MicrosyntaxAttribute {
>   name: "*ngFor",
>   bindings: [
>     LetBinding {lhs: "num", rhs: "nums", operator: "of"},
>     AsBinding {lhs: "index", rhs: "i"},
>     KeyExpressionBinding {lhs: "trackBy", rhs: "hasher"},
>   ],
> }
> ```
I think the AST should be like
```
MicrosyntaxAttribute {
  name: "*ngFor",
  bindings: [
    LetBinding {lhs: "num", rhs: null},
    KeyExpressionBinding {lhs: "of", rhs: "nums"},
    AsBinding {lhs: "index", rhs: "i"},
    KeyExpressionBinding {lhs: "trackBy", rhs: "hasher"},
  ],
}
```

**Comment by kyliau** [comment]
I think it'll be easier to reason about the microsyntax expression if we look at the expanded form:
```
*ngFor="let item of [1,2,3] as items; trackBy: myTrack; index as i"
```
```
<ng-template ngFor let-item [ngForOf]="[1,2,3]" let-items="ngForOf" 
             [ngForTrackBy]="myTrack" let-i="index">
```
In this case, yes, `let-item` does not have a `rhs`.
