### ISSUE TITLE
Styles not renderd with renderComponent (ɵrenderComponent)

### ISSUE THREAD

**Issue by KartoffelToby** [angular/angular#35526]
Hello in the issue https://github.com/angular/angular/issues/32179#issuecomment-523220131
There is an answer about rendering a component with styles, but i did't get it.

Running Angular 9 with ivy

my example code:

```
import {
    ɵrenderComponent as renderComponent,
    ɵdetectChanges as detectChanges,
    ɵLifecycleHooksFeature as LifecycleHooksFeature,
    Injector
  } from '@angular/core';
....
    async renderComponent() {
      const { HelloWorldComponent } = await import('./hello-world.component');
      this.component = renderComponent(HelloWorldComponent, { 
        host: this,
        **rendererFactory: Didn't know what to do here.**
        hostFeatures: [
          LifecycleHooksFeature,
        ],
        injector: this.injector
      });
      this.component.text = this.text;
      detectChanges(this.component);
    }
```

Thanks!

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
