### ISSUE TITLE
Angular test override promise with an error

### ISSUE THREAD

**Issue by Swoox** [angular/angular#35520]
# 🐞 bug report

### Affected Package
   "@angular/core": "8.3.25"
   "@angular/core": "^9.0.1"

### Is this a regression?
Tested it on version 4 also got the same error (in the console).

### Description
So I have one call, well actually my application have 2 the same calls.
For this example it doesn't matter, but anyway I have a promise that return a resolve or a reject.
When I call the promise with a succes on the ngOnInit and then reject it in the case it gives an error.

## 🔬 Minimal Reproduction
The test runs but gives an error in the **console**.
This error is making **my test** fail (it doesn't in the example).
https://stackblitz.com/edit/github-test-run-draft-8d3mkl?file=src%2Fapp%2Fapp.component.spec.ts

## 🔥 Exception or Error
`Error: Uncaught (in promise): [object String]`
My error: 
<pre><code>
Error: Uncaught (in promise): [object String]
error properties: Object({ rejection: '', promise: [object Promise], zone: Zone({ _parent: Zone({ _parent: null, _name: '<root>', _properties: Object({  }), _zoneDelegate: ZoneDelegate({ _taskCounts: Object({ microTask: 0, macroTask: 0, eventTask: 0 }), zone: <circular reference: Object>, _parentDelegate: null, _forkZS: null, _forkDlgt: null, _forkCurrZone: null, _interceptZS: null, _interceptDlgt: null, _interceptCurrZone: null, _invokeZS: null, _invokeDlgt: null, _invokeCurrZone: null, _handleErrorZS: null, _handleErrorDlgt: null, _handleErrorCurrZone: null, _scheduleTaskZS: null, _scheduleTaskDlgt: null, _scheduleTaskCurrZone: null, _invokeTaskZS: null, _invokeTaskDlgt: null, _invokeTaskCurrZone: null, _cancelTaskZS: null, _cancelTaskDlgt: null, _cancelTaskCurrZone: null, _hasTaskZS: null, _hasTaskDlgt: null, _hasTaskDlgtOwner: null, _hasTaskCurrZone: null }) }), _name: 'ProxyZone', _properties: Object({ ProxyZoneSpec: ProxyZoneSpec({ defaultSpecDelegate: null, name: 'ProxyZone', _delegateSpec: null ...
Error: Uncaught (in promise): [object String]
    at resolvePromise (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone.js:852:1)
    at http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone.js:762:1
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 8.3.22
Node: 10.15.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.25
@angular-devkit/build-angular     0.803.25
@angular-devkit/build-optimizer   0.803.25
@angular-devkit/build-webpack     0.803.25
@angular-devkit/core              8.3.25
@angular-devkit/schematics        8.3.22
@angular/cdk                      8.2.3
@angular/cli                      8.3.22
@angular/material                 8.2.3
@ngtools/webpack                  8.3.25
@schematics/angular               8.3.22
@schematics/update                0.803.22
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.39.2

</code></pre>

**Comment by atscott** [comment]
This issue is not caused by Angular. Your `.and.returnValue(Promise.reject(''))` is generating a rejected promise in the test after that line executes. You should instead do `.and.callFake(() => Promise.reject(''))` to have your spy return a promise rejection that is handled by your component: https://stackblitz.com/edit/github-test-run-draft-dexbfv?file=src%2Fapp%2Fapp.component.spec.ts
