### ISSUE TITLE
updating angular 8 to 9

### ISSUE THREAD

**Issue by devtestrw** [angular/angular#35521]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: 
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

i have updated  my angular version from 8 to 9 
Then after i do ng serve my cli is giving following which i am not able to debug

ERROR in Failed to resolve styles[0] to a string
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/34389

**Comment by devtestrw** [comment]
I have referred your above comments . but still i didn't get the  solution for this bug
