### ISSUE TITLE
Ivy regression: null-check issue with cross-referencing components in template

### ISSUE THREAD

**Issue by merobal** [angular/angular#35522]
# 🐞 bug report

### Is this a regression?

Yes, the previous version in which this bug was not present was: any version without Ivy.

### Description

Our use-case is: we have multiple form fields and we need to reset its value after any other form field value change.
The solution we implemented works perfectly without Ivy or if we set `fullTemplateTypeCheck` to `false` or if we have only 1 reference.
However since this is the only issue we get with Ivy, and works well if we remove any of the other references, we assume it's a regression and we expect to work well.
Switching off `fullTemplateTypeCheck` is not an acceptable workaround for us.

## 🔬 Minimal Reproduction

See a full project set up to reproduce this error: https://github.com/merobal/ivy-null-check

```
<app-handler-a #handlerA [resetOn]="handlerB.triggerChange"></app-handler-a>
<app-handler-b #handlerB [resetOn]="handlerA.triggerChange"></app-handler-b>

<!--
  NOTE: any of the following implementations works without errors
  <app-handler-a #handlerA></app-handler-a>
  <app-handler-b #handlerB [resetOn]="handlerA.triggerChange"></app-handler-b>
  OR
  <app-handler-a #handlerA [resetOn]="handlerB.triggerChange"></app-handler-a>
  <app-handler-b #handlerB></app-handler-b>
  OR "fullTemplateTypeCheck" set to false
  OR "enableIvy" set to false
-->
```

## 🔥 Exception or Error
```
ERROR in src/app/app.component.html:2:37 - error TS2531: Object is possibly 'null'.

2 <app-handler-b #handlerB [resetOn]="handlerA.triggerChange"></app-handler-b>
                                      ~~~~~~~~~~~~~~~~~~~~~~

  src/app/app.component.ts:5:16
   5   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.2
Node: 10.19.0
OS: linux x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by ericmartinezr** [comment]
Related/dup https://github.com/angular/angular/issues/35372, otherwise ignore.

**Comment by JoostK** [comment]
Agreed that this has the same root cause as #35372.

You _might_ be able to workaround this using `$any(handlerB).triggerChange`.

**Comment by merobal** [comment]
That's a perfect workaround meantime, thank you!
