### ISSUE TITLE
Http module should also resolve url (include base url)

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#3553]
While creating the Node version (for [universal#73](https://github.com/angular/universal/pull/73)) I ran into a problem where we needed the url to be resolved with a baseUrl before it's sent. We had to recreate `XHRConnection` as `NodeConnection` in order to find out the error was being thrown on `.send()`. What was suppose to be a simple `BrowserXhr` di swap to `NodeXhr` turned into recreating the `ConnectionBackend`, `NodeConnection`, and `BrowserXhr`. 

## proposal
allow Http to use baseUrl and resolve it's Urls before sending them

<b>updated</b>:
I asked the `node-xhr2` maintainer to add a baseUrl feature. When the Universal App is ran on the server we can assume either the user set the baseUrl on the server (for load balancing etc) or we can grab the baseUrl from the tag (also needed for the router and probably rendered anyways from the server).

**Comment by jeffbcross** [comment]
> While creating the Node version (for universal#73) I ran into a problem where we needed the url to be resolved with a baseUrl before it's sent.

@gdi2290 can you give some more info on the use case you're trying to support? You want the app, running on the server, to make an http request for a resource on the same server? What is the actual url of the request that's being made, and what is it expected to be?

**Comment by robwormald** [comment]
This issue was moved to angular/http#67
