### ISSUE TITLE
Cannot open https://angular.io/guide/testing on Microsoft Edge 42.17134.1098.0

### ISSUE THREAD

**Issue by TienTT** [angular/angular#35531]
# 📚 Docs or angular.io bug report

### Description

 Cannot open https://angular.io/guide/testing on Microsoft Edge 42.17134.1098.0

### What's the affected URL?**
 https://angular.io/guide/testing
## 📷Screenshot

![error](https://user-images.githubusercontent.com/13187826/74763541-00a59600-524e-11ea-82c5-d1efe7fddd88.PNG)

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Browser info

Microsoft Edge 42.17134.1098.0

**Comment by ericmartinezr** [comment]
Does the console show something?...

**Comment by gkalpak** [comment]
It works for me 🤔
(It takes a while to load, because it is a long guide, but it loads eventually.)

Maybe try clearing your cache and/or ServiceWorker.

**Comment by TienTT** [comment]
> Does the console show something?...

![error_Console](https://user-images.githubusercontent.com/13187826/74838048-d1943080-52f0-11ea-8c21-31216b260bc3.PNG)

**Comment by TienTT** [comment]
Also there are couple of pages could not load.

![image](https://user-images.githubusercontent.com/13187826/75494545-7dd9b500-598a-11ea-9dd9-363f7d0df9ba.png)
![image](https://user-images.githubusercontent.com/13187826/75494596-9fd33780-598a-11ea-9ba6-e7a88f02f061.png)

I could not capture all the pages, please have check the remaining page.

**Comment by gkalpak** [comment]
Sorry, I cannot reproduce this 😞 (I am on Edge 44.19041.1.0 on Windows 10.)

**Comment by pkozlowski-opensource** [comment]
Sounds like we were not able to reproduce it and we haven't heard other similar reports in ~3 months so I guess it was either a temporary problem or something related to the user environment. Closing for now, if anyone bumps into similar problems, please open a new issue.
