### ISSUE TITLE
Ivy input binding and directive dependancy

### ISSUE THREAD

**Issue by hugoj-goncalves** [angular/angular#35535]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Angular 9 without Ivy enabled.

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://github.com/hugoj-goncalves/angular9-ivy-fun/blob/master/src/app/my-input/my-base-input.directive.ts#L25

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.1
Node: 12.16.0     
OS: win32 x64     

Angular: 9.0.0    
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

With Ivy enabled [this](https://github.com/hugoj-goncalves/angular9-ivy-fun/blob/master/src/app/my-input/my-base-input.directive.ts#L25) fails because the formGroup is not defined yet.
Was this change intentional?

**Comment by JoostK** [comment]
This is a know breaking change, it's [listed in the compatibility guide](https://angular.io/guide/ivy-compatibility):

> Unbound inputs for directives (e.g. name in `<my-comp name="">`) are now set upon creation of the view, before change detection runs (previously, all inputs were set during change detection).


This issue is being tracked here: #34227
