### ISSUE TITLE
IVY: Server side rendering error

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#35549]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

`@angular/core`
`@angular/platform-server`

### Is this a regression?

Do not know.

### Description

When running server side rendering with IVY and Angular 9 it fails with error.

>TypeError: Cannot create property 'tView' on boolean 'true'

## 🔬 Minimal Reproduction

> `git clone https://github.com/kukjevov/ng-universal-demo.git`
> `git checkout ivy/1.0`
> `npm install`
> `npm run build:ssr`
> `npm run server`
> open browser at `http://localhost:8888`

## 🔥 Exception or Error

TypeError: Cannot create property 'tView' on boolean 'true'

## 🌍  Your Environment

**Angular Version:**
Angular 9.0.1

**Anything else relevant?**
Windows: 10.0.17763
Node: 11.6.0
NPM: 6.9.0

**Comment by AndrewKushnir** [comment]
Hi @kukjevov,

I tried to follow the steps you provided, but faced the following error while running `npm install`:

```
> ng-universal-demo@1.0.0 build:gulp /Users/akushnir/work/ng-universal-demo
> gulp build

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
```

I use MacOS 10.14.6, Node v12.14.1 and NPM v6.13.4.

Could you please check instructions once again to see if the app builds successfully?

Thank you.

**Comment by kukjevov** [comment]
Gulp 3 is not compatible with Node 12+ i can try to update it to gulp 4.

**Comment by kukjevov** [comment]
Ok i have updated gulpfile to v4, now it should work with Node 12+. You can test it now

**Comment by AndrewKushnir** [comment]
@kukjevov thanks for the update.

I am still unable to run it with Node v12, but the build went fine with Node v11 (11.10.1). The app was built successfully and I haven't seen the mentioned error (related to `tView`) in the browser (Chrome 80) console - the app loads on a page. The only error I've seen in the console is `Uncaught Error: Missing: jasmine.js`, but I believe the error is unrelated to the one you originally reported. Is there any particular scenario I should follow (like clicking some buttons/links, etc) to reproduce the issue?

Thank you.

**Comment by kukjevov** [comment]
@AndrewKushnir hmm that is weird.

Could be this connected to OS ? What do you see when you run it in browser and you turn off javascript?

**Comment by AndrewKushnir** [comment]
@kukjevov here is the content of the page when JS is disabled (what's coming from the server):
```

<div class="no-ie">Váš internetový prehliadač nie je podporovaný, prosím použite iný internetový prehliadač.</div>
<div class="no-grid alert alert-warning text-center">Váš internetový prehliadač nepodporuje všetky požadované funkcie, zobrazenie stránok v tejto aplikácii nebude správne, prosím použite iný internetový prehliadač.</div>
<app>
  <div class="loading-indicator">
    <div></div>
  </div>
</app>
```

Is that the expected output?

**Comment by kukjevov** [comment]
@AndrewKushnir hmm no, this looks like Server Side Rendering is not running at all.

Did you run `npm run build:ssr` and can you check if in `wwwroot/dist` is `server.es2015.js` and if it is, can you check that this line is ran by your server https://github.com/kukjevov/ng-universal-demo/blob/ivy/1.0/server.js#L119 or put there `console.log`.

**Comment by kukjevov** [comment]
any progrss here?

**Comment by AndrewKushnir** [comment]
Hi @kukjevov,

I was able to reproduce the problem and started to look at the code in the repro and found out that it contains a number of NgModules and Components.

Could you please help simplify the repro to include minimum possible setup/config and content and may be help determine if there is any particular Component that triggers the problem (i.e. if removing some Components make the problem go away)?

Thank you.

**Comment by kukjevov** [comment]
Thx @AndrewKushnir i will look into it tomorrow.

**Comment by kukjevov** [comment]
Hi @AndrewKushnir i have found out where was the problem. Problem is that i have custom build and problem was explicitly setting `ngDevMode`.

**Comment by kukjevov** [comment]
Ok I am closing this as it was my mistake and now it is working like a charm and it is incredible fast, love it :). Thx for all you help :)

**Comment by AndrewKushnir** [comment]
Thanks for the update @kukjevov!
