### ISSUE TITLE
fragmentation $location.search() string

### ISSUE THREAD

**Issue by vahidalvandi** [angular/angular#3554]
i have problem with return function $location.search()

i need allway return array. 
///////////////////
for example url with one parameter
mysite.com#/?userID=abc
params_get_from_url = ($location.search().userID);
in console.log(params_get_from_url)  return abc
/////////////////
example with two parameters

mysite.com#/?userID=abc&userID=def
params_get_from_url = ($location.search().userID);
in console.log(params_get_from_url)  return ['abc','def']
/////////////////////
i need return ['abc']  instance abc 
for mysite.com#/?userID=abc

please help me

**Comment by pkozlowski-opensource** [comment]
@vahidalvandi as [already stated](https://github.com/angular/angular/issues/3551) this is wrong repository and not an appropriate forum to ask support questions. We want to keep GitHub issues for bug reports and future requests. Please direct support questions to one of the support channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

Side note: if you want to always return an array it could as simple as one-liner: `angular.isArray($location.search('userID')) ? $location.search('userID') : [$location.search('userID')]`
