### ISSUE TITLE
Update Angular From 8 to 9 

### ISSUE THREAD

**Issue by devtestrw** [angular/angular#35543]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: 
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

 I have updated my angular version from 8 to 9 
but i am stuck in the issue from a package "ngx-popover": "0.0.16"  which is not supported by new  version  because it is using Renderer

ERROR in node_modules/ngx-popover/PopoverContent.d.ts:1:81 - error TS2724: Module '"PATH/node_modules/@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

1 import { AfterViewInit, ElementRef, ChangeDetectorRef, OnDestroy, EventEmitter, Renderer } from "@angular/core";
                                                                                  ~~~~~~~~

  node_modules/@angular/core/core.d.ts:5692:31
    5692 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.

Please suggest  any method to solve this.
Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by santoshyadav198613** [comment]
Hi @devmeyster ,
The package ngx-popover is archived, please use another package and remove the mentioned package,

**Comment by pkozlowski-opensource** [comment]
> Please suggest any method to solve this.

We are not going to add back the `Renderer` interface as it was deprecated for years. But you've got several options:
* ask the package maintainer to migrate from `Renderer` to `Renderer2`;
* if the package is not maintained any more you can either fork it and make the changes yourself or use another package.

In any case there is nothing actionable on the Angular side so I'm going to close this issue.
