### ISSUE TITLE
Grandparent generic inputs not compiling

### ISSUE THREAD

**Issue by pburkindine** [angular/angular#35542]
Okay, this is a lazy bug report, we've tried to repro this with and without nx without success, but the report from a high-profile semi-complicated NX project is:

We tried to upgrade to A9 and ran into issues with grandparents-class-defined input and outputs not passing strict template compile (as not defined).  The grandfather is abstract and defined and barreled out in a different nx lib.

Current proposed workarounds:
1) Redeclare inputs in father classes - √ Works
2) export class in NgModule after refactoring as not-abstract - X untried
3) import class from tsconfig - √WORKS

**Comment by pburkindine** [comment]
Update: I tried the third approach above and was successful.

Since this worked before A9, this could be treated as a regression; the desired behavior would be for Angular to add abstract classes in other projects to the tsconfig imports during upgrade

**Comment by mhevery** [comment]
- Please follow our template format
- We need a repro otherwise there is nothing for us to go on.
- Please create a new issue with reproduction steps and follow the template.
