### ISSUE TITLE
HammerJs Gestures not working after Update to Angular 9

### ISSUE THREAD

**Issue by simon-sharp** [angular/angular#35547]
# 🐞 bug report

### Affected Package
HammerJs and @angular/platform-browser

### Is this a regression?
Yes, the previous version in which this bug was not present was: 8.2.14

### Description
I have used swipe gestures according to the description in https://medium.com/angular-in-depth/gestures-in-an-angular-application-dde71804c0d0

I lately found out that the swiperight and swipeleft gestures are not working any more. The error i get states "Event swiperight is not emitted by any applicable directives nor by div element"

## 🔥 Exception or Error
<pre><code>
Event swiperight is not emitted by any applicable directives nor by div element
</code></pre>
is occuring in webstorm

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.2
Node: 10.16.3
OS: linux x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**
Happens before the page gets loaded in the browser. Browser is therefore irrelevant

**Comment by JoostK** [comment]
Please see [the Ivy compatibility guide](https://angular.io/guide/ivy-compatibility):

> HammerJS support is opt-in through importing the `HammerModule` (previously, it was always included in production bundles regardless of whether the app used HammerJS).

**Comment by simon-sharp** [comment]
Works like a charm. Thank you very much.
