### ISSUE TITLE
Pipe is not working with concat in string interpolation

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#35544]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
No idea

### Description

 A clear and concise description of the problem...
I should able to use pipe inside concat with other string
```
  {{session.title + ' ' + '(' + session.date | date + ')'}}
```

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

core.js:4002 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Parser Error: Unexpected token '+' at column 49 in [ {{session.title + ' ' + '(' + session.date | date + ')'}}] in 
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.3.0
Node: 10.16.0
OS: win32 x64
Angular: 8.2.3
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.801.3
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.801.3
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.3.0
@angular/animations               8.2.5
@angular/cdk                      8.1.4
@angular/cli                      8.3.0
@angular/material                 8.1.4
@ngtools/webpack                  8.1.3
@schematics/angular               8.3.0
@schematics/update                0.803.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2

</code></pre>

**Anything else relevant?**

This will not work
![image](https://user-images.githubusercontent.com/23274631/74814215-ceaf3500-531c-11ea-897f-9eda85ae985d.png)

This will work
![image](https://user-images.githubusercontent.com/23274631/74814274-e4bcf580-531c-11ea-842f-2355efb4558d.png)

**Comment by JoostK** [comment]
You can achieve this using parenthesis around the usage of the pipe:

```
{{session.title + ' ' + '(' + (session.date | date) + ')'}}
```
