### ISSUE TITLE
RangeError: Maximum call stack size exceeded from NgIf_Factory

### ISSUE THREAD

**Issue by rerion** [angular/angular#35550]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
angular 8

### Description

angular throws 
![Capture](https://user-images.githubusercontent.com/3441535/74830845-52185880-5314-11ea-953e-dd9a5e5454be.PNG)

## 🔬 Minimal Reproduction

Setup: https://github.com/rerion/demo-broken-ivy

Serve app, and navigate to '/path1'.

## 🔥 Exception or Error
<pre><code>
ERROR Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at getOrCreateInjectable (core.js:5378)
    at Module.ɵɵdirectiveInject (core.js:20777)
    at NodeInjectorFactory.NgIf_Factory [as factory] (common.js:4740)
    at getNodeInjectable (core.js:5615)
    at instantiateAllDirectives (core.js:12662)
    at createDirectivesInstances (core.js:11898)
    at Module.ɵɵtemplate (core.js:20608)
    at InnerComponent_Template (app.component.ts:9)
    at executeTemplate (core.js:11858)
    at renderView (core.js:11644)
    at resolvePromise (zone-evergreen.js:793)
    at resolvePromise (zone-evergreen.js:752)
    at zone-evergreen.js:854
    at ZoneDelegate.invokeTask (zone-evergreen.js:400)
    at Object.onInvokeTask (core.js:40772)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:570)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

I encountered this issue when trying to provide minimal reproduction for: #31221

I noticed something fishy with nested structural directives instantiation and router,
and exploration of that behavior led me to this issue.

**Comment by AndrewKushnir** [comment]
Hi @rerion,

We performed an investigation and found out that the infinite loop happens because `InnerComponent` [is used in its own template recursively](https://github.com/rerion/demo-broken-ivy/blob/master/src/app/app.component.ts#L7) without any conditions to stop this recursion. I tested this behavior with View Engine and got the same error (`Maximum call stack size exceeded`). Since this problem is specific to `InnerComponent` implementation, I'll close this ticket. 

Thank you.
