### ISSUE TITLE
Angular Elements / Custom Components now supported in IE Edge?

### ISSUE THREAD

**Issue by hisham** [angular/angular#35556]
# 📚 Docs or angular.io bug report

In https://angular.io/guide/elements#browser-support-for-custom-elements you say IE Edge is working on an implementation to support custom elements. But according to https://caniuse.com/#search=custom%20elements, as of Jan 14, 2020, IE Edge does support custom components.  

See also https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

**Comment by mlc-mlapis** [comment]
@hisham Probably, it's already irrelevant with Edge based on Chromium (distributed in production now).

**Comment by kapunahelewong** [comment]
Fixed by the great @abraham! Thank you!!
