### ISSUE TITLE
publishConfig not allowing to publish on private repository

### ISSUE THREAD

**Issue by olakara** [angular/angular#35554]
Dear all,

 I am trying to publish angular packages to our private Azure DevOps (On-Prem environment with no internet access) Repository feed. All Angular packages have **publishConfig** in their package.json which breaks the `npm publish` command.

 How do I override the publishConfig settings in the tgz files ?

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
