### ISSUE TITLE
viewChild: call method from ViewChield instance in set Input Property

### ISSUE THREAD

**Issue by jhonyeduardo** [angular/angular#35552]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8

### Description
Hello

I have a library and my component call a method from childComponent when set a Input property.

The ViewChild uses { static: true }, but in set the property not find my child component only
in ngOnChanges, but in angular v8 works fine!

This really change in Angular 9, i can't use an ViewChild instance in set input properties?

## 🔬 Minimal Reproduction
<pre><code>
@Component({ ... })
ChildComponent {}

@Component({
  template: '<child-component></child-component>'
})
ParentComponent {
@ViewChild(ChildComponent , { static: true }) child : ChildComponent ;

@Input('p-title') set title(title: string) {
    this._title = title;

    this.child.recalculateHeaderSize();
}

 get title() {
   return this._title;
 }

}
</code></pre>

I know that i can use ngOnChanges, but would be a breaking changes because ngOnChanges isn`t fired when change the value with this.instaceComponent.title = 'HELLO';

## 🔥 Exception or Error
<pre><code>
Angular CLI: 9.0.2
Node: 10.16.3
OS: win32 x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.2
@angular-devkit/build-angular      0.900.2
@angular-devkit/build-ng-packagr   0.900.2
@angular-devkit/build-optimizer    0.900.2
@angular-devkit/build-webpack      0.900.2
@angular-devkit/core               9.0.2
@angular-devkit/schematics         9.0.2
@angular/cli                       9.0.2
@ngtools/webpack                   9.0.2
@schematics/angular                9.0.2
@schematics/update                 0.900.2
ng-packagr                         9.0.0
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2

</code></pre>

## 🌍  Your Environment

**Angular Version:**
equal Exception or Error.

</code></pre>

**Comment by pkozlowski-opensource** [comment]
@jhonyeduardo could you please provide a minimal reproduce scenario using stackblitz or ng-run? I _think_ I know what is going on here (do you happen to have, by any chance sth like `p-title="..."` on your parent component? that is, setting an input from an attribute?), but want to confirm to be sure that we are fixing the _exact_ issue you are facing.

**Comment by pkozlowski-opensource** [comment]
We haven't heard back with the reproduce scenario so I've got no choice but close this issue. What I'm _suspecting_ is happening is that ivy sets an input much earlier from a static attribute (when a directive instance is created) and this happens _before_ queries had a chance to run. I'm assuming that this is a duplicate of #34227
