### ISSUE TITLE
feat(bundles): include all bundles in npm distributions

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#3555]
Bundles should be included with npm distributions so that users can still take advantage of all the goodies that come with a package manager (explicit versioning, git-ignored bundles, easy installation).

TODO
 - [ ] Include same bundles as are included on code.angularjs.org in top-level `bundle/` folder of npm distribution
 - [ ] Also include d.t.s files in same folder

**Comment by pkozlowski-opensource** [comment]
+1, I was about to open such issue, thnx @jeffbcross  :-) Currently we push bundles to https://code.angularjs.org/ but don't have them in npm.

**Comment by ericmdantas** [comment]
+1. That'd be awesome.

**Comment by jeffbcross** [comment]
@alexeagle @rkirov do you agree with including bundles in the `bundle/` folder of the npm distribution?

**Comment by rkirov** [comment]
+1 or maybe `bundles` is more accurate here.

**Comment by jeffbcross** [comment]
I think so, too, but seems inconsistent with the output in `dist/js/bundle/`. I'd be fine with changing the `dist/js/bundle` to be `dist/js/bundles`.
