### ISSUE TITLE
Platform Server Http: Allow Proxy Configuration

### ISSUE THREAD

**Issue by martinmcwhorter** [angular/angular#35553]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/platform-server

### Description
 Http Proxy configuration for Platform Server Http

When doing Server Side Rendering through Angular Universal, Angular makes XHR requests to services. If the environment (may be highly regulated) requires that these requests are made through a HttpProxy -- these requests will fail. 

### Describe the solution you'd like
 

This is directly related to this bug filed with @angular/universal https://github.com/angular/universal/issues/887

Though the proper solution may involve changes to https://github.com/angular/angular/blob/master/packages/platform-server/src/http.ts

Ideally an injection token for HTTP_PROXY and HTTPS_PROXY should be provided in the SSR instance of the app.

It seems the underlying issue is that `xhr2` does not support proxying out of the box, so some of this functionality may need to be bolted on. 

### Describe alternatives you've considered
 The only reasonable workaround is implementing code within the app similar to https://github.com/angular/universal/issues/887

**Comment by CaerusKaru** [comment]
Maybe I'm missing something, but why can't you use an `HttpInterceptor`?

**Comment by martinmcwhorter** [comment]
The `HttpInterceptor` allows the modification of requests before they leave the application -- or the modification of responses as they are returned. 

The `HttpInterceptor` cannot change the behaviour of the underlying `xhr2` implementation to give it the ability to work with a HTTP Proxy. 

Another way to think of it -- imaging this were a problem in the client side. The client side browser would need to be configured to point to a HTTP proxy. There is nothing that can be done within an `HttpInterceptor` to make your browser use an HTTP Proxy it wasn't configured to use. 

But in this case, there it is on SSR -- so `@angular/platform-server` is your "browser" -- or more likely the `xhr2` node module used under the hood.

**Comment by CaerusKaru** [comment]
Let me put this another way: all you want to do is point your requests at a proxy URL, right? Why can't an `HttpInterceptor` do that for you? (Again I may be missing something here)

**Comment by martinmcwhorter** [comment]
Quote: `all you want to do is point your requests at a proxy`. This is URL/host rewriting. This is now how HTTP/HTTPS Proxies works. 

If I make a request to `https://angular.io` -- regardless of whether or not this is going through an HTTPS Proxy the HTTPS command would be `GET https://angular.io`. 

The difference is with a Proxy configured, the request is forwarded (without changing the request) to proxy server by the UA/client.

**Comment by alxhub** [comment]
The approach taken in the issue you linked (https://github.com/angular/universal/issues/887) is the correct approach, I feel like. Implementing the desired proxy behavior application-side, and providing your own `XhrFactory`.

I think proxying logic is too specialized to live in Angular upstream, and should probably be a community-maintained library. Besides the maintenance cost of having a complex feature that's not widely used, it looks like implementing this would add extra dependencies to `platform-server`, which we want to avoid.

Thank you for the request and description of the use case, but unfortunately I don't think this is something we can provide on the framework side. I think it would be awesome as a community project, though, and could be implemented exactly as you describe.
