### ISSUE TITLE
when Ivy is enabled bootstrapmodule does not work

### ISSUE THREAD

**Issue by rahulroykumar** [angular/angular#35567]
# 🐞 bug report

### Is this a regression?

No

### Description

Get the message when running the app in browser prod/aot mode. Below is my main-aot.ts

Uncaught NullInjectorError: StaticInjectorError(Platform: core)[CompilerFactory]: NullInjectorError: No provider for CompilerFactory!

## 🔬 Minimal Reproduction

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { enableProdMode } from '@angular/core';
import { platformBrowser } from '@angular/platform-browser';
//import { AppModuleNgFactory } from './app/app.module.ngfactory';
import { AppModule } from './app/app.module';

enableProdMode();

// tslint:disable-next-line:no-console
/*platformBrowser().bootstrapModuleFactory(AppModuleNgFactory).catch(err => {
    console.log('CANNOT LOAD AOT MODULE')
    console.dir(AppModuleNgFactory);
    console.error(err)
});*/
platformBrowser().bootstrapModule(AppModule).catch(err => {
    console.log('CANNOT LOAD AOT MODULE')
    console.dir(AppModule);
    console.error(err)
});

## 🔥 Exception or Error
<pre><code>
Get the message when running the app in browser prod/aot mode. Below is my main-aot.ts

Uncaught NullInjectorError: StaticInjectorError(Platform: core)[CompilerFactory]: NullInjectorError: No provider for CompilerFactory!

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
 "dependencies": {
    "@angular/compiler": "9.0.0",
    "@angular/compiler-cli": "9.0.0",
    "@angular/core": "9.0.0",
    "@bazel/typescript": ">=1.0.0",
    "@stratus/stratus-lint": "^1.0.0",
    "@types/jasmine": "3.3.8",
    "angular-router-loader": "~0.8.5",
    "angular2-template-loader": "~0.6.2",
    "applicationinsights": "~1.4.2",
    "async": "^2.5.0",
    "awesome-typescript-loader": "~4.0.1",
    "azure-storage": "^2.10.0",
    "chalk": "^2.4.1",
    "codelyzer": "~5.0.0",
    "copy-webpack-plugin": "~4.5.2",
    "css-loader": "^0.28.11",
    "dirsum": "^0.1.1",
    "express": "^4.16.3",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "~1.1.11",
    "fs-extra": "~6.0.1",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "istanbul-instrumenter-loader": "^3.0.1",
    "jasmine-core": "~3.4.0",
    "jasmine-reporters": "^2.3.1",
    "jasmine-spec-reporter": "~4.2.1",
    "jshint": "^2.9.4",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "karma-webpack": "^3.0.5",
    "latest-version": "^3.1.0",
    "lodash": "~4.17.4",
    "moment": "~2.22.2",
    "node-dir": "0.1.17",
    "null-loader": "^0.1.1",
    "ora": "^2.1.0",
    "prompt": "^1.0.0",
    "protractor": "^5.4.1",
    "protractor-html-reporter": "^1.3.2",
    "raw-loader": "0.5.1",
    "selfsigned": "^1.10.1",
    "style-loader": "^0.21.0",
    "tslint": "5.15.0",
    "tslint-loader": "~3.5.4",
    "tslint-microsoft-contrib": "6.0.0",
    "ts-node": "^7.0.0",
    "typescript": "3.6.4",
    "uglifyjs-webpack-plugin": "^1.1.2",
    "webpack": "3.12.0",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-dev-server": "~2.11.1",
    "webpack-merge": "~4.1.0",
    "yargs": "^11.0.0"
</code></pre>

**Comment by pkozlowski-opensource** [comment]
Could you please provide a minimal reproduce scenario (GitHub repo?). A basic scenario seems to work fine: https://ng-run.com/edit/WAdKvGd8cH3seec8Hsop

Are you, by any chance, using compiler APIs directly?

**Comment by rahulroykumar** [comment]
Hi @pkozlowski-opensource 

Yes I am using compiler APIs . It's a custom build and serve script .Below is  the snapshot:

const ngTools2 = require("@angular/compiler-cli");
exports.aotCompile = function (entryPoints, base) {
  const options = {
    basePath: base,
    genDir: base,
    skipMetadataEmit: false,
    declaration: false,
    emitDecoratorMetadata: true,
    experimentalDecorators: true,
    module: ts.ModuleKind.ES2015,
    moduleResolution: ts.ModuleResolutionKind.NodeJs,
    sourceMap: false,
    target: ts.ScriptTarget.ES2016,
    disableTypeScriptVersionCheck: true,
    enableIvy: true
  };

  const host = ngTools2.createCompilerHost({ options });

  const program = ngTools2.createProgram({
    rootNames: entryPoints,
    host,
    options
  });

  const emitResult = program.emit();

  const allDiagnostics = ts.getPreEmitDiagnostics(program.getTsProgram()).concat(emitResult.diagnostics).concat(program.getNgStructuralDiagnostics());
  if (allDiagnostics.length > 0) {
    logging.error(ngTools2.formatDiagnostics(allDiagnostics), false, false);
    logging.error('Compilation failed', true, false);
  }
};

**Comment by JoostK** [comment]
Are you running ngcc to process Angular packages and libraries to be compatible with Ivy?

`platformBrowser` does not provide `CompilerFactory` as it is targeting AOT apps, only `platformBrowserDynamic` provides the compiler infrastructure. With Ivy, I believe it should be possible to use `platformBrowser().bootstrapModule(...)` instead of `bootstrapModuleFactory` iff the module has been AOT compiled, but that requires ngcc to have processed the Angular packages as otherwise the View Engine's bootstrap mechanism is used which _does_ require `CompilerFactory`.

**Comment by pkozlowski-opensource** [comment]
I'm going to close this one for now as we don't have minimal reproduce scenario and we haven't heard back with more info.
