### ISSUE TITLE
A new FormControl instance can disable an input, but it can't enable it

### ISSUE THREAD

**Issue by sod** [angular/angular#35565]
Angular 9.0.0

As form controls can disable inputs, it seems like a bug that they can't enable them. Or is it a feature request? It works if you only work with a single FormControl instance. But if you give an disabled input a new FormControl instance, you are stuck.

Reproduction https://ng-run.com/edit/eXsAwaGca33ShZmNXh7v

Click on `create enabled FormControl` and the input stays enabled. Click at least once on `create disabled FormControl`, and the enabled control won't kick the input out of the disabled state. And it doesn't inherit the disabled state from the input either.

I guess the disabled state it taken care of in https://github.com/angular/angular/blob/master/packages/forms/src/directives/reactive_directives/form_control_directive.ts#L188-L190, just the reverse is missing.

**Comment by navarrofracisco** [comment]
Any update on this? and is it related to? https://github.com/angular/angular/issues/22556.

This seems like a huge deal, since reactive forms seem to be preached as the best approach everywhere. Yet I can not disable an input... Any other workarounds?

**Comment by geromegrignon** [comment]
If i understand the problem, the best approach would be not to create a new instance from an already instanciated FormGroup. You should use setValue or patchValue if you need to change the value of the formGroup.

**Comment by sonukapoor** [comment]
@petebacondarwin I can take a look at this one. Can you assign it to me please?

**Comment by mart2k** [comment]
Workaround until fixed: 
`<input [formControl]="control" [attr.disabled]="control.disabled? '' : null">`
