### ISSUE TITLE
ERROR when run cypress-e2e test in Angular v9 - (ivy_ngcc_bak with an ngcc back up file, which is disallowed)

### ISSUE THREAD

**Issue by fbellod1986** [angular/angular#35569]
![dwdwdqdwq](https://user-images.githubusercontent.com/13698871/74897095-c4208a00-5374-11ea-8471-984d9adcd19a.png)

**Comment by gkalpak** [comment]
We need a minimal reproduction (e.g. a project we can check out or detailed instructions on how to create on), otherwise there is not much we can do 😞

**Comment by fbellod1986** [comment]
> We need a minimal reproduction (e.g. a project we can check out or detailed instructions on how to create on), otherwise there is not much we can do 😞

I hosted my project in gitlab, here I have created a YML file called .gitlab-ci.yml where I give instructions for e2e and LINT tests to be executed when doing push on the origin branch created to merge with develop, it is here where the tests for cypress-e2e falls and throw the error I left above.

**Comment by gkalpak** [comment]
@fbellod1986, that info is not enough to reproduct, I'm afraid. Maybe you could try to run the same commands locally and see it you are getting the error too.

**Comment by fbellod1986** [comment]
> @fbellod1986, that info is not enough to reproduct, I'm afraid. Maybe you could try to run the same commands locally and see it you are getting the error too.

I use this image in docker: cypress/base:12.16.0 with last version of node and e

xecute npm list --depth=0

+-- @angular-devkit/build-angular@0.900.3
+-- @angular/animations@9.0.2
+-- @angular/cli@9.0.3
+-- UNMET PEER DEPENDENCY @angular/common@9.0.2
+-- @angular/compiler@9.0.2
+-- @angular/compiler-cli@9.0.2
+-- UNMET PEER DEPENDENCY @angular/core@9.0.2
+-- UNMET PEER DEPENDENCY @angular/forms@9.0.2
+-- @angular/language-service@9.0.2
+-- @angular/platform-browser@9.0.2
+-- @angular/platform-browser-dynamic@9.0.2
+-- @angular/router@9.0.2
+-- @cypress/webpack-preprocessor@4.1.1
+-- @fortawesome/fontawesome-pro@5.12.1
+-- @ng-bootstrap/ng-bootstrap@5.3.0
+-- @ngchile/cypress-cucumber-schematics@1.0.0-rc.5
+-- @sentry/browser@5.12.4
+-- @types/jasmine@3.3.16
+-- @types/jasminewd2@2.0.8
+-- @types/jwt-decode@2.2.1
+-- @types/node@8.9.5
+-- angular-archwizard@5.0.0
+-- bootstrap@4.4.1
+-- codelyzer@5.2.1
+-- cypress-cucumber-preprocessor@2.0.1
+-- UNMET PEER DEPENDENCY jasmine-core@3.4.0
+-- jasmine-spec-reporter@4.2.1
+-- jquery@3.4.1
+-- jwt-decode@2.2.0
+-- karma@4.1.0
+-- karma-chrome-launcher@2.2.0
+-- karma-coverage-istanbul-reporter@2.0.6
+-- karma-jasmine@2.0.1
+-- karma-jasmine-html-reporter@1.5.2
+-- moment@2.24.0
+-- ngx-bootstrap@5.3.2
+-- ngx-pagination@5.0.0
+-- popper.js@1.16.1
+-- protractor@5.4.3
+-- rxjs@6.5.4
+-- sweetalert2@9.7.2
+-- ts-loader@6.2.1
+-- ts-node@7.0.1
+-- tslib@1.10.0
+-- tslint@5.15.0
+-- typescript@3.7.5
`-- zone.js@0.10.2
npm ERR! peer dep missing: @angular/common@^8.0.0, required by @ng-bootstrap/ng-bootstrap@5.3.0
npm ERR! peer dep missing: @angular/core@^8.0.0, required by @ng-bootstrap/ng-bootstrap@5.3.0
npm ERR! peer dep missing: @angular/forms@^8.0.0, required by @ng-bootstrap/ng-bootstrap@5.3.0
npm ERR! peer dep missing: jasmine-core@>=3.5, required by karma-jasmine-html-reporter@1.5.2
npm ERR! peer dep missing: jasmine-core@>=3.5, required by karma-jasmine-html-reporter@1.5.2

And this is my package.json

{
  "name": "bodega",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "e2e:ci": "ng e2e --mode console"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.0.2",
    "@angular/common": "~9.0.2",
    "@angular/compiler": "~9.0.2",
    "@angular/core": "~9.0.2",
    "@angular/forms": "~9.0.2",
    "@angular/platform-browser": "~9.0.2",
    "@angular/platform-browser-dynamic": "~9.0.2",
    "@angular/router": "~9.0.2",
    "@ng-bootstrap/ng-bootstrap": "^5.3.0",
    "@ngchile/cypress-cucumber-schematics": "^1.0.0-rc.5",
    "@sentry/browser": "^5.12.1",
    "@types/jwt-decode": "^2.2.1",
    "angular-archwizard": "^5.0.0",
    "bootstrap": "^4.4.1",
    "jquery": "^3.4.1",
    "jwt-decode": "^2.2.0",
    "moment": "^2.24.0",
    "ngx-bootstrap": "^5.3.2",
    "ngx-pagination": "^5.0.0",
    "popper.js": "^1.16.0",
    "rxjs": "~6.5.4",
    "sweetalert2": "^9.6.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.2",
    "@angular/cli": "~9.0.2",
    "@angular/compiler-cli": "~9.0.2",
    "@angular/language-service": "~9.0.2",
    "@cypress/webpack-preprocessor": "4.1.1",
    "@fortawesome/fontawesome-pro": "^5.12.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "cypress-cucumber-preprocessor": "2.0.1",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-loader": "6.2.1",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.7.5"
  },
  "cypress-cucumber-preprocessor": {
    "step_definitions": "./e2e/step_definitions"
  }
}

Thanks!

**Comment by fbellod1986** [comment]
SOLVED, i delete the node_module, i execute 'npm cache clean --force' and 'npm install' and it works!
