### ISSUE TITLE
Angular 9 Ivy issue with ng-stripe-checkout (registerNgModuleType id of undefined)

### ISSUE THREAD

**Issue by dtomaszewski** [angular/angular#35574]
# 🐞 bug report

### Affected Package
https://github.com/westphalen/ng-stripe-checkout

### Is this a regression?
Nope

### Description
Hi, when I want to upgrade to Angular 9 with Ivy from Angular 8 without Ivy I've encountered problem with one of my dependencies. Can You help me to identify the issue as error as error message is not very descriptive?

![Screenshot 2020-02-20 at 12 05 05](https://user-images.githubusercontent.com/4403684/74928167-45116d00-53d9-11ea-9c39-af76e1d3a436.png)

I can add that when Ivy is turned off everything works fine.

## 🔬 Minimal Reproduction
use https://github.com/westphalen/ng-stripe-checkout in Angular 9 IVY project

## 🔥 Exception or Error

<pre><code>
vendor.js:77761 Uncaught TypeError: Cannot read property 'id' of undefined
    at registerNgModuleType (vendor.js:77761)
    at vendor.js:77772
    at Array.forEach (<anonymous>)
    at registerNgModuleType (vendor.js:77772)
    at new NgModuleFactory (vendor.js:77879)
    at compileNgModuleFactory__POST_R3__ (vendor.js:81404)
    at PlatformRef.push.../../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.PlatformRef.bootstrapModule (vendor.js:81627)
    at Module../src/main.ts (main.js:15370)
    at __webpack_require__ (runtime.js:85)
    at Object.0 (main.js:15385)

</code></pre>

**Comment by dtomaszewski** [comment]
It looks like author is inactive, I've created a fork which works in ng9

https://github.com/dtomaszewski/ng-stripe-checkout 
https://www.npmjs.com/package/ng9-stripe-checkout

**Comment by petebacondarwin** [comment]
It appears that this is a bug with the library not being updated to support Angular v9. The workaround is to use the fork provided by @dtomaszewski (thanks!). So I am closing this issue.
