### ISSUE TITLE
Tree shaking of unused components and modules

### ISSUE THREAD

**Issue by siddiq-rehman** [angular/angular#35572]
Hi Team,

I have added a library to Angular 9 project which is built using Angular 8. The library has many modules being exported like InputFieldModule, CarouselModule and many others. When I imported the InputFieldModule in the AppModule, I expected that vendor.js will have code only related to InputFieldModule but surprisingly the code base of all other modules and its declaration is present over there. 
Does Angular 9 really does tree shaking on the unused modules from libraries or the feature is yet to be deployed?

Thanks

**Comment by pkozlowski-opensource** [comment]
> Does Angular 9 really does tree shaking on the unused modules from libraries or the feature is yet to be deployed?

Normally it does. If you see the case where things are not tree-shaken and you think they should have been - please open an issue with a minimal reproduce scenario. Thnx!
