### ISSUE TITLE
Angular Service Worker doesn't load web app when server is down

### ISSUE THREAD

**Issue by alexwiese** [angular/angular#35571]
# 🐞 bug report

### Affected Package
"@angular/service-worker": "^8.2.14",

### Is this a regression?
No

### Description
Angular service worker is registered.
When I set Chrome to offline it works as expected (cached web app is loaded correctly).
However if I stop the web server the web app displays HTTP Error 503 instead of the cached web app.

Info from /ngsw/state:

```
NGSW Debug Info:

Driver state: EXISTING_CLIENTS_ONLY (Degraded due to failed initialization: Manifest fetch failed! (status: 503)
Error: Manifest fetch failed! (status: 503)
    at Driver.<anonymous> (https://phl-imprest.pulse.com.au/ngsw-worker.js:2395:27)
    at Generator.next (<anonymous>)
    at fulfilled (https://phl-imprest.pulse.com.au/ngsw-worker.js:1801:62))
Latest manifest hash: c0c46b0dc1d733d0238b6aac57fc8fddb0771161
Last update check: 10m34s684u
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.23
Node: 12.13.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.23
@angular-devkit/build-angular     0.803.23
@angular-devkit/build-optimizer   0.803.23
@angular-devkit/build-webpack     0.803.23
@angular-devkit/core              8.3.23
@angular-devkit/schematics        8.3.23
@angular/cdk                      8.2.3
@angular/cli                      8.3.23
@angular/pwa                      0.803.23
@ngtools/webpack                  8.3.23
@schematics/angular               8.3.23
@schematics/update                0.803.23
rxjs                              6.5.4
typescript                        3.4.5
webpack                           4.39.2
</code></pre>

**Comment by gkalpak** [comment]
Well, a 503 status code, does not mean the server is offline. Offline would return a 504 (Gateway timeout) :grin:

Typically, it is not safe for the ServiceWorker to handle all error status codes as "offline" and just serve the cached content, so it only handles 504 that way. That said, I think it is reasonable to handle 503 as "effecticely offline", so we need to add it [here][1].

##
@alexwiese, would be interested in putting a pull request together?

[1]: https://github.com/angular/angular/blob/1997b86a0/packages/service-worker/worker/src/driver.ts#L698

**Comment by alexwiese** [comment]
@gkalpak that makes sense.
In my case stopping the web server (IIS) causes it to return 503. 

PR is #35595
