### ISSUE TITLE
Ambiguent error when creating component in onDestroy phase

### ISSUE THREAD

**Issue by kirill-chirkov-at-clouty** [angular/angular#35582]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?
Yes, there was no such error prior to Ivy

### Description
Imagine a template which is rendered via *ngIf while onDestroy phase is running. Inside template there is a component. Inside component there is some root-scoped service provided. While creating that component, injector can't provide service for him since [injector has already been destroyed](https://github.com/angular/angular/blob/0cbdd54fd0227deb63bf0ca08f249b11e4eecd48/packages/core/src/di/r3_injector.ts#L170). Is this assert by design and why there is no guard against creating components/embedded views in on destroy phase? Stack trace is also ambiguent and might take a lot of time to guess what is actually happening.

## 🔬 Minimal Reproduction
Would make on demand, since this is more like a question than a bug

## 🔥 Exception or Error
<pre><code>
Error: Injector has already been destroyed.
    at R3Injector.assertNotDestroyed
    at R3Injector.get
    at NgModuleRef$1.get
    at Object.get
    at getOrCreateInjectable
    at NodeInjector.get
    at R3Injector.get
    at R3Injector.get
    at NgModuleRef$1.get
    at Object.get
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.3
Node: 12.16.0
OS: win32 x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.3
@angular/cdk                      9.0.1
@angular/cli                      9.0.3
@ngtools/webpack                  9.0.3
@nguniversal/builders             9.0.0
@nguniversal/common               9.0.0
@nguniversal/express-engine       9.0.0
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.6
</code></pre>

**Anything else relevant?**

**Comment by kmanikandanmca2008** [comment]
@kara , Hello This is the blocker issue for our application. Is there any plan to add the fix for the bug.

**Comment by AdrienGallais** [comment]
Any news about this bug ?

**Comment by rankitbishnoi** [comment]
I am alos facing this issue but only while doing server side rendering with aspnetcore.
`Error: Injector has already been destroyed.
    at R3Injector.assertNotDestroyed (main.js:1:1365814)
    at R3Injector.get (main.js:1:1364560)
    at NgModuleRef$1.get (main.js:1:1546109)
    at Module.<anonymous> (main.js:1:4231304)
    at Generator.next (<anonymous>)
    at fulfilled (main.js:1:6138523)
    at ZoneDelegate.invoke (main.js:1:4423993)
    at Zone.run (main.js:1:4416407)
    at main.js:1:4435504
    at ZoneDelegate.invokeTask (main.js:1:4424925)) ---> Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Injector has already been destroyed.`

**Comment by rankitbishnoi** [comment]
is there any workaround. I don't even know why and from where this error is coming

**Comment by ar-ask** [comment]
I am alos facing this issue but only while doing server side rendering with aspnetcore.
Angular CLI : 9.1.0
Node : 12.16.1

`fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLUKRDLFTCGD", Request id "0HLUKRDLFTCGD:00000001": An unhandled exception was thrown by the application.
Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Injector has already been destroyed.
Error: Injector has already been destroyed.
    at R3Injector.assertNotDestroyed (\ClientApp\dist\main-server.js:2:1369376)
    at R3Injector.get (\ClientApp\dist\main-server.js:2:1368364)
    at NgModuleRef$1.get (\ClientApp\dist\main-server.js:2:1515923)
    at \ClientApp\dist\main-server.js:2:2521154
    at step (\ClientApp\dist\main-server.js:2:1213394)
    at Object.next (\ClientApp\dist\main-server.js:2:1212679)
    at fulfilled (\ClientApp\dist\main-server.js:2:1212179)
    at ZoneDelegate.invoke (\ClientApp\dist\vendor.js:2:1663977)
    at Zone.run (\ClientApp\dist\vendor.js:2:1658937)
    at \ClientApp\dist\vendor.js:2:1672298`

**Comment by pkozlowski-opensource** [comment]
> Would make on demand, since this is more like a question than a bug

@kirill-chirkov-at-clouty yes, please - it would be much, much easier to understand what is going on with a reproduce scenario! More specifically, I would like to see this part illustrated:

> Imagine a template which is rendered via *ngIf while onDestroy phase is running. Inside template there is a component. Inside component there is some root-scoped service provided. While creating that component, injector can't provide service for him since injector has already been destroyed

Are you trying to create a view instance inside `ngOnDestroy`? This sounds unusual - what would be a functional use-case here?

**Comment by kirill-chirkov-at-clouty** [comment]
@pkozlowski-opensource 
Demo might take a little time and a separate project, since in reproduces only on **server side**.

The use case is next: I have a permission library, something like this https://github.com/AlexKhymenko/ngx-permissions#readme which can add and remove `roles` in runtime and render some content via structural directive depending on whether some role is set or not. Scenario sounds like this:
1. Start rendering page A on **server side**
2. Page A has common to all routes (meaning it is located outside router-outlet) container `<div id="someId" *shouldNotPermit="someRole">...</div>`. `shouldNotPermit` directive would render that element via `ViewContainerRef.createEmbeddedView` whether `someRole` is **not** set.
3. On initialization phase, we're setting role `someRole`, thus `someId` div content would not be rendered
4. Inside `ngOnDestroy` phase we're removing that role, since we want to hide that content no more
5. Server finishes rendering and starts destroy phase for all injectors, reaches destroy phase on page A, removes role and `*shouldNotPermit` attempts to render that content. Error is thrown right at this moment.

**Comment by pkozlowski-opensource** [comment]
@kirill-chirkov-at-clouty thnx for the additional information. Still, I would insist on a _minimal_ reproduce scenario since, sadly, I'm having hard time picture what you are trying to do :-(

We don't need your entire application but rather something minimal that mimics your exact scenario.

**Comment by kirill-chirkov-at-clouty** [comment]
@pkozlowski-opensource 
Here is the repro: https://github.com/kirill-chirkov-at-clouty/Embedded-view-on-destroy-repro
Repro scenario:
1. Clone repo
2. `npm ci`
3. `npm run build:ssr`
4. `npm run serve:ssr`
5. Enter localhost:4200
Error would appear in server output

**Comment by SyedUmerHasan** [comment]
> I am alos facing this issue but only while doing server side rendering with aspnetcore.
> `Error: Injector has already been destroyed. at R3Injector.assertNotDestroyed (main.js:1:1365814) at R3Injector.get (main.js:1:1364560) at NgModuleRef$1.get (main.js:1:1546109) at Module.<anonymous> (main.js:1:4231304) at Generator.next (<anonymous>) at fulfilled (main.js:1:6138523) at ZoneDelegate.invoke (main.js:1:4423993) at Zone.run (main.js:1:4416407) at main.js:1:4435504 at ZoneDelegate.invokeTask (main.js:1:4424925)) ---> Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Injector has already been destroyed.`

@rankitbishnoi did you find solution to this?

I am also working with SSR but couldn't find any solution.

**Angular version - 10.0.6
.NET CORE version  - 2.2**

PS:  I am getting above exception inside ngAspnetCoreEngine() function as it returns stringified HTML but ended by destroying App Component with ngOnDestroy
Please let me know if you have any solution to this?

**Comment by SyedUmerHasan** [comment]
I have found a solution, may be not good for all, but will work fine in all conditions.
Just disable Angular Ivy and it will work fine 
**NOTE: you need to add the below code to _tsconfig.base.json_**
<pre>
<code>
  "angularCompilerOptions": {
    "enableIvy": true
  } 
</code>
</pre>

**Comment by chakrachi** [comment]
same error here after upgrading to angular 9+.. (only during ssr)

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
