### ISSUE TITLE
"Maximum call stack size exceeded" error in alpha 34 when using ngModel with a lot of fields

### ISSUE THREAD

**Issue by akorchev** [angular/angular#3558]
Seems to work fine until alpha 32. Reproduction is available here (Google Chrome 44): http://plnkr.co/edit/J6yfZRrAQs5MVlOtVmcn

**Comment by mhevery** [comment]
Thanks for the PLNKR repro

**Comment by grehovm** [comment]
This problem is known for half year. Can you tell the approximate plans when will fix: week, month, year, never? I would fix it but I'm new in javascript.

**Comment by sir-valentin** [comment]
I have same problem
updated to last version and see that error still came
what can I do?? Please help!

**Comment by FabioAparicio** [comment]
Indeed, this is extremely frustrating and it's preventing us from getting things done, is there any idea of when a fix is going to land?

I've created a plnkr (based on [quickstart](https://angular.io/docs/ts/latest/quickstart.html#!#see-it-run)) with beta 12 http://plnkr.co/edit/7grRyAGjfJZqOIP9mmss?p=preview

The error is being thrown at https://github.com/angular/angular/blob/2.0.0-build.0898bca.js/ts/src/facade/lang.ts#L458

Turn on "Pause on caught exception" and skip the first 18 (they're mostly in es6-shim, only one of them is in angular-polyfills).

Upon closer inspection i've noticed that `declarations` is huge (length 1174928) which leads me to believe that the JIT CD cannot cope with a large amount of bindings, at least when they're all together.
The only way I could take it out of chrome without crashing the devtools was to `document.write()` it.

I've also noticed that this does not happen on every machine, on my intern's, for example, it's slow but it does not throw. We both use Xubuntu, but at this time I do not know if we're running the same version of chrome (I'm doing this from home, will confirm tomorrow), I assume his stack limit is set higher than mine. Here, at home, I tested using Chromium `48.0.2564.116 Ubuntu 15.10 (64-bit)`

`enableProdMode` doesn't prevent the error, although it significantly reduces the size of `declarations` to 924440, as such I assume the additional calls done in dev mode do not trigger this behavior.

I use webpack as a bundler and I do not have variable name mangling turned on.

If there's any more info that you think I could gather please let me know, we need a fix with the utmost urgency, it's a medical portal, there are a lot of fields.

**Comment by grehovm** [comment]
> I've also noticed that this does not happen on every machine

On my machine in different browsers error always pops up, just need to add more elements. 500 elements should be enough to reproduce the problem.

**Comment by FabioAparicio** [comment]
I'm working on a pull request, should have it ready by tomorrow, just finishing the tests

**Comment by mhevery** [comment]
This should be fixed in the latest master. Closing.
