### ISSUE TITLE
Ivy 9.0.2: Component object memory is being released before the component is destroyed

### ISSUE THREAD

**Issue by Achilles1515** [angular/angular#35587]
# 🐞 bug report

### Affected Package

 The issue is caused by 9.0.2

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9.0.1

### Description

Below ng-run demo is a fork from a previous issue. In the `AppComponent` `ngOnInit()` method, a `TabComponent` is dynamically created, then immediately destroyed.

But this time, I have commented out the line for destroying the component, so it should just be held around in "Angular memory". The behavior of such seemed to have changed between 9.0.1 and 9.0.2, I'm assuming because of #35156.

Heap dumps after running the app and searching for "tabcomponent" references:

9.0.1 --> the TabComponent is still in memory. I assume this should be the expected behavior and is also what is seen with View Engine.
![image](https://user-images.githubusercontent.com/23387905/74958625-3d50c900-53d7-11ea-9e19-902a9046e959.png)

9.0.2 --> the TabComponent is gone from memory.
![image](https://user-images.githubusercontent.com/23387905/74958825-8739af00-53d7-11ea-962a-72b2bf9ebf86.png)

## 🔬 Minimal Reproduction
[https://ng-run.com/edit/ktOJQq53zINA9hqmCkNJ](https://ng-run.com/edit/ktOJQq53zINA9hqmCkNJ)

**Comment by pkozlowski-opensource** [comment]
@Achilles1515 just to make sure that I understand the issue - are you _suspecting_ that Angular is somehow "dropping" (destroying / release memory) the instance of the `TabComponent`? If so, you are right, but this is the good thing! 

The way I understand it that the only _reference_ to the `TabComponent` instance is here:

```javascript
ngOnInit() {
    const tab = this.createTab();
  }
```

So the only place that could hold onto the `TabComponent` instance is the `tab` const - but the scope of this const is the `ngOnInit` method - so as soon as this one is executed its scope is gone, no one holds reference to any tab instance and JS VM can garbage collect it. 

If you hold into an instance (ex. in a closure as in this example: https://ng-run.com/edit/0BNSVQjiDimv1ojHXgMk?open=app%2Fapp.component.ts) you will see that the reference is retained.

I'm going to close this issue as for me everything is in order here. But feel free to comment back if you still believe that there is something fishy going on on the Angular side!

**Comment by Achilles1515** [comment]
@pkozlowski-opensource I understand what you are saying about the scope, but this is not a good thing.

1) Back to the ng-run I linked - the `TabComponent` executes a console log in the `ngOnInit()` and `ngOnDestroy()` lifecycle hooks. `ngOnInit()` **does** get executed because of the call to `componentRef.changeDetectorRef.detectChanges();`

So it looks like this:

![image](https://user-images.githubusercontent.com/23387905/74977028-ead3d480-53f7-11ea-8190-66fa1b270d66.png)

The TabComponent was initialized (see console) but is now gone from memory (see heap). And with this, `ngOnDestroy()` was never called. Now this assumption may be wrong, but I always thought it was "impossible" to have an initialized Angular component be garbage collected without first being destroyed by Angular (e.g. user code could lose reference to a component, but a reference would still exist _somewhere_ in the Angular internals until properly destroyed --> `ngOnDestroy()` being called + no more user-land references). Is this not the case?

2) Aside from the first point, something still seems fishy because this is the first Angular version to act this way. As shown in the screenshots, why does the `TabComponent` still hang around in memory in version 9.0.1?

**Comment by pkozlowski-opensource** [comment]
> Now this assumption may be wrong, but I always thought it was "impossible" to have an initialized Angular component be garbage collected without first being destroyed by Angular (e.g. user code could lose reference to a component, but a reference would still exist somewhere in the Angular internals until properly destroyed --> ngOnDestroy() being called + no more user-land references). Put another way - after a component is created, I thought ngOnDestroy() was guaranteed to be called before the JVM garbage collects this compoent instance. Is this not the case?

This was the wrong assumption :-) The `ngOnDestroy()` lifecycle hook is purely Angular thing. It only gets called when Angular decides that it is "done" with a given component / directive (ex. a template where it is used is no longer shown). This has nothing to do with VM actually garbage-collecting a component instance.

> why does the TabComponent still hang around in memory in version 9.0.1?

This was a bug in 9.0.0 / 9.0.1

**Comment by Achilles1515** [comment]
> This was the wrong assumption :-) The `ngOnDestroy()` lifecycle hook is purely Angular thing. It only gets called when Angular decides that it is "done" with a given component / directive (ex. a template where it is used is no longer shown). This has nothing to do with VM actually garbage-collecting a component instance.

Interesting. Well thanks for clearing that up, I'll need to experiment with this more.

> This was a bug in 9.0.0 / 9.0.1

In that ng-run demo, turn "Ivy AOT" **off**. The tab component stays in memory. So is this a bug then?

![image](https://user-images.githubusercontent.com/23387905/74979017-c0841600-53fb-11ea-9db2-4a9655fabb1d.png)

**Comment by pkozlowski-opensource** [comment]
> In that ng-run demo, turn "Ivy AOT" off. The tab component stays in memory. So is this a bug then?

In this case the application runs on the View Engine (previous version of the rendering engine) _and_ development mode. From the memory dump it _does_ look like the internal debug (dev mode) data structures retain a reference to a tab. But again, this is a dev mode on the previous generation of the rendering engine... I'm afraid that at this point we won't dig into this any deeper.
