### ISSUE TITLE
Angular 9 - Pipes could not be found

### ISSUE THREAD

**Issue by richardsengers** [angular/angular#35583]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler (ivy issue)
@angular/compiler@9.0.2/bundles/compiler.umd.js (2724:21)

### Is this a regression?
I have an angular 8 project with the exact same settings as an angular 9 project, but in Angular 9 it breaks

### Description

The issue appears when you add your pipes to a sharedModule and within the sharedModule you are using another module which depends of the pipes

## 🔬 Minimal Reproduction

Repro [here](https://stackblitz.com/edit/angular-carvqg)
https://stackblitz.com/edit/angular-carvqg

## 🔥 Exception or Error
<pre><code>
Template parse errors:
The pipe 'safe' could not be found ("div *ngFor="let faqItem of faqItems" [innerHTML]="[ERROR ->]faqItem.answer | safe:'html'"></div>"): ng:///FaqModule/FaqComponent.html@1:51
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.2
Node: 12.15.0
OS: win32 x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**
Some other issues already mentioned about this
#35467 #35232 and maybe this one as well #26436

**Comment by alxhub** [comment]
In your repro, `FaqModule` declares `FaqComponent` which attempts to use the `safe` pipe in its template, but does not import `SharedModule` which would provide visibility of the pipe. 

Therefore the error is expected - there is no `safe` pipe available to use in the template of `FaqComponent`. This is working as intended.

**Comment by alxhub** [comment]
I'll add: since your goal appears to be that `SharedModule` re-export `FaqModule`, you need to create a separate module purely for the pipe (`SafePipeModule`?) which is imported by `FaqModule`, and probably exported by `SharedModule` as well.
