### ISSUE TITLE
Alternative to @Directive annotation for base classes

### ISSUE THREAD

**Issue by zlepper** [angular/angular#35585]
# 🚀 feature request

### Relevant Package
`@angular/core`

### Description
 
With Angular 9 it is now required to annotate your base classes for them to work using Angular's DI system. That by itself is fine. However the recommended annotation is `@Directive()` which causes tslint to fire like crazy and complain about bad naming, even though the base class might not even be anything close to a directive, which then causes a lot of tslint:ignore in the code. 

### Describe the solution you'd like
 
I would like an alternative (No really good idea for the naming), that can do basically the same, but explicitly marking this as a base class of sorts, and thus doesn't make tslint to crazy. 

### Describe alternatives you've considered
 
I have tried making a custom annotation that just returns directive, like so:
```ts
function Foo() {
  return Directive();
}

@Foo()
// tslint:disable-next-line:directive-class-suffix
export abstract class AbstractBaseInputComponent
```

However that doesn't work.

It is possible to disable the lint warning (Either globally or locally), but that is really impractical to keep doing, and looks a lot like a code smell of sorts.

**Comment by alxhub** [comment]
> With Angular 9 it is now required to annotate your base classes for them to work using Angular's DI system. That by itself is fine. However the recommended annotation is @Directive() which causes tslint to fire like crazy and complain about bad naming, even though the base class might not even be anything close to a directive...

I think you're confused here, which could be a result of the documentation for this change being confusing. Have you read the guide here? https://angular.io/guide/migration-undecorated-classes

The only base classes which should have `@Directive` are those which both:
1) end up being inherited into real components or directives, and
2) use any features of the above, like DI, inputs, outputs, queries, host bindings, etc.

So I think
>  even though the base class might not even be anything close to a directive...
isn't actually the case.

For plain service base classes with constructors that use DI, `@Injectable()` is what you want.

If `tslint` complains about the naming of abstract directives (base classes with `@Directive()`), then `tslint`'s requirements should probably be relaxed. @mgechev is this something that codelyzer is producing?

**Comment by mgechev** [comment]
Yes, looks like it. We can consider updating the default `tslint.json` of the CLI.

**Comment by zlepper** [comment]
> The only base classes which should have `@Directive` are those which both:
> 
> 1. end up being inherited into real components or directives, and
> 2. use any features of the above, like DI, inputs, outputs, queries, host bindings, etc.

Yes, that is exactly the situation I was talking about, however my description was very bad, and I apologize for that.

**Comment by Achilles1515** [comment]
@alxhub I've never implemented functionality like this, but just want to confirm -
The link you provided states

>**I'm a library author. Should I add the @Directive() decorator to base classes?**
As support for selectorless decorators is introduced in Angular version 9, if you want to support Angular version 8 and earlier, you shouldn't add a selectorless @Directive() decorator. You can either add @Directive() with a selector or move the Angular-specific features to affected subclasses.

So wanting to do something like OP's example (as a library author), should I be doing... 

`@Directive({
  selector: 'dont-use'
})
export abstract class AbstractBaseInputComponent {}`

...with some bogus selector that is never to be used? Or is something else recommended (ignoring the _potential_ option of moving Angular-specific features to child classes)?

**Comment by pkozlowski-opensource** [comment]
> ...with some bogus selector that is never to be used?

You can (should) omit a selector in this case...

**Comment by Achilles1515** [comment]
> > ...with some bogus selector that is never to be used?
> 
> You can (should) omit a selector in this case...

Sorry, I meant as a library author wanting to support version 8 as well.

**Comment by alxhub** [comment]
@Achilles1515 yes, in that case you should use `@Directive({selector: 'not-a-real-element'})` with a selector that won't ever match.

**Comment by zlepper** [comment]
@alxhub Your above comment doesn't fix the source issue here that I originally reported, can we please re-open the issue?
