### ISSUE TITLE
style binded to DomSanitizer.bypassSecurityTrustStyle() does not work

### ISSUE THREAD

**Issue by dann95** [angular/angular#35599]
# 🐞 bug report

### Affected Package
the module that contains the class that sanitizes: @angular/platform-browser

### Is this a regression?
Yes, as i show in demonstation, it works on ng8, but don't apply styles in ng9.

### Description

Binding Safe Style instance to a DOM Element like code bellow, does not apply any style to div, but works on ng8, also don't throw any Exception.
```ts
export class AppComponent {
  style: SafeStyle;
  constructor(
    private sanitizer: DomSanitizer
  ) {
    const style = `width: 50px; height: 50px; border:1px solid purple;`;
    this.style = this.sanitizer.bypassSecurityTrustStyle(style);
  }
}

```
```html
<div>
  <div [style]="style"></div>
</div>

```

## 🔬 Minimal Reproduction
https://github.com/dann95/ng9-bypass-bypassSecurityTrustStyle

## 🌍  Your Environment

**Angular Version:**
<pre>On ng 8<code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.3.25
Node: 12.13.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.25
@angular-devkit/core         8.3.25
@angular-devkit/schematics   8.3.25
@schematics/angular          8.3.25
@schematics/update           0.803.25
rxjs                         6.4.0

on ng9

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.3
Node: 12.13.1
OS: win32 x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cli                      9.0.3
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment]
This is a duplicate of #35476 for which we've got a PR #35564. Closing as a duplicate.
