### ISSUE TITLE
Ivy - Directive + NgModel - Different 'model' injected in directive depending on "enableIvy" value

### ISSUE THREAD

**Issue by IgorWolbers** [angular/angular#35594]
# 🐞 bug report

### Affected Package
Ivy + `@angular/forms`

### Is this a regression?
Yes. It works as expected when `"enableIvy": false` is set in the `tsconfig.json` file. When ivy is enabled the behavior changes.

### Description
When using a custom directive on an `input` html element and binding `ngModel` the injected model in the directive is different once using ivy from when ivy is disabled. A side effect is that existing created directives no longer work when trying to update the model value using `this.modelInstance.update.emit`.

## 🔬 Minimal Reproduction
I wanted to create this using stackblitz but there is no angular 9 and ivy support as of yet. I will include all the source code in the issue as there is not much.

From the command: `ng new directive-binding --minimal=true --routing=false --skipGit=true --skipTests=true`

**./src/app/mydirective.directive.ts**  *new file*

	import { Directive, AfterViewInit, NgZone } from '@angular/core';
	import { NgModel } from '@angular/forms';
	import {timer, Observable} from 'rxjs';

	@Directive({
		selector: '[my-directive]',
		providers: [NgModel]
	})
	export class MyCustomDirective implements AfterViewInit {

		source: Observable<any>;
		counter: number = 0;
		constructor(private readonly model: NgModel) { }

		ngAfterViewInit(): void {
			console.log(this.model);

			this.source = timer(1000, 1000);
			this.source.subscribe(_ => {
				this.counter++;
				console.log('emitted ', this.counter);
				this.model.update.emit(this.counter.toString());
			});
		}
	}

**./src/app/app.component.ts**

	import { Component } from '@angular/core';

	@Component({
	  selector: 'app-root',
	  template: `
		<p>The ngModel instance injected into my-directive is different depending if ivy is used or not (enabled/disabled from tsconfig.json)</p>
		<input type="text" name="control name" id="control id" [(ngModel)]="boundModel" my-directive>
	  `,
	  styles: []
	})
	export class AppComponent {
	  title = 'directive-binding';
	  boundModel: string = 'A text value to display';
	}

**./src/app/app.module.ts**

	import { BrowserModule } from '@angular/platform-browser';
	import { NgModule } from '@angular/core';
	import {MyCustomDirective} from './mydirective.directive';
	import { FormsModule } from '@angular/forms';

	import { AppComponent } from './app.component';

	@NgModule({
	  declarations: [
		AppComponent,
		MyCustomDirective
	  ],
	  imports: [
		BrowserModule,
		FormsModule
	  ],
	  providers: [],
	  bootstrap: [AppComponent]
	})
	export class AppModule { }

## 🔥 Exception or Error
No exception. When running the app with ivy the text box input will not be update based on the timer. When running with ivy disabled the model does update the text box's model.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.3
Node: 10.19.0
OS: win32 x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cli                      9.0.3
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

Nothing else should be relevant.

## Note
If there is anything I can provide to help with this issue please let me know.

**Comment by Airblader** [comment]
Why does the directive have a provider for NgModel? Does it work if you remove that?

**Comment by IgorWolbers** [comment]
> Why does the directive have a provider for NgModel? Does it work if you remove that?

Huh... it does work if I remove that. Any reason why Ivy treats the directive differently when that is present?

**Comment by Airblader** [comment]
I don't know exactly what Ivy changes here causing the difference, but IMHO Ivy gets this right and I would've called the behavior in View Engine odd.

BTW if your directive requires ngModel at all times, you could change its selector to `my-directive[ngModel]`; alternatively make the injection `@Optional()` and deal with it being absent.

**Comment by IgorWolbers** [comment]
Fair enough. Thank you for the fast response and the information @Airblader.
