### ISSUE TITLE
Improve documentation on https://angular.io/api/core/DoCheck#usage-notes

### ISSUE THREAD

**Issue by dyoo** [angular/angular#35596]
### Description

The "Usage notes" documentation on DoCheck has no useful content in it other than that DoCheck is an interface with an ngDoCheck() method.  It can be greatly improved with a better example. 

Something like the following:
```
@Component({
    selector: 'my-person-display',
    template: `This is {{person.name}}.`,
    changeDetection: ChangeDetectionStrategy.OnPush,
})
class MyComponent implements DoCheck, OnChanges {
  @Input() person = {name: 'Anemone'};
  constructor(private readonly cdr: ChangeDetectorRef) {}

  ngOnChanges() {
    this.oldPersonName = this.person.name;
  }

  ngDoCheck() {
    // Implement a custom change-detector to find if this.person is mutated.
    if (this.oldPersonName !== this.person.name) {
      this.oldPersonName = this.person.name;
      this.cdr.markForCheck();
    }
  }
}
```
would help in motivating why this hook exists.

**Comment by ajitsinghkaler** [comment]
@aikidave all life cycle hooks have the same type of usage notes either we should change all of them for consistency or there are good examples in lifecycle hooks to which we can link for detailed examples 

I need your comments on this. I can take this you can assign this to me

**Comment by aikidave** [comment]
@ajitsinghkaler Thanks for taking a look at this! I don't know the problem well enough, but I'm happy to review any solutions you suggest!
