### ISSUE TITLE
Missing RouterOutlet constructor in router.d.ts

### ISSUE THREAD

**Issue by debanjanbasu** [angular/angular#3559]
The router.d.ts should have all the typescript declaration according to the latest angular router alpha 34. However, most of it is missing.

I am getting TypeScript errors while compiling, yet the code runs as I had to dive deep into the source to fix it.

**Comment by debanjanbasu** [comment]
Also missing is the activate(instruction) method any many others. On deeper inspection..

**Comment by mhevery** [comment]
Please add concrete items which are missing and what you think it should be.

**Comment by Fincodr** [comment]
router.d.ts (alpha 34) is missing at least the following:

class RouterOutlet
+ constructor

class Router
+ config(<definition>) - The definition for allowed values is too tight, It doesn't accept all different combinations of values that are normally used. Still everything works if changed to definitions: List<any>)

**Comment by mhevery** [comment]
Already fixed on master, closing.
