### ISSUE TITLE
Code example is TestBed.get but description says TestBed.inject in the HTTP guide

### ISSUE THREAD

**Issue by Ivnosing** [angular/angular#35609]
# 📚 Docs or angular.io bug report

### Description
The _[Testing HTTP requests](https://angular.io/guide/http#testing-http-requests)_ section of the HTTP guide has contradictory code and explanation.

The method `TestBed.get` is being used but the description says `TestBed.inject`.

## 🔬 Minimal Reproduction
1. Navigate to https://angular.io/guide/http
2. Within that page, go to section _Testing HTTP Requests_ -> _Setup_ (https://angular.io/guide/http#setup-1)
3. Look at the last lines of the block of code named _app/testing/http-client.spec.ts(setup)_ and the description after it

### What's the affected URL?
https://angular.io/guide/http

### Expected vs Actual Behavior
`TestBed.get` should be `TestBed.inject`.

Alternatively, explanation should say _TestBed.get()_ instead of _TestBed.inject()_, but because of what is said in https://angular.io/guide/testing#angular-testbed the first option would be prefered.

## 📷Screenshot
![image](https://user-images.githubusercontent.com/26304638/75021458-5798ae80-548c-11ea-9af1-3313fe33ab10.png)

### Anything else relevant?
Not a duplicate of #30750 because this issue is about a mismatch between the code and the description.

**Comment by gkalpak** [comment]
Thx for reporting this, @Ivnosing. I will be fixing this as part of #34374.

**Comment by gkalpak** [comment]
Actually, I realized this was independent from #34374, so I created #35777.
