### ISSUE TITLE
Angular service worker update view when cache is updated after API response

### ISSUE THREAD

**Issue by crohit313** [angular/angular#35604]
I am using Angular service worker to cache my API response.
I am using following configuration to cache the API:

```json
"dataGroups": [
  {
    "name": "services",
    "urls": [
      "apiUrl"
    ],
    "cacheConfig": {
      "maxSize": 1,
      "maxAge": "1d",
      "timeout": "0s",
      "strategy": "freshness"
    }
  }
]
```

For the first time it is caching the response on service call and on second time its showing data from the cache and making the API call in parallel. After API response it is updating the cache only.
But I want to update my view also when the cache is updated. 
For now I've to reload my page to see the updated data, Is there any way to update data on view when API calls returns a response without reloading the page.

**Comment by gkalpak** [comment]
This is not supported with the current implementation. What you have is essentially a [stale-while-revalidate][1] strategy, which says that stale content (from the cache) will be served on one request and the freshed content (fetched and cached in the background) will be served on the next request.

Generally, when the page makes an HTTP request (either using `XMLHttpRequest` or `fetch()`), it expects a single response back (and there is no built-in mechanism to get an updated response). 

You could implement something like that with a custom ServiceWorker implementation and a custom communication mechanism between the page and the ServiceWorker (not implicitly via `XMLHttpRequest` or `fetch()`), which is outside the scope of the general-purpose Angular ServiceWorker.

[1]: https://developers.google.com/web/fundamentals/instant-and-offline/offline-cookbook/#stale-while-revalidate
