### ISSUE TITLE
Anchoring Animations (ng-animate-ref) no way to transition between cloned element and new element

### ISSUE THREAD

**Issue by lee-tunnicliffe** [angular/angular#3560]
I am trying to achieve a morphing animation between views using ng-animate-ref. The animation should follow the steps below:

1) When the user clicks the element to go forwards or the back link to go backwards, Fade out the contents of the element by transitioning the opacity of the contents.

2) Morph the element into it's new size and position using ng-animate-ref.

3) Either fade out the cloned element to reveal the actual element underneath or fade in the actual element when the cloned element is removed from the dom.

It is the 3rd step that I cannot achieve. Here is a plunkr with what I have so far.

http://plnkr.co/edit/H41tfHjpmK6o5jm2XhoE?p=preview

The problem I have is that ng-anchor-out-remove happens too early (during the morph) and then there is no ng-animate-shim-remove on the real element that I could use. I can't think what else to do.

Another smaller issue that I have is that on ie11 I get a flash of the content showing just before the morphing starts after I have faded out the content.

**Comment by ericmdantas** [comment]
Hello!

Please ask this in the [angular 1.x repo](https://github.com/angular/angular) instead.
This one is meant for angular 2x.  :smile:

**Comment by pkozlowski-opensource** [comment]
Thnx @ericmdantas

**Comment by lee-tunnicliffe** [comment]
Oops, sorry :/
