### ISSUE TITLE
Could not provide some locales for web app according to Accept-Langlage HTTP header

### ISSUE THREAD

**Issue by shu-mutou** [angular/angular#35606]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
@angular/localize
@angular/cli

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Before Angular 9, we could provide `zh-cn`, `zh-tw`, `zh-sg` according HTTP accept-language header.

### Description

 A clear and concise description of the problem...
They are deprecated in favor of `zh-Hans` and `zh-Hant` in Angular 9, despite `zh-Hans` and `zh-Hant` are not implemented in browsers, e.g. Chrome and Firefox.

## 🔬 Minimal Reproduction
part of `angular.json`
<pre><code>
      "i18n": {
        "sourceLocale": {
          "code": "en",
          "baseHref": "/"
        },
        "locales": {
          "zh": {
            "translation": "i18n/zh/messages.zh.xlf",
            "baseHref": "/"
          },
          "zh-cn": {
            "translation": "i18n/zh-cn/messages.zh-cn.xlf",
            "baseHref": "/"
          },
          "zh-sg": {
            "translation": "i18n/zh-sg/messages.zh-sg.xlf",
            "baseHref": "/"
          },
          "zh-Hans": {
            "translation": "i18n/zh-Hans/messages.zh-Hans.xlf",
            "baseHref": "/"
          },
          "zh-tw": {
            "translation": "i18n/zh-tw/messages.zh-tw.xlf",
            "baseHref": "/"
          },
          "zh-Hant": {
            "translation": "i18n/zh-Hant/messages.zh-Hant.xlf",
            "baseHref": "/"
          }
        }
      },
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>9.0.2<code>

</code></pre>

**Comment by petebacondarwin** [comment]
So that I can try to help you with this. Can you explain your problem a bit more?

What do you mean by 

> provide zh-cn, zh-tw, zh-sg according HTTP accept-language header.

I think you are saying that your browser is sending these locales in the HTTP request, and that somehow you are mapping these to the locale data files on the server? And now there is not a direct mapping between these header values and the filenames of the locale data files?

Is that correct?

**Comment by shu-mutou** [comment]
Sorry for leaving this issue.
This issue was really confusing for us.
* difference in supported i18n codes between angular and browsers.
* difference in supported i18n codes between angular and server side module (golang.org/x/text/message)

As of now, latest angular and modules go better partially and we had already fixed in our project manually.

Thanks.
