### ISSUE TITLE
Node Modules is taking 1.5 GB of disk space, How can we reduce the size of node modules.

### ISSUE THREAD

**Issue by TaruniSurampally** [angular/angular#35617]
My current Application is in ANGULAR 9. My node modules is taking 1.5 GB of disk space.
How to reduce the size of node modules?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by EatonZ** [comment]
Hate to tell you, but this is perfectly normal and not the fault of Angular. Note that not all of those modules will get bundled in your compiled app. It will be substantially smaller.

**Comment by TaruniSurampally** [comment]
okay
