### ISSUE TITLE
Entry point 'xxx' contains deep imports into 'yyy'

### ISSUE THREAD

**Issue by onebalaban** [angular/angular#35615]
# 🐞 bug report

### Is this a regression?
Yes, the previous version in which this bug was not present was: 8.2.14

### Description
Multiple warnings like "Entry point 'devextreme-angular/...' contains deep imports into '/node_modules/devextreme/...'. This is probably not a problem, but may cause the compilation of entry points to be out of order." occur when building an Angular v9 project with Ivy enabled.

## 🔬 Minimal Reproduction
[https://github.com/onebalaban/dxangular9](https://github.com/onebalaban/dxangular9)
npm install
ng build

## 🌍  Your Environment
<pre><code>
Angular CLI: 9.0.3
Node: 13.9.0
OS: win32 x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      9.0.3
@ngtools/webpack                  9.0.3
@schematics/angular               8.3.20
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
There are two packages in the project. The first one is [devextreme-angular](https://github.com/DevExpress/devextreme-angular). It is created according to Angular library requirements. The second package is **devextreme**. It is not an Angular library. The thing is that warnings are related to long paths of this second package. We think these warnings are false-positive.

**Comment by portothree** [comment]
I'm currently with the same problem, did you found a workaround?

**Comment by evanjmg** [comment]
+1

**Comment by petebacondarwin** [comment]
These are only warnings. Given that the `devextreme` package is not compiled by Angular then there should be no problem.

**Comment by evanjmg** [comment]
How do we remove these warnings? So many false warnings in my opinion

**Comment by petebacondarwin** [comment]
Currently this is not possible, but I will look into a way to add a configuration to ngcc to allow you to ignore deep imports for specific entry-points.

**Comment by portothree** [comment]
Thanks @petebacondarwin.

**Comment by stevethemacguy** [comment]
Steps I took to silence the warning:
1. Update to Angular 9.0.4
2. Create a file named 'ngcc.config.js' at your top-level project folder (see https://github.com/angular/angular/pull/35683)

```
module.exports = {
  packages: {
    'angular2-text-mask': {
      ignorableDeepImportMatchers: [
        /text-mask-core\//,
      ]
    },
  },
};
```
3. Enjoy a peaceful build 😌

**Comment by kekel87** [comment]
I'm not sure I understand:

I have this message on a project with a lib and demo:
```
WARNING in Entry point 'ngx-openlayers' contains deep imports into
  '[pwd]/ngx-openlayers/node_modules/ol/View',
  '[pwd]/ngx-openlayers/node_modules/ol/Map',
  '[pwd]/ngx-openlayers/node_modules/ol/layer',
```

My project architecture is:
```
projects/
    ngx-openlayers/  <----- lib with ol in peerDependencies
      ng-package.json
/src                 <----- demo project
ngcc.config.js       <----- i put ngcc.config.js here
```

```js
// ngcc.config.js
module.exports = {
  packages: {
    'ngx-openlayers': {
      ignorableDeepImportMatchers: [
        /ol\//,
      ]
    },
  },
};
```

I put `gcc.config.js` at the root of my project and updated angular but I still have the warnings.
Also, I don't understand how it will work when the lib is distributed.

**Comment by petebacondarwin** [comment]
I dont think it works with local libraries - if I remember correctly ngcc.config.js expects packages to be below a node_modules directory.

**Comment by petebacondarwin** [comment]
But I think you could put the `ngcc.config.js` directly into the local package folder using a slightly different syntax...

```
projects/
    ngx-openlayers/  <----- lib with ol in peerDependencies
      ngcc.config.js       <----- put ngcc.config.js here
      ng-package.json
/src                 <----- demo project
```

```ts
// ngcc.config.js
module.exports = {
  ignorableDeepImportMatchers: [/ol\//]
};
```

**Comment by kekel87** [comment]
I just tried it always does the same thing.
I put a log in `ngcc.config.js` and I don't have the impression that it is used.

**Comment by petebacondarwin** [comment]
Please open a new issue with a reproduction of your scenario, and I can look into it.

**Comment by Valera1980** [comment]
> Steps to silence the warning:
> 
> 1. Update to Angular 9.0.4
> 2. Create a file named 'ngcc.config.js' at your top-level project folder (see #35683)
> 
> ```
> module.exports = {
>   packages: {
>     'angular2-text-mask': {
>       ignorableDeepImportMatchers: [
>         /text-mask-core\//,
>       ]
>     },
>   },
> };
> ```
> 
> 1. Enjoy a peaceful build relieved

Thanks. That advice is helps me

**Comment by maxisam** [comment]
To me, it kinda works. There were like 3 duplicated warnings. Now I only got 2 duplicated warning.

**Comment by roopeshreddy** [comment]
> Steps to silence the warning:
> 
> 1. Update to Angular 9.0.4
> 2. Create a file named 'ngcc.config.js' at your top-level project folder (see #35683)
> 
> ```
> module.exports = {
>   packages: {
>     'angular2-text-mask': {
>       ignorableDeepImportMatchers: [
>         /text-mask-core\//,
>       ]
>     },
>   },
> };
> ```
> 
> 1. Enjoy a peaceful build 😌

This was helpful
