### ISSUE TITLE
Guidance for Ivy when publishing library

### ISSUE THREAD

**Issue by jeroenheijmans** [angular/angular#35625]
I've [searched](https://github.com/angular/angular/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+ivy+view+engine+library) but haven't found a question duplicate of my own.

# 📚 Docs or angular.io bug report

### Description

At the ["Creating Libraries / Publishing your library"](https://angular.io/guide/creating-libraries) documentation it says:

> It is not recommended to publish Ivy libraries to NPM repositories. Before publishing a library to NPM, build it using the --prod flag which will use the older compiler and runtime known as View Engine instead of Ivy.

Does that still hold for new applications, especially if I'm happy to have my library only be supported in Angular 9+?

- If yes: I'd expect a short bit of description to make explicit it's still relevant then, even though (I believe?) Ivy is the new default in Angular 9
- If no: the docs should be updated, I suppose.

### What's the affected URL?**

https://angular.io/guide/creating-libraries#publishing-your-library

## 📷Screenshot

![image](https://user-images.githubusercontent.com/1590536/75095231-0a533480-5593-11ea-9c67-c1582075e53e.png)

**Comment by pkozlowski-opensource** [comment]
> Does that still hold for new applications, especially if I'm happy to have my library only be supported in Angular 9+?

Yes, for now libraries to be published should be built the VE pipeline.

**Comment by jeroenheijmans** [comment]
Cheers, thanks for the response already!

I'd say with Ivy becoming "the new default" for Angular 9, it wouldn't hurt to clarify in the docs that libs still need to use VE pipeline.

(But with this response I personally know enough already, so if it's too tiny to fix feel free to close the issue.)

**Comment by alan-agius4** [comment]
@aikidave feel free to ping me if you need Eng Input.

**Comment by ajitsinghkaler** [comment]
Hey, @alan-agius4 does the --prod flag still builds the libraries using VE.

**Comment by alan-agius4** [comment]
> Hey, @alan-agius4 does the --prod flag still builds the libraries using VE.

Yes, more info https://angular.io/guide/creating-libraries#publishing-your-library

**Comment by epelc** [comment]
@alan-agius4 have you thought about the situation when you have many internal libraries and want to upgrade to ivy across all projects?

A lot of our code is shared between projects since any generic feature + it's ui is all shared with minor config via libraries. AKA we have a lot of code in libraries which is stuck using VE. I couldn't find a flag to force allowing publishing of ivy libs.

**Comment by ChaitanyaBabar** [comment]
> Hey, @alan-agius4 does the --prod flag still builds the libraries using VE.
> 

Yes as per docs it states that using --prod flag would build the libraries using View Engine Compiler.

But **does not** seems to be working unless we disable Ivy in "**angularCompilerOptions**" as
`"enableIvy": false`.

@pkozlowski-opensource  @jeroenheijmans 
Can you please confirm ?

**Comment by alan-agius4** [comment]
@epelc there is no flag to allow a library to be published using Ivy, the main reason for this is that the Ivy's internal instruction set is not yet stable which might result in libraries being compatible with Ivy 9.0.0 not to be compatible with Angular 9.1.0 and vice-versa.

@ChaitanyaBabar, if you used the Angular CLI to update you should have 2 tsconfigs for each library `tsconfig.lib.json` and `tsconfig.lib.prod.json`. In the latter the `enableIvy` flag is set to `false`.

**Comment by ChaitanyaBabar** [comment]
@epelc 
Thanks for the confirmation.

Are you suggesting that `tsconfig.lib.prod.json` that gets created while doing upgrade using Angular CLI ? 
If so I am not sure why it was not created for my project although I updated using Angular CLI  (My project contains **Application** as well as **Libraries** ).

**Comment by alan-agius4** [comment]
> Are you suggesting that tsconfig.lib.prod.json that gets created while doing upgrade using Angular CLI ?

Yes, if you updated to version 8 using `ng update @angular/cli`.

**Comment by ChaitanyaBabar** [comment]
> > Are you suggesting that tsconfig.lib.prod.json that gets created while doing upgrade using Angular CLI ?
> 
> Yes, if you updated to version 9 using `ng update @angular/cli`.

Yes, did the same .

**Comment by aikidave** [comment]
> Hey, @alan-agius4 does the --prod flag still builds the libraries using VE.
> 
> @aikidave can I take this issue.

That'd be great! Thanks!
