### ISSUE TITLE
Angular 9 ngForm issue

### ISSUE THREAD

**Issue by h33raj** [angular/angular#35636]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
this issue is caused by @angular/forms

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

Yes

### Description

 A clear and concise description of the problem...
Updated my running app from 8 to 9. All forms are breaking, even though changed to ng-form seems not working

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

 error NG8003: No directive found with exportAs 'ngForm'.
error NG8003: No directive found with exportAs 'ngModel'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.3
Node: 10.14.2
OS: win32 x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.900.3
@angular-devkit/build-angular              0.900.3
@angular-devkit/build-optimizer            0.900.3
@angular-devkit/build-webpack              0.900.3
@angular-devkit/core                       9.0.3
@angular-devkit/schematics                 9.0.3
@angular/cdk                               9.0.1
@angular/cli                               9.0.3
@angular/flex-layout                       9.0.0-beta.29
@angular/http                              7.2.16
@angular/material                          9.0.1
@ngtools/webpack                           9.0.3
@nguniversal/express-engine                8.2.6
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        9.0.3
@schematics/update                         0.900.3
rxjs                                       6.5.4
typescript                                 3.6.4
webpack                                    4.41.2
</code></pre>

**Anything else relevant?**

No

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by h33raj** [comment]
@ericmartinezr Updated the comment
