### ISSUE TITLE
DatePipe format time？

### ISSUE THREAD

**Issue by wanglei8** [angular/angular#35638]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

DatePipe.transform(date,'yyyy-MM-dd HH:mm:ss'), will transform 0 to 24;
like:
date = new Date('2012-12-12 00:00:00');
result is:
'2012-12-12 24:00:00'

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by geromegrignon** [comment]
Hello, I can't reproduce your issue.
As stated in the issue template, please provide a stackblitz example.

**Comment by AndrewKushnir** [comment]
@wanglei8 I also tried to reproduce the issue, put together a [quick Stackblitz example](https://stackblitz.com/edit/angular-dafy2w?file=src%2Fapp%2Fapp.component.html) but was unable to replicate the behavior you described, so I'll close this ticket. If the problem still exists, feel free to create a new ticket (by also following issue template and providing a repro), so we can perform further investigation. Thank you.
