### ISSUE TITLE
Catch error handler looses context of service under error path test

### ISSUE THREAD

**Issue by PHuhn** [angular/angular#35633]
# 🐞 bug report

### Affected Package
@angular/common/http/testing

### Description

In running my Jasmine tests.  I added an additional debugging service to my **handleError** method and the test stopped working.  As I understand it, the problem arises because the **handleError** method does not know any local variables in the service.  That is the following are unknown inside the method:
```
  codeName: string;
  _consoleLog = function( s:string ) { 
    console.log( s );
  }
```
The following emulates my code base.  I have replaced my debugging service with an anonymous method.

## 🔬 Minimal Reproduction
Test service problem is seen in the last **handleError** method.
```
//
import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';
//
import { throwError } from 'rxjs';
import { catchError } from 'rxjs/operators';
//
@Injectable({ providedIn: 'root' })
export class TestService {
	//
	codeName: string;
	_consoleLog = function( s:string ) { 
		console.log( s );
	}
	//
	public constructor( private http: HttpClient ) {
		this.codeName = 'test-service';
	}
	//
	public createIncident( incident: string ) {
		const urlPath: string = 'http://localhost:4004/incident/';
		this._consoleLog( `${this.codeName}.createIncident: ${incident}` );
		return this.http.post<string>( urlPath, incident )
			.pipe( catchError( this.handleError ) );
	}
	// General error handler, throw a string.
	private handleError( error: any ) {
		if ( error instanceof HttpErrorResponse ) {
			this._consoleLog(
				`${this.codeName}.handleError: ${ JSON.stringify( error ) }` );
			return throwError( error.statusText || 'Service error' );
		}
		this._consoleLog(
			`${this.codeName}.handleError: ${error.toString()}` );
		return throwError( error.toString() || 'Service error' );
	}
}
```
Jasmine test of the above service:
```
import { TestBed, async } from '@angular/core/testing';
import { HttpClientModule, HttpClient, HttpErrorResponse, HttpRequest, HttpResponseBase } from '@angular/common/http';
import { HttpClientTestingModule, HttpTestingController, TestRequest } from '@angular/common/http/testing';
//
import { TestService } from './test.service';
//
describe('TestService', () => {
	let sut: TestService;
	let http: HttpClient;
	let backend: HttpTestingController;
	//
	beforeEach( () => {
		TestBed.configureTestingModule( {
			imports: [
				HttpClientModule,
				HttpClientTestingModule
			],
			providers: [ TestService ]
		} );
		// Setup injected pre service for each test
		backend = TestBed.get( HttpTestingController );
		// Setup sut
		sut = TestBed.inject(TestService);
		TestBed.compileComponents();
	});
	//
	afterEach( ( ) => {
		backend.verify();
	});
	//
	it('should be created', () => {
		console.log(
			'===================================\n' +
			'TestService should create ...' );
		expect(sut).toBeTruthy();
	});
	// createIncident( Incident: IIncident )
	//
	it( 'should create a new row...', async( ( ) => {
		//
		const mockData: string = 'Test create data';
		const url = 'http://localhost:4004/incident/';
		sut.createIncident( mockData ).subscribe(( resp: string ) => {
			expect( resp ).toEqual( mockData );
		});
		const request: TestRequest = backend.expectOne( `${url}` );
		expect( request.request.method ).toBe( 'POST' );
		request.flush( mockData );
		//
	} ) );
	//
	// handle a create error
	//
	it( 'should handle an error on create...', async(() => {
		//
		console.log( 'handle an error on create...' );
		const mockData: string = 'Test incident data';
		const errMsg = 'Invalid request parameters';
		const mockErrorResponse: HttpErrorResponse = new HttpErrorResponse({
			error: {}, status: 500, url: 'http://localhost:4004/incident/', statusText: 'Bad Request' });
		sut.createIncident( mockData ).subscribe((resp) => {
			console.log( 'handleError on create: expected error response:' );
			console.log( JSON.stringify( resp ) );
			fail( 'handleError: expected error...' );
		}, ( error ) => {
			console.log( JSON.stringify( error ) );
			expect( error ).toEqual( mockErrorResponse.statusText );
		} );
		const request: TestRequest = backend.expectOne(mockErrorResponse.url);
		expect( request.request.method ).toBe( 'POST' );
		// https://github.com/alisaduncan/tutorial-angular-httpclient/blob/master/src/app/user.service.spec.ts#L89
		request.flush(errMsg, mockErrorResponse );
		//
	}));
	//
});
```
The test **it( 'should handle an error on create...'** fails, because the method **_consoleLog** is unknown to it.  If I replace **_consoleLog** with **console.log** the test succeeds.

## 🔥 Exception or Error
<pre>
TestService should handle an error on create...
Expected TypeError: this._consoleLog is not a function to equal 'Bad Request'.
Error: Expected TypeError: this._consoleLog is not a function to equal 'Bad Request'.
    at stack (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:2176:17)
    at buildExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:2146:14)
    at Spec.expectationResultFactory (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:766:18)
    at Spec.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:444:34)
    at Expectation.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:710:21)
    at Expectation.toEqual (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:2099:12)
    at SafeSubscriber._error (http://localhost:9876/_karma_webpack_/src/app/net-incident/services/test.service.spec.ts:67:20)
    at SafeSubscriber.__tryOrUnsub (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/Subscriber.js:183:1)
    at SafeSubscriber.error (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/Subscriber.js:135:1)
    at Subscriber._error (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/Subscriber.js:75:1)
</pre>

## 🌍  Your Environment
**OS:**
Windows 10

**Angular Version:**
<pre>
    @angular/cli: ^9.0.1
    @angular/common: ^9.0.0
    @angular/core: ^9.0.0
</pre>

**Anything else relevant?**
N/A

**Comment by paresh-bhave** [comment]
@PHuhn 

Try changing 

`return this.http.post<string>( urlPath, incident )
			.pipe( catchError( this.handleError ) );`

inside create incident in TestService with

`return this.http.post<string>(urlPath, incident)
			.pipe( catchError(this.handleError.bind(this)));`

That should resolve your issue. I did reproduced your bug and tried this change. It worked for me.

**Comment by JoostK** [comment]
@paresh-bhave is correct here, passing a reference to `this.handleError` into `catchError` makes it impossible for `catchError` to call the provided function using the expected `this` reference, as `catchError` simply doesn't have access to `this`.

**Comment by PHuhn** [comment]
Thanks, I did not know **catchError** did that.  I'm glad that my test yielded this understanding.

**Comment by JoostK** [comment]
@PHuhn It's nothing special to `catchError` really, it's just how JavaScript works. There's a lot of articles about this topic, one example would be [MDN's chapter on Function context](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#Function_context).
