### ISSUE TITLE
[ng] ERROR in @ViewChild options must be an object literal

### ISSUE THREAD

**Issue by EyadIT94** [angular/angular#35634]
# 🐞 bug report

### Description

 
After I update the ionic to 5 and I update Angular to 9 I get this error, I tried many ways and it's not possible always I get this error:

C:\Users\eyad1\OneDrive\Desktop\ionic\DowarahGit>ionic serve
> ng.cmd run app:serve --host=localhost --port=8100
[ng] chunk {main} main.js, main.js.map (main) 2.03 kB [initial] [rendered]
[ng] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 154 kB [initial] [rendered]
[ng] chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
[ng] chunk {styles} styles.js, styles.js.map (styles) 99.7 kB [initial] [rendered]
[ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 340 kB [initial] [rendered]
[ng]
[ng] ERROR in @ViewChild options must be an object literal
[ng] Date: 2020-02-23T00:23:01.284Z - Hash: d61085f6764f5116dcbf - Time: 13830ms

[INFO] Development server running!

       Local: http://localhost:8100

       Use Ctrl+C to quit this process

[INFO] Browser window opened to http://localhost:8100!

## 🔥 Exception or Error
<pre><code>

[ng] ERROR in @ViewChild options must be an object literal
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.3
Node: 12.13.1
OS: win32 x64

Angular: 9.0.2
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cli                      9.0.3
@angular/fire                     5.4.2
@ngtools/webpack                  9.0.3
@schematics/angular               8.3.25
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

Google Chrome 80

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/34958

**Comment by AndrewKushnir** [comment]
@EyadIT94 please see my reply in a ticket that @ericmartinezr mentioned: https://github.com/angular/angular/issues/34958#issuecomment-590112358.
