### ISSUE TITLE
We cannot connect to angular.iodocs server

### ISSUE THREAD

**Issue by Elkaboverde** [angular/angular#35630]
# 📚 Docs or angular.io bug report

### Description

When change version from "stable (v9.0.2)" to "stable (v9.0.2)' URL changet to "https://angular.iodocs/" and
When change version from "stable (v9.0.2)" to "next" URL changet to "https://next.angular.iodocs/";

### What's the affected URL?**
 https://angular.io/docs

### Reproduction Steps**
change version from "stable (v9.0.2)" to "stable (v9.0.2)' ||
change version from "stable (v9.0.2)" to "next"

## 📷Screenshot

![angular io](https://user-images.githubusercontent.com/26579451/75099502-70f84280-55d3-11ea-95c2-230046e72c1a.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Browser info
Not browser specific. But I tested in Google Chrome v80.0.3987.116  and Firefox: Developer Edition v74.0b6.
https://angular.io/ : Version 9.0.3-local+sha.bb09cd0e41.

**Comment by sonukapoor** [comment]
I will take a look.
