### ISSUE TITLE
subscribe for value changes on ng-model

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#3565]
If I have an input:
```html
<form #todo="form">
    <input type="text" ng-control="desc" [(ng-model)]="model.desc">
</form>
```
And I would like to subscribe to any changes to the `model.desc`, how would one do it?

If I'd be using the form builder, I'd be doing the following:
```js
that.form = fb.group({
    desc: ['', Validators.required]
});
that.desc = that.form.controls.desc;

ObservableWrapper.subscribe(that.desc.valueChanges, function (value) {
    // do something here
})
```
And of course the markup would be a bit different as well:
```html
<form #todo="form" [ng-form-model]="form">
    <input type="text" ng-control="desc">
</form>
```
But using the form builder and `that.form.controls.desc` makes the TS compiler complain that the `desc` property does not exist on a control.

**Comment by mhevery** [comment]
* `ObservableWrapper` is internal API, please don't use it.
* Use `form.find()` to locate the `desc`

@vsavkin can comment more.

Closing since no changes are needed in our code.

**Comment by rolandjitsu** [comment]
@mhevery alright, I'll try that. But if `ObservableWrapper` is an internal API, then how do I subscribe for changes on `that.desc.valueChanges`?

Is is `that.desc.valueChanges.toRx().subscribe()`? Because `valueChanges` is a `EventEmitter` and `EventEmitter` has a method `.toRx()` that returns the observable on which I can subscribe.

Or do I use `registerOnChange` on the `Control` class?

**Comment by mhevery** [comment]
It is RX so follow their API.

**Comment by rolandjitsu** [comment]
@vsavkin I still haven't figured how to listen on model changes when I use the template driven forms (the example I have at the very top of the post). Do you think you could point out how to do it, I would really appreciate it?

**Comment by awerlang** [comment]
Create a directive which has an `Observable` input. Attach this directive to your form and pass `todo.form.valueChanges` to it.
