### ISSUE TITLE
Can I intercept images requests with HTTP_INTERCEPTORS ?

### ISSUE THREAD

**Issue by waseem-isaac-BBN** [angular/angular#35659]

**Comment by mlc-mlapis** [comment]
Yes.

**Comment by waseem-isaac-BBN** [comment]
@mlc-mlapis How ? :))

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by waseem-isaac-BBN** [comment]
I read the guideline u sent and Still wondering why shouldn't it be under features requests ?

**Comment by mlc-mlapis** [comment]
@waseem-isaac-BBN This is not a discussion forum here and the functionality is available so it's not even a feature request.

PS: You can upload/download any type of data via XHR request (the base of HttpClientModule), including binary data as images are, so where is the problem?

**Comment by waseem-isaac-BBN** [comment]
@mlc-mlapis I don't want download nor upload the image. the HTTP_INTERCEPTORS only intercept the xhr requests .

**Comment by mlc-mlapis** [comment]
@waseem-isaac-BBN The first thing is probably to explain what do you mean by `images requests`?

**Comment by waseem-isaac-BBN** [comment]
@mlc-mlapis 
![image](https://user-images.githubusercontent.com/45534453/75240838-ad8f8e00-57cd-11ea-9664-311b5ace941b.png)

**Comment by mlc-mlapis** [comment]
@waseem-isaac-BBN So please understand that it has no relation to Angular (or any JS) at all. This is requested by a browser itself. It is an independent request.

**Comment by waseem-isaac-BBN** [comment]
So the http interceptor can't intercept/manage these kind of requests . you probably mis-understand me first when u said 'Yes, you can' in your first comment.
Thanks @mlc-mlapis :))

**Comment by mlc-mlapis** [comment]
@waseem-isaac-BBN No, I always meant an XHR request (which always can be intercepted) because thinking about a browser request didn't have a sense from the beginning.

**Comment by mlc-mlapis** [comment]
@waseem-isaac-BBN PS: There is the core JS functionality like the following pattern, that is much simpler than the download of a binary object:
```
private instantiateRasterImage(): HTMLImageElement {
	const rasterImage: HTMLImageElement = new Image();
	rasterImage.setAttribute('crossOrigin', 'anonymous');
	// The event which invokes on the successful loading of a raster image.
	rasterImage.onload = (event: Event) => {
		...
	};
	// The event which invokes if loading of a raster image fails.
	rasterImage.onerror = (event: Event) => {
		...
	};
	return rasterImage;
}
```
