### ISSUE TITLE
Configuration 'production' is not set in the workspace when --prod and -c flags set

### ISSUE THREAD

**Issue by BillLudwig** [angular/angular#35663]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, this command did not generate errors using Angular 8

### Description

We have renamed the production build configuration to "release" in our angular.json file for internal consistency. Prior to upgrading to Angular 9 this worked without issue. Now when we run ```ng build -c=release --prod --aot``` we get the following error.

```An unhandled exception occurred: Configuration 'production' is not set in the workspace.```

While we can rename our release configuration to production we have a lot of projects and it breaks our internal naming convention. Since it was working prior to the upgrade we thought it was worth bringing up here before we refactor.

## 🔬 Minimal Reproduction

Create a new Angular project using the CLI.
Rename the production build configuration to release (or anything else).
Run ```ng build -c=release --prod --aot```
Get Error

## 🔥 Exception or Error
<pre><code>
An unhandled exception occurred: Configuration 'production' is not set in the workspace.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.2
Node: 10.15.0
OS: win32 x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.3
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**
Shouldn't be anything else.

**Comment by clydin** [comment]
@ahsteele In regards to the `--prod` option, yes.  If the goal is a _production_ build then the options within the `release` configuration would also be relevant.  The following is the set of options present in a production configuration for a new 9.0 project (AOT is enabled in the `options` section and is used for both development and production builds now):
```
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "10kb"
                }
              ]
            }
```

**Comment by WDODW** [comment]
![05E9217C-1D53-4B5B-9D79-60F7F3DDF440](https://user-images.githubusercontent.com/61070336/75617420-e2a23480-5b6f-11ea-8af9-6f32416c2dde.jpeg)

**Comment by WDODW** [comment]
مكررة مكررة من #

**Comment by WDODW** [comment]
[Jaber ](u.com/.com) Kali

**Comment by redevill** [comment]
Hey guys,

Anyone coming in for the first time creating lib, i'm sure will be reading this:
https://angular.io/guide/creating-libraries

It specifically details the need not to use Ivy and use the --prod option as below screen shot.
If you follow the instructions, you also get the "Configuration 'production' is not set..." error.
Please can someone advise me? Adjust the documentation?

![image](https://user-images.githubusercontent.com/8999255/75897517-eb0ba100-5df5-11ea-9b11-cc8c48f1f7f8.png)

**Comment by Theinfinix500** [comment]
@redevill same problem here cant build the library into production mode. Configuration 'production' is not set in the workspace.

**Comment by redevill** [comment]
@Theinfinix500 - Well, the blind leading the blind - From what I can make out (meaning, that from what I have read and observation of behavior) the using the prod flag is no longer needed. I took the output from a build without the prod flag, and copied it to my node_modules. "pretending" that I did an npm install on the new library. Then referenced it in code. From a compile standpoint, this is working. Still need to see if the library functions correctly, and if the published version behaves the same. Hopefully someone with more knowledge will chip in.

**Comment by karthikVj-pfizer** [comment]
I have 3 different environments on my side and i have been building packets using the following command.
ng build --configuration=test app
ng build --configuration=stage app
ng build --configuration=prod app

with separate output folders and separate environment.ts files. How do i set it up now?

**Comment by Springrbua** [comment]
I just had a look at the code in [angular cli `architect-command.ts`](https://github.com/angular/angular-cli/blob/master/packages/angular/cli/models/architect-command.ts).
As much as I understand, the issue comes from [this code](https://github.com/angular/angular-cli/blob/master/packages/angular/cli/models/architect-command.ts#L376):
```
configuration =
          `${configuration ? `${configuration},` : ''}${commandOptions.configuration}`;
```
If the `--prod`-flag is set, it simply concats `production` with the configurations set in `--configuration`.
However, the comment on the [previous `if`-statement](https://github.com/angular/angular-cli/blob/master/packages/angular/cli/models/architect-command.ts#L370-L371) says:

> The --prod flag will always be the first configuration, available to be **overwritten** by following configurations.

So the comment says, that a `--configuration` will overwrite the `configuration` set by `--prod`, while it actually only adds it.
So it's probably either a bug or the comment is outdated.

**Comment by redevill** [comment]
A follow up from my previous comment - I published the library, and it appears to behave just fine. Using the "default" no flag supplied build option.

**Comment by ciekawy** [comment]
in addition I've just found `--aot` option is not available for libraries (as libraries are being build in AOT mode be fault?)

https://github.com/angular/angular-cli/issues/13328

OTOH what worked for me as per https://angular.io/guide/ivy there is dedicated `tsconfig` option to disable ivy - I've put it in each of my libraries in `tsconfig.lib.conf` existing there and dedicated for building a library:
```
  "angularCompilerOptions": {
    "enableIvy": false
  }
```

**Comment by kapunahelewong** [comment]
Status: Docs team needs engineering input in order to correct/clarify documentation.

**Comment by alan-agius4** [comment]
Closing since `--prod` is in deprecation phase and it all reference were completely removed from AIO.
