### ISSUE TITLE
[IVY] Can't create component instance in a feature module constructor

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#35677]
# 🐞 bug report

### Affected Package

@angular/core, maybe @angular/compiler...

### Is this a regression?

Worked in 8 and below

### Description

A module throws when trying to create a new component instance in the constructor.

```ts
@NgModule({
  declarations: [
    FeatComponent,
  ],
  imports: [
    CommonModule
  ],
})
export class FeatModule {

  constructor(ngRef: NgModuleRef<FeatModule>) {
    // A self declared component, WONT WORK:
    try {
      ngRef.componentFactoryResolver.resolveComponentFactory(FeatComponent).create(ngRef.injector);
    } catch (err) {
      console.error(err);
    }

    // A parent declared component, WONT WORK:
     try {
      ngRef.componentFactoryResolver.resolveComponentFactory(AppComponent).create(ngRef.injector);
    } catch (err) {
      console.error(err);
    }
  }
}
```

Note that both a self declared component and a parent component will fail.

The fix in #35580 solve a portion of the issue but not all of it. (Iv'e tried to [explain it here](https://github.com/angular/angular/pull/35637#issuecomment-590115523) with no luck)

The problem starts [here](https://github.com/angular/angular/blob/master/packages/core/src/render3/ng_module_ref.ts#L55) with the root module of the app is created along with an `NgModuleRef` for it:

```ts
    this._r3Injector = createInjector(
        ngModuleType, _parent,
        [
          {provide: viewEngine_NgModuleRef, useValue: this},
          {provide: viewEngine_ComponentFactoryResolver, useValue: this.componentFactoryResolver}
        ],
        stringify(ngModuleType)) as R3Injector;
```

`ngModuleType` is the app's root module class and in this call it will go and instantiate all child modules...  (`FeatModule`).

The child module will try to create a component instance (`FeatModule.constructor`) which will
at some point require the `_r3Injector`. However, it is still not there because the original function call (`createInjector`) did not still finish (the one called from the app module root).

This definitely worked in v8.

## 🔬 Minimal Reproduction

Go to https://stackblitz.com/edit/angular-9-abstract-mv8oep?file=src%2Fapp%2Ffeat-module%2Ffeat-module.ts 

While the repro demo is using angular 9.0.0 i've verified this locally on the latest build using:

```
    "@angular/compiler": "https://github.com/angular/compiler-builds/archive/9.1.0-next.1+835618c678.tar.gz",
    "@angular/core": "https://github.com/angular/core-builds/archive/9.1.0-next.1+835618c678.tar.gz",
```

Including an ngcc rebuild.

## 🔥 Exception or Error
<pre><code>
main.ts:15 TypeError: Cannot read property 'get' of undefined
    at NgModuleRef$1.get (core.js:36009)
    at Object.get (core.js:33759)
    at ComponentFactory$1.create (core.js:33816)
    at new ChildModule (child.module.ts:16)
    at Object.ChildModule_Factory [as factory] (child.module.ts:14)
    at R3Injector.hydrate (core.js:16837)
    at R3Injector.get (core.js:16598)
    at core.js:16528
    at Set.forEach (<anonymous>)
    at new R3Injector (core.js:16524)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.3
Node: 12.9.1
OS: darwin x64

Angular: 9.1.0-next.1+62.sha-835618c
... compiler, core
Ivy Workspace: Yes

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.900.3
@angular-devkit/build-angular       0.900.3
@angular-devkit/build-optimizer     0.13.9
@angular-devkit/build-webpack       0.900.3
@angular-devkit/core                9.0.3
@angular-devkit/schematics          9.0.3
@angular/animations                 9.0.2
@angular/cdk                        9.0.1
@angular/cdk-experimental           9.0.1
@angular/cli                        9.0.3
@angular/common                     9.0.2
@angular/compiler-cli               9.0.2
@angular/forms                      9.0.2
@angular/language-service           9.0.2
@angular/material                   9.0.1
@angular/platform-browser           9.0.2
@angular/platform-browser-dynamic   9.0.2
@angular/router                     9.0.2
@ngtools/webpack                    9.0.3
@schematics/angular                 9.0.3
@schematics/update                  0.900.3
rxjs                                6.5.4
typescript                          3.7.5
webpack                             4.41.2
</code></pre>

cc: @crisbeto

**Comment by pkozlowski-opensource** [comment]
Debugged it a bit and it seems like the problem is that we are trying to use `_r3Injector` _while it is being created_ here: https://github.com/angular/angular/blob/835618c67887ed323a3ce7b1b2178397f02b62eb/packages/core/src/render3/ng_module_ref.ts#L55-L70

We should investigate it / see what we can do about it, given that it used to work in Angular 8. As the very minimum we should throw a descriptive error message if we decide _not_ to support this case.

@shlomiassaf out of curiosity - what is the functional use-case for creating a component instance in a module constructor? Sounds like pretty early in the application / module lifecycle. Not dismissing the use-case, just trying to understand it better.

**Comment by shlomiassaf** [comment]
@pkozlowski-opensource I have a grid library which is template based.

I allow users to provide a component with templates for the grid (cells, headers, etc..). They provide it in a static function (think `forRoot`) so they are not hassled with provider configuration.

I take this component and instantiate it which immediately  registers all template references in the libraries template registry.

I can always force them to include that component in a template somewhere, since that component does nothing but register templates, which has no immediate UI effect.

I agree that such operation should not be done in the constructor. `OnInit` is the perfect place for this. But there is no `OnInit` event in modules, not one that i'm aware of anyway.

If you would to add that lifecycle event to modules this will not be an issue as it is already the recommended approach to handle angular stuff, in the `OnInit` event and not in the constructor.
