### ISSUE TITLE
Querying for child that provides itself as undefined throws under Ivy

### ISSUE THREAD

**Issue by joats** [angular/angular#35673]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Beeing able to use ViewChild to view children of cdkDropListGroup

#### What is the current behavior?
After updating to angular/material 9.0.1 and angular/cdk 9.0.1, I can no longer access cdkDropListGroup via ViewChild.

#### What are the steps to reproduce?

Use ViewChild on simple cdkDropList within a cdkDropListGroup:
`@ViewChild(CdkDropListGroup) listGroup: CdkDropListGroup<CdkDropList>;`

Console shows:
`ASSERTION ERROR: materialized query result should be defined [Expected=> null != undefined <=Actual]`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "9.0.2"
"@angular/material": "^9.0.1"
"@angular/cdk": "^9.0.1"
All browsers

**Comment by pkozlowski-opensource** [comment]
@crisbeto thnx for the detailed investigation! Out of curiosity: is `[{provide: GroupDir, useValue: undefined}]` the "real thing" in Material's CDK or was it the easiest way to reproduce without CDK?

**Comment by crisbeto** [comment]
It's the real thing. Here are a couple of examples where we're doing it:

https://github.com/angular/components/blob/master/src/cdk/drag-drop/directives/drop-list.ts#L51
https://github.com/angular/components/blob/master/src/material/expansion/expansion-panel.ts#L91

**Comment by jjbenitez026** [comment]
The exact same thing happens to me
Any workaround for this?
