### ISSUE TITLE
fix(router): support aux routes within aux routes

### ISSUE THREAD

**Issue by btford** [angular/angular#3568]

**Comment by mhevery** [comment]
needs better description

**Comment by naomiblack** [comment]
There is an API for this, but test coverage is poor.

**Comment by nosachamos** [comment]
I believe this can be closed now that the [new router](https://github.com/angular/vladivostok) is on the way.

**Comment by IgorMinar** [comment]
This issue was made obsolete by router v3: https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

If you believe this is not the case, please file a new issue updating the description to router v3. thank you!
