### ISSUE TITLE
TestBed.overrideProvider ngOnDestroy not called on fake provider

### ISSUE THREAD

**Issue by FDIM** [angular/angular#35685]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core/testing?

### Is this a regression?

 Yep, works with VE but breaks with IVY

### Description

 
After enabling IVY few of out unit tests started to fail, they were making sure that service provided on component level gets destroyed when fixture is destroyed. That is ngOnDestroy gets called.

Good thing is that it works as expected at runtime, but only breaks in unit tests. So not too important.

As a workaround I'll remove the tests as they are a bit questionable (testing the framework...), but decided to create an issue as you might want to know that this change occurred.

Food for thought for you guys is that I've also tried adding the service to a test bed module (or even `providedIn:'root'`), and would kind of expect that it's ngOnDestroy gets called once fixture is destroyed, but it does not (same in VE though). Should it? 

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-jhied6?file=src%2Fapp%2Fhello.component.spec.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>

@angular-devkit/architect          0.900.3
@angular-devkit/build-angular      0.900.3
@angular-devkit/build-ng-packagr   0.900.3
@angular-devkit/build-optimizer    0.900.3
@angular-devkit/build-webpack      0.900.3
@angular-devkit/core               9.0.3
@angular-devkit/schematics         9.0.3
@angular/cdk                       9.0.0
@angular/cli                       9.0.3
@ngtools/webpack                   9.0.3
@schematics/angular                9.0.3
@schematics/update                 0.900.3
ng-packagr                         5.7.1
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2

</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment]
Closing this issue since it should be resolved by PR #28737 (which has tracking issue #28738).
