### ISSUE TITLE
relative routing to a route with empty path causes weird urls and breaks the routing eventually

### ISSUE THREAD

**Issue by saithis** [angular/angular#35687]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/router

### Is this a regression?

I dont know

### Description

relative navigation to a route with empty path causes the url to contain additional /() on the next navigation. In some constelations undefined can also appear in the url. When the user then does some more navigating, at some point the route won't recognize the url anymore and the app breaks.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-lazy-route-relative-bug
I couldn't create the stackblitz with a base path (which I have in my app), so the routing imediatelly breaks, because the routerLink will generate the url as "//(lazy)".

## 🔥 Exception or Error

I don't get an error, just wrong urls, which then cause the app to break a few navigations later or on page reload.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.0
Node: 12.9.0
OS: win32 x64
Angular: 8.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.0
@angular-devkit/build-angular      0.803.0
@angular-devkit/build-ng-packagr   0.803.0
@angular-devkit/build-optimizer    0.803.0
@angular-devkit/build-webpack      0.803.0
@angular-devkit/core               8.3.0
@angular-devkit/schematics         8.3.0
@angular/cdk                       8.1.3
@angular/cli                       8.3.0
@angular/material                  8.1.3
@angular/material-moment-adapter   8.1.3
@ngtools/webpack                   8.3.0
@schematics/angular                8.3.0
@schematics/update                 0.803.0
ng-packagr                         5.5.0
rxjs                               6.5.2
typescript                         3.5.3
webpack                            4.39.2

</code></pre>

**Anything else relevant?**

I dont think that it is browser/os specific, but I had the problem with Chrome and Firefox on Windows 10

**Comment by saithis** [comment]
I found out why stackblitz and my app throw differrent errors. My app is served with a base href and stackblitz isn't. If you inspect the link in the stackblitz reproduction after step 2, the href is "//(lazy)".

**Comment by saithis** [comment]
I found out that it hasn't anything to do with lazy loading, so I updated the issue text above. The problem seems to be a relative navigation to a route with empty path.

**Comment by martinsik** [comment]
Issue is still present in Angular 9.1.0: https://stackblitz.com/edit/angular-lazy-route-relative-bug-fjhdin?file=src%2Fapp%2Fapp.module.ts

**Comment by atscott** [comment]
also related: #13011

**Comment by atscott** [comment]
Additional repro from #30437 without lazy loading: https://stackblitz.com/edit/relative-link-eager-loading
