### ISSUE TITLE
Angular 9 @Input() compilation error when typed only with @types/...

### ISSUE THREAD

**Issue by BovineEnthusiast** [angular/angular#35694]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8

### Description

We use `geojson`'s types, but not `geojson` itself. This means we installed `@types/geojson` but not `geojson`. When I type an `@Input()` decorated property with a type from `geojson`, the compiler fails to find it because it looks only in `node_modules/geojson` and not `node_modules/@types/geojson`. This issue does not occur if I don't use `@Input()`.

## 🔬 Minimal Reproduction
The replication stackblitz provided in the issue template was for Angular 6. I used an Angular 9 one instead through codesandbox: https://codesandbox.io/embed/green-dawn-dokf5?fontsize=14&hidenavigation=1&theme=dark

## 🔥 Exception or Error
From the codesandbox: 
<pre><code>
DependencyNotFoundError
Could not find dependency: 'geojson' relative to '/src/app/broken/broken.component.ts'
</code></pre>

From my project: 
<pre><code>
ERROR in ./src/app/ad/ad-detail/ad-detail-ui/ad-detail-ui.component.ts
Module not found: Error: Can't resolve 'geojson' in '/Users/dennissubachev/projects/mono/dl/apps/web/src/app/ad/ad-detail/ad-detail-ui'
resolve 'geojson' in '/Users/dennissubachev/projects/mono/dl/apps/web/src/app/ad/ad-detail/ad-detail-ui'
  Parsed request is a module
  using description file: /Users/dennissubachev/projects/mono/dl/package.json (relative path: ./apps/web/src/app/ad/ad-detail/ad-detail-ui)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in /Users/dennissubachev/projects/mono/dl
        using description file: /Users/dennissubachev/projects/mono/dl/package.json (relative path: .)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /Users/dennissubachev/projects/mono/dl/package.json (relative path: ./geojson)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/dennissubachev/projects/mono/dl/geojson doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/dennissubachev/projects/mono/dl/geojson.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/dennissubachev/projects/mono/dl/geojson.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/dennissubachev/projects/mono/dl/geojson.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/dennissubachev/projects/mono/dl/geojson.js doesn't exist
            as directory
              /Users/dennissubachev/projects/mono/dl/geojson doesn't exist
      /Users/dennissubachev/projects/mono/dl/apps/web/src/app/ad/ad-detail/ad-detail-ui/node_modules doesn't exist or is not a directory
      /Users/dennissubachev/projects/mono/dl/apps/web/src/app/ad/ad-detail/node_modules doesn't exist or is not a directory
      /Users/dennissubachev/projects/mono/dl/apps/web/src/app/ad/node_modules doesn't exist or is not a directory
      /Users/dennissubachev/projects/mono/dl/apps/web/src/app/node_modules doesn't exist or is not a directory
      /Users/dennissubachev/projects/mono/dl/apps/web/src/node_modules doesn't exist or is not a directory
      /Users/dennissubachev/projects/mono/dl/apps/web/node_modules doesn't exist or is not a directory
      /Users/dennissubachev/projects/mono/dl/apps/node_modules doesn't exist or is not a directory
      /Users/dennissubachev/projects/mono/node_modules doesn't exist or is not a directory
      /Users/dennissubachev/projects/node_modules doesn't exist or is not a directory
      /Users/dennissubachev/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/dennissubachev/projects/mono/dl/node_modules
        using description file: /Users/dennissubachev/projects/mono/dl/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /Users/dennissubachev/projects/mono/dl/package.json (relative path: ./node_modules/geojson)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/dennissubachev/projects/mono/dl/node_modules/geojson doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/dennissubachev/projects/mono/dl/node_modules/geojson.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/dennissubachev/projects/mono/dl/node_modules/geojson.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/dennissubachev/projects/mono/dl/node_modules/geojson.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/dennissubachev/projects/mono/dl/node_modules/geojson.js doesn't exist
            as directory
              /Users/dennissubachev/projects/mono/dl/node_modules/geojson doesn't exist
[/Users/dennissubachev/projects/mono/dl/geojson]
[/Users/dennissubachev/projects/mono/dl/geojson.ts]
[/Users/dennissubachev/projects/mono/dl/geojson.tsx]
[/Users/dennissubachev/projects/mono/dl/geojson.mjs]
[/Users/dennissubachev/projects/mono/dl/geojson.js]
[/Users/dennissubachev/projects/mono/dl/apps/web/src/app/ad/ad-detail/ad-detail-ui/node_modules]
[/Users/dennissubachev/projects/mono/dl/apps/web/src/app/ad/ad-detail/node_modules]
[/Users/dennissubachev/projects/mono/dl/apps/web/src/app/ad/node_modules]
[/Users/dennissubachev/projects/mono/dl/apps/web/src/app/node_modules]
[/Users/dennissubachev/projects/mono/dl/apps/web/src/node_modules]
[/Users/dennissubachev/projects/mono/dl/apps/web/node_modules]
[/Users/dennissubachev/projects/mono/dl/apps/node_modules]
[/Users/dennissubachev/projects/mono/node_modules]
[/Users/dennissubachev/projects/node_modules]
[/Users/dennissubachev/node_modules]
[/Users/node_modules]
[/node_modules]
[/Users/dennissubachev/projects/mono/dl/node_modules/geojson]
[/Users/dennissubachev/projects/mono/dl/node_modules/geojson.ts]
[/Users/dennissubachev/projects/mono/dl/node_modules/geojson.tsx]
[/Users/dennissubachev/projects/mono/dl/node_modules/geojson.mjs]
[/Users/dennissubachev/projects/mono/dl/node_modules/geojson.js]
 @ ./src/app/ad/ad-detail/ad-detail-ui/ad-detail-ui.component.ts 8:0-34
 @ ./src/app/ad/shared/ad-form/ad-form-ui/ad-detail-preview-ui/ad-detail-preview-ui.component.ts
 @ ./src/app/ad/shared/ad-form/ad-form-ui/ad-form-ui.component.ts
 @ ./src/app/ad/shared/ad-form/ad-form-smart.component.ts
 @ ./src/app/ad/post-new-ad/post-new-ad.routes.ts
 @ ./src/app/ad/post-new-ad/post-new-ad-routing.module.ts
 @ ./src/app/app-routing.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.3
Node: 12.10.0
OS: darwin x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cdk                      9.0.1
@angular/cli                      9.0.3
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.1.0
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by alxhub** [comment]
Hi @BovineEnthusiast,

I copied the files from your repro into a new CLI application, and it builds/serves without trouble. Perhaps this is specifically a problem with how codesandbox.io builds and bundles code?

I'm going to close this issue as it's not reproducible. If you can make a reproduction Git repo using the CLI, please feel free to open a fresh one.
