### ISSUE TITLE
Incorporate Remark.js into Angular.io so we can create presentations

### ISSUE THREAD

**Issue by aikithoughts** [angular/angular#35698]
# 📚 Docs or angular.io bug report

### Description

We have received some user requests to create presentations of our content. The purpose of these presentations would be to help teams teach new members how to use Angular (as opposed to just reading the docs).

Projects like Remark.js can potentially make this very easy, and we can continue to use markdown to write the content. Can we look into how we could add support creating presentations into Angular.io?

### What's the affected URL?**
N/A

### Reproduction Steps**
N/A

### Expected vs Actual Behavior**
N/A

## 📷Screenshot
N/A

## 🔥 Exception or Error

N/A

### Browser info
N/A

### Anything else relevant?
N/A

**Comment by sonukapoor** [comment]
@aikidave / @gkalpak , Let me know what you have in mind and I can take a look at this. 👍

**Comment by gkalpak** [comment]
I guess we need to have a more thorough discussion about it in the next meeting. We'll update the issue with more details.
