### ISSUE TITLE
Edit copy for tick function

### ISSUE THREAD

**Issue by kapunahelewong** [angular/angular#35696]
# 📚 Docs or angular.io bug report

### Description

Per @aikidave's request, creating issue to help track workflow. PR is forthcoming. PR https://github.com/angular/angular/pull/33838 merged but needs docs review.

### What's the affected URL?**
Relevant PR is: https://github.com/angular/angular/pull/33838

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by aikidave** [comment]
Pick up/address PR https://github.com/angular/angular/pull/35697
