### ISSUE TITLE
angular 9 IVY with target es5 breaks the build

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular#35708]
# 🐞 bug report

Created angular  9 sample with target as "es5", it throws compilation error. But it works fine with "es2015" and "es6" targets.

I have done some research and find below related issues but still i can't find cause

https://github.com/angular/angular/issues/35255
https://github.com/angular/angular/issues/35399
https://github.com/angular/angular/issues/35269

### Affected Package

 i think due to IVY core compiler, reported issue occurs

### Is this a regression?

Yes works fine in angular 8

### Description

while serving my application it throws compilation error

## 🔬 Minimal Reproduction

1. Download below sample
[angular-dropdownlist.zip](https://github.com/angular/angular/files/4259633/angular-dropdownlist.zip)

2. give `npm i`

3. then `ng serve`, you will error message in terminal

**Note** - i have used `ng-packagr` to generate my third party angular packages.

## 🔥 Exception or Error
<pre><code>
    ~~~~~~~~~~~~~~~~~
node_modules/@syncfusion/ej2-angular-dropdowns/@syncfusion/ej2-angular-dropdowns.es5.js:187:5 - error NG6002: Appears in the NgModule.imports of DropDownListAllModule, but could not be resolved to an NgModule class

 

187 var DropDownListModule = /** @class */ (function () {
        ~~~~~~~~~~~~~~~~~~
node_modules/@syncfusion/ej2-angular-dropdowns/@syncfusion/ej2-angular-dropdowns.es5.js:187:5 - error NG6003: Appears in the NgModule.exports of DropDownListAllModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
"@angular/animations": "~9.0.2",
    "@angular/common": "~9.0.2",
    "@angular/compiler": "~9.0.2",
    "@angular/core": "~9.0.2",
    "@angular/forms": "~9.0.2",
    "@angular/platform-browser": "~9.0.2",
    "@angular/platform-browser-dynamic": "~9.0.2",
    "@angular/router": "~9.0.2", 
"@angular-devkit/build-angular": "~0.900.3",
"@angular/cli": "~9.0.3",
"@angular/compiler-cli": "~9.0.2",
"@angular/language-service": "~9.0.2",

</code></pre>

**Anything else relevant?**

When i change my target to "es2015" or "es6", it works fine

**Comment by petebacondarwin** [comment]
This could be a problem with how the `@syncfusion/ej2-angular-dropdowns` ES5 bundle is formatted. In that it might have some minimisation or other syntax that ngcc cannot process...

**Comment by kumaresan-subramani** [comment]
@petebacondarwin , I jave used ng-packagr to pack angular package and it is working fine in older angular versions properly

**Comment by kumaresan-subramani** [comment]
@petebacondarwin , I jave used ng-packagr to pack angular package and it is working fine in older angular versions properly

**Comment by petebacondarwin** [comment]
I cannot reproduce this error locally. I downloaded the zip file and built it both with ES5 and ES6 in the tsconfig.json:

**es5**
```
➜  angular-dropdownlist git:(master) ✗ yarn ng serve
yarn run v1.21.1
$ ng serve
0% compiling
Compiling @angular/core : module as esm5

Compiling @angular/common : module as esm5

Compiling @angular/platform-browser : module as esm5

Compiling @angular/platform-browser-dynamic : module as esm5

Compiling @angular/forms : module as esm5

Compiling @syncfusion/ej2-angular-dropdowns : module as esm5

Compiling @syncfusion/ej2-angular-buttons : module as esm5

chunk {main} main.js, main.js.map (main) 11.4 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 165 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 682 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 3.26 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 5.59 MB [initial] [rendered]
Date: 2020-02-27T16:22:32.897Z - Hash: 13a38607296625efc894 - Time: 27693ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.

Date: 2020-02-27T16:22:34.159Z - Hash: 13a38607296625efc894
6 unchanged chunks
Time: 798ms
: Compiled successfully.
```

**es6**
```
➜  angular-dropdownlist git:(master) ✗ yarn ng serve
yarn run v1.21.1
$ ng serve
0% compiling
Compiling @angular/core : es2015 as esm2015

Compiling @angular/common : es2015 as esm2015

Compiling @angular/platform-browser : es2015 as esm2015

Compiling @angular/platform-browser-dynamic : es2015 as esm2015

Compiling @angular/forms : es2015 as esm2015

Compiling @syncfusion/ej2-angular-dropdowns : es2015 as esm2015

Compiling @syncfusion/ej2-angular-buttons : es2015 as esm2015

chunk {main} main.js, main.js.map (main) 11.2 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 140 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 3.26 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 5.29 MB [initial] [rendered]
Date: 2020-02-27T16:23:51.838Z - Hash: 147dfcf4928186ddc9c4 - Time: 21649ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.
```

In both cases I was able to run the app in the browser with no errors...

**Comment by kumaresan-subramani** [comment]
@petebacondarwin 
Thanks for trying to help me

I am so sorry for this, while cleaning npm cache and trying it is working fine for me
Thank you so much

**Comment by petebacondarwin** [comment]
Glad your problem got fixed!
