### ISSUE TITLE
ng update adds extraneous @Injectable() ref

### ISSUE THREAD

**Issue by sarora2073** [angular/angular#35700]
# 🐞 bug report

Issue #35282 which was closed as non-reproducible appears to be an issue with running ng-update when upgrading from ng8 to ng9. As shown in my comments in that closed ticket, i have a screenshot which definitely proves ng-update added the extraneous @Injectable() reference. Suggest someone review the ng-update code to see why it would do this.

### Affected Package

Issue occurred when using the highest 8.x version of ng-update that is used to upgrade from ng8 to ng9.

### Is this a regression?

n/a as it's a migration issue (i.e. specific to going from ng8 to ng9)

### Description

Please see referenced issue for complete details.

## 🔬 Minimal Reproduction
<!--
Please create and share minimal reproduction of the issue starting with this template: 

I followed the official docs on upgrading from ng8 to ng9 using ng-update script. First I did a minor ng8 upgrade to get to the highest ng8 package level, then i ran ng-update to go to ng9.

## 🔥 Exception or Error
detailed in referenced issue.

## 🌍  Your Environment

**Angular Version:**
(see above)

**Comment by pkozlowski-opensource** [comment]
>  i have a screenshot which definitely proves ng-update added the extraneous @Injectable() reference

@sarora2073 we will definitively need more info - ideally code that failed to migrate

**Comment by sarora2073** [comment]
If there's a way to share it directly without posting in a public forum, I should be able to share the relevant part of the code.

**Comment by sarora2073** [comment]
Hi, 
I sent an email to share parts of the code that I can, however, in reviewing it, i just realized what is the likely suspect..

I had the following import

`import { NgModule, Injectable } from '@angular/core';`

However, this was code was a module, not an Injectable..i.e. that was an extraneous import. I'm guessing the ng-update package looks to see if Injectable is imported and takes action on that?

-S. Arora

**Comment by devversion** [comment]
Thanks for submitting this issue. The migration walks through `NgModule` definitions, collects referenced providers, and adds `@Injectable` to those which don't have that decorator yet.

I don't think there is a chance that the import you shared could cause the issue you're seeing. We'd still need an actual reproduction for this. Would you be able to share one?

**Comment by sarora2073** [comment]
@devversion - sure, i'll send what I can of the code to your direct email.

**Comment by JoostK** [comment]
@devversion Quick heads up, this does not include `@NgModule` (which is shown in the screenshot of #35282)

https://github.com/angular/angular/blob/74edde0a944f9f82485ca662dd22a9fefcabb1fb/packages/core/schematics/migrations/missing-injectable/transform.ts#L23

**Comment by devversion** [comment]
@JoostK That is expected since the assumption is that a `NgModule` is never used as token in providers. Maybe that's the problem here though. The steps the migration currently performs:

1. Finds all `ts.ClassDeclaration`'s which are decorated with `@NgModule`, `@Directive`, `@Component`
2. Collects providers in there (`providers`, `viewProviders` etc).
3. Checks if referenced "providers" are already decorated (based on the `NO_MIGRATE_DECORATORS` constant.
4. If not decorated with any of these, `@Injectable` is imported, and added as decorator.

@sarora2073 Thanks for sharing the module file. From within the file, everything looks correct. Do you know if somewhere in your code, the module is referenced? (ideally in a provider?). That would at least explain why the `@Injectable` decorator has been added?

**Comment by sarora2073** [comment]
In my app.module.ts it looks like I accidentally let that module sneak into an array using in providers. This kind of mistake doesn't get picked up as a compilation error, but apparently a migration issue. Problem solved i guess, unless you think we need a separate ticket to catch this as a compilation error.

**Comment by devversion** [comment]
I think we can add logic to not add incorrect decorators here (even though it's an edge-case). Whether this should fail in the compiler or not, is a good question. cc. @JoostK in case you have a view on this.
