### ISSUE TITLE
Please support CanDeactive In Dynamic Component Loader

### ISSUE THREAD

**Issue by tranthoai** [angular/angular#35714]
I use Dynamic Component Loader. For Example: 

`componentFactory = this.componentFactoryResolver.resolveComponentFactory(DefineForViewerComponent);
       
 componentRef = this.evaluationHolder.createComponent(componentFactory);
        
componentInstance = componentRef.instance as DefineForViewerComponent;`

In DefineForViewerComponent, when i modified any data. I want to stop navigate to another route when click any another link in page.

Please add canDeactivate for Dynamic Component Loader.

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
