### ISSUE TITLE
[ng9] barrel index.ts file import issue

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#35713]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 
Yes it was working fine in angular 7

### Description
We just had to import like this which was export from index.ts in components folder
```
import * as SettingsComponents from './components'; 
```
But now it is giving error also i have to import it from like this
```
import * as SettingsComponents from './components/index'; 
```

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
 ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.3
Node: 10.16.0
OS: win32 x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cdk                      8.2.3
@angular/cli                      9.0.3
@angular/material                 8.2.3
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
This should work in v9. Can you provide some more information about the error and how to reproduce it>

**Comment by indraraj26** [comment]
Hi, 

here is repo : https://github.com/indraraj26/ng9-barrel
barrel index: https://github.com/indraraj26/ng9-barrel/tree/master/src/app/places/components
components and module : https://github.com/indraraj26/ng9-barrel/tree/master/src/app/places


```
import * as components from "./components";

// This will work
// import * as components from "./components/index";

export const placeComponents = [components.TestComponent];
```

**Comment by petebacondarwin** [comment]
The problem you have is that you have two files that match the import `./components`:

* `src/app/places/components.ts`
* `src/app/places/components/index.ts`

The way that TS module resolution works, it will match the `components.ts` file before the `components/index.ts` file.  The solution is not to have two such file paths in your app. In fact, it is a common pattern to see a `components.ts` file and a `components` folder, but where the `components.ts` is the barrel entry-point (effectively duplicating what is in `index.ts`).

This is in the design of TypeScript and is not an issue with the Angular framework.

**Comment by indraraj26** [comment]
Hi @petebacondarwin , 

Now i have changed the file name but i get below error 
Step1: I changed components.ts to places.components.ts
Step2: barrel works as expected.
Problem: 
As PlaceModule is a part of app.module.ts with that i should able to use app-test selector on every declaration of app.module.ts but it seems to be broken.

Updated Repo: https://github.com/indraraj26/ng9-barrel
```
<!-- 'app-test' is not a known element:
1. If 'app-test' is an Angular component, then verify that it is part of this module.
2. If 'app-test' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.ng(0) -->
```
