### ISSUE TITLE
Interfaces members don't show up in dgeni

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#3571]
For example, see https://github.com/angular/angular/blob/2.0.0-alpha.34/modules/angular2/src/core/annotations/decorators.ts#L284-L287 should be present in the API docs for the interface.

<img width="410" alt="screen shot 2015-08-10 at 3 47 58 pm" src="https://cloud.githubusercontent.com/assets/2286589/9186176/37470750-3f77-11e5-9767-11a4762e20e9.png">

**Comment by petebacondarwin** [comment]
@naomiblack It is present: https://angular.io/docs/js/latest/api/annotations/AttributeFactory-interface.html

**Comment by petebacondarwin** [comment]
Or do you mean that the "members" of the interface are not present?

**Comment by naomiblack** [comment]
Yes, sorry -- I mean the members of the interface (what's in my screenshot) should be part of the doc
