### ISSUE TITLE
Angular 9 Production Build Fails during Optimization Phase (terser out of memory) 

### ISSUE THREAD

**Issue by PMoransais** [angular/angular#35721]
A new bare bone **Angular 9** app fails during a production build (ng build --prod).
The application compiles with ng build and ng serve.

**Copy of the cli command and response**

PS C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder> **ng build**
Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {polyfills} polyfills-es2015.js, polyfills-es2015.js.map (polyfills) 148 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 656 kB [initial] [rendered]
chunk {main} main-es2015.js, main-es2015.js.map (main) 171 kB [initial] [rendered]
chunk {main} main-es5.js, main-es5.js.map (main) 220 kB [initial] [rendered]
chunk {public-public-module} public-public-module-es2015.js, public-public-module-es2015.js.map (public-public-module) 2.59 MB [rendered]
chunk {public-public-module} public-public-module-es5.js, public-public-module-es5.js.map (public-public-module) 2.92 MB [rendered]
chunk {vendor} vendor-es2015.js, vendor-es2015.js.map (vendor) 2.74 MB [initial] [rendered]
chunk {vendor} vendor-es5.js, vendor-es5.js.map (vendor) 3.21 MB [initial] [rendered]
chunk {runtime} runtime-es2015.js, runtime-es2015.js.map (runtime) 9.02 kB [entry] [rendered]
chunk {runtime} runtime-es5.js, runtime-es5.js.map (runtime) 9.02 kB [entry] [rendered]
chunk {styles} styles-es2015.js, styles-es2015.js.map (styles) 960 kB [initial] [rendered]
chunk {styles} styles-es5.js, styles-es5.js.map (styles) 962 kB [initial] [rendered]
Date: 2020-02-22T15:29:29.990Z - Hash: 0851422fb8d5b16cbcd5 - Time: 27659ms

PS C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder> **ng build --prod**

ERROR in main-es2015.7c0f16d0d0f04d486439.js from Terser
RangeError: Maximum call stack size exceeded
at Array.push ()
at Tn.push (C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder\node_modules\terser\dist\bundle.min.js:1:76200)
at AST_Call.transform (C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder\node_modules\terser\dist\bundle.min.js:1:79125)
at C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder\node_modules\terser\dist\bundle.min.js:1:80514
at AST_Return.transform (C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder\node_modules\terser\dist\bundle.min.js:1:79182)
at C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder\node_modules\terser\dist\bundle.min.js:1:79313
at l (C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder\node_modules\terser\dist\bundle.min.js:1:931)
at e (C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder\node_modules\terser\dist\bundle.min.js:1:1251)
at Mn (C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder\node_modules\terser\dist\bundle.min.js:1:79287)
at C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder\node_modules\terser\dist\bundle.min.js:1:81469

Thanks

I created a test project to reproduce the issue at

https://ibreederdev.visualstudio.com/_git/iBreederWeb

This project has been pared down. As is, ng build compiles without errors but ng build --prod has an error where the terser runs out of memory:

ERROR in main-es2015.7c0f16d0d0f04d486439.js from Terser
RangeError: Maximum call stack size exceeded

In the project at scr/app/app.module.ts I import:
import { TitleCaseUrlSerializer } from '../common/classes/lib';
TitleCaseUrlSerializer is a custom class that is used in the providers section

providers: [
{ provide: 'BASE_URL', useFactory: getBaseUrl },
{
// used to provide case insensitive routing
provide: UrlSerializer, useClass: TitleCaseUrlSerializer
}
]

If you comment out the second provider for Url serializer, both build and **build --prod** complete without errors.

However, when adding files to that project eventually the terser out of memory error reappears with code that compiles properly

I also tried to add memory to the node process

_node --max_old_space_size=8192 'node_modules/@angular/cli/bin/ng' build --prod_

I did not work!

My node version is 12.16.1 LTS which is the latest with LTS .

my cli version is:
Angular CLI: 9.0.3
Node: 12.16.1
OS: win32 x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cli                      9.0.3
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

I hope that information helps

**Comment by tebantebanteban** [comment]
Downgrading angular-cli to 9.0.2 works fine for moment.

**Comment by PMoransais** [comment]
Thanks #tebantebanteban

The error first appeared with angular-cli 9.0.2. I then upgraded to 9.0.3 and got the same error.

As per your suggestion I tried downgrading to 9.02 again. ng build --prod threw the same error.

ERROR in main-es2015.076727988cad3ee506d0.js from Terser
RangeError: Maximum call stack size exceeded
    at Array.push (<anonymous>)
    at Tn.push (C:\iBreederWeb\iBreeder\node_modules\terser\dist\bundle.min.js:1:76200)
    at AST_ClassExpression.transform (C:\iBreederWeb\iBreeder\node_modules\terser\dist\bundle.min.js:1:79125)
    at C:\iBreederWeb\iBreeder\node_modules\terser\dist\bundle.min.js:1:81712
    at AST_Dot.transform (C:\iBreederWeb\iBreeder\node_modules\terser\dist\bundle.min.js:1:79182)
    at C:\iBreederWeb\iBreeder\node_modules\terser\dist\bundle.min.js:1:81532
    at AST_Call.transform (C:\iBreederWeb\iBreeder\node_modules\terser\dist\bundle.min.js:1:79182)
    at C:\iBreederWeb\iBreeder\node_modules\terser\dist\bundle.min.js:1:82066
    at AST_Binary.transform (C:\iBreederWeb\iBreeder\node_modules\terser\dist\bundle.min.js:1:79182)
    at C:\iBreederWeb\iBreeder\node_modules\terser\dist\bundle.min.js:1:79313

**Comment by tebantebanteban** [comment]
I've got same error But I removed node_modules folder, run npm install again and works fine!

**Comment by ericmartinezr** [comment]
Tracked here https://github.com/angular/angular-cli/issues/17106, if you have more info please share it.

**Comment by mhevery** [comment]
Closing as bug moved to https://github.com/angular/angular-cli/issues/17106
