### ISSUE TITLE
Delegating to styles with lower precedence

### ISSUE THREAD

**Issue by dkornel** [angular/angular#35728]
# 📚 Docs or angular.io bug report

### Description

 Setting a style property to undefined do not cause Angular to fall back to the next-highest precedence binding to that style.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-1gqc24

### What's the affected URL?**
 https://angular.io/guide/template-syntax#delegating-to-styles-with-lower-precedence

### Reproduction Steps**

 setting property both to null and undefined cause Angular to remove the style entirely.

### Expected vs Actual Behavior**

Based on the stackblitz example I would expect background color to be yellow.

## 📷Screenshot

![image](https://user-images.githubusercontent.com/32896140/75484953-13387180-59aa-11ea-9e95-f284dc019776.png)

**Comment by atscott** [comment]
Hi @dkornel, the stackblitz example is running v8 but the docs you linked to are for v9. I updated your example to use v9 with Ivy enabled and the background color is yellow so this is working as intended.

**Comment by dkornel** [comment]
I have checked with v9 and that is all correct. Thank you @atscott and sorry for unnecessary issue I have opened. I will check the documentation version next time.
