### ISSUE TITLE
Specify the path of ngcc config 

### ISSUE THREAD

**Issue by rahulroykumar** [angular/angular#35724]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/compiler-cli/ngcc

### Description
 Specify the path of ngcc.config.js file 

### Describe the solution you'd like
 A parameter something like  node ./node_modules/@angular/compiler-cli/ngcc/main-ngcc.js  --properties es2015 browser module main --first-only --create-ivy-entry-points --path from where ngcc.config will be read

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
Trying to figure out a way to read the one config file for many application. This same file will have to be include for each and every app if we cannot specify the path

**Comment by alxhub** [comment]
What is the use case you have for multiple config files? There should be nothing in an ngcc-config file that's application specific.

**Comment by rahulroykumar** [comment]
I have multiple applications and I had to give ngcc-config for each of the application. Below is my ngcc.config.js. I need this because of angular-tree-component

module.exports = {
    packages: {
        'angular-tree-component': {
            entryPoints: {
                '.': {
                    override: {
                        main: undefined
                    }
                }
            }
        }
      
    }
};

**Comment by petebacondarwin** [comment]
@rahulroykumar - the `ngcc.config.js` is a normal CommonJS script so you can `require()` a shared file.

**my-project/ngcc.config.js**
```
module.exports = require('path/to/shared/config');
```

We are not going to support getting the config from a configurable path. This would add unwanted complexity to the other integrations with ngcc, such as CLI.
