### ISSUE TITLE
ERROR in Maximum call stack size exceeded (IVY 9.0.3)

### ISSUE THREAD

**Issue by stevethemacguy** [angular/angular#35727]
# 🐞 bug report

### Affected Package
N/A

### Is this a regression?
Yes, the previous version in which this bug was not present was: 9.0.2

### Description

AOT Build causes a "maximum call size exceeded" error when building with IVY in 9.0.3

## 🔬 Minimal Reproduction
No minimal repo at the moment, but the only change I made was upgrading from 9.0.2 to 9.0.3

## 🔥 Exception or Error
<pre><code>
ERROR in Maximum call stack size exceeded
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.3
Node: 12.16.1
OS: darwin x64

Angular: 9.0.3
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cdk                      9.1.0
@angular/material                 9.1.0
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.6

</code></pre>

**Anything else relevant?**
The error only occurs when building with IVY enabled.

**Comment by santoshyadav198613** [comment]
It is tracked in https://github.com/angular/angular-cli/issues/17106

**Comment by stevethemacguy** [comment]
@santoshyadav198613 Thanks. I forgot to include my tsconfig file, so please let me know if that's useful. Feel free to close this.

**Comment by santoshyadav198613** [comment]
Similar issue is reported by multiple developers, so the team is already looking into it, you can close this and monitor the CLI issue mentioned for update.

**Comment by cyrilletuzi** [comment]
This issue is not fixed correctly in 9.0.4. See angular/angular-cli#17115
