### ISSUE TITLE
AsyncPipe and KeyvaluePipe don't work well together in fullTemplateTypeCheck

### ISSUE THREAD

**Issue by princemaple** [angular/angular#35743]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core@9.0.4

### Is this a regression?

 Not sure, never turned on full template type check on before v9

### Description

using `... | async | keyvalue` throws a type error

## 🔬 Minimal Reproduction

stackblitz does not seem to do full template type check or ivy, right?

## 🔥 Exception or Error
<pre><code>ERROR in src/app/recent/recent.component.html:1:36 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ [dayDiff: number]: { [repo: string]: object[]; }; } | null' is not assignable to parameter of type 'Map<unknown, unknown>'.       
      Type 'null' is not assignable to type 'Map&lt;unknown, unknown&gt;'.

1 &lt;div *ngFor="let groupByDayDiff of groups | async | keyvalue"&gt;
                                     ~~~~~~~~~~~~~~~

  src/app/recent/recent.component.ts:17:16
    17   templateUrl: './recent.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component RecentComponent.
</code></pre>

`groups` is of type `Observable<{[dayDiff: number]: {[repo: string]: object[]}}>`
It used to be `Observable<any>` and it didn't error then. I guess `any` hid the error previously.

## 🌍  Your Environment

**Angular Version:**
<pre><code>Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.4
@angular-devkit/build-optimizer   0.900.4
@angular-devkit/build-webpack     0.900.4
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.4
@angular/cdk                      9.0.1
@angular/fire                     5.4.2
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.0.1
@ngtools/webpack                  9.0.4
@schematics/angular               9.0.4
@schematics/update                0.900.4
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by princemaple** [comment]
the project is opensource at https://github.com/princemaple/githubstalker

**Comment by alxhub** [comment]
@princemaple, thank you for the issue!

The type error as reported is indeed correct. It looks like `keyvalue` pipe typings (and TypeScript limitations) are at fault here. This is the essential shape of `keyvalue`:

```typescript
class KeyValuePipe {
  transform(value: null): null;
  transform(value: Map<...>): Array<KeyValue<...>>;
  transform(...) { ... }
}
```

Looking at this, you might think it's safe to call `KeyValuePipe.transform` with a `Map<...>|null`, like the `async` pipe produces. However, TypeScript currently considers this a type error. It tries to use each overload signature in turn and checks if it can accept the argument type(s). Since none of `KeyValuePipe`s signatures can accept the _whole_ type of `Map<...>|null`, it eventually concludes this call isn't allowed, even though each part of the union is individually compatible with at least one of the signatures.

I think we need to update `KeyValuePipe`'s signature list to be a little more permissive. Many thanks!

**Comment by princemaple** [comment]
Thanks for the confirmation!

**Comment by curiouscod3** [comment]
still happening in 9.1.0 

when using Async pipe
**I had to change this option: "fullTemplateTypeCheck": false,**

**Comment by JoostK** [comment]
@curiouscod3 Could you please elaborate? E.g. provide the snippets of code and exact error messages you're seeing, including the output of `ng version`.

**Comment by curiouscod3** [comment]
@JoostK Sure!
I've just used "ng update --all --force "
everything is up-to-date. 


>   ERROR in src/app/modules/user/firebase/signin/signin.component.html:12:15 - error TS2769: No overload matches this call.
>       The last overload gave the following error.
>         Argument of type 'FireUser' is not assignable to parameter of type 'Promise<unknown>'.
>           Type 'FireUser' is missing the following properties from type 'Promise<unknown>': then, catch, [Symbol.toStringTag], finally
>     
>     12 <div *ngIf="!(signInUser | async); else alreadyLoggedIn">
>                      ~~~~~~~~~~
>     
>       src/app/modules/user/firebase/signin/signin.component.ts:12:16
>         12   templateUrl: './signin.component.html',
>                           ~~~~~~~~~~~~~~~~~~~~~~~~~
>         Error occurs in the template of component FireSignInComponent.


This error came from this: signInUser 
`html
<div *ngIf="!(signInUser | async); else alreadyLoggedIn">
`
additional code related to this issue. 

```typescript
signInUser: FireUser;

  constructor(
    private store: Store<AppRootState>,
    private fireUserSV: FirebaseUserService,
    private router: Router
  ) {

    this.store.select(selectSignInUser).pipe(
      tap((u: FireUser) => {
        console.log("FirebaseTrackService|selectSignInUser: ", u);
        if (u) {
          this.signInUser = u;
        }
      })
    );
  }

```
```
dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/cdk": "^9.2.0",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/fire": "^5.4.2",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "~9.1.0",
    "@angular/material": "^9.2.0",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0",
    "@ngrx/effects": "^9.0.0",
    "@ngrx/entity": "^9.0.0",
    "@ngrx/router-store": "^9.0.0",
    "@ngrx/schematics": "^9.0.0",
    "@ngrx/store": "^9.0.0",
    "@ngrx/store-devtools": "^9.0.0",
    "firebase": "7.13.1",
    "howler": "^2.1.3",
    "moment": "^2.24.0",
    "rxjs": "~6.5.4",
    "screenfull": "^5.0.2",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.0",
    "@angular/cli": "~9.1.0",
    "@angular/compiler-cli": "~9.1.0",
    "@angular/language-service": "~9.1.0",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.10",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.1",
    "karma-jasmine": "~3.1.1",
    "karma-jasmine-html-reporter": "^1.5.3",
    "protractor": "~5.4.0",
    "ts-node": "~8.8.1",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3",
    "@angular-devkit/architect": "0.901.0",
    "firebase-tools": "^7.16.1",
    "fuzzy": "^0.1.3",
    "inquirer": "^7.1.0",
    "inquirer-autocomplete-prompt": "^1.0.1"
  }
}
```

**Comment by JoostK** [comment]
Okay, few observations:

1. There is no usage of the `keyvalue` pipe in that code, so this issue does not appear to be related.
2. `signInUser` is of type `FireUser` but you're passing it to the `async` pipe that operates only on `Observable` or `Promise`. So the error looks correct to me.

You appear to be mixing two approaches here. Given the follow snippet:

```ts
    this.store.select(selectSignInUser).pipe(
      tap((u: FireUser) => {
        console.log("FirebaseTrackService|selectSignInUser: ", u);
        if (u) {
          this.signInUser = u;
        }
      })
    );
```

This code will do absolutely nothing, as observables won't execute until they are subscribed to. There's two approaches possible:

1. Subscribe to the `Observable` and assign `this.signInUser` from within its next callback:

```ts
    const subscription = this.store.select(selectSignInUser).pipe(
      tap((u: FireUser) => {
        console.log("FirebaseTrackService|selectSignInUser: ", u);
      })
    ).subscribe((u: FireUser) => {
      this.signInUser = u;
    });
```

(you can keep the `tap` as above, or you could move it into the subscribe callback as well and get rid of the `tap` operator).

This approach does not need the `async` pipe as you're manually dealing with the subscription, but this also means that you'd need to properly unsubscribe from the `subscription` variable I introduced above when necessary (e.g. in `ngOnDestroy`).

2. Assign the `Observable` coming from `this.store.select` to `this.signInUser` and change `signInUser` to be of type `Observable<FireUser>`:

```ts
    this.signInUser = this.store.select(selectSignInUser).pipe(
      tap((u: FireUser) => {
        console.log("FirebaseTrackService|selectSignInUser: ", u);
      })
    );
```

This now does require the usage of the async pipe.

That's a brief summary for now, I can't get into more details. Please ask around on StackOverflow or e.g. [gitter](https://gitter.im/angular/angular) if you have more questions.

**Comment by princemaple** [comment]
@JoostK my original issue is fixed, I can confirm that. @curiouscod3 apparently has a different issue.

**Comment by curiouscod3** [comment]
@JoostK haha my bad. You're right. Async works with Observable..
