### ISSUE TITLE
formatDate function sometimes doesn't take format into account

### ISSUE THREAD

**Issue by WingedSmith** [angular/angular#35745]
Hello,

When I pass format as an argument to formatDate() function, it returns an error because the first line of this function doesn't take format into account:
`let date = toDate(value);`

<pre><code>
// This works (month is correct)
new Date(formatDate('12.01.2020', 'dd.MM.yyyy', 'ru'));
> Sun Jan 12 2020 00:00:00 GMT+0300 (Москва, стандартное время)

// This throws an error (although it should've parsed as January 20)
new Date(formatDate('20.01.2020', 'dd.MM.yyyy', 'ru'));
> Error

// This returns invalid date (month more 12)
new Date(formatDate('01.20.2020', 'dd.MM.yyyy', 'ru'));
> Invalid Date
</code></pre>

**Comment by petebacondarwin** [comment]
This is working as expected: The `format` argument is not even considered at this point.

The `formatDate()` function attempts to parse the `value` argument as an ISO date format, if it is a string. When parsing as ISO date format fails it then attempts to get a date by instantiating a new `Date` object. So your code effectively ends up looking like:

```
new Date(new Date('12.01.2020'))
```

Parsing of strings in the `Date` constructor is browser dependent so depending upon your OS and browser you might get different answers. But on my local Chrome I see the following:

```
> new Date('12.01.2020')
Tue Dec 01 2020 00:00:00 GMT+0000 (Greenwich Mean Time)
> new Date('20.01.2020')
Invalid Date
```

This shows that it is the browser that is complaining about that date string.

Note that if you get the ISO order correct (yyyy MM dd) then parsing mostly works (even if you don't use the officially correct `-` ISO separator:

```
new Date('2020.01.12')
Sun Jan 12 2020 00:00:00 GMT+0000 (Greenwich Mean Time)
new Date('2020.01.20')
Mon Jan 20 2020 00:00:00 GMT+0000 (Greenwich Mean Time)
```
