### ISSUE TITLE
NG6002/NG6003: Ivy with yarn workspaces and hoisting (repro)

### ISSUE THREAD

**Issue by andreialecu** [angular/angular#35747]
# 🐞 bug report

### Affected Package
 The issue is probably caused by package @angular/compiler

### Is this a regression?

Not sure. Did not use Ivy before.

### Description

There is an error when compiling with Ivy when using yarn workspaces and the angular libraries are hoisted to the root `node_modules` in a particular way by yarn.

I have attached a repro.

## 🔬 Minimal Reproduction

Repro at: https://github.com/andreialecu/ang9-ng6002

Run 
```bash
yarn
yarn repro
```
^ Fails

Note that if you delete the `library` directory from under `packages`, the compilation will finish just fine.

```
rm -rf packages/library
yarn && yarn repro
```
^ Works

Alternatively, adding `enableIvy: false` to tsconfig.json also works.

## 🔥 Exception or Error
<pre><code>
0% compiling
Compiling @ngx-loading-bar/http-client : es2015 as esm2015

chunk {main} main.js, main.js.map (main) 2.04 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 701 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 10.5 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 341 kB [initial] [rendered]
Date: 2020-02-28T07:56:25.844Z - Hash: f57d00fadb4a1cc320dd - Time: 4147ms

ERROR in Failed to compile entry-point @ngx-loading-bar/http-client (es2015 as esm2015) due to compilation errors:
../../node_modules/@angular/common/http/http.d.ts:2801:22 - error NG6002: Appears in the NgModule.imports of LoadingBarHttpClientModule, but could not be resolved to an NgModule class.

This likely means that the library (@angular/common/http) which declares HttpClientModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

2801 export declare class HttpClientModule {
                          ~~~~~~~~~~~~~~~~
../../node_modules/@angular/common/http/http.d.ts:2801:22 - error NG6003: Appears in the NgModule.exports of LoadingBarHttpClientModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class.

This likely means that the library (@angular/common/http) which declares HttpClientModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

2801 export declare class HttpClientModule {
                          ~~~~~~~~~~~~~~~~
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.4
Node: 13.7.0
OS: linux x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.4
@angular-devkit/build-angular     0.900.4
@angular-devkit/build-optimizer   0.900.4
@angular-devkit/build-webpack     0.900.4
@angular-devkit/core              9.0.4
@angular-devkit/schematics        9.0.4
@ngtools/webpack                  9.0.4
@schematics/angular               9.0.4
@schematics/update                0.900.4
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

Probably related to path resolution, workspaces use symlink. Also related: https://github.com/angular/angular/issues/35447

**Comment by andreialecu** [comment]
As a workaround until this is fixed, adding the angular libs to `nohoist` will get around this.

`package.json` of repro with workaround:
```json
{
  "name": "ang9-ng6002",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "repro": "yarn workspace angular-app start"
  },
  "workspaces": {
    "packages": [
      "packages/*"
    ],
    "nohoist": [
      "**/@angular/*",
      "**/@angular/*/**"
    ]
  },
  "private": true
}
```

**Comment by petebacondarwin** [comment]
It seems that in "target" mode ngcc is not correctly looking up the tree to find the hoisted packages.

A workaround is to run ngcc on the root folder directly before building the projects:

* `yarn ngcc -t @ngx-loading-bar/http-client -l debug --create-ivy-entry-points`
* `yarn workspace angular-app start`

**Comment by andreialecu** [comment]
@petebacondarwin in my actual project the workaround doesn't work and shows the same error:

```
Debug: [Worker #3] Processing task: {entryPoint: @ngx-loading-bar/http-client, formatProperty: main, processDts: false}
Compiling @ngx-loading-bar/http-client : fesm5 as esm5
Debug: Stopping 7 workers...
Error: Error on worker #5: Error: Failed to compile entry-point @ngx-loading-bar/http-client (fesm5 as esm5) due to compilation errors:
node_modules/@angular/common/http/http.d.ts:2801:22 - error NG6002: Appears in the NgModule.imports of LoadingBarHttpClientModule, but could not be resolved to an NgModule class.

This likely means that the library (@angular/common/http) which declares HttpClientModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

2801 export declare class HttpClientModule {
                          ~~~~~~~~~~~~~~~~
node_modules/@angular/common/http/http.d.ts:2801:22 - error NG6003: Appears in the NgModule.exports of LoadingBarHttpClientModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class.

This likely means that the library (@angular/common/http) which declares HttpClientModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

2801 export declare class HttpClientModule {
                          ~~~~~~~~~~~~~~~~

    at ClusterWorker.compile (/home/aandrei/projects/project-monorepo/packages/project-admin/node_modules/@angular/compiler-cli/ngcc/src/main.js:177:27)
    at Worker.<anonymous> (/home/aandrei/projects/project-monorepo/packages/project-admin/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:44:42)
    at Worker.emit (events.js:321:20)
    at process.<anonymous> (internal/cluster/worker.js:32:12)
    at process.emit (events.js:321:20)
    at emit (internal/child_process.js:881:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
    at ClusterMaster.onWorkerMessage (/home/aandrei/projects/project-monorepo/packages/project-admin/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:158:27)
    at /home/aandrei/projects/project-monorepo/packages/project-admin/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:46:95
    at ClusterMaster.<anonymous> (/home/aandrei/projects/project-monorepo/packages/project-admin/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:238:57)
    at step (/home/aandrei/projects/project-monorepo/packages/project-admin/node_modules/tslib/tslib.js:139:27)
    at Object.next (/home/aandrei/projects/project-monorepo/packages/project-admin/node_modules/tslib/tslib.js:120:57)
    at /home/aandrei/projects/project-monorepo/packages/project-admin/node_modules/tslib/tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/aandrei/projects/project-monorepo/packages/project-admin/node_modules/tslib/tslib.js:109:16)
    at EventEmitter.<anonymous> (/home/aandrei/projects/project-monorepo/packages/project-admin/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:232:32)
    at EventEmitter.emit (events.js:321:20)
```

It's probably because yarn put ngcc within the inner project folder's `node_modules`: `home/aandrei/projects/project-monorepo/packages/project-admin/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:44:42` instead of the root.

**Comment by andreialecu** [comment]
As an update, adding:

```
      "**/@angular/compiler-cli/*",
      "**/@angular/compiler-cli/**"
``` 

To `workspaces/nohoist` in `package.json` the above error went away when using the workaround recommended by @petebacondarwin in the full project.

**However:**

Now getting this:

```
ERROR in Failed to compile entry-point @angular/flex-layout (es2015 as esm2015) due to compilation errors:
../../node_modules/@angular/flex-layout/flex/typings/module.d.ts:6:22 - error NG6002: Appears in the NgModule.imports of FlexLayoutModule, but could not be resolved to an NgModule class.

This likely means that the library (@angular/flex-layout/flex) which declares FlexModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```

I've tried `yarn ngcc -t @angular/flex-layout -l debug --create-ivy-entry-points` and `yarn ngcc -t @angular/flex-layout/core -l debug --create-ivy-entry-points` but couldn't get past this error.

`@angular/flex-layout` is the latest at `9.0.0-beta.29` if it matters.

**Comment by petebacondarwin** [comment]
We have `flex-layout` in our ngcc-validation repository: https://github.com/angular/ngcc-validation/tree/master/projects/angularflex-layout-ngcc
In the repo it is at beta.28 and building with ES5 as a target.
But I just checked this out and I was able to build it successfully with both ES5 and ES2015 for both beta.28 and beta.29.

So I think the problem must be related to the workspace hoisting rather than flex-layout itself.

**Comment by andreialecu** [comment]
Yes. I think it's definitely related to hoisting and/or symlinks but I mentioned it because the workaround doesn't work and I wasn't able to find a valid one. Had to disable Ivy.

Issue was tagged as workaround2 but I'm not sure if the workaround applies in all cases.

**Comment by edocbuhtig** [comment]
I am trying to import 
```import { HttpClientModule } from '@angular/common/http';```
and there is a bug ```ERROR in node_modules/@angular/common/http/http.d.ts:2801:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
[ng]     
[ng]     This likely means that the library (@angular/common/http) which declares HttpClientModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
[ng]     
[ng]     2801 export declare class HttpClientModule {```

My Ionic App Package.json
```
"dependencies": {
    "@angular/common": "~9.0.5",
    "@angular/core": "~9.0.5",
    "@angular/forms": "~9.0.5",
    "@angular/platform-browser": "~9.0.5",
    "@angular/platform-browser-dynamic": "~9.0.5",
    "@angular/router": "~9.0.5",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.4",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.1",
    "tslib": "^1.10.0",
    "woocommerce-api": "^1.5.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.5",
    "@angular/cli": "~9.0.5",
    "@angular/compiler": "~9.0.5",
    "@angular/compiler-cli": "~9.0.5",
    "@angular/language-service": "~9.0.5",
    "@ionic/angular-toolkit": "^2.1.1",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.7.5"
  }
```

**Comment by pc-perrycima** [comment]
Im having the same issue with ionic angular 9

**Comment by chriswep** [comment]
if anyone needs a temporary workaround, adding this to the root `package.json` works for me:

```
        "nohoist": [
            "**/@angular/*",
            "**/@angular/*/**",
            "**/@ngrx/*",
            "**/@ngrx/*/**",
            "**/@ionic/*",
            "**/@ionic/*/**",
            "**/@ionic-native/*",
            "**/@ionic-native/*/**",
            "**/@angular-builders/*",
            "**/@angular-builders/*/**",
            "**/@angular-devkit/*",
            "**/@angular-devkit/*/**"
        ]
```

**Comment by pYassine** [comment]
Hello ! 
Same issue for me with Yarn and Workspaces.
`  "dependencies": {
    "@angular/animations": "^9.0.5",
    "@angular/common": "^9.0.5",
    "@angular/compiler": "^9.0.5",
    "@angular/core": "^9.0.5",
    "@angular/forms": "^9.0.5",
    "@angular/localize": "^9.0.5",
    "@angular/platform-browser": "^9.0.5",
    "@angular/platform-browser-dynamic": "^9.0.5",
    "@angular/router": "^9.0.5",
    "@fortawesome/angular-fontawesome": "0.6",
    "@fortawesome/fontawesome-svg-core": "^1.2.27",
    "@fortawesome/free-regular-svg-icons": "^5.12.1",
    "@fortawesome/free-solid-svg-icons": "^5.12.1",
    "@ng-bootstrap/ng-bootstrap": "^6.0.0",
    "@schematics/angular": "^9.0.5",
    "@types/jwt-decode": "^2.2.1",
    "add": "^2.0.6",
    "core-js": "^3.6.4",
    "fs": "^0.0.1-security",
    "jwt-decode": "^2.2.0",
    "ngx-matomo": "^0.1.4",
    "ngx-toastr": "^12.0.0",
    "path": "^0.12.7",
    "rxjs": "^6.5.4",
    "tslib": "^1.11.1",
    "xlsx": "^0.15.5",
    "zone.js": "~0.10.2"
  },


  "devDependencies": {
    "@angular-devkit/build-angular": "^0.900.5",
    "@angular/cli": "^9.0.5",
    "@angular/compiler-cli": "^9.0.5",
    "@angular/language-service": "^9.0.5",
    "@schematics/update": "^0.900.5",
    "@socialgouv/tslint-config-recommended": "^0.17.0",
    "@types/jest": "^25.1.4",
    "@types/node": "^8.9.5",
    "codelyzer": "^5.2.1",
    "eslint-plugin-import": "^2.20.1",
    "jest": "^25.1.0",
    "jest-preset-angular": "^7.1.1",
    "prettier": "^1.19.1",
    "ts-jest": "^25.2.1",
    "ts-node": "~8.6.2",
    "tslint": "^5.20.1",
    "typescript": "3.7.5"
  }`

I Tried nohoist options, but no changes for me

**Comment by andreialecu** [comment]
@petebacondarwin is this something I might be able to send a PR for? Do you think it requires extensive changes or is just a minor fix?

I have some time to poke around, but just need to clarify that it's worth doing or it's blocked by something else. Some pointers to relevant files would help as well.

**Comment by petebacondarwin** [comment]
I need to investigate this. It is possible that there is a simple fix in ngcc but also that it could be that the hoisting makes it very difficult to fix.

**Comment by jasonhodges** [comment]
I have tried adding the following to the package.json files of my projects, removed node_modules and ran `yarn`

```"workspaces": {
    "nohoist": [
      "**/@angular/*",
      "**/@angular/*/**"
    ]
  },
``` 

However, I still receive errors when running `ng build`. The errors are [here](https://github.com/angular/components/issues/18637#issuecomment-602720546)

**Comment by Hermholtz** [comment]
I'm NOT using `yarn` but `npm` and got similar problem. What's frightening it seems the problem appears randomly.

I upgraded packages in my project 12 days ago. I updated package.json with all fresh versions (angular 9.0.6 at the moment), deleted package-lock.json and node_modules entirely, then did `npm install` to refresh everything.

Today while doing some CSS fixes in components I read release notes for angular 9.0.7 and concluded it's a good idea to upgrade for the bugfixes. So I updated package.json, deleted lock and node_modules and reinstalled, followed by `npm run build`. I got errors similar to shown below and to what OP reports regarding flex-layout.

So I restored my package.json and package-lock.json from repo (to recover my previous state with angular 9.0.6), deleted node_modules and did `npm install`. I then ran `npm run build` and still got errors.

I then again deleted node_modules (without touching package.json and package-lock.json) and reinstalled with `npm install`. And the build succeeded.

So it was not deterministic on last 2 attempts. I'm not an expert on this matter, but something tells me it may not be related to sequence of steps I did. It's some kind of obscure bug that surfaces at random times.

I don't have time for further tinkering, hopefully that will help find root cause somehow...

I also got the same problem with other application with Flex just like @andreialecu.

So to summarize. In my case the problem occurred with `ngx-mat-select-search` and `@angular/flex-layout`. I'm using "@angular/flex-layout": "^9.0.0-beta.29" and "ngx-mat-select-search": "^2.1.2".

```
> ng build admin --configuration=dev

0% compiling
Compiling ngx-mat-select-search : es2015 as esm2015

ERROR in Failed to compile entry-point ngx-mat-select-search (es2015 as esm2015) due to compilation errors:
node_modules/@angular/material/button/button-module.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of NgxMatSelectSearchModule, but could not be resolved to an NgModule class.

This likely means that the library (@angular/material/button) which declares MatButtonModule has not been processed correctly by ngcc, or is not 
compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

8 export declare class MatButtonModule {
                       ~~~~~~~~~~~~~~~
node_modules/@angular/material/checkbox/checkbox-module.d.ts:11:22 - error NG6002: Appears in the NgModule.imports of NgxMatSelectSearchModule, but could not be resolved to an NgModule class.

This likely means that the library (@angular/material/checkbox) which declares MatCheckboxModule has not been processed correctly by ngcc, or is 
not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

11 export declare class MatCheckboxModule {
                        ~~~~~~~~~~~~~~~~~
node_modules/@angular/material/icon/icon-module.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of NgxMatSelectSearchModule, but could 
not be resolved to an NgModule class.

This likely means that the library (@angular/material/icon) which declares MatIconModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

8 export declare class MatIconModule {
                       ~~~~~~~~~~~~~
node_modules/@angular/material/input/input-module.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of NgxMatSelectSearchModule, but could not be resolved to an NgModule class.

This likely means that the library (@angular/material/input) which declares MatInputModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

8 export declare class MatInputModule {
                       ~~~~~~~~~~~~~~
node_modules/@angular/material/progress-spinner/progress-spinner-module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of NgxMatSelectSearchModule, but could not be resolved to an NgModule class.

This likely means that the library (@angular/material/progress-spinner) which declares MatProgressSpinnerModule has not been processed correctly 
by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

1 export declare class MatProgressSpinnerModule {
                       ~~~~~~~~~~~~~~~~~~~~~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

```
Angular CLI: 9.0.6
Node: 12.16.1
OS: win32 x64

Angular: 9.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.900.6
@angular-devkit/build-optimizer   0.900.6
@angular-devkit/build-webpack     0.900.6
@angular-devkit/core              9.0.6
@angular-devkit/schematics        9.0.6
@angular/cdk                      9.1.2
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.1.2
@ngtools/webpack                  9.0.6
@schematics/angular               9.0.6
@schematics/update                0.900.6
rxjs                              6.5.3
typescript                        3.7.5
webpack                           4.41.2
```

**Comment by petebacondarwin** [comment]
@Hermholtz - is there any symlinking going on in your project? Is it a monorepo with links between projects?

It is notable that this bit of your output:

```
0% compiling
Compiling ngx-mat-select-search : es2015 as esm2015
```

indicates that either 

a) the dependencies of `ngx-mat-select-search` have already been compiled, or
a) ngcc is not able to find the dependencies of `ngx-mat-select-search`

Notably `ngx-mat-select-search` has many dependencies including, obviously, `@angular/material/button`. And it appears that this is not being compiled.

Have you run any previous tasks, such as `ngcc` as a postinstall hook for example, before running this build?

**Comment by mpoiriert** [comment]
I am in the same kind of situation of @Hermholtz, I am not using yarn and I starting from a fresh install of 9.0.7, then added angulal/http and it wasn't compiling.

Fount this thread, wasn't sure it was related, decided to try a earlier version (9.0.4), installed it fresh. Work on the first time.

I don't have my old log and didn't need to do some back and forth  but I just want to mention it so we have more information about the issue.

FYI I am "new" to the stack since I am normally a PHP/Symfony developer, so I don't have a lot of insight about the issue....

**Comment by petebacondarwin** [comment]
@mpoiriert - welcome to the Angular stack. I am sorry this is not the best experience to be starting with!

When you say:

> then added angulal/http and it wasn't compiling.

How did you add this package? Were you running `ng serve` at the time?
Have you tried updating to 9.0.7 again since then?

If this happens again can you capture the logged errors so that we can see what processes where running when you had the error and exactly what the error was.

**Comment by mpoiriert** [comment]
Pretty sure I did a ng install @angular/http (I may have did a npm install since I was using that before using ng cli).
The serve might have been running when I did the install but I am pretty sure I restarted it after since it's happen pretty often that the server/watch is failing when doing big changes.

Didn't try again for 9.0.7, I was thinking about it, I'll give it a shot a bit later today. I'll get back with more detail after.

**Comment by andreialecu** [comment]
@mpoiriert do you mean `@angular/common/http`? `@angular/http` has been deprecated since Angular 7.

**Comment by Hermholtz** [comment]
@petebacondarwin aswering your questions:
> is there any symlinking going on in your project? 
No, it's Windows, I wouldn't dare symlinking anything.

> Is it a monorepo with links between projects?
Just a normal repo with 2 angular apps and one common library.

> the dependencies of ngx-mat-select-search have already been compiled
That is correct. They were compiled during previous run.

> Have you run any previous tasks, such as ngcc as a postinstall hook for example, before running this build?
Yes, full `npm run build` in development mode. It stopped at the same phase as this one, so this one did not recompile these ES2015 modules already compiled (I presume).

**Comment by mpoiriert** [comment]
@andreialecu Yes sorry I meant @angular/common/http so obvioulsy I didn't "install" it the way I explained...

I just remove my node_modules folder, set "everything" to 9.0.7 (fix version not using ~ ) and it's now working.

I also tried installing version 9.0.6 and then adding the ~ do a update (to make sure with a different flow) and it's still working.

So there is something about the flow like @Hermholtz mention. Cleaning the node_modules might have fix the issue for me or it might be a completely different issue.

**Comment by edocbuhtig** [comment]
Guys I had a big tough time finding a solution, have pasted the exact error it is caused by (http) please see my steps to reproduce above. Original bug posted by me here > https://github.com/ionic-team/ionic/issues/20716 but the team said it is not in our radar :) its an Angular issue.

**Comment by Hermholtz** [comment]
Fingers crossed!
