### ISSUE TITLE
NgFor - Property 'X' does not exist on type 'Y'

### ISSUE THREAD

**Issue by ogspink** [angular/angular#35749]
# 🐞 bug report

### Description

Simple *ngFor usage with Ivy enabled causes error

```html
<pre>
    <div *ngFor="let item of items">{{ item.key }}</div>
</pre>
```

## 🔥 Exception or Error
<pre><code>
Property 'item' does not exist on type 'ItemsComponent'.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
9.0.1
</code></pre>

**Comment by pkozlowski-opensource** [comment]
We _definitively_ need a minimal reproduce scenario as I couldn't reproduce it in isolation: https://ng-run.com/edit/2zls8tbMktc6uYSOrGwT

**Comment by ogspink** [comment]
The error appears only in one specific module of my app. Error in terminal shows only after editing template file of that component. 

Template:

```html
<table class="table" [formGroup]="form">
    <thead>
        <tr class="table__head-row">
            <th class="table__head-cell">{{ 'Agreements.Content' | translate }}</th>
        </tr>
    </thead>
    <tbody formArrayName="list">
        <tr class="table__body-row" *ngFor="let pkd of ctrl.controls">
            <td class="table__body-cell">{{ pkd.value | json }}</td>
        </tr>
    </tbody>
</table>
```

Ts. : 

<pre><code>
export class PkdListComponent {
    @Input() form: FormGroup;

    get ctrl() {
        return this.form.get('list') as FormArray;
    }
}
</code></pre>

Error in terminal:

<pre><code>
 ERROR in src/app/commons/pkd/components/pkd-list/pkd-list.component.pug:7:30 - error TS2339: Property 'pkd' does not exist on type 'PkdListComponent'.
    
    7             td.table__body-cell {{ pkd.value | json }}
                                   ~~~
    
      src/app/commons/pkd/components/pkd-list/pkd-list.component.ts:6:18
        6     templateUrl: './pkd-list.component.pug',

</pre></code>

**Comment by mlc-mlapis** [comment]
@ogspink Why don't you want to understand that the clear and simple reproduction demo is the key to any solution?
