### ISSUE TITLE
All Var and Const exports should have Type Information output by dgeni

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#3574]
In the docs, we have "Attribute Var" but this "Var" is not adding meaningful/helpful info for the user. `Attribute` can be called with `new Attribute(...)` or `Attribute(...)` or `@Attribute(...)`. What we really want to see is type information. (In this case, `Attribute: AttributeFactory` with no trailing "Var").

Likewise, for Const, we want to do the same thing.
Thus `Attribute Var` --> `Attribute: Attribute Factory`
and `httpInjectables Const` --> `HTTP_INJECTABLES: List<any>` (** the fixing of the name of this const is a separate issue, but we didn't have a capital-snake-case example so this will have to do**)

For the left-nav in dgeni, however, it is fine to omit the type information.

**Comment by mhevery** [comment]
fixed
