### ISSUE TITLE
Change detection on ES6 Generators causes unwanted side-effects and return wrong results

### ISSUE THREAD

**Issue by swen128** [angular/angular#35742]
# 🐞 bug report

### Affected Package

The issue is caused by [areIterablesEqual function](https://github.com/angular/angular/blob/a95e81978b14f6081ed3a8b4ceff358276b4d085/packages/core/src/change_detection/change_detection_util.ts#L74-L86) in the package @angular/core.

### Is this a regression?

 No

### Description

Inside Angular's component, the `next` method of [ES6 Generator](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Generator) almost always returns  `{done: true, value: undefined}`, even when you have never touched the generator anywhere else in your application code.

This is because Angular's change detection use [this function](https://github.com/angular/angular/blob/a95e81978b14f6081ed3a8b4ceff358276b4d085/packages/core/src/change_detection/change_detection_util.ts#L74-L86) to compare iterables:

```typescript
export function areIterablesEqual(
    a: any, b: any, comparator: (a: any, b: any) => boolean): boolean {
  const iterator1 = a[getSymbolIterator()]();
  const iterator2 = b[getSymbolIterator()]();

  while (true) {
    const item1 = iterator1.next();
    const item2 = iterator2.next();
    if (item1.done && item2.done) return true;
    if (item1.done || item2.done) return false;
    if (!comparator(item1.value, item2.value)) return false;
  }
}
```

`areIterablesEqual` apparently assumes that `[Symbol.generator]()` creates a new instance of iterator upon each call, and thus exhausts the iterator without care.

It is, however, quite common to implement both `Iterable` and `Iterator` in a single object and let `[Symbol.generator]()` to just return `this`. The pattern also applies to generators.

In such case, `areIterablesEqual` exhausts the iterable, and it will always return `{done: true, value: undefined}` afterward.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-issue-repro2-meqpb4

## 🔥 Exception or Error

In the above reproduction, 
```html
<div *ngFor="let x of generator">{{ x }}</div>
```
renders nothing, as if the generator is empty.

## 🌍  Your Environment

Dependencies in the above stackblitz:
```json
"@angular/common": "^9.0.4",
"@angular/compiler": "^9.0.4",
"@angular/core": "^9.0.4",
"@angular/forms": "^9.0.4",
"@angular/platform-browser": "^9.0.4",
"@angular/platform-browser-dynamic": "^9.0.4",
"@angular/router": "^9.0.4",
"core-js": "2",
"rxjs": "^6.5.4",
"tslib": "^1.11.1",
"zone.js": "^0.10.2"
```

**Anything else relevant?**

None

**Comment by Airblader** [comment]
I don't think using such generators in ngFor can ever be meaningful, since it's impossible for Angular to run change detection on it. I would think in this case it's simply up to you to convert the iterator to an array of the data beforehand (or to an reusable iterator).

It would be nice if Angular could detect this and log a warning or something, but I doubt that that's possible.

Or do you have a specific suggestion on what Angular should do here?

**Comment by swen128** [comment]
I used ngFor just to show you the generator was fully consumed in change detection. The problem can happen without you ever touching the generator in your application code. You can't extract any values from generators. In addition, looping over generator may well be computationally expensive or even infinite.

Can Angular detect changes in `Iterator` (not `Iterable`) objects?
If so, I think `areIterablesEqual` should just compare iterators returned by `[Symbol.iterator]()`.

**Comment by Airblader** [comment]
> In addition, looping over generator may well be highly expensive or even infinite. (The whole point of iterator is to defer such computation.)

Rendering an infinite generator is bound to cause problems. You'd just crash the browser. And using computationally expensive generators from the template is a strong antipattern exactly because of change detection. I would insist that this is something the developer should handle better.

NgFor is built with the very intention of rerendering whenever the produced data changes. If your generator only works once, it's IMHO not suited for NgFor.

**Comment by swen128** [comment]
My apologies, I misunderstood the behavior of `areIterablesEqual`, still there's serious problem nonetheless.

**When `a` and `b` reference the exact same generator object, `areIterablesEqual(a, b)` returns `false`**, and the generator is consumed twice or more in the process.

```typescript
const iterator1 = a[getSymbolIterator()]();
const iterator2 = b[getSymbolIterator()]();
```

In the above lines of the code, both `iterator1` and `iterator2` will point to the same generator. Therefore `item1` and `item2` are two consecutive elements returned by the generator:

```typescript
const item1 = iterator1.next();
const item2 = iterator2.next();
```

`areIterablesEqual` then compares these two different values and returns `false`.

**Comment by swen128** [comment]
> NgFor is built with the very intention of rerendering whenever the produced data changes. If your generator only works once, it's IMHO not suited for NgFor.

I've made [another stackblitz](https://stackblitz.com/edit/angular-issue-repro2-8dmupl) to show a more realistic example, which does not use NgFor at all. The example implements a custom structural directive for infinite scroll, similar to [virtual scroll of Angular CDK](https://material.angular.io/cdk/scrolling/overview).

The directive takes a iterator by `let x of iterator` syntax. Every time component is scrolled down to the bottom, it calls `iterator.next()` and renders the template with the returned value. It's fine as long as the iterator does not have `[Symbol.iterator]()` method. But when you uncomment the following lines in `app.component.ts`, you will see weird results and a lot of `ExpressionChangedAfterItHasBeenCheckedError`s in the console.

```typescript
[Symbol.iterator]() {
  return this;
}
```

**Comment by petebacondarwin** [comment]
From the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators#iterables): 

> It may be possible to iterate over an iterable more than once, or only once. It is up to the programmer to know which is the case.
>
>Iterables which can iterate only once (such as Generators) customarily return this from their @@iterator method, whereas iterables which can be iterated many times must return a new iterator on each invocation of @@iterator.

So as I see it this one should not be passing an iterable that can only be run once into any part of Angular that will be checking it for diffs during change detection.

**Comment by alxhub** [comment]
^ @petebacondarwin is correct - `NgFor` fundamentally expects that it can repeat iteration of an iterable on every change detection cycle.
