### ISSUE TITLE
Entry point 'xxx' contains deep imports into 'yyy' in lib

### ISSUE THREAD

**Issue by kekel87** [angular/angular#35750]
# 🐞 bug report

### Description

This issue follows https://github.com/angular/angular/issues/35615#

I am trying to update our [project](https://github.com/quentin-ol/ngx-openlayers) in angular 9.
Everything is fine, except that I get this warning when I consume the library.

I try to use `ngcc.config.js` to avoid the warning message but it doesn't work.
```
// architecture
projects/
    ngx-openlayers/  <----- lib with ol in peerDependencies
      ng-package.json
/src                 <----- demo project
ngcc.config.js       <----- i put ngcc.config.js here
```
```js
// ngcc.config.js
module.exports = {
  packages: {
    'ngx-openlayers': {
      ignorableDeepImportMatchers: [
        /ol\//,
      ]
    },
  },
};
```
I also don't really understand how this configuration will work once the library is deployed.

## 🔬 Minimal Reproduction
https://github.com/kekel87/ngx-openlayers/tree/chore-update-to-angular-9
```
ng build ngx-openlayers --prod
ng serve
```

## 🔥 Exception or Error
<pre><code>WARNING in Entry point 'ngx-openlayers' contains deep imports into
  '[pwd]/ngx-openlayers/node_modules/ol/View',
  '[pwd]/ngx-openlayers/node_modules/ol/Map',
  '[pwd]/ngx-openlayers/node_modules/ol/layer',
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 9.0.4
Node: 10.15.2
OS: linux x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.4
@angular-devkit/build-angular      0.900.4
@angular-devkit/build-ng-packagr   0.900.4
@angular-devkit/build-optimizer    0.900.4
@angular-devkit/build-webpack      0.900.4
@angular-devkit/core               9.0.4
@angular-devkit/schematics         9.0.4
@ngtools/webpack                   9.0.4
@schematics/angular                9.0.4
@schematics/update                 0.900.4
ng-packagr                         9.0.2
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Comment by petebacondarwin** [comment]
Thanks. I'll look into it.

**Comment by petebacondarwin** [comment]
@kekel87 - sorry it has taken a while to look into this. Your reproduction project was already really close to solving this as it stands.

You had already correctly added in an `ngcc.config.js` at `projects/ngx-openlayers/ngcc.config.js` with the correct format:

```js
module.exports = {
  ignorableDeepImportMatchers: [/ol\//]
};
```

(this is a "package" version of the file, which is slightly different to the "project" version which must also contain a `packages` property in the exported object.)

All you had to do now was to ensure that the `ngcc.config.js` file ends up in the distributable built files by modifying the `ng-package.json` file:

```json
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/ngx-openlayers",
  "assets": [
    "ngcc.config.js"
  ],
  ...
```

This means that the generated package folder under `dist` contains the `ngcc.config.js` which ngcc can then read and configure the deep-import ignoring appropriately.

**Comment by petebacondarwin** [comment]
Closing this issue now as ngcc already supports ignoring these warnings for local packages in `dist`.

**Comment by petebacondarwin** [comment]
Hold on I might have spoken too soon...

**Comment by petebacondarwin** [comment]
We do read that `ngcc.config.js` from the package but currently only parsing the entry-point information from it rather and not the `ignorableDeepImportMatchers` property 😱 

I'll fix it in a PR today.

**Comment by Sam-Lin-MillersLab** [comment]
it is odd. It doesn't work on my project. @kekel87 does it work on yours? 
I double check the node_module I can find the ngcc.config.js there but it doesn't work as expected.
