### ISSUE TITLE
Unexpected interpolation on build

### ISSUE THREAD

**Issue by SkrupSulten** [angular/angular#35752]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
I have no idea

### Is this a regression?

Yes, the previous version in which this bug was not present was 8

### Description

I get an error when I try to build

## 🔬 Minimal Reproduction
https://ng-run.com/edit/brirFkaAgFRoRsNqjWa6

## 🔥 Exception or Error
<pre><code>
ERROR in Error: Internal Error: Unexpected interpolation
    at error (C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:2721:15)
    at _AstToIrVisitor.interpolationFunction (C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17867:179)
    at _AstToIrVisitor.visitInterpolation (C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:8517:29)
    at Interpolation.visit (C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:7590:28)
    at convertPropertyBinding (C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:8292:52)
    at TemplateDefinitionBuilder.convertPropertyBinding (C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17867:44)
    at Object.value (C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17756:63)
    at Array.map (<anonymous>)
    at C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17816:38
    at C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17094:83
    at Array.map (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17094:56)
    at C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17636:60
    at C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17070:81
    at Array.forEach (<anonymous>)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.4
Node: 12.4.0
OS: win32 x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.4
@angular-devkit/build-angular      0.900.4
@angular-devkit/build-optimizer    0.900.4
@angular-devkit/build-webpack      0.900.4
@angular-devkit/core               9.0.4
@angular-devkit/schematics         9.0.4
@angular/cdk                       9.1.0
@angular/material                  9.1.0
@angular/material-moment-adapter   9.1.0
@ngtools/webpack                   9.0.4
@schematics/angular                9.0.4
@schematics/update                 0.900.4
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Anything else relevant?**

**Comment by splincode** [comment]
please create real example with reproduce

**Comment by SkrupSulten** [comment]
Sorry, but I don't think I'm able to provide a reproducible example

**Comment by EmaGht** [comment]
Start commenting out component's templates until you find the file which is throwing this compilation error, then double check it and make sure that you don't have random `{{}}` around.

We need a better error diagnostic boys.
I can't believe we still cannot see which is the file where the compiler died

**Comment by SkrupSulten** [comment]
We have 98 components wherein the problem could be. The error message gives no clue as to which file is the culprit.

I can only agree with EmaGht that better diagnostics is needed.

**Comment by pkozlowski-opensource** [comment]
YES, we should definitively have the file name name for a template _and_ the exact line / column number. Putting it in the backlog.

**Comment by SkrupSulten** [comment]
I finally found out what the problem was:

`ngxPermissionsOnly="{{ item.permission }}"`

I'll open an issue on ngx-permissions

**Comment by pkozlowski-opensource** [comment]
@SkrupSulten I still would love to improve the error reporting on the compiler side so I've re-opened this issue. Could you please link back to the issue you've opened on ngx-permissions so we can understand the scenario?

**Comment by pkozlowski-opensource** [comment]
I was trying to reproduce it in isolation (https://ng-run.com/edit/lBYdGVDeTbNCKzbRc1h1?open=app%2Fapp.component.ts) but couldn't...

**Comment by SkrupSulten** [comment]
I haven't yet opened an issue. I'm not sure who's at fault at this stage. You could try and follow the instructions at https://www.npmjs.com/package/ngx-permissions

We used it in a ng-template - not sure if it makes a difference:

`<ng-template #menuItemTemplate let-item="item" let-parentItem="parentItem">
    <ng-container *ngIf="!item.permission" [ngTemplateOutlet]="menuItemInnerTemplate" [ngTemplateOutletContext]="{ item: item, parentItem: parentItem }"></ng-container>
    <ng-template *ngIf="item.permission" ngxPermissionsOnly="{{ item.permission }}">
        <ng-container [ngTemplateOutlet]="menuItemInnerTemplate" [ngTemplateOutletContext]="{ item: item, parentItem: parentItem }"></ng-container>
    </ng-template>
</ng-template>`

The truth is we don't actually need ngx-permissions. It came with a "theme" we bought, but don't actually use it, so I think I'll get rid of it.

**Comment by pkozlowski-opensource** [comment]
> We used it in a ng-template - not sure if it makes a difference

Ha! It does! Now I can reproduce: https://ng-run.com/edit/brirFkaAgFRoRsNqjWa6

I think that this is a bug in Angular compiler as this:
* should not fail (an @Input should be correctly bound);
* we should review all cases where we throw "unexpected interpolation" to make sure that this error includes file name and a column/row.

**Comment by SkrupSulten** [comment]
Nice work!
