### ISSUE TITLE
@angular/localize adds unnecessary whitespace

### ISSUE THREAD

**Issue by kamilchlebek** [angular/angular#35754]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/localize (probably)

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular 8

### Description

For template: 
```
<span *ngIf="type === 'days'" class="test">
  {{ value }}
  <span i18n>
    {value, plural, =1 {day} other {days}}
  </span>
</span>
```
I have test that checks if proper content was generated https://github.com/kamilchlebek/angular-i18n-whitespace-issue/blob/master/src/app/app.component.spec.ts#L15

:heavy_check_mark: When using angular 8:
the output of `span.nativeElement` is:
```
<span _ngcontent-a-c0="" class="test"> 10 <span _ngcontent-a-c0=""><!--bindings={
  "ng-reflect-ng-plural": "10"
}--><!----><!---->days</span></span>
```
and the test passes (as `span.nativeElement.textContent.trim()` is equal to `10 days`)

:x:  When using angular 9:
the output of `span.nativeElement` is:
```
<span _ngcontent-a-c0="" class="test"> 10 <span _ngcontent-a-c0=""> <!--bindings={
  "ng-reflect-ng-plural": "10"
}--><!----><!---->days </span></span>
```

and the test **fails** (as `span.nativeElement.textContent.trim()` is equal to `10  days`) **extra whitespace**

## 🔬 Minimal Reproduction

https://github.com/kamilchlebek/angular-i18n-whitespace-issue/tree/master - angular 9
https://github.com/kamilchlebek/angular-i18n-whitespace-issue/tree/v8 - angular 8

Steps:
1. Run `ng test`

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 9.0.4
Node: 10.16.0
OS: linux x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.4
@angular-devkit/build-angular     0.900.4
@angular-devkit/build-optimizer   0.900.4
@angular-devkit/build-webpack     0.900.4
@angular-devkit/core              9.0.4
@angular-devkit/schematics        9.0.4
@ngtools/webpack                  9.0.4
@schematics/angular               9.0.4
@schematics/update                0.900.4
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Comment by petebacondarwin** [comment]
Thanks for the reproduction @kamilchlebek - tracking as FW-1934

**Comment by sonukapoor** [comment]
I will take a look @petebacondarwin. Please assign to me.

**Comment by petebacondarwin** [comment]
I was just looking at this I believe it works as expected... (i.e. it was actually a bug with the v8 whitespace collapsing...

Looking at the template:

```
<span *ngIf="type === 'days'" class="test">
  {{ value }}
  <span i18n>
    {value, plural, =1 {day} other {days}}
  </span>
</span>
```

After standard HTML whitespace collapsing, this is equivalent to:

```
<span *ngIf="type === 'days'" class="test"> {{ value }} <span i18n> {value, plural, =1 {day} other {days}} </span></span>
```

Note that there are spaces around both the `{{ value }}` binding and the ICU.

So I would expect the output to be equivalent to:

```
<span class="test"> 10 <span i18n> days </span></span>
```

which is what we see. So when you look at the `textContent` of the outer `<span>` you get `.10..days.`, where I have replaced the spaces with dots for clarity.

**Comment by petebacondarwin** [comment]
Note that your unit tests pass if you change the template to be:

```
<span *ngIf="type === 'days'" class="test">
  {{ value }}
  <span i18n>{value, plural, =1 {day} other {days}}</span>
</span>
```

where there is no whitespace between the ICU and its containing span, so the whitespace collapsing does not add any whitespace around the `days` string.

**Comment by kamilchlebek** [comment]
Many thanks for investigation and comprehensive explanation. It's all clear now, feel free to close this issue.

**Comment by petebacondarwin** [comment]
Thanks @kamilchlebek .
