### ISSUE TITLE
Throwing error when upgrading to alpha.34 router

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#3575]
After I upgrade to alpha version 34 of the router I get errors related to the routeConfig object at runtime:

\router_2.RouteConfig is not a function

Running against alpha.33 does not produce the same error. 

The typings seem ok, so this is a runtime error when using version 34

**Comment by Zyzle** [comment]
@thelgevold have a look here for a work around #3556

**Comment by thelgevold** [comment]
Thanks @Zyzle

**Comment by pkozlowski-opensource** [comment]
Right, this is duplicate of #3556
