### ISSUE TITLE
Angular running `ngcc` within unwanted diretory

### ISSUE THREAD

**Issue by nunocastromartins** [angular/angular#35762]
# 🐞 bug report

### Affected Package

Possibly `@angular/cli`.

### Is this a regression?

I am not absolutely sure, I will test with 9.0.2 when I have some more time, but I don't believe this happens with Angular < 9.

### Description

This is a follow-up to https://github.com/angular/angular/issues/35757#issuecomment-592642764.

I have an Angular workspace with two projects: `app`, and `lib`. Respectively, an Angular app and an Angular library packaged by `ng-packgr`. The lib is the "main product" and the app is simply a demo using the lib. This is (a simplification of) the structure of the repo:

```
app/
  dist/... <- Created by running `ng build app`
  src/...
lib/
  dist/... <- Created by running `ng build lib`
  src/...
  tsconfig.lib.json
angular.json
tsconfig.json
```

Within `tsconfig.json` (used when serving and building `app`), I specify in `paths` that references to `lib` should resolve to `lib/src` and `lib/dist` is explicitly excluded in the config.

Now, if I serve or build `app` before building the `lib` (_i.e._ if `lib/dist` does not exist), Angular seems to "compile `app` as if `lib` was part of its source code", which is what I would expect since all references of `lib` within `app` point to `lib/src`.

However, when `lib/dist` exists (a path that is explicitly excluded in the TS config), serving or building `app` causes Angular to run `ngcc` within `lib/dist`, seen by the message `Compiling lib : module as esm5` and the fact that I now have Ivy related files within `lib/dist`.

I believe that Angular should **not** be making changes to this folder, or even assume that it may exist. These are some reasons:
1. If I were to now publish `lib`, the folder is "polluted" with Ivy related files (not actually an issue since in practice production builds rebuild `lib/dist` from scratch).
2. If I build `lib`, then serve or build `app` (causing Ivy files to be generated within `lib/dist`), then rebuild `lib` (which for an unrelated reason I do with the option `"deleteDestPath": false` of `ng-packgr`), attempting to serve or build `app` will now fail with errors similar to: `ERROR in Tried to overwrite [path-to-lib-file].d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.` 

## 🔬 Minimal Reproduction

I don't currently have a minimal reproduction. If the above description of the problem is not enough, I may be able to provide one tomorrow.

## 🌍  Your Environment

**Angular Version:**
```
Angular CLI: 9.0.4
Node: 13.9.0
OS: linux x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.4
@angular-devkit/build-angular      0.900.4
@angular-devkit/build-ng-packagr   0.900.4
@angular-devkit/build-optimizer    0.900.4
@angular-devkit/build-webpack      0.900.4
@angular-devkit/core               9.0.4
@angular-devkit/schematics         9.0.4
@angular/cdk                       9.1.0
@ngtools/webpack                   9.0.4
@schematics/angular                9.0.4
@schematics/update                 0.900.4
ng-packagr                         9.0.2
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
```

**Comment by petebacondarwin** [comment]
Thanks @nunocastromartins - this is a known behaviour. If you have built the local library in non-Ivy mode then the consuming app needs to convert it to ivy before it can build itself. I am not sure of the best approach to avoid the problems you are seeing. @alan-agius4 can explain in more detail tomorrow.

**Comment by nunocastromartins** [comment]
What I find odd is that Angular is trying to find the built library at all when the TS config points directly to source code. In my opinion it shouldn't, and it should behave similarly to how it does when the library isn't built at all. If I wanted the current behaviour, I'd explicitly point references of `lib` to `lib/dist` instead of `lib/src`.

I'll await a more thorough explanation of what is going on, thank you! :)

**Comment by alan-agius4** [comment]
Hi @nunocastromartins,
Since the library is being built using VE, for it to work in an Ivy application, NGCC will need to be run on the library to transform it and make it compatible with Ivy.

> Now, if I serve or build app before building the lib (i.e. if lib/dist does not exist), Angular seems to "compile app as if lib was part of its source code", which is what I would expect since all references of lib within app point to lib/src.

This is because the library is being built as part of the application using the Ivy compiler, so NGCC doesn't need to run on that code. However, it's important to point out that such build configuration is discouraged, as the pipeline to build a library is different from that of the application so you might get undefined/different behaviour.

> If I build lib, then serve or build app (causing Ivy files to be generated within lib/dist), then rebuild lib (which for an unrelated reason I do with the option "deleteDestPath": false of ng-packgr), attempting to serve or build app will now fail with errors similar to: ERROR in Tried to overwrite [path-to-lib-file].d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.

If you are building both the application and library in `watch` mode, you should opt to use the default Angular CLI behaviour, where you build the library using Ivy, and when you are ready to publish the library to NPM you use `--prod` flag which will compile the library using the old view engine. (VE).

> If I were to now publish lib, the folder is "polluted" with Ivy related files (not actually an issue since in practice production builds rebuild lib/dist from scratch).

If you are building your library in VE, and you want to run tests prior to publishing it (Which you should) :), you should `pack` your library prior of doing so, so the workflow will look something like;
```
ng build mylib
npm pack dist/mylib
ng test
npm publish dist/mylib/mylib.tgz
```

> However, when lib/dist exists (a path that is explicitly excluded in the TS config), serving or building
Most likely you have a path mapping on `lib/dist`, Adding the path to `exclude` such folder will not take an effect when using mapped paths.

**Comment by nunocastromartins** [comment]
> Since the library is being built using VE, for it to work in an Ivy application, NGCC will need to be run on the library to transform it and make it compatible with Ivy.

Yes, but when I'm building `app` I'm not telling it to use the compiled version of `lib`, the config explicitly points all imports of `lib` to its source code, so Angular should be compiling `lib` as if it were part of `app`.

> However, it's important to point out that such build configuration is discouraged, as the pipeline to build a library is different from that of the application so you might get undefined/different behaviour.

Why? What undefined/different behaviour are we talking about? I've never noticed anything like that. To Angular, it should be as if `lib` is just another folder that is part of `app`. If `lib` is exporting Angular modules, services, components, and what not, why should it be any different than just having those same modules, services, and components within the source of `app`? Even though the pipeline is different for building an app and a lib, here I am **not** building a lib; I'm simply building an app as though `lib` is part of it.

Regardless, even if it is "discouraged", I'm being very explicit in my configuration, and the CLI is ignoring it.

> If you are building both the application and library in watch mode, you should opt to use the default Angular CLI behaviour, where you build the library using Ivy, and when you are ready to publish the library to NPM you use --prod flag which will compile the library using the old view engine. (VE).

I'm not doing that, though. I'm simply "serving" the app. Because the app is reading the source code of `lib`, whenever I change source files within `lib`, `app` is automatically recompiled. With this I don't have to run 2 processes, have more watchers watching files in my system, plus slower feedback loop. Correct me if I'm wrong, but with that approach, you run Rollup/`ng-packagr` in watch mode over `lib`, and then serve `app`, which is looking at the output of Rollup: this means that the app will only see changes in `lib` after Rollup outputs to `lib/dist`, instead of as soon as the source file changes. In my experience (I had that setup for a while) the feedback loop is slower and more system resources are used, especially if you have more than 1 lib in your repo, and `app` uses multiple of them.

With how I have things set up, `lib` is mostly only built in production mode in preparation to be published.

Still, my approach is similar to what you mentioned in one way: in development mode I'm testing `lib` with Ivy enabled (because `app` is being compiled in Ivy mode), and in production mode `lib` is built using VE to prepare it to be published.

I still believe that Angular is in the wrong here: Angular is behaving differently depending on the existence of a folder that it shouldn't even know exists, and making unwanted changes to said folder in the user's repository.

**Comment by alan-agius4** [comment]
>Why? What undefined/different behaviour are we talking about? I've never noticed anything like that. To Angular, it should be as if lib is just another folder that is part of app. If lib is exporting Angular modules, services, components, and what not, why should it be any different than just having those same modules, services, and components within the source of app? Even though the pipeline is different for building an app and a lib, here I am not building a lib; I'm simply building an app as though lib is part of it.

The library building pipeline uses different tools and settings from that of that of application. Thus the same input might result in a different output. 

> Still, my approach is similar to what you mentioned in one way: in development mode I'm testing lib with Ivy enabled (because app is being compiled in Ivy mode), and in production mode lib is built using VE to prepare it to be published. I still believe that Angular is in the wrong here: Angular is behaving differently depending on the existence of a folder that it shouldn't even know exists, and making unwanted changes to said folder in the user's repository.

I think it's best to setup a minimal reproduction that we can take a look at as this might be caused by various things.

**Comment by nunocastromartins** [comment]
I just spent quite a while trying to set up a minimal repro, but I'm not being able to reproduce it. In my minimal repo I can't get `app` to use the compiled version of `lib`, with a setup close to what I have in my actual project. In this minimal app, `app` always compiles using the source of `lib` (and not its `dist` folder): which I consider the correct behaviour.

Is there any way to "trace" the Angular compiler (run it in debug mode, or something) to try and understand why Angular is running `ngcc` on `lib/dist` in my actual project? I can consistently reproduce the behaviour there.

I'll try for a while longer to set up the minimal repro, but I'm not having a lot a luck.

**Comment by petebacondarwin** [comment]
You can debug the compiler using standard node.js debug tools. For example:

```
node --inspect-brk ./node_modules/.bin/ng build
```

Then I setup VS Code to attach to the process in `.vscode/launch.json`:

```
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Attach",
      "port": 9229,
      "skipFiles": [
        "<node_internals>/**"
      ]
   }
```

**Comment by nunocastromartins** [comment]
So far I've had no luck debugging this.

To test things out, I upgraded Angular to the latest version in another repo with a similar structure (an even larger one) and could not reproduce the issue (everything works as I expected it to work and Angular doesn't run `ngcc` in `dist` folders).

Since I can't reproduce this outside of the problematic repo, I'll close the issue for now, as it seems to indicate that there might be something wrong in the repo itself and not in Angular.

Thank you for your support! :)
