### ISSUE TITLE
dgeni should export classes with @private as interfaces

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#3576]
This can be fixed along with #1594

ApplicationRef, for example, is in the d.ts correctly as an interface, but output to API docs as a class.

See: https://github.com/borisyankov/DefinitelyTyped/blob/3b0f362204ea965952dafdb682a5274d527ef9d0/angular2/angular2.d.ts#L2154

Essentially, need to make the same fix we did for the d.ts in the dgeni template.
https://github.com/angular/angular/issues/3002

**Comment by btford** [comment]
I do not have time to take care of this in the near future. Removing myself.

Also reassigning as effort2, as this will certainly take more than a couple hours with our existing infrastructure.

**Comment by naomiblack** [comment]
@petebacondarwin can you have a look at this? It's complicating some of our API doc authoring work.

**Comment by petebacondarwin** [comment]
@naomiblack & @btford I have a fix for this. Care to take a look?
