### ISSUE TITLE
Add More ResponseType (Stream + SSE)

### ISSUE THREAD

**Issue by halimpuckjava** [angular/angular#35775]
hi

add support for responseType like : text/event-stream, appliaction/json+stream

**Comment by mlc-mlapis** [comment]
@halimpuckjava How would you use them? What would be additional benefits?

**Comment by halimpuckjava** [comment]
@mlc-mlapis imagine you develop a server with rest endpoint return steam of data with content-type 'text/event-stream', in front-end (angular) you consume this stream of data, angular httpclient responseType support only 'text - json - blob - bufferArray', so if i want to consume this stream i wait the whole data in stream to charge and return it as Array<T>
```
data: T[]
loadData()  {
    http.get(....).subscribe(obs => data = obs)
} 
```
client still wait the array of data come (poll model)

**Comment by mlc-mlapis** [comment]
@halimpuckjava But `text/event-stream` is the media type for Server-Sent Events (SSE) and it's something, that we can't mix with XHR requests, on which `HttpClientModule` is based.

You are using something like:
```
var sseSource = new EventSource(url);
sseSource.onmessage = function(event) {
   ...
};
```

**Comment by halimpuckjava** [comment]
@mlc-mlapis yes i know we cas resole this with SSE but i want to add more media types for response to adapt with data streaming

but with SSE there is one issue, how we can detect the completion of stream ?? sse support only 3 handler (onmessage, onopen, onerror) also if use addListener you must specify the event name of completion signal

**Comment by mlc-mlapis** [comment]
@halimpuckjava 

> I want to add more media types for a response to adapt with data streaming
I don't think that this cross meaning can be acceptable from the Angular core team.

> how we can detect the completion of stream
It's on your data API to understand what's going on. From a client, you can only use `evtSource.close();` to finish the listening.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
