### ISSUE TITLE
Angular 9. Can't bind to 'ngIf' since it isn't a known property of 'div'. Warning

### ISSUE THREAD

**Issue by Botu-source** [angular/angular#35774]
Hello. I have a problem with *ngIf directive.

Structure of the app: 1 Project and 2 libraries.

First library imports second: 

First Library module:
![image](https://user-images.githubusercontent.com/58546233/75606295-3d01ad80-5afc-11ea-9236-31c8e33963c7.png)

Second Library module:
![image](https://user-images.githubusercontent.com/58546233/75606306-5a367c00-5afc-11ea-80f8-d6adabc09ac8.png)

Project module (includes first which includes second): 
![image](https://user-images.githubusercontent.com/58546233/75606328-8fdb6500-5afc-11ea-8238-fed74d91d063.png)

If I use *ngIf directive in project everything works normally.
But if I use *ngIf in components from First Library it doesn't work normally.
I have no errors, but I have only warnings
![image](https://user-images.githubusercontent.com/58546233/75606355-d16c1000-5afc-11ea-80ec-6d0a8d7b59ab.png)

What wrong?  What the problem and how I can resolve it?
I tried to import CommonModule but It doesn't help me

**Comment by asajuenitan** [comment]
For any custom module you create, add `CommonModule` to the imports

**Comment by Botu-source** [comment]
> Для любого пользовательского модуля, который вы создаете, добавьте `CommonModule`в импорт

I added. Screenshots without it but I added. Unfortunatly I still have warning

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
