### ISSUE TITLE
Update docs for i18n

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular#35776]
# 📚 Docs or angular.io bug report

### Description

* https://angular.io/generated/zips/i18n/i18n.zip is source code for Angular 8 not Angular 9. Please add demo for Angular 9.
* [Locale data for 'en-US' cannot be found.  No locale data will be included for this locale. ](https://stackoverflow.com/questions/59514703/angular-9-locale-data-for-en-us-cannot-be-found-no-locale-data-will-be-includ)
* Missing documentation for targets in  https://angular.io/guide/i18n#merge-the-completed-translation-file-into-the-app

```json
"projects": {
  ...
  "angular.io-example": {
    ...
    "i18n": {
      "sourceLocale": "en-US",
      "locales": {
        "fr": "src/locale/messages.fr.xlf"
      }
    }
    ...
    "targets": {
      ...
    }
  }
}
```
### Anything else relevant?

Please add docs for `loadTranslations`, `clearTranslations` and use i18n for library in ng-packagr.

**Comment by luchillo17** [comment]
There are no docs about how to configure the locale so `baseHref` is what you expect.

In my case, I wanted to deploy the localized builds to 3 different domains but the `baseHref` was set to each locale like `<base href="/en-US/" />`, thus messing with my deploys.

I had to look into the `angular.json` schema to understand how to configure the locale to not touch the `baseHref`.

**Comment by petebacondarwin** [comment]
@luchillo17 - as you worked out it is possible to modify the angular.json to change the basehref per locale - https://github.com/angular/angular-cli/issues/17260#issuecomment-601959316.

We should definitely update the guide at https://next.angular.io/guide/i18n to explain this... cc @kapunahelewong

**Comment by aheadmode** [comment]
With the release of version 9, Angular proclaimed i18n improvements loudly. The marketing team did their job, but the "new features" are not documented. Zero documentation. Pain in the ass!

**Comment by luchillo17** [comment]
@aheadmode Can you list which ones you have found that are not yet implemented?

**Comment by xiaoxiangmoe** [comment]
@aheadmode Documentation  for `$localize` , `custom IDs` and `loadTranslations`:
https://blog.ninja-squad.com/2019/12/10/angular-localize/

**Comment by luchillo17** [comment]
It's been stated that $localize is not a public API yet, thus not yet documented:

https://github.com/angular/angular/issues/36714#issuecomment-616367270

**Comment by kapunahelewong** [comment]
@rockument69 is working on a [rewrite of the i18n doc](https://github.com/angular/angular/pull/36924). fyi, @rockument69

**Comment by rockument69** [comment]
Created PR to update the i18n example: [37418](https://github.com/angular/angular/pull/37418)

**Comment by rockument69** [comment]
This is now in progress in PR [36924](https://github.com/angular/angular/pull/36924).

**Comment by rockument69** [comment]
PR [36924](https://github.com/angular/angular/pull/36924) addresses the following parts of this issue:

> * https://angular.io/generated/zips/i18n/i18n.zip is source code for Angular 8 not Angular 9. Please add demo for Angular 9.
> * Missing documentation for targets in  https://angular.io/guide/i18n#merge-the-completed-translation-file-into-the-app
> 

The above PR does not address the following:

> *  Please add docs for `loadTranslations`and `clearTranslations`.
> *  Use i18n for library in ng-packagr.
> 

Some of this content requires a description of $localize, which is not a public API yet (see [comment](https://github.com/angular/angular/issues/35776#issuecomment-623273827)).

These topics (runtime translations, library) are reserved for a future PR based the separation of i18n docs into 3 separate "Task" docs:

*  Localizing your app: This will include the above topics.
*  Translating apps for different locales
*  Translating plurals and alternate selections

For details, see the [i18n Documentation Plan](https://docs.google.com/document/d/1aV2TKsIqry7JnNiHEfhmheu5rNAbNl1IRYVhYErc7Ks/edit?usp=sharing).

The above PR does not address the following:

> * [Locale data for 'en-US' cannot be found.  No locale data will be included for this locale. ](https://stackoverflow.com/questions/59514703/angular-9-locale-data-for-en-us-cannot-be-found-no-locale-data-will-be-includ)

This may be a bug; it doesn't work as expected.

**Comment by rockument69** [comment]
@xiaoxiangmoe : Hello, thanks for adding this issue. I have a plan to address part of the issue in a PR as described above in [my comment](https://github.com/angular/angular/issues/35776#issuecomment-640934138). I want to create new issues for the other requests, so that my PR can close this issue. Would this be okay with you? Thanks.

**Comment by rockument69** [comment]
`Locale data for 'en-US' cannot be found. No locale data will be included for this locale.`
This may be a bug; it doesn't work as expected. I have created a new issue for it:
https://github.com/angular/angular/issues/37562

**Comment by rockument69** [comment]
I have created a new issue for future work, integrating docs for `loadTranslations` and `clearTranslations`, using i18n for library in `ng-packagr.`, and use of `$localize`: https://github.com/angular/angular/issues/37563

**Comment by rockument69** [comment]
PR [36924](https://github.com/angular/angular/pull/36924) (docs: Refactor-i18n-DOCS-758) closes this issue.
