### ISSUE TITLE
Get Heroes with HTTP Client section of Tour of Heroes tutorial (part 6) may not be correct

### ISSUE THREAD

**Issue by aikidave** [angular/angular#35783]
# 📚 Docs or angular.io bug report

### Description
In the Tour of Heroes tutorial, part 6, there is a section, **Get Heroes with HTTP Client**. In that section, we tell users to replace a function, getHeroes, to one that uses an observable. 

The text implies that, after making this change, the application will run correctly. However, this does not appear to be the case, as another method, getHero(), has not been updated yet. You are instructed to update this second method later in the tutorial.

Can we confirm that the app should still work, or if the instructions are incorrect? If the latter, we should make it clear that the application is broken until you fix the next section.

We could also confirm that the problem is between my chair and the keyboard. That's fair too.

### What's the affected URL?**
https://angular.io/tutorial/toh-pt6#get-heroes-with-httpclient

### Reproduction Steps**
1. Follow the tutorial instructions.
2. At the step outlined, check the app. You'll find it broken.

### Expected vs Actual Behavior**
The instructions imply that the application should still be functional.

## 📷Screenshot
N/A

**Comment by sonukapoor** [comment]
@aikidave, I can take a look at this.

**Comment by sonukapoor** [comment]
@aikidave I looked at the documentation and at the [stackblitz example](https://stackblitz.com/angular/egmelpdxren?file=src%2Fapp%2Fhero.service.ts). They both return an `Observable<Hero[]>` and should work. The stackblitz example works fine. I don't see anything wrong there.

**Comment by aikidave** [comment]
Thanks for looking into this, @sonukapoor! As I mentioned, the problem may have been between my chair and my keyboard--in other words, I typed something incorrectly! I couldn't figure out what though.

As you've verified that the tutorial is correct, I will close this.

**Comment by sonukapoor** [comment]
@aikidave I am more than happy to look at your code, to make sure that we didn't miss anything.

**Comment by aikidave** [comment]
That's really kind of you! At this point, though, I copied the code through and got it working. I'll probably run through the tutorial again soon though. It's good to continually try these tutorials to ensure they work as intended.
