### ISSUE TITLE
bootstrap disappeared from API docs

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#3578]
Hey @yjbanov can you look into why `bootstrap`  is no longer getting exported to dgeni? @mhevery thinks this is related to your refactoring change to split it out into a separate file.

**Comment by yjbanov** [comment]
Let's wait until dartdocs.org is green. The fix for #3466 includes a small cleanup for our exports that may affect dgeni as well.

**Comment by naomiblack** [comment]
Clarified the issue with Yegor. Will try to get this in for 35.

**Comment by yjbanov** [comment]
Fixed by 5f7d4faa8872f784f895248dcae795cdbaf58d8a
