### ISSUE TITLE
[Ivy] (Memory Leak) Component references not released inside destroyed template (e.g. ngFor)

### ISSUE THREAD

**Issue by Achilles1515** [angular/angular#35787]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core, I guess

### Is this a regression?

 This is a bug in Ivy and is not present in View Engine.
The title states "component references", but it may be more than that. The example below is specifically pertaining to a component instance.

### Description

In the demo below, an `*ngFor` is stamping out two templates containing a `TestComponent`. Click the button, which pops the last `ngForOf` item, destroying the second `TestComponent` instance.

Now, take a heap snapshot of "ng-run-preview.firebase.app".

----------------------------

With Ivy **enabled**:
![image](https://user-images.githubusercontent.com/23387905/75644962-38c7b400-5c12-11ea-8042-4921520234a4.png)
...**two** instances of `TabComponent` still remain in memory.

----------------------------

With Ivy **disabled** (so, using View Engine):
![image](https://user-images.githubusercontent.com/23387905/75644943-1e8dd600-5c12-11ea-8aa1-31803a49d611.png)
...**one** instance of `TabComponent` remains, which is expected behavior.

## 🔬 Minimal Reproduction

https://ng-run.com/edit/2Cixj2OgChnV6TMEA3ZJ?open=app%2Fapp.component.ts

**Comment by ChristopherKiss** [comment]
This looks like a duplicate or related to:

https://github.com/angular/angular/issues/35575
https://github.com/angular/angular/issues/35164 (Your own post?)
https://github.com/angular/angular/issues/34538
https://github.com/angular/angular/issues/29053 (Not Ivy specific?)

**Comment by mhevery** [comment]
I have tried to reproduce following your steps, but on my Chrome it gets correctly released. So without a repro which works I don't think I can do anything about it.

I suspect it may be due to different version of chrome? I am on `80.0.3987.122 (Official Build) (64-bit)`

**Comment by mhevery** [comment]
I think this may be related to https://jsfiddle.net/y9xrtzmb/6/ Can you verify that you can reproduce the issue even if the Chrome DevTools are closed or you click on some other button to clear it?

**Comment by Achilles1515** [comment]
@mhevery I am coming to the realization that the uBlock Origin extension is the culprit for holding a reference to the destroyed object.

![image](https://user-images.githubusercontent.com/23387905/76022202-aa468180-5ef4-11ea-90fd-9f850f327de0.png)

Disabling the extension releases the memory as expected.
Sorry for the false report - I'll close this issue.

I have no clue what is going on with the internals of uBlock Origin and why it is holding references to detached DOM nodes...and why this doesn't occur with View Engine. I wonder if something like what was stated in the other thread of setting `__ngContext__` to null on object destruction would help at all.
