### ISSUE TITLE
Angular Sourcecode build failure in Windows 10

### ISSUE THREAD

**Issue by MrJithil** [angular/angular#35785]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
all packages

### Is this a regression?
No

### Description
While I'm trying to build the angular source code from Windows 10 machine using the command 
`node ./scripts/build-packages-dist.js `, I'm getting following error.

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

INFO: Call stack for the definition of repository 'npm' which is a yarn_install (rule definition at C:/users/username/_bazel_username/idexbm2i/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:431:16):
 - C:/users/username/_bazel_username/idexbm2i/external/build_bazel_rules_nodejs/index.bzl:84:5
 - C:/users/username/_bazel_username/idexbm2i/external/build_bazel_rules_nodejs/index.bzl:84:5
 - D:/opensource/angular/WORKSPACE:48:1
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
        File "C:/users/username/_bazel_username/idexbm2i/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 427
                _symlink_node_modules(<1 more arguments>)
        File "C:/users/username/_bazel_username/idexbm2i/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 191, in _symlink_node_modules
                repository_ctx.symlink(<2 more arguments>)
java.io.IOException: Could not create symlink from D:/opensource/angular/node_modules to C:/users/username/_bazel_username/idexbm2i/external/npm/node_modules: Cannot create junction (name=C:\users\username\_bazel_username\idexbm2i\external\npm\node_modules, target=D:\opensource\angular\node_modules): a file or directory already exists at the junction's path

ERROR: no such package '@npm//': Traceback (most recent call last):
        File "C:/users/username/_bazel_username/idexbm2i/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 427
                _symlink_node_modules(<1 more arguments>)
        File "C:/users/username/_bazel_username/idexbm2i/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 191, in _symlink_node_modules
                repository_ctx.symlink(<2 more arguments>)
java.io.IOException: Could not create symlink from D:/opensource/angular/node_modules to C:/users/username/_bazel_username/idexbm2i/external/npm/node_modules: Cannot create junction (name=C:\users\username\_bazel_username\idexbm2i\external\npm\node_modules, target=D:\opensource\angular\node_modules): a file or directory already exists at the junction's path
child_process.js:669
    throw err;
    ^

Error: Command failed: yarn --cwd "D:\opensource\angular" --silent bazel info bazel-bin
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at exec (D:\opensource\angular\scripts\package-builder.js:106:18)
    at Object.<anonymous> (D:\opensource\angular\scripts\package-builder.js:32:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18) {
  status: 2,
  signal: null,
  output: [ null, <Buffer >, null ],
  pid: 3856,
  stdout: <Buffer >,
  stderr: null
}
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>master<code>

</code></pre>

**Anything else relevant?**

**Comment by MrJithil** [comment]
Any fix or help on the above will be apreciated.

**Comment by gkalpak** [comment]
I have never seen this error (I am on Windows 10 too) and I am not sure what the exact problem is (it seems to be something inside [bazelbuild/rules_nodejs][1]). But based on the error message, it might be that `rules_nodejs` is trying to create symlinks, for which you do not have sufficient permissions.

What I have done on my machine (and perhaps the reason I am not seeing thids error) is enabling Developer Mode, which allows creating symlinks without elevation: 
- https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10
- https://www.ghacks.net/2016/12/04/windows-10-creators-update-symlinks-without-elevation

cc @gregmagolan to confirm what is going on inside `rules_nodejs` and whether we need to handle it differently for Windows users or give a more informative error message.

[1]: https://github.com/bazelbuild/rules_nodejs

**Comment by spike-rabbit** [comment]
I was facing the same issue. It seems to be related to bazelbuild/rules_nodejs#1641.
When moving my files to C:\ it works.

**Comment by JayeshVyas** [comment]
I also worked on the windows 10 with Angular 8 but never face this issue. maybe it is something related to the permission or as mentioned in the error it may not be able to find out some modules.

try with some different names or with another user.

**Comment by MrJithil** [comment]
> I also worked on the windows 10 with Angular 8 but never face this issue. maybe it is something related to the permission or as mentioned in the error it may not be able to find out some modules.
> 
> try with some different names or with another user.

Trying with different user? Seems like a customer support agent comment on network issue.

**Comment by MrJithil** [comment]
> I was facing the same issue. It seems to be related to [bazelbuild/rules_nodejs#1641](https://github.com/bazelbuild/rules_nodejs/issues/1641).
> When moving my files to C:\ it works.

Works Well. And it's a known issue with the bazel rules, and they fixed it. May be we can expect it in the upcoming releases.
