### ISSUE TITLE
content-type changes to text/plain in production

### ISSUE THREAD

**Issue by aanand07** [angular/angular#35789]
I'm facing a weird issue due to httpclient, when i set some HttpHeaders(not content-type), content-type changes to text/plain in production build, while in local content-type is application/json. 
Due to this my server responds with Http error 415(unsupported media type) as it can only handle application/json requests, and furthermore, this issue isn't reproducible all the time.
My understanding is that content-type by default should always be application/json.

### Affected Package
"@angular/http": "^6.0.3",
"angular": "^1.6.9",
"@angular/common": "^6.0.3",

Not sure

## 🌍  Your Environment

Angular CLI: 6.0.8
Node: 10.15.3
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@angular/compiler-cli             7.2.15
@ngtools/webpack                  7.3.9
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.0.0
typescript                        3.1.6
webpack                           4.29.0-->

</code></pre>

**Anything else relevant?**
No

**Comment by petebacondarwin** [comment]
I see that you are running Angular v6. This is no longer supported. Also the `@angular/http` was deprecated in v5 and removed in v7. It is feasible that this is a bug that does not exist in the replacement which is `@angular/common/http`.

Can I ask that you try updating to a newer version of Angular?  Version 7 is the oldest version that we are supporting - and support for that runs out in April. I would update to version 8, or even 9 if possible.

Even if you only update as a test you will be able to see whether the bug still exists in `@angular/common/http` in the latest versions. If it does then we can look into a bug fix for it.

**Comment by aanand07** [comment]
Thanks @petebacondarwin , I'll suggest updating to angular 8 to my lead, and yes I've removed @angular/http from package.json  Will check again in the prod and see if the issue persists.
Closing this for now.
