### ISSUE TITLE
i18n docs include multiple build tutorial link that is deprecated

### ISSUE THREAD

**Issue by santhony7** [angular/angular#35797]
# 📚 Docs or angular.io bug report

### Description

 The content on the bottom of the page is really no longer helpful. The article by Philippe Martin used old APIs that are now deprecated. It would be great if we could get an updated method for deploying multiple languages using new APIs.

### What's the affected URL?**
 https://angular.io/guide/i18n

**Comment by gkalpak** [comment]
Thx, @santhony7 :+1:

Merged this into #35776, because it is essentially the same issue (i.e. needs to be addressed together): https://github.com/angular/angular/issues/35776#issuecomment-593621870
(Let's track the problem there.)
