### ISSUE TITLE
error typeerror: cannot convert undefined or null to object angular

### ISSUE THREAD

**Issue by Deepak2985** [angular/angular#35791]
While giving the production build in angular 9 I am getting the below error.

![image](https://user-images.githubusercontent.com/36476799/75666848-8e48a300-5c9c-11ea-83bc-371ad864c06b.png)

**Comment by petebacondarwin** [comment]
@Deepak2985 - this does report not provide us with enough information to diagnose your problem. Please can you try:

* to debug into this error and find out where in the original source the error is being thrown
* recreate the problem in a small project that you can share with us

**Comment by AndrewKushnir** [comment]
Hi @Deepak2985, as @petebacondarwin mentioned, there is not enough information for us to perform an investigation, so I'll close this ticket. Feel free to open a new one and follow instructions in the issue template. It'd be helpful to have a reproduction (minimum possible setup, in a form of a Github repo) of the issue that you are observing. Thank you.
