### ISSUE TITLE
Ability to manually trigger reload of a routed component on parameter change

### ISSUE THREAD

**Issue by mujiak** [angular/angular#35794]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/router

### Description
 
On route parameter change angular by default reuse the routed component, which is nice.
but sometimes on specific routes we don't what to reuse the component, instead reloading it will be a lot easier option. 

### Describe the solution you'd like

So router navigation methods should provide the option to reload the same component , instead of reusing it.

### Describe alternatives you've considered

`NavigationExtras` should accept a property  like `onSameUrlNavigation : 'reload'` to indicate reload of current route if parameters changes.

which can be used like
`this.router.navigatebyUrl('/customer/1', { onSameUrlNavigation: 'reload' })`

**Comment by djleonskennedy** [comment]
@mujahid-akbar agree with author, this api could be more easy to use than `ReuseStrategy`

**Comment by liesahead** [comment]
Currently we found 2 hacky options to avoid this:

Option1: renavigate to some route with `skipLocationChange: true` and then navigate back to the same route.
Option2: Custom route reuse strategy

First one is not good at all, second one is not useful when it's needed only for ONE use-case..

**Comment by atscott** [comment]
This is trivial to implement and fits well into already existing router concepts (i.e. #23152). That said, I'd like to understand the use-cases before adding this to the backlog. What situations would you want to change `onSameUrlNavigation` for a single navigation?
