### ISSUE TITLE
Test for Undefined on a field defined in Typescript

### ISSUE THREAD

**Issue by MattDWhittle** [angular/angular#35806]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/compiler

### Description
 A clear and concise description of the problem or missing capability...
Hi! The current way I have to test for an undefined field for a field defined in a class seems clunky.

Example:
declare class HasAThing {
  thing: string;
}

    let thisHasAThing: HasAThing;

    try {
      if (thisHasAThing.thing) {
        b = 1;
      }
    } catch (e) {
      if (e instanceof TypeError) {
        b = 2;
      } else {
        throw e; 
      }
    }

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
It would be nice if I could test for undefined in the same manner I test other variables, such as

    if (thisHasAThing.thing) {
      b = 1;
    } else {
      b = 2;
    }

(This throws a TypeError currently)

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by pkozlowski-opensource** [comment]
@MattDWhittle I'm sorry but it is not very clear what you mean by "This throws a TypeError currently". I'm _assuming_ that you are trying to do an equivalent of:

```typescript
let thisHasAThing;

// somewhere later
thisHasAThing.thing; 
```

The `thisHasAThing.thing` will obviously fail, during runtime with a "TypeError: Cannot read property 'thing' of undefined" and the error says it all :-)

I'm not sure what is your exact scenario but if you want to access properties of something that is potentially undefined, you could do , in Typescript: `b = thisHasAThing?.thing ? 1 : 2;`: https://ng-run.com/edit/XDlVgo9KSQMs5AKAPNYB

I'm going to close this one as there is nothing Angular specific here.
