### ISSUE TITLE
[Question] Using EventEmitter to manipulate data and return an Observable.

### ISSUE THREAD

**Issue by ericmdantas** [angular/angular#3580]
I have asked this in the gitter room, but there were no responses, so I thought I might ask this here.

It looks like if we want to work with Rx.Observables, we'll have to use the EventEmitter class.

I was wondering how to do the following:

- My component calls a service passing something by parameter;
- My service modifies the parameter;
- My service returns an Observables so that my Component can observe and subscribe to it;

If I am using Rx.Observable (by importing it directly - ```import * as Rx from 'rx'```), I can do the following:
```ts
// MyService

export class MyService {
    static doSomething(something: Object):Rx.Observable {
          return Rx.Observable.create(o => {
                  something.createdAt = Date.now();
                  o.onNext(something);
                  o.onCompleted();
          })
    }
}
```

And then in my component:

```ts
// MyComponent

class MyComponent {
     doSomethingHandler(something:Object):void {
           MyService.doSomething(something).subscribe(info => console.log(info));
     } 
}
```

So, that'd work.

But how to do it with the EventEmitter wrapper? 

I saw it returns a ```Subject``` instead of an ```Observable```, and it looks like I'd have to pass callbacks left and right to make it work - but I'd like to have the logic separated - having the component to only call the service, and this one would do the heavy work, returning something already manipulated to the component.

**Comment by ericmartinezr** [comment]
You have full access to `Rx.Subject` with the `toRx()` method, you can customize it as you want using [Rx.Subject.create](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/subject.md#rxsubjectcreateobserver-observable). What I did was to use directy Rx classes instead of EventEmitter.

**Comment by ericmdantas** [comment]
@ericmartinezr thanks for the reply.

The thing is: ```toRx()``` gives me an instance of ```Rx.Subject``` which will work in a diferent way than ```Rx.Observable```. With the latest, I can manipulate the input and then output the result as an ```Observable```.

With ```Rx.Subject``` - I don't know if that's possible - manipulating the input and returning an ```Observable```.

By the way, even ```Rx.Subject.create``` won't give me something to subscribe.

**Comment by woppa684** [comment]
EventEmitter's toRx() method will return an Observable (not a Subject), see the definition of EventEmitter:

```typescript
class EventEmitter extends Observable {
    observer(generator: any): Rx.IDisposable;
    toRx(): Rx.Observable<any>;
    next(value: any): void;
    throw(error: any): void;
    return(value?: any): void;
}
```

**Comment by ericmartinezr** [comment]
Hey @ericmdantas yes, you are right. In fact, you couldn't use `Rx.Subject.create`. If you try it you'll see that something super simple as this will fail with `create() is not a function...`, my bad there...

```Javascript
evt = new EventEmitter();
evt.toRx().create(..., ...);
```

So I say that EventEmitter does its job, and if you want something more complex use Observables directly. Just keep it simple.

@woppa684 

In fact returns a Rx.Subject, see https://github.com/angular/angular/blob/master/modules/angular2/src/facade/async.ts

```Javascript
export class EventEmitter extends Observable {
  _subject: Rx.Subject<any>;
// ...
// Initialization in constructor
if (Rx.hasOwnProperty('default')) {
      this._subject = new (<any>Rx).default.Rx.Subject();
      //...
    } else {
      this._subject = new Rx.Subject<any>();
      //...
    }
//...
toRx(): Rx.Observable<any> { return this._subject; }
```

**Comment by woppa684** [comment]
Yes, but the return type is 'Rx.Observable<any>' right? So it DOES have a subscribe method .... because Subject<T> extends ISubject<T> which in turn extends Observable<T>. All I'm saying is that Rx.Subject is a sub class of Rx.Observable...

**Comment by ericmartinezr** [comment]
Oh, yeah, it is. My acknowledge of [Hot and cold Observables](http://www.introtorx.com/content/v1.0.10621.0/14_HotAndColdObservables.html) is not that deep, but I think I get the idea. Rx.Subject is a hot observable and Rx.Observable is a cold one. So there's a difference in how you use it whether Rx.Subject is a subclass or not.

Taking @ericmdantas example

*Changed it a little bit so it doesn't create an Observable everytime*
```Javascript
export class MyService {
    constructor() {
          this._obs = function(something) {
                 return Rx.Observable.create(o => {
                      something.createdAt = Date.now();
                      o.onNext(something);
                      o.onCompleted();
                 }); 
          };
    }

    getObs(something) {
        return this._obs(something);
    }
}

// .. Component
class MyComponent {
     constructor(svc: MyService) {
           svc.getObs(something).subscribe(info => console.log(info)); // Subscriber 1
           svc.getObs(something1).subscribe(info => console.log(info)); // Subscriber 2
           svc.getObs(something2).subscribe(info => console.log(info)); // Subscriber 3
           svc.getObs(something3).subscribe(info => console.log(info)); // Subscriber etc...

          // At this point all subscribers have reacted
     } 
}
```
With Rx.Subject you would have to do something like this

```Javascript
export class MyService {

    doSomething(something) {
         // Do something with something
     } 

    // Returns a new Rx.Subject so calling 'onCompleted' won't affect other subscribers
    getSubj() {
        return new Rx.Subject();
    }
}

// Component
class MyComponent {
     constructor(svc: MyService) {
           let sub = svc.getSubj();
           sub.subscribe(info => svc.doSomething(info)); // Subscriber 1
           sub.onNext(something1);
           sub.onCompleted(); // Dispose

           let sub2 = svc.getSubj();
           sub2.subscribe(info => svc.doSomething(info)); // Subscriber 2
           sub2.onNext(something2);
           sub2.onCompleted(); // Dispose

           let sub3 = svc.getSubj();
           sub3.subscribe(info => svc.doSomething(info)); // Subscriber 3
           sub3.onNext(something3);
           sub3.onCompleted(); // Dispose

           let sub4 = svc.getSubj();
           sub4.subscribe(info => svc.doSomething(info));  // Subscriber etc...
           sub4.onNext(something4);
           sub4.onCompleted(); // Dispose
     } 
}
```

For what I understood from his example what he needs is a Rx.Observable (Cold one). Rx.Subject would make it much complicated.

If I'm wrong please correct me (to anyone who understands Observables better than me)

**Comment by ericmdantas** [comment]
@woppa684, thanks for the reply.

But in this case, subject [is an instance of Rx.Subject](https://github.com/angular/angular/blob/5a405011de532480bcd2da8ab40a36955346d45d/modules/angular2/src/facade/async.ts#L107-L122) ([which inherits from both Observables and Observers](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/subjects.md#using-subjects)).

Bottom line is: 
- I want to separate the logic in my app. 
- I'd like to have the service only receiving values, doing something with it, and giving me something back - so I can subscribe and do something else whenever that given value is ready.
- I'd like to know if going with EventEmitter is the right way, or I should be using Rx.Observables directly, as @ericmartinezr pointed out.

I guess the idea is pretty much the same of the Http class. I pass an object to it, it'll do whatever it has to do with it, and lets me subscribe to the result of whatever was done.

**Comment by ericmdantas** [comment]
@ericmartinezr thank you for putting that together, and, yes - for this example I need a cold observable. But I needed to implement a hot a few days ago and I had no idea how to, I'll give it a try with EventEmitter's wraper then. :smile:

**Comment by woppa684** [comment]
So, to get things straight, this is NOT what you mean?

```typescript
import {Component, View, bootstrap, EventEmitter} from 'angular2/angular2'


class MyService {
    static doSomething(something: any): EventEmitter {
        var e = new EventEmitter();

        window.setTimeout(() => {
            something.createdAt = Date.now();
            e.next(something);
        }, 2000);

        return e;
    }
}

@Component({
    selector: 'main'
})
@View({
    template: ``
})
class Main {
    constructor() {
        MyService.doSomething({}).toRx().subscribe(info => console.log(info));
    }
}

bootstrap(Main, [MyService]);
```

**Comment by ericmdantas** [comment]
@woppa684 I guess that'd do the trick. I can't test it right now, but I'll try it later today and I'll let you know.

Thank you guys for the help!

**Comment by ericmdantas** [comment]
Alright so what @woppa684 suggested worked! 

I'll try to implement a MessageBus type of service with the hot observable as @ericmartinezr suggested.

Thank you again, guys!

**Comment by TiagoBraga39** [comment]
Hi all!
Can you spot what I am doing wrong?
My service is supposed to save a list of categories, which it does. But the problem is in that case I can't trigger the subscribe from my component.

Main Component:
```javascript
@ComponentMetadata({
    selector: 'main-cmp',
    bindings: [ Service ]
})
@ViewMetadata({ ... })
])
export class MainCmp { 
    constructor(router : Router, service : Service) {
        this.router = router;
        this.service = service;
    }
    onInit() {
        this.service.getMenu().subscribe(
            res => { this.categories = res; },
            error => { debugger },
            () => { }
        );
    }
}
```

---

Other Component
```javascript
@ComponentMetadata({
    selector: 'other-cmp',
    bindings: [ Service ]
})
@ViewMetadata({ ... })
])
export class MainCmp { 
    constructor(service : Service) {
        this.service = service;
    }
    onInit() {
        this.service.getMenu().subscribe(
            res => { debugger; this.categories = res; },
            error => { debugger; },
            () => { debugger; }
        );
    }
}
```

---

Service:
```javascript
 getMenu(pathToXml : string, pathToApplication : string) : Rx.Observable<any> {
        //var subject = new Rx.Subject();
        var emitter = new EventEmitter();
        if(this.categories.length > 0) {
            //subject.onNext(this.categories);
            emitter.next(this.categories);
        }
        else {
            this.getMenuFromXml(pathToXml).subscribe(
                res => {
                    var json = x2js.xml_str2json(res.text()).Application.Categories.Category_asArray;
                    this.categories = this.buildCategories(json, pathToApplication);
                    //subject.onNext(this.categories);
                    emitter.next(this.categories);
                },
                error => { },
                () => { }
            );
        }
        //return subject;
        return emitter.toRx();
    }
```

---

As you may see, I inject the service into the Main component, and the Other component has visibility over the Main component's bindings, due to 'bindings' property. (Main component is also a router, but that is not important here, but still that's how the Other component has visibility over the Service class). This way I have the same instance for both of them.

Why? Because I need to get a menu from a XML, which I don't want to load a second time (it's actually more than that).

<h3>Now for the issue:</h3>
While on the Other Component, that little code:
```javascript
if(this.categories.length > 0) {
    //subject.onNext(this.categories);
    emitter.next(this.categories);
}
```
Actually it triggers, <b>but I can't (somehow) subscribe to this when returning these "cached" array</b> (I confirmed with debugger on try catch finally clause on the Other Component.)

Any ideas what could be happening?

Thank you all!

Best regards,
Tiago Braga

**Comment by ericmdantas** [comment]
@TiagoBraga39 I guess it's because you're calling ```.next``` before there's anyone hearing it.

Try doing the following: 

```ts
 getMenu() : Rx.Observable<any> {
        //var subject = new Rx.Subject();
        var emitter = new EventEmitter();
        if(this.categories.length > 0) {
            //subject.onNext(this.categories);
            setTimeout(() => emitter.next(this.categories));
        }
        else {
            this.getMenuFromXml().subscribe(
                res => {
                    this.categories = res.json();
                    //subject.onNext(this.categories);
                    setTimeout(() => emitter.next(this.categories));
                },
                error => { },
                () => { }
            );
        }
        //return subject;
        return emitter.toRx();
    }
```

**Comment by TiagoBraga39** [comment]
@ericmdantas Thank you!

Now I understood and makes sense :)
But I don't need the 2nd setTimeout, since it is nested in a subscribe, so there's anyone hearing it. :)

Best regards,
Tiago Braga

**Comment by ericmdantas** [comment]
@TiagoBraga39 Glad it worked :smile:

**Comment by danicomas** [comment]
I have this:

```js
class MyAppComponent {
text: string;
constructor() {
this.text = "a";
this.emit().subscribe(response => {
	console.log(response);
	//Fist time text ="open"
	//The second time with Open1 is not fired. What happen?
});
this.text = "Open"; //only this causes the subscribe fire
//this.text = "Open1"; //no fire
setTimeout(() => {
	this.text = "Open1" //no fire
});
}
emit() : Rx.Observable<any> {
	var emitter = new EventEmitter();
	    var emitter = new EventEmitter();
	    setTimeout(() => emitter.next(this.text));

	    return emitter.toRx();
	}
}
```
@TiagoBraga39 @pkozlowski-opensource Why event emitter is not firing the second time?

**Comment by TiagoBraga39** [comment]
1. Don't forget subscribe is not a synchronous call. So you don't see console.log("a") because this.text = "Open" actually happens first.
2. setTimeout for itself does not make it trigger since you are only subscribing to that emit() function.

This is basically what you need:
```javascript
// This funtion is an observable
emit() : Rx.Observabe<any> {
    var emitter = new EventEmitter();
    emitterr.next(this.text); // I only use setTimeout here because of that thread I refered (I don't have it with me now).
    return emitter.toRx();
}
```
// Now you can do:
```javascript
this.emit.().subscribe(...)
```

<b>But I am not sure if you can just watch a variable</b>. I never tried that, since i don't have that use case.
But if that variable is a property of your component, you can use the onChanges lifecycle event:

```javascript
onChanges(changes) {
   // ..
}
```

Does this help?

**Comment by ericmdantas** [comment]
Alright, I'm reopening this because we've got a new problem with EventEmitters now. Either that or I'm missing something.

Here is the plnkr with the situation: http://plnkr.co/edit/9w5nzAuMkE1BHoTo2GxN?p=preview

Basically, we can't return an observable anymore when using `toRx()` see the change [here](https://github.com/angular/angular/commit/16bf335a4ae74155fef0d79f058dca0cf4d35fe4#diff-8be0a3d40b54a6a790fee3c42157b18dL141). 

We, can return an observable with `_subject`, though. But just doesn't feel right. 

Does anyone have any word on it? Should I still be using EventEmitter for that kind of situation or just switch to Rx's Observables?

Here's the full code:

```js
import {Component, View, EventEmitter, OnInit, bootstrap} from 'angular2/angular2';

class SomethingService {
  _ee: EventEmitter = new EventEmitter();
  
  fireStuff() {
    setTimeout(() => {
      this._ee.next('fire!');
    }, 1000);
    
    //return this._ee.toRx(); - doesn't work anymore
    return this._ee._subject; // silly work around
  }
}

@Component({
    selector: 'hello',
    viewBindings: [SomethingService]
})
@View({
	template: `
	  <h3>hello - uncomment line 11 and comment line 12 to see the error</h3>
	  <button type="button"
            (click)="fire()">btn</button>
    <pre [text-content]="f"></pre>
	`
})
export class Hello implements OnInit {
  f: string;
  
  constructor(private _ss: SomethingService) {
    
  }
  
  onInit() {
    console.log('hello init');
  }
  
  fire() {
    this.f = "loading";
    
    this._ss
        .fireStuff()
        .subscribe((info) => {
          this.f = info;
        });
  }
}


bootstrap(Hello);
```

cc: @ericmartinezr @robwormald @pkozlowski-opensource

**Comment by ericmdantas** [comment]
Closing. Opened a new one.
