### ISSUE TITLE
Angular Library Test Error: Unexpected value 'BrowserDynamicTestingModule' imported by the module 'DynamicTestModule'.

### ISSUE THREAD

**Issue by tgrux** [angular/angular#35805]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core/testing

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8 latest

### Description

Running unit tests for an angular library throws the following error:
```bash
Unexpected value 'BrowserDynamicTestingModule' imported by the module 'DynamicTestModule'. Please add an @NgModule annotation.
```

## 🔬 Minimal Reproduction

Simply run the unit tests for an angular library.

## 🔥 Exception or Error
<pre>Unexpected value 'BrowserDynamicTestingModule' imported by the module 'DynamicTestModule'. Please add an @NgModule annotation.<code>

## 🌍  Your Environment

**Angular Version:**

<pre>
Angular CLI: 9.0.4
Node: 10.15.3
OS: darwin x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.4
@angular-devkit/build-angular      0.900.4
@angular-devkit/build-ng-packagr   0.900.4
@angular-devkit/build-optimizer    0.900.4
@angular-devkit/build-webpack      0.900.4
@angular-devkit/core               9.0.4
@angular-devkit/schematics         9.0.4
@ngtools/webpack                   9.0.4
@schematics/angular                9.0.4
@schematics/update                 0.900.4
ng-packagr                         9.0.2
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
<code>

**Anything else relevant?**

**Comment by tgrux** [comment]
This seems to have been an issue related to node_modules not being wiped out correctly.  Once I reinstalled everything I'm able to run tests successfully.

**Comment by tgrux** [comment]
I lied, this is still happening.  I was able to get it working briefly, but upon reinstalling node modules the issue is back.  Seems to be related to this ticket: https://github.com/angular/angular/issues/32431 but it unclear if it is the same issue.

**Comment by saltcreek-alex** [comment]
I encountered a similar issue. 
Adding ngcc as postinstall script to my `package.json` seems to fix the issue, now the tests for the library are running as expected:

`{
  "scripts": {
    "postinstall": "ngcc"
  }
}`

I am not entirely sure why this is necessary, the explanation in the [docs](https://next.angular.io/guide/ivy#maintaining-library-compatibility) is not very clear to me:

> In version 9, the server builder which is used for App shell and Angular Universal has the bundleDependencies option enabled by default. If you opt-out of bundling dependencies you will need to run the standalone Angular compatibility compiler (ngcc). This is needed because otherwise Node will be unable to resolve the Ivy version of the packages.

I hope this helps. If someone knows, why this is necessary, I would appreciate a more detailed explanation.

**Comment by tgrux** [comment]
Thanks @saltcreek-alex - that helped.
