### ISSUE TITLE
Creating a module with --route & --routing duplicates code

### ISSUE THREAD

**Issue by Maryannah** [angular/angular#35818]
# 🐞 bug report

### Affected Package

 The issue is caused by the schematics that create a module

### Is this a regression?

 I do not know, I have never tried it before

### Description

 when running a command to create a module with --route & --routing, the code gets duplicated : there are routes in the *.module.ts along with the *-routing.module.ts

## 🔬 Minimal Reproduction

 I didn't manage to create a stackblitz, but here are the commands to reproduce it locally.

```bash
npx create-nx-workspace@latest workspace
cd workspace
ng add @nrwl/angular --defaults
ng g @nrwl/angular:application app --style scss --routing true --prefix app
ng g m home --route home --module app.module.ts --routing true --project app
```
## 🌍  Your Environment

**Angular Version:**
<pre><code>
    "@angular/animations": "^9.0.0",
    "@angular/cdk": "^9.0.0",
    "@angular/common": "^9.0.0",
    "@angular/compiler": "^9.0.0",
    "@angular/core": "^9.0.0",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "^9.0.0",
    "@angular/material": "^9.0.0",
    "@angular/platform-browser": "^9.0.0",
    "@angular/platform-browser-dynamic": "^9.0.0",
    "@angular/router": "^9.0.0",
    "@nrwl/angular": "^9.0.4",

</code></pre>

**Anything else relevant?**

I do not know if this is wanted or not, and I do not know which one is the best practice (the one to keep).

**Comment by Maryannah** [comment]
After testing a bit more, removing the `--routing` creates an invalid module : 

```typescript
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Routes, RouterModule } from '@angular/router';

import { LayoutRoutingModule } from './layout-routing.module';
import { LayoutComponent } from './layout.component';

const routes: Routes = [
  { path: '', component: LayoutComponent }
];

@NgModule({
  declarations: [LayoutComponent],
  imports: [
    CommonModule,
    LayoutRoutingModule,
    RouterModule.forChild(routes);
  ]
})
export class LayoutModule { }
```

You can see that there is a semi-colon right in the imports, and that the routing module is imported even though it wasn't created.

**Comment by Maryannah** [comment]
Another things, components that are created with this command do not follow the schematics configuration from the `angular.json` file.

**Comment by santoshyadav198613** [comment]
This needs to be raised in angular/cli repo, Can you close and raise one in correct repo, I will look into it. @alan-agius4 I will look into it.

**Comment by Maryannah** [comment]
@santoshyadav198613 I have created the issue in the CLI repo : 

https://github.com/angular/angular-cli/issues/17139
