### ISSUE TITLE
issue with TypeChecking in template in Angular 9 (with Ivy)

### ISSUE THREAD

**Issue by zero-1** [angular/angular#35811]
To be honest, I am not sure if this is an issue or I might just be using the thing wrong.... but the following code works in Angular 8 ... and in Angular 9 with Ivy disabled.

**In the .ts file.. we have something like this ...** 

```
export interface IA {
  name: string;
  age: number
}

export interface IB {
  fullname: string;
  halflife: number
}

someObj: IA | IB;
.
.
this.someObj = this.anObjectofTypeIA;
```

**in the template ...** 
`
{{ someObj?.name }}
`

Stackblitz..
https://stackblitz.com/edit/angular-hw62bd

This does not work in Angular 9 with Ivy.
Error:: Property 'name' does not exist on type 'IA | IB'.

There is some documentation on this at https://angular.io/guide/template-typecheck

But such a scenario isn't really covered and I couldn't find any best practices regarding the same.

**Comment by zero-1** [comment]
@ericmartinezr can you please provide some reasoning for the thumbs down...

**Comment by ChristopherKiss** [comment]
Your code doesn't compile under Typescript using the same semantics as Angular. I'd argue that this working in previous versions of Angular is a bug which is now fixed.

https://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgSQEE4BvAKDjiUwFtgAuOAZximQHMBuCuTdhqgFcaAIzRkAvmTKhIsRCjRZcBAEKke6QQBtt1OoxZskXHgAtM29NoToBSYWKiTpWpNhgIISONgg1IJGAUAAoASkYiOAAfNVI4HihgGEEoHxIqWgEAcmyAGl5+RgBGOAleJgJCbikyNw8vH1QA7UxUcPieADdMKDgIEQArOABeX39A4Jhw7koBwYA6fWAXIA

I've used a functions to mimic what the component side sees vs template side sees. As you can see the template doesn't know about the implementation details of your component, it doesn't know that you've only assigned IA, and not IB. It's only reporting what it knows.

I'm not sure why you would be expecting this to work.

**Comment by zero-1** [comment]
Agreed. But it seems like the only way to fix this is to reduce the strictness in the type checking.

**Comment by ChristopherKiss** [comment]
Have you tried playing with the strictness options in the documentation you linked? I can't recall if Ivy changed the defaults, but maybe you can return the strictness to what you want without Ivy.

**Comment by petebacondarwin** [comment]
Angular is now much more strict with its type checking in templates. As @ChristopherKiss points out `someObj.name` is not a valid expression because `someObj` may not have the `name` property.

One approach to fixing this is to use the `$any(...)` function to cast the `someObj` to `any` and then access its properties without type checking constraints. For example: https://stackblitz.com/edit/angular-zo3gmx?file=src/app/app.component.html

See https://angular.io/guide/template-typecheck#disabling-type-checking-using-any for more information.

**Comment by pkozlowski-opensource** [comment]
Agree with @petebacondarwin - in my mind this is pure TS / type-checking problem - the same error would be reported without any Angular involvement, see [example](https://www.typescriptlang.org/play/?ssl=16&ssc=10&pln=16&pc=25#code/JYOwLgpgTgZghgYwgAgJIEFkG8BQzkhwC2EAXMgM5hSgDmA3HsnLWQQK5EBG0OAvjhyhIsRClQAhbExjsANnMIlyVGiAZMAFnDkw5wGGxCceUfoIQB7EFUqWSAeS4ArchmQAfNFIC80-PhKbADkAGKWlsEANEz4LGwAjACs5jiyIAhgwNbIrGAUAKogwFnWACoAngAOEAAUcFC0bphekgCU-gFWNpZyEAB0cpa0tRT2EE7O-UFtjAHI3WN9g8Oj45P9sgozjAI4QA).
