### ISSUE TITLE
ang9 getLocaleDateFormat returns wrong format

### ISSUE THREAD

**Issue by ydg2018** [angular/angular#35821]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ^8.0.0

### Description

 When using getLocaleDateFormate to retrieve the dateformat for locale nl-NL with FormatWidth.Short the return value in previous versions was dd-MM-yy, but in 9.x.x this has been changed to dd-MM-y.
When using this new format in the DatePipe transform the return value is that of yyyy and not yy, which is not expected with `FormatWidth.Short`

## 🔬 Minimal Reproduction

anuglar 9 with the issue:
https://stackblitz.com/edit/angular-aqsjyz

angular 8 without the issue:
https://stackblitz.com/edit/angular-qyhldh

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.4
@angular-devkit/build-angular      0.900.4
@angular-devkit/build-ng-packagr   0.900.4
@angular-devkit/build-optimizer    0.802.2
@angular-devkit/build-webpack      0.900.4
@angular-devkit/core               9.0.4
@angular-devkit/schematics         9.0.4
@ngtools/webpack                   9.0.4
@schematics/angular                9.0.4
@schematics/update                 0.900.4
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Comment by petebacondarwin** [comment]
The locale data in Angular is retrieved directly from the CLDR project (http://cldr.unicode.org/index/downloads/cldr-36).

The change you are seeing resulted from us updating to CLDR v36.0.0 in this commit https://github.com/angular/angular/commit/c77faf566e01e76c7f3488265a84d3029d5cf8cc#diff-bbb5df62624fc33b57414349f599db3f. (If you wait a bit it will scroll down to the `nl.ts` file where you can see the change).

If you believe this is incorrect then you should create a ticket on their tracker: https://unicode-org.atlassian.net/projects/CLDR/issues?.  You can see the original ticket that caused this change here https://unicode-org.atlassian.net/browse/CLDR-11156

**Comment by ydg2018** [comment]
thanks for the fast response and links, guess it does work as expected and i just need to change my code a bit to get what we want.
