### ISSUE TITLE
Angular 9 Location back() issue

### ISSUE THREAD

**Issue by NiallKelly84** [angular/angular#35828]
# 🐞 bug report

### Affected Package
@angular/common

### Is this a regression?
Yes - worked in angular 8

### Description
Angular's location.back() method is updating the url when called but isn't triggering the matching component in the app-routing.module to render.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
