### ISSUE TITLE
Xliff1TranslationParser does not handle multiple <file> elements

### ISSUE THREAD

**Issue by kamilchlebek** [angular/angular#35839]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/localize

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular v8

### Description

https://github.com/angular/angular/blob/c7d0567d37f0590108d2f89626b0f7215d3b3adb/packages/localize/src/tools/src/translate/translation_files/translation_parsers/xliff1_translation_parser.ts#L56-L59

Xliff1TranslationParser assumes there's only one `<file>` element in `.xlf` file. When there's more of them, the `this.bundle` is overridden. 

Usually it's true for extracted files, but somehow in our app we managed to generate file with few `<file>` attributes (it may be related to xliffmerge, but happened only for one language so far).

However while using angular 8 it used to work without any issues. While building the app using angular 9 we get warnings: `No translation found for "<<id>>" ("<<msg>>")`. Resulting in missing translations.

Would be good if Angular 9 either support multiple `<files>` or throw an exception so we can see the cause easily.

## 🔬 Minimal Reproduction

https://github.com/kamilchlebek/angular-xliff-issue

Steps:
1. `ng build --localize`

## 🔥 Exception or Error
<pre><code>No translation found for "5085648050787544850" ("child works!").
...
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 9.0.4
Node: 10.16.0
OS: linux x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.4
@angular-devkit/build-angular     0.900.4
@angular-devkit/build-optimizer   0.900.4
@angular-devkit/build-webpack     0.900.4
@angular-devkit/core              9.0.4
@angular-devkit/schematics        9.0.4
@ngtools/webpack                  9.0.4
@schematics/angular               9.0.4
@schematics/update                0.900.4
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by petebacondarwin** [comment]
Thanks for this report. I wonder what the convention should be when loading multiple files in a single bundle...
Should we just merge all the translations together?

**Comment by kamilchlebek** [comment]
Since all these additional elements are inside the same `xlf` file, I'd merge them together. I haven't noticed any missing translations while using angular v8, so it probably worked this way.

**Comment by petebacondarwin** [comment]
The concern I have is that each `<file>` element can actually target a different language... so we might need to be a bit careful about merging... I need to look into what ViewEngine was doing in this case.

**Comment by petebacondarwin** [comment]
Should be fixed by https://github.com/angular/angular/pull/35936
