### ISSUE TITLE
Interpolation expression not recognized in host attributes / properties

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#3583]
Given:

```java
@Directive({selector: '[with-host]', host: {'title': '{{exp}}'}})
class WithHost {
  constructor() {
    this.exp = 'foo';
  } 
}
```

I would expect the host element to have `title="foo"` but it ends up being `title="{{exp}}"`, so interpolation expression are not recognized / taken into account. I would expect them to be processed as in regular templates (after all we are using the same syntax as in templates....)

Plunker with reproduce scenario: http://plnkr.co/edit/GcofUFX3LmqbOUNx8EjL?p=preview

**Comment by pkozlowski-opensource** [comment]
This is due to the fact that we've got duplicated logic in https://github.com/angular/angular/blob/77d366843268d7ea728901b568529fe292711d71/modules/angular2/src/render/dom/compiler/property_binding_parser.ts#L20 and https://github.com/angular/angular/blob/77d366843268d7ea728901b568529fe292711d71/modules/angular2/src/render/api.ts#L161

**Comment by mhevery** [comment]
I think these are meant for properties and no interpolation. Working as intended.
