### ISSUE TITLE
Module '"../../../../@bazel/typescript/internal/tsc_wrapped/plugin_api"' has no exported member 'TscPlugin'

### ISSUE THREAD

**Issue by vladimiry** [angular/angular#35855]
ERROR in node_modules/@angular/compiler-cli/src/ngtsc/tsc_plugin.d.ts:9:30 - error TS2305: Module '"../../../../@bazel/typescript/internal/tsc_wrapped/plugin_api"' has no exported member 'TscPlugin'.

9 import { PluginCompilerHost, TscPlugin } from '@bazel/typescript/internal/tsc_wrapped/plugin_api';

Workaround (presumably): enable `skipLibCheck` TS compilation option.

The issue started to appear after @bazel/typescript 1.3.0 => 1.4.0 update.

**Comment by vladimiry** [comment]
By the way [I don't explicitly use any bazel capabilities](https://github.com/vladimiry/ElectronMail/blob/216e9add317a09f76dbc5ad3836beb0831d64720/webpack-configs/web/browser-window.ts#L64) but `AngularCompilerPlugin` still requires the `@bazel/typescript` to be installed. Can the `@bazel/typescript` be made optional dependency?

**Comment by alan-agius4** [comment]
This should be fixed by this PR https://github.com/angular/angular/pull/34792 in version 9.1.

**Comment by vladimiry** [comment]
Thanks @alan-agius4. Closing the issue as I see in the code that `@bazel/typescript` is no longer directly imported in node_modules/@angular/compiler-cli/src/ngtsc/tsc_plugin.d.ts since v9.1.

https://github.com/angular/angular/commit/3c69442dbd3494a5fa200235195abbb9cf8a4b9b#diff-5e2ac3a7ffa588b789820d310ce8b0ad

**Comment by vladimiry** [comment]
Can confirm recently released `AngularCompilerPlugin` v9.1.0 doesn't require `@bazel/typescript` anymore.
