### ISSUE TITLE
Some Of the documents can not be accessed

### ISSUE THREAD

**Issue by keshani** [angular/angular#35868]
# 📚 Docs or angular.io bug report

I can not access some of the documents. Below I have mentioned some of the links that I can  not access. The page shows the error msg saying "REQUEST FOR DOCUMENT FAILED.". I can access other documents in the document sections.

https://angular.io/guide/dynamic-form
https://angular.io/guide/reactive-forms

## 🔬 Minimal Reproduction
Just click above link

### What's the affected URL?**
https://angular.io/guide/dynamic-form
https://angular.io/guide/reactive-forms

<img width="1680" alt="Screen Shot 2020-03-05 at 1 53 54 PM" src="https://user-images.githubusercontent.com/1351497/75961953-f095e380-5ee8-11ea-93a1-a16cb426b3d0.png">

## 🔥 Exception or Error
"REQUEST FOR DOCUMENT FAILED.".

**Comment by gkalpak** [comment]
I can access the pages without issues. Can you try clearing your cache (e.g. in Chrome DevTools: `Application` > `Clear storage` > `Clear site data` (with all checkboxes checked)? Also, are you getting any errors in the console?

**Comment by keshani** [comment]
@gkalpak  it works for me. thank you
