### ISSUE TITLE
[Front for longstractor/server0.conn0.child1/longstractor82] i am getting this issue in mozilla 73.0

### ISSUE THREAD

**Issue by abhishheksaxena0691** [angular/angular#35869]
"Uncaught (in promise): TypeError: config is undefined
AuthenticationContext@https://bdaconfigurationtool.azurewebsites.net/vendor.js:84200:13
./node_modules/adal-angular/lib/adal.js/module.exports.inject@https://bdaconfigurationtool.azurewebsites.net/vendor.js:85993:20
MsAdalAngular6Service@https://bdaconfigurationtool.azurewebsites.net/vendor.js:86437:83
MsAdalAngular6Service_Factory@https://bdaconfigurationtool.azurewebsites.net/vendor.js:86626:196
_callFactory@https://bdaconfigurationtool.azurewebsites.net/vendor.js:60957:20
_createProviderInstance@https://bdaconfigurationtool.azurewebsites.net/vendor.js:60915:26
resolveNgModuleDep@https://bdaconfigurationtool.azurewebsites.net/vendor.js:60890:17
_createClass@https://bdaconfigurationtool.azurewebsites.net/vendor.js:60942:68
_createProviderInstance@https://bdaconfigurationtool.azurewebsites.net/vendor.js:60912:26
resolveNgModuleDep@https://bdaconfigurationtool.azurewebsites.net/vendor.js:60876:21
./node_modules/@angular/core/fesm5/core.js/NgModuleRef_.prototype.get@https://bdaconfigurationtool.azurewebsites.net/vendor.js:61584:16
getToken@https://bdaconfigurationtool.azurewebsites.net/vendor.js:79448:21
runCanActivate/canActivateObservables</<@https://bdaconfigurationtool.azurewebsites.net/vendor.js:79677:33
defer/<@https://bdaconfigurationtool.azurewebsites.net/vendor.js:88927:21
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype._trySubscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87266:25
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87252:22
./node_modules/rxjs/_esm5/internal/operators/take.js/TakeOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:95601:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
subscribeTo/<@https://bdaconfigurationtool.azurewebsites.net/vendor.js:98517:31
subscribeToResult@https://bdaconfigurationtool.azurewebsites.net/vendor.js:98694:84
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._innerSub@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93451:90
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._tryNext@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93445:14
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._next@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93428:18
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87885:18
subscribeToArray/<@https://bdaconfigurationtool.azurewebsites.net/vendor.js:98559:24
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype._trySubscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87266:25
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87252:22
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93406:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
subscribeTo/<@https://bdaconfigurationtool.azurewebsites.net/vendor.js:98517:31
subscribeToResult@https://bdaconfigurationtool.azurewebsites.net/vendor.js:98694:84
./node_modules/rxjs/_esm5/internal/observable/combineLatest.js/CombineLatestSubscriber.prototype._complete@https://bdaconfigurationtool.azurewebsites.net/vendor.js:88828:107
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.complete@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87897:18
subscribeToArray/<@https://bdaconfigurationtool.azurewebsites.net/vendor.js:98562:24
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype._trySubscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87266:25
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87252:22
./node_modules/rxjs/_esm5/internal/observable/combineLatest.js/CombineLatestOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:88798:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
./node_modules/rxjs/_esm5/internal/operators/scan.js/ScanOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:94739:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
./node_modules/rxjs/_esm5/internal/operators/filter.js/FilterOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:92593:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
./node_modules/rxjs/_esm5/internal/operators/map.js/MapOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93154:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
./node_modules/rxjs/_esm5/internal/operators/take.js/TakeOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:95601:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
subscribeTo/<@https://bdaconfigurationtool.azurewebsites.net/vendor.js:98517:31
subscribeToResult@https://bdaconfigurationtool.azurewebsites.net/vendor.js:98694:84
./node_modules/rxjs/_esm5/internal/operators/switchMap.js/SwitchMapSubscriber.prototype._innerSub@https://bdaconfigurationtool.azurewebsites.net/vendor.js:95513:115
./node_modules/rxjs/_esm5/internal/operators/switchMap.js/SwitchMapSubscriber.prototype._next@https://bdaconfigurationtool.azurewebsites.net/vendor.js:95503:14
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87885:18
scalar/result<@https://bdaconfigurationtool.azurewebsites.net/vendor.js:90064:20
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype._trySubscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87266:25
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87252:22
./node_modules/rxjs/_esm5/internal/operators/switchMap.js/SwitchMapOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:95481:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
subscribeTo/<@https://bdaconfigurationtool.azurewebsites.net/vendor.js:98517:31
subscribeToResult@https://bdaconfigurationtool.azurewebsites.net/vendor.js:98694:84
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._innerSub@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93451:90
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._tryNext@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93445:14
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._next@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93428:18
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87885:18
subscribeToArray/<@https://bdaconfigurationtool.azurewebsites.net/vendor.js:98559:24
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype._trySubscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87266:25
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87252:22
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93406:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
./node_modules/rxjs/_esm5/internal/operators/filter.js/FilterOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:92593:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
./node_modules/rxjs/_esm5/internal/operators/take.js/TakeOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:95601:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
./node_modules/rxjs/_esm5/internal/operators/defaultIfEmpty.js/DefaultIfEmptyOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:91607:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
subscribeTo/<@https://bdaconfigurationtool.azurewebsites.net/vendor.js:98517:31
subscribeToResult@https://bdaconfigurationtool.azurewebsites.net/vendor.js:98694:84
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._innerSub@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93451:90
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._tryNext@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93445:14
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._next@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93428:18
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87885:18
subscribeToArray/<@https://bdaconfigurationtool.azurewebsites.net/vendor.js:98559:24
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype._trySubscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87266:25
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87252:22
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93406:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
./node_modules/rxjs/_esm5/internal/operators/filter.js/FilterOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:92593:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
./node_modules/rxjs/_esm5/internal/operators/take.js/TakeOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:95601:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
./node_modules/rxjs/_esm5/internal/operators/defaultIfEmpty.js/DefaultIfEmptyOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:91607:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
subscribeTo/<@https://bdaconfigurationtool.azurewebsites.net/vendor.js:98517:31
subscribeToResult@https://bdaconfigurationtool.azurewebsites.net/vendor.js:98694:84
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._innerSub@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93451:90
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._tryNext@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93445:14
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._next@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93428:18
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87885:18
./node_modules/rxjs/_esm5/internal/operators/defaultIfEmpty.js/DefaultIfEmptySubscriber.prototype._complete@https://bdaconfigurationtool.azurewebsites.net/vendor.js:91625:30
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.complete@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87897:18
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype._complete@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87915:26
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.complete@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87897:18
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype._complete@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87915:26
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.complete@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87897:18
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._complete@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93456:30
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.complete@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87897:18
subscribeToArray/<@https://bdaconfigurationtool.azurewebsites.net/vendor.js:98562:24
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype._trySubscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87266:25
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87252:22
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93406:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
./node_modules/rxjs/_esm5/internal/operators/filter.js/FilterOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:92593:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
./node_modules/rxjs/_esm5/internal/operators/take.js/TakeOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:95601:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
./node_modules/rxjs/_esm5/internal/operators/defaultIfEmpty.js/DefaultIfEmptyOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:91607:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93406:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
./node_modules/rxjs/_esm5/internal/operators/map.js/MapOperator.prototype.call@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93154:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87247:22
subscribeTo/<@https://bdaconfigurationtool.azurewebsites.net/vendor.js:98517:31
subscribeToResult@https://bdaconfigurationtool.azurewebsites.net/vendor.js:98694:84
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._innerSub@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93451:90
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._tryNext@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93445:14
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._next@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93428:18
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87885:18
./node_modules/rxjs/_esm5/internal/operators/map.js/MapSubscriber.prototype._next@https://bdaconfigurationtool.azurewebsites.net/vendor.js:93177:26
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://bdaconfigurationtool.azurewebsites.net/vendor.js:87885:18
./node_modules/rxjs/_esm5/internal/operators/tap.js/TapSubscriber.prototype._next@https://bdaconfigurationtool.azurewebsites.net/vendor.js:95895:26
"

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by dineshmaths1** [comment]
I am  also facing this problem

**Comment by kasimir1309** [comment]
Me too

**Comment by Kumohira** [comment]
I am also facing this problem, 5 days ago my ionic application (v5.4.4) was fine, but now when i try to use routing (navigateRoute or navigateForward) i got : 
[Front for longstractor/server0.conn17.child1/longstractor399]

**Comment by Kumohira** [comment]
The error didn't say anything about what was wrong, so I enabled the tracing on my routing module and the logs showed me what was the error.

imports: [
    RouterModule.forRoot(
      routes,
      { enableTracing: true } // <-- debugging purposes only
    )
]
