### ISSUE TITLE
Dgeni is giving errors while building pacages locally

### ISSUE THREAD

**Issue by ajitsinghkaler** [angular/angular#35865]
# 🐞 bug report

### Affected Package

 The issue is caused by dgeni

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 While running yarn docs-only in my local machine it is giving me following errors 
dgeni ./tools/transforms/angular.io-package
info:    running processor: readFilesProcessor
info:    running processor: extractJSDocCommentsProcessor
info:    running processor: collectExamples
info:    running processor: readTypeScriptModules
info:    running processor: linkInheritedDocs
info:    running processor: parseTagsProcessor
info:    running processor: extractTagsProcessor
info:    running processor: codeNameProcessor
info:    running processor: addNotYetDocumentedProperty
info:    running processor: splitDescription
info:    running processor: fixupRealProjectRelativePath
info:    running processor: convertPrivateClassesToInterfacesProcessor
info:    running processor: mergeDecoratorDocs
info:    running processor: extractDecoratedClassesProcessor
info:    running processor: extractPipeParams
info:    running processor: filterMembers
info:    running processor: removeInjectableConstructors
info:    running processor: createOverviewDump
info:    running processor: markBarredODocsAsPrivate
info:    running processor: mergeParameterInfo
info:    running processor: addMetadataAliasesProcessor
info:    running processor: addGlobalApiDataProcessor
info:    running processor: collectPackageContentDocsProcessor
info:    running processor: computeIdsProcessor
info:    running processor: processAliasDocs
error:   Error: There is no doc that matches "@alias core/ɵgetLocalePluralCase" - doc "/home/amrit/Documents/angular/packages/common/getLocalePluralCase" (const)  - from file "/home/amrit/Documents/angular/packages/common/src/i18n/locale_data_api.ts" - starting at line 507, ending at line 507
    at /home/amrit/Documents/angular/aio/tools/transforms/angular-api-package/processors/processAliasDocs.js:32:19
    at Array.forEach (<anonymous>)
    at Object.$process (/home/amrit/Documents/angular/aio/tools/transforms/angular-api-package/processors/processAliasDocs.js:13:12)
    at /home/amrit/Documents/angular/aio/node_modules/dgeni/lib/Dgeni.js:183:54
    at _fulfilled (/home/amrit/Documents/angular/aio/node_modules/q/q.js:854:54)
    at /home/amrit/Documents/angular/aio/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/home/amrit/Documents/angular/aio/node_modules/q/q.js:816:13)
    at /home/amrit/Documents/angular/aio/node_modules/q/q.js:624:44
    at runSingle (/home/amrit/Documents/angular/aio/node_modules/q/q.js:137:13)
    at flush (/home/amrit/Documents/angular/aio/node_modules/q/q.js:125:13)
error:   Error processing docs:  Error: There is no doc that matches "@alias core/ɵgetLocalePluralCase" - doc "/home/amrit/Documents/angular/packages/common/getLocalePluralCase" (const)  - from file "/home/amrit/Documents/angular/packages/common/src/i18n/locale_data_api.ts" - starting at line 507, ending at line 507
    at /home/amrit/Documents/angular/aio/tools/transforms/angular-api-package/processors/processAliasDocs.js:32:19
    at Array.forEach (<anonymous>)
    at Object.$process (/home/amrit/Documents/angular/aio/tools/transforms/angular-api-package/processors/processAliasDocs.js:13:12)
    at /home/amrit/Documents/angular/aio/node_modules/dgeni/lib/Dgeni.js:183:54
    at _fulfilled (/home/amrit/Documents/angular/aio/node_modules/q/q.js:854:54)
    at /home/amrit/Documents/angular/aio/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/home/amrit/Documents/angular/aio/node_modules/q/q.js:816:13)
    at /home/amrit/Documents/angular/aio/node_modules/q/q.js:624:44
    at runSingle (/home/amrit/Documents/angular/aio/node_modules/q/q.js:137:13)
    at flush (/home/amrit/Documents/angular/aio/node_modules/q/q.js:125:13)
/home/amrit/Documents/angular/aio/node_modules/q/q.js:155
                throw e;
                ^

Error: There is no doc that matches "@alias core/ɵgetLocalePluralCase" - doc "/home/amrit/Documents/angular/packages/common/getLocalePluralCase" (const)  - from file "/home/amrit/Documents/angular/packages/common/src/i18n/locale_data_api.ts" - starting at line 507, ending at line 507
    at /home/amrit/Documents/angular/aio/tools/transforms/angular-api-package/processors/processAliasDocs.js:32:19
    at Array.forEach (<anonymous>)
    at Object.$process (/home/amrit/Documents/angular/aio/tools/transforms/angular-api-package/processors/processAliasDocs.js:13:12)
    at /home/amrit/Documents/angular/aio/node_modules/dgeni/lib/Dgeni.js:183:54
    at _fulfilled (/home/amrit/Documents/angular/aio/node_modules/q/q.js:854:54)
    at /home/amrit/Documents/angular/aio/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/home/amrit/Documents/angular/aio/node_modules/q/q.js:816:13)
    at /home/amrit/Documents/angular/aio/node_modules/q/q.js:624:44
    at runSingle (/home/amrit/Documents/angular/aio/node_modules/q/q.js:137:13)
    at flush (/home/amrit/Documents/angular/aio/node_modules/q/q.js:125:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

## 🔬 Minimal Reproduction

Run yarn docs-only to create files of docs in local
 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

dgeni ./tools/transforms/angular.io-package
info:    running processor: readFilesProcessor
info:    running processor: extractJSDocCommentsProcessor
info:    running processor: collectExamples
info:    running processor: readTypeScriptModules
info:    running processor: linkInheritedDocs
info:    running processor: parseTagsProcessor
info:    running processor: extractTagsProcessor
info:    running processor: codeNameProcessor
info:    running processor: addNotYetDocumentedProperty
info:    running processor: splitDescription
info:    running processor: fixupRealProjectRelativePath
info:    running processor: convertPrivateClassesToInterfacesProcessor
info:    running processor: mergeDecoratorDocs
info:    running processor: extractDecoratedClassesProcessor
info:    running processor: extractPipeParams
info:    running processor: filterMembers
info:    running processor: removeInjectableConstructors
info:    running processor: createOverviewDump
info:    running processor: markBarredODocsAsPrivate
info:    running processor: mergeParameterInfo
info:    running processor: addMetadataAliasesProcessor
info:    running processor: addGlobalApiDataProcessor
info:    running processor: collectPackageContentDocsProcessor
info:    running processor: computeIdsProcessor
info:    running processor: processAliasDocs
error:   Error: There is no doc that matches "@alias core/ɵgetLocalePluralCase" - doc "/home/amrit/Documents/angular/packages/common/getLocalePluralCase" (const)  - from file "/home/amrit/Documents/angular/packages/common/src/i18n/locale_data_api.ts" - starting at line 507, ending at line 507
    at /home/amrit/Documents/angular/aio/tools/transforms/angular-api-package/processors/processAliasDocs.js:32:19
    at Array.forEach (<anonymous>)
    at Object.$process (/home/amrit/Documents/angular/aio/tools/transforms/angular-api-package/processors/processAliasDocs.js:13:12)
    at /home/amrit/Documents/angular/aio/node_modules/dgeni/lib/Dgeni.js:183:54
    at _fulfilled (/home/amrit/Documents/angular/aio/node_modules/q/q.js:854:54)
    at /home/amrit/Documents/angular/aio/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/home/amrit/Documents/angular/aio/node_modules/q/q.js:816:13)
    at /home/amrit/Documents/angular/aio/node_modules/q/q.js:624:44
    at runSingle (/home/amrit/Documents/angular/aio/node_modules/q/q.js:137:13)
    at flush (/home/amrit/Documents/angular/aio/node_modules/q/q.js:125:13)
error:   Error processing docs:  Error: There is no doc that matches "@alias core/ɵgetLocalePluralCase" - doc "/home/amrit/Documents/angular/packages/common/getLocalePluralCase" (const)  - from file "/home/amrit/Documents/angular/packages/common/src/i18n/locale_data_api.ts" - starting at line 507, ending at line 507
    at /home/amrit/Documents/angular/aio/tools/transforms/angular-api-package/processors/processAliasDocs.js:32:19
    at Array.forEach (<anonymous>)
    at Object.$process (/home/amrit/Documents/angular/aio/tools/transforms/angular-api-package/processors/processAliasDocs.js:13:12)
    at /home/amrit/Documents/angular/aio/node_modules/dgeni/lib/Dgeni.js:183:54
    at _fulfilled (/home/amrit/Documents/angular/aio/node_modules/q/q.js:854:54)
    at /home/amrit/Documents/angular/aio/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/home/amrit/Documents/angular/aio/node_modules/q/q.js:816:13)
    at /home/amrit/Documents/angular/aio/node_modules/q/q.js:624:44
    at runSingle (/home/amrit/Documents/angular/aio/node_modules/q/q.js:137:13)
    at flush (/home/amrit/Documents/angular/aio/node_modules/q/q.js:125:13)
/home/amrit/Documents/angular/aio/node_modules/q/q.js:155
                throw e;
                ^

Error: There is no doc that matches "@alias core/ɵgetLocalePluralCase" - doc "/home/amrit/Documents/angular/packages/common/getLocalePluralCase" (const)  - from file "/home/amrit/Documents/angular/packages/common/src/i18n/locale_data_api.ts" - starting at line 507, ending at line 507
    at /home/amrit/Documents/angular/aio/tools/transforms/angular-api-package/processors/processAliasDocs.js:32:19
    at Array.forEach (<anonymous>)
    at Object.$process (/home/amrit/Documents/angular/aio/tools/transforms/angular-api-package/processors/processAliasDocs.js:13:12)
    at /home/amrit/Documents/angular/aio/node_modules/dgeni/lib/Dgeni.js:183:54
    at _fulfilled (/home/amrit/Documents/angular/aio/node_modules/q/q.js:854:54)
    at /home/amrit/Documents/angular/aio/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/home/amrit/Documents/angular/aio/node_modules/q/q.js:816:13)
    at /home/amrit/Documents/angular/aio/node_modules/q/q.js:624:44
    at runSingle (/home/amrit/Documents/angular/aio/node_modules/q/q.js:137:13)
    at flush (/home/amrit/Documents/angular/aio/node_modules/q/q.js:125:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

Don't know

**Comment by petebacondarwin** [comment]
@ajitsinghkaler - sorry to hear you are getting this error. I can't reproduce it.
Have you run `yarn setup` to ensure everything that is needed is in-place?
Is this running directly off an un-modified `master` branch? The error implies that `ɵgetLocalePluralCase` is no longer being exported from the `core` package.

**Comment by ajitsinghkaler** [comment]
Yea I ran yarn setup and uses it on a un modified master branch

**Comment by petebacondarwin** [comment]
Did it only just start doing this? Was there some change that might have caused it?
Can you try it on a clean clone of the repo?
Can you check that this line is correct? https://github.com/angular/angular/blob/669df70da521fb190454088d69588e776b44f94e/packages/core/src/core_private_export.ts#L19
Also can you try removing the alias tag here: https://github.com/angular/angular/blob/055533b6a778522c0ab6e00a401229015bc9fadb/packages/common/src/i18n/locale_data_api.ts#L504

**Comment by ajitsinghkaler** [comment]
Thanks, @petebacondarwin for looking into this actually somehow my yarn.lock file got updated while I was setting up my angular project on a new pc. I reverted all the changes in the lock file and run the setup once again I ran smoothly I just didn't understand why changes in the .lock file would cause dgeni to fail. Thanks again for looking into this.
