### ISSUE TITLE
"Can't bind to 'capture' since it isn't a known property of 'input'."

### ISSUE THREAD

**Issue by YogliB** [angular/angular#35867]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/cli

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-tpbfqe?file=src%2Fapp%2Fapp.component.html

## 🔥 Exception or Error
```bash
error NG8002: Can't bind to 'capture' since it isn't a known property of 'input'.
```

## 🌍  Your Environment

**Angular Version:**
Angular: 9.0.2

**Anything else relevant?**
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#capture

**Comment by pkozlowski-opensource** [comment]
`[capture]` means element's _property_ and there is no `capture` _property_ on the input element as far as I can tell: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement

Still, there is a `capture` _attribute_ so you if you want to bind to this one you could do `[attr.capture]="expression"`.

Given the above it works as designed but I can see how this can get confusing: sets of HTML attributes and properties on a given element are _very close_ but not the same. As such things "just work most of the time" but not always (as here!). This is properly confusing! 

It is too late to change template syntax to clear up this confusion on the syntax level but I think that we could improve the error message to offer common reasons for this error (typo, input for a directive that didn't match, property vs. attribute as here).

Going to keep this issue open so we can ponder improving the error message.

**Comment by YogliB** [comment]
@pkozlowski-opensource Thanks for the explanation!

Where can I get more info about this?

**Comment by pkozlowski-opensource** [comment]
@YogliB https://angular.io/guide/template-syntax#binding-syntax-an-overview would be a good start

**Comment by AndrewKushnir** [comment]
This error should now be covered by the https://angular.io/errors/NG8002 created recently. Feel free to propose an improvement to that page if needed. Thank you.
