### ISSUE TITLE
Form refreshes on click event - https://github.com/angular/angular/issues/15058 

### ISSUE THREAD

**Issue by DineshNO** [angular/angular#35860]
Hi,
I am facing an issue similar to #15058 (https://github.com/angular/angular/issues/15058 ) in angular 8.
Form gets submit on click event and redirects to home page.
<button class="btn btn-success" type="submit" (click)="onAddItem()">Add</button>

On changing code to 
<button class="btn btn-success" type="button" (click)="onAddItem()">Add</button>

It stays on the screen on click event.

Browser used : 
Chrome Version 80.0.3987.132 (Official Build) [(64-bit)]

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by AndrewKushnir** [comment]
Hi @DineshNO, if I understand correctly, changing button type helped achieve the necessary behavior. I will close this ticket, please open a new one (and provide a repro using [Stackblitz](https://stackblitz.com/)) if the problem still exists. Thank you.
