### ISSUE TITLE
ViewChild on html element displayed with innerhtml

### ISSUE THREAD

**Issue by Rogier-blip** [angular/angular#35874]
# 🐞 bug or feature

### Affected Package
The issue is caused by package @angular/core, I think.

### Is this a regression?
No 

### Description

ViewChild on an element within innerHtml returns undefined.

## 🔬 Minimal Reproduction

```
@Component({
  selector: 'app-component',
  template: `<p [innerHTML]="'This is the innerhtml, 
                           and the following tag I want to select with ViewChild: 
                           <ng-template #innerHtmlNgTemplate></ng-template>' | safeHtml"></p>`
})
export class AppComponent {
  @ViewChild('innerHtmlNgTemplate') public innerHtmlNgTemplate;

  ngAfterViewInit() {
      console.log(this.innerHtmlNgTemplate); // undefined
  }
}
```
https://stackblitz.com/edit/angular-k1xeh6?file=src%2Fapp%2Fapp.component.ts

## 🌍  Your Environment

**Angular Version:**
Stackblitz is with Angular 8

But seems to be same with Angular 9

**Comment by pkozlowski-opensource** [comment]
When you insert HTML _string_ through `innerHTML`, such _string_ is not processed by Angular. As such you can't expect any Angular syntax / functionality (including queries) to work - simply put Angular has no chance of processing static HTML inserted into `innerHTML`. In this respect the observed behaviour "works as designed".

I'm not sure what your exact, functional use-case is but the scenario you've exposed is not something that Angular supports today and quite honestly, this is not how it was designed in the first place.

I'm going to close this issue as you are trying to use the framework in the way it wasn't designed for. Still, I would love to hear more about your exact use-case so we can (maybe) suggest an alternative approach.

**Comment by Rogier-blip** [comment]
@pkozlowski-opensource Thanks for your response and explanation!

My use case is the following. 

I am receiving a string with HMTL from the backend. In the HTML there is a tag, for example, 
<span #dynamicComponent></span>. The idea is to replace this tag with an Angular component dynamically created with Dynamic component loading (https://angular.io/guide/dynamic-component-loader). 

Cheers
