### ISSUE TITLE
ngcc with preserveWhitespaces

### ISSUE THREAD

**Issue by tscislo** [angular/angular#35871]
I'm using Angular 9 with Ivy to compile my app. This app uses a bunch of libs which it compiles using ngcc form View Engine to Ivy. I want those libs to be compiled by ngcc with preserveWhitespaces: true, currently this does not happen. I tried setting preserveWhitespaces in tsconfig of my project, but it does not work.

When those libs are used as they are without ngcc compilation I get preserveWhitespaces correctly respected.

**Comment by petebacondarwin** [comment]
Indeed you are right that we are not offering this option in ngcc...

I think the relevant place is where we create the options for the Angular compiler here: https://github.com/angular/angular/blob/6b468f9b2e4b99cd9e784c2515484bce47147476/packages/compiler-cli/ngcc/src/packages/entry_point_bundle.ts#L51-L54

We need to decide the best approach for supporting this. On the one hand we could just add `preserveWhitespaces` as an option to ngcc but perhaps we should be able to accept a `tsconfig.json` path and parse it ourselves...

**Comment by petebacondarwin** [comment]
Tracking at FW-1972

**Comment by tscislo** [comment]
@pedroclayman thanks for response! Is there any workaround I can use now for old libs which use preserveWhitespaces: true while I want to consume them in my Angular 9 app with Ivy enabled?

**Comment by petebacondarwin** [comment]
If you have access to the original library code, could you try specifying it explicitly in the `@Component()` decorators. See https://angular.io/api/core/Component#preservewhitespaces

**Comment by tscislo** [comment]
Yeah, that works. However I do not have source code for every library that I use...

**Comment by petebacondarwin** [comment]
I can't think of any other workaround until we fix the configuration issue.

**Comment by petebacondarwin** [comment]
@tscislo - a quick question... if you turn off Ivy and consume these libraries does the preserve whitespaces option apply to the View Engine built libraries too? I kind of expected ViewEngine libraries to have been built already and so the settings of the consuming app would not affect them.

**Comment by tscislo** [comment]
So here is the thing:
1. I have a lib project using Angular 8 where this "preserveWhitespaces" is not set explicitly, but apparently by default it builds those libs with preserveWhitespaces: true. Therefore when I consume it in my app with View Engine it works. What I set for preserveWhitespaces in my app (that consumes lib) is relevant only to my app I guess.
2. When I forcefully set it per each component in my lib using preserveWhitespaces: true and consumed it in my app with Ivy it also works.

**Comment by petebacondarwin** [comment]
Hmm, so this is tricky. It really should be the library author's decision on whether whitespace is preserved in their library's templates. 

Also strange is that in V8 the default is still `false`: https://v8.angular.io/guide/angular-compiler-options#preservewhitespaces. So I am not sure how this is working in v8...

**Comment by petebacondarwin** [comment]
OK so ngcc should accept an option to point to a tsconfig.json file (and programmatically to pass the config object directly) so that it will pull in the Angular compiler specific options.

**Comment by tscislo** [comment]
@petebacondarwin well by default ngcc shouldn't change the way the library was compiled either with or without preserveWhitespaces it should know what was set during initial compilation of those libs. 

It should however be possible to override this by for example honoring consuming project's tsconfig.json file.

**Comment by petebacondarwin** [comment]
As I understand it, in ViewEngine the application actually built the templates for components in libraries; and it used its own configuration to do this.

Since ngcc is supposed to make ViewEngine libraries available to Ivy, and it is also compiling the templates, I think the most "compatible" approach is to pass the application configuration through to ngcc.

**Comment by tscislo** [comment]
@petebacondarwin ok so if you're saying that for View Engine Angular compiler in consuming app also builds templates for components in libraries and uses its own config to do that then yes we should pass app configuration through to ngcc for Ivy compilation as well.
Is my understanding correct?

**Comment by petebacondarwin** [comment]
That is what @alxhub explained to me :-)

**Comment by tscislo** [comment]
@mhevery @petebacondarwin when (which version) this will be available in angular/compiler-cli?

**Comment by petebacondarwin** [comment]
It is in the 9.1.0-rc.2 release: https://github.com/angular/angular/commit/b08168bb90d7b85a7e5519056973510b608be4e9

**Comment by tscislo** [comment]
@petebacondarwin any idea when it will be final?

**Comment by petebacondarwin** [comment]
This week, unless we see a serious issue.

**Comment by tscislo** [comment]
This works well as expected. Thanks for your help! @petebacondarwin @mhevery

**Comment by petebacondarwin** [comment]
Great! Thanks for checking in.
