### ISSUE TITLE
ngDefaultControl is resetting the form control value

### ISSUE THREAD

**Issue by tirupathi471** [angular/angular#35872]
To resolve **No value accessor for form control with unspecified name attribute** error i have added **ngDefaultControl** attribute to my custom component, from that point form control value has been resetting.

Please let me know any valuable suggestion.

` this.formControl.valueChanges.subscribe(data => {
            console.log(data);
        });` 

https://stackoverflow.com/questions/60545048/ngdefaultcontrol-is-resetting-the-form-control-value

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
