### ISSUE TITLE
zone-patch-rxjs no longer work with Zone.js 0.10.0

### ISSUE THREAD

**Issue by iamchucky** [angular/angular#35878]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/zone.js

### Is this a regression?

 Yes, the previous version in which this bug was not present was: zone.js@0.9.1

### Description

 

Was trying to upgrade my project from Angular 8 to 9, noticed that protractor e2e tests started failing. Found that `ngZone.runOutsideAngular` is no longer doing what it supposed to do. After some more investigation, it is clear that `zone-patch-rxjs` is no longer doing its job starting with zone.js@0.10.0

## 🔬 Minimal Reproduction

 
ng8 with zone.js 0.9.1: https://stackblitz.com/edit/angular-kcwxp7
ng9 with zone.js 0.10.0: https://stackblitz.com/edit/angular-pgsmn9 

ng8 with zone.js 0.9.1 interval map: https://stackblitz.com/edit/angular-pdb78p
ng9 with zone.js 0.10.0 interval map: https://stackblitz.com/edit/angular-1tkd7i 

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.4
Node: 12.14.1
OS: darwin x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.4
@angular-devkit/build-angular     0.900.4
@angular-devkit/build-optimizer   0.900.4
@angular-devkit/build-webpack     0.900.4
@angular-devkit/core              9.0.4
@angular-devkit/schematics        9.0.4
@ngtools/webpack                  9.0.4
@schematics/angular               9.0.4
@schematics/update                0.900.4
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by JiaLiPassion** [comment]
@iamchucky , thank you for posting the issue, I created a PR to fix this one, the reason is the `bundle` of `zone-patch-rxjs` is not correct.
