### ISSUE TITLE
feat(dist): include "core" modules in angular2 npm dist

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#3588]
This task is to change the npm release script to copy modules from module folders outside of `angular2` into the npm distribution, if they are intended to be included according to #3458.

This issue is urgent because the `http` module has been moved out of the `angular2` folder, and would not be included in the npm distribution without changing the release script.

**Comment by jeffbcross** [comment]
Working on this now. It's a little more complicated than just copy/merging top-level module files and module src directories into angular2. The `System.register` statements need to be changed to reflect the new root module.

**Comment by DanWahlin** [comment]
I'm in the process of updating a demo to alpha 35 that uses http. Although I do see http in the bundles it's not in the root npm scripts as mentioned. Should I hold off or is it possible to use http now (I'm using jspm by the way for the demo). Thanks!

**Comment by jeffbcross** [comment]
@danwahlin if you can use the bundle, it should work alongside the angular2 bundle. I'm working on getting everything in order for alpha 36 release.

**Comment by DanWahlin** [comment]
Thanks Jeff. I got it going with some modifications to the "paths" property in the jspm config. It seems to load the bundle now (not sure it works yet though since I'm fighting some other issues that have to be upgraded :-)).

**Comment by IgorMinar** [comment]
@jeffbcross can you please provide current status for this?

**Comment by jeffbcross** [comment]
@IgorMinar yep I'll actually close this issue since it's solved by #3713. I updated that issue before I left for long weekend, but didn't think to update this one. Short story is, the bulk of the moving work is done; I just have to resolve a failing test, and I'm sure more little issues will creep up in the process.

**Comment by DanWahlin** [comment]
Great - thanks for the update @jeffbcross! I'm going to hold off until alpha 36 since I've run into some other things along the way that I suspect will be simplified with the next release.

**Comment by jeffbcross** [comment]
@DanWahlin that sounds like a good plan. Things should be more orderly with that release. Maybe you could help dogfood pre-alpha 36 after #3713 and #3714 are resolved?

**Comment by DanWahlin** [comment]
Sounds great. I suspect some of the issues I'm seeing now are completely my own doing (due to not realizing something changed somewhere) but I'm happy to try things out once you think the issues above are resolved.
