### ISSUE TITLE
[docs] Enable mouse wheel scrolling while hovering over the table of contents

### ISSUE THREAD

**Issue by Achilles1515** [angular/angular#35880]
# 📚 Docs or angular.io bug report

### Description

(Small personal rant)

Does it bother anyone else that your mouse wheel scrolling gets hijacked and ignored with your mouse on the rightmost ~18% of the page (on top of the table of contents)? If the table of contents itself is scrollable...then okay, maybe...but why can't I just scroll the page like normal if the table of contents does not have an active scrollbar?

Every time this happens, my brain goes haywire for a moment and I think my page is frozen or something. I find it to be extremely counter-intuitive, especially when there are few entries in the table of contents and tons of empty space underneath (with this empty space having the exact same background color as the main content, making you think it's just part of the main content).

Example of a docs page with a similar table of contents that doesn't hijack mouse scrolling:
[NG-ZORRO](https://ng.ant.design/docs/introduce/en)

There, it feels totally normal to be able to scroll the page while hovering over the table of contents or even just the right side of the page.

Can this restrain scrolling behavior just be removed entirely?

[app.component.html](https://github.com/angular/angular/blob/master/aio/src/app/app.component.html#L60)
```html
<div *ngIf="hasFloatingToc" class="toc-container no-print" [style.max-height.px]="tocMaxHeight" (wheel)="restrainScrolling($event)">
  <aio-lazy-ce selector="aio-toc"></aio-lazy-ce>
</div>
```

[app.component.ts](https://github.com/angular/angular/blob/master/aio/src/app/app.component.ts#L364)
```ts
// Restrain scrolling inside an element, when the cursor is over it
  restrainScrolling(evt: WheelEvent) {
    const elem = evt.currentTarget as Element;
    const scrollTop = elem.scrollTop;

    if (evt.deltaY < 0) {
      // Trying to scroll up: Prevent scrolling if already at the top.
      if (scrollTop < 1) {
        evt.preventDefault();
      }
    } else {
      // Trying to scroll down: Prevent scrolling if already at the bottom.
      const maxScrollTop = elem.scrollHeight - elem.clientHeight;
      if (maxScrollTop - scrollTop < 1) {
        evt.preventDefault();
      }
    }
  }
```

This is what it feels like without it....normal.
![GIF](https://user-images.githubusercontent.com/23387905/76028167-04007900-5f00-11ea-9278-9db1a278b13a.gif)

**Comment by sonukapoor** [comment]
Same here :) I always forget that.

**Comment by petebacondarwin** [comment]
Sounds like a good idea.  We should check with @gkalpak as to why it was added in the first place before changing though...

**Comment by gkalpak** [comment]
85241878693 has more info on why we need the restraining when the ToC itself is scrollable.
Happy to remove the restraining when ToC is not scrollable itself.

**Comment by lazarljubenovic** [comment]
So we have two options:

- A: make it obvious that we cannot scroll the document while hovering the ToC by changing the design.
- B: allow us to scroll the document while hovering ToC, by changing the behavior.

# A

Maybe we could add a line? Or turn the ToC into a collapsable card, similar to how it works in Google Docs? That would solve the confusion, I think.

# B

I think we should fall back to the default behavior but find a different way to fix the bug mentioned in the previous comment. If the inner scrollable element is already at the bottom, I expect the outer element to start scrolling (unless clearly visually distinguished, which gets us back to "A").

**Comment by Achilles1515** [comment]
> [8524187](https://github.com/angular/angular/commit/8524187869363ff01588a18837184e698ab5b8ee) has more info on why we need the restraining when the ToC itself is scrollable.
> Happy to remove the restraining when ToC is not scrollable itself.
Thanks for the link! I think it would be a great improvement and make more sense from a user perspective to only restrain when the ToC is scrollable.

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
