### ISSUE TITLE
[docs] Incomplete HttpClient documentation

### ISSUE THREAD

**Issue by a2937** [angular/angular#35887]
# 📚 Docs 

### Description

The example involving JsonP is missing proper bracketing at the end of handle error as well as parameterization of Observable elements. I am not sure if this issue has been discussed with the existing tickets for this section of page but if it has my apologies. 

<pre><code>
/* GET heroes whose name contains search term */
searchHeroes(term: string): Observable {
  term = term.trim();

  let heroesURL = `${this.heroesURL}?${term}`;
  return this.http.jsonp(heroesUrl, 'callback').pipe(
      catchError(this.handleError('searchHeroes', []) // then handle the error
    );
};
</code></pre>

### What's the affected URL?**
https://angular.io/guide/http#making-a-jsonp-request

### Anything else relevant?
I am certain there are probably a few minor issues such as using a element without having the reader declare those variables.

**Comment by sonukapoor** [comment]
@a2937 Good catch. I have created a PR for it.
