### ISSUE TITLE
SSR build fails with an error: @angular/platform-server has missing dependencies: @angular/animations/browser

### ISSUE THREAD

**Issue by realharry** [angular/angular#35888]
## 🐞 bug report

When I try to build an SSR app, I get the following error:

```
ERROR in The target entry-point "@angular/platform-server" has missing dependencies: @angular/animations/browser"
```

Obviously, adding the package `@angular/animations` to the project fixes the error. But, what I don't understand is, why `platform-server` has dependency on `@angular/animations/browser`? Maybe it's a mistake? (BTW, `platform-browser` does not seem to require the `@angular/animations` package.)

### Affected Package

@angular/platform-server

### Is this a regression?

Don't know.

### Description

1. Create an angular SSR app.
1. Remove dependency on @angular/animation.
1. Notice you cannot successfully `build:ssr` any more.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.5
Node: 10.19.0
OS: linux x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.4
@angular-devkit/build-angular      0.900.5
@angular-devkit/build-ng-packagr   0.900.5
@angular-devkit/build-optimizer    0.900.5
@angular-devkit/build-webpack      0.900.5
@angular-devkit/core               9.0.4
@angular-devkit/schematics         9.0.5
@angular/pwa                       0.900.5
@ngtools/webpack                   9.0.5
@nguniversal/builders              9.0.1
@nguniversal/common                9.0.1
@nguniversal/express-engine        9.0.1
@schematics/angular                9.0.5
@schematics/update                 0.900.5
ng-packagr                         9.0.2
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
    
</code></pre>

**Comment by alan-agius4** [comment]
Hi @realharry, Both `@angular/platform-server` and `@angular/platform-browser` require  `@angular/animations`, while the former has a peerDependency on `@angular/animations` the later doesn't which is a bug.  Thus, removing `@angular/animations` should result in an error.

**Comment by realharry** [comment]
Hi Alan, thanks for the clarification. That makes sense. I'll close this ticket. Thanks!
