### ISSUE TITLE
Require property binding // True template null checks in Ivy

### ISSUE THREAD

**Issue by babakness** [angular/angular#35898]
Hello, using Angular 9, I have a component defined as such

```ts
@Compontent({
  selector: 'app-whatever',
})
export class Whatever {
  @Input myProp: string
}
```

I also have `tsconfig.json` to be strict, with `strictNullChecks` and `noImplicityAny`, for Angular I've declared `strictTemplates`

While Angular does complain if I do this

```
<app-whatever [myProp]></app-whatever>
```
It does not complain if I don't bind any properties at all

```
<app-whatever></app-whatever>
```

Why is that? I want to catching missing prop bindings at static time, not during runtime.

In React this might be done as follows

```tsx

interface WhateverProps{
  myProp: string
}

export const Whatever: React.FC<WhateverProps> = ({ myProp }) => ....
```
In which case this would result in a static error

```ts
<Whatever />
```

As it is missing the required `myProp` when `strictNullChecks` is enabled

**Comment by vladimiry** [comment]
See `Strictness flags` table in https://angular.io/guide/template-typecheck

**Comment by babakness** [comment]
@vladimiry I’m using the strictest setting. `strictTemplates` supersedes other settings. Are you suggesting it is possible by tweaking these settings? I wish it were clear.

**Comment by JoostK** [comment]
Hi @babakness,

The concept of "required" inputs is not yet a thing in Angular, and the template type checker will not currently report missing input bindings as you experienced.

**Comment by rafaelss95** [comment]
@babakness see https://github.com/angular/angular/issues/18156#issuecomment-315774348.

**Comment by alxhub** [comment]
Closing as a duplicate feature request of #18156.

@babakness, I completely understand where you're coming from. This is definitely something I want to see in Angular eventually.

**Comment by tonivj5** [comment]
@alxhub #18156 is closed and locked. Maybe could mantain this issue open to track it? :+1:
