### ISSUE TITLE
Extended non-declared component template compilation fails w/ TS file entrypoints

### ISSUE THREAD

**Issue by alexrashed** [angular/angular#35899]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler.

### Is this a regression?
Yes, the previous version in which this bug was not present was: Angular 8

### Description
We implemented a customization process based on `tsconfig.app.json#path`:
- When building the default default app / project, just the sources of the default project are defined in the `tsconfig.app.json#path` section.
- When building the customized app / project, first the sources of the customized app and as a fallback the sources of the default project are defined in the `tsconfig.app.json#path` section.
- When extending a component of the default project, we create a new component and extend the one in the default project but do not export / declare the super component in any module anymore.

With Ivy, the recommended way to define included TS files is to use the entrypoints in `tsconfig.app.json#files` (instead of wildcard imports using `tsconfig.app.json#include` in NG <9):
```
WARNING in <...>\ng-ivy-cust\projects\my-app\src\app\mymodule\mymodule.module.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
```

The previous approach (`tsconfig.app.json#include`) now shows a warning for each component which is included but not used (i.e. overwritten using our customization).

When using `tsconfig.app.json#files`, the template of the super-component is compiled (even though it's not exported or declared in any module) but other components aren't detected for the super-component:
```
ERROR in projects/my-app/src/app/mymodule/mycomponent/mycomponent.component.ts:7:5 - error NG8001: 'app-mycomponent2' is not a known element:
1. If 'app-mycomponent2' is an Angular component, then verify that it is part of this module.
2. If 'app-mycomponent2' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

## 🔬 Minimal Reproduction
Here's a repo with a minimum working example:
https://github.com/alexrashed/ng-ivy-cust
In the project `my-custom-app` the component `Mycomponent3Component` extends `MycomponentComponent`.

Steps to reproduce:
- npm install
- npm run start-custom
  - The project can't be built (see above)
- Edit `projects/my-custom-app/tsconfig.app.json`:
  - Remove the "files" and "include" section and uncomment the "include" section after the "TODO"
- npm run start-custom
  - The project is built and served, but the include warnings are shown.

## 🔥 Exception or Error
<pre><code>
ERROR in projects/my-app/src/app/mymodule/mycomponent/mycomponent.component.ts:7:5 - error NG8001: 'app-mycomponent2' is not a known element:
1. If 'app-mycomponent2' is an Angular component, then verify that it is part of this module.
2. If 'app-mycomponent2' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.5
Node: 12.16.0
OS: win32 x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@ngtools/webpack                  9.0.5
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by alxhub** [comment]
> With Ivy, the recommended way to define included TS files is to use the entrypoints in `tsconfig.app.json#files` (instead of wildcard imports using `tsconfig.app.json#include` in NG <9)

As far as the Angular compiler goes, it doesn't matter. Either way gets the files included in the program.

The warning message you're seeing (`mymodule.module.ts is part of the TypeScript compilation but it's unused.`) is generated by `@ngtools/webpack`, the Angular compiler plugin for Webpack. I don't actually know what it's trying to say - I don't know what Webpack's requirements are around entry points / files in its compilation.

> When using `tsconfig.app.json#files`, the template of the super-component is compiled (even though it's not exported or declared in any module) but other components aren't detected for the super-component

This is normal and expected in Ivy. If you want the base component to have a template, you need to add an NgModule which declares it and scopes the template properly. Alternatively, if you only want the base component to have inputs, queries, etc., you can use the abstract `@Directive()` for it instead, and its subclasses can include their own templates.

**Comment by alexrashed** [comment]
Thanks for taking a look at the issue!

> I don't actually know what it's trying to say - I don't know what Webpack's requirements are around entry points / files in its compilation.

It is meant to warn about files which are not used for the compilation but still included. When using the "files" entrypoint, typescript traverses the import paths and only includes files which are necessary for the compilation. When using a wildcard "include" on the other hand, it's possible to include files which are not referenced by any other file, which is what you're warned about.

> This is normal and expected in Ivy.

I don't think so. If you look at my example repo, the component (`mycomponent.component.ts`) which is throws an error during the compilation of `my-custom-app` is not declared or referenced in any file, since every reference and declaration is overwritten in `my-custom-app` using `tsconfig.json#path`. So in my opinion the template of `mycomponent.component.ts` shouldn't be compiled, since it's never declared in any module. Is that assumption correct?

I know it's a quite complicated scenario, but in my opinion it's the most elegant way for a powerful customization using standard tooling. I would love to use Ivy, but I gave myself a strict "no warnings" policy.

**Comment by alxhub** [comment]
> So in my opinion the template of mycomponent.component.ts shouldn't be compiled, since it's never declared in any module. Is that assumption correct?

No, because Ivy allows module-less components.

I'm going to dig around in this repro a little and see what's going on. So far I see that the source files which are being compiled are:

```
  'projects/my-app/src/app/app.component.ts',
  'projects/my-app/src/app/mymodule/mycomponent/mycomponent.component.ts',
  'projects/my-app/src/app/mymodule2/mycomponent2/mycomponent2.component.ts',
  'projects/my-app/src/app/mymodule2/mymodule2.module.ts',
  'projects/my-custom-app/src/app/mymodule/mycomponent3/mycomponent3.component.ts',
  'projects/my-custom-app/src/app/mymodule/mymodule.module.ts',
  'projects/my-app/src/app/app.module.ts',
  'projects/my-app/src/environments/environment.ts',
  'projects/my-app/src/main.ts',
  'projects/my-app/src/polyfills.ts',
  'projects/my-custom-app/__ng_typecheck__.ts'
```
I need to look at the way things are imported and check if this set of files makes sense.

**Comment by alxhub** [comment]
Okay, after looking through the repro again I understand things completely at this point.

1. my-custom-app uses path mappings to override certain ES module names, so the actual program is assembled both from my-app and my-custom-app's overridden files

2. the overridden mymodule.module.ts file from my-custom-app declares mycomponent3

3. mycomponent3 extends mycomponent, a component declared in the module which was overridden. Thus, mycomponent has no module in the program.

4. Ivy now attempts to compile mycomponent without a module, leading to template type-checking errors.

**Comment by alexrashed** [comment]
This is exactly what happens, but is the compilation of `mycomponent` valid in this scenario?
I can't find any detailed documentation on module-less components in Ivy.
Does this mean that every component is always compiled even though they aren't declared in any module? And if so, is there some kind of workaround?

**Comment by alxhub** [comment]
> Does this mean that every component is always compiled even though they aren't declared in any module?

Yes indeed.

> And if so, is there some kind of workaround?

Two that I can think of.

1) create a separate file with the main logic for your base component, everything but the template. Make it an `@Directive` instead. In my-app the component would then extend the base to provide the default implementation with a template.

In my-custom-app, the overridden component would also extend the base directive. This way you avoid including the my-app version of the component into the program at all.

2) in my-custom-app, declare the base component in an NgModule of its own, since you're overriding the module it used to be declared in.

Either one of these would work.

**Comment by alexrashed** [comment]
I think the second approach won't work, since the two components are using the same selector (as I want to replace the original / extended component).

So the only possiblity with Ivy would then be to always create a pretty artificial inheritance structure. I have to say, that's not very satisfying...
Is there any documentation on this new behavior Ivy introduces?

**Comment by alxhub** [comment]
> I think the second approach won't work, since the two components are using the same selector (as I want to replace the original / extended component).

That's fine, you don't need to _reference_ that module from anything. It just needs to exist so that the compiler can process it correctly.

**Comment by alexrashed** [comment]
Okay, this isn't anything else than a workaround either, as it would force me to create an artificial module just to overcome this issue.
Is there any documentation on this new behavior? And is there really no clean way of fixing this compilation error in my - I have to admin pretty specific but powerful - setup?

**Comment by alexrashed** [comment]
And also, when thinking this though, the workaround with an additional module definition would also not solve the problem, as the module would have to be contained in the set of compiled typescript files but won't be used (and therefore cause the warning).

**Comment by alexrashed** [comment]
Unfortunately I couldn't find a more thorough documentation. But after some tests, I will most likely adopt the first idea:
> 1. create a separate file with the main logic for your base component, everything but the template. Make it an `@Directive` instead. In my-app the component would then extend the base to provide the default implementation with a template.
> In my-custom-app, the overridden component would also extend the base directive. This way you avoid including the my-app version of the component into the program at all.

However, the superclass (containing the standard component's logic) is an abstract class and doesn't need the Directive decorator.
I created a new branch in my repository with the minimum working example with an example and some tests (inputs,...):
https://github.com/alexrashed/ng-ivy-cust/tree/customization-tests

As there's no movement towards a better solution, I'll close the ticket.
@alxhub: Thanks a lot for the help!
