### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error: The pipe 'async' could not be found!

### ISSUE THREAD

**Issue by Sid13Kulat** [angular/angular#35900]
Hello Everyone,

I have upgraded my angular project to Angular 9.0,4. Everything is working fine but I am getting issue of pipe in my template like **"ERROR Error: Uncaught (in promise): Error: The pipe 'async' could not be found!"**

I am using "*ngIf='vehicles$ | async; let values;'" in my template.

Can anyone please help me in this?

Below are the configuration of my angular project.

Angular CLI: 9.0.4
Node: 12.16.1
OS: win32 x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect              0.803.25
@angular-devkit/build-angular      0.900.4
@angular-devkit/build-optimizer   0.900.4
@angular-devkit/build-webpack    0.900.4
@angular-devkit/core                     7.3.9
@angular-devkit/schematics          7.3.9
@angular/cdk                                 9.1.0
@angular/http                                7.2.16
@angular/localize                           9.0.5
@angular/material                         9.1.0
@ngtools/webpack                        9.0.4
@schematics/angular                    8.3.25
@schematics/update                    0.803.25
rxjs                                                6.5.4
typescript                                     3.7.5
webpack                                      4.41.2**
-------------------------------------------------------------------------------------------------------

Thank You.

**Comment by pkozlowski-opensource** [comment]
> Can anyone please help me in this?

Sure, as long as you can share a reproduce scenario so we can investigate.

**Comment by Sid13Kulat** [comment]
Actually it's started working again. Thank you.

**Comment by EvtK** [comment]
@Sid13Kulat can you share what you have changed to get it working again, since I'm facing exact the same issue?

**Comment by jonathanlie** [comment]
Im facing the exact same issue here. Dev build (ng serve) works perfectly, with AOT and Ivy, on application project consuming a library project.

**Comment by maxime1992** [comment]
Anyone found a solution? Also facing this...

**Comment by maxime1992** [comment]
Here are all the info I can gather around this: 
```
core.js:6237 ERROR TypeError: Cannot read property 'pure' of null
    at isPure (core.js:37157)
    at Module.ɵɵpipeBind1 (core.js:37055)
    at ErrorModalComponent_Template (error-modal.component.html:3)
    at executeTemplate (core.js:12098)
    at refreshView (core.js:11945)
    at detectChangesInternal (core.js:13588)
    at ViewRef.detectChanges (core.js:15225)
    at error-modal.component.ts:66
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41814)
```

So apparently the following in red can be null: 

![image](https://user-images.githubusercontent.com/4950209/80810496-de1fe980-8bbb-11ea-8171-5f6608045f11.png)

How do I end up with this error:

We've got a sandbox component to test a few things out and one of them is to make sure that we're correctly handling error. So when I click on a button, it calls a method which runs `throw new Error(`Dummy sandbox error`);`.

From here, our custom global error handler is supposed to open a modal and show a message.

The modal can't open (because everything is already broken at that stage).
