### ISSUE TITLE
DI error when using JIT from an AoT-compiled Ivy project

### ISSUE THREAD

**Issue by anhallbe** [angular/angular#35908]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core and/or @angular/compiler

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8 & 9 (without Ivy)

### Description

 An error is thrown when trying to load a component from an external service. The js module is fetched with SystemJS, and then compiled (JIT) using the @angular/core Compiler. The error is thrown when the component is added to the view (using ViewContainerRef.createComponent()). The problem only occurs when the component is not already compiled with AOT (ivy), xor if the project is not configured to use AOT.

## 🔬 Minimal Reproduction

 https://github.com/anhallbe/repro-app

1. Clone the repo
2. run `ng serve`
3. Follow instructions in the template

Demo:
![di-dynamic-component](https://user-images.githubusercontent.com/4991954/76088356-2eae0880-5fb8-11ea-8786-9f94c00264c2.gif)

## 🔥 Exception or Error
<pre><code>

Error: This constructor is not compatible with Angular Dependency Injection because its dependency at index 0 of the parameter list is invalid.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.5
Node: 12.13.1
OS: win32 x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@ngtools/webpack                  9.0.5
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by alxhub** [comment]
Hi @anhallbe,

Thanks for the well written and straightforward reproduction. I debugged through it and noticed that `reflect-metadata` is not loaded. This library is required for Angular JIT and is an essential part of how DI in JIT works. I added `import 'reflect-metadata';` to `polyfills.ts`, and the reproduction then was able to import and instantiate the JIT component with DI.

Cheers!
-Alex

**Comment by anhallbe** [comment]
Thank you @alxhub !
