### ISSUE TITLE
DatePipe works on Chrome but not on Firefox

### ISSUE THREAD

**Issue by cesco69** [angular/angular#35905]
# 🐞 bug report

### Affected Package
- Angular 8 
- Angular 9

### Description
This formatting with date pipe works on Chrome but not on Firefox:
```html
{{ "06-03-2020 11:04:06" | date:'dd/MM/yy' }}
```

## 🔬 Minimal Reproduction

Open this demo with Chrome and Firefox
https://stackblitz.com/edit/angular-kfuwc4
on Firefox raise an exception:

> ERROR
> Error: InvalidPipeArgument: 'Unable to convert "06-03-2020 11:04:06" into a date' for pipe 'DatePipe'

## 🔥 Exception or Error
> ERROR
> Error: InvalidPipeArgument: 'Unable to convert "06-03-2020 11:04:06" into a date' for pipe 'DatePipe'

## 🌍  Your Environment

```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.5
Node: 12.15.0
OS: win32 x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.5
@angular-devkit/build-angular      0.900.5
@angular-devkit/build-optimizer    0.900.5
@angular-devkit/build-webpack      0.900.5
@angular-devkit/core               8.3.8
@angular-devkit/schematics         8.3.8
@angular/cdk                       9.1.1
@angular/material                  9.1.1
@angular/material-moment-adapter   9.1.1
@ngtools/webpack                   9.0.5
@schematics/angular                8.3.8
@schematics/update                 0.900.5
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
```

**Comment by jnizet** [comment]
It only works by accident on Chrome. The value passed to the pipe is supposed, as per [the documentation](https://angular.io/api/common/DatePipe#input-value), to be a Date object, a number (of milliseconds), or an ISO string (something like `"2020-03-06T11:04:06.000Z"`).

**Comment by AndrewKushnir** [comment]
Hi @cesco69, thanks for reporting the issue. As @jnizet mentioned, the date that you try to use with `date` pipe doesn't seem to be a valid ISO date string and as a result it can not be converted. Please update the date format that you use for the pipe input and feel free to reopen the ticket if the problem still exists. Thank you.
