### ISSUE TITLE
[i18n] Support for ICU expressions in $localize (for programmatic use)

### ISSUE THREAD

**Issue by PapaNappa** [angular/angular#35912]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/localize.

### Description

With the new `$localize` in Angular 9, we are finally able to do translations in code.

To borrow from ["i18n with $localize in TypeScript code" of this blog post](https://blog.ninja-squad.com/2019/12/10/angular-localize/), you can now write this:
```
title = $localize`Hi ${this.name}! You have ${this.users.length} users.`;
```

(`ng xi18n` currently does not extract these strings, you have to add them manually to your translation files, but that's not what this feature request is about.)

Unfortunately, ICU expressions are currently not handled by $localize.
For instance, ideally, you would want to write
```
title = $localize`Hi ${this.name}! You have {${this.users.length}, plural, =0 {no users} =1 {one user} other {${this.users.length} users}} users.`;
```
But this does not work, and the ICU expression is returned literally.

As far as I understand, ICU expressions are currently handled only by compiler internals.
i18n strings with ICU expressions in the template are actually transformed to multiple `$localize` calls (one for the whole string, one for each ICU expression). `$localize` returns the ICU expressions as-is (but with expressions replaced by special markers), and the ICU expressions are handled by ivy in @angular/core.

### Describe the solution you'd like
 
I could see two possible solutions - totally from a developer's perspective:

`$localize` also supports evaluation of ICU expressions, as in my example above.

Alternatively, `$localize` is left as-is as a primitive, and a new `i18n` function (in the sense of @ocombe's [ngx-translate/i18n-polyfill](https://github.com/ngx-translate/i18n-polyfill)) is introduced that handles ICUs. (And can maybe also serve as a marker for automatic text extraction).

Ideally, the solution works both for compile-time inlining as well as for runtime translatations.

Although this would be another feature request (with probably lower priority, that's why I have not opened such a proposal), the implemented solution should not prevent to add dynamic runtime-translations in the future, i.e. where the translation id is composed at runtime (e.g. `$localize':@@${id}:'` or `i18n({id})`).

### Describe alternatives you've considered
 ngx-translate's -messageformat-compiler requires the CSP unsafe-eval, which is not an option in productive environments.

**Comment by petebacondarwin** [comment]
Do you have a specific requirement for it to be ICU based?
One benefit of `$locaize` is that it supports nested blocks out of the box, so if you had a suitable helper function, `plural()` you could do something like:

```
title = $localize `Hi ${this.name}! You have ${
    plural(this.users.length. {
      0: $localize `no users`,
      1: $localize `one user`,
      other: $localize`${this.users.length} users`,
}.`;
```

and `plural()` might be something like:

```
function plural(value, options) {
  // Handle 0, 1, ... cases
  const directResult = options[value];
  if (directResult !== undefined) { return directResult; }
  // handle zero, one, two, few, many
  // ...
  return options.other;
}
```

**Comment by ocombe** [comment]
oh that's a good point, since ICU expressions are parsed within `ɵɵi18n`, `$localize` doesn't know anything about ICUs...
One more thing to add to `Locl` :D

**Comment by PapaNappa** [comment]
@petebacondarwin That's actually a nice pattern with `$localize`, I did not think of that before.

With that in mind, I guess my underlying assumption, or the implicit feature request, is what @ocombe points out.
Currently, also with that pattern, translations with _n_ ICUs need _n+1_ translation string.

It would be much better if you can have a simple line in a translation:

`translationId = Hi {$name}! You have {{$userCount}, plural, =0 {no users} =1 {one user} other {{$userCount} users}} users.`

And then something along the line of

```
$localize`:@@${translationId}:`({name, userCount})
```

But I guess that's probably too much to ask for `$localize`?
Maybe then a separate `i18n` function is better suited - or Angular decides that's a gap third parties like Locl should fill in.

If you want, I can detail our use case a bit more.
But basically, my last line of code is what we would like to have.
That is in principle already available with nginx-translate; but I generally prefer Angular's `$localize`/i18n approach.
* It just neatly integrates in the template, where you can have the actual texts in the 'development' language, without cluttering the templates with translation ids
* It provides ICUs (in templates) without unsafe-eval

That said, we would like to load translations by a computed key (these keys are finite and the set is well-defined).
In this sense, nginx-translate provides the better features, but it does not support ICUs as well, and does not integrate in the templates so neat. And of course, having to deal with a single library for i18n would be great. :)

**Comment by petebacondarwin** [comment]
I don't think this is something we can support in the core `$localize` since it would add a lot of weight to the `@angular/localize` package.

**Comment by ocombe** [comment]
@petebacondarwin don't you think we could reuse some of the code from core/render3 that deals with ICUs ?

**Comment by petebacondarwin** [comment]
Let me see...

**Comment by petebacondarwin** [comment]
Well, there is the ICU parsing code `extractParts()` etc in `core/src/render3/i18n.ts` but there would need to be quite some additional work done to support this within `$localize.translate()`.

Will consider a PR if it is not too heavy.

**Comment by PapaNappa** [comment]
I will close this issue, as I think fixing this specific issue will not really make things better.

There are really two main use-cases which are needed by this - or some similar - functionality.
Both use-cases require much more changes, this PR is just some part of this.

For the record, here are some considerations.
Bear in mind that these are just my thoughts, from a Angular developer's perspective with only partial insight in (but much interest in) Angular's internals.

There are also some questions on how the Angular teams sees the role/future of i18n in Angular. Some insight/clarifications would be welcome.

## Simpler translation strings

Currently, embedding ICUs in `i18n` tags generates _n_+1 translation strings.
Having one string would be a much better translation experience, as the translation files would be cleaner and thus easier to translate.

However, integrating ICUs in the `$localize` calls used by `i18n` tags seems to require a lot of changes:
* Basically, the currently generated code of individually translating each ICU with `$localize` and then composing the result, would be unnecessary. If this logic is handled in `$localize`, the code would be duplicated.
* Still, there are cases where you might want to use ICUs _without_ i18n in single-language applications. So, `$localize` is not the only place where this needs to be handled.

## Using `$localize` with compile-time inlining in code

Currently, we can have `i18n` tags in the template. These are static strings and handled quite well by Angular:
* ICUs are supported
* all translatable string can be automatically extracted with `ng xi18n`
* translations are resolved automatically during compile time and thus embedded in the build

With Angular 9, `i18n` tags are resolved with `$localize`.
Now that `$localize` is an [official, exported, documented  function/tag](https://github.com/angular/angular/blob/0d806c84e2df18331ec075e3f57a6254f21eaff8/packages/localize/src/localize/src/localize.ts#L46-L137), it can also be used programmatically. The documentation also conveys the intent that this can indeed by used programmatically.

However, the support in programmatic use (think `this.title = $localize`:@@title:Title`) is limited:
* ICUs are not supported (what this issue is about)
* translatable strings are not automatically extracted during `ng xi18n`
* translations *are* still automatically resolved during compile time, which is good.

So although using `$localize` in code is now made possible, there is not as near the same experience as using `i18n` in templates.

So, for this use-case, this issue is only a minor issue, really.
With the proposal of [nested `$localize` calls](https://github.com/angular/angular/issues/35912#issuecomment-595867379), automatically extracting these calls with `ng xi18n` is the main issue here.

So, is this use-case something that will be given (even) more attention to in the future?

## Using `$localize` with runtime-evaluation in code

Here I mean my example above of building the translation key/id at run-time. The usual use-case here is generic (but probably domain-specifc) code that wants to retrieve translations at run-time.
All texts/keys are known in advance, but retrieved at only a few places in code.

Without ICUs, this can currently be achieved, in principle, by constructing the arguments for `$localize` dynamically, like this (adding placeholders is also possible with a few more lines):
```
const s = `:@@${t}:${t}`;
const templatedParts = Object.assign([s], { raw: [s] });
return $localize(templatedParts, []);
```

However, there are a few issues with this approach as well:
* Most importantly, the `$localize` function/'polyfill' is removed during AOT compilation. This totally makes sense for applications that do not use runtime-evaluation. But currently there is no way to avoid this optimisation. Since this is [officially supported](https://github.com/angular/angular/blob/0d806c84e2df18331ec075e3f57a6254f21eaff8/packages/localize/src/localize/src/localize.ts#L125-L127), I would consider this a separate bug. Of course the work-around is to load the polyfill manually somehow, but this is probably not the official way to do it
* Constructing all these intermediate objects for `$localize`, only to have `$localize` parse and split the parts again, is not the optimal performance.

That would mean that, for runtime-evaluation, we want a different i18n-function. But then, ICU handling also needs to by handled by this new function.

Is runtime-evaluation something that the Angular team wants to support and extend in the future?


In total, also after having a look at the [implementation documentation](https://github.com/angular/angular/blob/master/packages/core/src/render3/i18n.md), a single PR will not fix this issue. And at least I am not in the position to deliver such a PR, as I would need a lot of time to dive into the Angular internals, not to mention the plethora of constraints and considerations.

So I think what I want to say is that a) the Angular teams is making an amazing job delivering the experience we have right now, and b) changing the current implementation requires not just implementations, but major architectural changes, it seems - nothing this issue can address.

**Comment by petebacondarwin** [comment]
Hi @PapaNappa - thanks for this extensive write up. I am very interested to engage with you to discuss some of these design goals. I will respond here in the next few days but I will also reach out to you via email to have a more detailed discussion.

**Comment by AndrewKushnir** [comment]
Just as an idea for further discussion: ICU parsing in TS code can be implemented as a separate/additional function, for example as it's done with Closure Compiler i18n helpers (see [docs here](https://google.github.io/closure-library/api/goog.i18n.MessageFormat.html)):
```
const MSG_LABEL = goog.getMsg('{count, plural, =0 {zero} other {more}}');
const formatter = new goog.i18n.MessageFormat(MSG_LABEL);
const final = formatter.format({count: 10});
```
With `$localize` it might look like this:
```
const label = $localise`{count, plural, =0 {zero} other {more}}`;
const final = formatICU(label, {count: 10});
```
In this case the `$localize` function will serve its main purpose - bring translated string into the app (+ support basic interpolations) without carrying additional weight of having (non tree-shakable) extra code in it. Existing compile-time inlining would not require any changes in this case as well. The `formatICU` function will be very focused on ICU case and will perform runtime parsing and evaluation of ICU expression (similar to what Ivy does) and we may consider adding `formatICU` function into `@angular/localize` package in the future.

Thank you.

**Comment by kemsky** [comment]
@PapaNappa, can't you use `intl-messageformat` to process result of $localize?

**Comment by PapaNappa** [comment]
A separate `formatICU` function - maybe in the form of `intl-messageformat` - sounds like a good idea. That should work and the boilerplate isn't too much.

Then, you only need to be aware that this can cause confusion for both programmers and translators:
Programmers might confuse using `${count}` in bare `$localize` with `{count}` in bare ICUs. In the template ICU syntax, it is consistently `{{count}}`, whether the variable is interpolated in the template or inside the ICU.
Translators need to be aware of using `{$count}` vs. `{count}`.

And thanks @kemsky for pointing out `intl-messageformat`.
That opens yet another rabbit hole (oh dear ^^): Intl/messageformat supports number/date/etc. formatting (`{expires, date, short}`).
If `formatICU` is implemented, it would probably be nice if it also supports this formatting.
Yes, we have `formatDate` etc. and could interpolate the result in the string. But the downside is that you have to explicitly specify the locale, and then translators could not define individual formats when required.
If it supports this formatting, it should be consistent with the formatting of `DatePipe/formatDate` etc.

I guess the downside of using `intl-messageformat` is that it uses the Browser's locale formats (which is actually quite a good thing), but this might produce a different formatting than Angular's `DatePipe` for instance.

**Comment by ocombe** [comment]
The `DatePipe` uses dates from [CLDR](http://cldr.unicode.org/), which is also what the browsers use. The format should be the same, except in old browsers that have bugs (IE...) or haven't been updated with the latest locale data.
