### ISSUE TITLE
node sqlite3 package does not work on a simple angular 9-app

### ISSUE THREAD

**Issue by zuoshuluHTC** [angular/angular#35915]
https://stackoverflow.com/questions/60567717/node-sqlite3-package-does-not-work-on-a-simple-angular-9-app

I post my issues on stackoverflow above, I hope this is the better place to get a solution for angular sqlite support

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
