### ISSUE TITLE
There is no mention for entryComponents is Deprecated in "dynamic component loader" Chapter

### ISSUE THREAD

**Issue by OmarioHasan** [angular/angular#35926]
# 📚 Docs or angular.io bug report

### Description

I think it must update this chapter that using entryComponents in this part
https://angular.io/guide/dynamic-component-loader
and mention that it's deprecated ('https://angular.io/guide/deprecations')
and update the code samples if it needs

### What's the affected URL?**
https://angular.io/guide/dynamic-component-loader

## 📷Screenshot
![image](https://user-images.githubusercontent.com/8146344/76138134-4d121380-604d-11ea-92c5-be32c26d1dbe.png)

**Comment by kapunahelewong** [comment]
Status: Docs team needs to update doc as above.
