### ISSUE TITLE
Get instance of a pipe class only by a given pipeName.

### ISSUE THREAD

**Issue by yassine-klilich** [angular/angular#35939]
I spend hours to find how i can get object instance of a pipe class only by the name of the pipe.
For example :
`let uppercasePipeInstance: UpperCasePipe = getPipeByName(pipeName);
uppercasePipeInstance.transform('some params');
`
-----------> Is that possible in angular ??
-----------> How can I achieve this even if it was complicate to do it ??

**Comment by petebacondarwin** [comment]
@yassine-klilich - this is really a support request and not an issue with Angular, so you should really be asking on the mailing list, forums or chat rooms.

I assume that you mean the `name` as in the property on the `@Pipe({name: ...})` decorator? This is local to the `NgModule` where the pipe is declared or imported. So the name only makes sense in the context of an `NgModule` and so effectively a component's template. In AOT mode, all the pipe usage in the templates is compiled down to refer directly to the class and so is not used at runtime (unlike in AngularJS).

I think your best bet would be to inject the pipes that you care about into your `NgModule` of choice that declares or imports them and you can then access them by their member name:

```ts
@NgModule({...})
export class AppModule {
  constructor(readonly currency: CurrencyPipe, readonly percent: PercentPipe, ...) {}

  getPipe(name: string): PipeTransform {
    return (this as any)[name];
  }
}
```

Closing as this is not an Angular issue.

**Comment by yassine-klilich** [comment]
@petebacondarwin - thanks for your help
