### ISSUE TITLE
bug(docs): "Your First App" on stackblitz does not work

### ISSUE THREAD

**Issue by KostyaTretyak** [angular/angular#35947]
# 🐞 bug report

### Description

Clicking on [Click here to create the ready-made sample project in StackBlitz](https://angular.io/generated/live-examples/getting-started-v0/stackblitz.html) from https://angular.io/start page will redirect you to a non-working version of the example.

## 🔬 Minimal Reproduction

Once we are on the page on stack blitz, you need to click on the `checkout` button, and then see console error:

```text
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'cart'
Error: Cannot match any routes. URL Segment: 'cart'
    at ApplyRedirects.noMatchError (apply_redirects.ts:112)
    at CatchSubscriber.eval [as selector] (apply_redirects.ts:89)
```

**Anything else relevant?**
... And why is this example still running on Angular v8?

**Comment by sonukapoor** [comment]
@KostyaTretyak / @petebacondarwin I just tried this, but I am not able to reproduce it.

**Comment by KostyaTretyak** [comment]
@sonukapoor, did you click on the `Checkout` button on the stackblitz?

**Comment by sonukapoor** [comment]
@KostyaTretyak Just did and was able to reproduce it. I missed that part in your post. Thanks for pointing it out. I will take a look.

**Comment by sonukapoor** [comment]
@KostyaTretyak The `cart` feature is added much later in the start guideline, therefore, I have removed the `routerLink` in the initial setup. Thanks for pointing this out.
