### ISSUE TITLE
Same code, different behavior in (drop) directive

### ISSUE THREAD

**Issue by KannaKim** [angular/angular#35946]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?

no

### Description

https://stackblitz.com/edit/angular-9wqipt //minimal reproduction

I'm making a simple website when user drag an element and drop it on another element the 

context of each element swap with each other. 

However, the problem is in `(drop)="BuggyonDrop($event)"` $event is giving the DragEvent on dragged element.

 In other words, if I drag `<p id="unique0">` and drop it on `<p id="unique2">` the event info on drop() is `<p id="unique0">`

but the weird part is, when I console.log event.target.id the result is unique2. 

additionally, if I put debugger right below the console.log the result is fine (working as intended)

so it's really weird and inconsistent.

I had to spend hours and hours to find the cause and workaround. turns out not using *ngFor was a solution (have to put data-binded-value manually one by one). 

**Anything else relevant?**

tested on chrome and opera

**Comment by KannaKim** [comment]
![image](https://user-images.githubusercontent.com/47150013/76184621-9de35280-619a-11ea-834b-ab93cf21967e.png)

console.log("BuggyonDrop")
console.log(event)
console.log(event.target)
console.log(event.target.id)

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
