### ISSUE TITLE
Ability to bind to any DOM property for storing arbitrary data

### ISSUE THREAD

**Issue by shawnhuang2015** [angular/angular#35945]
Hi,
    I got this error after I upgraded my app to angular 9 when the AOT is enabled.  It is working in JIT.

   Error:  Can't bind to '_data' since it isn't a known property of 'span'.

Code snippet:
`   <span #tmpSpan
                *ngFor="let word of wrods; let i = index; trackBy: trackWord"
                class="__word"
                [attr.key]="i"
                [_data]="word"
                [ngStyle]="getOnWordStyle(word, tmpSpan)"></span>
`
Currently, I can only use a directive with Input to assign the data object to the native element. 
` this.el.nativeElement._data = this._data; `. But I am worry about the performance impact. Is there a way to disable this validation somewhere?

**Comment by JoostK** [comment]
This _should_ have also been an error prior to Angular 9, I'm not sure why that would not have been the case. Can you provide a repro in e.g. StackBlitz to show that it used to work in Angular 8, but not in 9?

I think you're trying to set the `_data` attribute on the `span` element? In that case, you should use an attribute binding instead of a property binding using `[attr._data]="word"`.

As a friendly reminder, please fill out the appropriate issue template instead of deleting it wholesale.

**Comment by shawnhuang2015** [comment]
Sorry about that. I upgraded Angular from 7.1 to 9.0. In my case, _data is an Object. If I use an attribute binding, it will be converted to a string.

**Comment by pkozlowski-opensource** [comment]
>  In my case, _data is an Object

Oh, this is an interesting use-case! Would you mind sharing _why_ are you trying to write an arbitrary JS object the `_data` property of an element? This is not a standard HTML / DOM property so I'm curious as to why you are doing this. Is it to store some data on the DOM and read it later? Is it to work some 3rd party libraries manipulating DOM directly?

**Comment by shawnhuang2015** [comment]
> > In my case, _data is an Object
> 
> Oh, this is an interesting use-case! Would you mind sharing _why_ are you trying to write an arbitrary JS object the `_data` property of an element? This is not a standard HTML / DOM property so I'm curious as to why you are doing this. Is it to store some data on the DOM and read it later? Is it to work some 3rd party libraries manipulating DOM directly?

Yes. I store some data on the DOM and read it later. I am implementing a text editor in which I manipulate a content editable DOM directly by keyboard interaction.

**Comment by JoostK** [comment]
By the way, you can probably workaround this issue by using the `NO_ERRORS_SCHEMA` schema in the NgModule that declares the component:

```ts
@NgModule({
  schemas: [NO_ERRORS_SCHEMA],
})
```

**Comment by shawnhuang2015** [comment]
> By the way, you can probably workaround this issue by using the `NO_ERRORS_SCHEMA` schema in the NgModule that declares the component:
> 
> ```ts
> @NgModule({
>   schemas: [NO_ERRORS_SCHEMA],
> })
> ```

I have my module as this `schemas: [NO_ERRORS_SCHEMA, CUSTOM_ELEMENTS_SCHEMA]`
But it still reports errors.

**Comment by pkozlowski-opensource** [comment]
Just for the record: it was the error in Angular <9 with View Engine: https://stackblitz.com/edit/angular-xsqiqo?file=src%2Fapp%2Fapp.component.html so this is _not_ a regression.

**Comment by JoostK** [comment]
@pkozlowski-opensource The crux seems to be the `NO_ERRORS_SCHEMA`, adding that to `AppModule` in your example hides the issue. But I'm seeing the same behavior on ng-run.com with Ivy AOT enabled, where no error is produced as soon as `NO_ERRORS_SCHEMA` is added to the NgModule.

> > By the way, you can probably workaround this issue by using the `NO_ERRORS_SCHEMA` schema in the NgModule that declares the component:
> > ```ts
> > @NgModule({
> >   schemas: [NO_ERRORS_SCHEMA],
> > })
> > ```
> 
> I have my module as this `schemas: [NO_ERRORS_SCHEMA, CUSTOM_ELEMENTS_SCHEMA]`
> But it still reports errors.

@shawnhuang2015 I can't find an obvious bug that would cause this not to work, and I can't reproduce the issue in a small example. Can you provide more information, or ideally a minimal working example (e.g. on ng-run.com)

**Comment by shawnhuang2015** [comment]
> o

In

**Comment by shawnhuang2015** [comment]
> Just for the record: it was the error in Angular <9 with View Engine: https://stackblitz.com/edit/angular-xsqiqo?file=src%2Fapp%2Fapp.component.html so this is _not_ a regression.

By adding [NO_ERROR_SCHEMA], it works in ^8. But not ^9. Check this out.
https://stackblitz.com/edit/angular-yg2gwh

**Comment by shawnhuang2015** [comment]
> @pkozlowski-opensource The crux seems to be the `NO_ERRORS_SCHEMA`, adding that to `AppModule` in your example hides the issue. But I'm seeing the same behavior on ng-run.com with Ivy AOT enabled, where no error is produced as soon as `NO_ERRORS_SCHEMA` is added to the NgModule.
> 
> > > By the way, you can probably workaround this issue by using the `NO_ERRORS_SCHEMA` schema in the NgModule that declares the component:
> > > ```ts
> > > @NgModule({
> > >   schemas: [NO_ERRORS_SCHEMA],
> > > })
> > > ```
> > 
> > 
> > I have my module as this `schemas: [NO_ERRORS_SCHEMA, CUSTOM_ELEMENTS_SCHEMA]`
> > But it still reports errors.
> 
> @shawnhuang2015 I can't find an obvious bug that would cause this not to work, and I can't reproduce the issue in a small example. Can you provide more information, or ideally a minimal working example (e.g. on ng-run.com)

Please try this repo. I create a new angular project from scratch by using the latest Angular Cli. https://github.com/shawnhuang2015/playground
`schemas: [NO_ERRORS_SCHEMA, CUSTOM_ELEMENTS_SCHEMA]` help to pass the compiling. But I can still have a warning in the console of Chrome. (`Can't bind to '_data' since it isn't a known property of 'span'.`). Also `_data` is undefined of my target span element. 
If I set AOT to be false. It works as expected.

**Comment by shawnhuang2015** [comment]
> Just for the record: it was the error in Angular <9 with View Engine: https://stackblitz.com/edit/angular-xsqiqo?file=src%2Fapp%2Fapp.component.html so this is _not_ a regression.
Thanks for creating the examples. The AOT should be true. I have tried it your example, both Angular 8 and 9 work without any warning at run time or compile errors. But when I run it locally with the same code. I still got the error in Angular 9.

**Comment by shawnhuang2015** [comment]
Currently, my temporary solution is using a directive to do the binding. 
`@Directive({
  selector: '[appBindingData]'
})
export class BindingDataDirective implements OnInit {
  @Input() _data: any;

  constructor(private el: ElementRef) {}

  ngOnInit() {
    this.el.nativeElement._data = this._data;
  }
}`
