### ISSUE TITLE
Have no access to an instance of a component from directive via ``ContentChild`` (Angular 9)

### ISSUE THREAD

**Issue by michael-vasyliv** [angular/angular#35942]
# 🐞 bug report

### Affected Package
@angular/core => ContentChild

### Is this a regression?
not sure

### Description
ContentChild on a property has value undefined

## 🔬 Minimal Reproduction
https://github.com/michael-vasyliv/content-child

Steps:

1. ``npm i``
2. ``npm run start``
3. open console
4. see
```
where is my {@link CdkVirtualScrollViewport} bro???
Content:  undefined
```

## 🔥 Exception or Error
no error

## 🌍  Your Environment
Windows 10

**Angular Version:**
```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 9.0.5
Node: 12.13.1
OS: win32 x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@angular/cdk                      9.1.1
@ngtools/webpack                  9.0.5
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```

**Anything else relevant?**
Here is an example of working code in Angular 8.x.x
https://stackblitz.com/edit/angular-kw59pk
in this demo we use directive ``ngxVirtualSwiper`` that gets the instance of ``CdkVirtualScrollViewport``.
Here is the source of the directive https://github.com/michael-vasyliv/ngx-virtual-swiper/blob/master/projects/ngx-virtual-swiper/src/lib/ngx-virtual-swiper.directive.ts

**Comment by pkozlowski-opensource** [comment]
This is a known and deliberate breaking change in Angular 9 with ivy enabled. In https://angular.io/guide/ivy-compatibility we can read:

> @ContentChild and @ContentChildren queries will no longer be able to match their directive's own host node (previously, these queries would match the host node in addition to its content children).

You will have to modify your directive so the `CdkVirtualScrollViewport` is not queried but obtained using different means (injecting it in a constructor seems like the best approach in this case).

Closing as with Angular 9 this is the expected behaviour (we consider previous behaviour as a bug).
