### ISSUE TITLE
Getting the context of the template inside of which my component has been rendered

### ISSUE THREAD

**Issue by EmaGht** [angular/angular#35957]
# 🚀 feature request

### Relevant Package
@angular/core

### Description
So i posted a [question ](https://stackoverflow.com/questions/60398827/getting-the-context-of-the-template-inside-of-which-my-component-has-been-render/60418016#60418016)about this on StackOverflow some time ago and since until now i had 0 question/comments and had to came up with a pretty ugly hack i think it's time to bring this to your attention.

Without repeating everything i've already said in that question, my request is if we can please have a non hacky way to retrieve the context of the template inside of which a component has been rendered

### Describe the solution you'd like
The ViewEngine solution to this problem actually sounds nice:

`(<any>this._viewContainer)._view.context`

Can we please have this on Ivy also?

### Describe alternatives you've considered
Ugly Alternative 1: `(<any>this._viewContainer)._hostView.debug.context`
Ugly Alternative 2: `(<any>this._viewContainer)._hostView.find(t => t && !!t.$implicit)`

**Comment by Airblader** [comment]
IMHO the design of your component is odd, but if you insist on this structure I would recommend you simply create a custom injector when you instantiate the template. Then your simple-item component can inject the item and no input binding is needed.

**Comment by EmaGht** [comment]
I think you are confusing the word "odd" with the word "sexy"
I mean... just look at this glory:

``
<ng-table [(ngModel)]="Items">
	<ng-template #header>
		<th ng-th="ID">ID</th>
		<th ng-th="DESC">Description</th>
	</ng-template>
	
	<ng-template #body let-itm>
		<td ng-td="ID" [RouterLink]="['/pages/itm/item_details', { idItem: itm.id }]">{{itm.id}}</td>
		<td ng-td="DESC">{{itm.desc}}</td>
	</ng-template>
</ng-table>
``

Nothing to write or configure, a table that just works with paging and all the goodness in this world without having to clutter your .ts with

`Headers = [...]` and
`Rows = [...]` and
`TypicalTableConfig = {... }`

The custom injector way is a way to solve this of course but since the information i was looking for was kind of "near home" (i mean... i'm inside a template who already has this information inside, why should i re-provide it?) i was hoping a direct access for this could be taken into consideration :)

**Comment by Airblader** [comment]
> I think you are confusing the word "odd" with the word "sexy"

The reason I found it odd is because you're mixing two approaches: either passing the item as an input or using content projection. You somehow want to do both. But tastes differ. :-)

The problem with accessing the context like that is IMHO that 1) it is entirely type-unsafe and 2) the compiler cannot figure out if and which context information are accessed from somewhere in the tree. This means we'd either lose some aggressiveness in the optimization process (not mangling names) or it would simply not work in a production build. Both, to me, are reasons not to allow this – apart from the fact that to me it feels odd to access the context of the template of the parent.

The custom injector would make things much more explicit and IMHO nicer.

**Comment by kemsky** [comment]
@EmaGht, see #14935. The problem here is that ng-template does not belong to ng-table context, so you don't have any non-explicit way to pass data to ng-template.

**Comment by EmaGht** [comment]
> 
> 
> @EmaGht, see #14935. The problem here is that ng-template does not belong to ng-table context, so you don't have any non-explicit way to pass data to ng-template.

Problem is not quite that, what i'm trying to do is accessing the `itm` item declared here: 
`<ng-template #body let-itm>`
from the many `<td ng-td="...">...</td>` inside of it

> The reason I found it odd is because you're mixing two approaches: either passing the item as an input or using content projection. You somehow want to do both. 
Actually it's only the latter, what i need is content projection, but the context on which this projection is made contains informations i need so i need a way to retrieve that. setting an `[Context]` input on every ng-td would actually fall in the category of "want to do both" but what i really want is just being able to get out of here with content projection alone.
That's why i think it would be cool to access the template's context. So i don't have to rely on both projection and inputs

>it is entirely type-unsafe 
I entirely agree but let's be real... take for example `onChange($event.target.value)`. This is already type-unsafe and it's way simpler than what i'm trying to setup here...

>lose some aggressiveness in the optimization process (not mangling names) 
I feel this, but we are talking about one context. Unless this is a monster class i don't think there's much to lose

>or it would simply not work in a production build
Can confirm my current, ugly workaround works in prod/dev VE/IVY and any combination of the 4

>The custom injector would make things much more explicit 
This is probably a limit of mine but i really cannot see anything nice/explicit in declaring a new injector for every table in your frontend to walk around the fact a `ViewContainerRef`'s context cannot be directly accessed (despite being there in some internals). This is probably a tastes thing :3

**Comment by pauldraper** [comment]
> simply create a custom injector when you instantiate the template 

AFAIK you cannot use a custom injector when creating a view from a template.

**Comment by pieterdegraeuwe** [comment]
people seem to say you can fix this with a custom Injector. I also think using custom injectors would solve most of these issues.
BUT, really, can anyone tell me how you render a template and let it use a custom injector? 
I know one can render a component with a custom injector (ngComponentOutlet), but this is in my opinion not possible with a ngTemplateOutlet)..

If someone knows how to do this.. please, let me know ;-)

**Comment by EmaGht** [comment]
[Disclaimer: Kind of OT]

@pauldraper @pieterdegraeuwe 
I assumed it could be possible by wrapping all your stuff in a custom component that registers your custom injector for the projected child, which in turn can now Inject the token provided by the top level component and use it.

Conceptually something like:

``
<ng-template #body let-itm>
    <context-provider-component [Context]="itm">
	<td ng-td="ID" [RouterLink]="['/pages/itm/item_details', { idItem: context.id }]">{{context.id}}</td>
	<td ng-td="DESC">{{context.desc}}</td>
    </context-provider-component>
</ng-template>
``

ContextProviderComponent would get _itm_ as an Input and dynamically set it in the Injection tree (I'm not sure this is 100% possible, but doesn't seem that impossible either... hopefully someone can test it :D ).
Once you have it in the injection tree registered as a token you can just take the token from the _ng-td_ s

Again, this is just an idea, i don't know if it's doable, but if it is i would expect to look like it

**Comment by EmaGht** [comment]
My ugly solution has a problem in case an "*ngIf" is used, as that will be the first context found.
In this case, VE holds the information on the context i want in viewContainerParent, while IVY holds it in a second level hierarchy, so managing to handle the ngIf case becomes...

```
//View Engine context lookup
let context = (<any>this._viewContainer)._view ? 
                          (<any>this._viewContainer)._view.context.ngIf ? 
                              (<any>this._viewContainer)._view.viewContainerParent.context.$implicit
                              : (<any>this._viewContainer)._view.context.$implicit
                          : null;

//Ivy context lookup
if (context == null) {
    var array = (<any>this._viewContainer)._hostLView;
    for (let i = 0; i < array.length; i++) {
        let item = array[i];
        if (item && item.$implicit && !item.ngIf) {
            context = item.$implicit;
            break;
        }

        //Second level search for the real context in case the first one we find is an ngIf
        if(item && item.length && item.length > 0)
        {
            for (let ii = 0; ii < item.length; ii++) {
                let iitem = item[ii];
                if (iitem && iitem.$implicit && !iitem.ngIf) {
                    context = iitem.$implicit;
                    break;
                }
            }

            //Context found in the internal cycle, break the external one
            if(context)
                break;
        }
    }
}
```

I would really love a non hacky way to do this

**Comment by pkozlowski-opensource** [comment]
@EmaGht we've reviewed this issue during the team's triage meeting and decided that this is not something we want to implement. There are 3 explicit ways of passing info to a component:
* inputs
* content
* DI

We don't want to add another way that would be implicit.
