### ISSUE TITLE
Angular 9 entryComponents with Ivy disabled 

### ISSUE THREAD

**Issue by boyanstanchev** [angular/angular#35955]
**Did this behavior use to work in the previous version?**
Yes, this worked in Angular 8

### Description
I've updated the project to Angular 9 and everything is working almost as expected, but I had to disable Ivy for now. I'm using Nebular https://akveo.github.io/nebular/.

After the update I noticed that using dialogService produces the error above even though the component is added to entryComponents.

## 🔬 Minimal Reproduction
https://github.com/boyanstanchev/ivy-entryComponents-bug
Just disable and enable Ivy from **tsconfig.app.json** to reproduce. After downgrading Angular to version 8 everything works as expected.

## 🔥 Exception or Error
<pre><code>
ERROR Error: No component factory found for SimpleDialogComponent. Did you add it to @NgModule.entryComponents?

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@angular/cdk                      9.0.0
@ngtools/webpack                  9.0.5
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by kara** [comment]
@boyanstanchev The repo you linked has many modules and components, so it's difficult for us to pare it down. Can you provide a minimal repro (e.g. as close to 1 component as you can get it)

**Comment by kumaresan-subramani** [comment]
I think, this issue also same https://github.com/angular/angular/issues/36079

**Comment by pkozlowski-opensource** [comment]
I'm going to close this one based on @kara [comment](https://github.com/angular/angular/issues/35955#issuecomment-597921585) - it is really hard to debug large repositories as the one linked as a repro.

Please try to reduce the amount of code needed to reproduce the problem to the absolute minimum and _without_ including any 3rd party dependencies. If you can reproduce the issue only when using nebular, please report the issue in there first.
