### ISSUE TITLE
Multiple definitions of a property not allowed in strict mode angular 8

### ISSUE THREAD

**Issue by wang525525** [angular/angular#35952]
Hello 
Please help me. 
I am the new writer for angular issues here. 

I am very afraid that I wrote wrong explanation which confused the core developers of Angular. 
So please understand my poor English and low level knowledge of the Angular. 

I have faced "Multiple definitions of a property not allowed in strict mode" in Angular 8
This issue is only occurred in the IE11. 

```
SCRIPT1046: Multiple definitions of a property not allowed in strict mode
File: vendor.js, line: 6140, column: 16
```

```
Dir.ngDirectiveDef = _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵɵdefineDirective"]({ type: Dir, selectors: [["", "dir", ""]], factory: function Dir_Factory(t) { return new (t || Dir)(); }, hostBindings: function Dir_HostBindings(rf, ctx, elIndex) { if (rf & 1) {
        _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵɵallocHostVars"](1);
    } if (rf & 2) {
        _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵɵattribute"]("dir", ctx._rawDir);
    } }, inputs: { dir: "dir" }, outputs: { change: "dirChange" }, exportAs: ["dir"], features: [_angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵɵProvidersFeature"]([{ provide: Directionality, useExisting: Dir }])] });
/*@__PURE__*/ _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵsetClassMetadata"](Dir, [{
        type: _angular_core__WEBPACK_IMPORTED_MODULE_1__["Directive"],
        args: [{
                selector: '[dir]',
                providers: [{ provide: Directionality, useExisting: Dir }],
                host: { '[attr.dir]': '_rawDir' },
                exportAs: 'dir'
            }]
    }], function () { return []; }, { _dir: [], _isInitialized: [], change: [{
            type: _angular_core__WEBPACK_IMPORTED_MODULE_1__["Output"],
            args: ['dirChange']
        }], dir: [{
            type: _angular_core__WEBPACK_IMPORTED_MODULE_1__["Input"]
        }], dir: [], value: [], ngAfterContentInit: [], ngOnDestroy: [] });
    return Dir;
}());
```

On the above code the `dir` is twice definition. 

So in order to avoid this, I changed the `"use strict"` in the dist folder as `"----------"`.
I followed this method here. 
https://github.com/angular/angular/issues/30569#issuecomment-536615422

for more details. 

**Environment**

```
    "@angular-devkit/build-ng-packagr": "^0.900.1",
    "@angular/animations": "8.2.14",
    "@angular/cdk": "8.2.3",
    "@angular/common": "8.2.14",
    "@angular/compiler": "8.2.14",
    "@angular/core": "8.2.14",
    "@angular/forms": "8.2.14",
    "@angular/http": "^7.2.16",
    "@angular/platform-browser": "8.2.14",
    "@angular/platform-browser-dynamic": "8.2.14",
    "@angular/router": "8.2.14",
```

But I don't think this is not the solution for that. 
So anybody please help me. 
Thanks. 

@gkalpak @

**Comment by JoostK** [comment]
Hello @wang525525,

you appear to be using the Ivy renderer in Angular 8, which was not yet stable in that release. This was a known issue which has since been resolved in Angular 9.

Please upgrade to Angular 9 to keep using Ivy, or disable Ivy in your project.

As this issue has already been resolved, I'm closing this issue.

**Comment by wang525525** [comment]
Hello @JoostK 
yes I am using Ivy renderer. 

I understand. 
Thanks for your reply.
