### ISSUE TITLE
Remove facade from HTTP since it is JS only

### ISSUE THREAD

**Issue by mhevery** [angular/angular#3595]
Currently HTTP module depends on facade, which just adds bulk and is not needed since it is JS only.

Blocked by #3579 and #2794

**Comment by jeffbcross** [comment]
Will be http-only after #3579, currently it supports dart.

**Comment by caitp** [comment]
what about the EventEmitter/Observable stuff? That's build into Facade, and seems hard to remove

**Comment by jeffbcross** [comment]
@caitp http will export Rx Observables directly with #2794

**Comment by mgechev** [comment]
I can take this one. As far as I see, soon [EventEmitter will removed](https://github.com/angular/angular/pull/4424) as dependency of http so there will be no more blocking issues.

**Comment by jeffbcross** [comment]
@mgechev yep! And you should coordinate with @robwormald to prevent stepping on each other's toes, since he's doing a lot inside `Http`.

**Comment by jeffbcross** [comment]
I'll self-assign this for now, but will consider @mgechev as the actual assignee.

**Comment by robwormald** [comment]
i've more or less completed this anyway whilst refactoring the Observable stuff, just a couple more bits on the MockBackend to remove to go, and then it should be just the isFunction and whatnot kind of things.

**Comment by jeffbcross** [comment]
In that case, do you want to just task on a commit to your PR removing the remaining facade stuff, @robwormald ?

**Comment by robwormald** [comment]
OK with me. I'd love some help with the next phase (refax of EventEmitter and such in the facade itself), but i think in Http i have it under control.

Q - handy things like "isFunction" - they're in the facade but useful, should they be pulled as well?

**Comment by jeffbcross** [comment]
@robwormald I think @mhevery is the one to ask about what should be in facade. From my most recent convo with him, I think his opinion is that utilities like `isFunction` should be pulled out of facade, and facade should just be treated as common abstractions over platform APIs that have subtle differences between JS and Dart.
