### ISSUE TITLE
How to run external javascript function on every route change?

### ISSUE THREAD

**Issue by satishverma143** [angular/angular#35953]
Please help us.
I just want to know that How can I run external JavaScript function on every route change?

Team Please help me.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
