### ISSUE TITLE
Correction → ReferenceError: __importDefault is not defined 

### ISSUE THREAD

**Issue by gildo-farias** [angular/angular#35966]
# 🐞 bug report (BUG SOLUTION) 

### Affected Package
Angular v.9, angular/cli v.9
TypeScript => 3.7.5
@angular-devkit/build-angular
@angular-devkit/build-ng-packagr

### Is this a regression?
Yes, the previous version Angular v.8, angular/cli v.8, with TypeScript = 3.5.3 
this bug was not present.

### Description 
  Hey guys, After updating my project to Angular and angular/cli to v.9, error in the nonsense template on the line:

**templateUrl: './MyComponent.component.html'**

So, after reading several posts about being a kind of bug in the recent version of Typescript among other possible causes, and attempts to switch to the previous version, my problem was solved when after reinstalling angular/cli and run npm commands:

```
npm install --save-dev @angular-devkit/build-angular
npm install --save-dev @angular-devkit/build-ng-packagr
```

_package.json BEFORE:_ 
```
     "@ angular-devkit / build-angular": "~ 0.803.20",
     "@ angular-devkit / build-ng-packagr": "~ 0.803.20",
```

_package.json AFTER npm installs:_ 
```
     "@ angular-devkit / build-angular": "^ 0.900.5",
     "@ angular-devkit / build-ng-packagr": "^ 0.900.5",
```

### *Detail:
  I tried to change the versions of these packages manually in the package.json and the error persisted, so I deleted this package.json lines in devDependencies and then executed the npm command above the error disappeared.

_I hope I can help other Angular beginners as well as i :grin:, TY ALL_ 

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.5
Node: 12.13.0
OS: win32 x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                                     Version
------------------------------------------------------------
@angular-devkit/architect          0.900.5
@angular-devkit/build-angular      0.900.5
@angular-devkit/build-ng-packagr   0.900.5
@angular-devkit/build-optimizer    0.900.5
@angular-devkit/build-webpack      0.900.5
@angular-devkit/core               9.0.5
@angular-devkit/schematics         9.0.5
@ngtools/webpack                   9.0.5
@schematics/angular                9.0.5
@schematics/update                 0.900.5
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2

</code></pre>

**Anything else relevant?**
project-link : [https://github.com/gildo-farias/Angular_NodeJS](url)

**Comment by alan-agius4** [comment]
Hi @gildo-farias, the problem here is that since you updated using `npm` directly the code migrations cannot run and thus you are left with a broken project.

To update to a newer major version it highly recommended to use `ng update` instead of npm/yarn install. See here: https://angular.io/guide/updating-to-version-9

Since you already update the packages manually, use the below commands to run the migrations:
```bash
ng update @angular/core --migrate-only --from 8 --to 9
ng update @angular/cli --migrate-only --from 8 --to 9
```
