### ISSUE TITLE
In Ivy, accessing rootNodes results in throwing error when its embedded view has a hole

### ISSUE THREAD

**Issue by Shijir** [angular/angular#35967]
# 🐞 bug report

Angular v9.0.3

### Is this a regression?

Possibly. This used to work fine with ViewEngine.

### Description

I have this component which I dynamically create and provide its projected nodes. But these projected nodes are placed inside a `ng-template` which I would use to create an embedded view. However, after creating the embedded view, I am no longer could access its `rootNodes` as it's throwing the following error:

```
ERROR Error: ASSERTION ERROR: Should be one of Element, Container, Projection, ElementContainer, IcuContainer but got <unknown> [Expected=> true == false <=Actual]
```

This is the minimal reproduction of the dynamic component: 
```ts
@Component({
  selector: 'dynamic-portal',
  template: `<ng-template #portal><ng-content></ng-content></ng-template>`,
})
export class DynamicPortal implements AfterViewInit {
  @ViewChild('portal') templateRef: TemplateRef<void>;
  view: EmbeddedViewRef<void>;

  ngAfterViewInit() {
    this.view = this.templateRef.createEmbeddedView();
    // Simply trying to access the view's rootNodes would throw an error
    console.log(this.view.rootNodes);
  }
}
```

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>
ERROR Error: ASSERTION ERROR: Should be one of Element, Container, Projection, ElementContainer, IcuContainer but got <unknown> [Expected=> true == false <=Actual]

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular v9.0.3
Node v12.15.0
</code></pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment]
I can confirm that this is a bug, minimal repo: https://ng-run.com/edit/DO0ZNKuNJH3iSck6BgyW

**Comment by Shijir** [comment]
Hi @pkozlowski-opensource! Sorry to bother you. Do you see any workaround to circumvent this issue?
