### ISSUE TITLE
Following a bookmarked link in safari breaks dynamic page titles

### ISSUE THREAD

**Issue by javajohnHub** [angular/angular#35972]
# 📚 Docs or angular.io bug report

### Description
If you bookmark an angular site in safari and follow the bookmark, the Page Title service fires but never updates when you continue navigating the site. It is happening in my app and also on angular.io.

## 🔬 Minimal Reproduction
Go to angular.io in safari and bookmark a page. Follow the bookmark back to angular.io. Continue to navigate elsewhere on the site. The page titles fail to update. Tested safari bookmarks on non angular sites and the page titles worked.

### What's the affected URL?**
https://angular.io

### Expected vs Actual Behavior**
Expected: Page titles update on navigating to new page.
Actual: Page titles fail to update.

## 🌍  Your Environment
MacOs Catalina 10.15.3

### Browser info
safari 13.0.5

### Anything else relevant?
Page titles update fine if you manually enter url into bar.

**Comment by petebacondarwin** [comment]
I can't recreate this on
Safari: Version 14.0 (15610.1.28.1.9, 15610)
OS/X Catalina 10.15.6 (19G2021)

**Comment by petebacondarwin** [comment]
Closing as not reproducible. @javajohnHub - if this is still a problem please create a new issue with further steps to reproduce it.
