### ISSUE TITLE
Angular2 uses wrong log level for exceptions

### ISSUE THREAD

**Issue by goderbauer** [angular/angular#3597]
Currently, exceptions logged by modules/angular2/src/core/exception_handler.ts have the wrong log level. They do not show up as ERROR in the console. This makes it very hard to assert after an automated test run that no exceptions have occurred. Errors should be logged as Errors.

This is a follow-up to https://github.com/angular/angular/issues/1231.

**Comment by goderbauer** [comment]
Internally tracked at b/23127206

**Comment by TedSander** [comment]
@naomiblack can you find someone to look at this? It is making end-end testing hard.

**Comment by pkozlowski-opensource** [comment]
This was fixed in #3812
