### ISSUE TITLE
Update Universal doc to include prerender and live reload functionality

### ISSUE THREAD

**Issue by santoshyadavdev** [angular/angular#36004]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by santoshyadav198613** [comment]
Hi @kapunahelewong ,
I will be working on it, please assign this to me.

**Comment by kapunahelewong** [comment]
Thank you, @santoshyadav198613!
