### ISSUE TITLE
Component displayed twice when used as Angular Element

### ISSUE THREAD

**Issue by Palapapaa** [angular/angular#36014]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/elements I think

### Is this a regression?

Nope, it doesn't seems to.

### Description

I've got 2 components : `my-card` and `my-button`
The `my-card` component uses the `my-button` component.
When used in an Angular App there is no problem it works as it should be.
But when used as an Angular Element the `my-button` component display 2 button instead of 1 

## 🔬 Minimal Reproduction

 I've made a reproduction repository :
[Repro](https://github.com/Palapapaa/repro-bug)

## 🔥 Exception or Error
None

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.25
Node: 10.15.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.25
@angular-devkit/build-angular     0.803.25
@angular-devkit/build-optimizer   0.803.25
@angular-devkit/build-webpack     0.803.25
@angular-devkit/core              8.3.25
@angular-devkit/schematics        8.3.25
@angular/cli                      8.3.25
@ngtools/webpack                  8.3.25
@schematics/angular               8.3.25
@schematics/update                0.803.25
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

But I have the same problem with Angular 9.

**Comment by dianikol** [comment]
Hi there!

If you import your script before the closing  </body> tag it will work fine!

**Comment by Palapapaa** [comment]
Hello !

Thank you for your response, it does fix my problem (I have to find a way to import my script in the body tag in storybook).


Is it a normal behaviour ?

**Comment by dianikol** [comment]
To be honest I never came across that issue before - I'm new to ng elements also -  so I don't know why it behaves like that but putting the scripts at the bottom of the page is always a good practise so that issue doesn't matter IMO.

**Comment by gkalpak** [comment]
From a quick look, the reason it was rendered twice is that you are using the same selector when declaring the Angular components as you use when registering them as Custom Elements. Thus `my-button` inside of the `my-card` component, it processed by Angular as a regular Angular components and also by the browser as a Custom Element (and therefore rendered twice).

Closing since everything seems to be working as expected.
