### ISSUE TITLE
v9.0.6 -> Uncaught TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by meriturva** [angular/angular#36020]
# 🐞 bug report

Updated to 9.0.6 and we got the error: Uncaught TypeError: Cannot read property 'type' of undefined

### Is this a regression?

with 9.0.5 no problem.

## 🔥 Exception or Error
<pre><code>
Uncaught TypeError: Cannot read property 'type' of undefined
    at Module.ɵɵNgOnChangesFeature (:4200/vendor.js:44937)
    at Module../node_modules/@angular/common/__ivy_ngcc__/fesm2015/common.js (:4200/vendor.js:14192)
    at __webpack_require__ (:4200/runtime.js:85)
    at Module../node_modules/@angular/common/__ivy_ngcc__/fesm2015/http.js (:4200/vendor.js:17244)
    at __webpack_require__ (:4200/runtime.js:85)
    at Module../node_modules/@aulos/core/fesm2015/aulos-core.js (:4200/vendor.js:89726)
    at __webpack_require__ (:4200/runtime.js:85)
    at Module.<anonymous> (:4200/main.js:2232)
    at Module../src/main.ts (:4200/main.js:2273)
    at __webpack_require__ (:4200/runtime.js:85)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.5
Node: 12.15.0
OS: win32 x64

Angular: 9.0.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@angular/cdk                      9.1.2
@angular/cli                      9.0.5
@ngtools/webpack                  9.0.5
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

Seems to be related to https://github.com/angular/angular/pull/35846/
Actually we found a call to the function:

```
function ɵɵNgOnChangesFeature(definition) {
    if (definition.type.prototype.ngOnChanges) {
        definition.setInput = ngOnChangesSetInput;
        ((/** @type {?} */ (definition))).onChanges = wrapOnChanges();
    }
}
```
without any param here (see last property **features** ):

`NgComponentOutlet.ɵdir = ɵngcc0.ɵɵdefineDirective({ type: NgComponentOutlet, selectors: [["", "ngComponentOutlet", ""]], inputs: { ngComponentOutlet: "ngComponentOutlet", ngComponentOutletInjector: "ngComponentOutletInjector", ngComponentOutletContent: "ngComponentOutletContent", ngComponentOutletNgModuleFactory: "ngComponentOutletNgModuleFactory" }, features: [ɵngcc0.ɵɵNgOnChangesFeature()] });`

**Comment by meriturva** [comment]
Update: we found that if we use our internal packages compiled and published with 9.0.5 with a project updated to 9.0.6 we have that issue. Actually we have published all packages built with 9.0.6 and now all satellite projects work well.

**Comment by petebacondarwin** [comment]
How are you building and publishing these internal libraries?

Libraries that are published to client projects as `package.json` dependencies should be built in ViewEngine mode (i.e. ivy disabled). Is that the case here?

**Comment by meriturva** [comment]
We actually build in the standard way, no custom build chain, no package published with ivy enabled (after 3 years with custom builds we have found that best for maintainers and keep all software updated is to follow angular cli rules).

So we use exactly the guide here: https://angular.io/guide/creating-libraries

**Comment by petebacondarwin** [comment]
Strange because the 9.0.6 version of ngcc should ensure that the library package is updated with the correct call. I wonder if there was some caching going on that meant that the libraries that had been processed with the 9.0.5 version of ngcc were being reused rather than being re-processed by 9.0.6 version of ngcc...??

**Comment by meriturva** [comment]
We delete client project npm_modules many times before open issue but i confirm that updated projects on latest version not trigger new ngcc compile process.

What is the trigger for ngcc to re-process a library?

**Comment by petebacondarwin** [comment]
If there is a `postinstall` hook in your `package.json` then it will be run when you do `npm/yarn install`.
If not then it will be triggered by a run of `ng serve` or `ng build`. Did you see messages like:

```
Compiling @angular/core : es2015 as esm2015

Compiling @angular/common : es2015 as esm2015

Compiling @angular/platform-browser : es2015 as esm2015

Compiling @angular/platform-browser-dynamic : es2015 as esm2015
```

when running `ng serve`?

And if so, did it also show `Compiling <name of your library>: ...` messages too?

**Comment by meriturva** [comment]
Thanks @petebacondarwin we already noted that re-process is not well triggered on our libraries. On CI we already force ngcc call as indicated on angular guide (that's why our tests are all green, also on client projects).

I'm collecting a few local logs and i will update the issue.

**Comment by meriturva** [comment]
Just found now....on our package,json produced by our CI message:

`"prepublishOnly": "node --eval \"console.error('ERROR: Trying to publish a package that has been compiled by Ivy. This is not allowed.\\nPlease delete and rebuild the package, without compiling with Ivy, before attempting to publish.\\n')\" && exit 1"`

I guess something broke in our configuration. I will keep the issue updated after a check with a colleague.
Again thanks @petebacondarwin for your help.

**Comment by MortadhaFadhlaoui** [comment]
Hello everyone, i got same problem. 
So as i understand i need to disable Ivy in my library!
"angularCompilerOptions": {
    "enableIvy": false
  }
Angular: 9.0.0

**Comment by meriturva** [comment]
@MortadhaFadhlaoui you have just to run ng build with --prod flag

**Comment by sahlifiras26** [comment]
Hello, i'm facing the same problem but i got this log :

> Uncaught TypeError: Cannot read property 'type' of undefined
    at Il (main-es2015.758ef42104c26b069343.js:1)
    at main-es2015.758ef42104c26b069343.js:1
    at Module.zUnb (main-es2015.758ef42104c26b069343.js:1)
    at l (runtime-es2015.0811dcefd377500b5b1a.js:1)
    at Object.0 (main-es2015.758ef42104c26b069343.js:1)
    at l (runtime-es2015.0811dcefd377500b5b1a.js:1)
    at t (runtime-es2015.0811dcefd377500b5b1a.js:1)
    at Array.r [as push] (runtime-es2015.0811dcefd377500b5b1a.js:1)
    at main-es2015.758ef42104c26b069343.js:1

**Comment by meriturva** [comment]
@sahlifiras26 you are simply using a library not well packed or you have to build correctly yours.
