### ISSUE TITLE
Properly decode $httpParamSerializer querystring?

### ISSUE THREAD

**Issue by Vayvala** [angular/angular#3603]
Here is my object, that I want to serialize:

    {"cars": [
       {"make":"volkswagen","model":"golf"},
       {"make":"volkswagen","model":"polo"},
       {"make":"audi","model":"a3"},
       {"make":"bmw","model":"1-series"},
       {"make":"renault","model":"espace"} 
    ]}

Before, I used jQuery `$.param()` function and `qs` library to decode it on node.js. And everything worked fine, I didn't need to parse anything myself.    
Now, I decided to try new Angular 1.4 service `$httpParamSerializer`. And after decoding, instead of `objects` in the array, I get `strings`:

     '{"make":"volkswagen","model":"golf"}'

How can I properly decode querystring that was created with the `$httpParamSerializer` service, without calling `JSON.parse` on every object in the array?

Here is `$.param` querystring:

    cars%5B0%5D%5Bmake%5D=volkswagen&cars%5B0%5D%5Bmodel%5D=golf&cars%5B1%5D%5Bmake%5D=volkswagen&cars%5B1%5D%5Bmodel%5D=polo&cars%5B2%5D%5Bmake%5D=audi&cars%5B2%5D%5Bmodel%5D=a3&cars%5B3%5D%5Bmake%5D=bmw&cars%5B3%5D%5Bmodel%5D=1-series&cars%5B4%5D%5Bmake%5D=renault&cars%5B4%5D%5Bmodel%5D=espace&demo%5Bsome%5D=bar

And here is `$httpParamSerializer` querystring:

    cars=%7B%22make%22:%22volkswagen%22,%22model%22:%22golf%22%7D&cars=%7B%22make%22:%22volkswagen%22,%22model%22:%22polo%22%7D&cars=%7B%22make%22:%22audi%22,%22model%22:%22a3%22%7D&cars=%7B%22make%22:%22bmw%22,%22model%22:%221-series%22%7D&cars=%7B%22make%22:%22renault%22,%22model%22:%22espace%22%7D&demo=%7B%22some%22:%22bar%22%7D`

**Comment by pkozlowski-opensource** [comment]
Wrong repo, try https://github.com/angular/angular.js
