### ISSUE TITLE
Docs not working on chrome

### ISSUE THREAD

**Issue by ishankghosh** [angular/angular#36032]
# 📚 Docs or angular.io bug report

### Description

The Docs is not woking in Chrome it is giving error in all the pages. I have attached a sample screen shot for reference

### What's the affected URL?**
https://angular.io/guide/user-input

### Reproduction Steps**
 Visit this - https://angular.io/guide/user-input

## 📷Screenshot
![Screenshot (51)](https://user-images.githubusercontent.com/26690434/76493942-d95f7480-6459-11ea-99c0-bf64e3447975.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by json-derulo** [comment]
What version of Chrome are you running? What is the content of the developer console?

**Comment by petebacondarwin** [comment]
Closing due to lack of response.
