### ISSUE TITLE
how to pass a model object into reactive form and vice versa in angular

### ISSUE THREAD

**Issue by r-shakeri** [angular/angular#36038]
model:
<pre><code>
export class Book {
 constructor(name: string,  isbn: string) { }
}
</code></pre>

component:
<pre><code>
@Component({
  selector: 'app-book',
  templateUrl: './book.component.html',
  styleUrls: ['./book.component.css']
})
export class BookComponent implements OnInit {

  bookFormGroup: FormGroup;
  private newBook: Book = new Book('the best wishes', 'isbn1111111111');

  constructor(private fb: FormBuilder) { }

  ngOnInit() {
   //1
    this.bookFormGroup = this.fb.group({
      name: ['', Validators.required],
      isbn: ['', Validators.required]
    });
  }

  submit() {
    //2
   const submittedBook = new Book(this.bookFormGroup.value.name, 
   this.bookFormGroup.value.isbn);
  }

}
</code></pre>

1. here how to combine newBook with this.fb.group then asign to the this.bookFormGroup, actually i want to know how to set the newBook object that i recently created as the form group object.

2. then how to get the value of the this.bookFormGroup from the form and convert it as an instance of the Book class.

actually i want to know what is the best practices on interaction between model object and form

**Comment by r-shakeri** [comment]
any ideas???????
answer pls...

**Comment by hemachandran85** [comment]
I have created the simple form to pass model to FormGroup and Vise versa.. please check it,,

https://stackblitz.com/edit/angular-dvbnsm?file=src%2Fapp%2Fapp.component.ts

**Comment by r-shakeri** [comment]
@hemachandran85 thank u by replying, i visited your link, for this line `this.bookFormGroup.patchValue(this.newBook);` patchvalue just uses the values of the object given to it. and i don't think it is good at first i initialize the formgroup with empty string then i patchvalue them.
and for getting values from the form into the model, you used Template-driven forms, so this mixture of two kind of forms i think is not a good method.

**Comment by r-shakeri** [comment]
@hemachandran85 thank u by replying, i visited your link, for this line this.bookFormGroup.patchValue(this.newBook); patchvalue just uses the values of the object given to it. and i don't think it is good at first i initialize the formgroup with empty string then i patchvalue them.
and for getting values from the form into the model, you used Template-driven forms, so this mixture of two kind of forms i think is not a good method.

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Thank you.
