### ISSUE TITLE
Now Ivy is Out.. Still No Solution to the Click Event and Custom Components in innerHTML 

### ISSUE THREAD

**Issue by totalard** [angular/angular#36041]
Now Ivy is Out.. Still No Solution to the Click Event and Custom Components in innerHTML 

I seen in many threads , says The problem will be solved when ivy is Out.. Wait for Ivy relase.  
Still in angular 9 (ivy) i can't find a solution to run my html that coMing from Api..I want to run it in angular innerHtml or in any way... 

Dynamic component is not suitable... As I have to follow the template coming from Api..

Somebody please help... It is mandatory to my project...

**Comment by petebacondarwin** [comment]
@totalard - please could you provide links to the issues that you refer to in your description. Even better can you provide a clear description of what you would like to see implemented.

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to respond / investigate.
