### ISSUE TITLE
i18n extraction does not preserve line endings format

### ISSUE THREAD

**Issue by Lectem** [angular/angular#36057]
# 🐞 bug report

### Affected Package
The issue is caused by package `@angular/localize`

### Is this a regression?

I do not think so.

### Description

When extracting localization with `ng xi18n`, source content with CR+LF (windows) line endings will be replaced by LF (Unix) line endings on **Windows**.

This is an issue depending on one's setup of `git` and for other tools that need to diff/merge localization files, such as https://github.com/manux54/vsc-angular-localization-helper.

## 🔬 Minimal Reproduction

This can be reproduced with the [i18n example ](https://angular.io/guide/i18n)after modifying some sources to include CR+LF line endings. 

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.5
Node: 12.9.1
OS: win32 x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@angular/cdk                      9.1.1
@angular/material                 9.1.1
@ngtools/webpack                  9.0.5
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

This was tested only on Windows.

**Comment by petebacondarwin** [comment]
Thanks for raising this issue.

We are currently rewriting the extraction tooling for extracting translations, which will be based on the build output of the Angular application, which is different to the current approach which is part of the ViewEngine compiler.

Whether line-endings are captured correctly will be dependent upon whether the original line-endings make it through the Ivy compilation and into the `$localize` calls. I suspect that it not but we need to investigate.

**Comment by Lectem** [comment]
The other option might be to simply output using the default line ending of the OS and make it possible to override the behavior instead of keeping the same line endings ?
I think it would probably be enough for most use-cases.

**Comment by petebacondarwin** [comment]
@Lectem - can you check to see if https://github.com/angular/angular/pull/36741 fixed your problem?

**Comment by Lectem** [comment]
Sorry I'm not very familiar with npm / the development of angular, is there a way to easily use the upstream master branch in my project to test those changes ?

**Comment by petebacondarwin** [comment]
This PR was released in 10.0.0-rc.0. So perhaps you could try updating to that version?

**Comment by petebacondarwin** [comment]
@Lectem - I believe that this is fixed by #36741, which was released as part of v10.0.0.
Please open a new issue (or comment here) if you still have a problem.
