### ISSUE TITLE
Angular Widgets

### ISSUE THREAD

**Issue by babaliaris** [angular/angular#36065]
# 🚀 feature request
Angular widgets that are going to work as **components** would be great!

### Description
Coming from android and other UI frameworks, widgets like date and clock pickers can
really optimize and speed up your development. It would be really awesome to have
built-in angular components for frequently input strategies, for example, @angular/widgets.

Of course, this is not an important requirement for the angular framework, but I believe it could
speed up the development especially for new web developers.

Unfortunately, I lack the knowledge of making them, especially when it comes to 
good designs with CSS.

Using `<input type="date">` is quite boring for users. Of course, you can find open source
CSS styles, but working with angular components directly would be a lot better experience!

Thank you for your time.

**Comment by santoshyadav198613** [comment]
Check this https://material.angular.io/

**Comment by santoshyadav198613** [comment]
Also you can find many open source libraries here https://angular.io/resources?category=development

**Comment by babaliaris** [comment]
Oh, I didn't know about them. Then this issue should be closed.
