### ISSUE TITLE
Service Scope Settings

### ISSUE THREAD

**Issue by ninezero90hy** [angular/angular#36064]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....

### Description
I want to set the service to be dependent on one module. But I don't think it's possible right now.

### Describe the solution you'd like
```javascript
@Injectable({
  providedIn: TypesetModule
})
export class TypesetStateManagementService {
```
It would be good to add it so that it can be set up in the service decorator. But this is my simple idea.

I don't think this is a simple task and I respect the Angular team.

This is my opinion, so I would appreciate it if you could refer to it.

**Comment by kara** [comment]
@ninezero90hy You should be able to do this already. See docs [here](https://angular.io/guide/providers#providedin-and-ngmodules). If I'm misunderstanding your question or if you think it's actually not working, please feel free to file more information with a minimal repro.

**Comment by ninezero90hy** [comment]
@kara Okay. I will check again.
