### ISSUE TITLE
App Not Loading Intermittently In Firefox - Polyfills.js

### ISSUE THREAD

**Issue by erabhisinha** [angular/angular#36069]
**Description:**

I have a angular app written in version 7.1.0 and this app intermittently does not loads in Firefox however works perfectly in chrome.

Issue which I can see in developer's tool looks to be in Polyfills.js however when I dig it a bit deeper is found in Zone.js -> function resolvePromise(promise, state, value)

Why I am saying this is intermittent is because after I encounter this issue then reloading the application using Ctrl+F5 sometimes fixes the issues and sometimes does not.

I could not found much on internet related to similar kind of issues faced by other developers however there were few issues reported by other developers in Pollyfills.js which were due to incorrect version's of dependent modules but that were not of much help to me since I am a new to Angular and could not relate to the issues well.

**Stack Trace:** 

Uncaught (in promise): TypeError: config is undefined
AuthenticationContext@http://localhost:4200/vendor.js:84200:13
./node_modules/adal-angular/lib/adal.js/module.exports.inject@http://localhost:4200/vendor.js:85993:20
MsAdalAngular6Service@http://localhost:4200/vendor.js:87904:83
MsAdalAngular6Service_Factory@http://localhost:4200/vendor.js:88093:196
_callFactory@http://localhost:4200/vendor.js:60957:20
_createProviderInstance@http://localhost:4200/vendor.js:60915:26
resolveNgModuleDep@http://localhost:4200/vendor.js:60890:17
_createClass@http://localhost:4200/vendor.js:60942:68
_createProviderInstance@http://localhost:4200/vendor.js:60912:26
resolveNgModuleDep@http://localhost:4200/vendor.js:60876:21
./node_modules/@angular/core/fesm5/core.js/NgModuleRef_.prototype.get@http://localhost:4200/vendor.js:61584:16
getToken@http://localhost:4200/vendor.js:79448:21
runCanActivate/canActivateObservables</<@http://localhost:4200/vendor.js:79677:33
defer/<@http://localhost:4200/vendor.js:90578:21
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype._trySubscribe@http://localhost:4200/vendor.js:88917:25
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88903:22
./node_modules/rxjs/_esm5/internal/operators/take.js/TakeOperator.prototype.call@http://localhost:4200/vendor.js:97252:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
subscribeTo/<@http://localhost:4200/vendor.js:100168:31
subscribeToResult@http://localhost:4200/vendor.js:100345:84
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._innerSub@http://localhost:4200/vendor.js:95102:90
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._tryNext@http://localhost:4200/vendor.js:95096:14
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._next@http://localhost:4200/vendor.js:95079:18
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@http://localhost:4200/vendor.js:89536:18
subscribeToArray/<@http://localhost:4200/vendor.js:100210:24
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype._trySubscribe@http://localhost:4200/vendor.js:88917:25
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88903:22
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapOperator.prototype.call@http://localhost:4200/vendor.js:95057:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
subscribeTo/<@http://localhost:4200/vendor.js:100168:31
subscribeToResult@http://localhost:4200/vendor.js:100345:84
./node_modules/rxjs/_esm5/internal/observable/combineLatest.js/CombineLatestSubscriber.prototype._complete@http://localhost:4200/vendor.js:90479:107
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.complete@http://localhost:4200/vendor.js:89548:18
subscribeToArray/<@http://localhost:4200/vendor.js:100213:24
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype._trySubscribe@http://localhost:4200/vendor.js:88917:25
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88903:22
./node_modules/rxjs/_esm5/internal/observable/combineLatest.js/CombineLatestOperator.prototype.call@http://localhost:4200/vendor.js:90449:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
./node_modules/rxjs/_esm5/internal/operators/scan.js/ScanOperator.prototype.call@http://localhost:4200/vendor.js:96390:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
./node_modules/rxjs/_esm5/internal/operators/filter.js/FilterOperator.prototype.call@http://localhost:4200/vendor.js:94244:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
./node_modules/rxjs/_esm5/internal/operators/map.js/MapOperator.prototype.call@http://localhost:4200/vendor.js:94805:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
./node_modules/rxjs/_esm5/internal/operators/take.js/TakeOperator.prototype.call@http://localhost:4200/vendor.js:97252:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
subscribeTo/<@http://localhost:4200/vendor.js:100168:31
subscribeToResult@http://localhost:4200/vendor.js:100345:84
./node_modules/rxjs/_esm5/internal/operators/switchMap.js/SwitchMapSubscriber.prototype._innerSub@http://localhost:4200/vendor.js:97164:115
./node_modules/rxjs/_esm5/internal/operators/switchMap.js/SwitchMapSubscriber.prototype._next@http://localhost:4200/vendor.js:97154:14
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@http://localhost:4200/vendor.js:89536:18
scalar/result<@http://localhost:4200/vendor.js:91715:20
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype._trySubscribe@http://localhost:4200/vendor.js:88917:25
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88903:22
./node_modules/rxjs/_esm5/internal/operators/switchMap.js/SwitchMapOperator.prototype.call@http://localhost:4200/vendor.js:97132:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
subscribeTo/<@http://localhost:4200/vendor.js:100168:31
subscribeToResult@http://localhost:4200/vendor.js:100345:84
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._innerSub@http://localhost:4200/vendor.js:95102:90
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._tryNext@http://localhost:4200/vendor.js:95096:14
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._next@http://localhost:4200/vendor.js:95079:18
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@http://localhost:4200/vendor.js:89536:18
subscribeToArray/<@http://localhost:4200/vendor.js:100210:24
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype._trySubscribe@http://localhost:4200/vendor.js:88917:25
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88903:22
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapOperator.prototype.call@http://localhost:4200/vendor.js:95057:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
./node_modules/rxjs/_esm5/internal/operators/filter.js/FilterOperator.prototype.call@http://localhost:4200/vendor.js:94244:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
./node_modules/rxjs/_esm5/internal/operators/take.js/TakeOperator.prototype.call@http://localhost:4200/vendor.js:97252:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
./node_modules/rxjs/_esm5/internal/operators/defaultIfEmpty.js/DefaultIfEmptyOperator.prototype.call@http://localhost:4200/vendor.js:93258:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
subscribeTo/<@http://localhost:4200/vendor.js:100168:31
subscribeToResult@http://localhost:4200/vendor.js:100345:84
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._innerSub@http://localhost:4200/vendor.js:95102:90
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._tryNext@http://localhost:4200/vendor.js:95096:14
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._next@http://localhost:4200/vendor.js:95079:18
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@http://localhost:4200/vendor.js:89536:18
subscribeToArray/<@http://localhost:4200/vendor.js:100210:24
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype._trySubscribe@http://localhost:4200/vendor.js:88917:25
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88903:22
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapOperator.prototype.call@http://localhost:4200/vendor.js:95057:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
./node_modules/rxjs/_esm5/internal/operators/filter.js/FilterOperator.prototype.call@http://localhost:4200/vendor.js:94244:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
./node_modules/rxjs/_esm5/internal/operators/take.js/TakeOperator.prototype.call@http://localhost:4200/vendor.js:97252:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
./node_modules/rxjs/_esm5/internal/operators/defaultIfEmpty.js/DefaultIfEmptyOperator.prototype.call@http://localhost:4200/vendor.js:93258:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
subscribeTo/<@http://localhost:4200/vendor.js:100168:31
subscribeToResult@http://localhost:4200/vendor.js:100345:84
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._innerSub@http://localhost:4200/vendor.js:95102:90
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._tryNext@http://localhost:4200/vendor.js:95096:14
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._next@http://localhost:4200/vendor.js:95079:18
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@http://localhost:4200/vendor.js:89536:18
./node_modules/rxjs/_esm5/internal/operators/defaultIfEmpty.js/DefaultIfEmptySubscriber.prototype._complete@http://localhost:4200/vendor.js:93276:30
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.complete@http://localhost:4200/vendor.js:89548:18
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype._complete@http://localhost:4200/vendor.js:89566:26
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.complete@http://localhost:4200/vendor.js:89548:18
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype._complete@http://localhost:4200/vendor.js:89566:26
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.complete@http://localhost:4200/vendor.js:89548:18
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._complete@http://localhost:4200/vendor.js:95107:30
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.complete@http://localhost:4200/vendor.js:89548:18
subscribeToArray/<@http://localhost:4200/vendor.js:100213:24
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype._trySubscribe@http://localhost:4200/vendor.js:88917:25
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88903:22
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapOperator.prototype.call@http://localhost:4200/vendor.js:95057:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
./node_modules/rxjs/_esm5/internal/operators/filter.js/FilterOperator.prototype.call@http://localhost:4200/vendor.js:94244:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
./node_modules/rxjs/_esm5/internal/operators/take.js/TakeOperator.prototype.call@http://localhost:4200/vendor.js:97252:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
./node_modules/rxjs/_esm5/internal/operators/defaultIfEmpty.js/DefaultIfEmptyOperator.prototype.call@http://localhost:4200/vendor.js:93258:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapOperator.prototype.call@http://localhost:4200/vendor.js:95057:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
./node_modules/rxjs/_esm5/internal/operators/map.js/MapOperator.prototype.call@http://localhost:4200/vendor.js:94805:23
./node_modules/rxjs/_esm5/internal/Observable.js/Observable.prototype.subscribe@http://localhost:4200/vendor.js:88898:22
subscribeTo/<@http://localhost:4200/vendor.js:100168:31
subscribeToResult@http://localhost:4200/vendor.js:100345:84
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._innerSub@http://localhost:4200/vendor.js:95102:90
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._tryNext@http://localhost:4200/vendor.js:95096:14
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._next@http://localhost:4200/vendor.js:95079:18
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@http://localhost:4200/vendor.js:89536:18
./node_modules/rxjs/_esm5/internal/operators/map.js/MapSubscriber.prototype._next@http://localhost:4200/vendor.js:94828:26
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@http://localhost:4200/vendor.js:89536:18
./node_modules/rxjs/_esm5/internal/operators/tap.js/TapSubscriber.prototype._next@http://localhost:4200/vendor.js:97546:26

Attaching angular.json and package.json files which could be of any use to help troubleshooting the issue.

[package.json.txt](https://github.com/angular/angular/files/4333956/package.json.txt)
[angular.json.txt](https://github.com/angular/angular/files/4333957/angular.json.txt)

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

The stack trace you shared does not reflect the issue you describe. Please feel free to open a new issue with additional information and ideally a minimal reproduction if you think this is an issue with the Angular framework/zone.js (at the moment it looks like an issue in your application).
