### ISSUE TITLE
NgModel with *ngFor Slow down the broswer and the page never loads!

### ISSUE THREAD

**Issue by babaliaris** [angular/angular#36061]
[Image](https://i.ibb.co/54pjR8R/Deepin-Screenshot-select-area-20200313193654.png)

I've used ngModel so many times and this is the first time this is happening. When I run `ng serve --open` the browser is loading the request forever and eventually after clicking **stop it** I'm getting a warning `script terminated after timeout` or something like that.

If I remove the ngModel then the app is working correctly.
Also if I remove the *ngFor and keep the ngModel, the app is still working.

Only when they are combined together I have this issue.

1. Clone [this](https://github.com/babaliaris/alex-barber-shop-webapp/tree/input-dialog) branch.
2. `npm install`
3. `ng serve --open`

And see it yourselves. Now remove the ngModel from the input tag inside the input-dialog.component.html and see that is working correctly.

```html
<div class="v-modal">
    <div class="v-modal-content">

        <!--Modal Title-->
        <div class="v-modal-titlebar">
            <div class="v-modal-title">{{m_title}}</div>
            <div [ngClass]="{'v-modal-x':true}" [class]="m_env.icons.x"></div>
        </div>

        <!--Modal Body-->
        <div class="v-modal-body">

            <!--Control Group-->
            <div
            *ngFor="let data of m_data"
            class="mt-1"
            >   

                <!--Generate an input element-->
                <input
                *ngIf="data.control === 'input'"
                class           ="form-control"
                [name]          = "data.name"
                [title]         = "data.desc"
                [placeholder]   = "data.desc"
                [attrList]      = "data.attrs"
                [(ngModel)]     = "data.value"
                appAttrPusher
                >

                <!--Error Displayer-->
                <div
                *ngIf="data.error"
                class="error-displayer"
                >
                </div>

            </div>

        </div>

        <!--Modal Footer-->
        <div class="v-modal-footer">
            <button class="form-control">{{m_submitTitle}}</button>
        </div>
    </div>
</div>
```

**Comment by jnizet** [comment]
The input of your component is `m_test.obj.getControls()`. And the `getControls()` method creates a brand new array containing brand new objects every time it's called. So, at each change detection, you create new objects that you pass as input. The presence of ngModel triggers a change detection, which causes a new array to be passed as input, and this apparently starts an infinite loop. 

Call `getControls()` once and store its result in a field. Pass this field as input.

**Comment by babaliaris** [comment]
> The input of your component is `m_test.obj.getControls()`. And the `getControls()` method creates a brand new array containing brand new objects every time it's called. So, at each change detection, you create new objects that you pass as input. The presence of ngModel triggers a change detection, which causes a new array to be passed as input, and this apparently starts an infinite loop.
> 
> Call `getControls()` once and store its result in a field. Pass this field as input.

Thank you! I learned one more thing about angular today! Next time, I'll be very careful
when I call a method from the template.
