### ISSUE TITLE
when diabling IVY in angular 9, component hook not get executed

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular#36079]
# 🐞 bug report

### Affected Package
@angular\core

### Is this a regression?

Working fine in below environments

- angular 8
- angular 9 with IVY

### Description

I have created angular 9 application, when i serve my application working fine.

Once i disable IVY and run my application, my component's hooks not get executed.

## 🔬 Minimal Reproduction

1. Download belwo sample
[sample.zip](https://github.com/angular/angular/files/4336696/sample.zip)

2. Give `npm i`

3. Then `ng serve`

you will see component in browser with mutilple colums like below
![issue](https://user-images.githubusercontent.com/36756050/76732039-b946f280-6784-11ea-963f-2370a4016954.PNG)

But i have defined only three columns like below

```
<e-columns>
               <e-column field='taskID' headerText='Freight ID'  width=130></e-column>
               <e-column field='taskName' headerText='Freight Name'  width=195></e-column>
               <e-column field='progress' headerText='Weight Per Unit' textAlign='Right' type='number' width=130></e-column>
    </e-columns>
```

When i enable IVY mode, by removing below code from `ts.app.config,json` file:

```
"angularCompilerOptions": {
    "enableIvy": false
  }
```

hooks get executed properly and component get rendered properly as like below

## My expected output is
![expect](https://user-images.githubusercontent.com/36756050/76732757-72a5c800-6785-11ea-804c-65f482b7d252.PNG)

## 🔥 Exception or Error
Hooks not get executed

## 🌍  Your Environment

**Angular Version:**
<pre><code>
    "@angular/animations": "~9.0.1",
    "@angular/common": "~9.0.1",
    "@angular/compiler": "~9.0.1",
    "@angular/core": "~9.0.1",
    "@angular/forms": "~9.0.1",
    "@angular/platform-browser": "~9.0.1",
    "@angular/platform-browser-dynamic": "~9.0.1",
    "@angular/router": "~9.0.1",
    "@angular-devkit/build-angular": "~0.900.2",
    "@angular/cli": "~9.0.2",
    "@angular/compiler-cli": "~9.0.1",
    "@angular/language-service": "~9.0.1",

</code></pre>

**Anything else relevant?**
 
Before IVY, we have used mixin to achieve multiple inheritance, Due to this issue [31495](https://github.com/angular/angular/issues/31495), i have created new instance of one class like below 
https://github.com/syncfusion/ej2-angular-ui-components/blob/master/components/grids/src/grid/grid.component.ts#L227 
and called component hooks like below
https://github.com/syncfusion/ej2-angular-ui-components/blob/master/components/grids/src/grid/grid.component.ts#L231

this workaround working fine in angular 9 with IVY and angular 8

But when disabling IVY in angular 9 my hooks no get executed

**Comment by JoostK** [comment]
Your issue is in [the `applyMixin` function](https://github.com/syncfusion/ej2-angular-ui-components/blob/ccfee6a911d455423ecff629989862413d13c21a/components/base/src/util.ts#L7-L13). You're not checking whether the derived class already has the method that is copied over, thereby completely overriding the lifecycle hooks.

Changing it as follows makes it work in ViewEngine:

```ts
if (!derivedClass.prototype.hasOwnProperty(name)) {
   derivedClass.prototype[name] = baseClass.prototype[name];
}
```

In Ivy this does not introduce an issue for the lifecycle exactly because of #31495, so let's keep the discussion central to that thread.

**Comment by kumaresan-subramani** [comment]
HI @JoostK ,

Thanks you so much and love you dude 🥇
