### ISSUE TITLE
Cache ngcc compiled node modules

### ISSUE THREAD

**Issue by RogierdeRuijter** [angular/angular#36076]
# 🚀 feature request

### Relevant Package
angular/compiler

### Description
Don't recompile the ngcc compilations modules when they do not change.

**For example:**

package.json
```
  "dependencies": {
    "@angular-devkit/build-angular": "0.900.5",
    "@angular/cli": "9.0.5",
    "@angular/common": "9.0.5",
    "@angular/compiler": "9.0.5",
    "@angular/compiler-cli": "9.0.5",
    "@angular/core": "9.0.5",
    "@angular/platform-browser": "9.0.5",
    "@angular/platform-browser-dynamic": "9.0.5",
    "bootstrap": "4.4.0"
  },
```

- Run `yarn install` on the package.json above
- Run `ngcc --properties es2015 browser module main`
- Update bootstap to "4.4.1"

```
  "dependencies": {
    "@angular-devkit/build-angular": "0.900.5",
    "@angular/cli": "9.0.5",
    "@angular/common": "9.0.5",
    "@angular/compiler": "9.0.5",
    "@angular/compiler-cli": "9.0.5",
    "@angular/core": "9.0.5",
    "@angular/platform-browser": "9.0.5",
    "@angular/platform-browser-dynamic": "9.0.5",
    "bootstrap": "4.4.1"
  },
```

- Run `yarn install`
- Run `ngcc --properties es2015 browser module main`

When running the ngcc command again all of the already compiled node modules get recompiled. 

### Describe the solution you'd like
Provide an option within ngcc to only compile the packages that changed.

**Comment by JoostK** [comment]
> When running the ngcc command again all of the already compiled node modules get recompiled again.

This should ordinarily not be the case, unless you ran `yarn install` again (as it clears out the `node_modules` tree). ngcc does detect when a package has already been processed, so a second run should complete fairly quickly without compiling anything.

Still, there's opportunities for ngcc to benefit from a global cache so that recompiling a certain package's version for a particular version of Angular doesn't have to be repeated across multiple projects or yarn installs.

**Comment by RogierdeRuijter** [comment]
@JoostK 
`unless you ran yarn install again (as it clears out the node_modules tree)`.

This does not seems to be the case. If you mean with `clears out the node_modules` that yarn removes the processed packages.

With the example above:
- Run `yarn install`
- Run `ngcc --properties es2015 browser module main`
- Update bootstrap to 4.4.1
- Run `yarn install`

When opening the angular/core folder in the node modules. The esm5 folder is still there. 

Therefore, I believe that the ngcc compiler is removing them or not registering that they are already there.

**Comment by JoostK** [comment]
The exact details of clearing the `node_modules` tree is unknown to me, but previously processed packages will have been restored to their original state.

> When opening the angular/core folder in the node modules. The esm5 folder is still there.
>
> Therefore, I believe that the ngcc compiler is removing them or not registering that they are already there.

I'm not sure I follow what you mean here. The `esm5` folder is always present, whether the package has been processed or not. ngcc itself will only remove previous compilation results if its version has changed, but that only occurs when using NPM, not Yarn (as NPM does not reset the `node_modules` tree upon installation).

**Comment by RogierdeRuijter** [comment]
Ok, I see, thanks!

**Comment by Sukesh-Gundoji** [comment]
@JoostK  need help on how to run ngcc command explicitly without using postinstall option while I am building angular libraries(monorepo) where "enableIvy" is turned to be false 

please note I am using ng-packagr for building my angular libraries.

**Comment by alxhub** [comment]
Closing as the (original) issue is resolved. @Sukesh-Gundoji, please file your own issue with a specific reproduction of a bug if you're having trouble with one - the Angular Github issue tracker is not an ideal forum for support requests. I suggest you go to Gitter or StackOverflow if you need help configuring your Angular build.

**Comment by RogierdeRuijter** [comment]
@alxhub 
This issue was moved to the backlog a couple of days ago, doesn't the ticket need to stay active for it to be picked up?

Or does closing it mean it is no longer seen as something useful to build?
