### ISSUE TITLE
Can't bind to 'formGroup' since it isn't a known property of 'form'

### ISSUE THREAD

**Issue by r-shakeri** [angular/angular#36070]
hi

i'm working on angular 9 ssr, and using reactive forms, i get this error when i use `npm run dev:ssr`, i checked all possible ways to solve it, i added related module `ReactiveFormsModule` to the `AppModule` module, then i tried adding it to the `AppServerModule` module too, also i added `FormsModule` to both modules but unfortunately i got no answer, and again and again there was console error for me.

could someone please tell me what is the problem here, i don't know what should i do?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

---

Unfortunately, the description doesn't provide enough information to be able to assess your problem. The issue template contains instructions on what information is needed for investigation, so please open a new issue to provide us with the necessary details.
