### ISSUE TITLE
Comma to remove on code

### ISSUE THREAD

**Issue by meriturva** [angular/angular#36081]
Just see:

https://github.com/angular/angular/blob/669df70da521fb190454088d69588e776b44f94e/packages/core/src/core_private_export.ts#L31

**Comment by petebacondarwin** [comment]
Thanks for pointing this out @meriturva. This is valid TypeScript code. One could consider it a stylistic issue. If you want to create a PR with the change, please go ahead. Closing this issue as it is not a bug in Angular we don't need to track it.

**Comment by petebacondarwin** [comment]
Closing this issue as it is not a bug in Angular we don't need to track it.

**Comment by JoostK** [comment]
Given that this is valid syntax and the code formatting linter is not complaining, I'm closing as not an issue.
