### ISSUE TITLE
Service Worker - handle redirects

### ISSUE THREAD

**Issue by klemenoslaj** [angular/angular#36099]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/service-worker

### Description

Without the service worker we redirect the `navigate` request with 302 to the authentication and then either to the login or back to the document.
When we enable the service worker the `index.html` is obviously cached, therefore the request never happens.

Would it be possible to configure service worker to somehow handle the 3xx requests?

### Describe the solution you'd like
For `navigate` requests try the network first, fall back to the cache, finally the offline page.

Something like:

```ts
if (isNavigationRequest(request)) {
  const navigateRequest = new Request(url, {
    method: 'GET',
    headers: request.headers,
    mode: request.mode == 'navigate' ? 'cors' : request.mode,
    credentials: request.credentials,
    redirect: request.redirect
  });

  event.respondWith(
    fetch(navigateRequest)
      .then(/*NETWORK - cache the result*/)
      .catch(/*Use from cache*/);
  );
}
```

This could be hidden behind the flag in ngsw-config.

### Describe alternatives you've considered

We could probably exclude `index.html` from caching but that's not a good idea as offline mode wont work.

---

If that happens to be something we could implement, I would love to contribute.

**Comment by gkalpak** [comment]
While supporting this would be possible, it would add quite a bit of extra logic and complexity (from a maintenance standpoint). It would also make understanding the configuration/behavior of the Angular SW more complicated for developers.

I feel like this is too specific a usecase (and one that doesn't fit very well with SW caching) to be worth supporting in `@angular/service-worker`.

Personally, I would consider redirecting to login from the client (subject to whether the browser is online or not).

##
For very specific usecases, such as yours, I would opt for a more customizable solution, such as hand-crafting a SW with the help of Workbox.

Currently, `@angular/service-worker` puts more emphasis on ease of installation and use than customizability and (for better or worse :grin:) that means there are certain usecase it can't accomodate for.

I am going to close the issue, but feel free to continue the discussion below.

**Comment by klemenoslaj** [comment]
@gkalpak thanks for detailed reply. I thought it could be a nice addition, but of course if it is against your design goals it makes little sense discussing further.

> Personally, I would consider redirecting to login from the client (subject to whether the browser is online or not).

That's exactly the attack plan now, while trying to keep `@angular/service-worker`. Thanks :+1:
