### ISSUE TITLE
Step by Step Guide: User Input : Minor Issue

### ISSUE THREAD

**Issue by flobrflo** [angular/angular#3610]
On Final Code part, there is a syntax error on directives : 
directives: \[NgFor, NIf\] ( instead of NgIf )

**Comment by vicb** [comment]
Are you referring to https://angular.io/docs/js/latest/guide/displaying-data.html ?

The `<li>`actually makes use of `NgFor`.

Please also note that angular.io relates issues should be reported at https://github.com/angular/angular.io/issues

Thanks

**Comment by khyamay** [comment]
I think he is referring to ``` https://angular.io/docs/js/latest/guide/user-input.html ``` where there is typo for NgIf should be ``` directives: [NgFor, NgIf] ``` instead of ``` directives: [NgFor, NIf] ```. But yeah, it is related to angular.io and should be reported there.

**Comment by flobrflo** [comment]
Exactly,
i rewrite the issue on angular.io,
thanks for answer =)
