### ISSUE TITLE
Preloading lazy modules are freezing the UI

### ISSUE THREAD

**Issue by bhushan-2** [angular/angular#36100]
Hi,

We are preloading modules in angular application by using custom preloading strategy. Our purpose of using preloading is to reduce intial load time and user can interact with home page meanwhile lazy module will load in the background in async way. But application home page(UI) gets freeze until the whole preload module gets loaded in the background. We have tested this using AOT compilation as ng build --prod provides it by default also by using --aot separate flag.
Even we have referred previous open issues but no solution is provided yet.

Below is our preloading strategy:

import { PreloadingStrategy, Route } from '@angular/router';
import { Observable, of } from 'rxjs';

export class CustomPreloadingStrategy implements PreloadingStrategy{

    preload(route: Route, loadModule: Function): Observable<any> {
        return route.data && route.data.applyPreload ? loadModule() : of(null);
    }
}

**Angular Version:**
Angular 7.1.0

Expected Behaviour:

User should be able to access UI at the same time when preloaded module getting load in the browser.

**Comment by JoostK** [comment]
Hey, I'm afraid there's not enough information available to investigate. What do flame graphs show in a profiler (in Chrome's Web Inspector, open the Performance tab and click the "Start profiling and reload page" button in the top left corner of the Performance panel)

**Comment by JoostK** [comment]
Also, what's the code of the `loadModule` function?

**Comment by bhushan-2** [comment]
@JoostK 

I have attached screenshot of flame graph.
![flame-graph](https://user-images.githubusercontent.com/25223097/76870769-24c9b680-6890-11ea-8180-d0c846c51e64.png)

There is no specific code of loadModule function we are using. The preload method takes two parameters: a route and the function that actually does the preloading.

Even if I use delay for preloading module, before preload module starts downloading UI becomes interactive and when module preloading starts it becomes unresponsive/freeze.

**Comment by JoostK** [comment]
It would really help if you could export that profile and share it (the screenshot doesn't tell much). Right click in the performance panel and choose "Save profile...". If the same issue occurs with `--prod` vs `--aot` then prefer to share the results using the `--aot` flag, as that is not mangled.

**Comment by bhushan-2** [comment]
Hi @JoostK 

Sharing the result of profiling using --aot flag. As JSON file is not supported sharing the txt file.
[Profile-20200317T212108.txt](https://github.com/angular/angular/files/4344355/Profile-20200317T212108.txt)

**Comment by JoostK** [comment]
I had a look around the profile but I can't trace what's going on, without knowing what's actually happening and what is expected to happen. As a heads up, make sure to always profile in Incognito windows to disable extensions, these can have a major perf impact and create noise in the trace.

**Comment by bhushan-2** [comment]
Well, looks like javascript is single threaded so when preloading of module starts it halts the current execution means it makes UI stuck on something (freezes loaded application) and when downloading of preloading module completes it resume the UI.

For reference you can see previously open issue like #28270, #809
