### ISSUE TITLE
Getting `Type 'undefined' is not assignable to type` when using the disabled attribute

### ISSUE THREAD

**Issue by IonelLupu** [angular/angular#36107]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler or a package related to templates (not sure)

### Is this a regression?

 I didn't test on older versions but I think this issue was always there

### Description

 
I have a component with a optional property `user?: User` and a method, `processUser`, that processes that user. Of course, because the `user` property is optional I have to check that in my method:
```html
<button (click)="processUser()">Process user</button>
```
```ts
processUser(){
    if(!this.user){
        return
    }
    // ... process here
}
```

Then I got the idea to make the `processUser` take the user parameter by passing it in the template:

```html
<button (click)="processUser(user)">Process user</button>
```
```ts
processUser(user: User){
    // ... now the processUser is cleaner
}
```
This works in dev mode but it will scream when building for prod with:
```
 Argument of type 'User | undefined' is not assignable to parameter of type 'User'.
```

This is great since this is protecting us. All I have to do is to add an `*ngIf` to my button:
```html
<button *ngIf="user" (click)="processUser(user)">Process user</button>
```
The problem raises when I want to use the `disabled` attribute on the button instead of `*ngIf`, because removing the button from the UI looks weird in my deisgn:
```html
<button [disabled]="!user" (click)="processUser(user)">Process user</button>
```
I now get the error above even if the user, technically, cannot click the button  because it is disabled. 

Is it possible to make the template parser check for the disabled attribute and if it's true, not to check the `(click)` event? if not, what is possible workaround?

PS. _This issue might also be a feature request_

## 🔬 Minimal Reproduction

[Stackblitz link](https://stackblitz.com/edit/angular-issue-repro2-zr6f8m?file=src%2Fapp%2Fapp.component.ts)

## 🔥 Exception or Error
<pre><code>

Argument of type 'User | undefined' is not assignable to parameter of type 'User'.
  Type 'undefined' is not assignable to type 'User'.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.22
Node: 12.13.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.22
@angular-devkit/build-angular     0.803.22
@angular-devkit/build-optimizer   0.803.22
@angular-devkit/build-webpack     0.803.22
@angular-devkit/core              8.3.22
@angular-devkit/schematics        8.3.22
@angular/cdk                      8.2.3
@angular/cli                      8.3.22
@ngtools/webpack                  8.3.22
@schematics/angular               8.3.22
@schematics/update                0.803.22
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Comment by JoostK** [comment]
This sort of checking goes beyond what the compiler can consider sound. There's an easy workaround though, and it's to include the non-null assertion operation if you deem it safe:

```html
<button [disabled]="!user" (click)="processUser(user!)">Process user</button>
```

**Comment by IonelLupu** [comment]
I see. The issue with this workaround is in case we decide to remove the `disabled` attribute and we forget about checking the `click` one. This will introduce a bug in our app that :(.
Developers always forget . That's why we need tools to help them.

_Do you think the compiler will support this type of checking in the distant future?_

Also, I have an idea: is it possible to write something similar to this?: 
```html
<!-- I know this exact syntax is now allowed -->
<button [disabled]="user; let theUser = user" (click)="processUser(theUser)">Process user</button>
```

In the case we decide to remove the `disabled` attribute the compile will complain about not finding the `theUser` variable.

**Comment by JoostK** [comment]
I don't see something like that being supported, as it introduces a lot of potential problems related to the evaluation order of bindings.

The reason why I don't see the compiler being of any help here is that there's no guarantee that there will absolutely not be a `click` event from that element. There could be a directive active that monitors events and programmatically triggers `click` events, for instance. Also, if you were to replace `button` with e.g. `div` you do get the `click` event, so the behavior depends on HTML semantics.

**Comment by IonelLupu** [comment]
Shouldn't binding be sequential? I mean, why would be compiler parse the `click` attribute first instead of the `disabled` attribute since the `disabled` attribute is written first? 

I think Angular already does sequential binding. Take for example this:

```html
<input (ngModelChange)="change()" [(ngModel)]="name">
```

```ts
change(){
  console.log(this.name);
}
```

The `console.log` here will print the previous value of the `name` property on every model change. But if we change the order of the attributes:
```html
<input  [(ngModel)]="name" (ngModelChange)="change()">
```
Now we get the proper value in the console. I know we should be using `$event` with `ngModelChange but I wanted to demonstrate that Angular takes the order of attributes based on how they were written.
