### ISSUE TITLE
A tutorial about authentication and authorization

### ISSUE THREAD

**Issue by flyredeagle** [angular/angular#36108]
Thanks for the tutorials 
A nice to have would be an advanced tutorial with authentication and authorization

**Comment by atscott** [comment]
This is a great opportunity for the community to provide content around this but as far as a tutorial on the angular.io site goes, we feel that this is outside the realm of needed documentation for the Angular framework. The topic itself is tremendously far reaching. We provide some basic ideas for these kinds of workflows such as using guards in the router tutorial. Beyond that, a more in-depth guide for domain-specific needs should be provided elsewhere.
