### ISSUE TITLE
NGCC create-ivy-entry-points for all project libraries before parallel test

### ISSUE THREAD

**Issue by meriturva** [angular/angular#36119]
We based our new build pipeline on standard `ng cli` commands. Especially for parallel builds, we create a dependency tree reading library's package.json file and run ng build command on our libraries in a parallel way.

For this particular task, the `ngcc` call before all compilation steps works like a charm (see https://angular.io/guide/ivy#speeding-up-ngcc-compilation).

The main problem now is that we would like to run tests also on parallel way after we build our libraries. Actually, `ng test libraryName` command, just tries to compile in 'ivy' way all our libraries it depends on, every time we execute tests.

Running our CI pipeline with a sequential test approach doesn't raise errors (but it is slower). Feature requested is just related to a way to compile our project libraries on dist folder in 'ivy' way before run tests to support also parallel tests.

See for example error from our teamcity agent:

```
Start to test projects parallel with 4 cpus
08:13:46
    Start test of @aulos/core with dependencies: []
08:13:46
    Start test of @aulos/common with dependencies: []
08:13:46
    Start test of @aulos/common-validators with dependencies: []
08:13:55
    JavaScript Unit Tests
08:13:55
      18 03 2020 08:13:55.510:INFO [karma-server]: Karma v4.2.0 server started at http://0.0.0.0:9877/
08:13:55
      18 03 2020 08:13:55.526:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
08:13:55
      18 03 2020 08:13:55.545:INFO [launcher]: Starting browser ChromeHeadless
08:13:55
      JavaScript Unit Tests
08:13:56
      ERROR in ngcc is already running at process with id 4565.
08:13:56
      If you are running multiple builds in parallel then you should pre-process your node_modules via the command line ngcc tool before starting the builds;
08:13:56
      See https://v9.angular.io/guide/ivy#speeding-up-ngcc-compilation
08:13:56
      (If you are sure no ngcc process is running then you should delete the lockfile at /opt/teamcity-agent/work/d27e3f1950cca49c/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)
08:13:56
      End test process of @aulos/core with code 1
08:13:56
      We have to test 3 libraries with 2 free cpu.
08:13:56
      Start test of @aulos/security with dependencies: [@aulos/core]
08:13:56
      Start test of @aulos/globalization with dependencies: [@aulos/core]
08:13:56
      Start test of @aulos/binary-resources with dependencies: [@aulos/core]
08:13:59
      
08:13:59
      Compiling @aulos/common : es2015 as esm2015
08:14:01
      18 03 2020 08:14:01.074:INFO [karma-server]: Karma v4.2.0 server started at http://0.0.0.0:9878/
08:14:01
      18 03 2020 08:14:01.075:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
08:14:01
      18 03 2020 08:14:01.084:INFO [launcher]: Starting browser ChromeHeadless
```

As you can see we run 3 concurrency tests but they require building our libraries (for example @aulos/common).

So request here is to enable `ngcc ..... --create-ivy-entry-points` also on ./dist/libraries folders.

**Comment by petebacondarwin** [comment]
You can already point `ngcc` at your `dist/libraries` folder if you wish... You just supply the `-s` option to `ngcc`. E.g.

```
ngcc -s dist/libraries --create-ivy-entry-points
```

That being said I believe that the work that @alan-agius4 has been doing to add async pre-processing of libraries by ngcc in CLI might already help this.

**Comment by meriturva** [comment]
So thanks @petebacondarwin .
I have tried (right now) the `ngcc` with `-s` option and it works as aspected but:

after `ngcc` command we have library not ready to publish (after `ngcc` command we have library 'ivy' enabled).

So how to accomplish that flow on CI?

1. Build all for tests (without prod so ivy is enabled)
2. Test all libraries in a concurrencies way
3. Rebuild all with --prod flag
...

I guess it is going to be slower than now.
Any advice here?
Thanks.

**Comment by petebacondarwin** [comment]
I remember seeing advice (possibly from @alan-agius4) that one could make a copy of the dist folder as a post-build step before running ngcc on it. Then do your library release from the copied folder.

**Comment by meriturva** [comment]
> I remember seeing advice (possibly from @alan-agius4) that one could make a copy of the dist folder as a post-build step before running `ngcc` on it. Then do your library release from the copied folder.

Right now I agree...copy folder is the only way.
Thanks @petebacondarwin 

Just waiting for a comment from @alan-agius4 before close issue.

**Comment by alan-agius4** [comment]
Hi @meriturva, 

**Issue 1: Parallel builds**
For this issue, what @petebacondarwin suggested in here https://github.com/angular/angular/issues/36119#issuecomment-600490685 is a correct approach. Currently, NGCC async in the CLI only processes `node_modules`.  @petebacondarwin, maybe we can add the feature to provide a stringified path mappings as argument in NGCC?

**Issue 2: Bulding, Testing and Publishing a VE libraries**
I think the best approach would be to;
- Building your library in VE
- Run `npm pack`
- Run ng test, which under the hood will call NGCC that will convert your library to Ivy
- `npm publish` using the tarball generated by `npm pack`

More info about `npm pack` and `npm publish` can be found here: https://docs.npmjs.com/cli-commands/pack.html and https://docs.npmjs.com/cli/publish

**Comment by meriturva** [comment]
Actually before point 3: `run ng test (concurrency way)` we have to call ngcc for all libraries we have with `-s` param.

am I right?

**Comment by petebacondarwin** [comment]
Given the rest of the discussion here - yes. But only if you want to run your tests in parallel.

**Comment by alan-agius4** [comment]
I want to emphases what @petebacondarwin said, that this will only be needed if you run tests in parallel and not when running them concurrently.

**Comment by meriturva** [comment]
Thanks for your help and ideas!
I will test new flow and give you a feedback if necessary.

**Comment by meriturva** [comment]
I have to reopen the issue.
We have now all the libraries prepared with `ngcc` command as described above.

But when we run `ng test` file `__ngcc_lock_file__` still created and so no way to run tests in parallel.

How to avoid the creation of lock file during test phase?

**Comment by petebacondarwin** [comment]
The lockfile should only be created if ngcc is having to do further work... Are you sure that your pre-test ngcc processing was comprehensive? Is there anything in the `ng test` logs? What is the error when the lockfile has been created?

**Comment by meriturva** [comment]
I found a strange behavior of `ngcc`.
We have libraries that `ngcc` compiles correctly and other libraries where `ngcc` compiles without produce any change.

For example:

`ngcc -s ./dist/aulos/core --properties es2015 browser module main --create-ivy-entry-points`
produce output: `Compiling @aulos/core : es2015 as esm2015`
and package.json is correclty touched.

instead for:
`ngcc -s ./dist/aulos/security --properties es2015 browser module main --create-ivy-entry-points`

**no output is produced and no error is raised.**

After that when we run `ng test` for a library `ng` starts correctly `ngcc` process and all libraries are correctly compiled with output:
`Compiling @aulos/security : es2015 as esm2015`

So I guess that `ng test` just call ngcc with different parameters?

**Comment by meriturva** [comment]
Ok i have enabled `ngcc` debug logs and we have more information:

```
Debug: Running ngcc on SingleProcessExecutor.
Debug: Analyzing entry-points...
Debug: Invalid entry-point D:/Projects/git.loccioni.com/web/loccioni-aulos-web/dist/aulos/security. It is missing required dependencies:
 - @aulos/core
Debug: Analyzed 0 entry-points in 0s. (Total tasks: 0)
Debug: Processing tasks...
Debug: Processed tasks in 0s.
Debug: Run ngcc in 0s.
```
so seems that `ngcc` is not able to find dependencies, how to specify them?

**Comment by petebacondarwin** [comment]
Why are you using `-s dist/aulos/security` etc rather than just `-s dist/aulos`? The `-s` option specifies the "base path" not the "target package".

**Comment by meriturva** [comment]
Because I have tried so many configurations and this is just one of them.
Here few examples:

command: `ngcc -s ./dist -t --properties es2015 --create-ivy-entry-points -l debug`:

```
Debug: Running ngcc on ClusterExecutor (using 8 worker processes).
Debug: Analyzing entry-points...
Debug: Invalid entry-point D:/Projects/git.loccioni.com/web/loccioni-aulos-web/dist/aulos/binary-resources. It is missing required dependencies:
 - @aulos/core
Debug: Invalid entry-point D:/Projects/git.loccioni.com/web/loccioni-aulos-web/dist/aulos/code-editor-component. It is missing required dependencies:
 - @aulos/core
 - @aulos/globalization
Debug: Invalid entry-point D:/Projects/git.loccioni.com/web/loccioni-aulos-web/dist/aulos/common-components. It is missing required dependencies:
 - @aulos/common
 - @aulos/conditions
 - @aulos/core
 - @aulos/globalization
 - @aulos/layout
Debug: Invalid entry-point D:/Projects/git.loccioni.com/web/loccioni-aulos-web/dist/aulos/common-editors. It is missing required dependencies:
 - @aulos/common-components
 - @aulos/common-validators
 - @aulos/conditions
 - @aulos/core
 - @aulos/globalization
 - @aulos/parameters
 - @aulos/common
......
.....
```

another try: `ngcc -s ./dist -t aulos/security --properties es2015 --create-ivy-entry-points -l debug`:

```
Debug: Running ngcc on ClusterExecutor (using 8 worker processes).
Debug: Analyzing entry-points...
Error: The target entry-point "@aulos/security" has missing dependencies:
 - @aulos/core

    at TargetedEntryPointFinder.findEntryPoints (D:\Projects\git.loccioni.com\web\loccioni-aulos-web\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:54:23)
    at analyzeEntryPoints (D:\Projects\git.loccioni.com\web\loccioni-aulos-web\node_modules\@angular\compiler-cli\ngcc\src\main.js:78:41)
    at new ClusterMaster (D:\Projects\git.loccioni.com\web\loccioni-aulos-web\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:40:30)
    at D:\Projects\git.loccioni.com\web\loccioni-aulos-web\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\executor.js:44:46
    at LockFile.lock (D:\Projects\git.loccioni.com\web\loccioni-aulos-web\node_modules\@angular\compiler-cli\ngcc\src\execution\lock_file.js:54:30)
    at ClusterExecutor.<anonymous> (D:\Projects\git.loccioni.com\web\loccioni-aulos-web\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\executor.js:42:61)
    at step (D:\Projects\git.loccioni.com\web\loccioni-aulos-web\node_modules\tslib\tslib.js:139:27)
    at Object.next (D:\Projects\git.loccioni.com\web\loccioni-aulos-web\node_modules\tslib\tslib.js:120:57)
    at D:\Projects\git.loccioni.com\web\loccioni-aulos-web\node_modules\tslib\tslib.js:113:75
    at new Promise (<anonymous>)
```

Actually, on `ngcc` help I see just -t option with description:
```
-t, --target               A relative path (from the `source` path) to a
                             single entry-point to process (plus its
                             dependencies).
```
how to declare dependencies?
Thanks...again for your help!

**Comment by petebacondarwin** [comment]
You should not need to declare the dependencies. Do you have package.json files at each of the entry-points?

**Comment by meriturva** [comment]
Yes, sure we have package.json on every library folder (plus all dependencies seems to be correct on it).
I just remember that `ng test` works and compiles correctly with `ngcc` all libraries it needs.

**Comment by meriturva** [comment]
@petebacondarwin @alan-agius4 I have prepared a repo to reproduce issue: https://github.com/meriturva/ngccTest (as you can see it is really simple).

To reproduce issue just follow steps described on project readme.

Right now we are not able to call single `ngcc` on single library (based on each library dependency tree) because we are not able to indicate dependencies during the compile phase.

So no `ng test` on parallel.

**Comment by petebacondarwin** [comment]
Great. Thanks. I will look into it later today or tomorrow.

**Comment by petebacondarwin** [comment]
I just had a look and it seems that you have not added the libraries to the repository :-)

**Comment by meriturva** [comment]
...embarrassing...so sorry!
Added libraries on repo right now!

**Comment by petebacondarwin** [comment]
Cool! Thanks for this. I have debugged and found out that the problem is that when we point ngcc at the `dist` folder we need to also provide the `pathMappings` from the `tsconfig.json` in order that it is able to resolve the imports (e.g. `@aulos/shared` from `dist/aulos/component/fesm2015/aulos-component.js`.

I manually injected the path mappings during debug and it does indeed process the entry-point 🎉 

---

The action on us is to allow the path mappings to be provided via the command line ngcc. It is already possible to provide it programmatically, which is what the CLI does when it is calling ngcc synchronously during its builds.

**Comment by meriturva** [comment]
So thanks, I guess we are going to check tsconfig way for sure!

Just to be sure.... I see on 9.1 rc changelog:

_ngcc improvements: concurrency & reliability improvements for monorepo use-cases (npm postinstall script no longer recommended)_

So is it going to support multiple `ngcc` calls at the same time, for example running tests parallel (that is the first request of that issue).

**Comment by petebacondarwin** [comment]
The improvements to CLI+ngcc integration were to run ngcc in async mode across the `node_modules` before running the build, where ngcc can only be run in sync mode. The benefits of `async` mode are: slight performance improvement if tasks can be run in parallel; and ability for ngcc to pause and wait (rather crashing) if another build is running ngcc.

This new integration is not able to build packages that are not in `node_modules` (e.g. in `dist`) as in this scenario since at that point it does not have access to the path mappings etc. So in your case you still need to run ngcc against the `dist` folder before running `ng build` if you want to run the builds in parallel. (If the builds are not parallel then there is no problem because the sync CLI+ngcc integration can handle `dist` packages.

If we implement ngcc looking up a local `tsconfig.json` when in async parallel mode then it might be that the new async CLI+ngcc integration might be able to handle this scenario too!

**Comment by petebacondarwin** [comment]
I have a fix in the works. See #36180
