### ISSUE TITLE
HtmlParser incorrectly reports end tags (@angular/compiler)

### ISSUE THREAD

**Issue by gregjacobs** [angular/angular#36118]
# 🐞 bug report

### Affected Package

The issue is caused by package: `@angular/compiler`

### Is this a regression?

 Not sure

### Description

The Angular HTML parser incorrectly reports end tags for elements. 

I'm not sure what this could affect internally (other than incorrect reporting of html source code locations for users), but seems like something that should be fixed to make sure downstream functionality works correctly.

It's also affecting the codemod tooling that I'm building on top of Angular's HTML parser (which is how I discovered the issue).

## 🔬 Minimal Reproduction

 

```
import { HtmlParser } from '@angular/compiler';

const parser = new HtmlParser();
const ast = parser.parse(`<div><input></div>`, 'tmp.html');

console.log(ast);
```

StackBlitz: https://stackblitz.com/edit/angular-vfni6r?file=src%2Fapp%2Fapp.component.ts

The AST shows the `<input>` element having an end tag of `</div>` (via its `endSourceSpan`), and the `<div>` element has an `endSourceSpan` of `null` (signifying that it has no end tag)

## 🌍  Your Environment

**Angular Version:** StackBlitz / Angular v9.0.6

**Comment by petebacondarwin** [comment]
Tracking at FW-2004

**Comment by gregjacobs** [comment]
Thanks @AndrewKushnir, good fix!
