### ISSUE TITLE
Access custom Component from its associated formControl in another Component

### ISSUE THREAD

**Issue by lovefamilychildrenhappiness** [angular/angular#36112]
# 🐞 bug report

### Affected Package
I extracted my issue into a small git repo:
https://github.com/lovefamilychildrenhappiness/AngularCustomComponentValidation

And I provided a descriptive explanation on SO but haven't gotten any workable solutions: https://stackoverflow.com/questions/60724475/change-the-css-class-of-custom-component-from-another-component

As the git repo illustrates, the affected package is Angular8 and AngularForms. 

### Is this a regression?

I am not aware of whether it worked in previous versions. 

### Description

As I explained in the SO post, I have a custom component. This custom component is referenced in another component. This other component handles the reactive form data. Consequently, when I click a button (not a submit form button) in this other component, I can fetch the specific formControl associated with the custom component. But if the formControl is not valid (it is blank), then I need to add a css class to the custom component. Note that the formControl has a Validators.required validation on it already, and the custom component implements both NG_VALUE_ACCESSOR and NG_VALIDATORS.   

## 🔬 Minimal Reproduction
https://github.com/lovefamilychildrenhappiness/AngularCustomComponentValidation
-->

## 🔥 Exception or Error
There are no exceptions. There is no way I am aware of to access the component in another component by its related formControl. I report it has a bug because this is a fundamental necessity in web development (without being able to change the css class based on some condition, it's not a web framework), and I spent over 5 hours searching feverishly for a solution to no avail. 

## 🌍  Your Environment

**Angular Version:**
<pre><code>
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.22
Node: 12.6.0
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.22
@angular-devkit/build-angular     0.803.22
@angular-devkit/build-optimizer   0.803.22
@angular-devkit/build-webpack     0.803.22
@angular-devkit/core              8.3.22
@angular-devkit/schematics        8.3.22
@angular/cdk                      8.2.3
@angular/cli                      8.3.22
@angular/material                 8.2.3
@ngtools/webpack                  8.3.22
@schematics/angular               8.3.22
@schematics/update                0.803.22
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Comment by AndrewKushnir** [comment]
Hi @lovefamilychildrenhappiness, it looks like there is an accepted reply on SO, so I'm closing this ticket. Feel free to reopen or create a new one if the problem still exists. Thank you.
