### ISSUE TITLE
Add git as prerequisite of Angular setup

### ISSUE THREAD

**Issue by ranaivomahaleo** [angular/angular#36124]
Please add in the docs that GIT is among the prerequisites of Angular setup.
This issue is specifically right under Windows machine which have no GIT pre-installed.

**Comment by ajitsinghkaler** [comment]
@ranaivomahaleo o we really need git for an angular setup I removed git and npm was working fine we only need npm and node for the proper working of angular

**Comment by EmmanuelDemey** [comment]
We do not need git at all. 
You can skip the creation of the git repository by using the skipGit flag with @angular/cli new command.

**Comment by ajitsinghkaler** [comment]
@kapunahelewong @gkalpak I think we can close this

**Comment by gkalpak** [comment]
@ranaivomahaleo, if you ran into a specific issue by not having git installed, feel free to let us know below (or on a new issue).
