### ISSUE TITLE
Router should push to history if the state differs from the previous when the url is the same

### ISSUE THREAD

**Issue by ayeletdn** [angular/angular#36128]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 I'm not sure

### Description
 When using a resolver to load a resource and the resource fails, trying to redirect the user to the same route they are currently on does not set the router's `state`. 
```
this.router.navigate(['route1'], { state: { resolveFailed: path } });
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Use case: 
A table shows the user a list of items. The user requests to load a given item using the resolver, but the item no longer exists on the list. The API will return an error which requires preventing the user from navigating to the resource's page, but still showing an error message. Setting the `state` on the navigation extras can be used exactly for this purpose.

## 🔬 Minimal Reproduction

 

[Reproduced issue on Stackblitz](https://stackblitz.com/edit/angular-resolve-router-state-failure?file=src/app/route3/route3-resolver.service.ts)

### Steps:
1. click on route1 button, text should say `Route 1 State: {"fromPage": "main", "navigationId": ...}`
2. click on route2 button, text should say `Route 2 State: {"fromPage": "main", "navigationId": ...}`
3. click again on route1 button
4. click on route3 button, text should say `Route 2, State: { "resolveFailed": "https://api.example.com", "navigationId": ... }`
5. click on route1 button
6. click on route2 button, text should say `Route 2 State: {"fromPage": "main", "navigationId": ...}`
7. click on route 3 button:

Text **should** say `Route 2 State: {"resolveFailed": "https://api.example.com", "navigationId": ...}`
**Actual** text displayed: `Route 2 State: {"fromPage": "main", "navigationId": ...}`

### Explanation:
Route 3 has a resolver which connects to a resource that doesn't exist, that in turn throws an error, caught by `catchError` rxjs operator. The catchError redirects the user back to `route2`. 
- If the user asked to navigate to the route from route1, then the state will be set successfully, as seen in step 4. 
- If the request was made from `route2`, then the user doesn't effectively change route and the state doesn't get set.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

8.2.14
</code></pre>

**Comment by atscott** [comment]
I believe this is working as expected, at least in the example you've provided. If you enable tracing, you'll see that the last navigation was cancelled, so the router state should not be changed. Can you explain why you would expect the state to change even if the navigation gets cancelled?

**Comment by ayeletdn** [comment]
Fair point.
To answer your question specifically, the answer is: No, if the navigation is **canceled**, then the state shouldn't change.

I would like to argue though, that canceling the navigation is wrong in this case. A navigation action was clearly requested, even if it is for the same resource. If the navigation is a valid request, therefor the state change should be valid as well. 

Thinking about this further, when the navigation request gets added to the stack along with its state, then when the user navigates back through history, they will experience a strange case of "trying to navigate to a place they never reached" and getting an error for it. It's a strange state, but it is part of history, and we wouldn't want to rewrite history, would we 😉.

**Comment by atscott** [comment]
Not pushing to the history when there is a same url navigation *is* working as intended. However, if your argument is that the router should still push to history if the state differs from the previous, then I can understand that as a bug/feature request. If we agree on this as the scope of the report, could you update the title/description of the issue?

**Comment by ayeletdn** [comment]
Agree.
Done.

**Comment by eaglet** [comment]
Hi, I would like to work on this bug. Is it ok?

**Comment by atscott** [comment]
Hi @eaglet, there's currently no formal process for claiming issues marked with the community help label. You're welcome to work on this.

**Comment by eaglet** [comment]
Hi @atscott, Thanks for your reply.
To clarify the problem further, is push to history means the router should take the state as a condition for deciding processing it or not? 
And also, since the URL is the same, should the browser refresh the page in this situation (The URL is the same but state is different.)?
