### ISSUE TITLE
Make compiler-cli use less regexes for performances

### ISSUE THREAD

**Issue by rmannibucau** [angular/angular#36148]
# 🚀 feature request

### Relevant Package
    @angular/compiler-cli util regexes

### Description
Using ng-packagr, (more precisely @angular-devkit/build-ng-packagr:build), program (and therefore utils) from compiler-cli are used a lot and compileSourceFiles() from ng-packagr is quite slow.
it seems that creating the diagnostics is slow (when the impl is not a no-op) because it iterates over the source files (which can be from node_modules, in my project I have ~720 files whereas the project code is ~15files) and moreover because it uses regexes for simple extractions (https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/compiler-cli/src/transformers/util.ts#L15). Replacing these regexes by a custom implementation with fast exit and just doing endsWith already saves some time (I just mocked a regex with {test:..., exec:...}).
I'm not 100% sure it is the best solution since ng-packagr can also avoid to compileSources twice but globally getting the diagnostics should be fast anyway, done once or twice, so i guess compiler-cli should be enhanced anyway.

### Describe the solution you'd like
Have this snippet taking no more than some milliseconds:

        const allDiagnostics = [
            ...ngProgram.getTsOptionDiagnostics(),
            ...ngProgram.getNgOptionDiagnostics(),
            ...ngProgram.getTsSyntacticDiagnostics(),
            ...ngProgram.getTsSemanticDiagnostics(),
            ...ngProgram.getNgSemanticDiagnostics(),
            ...ngProgram.getNgStructuralDiagnostics(),
        ];

### Describe alternatives you've considered
Using a custom webpack based build and skipping "ng" build ecosystem but i'd like to stick with official tools if possibles.

**Comment by JoostK** [comment]
The good news is that the Ivy compiler doesn't do regex matches for this purpose anymore, the bad news is that ng-packagr has to keep using the old compiler to generate ViewEngine compatible libraries.

**Comment by JoostK** [comment]
I am closing this request as I've not experienced regex testing to be a performance bottleneck, at least not in Ivy.

**Comment by rmannibucau** [comment]
Did you try with huge compilation units? Like node_modules to have some sized unit?

**Comment by JoostK** [comment]
> Did you try with huge compilation units? Like node_modules to have some sized unit?

Yes I have! I have been profiling using [ng-speed-rebuild](https://github.com/elvisbegovic/ng-speed-rebuild) and [ng9-aot-build-times](https://github.com/vaindil/ng9-aot-build-times) which have over 1000 components (I believe the latter has 2800 components). However, these measurements were done using the Ivy compiler, whereas the regexes you mentioned are for the View Engine compiler. I noticed you also reported this for ng-packagr so you are likely seeing this in library compilations, which can now be built using the Ivy compiler as well (starting from v12, if targeting Ivy apps that also use v12).

**Comment by rmannibucau** [comment]
@JoostK ok, guess I will need to wait a bit but that the project can't help too much too now. Thanks a lot for the feedback!
