### ISSUE TITLE
In Ivy, pipes uses providers from a host component where ViewEngine did not

### ISSUE THREAD

**Issue by EmaGht** [angular/angular#36146]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?
Yes, works without ivy

### Description
I think it's related to this https://github.com/angular/angular/issues/34227 but i'm not really sure.
What i have is a component let's say `component1` that passes an Input to another component `component2` and `component2`shows it as-is.
The problem is that this input gets transformed by a pipe that retrieves via injector the informations to transform this Input. This informations is stored component-wise. `component2` also provides it, but for his own data.
Unfortunately, the pipe in question, used in the template of `component1` ends up using the dependency declared in `component2`, probably because the execution gets delegated after change detection has been run, therefore the context of the pipe changes

I'm not honestly sure my English is good enough to explain this properly but luckily i have a repro

## 🔬 Minimal Reproduction
repo: https://github.com/EmaGht/ivypipe
ng-run version: https://ng-run.com/edit/32k314W605UdYOdVEPCE
Steps:
git clone https://github.com/EmaGht/ivypipe.git
cd ivypipe
npm install
ng serve
check out the on-screen debug informations

For now i think i can work around it telling the pipe explicitly which context should be used but... meh

**Comment by pkozlowski-opensource** [comment]
Thnx for reporting the issue and providing the reproduce scenario! We will look into this one but if you want to speed up things and help us investigate, providing a minimal, runnable reproduce scenario with https://ng-run.com/ would help immensely!

**Comment by EmaGht** [comment]
Sure thing, here you go:

https://ng-run.com/edit/32k314W605UdYOdVEPCE

**Comment by JoostK** [comment]
I briefly looked into this and found that the pipe in Ivy is able to see `providers` of the host component `app-component-child`, unlike ViewEngine where this was not the case.

There's no static inputs going here, as a pipe can only be present in a a dynamic binding. I'll update the title to this effect.

**Comment by JoostK** [comment]
Tracking in FW-2012

**Comment by EmaGht** [comment]
I've tried updating all the packages in my example project but this issue doesn't seem to be fixed...
Updating the ng-run version seems impossible (it gets stuck on "generating preview" for literally days), but updating the github repository and serving it yields the same results as before

**Comment by crisbeto** [comment]
The fix for your case, after the changes have been applied, is to switch from `providers` to `viewProviders`.

**Comment by EmaGht** [comment]
> 
> 
> The fix for your case, after the changes have been applied, is to switch from `providers` to `viewProviders`.

Ok, can confirm it works using `viewProviders ` instead of `providers`. Thanks!
