### ISSUE TITLE
Can't get ETag header from HttpClient response headers

### ISSUE THREAD

**Issue by lyon-liao** [angular/angular#36151]
My true question is [stackoverflow](https://stackoverflow.com/questions/60737381/angular8-get-full-of-httpclient-response-headers).

And I can not get full of Http response headers from HttpClient. the [stackblitz demo](https://stackblitz.com/edit/angular-b4vtlv?embed=1&file=src/app/app.component.ts)

And If I want to use ETag with JSON file, what is the best way.

**Comment by pankajparkar** [comment]
This doesn't seems to be Angular specific problem. You have to expose this `ETag` header from your server setting, that would fix the issue.

https://stackoverflow.com/questions/21345814/etag-header-not-returned-from-jquery-ajax-cross-origin-xhr

**Comment by lyon-liao** [comment]
@pankajparkar Thank you for your reply. The ETag header is in HTTP headers, but not in HttpClient response headers.  you can find it in chrome network tool in [stackblitz demo](https://stackblitz.com/edit/angular-b4vtlv?embed=1&file=src/app/app.component.ts)

**Comment by lyon-liao** [comment]
@pankajparkar You are right.  I misunderstand the `Access-Control-Expose-Headers` and I added to the request header. On the face of this issue is `cors`. Thanks
