### ISSUE TITLE
Docs: Testing section: component-class-testing, a little mistake

### ISSUE THREAD

**Issue by Fouzyyyy** [angular/angular#36155]
# 📚 Docs or angular.io bug report

### Description

There is a misleading sentence in the component class testing section, precisely the following sentence: This component class has no dependencies. To test a service with no dependencies, you create it...

Here, we jump from testing a component to testing a service.

## 🔬 Minimal Reproduction

This can be checked here: https://angular.io/guide/testing#component-class-testing

### What's the affected URL?**
https://angular.io/guide/testing#component-class-testing

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by Fouzyyyy** [comment]
I can submit a MR to fix this.

**Comment by sonukapoor** [comment]
@Fouzyyyy Go for it. Let us know if you need any help.
