### ISSUE TITLE
ngcc documentation needed

### ISSUE THREAD

**Issue by Willey1986** [angular/angular#36154]
# 📚 Docs or angular.io bug report

### Description

It seems like the ngcc compiler can be configured via flags or `ngcc.config.js` but I cannot find any documentation for it.

* In the offical angular.io docs (https://angular.io/guide/ivy) there is section about ngcc but without any further explanation about the used flags (**--properties** es2015 browser module main **--first-only** **--create-ivy-entry-points**).
* In some other issues if found a flag **-s** what's the purpose of it?
* It seems like I can configure the compiler with a `ngcc.config.js` file. When googling `ngcc.config.js` I cannot find any official documentation about it. What's the structure? Which options are available?

Am I just to dumb to find a documentation about ngcc? 

### What's the affected URL?
https://angular.io/guide/ivy

**Comment by petebacondarwin** [comment]
You are not dumb! There are no docs yet but we are working on it. Originally we had hoped that ngcc would be transparent to the developer and so would not need to understand how to configure it. And that is actually true in the majority of cases. But for a few corner cases (and for debugging some issues) it is helpful to be able to configure it.

Here is an initial draft that will hopefully arrive in the main docs guides soon: https://hackmd.io/Uzjupq0FQfyxX9zKJlTWBQ

You can also get some help by running `ngcc --help`, which should describe all the available command line options (but not the configuration file stuff).

**Comment by Willey1986** [comment]
Thank you! 
Looking forward to the finished documentation.
