### ISSUE TITLE
I want to know if a locale uses am/pm or 24-hour clock

### ISSUE THREAD

**Issue by jdcai** [angular/angular#36150]
# 🚀 feature request

### Relevant Package
@angular/common

### Description
I want to know if a locale uses am/pm or 24-hour clock.

### Describe the solution you'd like
I want to be able to call a method and pass it a locale and it will return something that tells me which one it uses. Or something like `is24Hour(locale) ` that returns a Boolean

### Describe alternatives you've considered

One alternative I could find was to use getLocaleTimeFormat() and check if the format uses h/hh for am/pm or H/HH for 24 hour

**Comment by petebacondarwin** [comment]
As explained in the associated PR at #36184 - this is not something we should add to the core API at this time. Feel free to include it as a helper in your own application projects.
