### ISSUE TITLE
TS2340 Only in libraries

### ISSUE THREAD

**Issue by brunosantosrhsenso** [angular/angular#36167]
I've created an workspace using Angular 9.0.7:

`ng new MyWorkspace --create-application=false`

In the workspace I created an application:

`ng g application MyApplication`

and a library:

`ng g library MyLibrary`

So at this point both the application and the library are in the same workspace and using the same version of angular/typescript.

I tried to override a getter on both sides, with different results:

```
export class AppComponentBase {
  public get name(): string {
    return 'My';
  }
}
export class AppComponent extends AppComponentBase {

  public get name(): string {
    return super.name + 'Application';
  }
}
```

this compiles without a problem. but this:

```
export class MyLibraryComponentBase  {
  public get name(): string {
    return 'My';
  }
}

export class MyLibraryComponent extends MyLibraryComponentBase {

  public get name(): string {
    return super.name + 'Application';
  }
}
```

does not compile. I get TS2340: Only public and protected methods of the base class are accessible via the 'super' keyword.

I'm using the exact same sintaxe and semantics, all things equal, can't quite figure out why the app compiles ok but the library does not.

Here's a repository with a working example:

https://github.com/brunosantosrhsenso/TS2340

**Comment by JoostK** [comment]
The error occurs in libraries because they are downleveled to ES5, in which case TypeScript produces this error as this usage is not supported.

More info in [on StackOverflow](https://stackoverflow.com/questions/50283360/typescript-error-ts2340-public-methods-accessible-via-super-keyword) and Microsoft/TypeScript#338.

**Comment by brunosantosrhsenso** [comment]
I appreciate the answer but neither link explains why "libraries are downleveled to ES5". Is this a Typescript thing or an Angular thing? Could you point me to a link expanding on why libraries target ES5?

**Comment by JoostK** [comment]
Oh, sorry. I put the references there regarding TypeScript's behavior, not Angular's ;)

Libraries are packaged using [ng-packagr](https://github.com/ng-packagr/ng-packagr) (the CLI delegates its work to that tool) to create a bundle that follows Angular Package Format (APF), [as documented on Google Docs](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview). At the moment, the specification mandates that ES5 formats have to be present, hence they are being generated for all libraries.

The relevance of the ES5 bundles have diminished with the introduction of differential loading, and there's ideas to revisit the APF specification to drop the ES5 bundle, so this is likely to change in the future.

**Comment by brunosantosrhsenso** [comment]
Much appreciated!
