### ISSUE TITLE
Not able to use component in child module 

### ISSUE THREAD

**Issue by nikhildhar1992** [angular/angular#36166]
Hi ,
I am not able to call components in child module.Please check below code:

**Approunting**:
 export const routes: Routes = [
    { path: 'dashboard', loadChildren: './components/dashboard/dashboard.module#DashboardModule'},]
**Dashboard modules.ts**  
     export const routes: Routes = [
      { path: '',component: DashboardComponent ,children: [
      { path: 'library', loadChildren: '../library/library.module#LibraryModule' },
      ]}];
**Dashboard html**:
   <div class="row no-gutters"><router-outlet></router-outlet></div>

**Library module:**
    import { SplitScreenComponent } from '../split-screen/split-screen.component';
    declarations: [SplitScreenComponent],
    entryComponents: [SplitScreenComponent],

So when I come to library page I am getting error like below:

**Error: No component factory found for SplitScreenComponent. Did you add it to @NgModule.entryComponents?**

Please comment what can be the issue,

Thanks

**Comment by floinay** [comment]
add routes to child Library module
const routes: Routes = [
  {
    path: '',
    component: SplitScreenComponent
  }
];

imports: [
RouterModule.forChild(routes)
]

**Comment by nikhildhar1992** [comment]
> **add routes to child Library module**
> 
> ```
> const routes: Routes = [
>   {
>     path: '',
>     component: SplitScreenComponent
>   }
> ];
> 
> imports: [
> RouterModule.forChild(routes)
> ]
> ```

I have like below:
export const routes: Routes = [
  { path: '', component:LibraryComponent }
];

**Comment by nikhildhar1992** [comment]
> > **add routes to child Library module**
> > ```
> > const routes: Routes = [
> >   {
> >     path: '',
> >     component: SplitScreenComponent
> >   }
> > ];
> > 
> > imports: [
> > RouterModule.forChild(routes)
> > ]
> > ```
> 
> I have like below:
> export const routes: Routes = [
> { path: '', component:LibraryComponent }
> ];

Also I am using splitscreen as modal so in library component I am calling like below:
let ngbModalOptions: NgbModalOptions = {
      backdrop: 'static',
      keyboard: false,
    };
    const modalRef = this.modalService.open(SplitScreenComponent, ngbModalOptions);

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
