### ISSUE TITLE
angular ssr authentication issue

### ISSUE THREAD

**Issue by r-shakeri** [angular/angular#36163]
the problem is how to authenticate user on server side? i hear rapidly that authentication should done on client side using `isPlatformBrowser`. but the problem is when user is login and then we send a request to the angular ssr, here rendering page is not correct, instead of seeing the correct page, user will see login page! i'm wondering that no body mentioned this issue!!! also infer 2 ways: 1: on the server side, we should request to the api server and get approve that user is valid or not. 2: we use cookie and check if there is a specific key in cookie on the authGuard

i want to know is there any other way that is better that mine? and also want to know if i use cookie approach, is it safe just to check for its existing and no one other than api server can add it manually or not?

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by r-shakeri** [comment]
@JoostK , i see, but i posted my issue at stackoverflow at first, but no one answered me, and i wanted angular's developers give me the best answer because i've searched for some days without any good answer, and now i see i was wrong...
