### ISSUE TITLE
IE11 only: blur and multiple focus events sent for animated elements' children

### ISSUE THREAD

**Issue by jzabinski** [angular/angular#36175]
# 🐞 bug report

### Affected Package

3 different packages are involved in the issue: @angular/animations, the package containing ng-container, and the package defining structural directives.

### Is this a regression?
No

### Description
Focusing on a child element in a very specific configuration will cause the intended focus to be triggered, followed by a blur, followed by a second iteration of the intended focus.

## 🔬 Minimal Reproduction
I created [a Github repository](https://github.com/jzabinski/multipleEventsOnFocus) for the problem since Stackblitz doesn't seem to run in IE11.

To reproduce:
1. Clone the repository.
2. 'npm install'
3. 'ng serve'
4. Open IE11, and navigate to https://localhost:4200.
5. Open IE11's Developer Tools
6. Click the text 'Click this to make a button appear' appearing on the page. Watch the console, and you should see three messages:
'button focused'
'button blurred, currently active element: BODY'
'button focused'

## 🔥 Exception or Error
Not applicable

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.7
Node: 12.13.1
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

This happens in IE11 only: version 11.657.18362.0. If you try the steps to reproduce in Chrome or Edge, you will only get a message saying 'button focused'.

Very important detail: this behavior only occurs in the following template setup:
```
<ng-container *ngIf="modalActivated === true">
    <div @popoverAnimations>
        <ng-container [ngTemplateOutlet]="popoverContent"></ng-container>
    </div>
</ng-container>

<ng-template #popoverContent>
    <button #example (focus)="onFocus()" (blur)="onBlur()">Just a button</button>
</ng-template>
```

So you need:

1. A parent ng-container using an *ngIf to determine whether to display
2. A child element using an animation
3. A child ng-container receiving an ngTemplateOutlet

Then if a ViewChild is used to focus on the button in IE11, you will get an extra blur and another focus. Taking away any of those three factors removes the ability to reproduce the issue.

**Comment by jzabinski** [comment]
I should note that sometimes I have seen Angular trigger element focus correctly, then trigger a blur without returning focus, unlike in the Minimal Reproduction. But regardless, my guess is that Angular should not be triggering a blur on the focused element in the first place.

**Comment by matsko** [comment]
Hey @jzabinski. Thank you for posting this. We are looking into it.

**Comment by AndrewKushnir** [comment]
Closing this ticket, since the reported problem was only present in IE11 and Angular no longer supports IE.
