### ISSUE TITLE
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for '@routeAnimations': 'undefined'. Current value: 'NewAnimationName'.

### ISSUE THREAD

**Issue by acohenOT** [angular/angular#36173]
[RouteAnimationError.zip](https://github.com/angular/angular/files/4361634/RouteAnimationError.zip)

# 🐞 bug report

### Affected Package

 Not clear. 
Possibly @angular/animations or @angular/router

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.3

### Description

Using route animation with a parent element that is conditionally hidden, causes ExpressionChangedAfterItHasBeenCheckedError. This did not happen in Angular 8.3. Began with Angular 9.

Possibly related to issue https://github.com/angular/angular/issues/34821.

**Error occurs with**
```
<div *ngIf="!mobileQuery.matches">
    <div [@routeAnimations]="prepareRoute(outlet)">
        <router-outlet #outlet="outlet"></router-outlet>
    </div>
</div>
```

**No error occurs with**
```
<div>
    <div [@routeAnimations]="prepareRoute(outlet)">
        <router-outlet #outlet="outlet"></router-outlet>
    </div>
</div>
```

## 🔬 Minimal Reproduction
Unable to recreate in stackblitz. See attached min repro project.

Steps:

<ol>
<li>Unzip attached project</li>
<li>Run <strong>npm install</strong></li>
<li>Run <strong>ng serve --open=true</strong></li>
<li>Navigate to <strong>/home</strong> URL</li>
<li>Open Developer tools, notice error</li>
</ol>

<img width="1336" alt="screenshot" src="https://user-images.githubusercontent.com/34688558/77237575-d1ad7780-6b9f-11ea-82b3-8dfcc0a190ea.png">

## 🔥 Exception or Error
<pre><code>
core.js:6185 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for '@routeAnimations': 'undefined'. Current value: 'HomePage'.
    at throwErrorIfNoChangesMode (core.js:8092)
    at bindingUpdated (core.js:19773)
    at Module.ɵɵproperty (core.js:20921)
    at StandardLayoutComponent_div_2_Template (standard-layout.component.html:9)
    at executeTemplate (core.js:11949)
    at refreshView (core.js:11796)
    at refreshDynamicEmbeddedViews (core.js:13154)
    at refreshView (core.js:11819)
    at refreshComponent (core.js:13229)
    at refreshChildComponents (core.js:11527)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.7
Node: 13.11.0
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@angular/cdk                      9.1.3
@angular/material                 9.1.3
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.42.0
</code></pre>

**Comment by acohenOT** [comment]
<img width="1336" alt="screenshot" src="https://user-images.githubusercontent.com/34688558/77237556-b5a9d600-6b9f-11ea-94f3-66b09eeddd13.png">

**Comment by atscott** [comment]
#36222 also had a minimal repro that's a bit smaller: https://github.com/fxck/angular-animation-cd-bug

**Comment by marcoripa96** [comment]
I have the same issue in angular 9.1.

**Comment by bhanna1693** [comment]
I have the same issue. I think this is an important issue. The [hidden] attribute is a good substitute (sometimes) but if I need to wait for information before rendering the child routes, the ngif is really necessary. A resolver might work as well, but that simply doesn't work for my use case all the time.

**Comment by acohenOT** [comment]
This bug exists in Angular 10, as well.

**Comment by digi-ratio** [comment]
core.js:6185 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.
    at throwErrorIfNoChangesMode (core.js:8092)
    at bindingUpdated (core.js:19773)
    at Module.ɵɵproperty (core.js:20921)
    at LayoutAfterLoginComponent_Template (layout-after-login.component.html:34)
    at executeTemplate (core.js:11949)
    at refreshView (core.js:11796)
    at refreshComponent (core.js:13229)
    at refreshChildComponents (core.js:11527)
    at refreshView (core.js:11848)
    at refreshDynamicEmbeddedViews (core.js:13154)

There is any solution for this bug?

**Comment by hhsissi** [comment]
Hi, did anyone find how to fix this ? Same problem as @acohenOT, error pops up when @routerAnimations directive is in a *ngIf.

**Comment by dmoore1181** [comment]
I am also getting this issue when attempting to use activated route data to trigger route animation. The animation works, just want to get rid of the error message to keep from hampering future debugging when we haven't been working in this project for a while. 

`<div style="overflow: hidden" [@projectAnimation]="projectOutlet && projectOutlet.activatedRouteData && projectOutlet.activatedRouteData['animation']">
      <router-outlet style="overflow: hidden" #projectOutlet="outlet"></router-outlet>
</div>`

**Comment by israeldesouza** [comment]
[I found this](https://angular.io/errors/NG0100)

**Comment by tenglongroy** [comment]
> Hi, did anyone find how to fix this ? Same problem as @acohenOT, error pops up when @routerAnimations directive is in a *ngIf.
> 
> **Edit**
> 
> Ok i found a fix that worked for me, kinda dirty but it works:
> 
> 1- Inject changeRef service
> 
> `constructor(private changeRef: ChangeDetectorRef) { }`
> Implement AfterViewChecked interface
> 
> `ngAfterViewChecked(): void { this.changeRef.detectChanges(); }`

works!

**Comment by irowbin** [comment]
+1 Getting same error.

**Comment by Davste93** [comment]
Same issue Angular 12.0.3

**Comment by aminetchitooss** [comment]
This Fixed the problem for me :



```html
<main [@routeAnimations]="prepareRoute(outlet)">
    <router-outlet class="route" #outlet="outlet"></router-outlet>
</main>
```


```ts
import { RouterOutlet } from '@angular/router';
import { AfterViewInit, ChangeDetectorRef } from '@angular/core';

export class HomeComponent implements AfterViewInit {


  constructor(private changeRef: ChangeDetectorRef) { }

  ngAfterViewInit(): void {
     this.changeRef.detectChanges();
  }

  prepareRoute(outlet: RouterOutlet) {
      return outlet?.activatedRouteData?.animation;
  }
 
}

```

**Comment by dario-piotrowicz** [comment]
For what it's worth I think that this is not at all related animations

I think the issue is related to the `router-outlet`'s `data` value and that just happens to be often used for routing animations but it is not specific to routing animations in the least, it can really just be used for anything

I've created a minimal reproduction which doesn't use animations anywhere (it does not even import the animations module): https://github.com/dario-piotrowicz/angular-expressionchanged-router-bug (the important bit is just in the [`AppComponent`](https://github.com/dario-piotrowicz/angular-expressionchanged-router-bug/blob/master/src/app/app.component.ts))

PS: this still happens in Angular 13 as you can see from the repo

**Comment by atscott** [comment]
This happens because the template attempts to read from the activated route data, which isn't updated until `ngOnInit`. 

Angular does not support reading values from a component which change during change detection _before_ the component executes. 

The reason this works when the outlet element is always present (rather than conditionally) is because the `Router` is able to locate the `RouterOutlet` during navigation, activate it, and then trigger a change detection run so everything is updated correctly. 

We _could_ consider activating the outlet in the `constructor` or at least setting the `_activatedRoute` there since we know the answer to that immediately. I'm hesitant to do this though since it's really just a workaround for a data access pattern that shouldn't exist. 

Instead, the way this should be done is through the public context data. For Dario's example, this would be

```
  constructor(private contexts: ChildrenOutletContexts) {
  }

  getRouteDataText() {
    return this.contexts.getContext('primary')?.route?.snapshot?.data?.['text'];
  }
```

@dario-piotrowicz Would you like to take a look at the documentation and update it to not show this backwards reference data access?

**Comment by dario-piotrowicz** [comment]
> This happens because the template attempts to read from the activated route data, which isn't updated until `ngOnInit`.
> 
> Angular does not support reading values from a component which change during change detection _before_ the component executes.
> 
> The reason this works when the outlet element is always present (rather than conditionally) is because the `Router` is able to locate the `RouterOutlet` during navigation, activate it, and then trigger a change detection run so everything is updated correctly.
> 
> We _could_ consider activating the outlet in the `constructor` or at least setting the `_activatedRoute` there since we know the answer to that immediately. I'm hesitant to do this though since it's really just a workaround for a data access pattern that shouldn't exist.
> 
> Instead, the way this should be done is through the public context data. For Dario's example, this would be
> 
> ```
>   constructor(private contexts: ChildrenOutletContexts) {
>   }
> 
>   getRouteDataText() {
>     return this.contexts.getContext('primary')?.route?.snapshot?.data?.['text'];
>   }
> ```
> 
> @dario-piotrowicz Would you like to take a look at the documentation and update it to not show this backwards reference data access?

@atscott sure! I'd love to! :grin: 

Feel free to assign the issue to me if you want :smiley:

**Comment by dario-piotrowicz** [comment]
Thanks @atscott :smile:
