### ISSUE TITLE
Material component(chip): Select events <mat-chip-list> and <mat-chip> not fired

### ISSUE THREAD

**Issue by RogierdeRuijter** [angular/angular#36174]
# 🐞 bug report

### Affected Package
angular/material

### Is this a regression?
Yes

### Description

When clicking on a material chip component. It seems like the chip and chip list do not fire a change event. 

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-o2npfc?file=src%2Fapp%2Fchips-overview-example.html

In the stackblitz there are methods that catch the events and these methods log something to the console, but this does not happen. 

## 🌍  Your Environment
Angular 9

**Comment by ericmartinezr** [comment]
Please open material related issue in [angular component's](https://github.com/angular/components) repo 👍

**Comment by RogierdeRuijter** [comment]
My bad. Will do!
