### ISSUE TITLE
Error NG6002: Upgraded LIB to NG9

### ISSUE THREAD

**Issue by fkolar** [angular/angular#36185]
# 🐞 bug report

### Affected Package
There is a similar problem https://github.com/angular/angular/issues/35536 and if I follow instructions from this issue it works as a workaround

### Is this a regression?
Yes. NG8 has no problem compiling local libs and local app to test it. 

### Description

As you can see it here at [MetaUI](https://github.com/ngx-meta/rules/tree/ng9), I have `libs` and `apps` folders. 

**Libs** contains two libraries ( that we shoudl care about now):
 - **rules** - core rules engine library
 - **material-rules** - Specific UI library implementation for rules. It also uses and imports core `rules` library

Then I have **apps** as playground: 
 - **material-app**: which imports both libraries. 

The normal workflow in NG8 to be able to test `material-app` was:

```
ng build rules 
ng build material-rules
ng build material-app
ng serve material-app
```

Now `ng build material-app` fails with **NG6002 &  NG6003** errors.

But if I follow #35536, and run ` npx ngcc && ngcc -s dist` before building `material-app`, all works. so Running:

```
rm -Rf dist && ng build rules && ng build material-rules && npx ngcc && ngcc -s dist
ng build material-app
```
fixes problem 

## 🔬 Minimal Reproduction 

```
git clone -b ng9 https://github.com/ngx-meta/rules.git
cd rules/
npm install

// Now you can run to see errors
rm -Rf dist && ng build rules && ng build material-rules && ng build material-app

// run to fix it
rm -Rf dist && ng build rules && ng build material-rules && npx ngcc && ngcc -s dist
ng build material-app

```

## 🔥 Exception or Error
<pre><code>

ERROR in dist/libs/rules/lib/metaui/rules.module.d.ts:27:22 - error NG6002: Appears in the NgModule.imports of MetaUILibLayoutModule, but could not be resolved to an NgModule class.

This likely means that the dependency (@ngx-metaui/rules) which declares MetaUIRulesModule has not been processed correctly by ngcc.

27 export declare class MetaUIRulesModule {
                        ~~~~~~~~~~~~~~~~~
libs/material-rules/src/lib/metaui/meta-ui-layout.module.ts:71:14 - error NG6002: Appears in the NgModule.imports of MaterialRulesModule, but itself has errors

71 export class MetaUILibLayoutModule {
                ~~~~~~~~~~~~~~~~~~~~~
dist/libs/rules/lib/metaui/rules.module.d.ts:27:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the dependency (@ngx-metaui/rules) which declares MetaUIRulesModule has not been processed correctly by ngcc.

27 export declare class MetaUIRulesModule {
                        ~~~~~~~~~~~~~~~~~
libs/material-rules/src/lib/material-rules.module.ts:40:14 - error NG6002: Appears in the NgModule.imports of AppModule, but itself has errors

40 export class MaterialRulesModule {

</code></pre>


## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.6
Node: 12.0.0
OS: darwin x64

Angular: 9.0.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.6
@angular-devkit/build-angular      0.900.6
@angular-devkit/build-ng-packagr   0.900.6
@angular-devkit/build-optimizer    0.900.6
@angular-devkit/build-webpack      0.900.6
@angular-devkit/core               9.0.7
@angular-devkit/schematics         9.0.7
@angular/cdk                       9.1.2
@angular/cli                       9.0.6
@angular/material                  9.1.2
@ngtools/webpack                   9.0.6
@schematics/angular                9.0.6
@schematics/update                 0.900.6
ng-packagr                         9.0.3
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Comment by fkolar** [comment]
@petebacondarwin here is the issue I was reffering in #35536

**Comment by petebacondarwin** [comment]
I'll take a look...

**Comment by vthinkxie** [comment]
Hi @petebacondarwin 
our users meet the same problem, there is a repro link here https://github.com/NG-ZORRO/ng-zorro-antd/issues/4917#issuecomment-602701057

**Comment by petebacondarwin** [comment]
I believe this might have the same cause as https://github.com/angular/angular/issues/36216

**Comment by petebacondarwin** [comment]
@fkolar it is working if I remove the devDependency on `@ngx-metaui/rules` from `package.json`:

```diff
diff --git a/package.json b/package.json
index 14cf78f..454e91c 100644
--- a/package.json
+++ b/package.json
@@ -75,7 +75,6 @@
     "@angular/cli": "9.0.6",
     "@angular/compiler-cli": "^9.0.6",
     "@angular/language-service": "^9.0.6",
-    "@ngx-metaui/rules": "^8.2.0",
     "@nrwl/cypress": "9.1.2",
     "@nrwl/workspace": "^9.1.2",
     "@schematics/angular": "~9.0.1",
```

I believe the reason for this is that when the package exists in both the `dist` folder and the `node_modules` folder, the `material-app` build tries to use the one in `dist` while ngcc has compiled the one in `node_modules`.

**Comment by fkolar** [comment]
hmm. interesting.. Then I need to figure out other way around it ;-(. I have there some logic that I use to run my compiler. 

Since I cannot simply refer to my /src folder I am refering to compiled version of it. and if it is creating this error, then its bad.

Its like working on https://github.com/angular/angular and you wont to run current IVY compiler for your https://github.com/angular/angular/tree/master/modules/playground . How do you guys going around this ?

Thanks, 
FK

**Comment by fkolar** [comment]
@petebacondarwin:   I can confirm it works and it was a cause.

**Comment by petebacondarwin** [comment]
👍 
Glad that got you moving. Please raise new issues if you have further problems.

**Comment by boskiv** [comment]
So guys, I'm not quite sure what I have to do to get it working in my case? :)
https://github.com/NG-ZORRO/ng-zorro-antd/issues/4917
Can you advise?

**Comment by petebacondarwin** [comment]
I think it might have been solved by https://github.com/angular/angular/pull/36249 @boskiv - this landed in 9.1.0. Can you try that version?

**Comment by boskiv** [comment]
I'm already there, here is a repo : https://github.com/boskiv/nx-zorro

**Comment by petebacondarwin** [comment]
Thanks I'll take a look...

**Comment by petebacondarwin** [comment]
So what I am seeing is that on the pre-build async ngcc run the processing of ` ng-zorro-antd/empty` is failing because ngcc is not picking up that it has numerous dependencies, which need to be processed first.

But then these dependencies are being built later during the sync ngcc mode when the actual webpack build comes across their imports.

We need to work out why the async build is failing to find and process the imports...

**Comment by petebacondarwin** [comment]
I thought that https://github.com/angular/angular/pull/36305 might solve this but still seeing problems...

**Comment by petebacondarwin** [comment]
I can confirm that locally #36305 also fixes your problem @boskiv .
