### ISSUE TITLE
Navigating to lazy loaded module from route guard causes the URL path to briefly be blank

### ISSUE THREAD

**Issue by chris13524** [angular/angular#36187]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?
Not sure

### Description
If you have a page that is protected by a route guard which triggers a redirect (thus cancelling the current navigation) to a page which is lazy-loaded, the URL will briefly read just the host name (`/`) while the module loads. (An example of this would be having a dashboard that's protected by a user login guard that redirects to the login page (which in my case is lazy-loaded).)

This is further an issue because it changes the history so that if the user hits the back button, they will be taken to `/` rather than the page they originally tried to navigate to.

Also, if there is a network issue retrieving the module, the user will be abandoned on the home page. If they refresh to try to fix the issue, they will no longer be where they started.

## 🔬 Minimal Reproduction
[angular-lazy-load-guard-test.zip](https://github.com/angular/angular/files/4363701/angular-lazy-load-guard-test.zip)

Navigate to `/page1` and you should get redirected to `/page2`. However, notice that the URL briefly reads `/`. If this is not apparent, try adding network throttling (a Firefox feature) to slow down the retrieval of the lazy module.

I also have a second redirect that emulates the behavior of the guard in the Page1Component. If you disable the card, the page1 component will still redirect. *However*, note that the URL never reads blank at this point...it always shows something. 

## 🔥 Exception or Error
N/A

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.7
Node: 12.3.1
OS: linux x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Comment by Applicafroguy** [comment]
I have a similar issue with the router, all lazy-loaded routes cause an endless loop, my issue has nothing to do with guards, I even turned them off, the problem still persists

**Comment by atscott** [comment]
Hi @chris13524, can you try to update your guard to return a `UrlTree` instead of combining `false` and `navigate`? In general, if you want your guard to redirect, that's the way I would recommend doing it (the feature was added in v8 I believe).

**Comment by chris13524** [comment]
@atscott Yes, that seems to avoid this issue.

**Comment by atscott** [comment]
Great, glad to hear that worked for you! I'm going to close this issue as it seems to be resolved.

**Comment by chris13524** [comment]
If this is going to be closed, then the example in the documentation should also be updated: https://angular.io/guide/router#canactivate-requiring-authentication

**Comment by atscott** [comment]
Ah, good catch and agreed. Reopening and adding the docs label to this report.

**Comment by atscott** [comment]
Guide can't be updated at this time because the last step adds `CanLoad` which doesn't support returning `UrlTree` for a redirect. Blocking issue: https://github.com/angular/angular/issues/28306
