### ISSUE TITLE
Add runtime instrumentation that reports unused reflection data

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#3618]
We won't have perfectly tree-shakeable DI syntax and/or transformer for some time. In the mean time it would be useful for developers to know what reflection data is retained by the transformer that never gets used in an application.

## Proposal

Add a flag to `Reflector` that causes it to track keys used to access `ReflectionInfo` objects in the `_injectableInfo` map. Add a new method `listUnusedReflectionData` that returns `List<ReflectionInfo>` objects that were never requested. Developers could flag these objects for further dead code audit.

**Comment by TedSander** [comment]
SGTM that should help a lot.
