### ISSUE TITLE
help me understand and fix 'ERROR in Cannot read property 'map' of undefined' and doesnt say where & in which file 

### ISSUE THREAD

**Issue by aminemshady2080** [angular/angular#36183]
hey guys please help me understand and fix 'ERROR in Cannot read property 'map' of undefined' error am getting where is run/serve or build my app (ionic4 angular project ) and doesnt say where & in which file the error is occuring. 
this is my environment version after running `ng versrion` command

![v](https://user-images.githubusercontent.com/6911823/77230701-ac6c3980-6b9e-11ea-9395-8e64a601da8c.PNG)

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
