### ISSUE TITLE
新建项目无法启动

### ISSUE THREAD

**Issue by jeemia** [angular/angular#36181]
![image](https://user-images.githubusercontent.com/52172424/77221572-afa6fb80-6b85-11ea-8633-ebcec1ef8bc4.png)
![image](https://user-images.githubusercontent.com/52172424/77221575-b897cd00-6b85-11ea-919c-74674fd2f17b.png)
![image](https://user-images.githubusercontent.com/52172424/77221577-bfbedb00-6b85-11ea-8c34-e7e2dc878fff.png)
>当我永ng new XXX 新建项目后 跟目录下生成很多文件，如上图所示：以前记得没有的  然后ng serve报错；如图：
![image](https://user-images.githubusercontent.com/52172424/77221658-8470dc00-6b86-11ea-8e41-b60104407664.png)
>穷途末路了，希望能指点下
>联系方式：1695603363@qq.com

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
