### ISSUE TITLE
Inconsistent v9.0.7 that caused the warnings to ng2-charts and fsevents

### ISSUE THREAD

**Issue by yr377** [angular/angular#36186]
Angular CLI: 9.0.7
Node: 12.13.1
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@angular/cdk                      9.1.3
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.1.3
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

>>>

npm WARN **ng2-charts@2.3.0** requires a peer of @angular/common@^7.2.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN **ng2-charts@2.3.0** requires a peer of @angular/core@^7.2.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: **fsevents@2.1.2** (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":" peer dependencies yourself.
npm WARN **ng2-charts@2.3.0** requires a peer of @angular/core@^7.2.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: **fsevents@2.1.2** (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for **fsevents@2.1.2**: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: **fsevents@1.2.12** (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for **fsevents@1.2.12**: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: **fsevents@1.2.12** (node_modules\watchpack\node_modules\fsevents):      
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for **fsevents@1.2.12**: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by JoostK** [comment]
I'm not sure what you're trying to report, but this does not look like an Angular issue.

The ng2-charts package does not specify that it supports Angular 9.0 so you get those warnings. Please open an issue with them to see if they can include support for 9.0.
