### ISSUE TITLE
[NGCC] Permit publishing Ivy compiled packages | Micro Frontends

### ISSUE THREAD

**Issue by flash-me** [angular/angular#36195]
# 🚀 feature request

### Relevant Package
 This feature request is for @angular/compiler-cli

### Description

Currently when compiling with Ivy enabled, the resulting libraries contain a `prepublishOnly` lifecycle script to prevent the publication of the package. E.g. <br> 
 ```JSON
"prepublishOnly": "node --eval \"console.error('ERROR: Trying to publish a package that has been compiled by Ivy. This is not allowed.\\nPlease delete and rebuild the package, without compiling with Ivy, before attempting to publish.\\n')\" && exit 1"
```

### Describe the solution you'd like

We are successfully establishing the [Micro Frontend approach with angular](https://github.com/flash-me/angular-micro-frontends) at our client side for every new project (company > 8000 employees). Angular 9.0.6 included already fixes ([details](https://github.com/angular/angular/issues/35429#issuecomment-600202556)) so I could remove the needed workarounds to implement Micro Frontends with pure angular toolchain.

The customer I'm working for provides an Artifactory with a custom NPM registry, where all the Micro Frontend Packages are hosted. **We are already working with Ivy compiled "libraries"**. 

It would be nice to have a flag with which we could disable the inclution of that `prepublishOnly` script. Something like 
```JSON
"angularCompilerOptions": {
  "permitPublication": "true"
}
```
or at the `ngcc` level by a flag like `--permitPublishing` 

### Describe alternatives you've considered

To enable the automatic (CI/CD) publication of those packages (to the internal artifactory), I worked this around by including following line in the Pipeline to remove the `prepublishOnly` script from the `package.json`:
```bash
sed -i '/prepublishOnly/d' package.json
```

No rocket science... but still a workaround. Anyway it would be nice to know, when you consider Ivy Libraries to be "stable" for publication.

cheers
flash :zap:

**Comment by JoostK** [comment]
This is not related to ngcc ;) Publishing libraries is more CLI related, or better yet ng-packagr related (the tool used behind the scenes).

The same request was made in ng-packagr/ng-packagr#1467.

Although I can see this being desirable for some projects, it's really not supported from Angular's perspective as the compilation output is not considered stable, not even across patch releases. Therefore, it seems silly to introduce an option that allows to shoot yourself in the foot so easily. If you deem this risk acceptable for your situation, the `sed` workaround seems like an appropriate "hack" to achieve this goal.

**Comment by flash-me** [comment]
Hi @JoostK ,

thanks for your reply. It's kinda interesting how the ivy compilation is currently seen. 

If we encounter any problems in the feature, we still have to option to disable it. But so far, everything looks fine, since the Micro Frontends approach allows us to massively reduce complexity by splitting up domains and concerns the "hard way" (i.e. the teams don't even have to possibility to produce dependencies to other packages, since the codebase is other repo's, which is a really cool way to enforce clean architectures imo :smile: )

Anyway. I got my answer + that small `sed` commad won't hurt anyone. 

--> can be closed

cheers and stay healthy!
flash :zap:
