### ISSUE TITLE
not able to create new project in angular8

### ISSUE THREAD

**Issue by mohdmazharkhan** [angular/angular#36196]
i am getting error, The system cannot find the path specified. when adding test new project into node.js command prompt getting error. I am totally confused to create new project and not able to create new project in angular8 in window 8.1 pro version : please check my details query: https://stackoverflow.com/questions/59705456/not-able-to-create-new-project-in-angular8

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
