### ISSUE TITLE
Forms: Assigning ng-control to variable results in null

### ISSUE THREAD

**Issue by jessegood** [angular/angular#3619]
Full example:
```
@Component({
  selector: 'demo-form'
})
@View({
  template: `
    <div>
      <h2>My Form</h2>
      <form>
          <input type="text"
                 ng-control="mycontrol"
                 #i="form">
        <div>{{i.valid}}</div>
      </form>
    </div>
  `,
  directives: [formDirectives]
})
export class DemoForm {
}

bootstrap(DemoForm);
```

The above results in:
>EXCEPTION: TypeError: this.control is null in [{{i.valid}} in null]

Now, changing the code to use `FormBuilder` shown below results in no errors and works as expected (omitting some code for brevity):

```
@Component({
  selector: 'demo-form',
  viewBindings: [FormBuilder]
})
@View({
  template: `
    <div>
      <h2>My Form</h2>
      <form [ng-form-model]="form">
          <input type="text"
                 [ng-form-control]="form.controls['mycontrol']"
                 #i="form">
        <div *ng-if="i.valid">{{i.valid}}</div>
      </form>
    </div>
  `,
  directives: [formDirectives, NgIf]
})
export class DemoForm {
  form: ControlGroup;
  constructor(fb: FormBuilder) {
    this.form = fb.group({"mycontrol": []});
  }
}
```

However, the odd part about the above, is if `*ng-if="i.valid"` is removed from the code you get the exact same error message:
>EXCEPTION: TypeError: this.control is null in [{{i.valid}} in null]

In short, the behavior seems to not be consistent.

**Comment by kara** [comment]
Thanks for reporting!  This issue looks a bit stale, since it hasn't had activity in almost a year.  The code has changed a lot since then.  If you're still seeing this in rc.1, please open a new issue with a plunker to demonstrate.
