### ISSUE TITLE
[language service] support type guard in template

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular#36192]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler, @angular/language-service

### Is this a regression?

 No
### Description

Please support type guard in Template, like jsx in react.

## 🔬 Minimal Reproduction

```ts
@Component({
  selector: 'my-app',
  template: `
    <ng-container *ngIf="value.hasDisplayName; else elseTemplate">
      {{ value.displayName }}
    </ng-container>
    <ng-template #elseTemplate>
      {{ value.name }}
    </ng-template>
  `,
  // Identifier 'displayName' is not defined. '{ readonly hasDisplayName: true; readonly displayName: string; } | { readonly hasDisplayName: false; readonly name: string; }' does not contain such a member
  // Identifier 'name' is not defined. '{ readonly hasDisplayName: true; readonly displayName: string; } | { readonly hasDisplayName: false; readonly name: string; }' does not contain such a member
})
export class AppComponent {
  readonly value:
    | { readonly hasDisplayName: true; readonly displayName: string }
    | { readonly hasDisplayName: false; readonly name: string } = {
    hasDisplayName: true,
    displayName: 'Foo',
  };
}
```

---

We always use discriminated union for define our data models.

There is the list of type guard we used frequently:

* instanceof type guards
* typeof type guards
* user-defined type guards
* key in type guard ( `'somekey' in someobject ? someobject.somekey : someobject.other`)

These features are very important for us to convert the data model defined in *the nodejs server code and existing react code* to Angular code.

**Comment by JoostK** [comment]
Hi @xiaoxiangmoe,

could you share your configuration regarding `fullTemplateTypeCheck`/`strictTemplates` and other strictness flags?

The limitation of the else-template is currently tracked in #21504.

**Comment by xiaoxiangmoe** [comment]
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "strict": true,
    "target": "es2015",
    "typeRoots": ["node_modules/@types"],
    "lib": ["esnext", "dom"]
  },
  "angularCompilerOptions": {
    "disableTypeScriptVersionCheck": true,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "strictTemplates": true
  }
}
```

**Comment by JoostK** [comment]
Thanks. I see that the first error is only produced by the language service, not the compiler itself. This limitation of the language service is tracked in #27891. As mentioned before, the second error is tracked in #21504.

<sub>It looks like I missed the "[language service]" annotation in the title before.</sub>
