### ISSUE TITLE
$httpProvider Cache Busting sends malformed requests to IIS when using $http.get with integrated authentication

### ISSUE THREAD

**Issue by fir3pho3nixx** [angular/angular#362]
Used this in the app.config block for doing cache busting in Internet Explorer

if (!$httpProvider.defaults.headers.get) {
            $httpProvider.defaults.headers.get = {};
        }
$httpProvider.defaults.headers.get['If-Modified-Since'] = '0';

However when I do $http.get I get the following back IIS. 

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
<title>IIS 7.5 Detailed Error - 400.0 - Bad Request</title> 
<style type="text/css"> 
 
</style> 
 
</head> 
<body> 
<div id="header"><h1>Server Error in Application "MyWeb"</h1></div> 
<div id="server_version"><p>Internet Information Services 7.5</p></div> 
<div id="content"> 
<div class="content-container"> 
 <fieldset><legend>Error Summary</legend> 
  <h2>HTTP Error 400.0 - Bad Request</h2> 
  <h3>Bad Request</h3> 
 </fieldset> 
</div> 
<div class="content-container"> 
 <fieldset><legend>Detailed Error Information</legend> 
  <div id="details-left"> 
   <table border="0" cellpadding="0" cellspacing="0"> 
    <tr class="alt"><th>Module</th><td>StaticFileModule</td></tr> 
    <tr><th>Notification</th><td>ExecuteRequestHandler</td></tr> 
    <tr class="alt"><th>Handler</th><td>StaticFile</td></tr> 
    <tr><th>Error Code</th><td>0x80070057</td></tr> 
     
   </table> 
  </div> 
  <div id="details-right"> 
   <table border="0" cellpadding="0" cellspacing="0"> 
    <tr class="alt"><th>Requested URL</th><td>http://localhost:8090/style/cache/http___localhost_8097__styles.axd.css</td></tr> 
    <tr><th>Physical Path</th><td>C:\SVN\Framework-Web\webapplication\style\cache\http___localhost_8097__styles.axd.css</td></tr> 
    <tr class="alt"><th>Logon Method</th><td>Negotiate</td></tr> 
    <tr><th>Logon User</th><td>ACUL\GMerwe</td></tr> 
     
   </table> 
   <div class="clear"></div> 
  </div> 
 </fieldset> 
</div> 
<div class="content-container"> 
 <fieldset><legend>Most likely causes:</legend> 
  <ul> 	<li></li> </ul> 
 </fieldset> 
</div> 
<div class="content-container"> 
 <fieldset><legend>Things you can try:</legend> 
  <ul> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul> 
 </fieldset> 
</div> 
 
 
<div class="content-container"> 
 <fieldset><legend>Links and More Information</legend> 
  The request could not be understood by the server due to malformed syntax. 
  <p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=400,0,0x80070057,7601">View more information &raquo;</a></p> 
  <p>Microsoft Knowledge Base Articles:</p> 
 <ul><li></li></ul> 
 
 </fieldset> 
</div> 
</div> 
</body> 
</html> 

When I remove it then everything works. Strange. 

I am using angularjs v1.2.21

**Comment by pkozlowski-opensource** [comment]
I don't think it has anything with AngularJS - it just sends what you tell it to send. But quick googling reveals that you are not the only one having this problem, ex.: http://stackoverflow.com/questions/2517242/xmlhttprequest-with-if-modified-since-webserver-returns-400-bad-request

Anyway, this is a support question that should be asked [elsewhere](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). If you still believe that there is a bug in AngularJS, please narrow down and clearly describe difference between the current and expected behavior. Thnx!

**Comment by pkozlowski-opensource** [comment]
This is wrong repo BTW, I guess you wanted to interact with this one: https://github.com/angular/angular.js

**Comment by fir3pho3nixx** [comment]
Thanks! :)
