### ISSUE TITLE
Docs: typo in the testing section, components with async service

### ISSUE THREAD

**Issue by Fouzyyyy** [angular/angular#36210]
# 📚 Docs or angular.io bug report

### Description

There is a typo in the next sentence:

And in some case, we don't want to trigger the new **maco** task

We mean, _macro_, don't we?

### What's the affected URL?**
https://angular.io/guide/testing#component-with-a-dependency

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by Fouzyyyy** [comment]
Able to quickly submit a PR for this.

**Comment by sonukapoor** [comment]
@Fouzyyyy Go for it.

**Comment by gkalpak** [comment]
Thx, @Fouzyyyy!

FYI, you don't need to create issues for fixing small typos in the docs. You can submit a pull request directly.

**Comment by Fouzyyyy** [comment]
Okidoki @gkalpak will do
