### ISSUE TITLE
Validators.minLength() not working with patchValue()

### ISSUE THREAD

**Issue by arif3258** [angular/angular#36217]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Description

 Validators.minLength(X) returns **status: false** after providing a valid value of **X** length using `patchValue()` method 

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-8-reactive-form-qr7bha

## 🔥 Observation
<pre><code>
Please observe the snippet below -
</code></pre>
![image](https://user-images.githubusercontent.com/23406656/77407576-8f26ad80-6de0-11ea-824e-b5922da474cd.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/forms": "^8.0.0",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/router": "^8.0.0",
    "core-js": "2",
    "rxjs": "^6.5.2",
    "zone.js": "^0.9.1"
</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
Something for you to look into @sonukapoor ?

**Comment by sonukapoor** [comment]
@petebacondarwin Please assign to me. I will take a look.

**Comment by arif3258** [comment]
@petebacondarwin 

Its seems like I have made a typo, making every value into an array. And when the value gets changed (when it is changed from the input field) the formControl then gets the value of the correct type and works as expected. This behavior confused me as it seemed to work after the data has been altered from the DOM. Sorry for the troubles
