### ISSUE TITLE
Dart: IE does not support <template> tag

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#3622]
We need to polyfill/workaround it. Specifically, the element becomes HTMLUnknownElement which does not provide the `content` getter.

This was fixed in `browser_adapter.ts` for the JS version. We need a similar fix in `browser_adapter.dart`. To avoid going through JS-interop on every call, we'll cache the value of `_supportsTemplateElement`:

```dart
// browser_adapter.dart

bool _templateElementCheckPerformed = false;
bool _supportsTemplateElement = true;

void _maybeCheckTemplateElementSupport() {
  if (_templateElementCheckPerformed) return;

  try {
    // IE throws, others may simply return null
    _supportsTemplateElement = new TemplateElement().content != null;
  } catch(e) {
    _supportsTemplateElement = false;
  }
}
```

Update `content` getter:

```dart
// BEFORE:
  Node content(TemplateElement el) => el.content;

// AFTER:
  Node content(TemplateElement el) {
    _maybeCheckTemplateElementSupport();
    if (_supportsTemplateElement) {
      return el.content;
    } else {
      // the compiler extracts children anyway
      return el;
    }
  }
```

**Comment by floitschG** [comment]
You can just use a final variable:
bool _supportsTemplateElement = () {
  try { new TemplateElement().content != null; return true; } catch { return false; }
}();

The Node content will probably not be allowed to take a TemplateElement as argument, since it can be a HTMLUnknownElement on IE.

**Comment by mhevery** [comment]
Fixed by: https://github.com/angular/angular/commit/ddcfd465ad74731cbc03109f86299ed386ac72e0
