### ISSUE TITLE
sudo npm start error : angular 5 project

### ISSUE THREAD

**Issue by arunranaoodles1** [angular/angular#36228]
ERROR in node_modules/@angular/cdk/a11y/typings/a11y-module.d.ts(7,25): error TS2694: Namespace '"projects_path/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDefWithMeta'.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
