### ISSUE TITLE
cannot instantiate cyclic dependency - App Initializer :: not working when build & deployed through jenkins

### ISSUE THREAD

**Issue by nutangwari** [angular/angular#36221]
rest Connector --> HttpClient** 

now when data is received initializer service calls navigation service to route to new page
**initialzer service  --> NavigationService --> Router**

now when i am running locally everything works fine. But when code is build in jenkins and deployed in QA environment i am getting cyclic dependency error. 

I tried prod build and from dist folder tried to run the application using lite-server npm plugin everything works fine, without any error or warning

I understand the issue after going through already raised issues, but i don't understand why it's working locally but not when done by build server in Jenkins.

doest angular builds application differently in jenkin (unix based) compared to local system (windows) ?? 

## 🔬 Minimal Reproduction
i would have shared a stackblitz repro or minimal code but as i mentioned in local am not sure if that will be helpful. although if required i can share the build log files.
 https://stackblitz.com/...

<!--

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
