### ISSUE TITLE
Deependancy Injection it is possible to inject ViewRef and EmbeddedViewRef

### ISSUE THREAD

**Issue by SebastianPodgajny** [angular/angular#36235]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/9.0.7

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9.0.7 Ivy disabled

### Description

 In Ivy you can inject ViewRef and EmbeddedViewRef in component/directive constructor, this was not possible in VE. I don't know if you consider this bug or I can rely on this behaviour?

## 🔬 Minimal Reproduction

```
@Component({
  selector: 'app-viewref',
  template: `viewref works!`
})
export class TestComponent {
  constructor(
    cdRef: ChangeDetectorRef,
    viewRef: ViewRef,
    embeddedViewRef: EmbeddedViewRef<any>
  ) {
    console.log({cdRef, viewRef, embeddedViewRef});
  }
}
```
![image](https://user-images.githubusercontent.com/21180501/77478855-f7947f80-6e1e-11ea-8a36-f4a9901247f3.png)

If we can inject `EmbeddedViewRef` then this issue https://github.com/angular/angular/issues/8277 should by resolved by `embeddedViewRef.context`

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.5
Node: 12.10.0
OS: darwin x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.5
@angular-devkit/build-angular      0.900.5
@angular-devkit/build-ng-packagr   0.900.5
@angular-devkit/build-optimizer    0.900.5
@angular-devkit/build-webpack      0.900.5
@angular-devkit/core               9.0.5
@angular-devkit/schematics         9.0.5
@angular/cdk                       9.0.0
@ngtools/webpack                   9.0.5
@schematics/angular                9.0.5
@schematics/update                 0.900.5
ng-packagr                         9.0.3
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment]
Uh, I don't think it was intentional :-) 

> can rely on this behaviour?

Hmmm, I would say hold on for a sec...

**Comment by kara** [comment]
@SebastianPodgajny @pkozlowski-opensource Yeah, this isn't intentional and it's a bug that we're allowing this to work. We should close the loophole and throw to prevent people from relying on it when it's incidentally working.
