### ISSUE TITLE
dgeni should insert a space when doc breaks over two comment lines

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#3623]
Observe this comment in the code
https://github.com/angular/angular/blob/2.0.0-alpha.34/modules/angular2/annotations.ts#L1-L48
<img width="699" alt="screen shot 2015-08-13 at 11 15 37 am" src="https://cloud.githubusercontent.com/assets/2286589/9257836/c6733322-41ac-11e5-9792-93d8452e8dc6.png">

which produces this doc, which is missing some spaces where linebreaks occur in the original.
<img width="1054" alt="screen shot 2015-08-13 at 11 16 07 am" src="https://cloud.githubusercontent.com/assets/2286589/9257842/d550d142-41ac-11e5-95fb-124c0eb938bc.png">

**Comment by petebacondarwin** [comment]
I have a fix here #3997
