### ISSUE TITLE
ng-template not working in angular 9 with IVY

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular#36238]
# 🐞 bug report

ng-template is not working properly in angular 9 but working fine in angular 8

### Is this a regression?

**yes, working fine in angular 8**

### Description

I have created same application in both angular 8 and angular 9, my application working fine in angular 8.

### Working sample
1. download below angular 8 sample
[angular8.zip](https://github.com/angular/angular/files/4379217/angular8.zip)

2. Give "npm i" and "ng serve"

3.then chose any one row from grid and click "edit" button, you wiill see below 

![image](https://user-images.githubusercontent.com/36756050/77505537-7920f780-6e89-11ea-8ed5-6f2b63f4103d.png)

my template working fine.

### issue sample
1. download below angular 9 sample

[angular 9.zip](https://github.com/angular/angular/files/4379205/angular.9.zip)

2. Give "npm i" and "ng serve"

3.then below screen occurs , then chose any one row from grid and click "edit" button, you wiill see below 

![image](https://user-images.githubusercontent.com/36756050/77505439-25aea980-6e89-11ea-8508-81b65959980d.png)

### Code snippet

```
<ejs-grid [dataSource]='data' allowPaging='true' [pageSettings]='pageSettings' [editSettings]='editSettings' [toolbar]='toolbar' (actionBegin)='actionBegin($event)' (actionComplete)='actionComplete($event)'>
      <e-columns>
          <e-column field='OrderID' headerText='Order ID' width='120' textAlign='Right' [isPrimaryKey]='true'></e-column>
          <e-column field='CustomerName' headerText='Customer Name' width='120'></e-column>
          <e-column field='Freight' headerText='Freight' width='120' format='C2' textAlign='Right'></e-column>
          <e-column field='OrderDate' headerText='Order Date' width='130' format='yMd' textAlign='Right'></e-column>
          <e-column field='ShipCountry' headerText='Ship Country' width='150'></e-column>
      </e-columns>
      <ng-template #editSettingsTemplate let-data>
          <div ngForm #orderForm="ngForm">
              <table class="e-table e-inline-edit" cellspacing="0.25">
                  <colgroup>`
                          <col style="width: 120px;">
                          <col style="width: 120px;">
                          <col style="width: 120px;">
                          <col style="width: 130px;">
                          <col style="width: 150px;">
                  </colgroup>
                  <tbody>
                      <tr>
                          <td style="text-align: right" class='e-rowcell'>
                              <div class="e-input-group" [ngClass]= "{'e-disabled': !data.isAdd}">
                                  <input class="e-input e-field" [(ngModel)]="orderData.OrderID" required [attr.disabled]="!data.isAdd ? '' : null" name='OrderID' type="text" (focus)="focusIn($event.target)"
                                      (blur)="focusOut($event.target)" #OrderID style="text-align: right"  />
                              </div>
                          </td>
                          <td class='e-rowcell'>
                              <div class="e-input-group">
                                  <input class="e-input e-field" name='CustomerName' [(ngModel)]="orderData.CustomerName" required type="text" (focus)="focusIn($event.target)"
                                      (blur)="focusOut($event.target)" #CustomerName />
                              </div>
                          </td>
                          <td style="text-align: right" class='e-rowcell'>
                              <ejs-numerictextbox name="Freight" id="Freight" [(ngModel)]="orderData.Freight" floatLabelType='Never'></ejs-numerictextbox>
                          </td>
                          <td style="text-align: right" class='e-rowcell'>
                              <ejs-datepicker id="OrderDate" name="OrderDate" required [(ngModel)]="orderData.OrderDate" floatLabelType='Never'></ejs-datepicker>                            
                          </td>
                          <td class='e-rowcell'>
                              <ejs-dropdownlist id="ShipCountry" name="ShipCountry" [(ngModel)]="orderData.ShipCountry" [dataSource]='shipCountryDistinctData' [fields]="{text: 'ShipCountry', value: 'ShipCountry' }" popupHeight='300px' floatLabelType='Never'></ejs-dropdownlist>
                          </td>
                      </tr>
                  </tbody>
              </table>
          </div>
      </ng-template>
  </ejs-grid>
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
"@angular/animations": "~9.0.2",
    "@angular/common": "~9.0.2",
    "@angular/compiler": "~9.0.2",
    "@angular/core": "~9.0.2",
    "@angular/forms": "~9.0.2",
    "@angular/platform-browser": "~9.0.2",
    "@angular/platform-browser-dynamic": "~9.0.2",
    "@angular/router": "~9.0.2",
"@angular-devkit/build-angular": "~0.900.3",
    "@angular/cli": "~9.0.3",
    "@angular/compiler-cli": "~9.0.2",
    "@angular/language-service": "~9.0.2",

</code></pre>

**Anything else relevant?**
Both angular 8 and angular 9, my template reference are same in my soure level"ngAfterContnctChecked" hook.

### angular 8 reference:

![image](https://user-images.githubusercontent.com/36756050/77506024-c18ce500-6e8a-11ea-8785-22446d8b1d8a.png)

### angular 9 reference:
![image](https://user-images.githubusercontent.com/36756050/77506130-0a449e00-6e8b-11ea-8183-c4a8c4732e34.png)

**Comment by JoostK** [comment]
In the Angular 8 screenshot, the `ngAfterContentChecked` is called with a `ComponentBase` instance as first parameter. This is not part of the signature of this method according to the `AfterContentChecked` interface, and it's not provided as such by Angular itself. I suspect that your decorators inject custom behaviour into how hooks are called, which had to be reworked because of #31495 which has broken this setup. The stack trace is missing in the Angular 8 screenshot so I can't know for sure, but there's likely an additional stack frame in the Angular 8 case.

**Comment by kumaresan-subramani** [comment]
HI @JoostK ,

We have used custom decarators to over-ride my angular componet hooks, it works tll anglar 9.

but in anglar 9 with IVY, it does not work due to this [issue](https://github.com/angular/angular/issues/31495) so that we have created new instance of my class which has all life cycle hook functionalities like below:

https://github.com/syncfusion/ej2-angular-ui-components/blob/master/components/grids/src/grid/grid.component.ts#L233

ans then i have passed current instace to newly created class instance which has all lie cycle hook functionalities like below

https://github.com/syncfusion/ej2-angular-ui-components/blob/master/components/grids/src/grid/grid.component.ts#L237

**Comment by kumaresan-subramani** [comment]
My issue is ng-template compilation not working fine in angular 9 but template reference are same i both angular 8 and 9

**Comment by kumaresan-subramani** [comment]
working fine in angular 8

not working in angular 9

**Comment by kumaresan-subramani** [comment]
Finally i have validated and partially assumed issue is in **node_modules\@angular\core\__ivy_ngcc__\fesm2015\core.js** packages

when it comes to **tickRootContext** method, it has my template reference

![image](https://user-images.githubusercontent.com/36756050/77530394-43930300-6eb7-11ea-8a8e-58d751a9ac28.png)


and then it goes to **renderComponentOrTemplate** method, in here template function goes null

![image](https://user-images.githubusercontent.com/36756050/77530707-c7e58600-6eb7-11ea-8a7c-52e6a6f5add1.png)

From renderComponentOrTemplate method it goes to **refreshView** method, in here component reference occurs in 19th index as like below image:
![image](https://user-images.githubusercontent.com/36756050/77530920-11ce6c00-6eb8-11ea-9a2f-ce23af0eafe5.png)

then i navigate to 19th component reference in there template not get compiled it shows undefined as like below image
![image](https://user-images.githubusercontent.com/36756050/77531399-d8e2c700-6eb8-11ea-8aa8-3800e06040f0.png)

So that i partially  conclude there is some error in angular 9 ivy template compilation, Can you please provide any update on this.

But for in angular 8, total architecture is different and working fine

**Comment by kumaresan-subramani** [comment]
HI @JoostK ,

I think, i found root cause, which is when i select anyone row and then click edit button, it triggers my component's life cycle hook **[which is placed inside ng-template]** in angular 8 so that component which has been placed inside ng-template grt rendered properly. refer below images:

### row selection
![image](https://user-images.githubusercontent.com/36756050/77615988-a5567a00-6f56-11ea-9754-97d03e8d3bb5.png)

### click edit button
after clicking edit button, it triggers my life cycle hook from **"callProviderLifecycles"** angular method, from my lifecycle hook i called append method and there i append my component which has been placed inside ng-template has been get rendered properly.

![image](https://user-images.githubusercontent.com/36756050/77616315-58bf6e80-6f57-11ea-92f4-f5143c77d017.png)

### my component inside ng-template rendering
![image](https://user-images.githubusercontent.com/36756050/77616639-22362380-6f58-11ea-95ad-e72472f12859.png)

in angular9, when i click edit button it doesn't trigger my life cycle hooks properly. so that ng-template not working

**Comment by alxhub** [comment]
One of the Ivy compatibility "changes you may see" on https://angular.io/guide/ivy-compatibility is:
> It's no longer possible to overwrite lifecycle hooks with mocks on directive instances for testing (instead, modify the lifecycle hook on the directive type itself).

This is a performance optimization - reading a function from an arbitrary component is expensive, and so Angular only does it once from the component's prototype.

Unfortunately you'll need to rework your decorator logic to not rely on arbitrary overwriting of lifecycle hooks.

**Comment by kumaresan-subramani** [comment]
Hi,

If over-riding angular hook is not possible in ivy,how below works

https://github.com/angular/angular/issues/36238#issuecomment-603702447

I have over-rided angular hooks here also.

**Comment by kumaresan-subramani** [comment]
HI @alxhub ,

I think you misunderstood my problem.

when i click "edit" button,
![image](https://user-images.githubusercontent.com/36756050/77908470-2ab89200-72a9-11ea-9b34-50de3a25d722.png)

it triggers, my life cycle hook from angular core level like below image

![image](https://user-images.githubusercontent.com/36756050/77908937-0a3d0780-72aa-11ea-8dc7-ee0e83c4d46b.png)

**Comment by Achilles1515** [comment]
> It's no longer possible to overwrite lifecycle hooks with mocks on directive instances for testing (instead, modify the lifecycle hook on the directive type itself).

@alxhub But this will be changing "soon"...right?
https://github.com/angular/angular/pull/35464

**Comment by bryanrideshark** [comment]
@alxhub , we're going to be merging #35464 and making it possible to override the prototype _before startup_ right? It'll still be pretty efficient AFAIK, because the read will be cached once the first component of that type has been instantiated.

I think a lot of more advanced users of Angular are waiting with eager expectation for #35464 to be merged.

**Comment by alxhub** [comment]
@bryanrideshark that'd be a better question for @kara, I don't work on the core specifically. But that approach looks sound to me.
