### ISSUE TITLE
LOCALE_ID accessed in tests before APP_INITIALIZER runs (with Ivy)

### ISSUE THREAD

**Issue by IgorAufricht** [angular/angular#36230]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core.

### Is this a regression?

Yes, the previous version in which this bug was not present was: ^8.2.0 (not using Ivy)

This also works if @angular/core is not processed by `ngcc` (when the tests use ViewEngine instead of Ivy) - we use jest, which does not call `ngcc` automatically like the default Angular CLI setup with karma, so we can test both scenarios easily in our private project repository.

### Description
There was a pull request (#34830) that ensured all `APP_INITIALIZER` functions are executed before `LOCALE_ID` is first accessed. This works correctly when the application is served (whether the initializer is synchronous or asynchronous).

But when running tests, this is not happening. The `LOCALE_ID` is accessed before `APP_INITIALIZER` functions are executed, thus ending in the locale being undefined.

## 🔬 Minimal Reproduction
https://github.com/IgorAufricht/angular-locale-id-test-repro

The steps are included in the readme, but for clarity, here they are:
* `git clone https://github.com/IgorAufricht/angular-locale-id-test-repro`
* `npm install`
* `ng serve` (application loads correctly, console confirms that `LOCALE_ID = fr-FR`)
* `ng test` (fails, `Error: Expected '' to equal 'fr-FR'`)

**Angular Version:**
<pre><code>
Angular CLI: 9.0.7
Node: 12.13.1
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
Related to #34830.

**Comment by AndrewKushnir** [comment]
Hi @IgorAufricht, just a quick update. Ivy TestBed change that update the execution order (to align it with the bootstrap code path) was merged and should be available in the next release of Angular Framework (most likely in `9.1.1`). Thank you.
