### ISSUE TITLE
HttpClient/HttpRequest should support fetch API-specific redirect control

### ISSUE THREAD

**Issue by thw0rted** [angular/angular#36246]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/common/http

### Description
#27689 requests a Fetch-based backend for `HttpClient`.  The only response thus far has been "feel free to implement it yourself".  I don't actually care what backend is used.  I'm trying to replace my (fetch-based) back-end interactions with HttpClient so that I can use injected mocks for testing.  The problem is that I currently use several features that are not available in the existing API, like the `cache` and `redirect` options in the [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) and the `redirected` property of [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response/redirected).

### Describe the solution you'd like
I'd like to see first-class Angluar support for `fetch`-specific features.

### Describe alternatives you've considered
I'm talking to back-end APIs that I have no control over.  I'm either going to have to a) stick with `fetch` and figure out how to test my code on my own, or b) switch to HttpClient and rewrite significant portions of my backend interactions to detect and handle redirects that I could have avoided using a simple `{redirect: "error"}` via native `fetch`.

**Comment by thw0rted** [comment]
cc #23033

**Comment by jimmywarting** [comment]
Someone just asked me if they could use streamsaver with angular's HttpClient
my answer where: you can't, they don't seem to give you a readable stream

https://github.com/jimmywarting/StreamSaver.js/issues/155#issuecomment-626470552

using fetch as http backend when possible would be 👍

**Comment by alxhub** [comment]
> I'd like to see first-class Angluar support for `fetch`-specific features.

I would too :)

When it was in development, `HttpClient` was initially based on `fetch`, but ran into some issues around browser support (like IE, as always) and around specific features such as cancellation, progress reports, etc.

I think it's a good time for us to re-evaluate what a `fetch`-based `HttpBackend` might look like. There are still some challenges here (implementing the progress events `HttpClient` exposes on top of `fetch` would be tricky) but I think it might be doable.

**Comment by thw0rted** [comment]
I should have guessed legacy support was the culprit.  Is there an existing ticket for "Drop IE support, raze it to the foundations, and salt the ashes" or should I open a new one?

**Comment by alxhub** [comment]
I'm going to close this as infeasible for now, until #27689 is implemented.

**Comment by thw0rted** [comment]
@alxhub that issue "didn't get enough votes" either.  Would it be safe to assume that Angular HTTP is going to stay XHR-backed for the foreseeable future?
