### ISSUE TITLE
Get component class from selector

### ISSUE THREAD

**Issue by nitzanb-medopad** [angular/angular#36240]
In angular 9 creating components dynamically doesn't work anymore. what alternatives I have because now I can't iterate componentFactoryResolver._factories as it doesn't exist anymore?

https://stackoverflow.com/questions/60691633/angular-9-ivy-get-component-class-from-selector

**Comment by JoostK** [comment]
This sounds like a support request for which the StackOverflow question you asked seem the most appropriate place.

**Comment by pkozlowski-opensource** [comment]
Plus we tracked the actual use-case in #33715. So this is duplicate of #33715 need-wise.
