### ISSUE TITLE
How to set tab index for the child component 

### ISSUE THREAD

**Issue by prasanthnsn11** [angular/angular#36244]
Hi I just have a doubt how to set Tab Index for the child component where we have a form while moving to next form at first tab it exceeds to the last button before moving to the form . kindly suggest me any idea that works out .

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
