### ISSUE TITLE
Angular Dynamic Form

### ISSUE THREAD

**Issue by keshani** [angular/angular#36245]
Hi 
I am developing angular dynamic form as describe [here](https://angular.io/guide/dynamic-form) .
My form template fields are created in vertical direction one after other.
I want show  fields in row where each row may have four  to  five fields . I am using boostrap and tried applying css alss "row". It didnt work. below I mentioned my code

Dynamic Form
 <form form name="dynamicform" role="form" (ngSubmit)="saveRecord()" [formGroup]="dynamicform">
              <dl class="row-md  overflow-y">
                    <div *ngFor="let question of questions ">
                    <div [ngClass]="getCSSClass(question.controlType)">  
                            <div class="form-group">
                        <app-question [question]="question" [form]="dynamicform"></app-question>
                       </div>
                    </div>
                    </div>
                    </div>
            </dl>
</form>

Question Components
<div [formGroup]="form" >
  <div [ngSwitch]="question.controlType">

    <div *ngSwitchCase="'textbox'">
      <div *ngIf="question.isVisible">
          <label class="form-control-label"></label>
          <input class="form-control" *ngSwitchCase="'textbox'" [formControlName]="question.key" [id]="question.key" [type]="question.type">
          <div *ngIf="form.get(question.key)!.invalid && (form.get(question.key)!.dirty || form.get(question.key)!.touched)">
              <small class="form-text text-danger" *ngIf="form.get(question.key)?.errors?.required">
                  This field is required.
              </small>
              <small class="form-text text-danger"  *ngIf="form.get(question.key)?.errors?.maxlength">
                  This field cannot be longer than 500 characters.
              </small>
          </div>
      </div>
   </div>

    <div  *ngSwitchCase="'dropdown'" >
        <div *ngIf="question.isVisible">
              <label class="form-control-label" >{{question.label}}</label>
              <select class="form-control" [id]="question.key" [formControlName]="question.key">
                 <option [value]="null"></option>
                <option *ngFor="let opt of question.options" [value]="opt[question.optionValue]">{{opt[question.optionDisplayVal]}}</option>
              </select>

              <div *ngIf="form.get(question.key)!.invalid && (form.get(question.key)!.dirty || form.get(question.key)!.touched)">
              <small class="form-text text-danger" *ngIf="form.get(question.key)?.errors?.required">
                  This field is required.
              </small>
              </div>
        </div>
    </div>

     <div *ngSwitchCase="'textarea'" >
      <div *ngIf="question.isVisible">
        <label class="form-control-label" >{{question.label}}</label>
          <div class="d-flex">
            <textarea rows="4" [id]="question.key"  class="form-control" [formControlName]="question.key" >
               </textarea>
          </div>
          <div *ngIf="form.get(question.key)!.invalid && (form.get(question.key)!.dirty || form.get(question.key)!.touched)">
               <small class="form-text text-danger" *ngIf="form.get(question.key)?.errors?.required">
                  This field is required.
              </small>
              <small class="form-text text-danger"  *ngIf="form.get(question.key)?.errors?.maxlength">
                  This field cannot be longer than 500 characters.
              </small>
          </div>
        </div>
    </div>
</div>

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
