### ISSUE TITLE
Google Cloud Angular App Hosting 401 Error on Hosting

### ISSUE THREAD

**Issue by rakshitbharat** [angular/angular#36257]
I'm trying to deploy an angular app to a Google Cloud Storage bucket so that I can serve the app from there. The bucket has has public access and is named so that I can serve it as a custom website via CNAME (let's say test.example.com). The bucket is also configured to map the main page to index.html and the 404 handler to index.html. When loading https://test.example.com, most of the app loads fine, but any of the assets that are loaded via XHR (GET from /assets/) get a HTTP 401 error. There are no preflight requests. I've tried setting various permutations of CORS settings on the bucket, but nothing seems to help.

I am getting this on loading on assets.

`<?xml version='1.0' encoding='UTF-8'?><Error><Code>AuthenticationRequired</Code><Message>Authentication required.</Message></Error>`

Can anyone help me out.

We are using Google storage and Google DNS Hosting for this.

Below link is for reference: https://html.developreference.com/article/10228923/401+error+with+Angular+app+deployed+to+Google+Cloud+Storage+with+CNAME%27d+DNS

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
