### ISSUE TITLE
Angular 9 fails to refer the global type I declared in a custom type definition file

### ISSUE THREAD

**Issue by binDongKim** [angular/angular#36251]
I've tried updating my angular project from Angular 8 to 9.

After the update, I entered `ng serve` to start up my app and it gave me these errors:

```javascript
src/app/core/components/server-map/server-map-container.component.ts:259:59 - error TS2304: Cannot find name 'ICoordinate'.

259     onContextClickLink({key, coord}: {key: string, coord: ICoordinate}): void {
                                                              ~~~~~~~~~~~
src/app/core/components/server-map/server-map-change-notification.service.ts:52:27 - error TS2304: Cannot find name 'ITransactionDetailData'.

52             filter((data: ITransactionDetailData) => {
                             ~~~~~~~~~~~~~~~~~~~~~~
src/app/core/components/server-map/server-map-change-notification.service.ts:55:28 - error TS2304: Cannot find name 'ITransactionDetailData'.

55         ).subscribe((data: ITransactionDetailData) => {
                              ~~~~~~~~~~~~~~~~~~~~~~
src/app/core/components/server-map/server-map-change-notification.service.ts:58:82 - error TS2304: Cannot find name 'INodeInfo'.

```

I suppose it's something to do with my custom definition file which occurs no error back in Angular 8. Anyway, I declared the types which I use across the app in `globals.d.ts.` under the `src` directory and let app the know it by referring it in `tsconfig.app.json` like:

```
"include": [
   "src/**/*.d.ts"
]
```

Again, there was no problem with this approach and I'm just wondering if something has changed internally which I didn't see from their migration guide. Any insight would be appreciated!

**Comment by alxhub** [comment]
Hello @binDongKim,

Can you provide a simple reproduction repository that shows this pattern working in 8 and failing in 9? That would be super helpful in debugging this issue.

**Comment by binDongKim** [comment]
@alxhub 
I assume it has something to do with the statement in the [update guide](https://update.angular.io/#8.2:9.0l3):
`We have updated the tsconfig.app.json to limit the files compiled. If you rely on other files being included in the compilation, such as a typings.d.ts file, you need to manually add it to the compilation.`

**Comment by tsteuwer-accesso** [comment]
@binDongKim, do you know what that means or how to even do that? According to the TS documentation, you can just use the `include` property in the TS config. If you can no longer do that, how are you supposed to "manually add it to the compilation"?

**Comment by binDongKim** [comment]
@tsteuwer-accesso Check out the link I attached above. I extracted it from the angular official update guide.

**Comment by tsteuwer** [comment]
@binDongKim, I did and it doesn't explain how to do that. Everytime I run the app it says to add it to the `'files'` or `'include`' sections, but it's already there. If we can't use that, we need to know what they mean by manually adding it to the include section lol.

**Comment by binDongKim** [comment]
@tsteuwer Exactly. I noticed the update had taken care of it and added `include` section to the `tsconfig.app.json` so I thought everything was okay but it turns out it's not.

**Comment by alxhub** [comment]
@binDongKim I'm sorry you're still having trouble with this, but unfortunately without a reproduction we won't be able to investigate this issue, so I'm going to close it for now. Feel free to open another one with a reproduction if you're still running into this problem.
