### ISSUE TITLE
Allow setting trusted domains that can receive the XSRF token

### ISSUE THREAD

**Issue by aarukarthiga** [angular/angular#36254]
In my application, I'm trying to add csrf token to my laravel API.  AS per the documentation I added the below code 

`HttpClientXsrfModule.withOptions({
      cookieName: 'XSRF-TOKEN',
      headerName: 'X-CSRF-TOKEN'
    }),`

It doesn't add the token to the post-login request. And laravel expecting token for login 

Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 192.168.10.10:80
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: *
Access-Control-Allow-Origin: *
Cache-Control: no-cache, private
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
Date: Thu, 26 Mar 2020 07:57:23 GMT
Server: nginx/1.15.8
Set-Cookie: laravel_session=eyJpdiI6Ikg3VUlidm5MVG92UVdrc1RjU1U1UEE9PSIsInZhbHVlIjoiZCtFcTU1bmsxZm1jUkdhZU8wV1o5Z0FnNmpUZUNQekI4V1h6QUJnaUxyU1FEeUZEUU1MQ2V1SVQ0andHclhrRXRuRmVSbVdRUldiU0NyZkJWYm1COHc9PSIsIm1hYyI6IjM3ODFhYTU3MjY3ZDY1YjIwM2ExOGI2YjMzNWNmNzhhZjA0NWNjYTBlYmVmMGRjNzJlNmU4N2E5NjcwZDgzYmQifQ%3D%3D; expires=Thu, 26-Mar-2020 09:57:23 GMT; Max-Age=7200; path=/; HttpOnly
Transfer-Encoding: chunked
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 34
Content-Type: application/json
Host: qa.api.platform
Origin: http://localhost:4200
Referer: http://localhost:4200/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

**Comment by delfinogomes** [comment]
Well, reading the code, it looks like absolute paths are ignored in the filter and demand a custom implementation as documented in the code:
https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/common/http/src/xsrf.ts#L75

But IMHO, it should not assume that a absolute path has a diferent origin, becaus it's common in development to have a backend running in a different port, but still the same origin.

Maybe this would open a security breach, but this last part is just a guess.

**Comment by alxhub** [comment]
> Maybe this would open a security breach, but this last part is just a guess.

Your instincts are correct - we avoid adding the token to _any_ absolute URL precisely for this reason. We shouldn't make assumptions about where the security boundaries are in your particular deployment.

That said, it might be reasonable for `withOptions` to accept a list of trusted origins/URL prefixes which should receive the token. I'm tagging this issue as a `use-case` for us to consider/discuss.

**Comment by biolauri** [comment]
I'd really like the feature to be able to add an additional trusted origin.

@alxhub, do I wrap it up correctly that this issue covers fixing the _bug_ you mention in https://github.com/angular/angular/issues/20511#issuecomment-636189306 and adding some options to add a trusted origin? Or shall I open a new bug for the security issue?  
Actually, I'd not only consider that a bug, but kind of a security flaw (albeit minor) as content of a _`SameSite` restricted cookie_ might be sent to a different site and people might not be aware of this when trusting on the build-in XSRF interceptor.

**Comment by petebacondarwin** [comment]
Closing as this feature did not get enough community support.
