### ISSUE TITLE
Build goes blank, just app-root tag in the DOM

### ISSUE THREAD

**Issue by whizyrel** [angular/angular#36252]
I have this project that built the first two times and afterwards I discovered the build only renders a blank page with app-root tag and nothing else as the child not even router-outlet.

ng serve --aot - works great
ng serve --prod - works great
ng build --prod --base-href ./ - blank page

Base href points to ./
Output directory is dist/[project-name]

I use angular@8.2.14, angular-cli@8.3.25

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
