### ISSUE TITLE
Case conversion pipes do not compose under strict TS checking

### ISSUE THREAD

**Issue by ranma42** [angular/angular#36259]
# 🐞 bug report

### Affected Package
`@angular/common`
The issue seems to be related to an incoherence between the implementation and signature of `LowerCasePipe`, `TitleCasePipe`, and `UpperCasePipe`.
https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/common/src/pipes/case_conversion_pipes.ts#L32-L38

### Is this a regression?
No, this works as intended when either
 - templates are not typechecked
 - typescript is not strict

Long ago Angular performed very limited checking of the templates, so it was much harder to get to this issue.

### Description
The `lowercase` (/`titlecase`/`uppercase`) pipe is implemented to handle `null` values (which might come from an `async` or a `date` pipe), but its signature does not reflect this.

## 🔬 Minimal Reproduction

https://github.com/ranma42/async-lowercase

## 🔥 Exception or Error
<pre><code>ERROR in src/app/app.component.html:1:4 - error TS2345: Argument of type 'string | null' is not assignable to parameter of type 'string'.
  Type 'null' is not assignable to type 'string'.

1 {{ v | date | lowercase }}
     ~~~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 9.1.0
Node: 12.16.0
OS: darwin x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0</code></pre>

**Comment by JoostK** [comment]
Tracking as FW-2032

**Comment by ranma42** [comment]
I can write a PR to fix it and possibly improve the typing of other pipes, but I will need some guidance regarding what should happen for `undefined` values. Some pipes seem to pass them through (`slice`), some map them to `null` (`date`, `number`).
I also found some inconsistencies in typing (and between typing and implementation), such as `async`, which is declared as returning `undefined` when passed `undefined`, but actually returns `null`.

What is the best way forward? Opening a PR and discussing this stuff on it?
