### ISSUE TITLE
[Bug] network timeout at: http://registry.npmjs.org/@angular/common/-/common-9.1.0.tgz

### ISSUE THREAD

**Issue by iameduardod** [angular/angular#36266]
I have tried multiple internet connections and hotspots, but this file always times out when doing a fresh npm install. Even after a npm cache clean. 

**NOT AN ISSUE WITH MY CONNECTION OR NPM AS OTHER PACKAGES DOWNLOAD FINE**

![image](https://user-images.githubusercontent.com/29149580/77693087-c8dced00-6f75-11ea-942a-fcd8eface15e.png)

**Comment by JoostK** [comment]
It downloads just fine for me (in The Netherlands) and NPM infrastructure/network is not something that Angular can do something about, so we can't help you resolve this problem.

**Comment by IgorMinar** [comment]
It looks like a transient npm outage - we occasionally see those and they are always due to network / npm infra issues and unfortunately not something we can control via Angular CLI. 😞

I'm sorry about the disruption.
