### ISSUE TITLE
How to access client's custom headers in Angular

### ISSUE THREAD

**Issue by m00zi** [angular/angular#36267]
I know how to implement interceptor in angular in order to add header to request toward backend, but I dont know how to read client headers when client access specefic route for example client access http://localhost:4200/ but there is some custom headers in the GET request from browser, for instance "X-Forwarded-For" how I can get this header inside app.component.ts ?

I am using latest version of angular :
```
Node: 12.13.1
OS: darwin x64

Angular: 9.0.7
```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
