### ISSUE TITLE
Is running multiple angular apps on the same page supported?

### ISSUE THREAD

**Issue by jared-christensen** [angular/angular#36261]
Is having multiple Angular apps on the same page something that is supported or something that is a good idea? I have been able to do it and I have seen plenty of articles showing how it can be done. We are about to build an architecture with this as its backbone but I do have concerns if it is something that we should be doing. I realize this is maybe not the best place for a question like this but I was not sure where else to ask.

**Comment by flash-me** [comment]
Hi @jared-christensen,

have a look at this [repo](https://github.com/flash-me/angular-micro-frontends), which actually does this implicitly.

You don't need to use angular elements to make it work. 

cheers
flash :zap:

**Comment by mlc-mlapis** [comment]
@jared-christensen Yep, it possible and working. The only important factor is the level of the redundancy because each standalone app has some part of the Angular platform code inside.

**Comment by jared-christensen** [comment]
I'm not really asking if it is possible as I have done it with Angular Elements. To make it work it felt hacky and fragile. For example, I had some CSS classes collide because the build repeated some of the namespaces when faking isolation. What I'm really asking is it a good idea to use multiple apps on the same page for an enterprise app.

> Ian: Your scientists were so preoccupied with whether or not they could, they didn’t stop to think if they should.

**Comment by jared-christensen** [comment]
> Hi @jared-christensen,
> 
> have a look at this [repo](https://github.com/flash-me/angular-micro-frontends), which actually does this implicitly.
> 
> You don't need to use angular elements to make it work.
> 
> cheers
> flash ⚡️

This looks

**Comment by flash-me** [comment]
> @jared-christensen Yep, it's possible and working. The only important factor is the level of the redundancy because each standalone app has some part of the Angular platform code inside.

@mlc-mlapis 

It depends :)

cheers 
flash :zap:

**Comment by flash-me** [comment]
> @jared-christensen Yep, it's possible and working. The only important factor is the level of the redundancy because each standalone app has some part of the Angular platform code inside.

@mlc-mlapis 

It depends :)

cheers 
flash :zap:

**Comment by alxhub** [comment]
Closing this issue as the question has been answered. But to reiterate, yes, it's possible to bootstrap multiple Angular apps on the same page.
