### ISSUE TITLE
9.1 Runtime errors

### ISSUE THREAD

**Issue by spock123** [angular/angular#36265]
Hi, 
After updating our application from 9.0.7 -> 9.1 we're getting strange errors.

What's even more scary is that these errors don't appear in development mode, and there are no compile errors. Our app experiences runtime errors like this when trying to load  a lazy loaded module:

# 🐞 bug report

### Is this a regression?

Yes, everything works fine in 9.0.7

## 🔥 Exception or Error
<pre><code>
Uncaught (in promise): ReferenceError: Cannot access 'P' before initialization
ReferenceError: Cannot access 'P' before initialization
</code></pre>

Other error experienced: 

<pre><code>
Error: Uncaught (in promise): ReferenceError: _rollupMoment__default is not defined
ReferenceError: _rollupMoment__default is not defined
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.0
Node: 12.13.1
OS: darwin x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.0
@angular-devkit/build-angular      0.901.0
@angular-devkit/build-optimizer    0.901.0
@angular-devkit/build-webpack      0.901.0
@angular-devkit/core               9.1.0
@angular-devkit/schematics         9.1.0
@angular/cdk                       9.2.0
@angular/fire                      6.0.0-rc.1
@angular/material                  9.2.0
@angular/material-moment-adapter   9.2.0
@ngtools/webpack                   9.1.0
@schematics/angular                9.1.0
@schematics/update                 0.901.0
rxjs                               6.5.4
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

I tried removing node_modules folder and reinstalling everything again - same result.

Tried reverting to Typescript 3.7 - same result.

Cheers

**Comment by spock123** [comment]
The issue occurs when loading any lazy loaded module.

**Comment by JoostK** [comment]
This was reported earlier today in #36248 and there's some discussion going on in angular/components#18925. That issue might be moved from "components" repo to the CLI (depending on the root cause) but it's not a framework issue, so please follow angular/components#18925 for now.
