### ISSUE TITLE
ng-model: viewModel doesn't update when model value is changed programatically

### ISSUE THREAD

**Issue by mgreenland** [angular/angular#3627]
To reproduce:

```dart
@Component(selector: 'example')
@View(directives: const [formDirectives], template: r'''
<input [(ng-model)]="value"></input>
<button (click)="doSwap()">Swap with "{{swap}}"</button>
''')
class ExampleComponent {
  String value = 'value';
  String swap = 'swap';
  void doSwap() {
    var tmp = value;
    value = swap;
    swap = tmp;
  }
}
```

1. Type something like "banana" into the input.
2. Click the "Swap with "swap"" button. The input will change to say "swap", and the button will change to say "Swap with "banana"".
3. Click the swap button again. The input will still say "swap", even though the value of `value` is now "banana".

I think what's going on is that the NgModel directive keeps around a `viewModel` field, which is the last thing typed into the input. After typing "banana", `viewModel` is updated to be "banana". But when `value` is programatically changed to "swap", `viewModel` isn't updated. So when `value` is swapped back to "banana", NgModel thinks the value hasn't changed, because it's the same as `viewModel`.

I think that just doing a `this.viewModel = this.model` in NgModel's `onChange` method would fix this, but there might be other side effects of that that I don't understand.

**Comment by GoossensMichael** [comment]
Could you provide all the code for a basic test? You can use Plunker if you want.

**Comment by mgreenland** [comment]
Yes, that's basically what I have. Thanks for providing a demo!
