### ISSUE TITLE
What is the best practice to put Header/Footer component in Angular 4+?

### ISSUE THREAD

**Issue by blueeye113** [angular/angular#36282]
I'd like to follow the Angular best practice to put component in proper module.
Header and footer components are used very frequently.

Question is:
These components should put in shared module or core module?

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
