### ISSUE TITLE
Optional injected dependency fails when strictNull set to true

### ISSUE THREAD

**Issue by nzacca** [angular/angular#36288]
# 🐞 bug report

### Affected Package

Not sure.

### Is this a regression?

Possibly? #25544 appears to be related but that indicates this was fixed.

### Description

When `strictNull` compiler option is set to `true` in tsconfig, `Optional` injected dependencies with a type unioned with null throw a `Can't resolve all parameters for <component>` error.

The example below uses an NgControl which follows the guide for creating a custom MatFormFieldControl here: https://material.angular.io/guide/creating-a-custom-form-field-control#-code-ngcontrol-code-

I also included another Injectable as an example as I thought it might be related to NgControl being abstract but ran into the same issue.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-mvwhe7?file=src%2Fapp%2Fapp.component.ts

## 🔥 Exception or Error
<pre><code>
Can't resolve all parameters for Child: (?).
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.0
Node: 12.16.1
OS: linux x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.1.0
@angular/cdk                      9.2.0
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.2.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.41.2
</code></pre>

I'm not sure if this is expected behavior or not. If expected, perhaps something could be added to the docs to help avoid these issues. Hopefully this helps someone in future!

Workarounds: 
1. adding explicit @Inject(X); 
2. removing null union; 
3. set strictNull to false in tsconfig

**Comment by kara** [comment]
Yeah, this is a weird error. You'd expect with all optional dependencies that you'd never get the "can't resolve" error. I'm not seeing this issue when I port the Stackblitz to Ivy - are you seeing it in Ivy too?

**Comment by nzacca** [comment]
Hi @kara ! Doesn't v9 have Ivy on by default or am I missing something in the config?

**Comment by JoostK** [comment]
This is working as expected now, with the remark that JIT compiles need a custom transformer as TypeScript itself does not include a type reference in decorator metadata for complex types such as unions. This is integrated into the CLI by default though.
