### ISSUE TITLE
FormControl with comma fails in Firefox 74.0 (with input type number)

### ISSUE THREAD

**Issue by DamienCollet** [angular/angular#36289]
### Description

With the new version of firefox (74.0), on input type="number" with a formControl, when a comma is added, the formcontrol value doesn't have the comma.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-issue-repro2-2mwocx

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.2.0
Node: 10.16.0
OS: darwin x64
Angular: 8.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.802.0
@angular-devkit/build-angular      0.802.0
@angular-devkit/build-ng-packagr   0.802.0
@angular-devkit/build-optimizer    0.802.0
@angular-devkit/build-webpack      0.802.0
@angular-devkit/core               8.2.0
@angular-devkit/schematics         8.2.0
@angular/cdk                       8.1.2
@angular/material                  8.1.2
@angular/material-moment-adapter   8.1.2
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.2.0
@schematics/angular                8.2.0
@schematics/update                 0.802.0
ng-packagr                         5.3.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.38.0
</code></pre>

**Anything else relevant?**
this a browser specific issue (Firefox 74.0)

**Comment by SheppardX** [comment]
we have these problem too and we can approve its Firefox 74, on Firefox 73 it worked.

**Comment by AndrewKushnir** [comment]
Hi @DamienCollet, thanks for providing a repro.

I've just tested this behavior using Firefox (76.0.1) and Chrome (83.0.4103.61) and here is the observed behavior:
- when I type "1.2" - it works in both browsers
- when I use comma (i.e. "1,2") - in Firefox the control value becomes blank, but Chrome doesn't allow me to input comma (so it stays just "1"), so the "1,2" doesn't seem to be a valid value for the <input type="number"> in "en-US" locale (default in my browser) and browsers handle that slightly differently (which looks ok in this case)

It looks like everything works as expected, so I'll close this ticket. Feel free to reopen if the problem still exists.

Thank you.
