### ISSUE TITLE
ngcc fails to scan directory in Azure DevOps Hosted Agent

### ISSUE THREAD

**Issue by ComradeCow** [angular/angular#36283]
# 🐞 Bug report

### Command (mark with an `x`)

`ngcc`

### Is this a regression?

Unsure, we're using a different command than previously.

### Description

After upgrading to Angular 9.1, the `ngcc` postinstall script no longer compiles projects in our `node_modules` folder.

The release changelog for Angular 9.1 mentions changes to running the `ngcc` command. [Angular.io states ](https://angular.io/guide/ivy#ivy-and-universalapp-shell) the `postinstall` script should be "ngcc" (changing from `ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points`). 

When this runs on local development machines (Windows, and WSL), the node_modules folder is scanned and Angular Material et. al are built in the various formats (`esm2015`, `esm5`, etc). 

Our CI system runs in Azure DevOps on Linux Hosted (ubuntu 18.04, x64) agents. When the postinstall script runs there, the command completes immediately with no targets compiled. The various libs and such are compiled when we run `ng [build|test] --project=[blah]` commands however. We cache our `node_modules` install so we can farm out the test, build steps for the multiple projects in our workspace in parallel more quickly. In 9.0, the cache would include the pre-compiled projects, but with 9.1 those are no longer in the cache, causing our CI build to take much longer.

## 🔬 Minimal Reproduction

0) set up package.json with specified `postinstall` script, targeting Angular 9.1 & Material 9.2
1) npm ci

## 🔥 Exception or Error

The build output will say it invokes `ngcc`, but nothing is compiled. We also tried running `ngcc` with `--async false` with the same results.

We ran the command with `-l debug` and saw this output:
<pre><code>
Debug: Forking unlocker child-process
Debug: Attemping to write lock-file at /home/vsts/work/1/s/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__ with PID 3261
Debug: Written lock-file at /home/vsts/work/1/s/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__ with PID 3261
Debug: Running ngcc on SingleProcessExecutorSync.
Debug: Analyzing entry-points...
Debug: No manifest found for /home/vsts/work/1/s so walking the directories for entry-points.
Debug: Walking directories took 0s.
Debug: Analyzed 0 entry-points in 0s. (Total tasks: 0)
Debug: Processing tasks...
Debug: Processed tasks in 0s.
Debug: Attempting to remove lock-file at /home/vsts/work/1/s/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.
Debug: PIDs match (3261), so removing /home/vsts/work/1/s/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.
Debug: Run ngcc in 0s.
Debug: Starting unlocker at process 3275 on behalf of process 3261
Debug: The lock-file path is /home/vsts/work/1/s/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__
Debug: Attempting to remove lock-file at /home/vsts/work/1/s/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.
Debug: The lock-file at /home/vsts/work/1/s/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__ was already removed.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.0
Node: 12.10.0
OS: linux x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.7
@angular-devkit/build-angular      0.901.0
@angular-devkit/build-ng-packagr   0.901.0
@angular-devkit/build-optimizer    0.901.0
@angular-devkit/build-webpack      0.901.0
@angular-devkit/core               9.0.7
@angular-devkit/schematics         9.0.7
@angular/cdk                       9.2.0
@angular/material                  9.2.0
@angular/material-moment-adapter   9.2.0
@ngtools/webpack                   9.1.0
@schematics/angular                9.0.7
@schematics/update                 0.901.0
ng-packagr                         9.0.3
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.42.0
</code></pre>

**Comment by petebacondarwin** [comment]
So to clarify. What is the current `ngcc` command you run and when do you run it? E.g. before you cache the node_modules or after?
You are saying that locally everything is fine? But only on your CI do you have this problem?
You then compiling some local libs? These compile successfully? Are you able to use them in ivy-enabled apps?

**Comment by ComradeCow** [comment]
Sorry for not being clear.  Everying eventually compiles, tests, and runs correctly.  Due to the complicated nature of our build, we want to cache and reuse the `node_modules` folder across multiple agents. `ngcc` doesn't run when we expect it to, so our caching mechanism misses out.

Our package.json is currently set up as:

```json
{
  "scripts": {
    // snip
    "postinstall": "ngcc"
  },
  "packages": {
    "@angular/cli": "9.1.0",
    // other stuff
  }
}
```

We have a NX workspace set up with around 25 projects that need testing and building (all Ivy enabled), so we run multiple agents in parallel.  We modeled our build after [Nrwl's parallel Azure build example](https://github.com/nrwl/nx-azure-build). One agent runs first to scan what's affected by the PR, then we fan out to build/test what's needed in parallel to many agents. To speed things along, we cache & share the `node_modules` folder from the first scan job, so the build / test jobs don't need to re-run `npm ci`.

Our CI build is roughly set up as:
(Our "scan job" on a single agent)
* git clone
* if cache available:
  * un-tarball cached node_modules folder
* else:
  * `npm ci`
* figure out what changed
* if there was no cache available:
  * tar, gz node_modules folder and upload

(then on multiple agents, in parallel)
* git clone
* un-tarball cached node_modules folder
* `ng [build | test]` whatever project

We expect `ngcc` to run during that first scan job (during `npm ci`) so all our npm libs (like Angular, Material, etc) are pre-compiled and ready to go in the cache.  However, ngcc says there's nothing that needs building (with the message posted above).  When the build calls `ng [build | test]`, ngcc does the pre-compiling magic needed (we see the "Building "foo" as esm2015" messages). Everything builds correctly, but we end up compiling the npm libs in every build/test job.  This caused our CI build times to roughly double. 

When we were targeting Angular 9, our postinstall script was `ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points` as was specified by the migration guide. `ngcc` built everything during that inital scan job, so our cache had the ngcc output ready to go.

When our devs run `npm ci` locally (on Windows or Windows Subsystem for Linux), the `ngcc` scripts scans and builds all the Angular libs in `node_modules` during the npm ci. They don't see additional output from ngcc when they run `ng [serve | test | build]`.

**Comment by petebacondarwin** [comment]
Ahah! I wonder if the new entry point manifest is causing problems... can you see if you have a file in your schedule node_modules file that looks like`__ngcc_entry_points__.json`. And see what is in it?

**Comment by ComradeCow** [comment]
When ngcc runs in our build, node_modules is empty. The build runs on a new
container, and first thing `npm ci` does is nuke node_modules anyway.

I'll be back to work on Monday, I'll upload a copy of that file from a Dev
machine (post install).

**Comment by olivierboudet** [comment]
I have the exact same issue when trying to upgrade to 9.1.0. 
```
    "postinstall": "ngcc --properties es2015 browser module main",
```
With angular 9.0, the postinstall script compiles all the node modules.
Since angular 9.1, the postinstall script do nothing.

```
Debug: Forking unlocker child-process
Debug: Attemping to write lock-file at /home/xxxx/Documents/passwebv2/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__ with PID 13375
Debug: Written lock-file at /home/xxxx/Documents/passwebv2/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__ with PID 13375
Debug: Running ngcc on ClusterExecutor (using 8 worker processes).
Debug: Analyzing entry-points...
Debug: No manifest found for /home/xxxx/Documents/passwebv2 so walking the directories for entry-points.
Debug: Walking directories took 0s.
Debug: Analyzed 0 entry-points in 0s. (Total tasks: 0)
Debug: Attempting to remove lock-file at /home/xxxx/Documents/passwebv2/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.
Debug: PIDs match (13375), so removing /home/xxxx/Documents/passwebv2/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.
Debug: Run ngcc in 0s.
Debug: Starting unlocker at process 13382 on behalf of process 13375
Debug: The lock-file path is /home/xxxx/Documents/passwebv2/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__
Debug: Attempting to remove lock-file at /home/xxxx/Documents/passwebv2/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.
Debug: The lock-file at /home/xxxx/Documents/passwebv2/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__ was already removed.

```

There is no file called __ngcc_entry_points__.json in the node_modules directory.

**Comment by petebacondarwin** [comment]
I think this looks wrong:

```
Debug: No manifest found for /home/xxxx/Documents/passwebv2 so walking the directories for entry-points.
```

It ought to be looking in the `/home/xxxx/Documents/passwebv2/node_modules` folder for an entry-point manifest, which indicates to me that the `basePath` being passed to ngcc is one directory to high...

And we can see the same problem in @ComradeCow's log: `No manifest found for /home/vsts/work/1/s `.

**Comment by petebacondarwin** [comment]
Can you both provide your `tsconfig.json` `compilerOptions -> paths` setting? I think I might know what is going on...

**Comment by olivierboudet** [comment]
This is mine : 

```
"compilerOptions": {
      "baseUrl": ".",
      "paths": { "*": ["types/*"] },
    [...]
  }
```

**Comment by petebacondarwin** [comment]
So the thing is that we have this function:

```ts
export function getBasePaths(
    sourceDirectory: AbsoluteFsPath, pathMappings: PathMappings | undefined): AbsoluteFsPath[] {
  const fs = getFileSystem();
  const basePaths = [sourceDirectory];
  if (pathMappings) {
    const baseUrl = resolve(pathMappings.baseUrl);
    Object.values(pathMappings.paths).forEach(paths => paths.forEach(path => {
      // We only want base paths that exist and are not files
      let basePath = join(baseUrl, extractPathPrefix(path));
      while (basePath !== baseUrl && (!fs.exists(basePath) || fs.stat(basePath).isFile())) {
        basePath = fs.dirname(basePath);
      }
      basePaths.push(basePath);
    }));
  }
  basePaths.sort().reverse();  // Get the paths in order with the longer ones first.
  return basePaths.filter(removeContainedPaths);
}
```

Note that at the bottom we have  `return basePaths.filter(removeContainedPaths);`.

Now my thinking is that if `sourceDirectory` is `/home/xxxx/Documents/passwebv2/node_modules` but for some reason one of the paths extracted from `paths` turns out to be `/home/xxxx/Documents/passwebv2` then the `node_modules` path will be stripped and we will not consider it directly.

Then recently we added optimisations to the `DirectoryWalkerEntryPointFinder` where if the top level `basePath` contains an "invalid" entry-point, rather than a folder that contains no entry-point, then we bail out. And since `/home/xxxx/Documents/passwebv2` probably contains your project `package.json` but is not a valid entry-point since the various properties in there will not line up we bail.

Before we revert (or modify) these optimisations, it would be good to work out why your `basePaths` contain `/home/xxxx/Documents/passwebv2` rather than `/home/xxxx/Documents/passwebv2/node_modules`...

**Comment by petebacondarwin** [comment]
I think the problem is this line: `const baseUrl = resolve(pathMappings.baseUrl);`
Up till now the `baseUrl` passed through has always been absolute, so the call to `resolve()` is actually a noop. But what if your `baseUrl` is left as `.`, in which case we would resolve it against the current working directory, which is probably your project directory.

**Comment by olivierboudet** [comment]
Thanks @petebacondarwin, but I did not understand if I need to test something on my side to see why my  ̀basePaths` contain `/home/xxxx/Documents/passwebv2` rather than `/home/xxxx/Documents/passwebv2/node_modules`.
If so, can you elaborate on possible tests ?

**Comment by petebacondarwin** [comment]
Is it possible to modify the code in `/home/xxxx/Documents/passwebv2/node_modules/packages/compiler-cli/ngcc/src/entry_point_finder/utils.js` on your CI to output the `sourceDirectory`, `baseUrl`, and `paths` values:

```js
    function getBasePaths(sourceDirectory, pathMappings) {
        var fs = file_system_1.getFileSystem();
        var basePaths = [sourceDirectory];
        if (pathMappings) {
            var baseUrl_1 = file_system_1.resolve(pathMappings.baseUrl);
            // NEW CODE
            console.log(sourceDirectory, pathMappings.baseUrl, pathMappings.paths, baseUrl_1);
            // END CODE
            ...
```

**Comment by olivierboudet** [comment]
I have the issue also on my laptop (not only in CI), so I tried on it : 
```
/home/xxxx/Documents/passwebv2/node_modules /home/xxxx/Documents/passwebv2 { '*': [ 'types/*' ] } /home/xxxx/Documents/passwebv2
Debug: Forking unlocker child-process
Debug: Attemping to write lock-file at /home/xxxx/Documents/passwebv2/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__ with PID 13554
Debug: Written lock-file at /home/xxxx/Documents/passwebv2/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__ with PID 13554
Debug: Running ngcc on ClusterExecutor (using 8 worker processes).
Debug: Analyzing entry-points...
Debug: No manifest found for /home/xxxx/Documents/passwebv2 so walking the directories for entry-points.
Debug: Walking directories took 0s.
Debug: Analyzed 0 entry-points in 0s. (Total tasks: 0)
Debug: Attempting to remove lock-file at /home/xxxx/Documents/passwebv2/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.
Debug: PIDs match (13554), so removing /home/xxxx/Documents/passwebv2/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.
Debug: Run ngcc in 0s.
Debug: Starting unlocker at process 13561 on behalf of process 13554
Debug: The lock-file path is /home/xxxx/Documents/passwebv2/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__
Debug: Attempting to remove lock-file at /home/xxxx/Documents/passwebv2/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.
Debug: The lock-file at /home/xxxx/Documents/passwebv2/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__ was already removed.

```

**Comment by petebacondarwin** [comment]
Great @olivierboudet - thanks.

Can you confirm whether `/home/xxxx/Documents/passwebv2/types` exists in your project?

**Comment by olivierboudet** [comment]
Oh, you are right, this folder does not exists. Removing it from tsconfig helps a lot :+1: 
```
"compilerOptions": {
      "baseUrl": ".",
      "paths": { "*": [] },
}
```

**Comment by ComradeCow** [comment]
We had a path in our tsconfig that pointed to empty space (left over from a refactor and didn't get 
cleaned up) - once I removed those `ngcc` ran over the repo as we expected it too :tada:!

Just to state out what happened - our tsconfig follows the pattern Nrwl's schematics set up for us. Each project is imported in other projects with a `@scope/project-name` import.

From our `tsconfig` (anonymizing a bit) :

```jsonc
{
  "baseUrl": ".",
  "paths": {
   // removing this guy fixed our problem:
    "animations/*": ["dist/animations/*"],
    // most are like this:
    "@company/lib1": ["libs/lib1/src/index.ts"],
    "@company/lib2": ["libs/lib2/src/index.ts"],
    // some have multiple layers
    "@company/groupX/libY": ["libs/groupX/libY/src/index.ts"],
    // and we have one example like:
    "@company/groupX/productY/libZ/testing": [
      "libs/groupX/productY/libZ/src/testing.ts"
    ],
  }
}
```

Dropped out the paths that aren't valid anymore, and now the ngcc output is captured in our cache!

**Comment by petebacondarwin** [comment]
Marvellous! I am glad you are sorted. I am putting together a PR to ignore these missing paths and to log a warning, so it shouldn't be such a pain to debug in the future.
