### ISSUE TITLE
has no exported member 'Renderer'. Did you mean 'Renderer2'?

### ISSUE THREAD

**Issue by liyang010813** [angular/angular#36293]
![微信图片_20200328165641](https://user-images.githubusercontent.com/31497640/77819351-2f4c4180-7115-11ea-9e2a-16f883807cc4.png)
![image](https://user-images.githubusercontent.com/31497640/77819368-44c16b80-7115-11ea-9fde-749e4c0f40e4.png)

**Comment by pkozlowski-opensource** [comment]
Those are problems with the dependencies that you are using and that are not updated to the version compatible with Angular 9. Please update the problematic dependencies (https://github.com/swimlane/ngx, https://github.com/mezoistvan/ng2-flatpickr)
