### ISSUE TITLE
After migration to 9.1.0 file `__ngcc_entry_points__.json` appears in workspace

### ISSUE THREAD

**Issue by vmasek** [angular/angular#36296]
# 🐞 bug report

### Affected Package
Angular 9.1.0

### Is this a regression?

This didn't occur in pre 9.1.0-* versions

### Description

There seems to be a file generated in the workspace `src/__ngcc_entry_points__.json`

## 🔬 Minimal Reproduction
It has first occurred after migration from 9.0.0 to 9.1.0. After that does eventually reappear after deleting it and building/serving application several times, but I didn't notice when exactly. 

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.0
Node: 12.16.1
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.0.6
@angular-devkit/schematics        9.1.0
@angular/cdk                      9.2.0
@angular/flex-layout              9.0.0-beta.29
@ngtools/webpack                  9.1.0
@nguniversal/builders             9.0.2
@nguniversal/common               9.0.2
@nguniversal/express-engine       9.0.2
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
We don't know if it is intended to have this file and if it should be added to version control. I suppose not. If yes it should probably be documented as intentional.

It was also mentioned in the issue regarding hanging build https://github.com/angular/angular/issues/36272#issuecomment-604361544

**Comment by petebacondarwin** [comment]
We should not be writing this file outside the node_modules folder. I'll submit a PR.

**Comment by david-mccoy** [comment]
I am seeing a __ngcc_entry_points__.json file being written at `libs/__ngcc_entry_points__.json' in my project. Should that be preventable as well?

**Comment by petebacondarwin** [comment]
Fixed by https://github.com/angular/angular/pull/36299
