### ISSUE TITLE
ng update add @Directive() decorator above base component

### ISSUE THREAD

**Issue by ofirrifo** [angular/angular#36303]
# 🐞 bug report

### Description
Upgrade to angular 9 from 8 added to my base component a @Directive() decorator instead of @Component()  decorator.

now when I execute the ng lint I get an error:
**The name of the class MyBaseComponent should end with the suffix Directive**

For example:

BEFORE UPDATE
```
export class MyBaseComponent{
  @Input name: string;
}

@Component({
  selector: 'app-my',
  templateUrl: '...',
  styleUrls: ['...']
})
export class MyComponent extends MyBaseComponent {
  
}

@Component({
  selector: 'app-my-second',
  templateUrl: '...',
  styleUrls: ['...']
})
export class MySecondComponent extends MyBaseComponent {

}
```

AFTER UPDATE
```
@Directive()
export class MyBaseComponent{
  @Input name: string;
}

@Component({
  selector: 'app-my',
  templateUrl: '...',
  styleUrls: ['...']
})
export class MyComponent extends MyBaseComponent {
  
}

@Component({
  selector: 'app-my-second',
  templateUrl: '...',
  styleUrls: ['...']
})
export class MySecondComponent extends MyBaseComponent {

}
```

I read this [migration-undecorated-classes](https://angular.io/guide/migration-undecorated-classes) but it not show how to fix my case

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.0
Node: 12.3.1
OS: darwin x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular-devkit/schematics-cli    0.803.25
@angular/cdk                      8.2.3
@angular/material                 8.2.3
@ngtools/webpack                  9.1.0
@nguniversal/express-engine       8.2.6
@schematics/angular               9.1.0 (cli-only)
@schematics/schematics            0.803.25
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by petebacondarwin** [comment]
Adding a `Directive()` decorator is the correct thing to do for it to work with ivy - remember that a component must have a template which obviously your base component does not provide.

You can avoid the error by disabling that lint rule just for that class. We should probably look into the migration to add such as lint comment automatically to prevent unwanted warnings/errors.

**Comment by ofirrifo** [comment]
Thanks @petebacondarwin 
:)

**Comment by ofirrifo** [comment]
@petebacondarwin 
can I decorate the base component like this ?
```
@Component({template: ''})
export abstract class BaseDropdownComponent {}
```

instead of
```
/* tslint:disable:directive-class-suffix */
@Directive()
export abstract class BaseDropdownComponent {}
```

**Comment by petebacondarwin** [comment]
Possibly - does the application build successfully? If so, then you are probably OK to do this.
