### ISSUE TITLE
Passing an object with ngValue in a Reactive Form logs a registerOnChange error to the console

### ISSUE THREAD

**Issue by WilliamHerbert** [angular/angular#36300]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms (most likely)

### Is this a regression?

 Present in 8 and 9

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-kgnjwv

## 🔥 Exception or Error
<pre><code>

core.js:6185 ERROR TypeError: control.registerOnChange is not a function
    at setUpModelChangePipeline (forms.js:3427)
    at setUpControl (forms.js:3306)
    at FormGroupDirective.addControl (forms.js:7547)
    at FormControlName._setUpControl (forms.js:8363)
    at FormControlName.ngOnChanges (forms.js:8284)
    at FormControlName.wrapOnChangesHook_inPreviousChangesStorage (core.js:26853)
    at callHook (core.js:4690)
    at callHooks (core.js:4650)
    at executeInitAndCheckHooks (core.js:4591)
    at selectIndexInternal (core.js:9621)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.1.0
Node: 12.14.0
OS: darwin x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.3
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Anything else relevant?**

I receive the same error on my Mac as I do in stackblitz.

**Comment by rafaelss95** [comment]
Looking at the provided example, it seems that you're passing the `country` **_FormGroup_** instance to a `formControlName` _@Input_.

**Comment by WilliamHerbert** [comment]
User Error.

I did not realize that a FormControl could also be composed of nested FormControls.  I thought that was explicitly the domain of a FormGroup.

[StackBlitz of solution](https://stackblitz.com/edit/angular-wcqfdc)
