### ISSUE TITLE
ViewContainerRef is not working Angular 9

### ISSUE THREAD

**Issue by afeef1915** [angular/angular#36315]
Problem 

* cannot user viewContainerRef fro parent child communication.

Code was working in Angular 8.2

     this.viewContainerRef[ '_data' ].componentView.component.viewContainerRef[ '_view' ].component;

Error

> ERROR TypeError: Cannot read property 'componentView' of undefined

Ng Version

    Package                      Version
    ------------------------------------------------------
    @angular-devkit/architect    0.900.7
    @angular-devkit/core         9.0.7
    @angular-devkit/schematics   9.0.7
    @schematics/angular          9.0.7
    @schematics/update           0.900.7
    rxjs                         6.5.3

Cannot replicate the issue in stackblitz

https://stackblitz.com/edit/angular-testangular9-communicating-x

Any suggestion  is most welcome.

   Working ViewconatainerRef  console.log				

				ViewContainerRef_ {_view: {…}, _elDef: {…}, _data: {…}, _embeddedViews: Array(0)}
					element: (...)
					injector: (...)
					parentInjector: (...)
					length: (...)
					_view: {def: {…}, parent: {…}, viewContainerParent: null, parentNodeDef: {…}, context: AComponentComponent, …}
					_elDef: {nodeIndex: 6, parent: null, renderParent: null, bindingIndex: 1, outputIndex: 1, …}
					_data:
					renderElement: app-b-component
					componentView:
					def: {nodeFlags: 3, rootNodeFlags: 1, nodeMatchedQueries: 0, flags: 0, factory: ƒ, …}
					parent: {def: {…}, parent: {…}, viewContainerParent: null, parentNodeDef: {…}, context: AComponentComponent, …}
					viewContainerParent: null
					parentNodeDef: {nodeIndex: 7, parent: {…}, renderParent: {…}, bindingIndex: 1, outputIndex: 1, …}
					context: BComponentComponent {viewContainerRef: ViewContainerRef_, somethingTestB: "Its Sara..!"}
					component: BComponentComponent
					viewContainerRef: ViewContainerRef_
					element: (...)
					injector: (...)
					parentInjector: (...)
					length: (...)
					_view:
					def: {nodeFlags: 50446339, rootNodeFlags: 50331649, nodeMatchedQueries: 0, flags: 0, factory: ƒ, …}
					parent: {def: {…}, parent: {…}, viewContainerParent: null, parentNodeDef: {…}, context: HomeComponentComponent, …}
					viewContainerParent: null
					parentNodeDef: {nodeIndex: 9, parent: {…}, renderParent: {…}, bindingIndex: 8, outputIndex: 6, …}
					context: AComponentComponent {viewContainerRef: ViewContainerRef_, somethingTestA: "Its Sara..!"}
					component: AComponentComponent
					viewContainerRef: ViewContainerRef_
					element: (...)
					injector: (...)
					parentInjector: (...)
					length: (...)
					_view: {def: {…}, parent: {…}, viewContainerParent: null, parentNodeDef: {…}, context: HomeComponentComponent, …}
					_elDef: {nodeIndex: 8, parent: null, renderParent: null, bindingIndex: 8, outputIndex: 6, …}
					_data: {renderElement: app-a-component, componentView: {…}, viewContainer: ViewContainerRef_, template: undefined}
					_embeddedViews: []
					__proto__: Object
					somethingTestA: "Its Sara..!"
					__proto__:
					ngOnInit: ƒ ()
					getParentComponent: ƒ ()
					testClick: ƒ ()
					constructor: ƒ AComponentComponent(viewContainerRef)
					__proto__: Object
					nodes: (8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
					state: 1036
					root: {ngModule: NgModuleRef_, injector: NullInjector, projectableNodes: Array(0), selectorOrNode: "my-app", sanitizer: DomSanitizerImpl, …}
					renderer: DebugRenderer2 {delegate: EmulatedEncapsulationDomRenderer2, data: {…}, debugContextFactory: ƒ}
					oldValues: (2) ["Its Sara..!", "Its Sara..!"]
					disposables: [ƒ]
					initIndex: -1
					__proto__: Object
					_elDef: {nodeIndex: 6, parent: null, renderParent: null, bindingIndex: 1, outputIndex: 1, …}
					_data: {renderElement: app-b-component, componentView: {…}, viewContainer: ViewContainerRef_, template: undefined}
					_embeddedViews: []
					__proto__: Object
					somethingTestB: "Its Sara..!"
					__proto__: Object
					nodes: (5) [{…}, {…}, {…}, {…}, {…}]
					state: 1036
					root: {ngModule: NgModuleRef_, injector: NullInjector, projectableNodes: Array(0), selectorOrNode: "my-app", sanitizer: DomSanitizerImpl, …}
					renderer: DebugRenderer2 {delegate: EmulatedEncapsulationDomRenderer2, data: {…}, debugContextFactory: ƒ}
					oldValues: ["Its Sara..!"]
					disposables: [ƒ]
					initIndex: -1
					__proto__: Object
					viewContainer: ViewContainerRef_ {_view: {…}, _elDef: {…}, _data: {…}, _embeddedViews: Array(0)}
					template: undefined
					__proto__: Object
					_embeddedViews: []
					
					
					
					Not Working consol.log   

						ViewContainerRef {_lContainer: LContainer(9), _hostTNode: TNode, _hostView: LComponentView_DynamicFormBuilderComponent(108)}
						element: (...)
						injector: (...)
						parentInjector: (...)
						length: (...)
						_lContainer: LContainer(9)
						lastIndex: (...)
						lastItem: (...)
						0: LComponentView_DynamicButtonBuilderComponent(57) [app-dynamic-button-panel, TView, 147, LComponentView_DynamicFormBuilderComponent(108), LContainer(9), null, TNode, null, DynamicButtonBuilderComponent, {…}, AnimationRendererFactory, BaseAnimationRenderer, null, LContainer(10), LContainer(10), LComponentView_DynamicFormBuilderComponent(108), LComponentView_DynamicButtonBuilderComponent(57), null, 0, div.button-panel-outer, div.row.justify-content-end.button-panel-row, LContainer(10), LContainer(10), LContainer(10), true, Array(1), true, 16412168, 0, 0, 0, 0, 0, 0, 0, 65634, NgIf, 16412168, 0, 0, 0, 0, 0, 0, 0, 65634, NgIf, 16412168, 0, 0, 0, 0, 0, 0, 0, 65634, NgIf, debug: LViewDebug]
						1: true
						2: -2
						3: LComponentView_DynamicFormBuilderComponent(108) [app-dynamic-form-builder, TView, 147, LComponentView_PortletBuilderComponent(67), null, null, TNode, LCleanup(12), DynamicFormBuilderComponent, {…}, AnimationRendererFactory, BaseAnimationRenderer, null, LContainer(9), LContainer(9), LComponentView_PortletBuilderComponent(67), LComponentView_DynamicFormBuilderComponent(108), null, 0, form#form_personal_details.form-horizontal.container.ng-untouched.ng-pristine.ng-valid.form-in-edit…, LContainer(9), LContainer(9), LContainer(32), KeyValuePipe, div.form-row, LContainer(9), FormGroup, "form-in-edit-mode", "form_personal_details", false, false, Array(23), Array(1), FormGroup, false, {…}, false, {…}, {…}, {…}, 7995912, 0, 0, 0, 0, 0, 0, 0, 65593, FormGroupDirective, NgClass, ɵNgNoValidate, NgControlStatusGroup, FormGroupDirective, true, true, false, false, true, true, false, false, true, true, false, false, false, false, 8023560, 0, 0, 0, 0, 0, 0, 0, 40, NgIf, 8023560, 0, 0, 0, 0, 0, 0, 0, 40, NgIf, 8023560, 0, 0, 0, 0, 0, 0, 0, 40, NgForOf, 8023560, 0, …]
						4: null
						5: null
						6: TNode {tView_: TView, type: 3, index: 25, injectorIndex: 98, directiveStart: 107, …}
						7: comment
						8: null
						length: 9
						debug: LContainerDebug {_raw_lContainer: LContainer(9)}
						__proto__: Array
						_hostTNode: TNode
						type_: (...)
						flags_: (...)
						template_: (...)
						styleBindings_: (...)
						classBindings_: (...)
						tView_: TView {type: 1, id: -1, blueprint: LViewBlueprint(108), queries: null, template: ƒ, …}
						type: 3
						index: 25
						injectorIndex: 98
						directiveStart: 107
						directiveEnd: 108
						directiveStylingLast: -1
						propertyBindings: null
						flags: 3
						providerIndexes: 107
						tagName: "app-dynamic-button-panel"
						attrs: (7) [3, "customButtons", "form", "isPublicPage", "pageDetails", "isLoading", "toggleFormMode"]
						mergedAttrs: (7) [3, "customButtons", "form", "isPublicPage", "pageDetails", "isLoading", "toggleFormMode"]
						localNames: null
						initialInputs: TNodeInitialInputs [null]
						inputs: {form: Array(2), customButtons: Array(2), pageDetails: Array(2), isPublicPage: Array(2), isLoading: Array(2)}
						outputs: {toggleFormMode: Array(2)}
						tViews: null
						next: null
						projectionNext: null
						child: null
						parent: TNode {tView_: TView, type: 3, index: 19, injectorIndex: 40, directiveStart: 50, …}
						projection: null
						styles: null
						residualStyles: undefined
						classes: null
						residualClasses: undefined
						classBindings: 0
						styleBindings: 0
						__proto__: Object
						_hostView: LComponentView_DynamicFormBuilderComponent(108)
						[0 … 99]
						[100 … 107]
						debug: LViewDebug {_raw_lView: LComponentView_DynamicFormBuilderComponent(108)}
						length: 108
						__proto__: Array
						__proto__: ViewContainerRef

**Comment by mlc-mlapis** [comment]
@afeef1915 It seems that you were using non-public API. You can't be surprised that things have been changed internally without guaranteed compatibility.

**Comment by afeef1915** [comment]
Thanks very much for the reply.

Please can you guide me  how can run my code

this.viewContainerRef[ '_data' ].componentView.component.viewContainerRef[ '_view' ].component;

dynamic view code

 @ViewChild(DynamicContainersViewDirective, { static: true }) appDynamicContainersView: DynamicContainersViewDirective;
  @Input() data: any;
  isFileDownloading = false;

  constructor(public componentFactoryResolver: ComponentFactoryResolver,
              private clientAppServices: ClientAppServices) { }

  ngOnInit() {
    const comp = new MainViewItem(DynamicContainerViewComponent, { header: '' });
    const componentFactory = this.componentFactoryResolver.resolveComponentFactory(comp.component);
    const viewContainerRef = this.appDynamicContainersView.viewContainerRef;
    viewContainerRef.clear();
    const componentRef = viewContainerRef.createComponent(componentFactory);
    (componentRef.instance as DynamicContainerViewComponent).data = this.data;
  }

**Comment by afeef1915** [comment]
Why There is missing _data in viewcontainerref

its missing in Angular 9
_data:
renderElement: app-b-component
componentView:

**Comment by mlc-mlapis** [comment]
@afeef1915 One more again, there is a lot of internal changes between Angular 8 and 9. And this is also the key reason why there is `public API` that should be used by any developer outside. So, if you still want to find out some `equivalent` from the internal point of view, you need to study the direct code, all available in GitHub repository. But still, the internal things -> `private API`, can change at any time, so it's really not recommended to use it at all from the outside scope.

**Comment by afeef1915** [comment]
Many Thanks for your  answer.

Please can you guide me how to use public  API instead of non public in vscode.

I try to test in stackblitz
https://stackblitz.com/edit/angular-testangular9-communicating-x

it seems to be working.

**Comment by mlc-mlapis** [comment]
@afeef1915 Not sure what you are expecting, buy the whole `public API` is documented on https://angular.io/api

**Comment by afeef1915** [comment]
Thanks for the help.

I was expecting to test this code
			this.viewContainerRef[ '_data' ].componentView.component.viewContainerRef[ '_view' ].component;

in stackblitz and seems to work.

i don't know what wrong after upgrade to angular 9 in vscode

**Comment by afeef1915** [comment]
> @afeef1915 Not sure what you are expecting, but the whole `public API` is documented on https://angular.io/api

Please can you help I tried Public API

this.viewContainerRef.get(0)  still i got null

**Comment by mlc-mlapis** [comment]
@afeef1915 There are several ways how to do it and it depends on the context and logic, what you want exactly to do. This is not a discussion forum, it's the issues channel, that is monitored by many people, so it's not really a good place.

**Comment by mlc-mlapis** [comment]
@afeef1915 Maybe you can start here: https://stackoverflow.com/questions/35267146/accessing-a-property-in-a-parent-component

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by afeef1915** [comment]
> @afeef1915 Maybe you can start here: https://stackoverflow.com/questions/35267146/accessing-a-property-in-a-parent-component

Thanks for t he help.

But i need to do by this method only.

   this.viewContainerRef[ '_data' ].componentView.component.viewContainerRef[ '_view' ].component

This was working in Angular 8.2 , but update to Angular 9 it stops die to core.d.ts  upgrade

Bug is in CORE.ts

**Comment by mlc-mlapis** [comment]
@afeef1915 Understand, that nobody won't be supporting you on private API to allow you to use it as public API. Sorry.

**Comment by afeef1915** [comment]
> @afeef1915 Understand, that nobody won't be supporting you on private API to allow you to use it as public API. Sorry.

Thanks But this was answered as well in angular issues

https://github.com/angular/angular/issues/10448

to get the parent component
viewContainerRef['_data'].componentView.component.viewContainerRef['_view'].component

My scenario:

@Component({
  selector: 'parent-component',
  template: '<child-component></child-component>'
})
export class ComponentParent{

}


@Component({
  selector: 'child-component',
  template: '<label> Example </label> <button (click)="submit()">Send</button>'
})
export class ComponentChild{

    constructor(private viewContainerRef: ViewContainerRef){}

    getParentComponent():ComponentParent{
        return this.viewContainerRef[ '_data' ].componentView.component.viewContainerRef[ '_view' ].component
    }

    submit(){
      this.getParentComponent().submit();
    }
}

**Comment by mlc-mlapis** [comment]
@afeef1915 Not sure what part of that issue you mean. It's really long and closed. If it is still the pattern of that private API, also the answer is the same. I don't understand why you are fixed to that exceptional point and why you don't use any other public API way, how to get the parent component instance reference.

**Comment by afeef1915** [comment]
> how to get the parent component instance reference.

Many Thanks for guiding me.

I was told to use  this way only  

But injecting parent child works for me

import { Component, OnInit, Inject } from '@angular/core';
import { ParentComponent } from '../views/parent/parent.component';

export class ChildComponent{
    constructor(@Inject(ParentComponent) private parent: ParentComponent){

    }

    someMethod(){
        this.parent.aPublicProperty = 2;
    }
}

**Comment by mlc-mlapis** [comment]
@afeef1915 Yep. It's not the only way how to do it. It depends on the context. I don't know who told it to you, but the one probably didn't know that context and the actual state of Angular progress from version to version. So take those orders with doubts and get the actual state before trying to change something.

**Comment by afeef1915** [comment]
> @afeef1915 Yep. It's not the only way how to do it. It depends on the context. I don't know who told it to you, but the one probably didn't know that context and the actual state of Angular progress from version to version. So take those orders with doubts and get the actual state before trying to change something.

Thanks for that.

I also learned better approach as well

@Inject(forwardRef(() => parentc)) public parent: parentc

work in cyclic dependencies

**Comment by afeef1915** [comment]
> @afeef1915 Yep. It's not the only way how to do it. It depends on the context. I don't know who told it to you, but the one probably didn't know that context and the actual state of Angular progress from version to version. So take those orders with doubts and get the actual state before trying to change something.

Refrence For ViewContainerRef

https://arshadmehmood.com/programming/change-parent-component-values-in-angular-with-viewcontainerref/

**Comment by afeef1915** [comment]
> Problem
> 
> * cannot user viewContainerRef fro parent child communication.
> 
> Code was working in Angular 8.2
> 
> ```
>  this.viewContainerRef[ '_data' ].componentView.component.viewContainerRef[ '_view' ].component;
> ```
> 
> Error
> 
> > ERROR TypeError: Cannot read property 'componentView' of undefined
> 
> Ng Version
> 
> ```
> Package                      Version
> ------------------------------------------------------
> @angular-devkit/architect    0.900.7
> @angular-devkit/core         9.0.7
> @angular-devkit/schematics   9.0.7
> @schematics/angular          9.0.7
> @schematics/update           0.900.7
> rxjs                         6.5.3
> ```
> 
> Cannot replicate the issue in stackblitz
> 
> https://stackblitz.com/edit/angular-testangular9-communicating-x
> 
> Any suggestion is most welcome.
> 
> Working ViewconatainerRef console.log
> 
> ```
> 			ViewContainerRef_ {_view: {…}, _elDef: {…}, _data: {…}, _embeddedViews: Array(0)}
> 				element: (...)
> 				injector: (...)
> 				parentInjector: (...)
> 				length: (...)
> 				_view: {def: {…}, parent: {…}, viewContainerParent: null, parentNodeDef: {…}, context: AComponentComponent, …}
> 				_elDef: {nodeIndex: 6, parent: null, renderParent: null, bindingIndex: 1, outputIndex: 1, …}
> 				_data:
> 				renderElement: app-b-component
> 				componentView:
> 				def: {nodeFlags: 3, rootNodeFlags: 1, nodeMatchedQueries: 0, flags: 0, factory: ƒ, …}
> 				parent: {def: {…}, parent: {…}, viewContainerParent: null, parentNodeDef: {…}, context: AComponentComponent, …}
> 				viewContainerParent: null
> 				parentNodeDef: {nodeIndex: 7, parent: {…}, renderParent: {…}, bindingIndex: 1, outputIndex: 1, …}
> 				context: BComponentComponent {viewContainerRef: ViewContainerRef_, somethingTestB: "Its Sara..!"}
> 				component: BComponentComponent
> 				viewContainerRef: ViewContainerRef_
> 				element: (...)
> 				injector: (...)
> 				parentInjector: (...)
> 				length: (...)
> 				_view:
> 				def: {nodeFlags: 50446339, rootNodeFlags: 50331649, nodeMatchedQueries: 0, flags: 0, factory: ƒ, …}
> 				parent: {def: {…}, parent: {…}, viewContainerParent: null, parentNodeDef: {…}, context: HomeComponentComponent, …}
> 				viewContainerParent: null
> 				parentNodeDef: {nodeIndex: 9, parent: {…}, renderParent: {…}, bindingIndex: 8, outputIndex: 6, …}
> 				context: AComponentComponent {viewContainerRef: ViewContainerRef_, somethingTestA: "Its Sara..!"}
> 				component: AComponentComponent
> 				viewContainerRef: ViewContainerRef_
> 				element: (...)
> 				injector: (...)
> 				parentInjector: (...)
> 				length: (...)
> 				_view: {def: {…}, parent: {…}, viewContainerParent: null, parentNodeDef: {…}, context: HomeComponentComponent, …}
> 				_elDef: {nodeIndex: 8, parent: null, renderParent: null, bindingIndex: 8, outputIndex: 6, …}
> 				_data: {renderElement: app-a-component, componentView: {…}, viewContainer: ViewContainerRef_, template: undefined}
> 				_embeddedViews: []
> 				__proto__: Object
> 				somethingTestA: "Its Sara..!"
> 				__proto__:
> 				ngOnInit: ƒ ()
> 				getParentComponent: ƒ ()
> 				testClick: ƒ ()
> 				constructor: ƒ AComponentComponent(viewContainerRef)
> 				__proto__: Object
> 				nodes: (8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
> 				state: 1036
> 				root: {ngModule: NgModuleRef_, injector: NullInjector, projectableNodes: Array(0), selectorOrNode: "my-app", sanitizer: DomSanitizerImpl, …}
> 				renderer: DebugRenderer2 {delegate: EmulatedEncapsulationDomRenderer2, data: {…}, debugContextFactory: ƒ}
> 				oldValues: (2) ["Its Sara..!", "Its Sara..!"]
> 				disposables: [ƒ]
> 				initIndex: -1
> 				__proto__: Object
> 				_elDef: {nodeIndex: 6, parent: null, renderParent: null, bindingIndex: 1, outputIndex: 1, …}
> 				_data: {renderElement: app-b-component, componentView: {…}, viewContainer: ViewContainerRef_, template: undefined}
> 				_embeddedViews: []
> 				__proto__: Object
> 				somethingTestB: "Its Sara..!"
> 				__proto__: Object
> 				nodes: (5) [{…}, {…}, {…}, {…}, {…}]
> 				state: 1036
> 				root: {ngModule: NgModuleRef_, injector: NullInjector, projectableNodes: Array(0), selectorOrNode: "my-app", sanitizer: DomSanitizerImpl, …}
> 				renderer: DebugRenderer2 {delegate: EmulatedEncapsulationDomRenderer2, data: {…}, debugContextFactory: ƒ}
> 				oldValues: ["Its Sara..!"]
> 				disposables: [ƒ]
> 				initIndex: -1
> 				__proto__: Object
> 				viewContainer: ViewContainerRef_ {_view: {…}, _elDef: {…}, _data: {…}, _embeddedViews: Array(0)}
> 				template: undefined
> 				__proto__: Object
> 				_embeddedViews: []
> 				
> 				
> 				
> 				Not Working consol.log   
> 
> 
> 
> 					ViewContainerRef {_lContainer: LContainer(9), _hostTNode: TNode, _hostView: LComponentView_DynamicFormBuilderComponent(108)}
> 					element: (...)
> 					injector: (...)
> 					parentInjector: (...)
> 					length: (...)
> 					_lContainer: LContainer(9)
> 					lastIndex: (...)
> 					lastItem: (...)
> 					0: LComponentView_DynamicButtonBuilderComponent(57) [app-dynamic-button-panel, TView, 147, LComponentView_DynamicFormBuilderComponent(108), LContainer(9), null, TNode, null, DynamicButtonBuilderComponent, {…}, AnimationRendererFactory, BaseAnimationRenderer, null, LContainer(10), LContainer(10), LComponentView_DynamicFormBuilderComponent(108), LComponentView_DynamicButtonBuilderComponent(57), null, 0, div.button-panel-outer, div.row.justify-content-end.button-panel-row, LContainer(10), LContainer(10), LContainer(10), true, Array(1), true, 16412168, 0, 0, 0, 0, 0, 0, 0, 65634, NgIf, 16412168, 0, 0, 0, 0, 0, 0, 0, 65634, NgIf, 16412168, 0, 0, 0, 0, 0, 0, 0, 65634, NgIf, debug: LViewDebug]
> 					1: true
> 					2: -2
> 					3: LComponentView_DynamicFormBuilderComponent(108) [app-dynamic-form-builder, TView, 147, LComponentView_PortletBuilderComponent(67), null, null, TNode, LCleanup(12), DynamicFormBuilderComponent, {…}, AnimationRendererFactory, BaseAnimationRenderer, null, LContainer(9), LContainer(9), LComponentView_PortletBuilderComponent(67), LComponentView_DynamicFormBuilderComponent(108), null, 0, form#form_personal_details.form-horizontal.container.ng-untouched.ng-pristine.ng-valid.form-in-edit…, LContainer(9), LContainer(9), LContainer(32), KeyValuePipe, div.form-row, LContainer(9), FormGroup, "form-in-edit-mode", "form_personal_details", false, false, Array(23), Array(1), FormGroup, false, {…}, false, {…}, {…}, {…}, 7995912, 0, 0, 0, 0, 0, 0, 0, 65593, FormGroupDirective, NgClass, ɵNgNoValidate, NgControlStatusGroup, FormGroupDirective, true, true, false, false, true, true, false, false, true, true, false, false, false, false, 8023560, 0, 0, 0, 0, 0, 0, 0, 40, NgIf, 8023560, 0, 0, 0, 0, 0, 0, 0, 40, NgIf, 8023560, 0, 0, 0, 0, 0, 0, 0, 40, NgForOf, 8023560, 0, …]
> 					4: null
> 					5: null
> 					6: TNode {tView_: TView, type: 3, index: 25, injectorIndex: 98, directiveStart: 107, …}
> 					7: comment
> 					8: null
> 					length: 9
> 					debug: LContainerDebug {_raw_lContainer: LContainer(9)}
> 					__proto__: Array
> 					_hostTNode: TNode
> 					type_: (...)
> 					flags_: (...)
> 					template_: (...)
> 					styleBindings_: (...)
> 					classBindings_: (...)
> 					tView_: TView {type: 1, id: -1, blueprint: LViewBlueprint(108), queries: null, template: ƒ, …}
> 					type: 3
> 					index: 25
> 					injectorIndex: 98
> 					directiveStart: 107
> 					directiveEnd: 108
> 					directiveStylingLast: -1
> 					propertyBindings: null
> 					flags: 3
> 					providerIndexes: 107
> 					tagName: "app-dynamic-button-panel"
> 					attrs: (7) [3, "customButtons", "form", "isPublicPage", "pageDetails", "isLoading", "toggleFormMode"]
> 					mergedAttrs: (7) [3, "customButtons", "form", "isPublicPage", "pageDetails", "isLoading", "toggleFormMode"]
> 					localNames: null
> 					initialInputs: TNodeInitialInputs [null]
> 					inputs: {form: Array(2), customButtons: Array(2), pageDetails: Array(2), isPublicPage: Array(2), isLoading: Array(2)}
> 					outputs: {toggleFormMode: Array(2)}
> 					tViews: null
> 					next: null
> 					projectionNext: null
> 					child: null
> 					parent: TNode {tView_: TView, type: 3, index: 19, injectorIndex: 40, directiveStart: 50, …}
> 					projection: null
> 					styles: null
> 					residualStyles: undefined
> 					classes: null
> 					residualClasses: undefined
> 					classBindings: 0
> 					styleBindings: 0
> 					__proto__: Object
> 					_hostView: LComponentView_DynamicFormBuilderComponent(108)
> 					[0 … 99]
> 					[100 … 107]
> 					debug: LViewDebug {_raw_lView: LComponentView_DynamicFormBuilderComponent(108)}
> 					length: 108
> 					__proto__: Array
> 					__proto__: ViewContainerRef
> ```

Solution for This problem

https://stackoverflow.com/questions/60926745/how-to-access-parent-component-from-child-component-in-angular-9

**Comment by govindthakur25** [comment]
I am also facing a similar issue after upgrading to Angular 9 and enabling Ivy. I have created a directive that prevents the page scroll while someone opens a mat-select. 

Below is the minimal code to demonstrate the problem, somehow the exception is not being logged in the console in the stackblitz, but this will give enough idea about the actual code.
https://stackblitz.com/edit/angular-hcdvcq
For this, there is a directive 'SelectScrollLockDirective' which is applied on a mat-select inside app.component.html.

The exact code used to work in Angular 7, but seems to be broken in Angular 9. Below are the -screenshots from 7 and 9. I am attaching the browser snap while debugging on my local repo.

**Angular 7 - getting _data in the viewContainerref object. No logs in the browser console**
![angular-7](https://user-images.githubusercontent.com/29503955/79195557-17cac380-7e4c-11ea-8c62-cfc0e39446cc.png)

**Angular 9 - _data is missing from viewContainerRef object. No logs in the console because I am using the typescript safe navigation operator**
![angular-9](https://user-images.githubusercontent.com/29503955/79195698-58c2d800-7e4c-11ea-82db-27453ba1adb0.png)

Please note that I am using typescript's new safe navigation operator so that the browser doesn't log it in the console and everything seems to be working absolutely fine, but still, the missing _data may present any unknown issue in future, so I want to know the fix or an efficient workaround.

Please provide any pointers as to what needs to be changed in the code to access the componentView with Angular 9?

**Comment by mlc-mlapis** [comment]
@govindthakur25 It looks like using a private API:

`this.selectBox = (<any>(this.viewRef))._data.componentView.component;`

**Comment by govindthakur25** [comment]
@mlc-mlapis Yes, I get that. But which public API of ViewContainerRef will give me access to the componentView then? Can you help me with that?

**Comment by mlc-mlapis** [comment]
@govindthakur25 Maybe the first step should be to describe analytically, what you are trying to do.

**Comment by govindthakur25** [comment]
@mlc-mlapis I only want to avoid the page scrolling when mat-select is expanded. Basically, I wanted to lock the page scroll in order to avoid double scrolling and I had created a directive to achieve this. Maybe I need to change the implementation entirely.

**Comment by mlc-mlapis** [comment]
@govindthakur25 If keeping the directive in the game, I suppose that the first step inside it is to get the reference of its parent, right?

**Comment by govindthakur25** [comment]
@mlc-mlapis I got a cleaner approach to achieve it, which is working in Angular 9 as well.
https://stackoverflow.com/a/46893614/11403680

Thanks for your prompt replies anyway. I appreciate that. :)

**Comment by mlc-mlapis** [comment]
@govindthakur25 Ah, great. 👍
