### ISSUE TITLE
Why does the <router-outlet> component not cover 100% of the available height?

### ISSUE THREAD

**Issue by atef123456789** [angular/angular#36318]
I have the template below :

`<navbar></navbar>`
` //principalComponent`
`<router-outlet></router-outlet>`
`<footer></footer>`

I want  that  < router-outlet>  cover  the  available height   with a template  that cover  also the available height with a button at the bottom

I tried with a lot of the proposed solutions but nothing worked

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
