### ISSUE TITLE
ngcc - angular 9.1 - docker container ENOENT on /proc/...

### ISSUE THREAD

**Issue by vipex** [angular/angular#36313]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?
Yes, the previous version in which this bug was not present was: 9.0.*

### Description
ngcc compilation goes ENOENT on /proc file in container environment

## 🔬 Minimal Reproduction
In `node:lts` or `node:lts-alpine` container run the `ngcc` compiler ( also w/ `--async false`)

## 🔥 Exception or Error
<pre><code>
$ ngcc --async false
Error: ENOENT: no such file or directory, lstat '/proc/104/fd/19'
    at Object.lstatSync (fs.js:923:3)
    at NodeJSFileSystem.lstat (/ws/node_modules/@angular/compiler-cli/src/ngtsc/file_system/src/node_js_file_system.js:41:72)
    at CachedFileSystem.lstat (/ws/node_modules/@angular/compiler-cli/src/ngtsc/file_system/src/cached_file_system.js:131:38)
    at /ws/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/directory_walker_entry_point_finder.js:102:37
    at Array.filter (<anonymous>)
    at DirectoryWalkerEntryPointFinder.walkDirectoryForEntryPoints (/ws/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/directory_walker_entry_point_finder.js:101:18)
    at /ws/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/directory_walker_entry_point_finder.js:108:76
    at Array.forEach (<anonymous>)
    at DirectoryWalkerEntryPointFinder.walkDirectoryForEntryPoints (/ws/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/directory_walker_entry_point_finder.js:105:18)
    at /ws/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/directory_walker_entry_point_finder.js:108:76
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.0
Node: 12.16.1
OS: linux x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular/cdk                      9.2.0
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.2.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

If relevant, the underlying system is a MacOS Catalina v. 10.15.4 (19E266)

**Comment by akyrey** [comment]
+1

**Comment by zmira** [comment]
using `lts-alpine` and having the same issue

**Comment by petebacondarwin** [comment]
I think this may have the same root cause as #36283

**Comment by petebacondarwin** [comment]
Does it work with other versions of node.js?
Can you post your `paths` property of tsconfig.json?

**Comment by vipex** [comment]
> Does it work with other versions of node.js?
> Can you post your `paths` property of tsconfig.json?

Thanks to your question I've found the issue:

tsconfig configuration had `"rxjs": ["../../node_modules/rxjs"]` in paths,
 ( I don't recall adding it, but it's an old project)
removing it worked fine.

Now the issue remains, why outside container worked and inside not?

Anyway thanks @petebacondarwin for the help.

**Comment by zmira** [comment]
Angular version:
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.0
Node: 12.16.0
OS: linux x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular/cdk                      9.2.0
@angular/fire                     5.4.2
@angular/material                 9.2.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.42.0
```
tsconfig.json:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "src",
    "downlevelIteration": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "types": [
      "jest",
      "gapi",
      "gapi.auth2"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
        "@env/*": [
            "environments/*"
        ],
        "@core": [
            "app/core/index.ts"
        ],
        "@shared": [
            "app/shared/index.ts"
        ],
        "@styles/*": [
            "styles/*"
        ],
        "@uiTestUtils": [
          "../ui-tests/utils"
        ],
        "@uiTestPageObjects": [
          "../ui-tests/page-objects"
        ],
        "@library/auth-provider": [
          "../../library_folder/npm-packages/dist/ps-auth-provider"
        ],
        "@library/auth-provider/*": [
          "../../library_folder/npm-packages/dist/ps-auth-provider/*"
        ],
        "@library/nav-components": [
          "../../library_folder/npm-packages/dist/ps-nav-components"
        ],
        "@library/nav-components/*": [
          "../../library_folder/npm-packages/dist/ps-nav-components/*"
        ]
    }
  }
}
```
After reading @vipex's comment I looked closer at my `paths` definition and noticed all the `@library` entries were pointing to a non-existent path...
**Removed the bad paths, added back Ivy compilation and `postinstall` script, and everything worked as expected.**

**Comment by petebacondarwin** [comment]
@vipex - I am not sure what you mean by:

> Now the issue remains, why outside container worked and inside not?

**Comment by vipex** [comment]
The issue was happening only inside the container.  
Instead if I ran it on my host machine ( macOS for clarity ) it worked flawlessly.

**Comment by petebacondarwin** [comment]
The non-existing path caused ngcc to start traversing the file-system, looking for entry-points at the root `/`.
So I believe the answer to your question is that on your local machine your logged in user had access to all the files on the file-system, and so ngcc was able to traverse all the files without any errors - but perhaps within Docker the user had limited rights to read some files, and so when ngcc tried to traverse important OS files like `/proc/...` then it was disallowed access.

**Comment by vipex** [comment]
Thanks for the explanations, very appreciated.
