### ISSUE TITLE
Support TypeScript 3.9

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular#36320]
# 🚀 feature request

### Relevant Package

@angular/core

### Description

[TypeScript 3.9-beta](https://devblogs.microsoft.com/typescript/announcing-typescript-3-9-beta/) was released. It includes plenty of useful new features, like `// @ts-expect-error` and uncalled function checks in conditional expressions. . Angular should support it.

**Comment by mlc-mlapis** [comment]
@xiaoxiangmoe Support is only implemented on the base of the stable and production version. See the progress of the implementation phase for TS 3.7 or 3.8 for example.

**Comment by alxhub** [comment]
Hey @xiaoxiangmoe, glad you're as excited about upcoming TypeScript features as I am!

We'll support 3.9 when it has a stable release, don't worry.
