### ISSUE TITLE
display problem of date picker

### ISSUE THREAD

**Issue by liyang010813** [angular/angular#36321]
create a new angular project to test this bug, please repair.
![微信图片_20200330200113](https://user-images.githubusercontent.com/31497640/77910292-80009d80-72c1-11ea-8585-eac72c78ae72.png)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by liyang010813** [comment]
sorry
