### ISSUE TITLE
ERROR Error: The pipe 'myPipe' could not be found in JIT mode and This will become an error in v10. Please add @Injectable() to the "" class.

### ISSUE THREAD

**Issue by splincode** [angular/angular#36334]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core

### Description

@JoostK I studied your suggestions and decided to try differently. But now things like pipes stopped working

### AOT

```
$ git clone https://github.com/Angular-RU/autowired.git
$ cd autowired && yarn install
$ ng serve --aot=true
```

@JoostK This works great and feels, unfortunately, now we have to do explicit instructions for the decorator

```ts
@ServiceScan()
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  @Autowired() public app: AppService;
  @Autowired() public cd: ChangeDetectorRef;
}
```

Good work

![image](https://user-images.githubusercontent.com/12021443/77967138-2c0bae00-72ed-11ea-925f-8cf716626edf.png)

```
core.js:421 DEPRECATED: DI is instantiating a token "" that inherits its @Injectable decorator but does not provide one itself.
This will become an error in v10. Please add @Injectable() to the "" class.
```

![image](https://user-images.githubusercontent.com/12021443/77967268-768d2a80-72ed-11ea-8569-08561a8202c2.png)

`to the "" class.` it's a bug?

### JIT

But if I running JIT

```ts
$ ng serve --aot=false
```

![image](https://user-images.githubusercontent.com/12021443/77967348-9cb2ca80-72ed-11ea-89e6-0f3521bc697c.png)

But if I replace

```ts
 <h1>Welcome to {{ title | myPipe }}!</h1>
```

on

```ts
 <h1>Welcome to {{ title }}!</h1>
```

routerLink doesn't work after

![image](https://user-images.githubusercontent.com/12021443/77967441-cd92ff80-72ed-11ea-8452-c836c5063bce.png)

## 🌍  Your Environment

**Angular Version:**

Angular 9.1

**Comment by symphony2014** [comment]
I just found **moduleRef._bootstrapComponents[0].ɵcmp.pipeDefs**  was **null** , if I run with :** ng serve --aot=false**
Seems like the pipeDef was not being bind to metadata.
@splincode

**Comment by alxhub** [comment]
Yeah, it looks like something is interfering with the relationship between `AppComponent` and `AppModule`. I suspect the `@ServiceScan` decorator is changing the identity of `AppComponent`, so that the `@Component` decorator for `AppComponent` and the `@NgModule` decorator of the module that declares it don't see the same class type.

Unfortunately this is not an actionable issue for Angular, so I'm going to close this.
