### ISSUE TITLE
add more docs about OnPush mode

### ISSUE THREAD

**Issue by vthinkxie** [angular/angular#36345]
# 📚 Docs or angular.io bug report

### Description

There should be more detail about OnPush mode in the angular.io docs

## 🔬 Minimal Reproduction

no

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by ajitsinghkaler** [comment]
@vthinkxie you are talking about change detection right

**Comment by kapunahelewong** [comment]
Thanks for bringing this up, @vthinkxie. Could you elaborate on your thoughts about what we could add documentation on? I'd like to make sure that I move this in the correct direction.

**Comment by atscott** [comment]
This should be covered by #33731
