### ISSUE TITLE
[Bug] Unable to provide `useExisting` provider for Directive or Component

### ISSUE THREAD

**Issue by gund** [angular/angular#36350]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?

Nope, same error in Angular v8.

### Description

If I want to provide a component under another token that is also component
I would like to use provider `useExisting` from that component.

However when I will try to do so - Angular will throw an error:

```
TypeError: Cannot read property 'reference' of null
```

This is due to specific code that in case of a component provider - makes assumption that
provider is always of type `useClass`, which in this case makes it impossible to provide anything different:

https://github.com/angular/angular/blob/2510e7dad6d583d9fa76369e53b88cd0e52f17b3/packages/compiler/src/view_compiler/provider_compiler.ts#L98-L102

I'm not really sure why is such check required, maybe for performance optimizations?
Is there a way to remove such a limitation?

## 🔬 Minimal Reproduction
See repro [for v8](https://stackblitz.com/edit/angular-component-di-resolution?file=src%2Fapp%2Fapp.component.ts) and [for v9](https://stackblitz.com/edit/angular-component-di-resolution-ivy?file=src/app/app.component.ts).

## 🔥 Exception or Error
<pre><code>
TypeError: Cannot read property 'reference' of null
    at singleProviderDef (compiler.js:22619)
    at providerDef (compiler.js:22571)
    at ViewBuilder.push../node_modules/@angular/compiler/fesm5/compiler.js.ViewBuilder._visitProviderOrDirective (compiler.js:24102)
    at ViewBuilder.push../node_modules/@angular/compiler/fesm5/compiler.js.ViewBuilder._visitDirective (compiler.js:23997)
    at compiler.js:23922
    at Array.forEach (<anonymous>)
    at ViewBuilder.push../node_modules/@angular/compiler/fesm5/compiler.js.ViewBuilder._visitElementOrTemplate (compiler.js:23914)
    at ViewBuilder.push../node_modules/@angular/compiler/fesm5/compiler.js.ViewBuilder.visitElement (compiler.js:23834)
    at ElementAst.push../node_modules/@angular/compiler/fesm5/compiler.js.ElementAst.visit (compiler.js:11193)
    at visit (compiler.js:11372)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.1
Node: 12.3.1
OS: win32 x64

Angular: 9.0.1
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.1
@angular-devkit/build-angular      0.900.1
@angular-devkit/build-ng-packagr   0.900.1
@angular-devkit/build-optimizer    0.900.1
@angular-devkit/build-webpack      0.900.1
@angular-devkit/core               9.0.1
@angular-devkit/schematics         9.0.1
@angular/cdk                       9.1.0
@ngtools/webpack                   9.0.1
@schematics/angular                9.0.1
@schematics/update                 0.900.1
ng-packagr                         9.0.0
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Anything else relevant?**

**Comment by alxhub** [comment]
Well, this is super interesting!

My guess is that View Engine is looking at the `SelectControlValueAccessor` token and tagging the provider as some kind of internal component/directive provider. But I'm not really clear on the logic.

Honestly, I don't think this is likely to be fixed in View Engine as Ivy likely already works in this case. I recommend giving it a try!

**Comment by gund** [comment]
@alxhub you are right, when building locally repro with Ivy the error disappears!

The issue is that when I'm building components in storybook or running unit tests - angular is not using Ivy but old View Engine, which means that the code that uses this feature will break...

Do you know maybe there is a way to force Ivy engine in those environments/builders (`@nrwl/jest` and `@nrwl/storybook`)?

**Comment by Martinspire** [comment]
I'm getting this issue as well, but with Jest/Spectator and because a dependency module is needed in the entryComponents. Since the dependency isn't moving to Angular 9 any time soon, is there a possible workaround I can try?

**Comment by Totati** [comment]
I'm confused, cause I've wrote some similar code recently, and [it works fine](https://stackblitz.com/edit/angular-odi8wt).

**Comment by gund** [comment]
@Totati your example is not the same as the case reported here.

You are just using `useExisting` for token `NG_VALUE_ACCESSOR` - which works fine because it is not a component class but simple instance object of `InjectionToken`.

This bug is about the case when you want to provide `useExisting` for tokens that are another component classes.

**Comment by Totati** [comment]
@gund please check my `MAT_RADIO_GROUP_PROVIDER`.

**Comment by gund** [comment]
Hmm, you are right, your code should also trigger the same error...

The only difference is that you are providing alias for Directive while in my example I provide alias for Component, maybe that's why your example is not throwing...

**Comment by Martinspire** [comment]
> I'm confused, cause I've wrote some similar code recently, and [it works fine](https://stackblitz.com/edit/angular-odi8wt).

As far as I can see that isn't using an entryComponent. My issue is when an entire module is being mocked (with NG-Mock's "MockModule", the entryComponent breaks the compiler. While this is fixed in Angular 9+ (because entryComponent is no longer needed), this is still broken on Angular 8. Not everybody can use 9+ because dependencies don't work with Ivy yet

**Comment by JoostK** [comment]
Closing this issue as resolved in Ivy.
