### ISSUE TITLE
[bug] HttpHeaders.append reference issue

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#36351]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: no idea

### Description
let headers = new HttpHeaders() As this is an object it should have reference. I do not need to re-assign append value to headers.
This will not work.
```
 let httpHeaders = new HttpHeaders();
  httpHeaders.append('name', 'foo');
   httpHeaders.append('xname', 'baz')
```

This will work.
```
 let httpHeaders = new HttpHeaders();
    httpHeaders = httpHeaders.append('name', 'foo');
    httpHeaders = httpHeaders.append('xname', 'baz')
```

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-qyhsrg

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

  ng-8
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
This is working as intended and documented as such:

https://angular.io/api/common/http/HttpHeaders

> **append()**
> Appends a new value to the existing set of values for a header and returns them in a clone of the original instance.
>
> **Returns**
> HttpHeaders: A clone of the HTTP headers object with the value appended to the given header.
