### ISSUE TITLE
Null pointer exception in transition_animation_engine.ts

### ISSUE THREAD

**Issue by scriby** [angular/angular#36378]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/animations

### Is this a regression?

I'm not sure. If so, it has been around a while.

### Description

I have a component that is able to trigger a null pointer exception on https://github.com/angular/angular/blob/08348fc2e8b48d58a30063b0b5b03d21158a315b/packages/animations/browser/src/render/transition_animation_engine.ts#L376. It seems that the element state is not in the map!

The end result is that an element gets orphaned in the DOM when it is supposed to be removed using an *ngIf.

I hacked up the code to do a silent return if the element state is not present and the problem went away. However, I don't know if this is the proper fix.

## 🔬 Minimal Reproduction

Internal Google bug b/152896966 has repro steps (but note that it requires some kind of timing issue / race condition to repro)

## 🔥 Exception or Error

```
TypeError: Cannot read property 'animateMessageStatus' of undefined

angular2/rc/packages/animations/browser/src/render/transition_animation_engine.ts:376:28
```

See b/152896966#comment2 for more

## 🌍  Your Environment

**Angular Version:**

Whatever version google3 is currently on.

**Comment by sobos** [comment]
Please kindly fix again, [https://github.com/angular/angular/pull/19661/files](url)

**Comment by matsko** [comment]
@scriby we are aware of the issue and I have been investigating internally. Still not sure what's causing the combination of events that's leading to this issue. I've triaged this issue directly so we can address it in the coming weeks.

**Comment by AndrewKushnir** [comment]
Hi @scriby, the code that you refer to was updated recently (see 4ce44eac3389f2c36972b0d8ce341e59042a5fd6) and the error should not happen now. The fix was synced into Google's codebase a couple days ago. I'm closing this ticket for now, please reopen if the problem still exists. Thank you.
