### ISSUE TITLE
Better Error-Message (more specific location) for "No provider for TemplateRef! (NgIf ->TemplateRef)"

### ISSUE THREAD

**Issue by tobias74** [angular/angular#36387]
Angular Version 8

The error-message "No provider for TemplateRef! (NgIf ->TemplateRef)" does not really provide any information about where the error occurred. Debugging can get really messy at this point.

A more precise error-message would be helpful (for example: which template caused the error)

Thanks :-)
Tobias

**Comment by pkozlowski-opensource** [comment]
With Angular v9 running ivy we've got at least component name (ex. https://ng-run.com/edit/NX4cFaK5Eo4ByzMegvqN), but we don't point to the corresponding template file (and the column / row).

**Comment by atscott** [comment]
Closing as a duplicate of #25959. Though is a slight variation of the same issue, we can track them in a single one rather than having multiples that are slight variations of each other.
