### ISSUE TITLE
Memory leak in renderer2

### ISSUE THREAD

**Issue by aeb-sia** [angular/angular#36388]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?
No

### Description

Dynamically created elements are not cleaned up after destruction. This happens using the development server and also in production builds. 

If you try the demo and create a memory snapshot, click on the toggle a little and create a new snapshot, you'll see a number of detached divs, text elements, ... according to the number of clicks you performed

## 🔬 Minimal Reproduction
https://github.com/aeb-sia/rendererleak

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.0
Node: 10.15.3
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Comment by pkozlowski-opensource** [comment]
> If you try the demo and create a memory snapshot, click on the toggle a little and create a new snapshot, you'll see a number of detached divs, text elements,

Out of curiosity - did you try to check, based on the memory snapshot, what retains the elements in question? In other words, what is pointing in the direction of Angular retaining those references?

**Comment by aeb-sia** [comment]
I didn't inspect it further. I spend significant time last year debugging memory leaks in our applications and found one that was our own fault. The other one was this rendere2 leak. I actually commented on a previous issue https://github.com/angular/angular/issues/26954 that was closed with "ivy will fix that"

Now I came back to it, because we started rolling out angular9 internally so I revisited the issue.

My demo is pretty minimal and I honestly don't know what else could be retaining those references...

**Comment by JiaLiPassion** [comment]
@aeb-sia, if you removed all the `console.log`, the `detached` div/html element will gone, all those objects are retained by console, can you also try it?

**Comment by aeb-sia** [comment]
Yeah, that removes most of them. Didn't think console.log would keep references... 

It doesn't remove all though. 
![image](https://user-images.githubusercontent.com/50743092/78260383-32bd3f80-74fe-11ea-8f8d-2ab08905fb46.png)

**Comment by JiaLiPassion** [comment]
@aeb-sia , you mean not all of those elements are removed? I tested your repo, all were removed.

**Comment by aeb-sia** [comment]
Yes. I updated the repo with the changes I did. To test I ran 
`ng build --prod` and served it with http-server
I ran the tests in Edge Version 81.0.416.34 (Official build) beta (64-bit)

**Comment by JiaLiPassion** [comment]
@aeb-sia , I didn't test on Edge, but it may related to the chrome dev tools, so could you
1. open the app, do not open chrome dev tools.
2. click toggle several times.
3. open chrome dev tool to take a snapshot

There should not any detached elements there.

**Comment by aeb-sia** [comment]
I still had them, but this time investigated myself. Turns out an extension was holding the remaining references. Sorry for the noise...
