### ISSUE TITLE
routerLink broken inside FireWire guarded route

### ISSUE THREAD

**Issue by waterplea** [angular/angular#36389]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/fire

### Is this a regression?

 Not sure, it's the first time I used Firewire

### Description

When I use `routerLink` inside a Firewire guarded route and click it I get a warning in console:
`Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?`

Also current route is not removed and new route is added broken (looks like change detection has not kicked in) - I have both routes right under `router-outlet`,

## 🔬 Minimal Reproduction

 Not sure how to provide a reproduction since it requires boilerplate, auth token etc. Here's what I have, it's pretty basic:

I have 4 routes: landing, login page, main logged in page and a "play" route. And app component which is just `router-outlet`. They are configured like that:

```
const routes: Routes = [
    {
        path: 'welcome',
        loadChildren: () =>
            import('./components/landing/landing.module').then(m => m.LandingModule),
    },
    {
        path: 'login',
        loadChildren: () =>
            import('./components/auth/auth.module').then(m => m.AuthModule),
        canActivate: [AngularFireAuthGuard],
        data: {authGuardPipe: () => redirectLoggedInTo([''])},
    },
    {
        path: 'play',
        loadChildren: () =>
            import('./components/play/play.module').then(m => m.PlayModule),
        canActivate: [AngularFireAuthGuard],
        data: {authGuardPipe: () => redirectUnauthorizedTo(['welcome'])},
    },
    {
        path: '',
        component: MainComponent,
        canActivate: [AngularFireAuthGuard],
        data: {authGuardPipe: () => redirectUnauthorizedTo(['welcome'])},
    },
];
```
All I have in main component from empty path is this:
```
<a routerLink="/play">
    Play
</a>
```
If I remove this part from this route configuration, it starts working properly:
```
        canActivate: [AngularFireAuthGuard],
        data: {authGuardPipe: () => redirectUnauthorizedTo(['welcome'])},
```

## 🔥 Exception or Error
<pre><code>
Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
9.1.0
@angular/fire - 6.0.0-rc.1
firebase - 7.8.0
</code></pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment]
Could you please open in https://github.com/angular/angularfire for the initial investigation? Thnx!

**Comment by waterplea** [comment]
Thank you. Look a lot like this: https://github.com/angular/angularfire/issues/2355
