### ISSUE TITLE
[global] white list web components selector for every module

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#36398]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [X] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
 I am using this web components in my project https://www.npmjs.com/package/ionicons, Now i get this error
```
  1. If 'ion-icon' is an Angular component, then verify that it is part of this module.
    2. If 'ion-icon' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress
this message.
```
Now in every module i am adding this CUSTOM_ELEMENTS_SCHEMA

### Describe the solution you'd like

Can we have global wise whitelist selector to act as an angular component.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by pkozlowski-opensource** [comment]
Related to #12045

**Comment by JoostK** [comment]
We do recognise this as a potential area for improvement; this will be considered in the design of #12045.
