### ISSUE TITLE
publish modules/* and tools/* to npm

### ISSUE THREAD

**Issue by tbosch** [angular/angular#364]
Open questions:

1. In which language do we want to publish? AtScript, ES6, ES5?
    a. if ES5: which module system to use? For some modules we need multiple ones (e.g. `modules/di` should be usable in node.js and in the browser)

**Comment by cironunes** [comment]
+1 to ES6 :smile:

**Comment by nesukun** [comment]
ES6 +1

**Comment by naomiblack** [comment]
Doc for tracking the plan for packaging and releasing: https://docs.google.com/document/d/15IlXYv01BDkJVtblKff_iHikNRksgwdjsPbFIvqOI9o/edit#heading=h.3juzvhnpfkil

**Comment by tbosch** [comment]
Modules are done.

Benchpress will be rewritten in AtScript and then be part of the `modules` folder, see https://github.com/angular/angular/pull/488

The transpiler will not be published for now...

**Comment by djindjic** [comment]
is https://github.com/angular/di.js active again?

**Comment by tbosch** [comment]
No, the current implementation of `di` lives in `github.com/angular/modules/di`.

For now we publish all modules except for `rtts_assert` and `benchpress` as subfolders under `angular2` (not yet on npm but today or tomorrow).

**Comment by cironunes** [comment]
@tbosch you mean [github.com/angular/angular/modules/angular2/di.js](https://github.com/angular/angular/blob/master/modules/angular2/di.js), right?

**Comment by djindjic** [comment]
sorry, I haven't understood where is di published? can I install only di with npm install? what is the package name?

**Comment by pkozlowski-opensource** [comment]
@djindjic AFAIK you can't install DI individually at this point, but you can get it as part of the `angular2` module.
