### ISSUE TITLE
filename convention in the repo: '-' or '_' ?

### ISSUE THREAD

**Issue by tailgo** [angular/angular#36406]
I find some file in this repo named using '-', like `angular/packages/bazel/src/ng_package/collect-type-definitions.bzl`, and in the same folder I find another style using '_', like `angular/packages/bazel/src/ng_package/ng_package.bzl`.

I think those Naming conventions should be unified, right ?

**Comment by BohdanChernivtsi** [comment]
Angular packages are followed with '_', like ng_package, it's angular convention
Other could be followed with '-', even if they are under angular package

**Comment by IgorMinar** [comment]
When it comes to public API surface our conventions are clear:

- we use `-` as the file name separator for all **public** JavaScript/TypeScript paths and filenames
- we use `_` for all the **public** bazel symbols (rules) and paths

In the source code of our packages we however mix up the two and I agree that we should fix that.

**Comment by tailgo** [comment]
> When it comes to public API surface our conventions are clear:
> 
> * we use `-` as the file name separator for all **public** JavaScript/TypeScript paths and filenames
> * we use `_` for all the **public** bazel symbols (rules) and paths
> 
> In the source code of our packages (**private** paths, filenames) we however mix up the two and I agree that we should fix that.

Thanks. And I want to know that which one convention would be chosen.

**Comment by atscott** [comment]
Closing. This isn't something we'll invest time in.
