### ISSUE TITLE
add Promise<T> | Observable<T> async pipe overload

### ISSUE THREAD

**Issue by Toxicable** [angular/angular#36404]
# 🚀 feature request

### Relevant Package
`@angular/common`

### Description
Currently the async pipe can take a Promise or Observable, but only as seperate obverloads, so with `strictTemplates` you get an error if you pass in a `Promise<T> | Observable<T>`

### Describe the solution you'd like
Add an overload which looks like `transform<T>(obj: Promise<T> | Observable<T> | null | undefined): T | null;`

### Describe alternatives you've considered
converting the promise into a observable, but this isn't ergonomic

Happy to submit a patch

**Comment by JoostK** [comment]
Go for it!

I like how you put a rocket in the issue. I know it's there by default, but still! 🚀

**Comment by JoostK** [comment]
This was done in #37447, so closing.
