### ISSUE TITLE
Service-worker and Firebase request with ngsw-bypass in header

### ISSUE THREAD

**Issue by msegmx** [angular/angular#36403]
When I make a GET request to 

    https://firestore.googleapis.com/v1/projects/....

the service-worker intercepts the request and serves the latest response from cache, if available. So far so good.

I have a "force-refresh" button on the page. When clicked, I want the service-worker to ignore the request and let the browser do its job. It works fine, the parameter gets added to the request header :

    access-control-request-headers: ngsw-bypass

This parameter can be set as a request header or a request parameter in url.

Problem is, firebase complains about the extra parameter, set as request header or parameter, doesn't matter. 

    {
      "error": {
        "code": 400,
        "message": "Invalid JSON payload received. Unknown name \"ngsw-bypass\": Cannot bind query parameter. Field 'ngsw-bypass' could not be found in request message.",
        "status": "INVALID_ARGUMENT",
        "details": [
          {
            "@type": "type.googleapis.com/google.rpc.BadRequest",
            "fieldViolations": [
              {
                "description": "Invalid JSON payload received. Unknown name \"ngsw-bypass\": Cannot bind query parameter. Field 'ngsw-bypass' could not be found in request message."
              }
            ]
          }
        ]
      }
    }

How can this be solved?

**Comment by gkalpak** [comment]
I'm afraid this sounds like a Firebase issue. It sounds weird to return an `Invalid JSON payload` error due to a header.

Are you making a direct request to `https://firestore.googleapis.com/v1/projects/...`?

**Comment by msegmx** [comment]
Yes, as described here : [https://firebase.google.com/docs/firestore/reference/rest](https://firebase.google.com/docs/firestore/reference/rest)

I'm looking into using IndexedDb as an alternative. But what if, Firestore or any other endpoint, has strict rules, wouldn't that mean that the service-worker should remove said parameter before passing the request to the browser?

**Comment by gkalpak** [comment]
Unfortunately, the SW can't mutate the request, unless it decides to handle it (even if it just means passing it through to the network with `self.fetch(req)`).

The purpose of `ngsw-bypass` is that the SW will not handle the request at all. So, I am afraid there is not much we can do here.

##
As a work-around, you can always use your own ServiceWorker script that checks all requests and stops the propagation of those you want to go through to the server and then let the rest fall back to the default Angular ServiceWorker:

```js
// my-sw.js
const myListOfIgnoredUrls = [ ... ];

self.addEventListener('fetch', evt => {
  if (myListOfIgnoredUrls.includes(evt.request.url)) {
    evt.stopImmediatePropagation();
  } else {
    // Let the request fall through to the Angular SW...
  }
});

importScripts('./ngsw-worker.js');
```

**Comment by msegmx** [comment]
Thanks for the workaround!
