### ISSUE TITLE
Configurable module creation with IVY and AOT on

### ISSUE THREAD

**Issue by vdshb** [angular/angular#36415]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?
No

### Description
I want to create configurable Angular 9 module with IVY and AOT on.
In the simplest scenario it must provide a single stateful service configurable by name:
```typescript
@Injectable()
export class CounterService {
  private counter = 0;
  shot() {
    return this.counter++;
  }
}

@NgModule()
export class CounterModule {
  static withConfig(name: string): ModuleWithProviders {
    return {
      ngModule: CounterModule,
      providers: [{
        provide: name,
        useClass: CounterService
      }]
    };
  }
}
```
Everything works fine at this point. But if I want to add any logic into `CounterModule.withConfig`:
```typescript
@NgModule()
export class CounterModule {
  static withConfig(name?: string): ModuleWithProviders {
    const counterProviderToken = name ? name : CounterService;
    return {
      ngModule: CounterModule,
      providers: [{
        provide: counterProviderToken,
        useClass: CounterService
      }]
    };
  }
}
```
I'm getting a compilation error NG1010.

## 🔬 Minimal Reproduction
https://github.com/vdshb/ng-modules-problem

Please, check out the last commit. It adds code to get compilation exception.

## 🔥 Exception or Error
<pre><code>
error NG1010: Value at position 1 in the NgModule.imports of AppModule is not a reference: [object Object]
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.1.0
Node: 13.12.0
OS: linux x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
I'm not sure if it's a bug or we have any other ways to make a configurable module. 

It might be related to this ticket: https://github.com/angular/angular/issues/36243 but the cases are different.

Everithyng works fine with option `projects.ng-modules-shots.architect.build.options.aot=false` set in angular.json

**Comment by JoostK** [comment]
There's currently a constraint that there's only a single statement in the function. So if you restructure your code to this effect, it will work.

```ts
@NgModule()
export class CounterModule {
  static withConfig(name?: string): ModuleWithProviders {
    return {
      ngModule: CounterModule,
      providers: [{
        provide: name ? name : CounterService;,
        useClass: CounterService
      }]
    };
  }
}
```

**Comment by vdshb** [comment]
Ok, knowing this constraint I've managed a module with multiple configuration arguments to work. 
It looks filthy and not the way I wanted, but it works.

**Comment by JoostK** [comment]
@vdshb You can pull out the organization of providers into a function, if you wish:

```ts
@NgModule()
export class CounterModule {
  static withConfig(name?: string): ModuleWithProviders {
    return {
      ngModule: CounterModule,
      providers: createProviders(name),
    };
  }
}

function createProviders(name?: string): Provider[] {
    const counterProviderToken = name ? name : CounterService;
    return [{
      provide: counterProviderToken,
      useClass: CounterService
    }];
  }
```

**Comment by vdshb** [comment]
Thanks a lot! Module looks way better now.

**Comment by JoostK** [comment]
Actually I will reopen this as I think this is rather arbitrary. At least the error message should be improved.

**Comment by vdshb** [comment]
Great. Maybe this constraint is not so necessary any more...

**Comment by alxhub** [comment]
I have some good news, @vdshb! #37126 will relax the single-statement restriction and allow you to write your `forRoot` functions however your heart desires :)

**Comment by AlexAegis** [comment]
Hey @alxhub! Thank your for your efforts regarding this. I have a question regarding  "however your heart desires", will this enable me to configure a module using a builder? Potentionally by extending the ModuleWithProviders, so I can leave the trailing `.build()` off.

Example:

```ts
export class ConfigurationBuilder implements ModuleWithProviders<FooModule> {
	ngModule = FooModule;

	constructor(public providers: Provider[] = []) {}

	withConfig(provider: Partial<Provider>): ConfigurationBuilder {
		this.providers.push({
			...provider,
			provide: FooModuleConfigurationService,
			multi: true,
		});
		return this;
	}
}

```

Then my `forRoot` method would just return a new instance of this.

**Comment by JoostK** [comment]
@AlexAegis nope, that is not supported. If a function call appears in `imports`, the call will be statically analyzed. If there's a single statement that returns a value, that value will be statically analyzed. If there's multiple statements or the return value was dynamic, there's a fallback on the function's return type; if it's `ModuleWithProviders<X>`, then `X` will be used as NgModule class. If there's no such return type, an error will be reported. 

In your example, it is unclear how you are planning on referring to the `ConfigurationBuilder` from within `NgModule.imports`. If you're planning on having `ConfigurationBuilder.withConfig` appear in `NgModule.imports`, you'll see how it doesn't follow the above rules, as the return type is not `ModuleWithProviders<FooModule>`. If instead the idea was to import just a value of type `ConfigurationBuilder` , it would also not work as both the class's `ngModule` field nor its inheritance clause would be considered by the static analyzer.

**Comment by JoostK** [comment]
Closing as #37126 has just been merged.

For anyone still seeing this issue with Ivy: make sure an explicit return type of `ModuleWithProviders<FooModule>` is present, where `FooModule` is the class name of the desired NgModule.

**Comment by AlexAegis** [comment]
@JoostK Thank you for the explanation. Another idea was to have the regular kind of forRoot, with only the ModuleWithProviders object returned, with the extra withConfig method on that. With the correct return type.

```ts
forRoot(): ModuleWithProviders<FooModule> {
  return {
    ngModule: FooModule,
    providers: [],
    withConfig(provider: Provider): ModuleWithProviders<FooModule> {
		this.providers.push(provider);
		return this;
	}
  }
}
```

Would this make more sense for the static analyser? By your description it should as the return types are correct.

**Comment by JoostK** [comment]
@AlexAegis yes, and no. The `forRoot` method now has the expected signature, so you're good from that perspective. However, the declared return type now restricts users from calling `withConfig`, as the return type from `forRoot` does not declare that property (you'd even get a TS error on that code as `withConfig` is not allowed in an object literal of inferred type `ModuleWithProviders`).

Also, the providers array is left empty, while you collect things into `this.providers`. The `providers` property in `ModuleWithProviders` is materialized into the injector when instantiating the NgModule, so at that moment in time would the array be read (which is now always empty). You could bind `this.providers` to `providers`, however that isn't really transparent as it does not restrict registering new providers after an NgModule has already been instantiated. That won't magically extend the existing injector with the new provider, so it may be misleading.
