### ISSUE TITLE
Form control not found in a component  while form group was created using Form builder.

### ISSUE THREAD

**Issue by ShahzaibSE** [angular/angular#36429]
Hello Everyone,

> Error: **Property 'firstname' does not exist on type 'SignupComponentComponent'.**

Here is SignupComponent class code:

<img width="774" alt="Screenshot 2020-04-04 at 9 29 30 PM" src="https://user-images.githubusercontent.com/12384815/78456247-f8010600-76bb-11ea-812b-24fc2afaaa8f.png">

and here is my template, I am trying to validate a form field using Reactive Forms **errors** class but I am getting mentioned error message.

<img width="876" alt="Screenshot 2020-04-04 at 9 30 05 PM" src="https://user-images.githubusercontent.com/12384815/78456333-75c51180-76bc-11ea-8f90-0e366336bdde.png">

Error message:

<img width="1035" alt="Screenshot 2020-04-04 at 9 29 16 PM" src="https://user-images.githubusercontent.com/12384815/78456341-7e1d4c80-76bc-11ea-8824-5de7665e3dc5.png">

Any help is appreciated.

Thank you,
Shahzaib Noor

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
