### ISSUE TITLE
Angular 2.0 alpha 34 form error

### ISSUE THREAD

**Issue by hitmanmcc** [angular/angular#3642]
Hello guys,

Have there been any breaking change in forms from alpha 33 to alpha 34? My forms stopped working when I upgraded and I got this error when I tried navigating to a page with one of the forms.

```javascript
EXCEPTION: TypeError: Cannot read property 'addEventListener' of undefined
angular2.dev.js:22448 STACKTRACE:
angular2.dev.js:22448 TypeError: Cannot read property 'addEventListener' of undefined
    at BrowserDomAdapter.execute.BrowserDomAdapter.on (angular2.dev.js:22475)
    at angular2.dev.js:16762
    at Zone.run (angular2.dev.js:136)
    at NgZone.execute.NgZone.runOutsideAngular (angular2.dev.js:16410)
    at DomEventsPlugin.execute.DomEventsPlugin.addEventListener (angular2.dev.js:16761)
    at EventManager.execute.EventManager.addEventListener (angular2.dev.js:16710)
    at $__0.execute.DomRenderer._createEventListener (angular2.dev.js:25960)
    at $__0.execute.DomRenderer._createView (angular2.dev.js:25951)
    at $__0.execute.DomRenderer.createView (angular2.dev.js:25801)
    at execute.AppViewManager._createPooledView (angular2.dev.js:27591)
```
I have plunkr examples for both alpha 33 and 34, so you can check that in alpha 33 it works and in alpha 34 it does not, which you can verify by checking the console's log:

<b>Angular Alpha 33 version:</b>
http://plnkr.co/edit/4Ic3gj74LXrSRj55GfzI

<b>Angular Alpha 34 version:</b>
http://plnkr.co/edit/PWFNAIVF4BuVafTlwpuw

I would appreciate any help you guys can dispense with this.

Best regards,
André

**Comment by GoossensMichael** [comment]
The problem lies in this piece of code:

            for (var binderIdx = 0; <b>binderIdx < binders.length</b>; binderIdx++) {
              var binder = binders[<b>binderIdx</b>];
              var element = boundElements[<b>binderIdx</b>];
              if (binder.hasNativeShadowRoot) {
                var shadowRootWrapper = DOM.firstChild(element);
                var shadowRoot = DOM.createShadowRoot(element);
                this._domSharedStylesHost.addHost(shadowRoot);
                moveChildNodes(shadowRootWrapper, shadowRoot);
                DOM.remove(shadowRootWrapper);
              }
              if (isPresent(binder.eventLocals) && isPresent(binder.localEvents)) {
                for (var i = 0; i < binder.localEvents.length; i++) {
                  this._createEventListener(view, element, binderIdx, binder.localEvents[i].name, binder.eventLocals);
                }
              }
            }

As you can see the binders.length is used as stop condition for the loop. But the index tested in the condition is not only used on the binders array but also on the boundElements array. In your case (on plunker) I can see that the amount of array elements of binder is 12 while the boundElements array is only 11 long. So when the 12th element of the boundElements array is requested it just gives 'undefined' this causes a problem later on when the function addListener is called on <b>'undefined'</b>.

I,m fairly new to Angular 2 so I don't know what the fix is yet. Should another index be used? Or should an extra condition be applied to stop the logic sooner? Or maybe it shouldn't possible at all to  have a different amount of items in the two arrays. Will try to look further into this to learn some more of the insides of angular 2 :-).

**Comment by hitmanmcc** [comment]
Thank you very much @GoossensMichael, I really appreciate the time and effort you put into this and the very thorough explanation of what goes on throughout Angular's DOM generation process in this case. It was very thoughtful of you to take the time to help a fellow programmer that is less well versed in the world of web development. :)

**Comment by GoossensMichael** [comment]
No problem. I just started learning javascript and angular 1 a month ago so I don't think we are on a different level of experience ;-).

**Comment by mhevery** [comment]
Is this still an issue for Angular or should this be closed?

**Comment by hitmanmcc** [comment]
@mhevery As I'm told that the HTML spec does not support nested forms, I see no reason why Angular would have to offer that support. In light of that circumstance, I believe that there isn't anything else for you guys to do, regarding this subject matter.

**Comment by GoossensMichael** [comment]
Well actually it would be better that angular 2 is a bit more defensive in its code. At least an exception should be thrown when the amount of bindings is not the same as the boundElements. This causes confusion for developers and is quite hard to find the cause, in this case it was innerHTML that fixed faulty HTML, causing angular to go further with wrong assumptions and eventually having a nullpointer.

**Comment by hitmanmcc** [comment]
:+1: I totally agree with that @GoossensMichael, it is indeed something that is likely to lead developers down a confusing path if there is no exception thrown. Excellent point. :)

**Comment by GoossensMichael** [comment]
Any documentation on how exception handling is to be done on angular 2? Maybe I can add it as my first contribution :).

**Comment by mhevery** [comment]
@GoossensMichael There is a central `ExceptionHandler` which receives all of the exceptions. So we are either not throwing the right error, or not catching it.
