### ISSUE TITLE
IVY Error NG6002: Appears in the NgModule.imports of AppModule

### ISSUE THREAD

**Issue by maxisam** [angular/angular#36424]
# 🐞 bug report

### Affected Package

ngcc

### Is this a regression?

Yes, it works at 9.0.0

### Description

It actually works in the end. I think it is caused by the order of the ngcc compilation. 

The problem is like when I have a package A using another package B. During ngcc compilation, somehow package A runs before package B.

And it throws an error. However, once package B got compiled, it will compile package A again and it will work.

And the build will work as well. 

I think it is a bug that it compiles out of order. It should compiles base on the dependency list. 

The good thing is it actually fixes itself in the end.

## 🔬 Minimal Reproduction

I can't reproduce in a small example yet. 

## 🔥 Exception or Error
<pre><code>
Compiling @m*****b/ngm-image-gallery : es2015 as esm2015
**Compiling @m*****b/ngm-image-gallery : es2015 as esm2015**
Error: Failed to compile entry-point @m*****b/ngm-image-gallery (es2015 as esm2015) due to compilation errors:
node_modules/@m*****b/ng-helper/components/confirm-button/confirm-button.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of NgmImageGalleryModule, but could not be resolved to an NgModule class.

This likely means that the library (@m*****b/ng-helper/components/confirm-button) which declares NgmConfirmButtonModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

1 export declare class NgmConfirmButtonModule {
                       ~~~~~~~~~~~~~~~~~~~~~~

Error: Failed to compile entry-point @m*****b/ngm-image-gallery (es2015 as esm2015) due to compilation errors:
node_modules/@m*****b/ng-helper/components/confirm-button/confirm-button.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of NgmImageGalleryModule, but could not be resolved to an NgModule class.

This likely means that the library (@m*****b/ng-helper/components/confirm-button) which declares NgmConfirmButtonModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**1 export declare class NgmConfirmButtonModule {**
                       ~~~~~~~~~~~~~~~~~~~~~~

0% compiling
Compiling @m*****b/ng-helper/components/millers-logo : es2015 as esm2015

**Compiling @m*****b/ng-helper/components/confirm-button : es2015 as esm2015**

**Compiling @m*****b/ngm-image-gallery : es2015 as esm2015**

Compiling @m*****b/ng-helper/components/alert-dialog : es2015 as esm2015

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.0
Node: 10.16.0
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.0
@angular-devkit/build-angular      0.901.0
@angular-devkit/build-ng-packagr   0.901.0
@angular-devkit/build-optimizer    0.901.0
@angular-devkit/build-webpack      0.901.0
@angular-devkit/core               9.1.0
@angular-devkit/schematics         9.1.0
@angular-devkit/schematics-cli     0.901.0
@angular/cdk                       9.2.0
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.2.0
@ngtools/webpack                   9.1.0
@schematics/angular                9.1.0
@schematics/schematics             0.901.0
@schematics/update                 0.901.0
ng-packagr                         9.1.0
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
This might be fixed by https://github.com/angular/angular/pull/36305 but it is impossible to know without more information about the structure and content of your packages.

Are any of the directories in `node_modules/@m*****b/ng-helper/components/confirm-button` (e.g `ng-helper/components`) not entry-points? I.E. there is no package.json there?

**Comment by maxisam** [comment]
@petebacondarwin  yes, you are correct. There is no `package.json` in node_modules/@m*****b/ng-helper/components/confirm-button

I think the problem is like ngcc does run "@m*****b/ng-helper" first. However, there are more than one entry-point.

**Comment by maxisam** [comment]
@petebacondarwin  I think it is exactly like what  #36305 is trying to fix. I will test 9.1.1 when it is out. Thanks!

**Comment by maxisam** [comment]
duplicated with #36216
