### ISSUE TITLE
Cannot use the service worker in AWS CloudFront with PathLocationStrategy

### ISSUE THREAD

**Issue by stefan-karlsson** [angular/angular#36439]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/service-worker

### Is this a regression?

 No, been a issue since release of the service-worker

### Description
The [documentation ](https://angular.io/guide/service-worker-devops#fail-safe) says

> To deactivate the service worker, remove or rename the ngsw.json file. When the service worker's request for ngsw.json **returns a 404**, then the service worker removes all of its caches and de-registers itself, essentially self-destructing.

The problem with this approach is that when running a CDN environments such as CloudFront where the 404 has to be redirected to 200 index.html to support the PathLocationStrategy.

![image](https://user-images.githubusercontent.com/25538602/78503863-8d0e0880-7769-11ea-97bc-6f3e5928fb77.png)

The client will never receive a http status code of 404 instead it will get a status code of 200 with the content type `text/html` instead of `application/json`. 
this leads to that the service-worker is not self-destructing.

I found a [old issue that address this problem](https://github.com/angular/angular/issues/24827)  but it has been closed due to inactivity.

There is also a [closed pull request](https://github.com/angular/angular/pull/25682)

## 🔥 Exception or Error
<pre><code>
NGSW Debug Info:

Driver state: EXISTING_CLIENTS_ONLY (Degraded due to failed initialization: Unexpected token < in JSON at position 0
SyntaxError: Unexpected token < in JSON at position 0)
Latest manifest hash: f4a29fe48fc6ded96da1161f83d19f6cca8bdbfb
Last update check: 16s186u

=== Version f4a29fe48fc6ded96da1161f83d19f6cca8bdbfb ===

Clients: 

=== Idle Task Queue ===
Last update tick: 21s597u
Last update run: 16s596u
Task queue:

Debug log:

[16s181u] SyntaxError(Unexpected token < in JSON at position 0, SyntaxError: Unexpected token < in JSON at position 0) Error occurred while updating to manifest (unknown)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.5
Node: 12.16.0
OS: win32 x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.23
@angular-devkit/build-angular              0.900.5
@angular-devkit/build-ng-packagr           0.900.5
@angular-devkit/build-optimizer            0.900.5
@angular-devkit/build-webpack              0.900.5
@angular-devkit/core                       9.0.5
@angular-devkit/schematics                 8.3.23
@angular/cdk                               9.1.2
@ngtools/webpack                           9.0.5
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.3.23
@schematics/update                         0.900.5
ng-packagr                                 9.0.3
rxjs                                       6.5.4
typescript                                 3.7.5
webpack                                    4.41.2
</code></pre>

**Comment by gkalpak** [comment]
As explained on [the closed PR][1] and [the closed issue][2], there is not much we can do (without breaking more common usecases) and there are other ways to unregister the SW (if you can't rely on `ngsw.json` 404-ing).

I am going to close this, since I don't see what action could be taken (for the reasons mentioned in #24827 and #25682). Feel free to continue the discussion below (e.g. if you have new ideas of how this could be handled better by the SW).

[1]: https://github.com/angular/angular/pull/25682#discussion_r213096921
[2]: https://github.com/angular/angular/issues/24827#issuecomment-415418100
