### ISSUE TITLE
Detect attributes used in deps for providers

### ISSUE THREAD

**Issue by waterplea** [angular/angular#36433]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/language-service

### Description
When you use `@Attribute` decorator in constructor language service detects it and provides code complete in IDE. It does not provide code complete and warnings are shown for unknown attributes by IDE if it is only used in `deps` in `providers` like I have here:
https://github.com/ng-web-apis/intersection-observer/blob/master/projects/intersection-observer/src/directives/intersection-observer.ts
however code works.

### Describe the solution you'd like
 It would be great if Angular Language Service picked those up.

### Describe alternatives you've considered
 Adding them to constructor for no reason other than code completion

**Comment by ayazhafiz** [comment]
Hi, thanks for the report. Looks like your link is broken or inaccessible -- could you provide another link or a code snippet?

**Comment by JoostK** [comment]
@ayazhafiz It's this file, this time with a hard ref to the current HEAD commit id:

https://github.com/ng-web-apis/intersection-observer/blob/0cd9b770ed0df0610075ddf6d385961dea241a77/projects/intersection-observer/src/directives/intersection-observer.directive.ts

**Comment by ayazhafiz** [comment]
thanks @JoostK  👍

**Comment by waterplea** [comment]
Hey, it looks like attribute in deps even got broken with Ivy! Created a bug with working Angular 8 and broken Angular 9 examples:
https://github.com/angular/angular/issues/36479

**Comment by waterplea** [comment]
This one is probably extremely convoluted to implement and nobody needs it but me :) There's also a fairly easy workaround so I'm closing this one.

**Comment by petebacondarwin** [comment]
Thanks @waterplea for tidying these issues up.
