### ISSUE TITLE
Angular Material Not working after update(relese 9.0.5)  on 4-4-2020 

### ISSUE THREAD

**Issue by 4-TREX** [angular/angular#36435]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by 4-TREX** [comment]
![Screenshot from 2020-04-05 14-47-53](https://user-images.githubusercontent.com/46960905/78471217-427e9300-774d-11ea-8133-f7891f76919b.png)
![Screenshot from 2020-04-05 14-49-24](https://user-images.githubusercontent.com/46960905/78471218-43afc000-774d-11ea-8183-e58cd91ade85.png)

**Comment by 4-TREX** [comment]
Nothing from angular material working.

**Comment by petebacondarwin** [comment]
Please run `ng version` to provide us with all the versions of the software you are using. Especially the version of Material and CDK. Also please provide any messages from the CLI during build and also any messages in the browser console.

**Comment by 4-TREX** [comment]
I am sharing all the required screenshots.The issue is Angular Material Designs are not working as in the style is not reflecting to angular material button component. I have added the angular material  button component api  in the app.module.ts file.
Screenshot Below -

![Screenshot from 2020-04-05 19-30-24](https://user-images.githubusercontent.com/46960905/78500469-32c67500-7774-11ea-95b8-43a2a6fc8a65.png)
![Screenshot from 2020-04-05 19-22-10](https://user-images.githubusercontent.com/46960905/78500470-33f7a200-7774-11ea-97b0-6aa5f99a0eda.png)
![Screenshot from 2020-04-05 19-25-22](https://user-images.githubusercontent.com/46960905/78500471-34903880-7774-11ea-9254-572b73aca48e.png)

**Comment by petebacondarwin** [comment]
@4-TREX - I note that your `JwsModule` is not imported into the `AppModule`. How is this module being used in the app? Is it lazy loaded?

Also can you clarify exactly what is not working? The build completes successfully, the app console shows no errors.

Finally, the best way to get a resolution to an issue with Angular is to provide us with a minimal reproduction of the problem that we can analyze. For example, can you create a small application that uses Material but is not working in the way that you describe?
