### ISSUE TITLE
Implement `withAnnotation` for DI 2.0

### ISSUE THREAD

**Issue by rkirov** [angular/angular#3644]
di.dart 1.x supported the following usage (translated to .ts below)

```
bind(Foo).withAnnotation(const Bar()).toImplementaion(Impl);
...
constructor(@Bar() bar) { ... }
```

Currently the same can be achieved by 
```
const BAR_TOKEN = 'bar';
bind(BAR_TOKEN).toClass(Impl);
...
constructor(@Inject(BAR_TOKEN) bar) {...}
```

Should this be the preferred replacement for `withAnnotation` or should we implement `withAnnotation` as sugar?

**Comment by vsavkin** [comment]
You are right `withAnnotation` and `@Inject(Token)` solve the same problem. They are used when the type annotation is not sufficient to resolve the dependency. 

The Angular DI's mental model is that every injector is like a "lazy hash map" from a token to an object. Implementing `withAnnotation` will make this model less clear. It would also complicate the implementation.

For instance, `bind(Foo).withAnnotation(const Bar()).toImplementation(Impl);` would require us to create a new composite token including Foo and Bar. We would have to create this token when we parse dependencies and create bindings. This means that we would probably not be able to use the === operator to compare two tokens. This is quite a bit of complexity we would have to add. And that is why I think we should consider it only if `@Inject(Token)` does not suffice.

**Comment by mhevery** [comment]
:+1: @vsavkin So what is the actionable thing here? Drop `withAnnotation` and replace it with?

**Comment by vsavkin** [comment]
I think no changes are required. The `@Inject(token)` is more flexible and covers the withAnnotation use case. Closing it.
