### ISSUE TITLE
Angular 6.1 to 7.2 upgrade

### ISSUE THREAD

**Issue by rohitmaini** [angular/angular#36443]
I am upgrading my application from Angular 6.1 to 7.2. I have got lot of javascript files also in  my application. I first upgraded rxjs to 6.3.3. It was suceessfully upgraded. I had to keep rxjs-compat for primeng support. After i upgraded Angular, it started giving below error.
![Capture](https://user-images.githubusercontent.com/50734174/78524915-0dc51700-77f3-11ea-85ba-ac0e25416377.JPG)

Below is my package.json.

{
  "version": "1.0.0",
  "name": "titan.webcore",
  "scripts": {
    "clean": "rimraf -- wwwroot",
    "ng": "ng",
    "prettier": "prettier --write \"**/*.{js,json,css,scss,less,md,ts,html,component.html}\"",
    "start": "npm run execute-gulp && ng serve --open",
    "build": "ng build",
    "test": "jest",
    "test:watch": "jest --watch",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "clean:dist": "rimraf -- dist",
    "execute-gulp": "gulp",
    "build:uat": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod --configuration=uat --watch=false",
    "build:local": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod --configuration=local",
    "build:preprod": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod --configuration=preprod",
    "build:qa": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod --configuration=qa",
    "build:demo": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod --configuration=demo",
    "build:testlab": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod --configuration=testlab",
    "build:hra-dev": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod --configuration=hra-dev",
    "build:hra-uat": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod --configuration=hra-uat",
    "build:hra-prod": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod --configuration=hra-prod",
    "build:hgt-prod": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod --configuration=hgt-prod",
    "build:hgt-dev": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod --configuration=hgt-dev",
    "build:indev": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod --configuration=indev --watch=false",
    "build:inqa": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod --configuration=inqa --watch=false",
    "build:stats": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --stats-json --named-chunks",
    "build:suzuki-dev": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod --configuration=suzuki-dev",
    "analyze": "webpack-bundle-analyzer dist/stats.json",
    "test-aot": "npm run execute-gulp && npm run build:uat && lite-server --baseDir=\"dist\"",
    "commit": "npx git-cz"
  },
  "dependencies": {
    "@angular/animations": "7.2.16",
    "@angular/cdk": "7.3.7",
    "@angular/common": "7.2.16",
    "@angular/compiler": "7.2.16",
    "@angular/core": "7.2.16",
    "@angular/forms": "7.2.16",
    "@angular/platform-browser": "7.2.16",
    "@angular/platform-browser-dynamic": "7.2.16",
    "@angular/router": "7.2.16",
    "@fortawesome/fontawesome-pro": "^5.10.0",
    "@ngrx/store": "^6.1.2",
    "@ngx-lite/in-viewport": "^0.1.3",
    "@schuchard/prettier": "3.1.0",
    "@swimlane/ngx-graph": "6.2.0",
    "@types/html2canvas": "0.0.35",
    "@types/jspdf": "^1.3.1",
    "ag-grid-angular": "21.0.1",
    "ag-grid-community": "21.0.1",
    "anychart": "^8.5.0",
    "bootstrap": "3.3.6",
    "chart.js": "2.8.0",
    "ckeditor": "4.11.4",
    "ckeditor4-angular": "1.0.0-beta.2",
    "clndr": "1.4.7",
    "core-js": "2.5.7",
    "crypto-js": "^3.1.9-1",
    "d3": "4.11.0",
    "es6-shim": "0.35.2",
    "event-source-polyfill": "0.0.9",
    "fingerprintjs2": "2.0.3",
    "fullcalendar": "4.0.0-alpha",
    "fullcalendar-scheduler": "^1.9.4",
    "gsap": "^1.20.4",
    "gulp": "^4.0.2",
    "html2canvas": "^1.0.0-rc.5",
    "ify-loader": "1.1.0",
    "immutable": "^4.0.0-rc.12",
    "intl": "1.2.5",
    "jquery": "3.4.1",
    "moment": "2.24.0",
    "moment-timezone": "0.5.23",
    "nanoscroller": "0.8.7",
    "natives": "1.1.6",
    "ng2-ckeditor": "1.2.1",
    "ng2-pdf-viewer": "5.2.3",
    "ngx-in-viewport": "0.0.2",
    "ngx-infinite-scroll": "6.0.1",
    "plotly.js": "1.51.0",
    "primeicons": "1.0.0",
    "primeng": "^5.2.2",
    "quill": "1.1.8",
    "reflect-metadata": "0.1.12",
    "resumablejs": "1.1.0",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.3.3",
    "rxjs-tslint": "^0.1.7",
    "systemjs": "0.20.12",
    "ts-helpers": "1.1.1",
    "underscore": "1.8.3",
    "web-animations-js": "2.3.1",
    "zone.js": "0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.6.8",
    "@angular-devkit/build-ng-packagr": "~0.7.0",
    "@angular/cli": "^7.2.4",
    "@angular/compiler-cli": "7.2.16",
    "@angular/language-service": "7.2.16",
    "@testing-library/angular": "^8.2.0",
    "@testing-library/dom": "6.11.0",
    "@testing-library/jest-dom": "4.2.4",
    "@types/crypto-js": "^3.1.43",
    "@types/jest": "24.0.23",
    "@types/jquery": "3.3.29",
    "@types/node": "8.9.5",
    "@types/plotly.js": "1.28.10",
    "@types/resumablejs": "1.0.5",
    "@types/underscore": "^1.8.13",
    "codelyzer": "^4.5.0",
    "cz-conventional-changelog": "^3.0.2",
    "gulp-sass": "^4.0.2",
    "husky": "3.1.0",
    "jest": "24.9.0",
    "jest-preset-angular": "8.0.0",
    "lint-staged": "9.5.0",
    "ng-packagr": "^3.0.0",
    "nps": "5.9.8",
    "nps-utils": "1.7.0",
    "prettier": "1.19.1",
    "protractor": "5.3.2",
    "rimraf": "2.6.1",
    "ts-node": "5.0.1",
    "tsickle": "^0.29.0",
    "tslib": "^1.9.0",
    "tslint": "5.9.1",
    "tslint-config-prettier": "1.18.0",
    "typescript": "^3.1.1",
    "webpack-bundle-analyzer": "^3.3.2"
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.{js,json,css,scss,less,md,ts,html,component.html}": [
      "prettier --write",
      "git add"
    ]
  }
}

I am not sure in which direction to proceed

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

---
One thing that does look suspicious is TypeScript's version range, which is `^3.1.1` so you might be pulling in `3.8` at the moment. This should definitely be replaced with `~3.1.1`.
