### ISSUE TITLE
Components are not removed from DOM when calling NgModuleRef.destroy()

### ISSUE THREAD

**Issue by arturovt** [angular/angular#36449]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

Yes

### Description

All components remain in DOM when calling `NgModuleRef.destroy()` if Ivy is enabled, but actually, all `ngOnDestroy` hooks are invoked, event listeners are removed, basically, all cleanups are done except removing nodes from DOM.

But if Ivy is disabled (view engine is being used) then all nodes are removed.

From what I see when using Ivy the `cleanUpView` function is invoked which execute on destroy hooks, removes listeners, but when it gets to `renderer.destroy()` it actually does nothing:

https://github.com/angular/angular/blob/d528dedd5007dd7272878bf7a933cb1f3e153ed0/packages/core/src/render3/node_manipulation.ts#L424-L428

When using view engine it gets to `ViewRef_.destroy -> execRenderNodeAction -> renderer.removeChild`.

I was looking for similar issues but haven't found anything, also I haven't found this change in the changelog. The use case is: we have micro-frontend apps which are destroyed via `NgModuleRef.destroy()`.

## 🔬 Minimal Reproduction

1) `git clone git@github.com:arturovt/ngmoduleref-destroy-issue.git`
2) `cd ngmoduleref-destroy-issue`
3) `yarn`
4) Start dev server `yarn ng s`
5) Go to `http://localhost:4200`, open dev tools, click the "Destroy" button. Notice logs in the console and that component is removed from DOM
6) Stop dev server, go to `tsconfig.json` and set `enableIvy` to `true`
7) Start dev server again, click the "Destroy" button. Notice logs in the console and that component is NOT removed from DOM

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.0
Node: 10.18.0
OS: linux x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Anything else relevant?**

**Comment by sonukapoor** [comment]
@AndrewKushnir As discussed please assign to me.

**Comment by pkozlowski-opensource** [comment]
Here is a minimal reproduce scenario: https://ng-run.com/edit/BKlIgySUOkhCvVLdhiVh (one can see the ivy regression and VE behaviour by switching between ivy and VE).

2 observations here:
* VE is clearing the content of the component's template (`I should self-destroy but I don't...`) but ivy don't (this is clearly a bug);
* VE is _also_ removing the app's root element (`<my-app id="app">Loading...</my-app>`) and this is debatable - somehow component doesn't "own" the root (host) node - it is just bootstrapped into this node. As such I'm not sure if VE behaviour is correct here...

cc @AndrewKushnir
