### ISSUE TITLE
Unable to get scroll position of element div  on ngOnDestroy, it is always zero

### ISSUE THREAD

**Issue by mohitvashisht88** [angular/angular#36445]
Unable to get scroll position of element div  on ngOnDestroy, it is always zero.

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
