### ISSUE TITLE
feat(compiler): [property]="{{foo}}" should raise an exception

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#3645]
Some users during a hack night were trying to set properties this way. Since {{foo}} would never be a valid expression, the compiler should raise a helpful exception when this pattern is found. Since this pattern is predictable, the exception should give specific feedback.

My suggestion: `{{foo}} is not a valid expression in [prop]="{{foo}}". Try [prop]="foo"`

CC: @mhevery 

Related: #3662 (should be done together)

**Comment by pkozlowski-opensource** [comment]
So, today we are getting those errors for the `<div [a]="{{b}}">` case:

> Parser Error: Unexpected token {, expected identifier, keyword, or string at column 2 in [{{b}}] in someComponent

As for giving specific feedback: if we decide to go down this path we need to take all the binding forms (`bind-a`, `data-bind-a`) into account. Same goes for events (`(click)="{{foo()}}"`) as well, I guess.

**Comment by PascalPrecht** [comment]
I'm also voting for more specific error messages here, if it's not to
expensive to implement. I think one thing that a lot of ppl struggled with
in AngularJS, was that the error messages weren't super clear at a first
glance (even tho I think minError is great). So if we can improve here, we
should definitely do so

**Comment by mhevery** [comment]
I think this should be implemented in the parser, and the error should read: `Got interpolation '{{}}' when expression was expected`. This can easily be done in Parser to see if the parsing text (expression) starts with `{{`

**Comment by pkozlowski-opensource** [comment]
> This can easily be done in Parser to see if the parsing text (expression) starts with {{

We should probably also check for interpolations inside an expression string to catch cases like `[foo]="before {{exp}} after"`
