### ISSUE TITLE
fix(compiler): directives pointing to forward ref should produce an error

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#3646]
If two components are defined in the same TypeScript/ES6 module, and one component depends on the other before it's defined, then the component will be undefined at runtime since classes are transpiled using assignment instead of hoistable declarations.

```typescript
@Component({
  directives: [Child] //Child would be undefined at this point
})
class ComponentOne {
}

@Directive(...)
class Child {
}
```

This should raise an error, instead of failing silently as it does now.

CC: @mhevery

**Comment by PascalPrecht** [comment]
Maybe that error could also give a hint for `forwardRef()` ?

**Comment by btford** [comment]
Woah, didn't even know we had a util for this. Nice!

Here's the docs page: https://angular.io/docs/js/latest/api/di/forwardRef-function.html

**Comment by mhevery** [comment]
The compiler should check the `View.directives` and thrown an error if any of them are `null` or `undefined` It is important that the error message has name of the component and the surrounding directives, otherwise `Directive was null` is not a useful error.

Suggested error: `View annotation on 'MyComponent` points to non existent directive: [NgIf, undefined, MyDirective]`.

**Comment by pkozlowski-opensource** [comment]
:+1: I was bumping into nulls / undefined in directives list before.

**Comment by pkozlowski-opensource** [comment]
> The compiler should check the View.directives and thrown an error if any of them are null or undefined It is important that the error message has name of the component and the surrounding directives, otherwise Directive was null is not a useful error.

The current error is: `Unexpected directive value 'undefined' on the View of component 'BsDemoApp'` when `undefined` ends up in the directives list - I wonder why it was silently failing for Jeff, going to re-test with forward references.

**Comment by danielrasmuson** [comment]
I also was not able to reproduce this error. 

If you explicitly state 'undefined'...

```javascript
@Component({
  directives: [undefined]
})
```

I still got the message @pkozlowski-opensource mentioned.

```
Unexpected directive value 'undefined' on the View of component 'BsDemoApp'
```

**Comment by mhevery** [comment]
obsolete
