### ISSUE TITLE
Attribute in deps stopped working with Ivy

### ISSUE THREAD

**Issue by waterplea** [angular/angular#36479]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8

### Description

You can use `Attribute` decorator in `deps` for providers like this:

```
{
    provide: TOKEN,
    deps: [[new Attribute('token')]],
    useFactory: factory,
}
```
It stopped working with Ivy and Angular 9

## 🔬 Minimal Reproduction

 
Working Angular 8:
https://stackblitz.com/edit/angular-attribute-deps

Broken Angular 9:
https://ng-run.com/edit/hyppU3cXJCaRYLYVDAQp

## 🔥 Exception or Error
<pre><code>
R3InjectorError(AppModule)[[object Object] -> [object Object] -> [object Object]]: 
  NullInjectorError: No provider for [object Object]!
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>9.1.0</code></pre>

**Comment by sonukapoor** [comment]
@AndrewKushnir i can take a look at this.
