### ISSUE TITLE
Move to typescript-eslint

### ISSUE THREAD

**Issue by gligoran** [angular/angular#36478]
# 🚀 feature request

### Relevant Package
tslint

### Description
Since [tslint is now deprecated](https://github.com/palantir/tslint/issues/4534), a move to the recommended [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) should be considered.

**Comment by destus90** [comment]
https://github.com/angular/angular-cli/issues/13732#issuecomment-575796158

**Comment by gkalpak** [comment]
This is a CLI issue. Since it is being tracked in angular/angular-cli#13732, I am going to close this one.
