### ISSUE TITLE
docs(Query): improve Query documentation

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#3647]
The Query documentation is lacking context (just code samples), and is only available in the [`QueryFactory`](https://angular.io/docs/js/latest/api/annotations/QueryFactory-interface.html) interface documentation at the moment. It should be added in the [`Query`](https://angular.io/docs/js/latest/api/annotations/Query-var.html) documentation, and given more description about its purpose.

CC: @mhevery

**Comment by mhevery** [comment]
fixed: https://angular.io/docs/ts/latest/api/core/index/Query-var.html

**Comment by zoechi** [comment]
It's deprecated anyway, isn't it?
