### ISSUE TITLE
Enable capturing while listening to an event using output property binding like (blur)

### ISSUE THREAD

**Issue by LalitKushwah** [angular/angular#36475]
Hello All,
I have developed a component which is simply a wrapper over input box say 
<my-input></my-input>
Now when I am using blur and focus event on created webcompoennt in angular like

**<my-input (blur)="method"></my-input>**

but my method is not getting called.
I came to know that it requires *capturing* enabled which can be done by :

myinput.addEventListener('blur', function () {}, *true*)
I have researched a lot but haven't found any support for this.

Can someone help me ?

**Comment by pkozlowski-opensource** [comment]
It is not very clear to me what is the exact problem you are facing. 

> <my-input (blur)="method">
but my method is not getting called.

If you want to call a method in response to an event you should actually use the method call syntax: ` (blur)="method()"`

> I came to know that it requires capturing enabled 

I'm not sure how `capture` fits into the overall picture here, but we do not support the `capture` option currently (it is tracked in #11200).

I'm afraid that we will need a minimal reproduce scenario in a stackblitz or similar and provide clear description of the problem? As the issue stands it is not actionable for us.

**Comment by pkozlowski-opensource** [comment]
I'm going to close this issue since we haven't heard back from the issue author. @LalitKushwah please open a new issue and provide requested info if this is still a problem for you.
