### ISSUE TITLE
Support dynamic ids in @angular/localize

### ISSUE THREAD

**Issue by simdevmon** [angular/angular#36480]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/localize

### Description

I know in-code translations using the global `$localize` are still an unofficial feature. However it is a very useful way for me to do translations in code. E.g. 
```
$localize`:@@OTHER_DAYS:days`
```
One use-case which is not covered is, if I get the translation id via an external API. Then I have the translation id stored within an variable. 
It would be helpful, to be able to call `$localize` with an id stored in a variable. E.g.

```
let translationId = // get from external API
let defaultText = //
$localize`:@@${translationId}:${defaultText}`
```

As far as I understand the current implementation will interpret the first placeholder as part of the text and will fail building. 

 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
An option to hand over the translation id stored in a variable to a `$localize` call.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
I have tried to build the arguments manually, but this fails when doing a production build:

```
localize(id: string, value: string) {
    let ra: ReadonlyArray<string> = [':@@' + id + ':', ''];
    ra['raw'] = [':@@' + id + ':', ''];
    let tsa: TemplateStringsArray = <TemplateStringsArray>ra;
    return $localize(tsa, ...value);
}
```

**Comment by petebacondarwin** [comment]
I'm afraid this is not in-scope for the `$localize` functionality. `$localize` is designed as a tagging device to enable translation primarily at compile-time. As you can imagine, it is not possible to do dynamic translation during the build.

The fact that there is talk about "runtime" translation can be confusing, since really it is just that the translations will still be done in a static way but in the browser rather than on the server. The underlying approach of `$localize` is not designed to operate in a dynamic way.

Another way of looking at your use case is to forget that these message might be translated and think about how you would code your app in that case. I think that what you are saying is that you have an API that returns a message id, and that you then lookup a message string based on this id. Where would these messages be stored in the first place? In other words, where would you store the `defaultText` that you refer to in your example? If you are storing all the `defaultText` values as static strings in code then you could add in translation by using `$localize` on each of these static strings.

**Comment by simdevmon** [comment]
@petebacondarwin: thank you for your thoughts on that topic and the quick response. 

The `messageId` and the `defaultText` (some features do not even have a default text and will only return the message id) are stored in a database and are fetched via a REST API from a Java application. For example I would get:

```
[{
  messageId: 42,
  defaultText: 'Humidity detected'
},
{
  messageId: 43,
  defaultText: 'Battery deep discharged'
}]
```

To explain my use case a bit better, this is the workflow I used for **Angular 8**:

There are 3 different ways, where translations are used:

1. Translations in templates
This works fine in Angular since the beginning, so no issue here.

2. Translations in code (static id)
For this I used `@ngx-translate/i18n-polyfill` (I know it is only a speculative polyfill):

```
import { I18n } from '@ngx-translate/i18n-polyfill';
[...]
this.i18n('{{count}} log messages successfully deleted.', { count: count })
```

3. Translations in code (dynamic id)
Also using `@ngx-translate/i18n-polyfill` 

```
const id = 'STATUS_' + messageId;
this.i18n({ value: defaultText, id: id });
```

In addition I maintain a static XLF file `messages.static.status.xlf` containing the dynamic ids:

```
    <unit id="STATUS_42">
      <segment state="final">
        <source>Humidity detected</source>
      </segment>
    </unit>
    <unit id="STATUS_43">
      <segment state="final">
        <source>Battery deep discharged</source>
      </segment>
    </unit>
```

During build I first run `ng xi18n` to extract messages from templates, `ngx-extractor` to extract messages from code and `xliffmerge` to merge the generated files with the static file:

```
ng xi18n --i18nFormat=xlf2 --output-path locale && ngx-extractor -i src/**/*.ts -f xlf2 -o src/locale/messages.xlf && node xliffmerge.static.js && xliffmerge --profile xliffmerge.json en de es fr ru
```

The advantage is that all phrases are stored in a single XLF file for each language, which makes external translation easy. 


This workflow is not working anymore for **Angular 9**, mainly because `@ngx-translate/i18n-polyfill` is quite different from `$localize` and not working anymore. 
Currently I have a few options in mind for my use case in Angular 9:

- Migrate to an external library like `ngx-translate` or `locl`, but after a first try, I found out that there are also some issues.

- Make a code generation to create a map or huge switch statement containing all dynamic ids as static strings in code. 

- Implement an own way to read XLF files (ship them as assets) and get the phrases during runtime.


Non of these seem to be ideal, that is why I came up with this feature request. As far as I understand there is a substitution during compilation of translated phrases. Maybe `$localize` could be extended with an option, to build a key/value map when processing a translation file (XLF) with all pairs, that are not used for template or static in code translations. During runtime there could be a lookup for this key/value map, which was build during compilation for the translated phrase.

**Comment by petebacondarwin** [comment]
Sorry I didn't reply sooner. This is a tricky problem, I agree. But I feel that it is not one that `$localize` is able to solve. I might propose the following idea for your consideration, although I have not completely thought it through...

1) Use the `@angular/localize` code to create a tool that takes a translation file and the untranslated distributable code of the application to extract a JSON file that contains this key-value map. This is basically what you suggested but I am saying that this should be external to the code-base. Also, as it stands the current `@angular/localize` tooling (especially integrated with the CLI) cannot do this but it would not be too hard to add this as a feature.
2) In you code have your own "runtime" translation service, which loads up the JSON translations file (perhaps via HTTP request?) and does the dynamic translations that you require. What I am basically saying is that the `$localize` tag itself would/should not be part of this. It should be kept purely as a tagging device for non-dynamic inlining of translation messages. This dynamic translation service could make use of the functions in `@angular/localize` such as `loadTranslations()` and `translate()`.

**Comment by simdevmon** [comment]
I read an interesting article about lazy loading locales with Angular from Manfred Steyer https://www.angulararchitects.io/aktuelles/lazy-loading-locales-with-angular/ 

I tried to adapt this to my use case and during build I generate a JavaScript file for each language with a map of translations.

e.g. `assets/i18n/static.en.js`

```
var globalPhrases = new Map();
globalPhrases.set('STATUS_42', 'Humidity detected');
globalPhrases.set('STATUS_43', 'Battery deep discharged');
```

I load the script depending on the language using the code of the simple loader (basically just attaching it to the document body)
https://github.com/manfredsteyer/global-locals/blob/master/src/app/simple-loader.service.ts 

With this I can get my static phrases through the global phrase map. I would say this might not be very elegant, but it works.

**Comment by petebacondarwin** [comment]
Closing as this is out of scope for $localize.
