### ISSUE TITLE
Ivy doesn't validate unknown attributes/properties

### ISSUE THREAD

**Issue by StNekroman** [angular/angular#36481]
Previously I compiled my app using ViewEngine in AOT mode.
So I received error about missing directives in template.
For example, if I do next:
`<div [someUnknownParam]="something"></div>`

And that was useful, so I received message, that I forgot to import some module, where some directive is defined.

Now, when I moved to Ivy, it does type check, for known parameters, but it just ignores any unknown directive, which I forgot to import.

Is this expected behavior?

P.S. In tsconfig.json I had and still have next:

```
"angularCompilerOptions": {
    "skipMetadataEmit" : false,
    "skipTemplateCodegen": false,
    "strictMetadataEmit" : true,
    "strictInjectionParameters": true,
    "fullTemplateTypeCheck": true,
    "strictTemplates": true,
    "enableIvy": true
  },
```

Even tried to extend with 
```
      "strictInputTypes": true,
      "strictNullInputTypes": true,
      "strictAttributeTypes": true,
      "strictSafeNavigationTypes": true,
      "strictDomLocalRefTypes": true,
      "strictOutputEventTypes": true,
      "strictDomEventTypes": true,
      "strictContextGenerics": true,
      "strictLiteralTypes": true
```
but without any difference.

**Comment by JoostK** [comment]
With `strictTemplates` enabled, these should indeed be detected and reported. Are you building using AOT? In JIT mode the template type checker doesn't run, so the flags won't matter then.

The individual strictness flags won't make a difference here, if `strictTemplates` is `true` then they're all enabled by default (and the flags can be used to disable individual checks) and if `strictTemplates` is `false` then they can be used to enable individual strictness flags.

**Comment by StNekroman** [comment]
> Are you building using AOT?

I thought, Ivy doesn't have two different build configs any more, rather then --env=production.
Previous I have dev mode with JIT compiler and bootstraping from modules
and AOT mode with bootstrapping from module factories.

Now Ivy dropped generation of ngfactories. So how I can make "AOT build" now?

**Comment by JoostK** [comment]
Ivy still has two modes of operation, it's just that the result of AOT compilations are no longer ngfactory files but static properties added onto the class in the compiled output.

With Ivy though, using AOT should be seen as default. If you upgraded using `ng update`, the migration will actually have changed the project's configuration to use AOT mode even in development mode, regardless of prod builds or not. So I'm guessing you're already using AOT compilation, in which case it's surprising that this doesn't work for you.

You can look for the "aot" property in `angular.json` in the project root, or alternatively inspect the compiled output but then you'd need to know what to look for :-)

**Comment by StNekroman** [comment]
That's not my case. Because I have ordinary webpack build, so I build angular code via AngularCompilerPlugin from @ngtools/webpack.
Moreover, I have hybrid app env with angularjs inside.

Just checked - production mode doesn't validate parameters.
Is there any way to check if build runs in AOT mode or no?

**Comment by StNekroman** [comment]
I have just a regular webpack build, which contains:

```
new AngularCompilerPlugin({
                tsConfigPath:         path.join(__dirname, "tsconfig.json"),
                sourceMap:            sourceMap,
                skipCodeGeneration:   !production,
                compilerOptions: {
                    strictInjectionParameters: true,
                    fullTemplateTypeCheck: true,
                    strictTemplates: true,
                    enableIvy: true
                }
            }),
```

Here is page with all options for that plugin:
https://www.npmjs.com/package/@ngtools/webpack
It doesn't contain any word about "getNgSemanticDiagnostics".
I suspect, that this method is applicable only for ng builds.

Additional information: when I run debug build - it uses JIT compiler inside and uses `eval` and  `new Function(...)`, which breaks CSP rule script-src: 'self'.
So for debug builds I had (and still have) relaxed CSP rule script-src: 'self' 'unsafe-eval', which allows to execute custom code from strings.
For prod builds I have regular strict CSP rule and... with Ivy it works. So I can assume, that there are no dynamic code, that everything is pre-compiled. Thus I assume, that I have AOT build.
But is there any better method to check AOT?

Here is how I bootstrap my app:

```
if (__BUILD__.production) {
    enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModuleNG2).then((moduleRef: NgModuleRef<any>) => {
        console.info("Main Angular module bootstrap done.");
    })
    .catch(err => console.error(err));
```

As I told before, before Ivy I had ngfactories and two entry points to app bootstraping - bootstrapModule and bootstrapModuleFactory. So that was pretty obvious, in which mode I'm running.
But Ivy dropped ngfactories. So, as I understand, now I need only bootstrapModule. Am I correct?

**Comment by JoostK** [comment]
In AOT mode it could just be

```ts
platformBrowser().bootstrapModule().then(...)
```

so yes, you can just use `bootstrapModule` even with AOT compiled code but you can switch from `platformBrowserDynamic` to `platformBrowser`.

You can check for AOT compiled code by looking for static properties in the compiled `.js` files. The classes that have an Angular decorator will have been converted into static property assignments. I just looked at `@ngtools/webpack` and the `skipCodeGeneration` flag enables JIT mode, in which case the template type checker does not execute.

By the way, you can still configure Ivy to generate ngfactory files but they don't offer any value (and also there's currently a bug, see #35703), so I would try not to use them. They will be going away at some point in the future.

**Comment by StNekroman** [comment]
Yes, thank you.
I had skipCodeGeneration: true for debug builds, so I was missing proper validation.
Now it reports expected error on  <div [someUnknownParam]="something"></div>
Additional question - currently it allows to have
`<div someUnknownParam="something"></div>`
Unknown attribute, not binding parameter. Is this expected behavior?

P.S. Although started using platformBrowser() for prod configuration.

**Comment by pkozlowski-opensource** [comment]
> Additional question - currently it allows to have
<div someUnknownParam="something"></div>
Unknown attribute, not binding parameter. Is this expected behavior?

Sadly we are not validating those today, see #3425

**Comment by StNekroman** [comment]
Ok, thanks everybody for help.
