### ISSUE TITLE
angular page must refresh that be ok

### ISSUE THREAD

**Issue by wxyer** [angular/angular#36485]
when fire the function，nothing wrong ，but the current page jump to home page which url is ‘/’ redirect to some url  like ‘project/cur'，after sometime it resumes jumping to the final url ,

1.  problem code

```
async open(id: string) {
    const idnum = Number(id);
    // let flag = false;
    let dev = new Device();
    try {
      dev = this.Devices.find(p => p.ID === idnum);
      this.showprgress = true;
      this.store.set('device', dev);
      await this.tpsService.init(dev.ID.toString()).toPromise();

    } catch (err) {
      this.toastService.error(err.error['message']);
    } finally {
      this.router.navigate([`tps/status/cur`]);
    }
  }
```

2.  store.set method code 
 ```
set<K extends keyof State>(name: K, stateValue: State[K]) {
    this.subject.next({ ...this.value, [name]: stateValue });
    if (name === 'project' || name === 'device') {
      sessionStorage.setItem(name, JSON.stringify(stateValue));
    }
  }
```

3.  this.tpsService.init method code

```
init(tpsid: string): Observable<boolean> {
    return this.http.put<boolean>(`${APP_CONFIG.api}/tps/init/${tpsid}`, null);
  }
```

**any other place,when code has store.set been call ，it has same thing。
how can i fix the bug。**
angular 6

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
