### ISSUE TITLE
Type errors in nested form groups / arrays 

### ISSUE THREAD

**Issue by TomTomB** [angular/angular#36496]
# 🐞 bug report

### Affected Package
@angular/forms

### Description

After enabling `strictTemplates` inside the `tsconfig.json` for my project I am getting the following type error for all nested form groups:

```
ERROR in src/app/sub-form/sub-form.component.html:1:52 - error TS2740: Type 'AbstractControl' is missing the following properties from type 'FormGroup': controls, registerControl, addControl, removeControl, and 3 more. 
<ng-container *ngIf="form.get('bar') as innerForm" [formGroup]="innerForm">   
```

## 🔬 Minimal Reproduction

https://github.com/TomTomB/forms-type-error

1. Clone the repo
2. Run `npm i && ng serve`
3. Look inside the terminal output

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.7
Node: 12.13.0
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Comment by JoostK** [comment]
Let's track this in #36405. I wouldn't classify it as bug that the forms' API typings do no convey insight into the type of control that you request, hence you end up with the `AbstractControl` base class.
