### ISSUE TITLE
docs: update Ivy compatibility guide to include a note on styling precedence changes

### ISSUE THREAD

**Issue by mlakmal** [angular/angular#36508]
we have a css class used to show/hide element. and we also have angular directive to take input and add/remove this class using host binding. below is the code.

<pre>
@Directive({
  selector: '[ngShow]',
  host: {
    '[class.hidden]': '!ngShow',
    '[attr.aria-hidden]': '!ngShow'
  }
})
export class NgShowDirective {
  @Input()
  ngShow = false;
}
</pre>

Usage:
```html
<div class="hidden" [ngShow]="asyncProperty">test 123</div>
```

when we set asyncProperty value to true after execution of an async function, it does not remove the "hidden" css class. this worked in angular v8 and started to break after v9 upgrade.

tested against v9.1.0

**Comment by pkozlowski-opensource** [comment]
I believe that it works as designed in Angular v9: classes added on an element have a higher priority that ones coming from a host binding. Yes, this is change from the v8 behaviour, but this is a deliberate change. You can find more info here: https://angular.io/guide/template-syntax#styling-precedence

**Comment by mlakmal** [comment]
@pkozlowski-opensource thanks for the information. but it seems like this might cause lot of issues since this was not included under breaking changes for v9. i personally assume [class.] binding on host will alter the given class even if it exists on element or not.

**Comment by Jasonkoolman** [comment]
@mlakmal Could you not just remove the initial class which is applied on the element? You could also use the `@HostListener` decorator I think.

**Comment by mlakmal** [comment]
> @mlakmal Could you not just remove the initial class which is applied on the element? You could also use the `@HostListener` decorator I think.

**Comment by mlakmal** [comment]
@Jasonkoolman i tried hostlistner binding and it didn’t work...

Also we can’t remove that class initially, if we do, it shows invalid state for brief time until async function completes...

**Comment by Jasonkoolman** [comment]
@mlakmal Try this:

```typescript
@HostBinding('class') get classes() {
    return 'classA classB classC';
}
```
You could use [classnames](https://www.npmjs.com/package/classnames) to conditionally join classes together in the `classes()` method.

**Comment by mlakmal** [comment]
I was able to fix this temporarily using renderer to remove class manually.

**Comment by dannymcgee** [comment]
Just wanted to chime in here to say that this change for Angular 9 is something I have been waiting on for a _long_ time and is a much appreciated improvement over the previous functionality. I would argue that adding a class to a component in the template, and having that component silently remove it due to a conflicting host-binding, is far more confusing/destructive than the new behavior. Though I guess you could argue that explicitly setting a class name to "false" in the host-binding is a different situation than just binding a string value to "class" and wiping out all of the existing classes.

**Comment by atscott** [comment]
As discussed here, this _is_ working as intended in Ivy and the styling precedence is described here: https://angular.io/guide/style-precedence. Keeping this open, since it should be included in the [compatibility guide](https://angular.io/guide/ivy-compatibility)
