### ISSUE TITLE
'mat-toolbar' is not a known element

### ISSUE THREAD

**Issue by palminha** [angular/angular#36519]
# 📚 Docs or angular.io bug report

### Description

 Trying to use the mat-toolbar but i got a compilation error saying
"ERROR in src/app/app.component.html:28:1 - error NG8001: 'mat-toolbar' is not a known element:"

### What's the affected URL?**
https://material.angular.io/guide/theming
https://material.angular.io/components/toolbar/examples

### Reproduction Steps**

Following the documentation steps in the links above we get an error compiling...

#1 install material 
#2 include the theme in styles.css
#3 try to use <mat-toolbar> as described in the example

## 🔥 Exception or Error
<pre><code>
ERROR in src/app/app.component.html:28:1 - error NG8001: 'mat-toolbar' is not a known element:
1. If 'mat-toolbar' is an Angular component, then verify that it is part of this module.
2. If 'mat-toolbar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

28 <mat-toolbar>
   ~~~~~~~~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.

</code></pre>

## 🌍  Your Environment
npx ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.0
Node: 12.16.1
OS: linux x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular/cdk                      9.2.0
@angular/material                 9.2.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.42.0

**Comment by santoshyadav198613** [comment]
You need to import import {MatToolbarModule} from '@angular/material/toolbar'; and add it in imports array. Also the code for material is maintained in https://github.com/angular/components.

**Comment by atscott** [comment]
Closing, see @santoshyadav198613's comment.

**Comment by palminha** [comment]
The examples are not importing... They should

A quarta, 8 de abr de 2020, 18:57, Andrew Scott <notifications@github.com>
escreveu:
