### ISSUE TITLE
Navigating relativeTo:Module

### ISSUE THREAD

**Issue by tobias74** [angular/angular#36514]
Currently it seems impossible to navigate relativly to the url of a lazy-loaded feature-module.

It is however possible to navigate relatively to the current URL by using "{relativeTo: this.route}"

Now the feature I would need is:

`        this.router.navigate(["/customer/123"], {
          relativeToFeatureModule: true,
        });
`

I could of course navigate with absolute URLs like this:

`        this.router.navigate(["/mycompany/videostore/customer/123"]);
`

But within the (lazy-loaded) feature-module I might not want to know anything about the URL which has been assigned to the feature-module.

**Comment by tobias74** [comment]
So it seems to be true that relative navigation can only be done with chained '../..' like

`this.router.navigate(['../../../../something/123])`

To elaborate on my use-case:

I have a component, that has a link. This link needs to navigate to 

`/something/123`

relative to its feature module. The absolute path might be 

`/mywebsite/projektA/something/123`

or in another project

`/another/website/projects/a/something/123`

Now the component with the link that has to navigate to said URL might be used in different pages of the feature-module. So the relative path to "something/123" is different depending on where this component is used. It might be '../something/123' or '../../../something/123'

Example:

The is a page /website/feature-module/elsewhere/123. Now this page contains my component and the navigation would be '../../something/123'.

Now in another page /website/feature-module/my/personal/space/today the same component is used. Navigating to '../../something/123' would end up as '/website/feature-module/my/personal/something/123' which is obviously wrong.

**Comment by tobias74** [comment]
There is a discussion on SO regarding this topic:

[https://stackoverflow.com/questions/46833891/navigate-relative-to-submodule-in-angular](https://stackoverflow.com/questions/46833891/navigate-relative-to-submodule-in-angular)

**Comment by miiihi** [comment]
A quick & dirty workaround, using an internal property  `Route._loadedConfig`
Service returns module "mount points", use it simply with `serviceInstance.GetModuleMountPaths(MyModuleClass)`

Service doesn't consider not yet loaded modules, but this shouldn't be a problem, as the "normal" use case is, to findout where one own's module has been mounted, meaning it has to be loaded by that point...

It would be great if Angular would consider making `Route._loadedConfig` public!

```
// router-mounted-modules.service.ts

import { filter } from 'rxjs/operators';

import { Injectable, NgModuleRef, Type } from '@angular/core';
import { Route, RouteConfigLoadEnd, Router } from '@angular/router';

interface LoadedRouterConfig {
  routes: Route[];
  module: NgModuleRef<any>;
}

interface IRouteWithLoadedConfig extends Route {
  _loadedConfig?: LoadedRouterConfig;
}

@Injectable({
  providedIn: 'root'
})
export class RouterMountedModulesService {
  private _map: Map<Type<any>, string[]>;

  constructor(private _router: Router) {
    this._router.events.pipe(filter(e => e instanceof RouteConfigLoadEnd)).subscribe(() => this._RebuildMap());
  }

  /**
   * Returns an array of URLs at which the module has been loaded.
   * It doesn't consider not yet loaded modules!
   *
   */
  GetModuleMountPaths(module: Type<any>): string[] {
    if (!this._map) {
      this._RebuildMap();
    }

    if (this._map && this._map.has(module)) {
      return this._map.get(module);
    }
    return [];
  }

  private _RebuildMap() {
    this._map = new Map<Type<any>, string[]>();
    return this._TraverseRoutes(this._router.config, '/');
  }

  private _TraverseRoutes(routes: IRouteWithLoadedConfig[], currentPath: string) {
    routes.forEach((r) => {
      if (r._loadedConfig) {
        this._AddToMap(r._loadedConfig.module.instance.constructor, currentPath + r.path);
      }
      if (r.children) {
        this._TraverseRoutes(r.children, currentPath + (r.path ? (r.path + '/') : ''));
      }
    });
  }

  private _AddToMap(module: Type<any>, path: string) {
    if (!this._map.has(module)) {
      this._map.set(module, []);
    }
    this._map.get(module).push(path);
  }
}
```
