### ISSUE TITLE
Enable Nullish Coalescing operator in angular template

### ISSUE THREAD

**Issue by manueledones** [angular/angular#36528]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
What do you think about enabling Nullish Coalescing also in angular template?

I often write for example something like this:

`<span [title]="variable != null ? variable : ''">`

s.t 
if variable = 3, title = '3'
if variable = 0, title = '0'
if variable = null, title = '', meaning the html tooltip title is hidden

### Describe the solution you'd like
It would be nice in my opinion to write something like:

`<span [title]="variable ?? ''">`

to obtain the same results with a less verbose syntax.

It may be also helpful in other situations, in template interpolation {{ ... }}, etc

What do you think? Thanks!

**Comment by amitbeck** [comment]
The `title` attribute binding is exactly my use-case. Nullish coalescing would be extremely useful in this case, and in others too.

**Comment by xiaoxiangmoe** [comment]
Can we use it in Angular 10 or 11?

**Comment by mmjr-x** [comment]
I would also like this very much :) especially for situations where you are binding with an async value that returns an object with properties that can be nullish. At the moment this requires convoluted (and expensive, as in using async 2 times) template expressions, e.g. `[value]="(someObservable$ | async).somePropertyThatCanBeNullish != null ? (someObservable$ | async).somePropertyThatCanBeNullish : someFallbackValue`

Hopefully we will get this functionality :) however, in the meantime I created this pipe to alleviate the pain a bit:
```typescript
import { Pipe, PipeTransform } from '@angular/core';

/*
 * Applies Nullish Coalescing to the value (Provides typescripts ?? operator like functionality in templates)
 * Takes an fallback value argument.
 * Usage:
 *   value | nullishCoalesce:fallbackValue
 * Example:
 *   {{ null | nullishCoalesce:'some fallback value' }}
 *   formats to: 'some fallback value'
*/
@Pipe({
  name: 'nullishCoalesce'
})
export class NullishCoalescePipe implements PipeTransform {

  transform<T, K>(value: T, fallbackValue: K): T | K {
    return value ?? fallbackValue;
  }

}
```

**Comment by xiaoxiangmoe** [comment]
@mmjr-x You should Add change return type to `NonNullable<T> | K`

**Comment by mmjr-x** [comment]
@xiaoxiangmoe Thanks for the suggestion! However this will cause an issue since the accrual return `return value ?? fallbackValue` will be of type `T | K`. This can be fixed by casing `T` to `NonNullable<T>` using `as`, however I am unsure whether this is the correct way. This is what I came up with:
```typescript
import { Pipe, PipeTransform } from '@angular/core';

/*
 * Applies Nullish Coalescing to the value (Provides typescripts ?? operator like functionality in templates)
 * Takes an fallback value argument.
 * Usage:
 *   value | nullishCoalesce:fallbackValue
 * Example:
 *   {{ null | nullishCoalesce:'some fallback value' }}
 *   formats to: 'some fallback value'
*/
@Pipe({
  name: 'nullishCoalesce'
})
export class NullishCoalescePipe implements PipeTransform {

  transform<T, K>(value: T, fallbackValue: K): NonNullable<T> | K {
    if (value != null) {
      return value as NonNullable<T>;
    }
    return fallbackValue;
  }

}

```
If you or someone else can confirm this is correct I will change the example above as well for future reference? :)

**Comment by rafaelss95** [comment]
> If you or someone else can confirm this is correct I will change the example above as well for future reference? :)

I didn't test but you can do something like this:

```ts
import { Pipe, PipeTransform } from '@angular/core';

/*
 * Applies Nullish Coalescing to the value (Provides typescripts ?? operator like functionality in templates)
 * Takes an fallback value argument.
 * Usage:
 *   value | nullishCoalesce:fallbackValue
 * Example:
 *   {{ null | nullishCoalesce:'some fallback value' }}
 *   formats to: 'some fallback value'
*/
@Pipe({
  name: 'nullishCoalesce'
})
export class NullishCoalescePipe implements PipeTransform {
  transform<K>(value: null | undefined, fallbackValue: K): K;
  transform<T, K>(value: T, fallbackValue: K): T;
  transform<T, K>(value: T, fallbackValue: K): T | K {
    return value ?? fallbackValue;
  }
}

**Comment by exenestecnico** [comment]
Nullish Coalescing would be great to have in angular template, along with Optional Chaining for function calls.
I wanted to write `{{ data[col.field] ?? col.renderer?.(data) }}`
Tried to use the pipe @mmjr-x posted but it wasn't the right fit.
Ended up doing `{{ getCellData(col, data) }}` in template and in component:
```typescript
getCellData(col: Column, data: Data): string {
  return data[col.field] ?? col.renderer?.(data) ?? '';
}
```

**Comment by pitops** [comment]
Any update on this?

**Comment by sam-s4s** [comment]
Hah, just went looking for this exact feature. Now it's standard in Typescript (along with Optional Chaining / Save Navigation Operator) it only seems logical to add it to Angular template syntax... https://angular.io/guide/template-expression-operators

**Comment by wottpal** [comment]
I just updated Angular to use Null-Coalescing with the new TypeScript just to see that it isn't supported in templates yet 😭😭

would be awesome to see this implemented!

**Comment by surajmandalcell** [comment]
+1 for this feature 🙏

**Comment by singhinderpal** [comment]
+1 for this feature.

**Comment by jwvance** [comment]
+1 for this feature 🤞

**Comment by janpauldahlke** [comment]
bump*

**Comment by snebjorn** [comment]
The nullish coalescing operator would be a much preferred way to handle the current `AsyncPipe` workaround for `null | undefined`

```html
<tag
  [myInput]="(myObs$ | async) ?? defaultValue"
>
</tag>
```
