### ISSUE TITLE
runtime translation with lazy loading and ES5 (differential loading) is buggy

### ISSUE THREAD

**Issue by janousek** [angular/angular#36521]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/localize

### Is this a regression?

No.

### Description
Angular generates functions called "_templateObjectXYZ" (XYZ is number) for purpose of runtime translations. These functions are defined in the global scope. This is not a problem when the code is loaded using ES6 modules. But for differential loading (ES5) with multiple chunks, these names collide between JS files. And overwrites each other (ES6 modules are isolated from each other and thus there is no problem)

An example:

chunk1.js:
```
function _templateObject27() {
  var data = _taggedTemplateLiteral([":@@reservationDisabledMsg\u241Fae7be3f0e6729c98b02e1124df8a77aad6ee9f30\u241F1393106427250937902:VAlpha"]);

  _templateObject27 = function _templateObject27() {
    return data;
  };

  return data;
}
```

chunk2.js:
```
function _templateObject27() {
  var data = _taggedTemplateLiteral([":@@pricesWithVatMsg\u241Fe346e0c62e86724c7d4234ff4bbd0135ff1fe127\u241F527442591666970432:VBeta."]);

  _templateObject27 = function _templateObject27() {
    return data;
  };

  return data;
}
```

This leads to incorrect translations. The result depends on the order in which they are loaded (because one function overrides other).

The solution would be to not placing these functions into the global scope. Or do not reset the counter for "_templateObjectXYZ" function name genration between chunks. 

## 🌍  Your Environment

Angular Version: 9.1

**Comment by petebacondarwin** [comment]
Thanks for posting this issue. It is a known issue as runtime translation is not officially supported yet in Angular. The fix would be (as you suggest) move these message variable definitions into the template function closure.

Keeping this issue open as a reminder to look into this for runtime support.
