### ISSUE TITLE
Avoid calling abort on XMLHttpRequest

### ISSUE THREAD

**Issue by tonivj5** [angular/angular#36537]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common/http

### Is this a regression?

 Yes, the previous version in which this bug was not present was: *

### Description

This problem was previously reported (https://github.com/angular/angular/issues/33822), but it was closed and locked... so I'm opening a new one.

The issue was closed because it was reported in the deprecated http module, but the issue is still present in the new `HttpClientModule`
https://github.com/angular/angular/blob/27997a16c0e87dea01562267f8207c2ab79cd18e/packages/common/http/src/xhr.ts#L326-L339

As https://github.com/angular/angular/issues/33822 says:
> it makes it hard for other libraries that instruments XMLHttpRequest, to keep track of the XHR correctly

I'm having this issue using the package `miragejs`, causing this issue https://github.com/miragejs/miragejs/issues/329, because on abort the `request` object is reset. It breaks this package and I guess any other that track the `request` (https://github.com/miragejs/miragejs/issues/329#issuecomment-611447910)

I think it should call `abort` only when really it has been aborted, and avoid calling it when server already has replied.

## 🔬 Minimal Reproduction

 I think it isn't needed, otherway I can create one :+1:

## 🔥 Exception or Error
No exception on Angular side, but it breaks third-party packages that rely on xhr request object.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.1.1
Node: 13.7.0
OS: linux x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              8.3.25
@angular-devkit/schematics        8.3.25
@angular/cdk                      9.2.0
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
    
Done in 0.46s.

</code></pre>

**Anything else relevant?**

Nope, keep doing this good job :+1:

**Comment by alxhub** [comment]
Confirmed as reported - this should be a fairly straightforward issue to fix. It's funny, I never thought about the behavior of the unsubscribe hook _after_ the response is received.

I think normally if `.complete` is called, the unsubscribe hooks don't run, but if someone does `.pipe(take(1))` on the `Observable` for example, then it absolutely would be.

**Comment by tonivj5** [comment]
The teardown logic always is executed (with or without completion), here you have a [demo](https://codesandbox.io/s/great-surf-f7bi5?file=/src/index.ts).

We could use a flag like in the example above, WDYT @alxhub? I could send a PR :smile:
