### ISSUE TITLE
Angular 9: WARNING while build library

### ISSUE THREAD

**Issue by quana2k49** [angular/angular#36534]
+ This is my structure: 
_project
___common ( library )
___app1
___app2

When i build library (common), so many warning like:  

> The basePath "../dist/common/common" computed from baseUrl "..." and path mapping "dist/common/common" does not exist in the file-system. It will not be scanned for entry-points.

How can i slove it? Thanks

**Comment by JoostK** [comment]
The warning was removed in #36525 as it was deemed not actionable.

**Comment by hugoebarboza** [comment]
Hi, thanks for writing back...

I wonder if I need to change something on my code or I need to wait for a new release ?

Thanks very much.

**Comment by petebacondarwin** [comment]
It will be in the next patch release.
