### ISSUE TITLE
Input field binding broken for ß with style uppercase (in Chrome)

### ISSUE THREAD

**Issue by cschwaderer** [angular/angular#36535]
### Description
The German language has the letter `ß` (called "Eszett", see [Wikipedia article](https://en.wikipedia.org/wiki/%C3%9F) ). It is usually considered a "lowercase-only" character and it is common practice to display it as `SS` in uppercase.
The combination of Angular binding, Chrome/Chromium browser and the CSS property `text-transform: uppercase` yields wrong results here.

Consider this code 
```
<input type="text" [(ngModel)]="searchText"/>
<span style="text-transform: uppercase">{{searchText}}</span>

```
now type in a word with `ß` like `Fußball`, expected result would be `FUSSBALL` (and this is what you get in Firefox, for example). However, Chromium and Chrome display `FUSSBALS`

Further observations:

- You have to type. Copy and pasting a word will show correct result.

- The last letter of input binding behaves strange when trying to mark it. I cannot mark `FUSSBALS`, I always get just `FUSSBAL`.

## 🔬 Minimal Reproduction
Link to [Stackblitz](https://stackblitz.com/edit/angular-sir89q)

## 🌍  Your Environment

**Angular Version:** 9.1.0
**Chrome Version:** 81.0.4044.92
**Chromium Version:** 80.0.3987.163

(I don't know if this might be a Chrome bug actually. However, I was not able to reproduce it in vanilla JavaScript without Angular.)

**Comment by petebacondarwin** [comment]
This is a bug in Chrome and not related to Angular. See https://bugs.chromium.org/p/chromium/issues/detail?id=27616
