### ISSUE TITLE
Elements stackblitz demo broken

### ISSUE THREAD

**Issue by umdstu** [angular/angular#36532]
# 📚 Docs or angular.io bug report

### Description

Documentation for Elements links to demo https://stackblitz.com/angular/jlyveeeexyg which does not work.

### What's the affected URL?**
https://angular.io/guide/elements

### Reproduction Steps**
Visit https://angular.io/guide/elements, click `live example`. Try to use the demo (Click `show as element`)

### Expected vs Actual Behavior**
Expected: The Element is rendered.
Actual: Error

## 🔥 Exception or Error
<pre><code>
Error in /turbo_modules/@angular/elements@9.0.7/bundles/elements.umd.js (590:51)
Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
</code></pre>

### Browser info
Chrome 80.0.3987.149 macOS

**Comment by gkalpak** [comment]
This is because StackBlitz uses the UMD bundles (instead of the ES2015 ones), so you need a polyfill.
You can add this at the bottom of `src/polyfills.ts` (and also install the dependency):

```ts
import '@webcomponents/custom-elements/src/native-shim';
```

##
Submitting a fix. Thx for reporting, @umdstu :+1:

**Comment by umdstu** [comment]
I love it when they're easy! Thanks for the feedback on the issue and the quick work.
