### ISSUE TITLE
Feature Request: New unbounded @Query type 

### ISSUE THREAD

**Issue by typotter** [angular/angular#3657]
@Query searches the light DOM tree for matching nodes. @ViewQuery searches the component's view for matching nodes.

Consider the case where there are many nodes on the page of a given type. In order to build a Tree model of these components, unbounded parent injection can be used to build the tree from the bottom-up, however, building the tree is not possible with child injection, as deeply view-nested components are not reachable by @ViewQuery.

Consider adding a new type of query which will descend the entire view tree. To optimize, the query can stop descending at the first instance, since that first instance can inject its own children, and so on, down the tree.

**Comment by PascalPrecht** [comment]
Aren't component's views supposed to be implementation detail of a
component, so outer boundaries shouldn't see components inside a
component's view?
Because then the current behavior seems just right.

**Comment by typotter** [comment]
Ancestral Injection is unbounded, though - this would be the compliment to that.

**Comment by mhevery** [comment]
I agree with @PascalPrecht this is an implementation detail, and will not be supported. I don'
