### ISSUE TITLE
style(core): change development mode console message

### ISSUE THREAD

**Issue by MikeOne** [angular/angular#36570]
The message can be improved by removing the unneeded ‘the’ (x2).

Before:
Angular is running in the development mode. Call enableProdMode() to enable the production mode.

After:
Angular is running in development mode. Call enableProdMode() to enable production mode.

I will do a PR for this issue shortly.

**Comment by Achilles1515** [comment]
I've always thought it would be nice to include which rendering engine is in use. Something like:

Angular is running in development mode **with Ivy enabled**. Call enableProdMode() to enable production mode.
