### ISSUE TITLE
How to solve StaticInjectorError in angular?

### ISSUE THREAD

**Issue by imbichitra** [angular/angular#36572]
Hi all
i develop an angular app  that work fine in developing mode but when i build for production by the command  **ng build --prod** and deploy to nginx server and when click an button i user **routerLink** to navigate to another page then it shows below error.
```
ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(i)[it -> t]: 
  StaticInjectorError(Platform: core)[it -> t]: 
    NullInjectorError: No provider for t!
NullInjectorError: StaticInjectorError(i)[it -> t]: 
  StaticInjectorError(Platform: core)[it -> t]: 
    NullInjectorError: No provider for t!
```
But all other **routerLink**  are work fine only one **routerLink**  is not work and shows above error .

Heare are **devDependencies**

> "@angular-devkit/build-angular": "~0.800.0",
    "@angular/cli": "~8.0.1",
    "@angular/compiler-cli": "~8.0.0",
    "@angular/language-service": "~8.0.0",
    "@types/node": "~8.9.4",

Thanks in advance.

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
