### ISSUE TITLE
Angular 9: WARNING while build project

### ISSUE THREAD

**Issue by hugoebarboza** [angular/angular#36579]
Hi,

When I build, so many warning like, around 100.

> WARNING in The basePath "C:/xampp/htdocs/odisdkp/node_modules/core-js/proposals/reflect-metadata" computed from baseUrl "C:/xampp/htdocs/odisdkp" and path mapping "node_modules/core-js/proposals/reflect-metadata" does not exist in the file-system. It will not be scanned for entry-points.

How can I solve it? Thanks.

**Comment by petebacondarwin** [comment]
Duplicate of #36534
