### ISSUE TITLE
Unable to load schema from 'node_modules\@angular\cli\lib\config\schema.json': ENOENT: no such file or directory, open 'node_modules\@angular\cli\lib\config\schema.json'.(768)

### ISSUE THREAD

**Issue by harish1995** [angular/angular#36575]
{
 "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "defaultProject": "app",
  "newProjectRoot": "projects",
  "projects": {
    "app": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {},

**Comment by JoostK** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
