### ISSUE TITLE
Unable to load schema from 'node_modules\@angular\cli\lib\config\schema.json': ENOENT: no such file or directory, open 'node_modules\@angular\cli\lib\config\schema.json'.(768)

### ISSUE THREAD

**Issue by harish1995** [angular/angular#36585]
I have deleted node_module and install it again, but after updating project, it giving me a error at angular.json. The error is Unable to load schema from  
"$schema": "./node_modules/@angular/cli/lib/config/schema.json". 
please help  me how to resolve this issue, is there any option to recreate new angular.json file.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Please open cli's related issues in its [repo](https://github.com/angular/angular-cli), **respecting** the issue template.
