### ISSUE TITLE
(lib) (lang)  ngx-share-button' is not a known element 

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#36581]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/...

### Is this a regression?

 Yes, the previous version in which this bug was not present was: no idea

### Description
I have created small library and included in my project it works perfectly no compilation error.
but in vscode i always get this
```
ngx-share-button' is not a known element
```

I already export those components and module from public_api.ts
```
export * from './src/share-button.component';
export * from './src/share-button.module';
```
## 🔬 Minimal Reproduction

Repo with library: https://github.com/indraraj26/angular-lib-issue

Step 1: Clone this repo
Step 2:  npm install 
Step 3: After sometime you will see above error in vscode only no compilation error during ng serve.

## 🔥 Exception or Error
<pre><code>

'ngx-share-button' is not a known element:. 
    If 'ngx-share-button' is an Angular component, 
    then verify that it is part of this module.. 
    If 'ngx-share-button' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas'
     of this component to suppress this message.",

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.1
Node: 10.16.3
OS: win32 x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
ng-packagr                        9.1.0
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
    
</code></pre>

**Anything else relevant?**

![image](https://user-images.githubusercontent.com/23274631/79048949-35c2d900-7c3e-11ea-8fe7-a86276a66e37.png)

**Comment by atscott** [comment]
I wasn't able to reproduce with the latest version of the Language Service. Please update to the most recent version to resolve the problem.

If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
