### ISSUE TITLE
Warning message being shown while building.

### ISSUE THREAD

**Issue by sujithmathewthomas** [angular/angular#36589]
# 🐞 bug report

### Is this a regression?

Yes, the previous version in which this bug was not present was 7.2.16

### Description

Warning message being shown for `ng2-ace-editor` module, while building.

## 🔬 Minimal Reproduction
 Import ng2-ace-module to app.module and try `ng build`. This doesn't break the build. It's just a warning.

## 🔥 Exception or Error
<pre><code>
Warning: Entry point 'ng2-ace-editor' contains deep imports into '/var/www/html/public/UI/v2/node_modules/brace/theme/monokai'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

</code></pre>

## 🌍  Your Environment

Angular CLI: 9.1.1
Node: 10.13.0
OS: linux x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

**Comment by petebacondarwin** [comment]
This is working as expected.

**Comment by sujithmathewthomas** [comment]
So that warning won't cause any problem? Can I just ignore it?

**Comment by petebacondarwin** [comment]
If your application works correctly then you can ignore this warning. It is there to help debug situations where you application is failing due to entry-points being processed in the wrong order. 

Looking at the thing being imported: https://unpkg.com/browse/brace@0.11.1/theme/monokai.js you can see that this has no Angular code and so will not affect build order.
