### ISSUE TITLE
How to create $rootScope in Angular 9

### ISSUE THREAD

**Issue by alex-jss** [angular/angular#36587]
`Angular v. 9.0.5`

In `AngularJS` i used `$rootScope` to pass user data, for example:

````
$rootScope.user = {
id: '4',
username: 'user',
...
};
$rootScope.user.authenticated = true;
````

The data in `$rootScope` was filled in every time a page was opened or updated using a query to `SQL`.

In `Angular 9` i did not find the use of `$rootScope`.
Tell me with what help can this functionality be implemented?

If possible, please show an example of implementation

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
