### ISSUE TITLE
Issue with MatBottomSheet entrycomponent in angular 9 stable version

### ISSUE THREAD

**Issue by actionanand** [angular/angular#36593]
# 🐞 bug report

### Affected Package
MatBottomSheetModule, MatListModule, MatCardModule and keyvalue pipe

### Is this a regression?

Yes, the previous version in which this bug was not present

### Description

MatBottomSheetModule(enrycomponent) is not supporting materials pipes such as keyvalue. It is working when using plane text like "Hello world". It was working in angular 8. I'm facing this problem in angular 9.

**Comment by ericmartinezr** [comment]
Please report Material issues in its repo https://github.com/angular/components/issues :+1:

**Comment by actionanand** [comment]
> Please report Material issues in its repo https://github.com/angular/components/issues

Not only material. It's angular issue. In entry component(angular 9), unable to use keyvalue pipe too.

**Comment by indraraj26** [comment]
Please share minimal repo to reproduce or you can use https://ng-run.com/?open=app%2Fapp.component.ts

**Comment by actionanand** [comment]
> Please share minimal repo to reproduce or you can use https://ng-run.com/?open=app%2Fapp.component.ts

I tested with official example given in material also. It's also not working with angular 9. It has no problem with angular 8. Please try to recreate the same example
https://material.angular.io/components/bottom-sheet/examples

**Comment by Totati** [comment]
[I could not reproduce. ](https://stackblitz.com/edit/angular-vq3tdp)

**Comment by actionanand** [comment]
> [I could not reproduce. ](https://stackblitz.com/edit/angular-vq3tdp)

yes exactly. I too can't reproduce. Entry componnet is not detecting pipes also like keyvalue pipe. Simple HTML fromat is working. It is wonder How angular team did not see this? Anyway we as a developer found this and reported to angular. We hope they will fix this as soon as possible, because the issue is serious.

**Comment by indraraj26** [comment]
This isn't going to fix if you can't provide reproduction.

**Comment by actionanand** [comment]
> This isn't going to fix if you can't provide reproduction.

ok I make it.

**Comment by actionanand** [comment]
Hi all,

It is working when adding the componnet in both the places entrycomponents array and declaration array. I tested at stackblitz. 

Stackbltz editor: https://stackblitz.com/edit/ng-bottom-sheet

App view: https://ng-bottom-sheet.stackblitz.io/

So I close this thread.
