### ISSUE TITLE
 Can't bind to 'ngModel' since it isn't a known property of 'input'. i have imported forms module but still not working, I am using angular 9 

### ISSUE THREAD

**Issue by abdirisakmo** [angular/angular#36602]
Can't bind to 'ngModel' since it isn't a known property of 'input'.
    
    18            [(ngModel)]="user.password

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by AndrewKushnir** [comment]
Hi @abdirisakmo,

It looks like this issue doesn't contain sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

Thank you.
