### ISSUE TITLE
FormControlName not working with Checkboxes Angular 9

### ISSUE THREAD

**Issue by afeef1915** [angular/angular#36603]
This code was working Angular 8.2

But didn't work Angular 9

			<input [id]="field.code" [name]="field.code" [formControlName]="field.code"
			class="form-check-input custom-control-input" type="checkbox"
			value="field.checkbox_values.checked.code" (change)="onChange($event)"
			[checked]="this.field.checkbox_values.checked.code === this.field.value ? true : false"
			/>

			onChange($event) {
			this.form.get(this.field.code).setValue($event.target.checked);

			}

Working  Angular 9 

        <input [id]="field.code" 
			class="form-check-input custom-control-input" type="checkbox"
			value="field.checkbox_values.checked.code" (change)="onChange($event)"
			[checked]="this.field.checkbox_values.checked.code === this.field.value ? true : false"
			/>

I  need to remove formControlName in angular 9 to make it work

Problem is

* all  checkbox are loaded in forloop from API  .

*  Page loads all chdckbox are checked by default.

*  i need when api field is Y then true otherwise unchecked.

*  this code was working Angular 8.2
any suggestion is most welcome.

Thanks.

**Comment by Totati** [comment]
Hi. Checked and formControlName should not be used together. When using formCobtrolName directive you should wrap it in a fromGroup, and set the value through the formGroup. You're mixing reactive forms with template driven forms.

**Comment by afeef1915** [comment]
> Hi. Checked and formControlName should not be used together. When using formCobtrolName directive you should wrap it in a fromGroup, and set the value through the formGroup. You're mixing reactive forms with template driven forms.

Thanks for the answer.

Please can you suggest any code snippet please.

Thank you

**Comment by Totati** [comment]
@afeef1915  
https://angular.io/guide/reactive-forms#grouping-form-controls 
https://angular.io/api/forms/CheckboxControlValueAccessor

**Comment by AndrewKushnir** [comment]
Hi @afeef1915, I'm closing this ticket as resolved (based on @Totati replies). Please reopen if the problem still exists. Thank you.
