### ISSUE TITLE
IVY Lazy loaded component is not well compiled

### ISSUE THREAD

**Issue by mboughaba** [angular/angular#36604]
# 🐞 bug report

### Affected Package
@angular/compiler?

### Is this a regression?
Lazy loading component via import is new in IV

### Description

 Directives such as ngIf, ngClass, ngStyle don't work in lazy loaded component.
`core.js:12626 Can't bind to 'xxx' since it isn't a known property of 'xxx'.`

The only binding I managed to get it working is something like: `[style.color]="color"`

## 🔬 Minimal Reproduction
<https://stackblitz.com/edit/angular-zyp3wm?file=src%2Fapp%2Flazy.component.ts>

Please use the sample outside of stackblitz, it seems lazy loading component is not working at all, maybe bundle is blocked or so.

## 🔥 Exception or Error (Warning)
<pre><code>
Can't bind to 'ngIf' since it isn't a known property of 'div'.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
```
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.1
Node: 12.13.1
OS: win32 x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
```

**Comment by JoostK** [comment]
This is working as expected. The `LazyComponent` is not declared in any NgModule, so it doesn't have access to any declarations.

**Comment by mboughaba** [comment]
thx JoostK, I've also tried with a module and got the same error.

```
  async lazy() {
    this.viewContainerRef.clear();
    const module = await import("./lazy/lazy.module");
    const LazyComponent = module.LazyModule.components["lazy"]
    this.viewContainerRef.createComponent(
      this.cfr.resolveComponentFactory(LazyComponent)
    );
  }
```

any thought of this?
