### ISSUE TITLE
Bad template type checking in `*ngFor`

### ISSUE THREAD

**Issue by ranma42** [angular/angular#36609]
# 🐞 bug report

### Affected Package

I do not know which angular package causes the issue.
I believe it depends on either the definition of `ngFor` (`@angular/core`) or on the transpilation process.

### Is this a regression?

 No

### Description

The [Template type checking guide](https://angular.io/guide/template-typecheck#strict-mode) states that the compiler should be able to type-check `ngFor` when using `strictTemplateTypeCheck`:
>Infers template context types where configured (for example, allowing correct type-checking of NgFor).

The reproduction seems to show otherwise. Specifically, when both "full checking" or "full+strict checking" is enabled, the compiler errors out on valid code as if the type of the iteration variable was not inferred (see the error in the section below).

Conversely, when only doing "strict checking" (without "full checking") the compiler accepts invalid code, which seems to contradict the docs: 

> Strict mode is a superset of full mode, and is accessed by setting the strictTemplates flag to true. This flag supersedes the fullTemplateTypeCheck flag. In strict mode, Angular version 9 adds checks that go beyond the version 8 type-checker.

## 🔬 Minimal Reproduction

I have been unable to tweak the compiler settings on stackblitz, so I created a repo containg the reproduction.

https://github.com/ranma42/strict-ngfor/commits/master

## 🔥 Exception or Error
<pre><code>ERROR in src/app/app.component.html:3:31 - error TS7053: Element
implicitly has an 'any' type because expression of type 'any' can't be
used to index type '{ x: string; }'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 9.1.1
Node: 12.16.0
OS: darwin x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
The flag is called `strictTemplates`, not `strictTemplateTypeCheck`.

**Comment by ranma42** [comment]
Oops, my bad! Sorry for the noise.
