### ISSUE TITLE
TestBed.overrideModule affects other tests

### ISSUE THREAD

**Issue by kalsowerus** [angular/angular#36619]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core/testing

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.2.13

### Description

All test cases after a call to `TestBed.overrideModule` seem to be affected by its modifications.

In the provided Example project I have two tests: `one.spec.ts` and `two.spec.ts`. Both create an instance of their own component which both contain a `TestComponent`. In `one.spec.ts` I replace `TestComponent` with a Mock using `overrideModule`. If `one.spec.ts` is executed first by the test runner, `two.spec.ts` also uses the Mock component.

Additionally this example also does not work if `two.spec.ts` is executed first. In that case the `overrideModule`-call seems to be ignored.

I cannot say for sure wether this is a problem with Angular or Karma. If you think I should open an issue on Karma, please let me know.

## 🔬 Minimal Reproduction

https://github.com/kalsowerus/repro-app

The `TestComponent` I mentioned earlier prints `'test'` in its `ngOnInit()`, while the mock component inside `one.spec.ts` prints `'mock'`. To see the problem just `npm install` and then `ng test`. The exact command I used to execute the tests is `ng test --browsers ChromeForWSL --watch=false`. `ChromeForWSL` being a custom Launcher based on Chrome which disables the "VizDisplayCompositor"-feature since that does not seem to work in a WSL (Windows subsystem for Linux) environment.

The expected result would be seeing both `'test'` and `'mock'` in the console once in any order. But depending on the execution order either of them are printed twice while the other one is not printed at all.

## 🔥 Exception or Error
No exception or error

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.1
Node: 12.14.0
OS: linux x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment]
Hi @kalsowerus,

Thanks for reporting the issue and providing a repro (this is super helpful!).

I was able to reproduce the problem, will perform further investigation and will keep this thread updated.

Thank you.

**Comment by AndrewKushnir** [comment]
Hi @kalsowerus,

I've created a [PR with proposed fix](https://github.com/angular/angular/pull/36649). I tested the fix using the repro that you provided and it seems to be working correctly now. If you get a chance, it'd be great if you could help test this fix with your real app to see if the original problem is also resolved.

To test your app with the changes from PR #36649, you can follow an instruction in [this document on how to use PR artifacts](https://github.com/angular/angular/blob/master/docs/DEVELOPER.md#archives-for-each-package). An archive with updated `@angular/core` package that contains changes from the PR is available [here](https://686837-24195339-gh.circle-artifacts.com/0/angular/core-pr36649-a2577b6a2d.tgz) (please make sure you update other `@angular` packages to `9.1.2` to avoid version conflicts). **Note**: the mentioned archive with updated `@angular/core` package is for **testing purposes only** and not suitable for production usage (that archive will be removed once PR is closed).

Thank you.

**Comment by kalsowerus** [comment]
Hi @AndrewKushnir,

Thank you very much for your response. I ran my tests a few times with your PR artifact and could not reproduce the original error. It seems to be working fine now.

Can I expect to see this fix in 9.1.3?

Thank you.

**Comment by AndrewKushnir** [comment]
Hi @kalsowerus, thanks for your help with testing the change 👍I expect the change to be included into `9.1.3` or `9.1.4` release. Thank you.
