### ISSUE TITLE
Angular Ivy

### ISSUE THREAD

**Issue by sushilchaurasia1990** [angular/angular#36614]
I was working on angular 9 migration and find one issue related to IVY.
I am using custom directive in which I am injecting NgModel and trying to access this.ngModel.viewModel property which works in angular 9 if I set enableIvy to false but when enableIvy is set to true which is default angular 9 behavior viewModel property in not available inside this.ngModel.

**Comment by indraraj26** [comment]
Please provide minimal repo to reproduce and along with that please follow issue template.

**Comment by AndrewKushnir** [comment]
Hi @sushilchaurasia1990,

Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

Thank you.
