### ISSUE TITLE
Can't download image on disk since Angular 9

### ISSUE THREAD

**Issue by Araknos** [angular/angular#36624]
Hello,

After migrating my application from Angular 7 to Angular 9 downloading images on disk isn't working anymore:

```
toDataURL(url) {
    return fetch(url).then((response) => {
            return response.blob();
        }).then(blob => {
            return URL.createObjectURL(blob);
        });
}

async download() {
        const a = document.createElement("a");
        a.href = await toDataURL("http://serverpath/images/50.jpg");
        a.download = "";
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
}
```
Note: I use DomSanitizer to load these images from server with the following (and it's working fine):

```
const objectURL = URL.createObjectURL(blob);
const img = this.sanitizer.bypassSecurityTrustUrl(objectURL);
```

**Comment by pkozlowski-opensource** [comment]
Can you please provide a minimal stackblitz /  GitHub repository reproduction? There's not enough information here for us to investigate.

**Comment by Araknos** [comment]
Forgot to add I got the following error in the console:

> GET http://localhost:4200/SafeValue%20must%20use%20[property]=binding:%20blob:http://localhost:4200/b0d55237-0f87-4654-afaa-19a0b50e47de%20(see%20http://g.co/ng/security 404 (Not Found) zone.js:1118

Here is a stackblitz but it's working:
https://stackblitz.com/edit/angular-mqbsjt

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
