### ISSUE TITLE
Better error reporting for [(ng-model)]="exp" syntax

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#3662]
This `[(ng-model)]="exp" ` will work while `([ng-model])="exp" ` will fail silently. We should either throw or allow both forms (not sure if it makes sense).

Related: #3645 (should be done together)

**Comment by PascalPrecht** [comment]
For consistency I'd also rather vote for throwing an error instead of allowing both syntaxes.

**Comment by mhevery** [comment]
We should throw on any attribute which is not valid. I think in this case this gets interpreted as event called `[ngModel]` so we should have some check which say that event names must be alphanumeric.

**Comment by mhevery** [comment]
cc: @pkozlowski-opensource

**Comment by pkozlowski-opensource** [comment]
OK, makes sense. I will start introducing event checks as part of the schema support, we could have some basic event name checks for the start.

Will take care of this one (or can help out if anyone from the community is interested!)

**Comment by pkozlowski-opensource** [comment]
Hmm, digging into it a bit more it seems like HTML spec are putting very little restrictions on the possible event names.... If I understand correctly there is nothing that would prevent one from creating a custom event named `[foo]` and in this sense `([foo])="actionExp()"` should be valid...

Another way of looking into it is that with custom directive events one can only declare events that are valid JS field names. So maybe we should be more restrictive here and stick to the lowest-common-denominator

**Comment by PascalPrecht** [comment]
:+1: on creating custom restrictions specific to Angular. I think this shouldn't be a problem since prolly no one would come up defining event names that start with `[` or `(` anyways..

**Comment by yanivefraim** [comment]
@pkozlowski-opensource I would love to get this as my first issue here (: 
But I'll need some help with that, if you can. 10x!

**Comment by PascalPrecht** [comment]
@yanivefraim maybe you can collaborate with @cironunes. Looks like he started working on this already.

@pkozlowski-opensource or did you also already start with sth?

**Comment by yanivefraim** [comment]
@cironunes' @pkozlowski-opensource - can I help with this one? (I'm looking to get in and start contributing to this project (:

**Comment by mhevery** [comment]
dup of #4737
