### ISSUE TITLE
Typos in the Step-by-Step guide

### ISSUE THREAD

**Issue by DominikPalo** [angular/angular#3663]
I found some typos in the Step-by-Step guide:

3: User Input (https://angular.io/docs/js/latest/guide/user-input.html) in the Final Code snippet:
Line 10: `*ngfor`-> `*ng-for`
Line 18: `NIf` -> `NgIf`

Also in chapter 2: Displaying data (https://angular.io/docs/js/latest/guide/displaying-data.html) there is missing a line `bootstrap(DisplayComponent);` on the end of the final TypeScript snippet

**Comment by khyamay** [comment]
there is already a pr for typos for *ngfor and Nif

**Comment by vicb** [comment]
see https://github.com/angular/angular.io/pull/161
