### ISSUE TITLE
Service Worker : Vary cache fails

### ISSUE THREAD

**Issue by gideruette** [angular/angular#36638]
# 🐞 bug report

### Affected Package
@angular/service-worker

### Is this a regression?
Probably never worked

### Description
When a ressource is provided by a server with "Vary" Header set, even if the request is cached with Vary header, the SW tries to prefetch it again when reload. So it crashes offline mode.

It seems that the presence of any Vary header prevent cache to find ressource. 
Maybe ngsw-workerjs can be generated with ignoreVary option in cache.match calls :
https://developers.google.cn/web/updates/2016/09/cache-query-options?hl=zh-cn

![image](https://user-images.githubusercontent.com/15626856/79355898-91db7500-7f3e-11ea-8f82-cae02aedc61b.png)
When refresh, tere those ressources are loaded twice : the SW should'nt try to pefetch them again.

When going offline :
![image](https://user-images.githubusercontent.com/15626856/79355955-a455ae80-7f3e-11ea-9fbe-42543df3122c.png)

## 🔬 Minimal Reproduction
ng new sw-vary-issue
cd sw-vary-issue
ng add @angular/pwa

Build and serve it with Vary header. Go offline (to test PWA)
(Github repo WIP)

## 🔥 Exception or Error
`ngsw-worker.js:615 Uncaught (in promise) Error: Response not Ok (fetchAndCacheOnce): request for http://localhost:8080/suit/suit-mobile/runtime-es2015.1eba213af0b233498d9d.js returned response 504 Gateway Timeout
    at PrefetchAssetGroup.<anonymous> (ngsw-worker.js:615)
    at Generator.next (<anonymous>)
    at fulfilled (ngsw-worker.js:160)`

## 🌍  Your Environment

**Angular Version:**

Angular CLI: 9.1.1
Node: 12.13.0
OS: win32 x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.1
@angular-devkit/build-angular      0.901.1
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.1
@angular-devkit/core               9.1.1
@angular-devkit/schematics         9.1.1
@angular/cdk                       9.2.0
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.2.0
@angular/material-moment-adapter   9.2.0
@ngtools/webpack                   9.1.1
@schematics/angular                9.1.1
@schematics/update                 0.901.1
rxjs                               6.5.5
typescript                         3.7.5
webpack                            4.42.0

**Anything else relevant?**
Works on Firefox

**Comment by gkalpak** [comment]
This will be fixed by #34663.
