### ISSUE TITLE
(router): routerLink is not working in shared module and strict check

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#36636]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 Yes, the previous version in which this bug was not present was: no idea

### Description
It has one feature-module where i have imported shared/custom-card.module in order to use custom-card component which is in shared/custom-card.

Reproduction: https://ng-run.com/edit/kiihOLV6qo1YIfMeJ6uA?open=app%2Ffeature-module%2Fmy-feature%2Fmy-feature.component.html

Parent Routing: 
```
const appRoutes = [{
   path: '', redirectTo: '/home', pathMatch: 'full' 
}, 
{
  path: 'home',
  loadChildren: () =>
     import('./feature-module/feature-module.module').then((c) => c.FeatureModuleModule),
  },
  {
  path: 'test',
  redirectTo: '/home'
  }
]

```
feature component.html: 
```
<app-custom-card></app-custom-card>
```

Issue: 
As we all know we can't import routerModule everywhere either it has to be forRoot for oneTime  and forChild depend upon feature module. I would expect routerLink should work as we are already importing this module in feature-module where we have RouterModule.forChild. Do we really need to import RouterModule everywhere in shared feature module in order to use router feature?

on shared/custom-card.component.html 
```
<!-- if you import routerModule in custom-card.module.ts then this routerlink will work -->
<div class="card" routerLink="/test">My Awesome card<div>
```
Structure: 
![image](https://user-images.githubusercontent.com/23274631/79351824-c3603a80-7f56-11ea-8e91-fc49d86623a6.png)

Output: 
![image](https://user-images.githubusercontent.com/23274631/79353243-6b2a3800-7f58-11ea-954d-e43e9793a86c.png)

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
9.1.1
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
This is working as expected.

NgModules have two responsibilities:
1. Defining the compilation scope of components using `declarations` and `imports`.
2. Configuring the injector by means of providers using `providers` and `imports`.

The `forRoot`/`forChild` idiom is about responsibility 2: it registers providers for a particular context. This is relevant as feature modules may not want to register providers for services that should only occur in the root injector.

In your example however, for the component to have access to the `routerLink` directive it must import `RouterModule` to satisfy responsibility 1. Importing `RouterModule` does not introduce any providers, as those are only included when using `forRoot`/`forChild`.

More information on the responsibility of NgModules can be found in https://angular.io/guide/module-types. There's five kinds described there as a distinction is made on a functional level, but technically only the two responsibilities described above are what matters.
