### ISSUE TITLE
Annotation for Auto Creation of Singleton Service

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular#36631]
Suppose we are doing this in `app.component.ts`

```
  constructor(assets: AssetsService) {}
```

The `AssetsService` is not actually used.  We just rely on the constructor to fetch assets like SVG custom icons etc.

It would be nice not to have to inject it on boot in order to get the constructor to run.  Something like:

```
@AutoConstruct()
export class AssetsService {

  constructor(
    private matIconRegistry: MatIconRegistry,
    private domSanitizer: DomSanitizer) {
    {
      this.matIconRegistry.addSvgIcon(
        "fsalpha",
        this.domSanitizer.bypassSecurityTrustResourceUrl(logoURL))
    }
  }
}



```

**Comment by pkozlowski-opensource** [comment]
I think that we've got other means of achieving it today, without changing how DI works:
* code executed before application starts (but you wouldn't have access to `DomSanitizer` in there)
* a constructor in [@NgModule](https://angular.io/guide/ngmodules)
* [APP_INITIALIZER](https://angular.io/api/core/APP_INITIALIZER)

Having said all the above, I do recognise a need / use-case here - people often need to do some, one time initialisation logic before an app starts (ex. to fetch some data from a server etc.). The mentioned initialisation logic often needs access to services from DI. It almost sounds like we want to boot-up a stand-alone injector, execute some logic using this injector and only _then_ bootstrap an application.

**Comment by JoostK** [comment]
Just as a note here: a proposal like `AutoConstruct` is problematic when tree-shaking is considered. If there's no reference to the class, but it just acts as bootstrap code, then it will be eligible for tree-shaking so your bootstrap code would not be executed anymore. To overcome this, the service would have to be imported/provided from an NgModule somewhere.

NgModules themselves are already eager, so you can rely on their constructor to execute when the injector is created.

**Comment by fireflysemantics** [comment]
Is it possible for the Angular compiler to search for classes with an `@AutoConstruct` annotation and exclude them from tree shaing?

**Comment by JoostK** [comment]
> Is it possible for the Angular compiler to search for classes with an `@AutoConstruct` annotation and exclude them from tree shaking?

The Angular compiler does not do tree-shaking itself, it's tools such as Terser that operate as part of the build pipeline. AFAIK there's no annotation to prevent tree-shaking from occurring.

But even if there were, the compiler may not even _find_ the class if it's not referenced from somewhere in the program _and_ not listed as input to the program, as the whole source file would not ever be loaded. That would be highly likely to occur as the compiler configuration usually starts from some entry-point source file. When the `@AutoConstruct` class is not part of the program at all, it would be a nightmare to debug why your bootstrap code wouldn't run.

**Comment by fireflysemantics** [comment]
Can Angular inject it for us as part of the compilation process?

So if it sees a class with this annotation:

```
@AutoConstruct()
export class AssetsService { ...

```

It will inject an instance of it into the component that is the `bootstrap` component:

```
bootstrap: [AppComponent]
```

We don't see this when looking at the Typescript compile time code, but it's part of the compiled runtime code?

**Comment by fireflysemantics** [comment]
More intelligent wiring in general would be nice. 

For example for the AssetService included by the original example here we need the `HttpClient`.  If we start the application without having included  the `HttpClientModule` the application fails to start.  The compilation fails.

But we are not explicitly using the `HttpClientModule` in code.  We just have to remember to include it.

If would be nice if Angular would first simply scan annotations and determine it's build structure from there.

Combine tree shaking and annotations to create the picture of what is needed in the runtime application.

**Comment by pkozlowski-opensource** [comment]
> For example for the AssetService included by the original example here we need the HttpClient. If we start the application without having included the HttpClientModule the application fails to start. The compilation fails.

I see this use-case (or a variant of it) in the wild all the time. When I was thinking about this use-case I was leaning in the direction of creating a DI container _without_ bootstrapping an app. Such DI container could have HttpClientModule, your `AssetService` and anything else needed to fetch data _before_ bootstrapping an app. If we had such mechanism we wouldn't need change anything about DI injection.

**Comment by fireflysemantics** [comment]
Indeed it feels like we are wiring in certain things that should be part of the container quite often.

If they are part of the container, and not used, then Angular's production build should be able to remove code that is not used, by bundling the code to a more lightweight production container.

**Comment by fireflysemantics** [comment]
Another thought along these lines of "Module Less" only "Annotation Blueprinted" applications is that it would be nice to have a cleaner router.

When creating a router we would just do:

```
@Router 
```

And Angular would see that it's a router and use that `Router` instance as the router.

We never call `forRoot` etc.

**Comment by fireflysemantics** [comment]
Another point of view is that Angular / Angular tooling should be able to construct the application efficiently so that when we use something Angular just picks up on the fact that we are using it.

So for example if we are using `MatIconRegistry`, and that has dependencies like `HttpClient`, then that wiring should be automatic.

If we are using `HttpClient` then the `HttpClientModule` should automatically be brought in.

So if the `HttpClientModule` were effectively part of the `HttpClient` via an annotation that describes the module, then this becomes automatic.

Just thinking out loud here ...

**Comment by fireflysemantics** [comment]
Another experiment that I think would yield insight is writing a preprocessor that:
- Creates a `wiring.ts` file
- The `wiring.ts` contains the blueprint for how Angular thinks the application should be wired

So in this context Angular would see the `@AutoConstruct` class, and describe it as part of something that should be injected into the main `AppComponent` class (The class that is bootstrapped).

Also same thing for the `@Router` annotation.  Angular could see a class annotated like that and include it in the `wiring.ts` blueprint.

This allows the Application Designer to review the wiring design without having to go through and manually add each class to the `declarations`...

**Comment by fireflysemantics** [comment]
Summarized some of the ideas here:

https://medium.com/@ole.ersoy/bluestreak-angular-dependency-injection-blueprint-preprocessor-cbc3ae025f73

I'll just add more there that way I can organize it better.

**Comment by fireflysemantics** [comment]
I was doing this scenario just now and remembered a detail that I wanted to be clear about.  Suppose we have an asset service like this:

```
import { Injectable } from '@angular/core';
import { DomSanitizer } from "@angular/platform-browser";
import { MatIconRegistry } from '@angular/material/icon';
import { SVG } from '@fireflysemantics/constants'

@Injectable({
  providedIn: 'root'
})
export class AssetService {

  constructor(
    private matIconRegistry: MatIconRegistry,
    private domSanitizer: DomSanitizer) {
    {
      this.matIconRegistry.addSvgIcon(
        SVG.GOOGLE_LOGO.name,
        this.domSanitizer.bypassSecurityTrustResourceUrl(SVG.GOOGLE_LOGO.url));
    }
  }
}

```

If we just copy that to another project that has Angular Material installed, we still get errors if the `HttpClientModule` is not declared.   So it would be nice if Angular CLI auto detects this and generates the corresponding dependency injection structure along with making that annotation work.

It would be nice to have that auto detected and just done for us within the application.

**Comment by fireflysemantics** [comment]
This ended being a pretty good workaround for now for me:
https://developer.fireflysemantics.com/tasks/tasks--angular--creating-a-self-initializing-material-icons-svg-assets-service

**Comment by fireflysemantics** [comment]
It looks like version 12 of Angular no longer allows the injection of a service within a module constructor.  I now get errors like this:

```
fireflysemantics-assets.js:20 Uncaught ReferenceError: Cannot access 'AssetService' before initialization
    at Module.3135 (fireflysemantics-assets.js:20)
    at __webpack_require__ (bootstrap:19)
    at Module.6747 (app.component.html:436)
    at __webpack_require__ (bootstrap:19)
    at Module.4431 (environment.ts:16)
    at __webpack_require__ (bootstrap:19)
    at __webpack_exec__ (main.js:527)
    at main.js:528
    at Function.__webpac
```

**Comment by JoostK** [comment]
@fireflysemantics that looks like an ordering issue, possibly related to the Webpack 5 update in the CLI (assuming you haven't changed any other code). Injecting services into a module should still be possible in v12. In any way, this seems unrelated to this issue so please open a new one with a minimum reproduction.

**Comment by dylhunn** [comment]
We're not implementing this on its own, but stay tuned for the next Standalone Components RFC, which may cover your use case re eager instantiation.
