### ISSUE TITLE
i18n - please support Json format

### ISSUE THREAD

**Issue by spock123** [angular/angular#36644]
# 🚀Support JSON for i18n

I know this topic has been suggested before, but I feel it's time to address it again as it's 2020 and the situation has not improved.

In order to use i18n translations, it is required to use translation files with the xliff format. This all well and all, but all tutorials/documents neglect to mention the tiny detail that no proper free editor or tool seems to exist. 

This means that unless you want to pay 50-100 $ a month to a service like phrase.com, you are supposed to manually edit the xliff xml files by hand.

This is not possible when a project has 5+ translation strings.  

Would it be a suggestion to look into supporting nested JSON for translations? I know there would be limitations such as placeholders, gender/plural etc, but for the 99% of developers who live fine with this limitation, it would be really beneficial.

The current official policy seems to be to use xliff, but it is not a practical solution for most people as, editing raw xml files is not something for a sane person. 

Googling for free tools leads to abandoned xliff editor projects last updated in 2014-ish. Not an option.

So please, (re-)consider: support simple json/nested-json files for i18n translations.

PS: I know plenty of 3rd party runtime solutions exist using json, but I'm really not much for degrading performance etc., I want to use the compile-time solution.

Please help

Thank you for a great work

**Comment by javier-vilares** [comment]
Hi, have you tried [https://poedit.net](url)? I think this is the tool you are looking for :)

**Comment by spock123** [comment]
Hi @javier-vilares I have been using it but t's not so practical for the free tier. Files have to be downloaded manually, there is no api. 

I just wish there was a simpler way, like a simple json file format.

**Comment by ocombe** [comment]
The Locl project lets you use `json` with `@angular/localize` if you want https://github.com/loclapp/locl

That being said, it's not going to be free once it's ready for v1 (currently in RC).
The price will be more like $100/year than each month, which might make it more affordable for you.
Also it's free for open source projects.

**Comment by petebacondarwin** [comment]
I hope to land https://github.com/angular/angular/pull/36795 into master, and then get CLI to integration this parser into its localization process. But before this will be of any use we will need to land https://github.com/angular/angular/pull/32912 along with an ARB serializer.

**Comment by petebacondarwin** [comment]
Angular CLI now supports both simple JSON and ARB formats.
