### ISSUE TITLE
Uncaught TypeError: Cannot read property 'get' of undefined uncurryThis(Object.getOwnPropertyDescriptor(TypedArrayPrototype, Symbol.toStringTag).get)

### ISSUE THREAD

**Issue by kathpal** [angular/angular#36647]
If i use package-lock.json ,then this error is not coming.When package-lock is not used then this error comes.

using the below babel configuration in package.json:- 
"@babel/core": "7.9.0",
"@babel/helpers": "^7.5.5",
"@babel/runtime": "^7.5.5",
"@babel/preset-env": "7.9.5",

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by kathpal** [comment]
Got it. It was due to the version of assert being used.
Downgrading the assert version to 1.4.* series.I am not using assert directly though some dependencies are using it and upgrading all dependencies cause it to change to 1.5.0 
Added 1.4.1 as this was being picked up earlier ,solved the issue.
