### ISSUE TITLE
(click) not work properly

### ISSUE THREAD

**Issue by olegstan** [angular/angular#3665]
Hello. I have html like that.
        &lt;li&gt;&lt;a class="btn btn-link btn-small current" (click)="sort($event, 'position')"&gt;&lt;span&gt;Some text&lt;/span&gt;&lt;/a&gt;&lt;/li&gt;

When I click on span there no effect. Click not work on child tags. Where magic?

**Comment by alexpods** [comment]
Use (^click) syntax.

From the docs [here](https://github.com/angular/angular/blob/ff1b110ae15962f01b9b3c4d42fca8f20bab8b55/modules/angular2/docs/core/01_templates.md):

> By default, angular only listens to the element on the event, and ignores events which bubble. To listen to bubbled events (as in the case of clicking on any child) use the bubble option ((^event) or on-bubble-event) as shown below.
