### ISSUE TITLE
ng build issues during production , @err=> Field 'browser' doesn't contain a valid alias configuration

### ISSUE THREAD

**Issue by sayancoding** [angular/angular#36657]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please file any Angular CLI issues at: https://github.com/angular/angular-cli/issues/new

For the time being, we keep Angular CLI issues in a separate repository.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Got an big error when i trynna hit '

> ng build --prod

' it's suffering and stuck me up.
please give suggestive some to fix this problem 

here i use **firebase tailwindCSS and angular 8**

### like:Field 'browser' doesn't contain a valid alias configuration

[errorLogs.txt](https://github.com/angular/angular/files/4486481/errorLogs.txt)
_It just like show me again and again 
please help me resolving it. I just stuck_

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
