### ISSUE TITLE
Angular SSR

### ISSUE THREAD

**Issue by hugoebarboza** [angular/angular#36664]
Hi,

I build with (SSR) with Angular Universal, I get the below error. What can I do to fix it ?
*********************************************************************
ERROR in ./server.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\xampp\htdocs\odisdkp\server.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
at AngularCompilerPlugin.getCompiledFile (C:\xampp\htdocs\odisdkp\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:933:23)
at plugin.done.then (C:\xampp\htdocs\odisdkp\node_modules\@ngtools\webpack\src\loader.js:41:31)
at process._tickCallback (internal/process/next_tick.js:68:7)
**********************************************************************

Package.
@angular/animations                ^9.1.1  →  ^9.1.2
@angular/common                    ^9.1.1  →  ^9.1.2
@angular/compiler                  ^9.1.1  →  ^9.1.2
@angular/core                      ^9.1.1  →  ^9.1.2
@angular/forms                     ^9.1.1  →  ^9.1.2
@angular/localize                  ^9.1.1  →  ^9.1.2
@angular/platform-browser          ^9.1.1  →  ^9.1.2
@angular/platform-browser-dynamic  ^9.1.1  →  ^9.1.2
@angular/platform-server           ^9.1.1  →  ^9.1.2
@angular/router                    ^9.1.1  →  ^9.1.2
@angular/service-worker            ^9.1.1  →  ^9.1.2

Best regards,
Hugo

**Comment by gkalpak** [comment]
The SSR guide is a little outdated wrt v9. This will be fixed by #36483.

Until #36483 is merged, you can use the PR preview: https://pr36483-928dd02.ngbuilds.io/guide/universal
<sub>(Once the PR is merged, the preview will be deleted, but you will be able to see the guide on angular.io as usual.)</sub>
