### ISSUE TITLE
Angular SSR - server.ts is missing from the TypeScript compilation

### ISSUE THREAD

**Issue by hugoebarboza** [angular/angular#36666]
Hi,

The seme issues following this [guide ](https://pr36483-928dd02.ngbuilds.io/guide/universal)

I build with (SSR) with Angular Universal, I get the below error. 

1) What can I do to fix it ? 
2) Where should I store the server.ts file ?

***************************************************************************************
ERROR in ./server.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\xampp\htdocs\odisdkp\server.ts is missing from the TypeScript compilation. 
Please make sure it is in your tsconfig via the 'files' or 'include' property.
at AngularCompilerPlugin.getCompiledFile (C:\xampp\htdocs\odisdkp\node_modules@ngtools\webpack\src\angular_compiler_plugin.js:933:23) at plugin.done.then (C:\xampp\htdocs\odisdkp\node_modules@ngtools\webpack\src\loader.js:41:31)
at process._tickCallback (internal/process/next_tick.js:68:7)

Package.
@angular/animations ^9.1.1 → ^9.1.2
@angular/common ^9.1.1 → ^9.1.2
@angular/compiler ^9.1.1 → ^9.1.2
@angular/core ^9.1.1 → ^9.1.2
@angular/forms ^9.1.1 → ^9.1.2
@angular/localize ^9.1.1 → ^9.1.2
@angular/platform-browser ^9.1.1 → ^9.1.2
@angular/platform-browser-dynamic ^9.1.1 → ^9.1.2
@angular/platform-server ^9.1.1 → ^9.1.2
@angular/router ^9.1.1 → ^9.1.2
@angular/service-worker ^9.1.1 → ^9.1.2

Sincerely,
Hugo Barboza

**Comment by gkalpak** [comment]
@hugoebarboza, can you please add more details on what commands you ran to get these errors? I downloaded the example from the guide, unzipped it and ran `npm install && npm run build:ssr` and everything worked fine.

**Comment by hugoebarboza** [comment]
Hi, 
Now another issue, what a terrible headache.
****************************************************
main.js:646127, throw error;
ReferenceError: navigator is not defined
****************************************************
Best regards,
Hugo

**Comment by gkalpak** [comment]
I'm afraid you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
