### ISSUE TITLE
i don't know it was an issue

### ISSUE THREAD

**Issue by sdbzxsl** [angular/angular#36678]
when <app-child> has  a provider,  <app-inspector> display the contents of the viewProvider,when<app-child> has no provider ,<app-inspector>display the content of root injector  service ,,,,
should it always display the content of the root injector? 

![1](https://user-images.githubusercontent.com/55081162/79520987-a4fb5b80-808a-11ea-9920-ca5317b306b7.JPG)
![2](https://user-images.githubusercontent.com/55081162/79520993-a9c00f80-808a-11ea-89ec-e7815f42bc97.JPG)
![3](https://user-images.githubusercontent.com/55081162/79520996-adec2d00-808a-11ea-9e39-de32933b13c3.JPG)

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please help us process issues more efficiently by filing an
issue using one of the following templates:

https://github.com/angular/angular/issues/new/choose

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by JoostK** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
