### ISSUE TITLE
Renderer2 does not update variable bound with NgModel

### ISSUE THREAD

**Issue by pmarshall111** [angular/angular#36677]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?

No idea.

### Description

When using Renderer2 to set the value on an element, the typescript variable bound via ngModel is not changed.

## 🔬 Minimal Reproduction
https://angular-issue-repro2-thy7sx.stackblitz.io

## 🔥 Exception or Error
n/a

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.7
Node: 12.16.1
OS: linux x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**
No, please let me know what you think.

**Comment by JoostK** [comment]
This is working as designed.

Using `Renderer2` is still doing manual DOM manipulation, while Angular's binding mechanism is designed to reflect data as some view in the browser. Just changing the DOM (the input in your case) will not achieve updating the actual data (`AppComponent.gridSize`) so it will not be reflected in other bindings that show the data.
