### ISSUE TITLE
Feature request: Open links from doc pages in popup or new tab

### ISSUE THREAD

**Issue by jbogarthyde** [angular/angular#36670]
It would improve the user experience for doc pages to open external links in a separate tab, and glossary links in either a separate tab or a popup.

**Comment by daftfox** [comment]
I'll pick this up.

**Comment by Arpan619Banerjee** [comment]
I want to work on this, but this will be my first open source contribution, can u pls guide me how to get the source code, so tht i can set it up in my local and give it a shot!

**Comment by kgrvaidya** [comment]
Hi @Arpan619Banerjee ,
Checkout this link. This provides a good understanding of how to start contributing to open source.
https://www.firsttimersonly.com/

**Comment by Arpan619Banerjee** [comment]
Sure! Thank you so much!

**Comment by petebacondarwin** [comment]
@jbogarthyde - actually @IgorMinar has always been against automatically opening links in new tabs, and I agree with him. Forcing external content in a new tab is a constraint on readers which they cannot workaround. Moving to a new tab also can be confusing as it appears that the browsing history was lost.

It is quite straightforward for the reader to open a new tab on a link, for example on OS/X you just hold the Cmd button down while clicking. Now that we have additional visual indicators on all external links I think that this issue should be closed. WDYT?

**Comment by jbogarthyde** [comment]
The external link marker is certainly helpful for actual external links -- the thing that concerns me most is Glossary definitions. I want to encourage the use of the Glossary, and it is annoying for a temporary reminder or references to take you away from the page you are reading. A pop-up would be the best solution. Is that possible?

**Comment by petebacondarwin** [comment]
@jbogarthyde - I think you are requesting that when you click on a glossary link a small pop-up appears showing the definition of the term, without navigating to a new page at all?

This is definitely doable - although it will require a bit of work on the docs-infra side.
Since this is a different requirement to this issue, I am going to close this one.
Can you open a new issue with this specific feature request?

**Comment by jbogarthyde** [comment]
https://github.com/angular/angular/issues/37294
