### ISSUE TITLE
same #35611 issue as ERROR in Symbol MatList declared in ...

### ISSUE THREAD

**Issue by Tharusara** [angular/angular#36676]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

getting this issue after importing angular material and don't  know how to fix this..
![image](https://user-images.githubusercontent.com/62446562/79493497-304eff80-803f-11ea-9d06-c3b1e20a8d7f.png)

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by AndrewKushnir** [comment]
Hi @Tharusara,

Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information (minimum repro in a form of Github repo would be helpful) when filling out the issue template.

Thank you.

**Comment by Tharusara** [comment]
okay i will file a new issue. sorry about that
Thank you
