### ISSUE TITLE
Fire ng-mouseover on disabled buttons

### ISSUE THREAD

**Issue by binarykitchen** [angular/angular#3668]
I know, you currently don't but IMO AngularJS should.

I have an use case here where the button remains disabled when the entered form is invalid. But I want to show a tooltip over the disabled submit button to explain the user why it's invalid every time the user hovers over that disabled submit button. This to improve usability.

Any chance this can be accepted?

**Comment by pkozlowski-opensource** [comment]
@binarykitchen this is the repo for Angular 2, I guess you wanted to report in https://github.com/angular/angular.js. 

Having said this my understanding is that browsers won't fire mouse events on disabled elements (there are slight differences between browsers here, it seems) so there is nothing that Angular (or any other framework, for that matter) can do here. It looks like most people are using a work-around which consist of wrapping a button in an invisible element, ex.:
* http://stackoverflow.com/questions/3100319/event-on-a-disabled-input
* http://stackoverflow.com/questions/9450641/does-jquery-not-fire-hover-event-on-a-disabled-button

**Comment by binarykitchen** [comment]
uh ok, probably you want to rename that repo to angular 2 to avoid wrong tickets being placed here. it wasn't obvious to me.

right, i realised that browsers won't fire mouse events on disabled elements. i solved that by wrapping it with another parent div element. thanks for the links.
