### ISSUE TITLE
Querystring removed when useHash is true

### ISSUE THREAD

**Issue by MathewBerg** [angular/angular#36688]
# 🐞 bug report

### Affected Package
Not sure, I'm guessing core.

 

### Is this a regression?
Nope

 

### Description

When useHash is set to true the querystring is removed on page load and not maintained when navigating.

## 🔬 Minimal Reproduction
For the router set useHash to true. Then if you load the page such as

http://localhost:4200/?param=value#/example

The querystring gets removed so the new url is

http://localhost:4200/#/example

 https://stackblitz.com/...

## 🔥 Exception or Error
While I am completely fine with moving things forward we have a lot of other systems that do reporting on ours. Most of these are on various api calls. We have to use the useHash = true strategy as we need the referer to not include the routes. At the same time there's reporting done on parameters in the querystring that get passed via the referer as well. I am unable to change those systems unfortunately and so I was expecting an option to preserve the query string to be something I could set globally. I know I can specify it for each route but that doesn't handle the page load scenario.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.1
Node: 12.14.0
OS: win32 x64

Angular: 9.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.1
@angular-devkit/build-angular      0.901.1
@angular-devkit/build-ng-packagr   0.901.1
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.1
@angular-devkit/core               9.1.1
@angular-devkit/schematics         9.1.1
@angular/cdk                       9.2.1
@angular/cli                       9.1.1
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.2.1
@ngtools/webpack                   9.1.1
@schematics/angular                9.1.1
@schematics/update                 0.901.1
ng-packagr                         9.1.1
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
Hi @MathewBerg - The `HashLocationStrategy` uses the entire fragment as the internal route and ignores the rest: https://github.com/angular/angular/blob/acf6075ca9aa92121bb0166b2b7560aeb2c167ff/packages/common/src/location/hash_location_strategy.ts#L61
The way to set parameters using the hash strategy would be http://localhost:4200/#/example?param=value. Can you format your URL that way or is there some reason that isn't possible?

**Comment by MathewBerg** [comment]
@atscott unfortunately not because that does not get passed along in the referer header to external services.

**Comment by atscott** [comment]
Hmm, I'm not really sure what to recommend other than experiment with implementing your own `LocationStrategy`. The `HashLocationStrategy` is working as intended here. Handling unordered url parts would greatly complicate the handling of the path. Even the URI RFC has a strict order: [path, then query, then fragment](https://tools.ietf.org/html/rfc3986#section-3). Allowing for the path to be after the query part isn't something we'll likely implement, but I'll file this as a feature request.

**Comment by atscott** [comment]
Right, I understand the issue but it does involve putting the query params before the path. As I mentioned before, the `HashLocationStrategy` uses the fragment part for all routing. So the makeup of the route becomes '#' + path + '?' + queryParams. You're requesting the query params be interpreted from the original URL where they appear before the fragment.

**Comment by MathewBerg** [comment]
Ah ok that makes a little more sense. I actually think there should be an option to handle this sort of url:

http://localhost:4200/?param=value#/example?hashQueryParam=value

I may need to roll my own LocationStrategy as you said, I'll look into that. I appreciate the responses.

**Comment by MathewBerg** [comment]
@atscott I was able to extend the hash_location_strategy and change this line in replaceState:

```
this.platformLocation.replaceState(state, title, url);
```

To this

```
this.platformLocation.replaceState(state, title, window.location.search + url);
```

It allows a url like this:

http://localhost:4200/?queryString#/path?hashQueryString=

I'd love to get this option into angular itself but would need suggestions on how to enhance the hash location strategy maybe? Or I can just keep this for myself.

Once again thanks for looking into it and responding.

**Comment by atscott** [comment]
Hey @MathewBerg - I'm happy to hear you were able to get it working!

As for adding it as an option on `HashLocationStrategy`, unless this gets more community support I don't think it should be something we add to the framework. It seems like a pretty rare requirement and we shouldn't try to provide a configuration option for every edge case when there is already a solution available (providing your own `LocationStrategy`). Having a big API surface with options that are almost never used could end up being more confusing than helpful.

I'll at least leave this report open for now for discoverability.

**Comment by weirdall** [comment]
Just for myself and prosperity (thanks to @MathewBerg):

In ParameterHashLocationStrategy.ts:
`import { Injectable } from '@angular/core';
import { HashLocationStrategy } from '@angular/common';

@Injectable()
export class ParameterHashLocationStrategy extends HashLocationStrategy {
	prepareExternalUrl(internal: string): string {
		console.log('preparing external url', window.location.search, super.prepareExternalUrl(internal));
		return window.location.search + super.prepareExternalUrl(internal);
	}
}`

In app.module.ts:
`	providers: [
		{
			provide: LocationStrategy,
			useClass: ParameterHashLocationStrategy
		}
	]`

This is working perfectly!

@atscott +1 on the community support :)

**Comment by atscott** [comment]
After further investigation, this is actually working as intended. There are three possible solutions here:

* Remove the `base href` from the header. Angular will not modify anything before the hash when using `HashLocationStrategy` when if `base href` is not defined. Note that the query params get removed because Angular uses the base href to set the state when it's defined, following the strategy defined in [RFC 3986, section 5.2.2: Transform References](https://tools.ietf.org/html/rfc3986#section-5.2.2). 
* Put the query params in the base href, i.e. `<base href="http://localhost:4200/?param=value">`. When no path or query is defined for a URI (this would be true when using `HashLocationStrategy`), the browser inherits those values from the base
* Provide your own `LocationStrategy` as described by @MathewBerg
