### ISSUE TITLE
can add a method to viewContainerRef in order to get the ComponentRefs from container?

### ISSUE THREAD

**Issue by runFP** [angular/angular#36680]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
 I want to dynamically add components to a container, and then change the some properties  via componentRef.instance, Sometime i have to merge some compoents to one  and change some  properties again ,remove some component from container.so I must maintain a list of componentRef,when remove component via ViewContainerRef.remove I must remove relate ComponentRef in my list, also add it.
in the version "@angular/core": "~9.0.7",I can get the componentRef via 
viewContainerRef.get(i)['_view'].nodes[1],but sadly it can't use in version "@angular/core": "9.1.1".

It any other way to do this?

### Describe the solution you'd like
 ViewContainer have a method to get ComponentRefs form it;

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by 0x018** [comment]
i need `componentRef.instance` too;

```
xxxDirective{

    constructor( private cref  :ComponentRef<any>)
           /* get the Component used xxxDirective */
          /// this.cref.instance ....
    } 
}
```
# Describe the solution you'd like
1. ViewContainer have a method to get ComponentRefs form it
or
2. get `ComponentRef` form DI

**Comment by JoostK** [comment]
You can keep a `WeakMap` from `ViewRef` to `ComponentRef` when using `ViewContainerRef.createComponent`, and then translate from a `ViewRef` to the associated `ComponentRef` by looking it up in the map.
