### ISSUE TITLE
Angular Local host not working

### ISSUE THREAD

**Issue by angularbeginner** [angular/angular#36691]
Hi Coders,
when i open url  : **http://localhost:4200/**   from browser on laptop i get "**This site can’t be reached localhost took too long to respond** ". so i tried installing everything in desktop there also i am getting same issue.

Any idea guys what could be the issue

Below Are versions i am using 

Angular CLI: 9.1.1
Node: 12.16.2
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.1
@angular-devkit/core         9.1.1
@angular-devkit/schematics   9.1.1
@schematics/angular          9.1.1
@schematics/update           0.901.1
rxjs                         6.5.4

Thank you in Advance

**Comment by petebacondarwin** [comment]
I'm afraid that this is a support request that we do not support in this issue tracker. This is only for reporting bugs or feature requests with the Angular framework. If you need further help please consider other channels such as StackOverflow.

(By the way, have ensured that you have a HTTP server running, e.g. by doing `ng serve`?)

**Comment by angularbeginner** [comment]
> I'm afraid that this is a support request that we do not support in this issue tracker. This is only for reporting bugs or feature requests with the Angular framework. If you need further help please consider other channels such as StackOverflow.
> 
> (By the way, have ensured that you have a HTTP server running, e.g. by doing `ng serve`?)
ok thanks for quick reply...!!!
Anyways yes i did ng serve

**Comment by petebacondarwin** [comment]
In that case you may need to look at whether your OS is setup to allow `localhost` as a domain name?  Perhaps try `0.0.0.0`?
