### ISSUE TITLE
Calling the same activated component url , how to get trigger function to get data?

### ISSUE THREAD

**Issue by nikhildhar1992** [angular/angular#36696]
I have a component loaded, calling modal on top of that and after closing redirecting to same loaded component, but I am not able to trigger any function when 2nd time I am at my component.

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
