### ISSUE TITLE
predefined date format constant for ISO8601

### ISSUE THREAD

**Issue by sdavids** [angular/angular#36703]
# 🚀 feature request

### Relevant Package

This feature request is for @angular/common

### Description

https://xkcd.com/1179/
<img width="392" alt="iso_8601_2x" src="https://user-images.githubusercontent.com/201931/79637339-00a71100-817f-11ea-93b7-2e4cdb9a22ca.png">

Please provide a predefined constant for ISO8601.

https://angular.io/api/common/DatePipe#pre-defined-format-options

### Describe the solution you'd like

One of:

```
{{ dateObj | date:'iso' }}          // output is '2015-06-15'
{{ dateObj | date:'isoDate' }}      // output is '2015-06-15'
{{ dateObj | date:'isoLocalDate' }} // output is '2015-06-15'
{{ dateObj | date:'ISO8601' }}      // output is '2015-06-15'
{{ dateObj | date:'iso8601' }}      // output is '2015-06-15'
```

### Describe alternatives you've considered

```
{{ dateObj | date:'yy-MM-dd' }}     // output is '2015-06-15'
```

You always have to remember that `yy` and `dd` are lowercase and `MM` is uppercase — or look it up, copy/paste, end up with erroneous templates containing `{{ dateObj | date:'yy-mm-dd' }}`.

**Comment by petebacondarwin** [comment]
While it is tempting to keep adding options to things in the standard libraries, Angular was designed to make it very easy to customise behaviour by writing your own components, directives and pipes. 

It is simple to create an `isoDate` pipe that does just what you want and saves on adding more weight to the bundle size for people who do not need this format. See https://stackblitz.com/edit/ivy-epqezo?file=src%2Fapp%2Fapp.component.html
