### ISSUE TITLE
 Insert data without request using javascript ngModel

### ISSUE THREAD

**Issue by rodrigofurlaneti** [angular/angular#36704]
I have an Angular / TypeScript application on the frontend, which is not consumed as information from a Web API, back-end that was made on the Asp.Net Core, normally normal. My question is a form in Html, no type of javascript code calculation, no "client", no time to send the form to a WebApi, or a field that "null". If the user enters the value, or the data arrives at the API. However, if I do the javascript calculation, it will not reach the value. Setei as an untouched directive to touch and untouched for dirty in html, however or problem persists.Could anyone advise what I can do?

**Comment by JoostK** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
