### ISSUE TITLE
CI environment fails to run tests with /node_modules/__ngcc_entry_points__.json issues

### ISSUE THREAD

**Issue by Dzhuneyt** [angular/angular#36702]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

```
    "dependencies": {
        "@angular/animations": "^9.1.0",
        "@angular/cdk": "~9.2.0",
        "@angular/common": "^9.1.0",
        "@angular/compiler": "^9.1.0",
        "@angular/core": "^9.1.0",
        "@angular/forms": "^9.1.0",
        "@angular/material": "^9.2.0",
        "@angular/material-moment-adapter": "^9.2.0",
        "@angular/platform-browser": "^9.1.0",
        "@angular/platform-browser-dynamic": "^9.1.0",
        "@angular/platform-server": "^9.1.0",
        "@angular/router": "^9.1.0",
        "@fortawesome/angular-fontawesome": "^0.6.1",
        "@fortawesome/fontawesome-svg-core": "^1.2.28",
        "@fortawesome/free-brands-svg-icons": "^5.13.0",
        "@fortawesome/free-regular-svg-icons": "^5.13.0",
        "@fortawesome/free-solid-svg-icons": "^5.13.0",
        "@ngrx/effects": "^9.0.0",
        "@ngrx/entity": "^9.0.0",
        "@ngrx/router-store": "^9.0.0",
        "@ngrx/store": "^9.0.0",
        "@ngrx/store-devtools": "^9.0.0",
        "@ngx-translate/core": "^11.0.1",
        "@ngx-translate/http-loader": "^4.0.0",
        "bootstrap": "^4.4.1",
        "ci": "^1.0.0",
        "concurrently": "^4.1.2",
        "jquery": "1.9.1 - 3",
        "lodash": "^4.17.15",
        "moment": "^2.24.0",
        "nocache": "^2.1.0",
        "popper.js": "^1.16.1",
        "rxjs": "~6.5.4",
        "tslib": "^1.10.0",
        "zone.js": "~0.10.2"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "~0.901.0",
        "@angular/cli": "^9.1.0",
        "@angular/compiler-cli": "^9.1.0",
        "@angular/language-service": "^9.1.0",
        "@fortawesome/fontawesome-free": "^5.13.0",
        "@types/jasmine": "~3.3.8",
        "@types/jasminewd2": "^2.0.8",
        "@types/lodash": "^4.14.149",
        "@types/node": "^12.11.1",
        "angular-ide": "^0.9.74",
        "codelyzer": "^5.1.2",
        "husky": "^3.1.0",
        "jasmine-core": "~3.5.0",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~4.1.0",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~2.0.1",
        "karma-jasmine": "~2.0.1",
        "karma-jasmine-html-reporter": "^1.5.3",
        "karma-parallel": "^0.3.1",
        "nodemon": "^1.19.4",
        "npm-run-all": "^4.1.5",
        "prettier": "^1.19.1",
        "pretty-quick": "^1.11.1",
        "protractor": "^5.4.3",
        "stylelint": "^11.1.1",
        "stylelint-config-rational-order": "^0.1.2",
        "stylelint-order": "^3.1.1",
        "ts-loader": "^5.2.0",
        "ts-node": "~7.0.0",
        "tslint": "~5.15.0",
        "tslint-config-prettier": "^1.18.0",
        "typescript": "~3.8.3",
        "wait-on": "^3.3.0",
        "webpack-cli": "^3.3.11",
        "@babel/compat-data": "~7.8.0",
        "node-sass": "^4.13.1",
        "fibers": "^4.0.2",
        "html-webpack-plugin": "^4.0.4"
    }
```

### Is this a regression?

We've not seen this error prior to the Angular 9 upgrade.

### Description

While running the tests in a CI environment (GitHub actions), the command above appears to be stuck for 6 hours, after which it's automatically terminated due to a timeout. The message generated AFTER the timeout is the one I pasted above.

## 🔥 Exception or Error
<pre><code>

> attendor@1.0.0 tests:frontend:all /home/runner/work/attendor/attendor
> cd ./services/angular && npx ng test --watch=false --browsers=ChromeHeadless --sourceMap=false

Warning: Unable to read the entry-point manifest for /home/runner/work/attendor/attendor/services/angular/node_modules:
 Error: The entry-point manifest at /home/runner/work/attendor/attendor/services/angular/node_modules/__ngcc_entry_points__.json contained an invalid pair of package paths: [/app/node_modules/@angular/animations, /app/node_modules/@angular/animations]
    at EntryPointManifest.readEntryPointsUsingManifest (/home/runner/work/attendor/attendor/services/angular/node_modules/@angular/compiler-cli/ngcc/src/packages/entry_point_manifest.js:79:35)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.0
Node: 13.11.0
OS: darwin x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.0
@angular-devkit/build-angular      0.901.0
@angular-devkit/build-optimizer    0.901.0
@angular-devkit/build-webpack      0.901.0
@angular-devkit/core               9.1.0
@angular-devkit/schematics         9.1.0
@angular/cdk                       9.2.0
@angular/material                  9.2.0
@angular/material-moment-adapter   9.2.0
@ngtools/webpack                   9.1.0

</code></pre>

**Anything else relevant?**

GitHub actions using the latest Ubuntu environment.

**Comment by petebacondarwin** [comment]
So this path doesn't look right: `/app/node_modules/@angular/animations` unless your project really is at `/app` directly off the root...

In any case, if you get this warning it means that the previous run of `ngcc` created a manifest that found a package a `/app/node_modules/@angular/animations` but now this path either has no package in it or has an invalid package. When this happens `ngcc` will simply discard the manifest file and re-walk the entire `node_modules ` folder looking for Angular libraries.

Given that you are getting this warning, it suggests to me that you have a corrupt `node_modules` folder. I propose that you wipe out the `node_modules` (ensure that there is not a broken cache of this on your CI) and upgrade to the very latest Angular v9.

**Comment by petebacondarwin** [comment]
Closing due to a lack of response.
@Dzhuneyt - if this is still an issue, please post further details and I can re-open this.
