### ISSUE TITLE
AngularJS $compile equivalent in Angular - compile string to HTML

### ISSUE THREAD

**Issue by ease** [angular/angular#36719]
# 🚀 feature request

### Relevant Package
`"@angular/core": "9.1.1"` or any Angular 2+ version

### Description
AngularJS had an option to programatically and easily compile HTML out of a string with all the bindings and directives in it. So if we were to compile AngularJS-recognisable HTML out of a string (i.e. `Click here <span ng-click="doSomething({property: 'value'})"></span>`), we could do that.

See it in action on [StackBlitz](https://stackblitz.com/edit/angularjs-compile-html-from-string-example?file=ng1%2Fng1-demo.component.ts) and [GitHub repo](https://github.com/ease/angularjs-angular-compile-html).

Starting from Angular, we are no more able to do that. I've tried some solutions explained in section below, but they simply were not adequate. I also haven't found that anyone around seemed to find solution to this. It's actually the downside of migrating to Angular.

### Describe the solution you'd like
I don't know how you should be doing it, but it needs to be the syntax similar to previous.
Best I did was the following, using [Renderer2](https://angular.io/api/core/Renderer2):
```.ts
let textToCompile = `Click here <span (click)="doSomething({property: 'value'})"></span>`;
let div = this.renderer.createElement('div') as HTMLDivElement;
div.innerHTML = textToCompile;
this.renderer.appendChild(this.elementRef.nativeElement, div);
```
but `"(click)="doSomething({property: 'value'})"` was unrecognised value for Angular, so no click was triggered, and I didn't want to hack with some `addEventListener("click")` stuff, because it's not the Angular way.

### Describe alternatives you've considered
I was trying to achieve this by dynamically loading components, using `ViewContainerRef`, `ComponentFactoryResolver` and appropriate methods such as [createComponent](https://angular.io/api/core/ViewContainerRef#createComponent), without success. I see no any relation between these two things, as some other members of community have suggested. That simply doesn't serve the same purpose.

As I'm not a contributor, I couldn't reopen https://github.com/angular/angular/issues/6886 or https://github.com/angular/angular/issues/25871, but this feature now becomes even more important as projects become more advanced solutions nowadays.

Thanks in advance and please comment or react if you've encountered the same problem, so that Angular team knows it.

**Comment by ease** [comment]
Any news about this? This is very important feature for some advanced solutions within HTML, that can't be achieved with `createComponent`.

**Comment by alxhub** [comment]
Currently Angular does support this, although it requires dropping into JIT mode:
```typescript
import '@angular/compiler';

function $compile(selector: string, template: string, imports: any[] = []): any {
  @Component({
    selector: selector,
    template: template,
  })
  class DynamicCmp {}
  
  @NgModule({
    declarations: [DynamicCmp],
    imports: [...imports],
  })
  class DynamicModule {}

  return DynamicCmp;
}

// ...
const dynamicUi = $compile('test-cmp', 'This is a dynamic test component.');
this.viewContainerRef.createComponent(dynamicUi);
```

It's possible to build apps that are AOT compiled but use JIT internally, although this is poorly supported by the Angular CLI. Using JIT for the entire application will work fine, however.

**Comment by nsksaisaravana** [comment]
this is a long-awaited feature in angular but still no development on this.

**Comment by alxhub** [comment]
I'm going to close this issue as superseded by #43120 - we want to have support for dynamic UIs, but through an API with better security and performance characteristics than compiling templates from strings in the browser.
