### ISSUE TITLE
[strictNullChecks] AsyncPipe should return undefined instead of null

### ISSUE THREAD

**Issue by SchnWalter** [angular/angular#36717]
# 🚀 feature request

### Relevant Package

This feature request is for `@angular/core`.

### Description

Currently, the `AsyncPipe` uses `null` a possible return type, for a better `strictNullChecks` support , it should return `undefined`.

```
export declare class AsyncPipe implements OnDestroy, PipeTransform {
  // ...
  transform<T>(obj: Observable<T> | null | undefined): T | null;
  transform<T>(obj: Promise<T> | null | undefined): T | null;
}
```

To work around this, components that have an optional `@Input()` property have to define the possible types as `T | null | undefined`, instead of just using `T | undefined`.

### Describe the solution you'd like

Add `undefined` as a possible return type for the `transform()` method, but keep `null` as the actual value and add a deprecation message.

And in a new major version, update the pipe to return `undefined` instead of null.

```
export declare class AsyncPipe implements OnDestroy, PipeTransform {
  // ...
  transform<T>(obj: Observable<T> | null | undefined): T | undefined;
  transform<T>(obj: Promise<T> | null | undefined): T | undefined;
}
```

**Comment by sayoojbk** [comment]
Hi, @SchnWalter  @AndrewKushnir could I work on this issue. I have been using Angular for the past couple of months and would like it if I could contribute to this issue. I just started out with open-source contributions so few relevant links for support would be helpful 😄

**Comment by petebacondarwin** [comment]
@sayoojbk - a good start is to have a full read of https://github.com/angular/angular/blob/master/CONTRIBUTING.md

**Comment by LastDragon-ru** [comment]
> it should return undefined

Why?

**Comment by SchnWalter** [comment]
When you have an optional property on the class, you need to deal with the situation when it's undefined, the same applies for optional attributes on component classes, so, it would make sense to just use undefined as an "undefined"/"empty" value for inputs and not add extra logic for dealing with `null` values.

Remember `typeof null === 'object'`, this can cause unexpected problems. You can find more info on the TS `strictNullChecks` flag in [TypeScript 2.0 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html).

**Comment by evgeniyefimov** [comment]
I like rationale why we should stick with undefined in tslint's no-null-keyword explanation. [https://palantir.github.io/tslint/rules/no-null-keyword/](https://palantir.github.io/tslint/rules/no-null-keyword/) I have never needed null keyword in my experience, I only used it for a few type of angular things like validators etc., but I'd be happy if angular team get rid null type in angular at all.

**Comment by LastDragon-ru** [comment]
> When you have

Thanks for your explanations. I just almost always use `null` instead of `undefined`  and `@Input() prop: T|null = null` for optional inputs. I never had any issues with it 🤷‍♂️ ( `strict` & `strictNullChecks`).

> `T | undefined`

So this will create the opposite problem and I will need to change my code to `T | null | undefined` :( 

>  I have never needed null keyword in my ts/js projects

`undefined` and `null` have different semantic meanings, sometimes very important distinguish them. Also `json` doesn't support `undefined`, so you should support `null`s in any case.

**Comment by amakhrov** [comment]
Is it the same as https://github.com/angular/angular/issues/16982 ?

**Comment by SchnWalter** [comment]
Don't know why I didn't see that.

Closing as a duplicate of #16982
