### ISSUE TITLE
[i18n] $localize extract translation unit & documentation

### ISSUE THREAD

**Issue by luchillo17** [angular/angular#36714]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/localize

### Description
Currently, the `$localize` API is not documented, and translation text & id is not extracted towards translation file, basically the translation units for a text translated with `$localize` in code have to be put in a translation unit in the file manually.

If you have many items to translate with `$localize` it will add load to the team, it multiplies the load by the number of locales you need to support, since each time you merge the source locale into any other locale file, with the VSCode Angular i18n plugin (and very likely with many other xlf merge utilities), those translation units you added manually will be removed and you're forced to either look into git to undo those you added by hand or add them back again.

Here's the math, if you have, say 10 items localized from code, you support 10 languages or locales, you have to re-visit 100 translation units every time you make changes that require changes in the source locale file, which is very often when you make new features or fix a typo, adding tons of load, not to mention being highly error-prone.

### Describe the solution you'd like
All `$localize` calls are extracted into the translation file as translation units, and documentation is updated.

### Describe alternatives you've considered
At the very least make the extraction work, I could take care of the docs later since I've meddled quite a bit with the `$localize` API for enterprise projects:

![image](https://user-images.githubusercontent.com/9698639/79721852-a99d5b00-82a8-11ea-924f-7b44089dbd09.png)

**Comment by petebacondarwin** [comment]
This is being worked on https://github.com/angular/angular/pull/32912

**Comment by petebacondarwin** [comment]
And `$localize` as an API was not made public in v9. That is why it is not yet documented. In v9 we just used it internally for template translations. The fact that you can use it in your own TS code is supposed to be a secret 🤫

**Comment by luchillo17** [comment]
🤐

**Comment by spock123** [comment]
@petebacondarwin But is works SO great... we've been able to ditch all runtime translations now, thanks to `$localize` .. it's wonderful

**Comment by xiaoxiangmoe** [comment]
@petebacondarwin can we use `$localize` in ng-packagr in Angular 10?

**Comment by petebacondarwin** [comment]
Once https://github.com/angular/angular/pull/32912 lands and we get it integrated into the CLI then I think we should be fine to use `$localize`.

I don't believe that ng-packagr will do anything with `$localize`. It should just pass them through so that the application can do the translation. This leaves us with a new interesting question of how to best support a library author providing translations for their library. I.E. can we merge translation files when translating; and/or filter out translations from libraries when extracting.

**Comment by xiaoxiangmoe** [comment]
@petebacondarwin Should I open an issue about *how to best support a library author providing translations for their library*

**Comment by petebacondarwin** [comment]
Yes! Please do. This is something that we need to improve.

**Comment by petebacondarwin** [comment]
#32912 is now available on `10.1.0-next.0` release.

**Comment by nadia318** [comment]
Hi @petebacondarwin,
I'm trying to generate translations for my project and can't succeed at this 😢
I create app inside which I use my libs (in node_modules) with translations. Run `ng xi18n my-app --output-path=src/locale --ivy` first, after that I try to run `ng build --configuration=fr` and have errors `No translation found for...`
Is there any way to extract translations from my libs into my `src/locale/messages.xlf` file (not manually)? I use v.10.1.0

P.S. Everything works only if I remove `--ivy` flag and set `"enableIvy": false` in my tsconfig (which is obvious)

**Comment by petebacondarwin** [comment]
How are you consuming your libraries? Are they packaged as npm dependencies?

**Comment by nadia318** [comment]
> How are you consuming your libraries? Are they packaged as npm dependencies?
yes, they are published as npm packages(from another repo) and added as npm dependencies in my project

**Comment by nadia318** [comment]
@petebacondarwin yes, they are published as npm packages(from another repo) and added as npm dependencies in my project

**Comment by petebacondarwin** [comment]
The ivy extractor in the CLI only pulls out the translations from the application files, at the moment. @alan-agius4 has some ideas on how we could also grab the translations from imported library files too. In the meantime you can extract them separately by using the standalone binary with something like:

```bash
node_modules/.bin/localize-extract -s node_modules/**/*.js -f xlf -o library-messages.xlf
```

**Comment by reduckted** [comment]
> @petebacondarwin  And `$localize` as an API was not made public in v9. That is why it is not yet documented

> @petebacondarwin #32912 is now available on `10.1.0-next.0` release.

Any idea on when the documentation for `$localize` will be available? I'm wanting to use translations in services, but the lack of documentation is making it difficult. The best I've been able to find is [this third-party blog post](https://blog.ninja-squad.com/2019/12/10/angular-localize/), but it's almost a year old ,so I'm not sure if it's still accurate.

**Comment by petebacondarwin** [comment]
We are talking about implementing the `$localize` documentation. In the meantime, Cédric's blog is pretty accurate. I am in regular communication with him and he checks his writings with us.

**Comment by petebacondarwin** [comment]
There are now API docs for $localize: https://angular.io/api/localize and https://angular.io/api/localize/init/$localize are good starting points.
