### ISSUE TITLE
Error while installing Angular

### ISSUE THREAD

**Issue by karanloona** [angular/angular#36712]
I installed node successfully, while installing angular using this command:- >npm install -g @angular/cli , I got this error:- 
'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.
Error: EINVAL: invalid argument, mkdir 'C:\Users\<User Name>\AppData\Roaming\npm'

Can anyone explain the error and let me know how to resolve it. Thanks in advance!!

**Comment by asajuenitan** [comment]
Run npm -v, does it give the version?

**Comment by karanloona** [comment]
@asajuenitan yes it show version. In powershell it show this error:- 

npm : File C:\Users\karanloona\AppData\Roaming\npm\npm.ps1 cannot be loaded because running scripts is disabled on
this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ npm install -g @angular/cli
+ ~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by petebacondarwin** [comment]
This looks, to me, like you have installed `npm` in a folder that the current user does not have access.
This is not a bug with the Angular framework but a problem with your local npm setup.

**Comment by matsko** [comment]
@karanloona please create a new issue and follow the issue creation steps so we can properly address the issue. Thank you.
