### ISSUE TITLE
Support extend angularCompilerOptions in tsconfig from absolute tsconfig

### ISSUE THREAD

**Issue by splincode** [angular/angular#36715]
# 🐞 bug report

@alan-agius4 https://github.com/angular/angular/issues/22684

### Is this a regression?

No

### Description

I know that extends works if we use a config regarding our file system

tsconfig.angular.json

```json5
{
      "angularCompilerOptions": {
        "strictTemplates": true,
        "fullTemplateTypeCheck": true,
        "annotateForClosureCompiler": true,
        "strictInjectionParameters": true,
        "skipTemplateCodegen": false,
        "preserveWhitespaces": true,
        "skipMetadataEmit": false,
        "disableTypeScriptVersionCheck": true
    }
}
```

tsconfig.json

```json5
{
    "extends": "./tsconfig.angular.json",
    "compilerOptions": {
        "baseUrl": "./src",
        "module": "esnext",
        "target": "es2015",
        "outDir": "./dist/out-tsc",
        "lib": ["es2017", "es2018", "dom"]
    }
}
```

Works great

But If I put the config in a separate package

```json5
{
    "extends": "@my-company/tsconfig",
    "compilerOptions": {
        "baseUrl": "./src",
        "module": "esnext",
        "target": "es2015",
        "outDir": "./dist/out-tsc",
        "lib": ["es2017", "es2018", "dom"]
    }
}
```

Only inheritance compilerOptions works,  but I expect angularCompilerOptions to be inherited too

## 🔬 Minimal Reproduction

```
$ npm i @angular-ru/tsconfig
```

```json5
{
    "extends": "@angular-ru/tsconfig",
    "compilerOptions": {
        "baseUrl": "./src",
        "module": "esnext",
        "target": "es2015",
        "outDir": "./dist/out-tsc",
        "lib": ["es2017", "es2018", "dom"]
    }
}
```

```
$ ng build
```

Works without angularCompilerOptions inherited properties

@alan-agius4 What do you think about this, is it a bug?

## 🌍  Your Environment

**Angular Version:**

Angular 8.2.14

**Comment by alan-agius4** [comment]
Hi @splincode, since TypeScript supports non rooted extends we should probably do the same.

https://github.com/microsoft/TypeScript/blob/b346f5764e4d500ebdeff7086e43690ea533a305/src/compiler/commandLineParser.ts#L2603-L2628

**Comment by splincode** [comment]
@alan-agius4 Glad to hear that!
