### ISSUE TITLE
Submit resources to list on angular website

### ISSUE THREAD

**Issue by miguelramos** [angular/angular#36737]
It is possible to propose libs to be added to your's resource list on the angular website? If yes how. And what are the requirements to be listed?

Actual resources:

https://angular.io/resources?category=development

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/blob/master/aio/content/marketing/resources-contributing.md

**Comment by pkozlowski-opensource** [comment]
Thnx @ericmartinezr !

**Comment by miguelramos** [comment]
Thanks to all :).
