### ISSUE TITLE
InjectionToken generic type is not considered when assigning instances

### ISSUE THREAD

**Issue by Allcharles** [angular/angular#36736]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core

### Is this a regression?

Unsure if this has worked in previous versions.

### Description

Comparison of InjectionToken's of different types does not fail. This causes an issue when a function requires a typed InjectionToken as an input.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-issue-repro2-wkbrj2?file=src%2Fapp%2Fapp.component.ts

Excerpt:
```
import { InjectionToken } from '@angular/core';

class Class1 {}
class Class2 {}
class Class3 {}

function testToken(token: InjectionToken<Class3>) {}

// Should fail type check as Class1 !== Class2
const token: InjectionToken<Class1> = new InjectionToken<Class2>("TOKEN");

// Should fail type check as Class1 !== Class3
testToken(token);
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.1.0
Node: 12.16.1
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular/cdk                      9.2.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
Shouldn't matter, but the working environment is:
OS: Windows 10
IDE: VSCode

**Comment by Allcharles** [comment]
For any people who may encounter this issue. I created a temporary fix by wrapping the class using the following:
```typescript
export class ServiceToken<T> {
  kind: T;
  token: InjectionToken<T>;

  constructor(_desc: string) {
    this.kind = (_desc as unknown) as T;
    this.token = new InjectionToken<T>(_desc);
  }
}
```

Using the ServiceToken now causes type checking to occur again. The reason why the above issue occurs is because the type is not used in the `InjectionToken` class (at least in a way Typescript understands currently) and thus its type is ignored. Saving the value to an attribute inside the class fixes this typing issue.

**Comment by jelbourn** [comment]
Somewhat related to #33883

**Comment by alxhub** [comment]
TypeScript types have no influence on the runtime - TypeScript is compiled to JavaScript for execution in the browser, at which point types are [erased](https://en.wikipedia.org/wiki/Type_erasure). It's the object identity of an injection token that matters - its generic type can't (the language just doesn't support it).
