### ISSUE TITLE
AngularJS Unit Testing

### ISSUE THREAD

**Issue by TiagoBraga39** [angular/angular#3674]
Hi all!

<b>First of all, this is not an issue related to the AngularJS.</b>
I just started on reading about unit testing and some frameworks related to it, but I wanted to use the same framework used in NG 2 development if there is any.

Does anyone know which is it or which one do you recommend?

Best regards,
Tiago Braga

**Comment by evan-liu** [comment]
Hi @TiagoBraga39, 

Check out https://github.com/angular/angular/blob/master/karma-js.conf.js 

Regards, 
Evan

**Comment by TiagoBraga39** [comment]
@evan-liu Thank you! :)

Best regards,
Tiago Braga
