### ISSUE TITLE
How to use Ng Build or cli to create new folder  inside dist/MyPojectName/assets/angular(ie new folder)

### ISSUE THREAD

**Issue by afeef1915** [angular/angular#36755]
What I need

* I need to create new folder say angular inside dist/myprojectname/assets folder.

So Folder Structure
  1. Project
  2.  dist
  3. MyProject Name
  4.assets

![image](https://user-images.githubusercontent.com/16572202/79970189-2baba080-84b0-11ea-9916-9dec04951c13.png)

 So when i ran
>ng build it craeted js ,css images folders inside assets that's fine.

But it also created new files main.js or pollifils.js outside of assets folder

![image](https://user-images.githubusercontent.com/16572202/79969051-965bdc80-84ae-11ea-99d1-4c9909ffe7e1.png)

I  need

* i need to create new folder inside assets name angular which may contains all files in new folder angular.

![image](https://user-images.githubusercontent.com/16572202/79969279-e8046700-84ae-11ea-9085-df7b3307005b.png)

![image](https://user-images.githubusercontent.com/16572202/79969316-f5215600-84ae-11ea-9343-7c92c2884c34.png)

Index.htm

![image](https://user-images.githubusercontent.com/16572202/79969386-0e2a0700-84af-11ea-86fe-0e34c4bfd5c6.png)

Include path of js in index,htm by  Angular Cli.

Command  I tried
ng build --output-path=dist/MyProjectName/assets/angular

Angular Jason
![image](https://user-images.githubusercontent.com/16572202/79970718-f94e7300-84b0-11ea-8f81-02560c15c0e3.png)

Refrence Link
 
https://angular.io/guide/deployment

https://angular.io/cli/build

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by afeef1915** [comment]
> Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.
> 
> If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Thanks for your reply.

I Just need Angular command which help in creating new folder in assets/angular

Thanks

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
