### ISSUE TITLE
break foreach

### ISSUE THREAD

**Issue by vahidalvandi** [angular/angular#3675]
hi

do angular support break on angular.foreach 

???

**Comment by PascalPrecht** [comment]
No, there's no support for that.

**Comment by ericmdantas** [comment]
@vahidalvandi if you want to get out of an .forEach, just use ```return```.

**Comment by pkozlowski-opensource** [comment]
There is no public angular.forEach in ng2 (well, there are facades with helper methods, but this is different story) and AFAIK we are not planning to add one (helper function like `forEach` created substantial maintenance overhead without much added value....).

**Comment by ericmdantas** [comment]
@vahidalvandi please use [this repo](https://github.com/angular/angular) for angular 1.x questions. :smile:

**Comment by vahidalvandi** [comment]
very thanks
