### ISSUE TITLE
I can't create a new angular project  using ng new project

### ISSUE THREAD

**Issue by ANadjia** [angular/angular#36754]
Hello ! i am trying to create a new angular project and it's not working 
i installed ,
Node v : 12.16.2
Npm v : '6.13.4'
Angular v :  latest 9.1.2
This is the output  : 
![image](https://user-images.githubusercontent.com/25845658/79969451-d365a600-8491-11ea-80fa-51f04ba713f1.png)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by gkalpak** [comment]
It looks like a corrupted `package.json` file somewhere. I suggest you remove `node_modules/` and reinstall dependencies.
