### ISSUE TITLE
Strange, inconsistent behavior using [ngClass] between setting `optimization` flag in build config to true or false.

### ISSUE THREAD

**Issue by itbrandonsilva** [angular/angular#36759]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ~8.2.7

### Description

This report is a result of attempting to upgrade to ng9/ivy from ng8/ve.

When setting `optimization: true` in angular.json (which ultimately sets `ngDevMode` to `false`, which is responsible for the below inconsistency), `[ngClass]` does not function the same as it does when `optimization: false`.

After investigation of the `ngClass` directive source code at runtime with `optimization: false`, I noticed that each time the `ngClass` setter was updated, `ngDoCheck` was called on the directive, which is where the `[ngClass]` directive makes necessary updates to the DOM. But if `optimization: true`, `ngDoCheck` is _not_ consistently called after the `ngClass` input changes, causing the `ngClass` instance to not apply the provided config to the element.

The usage of `[ngClass]` in my case is sloppy as the attribute expression (IE: `[ngClass]=buttonStyle`) is a _getter_ that returns a _new object_ on each invocation. After updating the component implementation such that the value `buttonStyle` only changes when necessary (and is no longer a getter), the problem I'm dealing with goes away entirely. Despite this, I'm looking to understand why the original getter pattern wasn't broken in ViewEngine/ng8, but it now breaks in Ivy/ng9. I can't find information in any Ivy/ng9 upgrade guide or notes that points out why the previous `getter` approach is suddenly being handled differently. I'm concerned about other potential breaks that can occur as a result of upgrading.

Ultimately I'm looking to understand why `[ngClass]` `ngDoCheck` is called consistently when `ngDevMode: true`, but is _not_ consistently called when `ngDevMode: false` when using Ivy. I'm used to angular throwing exceptions in dev mode if a feature is misused, but considering no warnings or exceptions occur in dev mode in this case, I'd expect this to work consistently between dev and prod configurations.

## 🔬 Minimal Reproduction

(I do not yet know how to have the dev server run in prod mode on stackblitz, so in order to use this repro, you'll need to set `ngDevMode = false` manually in the console, and click "Start editing" to trigger the click handler and force cd. After forcing cd, you'll see that the `[ngClass]` input value no longer properly propagates to the element).

https://stackblitz.com/edit/angular-uwerky

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.0
Node: 12.11.1
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.0
@angular-devkit/build-angular      0.901.0
@angular-devkit/build-ng-packagr   0.901.0
@angular-devkit/build-optimizer    0.901.0
@angular-devkit/build-webpack      0.901.0
@angular-devkit/core               9.1.0
@angular-devkit/schematics         9.1.0
@angular/cdk                       9.1.3
@angular/material                  9.1.3
@ngtools/webpack                   9.1.0
@schematics/angular                9.1.0
@schematics/update                 0.901.0
ng-packagr                         9.0.3
rxjs                               6.5.4
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

**Comment by Achilles1515** [comment]
I can't seem to reproduce this (in a real project, not StackBlitz, with 9.1.3 at least).
I modified your StackBlitz example slightly to show if dev mode is running and also to be able to toggle the class on/off.

With using `ng serve --prod` (which should be using `optimization: true`), everything seems to be working as expected:

![GIF](https://user-images.githubusercontent.com/23387905/80211658-15165e00-8604-11ea-9be2-5a25ac243a98.gif)

[ng-run demo](https://ng-run.com/edit/25zJwCUH0viEcO6mI5Au?open=app%2Fapp.component.ts) of my code

**Comment by itbrandonsilva** [comment]
Thanks for getting back to me.

I updated the above Stackblitz repro (sorry for not forking it) to reflect that despite what `isDevMode` reports, it doesn't have anything to do with `ngDevMode` being set. `ngDevMode` is cleared based on a compile-time constant. Correlating info can be [here] and (https://angular.io/guide/ivy-compatibility) and [here](https://github.com/angular/angular-cli/blob/493aa74019104fe029e3527b519918a0ae6febf0/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts#L375).

The updated repro includes `enableProdMode()` in `main.ts`, and you'll see that `ngDevMode` exists despite `isDevMode` reporting `false`. In this above scenario, after clearing the `ngDevMode` variable, it seems that things continue to work correctly.

What's interesting is if `enableProdMode()` were to be _excluded at startup_, then the `[ngClass]` weirdness can be seen after clearing `ngDevMode`. Ultimately `ngDevMode` is what is responsible for altering the relevant execution pattern.

I'll continue investigating through a local repro.

**Comment by itbrandonsilva** [comment]
The exact case I was describing towards the end of my last post is _exactly_ what's happening in our application. We had a commit get through to master recently causing our staging app builds to not set the `production` flag in our app environment.ts properly, creating the above strange situation (`enableProdMode()` _not_ being called, but `ngDevMode: false` being set at build time). This didn't create weirdness in NG8, but it _does_ create weirdness in NG9, but weirdness is exactly what one should expect in this case.

@Achilles1515 Thanks for helping me align my investigation.
