### ISSUE TITLE
[Request] Add unit tests for the examples (modules/examples)

### ISSUE THREAD

**Issue by ericmdantas** [angular/angular#3676]
It'd be awesome to have unit tests for the [examples in modules/examples](https://github.com/angular/angular/tree/master/modules/examples/src).

**Comment by PascalPrecht** [comment]
@ericmdantas I think there are already plenty of tests in `modules/angular2/test` that you can take a look at. Not sure if it's a benefit to have yet another place where tests are shown. In addition, the actual tests are always up-to-date.

**Comment by ericmdantas** [comment]
@PascalPrecht that's a good point and I've seen some of those.

I was just wondering if we could get something with a smaller scope and using the tools that are released with the bundled versions.

**Comment by PascalPrecht** [comment]
I think for now we need to use the tooling that is inside the angular repo the same way it is used for angular's tests.

**Comment by mhevery** [comment]
Examples have e2e tests. I don't think we are planning to have unit tests there.

we have a separate goal of having unit test examples in the docs which should cover this use case. Closing this issue.

**Comment by ericmdantas** [comment]
Sounds good. Thanks!
