### ISSUE TITLE
EmptyError: no elements in sequence

### ISSUE THREAD

**Issue by danbilokha** [angular/angular#36779]
# 🐞 bug report

### Affected Package
The source of the bug supposed to be RxJs, however, according to <a href='https://stackblitz.com/edit/rxjs-nguzst'> RxJs does not reproduce StackBlitz case</a> - I do not think so. 

### Is this a regression?
No

### Description
Angular ErrorHandler catches 'EmptyError: no elements in sequence' exception.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/emptyerror

## 🔥 Exception or Error
<pre><code>
EmptyErrorImpl {message: "no elements in sequence", name: "EmptyError"}
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.0
Node: 13.12.0
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular/cdk                      9.2.0
@angular/material                 9.2.0
@ngtools/webpack                  9.0.5
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.41.2

</code></pre>

**Comment by danbilokha** [comment]
Oh, as it turns out it can be reproduced - https://stackblitz.com/edit/rxjs-nguzst in catchError. So probably expected Angular behavior.

**Comment by JoostK** [comment]
What is the issue you're having? The [StackBlitz sample](https://stackblitz.com/edit/rxjs-nguzst) is working correctly. Also, how would Angular be relevant here?

**Comment by danbilokha** [comment]
@JoostK that's true. It could be closed. Although, it's still not obvious that you should catchError subject almost without any kind of logic inside

**Comment by JoostK** [comment]
In this particular example, it's the `last` operator that throws the error. This occurs because the subject is completed after 2.5 seconds, and the `false` value emitted at 1.5 seconds is filtered out before reaching the `last` operator, which causes it to fail. An alternative could be to use `takeLast(1)` which behaves differently.
