### ISSUE TITLE
ngFor doesn't work

### ISSUE THREAD

**Issue by brianshen1990** [angular/angular#36785]
ng-version: 
```
Angular CLI: 9.1.3
Node: 13.6.0
OS: darwin x64

Angular: 9.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.3
@angular-devkit/build-angular     0.901.3
@angular-devkit/build-optimizer   0.901.3
@angular-devkit/build-webpack     0.901.3
@angular-devkit/core              9.1.3
@angular-devkit/schematics        9.1.3
@ngtools/webpack                  9.1.3
@schematics/angular               9.1.3
@schematics/update                0.901.3
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
```
Code: 
![Screen Shot 2020-04-24 at 2 34 13 PM](https://user-images.githubusercontent.com/12724940/80182441-7d336700-8639-11ea-89bc-dc69d2a93756.png)
Preview
![Screen Shot 2020-04-24 at 2 34 35 PM](https://user-images.githubusercontent.com/12724940/80182446-7f95c100-8639-11ea-8e6c-33b879fdc930.png)

Tried online, everything works OK. 
![Screen Shot 2020-04-24 at 2 40 48 PM](https://user-images.githubusercontent.com/12724940/80182539-b53aaa00-8639-11ea-8f57-7c23a9fa3f11.png)

Is this a bug?

**Comment by mlc-mlapis** [comment]
@brianshen1990 No, it has to work exactly the same way. You have to have a mistake somewhere.

**Comment by petebacondarwin** [comment]
Is it related to the styles in the app? What do the generated HTML look like?

**Comment by hassan-devDz** [comment]
it's working
You forgot {{i}}

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
