### ISSUE TITLE
Compiling @angular/cdk/bidi with ngcc fails

### ISSUE THREAD

**Issue by altsanz** [angular/angular#36780]
# 🐞 bug report

### Affected Package
@angular/cdk/bidi

### Is this a regression?

I dont know

### Description

When I run ng build mylibrary and error happens while compiling @angular/cdk/bidi, I think through ngcc for Ivy.

## 🔬 Minimal Reproduction

https://github.com/altsanz/ngcc-repro-issue

## 🔥 Exception or Error
<pre><code>
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'run',
npm verb cli   'ng',
npm verb cli   '--',
npm verb cli   'build',
npm verb cli   'ngcc-repro-issue'
npm verb cli ]
npm info using npm@6.13.4
npm info using node@v12.16.1
npm verb run-script [ 'preng', 'ng', 'postng' ]
npm info lifecycle ngcc-repro-issue@0.0.0~preng: ngcc-repro-issue@0.0.0
npm info lifecycle ngcc-repro-issue@0.0.0~ng: ngcc-repro-issue@0.0.0

> ngcc-repro-issue@0.0.0 ng C:\Users\sanzdiaa\projects\ngcc-repro-issue
> ng "build" "ngcc-repro-issue"

? Would you like to share anonymous usage data about this project with the Angular Team at 
Google under Google’s Privacy Policy at https://policies.google.com/privacy? For more      
details and how to change this setting, see http://angular.io/analytics. No
0% compiling
Compiling @angular/core : es2015 as esm2015 

Compiling @angular/common : es2015 as esm2015

Compiling @angular/platform-browser : es2015 as esm2015

Compiling @angular/platform-browser-dynamic : es2015 as esm2015

Compiling @angular/cdk/keycodes : es2015 as esm2015

Compiling @angular/cdk/platform : es2015 as esm2015

Compiling @angular/cdk/observers : es2015 as esm2015

Compiling @angular/cdk/a11y : es2015 as esm2015

Compiling @angular/cdk/portal : es2015 as esm2015

Compiling @angular/cdk/bidi : es2015 as esm2015

ERROR in Cannot read property 'start' of undefined
npm verb lifecycle ngcc-repro-issue@0.0.0~ng: unsafe-perm in lifecycle true 
npm verb lifecycle ngcc-repro-issue@0.0.0~ng: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\sanzdiaa\projects\ngcc-repro-issue\node_modules\.bin;C:\Program Files (x86)\Java\jre6\bin;C:\Program Files\Java\jre6\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\Program Files\TortoiseGit\bin;C:\Program Files\nodejs\;C:\Users\sanzdiaa\scoop\apps\nvm\current\nodejs\nodejs;C:\Users\sanzdiaa\scoop\shims;C:\Users\sanzdiaa\AppData\Local\Microsoft\WindowsApps;C:\Users\sanzdiaa\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\sanzdiaa\AppData\Local\hyper\app-3.0.2\resources\bin;C:\Users\sanzdiaa\AppData\Roaming\npm;C:\Users\sanzdiaa\AppData\Local\Programs\Git\cmd
npm verb lifecycle ngcc-repro-issue@0.0.0~ng: CWD: C:\Users\sanzdiaa\projects\ngcc-repro-issue
npm info lifecycle ngcc-repro-issue@0.0.0~ng: Failed to exec ng script
npm verb stack Error: ngcc-repro-issue@0.0.0 ng: `ng "build" "ngcc-repro-issue"`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:311:20)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:311:20)
npm verb stack     at maybeClose (internal/child_process.js:1021:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
npm verb pkgid ngcc-repro-issue@0.0.0
npm verb cwd C:\Users\sanzdiaa\projects\ngcc-repro-issue
npm verb Windows_NT 10.0.17763
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "ng" "--" "build" "ngcc-repro-issue"
npm verb node v12.16.1
npm verb npm  v6.13.4
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngcc-repro-issue@0.0.0 ng: `ng "build" "ngcc-repro-issue"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ngcc-repro-issue@0.0.0 ng script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 44403ms

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.0
Node: 12.16.1
OS: win32 x64

Angular: 9.1.3
... animations, common, compiler, core, forms, localize
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.3
@angular-devkit/build-angular      0.901.3
@angular-devkit/build-ng-packagr   0.901.3
@angular-devkit/build-optimizer    0.803.4
@angular-devkit/build-webpack      0.901.3
@angular-devkit/core               9.1.3
@angular-devkit/schematics         9.1.0
@angular/cdk                       9.2.1
@angular/cli                       9.1.0
@angular/compiler-cli              9.1.0
@angular/language-service          9.1.0
@angular/material                  9.2.1
@ngtools/webpack                   9.1.3
@schematics/angular                9.1.0
@schematics/update                 0.901.0
ng-packagr                         5.7.1
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.42.0
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
There's a version skew in the Angular packages you have installed.

Specifically `@angular/compiler` and `@angular/compiler-cli` are pinned to 9.1.0, where others are ^9.1.0. Also `@angular-devkit/build-optimizer` is outdated, as is TypeScript (and ng-packagr). Aligning these versions allows the compilation to succeed.
