### ISSUE TITLE
Router should support case-insensitive root index.html

### ISSUE THREAD

**Issue by EatonZ** [angular/angular#36804]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/router.

### Description
I am aware that Router paths are case-sensitive. While personally I disagree with that, I can work around it with a custom `DefaultUrlSerializer`. What I cannot work around is when a request comes in for /INDEX.HTML. While my custom `DefaultUrlSerializer` will essentially make Router work with case-insensitive URLs by lower-casing everything, it doesn't appear to work for /INDEX.HTML.

I am also aware that the case-sensitivity problem has been brought up before (https://github.com/angular/angular/issues/7691, etc), but I think this is a unique case that is worth looking at.

### Describe the solution you'd like
Since Router already appears to handle /index.html internally somewhere, I think in this one-off case it should handle it in a case-insensitive manner to prevent the `Cannot match any routes` error.

### Describe alternatives you've considered
I do not see an alternative. I welcome any workarounds!

### Sample project / reproduction
I hesitated a bit in considering this a feature request, but in case this is classified as a bug, I put together a repro [here](https://stackblitz.com/edit/angular-pkxduk).
1. Expand the console on the right and add /index.html to the address bar and refresh. You will not see anything wrong.
2. Try using /INDEX.HTML and you _will_ see an error (in the console), **even though my custom DefaultUrlSerializer lower-cased it** (as seen in the console).

**Comment by TapanGujjar** [comment]
I would like to work on the issue if possible

**Comment by EatonZ** [comment]
@TapanGujjar Go ahead if you know what to do!

**Comment by TapanGujjar** [comment]
Thank you @EatonZ. I will start working on the issue.

**Comment by EatonZ** [comment]
@TapanGujjar Did you ever take a look?

**Comment by TapanGujjar** [comment]
@EatonZ i am not able to find the resolution. Sorry

**Comment by EatonZ** [comment]
Thank you for finally considering this feature.😁
