### ISSUE TITLE
Strange bug with regex.

### ISSUE THREAD

**Issue by AlQuraian** [angular/angular#36803]
### Description
The rendered output differs when commenting/uncommenting a console log.
Just comment/uncomment line 11.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-issue-repro2-zqt2sn

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.1
Node: 12.16.0
OS: win32 x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/language-service         9.1.2
@angular/localize                 9.1.2
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by JoostK** [comment]
Regexes have internal state, and matching a string affects this state.

You can avoid this in two ways:

1. Set `lastIndex` to 0 before testing:

```ts
function isValidContentUrl(url?: string): boolean {
  ytVideoRegexp.lastIndex = 0;
  return !!url && ytVideoRegexp.test(url);
}
```

2. Use `String.prototype.match` instead of `Regex.prototype.test`:

```ts
function isValidContentUrl(url?: string): boolean {
  return !!url && !!url.match(ytVideoRegexp);
}
```


This is not otherwise an Angular issue.
