### ISSUE TITLE
Limit template type checking scope to specific components or modules

### ISSUE THREAD

**Issue by SpiraMira** [angular/angular#36811]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/...

### Description
 Inline options to turn template type checking on or off would be very useful.  I am extending an existing library that contains many anomalies that I don't care to fix, while I need to make sure that my custom code is clean and component templates are fully type checked using the latest Ivy features

### Describe the solution you'd like
 A tsconfig configuration section that allows skipping the template type checking for certain components/modules or an exclude/include type of approach.

### Describe alternatives you've considered
 Not aware of any

**Comment by alxhub** [comment]
You can split your compilation into legacy code in a library build, using different settings than your application build.

At the framework level, we feel this is the right granularity for things - just like with TypeScript, the tsconfig governs the strictness/level of checking that Angular performs on your code. If you want different strictness settings, you need multiple tsconfigs (multiple compilations).
