### ISSUE TITLE
unwanted dependency from angular/localize

### ISSUE THREAD

**Issue by igorlino** [angular/angular#36813]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/localize

### Is this a regression?

 Yes, the previous version in which this bug was not present was: angular v8.x

### Description

When requiring angular/localize in a project that uses translations, an unwanted lodash dependency appears. It seems to come from babel/core. 

Analysing the size of the angular CLI bundle that requires angular/localize that dependes on babel/core, i noticed an additional complete lodash dependency.

```
>npm ls lodash

+-- @angular/localize@9.1.3
| `-- @babel/core@7.8.3
|   `-- lodash@4.17.15  deduped

```
The lodash fully included has:
Stat size: 527.84 KB
Parsed size: 70.72 KB
Gzipped size: 23.81 KB

## 🔬 Minimal Reproduction

```
>ng new test
>ng install @angular/localize
>npm ls lodash

```

## 🔥 Exception or Error

No a error, but a suboptimal bundling 

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.1.3                                               
Node: 12.16.1                                                    
OS: win32 x64                                                    
                                                                 
Angular: 9.1.3                                                   
... animations, cli, common, compiler, compiler-cli, core, forms 
... language-service, localize, platform-browser                 
... platform-browser-dynamic, router                             
Ivy Workspace: Yes                                               
                                                                 
Package                           Version                        
-----------------------------------------------------------      
@angular-devkit/architect         0.901.3                        
@angular-devkit/build-angular     0.901.3                        
@angular-devkit/build-optimizer   0.901.3                        
@angular-devkit/build-webpack     0.901.3                        
@angular-devkit/core              9.1.3                          
@angular-devkit/schematics        9.1.3                          
@ngtools/webpack                  9.1.3                          
@schematics/angular               9.1.3                          
@schematics/update                0.901.3                        
rxjs                              6.5.5                          
typescript                        3.8.3                          
webpack                           4.42.0                         
                                                                 
</code></pre>

**Anything else relevant?**

none

**Comment by petebacondarwin** [comment]
The `$localize` dependency on `babel` is required to do compile-time inlining of translations. This dependency will not appear in the bundled Angular application. Is this your concern?

**Comment by igorlino** [comment]
You are right, I don't know from where is it coming, somehow is appearing there.

I use a smaller project

To analyze the bundle I run:

```
> node ./node_modules/@angular/cli/bin/ng build --prod --stats-json
> npm i -g webpack-bundle-analyzer@latest
> webpack-bundle-analyzer dist/test/stats-es2015.json

```
lodash does not appear there.

I will close this issue, thank you for you feedback and time.
