### ISSUE TITLE
CAN NOT CALL FORROOT WITH ANGULAR 9 - IVY

### ISSUE THREAD

**Issue by danbn-100295** [angular/angular#36815]
I have a module with static method forRoot like this
<img width="631" alt="Ảnh chụp Màn hình 2020-04-27 lúc 5 07 51 CH" src="https://user-images.githubusercontent.com/61224981/80360516-a8bc8880-88a9-11ea-9f56-425f511f0083.png">
And call it in feature module
<img width="324" alt="Ảnh chụp Màn hình 2020-04-27 lúc 5 00 16 CH" src="https://user-images.githubusercontent.com/61224981/80360589-c4c02a00-88a9-11ea-9552-34e608da4e37.png">
I have error,after upgrade to angular 9 - IVY
<img width="623" alt="Ảnh chụp Màn hình 2020-04-27 lúc 5 00 26 CH" src="https://user-images.githubusercontent.com/61224981/80360647-da355400-88a9-11ea-8644-e007135e06d5.png">
Please help me fix it

**Comment by mlc-mlapis** [comment]
@danbn-100295 You missed the key info that the syntax inside `forRoot` is very strict. It has to exactly like:
```
ModuleWithProviders<xxxModule> {
		return {
			ngModule: xxxModule,
			providers: [
				...
			]
		};
```

**Comment by danbn-100295** [comment]
@mlc-mlapis 
thanks for reply,I try like this,it still not work
<img width="746" alt="Ảnh chụp Màn hình 2020-04-27 lúc 5 18 26 CH" src="https://user-images.githubusercontent.com/61224981/80361442-20d77e00-88ab-11ea-97b8-0a7604e19ccf.png">

**Comment by petebacondarwin** [comment]
You can't have `if` statements in the `forRoot()` method at this time. Try something like:

```
forRoot(config?: Partial<ICurrencyInput): ModuleWithProviders<InputCurrencyModule> {
  return {
    ngModule: InputCurrencyModule,
    providers: [
      provide: CURRENCY_CONFIG,
      useValue: config ? {...currencyConfig, ...config} : currencyConfig,
    ]
}
```

Or if that doesn't work just simply

```
      useValue: {...currencyConfig, ...config},
```

(since `{...currencyConfig, ...undefined}` is the same as `{...currencyConfig}`.

**Comment by danbn-100295** [comment]
@petebacondarwin 
Wow,it work perfect,thanks so much!
Can you tell me why ?

**Comment by mlc-mlapis** [comment]
@danbn-100295 Because of Angular compiler that is statically parsing the code and it has to understand it using pre-defined rules. You can't extend the code above those rules.

**Comment by petebacondarwin** [comment]
The Angular compiler must statically evaluate the code of `forRoot()` to work out what is going to be returned. It is able to evaluate most expressions (including ternary `... ? ... : ...`) but it isn't able to evaluate more complex statements.

**Comment by danbn-100295** [comment]
@pedroclayman thanks so much !

**Comment by AndrewKushnir** [comment]
Hi, it looks like this issue is resolved, so I'm closing this ticket. Thank you.
