### ISSUE TITLE
Ability to change the interpolation delimiter character

### ISSUE THREAD

**Issue by bradlygreen** [angular/angular#3682]
Folks who wish to mix Angular 2 template syntax with another template rendering syntax wish to change the interpolation character.  (ex: https://twitter.com/_JRawls/status/633330574208315396)

A complexity in doing this is that globally changing the interpolation character will break most existing directives that use the default {{ }} characters.  

A solution to this would be to make this a per-component setting via decorators and the ES5-equivalent syntax.  Teams who want to adopt a different separator would create this as part of their standard component config annotation (decorator) as a way to centralize maintenance of its usage.

**Comment by mhevery** [comment]
This would be possible in NG2, since we could change it on per view basis, so unlike NG1 (where it is kind of broken) such a feature could work properly in NG2.

**Comment by jeremytrawls** [comment]
Thanks for even considering this gents!  I can think of a few more scenarios where it would be beneficial to do the same.

**Comment by vicb** [comment]
This had landed in master
