### ISSUE TITLE
Assert all `Observables` unsubscribed

### ISSUE THREAD

**Issue by dgp1130** [angular/angular#36824]
# 🚀 feature request

### Relevant Package
This feature request is for `@angular/core` (specifically `TestBed`).

### Description
It is very easy for developers to forget to unsubscribe to an `Observable`. Most commonly, developers may use `ngOnInit()` to subscribe to an `Observable`, but they should also unsubscribe in `ngOnDestory()`. If they forget to do this, they will not receive any error in testing or at runtime, but will have a potential memory leak and use unnecessary resources.

### Describe the solution you'd like
The two solutions I can think of, include:

* A conformance test for all components to assert that after the component is destroyed, there should not be any active `Observable` subscriptions.
    * `TestBed.configureTestingModule()` could perhaps add this assertion to the end of all tests? Or maybe some other `addAngularConformanceTests()` could be added somewhere in the test file.
    * This way, everyone implicitly tests for this invariant without thinking about it.
    * Downside is that this only really works for components.
* Some kind of `expectNoActiveSubscriptions();`
    * This would allow users to test services and other non-component code.
    * Users must manually add this assertion and remember to test for it.
    * Not sure the best way of pointing the user to the offending `Observable`. Maybe some O(n) check for the class under test (or all injectable objects) to see if the `Observable` is still referenced somewhere?

I'm not sure the best way of actually implementing either of these. The only way I can think of is spying on `Observable.prototype.subscribe()` and `Observable.prototype.unsubscribe()`, which is a pretty hacky solution to the problem. It might be worth a FR to RxJS to support this use case more explicitly.

### Describe alternatives you've considered
I think the current workaround is to spy on `Observable.prototype.{,un}subscribe()` manually. I think https://github.com/awerlang/observable-profiler can do this, though it requires more work for the user.

### Links to users asking for this feature
[b/155107643](http://b/155107643)
https://stackoverflow.com/questions/54588424/how-to-test-is-all-subscription-unsubscribed-in-angular
https://stackoverflow.com/questions/52364687/how-do-i-unit-test-unsubscribe-in-angular-and-jasmine

**Comment by pauldraper** [comment]
FYI, this problem would be made far better if #10185 were implemented.

Then, you could simply `.takeUntil(destory)`.
