### ISSUE TITLE
Is it possible to publish Angular 9 ivy compiled library.

### ISSUE THREAD

**Issue by sonali395** [angular/angular#36836]
I have upgraded by angular components library for **version 8 to version 9**. Since version 9 comes with ivy compilation by deafult, when I try to publish my library to npm repo. It gives me the following error:
**node --eval "console.error('ERROR: Trying to publish a package that has been compiled by Ivy. This is not allowed.\nPlease delete and rebuild the package, without compiling with Ivy, before attempting to publish.\n')" && exit 1**

Is there any workaround or the issue is expected in this version of angular since the official docs of angular says it is not recommended.

**Comment by petebacondarwin** [comment]
Angular libraries must be compiled by ViewEngine, still. The ivy compiled code should not be published. If you use ng-packagr to construct your libraries for publishing to npm, this is done for you.

**Comment by petebacondarwin** [comment]
More information here https://angular.io/guide/creating-libraries#publishing-your-library
