### ISSUE TITLE
zone.js does not handle promise.then as async microTask in some case

### ISSUE THREAD

**Issue by JiaLiPassion** [angular/angular#36839]
- `zone.js` version: 0.10.3
- reproduce repo: https://github.com/JiaLiPassion/zone-promise-seq

The code will look like this.
```
<html>
  <script src="./node_modules/zone.js/dist/zone-evergreen.js"></script>
  <script>
    const promise = Promise.resolve(1);
    function doSomethingWithoutZoneTask() {
      window[Zone.__symbol__('requestAnimationFrame')](() => {
        console.log('handler begin');
        promise.then(() => {
          console.log('promise then called');
        });
        div.removeChild(btn);
        console.log('handler end');
      });
    }
    window.onload = function() {
      const btn = document.getElementById('btn');
      const div = document.getElementById('div');
      btn.addEventListener('blur', () => {
        console.log('blur');
      });
      btn.addEventListener('click', () => {
        doSomethingWithoutZoneTask();
      });
    }
  </script>
  <body>
    <div id="div">
      <button id="btn">Test</button>
    </div>
  </body>
</html>
```

And when user click button `Test`, the output in the console will be

```
handler begin
blur
promise then called
handler end
```

So the `promise.then` callback is being executed synchronize which is not correct.

The reason is here https://github.com/angular/angular/blob/master/packages/zone.js/lib/zone.ts#L1283, and it seems this issue is a known issue, since there is a test case here, https://github.com/angular/angular/blob/master/packages/zone.js/test/browser/element.spec.ts#L73

so in some cases, the `drainMicroTaskQueue` will be invoked too early since `zone.js` wrongly consider. the current task is the top task, we should always use `native promsie` to schedule a microTask to run `drainMicroTaskQueue`.

**Comment by naveedahmed1** [comment]
Should this also affect change detection in Angular? I noticed in my app that sometimes, if I programatically redirect user to another page, althought the url in address bar is updated but screen doesnt change and sometimes if the next page is loaded the items on next page are not interactive until change detection is triggered.
