### ISSUE TITLE
Missing ky-KG locale data in @angular/common/locales/

### ISSUE THREAD

**Issue by oneclickwebstudio** [angular/angular#36831]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/common/locales/

### Description
 We love angular and it will be great if you add missing locale **ky-KG** in common locales. Here is global  [ICU format](http://www.localeplanet.com/icu/ky-KG/index.html)

THX a lot

**Comment by petebacondarwin** [comment]
I might be wrong but this is my understanding of the situation:

`ky-KG` is listed in https://github.com/unicode-cldr/cldr-core/blob/master/defaultContent.json#L107. I believe that this means that this locale is an exact copy of its parent `ky`, so there is no need to have a separate locale for it. You can see some explanation of this in the [Design Goals section of the JSON Packaging proposal](http://cldr.unicode.org/development/development-process/design-proposals/json-packaging).

Therefore, I believe you can just load the `ky` locale in Angular and when you use `ky-KG` in your application it will automatically fallback to using `ky`.

**Comment by oneclickwebstudio** [comment]
> I might be wrong but this is my understanding of the situation:
> 
> `ky-KG` is listed in https://github.com/unicode-cldr/cldr-core/blob/master/defaultContent.json#L107. I believe that this means that this locale is an exact copy of its parent `ky`, so there is no need to have a separate locale for it. You can see some explanation of this in the [Design Goals section of the JSON Packaging proposal](http://cldr.unicode.org/development/development-process/design-proposals/json-packaging).
> 
> Therefore, I believe you can just load the `ky` locale in Angular and when you use `ky-KG` in your application it will automatically fallback to using `ky`.

Missed it. Thx
