### ISSUE TITLE
Design WebWorker Messaging Protocol

### ISSUE THREAD

**Issue by jteplitz** [angular/angular#3685]
Currently messaging between the UI and the WebWorker is pretty haphazard, and relies on a lot of hard coded strings. Additionally various components use their own protocols. For example, the broker has a protocol, the setup component has a protocol, and events have their own protocol. All of these are defined in different places.

There should be one protocol file (similar to [barista's protocol](https://github.com/yjbanov/barista/blob/master/lib/messaging/protocol.dart)) that defines the structure of all messages that we pass through the MessageBus and defines any constants that they use.

**Comment by mhevery** [comment]
obsolete
