### ISSUE TITLE
Add support for ReadonlyArray in NgIterable

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular#36854]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description

```
type NgIterable<T> = Array<T> | Iterable<T>;
```

Please change it into

```
type NgIterable<T> = ReadonlyArray<T> | Iterable<T>;
```

**Comment by pauldraper** [comment]
I'm confused by this in general, since Array<T> is already a subtype of Iterable<T>.

**Comment by xiaoxiangmoe** [comment]
I'm also confused by this in general, since Array is already a subtype of Iterable.

**Comment by petebacondarwin** [comment]
This type was introduced by @alxhub in https://github.com/angular/angular/pull/33536. Perhaps he can explain why it was necessary to us a union of array and iterable?

**Comment by alxhub** [comment]
Actually I have no idea why `NgIterable` is defined that way. #33536 just adds the type to `fake_core`, its real definition is in `iterable_differs.ts` and as far as I can tell it's been that way for a long time. My suspicion is something related to `Iterable` was different in the older TypeScript versions from when `NgIterable` was defined, that required the redundant definition.

**Comment by petebacondarwin** [comment]
Sorry I git-blamed @alxhub unfairly. As he points out, his commit is different.

Here is possibly some more context:

https://github.com/angular/angular/pull/14104/files#r98477745

https://github.com/angular/angular/blob/4.0.0-beta.5/modules/@angular/core/src/change_detection/differs/iterable_differs.ts#L29

```
// TODO(misko): We can't use Iterable as it would break the .d.ts file for ES5 users.
```

**Comment by JoostK** [comment]
Closing as `ReadonlyArray` is supported through the `Iterable` type, and type flowing into `NgForOfContext.ngForOf` retains the readonly array type as expected: https://stackblitz.com/edit/angular-ivy-xpnnjw?file=src%2Fapp%2Fapp.component.ts (change the signature of `test` to just `string[]` instead of `readonly string[]` to see an error, which confirms that `NgForOfContext.ngForOf` is indeed a readonly array).
