### ISSUE TITLE
HELP | Memory Leak, Angular 9

### ISSUE THREAD

**Issue by GlauberF** [angular/angular#36857]
# 🐞 bug report

### Affected Package
@angular/* 

### Description
Disclaimer: Sorry for my ignorance, but I am not very aware of this memory leak issue.

After I upgraded to version 9, I noticed that in some moments I am trying to consume a lot of memory, losing a lot of usability, but I am not absolutely sure if the problem has to do with the library, if you can help me follow snapshot.

## 🔬 Minimal Reproduction
Snapshot: https://we.tl/t-DEZUW9cNRk

## 🌍  Your Environment
```
Angular CLI: 9.1.3
Node: 10.15.3
OS: linux x64

Angular: 9.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.3
@angular-devkit/build-angular      0.901.3
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.3
@angular-devkit/core               9.1.3
@angular-devkit/schematics         9.1.3
@angular/cdk                       9.2.1
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.2.1
@angular/material-moment-adapter   9.2.1
@ngtools/webpack                   9.1.3
@nguniversal/builders              9.1.0
@nguniversal/common                9.1.0
@nguniversal/express-engine        9.1.0
@schematics/angular                9.1.3
@schematics/update                 0.901.3
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
```

**Comment by JoostK** [comment]
The heap doesn't tell much about a supposed leak. There's lots going on without context on what is expected to go on, so it's nearly impossible to determine a leak, let alone determine the cause of a leak.

As for follow up investigation, I would request you to extract a minimum reproduction scenario that shows a memory leak based on certain actions and can be shared in e.g. a Github repo. As finding memory leaks requires monitoring the memory usage over time together with the actions that are performed, a runnable application is essential to investigate.

Out of curiosity, what does HLTP mean?

**Comment by GlauberF** [comment]
I am closing because after some tests in other modules of the APP, the slowness does not happen, so I come to the conclusion that it is not something with the angle, but with some specific dependency used in some modules of the APP.
Thank you
