### ISSUE TITLE
Deploy to Github Pages KO

### ISSUE THREAD

**Issue by moueza** [angular/angular#36867]
Hi,
As you see https://github.com/moueza/site-internet-moueza-peter-a2/commits/master commit 372820ffc74b250f4f379abb2b90d7ad931dfb4c

I have parameterized /docs as source, set https://angular.io/guide/deployment : ng build --prod --output-path docs --base-href /site-internet-moueza-peter-a2/

But https://moueza.github.io/site-internet-moueza-peter-a2/ is KO, whereas it is locally OK (ng serve)

What to do please ?

**Comment by meriturva** [comment]
on html there is no presence of angular:

https://moueza.github.io/site-internet-moueza-peter-a2/index.html

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by moueza** [comment]
@meriturva 
Thank you
Yes it is the problem I do point out (index.html generated seems werd but seems rather similar to view-source:https://sanjaysaini2000.github.io/angular-todo-app/, and it is OK locally)
And my original index.html (https://github.com/moueza/site-internet-moueza-peter-a2/blob/master/peter/src/index.html) has the required  <app-root></app-root>

**Comment by moueza** [comment]
@is2ei 
Thanks
Yes my repo is already configured : master branch /docs folder
