### ISSUE TITLE
@Attribute does not work as expected

### ISSUE THREAD

**Issue by wdunn001** [angular/angular#36863]
# 🐞 bug report

### Affected Package
{ Attribute } @angular/core
### Is this a regression?
No

### Description

When using @attribute in a constructor there is no way to dynamically change what is passed as an attribute. I would expect [attr] template syntax to allow you to set whats passed into a component but it does not.
 I would expect one of these methods allow me to dynamically set an attribute for a component
<app-child [attr.test]="test" ></app-child>

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-9-starter-material-8gqrb1

## 🔥 Exception or Error
the @attribute DI returns null if the value is set using [attr] template syntax

## 🌍  Your Environment

**Angular Version:**
<pre><code>
9.0.0
</code></pre>

**Comment by eneajaho** [comment]
As written in the Angular documentation: **Template binding works with properties and events, not attributes.**

![image](https://user-images.githubusercontent.com/25394362/80653578-cee55280-8a7a-11ea-8eac-32d91a9d2c30.png)

**Comment by wdunn001** [comment]
> As written in the Angular documentation: **Template binding works with properties and events, not attributes.** - [Source](https://angular.io/guide/template-syntax#html-attribute-vs-dom-property)
> ![image](https://user-images.githubusercontent.com/25394362/80653578-cee55280-8a7a-11ea-8eac-32d91a9d2c30.png)

which is all fine and good and I don't want to set up a binding for the attribute. I want to be able to read the attribute with the @Attribute property as design and use the [Template Syntax](https://angular.io/guide/template-syntax) to set the attribute property. this should work but @attribute returns a null value if the attribute has been set using template syntax.

**Comment by Achilles1515** [comment]
Side note that it appears the earliest attribute bindings are available for reading is after change detection in the `ngAfterViewInit` hook. You're asking for the attribute in the class constructor...it makes sense (in regards to the rest of the Angular world) that the attribute is not resolved, just like how template bound properties are not resolved until `ngOnInit` (after the constructor).

With this example:
```html
<app-child [attr.test]="'two'"></app-child>
```

```ts
@Component({
  selector: 'app-child',
  // ...
})
export class ChildComponent implements OnInit, AfterViewInit {
  constructor(@Attribute('test') public test, private _elementRef: ElementRef) { 
    console.log(test);  // Output: null
  }

  ngOnInit() {
    console.log(this._elementRef.nativeElement.getAttribute('test')); // Output: null
  }

  ngAfterViewInit() {
    console.log(this._elementRef.nativeElement.getAttribute('test')); // Output: 'two'
  }
}
```

**Comment by wdunn001** [comment]
> ```ts
> his._elementRef.nativeElement.getAttribute('test')); // Output: null
>   }
> 
>   ngAfterViewInit() {
>     console.log(this._elementRef.nativeElement.getAttribute('test')); // Output: 'two'
>   }
> ```

So I would say it's acceptable that they cannot be read in the constructor but I would at least expect to be able to read it in ngOnInit. I would propose that the following stackblitz should both display 'test' and console.log 'test' twice.

https://stackblitz.com/edit/angular-9-starter-material-8gqrb1 

this would seem to be an issue with how @Attribute initially gets its value. For an example use case.   I have components like custom formControls that take an initial value. I don't want to detect changes to those inputs so I would rather just pass it in as an attribute. This seemed like a simple solution for this but turned out not to be.

**Comment by pkozlowski-opensource** [comment]
@wdunn001 I would like to better understand this part:

> I would expect one of these methods allow me to dynamically set an attribute for a component
<app-child [attr.test]="test" >

So, this was never our intention, which means that our intentions and your expectations don't match :-) 

I was wondering why you would like to use the above syntax and try to get the value from an attribute, given that you can just pass a value as `@Input()` (`<app-child [attr.test]="test" >`).

Is it because you are trying to both pass an input to a component _and_ set an attribute on a host element?

**Comment by wdunn001** [comment]
@pkozlowski-opensource @Input triggers change detection I want to be able to set a value and not have that value re evaluated further. I want to be able to dynamically set that value (using attr template syntax) and then read that attribute using @attribute.

The Documentation states for the Attribute directive 
> An Attribute directive changes the appearance or behavior of a DOM element.

And the attribute decorator states
> Parameter decorator for a directive constructor that designates a host-element attribute whose value is injected as a constant string literal.

I am simply wanting to dynamicly set that string literal using the attribute directive and read it using that attribute decorator which doesnt work and should which is shown in the following example https://stackblitz.com/edit/angular-9-starter-material-8gqrb1

**Comment by waterplea** [comment]
This is working as designed. DI is static, you can only read values at construction time. Bindings are resolved after the component is initiated. This is just technically impossible. You can inject `ElementRef` and add a getter as was mentioned in code snipped above:
```ts
get attr(): string {
  return this.elementRef.nativeElement.getAttribute('attr');
}
```
If you are worried about performance of re-querying it with a getter each time you access it, it takes just a few nanoseconds to do so it would definitely not affect you.

**Comment by wdunn001** [comment]
@waterplea It would be reasonable to have a static flag that defaults to false on the @attribute consider the following

`@Attribute('test', {static: false })`

this would inject a reference to the getAttribute method

**Comment by waterplea** [comment]
It's impossible to have it dynamically. Injections are resolved during construction, at that time dynamic bindings are not yet applied. This would require a fundamental change of how everything works.

**Comment by waterplea** [comment]
@wdunn001 I think I misread your message. You want Attribute decorator to inject closure of getAttribute instead of a string? A function for attribute is very counter intuitive. You can make a simple string token to act as you described. Check out this StackBlitz below:
https://ng-run.com/edit/mEzje2bqJDBEcuZGcVRd?open=app%2Ftest.component.ts

**Comment by wdunn001** [comment]
Yes I think a better keyword would have been dynamic

@Attribute('test', {dynamic: true })

The example you gave is exactly what I was thinking just simplified.
