### ISSUE TITLE
Enabled Ivy and postinstall:"ngcc", facing build duplicate identifier issue for ngx-monaco-editor anf ngx-img-cropper

### ISSUE THREAD

**Issue by Mahi223** [angular/angular#36870]
# 🐞 bug report

### Affected Package
ngx-monaco-editor 
ngx-img-cropper 
 ag-grid-community.

### Is this a regression?

No

### Description

I have upgraded angular to 9. Trying to add new Ivy feature, but I am facing duplicate identifier issue for ngx-monaco-editor and ngx-img-cropper and sometimes for ag-grid-community.
Then issue occures when adding "ngcc" in postinstall script.
This issue is getting while building using ng build.

## 🔬  Reproduction

1. Create new lazy loaded project with angular 9.
2. Enable Ivy from tsconfig.js
"angularCompilerOptions": {
    "enableIvy": true
  },

3. aot from angular.json
          "options": {
            "aot": true,
             ....
             }

(By default it is enabled for new angular 9 project).

4. Add postinstall script in package.json file
  "postinstall": "ngcc",

5. run command npm install.
6. build application using ng build

throwing compilation error for ngx-monaco-editor 

**ERROR in ./node_modules/ngx-monaco-editor/__ivy_ngcc__/fesm2015/ngx-monaco-editor.js 9:12
Module parse failed: Identifier 'ɵngcc0' has already been declared (9:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import * as ɵngcc0 from '@angular/core';
|
> import * as ɵngcc0 from '@angular/core';
|
| const _c0 = ["editorContainer"];**

and Error for ngx-img-cropper
**ERROR in ./node_modules/ngx-img-cropper/__ivy_ngcc__/fesm2015/ngx-img-cropper.js 8:12
Module parse failed: Identifier 'ɵngcc0' has already been declared (8:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import * as ɵngcc1 from '@angular/common';
| 
> import * as ɵngcc0 from '@angular/core';**

## 🔥 Exception or Error
<pre><code>
ERROR in ./node_modules/ngx-img-cropper/__ivy_ngcc__/fesm2015/ngx-img-cropper.js 8:12
Module parse failed: Identifier 'ɵngcc0' has already been declared (8:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import * as ɵngcc1 from '@angular/common';
| 
> import * as ɵngcc0 from '@angular/core';
| 
| const _c0 = ["cropcanvas"];
@ ./src/app/shared/common/sub-app-common.module.ts 6:0-53 100:12-30 170:8-26 237:20-38
@ ./src/app/app-routing.module.ts
@ ./src/app/app.module.ts
@ ./src/root.module.ts
@ ./src/main.ts
@ multi ./src/main.ts
ERROR in ./node_modules/ngx-monaco-editor/__ivy_ngcc__/fesm2015/ngx-monaco-editor.js 9:12
Module parse failed: Identifier 'ɵngcc0' has already been declared (9:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import * as ɵngcc0 from '@angular/core';
|
> import * as ɵngcc0 from '@angular/core';
|
| const _c0 = ["editorContainer"];
@ ./src/app/admin/libraries/libraries.module.ts 115:0-55 141:0-40 187:12-30 305:25-46 351:20-38
@ ./src/app/admin/admin-routing.module.ts
@ ./src/app/admin/admin.module.ts
@ ./src/app/app-routing.module.ts
@ ./src/app/app.module.ts
@ ./src/root.module.ts
@ ./src/main.ts
@ multi ./src/main.ts
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

PS C:\MyData\TCSrc\Client> ng version                                                                                    
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.1.1
Node: 12.16.2
OS: win32 x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.2
@angular-devkit/build-angular     0.901.2
@angular-devkit/build-optimizer   0.901.2
@angular-devkit/build-webpack     0.901.2
@angular-devkit/core              9.1.2
@angular-devkit/schematics        9.1.1
@angular/cdk                      9.2.1
@ngtools/webpack                  9.1.2
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

PS C:\MyData\TCSrc\Client>  
</code></pre>

**Comment by Mahi223** [comment]
1. This issue is not when I have not used ngcc in postinstall script. 
2. Without ngcc, I am able to build. but compilation time is more than without Ivy build, size is little less than normal build.

**Comment by Mahi223** [comment]
![duplicate identifier1](https://user-images.githubusercontent.com/54582064/80684910-09cfa080-8ae4-11ea-80c9-d569adf62522.png)

**Comment by Mahi223** [comment]
![image](https://user-images.githubusercontent.com/54582064/80685096-4f8c6900-8ae4-11ea-90f3-843e11fdc683.png)

**Comment by petebacondarwin** [comment]
Can you clarify what you mean by "lazy loaded project"?
> Create new lazy loaded project with angular 9.

Also can you try updating to 9.1.4, which is the latest release?

**Comment by Mahi223** [comment]
@petebacondarwin lazy loaded means Project with multiple modules which called on demand.
I have not tried with updating angular 9.1.4

**Comment by petebacondarwin** [comment]
Do you believe that lazy loading these modules triggers the issue?

**Comment by Mahi223** [comment]
Might not be, But In my project, We used this concepts so I mentioned here.

**Comment by petebacondarwin** [comment]
OK let me see if I can reproduce this.

**Comment by petebacondarwin** [comment]
I created this repository and I cannot reproduce this issue. https://github.com/petebacondarwin/angular-issue-36870
Please can you provide a reproduction of the error, either by sharing a repository of your own or updating this one.

**Comment by Mahi223** [comment]
As i see "postinstall": "ngcc" is not used in angular.json in script tag.
I have downloaded this project, made required changes in it but not able to reproduce the issue. 
In my project, when I build project, It creates __Ivy_ngcc__ folder. From this folder it throws exception (./node_modules/ngx-img-cropper/__ivy_ngcc__/fesm2015/ngx-img-cropper.js).
It create __Ivy_ngcc__ folder in respective folder like in ngx-img-cropper and ngx-monaco-editor.

**Comment by Mahi223** [comment]
I am using form
![image](https://user-images.githubusercontent.com/54582064/80702646-08f83800-8aff-11ea-842c-50f81c4c2dc3.png)

I am using formio in my project, while npm install, it shows above exception

**Comment by petebacondarwin** [comment]
So this last issue is caused by angular-formio/autht having an invalid package.json. See https://unpkg.com/browse/angular-formio@3.27.3/auth/package.json

The `"main": "formio-manager.umd.js",` format points to a non-existent file.

If you want to run ngcc as a postinstall hook then you could set it only to build the first matching format and then put the properties to consider in an order so that `main` comes last. E.g.

```
ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points
```

If that doesn't work for you, it is possible to "configure" ngcc to ignore this property by adding a `ngcc.config.js` file in your project root. It would look like:

```js
module.exports = {
  packages: {
    'angular-formio': {
      entryPoints: {
        'auth': { override: { main: undefined } }
      }
    }
  }
};
```

This tells ngcc to override the `main` property of `node_modules/angular-formio/auth/package.json` with `undefined`.

**Comment by Mahi223** [comment]
![image](https://user-images.githubusercontent.com/54582064/80738988-66a67780-8b33-11ea-946a-2cfef149364e.png)

Facing this issue while "npm install" from angular-formio

**Comment by petebacondarwin** [comment]
I believe this is a known issue with angular-formio. See https://github.com/formio/angular-formio/issues/505
