### ISSUE TITLE
APP_INITIALIZER supports Observables

### ISSUE THREAD

**Issue by pauldraper** [angular/angular#36886]
# 🚀 feature request

### Relevant Package

@angular/core

### Description

APP_INITIALIZER supports Promises, but not Observables. Nor does it provide any way to clean up the intializers.

### Describe the solution you'd like

Support Observable, including unsubscribing when the app is destroyed.

### Describe alternatives you've considered

This can be implemented manually by users.

**Comment by pkozlowski-opensource** [comment]
I believe that this is a duplicate of #15088
