### ISSUE TITLE
outdated code in angular routing documentation

### ISSUE THREAD

**Issue by jadidihosein68** [angular/angular#36885]
# 📚 Docs or angular.io bug report

### Description
There is a mismatch between the constructed and utilized router naming 
the function inside the ngOnInit should be` this.route.queryParams.subscribe(...)` instead of `this.activatedRoute.queryParams.subscribe(...)`

### What's the affected URL?**
https://angular.io/guide/router

## 📷Screenshot

![image](https://user-images.githubusercontent.com/21352258/80809003-62da2a00-8bf3-11ea-9f6f-2b8a2184fb61.png)

## 🔥 Exception or Error
Unable to compile. 

## 🌍  Your Environment
Local
### Browser info
Chrome
### Anything else relevant?
Stay safe. Cheers!

**Comment by sonukapoor** [comment]
I will take a look and provide a fix shortly.
