### ISSUE TITLE
[i18n] Different ICU and NgPlural behaviour when using sourceLocale

### ISSUE THREAD

**Issue by javiermarinros** [angular/angular#36888]
# 🐞 bug report

### Description

I found out that using a custom `sourceLocale` configuration ("es" in my case), the result from this code is unexpected:

```
<div *ngFor="let case of [0, 1, 2]">
  {{ case }}
  ICU: {case, plural, zero {zero} one {one} other {other}}

  NgPlural:
  <ng-container [ngPlural]="case">
    <ng-template ngPluralCase="zero">zero</ng-template>
    <ng-template ngPluralCase="one">one</ng-template>
    <ng-template ngPluralCase="other">other</ng-template>
  </ng-container>
</div>
```

### Expected:

0 ICU: other NgPlural: other
1 ICU: one NgPlural: one
2 ICU: other NgPlural: other

### Received:

0 ICU: other NgPlural: other
1 ICU: **other** NgPlural: one
2 ICU: other NgPlural: other

## 🔬 Minimal Reproduction

I haven't been able to reproduce it in Stackblitz, it doesn't recognize `sourceLocale` 
 configuration in `angular.json` https://stackblitz.com/edit/angular-g47pyh

Using CLI:
ng new project
Enable `localize` and set `sourceLocale` to "es" in angular.json
Copy the above code and run the project

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
I'm using Windows

**Comment by petebacondarwin** [comment]
Here's the problem:

![Screenshot 2020-05-02 at 21 22 34](https://user-images.githubusercontent.com/15655/80891332-35f14a00-8cbb-11ea-9cf8-c93dec2aea95.png)

It appears that Ivy passes a string form of the number through to the pluralization function, whereas ngPlural passes through the number form.

**Comment by petebacondarwin** [comment]
We actually strip out the conversion from string to number in the generated plural CLDR functions: https://github.com/angular/angular/blob/12fcc7cafe8bf6dd33416847327891b581281774/tools/gulp-tasks/cldr/extract.js#L571

This is to keep the size of the locale data files to a minimum, I believe.

So I think the best fix is to ensure that we only pass a number to these generated functions, by fixing it here: https://github.com/angular/angular/blob/12fcc7cafe8bf6dd33416847327891b581281774/packages/core/src/i18n/localization.ts#L15
