### ISSUE TITLE
Angular does not build with the instructions from DEVELOPER.md

### ISSUE THREAD

**Issue by kmillikin** [angular/angular#3688]
I'm trying to build Angular and run performance tests by following the instructions at https://github.com/angular/angular/blob/master/DEVELOPER.md.

The build fails because (1) the zone.js and traceur packages do not include a LICENSE file but (2) Angular will not build (!) if there is no such license file.

Maybe this is should be a bug against those packages, but it seems that until they begin shipping a LICENSE file, Angular can't really require one.

As a workaround, I'm using:

```
touch node_modules/zone.js/LICENSE
touch node_modules/traceur/LICENSE
```

**Comment by kmillikin** [comment]
I should say: it is the `npm install` step that fails.

**Comment by pkozlowski-opensource** [comment]
@kmillikin this sounds odd. What is the node.js / npm version that you are using?

**Comment by kmillikin** [comment]
node.js version v0.10.25 and npm version 1.3.10.  These are the packages from Ubuntu 14.04 LTS.

I tried with node v0.12.7 and npm version 2.13.5 and it seems to work.  I'm not sure why an older version of npm does not include the LICENSE file but only for those two out of all the packages.

In any case, it's not worth investigating but the directions at https://github.com/angular/angular/blob/master/DEVELOPER.md should probably just be updated to mention that a minimum version of node.js and npm is required.

**Comment by mhevery** [comment]
Version updated: https://github.com/angular/angular/commit/20cf61756a460cd53013d1381509548a0e627e80
