### ISSUE TITLE
formatNumber IS WRONG

### ISSUE THREAD

**Issue by infofromca** [angular/angular#36889]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/Common

### Is this a regression?

NO

### Description

 A clear and concise description of the problem...

pass 1234.56 , or 1789,or 1999...
to the function
it produce 1
## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

formatNumberToFixedTwo(n:number){
  let st = formatNumber(n,'en-CA','1.2-2');

  return parseFloat(st);
}
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>
 8

**Anything else relevant?**

**Comment by infofromca** [comment]
#32119 ,my suggestion . if decimal... is good, just delete this . very dangerous!!!!

**Comment by petebacondarwin** [comment]
@infofromca - I cannot reproduce any error here. Here are my results:

```
formatNumber(1234.56, 'en-CA', '1.2-2')   -> 1,234.56
formatNumber(1789, 'en-CA', '1.2-2')   -> 1,789.00
formatNumber(1999, 'en-CA', '1.2-2')   -> 1,999.00
```

Did you ensure that you had loaded the `en-CA` locale?

**Comment by infofromca** [comment]
did u parseFloat(st)É

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
