### ISSUE TITLE
INJECTOR docs are lacking

### ISSUE THREAD

**Issue by waterplea** [angular/angular#36896]
# 📚 Docs or angular.io bug report

### Description

`INJECTOR` description is unclear.

I'd like to understand better when do I need to inject `Injector` and when I can get away with just `INJECTOR` so my app bundle would be smaller.

Examples would be great!

### What's the affected URL?
https://angular.io/api/core/INJECTOR-1

**Comment by JeanMeche** [comment]
We're deprecating the `INJECTOR` token, I think we can close this issue.
