### ISSUE TITLE
Form (control | emitValue: true | false ): disable control should show in form.value

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#36894]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/forms

### Description

I would like see disable control value in onSubmit when we do (this.myForm.value). There are some situation where we want to disable control with default value. Right now i am preserving that default value in another variable.

### Describe the solution you'd like
It is good to have one more optional param to just disable control but you will see value in this.myForm.value.

`
 this.myForm.get('name').disable({onlySelf: true, emitEvent: false, emitValue: true});
`

third optional param **emitValue?: true | false**

### Describe alternatives you've considered
Above one

**Comment by chgc** [comment]
that's what [getRawValue](https://angular.io/api/forms/FormGroup#getRawValue) use for

**Comment by indraraj26** [comment]
> That's what [getRawValue](https://angular.io/api/forms/FormGroup#getRawValue) use for.
> 
> > Retrieves all values regardless of disabled status. The value property is the best way to get the value of the group, because it excludes disabled controls in the FormGroup.

So whenever we work with form regardless of state we should use getRawValue instead of myForm.value as it serves the same purpose. I have worked with number of forms in my admin panel (event on other projects) i never had any situation where i want to exclude disabled controls.

Btw It would be great if angular team can implement optional third param as i mentioned above with that we do not have to take care anything one method for every situation.

**Comment by criskrzysiu** [comment]
I also don't understand the logic behind removing the disabled form control value from the value property. What's the underlying reason for this?

**Comment by indraraj26** [comment]
Here one more strange things in form
here i am getting both value even both controls are disabled 
```
     this.parentForm.get('child').disable();
     console.log(this.parentForm.value) //  {child: {data: 'data1', name: 'name1}}
 ```
 here i am getting data value only
```
    this.parentForm.get('child').get('name').disable()
    console.log(this.parentForm.value) // {{child: {data: 'data1'}}}
```

Playground Stackblitz: https://stackblitz.com/edit/angular-ivy-3zk75s?file=src%2Fapp%2Fapp.component.html

**Comment by DavideViolante** [comment]
I think the default behaviour should be getting all the values, even if they are disabled. Disabled doesn't mean undefined or null. A form can be disabled but containing values inside.
My use case was the following:
- a user is able to submit a form for themself or (if they have permission) for another person. So there is a select element where they can select another person. If the user has no permission, the select is visible but disabled and the value inside is valid and required to submit the form.

**Comment by dylhunn** [comment]
Basically, this issue is about the default behavior of a form when submitted: disabled controls are excluded. If you need to get disabled controls, you can use `getRawValue`. Without lots of community interest, it doesn't seem worth the API complexity or bundle size cost to add this feature.

Note also: we are considering adding a [readonly](https://github.com/angular/angular/issues/11447) state to form controls which *would* be submitted; this might be a workaround if implemented.
