### ISSUE TITLE
Access "angular2" components from developer tools console.

### ISSUE THREAD

**Issue by alexpods** [angular/angular#3689]
This issue came from [this StackOverflow question](http://stackoverflow.com/questions/32052432/how-to-access-the-angular-2-components-data-in-the-browsers-console). As far as I know right now there isn't any easy way to get angular2 component from native DOM element. For example I have a compiled DOM:

```html
<body>
  <my-app>
    <div>Some content</div>
  <my-app>
</body>
```

I know that `my-app` is angular2 component, but I don't have access to it. And this is cool for production mode: incapsulation, security and so on... But for development mode I think It would be very handy if I could do something like:

```js
console.log(document.querySelector('my-app').component.someComponentProperty)
```

What do you think, guys?

**Comment by mhevery** [comment]
This is on our roadmap.

**Comment by cironunes** [comment]
:heart:

**Comment by tbosch** [comment]
We have `ngProbe(element)` as global function. To activate, pass the following binding to bootstrap:
`bind(AppViewListener).toClass(DebugElementViewListener)`.

**Comment by ollwenjones** [comment]
@tbosch In the repo I'm working on upgrading to beta.3 `DebugElementViewListener` doesn't seem to exist anymore ?? Did it's functionality get moved somewhere else?

**Comment by mhevery** [comment]
Yes see https://github.com/angular/angular/commit/e1bf3d33f8a1fa05a832b9b7ee1300ef9862fd0b

replacement is `ng.probe(element)`

**Comment by zoechi** [comment]
I'm still not able to figure out how to make `ng.probe()` available in the browser console. I get `ng.profiler` listed but no `ng.probe()`.

**Comment by pankajparkar** [comment]
+1

**Comment by vaseker** [comment]
@zoechi `enableDebugTools(ComponentRef)` makes `global.ng = new AngularTools(ref)` 
https://github.com/angular/angular/blob/master/modules/angular2/src/platform/browser/tools/tools.ts#L19
