### ISSUE TITLE
Root component doesnot support @Input

### ISSUE THREAD

**Issue by symphony2014** [angular/angular#36898]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

No

### Description

 I just found the decorator `@Input` doesnot work on root component inside the `index.html`.

## 🔬 Minimal Reproduction

 
https://stackblitz.com/edit/angular-m9462h

## 🔥 Exception or Error
<pre><code>

"hello,world" should be showed on view.
</code></pre>

## 🌍  Your Environment

**Angular Version:*9.1.0*
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/1858 5 years old :p
