### ISSUE TITLE
It's time to give more informations about ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by hmzlam** [angular/angular#36899]
Would you please show in the console the file or zone where ExpressionChangedAfterItHasBeenCheckedError is triggred

Angular get's better over time but this is the only error with no information is available to debug it.

**Comment by ajitsinghkaler** [comment]
Actually I think docs on change detection are missing. It is part of change detection so that is why it has no documentation

**Comment by kara** [comment]
@hmzlam Are you using Ivy and Angular 9? If so, you can click on the template function to be taken to the line that caused the error.

**Comment by pkozlowski-opensource** [comment]
Going to close this ticket for now as the mentioned error should be giving much better info in Angular 9+ with ivy enabled. Also, we haven't hard back from the author. Happy to re-open if / when we've got more info that would make this ticket more actionable
