### ISSUE TITLE
Add *ngTemplateOutlet context example in docs

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#36895]
# 📚 Docs or angular.io bug report

### Description
In which situation we can use ngTemplateOutlet and its context. and what $implicit does?
Thank you.

### What's the affected URL?**
 https://angular.io

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by destus90** [comment]
Hasn't it been documented enough? https://angular.io/api/common/NgTemplateOutlet#description

**Comment by indraraj26** [comment]
It would be great if we can have little more documented how to use ngFor with ngTemplateOutlet

**Comment by pauldraper** [comment]
There's nothing special about ngFor and ngTemplateOutlet.

There are some words about using multiple structural directives (though not those two specifically): https://angular.io/guide/structural-directives#one-structural-directive-per-host-element

**Comment by indraraj26** [comment]
Still i don't get how to use ngTemplateOutletContext to pass context to child component

playground: https://stackblitz.com/edit/angular-9iqfuj?file=src%2Fapp%2Fchild%2Fchild.component.html

**Comment by pauldraper** [comment]
@indraraj26 I'm confused by the example. I think you have some typos.

Fixed: https://stackblitz.com/edit/angular-empgzq

**Comment by indraraj26** [comment]
actually i want to pass this from app.component to child.component through get those context and use it on ngTemplateOutletContext

```
  smart = {
     $implicit: 'meoow',
     test: [1,2,3]
   }
```

I see you are just iterating child component array instead of app component data. If you console log you will see their you will see context

```
  @Input() set smartTemplate (data: TemplateRef<any>)  {
         console.log(data)
  };
 
```
> @indraraj26 I'm confused by the example. I think you have some typos.
> 
> Fixed: https://stackblitz.com/edit/angular-empgzq

**Comment by kapunahelewong** [comment]
Status: docs team will need SME to create documentation.

**Comment by LayZeeDK** [comment]
Plenty of subject matter experts available in the Angular community.

**Comment by kapunahelewong** [comment]
Thanks, @LayZeeDK! Yes, this community is top notch! SMEs in the community are integraland personally, I've benefited a great deal from their willingness to share knowledge. 

My note is just to help with issue organization and planning so that if someone (who potentially may not be familiar with this topic) is figuring out how to approach this issue, that they know a writer will need to pair with an SME. That way they can make sure to allocate the appropriate resources and coordinate people pairing.

**Comment by aikidave** [comment]
I think we can close this issue? We now have a topic on Content Projection that talks about ngTemplateOutlet, which was added with https://github.com/angular/angular/pull/41143.

I'm sure there's more we can do with this topic, however! Feel free to open another issue for suggestions if you like!
