### ISSUE TITLE
Adding a folder structure detail for better understanding of Angular Framework

### ISSUE THREAD

**Issue by deepamgupta** [angular/angular#36903]
# 📚 Docs or angular.io bug report

### Description

 Notes for a better explanation of the folder structure of Angular Framework for better understanding.

### What's the affected URL?**
https://github.com/deepamgupta/angular/blob/master/README.md

## 📷Screenshot

![Screenshot from 2020-05-04 01-17-01](https://user-images.githubusercontent.com/36341114/80924162-0e76ac00-8da5-11ea-9a11-233974522543.png)

**Comment by santoshyadav198613** [comment]
You can check the existing doc here https://angular.io/guide/file-structure

**Comment by ajitsinghkaler** [comment]
@santoshyadav198613 I think he asking the folder structre of Angular repo and the link you have gives tells us the folder structure of the angular workspace

**Comment by santoshyadav198613** [comment]
> @santoshyadav198613 I think he asking the folder structre of Angular repo and the link you have gives tells us the folder structure of the angular workspace

"better understanding of Angular Framework" he is not referring to Angular repo but the workspace I think @deepamgupta  can you confirm?

**Comment by ajitsinghkaler** [comment]
Yes I see most of the files are workspace files

**Comment by deepamgupta** [comment]
Yes, I'm new to angular. While learning, I thought that there should be a description of folder structure of workspace. Btw, Thanks @santoshyadav198613 for the link.

**Comment by santoshyadav198613** [comment]
> Yes, I'm new to angular. While learning, I thought that there should be a description of folder structure of workspace. Btw, Thanks @santoshyadav198613 for the link.

Welcome, you can close the issue and PR in that case 😊

**Comment by deepamgupta** [comment]
Ok sure.
