### ISSUE TITLE
Issue with "ERROR: unknown browser found in getBrowsersFromCLI()" when running tests locally

### ISSUE THREAD

**Issue by jessegood** [angular/angular#3691]
I tried running the test suite locally (`npm test`) as documented in https://github.com/angular/angular/blob/master/DEVELOPER.md.
However [this line](https://github.com/angular/angular/blob/master/scripts/ci/test_js.sh#L16) in the bash script adds `ChromeCanary`. As a result, it caused [this line to throw](https://github.com/angular/angular/blob/master/gulpfile.js#L559) from gulpfile.js when running the `test.unit.js/ci` task.

Suggestion: Remove `ChromeCanary`?

**Comment by mhevery** [comment]
I think those are for CI. Devs should be using `gulp test.unit.js`

**Comment by tomascharad** [comment]
+1

**Comment by tomascharad** [comment]
In seems that sauce.conf.js doesn't have 'SL_CHROMECANARY'

**Comment by pkozlowski-opensource** [comment]
@mlaval Marc, do you think it might be somehow linked to the latest Sauce changes?

**Comment by mlaval** [comment]
@pkozlowski-opensource It is, I've sent a fix in #3806

**Comment by mlaval** [comment]
Fix landed as bf4b75ee9c8a3af896d1921462902bb4dad3da3d
