### ISSUE TITLE
Not able to create a new angular project on my windows machine.

### ISSUE THREAD

**Issue by rakeshroshan0398** [angular/angular#36913]
npm WARN deprecated tslint@6.1.2: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.12: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\rollup\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! Unexpected end of JSON input while parsing near '...mark":"~1","microtime'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kotresh\AppData\Roaming\npm-cache\_logs\2020-05-04T06_47_05_673Z-debug.log

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem)

**Comment by adibhosale** [comment]
@rakeshroshan0398 is your Issues resolved? please share the link to the new issue raised by you for the same.

**Comment by rakeshroshan0398** [comment]
> @rakeshroshan0398 is your Issues resolved? please share the link to the new issue raised by you for the same.

No Adi, thanks for asking it. Please find the link to the posted issue on stackoverflow.
https://stackoverflow.com/questions/61605380/angular-9-issue-unable-to-run-the-initial-application

**Comment by adibhosale** [comment]
Welcome. We can discuss the issue there on Stackoverflow.  
Thanks
