### ISSUE TITLE
Override existing css classes with new classes.

### ISSUE THREAD

**Issue by ramprakashram** [angular/angular#36911]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....

### Description
 
i am having a peculiar scenario in which i need to override the existing classes i defined in the angular component's scss file. Based on the scenario, i will get a string of classes with styles from the api. Those styles will will have class name of that component with updated styles. I need to update that component and override the existing styling. I cannot use ngclass or ngstyle for this, as i will be getting an string of all the classes in the component with some updated styles. This will be unique for a component i.e each component should override the existing styles defined in its individual stylesheet. How do i override the entire individual style of an component.?? Thanks in Advance.

### Describe the solution you'd like
 If Renderer API have a new method to override the exisiting css class with new styles.

### Describe alternatives you've considered

 I am manually parsing the styles in the ts and update the dom using renderer API.

**Comment by criskrzysiu** [comment]
well You can use `ViewEncapsulation.None`, and just apply styles through `<style>` tag.

**Comment by ramprakashram** [comment]
@criskrzysiu That actually does not allow us to override the existing classes from typescript at runtime huh ???
