### ISSUE TITLE
Applying a style.color to input placeholder

### ISSUE THREAD

**Issue by wadie** [angular/angular#36928]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

NO

### Description

When adding a `[style.color]` to an input field, that color is expected to be applied to the input text as well as the placeholder.
It seems that the expected behavior is fine on Firefox, but on Chrome the color of the placeholder falls back to default like shown in the Stackblitz example below.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-gvssfb?file=src/app/app.component.html

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.0.4
Node: 10.18.0
OS: darwin x64
Angular: 7.0.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        7.0.4
@angular/cli                      7.0.4
@angular/flex-layout              7.0.0-beta.19
@ngtools/webpack                  6.0.8
@schematics/angular               7.0.4
@schematics/update                0.10.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.8.3
</code></pre>

**Anything else relevant?**
It occurs on Google Chrome Version 81.0.4044.129 (Official Build) (64-bit).
Works fine on Firefox.

**Comment by indraraj26** [comment]
I don't think so it will be consider as bug because i am having same behavior with vanilla js
to apply color to placeholder
```
 input::placeholder {
     color: red;
    }

```

**Comment by wadie** [comment]
@indraraj26 I believe that's how you'd do it for Chrome

```
::-webkit-input-placeholder {
    color:red;
}
```

**Comment by indraraj26** [comment]
if you bind [style.color] i would expect make input color what you type in input not placeholder.

> @indraraj26 I believe that's how you'd do it for Chrome
> 
> ```
> ::-webkit-input-placeholder {
>     color:red;
> }
> ```

It is global pseudo class for make any input placeholder red

**Comment by wadie** [comment]
Why ? I'm binding the color of the input which is the text+placeholder..

At least that's the way it works on Firefox..

**Comment by pkozlowski-opensource** [comment]
I can effectively see the difference between Chrome and FFox in terms of styling placeholder's text:
* it is gray-ish in Chrome
* it is green-ish in FFox 

Having said this, the observed discrepancy has nothing to do with Angular, as I can observe the same effect with vanilla HTML, without any Angular involvement, see:  https://stackblitz.com/edit/typescript-ufp1pz?file=index.html

**Comment by pkozlowski-opensource** [comment]
I'm going to close this issue as it is outside of Angular's scope and we can't do anything about the issue here in this project.
