### ISSUE TITLE
Service Worker failed to load

### ISSUE THREAD

**Issue by himanshugarg574** [angular/angular#36949]
# 🐞 bug report

### Affected Package
@angular/service-worker

### Is this a regression?
I haven't tested this functionality in previous versions of the package.

### Description
While importing ServiceWorkerModule in my `app.module.ts`, I provided script name as `my-worker,js` instead of default `ngsw-worker.js`. After I built my application, service worker was generated with `ngsw-worker.js` filename instead of one that I provided in configuration. Also, when I launched my application It threw a 404 on `my-worker.js `

## 🔬 Minimal Reproduction
This was on a brand new angular project. [Project on github](https://github.com/himanshugarg574/angular-issue)

## 🔥 Exception or Error

![1](https://user-images.githubusercontent.com/10850446/81179451-4bba8400-8fc7-11ea-8944-151a0ef58c0d.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
    _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.7
Node: 12.3.1
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
NA

**Comment by gkalpak** [comment]
@himanshugarg574, `ServiceWorkerModule#register()` method is not configuring the build. It where you register your SW script. Currently, the name of the SW script is not configurable (so `ng build --prod` will always produce an `ngsw-worker.js` script), but you are free to rename the file after the build has been completed.

Closing since this works as intended.

**Comment by himanshugarg574** [comment]
Yeah got it. Thanks.
