### ISSUE TITLE
@ContentChild and @ContentChildren in directive don't find component that is targeted in selector

### ISSUE THREAD

**Issue by juliancarrivick** [angular/angular#36945]
# 🐞 bug report

### Affected Package
Not sure.

### Is this a regression?
Yes, the previous version in which this bug was not present was: 8.2.14

### Description
I have been using a directive to apply custom logic to a third party component by targeting the component with the directive's selector with some additional attributes to customise the logic. In the directive it gets a reference to the third party component using `@ContentChild` then in `ngAfterContentInit()` it calls the public interface to customise it.

Unfortunately, after upgrading to Angular 9, this behaviour seems to have changed, and the component instance is undefined in `ngAfterContentInit()`. 

## 🔬 Minimal Reproduction
I was unable to reproduce this in Stackblitz for an unknown reason, but you should be able to reproduce by cloning https://github.com/juliancarrivick/angular-9-content-child-bug and executing `ng serve`. You will get a alert of `Child is not defined`. Note that `@ContentChild` is used in this example, but `@ContentChildren` also has the same issue, with the querylist having a length of 0.

If you checkout the commit before the upgrade to Angular 9 and run `ng serve` you will notice that you get an alert of `Child is defined` instead.

## 🔥 Exception or Error
The property that is decorated with `@ContentChild` is never defined.

## 🌍  Your Environment

**Angular Version:**
<pre><code>$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.4
Node: 10.15.3
OS: win32 x64

Angular: 9.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
If I alter the directive to targeting the parent element (in the repros case, target `div[appAlterChild]` and wrap `<app-child>` in `<div appAlterChild>`) then `@ContentChild` and `@ContentChildren` are populated as you would expect.

This is arguably consistent with the naming of `@ContentChild` and `@ContentChildren`, but it is a regression, unless there's an option that isn't documented (or that I could find!) which reverts the behaviour.

**Comment by pkozlowski-opensource** [comment]
Here is a minimal reproduce scenario in ng-run: https://ng-run.com/edit/xR0XUDYenymzk66bL8Up?open=app%2Fapp.component.ts

It is a known breaking change in ivy (we consider this a bug fix) - content queries will _not_ pick up elements from its host. A simple change to make this directive compatible with ngIvy is to _inject_ child component: https://ng-run.com/edit/6eYYpeZqQBbEIE6GMW83

**Comment by juliancarrivick** [comment]
Brilliant, that's exactly what I needed and works perfectly. Thanks for that 😃 

Is there any documentation on getting access to the host component like that? It would have helped me immensely if the `@ContentChild` or `@ContentChildren` documentation had said that they don't match the host, and if you need to do that just to inject it into the constructor.
