### ISSUE TITLE
replace traceur polyfills in angular 2

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#3694]
We need to investigate and find a replacement for polyfills still in use at runtime.

**Comment by vicb** [comment]
I think ts2dart rely on us using the Traceur's polyfills. If we use some other polyfills, we probably need to update ts2dart at the same time.

@mprobst is that correct ?

**Comment by mprobst** [comment]
ts2dart relies on the symbols `Iterable`, `Symbol`, and `Map` being defined in a file called `angular2/traceur-runtime.d.ts`. It's easy to change that, and we could also support two different locations for a while to make the upgrade easier.

**Comment by jeffbcross** [comment]
I'm going to move this to the next milestone since I'm focusing on re-arranging modules and other stuff that's part of #3458.

**Comment by alexeagle** [comment]
@rkirov fixed this last week by using es6-shim instead.
