### ISSUE TITLE
i18n within foreignObject doesn't work with nested tags

### ISSUE THREAD

**Issue by Goodwine** [angular/angular#36941]
# 🐞 bug report

### Affected Package

@angular/compiler
Angular i18n

### Is this a regression?

No

### Description
An `svg` element with `foreignObject` can contain any kind of HTML tags like `<div>` or `<span>`.
However If a `span` is nested inside a `div` that contains `i18n` the build breaks.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-va9pj8?file=src%2Fapp%2Fapp.component.html
See the comment about removing `i18n`

## 🔥 Exception or Error
```
Error in /turbo_modules/@angular/compiler@9.1.0/bundles/compiler.umd.js (21449:23)

Unexpected closing tag "xhtml:span". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("Lorem ipsum dolor sit amet, <:xhtml:span class="foo">rutrum[ERROR ->]</:xhtml:span> imperdiet eros."): ng:///AppModule/AppComponent.html@0:59
```

## 🌍  Your Environment

**Angular Version:**
9.x

**Anything else relevant?**
Existing workaround is to move the HTML from within `<foreignObject>` to an `<ng-template>`
https://stackblitz.com/edit/angular-hfqm3v?file=src/app/app.component.html
```diff
<svg:g>
  ...
  <foreignObject>
    <xhtml:div>
      ...
-      <div i18n="asd">x<span>{{foo.bar.baz //i18n(ph="name")}}</span></div>
+      <ng-container *ngTemplateOutlet="myTemplate; context: {name:foo.bar.baz}">
+      </ng-container>
    </xhtml:div>
  </foreignObject>
</svg:g>
+<ng-template #myTemplate let-name="name">
+  <div i18n="asd">x<span>{{name //i18n(ph="name")}}</span></div>
+</ng-template>
```

**Comment by AndrewKushnir** [comment]
Hi @Goodwine,

Thanks for reporting the issue. I've performed additional investigation and found out that this problem affects View Engine only and the same use-case works correctly in Ivy. I've created https://github.com/angular/angular/pull/36943 with additional tests to confirm that.

Thank you.

**Comment by petebacondarwin** [comment]
Since ViewEngine is deprecated and this is fixed in Ivy, I am going to close this.
