### ISSUE TITLE
angular documentation Error: loading chunk failed

### ISSUE THREAD

**Issue by essoShopbox** [angular/angular#36947]
# 📚 Docs or angular.io bug report

### Description
I know it common and known issues but it has to be reported so here what happen when open a angular docs after while it's not loaded correctly and opening the console found a lot of errors lines
the error of serve responded with a status 404
then Error preparing document 'cli/serve' : ChunkLoadError: Loading chunk 15 failed

## 🔬 Minimal Reproduction
I think that the deploying many times with small changes to the versions will cause the problem

### What's the affected URL?**
https://angular.io/

## 📷Screenshot
[Screen shot](https://imgur.com/kNkWZac)

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by ericmartinezr** [comment]
That's being tracked here https://github.com/angular/angular/issues/28114, also as a workaround clean your cache and see if it works.
