### ISSUE TITLE
Formcontrol value depends on constructor parameter type

### ISSUE THREAD

**Issue by hodossy** [angular/angular#36946]
# 🐞 bug report

### Affected Package
`@angular/forms`

### Is this a regression?
No.

### Description
Form control values are different if instantiated through the `FormBuilder` service with initial value or a state object.

One would expect the same value no matter what notation is used to construct the control. `null` is my preferred value.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-issue-repro2-kctpbt

## 🔥 Exception or Error
None

## 🌍  Your Environment

**Angular Version:**
Same on stackblitz with angular 6 and 9.

**Anything else relevant?**

**Comment by destus90** [comment]
@hodossy 
Is the StackBlitz demo broken? On my screen a weird error is displayed `Can't find package:core-js`.

**Comment by hodossy** [comment]
Hey, I fixed it. It is actually a [stackblitz issue](https://github.com/stackblitz/core/issues/930).

**Comment by destus90** [comment]
I have found the cause of the inconsistent behavior. The FormControl class constructor looks like 
https://github.com/angular/angular/blob/ecffc3557fe1bff9718c01277498e877ca44588d/packages/forms/src/model.ts#L1053-L1056
So, when you pass `undefined` as the first parameter, it will be replaced by the default value (`null` in that case).

**Comment by JeanMeche** [comment]
Should it this be closed in favor of #47027 which is more up-to-date with the typed forms ?

**Comment by JeanMeche** [comment]
I'll close this is favor of #47027.
