### ISSUE TITLE
Incorrect description of navigateByUrl method of Router class

### ISSUE THREAD

**Issue by eugenebmx** [angular/angular#36951]
# 📚 Docs or angular.io bug report

### Description

The navigateByUrl method description says that it accepts only absolute URLs. 
`@param url An absolute URL. The function does not apply any delta to the current URL`
https://github.com/angular/angular/blob/9.1.4/packages/router/src/router.ts#L991

Usage notes show examples of relative URLs.
https://github.com/angular/angular/blob/9.1.4/packages/router/src/router.ts#L999-L1006

Absolute URLs are the ones complying with the pattern scheme://server/path/resource. Therefore, the method's URL parameter description is incorrect. The parameter should be a relative URL.

**Comment by kapunahelewong** [comment]
Status: docs team, I think there's enough info here to fix the doc.

**Comment by cesperian** [comment]
@aikidave i'll take this one, please

**Comment by atscott** [comment]
This is technically correct when talking about URLs, it's more confusing and incorrect when talking about route paths.
The documentation for behavior of the`navigateByUrl` is correct. The route path is absolute. The method likely should have been named "navigateByPath" or something similar.
Closing.
