### ISSUE TITLE
Ability to add extraProviders on BootstrapModule

### ISSUE THREAD

**Issue by kristofdegrave** [angular/angular#36952]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
The ability to add additional (static) providers when bootstrapping the module. This allows to provide additional services or configuration at runtime when bootstrapping a module, which are specific for the module that is getting bootstrapped.

### Describe the solution you'd like
Extend the current bootstrapOptions with an additional collection of providers for the module. 
https://github.com/angular/angular/blob/ecffc3557fe1bff9718c01277498e877ca44588d/packages/core/src/application_ref.ts#L228-L258

These additional providers can be added to the injector which gets created to provide the NgZone for the module.
https://github.com/angular/angular/blob/ecffc3557fe1bff9718c01277498e877ca44588d/packages/core/src/application_ref.ts#L310-L315

### Describe alternatives you've considered
Additional Providers can be added to the platformBrowserDynamic callback, but once a platform is created, these values can't change and they are equal for all modules that get bootstrapped.

**Comment by pkozlowski-opensource** [comment]
You could do it today by creating a `NgModule` that has a desired providers and imports a NgModule that you wanted to bootstrap in the first place. This is supported today but If I understand it correctly you are asking for the syntactic sugar here.

The good news is that in v14 we are introducing the new `bootstrapApplication` where you can directly configure static providers!
