### ISSUE TITLE
@angular/language-service doesn't suport pipes with overloaded transform method

### ISSUE THREAD

**Issue by SchnWalter** [angular/angular#36966]
# 🚀 feature request

### Relevant Package

This feature request is for `@angular/language-service`

### Description

Currently, pipes that contain overloaded transform methods, are not accepted by the language service. For example, this simple pipe with two method signatures will have 2 distinct errors with valid use cases:
```
@Pipe({
  name: 'translate',
})
export class TranslatePipe implements PipeTransform {
  transform(value: string, namespace?: string): string;
  transform(value: string, params?: string | Record<string, string>, namespace?: string): string {
    console.log('transforming...');
  }
}
```
The first error is:
```
Argument type Record<string, string> is not assignable to parameter type string | undefined
```
When using the pipe like this:
```
<p>{{ 'with.params' | translate:stringParams }}</p>
```

And the 2nd error is:
```
Invalid number of arguments, expected 1..2
```
When using the pipe like this:
```
<p>{{ 'with.params.and.namespace' | translate:stringParams:featureNamespace }}</p>
```

Judging by the errors, the language service takes into account only the first method signature.

To reproduce this, you can run `ng serve` in this example Angular v10 repository:

> https://github.com/SchnWalter/ng-pipe-method-overloading-issue

And check the browser to see that everything is working with a single method signature, then uncomment the 2nd one and you will see that the application compiles successfully after the change and it still works properly, but now both the IDE and Angular Compiler will show the 2 type of errors that I've listed above.

This is the log output with a comment inserted where the 2nd signature was un-commented.
```
> ng serve

chunk {main} main.js, main.js.map (main) 14.5 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 141 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 12.4 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 2.72 MB [initial] [rendered]
Date: 2020-05-06T23:28:28.055Z - Hash: 1758942286bf1bc9d64f - Time: 5877ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.

///// UN-COMMENT METHOD SIGNATURE...

Date: 2020-05-06T23:28:37.928Z - Hash: a3489c657d7e6a14600e
4 unchanged chunks
chunk {main} main.js, main.js.map (main) 14.3 kB [initial] [rendered]
Time: 227ms
: Compiled successfully.

    ERROR in src/app/app.component.ts:8:37 - error TS2345: Argument of type 'Record<string, string>' is not assignable to parameter of type 'string'.

    8     <p>{{ 'with.params' | translate:stringParams }}</p>
                                          ~~~~~~~~~~~~
    src/app/app.component.ts:9:67 - error TS2554: Expected 1-2 arguments, but got 3.

    9     <p>{{ 'with.namespace.undefined.params' | translate:undefined:appOneNamespace }}</p>
                                                                        ~~~~~~~~~~~~~~~
    src/app/app.component.ts:11:64 - error TS2554: Expected 1-2 arguments, but got 3.

    11     <p>{{ 'with.params.and.namespace' | translate:stringParams:appOneNamespace }}</p>
                                                                      ~~~~~~~~~~~~~~~
```

### Describe alternatives you've considered

TypeScript method overloading is a "nice to have" feature, but it's not a deal breaker.

**Comment by lincolnthree** [comment]
This appears to be a problem even in the latest Angular `12.0.0-rc` builds. It means we have to completely disable `strictTemplates: true` in `angularCompilerOptions` to get a production build done. This is problematic since it means our production builds could in theory leak bugs that would otherwise be caught.

Seems like this is a somewhat insidious issue, as it encourages circumventing the template type-safety features Angular has worked so hard to create.

**Comment by JoostK** [comment]
The Ivy language service will now type-check pipe invocations according to overload resolution as done by TypeScript, so closing as resolved.
