### ISSUE TITLE
LazyLoad route without navigation

### ISSUE THREAD

**Issue by Marka83** [angular/angular#36977]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/router

### Description
Router has navigateByUrl method which resolves full path, loads lazy loaded modules, populates config and navigates to that Url.
But what if I want to show component in a Dialog (and not navigate from current component), but I want to be sure that component is loaded with all its dependencies wired up.

### Describe the solution you'd like
I would like to have some method like router.resolveUrl (or resolveRoute) with same parameters as navigateByUrl. It would do all the things like navigateByUrl, except for navigation itself.
Then, navigateByUrl could use that same method and navigate if Url was resolved correctly.
By doing that, I could check router.config to see if route is resolved.
If it's not, I would call resolveUrl... or even better, I could call resolveUrl every time and within that method you could check if it's already resolved.

### Describe alternatives you've considered
I know there is a way to manually lazy load module and component, but in order to be sure that all dependencies are resolved, I would have to duplicate code from RouterConfigLoader.

Then, I would have to store that component somewhere, so I would have to duplicate router.config.

Also, in order to handle all the cases for resolving url, I would have to duplicate most of the Router.

It would be much simpler to just move that subset of router functionality into separate method.
This would allow people like me to use it directy and you could use that same method within navigateByUrl method. 

There are some post about that like this:
https://medium.com/@ckyidr9/lazy-load-feature-modules-without-routing-in-angular-9-ivy-220851cc7751

but if I want to create some generic component I couldn't easily replicate what router is doing.

**Comment by atscott** [comment]
Hi @Marka83, thanks for your feature request. This appears to be achievable by creating a preloading strategy like this one: https://johnpapa.net/predictive-preloading-of-your-angular-bundles/. Is that something you've considered?

**Comment by Marka83** [comment]
This looks promising. I'll give it a try. Thank you.

**Comment by Marka83** [comment]
It works with minor modification! You can close this.
