### ISSUE TITLE
core.js:12662 Can't bind to 'ngforOf' since it isn't a known property of 'div'.

### ISSUE THREAD

**Issue by kprajaguru** [angular/angular#36976]
Hi, 

I am developing an app from my organization just a pilot app nothing so important about it. 

To be honest, am new to Angular coding and now have stuck upon an error mentioned in the title. 

I have searched the GIT forum for this error, everywhere has said about this issue either been made inactive or fixed in the Angular 9. 

Am using Angular I still get this issue so am trying to open an new one.

Am trying to loop through my json object and dynamically create accordions for the same. I have masked my json data for security purposes. 

![Issue](https://user-images.githubusercontent.com/64559062/81287063-c34bea00-907f-11ea-96d0-956acd1e0cc0.jpg)
 
** These are the packages that I have included in the App module **
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { CSPDailyTrackerComponent } from './cspdaily-tracker/cspdaily-tracker.component';
import { CSPReportingComponent } from './cspreporting/cspreporting.component';
import { HomeComponentComponent } from './home-component/home-component.component';
import { NgxPopper } from 'angular-popper';
import {NgbModule} from '@ng-bootstrap/ng-bootstrap';
import {FormsModule} from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import {CommonModule} from '@angular/common';

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by petebacondarwin** [comment]
Thanks @ericmartinezr
