### ISSUE TITLE
paramMap not giving param "id" in angular official example. Select not working in list

### ISSUE THREAD

**Issue by 2manoj1** [angular/angular#36970]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
https://bnrokodnokg.angular.stackblitz.io/crisis-center/2
In crisis-list should select id 2 but not selected in list. Also parammap not providing id in onInit. 

## 🔬 Minimal Reproduction

 https://stackblitz.com/...
https://stackblitz.com/angular/bnrokodnokg?file=src%2Fapp%2Fapp-routing.module.ts

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

"@angular-devkit/build-angular": "~0.901.1",
 "@angular/cli": "~9.1.1",
 "@angular/compiler-cli": "~9.1.1",
 "@angular/language-service": "~9.1.1"
</code></pre>

**Anything else relevant?**

**Comment by kapunahelewong** [comment]
Thanks for bringing this up, @2manoj1. I believe the `selectedId` shouldn’t be in the `crisis-list.component.ts` `ngOnInit()` at all, only in the `hero-list.component.ts` `ngOnInit()` because the only place the router tutorial covers `selectedId` is in [Milestone #3](https://angular.io/guide/router#route-parameters-in-the-activatedroute-service) and that's for styling. Am I correct in understanding what you're referencing?

**Comment by 2manoj1** [comment]
paramMap not providing data.  Css class not append because selectedId always 0.
PFA for more details
check ```this.selectedId = +params.get('id');```
<img width="1792" alt="Screenshot 2020-05-27 at 3 37 04 PM" src="https://user-images.githubusercontent.com/15128569/83006941-952f4980-a030-11ea-886a-4bea7ece8683.png">


<img width="1792" alt="Screenshot 2020-05-27 at 3 39 52 PM" src="https://user-images.githubusercontent.com/15128569/83006952-9791a380-a030-11ea-8a3e-c1b55f2cd58f.png">

**Comment by kapunahelewong** [comment]
Oh, thanks for clarifying, @2manoj1! The screenshots are helpful, too. 😊

Status: docs team might be able to correct/figure this one out. If not, might need an SME. Will mark for docs team presently. If docs team member finds a need for an SME, we may need to change the labels to require engineering input.
