### ISSUE TITLE
Make AIO content strictPropertyInitialization compliant

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#36978]
# 📚 Docs or angular.io bug report

### Description
In Angular CLI version 10, we introduced a new flag `--strict, we are also considering making this the default behaviour in the future. 

The `strict` option will enable stricter type checking and build optimization settings, one of them being `strictPropertyInitialization`.

Currently this option is explicitly disable in AIO https://github.com/angular/angular/blob/f7815cf96defa6b19fff482824c5997f03fd78ea/aio/tsconfig.json#L23-L24 We should remove this option (turn it on), and make sure all of our the examples are `strictPropertyInitialization` compliant.

More context: https://github.com/angular/angular-cli/pull/17372#discussion_r419681606

**Comment by JeanMeche** [comment]
Our examples don't use the local tsconfig from the aio project. They rely on the config generated from this one : 

https://github.com/angular/angular/blob/125fe19086e3c845816d46c990899fd3edc1ebbe/aio/tools/examples/shared/boilerplate/cli/tsconfig.json#L2-L26

So I'll close this issue as `strictPropertyInitialization` is already enabled on the examples !
