### ISSUE TITLE
dgeni outputs partial templates for aliases but should inline them

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#3699]
Under `http`, we export doc templates for two aliases, `RequestOptionsArgs` and `ResponseOptionsArgs`. Need to update the template so that these are inlined into the method signature, not independent docs.

**Comment by mhevery** [comment]
@btford Here is what should happen for `RequestOptionsArgs` and `ResponseOptionsArgs` They should be inlined everywhere they are used like this example.

```
 merge(options?: ResponseOptionsArgs): ResponseOptions
```

bocomes

```
 merge(options?: {
  body?: string | Object | FormData;
  status?: number;
  statusText?: string;
  headers?: Headers;
  type?: ResponseTypes;
  url?: string;
}): ResponseOptions
```

**Comment by btford** [comment]
What makes something an "alias" ?

The same in-lining needs to be done for `RouteDefinition` in the router.

I expect this to be non-trivial, but will do some investigatory work to see. Probably not going to happen this week though.

**Comment by mhevery** [comment]
interface 

```
interface Person { name: string }
```

alias:
```
type Person = { name: string }
```

**Comment by alexeagle** [comment]
@mhevery this is just temporary until TS1.6 right? in 1.6 the semantics of declaring assignability from an interface are tightened to catch typos in property names.

**Comment by mhevery** [comment]
Correct, but we can inline them all the time in `.d.ts` as it is easier to use such a `.d.ts` file from the tools. The suggestions are more useful.

**Comment by btford** [comment]
I will not have time to work on this in the near future. Unassigning myself.

**Comment by btford** [comment]
Also with our current docs infrastructure, this will certainly take days to implement.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
