### ISSUE TITLE
Could not see dynamic meta data on view source page in Angular 8

### ISSUE THREAD

**Issue by kaalidoss** [angular/angular#36996]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Could see the dynamically updated meta data,when inspect on the same page,but could not see that change in view source page.
could you help?
( version:angular 8)
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

Btw, this is expected. The Page source only shows the HTML as downloaded from the server. Angular renders the whole application dynamically in the browser, unless you use a technique called Server-Side Rendering, e.g. using Angular Universal or Scully.
