### ISSUE TITLE
angular+Jasmine+materialized

### ISSUE THREAD

**Issue by geeks-Dev** [angular/angular#37004]
Hi Team,
I'm not able to test the app with the materialized css it is not loaded and UI became ugly when ng test is running.

**Comment by alxhub** [comment]
Hi @geeks-Dev,

Unfortunately with the limited amount of information present in this issue report, we won't be able to identify any bugs or issues for us to fix. If you're still having problems with this, can you please file a new issue and fill out the issue template, including a link to a repo or StackBlitz that clearly reproduces the problem.

Thanks,
Alex
