### ISSUE TITLE
ng-if conditions are called twice, should also short-circuit?

### ISSUE THREAD

**Issue by Zyzle** [angular/angular#3701]
Not sure if this actually a bug or not but given, http://plnkr.co/edit/exgKLQWZVQjyg5vgnqI8 the conditionals in `ng-if` appear to be called twice each. 

Additionally in JS `||` and `&&` operators both short-circuit, in `ng-if` both sides are evaluated regardless. Again I'm not entirely sure if this is the expected behaviour or not, was hoping someone could shed some light.

**Comment by vicb** [comment]
@Zyzle we don't short-circuit for the change detection (it would make the code complex and probably prevent some other optimizations).

The conditions must be evaluated twice because we want to assert that the CD is stable (ie side effect free). @vsavkin could you confirm ?

**Comment by Zyzle** [comment]
@vicb thanks for the reply. Ok that makes sense, I just couldn't find any reference to it in the documentation so it looked a little odd to myself and others (I raised this after a conversation on gitter yesterday). As for the short-circuit it's not a big deal for me, I can't actually think of a reason to rely on that behaviour, the issue was more that it went against the expectations.

**Comment by mhevery** [comment]
So the short circuiting makes sense. But we actually don't run second time due to stability assertion. (That feature is currently broken). So it is a mystery to me why we have an extra CD cycle in there. @vicb do you want to investigate? When I run it in WTF, the second CD seems to be outside the zone. There is something weird going on there.

**Comment by mhevery** [comment]
@vicb it looks like some promise is getting resolved and we run CD at the end of it. Which means we should not be doing CD the first time (only at the end of resolved promise)

**Comment by vicb** [comment]
I'll investigate

**Comment by ericmartinezr** [comment]
Was this fix merged? I'm using alpha37 and I ran into a similar issue (not sure if it's exactly the same), so I don't know if to open a new issue or use this one.

**Comment by vicb** [comment]
It has not been merged. I expect to restart working on this in the coming weeks (was pending the bootstrap refactoring which just happened)

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

The latest compiler code generation makes this obsolete.
