### ISSUE TITLE
Example HostListener docs not work

### ISSUE THREAD

**Issue by cdac901** [angular/angular#37010]
Hi, 

I follow the example in https://angular.io/api/core/HostListener#usage-notes but no work, example:
https://stackblitz.com/edit/angular-ivy-vxwhwg

**Comment by destus90** [comment]
@cdac901 you forgot to put the `CountClicks` directive class into NgModule declarations.
https://stackblitz.com/edit/angular-ivy-czjywo?file=src%2Fapp%2Fapp.module.ts

**Comment by cdac901** [comment]
Thanks!, close this issue
