### ISSUE TITLE
RAIL performance goals

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#3702]
is there any way to track the RAIL performance goals using `benchpress`?

<img width="1248" alt="screen shot 2015-08-14 at 8 22 43 pm" src="https://cloud.githubusercontent.com/assets/1016365/9343446/e50bda2e-45b6-11e5-9444-a317b5011321.png">

How Users Perceive the Speed of The Web - Paul Irish (Google) keynote
[![RAIL performance goals](http://img.youtube.com/vi/2ksXo2_Lfl0/0.jpg)](http://www.youtube.com/watch?v=2ksXo2_Lfl0)

**Comment by mhevery** [comment]
closing as this is not very actionable. We also have offline compiler which achieves these numbers.
