### ISSUE TITLE
angular cli could not found definiteyTyped type definition

### ISSUE THREAD

**Issue by reallyimeric** [angular/angular#37023]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/cli

### Is this a regression?

 No

### Description

`ng serve` did not found installed definiteyTyped type definition

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ivy-qfenf4

## 🔥 Exception or Error
<pre><code>

Cannot find name 'DirectoryEntry'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.7
Node: 14.2.0
OS: linux x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@angular/cdk                      9.2.2
@angular/material                 9.2.2
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

vscode can found the type. Call `tsc` manually also works

**Comment by angelfraga** [comment]
I 've reproduced that issue too, but I guess the issue is caused by `@types/filesystem`. 

By the way, you could fix the build by adding a custom typing file.

`./src/types.d.ts`
```
/// <reference types="filesystem" />
```

`./tsconfig.app.json`
```json
{
  ...
  "compilerOptions": { 
    "types": [
      "./src/types"
    ]
  },
   ...
} 
```

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
