### ISSUE TITLE
When using JitCompilerFactory to compile "module and component" and using "ng build aot=true" to build project, the error "No NgModule metadata found for 'function(){}'" will be find in the browser console

### ISSUE THREAD

**Issue by simba-1007080** [angular/angular#37038]
### Description

When using the function "compileModuleAndAllComponentsAsync()" of JitCompilerFactory to compiler customer module and components and using "ng build --prod --aot=true" to build project, the error "No NgModule metadata found for 'function(){}'"  always to be foud in the browser console, how to do and fixed it?
Thanks!

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre>No NgModule metadata found for 'function(){}'</pre>

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 1.7.4
Node: 6.9.5
OS: win32 x64
Angular: 5.2.11

The following is my code:
<pre>
import { NgModule, Compiler, CompilerFactory, COMPILER_OPTIONS, SystemJsNgModuleLoader } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { BComponent } from './b/b.component';
import { JitCompilerFactory } from '@angular/platform-browser-dynamic';
import { EComponent } from './e/e.component';

export function createJitCompiler(compilerFactory: CompilerFactory) {
  console.log('skkkk', compilerFactory);
  return compilerFactory.createCompiler();
}

export const RESOURCE_ROUTES: Routes = [
  {path: 'b', component: BComponent}
];

@NgModule({
  imports: [
    CommonModule
    ,RouterModule.forChild(RESOURCE_ROUTES)
  ],
  declarations: [BComponent, EComponent],
  providers: [
    SystemJsNgModuleLoader,
    { provide: COMPILER_OPTIONS, useValue: {useJit: true}, multi: true },
    { provide: CompilerFactory, useClass: JitCompilerFactory, deps: [COMPILER_OPTIONS] },
    { provide: Compiler, useFactory: createJitCompiler, deps: [CompilerFactory] }
  ]
})
export class AModule { }

import { Component, OnInit, Compiler, ComponentFactory, NgModule, ModuleWithComponentFactories, ViewEncapsulation, 
  ComponentRef, ViewChild, ViewContainerRef, NgModuleRef, PlatformRef, NgModuleFactory, AfterViewInit, 
  ComponentFactoryResolver, SystemJsNgModuleLoader, Injector
} from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-b',
  templateUrl: './b.component.html',
  styleUrls: ['./b.component.css']
})
export class BComponent implements OnInit, AfterViewInit {

  @ViewChild('container', { read: ViewContainerRef }) container: ViewContainerRef;
  private componentRef: ComponentRef<any>;

  constructor(
    private _compiler: Compiler,
    private _componentFactoryResolver: ComponentFactoryResolver,
    private _systemJsNgModuleLoader: SystemJsNgModuleLoader,
    private _injector: Injector
  ) { }

  ngOnInit() {
    
  }

  ngAfterViewInit(){
    this.compileModuleAndCmp();
  }
  
  createdComponent: any = null;
  compileModuleAndCmp(){
    this._compiler.clearCache();

@Component({
      selector: 'app-c',
      template: "<a>compiler successed !</a>",
      encapsulation: ViewEncapsulation.None
    })
    class DComponent{}

    
    @NgModule({ 
      imports: [
        CommonModule
      ], 
      declarations: [
        DComponent
      ],
      entryComponents: [DComponent] 
    })
    class RuntimeModule { }
    
    
    
    this._compiler.compileModuleAndAllComponentsAsync(RuntimeModule).then(
      (moduleWithFactories: ModuleWithComponentFactories<any>) => {
        let factory = moduleWithFactories.componentFactories.find(f => f.componentType === DComponent);
        if (this.componentRef) {
          this.componentRef.destroy();
          this.componentRef = null;
        }
        this.componentRef = this.container.createComponent(factory);
      }
    );
 }
}
</pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment]
@simba-1007080 please turn your code example into a runnable one using https://stackblitz.com/ as requested in the issue template - we need a live reproduce scenario to confirm the issue.

**Comment by alxhub** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
