### ISSUE TITLE
ERROR in node_modules/angular-custom-tour/src/index.d.ts:4:22 - error NG6002: Appears in the NgModule.imports of ListModule, but could not be resolved to an NgModule class.

### ISSUE THREAD

**Issue by nitink789** [angular/angular#37036]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by nitink789** [comment]
This has happened after I moved to angular 9 ivy

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

**Comment by santoshyadav198613** [comment]
> This has happened after I moved to angular 9 ivy
Hi @nitink789 ,
Just to update, the package which you are using is not compatible with Angular 8 and above the last commit is a year ago and works only with angular 7, you can either move to another package or raise an issue with library. https://github.com/miraxes/angular-custom-tour

**Comment by santoshyadav198613** [comment]
@pkozlowski-opensource you can close this.

**Comment by pkozlowski-opensource** [comment]
Thnx @santoshyadav198613

**Comment by nitink789** [comment]
@santoshyadav198613 But I have some other modules as well which are not updated since more than a year. How are they working ?
