### ISSUE TITLE
Angular not installed

### ISSUE THREAD

**Issue by hossein647** [angular/angular#37034]
When I install a new Angular app with the following command, it doesn't install and it only installs packages for hours.
```
ng new my-app
```
When I forcibly stop the installation and want to do a test to run the app and hit the following command, I see that no package is installed and gives the following error.
```
cd my-app
ng serve --open
```

```
An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json'
See "C:\Users\Hossien\AppData\Local\Temp\ng-sIDAvL\angular-errors.log" for further details.
```
I searched in other refrences, but the problem is not solved

--------------------------
Angular CLI: 9.1.5
Node: 10.15.1
Npm: 6.14.5
OS: windows - x64
Browser: chrome

**Comment by reallyimeric** [comment]
It seems simply you did not finish the installation. check your network to npm registry.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
