### ISSUE TITLE
Angular application deployment Error - net::ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by ErVishalM** [angular/angular#37044]
Hi,

I am using angular 9 version and created a small application. When i deploy that application to some of my servers then i am getting **Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR** but same application is working on some other server also which i tested with the same compiled files just changing the URL in main.js files. Are there any dependencies in IIS server for Angular which we need to install first. I'm not able to find any solution for this. Can you guys please help me in this. 
Here is ss for this error.
<img width="960" alt="AngularError" src="https://user-images.githubusercontent.com/43669644/81553597-03bea700-93a3-11ea-8947-56db47bac9c7.png">

Thanks

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and **follow the instructions in the issue template**.

**Comment by ErVishalM** [comment]
Hi, I found the problem, but did not get why it was working on some server and why not working for some. Problem solution i found i have created common service files so need to import those service files only in app.module and then it was working for every server. 

But anyway you've closed it. 
Thanks.
