### ISSUE TITLE
HashLocationStrategy does not change hash when redirecting in canActivate Guard

### ISSUE THREAD

**Issue by tmair-red** [angular/angular#37048]
# 🐞 bug report

### Affected Package
 The issue is caused by package @angular/router

### Is this a regression?

 No, at least I can confirm that this issue was also present in version 8 of Angular

### Description
Please have a look at the reproduction example at Stackblitz. The issue can be reproduced as follows:
1. Open the application
1. Change the URL in the URL Bar to `.../#/bar` and hit <key>Enter</key> OR change the location by entering `location.href = '#/bar` in the console.
1. The state of the application does not change (this is expected as we are on `/start`)
1. The URL still displays `.../#/bar` even though we have been redirected to `/start`.

## 🔬 Minimal Reproduction
[https://stackblitz.com/edit/angular-ivy-bejfwf](https://stackblitz.com/edit/angular-ivy-bejfwf)

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.24
Node: 12.16.1
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.24
@angular-devkit/build-angular      0.803.24
@angular-devkit/build-optimizer    0.803.24
@angular-devkit/build-webpack      0.803.24
@angular-devkit/core               7.3.9
@angular-devkit/schematics         8.3.24
@angular/cdk                       8.2.3
@angular/cli                       8.3.24
@angular/flex-layout               8.0.0-beta.27
@angular/material                  8.2.3
@angular/material-moment-adapter   8.2.3
@ngtools/webpack                   8.3.24
@schematics/angular                8.3.24
@schematics/update                 0.803.24
rxjs                               6.5.4
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Anything else relevant?**

I tried to find the issue within the router code and it seems that `this.browserUrlTree` still points to `/start` on this lines: https://github.com/angular/angular/blob/acf6075ca9aa92121bb0166b2b7560aeb2c167ff/packages/router/src/router.ts#L474..L475 
Therefore the angular router detects that the state of the application does not need to change (which is correct) but we still would need to change the URL to the one we redirected to.

**Comment by jaydeep987** [comment]
any update on this?

**Comment by atscott** [comment]
Resolved by a combination of #43102 and #43424
https://stackblitz.com/edit/angular-ivy-9ednql?file=src%2Fapp%2Fapp.module.ts
