### ISSUE TITLE
Access data of route by URL before navigation

### ISSUE THREAD

**Issue by yelhouti** [angular/angular#37041]
# 🚀 feature request

### Relevant Package

This feature request is for @angular/router

### Description
My goal is to automatically display in my menu (and other pages) only links that a user can access.
All the info required for this is usually stored within the module routes:
- the `path` field contains the string that allows to map a "url" into a component 
- The `data` field may contain the authorities for the user that can access the component

It would be great if I could retrieve the routes before loading the whole module for lazy loading purposes. Also exposing the recognize fonction of the router would allow to convert any "url" to the route and retrieve it's `data` and no whether or nor to display the link.

### Describe the solution you'd like
have the ability to bundle the routes within the main components:
globaly:
```
RouterModule.forRoot(routes, {eagerRouteData: true})
```
or Per Route
```
{
    path: 'customer',
    loadChildren: () => import('./customer/customer.module').then(m => m.CustomerModule),
    eagerRouteData: true
},
```
We should also add a fonction that would go through all the redirects if any ... and returns the route, the routeTransition, the ActivatedRouteSnapshot that would result from a navigation to that url or anything that would allow as to read the data of the destination route.

Once a spec of what needs to be coded is specified I would gladly help coding it.

**Comment by alxhub** [comment]
I believe there are better architectural patterns to achieve this, and relying on the router as the authoritative source of this data is probably not what you want to do.
