### ISSUE TITLE
Steam Trading bot

### ISSUE THREAD

**Issue by Acornhut** [angular/angular#37058]
Hey guys, I am fairly new to coding and I decided to start off with making a steam trading bot. This is the first issue I had, does anyone know what I should do? Thanks. Also, this is the tutorial I'm following: https://github.com/MaestroDesign/SteamBotProjects
![Capture 25](https://user-images.githubusercontent.com/65208262/81634999-16a29d00-93de-11ea-9a2f-dd4854a7ab2e.PNG)
    

_________________________________________________________________________________________________
C:\Users\patri\OneDrive\Documents\Trading\Tf2 bot\Chapter 1>node index.js
C:\Users\patri\OneDrive\Documents\Trading\Tf2 bot\Chapter 1\index.js:15
  client.setPersona(SteamUser.Steam.EPersonaState.Online 'Steam Bot');
                                                  ^^^^^^

SyntaxError: missing ) after argument list
[90m    at wrapSafe (internal/modules/cjs/loader.js:1047:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1097:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:977:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:877:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m
[90m    at internal/main/run_main_module.js:18:47[39m

C:\Users\patri\OneDrive\Documents\Trading\Tf2 bot\Chapter 1>pause
Press any key to continue . . .
______________________________________________________________________________________________________

**Comment by Acornhut** [comment]
oh I forgot to mention, this is the tutorial I'm following: https://github.com/MaestroDesign/SteamBotProjects

**Comment by sarunint** [comment]
This is Angular repository, not a Steam Trading Bot repository.

**Comment by Acornhut** [comment]
An Angular repository? Should it be a Steam Trading Bot repository?

**Comment by pkozlowski-opensource** [comment]
I'm sorry but this issue is not caused by Angular.
