### ISSUE TITLE
dgeni should not export  @CONST, @IMPLEMENTS, & @ABSTRACT annotations

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#3705]
These are artifacts of the ts2dart conversion process. Can we hide them in the jade output?

**Comment by naomiblack** [comment]
@petebacondarwin could you work on this one for us? I'm hoping it's easy.

**Comment by petebacondarwin** [comment]
Will look today

**Comment by naomiblack** [comment]
I'm seeing @const in my API docs again. See for example https://angular.io/docs/ts/latest/api/router/AsyncRoute-class.html

@alexeagle @petebacondarwin could you investigate?

**Comment by petebacondarwin** [comment]
For some reason this patch never made it over to angular.io

**Comment by petebacondarwin** [comment]
I copied the patch over to angular.io in https://github.com/angular/angular.io/commit/23452bffa0676341c7fcb4d95ac7537453fed359

That should fix it.
