### ISSUE TITLE
Angular issue template on stackblitz should be updated

### ISSUE THREAD

**Issue by Maximaximum** [angular/angular#37063]
# 📚 Docs or angular.io bug report

### Description
The Angular [bug issue template](https://github.com/angular/angular/blob/master/.github/ISSUE_TEMPLATE/1-bug-report.md) contains a link to a [stackblitz template](https://stackblitz.com/fork/angular-issue-repro2). However, the stackblitz template is quite outdated - it was created for Angular 6. 

The stackblitz template's npm dependencies should be updated to the latest Angular version (9 as of now), and files like `polyfills.ts`, `angular.json`, `tsconfig.json` should be updated as well in order to enable Ivy by default, add missing dependencies and remove deprecated stuff like `core-js/es6/reflect` imports etc.

Otherwise it takes quite some time to create an issue reproduction project for the latest Angular version.

**Comment by sonukapoor** [comment]
@gkalpak I can take a look at this.

**Comment by sonukapoor** [comment]
@StephenFluin / @IgorMinar I see that the stackblitz url in the file:

https://raw.githubusercontent.com/angular/angular/master/.github/ISSUE_TEMPLATE/1-bug-report.md

points to:

https://stackblitz.com/fork/angular-issue-repro2

Do you know whether this repo was created using an account owned by angular? 
Should we actually be using https://stackblitz.com/fork/angular-ivy ?

**Comment by StephenFluin** [comment]
It should be this one, you're right: https://stackblitz.com/fork/angular-ivy

**Comment by sonukapoor** [comment]
@StephenFluin Thanks for confirming.

Do we want to update the `index.html` to that repo with the same instructions from the old repo?

https://stackblitz.com/edit/angular-issue-repro2-lx8p9a?file=src%2Findex.html

**Comment by StephenFluin** [comment]
I'm not sure. We have some of this information in the bug template now, so
some of it isn't relevant. Reminders about minimal reproductions are
helpful though, but I'm not sure if it's worth maintaining a separate
stackblitz repro fork.

**Comment by sonukapoor** [comment]
Ok. PR created for review.
