### ISSUE TITLE
Missing locale

### ISSUE THREAD

**Issue by Mejans** [angular/angular#37061]
# 🐞 bug report

### Affected Package
All

### Description
Hello,
in https://github.com/angular/angular/tree/master/packages/common/locales there is no locale for Occitan, usually oc_FR because it is in the «seed» folder of CLDR I think.
But all the information that are extracted from CLDR are already in the CLDR file.
Would it be possible to integrated it?
Some developers don't know how to make an application with this locale when this file is missing.
See here: https://github.com/Chocobozzz/PeerTube/issues/2612

Best regards

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by Mejans** [comment]
And I ping @Chocobozzz so he can better explain what problem he is facing :)
Many thanks!

**Comment by petebacondarwin** [comment]
Not sure how to bring in locales that are in seed still. Anyone got any ideas?
Meanwhile, it is definitely "feasible" to handcraft your own locale data file if you are desperate.

**Comment by Mejans** [comment]
Yes this is what I suggested here:
https://github.com/Chocobozzz/PeerTube/issues/2612
It's even really easy as the data, day and month day, are really easily available across the Internet :)

**Comment by petebacondarwin** [comment]
Looks like it was worked around in https://github.com/Chocobozzz/PeerTube/commit/2a39506c7da9ef79671d4c21539313b6d49b1884

Closing as I don't think we need to do anything further in the framework to support this. If the OC locale makes it into the main CLDR repository then we will pick it up automatically.
