### ISSUE TITLE
Module parse failed: Unexpected token (1:0)

### ISSUE THREAD

**Issue by GlauberF** [angular/angular#37064]
# 🐞 bug report

### Affected Package
@angular/....

### Description
I'm getting an error, which for me has no logic.
Since the form being written for this component is the same as the one written in others, however the error happens only in 1 component

## 🔬 Minimal Reproduction
**dynamic-component.html**
```html
<ng-container *ngIf="item && configurationItem">
    <ng-container *ngFor="let component of components; trackBy: ( '_id' | trackByVimbo )">
        <ng-template
            [lazyComp]="component.cpn | async"
            [inputs]="component.inputs"
            [outputs]="component.outputs">
        </ng-template>
    </ng-container>
</ng-container>
```

**dynamic-component.component.ts**
[dynamic-component.component.ts](https://gist.github.com/GlauberF/6184b5d82eaca31a3a29ad32e5d90c60)

## 🔥 Exception or Error
```
WARNING in ./src/@vimbo/components/table/content-per-type/dynamic-component/dynamic-component.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <ng-container *ngIf="item && configurationItem">
|     <ng-container *ngFor="let component of components; trackBy: ( '_id' | trackByVimbo )">
|         <!--<ng-container *ngIf="component?.cpn">-->
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.
```
![Captura de Tela_selecionar área_20200512080936](https://user-images.githubusercontent.com/11314585/81678418-f3044480-9427-11ea-850f-19d0f9d53638.png)

## 🌍  Your Environment

```
Angular CLI: 9.1.5
Node: 12.16.3
OS: linux x64

Angular: 9.1.4
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.5
@angular-devkit/build-angular      0.901.5
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.5
@angular-devkit/core               9.1.5
@angular-devkit/schematics         9.1.5
@angular/cdk                       9.2.2
@angular/cli                       9.1.5
@angular/compiler-cli              9.1.6
@angular/flex-layout               9.0.0-beta.29
@angular/language-service          9.1.6
@angular/material                  9.2.2
@angular/material-moment-adapter   9.2.2
@ngtools/webpack                   9.1.5
@nguniversal/builders              9.1.1
@nguniversal/common                9.1.0
@nguniversal/express-engine        9.1.0
@schematics/angular                9.1.5
@schematics/update                 0.901.5
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
```

**Comment by JoostK** [comment]
Please provide a reproduction for this issue, preferably using a Github repo and some commands to run. Without it, there's not enough information to investigate.

**Comment by alxhub** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by GlauberF** [comment]
@Alxandr , @JoostK sorry people for not returning, I tried to check the problem myself, but I couldn't get anywhere.
following new issue: https://github.com/angular/angular/issues/37307

I put the component as a whole in Minimal Reproduction
