### ISSUE TITLE
Re: Angular document for Japanese

### ISSUE THREAD

**Issue by javakiller0606** [angular/angular#37083]
I am writing to ask about Angular document for Japanese.

It seems that the imported part of the attached image is missing.

Isn't "import {Component, OnInit} from '@ angular / core';" correct?

Could you please confirm it?

<img width="900" alt="2020-05-13" src="https://user-images.githubusercontent.com/52107468/81788592-bfb3d980-953d-11ea-93e8-fc009a7dfae5.png">

# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by gkalpak** [comment]
The japanese version is not maintained by the Angular team.
Try opening an issue on their repo: https://github.com/angular/angular-ja
