### ISSUE TITLE
some ViewContainerRef properties are missed in angular 9?

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular#37084]
# 🐞 bug report
 `embeddedViews` prperty not available in angular 9 `viewcontainerRef` property and there is no alternate property also available

### Is this a regression?

yes

### Description

This is my script condition in my source level which is working fine in angular 7 and 8,

```
if (this.isNgTemplate()) {
            let items = this.listViewInstance.element.querySelectorAll('.' + classNames.listItem);
            for (let index = 0; index < items.length; index++) {
                items[index].context = this.listViewInstance.viewContainerRef._embeddedViews[index].context;
            }

```
But throws script error in angular 9, if i disbale ivy working fine.

### Validation details

I have validated and find root cause of my issue. in angular 7, `viewcontainerRef` property looks like below which has `embeddedViews` property so my script works fine.

![image](https://user-images.githubusercontent.com/36756050/81789198-41493e80-9521-11ea-9bd8-3abb9c2f7da3.png)

But in angular 9, there is no `embeddedViews` property, `viewcontainer` property looks like beloe:

![image](https://user-images.githubusercontent.com/36756050/81789533-bfa5e080-9521-11ea-8040-70258bb21198.png)

### Working sample
- Angular 7 sample - 
[Angular 7-ListView.zip](https://github.com/angular/angular/files/4620695/Angular.7-ListView.zip)

- download above sample

- Give `npm i` and then give `ng serve`

- you will see no script error in console

### issue reproducing sample

- angular 9 sample 
[Angular9-Virtualization template.zip](https://github.com/angular/angular/files/4620697/Angular9-Virtualization.template.zip)

- do same steps - you will see console error

## 🌍  Your Environment

**Angular Version:**
<pre><code>
"@angular/animations": "~9.0.0",
    "@angular/common": "~9.0.0",
    "@angular/compiler": "~9.0.0",
    "@angular/core": "~9.0.0",
    "@angular/forms": "~9.0.0",
    "@angular/platform-browser": "~9.0.0",
    "@angular/platform-browser-dynamic": "~9.0.0",
    "@angular/router": "~9.0.0",
 "@angular-devkit/build-angular": "~0.900.1",
    "@angular/cli": "~9.0.1",
    "@angular/compiler-cli": "~9.0.0",
    "@angular/language-service": "~9.0.0",

</code></pre>

**Anything else relevant?**
when disale `IVY`, there is now console error.

**Comment by kumaresan-subramani** [comment]
### script path 

> webpack:///./node_modules/@syncfusion/ej2-angular-base/src/component-base.js

![image](https://user-images.githubusercontent.com/36756050/81790713-663eb100-9523-11ea-886c-8eda0a5e454f.png)

**Comment by pkozlowski-opensource** [comment]
`_embeddedViews` is a private API so while you might have seen it under debugger, this is not the contract you can use in your application. If you want to get a view from a `ViewContainerRef` you can use the  `get` method: https://angular.io/api/core/ViewContainerRef

**Comment by kumaresan-subramani** [comment]
HI @pkozlowski-opensource ,

Thanks for your reply, i didn't get you. Can you please explain little more in detail?

**Comment by pkozlowski-opensource** [comment]
You shouldn't be using `ViewContainerRef._embeddedViews ` in your application as this private API and using it can break your application at any release (as it does for you).

Hard to suggest replacement here as it is not clear to me what you are trying to do, functionally speaking. If you've got valid case that is not covered by our public API, please explain it, ideally illustrating with a _mimimal_ reproduce scenario in a stackblitz or similar.

**Comment by kumaresan-subramani** [comment]
Hi @pkozlowski-opensource ,

While using `get` to get component view as you suggested, how can i able to give index number?

https://angular.io/api/core/ViewContainerRef#get

**Comment by mlc-mlapis** [comment]
@kumaresan-subramani It's a number starting with 0. If you are looking for some exact one, you need this value from some previous step. Another way is only to iterate through.

**Comment by kumaresan-subramani** [comment]
@pkozlowski-opensource  & @mlc-mlapis

Refer below image, i have tried you suggestions but it return undefined value i angular 9

## angular 9 viewcontainer ref:
![image](https://user-images.githubusercontent.com/36756050/81809227-a19aa900-953e-11ea-8841-215abf35a719.png)

## Tried your suggestion but return `undefined`
![image](https://user-images.githubusercontent.com/36756050/81809066-57b1c300-953e-11ea-8361-f99294b09c3f.png)

## in angular 7, i am getting component view

![image](https://user-images.githubusercontent.com/36756050/81809350-db6baf80-953e-11ea-9a30-be08489ba7a6.png)

**Comment by pkozlowski-opensource** [comment]
@kumaresan-subramani I'm sorry but it is _not_ clear to me (at all...) what you are trying to achieve and what it the exact scenario. It makes me sad as I can clearly see that we are not communicating productively here... Not sure what the best next step is. 

Maybe, if you can provide a _minimal_ reproduce scenario in stackblitz of your use-case, I can have a look at try to help. But at this point I'm failing to see your use-case based on the information provided.

**Comment by kumaresan-subramani** [comment]
## repro stesp

-  download sample - 
[Angular9-Virtualization template.zip](https://github.com/angular/angular/files/4621911/Angular9-Virtualization.template.zip)

- Giev `npm i` and then `ng serve`

- you will see console error in browser

## reason

In my [source](https://github.com/syncfusion/ej2-javascript-ui-controls/blob/master/controls/lists/src/list-view/virtualization.ts#L124), i have used `embededview` api to get component view and update my component native element template property.

## details

in below, i am updating `template` values to my created element using `embededview` api
![image](https://user-images.githubusercontent.com/36756050/81814137-00175580-9546-11ea-8a12-e0c800947796.png)

after updating template value from embedded views, my element items looks like below

![image](https://user-images.githubusercontent.com/36756050/81814494-7caa3400-9546-11ea-9358-861cc35ecfab.png)

above template values has been taken from `this.listViewInstance.viewContainerRef._embeddedViews`

![image](https://user-images.githubusercontent.com/36756050/81814700-b7ac6780-9546-11ea-9cf8-2702f12cd53e.png)


## But in angular9,  i didn't get any reference so that i am not able to update my element template values

**Comment by kumaresan-subramani** [comment]
> `_embeddedViews` is a private API so while you might have seen it under debugger, this is not the contract you can use in your application. If you want to get a view from a `ViewContainerRef` you can use the `get` method: https://angular.io/api/core/ViewContainerRef

Thanks @pkozlowski-opensource , this comment solve my issue but i haven't check properly at my end. Due cache problem this takes time
