### ISSUE TITLE
@angular/bazel use `bazelisk` instead of `bazel` as it is deprecated.

### ISSUE THREAD

**Issue by lukasholzer** [angular/angular#37087]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/bazel

### Description

The `@angular/bazel:build` is using `@bazel/bazel` to execute the bazel commands under the hood.  [bazelbuild/rules_nodejs/issues/1784](https://github.com/bazelbuild/rules_nodejs/issues/1784)
Switch to `bazelisk` instead of `bazel` as dependency.

Furthermore, this would solve the issue of having an old version of `bazel` (2.1.0) current bazel version (3.1.0).

### Describe the solution you'd like

Instead of using `bazel` use `bazelisk` 
https://github.com/angular/angular/blob/master/packages/bazel/src/builders/bazel.ts#L16

```typescript
export type Executable = 'bazelisk'|'ibazel';
```

Maybe add with the `ng-add` schematic a `.bazelversion` file to configure the bazel version in use. As it does not make sense to configure it on a build target level in the angular cli.

Are you willing to take contributions on this?

**Comment by THE-VR7** [comment]
Hello. I am new  and would love to contribute.
I would like to fix this issue, if no one is already on it.

**Comment by lukasholzer** [comment]
I guess this issue is irrelevant because the whole builder will be deprecated #37190 if not I will create a pull request with the fix.

**Comment by jelbourn** [comment]
@lukasholzer to clarify- the `ng add` schematic here should have `@bazel/bazelisk` instead of `@bazel/bazel`, yes? We probably won't have cycles to update this, but feel free to send a PR.

**Comment by TimJ0212** [comment]
You could assign it to me, I would like to contribute.

**Comment by alxhub** [comment]
Closing as obsolete - the Bazel builder and associated CLI functionality are deprecated and no longer supported.
