### ISSUE TITLE
Newly generated Angular Component and Unit Test fails with Jest Test Runner only when using Testbed

### ISSUE THREAD

**Issue by imnickvaughn** [angular/angular#37086]
Hello fellow angularians!  My goal is to create a unit test using the Testbed provided by Angular Core.  I happen to be using Jest Test Runner (syntax similar to Jasmine) for my unit testing.  I am currently able to run tests without Testbed, by newing up the component.
<br><br>
Expected:<br>
I expected that after the CLI generates a component and its associated unit test that the unit test would pass (see Component and Unit Test for the minimal reproducible example below).
<br><br>
Actual:<br>
In actuality, I received two errors (see Errors below).  These errors show me that the component is not being instantiated in time for the test.
<br><br>
Things I have tried:<br>
My [previous question][1] shows a history of things I have tried thus far.  That start with the first thing I tried which was [adding the initiation of the test environment to the setup File][2]. This just resulted in `Can't resolve all parameters for ApplicationModule: (?).` You can go to that ticket if you are interested in the riveting discussion coming from that. On to this attempt...
1. The second major attempt after the above leads to the below steps.  I tried wrapping the beforeEach Testbed call in an async function. <br>
2. This simply results in the error `ProxyZoneSpec is needed for the async() test helper but could not be found.` After that, you add `import 'zone.js/dist/proxy.js';` to your setup file.<br>
3. This results in the error `Expected to be running in 'ProxyZone', but it was not found.` After that, you find a few SO posts [one of which][3] suggests you use `fakeAsync` instead of `async` so you try that.  The error doesn't change this time. The test is still failing.
<br><br><br>
This post could have also been named:
>Using Testbed to do Angular Unit testing - BeforeEach wrapped in Async causes the error: Expected to be running in 'ProxyZone', but it was not found. 
<br>
But I believe starting on solid ground with the MRE where the CLI leaves you is the best since that SHOULD work, but doesn't.
Anyway, I am wondering where I went astray here.  If you have anything I could try I am all ears.  Thank you for your help.  Please let me know if I am missing anything so I can amend this post.
<br><br><br><br>

**Component**

```
@Component({
  selector: 'app-geode-lib',
  template: `  `,
})
export class GeodeLibComponent implements OnInit {
  constructor() { }
  ngOnInit() { }
}
```

**Unit test**
```
describe('GeodeLibComponent', () => {
  let component: GeodeLibComponent;
  let fixture: ComponentFixture<GeodeLibComponent>;
  beforeEach(() => {
    TestBed.configureTestingModule({
      schemas: [NO_ERRORS_SCHEMA],
      declarations: [GeodeLibComponent]
    });
    fixture = TestBed.createComponent(GeodeLibComponent);
    component = fixture.componentInstance;
  });
  it('can load instance', () => {
    expect(component).toBeTruthy();
  });
});
```

**ERROR1**
```
 FAIL  projects/geode-lib/src/lib/geode-lib.component.spec.ts
  ● GeodeLibComponent › can load instance

    TypeError: Cannot read property 'getComponentFromError' of null

      at TestBedViewEngine._initIfNeeded (../../packages/core/testing/src/test_bed.ts:378:46)
      at TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:570:10)
      at Function.TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:232:36)
      at Object.beforeEach (projects/geode-lib/src/lib/geode-lib.component.spec.ts:12:23)

  ● GeodeLibComponent › can load instance

    expect(received).toBeTruthy()

    Received: undefined

      14 |   });
      15 |   it('can load instance', () => {
    > 16 |     expect(component).toBeTruthy();
         |                       ^
      17 |   });
      18 | });
      19 | 

      at Object.it (projects/geode-lib/src/lib/geode-lib.component.spec.ts:16:23)
```
**ERROR2**
```
// getTestBed().initTestEnvironment(
//     BrowserDynamicTestingModule,
//     platformBrowserDynamicTesting()
// );
```

```
    "dependencies": {
        "@angular/animations": "~8.2.3",
        "@angular/cdk": "~8.2.3",
        "@angular/common": "~8.2.3",
        "@angular/compiler": "~8.2.3",
        "@angular/core": "~8.2.3",
        "@angular/flex-layout": "^8.0.0-beta.27",
        "@angular/forms": "~8.2.3",
        "@angular/material": "^8.2.3",
        "@angular/platform-browser": "~8.2.3",
        "@angular/platform-browser-dynamic": "~8.2.3",
        "@angular/router": "~8.2.3",
        "@geode/geode-lib": "20.6.3",
        "@ngrx/effects": "^8.4.0",
        "@ngrx/router-store": "^8.4.0",
        "@ngrx/store": "^8.4.0",
        "@ngrx/store-devtools": "^8.4.0",
        "angular-webstorage-service": "^1.0.2",
        "core-js": "^3.3.2",
        "devextreme": "19.2.3",
        "devextreme-angular": "19.2.3",
        "devextreme-schematics": "^1.0.11",
        "hammerjs": "^2.0.8",
        "jqwidgets-scripts": "^8.2.0",
        "ngx-cookie-service": "^2.2.0",
        "rxjs": "~6.5.3",
        "tslib": "^1.9.0",
        "web-animations-js": "^2.3.2",
        "zone.js": "~0.9.1"
    },
    "devDependencies": {
        "@angular-builders/jest": "^9.0.0",
        "@angular-devkit/build-angular": "~0.803.18",
        "@angular-devkit/build-ng-packagr": "~0.803.18",
        "@angular/cli": "^8.3.18",
        "@angular/compiler-cli": "~8.2.13",
        "@angular/language-service": "~8.2.13",
        "@linnenschmidt/build-ng-packagr": "^8.0.0",
        "@ngneat/spectator": "^4.11.1",
        "@types/jest": "^24.9.1",
        "@types/node": "~8.9.4",
        "codelyzer": "^5.0.1",
        "core.js": "^0.4.2",
        "devextreme-cldr-data": "^1.0.2",
        "globalize": "^1.4.2",
        "jest": "^24.9.0",
        "jest-preset-angular": "^8.2.0",
        "ng-packagr": "^5.4.0",
        "protractor": "~5.4.0",
        "ts-jest": "^24.1.0",
        "ts-node": "~7.0.0",
        "tsickle": "^0.37.0",
        "tslib": "^1.9.0",
        "tslint": "~5.11.0",
        "typescript": "~3.5.3"
    },
    "jest": {
        "preset": "jest-preset-angular",
        "setupTestFrameworkScriptFile": "<rootDir>/setupJest.ts",
        "testPathIgnorePatterns": [
            "./node_modules/",
            "./dist/",
            "./src/test.ts"
        ]
    }
```

  [1]: https://stackoverflow.com/questions/61728890/failed-zone-is-needed-for-the-async-test-helper-but-could-not-be-found?noredirect=1#comment109191113_61728890
  [2]: https://stackoverflow.com/questions/53913577/cant-resolve-all-parameters-for-applicationmodule
  [3]: https://stackoverflow.com/questions/48789782/angular-5-testing-expected-to-be-running-in-proxyzone-but-it-was-not-found

**Comment by pkozlowski-opensource** [comment]
@imnickvaughn 2 quick observations:
* we are not supporting Jest in CLI (our recommended setup) so you need to be prepared to dig much more on your own. In practical terms it means that you will have to tell us what we should change in the framework to support your use-case, rather than expecting us to investigate a particular integration you want to achieve; 
* I would suggest trying latest Angular v9 where TestBed was substantially re-worked.

**Comment by mlada** [comment]
@imnickvaughn 
Did you solve problem?
