### ISSUE TITLE
Make "Angular 9 introduced a global `$localize()`..." message a warning instead of error

### ISSUE THREAD

**Issue by jimbarrett33** [angular/angular#37092]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/core

### Description
Please consider changing the "**Angular 9 introduced a global`$localize()...**" message from an error to a console warning. In a monorepo, a shared lib/module may have components that are i18n aware that some applications will actually not use, although they have a dependency for some other functionality. With this message as an error, even applications that don't require i18n now break at runtime.

### Describe the solution you'd like

Use console.warn(...) instead.

### Describe alternatives you've considered
Not much I can do except add import `'@angular/localize/init';` to all apps in the monorepo. Other suggestions welcome.

**Comment by petebacondarwin** [comment]
I think the best solution here would be to move the `$localize` calls within the template function - something I have wanted to implement for some time. This would mean that this error only occurs if the template is actually instantiated - i.e. the component that uses i18n is actually used.

**Comment by petebacondarwin** [comment]
https://github.com/angular/angular/pull/38404 should solve this problem (by moving the `$localize` calls into a lazy evaluated factory function. In this case the call is not made if the component is not used.

**Comment by petebacondarwin** [comment]
#38404 was merged into master three weeks ago. So this should no longer be a problem. @jimbarrett33 can you check whether the next version (11.0.0-next.0) no longer has this problem?

**Comment by jimbarrett33** [comment]
@petebacondarwin thanks. I'll put this on my radar to test. I have a busy couple weeks coming up.
