### ISSUE TITLE
Compiler: generate template code from AST

### ISSUE THREAD

**Issue by petermikitsh** [angular/angular#37098]
# 🚀 feature request

### Relevant Package

This feature request is for @angular/compiler

### Description

The goal is to codeshift Angular template code.

The feature request is the ability to prettyprint a template AST.

### Describe the solution you'd like

With current APIs, getting an AST from a template string is simple:

```js
const compiler = require("@angular/compiler");

const code = `<button *ngIf="expression" foo="foo" [bar]="bar" (click)="onClick">
  Submit
</button>`;

const ast = compiler.parseTemplate(code, "foo.html", {
  preserveWhitespaces: false,
});
```

An API to generate code from the AST is needed. Such an API might look like this:

```ts
generate(ast: AST): string;
```

### Describe alternatives you've considered

In userland, there are HTML parsers (e.g., [parse5](https://github.com/inikulin/parse5)) but they do not support Angular template syntax.

**Comment by alxhub** [comment]
Our compiler API is non-public by design, and we have no plans to change that currently.
