### ISSUE TITLE
pipe not found in ng serve but found in production build

### ISSUE THREAD

**Issue by mix5003** [angular/angular#37105]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] config
- [ ] run
- [ ] help
- [ ] version
- [ ] doc

### Description
i try to upgrade from angular 8 to angular 9. i found one of my component can not find any pipe. but other component in same module works. and in production build every component can find a pipe normally.

## 🔬 Minimal Reproduction
https://github.com/mix5003/ng-pipe-not-exists
this is from my project that remove not relate code already . if you run `ng serve` and go to `/2/report/financial/profit-and-loss` it works. but if you go to `/2/report/financial/health-index` it will throw error. 

if you try to copy all code from `FinancialBaseComponent` to `FinancialBusinessHealthComponent` and remove `extends FinancialBaseComponent` it works too.

and if you create new project and copy `src/app` to new project and run `ng serve` it works too. 

## 🔥 Exception or Error
<pre><code>
core.js:4098 ERROR Error: Uncaught (in promise): Error: The pipe 'translate' could not be found!
Error: The pipe 'translate' could not be found!
    at getPipeDef$1 (core.js:25434)
    at ɵɵpipe (core.js:25397)
    at FinancialBusinessHealthComponent_Template (VM89 FinancialBusinessHealthComponent.js:20)
    at executeTemplate (core.js:7706)
    at renderView (core.js:7523)
    at renderComponent (core.js:8747)
    at renderChildComponents (core.js:7382)
    at renderView (core.js:7548)
    at ComponentFactory.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.ComponentFactory.create (core.js:23305)
    at ViewContainerRef.createComponent (core.js:10531)
    at resolvePromise (zone.js:832)
    at resolvePromise (zone.js:784)
    at zone.js:894
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:28273)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:507)
    at invokeTask (zone.js:1671)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.4
Node: 12.16.2
OS: win32 x64

Angular: 9.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
if you think this is not bug feel free to close this issue. i just curious why it happen?

**Comment by JoostK** [comment]
This appears to be a re-entrancy issue in the JIT compiler:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/123679/81984519-2f58c000-9635-11ea-8ae3-d466c41ab237.png">

In `addDirectiveDefToUndecoratedParents`, the parent component gets compiled which triggers a flush of the module queue, where the associated NgModule is pending. This will iterate its declarations to assign the scope to all components, which re-triggers compilation of the child component why it's already being compiled. As such, the scope is only set to the "inner" compilation output, after which the "outer" compilation will kick off and overwrite the "inner" result. Since the NgModule's scope has already been processed, the "outer" compilation output will never be assigned scope information.

Using the AOT compiler does not have this problem.

**Comment by JoostK** [comment]
Tracking as FW-2173 (internal only, but nothing to see there)

**Comment by 7freaks-otte** [comment]
I'm experiencing the exact same issue. Is there a workaround until this is fixed?

**Comment by robmcil** [comment]
Our team are also facing this issue. Totally fine on AOT/Prod build but using ng-serve if we refresh certain pages we the above error. Digging into the code it seems the pipeRegistry is null for the view when it shouldn't be!

**Comment by 7freaks-otte** [comment]
It seems to me that this started happening when upgrading Angular to 9/10 and moving to Ivy compilation. As @JoostK pointed out, I only experience this on certain pages that extend another template page.

```
import { TemplatePage } from '../tpl/template.page';

@Component({
    selector: 'app-some-page',
    templateUrl: './some.page.html',
})
export class SomePage extends TemplatePage {
    ...
```

I still consider this a bug as JIT should work with Ivy as well, but a "work-around" (I'm actually quite happy with that as it seems be the default for new projects) is to add the option `"aot": true` to the normal build section of the `angular.json` file. AOT is then used for `ng-serve` as well and the error disappears.

```
{
  ...,
  "projects": {
    "app": {
    ...,
      "architect": {
        "build": {
        ...,
          "options": {
          ...,
            "aot": true
...
```
