### ISSUE TITLE
Angular 9 - lazy loading is not working in production build

### ISSUE THREAD

**Issue by kashifazmi** [angular/angular#37107]
# 🐞 bug report

### Description
I am working on one of the application on Angular 9 and implemented the lazy loading for some module.
when i am running this app in local environment. its working fine but when i am creating the new build using **ng build --prod** and publish build on production environment then **routing is not working for lazy loaded modules.**
for local: http://localhost:4200/resident (working) 
production: http://abxxxx.com/resident (not wokring)
- Here resident is default path to render child component.

## 🔬 Minimal Reproduction
1. Create a new project using angular cli command
2. added some module and configure the lazy loading in app.routing as below:
- app.rotuing.module.ts
const routes: Routes = [
  {
    path: '',
    component: LoginComponent
  },
  {
    path: 'dashboard',
    component: DashboardComponent
  },
  {
    path: 'resident',
    loadChildren: () => import('./modules/resident/resident.module').then(rm => rm.ResidentModule)
  },
  {
    path: 'supervisor',
    loadChildren: () => import('./modules/oclm-supervisor/oclm-supervisor.module').then(sup => sup.OclmSupervisorModule)
  },
  // otherwise redirect to login page
  { path: '**', redirectTo: '' }
];
3. child routing for resident .
const routes: Routes = [
  {
    path: '',
    children: [
      {
        path: '',
        pathMatch: 'full',
        redirectTo: 'bashboard'
      },
      {
        path: 'bashboard',
        component: DashboardComponent
      }]
}]

## 🌍  Your Environment

**Angular Version:**
`Angular CLI: 9.1.5
Node: 12.16.3
OS: win32 x64

Angular: 9.1.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.6
@angular-devkit/build-angular     0.901.6
@angular-devkit/build-optimizer   0.901.6
@angular-devkit/build-webpack     0.901.6
@angular-devkit/core              9.1.5
@angular-devkit/schematics        9.1.5
@angular/cli                      9.1.5
@ngtools/webpack                  9.1.6
@schematics/angular               9.1.5
@schematics/update                0.901.5
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0`

**Comment by mlc-mlapis** [comment]
### @kashifazmi What do see on file system in the project root directory. There should be separate files generated for that lazy loaded modules.

**Comment by kashifazmi** [comment]
@mlc-mlapis  After building (ng build --prod) application, there are no file generated related modules. only I am able to see the some java-script files, styles and images  such as common, main,polyfills, runtimes and scripts.

**Comment by mlc-mlapis** [comment]
![](https://user-images.githubusercontent.com/5693835/81978753-40e99a00-962c-11ea-8079-6a71973ce796.png)

[**@kashifazmi**](https://github.com/kashifazmi) There should be files like those above, each one for each lazy loaded module.

**Comment by kashifazmi** [comment]
@mlc-mlapis - I uploaded two image which is showing the normal build and production build. 

![normal build](https://user-images.githubusercontent.com/22609961/81992449-1534d700-9661-11ea-86d7-a3291b83e947.PNG) 
- in above image, i used ng build.

![prod build](https://user-images.githubusercontent.com/22609961/81992452-16660400-9661-11ea-8f6f-8b95eea834b1.PNG)
- here, i used ng build --prod but there are no file for lazy loaded module.

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
