### ISSUE TITLE
Ivy doesn't include downgraded components into production build

### ISSUE THREAD

**Issue by zuzusik** [angular/angular#37102]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.x.x

### Description

Consider following situation:

- there is an AngularJS application
- follow [official upgrade guide](https://angular.io/guide/upgrade#upgrading-with-ngupgrade) to get it into hybrid mode with `ngUpgrade`
- start writing all new components in new Angular (to not to add more legacy code) and where needed - use `downgradeComponent` to be able to use Angular components in AngularJS
- if downgraded component is used _only_ in AngularJS templates - it will be shaken off the tree with production build - this manifests itself in component just not being rendered. Silently. No errors, warnings, or whatsoever.

#### Workaround

It can be fixed with referencing the component somewhere, as suggested in related issues - https://github.com/angular/angular/issues/35314#issuecomment-584821399, or in https://github.com/angular/angular-cli/issues/16246#issuecomment-557051190

Fix commit: https://github.com/zuzusik/angular-upgrade-ivy-bug/commit/f123b6bcb680231f823d9260c29b9a79cd6d4c2f

#### Things to fix/improve

There are several things about this which don't look right:

- this is huge regression for applications using `ngUpgrade` - _ideally_ this should be fixed
- it all happens silently - no errors/warnings/logs or whatsoever - _at least_ it should give some clues about it 
- it's discrepancy between prod and dev build - in dev build all still works great - _ideally_
 these 2 builds should not have such huge discrepancies
- official upgrade guide says to include component into `entryComponents` which has no effect in Ivy - _at least_ it should have some notes about compatibility with Ivy and possible shake off of the downgraded components

## 🔬 Minimal Reproduction

* clone https://github.com/zuzusik/angular-upgrade-ivy-bug
* run `ng serve`
* observe all components rendered
* run `ng serve --configuration=production`
* observe `<downgraded-component>` not being rendered
* expected - `<downgraded-component>` is rendered

## 🔥 Exception or Error
<pre><code>

No exceptions or errors or whatsoever - and this is very frustrating.
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.1.5
Node: 12.16.3
OS: darwin x64

Angular: 9.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router, upgrade
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.5
@angular-devkit/build-angular     0.901.5
@angular-devkit/build-optimizer   0.901.5
@angular-devkit/build-webpack     0.901.5
@angular-devkit/core              9.1.5
@angular-devkit/schematics        9.1.5
@angular/cli                      9.1.5
@ngtools/webpack                  9.1.5
@schematics/angular               9.1.5
@schematics/update                0.901.5
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

This is not really relevant, but this was very frustrating experience - literally everything is done by the guide and the app just ends up silently broken. Took me quite a time to figure all out...

**Comment by petebacondarwin** [comment]
Thanks for reporting this so clearly @zuzusik. I am sorry that it was a frustrating experience for you.

I agree, at the very least we should fix the docs to show the right approach and explain why it is necessary to reference these somewhere.

I am not sure how it would be possible to provide an error in the case where one forgets to reference the component and it gets tree shaken.

**Comment by petebacondarwin** [comment]
Tracking in FW-2170

**Comment by zuzusik** [comment]
> I am not sure how it would be possible to provide an error in the case where one forgets to reference the component and it gets tree shaken.

It might be a good idea to provide a list of tree shaken components. Can be useful not just in cases like this, but also for general purposes - to clean up unused components from the code.

What do you think?

**Comment by petebacondarwin** [comment]
Interesting idea... what do you think @alan-agius4 ?

**Comment by alan-agius4** [comment]
That data is already available if you use `—verbose` flag

**Comment by zuzusik** [comment]
@alan-agius4 thanks for the suggestion!

I have tried using the `--verbose` flag. 

I've ran it on the example repository I've provided above and the component being dropped (`DowngradedComponent`) is not mentioned there - I wasn't able to find any references to the component in the log neither by component's class name, nor by it's file name.

So, looks like `--verbose` is no help.

**Comment by alan-agius4** [comment]
@zuzusik, I am seeing `WARNING in Terser Plugin: Dropping unused function downgradeComponent [main-es2015.ef192de3c71ac997bcd9.js:89430,9]` when running `ng build --prod --verbose`

**Comment by zuzusik** [comment]
@alan-agius4 yes, I see that as well, but that doesn't give me any clue that my component is being dropped (`downgradeComponent` is Angular's function - not from project's code) - this message is pretty cryptic - it doesn't clear which part of code it's coming from

**Comment by zuzusik** [comment]
@alan-agius4 also, just next to that line is 

```
WARNING in Terser Plugin: Dropping unused function downgradeInjectable [main.5febe6c16fdade2eef41.js:99429,9]
```
and project is not referencing `downgradeInjectable`

so I can assume 

```
WARNING in Terser Plugin: Dropping unused function downgradeComponent [main-es2015.ef192de3c71ac997bcd9.js:89430,9]
```

will be just always present in that log - not depending whether any component using it is actually dropped

**Comment by alan-agius4** [comment]
@zuzusik, `WARNING in Terser Plugin: Dropping unused function downgradeComponent [main-es2015.ef192de3c71ac997bcd9.js:89430,9] ` will only be present if that function is dropped.

**Comment by zuzusik** [comment]
@alan-agius4 I get it

but still it doesn't give any clue that some component is dropped

imagine there are 2 components using `downgradeComponent` - one is dropped, the other is not dropped

now mentioned line will **not** present in the log, as `downgradeComponent` is used

so, how can I know now that one of components is droped

**Comment by JoostK** [comment]
In this particular instance, I would consider the call with global side-effects at the top-level of a module to be the culprit:

https://github.com/zuzusik/angular-upgrade-ivy-bug/blob/c31e260096d0e1436fe781c7e5c44cc98b4b7a51/src/app/downgraded.component.ts#L12-L14

The compiler elides the import to enable tree-shaking, however this will also drop the side-effect. For a module with global side-effects, it's generally a good idea to have an import that is unequivocally a side-effectful import:

`import './downgrade.component';`

Alternatively, you may want to consider registering the downgraded components in the same file as the NgModule. Looking at the documentation, that is what is done for `HeroDetailComponent` but not the others (`PhoneListComponent` and `PhoneDetailComponent`). In my opinion the documentation should be adjusted for those two components (moving the registration into the NgModule file) and perhaps a note about this situation could be added.

**Comment by zuzusik** [comment]
thanks for your input, @JoostK !

> import './downgrade.component';

Yes, this would work, but I personally don't like it cause it creates a double import situation - it is also required to import component class to register it in `NgModule`

> Alternatively, you may want to consider registering the downgraded components in the same file as the NgModule.

Yes, this would work as well, though it somehow contradicts commonly adopted approach of writing Angular.js code.

Generally speaking - the issue has workaround, yes. Even several of them. I personally ended up with declaring components in a static array property of the module class. 

> In my opinion the documentation should be adjusted for those two components (moving the registration into the NgModule file) and perhaps a note about this situation could be added.

This sounds good, but again - registering components like that is not a common thing in Angular.js world, so there is a big chance this specific approach would be just ignored (unless we make it super clear, that it's required to avoid situations with possible tree shaking)

**Comment by kapunahelewong** [comment]
Status: docs team will need engineering input to update documentation correctly. Currently, I'm not exactly sure what duck we should update and what we should say.

**Comment by JoostK** [comment]
@kapunahelewong Ducks generally say "Quack"! 🦆

**Comment by kapunahelewong** [comment]
Ha! @JoostK it's my goofy dictation app! 80% of the time it says ducks instead of docs! I'm here everyday. Tune in tomorrow for more! 😆

**Comment by JeanMeche** [comment]
I'll close this as the angular.dev docs don't cover the Angular.js/Upgrade support.
