### ISSUE TITLE
Etherpad service on Angular 

### ISSUE THREAD

**Issue by mohitmg25** [angular/angular#37103]
Can you suggest me how to develop an Angular project for using Etherpad lite

**Comment by petebacondarwin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
