### ISSUE TITLE
Steps to silence the Entry Point warning - Multiple EntryPoints

### ISSUE THREAD

**Issue by BobJeronowitz** [angular/angular#37115]
Including a library raises WARNINGS re: entrypoints and using ngcc.config.js works for most but even with the regex to the rxjs imports it raises those warnings.  Is there a limit to the number that it will find to suppress?  i tried including multiple entries in ignorableDeepImportMatchers array.  i don't see in the code where that node is being referenced in the build code either in configuration or dependency_resolver.

I tried: 

```js
module.exports = {
  "packages": {
    
    '@progress/kendo-angular-buttons': {
       ignorableDeepImportMatchers: [
        /rxjs\/.*/
      ]
      
    }
  }
}
```

@stevethemacguy recommended this but it doesn't always work.
Steps to silence the warning:
1. Update to Angular 9.0.4
2. Create a file named 'ngcc.config.js' at your top-level project folder (see https://github.com/angular/angular/pull/35683)

```js
module.exports = {
  packages: {
    'angular2-text-mask': {
      ignorableDeepImportMatchers: [
        /text-mask-core\//,
      ]
    },
  },
};
```
3. Enjoy a peaceful build 😌

_Originally posted by @stevethemacguy in https://github.com/angular/angular/issues/35615#issuecomment-592253747_

**Comment by petebacondarwin** [comment]
@BobJeronowitz - can you provide some more detail as to the specific warnings you are getting? If it is related to deep-imports in those libraries it should be possible to provide you with an appropriate ngcc.config.js that will solve it.

**Comment by BobJeronowitz** [comment]
[example_ngcc.config.txt](https://github.com/angular/angular/files/4633813/example_ngcc.config.txt)
I've attached the ngcc.config that i am using.  the regex for the paths for '@progress/kendo-angular-resize-sensor' work but '@progress/kendo-angular-buttons', doesn't it almost seems like the number of entry points breaks it.  sensor has 2 and buttons has 6.  i've included the warning/entrypoint list in the top of the example file.  i've seen other example ngcc.config where instead of ignorableDeepImportMatchers a list of entry poiints is used but i've been unable to get them to work either.

**Comment by petebacondarwin** [comment]
I just created a new Angular project using `ng new` and then installed `@progress/kendo-angular-buttons` and its relevant peer dependencies. Then running `ngcc` I do not see any warnings about it having deep imports:

```
Compiling @angular/core : fesm2015 as esm2015
Compiling @angular/animations/browser : fesm2015 as esm2015
Compiling @angular/common : fesm2015 as esm2015
Compiling @angular/core/testing : fesm2015 as esm2015
Compiling @angular/platform-browser : fesm2015 as esm2015
Compiling @progress/kendo-angular-common : es2015 as esm2015
Compiling @angular/common/http : fesm2015 as esm2015
Compiling @angular/platform-browser-dynamic : fesm2015 as esm2015
Compiling @angular/platform-browser/testing : fesm2015 as esm2015
Compiling @angular/common/testing : fesm2015 as esm2015
Compiling @angular/router : fesm2015 as esm2015
Compiling @progress/kendo-angular-l10n : es2015 as esm2015
Compiling @progress/kendo-angular-popup : es2015 as esm2015
Compiling @angular/animations/browser/testing : fesm2015 as esm2015
Compiling @angular/common/http/testing : fesm2015 as esm2015
Compiling @angular/forms : fesm2015 as esm2015
Compiling @angular/platform-browser/animations : fesm2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : fesm2015 as esm2015
Compiling @angular/router/testing : fesm2015 as esm2015
Compiling @progress/kendo-angular-buttons : es2015 as esm2015
Compiling @angular/core : fesm5 as esm5
Compiling @angular/core : esm2015 as esm2015
Compiling @angular/core : esm5 as esm5
Compiling @angular/animations/browser : fesm5 as esm5
Compiling @angular/core : main as umd
Compiling @angular/animations/browser : esm2015 as esm2015
Compiling @angular/animations/browser : esm5 as esm5
Compiling @angular/animations/browser : main as umd
Compiling @angular/animations/browser/testing : fesm5 as esm5
Compiling @angular/animations/browser/testing : esm2015 as esm2015
Compiling @angular/animations/browser/testing : esm5 as esm5
Compiling @angular/animations/browser/testing : main as umd
Compiling @angular/common : fesm5 as esm5
Compiling @angular/common : esm2015 as esm2015
Compiling @angular/common : esm5 as esm5
Compiling @angular/common : main as umd
Compiling @angular/common/http : fesm5 as esm5
Compiling @angular/common/http : esm2015 as esm2015
Compiling @angular/common/http : esm5 as esm5
Compiling @angular/common/http : main as umd
Compiling @angular/common/http/testing : fesm5 as esm5
Compiling @angular/common/http/testing : esm2015 as esm2015
Compiling @angular/common/http/testing : esm5 as esm5
Compiling @angular/common/http/testing : main as umd
Compiling @angular/forms : fesm5 as esm5
Compiling @angular/forms : esm2015 as esm2015
Compiling @angular/forms : esm5 as esm5
Compiling @angular/forms : main as umd
Compiling @angular/platform-browser : fesm5 as esm5
Compiling @angular/platform-browser : esm2015 as esm2015
Compiling @angular/platform-browser : esm5 as esm5
Compiling @angular/platform-browser : main as umd
Compiling @angular/platform-browser/animations : fesm5 as esm5
Compiling @angular/platform-browser/animations : esm2015 as esm2015
Compiling @angular/platform-browser/animations : esm5 as esm5
Compiling @angular/platform-browser/animations : main as umd
Compiling @angular/core/testing : fesm5 as esm5
Compiling @angular/core/testing : esm2015 as esm2015
Compiling @angular/core/testing : esm5 as esm5
Compiling @angular/core/testing : main as umd
Compiling @angular/platform-browser-dynamic : fesm5 as esm5
Compiling @angular/platform-browser-dynamic : esm2015 as esm2015
Compiling @angular/platform-browser-dynamic : esm5 as esm5
Compiling @angular/platform-browser-dynamic : main as umd
Compiling @angular/platform-browser/testing : fesm5 as esm5
Compiling @angular/platform-browser/testing : esm2015 as esm2015
Compiling @angular/platform-browser/testing : esm5 as esm5
Compiling @angular/platform-browser/testing : main as umd
Compiling @angular/platform-browser-dynamic/testing : fesm5 as esm5
Compiling @angular/platform-browser-dynamic/testing : esm2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : esm5 as esm5
Compiling @angular/platform-browser-dynamic/testing : main as umd
Compiling @angular/common/testing : fesm5 as esm5
Compiling @angular/common/testing : esm2015 as esm2015
Compiling @angular/common/testing : esm5 as esm5
Compiling @angular/common/testing : main as umd
Compiling @angular/router : fesm5 as esm5
Compiling @angular/router : esm2015 as esm2015
Compiling @angular/router : esm5 as esm5
Compiling @angular/router : main as umd
Compiling @angular/router/testing : fesm5 as esm5
Compiling @angular/router/testing : esm2015 as esm2015
Compiling @angular/router/testing : esm5 as esm5
Compiling @angular/router/testing : main as umd
Compiling @progress/kendo-angular-common : esm2015 as esm2015
Compiling @progress/kendo-angular-common : esm5 as esm5
Compiling @progress/kendo-angular-common : main as commonjs
Compiling @progress/kendo-angular-common : module as esm5
Compiling @progress/kendo-angular-l10n : esm2015 as esm2015
Compiling @progress/kendo-angular-l10n : esm5 as esm5
Compiling @progress/kendo-angular-l10n : main as commonjs
Compiling @progress/kendo-angular-l10n : module as esm5
Compiling @progress/kendo-angular-popup : esm2015 as esm2015
Compiling @progress/kendo-angular-popup : esm5 as esm5
Compiling @progress/kendo-angular-popup : main as commonjs
Compiling @progress/kendo-angular-popup : module as esm5
Compiling @progress/kendo-angular-buttons : esm2015 as esm2015
Compiling @progress/kendo-angular-buttons : esm5 as esm5
Compiling @progress/kendo-angular-buttons : main as commonjs
Compiling @progress/kendo-angular-buttons : module as esm5
✨  Done in 67.68s.
```

What versions are you using?

**Comment by BobJeronowitz** [comment]
It's when you create a library with the kendo control and then the library is included in the project that the warnings get raised.

**Comment by petebacondarwin** [comment]
Ahah! In that case it may be resolved by https://github.com/angular/angular/pull/37040
If you could provide a simple reproduction then we could ensure that this scenario is covered.
Without a repro we are just guessing.

**Comment by BobJeronowitz** [comment]
issue #37040 indicates that the build will crawl the tree to find the bundle if it exists regardless of the ngcc.config.  if this would address the issue that i am facing, then the warnings would not get thrown, no?

i will put together a sample of what is happening that replicates the scenario and see if there is something that is being interpreted differently for one import vs another.  i think i am missing an understanding of how the build process is using the ngcc.config to config my file correctly.  i am using the setup that is indicated but i don't see where that ignorableDeepImportMatchers node is being used.  is it being used in EntryPointInfo when it creates an entrypoint?  i don't understand the transformation from what is being sent in sith the config file to configuration to how those nodes/entrypoints get to entrypoint_resolver.

**Comment by gkalpak** [comment]
@BobJeronowitz, could you try using the [build artifacts from #37040][1] (see [here][2] for details) and see if it fixes the issue for you? 

[1]: https://circleci.com/gh/angular/angular/719470#artifacts/containers/0
[2]: https://github.com/angular/angular/blob/cdb5d076062dd3b4f938b54158dcfd68de71a800/docs/DEVELOPER.md#getting-packages-from-build-artifacts

**Comment by petebacondarwin** [comment]
@BobJeronowitz - did you manage to create a reproduction or check whether it was resolved?

**Comment by BobJeronowitz** [comment]
i wasn't able to create an app that replicates the issue, somehow a new app doesn't throw the warn for them. i was able to suppress 3 out of the 7 warnings, in my app using an ngcc.config.js:

module.exports = {
       "packages": {
'@progress/kendo-angular-popup': {
                     ignorableDeepImportMatchers: [
                             /rxjs\/.*/i
                    ]
                }
                 
           }
}

Thanks for your assistance.

**Comment by petebacondarwin** [comment]
Closing as we have no reproduction.
