### ISSUE TITLE
chore(zone): add zone.js to bundles and npm distribution

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#3712]
The reasoning is that we will distribute two types of bundles: an "angular2" bundle, and stripped down "sub bundles." The angular2 bundle that will include all "sub-bundles" like core, forms, http, router, web_workers, and there will be a version of the angular2 bundle that includes third-party dependencies like RxJS, reflect-metadata, polyfills, etc. The separate bundles, for more advanced users, will then not include any dependencies, and assume that dependencies have been provided elsewhere.

**Comment by pkozlowski-opensource** [comment]
@jeffbcross this will definitively not hurt, but I wonder if it is necessary: if I recall we'e got already a npm dependency on zone.js so I wonder if this isn't enough?

**Comment by pkozlowski-opensource** [comment]
@jeffbcross I think that this can be closed now. We've got zone.js (and other deps like this) as peerDependencies in npm, so npm part is covered. Also we've got `angular2-polyffils.js` bundle with zone.

So IMO we are good here.
