### ISSUE TITLE
camelCase property names don't work right

### ISSUE THREAD

**Issue by skybrian** [angular/angular#3716]
(This is in Dart using 2.0.0-alpha.34.)

I tried writing a property like this, but it didn't work, and no error was reported.
  properties: const ['compileResult']

After some experimentation, I found that the fix was to write the property name in lowercase:
  properties: const ['compileResult: compileresult']

The documentation seems to indicate that camelCase should work:

 @Directive({
   *   properties: [
   *     'propertyName', // shorthand notation for 'propertyName: propertyName'
   *     'directiveProperty1: bindingProperty1',
   *     'directiveProperty2: bindingProperty2 | pipe1 | ...',
   *     ...
   *   ]
   * }

A bit of experimentation shows that the property name in the template is case-insensitive. So it seems like the first thing I tried should match?

Or if not, there should be better error-checking here for a misspelled property.

**Comment by pkozlowski-opensource** [comment]
Right, HTML is not case sensitive nor case-preserving so if you want to access mixedCase properties from a template you need to use dash-case to camelCase convention that we've got special-cased in the compiler. In your case you could bind to your property using `[binding-property]="exp"`.

As for the error checking - we've got it on the JS side )so trying to bind to non-existing property will throw) and AFAIK it is planned for Dart. But this will require a hand-written schema to indicate which properties are supported on which elements (hand-written to avoid reflective calls). This is tracked by https://github.com/angular/angular/issues/3427

I'm going to close this one for now, as there is a way to bind to camelCased properties and the better error messages are going to be handled in a separate issue.
