### ISSUE TITLE
Angular 9 Service Worker: Clean up unused versions

### ISSUE THREAD

**Issue by nschmit** [angular/angular#37161]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/service-worker.

### Description
 The service worker keeps track of all new app versions it encounters. Every time when a new manifest is received, its hash is saved in a versions-map, where it may stay for a very long time. This does not allow a software developer to go back to an older version of his application, which might be useful if the latest application version is flawed and you like to go back to a previous version.

### Describe the solution you'd like
 Every time a client is updated, the versions-map and the cache should be cleaned up. Versions, which are not the latest version and which are not used anymore by a client should be deleted.

**Comment by gkalpak** [comment]
The SW should work exactly as you described. We call [cleanupCaches()][1] on every [SW initialization][2].

If you see something different, maybe you could try to debug the SW and find out whether the `cleanupCaches()` method is called (and if not, why not) and whether is removes the caches (and if not, why not).

Based on the above, I am afraid there is not much we can do without a reproduction and the SW is already designed to work as you suggested. I am going to close this issue, but feel free to comment below or open a new issue if/when you have more info or a reproduction.

[1]: https://github.com/angular/angular/blob/3f9b3d76667694c404ab0e0ce9bd86e6d282bc7d/packages/service-worker/worker/src/driver.ts#L883-L934
[2]: https://github.com/angular/angular/blob/3f9b3d76667694c404ab0e0ce9bd86e6d282bc7d/packages/service-worker/worker/src/driver.ts#L498

**Comment by nschmit** [comment]
Thanks for the quick reply!
I do agree that the SW is cleaning up the caches on every SW initialization. But as I understood it, this only happens when a new version of the SW is released, which depends on the @angular/service-worker version and not on the version of the PWA. If I'd release many versions of my PWA without updating the SW, I might run into problems such as Quota-Exceeded errors...

What I'd like to suggest is to not only call `cleanupCaches()` in the SW initialization, but also every time the clientVersionMap is updated. That is if `this.clientVersionMap.set(clientId, hash) `is called, the version that was assigned to the client prior to this call might not be needed anymore and might be deleted from cache.

**Comment by gkalpak** [comment]
The SW initialization is unrelated to the version of `@angular/service-worker`. After a some time of inactivity the browser will terminate the SW (to reclaim resources) and it will create a new instance of it the next time it needs to handle an event for its scope. That is what initialization refers to.

This is independent of the version of `@angular/service-worker` (or the `ngsw-worker.js` script) and can happen multiple times per day, even without an update to the SW or the app.
