### ISSUE TITLE
Unclear alert about reactive forms and validation attributes

### ISSUE THREAD

**Issue by bampakoa** [angular/angular#37165]
# 📚 Docs or angular.io bug report

### Description

 
The **Reactive Forms** guide contains an important alert stating that:

> **Caution**: Use these HTML5 validation attributes in combination with the built-in validators provided by Angular's reactive forms. Using these in combination prevents errors when the expression is changed after the template has been checked.

I think that it is a bit misleading for the reader because:

1. The content of the alert should elaborate more on the reason that the expression is changed error may appear in a reactive form.
2. It seems to oppose on the following statement that appears in the **Validate form input** guide.

> Notice that the required attribute is still present in the template. Although it's not necessary for validation, it should be retained to for accessibility purposes.

### What's the affected URL?**

https://angular.io/guide/reactive-forms#validating-form-input
https://angular.io/guide/form-validation#built-in-validator-functions

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by kapunahelewong** [comment]
Thank you for such a clear explanation @bampakoa!

Status: the docs team can work on this one based on the info above.

**Comment by matthewjheaney** [comment]
So where do we stand on this note in the documentation?  Is specifying the validator in the component and template something needed for all built-in HTML5 validators, or is it only necessary for the required validator, and only because required is needed for accessibility reasons?

**Comment by AndrewKushnir** [comment]
FYI, closing this ticket since the content would be updated in PR #42377.
