### ISSUE TITLE
No option to get back to the English translation in Language

### ISSUE THREAD

**Issue by divya96kumari** [angular/angular#37177]
When we click on a different language, then there is no option for English.

**Comment by JoostK** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by petebacondarwin** [comment]
Also be aware that non-English translations of the Angular docs are not owned nor managed by the Angular team. So we are not responsible for ensuring there are links back to our site. If you specify which language version you have a problem with then we may be able to point you at the projec/team that are running that version to allow you to create an issue with them directly.
