### ISSUE TITLE
ERROR: Cannot find module 'tsickle'

### ISSUE THREAD

**Issue by varora1406** [angular/angular#37175]
# 🐞 bug report

### Affected Package
@angular/compiler-cli: "9.1.7"

### Is this a regression?

 Yes, the previous version in which this bug was not present was: "9.1.3"

### Description

Stack
`Building entry point '@catalystone/ui-common'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
ERROR: Cannot find module 'tsickle'
Require stack:
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\ng-packagr\lib\ngc\create-emit-callback.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\ng-packagr\lib\ngc\compile-source-files.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\ng-packagr\lib\ng-package\entry-point\compile-ngc.transform.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\ng-packagr\lib\ng-package\entry-point\compile-ngc.di.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\ng-packagr\lib\ng-package\entry-point\entry-point.di.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\ng-packagr\lib\packagr.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\ng-packagr\lib\commands\build.command.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\ng-packagr\public_api.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular-devkit\build-ng-packagr\src\build\index.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular-devkit\architect\node\index.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular\cli\models\architect-command.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular\cli\commands\build-impl.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular-devkit\schematics\tools\export-ref.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular-devkit\schematics\tools\index.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular\cli\utilities\json-schema.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular\cli\models\command-runner.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\VaibhavArora\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\VaibhavArora\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
An unhandled exception occurred: Cannot find module 'tsickle'
Require stack:
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\ng-packagr\lib\ngc\create-emit-callback.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\ng-packagr\lib\ngc\compile-source-files.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\ng-packagr\lib\ng-package\entry-point\compile-ngc.transform.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\ng-packagr\lib\ng-package\entry-point\compile-ngc.di.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\ng-packagr\lib\ng-package\entry-point\entry-point.di.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\ng-packagr\lib\packagr.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\ng-packagr\lib\commands\build.command.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\ng-packagr\public_api.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular-devkit\build-ng-packagr\src\build\index.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular-devkit\architect\node\index.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular\cli\models\architect-command.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular\cli\commands\build-impl.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular-devkit\schematics\tools\export-ref.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular-devkit\schematics\tools\index.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular\cli\utilities\json-schema.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular\cli\models\command-runner.js
- E:\repos\CatalystOneHeroProgramRelated\library-platform-ui-common\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\VaibhavArora\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\VaibhavArora\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng

**Comment by varora1406** [comment]
I have imported tsickle separately in project, and it works.
Hopefully it can added into required artifact of angular

**Comment by alan-agius4** [comment]
@varora1406, this seems like a bug in `ng-packagr`, where `tsickle` should be listed as an optional peerDependency.

That said since version 9, tsickle is no longer needed by default as `annotateForClosureCompiler` is turned off. You only need tsickle when `annotateForClosureCompiler` is switched on and you are using closure compiler, which in many cases users outside of Google don't need.

See: https://github.com/angular/angular-cli/pull/15603 and https://github.com/ng-packagr/ng-packagr/pull/1213
