### ISSUE TITLE
Getting error while building with Bazel (missing bazelisk)

### ISSUE THREAD

**Issue by beingminimal** [angular/angular#37172]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [x] serve

### Description
We have created new angular project building with bazel by follwing steps given in https://next.angular.io/guide/bazel.
After installtion, getting error while running project locally. 
Note that we have tried same steps on Google Cloud shell with linux environment and there also we received error for bazelisk as below
`node_modules/@bazel/bazelisk/bazelisk-linux_amd64: no such file or directory`

## 🔬 Minimal Reproduction

Repository:
https://github.com/brpatel0202/angular-bazel-example

## 🔥 Exception or Error
<pre><code>
C:\Users\br\Downloads\Workspace\Github\brpatel0202\angular-bazel-example>ng s
iBazel [9:07AM]: Error getting Bazel info exec: "C:\\Users\\br\\Downloads\\Workspace\\Github\\brpatel0202\\angular-bazel-example\\node_modules\\@bazel\\bazelisk\\bazelisk-windows_amd64.exe": file does not exist
iBazel [9:07AM]: Querying for files to watch...
iBazel [9:07AM]: Bazel query failed: exec: "C:\\Users\\br\\Downloads\\Workspace\\Github\\brpatel0202\\angular-bazel-example\\node_modules\\@bazel\\bazelisk\\bazelisk-windows_amd64.exe": file does not exist
iBazel [9:07AM]: Bazel query failed: exec: "C:\\Users\\br\\Downloads\\Workspace\\Github\\brpatel0202\\angular-bazel-example\\node_modules\\@bazel\\baazel-example\\node_modules\\@bazel\\bazelisk\\bazelisk-windows_amd64.exe": file does not exist
iBazel [9:07AM]: Running //src:devserver
iBazel [9:07AM]: Error running Bazel exec: "C:\\Users\\br\\Downloads\\Workspace\\Github\\brpatel0202\\angular-bazel-example\\node_modules\\@bazel\\baazel-example\\node_modules\\@bazel\\bazelisk\\bazelisk-windows_amd64.exe": file does not exist
C:\Users\br\Downloads\Workspace\Github\brpatel0202\angular-bazel-example\node_modules\@bazel\ibazel\bin\windows_amd64\ibazel.exe failed with code 4. _amd64\ibazel.exe failed with code 4.
</code></pre>

## 🌍 Your Environment
<pre><code>

C:\Users\br\Downloads\Workspace\Github\brpatel0202\angular-bazel-example>ng version

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.6
Node: 12.11.1     
OS: win32 x64     

Angular: 9.1.7    
... animations, bazel, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.6
@angular-devkit/core         9.1.6
@angular-devkit/schematics   9.1.6
@angular/cli                 9.1.6
@bazel/bazel                 2.1.0
@bazel/hide-bazel-files      1.6.1
@bazel/ibazel                0.12.3
@bazel/karma                 1.6.0
@bazel/protractor            1.6.0
@bazel/rollup                1.6.0
@bazel/terser                1.6.0
@bazel/typescript            1.6.0
@schematics/angular          9.1.6
@schematics/update           0.901.6
rxjs                         6.5.5
typescript                   3.8.3
</code></pre>

**Anything else relevant?**

Operating system : Windows

**Comment by klemenoslaj** [comment]
I am having the exact same issue on OSX.

**Comment by jessicajaniuk** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
