### ISSUE TITLE
Update to tslib v2

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular#37188]
# 🐞 bug report

### Affected Package
All Angular v10 packages

### Is this a regression?
No.

### Description
According to the upgrade to TypeScript 3.9 in last v10 beta, Angular should upgrade to tslib v2 ([releases notes](https://github.com/microsoft/tslib/releases)) and requires v2 as minimum peerDependency.

**Comment by cyrilletuzi** [comment]
Related issue in Angular CLI: angular/angular-cli#17753

**Comment by alan-agius4** [comment]
Hi @cyrilletuzi,

We are aware of this and we are working on this. Tslib update to version 2 breaking and requires a number of changes across the board.

This is currently being tracked in TOOL-1374
