### ISSUE TITLE
ModuleWithProviders broken in v10.0.0-next.8

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular#37189]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler-cli

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 10.0.0-next.6 (maybe 10.0.0-next.7, skipped this one)

### Description

`ngcc` fails to compile the `NgModule.forRoot()` of my library.

Seems to be introduced by #36948 ([commit](https://github.com/angular/angular/commit/fafa50d97fc45307f8e8bb19a7f9ba7dd16c5079))

## 🔬 Minimal Reproduction
1. `git clone https://github.com/cyrilletuzi/angular-async-local-storage`
2. `cd angular-async-local-storage`
3. `git checkout ng10`
4. `npm ci`
5. `npm run build`
6. `npm run unit`

You can also see the error in this [CI test](https://github.com/cyrilletuzi/angular-async-local-storage/pull/360/checks?check_run_id=686631502).

Source code [is here](https://github.com/cyrilletuzi/angular-async-local-storage/blob/ng10/projects/ngx-pwa/local-storage/src/lib/storage.module.ts) (it's a very simple NgModule with a classic `forRoot()`).

## 🔥 Exception or Error
<pre><code>
The identity given by StorageModule referenced in "static forRoot(config) {
            return {
                ngModule: StorageModule_1,
                providers: [...],
            };
        }" doesn't appear to be a "class" declaration.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular: 10.0.0-next.8
... common, compiler, compiler-cli, core, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.0-next.6
@angular-devkit/build-angular      0.1000.0-next.6
@angular-devkit/build-ng-packagr   0.1000.0-next.6
@angular-devkit/build-optimizer    0.1000.0-next.6
@angular-devkit/build-webpack      0.1000.0-next.6
@angular-devkit/core               10.0.0-next.6
@angular-devkit/schematics         10.0.0-next.6
@angular/cli                       10.0.0-next.6
@ngtools/webpack                   10.0.0-next.6
@schematics/angular                10.0.0-next.6
@schematics/update                 0.1000.0-next.6
ng-packagr                         10.0.0-next.1
rxjs                               6.5.5
typescript                         3.9.2
webpack                            4.43.0

</code></pre>

**Comment by petebacondarwin** [comment]
I think that this is actually more likely due to the changes in TypeScript 3.9, which can now wrap ES2015 classes in an IIFE, which is what is happening to this class:

```ts
let StorageModule = /** @class */ (() => {
    var StorageModule_1;
    let StorageModule = StorageModule_1 = class StorageModule {
        /**
         * Only useful to provide options, otherwise it does nothing.
         * **Must be used at initialization, ie. in `AppModule`, and must not be loaded again in another module.**
         *
         * @example
         * NgModule({
         *   imports: [StorageModule.forRoot({
         *     LSPrefix: 'custom_',
         *   })]
         * })
         * export class AppModule
         */
        static forRoot(config) {
            return {
                ngModule: StorageModule_1,
                providers: [
                    config.LSPrefix ? { provide: LS_PREFIX, useValue: config.LSPrefix } : [],
                    config.IDBDBName ? { provide: IDB_DB_NAME, useValue: config.IDBDBName } : [],
                    config.IDBStoreName ? { provide: IDB_STORE_NAME, useValue: config.IDBStoreName } : [],
                    config.IDBDBVersion ? { provide: IDB_DB_VERSION, useValue: config.IDBDBVersion } : [],
                    (config.IDBNoWrap === false) ? { provide: IDB_NO_WRAP, useValue: config.IDBNoWrap } : [],
                ],
            };
        }
    };
    StorageModule = StorageModule_1 = __decorate([
        NgModule()
    ], StorageModule);
    return StorageModule;
})();
```

**Comment by petebacondarwin** [comment]
I will dig into why we are not matchin `StorageModule_1` to the correct class declaration.

**Comment by petebacondarwin** [comment]
Indeed it is a bug in the Es2105ReflectionHost changes to deal with IIFE wrapped classes.

The `StorageModule_1` identifier is declared as a `var` and so this is not picked up as the “alias declaration” of the “inner declaration”.

I’ll put together a fix tomorrow.

**Comment by petebacondarwin** [comment]
Basically, when given the alias `StorageModule_1` the host is finding the inner class "expression" instead of the outer class "declaration".
