### ISSUE TITLE
Angular 9 upgrade - removal of tsickle library is not documented.

### ISSUE THREAD

**Issue by devin5885** [angular/angular#37193]
# 📚 Docs or angular.io bug report

### Description

The Angular 9 upgrade appears to remove the library 'tsickle' from the project, according to this page it is obsolete with Ivy:

https://blog.ninja-squad.com/2020/02/07/angular-cli-9.0/

Please confirm and document.

### What's the affected URL?**
https://angular.io/guide/updating-to-version-9
https://update.angular.io/

**Comment by kapunahelewong** [comment]
Thanks for bringing this up, @devin5885!

Status: docs team needs direction from an engineer on the above questions and what we should cover in the documentation.

**Comment by alan-agius4** [comment]
Version 9 is no longer supported. Also, tsickle dependency will be removed automatically when running `ng update`.
