### ISSUE TITLE
Add createInjector() to public API

### ISSUE THREAD

**Issue by steverob2k** [angular/angular#37229]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/core

### Description
A pull request was made to remove createInjector from the public API. Stated in the PR is "It will be re-exported when Ivy is released."

This is a very useful function for loading non routed modules and there are many examples online using this.

The PR for reference [https://github.com/angular/angular/pull/28509](url)

Example reference of where this function is useful [https://indepth.dev/lazy-loading-angular-modules-with-ivy/](url)

### Describe the solution you'd like
createInjector is made public giving confidence it can be used or an alternative solution is provided.

### Describe alternatives you've considered
Currently using the private reference to the function when needed:
`import { ɵcreateInjector as createInjector } from '@angular/core';`

**Comment by alxhub** [comment]
It is exposed via `Injector.create`.
