### ISSUE TITLE
No provider for CompilerFactory! after upgrade to angular 9

### ISSUE THREAD

**Issue by angela95ry** [angular/angular#37225]
Upgrade to angular 9.1.7 however, this error display

<code>Uncaught NullInjectorError: StaticInjectorError(Platform: core)[CompilerFactory]:
NullInjectorError: No provider for CompilerFactory!</code>

Below is my main.ts code

<code>
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

if (environment.production) {
  enableProdMode();
}
  platformBrowserDynamic().bootstrapModule(AppModule).catch(err => console.log(err));
</code>

**Comment by JoostK** [comment]
Heya,

unfortunately there's not enough information to be able to investigate. Could you please provide us with a runnable reproduction, for example a Github repo or similar.

**Comment by pkozlowski-opensource** [comment]
I'm going to close this issue for now as we haven't heard back with a reproduce scenario. Happy to re-open if / when we've got one!
