### ISSUE TITLE
Zoneless async router guards break change detection

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular#37223]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 Probably not

### Description

 Async router guards that run outside of zone break change detection.

## 🔬 Minimal Reproduction

 
https://stackblitz.com/edit/angular-zoneless-guard-issue?file=src%2Fapp%2Fapp.module.ts

Change detection is triggered when clicking the button on the eagerly loaded component but **it is not triggered when clicking the button on the lazy loaded component as it's running outside of zone**.

Even if async guards that run outside of zone are a rare case, it can happen and produce issues like with **@angular/fire** here https://github.com/angular/angularfire/issues/2453 or https://github.com/angular/angularfire/issues/2355.

Maybe the router should get back in the zone once the guard emits the value somewhere after the routing guard management here: https://github.com/angular/angular/blob/f930e75a809a1e21369050884c20f42a350c411f/packages/router/src/router.ts#L590-L631

Should I try to shoot a PR?

Thanks!

**Comment by atscott** [comment]
Confirmed in v10 as well without lazy loading: https://stackblitz.com/edit/angular-ivy-tetq7a?file=src%2Fapp%2Fapp.module.ts 
Note that the broken change detection is that clicking the button in the `HelloComponent` does not trigger change detection.

**Comment by JiaLiPassion** [comment]
I will try to check this one.

**Comment by tscislo** [comment]
That also does not work with ng11: https://stackblitz.com/edit/angular-ivy-jx2ecj?file=package.json

**Comment by atscott** [comment]
Copying Joost's response from https://github.com/angular/angular/pull/40989#discussion_r582951599

> I also think that incorporating Zone logic in the primary rendering primitive itself is not really desirable; as @arturovt points out there are valid cases where one explicitly opts-out of zone tracking.

> It currently works very consistently to me: every activity that originates from outside of the Zone will also run outside of the Zone. I would personally not even consider #37223 as a bug: I'd consider the code that leaves the Zone to also be responsible for re-entering the Zone when applicable. Without this symmetry the behavior becomes hard to reason about.

@JoostK also provided how your guard should re-enter the zone: https://stackblitz.com/edit/angular-zoneless-guard-issue-cwsp2v?file=src%2Fapp%2Fapp.module.ts

Keeping this open as a docs issue, reducing priority and adding the community help label.

**Comment by JoostK** [comment]
I played with it a bit more and it appears that it can be simplified using an operator that wraps all notifications into a call to `NgZone.run`:

```typescript
const rezone = (zone: NgZone) => <T>(source: Observable<T>) =>
  new Observable<T>(observer => source.subscribe({
    next: (v) => zone.run(() => observer.next(v)),
    error: (e) => zone.run(() => observer.error(e)),
    complete: () => zone.run(() => observer.complete()),
  }));
```

This can then be used together with `dezone`, [see StackBlitz](https://stackblitz.com/edit/angular-zoneless-guard-issue-1y3hbu?file=src%2Fapp%2Fapp.module.ts).

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
