### ISSUE TITLE
[Ivy] createEmbeddedView invalid rootNodes length

### ISSUE THREAD

**Issue by wszydlak** [angular/angular#37237]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core

### Is this a regression?

Yes, the previous version in which this bug was not present was: Angular 8 without Ivy

### Description

When creating embedded view with `createEmbeddedView` of `TemplateRef`, view contains not equal rootNodes length, with ivy it appears that is one element less.

```typescript
import { Component, TemplateRef, AfterContentInit, ViewChild } from '@angular/core'

@Component({
  selector: 'app-example',
  templateUrl: './example.component.html',
  styleUrls: ['./example.component.css']
})
export class ExampleComponent implements AfterContentInit {
  childCount = 0;
  @ViewChild('tmpl', {static: true}) tmpl: TemplateRef<any>;

  ngAfterContentInit() {
    const view = this.tmpl.createEmbeddedView({});
    this.childCount = view.rootNodes.length;
  }
}
```

```html
<ng-template #tmpl><ng-content select="label"></ng-content></ng-template>

<div>
  Has child count: {{childCount}} <!-- There will be 2 for VE and 1 for Ivy -->
</div>
```

```html
<app-example><label>aaa</label></app-example>
```

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/github-f2y5an-1xa2pu

If you change `enableIvy` to `false` in `tsconfig.json` you will see that there are more elements for VE. Additional `comment` element is created. There should be equal elements both for IVY and VE.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**

<pre><code>Angular CLI: 9.1.6
Node: 10.16.3
OS: darwin x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes
</code></pre>

**Anything else relevant?**

Seems like it's connected to additional comment node in VE engine: https://github.com/angular/angular/commit/a576852ad97f8bd38195bb9fe68d88b3e7f559ae#diff-96a437ab2b6a8ea3a3bf704d7e6fbeccR196

**Comment by pkozlowski-opensource** [comment]
> If you change enableIvy to false in tsconfig.json you will see that there are more elements for VE. Additional comment element is created. There should be equal elements both for IVY and VE.

Indeed, there is a change in the exact DOM creation (VE was adding additional comment, as you've observed). But we consider this a private implementation detail and the fact that ivy can get away without this additional comment node is a plus.

We've got no intention in reverting to VE behaviour as we consider ivy way of doing thing an improvement. Yes, it is change in the behaviour but we didn't expect to break any existing code. You've proved this assumption to be wrong :-)

All it all it will be won't fix I'm afraid. I do hope that you can find a work-around on your application side. To be honest driving DOM display based on number of DOM nodes in some other place is the pattern that we don't want to encourage nor support.

**Comment by wszydlak** [comment]
@pkozlowski-opensource 

How then You suggest do the checking if ng-content inside ng-container has some childrens? Cause this is what we need to achieve - we need to be sure that user put `label`. Will using `ɵivyEnabled` from `@angular/core` be good decision to check special use case of VE or there is another "better way" to do this ?

**Comment by pkozlowski-opensource** [comment]
> How then You suggest do the checking if ng-content inside ng-container has some childrens? Cause this is what we need to achieve - we need to be sure that user put label

@wszydlak I'm not sure I understand your scenario based on this brief description but it sounds like the open feature request #26083 ? Even if, I'm not sure how root nodes of a view come into play here... I can try to suggest an approach that doesn't use private implementation details, but I need to understand the exact use-case first. If you can provide a minimal stackblitz illustrating what you are trying to achieve, I might be able to help

**Comment by pkozlowski-opensource** [comment]
Oh, actually, I can see that you've provided a minimal stackblitz! So, is what you are trying to do a work-around for #26083?

**Comment by wszydlak** [comment]
@pkozlowski-opensource 
I created extra example: https://stackblitz.com/edit/github-f2y5an-kjqmxa
Without using `label-wrapper` class i would use `:empty` css selector, but i need to have html structure like this.

As you can see i need to be sure if there are exactly some `rootNodes` passed by user nas `label`
You can see with ivy this example is working properly, so as workaround I've changed expression to:

`this.hasLabel = view.rootNodes.length > (ɵivyEnabled ? 0 : 1)`

but I know that `ɵivyEnabled` is private so I'm looking for better solution.

Maybe this is connected to #26083, but I'm not sure if #26083 will also work with `ng-content` inside `ng-template`

**Comment by wszydlak** [comment]
@pkozlowski-opensource Have you looked at example above?
