### ISSUE TITLE
Angular CLI on windows 10

### ISSUE THREAD

**Issue by ashishakm** [angular/angular#37238]
npm install -g @angular/cli  throwing error on windowns 10, 
It says : to many symbolic link reconnoitered stat  \\ac2kn1012\userdata

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and **follow the instructions in the issue template**.

**Comment by petebacondarwin** [comment]
Also issues with the Angular CLI should be sent to https://github.com/angular/angular-cli/issues
