### ISSUE TITLE
Add support for observable directives and components

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#3724]
Currently, when using the experimental `ON_PUSH_OBSERVE` change detection mode, we detect all the objects that are used in bindings and implement Observable (dart observable, not Rx observable) and subscribe to them. When any of these objects fires an event, we request a check.

To make our solution complete we also need to detect if the component itself or any of the directives used in the template implement the Observable interface and subscribe to them if they do.

Example:

```
@Component(selector:'mycomponent', changeDetection:ON_PUSH_OBSERVE)
@View(
  template: """
    {{name}}
    <my-directive></my-directive>
  """,
  directives: const [MyDirective]
)
class MyComponent implements Observable {
  String name;
  //....
}

@Directive(selector: 'my-directive')
class MyDirective implements Observable {}
```

In this example:
* if MyComponent emits an event, we will request a check
* if MyDirective emits an event, we will request a check

@yjbanov @mhevery

**Comment by yjbanov** [comment]
+1
