### ISSUE TITLE
Proxy mock object provide through TestBed gets removed during test execution

### ISSUE THREAD

**Issue by DW8Reaper** [angular/angular#37242]
# 🐞 bug report

### Affected Package
This issue is caused by @angular/compiler more specifically:

- [line 39 - util.ts]{https://github.com/angular/angular/blob/88b0985bad498f2fdd6bc8846279f63ed3acb205/packages/compiler/src/util.ts#L39) - checks to see if an object is a map of  strings. Because the proxy was created as ```new Proxy({}, ...```
- the proxy matches and is then replaced by a new object by ```visitor.visitStringMap```

### Is this a regression?
I have had this issue in multiple angular releases

### Description
If you use a proxy object as the provided value in a unit test (this is done by some mocking frameworks like ts-mockito) the proxy is removed when the test runs.

In the reproduction I made a simple proxy manually that returns the mocked method:
<pre><code>
    const mockedSomeService = new Proxy({} as SomeService, {
      get: (target, prop) => {
        if (prop === "returnSomething") {
          return () => "mocked something";
        } else {
          return target[prop];
        }
      },
    });
</code></pre>

There are some workarounds (granted it isn't obvious), the first option is to create some kind of class other than a generic object {}:
<pre><code>
    const mockedSomeService = new Proxy(new AnyClass() as SomeService, {
    ...
</code></pre>

the other is to use a factory when injecting
<pre><code>
    providers: [{ provide: SomeService, useFactory: () => mockedSomeService }],
    // instead of
    // providers: [{ provide: SomeService, useValue: mockedSomeService }], 
</code></pre>

## 🔬 Minimal Reproduction
I can't make a reproduction on stackblitz since the error occurs inside test execution, here is a repo on GitHub: https://github.com/DW8Reaper/TestBed-proxy-removal-reproduction

## 🔥 Exception or Error
When you run the test for app.component.spec.ts the test fails:
<pre><code>
AppComponent should create the app
TypeError: this.someService.returnSomething is not a function
TypeError: this.someService.returnSomething is not a function
    at AppComponent../src/app/app.component.ts.AppComponent.callTheService (http://localhost:9876/_karma_webpack_/webpack:/src/app/app.component.ts:13:29)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/src/app/app.component.spec.ts:33:48)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:391:1)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.10
Node: 12.16.1
OS: darwin x64
Angular: 7.2.16
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.10
@angular-devkit/build-angular     0.13.10
@angular-devkit/build-optimizer   0.13.10
@angular-devkit/build-webpack     0.13.10
@angular-devkit/core              7.3.10
@angular-devkit/schematics        7.3.10
@angular/cli                      7.3.10
@ngtools/webpack                  7.3.10
@schematics/angular               7.3.10
@schematics/update                0.13.10
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Comment by pkozlowski-opensource** [comment]
@DW8Reaper did you try with the latest Angular (9.x at this point)? The whole compilation and TestBed pipeline changed completely before 7.x and 9.x so the code you've linked is no longer used / relevant.

**Comment by DW8Reaper** [comment]
shucks you are absolutely correct I upgraded my sample to 9.1.6 and it works. 

My real project is on 9.1.0 and this still happens but I think it is something else since changed my reproduction to use that and it still works. I will see if I can find something else in my real project causing that.

Thanks for the help and I apologize for waisting your time on this one.
