### ISSUE TITLE
Update CONTRIBUTING.md examples

### ISSUE THREAD

**Issue by dalejodc** [angular/angular#37249]
# 📚 Docs or angular.io bug report

### Description

 
Update the [CONTRIBUTING.md](https://github.com/angular/angular/blob/master/CONTRIBUTING.md) **Commit Message Guidelines section** (commit message format and examples) in order to explicitly say that the commit body must have a minimun length of 100 characters. Also get rid or update the first example (line 179) because it would not pass the CI test because it does not have body/description.

### What's the affected URL?**
[CONTRIBUTING.md](https://github.com/angular/angular/blob/master/CONTRIBUTING.md)

### Reproduction Steps**
N/A

### Expected vs Actual Behavior**
N/A

## 📷Screenshot

A few examples of PR that are failing because of the minimum length of the commit body/description:
 
- [PR #37125](https://circleci.com/gh/angular/angular/711500?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) 
- [PR #37162](https://circleci.com/gh/angular/angular/713793?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) 
- [PR #37164](https://circleci.com/gh/angular/angular/713648?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
- ![image](https://user-images.githubusercontent.com/36966980/82625511-8c5af580-9ba2-11ea-81a0-dc1801748d10.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Browser info
N/A

### Anything else relevant?
We were talking a little bit with @Splaktar about this issue in this [thread](https://github.com/angular/angular/pull/37127#issuecomment-632099128).

**Comment by kapunahelewong** [comment]
Thanks for this, @dalejodc! We absolutely need to update this.

Status: docs team can update this with the information provided. 🎉

**Comment by ajitsinghkaler** [comment]
@kapunahelewong the information mentioned has been added to contributing.md so can this be closed or is it something I'm missing

**Comment by Splaktar** [comment]
Fixed in PR https://github.com/angular/angular/pull/37951 and commit https://github.com/angular/angular/commit/53d4859f48465b850098d08647bdfe60852adf73.

The 100 char limit rule is mentioned twice and the invalid example has been removed.
