### ISSUE TITLE
A

### ISSUE THREAD

**Issue by gregissa** [angular/angular#37259]
# 🐞 bug report

### Affected Package

 I think it happens after Angular Client compiles all the elements into their correspondent files (compiled files).

### Is this a regression?

 Not sure. I am expanding the system functionality and added a new module.

### Description

  I was debugging a Component and during the execution it shows in the Console the location where the error happened. It was pointing to a different Component, and both had the same function name (example: subitJob() function). I renamed the function to something in the component that I was testing, and now it invoked the proper function. I used "ng serve".

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.1
Node: 12.9.1
OS: win32 x64

Angular:
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.1
@angular-devkit/core         9.1.1
@angular-devkit/schematics   9.1.1
@schematics/angular          9.1.1
@schematics/update           0.901.1
rxjs                         6.5.4

</code></pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
