### ISSUE TITLE
[Guide] 'User Input' Final Code

### ISSUE THREAD

**Issue by KapuzenSohn** [angular/angular#3725]
I just did the Guide and found in the third Guide 'User Input' in the Final Code example a small typo.

In line 18 ```directives: [NgFor, NIf]```
it has to be ```NgIf``` and not ```NIf```

**Comment by vicb** [comment]
Should be fixed in https://github.com/angular/angular.io/pull/161

_Doc issues should be reported to that other repo, thanks_

**Comment by KapuzenSohn** [comment]
Nice :+1: 

Sorry, next time II will consider it

**Comment by vicb** [comment]
> Sorry, next time II will consider it

No worries, it's easy to get lost with the multiple repos
