### ISSUE TITLE
SlicePipe signature

### ISSUE THREAD

**Issue by princemaple** [angular/angular#37253]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common

### Is this a regression?

 No

### Description

Same problem with https://github.com/angular/angular/issues/35743#issue-572534549
I tried to pass something with type `any[] | null` to it, it doesn't allow it.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/slice-type-error?file=src%2Fapp%2Fapp.component.html
It doesn't really error on stackblitz, since no template type check?

## 🔥 Exception or Error
<pre><code>
      The last overload gave the following error.
        Argument of type 'any[] | null' is not assignable to parameter of type 'undefined'.
          Type 'null' is not assignable to type 'undefined'.
    
    3     &lt;ng-container *ngFor="let pair of frequentAssignees | keyvalue | sort: '-value' | slice: 0:10"&gt;
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.5
Node: 13.12.0
OS: win32 x64

Angular: 9.1.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.5
@angular-devkit/build-angular     0.901.5
@angular-devkit/build-optimizer   0.901.5
@angular-devkit/build-webpack     0.901.5
@angular-devkit/core              9.1.5
@angular-devkit/schematics        9.1.5
@angular/cdk                      9.2.1
@angular/cli                      9.1.5
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.2.1
@ngtools/webpack                  9.1.5
@schematics/angular               9.1.5
@schematics/update                0.901.5
rxjs                              6.5.3
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
Thanks for reporting. I believe this use-case is addressed in #36277.

**Comment by princemaple** [comment]
Thanks for confirming. I'll just subscribe to the referenced PR and wait for it to be merged :)

**Comment by ajitsinghkaler** [comment]
Adressed in #37447 old pr abandoned

**Comment by jelbourn** [comment]
This was fixed in #37447
