### ISSUE TITLE
[IVY][TEST] TypeError: Cannot read property 'ngModule' of undefined at <Jasmine>

### ISSUE THREAD

**Issue by sanchezcarlosjr** [angular/angular#37265]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
ivy

### Is this a regression?

"angularCompilerOptions": {
    "enableIvy": false
  }
 Yes, the previous version in which this bug was not present was: ....
`23 05 2020 21:37:35.814:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
23 05 2020 21:37:35.817:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
23 05 2020 21:37:35.868:INFO [launcher]: Starting browser ChromeHeadless 
23 05 2020 21:38:34.069:WARN [karma]: No captured browser, open http://localhost:9876/ 
23 05 2020 21:38:36.506:WARN [launcher]: ChromeHeadless have not captured in 60000 ms, killing. 
23 05 2020 21:38:43.650:INFO [launcher]: Trying to start ChromeHeadless again (1/2). 
23 05 2020 21:38:47.203:INFO [HeadlessChrome 80.0.3987 (Windows 10.0.0)]: Connected on socket 62YfA1zG5o8INa-OAAAB with id 56983364 
HeadlessChrome 80.0.3987 (Windows 10.0.0): Executed 1 of 56 (skipped 55) SUCCESS (0.22 secs / 0.008 secs)
TOTAL: 1 SUCCESS `

### Description

 A clear and concise description of the problem...
Service Testing without dependencies causes an error when I enable ivy.

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
"angularCompilerOptions": {
    "enableIvy": true
  }
<pre><code>
HeadlessChrome 80.0.3987 (Windows 10.0.0) Shell childRoutes should create routes as children of shell FAILED
        TypeError: Cannot read property 'ngModule' of undefined
            at <Jasmine>
            at isModuleWithProviders (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:39919:27)
            at expandModuleWithProviders (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:39909:1)
            at <Jasmine>
            at Function.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:39388:1)
            at getNgModuleDef (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:2210:1)
            at isNgModule (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:39927:1)
            at http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:39827:1
            at <Jasmine>
            at transitiveScopesFor (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:39819:1)
            at setScopeOnDeclaredComponents (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:39729:1)
HeadlessChrome 80.0.3987 (Windows 10.0.0): Executed 1 of 56 (1 FAILED) (skipped 55) (0.439 secs / 0.167 secs)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
  "dependencies": {
    "@angular/animations": "^9.1.0",
    "@angular/common": "^9.1.0",
    "@angular/compiler": "^9.1.0",
    "@angular/core": "^9.1.0",
    "@angular/fire": "^6.0.0",
    "@angular/forms": "^9.1.0",
    "@angular/platform-browser": "^9.1.0",
    "@angular/platform-browser-dynamic": "^9.1.0",
    "@angular/router": "^9.1.0",
    "@angular/service-worker": "^9.1.0",
    "@ckeditor/ckeditor5-angular": "^1.2.3",
    "@ckeditor/ckeditor5-build-balloon-block": "^19.0.0",
    "@ionic/angular": "^5.0.0",
    "@ngx-translate/core": "^12.0.0",
    "@ngxs/devtools-plugin": "^3.3.2",
    "@ngxs/logger-plugin": "^3.3.2",
    "@ngxs/storage-plugin": "^3.6.2",
    "@ngxs/store": "^3.3.2",
    "date-fns": "^2.9.0",
    "firebase": "^7.14.4",
    "rxjs": "^6.5.4",
    "tslib": "^1.10.1",
    "zone.js": "^0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.900",
    "@angular-devkit/build-angular": "^0.901.0",
    "@angular/cli": "~9.1.0",
    "@angular/compiler-cli": "^9.1.0",
    "@angular/language-service": "^9.1.0",
    "@angularclass/hmr": "^2.1.3",
    "@biesbjerg/ngx-translate-extract": "^4.2.0",
    "@compodoc/compodoc": "^1.1.9",
    "@ngx-rocket/scripts": "^4.0.0",
    "@ngxs/schematics": "^0.0.1-alpha.5",
    "@types/jasmine": "^3.3.13",
    "@types/jasminewd2": "^2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "firebase-tools": "^8.0.0",
    "fuzzy": "^0.1.3",
    "hads": "^2.0.1",
    "htmlhint": "^0.11.0",
    "https-proxy-agent": "^5.0.0",
    "husky": "^4.2.3",
    "inquirer": "^6.2.2",
    "inquirer-autocomplete-prompt": "^1.0.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "^3.1.0",
    "karma-coverage-istanbul-reporter": "^2.0.2",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.5.3",
    "karma-junit-reporter": "^2.0.1",
    "prettier": "^2.0.2",
    "pretty-quick": "^2.0.1",
    "protractor": "~5.4.3",
    "puppeteer": "^2.1.1",
    "stylelint": "~13.2.1",
    "stylelint-config-prettier": "^8.0.1",
    "stylelint-config-recommended-scss": "~4.2.0",
    "stylelint-config-standard": "~20.0.0",
    "stylelint-scss": "~3.16.0",
    "ts-node": "^8.8.1",
    "tslint": "~5.20.1",
    "tslint-config-prettier": "^1.14.0",
    "typescript": "~3.8.3"
  },

</code></pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment]
@sanchezcarlosjr please provide a minimal reproduce scenario (stackblitz or a link to a GitHub repository). Otherwise this issue is not actionable for us.

**Comment by pkozlowski-opensource** [comment]
@sanchezcarlosjr I'm sorry but it is really next to impossible for us to diagnose / fix this issue as we can't reproduce it given the information provided. I'm going to close this issue for now since we haven't heard back with a reproduce scenario. Happy to re-open the issue if / when you've got a reproduce scenario.
