### ISSUE TITLE
Dart transformer ChangeDetectors do not have IDs

### ISSUE THREAD

**Issue by mhevery** [angular/angular#3726]
When running WTF in Dart with transformers all ChangeDetector ids are null. The issue is [here](https://github.com/angular/angular/blob/d191ec4c333ffcbbc8c1a85dfd78d96bfffeffd1/modules/angular2/src/change_detection/abstract_change_detector.ts#L89) the `this.id` is null, it seems that `id`s are not generated in transformer mode. This makes it hard to do debugging.

**Comment by kegluneq** [comment]
I'll take a look right away

**Comment by kegluneq** [comment]
/cc @tbosch , @vsavkin 

The change detector ids are coming from [`ChangeDetectorDefinition`](https://github.com/angular/angular/blob/master/modules/angular2/src/transform/template_compiler/change_detector_codegen.dart#L105), which comes from [ProtoViewFactory](https://github.com/angular/angular/blob/master/modules/angular2/src/core/compiler/proto_view_factory.ts#L239).

Any idea why these might be coming back empty?

**Comment by kegluneq** [comment]
@mhevery can you (or someone else) post some repro steps? I haven't been able to get this to happen so far.

**Comment by mhevery** [comment]
https://travis-ci.org/angular/angular/builds/76371907

**Comment by mhevery** [comment]
@kegluneq the build is failing with some unrelated error. Could you have a look as to why?

**Comment by kegluneq** [comment]
/cc @rkirov, @vicb 

@mhevery , this is coming from package:di

```
Transform InjectorGenerator on benchmarks_external|web/src/naive_infinite_scroll/index.dart threw error: <rethrow>
Caused by The null object does not have a getter 'importsAndExports'.
```
Here is [InjectorGenerator](https://github.com/angular/di.dart/blob/master/lib/transformer/injector_generator.dart#L15)

That transformer tries to resolve, and the error is cropping up in analyzer. Here is the [getter I'm guessing we're trying to call](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/generated/resolver.dart#L6830).

Sorry I don't have more here, but I'm flying to MD tomorrow and will be OOO until Tuesday - hopefully someone with more di knowledge can track down the issue.

**Comment by vicb** [comment]
The failure was related to #3698 which has been reverted from master for now.
