### ISSUE TITLE
Reactive forms using FormBuilder.array() loses focus of input control

### ISSUE THREAD

**Issue by patilmangeshv** [angular/angular#37269]
Bug, feature request, or proposal:
Bug in ReactiveForms

What is the expected behaviour?
After entering a value the focus should remain in the input control. The input control is created using FormBuilder.array().

What is the current behaviour?
After entering a value the input control loses the focus.

What are the steps to reproduce?
Providing a github repository link below. Please refer the readme.md for more details.

https://github.com/patilmangeshv/ngFormsIssue.git

What is the use-case or motivation for changing an existing behaviour?
It seems a bug unless I am missing something in my code.

Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular version 9.1.9
OS: MacOS 10.15.4
Typescript: 3.8.3

Is there anything else we should know?
Please readme.md file for more details

**Comment by EliseoPlunker** [comment]
it's NOT a bug, is a wrong code
You can not iterate over validationsForm.controls.orderItems.value

create a getter:
```
get orderItems() {
    return this.validationsForm.controls.orderItems as FormArray;
}

```

And iterate over orderItems.controls, you need also use item.value.item for the labels
```
<div formArrayName="orderItems" >
    <ng-container *ngFor="let item of orderItems.controls; let i=index" [formGroupName]="i">
      <div>
        <label>{{item.value.item?.itemName}}</label>
        <button (click)="removeItemClicked(item.value)" slot="end"></button>
      </div>

      <div>
        <label slot="start">@{{item.value.item.rate | number:'1.0-1'}} Amt.:
          {{item.value.item.rate*item.value.quantity | number:'1.2-2'}}</label>

        <input type="number" formControlName="quantity">

        <label>{{item.value.item.unitOfMeasurement}}</label>
      </div>

      {{item.value.item.itemDescription}}
    </ng-container>
  </div>

```
see the [stackblitz](https://stackblitz.com/edit/angular-ivy-6t7yop?file=src%2Fapp%2Fapp.component.html)

**Comment by patilmangeshv** [comment]
Thanks for showing me the issue in the code. Have a nice day and stay safe.
