### ISSUE TITLE
When using AOT, changes to objects passed to forRoot are discarded when injected

### ISSUE THREAD

**Issue by bygrace1986** [angular/angular#37278]
### Versions
```
angular: 5.2.0
angular-cli: 1.6.4 (my app), 1.7.4 (my test)
typescript: 2.4.2
```

### Repro steps
Setup a module with a static `forRoot` method. That method should accept an object as a parameter that it provides via a custom injection token.
**TestModule**
```
import { NgModule, ModuleWithProviders } from '@angular/core';
import { CommonModule } from '@angular/common';

import { TestDependency, TEST_DEPENDENCY, TestService } from './test.service';

@NgModule({
  imports: [
    CommonModule
  ],
  declarations: []
})
export class TestModule {
  static forRoot(dependency?: TestDependency): ModuleWithProviders {
    return {
      ngModule: TestModule,
      providers: [
        TestService,
        { provide: TEST_DEPENDENCY, useValue: dependency }
      ]
    }
  }
}
```

Use the injection token to inject the provided object into a class.

**TestService**
```
import { Injectable, InjectionToken, Inject } from '@angular/core';

export interface TestDependency {
    property: string;
}

export const TEST_DEPENDENCY = new InjectionToken<TestDependency>('TEST_DEPENDENCY');

@Injectable()
export class TestService {
    constructor(@Inject(TEST_DEPENDENCY) dependency: TestDependency) {
        console.log('[TestService]', dependency);
    }
}
```

Create an object with a property initialized to some value. Create a new object with some properties and the properties of the first object via an object destructuring assignment (or vai Object.assign). Update one of the properties on the second object after initialization. Import the `TestModule` and pass the second object to its static `forRoot` method.

**AppModule**
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { TestModule } from './test/test.module';
import { TestDependency, TEST_DEPENDENCY } from './test/test.service';

const dependency = {
  property: 'value'
} as TestDependency;
const dependencyCopy = { id: 1, name: 'first', ...dependency };
dependencyCopy.name = 'last';
console.log('[AppModule]', dependencyCopy);

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    TestModule.forRoot(dependencyCopy)
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Setup some component to require the `TestService`.

**AppComponent**
```
import { Component } from '@angular/core';

import { TestService } from './test/test.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor(testService: TestService) {
  }
}
```

Run `ng serve --aot`. Open a browser to `http://localhost:4200`. Open the console to view the logs.

Here is a repository that can reproduce this issue: https://github.com/bygrace1986/wat

### Observed behavior
Here is the console output:
```
[AppModule] {id: 1, name: "last", property: "value"}
[TestService] {id: 1, name: "first"}
```
The object was properly modified by the object destructuring assignment and the update after initialization. The object injected into the test service is a different object (`===` returns false), the property that should have been aded by the object destructuring assignment is missing and the updated value of the `name` property is reverted. It is as if the original object before assignment and mutation is being used.

### Desired behavior
The object that I provide should be provided.

### Mention any other details that might be useful (optional)
If I provide the object at the `AppModule` level then everything works as expected.
```
imports: [
  BrowserModule,
  TestModule.forRoot()
],
providers: [
  { provide: TEST_DEPENDENCY, useValue: dependencyCopy }
]
```

The practical use case is that I have a base environment file that I am importing into my environment specific files (`environment.*.ts`). I was composing a new environment file using object destructuring assignment. When that didn't work I tried to just update the original object. When that didn't work I just extracted the properties that are provided via `forRoot` to third party libs.

My related SO post: https://stackoverflow.com/questions/50141412/when-using-aot-changes-to-objects-passed-to-forroot-are-discarded-when-injected

**Comment by alxhub** [comment]
This is a "bug" in the View Engine compiler (more realistically it could be termed a "design flaw"). Providers are entirely processed at compile time, so any objects passed via providers have a different identity than they would if not AOT-compiled.

In Ivy, providers are entirely processed at runtime and so this is a non-issue.

**Comment by JoostK** [comment]
Closing as resolved in Ivy, as the AOT compiler no longer makes literal copies of values.
