### ISSUE TITLE
Angular 9 breaks xi18n

### ISSUE THREAD

**Issue by DefeninMaxime** [angular/angular#37271]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

In angular 8+ when I use `ng xi18n`, command runs without error. Since angular 9, it produce an error.

### Description

Produced error : `Metadata collected contains an error that will be reported at runtime: Lambda not supported.`

## 🔬 Minimal Reproduction
Try to execut `ng xi18n` inside a project with lambda.

For example:
Set a new route with: 
`{ path: 'signin', loadChildren: () => import('./lazy-loader-modules/lazy.module').then(m => m.LazyModule) }`

And have a tsconfig like:
````
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": true,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "types": [
      "node",
      "fabric"
    ],
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableIvy": true,
    "allowEmptyCodegenFiles": true,
    "annotateForClosureCompiler": true,
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "enableResourceInlining": true
  }
}

````
## 🔥 Exception or Error
 `Metadata collected contains an error that will be reported at runtime: Lambda not supported.`

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.7
Node: 12.3.1
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.7
@angular-devkit/build-angular      0.900.7
@angular-devkit/build-ng-packagr   0.900.7
@angular-devkit/build-optimizer    0.900.7
@angular-devkit/build-webpack      0.900.7
@angular-devkit/core               9.0.7
@angular-devkit/schematics         9.0.7
@angular/cdk                       9.1.3
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.1.3
@ngtools/webpack                   9.0.7
@schematics/angular                9.0.7
@schematics/update                 0.900.7
ng-packagr                         9.0.3
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2

</code></pre>

**Anything else relevant?**

**Comment by lenichols** [comment]
Is this issue fixed? I seem to be running into this issue. runtime-es2015 getting 404 not found.

**Comment by petebacondarwin** [comment]
@lenichols - I am afraid that the new message extractor is still not available. That being said I wonder if your issue is the same as this? Why would you be getting a 404 error from running `ng xi18n`?

**Comment by DaSchTour** [comment]
I have a possibly similar issue with different errors. I get `Function calls are not supported in decorators` and `Cannot determine the module for class` errors when running `xi18n`.

**Comment by petebacondarwin** [comment]
@DaSchTour - the only workaround would be to change your code so that it is compatible with the ViewEngine compiler.

**Comment by petebacondarwin** [comment]
The new message extraction has been released as a stand-alone binary `localize-extract` in `@angular/localize` version `10.1.0-next.0`. You can try it out. The best way is to add the following to your package.json:

```
{
  ...
  "scripts": {
    ...
    "preextract": "ngc -p tsconfig.app.json",
    "extract": "localize-extract -s \"out-tsc/**/*.js\" -f xlf -o src/locales/messages.xlf"
    ...
  },
  ...
}
```

This will quickly compile the application TS files using the Angular compiler (including adding in the `$localize` calls) and then extract those calls into the `messages.xlf` file. You might need to tweak the options for your set up, and also I recommend ensuring that the tsconfig is setup to generate source-maps, since this will ensure that you get the correct original context for the translations.

**Comment by petebacondarwin** [comment]
The aim is for this to be integrated in to the CLI by 10.1.0
