### ISSUE TITLE
select / <option *ngFor [ngValue]> performance

### ISSUE THREAD

**Issue by sod** [angular/angular#37285]
The performance of creating `<option *ngFor [ngValue]>` is pretty sad (the syntax described at https://angular.io/api/forms/SelectControlValueAccessor)

```html
  <select [formControl]="control">
    <option *ngFor="let value of values" [ngValue]="value">{{ value }}</option>
  </select>
```

Reproduction: https://stackblitz.com/edit/angular-ivy-zrphum

See console for times. Angular needs ~25ms to render 100 options. And it gets even worse when you add BrowserAnimationsModule (as in the reproduction). It adds `ng-star-inserted` class to every option and increases the render time quite a bit. Then you are at ~35ms.

As a comparison just innerHTML'ing 100 options needs ~0.5ms. So if i only have string values, creating the options via innerHTML is 70x faster and works just as well with formControl/ngModel.

Btw. `enableProdMode()` method has no effect anymore since ivy as the value that it sets to true is not used by ivy's debug mode. It only removes the "not in prod mode" warning 😄 - so I can't show you the performance on stackblitz without all the debug overhead.

**Comment by sod** [comment]
For now I created this pipe

```typescript
import {Pipe, PipeTransform} from '@angular/core';
import {DomSanitizer, SafeHtml} from '@angular/platform-browser';

/**
 * Create options for a select to be used via innerHTML:
 *
 * Example usage (where `options` is `string[]`):
 *   <select [formControl]="myControl" [innerHTML]="options | ryOptions: 'Please select something'"></select>
 *
 * Alternative to `*ngFor` option creation as documented on https://angular.io/api/forms/SelectControlValueAccessor due to performance
 * @see https://github.com/angular/angular/issues/37285
 */

const removeNonWordCharacters = /[^\w -]/g;

@Pipe({
    name: 'ryOptions',
})
export class OptionsPipe implements PipeTransform {
    constructor(private domSanitizer: DomSanitizer) {}

    public transform(options: string[], placeholder?: string): SafeHtml {
        const placeholderHtml = placeholder ? `<option readonly value="">${placeholder}</option>` : '';
        const optionsHtml = options
            .map((value) => value?.toString().replace(removeNonWordCharacters, '') ?? '')
            .map((value) => `<option value="${value}">${value}</option>`)
            .join('');

        return this.domSanitizer.bypassSecurityTrustHtml(placeholderHtml + optionsHtml);
    }
}

```

With it i'm below the 1ms mark to create my 100 option selects.

**Comment by theodorejb** [comment]
One reason that selects perform poorly (at least when using `ngModel`) is that Angular sets the select `value` and `selectedIndex` over and over for every single option element that is rendered, rather than setting it once after rendering all the options. This would be fixed by PR #23784.

**Comment by sod** [comment]
Oh nice. Thank you for having the stamina holding onto that PR for 2 years :)

**Comment by tonivj5** [comment]
hey @sod, why did you close this issue and https://github.com/angular/angular/issues/38732? 😕 I follow them 😅

**Comment by pauldraper** [comment]
@tonivj5 you can open new issue and link to this one.

**Comment by sod** [comment]
@tonivj5 sorry. I was mad because someone requested a reproduction in https://github.com/angular/angular/issues/40361, which literally is just dropping the `HostListener` line into an universal app. That response told me, that nobody at google uses universal anyway (heck the documentation doesn't even work without javascript) so I thought, why do I even bother submitting anything and closed all my issues.
