### ISSUE TITLE
[routerLink][routerLinkActive] Add event when link becomes active

### ISSUE THREAD

**Issue by waterplea** [angular/angular#37284]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/router

### Description
I've searched a bit but didn't find such a request or discussion which feels rather strange. Right now routerLinkActive works around change detection by applying classes directly. Therefore we cannot react to this event with something like a sliding underline in the tabs of links. It would be great if routerLinkActive directive had an output that triggers when link becomes active. It's easy to make a wrapper directive or something, but it would be nice to have it out of the box.

### Describe the solution you'd like
Just an EventEmitter<boolean> output `routerLinkActivated` on `routerLinkActive` directive.

### Describe alternatives you've considered
Create a custom directive with the same logic.

**Comment by waterplea** [comment]
@atscott @pkozlowski-opensource would you consider a PR for this feature if I make one? If so, I see 3 options:

1. A `void` emitter that emits when `isActive` becomes `true`
2. A `void` emitter that emits when `isActive` changes
3. A `boolean` emitter that emits `isActive` when it changes

Which of these do you think works best?

**Comment by atscott** [comment]
@waterplea I think it makes sense to emit a boolean when the state of `isActive` changes to future-proof this feature a bit.  We can bikeshed the name of the event in the public api review stage of the PR :)

**Comment by waterplea** [comment]
The idea behind emitting only when becomes true is — if you loop over links with ngFor and listen to this output on all of them, they would all emit when changed. This would probably be suboptimal in terms of performance.

**Comment by atscott** [comment]
@waterplea I was thinking only emit when the change is from `false=>true` and vice versa. This shouldn't happen that frequently for any given link, right?

**Comment by waterplea** [comment]
Right, stupid me, it would only emit two times on routing, previous one will emit false and new one will emit true. Don't know why I thought different )

**Comment by atscott** [comment]
Hi @waterplea, did you still want to work on this feature?

**Comment by waterplea** [comment]
Yeah, I do, sorry. Busy days + vacations season 🙂

**Comment by anandtiwary** [comment]
I can pick this up if @waterplea is busy. lemme know

**Comment by waterplea** [comment]
@anandtiwary yes, you can pick it up if you want to. I'm going on another vacation next two weeks and I didn't get to this issue today :(

**Comment by anandtiwary** [comment]
Cool.  I will put up a PR. Have a nice vacation :)

**Comment by Text-only** [comment]
**Texture**

Of course;
#1 _for - <true>
@atscott[!`0-0.0615]()
