### ISSUE TITLE
Template parse error: The pipe 'Date' could not be found

### ISSUE THREAD

**Issue by jschank** [angular/angular#37287]
🐞 bug report

I have searched the issue log, and there are a few related issues:
#35583
#35467
#35232
#26436

### Affected Package

The issue is *possibly* caused by package @angular/common

### Is this a regression?

Yes, the previous version in which this bug was not present was: angular6.x

### Description
I receive the following compiler error:
ERROR in The pipe 'Date' could not be found

I have tried turning off ivy, turning off aot, building for prod, All of the suggestions in the other issues.
All the related issues have been closed - with no apparent resolution.

*Interestingly, the async pipe works fine.*
So far async and date are the only two pipes I'm using

My module imports CommonModule, as does App.module.

## 🔬 Minimal Reproduction

Other issues have offered repo steps

This is particularly frustrating because so many issues have been created. Yet still the Date pipe remains unuseable. It would be nice if there were a definitive reason why Async pipe works, and Date pipe does not. With a remedy.

## 🔥 Exception or Error
<pre><code>
The pipe 'Date' could not be found ("
      </div>
      <div class="p-col-6">
        Upda[ERROR ->]ted: {{ daq.updateDate | Date:'short' }}
      </div>
    </div>
")

In dev console
compiler.js:2387 Uncaught Error: Template parse errors:
The pipe 'Date' could not be found ("
    <div class="p-grid">
      <div class="p-col-6">
        Crea[ERROR ->]ted: {{ daq.createDate | Date:'short' }}
      </div>
      <div class="p-col-6">
"): ng:///DaqModule/CardComponent.html@27:12
The pipe 'Date' could not be found ("
      </div>
      <div class="p-col-6">
        Upda[ERROR ->]ted: {{ daq.updateDate | Date:'short' }}
      </div>
    </div>
"): ng:///DaqModule/CardComponent.html@30:12
    at syntaxError (compiler.js:2387)
    at TemplateParser.parse (compiler.js:12144)
    at JitCompiler._parseTemplate (compiler.js:27606)
    at JitCompiler._compileTemplate (compiler.js:27594)
    at compiler.js:27538
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.js:27538)
    at compiler.js:27451
    at Object.then (compiler.js:2377)
    at JitCompiler._compileModuleAndComponents (compiler.js:27450)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.7
Node: 13.12.0
OS: darwin x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.7
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.7
@angular-devkit/schematics        9.1.7
@angular/cdk                      9.2.4
@angular/cli                      9.1.7
@angular/material                 9.2.4
@ngtools/webpack                  9.1.7
@schematics/angular               9.1.7
@schematics/update                0.901.7
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
I am using a workspace created with nrwl/nx, don't know if it is relevant

**Comment by JoostK** [comment]
Pipe names are case sensitive and the `date` pipe is all lowercase.

If that does not resolve the issue, we would need a minimal reproduction to investigate.

**Comment by jschank** [comment]
OMG - I'm so dumb. Totally forgot pipes were case-sensitive.
Apologies for my frustration.
I will close this.
