### ISSUE TITLE
Open Glossary-definition links in a pop-up

### ISSUE THREAD

**Issue by jbogarthyde** [angular/angular#37294]
# 📚 Docs or angular.io bug report

### Description

When you click on a glossary link, it would be better for a small pop-up to appear showing the definition of the term, without navigating to a new page.

### What's the affected URL?**
Any AIO page with a glossary link (guide/glossary#...)

### Reproduction Steps**
Click a glossary link - try https://angular.io/guide/displaying-data

### Expected vs Actual Behavior**
 Current: replaces the current page with guide/glossary, opened to the linked term
 Preferred: Opens a pop-up with the term definition. (Every term has an anchor, so this would be the text between anchors.)
(Glossary definitions also contain glossary links - should those open another popup without closing the first one?)

**Comment by aikidave** [comment]
Closing (inactvitity).
