### ISSUE TITLE
HostBinding style parsing fails for custom properties with numbers under Ivy

### ISSUE THREAD

**Issue by SkaillZ** [angular/angular#37292]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Description
Custom properties with names that contain numbers cannot be used in a host binding with the Ivy renderer. It works fine if the custom property doesn't contain a number.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-u6ghxr

## 🔥 Exception or Error

<pre><code>ERROR Error: ASSERTION ERROR: Malformed style at location 8 in string '--color-[>>1<<]00: #f00;'. Expecting ':'.
    at throwError (core.umd.js? [sm]:1321)
    at malformedStyleError (core.umd.js? [sm]:16467)
    at consumeSeparator (core.umd.js? [sm]:16392)
    at parseStyleNext (core.umd.js? [sm]:16318)
    at parseStyle (core.umd.js? [sm]:16293)
    at styleStringParser (core.umd.js? [sm]:16574)
    at toStylingKeyValueArray (core.umd.js? [sm]:17029)
    at checkStylingMap (core.umd.js? [sm]:16693)
    at Object.ɵɵstyleMap (core.umd.js? [sm]:16562)
    at AppComponent_HostBindings (app.component.ts? [sm]:10)
</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>Angular CLI: 9.1.3
Node: 13.11.0
OS: linux x64

Angular: 9.1.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.900.7
@angular-devkit/build-angular              0.901.3
@angular-devkit/build-ng-packagr           0.901.3
@angular-devkit/build-optimizer            0.901.3
@angular-devkit/build-webpack              0.900.7
@angular-devkit/core                       9.0.7
@angular-devkit/schematics                 9.0.7
@angular/cdk                               9.2.2
@angular/cli                               9.1.3
@ngtools/webpack                           9.1.3
@nguniversal/builders                      9.1.0
@nguniversal/common                        9.1.0
@nguniversal/express-engine                9.1.0
@nguniversal/module-map-ngfactory-loader   9.0.0-next.9
@schematics/angular                        9.0.7
@schematics/update                         0.901.3
ng-packagr                                 9.1.1
rxjs                                       6.5.5
typescript                                 3.8.3
webpack                                    4.41.2
</code></pre>

**Comment by pkozlowski-opensource** [comment]
This is a confirmed bug in a style parser, thnx for reporting!
