### ISSUE TITLE
Select element with size attribute does not display nested elements

### ISSUE THREAD

**Issue by mottykohn** [angular/angular#37295]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/ I cannot pinpoint

### Is this a regression?

 I don't know

### Description

A `<select>` element with a `size` attribute only displays text in chromium based browsers. No other nested element. If I remove the size="?" it works perfectly as a dropdown.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-issue-repro2-ue9hrn

## 🔥 Exception or Error
<pre><code>

No output

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.20
Node: 12.13.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.20
@angular-devkit/build-angular     0.803.20
@angular-devkit/build-optimizer   0.803.20
@angular-devkit/build-webpack     0.803.20
@angular-devkit/core              8.3.20
@angular-devkit/schematics        8.3.20
@angular/cdk                      8.2.3
@angular/cli                      8.3.20
@angular/material                 8.2.3
@ngtools/webpack                  8.3.20
@schematics/angular               8.3.20
@schematics/update                0.803.20
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.3

</code></pre>

**Anything else relevant?**

Google Version 81.0.4044.138 (Official Build) (64-bit) -> Does not work
Does work in Firefox

Makes no difference if IVY enabled/diabled

**Comment by pkozlowski-opensource** [comment]
`<h1>` tag is invalid as a child of `<option>` element, see: https://stackoverflow.com/q/572755

If you compare DOM of the "working" example you will notice that `<h1>` is not there as HTML parser removed it. Angular creates elements through the DOM API so a HTML parser couldn't do the auto-corrections for you.

Still, the bottom line is that you've got invalid HTML.
