### ISSUE TITLE
[router] lazyload route in nested module with the same path name ignored

### ISSUE THREAD

**Issue by aitboudad** [angular/angular#37300]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

`@angular/cli: 1.2.3`

### Repro steps.

1. clone https://github.com/aitboudad/ng-router-lazyload-issue
2. run ng serve
3. navigate to `Foo route`

### The log given by the failure.

```
ERROR Error: Uncaught (in promise): Error: Cannot find 'FooSearchModule' in './search/search.module'
```

### Desired functionality.

Hi I have two nested module (`FooModule`, `BarModule`) which define a child route with the same path but located in a different root folder (`./search/search.module`).
The router only consider the first one and consider the second module as loaded.

![selection_102](https://user-images.githubusercontent.com/1753742/28479661-605bc57c-6e55-11e7-8f85-24f12889ec14.png)

#### FooModule (defined in `foo` folder)
```ts
    RouterModule.forChild([
      { path: 'foo', loadChildren: './search/search.module#FooSearchModule' },
    ])
```
#### BarModule (defined in `bar` folder)
```ts
    RouterModule.forChild([
      { path: 'bar', loadChildren: './search/search.module#BarSearchModule' },
    ])
```

**Comment by atscott** [comment]
> I think this is no longer relevant since string-based `loadChildren` has been deprecated. @atscott could you please confirm?
I confirmed that the provided example works when changing to the ES6 dynamic `import()` expression:
https://stackblitz.com/edit/angular-ivy-ectwg9?file=src%2Fapp%2Ffoo%2Ffoo.module.ts

Closing as resolved by using the new, non deprecated API.
