### ISSUE TITLE
Allow ReadonlyMap with keyvalue pipe

### ISSUE THREAD

**Issue by baanloh** [angular/angular#37308]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
The `keyvalue` pipe accept as input `Map<K, V>` but not `ReadonlyMap<K, V>`.
I don't know how exactly work the pipe, but I don't think the pipe need to change the input value.

### Describe the solution you'd like
It's possible to replace `Map<K, V>` by `ReadonlyMap<K, V>` in the `KeyValuePipe.transform` signature without break the backward compatibility.

### Describe alternatives you've considered
It's possible to add a property to the component and make a cast. But this solution don't seems proper.

**Comment by petebacondarwin** [comment]
This seems like a very reasonable request - and probably one that we should apply to other pipes that do not modify their value. Also it would not be a breaking change IMO - so perhaps we could do it in 10.1?  @IgorMinar ??
