### ISSUE TITLE
platform-server - Changes introduced in 10.0.0-next.8 to convert relative URLs to absolute URLs breaks SSR

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#37314]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/platform-server

### Is this a regression?

Yes, the previous version in which this bug was not present was: 10.0.0-next.6

### Description
I recently updated my app from Angular `10.0.0-next.6` to `10.0.0-rc.0`, after which I noticed strange behavior in SSR requests. After the update it broke the SSR for my app. I downgraded `@angular/platform-server` to  `10.0.0-next.6` and everything started working fine.

I have an http interceptor, which:

1. Converts the request url from relative to absolute urls in `intercept` method of  my `http interceptor`.
2. When on server, when I receive a response of the http request I add it to `this.transferState.set(CACHE_KEY, event as any);` and on client, I check if we already have the cached response, its served from cache otherwise request is sent to the server.

After the update if I open `http://localhost:53189` in browser, which pulls data from `https://www.mustakbil.com/ws/home/index`, request seems to be working fine.

But if I open any other url e.g. `http://localhost:53189/jobs/job/204182`, when I open it in my browser the request goes to server which should fetch data from `https://www.mustakbil.com/ws/jobs/job/204182`, render it and return final response to client. 
But this doesn't happen, and the SSR is broken.

In my component I make `http` request to `/ws/jobs/job/204182` and then in intercept method of my interceptor I convert it to `https://www.mustakbil.com/ws/jobs/job/204182`.

After https://github.com/angular/angular/pull/37071 pull request , if I `console log(req.url)` in `intercept` method of my interceptor, before any modification to the request it shows `/jobs/job/204182/ws/jobs/job/204182`, whereas I expect it to show `/ws/jobs/job/204182` because that's what I passed from my component using this code `this.http.get("/ws/jobs/job/204182")`.
 
## 🔬 Minimal Reproduction
I can add anyone from Angular team to a private repo.

## 🔥 Exception or Error
<pre><code>
SSR is broken since the server is sending request to wrong url.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.0-rc.0
Node: 12.16.2
OS: win32 x64

Angular: 10.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: <error>

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.901.7
@angular-devkit/build-angular              0.1000.0-rc.0
@angular-devkit/build-optimizer            0.901.7
@angular-devkit/build-webpack              0.901.7
@angular-devkit/core                       10.0.0-rc.0
@angular-devkit/schematics                 10.0.0-rc.0
@angular/cdk                               10.0.0-next.1
@angular/fire                              6.0.0
@angular/google-maps                       10.0.0-next.1
@angular/material                          10.0.0-next.1
@angular/pwa                               0.1000.0-rc.0
@ngtools/webpack                           9.1.7
@nguniversal/module-map-ngfactory-loader   9.0.0-next.9
@schematics/angular                        10.0.0-rc.0
@schematics/update                         0.1000.0-rc.0
rxjs                                       6.5.5
typescript                                 3.9.3
webpack                                    4.41.2
</code></pre>

**Anything else relevant?**

I am using `aspnet-prerendering` package to create `createServerRenderer`, should it cause issue?

**Comment by CaerusKaru** [comment]
Please provide a minimal reproduction, otherwise we cannot investigate this issue.

**Comment by naveedahmed1** [comment]
If I add you to a private repository, will it work?

**Comment by CaerusKaru** [comment]
No, it needs to be a public, minimal reproduction. That means a base application that should not have anything that needs to be private.

**Comment by naveedahmed1** [comment]
Ok, I will try to share the reproduction repo soon.

Meanwhile, shouldn't we use `window.location.hostname` or `location.location.hostname` ? Since `Location href` Property returns the entire URL (of the current page) and we just need the `hostname` to prepend to convert the relative url to absolute url.

Ref: https://github.com/angular/angular/pull/37071/files#diff-9284ae2ef4d515b3852aa90e1c037817R113

**Comment by CaerusKaru** [comment]
Domino only implements the `href` property ([source](https://github.com/fgnass/domino/blob/master/lib/Location.js#L12)). We'll have to look at how we want to implement this to include the base URL and current route.

**Comment by jedjebari** [comment]
I have the same issue than you @naveedahmed1 .

If we bootstrap the app on root route (http://myapp/), then everything is ok.
But if we bootstrap directly on a feature root (http://myapp/myfeature), then it breaks, because the http request is done on http://myapp/myfeature/api/blablabla instead of http://myapp/api/blablabla.

So the issue is there even without interceptor.

**Comment by CaerusKaru** [comment]
We’ve got a PR open to fix this. It’ll hopefully get into the next release.

**Comment by naveedahmed1** [comment]
I just tested it with `10.0.0-rc.4` and issue still persists. 

For root url e.g. `http://localhost:53189/` it works fine.

Whereas for urls like `http://localhost:53189/jobs/job/204235` which makes http call to `/ws/jobs/job/204235` it doesn't work. 

Ideally it should have been converted to `http://localhost:53189/ws/jobs/job/204235` but it doesn't and server log shows this error:

```
Error: ERROR TypeError [ERR_INVALID_URL]: Invalid URL: //
    at onParseError (internal/url.js:257:9)
    at new URL (internal/url.js:333:5)
    at new URL (internal/url.js:330:22)
    at ZoneClientBackend.handle (D:\MyProject\ClientApp\dist-server\main.js:1:1127731)
    at MergeMapSubscriber.project (D:\MyProject\ClientApp\dist-server\main.js:1:2720672)
    at MergeMapSubscriber._tryNext (D:\MyProject\ClientApp\dist-server\main.js:1:368682)
    at MergeMapSubscriber._next (D:\MyProject\ClientApp\dist-server\main.js:1:368574)
    at MergeMapSubscriber.next (D:\MyProject\ClientApp\dist-server\main.js:1:392600)
    at Observable_Observable._subscribe (D:\MyProject\ClientApp\dist-server\main.js:1:2386324)
    at Observable_Observable._trySubscribe (D:\MyProject\ClientApp\dist-server\main.js:1:500880) {
  input: '//',
  code: 'ERR_INVALID_URL'
}
```

I think there should also be an option to disable this automatic absolute url conversion.

**Comment by CaerusKaru** [comment]
To disable it, simply specify `url: ‘’` in the options for either renderModule or ngExpressEngine

**Comment by CaerusKaru** [comment]
Once again you have two options, either come up with a minimal reproduction for us, or open a PR with a test case that explicitly shows the failure. Because our current tests cases cover for the case from your most recent comment without error.

**Comment by naveedahmed1** [comment]
Thank you @CaerusKaru .

Since its .net core app, below is what my `main.server.ts` file looks like, do you see anything which could be causing the issue?

```
import { APP_BASE_HREF } from '@angular/common';
import { enableProdMode } from '@angular/core';
import { renderModule } from '@angular/platform-server';
import { createServerRenderer } from 'aspnet-prerendering';
import 'reflect-metadata';
import 'zone.js/dist/zone-node';
import { AppServerModule } from './app/app.module.server';
import * as myGlobals from './app/globals';

enableProdMode();

export default createServerRenderer(params => {
  const options = {
    document: params.data.originalHtml,
    url: params.url,
    extraProviders: [
      { provide: APP_BASE_HREF, useValue: params.baseUrl },
      { provide: 'BASE_URL', useValue: params.origin + params.baseUrl },
      { provide: 'origin', useValue: params.origin }
    ]
  };

  const renderPromise = renderModule(AppServerModule, options);

  return renderPromise.then((html) => {

    let statusCode = 200;
    if (myGlobals.response.statusCode === 404) {
      statusCode = 404;
      //reset status code to 200 for next request
      myGlobals.response.statusCode = 200;
    }

    return {
      html: statusCode === 404 ? '<!DOCTYPE html><html lang="en"><head><title>404 Page Not Found</title><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"></head><body style="font-family:Verdana;font-size:12px;background: url(https://www.mustakbil.com/content/images/header-pattern.png) #f9f9f9;padding:100px;"><div style="max-width:620px;min-height:200px;margin:auto;padding:50px;box-shadow:15px;box-shadow: 0 3px 1px -2px rgba(0,0,0,.2), 0 2px 2px 0 rgba(0,0,0,.14), 0 1px 5px 0 rgba(0,0,0,.12);"><p style="text-align:center"><a href="https://www.mustakbil.com"><img src="https://www.mustakbil.com/content/images/logo-round.png" border="0" width="120" /></a></p><br /><h1 style="font-size:14px;text-align:center;">Sorry Page Not Found!</h1><p style="text-align:center">It seems that the page you are looking for doesn\'t exist, or it has been removed.  <br /><br /><br /><a href="https://www.mustakbil.com" style="border:0;padding:7px 20px;text-transform:uppercase;outline:none;color:white;text-decoration:none;background-color:#4d5ec1">Click here to Continue</a></p></div></body></html>' : html, StatusCode: statusCode
    }

  });
});

```

**Comment by CaerusKaru** [comment]
Can you provide what `params.url` is? For that matter, just what your entire config option resolves to

**Comment by naveedahmed1** [comment]
`params` in `createServerRenderer` from Microsoft's `aspnet-prerendering` package contains below properties:

```
export interface BootFuncParams {
    location: any;
    origin: string;
    url: string;
    baseUrl: string;
    absoluteUrl: string;
    domainTasks: Promise<any>;
    data: any;
}
```
**Below are the values when accessing homepage:**

**origin**: http://localhost:53189
**baseUr**l: /
**url**: /
**absoluteUrl**: http://localhost:53189/

**When accessing http://localhost:53189/jobs/job/204450, I see below values in params**

**origin**: http://localhost:53189
**baseUrl**: /
**url**: /jobs/job/204450
**absoluteUrl**: http://localhost:53189/jobs/job/204450

**Comment by CaerusKaru** [comment]
URL should be absolute. That’s what we use to create the absolute URL that is prepended later on.

We’re rolling back this change in 10.0.x, but in 10.1, it will be fixed such that providing the wrong format for the URL will simply fall back to the default behavior. We’ve also added a flag for opt-in.

**Comment by naveedahmed1** [comment]
Thank you so much, changing 'url: params.url,' to `url: params.absoluteUrl,` fixed the issue.

> We’re rolling back this change in 10.0.x, but in 10.1, it will be fixed such that providing the wrong format for the URL will simply fall back to the default behavior. We’ve also added a flag for opt-in.

This would be great.
