### ISSUE TITLE
ngcc generate inline sourcemaps in `.d.ts` files and break completely DX

### ISSUE THREAD

**Issue by tonivj5** [angular/angular#37324]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/ALL

### Is this a regression?
I think yes, the previous version in which this bug was not present was: I don't know, maybe `8.x.x`.

### Description

When `ngcc` run it appends a massive source-map at the end of definition files (`.d.ts`) in every angular package, and it gets stuck my code editor (`vscode`). I have to restart `vscode` to kill the `tsserver`, and avoid to enter to any `angular`'s file definition.

## 🔬 Minimal Reproduction
`ng new ...`, `npm run start` (to run `ngcc`) and follow, for example, `Component` definition to its `.d.ts` file at `@angular/core`. VSCode and `ng-language-service` take a lot of time to process the file and consume a lot of CPU.

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/7110786/83151573-04726f80-a0fd-11ea-8d75-18399580986b.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.6
Node: 13.7.0
OS: linux x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.6
@angular-devkit/build-optimizer   0.901.6
@angular-devkit/build-webpack     0.901.6
@angular-devkit/core              8.3.25
@angular-devkit/schematics        8.3.25
@angular/cdk                      9.2.4
@angular/cli                      9.1.6
@ngtools/webpack                  9.1.6
@schematics/angular               9.1.6
@schematics/update                0.901.6
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
    
Done in 0.58s.

</code></pre>

**Anything else relevant?**
![image](https://user-images.githubusercontent.com/7110786/83151996-94181e00-a0fd-11ea-914e-8abee83729e7.png)

**Comment by petebacondarwin** [comment]
Currently ngcc tries to guess whether to add source-mapping inline or as an external file.
It does seem strange that the d.ts files are getting inline source-maps since the originals do not have one...

**Comment by tonivj5** [comment]
As a workaround, I'm removing source-maps by hand... but it's a pain :sweat:
