### ISSUE TITLE
[development] Bazel run fails to install nodejs

### ISSUE THREAD

**Issue by MatthiasKunnen** [angular/angular#37329]
### Description

I'm trying to work on the Angular source code but when I run `yarn run bazel test packages/...`, I get an error.

## 🔥 Exception or Error
```
WARNING: Download from https://mirror.bazel.build/nodejs.org/dist/v12.14.1/node-v12.14.1-linux-x64.tar.xz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
```

When I manually fetched the URL, I got the following response:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
</Error>
```

## Workaround
I've found a fix by making Bazel download from <https://nodejs.org> instead of their mirror.
This can be accomplished by the following commit: <https://github.com/MatthiasKunnen/angular/commit/3d1524388852f95be780f89f4a140e8ea5c4d778>.

If this change would be accepted I will make a PR.

## 🌍  Your Environment
OS: Ubuntu 18.0.4.4
Commit: 64fc8b8ee5343585060c3eca71931cd101859923

**Comment by jelbourn** [comment]
@MatthiasKunnen does this still happen? It looks like it may have been a transient error with the mirror.

**Comment by akuczyns** [comment]
> @MatthiasKunnen does this still happen? It looks like it may have been a transient error with the mirror.

Yes, it does:
root@485a8ae61b17:/workspaces/angular# node ./scripts/build/build-packages-dist.js
2020/12/13 14:22:10 Downloading https://releases.bazel.build/3.6.0/release/bazel-3.6.0-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: Download from https://mirror.bazel.build/nodejs.org/dist/v12.14.1/node-v12.14.1-linux-x64.tar.xz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

**Comment by petebacondarwin** [comment]
<img width="754" alt="Screenshot 2021-01-26 at 17 31 18" src="https://user-images.githubusercontent.com/15655/105881377-55c05f00-5ffc-11eb-8839-98430843921b.png">

Indeed that URL appears to be broken...

**Comment by MatthiasKunnen** [comment]
And the one on nodejs.org works: <https://nodejs.org/dist/v12.14.1/node-v12.14.1-darwin-x64.tar.gz>

**Comment by petebacondarwin** [comment]
We have recently updated to node.js 14 - https://github.com/angular/angular/commit/ee615e0744d7dd607b6ddb2482b64e4d71b09fc0

Can you check to see if this issue is resolved?

**Comment by petebacondarwin** [comment]
Actually I believe this should have been resolved by https://github.com/bazelbuild/rules_nodejs/pull/2408

**Comment by alxhub** [comment]
Considering this resolved.
