### ISSUE TITLE
Unhandled Promise rejection: Cannot read property 'selectors' of null

### ISSUE THREAD

**Issue by msalmankarim** [angular/angular#37323]
## 🌍  Your Environment

**Angular Version:**
<pre>
Angular CLI: 9.1.7
Node: 12.16.1
OS: win32 x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.7
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.7
@angular-devkit/schematics        9.1.7
@angular/cdk                      9.2.4
@angular/cli                      9.1.7
@angular/material                 9.2.4
@ngtools/webpack                  9.1.7
@schematics/angular               9.1.7
@schematics/update                0.901.7
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
<code>

</code></pre>

**Comment by msalmankarim** [comment]
I have upgraded my application from angular v7 to Angular v9. Everything seems to be until I made the production. Build was successfully made. but when I deploy on IIS Server, it gives error in browser console and nothing is displayed on the screen.

![image](https://user-images.githubusercontent.com/11595290/83150223-50241980-a0fb-11ea-84c8-02c9c6bd31e2.png)

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
