### ISSUE TITLE
A validation layer in routing to validate resolved data

### ISSUE THREAD

**Issue by MonocleKelso** [angular/angular#37326]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/router

### Description
Currently there is no way to use resolved data as part of preventing a route from loading. We use **canActivate** for authentication/authorization but we have many scenarios where dependent entities are resolved in hierarchical routes and we need to validate that the relationship is valid.

Imagine a basic case of routing to _Organizations/1/Users/2_ where the organization route resolves organization data and the user route resolves user data. It would be useful to run another level of guard after all resolvers run that ensures user 2 actually belongs to organization 1.

### Describe the solution you'd like
Another piece of configuration in the route, something like **isValid**, that runs after resolvers and follows the same signature as guards (returning a boolean or UrlTree) that would either prevent the route from loading or redirect to another spot in the app.

### Describe alternatives you've considered
We have some checks in individual components but this does not work for routes without components and does not protect child routes unless we duplicate the logic everywhere. We also use ngrx so we're doing some resolvers that wait for store updates from the "real" resolvers and then validate that data and issue a redirect manually. This feels like it muddies the purpose of resolvers.

**Comment by Airblader** [comment]
Related https://github.com/angular/angular/issues/24187
