### ISSUE TITLE
Allow state queries within animations: state('x', query(...))

### ISSUE THREAD

**Issue by nedredmond** [angular/angular#37337]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/animations

### Description
 Currently there's no way to apply state to children through querying. If I need to target a child element that is within a component in an imported library, there is no way to apply a state to that element, nor apply animations in parallel.

### Describe the solution you'd like
 As intellix suggested for closed request /issues/18775 (though requested for different reasons), I would like to query children within a container and apply state:
```
trigger('fade', [
  state('yes', [
    query('span', [
      style({
        opacity: .5,
      }),
    ]),
  ]),
]),
```

### Describe alternatives you've considered
 The workarounds provided in /issues/18775 do not work for my use case.

**Comment by alxhub** [comment]
Unfortunately we have no plans to expand the animations API currently.
