### ISSUE TITLE
Add http.d.ts to definitely typed

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#3733]
In alpha.35 I noticed that http is no longer part of the Typings file. Is this an oversight, or a breaking change?
Is http moving out of the Angular2/Angular2 module?

I don't see the renamed constant HTTP_BINDINGS either

**Comment by ericmartinezr** [comment]
Do `npm install angular2@angular2.0.0-alpha35`. This will install all de javascript files and typings.

You should import `Http` and `HTTP_BINDINGS` from 'http/http'.

https://code.angularjs.org/2.0.0-alpha.35/ <-- See that http was separated into its own file.

**Comment by thelgevold** [comment]
Interesting. The http typings file does not seem to be added on DefinitelyTyped. I will look at the npm or bower bundles instead.

**Comment by thelgevold** [comment]
The http typings file from npm causes the following errors:
typings/angular2/http.d.ts(367,16): error TS1005: ';' expected.
typings/angular2/http.d.ts(374,16): error TS1005: ';' expected.

**Comment by ericmartinezr** [comment]
Yes, I saw that too. What I did, and I was suggested to do in gitter chat was too comment those lines 
`
type-alias RequestOptionsArgs;
type-alias ResponseOptionsArgs;
`

**Comment by rixrix** [comment]
+1 same error here, tried referencing from the `bundles` typings folder

**Comment by Fank** [comment]
I think this is fixed with 10437ab85cf1e59fbcff4a4de0ab17d7d3ca14ee

**Comment by gdi2290** [comment]
For anyone looking for a workaround. During `postinstall` remove the http typings 
`rm -rf node_modules/angular2/bundles/typings/angular2/http.d.ts`
[package.json#L27](https://github.com/angular-class/angular2-webpack-starter/blob/8e4773cdf731e389228b9f394daac6faf644a1bf/package.json#L27) then install tsd that way the file won't be added to tsd.d.ts and make sure to include your own version of http type definitions [here's mine](https://github.com/angular-class/angular2-webpack-starter/blob/8e4773cdf731e389228b9f394daac6faf644a1bf/src/typings/ng2http.d.ts)

here's the tsd issue where they're doing a tsd link
https://github.com/DefinitelyTyped/tsd/issues/204

**Comment by thelgevold** [comment]
Any updates on this?

**Comment by thelgevold** [comment]
I have temporarily added a modified version to http.d.ts to my sample project. You can find it here: https://github.com/thelgevold/angular-2-samples

**Comment by thelgevold** [comment]
I confirmed as of alpha.37 that this issue has been resolved.
