### ISSUE TITLE
Firefox content script does not allow clearTimeout and clearInterval to be called in a non-global context

### ISSUE THREAD

**Issue by spaceribs** [angular/angular#37333]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/zone.js

### Is this a regression?

No

### Description

 A clear and concise description of the problem...
When calling `clearInterval` or `clearTimeout` in the restricted context of a content script on Firefox with ZoneJS initialized, the call will error out because the function is no longer being called in the context of the `window`.

## 🔬 Minimal Reproduction
Difficult to recreate, I'll update my previous testing repo later today.

## 🔥 Exception or Error
<pre><code>
ERROR TypeError: "'clearInterval' called on an object that does not implement interface Window."
</code></pre>
<img width="205" alt="image" src="https://user-images.githubusercontent.com/715484/83179116-852a6f00-a0ef-11ea-870b-04b41dc1ecbf.png">

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.1
Node: 12.16.3
OS: darwin x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/cdk                      9.2.1
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

This applies only to Firefox Web Extension content scripts, a temporary patch to work around this issue is below, placed after the zone.js import in `polyfills.ts`:
```typescript
const patchedClearTimeout = window.clearTimeout;
window.clearTimeout = function(...args) {
  return patchedClearTimeout.apply(window, args);
};

const patchedClearInterval = window.clearInterval;
window.clearInterval = function(...args) {
  return patchedClearInterval.apply(window, args);
};
```

**Comment by JiaLiPassion** [comment]
@spaceribs, please provide a reproduce repo, and I would like to do some research.

**Comment by spaceribs** [comment]
Will do!

**Comment by spaceribs** [comment]
@JiaLiPassion https://github.com/spaceribs/zonejs-angular-issue/pull/1

**Comment by JiaLiPassion** [comment]
@spaceribs , I tried your repo, but can not reproduce the issue, my firefox is 77.0.1 (64-bit)

**Comment by spaceribs** [comment]
@JiaLiPassion same version here, I have a screen recording demonstrating the issue locally for me, first without the hack, then with:

https://imgur.com/a/7EzCxAe

**Comment by JiaLiPassion** [comment]
@spaceribs , thanks, I am looking at the wrong dev console, now I can reproduce, I will try to resolve this one.
