### ISSUE TITLE
[i18n] Extract with personal library

### ISSUE THREAD

**Issue by squelix** [angular/angular#37344]
# 🐞 bug report

### Affected Package

The issue is caused by package `@angular-devkit` i18n extract or `ng-packagr` or another one.

### Description
I have a library in a Nx repo builded with `ng-packgr` and a project that is using that library.
The library is building well, and with `enableIvy` to `false` when i'm publishing, and it's working in the project when i'm serving, building and building prod mode. But when i'm trying to extract i18n, i have this following error.

It appears that this error occurs on the `async` pipe in the library and I don't know why but the Type is not well detected or I don't understand the error.

When I put the type `any` on the problematics `Observable` that ares async piped in the `html` everything is working fine.
```typescript
cities$: Observable<City[]>; => cities$: Observable<City[]> | any;

addresses$: Observable<City[]>; => addresses$: Observable<City[]> | any;

isMobile$: Observable<boolean>; => isMobile$: Observable<boolean> | any;
isTabletPortrait$: Observable<boolean>; => isTabletPortrait$: Observable<boolean> | any;
isSticky$: Observable<boolean>; => citiesisSticky: Observable<boolean> | any;
```

## 🔬 Minimal Reproduction

It's difficult to provide a reproduction because my library is in a private npm registry behind a VPN, and our project is private but i'm trying to explain everything.
But i put the problematics components in Stackblitz anyway ;) 
https://stackblitz.com/edit/angular-extract-bug

## 🔥 Exception or Error
<pre><code>ERROR in node_modules/@wizbii/angular-ui/wizbii-angular-ui.d.ts.WzbHeaderComponent.html(5,3): No overload matches this call.
  The last overload gave the following error.
    Argument of type ‘Observable<boolean>’ is not assignable to parameter of type ‘Promise<unknown>’.
node_modules/@wizbii/angular-ui/wizbii-angular-ui.d.ts.WzbHeaderComponent.html(5,3): No overload matches this call.
  The last overload gave the following error.
    Argument of type ‘Observable<boolean>’ is not assignable to parameter of type ‘Promise<any>’.
      Type ‘Observable<boolean>’ is missing the following properties from type ‘Promise<any>’: then, catch, [Symbol.toStringTag], finally
node_modules/@wizbii/angular-ui/wizbii-angular-ui.d.ts.WzbHeaderComponent.html(6,3): No overload matches this call.
  The last overload gave the following error.
    Argument of type ‘Observable<boolean>’ is not assignable to parameter of type ‘Promise<unknown>’.
node_modules/@wizbii/angular-ui/wizbii-angular-ui.d.ts.WzbHeaderComponent.html(14,7): No overload matches this call.
  The last overload gave the following error.
    Argument of type ‘Observable<boolean>’ is not assignable to parameter of type ‘Promise<any>’.
node_modules/@wizbii/angular-ui/wizbii-angular-ui.d.ts.WzbHeaderComponent.html(14,7): No overload matches this call.
  The last overload gave the following error.
    Argument of type ‘Observable<boolean>’ is not assignable to parameter of type ‘Promise<any>’.
node_modules/@wizbii/angular-ui/wizbii-angular-ui.d.ts.CityPickerComponent.html(19,17): No overload matches this call.
  The last overload gave the following error.
    Argument of type ‘Observable<City[]>’ is not assignable to parameter of type ‘Promise<any>’.
      Type ‘Observable<City[]>’ is missing the following properties from type ‘Promise<any>’: then, catch, [Symbol.toStringTag], finally
node_modules/@wizbii/angular-ui/wizbii-angular-ui.d.ts.AddressPickerComponent.html(23,17): No overload matches this call.
  The last overload gave the following error.
    Argument of type ‘Observable<City[]>’ is not assignable to parameter of type ‘Promise<any>’</code></pre>

## 🌍  Your Environment

**Angular Version:**

***In library***
<pre><code>
    "@angular/animations": "9.1.9",
    "@angular/cdk": "9.2.4",
    "@angular/common": "9.1.9",
    "@angular/compiler": "9.1.9",
    "@angular/core": "9.1.9",
    "@angular/forms": "9.1.9",
    "@angular/localize": "9.1.9",
    "@angular/material": "9.2.4",
    "@angular/platform-browser": "9.1.9",
    "@angular/platform-browser-dynamic": "9.1.9",
    "@angular/platform-server": "9.1.9",
    "@angular/router": "9.1.9",
    "@angular/service-worker": "9.1.9",
...
    "@angular-builders/custom-webpack": "9.1.0",
    "@angular-devkit/build-angular": "~0.901.7",
    "@angular-devkit/build-ng-packagr": "~0.901.7",
    "@angular/cli": "9.1.7",
    "@angular/compiler-cli": "9.1.9",
    "@angular/language-service": "^9.1.0",
...
    "ng-packagr": "9.1.5",
</code></pre>

***In project***
<pre><code>
    "@angular/animations": "9.1.9",
    "@angular/cdk": "9.2.4",
    "@angular/common": "9.1.9",
    "@angular/compiler": "9.1.9",
    "@angular/core": "9.1.9",
    "@angular/forms": "9.1.9",
    "@angular/localize": "9.1.9",
    "@angular/material": "9.2.4",
    "@angular/platform-browser": "9.1.9",
    "@angular/platform-browser-dynamic": "9.1.9",
    "@angular/platform-server": "9.1.9",
    "@angular/router": "9.1.9",
...
    "@angular-builders/custom-webpack": "9.1.0",
    "@angular-devkit/build-angular": "0.901.7",
    "@angular/cli": "9.1.7",
    "@angular/compiler-cli": "9.1.9",
    "@angular/language-service": "9.1.9",
</code></pre>

**Comment by petebacondarwin** [comment]
I'm sorry @squelix but I cannot tell what is causing the problem from these error logs. I tried downloading the stackblitz but I cannot reproduce the error. Could you try creating a small repository that displays the problem that I can clone and test?

**Comment by squelix** [comment]
The problem is that I need to do a repo for my lib, which is in a private repository NPM that you can't access, and a repo for the project that is using that lib :/

**Comment by petebacondarwin** [comment]
I understand that you cannot expose your private code. Ideally you could try to extract out a single component (and even delete as much of the behaviour as possible) that still causes this error when extracting i18n messages.

It is not possible to help you if there is no way to diagnose the problem on our side. There are just too many moving parts and potential code and configurations on your side to guess at the problem.

**Comment by squelix** [comment]
Ok, i'll try :)

**Comment by petebacondarwin** [comment]
Without a reproduction there is nothing more we can do to help. If you are able to produce one, @squelix, please open a new issue.
