### ISSUE TITLE
Angular Service Worker Cache Not updating Instantly

### ISSUE THREAD

**Issue by pk4all** [angular/angular#37350]
Oh hi there! 😄
My Module setting is
ServiceWorkerModule.register('ngsw-worker.js', { enabled: environment.production})

My Config file setting is  ..
<code>
{
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "freshness",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/favicon.ico",
          "/index.html",
          "/*.css",
          "/*.js"
        ]
      }
    }, {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "freshness",
      "resources": {
        "files": [
          "/assets/**",
          "/*.(eot|svg|cur|jpg|png|webp|gif|otf|ttf|woff|woff2|ani)"
        ]
      }
    }
  ],
  "dataGroup":[{
    "name": "app",
    "urls":["/admin/**","https://www.jimsfresh.com.au/admin/**"],
    "cacheConfig":{
      "maxSize":5,
      "maxAge":"1h",
      "timeout":"300s",
      "strategy":"freshness"
    }
  }],
  "navigationUrls":[
    "!/admin/**"
  ]
}
</code>

My App component code is =>

<code>
updates.available.subscribe(event => {
        updates.activateUpdate().then(() => this.updateApp());
 });

updateApp(){
    this.updates.checkForUpdate().then(data=>console.log('update',data)).catch(err => console.log(err));
    console.log("The app is updating right now",'A newer version is now available');
   }

</code>

# 🐞 bug report

My site cache is not updated is load many time old cache.

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
