### ISSUE TITLE
please help me!angular8 RouteReuseStrategy scroll position error

### ISSUE THREAD

**Issue by 3833430** [angular/angular#37359]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

angular8 RouteReuseStrategy scroll position error.

When I returned to the p-table from another page, the p-table scroll bar went back to the top.
i want keep old scroll.
imports: [RouterModule.forRoot(appRoutes, {scrollPositionRestoration: 'enabled'})], is invalid

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
