### ISSUE TITLE
relativeLinkResolution: 'corrected' should be the default option

### ISSUE THREAD

**Issue by atscott** [angular/angular#37355]
https://angular.io/api/router/ExtraOptions#relativeLinkResolution
`relativeLinkResolution: 'corrected` Enables a bug fix that corrects relative link resolution in components with empty paths. 
The following issues are fixed, but continue to cause user pain because the default option is 'legacy' (used when `undefined`): #19290, #27674, #18059

**Comment by shairez** [comment]
Is this issue still relevant?

Isn't this the default in V11 already?

**Comment by atscott** [comment]
@shairez - Yes, that's right. This is done.

**Comment by shairez** [comment]
Thanks @atscott !
