### ISSUE TITLE
withCredentials:false is not working in  incognito  chrome,firefox,edge

### ISSUE THREAD

**Issue by sudha1981** [angular/angular#37356]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please read https://angular.io/guide/security#report-issues on how to disclose security related issues.

Iam developing new angular8 website with windows authentication and works fine with  in the chrome(normal),Internet explorer

But it is asking windows login prompt in the incognito chrome,firefox,edge. Share the suggestions how to fix the issue.
It seems "withCredentials: true" is not working chrome,firefox,edge browsers

![image](https://user-images.githubusercontent.com/15940070/83306345-041ec500-a220-11ea-8a8d-f6708b2d0b07.png)

Tried the below scenario but is no luck
https://karatejb.blogspot.com/2017/12/angular-windows-authentication-with-web.html

Added IIS settings and angular8 code for your reference

getAPIData(apiName): Observable {
console.log(Constants.API_URL + apiName);
let headers = this.getHeaders();
return this.http
.get(Constants.API_URL + apiName, headers)
.map((res: Response) => res.json())
}

getHeaders(): RequestOptions {
let optionsArgs: RequestOptionsArgs = { withCredentials: true }
let options = new RequestOptions(optionsArgs)
return options;
}

This code will return the web api data
   return this.http
      .get(Constants.API_URL + apiName, headers)
      .map((res: Response) => res.json())

Request URL: http://localhost/webapi/utilities/banner

![image](https://user-images.githubusercontent.com/15940070/83306420-287aa180-a220-11ea-9c0b-d4a7996e5afa.png)

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
