### ISSUE TITLE
@dannyhuly it's already working. Do you set `withCredentials` to true when make request?

### ISSUE THREAD

**Issue by sudha1981** [angular/angular#37353]
getAPIData(apiName): Observable<any> {
    console.log(Constants.API_URL + apiName);
    let headers = this.getHeaders();
    return this.http
      .get(Constants.API_URL + apiName, headers)
      .map((res: Response) => res.json())
  }

 getHeaders(): RequestOptions {
    let optionsArgs: RequestOptionsArgs = { withCredentials: true }
    let options = new RequestOptions(optionsArgs)
    return options;
  }

Enabled cors in the webapi
Same code works fine in the chrome(normal),Internet explorer

But it is asking windows login prompt in the incognito chrome,firefox,edge. Share the suggestions how to fix the issue.It seems "withCredentials: true" is not working   chrome,firefox,edge browsers

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
