### ISSUE TITLE
Warn about missing `bootstrap()` calls in entry points 

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#3735]
We only allow to omit them because some of our e2e tests (change detection for instance) do not bootstrap anything but rely on reflection remover. We should refactor all such e2e tests and add the warning.

**Comment by TedSander** [comment]
We have tests that use transformers (basically all of our unit tests,) but don't have bootstrap either. Would like to have this covered as well before we move the reflection remover.

**Comment by naomiblack** [comment]
obsolete.
