### ISSUE TITLE
Route data is not updated when upstream parameters change, reopen: #15677

### ISSUE THREAD

**Issue by GenaANTG** [angular/angular#37365]
**Bug**
There is a real problem with unexpected behavior of a route with a children modules and view state component caching.
I will reopen this issue again. Please look at this problem here: [#15677](https://github.com/angular/angular/issues/15677)

**Explanation**
Suppose we have some modules like listed below:

┌ Parent module   (e.g. exists some data resolvers for every child path)
├ Child module 1
├ Child module 2

**Unexpected behavior**
1. **Action**: navigate from the parent to the child path. (**parent -> child**)
    **Effect**: Route is changed. Resolvers works fine. Data is changed. Component view is updated.
2. **Action**: navigate from the child to the parent path. (**child -> parent**)
    **Effect**: Route is changed. Resolvers works fine. Data is changed. Component view is updated.
3. **Action**: navigate between children modules(the same parent module for both). (**child <-> child**)
    **Effect**: Route is changed. Resolvers works fine. Data is changed. **But** component view state **is the same** (old state).

**Expected behavior**
Component view should be updated when we navigate between children of the same parent module, because route is changed.

```
Angular CLI: 9.1.4
Node: 12.13.1
OS: linux x64

Angular: 9.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@angular/cdk                      9.2.2
@angular/material                 9.2.2
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
```

**Comment by pkozlowski-opensource** [comment]
@GenaANTG could you please provide a minimal reproduce scenario using stackblitz or similar? We systematically ask for a reproduction scenario to make sure that we understand, can diagnose and fix the problem.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
