### ISSUE TITLE
AppInitializer allows to load the submodule before getting the config values

### ISSUE THREAD

**Issue by NishanthRE** [angular/angular#37364]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Hi Team,
              I am working in the mono repo project which is consist of many angular projects and angular custom libraries. These are all depends on the config values from the shell application. We are getting the config values by using appinitializer factory method. In shell application, we have some imports of custom libraries in which we need to pass the config values. My doubt is like before the appinitializer loads all the submodules in the shell application are getting loaded and throws an error as config values are undefined in the submodules. Can you please suggest how to pass config values to the submodules if we need to get the config values dynamically. 

**shell application app.module.ts imports:**
`  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    SecurityModule.forRoot(environment.securityConfig),
    CoreModule.forRoot(environment),
    AppStateModule,
    CMTRoutingModule,
    CmtStateModule.forRoot(environment),`

**Instead of environment we have to pass config values dynamically**

Thanks in advance.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by poddarkhushbu07** [comment]
export function ConfigLoader(configService: AppInitService): any {
    return (): Promise<any> => configService.init();
}

providers: [AppInitService, {

        provide: APP_INITIALIZER, useFactory: ConfigLoader, deps:
[AppInitService], multi: true

    }]


export class AppInitService {
> constructor(private httpClient: HttpClient, private injector: Injector) {

}
> init(): Promise<any> {
> return new Promise((resolve: any): any => {
> this.httpClient.get(URL_TO_FETCH_VALUES).subscribe((data: any) => {
> // Assign values in your lib from here.
>
resolve();

> });

**Comment by NishanthRE** [comment]
@poddarkhushbu07  i can load the config values using appinitializer but my custom libraries which needs config values are loading before the appinitializer . How to load custom library module after getting the config values. do you have any sample code?

 ```
this.httpClient.get(URL_TO_FETCH_VALUES).subscribe((data: any) => {
 // Assign values in your lib from here.
//**how can i assing values to library from here**
```

**Comment by petebacondarwin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`. If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
