### ISSUE TITLE
How to set child component angular expression from parant model string value like passing expression {{row.parentId}} as string? 

### ISSUE THREAD

**Issue by waqaxs** [angular/angular#37374]
Hi, 
I'm creating generic responsive mat table which will work with any type of data and data types and passing all table and column options from database. For that purpose, every thing is completed and working except angular expressions conversion from string. E.g if we create mat table column of button type in my database then user should define button url for click event. Here user will set row + someId  like {{row.someId}} and that will be passed along with grid data, grid options and grid columns to work. 

# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by petebacondarwin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
