### ISSUE TITLE
Cannot read property 'toLowerCase' of null at HttpXsrfInterceptor.intercept

### ISSUE THREAD

**Issue by alvipeo** [angular/angular#37381]
v.9.1.9

look at this - https://github.com/manfredsteyer/angular-oauth2-oidc/issues/828.

And it seems like the issue is [at HttpXsrfInterceptor.intercept](https://github.com/angular/angular/blob/d1ea1f4c7f3358b730b0d94e65b00bc28cae279c/packages/common/http/src/xsrf.ts#L76).

It could be that's an angular-oauth2-oidc issue but I actually doubt it.

**Comment by JoostK** [comment]
`HttpRequest.url` is declared as non-nullable in TypeScript, so a null value for URLs is not supported. Consequently, it is the responsibility of the caller not to create an `HttpRequest` with a null value at runtime, which appears to be happening here. As such, closing as not a framework issue.
