### ISSUE TITLE
Adding headers with interceptor cause CORS 

### ISSUE THREAD

**Issue by iamabs2001** [angular/angular#37392]
I added my jwt token in headers with help of interceptor then my request has been blocked by CORS policy

To Reproduce : 
1) ng g interceptor
2) ADD headers to interceptor
3) call a http request
4) Error

Access to XMLHttpRequest at 'http://localhost:8080/api/user/profile' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

Angular Version : 9.1.0-rc.0

**Comment by AlexAegis** [comment]
CORS issues have little to do with Angular. You are trying to request from a resource from another domain. localhost:4200 is a different domain than localhost:8080, ports count.

Either your server needs to add the Access-Control-Allow-Origin header when it replies to the preflight OPTIONS request (which is a must for the deployed application to not run into CORS issues unless they are deployed to the same domain) or while using the development server you can define a proxy definition and map the 8080 domain under 4200

Here's an article that might help:
https://medium.com/better-programming/setup-a-proxy-for-api-calls-for-your-angular-cli-app-6566c02a8c4d

**Comment by pkozlowski-opensource** [comment]
@AlexAegis is totally right here (thnx for helping out with the issues on GitHub, much appreciated!).
Closing as a support request.

**Comment by iamabs2001** [comment]
**cors support is already added in my node.js server** and the cors issues does not occurred when i tried http request without interceptors. **The interceptor is causing the cors problem. **

**Comment by AlexAegis** [comment]
Can you show me that interceptor?

**Comment by mlc-mlapis** [comment]
[**@iamabs2001**](https://github.com/iamabs2001) Remember, that CORS is the server side thing.

**Comment by iamabs2001** [comment]
leave I'm fool i don't no where to add cors header okay
