### ISSUE TITLE
Create examples for Creating libraries topic

### ISSUE THREAD

**Issue by aikithoughts** [angular/angular#37394]
# 📚 Docs or angular.io bug report

### Description

We recently updated the creating libraries topic in [PR 36144](https://github.com/angular/angular/pull/36144), However, the examples are hard-coded into the topic. 

We need to create an example that we can run, test, and include in the topic.

### What's the affected URL?**
angular.io/guide/creating-libraries

### Reproduction Steps**
1. Open source for topic
2. Notice that examples are hard-coded.

### Expected vs Actual Behavior**
n/a

## 📷Screenshot
n/a

## 🔥 Exception or Error
n/a

**Comment by kapunahelewong** [comment]
Cool! @aikidave, I've worked on creating an example from the doc but I'm not using the abstract class correctly (so it won't compile, but I think it's a little fix, not a big one): https://stackblitz.com/edit/lightweight-tokens
