### ISSUE TITLE
Typed WrappedValue

### ISSUE THREAD

**Issue by william-lohan** [angular/angular#37396]
# 🚀 feature request

### Relevant Package
@angular/core

### Description
Typed `WrappedValue` (`WrappedValue<T>`) so custom async pipes' `transform` method can return something like  `string | WrappedValue<string>` so you can insure you are passing the right value to `return WrappedValue.wrap(this._latestValue);`

### Describe the solution you'd like
Something like:
```ts
class WrappedValue<T = any> {
  wrapped: T;
  constructor(value: T);
  static wrap<T>(value: T): WrappedValue<T>;
  static unwrap<T>(value: T | WrappedValue<T>): T;
  static isWrapped(value: any): value is WrappedValue;
}
```

### Describe alternatives you've considered
Having custom async pipes' `transform` method return `string | WrappedValue` (which doesn't protect `WrappedValue` from containing something other than a string) or `any`.

**Comment by jelbourn** [comment]
`WrappedValue` has been deprecated and is planned to be removed in Angular v12, so closing this issue.
