### ISSUE TITLE
Ivy not flowing type information across all ngFor occurrences

### ISSUE THREAD

**Issue by msorens** [angular/angular#37401]
# 🐞 bug report

### Affected Package

Not known

### Is this a regression?

No

### Description

 
When I turn on `strictInputTypes` in `angularCompilerOptions` in tsconfig.json I am getting a variety of errors due to type inference apparently not working for all occurrences of `ngFor`. I found [this issue](https://github.com/angular/angular/issues/12398) indicating that it should be working for Ivy with this setting.

This problem occurs on some of my uses of ngFor--_but not all of them_. For most of them it is working fine, and by "working" I mean that VSCode shows the correct type (rather than `any`) when I hover over a use of the local variable inside the `ngFor` block. In this image, the type correctly shows for the source list (top), while the bottom shows type inference for the individual item from that list:

![image](https://user-images.githubusercontent.com/6817500/83552337-73194980-a4be-11ea-826b-3c928f4bdc52.png)

Now here is one where it does not work--the list (top) still shows the correct type but the individual item (bottom) shows just `any`:

![image](https://user-images.githubusercontent.com/6817500/83552922-5b8e9080-a4bf-11ea-9995-81056e5df4bb.png)

Our code base is open source, so here are some other occurrences where it works fine:
https://github.com/chef/automate/blob/89266c693922da93fd0c47df37fc3ae4fa2bccdc/components/automate-ui/src/app/components/sidebar/sidebar.component.html#L7-L11
https://github.com/chef/automate/blob/89266c693922da93fd0c47df37fc3ae4fa2bccdc/components/automate-ui/src/app/components/sidebar/sidebar.component.html#L12-L17
https://github.com/chef/automate/blob/675940bf21f3da669014d6e22816dd60bcc74099/components/automate-ui/src/app/components/notifications/notifications.component.html#L2-L5
https://github.com/chef/automate/blob/8b4dd26cf00441b8746e43c272c102c8c55df3d9/components/automate-ui/src/app/modules/desktop/insight/insight.component.html#L108-L112
https://github.com/chef/automate/blob/72325ab808f09179be86c193efd2b817d19735a4/components/automate-ui/src/app/pages/project/list/project-list.component.html#L29-L31

And here are some occurrences where it is broken:
https://github.com/chef/automate/blob/1ca3deb611fa1ab5bbf28cfb55179011e16d4a3e/components/automate-ui/src/app/components/tabs/tabs.component.html#L2-L3
https://github.com/chef/automate/blob/129df76f089f698172d1318a927510c94effe671/components/automate-ui/src/app/page-components/search-bar/search-bar.component.html#L36-L39
https://github.com/chef/automate/blob/228e5a1d5eda471f6139f66cfd72a4420a67b5e2/components/automate-ui/src/app/pages/project/rules/project-rules.component.html#L84-L87
https://github.com/chef/automate/blob/55eae9595b3aeab1e7c43128c6079c778d858df5/components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-nodes/reporting-nodes.component.html#L173-L175

We have about 140 `ngFor` occurrences in our code base. I checked around 20 or 25 of those and found that about 80% of them were working correctly. (In fact, the broken ones above were the only broken ones I could find.) I am guessing there is something wrong in our code causing this, but I have not been able to discern any pattern.

## 🔬 Minimal Reproduction
Not sure how to isolate it.

 

## 🔥 Exception or Error
NA

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.4
Node: 12.13.1
OS: darwin x64

Angular: 9.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@angular/cdk                      9.2.2
@angular/material                 9.2.2
@ngtools/webpack                  9.1.4
@nguniversal/common               9.0.0-rc.2
@nguniversal/express-engine       9.0.0-rc.2
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
No

**Comment by JoostK** [comment]
Heya, thanks for reporting.

VS Code depends on the Angular Language Service which unfortunately does not yet benefit from Ivy's improved type checking. There's #35513 as tracking issue and loads more issues that are due to the discrepancy.

You can check whether the Ivy type checker itself is affected, for example by changing `selectTab`'s parameter to be incompatible, e.g. `number`, and see if it produces a type check error. If it does, type inference is working correctly, but if no error is produced then `tab` is genuinely `any`.

**Comment by JoostK** [comment]
The question is whether an actual build would give an error, so running `ng build` should fail if I'm not mistaken.

**Comment by msorens** [comment]
Ah, I misinterpreted your comment. With an `ng build` and `strictInputTypes` set to true, I do indeed get the expected error:
```
src/app/components/tabs/tabs.component.html:3:32 -
  error TS2345: Argument of type 'TabComponent'
    is not assignable to parameter of type 'number'.

3     <button (click)="selectTab(tab)" class="nav-tab" [class.active]="tab.active">
                                 ~~~
```

**Comment by JoostK** [comment]
Ah cool, thanks for checking. That's good, as it confirms this is a language service only issue.

There is work in progress to integrate Ivy's template type checking capabilities into the language service to overcome these discrepancies. No ETA at this moment though, but [it's materializing here](https://github.com/angular/angular/tree/master/packages/language-service/ivy) if you're interested.

**Comment by msorens** [comment]
FYI: My goal is to turn on all the new Ivy-supported strict checks in `angularCompilerOptions`, so now I will impatiently tap my foot and wait for the downstream fixes to the language service. 😁 

Thanks for your guidance and info!

**Comment by JoostK** [comment]
Note that at the moment, any of the `strict*` flags you set will not be picked up by the language service anyway, as that is also one of its weak points. So your effort to switch these flags on should not be gated on LS support (although it my negatively affect your workflow where the actual compilation (`ng build`) produces errors where LS did not find an issue during development)

**Comment by JoostK** [comment]
This is now working in the Ivy language service, provided that `strictTemplate` is enabled.
