### ISSUE TITLE
lazy loading, service worker and performance

### ISSUE THREAD

**Issue by GlauberF** [angular/angular#37406]
# 🐞 bug report

### Affected Package
@angular/....

### Description
I'm using lazy loading and service worker, however when starting the application for the first time, it calls many js files (networks tab) and this is causing loss of performance.
tested via audit.
I don't know where I'm going, because I shouldn't call too many files and the performance and notes in the audit should also be good, because today everything is loaded in lazy mode, nothing is called in advance

## 🔬 Minimal Reproduction
APP: https://app1.vimbo.com.br/pages/auth/login

structuring:
![Captura de Tela_selecionar área_20200602185541](https://user-images.githubusercontent.com/11314585/83573898-b2698980-a502-11ea-9b2a-f98e21b49c3b.png)
![Captura de Tela_selecionar área_20200602190038](https://user-images.githubusercontent.com/11314585/83574208-6408ba80-a503-11ea-81bc-9377f9c35860.png)

```ts
RouterModule.forRoot(appRoutes, {
      initialNavigation: 'enabled'
})
```

maybe you are calling all these files, why the services within each module / app of the application, have providedIn as root, am I right?
If that's the problem, then how should it look?

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.7
Node: 12.16.3
OS: linux x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.7
@angular-devkit/build-angular      0.901.7
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.7
@angular-devkit/core               9.1.7
@angular-devkit/schematics         9.1.7
@angular/cdk                       9.2.4
@angular/cli                       9.1.7
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.2.4
@angular/material-moment-adapter   9.2.4
@ngtools/webpack                   9.1.7
@nguniversal/builders              9.1.1
@nguniversal/common                9.1.1
@nguniversal/express-engine        9.1.1
@schematics/angular                9.1.7
@schematics/update                 0.901.7
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0

</code></pre>

**Comment by gkalpak** [comment]
It is really hard to know what is going on without getting our hands on the code. Can you please provide the (non-minified) code of a minimal reproduction and explain which requests you are not expecting? Otherwise, there is really not much we can do.

**Comment by GlauberF** [comment]
hello @gkalpak , sorry follow the link: https://we.tl/t-2cC8wzST8c.
If you check the site where I put it in the description of the issue, it takes a long time to start even with a lazy load on everything and looking at the tab network, he makes a lot of requests, maybe something related to that.
It probably won't take long for your tests because I'm sending a minimum to reproduce the tests.

**Comment by gkalpak** [comment]
Thx, @GlauberF, for providing the code. As mentioned in my previous comment, can you please also tell us which requests you are not expecting? The reproduction is far from minimal and it is not easy to tell what might be causing the issue (or even whether there is an issue in the first place).

Since you are familiar with the code, you are in the best position to debug and gather more info. Also, I noticed you are using server-side rendering and ServiceWorker. It would help to turning these off and see if the problem still exists (so we can easily eliminate the candidate sources of the slowness).

BTW, you can set `"namedChunks": true` in your build options in `angular.json` to have named lazy-loaded chunks, which helps identify what each loaded chunk corresponds to.

**Comment by GlauberF** [comment]
@gkalpak  so, i also have a problem with server-side rendering, this issue https://github.com/angular/universal/issues/1711, the issue was in angular, it was transferred to universal angular and still waiting, because I believe it is a bug in the library.
I installed, uninstalled and nothing works.
but I will try to do some analysis.
Note: if you know how I could best debug the universal angle problem, I would appreciate it

**Comment by gkalpak** [comment]
I don't know much about universal, so I'll leave it for the universal team.
As a general advice, a minimal reproduction is key to getting faster responses in such cases :wink:

**Comment by petebacondarwin** [comment]
This issue has not had any updates and is lacking a minimal reproduction here, so it is not actionable by us. It looks like there was some discussion at https://github.com/angular/universal/issues/1711 and I am going to assume that is the place where this issue should be tracked for now.
