### ISSUE TITLE
Please add the setting to enable or disable AOT Diagnostic messages, thank you.

### ISSUE THREAD

**Issue by 1203623465** [angular/angular#37413]
Please add the setting to enable or disable AOT Diagnostic messages, thank you.
Sometimes I don’t need this feature, but those error messages can’t be turned off.

**Comment by JoostK** [comment]
What messages are you referring to?

**Comment by 1203623465** [comment]
Thank you for replying to me ，&nbsp;

Some error messages, sometimes I just don’t need the function of AOT Diagnostic, so I think maybe you can add a setting to turn off or turn on AOT Diagnostic


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Joost Koehoorn"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月3日(星期三) 下午3:40
收件人:&nbsp;"angular/angular"<angular@noreply.github.com&gt;;
抄送:&nbsp;"#97"<1203623465@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [angular/angular] Please add the setting to enable or disable AOT Diagnostic messages, thank you. (#37413)





 
What messages are you referring to?
