### ISSUE TITLE
Remove LocationUrlInterface and use abstract class

### ISSUE THREAD

**Issue by jteplitz602** [angular/angular#3741]
Once TypeScript 1.6 is released LocationURL should be an abstract class.

**Comment by mhevery** [comment]
`LocationURL` class does not exist in Angular2 Could you provide a more concrete description of the type?

**Comment by jteplitz602** [comment]
Sorry, LocationURL will exist inside of router once @matsko finishes a refactor he's working on for #3563

**Comment by mhevery** [comment]
@matsko  Please don't name things as `LocationUrlInterface` or `ILocationUrl`, it does not follow our naming conventions.

**Comment by vicb** [comment]
@mhevery do we actually have a doc describing the naming conventions ?

**Comment by mhevery** [comment]
@vicb, We do now: https://github.com/angular/angular/pull/3787

//cc @naomiblack

**Comment by btford** [comment]
@matsko – what's the state of this?

**Comment by btford** [comment]
This is now stale. We've since implemented a `PlatformLocation` class used by both strategies, and cleaned up the hierarchy. I'm going to close this, but feel free to open a new issue @jteplitz602 that reflects the current state of the codebase if this isn't resolved for you.

Thanks!
