### ISSUE TITLE
Can't resolve all parameters for Location

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular#37438]
I upgraded to Angulr9 (ssr)  and enabled Ivy.
but I got the error `Can't resolve all parameters for Location`
I don't use the service 'Location' at all, and all services uses `@Injectable`

anyway, the error trace doesn't show clearly wher is the source of this error.

```
Error: Can't resolve all parameters for Location: (?, ?).
    at syntaxError (D:\Downloads\__projects\dev\NodeJs\almogtama3\node_modules\@angular\compiler\bundles\compiler.umd.js:2845:21)
    at CompileMetadataResolver._getDependenciesMetadata (D:\Downloads\__projects\dev\NodeJs\almogtama3\node_modules\@angular\compiler\bundles\compiler.umd.js:23397:39)
    at CompileMetadataResolver._getTypeMetadata (D:\Downloads\__projects\dev\NodeJs\almogtama3\node_modules\@angular\compiler\bundles\compiler.umd.js:23289:30)
    at CompileMetadataResolver._getInjectableTypeMetadata (D:\Downloads\__projects\dev\NodeJs\almogtama3\node_modules\@angular\compiler\bundles\compiler.umd.js:23515:25)
    at CompileMetadataResolver.getProviderMetadata (D:\Downloads\__projects\dev\NodeJs\almogtama3\node_modules\@angular\compiler\bundles\compiler.umd.js:23524:26)
    at D:\Downloads\__projects\dev\NodeJs\almogtama3\node_modules\@angular\compiler\bundles\compiler.umd.js:23462:53
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver._getProvidersMetadata (D:\Downloads\__projects\dev\NodeJs\almogtama3\node_modules\@angular\compiler\bundles\compiler.umd.js:23419:23)
    at D:\Downloads\__projects\dev\NodeJs\almogtama3\node_modules\@angular\compiler\bundles\compiler.umd.js:23421:27
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver._getProvidersMetadata (D:\Downloads\__projects\dev\NodeJs\almogtama3\node_modules\@angular\compiler\bundles\compiler.umd.js:23419:23)
    at D:\Downloads\__projects\dev\NodeJs\almogtama3\node_modules\@angular\compiler\bundles\compiler.umd.js:23038:76
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (D:\Downloads\__projects\dev\NodeJs\almogtama3\node_modules\@angular\compiler\bundles\compiler.umd.js:23029:53)
    at CompileMetadataResolver.getNgModuleSummary (D:\Downloads\__projects\dev\NodeJs\almogtama3\node_modules\@angular\compiler\bundles\compiler.umd.js:22964:39)
    at D:\Downloads\__projects\dev\NodeJs\almogtama3\node_modules\@angular\compiler\bundles\compiler.umd.js:23051:59
```

reproduction: 
https://github.com/goblins-tech/almogtama3/tree/tmp

run `npm run build:browser:dev && npm run build:server:dev && npm run serve:inspect`

**Comment by ericmartinezr** [comment]
Seems to be dup of/related to https://github.com/angular/angular/issues/35924

**Comment by eng-dibo** [comment]
I already read all comments of https://github.com/angular/angular/issues/35924 but no any solution could help.
also the service that caused the error is difference

**Comment by petebacondarwin** [comment]
When I run `npm run build:browser:dev` is:

```
Error: Failed to compile entry-point ngx-formly-material-file (es2015 as esm2015) due to compilation errors:
node_modules/ngx-formly-material-file/fesm2015/ngx-formly-material-file.js:1331:26 - error NG1010: Value at position 6 in the NgModule.imports of FileTypeModule is not a reference: [object Object]

1331                 imports: [
                              ~
1332                     CommonModule,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ... 
1340                     MatFormFieldModule
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1341                 ],
```

This indicates that there is a problem with processing the `ngx-formly-material-file` with ngcc.

**Comment by eng-dibo** [comment]
I will try to remove this package and build again.
thank you for your help @petebacondarwin 

but I still ask why there is no clear error message?

**Comment by petebacondarwin** [comment]
OK, so this is a problem with the `ngx-formly-material-file` library. You can see here
 - https://unpkg.com/browse/ngx-formly-material-file@1.0.0/fesm2015/ngx-formly-material-file.js - that it is trying to import `MatTooltipModule` and `MatFormFieldModule` from the top level `@angular/material` entry-point.

```ts
import { MatTooltipModule, MatFormFieldModule } from '@angular/material';
```

This is no longer supported in Angular Material and in fact the top level typings file for Angular Material is empty, which is why ngcc is not finding the `MatFormFieldModule` type, which it needs to compile this NgModule.

Instead, the library should be importing from the correct secondary entry-points:

```ts
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatFormFieldModule } from '@angular/material/form-field';
```

If you hack `node_modules/ngx-formly-material-file/fesm2015/ngx-formly-material-file.js`  in your project to use these imports then it compiles correctly.

**Comment by petebacondarwin** [comment]
The error messaging could be more clear but there is not a huge amount that the compiler can know about the cause of this type being unavailable. (As you will see if you trawl through our issue log, there are many causes and each of them is tricky to unravel.)

**Comment by petebacondarwin** [comment]
By the way, the error message you got in the issue description is from ViewEngine, not Ivy.

**Comment by petebacondarwin** [comment]
And I suspect that your dev server setup is trying to do some more compilation of its own?

**Comment by eng-dibo** [comment]
> And I suspect that your dev server setup is trying to do some more compilation of its own?

so, I will try to use the original builders (i.e: @angular-devkit/build-angular:server) instead of @angular-builders/custom-webpack:server

if it worked, then the problem is from `webpack.server.config.js` configuration.

**Comment by jelbourn** [comment]
I suspect that this is a manifestation of #17446 - it looks like your app may be routing to a component without the module that specifies the route config importing said component's declaring `NgModule`. Going to close for now since I think that's the issue, feel free to re-file if it becomes clear that that's not the case.
