### ISSUE TITLE
select_multiple_control_value_accessor uses IE degradation 100% of the time

### ISSUE THREAD

**Issue by dgarner-boost** [angular/angular#37433]
# 🐞 bug report

### Affected Package
https://github.com/angular/angular/blob/master/packages/forms/src/directives/select_multiple_control_value_accessor.ts

### Is this a regression?

No, it's always been broken

### Description

Minor. Functionality works fine, just a mistake causing unoptimized JS

## 🔬 Minimal Reproduction

Any `<select>` will reproduce it

## 🔥 Exception or Error
```
  registerOnChange(fn: (value: any) => any): void {
    this.onChange = (_: any) => {
      const selected: Array<any> = [];
      if (_.hasOwnProperty('selectedOptions')) {
        const options: HTMLCollection = _.selectedOptions;
        for (let i = 0; i < options.length; i++) {
          const opt: any = options.item(i);
          const val: any = this._getOptionValue(opt.value);
          selected.push(val);
        }
      }
      // Degrade on IE
      else {
        const options: HTMLCollection = <HTMLCollection>_.options;
        for (let i = 0; i < options.length; i++) {
          const opt: HTMLOption = options.item(i);
          if (opt.selected) {
            const val: any = this._getOptionValue(opt.value);
            selected.push(val);
          }
        }
      }
      this.value = selected;
      fn(selected);
    };
  }
```

Notice the check for newer browers uses:
```
_.hasOwnProperty('selectedOptions')
```
This doesn't work, because it's an inherited property.
Alternatives are:
```
_.constructor.prototype.hasOwnProperty('selectedOptions')
_.selectedOptions !== undefined
'selectedOptions' in _
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.4
Node: 12.13.1
OS: win32 x64

Angular: 9.1.4
... animations, cli, common, compiler, compiler-cli, 
core, forms
... language-service, localize, platform-browser     
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

**Comment by sonukapoor** [comment]
I will take a look.

**Comment by sonukapoor** [comment]
@AndrewKushnir / @gkalpak can you please assign this to me?
