### ISSUE TITLE
Page not update until  Ctrl+R to force update at chrome.

### ISSUE THREAD

**Issue by magicdict** [angular/angular#37448]
# 🐞 bug report

### Description

I found sometime the page not update until I push  Ctrl+R to force update at chrome.
Step1: I user ng build --prod --build-optimizer to pack my project and send to my centos server.
Step2: I pick the url form address bar ,but the page is not update
Step3:I push Ctlr + R to force refresh, page is update to new.
Step4:I pick the url form address bar again,and the page return to old....

IE is OK...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

Angular 9.1.9 
chorme 83.0.4xxxx
**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by magicdict** [comment]
![Demo](https://user-images.githubusercontent.com/897796/83853616-1fba2c00-a748-11ea-97ac-ea5243ea716f.gif)

**Comment by Enngage** [comment]
Are you using `outputHashing` for your production build? By default its set to none - meaning the script names will remain the same. You should set it to `all` if you want to bust cache. See this for more details https://angular.io/cli/build

**Comment by magicdict** [comment]
> Are you using `outputHashing` for your production build? By default its set to none - meaning the script names will remain the same. You should set it to `all` if you want to bust cache. See this for more details https://angular.io/cli/build

I build proj with --prod , so the filename with hash code. like this:

![image](https://user-images.githubusercontent.com/897796/83855144-41b4ae00-a74a-11ea-8274-e52f7d4f9322.png)

**Comment by Enngage** [comment]
And how do you serve your `index.html`? It might be the case that your index.html is cached which is why it references old scripts. For example, we are deploying our angular app, including `index.html` to CDN where it gets cached and when we deploy new version (with outputHashing) we also need to notify CDN to purge our `index.html`.

Since you are using output hashing, this issue is almost certainly not related to Angular, but the way you deploy your app and how you distribute your index files.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
