### ISSUE TITLE
Registering locale data mismatch between documents and API

### ISSUE THREAD

**Issue by babajonni** [angular/angular#37449]
I'm having issues with with my pipe is throwing an error on locale data missing.

Reading the docs I says to register the locale data like this:

`registerLocaleData(localeFr, 'fr-FR');`

But when reading the common.d.ts file it says:

/**
 * Register global data to be used internally by Angular. See the
 * ["I18n guide"](guide/i18n#i18n-pipes) to know how to import additional locale data.
 *
 * The signature registerLocaleData(data: any, extraData?: any) is deprecated since v5.1
 *
 * @publicApi
 */

What is the correct use?

**Comment by petebacondarwin** [comment]
The full correct signature is:

```ts
function registerLocaleData(data: any, localeId?: string|any, extraData?: any): void;
```

So the use described in the docs is correct:

```ts
registerLocaleData(localeFr, 'fr-FR');
```

This will load the `localeFr` locale data and associate it with the `fr-FR` locale.

Without more information I can't say why your code is throwing an error. Perhaps you are using a locale code of `fr` in your code and so Angular is not able to match to the `fr-FR` locale that you loaded?

**Comment by JoostK** [comment]
As far as the deprecation comment goes, it would be good to actually declare that signature and mark it `@deprecated` with a scheduled removal.

**Comment by petebacondarwin** [comment]
Tracking at FW-2220

**Comment by babajonni** [comment]
@petebacondarwin  I just copied the code from the docs. But in reality I'm using the Norwegian locale. Like this:

`registerLocaleData(localeNo, 'nb');`
This step shouldn't be neccessary according to the docs, but I'm stil having issues:

` providers: [
    { provide: LOCALE_ID, useValue: 'nb' },
    CurrencyPipe,
    PercentPipe
  ],`

I'm using the pipe in my cocponent (not in template) like this:

`this.percent.transform(
      this.percentage,
      '1.3-3',
      'nb'
    );`

Which throws the:

`ERROR Error: "InvalidPipeArgument: 'Missing locale data for the locale "nb".' for pipe 't'"`

But if I import the locale in my App.component and console log it:

`import localeNo from '@angular/common/locales/nb';`

` console.log(localeNo);`

I do see that the data from localeNo is available. I'm using this code in a library. And this pipe works when integrating the library in an app running locally. But it throws this error when integrating the app and reploying it in prod. 

Should I perhaps try to import the locale file in my polyfills like this?

` import '@angular/common/locales/nb';`

**Comment by petebacondarwin** [comment]
It works for me: https://stackblitz.com/edit/ivy-mxaoby?file=src/app/app.module.ts

**Comment by babajonni** [comment]
@petebacondarwin  Definitively looks like so. Works for me locally too. But for some reason it doesn't work when publishing an app that uses the library which is running the pipe with locale data.

**Comment by petebacondarwin** [comment]
I'm sorry @babajonni - the framework is working as expected and we are not able to provide user support here as the issue tracker is only for reporting bugs or requesting features. 

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by babajonni** [comment]
@petebacondarwin  Yeah I understand, no worries. Thanks for reaching out and trying it!
