### ISSUE TITLE
NgFor doesn't work inside <router-outlet>

### ISSUE THREAD

**Issue by antonmoiseev** [angular/angular#3745]
Can't make NgFor and other directives to work inside `<router-outlet>`. Here is the reproducible demo application - [ng2-router-issue](https://github.com/antonmoiseev/ng2-router-issue). To start with the app run `npm install && npm start`.

The app has 3 components - AppRootCmp, HomeCmp and HelpCmp. AppRootCmp configures the routes and hosts RouterOutlet. HomeCmp and HelpCmp are loaded by the router inside the RouterOutlet. HelpCmp contains NgFor that displays the list of topics. However the list isn't displayed and no errors are thrown to the console. If I move HelpCmp from RouterOutlet to the AppRootCmp's template everything works fine.

**Comment by rosendi** [comment]
@antonmoiseev same issue. have you found where the point is?

**Comment by rosendi** [comment]
@antonmoiseev `import 'zone.js'` fixes the problem.

**Comment by antonmoiseev** [comment]
@rosendi thanks!
