### ISSUE TITLE
Route params are lost and having empty object {} while refreshing the routes.

### ISSUE THREAD

**Issue by durgapadhu** [angular/angular#37455]
In angular the lazy loaded route params data were lost while refreshing the routes. Can someone please tell me how to resolve this one..?!
const routes: Routes = [
      { path: 'users', loadChildren: () => import('./users/users.module').then(m => m.UsersModule) }
];
These usermodule route params were lost after reloading the page.

Thank you!

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
