### ISSUE TITLE
No way to set CUSTOM_ELEMENTS_SCHEMA in an Angular Element build

### ISSUE THREAD

**Issue by adrm** [angular/angular#37457]
# 🐞 bug report

### Affected Package
Probably, @angular/elements, but I don't know if this has to be fixed in core.

### Is this a regression?
No.

### Description
I am using @angular/elements to package an Angular component as a standard web component, but I am using other web components in it and the Angular complier errors saying that those elements do not exist, and I need to add CUSTOM_ELEMENTS_SCHEMA to its ngModule. I already had it added to the ngModule where now I register the Angular Element as a web component, but the error is still there and I don't see where to signal which schema should be used when compiling an Angular Element, since there is no way to specify this through the `createCustomElement` function.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-cm8oeb

## 🔥 Exception or Error
You can see the error live on the stackblitz above.

<pre><code>
Error in src/app/hello.component.ts (5:39)
'custom-element' is not a known element:
1. If 'custom-element' is an Angular component, then verify that it is part of this module.
2. If 'custom-element' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
9.1.9

Latest version of everything, I just created that stackblitz.

**Anything else relevant?**

**Comment by JoostK** [comment]
Your `HelloComponent` is not declared in any NgModule, it's only registered as a custom element from within an NgModule. Since Ivy it is possible to have a component that is not declared in an NgModule, however it means that such component does not have access to other components/directives nor a custom schema, hence the compiler produces that error.

Once you add `HelloComponent` to `NgModule.declarations` the example will start working.

**Comment by adrm** [comment]
Hi, thanks for your response.

I can confirm that your fix is working. I wasn't doing that because I don't really want this element to be part of the module, since, if I understand correctly, this will make that component to be compiled as an Angular component and also as a web component, thus creating unneeded bloat in the app just to be able to add the schema.

This is why I think that there should be a way to specify the schema in the component, so this error can be avoided without adding bloat to the app.

If I am wrong about the bloat issue, please let me know.

Thanks!

**Comment by JoostK** [comment]
> this will make that component to be compiled as an Angular component and also as a web component

The `HelloComponent` __is__ an Angular component, regardless of whether it is registered in an NgModule or not. Declaring it in an NgModule allows it to use other declarations, such as components, directives and pipes, and as shown here allows for influencing the schema configuration.

> thus creating unneeded bloat in the app just to be able to add the schema.

There won't be additional bloat by declaring the component in an NgModule. In fact, the compiled output of the NgModule will no longer include the reference to `HelloComponent`.

In this scenario, I think it makes sense to create a new NgModule specifically for `HelloComponent` to customize the schema. This NgModule wouldn't have to be used in any other way, it's just there for providing the compiler with the custom schema hint. I understand that may be a little verbose,  but it's currently the only way to make it work. Again, this additional NgModule could be tree-shaken entirely in prod builds as it's not used anywhere.

**Comment by adrm** [comment]
Understood, thanks for the help. In that case maybe this could be clarified in the docs, but my worries are solved so I will be closing this issue.
