### ISSUE TITLE
router: stricter typing for Route.pathMatch

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#37469]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/router

### Description

`Route.pathMatch` field is now typed as `string | undefined` but actually it can accept `prefix` or `full` as a valid value.
I want to restrict invalid values statically at compilation step with a string literal types.

### Describe the solution you'd like

Typing `pathMatch` as `pathMatch?: 'prefix' | 'full'`

### Describe alternatives you've considered

This is a breaking change because it may cause build error by narrowing the acceptable value (even if those already have caused runtime error).

**Comment by mhamri** [comment]
after 2 years of asking for this, finally 🥳
