### ISSUE TITLE
[BUG]: Angular 9 Ivy not working with decorators where usage Proxy class

### ISSUE THREAD

**Issue by splincode** [angular/angular#37476]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/compiler

### Is this a regression?

Yes, Angular 8 - good work with Proxy class (with VE)

Also, if I set in tsconfig.json

```
  "angularCompilerOptions": {
    "enableIvy": false,
   }
```

It will work

### Description

https://github.com/ngxs-labs/data/blob/master/lib/decorators/src/persistence/persistence.ts

I use a proxy class in the decorator, so inheritance works correctly for CommonJS, ES5, ES2016+

```ts
 return new Proxy(stateClass, {
            construct(clazz: DataStateClass, args: Any[]): StateClass {
                const stateInstance: StateClass = Reflect.construct(clazz, args);
                const providers: PersistenceProvider[] = ensureProviders(repositoryMeta, stateInstance, options);
                registerStorageProviders(providers);
                return stateInstance;
            }
        });
```

I tried instead Proxy class
https://stackoverflow.com/a/54526221/8029169

But not working with Angular 8 (for stackblitz CommonJS) and Angular 9 by comment: 

```
Tried this and it works fine unless you're in Angular :( In such a case the constructor args are assumed to be dependencies and so always undefined (even if some args are indeed provided) if this is not an Injectable() class
```

Maybe I need use other class reference instead target from decorator?

If you look at when the factory is called

```ts
   return new Proxy(stateClass, {
          get(target, prop, receiver) {

            if (prop === 'ɵfac') {
              console.log('target', 'ɵfac', prop, Reflect.get(...arguments))
             }

            return Reflect.get(...arguments);
          },
```

![image](https://user-images.githubusercontent.com/12021443/83969019-e31c3b00-a8d5-11ea-9c77-e900cdc4aeca.png)

Then I need to intercept precisely this moment of the call and after calling it, execute the corresponding code.

However `construct (clazz, args) {}` is not called.

## 🔬 Minimal Reproduction

https://github.com/ishanuda/ngxs-data-issue-mr-1

```ts
$ yarn install
$ yarn start --open 4200
```

open file `./node_modules/@ngxs-labs/data/__ivy_ngcc__/fesm2015/ngxs-labs-data-decorators.js`

I use a proxy class in one place

![image](https://user-images.githubusercontent.com/12021443/83966480-1d301180-a8c3-11ea-873a-0340dfc69a78.png)

And after reload page we don't see `console.log('Hell World')` only work `console.log('stateClass', stateClass)`. But if we downgrade to Angular 8, it's work. Why?

Angular 9 doen't invoke real constructor? Therefore, the construct method of the proxy class is not called? How can I solve this problem, since the @ngxs-labs/data package is used in many of my projects and it’s difficult now to switch to Angular 9?

## 🔥 Exception or Error

If the proxy class would work, then the logic would work.  But nothing happens

## 🌍  Your Environment

**Angular Version:**

Angular 9.1.9

**Comment by splincode** [comment]
@petebacondarwin @pkozlowski-opensource How can I solve this problem, since the `@ngxs-labs/data` package is used in many of my projects and it’s difficult now to switch to Angular 9?

**Comment by ishanuda** [comment]
Hi,
Any updates on this?
Regards

**Comment by splincode** [comment]
I will wait Angular 9.1.12

https://github.com/angular/angular/issues/35733

![image](https://user-images.githubusercontent.com/12021443/85403150-8e2f2480-b565-11ea-877f-e5fd23a50949.png)

**Comment by ishanuda** [comment]
Hi,
with angular 9.1.12 the result is the same.
even with angular 10.0.5.
regards
