### ISSUE TITLE
"Get References" in the Angular LS

### ISSUE THREAD

**Issue by ayazhafiz** [angular/angular#37496]
# "get references" in the Angular Language Service

The language service recently re-opened discussion on https://github.com/angular/vscode-ng-language-service/issues/29, which is the oldest issue in the VSCode extension repo at nearly 4 years old. Originally, the language service was planning to add support for "get references" post the Ivy migration. However, due to a lack of engineering resources available to commit to this migration and a resurgence of community interest in this feature, we have recently landed support for TS references from Angular templates (#37437).

I think we should _try_ to make this feature more powerful, since template->TS references are maybe 10% of use cases (before the mentioned commit, this was already doable by getting a definition and searching for TS references). At the same time, we don't want to invest too much time in our solutions, as it will eventually get scrapped (even if that "eventually" has no deadline). So, I suggest we constrain solutions for "get references" as

- Relatively simple, even if this leads to a less-performant solution. Today's language service already has some very large performance bottlenecks; its unlikely that a very performant "get references" will overcome the tail-end costs of parsing, analyzing modules, etc.

- Focused first on the 90% use cases

Okay, so in some order of priority combined from the two ideas above, here are my suggestions for how we _might_ be able to implement "get references":

## Case 1: Ng->TS references

This is already done by #37437. The idea is trivial - we get the TS definition for an Ng symbol and then defer searching for other TS symbols using a TS language service.

### Case 2.1: Component members

This is also straightforward. As Ng symbols, component members can only be used in the template that belongs to the component. So we just walk the Ast and record everytime we hit a usage of the symbol.

There is a bit smarter way to do this that also gives us for free information about whether the reference is in a string (a reference entry can be augmented with this information): first we grep the template for occurences of the symbol, and then descend into only the relevant Ast branches to validate the symbol. If the symbol is not a valid reference, then it's a reference in a string.

### Case 2.x: Directive members->template, Directive/Component selectors->template, ...

Here is where it gets tricky. Okay, so first we need to find all NgModules a directive/component is in; this is solved when we analyze NgModules.

Next we need to find all the templates the directive/component is being used in. We don't know we've found a usage until we parse a template, so we need to construct a set of template files to search. This can be done in two levels:

1. Include only files of NgModules that import the relevant directive

2. Use the same grep trick as in 2.1 to prune files that definitely don't have a usage

After this we parse each file and walk it to find references of the Angular item.

Needs feedback:

- Can we be smarter about the searching?
- Grepping can time-consuming and can start falling into the "very complicated" category. For example, matching a selector like `form[a][b].a.b` requires matching 16 different combinations. Here a heuristic could be put in place.

* Note: this section also applies to inputs, outputs, pipes, etc. For inputs/outputs we first find references to the enclosing directive and then search for the input/output. Pipes are imported just like directives and their "selector" is the pipe name.

### Case 3: Ng->Ng references

This only applies to references, and is localized to exactly one Ng template file. Thus the implementation can be identical to Case 2.1

Requesting review: @kyliau

**Comment by atscott** [comment]
"Get references" is supported in the Ivy language service. Closing.
