### ISSUE TITLE
mistake in online step by step guide

### ISSUE THREAD

**Issue by marco-gagliardi** [angular/angular#3749]
I apology if this is not a proper issue or if if it's not the right place to report it. 
The Final Code provided by step by step guide (page: https://angular.io/docs/js/latest/guide/user-input.html)  raises two errors due to:

- Line 10: `*ngfor` interator syntax (should be `*ng-for` I guess)
- Line 18: `NIf` directive inclusion (should be `NgIf` I guess)

**Comment by PascalPrecht** [comment]
I think this has been fixed here: https://github.com/angular/angular.io/pull/183

Might be that this is not deployed yet.

/cc @vicb @naomiblack

**Comment by vicb** [comment]
@marco-gagliardi Thanks for your report.

Docs error should be reported at https://github.com/angular/angular.io. There is a pending PR for the issues you mentioned: https://github.com/angular/angular.io/pull/192
