### ISSUE TITLE
Can't install the angular cli version 9 after installing version 10 RC 2

### ISSUE THREAD

**Issue by anirugu** [angular/angular#37510]
I tried to install the package 9 after having installed pre-version. It's showing me this error
![Capture](https://user-images.githubusercontent.com/35772421/84171825-1b379100-aa30-11ea-8864-8455e12a6697.PNG)
[](url)

I tried uninstall it and then install, it's working. If I tried to install the version 9 over 10 the following error happen.

**Comment by JoostK** [comment]
It looks like NPM is attempting to resolve `angular/cli` from Github, but it fails to download. The issue here is that the NPM package is `@angular/cli` (notice the `@` at the beginning) which should successfully resolve to NPM instead of Github.
