### ISSUE TITLE
Default value of router param

### ISSUE THREAD

**Issue by MouadZIANI** [angular/angular#37513]
Hi angular community !
It's possible to set default value of router param ?

**Comment by AndrewKushnir** [comment]
Hello @MouadZIANI, it looks like this issue doesn't contain enough information to understand what the problem/question is. I'll close this ticket, feel free to open a new one (and follow an issue template) or post your question on [StackOverflow](http://stackoverflow.com/) using tag `angular` in case you need help/advice on selecting a specific setting/configuration for your project. Thank you.
