### ISSUE TITLE
service-worker-communications: lazy-loading and promptUser

### ISSUE THREAD

**Issue by davewelsh** [angular/angular#37527]
# 📚 Docs or angular.io bug report

### Description

````
@Injectable()
export class PromptUpdateService {

  constructor(updates: SwUpdate) {
    updates.available.subscribe(event => {
      if (promptUser(event)) {
        updates.activateUpdate().then(() => document.location.reload());
      }
    });
  }
}
````

>Doing this could break lazy-loading in currently running apps, especially if the lazy-loaded chunks use filenames with hashes, which change every version.

1. The documentation seems incomplete. What should we do if we *are* using lazy-loading but we want our users to update to the latest version of the app?

2. I think it would be helpful to explain what `promptUser` is too. If it's function the developer is expected to write himself--which seems to be the case--then that could be made more clear like this:

````
@Injectable()
export class PromptUpdateService {

  constructor(updates: SwUpdate) {
    updates.available.subscribe(event => {
      if (this.promptUser(event)) {
        updates.activateUpdate().then(() => document.location.reload());
      }
    });
  }

  private promptUser(event: UpdateAvailableEvent): boolean {
    // prompt the user if now would be a good time to reload the app
  }
}
````

### What's the affected URL?**
https://angular.io/guide/service-worker-communications

**Comment by gkalpak** [comment]
Thx for reporting this, @davewelsh!

1. The `Doing this could break lazy-loading in currently running apps` part seems wrong. Activating the update without reloading could have that effect. But reloading the page once the update has been activated is fine. Maybe that is what we intended to say there.
  @kapunahelewong (since you seem to have [authored that part][1]), do you remember why you put it in there? Is there something else I am missing?

2. :+1: on being more clear that `promptUser()` is to be implemented by the app developer.

[1]: https://github.com/angular/angular/blame/7cc332efe6c01778c63c6a726f6fadb8e8655843/aio/content/guide/service-worker-communications.md#L64

**Comment by gkalpak** [comment]
FYI, I submitted #37555 which partially addresses this issue.

**Comment by kapunahelewong** [comment]
> 1. The `Doing this could break lazy-loading in currently running apps` part seems wrong. Activating the update without reloading could have that effect. But reloading the page once the update has been activated is fine. Maybe that is what we intended to say there.
>    @kapunahelewong (since you seem to have [authored that part](https://github.com/angular/angular/blame/7cc332efe6c01778c63c6a726f6fadb8e8655843/aio/content/guide/service-worker-communications.md#L64)), do you remember why you put it in there? Is there something else I am missing?

That was actually written by the then new docs members Jen and Sreevani who were still learning the process and Angular. Jen's PR https://github.com/angular/angular/pull/20021 with the [original content](https://github.com/angular/angular/pull/20021/files#diff-c19a9fd118b90328ebb847eaf54852c9R41) had to be reverted in https://github.com/angular/angular/pull/20716. So I took their work and submitted a [new PR](https://github.com/angular/angular/pull/20736) to help them through the process, but they [handled comments and content](https://github.com/angular/angular/pull/20736#issuecomment-349708673). Does that context help? Regarding service worker though, I know very little.

**Comment by gkalpak** [comment]
Thx for the info, @kapunahelewong. This looks like an oversight, so look let's move forward with #37555.

Interestingly, there was a comment about clarifying that bit in the original PR, but it was apparently never addressed: https://github.com/angular/angular/pull/20021#discussion_r149189505

**Comment by bob-watson** [comment]
P3 to at least reassess where this is after 2 years of nothing happening with it.

**Comment by JeanMeche** [comment]
Without any activity on this issue I'll close this;
