### ISSUE TITLE
Need to have nested ng-content

### ISSUE THREAD

**Issue by kumaraswamyunimity** [angular/angular#37536]
Hi,

  I need the feature component like below.

    <app-temp>
         <app-temp-items *ngFor="let data of sampleData">
                <app-temp-title>{{data.title}}</app-temp-title>
                <app-temp-head>{{data.head}}</app-temp-head>
         </app-temp-items>
     </app-temp>

currently having angular version 9. and i need support for above. thanks in advance.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
