### ISSUE TITLE
Public IP

### ISSUE THREAD

**Issue by ashish207** [angular/angular#37535]
Hi
In my office laptop I am.unable to install Angular and my admin team want to know public IP of Angular.. Can you please share the same.

**Comment by santoshyadav198613** [comment]
I doubt that this is how it works, you IT team need to set up a proxy to access it, or go for internal artifactory setup, like jfrog.

**Comment by yasinkocak** [comment]
u need acces to npm registry

https://docs.npmjs.com/misc/config#proxy

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by ashish207** [comment]
Hi Santosh

I am also wondering why they need public address of Angular. Below is the
response I got:

When try to install angular software in system software will communicate
with angular global database with multiple public ip address, so we need
all angular database public ip address.
