### ISSUE TITLE
The `global` variable in Zone.js not compatible with the one in @types/node

### ISSUE THREAD

**Issue by JasonHK** [angular/angular#37531]
# 🐞 bug report

### Affected Package

he issue is caused by package zone.js

### Is this a regression?

No.

### Description

In DefinitelyTyped/DefinitelyTyped#44700, the type definition of the `global` variable was updated to `NodeJS.Global & typeof globalThis`. Which makes the Zone.js package not compatible with @types/node 14.0.5 or up.

This issue was reported in DefinitelyTyped/DefinitelyTyped#45116.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by tachojelev** [comment]
Hello guys, is there any update on this, I can see a PR is opened. Can we expect this to be fixed and released any time soon?

**Comment by darkoandreev** [comment]
Hello guys, any update on this? I have exactly the same problem.

**Comment by chiefmc** [comment]
I'll subscribe to the thread

**Comment by JiaLiPassion** [comment]
Now the new version is under review, so please wait for some more days, thanks.

**Comment by centigrade-julian-lang** [comment]
Any news on this one? :)

**Comment by chekit** [comment]
In my case adding "es2018" to tsconfig.base.json libs section helped

**Comment by rezonant** [comment]
@chekit Careful, Zone.js does not work correctly with native async/await (which would be enabled if you build with ES2017 and above) https://github.com/angular/angular/issues/31730

**Comment by chekit** [comment]
> @chekit Careful, Zone.js does not work correctly with native async/await (which would be enabled if you build with ES2017 and above) https://github.com/angular/angular/issues/31730

Nice point, thank you. I’ll double check 👍

**Comment by JiaLiPassion** [comment]
This issue need to be resolved after updating the `@types/node` to the new version.
BTW, I used `@types/node` 14.6.2 and it seems there is no compile error, I am not sure I am using the correct way to reproduce the issue.

**Comment by Zeetah** [comment]
This affects also for example node 12.12.61. So i guess you should not make it only compliant with v14. We have had to skip already several version updates to the @types/node 12 line from 21 May onwards. 

So is there a way we could fix this soon(ish) @JiaLiPassion?

**Comment by JiaLiPassion** [comment]
@Zeetah, I don't think this can be resolved easily unless `Angular CLI` update `@types/node` for `Angular apps` to `12.12.61+`, for now, you have to use the older version of `@types/node`.

**Comment by danlz** [comment]
Upgrading zone.js to 0.11.1 helps.
