### ISSUE TITLE
Error in router.d.ts

### ISSUE THREAD

**Issue by cghislai** [angular/angular#3753]
I'm a bit puzzled about this one. I think it appeared on alpha 34. I didn't upgrade by then.
Now I updated to angular alpha35, "systemjs-builder": "^0.13","systemjs": "^0.18.10".

With a simple route config  like 
```javascript
@RouteConfig([
    {path: '/', redirectTo:'/login'},
    {path: '/login', component: LoginView, as:'login'}
])
```
I got a compilation error:
```
app/app.ts(56,14): error TS2345: Argument of type '({ path: string; redirectTo: string; } | { path: string; component: typeof LoginView; as: string;...' is not assignable to parameter of type 'List<RouteDefinition>'.
  Types of property 'push' are incompatible.
    Type '(...items: ({ path: string; redirectTo: string; } | { path: string; component: typeof LoginView; ...' is not assignable to type '(...items: RouteDefinition[]) => number'.
      Types of parameters 'items' and 'items' are incompatible.
        Type '{ path: string; redirectTo: string; } | { path: string; component: typeof LoginView; as: string; ...' is not assignable to type 'RouteDefinition'.
          Type '{ path: string; component: typeof LoginView; as: string; }' is not assignable to type 'RouteDefinition'.
            Types of property 'component' are incompatible.
              Type 'typeof LoginView' is not assignable to type 'Type | ComponentDefinition'.
                Type 'typeof LoginView' is not assignable to type 'ComponentDefinition'.
```

The only work around I found was to provide my own router.d.ts file with the following fix:
```
interface RouteDefinition {
    
     path: string;
    
     component?: Type | ComponentDefinition | any; //<= added any here
    
     loader?: Function;
    
     redirectTo?: string;
    
     as?: string;
    
     data?: any;
  }
```

The LoginView  view has nothing special

**Comment by LMFinney** [comment]
+1

**Comment by btford** [comment]
Yep, this is weird.

**Comment by btford** [comment]
@cghislai can you post at least a snippet of what `LoginView` looks like (it should include the constructor signature)? It's an ES6 class, correct?

**Comment by andersbc** [comment]
I case it is helpful: I seem to only get this error on components when the component constructor function has more than one parameter.

**Comment by cghislai** [comment]
@btford it is available here : https://github.com/cghislai/comptoir/blob/ng2-alpha-35/app/components/auth/login/login.ts

**Comment by cghislai** [comment]
With `@Query(MyView)`, components MyView also fails to match the `Type` type with:
```
error TS2345: Argument of type 'typeof MyView' is not assignable to parameter of type 'string | Type'.
  Type 'typeof MyView' is not assignable to type 'Type'.
```
`MyView` injects 3 services in its constructor, without annotations. They are bound through the `boostrap` call.
This happens on alpha 34.

**Comment by btford** [comment]
A fix for this landed in https://github.com/angular/angular/commit/a34d4c6a5f75fdc766d1e80635215550b1e4a065

So this should be in the next release.

Thanks everyone!
