### ISSUE TITLE
Angular route with Query Parameter and Appended Route

### ISSUE THREAD

**Issue by shinchan305** [angular/angular#37546]
Hello,

I am using angular 9 application.

I have a routing file with the below code

{ path: 'a/:id', component: AComponent },
{ path: 'a/b', component: BComponent },
{ path: 'a/c', component: CComponent }

I want to have the same route ('a') with query parameter (id) as well as appended routes (b & c)

When I am trying to navigate to 'a/b' OR a/c, the URL in the browser gets updated, however, it doesn't actually navigates to the desired route.

Is there any way to achieve this?

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
