### ISSUE TITLE
Using *ngFor to fill options has a problem in iphone devices

### ISSUE THREAD

**Issue by rafaeldafranca** [angular/angular#37540]
I'm filling my select element with ngFor and works fine on pc browsers and android.
When I test in iphone device, it seens that I doesn't  select anything.

![image](https://user-images.githubusercontent.com/22636978/84421849-88931f80-abf2-11ea-956a-d268f4f9f041.png)

In pc/android browsers 
![image](https://user-images.githubusercontent.com/22636978/84421997-c1cb8f80-abf2-11ea-87bf-67cfd6c555b8.png)

In Iphone 
![image](https://user-images.githubusercontent.com/22636978/84422255-20910900-abf3-11ea-81e9-79a187e634c2.png)

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by AndrewKushnir** [comment]
Hi @rafaeldafranca, as @ericmartinezr mentioned, this ticket doesn't contain enough information for us to perform further investigation. I will close it for now, feel free to create a new one (and follow the template). It'd be also important to have a minimal repro (using https://stackblitz.com/), so we can try to reproduce the issue. Thank you.
