### ISSUE TITLE
AOT Compilation drops certain functions from Route files silently

### ISSUE THREAD

**Issue by mabdrew** [angular/angular#37557]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 I am not sure

### Description

I am noticing dissonant behavior between AOT compilation and JIT compilation. This in and of itself, is not the concern. The issue is that, in this particular context, AOT and JIT behave similarly but differ without compiler warnings or errors in one particular case.

If I define a function on a route's `data` field, it will appear with JIT on `ActivatedRoute.snapshot.firstChild.data`. However, with AOT, it silently drops this field. No compiler error, no compiler warning. This seems to go against the precedent that has been set, wherein both AOT and JIT give compiler errors if you attempt to build with lambda expressions or non exported functions.

See example code below.

## 🔬 Minimal Reproduction

Serve commands with arguments I used.
 
```
ng serve -c=debug
ng serve -c=debug --aot
```

Example Route

```
  {
    path: 'someroute',
    component: SomeComponent,
    pathMatch: 'full',
    data: {
      pageTitle: 'Some | Title',
      doesShowUpWithAOT: doesShowUpWithAOT,
      // throwsCompileErrorWithAndWithoutAOT: throwsCompileErrorWithAndWithoutAOT, this behaves as expected
      doesNotShowUpWithAOTAndDoesNotThrowCompilerError() { // behaves inconsistently between JIT and AOT
        console.log('foo');
      },
      // alsoThrowsCompilerErrorWithAndWithoutAOT: () => console.log('foo') this behaves as expected
    }
```

```
// code from within some class
constructor(private _route: ActivatedRoute, private _router: Router) {
   this._router.events
      .subcribe(event => {
         if(event instanceof NavigationEnd) {
               const data = this._route.snapshot.firstChild.data;
               const functionMember = data['doesNotShowUpWithAOTAndDoesNotThrowCompilerError']; // is null with AOT, properly defined with JIT
         }
      })
}
```

I would argue, for the sake of consistency and explicitness, that both AOT and JIT should throw compiler errors, instead of the function making it through in JIT, and dropping away silently in AOT. I believe this would save development time by cutting down on debugging.

Of course, I am always open to an explanation.

Thanks!

## 🔥 Exception or Error
<pre><code>

In this particular case, there is none, which what I contend the bad behavior (bug) is.
</code></pre>

## 🌍 Your Environment
OS: Windows 10 Enterprise, 64-bit
<pre><code>

@angular-devkit/architect         0.12.1
@angular-devkit/build-angular     0.12.1
@angular-devkit/build-optimizer   0.12.1
@angular-devkit/build-webpack     0.12.1
@angular-devkit/core              7.2.1
@angular-devkit/schematics        7.2.1
@angular/cli                      7.2.1
@ngtools/webpack                  7.2.1
@schematics/angular               7.2.1
@schematics/update                0.12.1
rxjs                              6.3.3
typescript                        3.2.2
webpack                           4.23.1
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
This is similar to #21195 and #20239 and probably some more, where View Engine's AOT compiler would be unable to emit such structures incorrectly. This is no longer an issue in Ivy, so please try upgrading to latest Angular with Ivy enabled.

**Comment by mabdrew** [comment]
Hey y'all, thanks for checking this out! I just tried it out. All of our apps build with Ivy and AOT. It appears that exported functions, non exported functions, member functions on the `data` field, and member fields as lambda expressions on `data`, all work.  That's what y'all expected, right? If so, I dare say this thing closed. Thanks!

**Comment by JoostK** [comment]
@mabdrew Yes, route data is no longer constrained in AOT compilations.

I'll keep this open as a ViewEngine specific bug, but thanks for confirming that Ivy does indeed resolve the issue!

**Comment by JoostK** [comment]
Closing as resolved in Ivy.
