### ISSUE TITLE
Calling both @HostListener('window:unload', ['$event']) and @HostListener('window:beforeunload', ['$event']) on browser refresh

### ISSUE THREAD

**Issue by rangatejagolla** [angular/angular#37552]
Issue: **Calling both @HostListener('window:unload', ['$event']) and @HostListener('window:beforeunload', ['$event']) on browser refresh**

i want to clear the local storage on browser close but not on the page refresh in angular 6

I have written clearing the local storage logic in "unload" only but it is clearing on the page refresh. Internally it is executing both beforeunload and unload

Please guide me how can i stop calling the beforeunload on page refresh.

My assumption is like unload will execute on browser refresh and beforeunload will execute on browser close correct me if i am wrong.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
