### ISSUE TITLE
Local project shows Circular dependency detected warning but Stackblitz does not

### ISSUE THREAD

**Issue by alogim** [angular/angular#37550]
I am not sure which is the most appropriate section where to report this.

I have a very simple example on [Stackblitz](https://stackblitz.com/edit/angular-routing-demo-5) where I tried to use routing and children. 
I have two modules, the app-module and an authorisations module, with three children routes.

While the Stackblitz example works without returning any problem, if I try to run the same project locally on my machine it returns the following Warning:

> WARNING in Circular dependency detected:
src/app/authorisations/authorisations-routing.module.ts -> src/app/authorisations/authorisations/authorisations.component.ts -> src/app/authorisations/authorisations-routing.module.ts

> WARNING in Circular dependency detected:
src/app/authorisations/authorisations/authorisations.component.ts -> src/app/authorisations/authorisations-routing.module.ts -> src/app/authorisations/authorisations/authorisations.component.ts

I would like to fix this problem, if it is not a bug on my local machine.
Thank you in advance.

**Comment by JoostK** [comment]
Hi,

circular dependency detection is a feature in the CLI and it appears that Stackblitz does not give insight into the full build output, therefore it won't make you aware of the circular dep (but it's still there).

Circular deps do not necessarily introduce problems, depending on when exactly an import is needed. This is why the message is only a warning, not an error. In general, though, it is advised to avoid circular module dependencies.

As this is not a framework issue nor is it actionable from our side, I will close this issue. Please reach out to Stackblitz folks to request similar functionality in Stackblitz.
