### ISSUE TITLE
Update i18n doc with loadTranslations and $localize

### ISSUE THREAD

**Issue by rockument69** [angular/angular#37563]
# 📚 Docs or angular.io bug report

### Description

 
Issue first reported in https://github.com/angular/angular/issues/35776.
Related issue about length of document: https://github.com/angular/angular/issues/33461

Developers want the following:

Please add docs for `loadTranslations` and `clearTranslations`.
Use i18n for library in ng-packagr.

### What's the affected URL?**
 https://angular.io/guide/i18n#internationalization-i18n

### Expected vs Actual Behavior**

Some of this content requires a description of `$localize`, which is not a public API yet.

Doc team wants to separate the i18n doc into 3 separate docs:

Task: Translating templates for different locales
- Format data based on locale using pipes
- Prepare templates for translations
- Extract and work with translation files
- Mark plurals and alternates for translation
- Translate plurals and alternate expressions
- See [comment in PR](https://github.com/angular/angular/pull/36924/files#r426140059) about ICU expressions

Task: Localizing your app
- Set up localization
- Merge translations with the app
- Inline at compile-time
- Runtime ?
- Merge translated libraries used in the app
- Deploy app for multiple locales

Tutorial: Using $localize in your app
- Step-by-step tutorial

Other docs that need updating:
- [Creating libraries](https://angular.io/guide/creating-libraries): Build libraries with translations

For details, see the [i18n Documentation Plan](https://docs.google.com/document/d/1aV2TKsIqry7JnNiHEfhmheu5rNAbNl1IRYVhYErc7Ks/edit?usp=sharing).

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by stefan-schweiger** [comment]
What I'm having a really hard time to understand is if it's ok to use `$localize.locale` or if we are supposed to keep using the injected `LOCALE_ID` since it's never mentioned anywhere.

I think [soluing](https://www.soluling.com/Help/Angular/Index.htm) (no affiliation) has a pretty good doc on a i18n and a few $localize functionalities. But I would prefer an official doc to know what's actually a supported functionality.

**Comment by petebacondarwin** [comment]
`$localize.locale` is only available if you are using runtime translation of $localize. So if you are using compile time inlining of translations then `$localize.localize` will not exist. You should be able to rely upon the `LOCALE_ID` injectable. **The Angular CLI automatically includes the locale data and sets the LOCALE_ID value when you use the --localize option with ng build.**

**Comment by stefan-schweiger** [comment]
@petebacondarwin At least in Angular 10.0 $localzie.locale works during compile time translation as it gets replaced with a string of the locale (e.g. "de").

It's not accessible during runtime with `ng serve` for whatever reason ($localize has a function value), but with `ng build` you can also access it during runtime.

This is what I meant when I said, teh documentation js lacking and the usage is confusing 😅

**Comment by stefan-schweiger** [comment]
@petebacondarwin it's also working with Angular 11 as you can see in this repro https://github.com/stefan-schweiger/angular-localize-test

It doesn't work on stackblitz (I guess they are using different build/serve settings) but when you run it locally via ng serve you get the right values for `$localize.locale` in the .ts files, but it fails in the template files (but even then you can just set it to a property from the code and it works).

**Comment by petebacondarwin** [comment]
> `$localize.locale` works during compile time translation as it gets replaced with a string of the locale (e.g. "de").

Oh yes! I have forgotten that the CLI also does this.

**Comment by petebacondarwin** [comment]
You cannot access any globals in templates (except for `null`) and so it is expected that `{{ $localize.locale }}` would not work. It is not related to `$localize` itself.

**Comment by petebacondarwin** [comment]
You are basically right in your first description of this issue. This whole area is not documented well (or at all).
Hopefully #40317 will begin to resolve this. But we do need to add more to the guides.

**Comment by michaelfaith** [comment]
Would love to have more documentation on this.  Especially handling runtime localization and about building libraries with translations.

**Comment by jessicajaniuk** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
