### ISSUE TITLE
ng debug methods in production build when debugging tools are enabled

### ISSUE THREAD

**Issue by jyothi530** [angular/angular#37565]
# 🚀 feature request
When debug tools are enabled in production build please allow accessing ng debug methods (getComponent, getOwningCompenet, getContext) etc.
### Relevant Package

 This feature request is for @angular/core.

### Description
We recently upgraded to Angular 9. In Angular 6 if we enable debug tools, With ng.probe we are able to access components and it's dependent services. With Angular 9 when we enable debug tools only 'profiler' property is exposed in 'ng' object.

It is not a good practice to have debug tools as production build but at times it comes handy. In some scenarios if a user has an issue, We resolve it by enabling debug tools and fixing the issue. Without having debug tools the user will be blocked until we make a code change release a hotfix which will go through rigorous approval process until then user will be blocked.

I thought of setting 'ngDevMode' variable to true when debug tools are enabled if possible but looking at the source code it is not that simple setting 'ngDevMode' and evrything will work. Looks like the tree shaking is done differently based on whether 'ngDevMode' is enabled or not.

**Comment by villelahdenvuo** [comment]
I also noticed that if "optimization" is set to true in the build, the ng.getComponent method is not exposed. This is a regression since before the debug tools were exposed unless enableProdMode was called. I understand that it makes sense to remove the dev tools from the bundle, but perhaps there could be a way to lazily load them if needed even in production builds.

**Comment by jelbourn** [comment]
While this would certainly be useful, I don't think that there's a practical way for us to accomplish this. As you mentioned, the debugging tools are intentionally stripped in prod mode for performance, and I don't think there would be any way to re-insert them imperatively for debugging.
