### ISSUE TITLE
want to Prevent JitsiMeetExternalAPI reinitializing  when mat-tab switching! 

### ISSUE THREAD

**Issue by amran75** [angular/angular#37573]
<mat-tab label="Conference">
                    <div  class="card-body col-sm-12">
                      <div style="text-align:center">
                        <div id="meet"  #meet></div>
                      </div>
                    </div>
    </mat-tab>
 <mat-tab label="Others" >
 </mat-tab>

here I init my jitsiMeet html code on under a mat-tab element. its works fine. 
but when i move another mat-tab (Others), JitsiMeetExternalAPI turns off the camera as well as connection!
again when i get back my Conference tab it reconnects!

its an angular-6 project.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
