### ISSUE TITLE
Include the injector name in error: Trying to get the Angular injector before bootstrapping the corresponding Angular module

### ISSUE THREAD

**Issue by marianazangrossi** [angular/angular#37579]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/upgrade

### Description
In the project I'm working we are migrating AngularJS to Angular 2+ and we face this error often: `Trying to get the Angular injector before bootstrapping the corresponding Angular module.` It would be very helpful to include the injector name in the error message, it would save a lot of time instead of search each injector until finding the one which is throwing this error.

### Describe the solution you'd like
`Trying to get the Angular injector before bootstrapping the corresponding 'Angular module. Injector name: SomeAngularService.`

**Comment by gkalpak** [comment]
Is this failing for a downgraded injectable (or are there more usecases where this can break)?

From a quick look, I think this error will only be thrown when trying to inject a downgraded injectable (without having loaded the corresponding module).

If that's the case, we could add a `try/catch` block and throw a more descriptive error [here][1].

[1]: https://github.com/angular/angular/blob/62e4acc3d1be412e221b20bdc68618a35ba0c1a8/packages/upgrade/src/common/src/downgrade_injectable.ts#L82

**Comment by marianazangrossi** [comment]
I'm not sure @gkalpak, this use to happen when trying to use an upgraded service in an AngularJS directive/component/controller/service. I think that is what are you meaning, right?

**Comment by gkalpak** [comment]
Oh, that's different. Can you show an example of the failure?
<sub>(You can use [this StackBlitz project][1] as a starting point if it helps.)</sub>

[1]: https://stackblitz.com/edit/ngupgradestatic-playground
