### ISSUE TITLE
Dart build is failing

### ISSUE THREAD

**Issue by vicb** [angular/angular#3757]
See https://travis-ci.org/angular/angular/jobs/76361788#L1052

```
Build error:
Transform InjectorGenerator on benchmarks_external|web/src/naive_infinite_scroll/index.dart threw error: <rethrow>
Caused by The null object does not have a getter 'importsAndExports'.
NoSuchMethodError: method not found: 'importsAndExports'
Receiver: null
Arguments: []
```

This build is the first build where the issue has re-appeared ([previous build](https://travis-ci.org/angular/angular/builds/76352379) is fine)

This issue had already been seen with 1.12-DEV at the e/o june, see #2798

Apparently both the green & red builds use the same Dart version (1.11.3 - print at l 140 on Travis logs).

@kevmoo @sigmundch any idea of what could go wrong ?

**Comment by sigmundch** [comment]
cc @kegluneq 

I honestly don't know. I don't think it is necessarily an sdk issue, it could also be an issue introduced in the analyzer package or a flaky behavior, for example a race condition in the order in which some files are processed.

The stacktrace seems to come from the resolver part of the analyzer package:
```
#0      AnalysisTask._safelyPerform (package:analyzer/src/generated/engine.dart:6434:7)
#1      AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6403:7)
```

IIRC correctly the angular2 transformer doesn't use this. Is this issue with the angular1 transformers?

**Comment by vicb** [comment]
@sigmundch you are right "benchmarks_external" contains Angular1 apps.

**Comment by btford** [comment]
@yjbanov and I looked a bit. @yjbanov suspects the issue is in some pub dependency, most likely code_transformers or analyzer.

**Comment by sigmundch** [comment]
I recall a recent change in code_transformers that had a bad lower bound on analyzer, I believe that a new version has already been released (@jakemac can confirm)

**Comment by yjbanov** [comment]
I think the version constraints on `code_transformers` and `analyzer` in https://github.com/angular/angular.dart/blob/master/pubspec.yaml are somehow busted with the latest release of `code_transformers`. @jakemac53 or @sigmundch, do you know what the version constraints should be?

**Comment by jakemac53** [comment]
0.2.9+1 of code_transformers was a bad version (it should have had a lower
bound of 0.26.0 for analyzer). The new version(s) should fix it.

**Comment by yjbanov** [comment]
@jakemac53 does this mean that _no_ change in https://github.com/angular/angular.dart/blob/master/pubspec.yaml is necessary?

**Comment by jakemac53** [comment]
Yes, that should be the case.

**Comment by yjbanov** [comment]
Fixed
