### ISSUE TITLE
Android bottom navigation bar overlay content in pwa when set as home screen

### ISSUE THREAD

**Issue by tahir-jamil** [angular/angular#37589]
Hi i am using pwa with angular and my list content just overlay when android navigations are shown how can i fix this problem please suggest me any solution for that 
Thanks in advanced
This is how it looks like with my angular material navBar
![Screenshot_20200615-171447](https://user-images.githubusercontent.com/40952630/84656623-6966fb80-af2c-11ea-83fc-9f4553f2c31d.png)

In this image navigation icons are shown and overlay my content
![Screenshot_20200615-171451](https://user-images.githubusercontent.com/40952630/84656746-9ddab780-af2c-11ea-865c-8ea07142a523.png)

And Finally this is how it should work that i wish in the chrome tab 
![Screenshot_20200615-171502](https://user-images.githubusercontent.com/40952630/84656782-adf29700-af2c-11ea-9c6d-8a6a176d9cca.png)

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
