### ISSUE TITLE
[error] Error: Job name "..getProjectMetadata" does not exist.

### ISSUE THREAD

**Issue by jusfeel** [angular/angular#37584]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
@angular-devkit/build-angular": "^0.901.8"

### Is this a regression?

no
 Yes, the previous version in which this bug was not present was: ....
@angular-devkit/build-angular": "^0.803.26"

### Description

 A clear and concise description of the problem...
After "npm audit fix". I cannot start the development console. Check package.json, there it is:
-    "@angular-devkit/build-angular": "^0.803.26",
+    "@angular-devkit/build-angular": "^0.901.8",

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.17
Node: 12.16.3
OS: linux x64
Angular: 8.2.13
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.17
@angular-devkit/build-angular     0.803.27
@angular-devkit/build-optimizer   0.803.27
@angular-devkit/build-webpack     0.803.27
@angular-devkit/core              8.3.17
@angular-devkit/schematics        8.3.17
@angular/cli                      8.3.17
@angular/compiler-cli             8.2.14
@ngtools/webpack                  8.3.27
@schematics/angular               8.3.17
@schematics/update                0.803.17
rxjs                              6.5.5
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

no

ubuntu20.4

**Comment by JoostK** [comment]
Heya, `@angular-devkit/build-angular` ~0.900 requires Angular 9, so using it with Angular 8 is not supported (and will cause errors like this)
