### ISSUE TITLE
app not initializing with prod build after converting application from angular 8 to angular 9

### ISSUE THREAD

**Issue by chinna510** [angular/angular#37588]
Hi, we have an existing application with angular 8. so now we are converting our existing application from angular 8 to angular 9. we have faced some issues while converting but all those errors got solved. we are not facing any issues with dev build but problem with production build. prod build was successful but while opening the application angular app is not initializing.
i have asked in
[stackoverflow](https://stackoverflow.com/questions/62381891/app-not-initializing-with-prod-build-after-converting-application-from-angular-8?noredirect=1#comment110328011_62381891)

please can any one help me to resolve this issue.
Thanks.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
