### ISSUE TITLE
Aync pipe + optional chaining reevalutate unrelated inputs

### ISSUE THREAD

**Issue by mistic100** [angular/angular#37591]
# 🐞 bug report

### Affected Package
@angular/*** 9.1.9

### Is this a regression?

Probably

#### Prerequisite :
Create a component with two `@Input`, one of them is a setter method (it propably does not matter but having a method helps to see the problem).
Let's call "value1" the Input using a setter method and "value2" the Input applied directly on a property.

```ts
@Component({
  selector: 'hello',
  template: `
    setValue called {{count}} times<br>
    value1 : {{value1}}<br>
    value2 : {{value2}}
  `,
})
export class HelloComponent  {

  value1: any;
  count = 0;

  @Input('value1')
  set setValue1(value: any) {
    this.value1 = value;
    this.count++;
  }

  @Input() value2: any;

}
``` 

#### Use it :
Use this component in a view with this configuration
- "value1" is a direct binding to a constant
- "value2" uses an Observable + async pipe + optional chaining

```ts
@Component({
  selector: 'my-app',
  template: `
  <hello [value1]="value1" [value2]="(value2$ | async)?.i"></hello>
  `,
})
export class AppComponent  {

  value1 = 'value 1';

  value2$ = timer(1000, 1000)
    .pipe(map(i => ({i})));

}
```

#### What happens :
Everytime "value2" changes, the setter method of "value1" is called, although the value didn't changed.
**If you remove the optional chaining there is no problem.**

After a long debugging session in the change detector I tracked down the problem to this line
https://github.com/angular/angular/blob/master/packages/core/src/render3/pipe.ts#L221
where "bindingToInvalidateIdx" is for some reason the index of "value1" and not "value2". Because of this when the change detector runs for "value1" the old value is "NO_CHANGE" and not the actual value, hence refreshing the input.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-xkcbs1

In the setter of "value1" I increment a counter, this counter is increment when "value2" changes.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
    "@angular/animations": "9.1.9",
    "@angular/common": "9.1.9",
    "@angular/compiler": "9.1.9",
    "@angular/core": "9.1.9",
    "@angular/forms": "9.1.9",
    "@angular/platform-browser": "9.1.9",
    "@angular/platform-browser-dynamic": "9.1.9",
    "@angular/router": "9.1.9",
    "@angular-devkit/build-angular": "0.901.7",
    "@angular/cli": "9.1.7",
    "@angular/compiler-cli": "9.1.9",
</code></pre>

**Comment by destus90** [comment]
Duplicate of https://github.com/angular/angular/issues/37194#issuecomment-634229827

**Comment by pkozlowski-opensource** [comment]
This one sounds very similar to #37194

**Comment by mistic100** [comment]
It is, hoping for a fix in next release.
