### ISSUE TITLE
Use data- for attribute of component

### ISSUE THREAD

**Issue by samshay** [angular/angular#37592]
Hi,

I have a different comportment with the same component between angular 7 and angular 9.

The Component :
```

@Component({
  selector: 'hello',
  template: `<h1>Hello {{name}}!</h1>`,
  styles: [`h1 { font-family: Lato; }`]
})
export class HelloComponent  {
  @Input() name: string;
}

```
Html who i use the component :
`
<hello **data-name**="Dark Vador Angular 9"></hello>`

With angular 7, it work, angular get the attibute name.
In angular 9, it's not work, angular 9 can't get the attribute.

Of course, if i delete prefix data-, all is work.

But i want to know if it a bug or break change ...

Two stackblitz for test ( i have test with angular-cli, the same result )
Angular 7 : https://stackblitz.com/edit/angular-7-master
Angular 9 : https://stackblitz.com/edit/angular-ivy-zan6uc

Thanks a lot.

**Comment by pkozlowski-opensource** [comment]
I can confirm the difference in behaviour between Angular v7 and v9, here are simpler reproduction scenarios:
* v7: https://stackblitz.com/edit/angular-7-master-veja7e?file=src%2Fapp%2Fapp.component.ts
* v9: https://stackblitz.com/edit/angular-tglrto?file=package.json

While there is a difference in the behaviour I think that the long term idea is to drop special behaviour of data- prefix given the discussion in #26406.

My take on this is that we should consider this ticket alongside with #26406 and rationalise data- handling
