### ISSUE TITLE
Angular Console reference in the documentation

### ISSUE THREAD

**Issue by Windvis** [angular/angular#37604]
# 📚 Docs or angular.io bug report

### Description

I noticed the "Try It" deployment documentation links to **Angular Console** but it seems that website no longer exists. I did some searching and it looks like Angular Console [has been superseded by NX Console](https://blog.nrwl.io/re-introducing-nx-console-a21fa9f4f668). Should the documentation link to that instead? Another option could be to simply remove the link and only keep the Node.js example. Which solution is preferred? I can open a MR later.

### What's the affected URL?**
https://angular.io/start/start-deployment#building-locally

### Reproduction Steps**

Click on the Angular Console link

### Expected vs Actual Behavior**

Clicking on the Angular Console link displays a Firebase "Site not found" message which is confusing for people learning Angular.

**Comment by sonukapoor** [comment]
I think it can be replaced with this one: https://nx.dev/angular/cli/console

**Comment by Windvis** [comment]
Personally I think that dropping the link and only keeping the Node.js example would be a better solution. I took a quick glance at the NX website and it looks like an awesome tool but I think it solves issues that people who are new to Angular won't have run into yet. At that point in the tutorial you just want to run your StackBlitz app locally and the Node.js example seems like a easier solution to me.

I'm also new to the Angular world. Is NX widely used? If it is, there may be better places to recommend its usage?

**Comment by sonukapoor** [comment]
I think that makes sense. The only reason it is mentioned there is to serve the app, which can be done easily via the angular cli.

**Comment by gkalpak** [comment]
I think in the past "Angular Console" was just a UI for the Angular CLI, but now "Nx Console" is more of a UI for the Nx cli (which may use the Angular CLI under the hood, but is more than that).

So, I agree that it is confusing to mention "Nx Console" at this point. Also, "Nx Console" is now a VSCode extension (not a standalone app as "Angular Console" used to be when it was introduced), so should not assume that everyone is (or wants to be) using VS Code for development.

##
BTW, whatever we decide to do, we should update all mentions of "Angular Console.

As mentioned in #37609, there is one more in https://angular.io/cli#cli-overview-and-command-reference.
