### ISSUE TITLE
Using computed property keys in object literals

### ISSUE THREAD

**Issue by mariushilleke** [angular/angular#37606]
# 🚀 feature request

### Description
I would like to use the below code, which is leading to following error message during the build-process:

`{"__symbolic":"error","message":"Expression form not supported", ...}"`

```
const STUDENT_NAME_PROPERTY_KEY = "name";

export class StudentDto {
    constructor() {
        super();
    }
}

export class StudentBuilder {
    static createDefault(): StudentDto {
        return {
            [STUDENT_NAME_PROPERTY_KEY]: 'default',
        };
    }
}
```

**Comment by JoostK** [comment]
You can do this if compiling the application with Ivy in Angular 9. Any library needs to be compiled with `strictMetadataEmit` set to `false` to allow the error to exist in the ViewEngine metadata, but luckily the Ivy compiler won't use that metadata.

**Comment by JoostK** [comment]
With v12 now allowing libraries to be compiled with the Ivy compiler, this issue has been resolved.
