### ISSUE TITLE
Yet another ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by Booster2ooo** [angular/angular#37605]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core (?)

### Is this a regression?

 I had a similar "flow" in an Angular v8 project and didn't encounter the bug but I'm not sure at all as this bug appeared on a brand new project.

### Description

 When switching a mat-progress bar mode according to a boolean (or by displaying one or another progress bar with *ngIf), the following error pops in the console, either when loading the app or changing route:
```ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'mode: determinate'. Current value: 'mode: indeterminate'.```

(or this one for the *ngIf version:
```ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngIf: false'. Current value: 'ngIf: true'.```
)

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-t7ecan?file=src%2Fapp%2Fprogress-bar-test.html

## 🔥 Exception or Error
<pre><code>

ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'mode: determinate'. Current value: 'mode: indeterminate'.
    at viewDebugError (errors.ts:38)
    at expressionChangedAfterItHasBeenCheckedError (errors.ts:24)
    at checkBindingNoChanges (util.ts:104)
    at checkNoChangesNodeInline (view.ts:485)
    at checkNoChangesNode (view.ts:472)
    at debugCheckNoChangesNode (services.ts:468)
    at debugCheckDirectivesFn (services.ts:396)
    at Object.eval [as updateDirectives] (VM28592 ProgressBarTest.ngfactory.js:47)
    at Object.debugUpdateDirectives [as updateDirectives] (services.ts:388)
    at checkNoChangesView (view.ts:352)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.1.7
Node: 10.16.2
OS: win32 x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.7
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.7
@angular-devkit/schematics        9.1.7
@angular/cdk                      9.2.4
@angular/cli                      9.1.7
@angular/material                 9.2.4
@ngtools/webpack                  9.1.7
@schematics/angular               9.1.7
@schematics/update                0.901.7
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

Maybe it's Material related?

**Comment by Booster2ooo** [comment]
I must admit I don't understand the change verification cycle :'( Just for your info, in my real use case, the loading is triggered by a setter of an @Input(), I just replicated the behavior here by putting the code in ngOnInit(). I assume the underlying problem is the same.

As a "fix", if I just "delay" the loading using a "immediate" setTimeout, the error disapears:

```
    window.setTimeout(() => {
      token = this.loadingService.startLoading();
    }, 0);
```
See [the fork for live example](https://stackblitz.com/edit/angular-t7ecan-kadzc3?file=src%2Fapp%2Fprogress-bar-test.ts)

**Comment by mlc-mlapis** [comment]
@Booster2ooo Sure, if you make it async, you always postpone the execution to another tick.

But your original problem is from 99% a symptom of an inappropriate logic in your code. Simply you shouldn't make the change during one CD cycle - when the component and its childs are checked.

**Comment by Booster2ooo** [comment]
Sorry for opening this issue as a bug report. It's only a bad understanding of the CD cycle on my part. Thank you all for your help.
