### ISSUE TITLE
Move code in shims_for_IE.js to third_party directory

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#37615]
Any vendor third_party code should all live in `third_party`. The shims_for_IE.js file contains vendor code that predates the `third_party` directory. This file is currently used for internal karma testing setup.

**Comment by jelbourn** [comment]
@josephperrott does this fall into your department?

**Comment by josephperrott** [comment]
@jelbourn Yep, will make the change

**Comment by AndrewKushnir** [comment]
Closing this ticket since the corresponding change has landed in #37624. Thank you.
