### ISSUE TITLE
angular项目在chrome 49.0.2623.112版本中无法运行，在更低的38或者最新版本运行正常

### ISSUE THREAD

**Issue by alone-fool** [angular/angular#37616]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
引入的依赖
"dependencies": {
    "@angular/animations": "8.2.14",
    "@angular/cdk": "8.2.3",
    "@angular/common": "8.2.14",
    "@angular/compiler": "8.2.14",
    "@angular/core": "8.2.14",
    "@angular/forms": "8.2.14",
    "@angular/platform-browser": "8.2.14",
    "@angular/platform-browser-dynamic": "8.2.14",
    "@angular/router": "8.2.14",
    "@types/lodash": "4.14.91",
    "bootstrap-contextmenu": "1.0.0",
    "bootstrap-daterangepicker": "2.1.30",
    "classlist.js": "1.1.20150312",
    "core-js": "2.5.3",
    "crypto-js": "3.1.9-1",
    "echarts": "3.8.5",
    "intl": "1.2.5",
    "jquery": "3.2.1",
    "jquery-confirm": "3.3.2",
    "jquery-slimscroll": "1.3.8",
    "lodash": "4.17.4",
    "moment": "2.20.1",
    "ng-select": "1.0.0-rc.3",
    "ng2-file-upload": "1.3.0",
    "ng2-pdf-viewer": "2.0.2",
    "ng2-tree": "2.0.0-rc.9",
    "ngx-bootstrap": "2.0.0-rc.0",
    "ngx-contextmenu": "4.1.2",
    "ngx-toastr": "8.0.0",
    "primeicons": "1.0.0-beta.10",
    "primeng": "6.1.2",
    "rxjs": "6.5.3",
    "rxjs-compat": "6.0.0-rc.0",
    "store": "2.0.12",
    "tslib": "1.10.0",
    "wangeditor": "3.1.1",
    "web-animations-js": "2.3.2",
    "zone.js": "0.10.2"
  },

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by JoostK** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
