### ISSUE TITLE
xi18n Support for Cleaning Unused Strings

### ISSUE THREAD

**Issue by SethFalco** [angular/angular#37617]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/localize

### Description
 When a string is updated, and `xi18n` is performed, it only affects the target language to export, but doesn't touch any of the other language files in the repository. 

### Describe the solution you'd like
 Could an argument be added to remove all strings from other language files that have now been made redundant? For example, if I change or remove a string and it's ID no longer exists in the primary language, it should automatically be removed from all other languages.

**Comment by petebacondarwin** [comment]
For the moment the `xi18n` tooling is only going to focus on generating the messages found in the source code. What you do with that extracted data is out of scope for us right now. There are already some tools in the market that are designed to help manage translation of extracted messages. For example https://github.com/martinroob/ngx-i18nsupport/tree/master/projects/xliffmerge comes to mind. I am sure that there are others.

So I won't close this feature request for now, but I wanted to set expectation on what is likely to be provided by the core Angular framework.

**Comment by petebacondarwin** [comment]
Actually, there are no plans to provide tooling to support merging/updating translated translation files. So I am going to close this. There are various 3rd party tools that can manage changes to the translation files.
