### ISSUE TITLE
Flaky `test_aio` and `test_aio_local` CircleCI jobs

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#37629]
The `test_aio` and `test_aio_local` CircleCI jobs started to be quite flaky recently (~50% of attempts results in false-positive failures). Example of the recent failure [can be found here](https://app.circleci.com/pipelines/github/angular/angular/17212/workflows/05430fc4-f921-42f6-9e94-643c6b6d2bff/jobs/741612/steps). It looks like the same tests produce flaky results:

```
Chrome Headless 83.0.4103.0 (Linux x86_64) DocViewerComponent #render() (swapping views) should unsubscribe from the previous "swap" observable when unsubscribed from FAILED
 ```

and

```
Chrome Headless 83.0.4103.0 (Linux x86_64) DocViewerComponent #render() (embedding components) should unsubscribe from the previous "embed" observable when unsubscribed from FAILED
```

CC @gkalpak

**Comment by petebacondarwin** [comment]
This looks like a timing issue with Angular elements. Perhaps the un-subscription is happening async??

**Comment by gkalpak** [comment]
I don't think Angular Elements are at play here. The subscription is happening sync afaict.

We are probably checking the wrong unsubscribe spy. (If I had to guess, I would say it is somehow related to how we use RxJS' `asap` scheduler.) 👀

**Comment by gkalpak** [comment]
Unfortunately, I haven't been able to find the root cause (after several hours of investigating). See #37637 for some more info.

I have submitted #37673 to disable these tests for now.

**Comment by AndrewKushnir** [comment]
Thanks for the investigation and disabling flaky tests @gkalpak 👍
