### ISSUE TITLE
Does  i18n angular app need to be builded for each of the suported language?  

### ISSUE THREAD

**Issue by hegedis-andor** [angular/angular#37634]
# 📚 Docs or angular.io bug report

### Description

In the doc at the i18n section, the bottom of the page shows a tutorial where an example application is built for all the supported languages. I have read from @ocombe in the ngx-translate repo, that in the version 9 of the angular, apps wont be needed to be built for each translation.

Is the doc is waiting for an update about it, or it not yet implemented for the current version of angular?

### What's the affected URL?**
 https://angular.io/...

https://angular.io/guide/i18n#deployment-for-multiple-locales

### Reproduction Steps**

non 

### Expected vs Actual Behavior**

Update of doc?

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by petebacondarwin** [comment]
@hegedis-andor - the difference between the new Ivy translation tooling and the old ViewEngine translation tooling, is that previously the translations happened within the Angular template compilation, so the full build of the application had to happen for each locale. Now the translation is applied to the distributable files, so the full build only needs to happen once, and then a copy of the app is generated for each locale from the distributable files.

So to be clear: the build of the app itself only needs to happen once, but there is still a step that makes a translated copy of each app for each locale.

There is an update to the i18n guide about to land, https://github.com/angular/angular/pull/36924. But I believe that the current guide and this update are both accurate with regards to the build pipeline.
