### ISSUE TITLE
docs(security): add useful guidance to the CSP section of the guide

### ISSUE THREAD

**Issue by Splaktar** [angular/angular#37631]
# 📚 Docs or angular.io bug report

### Description
In the Security Guide for Angular, the section on Content Security Policy (CSP) provides no useful guidance or information on the specific requirements, impediments, or issues related to using a CSP with an Angular application.

### What's the affected URL?**
https://angular.io/guide/security#content-security-policy

### Reproduction Steps**
This is the entire guide for using Angular with a Content Security Policy (CSP):

---

## Content security policy

Content Security Policy (CSP) is a defense-in-depth technique to prevent XSS. To enable CSP, configure your web server to return an appropriate Content-Security-Policy HTTP header. Read more about content security policy at [An Introduction to Content Security Policy](http://www.html5rocks.com/en/tutorials/security/content-security-policy/) on the HTML5Rocks website.

---

### Expected vs Actual Behavior**

We should clearly state some of the known limitations and configurations for using Angular with a CSP.

Here are some related, known issues that have been around for 1-4 years now

1. ~~[[innerHTML] triggers CSP alert/report](https://github.com/angular/angular/issues/25214)~~
1. [Inline <style> elements violate style-src Content Security Policy](https://github.com/angular/angular/issues/6361)
1. [feat: add a customizable nonce attribute for injected style elements](https://github.com/angular/angular/issues/26152)
1. [Empty style tag generated when one or more components don't have styles](https://github.com/angular/angular/issues/31191)

## Suggested Steps

1. We should clearly state that allowing `'unsafe-inline'` in `style-src` is required for Angular applications.
1. We should clearly state that `'self'` is required for `style-src` and `script-src` in Angular applications.
1. We should recommend `upgrade-insecure-requests`.
1. We should document that `connect-src` must be configured with `'self'` and any other font, script, or style sources that are retrieved by `@angular/service-worker`.

If there are some little-known work arounds for any of these issues, they should be documented in this guide.

### Browser info
Chrome 85

### Anything else relevant?
[WebPageTest.org](https://webpagetest.org/) now gives web sites/apps a security grade based on a scan by [Snyk](https://snyk.io/).

https://angular.io/guide/security#content-security-policy gets the following score

![Screen Shot 2020-06-18 at 12 28 10 AM](https://user-images.githubusercontent.com/3506071/84978392-c6181100-b0fa-11ea-9182-74de8ed6bd48.png)

![Screen Shot 2020-06-18 at 12 29 15 AM](https://user-images.githubusercontent.com/3506071/84978402-cadcc500-b0fa-11ea-9fb0-6f6e39a16eba.png)

**Comment by gautamsingal** [comment]
@Splaktar Can I pick this up?

**Comment by Splaktar** [comment]
@gautamsingal thank you for volunteering to help with this. Ideally, I would like to get some discussion going here.

I am curious if others have additional best practices or recommendations.

Of course, some of that discussion could happen in a PR as well.

**Comment by dsm0880** [comment]
@gautamsingal @Splaktar Just came across this. Just wanted to give an up vote. In the guidance I would highly recommend ensuring people utilize the report-only at first. In addition what would be interesting is looking at this from an attacker perspective. I know Angular does do some sanitization, but how does CSP help with other vulnerabilities? The explanations help us devs talk with Stakeholders who will typically just want to know "are you secure or not." On top of this high level question, these scoring websites that give you A,B,C,D... are very attractive to them (accurate or not). When the CSP header requires style-src unsafe we need to come up with a good explanation. Going through implementation of CSP on my site now, if I find anything interesting will post.

**Comment by gautamsingal** [comment]
Thanks @dsm0880 for the feedback.

**Comment by jyotitushir** [comment]
Similar issue is being faced in our application. Our angular7 application is not working without unsafe-inline with 'style-src'. 
Our security team is not allowing to have unsafe inline values in CSP..
Is there a work around for this? or by when can we expect a fix from angular.

**Comment by jyotitushir** [comment]
Any update on this?

**Comment by anno1985** [comment]
Some [Google Security Engineers are pushing CSP +nonces quite a bit (instead of whitelists)](https://www.youtube.com/watch?v=_L06HetskC4&feature=youtu.be&t=674), so maybe also add a note about if/how that works ([re webpack's `__webpack_nonce__`](https://webpack.js.org/guides/csp/))? And maybe add a link to the [cli docs](https://angular.io/cli/build#options) that mention that it supports [SRI (subresource integrity hashes)](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) with [an explanation what that does](https://izifortune.com/angular-subresource-integrity/) (and maybe that you can also [send hashes instead of nonces in CSP headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Syntax))...

**Comment by Splaktar** [comment]
> Similar issue is being faced in our application. Our angular7 application is not working without unsafe-inline with 'style-src'.
> Our security team is not allowing to have unsafe inline values in CSP..
> Is there a work around for this? or by when can we expect a fix from angular.

This issue is about updating the documentation. The issue you are seeing appears to be https://github.com/angular/angular/issues/6361. In that issue, there is a workaround, but multiple people report that it is not effective. I don't believe that there is a workaround that has been verified to work.

The Angular team doesn't give ETAs on features or bug fixes. So I would advise that you do not make business decisions based on the hope that something changes/gets fixed in the future. Note that the issue has been known and unfixed for 4 years now.

That said, your mention of a security team blocking deployment based on CSP violations should help to increase the priority of https://github.com/angular/angular/issues/6361 (if you post the details in that issue).

**Comment by AElmoznino** [comment]
Having very little knowledge of CSP and understanding it's implications, I find the documentation hard to read and implement.
IMO it should be either secure by default, or super easy to implement. I can't find any simple guide/docs on how to implement a nonce or hash for the inline styles.
I face the same problem as @jyotitushir - our security team not allowing to have unsafe inline values in CSP.

**Comment by Splaktar** [comment]
An update to this:
- [[innerHTML] triggers CSP alert/report](https://github.com/angular/angular/issues/25214) was fixed in `v10.1.0` via https://github.com/angular/angular/commit/b950d4675fb76611ee1b9af4eb35db15c46aacf0
  - However, I don't think that there was any associated documentation update related to that work.

**Comment by Splaktar** [comment]
More updates!

There is a lot of discussion on https://github.com/angular/angular-cli/issues/21711 (Feature Request : Add Support for Strict Content Security Policy).

Also there's an open PR https://github.com/angular/angular/pull/43553 to start to make the Angular CSP docs a little more useful.

**Comment by bob-watson** [comment]
It's hard to tell what remains to be done on this.
I'm closing it out, but if there's more to do, reopen it and describe the remaining work, please.
