### ISSUE TITLE
Input value is an empty string in Jasmine Tests using an combined element, attribute Component Selector

### ISSUE THREAD

**Issue by riede** [angular/angular#37646]
# 🐞 bug report

### Description

 
I've got a component with some [inputs](https://angular.io/api/core/Input). Some of them are optional but the input `config` is required to use the component. Therefore I defined a component selector that has an element part and an attribute part (e.g. `app-my-component[config]`). Now I always need to pass a config into the component if I want to use it. Great! I started the app with `ng serve` and everything works fine. So far so good...

While writing the component tests I'm coming in trouble. I set the config in the `beforeEach` block where the component fixture is also created. However the required input attribute `config` is always an empty string when I called `fixture.detectChanges()`.

Here is the Test-File of the [minimal Reproduction](https://github.com/riede/component-with-element-and-attribute-selector) I wrote that shows exactly the behaviour.

```ts
describe('TestComponent', () => {
  let component: TestComponent;
  let fixture: ComponentFixture<TestComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ TestComponent ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(TestComponent);
    component = fixture.componentInstance;
    component.requiredInput = { anyKey: 'anyValue'};
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it('should not fail', () => {
    const expectedResult: RequiredInput = { anyKey: 'anyValue' };
    expect(component.requiredInput).toEqual(expectedResult); // <-- this expectation fails
  });
});
```

Removing the attribute part of the selector solves the problem. But that is no way.

## 🔬 Minimal Reproduction

I've created a minimal [GitHub repository](https://github.com/riede/component-with-element-and-attribute-selector) with the reproduction of the issue. I used Angular 8 for the reproduction repository because my main project is still using Angular 8, too

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.26
Node: 10.19.0
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.26
@angular-devkit/build-angular      0.803.26
@angular-devkit/build-ng-packagr   0.803.26
@angular-devkit/build-optimizer    0.803.26
@angular-devkit/build-webpack      0.803.26
@angular-devkit/core               8.3.26
@angular-devkit/schematics         8.3.26
@angular/cli                       8.3.26
@ngtools/webpack                   8.3.26
@schematics/angular                8.3.26
@schematics/update                 0.803.26
ng-packagr                         5.7.1
rxjs                               6.5.5
typescript                         3.5.3
webpack                            4.39.2

</code></pre>

**Comment by jnizet** [comment]
Not sure if it's a bug or a feature (I'll let better specialists decide about that).

But the typical way of testing a component that requires inputs is to actually pass inputs the way they're supposed to be passed, with a test such as this one:

```
import { async, ComponentFixture, TestBed } from '@angular/core/testing';

import { TestComponent, RequiredInput } from './test.component';
import { Component } from '@angular/core';
import { By } from '@angular/platform-browser';

@Component({
  template: '<app-test [requiredInput]="input"></app-test>'
})
class FixtureComponent {
  input!: RequiredInput;
}

describe('TestComponent', () => {
  let fixtureComponent: FixtureComponent;
  let component: TestComponent;
  let fixture: ComponentFixture<FixtureComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ TestComponent, FixtureComponent ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(FixtureComponent);
    fixtureComponent = fixture.componentInstance;
    component = fixture.debugElement.query(By.directive(TestComponent)).componentInstance;
    fixtureComponent.input = { anyKey: 'anyValue'};
    fixture.detectChanges();
  });

  it('should not fail', () => {
    const expectedResult: RequiredInput = { anyKey: 'anyValue' };
    expect(component.requiredInput).toEqual(expectedResult);
  });
});
```

**Comment by riede** [comment]
> Not sure if it's a bug or a feature (I'll let better specialists decide about that).
> 
> But the typical way of testing a component that requires inputs is to actually pass inputs the way they're supposed to be passed, with a test such as this one:

This "workaround" works for me. Thanks! 

I think the main problem (I described) is that the component is created by the TestBed without any parent that gives the input into the component itself. So it could be a way to pass an argument object while creating the component fixture - e.g.:

```typescript
beforeEach(() => {
    fixture = TestBed.createComponent(TestComponent, {
        requiredInput: { anyKey: 'anyValue'}
    });
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

```
In this case each attribute represents a value the TestBed sets to the same named input of the component.
