### ISSUE TITLE
let's write in one language

### ISSUE THREAD

**Issue by koshpendi** [angular/angular#37649]
I wish the component has a function that returns template
as build in the Flutter
as render in the React

and please add support for functional components like in react and flutter as well

**Comment by amitport** [comment]
The sentiment is understandable. It would have been nice to have a killer OS/programming language/paradigm/architecture that always fits all, _but_, almost surely the way to get there (IF possible) is not about _choosing_ an approach, it is about research, experimentation, practical experience, and survival of the fittest (and this github issue isn't helping any of that).
