### ISSUE TITLE
`processNewMacroTasksSynchronously: false` does not work well with rxjs' timer and interval functions

### ISSUE THREAD

**Issue by artaommahe** [angular/angular#37653]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/angular/core/testing

### Is this a regression?

No

### Description

Using `tick(0, { processNewMacroTasksSynchronously: false })` with rxjs' `timer` and `interval` does not worked as expected.

## 🔬 Minimal Reproduction

Example with timer, callback never been called

```ts
it('with timer', fakeAsync(() => {
  const callback = jasmine.createSpy('callback');

  timer(0, 0).pipe(skip(1), take(1)).subscribe(callback);

  expect(callback).not.toHaveBeenCalled();

  tick(undefined, { processNewMacroTasksSynchronously: false });

  expect(callback).not.toHaveBeenCalled();

  tick(undefined, { processNewMacroTasksSynchronously: false });

  expect(callback).toHaveBeenCalledTimes(1);
}));
```

Same with interval, code in test file.
Repo with this test

- `git clone git@github.com:artaommahe/tick-with-timer-and-interval.git`
- `yarn install`
- `yarn test`

[test file](https://github.com/artaommahe/tick-with-timer-and-interval/blob/master/src/app/tickWithTimerAndInterval.spec.ts)

Even using `tick()` does not work here.

## 🔥 Exception or Error
<pre><code>
Chrome 83.0.4103.106 (Windows 10) tickWithTimerAndInterval with timer FAILED
        Error: Expected spy callback to have been called once. It was called 0 times.
            at <Jasmine>
            at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/app/tickWithTimerAndInterval.spec.ts:24:22)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.0-rc.5
Node: 12.18.1
OS: win32 x64

Angular: 10.0.0-rc.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0-rc.5
@angular-devkit/build-angular     0.1000.0-rc.5
@angular-devkit/build-optimizer   0.1000.0-rc.5
@angular-devkit/build-webpack     0.1000.0-rc.5
@angular-devkit/core              10.0.0-rc.5
@angular-devkit/schematics        10.0.0-rc.5
@angular/cli                      10.0.0-rc.5
@ngtools/webpack                  10.0.0-rc.5
@schematics/angular               10.0.0-rc.5
@schematics/update                0.1000.0-rc.5
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0
</code></pre>

**Anything else relevant?**

Same case works well with jest fake timers

```ts
const callback = jest.fn();
jest.useFakeTimers();

timer(0, 0).pipe(skip(1), take(1)).subscribe(callback);

expect(callback).not.toHaveBeenCalled();

jest.runOnlyPendingTimers();

expect(callback).not.toHaveBeenCalled();

jest.runOnlyPendingTimers();

expect(callback).toBeCalledTimes(1);
```

**Comment by JiaLiPassion** [comment]
@artaommahe, I am not sure I understand your test case. Your case has nothing to do with `processNewMacroTasksSynchronously` option since there are no nested timeout.

I added comment in your test code about my understanding.

```
it('with timer', fakeAsync(() => {
  const callback = jasmine.createSpy('callback');

  timer(0, 0).pipe(skip(1), take(1)).subscribe(callback);

  // not tick, so not called
  expect(callback).not.toHaveBeenCalled();

  tick(undefined, { processNewMacroTasksSynchronously: false });
  
  // tick, and timer triggered, then `skip(1)` will just skip the value
  // and the callback still not being called.
  expect(callback).not.toHaveBeenCalled();

  tick(undefined, { processNewMacroTasksSynchronously: false });
  
  // tick again, and `take(1)` got the value and trigger the `spy` callback
  expect(callback).toHaveBeenCalledTimes(1);
}));
```

I am not sure why `jest` get the other result, but in my opinion, the current result is correct.

**Comment by artaommahe** [comment]
oh, you're right, this is not about nested timeouts 😕 this code does not work right even with regular `tick()` call

```
  // tick again, and `take(1)` got the value and trigger the `spy` callback
  expect(callback).toHaveBeenCalledTimes(1);
```
and it does not get the value, that's the problem

**Comment by artaommahe** [comment]
i've update code in the repo, removed `processNewMacroTasksSynchronously` usage. Same problem - callback is never been called

**Comment by JiaLiPassion** [comment]
@artaommahe, the reason is here 
```
  timer(0, 0).pipe(skip(1), take(1)).subscribe(callback);

```

the 2nd parameter of `timer(0, 0)` should be `period`, even you pass `0`, rxjs will use the default value `1`, so there is no `zero` period things.

so your test code should be 

```
it('with timer', fakeAsync(() => {
  const callback = jasmine.createSpy('callback');

  timer(0, 0).pipe(skip(1), take(1)).subscribe(callback);

  // not tick, so not called
  expect(callback).not.toHaveBeenCalled();

  tick();
  
  // tick, and timer triggered, then `skip(1)` will just skip the value
  // and the callback still not being called.
  expect(callback).not.toHaveBeenCalled();

  tick(1);
  
  // tick again, and `take(1)` got the value and trigger the `spy` callback
  expect(callback).toHaveBeenCalledTimes(1);
}));
```

**Comment by artaommahe** [comment]
O_o so it works with `jest.runOnlyPendingTimers()` cause this call just runs all current timers despite their duration..

Looked again at the interval case and it fails differently
```ts
interval(0).pipe(skip(1), take(1)).subscribe(callback);

tick();

expect(callback).not.toHaveBeenCalled();
```
will produce an error
```
Error: Expected spy callback not to have been called.
```

that's 'by design' too?)

**Comment by JiaLiPassion** [comment]
yes, just like you said, `jest.runOnlyPendingTimers()` is different with `tick(x, {processNewMacroTAsksSynchronously: false})`, since tick has a `advancedTime` parameter.

And `interval(0)` behave differently with `timer(0,0)` since `setInterval` allow to pass an `zero` interval. So when you `tick`, the `interval` will be triggered twice and cause `skip` and `take` to be triggered too.

And also, here use `processNewMacroTasksSynchronously: false` will not work either since `fakeAsync` will always handle `interval` calls in the current tick.
So if you have some use case need this case work as `spy not called`, please tell me and we can discuss about it.

Thanks.
