### ISSUE TITLE
Currency pipe - display parameter, mistake in documentation

### ISSUE THREAD

**Issue by svendjanis** [angular/angular#37663]
# 📚 Docs or angular.io bug report

### Description

 Currency pipe - display parameter

### Expected vs Actual Behavior**
symbol(default): Show the symbol (such as $).

symbol-narrow: Use the narrow symbol for locales that have two symbols for their currency. For example, the Canadian dollar CAD has the symbol CA$ and the symbol-narrow $. If the locale has no narrow symbol, uses the standard symbol for the locale.

Symbol and symbol-narrow descriptions are mixed. Symbol shows CA$ and symbol-narrow shows $.

## 📷Screenshot
![image](https://user-images.githubusercontent.com/42269262/85275846-36b78880-b481-11ea-87ad-418fc7b4cc1d.png)

![image](https://user-images.githubusercontent.com/42269262/85276502-31a70900-b482-11ea-828d-556c17d6e432.png)

### Browser info
Google Chrome

**Comment by petebacondarwin** [comment]
Hi @svendjanis - I don't understand what is wrong here. Perhaps the confusion is that the `USD` currency code has the same output for both `symbol` and `symbol-narrow`:

```
{{price | currency : 'USD' : 'symbol'}}
{{price | currency : 'USD' : 'symbol-narrow'}}
```

```
$2.00
$2.00
```

In the case of `CAD` the symbol is `CA$` whereas the  narrow symbol is `$`:

```
{{price | currency : 'CAD' : 'symbol'}}
{{price | currency : 'CAD' : 'symbol-narrow'}}
```

```
CA$2.00
$2.00
```

This is what is described in the documentation, yes?

**Comment by svendjanis** [comment]
Oh, I see now. I have misread this part For example, the Canadian dollar CAD has the symbol CA$ and the symbol-narrow $. My apologies
