### ISSUE TITLE
Conditional routing is not working in production build, while it works, if Angular is running in the development mode.

### ISSUE THREAD

**Issue by Vatspra** [angular/angular#37664]
# 🐞 bug report

### Affected Package
@angular/router

### Is this a regression?
No, it is not working on an older version also

### Description
 When we add a conditional route on routing.module.ts, it works on development mode, but when we make a production build, it does not work.
eg.
```
app.routing.module.ts
if(someCondition) {
  routes.push(someExtaRoute)
}

```
this line works on development mode but does not work on a production build.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.1.3
Node: 10.16.0
OS: Linux x64
Angular: 8.1.3

</code></pre>

**Anything else relevant?**
This issue is relevant to older versions also like Angular 5.2.9

**Comment by JoostK** [comment]
Please share a minimum reproduction, e.g. a Github repo.

My guess is that this is done as a side effect in a module, which is dropped in production builds. Try setting `"sideEffects": true` in your package.json.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
