### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Javaman2** [angular/angular#37661]
# 🐞 bug report

### Affected Package

packages/core/src/linker/ng_module_factory_registration.ts
```typescript
export function registerNgModuleType(ngModuleType: NgModuleType) {
 // If id emod is undefined an error is thrown.
 if (ngModuleType.ɵmod.id !== null) {
 ```
### Is this a regression?

No

### Description

This line: 
```typescript
ngModuleType.ɵmod.id !== null
``` 
Results in this: 
```typescript
Uncaught TypeError: Cannot read property 'id' of undefined
    at registerNgModuleType (core.js:36228)
    at core.js:36246
    at Array.forEach (<anonymous>)
    at registerNgModuleType (core.js:36242)
    at core.js:36246
    at Array.forEach (<anonymous>)
    at registerNgModuleType (core.js:36242)
    at new NgModuleFactory$1 (core.js:36407)
    at compileNgModuleFactory__POST_R3__ (core.js:42296)
    at PlatformRef.bootstrapModule (core.js:42663)
```
Would be nice to catch the error and tell the user which module is failing.

This was failing in the MatPaginator module.  It is probably an incorrect import but not sure yet.  

I've written an [article](https://dev.to/jwp/uncaught-typeerror-cannot-read-property-id-of-undefined-5104) on the journey to determine root cause.  

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.8
Node: 12.18.0
OS: win32 x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.8
@angular-devkit/build-angular      0.901.8
@angular-devkit/build-ng-packagr   0.901.8
@angular-devkit/build-optimizer    0.901.8
@angular-devkit/build-webpack      0.901.8
@angular-devkit/core               9.1.8
@angular-devkit/schematics         9.1.8
@angular/cdk                       9.2.4
@angular/cli                       9.1.8
@angular/material                  9.2.4
@ngtools/webpack                   9.1.8
@schematics/angular                9.1.8
@schematics/update                 0.901.8
ng-packagr                         9.1.5
rxjs                               6.5.5
typescript                         3.7.5
webpack                            4.42.0

</code></pre>

**Anything else relevant?**

No

**Comment by petebacondarwin** [comment]
Can you try updating to the most recent versions of Angular and Angular CLI. There have been a number of bug fixes in the last few releases, which might solve this problem.

**Comment by Javaman2** [comment]
Hi Pete..

The library was running at Angular 9 but had to downgrade because Angular 9 libraries are not compatible with Apps, running version 8.  

We had tried to upgrade our app to Angular 9 which was too painful.  We lost two weeks trying to get all dependencies fixed. So we rolled back to 8.  Thats, why I had to downlevel library solution to 8.

I could try again, but to loose another two weeks just to get to 10 may be a stretch.

**Comment by Javaman2** [comment]
Here's the enterprise application configuration:

```
Angular CLI: 8.3.26
Node: 12.18.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.28
@angular-devkit/build-angular     0.803.28
@angular-devkit/build-optimizer   0.803.28
@angular-devkit/build-webpack     0.803.28
@angular-devkit/core              8.3.28
@angular-devkit/schematics        8.3.26
@angular/cdk                      8.2.3
@angular/cli                      8.3.26
@angular/material                 8.2.3
@ngtools/webpack                  8.3.28
@schematics/angular               8.3.26
@schematics/update                0.803.26
rxjs                              6.6.0
typescript                        3.5.3
webpack                           4.43.0
```

**Comment by Javaman2** [comment]
And here's the new downgrade of the library.
```
Angular CLI: 8.3.28
Node: 12.18.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.28
@angular-devkit/build-angular      0.803.28
@angular-devkit/build-ng-packagr   0.803.28
@angular-devkit/build-optimizer    0.803.28
@angular-devkit/build-webpack      0.803.28
@angular-devkit/core               8.3.28
@angular-devkit/schematics         8.3.28
@angular/cdk                       8.2.3
@angular/cli                       8.3.28
@angular/material                  8.2.3
@ngtools/webpack                   8.3.28
@schematics/angular                8.3.28
@schematics/update                 0.803.28
ng-packagr                         5.7.1
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.39.2
```

**Comment by Javaman2** [comment]
I think you are saying go up to 10.0 right?

**Comment by Javaman2** [comment]
Thanks for your help!

**Comment by petebacondarwin** [comment]
Marvellous!! I am really glad we got through this. Thanks for your patience.
