### ISSUE TITLE
Ivy Memory Leak: Select & Option Elements

### ISSUE THREAD

**Issue by Everduin94** [angular/angular#37671]
# 🐞 bug report

### Affected Package

Minimal reproduction uses Angular 9.1.9

### Is this a regression?

This issue does not happen when using View Engine (enableIvy: false)

### Description

When running Angular with Ivy (enableIvy: true), if a select element contains an option element, the HTML select element and it's component will leak.
- If the option element is removed, the select/component will not leak
- When running view engine (enableIvy: false), the select/component will not leak.

![image](https://user-images.githubusercontent.com/14320878/85302013-395cb280-b46e-11ea-90ad-f108e0ef912b.png)

## 🔬 Minimal Reproduction
Example using Ivy (Creates leak): https://angular-ivy-select-mem-leak.stackblitz.io/
Example using View Engine (Does not create leak): https://angular-ve-select-mem-leak.stackblitz.io/

## 🔥 Exception or Error
None

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular/animations9.1.9
@angular/common9.1.9
@angular/compiler9.1.9
@angular/core9.1.9
@angular/forms9.1.9
@angular/platform-browser9.1.9
@angular/platform-browser-dynamic9.1.9
@angular/router9.1.9
rxjs6.5.5
tslib1.13.0
zone.js 0.10.3
</code></pre>

**Anything else relevant?**
Replicated in Chrome: Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by petebacondarwin** [comment]
@Everduin94 can you have a look to see if this is the same problem that has been reported in one of:

* https://github.com/angular/angular/issues/35164
* https://github.com/angular/angular/issues/29053
* https://github.com/angular/angular/issues/36878

**Comment by Everduin94** [comment]
@petebacondarwin 

#35164 seems similar. Although, in that issue it's the ComponentView and EmbeddedView that are leaking. In my reproduction, the native element (HTMLSelect) and the component (LeakComponent) housing the native element are leaking. -- That issue is also using Dynamic Components whereas this is simply a select element in a component template.

**Comment by Kshitij-Banerjee** [comment]
Also seeing the same with  ```  "@angular/animations": "9.1.0",
    "@angular/cdk": "^9.0.0",
    "@angular/common": "9.1.0",
    "@angular/compiler": "9.1.0",
    "@angular/core": "9.1.0",```

**Comment by KimAlexander** [comment]
Any update on this ?

**Comment by JoostK** [comment]
This appears to be a Chrome bug, similar to what was found in #40614.

In VE the same leak occurs, but in VE's case no internal data structures are attached to the DOM elements so only the detached nodes can be found in the heapdump:

<img width="737" alt="Screenshot 2021-02-19 at 20 17 45" src="https://user-images.githubusercontent.com/123679/108551175-dc144c00-72ef-11eb-93b6-ca977668ed13.png">

**Comment by Everduin94** [comment]
@JoostK I don't think that what happens in VE should be considered the same leak, as the consequences are significantly different. -- In Ivy, the component containing the select element is leaked (as well as anything residing inside of that component). In VE, the component containing the select element is not leaked, and thus everything inside of that component that is eligible for GC is garbage collected.

I updated my example to build a large array of data on init in Leak Component:

Ivy:
![image](https://user-images.githubusercontent.com/14320878/108731867-9d9aaf00-74f2-11eb-814a-bbee7a9089fb.png)

VE:
![image](https://user-images.githubusercontent.com/14320878/108731984-c02cc800-74f2-11eb-869b-39bfec826073.png)

Also, from a debugging standpoint. When I check if my component is leaking, I'll search that components name in the memory profiler. Even if the detached elements are leaking in VE due to a chrome bug, I can still confirm that the component itself is not causing the leak. Whereas in Ivy, I can no longer rely on this process (in dev configuration), as this issue may be what's causing the leak and not the component itself.

**Comment by KimAlexander** [comment]
@Everduin94, Do you have this leaking problem in production buil. Seams that i have this problem in production build too

**Comment by JoostK** [comment]
A change was just merged in #41358 which marked #41047 as fixed, but it addresses this issue in the same way. The memory leak itself is still present as that is a Chrome bug, but Angular's internal data structures should no longer be attached to the leaking objects.
