### ISSUE TITLE
If Data-binding an empty Array in template, the state will be retained

### ISSUE THREAD

**Issue by johnDLK** [angular/angular#37687]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Description

 

I binding an empty Array in template as below. And click the ADD button to make some changes. When I click the Rebuild button, app-level-1 component will rebuild(its ngOnInit function will be called). And I expect it always input an empty Array into the sub-component. Actually the binding data will be retained. As a comparison, the the binding data in other two component will be reset.
	
![20200623192341](https://user-images.githubusercontent.com/15192986/85398439-cfd0c700-b587-11ea-979a-669c1ba34ff5.png)

Even if I deepen the level componet, rebuild all of them, the binding data still here, so maybe it stored in the entire angular lifecycle.

I found out how bugs happen：
1.  a component binding an empty Array in template.
2.  push some data into Array.
3. delete the component. (even if delete its grandparent-componet)
4. build a component that is in the same place of Angular tree.

the new component binding a Array as the old component instead of empty Array.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-zkdxh1

## 🔥 Exception or Error
<pre><code>

Nope
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

9.1.11
</code></pre>

**Anything else relevant?**

It happend in Angular 7

**Comment by JoostK** [comment]
This appears to no longer be an issue with Ivy enabled, I suspect since #33705.

**Comment by atscott** [comment]
Confirming that this is not an issue in Ivy: https://stackblitz.com/edit/angular-zkdxh1-5hcfkt?file=src%2Fpolyfills.ts
