### ISSUE TITLE
Forms: consider using `ngDevMode` to tree-shake error messages text in prod mode

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#37697]
In Ivy runtime code, the `ngDevMode` const is used to guard asserts required in dev mode only. We should consider doing the same in Forms package to tree-shake error messages text (which cannot be minified) and some dev mode specific checks. That should help reduce the size of the `forms` package in production mode.

**Comment by sonukapoor** [comment]
@AndrewKushnir I can assist with that.
