### ISSUE TITLE
fix(docs-infra): TS generic parameter defaults are not preserved in API docs

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#37694]
TypeScript generic parameter defaults from source code do not show up in API docs.
For example, `class ElementRef<T = any> { ... }` (from the [source code][1]) appears as `class ElementRef<T> { ... }` in the [API docs][2].

[1]: https://github.com/angular/angular/blob/71c0363bb576ef909d81882f8ec9c69392e05bd0/packages/core/src/linker/element_ref.ts#L27
[2]: https://v9.angular.io/api/core/ElementRef

**Comment by petebacondarwin** [comment]
This is a bug in the `typescript` dgeni package.

**Comment by sonukapoor** [comment]
@gkalpak / @petebacondarwin I will take a look.

**Comment by petebacondarwin** [comment]
To get you started... take a look at this line: https://github.com/angular/dgeni-packages/blob/master/typescript/src/api-doc-types/ClassLikeExportDoc.ts#L33

and then consider this function https://github.com/angular/dgeni-packages/blob/master/typescript/src/services/TsParser/getDeclarationTypeText.ts

**Comment by sonukapoor** [comment]
Thanks for the pointer @petebacondarwin - that helps

**Comment by petebacondarwin** [comment]
Should be fixed by @sonukapoor's PR: https://github.com/angular/dgeni-packages/pull/290

**Comment by ajitsinghkaler** [comment]
@petebacondarwin @gkalpak this issue can be closed I think

**Comment by gkalpak** [comment]
Fixed in #37793.
