### ISSUE TITLE
Angular 7 IE11 View Not Changing when Array Updates works in Chrome/FF - Solution added

### ISSUE THREAD

**Issue by vgc1567** [angular/angular#37693]
I am keeping same title so that any one searches, This is the similar old and closed issue https://github.com/angular/angular/issues/30710 reported and i don't see solution, I got a solution i thought of sharing so that others can benefit.

Issue : Angular 7 IE11 Drop Down View Not Changing when Array Updates works in Chrome/FF.

**Solution:** In .html file just add a `[value]="your variable name"`, 
                in code for Example: `<option *ngFor="let employee of employeeDetails" [value]="employee">{{employee}}</option>
`
Hope this is helpful. Thank you

**Comment by vgc1567** [comment]
@lenichols hope this helps.

**Comment by JoostK** [comment]
Thank you for being helpful!

I will go ahead and close this, as there isn't anything actionable for us.
