### ISSUE TITLE
queryParams and queryParamMap subscription not triggered when param has array with repeating values

### ISSUE THREAD

**Issue by dileepyelleti** [angular/angular#37709]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 No

### Description

 When a query param has array initially containing a repeating value (ex: item: [4, 4, 2]) and after changing the repeating value (item: [4, 3, 2]), queryParams observable or queryParamMap observable is not getting triggered. 

Steps to reproduce:
1. Open https://stackblitz.com/edit/angular-lwjmzk
2. Open console (dev console) in stackblitz.
3. Click on link "Go to parent component with items 4, 4, 2". In console will be displayed message from queryParams and queryParamMap observable handlers.
4. Now click on link "Go to parent component with items 4, 3, 2". Now nothing will be printed in console.
5. But reverse will work fine

Expected: Should trigger queryParams observable handler whenever any value changes in query param

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-lwjmzk 

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.9
Node: 12.1.0
OS: darwin x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.9
@angular-devkit/build-angular     0.901.9
@angular-devkit/build-optimizer   0.901.9
@angular-devkit/build-webpack     0.901.9
@angular-devkit/core              9.1.9
@angular-devkit/schematics        9.1.9
@angular/cdk                      9.2.4
@angular/cli                      9.1.9
@angular/material                 9.2.4
@ngtools/webpack                  9.1.9
@schematics/angular               9.1.9
@schematics/update                0.901.9
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Anything else relevant?**

**Comment by rubenschuckit** [comment]
I wonder if this is intended. I poked around the code and the issue may be the [`equalArraysOrString`](https://github.com/angular/angular/blob/616543ded07d632438185f3df6f3b73591cdaf80/packages/router/src/utils/collection.ts#L46) function that is called to determine if `queryParams` have changed, and if so to emit them.

The function doesn't do an index-by-index comparison. Rather it just makes sure that for each value in the first array, that value exists _anywhere_ in the 2nd array.

So `[4, 4, 2]` -> `[4, 3, 2]` does not emit because 4 and 2 exist in the 2nd array. The other way around works as expected `[4, 3, 2]` -> `[4, 4, 2]` because 3 does not exist in the 2nd array.

**Comment by rubenschuckit** [comment]
On further look, it seems `equalArraysOrString` was [created](https://github.com/angular/angular/commit/828e5c1f79e53202be497fb57aa0b39bc3774300) for query params? In this case, maybe a stricter comparison is in order for this edge case to track frequency and existence in both arrays.

**Comment by Airblader** [comment]
Yeah this strikes me as a bug. It needs to look for the same key/values with the same frequency but ignoring the order. [4, 4, 2] to [4, 3, 2] should be counted as a change for multiple reasons: the frequency of 4 is different and there's a new value 3.

**Comment by charanseeram** [comment]
please unsubscribe my email address

**Comment by Airblader** [comment]
@charanseeram You can click on "Unsubscribe" here on GitHub. Replying to the email only leaves a comment which in turns sends an email to all of us who are also just users.

**Comment by atscott** [comment]
Fixed by #37860
