### ISSUE TITLE
httpTestingController.match doesn't work for multiple requests in a pipe

### ISSUE THREAD

**Issue by amejiarosario** [angular/angular#37714]
# 🐞 bug report

### Affected Package

The issue is caused by package **@angular/common/http/testing**

### Is this a regression?

No

### Description

`httpTestingController.match` doesn't work for multiple requests in a pipeline.

```js
    httpClient.get<Data[]>(testUrl)
      .pipe(
        mergeMap(() => range(0, 2)),
        mergeMap(() => httpClient.get<Data[]>(testUrl)),
      )
      .subscribe(d => expect(d.length).toEqual(0, 'should have no data')); 

    const requests = httpTestingController.match(testUrl);
    console.log({requests}); // <--- why only one instead of 3??

    requests[0].flush([]);
    // requests[1].flush([]); // This is undefined. How do I flush the other two requests?
    // requests[2].flush([]);  // undefined. 

    // Error: Expected no open requests, found 2: GET /data, GET /data
```

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-http-testing2?file=src%2Ftesting%2Fhttp-client.spec.ts

## 🔥 Exception or Error
<pre><code>

Error: Expected no open requests, found 2: GET /data, GET /data
</code></pre>

![image](https://user-images.githubusercontent.com/418605/85624050-4bd61800-b637-11ea-93dc-456defa0ea13.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.6
Node: 10.16.3
OS: darwin x64
Angular: 8.0.1
...

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.803.23
@angular-devkit/build-optimizer   0.803.23
@angular-devkit/build-webpack     0.803.23
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cli                      8.0.6
@angular/compiler-cli             8.0.3
@angular/language-service         8.0.3
@ngtools/webpack                  8.3.23
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

It also happens on angular `9.1.11` as you can see in the `stackblitz`.

**Comment by alxhub** [comment]
The issue is actually in the code triggering the requests:

```typescript
httpClient.get<Data[]>(testUrl)
  .pipe(
    mergeMap(data => range(0, 2)),
    mergeMap(() => httpClient.get<Data[]>(testUrl)),
  )
```

I changed the first call to `mergeMap` slightly to highlight the fact that the argument to the merge function is the data from the first request. The `Observable` sequence described here waits for the first request to finish, _then_ triggers two more based on the results.

So for example, this will work:

```typescript
const firstRequest = httpTestingController.expectOne(testUrl);
firstRequest.flush([]);

const requests = httpTestingController.match(testUrl);
console.log({requests}); // now this will log the second two

requests[0].flush([]);
requests[1].flush([]);
```
