### ISSUE TITLE
d.ts generation should not depend on _

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#3772]
Currently, we have the following three mechanisms for excluding certain types from the d.ts generation:

* private methods/classes are ignored 
* methods starting with _ are ignored
* constructors annotated with @private are ignored

By excluding methods starting with _ we are mixing the privacy semantics of TS and Dart. This creates a lot of problems. For instance,

```
myfile.ts

class A {
  method(b:B) { b._method(); }
}

class B {
  _method():PrivateType{}
}
```

Say I decided to move the class B into a separate file to improve my code organization. Since we compile every file into a separate library, to make it work in Dart I will have to rename `_method` into `method`, which will force me to export PrivateType.

We have this problem because we are mixing the privacy semantics of Dart and TypeScript. Dart has library-scope privacy, TS has class-scoped privacy. The privacy in TS is stricter--a private method in TS is a private method in Dart, but not the other way around. We should only use the TS notion of privacy and do not rely on the presence of _ in any way.

Steps to take:
* We should make @private work for methods.
* We should annotate all public methods starting with _ private.
* We should rename all public methods starting with _ (e.g., _do into do).
* We should change ts2dart to guarantee that all private methods and fields start with _ (this will require some work, so we can do it later.)

The situation we want to end up with:
* We only use TypeScript privacy semantics
* All private methods start with _
* No public methods start with _

@alexeagle @mhevery @rkirov @mprobst

**Comment by mhevery** [comment]
I believe this is obsolete. Closing (reopen if you feel otherwise)

**Comment by alexeagle** [comment]
Well, it's now the case that every method starting with `_` had better also have the `@internal` annotation, or we will output it with the typings. I'll enforce that with https://github.com/angular/angular/issues/4645

It's not clear to me if every one of Victor's steps are effectively taken. For example, there is a setting in ts2dart to enforce the public->no underscore which is currently *off*.

**Comment by alexeagle** [comment]
@vsavkin FYI this is closed, just in case you still have something to say about the subject :)
