### ISSUE TITLE
Build failed after Update (NGCC failed)

### ISSUE THREAD

**Issue by MaTo04** [angular/angular#37729]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9.0.1

### Description

 I followed the instruction on update.angular.io. The update was sucessfull.

## 🔬 Minimal Reproduction
I tried to run "ng b --watch" like in Angular 9.0.1 with the Option "angularCompilerOption": { "enableIvy": true }. The error bellow occure. If i disable Ivy everything works.

## 🔥 Exception or Error
<pre>
Compiling angular-playground : main as esm5
Error: Error on worker angular/angular-cli#1: Error: Compiled class declaration is not inside an IIFE: AppComponent in workspace/node_modules/angular-playground/dist/build/src/app.component.js
    at Esm5RenderingFormatter.addDefinitions (workspace\node_modules\@angular\compiler-cli\ngcc\src\rendering\esm5_rendering_formatter.js:43:23)
    at workspace\node_modules\@angular\compiler-cli\ngcc\src\rendering\renderer.js:79:40
    at Array.forEach (<anonymous>)
    at Renderer.renderFile (workspace\node_modules\@angular\compiler-cli\ngcc\src\rendering\renderer.js:76:46)
    at workspace\node_modules\@angular\compiler-cli\ngcc\src\rendering\renderer.js:53:84
    at Array.forEach (<anonymous>)
    at Renderer.renderProgram (workspace\node_modules\@angular\compiler-cli\ngcc\src\rendering\renderer.js:48:54)
    at Transformer.transform (workspace\node_modules\@angular\compiler-cli\ngcc\src\packages\transformer.js:84:42)
    at workspace\node_modules\@angular\compiler-cli\ngcc\src\execution\create_compile_function.js:49:42
    at workspace\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\worker.js:85:54
    at ClusterMaster.onWorkerMessage (workspace\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:195:27)
    at workspace\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:55:95
    at ClusterMaster.<anonymous> (workspace\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:293:57)
    at step (workspace\node_modules\@angular\compiler-cli\node_modules\tslib\tslib.js:140:27)
    at Object.next (workspace\node_modules\@angular\compiler-cli\node_modules\tslib\tslib.js:121:57)
    at workspace\node_modules\@angular\compiler-cli\node_modules\tslib\tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (workspace\node_modules\@angular\compiler-cli\node_modules\tslib\tslib.js:110:16)
    at EventEmitter.<anonymous> (workspace\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:287:32)
    at EventEmitter.emit (events.js:311:20)
An unhandled exception occurred: NGCC failed.

[error] Error: NGCC failed.
    at NgccProcessor.process (workspace\node_modules\@ngtools\webpack\src\ngcc_processor.js:69:19)
    at workspace\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:576:31
    at SyncHook.eval [as call] (eval at create (workspace\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (workspace\node_modules\tapable\lib\Hook.js:154:20)
    at Object.webpack [as webpackFactory] (workspace\node_modules\webpack\lib\webpack.js:55:30)
    at createWebpack (workspace\node_modules\@angular-devkit\build-webpack\src\webpack\index.js:20:36)
    at Object.runWebpack (workspace\node_modules\@angular-devkit\build-webpack\src\webpack\index.js:34:12)
    at SwitchMapSubscriber.project (workspace\node_modules\@angular-devkit\build-angular\src\browser\index.js:131:32)
    at SwitchMapSubscriber._next (workspace\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\switchMap.js:49:27)
    at SwitchMapSubscriber.Subscriber.next (workspace\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\Subscriber.js:66:18)
    at workspace\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\util\subscribeToPromise.js:7:24
<code>

</code></pre>

## 🌍 Your Environment
<pre>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.0
Node: 12.16.1
OS: win32 x64

Angular: 10.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@ngtools/webpack                  10.0.0
@schematics/angular               10.0.0
@schematics/update                0.1000.0
rxjs                              6.5.4
typescript                        3.9.5
webpack                           4.43.0<code>

</code></pre>

**Anything else relevant?**

Angular.json
<pre>
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "STM": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "aot": true,
            "outputPath": "Map",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/assets",
              "src/assets/logo.png",
              "src/style/"
            ],
            "extractCss": true,
            "styles": [
              "node_modules/@fortawesome/fontawesome-pro/css/all.css",
              "node_modules/flag-icon-css/css/flag-icon.min.css",
              "src/styles.scss"
            ],
            "stylePreprocessorOptions": {
              "includePaths": [
                "src/style/"
              ]
            },
            "scripts": [],
            "allowedCommonJsDependencies": [
              "@angular/common/locales/de",
              "@angular/common/locales/en",
              "rxjs/Subject",
              "rxjs/operators",
              "rxjs/Subscription",
              "lodash/cloneDeep",
              "chart.js",
              "mathjs",
              "rbush"
            ]
          },
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                },
                {
                  "replace": "src/index.html",
                  "with": "src/redirect.html"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "STM:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "STM:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "STM:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
              "./node_modules/flag-icon-css/css/flag-icon.min.css",
              "src/styles.css"
            ],
            "scripts": [],
            "assets": [
              "src/assets/"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "STM-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "STM:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "STM:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "playground": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "aot": true,
            "outputPath": "dist/playground",
            "index": "src/index.html",
            "main": "src/main.playground.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/assets",
              "src/styles.css"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "playground:build",
            "port": 4201
          }
        }
      }
    }
  },
  "defaultProject": "STM",
  "schematics": {
    "@schematics/angular:component": {
      "style": "scss"
    }
  }
}
<code>
</pre>
</code>

Tsconfig.app.json
<pre>
{
  "extends": "../tsconfig.base.json",
  "compilerOptions": {
    "experimentalDecorators": true,
    "allowJs": true,
    "outDir": "../out-tsc/app",
    "types": []
  },
  "files": [
    "main.ts",
    "polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ],
  "angularCompilerOptions": {
    "enableIvy": true
  }
}
<code>

</code></pre>

**Comment by petebacondarwin** [comment]
I believe that you are using `angular-playground@6.2.x`, which does not follow the Angular Package Format (APF) - and so ngcc struggles to cope with it. I note that the latest version `7.0.3` does follow APF. Can you try updating this dependency?

**Comment by petebacondarwin** [comment]
Further could you provide a link to a project that exhibits this problem, which we can debug?

**Comment by MaTo04** [comment]
Sorry it was my mistake. I updated the angular-playground and it works. Thanks for your help.
