### ISSUE TITLE
Create an angular devtools extension for Angular 9 (Chrome, firefox, IE, Edge)

### ISSUE THREAD

**Issue by nspeedzy** [angular/angular#37735]
# 🚀 feature request

### Relevant Package

 This feature request is for the angular framework in general
 

### Description
 
Create an angular devtools extension that allows developers to study the components in an angular built website. The extension must be available to users who use Firefox, chrome, Edge or IE10. We should also be able to use the extension when the app is in production mode. I am suggesting this because it will be easier for people who just started creating a website with angular, plus web frameworks like React and Vuejs have their own devtools extension whereas Angular does not

### Describe the solution you'd like

I haven't seen upon a solution

### Describe alternatives you've considered
Have you considered any alternative solutions or workarounds?

No

**Comment by JhonatanMedeiros** [comment]
https://augury.rangle.io/

**Comment by nspeedzy** [comment]
Oh snap. I didn't know about that. I will go check it out. Thanks
