### ISSUE TITLE
Angular Microfrontend - Need to add forcible change detection for view to refresh when plugged in

### ISSUE THREAD

**Issue by aar-1** [angular/angular#37733]
We have the following tech stack -
Angular Microfrontend library - Angular 9
Host UI Angular Repo - Angular 7

Currently when we run the microfrontend independently then on component variable changes view gets refreshed.
But when we plug into the host UI by adding it as a component -
`<app-if-webcomponent *ngIf="appconfigData && isSupportedIfType" [appconfigData]="appconfigData"
      [userServObject]="userServObject" [imagingFabricPayload]="imagingFabricPayload$ | async"
      [hasAnnotationRights]="hasAnnotationPermission"></app-if-webcomponent>
    </div>`
Then we get issues that the component variable change does not reflect in a change in view internally
and we have to add for it to pick up changes - 
`this.changedetection.detectChanges();`

But this at times greatly affects the UI performance  - e.g. if a code runs in 10 ms - then it can shoot upto 20seconds as well for a component.
From our observations - we checked if its in Angular Zone or not & found that it is in NgZone - since thats a common reason for it to not be refreshed.
One of the places it doesn't work is as follows -

`ngOnInit(): void {
    this.setEditAnnotationValidation();
    const getValSubscription: Subscription = this.sharedService.getValue()
    .subscribe((data) => {
   
      if (Array.isArray(data)) {
        data = data.filter(v => v.annotationType !== ANNOTATION_TYPES.GROUP_LABEL);
        this.annotationObject = data;
      } else {
        // Other business logic
      }
      console.log('IS INA NGZONE' , NgZone.isInAngularZone());
    // Had to add maual change detection
      this.changedetection.detectChanges();
      this.annotationObjectCopy = JSON.parse(JSON.stringify(this.annotationObject));
      this.subscriptionList.push(getValSubscription);
    });`

Please help us in knowing what could be a possible reason of it getting broken & how we could eliminate extra overhead of putting change detection manually.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by aar-1** [comment]
Sure thanks for looking into it - will post at the required forum.
