### ISSUE TITLE
feat(router): release process for 1.x router

### ISSUE THREAD

**Issue by btford** [angular/angular#3774]
With #3698, we finally have the 1.x router code merged.

We still need to determine how best to version and release 1.x builds from this repo.

**Comment by twhitbeck** [comment]
am I missing something? I've cloned master, and the unit tests for angular 1 router almost all fail. Maybe it's too early, but it sounded like we had something we could see.

**Comment by btford** [comment]
@twhitbeck The code is here: https://github.com/angular/angular/tree/master/modules/angular1_router

And the artifact gets built to `dist/angular_1_router.js`.

**Comment by twhitbeck** [comment]
@btford Yes, I `built angular_1_router.js` to try it out, and when I was getting errors I tried running the unit tests. That's when I noticed that they were largely failing.

I've got an up-to-date clone of master

**Comment by btford** [comment]
@twhitbeck feel free to file new issues for whatever error's you're seeing. I'd like to keep discussion on this issue focused on release concerns.

**Comment by satish860** [comment]
btford is this to say we will be able to get angular new router in 1.5 ?

**Comment by SanderElias** [comment]
@btford, Just for my easy of setting up plunks, is there an pre-build artifact available online somewhere?

**Comment by brandonroberts** [comment]
@SanderElias Here is a plunk example with a pre-built artifact if you want to use it

http://plnkr.co/edit/005pXZKP2Ag5UkH7IzJf?p=preview

**Comment by satish860** [comment]
@brandonroberts Is there any code repo or directory get the latest version until the final version is release. I tried building the repo and it hard to do the same.

**Comment by brandonroberts** [comment]
@satish860 you can get a pretty recent build from npm 

    npm install @angular/router

**Comment by satish860** [comment]
@brandonroberts  isn't that angular 2.0 router ?

**Comment by brandonroberts** [comment]
@satish860 it has a build of the router for both Angular 1 and 2.

**Comment by satish860** [comment]
@brandonroberts  Can you please point me to right Package in NPM, I am not able to find in NPM . Sorry for that and thanks for your help

**Comment by satish860** [comment]
Sorry I got that done.

**Comment by brandonroberts** [comment]
:+1:

**Comment by poshest** [comment]
@btford to repeat satish860's question, will we be able to get angular new router in 1.5?  When?  

Meantime, is the `npm install @angular/router` version the latest release?  How stable/final is it?  Enough that you would recommend relying on it for development now?

**Comment by poshest** [comment]
Further to my questions, I just plugged in `router-directive.es5.js` and got this error `Error: [$injector:unpr] Unknown provider: $$rootRouterProvider <- $$rootRouter <- $router <- aDirective` on both 1.4.4 and 1.5.0-rc.0 branches.  Is there something else I need to reference?  Searching the 1.x and 2 repositories yeilds `We couldn’t find any code matching '$$rootRouterProvider'`.

Also `router-directive.es5.js` breaks `strictdi`.

**Comment by brandonroberts** [comment]
@poshest the `router-directive.es5.js` is no what you should be using. If you `npm install @angular/router` there is `node_modules/@angular/angular1/angular_1_router.js`. That's what you should be using. Here is a sample repo with the new router and component helper. https://github.com/brandonroberts/angularjs-component-router

**Comment by iksose** [comment]
nice @brandonroberts

**Comment by poshest** [comment]
@brandonroberts OK, thanks!  My `npm install @angular/router` yielded

````
 $ find ./node_modules -name '*router*' 2>/dev/null
./node_modules/express/lib/router
./node_modules/angular-new-router
./node_modules/angular-new-router/dist/router.es5.js
./node_modules/angular-new-router/dist/router.es5.min.js
./node_modules/angular-new-router/dist/router.js
./node_modules/angular-new-router/src/router-directive.es5.js
./node_modules/angular-new-router/src/router.ats
./node_modules/angular-new-router/test/router-viewport.es5.spec.js
./node_modules/angular-new-router/test/router.spec.ats
./node_modules/angular-new-router/node_modules/route-recognizer/tests/router-tests.js
````

Perhaps it's changed since you `./node_modules/angular-new-router/dist/router.es5.js` seems to be working much better.

**Comment by brandonroberts** [comment]
@poshest that's not the right one, but ok :+1:

**Comment by poshest** [comment]
OK, @brandonroberts I copied the version you included in http://plnkr.co/edit/005pXZKP2Ag5UkH7IzJf?p=preview.  But I'm assuming that's not the latest?  Is it not on Github somewhere?  

And by the way, now it's `ng-outlet` and not `ng-viewport`?  I'm thoroughly confused. Is this doco https://angular.github.io/router/ out of date?

**Comment by brandonroberts** [comment]
@poshest No its not the latest one. The latest build isn't published. Yes, that site is way out of date. Here is an example with an updated build as of today and angular 1.5.0.rc0   http://plnkr.co/edit/bzmgUygZ5nPLDaU7ucHB?p=preview

**Comment by poshest** [comment]
@brandonroberts that helps very much!  And could you please give me a steer in the right direction with my other questions: How stable/final is it? Enough that you would recommend relying on it for development now?  How far off is it from going into the 1.5 branch?

**Comment by brandonroberts** [comment]
@poshest I have no concrete answers for you there. Its usable but not production ready is about the best I can say.

**Comment by poshest** [comment]
@brandonroberts OK, much obliged. :) Is the plan at least to put it into 1.5.0?  I read that using the new router was one of the good things to do to prepare for 2.0, so figured it would be worth building directly on the new one instead of starting now with ngRoute.

**Comment by brandonroberts** [comment]
@poshest It was/is planned to be released along with 1.5.0. I suggest you start using it to get a feel for how it works. It will help with migration either way

**Comment by winnemucca** [comment]
Big thanks for sharing the git repo @brandonroberts .  There seems to be a couple of small errors on the repo.

**Comment by brandonroberts** [comment]
@winnemucca What errors are you getting?

**Comment by winnemucca** [comment]
1. On about.js 
    Uncaught TypeError: angular.module(...).component is not a function

2. Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
Error: [$injector:nomod] Module 'myApp' is not available! You either misspelled the module name or forgot to load it.

The modules seem correct not sure what is causing that.

**Comment by brandonroberts** [comment]
@winnemucca delete your node_modules folder and do a clean install. See https://github.com/brandonroberts/angularjs-component-router/issues/2

**Comment by jgrund** [comment]
Just curious, what is the current timeline for this coming to Angular 1.x?

**Comment by brandonroberts** [comment]
@jgrund there is a guide in the upcoming 1.5.1 already here: https://docs.angularjs.org/guide/component-router. @petebacondarwin can shed some light on a more official announcement.

**Comment by petebacondarwin** [comment]
We have  a release of the component router, 0.2.0, that works well enough with Angular 1.5.
So you can go get the bits and start building Angular 1.5 apps with the new router right now, using the guide mentioned above as a starting point.

There are more improvements in the pipeline so 0.3.0 will be even better.
It is an iterative incremental improvement process and 1.0.0 of the component router will coincide with the final release of Angular 2.

**Comment by jgrund** [comment]
@brandonroberts @petebacondarwin Thanks. What's the best way to get the bits right now?

**Comment by petebacondarwin** [comment]
@jgrund I would just follow the component router guide at https://docs.angularjs.org/guide/component-router, which says to use npm:

```
npm install --save angular
npm install --save @angular2/router
```

**Comment by evangalen** [comment]
@petebacondarwin cannot seem to install 0.2.0 through NPM.
When I do a `npm install --save @angular/router` version 0.1.0 of the component router is installed...
... and when trying to force installing 0.2.0 (using `npm install --save @angular/router@0.2.0`) NPM complains that 0.2.0 is "invalid".

**Comment by petebacondarwin** [comment]
@evangalen - what npm repository are you pointing at? I get the following:

```bash
npm info @angular/router
 
{ name: '@angular/router',
  'dist-tags': { 'pre-release': '0.1.0', latest: '0.2.0' },
  versions: [ '0.0.1', '0.1.0', '0.2.0' ],
  maintainers: [ 'angular <angular-core+npm@google.com>' ],
  time: 
   { modified: '2016-03-03T22:30:40.106Z',
     created: '2015-11-06T23:22:32.296Z',
     '0.0.1': '2015-11-06T23:22:32.296Z',
     '0.1.0': '2016-02-12T21:08:55.364Z',
     '0.2.0': '2016-03-03T22:30:40.106Z' },
  readmeFilename: '',
  users: { theodorejb: true },
  version: '0.2.0',
  scripts: {},
  dist: 
   { shasum: '4a30c79122273baefeb76376fbed62570e28a828',
     tarball: 'http://registry.npmjs.org/@angular/router/-/router-0.2.0.tgz' },
  directories: {} }
```

**Comment by evangalen** [comment]
@petebacondarwin thanks for your response... weird... now it does work... and I did try multiple times this morning... also doing a `npm cache clean` and completely clearing out all stuff (i.e. node_modules) from my current directory.

I do have one issue left... turns out that NPM won't install `@angular/router` when I specify a registry (pointing to our internal Artifactort mirror) in my .npmrc.
Could it be that the \@ in front of `angular` is causing issues when using enterprise NPM mirroring solutions?

**Comment by petebacondarwin** [comment]
I believe that scoped packages are restricted to specified repositories...

**Comment by mhevery** [comment]
closing as obsolete due to new router.

**Comment by jgrund** [comment]
The docs now say the router is deprecated for 1.x. Is it the case that the new router can be used in 1.x projects?
