### ISSUE TITLE
Zone.js does not support native async/await in ES2017 warning

### ISSUE THREAD

**Issue by markgoho** [angular/angular#37742]
# 📚 Docs or angular.io bug report

### Description

[We're told to update our target to `es2018`](https://update.angular.io/#9.0:10.0l3), so, after doing that, I'm getting a ton of 
``` bash
WARNING: Zone.js does not support native async/await in ES2017.
    These blocks are not intercepted by zone.js and will not triggering change detection.
    See: https://github.com/angular/zone.js/pull/1140 for more information.
```
...when I run tests and when I serve the application.

### Reproduction Steps**
Upgrade to Angular v10, update `target` in `tsconfig.base.json` to `es2018`

### Expected vs Actual Behavior**
Expected behavior would probably be to not see any sort of warning after having followed official instructions. In reality, I'm getting a warning with a linked PR to an archived repo. We could provide a better experience to our users.

**Comment by alan-agius4** [comment]
The update guide is incorrect. You shouldn't be needed to update the script target. I also see a number of points that shouldn't be there in the medium/advanced sections.

**Comment by alan-agius4** [comment]
Issue for zone.js not supporting ES2017 can be found here: https://github.com/angular/angular/issues/31730

**Comment by markgoho** [comment]
@alan-agius4 should we close this issue with the workaround: Leave tsconfig target as `es2015`?

**Comment by alan-agius4** [comment]
@markgoho, it’s best to keep this open at least until we fix the update guide.

**Comment by splincode** [comment]
I have same problem after upgrade (es2018)

**Comment by alan-agius4** [comment]
@splincode, don’t change the application target to es2018.

**Comment by romanryasne2** [comment]
How to suppress this warning? It doesn't make sense to me, since I don't use zone.js at all.

**Comment by driiftkiing** [comment]
> How to suppress this warning? It doesn't make sense to me, since I don't use zone.js at all.

but still there is a peer-dependency in `angular/core`...

**Comment by freed00m** [comment]
@splincode - can you provide an/link to explanation why? please

I know the Ivy compiler compiles to es2015, but nowhere in the wikis and github I could find more direct information why the target in tsconfig should be es2015 and how does it relate to the AOT compilers.

**Comment by qortex** [comment]
I removed all references to async/await and still get the warning.

Can some angular blog post explain the situation here? Should we update to es2018 or not? What does it even mean? What are the tradeoffs?

**Comment by xinthose** [comment]
I think this issue causes `this.router.navigate` to show this error in the console: `Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?`
