### ISSUE TITLE
Autocomplete doesn't work in VSCode to access directives, attributes and methods of components with Angular v10

### ISSUE THREAD

**Issue by jcpalma** [angular/angular#37751]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

This not affect packages.

### Is this a regression?
No, this feature work in previous versions.

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
When you need include directives, attributes in view components (html files) doesn't works.

## 🔬 Minimal Reproduction

Create a components, when you need to reference directives o attributes in html files, autocomplete o intelligence doesn't work.

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre>No Error<code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>v10.0.0<code>

</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment]
Hi @jcpalma, we've reviewed this ticket and found out that there is not enough information to proceed. Could you please create a new ticket and follow the issue template (and fill in the sections from the template)? If the problem still exists, it'd be helpful to have a repro (in a form of GitHub repository) that we can use to investigate the problem further. Thank you.

**Comment by kyliau** [comment]
This is a duplicate of https://github.com/angular/vscode-ng-language-service/issues/824.

**Comment by jcpalma** [comment]
Hi @AndrewKushnir, thanks for your answer. This is the first time I've ever reported a problem.

**Comment by jcpalma** [comment]
Hello @kyliau, Thank you for your observation.
