### ISSUE TITLE
Rename HTML5LocationStrategy to PushstateLocationStrategy

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#3776]
I think that we should move away from the "HTML5" lingo for location strategy.

HTML spec is no longer versioned and a year or two this naming will look archaic.

I'm happy to consider other names as long as they don't refer to HTML5.

**Comment by btford** [comment]
The problem is that both of them use "pushstate" – one just happens to serialize the url to the hash.

I think `PathLocationStrategy` is maybe better?

**Comment by btford** [comment]
Last week we agreed on `PathLocationStrategy`. I made the change and pushed to presubmit.

**Comment by evanplaice** [comment]
Considering this is a breaking change, it should be documented in the CHANGELOG.
