### ISSUE TITLE
Compiler XHTML support

### ISSUE THREAD

**Issue by dgp1130** [angular/angular#37779]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler

### Is this a regression?

Sort of. XHTML did somewhat work before and we are [considering it a regression in the CLI](https://github.com/angular/angular-cli/issues/16964#issuecomment-587271546). Though I doubt this was ever supported in the Ivy compiler, it may have sort-of worked in View Engine.

### Description

The Angular compiler should be capable of outputting XHTML for SSR and app-shell use cases. See https://github.com/angular/angular-cli/pull/16965 and [this Slack thread](https://app.slack.com/client/T040VPWEE/C46U16D4Z/thread/C46U16D4Z-1585164541.040900) for more discussion.

**Anything else relevant?**

Some serving tools (such as Spring in particular I think) want XHTML-compliant content and throw errors if not the case. The main motivation for this is to be compatible with such tools.

**Comment by dgp1130** [comment]
Related: https://github.com/angular/angular-cli/issues/18044.

**Comment by bbarry** [comment]
I think the link in the description should be to CLI PR https://github.com/angular/angular-cli/pull/16965 and not the local issue #16965.

**Comment by dgp1130** [comment]
See: https://github.com/angular/angular-cli/issues/18044#issuecomment-832281245
