### ISSUE TITLE
[Build-Library] WARNING: No name was provided for external module '@ionic-native/camera/ngx' in output.globals – guessing 'ngx'

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#37789]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: no idea

### Description
I have just created my first angular library contribution to open source
Repo: https://github.com/indraraj26/ion-camera

No clue where to put global dependencies 
now when i am adding this npm package to project i get this 
```
[ng] Warning: Entry point '@indraraj26/ion-camera' contains deep imports
 into 'D:/ionic/ionic5-starter-tabs-sidemenu/node_modules/@ionic-native/camera/ngx/index', 
'D:/ionic/ionic5-starter-tabs-sidemenu/node_modules/@ionic-native/ionic-webview/ngx/index'. 
This is probably not a problem, but may cause the compilation of entry points to be out of order.
``` 

These two are dependencies of this library
```
npm install @ionic-native/camera
npm install @ionic-native/ionic-webview
```

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

[ng] Warning: Entry point '@indraraj26/ion-camera' contains deep imports
 into 'D:/ionic/ionic5-starter-tabs-sidemenu/node_modules/@ionic-native/camera/ngx/index', 
'D:/ionic/ionic5-starter-tabs-sidemenu/node_modules/@ionic-native/ionic-webview/ngx/index'. 
This is probably not a problem, but may cause the compilation of entry points to be out of order..
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Version: 9.1.9
CLI version: 9.1.7
</code></pre>

**Anything else relevant?**
I have added this in projects/ion-camera/package.json to test but still getting error

"ngPackage": {
		"lib": {
			"entryFile": "public-api.ts"
		},
		"dest": "dist",
		**"whitelistedNonPeerDependencies": [
			"."**
		]
	},

**Comment by petebacondarwin** [comment]
This warning comes from ngcc. It is not a concern because the "deep" imports (the ones ending in `/index`) are basically copies of the normal non-deep imports. E.g.

```
import { Camera } from '@ionic-native/camera/ngx';
import { WebView } from '@ionic-native/ionic-webview/ngx';
import { Camera as Camera$1 } from '@ionic-native/camera/ngx/index';
import { WebView as WebView$1 } from '@ionic-native/ionic-webview/ngx/index';
```

If necessary you could hide the warnings by providing an `ngcc.config.js` file in your library.

It is a strange warning because it looks like this problem is caused by the imports that are added automatically by the Angular compiler.

**Comment by indraraj26** [comment]
i am trying to solve this since afternoon don't know where i went wrong, i thought i used ng-packagr because of that it is creating this warning. So i rebuild the structure of library still i am getting error.

Do i have to add this in ngcc.config.js
```
{
	ignorableDeepImportMatchers: [
		'@ionic-native/camera/ngx/index',
		'@ionic-native/ionic-webview/ngx/index',
	];
}

```

**Comment by petebacondarwin** [comment]
I'm not sure if we should be getting these warnings via ngPackagr... Perhaps @alan-agius4 has an idea?
But, yes, the `ignorableDeepImportMatchers` ought to turn of the warning.

**Comment by indraraj26** [comment]
Still i am getting deep import warning in project i just published 0.0.8 and added ngcc.config.js to ignoreDeepImportMatchers
Repo: https://github.com/indraraj26/ion-camera/tree/master/projects/ion-camera

I have added this in ng-package.json to hide no name was provided for external module during build library
```
"umdModuleIds": {
"@ionic-native/camera/ngx": "@ionic-native/camera/ngx",
"@ionic-native/ionic-webview/ngx": "@ionic-native/ionic-webview/ngx",
"@ionic-native/camera/ngx/index": "@ionic-native/camera/ngx/index",
"@ionic-native/ionic-webview/ngx/index": "@ionic-native/ionic-webview/ngx/index"
}
```

**Comment by alan-agius4** [comment]
@indraraj26, I am nit confused by the issue you are reporting.

In the issue title your are mentioning a warning related to module ids, but in the issue description you are mentioning a warning related to deep imports. These are 2 very different unrelated warnings, with different root causes and resolutions.

For `No name was provided for external module`, you can read this documentation: https://github.com/ng-packagr/ng-packagr/blob/master/docs/dependencies.md

For the ngcc warnings related to deep imports you need to config an `ngcc.config.js` and provide this config as part of the distributable library as mentioned by @petebacondarwin.

**Comment by indraraj26** [comment]
Sorry @alan-agius4 , i thought both warning it is because of ng-packagr package. You can see i closed this thread 3 hours ago and reopened it. I had opened issue at ng-packagr as well but end up being here. 

I see ngcc.config.js is being added in final but still i am getting deep import error

![image](https://user-images.githubusercontent.com/23274631/85925896-13de0780-b8b9-11ea-82bd-6b62d3a6eef2.png)

![image](https://user-images.githubusercontent.com/23274631/85925961-818a3380-b8b9-11ea-9f5d-63d828a71daa.png)

Regarding no name was provided for external module still i am confused even though it is resolved by these changes
> I have added this in ng-package.json to hide no name was provided for external module during build library
> 
> ```
> "umdModuleIds": {
> "@ionic-native/camera/ngx": "@ionic-native/camera/ngx",
> "@ionic-native/ionic-webview/ngx": "@ionic-native/ionic-webview/ngx",
> "@ionic-native/camera/ngx/index": "@ionic-native/camera/ngx/index",
> "@ionic-native/ionic-webview/ngx/index": "@ionic-native/ionic-webview/ngx/index"
> }
> ```


```
 "umdModuleIds": {
     // i see key is referred to package name but what about value DateFns i checked their repo i cant find it 
      "date-fns": "DateFns" 
    }
```
