### ISSUE TITLE
Activate route params getting empty

### ISSUE THREAD

**Issue by Bizotics-Dev** [angular/angular#37787]
Angular 7
Here we route for lazyloaded module , when we try to access route params in app component it's getting empty object.
also added  paramsInheritanceStrategy: 'always' in approutes but still it not works.
we try with queryParams,queryParamap but not works.Please check it.

**Comment by JoostK** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
