### ISSUE TITLE
Deploying production application to web gives error: Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by peter-snr** [angular/angular#37791]
# 🐞 bug report

Uncaught SyntaxError: Unexpected token '<'

### Affected Package
Angular 9

### Is this a regression?
Do not know

### Description

I have built a new Angular 9 project using these args:

ng build fe --prod  --baseHref /fe/

The generated files in dist/fe are copied to an nginx server

This URL is visited:

http://localhost/fe/

A blank page is served and the console contains these errors: 

Uncaught SyntaxError: Unexpected token '<'  runtime.js:1 
Uncaught SyntaxError: Unexpected token '<'  polyfills.js:1 
Uncaught SyntaxError: Unexpected token '<'  scripts.js:1 
Uncaught SyntaxError: Unexpected token '<'   main.js:1 

## 🔬 Minimal Reproduction
Create a new Angular 9 project.
Create a --prod build.
ng build fe --prod  --baseHref /fe/
Deploy generated content to NGINX server
Visit page.

## 🔥 Exception or Error
<pre><code>
Uncaught SyntaxError: Unexpected token '<'
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.1.1
Node: 10.16.0
OS: linux x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.1
@angular-devkit/build-angular      0.901.1
@angular-devkit/build-ng-packagr   0.901.1
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.1
@angular-devkit/core               9.1.1
@angular-devkit/schematics         9.1.1
@angular/cdk                       9.2.0
@angular/material                  9.2.0
@ngtools/webpack                   9.1.1
@schematics/angular                9.1.1
@schematics/update                 0.901.1
ng-packagr                         9.1.0
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0

</code></pre>

**Anything else relevant?**
No

**Comment by jnizet** [comment]
That looks like a server configuration problem: instead of returning the JavaScript files, the server seems to be returning HTML error pages. 
If you open the network tab of your browser console, you should be able to inspect the response and, hopefully, see what the server returns as responses to the requests for the .js files.

**Comment by JoostK** [comment]
I agree with @jnizet here, this is likely a server configuration issue.

**Comment by peter-snr** [comment]
Agreed, it was returning the .js files as text/html, even though I had the mime types set (NGINX). It was still incorrect.

I was using a prefix in my index.html 
`<base href="/fe/">`
My nginx.conf has this section
```
http {
  include /etc/nginx/mime.types;

  server {
    listen 80 default_server;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    gzip on;
    gzip_min_length 1000;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    location /fe/ {
      try_files $uri $uri/ /index.html;
    }
  }
```
Moving all files to `/usr/share/nginx/html/fe` but keeping the index.html in `/usr/share/nginx/share` solved the issue.

In case this helps anyone else having problems with serving Angular 9 with NGINX and using prefixes.
