### ISSUE TITLE
Angular 9: pathMatch prefix not working in expected way

### ISSUE THREAD

**Issue by vasicvuk** [angular/angular#37797]
# 🐞 bug report

### Affected Package
@angular/router:9.0.7

### Is this a regression?

With Angular 8 the router handled URL differently so that all subpaths are resolved with component specified in routes

### Description

I have a route defined like this:
```
  {
    path: 'sample/:key',
    component: SampleComponent,
    pathMatch: 'prefix'
  }
```
When navigating to URL: localhost:4200/sample/10/children i expect for SampleComponent to appear but instead i get following error:
<pre><code>
Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'sample/11/children'
Error: Cannot match any routes. URL Segment: 'sample/11/children'
</code></pre>
Route sample/11 works regulary

## 🔬 Minimal Reproduction

Reporduction on following link:
https://stackblitz.com/edit/angular-ivy-vppcwo?file=src%2Fapp%2Fapp.module.ts

## 🔥 Exception or Error

<pre><code>
Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'sample/11/children'
Error: Cannot match any routes. URL Segment: 'sample/11/children'
</code></pre>

## 🌍  Your Environment

**Angular Version:** 
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.1.4
Node: 12.16.3
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.4
@angular-devkit/core         9.1.4
@angular-devkit/schematics   9.1.4
@schematics/angular          9.1.4
@schematics/update           0.901.4
rxjs                         6.5.4

</code></pre>

**Comment by criskrzysiu** [comment]
@vasicvuk Why closed?

**Comment by vasicvuk** [comment]
@criskrzysiu Because it didn't work that way on previous versions also. The issue i had was not using encodeUriComponent which I used before. Anyway this would be nice to have as an feature (Some wildcard character matching all after some path)
