### ISSUE TITLE
Angular.io dev guide still shows the renamed viewInjector 

### ISSUE THREAD

**Issue by stevenroose** [angular/angular#3781]
It's here: https://angular.io/docs/dart/latest/guide/displaying-data.html
Search for viewInjector.

I found out that it has been renamed to viewBindings, but it was not trivial. Please update the dev guide accordingly.

Is there a repo for the dev guide btw? I'd correct it myself..

**Comment by ericmartinezr** [comment]
Hey there @stevenroose, the repo for angular.io is https://github.com/angular/angular.io

**Comment by stevenroose** [comment]
Should be fixed by my change.
