### ISSUE TITLE
Creating fake event objects for testing components.

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#3782]
Say I want to test a component behavior where `preventDefault()` or `stopPropagation()` is called on some event.

In vanilla JS land, I would create a fake event object, passing it to the event handler and be done with it. However, with types, any fake event has to line up with the expected event type for both TS and Dart. One could _almost_ just do `class FakeEvent extends Event`, but IE doesn't support instantiating event objects with `new`.

From here, there's no clear way of getting a fake event object that works with the handler's signature

**Comment by naomiblack** [comment]
@mhevery @juliemr this is needed so we can write unit tests that capture keyboard accessibility.

**Comment by juliemr** [comment]
Would be useful primarily for compiling both to Dart and JS, but also for creating events cross-browser.

**Comment by juliemr** [comment]
Material has solutions for this internally - we should address this with utilities to make event testing easier, but this isn't an RC blocker so I'm moving to a later milestone.

**Comment by nadavsinai** [comment]
I use a little lib called [simulant](https://github.com/Rich-Harris/simulant) quite successfully.
I do a lot of component testing with it, mostly very successfully ;-);
one thing I found it can't do - fake mouseWheel event in phantomJS , but that phantom's fault...

**Comment by marcysutton** [comment]
There are little to no examples of Angular 2 unit test coverage for keyboard/accessibility support. Now that Angular 2 is stable, it's imperative that support be added for this.

**Comment by yugi03** [comment]
@jelbourn : Can we now make fake event objects for testing purpose?

**Comment by Splaktar** [comment]
Should this have some kind of label for priority/severity?

**Comment by mswilson4040** [comment]
My use case is that I have some third party application who spits out window.postMessage events to me. I need a way to unit test a function that takes in a MessageEvent as an argument. However, that particular test checks the origin on the MessageEvent object but that's read only so I need to create a FakeMessagEvent which doesn't seem to be possible without sacrificing the type.

**Comment by db6edr** [comment]
Why not simply - in this test - call the event handler directly with a fake event object as argument?
You have other tests that check for the handler being attached to the onMessage event, so that should not be a problem.

**Comment by mswilson4040** [comment]
Not in this case since it's the `window.postMessage` event. I specifically need to test the origin and some other read only properties. Yes, on the TypeScript side, I could just not put it's type as a `MessageEvent` and just pass in a custom object, but i'm using TypeScript and therefore I should be using types.

**Comment by mswilson4040** [comment]
Still feels like a hack.

**Comment by splincode** [comment]
@jelbourn Is the issue relevant?

**Comment by jelbourn** [comment]
Yeah, though we may end up deciding that it's something that's more appropriate for the cdk.

**Comment by Splaktar** [comment]
@manughub does this need to be reassigned?

Can the triage team evaluate this for a priority/sev?

**Comment by jelbourn** [comment]
Closing since we moved in the direction of doing this more in the cdk (see `@angular/cdk/testing`)
