### ISSUE TITLE
Template definition error: Cannot invoke an object which is possibly 'undefined'.

### ISSUE THREAD

**Issue by muuvmuuv** [angular/angular#37820]
# 🐞 bug report

### Affected Package

I guess core or anything related to html templates

### Is this a regression?

 I think so but have not tested `strictTemplates` before

### Description

 A clear and concise description of the problem...

I am trying to use `strictTemplates` atm an encountered a weird behaviour. In the below code I declare `dropdown` to be optional but if set it must have items in it. In my template I have an `if`-clause to check wether or not the `dropdown` is set so later I can be sure looping over items is possible BUT the compiler seems to don't understand that. Here it says `'dropdown' is possibly undefined. Consider using the safe navigation operator (dropdown?.items) or non-null assertion operator (dropdown!.items).` which I don't understand, it has to be safe in that situation or am I missing something?

```ts
export interface ButtonDropdown {
  items: ButtonDropdownItem[]
}

@Component({
  // eslint-disable-next-line @angular-eslint/component-selector
  selector: 'button, [button]',
  templateUrl: './button.component.html',
  styleUrls: ['./styles/button.component.scss', './styles/dropdown.component.scss'],
})
export class ButtonComponent implements Button, OnInit {
  // ...
  @Input() dropdown?: ButtonDropdown
// ...
}
```

```html
<div
  *ngIf="dropdown"
  class="dropdown"
  aria-haspopup="true"
  aria-label="Open dropdown"
>
  <ul class="menu">
    <li *ngFor="let item of dropdown.items">
      <a
        (click)="item.pressed()"
        href="#0"
      >{{ item.label }}</a>
    </li>
  </ul>
</div>
```

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

If it isn't possible to help me without a repl I will add one.

## 🔥 Exception or Error
<pre><code>

From VS Code: 'dropdown' is possibly undefined. Consider using the safe navigation operator (dropdown?.items) or non-null assertion operator (dropdown!.items). ng

src/app/shared/button/button.component.html:27:23 - error TS2722: Cannot invoke an object which is possibly 'undefined'.

27         (click)="item.pressed()"
                         ~~~~~~~

  src/app/shared/button/button.component.ts:33:16
    33   templateUrl: './button.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ButtonComponent.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 10.0.0
Node: 12.18.0
OS: darwin x64

Angular: 10.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.9
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.901.9
@angular-devkit/build-webpack     0.901.9
@angular-devkit/core              9.1.9
@angular-devkit/schematics        10.0.0
@angular/cdk                      10.0.0
@angular/cli                      10.0.0
@ngtools/webpack                  9.1.9
@schematics/angular               10.0.0
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
This a known issue with the language service, which does not follow the exact type checking as the "real" compiler does. There's effort being put in to address these kinds of issues, but we're not there yet. See #35513 for details.

**Comment by slcoder** [comment]
> This a known issue with the language service, which does not follow the exact type checking as the "real" compiler does. There's effort being put in to address these kinds of issues, but we're not there yet. See #35513 for details.

Can you please let me know, what is the exact solution for fix this please?

**Comment by JoostK** [comment]
This is no longer an issue with the Ivy language service.
