### ISSUE TITLE
Angular 10 Router Outlet does not match

### ISSUE THREAD

**Issue by danielehrhardt** [angular/angular#37826]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
@angular/*

### Is this a regression?
Yes
I downgraded my Version to ~9.1.8 and there it is working.

### Description
![image](https://user-images.githubusercontent.com/19570043/86025880-0b0f4200-ba2f-11ea-9223-80ab0d718414.png)

this.router.navigate(['auth', 'login']) should redirect to the Router Outlet inside the Blank Component
this.router.navigate(['dashboard']) should redirect to the Router Outlet inside the Full Component

With Angular 10 the Outlet stay in the Old URL Outlet.

## 🌍  Your Environment

**Angular Version:**
Angular 10

**Comment by atscott** [comment]
Hi @danielehrhardt, can you please provide a minimal reproduction in stackblitz so we can investigate this issue?

**Comment by danielehrhardt** [comment]
I will create a Repo

**Comment by danielehrhardt** [comment]
https://github.com/codextde/ionic-router-angular-10-issue
It is an Ionic Issue. I will create there a new Issue.
Thank you for the Help!!
