### ISSUE TITLE
Value of input element can't be refreshed with the same value

### ISSUE THREAD

**Issue by archzaiko** [angular/angular#37824]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 No, the previous version has the same behavior

### Description
There is an input on the page with using property binding to its value.

<b>html</b>
```HTML
<button (click)="onClick()">Set value</button>
<input type="text" [value]="getValue()">
```

A new value is set by clicking on the button as shown below

<b>ts</b>
```JavaScript
data = 'default value';
getValue() {
  return this.data;
}
 onClick() {
  this.data = 'new value';
}
```

The input at the first render has a value ```default value```. Then, after the first click on the button, it has the ```new value```.
If clear the value manually (select the value and remove it) and click on the button again, the value isn't updated.

I found a reason of this in source code ```core/src/render3/bindings.ts```

```JavaScript
export function bindingUpdated(lView: LView, bindingIndex: number, value: any): boolean {
  const oldValue = lView[bindingIndex];

  if (Object.is(oldValue, value)) {
    return false;
  } else {
    lView[bindingIndex] = value;
    return true;
  }
}
```

Because of the value isn't changed and the function has the ```Object.is(oldValue, value)``` condition, the input element doesn't update its value

is it expected behavior and is there some workaround to solve my problem?

P.S. The same problem exists if we update ```checked``` for radio/checkbox components

## 🔬 Minimal Reproduction
 https://stackblitz.com/edit/angular-ivy-gqkhgr

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.0
Node: 10.20.1
OS: win32 x64

Angular: 10.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@angular/cli                      10.0.0
@ngtools/webpack                  10.0.0
@schematics/angular               10.0.0
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0
</code></pre>

**Comment by mlc-mlapis** [comment]
@archzaiko You have the binding for the value `[value]="getValue()"` and concurrently you don't want to use it. So you have to somehow, like using `(blur)` event, pass that manual change into the model.

**Comment by JoostK** [comment]
This is working as expected. Angular render the model into a view, hence you'll see the input update to `'new value'` if the model changes as that is when Angular detected the change and syncs it to the view. Once you start manually updating the view, you'll also have to update the model to reflect that change. In your case, the model stays `'new value'` so there's no need for Angular to update anything, as the most recent value it set was already `'new value'` (so from Angular's perspective the view is still up-to-date with the model)
