### ISSUE TITLE
ERROR: 'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by paulo3262** [angular/angular#37832]
Error when building the library in angular 9 the error occurs in the build of UMD

Bundling to UMD
ERROR: 'import' and 'export' may only appear at the top level
An unhandled exception occurred: 'import' and 'export' may only appear at the top level
See "/tmp/ng-4K3jnq/angular-errors.log" for further details.

`{
    "@angular-devkit/build-angular": "~0.901.9",
    "@angular-devkit/build-ng-packagr": "~0.901.9",
    "@angular-devkit/build-webpack": "~0.901.9",
    "@angular/cli": "^9.1.9",
    "@angular/compiler-cli": "9.1.11",
    "@angular/animations": "9.1.11",
    "@angular/cdk": "^9.2.4",
    "@angular/common": "9.1.11",
    "@angular/compiler": "9.1.11",
    "@angular/core": "9.1.11",
    "@angular/elements": "^9.1.11",
    "@angular/flex-layout": "^9.0.0-beta.31",
    "@angular/forms": "9.1.11",
    "@angular/material": "^9.2.4",
    "@angular/platform-browser": "9.1.11",
    "@angular/platform-browser-dynamic": "9.1.11",
}`

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by paulo3262** [comment]
solution install the package `@rollup/plugin-commonjs@11.0.2`,  the problem is in the rollup library
