### ISSUE TITLE
Missing contributors list in Angular 10 release blog post

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular#37839]
# 📚 Docs or angular.io bug report

### Description

Hello, I didn't want to tell it on day one because I thought it was an oversight, but there is still no contributors list in [Angular 10 release blog post](https://blog.angular.io/version-10-of-angular-now-available-78960babd41). :(

### What's the affected URL?**
[https://blog.angular.io/version-10-of-angular-now-available-78960babd41](https://blog.angular.io/version-10-of-angular-now-available-78960babd41)

### Expected vs Actual Behavior**
A thank you to all contributors (both for Angular and Angular CLI).

**Comment by mgechev** [comment]
Hey @cyrilletuzi, thanks for pointing this out!

That's not a common practice yet. So far, we've listed the contributors for only two releases [v2](http://blog.angularjs.org/2016/09/angular2-final.html) and [v9](https://blog.angular.io/version-9-of-angular-now-available-project-ivy-has-arrived-23c97b63cfa3). I particularly remember v2 because I was super excited to see my name in the blog post as an external contributors.

I think we're all on the same page that it's a good idea to make it a common practice. We don't have the infrastructure for this yet. Both times the list was generated with a pretty much ad hoc approach, via non-reusable shell scripts.

I have two suggestions:
- We can hold this off for a future release. I'll likely have the bandwidth to implement reusable package on time for v11.
- We can collaborate on implementing these scripts together and edit the blog post.

How does this sound?

**Comment by cyrilletuzi** [comment]
Hi @mgechev,

It was also the case for [v8](https://blog.angular.io/version-8-of-angular-smaller-bundles-cli-apis-and-alignment-with-the-ecosystem-af0261112a27).

As for your suggestions, I'll be honest: it sounds very bad. It may not be your intention, but what you're suggesting is basically saying "if you want your due recognition, do the work yourself".

Especially when on the technical level I don't see why the previous scripts can't be reused (the repos are still the same, and I'm quite sure that Angular CLI already does have that kind of scripts as each release automatically has the list of contributors).

Up to you.

**Comment by santoshyadav198613** [comment]
Hi @cyrilletuzi, 
Though I would love to see the contribution list in all releases, there is nothing wrong in what @mgechev asked for, open source is all about collaboration,  and I am sure if there was some script, the team would have loved to use that, so my thought is let's work like a team, and let's do something so it can be automated, believe me I am one of the devs, who was shouting and telling everyone like crazy when I saw my name in Angular 8 release for the first time, and would love to see contributors list in all future releases.

**Comment by cyrilletuzi** [comment]
Hi @santoshyadav198613, I didn't open this issue to start a debate. It turns out that, coincidently, all the versions I contributed to had their contributors list. So I wasn't aware that the others versions did not, and honestly it didn't even come to my mind to check, as for me it seems like a very natural thing to do in a project like Angular.

Apparently it's not that "natural". So to try to be objective, I checked in other tools:
- jQuery: in each minor release (manually)
- React: in each minor release (manually)
- Vue.js: more disparate (not always a full list of contributors, but at least a "thank you all")

To be clear: their release cycle is not the same, so I'm not suggesting Angular should to the same in each minor release. For Angular, the equivalent are major releases.

Also note that a simple "thank you" with links (to GitHub releases or maintainers page) takes no time at all, and would be more in line with the "working with the community" blog post's sentence.

But again, I'm not here to fight. It's up to the Angular team, I'll close my issue if they think it can wait v11.

**Comment by santoshyadav198613** [comment]
Hey @cyrilletuzi sorry buddy, looks like you misunderstood me, I just wanted to say,  as a contributor it is our project too, and we can build something together, anyways I will not comment further.

**Comment by cyrilletuzi** [comment]
@santoshyadav198613 you're welcome, your message helped me to clarify my opinion. :)

**Comment by cyrilletuzi** [comment]
I talked to a friend, and he thinks I may take things a little too seriously and personally, as it often happens. 😆 I really thought it was just an oversight, so I was quite taken aback by an answer I didn't expected. So I'll close the issue and let the Angular team manage this their way.
