### ISSUE TITLE
Content-Disposition header is not available

### ISSUE THREAD

**Issue by zendu** [angular/angular#37836]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common/http

### Is this a regression?

 Not sure

### Description

 Content-Disposition header is not returned by response.headers even when server sends it.

## 🔬 Minimal Reproduction

 
     return this.http.get(this.formatUrl(url), {
      headers: httpOptions.headers,
      params: httpOptions.params,
      responseType: 'blob',
      observe: 'response'
    }).pipe(
      map((response: HttpResponse<Blob>) => {
        // header looks like --> Content-Disposition: attachment; filename="filename.extn"
        if (response.headers.has(ContentDispositionHeaderName)) {
          // select value filename="filename.extn" --- *THIS CODE IS NEVER HIT*
          const fileNameValue = response.headers.getAll(ContentDispositionHeaderName).filter(x => x.startsWith('filename='))[0];
          if (fileNameValue) {
            // extract value --> filename.extn
            const fileName = fileNameValue.split('=').map(x => x.replace('"', ''))[1];
            if (fileName) {
              return new File([response.body], fileName);
            }
          }
        }

        return response.body;
      })
    );

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.1.4
Node: 12.18.1
OS: win32 x64

Angular: 9.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.4
@angular-devkit/build-angular      0.901.4
@angular-devkit/build-ng-packagr   0.901.4
@angular-devkit/build-optimizer    0.901.4
@angular-devkit/build-webpack      0.901.4
@angular-devkit/core               9.1.4
@angular-devkit/schematics         9.1.4
@ngtools/webpack                   9.1.4
@schematics/angular                9.1.4
@schematics/update                 0.901.4
ng-packagr                         9.1.2
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0

</code></pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment]
This has nothing to do with Angular but rather with how browsers expose headers. See https://stackoverflow.com/questions/45892875/unable-to-view-content-disposition-headers-in-angular4-get-response and many other similar questions
