### ISSUE TITLE
Angular 10 library publish does not publish while ivy enabled.

### ISSUE THREAD

**Issue by mukundkatpatal** [angular/angular#37844]
### Description

Hi All,
I am following this matrix https://gist.github.com/LayZeeDK/61caba93df1ec1a0788c94a973c8dfac
 My Application is in angular 10 now with ivy enabled. I am trying to enable ivy for my library project.
The build and test is success but when I try to publish the package, I get below error
## 🔥 Exception or Error
<pre><code>
x64\npm.cmd publish dist/components --tag beta"_
**ERROR: Trying to publish a package that has been compiled by Ivy. This is not allowed.
Please delete and rebuild the package, without compiling with Ivy, before attempting to publish.**
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>

  _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 10.0.0
Node: 12.13.0
OS: win32 x64

Angular: 10.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.0
@angular-devkit/build-angular      0.1000.0
@angular-devkit/build-ng-packagr   0.1000.0
@angular-devkit/build-optimizer    0.1000.0
@angular-devkit/build-webpack      0.1000.0
@angular-devkit/core               10.0.0
@angular-devkit/schematics         10.0.0
@ngtools/webpack                   10.0.0
@schematics/angular                10.0.0
@schematics/update                 0.1000.0
ng-packagr                         10.0.0
rxjs                               6.5.5
typescript                         3.9.5
webpack                            4.43.0

<code>

</code></pre>

**Comment by petebacondarwin** [comment]
That is correct. You should only publish libraries compiled by ViewEngine for the moment.
If you have built your library with ivy enabled; or processed the distributable library files via ngcc then the library contains ivy generated code that should not be pushed to npm.

Running `yarn build --prod` on your library will build it in ViewEngine mode, and that is what you should publish to npm.

More information is available here: https://angular.io/guide/creating-libraries#publishing-your-library

**Comment by mukundkatpatal** [comment]
https://gist.github.com/LayZeeDK/61caba93df1ec1a0788c94a973c8dfac

Thank you. @petebacondarwin.  So the above link is incorrect?

**Comment by petebacondarwin** [comment]
I am not quite sure what that matrix is describing but it looks to me like line 9 is not valid.
And furthermore, anything past v10 is just guessing, since we have not released those versions yet.
