### ISSUE TITLE
Angular - PWA 

### ISSUE THREAD

**Issue by Crtac** [angular/angular#37848]
Hello there,

I have problem with redirecting in PWA, in normal mode it work's like it need to work, but in installed mode when I login in app and then press "X" token lose valid value and then when I again open app it needs to redirect on login page but it lose compass somewhere and I need to press "F5" to get normal look.

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
