### ISSUE TITLE
i18n example errors while extracting

### ISSUE THREAD

**Issue by Theraggon** [angular/angular#37849]
# 📚 Docs or angular.io bug report

### Description

 After downloading i18n example from https://angular.io/generated/zips/i18n/i18n.zip and  extracting it using 7-zip it shows warnings and some extracted files are broken like missing half a file with gibberish at the end.

Same with winRAR.

### What's the affected URL?**
 
https://angular.io/generated/zips/i18n/i18n.zip 

### Reproduction Steps**

download https://angular.io/generated/zips/i18n/i18n.zip
7-zip Test archive or extract

## 🔥 Exception or Error

image with 7-Zip errors:
https://imgur.com/5wI7WNe

End of angular.json file:
<pre>
<code>
            "fr": {
              "localize": [
                "fr"
              ]
            }
          }
        },
        "
  dm         "output     }
  tt
a vl
d     hent    "oulzer": true,
              m    r          ],
        "maximumWa e,
            ftMsiowser",
  e,
       T        "max.tob  "namedChunks"lor"
      "oulzer": true,
 
</code>
</pre>

## 🌍  Your Environment

Windows 10
7-Zip 19.00

**Comment by petebacondarwin** [comment]
I just tried downloading the zip on OS/X and it cannot be expanded there either. So it appears this is no OS specific and that we are generating a corrupt zip file.

**Comment by petebacondarwin** [comment]
It also fails on `next.angular.io` but is OK on `v8.angular.io`...

**Comment by rockument69** [comment]
On macOS Mojave (10.14.6) I get `Unable to expand "i18n.zip" into "Downloads". (Error 2 - No such file or directory.)`. The live example shows up in stackblitz OK.

**Comment by petebacondarwin** [comment]
It's definitely something to do with our zip generation. I will take a quick look later today.

**Comment by petebacondarwin** [comment]
Should be fixed by #37947
