### ISSUE TITLE
TSLint has been deprecated in favor of ESLint

### ISSUE THREAD

**Issue by GlauberF** [angular/angular#37843]
# 🚀 feature request
Migrate TSLint to ESLint

### Relevant Package
@angular/....

### Description
as we know tslint has been discontinued, you can see more details here:
https://github.com/palantir/tslint/issues/4534

### Describe the solution you'd like
in the next versions that Angular releases, upgrade from TSLint to ESLint.
It has a cli for this, where it could be used https://github.com/typescript-eslint/tslint-to-eslint-config

**Comment by pkozlowski-opensource** [comment]
This is already tracked in https://github.com/angular/angular-cli/issues/13732 , closing as a duplicate
