### ISSUE TITLE
Angular page - twitter and github icons are not showing in header

### ISSUE THREAD

**Issue by vesivagu** [angular/angular#37847]
![image](https://user-images.githubusercontent.com/25737946/86128192-ac18fe00-bafe-11ea-95a4-58badbd59aa9.png)

IE 11
windows 10

**Comment by saifabusaleh** [comment]
Hi, 
Can I take this issue?

**Comment by petebacondarwin** [comment]
@saifabusaleh - sure, please do have a go. Thanks
