### ISSUE TITLE
Type guards in template

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular#37851]
# 🚀 feature request
 

### Description
Use [in type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#using-the-in-operator), [instanceof type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#instanceof-type-guards) and [typeof type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#typeof-type-guards) in Angular template.

---

Use case demonstrated in react jsx:

```jsx
declare const data: Date | string;
return <div>date message is {data instanceof Date ? formatDate(data) : data}</div>
```

```jsx
declare const data: number | string;
return <div>date message is {typeof data === 'number' ? formatNumber(data) : data}</div>
```

Here is just the simplest example without nesting.
In the scenario of nested multi-layer ngFor ngSwitch data display, if NgTemplate supports it, we can omit the function of writing data conversion, which will be very convenient.

```jsx
type Data = Array<{
  classRoomId: string;
  students: Array<{
    name: string;
    value: Array<{
      data: string | Date;
    }>;
  }>;
}>;
declare const data: Data;

declare function formatDate(x: Date): string;

const jsxWithInstanceofTypeGuard = (
  <div>
    {data.map(classRoom => (
      <>
        {classRoom.classRoomId}
        <ul>
          {classRoom.students.map(({ name, value }) => (
            <>
              name:{name} value:
              {value.map(x =>
                x.data instanceof Date ? formatDate(x.data) : x.data,
              )}
            </>
          ))}
        </ul>
      </>
    ))}
  </div>
);

function transformData(data: Data) {
  return data.map(classRoom => ({
    ...classRoom,
    students: classRoom.students.map(({ name, value }) => ({
      name,
      value: value.map(v =>
        v.data instanceof Date
          ? ({
              type: 'Date',
              v,
            } as const)
          : ({
              type: 'number',
              v,
            } as const),
      ),
    })),
  }));
}
const jsxWithoutInstanceofTypeGuard = (
  <div>
    {transformData(data).map(classRoom => (
      <>
        {classRoom.classRoomId}
        <ul>
          {classRoom.students.map(({ name, value }) => (
            <>
              name:{name} value:
              {value.map(x => (x.type === 'Date' ? formatDate(x.v.data) : x.v.data))}
            </>
          ))}
        </ul>
      </>
    ))}
  </div>
);
```

The above is a small example demonstrated with react. If we want to prevent the use of *instanceof type guard* in the template, we need to add a lot of code to handle data conversion.

**Comment by alxhub** [comment]
I'm going to close this as a feature request that we're not going to target in isolation.

We do plan on undertaking a survey of template syntax in general, and that will include various operations including `instanceof` or `typeof`. We want to make sure we continue our thoughtful approach to the design of template syntax.
