### ISSUE TITLE
Choose injector when creating components

### ISSUE THREAD

**Issue by pauldraper** [angular/angular#37857]
# 🚀 feature request

### Relevant Package

@angular/core

### Description

Often, I'd like to inject different values into different components. For example, have a component tree with `color: 'BLUE` injected, and another component tree with `color: 'RED'` injected.

This sort of desire comes up in a lot of different forms. Sometimes the component tree exist contemporaneously; other times they don't (e.g. router-like functionality).

The point of dependency injection is to not code against fixed values, however Angular's DI currently makes it cumbersome to adjust the injector.

### Describe the solution you'd like

Specify the injector when creating the component. Example syntax:

```ts
export class RootComponent {
  constructor(private readonly injector: Injector) {}
  readonly blueProviders: StaticProviders[] = [{ provide: COLOR, useValue: 'BLUE' }];
  readonly blueInjector = Injector.create(this.blueProviders, this.injector);
}
```

```html
<my-component [@injector]="blueInjector"></my-component>
```

or

```html
<my-component [@providers]="blueProviders"></my-component>
```

### Describe alternatives you've considered

1. Inject an `Observable`. However that complicates client code, and requires components to understand how to handle changes.

2. Use non-template code to dynamically create components. However, lifecycles methods, etc. make the approach complex in general.

3. Use `*ngComponentOutlet`. However, like (2), that removes the ability to use inputs with the child component, and it requires explicitly adding components to module entry points.

**Comment by djleonskennedy** [comment]
@pauldraper you can use component wrappers with different providers, i had component for getting addresses with different logic required in final it looks like

`
<address value="data"></ address>

<address-authority-inject-wrapper>
    <address value="data"></ address>
</address-authority-inject-wrapper>
`

wrapper just have component level provider

works nice :)

**Comment by Airblader** [comment]
@djleonskennedy A wrapping component creates DOM noise and CSS burden, though, and making it dynamic to have something like

```
<use-injector [injector]="blueInjector">
  <my-component></my-component>
</use-injector>
```

doesn't work since `use-injector` has to statically define its providers and cannot reference so from an input. So you'd have to create different wrapper components for every injector, which then becomes problematic if you build your injector somewhat dynamically as well (which I think is what @pauldraper wants to do).

My first thought here was a structural directive like

```
<my-component *useInjector="blueInjector"></my-component>
```

But this actually turns out not to really lead anywhere either.

**Comment by pauldraper** [comment]
Using directive-wrapping instead of component-wrapping can overcome the DOM/CSS issue.

Yes the larger issue is that the directive/component-wrapping approach only works if you build enough components to enumerate all possible values (e.g. `RedComponent` and `BlueComponent`, but if you want an arbitrary `color: '#51230f'`, you are out of luck).

---

More philosophically,

There is a static tree of (1) Directive/component selectors (2) component templates (3) injected values.

There is a dynamic tree of (1) Inputs (2) injected Observables (3) dynamically created components (`ngComponentOutlet`, router).

I want to increase what can be done dynamically.

---

For example, suppose an app has most routes under:

    /site/:siteId

and that use of site ID (or account ID, organization ID) is ubiquitous.

The router injects `ActivatedRoute` which has an observable with the `siteId` value.

However, that means that *every* component using `siteId` must consume it as an Observable. It'd be more convenient if I could just assume it's constant (and re-create components when it changes).

I think the currently best approach is `ngComponentOutlet`, though that the mentioned downsides.

I suppose one to solve this is to extends `ngComponentOutlet`: support inputs (`ngComponentInputs`) and ngOnChanges and maybe change detection strategy in ngComponentOutlet. It's a more awkward calling convention, requires entryComponents, and can't use input intellisense.

**Comment by Airblader** [comment]
> However, that means that every component using siteId must consume it as an Observable. It'd be more convenient if I could just assume it's constant (and re-create components when it changes).

For this you can access the snapshot and use a route reuse strategy that always recreates the routed component instead of reusing it. You could also use things like CanActivate guards or resolvers to fully resolve objects and make them available to all components through a service provided on the routed component.

**Comment by pauldraper** [comment]
Those are some good ideas. Thanks @Airblader .

**Comment by pauldraper** [comment]
Related SO issue: https://stackoverflow.com/questions/62717425/angular-dependency-injection-through-input-property

```html
<ex-shape [shapeServiceInput]="rectangleShapeService" />
<ex-shape [shapeServiceInput]="ellipseShapeService" />
<ex-shape [shapeServiceInput]="polygonShapeService" />
```

**Comment by pauldraper** [comment]
Also worth mentioning `NgComponentOutlet`. However it can't be used with Inputs.

**Comment by pauldraper** [comment]
A solution that allows injection of dynamic view values (doesn't allow specifying the Injector, but can inject values).

<details>
<summary>Code</summary>
```ts
import { BrowserModule } from "@angular/platform-browser";
import {
  Component,
  Directive,
  Input,
  TemplateRef,
  NgModule,
  VERSION,
  ViewContainerRef,
  EmbeddedViewRef,
  InjectionToken,
  Inject
} from "@angular/core";
import { Subject } from "rxjs";
import { distinctUntilChanged, scan } from "rxjs/operators";

export const EXAMPLE = new InjectionToken<string>("EXAMPLE");

@Directive({ selector: "[exampleValue]" })
export class ExampleValueDirective {
  value: string;
  readonly value$ = new Subject();

  @Input() set exampleValue(value: string) {
    this.value = value;
    this.value$.next(value);
  }
}

@Directive({ selector: "[exampleRender]" })
export class ExampleRenderDirective {
  constructor(
    private readonly template: TemplateRef<{}>,
    private readonly exampleValue: ExampleValueDirective,
    private readonly viewContainer: ViewContainerRef
  ) {
    this.render.subscribe();
  }

  private readonly render = this.exampleValue.value$.pipe(
    distinctUntilChanged(),
    scan(
      view => {
        if (view) {
          view.destroy();
        }
        return this.viewContainer.createEmbeddedView(this.template);
      },
      <EmbeddedViewRef<{}> | undefined>undefined
    )
  );
}

export function getExample(directive: ExampleValueDirective) {
  return directive.value;
}

@Directive({
  selector: "[example]",
  providers: [
    {
      provide: EXAMPLE,
      useFactory: getExample,
      deps: [ExampleValueDirective]
    }
  ]
})
export class ExampleDirective {}

@Component({
  selector: "leaf",
  template: `
    Injected value #{{ n }}: {{ example }}
  `
})
export class LeafComponent {
  constructor(@Inject(EXAMPLE) readonly example: string) {}

  @Input() n: number;
}

@Component({
  selector: "app",
  template: `
    <div [exampleValue]="color1">
      <leaf *exampleRender example [n]="1"></leaf>
    </div>
    <div [exampleValue]="color2">
      <leaf *exampleRender example [n]="2"></leaf>
    </div>
    <div>
      <button type="button" (click)="toggle()">Toggle</button>
    </div>
    <hr />
    Angular version: {{ VERSION.full }}
  `
})
export class AppComponent {
  readonly VERSION = VERSION;

  color1 = "blue";
  color2 = "red";

  toggle() {
    const tmp = this.color1;
    this.color1 = this.color2;
    this.color2 = tmp;
  }
}

@NgModule({
  imports: [BrowserModule],
  declarations: [
    AppComponent,
    ExampleDirective,
    ExampleValueDirective,
    ExampleRenderDirective,
    LeafComponent
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

https://stackblitz.com/edit/angular-25tawh
</details>

```html
<div [exampleValue]="color1">
  <leaf *exampleRender example [n]="1"></leaf>
</div>
```

The `exampleValue` directive would be superfluous if it were not for the feature regression in Angular 4 (#15998) where template directives aren't DI parents for the template.

**Comment by alberto-chiesa** [comment]
@pauldraper Excellent example! I have something like this in my projects, used for, basically, the same use case: I inject via directive or custom components a token that represents a styling (a "theme") for the application buttons.

This approach works for components and directives (their injectors are parent of their content), but NOT for structural directives, as you mentioned. This is really a shame, IMO, and should be fixed ASAP, because the hierarchy of Injectors is broken, when talking about structural directives:

```
<div [myButtonTheme]="'blue'">
  <my-button>This component will get 'blue' via Dependency Injection</my-button>
</div>

<div *myStructuralHeaderTheme="'blue'">
  <my-button>
    This component will NOT get any styling token via Dependency Injection,
    because someone decided myStructuralHeaderTheme's injector is not parent of myButton.
  </my-button>
</div>
```

Regarding the specifics of this issue, I don't think the required feature is needed, except for the requirement of the aforementioned issue #15998. Custom directives "providing" tokens seem to be (AFAICT) exactly what the OP is requesting.

**Comment by pauldraper** [comment]
Actually, structural directives seem to work as parents now.

I can inject `color1` into `<leaf></leaf>` with:

```html
<leaf *exampleRender="color1" example></leaf>
```

Full example:

```ts
import { BrowserModule } from "@angular/platform-browser";
import {
  Component,
  Directive,
  Input,
  TemplateRef,
  NgModule,
  VERSION,
  ViewContainerRef,
  InjectionToken,
  Inject,
  ViewRef
} from "@angular/core";

export const EXAMPLE = new InjectionToken<string>("EXAMPLE");

@Directive({ selector: "[exampleRender]" })
export class ExampleRenderDirective {
  constructor(
    private readonly template: TemplateRef<{}>,
    private readonly viewContainer: ViewContainerRef
  ) {}

  value!: string;

  private view!: ViewRef;

  set exampleRender(value: string) {
    this.value = value;
    if (this.view) {
      this.view.destroy();
    }
    this.view = this.viewContainer.createEmbeddedView(this.template);
  }
}

export function getExample(directive: ExampleRenderDirective) {
  return directive.value;
}

@Directive({
  selector: "[example]",
  providers: [
    {
      provide: EXAMPLE,
      useFactory: getExample,
      deps: [ExampleRenderDirective]
    }
  ]
})
export class ExampleDirective {}

@Component({
  selector: "leaf",
  template: `
    Injected value #{{ n }}: {{ example }}
  `
})
export class LeafComponent {
  constructor(@Inject(EXAMPLE) readonly example: string) {}

  @Input() n!: number;
}

@Component({
  selector: "app",
  template: `
    <div *exampleRender="color1" example>
      <leaf [n]="1"></leaf>
    </div>
    <div *exampleRender="color2" example>
      <leaf [n]="2"></leaf>
    </div>
    <div>
      <button type="button" (click)="toggle()">Toggle</button>
    </div>
    <hr />
    Angular version: {{ VERSION.full }}
  `
})
export class AppComponent {
  readonly VERSION = VERSION;

  color1 = "blue";
  color2 = "red";

  toggle() {
    const tmp = this.color1;
    this.color1 = this.color2;
    this.color2 = tmp;
  }
}

@NgModule({
  imports: [BrowserModule],
  declarations: [
    AppComponent,
    ExampleDirective,
    ExampleRenderDirective,
    LeafComponent
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

https://stackblitz.com/edit/angular-qsjthv?file=src%2Fapp.ts

**Comment by alberto-chiesa** [comment]
I tried it too, and it seems to work on Angular 11 on Stackblitz. I'm going to try it on our applications (currently being migrated from v9 to v11) to understand when/if the change was made.

Thanks @pauldraper for the hint!
