### ISSUE TITLE
No Provider for NgControl in sub component of Angular app

### ISSUE THREAD

**Issue by nchetbani** [angular/angular#37853]
I developed a custom input component with a custom control:

```
@Component({
	selector: 'input[custom-input]',
	template: `<ng-content></ng-content>`,
	providers: [
		{ provide: CustomControl, useExisting: CustomInput, multi: true }
	],
	host: {
		'(blur)': 'changeFocus(false)',
		'(focus)': 'changeFocus(true)',
		'(input)': 'onChange($event.target.value)'
	},
	inputs: [
		'required'
	]
})
export class CustomInput implements CustomControl<any>, ControlValueAccessor, DoCheck {

constructor(private elementRef: ElementRef, @Optional() @Self() public _ngControl: NgControl, private _renderer: Renderer2) {
		console.log(_ngControl) ;
		...
		...
}
```

As is shown above, in the constructor of my custom component I get an instance of the NgControl. In the AppComponent of my Angular app, I can get the NgControl instance (not null) for all the input field possessing a control

But when I try to use this component as imported module (*) I'm getting a null NgControl instance

(*) after build the custom component as a module (ng-packagr), then published it to my registry 

bellow my module code :

```
@NgModule({
    declarations: [
        CustomInput
    ],
    imports: [
        CommonModule,
        ReactiveFormsModule,
        FormsModule
    ],
    exports: [
        CustomInput
    ]
})
export class CustomInputModule { }
```

Any idea ?

**Comment by AndrewKushnir** [comment]
Hi @nchetbani, could you please create a repro using [Stackblitz](https://stackblitz.com/), so that we can perform further investigation? Thank you.

**Comment by AndrewKushnir** [comment]
Closing this ticket as there was not actionable repro provided. If the problem still exists, please create a new ticket and provide an repro, so that we can perform further investigation. Thank you.
