### ISSUE TITLE
angular中 @HostListener('window:load') Ie11 does not support it. How do you fix it?（ie11不支持，如何解决呢？）

### ISSUE THREAD

**Issue by yinuocode** [angular/angular#37868]
### angular9
```ts
@HostListener('window:load', ['$event']) 
onLoad(event: Event) {
	console.log(123);
} 
```
Ie11 does not support
Anyone know the solution?
(ie11不支持，有知道解决方案的吗？)

**Comment by pkozlowski-opensource** [comment]
I don't think it is IE11 specific as the same behaviour can be observed in other browsers: https://stackblitz.com/edit/angular-ivy-gqsxur?file=src%2Findex.html

The most probable issue here is that the `load` event fires _before_ Angular had a chance to register the corresponding event handler. This is just a theory, though, as we don't have any reproduce scenario. We need a minimal reproduce scenario to be able to understand and diagnose the issue.

**Comment by JiaLiPassion** [comment]
@yinuocode, please provide a reproduce repo. thanks.

**Comment by pkozlowski-opensource** [comment]
Going to close this issue as we haven't heard back with a reproduce scenario.
