### ISSUE TITLE
Dependency injection issues since upgrading to Angular 10

### ISSUE THREAD

**Issue by yusijs** [angular/angular#37878]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core (maybe)
I'm not 100% sure, but I would believe it's in @angular/core?

### Is this a regression?

Yes, the previous version in which this bug was not present was: ^9.1.0

### Description

 A clear and concise description of the problem...
This is a bit hard to pinpoint as it only happens when bundling in production mode. I've yet to see it materialize in dev mode, whereas in production it's 50/50. 

Basically, the build is perfectly fine. No errors, compilation is fine. Only two warnings due to UMD / commonjs modules. However, when starting the application in my browser, I get one of multiple errors:

- `Error: inject() must be called from an injection context`
- `NullInjectorError: R3InjectorError(t)[t -> InjectionToken ngrx/effects: Root Effects -> t -> t -> w -> w -> w]:  NullInjectorError: No provider for w!`
- Other times, MatDialogs refuse to open, and I get `Cannot read property 'selectors' of null `, where the list of the directives in the DOM has an empty slot at the end (null) where a provider would normally be.

## 🔬 Minimal Reproduction
I would love to give you a reproduction, but I'm not able to pinpoint the problem since it happens completely randomly and only for production builds. If you absolutely need our code, I'd need to verify with the business if that's alright. Shouldn't be a problem, but red tape.. :)

All the errors point to vendor-code (either ngrx, @angular/material or @angular/core).

E.g:
![image](https://user-images.githubusercontent.com/11261560/86286930-a3e8bd80-bbe7-11ea-8132-cf4d8bc61b47.png)

## 🔥 Exception or Error
<pre><code>

main-es2015.d078cc418c208dc5662c.js:1 NullInjectorError: R3InjectorError(t)[t -> InjectionToken ngrx/effects: Root Effects -> t -> t -> w -> w -> w]:
  NullInjectorError: No provider for w!
    at st.get (main-es2015.d078cc418c208dc5662c.js:1:577831)
    at ys.get (main-es2015.d078cc418c208dc5662c.js:1:623782)
    at ys.get (main-es2015.d078cc418c208dc5662c.js:1:623782)
    at ys.get (main-es2015.d078cc418c208dc5662c.js:1:623782)
    at tt (main-es2015.d078cc418c208dc5662c.js:1:576987)
    at Object.et (main-es2015.d078cc418c208dc5662c.js:1:577061)
    at Object.t.ɵfac [as factory] (main-es2015.d078cc418c208dc5662c.js:1:1240185)
    at ys.hydrate (main-es2015.d078cc418c208dc5662c.js:1:625952)
    at ys.get (main-es2015.d078cc418c208dc5662c.js:1:623735)
    at tt (main-es2015.d078cc418c208dc5662c.js:1:576987)
(anonymous) @ main-es2015.d078cc418c208dc5662c.js:1

</code></pre>

![image](https://user-images.githubusercontent.com/11261560/86286930-a3e8bd80-bbe7-11ea-8132-cf4d8bc61b47.png)

![image](https://user-images.githubusercontent.com/11261560/86288308-fdea8280-bbe9-11ea-93f8-29f7a48b5eca.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular: 10.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@angular/cdk                      10.0.0
@angular/cli                      10.0.0
@angular/material                 10.0.0
@ngtools/webpack                  10.0.0
@schematics/angular               10.0.0
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0

</code></pre>

**Anything else relevant?**

*Edit: Added another stacktrace

**Comment by meriturva** [comment]
Could you try to buid your project without minification?

**Comment by yusijs** [comment]
Which one would that be? optimization or buildOptimizer?

**Comment by yusijs** [comment]
Removed both of them, now I'm at this error:
![image](https://user-images.githubusercontent.com/11261560/86291339-24f78300-bbef-11ea-8002-be0e8a681804.png)

**Comment by meriturva** [comment]
See here: https://github.com/angular/angular/issues/37867

**Comment by yusijs** [comment]
Interesting.. I'll give that a shot then. Could it be the cli's invocation of ngcc that's causing these problems then?

**Comment by yusijs** [comment]
So, seems like it worked to run ngcc in postinstall, rather than via ng build.

**Comment by petebacondarwin** [comment]
@yusijs  Can you try updating to `@angular/cli` version 10.0.2 or newer? There was an issue with deduping modules, that might be related to this.

**Comment by yusijs** [comment]
I'll give it a go this evening or tomorrow morning!

**Comment by petebacondarwin** [comment]
Any update @yusijs ?

**Comment by yusijs** [comment]
Sorry @petebacondarwin - we've released to production this week, so it's been a bit mental. I'll update this evening or tomorrow and post back!

**Comment by petebacondarwin** [comment]
No worries. I hope the release went well

**Comment by yusijs** [comment]
It did, thanks. I got around to trying it out and it seemed to work as expected now. Will report back / reopen if it regresses at some point.

**Comment by robmcilroy** [comment]
I'm also facing the exact same error we are upgrading from A8.2->10. This is happening on ng-serve.

`main.ts:11 NullInjectorError: R3InjectorError(AppModule)[EffectsRootModule -> InjectionToken ngrx/effects: Root Effects -> XXX -> XXX -> HttpClient -> HttpClient -> HttpClient]: 
  NullInjectorError: No provider for HttpClient!`

This is with postInstall: ngcc in my package.json. If I wipe my node_modules and remove postInstall then pull down a fresh set of packages I get this error on ng serve

![image](https://user-images.githubusercontent.com/52494883/87782560-a7588780-c82a-11ea-97cc-14dabe1df778.png)

### Version Info
`Angular CLI: 10.0.3
Node: 12.8.0
OS: win32 x64

Angular: 10.0.3
... animations, cli, common, compiler, compiler-cli, core
... elements
Ivy Workspace: Yes

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1000.2
@angular-devkit/build-angular       0.1000.2
@angular-devkit/build-optimizer     0.1000.2
@angular-devkit/build-webpack       0.1000.2
@angular-devkit/core                10.0.2
@angular-devkit/schematics          10.0.3
@angular/cdk                        10.0.2
@angular/flex-layout                10.0.0-beta.32
@angular/forms                      10.0.2
@angular/language-service           10.0.2
@angular/material                   10.0.1
@angular/platform-browser           10.0.2
@angular/platform-browser-dynamic   10.0.2
@angular/platform-server            10.0.2
@angular/router                     10.0.2
@ngtools/webpack                    10.0.2
@schematics/angular                 10.0.3
@schematics/update                  0.1000.3
rxjs                                6.6.0
typescript                          3.9.6
webpack                             4.43.0`

### Full list of packages complied by ngcc
```
Compiling @angular/core : es2015 as esm2015
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/cdk/keycodes : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Compiling ngx-bootstrap/chronos : es2015 as esm2015
Compiling ngx-bootstrap/mini-ngrx : es2015 as esm2015
Compiling ngx-bootstrap/locale : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/cdk/observers : es2015 as esm2015
Compiling @angular/cdk/collections : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/cdk/platform : es2015 as esm2015
Compiling @angular/cdk/bidi : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/cdk/a11y : es2015 as esm2015
Compiling @angular/cdk/scrolling : es2015 as esm2015
Compiling @angular/cdk/portal : es2015 as esm2015
Compiling @angular/material/core : es2015 as esm2015
Compiling ngx-bootstrap/utils : es2015 as esm2015
Compiling @angular/cdk/overlay : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/material/form-field : es2015 as esm2015
Compiling ngx-bootstrap/positioning : es2015 as esm2015
Compiling @angular/flex-layout/core : es2015 as esm2015
Compiling ngx-bootstrap/component-loader : es2015 as esm2015
Compiling @angular/cdk/layout : es2015 as esm2015
Compiling @angular/material/button : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/core/testing : es2015 as esm2015
Compiling @ngrx/store : es2015 as esm2015
Compiling @angular/platform-server : es2015 as esm2015
Compiling @angular/cdk/text-field : es2015 as esm2015
Compiling @angular/material/icon : es2015 as esm2015
Compiling @angular/material/select : es2015 as esm2015
Compiling @angular/material/tooltip : es2015 as esm2015
Compiling @angular/platform-browser/testing : es2015 as esm2015
Compiling @angular/flex-layout/extended : es2015 as esm2015
Compiling @angular/flex-layout/flex : es2015 as esm2015
Compiling @angular/flex-layout/grid : es2015 as esm2015
Compiling @angular/material/dialog : es2015 as esm2015
Compiling @angular/material/input : es2015 as esm2015
Compiling @angular/cdk/accordion : es2015 as esm2015
Compiling @angular/material/divider : es2015 as esm2015
Compiling @angular/cdk/stepper : es2015 as esm2015
Compiling @angular/cdk/table : es2015 as esm2015
Compiling @angular/material/paginator : es2015 as esm2015
Compiling @angular/material/sort : es2015 as esm2015
Compiling @angular/cdk/tree : es2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : es2015 as esm2015
Compiling @angular/common/testing : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @asymmetrik/ngx-leaflet : module as esm5
Compiling @ngrx/effects : es2015 as esm2015
Compiling @ngx-translate/core : es2015 as esm2015
Compiling angular-draggable-droppable : es2015 as esm2015
Compiling angular-resizable-element : es2015 as esm2015
Compiling ngx-bootstrap/collapse : es2015 as esm2015
Compiling ngx-window-token : es2015 as esm2015
Compiling @angular/animations/browser/testing : es2015 as esm2015
Compiling @angular/cdk/clipboard : es2015 as esm2015
Compiling @angular/cdk/drag-drop : es2015 as esm2015
Compiling @angular/common/http/testing : es2015 as esm2015
Compiling @angular/elements : es2015 as esm2015
Compiling @angular/flex-layout : es2015 as esm2015
Compiling @angular/flex-layout/server : es2015 as esm2015
Compiling @angular/material/autocomplete : es2015 as esm2015
Compiling @angular/material/badge : es2015 as esm2015
Compiling @angular/material/bottom-sheet : es2015 as esm2015
Compiling @angular/material/button-toggle : es2015 as esm2015
Compiling @angular/material/card : es2015 as esm2015
Compiling @angular/material/checkbox : es2015 as esm2015
Compiling @angular/material/chips : es2015 as esm2015
Compiling @angular/material/datepicker : es2015 as esm2015
Compiling @angular/material/expansion : es2015 as esm2015
Compiling @angular/material/grid-list : es2015 as esm2015
Compiling @angular/material/icon/testing : es2015 as esm2015
Compiling @angular/material/list : es2015 as esm2015
Compiling @angular/material/menu : es2015 as esm2015
Compiling @angular/material/progress-bar : es2015 as esm2015
Compiling @angular/material/progress-spinner : es2015 as esm2015
Compiling @angular/material/radio : es2015 as esm2015
Compiling @angular/material/sidenav : es2015 as esm2015
Compiling @angular/material/slide-toggle : es2015 as esm2015
Compiling @angular/material/slider : es2015 as esm2015
Compiling @angular/material/snack-bar : es2015 as esm2015
Compiling @angular/material/stepper : es2015 as esm2015
Compiling @angular/material/table : es2015 as esm2015
Compiling @angular/material/tabs : es2015 as esm2015
Compiling @angular/material/toolbar : es2015 as esm2015
Compiling @angular/material/tree : es2015 as esm2015
Compiling @angular/platform-server/testing : es2015 as esm2015
Compiling @angular/router/testing : es2015 as esm2015
Compiling @asymmetrik/ngx-leaflet-draw : module as esm5
Compiling @ng-select/ng-select : es2015 as esm2015
Compiling @ngrx/effects/testing : es2015 as esm2015
Compiling @ngrx/store/testing : es2015 as esm2015
Compiling @ngx-translate/http-loader : es2015 as esm2015
Compiling @zxing/ngx-scanner : es2015 as esm2015
Compiling angular-calendar : es2015 as esm2015
Compiling angular-gridster2 : es2015 as esm2015
Compiling angular-user-idle : es2015 as esm2015
Compiling jw-bootstrap-switch-ng2 : es2015 as esm2015
Compiling ng2-charts : es2015 as esm2015
Compiling ngx-bootstrap/accordion : es2015 as esm2015
Compiling ngx-bootstrap/alert : es2015 as esm2015
Compiling ngx-bootstrap/buttons : es2015 as esm2015
Compiling ngx-bootstrap/carousel : es2015 as esm2015
Compiling ngx-bootstrap/datepicker : es2015 as esm2015
Compiling ngx-bootstrap/dropdown : es2015 as esm2015
Compiling ngx-bootstrap/modal : es2015 as esm2015
Compiling ngx-bootstrap/pagination : es2015 as esm2015
Compiling ngx-bootstrap/popover : es2015 as esm2015
Compiling ngx-bootstrap/progressbar : es2015 as esm2015
Compiling ngx-bootstrap/rating : es2015 as esm2015
Compiling ngx-bootstrap/sortable : es2015 as esm2015
Compiling ngx-bootstrap/tabs : es2015 as esm2015
Compiling ngx-bootstrap/timepicker : es2015 as esm2015
Compiling ngx-bootstrap/tooltip : es2015 as esm2015
Compiling ngx-bootstrap/typeahead : es2015 as esm2015
Compiling ngx-clipboard : es2015 as esm2015
Compiling ngx-currency : es2015 as esm2015
Compiling ngx-dropzone-wrapper : es2015 as esm2015
Compiling ngx-image-cropper : es2015 as esm2015
```

Any ideas on resolving this?

**Comment by petebacondarwin** [comment]
@robmcilroy it is pretty impossible to debug this sort of thing without a reproduction. Could you try to cut down your project to the minimum that still fails and share it with us in a new issue?
I am closing this issue as the original problem has been resolved.
