### ISSUE TITLE
Failed to set the 'responseType' property on 'XMLHttpRequest'

### ISSUE THREAD

**Issue by haseebahmed7** [angular/angular#37875]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/http

### Is this a regression?
Yes, the previous version might have had this bug. I can see this being discussed by people in 2018 on Stackoverflow.

### Description
From the research that I did, this seems to happening if one of the JS assets on your page is making a synchronous request. Sometimes, a tracking library included on the page is making synchronous calls and is messing up with the angular HTTP requests.

You can find related questions here:

- https://stackoverflow.com/questions/49666138/not-able-to-use-httpclient-in-angular-5/52158459#comment110802776_52158459
- https://stackoverflow.com/questions/49048060/subscribing-to-httpclient-get-method-results-in-an-xmlhttprequest-error/62656061#62656061

## 🔬 Minimal Reproduction
For minimal reproduction, please refer to the repo here: https://github.com/haseebahmed7/angular-bugrepro-37875

## 🔥 Exception or Error
<pre><code>
Failed to set the 'responseType' property on 'XMLHttpRequest': The response type cannot be changed for synchronous requests made from a document. error.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.6
Node: 10.15.0
OS: win32 x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cli                      8.0.6
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**
As soon as an incompatible (for the lack of a better word) script loads on the page, any HTTP calls being made by Angular HTTP Client start throwing the error mentioned above. I haven't come across any workaround but to remove that script which isn't always possible in a Production environment.

**Comment by JoostK** [comment]
This is a bug in the PearCommerce SDK.

They patch `XMLHttpRequest.open` with some interceptors:

```js
XMLHttpRequest.prototype.open = function(method, url, async, user, pass) {
        var _this = this;
        intercepts.forEach(function(_ref, index) {
          var _ref2 = _slicedToArray(_ref, 2)
            , criteria = _ref2[0]
            , handler = _ref2[1];
          criteria.readyState || (criteria.readyState = 4);
          var parsedUrl = parseUri(url)
            , matches = !0;
          if (matches && criteria.path) {
            var _matches = !1;
            criteria.path.forEach(function(_path) {
              _path instanceof RegExp ? _path.test(parsedUrl.path) && (_matches = !0) : parsedUrl.path == _path && (_matches = !0)
            }),
            _matches || (matches = !1)
          }
          if (matches && criteria.host && parsedUrl.host != criteria.host && (matches = !1),
          matches && criteria.method) {
            var _matches2 = !1;
            criteria.method.forEach(function(_method) {
              _method.toUpperCase() == method && (_matches2 = !0)
            }),
            _matches2 || (matches = !1)
          }
          matches && criteria.filter && !criteria.filter(parsedUrl) && (matches = !1),
          matches && (_this.recordingRequestBody || (_this.recordingRequestBody = !0,
          _this._send = _this.send,
          _this.send = function(body) {
            return this.requestBody = body,
            this._send(body)
          }
          ),
          0 == criteria.readyState ? handler.apply(_this, args) : _this.addEventListener("readystatechange", function() {
            if (criteria.readyState == this.readyState) {
              var _matches3 = !0;
              if (4 == criteria.readyState && _matches3 && criteria.status && -1 == criteria.status.indexOf(this.status) && (_matches3 = !1),
              _matches3) {
                for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++)
                  args[_key] = arguments[_key];
                handler.apply(this, args)
              }
            }
          }, !1))
        }),
        open.call(this, method, url, async, user, pass)
      }
```

The problem here is in the last line: `async` is not passed in an argument, so the parameter `async` is `undefined` here. Because it's explicitly provided as argument to the native `XMLHttpRequest.open` it's `undefined` value is interpreted as `false`, making it a synchronous request.

You can reproduce the issue with a little snippet:

```ts
setTimeout(() => {
    debugger;
    const xhr = new XMLHttpRequest();
    xhr.open('POST', 'http://google.com');
    xhr.responseType = 'json';
}, 2000);
```

The timeout is there to allow the PearCommerce patch to have initialized.
