### ISSUE TITLE
Prod Build Issue on IE only

### ISSUE THREAD

**Issue by sauravgaursmith** [angular/angular#37874]
How can I know which dependency is causing this issue? This errors shows following error in vendor.gghhh7787h777.ts file.. 
SCRIPT5022: No Provider for e! 
This issue is only IE specific.

I'm able to reproduce this issue with following command on local but error does not have complete stack trace. 
> ng serve -prod

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
