### ISSUE TITLE
sharedWorker.port.onmessage doesn't seem to be covered by NgZone

### ISSUE THREAD

**Issue by Dassderdie** [angular/angular#37885]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/zone.js

### Is this a regression?

I don't think so.

### Description

We are using a SharedWorker to synchronize data between multiple open tabs. We ran into some very weird behaviors where the displayed data would only change if you e.g. click on the page (= trigger for change detection).

We could finally track it down to the following root:
```ts
sharedWorker = new SharedWorker('shared-worker.js');
sharedWorker.port.onmessage = (event: MessageEvent) => {
    // here is some logic to transport the received data around the application via rxjs Subjects
    // these subjects didn't trigger change-detection anywhere
}
``` 

It could be fixed by letting it manually run in the zone (zone: NgZone)
```ts
sharedWorker = new SharedWorker('shared-worker.js');
sharedWorker.port.onmessage = (event: MessageEvent) => {
    this.zone.run(()=> {
        // here is some logic to transport the received data around the application via rxjs Subjects
       // now change-detection is everywhere triggered as expected
     });
}
``` 

## 🔬 Minimal Reproduction

I currently don#t have time to create a full reproduction in stackblitz - if necessary I will add it later on...

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.0
Node: 14.4.0       
OS: win32 x64      

Angular: 10.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@angular/cdk                      10.0.1
@angular/cli                      10.0.0
@ngtools/webpack                  10.0.0
@schematics/angular               10.0.0
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0

zone.js                               0.10.3
</code></pre>

**Comment by Dassderdie** [comment]
@JiaLiPassion https://github.com/angular/angular/issues/14027#issuecomment-652688802

**Comment by JiaLiPassion** [comment]
@Dassderdie, thanks for the issue, and you need to 
```
import 'zone.js/dist/zone';
import 'zone.js/dist/zone-patch-message-port'; // add this patch
```

in `polyfills.ts` to make it work.

**Comment by Dassderdie** [comment]
@JiaLiPassion Thank you very much. It is indeed working as expected with this additional import.

Short follow up: Shouldn't `zone-patch-message-port` be mentioned [here](https://github.com/angular/angular/tree/master/packages/zone.js#bundles) under optional patches?

**Comment by JiaLiPassion** [comment]
@Dassderdie , yeah, you are right, there are several other bundles are missing there too, I will add it to the document, thanks.
