### ISSUE TITLE
Angular Universal not rendering on server and keep showing the static version

### ISSUE THREAD

**Issue by MVDeveloper1** [angular/angular#37882]
# 🐞 bug report

### Affected Package

 I have no idea.

### Is this a regression?

 Did not tried with older versions.

### Description

 I implemented server side rendering in a new angular 9 project and when I test it running 
**npm run build:ssr && npm run serve:ssr**
everything works as expected, I check the source code that the browser received (view-source:) and is SSR.

But when I deploy the project to firebase hosting 
**npm run build:all && firebase deploy (or even firebase serve)**
and check the source code (view-source:) it is the static version, it just shows the app-root tag, despite not showing any errors on the console.

I don't know if it's an error in the implementation or a problem with a package or version.

## 🔬 Minimal Reproduction

I just generated a new project, added angular universal (ng add @nguniversal/express-engine). Init firebase, update public and rewrites fields in firebase.json, add the scripts to package.json (in src and functions folder) and add the ssr function (universal) to functions/src/index.ts .

## 🔥 Exception or Error
<pre><code>
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.9
Node: 12.16.1
OS: win32 x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.9
@angular-devkit/build-angular     0.901.9
@angular-devkit/build-optimizer   0.901.9
@angular-devkit/build-webpack     0.901.9
@angular-devkit/core              9.1.9
@angular-devkit/schematics        9.1.9
@angular/cli                      9.1.9
@ngtools/webpack                  9.1.9
@nguniversal/builders             9.1.1
@nguniversal/common               9.1.1
@nguniversal/express-engine       9.1.1
@schematics/angular               9.1.9
@schematics/update                0.901.9
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**src/package.json:**
<pre><code>
{
  "name": "diastour",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build:all": "npm run build:ssr && npm run build:functions",
    "build:functions": "npm run --prefix functions build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "dev:ssr": "ng run diastour:serve-ssr",
    "serve:ssr": "node dist/diastour/server/main.js",
    "build:ssr": "ng build --prod && ng run diastour:server:production",
    "prerender": "ng run diastour:prerender"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/forms": "~9.1.0",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/platform-server": "~9.1.0",
    "@angular/router": "~9.1.0",
    "@nguniversal/express-engine": "^9.1.1",
    "express": "^4.15.2",
    "parse5": "^6.0.0",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.0",
    "@angular/cli": "~9.1.0",
    "@angular/compiler-cli": "~9.1.0",
    "@angular/language-service": "~9.1.0",
    "@nguniversal/builders": "^9.1.1",
    "@types/express": "^4.17.0",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}
</code></pre>
**functions/package.json:**
<pre><code>
{
  "name": "functions",
  "scripts": {
    "lint": "tslint --project tsconfig.json",
    "build": "rm -r ./dist && cp -r ../dist . && tsc",
    "serve": "npm run build && firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "8"
  },
  "main": "lib/index.js",
  "dependencies": {
    "firebase-admin": "^8.10.0",
    "firebase-functions": "^3.6.1"
  },
  "devDependencies": {
    "tslint": "^5.12.0",
    "typescript": "^3.8.0",
    "firebase-functions-test": "^0.2.0"
  },
  "private": true
}
</code></pre>
**functions/index.ts:**
<pre><code>
import * as functions from 'firebase-functions';

export const universal = functions.https.onRequest((request, response) => {
    require(`${process.cwd()}/dist/diastour/server`).app(request, response);
});
</code></pre>
**firebase.json:**
<pre><code>
{
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ]
  },
  "hosting": {
    "public": "dist/diastour/browser",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "function": "universal"
      }
    ]
  }
}
</code></pre>

**All other Angular Universal files such as server.ts, main.ts, main.server.ts, are in defaults states and location**.

**Comment by tieppt** [comment]
Firebase hosting will serve static file first. therefore you need rename index.html in `dist` folder to something like this `index.original.html`
![984635F3-0664-4254-9049-53D9184BEC9A](https://user-images.githubusercontent.com/7151365/86326197-8a895500-bc6b-11ea-91ad-241671e512b9.png)

**Comment by MVDeveloper1** [comment]
@tieppt I have two dist folder in the project, one at the root level and the other one inside functions folder, as shown below in project struture.

**I renamed index.html at dist/diastour/browser to index.original.html, but it triggers an error when I run  'firebase serve'**
`Cannot find module 'C:\Users\Marcel Varela\Desktop\angular-universal3\diastour\functions/dist/diastour/server'`

I renamed back to index.html, and tried the other one at functions. 
So I renamed index.html at functions/dist/diastour/browser to index.original.html, and this time it did not show any errors but nothing changed, i keep getting the static version.

I do not have any other index.html at dist folders.

<pre>
<code>
\---diastour
    |   .editorconfig
    |   .firebaserc
    |   .gitignore
    |   angular.json
    |   browserslist
    |   firebase-debug.log
    |   firebase.json
    |   karma.conf.js
    |   package-lock.json
    |   package.json
    |   README.md
    |   server.ts
    |   tsconfig.app.json
    |   tsconfig.json
    |   tsconfig.server.json
    |   tsconfig.spec.json
    |   tslint.json
    |   
    +---.firebase
    |       ...
    |       
    +---dist
    |   \---diastour
    |       +---browser
    |       |       3rdpartylicenses.txt
    |       |       favicon.ico
    |       |       index.html
    |       |       main-es2015.4f8252425903bc9654cd.js
    |       |       main-es5.4f8252425903bc9654cd.js
    |       |       polyfills-es2015.f332a089ad1600448873.js
    |       |       polyfills-es5.177e85a9724683782539.js
    |       |       runtime-es2015.0dae8cbc97194c7caed4.js
    |       |       runtime-es5.0dae8cbc97194c7caed4.js
    |       |       styles.09e2c710755c8867a460.css
    |       |       
    |       \---server
    |               main.js
    |               
    +---e2e
    |   ...
    |           
    +---functions
    |   |   .gitignore
    |   |   package-lock.json
    |   |   package.json
    |   |   tsconfig.json
    |   |   tslint.json
    |   |   
    |   +---dist
    |   |   \---diastour
    |   |       +---browser
    |   |       |       3rdpartylicenses.txt
    |   |       |       favicon.ico
    |   |       |       index.html
    |   |       |       main-es2015.4f8252425903bc9654cd.js
    |   |       |       main-es5.4f8252425903bc9654cd.js
    |   |       |       polyfills-es2015.f332a089ad1600448873.js
    |   |       |       polyfills-es5.177e85a9724683782539.js
    |   |       |       runtime-es2015.0dae8cbc97194c7caed4.js
    |   |       |       runtime-es5.0dae8cbc97194c7caed4.js
    |   |       |       styles.09e2c710755c8867a460.css
    |   |       |       
    |   |       \---server
    |   |               main.js
    |   |               
    |   +---lib
    |   |       ...
    |   |       
    |   +---node_modules
    |   \---src
    |           index.ts
    |           
    +---node_modules
    \---src
        |   favicon.ico
        |   index.html
        |   main.server.ts
        |   main.ts
        |   polyfills.ts
        |   styles.scss
        |   test.ts
        |   
        +---app
        |   |   app-routing.module.ts
        |   |   app.component.html
        |   |   app.component.scss
        |   |   app.component.spec.ts
        |   |   app.component.ts
        |   |   app.module.ts
        |   |   app.server.module.ts
        |   |   
        |   +---about
        |   |       ...
        |   |       
        |   \---home
        |           ...
        |           
        +---assets
        |       .gitkeep
        |       
        \---environments
                environment.prod.ts
                environment.ts
</code>
</pre>

**Comment by MVDeveloper1** [comment]
Finally figured out how to solve the problem in this project.

**1:** Rename <code>index.html</code> in <code>dist</code> folder to `index.original.html` as @tieppt mentioned!
_**I DO NOT KNOW WHY THIS STEP IS NOT IN ANY DOCUMENTATION!**_

**2:** Remove the arrow function syntax from (https://github.com/angular/angularfire/blob/master/docs/universal/cloud-functions.md) I used in `index.ts`.

From this
<pre>
<code>export const universal = functions.https.onRequest((request, response) => {
    require(`${process.cwd()}/dist/projectname/server`).app(request, response);
});</code>
</pre>
To this
<pre>
<code>export const universal = functions.https.onRequest(require('../dist/projectname/server').app());</code>
</pre>

**3:** Change path of `server/main.js ` from `require(${process.cwd()}/dist/projectname/server)` to `require('../dist/projectname/server/main')`
