### ISSUE TITLE
ngcc: unable to process libary

### ISSUE THREAD

**Issue by chrisaige** [angular/angular#37884]
# 🐞 bug report

### Affected Package
@angular/cli || ngcc || ng-package

### Is this a regression?

Worked with Angular 9 (IVY enabled)

### Description

When updating our project to Angular 10 we are unable to build the library that manages general UI components for our company (https://github.com/porscheinformatik/material-addons). 
ngcc fails to compile angular material Components for our project and that in turn then leads the build tobe unable to resolve our Components.

## 🔬 Minimal Reproduction
git clone https://github.com/chrisaige/angular-ivy-example
npm i

-> should display the ngcc errors

ng serve example --prod 

-> should display that compontens from "porscheinformatik/material-addons" are missing

## 🔥 Exception or Error
Thats what the ngcc spits out when you run an npm i
<pre><code>
Error: Failed to compile entry-point @porscheinformatik/material-addons (esm2015 as esm2015) due to compilation errors:
node_modules/@porscheinformatik/material-addons/node_modules/@angular/material/menu/menu-module.d.ts:14:22 - error NG6002: Appears in the NgModule.imports of ToolbarModule, but could not be resolved to an NgModule class.

This likely means that the library (@angular/material/menu) which declares MatMenuModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and upda
te if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

14 export declare class MatMenuModule {
                        ~~~~~~~~~~~~~
node_modules/@porscheinformatik/material-addons/node_modules/@angular/material/toolbar/toolbar-module.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of ToolbarModule, but could not be resolved to an NgModule class.

This likely means that the library (@angular/material/toolbar) which declares MatToolbarModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, an
d update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

8 export declare class MatToolbarModule {
                       ~~~~~~~~~~~~~~~~
node_modules/@porscheinformatik/material-addons/esm2015/lib/toolbar/toolbar.module.js:11:14 - error NG6003: Appears in the NgModule.exports of MaterialAddonsModule, but itself has errors

11 export class ToolbarModule {
                ~~~~~~~~~~~~~

Compiling @angular/material/datepicker : esm2015 as esm2015
</code></pre>


**Anything else relevant?**
Currently I have IVY disabled, so I could complete the update to Angular 10, but it would be nice to get this resolved, is it a problem with our library?

**Comment by JoostK** [comment]
Based on this path:

```
node_modules/@porscheinformatik/material-addons/node_modules/@angular/material
```

It looks like you have multiple versions of `@angular/material` installed, where the "nested" version is not processed.

**Comment by chrisaige** [comment]
Thats correct.

https://github.com/porscheinformatik/material-addons/blob/master/projects/material-addons/package.json

I will move them to the peer dependencies and check if that solves the problem :) thanks for your help

**Comment by chrisaige** [comment]
@JoostK it solved the issue. Thanks I would have never found the issue 😄
