### ISSUE TITLE
Automatically reduce number of placeholder comment nodes for ngIf and ngSwitch

### ISSUE THREAD

**Issue by mikebolt** [angular/angular#37880]
# 🚀 feature request

### Relevant Package
https://github.com/angular/angular/blob/master/packages/common/src/directives/ng_switch.ts

### Description

When using ngIf or ngSwitch the framework adds comment nodes to the DOM that act as placeholders. This can become a performance issue, for example with a large switch block (50 cases) inside a component that is repeated many times (1000+). Each inactive switch case has a placeholder comment node for each 

In some manual tests I did, the chrome memory profiler showed that there were > 13000 comment nodes, and most of them were from a single ngSwitch inside a table cell component (I tested this by removing all the cells). This accounted for over 4% of total memory consumption in a large app. According to a theory of mine this will also slow down other actions on the page due to the increased DOM size which decreases the cache locality of non-comment elements.

### Describe the solution you'd like

I have a theory that the framework can automatically skip creating comment nodes that are unnecessary. For ngSwitch, no comment nodes should be necessary if there are no "interleaved" elements or text content between the switch cases. If there is only one "interleaved" thing, then only one comment node should be necessary to keep track of the location of the inactive group of cases.

The same trick should also work for ngIf, with the caveat that we still need placeholder comment nodes unless the compiler knows that the if blocks are mutually exclusive, and also they don't have content between them.

I hope this makes sense, but please let me know if I can clarify anything. I'm sure there are other good solutions too, so I would like to start some brainstorming.

**Comment by pkozlowski-opensource** [comment]
We've tried this in the past and the results weren't great for 2 main reasons:
* without a marker comment node we had to do more runtime processing (go over internal data structures to determine position of nodes to insert in the DOM);
* the code mentioned above was getting really complicated resulting in increased cost of maintenance _and_ increased bundle size.

So yes, you are right in saying that creating comment nodes has cost. But not having them isn't free either and there are just different tradeoffs.

Based on the experience from previous experiments we are not planning changes / revisiting of the comments node creation. We might re-consider this in the future but for this to happen someone would have to demonstrate that it is possible to change the current DOM mutation part in the way that comment nodes are not needed _and_ we don't increase code size / runtime processing time.

**Comment by mikebolt** [comment]
Thanks for the info. How can I find the PR or branch with those changes?

**Comment by pkozlowski-opensource** [comment]
> Thanks for the info. How can I find the PR or branch with those changes?

@mikebolt here is the PR that removed marker comment nodes from ivy: #21638. And this is the one that added them back: #24346

**Comment by mikebolt** [comment]
Thanks. I may try to make a change that only affects ngSwitch, but I will close this issue.
