### ISSUE TITLE
NodeInvocationException: Uncaught (in promise): Error: Injector has already been destroyed. Error: Injector has already been destroyed.

### ISSUE THREAD

**Issue by CL-BayanAbuawad** [angular/angular#37888]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/platform-server

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8

### Description
I am using Angular Universal with .net core 2.2 and after migrating to Angular 9 I have this weird issue that on first website load (it does not matter what page) the SSR works perfectly but after navigation to another page and then refreshing I get this error, if I refresh again the websites work without SSR.

removing the **Destroy** of **NgModuleRef** instance solves the problem.

This is my code for the **main.server.ts**
```
import '@angular/localize/init';
import 'zone.js/dist/zone-node';
import 'reflect-metadata';
import { INITIAL_CONFIG, platformDynamicServer, PlatformState } from '@angular/platform-server';
import { APP_BASE_HREF } from '@angular/common';
import { enableProdMode, ApplicationRef, NgZone } from '@angular/core';
import { provideModuleMap } from '@nguniversal/module-map-ngfactory-loader';
import { createServerRenderer, RenderResult } from 'aspnet-prerendering';
import { SSRResponseStatusCodeService } from './app/services/SSRResponseStatusCode.service';
import { first } from 'rxjs/operators';
import * as cache from 'memory-cache';
export { AppServerModule } from './app/app.server.module';

enableProdMode();

export default createServerRenderer(params => {
	const { AppServerModule, AppServerModuleNgFactory, LAZY_MODULE_MAP } = (module as any).exports;


	const providers = [
		provideModuleMap(LAZY_MODULE_MAP),
		{ provide: INITIAL_CONFIG, useValue: { document: params.data.originalHtml, url: params.url } },
		{ provide: APP_BASE_HREF, useValue: params.baseUrl },
		{ provide: 'BASE_URL', useValue: params.origin + params.baseUrl }
	];

	const cachedEntry = cache.get(params.url);
	if (cachedEntry) {
		return new Promise<RenderResult>((resolve) => {
			resolve(cachedEntry);
		})
	}

	const renderPromise = AppServerModuleNgFactory
		? /* AoT */ platformDynamicServer(providers).bootstrapModuleFactory(AppServerModuleNgFactory)
		: /* dev */ platformDynamicServer(providers).bootstrapModule(AppServerModule);

	return renderPromise.then(moduleRef => {
		const appRef: ApplicationRef = moduleRef.injector.get(ApplicationRef);
		const state = moduleRef.injector.get(PlatformState);
		const zone = moduleRef.injector.get(NgZone);

		// this will get the instance of the HttpStatusCodeService created for this request.
		const statusCodeService = moduleRef.injector.get(SSRResponseStatusCodeService);

		return new Promise<RenderResult>((resolve, reject) => {
			zone.onError.subscribe((errorInfo: any) => reject(errorInfo));
			appRef.isStable.pipe(first(isStable => isStable))
				.subscribe(() => {
					// Because 'onStable' fires before 'onError', we have to delay slightly before
					// completing the request in case there's an error to report
					setImmediate(() => {
						const result = {
							html: state.renderToString(),
							// this will get the currently set status code and return it along with the prerendered html string
							statusCode: statusCodeService.getStatusCode()
						}
						cache.put(params.url, result, 20 * 60 * 1000);
						resolve(result);
                                                //REMOVING this destroy will solve the problem for angular 9
						moduleRef.destroy();
					});
				});
		});
	});
});
```

## 🔥 Exception or Error
<pre><code>
NodeInvocationException: Uncaught (in promise): Error: Injector has already been destroyed. Error: Injector has already been destroyed.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.9
Node: 12.13.1
OS: win32 x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.901.9
@angular-devkit/build-angular              0.901.9
@angular-devkit/build-optimizer            0.901.9
@angular-devkit/build-webpack              0.901.9
@angular-devkit/core                       9.1.9
@angular-devkit/schematics                 9.1.9
@angular/cdk                               9.2.4
@angular/cli                               9.1.9
@angular/flex-layout                       9.0.0-beta.31
@angular/material                          9.2.4
@ngtools/webpack                           9.1.9
@nguniversal/aspnetcore-engine             9.1.1
@nguniversal/builders                      9.1.1
@nguniversal/common                        9.1.1
@nguniversal/express-engine                9.1.1
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        9.1.9
@schematics/update                         0.901.9
rxjs                                       6.5.5
typescript                                 3.8.3
webpack                                    4.43.0
</code></pre>

**Comment by pkozlowski-opensource** [comment]
@CL-BayanAbuawad I'm afraid that we will need some kind of a reduced reproduce scenario as it is very hard to say what might be going on based on the information provided.

**Comment by CL-BayanAbuawad** [comment]
@pkozlowski-opensource thanks for your replay, I will work on one soon

**Comment by CL-BayanAbuawad** [comment]
@pkozlowski-opensource added this repo:
https://github.com/CL-BayanAbuawad/ng9-ssr-destroy-issue

some after trying to recreate the issue with a newly created project I was able to detect what is causing to this issue, but still, I don't understand why this is happening.

if you check the repo project I created a base angular component with this code:
page-base.component.ts
```
import { Injector, ElementRef } from '@angular/core';
import { appInjector } from '../utils/angular-injector.utils';
import { StatusCodeService } from '../services/status-code.service';

export class BasePageComponent {
  protected statusCodeService: StatusCodeService;
  constructor(protected statusCode: number) {
    this.statusCodeService = appInjector.get(StatusCodeService);
    this.statusCodeService.setStatusCode(statusCode);
  }
}

```
inside the component, I am using appInjector wish inject the singleton services (only rooted services).

angular-injector.utils.ts
```
import { Injector } from '@angular/core';

/**
 * Allows for retrieving singletons using `AppInjector.get(MyService)` (whereas
 * `ReflectiveInjector.resolveAndCreate(MyService)` would create a new instance
 * of the service).
 */
export let appInjector: Injector;

/**
 * Helper to set the exported {@link AppInjector}, needed as ES6 modules export
 * immutable bindings (see http://2ality.com/2015/07/es6-module-exports.html) for
 * which trying to make changes after using `import {AppInjector}` would throw:
 * "TS2539: Cannot assign to 'AppInjector' because it is not a variable".
 */
export function setAppInjector(injector: Injector) {
  if (!appInjector) {
    appInjector = injector;
  }
}
```
and I am initializing the injector in 
app.component.ts
```
import { Component, Injector } from '@angular/core';
import { setAppInjector } from './utils/angular-injector.utils';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  constructor(public injector: Injector) {
    setAppInjector(injector);
  }
}
```

this used to work perfect in Angular 8 project, I started to get the issue when I updated to angular 9

Thanks in advance.

**Comment by emondora** [comment]
Same problem in Angular 9 and 10 project at Server Side Rendering.
When I extend the BaseComponent which has an injector.get() in the contrustor,  If frequently visit the server side rendering page, ocassionally will throw the error "Uncaught (in promise): Error: Injector has already been destroyed."
![ng](https://user-images.githubusercontent.com/2391113/90580820-5b6b7a80-e1fc-11ea-9718-3d5ebdb82589.png)

**Comment by hanstf** [comment]
@CL-BayanAbuawad do you find the solution for this? I have exactly the same issue

**Comment by CL-BayanAbuawad** [comment]
@hanstf 
for me, I removed the moduleRef.destroy(); in order to solve the problem, I am not sure what it does depply so I dont suggest it, but the project is working for me perfectly without it for now, and i am still waiting for a solution fro 
![image](https://user-images.githubusercontent.com/58811253/94118528-554d6700-fe56-11ea-8611-2518663d7546.png)

@pkozlowski-opensource any updates on this?

**Comment by chakrachi** [comment]
same issue here after angular 9+
' Injector has already been destroyed' (only in ssr)

**Comment by elementalPRESS** [comment]
I can confirm the problem for angular 11. The error happens occasionally.

**Comment by naveedahmed1** [comment]
I recently upgraded my `main.server.ts` to use `@nguniversal/aspnetcore-engine` and started receiving this error. 

**Below is my code using @nguniversal/aspnetcore-engine, which throws this error**

```
import { APP_BASE_HREF } from '@angular/common';
import { enableProdMode } from '@angular/core';
import { IEngineOptions, ngAspnetCoreEngine } from '@nguniversal/aspnetcore-engine';
import { createServerRenderer } from 'aspnet-prerendering';
import 'es6-promise';
import 'es6-shim';
import 'reflect-metadata';
import 'zone.js/dist/zone-node';
import { AppServerModule } from './app/app.module.server';

enableProdMode();

export default createServerRenderer(params => {

  // Platform-server provider configuration
  const setupOptions: IEngineOptions = {
    appSelector: '<app-root></app-root>',
    ngModule: AppServerModule,
    request: params,
    providers: [
      { provide: APP_BASE_HREF, useValue: params.baseUrl },
      { provide: 'BASE_URL', useValue: params.origin + params.baseUrl },
      { provide: 'origin', useValue: params.origin }
    ]
  };

  return ngAspnetCoreEngine(setupOptions).then(response => {

    return ({
      html: response.html,
      globals: response.globals
    });

  });
});

```

**Below is the code that works without any issue:**

```
import { APP_BASE_HREF } from '@angular/common';
import { enableProdMode } from '@angular/core';
import { renderModule } from '@angular/platform-server';
import { createServerRenderer } from 'aspnet-prerendering';
import 'reflect-metadata';
import 'zone.js/dist/zone-node';
import { AppServerModule } from './app/app.module.server';

enableProdMode();

export default createServerRenderer(params => {
  const options = {
    document: params.data.originalHtml,
    url: params.absoluteUrl,
    extraProviders: [
      { provide: APP_BASE_HREF, useValue: params.baseUrl },
      { provide: 'BASE_URL', useValue: params.origin + params.baseUrl },
      { provide: 'origin', useValue: params.origin }
    ]
  };

  const renderPromise = renderModule(AppServerModule, options);

  return renderPromise.then((html) => {
    return {
      html: html
    }

  });
});
```

**Comment by naveedahmed1** [comment]
Is it related to IVY? I found this issue on Universal repo:

https://github.com/angular/universal/issues/1808

**Comment by alan-agius4** [comment]
@naveedahmed1, 

Can you please share a reproduction that I can take a look at?

**Comment by naveedahmed1** [comment]
@alan-agius4 I have already added you to Mustakbil repo, please comment out the code in `/src/main.server.ts` and uncomment the code block at the bottom of the file.

**Comment by alan-agius4** [comment]
Hi @naveedahmed1, I cloned the `Mustakbil-Angular` repo. However, I am failing to understand how to spawn the server and eventually get `createServerRenderer` invoked.

Can you please provide more context? Thanks.

**Comment by naveedahmed1** [comment]
Oh I'm sorry, its just Angular repo, let me create a demo project repo with visual studio. I hope you're familiar with running .Net Core projects.

**Comment by alan-agius4** [comment]
@naveedahmed1, thanks that would help. Yeah, I am familiar with dotnet.

**Comment by naveedahmed1** [comment]
@alan-agius4 I have added you to the repo, just clone the repo, restore dependencies and run project by pressing F5. If you see error `AggregateException: One or more errors occurred. (The NPM script 'build:ssr' exited without indicating success....)` this is a know issue in .Net Core, try pressing F5 few time and it should start working.

Please comment out the code in `ClientApp/src/main.server.ts` and uncomment the code block at the bottom of the same file.

**Comment by alan-agius4** [comment]
Thanks @naveedahmed1, I can confirm that I can replicate the issue. I can also see that there were some changes on the dotnet side were using `globals` is no longer possible and `html` must return the complete page because of the below errors.

```
InvalidOperationException: Globals is not supported when prerendering via UseSpaPrerendering().
Instead, your prerendering logic should return a complete HTML page, in which you embed any information you wish to return to the client.
```

I can confirm that some fixes need to be done in `@nguniversal/aspnetcore-engine`. (I'll be landing a fix in the next couple of days). I suggest to subscribe to angular/universal#1808 to keep yourself up-to-date.

@CL-BayanAbuawad, I still need to take a look at your reproduction, which I will do in the next day or two.

**Comment by naveedahmed1** [comment]
Thank you so much @alan-agius4 for the update, I really appreciate your time and efforts :)

I have also subscribed to https://github.com/angular/universal/issues/1808

**Comment by alan-agius4** [comment]
@CL-BayanAbuawad, had a look at the reproduction.

It appears that the errors is being caused when delaying the destroy via the `setImmediate`. It appears that this shenanigans is used to get around an issue with `this.ngZone.onError` subscription. This is however unneeded as Angular subscribes to this internally to send uncaught errors to its own error handler.

Below find a snippet of the code, which also uses platform destroy instead of module destroy, as destroying the platform is a better way to dispose of the application in SSR as it also mitigates the risks of having memory leaks.

```ts
export default createServerRenderer(async params => {
  const providers = [
    { provide: INITIAL_CONFIG, useValue: { document: params.data.originalHtml, url: params.url } },
    { provide: APP_BASE_HREF, useValue: params.baseUrl },
    { provide: 'BASE_URL', useValue: params.origin + params.baseUrl }
  ];

  const platform = platformDynamicServer(providers);
  const moduleRef = await platform.bootstrapModule(AppServerModule);
  const appRef: ApplicationRef = moduleRef.injector.get(ApplicationRef);
  const state = moduleRef.injector.get(PlatformState);

  // this will get the instance of the HttpStatusCodeService created for this request.
  const statusCodeService = moduleRef.injector.get(StatusCodeService);

  await appRef.isStable.pipe(first(isStable => isStable)).toPromise();

  const result = {
    html: state.renderToString(),
    // this will get the currently set status code and return it along with the prerendered html string
    statusCode: statusCodeService.getStatusCode()
  }

  if (platform.destroyed) {
    platform.destroy();
  }

  return result;
});

```

**Comment by chakrachi** [comment]
wait what about those of us not relying on a .net SSR solution..
