### ISSUE TITLE
Ng commands not working in angular web pack project to update it.

### ISSUE THREAD

**Issue by SWGeekPD** [angular/angular#37886]
Hi,

I am trying to update angular version from version 5 to 9 in my .net core angular project.
But the project is having webpack configuration and hence CLI commands not working in it.

Please suggest how to update Angular Version without CLI commands.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
