### ISSUE TITLE
[Angular 9+] Thousand separator for localeFr on Safari and IOS webview

### ISSUE THREAD

**Issue by mcailleaux** [angular/angular#37905]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/common/locales/fr

### Is this a regression?

Yes, the previous version in which this bug was not present was: angular 8

### Description

Since Angular 9 on the locale FR file : https://github.com/angular/angular/blob/10.0.x/packages/common/locales/fr.ts you use for the thousand separator the unicode '\u202f' instead of a classic white space ' ' (line 48 of the file)

So this unicode dont work on Safari and Ios Webview, those browsers return an empty string for this unicode

## 🔬 Minimal Reproduction
Simply use a decimal pipe with local FR on angular 9+ and Safari and a value with a thousand separator

## 🔥 Exception or Error
No exception just an empty thousand separator on Safari and IOS

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.1
Node: 12.16.3
OS: linux x64

Angular: 9.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.1
@angular-devkit/build-angular      0.901.1
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.1
@angular-devkit/core               9.1.1
@angular-devkit/schematics         9.1.1
@angular/cdk                       9.2.1
@angular/cli                       9.1.1
@angular/flex-layout               9.0.0-beta.29
@angular/http                      7.2.16
@angular/material                  9.2.1
@angular/material-moment-adapter   9.2.1
@angular/pwa                       0.901.1
@ngtools/webpack                   9.1.1
@schematics/angular                9.1.1
@schematics/update                 0.901.1
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0

</code></pre>

**Anything else relevant?**
Its a spécific Safari and Ios Webview issue

**Comment by petebacondarwin** [comment]
I'm afraid that this is due to an upstream change in the CLDR, which we use to generate our locale data files.
The change happened in v34: http://cldr.unicode.org/index/downloads/cldr-34

> The French locale now uses narrow no-break space U+202F is several places: as the numeric grouping separator, in many short unit patterns, and in the locale display name patterns. It also changed normal space to no-break space U+00A0 in the wide unit patterns.

If you feel this is incorrect you should create an issue with the CLDR project.

**Comment by mcailleaux** [comment]
Thx for your response, an issue is open on the CLDR project : https://unicode-org.atlassian.net/browse/CLDR-13930
