### ISSUE TITLE
xi18n configuration stopped working after upgrading to Angular 10

### ISSUE THREAD

**Issue by SanderBreivik** [angular/angular#37901]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/localize

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9.x

### Description

 I upgraded from Angular 9.x to 10.x using ng update @angular/core @angular/cli. After doing some more programming and adding more translation to my solution, I then tried to run my english configuration using 'ng serve --configuration=en' and I got the error shown later in this issue. This configuration has worked flawlessly before upgrading to 10.0.2.

## 🔬 Minimal Reproduction

Hard to reproduce since I cannot extract i18n from stackblitz, nor run a different configuration
 https://stackblitz.com/edit/angular-ivy-ju9lvy

## 🔥 Exception or Error
<pre><code>

[error] Error: Unsupported translation file format.
    at C:\Developement\Microservices\Statistics\app\node_modules\@angular-devkit\build-angular\src\utils\load-translations.js:24:15
    at Object.configureI18nBuild (C:\Developement\Microservices\Statistics\app\node_modules\@angular-devkit\build-angular\src\utils\i18n-options.js:163:28)
    at async Object.generateI18nBrowserWebpackConfigFromContext (C:\Developement\Microservices\Statistics\app\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:86:36)
    at async setup (C:\Developement\Microservices\Statistics\app\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:76:47)

</code> </pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.1
Node: 12.18.1
OS: win32 x64

Angular: 10.0.2
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.1
@angular-devkit/build-angular     0.1000.1
@angular-devkit/build-optimizer   0.1000.1
@angular-devkit/build-webpack     0.1000.1
@angular-devkit/core              10.0.1
@angular-devkit/schematics        10.0.1
@angular/cdk                      10.0.1
@angular/cli                      10.0.1
@angular/material                 10.0.1
@ngtools/webpack                  10.0.1
@schematics/angular               10.0.1
@schematics/update                0.1000.1
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0
</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
Taking a look...

**Comment by petebacondarwin** [comment]
I created a repository to reproduce this issue: https://github.com/petebacondarwin/angular-issue-37901
Running

```
npm i
npm run ng serve --configuration=en 
```

Does not fail. Can you update this repository with changes to reproduce the problem you have?

I wonder if your real XLIFF file has a typo in it that makes it invalid XML?

**Comment by SanderBreivik** [comment]
You are absolutely right. It was an extra <body> tag in one of the xlf files. Thanks! The error message threw me off a bit.

**Comment by petebacondarwin** [comment]
Glad you are sorted but you are right that the error message is not so helpful.
The translation file parsers do actually have some information about bad XML, so we should expose that...
