### ISSUE TITLE
Injector does not respect TypeScript type-only imports

### ISSUE THREAD

**Issue by samherrmann** [angular/angular#37900]
# 🐞 bug report

### Description

TypeScript introduced [type-only imports in version 3.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-exports) which contains the following text in the documentation:

> `import type` only imports declarations to be used for type annotations and declarations. **It always gets fully erased, so there’s no remnant of it at runtime**.

Now consider a new Angular CLI project with the following relevant files:

**foo.ts**:
```ts
console.log('I do not expect this statement to print if the file is imported as type-only.')

export class Foo { }
```

**foo.token.ts**:
```ts
import { InjectionToken } from '@angular/core';

export const FOO = new InjectionToken('Foo', {
    factory: () => { };
});
```

**app.component.ts**:
```ts
import { Component, Inject } from '@angular/core';
import { FOO } from './foo.token';
import type { Foo } from './foo';

@Component({ ... })
export class AppComponent {


  constructor(@Inject(FOO) foo: Foo) {}
}
```
The key things to note is that the `Foo` class is being imported as a type only. It is also not being imported anywhere else in the project. As the `console.log` message in the `foo.ts` file states, I do not expect that line to print at run time. I do not expect that line to print because TypeScript says that type-only imports "always gets fully erased, so there’s no remnant of it at runtime". The actual behavior does not match my expected behavior because the `console.log` message is being printed at runtime.

## 🔬 Minimal Reproduction
[StackBlitz](https://stackblitz.com/edit/angular-ivy-54e8de)
or
[GitHub repo](https://github.com/samherrmann/angular-sandbox/commit/9c77f6a57b2c7d2bc036700d0df278232ef0a314)

Observe the console.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 10.0.0
Node: 12.15.0
OS: linux x64

Angular: 10.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@angular/cli                      10.0.0
@ngtools/webpack                  10.0.0
@schematics/angular               10.0.0
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0

</code></pre>

**Comment by samherrmann** [comment]
Further investigation shows that the type-only import works as expected if the class is being referenced as a type only anywhere else but the component constructor. The following sample `app.component.ts` does not cause the `console.log` message in the `foo.ts` file to print as expected:

```ts
import { Component, Inject } from '@angular/core';
import type { Foo } from './foo';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  
  constructor() {
    this.doSomething({});
  }

  private doSomething(foo: Foo) { }
}
```
[StackBlitz](https://stackblitz.com/edit/angular-ivy-mb4v6a)

**Comment by JoostK** [comment]
Can confirm, the type-only modifier is not respected when emitting decorator metadata.

**Comment by JoostK** [comment]
I opened #37912 with a fix, an easy workaround would be to introduce a local type alias and use that instead:

```ts
type Foo_ = Foo;
```
