### ISSUE TITLE
dynamic object key in html

### ISSUE THREAD

**Issue by kernyden** [angular/angular#37906]
Is there a way or plans to make smth like this:
```Javascript
<app-some-component
     [perms]="{
         [customEnums.create]: (([
              'ADMIN', 
              'MANAGER'
         ]   | hasPermissions: 
                  project.name 
             | async
         )
    }">
   Look at me
</app-some-component>
```

Seems like now it itsn't..

**Comment by pkozlowski-opensource** [comment]
This is a duplicate of #13855 - generally speaking we want to work towards alleging Angular expression syntax with JS expressions syntax but for now there are still some discrepancies (you've just bumped into one of them).

Closing as a duplicate of #13855

**Comment by kernyden** [comment]
Oh, thx for supplying.
