### ISSUE TITLE
Please provide meaningful error message " ERROR in Cannot read property 'isSkipSelf' of null "

### ISSUE THREAD

**Issue by Mani2693** [angular/angular#37910]
How to trace " ERROR in Cannot read property 'isSkipSelf' of null " ? 

There is lot of possible fix for above error , Our project is huge we are getting this error and it is nearly impossible to trace back all the potential cause for this issue. 

Error occurs only in production mode ( with --aot and --prod ) 

We tried "--verbose" which still not giving us any stack trace 
![image](https://user-images.githubusercontent.com/11607412/86485168-a37e2d00-bd75-11ea-98c3-8e7203539cc1.png)

Angular version: 
![image](https://user-images.githubusercontent.com/11607412/86485204-babd1a80-bd75-11ea-9ba2-93c02779e905.png)

tsconfig: 
![image](https://user-images.githubusercontent.com/11607412/86485264-f48e2100-bd75-11ea-8f7c-583e45050f56.png)

Please help us to trace the root cause of this error

**Comment by JoostK** [comment]
Hi @Mani2693,

this error has been fixed with Ivy in Angular 9. Please note that Angular 7 is no longer supported.

**Comment by JoostK** [comment]
Closing as resolved in Ivy.
