### ISSUE TITLE
Angular 10, no esm5 build for @angular/localize, rest parameter in esm2015 build not supported by IE11

### ISSUE THREAD

**Issue by chumbalum** [angular/angular#37915]
# 🐞 bug report

### Affected Package

@angular/localize

### Is this a regression?

no problem in angular 9.1.x

### Description

The package @angular/localize in angular 10.0.x doesn't ship with a esm5 build anymore. 

![grafik](https://user-images.githubusercontent.com/486034/86491294-b0e1ea00-bd6a-11ea-825f-7b4d5a23828e.png)

The esm2015/fesm2015 module which are shipped use a syntax which is not supported in IE11.

esm5 module that was part of angular 9.1.x (working):
https://github.com/angular/localize-builds/blob/731517c83efc2ebc8948a1aca48f59a122ccee75/esm5/src/localize/src/localize.js#L99

esm2015 module that is part of angular 10.0.x (not working):
https://github.com/angular/localize-builds/blob/3906cc23be6a21a7befdbdd537d3730ae776793e/esm2015/src/localize/src/localize.js#L99

The error is showing up like this:

![grafik](https://user-images.githubusercontent.com/486034/86491492-47aea680-bd6b-11ea-921b-ac88e2367f59.png)

![grafik](https://user-images.githubusercontent.com/486034/86491559-57c68600-bd6b-11ea-9942-d16aa68fdad9.png)

So in my opinion, without additional transpilation, the esm2015 can't be used in IE11, since the spread/rest cannot be polyfilled.

I'm using a custom webpack build so I cannot tell if this problem occurs when using the CLI.

## 🔬 Minimal Reproduction
minimal example via IE11 developer tools:
![grafik](https://user-images.githubusercontent.com/486034/86490923-614eee80-bd69-11ea-9072-b7ff69f2860a.png)

## 🔥 Exception or Error
<pre><code>SCRIPT1010: Bezeichner erwartet</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
"@angular/compiler": "^10.0.1",
"@angular/compiler-cli": "^10.0.1",
"@angular/language-service": "^10.0.1",
"@ngtools/webpack": "^10.0.1",
"@angular/animations": "^10.0.1",
"@angular/common": "^10.0.1",
"@angular/core": "^10.0.1",
"@angular/forms": "^10.0.1",
"@angular/localize": "^10.0.1",
"@angular/platform-browser": "^10.0.1",
"@angular/platform-browser-dynamic": "^10.0.1",
"@angular/router": "^10.0.1",
</code></pre>

**Anything else relevant?**
Tested in Internet Explorer 11.900.18362.0CO

**Comment by sonukapoor** [comment]
@chumbalum I believe esm5 has been deprecated:

https://v9.angular.io/guide/deprecations#esm5-and-fesm5-code-formats-in-angular-npm-packages

https://github.com/angular/angular/pull/36944

**Comment by chumbalum** [comment]
@sonukapoor I see ... thanks for the hint. I guess many people, who are not using the CLI, will run into this.

I'll close this issue then, since it's not a bug.

**Comment by sonukapoor** [comment]
@chumbalum Probably would be good to make it somehow better visible.

**Comment by chumbalum** [comment]
@sonukapoor Yea probably. But I'm not even sure if my issue comes with the lack of esm5 modules. My current guess is that the `target: 'es5'` in my tsconfig is not reflected anymore.

I tried a fresh CLI project with angular 10.0.2 and set the target in tsconfig to es5. When running `ng serve` the console did show the following output:

```
ng serve
chunk {main} main.js, main.js.map (main) 62.1 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 143 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 12.9 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.06 MB [initial] [rendered]
Date: 2020-07-03T22:45:26.124Z - Hash: ff2dcb6b18064be04cfa - Time: 29253ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.
```

After I whitelisted IE11 in the .browserlistrc file and ran `ng serve` again, the console did show the following output (notice the additional es5 file):

```
ng serve
chunk {main} main.js, main.js.map (main) 62.1 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 143 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 581 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 12.9 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.06 MB [initial] [rendered]
Date: 2020-07-03T22:50:54.543Z - Hash: 63ab3657d5d976966a54 - Time: 16566ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.
```

So setting the target to es5 doesn't seem to be sufficient to produce es5 code. The problem is that in my custom webpack build, a browserlist is not taken into account. I have to investigate this further because, I can't move on to angular 10 at the moment. I'll comment if I have any news on this.

**Comment by wmarques** [comment]
Sorry to comment on a closed issue but I'm running through same issues with a custom webpack config. 

I already use babel so can you tell me how to transpile @angular packages in order to get IE11 support ? I tried with a classic exclude Regexp like:
`exclude: /[\\/]node_modules[\\/](?!(@angular)[\\/])/
`
but then I had alot of errors...

**Comment by chumbalum** [comment]
I ditched my custom webpack config and moved to cli because with every angular release, the hassle got bigger getting things back to work. Ivy, AoT, and now es5 drop. It's a fight against windmills. At least I could catch up until angular 10, but it's not economical.

Concerning your question I can only give the advice to dig in the angular build system and do some research how the ES5 builds are made. As far as I know, ES5 builds for differential loading will only be produced in production builds and only if 1) your browserlistrc does not exclude IE11 and 2) the target in your tsconfig is set to ES5. So even with @angular/cli it's not possible anymore to test IE11 with an development build. Furthermore it seems that the ES5 files are created as the last step of a compilation when in production mode. So I assume that the ES5 transpilation is a seperate step which is executed afterwards when the ES2015 build is finished. But that's just an assumption. So maybe you could try to execute a babel transpilation of the files after your build is finished as a seperate task (and not as part of your webpack build).

**Comment by wmarques** [comment]
@chumbalum That's what I thought :( For now the cost of moving to the CLI is too big, but I guess we won't have the choice soon or after...

For now I solved this by transpiling all the node_modules through Babel... It slows down the build but at least I'm sure I have a full ES5 build after that.

Thanks !
