### ISSUE TITLE
Nice, the only notable contribution you've ever made anywhere on Github is making sure everyone at Google knows you're a racist.

### ISSUE THREAD

**Issue by varun-av** [angular/angular#37925]
Nice, the only notable contribution you've ever made anywhere on Github is making sure everyone at Google knows you're a racist.

_Originally posted by @ncrawlins in https://github.com/angular/angular/issues/37771#issuecomment-650169764_

**Comment by varun-av** [comment]
Why are you using this platform for displaying your political agenda. You have other platforms to do that. No one wants this here. Stop whining about that and remove the BLM from the site.

**Comment by gkalpak** [comment]
See https://github.com/angular/angular/issues/37771#issuecomment-650294204.

**Comment by petebacondarwin** [comment]
Note that @varun-av only created the account to post this.
