### ISSUE TITLE
Bad menu

### ISSUE THREAD

**Issue by AngularLessonsGit** [angular/angular#37937]
https://angular.io/docs

Cutted word "BLOG"

![image](https://user-images.githubusercontent.com/53466268/86564088-3da8c580-bf6e-11ea-8def-4a95a3eb636b.png)

**Comment by petebacondarwin** [comment]
That's a good spot. The CSS appears to be targeting the home page where there is no hamburger menu, then when the blog is about to be overlapped by the search, it swtiches to "narrow" mode. On this page, the hamburger pushes the menu across enough that it get overlapped before the switch to narrow.

cc @sjtrimble
