### ISSUE TITLE
Problems with "scrollPositionRestoration" using angular material

### ISSUE THREAD

**Issue by cvalenzuelab1982** [angular/angular#37934]
Hello experts, I tell you that I have problems with the position of the view, using routes, and angular material, I have a side bar using the "mat-drawer-container" component, which I do with the dynamic content with "router-outlet" When I change routes you are not positioned above, what am I doing wrong?

=>>> here app.routers.ts
import { RouterModule, Routes } from '@angular/router'
import { LoginComponent } from '../components/login/login.component'
import { LoginEmployeeComponent } from '../components/login-employee/login-employee.component'
import { LoginGuestComponent } from '../components/login-guest/login-guest.component'
import { LoginReceptionComponent } from '../components/login-reception/login-reception.component'

import { ContainerComponent } from '../components/layouts/container/container.component'
import { NoFoundComponent } from '../components/no-found/no-found.component'
import { ProfileUserComponent } from '../components/profile-user/profile-user.component'
import { CSideNavComponent } from '../components/layouts/c-side-nav/c-side-nav.component'
import { EquipmentListComponent } from '../components/equipment/equipment-list/equipment-list.component'
import { InOutControlComponent } from '../components/reception/in-out-control/in-out-control.component'
import { LoginAdminComponent } from '../components/login-admin/login-admin.component'
import { WelcomeComponent } from '../components/welcome/welcome.component'
import { ConfirmMeetingComponent } from '../components/guest/confirm-meeting/confirm-meeting.component'
import { SheduleMeetingComponent } from '../components/employee/shedule-meeting/shedule-meeting.component'
import { MeetingDetailsComponent } from '../components/admin/meeting-details/meeting-details.component'
import { MeetingDetailsClientComponent } from '../components/employee/meeting-details-client/meeting-details-client.component'
import { ReportDashComponentAdmin } from '../components/admin/report-dash-admin/report-dash-admin.component'
import { ReportMonthComponent } from '../components/admin/report-month/report-month.component'
import { IncomeMethodComponent } from '../components/admin/income-method/income-method.component'
import { CompanyDashComponent } from '../components/admin/company-dash/company-dash.component'
import { MeetingDashComponent } from '../components/admin/meeting-dash/meeting-dash.component'
import { GuestDashComponent } from '../components/admin/guest-dash/guest-dash.component'
import { ReportDashEmployeeComponent } from '../components/employee/report-dash-employee/report-dash-employee.component'
import { ReportMonthEmployeeComponent } from '../components/employee/report-month-employee/report-month-employee.component'
import { LoginLeaderComponent } from '../components/login-leader/login-leader.component'
import { ReportDashLeaderComponent } from '../components/leader/report-dash-leader/report-dash-leader.component'
import { SubManagerDirectionComponent } from '../components/leader/sub-manager-direction/sub-manager-direction.component'
import { ReportMonthLeaderComponent } from '../components/leader/report-month-leader/report-month-leader.component'
import { InOutControlAdminComponent } from '../components/admin/in-out-control-admin/in-out-control-admin.component'

// PARA USO EXTERNO AL SISTEMA
import { TotemAccessComponent } from '../components/totem/totem-access/totem-access.component'
import { TotemWelcomeComponent } from '../components/totem/totem-welcome/totem-welcome.component'
import { TotemCheckComponent } from '../components/totem/totem-check/totem-check.component'
import { TotemEmailComponent } from '../components/totem/totem-email/totem-email.component'
import { TotemScheduledComponent } from '../components/totem/totem-scheduled/totem-scheduled.component'
import { TotemContactComponent } from '../components/totem/totem-contact/totem-contact.component'
import { TotemNoRegisterComponent } from '../components/totem/totem-no-register/totem-no-register.component'
import { TotemLockedComponent } from '../components/totem/totem-locked/totem-locked.component'

const APP_ROUTES:Routes = [

  { path: '', pathMatch: 'full', redirectTo: 'login'},
  { path: 'login', component: LoginComponent},

  { path: 'admin' , component: LoginAdminComponent },
  { path: 'admin/:uid/home', component: ContainerComponent,
    children: [
      { path: '', redirectTo: 'welcome', pathMatch: 'full'}, 
      { path: 'welcome', component: WelcomeComponent },
      { path: 'eprofile', component: ProfileUserComponent },
      { path: 'equipment', component: EquipmentListComponent },
      { path: 'ioControlAdmin', component: InOutControlAdminComponent },
      { path: 'meetingDetails/:id', component: MeetingDetailsComponent},
      { path: 'reportDashAdmin', component: ReportDashComponentAdmin},
      { path: 'reportMonth/:tabId', component: ReportMonthComponent},
      { path: 'incomeMethod', component: IncomeMethodComponent},
      { path: 'company/:id', component: CompanyDashComponent},
      { path: 'meetingDash/:id', component: MeetingDashComponent},
      { path: 'guestDash/:id', component:GuestDashComponent}
    ]
  },

  { path: 'employee' , component: LoginEmployeeComponent },
  { path: 'employee/:uid/home', component: CSideNavComponent,
    children: [
      { path: '', redirectTo: 'welcome', pathMatch: 'full'}, 
      { path: 'welcome', component: WelcomeComponent },
      { path: 'eprofile', component: ProfileUserComponent },
      { path: 'equipment', component: EquipmentListComponent },
      { path: 'iocontrol', component: InOutControlComponent },
      { path: 'shedule', component: SheduleMeetingComponent},
      { path: 'meetingDetailsClient/:id', component: MeetingDetailsClientComponent},
      { path: 'reportDashEmployee', component: ReportDashEmployeeComponent },
      { path: 'reportMonthEmployee', component: ReportMonthEmployeeComponent},
      { path: 'guestDash/:id', component:GuestDashComponent},
      { path: 'reportMonth', component: ReportMonthComponent},
      { path: 'company/:id', component: CompanyDashComponent},
      { path: 'meetingDash/:id', component: MeetingDashComponent},
      { path: 'incomeMethod', component: IncomeMethodComponent},
    ] 
  },

  { path: 'leader', component: LoginLeaderComponent},
  { path: 'leader/:uid/home', component: CSideNavComponent,
    children: [
      { path: '', redirectTo: 'welcome', pathMatch: 'full'}, 
      { path: 'welcome', component: WelcomeComponent },
      { path: 'reportDashLeader', component: ReportDashLeaderComponent },
      { path: 'meetingDetailsClient/:id', component: MeetingDetailsClientComponent},
      { path: 'company/:id', component: CompanyDashComponent},
      { path: 'subManagerDirection', component: SubManagerDirectionComponent},
      { path: 'reportMonthLeader', component: ReportMonthLeaderComponent},
      { path: 'meetingDash/:id', component: MeetingDashComponent},
      { path: 'incomeMethod', component: IncomeMethodComponent},
    ]
  },

  { path: 'reception' , component: LoginReceptionComponent },
  { path: 'reception/:uid/home', component: ContainerComponent,
    children: [
      { path: '', redirectTo: 'welcome', pathMatch: 'full'}, 
      { path: 'welcome', component: WelcomeComponent },
      { path: 'eprofile', component: ProfileUserComponent },
      { path: 'iocontrol', component: InOutControlComponent },
    ]
  },

  { path: 'guest' , component: LoginGuestComponent },
  { path: 'guest/:uid/home', component: ContainerComponent,
    children: [
      { path: '', redirectTo: 'welcome', pathMatch: 'full'}, 
      { path: 'welcome', component: WelcomeComponent },
      { path: 'eprofile', component: ProfileUserComponent },
      { path: 'equipment', component: EquipmentListComponent },
      { path: 'meetings', component: ConfirmMeetingComponent}
    ]
  },

 

  { path: 'totem-welcome', component: TotemWelcomeComponent},
  { path: 'totem-access', component: TotemAccessComponent},
  { path: 'totem-check', component: TotemCheckComponent},
  { path: 'totem-email', component: TotemEmailComponent},
  { path: 'totem-scheduled', component: TotemScheduledComponent},
  { path: 'totem-contact', component: TotemContactComponent},
  { path: 'totem-no-register', component: TotemNoRegisterComponent},
  { path: 'totem-locked', component: TotemLockedComponent},

  { path: '404', component: NoFoundComponent },
  { path: '**', pathMatch: 'full', redirectTo: '/404'},

]

export const APP_ROUTING = RouterModule.forRoot(APP_ROUTES, { useHash: true, initialNavigation: 'enabled', scrollPositionRestoration: 'enabled'})

==>here c-side-nav.component.html

<mat-drawer-container   class="drawer-container" autosize>
  <mat-drawer #drawer class="drawer-sidenav" mode="side" opened [ngClass]="{'opened': showFiller}">
    ....
  </mat-drawer>

  <mat-toolbar class="drawer-sidenav-toolbar">
  ...
  </mat-toolbar>

  <div>

    <div class="container-body-area">
      <router-outlet></router-outlet>   => HERE ROUTER!!!!!!
    </div>

  </div> 

  <app-float-button *ngIf="userData.perfil[0] == 1"></app-float-button>

</mat-drawer-container>

I hope you can tell me what I'm doing wrong

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
