### ISSUE TITLE
ApplicationRef.tick is called recursively when UpgradeModule.bootstrap is called from inside a tick.

### ISSUE THREAD

**Issue by razronen** [angular/angular#37936]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?

Not a regression.

### Description

We use Angular 8 application that bootstrap an AngularJs application via UpgradeModule in its app.component.ts.
We don't want to bootstrap AngularJs first. **As performance is very important for us we call the UpgradeModule.bootstrap from AppComponent ngAfterViewInit, to avoid the time a callback is pushed to the callback queue and get executed**, so it is been called inside a tick, meaning if you look at the call stack above you'll see ApplicationRef.tick. 
The problem is that in function `forkInnerZoneWithAngularBehavior` in packages\core\src\zone\ng_zone.ts `onLeave()` is called.
This causes a `checkStable()` check that triggers another tick because functions were inserted to the promise queue while the bootstrap ran.

maybe adding a parameter to `forkInnerZoneWithAngularBehavior` if to run `onLeave()` will fix this issue?

## 🔬 Minimal Reproduction
Simply bootstrap AngularJs application from `ngAfterViewInit` of Angular AppComponent.

## 🔥 Exception or Error
<pre><code>
ApplicationRef.tick is called recursively
    at ApplicationRef.push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
ng version
Your global Angular CLI version (8.3.22) is greater than your local
version (8.2.2). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.2.2
Node: 10.16.0
OS: win32 x64
Angular: 8.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.2.2
@angular/cdk                      8.0.0
@angular/cli                      8.2.2
@angular/http                     7.2.15
@ngtools/webpack                  8.1.0
@schematics/angular               8.2.2
@schematics/update                0.802.2
rxjs                              6.4.0
typescript                        3.4.2
webpack                           4.43.0

</code></pre>

**Anything else relevant?**

**Comment by JiaLiPassion** [comment]
@razronen, could you post a reproduce repo? thanks.

**Comment by petebacondarwin** [comment]
Closing due to a lack of response.
