### ISSUE TITLE
The Angular logo is racist and needs to be changed

### ISSUE THREAD

**Issue by Achilles1515** [angular/angular#37931]
Thanks for the #BlackLivesMatter inspiration! I didn't know I was prejudice against some of my own people until I went looking for web framework documentation and was met with a BLM banner. This inspiration awakened me from my social injustice slumber and led me to realize the Angular logo, consisting of a *capitalized*, **white** 'A' inside a shield, is clearly a sign of white supremacy and is nothing but racist, "we defend powerful whites", propoganda.

Can the Angular team please give an explanation behind the microaggressions exhibited during the creation of this logo?

In my opinion, this logo should be torn down immediately and replaced with one that is comforting to blacks, first and foremost. Any new logo submissions should be vetted by the BLM organization for approval. This would show great support for the #BlackLivesMatter movement!

**Comment by ericmartinezr** [comment]
How about we change it to Blackngular? That sounds fine too me. Now, Transngular sounds even more inclusive.
