### ISSUE TITLE
Change type of routes parameter on  RouterModule.forRoot() and forChild() to be of type Routes | ()=>Routes 

### ISSUE THREAD

**Issue by jalberto-ghub** [angular/angular#37944]
# 🚀 feature request

### Relevant Package
RouterModule

### Description
When using AOT there is no easy way to define your routes as the result of some processing, for example there is no simple way to achieve the following valid JIT definitions:

**routes.ts:**
`
export const routes = [ 
    {
        path: '',
        redirectTo: '/home',
        pathMatch: 'full',
    },
    {
        path: 'home',
        component: HomePageComponent,
    },
 ]
`
**environment.ts**
`
import {routes} from './routes.ts';
export const fullRoutes = [
        {
        path: '',
        pathMatch: 'full',
        component: 'ShowDevComponent'
    },
    ...routes
];
`
**environment.prod.ts**
`
import {routes} from './routes.ts';
export const fullRoutes = routes;
`
Then use fullRoutes on RouterModule.forRoot(fullRoutes);

This breaks if compiled using AOT.

### Describe the solution you'd like
Like for other AOT related settings, the solution is allow passing a factory and let `forRoot/forChild` do the right thing.

**environment.ts**
`
import {routes} from './routes.ts';
export function fullRoutes() {
   return [
        {
        path: '',
        pathMatch: 'full',
        component: 'ShowDevComponent'
    },
    ...routes
   ];
}
`
**environment.pord.ts**
`
import {routes} from './routes.ts';
export function fullRoutes() { return routes; }
`
With the above change, we can now do the following call:

`
   RouterModule.forRoot(fullRoutes)
`

### Describe alternatives you've considered
The current alternative requires reloading the routes on your code and it brings with it all kinds of unnecessary additional issues.

**Comment by JoostK** [comment]
What version are you using? I'm pretty sure this just works in Ivy (since 9.0)

**Comment by atscott** [comment]
As @JoostK mentioned, this can just work in Ivy with the caveat that you'd need to write this as `RouterModule.forRoot(fullRoutes())`. That should be sufficient and cover the use-case you need, i.e. providing different routes for different environments.
