### ISSUE TITLE
ngModel support for Subject

### ISSUE THREAD

**Issue by pickfire** [angular/angular#37955]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/forms

### Description

Using `Subject` for `ngModel` requires writing boilerplate
```html
<mat-select [ngModel]="users" (ngModelChange)="users.next($event)">
```

### Describe the solution you'd like

Allow the use of `Subject` for `ngModel` without writing custom change detection such as
```html
<mat-select [(ngModel)]="users">
```

### Describe alternatives you've considered

Change rxjs prototype itself
```typescript
Object.defineProperty(BehaviorSubject.prototype, 'value', {
    set: function(v) {
        return this.next(v);
    }
});
```
And use `[(ngModel)]="users.value"` https://stackoverflow.com/questions/38662155/how-to-two-way-bind-my-own-rxjs-subject-to-an-ngmodel

This change may require different handling for `Subject` in https://github.com/angular/angular/blob/master/packages/forms/src/directives/ng_model.ts

**Comment by Airblader** [comment]
This will always be a breaking change as there could be CVAs out there that use an observable as the model.
