### ISSUE TITLE
documentation for "coreDirectives" needs to be updated to match the switch to upper-case constants

### ISSUE THREAD

**Issue by sanfordredlich** [angular/angular#3795]
https://github.com/rkirov/angular2-dart-router-demo/blob/master/angular2/lib/directives.dart docs specify using "coreDirectives" when it looks like it should be "CORE_DIRECTIVES"

**Comment by pkozlowski-opensource** [comment]
Yes, it will be solved by https://github.com/angular/angular/pull/3791 which I'm going to merge today

**Comment by pkozlowski-opensource** [comment]
Thnx for the report though!
