### ISSUE TITLE
Typo in Doc - on page -  Angular elements overview

### ISSUE THREAD

**Issue by tphobe9312** [angular/angular#37964]
**Sentence in document** :  This is a good way to quickly get TypeScript features, such as type checking and autocomplete support, for **you** custom element.

**Sentence should be** :  This is a good way to quickly get TypeScript features, such as type checking and autocomplete support, for **your** custom element.

![typo](https://user-images.githubusercontent.com/8081089/86875397-066a1e00-c100-11ea-9d3a-54307d6b7c47.png)

**Comment by santoshyadavdev** [comment]
Hi @tphobe9312, Good catch, would you like to do open the PR?

**Comment by tphobe9312** [comment]
Yes I want to open the PR and ix that typo

**Comment by santoshyadavdev** [comment]
> Yes I want to open the PR and fix that typo

Great, tag me if you need any help.

**Comment by tphobe9312** [comment]
@santoshyadavdev could you help me open the PR?

**Comment by santoshyadavdev** [comment]
1. 
![image](https://user-images.githubusercontent.com/11923975/86878349-5350f300-c106-11ea-9314-dfadc6321b87.png) when you click on this icon you will see the file which you can edit
2. 
![image](https://user-images.githubusercontent.com/11923975/86878371-606de200-c106-11ea-8239-177fa8435f46.png)
here in commit: enter "docs: fix a typo"

in additional description enter the description min 100chars and click propose changes

**Comment by tphobe9312** [comment]
@santoshyadavdev I have committed the changes. Is that all?

**Comment by santoshyadavdev** [comment]
Now just last step open a PR

**Comment by santoshyadavdev** [comment]
I did that as of now, you can accept the CLA and it will be added in review,

**Comment by santoshyadavdev** [comment]
Hi, @tphobe9312 I am closing the PR, please open it one as it may create issues.

**Comment by tphobe9312** [comment]
why closed @santoshyadavdev, should I re-create the PR or what ?

**Comment by santoshyadavdev** [comment]
I will be an author in that case, just open the OR from your account, so you will become an author.

**Comment by santoshyadavdev** [comment]
> why closed @santoshyadavdev, should I re-create the PR or what ?

Go to 
![image](https://user-images.githubusercontent.com/11923975/86882400-d9246c80-c10d-11ea-8b1c-7c05903b86d1.png)
and select the branch patch-1 and click on Pull request.

**Comment by ajitsinghkaler** [comment]
Fixed #37966
