### ISSUE TITLE
How to pass Parameters from one forRoot to another forRoot

### ISSUE THREAD

**Issue by jimmyhdolores** [angular/angular#37961]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
Hello, I am using Firebase and what I am trying to do is put the notifications functionality in a separate project and then publish it in NPM and reuse it; Angular- Fire has an AngularFireModule module and an initializeApp method which expects a value, I have created an ngModule to be able to do my job, but I am having trouble trying to pass a parameter to that firebase module from my module's forRoot.

```javascript
import { ModuleWithProviders, NgModule, Optional, SkipSelf } from '@angular/core';
import { AngularFireModule } from '@angular/fire';
import { AngularFireMessagingModule } from '@angular/fire/messaging';
import { TDPNotificationService } from './notification.service';

let config: any = {};


@NgModule(
  {
    imports: [
      AngularFireModule.initializeApp(config),
      AngularFireMessagingModule,
    ],
  }
)

export class TDPNotificationModule {
  constructor(@Optional() @SkipSelf() parentModule: TDPNotificationModule) {
    if (parentModule) {
      throw new Error(
        'TDP Notification Module is already loaded. Import it in the AppModule only');
    }
  }
  static forRoot(configFirebase: any): ModuleWithProviders {
    config = configFirebase;
    return {
      ngModule: TDPNotificationModule,
      providers: [
        TDPNotificationService,
      ]
    };
  }
}

```
I hope you can guide me, thanks

Angular version: 9.1.9
angular/fire: 5.2.3
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by CodeLiam** [comment]
Mate, likely the team is going to close this, as the Issues section is for, well, issues.

To give a you a little help, you need to add your config credentials/keys to your object config variable, right now you are passing nothing in there.  You get those from your firebase project.

This may point you in the direction you wish to go
https://fireship.io/snippets/install-angularfire/

**Comment by jimmyhdolores** [comment]
Well I opened this question as "support or help" when generating the issue; Outside of it, I know that it is necessary to pass those values ​​from firebase, but as I said I try to put this module as a utility and when the module is used in another angular project, the value will only be passed there

```javascript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { environment } from '../environments/environment';
import { AsyncPipe } from '@angular/common';
import { AppComponent } from './app.component';
import { TDPDirectivesModule, TDPNotificationModule, TDPNotificationService } from '@tdp/ng-commons';
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    TDPNotificationModule.forRoot(environment.firebase),
    TDPDirectivesModule,
  ],
  providers: [TDPNotificationService, AsyncPipe],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

PS: The content inside the issue template for a support request is:

> Please do not file questions or support requests on the GitHub issues tracker.
> 
> You can get your questions answered using other communication channels. Please see: 
> https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
> 
> Thank you!
