### ISSUE TITLE
Flow component context to component's contents (<content></content>)

### ISSUE THREAD

**Issue by abelepereira** [angular/angular#3796]
Take for example:

```javascript
import {Component, View, bootstrap} from "angular2/angular2";

@Component({
    selector: "app"
})
@View({
	template:  "<content></content>"
})
class App {
    name: string;
	
    constructor() {
        this.name = "FooBar";
    }
}

bootstrap(App);
```

Make the app context available for the view content, suck as:

(consuming the component from foo.html)
```html
<app>
	<h1>Hello {{name}}</h1>
</app>
```
Should produce "Hello FooBar", but actually produces "Hello {{name}}".

**Comment by vicb** [comment]
It actually works as expected, the interpolation would only be active in the view of a component.

If an outer component as its view set to:
```
<app>
    <h1>Hello {{name}}</h1>
</app>
```

Then the `name` will be retrieved from the instance of this outer component.

Makes sense ?

**Comment by xsilen** [comment]
if html body is a component, the body innerHtml should move to angular defined template?
and by the way, in the html file the component define is a bare tag without using children node and it will be removed later?
