### ISSUE TITLE
Rename the "master" branch to avoid problematic terminology

### ISSUE THREAD

**Issue by jermowery** [angular/angular#37963]
Similar to the reasoning behind GitHub's recent statement that the default branch on new repos will be changed to not use "master" can we change the name of the default branch on this repo to something else? Perhaps "main"?

**Comment by sonukapoor** [comment]
While I somewhat agree with that, there are several discussions on the web, encouraging not to rename `master` to `main`.

**Comment by spock123** [comment]
Master is not a problematic word. Come on, madness for the uninformed.

**Comment by CodeLiam** [comment]
This crap has gotten way out of control, give em an inch and they'll try to take a mile.  Enough is enough already

**Comment by spock123** [comment]
@CodeLiam  I guess my Masters Degree now has to renamed to Main Degree as well.. Jesus Christ

**Comment by CodeLiam** [comment]
I concur @spock123 I am of the opinion that this is not even an issue with regards to Angular, it's functionality, and if it works properly and should therefore simply be closed.  Regardless I hope you are well and have an awesome day!!!

**Comment by ericmartinezr** [comment]
Simply stupid. There's no other way to put it. Stupid, like all this progressive shit destroying everything it touches.

**Comment by mgechev** [comment]
Hey @jermowery, thanks for starting the discussion. This is something we've been talking about. As you mentioned GitHub will be likely [taking actions](https://twitter.com/natfriedman/status/1271253144442253312?lang=en) in the future and we'd want to coordinate the efforts.

I'll lock this thread for now. If you're interested in further reading on the motivation for such a change, I recently got pointed to a [similar discussion](https://lkml.org/lkml/2020/7/4/229) in the Linux community.

**Comment by JoostK** [comment]
The framework, CLI and components repo have recently switched to using `main` as default branch.
