### ISSUE TITLE
alpha.35  Http module missing

### ISSUE THREAD

**Issue by kweheliye** [angular/angular#3797]
I cannot find the Http Module in alpha.35

**Comment by pkozlowski-opensource** [comment]
@kweheliye How do you setup your project? Are you using pre-bundled version? If so Http has a separate bundle now: https://code.angularjs.org/2.0.0-alpha.35/

**Comment by PascalPrecht** [comment]
@kweheliye the http module is now available as `http/http` namespace, instead of `angular/http`. Maybe that causes you problem?

**Comment by kweheliye** [comment]
Thanks.

**Comment by dsebastien** [comment]
Will the http.d.ts file also get uploaded to DefinitelyTyped along with the angular2.d.ts?
I'm currently referring to the one part of the npm package but it ain't great :)

**Comment by kweheliye** [comment]
See this issue https://github.com/angular/angular/issues/3740
