### ISSUE TITLE
To explore the sample app with French translations used in this guide, see the live example. This live example url not working. On same page i have tried another hyperlink that one also not working.

### ISSUE THREAD

**Issue by DhanukaManish** [angular/angular#37975]
![image](https://user-images.githubusercontent.com/34171208/86924563-377b3a80-c162-11ea-9991-2cac9309561c.png)

# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by sonukapoor** [comment]
@DhanukaManish On this [page](https://angular.io/guide/i18n), there are two links pointing to the same [live example](https://stackblitz.com/angular/klxpvxkkrdn?file=src%2Fapp%2Fapp.component.ts). I tried to open the app and can see that it is working. See the below screenshot. Is that not what you are seeing?

![image](https://user-images.githubusercontent.com/59734/87144428-bca34400-c275-11ea-98a6-b609d2e37e1c.png)

**Comment by sonukapoor** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
