### ISSUE TITLE
Map is not visible if I implement the options

### ISSUE THREAD

**Issue by DMuellerFielddata** [angular/angular#37978]
Hi, 
if I iplements the Code for the Google Map Options, my Map empty.
What do I Wrong?
[https://stackblitz.com/](https://stackblitz.com/edit/angular-ivy-bm1vad)

.html

```
<google-map
  height="500px"
  width="100%"
  [options]="mapOptions"
  [zoom]="mapZoom"
></google-map>
```

.ts
```

import { Component} from '@angular/core';
import { MapInfoWindow, MapMarker, GoogleMap } from '@angular/google-maps'

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent {
  zoom=15;
  options : google.maps.MapOption = {
    maxZoom: 18,
    minZoom: 15,
    fullscreenControl: false,
    streetViewControl: false,
    mapTypeControl: false,
  }
}

```

"@angular/core": "~9.1.3",
"@angular/google-maps": "^9.2.2",

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
