### ISSUE TITLE
Poorly coded reactive form doesn't throw an exception

### ISSUE THREAD

**Issue by wobblycogs** [angular/angular#37988]
# 🐞 bug report

### Affected Package
Presumably @angular/forms

### Is this a regression?

Not as far as I know

### Description

I can write a very poorly coded reactive form and the system will still attempt to interpret it with unexpected results. I would expect either an exception or nothing, I didn't expect it to splurge out a chunk of code.

## 🔬 Minimal Reproduction
```typescript
this.form = this.fb.group({
    name: ['', [Validators.required]],
    description: [[Validators.required]],
});
````

```
...
<mat-form-field>
    <input type="text" matInput placeholder="Description" id="description" formControlName="description" autocomplete="off"/>
</mat-form-field>
...
```

## 🔥 Exception or Error
Description field of the above form field displays the text:
>required(control) {        return isEmptyInputValue(control.value) ? { 'required': true } : null;    }

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 9.0.4
Node: 12.18.1
OS: win32 x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.4
@angular-devkit/build-angular      0.900.4
@angular-devkit/build-optimizer    0.900.4
@angular-devkit/build-webpack      0.900.4
@angular-devkit/core               9.0.4
@angular-devkit/schematics         9.0.4
@angular/cdk                       9.1.0
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.1.0
@angular/material-moment-adapter   9.2.4
@ngtools/webpack                   9.0.4
@schematics/angular                9.0.4
@schematics/update                 0.900.4
rxjs                               6.5.3
typescript                         3.7.5
webpack                            4.41.2

**Anything else relevant?**

**Comment by AndrewKushnir** [comment]
Hi @wobblycogs, thanks for reporting the issue. I believe that it's related to the fact that the Forms are not strongly typed (see #13721), so TypeScript can't be used to improve the situation that you described. I will close this ticket for now and please subscribe to the issue #13721 for further discussion/updates. Thank you.
