### ISSUE TITLE
Angular2 UT error: $(...).popover is not a function /  TypeError: Cannot read property 'focus' of null

### ISSUE THREAD

**Issue by Anna-liu-77** [angular/angular#37985]
Recently I test the component with directives (likes tooltip), but when I run this spec.ts file, I always got the error likes this: $(...).popover is not a function. So how can I handle with this problem?
Thank you in advance!

**Comment by Anna-liu-77** [comment]
An error was thrown in afterAll
  TypeError: _this.handler.handle is not a function

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
