### ISSUE TITLE
Set cursor position in contenteditable div - updating when matching character

### ISSUE THREAD

**Issue by santokt** [angular/angular#37996]
When user types 'foo' it's automatically changes to bar(this changes based on some condition) , but the caret/cursur keeps going to start position and typing backward.below is the code in stackblitz.

https://stackblitz.com/edit/angular-ivy-sjhbb6

stackoverlofw question link
https://stackoverflow.com/questions/62799054/angular-and-typescript-set-cursur-position-multiple-child-element-in-contented

Thank you.

**Comment by basherr** [comment]
This is all what you need

```
setCaretToEnd(target/*: HTMLDivElement*/) {
  const range = document.createRange();
  const sel = window.getSelection();
  range.selectNodeContents(target);
  range.collapse(false);
  sel.removeAllRanges();
  sel.addRange(range);
  target.focus();
  range.detach(); // optimization

  // set scroll to the end if multiline
  target.scrollTop = target.scrollHeight; 
}
```

Thanks to [am0wa](https://stackoverflow.com/questions/1125292/how-to-move-cursor-to-end-of-contenteditable-entity/3866442#3866442)

**Comment by santokt** [comment]
Thank you

**Comment by santokt** [comment]
Sorry this is still not working when we change/delete any text in between. We cant type middle it's keep coming to end.
https://stackblitz.com/edit/angular-ivy-9bfrpz?embed=1&file=src/app/app.component.ts&view=editor

@basherr  please look into it.

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
