### ISSUE TITLE
Failed to load js when accessing invalid url

### ISSUE THREAD

**Issue by uuk007** [angular/angular#37998]
Following is my route

`
const routes: Routes = [

  {

    path: '', component: Layout, 

    children: [

      { path: 'home', component: HomeComponent},

      {

        path: 'Product', component: ProductComponent},

        children: [

          { path: '', component: ProducListComponent},

          { path: 'add', component: ProductAddComponent },

        ]

      },

    ],

  },

  { path: '**', component: PageNotFoundComponent },

];
`
This is working as expected.

When i access url directly, i am facing some weird behaviour

http://localhost:4200/home -- Working

http://localhost:4200/Product - Working

http://localhost:4200/Products - Working (Page not found is getting rendered)

But when i access below url manually, i am getting blank page

http://localhost:4200/Product/1 -- Blank page

http://localhost:4200/Product/add -- Blank page

My expectation is it should redirect to Page not found component...What is the issue in the configuration

**Comment by basherr** [comment]
How your `ProductAddComponent` and `ProducListComponent` looks like?

**Comment by frederikprijck** [comment]
@basherr That's actualy a very common pattern when using child routes. It's to define the default route that is to be shown as the child.

That said, there might be better places to get this kind of support @uuk007  (gitter / discord). If you have a reproduction of the problem, feel free to ping me at any of the two places.

**Comment by basherr** [comment]
@frederikprijck How will `Angular` load the `ProducListComponent` component? What will be the `URL` for that?

**Comment by basherr** [comment]
@frederikprijck Thanks for the correction. Just reviewed this [Stackblitz Plunker](https://stackblitz.com/edit/angular-saw268?embed=1&file=src/app/app.component.html&view=editor) and it seems to be working.

**Comment by MisaGu** [comment]
I will suggest to try adding additional '**' to the children arrays (unfortunately i've never had children -> children hierarchy, only flat router array with loadChild when need to deepen router tree)

**Comment by petebacondarwin** [comment]
Hello @uuk007, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
