### ISSUE TITLE
Proposal: Public API to add custom EventManagerPlugins

### ISSUE THREAD

**Issue by adamdbradley** [angular/angular#3800]
Currently it looks like Angular2 has a locked in set of `EventManagerPlugin`s, to include `HammerGesturesPlugin`. 
https://github.com/angular/angular/blob/a9ce454b2176514e1b655d7b005c32f0aa14ab98/modules/angular2/src/core/application_common.ts#L115

Would it be possible to create a public API so custom `EventManagerPlugin`s could be created? This would make it easier for third party libraries to add logic to certain events, most importantly `click`. For example, Ionic needs a clean way to be able to immediately fire click events on `touchend`, but also prevent the 300ms delayed click on iOS.

Additionally, I think the `HammerGesturesPlugin` itself should be an external plugin, not within the core, and the plugin would use this new Public API.

**Comment by vicb** [comment]
What about passing an EventManager binding to the bootstrap method ?

```
var binding =  [bind(EventManager)
        .toFactory(
            (ngZone) => {
              var plugins =
                  [new CustomPlugin(), new KeyEventsPlugin(), new MyCustomDomEventsPlugin()];
              return new EventManager(plugins, ngZone);
            },
            [NgZone])];

bootstrap(appCmp, bindings);
```

**Comment by tbosch** [comment]
I think a better idea might be to pass an own renderer to Angular.

After my refactoring in #3605 the renderer will have methods like
`addEventListener(element, name, callback)`, removeEventListener(element,
name, callback), ...
By providing your own renderer you can also have special semantics when
someone sets a property on an element by overrriding `setElementProperty`.
Or when an element is created by overriding `createElement()` (which we
will call for every element in the template).

In my opinion, special casing events is not right. Either a user takes the
defaults, or he wants to have full control over what Angular does to the
DOM...

**Comment by adamdbradley** [comment]
So @tbosch are you suggesting the EventManagerPlugins isn't the right approach to begin with, and should be removed? Or that angular will continue to have it's own array of event plugins, and not expose a public API, but with the new `addEventListener` and `removeEventListener` methods my use case would be covered at that point?

**Comment by tbosch** [comment]
Yes, I am suggesting that the EventManagerPlugins is not the right approach
and we should remove this extension point.

**Comment by mhevery** [comment]
After chatting with @tbosch here are some ideas: #3929

**Comment by mhevery** [comment]
Closing in favor of #3929
