### ISSUE TITLE
'pathParamsOrQueryParamsChange' checks different pathParams then 'paramsChange'?

### ISSUE THREAD

**Issue by ukrukarg** [angular/angular#38007]
# 🐞 bug report

### Affected Package
@angular/router

### Is this a regression?
Not sure.

### Description
I switched runGuardsAndResolvers from paramsChange to pathParamsOrQueryParamsChange (I don't want to trigger resolvers when matrix params change). Now resolvers are not longer rerun when path params change either.

I have a lazy router route like this:

    RouterModule.forRoot([{
      path: 'instances/:instanceId/page',
      loadChildren: () => import('./lazy-loaded/page.module').then(m => m.AdminModule),
    }], {
      paramsInheritanceStrategy: 'always',
    }),
that is supposed to load this module:

    RouterModule.forChild([{
      path: '',
      component: AdminComponent,
      resolve: {
        data: AdminResolver,
      },
      runGuardsAndResolvers: 'pathParamsOrQueryParamsChange',
    }])
I specify runGuardsAndResolvers: 'pathParamsOrQueryParamsChange' because the page uses a bunch of matrix params and I don't want to rerun resolvers when those change.

I would expect that AdminResolver will be called when I navigate from instances/abd/page to instance/def/page but it's never called.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-jxfove

You can see same exact app with runGuardsAndResolvers=paramsChange here: https://stackblitz.com/edit/angular-ivy-sp9fub

## 🔥 Exception or Error
No exceptions, just resolvers are not run.

## 🌍  Your Environment

**Angular Version:**
10

**Comment by Andrei0872** [comment]
I think the _problem_ is that the strategy behind `runGuardsAndResolvers` will run based on the current route object, which means that for such configuration:

```typescript
{
  path: '',
  component: AdminComponent,
  resolve: {
    data: AdminResolver,
  },
  runGuardsAndResolvers: 'pathParamsOrQueryParamsChange',
}
```

the path of the **current snapshot** and the **next snapshot** 

https://github.com/angular/angular/blob/88d68d2d216dba744dff7cc1ef93c8441d68c6a3/packages/router/src/utils/preactivation.ts#L157-L159

will always be empty.

This can be seen by following these steps:
* open the StackBlitz demo
* open dev tools
* look for the file `router.umd.js`
* search for the `shouldRunGuardsAndResolvers` and then place a breakpoint inside the function's block

---

A way to solve this would be to use a custom predicate function as the value for `runGuardsAndResolvers`, where the return value will depend on the parent routes:

```typescript
RouterModule.forChild([{
      path: '',
      component: AdminComponent,
      resolve: {
        data: AdminResolver,
      },
      runGuardsAndResolvers: (crt, next) => {
        const crtP = crt.parent;
        const nextP = next.parent;

        return !(crtP.url.every((s, i) => s.path === nextP.url[i].path))
      },
    }])
```

[StackBlitz](https://stackblitz.com/edit/angular-ivy-wbuscf?file=src%2Fapp%2Flazy-loaded%2Fpage.module.ts).

**Comment by ukrukarg** [comment]
I think the problem is that `paramsChange` and `pathParamsOrQueryParamsChange` work differently. They should either both run on current route or both run on entire url, instead of being inconsistent.

**Comment by atscott** [comment]
I agree, this is confusing since `paramsOrQueryParamsChange` and `paramsChange` both recursively check the parents as well while `pathParamsChange` and `pathParamsOrQueryParamsChange` only compare the activated segment. 

I'm not sure this is something we could change, as people would almost certainly be relying on the behavior as it is. I would recommend using a function for `runGuardsAndResolvers` as @Andrei0872 suggested
