### ISSUE TITLE
Add model-view type converters to form controls

### ISSUE THREAD

**Issue by baarney** [angular/angular#38008]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/forms

### Description
Add an optional converter to angular form controls, so that view-to-model and model-to-view value conversions are performed by the control, and all external users of the control (`control.value`, `control.setValue()`, `control.valueChanges.subscribe()` etc.) all see model values.

### Describe the solution you'd like

- Add a new interface, similar to the following:
```
export interface Converter<M, V> {
  // assumes always able to convert a valid model
  modelToView(model: M): V;

  // return undefined to indicate failure
  viewToModel(view: V): M | undefined;
}
```

- Add a converter to `AbstractControlOptions` to assign it to the control:
```
class WidgetConverter implements Converter<Widget, string> {
  ...
}

this.control = new FormControl('', { converter: new WidgetConverter(); });
```

- `control.value` returns a converted model value.
- `control.valueChanges` observable produces converted model values.
- `control.setValue()` accepts a model value.
- Internally, `ControlValueAccessor.writeValue` passes the view value.
- Conversion probably takes place before validation, so validators also work on the model value.
- Conversion may return an error, to be treated like any other validation error.
- Can also trigger a write-back on blur or submit to update the displayed value.

These are just all my thoughts on how it should work based on what I'm currently trying to achieve. More than happy to be corrected if there are better ways of doing this. Fundamentally, I'm just trying to shove the conversion inside the control and not have to worry about it every time I use that control.

### Describe alternatives you've considered
I can get most of this working using a custom CVA, but I can't see where to hook in to the model-to-view pipeline to intercept the `control.setValue()` call and call the converter `modelToView` method. 

Here's a stackblitz with a Widget:
- made up of a string code and a numeric catalogue number
- the users know them off by heart and just want to type straight into a single text field
- the input should allow upper/lower case text and an optional hyphen
- the output should always be formatted ABC-123.

https://stackblitz.com/edit/angular-ivy-2rhvar 

It mostly works, until you press the 'Set Value' button, when it does not convert the object back to the view type.

**Comment by basherr** [comment]
At least add a plunker with editable functionality so someone can look into the code as well.

**Comment by baarney** [comment]
I've updated the stackblitz link to go directly to the edit page.
