### ISSUE TITLE
Feature: Dynamic control over host element binding

### ISSUE THREAD

**Issue by SalathielGenese** [angular/angular#38015]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core (I believe).

### Description

Hello, folks from our loved community,

We are using Nebular in one of our apps and the `<nb-card-back/>` and `<nb-card-front/>`,  children of `<nb-flip-card/>`, turns out to be tricky. When using `<nb-card/>` right inside those children (as the docs suggest), it works great... But I've had the morning figure out why our form in the back element is not rendered :(

I just realized that the Nebular component doesn't like it when its cards are wrapped in another element: a component (like our form) or even a `<div/>`... So I have come up with one idea - to have the host element rendering optional for my form. But it doesn't seem to me as some that can be dynamic (and therefore, could be orchestrated with an attribute binding).

I came up with a second idea of allowing my component to be activated/selected as an attribute (like common directives) but next question is: **Can I know at runtime which selector matched my component?** While I'd like to blame the constraining design of those components, my problem is happening now and I believe that such a feature would not be much insane.

### Describe the solution you'd like

It would make sense to have one of these two solutions:

- The ability to control dynamically (as opposed to statically, as currently is), whether a component host should be rendered.
- Empower developers with the ability to access Ivy metadata like the component matched selector (element, attribute, etc) - maybe by injecting it into the component but components and directives only.

### Describe alternatives you've considered

- Send this issue link to the Nebular developer team!?

**Comment by Airblader** [comment]
Can you please post a full example of what you're trying to do?

**Comment by dylhunn** [comment]
This would be a major change we're unlikely to implement (hostless components)
