### ISSUE TITLE
HttpClient not following redirect on platform-server

### ISSUE THREAD

**Issue by digitalstaub** [angular/angular#38016]
Hi,

# 🐞 bug report

### Affected Package
platform-server, HttpClientModule

### Is this a regression?
tested 7.1.4 and 8.2.14. happens on both.

### Description

When using the http module in server mode, a redirected request doesn't follow the redirection and ends with:
`Http failure response for (unknown url): 0 Unknown Error`

## 🔬 Minimal Reproduction
```
git clone https://github.com/digitalstaub/universal-starter.git
cd universal-starter
npm i
npm run build:ssr
npm run serve:ssr
curl -I localhost:4000

```

## 🔥 Exception or Error
<pre><code>
HttpErrorResponse {
  headers: HttpHeaders {
    normalizedNames: Map {},
    lazyUpdate: null,
    headers: Map {}
  },
  status: 0,
  statusText: 'Unknown Error',
  url: null,
  ok: false,
  name: 'HttpErrorResponse',
  message: 'Http failure response for (unknown url): 0 Unknown Error',
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.26
Node: 12.8.0
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.26
@angular-devkit/build-angular              0.803.26
@angular-devkit/build-optimizer            0.803.26
@angular-devkit/build-webpack              0.803.26
@angular-devkit/core                       8.0.6
@angular-devkit/schematics                 8.0.6
@angular/cli                               8.3.26
@angular/pwa                               0.800.6
@ngtools/webpack                           8.3.26
@nguniversal/aspnetcore-engine             8.2.6
@nguniversal/express-engine                8.2.6
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.0.6
@schematics/update                         0.803.26
rxjs                                       6.5.4
typescript                                 3.5.3
webpack                                    4.39.2
</code></pre>

**Anything else relevant?**
the xhr2 module which is used seems to support http redirects

**Comment by petebacondarwin** [comment]
This appears to be happening even if Angular is running in the browser (i.e. with `ng serve`) so I wonder if the problem is actually with the response coming from `httpstat.us`?

**Comment by petebacondarwin** [comment]
Closing due to a lack of response.
