### ISSUE TITLE
angular Set Errors is not setting for the list of controls while return the list of error message in service  response for controls

### ISSUE THREAD

**Issue by MohamedSahir** [angular/angular#38017]
Problem :

I got a set of error from service response and a set of values from service response
based on field names I mapped the value and errors to the respective field FormControls. 

Value is setting for all the controls and working fine.
But in error, while the return from service it has the error and while come to component error is null. How?

**Note:
1) I am not using validators because I need to validate on Focus out not in value changes or blur.
2) This is an async Validations.
3)  Initially, I will get the response error message based on field names from service.**

I have a requirement to set the errors based on service response on component initialization:

In the form component, I have declared form groups and controls.

form.component.ts

    forms: FormGroup;
    
    in the ngOninit() life cycle
    this.forms = this.formService.initializeForm();
    // hit the service call and get a response and set the value and errors // value is setting and error is setting from service. when return to component it is nulll
    
    this.forms = this.formService.setFormValue(fieldList, this.forms);

Next Service

    export class FormsService {
        SERVER_URL: string = "http://localhost:8080/api/";
        constructor(private httpClient: HttpClient,
            private formBuilder: FormBuilder,
            private formCustomValidationService: FormCustomValidationService,
            private formValidationService: FormValidationService) {
        }
    
       InitializeForm(): FormGroup {
            let Form: FormGroup;
            Form = this.formBuilder.group({
                ProducNumber: ['', [Validators.required, Validators.minLength(1)]],
               ProductId: ['', [Validators.required, Validators.minLength(1)]],
               
            });
            return Forms;
        }
    
     
      
    
          setFormValue(successResponse: any, Forms: FormGroup): FormGroup {
                if (successResponse && successResponse.length > 0) {
                    successResponse.map((response) => {
                        switch (response.fieldName) {
                            case 'ProducNumber':
                                 Forms.controls?.ProducNumber.setErrors({ error: response?.ErrorMessage != null ? response?.ErrorMessage : null, info: response?.informationMessage != null ? response?.informationMessage : null });
                                 Forms.patchValue({ ProducNumber: response.value != undefined ? response?.value : '' }, { emitEvent: false, onlySelf: true });
                                break;
                            case 'ProductId':
                                Forms.controls?.ProductId.setErrors({ error: response?.ErrorMessage != null ? response?.ErrorMessage : null, info: response?.informationMessage != null ? response?.informationMessage : null });
                                Forms.patchValue({ ProductId: response.value != undefined ? response?.value : '' }, { emitEvent: false, onlySelf: true });
                                break;
                
        
                        }
                    });
                }
                return Forms;      // here error has set for all the fields 
            }
    
    
    Here return forms From service, have return all the errors but when comes into the component it is not. But have all the values which I set according to controls.

in component, it will return here from service but here null while return in service have errors.
  

       this.forms = this.formService.setFormValue(fieldList, this.forms);
         this.form.updateValueAndValidity();
            this.cdr.detectChanges();

**Comment by AndrewKushnir** [comment]
Hi @MohamedSahir, thanks for reporting the issue. Could you please also create a repro using [Stackblitz](https://stackblitz.com/), so we can better understand the problem? Thank you.

**Comment by MohamedSahir** [comment]
Hi @AndrewKushnir, 

1)I have n number of fields in real scenarios. For the sample, I have provided with one field and use case and problem.

Working Fine I update the controls individually, but not by forms inside components.
{
       this.formData.controls[controlName].setErrors({ error: result.ErrorMessage , info: 'sfsdf' });
        this.formData.updateValueAndValidity();
        this.cdr.detectChanges();
    }

Added Stackblitz: [demo](https://stackblitz.com/edit/samp-angular-services-with-mock-data-8p2bcc?file=app%2Fapp.component.ts)

**Comment by AndrewKushnir** [comment]
Hi @MohamedSahir, thanks for creating a repro. I've looked at the code of the repro and it seems like it can be simplified more to illustrate the problem. Could you please update it to keep just the minimum possible amount of code to illustrate and reproduce the issue? Thank you.

**Comment by MohamedSahir** [comment]
@AndrewKushnir  pls find[demo]( here https://stackblitz.com/edit/samp-angular-services-with-mock-data-ewtrjk?file=app%2Fapp.component.ts)

**Comment by AndrewKushnir** [comment]
Thanks for the update @MohamedSahir. I looked at the code and I'm still a bit confused. Could you please describe the expected vs actual behavior and provide an instructions on how to reproduce the issue? Thank you.

**Comment by MohamedSahir** [comment]
Expected Behaviour:
i have receive a set of errors, value, field names from service response. I have set the values ,setting errors. value is working fine. error is not setting,

Actual:


In the form service, I have setting error and value for the form controls. Value is updating properly on the fields, the error is not setting.

see the line in app.component.ts:
![image](https://user-images.githubusercontent.com/20682302/87634025-216d0b80-c75a-11ea-937a-233b14a203eb.png)

form.service.ts
![image](https://user-images.githubusercontent.com/20682302/87634068-32b61800-c75a-11ea-9aa9-4dd54169001d.png)

**Comment by AndrewKushnir** [comment]
Hi @MohamedSahir, thanks for additional information. I'm wondering if you could simplify the repro a bit more and may be get rid of the `form.service.ts` and replace it with a function calls in the demo app, so that it's more clear what the actual vs expected behavior is (it's still a bit unclear to me)? Thank you.

**Comment by MohamedSahir** [comment]
sorry i can't do a minimal version. already it is minimized and clearly states that problem , In real my use case I want to use forms as a service because we have a different configurable form across the application.if i move to the components and  set the errors each control and updateValueandValidity.it will work. My problem is  setformValue functions inside form service set the value and errors and value is working properly. why the error is setting and error becomes null after excecuting the next line of code,

**Comment by sonukapoor** [comment]
@MohamedSahir 

While performing the investigation, we've also come up with a simplified version of the repro and I've created a [new ticket](https://github.com/angular/angular/issues/38191) based on this information. Please subscribe to that issue for further updates on this issue.

Here is your modified [stackblitz ](https://stackblitz.com/edit/samp-angular-services-with-mock-data-coxyna?file=app%2Fapp.component.ts)that sets the errors with the fix mentioned in the new issue.
