### ISSUE TITLE
Production Build with empty 'WARNING in' message

### ISSUE THREAD

**Issue by contrastxp** [angular/angular#38019]
Hello there,
I have got 3 projects in my workspace which two of them are populated with the same modules and one is pretty filled.

If i want to build in production the same thing happen.

example:
Project A and B have the same deps but Project B has got issues
Project C which has got lot more deps has got the same issue as Project B

the compiler builds the projects but it says there is a WARNING in, but i cant figure out where exactly.
How can i solve that issue.

```
chunk {2} polyfills-es2015.a5fd3e876b9f30911149.js (polyfills) 36.8 kB [initial] [rendered]
chunk {3} polyfills-es5.6a3e2bf918a14c376fe8.js (polyfills-es5) 130 kB [initial] [rendered]
chunk {5} 5-es2015.139db91a96e64cc16236.js () 172 kB  [rendered]
chunk {5} 5-es5.139db91a96e64cc16236.js () 172 kB  [rendered]
chunk {0} runtime-es2015.5b4425ae80e14a6ef11e.js (runtime) 2.24 kB [entry] [rendered]
chunk {0} runtime-es5.5b4425ae80e14a6ef11e.js (runtime) 2.23 kB [entry] [rendered]
chunk {1} main-es2015.24abb95143d6dff40819.js (main) 949 kB [initial] [rendered]
chunk {1} main-es5.24abb95143d6dff40819.js (main) 1.02 MB [initial] [rendered]
chunk {4} styles.323c09a7136d74c65b9c.css (styles) 260 kB [initial] [rendered]
chunk {scripts} scripts.1064ca3406a50daf3ddc.js (scripts) 20.2 kB [entry] [rendered]
Date: 2020-07-12T20:02:54.397Z - Hash: 7f05f7baf157b6893e61 - Time: 26071ms

WARNING in 

WARNING in 

WARNING in 

WARNING in 

WARNING in 

```

**Comment by petebacondarwin** [comment]
I'm pretty confident that this is a CLI issue. And there is already an issue there for it: https://github.com/angular/angular-cli/issues/18231. So I will close this. If it turns out to be a FW issue, then that issue can be transferred here.
