### ISSUE TITLE
$localize error when gzip is enabled

### ISSUE THREAD

**Issue by dyingangel666** [angular/angular#38011]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/localize

### Description

 I have a i18n project which uses two languages (en, de) and all is working without any issues. Then we have enabled gzip_static compression on our nginx. I'm using a custom webpack config with the compression-webpack-plugin which precompresses the js and css files. With gzip_static on i now receive the following error and js is completely broken:

```
main.fac96a836ab6c611ad83.js:1 Uncaught ReferenceError: $localize is not defined
    at Module.zUnb (main.fac96a836ab6c611ad83.js:1)
    at u (runtime.4e1de19760d0e13f65d7.js:1)
    at Object.0 (main.fac96a836ab6c611ad83.js:1)
    at u (runtime.4e1de19760d0e13f65d7.js:1)
    at t (runtime.4e1de19760d0e13f65d7.js:1)
    at Array.r [as push] (runtime.4e1de19760d0e13f65d7.js:1)
    at main.fac96a836ab6c611ad83.js:1
```

I'm also using scully in this project as static site generator, but i have it also tested without scully and the same error pops up. I think it has something to do with the custom webpack config and when $localize stuff is parsed. It currently looks like the files are gzipped before the $localize stuff is parsed

## 🔬 Minimal Reproduction

https://marketplace.staging.softgarden.io/de/

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.11
Node: 14.5.0
OS: darwin x64

Angular: 9.1.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.11
@angular-devkit/build-angular     0.901.11
@angular-devkit/build-optimizer   0.901.11
@angular-devkit/build-webpack     0.901.11
@angular-devkit/core              9.1.11
@angular-devkit/schematics        9.1.11
@angular/cdk                      9.2.4
@angular/cli                      9.1.11
@ngtools/webpack                  9.1.11
@schematics/angular               9.1.11
@schematics/update                0.803.28
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by dyingangel666** [comment]
I've now switched to the npm tool gzipper to make sure gzip is done after angular build has been finished and it's working now with this tool. So it really seems to be that with the custom webpack loader the gzipping start to run before the $localize stuff was parsed.

**Comment by petebacondarwin** [comment]
I was going to say that it appeared that something funny was going on in WebPack, since the compile-time translation will remove all references to `$localize`.
I assume that we can close this then?

**Comment by dyingangel666** [comment]
Yeah that's ok for me since my issue is solved by using another tool ;-)

**Comment by petebacondarwin** [comment]
Great thanks!
