### ISSUE TITLE
router.url provides Invalid Url  in refresh  under app.component.ts

### ISSUE THREAD

**Issue by MohamedSahir** [angular/angular#38018]
In angular app, I have localhost:4200 is the default URL. If I change the URL in browser as localhost:4200 /login hit Enter and the router, URL provides '/'
app.component.ts ngOninit Lifecycle hooks
  ngOnInit() {

   ```
 let loginUrl = this.router.url == '/login' ? true : false;
    if(loginUrl){
      this.router.navigateByUrl('/login');
    }
```

**Comment by basherr** [comment]
[Check this routing](https://stackoverflow.com/questions/45523871/angular-4-routing) and implement accordingly. Try some research before opening any issue.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
