### ISSUE TITLE
initialNavigation with lazy loading crashes application with no error

### ISSUE THREAD

**Issue by GeorgeHulpoi** [angular/angular#38010]
# 🐞 bug report

### Is this a regression?
No

### Description

When you have routes using lazy loading and initialNavigation enabled, the app-root or the bootstrap component is not rendered.

## 🔬 Minimal Reproduction

https://github.com/GeorgeHulpoi/ng-initialNavigation-lazy-loading

## 🔥 Exception or Error

None (it should be at least...)

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.1.7
Node: 12.17.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.7
@angular-devkit/core         9.1.7
@angular-devkit/schematics   9.1.7
@schematics/angular          9.1.7
@schematics/update           0.901.7
rxjs                         6.5.4
</code></pre>

**Comment by basherr** [comment]
You must be missing something. If you can `reproduce` or have a look at this [Plunker](https://stackblitz.com/edit/angular-ivy-mcm51t?embed=1&file=src/app/app-routing.module.ts&view=editor)and compare it with your implementation.

**Comment by GeorgeHulpoi** [comment]
> You must be missing something. If you can `reproduce` or have a look at this [Plunker](https://stackblitz.com/edit/angular-ivy-mcm51t?embed=1&file=src/app/app-routing.module.ts&view=editor) and compare it with your implementation.

That Plunker project doesn't have the initialNavigation enabled. To use Angular Universal on Angular 9+ you need initialNavigation enabled, that's why is a need.

**Comment by atscott** [comment]
Hi @GeorgeHulpoi, there are several issues with the reproduction:

* forRoot should only be called once. Child modules should use `forChild`
* your import statements are incorrect. Try using relative paths
* `AppModule` has no routes in its `RouterModule.forRoot`

Here is a more or less fixed version of your example: https://stackblitz.com/edit/angular-ivy-h1j5h1?file=src%2Fapp%2Fmodules%2Fapp.ts

I would recommend starting with reading the router guide and posting questions on StackOverflow to get some support on how to set up your project.
