### ISSUE TITLE
node_modules/__ngcc_entry_points__.json causes issues with `pnpm install`

### ISSUE THREAD

**Issue by leonard84** [angular/angular#38023]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

"@angular/compiler": "^10.0.3"

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular 8. I didn't try Angular 9.
It worked before `__ngcc_entry_points__.json` was added to `node_modules` so I'd say yes.

### Description

Under some circumstances Angulars ngcc create a file `node_modules/__ngcc_entry_points__.json`, this file conflicts with the package manager `pnpm`. 

## 🔬 Minimal Reproduction

You need to have `pnpm` installed as package manager.

1. Run `ng new --package-manager pnpm test-issue`
2. As I couldn't find a way to get the `node_modules/__ngcc_entry_points__.json` generated in this test project, simply put this sample `__ngcc_entry_points__.json` into `node_modules`
[__ngcc_entry_points__.zip](https://github.com/angular/angular/files/4912911/__ngcc_entry_points__.zip)
3. Run `pnpm install`

## 🔥 Exception or Error
<pre><code>
 ERROR  "./test-issue/node_modules/__ngcc_entry_points__.json" is not a directory
at tryReadProjectManifest     ../../../../../../../AppData/Roaming/npm/node_modules/pnpm/lib/node_modules/@pnpm/read-project-manifest/lib/index.js:89  const err = new Error(`"…
at async readProjectManifest  ../../../../../../../AppData/Roaming/npm/node_modules/pnpm/lib/node_modules/@pnpm/read-project-manifest/lib/index.js:17  const result = await try…
at readProjectManifestOnly    ../../../../../../../AppData/Roaming/npm/node_modules/pnpm/lib/node_modules/@pnpm/read-project-manifest/lib/index.js:25  const { manifest } = awa…
at async safeReadProjectMan…  ../../../../../../../AppData/Roaming/npm/node_modules/pnpm/lib/node_modules/@pnpm/link-bins/lib/index.js:126             return await read_projec…
at async getPackageBins       ../../../../../../../AppData/Roaming/npm/node_modules/pnpm/lib/node_modules/@pnpm/link-bins/lib/index.js:76              ? await safeReadProjectM…
at all
at default                    ../../../../../../../AppData/Roaming/npm/node_modules/pnpm/lib/node_modules/@pnpm/link-bins/lib/index.js:30              const allCmds = R.unnest…
at all
at default                    ../../../../../../../AppData/Roaming/npm/node_modules/pnpm/lib/node_modules/@pnpm/headless/lib/index.js:210              await Promise.all(opts.p…
at async _install             ../../../../../../../AppData/Roaming/npm/node_modules/pnpm/lib/node_modules/supi/lib/install/index.js:97                 await headless_1.default…
</code></pre>

## 🌍  Your Environment

**Angular Version:**
There seems to be an issue with the version detection when `pnpm` is used

```
Angular CLI: 10.0.1
Node: 14.4.0
OS: win32 x64

Angular: 10.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       <error>
@angular-devkit/build-angular   0.1000.1
@angular-devkit/core            <error>
@angular-devkit/schematics      <error>
@angular/cli                    10.0.1
@schematics/angular             <error>
@schematics/update              <error>
rxjs                            6.5.5
typescript                      3.9.6
```

**Anything else relevant?**
no

**Comment by JoostK** [comment]
Using pnpm is generally not supported, please see https://github.com/angular/angular/issues/32087#issuecomment-523225437 for details. So even if pnpm would not error because of the manifest file, it may still not work. We're not actively testing with pnpm and ngcc's model is not really compatible with the way pnpm operates.

**Comment by leonard84** [comment]
That is unfortunate, the scarce documentation regarding package managers suggests otherwise. Maybe you could print out a Warning/Error when `pnpm` and `ivy` are active.

The funny thing is, it seems to work fine, when I delete this json file I can install new modules if needed, and `ng build` runs without problems, So if I understand it correctly it then modifies the shared packages in `node_modules/.pnpm`?

**Comment by radarsu** [comment]
pnpm assumes node_modules contains only directories. I believe **this assumption is correct**.

ngcc compiler adds __ngcc_entry_points__.json to node_modules directly. I believe that file should be generated under some dot-directory (like `.angular`, `.ng` or `.ngcc`) and not bloating node_modules with json file.

**Comment by petebacondarwin** [comment]
This should be solved by the ng-linker being developed to replace ngcc. Please follow along with the progress here: https://github.com/orgs/angular/projects/2
