### ISSUE TITLE
Pipes and directives from CommonModule not being recognised when i upgraded from Angular 8 to Angular 9 and also Angular 10

### ISSUE THREAD

**Issue by abbasogaji** [angular/angular#38021]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/cli @angular/core version 10.0.2

### Is this a regression?

 Yes, the previous version in which this bug was not present was: @angular/cli @angular/core version 8

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

 - error NG8001: 'router-outlet' is not a known element:
 - error NG8002: Can't bind to 'ngClass' since it isn't a known property of 'div'.
 - error NG8004: No pipe found with name 'async'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 10.0.2
Node: 12.16.3
OS: win32 x64

Angular: 10.0.3
... animations, common, compiler, compiler-cli, core, forms     
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.1000.2
@angular-devkit/build-optimizer   0.1000.2
@angular-devkit/build-webpack     0.1000.2
@angular-devkit/core              8.1.3
@angular-devkit/schematics        10.0.2
@angular/cdk                      10.0.1
@angular/cli                      10.0.2
@angular/fire                     5.2.3
@angular/material                 10.0.1
@ngtools/webpack                  10.0.2
@schematics/angular               10.0.2
@schematics/update                0.1000.2
rxjs                              6.6.0
typescript                        3.9.6
webpack                           4.43.0

</code></pre>

**Anything else relevant?**

# Current Workaround
i set enableIvy Compilation Option to false
```json
  "angularCompilerOptions": {
    "enableIvy": false
  }
```

**Comment by basherr** [comment]
Can you [reproduce](https://stackblitz.com/edit/angular-ivy-q9qpez?embed=1&file=src/app/app.component.ts&view=editor) this?

**Comment by spock123** [comment]
@abbasogaji  I had this issue as well, after closing everything, removing node_modules, package-lock , everything worked again .

**Comment by petebacondarwin** [comment]
@abbasogaji - please can you delete your node_modules and reinstall them. If that still does not solve the problem then please can you provide us with a reproduction so that we can diagnose the problem.

**Comment by abbasogaji** [comment]
@petebacondarwin i have just noticed something weird. In my Angular project i use Cloudinary, (Currently cloudinary doesnt support Angular 10) when i import cloudinary in my app.module.ts the error shows, but we ever i remove cloudinary it works fine


```typescript

 imports:      [
     BrowserModule,
    AppRoutingModule,
    ReactiveFormsModule,
    FormsModule,
    SharedModule,
    HttpClientModule,

   .....

     CloudinaryModule.forRoot(cloudinaryLib, { cloud_name: 'xxxxxxx', upload_preset : 'xxxxxxx', api_key : 'xxxxxxxxxxxxx'}),

  .....
  
  ],
```


The reproduction works fine 

https://stackblitz.com/edit/angular-ivy-anrejs

**Comment by petebacondarwin** [comment]
If cloudinary does not support v10, then this could be the problem. If `ngcc` (Angular's compatibility compiler) is unable to process cloudinary, it could be blocking the other libraries (such as `@angular/common`) from being processed.

Can you try cleaning out `node_modules` and then running

```
node_modules/.bin/ngcc -l debug
```

**Comment by abbasogaji** [comment]
@petebacondarwin  i upgraded to the latest cloudinary version and everything seems to be okay now

**Comment by petebacondarwin** [comment]
Great! Glad you are sorted. I'll close this issue then.
