### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError error using async pipe

### ISSUE THREAD

**Issue by majidmadadi** [angular/angular#38022]
I get this error(ExpressionChangedAfterItHasBeenCheckedError) when I use async pipe! Here is the code [Stackblits](https://stackblitz.com/edit/angular-so58276430-attempt-solution-1lnzpr). I don't know where is the problem?

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mlc-mlapis** [comment]
[**@majidmadadi**](https://github.com/majidmadadi) Yep, you are changing the \*ngIf condition state in one CD cycle. Initially, it's an observable object before the first emit, and then the first emitted value of `true`.

**Comment by majidmadadi** [comment]
> [**@majidmadadi**](https://github.com/majidmadadi) Yep, you are changing the *ngIf condition state in one CD cycle. Initially, it's an observable object before the first emit, and then the first emitted value of `true`.

That's right. I didn't know how change-detection internally works. 🙏
