### ISSUE TITLE
Guidelines for Unrelated Content on Angular.io?

### ISSUE THREAD

**Issue by Achilles1515** [angular/angular#38025]
When visiting the Angular.io site, one is currently met with a #BlackLivesMatter banner - a topic **completely** unrelated to the Angular web framework.

Are there any posted guidelines regarding what content unrelated to Angular is acceptable on the documentation site?

I was informed on another issue thread that "silence [about social injustice issues] is violence", so it would probably look good if we added a whole bunch more banners - statements about issues like pedophilia, human trafficking, maybe even saving the whales! I've always thought it would be cool to have some NBA scores up there too!

Anyway, those are topics for their own discussion threads. Here, I am simply looking to know what content unrelated to Angular is acceptable to add to the Angular documentation site? This would be helpful for future pull requests from contributors.

Thanks!

**Comment by ericmartinezr** [comment]
That is a good question considering that this issue https://github.com/angular/angular/issues/37931 was closed as "offtopic" when it's directly related to https://github.com/angular/angular/pull/37407, so... it's offtopic, or it's not? It's funny how a company that promotes "equality" then closes all the issues as "too heated" or "offtopic" when they don't follow their narrative.

Thank you @Achilles1515 for speaking for people that's constantly being silenced and ignored. I truly appreciate it.

**Comment by Achilles1515** [comment]
> That is a good question considering that this issue #37931 was closed as "offtopic" when it's directly related to #37407, so... it's offtopic, or it's not? It's funny how a company that promotes "equality" then closes all the issues as "too heated" or "offtopic" when they don't follow their narrative.
> 
> Thank you @Achilles1515 for speaking for people that's constantly being silenced, ignored and censored. I truly appreciate it.
I too am still scratching my head about why that issue was closed as being "off topic". If I go to Angular.io I am met with #BlackLivesMatter along with the Angular logo - the main items mentioned in that issue, along with a simple question to the team regarding the logo creation process and a comment about oppression that the logo conveys. Apparently #NotAllFeelingsMatter (or even warrant discussion).

Anyway, let's pause all further comments until we hear from the team. I don't want this issue to get closed for being "heated" or "off topic". I have about 30 PRs cooking in my head about ways to "spice up" the documentation site and am genuinely looking for an answer about guidelines.
