### ISSUE TITLE
Links to StackBlitz example app and tests in testing guide broken

### ISSUE THREAD

**Issue by pas2al** [angular/angular#38036]
# 📚 Docs or angular.io bug report

### Description

Both links to StackBlitz are broken within this section:

> For the sample app that the testing guides describe, see the **sample app**.
> 
> For the tests features in the testing guides, see **tests**.

### What's the affected URL?**
https://angular.io/guide/testing-code-coverage
https://angular.io/guide/testing-services
https://angular.io/guide/testing-components-basics
https://angular.io/guide/testing-components-scenarios
https://angular.io/guide/testing-attribute-directives
https://angular.io/guide/testing-pipes
https://angular.io/guide/test-debugging

**Comment by gkalpak** [comment]
Thx for reporting this, @pas2al :+1:
This is a result of our recent breaking up the testing guide into multiple ones. I have submitted #38038 to fix it.

**Comment by pas2al** [comment]
Sure, no problem. I really like the new structure of the testing guide. Thanks for the quick fix and keep up the good work!
