### ISSUE TITLE
Changing maxlength dynamically of a textarea fires form valueChanges twice after upgrading to Angular 10

### ISSUE THREAD

**Issue by maddy2894** [angular/angular#38040]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms and valueChanges

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular 8

### Description

I recently upgraded our application from Angular 8 to Angular 10. After much research, the upgrade was successful. Following the upgrade, I found a bug on form valueChanges with dynamically changing textarea maxlength. I am dynamically changing the maxlength of the textarea based on previous input field in same form. When doing so, form valueChanges gets fired twice and eventually causing `Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked` error. I have produced a minimal repo below with one textarea and changing it's maxlength dynamically while typing in it.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-oubtwj
Try giving any input to textarea and observe stackblitz console

## 🔥 Exception or Error
<pre><code>

Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked
</code></pre>

## 🌍  Your Environment

**Angular Version: 10.0.3**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.2
Node: 12.12.0
OS: darwin x64

Angular: 10.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.2
@angular-devkit/build-angular     0.1000.2
@angular-devkit/build-optimizer   0.1000.2
@angular-devkit/build-webpack     0.1000.2
@angular-devkit/core              10.0.2
@angular-devkit/schematics        10.0.2
@angular/cdk                      10.0.1
@angular/cli                      10.0.2
@angular/material                 10.0.1
@ngtools/webpack                  10.0.2
@nguniversal/builders             10.0.1
@nguniversal/common               10.0.1
@nguniversal/express-engine       10.0.1
@schematics/angular               10.0.2
@schematics/update                0.1000.2
rxjs                              6.6.0
typescript                        3.9.6
webpack                           4.43.0
</code></pre>

**Comment by AndrewKushnir** [comment]
Hi @maddy2894, thanks for providing a repro.

I performed further investigation and found out that the problem appeared because template-driven and reactive forms approaches were used together. I've cloned your repro and updated it to use `setValidators` function call to update validators for FormControl, [see here](https://stackblitz.com/edit/angular-oubtwj-j3adj6?file=src%2Fapp%2Fform-field-hint-example.ts) (and also removed the `maxlength` property from the template) - the error doesn't happen now.

I will close this ticket for now, feel free to reopen if the problem still exists.

Thank you.

**Comment by maddy2894** [comment]
Hi @AndrewKushnir thank you for the quick response, I can confirm that the error is solved but maxlength functionality is not working. In the [repo](https://stackblitz.com/edit/angular-oubtwj-j3adj6?file=src%2Fapp%2Fform-field-hint-example.ts) you shared, the textarea allows me to type more than the maxlength limit. Is this an intended behaviour?

Cheers.

**Comment by AndrewKushnir** [comment]
@maddy2894 thanks for the reply. I just wanted to demonstrate the overall approach (that the FormControl's validators should be set using FormControl API). The final solution might require additional updates (may be creating a custom validator) based on the logic that you want to have in your component(s). Thank you.

**Comment by maddy2894** [comment]
Okay cool. Thank you for your time.
