### ISSUE TITLE
Dont put political messages on your website, make syou look bad

### ISSUE THREAD

**Issue by andremendes2m19** [angular/angular#38041]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by mgechev** [comment]
Hey @andremendes2m19, the message we've shared is in solidarity with the black community. Angular consists of a very diverse set of individuals and the least we could do in hard moments for the highly impacted minorities is to show our support.

**Comment by mlc-mlapis** [comment]
[**@mgechev**](https://github.com/mgechev) I am a little afraid that it is not carefully watched who the spokespersons of this minority are and what thoughts, apart from the generally positive ones, come from this community. We, in Europe, still have quite subconsciously what thoughts and what subsequent actions have taken place in our countries in the recent past. I have an increasingly compelling feeling that things are not going in the direction, we really want.
