### ISSUE TITLE
O bug acarreta na duplicação de informações

### ISSUE THREAD

**Issue by AdamTeodoro** [angular/angular#38052]
# 🐞 bug report

### Affected Package
'@angular/core';

### Is this a regression?
Esse problema pode ser encontrado na versão anterior.

### Description
Código Simples
TypeScript: 
const vagas = [
  { nome: 'vendedor', remuneracao: 1000, cidade: "cidade" },
  { nome: 'analista', remuneracao: 2000, cidade: "cidade"  },
];
HTML:
<div class="vagas" *ngFor="let vaga of vagas">
{{vaga.nome}}<br/>
{{vaga.remuneracao}}<br/>
{{vaga.cidade}}<br/>
</div>

Descrição do resultado: 
O resultado é a exibição de quatro vagas,
respectivamente:
  { nome: 'vendedor', remuneracao: 1000, cidade: "cidade" },
  { nome: 'analista', remuneracao: 2000, cidade: "cidade"  },
  { nome: 'vendedor', remuneracao: 1000, cidade: "cidade" },
  { nome: 'analista', remuneracao: 2000, cidade: "cidade"  },

## 🔬 Minimal Reproduction

onde o problema acontece:
https://click-rh.web.app/vagas

**Angular Version: Ultima versão

**Comment by JoostK** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by AdamTeodoro** [comment]
Eu entendo a falta de vontade, mas o desprestigio é do framework.

**Comment by AdamTeodoro** [comment]
Enter in https://click-rh.web.app and press F5

**Comment by petebacondarwin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.


---


Obrigado por relatar este problema. No entanto, você não forneceu informações suficientes para entender e reproduzir o problema. Consulte [nossas diretrizes de envio] (https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) para entender por que não podemos agir sobre questões que não são importantes em formação.

Se o problema persistir no seu aplicativo, [abra um novo problema] (https://github.com/angular/angular/issues/new/choose) e siga as instruções no modelo de problema.
