### ISSUE TITLE
ngModule needs to allow us to point to index.ts files too.

### ISSUE THREAD

**Issue by Javaman2** [angular/angular#38056]
# 🚀 feature request

### Relevant Package
ngModule
 

### Description
 The ngModule class closely resembles the Javascript module system (import and export statements),  but does not operate in the same manner.  

If we catalog modules based on the simple (import, export, filename) model via an index.ts,

```
// content of an Index.ts file
 export * from './componentName';
 export * from '/componentName2';
 export * from '/functionName';

``` 
We are able to combine imports like this:

```
import {componentName, componentName2, functionName } from './folderNameWithIndexFile';
```

This is very helpful and a requirement for NPM Packages. 

Unfortunately, the NGMODULE requirements duplicate content and add an extra level of complexity. 

### Describe the solution you'd like

Any Angular Compile should be able to discover anything it needs to compile based only on decorators (class names, function names, etc). Currently the imports and exports section of the NGModule seem to have nothing to do with the native module system.  Yes, the Angular Cli attempts to add new components, pipes, directives, services automatically but why?

All components, pipes, directives and services use decorators unique to Angular.  This allows a compiler to discover them without the need of a file named app.module.ts which is a decorated class of type ngModule.

### Describe alternatives you've considered
 
1) The compile based on a configuration setting can satisfy all Angular requirements, and provide an index.ts file based on public private properties of each ts class it needs. 

Adopt the namespace concept just like .NET does.  Each import in .NET. requires one line of code per import, but they are implicit to the build; which finds all information at compile time. 

Intellisense in .NET finds all the folders/files automatically without any index concept.

**Comment by Airblader** [comment]
How should the Angular compiler know what you want to export in your index.ts? Sometimes we explicitly don't want to export certain services (or other things) because they aren't considered to be API. On the other hand I might want to export not just the module but also a component so that it can be used programmatically. In other words, the premise that this is duplicate information is incorrect.

There's also no restriction on file structure right now. I could have my NgModules in one folder and reference components and services and other modules in it which lie anywhere else in the project. Generating the NgModule from the file structure therefore doesn't work (without being a breaking change).

**Comment by Javaman2** [comment]
> How should the Angular compiler know what you want to export in your index.ts?
A possibility to to mark exports as private for those that shouldn't be public.

> In other words, the premise that this is duplicate information is incorrect.
Not true any time any code or configuration is duplicated it's duplicated. If the pattern is basically the same then the required duplication of effort is a code smell. 
>Generating the NgModule from the file structure therefore doesn't work (without being a breaking change).
Again not true, all NGModules are discoverable based solely on the decorator @ngModule.

I'm talking about what compiler lexing and parsing can do for us, the missing parts of what's not being done here.  As I mentioned earlier .NET doesn't have any of these issues.  The compiler uses namespaces to define content within the package using only folder structure and types. 

The NgModule system to me is way more complex than it has to be which indicates that it can't discover annotations and that it doesn't hold Folder Structure namespace conventions as it's primary concern.  Rather it registers components as we add them to a NGmodule addition which shouldn't need to be there at all. 

The compiler should be able to discover any component in a folder as follows:
```
Components
   A
   B
   C
   SubFolder
      A
      B
      C
```
The namespaces being:  

Components.A, Components.B, Components.C and
Components.Subfolder.A, Components.Subfolder.B, Components.Subfolder.C 

Fully discoverable and fully unique.

**Comment by Airblader** [comment]
But you're assuming that all projects have that structure, which is simply not true. I can have `src/modules/foo.module.ts` which contains components located in `src/components/bar.component.ts`. Therefore switching to such a structure is a forced breaking change.

**Comment by Airblader** [comment]
> A possibility is simply the class or function definition being marked as public or private.

This would collide with TypeScript.

**Comment by mlc-mlapis** [comment]
[**@Javaman2**](https://github.com/Javaman2) In monorepo environment you simply organize NgPackages differently for each built application, so it's not possible to fix them to the folder/file structures.

**Comment by Javaman2** [comment]
>I can have src/modules/foo.module.ts which contains components located in src/components/bar.component.ts

Be it a class or function, the file system disallows duplicate naming, so using that to ensure uniqueness we simply need to import what we want to use.  We're not breaking anything using the existing import system.

```
// we don't need the module system to import.
import (something) from "../src/components/bar.component.ts
```
>This would collide with TypeScript.

I think your view point is from the NGModule perspective.  I'm saying we don't need NGModules, or at a minimum the architecture is a code smell.  The compile can and should take care of all discovery.  Typescript already supports public and private so there's no conflict or breaking changes.  The only breaking change would be if the new compiler functions doesn't allow for NGModules which by a simple scan would know if one existed or not.

**Comment by Javaman2** [comment]
@mlc-mlapis

>In monorepo environment you simply organize NgPackages differently for each built application, so it's not possible to fix them to the folder/file structures.

Actually it is, because we have the ability to configure different build types and folders to contain.  It's just a configuration of a specific build name.

**Comment by mlc-mlapis** [comment]
[**@Javaman2**](https://github.com/Javaman2) Do we understand each other? The NgPackages are totally on different places than components and other elements inside monorepo structure.

**Comment by Javaman2** [comment]
> [**@Javaman2**](https://github.com/Javaman2) Do we understand each other? The NgPackages are totally on different places than components and other elements inside monorepo structure.

No I'm may not be aware of NgPackages.  Please explain.

**Comment by mlc-mlapis** [comment]
[**@Javaman2**](https://github.com/Javaman2) EDIT: Sorry, I meant NgModules, of course.

**Comment by Javaman2** [comment]
> [**@Javaman2**](https://github.com/Javaman2) EDIT: Sorry, I meant NgModules, of course.

The dist folder contains the result of the compile for publishing to NPM (we know that) but what if put into that folder is only the result of a build which is totally controlled by the Angular.json build definition.  When we look at the package.d.ts file in the dist folder, we see it points to the public.api.ts file. Which is the exports files required by NPM packages.

**Comment by mlc-mlapis** [comment]
[**@Javaman2**](https://github.com/Javaman2) Hmm, sure, but I am talking about the structure and locations of source files in monorepo repository, that can be far different in comparison with a standalone application.

**Comment by Javaman2** [comment]
> [**@Javaman2**](https://github.com/Javaman2) Hmm, sure, but I am talking about the structure and locations of source files in monorepo repository, that can be far different in comparison with a standalone application.

No source file can have the same name, so the combination of name and type is all the compiler needs to know. What about functions? Still there's no collisions because you can have multiple exported functions in one file, but you cannot have duplicate function names, so the fully qualified name of an exported function would be. 

```
folderName.FileName.FunctionName
```

**Comment by Javaman2** [comment]
Ahh yes, others have seen the light too.  
https://github.com/angular/angular/issues/37904

**Comment by alxhub** [comment]
You _can_ import things from an index file into the ES module to use in an `NgModule` declaration. `NgModule`s are designed around the idea of an explicit compilation context for components though - it was a very intentional choice to not "auto-discover" components in an application. This would be especially problematic for code published in libraries - without a direct import to something in the library, the compiler won't even be aware of the existence of those components.

This FR isn't really actionable for us - we're not going to make any substantial changes to `NgModule`s. Instead, our focus is on reducing the need to author `NgModule`s via the new Standalone Components functionality.
