### ISSUE TITLE
Library incombatible with Angular 10

### ISSUE THREAD

**Issue by chrisaige** [angular/angular#38069]
# 🐞 bug report

### Affected Package
The issue is with ngcc or with the way our library is build/designed (https://github.com/porscheinformatik/material-addons)

### Is this a regression?

I dont think so.

### Description

The problem seems like the ngcc is unable to parse the @porscheinformatik/material-addons 
But in other projects it works with no problems and when running the ngcc no errors are logged. Only one warning, but this warning is logged in working and non working projects alike.

<pre><code>
Warning: Unable to fully load D:/temp/angular-working-proj/node_modules/@porscheinformatik/material-addons/bundles/porscheinformatik-material-addons.umd.js for source-map flattening: ENOENT: no such file or directory, open 'D:/temp/
angular-working-proj/node_modules/@porscheinformatik/material-addons/bundles/porscheinformatik-material-addons.umd.js.map'
</code></pre>

## 🔬 Minimal Reproduction

To test one of the examples run 
"npm i" 
"ng serve" on the unzipped directory

Example that fails:
[angular-test-proj.zip](https://github.com/angular/angular/files/4923456/angular-test-proj.zip)

Example that does not fail:
[angular-working-proj.zip](https://github.com/angular/angular/files/4923458/angular-working-proj.zip)

## 🔥 Exception or Error
<pre><code>
ERROR in node_modules/@porscheinformatik/material-addons/lib/readonly/readonly-form-field.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (@porscheinformatik/material-addons) which declares ReadOnlyFormFieldModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library
is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

1 export declare class ReadOnlyFormFieldModule {
</code></pre>

Are we doing something wrong in our library? If so what? We are unable to find the issue :(

**Comment by petebacondarwin** [comment]
The problem is that your package.json has invalid paths to the ESM files:

For example:

```
"es2015": "fesm2015/porscheinformatik-material-addons.js",
```

But this path does not exist in the npm bundle: https://unpkg.com/browse/@porscheinformatik/material-addons@10.0.4/

**Comment by petebacondarwin** [comment]
So ngcc is processing nothing.

**Comment by petebacondarwin** [comment]
To prove the point you can add the following file to the broken test project linked in the original post:

**ngcc.config.js**

```
module.exports = {
  packages: {
    '@porscheinformatik/material-addons': {
      entryPoints: {
        '.': {
          override: {
            es2015: 'esm2015/porscheinformatik-material-addons.js',
            fesm2015: 'esm2015/porscheinformatik-material-addons.js',
            module: 'esm2015/porscheinformatik-material-addons.js',
          }
        }
      }
    }
  }
};
```

This configures ngcc to use the correct file paths for these properties of the package.json.

**Comment by petebacondarwin** [comment]
The solution is to release a new version of the library with the package.json paths fixed.
The workaround (in a current application that uses this library) is to apply the `ngcc.config.js` file above in the root of the application project.

**Comment by Laess3r** [comment]
Hello!
@petebacondarwin  thank you very, very much for this detailled explanation! We were able to add the missing fesm2015 folder to our library.

https://unpkg.com/browse/@porscheinformatik/material-addons@10.0.6/

**Comment by petebacondarwin** [comment]
Glad you are back in the game!
I was in Salzburg last year!
