### ISSUE TITLE
framework level support to reuse static parts of ssr

### ISSUE THREAD

**Issue by sod** [angular/angular#38078]
# 🚀 feature request

I already have something running, but without first level framework support, it introduces footguns and boilerplate.

As an example lets use https://angular.io/. Look at the footer:

![image](https://user-images.githubusercontent.com/905328/87570497-0bfbd100-c6c9-11ea-8555-915f5744c827.png)

Thats completely static. It's a waste to 1) ship that again via javascript & 2) render it again via javascript. When it's already right there in the browser (now ignoring that angular.io neither uses ssr, nor works without javascript - but our page does).

What I'd like to have was something like a `static` directive:

```typescript
<footer *static></footer>
```

Now this is what the framework could do:

* the server
  * flag all styles that are created inside `<footer *static>...</footer>` for reuse in the browser
* the compiler
  * throw an error if you do anything dynamic inside - like adding an event listener
  * create a dynamic component of the insides and put that into a seperate chunk, that is only loaded, when ssr is missing. Of course I could create an NgModule and bootstrap that via ngComponentOutlet. But it would be so much nicer, if the framework would handle that
* the browser
  * pick the ssr styles
  * pick the ssr DOM
  * if ssr is missing, load the contents async and render it

--

I mean, if you use ssr, you already optimize the page to work without javascript. And most of our page does. We intentionally use urls instead of click handler most of the time. Or hidden radio buttons for accordions and checkboxes for switches. We could use event bubbling to bind click handler on a static container to support pushState navigation on static content.

With native support with something like above we could stencil out huge chunks of the page.

**Comment by alan-agius4** [comment]
Hi @sod, 

This feature request seems to be a covered by another request for DOM hydration.

See: https://github.com/angular/angular/issues/13446

**Comment by sod** [comment]
This is not hydration. This is reusing DOM, that is static. No hydration needed at all.

**Comment by alan-agius4** [comment]
@sod, would this be addressed though with rehydration? Where an element will only be rendered again if it changes, ie: if the element is static it I’ll not be re-rendered on the client side.

**Comment by sod** [comment]
Depends how the hydration is implemented. If there is actually something already in the works by the team, I'm excited what we can do with it.

Profiling pages like https://www.nytimes.com/ which uses ReactDOM.hydrate - that doesn't look promising at all. Pretty horrifying actually I have to say.

Angulars approach seems brute force at first. But I yet have to see proof that trying to sync up the app with existing DOM is actually faster.

The thing I'm trying to do is just do less scripting and reduce bundle size. Like I showed in the example above. I don't want the frontend to sync up the DOM ... that sounds like even more javascript to ship and to run. What I wanna do is remove parts of the app entirely that are sufficiently served by ssr. Aka:

* don't try to sync up the footer
* don't render it
* actually don't even ship the javascript that creates the footer

I already have that working in our app, and it has pretty profound performance impact. Like cutting the javascript bundle and initial scriping by 30%, just by reusing static parts that were shipped via ssr and getting the interactive parts up-and-running faster.

**Comment by alan-agius4** [comment]
@sod, rehydration is indeed something that we are looking at. Still from a very high level but we see that rehydration offers a lot of benefits, though indeed in some cases destroying  the entire app and creating it might be faster.

IMHO, the below two points do fall under the rehydration umbrella.
* don't try to sync up the footer
* don't render it

I am curios to know though how are you actually removing the static components from the final bundle browser application?

//cc @CaerusKaru

**Comment by sod** [comment]
It's not yet in production, so this directive contains debug code. But it looks like this:

I wrote this SsrRecycleDirective: https://gist.github.com/sod/97178a8650662300983f6ca08db178b7

The `SsrDocumentService` is used to search in the ssr dom. We already detach it from the DOM before angular kills it, so we can still access it.

It's used like:

```html
@Component({
template: `
<div *rySsrRecycle="'footer'">
    <ng-container *ngComponentOutlet="footer$ | async"></ng-container>
</div>`)
export class AppComponent {
    public footer$ = from(
        defer(() => import(/* webpackChunkName: "lazy-footer" */ './component/footer.component')
            .then(module => module.FooterComponent)),
    );
}
```

If rySsrRecycle decides to render, it'll load the `lazy-footer` chunk and bootstrap the component.

### ssr
If the ssr encounters that directive, it'll just render as-is and add the `id="ssr-recycle-footer"` to that element.

### browser
If the browser encounters that directive, it'll search the DOM for `#ssr-recycle-footer`, and if that exist, move it to that place.

--

You can extrapolate that scheme to all parts of the page. PushState navigation stil works through another directive, that captures click events, as they bubble upwards.
