### ISSUE TITLE
Cannot determine the module for class <class> in <path>! Add <class> to the NgModule to fix it

### ISSUE THREAD

**Issue by soyjuanmedina** [angular/angular#38070]
### Affected Package

 The issue is caused when try to complite with AOT option

### Is this a regression?

I don't know, I see here

https://github.com/angular/angular/issues/19544

yes is a regression, but in my case I don't have this problem until I reorganice some files

### Description

 A clear and concise description of the problem...

When I try to compile with `"aot": true`  in angular.json

It fails with the given error message

## 🔬 Minimal Reproduction

Sorry, I am trying to make a minimal application to reproduce it but I have not succeeded yet

## 🔥 Exception or Error
<pre><code>
ERROR in : Cannot determine the module for class BookappointmentsBase in D:/desarrollos/PatientPortal/front/src/app/pages/bookappointments/bookappointments.base.ts! Add BookappointmentsBase to the NgModule to fix it.
Cannot determine the module for class AppComponent in D:/desarrollos/PatientPortal/front/src/app/customizations/database/app.component-database.ts! 
Add AppComponent to the NgModule to fix it.
Cannot determine the module for class BookappointmentsComponent in D:/desarrollos/PatientPortal/front/src/app/customizations/database/bookappointments.page-database.ts! Add BookappointmentsComponent to the NgModule to fix it.
Cannot determine the module for class FooterComponent in D:/desarrollos/PatientPortal/front/src/app/customizations/database/footer.component-database.ts! Add FooterComponent to the NgModule to fix it.
Cannot determine the module for class NavbarComponent in D:/desarrollos/PatientPortal/front/src/app/customizations/database/navbar.component-database.ts! Add NavbarComponent to the NgModule to fix it.
Cannot determine the module for class BookappointmentsComponent in D:/desarrollos/PatientPortal/front/src/app/customizations/iaso/pages-con gaps no 
aprobados/bookappointments/bookappointments.page-iaso.ts! Add BookappointmentsComponent to the NgModule to fix it.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.1
Node: 12.18.0
OS: win32 x64
Angular: 8.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@angular/fire                     5.2.1
@angular/pwa                      0.8.9
@ngtools/webpack                  8.0.0
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.32.2

</code></pre>

**Anything else relevant?**

 Compile with `"aot": false` is successful but the result is much heavier.

I open some questions for specifics problems related with the sames problems

https://stackoverflow.com/questions/62590862/differences-between-angular-compilations

https://stackoverflow.com/questions/62636616/aot-compilation-and-filereplacement

**Comment by petebacondarwin** [comment]
What decorators are attached to the `BookappointmentsBase` class?

**Comment by soyjuanmedina** [comment]
> What decorators are attached to the `BookappointmentsBase` class?

I only have @Component and @ViewChild

**Comment by petebacondarwin** [comment]
OK. `BookappointmentsBase` sounds like some abstract class that is not really rendered but instead acts as a base class for "real" components to be derived from, yes?
If so then you should not add the `@Component({...})` decorator to this class. Instead just add the empty `@Directive()` decorator.

**Comment by soyjuanmedina** [comment]
It works!!!!! Thanks a lot.... I don't understand very well the @Directive but it's works!!!.... Now I will go to investigate to well undestanding!!!! Thanks a lot!!!
