### ISSUE TITLE
Duplicate text when using ICU expression in list without 'other'

### ISSUE THREAD

**Issue by sodaDreamer** [angular/angular#38073]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

Pretty sure this wasn't an issue in Angular 7. Noticed the issue after updating to Angular 9.

### Description

When using an ICU select expression inside a list, if you do not include the "other" placeholder, then subsequent changes to an item in the list causes the replacement text to display twice.

Issue #34018 suggests that the "other" case should actually be required but this is now no longer enforced. It might be worth reinstating the warning if this is deemed not to be a bug.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-cuoymq?file=src%2Fapp%2Fapp.component.html

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.10
Node: 12.18.2
OS: win32 x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.10
@angular-devkit/build-angular     0.901.10
@angular-devkit/build-optimizer   0.901.10
@angular-devkit/build-webpack     0.901.10
@angular-devkit/core              9.1.10
@angular-devkit/schematics        9.1.10
@angular/cli                      9.1.10
@ngtools/webpack                  9.1.10
@schematics/angular               9.1.10
@schematics/update                0.901.10
rxjs                              6.6.0
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by mhevery** [comment]
First let me say thank you for creating simple and easy to follow reproduction with text explaining what to click and what is about to happen. KUDOS!

Yes, this seems to be a bug. While ICU may require `other` I don't see a reason why that should affect the runtime algorithm.
