### ISSUE TITLE
add an option for xi18n tool to detect Inconsistency for ID content

### ISSUE THREAD

**Issue by jeandera** [angular/angular#38077]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
With angular i18n, If the same message ID is used in several different places in the source code , but contains different messages, the extracted.xlf contains only one occurence of the ID, one source message (the first one found in sources) and the different locations where the message have been found.

But sometimes during developement process, for different reasons (copy/paste, modification of the message in one source and not in others, etc ....) the same ID, does not contain the same message, and it generates bugs because the messsage will be replace by the only one translation.

In one angular application the same i18n ID used in different places MUST refer the same message. If not, it means there is a problem to be fixed.

example:
`<button mat-menu-itemi18n="@@MY_TEXT_LABEL"(click)="openAuthenticationConfigurationModal()">
  The first Text
</button>
`
 
and somewhere else in the code
`<app-readonly-field i18n-label="@@MY_TEXT_LABEL" label="Another Text">{{getLabelFor()}}</app-readonly-field>`

### Describe the solution you'd like
To avoid this problem, it would be nice to have an option for xi18n tool to detect if a message ID , used several times, refers the same message or not.

something like :
--checkIdContentConsistency
--checkIdSourceConsistency

The xi18n tool has all information to do this check easily

### Describe alternatives you've considered
I've thought to develop some scripts to do, but no easy to implement a angular code parser to extract all messages from code

**Comment by petebacondarwin** [comment]
Thanks for submitting this feature request. I think we could indeed support it, although there are some awkward corner cases.

That being said, the recommendation is actually not to provide your own message ids. Instead to let the extractor compute its own ids (based on the message text and any reason that is provided). This avoid the same message id being used in two different places where the message text does not match.

**Comment by jeandera** [comment]
Thanks a lot to have implemented this feature so quickly
