### ISSUE TITLE
View binding order is not as the order in the template!

### ISSUE THREAD

**Issue by majidmadadi** [angular/angular#38071]
Consider the following code:

```
import { Component, OnInit } from "@angular/core";
import { Observable, of, BehaviorSubject } from "rxjs";
import { tap } from "rxjs/operators";

@Component({
  selector: "app-root",
  template: `{{ users$ | async }}
    <div *ngIf="loading$ | async">
          SPINING...
    </div>`,
  styleUrls: [],
})
export class AppComponent implements OnInit {
  users$: Observable<any>;
  loadingSubject = new BehaviorSubject(false);
  loading$ = this.loadingSubject.asObservable();

  constructor() {}

  ngOnInit() {
    this.users$ = of({}).pipe(tap(() => this.loadingSubject.next(true)));
  }
}

```
When you run the code, you get the ExpressionChangedAfterItHasBeenCheckedError in the console. The reason is that the "*ngIf" binding is evaluated first while it's after the "users$" async pipe in the template. 

I expect binding should occur in the same order as in the template.

**Angular Version:**
<pre><code>
Angular CLI: 8.3.28
Node: 12.17.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.28
@angular-devkit/build-angular     0.803.28
@angular-devkit/build-optimizer   0.803.28
@angular-devkit/build-webpack     0.803.28
@angular-devkit/core              8.3.28
@angular-devkit/schematics        8.3.28
@angular/cli                      8.3.28
@ngtools/webpack                  8.3.28
@schematics/angular               8.3.28
@schematics/update                0.803.28
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Comment by DenysVuika** [comment]
This thing is driving me crazy. I've already spent 2 days investigating this problem. We got hundreds of similar errors all over the product after upgrading to Angular 10.

**Comment by pkozlowski-opensource** [comment]
I can't reproduce using the latest Angular v10 running ivy. Here is the stackblitz where I was trying to reproduce using the provided code: https://stackblitz.com/edit/angular-zsi27d?file=src%2Fapp%2Fapp.module.ts

@majidmadadi @DenysVuika could one of you please provide a minimal reproduce scenario in a stackblitz? Given the provided info I can't determine if this issue is specific to ViewEngine or ivy and when it was fixed (if it was).

**Comment by majidmadadi** [comment]
Fortunately, it's solved in v10.
