### ISSUE TITLE
ERROR in ./node_modules/@ng-dynamic-forms/core/__ivy_ngcc__/fesm2015/core.js 1898:86-101 "export 'ɵlooseIdentical' was not found in '@angular/core'

### ISSUE THREAD

**Issue by phgachoud** [angular/angular#38091]
# 🐞 bug report

### Affected Package
@ng-dynamic-forms

### Is this a regression?

Never seen in previous versions

### Description
Compile issue with 

ERROR in ./node_modules/@ng-dynamic-forms/core/__ivy_ngcc__/fesm2015/core.js 1898:86-101
"export 'ɵlooseIdentical' was not found in '@angular/core'

## 🔬 Minimal Reproduction
Wont be able to tell what is minimum sorry but here is the packages.json

`{
  "name": "sit-angular-srv",
  "version": "0.0.1",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --poll=2000 --configuration=dev --host 0.0.0.0 --disable-host-check",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "4": "0.0.0",
    "@angular/animations": "^10.0.4",
    "@angular/cdk": "^10.0.2",
    "@angular/common": "^10.0.4",
    "@angular/compiler": "^10.0.4",
    "@angular/core": "^10.0.4",
    "@angular/forms": "^10.0.4",
    "@angular/http": "^7.2.16",
    "@angular/material": "^10.0.2",
    "@angular/platform-browser": "^10.0.4",
    "@angular/platform-browser-dynamic": "^10.0.4",
    "@angular/router": "^10.0.4",
    "@ng-dynamic-forms/core": "^11.0.3",
    "@ng-dynamic-forms/ui-material": "^11.0.3",
    "angular2-text-mask": "^9.0.0",
    "bootstrap": "^4.5.0",
    "chart.js": "^2.9.3",
    "chartjs-plugin-annotation": "^0.5.7",
    "chartjs-plugin-zoom": "^0.7.7",
    "dev": "^0.1.3",
    "hammerjs": "^2.0.8",
    "jquery": "^3.5.1",
    "jspdf": "^1.5.3",
    "jspdf-autotable": "^3.5.6",
    "material-design-icons": "^3.0.1",
    "moment": "^2.27.0",
    "ngx-webstorage-service": "^4.1.0",
    "popper.js": "^1.16.1",
    "rxjs": "^6.6.0",
    "sunnyportal-api": "0.0.1",
    "tslib": "^2.0.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.3",
    "@angular/cli": "^10.0.3",
    "@angular/compiler-cli": "^10.0.4",
    "@angular/language-service": "^10.0.4",
    "@angular/material-moment-adapter": "^10.0.2",
    "@types/chart.js": "^2.9.23",
    "@types/hammerjs": "^2.0.36",
    "@types/jasmine": "^3.5.11",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "^14.0.23",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.10.2",
    "tslint": "~6.1.0",
    "typescript": "~3.9.6",
    "zone.js": "~0.10.3"
  }
}
`

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>Angular CLI: 10.0.3
Node: 10.16.0
OS: linux x64

Angular: 10.0.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.3
@angular-devkit/build-angular      0.1000.3
@angular-devkit/build-optimizer    0.1000.3
@angular-devkit/build-webpack      0.1000.3
@angular-devkit/core               10.0.3
@angular-devkit/schematics         10.0.3
@angular/cdk                       10.0.2
@angular/cli                       10.0.3
@angular/http                      7.2.16
@angular/material                  10.0.2
@angular/material-moment-adapter   10.0.2
@ngtools/webpack                   10.0.3
@schematics/angular                10.0.3
@schematics/update                 0.1000.3
rxjs                               6.6.0
typescript                         3.9.6
webpack                            4.43.0
<code>
Linux debian 10.0

**Comment by AndrewKushnir** [comment]
Hi @phgachoud, thanks for reporting the issue. The problem was caused by the code in the `ng-dynamic-forms` package, see https://github.com/udos86/ng-dynamic-forms/issues/1085 for additional information. Please subscribe to that thread to receive further updates. Thank you.
