### ISSUE TITLE
Lazy load ngModule to render the components dynamically

### ISSUE THREAD

**Issue by fksik** [angular/angular#38108]
🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅

Hi,
    I found feature requests to lazy load components directly, But it seems not standardised.

🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅

🚀 feature request

Relevant Package
      @angular/common
      @angular/router[refereed from]

Description
               To lazy load a component like we load and render routing components, I think we can provide a service to lazy load module of components or component. And we can get components out of the module using an value provider as provided in gist.

Solution
              [Gist](https://gist.github.com/fksik/31262f39c921f5731949093ca1b67337#file-lazy-load-module-service-ts)

**Comment by sod** [comment]
You may be interested in reading https://medium.com/angular-in-depth/lazy-load-components-in-angular-596357ab05d8 - it describes a way to lazyload a component. The trick is to have the component in it's own NgModule thats not exported:

![image](https://user-images.githubusercontent.com/905328/87784777-38356000-c837-11ea-82dc-20701dcabf15.png)

Then you can just have your lazy import statement:
`loader = defer(() => import("./my-lazy-compoent").then(module => module.MyComponent))`  
and render it dynamically via `ngTemplateOutlet` like:
`<ng-container *ngTemplateOutlet="loader | async">`

**Comment by fksik** [comment]
Yeah we can do that but language service intelisense will not work and also as angular does loading with ngModules(routing), Why can't we use the same approach for loading and rendering dynamic components in the same way. Why just restrict it with only `router-outlet`

**Comment by mlc-mlapis** [comment]
[**@fksik**](https://github.com/fksik) What do you by that?

> Why just restrict it with only `router-outlet`

**Comment by fksik** [comment]
The solution that i gave in the gist is modified code from @angular/router.

**Comment by mlc-mlapis** [comment]
@fksik Then the principle is general, it's possible to use it without router also - just only the programmatical way to load a module/component in any moment and place.

**Comment by fksik** [comment]
This could be a solution for these kind of issues #33654, #35759, #34780

**Comment by Hx2heng** [comment]
> This could be a solution for these kind of issues #33654, #35759, #34780 by loading modules not components directly.
> component to render dynamically can be queried from module using a value provider get.

It can work：
```
import('src/app/components/smart-robot/smart-robot.module').then(mod => {
            const mwcf = this.compiler.compileModuleAndAllComponentsSync(mod.SmartRobotModule);
            const rootComponet = mwcf.componentFactories[0];
            this.viewContainer.createComponent(rootComponet);
          });
```
BUT doesn't work with AOT build!
Anyone can help me?

**Comment by mlc-mlapis** [comment]
@Hx2heng It's not possible to invoke `this.compiler.compileModuleAndAllComponentsSync` because the compiler is not loaded by default in AOT run-time application. But it's also not necessary because the module is already compiled and as a lazy-loaded module, a separate bundle file is created for it.

The following code is only necessary to allow Angular CLI to understand what to do:
```
const lazyLoadedModules = {
   anyname: {
      loadChildren: async () => (await import('.../modules/any')).AnyModule
   }
};
```
Then you call the following code to load programmatically that lazy-loaded module and create a module instance (works both for JIT and AOT mode):
```
lazyLoadedModules.anyname.loadChildren().then(moduleOrFactory => {
   if (moduleOrFactory instanceof NgModuleFactory) {
      return moduleOrFactory;
   } else {
      return this._compiler.compileModuleAsync(moduleOrFactory);
   }
}).then((factory: NgModuleFactory<any>) => {
   const anyModuleRef = factory.create(this._injector);
   ...
});
```

**Comment by Hx2heng** [comment]
@mlc-mlapis Thanks! 
one more question：how to get the components declarationed in this dynamic module?

**Comment by mlc-mlapis** [comment]
@Hx2heng There are more ways. One of them is to create a map directory structure on a lazy-loaded module level that allows getting a component type definition based on just a string.

**Comment by jzabinski-dolios** [comment]
Putting together some different suggestions from this thread, and updating for some (almost undocumented) changes in Angular 13, the following works well for us:

1. The lazy loaded module can stay almost the same as any other module, with the following minor addition:
```
export class LazyLoadedModule {
  get exported(): Type<InterestingComponent> {
    return InterestingComponent;
  }
}
```

This keeps the type of component installed by the lazy loaded module known only to the lazy loaded module. This should keep the lazy loaded code separate from the rest of the app.

2. When it is time to load:
```
import {
    Injector, ViewContainerRef, NgModuleRef, ElementRef,
    createNgModuleRef
} from '@angular/core';
import { Observable, from } from 'rxjs';
import { LazyLoadedModule } from './module';
import { map } from 'rxjs/operators';

export function installModule(injector: Injector, vcRef: ViewContainerRef): Observable<ElementRef> {
    // 1. Load the module
    return from(import('./module'))
        .pipe(
            map(m => m.LazyLoadedModule),
            // 2. Create module reference.
            map(mod => createNgModuleRef<LazyLoadedModule>(mod, injector)), // any module level injections added via the 'injector'
            // 3. Create component.
            map((moduleRef: NgModuleRef<LazyLoadedModule>) => vcRef.createComponent(moduleRef.instance.exported, { injector })), // any component level injections (for things like services) added via the 'injector'
            // 4. Return ElementRef
            map(cmpntRef => cmpntRef.location)
        );
}

```

3. When you want to install the component loaded via the lazy loaded module:

- in component `html`:
```
<ng-template #loadedcmpnt></ng-template>
```
- in component `ts`:
```
@ViewChild('loadedcmpnt', { read: ViewContainerRef }) loadedCmpntVcRef: ViewContainerRef;
...
installModule(this.injector, this.navCmpntVcRef)
```

**Comment by pkozlowski-opensource** [comment]
Components lazy loading will be supported (and feel "natural", both with router and without router) when [standalone components](https://github.com/angular/angular/discussions/43784) are implemented (currently in progress). 

Going to close this issue as not planning to implement suggestions from this issue but go with what is described in the linked RFC instead.
