### ISSUE TITLE
redundant reference to npm

### ISSUE THREAD

**Issue by Azcrew** [angular/angular#38106]
# 📚 Docs or angular.io bug report

### Description

On page [Using published libraries](https://github.com/angular/angular/blob/deac9945176f2668752b479450ce4859d7977d72/aio/content/guide/using-libraries.md) line 11 is quoted

> The ng add command uses the npm package manager or yarn (...)

Considering that npm is literally node package manager, this sentence sounds redundant

**Comment by saifabusaleh** [comment]
Hi,

Can I take this issue?

**Comment by petebacondarwin** [comment]
Sure!

**Comment by petebacondarwin** [comment]
Please note the commit message requirements and signing the CLA: https://github.com/angular/angular/blob/master/CONTRIBUTING.md
