### ISSUE TITLE
Compilation: Out of Memory Exception due to combineLatest + 7+ Observables + Object Merge

### ISSUE THREAD

**Issue by BaggersIO** [angular/angular#38116]
# 🐞 bug report

### Affected Package

Maybe @angular/compiler or @angular/compiler-cli

### Is this a regression?

Unclear

### Description

Using RxJS combineLatest with `7 or more` Observables in an array and `merging` all values into one single object using the `spread operator` results in high memory cosumption - sometimes I get a node.js out of memory exception. The memory rises at compilation time (ng build, ng serve, ng test).

We created a repository with sample code, workarounds and performance insights: https://github.com/qupaya/ng-example-obj-spread-bug

The code which causes high memory consumption at compilation time (https://github.com/qupaya/ng-example-obj-spread-bug/blob/main/src/app/app.component.ts#L70):

```ts
    this.sevenPropsBrokenResult$ = combineLatest(
      [a$, b$, c$, d$, e$, f$, g$]
    ).pipe(map(
      ([a, b, c, d, e, f, g]) => ({
        ...a,
        ...b,
        ...c,
        ...d,
        ...e,
        ...f,
        ...g
      }),
    ));
```

Memory & time consumption at compilation `/usr/bin/time -l ng build`

```ts
       46.85 real        37.37 user         5.53 sys
1936789504  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
    980706  page reclaims
      4458  page faults
         0  swaps
         0  block input operations
         0  block output operations
         0  messages sent
         0  messages received
         2  signals received
      8570  voluntary context switches
    174244  involuntary context switches
```

## 🔬 Minimal Reproduction

Repo: https://github.com/qupaya/ng-example-obj-spread-bug

Just clone the repo, run npm install and call `ng build` (or `/usr/bin/time -l ng build` if you want to monitor time and memory).

## 🔥 Exception or Error
<pre><code>
$ ng build                                                                                                                                                                                          ‹ruby-2.5.1›
10% building 5/5 modules 0 active
<--- Last few GCs --->

[24031:0x104619000]    95253 ms: Mark-sweep 2035.4 (2057.8) -> 2033.4 (2067.5) MB, 3288.8 / 0.0 ms  (average mu = 0.372, current mu = 0.010) allocation failure scavenge might not succeed
[24031:0x104619000]    99553 ms: Mark-sweep (reduce) 2041.6 (2067.5) -> 2037.5 (2056.5) MB, 4150.1 / 0.0 ms  (+ 0.1 ms in 127 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 4300 ms) (average mu = 0.209, current mu = 0.0

<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 0x1012762c5 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000a2899 node::Abort() [/usr/local/bin/node]
 3: 0x1000a29ff node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x1001e45b7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1001e4553 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 6: 0x10037dda5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 7: 0x1003d3bb0 v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [/usr/local/bin/node]
 8: 0x1003bc19b void v8::internal::LiveObjectVisitor::VisitBlackObjectsNoFail<v8::internal::EvacuateNewSpaceVisitor, v8::internal::MajorNonAtomicMarkingState>(v8::internal::MemoryChunk*, v8::internal::MajorNonAtomicMarkingState*, v8::internal::EvacuateNewSpaceVisitor*, v8::internal::LiveObjectVisitor::IterationMode) [/usr/local/bin/node]
 9: 0x1003bbce5 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [/usr/local/bin/node]
10: 0x1003bba26 v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [/usr/local/bin/node]
11: 0x1003d85ee v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [/usr/local/bin/node]
12: 0x100397962 v8::internal::ItemParallelJob::Task::RunInternal() [/usr/local/bin/node]
13: 0x100397de8 v8::internal::ItemParallelJob::Run() [/usr/local/bin/node]
14: 0x1003bda75 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [/usr/local/bin/node]
15: 0x1003bd676 v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [/usr/local/bin/node]
16: 0x1003a9ab7 v8::internal::MarkCompactCollector::Evacuate() [/usr/local/bin/node]
17: 0x1003a732b v8::internal::MarkCompactCollector::CollectGarbage() [/usr/local/bin/node]
18: 0x10037e0ef v8::internal::Heap::MarkCompact() [/usr/local/bin/node]
19: 0x10037ae9b v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
20: 0x100378f88 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
21: 0x1003863da v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
22: 0x100386461 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
23: 0x100355c17 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
24: 0x1006cd948 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
25: 0x100a24519 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
26: 0x1009fe375 Builtins_MapConstructor [/usr/local/bin/node]
27: 0x1009b8f41 Builtins_JSBuiltinsConstructStub [/usr/local/bin/node]
28: 0x2bec9a771a3d 
29: 0x2bec9a759379 
30: 0x2bec9a7613c8 
31: 0x2bec9a761f80 
[1]    24031 abort      ng build></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.3
Node: 14.5.0
OS: darwin x64

Angular: 10.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.3
@angular-devkit/build-angular     0.1000.3
@angular-devkit/build-optimizer   0.1000.3
@angular-devkit/build-webpack     0.1000.3
@angular-devkit/core              10.0.3
@angular-devkit/schematics        10.0.3
@angular/cli                      10.0.3
@ngtools/webpack                  10.0.3
@schematics/angular               10.0.3
@schematics/update                0.1000.3
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Anything else relevant?**

no

**Comment by JoostK** [comment]
I am sorry to tell you that I can't reproduce the OOM crash, but it seems like TypeScript is just choking on this:

```
./node_modules/.bin/tsc -p tsconfig.app.json --diagnostics
src/app/app.component.ts:70:5 - error TS2322: Type 'Observable<{ a: string; } | { b: string; a: string; } | { c: string; a: string; } | { d: string; a: string; } | { e: string; a: string; } | { f: string; a: string; } | { g: string; a: string; } | { a: string; b: string; } | { b: string; a: string; } | ... 823533 more ... | { ...; }>' is not assignable to type 'Observable<SevenPropsResult>'.
  Type '{ a: string; } | { b: string; a: string; } | { c: string; a: string; } | { d: string; a: string; } | { e: string; a: string; } | { f: string; a: string; } | { g: string; a: string; } | { a: string; b: string; } | { b: string; a: string; } | ... 823533 more ... | { ...; }' is not assignable to type 'SevenPropsResult'.
    Type '{ a: string; }' is missing the following properties from type 'SevenPropsResult': b, c, d, e, and 2 more.

70     this.sevenPropsBrokenResult$ = combineLatest(
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.

Files:               299
Lines:             60200
Nodes:            225253
Identifiers:       83073
Symbols:           62040
Types:           3043402
Instantiations:    24066
Memory used:    1774048K
I/O read:          0.02s
I/O write:         0.00s
Parse time:        0.96s
Bind time:         0.31s
Check time:       13.94s
Emit time:         0.04s
Total time:       15.25s
```

Notice the `... 823533 more ...` in the message, indicating the huge number of constituents in the expanded union type.

As this is reproducible just with TypeScript (there's no Angular involved in the output above) I'm afraid we can't help you here. I'm not sure if your best bet is to report this with either TypeScript or RxJS, as I'm not surprised that a type union of ~823533 constituents is taking some amount of memory. So you might want to address it with the RxJS to indicate that their typings cause these huge expanded type unions, or address it with TS to indicate that their computation is getting quite large (for which I cannot determine if that is deemed reasonable).

**Comment by JoostK** [comment]
FYI, I'm seeing the same behavior using:

`rxjs@7.0.0-beta.2` and `typescript@4.0.0-dev.20200715`

**Comment by BaggersIO** [comment]
Thank you @JoostK for your investigation on this! I'll get in touch with the RxJS Team :)
