### ISSUE TITLE
Angular Debugger Does not Work when aot is false in Visual Studio Code

### ISSUE THREAD

**Issue by dancoltonart** [angular/angular#38122]
I am currently trying to debug in Visual Studio Code.

We set Ahead of Time Compiler (AOT) to false, and now Visual Studio Code (Menu -->Debugger Run--->Start Debugging), does not start Debugger correctly. It just freezes it. How can this be solved?

`"aot": false`

Background: Set AOT to false, due to new Angular 10 making builds slow (setting AOT to false actually made application compile speed up according to github)

Github link: **https://github.com/angular/angular/issues/37293**

Also sometimes get error with it ,

`epipe.js: TypeError: Cannot read property 'requestContent' of undefined`

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---
I am sorry but this is more of a support question, for which Github is not the right place to ask.
