### ISSUE TITLE
Angular 9.x - Change detection not working in prod build (but works in dev)

### ISSUE THREAD

**Issue by petef19** [angular/angular#38128]
# 🐞 bug report

### Description

I'm running into some strange behavior on Angular 9.1.11. I have a simple app that only uses the app.component.ts. A public class var (boolean) controls whether a button in the template is disabled or not.

Change Detection (using `changeDetection: ChangeDetectionStrategy.Default`) is working absolutely fine in the dev build, but it **does NOT work in the prod build** of the app.

I have to import and inject `ChangeDetectorRef` into the `AppComponent` class and manually trigger the `.detectChanges() ` method to make it work in the prod build (all of this works automatically in the dev build).

Any suggestions what may be causing the behavior in the prod build ?

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.10
Node: 12.18.0
OS: win32 x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.10
@angular-devkit/build-angular     0.901.10
@angular-devkit/build-optimizer   0.901.10
@angular-devkit/build-webpack     0.901.10
@angular-devkit/core              9.1.10
@angular-devkit/schematics        9.1.10
@angular/cli                      9.1.10
@ngtools/webpack                  9.1.10
@schematics/angular               9.1.10
@schematics/update                0.901.10
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Comment by ajitsinghkaler** [comment]
Can you please create a minimalistic reproduction for it.

**Comment by petef19** [comment]
Hi,

just found out what the problem is. We're updating the var in async/await blocks, and it seems that even with latest Ng 9.x this is still not doable unless targeting ES2015.

Odd enough, this does work in the dev build in the small app we have, but it does not work in the production build, but now we know at least why.  ;-)

We'll have to trigger CD manually until this is implemented.

Thanks.
