### ISSUE TITLE
docs: coding style guide - no information about getters and setters

### ISSUE THREAD

**Issue by saifabusaleh** [angular/angular#38134]
### Description
In [Angular Coding style guide](https://angular.io/guide/styleguide) There is missing information about usage of getter and setters in Angular:

- Are they anti-pattern?
- Is it best/bad practice to bind the getter directly to the template, and how it can affect performance
- Getter/Setter side effects
- Where to place them in the component(before or after members, etc.. ?)
- Naming convention

**Comment by aikidave** [comment]
Hey there! Thanks for raising this issue. We have a performance guide on our content roadmap, in which we can address the Angular-related portions of your issue. Closing this issue as we're tracking this work in our content outline. Thanks!
