### ISSUE TITLE
test(router): test parity between 1.x and 2.x directives

### ISSUE THREAD

**Issue by btford** [angular/angular#3813]
Right now, we have totally different tests for 1.x and 2.x for the router. We should have roughly the same high level tests for use cases.

This should be enforced via script. So for some set of specs (probably the integration specs), we should assert as part of the angular1_router target that we have the same spec descriptions.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
