### ISSUE TITLE
unable to Add some texts and links together

### ISSUE THREAD

**Issue by santokt** [angular/angular#38135]
Can someone help me to show some links along with text?

Here is the stackbliz link
https://stackblitz.com/edit/angular-ivy-kxg9cj?file=src%2Fapp%2Finnerhtmltest%2Finnerhtmltest.component.html

Here is the stackoverflow link
https://stackoverflow.com/questions/62903315/angular-typescript-text-with-routerlink

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
