### ISSUE TITLE
`<div [class.x]=></div>` crashes the forked type checker

### ISSUE THREAD

**Issue by sod** [angular/angular#38155]
# 🐞 bug report

## 🌍  Your Environment

Angular CLI: 10.0.3
Angular: 10.0.4

## 🔬 Minimal Reproduction

```sh
npm i -g @angular/cli
ng new ng10-crash
cd ng10-crash
ng serve
```

Then replace the app.component.html with `<div [class.x]=></div>` and see this in the terminal:

![image](https://user-images.githubusercontent.com/905328/88021695-454f9900-cb2e-11ea-9685-c9d51c318316.png)

If you don't want the typechecker now slowing down the watcher in the main thread, you have to restart it.

## Expected behavior

typechecker remaining forked, even when there was an error

**Comment by JoostK** [comment]
Closing as #38576 was just merged, should be available in 10.1.1 somewhere next week.
