### ISSUE TITLE
AOT Metadata Errors page contains wrong import for DOCUMENT

### ISSUE THREAD

**Issue by IxquitilisSaid** [angular/angular#38158]
# 📚 Docs or angular.io bug report

### Description

The documentation reads as follows: 
`import { DOCUMENT } from '@angular/platform-browser';` 
instead of `import { DOCUMENT } from '@angular/common';`

### What's the affected URL?**

https://angular.io/guide/aot-metadata-errors#could-not-resolve-type

### Expected vs Actual Behavior**

Same as written in the Description section

**Comment by JoostK** [comment]
This was addressed in #38159
