### ISSUE TITLE
Documentation translated into Portuguese (PT-br/Pt-pt)

### ISSUE THREAD

**Issue by ronaldohoch** [angular/angular#38162]
Hello!
Is there a project to translate the documentation?

If yes -> How can the Brazilian community contribute to the Portuguese translation?
If not -> How can I start translating the documentation and move the Portuguese speaking community?

**Comment by sidneifjr** [comment]
I'm also available to help translating the docs, if the team is interested.

**Comment by ronaldohoch** [comment]
@sidneifjr Não tenho time ainda, iria formar um grupo de ajudantes postando na comunidade do facebook, tu está nesse grupo? Angular 2~10 Brasil?

**Comment by sidneifjr** [comment]
@ronaldohoch Acabei de mandar uma solicitação para entrar no grupo. Eu diria que é uma boa idéia, mas algo a ter em mente é o cuidado de não entrar muita gente, pois isso pode diluir a qualidade da tradução por haver muitas mãos tocando na mesma.

Na minha opinião, seria bom entrar mais um ou dois no máximo, levando em conta a extensão da documentação (e o fato de que precisaríamos rever todos os textos para garantir que tudo foi feito corretamente). Aí, criava uma equipe e combinava a parte de cada um igualmente. Mas claro, são só idéias por enquanto.

**Comment by ferfox1981** [comment]
Did the Portuguese translation begin? I want to help too.

A tradução para o Português já começou? Gostaria de ajudar também.

**Comment by ronaldohoch** [comment]
Bah, então...

Acabou que fiquei ocupado e não pude iniciar, acabei de postar no grupo de Angular no facebook, vamos combinar por lá.

https://www.facebook.com/groups/133245103752262/permalink/1054147604995336/

**Comment by ferfox1981** [comment]
> Bah, então...
> 
> Acabou que fiquei ocupado e não pude iniciar, acabei de postar no grupo de Angular no facebook, vamos combinar por lá.
> 
> https://www.facebook.com/groups/133245103752262/permalink/1054147604995336/

Entrei lá, mas por mim podemos falar por aqui mesmo se quiser.

**Comment by andrebaltieri** [comment]
> @petebacondarwin and @AndrewKushnir
> Is there a way to start the translate, like a guide from Angular Core Team for community or the translate we want to do is only up to us?
> 
> have seen that you marked with label "type:confusing", let's talk about.

I don't think they have localization for docs, here seems to be the official docs:
https://github.com/angular/angular/tree/master/aio

**Comment by petebacondarwin** [comment]
"type: confusing" means that the issue is reporting that there is some aspect of Angular that is confusing to developers; not that the issue itself is confusing.

Indeed the core team are not involved directly in any of the efforts to translate the Angular docs to other languages.

Perhaps @mgechev has information about whether we provide any support to such efforts?

**Comment by ferfox1981** [comment]
> @petebacondarwin and @AndrewKushnir
> Is there a way to start the translate, like a guide from Angular Core Team for community or the translate we want to do is only up to us?
> 
> have seen that you marked with label "type:confusing", let's talk about.

Look this issue: https://github.com/angular/angular/issues/38503
It is trying to start translation to viatnamese. It contains some links to the japanese initiative: https://github.com/angular/angular-ja
And Spanish initiative: https://github.com/angular-hispano/angular
The japanese seens to be inside Angular's Github, whereas the spanish it not.

**Comment by mgechev** [comment]
Could you reach out to me via email (mgechev at google.com) and we can discuss next steps?

**Comment by ronaldohoch** [comment]
@ferfox1981 me add no facebook lá https://www.facebook.com/groups/133245103752262/permalink/1054147604995336/ ou no telegram/whats 51982291344.

@mgechev i'll send an email asap.

**Comment by Maransatto** [comment]
One more Brazilian here to help.

**Comment by mgechev** [comment]
Closing since we're already in touch on Slack. @Maransatto feel free to email me on mgechev at google dot com.
