### ISSUE TITLE
Angular 9.1 broken karma tests on jenkins

### ISSUE THREAD

**Issue by Kchaan** [angular/angular#38160]
# 🐞 bug report

### Affected Package
Angular 9.1

### Is this a regression?

Everything works in angular 9.0

### Description

After upgrade to angular 9.1, karma tests on jenkins fail with following error: 
DEBUG [Chrome Headless 83.0.4103.116 (Linux x86_64)]: CONFIGURING -> EXECUTING
Chrome Headless 83.0.4103.116 (Linux x86_64): Executed 0 of 0 SUCCESS (0 secs / 0 secs)
[1A[2KChrome Headless 83.0.4103.116 (Linux x86_64) ERROR
  An error was thrown in afterAll
  Script error. 
It does not matter if I am using typescript 3.7 or 3.8 or different karma versions (4/5)

## 🔬 Minimal Reproduction
since this is jenkins problem, it is hard to create reproduction for this

## 🔥 Exception or Error
<pre><code>
DEBUG [Chrome Headless 83.0.4103.116 (Linux x86_64)]: CONFIGURING -> EXECUTING
Chrome Headless 83.0.4103.116 (Linux x86_64): Executed 0 of 0 SUCCESS (0 secs / 0 secs)
[1A[2KChrome Headless 83.0.4103.116 (Linux x86_64) ERROR
  An error was thrown in afterAll
  Script error.

</code></pre>

## 🌍  Your Environment

**Angular Version: 9.1**
more information is in stackoverflow question 

https://stackoverflow.com/questions/62959672/angular-9-1-upgrade-broken-unit-tests-on-jenkins

**Comment by JiaLiPassion** [comment]
@Kchaan , could you provide a reproduce repo? thanks!

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
