### ISSUE TITLE
Angular 8 - @angular/core has no exported member ɵɵFactoryDef, etc.

### ISSUE THREAD

**Issue by pmandayam** [angular/angular#38175]
# 🐞 bug report

### Affected Package

@angular/core

### Is this a regression?

No.

### Description

I have created a custom Angular library using Angular 8. The issue occurs in @angular/core/core in that library.

When an Angular 9 project imports this library through `npm install`, and when I run `ng build` to build the Angular 9 project, I get errors similar to the following:

`@angular/core/core has no exported member ɵɵFactoryDef`

`@angular/core/src/r3_symbols has no exported member eeFactoryDef`

`@angular/core/src/r3_symbols has no exported member eeInjectableDef`

etc.

## 🔥 Exception or Error

See above in description.

## 🌍  Your Environment

The Angular library that has the `@angular/core` errors is version 8.
The Angular project that uses the library is version 9.

A ticket for this issue has already been submitted [here](https://github.com/angular/angular/issues/35291).

But there some issues with that. For one, [this comment](https://github.com/angular/angular/issues/35291#issuecomment-585102857) says to run using `ng build --prod`, but the [Angular documentation](https://angular.io/cli/build) says that `ng build` automatically runs in production.

Then, [this comment](https://github.com/angular/angular/issues/35291#issuecomment-586338571) says to delete `node_modules` folder and run `npm i`. I tried that and it didn't work.

**Comment by JoostK** [comment]
I suspect that the library has a direct dependency on Angular 8, instead of a peer dependency. This will cause two installs of `@angular/core` to be present and this causes strange build issues.

**Comment by pmandayam** [comment]
> I suspect that the library has a direct dependency on Angular 8, instead of a peer dependency. This will cause two installs of `@angular/core` to be present and this causes strange build issues.

Thanks, I see your other comment to run `npm ls @angular/core`. So I will try that and see what I get.

**Comment by pmandayam** [comment]
I was able to solve the problem by adding to `tsconfig.json`:

```
"compilerOptions": {
        ...
        "paths": { "@angular/*": ["./node_modules/@angular/*"] }
}
```

just as [this comment](https://github.com/angular/angular/issues/35291#issuecomment-598118244) says.
