### ISSUE TITLE
formState as object might not need value property

### ISSUE THREAD

**Issue by doggy8088** [angular/angular#38178]
# 🐞 bug report

### Affected Package

The issue is caused by package `@angular/forms`

### Is this a regression?

No

### Description

Due to [this comment](https://stackoverflow.com/questions/49200258/passing-disabled-in-form-state-object-to-formcontrol-constructor-doesnt-work#comment85487742_49201639), I think `formState`'s `value` property might not required.

The internal [_isBoxedValue](https://github.com/angular/angular/blob/10.0.4/packages/forms/src/model.ts#L898-L901) method in the `@angular/forms` was defined the `value` property must be defined (The `'value' in formState` part). This condition might not needed.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-z9i4rb?file=src%2Fapp%2Fapp.component.ts

When omit the `value` property in the `formState` parameter, the result should binding correctly.

![image](https://user-images.githubusercontent.com/88981/88195478-ae402980-cc72-11ea-9750-6fa99170b845.png)

## 🔥 Exception or Error

N/A

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 10.0.3
Node: 12.18.2
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1000.3
@angular-devkit/core         10.0.3
@angular-devkit/schematics   10.0.3
@schematics/angular          10.0.3
@schematics/update           0.1000.3
rxjs                         6.5.5
</code></pre>

**Anything else relevant?**

N/A

**Comment by AndrewKushnir** [comment]
Hi @doggy8088,

This logic was added a while ago in https://github.com/angular/angular/pull/10994 and an answer to a similar question can be found in https://github.com/angular/angular/pull/10994#issuecomment-244195999. You can also find usage examples in the [FormControl docs](https://angular.io/api/forms/FormControl#usage-notes).

I think that the `value` check in the `_isBoxedValue` function can not be removed at this time for the reasons mentioned in https://github.com/angular/angular/pull/10994#issuecomment-244195999, so I'm closing this ticket for now.

Thank you.
