### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ɵprov' of undefined

### ISSUE THREAD

**Issue by Tehalka** [angular/angular#38189]
# 🐞 bug report

### Description

Uncaught TypeError: Cannot read property 'ɵprov' of undefined, when build ionic application in production mode

## 🔥 Exception or Error
<pre><code>

Uncaught TypeError: Cannot read property 'ɵprov' of undefined

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.6
Node: 12.18.1
</code></pre>

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
