### ISSUE TITLE
Usage of Angular Logo

### ISSUE THREAD

**Issue by loganwyas** [angular/angular#38188]
I am not sure if this is the right place to ask this, but would I be able to use the Angular logo for commercial purposes (like in a board game)? I'm seeing posts about using it for company t-shirts, so I am unsure if this applies similarly. If I can use it, are there any specific citations or references I need to use? Thanks in advance.

**Comment by hiepxanh** [comment]
yeah, I have the same question too, any guideline of how to use it? do we need to paid anything?

**Comment by petebacondarwin** [comment]
Here is some background information, which you might have found already: https://angular.io/presskit. On this page it is stated that the logos are licensed under [Creative Commons](https://creativecommons.org/licenses/by/4.0/legalcode).

But we should get @StephenFluin or @mgechev to provide more clarification in situations where you are going to use the logo for commercial use where it might look like your product represents the Angular team.

**Comment by StephenFluin** [comment]
Yes you can use our logo for commercial purposes. You could, for example, print Angular shirts and sell them.

Usage of our logo is available under: https://creativecommons.org/licenses/by/4.0/, this site clarifies attribution requirements.

If you are using our logo to pose as the Angular team or confuse customers, that would be a violation of our trademark, but I assume you aren't trying to do that. :) We'd also love to see what you are building! If you are making a board game, we have a lot of folks in the community who love board games.
