### ISSUE TITLE
Add "remove hammerjs"-step to Angular Update Guide

### ISSUE THREAD

**Issue by Roseidon** [angular/angular#38190]
# 📚 Docs or angular.io ~bug report~ feature request

### Description

Recently I upgraded from Angular6 to Angular9 using the [Angular Update Guide](https://update.angular.io/). After a while we went through our dependencies and found out that we could have removed `hammerjs` as dependency. It would have been nice to have this step as reminder that `hammerjs` is not needed as dependency anymore.

### What's the affected URL?
[Angular Update Guide](https://update.angular.io)

**Comment by devversion** [comment]
Hey, thanks for this issue! Could provide a little bit more context on why HammerJS was added to your project in the first place? Did you use Angular Material? Angular Material required HammerJS until v9, and we provided a migration for consumers running `ng update @angular/material` to clean up HammerJS for v9 and v10.

**Comment by Roseidon** [comment]
Oops sorry for the missing context!

We added HammerJS in older versions because of Angular Material. But I did not notice that the ng update step for @angular/material cleaned up HammerJS. (I had some issues using `ng update @angular/material` at earlier versions, that's why I updated manually).

Well then this topic can be closed!
