### ISSUE TITLE
Missing pipe not caught by production build with AOT

### ISSUE THREAD

**Issue by lukebellamy053** [angular/angular#38195]
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I have a module with a view that includes a pipe from a library. 
The library was not imported into this module and thus the pipe is not included in the module.
IntelliJ correctly flags the missing pipe but the Angular build process (even when AOT is enabled) does not find this problem

The same issue occurs when referencing a pipe that doesn't even exist at all, the builder never shows any warnings or errors

![image](https://user-images.githubusercontent.com/7202374/88241836-3cbca700-cc83-11ea-81f9-6cacfa85f183.png)
The above image shows the app component including a pipe that does not exist. The pipe is highlighted red as IntelliJ recognizes the pipe has not been imported. The terminal below shows a successful production build of the project including the missing pipe. I would expect the build to fail

The example above and the repo below are both built using Nrwl NX but the same issue can be found with a regular Angular project

## 🔬 Minimal Reproduction

Check out the following repo: https://github.com/lukebellamy053/angular-pipe-error-example
Build either of the applications, both should fail as the pipe is either not imported or just doesn't exist but the build passes in both cases

## 🔥 Exception or Error
There isn't one but there should be

**Comment by lukebellamy053** [comment]
@JoostK Looks like this is also the case with missing components as well

**Comment by JoostK** [comment]
Alright, it turns out that pipes are not reported as missing when `fullTemplateTypeCheck` is disabled/not set. I opened #39320 to address that, but it will continue to suffer from #36171.
