### ISSUE TITLE
Hi im making a update of #32724

### ISSUE THREAD

**Issue by AntonioCardenas** [angular/angular#38200]
Im here just to notice about the state of the new angular-es page and comunity we are working with @alvarocamillont and the page its ready on netlify https://angular-es.netlify.app/ im based on the angular-ja repo of @lacolaco if he agree i can continue working giving credit for the creation of the project base

**Comment by AntonioCardenas** [comment]
Hi this is the mentioned issue #32724 but this is not a issue is just a doc petition @kapunahelewong was the reviewer ,thanks a lot

**Comment by AntonioCardenas** [comment]
update app deployed to https://www.angular-es.dev/ waiting for response

**Comment by ericmartinezr** [comment]
Podrías enlazar el repositorio sobre el cual estás trabajando por si más gente se quiere unir a la traducción.

**Comment by AntonioCardenas** [comment]
@ericmartinezr aqui https://github.com/angular-es/Angular-es

**Comment by ericmartinezr** [comment]
@Splaktar I found another issue (https://github.com/angular/angular/issues/38503#issuecomment-677702279) where you mentioned that the website is being translated into spanish in the repo https://github.com/angular-hispano/angular. Is that one the "official" translation repo?

**Comment by Splaktar** [comment]
@ericmartinezr Yes, we've consolidated the efforts at https://github.com/angular-hispano/angular. It's online at https://docs.angular.lat (the https://angular.es domain is not active but is being held by someone not affiliated with us, in Spain).

You can find out more about Angular Hispano, including our CoC, guides, events, and how to register for our chat at https://angular.lat.

**Comment by Splaktar** [comment]
Oh and as for impacts to angular.io, we plan to make a PR to the official docs page to add the Spanish docs site in the coming weeks. We wanted to get the last bits of our sidenav translated first (PR in review atm).

**Comment by AntonioCardenas** [comment]
Sorry, I forgot to update that now I am working in conjunction with Angular Hispano so that there is no duplicate work and my project redirects to the new official project so I think we can close this issue
