### ISSUE TITLE
Removing ViewRef causes error in Ivy

### ISSUE THREAD

**Issue by waterplea** [angular/angular#38201]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8

### Description

I have a dropdown directive that creates a new view in a `ViewContainerRef` of dropdowns host component. If that new view also has this directive it can create another view. In `ngOnDestroy` of that directive I remove this view from `ViewContainerRef`. 

When parent dropdown is removed, I get an error in Ivy on destruction of nested directive created view. 

Seems like destruction of first view causes destruction of the second view in sync and when I attempt to remove second view I get error, because length is already updated as if parent view is removed (`length` is 1):
https://github.com/angular/angular/blob/0879d2e85d29c33c10e7314e49f5e4f0cc6ce2ba/packages/core/src/render3/view_engine_compatibility.ts#L209-L211

However both views are still there in `indexOf`:
https://github.com/angular/angular/blob/0879d2e85d29c33c10e7314e49f5e4f0cc6ce2ba/packages/core/src/render3/view_engine_compatibility.ts#L299-L302

So nested view reports being at index of 1 and this assertion fails thinking there is only index of 0 because it thinks `length` is 1:
https://github.com/angular/angular/blob/0879d2e85d29c33c10e7314e49f5e4f0cc6ce2ba/packages/core/src/render3/view_engine_compatibility.ts#L321-L331

## 🔬 Minimal Reproduction

Toggle parent, then toggle child, then toggle parent again to have them both removed
https://stackblitz.com/edit/angular-ivy-viewref-bug

Here's working example on Angular 8 with ViewEngine:
https://stackblitz.com/edit/angular-ve-viewref

## 🔥 Exception or Error
<pre><code>ERROR
Error: ASSERTION ERROR: index [Expected=> 1 < 1 <=Actual]</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>10.0.5</code></pre>

**Comment by Achilles1515** [comment]
Nice one.

Looks like the array item removal being done on...
```ts
// view_engine_compatibility.ts
// ViewContainerRef
remove(index?: number): void {
        this.allocateContainerIfNeeded();
        const adjustedIdx = this._adjustIndex(index, -1);
        removeView(this._lContainer, adjustedIdx);
        removeFromArray(this._lContainer[VIEW_REFS]!, adjustedIdx); // <--- this line
      }
```
...needs to be occurring...
```ts
// node_manipulation.ts
export function removeView(lContainer: LContainer, removeIndex: number) {
  const detachedView = detachView(lContainer, removeIndex);
  // <--- here
  detachedView && destroyLView(detachedView[TVIEW], detachedView);
}
```

As a workaround, you can just call `destroy()` on the `EmbeddedViewRef` itself.

```ts
export class DropdownDirective implements OnInit, OnDestroy {
  // ...
  ngOnDestroy() {
    // this.host.remove(this.ref);
    this.ref.destroy();
  }
}
```

**Comment by waterplea** [comment]
Thanks, @Achilles1515 don't I need to remove it though? What happens to the destroyed but attached view?

**Comment by pkozlowski-opensource** [comment]
@waterplea this looks like a valid bug in ivy indeed! I wonder if you would like to send a PR correcting this issue, given that you did quite a bit of digging into it? I can help with the process getting PR to the "land-able" state. If not I can fix this issue, please let me know what works best for you.

**Comment by Achilles1515** [comment]
> Thanks, @Achilles1515 don't I need to remove it though? What happens to the destroyed but not removed view? Will that also work for ComponentRefs hostView? I checked it logging length of ViewContainerRef and it seems to be a valid workaround.

Calling `ViewRef.destroy()` **does** remove it from a `ViewContainerRef`, if it is attached to one. It first detaches it, then destroys it.

See [here](https://github.com/angular/angular/blob/master/packages/core/src/render3/view_ref.ts#L75)
```ts
  destroy(): void {
    if (this._appRef) {
      this._appRef.detachView(this);
    } else if (this._viewContainerRef) {
      const index = this._viewContainerRef.indexOf(this);

      if (index > -1) {
        this._viewContainerRef.detach(index);
      }

      this._viewContainerRef = null;
    }
    destroyLView(this._lView[TVIEW], this._lView);
  }
```

It should work for `EmbeddedViewRef`s and `ComponentRef`'s host view, as they are both a `ViewRef`.

**Comment by Achilles1515** [comment]
@pkozlowski-opensource 

One route would be to just remove the `removeView` function entirely (I think it is only being called from `ViewContainerRef.remove()`), and just inline the detaching and destruction (similar to what is done in the snippet above from `ViewRef.destroy()`).

https://github.com/angular/angular/blob/0879d2e85d29c33c10e7314e49f5e4f0cc6ce2ba/packages/core/src/render3/node_manipulation.ts#L358-L361

Doing so would make the `ViewContainerRef.remove()` method this to fix the bug (imports would also need to be updated):

```ts
      remove(index?: number): void {
        this.allocateContainerIfNeeded();
        const adjustedIdx = this._adjustIndex(index, -1);
        const detachedView = detachView(this._lContainer, adjustedIdx);
        if (detachedView) {
          // Before destroying the view, remove it from the container's array of `ViewRef`s.
          // This ensures the view container length is updated before calling
          // `destroyLView`, which could recursively call view container methods that
          // rely on an accurate container length.
          // (e.g. a method on this view container being called by a child directive's OnDestroy lifecycle hook)
          removeFromArray(this._lContainer[VIEW_REFS]!, adjustedIdx);
          destroyLView(detachedView[TVIEW], detachedView);
        }
      }
```

As referenced in my first comment, another option is to move the

```ts
removeFromArray(this._lContainer[VIEW_REFS]!, adjustedIdx);
```

call into the `removeView` function, but I don't know if you guys would rather keep those `removeFromArray` calls directly in the `ViewContainerRef` class for visibility.

**Comment by waterplea** [comment]
I think removing function should be fine. I'll look into it more later, @pkozlowski-opensource I will try to make a PR.
