### ISSUE TITLE
ConstantPool timing issue with multiple components in a file

### ISSUE THREAD

**Issue by alxhub** [angular/angular#38203]
`ConstantPool` deduplicates constants by returning a particular kind of `o.Expression` called a `FixupExpression`, to which it retains a reference. For the first usage, this `FixupExpression` transparently returns the original `o.Expression`, so nothing special happens.

Whenever the `ConstantPool` encounters a second usage of the same value, however, it creates a shared variable declaration for the value, and uses its reference to the `FixupExpression` to replace its contents with a reference to this variable instead. Thus, the original usage is updated to refer to the constant instead of the literal value.

This works as long as all potential constants pass through the `ConstantPool` _before_ any of the `o.Expression` outputs are processed. However, in ngtsc the final compilation of classes violates this condition.

This compilation happens in a TypeScript transform (in `ngtsc/transform/src/transform.ts`, within `IvyVisitor`'s `visitClassDeclaration`). Each class goes through a process of `o.Expression` generation (which includes `ConstantPool` wrapping), then reification of `o.Expression`s into `ts.Expression`s via `translateExpression`, and then updating of the `ts.ClassDeclaration` to add the new static properties. Because `o.Expression`s are immediately converted to `ts.Expression`s, any `FixupExpression`s produced by the `ConstantPool` are converted **as they are** immediately following processing of that single class. Any future deduplication based on usage of the same constants by other classes will not affect them.

In practice, this means that such shared constants are always duplicated for the first class that uses them, and all subsequent classes use the shared variable declaration. This only affects constant reuse _between_ classes - constant reuse within the same class works normally.

**Comment by petebacondarwin** [comment]
@alxhub do we have any metrics on how often a constant is reused in applications - i.e. how much do we save in time and size by doing this constant deduplication?
