### ISSUE TITLE
Handle SwPush notification action without application running

### ISSUE THREAD

**Issue by tsproesser** [angular/angular#38218]
### Relevant Package
@angular/service-worker

### Description
Feeling a bit bad to open this issue since it **must** have been discussed elsewhere but I just can't found it. I already described the issue on stackoverflow, too ([link](https://stackoverflow.com/questions/63072347/handle-swpush-notification-action-without-application-running)).

All I'd like to achive is push notification action clicks being processed when the application is not running (e.g. sending the selected option back to the server). Relying on actions that only get executed when the application is running is no acceptable solution, that's why I think I must have missed something here. But if that really is the expected behavior this needs to change!

### Describe the solution you'd like
Since I guess it's not possible to bootstrap the whole application for executing the action (eventhough it should be somehow?) I should at least be able to set an endpoint getting called when the action is clicked and no application is running.

Also clicking the notification does not open the application - and there are only unclean solutions out there to work around it. It all feels a little bit "work in progess". Are there more features for SwPush in the pipeline?

**Comment by tsproesser** [comment]
Sorry for bumping but could someone please confirm me that this is the intended behavior? I can not beleave that I'm the only one having an issue with this?

**Comment by gkalpak** [comment]
You are right, @tsproesser. Our support for notification click action is kind of rudimentary (although there are work-arounds available).
This is being tracked in #26907, so let's move the discussion there.
