### ISSUE TITLE
documentation quickstart is not working

### ISSUE THREAD

**Issue by cultofmetatron** [angular/angular#3821]
<img width="946" alt="screen shot 2015-08-24 at 7 55 57 pm" src="https://cloud.githubusercontent.com/assets/5964/9457691/b963cc0e-4a9a-11e5-8e68-e4b1a3c7ed0d.png">

I heard angular2 is cool and wanted to try it verses react. I decided to spend some time onboarding myself.  I used the quickstart till I got to this point. At this point it completely broke and I can't figure out what is wrong.

**Comment by Fank** [comment]
use `viewBindings` instead of `appInjector` @angular2.0-alpha35

**Comment by mhevery** [comment]
Please provide an exception and repro case. I think @Fank probably pointed out the root cause.
