### ISSUE TITLE
Allow local WIP commits

### ISSUE THREAD

**Issue by dgp1130** [angular/angular#38225]
# 🚀 feature request

### Relevant Package

This feature request is for dev-infra

### Description
Currently, [WIP commits are explicitly disallowed by commit validation](https://github.com/angular/angular/blob/9322b9a06040e3401377e2123691230e1e7e62e8/dev-infra/commit-message/validate.spec.ts#L131-L138). That makes sense for merged code, but is really annoying for local development. I often want to use `wip: does this thing` as a simple commit message which is good enough for me to remember the context of the commit and clean up the message later.

### Describe the solution you'd like
Allow `WIP` commit messages, at lest for local commits. We can have a separate test that runs on PRs to make sure these don't get submitted, while still being more usable.

### Describe alternatives you've considered
Currently I think the best workaround is `--no-verify` or including a dummy commit message that fits the requirements. I never think to include `--no-verify`, and a lot of the time I'm using VSCode's commit functionality where I can't really specify that.

**Comment by sonukapoor** [comment]
Agreed. I think this would be super useful as well.

**Comment by atscott** [comment]
I believe this is resolved by #38784
