### ISSUE TITLE
Docs: StackBlitz sample project gives 404

### ISSUE THREAD

**Issue by paoloc0** [angular/angular#38221]
# 📚 Docs or angular.io bug report

### Description

The StackBlitz sample project link gives a 404 error.

### What's the affected URL?

https://angular.io/start#create-the-sample-project

### Reproduction Steps

Visit https://angular.io/start#create-the-sample-project and click on _Click here to create the ready-made sample project in StackBlitz_, which is a link to https://angular.io/generated/live-examples/getting-started-v0/eplnkr.html

## 🔥 Exception or Error
<pre><code>
Page Not Found

We're sorry. The page you are looking for cannot be found.
</code></pre>

**Comment by sonukapoor** [comment]
@paoloc0 I just tried this and it seems to work fine

**Comment by gkalpak** [comment]
It works for me too 🤷‍♂️
@paoloc0, are you getting any errors in the DevTools console?

**Comment by paoloc0** [comment]
@sonukapoor @gkalpak It works for me too, now. Clicking on the link now sends me (via various redirects) to:

https://stackblitz.com/angular/lbnogavalmp?file=src%2Fapp%2Fapp.component.ts

... whereas it previously sent me (repeatedly tested) to:
https://angular.io/generated/live-examples/getting-started-v0/eplnkr.html

The latter still gives a 404.

Ok, thanks - guess it's resolved itself, somehow.
