### ISSUE TITLE
Angular.io is not refreshing the page upon clicking on topic links on the left.

### ISSUE THREAD

**Issue by karthikk1984** [angular/angular#38222]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by sonukapoor** [comment]
Hi @karthikk1984 I just tried this and it seems to work as expected. Could you try again?

**Comment by ajitsinghkaler** [comment]
@karthikk1984 it's really hard to investigate this issue without reproduction.

**Comment by gkalpak** [comment]
I'm afraid there is not enough info on this issue for us to take an action. If you are still running into this problem, @karthikk1984, please open a new issue with more details.
