### ISSUE TITLE
loadTranslations throwing Unable to parse ICU expression exception

### ISSUE THREAD

**Issue by s992** [angular/angular#38230]
# 🐞 bug report

### Affected Package
`@angular/localize`

### Is this a regression?
Unsure if this is considered a regression as this is a new feature for me.

### Description
When using `loadTranslations` from `@angular/localize` and providing a translation such as `Version <x id="INTERPOLATION" equiv-text="{{ appVersion$ | async }}"/>`, a runtime error occurs.

The xlf file generated by `ng xi18n` looks like this:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en-US" datatype="plaintext" original="ng2.template">
    <body>
      <trans-unit id="my_id" datatype="html">
        <source>Version <x id="INTERPOLATION" equiv-text="{{ appVersion$ | async }}"/></source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">1</context>
        </context-group>
      </trans-unit>
    </body>
  </file>
</xliff>
```

## 🔬 Minimal Reproduction
1. Clone https://github.com/s992/i18ntest
2. `ng build --prod`
3. Serve the files in the `dist/i18ntest` directory (e.g. `npx http-server`)
4. Navigate to http://localhost:8080 (or your port of choice)
5. Observe error in console

## 🔥 Exception or Error
```
ERROR Error: Unable to parse ICU expression in "Version <x id="INTERPOLATION" equiv-text="{{ appVersion$ | async }}"/>" message.
    at main.8831a1ce5c96d40b5885.js:1
    at main.8831a1ce5c96d40b5885.js:1
    at template (main.8831a1ce5c96d40b5885.js:1)
    at Vr (main.8831a1ce5c96d40b5885.js:1)
    at Lr (main.8831a1ce5c96d40b5885.js:1)
    at as (main.8831a1ce5c96d40b5885.js:1)
    at main.8831a1ce5c96d40b5885.js:1
    at Lr (main.8831a1ce5c96d40b5885.js:1)
    at ri.create (main.8831a1ce5c96d40b5885.js:1)
    at t.bootstrap (main.8831a1ce5c96d40b5885.js:1)
```

## 🌍  Your Environment

**Angular Version:**
Note that the following is from the minimal repro, issue also occurs in Angular 9.

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.4
Node: 10.16.3
OS: darwin x64

Angular: 10.0.5
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.4
@angular-devkit/build-angular     0.1000.4
@angular-devkit/build-optimizer   0.1000.4
@angular-devkit/build-webpack     0.1000.4
@angular-devkit/core              10.0.4
@angular-devkit/schematics        10.0.4
@angular/cli                      10.0.4
@ngtools/webpack                  10.0.4
@schematics/angular               10.0.4
@schematics/update                0.1000.4
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
OK so the problem is that you are passing XLIFF formatted translations to the `loadTranslations()` function here https://github.com/s992/i18ntest/blob/3c8c4faa62360bf2e1776e50ca52d77aca9e6ce0/src/polyfills.ts#L9

This function accepts translations in the "simple JSON" format only. See https://github.com/angular/angular/blob/4857c53a49851e04e32dbe3987f3bb9d005a63e0/integration/ivy-i18n/src/polyfills-runtime.ts#L73 for an example of how to do this.

**Comment by s992** [comment]
@petebacondarwin Thank you so much for the quick response! I've been searching for documentation on the simple JSON format this morning but am coming up empty handed. Would it be accurate to say that the best way to deal with these translation files currently is to use `locl`'s [`convert`](https://github.com/loclapp/locl/tree/master/libs/cli#conversion) functionality to translate my XLIFF files into JSON?

**Comment by petebacondarwin** [comment]
That's definitely an option. Otherwise you'll need to start touching our private APIs like https://github.com/angular/angular/blob/master/packages/localize/src/tools/src/translate/translation_files/translation_parsers/xliff1_translation_parser.ts#L40

**Comment by s992** [comment]
Thanks @petebacondarwin ! Appreciate it.
