### ISSUE TITLE
404 Page component given 200 status in header

### ISSUE THREAD

**Issue by rsyscraft** [angular/angular#38232]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
I have facing issue in 404 route. when page or url not found we call custom component for 404 page and it gives 200 status code in google seo. So i would like to asky you for can we set custom header status of page component if not then please add it in angular feature so that we can set page header same like php

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by ajitsinghkaler** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
