### ISSUE TITLE
ViewMetadata doesn't have public constructor in d.ts 

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#3825]
`ViewMetadata` and other *Metadata classes don't have a public constructor present in our d.ts files.

Since `TestComponentBuilder` takes `ViewMetadata` via it's public api, this constructor should be public as well.

**Comment by mhevery** [comment]
https://github.com/angular/angular/commit/1926335b85af6c1fe56f4e36d0b95dcc92bb5c42
