### ISSUE TITLE
Add angular component to angular built project

### ISSUE THREAD

**Issue by nijakanthan** [angular/angular#38250]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Hi,
Is there any possibilities to add/import a new component to already built angular project
If it not possible, please provide the proper technical explanation.

Please help me on this..

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by nijakanthan** [comment]
Thanks for you reply

**Comment by gnaneswarreddy** [comment]
> 🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
> 
> Hi,
> Is there any possibilities to add/import a new component to already built angular project
> If it not possible, please provide the proper technical explanation.
> 
> Please help me on this..
> 
> 🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Hi Nija,

Can you reply on the windows-automation-spy issue please, sorry to post here.
