### ISSUE TITLE
KeyEventPlugin forces event handler in `ngZone`, the behavior is different with non key event handler.

### ISSUE THREAD

**Issue by JiaLiPassion** [angular/angular#38260]
Consider the following case.

app.component.html
```
<button #btnToggle>Toggle</button>
<div *ngIf="show">
  <button (click)="onClick()">Button</button>
  <input (keydown.enter)="onKeydown()"/>
</div>
```

app.component.ts
```
export class AppComponent implements AfterViewInit {
    @ViewChild('btnToggle') btnToggle: ElementRef;
    show = false;
    constructor(private zone: NgZone, private cd: ChangeDetectorRef) {}

    ngAfterViewInit() {
      this.zone.runOutsideAngular(() => {
        const el = this.btnToggle.nativeElement as HTMLElement;
        el.addEventListener('click', e => {
          this.show = true;
          this.cd.detectChanges();
        })
      })
   }

   onClick() {
      console.log('button click in ngZone? ', NgZone.isInAngularZone());
   }

   onKeydown() {
      console.log('keydown in ngZone? ', NgZone.isInAngularZone());
    }
}
```

The live sample is here https://stackblitz.com/edit/angular-hga7lk?file=src%2Fapp%2Fapp.component.ts

After click the `toggle` button, then click the inside `button` and press enter inside the `input`.
The output will be:

```
button click in ngZone?  false
keyDown in ngZone? true
```

This is not consistent

**Comment by artaommahe** [comment]
@JiaLiPassion why keydown listener should run outside of zone in your example?

**Comment by JiaLiPassion** [comment]
@artaommahe, since the `keydown` listener is added outside of `ngZone`, you can check this issue for more information https://github.com/angular/angular/issues/37062

**Comment by artaommahe** [comment]
@JiaLiPassion hm, but new behavior looks counter-intuitive. Developer needs to know some angular core stuff to understand why click/keydown is running outside angular zone despite they are just declared in template like any other event listeners.

**Comment by JiaLiPassion** [comment]
@artaommahe , I totally understand your concerns and agree with your point, but this issue and related PR doesn't introduce a `new` behavior. The current behavior (except the events like  `keydown.enter`) is `outside` ngZone.

```
<button #btnToggle>Toggle</button>
<div *ngIf="show">
  <button (click)="onClick()">Button</button>
  <input (keydown.enter)="onKeydown()"/>
</div>
```

In this case, the current behavior is 

1. the `button click` is outside of ngZone.
2. the `keydown` is inside ngZone.

Which is not consistent. And most cases are like `button` click, so this issue and PR just make `keydown.enter` behaves the same way as `button click`.

Of course we can discuss this behavior is correct/confuse or not in another issue.
