### ISSUE TITLE
ngOnChanges doesn't work on two way data binding [(ngModel)]

### ISSUE THREAD

**Issue by pixieaka** [angular/angular#38261]
**Component**
```
import { Component, OnChanges } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnChanges {
  title = 'app';
  user = '';

  ngOnChanges(): void {
    console.log('user changed !');
  }
}
```

**View**
```
<input type="text"
       name="user"
       id="user"
       [(ngModel)]='user'>


<p>{{user}}</p>
```

**Comment by alexkunin** [comment]
Aren't you using `'user'` string literal (i.e. not a reference to `user` field) in `ngModel` binding?

**Comment by pixieaka** [comment]
In this way Computed methods in angular is very hard to achieve, Vue JS is very power full in this point, angular must have method like `ngOnChange` but work internally we need to watch properties and take some actions it's simple requirement for every application literally.

**Comment by alexkunin** [comment]
Well, for some reason change detection works differently for the root component. Which might be a very valid reason because root is a very special, though still would be nice to have some explanation or warning in docs (I couldn't find one).

Still, it works on "normal" components (i.e. non-root ones), and that's probably an acceptable workaround.

**Comment by pixieaka** [comment]
For example when you have 20 properties by `ngModel` and want to take the same actions on every change of each of them this can be hard to write on every `textbox` `(change)` directive.

**Comment by alexkunin** [comment]
I don't think I understand your case clearly, do you have some code to look at?

What exactly is hard -- sheer amount of boilerplate code? You could wrap desired behavior into custom directive (to be added to `<input>`) or component (to replace `<input>`), or maybe use `@ViewChildren` to process child components in a loop.

Also keep in mind that `ngOnChanges()` is quite a low level thingie, I mean it is rarely needed to use it directly. If you describe your use case, I might be able to help you find some less verbose solution. Though this might be an off-topic for this issue.

**Comment by pixieaka** [comment]
Sorry for miss understanding i'm not professional in angular i'm used to do things in VueJS way with Computed method I can watch tones of properties and take some action's if they changes.

I want the same result for example my component is 20 textboxs, I want to watch them on any change of each of them fire the same function.

**Comment by pixieaka** [comment]
This can achive with `ngDoCheck` method but this can be very load on performance.

**Comment by mlc-mlapis** [comment]
### [**@pixieaka**](https://github.com/pixieaka) 

You probably missed some information. The `OnChanges` hook focusses on bounded inputs on a component level. https://angular.io/api/core/OnChanges

The main root component of an application doesn't have any bounded inputs, it's a bootstrap element of the app, so the `OnChanges` on it has no sense. On any other component, it runs when any of its inputs have been changed.

So probably you want to use the syntax `<input [ngModel]="user" (ngModelChange)="userChanged($event)" />`, where \``userChanged`\` is a method, that runs when a user changes the input value. It's necessary to say, that there are 2 principal ways how to process forms. Template-based and reactive-based. https://angular.io/guide/forms-overview

**Comment by pixieaka** [comment]
Thank you very much I appreciated to help me @mlc-mlapis , @alexkunin . (ngModelChange) it's very much what i need.

**Comment by mlc-mlapis** [comment]
### **@pixieaka** 

If you have a form with 20 inputs, it would be probably better to use the reactive way and create a model based on `FormGroup`. https://angular.io/api/forms/FormGroup

**Comment by pixieaka** [comment]
@mlc-mlapis  I'll take full course in angular on Udemy soon. All the best bro appreciated. I wish for you success for your future projects.
