### ISSUE TITLE
systemjs sample not working fine in chrome browser only

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular#38267]
# 🐞 bug report

I have created systemjs sample in angular. it is working fine in other browser. facing issue only in chrome browser.

### Is this a regression?

yes

1. working fine in typescript platform - in all browsers
2. facing issue in angular and only in chrome browser

### Description

drag and drop is not working fine in angular at chrome browser

### Angular sample:

1. download below sample:
[drag-drop-action.zip](https://github.com/angular/angular/files/4987997/drag-drop-action.zip)
2. Run `npm i lite-server`
3.Then open terminal and give `lite-server`
4. drag `draggable element` and drop it into `drop target` - **element not get dropped.**

>Note: check hosted in in IE, it is working fine but in chrome my drag element not get dropped properly

### typescript sample

https://ej2.syncfusion.com/documentation/common/drag-and-drop/#defining-drop-action 

open above link and click preview tab,

**Comment by kumaresan-subramani** [comment]
HI @alan-agius4 ,

I need your suggestion, can you please suggest on this

**Comment by alan-agius4** [comment]
@kumaresan-subramani, seems like this is caused by an older version of `zone.js` which patches the event listeners.
 
Please note that Angular 5 is no longer supported. The current supported versions are Angular 8, 9 and 10. See: https://angular.io/guide/releases#support-policy-and-schedule

**Comment by kumaresan-subramani** [comment]
@alan-agius4 , thanks for the reply but in below sample i have used angular 4

https://github.com/kumaresan-subramani/quickstart/blob/master/package.json

**Comment by alan-agius4** [comment]
You’d need to update to a more modern version of Angular which supports at least Zone.js 0.9.x or later.

**Comment by kumaresan-subramani** [comment]
HI @alan-agius4 ,

Thanks brother, while upgrading my zone.js version it works like a charm
