### ISSUE TITLE
Add animation keyframe events to trigger callback function

### ISSUE THREAD

**Issue by moshe5745** [angular/angular#38269]
# 🚀 feature request

### Description
Current animations have only **start** and **done** events.

```
<div [@openClose]="isOpen ? 'open' : 'closed'"
    (@openClose.start)="onAnimationEvent($event)"
    (@openClose.done)="onAnimationEvent($event)"
    class="open-close-container">
</div>
```

It would be convenient to catch events from keyframe offset points too.

### Describe the solution you'd like
So if we define the following keyframes:

```
transition('* => openClose', [
  animate('2s', keyframes([
    style({ 'customEventName1', backgroundColor: 'blue', offset: 0.2 }),
    style({ 'customEventName2', backgroundColor: 'red' offset: 0.6 }),
    style({ 'customEventName3', backgroundColor: 'orange' , offset: 0.9 })
  ]))

```
We could bind them like this:

```
<div [@openClose]="isOpen ? 'open' : 'closed'"
    (@openClose.customEventName1)="onAnimationEvent($event)"
    (@openClose.customEventName2)="onAnimationEvent($event)"
    (@openClose.customEventName3)="onAnimationEvent($event)"
    class="open-close-container">
</div>
```

**Comment by jelbourn** [comment]
Closing this since I don't see us building a feature like this because the underlying CSS keyframe animations don't offer any kind of event for this, so having the framework reliably figure this out would likely not be feasible.
