### ISSUE TITLE
Zone.js: current task return null using Angular 8

### ISSUE THREAD

**Issue by Mubashir-Ali1** [angular/angular#38277]
how to find the reason why after sometime Zone.currentTask return null and then Angular app will be freeze until I will close the tab. Unfortunately there is no error in console. 

Thanks

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
