### ISSUE TITLE
Path alias doesn't work for libraries (tsconfig.lib.json)

### ISSUE THREAD

**Issue by gbrunow** [angular/angular#38278]
# 🐞 bug report

### Description
Path aliases don't work for libraries, paths are not found.
Similar to what is described on #16382 but for libs.

## 🔬 Minimal Reproduction
1. Create a new workspace and add a library
```
ng new path-issue --create-application=false
cd path-issue
ng generate library test-lib
```

2. Create a component in the `components` folder
```
ng g c components/dummy
```

3. Add a path alias to `projects/test-lib/tsconfig.lib.json`
```
"paths": {
  "@components": [
    "/projects/test-lib/src/lib/components"
  ],
  "@components/*": [
    "/projects/test-lib/src/lib/components/*"
  ]
}
```
4. Import it from the auto-generated component `test-lib.component.ts`
```
import { DummyComponent } from "@components/dummy/dummy.component";
```

5. Run `ng build`

Sample: https://github.com/gbrunow/path-issue

## 🔥 Exception or Error
<pre><code>
------------------------------------------------------------------------------
Building entry point 'test-lib'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
ERROR: projects/test-lib/src/lib/test-lib.component.ts:2:32 - error TS2307: Cannot find module '@components/dummy/dummy.component' or its corresponding type declarations.

2 import { DummyComponent } from "@components/dummy/dummy.component";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

An unhandled exception occurred: projects/test-lib/src/lib/test-lib.component.ts:2:32 - error TS2307: Cannot find module '@components/dummy/dummy.component' or its corresponding type declarations.

2 import { DummyComponent } from "@components/dummy/dummy.component";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.4
Node: 13.11.0
OS: darwin x64

Angular: 10.0.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.4
@angular-devkit/build-angular      0.1000.4
@angular-devkit/build-ng-packagr   0.1000.4
@angular-devkit/build-optimizer    0.1000.4
@angular-devkit/build-webpack      0.1000.4
@angular-devkit/core               10.0.4
@angular-devkit/schematics         10.0.4
@angular/cli                       10.0.4
@ngtools/webpack                   10.0.4
@schematics/angular                10.0.4
@schematics/update                 0.1000.4
ng-packagr                         10.0.3
rxjs                               6.5.5
typescript                         3.9.7
webpack                            4.43.0
</code></pre>

**Anything else relevant?**
Defining paths on `/tsconsig.base.json` and/or defining `baseUrl`doesn't help either.

**Comment by gkalpak** [comment]
Paths starting with `/` (e.g. `/projects/...`) are absolute to your filesystem. You want to use paths relative to the `baseUrl` (or to the tsconfig's location if there is no `baseUrl`, so in your case it should be `projects/...` (without the leading `/`).

Closing since everything seems to work as expected.

**Comment by gbrunow** [comment]
@gkalpak Make it `./src/lib/components` still doesn't work. `/projects/...` is actually relative to `tslint.base.json` same as `./projects`.
I've tried several different combinations regarding the path and none seemed to work.

My folder structures is as follows:
```
.
+-- projects
|     +-- src
|     +-- tslint.lib.config.json
+-- tslint.base.config.json
```

Therefore `./projects/...` would be relative to `tslint.base.config` and './src' to `tslint.lib.config.json`. None of which work.
I've updated the sample repo to point to `./src/lib/components`.

**Comment by gkalpak** [comment]
`projects/...` worked for me (i.e. `ng build` completed successfuly).
What error are you getting with `projects/...`? What command did you run, `ng build` or something else?

**Comment by gbrunow** [comment]
Just tried a few more thing and this worked:
```
"baseUrl": "src/lib",
"paths": {
  "@components": [
    "components"
  ],
  "@components/*": [
    "components/*"
  ]
}
```

**Comment by gbrunow** [comment]
Yes, `ng build`.
With any other configuration I got the error stated above.

**Comment by gbrunow** [comment]
Curiously enough this does not work:
```
"paths": {
  "@components": [
    "src/lib/components"
  ],
  "@components/*": [
    "src/lib/components/*"
  ]
}
```

**Comment by gbrunow** [comment]
I played around some more and apparently if you don't add `baseUrl` it just doesn't work.
`baseUrl` isn't inherited from `tsconfig.base.json`.

**Comment by gkalpak** [comment]
Glad you got it working :rocket:

**Comment by gbrunow** [comment]
@gkalpak I've just had some interesting development on this.

After:
 1. fixing the library as mentioned above
 2. building it 
 3. installing it via `npm i dist/test-lib` (so it can be tested while being developed)
 4. importing it on a test app in the same workspace

I see the following error message when building the app:
```
ERROR in dist/test-lib/lib/test-lib.component.d.ts:2:32 - error TS2307: Cannot find module '@components' or its corresponding type declarations.

2 import { DummyComponent } from '@components';
```
**Note that the import that fails is in the already built code.**

I've updated the repo and and to reproduce it just run `ng build test-lib; ng build test;`
Or is this something I should open an issue on `ng-packagr`?

**Comment by gbrunow** [comment]
`ng build test-lib; ng build test` also fails by the way.
With the following message:
```
ERROR in The target entry-point "test-lib" has missing dependencies:
 - @components
```
