### ISSUE TITLE
Angular app will freeze after loading 3rd party lib in tab.

### ISSUE THREAD

**Issue by Mubashir-Ali1** [angular/angular#38288]
I am loading leaflet map in primeng tab. After loading it when I click on any other tab App will freeze and nothing is work until close the tab. Unfortunatly there is no error in console.

**Comment by sonukapoor** [comment]
@Mubashir-Ali1 Have you tried removing the 3rd part library to see if Angular is behaving as expected. If it does, I recommend you reach out to the library owner and file an issue on their issue tracker

**Comment by Mubashir-Ali1** [comment]
Let me describe the complete use cases.

1- When I show a single tab and load 3rd party library(leaflet map) in it. It is working fine.
2- When I have a multiple tabs. Click other than map tab also working fine (Navigation between tabs except map tab).
3- When click on map tab, map is rendered and also data is displaying on tab map.
4. After the 3rd step, click on any other tab App will freeze nothing will work.

**Code TS file**
 class TabViewComponent implements OnChanges {
  loadFirstTab(): void {
    let defaultRoute = '';
    if (this.tabs && this.tabs.length) {
      // Set default route (First tab) on the basis of sort order (excluded hidden Tabs)
      defaultRoute = this.tabs[0].route;
      console.log(defaultRoute);
       this.router.navigate([defaultRoute],
         { relativeTo: this.route, skipLocationChange: true, preserveQueryParams: true });
    }
  }

onTabChange(event: any) {
    console.log(event);

      this.router.navigate([this.tabs[event.index].route],
         { relativeTo: this.route, skipLocationChange: true, preserveQueryParams: true });
  }

}

**HTML file**

<p-tabView (onChange)="onTabChange($event)">
  <div *ngFor="let item of tabs; let i = index">
    <p-tabPanel [header]="item.label" [selected]="i == 0" [disabled]="item.isDisabled" *ngIf="item.isVisible">
    </p-tabPanel>
  </div>
  <router-outlet></router-outlet>
</p-tabView>

**Comment by neofuture** [comment]
umm <router-outlet> inside a PrimeNG tab ? the router outlet is there to output the router component/module

**Comment by ocombe** [comment]
I've used leaflet with Angular in a project recently, and it didn't freeze anything. I think that there's something wrong in your code, but it has nothing to do with Angular.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by Mubashir-Ali1** [comment]
@neofuture 
I am using router-outlet for loading the lazy loaded components in tab-view. Is there any other good way.

**Comment by neofuture** [comment]
https://github.com/angular/angular/issues/33654

Have a look here
