### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Bunny899** [angular/angular#38286]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....core

### Is this a regression?

 Yes, the previous version in which this bug was not present was:...

### Description
Uncaught TypeError: Cannot read property 'id' of undefined
    at registerNgModuleType (core.js:23870)
    at core.js:23881
    at Array.forEach (<anonymous>)
    at registerNgModuleType (core.js:23881)
    at new NgModuleFactory$1 (core.js:23978)
    at compileNgModuleFactory__POST_R3__ (core.js:27497)
    at PlatformRef.bootstrapModule (core.js:27735)
    at Module../src/main.ts (main.ts:12)
    at __webpack_require__ (bootstrap:79)
    at Object.0 (main.ts:13)
 A clear and concise description of the problem...

I am getting this error while upgrading my angular CLI.
please help me 

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>Angular CLI: 10.0.4
Node: 12.16.3
OS: win32 x64

Angular: 10.0.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.4
@angular-devkit/build-angular     0.1000.4
@angular-devkit/build-optimizer   0.1000.4
@angular-devkit/build-webpack     0.1000.4
@angular-devkit/core              10.0.4
@angular-devkit/schematics        10.0.4
@angular/cdk                      10.1.1
@angular/cli                      10.0.4
@angular/http                     6.1.10
@angular/material                 10.1.1
@ngtools/webpack                  10.0.4
@schematics/angular               10.0.4
@schematics/update                0.1000.4
rxjs                              6.6.0
typescript                        3.9.7
webpack                           4.44.0<code>

</code></pre>

**Anything else relevant?**

I have upgraded it successfully but I don't know why this error is occurring..please help me.

**Comment by blomqma** [comment]
Had the same issue, then I found using this helpful: https://bit.ly/30dbEhf

**Comment by vugar005** [comment]
> Had the same issue, then I found using this helpful: https://bit.ly/30dbEhf

That page referred me back to this page.

**Comment by vugar005** [comment]
> Had the same issue, then I found using this helpful: https://bit.ly/30dbEhf

Sorry that page said no Service found and redirected me to this page.

**Comment by vugar005** [comment]
> Had the same issue, then I found using this helpful: https://bit.ly/30dbEhf

Sorry that page said no Service found and redirected me back to this page.

**Comment by alxhub** [comment]
@Bunny899 unfortunately to investigate this issue fully, we're going to need a reproduction on StackBlitz or as a linked Github repository that demonstrates the problem.

Off the top of my head though, this looks like it could be a circular dependency issue, where some imported module is `undefined` at runtime while the cycle is being resolved.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
