### ISSUE TITLE
i18n guide should have a word about /assets/ folder

### ISSUE THREAD

**Issue by rslemos** [angular/angular#38299]
# 📚 Docs or angular.io bug report

### Description

The [i18n guide](https://angular.io/guide/i18n) should explain how does i18n deals with assets (in `/assets/` folder).

In particular, it should address recommendations about how to reference those assets (and how to localize them). I'm currenly facing this issue. My application used to work fine before i18n, but now that extra path component (`/en/` before any resource) spoiled every reference to `/assets` (which now should be `/en/asstes`).

**Comment by rslemos** [comment]
I found out that my application have 2 mistakes, even before applying i18n.

In templates, I had a bunch of `<img src="/assets/images/...">`. It worked before because my `baseHref` was `/`. If I had the correct `<img src="assets/images/...">` (note the prefix `/` - which should be supplied by baseHref in first place - had been removed) then everything would be fine in whatever baseHref.

In scss, I had some `url("/assets/images/...")`. Again it only worked before because of my previous baseHref. I'm not sure, but I think SASS refused to rework these absolute urls. Once changed to relative urls (like `../assets/images/...`  and `../../assets/images/...`) SASS began packaging the referenced files in the root path, and changing `url(...)` to the appropriate path.

Everything is working fine now. But I still think it's worth a word or two in i18n guide (perhaps a troubleshooting section).

**Comment by alan-agius4** [comment]
Considering the little interest in this from the community and the fact that this is how base-href works even when not using i18n. I don't think this warrants to be included in our docs. 

Let's re-consider in the future if more users request this.
