### ISSUE TITLE
Make a way  to add  new DecoratorHandlers or change some existing DecoratorHandlers

### ISSUE THREAD

**Issue by abadakhshan** [angular/angular#38300]
Angular compiler uses `DecoratorHandlers `  to handle decorators on compile time.

[NgCompiler](https://github.com/angular/angular/blob/d8c07b83c3d137e3380f98b75685c3513d1fb18c/packages/compiler-cli/src/ngtsc/core/src/compiler.ts) uses them to compile Angular projects.

I want a way to add my custom decorator handles to it or change some default handles behaviour.

I think It would be possible via some method in custom Angular Cli builder.
With this approach, developers can extend Angular compiler.

**Comment by JoostK** [comment]
The Angular compiler and its interfaces have not been designed as public API and will not be exposed as requested.
