### ISSUE TITLE
Router: Needs a way to be manually shutdown/disposed (mutli-app or tests)

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#3830]
Discussed this offline a bit, but because the `Router` injectable listens (indirectly) to location changes, and is not part of the destroy cycle of components when an application is disposed, during tests and multi-app environments it's possible for a route change to trigger a dynamic component loader load into DOM that no longer exists.

**Comment by btford** [comment]
Thanks! I'll look this week.

**Comment by mhevery** [comment]
Should be part of #1594

**Comment by btford** [comment]
Just chatted with @alxhub about this– we think we have a solution as a part of #1594 for this.

**Comment by btford** [comment]
@alxhub – Can you give a status update on this?

**Comment by alxhub** [comment]
#4915 should resolve this issue.

**Comment by btford** [comment]
So this can be closed now that #4915 has landed?

**Comment by matanlurey** [comment]
:+1:
