### ISSUE TITLE
Typo in the glossary entry for structural directives

### ISSUE THREAD

**Issue by zaracooper** [angular/angular#38314]
# 📚 Docs or angular.io bug report
### Description

There's an error in the glossary entry for structural directives. The dash is not displayed correctly. This is what is displayed. The section in bold is the problem. 

> A category of directive that is responsible for shaping HTML layout by modifying the **DOM&mdashthat** is, adding, removing, or manipulating elements and their children.

### What's the affected URL?
https://angular.io/guide/glossary#structural-directives

### Expected vs Actual Behavior
With the dash displayed correctly, it should look something like this (section in bold): 
> A category of directive that is responsible for shaping HTML layout by modifying the **DOM—that** is, adding, removing, or manipulating elements and their children.

## 📷 Screenshot
<img width="1428" alt="structural directive glossary typo" src="https://user-images.githubusercontent.com/54225554/89034931-a2272c80-d342-11ea-8e73-4135129a14b9.png">

**Comment by juanarbol** [comment]
@AndrewKushnir I think t his is ready to be closed, this was fixed by https://github.com/angular/angular/commit/585ef2bdd7084110b969032ef6b0cccbaa6a93e5

**Comment by sonukapoor** [comment]
Closed by https://github.com/angular/angular/pull/38318
