### ISSUE TITLE
No intellisense/autocompletion due to tsconfig files

### ISSUE THREAD

**Issue by MeMeMax** [angular/angular#38312]
### Affected Package
The issue is most probablycaused by package "@angular/cli": "~10.0.4",

### Is this a regression?
Yes, the previous version in which this bug was not present was: I can´t say which was the last version this worked on...most probably 9.x.x, but it worked in versions before ;-)

### Description
I generated a new Angular Project with Angular CLI 10.0.4. It generated the project and added the different tsconfig files. Unfortunately I could no longer use auto completion.

For example I removed this line from app-routing.module.ts
`import { Routes, RouterModule } from '@angular/router';`

Then I set my cursor to the end of "Routes" in this line and pressed CMD+Space:
`const routes: Routes = [];`

But it didn´t suggest me to import from @angular/router. This happens as well with Modules which I generated myself.

This issue is due to the tsconfig files:

tsconfig.json
```
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ]
}
```

tsconfig.app.json
```
{
  "extends": "./tsconfig.base.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": [],
    "paths": {
      "@task/*": ["src/app/task/*"]
    }
  },
  "files": ["src/main.ts", "src/polyfills.ts"],
  "include": ["src/**/*.d.ts"]
}
```

tsconfig.base.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": ["es2018", "dom"]
  }
}
```

If I replace my tsconfig.app.json with a tsconfig from another (older) app, it works.
e.g.
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2017", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@customer-request/common-ui": ["libs/common-ui/src/index.ts"],
      "@customer-request/p-house-connection": ["libs/p-house-connection/src/index.ts"],
      "@customer-request/p-internet-connection": ["libs/p-internet-connection/src/index.ts"],
      "@customer-request/auth": ["libs/auth/src/index.ts"]
    }
  },
  "exclude": ["node_modules", "tmp"]
}
```

Nevertheless I want to use the new structure but there seems to be any issue in it.

## 🔬 Minimal Reproduction
Generate a new App with version 10.0.4 of Angular CLI and try to auto import any Element like shown above.

## 🔥 Exception or Error
No real Error, intellisense/autocomplete just doesn´t work.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.4
Node: 12.16.1
OS: win32 x64

Angular: 10.0.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.4
@angular-devkit/build-angular     0.1000.4
@angular-devkit/build-optimizer   0.1000.4
@angular-devkit/build-webpack     0.1000.4
@angular-devkit/core              10.0.4
@angular-devkit/schematics        10.0.4
@angular/cli                      10.0.4
@ngtools/webpack                  10.0.4
@schematics/angular               10.0.4
@schematics/update                0.1000.4
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Comment by KapilSachdev** [comment]
Prima-facie it does not seems like an angular issue, Which editor are you using and which tool you are using for intellisense/autocompletion? (vscode and atom both editors are behaving as expected for me)

Can you verify if the editor or tool you are using for auto-completion works with [`Solution Style tsconfig.json Files`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#support-for-solution-style-tsconfigjson-files), as i too have encountered similar issue where `eslint` stopped linting because of this `Solution Style` introduced in TypeScript 3.9.

**Comment by MeMeMax** [comment]
I am using VS Code.
