### ISSUE TITLE
zone.js incorrectly throws an error when rejecting a Promise with the `DISABLE_WRAPPING_UNCAUGHT_PROMISE_REJECTION` flag enabled

### ISSUE THREAD

**Issue by antch** [angular/angular#38334]
# 🐞 bug report

### Affected Package
zone.js

### Is this a regression?
No.

### Description
Recently the flag `DISABLE_WRAPPING_UNCAUGHT_PROMISE_REJECTION` was added with #35873 to allow disabling of the wrapping behavior that zone.js performs on rejected promise values. Unfortunately, when this flag is enabled the zone.js code throws an unexpected error when a non-Error value is rejected, due to the code attempting to set various properties on the rejected value regardless of type: https://github.com/angular/angular/blob/31796e8e2fa78fb55ae0c8bf461c4ad742898363/packages/zone.js/lib/common/promise.ts#L209-L212

For example, if I reject a Promise with the value "42" the following error occurs:
`Error: Cannot create property 'rejection' on number '42'`

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/zonejs-disable-promise-reject-wrapping-issue

## 🔥 Exception or Error
If I reject a Promise with the value "42" the following error occurs:
<pre><code>
`Error: Cannot create property 'rejection' on number '42'`
</code></pre>

This is reproducible with any non-error value (number, string, null, etc.)

## 🌍  Your Environment
Stackblitz repro is Angular 10, but here is the output from my own project:

**Angular Version:**
<pre><code>
Angular CLI: 9.1.12
Node: 10.14.2
OS: darwin x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.5
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12 (cli-only)
@angular/cdk                      9.2.4
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.39.3
</code></pre>

Note that my own project along with the Stackblitz repro are both on zone.js 0.10.3.

**Comment by JiaLiPassion** [comment]
@antch , thank you for posting the issue, I will fix this one.
