### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by alippai** [angular/angular#3833]
Where can we find a roadmap for Angular 2.0 beta release? Is there a feature and/or QA goal set for the beta/rc/stable releases or do you work by thresholds?

**Comment by gdi2290** [comment]
ya
Angular 2 Roadmap Update at AngularU.com in San Francisco
[![Angular 2 Roadmap Update at AngularU.com in San Francisco](http://img.youtube.com/vi/aHGmj_fqPLE/0.jpg)](http://www.youtube.com/watch?v=aHGmj_fqPLE)

here's the weekly meeting notes 
https://docs.google.com/document/d/150lerb1LmNLuau_a_EznPV1I1UHMTbEl61t4hZ7ZpS0/edit?pli=1

watch/attend [AngularConnect](http://angularconnect.com/)
