### ISSUE TITLE
Angular 9+ cannot use Angular 9 lib inside of Angular 9+ not ivy application/lib with barrels

### ISSUE THREAD

**Issue by criskrzysiu** [angular/angular#38346]
All informations in NGRX issue
https://github.com/ngrx/platform/issues/2643

**Comment by JoostK** [comment]
I notice this issue is regarding View Engine issues with regards to barrel files; unfortunately that is a widespread issue which has been addressed in Ivy, but is still present in VE.

**Comment by JoostK** [comment]
With v12 now allowing libraries to be compiled with the Ivy compiler, I'll close this as resolved.
