### ISSUE TITLE
BrowserAnimationsModule not working properly with scrollPositionRestoration

### ISSUE THREAD

**Issue by vajahath** [angular/angular#38341]
# 🐞 bug report

### Affected Package
This is possibly caused by the `BrowserAnimationsModule` from `@angular/platform-browser/animations`
### Description
Scroll position is not restoring properly when `BrowserAnimationsModule` is used in the project.
See the demo reproduction. Try commenting the `BrowserAnimationsModule` to see the difference.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-c4pgqm
Please note to see the scroll behaviour you need to open the stackblitz preview in a separate tab: https://angular-ivy-c4pgqm.stackblitz.io

### `BrowserAnimationsModule` enabled (results in incorrect behaviour :x: )
```ts
@NgModule({
  imports:      [ AppRoutingModule, BrowserModule, BrowserAnimationsModule], // <-- here
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }
```
(incorrect behaviour demo)
![Peek 2020-08-04 16-52](https://user-images.githubusercontent.com/12165822/89288972-1da31980-d674-11ea-89f8-aca53a80fcc4.gif)

Sometimes it behaves correctly and sometimes it won't.

### `BrowserAnimationsModule` disabled (working properly :heavy_check_mark: )
```ts
@NgModule({
  imports:      [ AppRoutingModule, BrowserModule, /*BrowserAnimationsModule*/], // <-- here
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }
```
Note that scroll position is retained here correctly when coming back to the route.
(expected behaviour)
![Peek 2020-08-04 16-55](https://user-images.githubusercontent.com/12165822/89289297-a02bd900-d674-11ea-9181-d126391a1173.gif)

## 🌍  Your Environment

**Angular Version: 10.0.1** ( see stackblitz)

**Comment by sod** [comment]
Not very helpful, but it works in Firefox :D

**Comment by jelbourn** [comment]
Next steps for this issue would be investigating _why_ this happens (and whether it's something in Angular responsible), especially since it seems to work fine in Firefox.

**Comment by KostyaTretyak** [comment]
At the moment, this problem is still unresolved. I have a simpler example:

![angular-scroll-bug](https://user-images.githubusercontent.com/2286306/153790034-fc77c7c0-78f1-4035-ac53-eb7f12e5f351.gif)

**Comment by KostyaTretyak** [comment]
By the way, `NoopAnimationsModule` has same issue.

**Comment by JeanMeche** [comment]
I'm flagging as needing a repro, I was able to reproduce it on Chrome.

**Comment by alxhub** [comment]
Closing as no reproduction was provided (feel free to open a new issue with one if you can reproduce it!)
