### ISSUE TITLE
Link that needs correction :  https://angular.io/guide/set-document-title

### ISSUE THREAD

**Issue by pejman-saberin** [angular/angular#38343]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
Hi Team,

I ran into this link on Angular site that needs some correction:  https://angular.io/guide/set-document-title

Regards,
Pejman

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by sonukapoor** [comment]
@pejman-saberin Could you please provide more information on where exactly the correction is needed?

**Comment by pejman-saberin** [comment]
Hi, At first, I could not find what that guide is linked to. I thought it is a draft. What document is that link to?

**Comment by sonukapoor** [comment]
@pejman-saberin I do not think the document is a draft. It describes how to use the `Title` service to set the title of the document.
