### ISSUE TITLE
Merge script to warn in case `feat` commits are present before merging into a patch branch

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#38351]
# 🚀 Feature request

### Description
When merging PRs with multiple commits it's easy to miss a `feat` commit that may go into a patch branch accidentally. Since only `dev-infra` feature commits are allowed in patch branch, it'd be great to check all commits that are about to be merged to patch branch and warn caretaker in case there is a `feat` commit with a scope other than `dev-infra`.

// cc @josephperrott @devversion

**Comment by devversion** [comment]
Great suggestion. I'd need to play with how it can work for the autosquash and Github API merge strategy. Most likely it should be part of the label configuration, where each label has something like a `validate` hook (that might even work nicely with validations we have for branches)

**Comment by AndrewKushnir** [comment]
Closing this ticket since this logic was already implemented into the merge script.
