### ISSUE TITLE
Unable to install the angular/cli

### ISSUE THREAD

**Issue by bojidaryovchev** [angular/angular#38363]
C:\Windows\system32>npm i -g @angular/cli
npm ERR! code E404
npm ERR! 404 Not Found: @yarnpkg/lockfile@1.1.0

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dev\AppData\Roaming\npm-cache\_logs\2020-08-06T10_49_08_790Z-debug.log

**Comment by sid-maddy** [comment]
> There is an ongoing [NPM issue](https://web.archive.org/web/20200806105739/https://status.npmjs.org/) with scoped packages

Close this issue and subscribe to angular/angular-cli#18462 for updates
P.S. You should open issues related to the Angular CLI in the [angular/angular-cli](https://github.com/angular/angular-cli/) repo
