### ISSUE TITLE
TypeError: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by rifler** [angular/angular#38361]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/zone.js

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
`instanceof` is not safe operation, so if you monkeypatch such substantial method as `Object.prototype.toString`, you have to use try..catch

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>TypeError: Right-hand side of 'instanceof' is not an object
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by rifler** [comment]
https://github.com/angular/angular/pull/38350

**Comment by AndrewKushnir** [comment]
Hi @rifler, thanks for creating this ticket. Could you please provide more information on this issue, so we can perform an investigation? It'd be helpful to have a minimal repro in a form of GitHub repo or using a [Stackblitz](https://stackblitz.com/). Thank you.

**Comment by rifler** [comment]
> Hi @rifler, thanks for creating this ticket. Could you please provide more information on this issue, so we can perform an investigation? It'd be helpful to have a minimal repro in a form of GitHub repo or using a [Stackblitz](https://stackblitz.com/). Thank you.

Hi @AndrewKushnir!

It is hard to explain. I support some third-party script, that works on many sites. All our code is wrapped in try..catch and arising errors are sent to our backends to analyze.

And there are many errors from angular sites in some _not new browsers_ - `TypeError: Right-hand side of 'instanceof' is not an object`

This error rises in monkey-patched `Object.prototype.toString`, you can see fix in my closed PR - https://github.com/angular/angular/pull/38350/files#diff-1ea597cc37810838e2adf0433681b63bR53. I think it arises because sites don't add Promise polyfill

All I want to say:
- `instanceof` is not safe operation, it can throw errors and have to be wrapped in try..catch
- monkey patching is not safe, so if you add some behaviour (except `return original.call(this, ...args);` - you have to wrap it in try..catch

can you please reopen and merge my PR?

**Comment by AndrewKushnir** [comment]
Hi @rifler, thanks for providing additional information.

I'm adding @JiaLiPassion to this thread to get his opinion from the ZoneJS standpoint (he should also have an access to reopen PR #38350 once the root cause is identified).

Thank you.

**Comment by JiaLiPassion** [comment]
@rifler, I can reproduce the issue.

```
<html>
  <body>
    <script src="./node_modules/zone.js/dist/zone.js"></script>
    <script>
      window[Zone.__symbol__('ZoneAwarePromise')] = undefined;
      window[Zone.__symbol__('Promise')] = undefined;
      const obj = {};

      console.log('toString', obj.toString());
    </script>
  </body>
</html>
```

And about the fix, use `try/catch` will impact the performance and also swallow the error.
So the recommend fix is 

```
        Object.prototype.toString = function () {
            if (typeof Promise !== 'undefined' && this instanceof Promise) {
                return PROMISE_OBJECT_TO_STRING;
            }
            return originalObjectToString.call(this);
        };
```

could you update the PR? thanks!

**Comment by rifler** [comment]
@AndrewKushnir thanks you

@JiaLiPassion I updated PR with `typeof Promise === 'function'`, I think it is more safely
