### ISSUE TITLE
bug(@angular/material-moment-adapter): ERROR in getInternalNameOfClass() called on a non-ES5 class: expected MomentDateAdapter to have an inner class declaration

### ISSUE THREAD

**Issue by nminhduc** [angular/angular#38369]
#### Reproduction

Steps to reproduce:
1.  try to change angular material dateime picker dateime format on IE 11 with example on https://stackblitz.com/angular/ggrjljebbey?file=src%2Fapp%2Fdatepicker-formats-example.ts
https://material.angular.io/components/datepicker/examples - Datepicker with custom formats

2. run project with es5 config
    "compilerOptions": {
        "target": "es5" 
    }
 
 
#### Expected Behavior

work on IE 11
currently, it worked on chrome with run command: ng serve --aot
don't work on IE 11 with run:  ng serve --configuration es5 --aot
es5 config:
 {
    "extends": "./tsconfig.app.json",
    "compilerOptions": {
        "target": "es5" 
    }
}

run serve success with: ng serve --configuration es5
but error when open app in IE:
Syntax error
 Uncaught (in promise): ChunkLoadError
class MomentDateAdapter extends _angular_material_core__WEBPACK_IMPORTED_MODULE_1__["DateAdapter"] {

#### Environment

- Angular: 9
- MomentDateAdapter : 10
- CDK/Material: 9.2
- Browser(s): ie 11
- Operating System (e.g. Windows, macOS, Ubuntu):  Win 10 64 bit

**Comment by jelbourn** [comment]
@gkalpak I _suspect_ this is related to ngcc- do you have any insight here?

**Comment by petebacondarwin** [comment]
@nminhduc - there should be no need to run with `target: es5` any more, since the CLI will automatically generate downleveled ES5 code for "differential loading" if you have setup the browsers you support correctly. In that case, the build will use ES2015 versions of libraries and so avoid this issue - I believe.

See https://angular.io/guide/deployment#differential-loading

**Comment by nminhduc** [comment]
@petebacondarwin If don't use `target: es5` my application can not run on IE 11.
https://medium.com/better-programming/how-to-fix-your-angular-app-when-its-not-working-in-ie11-eb24cb6d9920

**Comment by nminhduc** [comment]
@petebacondarwin update some other scenarios:
When I use `ng build` to get a package and use lite-serve to run. amazing, it's worked on both chrome and IE 11
When I try to edit DateTime format in runtime
https://stackoverflow.com/a/51696436/5118204
https://stackblitz.com/edit/date-picker-format-change?file=src%2Fapp%2Fcomponents%2Fapp-component%2Fapp.component.html
It's worked on the package case(`ng build and lite-serve` on both chrome and IE 11
but it's not worked on both chrome and IE 11
when run serve `ng serve --configuration es5 --aot`
`Uncaught (in promise): TypeError: Class constructor MomentDateAdapter cannot be invoked without 'new'
TypeError: Class constructor MomentDateAdapter cannot be invoked without 'new'`
but worked on chrome with `ng serve --aot`

**Comment by petebacondarwin** [comment]
I see that your stackblitz is on Angular v8 - can you try updating to v10?

**Comment by nminhduc** [comment]
@petebacondarwin My project is Angular 9. stackblitz is an only internet link. however, I will try on angular 10

**Comment by Radiniiiim** [comment]
![Screenshot_20200809-181948.jpg](https://user-images.githubusercontent.com/67246541/90270652-c9681880-de6f-11ea-8967-49c5d4e501b2.jpg)

**Comment by nminhduc** [comment]
@petebacondarwin  I was updated to angular 10 and angular material 10, it was worked on `ng serve --configuration es5 --aot ` so only one solution is to upgrade angular 10?

**Comment by petebacondarwin** [comment]
@nminhduc that sounds expected - keeping the major versions in sync (9 with 9, 10 with 10) is a good idea. Ideally if you can update to v10 you are in a better place since that will contain the majority of fixes and features going forward.
