### ISSUE TITLE
@Host not setting attribute

### ISSUE THREAD

**Issue by wisesascha** [angular/angular#3837]
The host property is not properly setting the attribute. In my app it sampling becomes `undefined`. Im doing this and its simple not working
`constructor(@Host()  tabs:Tabs) {`
Tabs is defined in the same file.
This issue is the same when they are in separate files.

**Comment by pkozlowski-opensource** [comment]
@wisesascha it is hard / impossible to say what it your pb here just based on the description. If you believe that there is a bug in ng2 please share a _minimal_ plunk demonstrating it. 

I saw that you were getting support on gitter so hopefully I've managed to sort it out by now. If not feel free to re-open with a minimal, live reproduce scenario.
