### ISSUE TITLE
ngOnDestroy is not calling on providers during unit-testing

### ISSUE THREAD

**Issue by fetis** [angular/angular#38374]
# 🐞 bug report

### Affected Package
`@angular/core/testing`

### Is this a regression?
I don't know

### Description

Lifecycle hook `ngOnDestroy` is not called for providers during unit-testing

## 🔬 Minimal Reproduction
I made a repo for this https://github.com/fetis/providers-ondestroy/blob/master/src/some.service.spec.ts

I expect to have a console message and green test, but get no message and failed test

Motivation: `ngOnDestroy` for service might be a rare case but if service gets some resource it needs to be freed during the testing as well.

## 🔥 Exception or Error
<pre><code>
  An error was thrown in afterAll
  Error: Expected spy ngOnDestroy to have been called.
      at <Jasmine>
      at UserContext.<anonymous> (http://localhost:9878/_karma_webpack_/src/some.service.spec.ts:17:17)
      at ZoneDelegate.invoke (http://localhost:9878/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:364:1)
      at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9878/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:292:1)
Chrome 84.0.4147.105 (Mac OS 10.13.6): Executed 1 of 1 ERROR (0 secs / 0.013 secs)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.5
Node: 12.18.3
OS: darwin x64

Angular: 10.0.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.5
@angular-devkit/build-angular     0.1000.5
@angular-devkit/build-optimizer   0.1000.5
@angular-devkit/build-webpack     0.1000.5
@angular-devkit/core              10.0.5
@angular-devkit/schematics        10.0.5
@angular/cli                      10.0.5
@ngtools/webpack                  10.0.5
@schematics/angular               10.0.5
@schematics/update                0.1000.5
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Comment by JoostK** [comment]
Well, that's coincidentally what #38336 should address :-)

**Comment by fetis** [comment]
@JoostK ah, that's sweet

**Comment by JoostK** [comment]
This is indeed resolved if `ModuleTeardownOptions.destroyAfterEach` is enabled, which it is by default since v13.
