### ISSUE TITLE
Unit testing regression in Angular 9/10

### ISSUE THREAD

**Issue by fetis** [angular/angular#38373]
# 🐞 bug report

### Affected Package
`@angular/core/testing` probably?

### Is this a regression?
Yes

### Description
Angular team changed the logic of how unit tests compile with Ivy release [(more details](https://blog.angular.io/version-9-of-angular-now-available-project-ivy-has-arrived-23c97b63cfa3)) and now test suite doesn't recompile on every run. But this also brings side effects when you're using providers with `useValue` because now they live between test runs and might be changed in between. _They're are not clean anymore._

This makes tests running on Angular 8 fail on Angular 9/10 without a clear reason. 

## 🔬 Minimal Reproduction
I made a repo to illustrate this https://github.com/fetis/ng-testing
It has 2 branches `angular8` and `angular10`. Checkout `angular8`, install and run, you will have 2 green tests.
Now checkout out `angular10`, install packages, and run the tests. The same test suite will fail.

I know that it's caused because the reference to the service mock is held between 2 case runs and I know how to fix, _but_ I'm not talking about this. I'm talking about dev experience and backward compatibility. Imagine a project with 2k tests that start to fail randomly (Jasmine 3.x also might run tests in the random order, so execution order really matters here) after the upgrade, and imagine a nightmare to debug this.

This way of mocking was quite valid and reflected in docs. Since now it has that huge drawback I think Angular framework should at least produce a warning if you give a non-primitive value for providers. 
Of course, it's an open question of how to handle this situation with possible solutions like
- throw a warning
- deep freeze
- return back functionality
I would like to hear Angular developers opinion about this.

In practice, I found `useValue` much shorter rather than using `useClass` or `useFactory`

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.5
Node: 12.18.3
OS: darwin x64

Angular: 10.0.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.5
@angular-devkit/build-angular     0.1000.5
@angular-devkit/build-optimizer   0.1000.5
@angular-devkit/build-webpack     0.1000.5
@angular-devkit/core              10.0.5
@angular-devkit/schematics        10.0.5
@angular/cli                      10.0.5
@ngtools/webpack                  10.0.5
@schematics/angular               10.0.5
@schematics/update                0.1000.5
rxjs                              6.6.2
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Anything else relevant?**

**Comment by fetis** [comment]
any response on this?

**Comment by atscott** [comment]
This works as intended in Ivy. When `useValue` is used it is literally saying to use that value which means the value by necessity becomes a singleton.

In VE in JIT mode this will have the same behavior as in Ivy (We are sharing instance of the `useValue`)

In VE in AoT mode there is a bug where we wrap the `useValue` in something like this:
```
factory() {
  return  {modified: 0};
}
```
The result is that in AoT `useValue` is not a singleton.

This means that VE has inconsistent behavior between JIT and AoT mode.

confirming that in JIT in VE values are shared: https://stackblitz.com/edit/angular-hpurdz

workaround is `useFactory: () =>  {modified: 0}`

**Comment by fetis** [comment]
@atscott what is 'VE' in your exlanation?

**Comment by atscott** [comment]
@fetis - Sorry, VE is for "View Engine", the runtime/compiler used by angular pre-v9
