### ISSUE TITLE
recompile components at runtime

### ISSUE THREAD

**Issue by sumigoma** [angular/angular#3838]
In Angular2, will it be possible to recompile components at runtime or have components whose templates are dynamic (change at runtime), a la $compile? DynamicComponentLoader seems to support the adding components dynamically into the component tree, but their templates are still defined statically for compilation at startup.

**Comment by gdi2290** [comment]
this will be easier to do after this PR https://github.com/angular/angular/issues/3605 I'm assuming your usecase is either A/B testing, Hot Component reload, or different user permission

**Comment by sumigoma** [comment]
Yea, I was wondering where this would fit in if components are now going to be precompiled during the build process. My usecase is basically hot component reload and general extensibility, though all of your cases seem applicable too.

**Comment by danicomas** [comment]
@gdi2290 by now don't exist something as $compile(template)($scope) is not it?

I am creating a component that it has a button and this call a service then it will open a modal. I can add the modal in the DOM with DOM.appendChild but I don't know how can I add the component or the template compiled. In Angular 1.X I would do:

var linkFn = $compile(template);
var el = linkFn($scope);
el.append(el)

**Comment by danicomas** [comment]
Is possible add a component without root(elementRef) and move it @gdi2290?

```js
return this.loader.loadNextToLocation(Dialog, this.elementRef).then(containerRef => {
      //move the element to the body
      var dialogElement = containerRef.location.nativeElement;
      DOM.setStyle(dialogElement, 'display', 'none');
      DOM.appendChild(DOM.query('body'), dialogElement);
      this.dialogRef = containerRef;
      return containerRef;
    });
```

**Comment by danicomas** [comment]
@gdi2290 @sumigoma @mhevery @btford @PascalPrecht  can we compile similar in Angular1 $compile(template)(component)? or the best way is doing that? Regards

**Comment by mhevery** [comment]
@danicomas yes you can using the `Compiler`

**Comment by danicomas** [comment]
@mhevery Are you saying we should use the DynamicComponentLoader passing the root elementRef (By now we can't use this without elementRef) or exist something like Angular1(get template + create scope and compile both)?

**Comment by webteckie** [comment]
I also have a use case for this.  Can a plunkr example be provided on how to use the compiler as suggested by @mhevery ?

**Comment by danicomas** [comment]
@mhevery do you have news about that? Or @vicb @gdi2290?

**Comment by mhevery** [comment]
You can create components on the fly like this: https://github.com/angular/angular/blob/1f2302e39e42220e0ad5179fb63abbd667e3d1f3/modules/upgrade/src/upgrade_module.ts#L66-L77 and than load them using `DynamicComponentLoader`

**Comment by danicomas** [comment]
Nice @mhevery . But I see that you are using ng1 services. It only will be possible via ng1 injection in ng2 or with ng2 core too? Are you saying that in ng2 the correct way is load via loader.loadNextToLocation or other DynamicComponentLoader method instead the get the template and compile?
