### ISSUE TITLE
docs: review and update AOT compiler guide

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#38381]
# 📚 Docs or angular.io bug report

### Description

It looks like the [AOT compiler guide](https://angular.io/guide/aot-compiler) is a bit outdated in a context of Ivy ([for example this section](https://angular.io/guide/aot-compiler#no-arrow-functions)). It'd be great to review the entire guide and structure it around Ivy compiler features/capabilities.

**Comment by Splaktar** [comment]
Our GDEs have been reporting questions from the community on this as well. The current statements in the doc around arrow functions cause confusion.

**Comment by elca-lan** [comment]
Yes.... they do. I was just spending some time on that to figure out what is actually going on. With a brand new 12.2.4 sample project, using a lambda (arrow function) as the `useFactory` in a provider results in the following AOT output:

```
class MyService {
    constructor(name) {
        this.name = name;
    }
}
class AppModule {
}
AppModule.ɵfac = function AppModule_Factory(t) { return new (t || AppModule)(); };
AppModule.ɵmod = /*@__PURE__*/ _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵɵdefineNgModule"]({ type: AppModule, bootstrap: [_app_component__WEBPACK_IMPORTED_MODULE_0__.AppComponent] });
AppModule.ɵinj = /*@__PURE__*/ _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵɵdefineInjector"]({ providers: [
        {
            provide: MyService,
            useFactory: () => new MyService("test")
        }
    ], imports: [[
            _angular_platform_browser__WEBPACK_IMPORTED_MODULE_2__.BrowserModule
        ]] });
(function () { (typeof ngJitMode === "undefined" || ngJitMode) && _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵɵsetNgModuleScope"](AppModule, { declarations: [_app_component__WEBPACK_IMPORTED_MODULE_0__.AppComponent], imports: [_angular_platform_browser__WEBPACK_IMPORTED_MODULE_2__.BrowserModule] }); })();
```

As we can see here, there are some contradictions to what the docs are saying:
* The documentation states that "The AOT compiler does not support function expressions and arrow functions...". While it later _corrects_ that statement, it does so in the very last sentence of that section which is... let's call it "_unfortunate_ placement". It seems that this is now in fact pretty well supported and so the entire section of "No arrow functions" could probably be removed IMO.
* Both, in the sections about "No arrow functions" and "Metadata rewriting", the documentation states that lambdas are extracted and rewritten to become exported functions (in "No arrow functions") or exported constants (in "Metadata rewriting"). According to my test above, both of those are incorrect.

Which is what brought me here. What exactly **is** the current expected support for lambda expressions in the AOT context? Is it just fully supported now?
