### ISSUE TITLE
Setting Promise object to img [src] sets image to null..sometimes

### ISSUE THREAD

**Issue by Githubber2021** [angular/angular#38386]
Hi, I use Angular within my Electron app.

I have a component with an array of objects called `files`, where each `file` has a member called `preview` which is a **Promise** object and returns a `file://` object.

```
<mat-list-item *ngFor="let file of files;">
<img mat-list-avatar [src]="file.preview ? (file.preview | async | safe) : 'assets/file.png'"
...
```

`files` is an **@Input** in this component. When I rebuild this array it in the parent component I often get broken images.

Eventually, by moving the mouse across the window, the images are drawn properly. Does anyone know if there is a redraw missing somewhere, or how I can find out why the img src is temporarily set to null sometimes?

P.S. In the `safe` pipe I can confirm that the incoming value is already null in some cases, although `file.preview` has a Promise object attached to it.

Thank you!

**After refocusing the app window:**
![image](https://user-images.githubusercontent.com/57302913/89726717-b971b400-d9eb-11ea-990c-1f2110b3d24c.png)

**After moving the mouse for a second across the app window:**
![image](https://user-images.githubusercontent.com/57302913/89726726-c5f60c80-d9eb-11ea-9ec2-69743442c561.png)

**Comment by lazarljubenovic** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
