### ISSUE TITLE
Router scrollPositionRestoration should be configurable via outlets

### ISSUE THREAD

**Issue by rsouthgate** [angular/angular#38382]
# 🐞 bug report

(this may be considered a feature request - but to my mind it is a current defect in scrollPositionRestoration)

It has previously been open and closed (#26848) due to no repro - so have added a repro to this one.

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?
No

### Description
When scrollPositionRestoration is enabled the behaviour on forward navigation is always to go to viewport [0,0]. This may be undesirable when auxilary routes are implemented but it is not configurable or overrideable at either an outlet or a route.

## 🔬 Minimal Reproduction
https://auxiliary-route-modal-animated-basic-working-example.stackblitz.io

(Scroll down to the link to navigate to an auxilary route. In this example the route might open a modal that gives context to the primary outlet and it's scrolled position - therefore it is undesirable to scroll away from the link. But with scrollPositionRestoration enabled (often desired on the primary router outlet) it will take you back to the top.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.0
Node: 14.5.0
OS: darwin x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.0
@angular-devkit/build-angular      0.901.7
@angular-devkit/build-ng-packagr   0.901.0
@angular-devkit/build-optimizer    0.901.7
@angular-devkit/build-webpack      0.901.7
@angular-devkit/core               9.1.0
@angular-devkit/schematics         9.1.0
@angular/cdk                       9.2.0
@ngtools/webpack                   9.1.7
@schematics/angular                9.1.0
@schematics/update                 0.901.0
ng-packagr                         9.1.0
rxjs                               6.5.4
typescript                         3.8.3
webpack                            4.42.0
    
</code></pre>

**Comment by tlaverdure** [comment]
I would also like to see this feature. The example provided is the exact issue I'm running into with outlets that control overlays like modals and even fixed sidebars.

**Comment by tlaverdure** [comment]
Enabling in `NavigationExtras` would also be a good solution as described here: https://github.com/angular/angular/issues/26744

**Comment by atscott** [comment]
Closing in favor of #26744
