### ISSUE TITLE
Angular DragDropModule not working with IE11

### ISSUE THREAD

**Issue by zionrealcommerce** [angular/angular#38392]
# 🐞 bug report

### Affected Package

 

"@angular/animations": "~9.1.11",
    "@angular/cdk": "^10.1.2",
    "@angular/common": "~9.1.11",
    "@angular/compiler": "~9.1.11",
    "@angular/core": "~9.1.11",
    "@angular/forms": "~9.1.11",
    "@angular/platform-browser": "~9.1.11",
    "@angular/platform-browser-dynamic": "~9.1.11",
    "@angular/router": "~9.1.11",
    "classlist.js": "^1.1.20150312",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.10.2"

### Description

 An error  in IE11 when trying to import the DragDropModule in the app module
Syntax error
vendor.js (64,1)

....class Directionality {....

## 🔥 Exception or Error
<pre><code>

import {DragDropModule} from '@angular/cdk/drag-drop';
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    DragDropModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.1.12
Node: 12.12.0
OS: win32 x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: No

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/cdk                      10.1.2
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by Jefiozie** [comment]
Hi @zionrealcommerce,

I believe you created the issue in the wrong repo. [Here](https://github.com/angular/components/issues/new/choose) you can create an issue for the material team that is handling the `cdk` module.

They will assist you with your problem. Could you close this issue so that we keep a clean backlog? 

Thanks

**Comment by JoostK** [comment]
I think this has little to do with Material at all, it looks like the code is not downleveled to ES5 for IE support.

Also, you appear to be using `@angular/cdk` 10 while still on Angular 9, that's a bit unexpected to me. Angular 10 has dropped the ES5 bundles and fully relies on downleveling through the differential loading feature to achieve IE/ES5 compatibility, but the v9 toolchain may not operate as expected using v10 dependencies. I'd recommend aligning the versions to be all v9, or all v10, but not mixed.

Please see [the Differential Loading documentation](https://angular.io/guide/deployment#differential-loading) for more information. At this point, I don't think this is actionable from our side, so I'll close this as a support request. For additional troubleshooting, consider asking a question on platforms such as StackOverflow. If you do think there's a bug with Angular, though, feel free to open a new issue.
