### ISSUE TITLE
Can't use a <form> tag with a [formControl] directive

### ISSUE THREAD

**Issue by kara** [angular/angular#38391]
🐞 bug report

### Affected Package
The issue is caused by package angular/forms.

### Is this a regression?

I don't think this is new behavior

### Description

It's not currently possible to wrap a `[formControl]` directive in a `<form>` tag because an error is thrown by `NgControlStatusGroup` that the `ControlContainer` is missing. This isn't right because `[formControl]` directives are intended to be used without a `ControlContainer`. 

The problem seems to be caused by `NgControlStatusGroup` having too broad of a selector, so that it activates on all `form` tags. 

Workarounds:
- You can circumvent the problem by adding `ngNoForm` to the parent `<form>` tag, but that is not intuitive
- You can also work around the problem by adding the `FormsModule` so `NgForm` is automatically created. However, this isn't really correct because it requires mixing the forms modules.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-cke9q5?file=src%2Fapp%2Fapp.component.html

If you load that Stackblitz, you can see the error in the console.

## 🔥 Exception or Error
<pre><code>
preview-e378c6d150742202f755b.js:1 ERROR Error: NodeInjector: NOT_FOUND [ControlContainer]
    at getOrCreateInjectable (core.umd.js:4047)
    at Object.ɵɵdirectiveInject (core.umd.js:14362)
    at NodeInjectorFactory.NgControlStatusGroup_Factory [as factory] (forms.umd.js:1058)
    at getNodeInjectable (core.umd.js:4141)
    at instantiateAllDirectives (core.umd.js:8464)
    at createDirectivesInstances (core.umd.js:7831)
    at Object.ɵɵelementStart (core.umd.js:14511)
    at AppComponent_Template (app.component.ts:18)
    at executeTemplate (core.umd.js:7804)
    at renderView (core.umd.js:7613)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
Ivy, v10

**Comment by mlc-mlapis** [comment]
@kara Nice to hear from you again. :smiling\_face\_with\_three\_hearts: 

> You can circumvent the problem by adding `ngNoForm` to the parent `<form>` tag, but that is not intuitive.

Yep, it's a bit hidden feature, but still, even with this directive, the console prints `NOT_FOUND [ControlContainer]`.

**Comment by AndrewKushnir** [comment]
@kara thanks for reporting the issue! The fix was merged and it's now available in google3 :)
