### ISSUE TITLE
 facing a issue in angular site route navigation

### ISSUE THREAD

**Issue by AnkitEncom** [angular/angular#38395]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please help me i am facing a issue in angular site route navigation.
my site url is this in local
http://192.168.17.30:4200/login
on server 
https:// ******/login

When i reload the same page with F5 then it come like 

https:// ******/login/login

again i hit to reload then site not working blank page comes.

When i navigate to menu then its works fine but in all route when i reload the site or hit F5 same url added in route like 
https:// ******/checkstatus/checkstatus
etc...

Please anyone can help what i am doing wrong.

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by alan-agius4** [comment]
Closing as per above.

**Comment by AnkitEncom** [comment]
ok thank you for responding.
i will post it on StackOverflow.

**Comment by AnkitEncom** [comment]
**Thanks man** i got the solution as you suggest from StackOverflow  @ericmartinezr @alan-agius4 

**Yeah, there it is, change <base href=""> to <base href="/"> in index.html**
