### ISSUE TITLE
can not import module after upgrading Angular 10 from Angular 9

### ISSUE THREAD

**Issue by anjneeksharma** [angular/angular#38390]
Upgraded to Angular 10 from 9 now i am getting some import error even after installing those module.
Bellow are the module which i am not able to import.

import { ApolloModule} from 'apollo-angular';
import { HttpLinkModule} from 'apollo-angular/http';

but i can import  import {HttpLink} from 'apollo-angular/http';  

Please help me.

**Comment by santoshyadavdev** [comment]
Check with https://github.com/kamilkisiela/apollo-angular they had released 4 days ago.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
