### ISSUE TITLE
Add Macro Directive type to compiler.

### ISSUE THREAD

**Issue by sskyy** [angular/angular#384]
Is there a way to get the original element before the directive on it replace it with the template? If there not, is it possible to add a precompile option which would be a function receive the original element to the directive definition object.
I'm making some new with angular now and I want to use the original element before directive take effect. Thx.

**Comment by tbosch** [comment]
Right now, this is not possible in a generic way. We thought about so called "macro" directives that would be able to do this, but there is a big downside to directives that change the DOM during compile: The can introduce new directives, and therefore analyzing the template by IDEs and tools gets really hard without executing the directives...

Could you explain your use case a little more?

**Comment by biiiipy** [comment]
I use this functionality in Angular 1.X for modifying templates at runtime - basically loading up a generic template and customizing it using runtime environment information. If this feature is not present in 2.0, it will seriously reduce the flexibility and power of AngularJS.

**Comment by sskyy** [comment]
http://sskyy.github.io/Gilgamesh/   This is my current work. I need this functionality for template overwrite at runtime just like @biiiipy said.

**Comment by mhevery** [comment]
This will fall under macro directive. We need to have macro directives for i18n, so your use case would be covered.

**Comment by gdi2290** [comment]
there is an issue for this here https://github.com/angular/angular/issues/521

**Comment by truongminh** [comment]
At this point, the template is a string.
Is it possible to pass in a promise as the `template`?
https://github.com/angular/angular/blob/215c4aa8fb75183b2f1ed88413bea1fabee8558e/modules/angular2/src/render/dom/compiler/view_loader.ts#L92
If so, additional modification could be made simple.

**Comment by mhevery** [comment]
Dup of #521
