### ISSUE TITLE
Investigate potential code savings in "hello world" app by shutting off optional features

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#3840]
The outcome of this exercise would be a report on the final code size and a recommendation for what we should do next to get there.

**Comment by yjbanov** [comment]
Update: below are code size improvements from removing forms, intl pipes (numbers, currency, date), long stack traces, Uri and dynamic change detector.

### Before

Minified ungzipped: 511kb
Minified gzipped: 145kb

### After

Minified ungzipped: 365kb (-28%)
Minified gzipped: 105kb (-27%)

### Breakdown

The reliance of Dart core libs dropped from 126kb to 89kb. Angular's own code dropped from 176kb to 141kb. Dropped the deps on 3rd-party libs, including `package:intl`, `package:stack_trace`, `package:path`.

With #3605 we should be able to drop large chunks of code in `angular2.src.core.compiler` (34kb), `angular2.src.render.dom.compiler` (23kb) and `angular2.src.change_detection` (31kb). #3285 should yield more compact and better tree-shakable dart2js output.

**Comment by bradlygreen** [comment]
Nice!

Where are we on JS/TS?  What can be reused there?

**Comment by yjbanov** [comment]
@bradlygreen, JS is in a bit of a flux until @jeffbcross is done splitting up the code into bundles. Right now all of Angular 2 minified ungzipped is [506kb](https://code.angularjs.org/2.0.0-alpha.35/), so "hello, world" would be that plus user code, i.e. identical to the current Dart situation. This will likely change drastically after unbundling.
