### ISSUE TITLE
Time element throws "is not a known element" in Unit Tests

### ISSUE THREAD

**Issue by Martinspire** [angular/angular#38409]
# 🐞 bug report

### Affected Package

It happens with unit testing, not entirely sure what package is responsible.

### Is this a regression?

No I think it has always been a bug

### Description

When using a HTML Time element `<time></time>` during `ng test` it gives back a warnning because it doesn't recognize it as an element.

## 🔬 Minimal Reproduction

Any time element will do, but for example: `<time>19-08-2020</time>`. Run a unit test and it will pop up.

## 🔥 Exception or Error
<pre><code>
WARN: ''time' is not a known element:
1. If 'time' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.'
</code></pre>

## 🌍  Your Environment

**Angular Version:**
9.1.10 but I think it hasn't been fixed yet.

**Anything else relevant?**

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time

Workaround is to not use it, use the no_errors_schema or mock the element as if it was Angular.

**Comment by MrJithil** [comment]
Seems an issue with your unit test framework. Are you using Karama/Jasmine or JEST? 
I tested with the Karma/Jasmine, and the unit tests were passing.

**Comment by Martinspire** [comment]
I'm using Karma/Jasmine. And I know of the workaround. I don't have anything special in the karma conf.

Right now I'm using this setup:
```

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-phantomjs-launcher'),
      require('@angular-devkit/build-angular/plugins/karma'),
      require('karma-mocha-reporter'),
      require('karma-jasmine-html-reporter'),
    ],

    reporters: ['mocha', 'kjhtml'],
    mochaReporter: {
      ignoreSkipped: true,
      maxLogLines: 5,
    },
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    browsers: ['Chrome'],
    browserNoActivityTimeout: 60000,
    singleRun: false,
  });
};
```

**Comment by Martinspire** [comment]
No wait, it happens when I'm running the tests with PhantomJS, so that would be this config:

```
module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-phantomjs-launcher'),
      require('@angular-devkit/build-angular/plugins/karma'),
      require('karma-coverage-istanbul-reporter'),
      require('karma-mocha-reporter'),
    ],
    reporters: ['mocha'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    browsers: ['PhantomJS'],
    browserNoActivityTimeout: 60000,
    singleRun: true,
  });
};

```

But I'm not sure where this should be picked up as the message comes in Angular. I don't know if for certain elements polyfills are used...

**Comment by MrJithil** [comment]
FYI it is not an issue with the Angular. The frameworks and tools for testing is causing the fails.

Could you please create a dummy repo in Github? So that, I could test, debug, and report the case to the concerned framework.

**Comment by gkalpak** [comment]
FWIW, I can confirm that the `<time>` element is included in our list of known elements [here][1], so it is unexpected that Angular is throwing this error. @Martinspire, can you please provide a reproduction (as suggested by @MrJithil).

[1]: https://github.com/angular/angular/blob/d1ea1f4c7f3358b730b0d94e65b00bc28cae279c/packages/compiler/src/schema/dom_element_schema_registry.ts#L230

**Comment by vtsiris** [comment]
Hello everyone,

I have created a reproduction of this issue and you can find it [here](https://stackblitz.com/github/vtsiris/time_elements_throws_error).
It seems that this is not an Angular issue.

**Comment by gkalpak** [comment]
Thx, @vtsiris! Based on the reproduction, it seems that Angular does indeed recognize the built-in `<time>` element.
Since the issue seems to only be related to PhantomJS, which is not actively developed any more (see ariya/phantomjs#15344) and is not one of the browsers officially supported by Angular (see [Browser support][1]), I believe this issue can be closed.

##
@Martinspire, feel free to open a new issue (with a runnable reproduction) in case I've missed something and this is indeed an Angular issue.

[1]: https://next.angular.io/guide/browser-support
