### ISSUE TITLE
Add CSS class or ID to docs or non-docs pages for styling purposes

### ISSUE THREAD

**Issue by sjtrimble** [angular/angular#38417]
# 📚 Docs or angular.io bug report

### Description
Currently there are several styles that have to exclude the marketing pages individually in order to have docs-specific styling. There will be more of this implemented in the future.

Request to have a class or ID that is specific to docs or non-docs pages so that styling can be condensed.

Example: See lines 264 and 276 and 292 of https://github.com/angular/angular/blob/master/aio/src/styles/1-layouts/_marketing-layout.scss

**Comment by gkalpak** [comment]
This has mostly be addressed with the introduction of the [docs-pages()][1] and [marketing-pages()][2] Sass mixins.

[1]: https://github.com/angular/angular/blob/642362a9c7fa5f8c7eb7d47c243729f8e750dc8b/aio/src/styles/_mixins.scss#L120
[2]: https://github.com/angular/angular/blob/642362a9c7fa5f8c7eb7d47c243729f8e750dc8b/aio/src/styles/_mixins.scss#L174
