### ISSUE TITLE
CORS issue while playing video from digitalocean spaces in angular pwa app

### ISSUE THREAD

**Issue by yasar-salim** [angular/angular#38425]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/service-worker

### Description

 A clear and concise description of the problem...
I had a website (PWA created using angular) which serves video from digitalocean spaces previously it was amazon s3. 
 I have configured digitalocean for cors. 
The issue is only found in chrome browsers. 
When the page with video loads it shows the cors error. When i try hard refresh it gets played.
When i rename the ngsw.json file to some other the video plays perfectly. Thats why i came to the conclusion that the issue is with the pwa.

I will share the 2 use cases below,
1. The website with cors error - https://salesman-57e01.web.app/course/3 ( Hard refresh and video gets played)
2. The website with ngsw.json renamed - https://www.thesalesmanonline.com/course/3 (Video works perfectly)

## 🌍  Your Environment

**My package.json file:**
<pre><code>

{
  "name": "salesman",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.11",
    "@angular/common": "~9.1.11",
    "@angular/compiler": "~9.1.11",
    "@angular/core": "~9.1.11",
    "@angular/forms": "~9.1.11",
    "@angular/platform-browser": "~9.1.11",
    "@angular/platform-browser-dynamic": "~9.1.11",
    "@angular/router": "~9.1.11",
    "@angular/service-worker": "~9.1.11",
    "@ng-bootstrap/ng-bootstrap": "^5.3.1",
    "ngx-cookie-service": "^3.0.4",
    "ngx-plyr": "^4.0.0",
    "ngx-slick-carousel": "^0.5.1",
    "plyr": "^3.6.2",
    "rxjs": "~6.5.5",
    "slick-carousel": "^1.8.1",
    "tslib": "^1.10.0",
    "video.js": "^7.8.2",
    "videojs-youtube": "^2.6.1",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.9",
    "@angular/cli": "^9.1.9",
    "@angular/compiler-cli": "~9.1.11",
    "@angular/language-service": "~9.1.11",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.7.5"
  }
}

</code></pre>

A quick resolution is much appreciated other i will be in trouble with client

**Comment by yasar-salim** [comment]
@sonukapoor @gkalpak any workarounds?

**Comment by gkalpak** [comment]
I took some time to look into this, but I couldn't tell why this fails. Even when this is handled by the ServiceWorker, we just pass the request through to the network (via something like `event.responseWith(fetch(event.request))`). If the error is only happening on Chrome, maybe it is a Chrome bug (potentially related to the partial content response returned by the server?).

As a work-around, you can instruct the ServiceWorker to completely ignore a request by specifying an `ngsw-bypass` query param or header: [Bypassing the SW](https://angular.io/guide/service-worker-devops#bypassing-the-service-worker).

**Comment by yasar-salim** [comment]
@gkalpak can you provide a sample on this

**Comment by gkalpak** [comment]
@yasar-salim: I'm not sure what you mean. What kind of sample?

**Comment by petebacondarwin** [comment]
I think @yasar-salim wanted a sample to demonstrate how to instruct the ServiceWorker to ignore a request. Is that correct?
If you are using the `HttpClient` to make the request that is failing then you can just add `ngsw-bypass` as a header value to the request. Something like:

```ts
const headers = new HttpHeaders({'ngsw-bypass':  'true'})
this.http.get(url, {headers});
```

**Comment by gkalpak** [comment]
OP mentioned they are showing a video, so they are more likely using something like `<video src="url/to/video.ext"></video>` :grin:
In which case they can't change the request headers, but they can use the query param:

```diff
-<video src="url/to/video.ext">...</video>
+<video src="url/to/video.ext?ngsw-bypass">...</video>
```

**Comment by jelbourn** [comment]
Closing since this doesn't seem to be an Angular bug (potentially a Chrome bug?) and has a relatively simple workaround (specify the ngsw-bypass query param)
