### ISSUE TITLE
Allow loading indicator and error handling for resolver using Resolve<T>

### ISSUE THREAD

**Issue by Kayes-Islam** [angular/angular#38420]
# 🚀 feature request

### Relevant Package
@angular/router

### Description
A very common scenario is that the Resolve<T> resolver fetches data from the server before route is activated. There could be a delay or an error during the fetch. To handle these scenarios we would like to show the following based on outcome of Resolve<T>:

Delay: Show a loading indicator instead of the component that is activated within the router outlet.
Error: Show an error indicator. For example, user may navigate to the route "/products/1234". Resolver attempts to fetch the data from the server for product with ID 1234. Server returns 404. We'd like to show an error such as "Product with ID 1234 does not exist". 

### Describe the solution you'd like
Solution 1: 
If we could provide these templates as part of router-outlet that would be great:
```
<router-outlet>
    <ng-template #activating >
        <busy-indicator></busy-indicator>
    </ng-template>
    <ng-template #error let-error="error" >
        <div class="error">{{error}}</div>
    </ng-template>
</router-outlet>
```

Solution 2:
If Resolve<T> returns an Observable<T>, activate the route with the data pushed to the observable without requiring it to complete. Currently route is activated once the returned observable completes. If this behaved as suggested, we could then handle it in the resolver by returning a ResolveResult<T> with states such as loading, loaded, error etc.

### Describe alternatives you've considered
You can achieve similar result by hooking into router events. However, these events are global and I found it hard to filter events that relate to just the current route, not related to some child route in other branch of the route tree, or a child of a child route.

**Comment by atscott** [comment]
I believe the loading indicator is covered by #42489
The error page behavior seems like #42915 or just triggering a new navigation to an error page.
