### ISSUE TITLE
transformers: reimplement reflection data on top of tree-shakeable map

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#3842]
Assigning to @sigmundch to give us green light to being implementation.

**Comment by sigmundch** [comment]
Reassigning to @kegluneq as we are now ready to begin implementation on the transformers front. 

You can start using the [`LookupMap`][1] class right away by depending on the [`lookup_map` package][2]. All necessary features in dart2js have landed: initial support for tree-shaking `Type` keys is available in 1.13.0-dev.1.0, the full implementation with support for other const-keys will be available in the next dev release (1.13.0-dev.2.0). 


[1]: https://github.com/dart-lang/sdk/blob/master/pkg/lookup_map/lib/lookup_map.dart
[2]: https://pub.dartlang.org/packages/lookup_map

**Comment by sigmundch** [comment]
FYI - 1.13.0-dev.2.0 was released yesterday, so all of the dart2js support is now available on the dev channel.

**Comment by tbosch** [comment]
This is not needed any more, as #6270 will remove the reflector completely.
