### ISSUE TITLE
New localize extractor tool: incorrect source/target with plural forms

### ISSUE THREAD

**Issue by Chocobozzz** [angular/angular#38437]
# 🐞 bug report

### Affected Package

The issue seems to be caused by package @angular/localize

### Is this a regression?

No because it's a new tool, but yes because the old extractor worked.

### Description

When using the new extractor tool introduced in https://github.com/angular/angular/pull/32912 (`./node_modules/.bin/localize-extract`), it seems to create an XLIFF 1.2 file with invalid `source` when using plural in templates. For example with the following template:

```
<span i18n>Updated {minutes, plural, =0 {just now} =1 {one minute ago} other {{{minutes}} minutes ago}}</span>
```

It creates this element

```
<trans-unit id="5a134dee893586d02bffc9611056b9cadf9abfad" datatype="html">
  <source>{VAR_PLURAL, plural, =0 {just now} =1 {one minute ago} other {{INTERPOLATION} minutes ago}}</source>
  <context-group purpose="location">
    <context context-type="sourcefile">../app/app.component.html</context>
    <context context-type="linenumber">1</context>
  </context-group>
</trans-unit>
```

If we use the `source` as a `target`:

```
<trans-unit id="5a134dee893586d02bffc9611056b9cadf9abfad" datatype="html">
  <source>{VAR_PLURAL, plural, =0 {just now} =1 {one minute ago} other {{INTERPOLATION} minutes ago}}</source>
  <target>{VAR_PLURAL, plural, =0 {just now} =1 {one minute ago} other {{INTERPOLATION} minutes ago}}</target>
  <context-group purpose="location">
    <context context-type="sourcefile">../app/app.component.html</context>
    <context context-type="linenumber">1</context>
  </context-group>
</trans-unit>
```

Then we can't build the application:

```
Error: Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.)
Error: Invalid ICU message. Missing '}'.
```

## 🔬 Minimal Reproduction

https://github.com/Chocobozzz/angular-test

## 🔥 Exception or Error
<pre><code>Error: Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.)
Error: Invalid ICU message. Missing '}'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 10.1.0-next.4
Node: 12.18.3
OS: linux x64

Angular: 10.1.0-next.5
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.0-next.4
@angular-devkit/build-angular     0.1001.0-next.4
@angular-devkit/build-optimizer   0.1001.0-next.4
@angular-devkit/build-webpack     0.1001.0-next.4
@angular-devkit/core              10.1.0-next.4
@angular-devkit/schematics        10.1.0-next.4
@angular/cli                      10.1.0-next.4
@ngtools/webpack                  10.1.0-next.4
@schematics/angular               10.1.0-next.4
@schematics/update                0.1001.0-next.4
rxjs                              6.6.2
typescript                        3.9.7
webpack                           4.44.1
</code></pre>

**Anything else relevant?**

The issue seems to be `{INTERPOLATION}`

**Comment by petebacondarwin** [comment]
Should be fixed by https://github.com/angular/angular/pull/38484

**Comment by Chocobozzz** [comment]
I tested the latest angular release and it works. Thanks @petebacondarwin for your work on localization, that allowed us to reduce our build time by 10 with reduced localized bundle sizes.

**Comment by petebacondarwin** [comment]
Fantastic! Great to hear your build time improvements. Is that 10 times faster?

**Comment by Chocobozzz** [comment]
> Fantastic! Great to hear your build time improvements. Is that 10 times faster?

Yes, ~1h20 before and now ~8 minutes. Before your new extractor we used [18n-polyfill](https://github.com/ngx-translate/i18n-polyfill/) to translate our components, requiring to make 1 Angular build per language (because it `require` the translated XLIFF file of the current locale). Now we do only 1 build :) We also reduced our bundle sizes since we don't need to `require` XLIFF files anymore.

The only (small) issue we have now, is that we use new IDs for strings in components and old IDs for strings in templates. So translators could have to translate twice the same string (because they don't have the same ID, even if there have the same source). But it's not a big deal, we'll wait the migration tool to migrate to new IDs :)

**Comment by petebacondarwin** [comment]
You can turn off legacy message ids for your project, and then have new ids everywhere. 
In tsconfig set `enableLegacyMessageIds` to false.

**Comment by Chocobozzz** [comment]
Yes I now but we need to update existing IDs to new ID format first to not loose existing translations.

For example, if I regenerate `angular.xlf` using `./node_modules/.bin/localize-extract` with `enableLegacyMessageIds: false`, and then merge this file in existing translations (`angular.fr.xlf`), we'll loose translated strings that used legacy IDs because they don't exist anymore in `angular.xlf`.

**Comment by petebacondarwin** [comment]
Right! I have a plan to work on a migration tool for these purposes when we look at deprecating and removing the legacy ids.
