### ISSUE TITLE
Attribute binding is not working correctly when using optional chaining

### ISSUE THREAD

**Issue by xtephan** [angular/angular#38433]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/¯\_(ツ)_/¯

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ¯\_(ツ)_/¯

### Description

When trying to bind a proprietary like class and attribute, using an expression containing optional chaining, the evaluation result seems to be wrong. 

For example the following expression:
```
barStruct?.bar === null
```
when barStruct is `null`, should evaluate to `false`, since `barStruct?.bar` would be `undefined`.

Doing the same evaluation in the component logic, will return the expected result `false`

This has a bit more impact when trying to write more complex expressions with rxjs operator. For example:
```
[ngClass]="{ selected: foo.bar === (myObs | async)?.zoo }"
```
can produce unexpected results when the observable has not emitted or emitted a null value.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-rlhok1

Please check the stackblitz above.
The expected result would be that none of the boxes have the `red` class or `foo` attribute added.

## 🔥 Exception or Error
None

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.5
Node: 12.4.0
OS: darwin x64

Angular: 10.0.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.1000.5
@angular-devkit/build-angular              0.1000.5
@angular-devkit/build-ng-packagr           0.1000.5
@angular-devkit/build-optimizer            0.1000.5
@angular-devkit/build-webpack              0.1000.5
@angular-devkit/core                       10.0.5
@angular-devkit/schematics                 10.0.5
@angular/cdk                               10.1.3
@angular/cli                               10.0.5
@angular/flex-layout                       10.0.0-beta.32
@ngtools/webpack                           10.0.5
@nguniversal/common                        10.0.2
@nguniversal/express-engine                10.0.2
@nguniversal/module-map-ngfactory-loader   v8.2.6
@schematics/angular                        10.0.5
@schematics/update                         0.1000.5
ng-packagr                                 10.0.3
rxjs                                       6.6.2
typescript                                 3.9.7
webpack                                    4.43.0
</code></pre>

**Comment by JoostK** [comment]
This is working as expected, at the moment. The ECMAScript standard decided on using `undefined` in the optional chaining spec, whereas Angular's safe navigation operator (which predates the optional spec by a couple of years) uses `null`. There's #34385 for the proposal to change Angular's semantics to be aligned with the optional chaining spec, but this may require significant effort to overcome the breaking change it would be.
