### ISSUE TITLE
Angular CLI don't preserve whitespaces in JIT and AOT mode

### ISSUE THREAD

**Issue by belyan** [angular/angular#38459]
https://stackblitz.com/edit/angular-preserve-whitespaces?file=src/app/app.component.html

**Test Case**
```<p><span>1</span> <span>2</span> <span>3</span></p>```

**AR**
123

**ER**
1 2 3

Angular CLI: 9.0.0

**tsconfig.app.json**
```"angularCompilerOptions": { "preserveWhitespaces": true },```

**main.ts**
```platformBrowserDynamic().bootstrapModule(AppModule, { preserveWhitespaces: true }) .catch(err => console.log(err));```

**Comment by belyan** [comment]
After spending a few hours (hello to Angular Team) I have found this workaround:
https://stackblitz.com/edit/angular-preserve-whitespaces-fix?file=src%2Fapp%2Fapp.component.html

**Comment by belyan** [comment]
Related issue:
https://github.com/angular/angular/issues/35871

**Comment by mlc-mlapis** [comment]
**@belyan** Ivy enabled, and it works.

https://stackblitz.com/edit/angular-preserve-whitespaces-fix-czmybn?file=src%2Fapp%2Fapp.component.html

**Comment by belyan** [comment]
> **@belyan** Ivy enabled, and it works.
> 
> https://stackblitz.com/edit/angular-preserve-whitespaces-fix-czmybn?file=src%2Fapp%2Fapp.component.html

Actual Result (AR) should equal to ER (Expected Result).

**Comment by mlc-mlapis** [comment]
### **@**[**belyan**](https://github.com/belyan) 

Probably don't understand, what you mean. Don't understand why:

```
<p>123</p>
```

should be equal to:

```
<p>1 2 3</p>
```

**Comment by belyan** [comment]
@mlc-mlapis, I have updated my example of code, to make it more easy to understand. Please, take a look again:
https://stackblitz.com/edit/angular-preserve-whitespaces?file=src/app/app.component.html

**Comment by mlc-mlapis** [comment]
### [**@belyan**](https://github.com/belyan) 

Ah, OK, now it' more clear. I am not 100% sure, but I think that it's not a bug, but expected result (as designed), as I remember correctly.

**Comment by belyan** [comment]
I am going to check this defect in version 9.1.0, maybe (I hope) it was fixed at least in AOT mode.

**Comment by JoostK** [comment]
@belyan the JIT part has been fixed in #35534, indeed in 9.1.0.

I have to look into why it wouldn't work in AOT mode. The option provided to `bootstrapModule` will definitely not work in AOT (and never will be) but the compiler option should work.

**Comment by belyan** [comment]
@JoostK, thanks for the answer. I am going to check version 9.1.0 and if it is working as you described I will close this issue.

**Comment by kenaidri** [comment]
Thanks, no need

**Comment by belyan** [comment]
I have checked, the issue in AOT mode was fixed in 9.1.0. The issue in JIT mode does not reproduce if use option `preserveWhitespaces` in `bootstrapModule`.
