### ISSUE TITLE
Simple Docs for angular cli command | Routing

### ISSUE THREAD

**Issue by ChaitanyaBabar** [angular/angular#38461]
# 📚 Docs or angular.io bug report

### ✍️Description

Hi All,

The documentation for creating feature module with routing  [here](https://angular.io/guide/lazy-loading-ngmodules#create-a-feature-module-with-routing) with routing needs to be more simplified. 

## 🔬 Minimal Reproduction

![image](https://user-images.githubusercontent.com/6712223/90227421-28a73800-de32-11ea-82ef-944772ad214b.png)

As per above description the command auto generates following files

1. CustomersModule 
2. CustomersComponent.

Where as the command `ng generate module customers --route customers --module app.module` creates following files.

1. CustomersModule 
2. CustomersComponent
3. CustomersRoutingModule 

### What's the affected URL?**
✍️

Docs for creating feature module with routing  [here](https://angular.io/guide/lazy-loading-ngmodules#create-a-feature-module-with-routing)

### Reproduction Steps**

N/A

### Expected vs Actual Behavior**

The docs should be improved to clearly stating what is happening  as follows.

`ng generate module customers --route customers --module app.module`.

**Expected Behavior :-**

> The above command creates the following files.
> 
> 1. CustomersModule 
> 2. CustomersComponent
> 3. CustomersRoutingModule 
> 
> Once above files are created below configuration are auto-wired.
> 
> 1. The customers route, specified with the --route option, is added to the routes array inside the _app-routing.module.t_s file, using the lazy-loading syntax..
> 2. The blank route is added to the routes array inside the _customers-routing.module.ts_ file.

## 📷Screenshot

![image](https://user-images.githubusercontent.com/6712223/90227421-28a73800-de32-11ea-82ef-944772ad214b.png)

## 🔥 Exception or Error
N/A

## 🌍  Your Environment
N/A

### ✍️ Browser info
N/A

### ✍️ Anything else relevant?
N/A

**Comment by akashsolanki** [comment]
I've created [this](https://github.com/angular/angular/pull/38480) pull request for the issue.

**Comment by themindfulcoder** [comment]
#38480

**Comment by Yash2737** [comment]
Is this issue still available ? @themindfulcoder @akashsolanki , did you work on it?

**Comment by akashsolanki** [comment]
@Yash2737 This issue should be closed. See #38480.

**Comment by rahiyansafz** [comment]
it is not fixed yet!

**Comment by kirjs** [comment]
Seems like this issue can be closed after #38480
