### ISSUE TITLE
Mistake in [Hierarchical Injection] "@Host and viewProviders" section's logical tree representation"

### ISSUE THREAD

**Issue by jacobzhou1** [angular/angular#38471]
# Mistake in [Hierarchical Injection] "@Host and viewProviders" section's logical tree representation"

### Description

Following the hierarchical injection tree representation logic, the Injection of AnimalService need to be fixed. 

Below is the logical tree representation in "Hierarchical Injection" - "`@Host` and viewProviders" section:
![screenshot-1](https://user-images.githubusercontent.com/11903242/90287100-2c908580-de45-11ea-80d3-090ffbcd87e3.png)
There are 2 mistakes: 
(1) The root component's viewProviders shouldn't have `@SkipSelf` and `@Host`. These two modifiers aren't necessary and I guess they should only belong to the child component in this case. Although strickly speaking, in this case, the root component's injector will not change the result in child component. However, the real injector's value in root component should be 'null', instead of 🦔 . I think 'changing the value to null' or 'removing the `@SkipSelf` and `@Host` modifiers' both works.

(2) The child component's injector value should be 🦔, instead of 🐶. I think this also fits the conclusion of the document and the real test result.

So below is the expecting fix of current representation:
![screenshot-3](https://user-images.githubusercontent.com/11903242/90288223-6c586c80-de47-11ea-8e05-34e5e5379861.png)

I think logical tree representation is a good idea to represent the details of the injection process. I met the issue to understand the value in this one and I tested the value following the project structure to verify, so I guess this is an editing error.

If I have some misunderstandings for the document, looking forward to your correction. 

Thank you for your work and the constantly update!

## 🔬 Minimal Reproduction

https://angular.io/guide/hierarchical-dependency-injection#host-and-viewproviders

## 📷Screenshot
![screenshot-1](https://user-images.githubusercontent.com/11903242/90287100-2c908580-de45-11ea-80d3-090ffbcd87e3.png)

![screenshot-3](https://user-images.githubusercontent.com/11903242/90288223-6c586c80-de47-11ea-8e05-34e5e5379861.png)

![screenshot-2](https://user-images.githubusercontent.com/11903242/90287522-07e8dd80-de46-11ea-8aaf-7b4338e28cb0.png)

**Comment by aikidave** [comment]
Thanks for raising this issue, @jacobzhou1! And thank you especially for providing a solution! I've created a PR to address this issue!

**Comment by josmar-crwdstffng** [comment]
@jacobzhou1
Thank you for providing your feedback and a solution.
The changes are now live in the last code example in the following section.

https://angular.io/guide/hierarchical-dependency-injection#skipself-and-viewproviders
