### ISSUE TITLE
Need Two routing stack @angular/routing

### ISSUE THREAD

**Issue by Prabin1111** [angular/angular#38481]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/router

### Description
While working on angular project i am force to add AuthGuard in every Route
like bellow

const appRoutes: Routes = [
  { path: 'crisis-center', 
   component: CrisisListComponent,
    canActivate: [AuthGuard], },
  {
    path: 'heroes',
    canActivate: [AuthGuard],
    component: HeroListComponent,
  },
  { path: '',
    redirectTo: '/heroes',
    canActivate: [AuthGuard],
    pathMatch: 'full'
  },
  { path: '**', component: PageNotFoundComponent }
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})

### Describe the solution you'd like
i am tried to doing this it will better if we can add stack like 
One stack which need permission
Other stack which don't need permission

following is code for just concept
const checkPermission: Routes = [
  { path: 'demo1', 
   component: Component
 },
  {
    path: 'demo2',
    component: Component,
  },
  { path: '',
    redirectTo: '/demo3',
    pathMatch: 'full'
  },
];

const normalRoute: Routes = [
  { 
   path: 'demo4', 
   component: Component
 },
  { 
   path: 'demo5', 
   component: Component
 },
  { path: '**', component: PageNotFoundComponent }
];
@NgModule({
  imports: [RouterModule.forRoot(normalRoute, checkPermission)],
  exports: [RouterModule]
})

**Comment by jnizet** [comment]
You can already, by introducing an empty path route as the parent of the routes that need the guard, and by placing the guard on that parent route:

```
const appRoutes: Routes = [
  { 
    path: '', 
    canActivate: [AuthGuard],
    children: [
      { path: 'demo1', ... },
      { path: 'demo2', ... },
      { path: 'demo3', ... },
    ]
  },
  { path: 'demo4', ... },
  { path: 'demo5', ... }
];
```

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Prabin1111** [comment]
@jnizet  I am afraid that if i use this solution  then i will lose lazy loading for demo1 demo2 demo3
const appRoutes: Routes = [
  { 
    path: '', 
    canActivate: [AuthGuard],
    children: [
      { path: 'demo1', ... },
      { path: 'demo2', ... },
      { path: 'demo3', ... },
    ]
  },
  { path: 'demo4', ... },
  { path: 'demo5', ... }
];

**Comment by Prabin1111** [comment]
@atscott if you cannot give solution plz don't close it. May other have better solution then just closing it
