### ISSUE TITLE
Angular oidc client in unit test

### ISSUE THREAD

**Issue by natier** [angular/angular#38491]
I have an AuthentificationService service that calls OIDC client. I would like to test this service:

`export class AuthentificationService {
  private manager: UserManager;
  private user: User = null;

  constructor() {
      this.manager = new UserManager(getClientSettings());

      this.manager.getUser().then(user => {
        this.user = user;
      });
  }

  completeAuthentication(): Promise<void> {
    console.log(this.manager);
    return this.manager.signinRedirectCallback().then((user) => {
      console.log(user);
      this.user = user;
    }).catch((err) => {
      console.log(err);
 

   });
  }
}`

I want to test the completeAuthentication method but I can’t simulate the method. How to do it with a stub or mock?

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
