### ISSUE TITLE
ViewContainerRef createComponent() on an Overlay Portal fails. 

### ISSUE THREAD

**Issue by zehavibarak** [angular/angular#38497]
### Affected Package

The issue is caused by package @angular/core, @angular/cdk

## Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-mcndqk?file=src/app/first-component/first-component.component.ts

The above demonstrate a 2 components app, where the 1st creates the 2nd using factory and ViewContainerRef. 

When the 1st is embedded in the app as html is shows the 2nd as expected. 
When the 1st is then created using an Overlay and ComponentPortal - the 2nd is ignored.

Click the button to reproduce.

no exception is thrown.

## Environment

Angular Version: 10.0.9

**Comment by crisbeto** [comment]
This will be fixed in the CDK by https://github.com/angular/components/pull/20346.
