### ISSUE TITLE
Application crashing with angular version 10.0.10

### ISSUE THREAD

**Issue by fksik** [angular/angular#38518]
🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅

Hi

      My application got crashed with 17th aug release of 10.0.10. Even I could not able to extract performance profile or memory snapshot. On downgrading to angular 10.0.9 fixed the issue. 

🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅

# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/*

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 10.09

### Description

 My application got crashed with 17th aug release of 10.0.10. Even I could not able to extract performance profile or memory snapshot. On downgrading to angular 10.0.9 fixed the issue. With some techniques i found that some of the apis requests are in pending state forever. 

## 🌍  Your Environment

**Angular Version:**
<pre><code>
10.0.10
</code></pre>

**Comment by sonukapoor** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by JoostK** [comment]
For the record, I think this is due to #38510.
