### ISSUE TITLE
unpkg not serving up zone.js@0.11.0

### ISSUE THREAD

**Issue by anothermarkus** [angular/angular#38517]
Super easy repro steps:

Navigate: https://unpkg.com/zone.js@0.11.0

Zone.js is no longer served up, our site is now broken.

Thanks!

**Comment by JounQin** [comment]
There is nothing inside the package:

https://unpkg.com/browse/zone.js@0.11.0/

![image](https://user-images.githubusercontent.com/8336744/90596203-0beb7580-e221-11ea-8104-62784c170baa.png)

**Comment by JiaLiPassion** [comment]
The content of the npm package is not right, will update the release tomorrow.

**Comment by splincode** [comment]
https://github.com/angular/angular/issues/38526

**Comment by daledale** [comment]
This is causing downtime on our live application, do we have an ETA on this. Or alternativly a temporary work around?

**Comment by muuvmuuv** [comment]
@daledale downgrade to previous version?

**Comment by daledale** [comment]
@muuvmuuv, Ah sorry I undertsand what's going on now, we where just refrencing `https://unpkg.com/zone.js` so when the new release got created it automaticly started trying to use that. We can easily change to  `https://unpkg.com/zone.js@0.10.3/dist/zone.js`

**Comment by JiaLiPassion** [comment]
Sorry for the inconvenience, and thank you @daledale for the walk around, will update the package asap.

**Comment by sonukapoor** [comment]
Closed via #38528

**Comment by mhevery** [comment]
[release: cut the zone.js-0.11.1 release by mhevery · Pull Request #38537 · angular/angular](https://github.com/angular/angular/pull/38537) is on its way.

**Comment by anothermarkus** [comment]
When does CDN get updated, I'm still getting not found for zone.js v 0.11.0?

https://unpkg.com/zone.js@0.11.0

**Comment by petebacondarwin** [comment]
Try https://unpkg.com/zone.js@0.11.1 :-)

**Comment by anothermarkus** [comment]
How dare you.  I can't believe the inconvenience you all have caused me for a few hours, when you did all the work, hosted this all for free on CDN, and I referenced your hyperlink for my whizbang site.  

Just kidding, much appreciation to all you guys for the fast turn around!

**Comment by petebacondarwin** [comment]
@anothermarkus - I know this must have been a stressful event for you. Sorry that you got stung by this error.

I'm glad that you are back up and running - and that you have managed to keep your sense of humour!

We are currently doing a postmortem to see what we can do to prevent a similar problem in the future.

**Comment by mgechev** [comment]
At Google, we have a [postmortem culture](https://landing.google.com/sre/sre-book/chapters/postmortem-culture/), which helps us to learn from mistakes. Following this philosophy, we'd want to share what went wrong and what steps we're going to take to make sure this does not happen in the future.

You can find the postmortem document associated with this incident [here](https://docs.google.com/document/d/1ZGT7afiMa0IPjAPIDF_v6Rc3UE-DxxLsOEEPlqKM8_o/preview).
