### ISSUE TITLE
zone.js: zone lost inside requireJS (AMD) module

### ISSUE THREAD

**Issue by mblout** [angular/angular#38516]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/packages/zone.js

### Is this a regression?
Yes, worked in 0.9.1

### Description
When loading modules using requireJS, the zone is lost.

## 🔬 Minimal Reproduction
The following <body> in index.html, which should also include zone.js
<pre><code>
  <script src="zone.js"></script>
  <script src="../node_modules/requirejs/require.js"></script>
  <script>
  function testOne () {
    Zone.current.fork({name:'one-zone'})
      .run(() => new Promise((resolve) => {
        // load one.js
        requirejs(['one'], (one) => {
          one();
          resolve(one);
        });
      }));
  }

  // bootstrap
  Zone.current.fork({ name: 'main' }).run(testOne);
  </script>
</body>`
</code></pre>

the entire contents of one.js, in the same folder of index.html
<pre><code>
console.log('outside module "one" : ' + window.Zone.current.name); 
define(() => {
    console.log('module "one": ' + window.Zone.current.name); 
    return () => {
        console.log('module "one" function: ' + window.Zone.current.name); 
    }
});
</code></pre>

In 0.10.X, all three console.logs report the name of the zone as the `<root>`, and not my `one-zone`.

With 0.9.1, I see the following:
```
outside module "one" : <root>
module "one": one-zone
module "one" function: one-zone
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
angular: 10.1.0-next.6
zone.js: 0.10.3
requirejs: 2.3.6
</code></pre>

**Comment by JiaLiPassion** [comment]
The content of the npm package is not right, will update the release tomorrow.

**Comment by JoostK** [comment]
@JiaLiPassion I don't think this is related to the NPM package being corrupt, as this was reported before 0.11.0 was released and the issue description mentions it occurs in 0.10.3.

**Comment by JiaLiPassion** [comment]
@JoostK, yes you are right, I will check the issue again.

**Comment by mhevery** [comment]
[release: cut the zone.js-0.11.1 release by mhevery · Pull Request #38537 · angular/angular](https://github.com/angular/angular/pull/38537) is on its way.

**Comment by JiaLiPassion** [comment]
I put wrong issue number to associate with this issue, reopen it to do more investigation.

**Comment by JiaLiPassion** [comment]
@mblout , I tried the code with zone.js `0.10.3` and `0.11.2` the result is the same with `0.9.1`, all output 

```
outside module "one" : <root>
module "one": one-zone
module "one" function: one-zone
```

could you check it again?

**Comment by mblout** [comment]
thanks for checking; yes, I see what you see; 
i can't explain why i saw different behavior with the same test before, other than ...I goofed somehow? I'll close (and re-open iff needed).
