### ISSUE TITLE
Alert in built-in directives guide seems to be placed irrelevant

### ISSUE THREAD

**Issue by bampakoa** [angular/angular#38525]
# 📚 Docs or angular.io bug report

### Description

 It seems that the alert about the use of access on public and private APIs from built-in directives is not related in the `NgFor` section. If it is, something that is not clear to me, maybe the content should be modified to convey a more clear meaning.

### What's the affected URL?**
 https://angular.io/guide/built-in-directives#ngfor

## 📷Screenshot

![image](https://user-images.githubusercontent.com/7170892/90608586-81e4e200-e20b-11ea-98f0-2dc7318cd3ba.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by petebacondarwin** [comment]
It is a valid statement, but I agree that perhaps its position makes it look particularly associated with the ngFor directive rather than Angular's common directives in general.

@kapunahelewong / @aikidave - thoughts?

**Comment by kapunahelewong** [comment]
Should we maybe put it in the intro to the document? If I understand, it applies to all types of built-in directives, right?

**Comment by petebacondarwin** [comment]
Yes it applies to all the built-ins. I guess the point is that even though they are built-in they could have been built by 3rd parties.
