### ISSUE TITLE
Cannot find module 'zone.js/dist/zone.js' after upgrade to zone.js 0.11.0

### ISSUE THREAD

**Issue by splincode** [angular/angular#38526]
# 🐞 bug report

### Affected Package

The issue is caused by package zone.js

### Is this a regression?

Yes

### Description

https://github.com/thymikee/jest-preset-angular/issues/445

```text
FAIL  file-size.pipe.spec.ts
  ● Test suite failed to run

    Cannot find module 'zone.js/dist/zone.js' from '../../../../../node_modules/jest-preset-angular/build/setupJest.js'

    Require stack:
      /node_modules/jest-preset-angular/build/setupJest.js
      /node_modules/jest-preset-angular/index.js
      src/stubs/setupJest.ts

      at Resolver.resolveModule (../../../../../node_modules/jest-resolve/build/index.js:307:11)
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Yarn 1.26
Angular 9
Jest 26
jest-preset-angular 8
</code></pre>

After install zone.js I am open node_modules

![image](https://user-images.githubusercontent.com/12021443/90609340-91185f80-e20c-11ea-8e23-418502df0143.png)

![image](https://user-images.githubusercontent.com/12021443/90609478-c2912b00-e20c-11ea-90c9-28f5e57a2d4c.png)

Where `dist/zone.js`?

**Comment by eran10** [comment]
same issue here

**Comment by pimmesz** [comment]
Same here

**Comment by muuvmuuv** [comment]
Nice, no package files :D 

![Bildschirmfoto 2020-08-19 um 11 24 10](https://user-images.githubusercontent.com/11534760/90617053-8232ac80-e20e-11ea-9aad-58b4588980bd.png)

**Comment by ngohungphuc** [comment]
Same issue. I have to revert back to "zone.js": "~0.10.3"

**Comment by damiencal** [comment]
Same here.
How can such regressions still occur ? 
For sure this one would have been caught by automated tests..

**Comment by mlc-mlapis** [comment]
You can have hundreds of tests and you can be sure that there are always other 5 hidden mistakes, you are not aware of.

**Comment by JiaLiPassion** [comment]
Sorry for the inconvenience, will update the npm package very soon.

**Comment by AliMD** [comment]
This issue proves that angular is not a enterprise ready solution!

**Comment by muuvmuuv** [comment]
It is... Idk how your production deployments look like but I can think of no developer that has NEVER break something on releases. Things happen and you can never test everything. Besides that this issue did not break any production pipeline unless you have used `zone.js: "*"` in your `package.json` and even if you should have build tests before every deployment. 🤦🏼

**Comment by mhevery** [comment]
[release: cut the zone.js-0.11.1 release by mhevery · Pull Request #38537 · angular/angular](https://github.com/angular/angular/pull/38537) is on its way.

**Comment by crfrolik** [comment]
I am seeing a peer dependency warning when using the latest zone.js with the latest angular
```
warning " > @angular/core@10.0.12" has incorrect peer dependency "zone.js@~0.10.3".
```

**Comment by mgechev** [comment]
At Google, we have a [postmortem culture](https://landing.google.com/sre/sre-book/chapters/postmortem-culture/), which helps us to learn from mistakes. Following this philosophy, we'd want to share what went wrong and what steps we're going to take to make sure this does not happen in the future.

You can find the postmortem document associated with this incident [here](https://docs.google.com/document/d/1ZGT7afiMa0IPjAPIDF_v6Rc3UE-DxxLsOEEPlqKM8_o/preview).
