### ISSUE TITLE
DI - Service resolves as undefined when inject metadata with @Inject decorator

### ISSUE THREAD

**Issue by hsntngr** [angular/angular#38532]
# 🐞 bug report

### Affected Package
`@angular/core`

### Is this a regression?
Only tried with angular 7

### Description

When I inject a metadata into a service, if I use `@Inject` decorator not injector instead, angular resolves the service as undefined. I'm able to resolve metada and service individually, but if I try to inject metada inside of the service problem occurs. 

[question on stackoverflow](https://stackoverflow.com/questions/63481712/angular-7-service-returns-undefined-when-has-metadata-dependency)

## 🔬 Minimal Reproduction
live example on stackblitz

https://stackblitz.com/edit/angular-buwetk

Issues that don't have enough info and can't be reproduced will be closed.

You can read more about issue submission guidelines here: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue
-->

## 🔥 Exception or Error

Angular 10 throws below error instead of undefined

```
preview-8079e088a5819580c54db.js:1 ERROR TypeError: Cannot read property 'ɵprov' of undefined
    at getInjectableDef (defs.ts:196)
    at resolveNgModuleDep (ng_module.ts:113)
    at NgModuleRef_.get (refs.ts:420)
    at injectInjectorOnly (injector_compatibility.ts:97)
    at ɵɵinject (injector_compatibility.ts:116)
    at injectArgs (injector_compatibility.ts:215)
    at eval (util.ts:55)
    at _callFactory (ng_module.ts:200)
    at _createProviderInstance (ng_module.ts:153)
    at resolveNgModuleDep (ng_module.ts:125)
```

## 🌍  Your Environment

```
Angular CLI: 10.0.5
Node: 14.7.0
OS: linux x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1000.5
@angular-devkit/core         10.0.5
@angular-devkit/schematics   10.0.5
@schematics/angular          10.0.5
@schematics/update           0.1000.5
rxjs                         6.5.5


"dependencies": {
    ....
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
```

**Comment by JoostK** [comment]
The issue here is a circular dependency from `app.module.ts` -> `app.component.ts` -> `user.service.ts` -> `app.module.ts`, which StackBlitz unfortunately does not warn you about (the CLI can report a warning here).

This is actually working since Angular 9 with Ivy, although I'd recommend avoiding circular dependencies whenever possible. In this case, the easiest way is to pull out `AUTH_USER` into a separate file, as that allows for breaking the chain.

Since this is no longer an issue in latest Angular, I'll close this issue.

**Comment by hsntngr** [comment]
@JoostK in angular 7 I import the injection token completely different file but still doesn't work.
