### ISSUE TITLE
Demo specs missing in testing-services guide

### ISSUE THREAD

**Issue by doenn** [angular/angular#38535]
The demo specs such as app/demo/demo.spec.ts in this guide https://angular.io/guide/testing-services are missing from the sample app https://angular.io/generated/live-examples/testing/stackblitz.html. The guide says services are often the easiest to unit test, but a new person getting started will have difficulty guessing what exactly is being imported and how someone can implement their own service tests.

The sample app is necessary because otherwise it is not obvious what ValueService even is and if getValue() is a library function or defined within ValueService.

**Steps to Reproduce:**
1. Visit https://angular.io/guide/testing-services.
2. Visit first link https://angular.io/generated/live-examples/testing/stackblitz.html.
3. Try to find sample specs.

**Expected Results:**
Sample specs are in demo, showing imports.

**Actual Results:**
Sample specs are not found in demo.

![demo_specs_missing](https://user-images.githubusercontent.com/3093577/90661943-c7a6a800-e215-11ea-9eb8-02d1b8dd1971.JPG)

**Comment by juhas96** [comment]
Hey I want to contribute on this issue.
