### ISSUE TITLE
Child component references

### ISSUE THREAD

**Issue by mlynch** [angular/angular#3853]
One common use case that is emerging from Ionic 2 usage is accessing child components from a parent component. `Query` and `ViewQuery` exist, but I don't believe they are intuitive enough for how common this operation is turning out to be.

As an example, take this Gallery component that has an image carousel inside of it. The Gallery wants to control this carousel. It might push new images or remove old ones from it over the lifetime of the Gallery component.

```javascript
@Component({
  selector: 'gallery'
})
@View({
  template: '<div><h1>Gallery</h1><carousel></carousel></div>`
})
export class Gallery {
  constructor() {
  }
  loadNewSlides() {
    // Load from imgur
    // Push new images to the carousel 
  }
}
```

To do this today, I can query for the Carousel:

```javascript
constructor(@ViewQuery(Carousel) carousels : QueryList<Carousel>) {
  carousels.onChange(() => {
  });
}
```

However, this is not a natural GUI-style way to access and interact with children, especially when I specify the exact set of child components (most commonly, just one). What would be more natural is to tag a child with a ref (like we have with internal view variables using `#`) and expose that to the component:

```javascript
template: '<div><h1>Gallery</h1><carousel  #myCarousel></carousel>'
```

Then, I can access this carousel directly in my `Gallery` component:

```javascript
constructor() {
}
onInit() {
  this.myCarousel.addSlide()
}
```

Some questions that have come up that would need to be addressed for this to work properly:

 * How does this work with sets of components (for example, those created with `ng-for`)? One option is to make the tagging take an interpolated value and use an attribute: `ref="button-{{button.id}}"`. In that case, perhaps child references can be accessed through an abstraction where the reference id is just a key in a object (`this.refs.blah`)

 * What are the semantics of component destruction and the ref system? I think just nullifying the reference would be sufficient, along with emitting an event: `this.myCarousel.on('destroy')` though that event support would have to be added to a wrapper class or to the component internals.

 * What is the syntax for tagging child components? We have `#variable` for view-internal references, maybe that system could be expanded to allow the parent to access those as well? Or, supply an attribute like react does with `ref`.

It's worth noting that React has a nice `ref` system for just this purpose. The docs on it go into greater detail on why parent -> child direct access is valuable: https://facebook.github.io/react/docs/more-about-refs.html. Here are some thoughts about the dynamic children problem: http://www.mattzabriskie.com/blog/react-referencing-dynamic-children

**Comment by PascalPrecht** [comment]
I like that `@Query` and `@ViewQuery` allow us to access children without knowing what the template actually looks like. Having a reference to any local template variable is surely a nice and convenient way to get hold of element instance, however, that also means that the component has to know what identifier is used in the template.

In addition to that, as soon as you change a name of a local variable, your component code won't work anymore (unless you change it too). I like your idea, but I do think we should somehow try to keep things as decoupled as possible.

**Comment by mlynch** [comment]
That's a great point I didn't think of. I think there's a natural separation between "user components" and "library components": essentially, the user writes these controller-style components and interact with black-box library components.

This is squarely in the user component space. How can we make it easier and more natural than Query?

**Comment by PascalPrecht** [comment]
Tbh I really don't know how to make that easier without introducing a coupling between component and view.

An option would be to introduce a new decorator `@ViewQueryLocal` which is specifically meant to be used to query local template variables. However, this doesn't really bring any additional value except that you can see, just by looking at your component's code, that it relies on template vars which could help a little bit when refactoring things.

@mhevery any thoughts on this?

**Comment by mhevery** [comment]
@vsavkin / @rkirov can you comment here with the latest thinking?

**Comment by rkirov** [comment]
@mlynch Thanks for the detailed issue! Take a look at our https://github.com/angular/angular/issues/3922 proposal. Moving the query out of the injectables and removing the array indirection for singular cases will make it a lot more natural:

```javascript
@Component({
  selector: 'gallery'
})
@View({
  template: '<div><h1>Gallery</h1><carousel></carousel></div>'
})
export class Gallery {
  @ViewChild(Carousel)
  carousel: Carousel;

  loadNewSlides() {
    // work with this.carousel here as long as this is called on afterViewInit
  }
}
```

About the finer point you bring up:
- we already support querying for var bindings, see - https://github.com/angular/angular/blob/master/modules/angular2/test/core/compiler/query_integration_spec.ts#L515. But as Pascal said, there are benefits for querying for directive types.
- var bindings don't have to be unique in a template. So if you have ```<div *ng-for="...." var-foo>``` , you can just ask for `@ViewChildren('foo')` and work with the `ObservableArray`. 
- putting all interesting child objects into a `this.ref` grabbag Object would be unfortunate for TS users, because you will lose the type information for what type `this.ref.foo` is.

Destruction of singular objects can be implemented using a custom setter. Or you can `upgrade` to the unboxed `ObservableArray` using @ContentChildren and listen on the changes.

**Comment by mlynch** [comment]
This seems like a nice improvement! :+1:

I think renaming the Query types is also a good idea. I'd add that I think end-users are going to find the subtleties of View/Content space challenging, but I'm not really sure what can be done at this point to simplify it since it's core concept of v2.

**Comment by mhevery** [comment]
Closing due to https://github.com/angular/angular/issues/3922
