### ISSUE TITLE
AOT 进行打包无法获取location.host值？？？

### ISSUE THREAD

**Issue by nzjcnjzx** [angular/angular#38530]
export const MQTT_SERVICE_OPTIONS = {
  url: `ws://${location.hostname}:${location.port}/mqtt`
};

 MqttModule.forRoot(MQTT_SERVICE_OPTIONS)

正常进行打包编译，能获取到对应的参数
当使用AOT的模式进行编译，无法获取到location属性，显示为null，该如何处理？？

望指教，非常感谢！

**Comment by sonukapoor** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
