### ISSUE TITLE
formGroup reset does not reset the property valid

### ISSUE THREAD

**Issue by LuizGGeas** [angular/angular#38538]
when resetting formgroup after submission, it does not change the valid element of the form

**Comment by sonukapoor** [comment]
@LuizGGeas I just tried this out with a simple `FormGroup` and a `FormControl` and it seems to work as expected. You can see a stackblitz here:

https://stackblitz.com/edit/angular-ivy-tuawdc?file=src%2Fapp%2Fapp.component.html

If you have a different reproducible, can you please share it?

**Comment by AndrewKushnir** [comment]
Closing this ticket since there is no repro, so we can not perform further investigation. Feel free to create a new ticket once repro is available. Thank you.
