### ISSUE TITLE
Localized bundle generation failed: Unexpected return value from helper (expected a call expression)

### ISSUE THREAD

**Issue by bobKasbi** [angular/angular#38544]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/localize

### Is this a regression?
the previous version in which this bug was not present was: Angular 8.x

### Description

After upgrading the app to angular 9 and then 10 when I run <code>ng build appName --configuration=production</code> localy it works. But the issue accoures on the gitLab pipeline

## 🔥 Exception or Error
<pre><code>
Localized bundle generation failed: Unexpected return value from helper (expected a call expression)

</code></pre>

**Angular Version:**
<pre><code>
Angular CLI: 10.0.6
Node: 12.14.1
OS: darwin x64

Angular: 10.0.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: <error>

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.15
@angular-devkit/build-angular      0.1000.6
@angular-devkit/build-optimizer    0.1000.6
@angular-devkit/build-webpack      0.1000.6
@angular-devkit/core               10.0.6
@angular-devkit/schematics         10.0.6
@angular/cdk                       8.2.3
@angular/cli                       10.0.6
@angular/flex-layout               9.0.0-beta.29
@angular/http                      7.2.16
@angular/material                  8.2.3
@angular/material-moment-adapter   8.2.3
@ngtools/webpack                   10.0.6
@schematics/angular                8.3.29
@schematics/update                 0.1000.6
rxjs                               6.6.2
typescript                         3.9.7
webpack 
</code></pre>

**Anything else relevant?**
import in pollyfills.ts:<code>
 /* Load `$localize` onto the global scope - used if i18n tags appear in Angular templates.*/
import '@angular/localize/init';</code> and package.json: <code>"@angular/localize": "^10.0.10",</code>
But in other hand, I' am still not using <code>$localize</code> in typescript and in HTML to implement the new i18n translation. I still keep the previous implementation for i18n translation. Using </code>$localize</code> will be the next step after getting rid of the this issue/error.

**Comment by petebacondarwin** [comment]
This error is thrown when the translation merging is trying to unwrap a "lazy load" template object helper call from ES5 code. For example:

```ts
function _templateObject() {
  var e = _taggedTemplateLiteral(['a', 'b', 'c'], ['a', 'b', 'c']);
  return _templateObject = function() { return e }, e
}
$localize(_templateObject(), 1, 2);
```

In this case the `_templateObject()` is the "lazy load" helper, and the code tries to unwrap the `_taggedTemplateLiteral(['a', 'b', 'c'], ['a', 'b', 'c'])` call.

In your case, it seems that this line:

```
var e = _taggedTemplateLiteral(['a', 'b', 'c'], ['a', 'b', 'c']);
```

is of the form:

```
var e = xxx;
```

where `xxx` is not a call expression.

---

To be able to diagnose this further, we would need a reproduction.

Note that the Angular compiler generates `$localize` calls internally from `i18n` attributes in the component templates.

**Comment by bobKasbi** [comment]
Sorry, what kind of reproduction is exactly meant here?

**Comment by petebacondarwin** [comment]
Sorry I wasn't clear. I would need something to look at that reproduces the error. I don't think that a StackBlitz would be enough, since it doesn't run the translation inlining. Perhaps a minimal CLI project uploaded to github?

**Comment by bobKasbi** [comment]
I'll check how fare I can provide such reproduction even if I think it would be dificult. The app is really too large and advanced. I'll see how to provide a smiple example.

**Comment by petebacondarwin** [comment]
Alternatively, if you could build the application with localization turned off, (I think by setting `"localize": false` in the angular.json and then running `ng build`). This should generate some distributable files (e.g. `main.es5.js`) that you could look inside to find the `$localize` calls. If you were able to send me some examples of the kind of calls that are being generated that might help.

Also, if you did manage to generate these distributables you could try running the `localize-translate` binary directly on the files, which you could even debug into and maybe get some more information about the shape of the code that is causing the problem.

**Comment by bobKasbi** [comment]
There is no main.es5.js generated. I do get just a file: <code>main.js</code>, but there I don't find any <code>$localize</code>. It existst just in <code>pollyfillys-es5.js.map</code> and here is some part:
</code>typeof $localize !== "undefined" && $localize.locale
   * ```
   *
   * with a string literal of the current locale. E.g.
   *
   * ```
   * "fr"
   * ```
   */
  locale?: string;
}

export interface TranslateFn {
  (messageParts: TemplateStringsArray,
   expressions: readonly any[]): [TemplateStringsArray, readonly any[]];
}

/**
 * Tag a template literal string for localization.
 *
 * For example:
 *
 * ```ts
 * $localize `some string to localize`
 * ```
 *
 * **Providing meaning, description and id**
 *
 * You can optionally specify one or more of `meaning`, `description` and `id` for a localized
 * string by pre-pending it with a colon delimited block of the form:
 *
 * ```ts
 * $localize`:meaning|description@@id:source message text`;
 *
 * </code>

**Comment by petebacondarwin** [comment]
Can you post your `angular.json` and `tsconfig.app.json` files?

Did you change your `angular.json` to turn off localization?

```jsonc
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "localize": false, // To prevent the CLI from doing inlining itself
```

**Comment by bobKasbi** [comment]
Yes, I did:

<code>"builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/my-app",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "node_modules/font-awesome/scss/font-awesome.scss",
              "src/assets/scss/main.scss"
            ],
            "scripts": [],
            "localize": false
          },</code>

**Comment by petebacondarwin** [comment]
It is better to use triple backticks (```) to render code blocks in these comments.

The code in `vendor.js` that you mentioned is just the Angular JIT compiler code (from `@angular/compile`).

Are you using `i18n` attributes in any of your templates?

Are there any other references to `$localize` in the `vendor.js` file? Perhaps there is a library that contains internlationalization messages?

**Comment by bobKasbi** [comment]
Yes, I'am using i18in in all HTML/view templates. Yes, there some more in <code>vendor.js</code>. I'll check

**Comment by petebacondarwin** [comment]
If you are using `i18n` attributes then there should definitely be some `$localize` calls in your `main.js`. What command are you using to create the build?

**Comment by bobKasbi** [comment]
in <code>vendor.js</code>:
```if (typeof ngI18nClosureMode !== "undefined" && ngI18nClosureMode) {
  var MSG_EXTERNAL_PasswordMatTooltipRules$$FESM2015_SL_FORM_ELEMENTS_JS_2 = goog.getMsg("Ihr Passwort muss mindestens 8 Zeichen lang sein und muss mindestens einen Gro\xDFbuchstaben, einen Kleinbuchstaben, ein Sonderzeichen und eine Ziffer enthalten!");
  I18N_1 = MSG_EXTERNAL_PasswordMatTooltipRules$$FESM2015_SL_FORM_ELEMENTS_JS_2;
} else {
  I18N_1 = $localize(_templateObject());
}```

**Comment by petebacondarwin** [comment]
OK, so that is indeed a "lazy load" helper. Can you look up and find the definition of `_templateObject()`?

**Comment by bobKasbi** [comment]
here is it: 
```
function _templateObject() {
  var data = Object(_Users_myName_FOLDER_my_app_node_modules_babel_runtime_helpers_esm_taggedTemplateLiteral__WEBPACK_IMPORTED_MODULE_2__["default"])([":@@PasswordMatTooltipRules\u241F0df3b2d900e498a78bb783070d0c23656fa1df1f\u241F7757858069437389817:Ihr Passwort muss mindestens 8 Zeichen......more text!"]);

  _templateObject = function _templateObject() {
    return data;
  };

  return data;
}
```

**Comment by petebacondarwin** [comment]
OK, great. Let me take a look at that. I wonder why these are in vendor.js rather than main.js??

**Comment by petebacondarwin** [comment]
Is `Ihr Passwort muss mindestens 8 Zeichen...` a message that you have in your application components or is it from a library?

**Comment by petebacondarwin** [comment]
Hmm, OK, so the form that you have shown here can be handled by our tooling - I just checked locally. So I don't understand why you are getting this error.

Can you try doing:

```
node node_modules/.bin/localize-translate -r dist -s *.js -o tmp -t <path/to/a/translation/file>
```

**Comment by petebacondarwin** [comment]
Another thing you could try is just building the TS files without bundling...

```
node node_modules/.bin/ngc -p tsconfig.app.json
```

Then have a look in `out-tsc/app` and see if the `.js` files have any `$localize` calls in them.

**Comment by petebacondarwin** [comment]
Can I ask how you build these private libraries? Do you use ng-packagr or something else?

**Comment by bobKasbi** [comment]
I'll give it a try, it I think should be: <code>node node_modules/.bin/ngc -p src/tsconfig.app.json</code>

**Comment by bobKasbi** [comment]
> Can I ask how you build these private libraries? Do you use ng-packagr or something else?

Sure. I do use: <code>ng build nameOfLib</code> as I do have more projects in the lib <code>projects/nameOfLib/src/lib</code>

**Comment by bobKasbi** [comment]
I see now. Your hint regarding removing some libraries to localize the issue did help. I do have a library which is still using an older version in <code>preDependencies</code> in the specific <code>package.json</code> (not the main one in the root) than the one where I do embed it. But when trying to upgrade the <code>preDependencies</code> (manually) in/for the library, it doesn't work. It  keeps the older one. So, how can we force upgrading the <code>preDependencies</code> for specific library? Any idea.

**Comment by petebacondarwin** [comment]
What are `preDepedencies`? Do you mean `peerDependencies`?

**Comment by bobKasbi** [comment]
Yes, Sorry!

**Comment by petebacondarwin** [comment]
I would say that you must update those `peerDependencies` directly. The Angular framework peer dependencies should update themselves automatically when using `ng update @angular/core` since it contains information about how to do that. But if you have a library that has a `peerDependency`, it would be up to you to do the update manually.

**Comment by bobKasbi** [comment]
This is what I did exactly. Manually updating the specific version of <code>peerDependencies</code> in the specific <code>package.json</code>. The main <code>package.json</code> file has been updated automtically running <code>ng update @angular/core @angular/cli</code>. Any way, I also found out, that it's even not an issue with library version or it <code>peerDependencies</code>. In the library I did have a hard coded tanslatbale text with <code>i18nKindOfID</code> for an attribute. When I did remove it, it did work using <code>"optimization": "true"</code> in <code>angular.json</code> file. I don't know exactly the reason behind it, but removing it, id did remove the error.
This was the text you mentioned in the beginning: <code>Ihr Passwort muss mindestens...</code>.
I apologize for too much noise. But Your hints did help me to localize the issue. I'll take care of the rest. Many Thanks!
Please feel free to close the bug/Issue. THANKS!

**Comment by petebacondarwin** [comment]
Glad you got to the bottom of it!! Thanks for working with me on this.
