### ISSUE TITLE
Support TypeScript 4.x

### ISSUE THREAD

**Issue by splincode** [angular/angular#38547]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/*

### Description

After upgrade to TypeScript 4.0.2

```ts
$ ngcc

Error: Error on worker #1: TypeError: ts.updateIdentifier is not a function
    at Object.generateSetClassMetadataCall
error Command failed with exit code 1.
```

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/pull/38076
