### ISSUE TITLE
Missing documentation on localization scripts

### ISSUE THREAD

**Issue by ArtemAvramenko** [angular/angular#38545]
# 📚 Docs or angular.io bug report

### Description

I have a mixed AngularJS/Angular application. To build it I use webpack, AngularCompilerPlugin and `localize-translate` script. The problem is `xlf` extracting . I have no angular.json config, so I cannot use `ng xi18n`. To use `i18nOutFile` option I have to disable Ivy temporary. This is not convenient and I think it stops working with some Ivy-specific features in templates. The documentation does not have any guide for that case.

### What's the affected URL?**
 https://angular.io/guide/i18n

**Comment by petebacondarwin** [comment]
Try using `localize-extract` instead. It is the extraction version of `localize-translate` which you are already using.

**Comment by petebacondarwin** [comment]
Closing since `localize-extract` has been available for some time now.
