### ISSUE TITLE
[FR] New default input property binding style

### ISSUE THREAD

**Issue by KingMario** [angular/angular#38556]
# 🚀 feature request

### Description

Could you please add a `[prop.propertyA]="boundVariable"` style data binding for `@Input() propertyA = initialValue;` in a component. When the value `boundVariable` is `undefined`, the `propertyA` will be set to the `initialValue`.

```html
<my-component [prop.propertyA]="boundVariable"></my-component>
```

As in `[attr.id] = "uniqId"` for simple HTML elements, if the value of `uniqId` is `underfined`, no id will be set for the element.

```html
<div [attr.id]="uniqId">
  blahblahlbah
</id>
```

-- thanks for @abraham 's comment. added to clarify:
While you bind id like this [id]="uniqId", if the value of uniquId is undefined, the id will be assigned a string "undefined".

### Describe alternatives you've considered

To implement it in a component, the property should be impleme nted as setter/getter pair:

```typescript
  private _propertyA = initialValue; // initialValue is a const declared somewhere
  @Input() set propertyA(value) {
    if (value === undefined) {
      this._propertyA = initialValue;
    } else {
      this._propertyA = value;
    }
  }

  get propertyA() {
    return this._propertyA;
  }
```

-- thanks for @abraham 's and @petebacondarwin 's comments. added to clarify:
If you don't have control over the component you may conditionally bind the property like this without having to dive in to know the default-value of the property:

```
<component *ngIf="boundVariable !== undefined" [propertyA]="boundVariable"></component>
<component *ngIf="boundVariable === undefined"></component>
```

If the new feature is provided, a `[prop.propertyA]="boundVariable"` style data binding will save the works.

**Comment by Nosfistis** [comment]
Defaults might not be known in all cases, and if used in a library, the defaults might change over time as intended behavior, but will cost a lot to refactor. For example, if the property is assigned dynamically with a switch case that defaults to undefined, the developer has to know the author's default value.

This is counter-intuitive with what a default value should be.

**Comment by pkozlowski-opensource** [comment]
O believe that users today can validate / transform incoming input values in the `OnChanges` lifecycle hook like so: 

```typescript
export class TestComponent implements OnChanges {
  @Input()
  value: string;

  ngOnChanges(changes: SimpleChanges) {    
    if (changes.value?.currentValue === undefined) {
      this.value = 'The default';
    }
  }
}
```

I'm not sure if the new syntax and the increased conceptual surface of the framework justifies this new feature request.

**Comment by pkozlowski-opensource** [comment]
Just to summarise the feature request: the way I understand it is about ability to set an input field to a "default" value (generally speaking - to an arbitrary value) when an input is not provided _or_ the input's binding value is `undefined`. 

Somehow we could think of it as default argument values in JavaScript (ex. `function foo(arg1 = devalutValExp) {}`) but for class fields. Sadly, there is no such mechanism for class fields in JavaScript, but Angular provides at least 2 ways of solving this problem:
* setter, as already [pointed out](https://github.com/angular/angular/issues/38556#issue-684102148) by the author of the issue;
* `ngOnChanges` hook, as [described above](https://github.com/angular/angular/issues/38556#issuecomment-881463373)

Given that no equivalent mechanism exists in JavaScript and there are already 2 ways of achieving the requested behaviour in Angular we believe that additional complexity of this new feature (more concepts, more syntax, more code to maintain) doesn't pass our "cost / benefit" assessment. We've discussed this feature request internally in the team and decided not to implement it for the time being.
