### ISSUE TITLE
`RangeError: Maximum call stack size exceeded` in `@angular/animations` module

### ISSUE THREAD

**Issue by th0r** [angular/angular#38551]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/animations

### Is this a regression?

 Not sure

### Description

We sometimes see `RangeError: Maximum call stack size exceeded` error in our production environment. Some of them come from Safari, some from Chrome. I'm attaching a few last frames of the stacktrace (see the section below). I think this is the reason for the issue: https://anchortagdev.com/range-error-maximum-call-stack-size-exceeded-error-using-spread-operator-in-node-js-javascript. Looks like it happens when page contains a lot of DOM elements and code tries to push them all into an array using a spread operator.

## 🔬 Minimal Reproduction

Sorry, I don't know how to reproduce it.

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/302213/90875862-6e23b200-e3aa-11ea-9b46-16de1cd13164.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.1.5
Node: 12.16.1
OS: darwin x64

Angular: 9.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router, upgrade
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.5
@angular-devkit/build-angular     0.901.5
@angular-devkit/build-optimizer   0.901.5
@angular-devkit/build-webpack     0.901.5
@angular-devkit/core              7.3.10
@angular-devkit/schematics        7.3.10
@angular/cdk                      9.2.3
@angular/cli                      9.1.5
@ngtools/webpack                  9.1.5
@schematics/angular               9.1.5
@schematics/update                0.901.5
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.43.0
</code></pre>

**Comment by th0r** [comment]
Any feedback folks?

**Comment by AleksanderBodurri** [comment]
This issue got me really curious so I did some benchmarking with https://jsbench.me

https://jsbench.me/jvkf8ynmgg/1

Each test creates 1000 divs before the test case runs and assigns the result to a variable. 

1. `nodeList` kept as a `NodeList`
<img width="1114" alt="Screen Shot 2020-09-18 at 9 07 20 PM" src="https://user-images.githubusercontent.com/39253660/93655783-9a574080-f9f3-11ea-88db-284edb458125.png">

2. `nodeList` converted into an `Array` (This one is unrelated to this issue but I thought it was interesting)

<img width="1119" alt="Screen Shot 2020-09-18 at 9 08 13 PM" src="https://user-images.githubusercontent.com/39253660/93655784-9cb99a80-f9f3-11ea-87d4-bea56ca40819.png">


Relevant code
https://github.com/angular/angular/blob/a91f0f6b82f340cfde5a01bc328d2723dc4248f0/packages/animations/browser/src/render/shared.ts#L183-L194

 Maybe changing 

```ts
     results.push(...element.querySelectorAll(selector)); 
```

to 

```ts
    const elements = element.querySelectorAll(selector);
    for (let i = 0, l = elements.length; i < l; i++) {
       results.push(elements[i]);
    }
```

might resolve this issue and potentially offer a performance increase.

**Comment by jelbourn** [comment]
While we can't reproduce this issue, it looks like the function @AleksanderBodurri mentions could be simplified anyway to something like this:
```typescript
_query = (element: any, selector: string, multi: boolean): any[] => {
    if (multi) {
        return Array.from(element.querySelectorAll(selector));
    } else {
      const elm = element.querySelector(selector);
      return elm ? [elm] : [];  
    }
  };
```
Feel free to send a PR
