### ISSUE TITLE
Cannot use url matcher along with outlet in router confiuation

### ISSUE THREAD

**Issue by agalazis** [angular/angular#38558]
You cannot use 
```
   {
        matcher: myAwesomeMatcher,
        outlet: 'myAwesomeOutlet',
       component:  MyAwesomeComponent
   }
```

the configuration seems to be entirely disregarded see reproduction for more details:

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-router-basic-example-x5yxss?file=app%2Fapp.routing.module.ts

## 🔥 Exception or Error
 No exception or error thrown. I would expect the correct typings and a compiler error if  I cannot have the combination for some reason.

## 🌍  Your Environment
```
>yarn ng version
yarn run v1.22.4
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.5
Node: 12.16.3
OS: linux x64

Angular: 9.1.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.5
@angular-devkit/build-angular      0.901.5
@angular-devkit/build-ng-packagr   0.901.5
@angular-devkit/build-optimizer    0.901.5
@angular-devkit/core               9.1.5
@angular-devkit/schematics         9.1.5
@angular/cli                       9.1.5
@schematics/angular                9.1.5
@schematics/update                 0.901.5
ng-packagr                         9.1.3
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.43.0
    
Done in 0.91s.
```

**Comment by agalazis** [comment]
I think that router also needs both better typings and runtime error handling as well eg I am allowed to leave path parameter out(typings issue) but even then instead of seeing a meaningful runtime exception thrown I get  `Cannot read property 'split' of undefined` (Could be `invalid route: matcher or path required`)

**Comment by wooliesx-apirillo** [comment]
Could this be triaged into an upcoming release? I am also dealing with this exact issue and a solution would be much appreciated.

**Comment by chriscarpenter12** [comment]
2023 and I just came across this to trying to restrict loading of a sidebar in a named route outlet

**Comment by atscott** [comment]
This is working as expected actually. The outlet doesn’t appear in the URL so the router doesn’t attempt to match any configs for the outlet. 

The only segments that would ever be passed to the matcher in this case would be an empty list so the only thing that can match is an empty path route. 

I think you instead want something more like:

`{path: ‘’, outlet: ‘myAwesomeOutlet’, canMatch: [someGuard], component: X}`
