### ISSUE TITLE
gRPC client

### ISSUE THREAD

**Issue by alvipeo** [angular/angular#38566]
I need a gRPC communication in my angular app. Is there anything already built-in or planned? Sorry, never used it with angular and I don't see it mentioned anywhere in the docs.

**Comment by petebacondarwin** [comment]
There is no gRPC provided in by the Angular team. A quick Google search brings up https://github.com/ngx-grpc/ngx-grpc, which is probably what you are after (or at least a starting point). Closing as this is either deemed a support request, or a feature request that we will not support.

**Comment by alvipeo** [comment]
In a year there will be more and more gRPC use, I think you should consider it.
Anyway, thanks.
