### ISSUE TITLE
BUG: ɵɵnextContext in template does not return *latest* context/component instance

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#38562]
# 🐞 bug report

### Affected Package

`@angular/core`

### Is this a regression?

Dont know, never tried this before IVY.

### Description

I have *table* which renders *detail* rows. When you click on any row, new *detail* row should be added to the table.

Component works correctly if you refresh page or navigate to it after refresh. Then click on any row and new *detail* row is added to the table. But if you are already on page and navigates to other page, or logout and then return to page, *detail* row after click is not displayed.

After debugging i found out, that problem is that `ɵɵnextContext` does not return correct instance of component. Returned context does not contains latest changes from component, even though that code that makes these changes is called before call of `ɵɵnextContext`.

## 🔬 Minimal Reproduction

- `git clone https://github.com/kukjevov/ng-universal-demo.git`
- `cd ng-universal-demo`
- `git checkout nextContext/1.0`
- `npm install`
- `npm start`
- open browser at `http://localhost:8888`
- log in using *admin* *admin* credentials
- click on any row and see detail row is displayed
- click on *logout*
- log in using *admin* *admin* credentials
- click on any row and see detail is **not** displayed
- refresh page
- click on any row and see detail row is displayed

Here is part of template that should be added https://github.com/kukjevov/ng-universal-demo/blob/nextContext/1.0/app/modules/gridExtensions/components/plugins/contentRenderer/detailTable/advancedDetailTableBodyContentRenderer.component.html#L15 , but condition is never met since context does not contains correct data. And here is code that changes data https://github.com/kukjevov/ng-universal-demo/blob/nextContext/1.0/app/modules/gridExtensions/components/plugins/contentRenderer/detailTable/advancedDetailTableBodyContentRenderer.component.ts#L115 .

## 🔥 Exception or Error
No error.

## 🌍  Your Environment

**Angular Version:** *10.0.11*
**Node Version:** *10.19.0*
**NPM Version:** *6.9.0*
**Windows Version:** *10.0.19041 Build 19041*

**Comment by kukjevov** [comment]
@AndrewKushnir anything new here ? :)

**Comment by JoostK** [comment]
A heap dump clearly shows what is going on here:

<img width="1718" alt="Screenshot 2020-10-24 at 22 54 30" src="https://user-images.githubusercontent.com/123679/97093414-03ae1d00-164c-11eb-9836-17acc4d0a242.png">

The original instance (1365551) is retained through a bound function, as you're writing it into the global default option object:

https://github.com/kukjevov/ng-universal-demo/blob/49a01bae1b47ce8471369a502b34749c50232e57/app/modules/gridExtensions/components/plugins/contentRenderer/detailTable/advancedDetailTableBodyContentRenderer.component.ts#L81

Closing as not an Angular bug.

**Comment by kukjevov** [comment]
@JoostK Ouch, thanks a lot, what a stupid mistake.

I can see it now :). 

Have a nice day a and one more thx.
