### ISSUE TITLE
Kyrgyzstani som in CurrencyPipe by default

### ISSUE THREAD

**Issue by oneclickwebstudio** [angular/angular#38568]
Hello! I'd like to ask you to add `KGS` currency code to your CyrencyPipe with symbol    ![image](https://user-images.githubusercontent.com/5783161/91122031-0c6d8b80-e6bb-11ea-9833-9a042eb0e76f.png)

[Resource]( https://en.wikipedia.org/wiki/Kyrgyzstani_som)

# 🚀 feature request

### Relevant Package
@angular/common/common.d.ts

### Describe the solution you'd like

`{{1000 | currency: 'KGS': 'symbol'}}`

output should be

`1000,00 `![image](https://user-images.githubusercontent.com/5783161/91122031-0c6d8b80-e6bb-11ea-9833-9a042eb0e76f.png)

**Comment by petebacondarwin** [comment]
Unfortunately, we cannot make this change in the Angular project. All our locale data is extracted from the CLDR project automatically. I see in that project that there is the following data:

```
          "KGS": {
            "displayName": "Кыргызстан сому",
            "displayName-count-one": "Кыргызстан сому",
            "displayName-count-other": "Кыргызстан сому",
            "symbol": "сом"
          },
```

This implies to me that the symbol being used is `сом` and not the character you request.

If you wish this to change it would need to be by getting CLDR to update their data. You can start by looking in their bug tracker here https://unicode-org.atlassian.net/secure/Dashboard.jspa

Closing as this cannot be rectified here.
