### ISSUE TITLE
feat(compiler): Support "in" operator in Angular templates

### ISSUE THREAD

**Issue by manueledones** [angular/angular#38560]
# 🚀 feature request

### Description
I'd like to have your opinions about supporting "in" operator in html templates. Let's say I have an object of a union type A | B. I'd like to use the 'in' operator to differentiate type.
Something like: 

```
export interface A {
  a: number
}

export interface B {
  b: string
}

export type MyUnionType = A | B;

item: MyUnionType = {
    a: 1
  }

<div *ngIf="'a' in item">
  I'm expecting item is no longer of type A | B, but only A
  {{item.a}}
</div>
```

Here is a [stackblitz](https://stackblitz.com/edit/ngifin?file=src/app/app.component.html)

**Comment by alxhub** [comment]
In this spirit of aligning Angular expression syntax with JS expression syntax, I'm moving this into our triage process for further discussion.

**Comment by petebacondarwin** [comment]
This is being tracked in the aggregate issue of #43485 for which we need to create a project proposal.

**Comment by alxhub** [comment]
^ closing as we're discussing these improvements to template expression syntax holistically, along the theme of unifying Angular syntax with JS.
