### ISSUE TITLE
Router docs is showing class as interfaces

### ISSUE THREAD

**Issue by dev054** [angular/angular#38563]
# 📚 Docs or angular.io bug report

### Description
Most (if not all) classes in `@angular/router` docs are being shown up as _interfaces_.

### What's the affected URL?**
See https://angular.io/api/router/ActivatedRoute per example:

![Captura de Tela 2020-08-24 às 12 38 19](https://user-images.githubusercontent.com/28629080/91065354-bccd8800-e606-11ea-9fc6-620c36fffdf6.png)

**Comment by petebacondarwin** [comment]
So if I remember correctly, this is because the class's `constructor` is marked as `@internal`. Any class in the framework that is not supposed to be instantiated by application developers is rendered as as an interface.

**Comment by petebacondarwin** [comment]
Closing as "works as expected".
