### ISSUE TITLE
Why this error when communication Angular with Backend throw REST service?

### ISSUE THREAD

**Issue by ergys7is** [angular/angular#38579]
I am running an application (front end is Angular ver 8), backend is Java Spring Boot. The server where the application will run is Windows Server 2019. In my pc the application is running without problems (on serve, not build), but on server, I am trying to serve the application, before build, but an error is occurred the moment fe is trying to communicate be - [HPM] Error occurred while trying to proxy request / from localhost:3701 to http://localhost:3700 ... etc.

from package.json -
 "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy-conf.json --host 0.0.0.0 --port 3701",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  }

and from proxy-config.json - 
{
  "/api": {
    "target": "http://localhost:3700",
    "secure": "false"
  }
}

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
