### ISSUE TITLE
useFactory in @Injectable doesn't work using object's shorthand method definition

### ISSUE THREAD

**Issue by tonivj5** [angular/angular#38578]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: I don't know

### Description

`useFactory` doesn't work when I use it like this:
```ts
@Injectable({
  providedIn: 'root',
  useFactory() {
    console.log('this useFactory should be called, but... nope :`(')

    return {}
  },
})
class TestService {
  constructor() {
    console.log('this constructor should not be called!!! but it's');
  }
}
```

Using an arrow function, an anonymous function or an exported function work (see repro).
But using an arrow function `angular language service` complains... it works at runtime and building, but it's annoying
![image](https://user-images.githubusercontent.com/7110786/91208654-cc35f980-e70a-11ea-95e1-8d79329f906c.png)

## 🔬 Minimal Reproduction

this repro uses `9.1.1`, but it doesn't work with latest (`10.0.12`) either

https://ng-run.com/edit/zwh0lwIk3NYX9tKWSUMt

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 10.0.7
Node: 14.6.0
OS: linux x64

Angular: 10.0.12
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.4
@angular-devkit/build-angular     0.1000.7
@angular-devkit/build-optimizer   0.1000.7
@angular-devkit/build-webpack     0.1000.7
@angular-devkit/core              10.0.4
@angular-devkit/schematics        10.0.7
@angular/cdk                      10.1.3
@angular/cli                      10.0.7
@ngtools/webpack                  10.0.7
@schematics/angular               10.0.7
@schematics/update                0.1000.7
rxjs                              6.6.2
typescript                        3.9.7
webpack                           4.43.0

</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
Labeled for language-service as it's still using the ViewEngine format, which still has this limitation. Preparing the LS to fully work the Ivy way is being worked on!

**Comment by tonivj5** [comment]
@JoostK using `useFactory` as an object method is not working as you can see opening the console in https://ng-run.com/edit/zwh0lwIk3NYX9tKWSUMt

The language service is other inconvenient...

**Comment by JoostK** [comment]
@tonivj5 Oh, sorry, I misread "Using an arrow function, an anonymous function or an exported function work (see repro)." to refer to the method syntax.

**Comment by tonivj5** [comment]
No problem, thanks for confirm! :smile:

**Comment by djleonskennedy** [comment]
Useless functionality, can be removed

**Comment by JeanMeche** [comment]
This works now !
