### ISSUE TITLE
localize-extract does not write 'original' attribute

### ISSUE THREAD

**Issue by ArtemAvramenko** [angular/angular#38570]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/localize^10.1.0-next.7

### Is this a regression?

Yes, the `View Engine` extraction via `AngularCompilerPlugin` write xlf attribute as:
``` xlf
<file source-language="en" datatype="plaintext" original="ng2.template">
```

### Description

I call `localize-extract` and get xlf file without `original` attribute:
``` xml
  ...
  <file source-language="en" datatype="plaintext">
  ...
````
My CAT tool (OmegaT) cannot open this file.

## 🌍  Your Environment

**Angular Version:**
```
10.1.0-next.7
```

**Comment by petebacondarwin** [comment]
I'm really sorry, I didn't realise that `original` is a required property of `<file>`. I will remedy that today.
