### ISSUE TITLE
Angular 9 custom module not loading specific component (Can't bind to 'ngIf' since it isn't a known property of 'ng-container'.)

### ISSUE THREAD

**Issue by lahirudilshan** [angular/angular#38586]
### Problem scenario

The issue is in my custom-created module, I imported a component and that component uses a service, then I **ng serve** that component not rendering and give a warning in the console as **Can't bind to 'ngIf' since it isn't a known property of 'ng-container'** and if I remove that service from that component it renders and works fine..but if I add that service into the component it does not render and doesn't show....but I already use that service in other components and it works fine.

# 🐞 bug report

### Affected Package
<code><pre>
{
    "name": "orelbuy-web",
    "version": "0.0.0",
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e",
        "build-prod": "node --max_old_space_size=8048 ./node_modules/@angular/cli/bin/ng build --aot --prod",
        "serve-prod": "node --max_old_space_size=8048 ./node_modules/@angular/cli/bin/ng serve --aot --prod"
    },
    "private": true,
    "dependencies": {
        "@agm/core": "^1.1.0",
        "@angular/animations": "^9.1.11",
        "@angular/cdk": "^10.0.1",
        "@angular/common": "~9.1.11",
        "@angular/compiler": "~9.1.11",
        "@angular/core": "~9.1.11",
        "@angular/fire": "^6.0.2",
        "@angular/forms": "~9.1.11",
        "@angular/localize": "~9.1.11",
        "@angular/material": "^9.2.4",
        "@angular/platform-browser": "~9.1.11",
        "@angular/platform-browser-dynamic": "~9.1.11",
        "@angular/router": "~9.1.11",
        "@ng-bootstrap/ng-bootstrap": "^6.1.0",
        "angularfire2": "^5.4.2",
        "bootstrap": "^4.5.0",
        "crypto-js": "^4.0.0",
        "firebase": "^7.15.5",
        "firebase-functions": "^3.7.0",
        "jquery": "^3.5.1",
        "moment": "^2.27.0",
        "ngx-infinite-scroll": "^9.0.0",
        "ngx-pagination": "^5.0.0",
        "ngx-slick-carousel": "^0.5.1",
        "rxjs": "~6.5.4",
        "slick-carousel": "^1.8.1",
        "tslib": "^1.10.0",
        "underscore": "^1.10.2",
        "zone.js": "~0.10.2"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "~0.901.9",
        "@angular/cli": "~9.1.9",
        "@angular/compiler-cli": "~9.1.11",
        "@types/googlemaps": "^3.39.8",
        "@types/jasmine": "~3.5.0",
        "@types/jasminewd2": "~2.0.3",
        "@types/jquery": "^3.5.0",
        "@types/node": "^12.11.1",
        "@types/underscore": "^1.10.14",
        "codelyzer": "^5.1.2",
        "jasmine-core": "~3.5.0",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~5.0.0",
        "karma-chrome-launcher": "~3.1.0",
        "karma-coverage-istanbul-reporter": "~2.1.0",
        "karma-jasmine": "~3.0.1",
        "karma-jasmine-html-reporter": "^1.4.2",
        "protractor": "~7.0.0",
        "ts-node": "~8.3.0",
        "tslint": "~6.1.0",
        "typescript": "~3.8.3"
    },
    "browser": {
        "crypto": false
    }
}
</code></pre>
### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

The issue is in my custom-created module, I imported a component and that component uses a service, then I **ng serve** that component not rendering and give a warning in the console as **Can't bind to 'ngIf' since it isn't a known property of 'ng-container'** and if I remove that service from that component it renders and works fine..but if I add that service into the component it does not render and doesn't show....but I already use that service in other components and it works fine.

## 🔥 Exception or Error
<pre><code>

</code></pre>
![image](https://user-images.githubusercontent.com/30127504/91285425-d1e31c00-e7aa-11ea-91b0-18bbb09356d6.png)

Subcomponent already declare in module
![image](https://user-images.githubusercontent.com/30127504/91285695-2be3e180-e7ab-11ea-89ae-8b52a87cf2b2.png)
If i remove authentication service component load fine
![image](https://user-images.githubusercontent.com/30127504/91285903-6483bb00-e7ab-11ea-833f-ba53fceb00c9.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "orelbuy-web": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/orelbuy-web",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": true,
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "node_modules/slick-carousel/slick/slick.scss",
              "node_modules/slick-carousel/slick/slick-theme.scss",
              "src/scss/styles.scss"
            ],
            "scripts": [
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/slick-carousel/slick/slick.min.js",
              "src/js/navigation.js"
            ],
            "showCircularDependencies": false
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "10kb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "orelbuy-web:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "orelbuy-web:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "orelbuy-web:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json",
              "e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "orelbuy-web:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "orelbuy-web:serve:production"
            }
          }
        }
      }
    }
  },
  "defaultProject": "orelbuy-web",
  "cli": {
    "analytics": false
  }
}
</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment]
Hi @lahirudilshan,

Could you please provide a minimum repro (using [Stackblitz](https://stackblitz.com/) or in a form of GitHub repo), so we can perform additional investigation?

I also noticed that you are using 9.1.11 version of Angular packages. Please try upgrading to the most recent version (10.0.12 at this moment) to see if the problem still exists and/or the error message is the same.

Thank you.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
