### ISSUE TITLE
DebugElement.componentInstance returning the wrong component

### ISSUE THREAD

**Issue by bibhas2** [angular/angular#38591]
# 🐞 bug report

### Affected Package
N/A

### Is this a regression?

N/A

### Description

``DebugElement.componentInstance`` is returning the wrong component.

## 🔬 Minimal Reproduction

Create a new app.

```
ng new test-app --defaults
```

Create two components.

```
ng g c pet-list
ng g c pet-display
```

In ``src/app/pet-list/pet-list.component.html`` use pet display component.

```xml
<app-pet-display></app-pet-display>
```

In ``src/app/app.component.html`` use pet list component.

```xml
<app-pet-list></app-pet-list>
```

In ``src/app/pet-list/pet-list.component.spec.ts`` add a test spec.

```javascript
it('Should lookup child', () => {
  let pd = fixture.debugElement.query(By.css("app-pet-display"))
  
  expect(pd.componentInstance.constructor.name).toBe("PetDisplayComponent")
})
```

Run test.

```
npm test
```

The test case above fails:

```
Expected 'PetListComponent' to be 'PetDisplayComponent'.
```

## 🔥 Exception or Error
N/A

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.7
Node: 10.14.2
OS: darwin x64

Angular: 10.0.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.7
@angular-devkit/build-angular     0.1000.7
@angular-devkit/build-optimizer   0.1000.7
@angular-devkit/build-webpack     0.1000.7
@angular-devkit/core              10.0.7
@angular-devkit/schematics        10.0.7
@angular/cli                      10.0.7
@ngtools/webpack                  10.0.7
@schematics/angular               10.0.7
@schematics/update                0.1000.7
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Anything else relevant?**

**Comment by jnizet** [comment]
I can't reproduce. Your test passes fine here. I initially suspected you forgot to add the PetDisplayComponent to the declarations of you test module (i.e. inside `configureTestingModule`), but if I do that, I have (as expected) a compilation error: `ERROR: ''app-pet-display' is not a known element`.

You should provide a complete reproduction, as a github project that we can clone and execute.

**Comment by bibhas2** [comment]
Thank you for checking this so quickly. I have created a repo to show the problem:

https://github.com/bibhas2/test-app

After cloning the repo, just do:

```
npm install

npm test
```

You should see the failed test case like this.

![image](https://user-images.githubusercontent.com/1730356/91331189-7445d400-e798-11ea-8888-488c1614a5e1.png)

**Comment by jnizet** [comment]
OK, so it's exactly as I suspected. Read the error messages in your terminal. It says:

```
ERROR: ''app-pet-display' is not a known element:
1. If 'app-pet-display' is an Angular component, then verify that it is part of this module.
2. If 'app-pet-display' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this 
```

And you get that error because you haven't added PetDisplayComponent to the `declarations` of your testing module, inside `configureTestingModule`. So, as the eror message explains, Angular doesn't know what the `<app-pet-display>` element is: it's not a standard HTML element, and it's not, inside this test, known as an angular component either.

**Comment by dannyskoog** [comment]
As @jnizet pointed out - try adding the `PetDisplayComponent` to the declarations array in the spec file, since currently your just rendering a non-Angular HTML element (called `pet-display`)

**Comment by bibhas2** [comment]
Ah, yes. That was my mistake. Adding ``PetDisplayComponent`` to declarations fixed the issue.

```javascript
beforeEach(async(() => {
  TestBed.configureTestingModule({
    declarations: [ 
      PetDisplayComponent,
      PetListComponent ]
  })
  .compileComponents();
}));
```
