### ISSUE TITLE
AOT complier

### ISSUE THREAD

**Issue by yating00000** [angular/angular#38593]
# 📚 Docs or angular.io bug report

### Description

 
Hi, I saw the below paragraph on your website mentioning that AOT Complier doesn't support arrow functions:
&nbsp;
<img width="600" alt="截圖 2020-08-26 下午9 11 24" src="https://user-images.githubusercontent.com/26374265/91312014-51daa780-e7e6-11ea-8a2d-b9f9b28f4bd6.png">

However, in LazyModule of Angular10:
```ts
{
   path: 'pages',
   loadChildren: () =>
      import('./pages/pages.module').then((m) => m.PagesModule),
},
```

### Expected vs Actual Behavior**

That means AOT complier doesn't apply under the Decorator situation only.
Therefore, could you please help to update the description of that paragraph?

**Comment by petebacondarwin** [comment]
I believe that this does not apply to the new Ivy AOT compiler. So the documentation is out of date and needs to be updated.

**Comment by AndrewKushnir** [comment]
Hi, as @petebacondarwin mentioned, the AOT guide needs to be updated in a context of Ivy compiler. There is a ticket to track that (see #38381) so I'll close this one as a duplicate. Thank you.
