### ISSUE TITLE
[Feature request] Router : load lazy load modules only after checking guards/resolvers

### ISSUE THREAD

**Issue by geromegrignon** [angular/angular#38607]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/router

### Description

When accessing a route dedicated to a lazy loaded module, the bundle is loaded just after NavigationStart but before checking guards and resolving the Resolvers. It means the bundle is still loaded even if it doesn't pass the guard or the data can't be resolved.

As the point of lazy loading is to load a bundle only when a user access it through a route for web performance purposes, it shouldn't be loaded if the route is somehow inaccessible.

### Describe the solution you'd like

Would it be possible to move the loading of the bundle later on inside `setupNavigations()` ?

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by KostyaTretyak** [comment]
How is the feature described here different from [CanLoad](https://angular.io/api/router/CanLoad) feature?

**Comment by geromegrignon** [comment]
Using CanLoad on a route with a Resolver would mean to resolve the data twice and might impact performance : 
- once checking if data is available with CanLoad
- once to store the data when resolve occurs
