### ISSUE TITLE
angular naming 'service' bug

### ISSUE THREAD

**Issue by edsulaiman** [angular/angular#38606]
# 🐞 bug report

### Affected Package
I don't know, I think it's a bug caused by the Angular compiler

### Is this a regression?

 Yes, the previous version in which this bug was not present was:  Angular 9

### Description

in angular 9, I use the naming of ````service```` for some modules (````service.module.ts```` and ````service-routing.module.ts````), and use it as a lazy load module, when I run ````ng serve```` there is no problem, After I updated to Angular 10, the application I created did not respond, when I changed the name ````service```` to ````services```` the problem was resolved, but when I used ````routerLink```` it pointed to ````/service````, my application did not respond again, after I changed it to ````/services````, the problem is resolved.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.7
Node: 12.18.3
OS: win32 x64

Angular: 10.0.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.7
@angular-devkit/build-angular     0.1000.7
@angular-devkit/build-optimizer   0.1000.7
@angular-devkit/build-webpack     0.1000.7
@angular-devkit/core              10.0.7
@angular-devkit/schematics        10.0.7
@angular/cli                      10.0.7
@ngtools/webpack                  10.0.7
@schematics/angular               10.0.7
@schematics/update                0.1000.7
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0

</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
@edsulaiman - please could you provide a reproduction of this issue so that we could debug what is going on?
I wonder if your upgrade got corrupted somehow? It might be worth cleaning out `node_modules` and reinstalling everything.

**Comment by edsulaiman** [comment]
so I have created a new project and moved all the code in my old project to my new project, and all the problems have disappeared, maybe the problem is in the upgrade process that I did, thanks

**Comment by petebacondarwin** [comment]
Glad to hear it!
