### ISSUE TITLE
router for angular1: no lifecycle hooks (yet)?

### ISSUE THREAD

**Issue by acalvo** [angular/angular#3860]
I've been trying the new version of the router for AngularJS 1.x and could make it work in the most simple scenario (single outlet and a few links to navigate), but couldn't use features such as canActivate and the other lifecycle hooks as they are being ignored (not executed at all). Is this a known bug, or am I missing something? I was quite surprised about this not working since it did back when the code was located in the other repo (angular/router).

BTW, if you could share your current timing plans around the new router (for angular1) it'd be extremely useful :)

**Comment by btford** [comment]
You should be able to implement `Cmp.canActivate = ...` and have it work. You can take a look at the angular1_router specs to see it in action.

There's still a lot of work across the codebase. The best way to keep up is to check issues tagged with `component: router`. If you have specific bugs/problems, filing issues is the best way to influence what gets worked on next. :)

**Comment by btford** [comment]
You can also follow #3813, which specifically tracks progress on 1.x the router

**Comment by acalvo** [comment]
Digging in the code, I just realized that it's `$canActivate` now (with the $ symbol, I mean), isn't it? And it's executed before the Controller is instantiated. And `activate` is now `onActivate`, this is why neither of them were working for me!

So, just in case someone else gets to this issue having the same problem, this would be the way of defining lifecycle hooks right now (at least in angular1):

	function UserListController () {
		this.onActivate = function() {
		};
		this.canDeactivate = function() {
			return true;
		};
		this.onDeactivate = function() {
		};
	}
	
	UserListController.$canActivate = function() {
		return true;
	}

Hope it helps. Thanks for your answer, Brian! :)
