### ISSUE TITLE
Reactive form required validation not working for input type=number

### ISSUE THREAD

**Issue by sekar-dev14** [angular/angular#38608]
### Description

We need to show numpad in angular application in mobile browser.so,we set number input type for all currency format field.After that,required validation not working.

## 🔬 Minimal Reproduction

https://angular-seeui8.stackblitz.io

## 🌍  Your Environment

Angular 10

```
import { Component } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  name = 'Angular';
  constructor(
    private _fb: FormBuilder
  ) {

  }
  testForm= this._fb.group({});
  ngOnInit() {
    this.testForm=this._fb.group({
      age:['',[Validators.required]]
    });
  }
  submit() {
    
  }
}

<form [formGroup]='testForm'>
<input type="number" formControlName='age' />
<button type='button' (click)='submit()'>Submit</button>
</form>
```

**Comment by ajitsinghkaler** [comment]
For now as a workaround you can use type=tel for showing numpad

**Comment by AndrewKushnir** [comment]
Hi @sekar-dev14, thanks for reporting the issue and providing a repro.

I tried to reproduce the problem, but failed to do that. I've [created a copy of your repro](https://stackblitz.com/edit/angular-5c2wam) and added a flag that illustrates whether a form is valid. After that I tried adding/removing values in the input field and the form validity changed accordingly. I tested the behavior in Chrome browser on my laptop as well as in Mobile Safari browser on my phone.

Could you please have a look at [my repro](https://stackblitz.com/edit/angular-5c2wam) and see if the form validity changes as expected for you too?

Thank you.

**Comment by sekar-dev14** [comment]
@AndrewKushnir It's working thanks
