### ISSUE TITLE
Angular 2 routing

### ISSUE THREAD

**Issue by basvandenheuvel** [angular/angular#3861]
Hello everyone, 

i'm wondering if there is a good tut/example of how to make routing work in Angular2?
Currently i have something working using the RouteConfig in my app component, like this:
```javascript
@RouteConfig([
    { path: '/', redirectTo: '/home' },
    { path: '/home', component: Home, as: 'home' },
    { path: '/bootstrap', component: Bootstrap, as: 'bootstrap' },
    { path: '/toastr', component: Toastr, as: 'toastr' }
])
```

In my app.html i made a simple list to navigate, like this:
```html
<ul>
    <li><a [router-link]=['./home']>Home</a></li>
    <li><a [router-link]=['./bootstrap']>Bootstrap</a></li>
    <li><a [router-link]=['./toastr']>Toastr</a></li>
</ul>

<main>
    <router-outlet></router-outlet>
</main>
```

This does actually work, though not completely. The problem is, when i navigate to my... Bootstrap page im on 'XYZ/bootstrap' page. Once i press F5 i get a 404-error from the webserver, no mather i use wamp or iis. This problem happens on all my pages, i simply can't use refresh? This was perfectly possible when i used Angular 1 with ui-router.
This also mean that when im on 'XYZ/bootstrap' page and i want to navigate to my toastr page by typing it in myself, 'XYZ/toastr', i get the same error. So routing only works using the buttons in my app.html....

The other problem i have is that when i navigate through my pages and want to use the browser back and forward button  i can only navigate back one time and thats it. Like there is no history except go back one.

Hopefully someone can help me out or give me a link to a nice tut. Thanks!

**UPDATE**: i use the alpha 2.0.0-alpha.28 of Angular and 2.0.0-alpha.33 of Router. Using other versions or version combinations i couldn't even get this working...
**UPDATE**: im building my app using TypeScript in VS2013, i tried running it from VS (IIS) and publish it and run it in wamp (apache), same result

**Comment by Yunlong2cn** [comment]
I have truble in the same problem,have u solved it?

**Comment by TusharKanjariya** [comment]
I am also faced this problem
Plz help 
Thank in advanced!!
