### ISSUE TITLE
dataGroups version increase not updating new files in mobile chrome

### ISSUE THREAD

**Issue by zedL** [angular/angular#38610]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/service-worker  10.0.11

### Is this a regression?

I dont know

### Description
I configured dataGroups in ngsw-config.json like the following config shows.
<pre>
"dataGroups": [
    {
      "name": "i18n",
      "version": 5,
      "urls": [ "/assets/**" ],
      "cacheConfig": {
        "strategy": "freshness",
        "timeout": "5s",
        "maxSize": 50,
        "maxAge": "1d"
      }
    },
    {
      "name": "portal",
      "version": 2,
      "urls": [ "/api/v1/portal/**" ],
      "cacheConfig": {
        "strategy": "freshness",
        "timeout": "30s",
        "maxSize": 0,
        "maxAge": "0u"
      }
    }
  ]
</pre>
I expect that Angular loads/updates the new files after increasing the version and shipping the new compiled app version.
Unfortunatly on Android/Chrome/mobile the files gets not updated. SW still deliver the previous version.
But on Win10/Desktop/Chrome, IOS/Safrai works.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.6
Node: 14.1.0
OS: win32 x64

Angular: 10.0.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.6
@angular-devkit/build-angular     0.1000.6
@angular-devkit/build-optimizer   0.1000.6
@angular-devkit/build-webpack     0.1000.6
@angular-devkit/core              10.0.6
@angular-devkit/schematics        10.0.6
@angular/cdk                      10.1.3
@angular/cli                      10.0.6
@ngtools/webpack                  10.0.6
@schematics/angular               10.0.6
@schematics/update                0.1000.6
rxjs                              6.6.2
typescript                        3.9.7
webpack                           4.43.0

</code></pre>

**Comment by gkalpak** [comment]
Sorry for the late response. I somehow missed this 😓

Are you still having this problem, @zedL? The fact that it only happens on specific browsers is an indication that it is likely not an issue with Angular, but I would be happy to look into it some more.

Could you provide a minimal reproduction, @zedL? (For example, a GitHub repo I could check out and build locally along with clear instructions on what steps to take to see the problem in action.)

**Comment by zedL** [comment]
@AndrewKushnir I had problems with the local installed chrome mobile.
