### ISSUE TITLE
@ViewChild with { static: false } and type selector breaking unit tests

### ISSUE THREAD

**Issue by starx207** [angular/angular#38628]
This goes along with #31386, but since that thread as been locked, I started a new one.

I'm having the same issue described in that thread with the difference being that I'm not using a template name for the `@ViewChild` selector, I'm using the component type.

``` javascript
// Instead of this:
@ViewChild('templateName', { static: false }) childComponent: MyChildComponent;

// I have:
@ViewChild(MyChildComponent, { static: false }) childComponent: MyChildComponent;
```
I have a `StubChildComponent` that I'm using in my tests, and following info found [here](https://indepth.dev/angular-unit-testing-viewchild/#adding-a-provider-to-the-stub-component), define a provider to use the stub component in place of my real one.
``` javascript
TestBed.configureTestingModule({
  declarations: [ ComponentUnderTest, StubChildComponent ],
  providers: [
    { provide: MyChildComponent, useClass: StubChildComponent }
  ]
})
.compileComponents();
```
If I change `ComponentUnderTest` to either use `static: true` or use a named template instead of the component type, the tests work correctly. However, I can't use `static: true` because the `MyChildComponent` is conditionally displayed with `*ngIf`, and while I can use a named template (and probably will for now), I don't like the idea of changing the app code in order to support the tests.

Not sure if this is a bug, or if there is a different way I should be configuring my tests to handle this situation.

My version info:
```
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.1
@angular-devkit/build-angular     0.1000.1
@angular-devkit/build-optimizer   0.1000.1
@angular-devkit/build-webpack     0.1000.1
@angular-devkit/core              10.0.1
@angular-devkit/schematics        10.0.1
@angular/cdk                      10.0.1
@angular/cli                      10.0.1
@angular/material                 10.0.1
@ngtools/webpack                  10.0.1
@schematics/angular               10.0.1
@schematics/update                0.1000.1
rxjs                              6.5.5
typescript                        3.9.6
webpack                           4.43.0
```

**Comment by jelbourn** [comment]
@starx207 it's not super clear to me what you're trying to accomplish here or what your unit tests might look like. Could you provide a stackblitz that demonstrates more of the scenario?

**Comment by starx207** [comment]
@jelbourn As I was putting together a stack blitz example, I noticed that I didn't do something quite right in defining a provider for my stub component. The link I provided says to add the provider to the stub component itself, whereas I was adding it to the TestBed. Once I switched the location of the provider, everything worked. Sorry about that.

Instead of
``` typescript
// Stub Definition:
@Component({
  selector: 'child-component',
  template: '<ng-content></ng-content>'
})
class StubChildComponent { }

// With test bed configuration:
TestBed.configureTestingModule({
  declarations: [ ComponentUnderTest, StubChildComponent ],
  providers: [
    { provide: MyChildComponent, useClass: StubChildComponent }
  ]
})
.compileComponents();
```

I needed to do:
``` typescript
// Stub Definition:
@Component({
  selector: 'child-component',
  template: '<ng-content></ng-content>',
  providers: [
    { provide: MyChildComponent, useClass: StubChildComponent }
  ]
})
class StubChildComponent { }

// With test bed configuration:
TestBed.configureTestingModule({
  declarations: [ ComponentUnderTest, StubChildComponent ]
})
.compileComponents();
```

**Comment by petebacondarwin** [comment]
Great! I'm glad you got it working. Thanks for the update.
