### ISSUE TITLE
 Can't bind to 'ngIf' since it isn't a known property of 'div'. in angular 9.1

### ISSUE THREAD

**Issue by Krishna7852** [angular/angular#38634]
### Description

 *ngIf not working in angular 9.1 , in console i'm getting  Can't bind to 'ngIf' since it isn't a known property of 'div'. 

## 🌍  Your Environment

**Angular Version:**
<pre>9.1<code>

**Comment by aksdevac** [comment]
Have you imported `CommonModule` & `BrowserModule`? this looks like support request not a bug.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
