### ISSUE TITLE
Routing issue

### ISSUE THREAD

**Issue by deepakkumarbarik** [angular/angular#38636]
Hi Team,

I was trying to use the log in page routing with lazy loading. From the root module I am calling the log in page as lazy loading. It is not working properly. Please can any one help me on this. I have attached the project for more details. Advance thanks.
[my-dream-app.zip](https://github.com/angular/angular/files/5146336/my-dream-app.zip)

Best Regards,
Deepak

**Comment by sonukapoor** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
