### ISSUE TITLE
Adde more LifecycleEvents

### ISSUE THREAD

**Issue by mhevery** [angular/angular#3863]
Currently we have:
  - `OnInit` / `OnDestroy`
  - `OnCheck` / `OnChange`
  - and `OnAllChangesDone`

Proposal:
  - `onChanges()`
  - `onInit()`
  - `doCheck():boolean`
  - Content
    * `afterContentInit()`
    * `afterContentChecked()`
    * `onContentChanges()` (Delayed for now)
  - View
    * `afterViewInit()`
    * `afterViewChecked()`
    * `onViewChanges()` (Delayed for now)

**Comment by IgorMinar** [comment]
`OnViewChecked` and `OnChildrenChecked` sound good to me.

I like the idea of letting the parent know if the stuff under changed, but I don't think that providing a number of changes is useful. It should be sufficient to know if anything changed at all, so I'd go with a boolean.

**Comment by vicb** [comment]
After having seen your PR I get what the names actually mean.

I'm not sure I like that `on`, `do` and `after` all 3 mean after, why different prefixes ?

I also find `content` confusing (remind me of `<content>`)

**Comment by mhevery** [comment]
@vicb 

- `on` (`onInit`, `onDestroy`, 'onChanges`) Something has just happen letting you know, I don't care what you do with it.
- `doCheck` - I need you to do something right now. 
- `afterViewChanges` - just letting you know that we have passed a certain point. Here `on` would sound ambiguous, and `after` makes it clear that it is after view changes have been processed.

But there is still time to rename them. :-) You have other ideas?

**Comment by vicb** [comment]
@mhevery from your desciption above I don't get the difference of `on` vs `after` - and the doc says: ``OnInit` (after the first check only)`. So really I think there should be on `after` everywhere:
- `OnInit` -> `AfterInit`,
- `OnDestroy` -> `AfterDestroy`,
- `OnChanges` -> `AfterChanges`

IMO `doCheck` is confusing for an event name. When I see `lifecycle: [LifecycleEvent.DoCheck]`, I'm under the impression that it is a request for checking something (that would not be checked otherwise). FWIT I can't remember ever having seen an event prefixed with `do` (vs on, before or after). I would be satisfied with `afterCheck`.

I would also use `Children` instead  of `Content`.

**Comment by vicb** [comment]
I can see where the confusion comes from. Allow me some time to come with a better proposal.

**Comment by mhevery** [comment]
So the `Content`/`View` is more descriptive over `Children`. Which children? View or content?.

Any more thoughts?

**Comment by vicb** [comment]
Yep some more thoughts:

The enums members are actually interface names and those interface all define a function with the same name (in lowerCase).

May be then "`Event`" as in `LifecycleEvent` is not the most appropriate. `LifecycleInterface` would be more accurate but I tend to think that `LifecycleMethod` would be better (especially in ES5 context).

Also as we fall back to structural type checking in TS/JS and the method names are probably too generic and might lead to collision. Some proposal:

- onInit / onDestroy -> onDirectiveInit / onDirectiveDestroy
- doCheck -> checkBindings
- ...

Misc notes:

- Doesn't the comment for [DoCheck](https://github.com/angular/angular/blob/c349bbbc08dab05ca916b20f92d1a50cb1183618/modules/angular2/src/core/metadata/directives.ts#L940) need rework ?
- Should we rename [ViewListener methods](https://github.com/angular/angular/blob/c349bbbc08dab05ca916b20f92d1a50cb1183618/modules/angular2/src/core/compiler/view_listener.ts#L9) to be more consistent (onViewCreated vs viewCreated) ?

**Comment by mhevery** [comment]
@vicb 
1. yes let's rename ViewListeners method. Can you take on it?
2. yes, the comment on doCheck needs work. Sorry I missed it. Can you also create a PR for that?

**Comment by vicb** [comment]
closing.
- Listeners are renamed in #3925, 
- #3928 drops the LifecycleEvent enum.
