### ISSUE TITLE
Animating margin of a leaving element breaks in Firefox

### ISSUE THREAD

**Issue by sid-maddy** [angular/angular#38641]
# 🐞 Bug report

### Affected Package
@angular/animations

### Is this a regression?
No

### Description
When the margin of a leaving element is animated (* => 0), the element does not actually leave the view, but becomes unresponsive. This issue only occurs in Firefox and works in Chrome and other Chromium-based browsers.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-firefox-animations-issue (https://angular-firefox-animations-issue.stackblitz.io/)
https://github.com/sid-maddy/angular-firefox-animations-issue (https://angular-firefox-animations-issue.vercel.app/)

[Firefox recording](https://vimeo.com/453048696)
[Chrome recording](https://vimeo.com/453048678)

## 🔥 Exception or Error
N/A

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 10.0.8
Node: 12.18.3
OS: linux x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cdk                      10.1.3
@angular/cli                      10.0.8
@angular/material                 10.1.3
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Anything else relevant?**
N/A

**Comment by dario-piotrowicz** [comment]
This issue doesn't seem to happen in firefox anymore

I've tested the stackblitz with firefox 104:
![Screenshot at 2022-08-27 22-36-12](https://user-images.githubusercontent.com/61631103/187048860-0b47476c-d966-44d3-98ea-27c60830da00.png)

And as you can see everything seems to work as it should:
![Peek 2022-08-27 22-35](https://user-images.githubusercontent.com/61631103/187048846-d0f86160-4086-4841-8700-ad970ea9954b.gif)

**Comment by sid-maddy** [comment]
Yes. This seems to be fixed. Closing this issue.
