### ISSUE TITLE
Ivy: readonly property becomes readOnly without Ivy

### ISSUE THREAD

**Issue by turtledev1** [angular/angular#38655]
# 🐞 bug report

### Affected Package
Ivy renderer

### Is this a regression?
Yes, it is working without Ivy

### Description
Readonly property binding becomes camelCase for no apparent reason

## 🔬 Minimal Reproduction
In my component:
```
// template
<child-component [readonly]="readonly">
</child-component>

// component
@Input() public readonly: boolean = true;
```

In my test:
```
it('should set the item readonly attribute to true', () => {
    expect(getChildComponent().properties.readonly).toBe(true);
});
```

## 🔥 Exception or Error
Test fails. With further investigation, with Ivy disabled, the property is named `readOnly` instead of `readonly`

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.12
Node: 12.3.1
OS: darwin x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/cdk                      9.2.4
@angular/material                 9.2.4
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.5.3
typescript                        3.7.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
Can you provide a runnable repro? I cannot reproduce [in a basic StackBlitz setup](https://stackblitz.com/edit/angular-ivy-k2yaip?file=src/app/hello.component.ts).

**Comment by turtledev1** [comment]
I'm sorry, it's the contrary, before Ivy it would change to `readOnly`, but now it's `readonly`. I edited the description. 

https://stackblitz.com/edit/angular-ivy-o6ptdq 
You can check in my `spec` file, and in the console. The property is named `readonly`, but in the console it's `readOnly` and both my tests fail.

**Comment by JoostK** [comment]
Oh, I see. Interesting; so Ivy appears to have changed the behaviour according to how you expected it to work: i.e. not changing it to `readOnly`.

There's a few properties that are translated like this, e.g. `class` becomes `className` and `innerHtml` becomes `innerHTML` (the full mapping [is located here](https://github.com/angular/angular/blob/cb05c0102fc951899745e16a923966d41f9384a7/packages/core/src/render3/instructions/shared.ts#L967-L985)). Ivy only applies this mapping when setting a property to a DOM element; not on an Angular directive instance. View Engine appears to have always applied the mapping.

**Comment by AndrewKushnir** [comment]
Hi @turtledev1,

Thanks for creating a ticket and providing a repro.

As @JoostK mentioned above, in Ivy the mapping (e.g. `readonly` -> `readOnly`) is not applied when setting inputs to a component/directive instance and it's only applied when setting a property to a DOM element. We discussed this behavior and we believe that Ivy logic is more reasonable and we do not plan to change it.

Thank you.
