### ISSUE TITLE
Unsubscribing interval outside of fakeAsync call leads 1 periodic timer(s) still in the queue.

### ISSUE THREAD

**Issue by artaommahe** [angular/angular#38651]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core/testing

### Is this a regression?

 Dunno

### Description

If interval was created in one fakeAsync call and is unsubscribed in another (or without one) then test fails with `Error: 1 periodic timer(s) still in the queue.`. Same with unfinished timeout.

## 🔬 Minimal Reproduction

```ts
import { fakeAsync } from '@angular/core/testing';
import { interval, Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

describe('fakeAsync + interval', () => {
  const subscribeMock = jasmine.createSpy();
  const interval$ = interval(1000);
  const destroyed = new Subject<void>();

  beforeEach(fakeAsync(() => {
    interval$.pipe(takeUntil(destroyed)).subscribe(subscribeMock);
  }));

  afterEach(() => {
    destroyed.next();
  });

  it('smth', () => {
    expect(subscribeMock).not.toHaveBeenCalled();
  });
});
```

Adding fakeAsync calls to afterEach/it don't help.
It passes only like this

```ts
  it('smth', fakeAsync(() => {
    interval$.pipe(takeUntil(destroyed)).subscribe(subscribeMock);
    expect(1).toEqual(1);
    destroyed.next();
  }));
```

(fakeAsync is used due to tick usage in real tests)

## 🔥 Exception or Error
<pre><code>
Error: 1 periodic timer(s) still in the queue
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
yarn run v1.16.0
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.8
Node: 12.18.1
OS: win32 x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, upgrade
Ivy Workspace: Yes

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.1000.8
@angular-devkit/build-angular              0.1000.8
@angular-devkit/build-optimizer            0.1000.8
@angular-devkit/build-webpack              0.1000.8
@angular-devkit/core                       10.0.8
@angular-devkit/schematics                 10.0.8
@angular/cli                               10.0.8
@ngtools/webpack                           10.0.8
@nguniversal/common                        9.0.2
@nguniversal/express-engine                9.0.2
@nguniversal/module-map-ngfactory-loader   9.0.0-next.9
@schematics/angular                        10.0.8
@schematics/update                         0.1000.8
rxjs                                       6.5.5
typescript                                 3.9.7
webpack                                    4.43.0
</code></pre>

**Anything else relevant?**
Thats a real-word case while testing service with public Observable, that uses timers/intervals inside, and creating a subscription inside beforeEach + unsubscribing in afterEach to prevent code duplication.

**Comment by JiaLiPassion** [comment]
@artaommahe , this is by design, since `it()` itself is a test block, you have to close all timers inside a `fakeAsync`.
