### ISSUE TITLE
Angular language-service intellisense add keyof autocomplete

### ISSUE THREAD

**Issue by noelelias** [angular/angular#38663]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/language-service

### Description
A property of type keyof anyInterface when used will not display those keys inside html or inline html.

### Describe the solution you'd like
Property representing a keyof interface should give the user a list of the properties while activating intellisense inside the parameter value in the .html file or inline html.

### Describe alternatives you've considered
It's possible to use an enum but they have to be defined inside the ts file first.

**Comment by JoostK** [comment]
This was recently implemented for the Ivy language service in #41645, which has been released in v12.
