### ISSUE TITLE
zone.js v0.11.1: TypeError "Invalid Calling Object" & 'undefined' where a stream was expected Errors in IE11

### ISSUE THREAD

**Issue by JaxonWright** [angular/angular#38669]
# 🐞 bug report

### Affected Package
zone.js v0.11.1

### Is this a regression?

Yes, v0.10.3 does not have this issue

### Description

When trying to open an Angular application within IE11, this exception is thrown and the browser really does not tell you anything useful. I basically got lucky as I discovered this only happened after updating dependencies, and was able to narrow it down to zone.js.

## 🔬 Minimal Reproduction
I have tried making a repro, but StackBlitz does not even work in IE11 at all. I believe the issue stems from making calls with HttpClient, though. I wish that I could provide more information here.

## 🔥 Exception or Error
<pre><code>
ERROR TypeError: Invalid calling object
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "Invalid calling object",
      message: "Invalid calling object",
      name: "TypeError",
      number: -2147418113,
      stack: "TypeError: Invalid calling object
   at scheduleTask (http://localhost:4201/polyfills-es5.js:15404:9)
   at scheduleTask (http://localhost:4201/polyfills-es5.js:12549:15)
   at onScheduleTask (http://localhost:4201/polyfills-es5.js:12436:9)
   at scheduleTask (http://localhost:4201/polyfills-es5.js:12544:13)
   at scheduleTask (http://localhost:4201/polyfills-es5.js:12294:13)
   at scheduleMacroTask (http://localhost:4201/polyfills-es5.js:12325:11)
   at scheduleMacroTaskWithCurrentZone (http://localhost:4201/polyfills-es5.js:12955:5)
   at Anonymous function (http://localhost:4201/polyfills-es5.js:15456:13)
   at proto[name] (http://localhost:4201/polyfills-es5.js:13319:11)
   at Anonymous function (http://localhost:4201/vendor.js:39494:5)",
      Symbol()_8.tzdmwasjaqy: undefined,
      Symbol(INITIAL_VALUE)_j.tzdmwasjakg: undefined,
      Symbol(nodejs.util.inspect.custom)_k.tzdmwasjakg: undefined,
      Symbol(rxSubscriber)_i.tzdmwasjakg: undefined
   }

ERROR TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      message: "You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.",
      name: "TypeError",
      stack: "TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
   at subscribeTo (http://localhost:4201/vendor.js:232505:1)
   at innerSubscribe (http://localhost:4201/vendor.js:219250:4)
   at error (http://localhost:4201/vendor.js:222695:5)
   at _error (http://localhost:4201/vendor.js:218653:3)
   at error (http://localhost:4201/vendor.js:218622:5)
   at _trySubscribe (http://localhost:4201/vendor.js:217811:7)
   at subscribe (http://localhost:4201/vendor.js:217784:5)
   at call (http://localhost:4201/vendor.js:225367:3)
   at subscribe (http://localhost:4201/vendor.js:217782:5)
   at call (http://localhost:4201/vendor.js:222654:3)",
      Symbol()_8.tzdmwasjaqy: undefined,
      Symbol(INITIAL_VALUE)_j.tzdmwasjakg: undefined,
      Symbol(nodejs.util.inspect.custom)_k.tzdmwasjakg: undefined,
      Symbol(rxSubscriber)_i.tzdmwasjakg: undefined
   }

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.8
Node: 14.4.0
OS: win32 x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cdk                      10.1.3
@angular/cli                      10.0.8
@angular/material                 10.1.3
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.6.2
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Anything else relevant?**
This is specific to Internet Explorer 11

**Comment by JaxonWright** [comment]
This might be related to #38561

**Comment by sivaecekrr** [comment]
I get the below issue after upgrading zone from **0.10.3** to **0.11.1** in IE11. But it works in 0.10.3.

SCRIPT1002: Syntax error
polyfills-es5.js (15604,9)

SCRIPT1002: Syntax error
polyfills.js (5252,9)

SCRIPT5009: 'Promise' is undefined
vendor.js (242998,41)

**Comment by JiaLiPassion** [comment]
@JaxonWright , @sivaecekrr , this issue seems to be the same reason as #38561, so could you provide a reproduce repo so I can confirm? And is your project created by `Angular CLI`? thanks.

**Comment by sivaecekrr** [comment]
@JiaLiPassion Yes project i am working on use Angular CLI (v9.1.11). Issue i faced in company project. Will try to create a repo. Thanks.

**Comment by adamdport** [comment]
[rolling back zone](https://github.com/angular/angular/issues/38561#issuecomment-679956163) resolved this issue for me

**Comment by JiaLiPassion** [comment]
Please use the new released `0.11.2`, this issue should be gone.

**Comment by JaxonWright** [comment]
I can confirm that `0.11.2` works as expected.
