### ISSUE TITLE
New Documentation

### ISSUE THREAD

**Issue by ArinaSavchenko** [angular/angular#38661]
# 📚 Docs or angular.io bug report

### Description

 I'm totally disappointed with your update. Your refactored docs doesn't contain "Fundamentals" materials. I've lost possibility to increase my knowledge and widen my outlook. I hope you'll solve this problem and bring all staff back as soon as possible.

### What's the affected URL?**
 https://angular.io/...

### Reproduction Steps**

1) Return previous version of Documentation 
2) If it's impossible host both versions
3) If it is either impossible, please, send me or public the path where this information is located in new version

### BEFORE:
![photo_2020-09-01_15-59-47](https://user-images.githubusercontent.com/56936671/91855317-ae6a1680-ec6d-11ea-8cce-2c6bf9e8692a.jpg)

### AFTER:
![image](https://user-images.githubusercontent.com/56936671/91855388-c80b5e00-ec6d-11ea-921c-a4b9037a8b93.png)

### Anything else relevant?

I love Angular <3

**Comment by petebacondarwin** [comment]
Hi @ArinaSavchenko - none of the guides have been removed. It is just that the navigation menus have been reordered and renamed. Move of what was previously under "Fundamentals" is now under "Main Concepts". If you want to, you can compare the navigation in the v9.angular.io with the new navigation.

**Comment by aikidave** [comment]
Hi @ArinaSavchenko! I am sorry you're unhappy with the documentation changes. I hope that, as you get used to these changes, you'll find it easier to find the information you need. I'm writing up a document to explain these changes more fully. My explanation may not make you content with these changes, but at least I can explain why I made them!

Please continue to share your feedback!
