### ISSUE TITLE
Named router outlets which use the normal uri to navigate

### ISSUE THREAD

**Issue by TheBlue-1** [angular/angular#38678]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/router

### Description
Named router outlets use their own url part and can not use the full url.
In many cases it's senseful to have multiple components with content according to the url 
and it would safe much code if you wouldnt need to have just one primary route outlet where you need to change all of the childs contents.

As example:
your site has a banner at the top of the page, than a navigation bar, and below that some content.
The banner should always be fitted to the content.
Thats where you could use a named outlet for the banner which uses the same url as the contents (primary) outlet.

Right now you would have to make the whole page the primary outlet, and add the navigationbar to all routed components.

### Describe the solution you'd like
Named outlets routes should have an option to use the main url like this:
`{ path: '**', outlet: 'navigation', component: MainNavigationComponent, useMainUrl: true }`
and if it's set to true, it should use the same value to compare as the main outlet would use.

**Comment by criskrzysiu** [comment]
I would add another feature, add names to route levels, and allow to be render multiple components from one router outlet like this

[blade layout](https://ibb.co/mT00tw4)

```typescript
{ path: 'invoices', component: InvoicesBladeContainer, levelName: 'invoices', children: [
   { path: '', component: InvoicesList, children: [
      { path: 'details', component: InvoiceDetails, level: 'invoices', children: [
         { path: 'lines', component: InvoiceLinesList, children: [
           { path: 'create', component: InvoiceLineCreate, level: 'invoices'  } 
          ] }      
      ] }       
  ] }
], }
```

so we get ability to render components next to each other instead of always one into another. And thus blade layout.

**Comment by Airblader** [comment]
@criskrzysiu Instead of hijacking this issue please open a feature request yourself for that.
