### ISSUE TITLE
Space preservation attribute not added to XLF file

### ISSUE THREAD

**Issue by ArtemAvramenko** [angular/angular#38679]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/localize^10.1.0-rc.0

### Description

In ts code I use i18n:
``` typescript
title = $localize`hello\nworld` // tooltip should be shown in two lines
```
Then I call `localize-extract` and get xlf file without `xml:space="preserve"` attribute:
``` xml
  ...
  <file source-language="en" datatype="plaintext" original="ng2.template">
  ...
      <trans-unit id="1122334455667788990" datatype="html">
        <source>Hello
world</source>
  ...
````
When I add translation in CAT tool (OmegaT), line break is gone.

## 🌍  Your Environment

**Angular Version:**
```
10.1.0-rc.0
```

**Comment by petebacondarwin** [comment]
I guess this would be a sensible attribute to include... let me just check it won't cause any problems.

**Comment by petebacondarwin** [comment]
@ArtemAvramenko - did you consider trying to set the configuration of OmegaT? I see that there is a whitespace handling configuration in the "7.6 File Filters" section - https://omegat.sourceforge.io/manual-standard/en/windows.and.dialogs.html#dialogs.preferences.

**Comment by ArtemAvramenko** [comment]
That are my options:
![image](https://user-images.githubusercontent.com/11413326/92473561-76218580-f1e3-11ea-9fb3-822ee6b6a2c5.png)

These options have effect on output, but the problem that OmegaT respects `xml:space` attribute, so it ignores whitespaces in source file.

**Comment by ArtemAvramenko** [comment]
For now I run powershell script after resource extracting:
```
$file = Resolve-Path $args[0]
$content = [System.IO.File]::ReadAllText($file)
$content = $content -replace '(<file.+)>', '$1 xml:space="preserve">'
[System.IO.File]::WriteAllText($file, $content)
```

**Comment by ArtemAvramenko** [comment]
Adding `--preserveSpaces` to `localize-extract` would be an ideal solution for me.

**Comment by petebacondarwin** [comment]
Yeah, I think it might need to be behind a flag, since I am concerned that many XLIFF readers might not handle the xml namespaced attribute. It looks like XLIFF is trying to agree a specification for this but it has not made it standard yet.
