### ISSUE TITLE
Time zone globally

### ISSUE THREAD

**Issue by Yavorss** [angular/angular#38696]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
I would like a global time zone setting for the date pipe. Currently, the date pipe gets a time zone as an optional parameter if there is no such parameter then gets the current zone of the client. 

### Describe the solution you'd like
We could achieve that with an injection token just like the LOCALE one.

I could implement that. My plan is to create a new injection token called TIME_ZONE in the **/i18n/tokens.ts**. Then we could inject that token in the application_module.ts with a default value your local time zone. Once we have that we could inject that token in the date pipe and pass that value to the **formatDate** method.

**Comment by petebacondarwin** [comment]
For what it is worth, this is pretty easy to implement locally for your own project: https://stackblitz.com/edit/ivy-ryeoix?file=src%2Fapp%2Fapp.component.html

Given not many people have requested this, and it is straightforward to implement on a per-project basis, I would not be in favour of landing such a feature.

**Comment by Yavorss** [comment]
In the example above, you should create a new pipe to do that. In my opinion would be better if the angular date pipe has that ability.

**Comment by petebacondarwin** [comment]
Closing as this is a rare use-case (only one person has requested it with only two +1s), which can be handled in application code quite easily.
