### ISSUE TITLE
Extractor no longer extracts the location if i18n is without parameters

### ISSUE THREAD

**Issue by jaska45** [angular/angular#38705]
# 🐞 bug report

First of all, congratuliations for Angular 10.1, It finally complated the I18N features and you now can localize templates and the source code. I wrote an [API that enables loading the translations on runtime](https://github.com/soluling/I18N/tree/master/Library/Angular) that you can use to create a single deployment that can serve any number of languages.

Then for the bug I found in 10.1.0.

### Is this a regression?

Yes. This used to work in Angular 10.

### Description

If you use i18n attribute without any parameter (i.e. meaning or comment) the extractor tool does not extract location.

## 🔬 Minimal Reproduction

You can find a repo [here](https://github.com/jaska45/LocationBug).

Use this template

```
<p i18n>This is a sample</p>
<p i18n="Comment">This is a sample with a comment</p>
```
Run XLIFF 2,0 extraction.

`ng xi18n --format=xlf2 --output-path src/locale --ivy`

You will get the following XLIFF

```
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="2.0" xmlns="urn:oasis:names:tc:xliff:document:2.0" srcLang="en-US">
  <file id="ngi18n" original="ng.template">
    <unit id="3067469718492071419">
      <segment>
        <source>This is a sample</source>
      </segment>
    </unit>
    <unit id="5855772298569654559">
      <notes>
        <note category="location">src/app/app.component.js:23</note>
        <note category="description">Comment</note>
      </notes>
      <segment>
        <source>This is a sample with a comment</source>
      </segment>
    </unit>
  </file>
</xliff>
```

The first unit is without location note!

## 🌍  Your Environment

**Angular Version:** 

```
Angular CLI: 10.1.0
Node: 12.9.1
OS: win32 x64

Angular: 10.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.0
@angular-devkit/build-angular     0.1001.0
@angular-devkit/build-optimizer   0.1001.0
@angular-devkit/build-webpack     0.1001.0
@angular-devkit/core              10.1.0
@angular-devkit/schematics        10.1.0
@ngtools/webpack                  10.1.0
@schematics/angular               10.1.0
@schematics/update                0.1001.0
rxjs                              6.6.2
typescript                        4.0.2
webpack                           4.44.1
```

**Comment by petebacondarwin** [comment]
I'll investigate this today.
