### ISSUE TITLE
Angular documentation 

### ISSUE THREAD

**Issue by yashi12** [angular/angular#38722]
The documentation pages do not scroll smoothly, it is very difficult to scroll the pages and takes large time in responding.
Also on clicking on the topics on right hand side the page loading takes a lot of time.

**Comment by petebacondarwin** [comment]
Please can you provide some more information about these problems? Perhaps video of your screen when the scrolling is not moving smoothly. And for the page loading, please provide explicit steps to reproduce the issue, including the URL of the page and the items in the contents pane that you are clicking.

**Comment by yashi12** [comment]
When I scroll the documentation page of angular [https://angular.io/tutorial/toh-pt6](url) or even any other documentation page , initially scroll works fine but when I am on that page for few minutes and try scrolling small amount of content then I get a lag between the scrolling content seen on the screen, the scroll occours after few seconds, it does not occur simultaneously while scrolling on touchpad.
In this video I have shown the lag
[https://drive.google.com/file/d/149dfPZpZy1HgV4VAEQbFo8-YY8AQCVOZ/view?usp=sharing](url).

Thankyou

**Comment by gkalpak** [comment]
Thanks for getting back, @yashi12!

Unfortunately, I cannot reproduce the issue 😕
I wonder if it is related to some Chrome extension you have. Can you try opening the docs in an incognito tab with extensions disabled?

**Comment by petebacondarwin** [comment]
Closing due to lack of response.
