### ISSUE TITLE
Dart: make long stack traces optional

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#3872]
They pull in `package:stack_trace` dependency, which in turn pulls in `package:path` and `trace`.

**Comment by jbdeboer** [comment]
I just filed #5453 to make them default. This two issues should be orthogonal, though: maybe two implementations of NgZone: NgZoneWithShortTraces and NgZoneWithLongTraces.

**Comment by naomiblack** [comment]
They are optional. See #7345
