### ISSUE TITLE
d.ts generation does not preserve spread arguments

### ISSUE THREAD

**Issue by btford** [angular/angular#3874]
If you look at the generated definition for `Type` in `angular2.d.ts`, you'll notice that it does not include the spread operator as it was declared in `core/facade/lang.ts`.

@alexeagle can you please help with this?

This causes #3753.

**Comment by pkozlowski-opensource** [comment]
Looks like it was fixed via a34d4c6a5f75fdc766d1e80635215550b1e4a065, right? @alexeagle @btford ?

**Comment by btford** [comment]
yes
