### ISSUE TITLE
avoid verbosity when calling super()

### ISSUE THREAD

**Issue by GlauberF** [angular/angular#38757]
# 🚀 feature request

### Description
there is some more practical / dynamic way of passing the injectors from the constructor to the super ().
instead of one to 1, example:
`super(MatDialog)`

![Captura-de-Tela_selecionar-area_20200908180336](https://user-images.githubusercontent.com/11314585/92592802-833b8480-f276-11ea-8af5-7e7482a68ae3.png)

In the image you can see that the CompanyCustomerDataComponent class has an extend UtilsDetailsForm, within the UtilsDetailsForm I use the constructor too, but it has the same fields as the CompanyCustomerDataComponent constructor.

So it would be very verbose in the CompanyCustomerDataComponent class, inside the super inject one by one what is being ejected into the constructor already.

**Comment by Airblader** [comment]
That's how TS works. Angular doesn't modify TS, it uses it.

**Comment by petebacondarwin** [comment]
@Airblader is right. This is not something that Angular has any control over.
You can do some funky things with TypeScript types, so you might get some mileage with something like:

```
class Parent {
  constructor(public a: number, public b: number, public c: number) {}
}

class Child extends Parent {
  constructor(a: number, b: number, c: number) {
    const args: ConstructorParameters<typeof Child> = arguments as any;
    super(...args);
  }
}
```

But really I think that this is just a necessary evil.

Closing as this is not an issue with Angular itself.
