### ISSUE TITLE
Minor documentation issue: Step by Step Guide: Step 3: User Input

### ISSUE THREAD

**Issue by vernjensen** [angular/angular#3878]
For the docs here:
https://angular.io/docs/js/latest/guide/user-input.html

in the Final Code section, this line:

    <li *ngfor="#todo of todos">

should instead be:

    <li *ng-for="#todo of todos">

It is correct earlier in the article.

**Comment by vicb** [comment]
see https://github.com/angular/angular.io/pull/192
