### ISSUE TITLE
Pre-rendering should work out of the box without Angular Universal

### ISSUE THREAD

**Issue by siva636** [angular/angular#38785]
### Description
 Pre-rendering was introduced in Angular 9, but this does not work without Angular Universal. Adding Universal involves significant work that includes modifying our codebase. But if I just want to run my application only on browsers, why should I think 'Universal'?! 

Angular pre-rendering feature should work out of the box without Universal, for example when we run `ng build --prod` all the pages configured ( in angular.json) for pre-rendering should just be pre-rendered by default.

### Describe the solution you'd like
 This feature may be implemented using Puppeteer as described in the following articles:

[Headless Chrome: an answer to server-side rendering JS sites
](https://developers.google.com/web/tools/puppeteer/articles/ssr)
[Prerender an Angular application with @angular/cli and puppeteer](https://blog.cloudboost.io/prerender-an-angular-application-with-angular-cli-and-puppeteer-25dede2f0252)

**Comment by geromegrignon** [comment]
If the maintainers don't mind, i advice you to take a look at [Scully](https://scully.io/) which use Puppeteer under the hood to prerender your application without having to configure your project (still some routing prerequisites as it uses Guess.js to find out the routes of your application).

**Comment by petebacondarwin** [comment]
I am tempted to close this, since Scully does indeed provide what @siva636 appears to be asking for.

**Comment by alan-agius4** [comment]
Closing since with Angular Universal version 12, there is a new experimental approach for SSR/rendering which is easier to get started with and require far less onboard changes.

Try it out using the below command.
```
ng add @nguniversal/common
```
