### ISSUE TITLE
templateUrl does not understand relative paths when using double quotes

### ISSUE THREAD

**Issue by ErgoProxy1** [angular/angular#38796]
We recently encountered an issue where, after deployment, the html file for a component would not be found on the server. This was due to the server looking for the file in root (website.com/component.html) rather than its actual directory (website.com/main/project/something/component.html). 

This was fixed when we changed @Components templateUrl from:

`templateUrl = "./component.html"`

to:

`templateUrl = './component.html'`

After replacing double quotes with single quotes, the server started looking for images in the correct path. It would seem that Angular thought that "./" referred to the root directory rather than the current folder when using double quotes.

Unfortunately, I can't provide too many details about our environment, but I can say that the "dist" folder used for hosting was generated using a gulp script and our hosting is done on heroku. We also use .pug rather than .html files for our templates. Other than that, everything runs on fairly standard Angular 10.

Please let me know if there are any other details I can provide, or if this is already a known bug (Or even expected behaviour?)

**Comment by Airblader** [comment]
> This was due to the server looking for the file in root (website.com/component.html) rather than its actual directory (website.com/main/project/something/component.html).

A compiled Angular application doesn't even have HTML files anymore (apart from index). Templates get compiled into JS.

> This was fixed when we changed @components templateUrl from:
>
> ```
> templateUrl = "./component.html"
> ```
>
> to:
>
> ```
> templateUrl = './component.html'
> ```

Either one is invalid TS and would cause a compilation error.

> After replacing double quotes with single quotes, the server started looking for images in the correct path.

Images? What images? I thought this was about the HTML files?

> Unfortunately, I can't provide too many details about our environment

Nor a reproducible example, therefore no one will be able to help you.

> We also use .pug rather than .html files for our templates.

Why did the two lines of code then say *.html?

> Please let me know if there are any other details I can provide

Fill out the issue template and provide a project that reproduces the problem.

**Comment by petebacondarwin** [comment]
I'm sorry but we can't reproduce the problem you are reporting. We require that reported issues have a minimal reproduction that showcases the problem.

Moreover, it sounds like you have a very custom setup that (possibly?) involves JIT compilation (not recommended) and some kind of additional loader that converts your PUG files to HTML.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template that include info on how to create a reproduction using our template.

**Comment by ErgoProxy1** [comment]
@Airblader Sorry about the images part, I meant .html files. Regarding the .pug files, they are converted to .html files when the gulp script is executed.

@petebacondarwin Will do

**Comment by ErgoProxy1** [comment]
@Airblader I'm confused about it being invalid TS, it's the same as I found in many Angular examples online. What part of this would be incorrect:

`@Component({
    selector: 'app-example-component',
    templateUrl: './example-component.html',
})
export class ExampleComponent implements OnInit`

**Comment by Airblader** [comment]
```
templateUrl: './example-component.html',
```

is correct, but not what you wrote. You wrote

```
templateUrl = './example-component.html',
```

**Comment by ErgoProxy1** [comment]
Ah yes, my mistake!
