### ISSUE TITLE
use component in two components angular

### ISSUE THREAD

**Issue by AmeerAmjed** [angular/angular#38794]
I have Three components (NavbarComponent , IndexComponent , PoweredComponent ) so I use lazy loading I need use components in multi components

- NavbarComponent
**navbar.module.ts** 
`@NgModule({
  declarations: [NavbarComponent],
  imports: [
    CommonModule
  ],
  exports: [NavbarComponent]
})`

- IndexComponent
**Index.module.ts** 
`@NgModule({
  declarations: [IndexComponent ,NavbarComponent],
  imports: [
    CommonModule,
    IndexRoutingModule,
  ],
})`

**index.component.html**
`<app-navbar></app-navbar>
.......
`
in index show navbar 
![image](https://user-images.githubusercontent.com/33216144/92770966-2689b800-f3a3-11ea-9c2c-fab2bb8cdccd.png)

- PoweredComponent

**powered.module.ts**
`@NgModule({
  declarations: [PoweredComponent,NavbarComponent],
  imports: [
    CommonModule,
    PoweredRoutingModule,
  ], 
})`

**powered.component.html**
`<app-navbar></app-navbar>
.......
`
in powered not show navbar  and not show any error
![image](https://user-images.githubusercontent.com/33216144/92771334-7799ac00-f3a3-11ea-995c-17540bef8471.png)

 
I need show navbar in `powered.component.html`

Thank to read!

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
