### ISSUE TITLE
router.recognize doesn't find urls ( alpha.35 ) 

### ISSUE THREAD

**Issue by gustavoq-infocorp** [angular/angular#3879]
I'm using router.subscribe to know when a navigation occurred and I'm trying to get the component related with the current url (from router.subscribe) but router.recognize doesn't find it. 

I tried to call router.recognize with other registered urls but the result is the same.

See code here http://plnkr.co/edit/R5tqQdw2u59eBch1nikE

**Comment by brandonroberts** [comment]
The router.recognize returns a promise, so you need to handle the return to get the instruction, which has the component

   checkRecognizeResult(result, value){
        if (result) {
          result.then(function(instruction) {
            if (instruction.component){
              alert ('ok using "' + value + '"');
            } else {
              alert ('nothing found using "' + value + '"');
            }
          });
        }
    }

**Comment by gustavoq-infocorp** [comment]
Thanks Brandon, I'm closing the issue.

By the way, the Instruction.component property return a ComponentInstruction, do you know how to get the instance for the current component (I'm talking about Page1 or Page2 in the sample)?

**Comment by brandonroberts** [comment]
You can get the component by accessing the ComponentInstruction.component.componentType

**Comment by gustavoq-infocorp** [comment]
Mmm, I'm losing something :)

component.componentType is the type (Page1) and I want the specific instance created by the router, not a new one from Page1's constructor.

I dont know, maybe I need a different approach :)
