### ISSUE TITLE
i18n Ivy extactor: missing type="fmt" inside <source> 

### ISSUE THREAD

**Issue by mstawick** [angular/angular#38791]
# 🐞 bug report

### Is this a regression?
Kind of. Makes translation system (Crowdin in my case) treat the extracted text as a new string

### Description
Given following HTML:
`<div i18n>You're using a web browser<br/>that we don't support.</div>`

Old extractor would produce:
`<source>You&apos;re using a web browser<ph id="0" equiv="LINE_BREAK" type="fmt" disp="&lt;br/&gt;"/>that we don&apos;t support.</source>`

But with the --ivy flag it produces:
`<source>You&apos;re using a web browser<ph id="0" equiv="LINE_BREAK" disp="&lt;br/&gt;"/>that we don&apos;t support.</source>`

so the `type="fmt"` is missing, changing into a new string.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.1.0
Node: 14.10.0
OS: linux x64

Angular: 10.1.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1001.0
@angular-devkit/build-angular      0.1001.0
@angular-devkit/build-optimizer    0.1001.0
@angular-devkit/build-webpack      0.1001.0
@angular-devkit/core               10.1.0
@angular-devkit/schematics         10.1.0
@angular/cdk                       10.2.0
@angular/cli                       10.1.0
@angular/material                  10.2.0
@angular/material-moment-adapter   10.2.0
@ngtools/webpack                   10.1.0
@schematics/angular                10.1.0
@schematics/update                 0.1001.0
rxjs                               6.6.3
typescript                         4.0.2
webpack                            4.44.1
</code></pre>

**Comment by petebacondarwin** [comment]
@mstawick thanks for sending this in. I will look into it. It is a bit difficult to accurately identify these "type" attributes for placeholders since the `$localize` tagged strings do not contain HTML related information.

Can I ask, does the id of the message change? If not, which is what I would expect, why does your tool (Crowdin) treat it as a different message?

**Comment by mstawick** [comment]
@petebacondarwin It's because Crowdin doesn't understand anything between the <source> tags - it's just a string. So even though the ID is the same, it thinks that the string has changed, marking it as needing translation. So I guess I can have someone just go through all the languages and approve all the "changed" translations. Thanks for looking into this.
