### ISSUE TITLE
Macro Tasks left running after failed http requests with Unknown Error, preventing protractor from completing tests

### ISSUE THREAD

**Issue by wfairclough** [angular/angular#38795]
# 🐞 bug report

### Affected Package
@angular/common/http

### Is this a regression?
Yes.
Worked in **@angular/common@9.1.12**

### Description
A macroTask is left running when certain http errors occur and this prevents protractor for completing since there are tasks left running in the ngZone.

## 🔬 Minimal Reproduction
https://github.com/wfairclough/AngularHttpMacroTaskMinimalReproduction

Run `npm install`

Run with `npx ng serve`

Open Chrome Browser to `http://localhost:4200`

**Reproduce Bug**

1. Click Button **Make Successful Request** and see successul response.
1. Click Button **Check Task Counts** and see the open micro and macro task counts in the ngZone.
1. Click Button **Make Failed Request** and see the error response.
1. Click Button **Check Task Counts** again and notice that the macroTask count is now 1.
1. Repeat failed requests as many times as you like and the marcroTask count will just keep increasing.

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/1356641/92775200-2e7a3580-f36c-11ea-8088-f74c23bd01a1.png)

No macroTasks should be left running after this failed http request.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.0
Node: 10.20.1
OS: linux x64

Angular: 10.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.0
@angular-devkit/build-angular     0.1001.0
@angular-devkit/build-optimizer   0.1001.0
@angular-devkit/build-webpack     0.1001.0
@angular-devkit/core              10.1.0
@angular-devkit/schematics        10.1.0
@angular/cli                      10.1.0
@ngtools/webpack                  10.1.0
@schematics/angular               10.1.0
@schematics/update                0.1001.0
rxjs                              6.6.3
typescript                        4.0.2
webpack                           4.44.1
</code></pre>

**Anything else relevant?**
Error occurs in both browsers I tested with Chrome and Firefox.

**Comment by JoostK** [comment]
Confirmed and identified #37367 to be the cause (reverting that change fixes the issue).

**Comment by JoostK** [comment]
@JiaLiPassion could you have a look at  zone.js's XHR patching to see if this is something that can be addressed from within zone.js, without needing to revert #37367?

**Comment by nutza249949** [comment]
u

**Comment by JiaLiPassion** [comment]
@JoostK , sure, I will chck this one.

**Comment by wfairclough** [comment]
Hi @JiaLiPassion,

Thanks for looking into this issue I was seeing. I have tried updating my minimal reproduction repo to 10.1.4 to see that your commit fixes the issues, although I am still seeing macroTasks left running after requests to non-existent urls. I believe the fix should be in the release, am I mistaken?

```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.4
Node: 10.20.1
OS: linux x64

Angular: 10.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.4
@angular-devkit/build-angular   0.1001.4
@angular-devkit/core            10.1.4
@angular-devkit/schematics      10.1.4
@schematics/angular             10.1.4
@schematics/update              0.1001.4
rxjs                            6.6.3
typescript                      4.0.2 
```

https://github.com/wfairclough/AngularHttpMacroTaskMinimalReproduction

**Comment by JoostK** [comment]
@wfairclough Could you try with zone.js 0.11.2? It's released separately from the main framework; [the changelog can be found here](https://github.com/angular/angular/blob/05672ab13644b1cb03c3683fdfa4c2d186438938/packages/zone.js/CHANGELOG.md).

**Comment by wfairclough** [comment]
@JoostK Thanks for pointing that out. Doesn't look like 0.11.2 has been released to npm as of now, I will try it once it has been published.

**Comment by JoostK** [comment]
@wfairclough Oh, I didn't realize that. But now that you mention it, I remembered there's #39094 for that.
