### ISSUE TITLE
ERROR in node_modules/@angular/platform-browser/platform-browser.d.ts:44:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

### ISSUE THREAD

**Issue by Martinlorajorge** [angular/angular#38800]
This likely means that the library (@angular/platform-browser) which declares BrowserModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

44 export declare class BrowserModule {
                        ~~~~~~~~~~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


HOLA A TODOS SOY NUEVO EN ESTE TEMA DE ANGULAR Y NODE JS ME ESTOY INICIANDO. ESCRIBO EN MAYUSCULA PARA DIFERENCIARLO DEL ERROR.

SI ALGUNO PUEDE AYUDARME CON ESE ERROR. QUIERO INICIAR ng serve Y ME SALE ESO. QUE PUEDO HACER. PORFA

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
