### ISSUE TITLE
Can't bind to 'ngforOf'

### ISSUE THREAD

**Issue by isakulaksiz** [angular/angular#38813]
**Error :** Can't bind to 'ngforOf' since it isn't a known property of 'li'.

component.html
`
<div>
  <ul>
    List below!
   
    <li *ngfor = "let avatar of  avatars" >
      {{ avatar.total }}
      
    </li>
   
  </ul>
</div>
`
Can you give me a information.Where I did mistake ?

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

But hey: attributes are case sensitive, so it needs to be `<li *ngFor="let avatar of avatars">`.

**Comment by Abhishek9166919669** [comment]
After reviewing your issue I can see that you are doing one mistake.

you should write
<li ***ngFor** = "let avatar of  avatars" >
  {{ avatar.total }}</li>

Hope this will help you.

If required you can take a reference from the below screenshot.
![image](https://user-images.githubusercontent.com/39114448/93851096-832b8380-fc7d-11ea-8289-f9004f059b22.png)

Angular Doc
https://angular.io/tutorial/toh-pt2

**Comment by isakulaksiz** [comment]
Thanks @Abhishek9166919669 
It works fine,
