### ISSUE TITLE
Templates for components that are not declared are rendered

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular#38829]
The router will render a component template for a component that is not declared.

For example if we copy a component into a project and add it to routing and forget to declare it.

However if we are using something like a material button in the component, the button will not render.  Angular does not explain this in any type of error reporting.

**Comment by JoostK** [comment]
Could you please provide a reproduction? I kind of see what you're hinting at, but there may be quite some variables that may affect the behavior here (e.g. JIT vs AOT, ViewEngine vs Ivy). So a reproduction would provide us with a well-defined setup in which we can observe the failure mode you're bringing up here.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
