### ISSUE TITLE
refactor(ngContent): rename <ng-content> to <ng-slot>

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#3882]
Turns out that the Shadow DOM's spec `<content>` element has been deprecated and is now called `<slot>`.

Do we want to align `<ng-content>` accordingly?

https://w3c.github.io/webcomponents/spec/shadow/#slots

**Comment by tamascsaba** [comment]
https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/Ez2cuT0KmQo/eUpSsU-uAgAJ

**Comment by PascalPrecht** [comment]
I think I saw in the weekly meeting notes that `<ng-content>` is going to stay and `<ng-slot>` will be added

**Comment by mhevery** [comment]
@tbosch can you comment

**Comment by tbosch** [comment]
- We already have our own semantics behind it (see [Static content projection](https://docs.google.com/a/google.com/document/d/1BXUFVpImyWN7ynyPKehAesctP0UJTaDYbDTNVkarSeQ/edit?usp=drive_web))
- using selectors allows to build components with a nicer API (a user does not have to use the `slot` attribute for child nodes). 
- Performance is not an issue for Angular as we precalculate the content projection during compilation, which will eventually end up in a build step.

So far we stick with `<ng-content>`...

**Comment by tbosch** [comment]
We _can_ add `ng-slot` trivially though, if users really want it...

**Comment by vicb** [comment]
IMO renaming it to `<ng-slot>` would be confusing for users (vs `<slot>`).

**Comment by PascalPrecht** [comment]
We can stick with just `slot` too, the more interesting question is, if we want to implements this or not. @tbosch thank you for the doc! I just read it and it makes also (finally) clear why we have `ng-content`.

So based on that document it really seems like `slot` is not hard to implement as it boils down to `ng-content select="[slot..."`, however, I'd say we can add this, as soon as people are actually asking for it. I could imagine that very few users (if at all) will have a use case for that. That might change in the future tho.

**Comment by mhevery** [comment]
We should stick with `content`. We have content injection, content change detection, contentBindings, etc. In all of those cases slot does not make sense. 

We may implement the new functionality, but that is outside the scope of this issue.

Closing.
