### ISSUE TITLE
Is there a way to use Routing without router-outlet

### ISSUE THREAD

**Issue by sergeyplishka** [angular/angular#38837]
How can I use routing only for logical actions?
And I do not need that some components be inserted somewhere in the template.
But browser url should be changed and navigating to these urls should be handled.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
