### ISSUE TITLE
Allow using hgroup tag in Angular templates

### ISSUE THREAD

**Issue by yinonov** [angular/angular#38831]
# 🐞 bug report
This is a very simple issue and there aren't many details to share

### Description
I'm getting compilation error on including the `hgroup` tag in a template which is a [totally valid html tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup).

```
Error in src/app/app.component.html (6:1)
'hgroup' is not a known element:
1. If 'hgroup' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
```

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-vwcpfd?file=src/app/app.component.html

if there isn't any special reason to exclude this tag, it would help composing html semantically

**Comment by Airblader** [comment]
> The <hgroup> element has been removed from the HTML5 (W3C) specification

**Comment by RafaelAngelRamirez** [comment]
From [docs](https://developer.mozilla.org/en-US/docs/Web/HTML/element/hgroup):

> The <hgroup> element has been removed from the HTML5 (W3C) specification, but it still is in the WHATWG version of HTML. It is partially implemented in most browsers, though, so is unlikely to go away.
> However, given that a key purpose of the <hgroup> element is to affect how headings are displayed by the outline algorithm defined in the HTML specification—but the HTML outline algorithm is not implemented in any browsers—then the <hgroup> semantics are in practice only theoretical.
> So the HTML5 (W3C) specification provides advice on how to mark up Subheadings, subtitles, alternative titles and taglines without using <hgroup>.

**Comment by yinonov** [comment]
> From [docs](https://developer.mozilla.org/en-US/docs/Web/HTML/element/hgroup):
> 
> > The <hgroup > element has been removed from the HTML5 (W3C) specification, but it still is in the WHATWG version of HTML. It is partially implemented in most browsers, though, so is unlikely to go away.
> > However, given that a key purpose of the <hgroup> element is to affect how headings are displayed by the outline algorithm defined in the HTML specification—but the HTML outline algorithm is not implemented in any browsers—then the <hgroup> semantics are in practice only theoretical.
> > So the HTML5 (W3C) specification provides advice on how to mark up Subheadings, subtitles, alternative titles and taglines without using `<hgroup>`.

@RefaelAngelRamirez rthanks for the detailed explanation. if anyone lands here for the same purpose i've added `role="heading" aria-level="1"` indication instead.

**Comment by AndrewKushnir** [comment]
Closing this ticket based on the comments in the thread (mentioning the fact that the hgroup element has been removed from the HTML5 (W3C) specification).
