### ISSUE TITLE
NgModelGroup's control and NgModel's root are not available until after view initialization.

### ISSUE THREAD

**Issue by TrevorKarjanis** [angular/angular#38830]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/forms.

### Is this a regression?

No

### Description

NgModelGroup's control and NgModel's root are not available until after view initialization. This seems to be because the task that adds them to their parent form group is queued to be and executed after initialization ([packages/forms/src/directives/ng_form.ts](https://github.com/angular/angular/blob/master/packages/forms/src/directives/ng_form.ts#L229) lines 186 and 229). NgModelGroup's control and NgModel's correct root are not set until this time. Therefore, subscribing to observables like AbstractControlDirective.valueChanges must occur in a timeout.

## 🔬 Minimal Reproduction

[StackBlitz Example](https://stackblitz.com/edit/angular-ivy-cxehhh)

## 🔥 Exception or Error

In one use case, I am using NgModelGroup to monitor the value and status of a dynamic number of controls rather than iterate over each one.

`Error: Cannot read property 'pipe' of null`

[StackBlitz Example](https://stackblitz.com/edit/angular-ivy-s3wsan)

In a second use case, I require the root form group and valueChanges observable to implement a directive that automates cross field form validation as an alternative to group validators.

[StackBlitz Example](https://stackblitz.com/edit/angular-u4ejdx?file=src%2Fapp%2Fdirectives%2Fcross-validator.directive.ts)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.1.0
Node: 12.18.1
OS: darwin x64

Angular: 10.1.0
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1001.0
@angular-devkit/build-angular      0.1001.0
@angular-devkit/build-ng-packagr   0.1001.0
@angular-devkit/build-optimizer    0.1001.0
@angular-devkit/build-webpack      0.1001.0
@angular-devkit/core               10.1.0
@angular-devkit/schematics         10.1.0
@angular/cdk                       10.2.0
@angular/flex-layout               10.0.0-beta.32
@angular/material                  10.2.0
@ngtools/webpack                   10.1.0
@schematics/angular                10.1.0
@schematics/update                 0.1001.0
ng-packagr                         10.0.0
rxjs                               6.5.5
typescript                         3.9.5
webpack                            4.44.1
</code></pre>

## Workaround

Execute a timeout with setTimeout from ngAfterViewInit and access NgModelGroup or NgModel after their controls have been updated. Is this the recommended solution?

[StackBlitz Example](https://stackblitz.com/edit/angular-u4ejdx?file=src%2Fapp%2Fdirectives%2Fcross-validator.directive.ts)

**Comment by AndrewKushnir** [comment]
Hi @TrevorKarjanis, thanks for providing repros, this is very helpful.

I believe that the best option in your scenarios might be using Reactive Forms approach instead of a template-driven one. In this case you'll have more granular control over FormGroup and FormControls. Relying on the template-driven approach in your use-cases would require additional processing (using `setTimeout`, etc) and the final solution might be a bit more complicated. The template-driven approach covers simple use-cases and in more advanced scenarios it's easier to achieve the goal with Reactive Forms.

Thank you.
