### ISSUE TITLE
Angular Ivy causes objects not rendering correctly when implemented toString and valueOf

### ISSUE THREAD

**Issue by jmwierzbicki** [angular/angular#38839]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler

### Is this a regression?

 Yes, the previous version in which this bug was not present was: any version with IVY disabled

### Description

When IVY compiler is enabled, every object that is passed in interpollation marks tries to use .valueOf() method before .toString(), because of that it is not possible for creation of flexible objects that can take form of numbers if needed.

In previous version it was possible to create such constructions:
```
{{ testOb }} // renders 'some string'
{{ testOb + ' foo' }} //renders '0 foo'
{{ testOb.valueOf()}} // renders 0
{{ testOb++}} // renders 1 without ivy and crashes at ivy
```

Also when passing Proxy object to template, console error is thrown. like it can not find toString method at all.

## 🔬 Minimal Reproduction

examples with IVY enabled and disabled:

https://stackblitz.com/edit/angular-ivy-af1zfj?file=src%2Fapp%2Fapp.component.ts
https://stackblitz.com/edit/angular-wwwg7j?file=src%2Fapp%2Fapp.component.html

## 🌍  Your Environment

**Angular Version:**
<pre><code>

@angular-devkit/architect         0.1000.5
@angular-devkit/build-angular     0.1000.5
@angular-devkit/build-optimizer   0.1000.5
@angular-devkit/build-webpack     0.1000.5
@angular-devkit/core              10.0.5
@angular-devkit/schematics        10.0.5
@angular/cdk                      8.2.3
@angular/cli                      10.0.5
@angular/material                 8.2.3
@ngtools/webpack                  10.0.5
@schematics/angular               10.0.5
@schematics/update                0.1000.5
rxjs                              6.5.4
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Comment by pmartijena** [comment]
As a temporary fix, couldn't you cast it to a number? E.g. `Number(testOb)++`

**Comment by jmwierzbicki** [comment]
not really, we got special case in our project, that some properties in objects pulled from api might be encrypted - this is also true for whole lists. Our goal is to display data with placeholders, without breaking layouts. Solution we came with was Proxied object. With these we could pass this special object inside *ngFor, and every reference to value or string was filled with placeholders, while subproperties was generated on fly.

it worked flawlessy until we enabled angular ivy

**Comment by crisbeto** [comment]
The reason it works this way is because we convert values to strings using `'' + value` (see https://github.com/angular/angular/blob/master/packages/core/src/render3/util/misc_utils.ts#L20). We can make it work with something like `String(value)`, but we have to be very careful when changing the `renderStringify`, because every single binding in the app goes through it after every change.
