### ISSUE TITLE
Angular update from 10 to 10.1 cannot build

### ISSUE THREAD

**Issue by jecraig** [angular/angular#38847]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?

Yes, the previous version in which this bug was not present was: 10.0.14

### Description

I used the cli to update from 10.0.14 to the latest 10.1.1. Upon doing so, my build no longer works. I instead get 

ERROR in Cannot read property 'kind' of undefined

when trying to build my projects. I've tried dumping my node_modules and rebuilding them but it hasn't helped.

## 🔬 Minimal Reproduction

package.json
```
{
  "name": "aeclient",
  "version": "0.0.0",
  "scripts": {
    "try-reinstall": "npm install rimraf -g && rimraf node_modules || npm install",
    "try-install": "npm install || npm run try-reinstall",
    "setup": "npm run try-install && npm run parallel-dev",
    "setup-prod": "npm run try-install && npm run parallel-prod",
    "parallel-dev": "npx ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points && set BROWSERSLIST_ENV=modern&& npx run-p b-admin b-student b-gabby",
    "parallel-prod": "npx ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points && npx run-p prod-admin prod-student prod-gabby",
    "format": "prettier --config ./.prettierrc.json --write \"{projects,src}/**/*.{js,ts,json,scss,css,html}\"",
    "ng": "ng",
    "b-lib": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --project=aelib",
    "b-admin": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --project=aeweb-admin",
    "b-student": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --project=aeweb-student",
    "b-gabby": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --project=aeweb-gabby",
    "b-all": "npm run b-admin && npm run b-student && npm run b-gabby",
    "w-lib": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --project=aelib --watch --output-hashing=none",
    "w-admin": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --project=aeweb-admin --watch --output-hashing=none --tsConfig=\"./projects/aeweb-admin/tsconfig.app.watch.json\"",
    "w-student": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --project=aeweb-student --watch --output-hashing=none --tsConfig=\"./projects/aeweb-student/tsconfig.app.watch.json\"",
    "w-gabby": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --project=aeweb-gabby --watch --output-hashing=none --tsConfig=\"./projects/aeweb-gabby/tsconfig.app.watch.json\"",
    "t-lib": "ng test --project=aelib --browsers ChromeDebugging",
    "t-lib:quick": "ng test --project=aelib --watch=false --browsers ChromeHeadless --source-map=false",
    "t-lib:coverage": "ng test --project=aelib --watch=false --code-coverage --browsers ChromeHeadless",
    "t-admin": "ng test --project=aeweb-admin",
    "t-admin:coverage": "ng test --project=aeweb-admin --watch=false --code-coverage --browsers ChromeHeadless",
    "t-student": "ng test --project=aeweb-student",
    "t-student:coverage": "ng test --project=aeweb-student --watch=false --code-coverage --browsers ChromeHeadless",
    "t-gabby": "ng test --project=aeweb-gabby",
    "t-gabby:coverage": "ng test --project=aeweb-gabby --watch=false --code-coverage --browsers ChromeHeadless",
    "t-all": "ng test --watch=false --browsers ChromeHeadless --source-map=false",
    "l-lib": "ng lint --project=aelib",
    "l-admin": "ng lint --project=aeweb-admin",
    "l-student": "ng lint --project=aeweb-student",
    "l-gabby": "ng lint --project=aeweb-gabby",
    "l-all": "ng lint",
    "prod-lib": "npm run b-lib && cd dist/@ae/lib && npm pack",
    "prod-admin": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --project=aeweb-admin --prod",
    "prod-student": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --project=aeweb-student --prod",
    "prod-gabby": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --project=aeweb-gabby --prod",
    "prod-all": "npm run prod-admin && npm run prod-student && npm run prod-gabby",
    "check": "npm run format && npm run b-all && npm run l-all && npm run t-all"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "10.1.1",
    "@angular/cdk": "10.1.3",
    "@angular/common": "10.1.1",
    "@angular/compiler": "10.1.1",
    "@angular/core": "10.1.1",
    "@angular/forms": "10.1.1",
    "@angular/localize": "10.1.1",
    "@angular/platform-browser": "10.1.1",
    "@angular/platform-browser-dynamic": "10.1.1",
    "@angular/router": "10.1.1",
    "@fortawesome/fontawesome-pro": "5.14.0",
    "@ng-bootstrap/ng-bootstrap": "7.0.0",
    "@ng-select/ng-option-highlight": "0.0.5",
    "@ng-select/ng-select": "5.0.1",
    "@swimlane/ngx-charts": "16.0.0",
    "@uirouter/angular": "7.0.0",
    "@uirouter/core": "6.0.6",
    "@uirouter/rx": "0.6.5",
    "bootstrap": "4.5.2",
    "class-transformer": "0.3.1",
    "classlist.js": "1.1.20150312",
    "diff": "4.0.2",
    "diff2html": "3.1.12",
    "dompurify": "2.0.14",
    "fuzzysort": "1.1.4",
    "history": "5.0.0",
    "ngx-quill": "12.0.1",
    "ngx-toastr": "13.0.0",
    "overlayscrollbars": "1.13.0",
    "overlayscrollbars-ngx": "0.2.2",
    "pluralize": "8.0.0",
    "quill": "1.3.7",
    "reflect-metadata": "0.1.13",
    "resize-observer": "1.0.0",
    "rxjs": "6.6.2",
    "spacetime": "6.6.3",
    "store": "2.0.12",
    "thenby": "1.3.2",
    "ts-key-enum": "2.0.3",
    "tslib": "2.0.0",
    "wampy": "6.2.2",
    "zone.js": "0.11.1"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "9.1.0",
    "@angular-devkit/build-angular": "0.1001.1",
    "@angular-devkit/build-ng-packagr": "0.1001.1",
    "@angular/cli": "10.1.1",
    "@angular/compiler-cli": "10.1.1",
    "@angular/language-service": "10.1.1",
    "@fluffy-spoon/substitute": "1.145.0",
    "@types/diff": "4.0.2",
    "@types/dompurify": "2.0.4",
    "@types/jasmine": "3.5.14",
    "@types/jasminewd2": "2.0.8",
    "@types/node": "14.6.2",
    "@types/overlayscrollbars": "1.12.0",
    "@types/pluralize": "0.0.29",
    "@types/quill": "1.3.10",
    "@types/store": "2.0.2",
    "@types/wampy": "0.0.0",
    "codelyzer": "6.0.0",
    "jasmine-core": "3.5.0",
    "jasmine-spec-reporter": "5.0.0",
    "karma": "5.0.0",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage-istanbul-reporter": "3.0.2",
    "karma-jasmine": "3.3.0",
    "karma-jasmine-html-reporter": "1.5.0",
    "karma-jasmine-matchers": "4.0.2",
    "ng-packagr": "10.0.0",
    "npm-run-all": "4.1.5",
    "prettier": "2.1.1",
    "rxjs-tslint-rules": "4.30.1",
    "ts-node": "8.9.0",
    "tslint": "6.1.0",
    "typemoq": "2.1.0",
    "typescript": "3.9.7"
  },
  "browserslist": {
    "production": [
      "> 1%",
      "ie 10"
    ],
    "modern": [
      "last 1 chrome version",
      "last 1 firefox version"
    ]
  }
}
```

## 🔥 Exception or Error

Build Output
<pre>
C:\CodeOther\alted\d8\web\aeclient>npm run b-admin

> aeclient@0.0.0 b-admin C:\CodeOther\alted\d8\web\aeclient
> node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --project=aeweb-admin

Compiling @angular/core : es2015 as esm2015
Compiling @angular/animations : es2015 as esm2015
Compiling @uirouter/core : module as esm5
Compiling @angular/common : es2015 as esm2015
Compiling @angular/cdk/collections : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @ng-select/ng-option-highlight : es2015 as esm2015
Compiling overlayscrollbars-ngx : module as esm5
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/cdk/platform : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/cdk/bidi : es2015 as esm2015
Compiling @uirouter/angular : es2015 as esm2015
Warning: Unable to fully load C:/CodeOther/alted/d8/web/aeclient/node_modules/overlayscrollbars-ngx/ngc/src/overlayscrollbars.component.js for source-map flattening: ENOENT: no such file or directory, open 'C:/CodeOther/alted/d8/web/aeclient/node_modules/overlayscrollbars-ngx/ngc/src/overlayscrollbars.component.js.map'
Warning: Unable to fully load C:/CodeOther/alted/d8/web/aeclient/node_modules/overlayscrollbars-ngx/ngc/src/overlayscrollbars.module.js for source-map flattening: ENOENT: no such file or directory, open 'C:/CodeOther/alted/d8/web/aeclient/node_modules/overlayscrollbars-ngx/ngc/src/overlayscrollbars.module.js.map'
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/cdk/portal : es2015 as esm2015
Compiling @angular/cdk/scrolling : es2015 as esm2015
Compiling ngx-toastr : es2015 as esm2015
Compiling @ng-bootstrap/ng-bootstrap : es2015 as esm2015
Compiling @ng-select/ng-select : es2015 as esm2015
Compiling ngx-quill : es2015 as esm2015
Compiling @angular/cdk/drag-drop : es2015 as esm2015
Compiling @swimlane/ngx-charts : es2015 as esm2015

ERROR in Cannot read property 'kind' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aeclient@0.0.0 b-admin: `node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --project=aeweb-admin`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aeclient@0.0.0 b-admin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jcraig.GA\AppData\Roaming\npm-cache\_logs\2020-09-14T22_55_23_883Z-debug.log
</pre>

[2020-09-14T22_55_23_883Z-debug.log](https://github.com/angular/angular/files/5221503/2020-09-14T22_55_23_883Z-debug.log)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.1.1
Node: 12.16.3
OS: win32 x64

Angular: 10.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.12
@angular-devkit/build-angular      0.1001.1
@angular-devkit/build-ng-packagr   0.1001.1
@angular-devkit/build-optimizer    0.901.12
@angular-devkit/build-webpack      0.901.12
@angular-devkit/core               9.1.12
@angular-devkit/schematics         10.1.1
@angular/cdk                       10.2.1
@ngtools/webpack                   9.1.12
@schematics/angular                10.1.1
@schematics/update                 0.1001.1
ng-packagr                         10.0.0
rxjs                               6.6.2
typescript                         3.9.7
webpack                            4.42.0
</code></pre>

**Comment by JoostK** [comment]
Hi, you appear to be using `@angular-builders/custom-webpack` which is outdated, you're likely seeing peer dependency warning during npm install. This is known to cause issues, as it pulls in outdated versions of e.g. Angular Devkit and this may cause crashes. Please update to a version that is compatible with Angular 10.

**Comment by jecraig** [comment]
That shouldn't matter since @angular-builders/custom-webpack is only used in the test builds. Regardless, I tried updating that and got 

<pre>
An unhandled exception occurred: Cannot find module 'webpack'
Require stack:
- C:\CodeOther\alted\d8\web\aeclient\node_modules\webpack-dev-server\lib\Server.js
- C:\CodeOther\alted\d8\web\aeclient\node_modules\@angular-devkit\build-angular\node_modules\@angular-devkit\build-webpack\src\webpack-dev-server\index.js
- C:\CodeOther\alted\d8\web\aeclient\node_modules\@angular-devkit\build-angular\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\CodeOther\alted\d8\web\aeclient\node_modules\@angular-devkit\build-angular\src\browser\index.js
- C:\CodeOther\alted\d8\web\aeclient\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\CodeOther\alted\d8\web\aeclient\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\index.js
- C:\CodeOther\alted\d8\web\aeclient\node_modules\@angular\cli\models\architect-command.js
- C:\CodeOther\alted\d8\web\aeclient\node_modules\@angular\cli\commands\build-impl.js
- C:\CodeOther\alted\d8\web\aeclient\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\CodeOther\alted\d8\web\aeclient\node_modules\@angular-devkit\schematics\tools\index.js
- C:\CodeOther\alted\d8\web\aeclient\node_modules\@angular\cli\utilities\json-schema.js
- C:\CodeOther\alted\d8\web\aeclient\node_modules\@angular\cli\models\command-runner.js
- C:\CodeOther\alted\d8\web\aeclient\node_modules\@angular\cli\lib\cli\index.js
- C:\CodeOther\alted\d8\web\aeclient\node_modules\@angular\cli\lib\init.js
- C:\CodeOther\alted\d8\web\aeclient\node_modules\@angular\cli\bin\ng
See "C:\Users\jcraig.GA\AppData\Local\Temp\ng-l5N2x0\angular-errors.log" for further details.
</pre>

**Comment by petebacondarwin** [comment]
Did you completely clear out your `node_modules` when updating? There are sometime unwanted packages left lying around.

**Comment by jecraig** [comment]
Yes. I've deleted the entire node modules folder twice to see if that would clear it up.

**Comment by petebacondarwin** [comment]
To be able to help debug this problem we will need to have some kind of reproduction.

**Comment by JoostK** [comment]
That looks like a hoisting issue. Also, `@angular-devkit/build-webpack`  should typically be installed next to `@angular-devkit/build-angular`, whereas it is now installed inside of it (inferred from the `node_modules\@angular-devkit\build-angular\node_modules\@angular-devkit\build-webpack\src\webpack-dev-server\index.js` path). So it appears that there's still conflicts around Devkit versions.

What might help is throwing out package-lock.json/yarn.lock entirely. Btw, there is a `@angular-builders/custom-webpack` 10.1 beta, maybe you could see if that improves the situation.

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/18764#issuecomment-691236763 and a hand of of other issues.

**Comment by jecraig** [comment]
Rebuilding the package-lock file appears to be the solution. Thank you all.
