### ISSUE TITLE
Lazy-loaded module in new project gives "ɵɵdefineComponent is not a function" / Fixed by changing .browserslistrc

### ISSUE THREAD

**Issue by davehasagithub** [angular/angular#38865]
# 🐞 bug report

### Affected Package

 Unknown

### Is this a regression?

 Possibly. A new project created in version 9.1 does not have this issue.

### Description

I created a new project today using the following:

    ng new testapp --packageManager=yarn --skipGit=true --routing=true --style=scss
    ng generate module test --module=app --routing --route=test
    (then I emptied app.component.html and added <router-outlet></router-outlet>)
    ng build

When I visit the /test route in the _latest_ Firefox or Chrome, the developer console shows the error below. Running from the webpack dev server does not exhibit the issue.

This is strange, but I determined that the problem goes away after editing .browserslistrc to change "last 1 Chrome version" to "last 25 Chrome versions". Today this equates to Chrome versions 60-85. Using 'last 1' thru 24 all fail. It's also fixed by adding "> 0.5%". This existed in a new install with Angular 9. It seems this equates to just Chrome versions 83-85. Adding "maintained node versions" also prevents the error.

Sorry ahead of time. I'm aware this could be all my fault or maybe a bug in the browserslist library. Just seems like a brand new install would be fine and it took a long time to track down. I checked similar lazy-load examples in the tutorials and they work, but the Stackblitz projects I reviewed didn't have a browserslist file.

## 🔬 Minimal Reproduction

https://github.com/davehasagithub/ngtemp

First commit was from ng new, second from ng generate plus an updated app.component.html--that's it!

## 🔥 Exception or Error
<pre><code>ERROR Error: Uncaught (in promise): TypeError: _angular_core__WEBPACK_IMPORTED_MODULE_0__.ɵɵdefineComponent is not a function
TypeError: _angular_core__WEBPACK_IMPORTED_MODULE_0__.ɵɵdefineComponent is not a function
    at Module.K9yR (test.component.ts:8)
    at __webpack_require__ (bootstrap:84)
    at Module.NBQd (test-routing.module.ts:1)
    at __webpack_require__ (bootstrap:84)
    at Module.FScs (test.module.ts:1)
    at __webpack_require__ (bootstrap:84)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:27431)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
    at Zone.run (zone-evergreen.js:123)
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:27419)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 10.1.1
Node: 14.10.0
OS: linux x64

Angular: 10.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.1
@angular-devkit/build-angular     0.1001.1
@angular-devkit/build-optimizer   0.1001.1
@angular-devkit/build-webpack     0.1001.1
@angular-devkit/core              10.1.1
@angular-devkit/schematics        10.1.1
@ngtools/webpack                  10.1.1
@schematics/angular               10.1.1
@schematics/update                0.1001.1
rxjs                              6.6.3
typescript                        4.0.2
webpack                           4.44.1</code></pre>

**Anything else relevant?**

FWIW, I'm running the CLI in a linux VirtualBox in a synced folder and the browser in the Windows host.

**Comment by jelbourn** [comment]
Closing this since it seems to have been an environment issue rather than a framework bug.

**Comment by davehasagithub** [comment]
To be clear, non-prod Angular builds require the UTF-8 character set. Prod builds do not. This requirement is not documented and the error it causes is not helpful.
