### ISSUE TITLE
How to access all nested `routes: Routes` in Angular using a reference to the `Router` object?

### ISSUE THREAD

**Issue by i-kapri** [angular/angular#38867]
Hi there! I am creating a service method which is supposed to access all of the `routes: Routes` arrays (in case there are nested routes).

# 🚀 It would be better to access child routes through loadChildren for lazy-loaded modules.

### Description

My function inside my service class is as follows:

```typescript

...

public get routes(): FatherRoute[] {
   const routes = this.router.config;
   const fathers: FatherRoute[] = [];
   for (const route of routes) {
         fathers.push({
            path: route.path,
            children: this.getChildren(route)
         });
   }
   return routeDetails;
}

private getChildren(fatherRoute: Route): ChildRoute[] {
   const children: ChildRoute[] = [];
   Promise.resolve((fatherRoute as any)._loadedConfig).then(child => {
      child.routes.forEach((route: Route) => {
         children.push({
            path: route.path
         });
      });
   }
}
...

```

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
