### ISSUE TITLE
will facade be exposed on the angular2 public namespace?

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#3886]
Right now most of the things we need to write an app we can just import them from `angular2/angular2`, but there are some useful things under the facade like `isFunction`, `isBlank` and so on.

Are there any plans on exposing all of those things in the facade folder on the `angular2/angular2` namespace?

**Comment by pkozlowski-opensource** [comment]
Most probably not. Facades are here to abstract JS / Dart differences. We don't want to be in business of providing general helper functions as there are already plenty of libraries that do just that in a generic manner. Facades are minimal and for internal use - we don't want to grow those to sth generic as not to add too many bytes to the framework.

**Comment by rolandjitsu** [comment]
@pkozlowski-opensource makes sense, I was just curious what were the plans for it.
