### ISSUE TITLE
SwUpdate.available does not fire in chrome (desktop) anymore

### ISSUE THREAD

**Issue by Benny739** [angular/angular#38877]
Hi,

when we upgraded from 10.0 to 10.1 we observed that SwUpdate.available does not fire anymore on chrome desktop.
We tested v83, v85 and v86. Chrome on android still fires, safari fires, firefox fires.
Updates are getting installed, just the observable does not emit anymore.

**Comment by gkalpak** [comment]
@Benny739, I just tried it on a new CLI app using v10.1.1 and it works as expected.
This means that the problem you are seeing is probably caused (partly?) by something in your application code. Could you share an (ideally minimal) reproduction?

**Comment by Benny739** [comment]
Sorry for the wrong bug report. Somehow the service worker in our staging environment became corrupted. After clearing all application data it started working correct again. I have no idea how the service worker could become corrupted. So sorry again for the wrong bug.

**Comment by gkalpak** [comment]
No worries. Glad you sorted it out.
