### ISSUE TITLE
Create examples for best practices documentation

### ISSUE THREAD

**Issue by kapunahelewong** [angular/angular#38873]
# 📚 Docs or angular.io bug report

### Description

Per @aikidave's request, we should create working examples that demonstrate best practices for the best practices documentation. Original request is in this comment:  https://github.com/angular/angular/pull/38799#discussion_r488950859

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by cesperian** [comment]
@aikidave let me know if I can help with this
