### ISSUE TITLE
DOM should be exposed under test_lib

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#3887]
Right now if I want to do some DOM operations during unit tests I have to import `DOM` from `angular2/src/dom/dom_adapter`, wouldn't it make sense to expose `DOM` under a different name (`MockedDOM` or something) under `angular2/test_lib` since the only place `DOM` will be used by end users will be in tests?

**Comment by pkozlowski-opensource** [comment]
I've got an impression that you are trying to use our DOM facade as an utility library. AFAIK, this is not the intent of this abstraction. If you are after queering DOM in tests, why not use DOM API directly or even jQuery?

**Comment by rolandjitsu** [comment]
@pkozlowski-opensource you can see how I use `DOM` [here](https://github.com/rolandjitsu/ng2-play/blob/master/src/common/icon.spec.ts) and [here](https://github.com/rolandjitsu/ng2-play/blob/master/src/app/directives/logo.spec.ts#L84).

**Comment by pkozlowski-opensource** [comment]
@rolandjitsu from what you can see you are using 2 methods:
* `DOM.querySelector`
* `DOM.createElement` 

You can safely replace those with built-in browser, native implementations. ng2 facade doesn't add anything here, it is a simple proxy: https://github.com/angular/angular/blob/be0739085976bbdbcf8f560475e87b07343f464d/modules/angular2/src/core/dom/browser_adapter.ts#L177

I'm going to go ahead and close this one as I don't believe we want to have this DOM facade as a public API for testing. It doesn't provide any value for tests and would only increase API surface.

**Comment by rolandjitsu** [comment]
@pkozlowski-opensource I was just worried that the native implementations will fail and that the use of `DOM` was intended to fix that.

Thanks for clearing that out :)
