### ISSUE TITLE
Pull request finally resolved, issues properly looked at, and clear plan for development clear for everyone

### ISSUE THREAD

**Issue by criskrzysiu** [angular/angular#38879]
Hi I have a request!

The way Angular is being maintained now it's getting more and more behind other frameworks.
Just look at the number of issues and pull request that are swept under the rug. 
Also there is no public plan on where angular is heading in it's development. What features are currently worked at. 
Just compare Angular to TS development. In TS 4.1 there is a clear plan, features worked on are clear for everyone and in Angular it's basically a secret that only Angular teams seems to know. 

As example let's look at typed forms and actually better reactive forms handling. It have been requested for years and nothing is happening in that regard. 

I feel like Angular is open source project but people have basically nothing to say apart form issuing bug reports.

So my request is: Create a page that will show clearly where angular is heading and what is currently worked on and what's next in line.

**Comment by mlc-mlapis** [comment]
### [**@criskrzysiu https://angular.io/guide/roadmap**](https://github.com/criskrzysiu)

**Comment by petebacondarwin** [comment]
Well said @mlc-mlapis - thanks.

@criskrzysiu - I think what this indicates is that we need to do a better job of communicating these plans.

**Comment by sonukapoor** [comment]
> @criskrzysiu - I think what this indicates is that we need to do a better job of communicating these plans.

I think the link to the roadmap should be on the homepage as well as in the top navigation.

**Comment by criskrzysiu** [comment]
@mlc-mlapis  @petebacondarwin the issue is that for example, yes there is a point - Operation Bye Bye Backlog - but there is no clear indications which issues are worked on. Again look at TS https://github.com/microsoft/TypeScript/issues/40124 here everything is clear. You can look at bullet points, features, issues and more - track those back to pull requests and discussion. I think that's what's missing.  Make it more transparent. At least that's my point of view on that.
