### ISSUE TITLE
Change code new Event in documentation error in Angular aio

### ISSUE THREAD

**Issue by renatodysouza** [angular/angular#38880]
In Angular testing-attribute-directives in app/shared/highlight.directive.spec.ts (selected tests) in this part of code is wrong.
url: https://angular.io/guide/testing-attribute-directives

 // dispatch a DOM event so that Angular responds to the input value change.
  input.value = 'green';
  input.dispatchEvent(newEvent('input'));
  fixture.detectChanges();

Should be  input.dispatchEvent(new Event('input'));  and not  input.dispatchEvent(newEvent('input'));

**Comment by sonukapoor** [comment]
`newEvent` is actually coming from here:

https://github.com/angular/angular/blob/dd8d8c828998fc62aad253bcb296174aee4a2aa0/aio/content/examples/testing/src/testing/index.ts#L17-L27

I guess the name `newEvent` is indeed a little bit confusing. 
Maybe @gkalpak can weigh in on this on how we can change it.

**Comment by gkalpak** [comment]
Oh, we were supposed to have gotten rid of the `newEvent()` helper with #37251. Somehow it had slipped through the cracks.
I'll rebase it and fix it up and we can hopefully merge it soon.

Thx for bringing it up, @renatodysouza and @sonukapoor for bringing it to my attention.
I'll go ahead and close this. Please follow #37251 for updates/ongoing discussion.
