### ISSUE TITLE
ChangeDetectorRef in Pipe used in Input resolves to wrong Components Instance

### ISSUE THREAD

**Issue by nrauschcom** [angular/angular#38883]
# 🐞 bug report

### Is this a regression?

The same code worked for me in 9.x

### Description

I'm using ChangeDetectorRef in one of my Pipes. When used in the Input of a custom Component, CHangeDetectorRef resolves to that component instead of the hosts template.
```html
<hwe-rte-viewer [value]="description$ | async"
  [disabled]="(generalDisabled$ | async) || !([hasPermission$, 'WRITE'] | fnCall | async)"
  (onStartEditing)="onStartEditing($event)"
  (update)="onEditDescription($event)"
  editButtonTooltip="{{'PROPERTIES.GENERAL.DESCRIPTION_EDIT' | translate}}">
</hwe-rte-viewer>
```
The FnCallPipe gets the folowing ChangeDetectorRef:
![image](https://user-images.githubusercontent.com/1051009/93484920-c8a92300-f902-11ea-8aef-5abd21c63111.png)
As you can also see (L156), the code is generated as `ɵɵdirectiveInject(ChangeDetectorRef)` instead of `ɵɵinjectPipeChangeDetectorRef()`

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-8x6a4f

You can see, it works with uncompiled code, but not with the included library ngx-function-expression, which uses cdRef exactly like the TestPipe. Thus, the compilation/ngcc process of the library causes this issue.

## 🌍  Your Environment

**Angular Version:**
<pre>
<code>@angular-devkit/architect         0.1001.1
@angular-devkit/build-angular     0.1001.1
@angular-devkit/build-optimizer   0.1001.1
@angular-devkit/build-webpack     0.1001.1
@angular-devkit/core              10.1.1
@angular-devkit/schematics        10.1.1
@angular/cdk                      10.2.0
@angular/flex-layout              9.0.0-beta.31
@angular/material                 10.2.0
@ngtools/webpack                  10.1.1
@schematics/angular               10.1.1
@schematics/update                0.1001.1
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

## Related Issues

#33677 (closed and fixed)

**Comment by JoostK** [comment]
Uh oh, I think this broke in #38666 (10.1.1) :(
