### ISSUE TITLE
Angular 9 Application Not running on IE11

### ISSUE THREAD

**Issue by MVeerarouth** [angular/angular#38895]
We at our organization have tried adding polyfills and changing the ES version on tsconfig file, this helped us to get our angular application working in Production.

However when we try to get the application working on Development environment it doesn't support.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
