### ISSUE TITLE
@ViewChild injection for dynamic created components with shared baseline class does not work anymore (Angular 9/10)

### ISSUE THREAD

**Issue by jenshildebrand** [angular/angular#38918]
@ViewChild injection for dynamic created components with shared baseline class does not work anymore (Angular 9/10), in Angular 8 it was working.

The attached project illustrates the issue as demo including description and class/component diagram (see readme.txt and startup.txt). The project can be setup via maven. The default configuration is for Angular 9 but there are also package.json files for Angular 8 and 10.

[angular-v9-view-child-injection-issue.v20200921-0900.zip](https://github.com/angular/angular/files/5253887/angular-v9-view-child-injection-issue.v20200921-0900.zip)

**Comment by AndrewKushnir** [comment]
@jenshildebrand, could you please create a repro using [StackBlitz](https://stackblitz.com/), so that we can have a look? Please include only the minimum required code to illustrate the issue - that'd help investigate the problem.

**Comment by jenshildebrand** [comment]
Hi,

please refer to attached zip file 
(angular-v9-view-child-injection-issue.v20200921-0900.zip). It's a maven 
project that fully initializes itself (see: startup.txt). I also included 
package.json files for angular 8 (working), 9+10 (not working). In assets 
and running demo you will also find a diagram 
(angular-v9-view-child-injection-issue.png) illustrating the component 
structure (since it was quite tricky to reproduce the issue).

Mit freundlichen Grüßen
Best regards
Jens Hildebrand


Jens Hildebrand
Software Engineer

IAB

SYSTEMA Systementwicklung Dipl.-Inf. Manfred Austen GmbH|Manfred-von-Ardenne-Ring 6|01099 Dresden
HRB 5422 Amtsgericht Dresden | USt.-ID DE 159 607 786
Geschäftsführer Manfred Austen

P   +49 +49 351 / 88 24 679
M  +49 
F   +49 





Von:    "Andrew Kushnir" <notifications@github.com>
An:     "angular/angular" <angular@noreply.github.com>
Kopie:  "jenshildebrand" <jens.hildebrand@systemagmbh.de>, "Mention" 
<mention@noreply.github.com>
Datum:  28.10.2020 21:12
Betreff:        Re: [angular/angular] @ViewChild injection for dynamic 
created components with shared baseline class does not work anymore 
(Angular 9/10) (#38918)



@jenshildebrand, could you please create a repro using StackBlitz, so that 
we can have a look? Please include only the minimum required code to 
illustrate the issue - that'd help investigate the problem.
?

**Comment by AndrewKushnir** [comment]
@jenshildebrand thanks for providing additional details.

Unfortunately we won't be able to run your project locally. In order for us to investigate the problem further, we'd need a simpler repro (minimum possible setup to illustrate the issue) in a form of GitHub repo (simple Angular app created via CLI + custom configuration if it's a compiler-related issue) or a page on [StackBlitz](https://stackblitz.com/).

I will close this ticket for now, feel free to create a new one once a minimal repro is available.

Thank you.
