### ISSUE TITLE
Problem in docs of CanActivate

### ISSUE THREAD

**Issue by pasha-bolokhov** [angular/angular#38910]
# 📚 Docs or angular.io bug report

### Description
`See more...` seems to be doing the wrong thing. It normally means it's going to expand something and show more text. On this page, however, it's just an anchor which bounces you down a paragraph
https://angular.io/api/router/CanActivate

**Comment by aikidave** [comment]
Hi @pasha-bolokhov! Thanks for filing this. I've added it to our priority list so we can look into address this issue!

**Comment by aikidave** [comment]
@pasha-bolokhov Thank you for submitting this! I've added it to our priority list and we'll look into how to address this.

**Comment by JoostK** [comment]
This seems to be intended behavior looking at the source:

https://github.com/angular/angular/blob/2843f15e8c30faf6e396413356936295cfe7a141/aio/tools/transforms/templates/api/export-base.template.html#L6

@aikidave WDYT?

**Comment by pasha-bolokhov** [comment]
That may be, you'd guys name it differently then… "See more..." with dots is normally associated with an expandable section, even if it's not written in Material Design specs. If you want the user to jump to the Description section, maybe just name it "Jump to description", or something along these line.

**Comment by aikidave** [comment]
It may be intended behavior, but I don't think it's the right behavior. We definitely need to look more closely at how we display our API content. 

@pasha-bolokhov , I apologize that I've not been able to get to this issue. I assure you, however, that I haven't forgotten!

**Comment by atscott** [comment]
We've re-evaluated this issue and, while we appreciate the feedback, we're going to keep the `See Also...` behavior as-is for now. Thanks for bringing this to our attention, however!
