### ISSUE TITLE
Doc: Heroes Tutorial with Persistence through REST and GraphQL backend endpoint

### ISSUE THREAD

**Issue by darkn3rd** [angular/angular#38915]
# 🚀 feature request

### Relevant Package

https://angular.io/tutorial

### Description

This is enhancement request for a part2 of the heroes tutorial to have a simple back-end that can store/retrieve heroes. 

### Describe the solution you'd like

I would like to have a part 2 of Tour of Heroes to have persistence (save heroes) using REST or GraphQL API.  As a newbie, I am a little fuzzy to work with state. 

### Describe alternatives you've considered

Others have made attempts to do this, but often they don't update their repos, the APIs get out of sync, and it is hard to use/parse for newbies.

**Comment by AndrewKushnir** [comment]
@darkn3rd thanks for the proposal. It looks like it's outside of the scope of the tutorial, so I will close this ticket for now and we'll get back to that topic in case we have more requests to extend the tutorial with a similar information. Thank you.
