### ISSUE TITLE
Required validator shows failed validation when input set to "0"

### ISSUE THREAD

**Issue by dpsthree** [angular/angular#3892]
Given the following input:

```HTML
<input ng-control="mixedstring" [(ng-model)]="inputs.mixedstring" required>
```

Setting the value of inputs.mixedstring = 0 to initialize the field results in the required validator marking this input as invalid. Typing the value into the input does not.

Subsequent attempts to assign the value 0, such as a reset button also result in an incorrect validation result.

**Comment by vicb** [comment]
Can not reproduce with the template_driven_form example which looks similar.

Could you please provided more details on your environment and ideally a plunker ?

**Comment by mhevery** [comment]
stale
