### ISSUE TITLE
Debounce individual form controls

### ISSUE THREAD

**Issue by Airblader** [angular/angular#38936]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/forms.

### Description

In complex forms it can be necessary to react to value changes to update some state (e.g. when some JSON/YAML configuration can be shown both in a JSON/YAML editor ("advanced view") and individual form controls and they need to be synced up). However, checkboxes or select inputs are inherently different from text inputs in one specific way: frequency of value changes, with the latter receiving significantly more.

Therefore it would be nice if individual form controls could easily be debounced such that their valueChange emits less frequently. This is opposed to debouncing the entire FormGroup's valueChange which would unnecessarily debounce these other controls as well.

I maintain a library, [ngqp](https://github.com/TNG/ngqp) which uses the forms infrastructure to wire up form controls with query parameters, and there I have this feature implemented and got the inspiration from to make this feature request.

### Describe the solution you'd like

An addition to AbstractControlOptions such that this can be done:

```
formBuilder.control('', {debounceTime: 100});
```

### Describe alternatives you've considered

Technically this can already be achieved by splitting the valueChange observable using distinctUntilChanged etc. and merging it back, but that requires quite a bit of effort. If this could be a configuration on the form control itself, however, users would have a simple, declarative solution.

---

This request is related to and possibly a duplicate of #19705, but that request is specifically about template-driven forms while I am focusing on reactive forms here.

**Comment by Airblader** [comment]
On a side note, I realize that with the current implementation this is likely far from trivial as forms are internally not built in a very reactive manner, as such this may be something to consider in a bigger picture as the current long-term roadmap item of improving typing in forms.

**Comment by SebastianStehle** [comment]
I think it is related to my feature request: https://github.com/angular/angular/issues/39014
