### ISSUE TITLE
Extract i18n strings from TypeScript

### ISSUE THREAD

**Issue by Arackow** [angular/angular#38942]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/localize

### Description
There are times when it would be much cleaner for my team to be able to translate strings in the TypeScript code and display them in the HTML. While $localize lets you do the translation you cannot extract them from the file itself so the same text must be either somewhere in your HTML or added manually.

### Describe the solution you'd like
ng xi18n should be able to extract at least simple text strings from typescript files as it does with HTML

### Describe alternatives you've considered
The only work around I have is setting up a display=none block of code in my HTML for possible strings to live so they get extracted properly.

**Comment by petebacondarwin** [comment]
This is possible now, but hidden behind a flag until 11.0.0 is released. Just run

```bash
ng xi18n --ivy
```

And it will extract the messages from the `$localize` tagged strings in your application code.

Closing as this feature is already available. If I have misunderstood your request please re-open.

**Comment by Arackow** [comment]
@petebacondarwin Ah perfect! thank you!
