### ISSUE TITLE
new FormControl({value: <value>}) syntax is broken

### ISSUE THREAD

**Issue by maeb** [angular/angular#38946]
This line
https://github.com/angular/angular/blob/b1682526ddcbde922d07b07d82727366ddf5bf00/packages/forms/src/model.ts#L1314

Should be like this line
https://github.com/angular/angular/blob/b1682526ddcbde922d07b07d82727366ddf5bf00/packages/forms/src/model.ts#L1310

Note the missing `.value` in the first example.

Expected value of `aKey` after `this.formBuilder.group({aKey: {value: []}})` is `[]`, but the actual value is `{value: []}`.

**Comment by JoostK** [comment]
This seems to be working as expected. The `{ value: [] }` initializer is not interpreted as a boxed configuration object, as the `disabled` property is required. The syntax is a bit ambiguous, so to minimize any conflicts it is required that a boxed object has exactly `value` and `disabled` properties, nothing less and nothing more.

**Comment by maeb** [comment]
Ok. Thanks for the quick response. I now see it is documented in the second example in the usage notes: https://angular.io/api/forms/FormControl.
