### ISSUE TITLE
router.url variable updates even if skipLocationChange = true

### ISSUE THREAD

**Issue by Yohandah** [angular/angular#38949]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

No

### Description

If you navigate from `/firstPage/xx/yy` to `/secondPage/xx/yy` using ` this.router.navigateByUrl("/secondPage/xx/yy", { skipLocationChange: true })` options, then `this.router.url` variable will be updated to `/secondPage/xx/yy` while it should stay `/firstPage/xx/yy`.

If this is intended behavior where can I find the "real" url : `/firstPage/xx/yy` ? 
The only way I found is `import { Location } from "@angular/common"; this.location.path()` but is that the right way to do it ?

## 🔬 Minimal Reproduction
Open the stackblitz below, click "navigate" button. See in the url it's still /login but router.url returns /home

https://stackblitz.com/edit/angular-router-bug-skiplocation?file=app/app.component.ts

**Comment by atscott** [comment]
Yes, this is working as intended. `skipLocationChange` "When true, navigates without pushing a new state into history." This means simply that the browser URL won't update. The internal state of the router still keeps track of what the current page really is.
