### ISSUE TITLE
Add UrlTree utilities/helpers to public API

### ISSUE THREAD

**Issue by zelliott** [angular/angular#38951]
# Add UrlTree utilities/helpers to public API

### Relevant Package

Latest

### Description

Angular has a number of internal `UrlTree` helpers for creating trees/segment groups/segments, comparing segments/paths, checking if one tree is contained within another, etc. [This file has some examples of such helpers](https://github.com/angular/angular/blob/1801d0c6500ea5e677e753fbcfb73dbd3675f054/packages/router/src/url_tree.ts). It would be helpful if these were exposed as part of Angular's public API as a collection of utilities for working with `UrlTrees`.

### Describe the solution you'd like

I'm not entirely sure what the solution would look like, but potentially a new import path (e.g. `@angular/router/utils`, `@angular/router/urls`) with just a bunch of small exported helpers.

### Describe alternatives you've considered

Currently I've been copying many of these utilities within my own codebase, but it would be nice if I could import them directly from Angular.

**Comment by atscott** [comment]
Closing due to the insufficient votes _but_ this change will likely be required in order to achieve #42953
