### ISSUE TITLE
how to use material lib components in lazyload routing modules?

### ISSUE THREAD

**Issue by kagaricyan** [angular/angular#38967]
forExample,using this project,address: https://angular.cn/generated/live-examples/lazy-loading-ngmodules/stackblitz.html;
 I want to use official material lib component in project's CustomersComponent。what should i do?
i'm facing this error:
 1. If 'mat-slider' is an Angular component, then verify that it is part of this module.
 2. If 'mat-slider' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
the angular version is 10

**Comment by Totati** [comment]
Hi, you should import the `MatSliderModule` in your `CustomersModule`

**Comment by kagaricyan** [comment]
> Hi, you should import the `MatSliderModule` in your `CustomersModule`

i did this,but in angular version 10 it don;t work; 
this project https://angular.cn/generated/live-examples/lazy-loading-ngmodules/stackblitz.html; is angular 9 it'works,but my local project is verison 10.

**Comment by kagaricyan** [comment]
> Hi, you should import the `MatSliderModule` in your `CustomersModule`

thx. I found my mistake. i should import module rather then module's routing in root routing.module
