### ISSUE TITLE
Injectable decorator not recognized when used with custom decorator

### ISSUE THREAD

**Issue by splincode** [angular/angular#38966]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/compiler

### Is this a regression?

Yes, since everything worked fine in previous versions (Angular 8, Angular 9)

### Description

In my projects I use decorators and now for some reason the error is constantly shown, what does this mean and how to get around it? Is this a bug in Angular? The decorator is ordinary and made according to the TypeScript guide

```ts
import { Component, VERSION, Injectable } from '@angular/core';

// simple example
export function Decorator(): any {
    return function <T extends any>(parent: any) {
        return class extends parent {
            constructor(...args: any[]) {
                super(...args);
            }
        };
    };
}

@Decorator()
@Injectable()
class MyService {
  public world() {
    return 'world';
  }
}

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ],
  providers: [MyService]
})
export class AppComponent  {
  name = 'Angular ' + VERSION.major;

  constructor(private my: MyService){
    console.log('hello', my.world())
  }
}
```

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/token-invalid?file=src/app/app.component.ts

## 🔥 Exception or Error
<pre><code>
DEPRECATED: DI is instantiating a token "" that inherits its @Injectable decorator but does not provide one itself.
This will become an error in a future version of Angular. Please add @Injectable() to the "" class.
</code></pre>

## 🌍  Your Environment

**Angular Version:**

Angular 10.1

**Comment by ulrikwalter** [comment]
Use the Injectable decorator for the returned new class in own Decorator. For example:

```ts
import { Component, VERSION, Injectable, InjectableProvider, Type } from "@angular/core";

export function Decorator(injectionOptions?: {
        providedIn: Type<any> | 'root' | 'platform' | 'any' | null;
    } & InjectableProvider): any {
  return function<T extends any>(stateClass: any) {
    class DecoratedClass extends stateClass {
      constructor(...args: any[]) {
        super(...args);
      }
    };
    return Injectable(injectionOptions)(DecoratedClass);
  };
}

@Decorator({ providedIn: 'root' })
export class MyService {
  public world() {
    return "world";
  }
}

@Component({
  selector: "my-app",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
  //providers: [MyService],
})
export class AppComponent {
  name = "Angular " + VERSION.major;

  constructor(private my: MyService) {
    console.log("hello", my.world());
  }
}

```

**Comment by splincode** [comment]
@ulrikwalter  if I build the project locally

![image](https://user-images.githubusercontent.com/12021443/100525985-e8e44080-31d5-11eb-85a4-18d053d19429.png)

**Comment by ulrikwalter** [comment]
@splincode it works for me. Check angular versions. 

https://stackoverflow.com/questions/60690670/uncaught-in-promise-error-angular-jit-compilation-failed-angular-compiler

**Comment by splincode** [comment]
I have Angular 11 and Ivy enabled

**Comment by ulrikwalter** [comment]
Is it a new (empty) ng project?

**Comment by splincode** [comment]
Yes

**Comment by tonivj5** [comment]
I think the question here is if we are going to be able to decorate our classes with custom decorators and at the same time be able of use `@Injectable()`. What are the future plans? I'd like to know this

My use case is to mark a class as final:
```ts
export function Final<T extends new (...args: any[]) => Record<any, any>>(target: T): T {
  return class FinalKlass extends target {
    constructor(...args: any[]) {
      if (new.target !== FinalKlass) {
        throw new Error(`Cannot extend a final class "${target.name}"`);
      }
      super(...args);
    }
  };
}

@Final
@Injectable()
export class NotExtensibleService { }
```

**Comment by splincode** [comment]
@petebacondarwin @JoostK what do you think about?

**Comment by petebacondarwin** [comment]
I'll ask the others....

**Comment by martinbojnansky** [comment]
I am experiencing the same problem, however, the bigger issue than warning itself is that such a usage of custom decorator ends up without injected dependencies in test environment.

Is it me, or should this be supported use case?

```
export const View = () => {
  return <T extends new (...args: any[]) => OnInit & OnDestroy & WithChangeDetector>(constructor: T ) => {
    const unsubscriber = new ObservableUnsubscriber();

    return class extends constructor {
      constructor(...args: any[]) {
        super(...args);

        const ngOnInit = constructor.prototype.ngOnInit;
        constructor.prototype.ngOnInit = () => {
          ...
          ngOnInit.apply(this);
        };

        const ngOnDestroy = constructor.prototype.ngOnDestroy;
        constructor.prototype.ngOnDestroy = () => {
          unsubscriber.destroy();
          ngOnDestroy.apply(this);
        };
      }
    };
  };
};
```

**Comment by tomstolarczuk** [comment]
For anybody still interested, this works:

```typescript
export function Decorator(): <T extends new (...args: any[]) => any>(target: T) => T {
  return function decorator<T extends new (...args: any[]) => any>(target: T): T {
    @Injectable()
    class Decorated extends target {
      // do something with decorated class
    }

    return Decorated;
  };
}
```

**Comment by splincode** [comment]
@tomstolarczuk more examples please)

**Comment by tomstolarczuk** [comment]
@splincode updated my previous comment - not much added to be honest.

**Comment by bvandermeide** [comment]
> For anybody still interested, this works:
> 
> ```ts
> export function Decorator(module: string): <T extends new (...args: any[]) => any>(target: T) => T {
>   return function decorator<T extends new (...args: any[]) => any>(target: T): T {
>     @Injectable()
>     abstract class Decorated extends target {
> 	  someProp = 'someProp';
>       // do something with decorated class
>     }
>     return Decorated;
>   };
> }
> 
> 
> @Injectable({
>   providedIn: 'root'
> })
> @Decorator()
> export class SomeApiService {
>   constructor(private http: HttpClient) {}
> 
>   someMethod(params: any): void {
>     console.log(this.someProp);
>   }
> }
> ```
> 
> Tested on Angular 12.

You may receive the following error if you try to apply constructor logic

`Uncaught (in promise): Error: This constructor was not compatible with Dependency Injection.
Error: This constructor was not compatible with Dependency Injection.`

If you need to do constructor initialization logic, I found the following to work well.

```ts
    abstract class Decorated extends target {
      constructor(...args) {
        super(...args);
        someProp = 'someProp';
      }
    }

    @Injectable()
    class Decorated_Injectable() extends Decorated { }

    return Decorated_Injectable;
```

**Comment by mkurcius** [comment]
As mentioned here: https://stackoverflow.com/a/53622493/4663231
Proxy and Reflect.construct can be used:

```typescript
export function MyDecorator() {
  return (target: any) => {
    return new Proxy(target, {
      construct(clz, args) {
        console.log('before constructor');
        const obj = Reflect.construct(clz, args);
        console.log('after constructor');

        return obj;
      },
    });
  };
}

@MyDecorator()
@Injectable({ providedIn: 'root' })
export class MyClass {
  constructor(@Inject(DOCUMENT) private document: Document) {
    console.log('Impl (constructor)');
    console.log('document', this.document);
  }
}

@Injectable({ providedIn: 'root' })
export class MyService {
  constructor(private myClass: MyClass) {
    console.log('myClass', this.myClass);
  }
}
```

and the output is:
![result](https://user-images.githubusercontent.com/1613212/144681970-686287cd-959d-46b4-826d-c6214695f55f.png)

as you can see:
1. DI works without `@Injectable` inside custom decorator
![result -DI](https://user-images.githubusercontent.com/1613212/144682226-a1030b7e-136f-454d-9461-d70d51e3b7ae.png)

2. returned class is the original one (not wrapped)
![result -class](https://user-images.githubusercontent.com/1613212/144682256-edb2a00d-1502-484d-8b1e-843b4d463881.png)

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
