### ISSUE TITLE
Unit test doesn't fail even if Error is thrown during cleanup

### ISSUE THREAD

**Issue by bertrandE** [angular/angular#38971]
# 🐞 bug report

### Affected Package
The issue is caused by package **@angular/core**

### Is this a regression?
Not sure but it's a problem since at least Angular 8.

### Description
Suppose you have an application with a component that implements the `ngOnDestroy` method:

`ngOnDestroy(): void {
    console.log(this.foo.bar);
}`

Also, suppose that `this.foo === undefined` when `ngOnDestroy` is called during the execution of the unit tests. It will logically output a TypeError.

The problem is that the test that logs this error **does not fail**.  There is obviously something that went wrong during the cleanup of the component, I would expect my test to fail.

The problem is that such errors are catched but nothing is done with them apart from logging the error:
https://github.com/angular/angular/blob/master/packages/core/testing/src/test_bed.ts#L336

Is this behaviour expected? If so is there another way to fail the test when such an error is thrown?

## 🔬 Minimal Reproduction
See the following repo:
https://github.com/bertrandE/app-repro

Just run `ng test` in order to reproduce.

## 🔥 Exception or Error
<pre><code>
ERROR: 'Error during cleanup of component', Object{component: AppComponent{title: 'app-repro', __ngContext__: [...]}, stacktrace: TypeError: Cannot read property 'bar' of undefined
TypeError: Cannot read property 'bar' of undefined
    at AppComponent.ngOnDestroy (http://localhost:9876/_karma_webpack_/src/app/app.component.ts:15:26)
    at executeOnDestroys (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9070:1)
    at cleanUpView (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:8992:1)
    at destroyViewTree (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:8801:1)
    at destroyLView (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:8945:1)
    at RootViewRef.destroy (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9679:1)
    at ComponentRef$1.destroy (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:22234:1)
    at ComponentFixture.destroy (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:330:1)
    at http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:2052:1
    at Array.forEach (<anonymous>)}
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
      _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.3
Node: 12.18.3
OS: darwin x64

Angular: 10.1.2
... core
Ivy Workspace: Yes

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1001.3
@angular-devkit/build-angular       0.1001.3
@angular-devkit/core                10.1.3
@angular-devkit/schematics          10.1.3
@angular/animations                 10.1.3
@angular/cli                        10.1.3
@angular/common                     10.1.3
@angular/compiler                   10.1.3
@angular/compiler-cli               10.1.3
@angular/forms                      10.1.3
@angular/platform-browser           10.1.3
@angular/platform-browser-dynamic   10.1.3
@angular/router                     10.1.3
@schematics/angular                 10.1.3
@schematics/update                  0.1001.3
rxjs                                6.6.3
typescript                          4.0.3
</code></pre>

**Anything else relevant?**
No.

**Comment by atscott** [comment]
Looks like the `try...catch` was added in https://github.com/angular/angular/commit/2c5a67134198a090a24f6671dcdb7b102fea6eba but it's not clear why. Potentially it was to ensure every active fixture got destroyed even if an error was thrown. A different approach could be to still `try...catch` but throw an error at the very end if one of the `destroy` calls threw. 

This would certainly be a breaking change to address (tests which previously threw during cleanup would start to fail) and we'd have to determine if this makes sense to change now ([experimental presubmit](https://test.corp.google.com/ui#id=OCL:338322476:BASE:338288991:1603310398676:f3375a77)).

As an alternative, if you want to have your test fail if there is an error during cleanup, you could spy on the `console.error` and watch for calls to that and fail the test if there are any.

**Comment by JoostK** [comment]
This can now be configured using [ModuleTeardownOptions.rethrowErrors](https://angular.io/api/core/testing/ModuleTeardownOptions) in `TestBed.initTestEnvironment`.
