### ISSUE TITLE
Update content about view encapsulation to ensure it is concise, clear and correct.

### ISSUE THREAD

**Issue by aikidave** [angular/angular#38987]
# 📚 Docs or angular.io bug report

### Description
The content for view encapsulation has not been reviewed in some time. We need to verify that it contains up to date and complete information.

### What's the affected URL?**
If https://github.com/angular/angular/pull/38986 moves through, it is angular.io/guide/view-encapsulation.

Otherwise, it's angular.io/guide/component-styles#view-encapsulation.

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by petebacondarwin** [comment]
I reviewed the guide and it is up to date.
