### ISSUE TITLE
i18n ID generation should ignore inner HTML tag attributes and interpolation content

### ISSUE THREAD

**Issue by Goodwine** [angular/angular#38980]
# 🚀 feature request

### Relevant Package
- @angular/core
- i18n

### Description
Let's imagine the following snippet:
```html
<button i18n="...">
  <icon value="notebook"></icon>
  Edit {{ 1 + 1 // i18n(ph="number") }}
</button>
```

The generated message would _look like_:
`[ICON_TAG_START][ICON_TAG_END] Edit [NUMBER]`

Therefore if I modify the icon `value` to say... "pencil", I expect my localization not to be affected, however at this time, Angular i18n considers _all_ the inner HTML contents to generate, this means that `<icon value="notebook"></icon>` is used to generate the ID when it doesn't actually (in most cases) affect localization.

_The same is true for interpolation._ For example, If I change `{{ 1 + 1 // i18n(ph="number") }}` to `{{1+1 // i18n(ph="number")}}`, where the contents didn't even change semantics, the whitespaces just got removed.

**Note:**
This is slightly related to the Issue about whitespaces such as indentation affecting localization
Issue: https://github.com/angular/angular/issues/13114

### Describe the solution you'd like
As stated above, I would like that Angular would generate the localization ID based of a normalized string instead of the inner HTML.

The normalized string would mean:
- whitespace is normalized (unrelated to this report, but still important)
- transform inner HTML tags into the respective placeholder (e.g. `<icon></icon>` -> `[ICON_START][ICON_END]`)
- transform interpolation to the respective placeholders (e.g. `{{ 1 + 1 }}` -> `[INTERPOLATION]`)

**And then** generate the ID based off this:
`[ICON_TAG_START][ICON_TAG_END] Edit [NUMBER]`

Not based of the inner HTML character by character.

### Describe alternatives you've considered

Sometimes it's possible to alleviate these issues with `<ng-container>` such as:
```html
<button>
  <icon value="notebook"></icon>
  <ng-container i18n="...">Edit {{ 1 + 1 // i18n(ph="number") }}</ng-container>
</button>
```
However this is not always ideal because some non-English languages may change meaning slightly based on this difference.

For example this is **not** localization-friendly:
```html
<button>
  <icon value="notebook"></icon>
  <ng-container i18n="...">Edit</ng-container> {{ 1 + 1 // i18n(ph="number") }}
</button>
```

**Comment by Goodwine** [comment]
Related: (internal link) yaqs/4669638370263040

**Comment by petebacondarwin** [comment]
I cannot reproduce this problem @Goodwine. Can you please provide a github repository that show different ids in the cases you describe above?

Here is my attempt to reproduce it: https://github.com/petebacondarwin/angular-issue-38980

**Comment by Goodwine** [comment]
my bad 😣

Yeah somehow I thought that the exact HTML contents mattered but it looks like they don't! :)

So while `{{ 1 }}` and `{{1}}` generate different IDs when they _should not_, the "ivy no-legacy" target generated the expected output so I believe the new ID generation did take care of things.
