### ISSUE TITLE
using http.d.ts throws during ts compilation

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#3899]
I'm using the `bundles/http.d.ts` during the app compilation and it seems that it causes the compile to throw two semantic errors:
```shell
node_modules/angular2/bundles/typings/angular2/http.d.ts(367,14): error TS1005: ';' expected.
node_modules/angular2/bundles/typings/angular2/http.d.ts(374,14): error TS1005: ';' expected.
```
It might be because of `type-alias` which is not recognised (I am using version `1.5.3` of TS).

**Comment by jessegood** [comment]
See https://github.com/angular/angular/issues/3740
and
https://github.com/angular/angular/issues/3699

**Comment by thelgevold** [comment]
There is currently a bug in the http file. To get around it I have temporarily hacked the file in my project.
You can get it from here until the Angular team fixes it in the source file:  https://github.com/thelgevold/angular-2-samples

**Comment by mhevery** [comment]
this should have been resloved
