### ISSUE TITLE
how to config SystemJS when using the bundles from the npm dist

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#3900]
I am trying to run the [app](https://github.com/rolandjitsu/ng2-play) I am working on using the `bundles` contents, but it seems that I am failing :)

So far my `index.html` looks like:

```html
<script src="lib/traceur-runtime.js"></script>
<script src="lib/system.js"></script>
<!-- Angular Deps -->
<!--<script src="lib/reflect.js"></script>-->
<!--<script src="lib/zone.js"></script>-->
<!--<script src="lib/long-stack-trace-zone.js"></script>-->
<script src="lib/angular2.js"></script>
<script src="lib/router.dev.js"></script>
<script src="lib/http.js"></script>
<!-- App -->
<script>
    System.config({
        baseURL: '/',
        defaultJSExtensions: true,
        paths: {
            'angular2/*': 'angular2/*'
        },
        meta: {
            'lib/rx.js': { format: 'cjs' },
            'lib/firebase.js': { format: 'global', exports: 'Firebase' }
        },
        map: {
            'rx': 'lib/rx.js',
            'firebase': 'lib/firebase.js'
        }
    });
    System.import('app/bootstrap').catch(
        console.error.bind(console)
    );
</script>
```

But it cannot load any of the modules exposed by `angular2`, nor `http`:

<img width="1440" alt="screenshot 2015-08-29 14 00 24" src="https://cloud.githubusercontent.com/assets/1479737/9561820/5b18cbf8-4e56-11e5-987a-1f3242b38c27.png">

I am using the latest version of System (`0.18.16`). A little bit of help would be appreciated, because the only way I could make it work before was by having all `angular2` source on disk and then configured System as such:

```html
<!-- ES6 -->
<script src="lib/traceur-runtime.js"></script>
<script src="lib/system.js"></script>
<!-- Angular Deps -->
<script src="lib/reflect.js"></script>
<script src="lib/zone.js"></script>
<script src="lib/long-stack-trace-zone.js"></script>
<!-- App -->
<script>
    System.defaultJSExtensions = true;
    System.config({
        paths: {
            'angular2/*': 'lib/angular2/*'
        },
        meta: {
            'lib/rx.js': { format: 'cjs' },
            'lib/firebase.js': { format: 'global', exports: 'Firebase' }
        },
        map: {
            rx: 'lib/rx.js',
            firebase: 'lib/firebase.js'
        }
    });
    System.import('app/bootstrap').catch(
        console.error.bind(console)
    );
</script>
```

The above combination worked fine, but now that `http` has been moved out I have to get it from the `bundles` from the npm dist which forces me to config System a different way.

**Comment by pkozlowski-opensource** [comment]
@rolandjitsu I've got an impression that you are making your life harder than necessary - what I'm doing is that I'm just putting angular2 deliverables in a script tag - there is no real point it having it downloaded dynamically via SystemJS as you need framework code to be there anyways. Here is a quick setup demonstrated in plunker: http://plnkr.co/edit/Gm5M5PNlzicZTEwKuy6A?p=preview

You can also check build-time compilation examples:
*  https://github.com/pkozlowski-opensource/ng2-play (AtScript)
* https://github.com/pkozlowski-opensource/ng2-play.ts (Typescript)

**Comment by rolandjitsu** [comment]
@pkozlowski-opensource I am doing the exact same thing at the top, I just load the angular2 lib in a script tag (same with http and the router), but I cannot figure it out why it behaves the way it does.

**Comment by pkozlowski-opensource** [comment]
@rolandjitsu I'm sorry, I not sure I follow... Can you see the plunk I've linked? The repos? Both are using bundles from npm / as deployed to npm...

Please share the entire plunk with what you are doing (you can modify mine) if you need more help. Better yet, let's move this discussion to gitter as it seems like this is more about using SystemJS that ng2 pb.
