### ISSUE TITLE
Missing modules link

### ISSUE THREAD

**Issue by abderrahimkrimi** [angular/angular#39015]
Hello,
I think there is a missing link to the modules chapter in the main concepts menu right before the components link
![Screenshot_2020-09-27-11-01-22-19](https://user-images.githubusercontent.com/6990069/94362108-f6375e80-00b0-11eb-8f6c-8bd830f7f651.png)

**Comment by s-gbz** [comment]
I can submit a PR. Here are [all module related results](https://angular.io/?search=modules)
```
NgModules
Feature modules
Sharing modules
Introduction to modules
Frequently-used modules
Guidelines for creating NgModules
JavaScript modules vs. NgModules
Launching your app with a root module
Lazy-loading feature modules
ModuleWithProviders Migration
NgModule API
NgModule FAQ
Providing dependencies in modules
Update module and target compiler options migration
```

I'd suggest to include
- Feature modules
- Lazy-loading feature modules
- Sharing modules
- NgModules

However this is just my 5 cents. Tell me what to include and the PR is out by tomorrow 🚀

**Comment by abderrahimkrimi** [comment]
Hello,
My remark is just to add a link in the menu to be able to access the Modules chapter 
In fact, I thought that the main concepts includes: modules, components, templates, directives and dependency injection but under the main concepts we don't see the Modules so I was just wondering if the link to the Modules chapter is missing :)
Thanks

**Comment by aikidave** [comment]
Thanks for submitting this issue! (And sorry it took us a bit to respond!)

As part of our efforts to improve the documentation, we moved the ngModule content into our Conceptual Reference. You can find it here: https://angular.io/guide/ngmodules.

Of course, this isn't to say that modules aren't important! We're just working out how to introduce concepts to new Angular developers without overwhelming them. We're working on it, though! I appreciate your patience!
