### ISSUE TITLE
Separate change callback with reading value

### ISSUE THREAD

**Issue by SebastianStehle** [angular/angular#39014]
### Relevant Package
angular/forms

### Description

I think the `ControlValueAccessor` has a performance issue, which cannot be fixed with the current design.

The root cause of the issue is the following method: `registerOnChange`:

```
interface ControlValueAccessor {
  registerOnChange(fn: (value: any) => void): void;
  ...
}
```

The callback has two responsibilities:

1. Notify the model that the value has been changed.
2. Provide the current value

This works fine when you have easy access to the current underlaying value and you can provide the value with each keystroke or change. But it is very problematic in the following cases:

1. The external state is not the same as the internal state. For example editors like Quill or Slate maintain an internal object structure for their state. When you want to write a markdown editor you have to convert the state to markdown with every change, which is expensive. Other editors like TinyMCE are based on the DOM, so you have to convert the DOM to HTML with every change which is also expensive.

2. The editor itself does not provide a reliable way to get all changes. It could be a bug, but sometimes it is just a feature, for example when plugins make a silent change in Quill.

3. You can miss changes. For example when you update the form state on blur only to improve performance and then press a submit button, you do not have the latest changes available, because the form has no way to force an update of all values.

### Describe the solution you'd like

I would like to change the signature to this

```
interface ControlValueAccessor {
  registerOnChange(fn: () => void): void;

  getValue(): any;
  ...
}
```

This allows different approaches, for example:

1. You can call `getValue()` in your change callback to update your model on every change.
2. You can call `getValue()` in your blur callback to update your model on every focus lost.
3. You can convert your change callback to an observable and then use `debounceTime` operator to improve performance.

EDIT: For backwards compatibility we can either make `getValue()` optional or introduce a `ControlValueAccessor2`.

It is relatively easy build a wrapper of `ControlValueAccessor2` around `ControlValueAccessor1` in angular itself, e.g.

### Describe alternatives you've considered
I have not found a good workaround.

**Comment by Airblader** [comment]
On the flip side this would be a breaking changes for countless libraries and components, so I'd appreciate more backwards compatible solutions.

**Comment by SebastianStehle** [comment]
@Airblader True, I have added a few sentences about this. It is relatively easy to make it backwards compatible.

**Comment by Airblader** [comment]
Can you actually show an example of how you'd make use of this? I'm having a hard time seeing the use case for this given that CVAs are mostly used by the forms implementation and some libraries, but not generally "user code". It sounds like you'd have to manually call this, but for that you wouldn't need a change in CVAs anyway, you can just implement that app-side.

**Comment by SebastianStehle** [comment]
I have a wide range of ControlValueAccessor implemented, because when I started my project (https://github.com/squidex/squidex) Angular was in Beta and there was no library. I don't know how I can implement this app side without a lot of hacks. Probably there is a solution but it just not a great one.

**Comment by Airblader** [comment]
I'd be happy to ponder over this if I understood the use case a bit better. My main question is: who would call getValue and under which circumstances?

Naively I'd expect that you can just have your own interface `ControlValueAccessor2<T> extends ControlValueAccessor { getValue: () => T` and then provide NG_VALUE_ACCESSOR as usual, but wherever you're currently interacting with a CVA directly you inject them as that interface instead and use a type guard to see if they actually implement the method.

Side note: I wonder if long term all these APIs shouldn't be built as async by default.

**Comment by SebastianStehle** [comment]
There are two cases when getValue() should be called in my opinion.

1. Before a submit when using reactive forms to force an update of all controls.
2. By the form directives like `formControlName` or `formControl`.

At the moment we have the `updateOn` option for forms. But imagine you have a complex control like TinyMCE and you set this value to `updateOn: 'blur'`.

Then the form system does the following:

1. Change: CVE converts DOM to HTML and sends it as value to the directive. The directive maintains a `pendingValue` which is updated.
2. Another Change
3. Another Change.
... Another Change. // Could be one hour of writing.
X. Blur: CVE invokes callback. The directive forwards the pendingValue to the reactive FormControl.

So we have a lot of conversions from DOM to HTML and we need to maintain the pendingValue to make it work.

Instead the directive now just calls getValue(). Either in the blur callback or in the change callback.

**Comment by Airblader** [comment]
Thanks for taking the time! So you're actually proposing to change the implementation of how reactive forms work and not just extend the API, that wasn't clear to me from the initial post. Indeed I think that'd require ugly workarounds at the moment.

**Comment by SebastianStehle** [comment]
Yes, but the code and logic is shared and ngModel has the same problem.
