### ISSUE TITLE
Invalid X-XSRF-Token

### ISSUE THREAD

**Issue by rubensa** [angular/angular#39020]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common/http

### Is this a regression?

 Not sure

### Description

 I have an Spring Boot application configured with CSRF protection using a CookieCsrfTokenRepository without session enabled (no JSESSIONID is ever generated).
I have an Angular app that consumes this Spring Boot app endpoints.
When loading a component, the component makes multiple request to the server.  Most are GET request but some are POST request.
The problem I'm facing is that when making the POST request, sometimes the request success but much times do not.
Upon examining the client Headers I see that the X-XSRF-TOKEN header value differs from the XSRF-TOKEN cookie value.
In the request history I can see that each request is sending the same XSR-TOKEN cookie and the server responds with a new XSR-TOKEN but looks like the browser cookie is not updated as soon as the cookie is returned.
At some point in the request history, the browser cookie is updated with one of the new server returned cookies.
Subsequent endpoint request send this new Cookie but, if the request is a POST, keeps sending the old X-XSRF-TOKEN value (from old/inital cookie value) so the server responses with a 403.  Expected as the XSR-TOKEN cookie value differs from the X-XSR-TOKEN value.

As far as I can understand, the problem is that:

- For any API call, the server returns a new XSR-TOKEN cookie (as no session ever exists)
- When the browser receives a new cookie value from the server, the update of the cookie may be not processed right the way (has it a processing loop in other thread or something?)
- HttpClientXsrfModule keeps using "his last known" value for the cookie to set the X-XSRF-TOKEN header before making new requests
- Eventually the browser updates the value of the XSR-TOKEN cookie with the last value received from the server
- HttpClientXsrfModule does not know this update has been done and keeps using "his last known" value for the cookie (but the browser sends the new cookie value to the server)
- The request is received by the server that checks the value from the XSR-TOKEN cookie and the X-XSRF-TOKEN header.  As the do not match, a 403 is returned

## 🔬 Minimal Reproduction

 Sorry, I don't know how to setup a REST API on stackblitz.com that requires XSRF with cookie token repository

## 🔥 Exception or Error
<pre><code>

Invalid CSRF token found
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.2
Node: 12.18.3
OS: linux x64

Angular: 9.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@angular/flex-layout              9.0.0-beta.29
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

I think that if all request are fast enough then the problem does not arise (probably the browser has no time to update the cookie?) but if the requests or the network connection are slow the problem appears (as the browser has time to update the cookie?).

**Comment by rubensa** [comment]
Could be the problem [this line](https://github.com/angular/angular/blob/d1ea1f4c7f3358b730b0d94e65b00bc28cae279c/packages/common/http/src/xsrf.ts#L57) from **HttpXsrfCookieExtractor**? Looks like there is some kind of "cache" that prevents parsing the "real" cookie value if the cookie value has already been parsed.

```TypeScript
/**
 * `HttpXsrfTokenExtractor` which retrieves the token from a cookie.
 */
@Injectable()
export class HttpXsrfCookieExtractor implements HttpXsrfTokenExtractor {
  private lastCookieString: string = '';
  private lastToken: string|null = null;

  /**
   * @internal for testing
   */
  parseCount: number = 0;

  constructor(
      @Inject(DOCUMENT) private doc: any, @Inject(PLATFORM_ID) private platform: string,
      @Inject(XSRF_COOKIE_NAME) private cookieName: string) {}

  getToken(): string|null {
    if (this.platform === 'server') {
      return null;
    }
    const cookieString = this.doc.cookie || '';
    if (cookieString !== this.lastCookieString) {
      this.parseCount++;
      this.lastToken = parseCookieValue(cookieString, this.cookieName);
      this.lastCookieString = cookieString;
    }
    return this.lastToken;
  }
}
```

**Comment by JoostK** [comment]
@rubensa Parsing the cookie is a pure operation, so the cache based on identical string contents should be sufficient to re-parse as necessary.

Are you actually properly sequencing all requests to avoid parallel requests? I reckon you store the CSRF value in a database when doing the comparison the server side?

Angular's XSRF processing appears to always read the cookie value when setting the token, so it shouldn't get out of date with what the browser reports.

**Comment by JoostK** [comment]
@rubensa ah, I see.

> Isn't the read cookie, set header and make request synced (atomic operation)?

I believe it is, yes, provided that there aren't any interceptors that introduce asynchronicity.

I don't see anything out of the ordinary in `@anguar/common/http` that could introduce behavior other than native browser behavior, so I can't really judge whether this is an issue with Angular or nor.

You may be able to gain more insight by adding some logging to where the XSRF token is determined and where the request is sent, and cross-referencing that with what you're observing in the Web Inspector's Network tab.

**Comment by rubensa** [comment]
@JoostK I'll check cause we are using [kecycloak](https://www.keycloak.org) client library by mean of [keycloak-angular](https://github.com/mauriciovigolo/keycloak-angular)

**Comment by AndrewKushnir** [comment]
Closing this ticket based on the comments above - it looks like the problem is outside of the `@anguar/common/http` package. Feel free to reopen if the problem still exists. Thank you.
