### ISSUE TITLE
Rendering template with plural forms from bundle localized by command localize-translate throws error Missing locale data for the locale

### ISSUE THREAD

**Issue by SergeyMul** [angular/angular#39023]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/localize@10.1.0

### Is this a regression?

 No

### Description

 I have an issue with rendering template with plural forms. My code bundle localized by CLI command `localize-translate`. The template string is translated and searchable in bundle. But rendering template, I get error like `Missing locale data for the locale "SOME_LOCALE".` throwed by angular. As I see from source code translated plural forms placed and searched at runtime in LOCALE_DATA variable. But it does not contain them in my case. If I import locale data manually by call `import '@angular/common/locales/global/SOME_LOCALE'` rendering is working, because LOCALE_DATA contain imported locale info and translation for my template plural forms. Manual import can be considered as workaround but a think that command `localize-translate` should inject bare locale info object there translated template plural forms can be placed and used by angular runtime.
The bundle build process involve webpack and AngularCompilerPlugin.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 10.1.0
Node: 12.16.3
OS: win32 x64

Angular: 10.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... upgrade
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1001.0
@angular-devkit/core         10.1.0
@angular-devkit/schematics   10.1.0
@ngtools/webpack             10.1.0
@schematics/angular          10.1.0
@schematics/update           0.1001.0
rxjs                         6.6.2
typescript                   3.9.7
webpack                      4.44.1

</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
The Angular CLI integration provides exactly this behaviour. The `localize-translate` binary is purely designed to replace the `$localize` tagged strings with translated versions. The solution that you are using:

```ts
import '@angular/common/locales/global/SOME_LOCALE';
```

is precisely what you must do if you do not utilize the Angular CLI to do the localization. If you are doing your own build pipeline then it is up to you to provide this.

**Comment by SergeyMul** [comment]
Solution with manual locale import not convenient because it requires importing locales for all translations in the source bundle. For now, stayed with concatenating translated bundle and locale data at the build step.

**Comment by petebacondarwin** [comment]
Yes! That is another good solution. (And the one that the CLI uses). I forgot that you are in control of the build pipeline.
I am going to close this as it is working out of the box in the officially supported build tool (CLI) and is straightforward for projects with custom build pipelines to implement.
