### ISSUE TITLE
refactor(router/1.x): split up source files

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#3902]
Currently in `modules/angular1_router` the entire source of that module is in `ng_outlet.js`. I think we should split the source up in dedicated separated files for each component that comes with the module.

/cc @btford

**Comment by btford** [comment]
PR welcome. :)

**Comment by PascalPrecht** [comment]
So you're agreeing. I'll work on that.

**Comment by PascalPrecht** [comment]
Any preferences on what that should look like? One file per component? Do we want to have folders for directives, services, ..(IMO over engineered in that case).

**Comment by btford** [comment]
Up to you– note that you'll need likely need to improve the build script to account for multiple files. @shahata also wanted to migrate that code to TypeScript, but I think splitting first is best.

I agree we should be pragmatic :)

**Comment by PascalPrecht** [comment]
Gotcha

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
