### ISSUE TITLE
cva Error: Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#39022]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 7

### Description
In ViewChild if i pass `{static:true}` then it is working fine but in older version of angular without `{static: true}` it was working fine.

## 🔬 Minimal Reproduction

 https://stackblitz.com/...
Angular 10
https://stackblitz.com/edit/angular-ivy-sili1e?file=src%2Fapp%2Frequired-text%2Frequired-text.component.ts
Angular 7 
https://stackblitz.com/edit/angular-7-master-swasmm?file=src%2Fapp%2Fapp.component.html

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

"@angular/core": "^10.0.9",
</code></pre>

**Anything else relevant?**

**Comment by Achilles1515** [comment]
https://angular.io/guide/static-query-migration

>Starting with version 9, the static flag will default to false.

**Comment by indraraj26** [comment]
It is totally breaking changes i think, as per my understanding you will need `static:true` when do you want to access element in ngOnInit to avoid expressChange error. Also it is not mentioned on docs wherever are you using writeValue there you will have to change @ViewChild static true.

**Comment by sod** [comment]
Yes, it's a breaking change. But angular 8 yelled with deprecation warnings at you - if the option was missing  - and the migration to ng8 actually added `{static: true}` to all ViewChilds.

So it's an unfortunate consequence of skipping the angular 8 major

**Comment by indraraj26** [comment]
anyway i am okay with it since i have few custom form.
