### ISSUE TITLE
fix: runtime throws when not using QueryList type annotation

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#3903]
This error came up with both traceur and TS code  https://github.com/pkozlowski-opensource/ng2-play.ts/issues/2

The problem is that we get a runtime error when `@Query` is used without `QueryList` type annotations. @pkozlowski-opensource opinion is that this should work without `QueryList` annotations.

**Comment by mhevery** [comment]
yes this should work.

**Comment by pkozlowski-opensource** [comment]
`Query` is deprecated and we've got not checks for QueryList so I believe that we can close this one for now.
