### ISSUE TITLE
Previous HTTP requests are re-issued when using observable based interceptor

### ISSUE THREAD

**Issue by rtodea** [angular/angular#39038]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common/http

### Is this a regression?

No.

### Description

When using interceptors based on an observable, the HTTP requests will fire again if the interceptor source fires too.

If we have something like:
<pre><code>
intercept(request, next) {
  return this.colorService.currentColor$.pipe(switchMap((color) => {
     return next.handle(request.clone({
          setHeaders: {'XCustomValue': color}
        }));
  }))
}
</code></pre>

then each time <code>currentColor$</code> fires a new HTTP request is created.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-interceptor-switch-map?file=src/app/app.component.html

In this example we have:

1. <code>HeaderValueService.value()</code> is an interval that emits every 1000 ms
2. <code>CustomHeaderInterceptor</code> uses the value emitted to add a custom header to the HTTP request
3. <code>AppComponent</code> which starts a single HTTP request to an Echo service 

We added a STOP button which makes <code>HeaderValueService.failSafe$</code> emit so we do not block the browser

## 🔥 Exception or Error

Each time the observable fires, all previous intercepted requested are fired again.

## 🌍  Your Environment
**Angular Version:**
<pre><code>

 Tested on Angular 10 via StackBlitz.

</code></pre>

**Anything else relevant?**

Workaround is to use the <code>first</code> operator:

<pre><code>
intercept(request, next) {
  return this.colorService.currentColor$.pipe(
   first(), 
   switchMap((color) => {
     return next.handle(request.clone({
          setHeaders: {'XCustomValue': color}
        }));
  }))
}
</code></pre>

We do not know the internals of the interceptor to suggest a fix.
The external observable should be completed altogether.

**Comment by JoostK** [comment]
This is exactly like I'd expect this to work; any other behavior would be a bug in my opinion. The call to `next.handle` is what triggers the request and this occurs in your Observable pipeline, so whenever that Observable emits you are the one triggering the request. Using the `first()` operator is actually correct if you do have a continuously emitting Observable but only want to execute some logic twice.

**Comment by sod** [comment]
If:
* you implemented the `ColorService` yourself
* `currentColor$` is `ReplaySubject` (?) where you `next()` new values into
* `currentColor$` always holds a value and you are only interested in the current one

then you could change `currentColor$` to a [`BehaviorSubject`](https://rxjs.dev/api/index/class/BehaviorSubject)

Then your intercepter could do:

```typescript
intercept(request, next) {
    return next.handle(request.clone({
        setHeaders: {'XCustomValue': this.colorService.currentColor$.getValue()}
    }));
}
```

and you don't have to deal with observables

**Comment by rtodea** [comment]
@JoostK , I think a big source of confusion here is the <code>switchMap</code> operator which switches from the **first** source of values to a **second** source of values:

Let us consider the case available at https://stackblitz.com/edit/switchmap-restarts?file=index.ts:

```
const second$ = interval(1000).pipe(
  take(3),
  finalize(() => console.log('second$ finished'))
);

const first$ = fromEvent(document, 'click')

first$.pipe(
  tap(() => console.log('clicked')),
  switchMap(() => second$),
)
.subscribe(console.log);
```

If the <code>first$</code> emits again, then `second$` will emit again even though it was marked as complete.

In light of the `switchMap` behavior, there is nothing developers on the `http` module can do.
