### ISSUE TITLE
Import angular2_material in project from npm client

### ISSUE THREAD

**Issue by emirdeliz** [angular/angular#3904]
I tried to import library angular2_materialize from client npm, but miserably failed. I need this for responsive layout of system. Somebody tried this? Or know how to do?

**Comment by PascalPrecht** [comment]
@emirdeliz Angular 2 Material is not ready to be used in production yet. Therefore it's not exposed on any npm package. In other words: don't use Angular 2 Material yet unless you want to play with and contribute to it.

**Comment by emirdeliz** [comment]
OK, @PascalPrecht I am development the program utilizing 'Material Design Lite'. The result is similar of Material css framework, right? Anyway i will go contribute when terminated my current project.

Thank you!

**Comment by PascalPrecht** [comment]
Yes, Material Design Lite is a pure CSS implementation of the MD spec. Don't forget to close this issue :)

**Comment by emirdeliz** [comment]
OK, Thank you!

**Comment by maku** [comment]
btw, Material Design Lite is not pure CSS. It has also a javascript part. Especially when you use it with ng2 you have to register your html element via js (e.g. for input fields)

**Comment by PascalPrecht** [comment]
It has JavaScript components too yes. But I didn't want to go into details here. Not sure what you mean with the registering of HTML elements when using Angular 2 tho.

**Comment by maku** [comment]
see http://www.getmdl.io/started/index.html - Use MDL on dynamic websites:  "Material Design Lite will automatically register and render all elements marked with MDL classes upon page load. However in the case where you are creating DOM elements dynamically you need to register new elements using the upgradeElement function".

So when you use mdl with ng2 in a template you have to call the upgradeElement function...

**Comment by PascalPrecht** [comment]
@maku interesting! Didn't know that. Well, I think until Angular 2 is in a shape that one can actually use it, Angular 2 Material will be in such a shape too. So one could then just you that one.

Thanks for pointing that out!

**Comment by maku** [comment]
@PascalPrecht yeah would be a good exercise to make reusable ng2 components based on mdl... maybe when I have enough time (I think angular material design for ng2 is really far away)

**Comment by dsebastien** [comment]
I know that this issue has been closed for a while but I'm currently trying to use material design lite in combination w/ Angular 2 for a small project of mine.

Does anyone know if there's a way to hook some custom logic in Angular 2 right after new DOM nodes are created from template elements and before (or right after) they're added to the DOM?

If I can do that then I should be able to call the ` componentHandler.upgradeElement(foo);` on DOM nodes created by Angular, hence made the JS effects work as explained in the documentation of MDL (http://www.getmdl.io/started/index.html#dynamic)

If not then I suppose I'll have to take the issue from a different angle and listen for DOM changes... Note that my app is really small and performance shouldn't be an issue.. :)

**Comment by dsebastien** [comment]
Ok this ain't the most efficient thing in the world but it does the job:

```
bootstrap(App, [...]).then(
	success => {
		console.log("Bootstrap successful");
		var mdlUpgradeDom = false;
		setInterval(function() {
			if (mdlUpgradeDom) {
				componentHandler.upgradeDom();
				mdlUpgradeDom = false;
			}
		}, 200);

		var observer = new MutationObserver(function () {
			mdlUpgradeDom = true;
		});
		observer.observe(document.body, {
			childList: true,
			subtree: true
		});
	},
	error => console.error(error)
);
```
Source: http://stackoverflow.com/questions/31278781/material-design-lite-integration-with-angularjs

**Comment by robwormald** [comment]
@dsebastien you might also try doing it at the component level, with the `afterViewInit` lifecycle hook.

**Comment by dsebastien** [comment]
Yep. I also tried with a custom directive but it feels cumbersome (though probably much more efficient as I can only register those components that need it instead of going though the whole DOM ^^): https://github.com/dsebastien/regForm
