### ISSUE TITLE
ngBeforeChanges/ngOnChanging and preventing further Input processing

### ISSUE THREAD

**Issue by Alphish** [angular/angular#39056]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/core.

### Description
Right now, the changes detection cycle:
- updates all input bindings, gradually populating `SimpleChanges` object
- fires `ngOnChanges` with the built `SimpleChanges`, allowing to process the changes collectively

As far as I can tell, there's no documented order of input bindings update. It means that before I have a chance to process changes as a whole, the change processing fires input updates in an order I don't know - and even if I can figure it out from the sources and control it, I still can't rely on it if it's not documented.

This becomes a problem in the following scenario:
- I have one input affecting the list of available items
- I have another input changing the currently selected item, but ignoring the new value if it's outside the range of available items
- in the same change detection cycle, I change available items from collection without item X to a collection with item X *and* change the currently selected item to X
- the input processing system decides to first attempt to choose X as selected item (but X is not among available items), then update the list of available items (only then making X available)

### Describe the solution you'd like
I'd like to propose a new lifecycle hook: ngBeforeChanges/ngOnChanging. This hook would be called *after* input changes have been determined, but *before* inputs would be processed.

In this lifecycle hook, the user could:
- access information about input changes, so that they could process these collectively
- prevent updating certain inputs, usually done when the user handled the input themself
- an additional method for eager processing input would be nice (basically, assign the incoming input to the corresponding value and prevent the input)

This allows finer control over input processing order. For example, in the described scenario I could hook to ngOnChanging, I could do something like:
```typescript
ngOnChanging(changes: IncomingChanges) {
  const change = changes['availableValues'];
  // I imagine SimpleChange previousValue/currentValue would be IncomingChange currentValue/newValue
  this.availableValues = change.newValue;
  change?.prevent(); // or maybe change?.markAsProcessed() or something

  // alternative approach, if method for eager input processing is available
  changes['availableValues']?.process();
}
```

Additionally, it allows simultaneous processing of inputs *before* they are processed individually. It can be used for optimising updates when some relatively expensive processing is triggered by updating either of several values.
```typescript
ngOnChanging(changes: IncomingChanges) {
  if ('value1' in changes || 'value2' in changes || 'value3' in changes) {
    const value1change = changes['value1'];
    const value2change = changes['value2'];
    const value3change = changes['value3'];

    // expensiveValuesUpdate(...) takes a while
    // so if you change multiple related values at the same time, you better call it once
    this.expensiveValuesUpdate(
      value1change?.newValue ?? this.value1,
      value2change?.newValue ?? this.value2,
      value3change?.newValue ?? this.value3
      );

    value1change?.prevent();
    value2change?.prevent();
    value3change?.prevent();
  }
}
```

**Interactions with existing functionality**
We might want to consider the intended use of input prevention:
- default input processing is meant to be prevented *only* if the user processed the input themselves
- input processing may be prevented because the user processed the input themselves *or* refused to process it altogether

As of now, I can only think of reasonable scenarios when default input processing is prevented because user processes it instead. In fact, outright refusing to process inputs might go against the expectations of what inputs are meant to do.

If we assume that all inputs are meant to be processed - some just may be pre-processed by users - I'd keep ngOnChanges the way it works now. I.e. SimpleChanges object contains all the changes - user-prevented and default-processed alike - and doesn't differentiate between them. That's the option I lean towards - I intend user pre-processing to enhance the input processing in general, not to make it a completely new thing.

If we allow refusing to process inputs, we might want to reflect it in some way or another in SimpleChanges object, whether by adding something like "isCancelled" property to SimpleChange or removing the change altogether.

**Implementation notes**
Judging by the sources I've seen earlier but can't find now (I think the file was called `provider.ts` or something similar, and there are lots of providers), the inputs processing right now interleaves input processing and SimpleChanges building (i.e. there's a method that updates bound input and returns a new simple changes object).

If `gather changes + optionally call ngOnChanging + apply non-prevented changes + optionally call ngOnChanges` method is significantly more expensive than current `apply and gather changes + optionally call ngOnChanges`, maybe we could opt for the current input processing for directives that don't implement ngOnChanging. Hopefully, the cost of checking for ngOnChanging implementation is negligible.

### Describe alternatives you've considered
One workaround I tried before was a mechanism for buffering changes when receiving input, then processing these changes in ngOnChanges(...). It got pretty messy, however, especially considering the fact that same component value could be changed via external Input or via internal Output (it was bound to inner input value).

Possibly cleaner workaround I just came up with is having separate dummy Input values - separate from the main values - and process these in ngOnChanges(...). This should allow separating Input()-variables handling (e.g. to control inputs processing orders) and not polluting the processing of core variables.

So if I e.g. have `availableValues: any[]` and `selectedValue: any` properties with all their processing, then I'd add `@Input('availableValues') inputAvailableValues: any[];` and `@Input('selectedValue') inputSelectedValue: any;`, then I'd process these inputs in ngOnChanges.

Not sure how well it works if I have `@Input() someValue;` in a base class then `@Input('someValue') inputSomeValue` in a child class. If the latter declaration completely overrides the former, I guess it would make the workaround relatively clean and effective.

Still, having an ngBeforeChange/ngOnChanging hook would make the dummy input variables unnecessary and also provide much more intuitive place to handle incoming inputs. I at least wouldn't have wasted hours on trying to find a reasonably clean and properly working solution to the inputs asynchronism problem.

Another option could be specifying the order of processing inputs manually, e.g. in the `@Input()` dectorator (with 0 being a default order). However, it's not as flexible and doesn't cover the scenario of one-time expensive processing of simultaneously updated values.

**Comment by IgorMinar** [comment]
Hi @Alphish, thanks for the detailed write up!

Change detection is a tricky subject and adding new hooks to the system is very unlikely unless there is no other way to achieve something. I've read through your write up about how the input change prevention would work, and based on our past experience, I can tell you that system like that would be very unstable and hard to debug, so I'd rather find an easier solution to your use-case.

What I would recommend is that you use one of these two approaches:

  1/ use `ngDoCheck` and intermediate `@Input` properties. In this hook you can check which of the properties have changed, and then update your other properties that are actually bound in the template.
  2/ consider using a different architecture with component level store such as those offered by `@ngrx/component-store` its alternatives. Component stores allow you to collect all of the changes from inputs and propagate them as a single change.

I'm going to go ahead and close this issue, as it's unlikely that we'll be adding the hooks you proposed. But I hope that the alternative solutions I proposed will work for you.
