### ISSUE TITLE
Update Validators.pattern docs to mention the use of global flag in RegExp

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#39053]
We should update the [Validators.pattern docs](https://angular.io/api/forms/Validators#pattern) to mention possible effects of using the global flag (e.g. `/abc/g`) in a RegExp passed as an argument. If the validator function is invoked multiple times the subsequent calls might produce unexpected results due to the `lastIndex` being preserved. Additional info: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test.

**Comment by AleksanderBodurri** [comment]
@AndrewKushnir I can take this issue.

**Comment by AndrewKushnir** [comment]
Thanks @AleksanderBodurri!

**Comment by sonukapoor** [comment]
@AndrewKushnir While documenting this issue will certainly help, it will not help much if somebody needs to perform a global regex search. Maybe we need a followup issue to fix the underlying issue so that the `lastIndex` is reset before re-running the validation logic. WDYT?

**Comment by AndrewKushnir** [comment]
@sonukapoor thanks for the comment. I was thinking about that too, but my understanding is that we should not change the state of the `RegExp` as this is something that a user controls. Using a `RegExp` with a global flag for validation is typically undesirable (and not needed in majority of cases), since it has unclear practical purpose in a context of validation: if there is at least one match, the validation will be treated as successful, so if there are more matches (in case a global flag is used) it doesn't change the validation result - it will still be successful. If there are no matches (which will be true with or without the global flag) - the validation will fail. Throwing an error in case a `RegExp` has a global flag might be too restrictive as well, since there might be use-cases where developers rely on shifting the `lastIndex` property. So I think adding a paragraph into the docs is a step forward that provides more information to users and do not restrict or enforce certain logic. We can reconsider this behavior in the future in case we get more feedback. Thank you.

**Comment by sonukapoor** [comment]
Ah. That makes sense @AndrewKushnir. 👍

**Comment by AndrewKushnir** [comment]
Closing this ticket since PR #39055 addressed this issue.
