### ISSUE TITLE
docs(strict-mode): add examples and make the guide more robust based on Angular blog post

### ISSUE THREAD

**Issue by Splaktar** [angular/angular#39052]
# 📚 Docs enhancement request

### Description

From the Angular blog, there is some feedback on the strict mode docs (https://medium.com/@john.crim/this-is-a-very-helpful-post-it-is-clearer-than-the-docs-at-this-page-https-angular-io-guide-str-2c674bc61224):

> This is a very helpful post - it is clearer than the docs at this page: https://angular.io/guide/strict-mode

I agree that @mgechev’s [blog post](https://blog.angular.io/angular-cli-strict-mode-c94ba5965f63) includes some useful examples that should be added to the official docs. I would suggest that examples of some of the other rules in action would also be useful for our strict mode docs.

### What's the affected URL?**
https://angular.io/guide/strict-mode

### Reproduction Steps**
- Reading the docs page

### Expected vs Actual Behavior**

**Expected:** Angular Documentation is more complete than what is found in a single blog post.
**Actual:** https://blog.angular.io/angular-cli-strict-mode-c94ba5965f63 is more complete and includes details missing from https://angular.io/guide/strict-mode

## 📷Screenshot
![Screen Shot 2020-09-29 at 20 10 29](https://user-images.githubusercontent.com/3506071/94629132-d9a54d00-028f-11eb-8669-621cb100f499.png)

## 🔥 Exception or Error
N/A

### Browser info
- Chrome 85

### Anything else relevant?
Related but not the same: https://github.com/angular/angular/issues/38771.

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
