### ISSUE TITLE
possible Table Design 

### ISSUE THREAD

**Issue by liorkatzdev** [angular/angular#39058]
I need to do this design : 

![‏‏צילום מסך (5)](https://user-images.githubusercontent.com/56354154/94684500-d01ff180-0330-11eb-8fd9-a548ea27da47.png)

Is there any Angular package/framework that makes this similar tables? even pure html will help

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
