### ISSUE TITLE
Misleading filter:notarray error

### ISSUE THREAD

**Issue by Andyhasit** [angular/angular#3906]
I made a simple error by not placing the "track by" instruction at the end:

     <tr ng-repeat="item in myItems| orderBy : 'name' track by $index | filter: {isUnmapped: true} ">

I should have put it here:

     <tr ng-repeat="item in myItems| orderBy : 'name' | filter: {isUnmapped: true} track by $index">

But the error raised for this mistake is filter:notarray, which is misleading:

Expected array but received: 0

Suggestions:
  * Create a new error if track by is in the wrong place: trackbyisnotlast
  * Check why the notarray got wrongly flagged despite an object being passed (and the alleged value passed is 0)

In AngularJS v1.4.4

**Comment by gdi2290** [comment]
this is the angular2 repo the angular1 repo is here https://github.com/angular/angular.js
