### ISSUE TITLE
FormControlName doesn't resolve a form child path

### ISSUE THREAD

**Issue by francesco-gallo** [angular/angular#39074]
# 🐞 bug report

### Affected Package
@angular/forms

### Is this a regression?
Cannot tell

### Description
Using FormControlName to bind a FormControl to a component fails if the form name is a path; form.get('path.subpath') must be used in this case.

In model.ts the delimiter split check "if (!Array.isArray(path))" fails because path is treated as an array

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-zhwhvx

## 🔥 Exception or Error
<pre><code>
Cannot find control with name: 'path.subpath'
</code></pre>

## 🌍  Your Environment

**Angular Version: 9.1.12**
<pre><code>
Angular CLI: 9.1.12
Node: 14.10.1
OS: linux x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/cdk                      10.2.1
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.6.3
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by AndrewKushnir** [comment]
Hi @Mewster, currently the `FormControlName` and `FormGroupName` directives do not support dot notation and the whole string is treated as control/group name, so I'm labelling this ticket as a feature. Thank you.

**Comment by abarghoud** [comment]
Hello @AndrewKushnir I would be happy to work on this one, can i ?

**Comment by AndrewKushnir** [comment]
Hi @abarghoud, it looks like this feature would require a design to review cases when the `FormControl`'s path crosses `FormGroup` and `FormArray` boundaries. Currently a parent container is [being injected into FormControlName directive constructor](https://github.com/angular/angular/blob/master/packages/forms/src/directives/reactive_directives/form_control_name.ts#L130) and we may not have it (or may have a reference to a wrong parent) if the path crosses `FormGroup` and `FormArray` boundaries. It's unclear whether this feature is feasible without massive changes to underlying architecture, so I do **not** consider this ticket to be ready for implementation. Thank you.
