### ISSUE TITLE
$http spends too much time on chrome

### ISSUE THREAD

**Issue by youtsea** [angular/angular#3908]
back-end:

```python 
    def get(self):
        return {'status': 201, 'error': None, 'data': {'site': 'root'}}
```

front-end:

```javascript

    var req = {
		method: 'GET',
		url: 'http://ServerIp/api/site/root',
		headers: {
		'Authorization': '******************'}
	}
	$http(req).then(function(response){
		$scope.json_data = response.data;
	},function(response){
		$scope.json_data = 'fail';
	});
```

chrome:

![image](https://cloud.githubusercontent.com/assets/9941834/9570679/143b0466-4fc4-11e5-875c-232eba3adf1c.png)

Firefox:

![image](https://cloud.githubusercontent.com/assets/9941834/9570702/590159d8-4fc4-11e5-9504-139866e6924f.png)

IE:

![image](https://cloud.githubusercontent.com/assets/9941834/9570735/bc40678c-4fc4-11e5-8a76-c68dee5408f0.png)

wireshark:

![image](https://cloud.githubusercontent.com/assets/9941834/9570716/8d4890d0-4fc4-11e5-846a-03c1a425dc82.png)

**Comment by ericmdantas** [comment]
Hello, @youtsea!

Please ask 1.x questions [in this repo](https://github.com/angular/angular.js/issues/) instead. :smile:

**Comment by youtsea** [comment]
oh,thanks.:flushed:
