### ISSUE TITLE
Impossible to run unit tests

### ISSUE THREAD

**Issue by Gennady77** [angular/angular#39085]
Hi everyone.

node version 12.18.3
windows 10

I just don't know where I can find a help. I spent several hours to run unit tests and didn't have a success. So I run command:  yarn test-non-ivy //packages/core/... and got the following error:

INFO: Analyzed 320 targets (1 packages loaded, 1199 targets configured).
INFO: Found 300 targets and 20 test targets...
ERROR: C:/users/my_name/documents/project/angular/packages/zone.js/BUILD.bazel:13:8: Executing genrule //packages/zone.js:LICENSE_copy failed (Exit -1). Note: Remote connection/protocol failed with: execution failed
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("c:\tools\msys64\usr\bin\bash.exe" -c "source external/bazel_tools/tools/genrule/genrule-setup.sh; cp LICENSE bazel-out/x64_windows-fastbuild/bin/packages/zone.js/LICENSE"): The system cannot find the file specified.
 (error: 2)
INFO: Elapsed time: 1.986s, Critical Path: 0.24s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
//packages/core:core_api                                              NO STATUS
//packages/core:ng_global_utils_api                                   NO STATUS
//packages/core/schematics/test:test                                  NO STATUS
//packages/core/schematics/test/google3:google3                       NO STATUS
//packages/core/test:circular_deps_test                               NO STATUS
//packages/core/test:test                                             NO STATUS
//packages/core/test:test_web_chromium                                NO STATUS
//packages/core/test:test_web_firefox                                 NO STATUS
//packages/core/test:testing_circular_deps_test                       NO STATUS
//packages/core/test/acceptance:acceptance                            NO STATUS
//packages/core/test/acceptance:acceptance_web_firefox                NO STATUS
//packages/core/test/render3:render3                                  NO STATUS
//packages/core/test/render3:render3_web_chromium                     NO STATUS
//packages/core/test/render3:render3_web_firefox                      NO STATUS
//packages/core/test/render3/perf:perf                                NO STATUS
//packages/core/test/strict_types:strict_types                        NO STATUS
//packages/core/test/view:view                                        NO STATUS
//packages/core/test/view:view_web_chromium                           NO STATUS
//packages/core/test/view:view_web_firefox                            NO STATUS
//packages/core/test/acceptance:acceptance_web_chromium         FAILED TO BUILD

FAILED: Build did NOT complete successfully
error Command failed with exit code 34.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Best Regards

**Comment by josephperrott** [comment]
It looks like you are using RBE, with a windows machine.  Unfortunately at this time RBE does not work with our bazel setup.

Are you seeing this same error when you run these tests locally, without `config=remote`?

**Comment by ajitsinghkaler** [comment]
@josephperrott we should add different documentation for windows in contributing.md

**Comment by Gennady77** [comment]
I agree with @ajitsinghkaler. Add please in contributing.md instruction for building project and running test.

**Comment by Gennady77** [comment]
@josephperrott what is RBE? Relative biological effectiveness? :)

**Comment by josephperrott** [comment]
RBE is remote build execution.

The process is the same for building using both unix and windows, however based on your log output you provided it looked like you may have been relying on RBE.

If you are not using remote build execution, my recommendation would be to try cleaning bazel to ensure that there isn't something amiss

```
yarn bazel clean --expunge
```

**Comment by sonukapoor** [comment]
@Gennady77 I am on windows as well. I usually run individual package tests using the following command:

```bash
yarn bazel test //packages/forms/test --config=ivy
```

Note that on windows you need to use `yarn bazel test ..` instead of `yarn bazel run ...`. This is mentioned [here](https://github.com/angular/angular/blob/master/docs/BAZEL.md#windows).

**Comment by josephperrott** [comment]
Thanks @sonukapoor, that is likely the issue that you are seeing a manifestation of as `test-non-ivy` calls `bazel test`

**Comment by atscott** [comment]
@josephperrott Has this issue been resolved or does it still need investigation?

**Comment by petebacondarwin** [comment]
Closing due to a lack of response.
