### ISSUE TITLE
Broken external link

### ISSUE THREAD

**Issue by kjdeepak** [angular/angular#39106]
# 📚 Docs or angular.io bug report

### Description

On clicking this link  [Flaw: Constructor does Real Work
](http://misko.hevery.com/code-reviewers-guide/flaw-constructor-does-real-work/) in the documentation page under [Initializing a component or directive](https://angular.io/guide/lifecycle-hooks#initializing-a-component-or-directive)   the user is directed to a broken link.

### What's the affected URL?**
https://angular.io/guide/lifecycle-hooks#initializing-a-component-or-directive

### Expected vs Actual Behavior**
The article on the topic **Flaw: Constructor does Real Work** is not displayed in the redirected URL  as expected.

## 📷Screenshot

![image](https://user-images.githubusercontent.com/9925122/95005852-d953db80-061a-11eb-9b47-bf8bce2580bc.png)

**Comment by sonukapoor** [comment]
This seems to be an issue with @mhevery's site.

**Comment by yallen011** [comment]
I would like to work on this.

**Comment by aikidave** [comment]
@yallen011 Do you have a PR for this yet? Anything I can do to help?

**Comment by yallen011** [comment]
@aikidave submitted a PR.
