### ISSUE TITLE
$http.get don't return any thing

### ISSUE THREAD

**Issue by vahidalvandi** [angular/angular#3910]
i have factory like bellow

app.factory('awesomeService', function($http) {
return {
getUsers: function(){
return   $http.get("/smart").success(function(response){
 return response.data;
 })
}}})
---------------------------------------------------------------------
in controller=
var user = awesomeService.getUsers();
 console.log(user);
------------------------------------------------------------------
in console display=
d {$$state: Object}

======================================
in success don't return any thing and in console just  $http.get("/smart") result
otherwise must display result
return response.data;
why?

**Comment by PascalPrecht** [comment]
@vahidalvandi this is the repository for Angular 2. You might want to file this issue at http://github.com/angular/angular.js

To give you a hint, `.success()` and `.error()` have been deprecated in Angular 1.4. Try to go with `$http.get().then(function () { ... });`

**Comment by btford** [comment]
Please read the [contributing guidelines](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem); as Pascal said, these types of questions are ill-suited for GitHub. Thanks!
