### ISSUE TITLE
 angular component not created when run test case(ng test)

### ISSUE THREAD

**Issue by mohankumar91** [angular/angular#39109]
We have created the angular component and write the spec in the ts file. I have run the command **ng test**, but not create the component only run the test case. Please help me.

Please run the below sample
[Angular-testcase.zip](https://github.com/angular/angular/files/5323365/Angular-testcase.zip)

Link: https://stackoverflow.com/questions/64139838/e-columns-is-not-a-known-element

**Comment by sonukapoor** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
