### ISSUE TITLE
DOMSanitizer doesn't sanitize as expected

### ISSUE THREAD

**Issue by eliavmaman** [angular/angular#39104]
i'm trying to bind
```
<div style="width: 300px;height: 300px; background-size: cover;" [ngStyle]="{'background-image':'url('+imageSrc+')'}"
```
```
this.imageSrc = this.sanitizer.bypassSecurityTrustResourceUrl('https://dewqn7xrxo328.cloudfront.net/fit-in/1280x1280/filters:format(webp)/HojCmQ1zBtfye47xm8VX/1576355105374_picmywave.jpg');
```

And i get the following message:

```
SafeValue must use [property]=binding: https://dewqn7xrxo328.cloudfront.net/fit-in/1280x1280/filters:format(webp)/HojCmQ1zBtfye47xm8VX/1576355105374_picmywave.jpg (see http://g.co/ng/security#xss)
```

when i remove the  "filters:format(webp)/" it works fine, also if i bind it to <img [src]/> it works fine.
what should i do?

**Comment by eliavmaman** [comment]
Anyone?

**Comment by petebacondarwin** [comment]
Hello @eliavmaman

I note that you can indeed get this to work as follows: https://stackblitz.com/edit/ivy-r6drbo?file=src%2Fapp%2Fapp.component.ts

We reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by eliavmaman** [comment]
@petebacondarwin thx ... it worked for me..
I thought i tried almost everything  but apearse i didn't. Thx again
