### ISSUE TITLE
Angular 10 Custom Elements not found

### ISSUE THREAD

**Issue by NaKyouTae** [angular/angular#39115]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common and CUSTOM_ELEMENTS_SCHEMA

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.2.x

### Description

 
A. Custom element is not recognized
 - I used CUSTOM_ELEMENTS_SCHEMA but Custom Element not found

B. ngStyle, ngIf, ngModel etc Do not recognize
 - In that Module import CommonModule but do not recognize

## 🔥 Exception or Error
<pre><code>

error NG8001: 'app-user-list' is not a known element:
1. If 'app-user-list' is an Angular component, then verify that it is part of this module.
2. If 'app-user-list' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

error NG8002: Can't bind to 'ngModel' since it isn't a known property of 'input'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.4
Node: 12.18.4
OS: win32 x64

Angular: 10.1.4
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.4
@angular-devkit/build-angular   0.1001.4
@angular-devkit/core            10.1.4
@angular-devkit/schematics      10.1.4
@angular/cdk                    10.2.3
@angular/http                   7.2.16
@angular/material               10.2.3
@schematics/angular             10.1.4
@schematics/update              0.1001.4
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Anything else relevant?**

Update from 8.2.x to 10.1.4 without updating 9.x

**Comment by petebacondarwin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

**Comment by NaKyouTae** [comment]
That's all..
I upgraded Angular version 8.x to 10.1.4.
After then CommonModule, ngStyle, ngModel, etc. are not recognized

Sorry. It seems that This is all I can offer..
Is there anything you can response with just this information?

**Comment by NaKyouTae** [comment]
Create custom elements and use them in other components.

I upgraded 8.x to 10.1.4 without upgrading 9.x.

After that, ngStyle, ngModel, Custom Element, etc. Do not recognized by all projects.

That's all I know...

An error message  is attached belowd

--------------------- error message -----------------------------------------------------------------------------------------------

A. error NG8001: 'app-xxxx is not a known element:
1. If 'app-user-list' is an Angular component, then verify that it is part of this module.
2. If 'app-user-list' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

B. error NG8002: Can't bind to 'ngStyle' since it isn't a known property of 'div'.

**Comment by NaKyouTae** [comment]
Eventually I make new project.
Successfully runs project...

**Comment by Piket564** [comment]
Hi, i've same issue with an Ionic project.
Here my info:
```
Ionic:

   Ionic CLI                     : 6.11.11 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.4
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 5 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : not installed

System:

   ios-deploy : 1.11.2
   ios-sim    : 8.0.2
   NodeJS     : v14.13.0 (/usr/local/Cellar/node/14.13.0/bin/node)
   npm        : 6.14.8
   OS         : macOS Catalina
   Xcode      : Xcode 12.0.1 Build version 12A7300

```

And the error:

`Can't bind to 'ngIf' since it isn't a known property of 'ion-button'.`

**Comment by Piket564** [comment]
Hi @petebacondarwin,

Sorry for misunderstanding.
Not a bug, but my mistake.

In the file `app-routing.module.ts` I had not set the route to the page or component correctly, consequently the component module could not load BrowserModule or CommonModule.

**Comment by NaKyouTae** [comment]
I resolved the problem.
Cause was lazy load.
Called component in routing module is happened compile error.
So I changed in the routing module how to call component.

ex)
{path : '', component: TestComponent} 
to
{path: '', loadChildren: () => import('./test/testmodule').then((m) => m.TestModule)

I changed as above and it worked successfully.
