### ISSUE TITLE
docs(di): improve documentation for the providedIn: 'any' provider scope

### ISSUE THREAD

**Issue by LayZeeDK** [angular/angular#39112]
# 📚 Docs or angular.io bug report

### Description
It is a bit difficult to identify use cases that can benefit from using the `providedIn: 'any'` provider scope and how it's different from other ways of configuring Angular injectors.

### What's the affected URL?
1. https://angular.io/api/core/Injectable#providedIn
1. https://angular.io/guide/providers#limiting-provider-scope-by-lazy-loading-modules

### Reproduction Steps

1. The description in the [`providedIn` option reference](https://angular.io/api/core/Injectable#providedIn) is short and precise, but not very helpful in this regard.
>Provides a unique instance in each lazy loaded module while all eagerly loaded modules share one instance.
2. The description in the [*Providing dependencies in modules* guide](https://angular.io/guide/providers#limiting-provider-scope-by-lazy-loading-modules) explains how the dependency is resolved, but does not give useful examples of dependencies that could benefit from this approach.

### Expected vs Actual Behavior

It would be great to list at least one simple example that is realistic and easy to understand.

Also, we could explain how it's different from other ways of configuring injectors.

My thoughts on the `providedIn: 'any'` provider scope:
- It is useful to control stateful dependencies that vary between lazy-loaded feature modules.
- It is useful for configurations, logging, analytics, and metrics.
- It is a tree-shakable alternative to:
  - The `forRoot`-`forChild` pattern
  - A feature module provider
  - A service module provider
- It keeps the dependency tree-shakable, where as if it was provided in Angular module metadata, it would always be included in the bundle, even if no component was using this dependency.

One of the techniques is described in [A detailed look at Angular's 'root' and 'any' provider scopes](https://indepth.dev/angulars-root-and-any-provider-scopes/).

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Anything else relevant?

Current version: Angular 10.1.

See [Gist of how the `'any'` provider scope is used compared to a module provider and the forChild pattern](
https://gist.github.com/LayZeeDK/291a1d0230de81bf2cf89256070ce569).

**Comment by JeanMeche** [comment]
I'll close this as `providedIn: 'any'` has been deprecated in v15.

**Comment by LayZeeDK** [comment]
For anyone still interested in this topic, you could purchase a copy of my book [Accelerating Angular Development with Ivy](https://www.packtpub.com/product/accelerating-angular-development-with-ivy/9781800205215). *Chapter 3: Introducing CSS Custom Properties and New Provider Scopes* has a section that explains both the `providedIn: 'any'` and `providedIn: 'platform'` provider shorthands.
