### ISSUE TITLE
ID generated by xi18n command does not match ID generated at run time

### ISSUE THREAD

**Issue by aresot** [angular/angular#39128]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

  Not sure

### Description

 string ID generated by using "ng xi18n --ivy --format=xlf" dont match ID at runtime. Im getting  `localize.js:392 No translation found for ...`

## 🔬 Minimal Reproduction
 

1. Say add `<custom-element i18n-label label="Your details must match your government issued ID"></custom-element>` in your template
2. Run `ng xi18n --ivy --format=xlf` command
3. in your main.ts add `loadTranslations({<key from xlf file>:<string vlaue>})`
4. run it with "ng serve"

## 🔥 Exception or Error
<pre><code>

In the console I see `localize.js:392 localize.js:392 No translation found for "4775231765644062609" ("Your details must match your government issued ID") warning. By comparison ID for that string in the xlf file was "bf882f6f9243369463e44749b2780c253ddce34a"

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.1.1
Node: 10.15.3
OS: darwin x64

Angular: 10.1.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.12
@angular-devkit/build-angular      0.1001.4
@angular-devkit/build-ng-packagr   0.1001.4
@angular-devkit/build-optimizer    0.1001.4
@angular-devkit/build-webpack      0.1001.4
@angular-devkit/core               7.3.10
@angular-devkit/schematics         7.3.10
@angular/cdk                       10.2.3
@angular/cli                       10.1.1
@angular/flex-layout               10.0.0-beta.32
@angular/google-maps               10.2.3
@angular/material                  10.2.3
@ngtools/webpack                   10.1.4
@schematics/angular                8.3.23
@schematics/update                 0.1001.1
ng-packagr                         10.1.2
rxjs                               6.6.3
typescript                         3.9.7
webpack                            4.44.1

</code></pre>

**Anything else relevant?**

I also noticed that IDs generated from templates vs from $localize in TS files have different length. Here is ID from $localize: 4998556035340110929 and here is from template 47c477a6e7959ffde7a0ab247ec1c88468d5e101. Looks like ones from templates is hexadecimal where from $localize are numbers only. And template IDs twice longer.

**Comment by petebacondarwin** [comment]
I cannot reproduce this problem locally. Here is an example repository that show everything working fine: https://github.com/petebacondarwin/angular-issue39128

Here are some things that might help:

The new localization uses a new message id format, which is more suited to the `$localize` tagged string approach and is resilient to things like whitespace changes. This is the message format used internally for translation. This is the shorter numerical ids that you are seeing.

The longer hexadecimal message id that you also see are "legacy" message ids from before the new localization implementation. These are still supported at the moment but will be dropped at some point. The way the legacy ids are supported is that they are attached as metadata to the `$localize` tagged message. You can see this in the generated code in the example repository that I link to above: 

```
i18n_0 = $localize `:␟33a8faca74df927c30c40c8db2679cc485a9f524␟4386761592423030977:this is a test`;
```
  
The `33a8faca74df927c30c40c8db2679cc485a9f524` and `4386761592423030977` are legacy message ids. The first should match the id in the extracted XLF file.

Finally, I note, in your original report that the warning states that the missing message has the text `"Name can not contain numbers and special characters"`. But this is different to the text that you have marked for translation `"Your details must match your government issued ID"`. Is this just a mistake in the bug report or is it that there are actually two messages here?

I suspect that the latter is the case, and that the confusion for you comes from the fact that the warning is mentioning a different message id to the one that you expected.

**Comment by aresot** [comment]
Thank you for reply. I corrected my original report with proper message. Message is definitely the same. Will compare your example with mine. Have a feeling something mismatched with the versions.

**Comment by petebacondarwin** [comment]
I suspect that in JIT mode (i.e. aot=false) then the compiler is not configured to produce the legacy message ids in the `$localize` tagged template strings. I can take a look into that.

In terms of interpolations, you must realise that the format of the object you load at runtime (via `loadTranslations()`) is an a format that is not XLIFF. So you cannot expect XLIFF style placeholders to work. Basically, you need to parse your XLIFF into the required format. There are "private" APIs in the `@angular/localize` package that can do this. This is basically what https://www.locl.app/ is using. The format is basically that placeholders are of the form: `{$PLACEHOLDER_NAME}`.  So the example you give above would look like:

```
Ich habe die {$START_LINK} " MyCompany-Datenschutzrichtlinie {$CLOSE_LINK} gelesen und bin damit einverstanden {$CLOSE_LINK}
```

**Comment by petebacondarwin** [comment]
For reference, I think the line that needs to change to support legacy message ids in Ivy JIT mode is https://github.com/angular/angular/blob/d795a001375a7d06592450d6f57a4f05d4d3e8e9/packages/compiler/src/render3/view/i18n/meta.ts#L55

**Comment by aresot** [comment]
Thank you Pete. Sorry to highjack that thread but im not 100% clear on what should be JSON final format. The `$START_LINK` and `{$CLOSE_LINK}` are XLF structures that contain HTML inside. How would localize know what values of those $START_LINK and $CLOSE_LINK are (from your example)?

Here is original HTML template: `<ta-checkbox formControlName="checkAgree" [required]="true" i18n
        >I have read and agree to the &nbsp;
        <a href="https://tripactions.com/privacy" target="_blank">TripActions Privacy Policy</a></ta-checkbox
      >`

Here is what xi18n gives me in XLF: `<source>I have read and agree to the   <x id="START_LINK" equiv-text="&lt;a href=&quot;https://tripactions.com/privacy&quot; target=&quot;_blank&quot;&gt;"/>TripActions Privacy Policy<x id="CLOSE_LINK" equiv-text="&lt;/a&gt;"/></source>`

Here is JSON i get (we use 3rd party service to translate): `"23777a72d61a8aef330dbd2250aec97c5c2e3210": "I have read and agree to the   <x id=\"START_LINK\" equiv-text=\"<a href=\"https:\/\/tripactions.com\/privacy\" target=\"_blank\">\"\/>TripActions Privacy Policy<x id=\"CLOSE_LINK\" equiv-text=\"<\/a>\"\/>"`

What should be correct JSON that I can feed into loadTranslations for that example?

**Comment by petebacondarwin** [comment]
The internal format will look like:

```
"I have read and agree to the   {$START_LINK}TripActions Privacy Policy{$CLOSE_LINK}"
```

The other attributes on the XLIFF tags are not relevant to actually translating the message.

**Comment by aresot** [comment]
oh got it now. Thank you for your help!
