### ISSUE TITLE
ActivatedRoute data type mismatch BehaviorSubject<Data> vs Observable<Data>

### ISSUE THREAD

**Issue by Omi0** [angular/angular#39133]
As long as createActivatedRoute() construct data as [BehaviorSubject](https://github.com/angular/angular/blob/3817e5f1dfeb9de26fa2ea4068a37565f435214f/packages/router/src/create_router_state.ts#L79) shouldn't we define it accordingly in [ActivatedRoute constructor](https://github.com/angular/angular/blob/cf9a47ba53738bf3b8ce282938211370e946bbf9/packages/router/src/router_state.ts#L131)

value getter is only available on BehaviorSubject but not Observable

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate
