### ISSUE TITLE
Export RadioControlRegistry to be able to use it for custom implementations of ControlValueAccessor

### ISSUE THREAD

**Issue by abarghoud** [angular/angular#39136]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/forms.

### Description
I am trying to implement `ControlValueAccessor` for a custom radio component, but the problem is that for radio buttons we need to deselect/select other radios of the same group when one is selected as it is done in https://github.com/angular/angular/blob/c0523fc3b45cdb5ba52109f7ae0e4dab555b7d72/packages/forms/src/directives/radio_control_value_accessor.ts using `RadioControlRegistry`, except that this registry is not exported for external use.

### Describe the solution you'd like
Export `RadioControlRegistry` to be able to use it when implementing `ControlValueAccessor` without needing to create a new one internally in the project where it's being implemented.

I can propose a PR if you consider this as needed.

### Describe alternatives you've considered
N/A

**Comment by abarghoud** [comment]
Hi @AndrewKushnir, do you think that this is feasible by design, if so, I can start working on it

**Comment by AndrewKushnir** [comment]
Hi @abarghoud, thanks for creating this ticket and describing your request. I believe the best way for now would be to create your own service (similar to what `RadioControlRegistry` does) and we'll keep this ticket open to collect more feedback from the community to consider extending public API surface of the framework in the future. Thank you.
