### ISSUE TITLE
Required validator does not work with number

### ISSUE THREAD

**Issue by Mohamed-M** [angular/angular#39132]
Re-opened a bug issue that wasn't resolved, but closed due to inactivity.

https://github.com/angular/angular/issues/6932

> The required validator does not work with a input whose type is number :
> <input type="number" ngControl="weight" />
> 
> this.form = fb.group({
>   weight: ["", Validators.required]
> });
> When the input is empty, no error appear.
> 
> The reason is that the NumberValueAccessor selector match the input, and set the value of the Control to a number. If the entered string of the input does not match a number, the value is NaN. This is the case for the empty string.
> But the required validator return a error only if the control value is blank (null or undefined) or is a empty string. This is not the case of any of these two conditions because the NumberValueAccessor set the value to the NaN number.
> 
> The required validator can not really verify the NaN value because it can appear for empty string, but also for string that are not a number (like 'aaa'). The problem is that the validator can not retrieve the entered string from the control variable.

**Comment by sonukapoor** [comment]
@Mohamed-M This seems to be working as expected. Here is a [stackblitz](https://stackblitz.com/edit/angular-gh-39132-input-number-validator?file=src/app/app.component.ts).  

Enter a numeric value into the field and you will see that the `valid` property returns `true`, remove the value from the input and it shows `false`.

**Comment by AndrewKushnir** [comment]
Closing this issue based on the comment above. Feel free to reopen of create a new one if the problem still exists.
