### ISSUE TITLE
Make pipes pure functions by default, with an option to opt out

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#3914]
Currently all pipes are statefull and recompute the output on each change detection pass. This can quickly become a perf bottlenecks within repeaters of large apps.

Considering the pipes to be pure functions by default will allow us to:
- cache and reuse output values when input doesn't change
- share a single pipe instance across the whole app

This is a change that we made in Angular 1.3 and it gave us a huge perf boost especially for Date filter/pipe that is commonly used in large apps.

**Comment by jeffbcross** [comment]
I believe both requirements were satisfied by https://github.com/angular/angular/commit/a8bdb693b9d9df82c0078eb327ba6f9fe0e8ca0a
