### ISSUE TITLE
Merge the attribute and property binding pages

### ISSUE THREAD

**Issue by kapunahelewong** [angular/angular#39141]
# 📚 Docs or angular.io bug report

### Description

Per this comment, should merge the attribute and property binding pages.
https://github.com/angular/angular/pull/38860#discussion_r498539098

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by mgechev** [comment]
That's part of the documentation effort our team is working on and will be resolved by the template topic refactoring. Closing for now.
