### ISSUE TITLE
HttpClient support for binary file upload

### ISSUE THREAD

**Issue by gnusiva** [angular/angular#39157]
hi, 

I need to upload binary file form angular httpClient class. 

curl --location --request PUT 'http://something.com/somepath' \
--header 'Authorization: Bearer alsdfjalsf.asdfadsf.asdfadsf' \
--header 'Content-Type: application/x-7z-compressed' \
--data-binary 'path_to_binary_file'

**Comment by sonukapoor** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
