### ISSUE TITLE
An unhandled exception occurred: Cannot read property 'Minus' of undefined

### ISSUE THREAD

**Issue by Anishmourya** [angular/angular#39158]
Oh hi there! 😄

Hi, I am trying to serve my angular app locally, but it's giving error "An unhandled exception occurred: Cannot read property 'Minus' of undefined"
I also looked codebase of angular-CLI, just noticed they have updated 28 days ago.
https://github.com/angular/angular/blob/aeec223db1236db236ab56a4a283cf2ca410cae3/packages/compiler-cli/src/ngtsc/translator/src/translator.ts#L14
which seems to be "-"  undefined.

Can you fix it on an urgent basis? 
thanks in advance.

## 🔥 Error
<pre>
An unhandled exception occurred: Cannot read property 'Minus' of undefined

@angular/compiler-cli/src/ngtsc/translator/src/translator.js:47:37
node_modules/@angular/compiler-cli/src/ngtsc/translator/src/translator.js:10:17
node_modules/@angular/compiler-cli/src/ngtsc/translator/src/translator.js:16:3)
Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
<code>

</code></pre>

## 🌍  Environment
**Angular Version:**
<pre><code>
Node version :- v14.11.0
NPM version  :- 6.14.8
Angular version :- @angular/cli@10.1.4
</code></pre>

**Comment by petebacondarwin** [comment]
I would suggest that you have a version mismatch between `@angular/compiler` and `@angular/compiler-cli`. (Note that this has nothing to do with `@angular/cli`. Please check which versions you have installed.

**Comment by Anishmourya** [comment]
@petebacondarwin worked for me. Yes, it was a version mismatch issue. I downgraded the compiler-cli version 😄 

npm i @angular/compiler-cli@8.2.14
npm i @angular-devkit/build-angular@0.803.24
