### ISSUE TITLE
Show All not working on api/common/http/HttpRequest

### ISSUE THREAD

**Issue by frederikprijck** [angular/angular#39156]
# 📚 Docs or angular.io bug report

### Description

On the https://angular.io/api/common/http/HttpRequest link, clicking the `Show All` underneath the constructor doesnt expand the section. Clicking anywhere else (e.g. on 3 overloads) works fine.

### What's the affected URL?
https://angular.io/api/common/http/HttpRequest

### Reproduction Steps
- Scroll to the constructor section
- Click Show All or the Carret behind it

### Expected vs Actual Behavior
It should expand while currently it does not.

## 📷Screenshot
![image](https://user-images.githubusercontent.com/2146903/95329395-2815a580-08a7-11eb-905e-16367ba47cf6.png)

## 🔥 Exception or Error
N/A

### Browser info
Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by petebacondarwin** [comment]
The `Show All` is wrapped in an `<a>` tag, which is blocking the click from reaching the enclosing `<summary>` tag.
Removing the `<a>` wrapper fixes the behaviour but messes up the styling. So I think just a bit of tweaking in 
https://github.com/angular/angular/blob/0681a20d2804c8d5e95bbd7babd7998a58655db8/aio/tools/transforms/templates/api/lib/memberHelpers.html#L135-L139
and
https://github.com/angular/angular/blob/d8f9ec5291236d48a2c191297d4431f7820402f7/aio/src/styles/2-modules/_api-pages.scss#L33-L48

is needed.

**Comment by marcinmilewicz** [comment]
I'd take it
