### ISSUE TITLE
Recommendation clarification for Observables

### ISSUE THREAD

**Issue by kkamkou** [angular/angular#39155]
### Description
I would like to ask the core developers to clarify/expand the following sentence in the documentation for [Observables](https://angular.io/guide/observables):  "_They are used frequently in Angular and are the **recommended** technique for event handling, **asynchronous programming**, and handling multiple values._".

**Problem:**
_asynchronous programming_ here is a little bit wide. In some cases it might be interpreted as "do not use promises at all" [1][2]. As this is an official documentation and people who start to dive into angular tend to read documentation as a single truth, I would like to reduce a number interpretations.

**important:** this issue is not about observables vs promises.

---
**[1]**: as for some people...
1. learning two concepts (promises/observables) is irrational as they can concentrate on a single concept (but as angular recommends to use observables, the choice is obvious);
2. `async` and `await` aren't in a comfort zone;
3. who has never worked with event driven APIs (example: node.js) (to get a feel for the difference in these concepts) is not clear when to use promises as the observable is more powerful (read: rxjs) and with canceling.

**[2]**: which is not the case according the angular codebase itself where we can find promises.

---

### Proposal
1. Add a new clarification describing why/when promises should (not) be used and (one of)
a. To remove _asynchronous programming_ from the mentioned paragraph.
b. Keep _asynchronous programming_
2. Or remove the recommendation part completely (_and are the recommended technique for event handling, asynchronous programming, and handling multiple values_.).
3. Replace "the recommended technique" with "a technique".

### URL:
https://angular.io/guide/observables

### Similars
- [When to use Observables and Promises in Angular](https://stackoverflow.com/questions/55129131/when-to-use-observables-and-promises-in-angular?rq=1)
- [When to use Promise over observable?](https://stackoverflow.com/questions/50269671/when-to-use-promise-over-observable)
and so on.

**Comment by Airblader** [comment]
Personally I'd prefer Angular stay away from making opionated recommendations that fall outside the actual framework on what to do or how to do it unless it is *objectively* better.

The framework doesn't need to dictate whether you're ever allowed, recommended or discouraged from using promises or async await any more than it needs to tell you how to format your code or which IDE to use. 

If you prefer promises, use them, and convert between them and observables as needed (the framework APIs are what they are). If you prefer sticking to one concept or dislike frequent conversions, use observables. It doesn't affect if or how the framework works.

Documenting things that don't actually have anything to do with the framework just blows up the documentation, and ultimately that doesn't help newcomers either.

Just my 2c obviously.

**Comment by kkamkou** [comment]
@Airblader you propose to remove the whole sentence? _and are the recommended technique for event handling, asynchronous programming, and handling multiple values._? am I correct?

**Comment by Airblader** [comment]
I think that Angular's documentation on observables should be limited to describing what they are (since they're used in the framework) and, possibly, why Angular chooses to use them over promises. But it shouldn't say »and this is how we recommend you deal with things in your application«. 

Given that the only thing I slightly disagree with in the sentence you're quoting is the phrase "the recommended technique", it could be replaced with "a technique".

**Comment by kkamkou** [comment]
>  Angular chooses to use them over promises...

If you dig the core module you'll find the usage of promises. My assumption is that angular uses both of them in context.

Nevertheless, removing _"the recommended technique"_ would decrease a number of interpretations:
_"Observables provide support for passing messages between parts of your application. They are used frequently in Angular and are a technique for event handling, asynchronous programming, and handling multiple values."_
