### ISSUE TITLE
Be more accurate in minimal supported browser versions

### ISSUE THREAD

**Issue by maximelafarie** [angular/angular#39152]
# 📚 Docs or angular.io bug report

### Description

The supported browser versions listed [here](https://github.com/angular/angular/edit/master/aio/content/guide/browser-support.md) aren't that much accurate and make hard the explanations to bring to the client if it needs to upgrade each collaborator's browser. 

### What's the affected URL?**
https://angular.io/guide/browser-support
<sub>(source: https://github.com/angular/angular/edit/master/aio/content/guide/browser-support.md)</sub>

### Expected vs Actual Behavior**

What could be nice would be to tell a range or a minimal supported version for the given Angular release (as it's done for Angular v2 (c.f. screenshot down below).

E.g.: for Chrome or Firefox, `latest` is really not accurate since it's hard with that to know if the client's browser matches or not a valid browser version for the project's Angular version.

## 📷Screenshot

Current documentation (not accurate):
![image](https://user-images.githubusercontent.com/5319267/95311645-2be8fe00-088e-11eb-80e3-47385bf88ce3.png)

Old Angular v2 documentation (more accurate):
![image](https://user-images.githubusercontent.com/5319267/95311702-4622dc00-088e-11eb-875f-c31af5c7104c.png)

**Comment by petebacondarwin** [comment]
I believe we switched to using `latest` because evergreen browsers are generally kept up to date on user's machines.

**Comment by josephperrott** [comment]
Closing out as this was determined to be the best way we can express our browser support.  As Pete mentioned, since evergreen browsers are kept up to date on user machines, the understanding/expectation is that all users on evergreen browsers are already on the latest from those browsers.
