### ISSUE TITLE
Lazy Loading documentation should be in Best Practices

### ISSUE THREAD

**Issue by aikidave** [angular/angular#39161]
# 📚 Docs or angular.io bug report

### Description

Currently, our documentation for lazy loading is here:

https://angular.io/guide/lazy-loading-ngmodules

Lazy loading is a common best practice when building an Angular application. It would be better if it we made this content more prominent and moved it to the Best Practices section.

### What's the affected URL?**
https://angular.io/guide/lazy-loading-ngmodules

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by eduardbme** [comment]
#39532

**Comment by eduardbme** [comment]
#41378

**Comment by aikidave** [comment]
Content moved to Best Practices section!
