### ISSUE TITLE
Changes  in modules not detected unless I restart server.

### ISSUE THREAD

**Issue by kaleem68** [angular/angular#39178]
Weird behavior I'm noticing with an angular 10 module.

Considered a component XYZ is declared in AppModule
Let's say I remove the XYZ component from the Declaration array in the AppModule. The application does not complain that when it reloads. If I restart the server it then complains components XYZ is not defined inside any module.
Conclusion: especially removing a component from Declaration, Export array from angular is not detected unless restarting the server, however adding a Component to Declaration, Export Array is detected on auto-reload.

**Comment by JoostK** [comment]
This is a bug with the CLI and an issue is available here: angular/angular-cli#18707. Closing this one as duplicate.
