### ISSUE TITLE
DatePipe needs review and potentially breaking changes

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#3917]
The date pipe is quite limited considering the implementation in Angular v1. We should review the code and decided an any breaking changes that might need to happen. Especially:

- the dependency on internationalization apis (can we rely on this spec?, do we have a polyfill?)
- are the default formats and formatting flags aligned with a spec or Angular v1?
- compare the feature set to Angular 1 (e.g. the ISO string input is currently not supported)
- the filter is stateful which will cause perf issues
- do we have a plan for switching locales?

**Comment by pkozlowski-opensource** [comment]
@IgorMinar our early input on using internationalization apis: https://github.com/angular/angular/issues/3333

In short: this might not be the best path to move forward...

**Comment by IgorMinar** [comment]
Thanks for linking the issue.

**Comment by IgorMinar** [comment]
@vicb reviewed this and determined that while the polyfills need a lot of love, the general direction is ok, so let's keep things as they are..
