### ISSUE TITLE
Unable to access json files from angular assets through HttpClient when they start with the letter 'q' or 'Q'.

### ISSUE THREAD

**Issue by mahidhar96** [angular/angular#39177]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/common/http/HttpClientModule .
I'm not sure, but I think it is because of this package as I'm using HttpClient to access the JSON files.

### Is this a regression?
I'm not sure never tried this on previous versions.

### Description

I'm making a simple angular application which reads an assets JSON file containing a list (through HttpClient) and reads it and prints it on the web page in a paragraph. When the JSON file doesn't start with the letter 'q' or 'Q', it works fine but when either of those letters are used it throws an error.

In the Stackblitz link change the "json_name" variable to "uant", it will work, but with "Quant" and "quant", it won't work. Please check the console for errors. I made 3 json files in assets (Quant.json,quant.json,uant.json). This problem is only with firefox and not with chromium based browsers. I raised a bug in firefox as well (https://bugzilla.mozilla.org/show_bug.cgi?id=1669951).

Here's a link to Stackblitz which demonstrates the problem. 

Is this a bug or am I making a mistake?

Thanks in advance for any help.

## 🔬 Minimal Reproduction

Here's a stackblitz link for minimal reproduction of the issue 
(https://stackblitz.com/edit/amgularq-cqvecz?devtoolsheight=33&file=src/app/app.component.ts)

## 🔥 Exception or Error
<pre><code>
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null,
    "headers": {}
  },
  "status": 0,
  "statusText": "Unknown Error",
  "url": "http://localhost:4200/assets/data/Quant.json",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for http://localhost:4200/assets/data/Quant.json: 0 Unknown Error",
  "error": {
    "isTrusted": true
  }
}

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.8
Node: 12.13.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1000.8
@angular-devkit/core         10.0.8
@angular-devkit/schematics   10.0.8
@schematics/angular          10.0.8
@schematics/update           0.1000.8
rxjs                         6.5.5

</code></pre>

**Anything else relevant?**
Yes, only in Firefox, version: 81.0.1 (64-bit) and not in Chromium based browsers.

**Comment by petebacondarwin** [comment]
It works for me in FF 80.0.1 and 81.0.1 (on OS/X) - and obviously on Chrome.

**Comment by mahidhar96** [comment]
> 
> 
> It works for me in FF 80.0.1 and 81.0.1 (on OS/X) - and obviously on Chrome.

Let me uninstall and reinstall firefox and try.

**Comment by sonukapoor** [comment]
Works for me as well on Windows 10.

Tested on:

- FF 74.0 (64-bit)
- FF 81.0.1 (64-bit)
- Chrome 85.0.4183.121

**Comment by mahidhar96** [comment]
guys, I'm really sorry, some add-on was blocking it. I removed it and everything is working. I'm really sorry. and thanks a lot for all of your responses.

**Comment by petebacondarwin** [comment]
No problem.
