### ISSUE TITLE
Canonical list of all benchmarks?

### ISSUE THREAD

**Issue by hterkelsen** [angular/angular#3918]
Is there a canonical list of all benchmarks? I would also like to know which ones are supported for both JS and dart2js, just JS, or just dart2js. It seems like the only way to find out now is to go to each benchmark source file and see which benchmarks it declares.
@tbosch

**Comment by tbosch** [comment]
Harry,
there is none in the sense of a file that lists all of them.
We calculate them via a glob over dist/js/cjs/**/*_perf.js and exclude some
for JS / Dart in the protractor-js.conf.js / protractor-dart2js.conf.js.

Tobias
