### ISSUE TITLE
Child Component Reuse and Navigation Question

### ISSUE THREAD

**Issue by Javaman2** [angular/angular#39183]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

Consider these routes.

```
  {
      path: "main",
      component: MainComponent,
      canActivate: [canActivateService],
   },
   {
      path: "main/:id",
      component: SpecificComponent,
      canActivate: [canActivateService],
   },
``` 
The MainComponent contains three other components, PersonComponent, AddressComponent, and FamilyMemberComponent.  By default, it is used to enter a new person, address and family members.  Navigation to  /main works perfectly.  User enters in data and it is saved no problem.

The SpecificComponent contains the MainComponent which is to display a specific person, addresses and family members.

I am having problems with the SpecificComponent not updating when navigation occurs.  I suspect the default route re-use strategy is getting in the way for the contained MainComponent.  But because the MainComponent is not actually navigated to, rather it's contained in the SpecficComponent I don't understand why a new route to the SpeficificComponent doesn't inject the actual person data?

I did find this to work when actually using the Navigate function. But as mentioned above I'm not Navigating, just re-using the MainComponent. 

```
//browser is already on /pathName/oldID, 
 //this means our Routes are correct

 let newLocation = `/pathName/${newID}`;
 // override default re use strategy
 this.router
    .routeReuseStrategy
    .shouldReuseRoute = function () {
        return false;
 };
 this.router
   .navigateByUrl(newLocation)
   .then(
   (worked) => {
        //works only because we hooked 
        //the routeReuseStrategy.shouldReuseRoute above
   },
   (error) => {
    debugger;
    }
 );
```
 

## 🔬 Minimal Reproduction

 https://stackblitz.com/...
I'll see if I can create a stackblitz on this issue.

## 🔥 Exception or Error
<pre><code>

The error is simply re-use of a child component doesn't reload/refresh with new data.  The only routing that is done, is via the url, which by default opens to Main, then by appending an ID and pressing enter. I'm trying to get the new URL to reload the data based on a Specific person. 

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.3
Node: 12.18.0
OS: win32 x64

Angular: 10.0.4
... animations, common, compiler, compiler-cli, core, forms     
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.11
@angular-devkit/build-angular     0.1000.3
@angular-devkit/build-optimizer   0.1000.3
@angular-devkit/build-webpack     0.1000.3
@angular-devkit/core              10.0.3
@angular-devkit/schematics        10.0.3
@angular/cdk                      10.1.0
@angular/cli                      10.0.3
@angular/material                 10.1.0
@ngtools/webpack                  10.0.3
@schematics/angular               10.0.3
@schematics/update                0.1000.3
rxjs                              6.6.0
typescript                        3.9.7
webpack                           4.43.0

</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
