### ISSUE TITLE
i18n: localize message extraction producing incorrect `equiv-text` values

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#39195]
(See https://github.com/angular/angular/issues/38711#issuecomment-706079727 for original report)

Extraction of i18n messages from the following template HTML:

```html
<ng-container i18n="Update @@update"> <b>{{value1}}:</b> current {{value2}} to new {{value3}} </ng-container>
```

**Without ivy:** (ctype attributes removed for clarity)
```xml
<source>
  <x id="START_BOLD_TEXT" equiv-text="&lt;b&gt;"/>
  <x id="INTERPOLATION" equiv-text="{{value1}}"/>:
  <x id="CLOSE_BOLD_TEXT" equiv-text="&lt;/b&gt;"/> current
  <x id="INTERPOLATION_1" equiv-text="{{value2}}"/> to new
  <x id="INTERPOLATION_2" equiv-text="{{value3}}"/>
</source>
```

**With ivy:**
```xml
<source>
  <x id="START_BOLD_TEXT" equiv-text="&lt;b&gt;{{value1}}"/>
  <x id="INTERPOLATION" equiv-text="{{value1}}"/>:
  <x id="CLOSE_BOLD_TEXT" equiv-text="&lt;/b&gt; "/> current
  <x id="INTERPOLATION_1" equiv-text="{value2}} "/> to new
  <x id="INTERPOLATION_2" equiv-text="{value3}} "/>
</source>
```

It seems that there is some offsetting going on, which is making the start and end points in the equiv-text appear in the wrong place. I'll need to debug into this but since these equiv-text attributes are primarily to aid the translator's job, it will not be high on my priority list. Hopefully I can take a look at it later next week or the week after.

**Comment by petebacondarwin** [comment]
OK, so I did some debugging and this issue is caused by us skipping "leading trivia characters" thanks to this https://github.com/angular/angular/commit/304a12f0271a08c447c1d1c12fa7dd99baf1f983.

The problem appears because the i18n message begins with a leading space, which is skipped when computing the source-span for the start of the i18n message. This appears to make the source-spans for the inner pieces out of sync.

**Comment by petebacondarwin** [comment]
Actually things are more complex than just that, although that is part of it... 
It seems that there are various places where we are mapping back and forth between source-spans and parsed content, which is causing some source-spans to get out of sync.
I think this needs some considerable thought...

**Comment by bougnat12** [comment]
I made some tests with last Angular 11 and I always have bad translation:

```xml
    <unit id="MAD.confirmDeleteModalMsg">
      <notes>
        <note category="location">src/app/components/setup/zone/detail/zone-detail.component.html:14,16</note>
        <note category="location">src/app/components/setup/wall/panel-setup/panel-setup.component.html:56,58</note>
        <note category="location">src/app/components/setup/vc/setup-panel/vc-setup-panel.component.html:10,12</note>
        <note category="location">src/app/components/setup/ps/setup-panel/ps-setup-panel.component.html:7,9</note>
      </notes>
      <segment>
        <source> Confirm delete <ph id="0" equiv="INTERPOLATION" disp="e {{uiName"/>?
</source>
      </segment>
    </unit>
```

for the original text to translate:

```html
<mad-modal-confirm i18n="@@MAD.confirmDeleteModalMsg" i18n-title="@@psSetupPanel.modalConfirmTitle" title="Delete Power Supply" size="md" id="deletePowerSupplyButton" (closed)="deletePowerSupplyConfirm($event)">
  Confirm delete {{uiName}}?
</mad-modal-confirm>
```

I'm really disappointed because I like the new Angular 11 version but I cannot migrate my project with this show stopper.

For me it's not corrected and I don't understand why this issue was closed.

**Comment by petebacondarwin** [comment]
@bougnat12 see #39671
