### ISSUE TITLE
ngOnChange doesn't work well.

### ISSUE THREAD

**Issue by SuperDeveloper10** [angular/angular#39197]
ngOnChange , it has serious problem.
I worked with log. but it show different result in two lines.

**Comment by sonukapoor** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
