### ISSUE TITLE
feat(common): DatePipe default option(s) injection token 

### ISSUE THREAD

**Issue by Totati** [angular/angular#39194]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/common

### Description
There's no option for the DatePipe to override the default format: 'mediumDate', or set timezone with injection token.

### Describe the solution you'd like
  It would be really good to configure other attributes of the DatePipe with an injection than LOCALE. We use 'shortDate' format for 85% of the times (120/140) - 10% is 'short' and 5% is custom, never 'mediumDate', and we have to write it out every single time. 

### Describe alternatives you've considered
 I know we could extend the date pipe, and set it there, but then I should force our teem to use it against the built in one.

**Comment by petebacondarwin** [comment]
Why is overriding the `DatePipe` any more difficult than requiring your team to add a provider for the default pipe format?
If you put your overridden `CustomDatePipe` into an `NgModule` that the team import, and it uses the same `date` name, then it will be used throughout the application instead of the one in `@angular/common`.

**Comment by Totati** [comment]
Providing a default config for the `DatePipe` for example in the `AppModule` is easier than creating a new module, extend the `DatePipe`, and then import it in every other module too. 

> If you put your overridden `CustomDatePipe` into an `NgModule` that the team import, and it uses the same `date` name, then it will be used throughout the application instead of the one in `@angular/common`.

I did not know it is possible to create pipes with the same name. How does Angular now which one to use? What if I make 3 pipes with the same name? Is that a good practice?

**Comment by petebacondarwin** [comment]
Sorry, I think I assumed that you would provide such a shared `NgModule` to each of your projects that needed it. 
If you provide a pipe that has the same name as a previous pipe, the last one in wins.
See https://stackblitz.com/edit/ivy-ycjczd?file=src%2Fapp%2Fapp.component.html for an example.

**Comment by Totati** [comment]
[Oh I didn't see that comming](https://stackblitz.com/edit/ivy-vu8r8p?file=src%2Fapp%2Fapp.module.ts), it sound weird, but I guess it's fine then. 
Thank you!
