### ISSUE TITLE
`ng xi18n` duplicating strings in HTML & TS

### ISSUE THREAD

**Issue by acalvo** [angular/angular#39198]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No (AFAIK)

### Description

If you have the same string twice in HTML templates (ex. `<span i18n>Some string</span>`), `ng xi18n --ivy` extracts it once. That's OK. But if you have that same string in a TS file (i.e., ``$localize`Some string` ``), its extracted twice (with different IDs) when running `ng xi18n --ivy`:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en-US" datatype="plaintext" original="ng2.template">
    <body>
      <trans-unit id="8321000940098097247" datatype="html">
        <source>Some text</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.ts</context>
          <context context-type="linenumber">10</context>
        </context-group>
      </trans-unit>
      <trans-unit id="5dbba0a3da8dff890e20cf76eb075d58900fbcd3" datatype="html">
        <source>Some text</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">334</context>
        </context-group>
      </trans-unit>
    </body>
  </file>
</xliff>
```

## 🔬 Minimal Reproduction

Repo: https://github.com/acalvo/ng-xi18n-dup

See this commit (over a clean `ng new` project): https://github.com/acalvo/ng-xi18n-dup/commit/cf72e7795069811712c9340382cf29d8d1275d36

## 🔥 Exception or Error

Not an error, just dup strings in the resulting XLF file.

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.1.6
Node: 12.2.0
OS: darwin x64

Angular: 10.1.5
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.6
@angular-devkit/build-angular   0.1001.6
@angular-devkit/core            10.1.6
@angular-devkit/schematics      10.1.6
@angular/cli                    10.1.6
@schematics/angular             10.1.6
@schematics/update              0.1001.6
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Anything else relevant?**

Nope.

**Comment by petebacondarwin** [comment]
This is working as expected. Messages generated by calls to `$localize` in application code use the new more resilient message id format.
(Actually messages in templates also use this format, but they also support the legacy message id format if the `enableI18nLegacyMessageIdFormat` is not set to `false`. Currently the default is `true` but that will change in the future.
You can read more about this option here: https://github.com/angular/angular/blob/4a1c12c773f14dbfc5db61087f415d56f60127cf/packages/compiler-cli/src/ngtsc/core/api/src/public_options.ts#L312-L321

If you only want to have a single message id in your translation files for messages that appear in a template and in application code then you should use the new format. This will work with both messages.
If you are starting from scratch and do not have any legacy translation files to support, then you might like to try turning `enableI18nLegacyMessageIdFormat` off in your tsconfig.json, which will result in only the new message format being used throughout.

**Comment by acalvo** [comment]
Oh, yes! That's exactly what I was looking for! 😍

Adding
```json
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false
  }
```
in my `tsconfig.json`  worked like a charm. Thanks a lot! 😄
