### ISSUE TITLE
Form controls should not require <form>

### ISSUE THREAD

**Issue by mhevery** [angular/angular#3919]
See: http://plnkr.co/edit/5j4kMAlnV5dBstDxG6ou?p=preview
and Working: http://plnkr.co/edit/XIJwnPHh5o1MpalxsZRq?p=preview

The issue is:
- missing `FORM_BINDINGS`
- missing `<form>` around the `<input>`

`<form>` should be optional

**Comment by mhevery** [comment]
This works correctly because `ng-control` requires container which is provided by `<form>`

**Comment by jorgeunimicro** [comment]
That form is always invalid. It is not working.
