### ISSUE TITLE
ERROR NullInjectorError: StaticInjectorError(AppModule)[RouterScroller -> ViewportScroller]: Angular 6

### ISSUE THREAD

**Issue by roykathurima** [angular/angular#39191]
Hello... my project builds without any errors but a few warnings as you can see below...
![UA1](https://user-images.githubusercontent.com/31662354/95548186-3b428580-0a0d-11eb-9636-62e9de91c379.PNG)

However, when I open the it on the browser, it shows a blank page with the following error in the console...
![UA2](https://user-images.githubusercontent.com/31662354/95548190-3d0c4900-0a0d-11eb-9a20-511dbbf55374.PNG)

This is my package.json file...

{
  "name": "ultra-agent-app",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "ngcc"
  },
  "private": true,
  "engines": {
    "node": ">6.9.4",
    "npm": ">4.2.0"
  },
  "dependencies": {
    "@agm/core": "^1.0.0-beta.5",
    "@angular/animations": "^6.1.9",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.0.0-rc.1",
    "@angular/compiler": "^10.0.11",
    "@angular/compiler-cli": "^10.0.11",
    "@angular/core": "^10.1.5",
    "@angular/forms": "^6.0.0-rc.1",
    "@angular/http": "^6.0.0-rc.1",
    "@angular/material": "^6.4.7",
    "@angular/platform-browser": "^6.0.0-rc.1",
    "@angular/platform-browser-dynamic": "^6.0.0-rc.1",
    "@angular/router": "^6.0.0-rc.1",
    "angular-star-rating": "^4.0.0-beta.3",
    "angularfire2": "^5.0.2",
    "bootstrap": "^4.5.2",
    "chart.js": "^2.9.3",
    "core-js": "^2.5.4",
    "css-star-rating": "^1.2.4",
    "firebase": "^7.22.0",
    "html2canvas": "^1.0.0-alpha.12",
    "jquery": "^3.5.1",
    "jspdf": "^1.4.1",
    "ng-pick-datetime": "^6.0.16",
    "ng2-charts": "^2.2.3",
    "ngx-embed-video": "^0.3.0",
    "ngx-material-timepicker": "^2.8.3",
    "popper": "^1.0.1",
    "popper.js": "^1.16.1",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.3.3",
    "typescript": "^4.0.2",
    "zone.js": "^0.8.24"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.12.4",
    "@angular-devkit/schematics": "^10.0.7",
    "@angular/cli": "~6.0.0-rc.4",
    "@angular/language-service": "^6.0.0-rc.1",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1"
  }
}

What could be the issue....

**Comment by roykathurima** [comment]
I am Using Angular 6 for the project

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

You're using different versions of Angular framework/CLI packages. Please correct them to a single Framework version and its corresponding CLI version.
