### ISSUE TITLE
Nested routing (poor docs)

### ISSUE THREAD

**Issue by bagatka** [angular/angular#39200]
# 📚 Docs extension 

### Description

I had to make nested routing. But there is no such information in docs.

### What's the affected URL?**
https://angular.io/api/router/Route#lazy-loading

### Reproduction Steps**

The hole app is based on routing. Every page is shown via `<router-outlet></router-outlet>`
I had to apply `<router-outlet></router-outlet>` inside the component, that already shown via `<router-outlet></router-outlet>`
I could make it with the only one `<router-outlet></router-outlet>`, but it will cause repetition code and the component will be reloaded each `routerLink` click.

## 📷Screenshot

![ezgif com-gif-maker](https://user-images.githubusercontent.com/45293863/95606967-c0588980-0a63-11eb-98ad-c77279b121e9.gif)

Menu (one the left) is the first `<router-outlet></router-outlet>`
Selected menu item (one the right) is nested `<router-outlet></router-outlet>`.

## Code

This solved the task. Maybe, it's possible to add something like that in docs. Something like a small example for developers.

### app-routing.module.ts
```ts
...
const routes: Routes = [
  {
    path: 'admin', loadChildren: () => import(`./admin-control-screen/admin-control-screen-routing.module`)
      .then(m => m.AdminControlScreenRoutingModule)
  }
];

@NgModule({
  imports: [RouterModule.forRoot(routes, {enableTracing: false})],
  exports: [RouterModule]
})
...
```
### admin-control-screen-routing.module.ts
```ts
...
const routes: Routes = [
  {
    path: '', component: AdminControlScreenComponent, children: [
      {
        path: 'films',
        loadChildren: () => import(`./admin-films/admin-films-routing.module`).then(m => m.AdminFilmsRoutingModule)
      },
      {
        path: 'cinemas',
        loadChildren: () => import(`./admin-cinemas/admin-cinemas-routing.module`).then(m => m.AdminCinemasRoutingModule)
      },
      {
        path: 'shows',
        loadChildren: () => import(`./admin-shows/admin-shows-routing.module`).then(m => m.AdminShowsRoutingModule)
      },
      {
        path: 'services',
        loadChildren: () => import(`./admin-services/admin-services-routing.module`).then(m => m.AdminServicesRoutingModule)
      },
    ]
  }
];

@NgModule({
  imports: [
    RouterModule.forChild(routes)
  ],
  exports: [RouterModule]
})
...
```
### admin-cinemas-routing.module.ts
```ts
...
const routes: Routes = [
  {
    path: '', component: AdminCinemasComponent, children: [
      {path: 'add', component: AdminAddCinemaComponent},
    ]
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
...
```

## 🌍  Code example (at the moment of issue creation in user-and-admin-pages-upgrade branch)

https://github.com/bagatka/Cinema

**Comment by aikidave** [comment]
Hi @bagatka! You are correct! We do not document this feature very well. There is some information available in the Tour of Heroes tutorial (https://angular.io/guide/router-tutorial-toh#named-outlets), but it is difficult to find.

The writing team and I will look into addressing this issue. Thank you for bringing it to our attention!

**Comment by atscott** [comment]
@aikidave This is about children routing and lazy loading which is covered in [milestone 4](https://angular.io/guide/router-tutorial-toh#milestone-4-crisis-center-feature) and [milestone 6](https://angular.io/guide/router-tutorial-toh#milestone-6-asynchronous-routing) of the tour of heroes. I'll leave it to you to decide if this is enough or if we should do something more (like adding a link to these sections of the tutorial from the [api docs](https://angular.io/api/router/Route#lazy-loading))

**Comment by aikidave** [comment]
Hi @bagatka ! Thank you for opening this issue. I did some checking and I can confirm what @atscott points out. We have several areas of the documentation that describe nested, or child, routes. For example: https://angular.io/guide/router#nesting-routes.

Closing this issue for now; happy to discuss the matter further if needed!
