### ISSUE TITLE
Improve ControlValueAccessor

### ISSUE THREAD

**Issue by r-shakeri** [angular/angular#39213]
# 🚀 feature request

### Description
 Hello there, thank you for giving us `ControlValueAccessor` feature to use, i want to know is it possible to have more access on it in the future? like making a form with main implementation including main validators... with `ControlValueAccessor` and giving it more options like more validations in different parent forms. i mean giving additional validations or even accessible to enable/disable each `formControl` of `ControlValueAccessor` based on the parent form?

### Describe the solution you'd like
 I made a basic `userForm` using `ControlValueAccessor` and use it in both `registerUserForm` and `updateUserForm`. both `registerUserForm` and `updateUserForm` have same validations and different ones, I put same ones in basic `userForm` and now for each different validation i want to set it from its parent form either `registerUserForm` or `updateUserForm`.
also i have the same senario for disabling inputs of `userForm` based on the parent form.

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
