### ISSUE TITLE
Add the Ability to Update RouteParams Without Reloading Component

### ISSUE THREAD

**Issue by IAPark** [angular/angular#3921]
I've been asking around on Gitter for the last couple days and not really getting much of a response so I thought I would post something here with the assumption that no good way to do this already exists. There's a fair change this is not the case, but I certainly couldn't find anything after some brief digging in the source.

I'm trying to to set up linking to particular projects in a list of projects I have on a personal website I'm creating for myself. I've got linking to a particular project working fine, but ideally I'd have the URL update as the user (aka me) scrolled so that I could just copy the URL and know it would take me back to the project I was looking at. As far as I can tell there is no good way of doing this. I can obviously manually edit the url, but this would make any code a I wrote much less reusable especially relevant given I was even thinking about making this into a directive. Is there any good way to do this at the moment?

If not I think it makes sense to add something like RouteParams.set(param: string) to allow the user to update the params without calling [Router.navigate()](https://github.com/angular/angular/blob/master/modules/angular2/src/router/router.ts#L169). Alternatively it might be better to add a method to Router to update the current instruction without calling [RouterOutlet.activate()](https://github.com/angular/angular/blob/master/modules/angular2/src/router/router_outlet.ts#L47). 

If there is indeed not already a way to do this, I could probably implement this myself. With access to [stringifyInstruction()](https://github.com/angular/angular/blob/fa2c6791b4c0b98e00b213e33751e082aee9c44b/modules/angular2/src/router/instruction.ts#L48) which doesn't seem to exist in the finished distribution and [Location.go()](https://github.com/angular/angular/blob/fa2c6791b4c0b98e00b213e33751e082aee9c44b/modules/angular2/src/router/location.ts#L51) which does, it shouldn't be too complicated.

**Comment by cghislai** [comment]
you can use the 'canReuse' 'onReuse' hooks. (https://github.com/angular/angular/blob/master/modules/angular2/src/router/interfaces.ts#L113)

**Comment by IAPark** [comment]
Hum that makes sense. So I'd need to check if it was just changing the params and the just tell it to reuse. There isn't any way I can do this from a directive though right? But then again I don't think I could with anything I was talking about either.

**Comment by btford** [comment]
@matsko and I were talking about this– I think it's an important feature.

We want to provide different options for debouncing URL updates, and for pushing history state changes.

For now @cghislai is right, you should implement canReuse to decide whether or not to reinstantiate.

**Comment by IAPark** [comment]
Is there anything I can do to help move this forward. This is obviously a big enough change that I shouldn't just go ahead and implement it my way as it will be important for a bunch of things, but at the same time having created the ticket I feel a bit guilty not doing anything about it. Is the idea to do basically what I talked about and implement an in essence Router.navigate_instruction/Router.navigate method that does not not update the router among other things or is this planned to be more abstract than that.

The only real point that I can add is that the canReuse function will work fine for Components, but one of the places pushing history might be nice would be Directives. An example tying into my earlier example is that it might be nice to be able to write a directive targeting an attribute where you can just set a element as a scroll location and have it both subscribe to routing changes scroll based on them and update the URL based on the current position. The first part can definitive be done though it might be a bit hacky depending on how easy it is to get the parent Component of a Directive

Also side note. As you might have guessed I'm a bit new to the world of Angular open source development and even programming as I'm just a Junior CS major, but I'm a bit confused by terminology. What do you mean by "debouncing URL updates". Are you just talking about rate limiting updates?

**Comment by btford** [comment]
@IAPark I appreciate the offer, but I think @matsko, @IgorMinar, and I need to sit down and design how this should work. After we have an idea of how this should work, I'd by happy to have your help implementing this feature.

> debouncing

Yep. See http://davidwalsh.name/function-debounce

**Comment by jorgeunimicro** [comment]
@btford will also router implement reuse if you change from one component to other and not just in the same component with different parameters?
I know keep all components in memory is a problem but sometimes, in some apps we want to assume that risk so maybe that could be a startegy like LocationStrategy.

Maybe something like: 
```typescript
bootstrap(App, [
    ROUTER_PROVIDERS,
    HTTP_PROVIDERS,
    provide(RouterStrategy, { useClass: ReuseRoutesStrategy}),
]);
```
Reuse components that have been instantiated will be helpful to maintain the state of the app easily.

**Comment by bennylut** [comment]
I facing similar problem (need to keep the url in sync with the state of some components in the page), Is there any progress on this - any preferred way to accomplish that? 

In the meanwhile - as a work around I am changing the route parameters using `Location.replaceState` but this became really ugly when dealing with both query strings and matrix parameters..

**Comment by zoechi** [comment]
AFAIK this is the default behavior in the new router.

**Comment by vicb** [comment]
Please reopen if still an issue with the new router
