### ISSUE TITLE
[IE11]: Checkbox state and ngModel binding not in sync on calling preventDefault inside click handler

### ISSUE THREAD

**Issue by Amrender-Singh** [angular/angular#39220]
### Description
Currently in our application we have a checkbox with a ngModel binding and a click handler attached to it. We want our checkbox to be checked only if certain business logic is met. To prevent the checkbox from getting checked, we call the event.preventDefault() method inside of our click handler attached to our checkbox element. Though the preventDefault() prevents the checkbox from being checked, but in IE11 it can be observed that the ngModel binding is updated, i.e binded variable has default value set to false, the value now updates to true, but the checkbox state remains unchanged. Also, this can be observed only when we click on the checkbox for the first time, after that on clicking on the checkbox the value remains unchanged if we call preventDefault() method.

### 🔬 Minimal Reproduction
Here, is the plunker for the issue described above:

https://plnkr.co/edit/J29x5S7TTKBjoSXt

### Note
 on looking into the source code. It was found that currently for input checkboxes listen to the change event for model updates. Which can be seen here:

https://github.com/angular/angular/blob/a84976fdfcde45adeba406be48ed979c2010ee57/packages/forms/src/directives/checkbox_value_accessor.ts#L45

It works fine in Chrome/firefox as the change event in these browser is triggered after the click event. So in case we call preventDefault() method in our click event handler the checkbox state is not changed . However in case of IE11 the change event is triggered before the click event.

**Comment by AndrewKushnir** [comment]
Hi @Amrender-Singh,

I looked at the example code and I think you may try to de-sugar the two-way binding and control the behavior in the `ngModelChange` listener, for example:

```
 <input type="checkbox" [ngModel]="checked" (ngModelChange)="clickHandler($event)" />
```

It looks like there are no action items for the framework (since we do not normalize/change event order), so I'm closing this ticket.

Thank you.

**Comment by Amrender-Singh** [comment]
Hi @AndrewKushnir ,
Thanks for suggesting the workaround. But the proposed workaround doesn`t seems to work in our case. As even if we prevent the ngModel binding value from being updated  but the checkbox state toggles regardless of the current model state, i.e if it checked it now becomes unchecked and vice versa. So again the checkbox state and the model are out of sync. So reopening the issue.
Thanks
