### ISSUE TITLE
Duplicated method call when extending the base class with @HostListener

### ISSUE THREAD

**Issue by sviat9440** [angular/angular#39225]
# 🐞 bug report

### Affected Package
`@angular/core`

### Is this a regression?
Yes, the previous version (8.1.2) in which this bug was not present was

### Description
When extend some class, which has a decorator `@HostListener` on some method (e.g. `onInput(): void`), and override this method with another `@HostListener` decorator in child class, method `onInput` will be called twice on the event.

## 🔬 Minimal Reproduction
[StackBlitz](https://stackblitz.com/edit/angular-ivy-6dv4yt?file=src/app/app.component.ts)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.12
Node: 12.16.3
OS: win32 x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.12
@angular-devkit/build-angular      0.901.12
@angular-devkit/build-ng-packagr   0.901.12
@angular-devkit/build-optimizer    0.901.12
@angular-devkit/build-webpack      0.901.12
@angular-devkit/core               9.1.12
@angular-devkit/schematics         9.1.12
@ngtools/webpack                   9.1.12
@schematics/angular                9.1.12
@schematics/update                 0.901.12
ng-packagr                         9.1.5
rxjs                               6.6.3
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

**Comment by jelbourn** [comment]
This is actually working as intended. Child directives/components inherit host bindings/handlers from their parent, so adding another `HostBinding` creates a second one. You can override the `onInput` method without adding `HostBinding` and the binding from the parent will still apply and call the new method implementation.
