### ISSUE TITLE
Issue during installation command "npm install -g botium-cli"

### ISSUE THREAD

**Issue by vinayjeevan** [angular/angular#39224]
During installation of Botium CLI am facing a issue as shown in below, before installing the command "npm install -g botium-cli", installed Node version v12.19.0. 
![Screenshot (250)](https://user-images.githubusercontent.com/68061658/95712072-ba3ff400-0c81-11eb-9d14-388d612c0667.png)
![Screenshot (249)](https://user-images.githubusercontent.com/68061658/95712258-1b67c780-0c82-11eb-83aa-444fd3024d5e.png)

**Comment by JoostK** [comment]
I'm sorry but this issue is not caused by Angular. Please contact the author(s) of botium-cli or file issue on their issue tracker.
