### ISSUE TITLE
query params bug if value if an empty array

### ISSUE THREAD

**Issue by noureddine-taleb** [angular/angular#39239]
# 🐞 bug report

### Description

when you generate query params dynamically when user click something, and you pass an empty array to a query param key. after some iterations ( add and remove query params using "queryParamsHandling: 'merge'" ) you get some extra "&" in the end of the url

this.router.navigate([], {
      relativeTo: this.route,
      queryParams: queryParams,
      queryParamsHandling: 'merge', 
});

I think simple solution for that is for angular, to just check if the query param value is an empty array then treat it like null.

**Comment by atscott** [comment]
Hi @noureddine-taleb, could you please provide a reproduction for this on stackblitz?

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
