### ISSUE TITLE
[RFC]  Drop lifecyle from Directive config

### ISSUE THREAD

**Issue by vicb** [angular/angular#3924]
The current way of subscribing to LC hooks is kind of messy:

```js
   @Directive({
      lifecycle: [LifecycleEvent.OnChanges, ...]
   })
``` 

**In Dart**:

If the `lifecycle` key exists, we use it as the source of truth:
- The `lifecycle` configuration gets generated by the transformer from the implemented interfaces, that is fine,
- For non-transformed code, the `lifecycle` value has priority over implemented interfaces. It's counter-intuitive and might lead to a different behavior vs transformed code.

**In JS**:

The `lifecycle` value has priority over a structural type checking. Once again this could cause unexpected behavior if the `lifecycle` value is no updated when LC hooks are added or removed.

** Proposal**:

Remove the `lifecycle` config option from `Directive`:
- In Dart, you would only have to implement the desired interfaces,
- In JS, you would have to name methods as LC hooks for them to pass the structural type check,
- In TS, the preferred way would be to implement the interfaces as well but the JS way would work equally well.

```js
// Dart & TS (preferred)
class MyDirective implements OnChanges {
  onChanges() {
  }
}

// ES6 & TS (non-preferred)
class MyDirective {
  onChanges() {
  }
}
```

The only pb I can imagine is related to #2898 where @yjbanov wants to remove interfaces from the generated metadata in Dart. What about having a white list of interfaces we want to include there ?

I'd like to collect some thoughts before doing the changes, WDYT @mhevery @yjbanov @vsavkin @jakemac53 @kegluneq ?

_The effort would probably be around .5 to 1 day_

**Comment by mhevery** [comment]
I think this is great, and I would love to see this happen. It is not clear to me if we can do this due to way Dart Transformers work.

**Comment by yjbanov** [comment]
I don't see a conflict with #2898. We either use interfaces in a runtime check `is OnChange` (in dev mode) or we discover them in the transformer and generate lifecycle call sites (and let `dart2js` erase the interfaces later).

Not sure how this would work in TS, as `tsc` erases all information about interfaces.

**Comment by vicb** [comment]
As of today, it seems that the compiler calls [`DirectiveBinding.createFromBinding`](https://github.com/angular/angular/blob/ad1bd5fc11f27380b523e7e94de98debd34201b0/modules/angular2/src/core/compiler/compiler.ts#L118) that in turn [check what interfaces are implemented](https://github.com/angular/angular/blob/ad1bd5fc11f27380b523e7e94de98debd34201b0/modules/angular2/src/core/compiler/element_injector.ts#L241). At some later point we should probably retrieved the metadata generated by the transformer instead. When this is implemented there will be no need for the reflector to have information about implemented interfaces (at least for the LC hooks).

TS (as JS) would use structural type check (`implements OnHook` is optional but would be documented as the best practice).

**Comment by mhevery** [comment]
@vicb can this be refactored somehow so that we could drop this? I really would like to get this breaking change in ASAP.
