### ISSUE TITLE
Current way of view encapsulation does not look correct to me

### ISSUE THREAD

**Issue by cheong00** [angular/angular#39259]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/compiler

### Description
I'm still a newbie in Angular (although have done web programming for 20+ years), so feel free to correct me if I'm wrong in my perspective.

Say when I have page that have the following snippet:
```
<mat-input-field class="foo">
  <mat-label>Foo</mat-label>
  <input mat-input name="txtFoo" [(ngModel)]="currentData.foo" />
</mat-input-field>
```

And then I have another field that named "bar" that has DatePicker. People who used Angular Material will know the whole "Bar" field will be pushed down a little by the button to invoke the datepacker this way, hence make these two fields look unbalanced when be put together side-by-side.

So I added the following CSS rules try to fix it:
```
mat-form-field.foo input { height: 3em; }
mat-form-field.foo span.mat-form-field-label-wrapper { top: 0.3em; }
```

However in the rendered CSS, I saw this for the second rule:
`mat-form-field.foo[_ngcontent-cgh-c299] span.mat-form-field-label-wrapper[_ngcontent-cgh-c299] { top: 0.3em; }`

This don't work as the DOM element for .mat-form-field-label-wrapper is rendered by Angular material component, and therefore carries no _ngcontent-cgh-c299 attribute, only with class "ng-tns-c60-3".

### Describe the solution you'd like
IMO, adding the [_ngcontent-cgh-c299] to the first part of CSS selector should be enough for view encapsulation. There's no need to append it to each-and-every segments of CSS selector.

### Describe alternatives you've considered
Change default behaviour may break (say if the last part is just div or span, it may apply to other components inside the scope but not previously affected), so it would be helpful to see some ViewEncapsulation options be added, or some directive like ::ng-deep that will modify the parsing rule to what I described here.

**Comment by jelbourn** [comment]
This is working as expected- the styles in _your_ component are being encapsulated to only affect elements within your component's template. See this guide for more info: https://material.angular.io/guide/customizing-component-styles

**Comment by cheong00** [comment]
No. While this is working "as expected", we page designers should have final say to how the page look like.

If you Angular folks are going to deprecate ::ng-deep, you have to give us functionality to cover the use case, or I will have no choice but to disable it at all in the future. (say, IMO for page with tag app-page1, just add CSS rule with app-page1.someclass would do, but that's not very Angular)

That said, I still think the original way to do "view encapsulation" is wrong. I request new functionality just because changing the old way can break things as I've mentioned.
