### ISSUE TITLE
Service not treated as singleton when .js extension is added to service

### ISSUE THREAD

**Issue by michaelsimsoe** [angular/angular#39258]
# 🐞 bug report

### Affected Package
nil

### Is this a regression?
nil

### Description
I've got a service with `{provideIn: root}`. If used in multiple components and `.js` is appended to fileending on import path it is apparently not treated as a singleton.

## 🔬 Minimal Reproduction
Stackblitz is not suitable for reproduction. I've made a simple github repo: https://github.com/michaelsimsoe/angular-not-singleton

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.8
Node: 14.4.0
OS: darwin x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cli                      10.0.8
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Anything else relevant?**
nil

Due to my juniorness I'm prepared to take the pain if this is expected behavior or has some obvious explanation. The fix is of course easy. Just remove the .js at the end, but I want to know why it behaves like this with it on.

**Comment by jelbourn** [comment]
Adding this kind of `.js` extension isn't really supported. What's probably happening is that Webpack (under Angular CLI) is actually pulling in two different bundle formats, which you definitely don't want. We strongly recommend not using the `.js` file extensions like this.
