### ISSUE TITLE
loadTranslations with ICU plural expression not working

### ISSUE THREAD

**Issue by aresot** [angular/angular#39269]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/localize

### Is this a regression?

 not sure

### Description

 When I use this
`loadTranslations({
  d6cec643d19c2a2a8370673d27681775093e0322: "{VAR_PLURAL, plural, =0 {No guests1} =1 {Single guest1} other {{$INTERPOLATION} lalala1}}",
});` I am getting this warning in the console:
`There is a placeholder name mismatch with the translation provided for the message "5362348912232916994" ["d6cec643d19c2a2a8370673d27681775093e0322", "589468133713640460"] ("{VAR_PLURAL, plural, =0 {No guests} =1 {Single guest} other {{INTERPOLATION} lalala}}").
The translation contains a placeholder with name INTERPOLATION, which does not exist in the message.`

## 🔬 Minimal Reproduction

 https://github.com/aresot/ng10-localize When running dont forget to use aot `ng serve --aot=true`

## 🔥 Exception or Error
Warning in console:
<pre><code>

`There is a placeholder name mismatch with the translation provided for the message "5362348912232916994" ["d6cec643d19c2a2a8370673d27681775093e0322", "589468133713640460"] ("{VAR_PLURAL, plural, =0 {No guests} =1 {Single guest} other {{INTERPOLATION} lalala}}").
The translation contains a placeholder with name INTERPOLATION, which does not exist in the message.`
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 10.1.0
Node: 12.15.0
OS: darwin x64

Angular: 10.1.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.0
@angular-devkit/build-angular     0.1001.0
@angular-devkit/build-optimizer   0.1001.0
@angular-devkit/build-webpack     0.1001.0
@angular-devkit/core              10.1.0
@angular-devkit/schematics        10.1.0
@angular/cli                      10.1.0
@ngtools/webpack                  10.1.0
@schematics/angular               10.1.0
@schematics/update                0.1001.0
rxjs                              6.6.2
typescript                        3.9.7
webpack                           4.44.1

</code></pre>

**Anything else relevant?**

As you can see in github project other ICU like SELECT is working fine but VAR_PLURAL is having issues.

**Comment by petebacondarwin** [comment]
Note that inside the ICU the placeholder should be `{INTERPOLATION}` not `{$INTERPOLATION}`.

**Comment by aresot** [comment]
Oh that did it. Sorry for false flag.

**Comment by petebacondarwin** [comment]
Great!
