### ISSUE TITLE
items translated by $localize in by custom library angular doesn't extracted

### ISSUE THREAD

**Issue by hessamhoseinkhani** [angular/angular#39261]
# 🐞 bug report

### Affected Package

 The issue is caused by package:
@angular/localize

### Is this a regression?

 no

### Description

 A clear and concise description of the problem...
i'm building my own libraries i'd used to work with "@ngx-translate/i18n-polyfill" since $lcoalize wasn't annonced i'm trying to move on $localize ... for bit of testing it first i tried to use a dummy $localize example in my libraries component then i get build of it and used it in my main project as an package. i expected when i do an extraction for i18n (and $localize) i see my word extracted in xlf files but it wasn't
  

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code>{
  "name": "mig-t",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "translate": "ng xi18n  --output-path ./src/locales --format=xlf2 --ivy && ng run mig-t:xliffmerge",
    "fa": "ng serve --configuration=fa"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.1.1",
    "@angular/common": "~10.1.1",
    "@angular/compiler": "~10.1.1",
    "@angular/core": "~10.1.1",
    "@angular/forms": "~10.1.1",
    "@angular/platform-browser": "~10.1.1",
    "@ngx-i18nsupport/tooling": "^8.0.3",
    "@angular/platform-browser-dynamic": "~10.1.1",
    "@angular/router": "~10.1.1",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1001.1",
    "@angular/cli": "~10.1.1",
    "@angular/compiler-cli": "~10.1.1",
    "@angular/localize": "^10.1.4",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "ng-packagr": "^10.1.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}
</pre>

**Anything else relevant?**

**Comment by hessamhoseinkhani** [comment]
what else information should i provide ?

**Comment by petebacondarwin** [comment]
@hessamhoseinkhani - sorry, I thought I had already commented here!

Please can you provide a runnable example of your problem that I can use to diagnose your problem.

(It is not clear to me if you are running extraction on the library or some test application and how your project is setup.)

**Comment by petebacondarwin** [comment]
Thanks for reporting this issue, @hessamhoseinkhani. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

Specifically, I need a link to a git repository that reproduces this issue.
