### ISSUE TITLE
ngOnChanges Hook not triggered in angular 9

### ISSUE THREAD

**Issue by SathishKumarRajendran** [angular/angular#39260]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, it is working fine angular 7, but issue in angular 9.

### Description

While dynamically changing the property, `ngOnChanges` hook not triggered in angular 9 but it properly triggered in angular 7.

**Angular 7:**

Please refer the below image, here we have used button name hidden click to changes the property. 

![image](https://user-images.githubusercontent.com/53341125/95934502-9ea62c00-0dee-11eb-86de-10f5d95853fa.png)

In angular 7 the `ngOnChanges` hook are triggered properly from angular core level and I am getting changes from the changes parameter.

![image](https://user-images.githubusercontent.com/53341125/95934635-f80e5b00-0dee-11eb-817f-b9d823b85ba4.png)

![image](https://user-images.githubusercontent.com/53341125/95846868-9c4dbe80-0d69-11eb-88ef-ae8b37a60d19.png)

**Angular 9:**

Same as angular 9, `ngOnChanges` hook not triggered, at the time of property changes,

![image](https://user-images.githubusercontent.com/53341125/95935094-0d37b980-0df0-11eb-8750-2d3e07d721cd.png)

![image](https://user-images.githubusercontent.com/53341125/95846926-b38cac00-0d69-11eb-8dc6-7e9cdbc142ad.png)

## 🔬 Minimal Reproduction

Angular 7 sample: https://github.com/kumaresan-subramani/Angular_diagram_7
Angular 9 sample: https://github.com/kumaresan-subramani/Angular_diagram_9

## Steps to reproduce issue

- npm i
- ng serve

Then click button hidden to change the property, then you can reproduce the issue. 

## 🔥 Exception or Error
No

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.10
Node: 10.15.1
OS: win32 x64
Angular: 7.2.16
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.10
@angular-devkit/build-angular     0.13.10
@angular-devkit/build-optimizer   0.13.10
@angular-devkit/build-webpack     0.13.10
@angular-devkit/core              7.3.10
@angular-devkit/schematics        7.3.10
@angular/cli                      7.3.10
@ngtools/webpack                  7.3.10
@schematics/angular               7.3.10
@schematics/update                0.13.10
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

<pre><code>
Angular CLI: 9.1.11
Node: 10.15.1
OS: win32 x64

Angular: 9.1.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.11
@angular-devkit/build-angular     0.901.11
@angular-devkit/build-optimizer   0.901.11
@angular-devkit/build-webpack     0.901.11
@angular-devkit/core              9.1.11
@angular-devkit/schematics        9.1.11
@angular/cli                      9.1.11
@ngtools/webpack                  9.1.11
@schematics/angular               9.1.11
@schematics/update                0.901.11
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Comment by geromegrignon** [comment]
I can't find in which version it was introduced but `ngOnChanges` is now only triggered by changes on properties passed from a parent component through data binding (it isn't triggered anymore in a component where the properties are declared).

**Comment by kumaresan-subramani** [comment]
HI @geromegrignon ,

In that case, how can we suppose to track component's directives changes.

Is there any other alternate way available to handle this?

**Comment by kumaresan-subramani** [comment]
IN (here)[https://github.com/syncfusion/ej2-angular-ui-components/blob/master/components/diagrams/src/diagram/connectors.directive.ts#L251], i hae added `ngdocheck` hook but it is getting triggered but `ngoOnchange` not get triggered

**Comment by geromegrignon** [comment]
Please explain your use case : As the component is responsible of providing data to the directives through inputs, why do you want to listen to the directive changes at the scope of the component?

PS:  there is no hook declared in your last link.

**Comment by kumaresan-subramani** [comment]
@geromegrignon , i have below architecture

parent component
    -- array-base directive
         ---- complex-base directive

When i chnage property in complex directive - i have provided hooks for that directive after this get updated then it update `array-base`. Finally my component get update at `ngAfterContentChecked` hoook.

Here `ngOnChnage` hook not triggere for `complex-base` so i am facing issue


> PS: there is no hook declared in your last link.

That is just an example i have tried it in local like below

https://github.com/kumaresan-subramani/ej2-angular-ui-components/blob/master/components/diagrams/src/diagram/connectors.directive.ts#L227

**Comment by jelbourn** [comment]
This is working as expected; as of Angular 9, lifecycle hooks are cached during creation mode and then re-used for the rest of the application's lifetime. While changing these dynamically worked in previous versions, it was never intentionally supported. I would recommend changing the body of the lifecycle hook to do different things rather than changing the method completely.
