### ISSUE TITLE
Request for script to generate aio examples

### ISSUE THREAD

**Issue by kapunahelewong** [angular/angular#39275]
# 🚀 feature request

### Relevant Package

 This feature request is for aio.

### Description

It would be very helpful if we had a script that we could use to generate new examples for AIO.

### Describe the solution you'd like
A script that you could use a command like `ng new aio-example` that would set up a base example in the examples directory.

### Describe alternatives you've considered
The alternative is to generate an example with the CLI outside of io locally and get everything working first. Then duplicate one of the existing examples, replace the `src` directory, write new e2e tests, and make sure any references (like titles) are for the new app, not the old.

An alternative is to create the same structure by hand and then run yarn to install everything.

We created a PR to add a template example that contributors could copy and fill in, but it would be more efficient to have this as a script instead.

[https://github.com/angular/angular/pull/39273](https://github.com/angular/angular/pull/39273)

Creating this issue as requested per @petebacondarwin 

cc @aikidave

**Comment by petebacondarwin** [comment]
Sadly we can't use `ng new ...` because the CLI will complain that we are already inside a CLI project:

```
The new command requires to be run outside of a project, but a project definition was found at ".../angular/aio/angular.json".
```

**Comment by petebacondarwin** [comment]
I have two proposal, we could implement both:

1) The script will simply create the most basic skeleton of the example (i.e. the markers files, the `src` and `e2e` folders with skeleton files inside). 
2) The script will take a path to a ready made CLI project somewhere and copy over important files, while adding the necessary marker files.

WDYT?

**Comment by gkalpak** [comment]
I have a slight preference for option 1. Plus having the script print (a link to docs with) some useful info, such as how to change the example type, how to update it, how to run tests, etc.

With option 2, I am worried that people might not be sure which parts they can get rid of, so it would be easier to end up with redundant code.

**Comment by petebacondarwin** [comment]
I have a PR almost ready. Let's discuss it there...
