### ISSUE TITLE
Angular pipes and directives could not be used as a global state for all modules?

### ISSUE THREAD

**Issue by Hasnat150822** [angular/angular#39281]
To use Pipes & Directives in all lazy loaded module, I have used shared module in which I import and export these pipes.
I think this is not good approach because if there are many pipes & directives then a module will use all these pipes even some of them is not needed.
Here is the link of my code.
https://stackblitz.com/edit/angulattesting?file=src%2Fapp%2Fcustom-pipes%2Freturn-dash.pipe.ts
So, I think there should be a global way to handle this just like angular global state management.

**Comment by jelbourn** [comment]
Angular's advice here is to always import things where they are used, even if that does end up being verbose; this will let bundlers/optimizers work most effectively on your codebase.
