### ISSUE TITLE
Change Detection Not Working with Routing in Zone-Less Application

### ISSUE THREAD

**Issue by markostanimirovic** [angular/angular#39296]
# 🐞 bug report

<img src="https://user-images.githubusercontent.com/17877290/96185170-ceae1600-0f39-11eb-9687-0bcda9919a20.gif" alt="zoneless-routing-bug" width="600" />

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 No

### Description

Issue happens in zone-less environment when routing is used. If you remove `<router-outlet></router-outlet>` from app component template and put `<app-counter></app-counter>`, everything works fine.

Problem makes `ɵmarkDirty(this)` that is called immediately in `ngOnInit` method of counter component (see bellow **Workaround 1**). Then, when you click on increment or decrement button, `rootContext.flags` is equal to `1 (DetectChanges)` instead of `0 (Empty)`, and because of that, tick is never scheduled:

![schedule-tick](https://user-images.githubusercontent.com/17877290/96188191-9bba5100-0f3e-11eb-8182-c98fad41333f.png)

## 🔬 Minimal Reproduction

1. Clone https://github.com/markostanimirovic/zoneless-routing-bug repo
2. Run `npm install`
3. Run `npm start`
4. Click on increment/decrement buttons, observe that count value is not changed
5. Navigate to Counter 2, observe that count paragraph disappeared
6. Navigate back to Counter, observe that count paragraph disappeared too

**Workaround 1**

1. Open `counter.component.ts` file
2. Comment out lines 24-29
3. Uncomment lines 32-38

**Workaround 2**

1. Open `app.component.ts` file
2. Swap `ɵmarkDirty(this)` with `ɵdetectChanges(this)` on line 21

## 🌍  Your Environment

**Angular Version:** 10.1.6

**Comment by JiaLiPassion** [comment]
This seems to be a bug that when `markDirty()` is called during another `markDirty` and the `rootContext.flags` are not reset. I will create a PR to fix it.
