### ISSUE TITLE
coalesce common expressions

### ISSUE THREAD

**Issue by mhevery** [angular/angular#393]
Currently having `{{user.first}}` and `{{user.last}}` will create 4 records. But we could crate only three records if the `user` record can deliver the change to both of the `first` and `last` record.

**Comment by vicb** [comment]
@mhevery last time we've discussed about that the conclusion was that is was not worth supporting coalescence:
- it would only speed up a few cases (ie the one in your comment above),
- but it would require to store one more pointer in every single records (unused most of the time).

Do you think that the speed up would be worth the increased memory usage ?

**Comment by mhevery** [comment]
2793d47c67db956abe3503ca3faff857d04d8513
