### ISSUE TITLE
Router - Routes Config transform hook

### ISSUE THREAD

**Issue by stephenlautier** [angular/angular#39304]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/router

### Description
Ability to transform/process routes when they are being registered (in order to be filtered/manipulated or so)

### Describe the solution you'd like

```ts
@NgModule({
    imports: [RouterModule.forChild(ROUTES)],
    providers: [
        { provide: RoutesConfigHandler, useClass: AppRoutesConfigTransformer } // register in root
    ],
    exports: [RouterModule]
})
export class AppShellRoutingModule {

}

class AppRoutesConfigTransformer extends RoutesConfigHandler {

    constructor(
        appInfo: AppInfoService, // custom service
    )

    process(routes: Routes): Routes { // if it can take `Routes | Promise<Routes> | Observable<Routes>` as return even better but probably complicates things
        // perform custom logic on routes - validate data, set some data, filter or so...
        return routes;
    }

}

```

### Describe alternatives you've considered
Tried to handle the more angular DI way, however with the router I had no luck.
I tried even custom function for `RouterModule.forChild` (as how it is internally) but still nothing works.

```ts
@NgModule({
    imports: [RouterModule.forChild(ROUTES)],
    providers: [
       { provide: ROUTES, useFactory: validateProcessRoutes, deps: [AppInfoService] },
    ],
	exports: [RouterModule]
})
export class AppShellRoutingModule {

}

function validateProcessRoutes(routes: Routes) {
    // perform custom logic on routes - validate data, set some data, filter or so...
    return routes;
}

```

**Comment by Airblader** [comment]
What would this be useful for, specifically?

**Comment by stephenlautier** [comment]
There are quite a lot of things which you can do with them but essentially iterate through them and perform some checks, add data "dynamically" (e.g. generate data id based on path), exclude routes etc...
You can do some, with a plain function **UNLESS** you need to use a service, then you won't be able to.

A small concreate example would be:

Enable certain routes in `debugOnly` (specified in data),
For example in our apps we control `debugMode` through a service named `AppInfoService` to determine whether its in debug mode or not (there are no async calls, as its done via transfer state), and we have some routes which are only for developers only (or debug), so if its not running in debug mode the route is removed.

**Comment by Airblader** [comment]
And why can't all of this already be achieved with guards, resolvers and url matchers? 

For example, let's consider your debugMode. Either this is purely a build time thing for developers or you want this to be possible even in the live production app. In the first case adding / removing routes at build time is already possible. In the latter case you can use guards.

The config based on route data sounds a whole lot like resolvers to me, though you didn't go into a lot of detail so I'm not sure.

**Comment by Airblader** [comment]
Also this is possibly related to #17145

**Comment by stephenlautier** [comment]
Some things can be handled maybe, but still different than what we expect and some doesn't.
e.g. If you need to validate a route, with a guard/resolver you need to **active** it in order to be validated so its lazy, ideally in such case we do it upfront so it makes our life easier (and don't need navigate through route 1 by 1 in order to find issues).

Other actions if you need it a bit more crosscutting such as breadcrumb or so it uses the route config but not done as a guard, but reacts to navigation events instead, so having some data in the route helps you do some logic.

And in some other cases we do it the other way round, pass data in route config and consume in guard/resolver.

> Also this is possibly related to #17145
The usage of this is not about route matching so I don't think its related to that

This one seems related/possibly duplicate https://github.com/angular/angular/issues/31800

**Comment by Airblader** [comment]
> e.g. If you need to validate a route, with a guard/resolver you need to active it in order to be validated so its lazy, ideally in such case we do it upfront so it makes our life easier (and don't need navigate through route 1 by 1 in order to find issues).

I don't see the difference. In both cases the route has to exist in the application, in both cases the decision is made at runtime. The guard can easily defer the logic to a cached result that you eagerly calculate if for some reason this is absolutely necessary. Either way the requested feature of making routes inaccessible at runtime based on logic from a service already exists.

I'd really love to see an actual, concrete example of something you'd want to achieve with this feature (like example code) as maybe that makes it easier to discuss if or why this isn't possible with the existing feature set and, if so, how this feature could be shaped.

**Comment by stephenlautier** [comment]
Oki so one of the examples i mentioned is to iterate through routes and add validation. Again the only problem we have is we are not able to use DI, so the requested feature is to enable DI pretty much, in this case a simple logger.

#### Validate the Routes has certain data e.g. RouteId in this case

This is how it currently is, and it works, however in this example we cannot use our own logger (commented below)
```ts
export function appProcessRoutes(routes: Routes): Routes {
  return processRoutes(routes, routeIdCheck);
}

function processRoutes(routes: Routes, filterFn?: (route: Route) => boolean | undefined): Routes {
  return _.reduce(routes, (result, route) => {
    const isValid: boolean | undefined = filterFn?.(route);
    if (isValid === false) {
      return result;
    }
    result.push(route);

    if (route.children) {
      route.children = processRoutes(route.children, filterFn);
    }
    return result;
  }, [] as Routes);
}

function routeIdCheck(route: Route): boolean | undefined {
  const data = route.data as AppRouteData;
  if (!data.id) {
    const routeInfo = routeConfigDebugId(route); // code omitted
    // this.logger.error("routeIdCheck", "route has no 'id' specified", {route: routeInfo}); // need to use this
    console.error(`[routeIdCheck] route has no 'id' specified`, routeInfo);
    return false;
  }
}
```

Now in order to be able to use the logger we would need DI, and this is how we generally create it
```ts
constructor(
  loggerFactory: LoggingFactory
) {
  this.logger = loggerFactory.get("AppRoutesConfigTransform");
}
```

So again, the problem is that we are currently limited to only write code which doesn't use any services.

Another issue is you need to apply this manually for each individual usage, like this:

```ts
@NgModule({
  imports: [RouterModule.forChild(appProcessRoutes(ROUTES))], // <-- like this
  exports: [RouterModule]
})
export class AppShellRoutingModule {

}
```

While with the other, you register the service once in root and thats it.

```ts
// copied from feature request above
@NgModule({
  imports: [RouterModule.forRoot(ROUTES)],
  providers: [
      { provide: RoutesConfigHandler, useClass: AppRoutesConfigTransformer }
  ],
  exports: [RouterModule]
})
export class AppRoutingModule {

}
```

**Comment by Airblader** [comment]
Thanks for taking the time to write this up, I appreciate it! I think understanding the use-case helps in finding solutions, be it existing ones or to think about a possible new feature. I'll follow up with my thoughts on this below, but let's see what the Angular team thinks about it. :-)

---

Since this is about preventing misconfiguration during development, wouldn't you rather want this to be a compile-time error rather than a runtime one, though? This could probably be covered in a test that scans the source for routing modules and then performs the checks (although admittedly I don't know of specific tooling that makes writing such tests straight-forward).

As for a runtime version you could have a service which injects Router and then parses Router#config this way to log the errors. This wouldn't disable those routes, though this could then still be achieved by keeping that validation result and accessing it from a guard.

**Comment by stephenlautier** [comment]
> As for a runtime version you could have a service which injects Router and then parses Router#config this way to log the errors. This wouldn't disable those routes, though this could then still be achieved by keeping that validation result and accessing it from a guard.

This sounds almost good for me I think, tho after some thinking, I think its not going to work for lazy loaded routes (havent tried it yet so can't be certain for sure)

**Comment by Airblader** [comment]
That's true; the best I could offer is an internal `provideRouter` method which provides both RouterModule and that service, and then by-convention use that to provide the router in all modules. But I can see why that tends to defeat the purpose.
