### ISSUE TITLE
HttpInterceptor stack trace includes a lot of rxjs and zone.js noise

### ISSUE THREAD

**Issue by alastair-todd** [angular/angular#39315]
If you get a http client remote error, tracing the code is difficult because there is no relevant stack trace. If you try and read the error stack or generate a stack at the point of error in an HttpInterceptor, all you get is a load of zone/rxjs noise and nothing about the caller.

### Affected Package
HttpClientBrowser / HttpClient

### Is this a regression?

This has been the case forever.

If you use this interceptor, you will never see the caller info.

```ts
@Injectable()
export class HttpErrorInterceptor implements HttpInterceptor {

  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    if (environment.production) return next.handle(request);

    const stack = Error().stack;
    // tslint:disable-next-line:no-console
    console.log(stack); // useless
    return next.handle(request).pipe(
      catchError((error: HttpErrorResponse) => {
        if (!(error.error instanceof ErrorEvent)) {
          // server-side error
          console.error('ERROR', error);
        }

        return throwError(error);
      })
    );
  }
}

```

I have a workaround which extends `HttpClient`

```ts

/**
 * Extended HttpClient that generates a stack trace on error when not in a production build.
 */
@Injectable()
export class TraceHttpClient extends HttpClient {
  constructor(handler: HttpHandler) {
    super(handler);
  }

  request(...args: [any]): Observable<any> {
    const stack = environment.production ? null : Error().stack;
    return super.request(...args).pipe(
      catchError((err) => {
        // tslint:disable-next-line:no-console
        if (stack) console.error('HTTP Client error stack\n', stack);
        return throwError(err);
      })
    );
  }
}


```

**Comment by jelbourn** [comment]
@alastair-todd if you use Chrome devtools to blackbox rxjs and zonejs, is your stack more of what you would expect? While it does definitely add a lot of noise, those calls are indeed part of the stack there.

**Comment by alxhub** [comment]
I agree with @jelbourn here - a good way to cut down on the noise is to blocklist those functions in devtools. Stack traces are naturally going to include framework internal functions and operations, and I don't think we can really avoid that.
