### ISSUE TITLE
JIT Complier needed with AOT Build for Dynamic Component

### ISSUE THREAD

**Issue by 513205785Xie** [angular/angular#39326]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/platform-browser-dynamic

### Is this a regression?

 I do not know, my english is not good, sorry...

### Description

I met a problem like this https://github.com/angular/angular/issues/20875#issuecomment-350362783
and I solved this problem, use the method provided earlier,and then i encountered another problem 'undefined is not iterable',
so i checked @angular/platform-browser-dynamic/platform-browser-dynamic.d.ts, and find the class 'JitCompilerFactory' have not constructor for defaultOptions, Is this your intention? 

## 🌍  Your Environment

**Angular Version:**
<pre><code>
    "@angular/cdk": "^10.2.5",
    "@angular/common": "^10.1.6",
    "@angular/compiler": "^10.1.6",
    "@angular/core": "^10.1.6",
    "@angular/flex-layout": "^10.0.0-beta.32",
    "@angular/forms": "^10.1.6",
    "@angular/material": "^10.2.5",
    "@angular/platform-browser": "^10.1.6",
    "@angular/platform-browser-dynamic": "^10.1.6",
    "@angular/router": "^10.1.6",
    "@angular-devkit/build-angular": "~0.1001.2",
    "@angular-devkit/build-ng-packagr": "~0.1001.2",
    "@angular/cli": "~10.1.7",
    "@angular/compiler-cli": "~10.1.6",
    "@angular/language-service": "~10.1.6",
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
Hi @513205785Xie,

the `JitCompilerFactory` is not supposed to be instantiated manually, as it should be obtained through Angular's DI system (using `injector.get(CompilerFactory)`, where `injector` is an Angular injector). As such, the constructor is marked as `@internal`.

I'd actually expect that you should be able to use `injector.get(Compiler)` to get a `Compiler` instance without going through `CompilerFactory` at all. I can't give more insight into which `injector` you should use, as I have too little insight into your situation.

I'll go ahead and close this as I don't see any actionable items for the framework here, but feel free to follow up.
