### ISSUE TITLE
Broken link in aio resources section

### ISSUE THREAD

**Issue by AleksanderBodurri** [angular/angular#39331]
# 📚 Docs or angular.io bug report

### Description

There is a broken link in the aio "Resources" section
<img width="1111" alt="Screen Shot 2020-10-19 at 12 52 51 PM" src="https://user-images.githubusercontent.com/39253660/96487037-f7b8fa00-120a-11eb-877d-6ba24cf8b006.png">

As far as I can tell the new link is https://datorama.github.io/akita/

I can make a PR to fix this if necessary.

### What's the affected URL?**
https://angular.io/resources?category=development

https://netbasal.gitbook.io/akita/  - broken link
https://datorama.github.io/akita/  - new link?

**Comment by sonukapoor** [comment]
@AleksanderBodurri go for it. 👍
