### ISSUE TITLE
drop and focus events behave differently on macOS and Windows

### ISSUE THREAD

**Issue by Githubber2021** [angular/angular#39336]
Hi, I use Electron and Angular and I noticed two different behaviour between macOS and Windows when a component has the `drop` and `focus` event.

```
  @HostListener('window:focus', ['$event'])
  onFocus(event: any): void {
    console.log('focus');
  }
  @HostListener('drop', ['$event'])
  onDrop(event: any): void {
    console.log('drop');
  }
```

If I drag a directory onto the browser window on macOS I only get a `drop` in the console. On Windows however I get between 1 and 2 `focus` outputs before. Is this intended? And if so, what are potential workarounds? I need to distinguish between a real focus and a drop event.

Any help is highly appreciated!

**Comment by petebacondarwin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Githubber2021** [comment]
Hi @petebacondarwin Can you please re-read the issue. There is no support asked for! It is a bug because it is a different behaviour between macOS and WIndows
