### ISSUE TITLE
Test all angular.io examples to ensure they work with `strict` mode enabled

### ISSUE THREAD

**Issue by aikidave** [angular/angular#39344]
# 📚 Docs or angular.io bug report

### Description

Angular now supports an optional `strict` mode. However, we do not know if all existing code examples on Angular.io work with this mode enabled. 

We need to test to see if any examples break when strict mode is enabled. If any do break, we can figure out how to fix them.

### What's the affected URL?**
 https://angular.io/docs

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by gkalpak** [comment]
Based on the configurations mentioned in https://v11.angular.io/guide/strict-mode, there examples that will fail with the [strict][1] and [strictTemplates][2] `tsconfig` rules.

From a test I ran last week, there are the following failures per rule**

<details>
  <summary>Rule <code>strict: true</code> <i>(click to expand)</i></summary>

  - [ajs-quick-reference](https://github.com/angular/angular/blob/master/aio/content/examples/ajs-quick-reference)
  - [animations](https://github.com/angular/angular/blob/master/aio/content/examples/animations)
  - [architecture](https://github.com/angular/angular/blob/master/aio/content/examples/architecture)
  - [attribute-directives](https://github.com/angular/angular/blob/master/aio/content/examples/attribute-directives)
  - [binding-syntax](https://github.com/angular/angular/blob/master/aio/content/examples/binding-syntax)
  - [built-in-directives](https://github.com/angular/angular/blob/master/aio/content/examples/built-in-directives)
  - [component-interaction](https://github.com/angular/angular/blob/master/aio/content/examples/component-interaction)
  - [component-styles](https://github.com/angular/angular/blob/master/aio/content/examples/component-styles)
  - [dependency-injection](https://github.com/angular/angular/blob/master/aio/content/examples/dependency-injection)
  - [dependency-injection-in-action](https://github.com/angular/angular/blob/master/aio/content/examples/dependency-injection-in-action)
  - [docs-style-guide](https://github.com/angular/angular/blob/master/aio/content/examples/docs-style-guide)
  - [dynamic-component-loader](https://github.com/angular/angular/blob/master/aio/content/examples/dynamic-component-loader)
  - [dynamic-form](https://github.com/angular/angular/blob/master/aio/content/examples/dynamic-form)
  - [elements](https://github.com/angular/angular/blob/master/aio/content/examples/elements)
  - [event-binding](https://github.com/angular/angular/blob/master/aio/content/examples/event-binding)
  - [form-validation](https://github.com/angular/angular/blob/master/aio/content/examples/form-validation)
  - [getting-started](https://github.com/angular/angular/blob/master/aio/content/examples/getting-started)
  - [hierarchical-dependency-injection](https://github.com/angular/angular/blob/master/aio/content/examples/hierarchical-dependency-injection)
  - [http](https://github.com/angular/angular/blob/master/aio/content/examples/http)
  - [inputs-outputs](https://github.com/angular/angular/blob/master/aio/content/examples/inputs-outputs)
  - [interpolation](https://github.com/angular/angular/blob/master/aio/content/examples/interpolation)
  - [lifecycle-hooks](https://github.com/angular/angular/blob/master/aio/content/examples/lifecycle-hooks)
  - [ngmodules](https://github.com/angular/angular/blob/master/aio/content/examples/ngmodules)
  - [observables](https://github.com/angular/angular/blob/master/aio/content/examples/observables)
  - [observables-in-angular](https://github.com/angular/angular/blob/master/aio/content/examples/observables-in-angular)
  - [pipes](https://github.com/angular/angular/blob/master/aio/content/examples/pipes)
  - [practical-observable-usage](https://github.com/angular/angular/blob/master/aio/content/examples/practical-observable-usage)
  - [property-binding](https://github.com/angular/angular/blob/master/aio/content/examples/property-binding)
  - [providers](https://github.com/angular/angular/blob/master/aio/content/examples/providers)
  - [reactive-forms](https://github.com/angular/angular/blob/master/aio/content/examples/reactive-forms)
  - [resolution-modifiers](https://github.com/angular/angular/blob/master/aio/content/examples/resolution-modifiers)
  - [router](https://github.com/angular/angular/blob/master/aio/content/examples/router)
  - [rx-library](https://github.com/angular/angular/blob/master/aio/content/examples/rx-library)
  - [security](https://github.com/angular/angular/blob/master/aio/content/examples/security)
  - [service-worker-getting-started](https://github.com/angular/angular/blob/master/aio/content/examples/service-worker-getting-started)
  - [set-document-title](https://github.com/angular/angular/blob/master/aio/content/examples/set-document-title)
  - [structural-directives](https://github.com/angular/angular/blob/master/aio/content/examples/structural-directives)
  - [styleguide](https://github.com/angular/angular/blob/master/aio/content/examples/styleguide)
  - [template-expression-operators](https://github.com/angular/angular/blob/master/aio/content/examples/template-expression-operators)
  - [template-reference-variables](https://github.com/angular/angular/blob/master/aio/content/examples/template-reference-variables)
  - [template-syntax](https://github.com/angular/angular/blob/master/aio/content/examples/template-syntax)
  - [testing](https://github.com/angular/angular/blob/master/aio/content/examples/testing)
  - [toh-pt1](https://github.com/angular/angular/blob/master/aio/content/examples/toh-pt1)
  - [toh-pt2](https://github.com/angular/angular/blob/master/aio/content/examples/toh-pt2)
  - [toh-pt3](https://github.com/angular/angular/blob/master/aio/content/examples/toh-pt3)
  - [toh-pt4](https://github.com/angular/angular/blob/master/aio/content/examples/toh-pt4)
  - [toh-pt5](https://github.com/angular/angular/blob/master/aio/content/examples/toh-pt5)
  - [toh-pt6](https://github.com/angular/angular/blob/master/aio/content/examples/toh-pt6)
  - [two-way-binding](https://github.com/angular/angular/blob/master/aio/content/examples/two-way-binding)
  - [universal](https://github.com/angular/angular/blob/master/aio/content/examples/universal)
  - [upgrade-lazy-load-ajs](https://github.com/angular/angular/blob/master/aio/content/examples/upgrade-lazy-load-ajs)

</details>

<details>
  <summary>Rule <code>strictTemplates: true</code> <i>(click to expand)</i></summary>

  - ~~[accessibility](https://github.com/angular/angular/blob/master/aio/content/examples/accessibility)~~ _Fixed in angular/angular#39248._
  - [built-in-directives](https://github.com/angular/angular/blob/master/aio/content/examples/built-in-directives)
  - [event-binding](https://github.com/angular/angular/blob/master/aio/content/examples/event-binding)
  - [http](https://github.com/angular/angular/blob/master/aio/content/examples/http)
  - [pipes](https://github.com/angular/angular/blob/master/aio/content/examples/pipes)
  - [template-syntax](https://github.com/angular/angular/blob/master/aio/content/examples/template-syntax)

</details>

[1]: https://github.com/angular/angular/blob/a67895cee32b77045ed0ec5ab7b44979fd0aeac8/aio/tools/examples/shared/boilerplate/cli/tsconfig.json#L8-L9
[2]: https://github.com/angular/angular/blob/a67895cee32b77045ed0ec5ab7b44979fd0aeac8/aio/tools/examples/shared/boilerplate/cli/tsconfig.json#L28-L29

**Comment by alan-agius4** [comment]
Looks like `strictInputAccessModifiers` is not listed as part of the strict mode instead `strictTemplates` is listed twice.

**Comment by petebacondarwin** [comment]
I believe this was resolved via https://github.com/angular/angular/pull/41999
