### ISSUE TITLE
Version 11 migrations remove non deprecated API

### ISSUE THREAD

**Issue by slubowsky** [angular/angular#39345]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 10.1.6

### Description

 A clear and concise description of the problem...
Running ng update from 10.1.6 to 11.0.0-next.6 migrations remove usage of an API never documented as deprecated

## 🔬 Minimal Reproduction

 
Have following code:
```
this.router.navigateByUrl(url,
                {
                  queryParamsHandling: 'preserve',
                  replaceUrl: true
                });
```
Running migration changes it to:
```
this.router.navigateByUrl(url,
                { /* Removed unsupported properties by Angular migration: queryParamsHandling. */ replaceUrl: true });
```
But queryParamsHandling is not deprecated!
See https://angular.io/guide/deprecations#angularrouter where preserveQueryParams is deprecated and queryParamsHandling is documented as the replacement!
See https://angular.io/api/router/NavigationExtras#queryParamsHandling where queryParamsHandling is clearly not deprecated but https://angular.io/api/router/NavigationExtras#preserveQueryParams is.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 11.0.0-next.7
Node: 14.14.0
OS: win32 x64

Angular: 11.0.0-next.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.0-next.7
@angular-devkit/build-angular   0.1100.0-next.7
@angular-devkit/core            7.3.10
@angular-devkit/schematics      7.3.10
@angular/cdk                    10.2.5
@angular/cli                    11.0.0-next.7
@schematics/angular             8.3.29
@schematics/update              0.1100.0-next.7
rxjs                            6.6.3
typescript                      4.0.3

</code></pre>

**Anything else relevant?**
not sure, perhaps this belongs in cli repo?

**Comment by crisbeto** [comment]
@slubowsky the deprecation note you mentioned is for v4, whereas this migration accounts for properties that have been removed in v11. Note that the properties that were removed never actually did anything, but now we also removed them from the type so users don't try to add them. Here's the relevant PR that changes the type: https://github.com/angular/angular/pull/38227

**Comment by slubowsky** [comment]
@crisbeto If it wasn't doing anything anyway then I guess its not an issue (I haven't actually tested my code, was just surprised by the result of update) - but normally I wouldn't expect deprecation and removal in one shot. Usually we get deprecation, then in a later version we get removal. My point was that as far I can tell, queryParamsHandling has never been marked deprecated in a released version.

**Comment by petebacondarwin** [comment]
Actually there is a stronger reason for removing it. TS will not allow properties that are not on the interface to appear in an object literal. See this [playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgILIN4Chm+XALmRAFcBbAI2gG4sBfLLGEkBMYAexGRg44ApCaAJSYGTPvwxCAjAAY6w2rwHSi8gDTIKRAEwKlQA).

**Comment by petebacondarwin** [comment]
So just to be clear. What happened in v11 is that a single interface `NavigationExtras` was split into two: `UrlCreationOptions` and `NavigationBehaviorOptions`. Now `UrlCreationOptions` is only used in `createUrlTree()` and `NavigationBehaviorOptions` is only used in `navigateByUrl()`. So in your case the call to `navigateByUrl()` should only pass options that are in `NavigationBehaviorOptions` and not those that are in `UrlCreationOptions`.

Closing as I think that this is working as expected.
