### ISSUE TITLE
docs: improve documentations around injection token ROUTES

### ISSUE THREAD

**Issue by nartc** [angular/angular#39350]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...
Injection token `ROUTES` is sometimes needed in applications where router configuration is fetched dynamically. Providing `ROUTES` allows that to work. As of the moment, documentations relating to dynamic routing or just the `ROUTES` injection token is close to non-existing. `ROUTES` does have https://angular.io/api/router/ROUTES but it's essentially empty.

### What's the affected URL?**
 https://angular.io/...
https://angular.io/api/router/ROUTES

### Expected vs Actual Behavior**

Documentations for `ROUTES` need to be filled with more information.

**Comment by LayZeeDK** [comment]
Related: [Router#resetConfig](https://angular.io/api/router/Router#resetConfig).

**Comment by LayZeeDK** [comment]
@AndrewKushnir @IgorMinar
The URL was accidentally renamed to https://angular.io/api/router/ROUTES-1.

**Comment by petebacondarwin** [comment]
@LayZeeDK - the rename of the path for ROUTES was not accidental - it was to account for the ambiguity on case-insensitive file-systems of the `ROUTES` and `Routes` API pages. There is now a disambiguation page at `https://angular.io/api/router/routes`. But @IgorMinar has suggested a better approach that does not require these URL changes, which I will implement today.

**Comment by LayZeeDK** [comment]
@petebacondarwin Thanks for explaining. I see the problem.
