### ISSUE TITLE
Alpha 36 ComponentRef

### ISSUE THREAD

**Issue by TiagoBraga39** [angular/angular#3935]
Hi all!

Any major changes in alpha 36?

---

<b>It throws this:</b>
![image](https://cloud.githubusercontent.com/assets/8090726/9602739/cf8a7024-50a2-11e5-8bdf-f8cfc19af2e9.png)

---

<b>The bootstrap:</b>
![image](https://cloud.githubusercontent.com/assets/8090726/9602748/e2d65558-50a2-11e5-812c-23cbcb650916.png)

---

By the way, HTML5LocationStrategy does not exist now, so I changed to HashLocation.

Best regards,
Tiago Braga

**Comment by PascalPrecht** [comment]
It's called `PathLocationStrategy` now. Won't solve your issue tho

**Comment by TiagoBraga39** [comment]
Well, it throws the error here https://github.com/angular/angular/blob/master/modules/angular2/src/core/application_common.ts#L309

**Comment by Zyzle** [comment]
I'm having the same issue when moving to alpha 36. Only difference between the example given and my setup is the `APP_BASE_HREF` binding which I don't use.

Are the breaking changes missing from the changelog maybe?

**Comment by TiagoBraga39** [comment]
@Zyzle Maybe you are using the base tag, correct?

I didn't find anything on the changelog, so I guess that is the case.

**Comment by Zyzle** [comment]
Hmmn, I was under the impression that wasn't necessary any more but I can't seem to find the issue that would make me think that.

**Comment by Zyzle** [comment]
@TiagoBraga39 I've found the issue (for me at least); `routerInjectables` has now become `ROUTER_BINDINGS`  Making this change fixed the issue for me.  There's no mention of this in the changelog that I can see though. :cry:

**Comment by ericmdantas** [comment]
@Zyzle might be part of [these changes](https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes), no?

**Comment by Zyzle** [comment]
@ericmartinezr No it seems to have happened after that here:

https://github.com/angular/angular/commit/ccfadb9b4747d5fd7a3c32f7a8e92b23b07f7fd0#diff-a5b6e4e6bcf42bfbebef722164c4033eR41

The commit message about the breaking change doesn't seem to have been hoovered up by the changelog script

**Comment by ericmdantas** [comment]
@Zyzle welp, that explains it.

**Comment by TiagoBraga39** [comment]
@Zyzle Well, we should be expecting those naming changes. Anyway, works for me, but I still need this:
```javascript
bind(APP_BASE_HREF).toValue('#')
```

Closing for now.
