### ISSUE TITLE
Add HMR when using component styles and template 

### ISSUE THREAD

**Issue by mikkelrd** [angular/angular#39367]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

Although the Angular+Webpack docs present the combo as "an excellent alternative to the SystemJS approach", loading component styles via `styles` or `styleUrls` results in a full page refresh, instead of style injection, which occurs when using SystemJS+lite-server.

**Expected behavior**

A core feature of using Webpack+Webpack-dev-server in development is the availability of Hot Module Replacement. It is expected that HMR would work for css injection regardless of the style loading strategy used. Instead, currently changes to css or scss files which are included in a component's styles result in a full page reload.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

Speed up the Angular 2 development process for CSS developers

**Please tell us about your environment:**

- **Angular version:** 2.0.0
  
  
- **Browser:** [**_all_** | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
  
  
- **Language:** [all | **_TypeScript 2.02_** | ES6/7 | ES5]
- **Webpack version:** 1.13.2
- **Webpack-dev-server version:** 1.14.1
- **Node (for AoT issues):** `node --version` =  6.5.0

**Comment by alan-agius4** [comment]
Also related from angular/angular-cli#19233

> ### Description
> I am using HMR with the latest rc of the cli.
> Refresh and refill of forms works great, however the app state (saved as variables in services) is lost with each refresh.
> It seems that all services are newly created with each reload.
> 
> ### Describe the solution you'd like
> The app doesn't loose the current state of the app at an HMR update

**Comment by hiepxanh** [comment]
great, finally, I see a little attention on this

**Comment by hiepxanh** [comment]
long time no see, it is a little complex and have some block that I cannot continue, since I change to use tailwind, it doesn't useful anymore :D. maybe you should try tailwind sir. If I have a solution to update html code On The Fly, it will be so good

**Comment by anymos** [comment]
any interest here ? that a very long time with no visible progress, and no real documentation about it. 

Is there any pointers to some doc, some code that could be useful to maintain the state between refresh ?

The use case is to not run api call each time there is a reload as it can take a huge amount of time for some api call ...

**Comment by anymos** [comment]
@angularclass/hmr sounds like not up to date anymore ... any other way to do it ?

**Comment by infacto** [comment]
I think Angular needs a full hot reload support. Currently enabling hmr has some weird side effects and just don't work well with Angular. It still hard reloads and clears history, etc. I want to change some text in HTML without reloading app. Just like hot reload from Flutter. As I see this ticket is only about CSS. Other tickets for general hot reload for e.g. HTML etc. are closed in favor of this issue. But it's only CSS. But ok...

**Comment by alan-agius4** [comment]
@infacto, this is something that we definitely want to improve.  However, based on our comment it doesn't seem you are opted to use HMR. When HMR is enabled there is no hard reload nor clearing of history.  Currently, our approach to HMR, is to re-bootstrap the application on every change as such any "local" state which is lost.

**Comment by davidivkovic** [comment]
Still no progress after 6 years?

**Comment by valibraimi** [comment]
I am leaving Angular ASAP!

**Comment by Rafik-Belkadi-malou** [comment]
+1 
Any progress on this ? 
we are doing a full redesign of our app and this is really painful having to reload all the page when making any. change , text/css/ts .. 
not preserving state is ok but at least changing styles without a full reload of the app is an absolute necessity.

**Comment by jmroon** [comment]
> @infacto, this is something that we definitely want to improve. However, based on our comment it doesn't seem you are opted to use HMR. When HMR is enabled there is no hard reload nor clearing of history. Currently, our approach to HMR, is to re-bootstrap the application on every change as such any "local" state which is lost.

What is functionally the difference between hmr and non-hmr in that case? If we're re-bootstrapping the whole application, it doesn't really sound like we're reloading a module.

This is a real productivity killer when it comes to styling, especially when we're doing css changes in a deep, nested workflow. Modern build tools can show css changes in ~20ms. In Angular, it can take 20s+ in complex workflows to see any css changes.

**Comment by mtuzinskiy** [comment]
Unfortunately we all have to admit that HMR doesn't work in Angular, 7 years after the release - v15 - and it's 2023.

**Comment by michaellee8** [comment]
Will there be any ETA in this issue? Would it be possible to prevent a re-bootstrap after the application has been hot-reloaded? Vue seems to be similar in terms of architecture with Angular and hot reloading has been achieved long ago so are there any angular-sprcific obstacles here?

**Comment by alorka** [comment]
I hope someone from the Angular team could provide an update on the status of HMR. 

It would be greatly appreciated if we could receive some insight, even if it requires a bit of creative storytelling considering it is xxxx 2023.

**Comment by ntorrey** [comment]
Was struggling with getting this to work this morning. Not I'm realizing it's not me that's broken, but Angular! At least I will stop wasting time on trying to fix this issue myself...

**Comment by kchojhu** [comment]
I've been doing Angular for few years now and every new version I keep hoping that HMR would work.  Angular itself is great but I just can't recommend this framework without full HMR support.  At least can we have HMR with just the HTML/CSS only? As one UI dev to another, please make this happen.

**Comment by Loque18** [comment]
> HMR

I totally agree with you, **we need this feature ASAP**, it's really awful to wait for the browser to finish loading each time you change a single word in your HTML/CSS, I recently moved from React to Angular, and I loved Angular instantly, but one thing that I like about react, is how you can update your code and see those updates automatically in the browser without reloading the whole thing.

so please _**ANGULAR TEAM**_ make this happen asap, you guys have done an amazing job with this framework, coding in Angular feels good, you feel like you are doing things the right way, but please we need HMR, pleeeease!!!

**Comment by scr2em** [comment]
The team is investigating using Signals but they can't do HMR right .... smh

**Comment by alan-agius4** [comment]
From https://github.com/angular/angular-cli/issues/24755

> Angular CLI currently supports HMR via `ng serve --hmr` though it isn't the ideal experience. Under the hood, this mostly rerenders the Angular application from scratch, which is better than a full page reload, but could definitely be improved. @alan-agius4 has suggested a number of opportunities for improving HMR. Most importantly, our strategy here should be to optimize the turnaround time for any given change _scaled_ with the frequency of that kind of change. For example, it is very common to make numerous tiny adjustments to CSS in quick succession while finding the precise styling needed for a page. This is a very hot path to optimize and even marginal improvements here can have a bit impact due to how frequently CSS-only changes are made during development.
> 
> ### Describe the solution you'd like
> Some ideas to improve HMR include (but are not limited to):
> 
> * Fast track CSS-only changes and apply them to any existing components on the page.
>   
>   * This should be relatively straightforward since we mostly need to correlate a component class with its `<style />` tag on the page, then delete and recreate that tag with the new CSS content. This would be very fast and maintain page state.
>   * Supporting inline styles is a bit more complicated but should be achievable?
> * Fast track Angular template-only changes and apply them to any existing components on the page.
>   
>   * In theory, we just need to delete the generated JavaScript render functions for a component and overwrite them with the new render functions from the modified template, then re-apply the DOM.
>   * In practice, I think this is a challenge as Angular templates aren't completely stateless (ex. `async` pipe). But this is likely achievable in some capacity. Should be pretty quick and mostly maintain page state.
>   * Supporting inline templates is a bit more complicated but should be achievable?
> * Re-render only the currently displayed Angular route, rather than the full application.
>   
>   * Statistically speaking, most code changes will be within the currently displayed Angular route and won't impact anything outside the route. In many cases, it would be sufficient to just rerender that one route.
> 
> Angular template and CSS changes in particular are two areas where users frequently make a large number of small changes in quick succession and in a manner which is easy for tooling to reason about. These are two spaces where we can have a huge impact on developer's quality of life.
> 
> If we can get this good enough, I'd love to get to a place where we could turn `--hmr` on by default in `ng serve`.
> 
> ### Describe alternatives you've considered
> HMR is mostly one facet of the larger problem around "How do we make the time between editing a file and reloading its changes in the browser as quick as possible?" (edit/refresh time). HMR is one means of getting built changes into the running browser faster and maintain the application's current state. We should (and are) investigating ways to improve the overall edit/refresh experience independent of HMR.
> 
> More related to HMR, the focus on Angular template and CSS changes does highlight a lack of focus on TypeScript changes. This is somewhat intentional. Angular has strong separation of concerns between Angular templates (for HTML/DOM rendering), CSS (for styling), and TypeScript (for component functionality). While this isn't absolute and TypeScript can often containing rendering or styling functionality (ex. list filters or conditional CSS classes), the vast majority of DOM and CSS changes made by a developer will be done by editing a template or a stylesheet, not TypeScript.
> 
> TypeScript changes are also very tricky to apply consistently with HMR. As one example, renaming a class field in TypeScript _can_ be HMR'd, however doing so often leads to inconsistencies and confusing behavior. HMR is intended to maintain the current user state, but it is effectively impossible for the build process to understand that deleting a `foo` field and creating a `bar` field as intended as a rename and state should be transferred from one property to the other during HMR. At runtime, it looks like this renamed field just "forgot" all its state, which can easily break the component and cause errors which require a full page reload to fix. That's one example, but the sheer variety of possible changes a user can make to TypeScript code means it can never be totally consistent or reliable.
> 
> We should definitely be open to improvements here where we can take advantage of them, and we should make sure not to let "perfect" be the enemy of "good enough". The key takeaway here is that HMR of TypeScript-only changes in Angular is simultaneously the hardest to do right, and also the least impactful. Again, _scaling_ the impact of optimizing a particular change with the _frequency_ that kind of change occurs is where we can find the most value for users.
> 
> /cc @alan-agius4 for other ideas around improving HMR, definitely lots of cool stuff we're hoping to do here.

**Comment by niccolofanton** [comment]
The Angular CLI now uses a new [esbuild-based build system](https://angular.io/guide/esbuild)! As mentioned in the article, hmr isn't currently supported but it seems like it's coming very soon, good job team!

**Comment by shunia** [comment]
I don't want to be mean here but in the morden front-end world an enterprise-level framework doesn't even provide basic level DX is so disapointing and frustrating, and the team didn't event mention this in the documents.

I'm kinda of forced to work with angular in an internal project as it's a legacy project, there are some features/bugs I have to develop/fix deep into a workflow, the application level refresh drive me nuts if I just want to change a single line of code to see if it works. 
By looking for solutions on the internet, I'm shocked that there's no HMR feature in angular, and what's more no one in the team is bringing this up except the guy who just shutdown every other issues/discussions and point them to here, and no more, no progress, no priority, no spec, no work-around, no one just cares.

I'm really wondering how hard is it to implement this by the team, in a world where each and every other bundler can provide almost perfect HMR experiences, can anyone lighten me up on this please?

**Comment by HCenggel** [comment]
it's important

**Comment by scr2em** [comment]
One of the oldest issues I have been watching since 2019, glad I decided to migrate from Angular (took 1 year) 

and I'm still here watching it 😅

**Comment by zhan3333** [comment]
react changes styles and updates them to the browser in real time without refreshing the page 🥹

**Comment by alisonjonck** [comment]
I wonder if there's anything you could use to make it work like it should work from start :-( 👎

**Comment by loudar** [comment]
Also chiming in to note that Angular is obviously being used for enterprise-level applications. If it wants to have a chance at still being relevant for those things in the future, things like these are **absolutely** necessary to have, otherweise developers will simply choose to not use it.

**Comment by dimitri-bret** [comment]
@alan-agius4  could you please consider this issue, at least give an official position from the Angular Team in the roadmap could we expect one day to have a feature like this.
We do not see a point of this in the [roadmap](https://angular.io/guide/roadmap), (with exciting stuff to come though).
@loudar comment is very relevant about how developpers feel about the lack of true HMR.
Thank you for your amazing works.

**Comment by tayambamwanza** [comment]
> @alan-agius4 could you please consider this issue, at least give an official position from the Angular Team in the roadmap could we expect one day to have a feature like this. We do not see a point of this in the [roadmap](https://angular.io/guide/roadmap), (with exciting stuff to come though). @loudar comment is very relevant about how developpers feel about the lack of true HMR. Thank you for your amazing works.

@dimitri-bret  It's there now: https://angular.dev/roadmap#future-work-explorations-and-prototyping

**Comment by haskelcurry** [comment]
> Under the hood, this mostly rerenders the Angular application from scratch, which is better than a full page reload
No it's not better 😒

**Comment by bsplosion** [comment]
> > Under the hood, this mostly rerenders the Angular application from scratch, which is better than a full page reload
> 
> No it's not better 😒

Adding my voice to the pile: I have an Angular enterprise app which was largely built prior to my tenure.  Every time we need to do anything more than small tweaks we incur an absolutely staggering loss of productivity, where our only options are HMR with minimum 20s full reloads or 45s-90s rebuilds.

The roadmapped improvement, as currently defined, is incredibly disappointing and doesn't bring Angular up to anything resembling parity with other frameworks.  We've actually selected Next.js/React for another major platform we've brought online and it's rocked our world how much better DX is.

Productivity skyrockets when changes can reflect instantly.  Gone is the pain of having to make a small change, rebuilding/reloading for an exceptionally long time, then realizing you needed to tweak it in a slightly different way and going through the same long process again.

Frankly, given how little the Angular team apparently cares about core features, I'd be migrating off of it if there wasn't such a dev cost.  From my perspective, anyone who selects Angular for a new project today is making a foolish choice and they'd be far better served looking at almost any other big name.  I only wish it were simpler to migrate this stack - I've also been watching this for 5 years with growing frustration, and at some point the pain of continuing to deal with it will exceed the pain of a migration.

**Comment by tayambamwanza** [comment]
> > > Under the hood, this mostly rerenders the Angular application from scratch, which is better than a full page reload
> > 
> > No it's not better 😒
> 
> Adding my voice to the pile: I have an Angular enterprise app which was largely built prior to my tenure.  Every time we need to do anything more than small tweaks we incur an absolutely staggering loss of productivity, where our only options are HMR with minimum 20s full reloads or 45s-90s rebuilds.
> 
> The roadmapped improvement, as currently defined, is incredibly disappointing and doesn't bring Angular up to anything resembling parity with other frameworks.  We've actually selected Next.js/React for another major platform we've brought online and it's rocked our world how much better DX is.
> 
> Productivity skyrockets when changes can reflect instantly.  Gone is the pain of having to make a small change, rebuilding/reloading for an exceptionally long time, then realizing you needed to tweak it in a slightly different way and going through the same long process again.
> 
> Frankly, given how little the Angular team apparently cares about core features, I'd be migrating off of it if there wasn't such a dev cost.  From my perspective, anyone who selects Angular for a new project today is making a foolish choice and they'd be far better served looking at almost any other big name.  I only wish it were simpler to migrate this stack - I've also been watching this for 5 years with growing frustration, and at some point the pain of continuing to deal with it will exceed the pain of a migration.

I saw that fixing this particular problem is slated for 2024, so it will be sorted.

**Comment by bsplosion** [comment]
> I saw that fixing this particular problem is slated for 2024, so it will be sorted.

That's what we're discussing - few of us believe that the slated improvements, at least as currently defined, are going to remotely address the disparity in HMR experience between Angular and every other modern JS framework.  Their roadmap just links back to [this comment](https://github.com/angular/angular/issues/39367#issuecomment-1439537306) on this very issue, and that comment is at best a small improvement to a few particular workflows.

**Comment by tayambamwanza** [comment]
I belive the integration of dev server with Vite shows there is progress in that area also, the team has stated single file compilation is something they are trying to achieve so don't give up as if the team is totally ignoring it, it might just be that they need to change Angular in small steps to support it properly instead of doing a hack job or a catastrophic breaking change.

**Comment by LanderBeeuwsaert** [comment]
Indeed, our application (1276 components for now) went from +-8 seconds rebuilds to +-2 seconds rebuilds with vite/esbuild which has been from a DX standpoint a massive improvement.
Even then 2 seconds rebuilds + +-3 seconds browser app reloads are annoying.
So the projected single file compilation + HMR will be very welcome.
But to say that there has been no improvement in the framework is to our experience incorrect.
As well, I suppose that what has been discussed in https://github.com/angular/angular/issues/39367#issuecomment-1439537306 is before they have researched it, so the extent (or lack) of the future improvements is unkown.
That Minko brings it up himself on twitter uhhh X gives credibility they will be looking into it in the coming year: https://github.com/angular/angular/issues/39367#issuecomment-1439537306

**Comment by tayambamwanza** [comment]
> Indeed, our application (1276 components for now) went from +-8 seconds rebuilds to +-2 seconds rebuilds with vite/esbuild which has been from a DX standpoint a massive improvement.
> Even then 2 seconds rebuilds + +-3 seconds browser app reloads are annoying.
> So the projected single file compilation + HMR will be very welcome.
> But to say that there has been no improvement in the framework is to our experience incorrect.
> As well, I suppose that what has been discussed in https://github.com/angular/angular/issues/39367#issuecomment-1439537306 is before they have researched it, so the extent (or lack) of the future improvements is unkown.
> That Minko brings it up himself on twitter uhhh X gives credibility they will be looking into it in the coming year: https://twitter.com/mgechev/status/1738041018673701153
> 
> 

@bsplosion exactly, so you'll get what you want.

**Comment by pumano** [comment]
As for now you can just use "forceEsbuild=true" when you serve app for development and It give you huge improvement in startup time. We got drop startup time from 140-160 sec to 40 sec. Restart mostly the same time few seconds (yes it's huge) but angular devs looking into it, and looks like some combined new features will navigate us to better Future. Looks like when standalone components Will fully work we got what we want, fastest recompilation.

**Comment by LanderBeeuwsaert** [comment]
maybe this comes into this as well, not sure:
https://twitter.com/dylhunn/status/1740891299342119416

**Comment by fabm22** [comment]
Hi there, I would like to know if this problem is now a non-issue with the release of the use of Vite build-toolkit in Angular? thanks

**Comment by fabm22** [comment]
Hello, I would like to know if, with the drastic improvments in speed of build thanks to use of Vite "build toolchain", this is still on the cards or has this been "more" placed on back burner? I presume this would still be a great improvement in DX?? Thanks

**Comment by tayambamwanza** [comment]
> Hello, I would like to know if, with the drastic improvments in speed of build thanks to use of Vite "build toolchain", this is still on the cards or has this been "more" placed on back burner? I presume this would still be a great improvement in DX?? Thanks

Last I checked Angular team has "proper hmr" on road map for this year.

**Comment by jeudryWepsys** [comment]
We need this

**Comment by xnf** [comment]
we still need this. 🙏

**Comment by marcellkiss** [comment]
Deeply agree... Would be very nice if you could share the state of the current state / research / guides on contributing to HMR capabilities.
This is currently (by far) the most painful missing feature compared to other FE frameworks.

**Comment by jeudryWepsys** [comment]
WE NEED TRHIS!!

**Comment by 3dyuval** [comment]
Just came in here to say that this is 2024 and we still need this

**Comment by scarqin** [comment]
We need this

**Comment by rohit-techolution** [comment]
hello???

**Comment by rohit-techolution** [comment]
> @rohit-techolution have you tried Angular 18? It seems like hmr has improved on css, it's not 100% but there seems like an improvement, do they are working on it it seems.
Enterprises cannot update to latest version as soon it is released. We are on 16-17.
Angular team should really prioritise it as it will improve developer experience. No wonder developers love other frameworks.

**Comment by tayambamwanza** [comment]
> > @rohit-techolution have you tried Angular 18? It seems like hmr has improved on css, it's not 100% but there seems like an improvement, do they are working on it it seems.
> 
> Enterprises cannot update to latest version as soon it is released. We are on 16-17.
> Angular team should really prioritise it as it will improve developer experience. No wonder developers love other frameworks.

I believe they have it on priority, since it's improving and on the road map, just because it's not here today doesn't mean it's not coming.

**Comment by haskelcurry** [comment]
We need this

**Comment by DanielMcFluffy** [comment]
We need this

**Comment by daniel-rrapi** [comment]
We still need this

**Comment by aniketsuryavanshi093** [comment]
> @rohit-techolution have you tried Angular 18? It seems like hmr has improved on css, it's not 100% but there seems like an improvement, do they are working on it it seems.

How did you manage to add hmr in angular 18

**Comment by Junior-Stalin** [comment]
2023, 2024 I'm still waiting for this

**Comment by lucas-implanta** [comment]
Using Angular 18 here, unfortunately, updating CSS or simple text in components still updates the whole application 😥 (i envy so much react devs)

**Comment by hakimio** [comment]
Angular `19` now has `NG_HMR_TEMPLATES=1` for HMR template updates, but at least for me it's not working. 
The console message says `Component update sent to client(s).` but nothing changes in the browser. Disappointing.

[More info on Angular blog](https://blog.angular.dev/meet-angular-v19-7b29dfd05b84#2bb5)

**Comment by marcellkiss** [comment]
Same here, on a brand new @angular/cli project, version 19.0.0, the only thing the `NG_HMR_TEMPLATES=1` is doing, that it turns off refresh on template changes. 

(Maybe it should also be removed from the announcement post for now.)

**Comment by JeanMeche** [comment]
What the blog doesn't say is that template HMR only works for external template file (and not inline templates) for now.

**Comment by hakimio** [comment]
Tested with external template and it didn't update anything in the browser.

**Comment by marcellkiss** [comment]
Tried both without success

**Comment by JeanMeche** [comment]
You're right, a small regression sneaked in just before the release but was already fixed in #58724. It'll be shipped in the next patch release.

**Comment by cjosue15** [comment]
Currently i have this error in a template file when i use `NG_HMR_TEMPLATES=1 ng serve`, i'm using the version `^19.0.0`

![Image](https://github.com/user-attachments/assets/48e907bd-7158-4fd5-95da-7ab79ebc675b)

**Comment by hakimio** [comment]
Template and style HMR now works on all platforms with Angular `19.0.4` and Angular CLI `19.0.5`.
The only major remaining HMR issue is #59058

**Comment by scr2em** [comment]
Time to edit my will, I got HMR before my children
