### ISSUE TITLE
add test_lib.d.ts on DefinitelyTyped

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#3936]
It looks like `test_lib.d.ts` did not make it to DT yet, was this postponed until the next release or it hasn't even been considered?

**Comment by pkozlowski-opensource** [comment]
Isn't it duplicate of https://github.com/angular/angular/issues/3824?

**Comment by rolandjitsu** [comment]
@pkozlowski-opensource kind of, I'm closing :)
