### ISSUE TITLE
Angular HttpClient error

### ISSUE THREAD

**Issue by GaneshSingaravelu** [angular/angular#39362]
Hi 😄

I am getting below the issue only when my API throws the exception (Asp.Net core 3.1 WebApi). Please do the needful.

> ERROR TypeError: source.lift is not a function
    at TapSubscriber.catchErrorOperatorFunction [as _tapError] (catchError.js:7)
    at TapSubscriber._error (tap.js:50)
    at TapSubscriber.error (Subscriber.js:55)
    at XMLHttpRequest.onLoad (http.js:2533)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41632)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:480)
    at invokeTask (zone-evergreen.js:1621)

**_Http Request_**

` this.httpClient.post<any>(this.api, data);`

**_**Angular Interceptor**_**

```
import { Injectable } from '@angular/core';
import { HttpInterceptor, HttpHandler, HttpRequest, HttpEvent, HttpHeaders, HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { catchError, tap } from 'rxjs/operators';
import { NgxSpinnerService } from "ngx-spinner";

@Injectable({
  providedIn: 'root'
})
export class AppInterceptorService implements HttpInterceptor {

  constructor(private spinner: NgxSpinnerService) { }

  handleError(error: HttpErrorResponse) {
    let errorMessage = 'Unknown error!';
    if (error.error instanceof ErrorEvent) {
      // Client-side errors
      errorMessage = `Error: ${error.error.message}`;
    } else {
      // Server-side errors
      errorMessage = `Error Code: ${error.status}\nMessage: ${error.message}`;
    }
    this.spinner.hide();
    window.alert(errorMessage);
    return throwError(errorMessage);
  }


  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>>{
    
    this.spinner.show();
    const header = new HttpHeaders({
      'content-type': 'application/json'
    });

    const clone = req.clone({headers: header, method:'POST'});

    return next.handle(clone).pipe(tap((event: HttpEvent<any>) => {
      if (event instanceof HttpResponse) {
        this.spinner.hide();
      }
    }, 
    catchError(this.handleError)));

    // return next.handle(clone).pipe(
    //   catchError(this.handleError)
    // );
  }
}
```

**_Angular App.Module_**
```

import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations'
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { NgxSpinnerModule } from "ngx-spinner";
import { ToastrModule } from 'ngx-toastr';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { AppInterceptorService } from './app-interceptor.service';
import { FormsModule } from '@angular/forms';
import { NgxWebstorageModule } from 'ngx-webstorage';

import { SpinnerComponent } from './core/shared/spinner/spinner.component'

import { LoginComponent, SignupComponent, ChangepasswordComponent } from '@modules/user_account';
import { HeaderComponent, NavbarComponent, ContainerComponent, FooterComponent } from '@core/shared/layout'
import { CommondashboardComponent } from '@modules/dashboard';

import { UserAccountBL } from './businesslogic/user_account/useraccount_bl';
import { AppAuthGuardService as AuthGuard } from 'app/app-auth-guard.service';
import { ParentmenuPipe } from './pipes/common/parentmenu.pipe';
import { ChildmenuPipe } from './pipes/common/childmenu.pipe';


@NgModule({
  declarations: [
    AppComponent,
    LoginComponent,
    SignupComponent,
    ChangepasswordComponent,
    HeaderComponent,
    FooterComponent,
    NavbarComponent,
    CommondashboardComponent,
    ContainerComponent,
    SpinnerComponent,
    ParentmenuPipe,
    ChildmenuPipe
  ],
  imports: [
    BrowserModule,    
    BrowserAnimationsModule,  
    FormsModule,
    AppRoutingModule,
    HttpClientModule,
    NgxWebstorageModule.forRoot(),  
    ToastrModule.forRoot(), 
    NgxSpinnerModule 
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  providers: [AuthGuard, 
              UserAccountBL,
              {provide: HTTP_INTERCEPTORS, useClass: AppInterceptorService, multi: true},],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**_Asp.Net core 3.1 Web API_**

```
public IActionResult LoadUserMenu(UserInfoModel _uim)
        {
            try
            {
                var Loginresult = oUserAccDAL.LoadUserMenu(_uim);
                var result = null as object;
                result = new
                {
                    Info = Loginresult
                };
                return Ok(result);

            }
            catch (Exception ex)
            {
                // return NotFound(new { message = ex.Message.ToString() });
                return BadRequest("Error from api");
            }
        }
```

# 🐞 bug report

### Description

 I am getting a below error when API throws the exception. My angular "error handler" method did not catch the exception of API.

## 🔥 Exception or Error
<pre><code>
core.js:6228 ERROR TypeError: source.lift is not a function
    at TapSubscriber.catchErrorOperatorFunction [as _tapError] (catchError.js:7)
    at TapSubscriber._error (tap.js:50)
    at TapSubscriber.error (Subscriber.js:55)
    at XMLHttpRequest.onLoad (http.js:2533)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41632)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:480)
    at invokeTask (zone-evergreen.js:1621)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
  _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.9
Node: 13.7.0
OS: win32 x64

Angular: 9.1.11
... common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.9
@angular-devkit/build-angular     0.901.9
@angular-devkit/build-optimizer   0.901.9
@angular-devkit/build-webpack     0.901.9
@angular-devkit/core              9.1.9
@angular-devkit/schematics        9.1.9
@angular/animations               9.1.12
@angular/cli                      9.1.9
@ngtools/webpack                  9.1.9
@schematics/angular               9.1.9
@schematics/update                0.901.9
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Comment by destus90** [comment]
Take a closer look at your `AppInterceptorService#intercept` method. Seems that you have lost some curly braces. Try this
```
    return next.handle(clone).pipe(
        tap((event: HttpEvent < any > ) => {
            if (event instanceof HttpResponse) {
                this.spinner.hide();
            }
        }),
        catchError(this.handleError)
    );
```

**Comment by gkalpak** [comment]
@destus90 seems to be spot on. Closing...

**Comment by JoostK** [comment]
> Take a closer look at your `AppInterceptorService#intercept` method. Seems that you have lost some curly braces. Try this
> 
> ```
>     return next.handle(clone).pipe(
>         tap((event: HttpEvent < any > ) => {
>             if (event instanceof HttpResponse) {
>                 this.spinner.hide();
>             }
>         }),
>         catchError(this.handleError)
>     );
> ```

Also note that `this.handleError` depends on the `this` context so it needs to be

```ts
    return next.handle(clone).pipe(
        tap((event: HttpEvent < any > ) => {
            if (event instanceof HttpResponse) {
                this.spinner.hide();
            }
        }),
        catchError(this.handleError.bind(this))
    );
```

**Comment by GaneshSingaravelu** [comment]
Thank you so much
