### ISSUE TITLE
ngOnInit does not fire when going back/forward to/from an external domain in Safari 14.0 and iOS browsers.

### ISSUE THREAD

**Issue by jdpearce** [angular/angular#39382]
This seems as though it may be a duplicate of #26829 but I have a repro here. The workarounds provided in that issue thread do not seem to work.

## 🔬 Minimal Reproduction & Description

I created a brand new repo here:

https://github.com/jdpearce/jhp-safari-back

This is deployed in two places:

http://jhp-safari-back.herokuapp.com/
http://jhp-safari-back2.herokuapp.com/

If you open up the first instance in Safari 14.0 and then click "external" it will navigate to the second instance. Click "back" and you can see that the text in the template has _not_ been updated (the time remains the same as when the page was first visited) - i.e. `ngOnInit` has not fired. If you click between "one" and "two" on the same domain that text is updated on each visit.

e.g.

![angular_safari_back_bug](https://user-images.githubusercontent.com/439121/96857567-0693ec80-1457-11eb-85d6-eff9131389eb.gif)

## 🌍  Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 10.1.7
Node: 12.16.3
OS: darwin x64

Angular: 10.2.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cli                    10.1.7
@schematics/angular             10.1.7
@schematics/update              0.1001.7
rxjs                            6.6.3
typescript                      3.9.7
</code></pre>

**Anything else relevant?**

This is specific to Safari 14.0 and ALL browsers on iOS

I understand this may be a problem with Safari/WebKit itself, but even if it's not a bug in Angular per se, advice on how best to overcome this would be enormously welcome.

Thanks!

**Comment by petebacondarwin** [comment]
@jdpearce - do you know if any JS is being executed when you hit the back button? I have a feeling that the browser is trying to improve performance by, effectively, hibernating the page when you navigate forward, and then rehydrating it in the same state that it was left when you navigate back.  If this is the case, then there would not be much that Angular can do to overcome this. It would be like the user navigating to the new page on a new tab. And then switching back to the previous tab.

**Comment by petebacondarwin** [comment]
Possibly related issue on StackOverflow:  https://stackoverflow.com/questions/15613526/back-button-does-not-execute-any-page-script-in-safari-ff-android-and-ios-5ipho

And this might be the underlying cause: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/1.5/Using_Firefox_1.5_caching

**Comment by petebacondarwin** [comment]
In that last link there are a number of suggestion why the cache might not be used. Perhaps you could use one of those to prevent your page from being added to the bfcache?

**Comment by jdpearce** [comment]
@petebacondarwin I don't think any JS is being executed, I've tried this with a non-Angular setup and it's the same unless I add a listener to the `pageshow` event. I did idly wonder if Angular could use this hook to re-vivify itself somehow?

Part of the problem with the more involved case that I'm investigating is that the NgRX state seems to be completely lost, this means that the state of the page _can_ be different to what it should be, so although it seems like page state may be retained, JS state isn't. The tab analogy breaks down there, unfortunately.

Really appreciate the rapid response and the advice. I will take a closer look at the bfcache and see if I can break it somehow.

**Comment by petebacondarwin** [comment]
I we can break it reliably in applications, then I think we should document that and mark this as working-as-expected from Angular's point of view.

**Comment by jdpearce** [comment]
Unfortunately I can't find a way to break the bfcache so far.  None of these seem to work:

❌ `window.unload` handler
❌ `window.beforeunload` handler
❌ `cache-control: no-store`
❌ `pragma: no-cache`

cf. https://jhp-safari-back3.herokuapp.com which implements them.

Adding this to the header does work but it feels like a terrible hack:

```
window.addEventListener("pageshow", function (event) {
  if (event.persisted) {
    window.location.reload();
  }
});
```

**Comment by petebacondarwin** [comment]
I think that might be the best you can hope for 🤷 .
Either way, it appears that the problem really is with the bfcache and I don't think there is anything the Angular framework can do about this, right? In which case can we close this?

**Comment by jdpearce** [comment]
@petebacondarwin I think you're right. Appreciate your advice on this. I'm closing the issue. Hopefully if anyone comes across this again there's enough info here to see and fix the problem now.
