### ISSUE TITLE
Re-evaluate or expand template vars example

### ISSUE THREAD

**Issue by kapunahelewong** [angular/angular#39385]
# 📚 Docs or angular.io bug report

### Description

We should demo in the template vars example each use of a template variable that we discuss in the doc. We may need two separate examples with the second one focusing on forms. Per these two comments: 
https://github.com/angular/angular/pull/31195#pullrequestreview-512219336
https://github.com/angular/angular/pull/31195#discussion_r508113682

### What's the affected URL?**

https://angular.io/guide/template-reference-variables

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by alxhub** [comment]
This seems to have been fixed at some point - the template variable guide shows examples now for each type of variable.
