### ISSUE TITLE
Asynchronous ngOptions loading results in a select with no selected option

### ISSUE THREAD

**Issue by TwitchBronBron** [angular/angular#394]
Here's the issue:

I have a select using ng-model and ng-options. The ng-model value is available immediately, but the ng-options array is loaded asynchronously. Once the ng-options array arrives, the select is rendered with the options, but the correct option in the select is not selected. 

I tried using the latest build at the time but it doesn't look like this issue has been fixed yet. https://ci.angularjs.org/job/angular.js-angular-master/3760/artifact/build/

Here is an example jsfiddle. 

http://jsfiddle.net/TwitchBronBron/bmpeuLqt/18/

**Comment by pkozlowski-opensource** [comment]
Wrong repo, the one you are looking for is here: https://github.com/angular/angular.js
