### ISSUE TITLE
Register dependencies from feature loaded modules

### ISSUE THREAD

**Issue by ghost** [angular/angular#39414]
# 🚀 feature request

### Relevant Package
Probable @angular/core & @angular/router?

### Description
I hope this isn't yet possible but I've searched a while for it, asked stackoverflow (https://stackoverflow.com/questions/64503147/lazy-registered-provider-not-available-for-already-created-injectors, https://stackoverflow.com/questions/64514525/angular-register-dependencies-from-feature-module) and couldn't find a solution. I'd like to register providers from feature loaded modules that are available in already existingt modules.

Here is a stackblitz showing the problem: [Sample](https://stackblitz.com/edit/angular-hbxx3f?file=src%2Fapp%2Fapp.component.ts)

Clicking on count shows the amount of registered dependencies of type EXCEPTION_FORMATTER. Clicking on "Orders" loads a feature module with a dependency. Clicking count again still only findes one dependency.

### Describe the solution you'd like
Be somehow able to register providers from feature modules and refresh already created injectors to known them.

### Describe alternatives you've considered
I'm currenty using a shared singleton service to share instances. But that's quite ugly and "un"-DI.

**Comment by gilsdav** [comment]
It would be great to add "prividedIn" into [provider](https://github.com/angular/angular/blob/d1ea1f4c7f3358b730b0d94e65b00bc28cae279c/packages/core/src/di/interface/provider.ts) interface like in [injectable meta](https://github.com/angular/angular/blob/d1ea1f4c7f3358b730b0d94e65b00bc28cae279c/packages/compiler/src/injectable_compiler_2.ts#L20)

**Comment by magicmatatjahu** [comment]
@tsproesser If you know how Angular's DI works under the hood you can use some hacks:

```ts
import { NgModule, Inject, Injector } from "@angular/core";
import { CommonModule } from "@angular/common";

import { OrdersRoutingModule } from "./orders-routing.module";
import { OrderListComponent } from "./order-list/order-list.component";
import { EXCEPTION_FORMATTER, IExceptionFormatter } from "../app.component";

export class InjectB implements IExceptionFormatter {
  handleException(paramException: any): { message?: string } {
    throw new Error("Method not implemented.");
  }
}

@NgModule({
  imports: [CommonModule, OrdersRoutingModule],
  declarations: [OrderListComponent],
  providers: [
    {
      provide: EXCEPTION_FORMATTER,
      useClass: InjectB,
      multi: true
    }
  ]
})
export class OrdersModule {
  constructor(injector: Injector, @Inject(EXCEPTION_FORMATTER) exceptions: any[]) {
    const records = (injector as any).parent.records; // read the records from parent injector, records is internal storage for loaded providers
    records.get(EXCEPTION_FORMATTER).multi.push(...exceptions); // save to reference new values
  }
}
```

Probably this (and idea with some service which handles instances) is only possible way to do it. However your proposition includes override existing providers in parent:

>Be somehow able to register providers from feature modules and refresh already created injectors to known them.

so what should be done after overriding with given instances in parent scope?

**Comment by alxhub** [comment]
Angular has immutable DI and there are no current plans to make it mutable, so this is not a feature that we plan to support.

I would suggest viewing this use case as "I want my lazily loaded module to have some side effect on existing services", not providing more things. Ngrx does this with `StoreModule.forFeature` - I'd suggest following this pattern instead.
