### ISSUE TITLE
Angular 10.2.0 leak memory

### ISSUE THREAD

**Issue by longcharmroeun** [angular/angular#39419]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 10.0.7

### Description
After I update angular v10.0.7 to v10.2.0 my browser ram was increased when reload browser.

Before updated ram usage: 15mb to 20mb.
After updated ram usage: 15mb to 20mb but it not release after reload browser it keep increase until restart browser or close tap.

My issue same as #17637 but different browser (chrome)

*Note** all my data collection is using async pipe and unsubscribe on ngOnDestroy

![ClientApp - Google Chrome 10_25_2020 6_35_04 PM](https://user-images.githubusercontent.com/42161560/97106493-87bbdf80-16f4-11eb-8283-29d136e7b6de.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.2.0
Node: 12.18.0
OS: win32 x64

Angular: 10.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.2.0
@angular-devkit/schematics      10.2.0
@angular/cdk                    10.2.5
@angular/fire                   6.0.3
@angular/flex-layout            10.0.0-beta.32
@angular/material               10.2.5
@schematics/angular             10.2.0
@schematics/update              0.1002.0
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
Unfortunately this provides the same amount of information as #39418 and it's not sufficient for us to investigate. I'd like to request again that you isolate the exact update (so update *only* Angular packages, nothing else) and then extract and share a minimal example that we can run to perform investigation (if it turns out that's indeed related to a change in Angular, which at this moment is not clear at all).

**Comment by longcharmroeun** [comment]
bug fix now after i use `npm cache clean --force`
thank for your response

> Unfortunately this provides the same amount of information as #39418 and it's not sufficient for us to investigate. I'd like to request again that you isolate the exact update (so update _only_ Angular packages, nothing else) and then extract and share a minimal example that we can run to perform investigation (if it turns out that's indeed related to a change in Angular, which at this moment is not clear at all).
