### ISSUE TITLE
Angular 10.2.0 Leak Memory after updated

### ISSUE THREAD

**Issue by longcharmroeun** [angular/angular#39418]
Normal ram usage: 15mb to 20mb.
After update ram usage: 15mb to 20mb but it not release after reload browser it keep increase until restart browser or close tap.

*Note** all my data collection is using async pipe and unsubscribe on ngOnDestroy

![ClientApp - Google Chrome 10_25_2020 6_35_04 PM](https://user-images.githubusercontent.com/42161560/97106030-d2882800-16f1-11eb-90a3-2d57c066c28b.png)

Before updated

> "dependencies": {
    "@angular-material-extensions/password-strength": "^6.0.0",
    "@angular/animations": "~10.0.5",
    "@angular/cdk": "^10.1.0",
    "@angular/common": "~10.0.5",
    "@angular/compiler": "^10.0.7",
    "@angular/core": "^10.0.7",
    "@angular/fire": "^6.0.2",
    "@angular/flex-layout": "^9.0.0-beta.31",
    "@angular/forms": "^10.0.7",
    "@angular/material": "^10.1.1",
    "@angular/platform-browser": "^10.0.7",
    "@angular/platform-browser-dynamic": "^10.0.7",
    "@angular/router": "^10.0.7",
    "@angular/service-worker": "^10.0.7",
    "@ionic-native/app-availability": "^5.28.0",
    "bootstrap": "^4.5.0",
    "cordova-plugin-browsertab": "0.2.0",
    "cordova-plugin-buildinfo": "4.0.0",
    "cordova-plugin-compat": "1.2.0",
    "cordova-plugin-inappbrowser": "4.0.0",
    "cordova-universal-links-plugin-fix": "1.2.1",
    "firebase": "^7.17.1",
    "hammerjs": "^2.0.8",
    "hls.js": "^0.14.13",
    "ng-mat-carousel": "^0.7.7",
    "ngx-auth-firebaseui": "^4.4.0",
    "ngx-mat-select-search": "^3.0.1",
    "ngx-sharebuttons": "^8.0.1",
    "password-strength": "github:angular-material-extensions/password-strength",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },

After updated
> "dependencies": {
    "@angular-material-extensions/password-strength": "^7.0.0",
    "@angular/animations": "~10.2.0",
    "@angular/cdk": "^10.2.5",
    "@angular/common": "~10.2.0",
    "@angular/compiler": "^10.2.0",
    "@angular/core": "^10.2.0",
    "@angular/fire": "^6.0.3",
    "@angular/flex-layout": "^10.0.0-beta.32",
    "@angular/forms": "^10.2.0",
    "@angular/material": "^10.2.5",
    "@angular/platform-browser": "^10.2.0",
    "@angular/platform-browser-dynamic": "^10.2.0",
    "@angular/router": "^10.2.0",
    "@angular/service-worker": "^10.2.0",
    "@ionic-native/app-availability": "^5.29.0",
    "bootstrap": "^4.5.3",
    "cordova-plugin-browsertab": "0.2.0",
    "cordova-plugin-buildinfo": "4.0.0",
    "cordova-plugin-compat": "1.2.0",
    "cordova-plugin-inappbrowser": "4.0.0",
    "cordova-universal-links-plugin-fix": "1.2.1",
    "firebase": "^7.24.0",
    "hammerjs": "^2.0.8",
    "hls.js": "^0.14.16",
    "ng-mat-carousel": "^0.7.9",
    "ngx-auth-firebaseui": "^4.4.0",
    "ngx-mat-select-search": "^3.1.2",
    "ngx-sharebuttons": "^8.0.1",
    "password-strength": "github:angular-material-extensions/password-strength",
    "rxjs": "~6.6.3",
    "tslib": "^2.0.3",
    "zone.js": "~0.11.2"
  },

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

---

Please isolate the exact update and extract a minimum reproduction before opening a new issue; in its current form it's unclear that this is caused by Angular.
