### ISSUE TITLE
feat(dgeni): change hierarchy of docs

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#3941]
In the grand re-shuffling of exports (See #3713, #3458), many things that previously lived outside of the `src/core` folder now live in `src/core`: di, forms, directives, change_detection. Consequently, with #3932 landing, these things are now imported from `angular2/core`. This presents a problem with the current docs side navigation, which would just have a few top-level modules, with core having a huge list of things underneath it.

The first way to solve this that comes to mind is to change the "sub-nav" to represent logical children of a top-level module, i.e.

```
|- core
|--- annotations
|--- change_detection
|--- di
|--- directives
|--- forms
|--- pipes
|- http
|- router
|- test
```

Thoughts @wardbell, @mhevery, @naomiblack?

**Comment by PascalPrecht** [comment]
@jeffbcross with "represent logical children of a top-level module" you mean, displaying them by default, without the user's need to "open" a top-level module first?

I would agree with that, but it would be a bit inconsistent because `http` and `router` don't have these sub-level modules (right?). So maybe we should rather have something like "categories" or "meta" modules that are created for each available top-level module, and this would have it's module components underneath it.

So pretty much what you said, but enforcing other top-level modules without sub-level modules to have sub-level modules.

**Comment by wardbell** [comment]
I think everything depends upon **how the developer sees the structure** when s/he imports these modules. If s/he would see them all listed in the IDE when importing from `angular/core`, so be it.  That's what the left nav should reflect.

I don't think the developer will know or care about the groupings that you're proposing. They just make it harder to find something that you know (more or less) by name.  I never liked the Easter egg hunt in Angular 1 ("looking for ngClick ... oops, wrong bucket ... keep looking ... oh, right, directives").

No, not keen on this suggestion.

I think I would like a module-level trampoline page that lists all the members in an alphabetical grid. That's a more compact representation than the long list in the left nav. But I'm describing a supplementary navigational aid.

**Comment by jeffbcross** [comment]
I guess the problem, more generally stated, is the concern of noise because hundreds of things will be exported, some of which are only exported because they're used by public APIs, though they're not first-class public APIs themselves (return types, parameters of classes that mostly are only constructed via DI for example).

**Comment by jeffbcross** [comment]
Yes, that whole comment was a single sentence.

**Comment by wardbell** [comment]
Maybe we need a marker for "small stuff" that is only exposed when you want to see it all. 

Anything with the small stuff comment is hidden by default but available by checking "Show it all!"

**Comment by wardbell** [comment]
And search can find anything, large or small.

**Comment by jeffbcross** [comment]
Such a marker may be useful. I'd guess that the ratio of actual "public APIs" to "types that happen to be used with public APIs" is something low, like 1:4.

**Comment by wardbell** [comment]
I kind of like the idea of a structured comment that both humans and dgeni can quickly read to understand the classification and categorization of an exported module member. 

A little tedious at first bit we have an inexpensive resource who can take a first crack at a sweep. Or maybe we automate that first sweep. Worth discussing internally?

**Comment by jeffbcross** [comment]
CC @alexwolfe, who I think is already working on re-designing the side nav.

**Comment by naomiblack** [comment]
@petebacondarwin -- one more requirement for this while you are looking at it.

Within a module, we also want to be able to re-order based on type, and then alphabetize. Currently we export everything in the order in which it appears in the API. 

Order we'd like to have implemented for each module:

1. globals (everything that’s not an enum, const, interface, or class)
1. enums and consts
1. interfaces
1. classes

**Comment by petebacondarwin** [comment]
Hmm. OK so what I am hearing here is:

1. We export loads of things that are not particularly relevant to the reader of the API docs
2. Arbitrary grouping of exports in a module can actually hinder browsing of the docs
3. It would be good if the navigation had a way to hide the not-so-important exports
4. Exports should be sorted by type (globals, enums, interfaces, classes, etc) and then alphabetically
5, All exported items should still be navigable/searchable.

We can certainly have a dgeni jsdoc tag on exports that says that it is either a primary or secondary navigable item. The navigation could then be arranged to do some different styling (possibly dynamic "show all") for the different navigable types. I am not quite sure if this is what you want.

Also note that sorting items into "type" order before alphabetizing might fall foul of number 2, which Ward is not keen on.
