### ISSUE TITLE
Update documentation for improving template type check

### ISSUE THREAD

**Issue by Lonli-Lokli** [angular/angular#39421]
# 📚 Docs or angular.io bug report

### Description

Improve documentation for the template type checking

## 🔬 Minimal Reproduction

https://angular.io/guide/structural-directives#make-in-template-type-requirements-more-specific-with-template-guards

### Expected vs Actual Behavior**

It should be possible to use different type guards for narrowing, in case of IfLoaded directive from documentation - should be added #else, similar to ngif-else syntax.

Second guard should return Loading state which can be used in else block with full type check

**Comment by JoostK** [comment]
Hi @Lonli-Lokli,

it's not currently possible to impose a type guard on anything other than the `ng-template` the directive is applied on; so I don't see how the documentation can show how that's supposed to work (as it can't be done 😅)

**Comment by Lonli-Lokli** [comment]
Implicit context can be specified with guard but it does not help to narrow union to specific type
See https://github.com/Lonli-Lokli/templateContextGuard - only one line will be treated as error

**Comment by JoostK** [comment]
Yes I understand what you mean, but the thing you're trying to do cannot currently be expressed in template context guards.

**Comment by Lonli-Lokli** [comment]
@alexzuza As I remember it was you who introduced support for that in ngIf.

Can you confirm it? If so, can you update docs with limitations and close this issue?

**Comment by Lonli-Lokli** [comment]
@JoostK can ot be implemented now with the https://github.com/angular/angular/pull/48374 landing?

**Comment by JoostK** [comment]
No, #48374 does not help; `NgTemplateOutlet` (or any directive, in fact) can only influence the type of the `ng-template` it is applied to.

**Comment by alxhub** [comment]
Closing as infeasible under the current model of template type-checking (and also `@else` is properly type-checked)
