### ISSUE TITLE
Update lifecycle hooks documentation in Ivy runtime code

### ISSUE THREAD

**Issue by AleksanderBodurri** [angular/angular#39439]
Something confuses me about the `preOrderHooks` array within `TView` objects.

According to https://github.com/angular/angular/blob/3236ae0ee118d0734c90fa9f3767435396213470/packages/core/src/render3/interfaces/view.ts#L658-L665

even indices are for directive indices and odd indices are for hook functions. The other hook arrays follow this exact same pattern.

I noticed that in several places where the hook arrays are updated, they are always updated with the directive index and hook function simultaneously, enforcing the encoding of even indices as directive indices and odd indices as hook functions. 

See
https://github.com/angular/angular/blob/3236ae0ee118d0734c90fa9f3767435396213470/packages/core/src/render3/hooks.ts#L40
https://github.com/angular/angular/blob/3236ae0ee118d0734c90fa9f3767435396213470/packages/core/src/render3/hooks.ts#L46
https://github.com/angular/angular/blob/3236ae0ee118d0734c90fa9f3767435396213470/packages/core/src/render3/hooks.ts#L50

In practice though this encoding is not always true for `preOrderHooks`. See this screenshot from https://angular.io :

<img width="1092" alt="Screen Shot 2020-10-26 at 8 27 29 PM" src="https://user-images.githubusercontent.com/39253660/97242752-0a16d300-17cb-11eb-96ad-c9bad4e69a82.png">

Notice how the `preOrderHooks` array does not follow this encoding. As far as I can tell the reason is this line:

https://github.com/angular/angular/blob/3236ae0ee118d0734c90fa9f3767435396213470/packages/core/src/render3/instructions/shared.ts#L1180-L1183

My understanding of these data structures is not strong enough yet to determine if this is a documentation issue or if there is something that is not behaving in the way that it should. Any clarification would be greatly appreciated, especially relating to the comment above that states `// We will push the actual hook function into this array later during dir instantiation`

**Comment by AndrewKushnir** [comment]
Hi @AleksanderBodurri,

I've looked at the comments and the code and I think the comments that you refer to (that talk about odd and even indices) are not accurate. The way hooks are encoded in the `tView.preOrderHooks` (and in other hooks-related fields) is as follows:

- the `TNode` index that points to the corresponding instance of a component in `LView`
- Pairs of `directive index` + `lifecycle hook fn` that contain information on which lifecycle hooks should be called (directive index for `ngOnInit` hooks is represented as a negative number, which indicates that the hook should be invoked only once)

So an array that you have on a screenshot contains the following information:
- 4 - a `TNode` index
- -143 - index of where directive instance can be found in an `LView`
- ngOnInit() - actual hook function (will be called in a context of a directive instance obtained using an index above)

(start of a new section) 
- 6 - index of the next `TNode` that represents a component that has lifecycle hooks
- 154 - directive instance index
- qt() - actual hook function
- -154 - directive instance index for the `ngOnInit` hook
- ngOnInit() - actual hook function

You can find additional information on the runtime data structures in the [VIEW_DATA.md](packages/core/src/render3/VIEW_DATA.md) file (note: it may also require some updates, but the main concepts are still the same).

I'll keep this ticket open to indicate that the hooks docs require an update (will also update the ticket title) and will close this once the docs are up-to-date.

Thank you.

**Comment by AleksanderBodurri** [comment]
I see. Thanks for the quick response @AndrewKushnir. 🙏 

Is there a reason why the `tNode` index is saved in the `preOrderHooks` array but not within any other hook array? I'm struggling to find locations in the code base where the `tNode` index is referenced when hooks are called.

**Comment by AndrewKushnir** [comment]
> Is there a reason why the tNode index is saved in the preOrderHooks array but not within any other hook array?

The lifecycle hooks that are stored in that array are invoked as we go through one element/component to another while executing a template, so it's important to keep track of the current index and which lifecycle hooks should be executed at a given point.

> I'm struggling to find locations in the code base where the tNode index is referenced when hooks are called.

You can have a look at the `callHooks` and `callHook` functions in [hooks.ts](https://github.com/angular/angular/blob/master/packages/core/src/render3/hooks.ts).

Note: I've also updated the docs for the tView.preOrderHooks and tView.preOrderCheckHooks fields (PR #39497), which caused initial confusion.

Thank you.
