### ISSUE TITLE
Public url for angular 2?

### ISSUE THREAD

**Issue by calebmer** [angular/angular#3943]
I'd love to try angular 2 with [codepen](codepen.io). Is there a public url I can reference to use angular 2 developer previews in my pens?

**Comment by pkozlowski-opensource** [comment]
Sure, try https://code.angularjs.org/
Ex. for the latest release: https://code.angularjs.org/2.0.0-alpha.36/

**Comment by calebmer** [comment]
Thanks so much, it might be helpful to put a link to this on [angular.io](http://angular.io/downloads) or npm which is how I got here :smile:
