### ISSUE TITLE
Missing official documentation on supported Node versions.

### ISSUE THREAD

**Issue by callumelgrant** [angular/angular#39436]
# 📚 Docs or angular.io bug report
### What's the affected URL?**
https://angular.io/guide/universal
### Description

At the moment there is no official guidance on what nodejs versions are supported/tested for Angular Universal, the platform-server package says that anything higher than 8 will work (https://github.com/angular/angular/blob/master/packages/platform-server/package.json) but it would be clearer if each Angular version had a supported nodejs version range like here: https://gist.github.com/LayZeeDK/e1b5b6e0599802c671b564a62d1261eb 

The main reason I'm bringing this up is that I would like to know if the current LTS version 14 is supported.

**Comment by alan-agius4** [comment]
Hi @callumelgrant, 

Angular supports the current, active LTS, or maintenance LTS versions of Node.js. Therefore version 14 is currently supported. 

More info
https://nodejs.org/en/about/releases/
https://angular.io/guide/setup-local#prerequisites

That said, I do agree that the docs for supported Node.Js versions are rather hard to find even when using the search.

**Comment by saiprasad2595** [comment]
Below representation looks so good than the existing ones. Should we consider this type of representation ? @kapunahelewong  @alan-agius4 
https://gist.github.com/LayZeeDK/e1b5b6e0599802c671b564a62d1261eb

**Comment by alan-agius4** [comment]
I think a table might not be necessary since the documentation is versioned based on the URL

IE:
http://www.angular.io is the documentation for v10
http://v9.angular.io is the documentation for v9

**Comment by saiprasad2595** [comment]
And where do we see the Angular supported versions of Typescript, Webpack ? Is this the place?  https://github.com/angular/angular-cli/blob/master/package.json

**Comment by kapunahelewong** [comment]
@mgechev and @aikidave might have more info, but maybe these could help you:

Here's info on TypeScript:
https://angular.io/guide/updating-to-version-10

And info on Webpack:
https://angular.io/guide/roadmap#webpack-5-in-the-angular-cli

**Comment by alan-agius4** [comment]
In version 11.0.x, only Typescript 4.0.x is supported, while in v11.1.x TypeScript 4.1 will also be supported.

With regards to Webpack, version 5 is supported experimentally opt-in using yarn module resolutions. 

NB: Webpack is considered an implementation detail of the Angular CLI and users shouldn’t be concerned too much about which version is currently being used/supported by the CLI.

**Comment by KingDarBoja** [comment]
Based on previous comments, maybe a small list of prerequisites can be added for each version based URL at the https://angular.io/guide/setup-local#prerequisites section using the provided "compatibility" table?

**Comment by davidroeca** [comment]
It would also probably be best to update the engines field here: https://github.com/angular/angular/blob/0fc8466f1be392917e0c7e3448b2144d52286b56/package.json#L11

Technically, node 14 isn't supported by this line. And a `yarn add` will actually fail.

Related (the exact same problem): https://github.com/angular/vscode-ng-language-service/issues/1040

**Comment by alan-agius4** [comment]
> It would also probably be best to update the engines field here:
> 
> https://github.com/angular/angular/blob/0fc8466f1be392917e0c7e3448b2144d52286b56/package.json#L11
> 
> Technically, node 14 isn't supported by this line. And a `yarn add` will actually fail.
> 
> Related (the exact same problem): [angular/vscode-ng-language-service#1040](https://github.com/angular/vscode-ng-language-service/issues/1040)

that’s actually not quite right, because the package manifest you referenced is the one used to install dependencies in the Angular monorepo and is not shipped with any `@angular/` package. 

Each package has a dedicated package manifest such as https://github.com/angular/angular/blob/362f45c4bf1bb49a90b014d2053f4c4474d132c0/packages/compiler-cli/package.json#L35
