### ISSUE TITLE
More typos in the component overview documentation (Defining a component's template & Next steps)

### ISSUE THREAD

**Issue by imkikus** [angular/angular#39444]
I find more typos in the docs.
Here are the links [1](https://angular.io/guide/component-overview#defining-a-components-template) & [2](https://angular.io/guide/component-overview#next-steps) for reference.
PFA snapshots

![Screenshot from 2020-10-27 09-31-22](https://user-images.githubusercontent.com/10371390/97256537-441ebe00-1839-11eb-9608-e332dac1fd26.png)
![Screenshot from 2020-10-27 09-31-10](https://user-images.githubusercontent.com/10371390/97256540-46811800-1839-11eb-93ff-c4467b3de3b6.png)

**Comment by AndrewKushnir** [comment]
Closing this ticket as the corresponding PR #39445 was merged.
