### ISSUE TITLE
ForwardRef example in documentation is outdated

### ISSUE THREAD

**Issue by ahnpnl** [angular/angular#39447]
# 📚 Docs or angular.io bug report

### Description

The example for `forwardRef` at https://angular.io/api/core/forwardRef is using the deprecated api `ReflectiveInjector.resolveAndCreate`

### What's the affected URL?**

https://angular.io/api/core/forwardRef

### Reproduction Steps**

- Go to https://angular.io/api/core/forwardRef

- Check the example codes

### Expected vs Actual Behavior**

The example codes should use `Injector.create` API

## 📷Screenshot

![image](https://user-images.githubusercontent.com/27772165/97285022-05413600-1842-11eb-8d70-cd99c5f8e80e.png)

## 🔥 Exception or Error

**N.A.**

## 🌍  Your Environment

**N.A.**

**Comment by eduardbme** [comment]
#39519

**Comment by AndrewKushnir** [comment]
@ahnpnl thanks for reporting this and thanks @eduardbme for updating the docs! I'm closing this ticket, since the corresponding PR (#39519) is now merged.
