### ISSUE TITLE
xi18n creates different id's for same texts

### ISSUE THREAD

**Issue by AndiPerlitz** [angular/angular#39449]
# 🐞 Bug report

### Command (mark with an `x`)

- [ X ] extract-i18n

### Is this a regression?

Don't know, I am using this version for the first time

### Description

When creating a translation file in xlf-format using the tool xi18n with the option --ivy=true there are different Id's for same words in ts-files and in html-files. 

## 🔬 Minimal Reproduction
I created a new project named localize-test with this steps (will reproduce the bug reliable):

- create project with command: ```ng new localize-test```
- goto directory localize-test, execute: ```ng add @angular/localize```
- replace content of file src/app/app.component.html with this: 
```
<div i18n>Country</div>
<div>{{test1}}</div>
<div>{{test2}}</div>
```
- replace content of file src/app/app.component.ts with this:
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'localize-test';
  test1 = $localize `Country`;
  test2 = $localize `CountryRoad`;
}
```
- execute command: ```ng xi18n --outFile=.\dist\out-locl\locl.xlf --ivy=true```

## 🔥 Exception or Error

The file ./dist/out-locl/local.xlf contains the following xml-structure:
```
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en-US" datatype="plaintext" original="ng2.template">
    <body>
      <trans-unit id="516176798986294299" datatype="html">
        <source>Country</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.ts</context>
          <context context-type="linenumber">10</context>
        </context-group>
      </trans-unit>
      <trans-unit id="6079395462132705951" datatype="html">
        <source>CountryRoad</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.ts</context>
          <context context-type="linenumber">11</context>
        </context-group>
      </trans-unit>
      <trans-unit id="a43f25a9ac40e8e2441ff0be7a36b8e5d15534df" datatype="html">
        <source>Country</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">1</context>
        </context-group>
      </trans-unit>
    </body>
  </file>
</xliff>
```
There are two trans-unit tags, that contain the source **Country**. One from the ts-file, one from the html-file. But even though these texts are identical the id is different. For the translators this is an issue, since the same texts have to be translated multiple times, depending on its placement in code or html.

## 🌍 Your Environment
<pre><code>
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 10.1.7
Node: 12.18.4
OS: win32 x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cli                    10.1.7
@schematics/angular             10.1.7
@schematics/update              0.1001.7
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by petebacondarwin** [comment]
This is because the Angular compiler is currently configured to generate legacy IDs for the messages extracted from there, while messages extracted from application code use the non-legacy ID format.

You can (and should turn this off by applying `"enableI18nLegacyMessageIdFormat": false` in your tsconfig.json files.
This will become the default at some point but it currently defaults to true.

**Comment by petebacondarwin** [comment]
Closing since this is working as expected.

**Comment by AndiPerlitz** [comment]
> You can (and should turn this off by applying `"enableI18nLegacyMessageIdFormat": false` in your tsconfig.json files.
> This will become the default at some point but it currently defaults to true.

Thanks for the explanation :) But unfortunately this option seems not to be a known compiler option. I keep getting the error message

An unhandled exception occurred: tsconfig.json:10:5 - error TS5023: Unknown compiler option 'enableI18nLegacyMessageIdFormat'.

10     "enableI18nLegacyMessageIdFormat": false,
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

when trying to built the project with this option. Is there something else, I have to configure to make this work?

**Comment by petebacondarwin** [comment]
Oops sorry, I meant to be more clear. It needs to be in the Angular compiler options. So something like:

```jsonc
{
  "compilerOptions": {
    ...
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false
  }
}
```

**Comment by AndiPerlitz** [comment]
Wow, great. Thank you so much 👍 This did the trick. Thanks for the very quick help.

**Comment by petebacondarwin** [comment]
I am - right now - putting together PRs to update the `ng new` template for a workspace to set this default, and to update the docs.

**Comment by petebacondarwin** [comment]
https://github.com/angular/angular-cli/pull/19232 and https://github.com/angular/angular/pull/39453
