### ISSUE TITLE
Improve documentation of NO_ERRORS_SCHEMA

### ISSUE THREAD

**Issue by FabianGosebrink** [angular/angular#39454]
# 📚 Docs or angular.io bug report

### Description

I recently had to fight with tests at a customer and it turned out that the tests only ran because he included the `NO_ERRORS_SCHEMA` in his tests. The `NO_ERRORS_SCHEMA` caused the tests to run through but they swallowed every problem in the template, even wrong attributes on components etc.

The initial intention was only to skip not provided components to not declare all of them inside the ` TestBed.configureTestingModule({ ... })` `declarations` array. The intention is totally fine IMHO but solving this with `NO_ERRORS_SCHEMA` results in tests which appear green and maybe do not test anything and leading to weighing the developer in a false security. This case should be solved with the `CUSTOM_ELEMENTS_SCHEMA`.

The documentation shows nothing at the page [https://angular.io/api/core/NO_ERRORS_SCHEMA](https://angular.io/api/core/NO_ERRORS_SCHEMA) and even uses it in the tests shown [https://angular.io/guide/testing-attribute-directives](https://angular.io/guide/testing-attribute-directives) without giving a warning that `NO_ERRORS_SCHEMA` mostly swallows more than the developer wanted to and may result in false positive tests.

### What's the affected URL?**
[https://angular.io/api/core/NO_ERRORS_SCHEMA](https://angular.io/api/core/NO_ERRORS_SCHEMA)
[https://angular.io/guide/testing-attribute-directives](https://angular.io/guide/testing-attribute-directives)

### Reproduction Steps**
None

### Expected vs Actual Behavior**
I would expect the documentation to point out to what the difference between `CUSTOM_ELEMENTS_SCHEMA` and `NO_ERRORS_SCHEMA` is and that the last one could lead to false results.

**Comment by Splaktar** [comment]
Agreed! I recently had a client who used this on 95% of their tests (~500). They didn’t test any real functionality, just that components rendered. It turned out that those tests were completely useless and not even testing rendering when `NO_ERRORS_SCHEMA` was used. It’s really dangerous and confuses a lot of developers.

The docs for it should explicitly call this out and recommend that people don’t use this schema just to make their tests pass, because it just covers up other valid errors and results in tests that don’t actually test anything.

The current docs (https://angular.io/api/core/NO_ERRORS_SCHEMA) need examples of when it's appropriate to use this API.

**Comment by kapunahelewong** [comment]
Wow. Thanks for this issue, @FabianGosebrink, and @Splaktar for the additional context. 

cc @aikidave

**Comment by aikidave** [comment]
Yes, thank you for bringing this to our attention!

**Comment by AndrewKushnir** [comment]
Hi @FabianGosebrink, thanks for creating this ticket. I've submitted a PR #42327 to improve the docs of the `NO_ERRORS_SCHEMA` symbol and switched from using the `NO_ERRORS_SCHEMA` to `CUSTOM_ELEMENTS_SCHEMA` in the mentioned guide. Please let us know if you have any feedback and feel free to create a PR with additional improvements if needed. Thank you.

**Comment by FabianGosebrink** [comment]
Hey @AndrewKushnir, thanks for getting back with this. The text really is on point and I think this is a great enhancement. Thank you very much for this.

**Comment by jcludwig** [comment]
It's really unclear to me what the recommended strategy is for unit testing components with testing child components. `CUSTOM_ELEMENTS_SCHEMA` only ignore components/directives that are named with a `-`, but directives are supposed to be named using camelCase. So we ignore components but not directives?

**Comment by AndrewKushnir** [comment]
@jcludwig you can still use the `NO_ERRORS_SCHEMA` schema, but the `CUSTOM_ELEMENTS_SCHEMA` is more preferred where you can use it instead.
