### ISSUE TITLE
Lighthouse "Best Practices" issue with zone.js

### ISSUE THREAD

**Issue by initplatform** [angular/angular#39484]
# 🐞 bug report

### Affected Package

The issue is caused by zone.js

### Is this a regression?

not applicable

### Description

`polyfills.ts` contains:

```javascript
import 'zone.js/dist/zone'; // Included with Angular CLI.
```

When running lighthouse on my app, I see this:

<img width="725" alt="Screen Shot 2020-10-28 at 9 13 11 PM" src="https://user-images.githubusercontent.com/47506789/97513380-75df7400-1962-11eb-8648-5ee930f1d5c1.png">

grepping though all the files that `polyfills.ts` pulls in, only zone.js uses unload.

The details of the issue are here ->

https://developers.google.com/web/updates/2018/07/page-lifecycle-api?utm_source=lighthouse&utm_medium=devtools#the-unload-event

## 🔬 Minimal Reproduction

Running Lighthouse on any angular app should exhibit the issue. 

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 10.1.7
Node: 12.18.3
OS: darwin x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.1
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.1.1
@angular-devkit/schematics      10.1.7
@angular/cli                    10.1.7
@nguniversal/builders           10.1.0
@nguniversal/express-engine     10.1.0
@schematics/angular             10.1.7
@schematics/update              0.1001.7
rxjs                            6.6.3
typescript                      4.0.3

</code></pre>

**Anything else relevant?**

Chrome -> Version 86.0.4240.111 (Official Build) (x86_64)

**Comment by JiaLiPassion** [comment]
@initplatform, `zone.js` doesn't register `unload` event, all event listeners will call `zone.js` patched version, so it looks like it is from `zone.js`, I just checked it, in dev mode, `ng serve` is using `socket.js` to do the live loading (maybe), so the `unload` event is registered by the `socket.js`, if you run `ng build --prod` and try lighthouse again, this unload warning will be gone.

**Comment by AndrewKushnir** [comment]
Closing this ticket based on the comment above. Feel free to reopen if the problem still exists. Thank you.

**Comment by initplatform** [comment]
You can run lighthouse on our app to see it. 

https://startbootstrap.com/

This is build with :
```
npm run ng -- build --prod --crossOrigin=anonymous --build-optimizer=true --vendor-chunk=true --statsJson=true
```

**Comment by initplatform** [comment]
Also.. we have upgraded to angular 11, same issue.

```
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.1
Node: 12.18.3
OS: darwin x64

Angular: 11.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.1
@angular-devkit/build-angular   0.1100.1
@angular-devkit/core            11.0.1
@angular-devkit/schematics      11.0.1
@angular/cli                    11.0.1
@nguniversal/builders           11.0.0
@nguniversal/express-engine     11.0.0
@schematics/angular             11.0.1
@schematics/update              0.1100.1
rxjs                            6.6.3
typescript                      4.0.5
```

**Comment by initplatform** [comment]
Also, shouldn't matter, but FWIW, `npm run ng` is:

```
"ng": "cross-env NODE_OPTIONS=--max_old_space_size=2048 ./node_modules/.bin/ng",
```

**Comment by gkalpak** [comment]
I ran Lighthouse on https://startbootstrap.com/ and the one report about `unload` event I got was from line 23 of the `fbevents.js` file (which is not related to Angular). Are you seeing something different, @initplatform?

**Comment by initplatform** [comment]
This is weird.. If I do it multiple times I see one.. or the other... 

<img width="994" alt="Screen Shot 2020-11-30 at 3 22 10 PM" src="https://user-images.githubusercontent.com/47506789/100660330-e1c94980-331f-11eb-815b-9609b308ad44.png">

The first time I did it, I saw the facebook one like you.. but now I only seem to be getting the polyfills one `https://startbootstrap.com/polyfills-es2015.9509cf6cf3660a1b8556.js`

I wonder if this may have something to do with the pwa voodoo in `ngsw-worker.js` ... 

Are you able to run it multiple times and see the `polyfills-es2015.9509cf6cf3660a1b8556.js` one?

**Comment by initplatform** [comment]
This is the contents of my polyfills.ts with all comments removed:

```
import '@angular/localize/init';

import 'zone.js/dist/zone'; // Included with Angular CLI.

import smoothscroll from 'smoothscroll-polyfill';
smoothscroll.polyfill();
```

smoothscroll does not appear to be using `unload` -> https://github.com/iamdustan/smoothscroll/blob/master/src/smoothscroll.js

I wonder if lighthouse is incorrectly thinking zone.js is using unload, since it includes ->
node_modules/zone.js/dist/zone.js - line 2332

```javascript
    var windowEventNames = [
        'absolutedeviceorientation',
        'afterinput',
        'afterprint',
        'appinstalled',
        'beforeinstallprompt',
        'beforeprint',
        'beforeunload',
        'devicelight',
        'devicemotion',
        'deviceorientation',
        'deviceorientationabsolute',
        'deviceproximity',
        'hashchange',
        'languagechange',
        'message',
        'mozbeforepaint',
        'offline',
        'online',
        'paint',
        'pageshow',
        'pagehide',
        'popstate',
        'rejectionhandled',
        'storage',
        'unhandledrejection',
        'unload',
        'userproximity',
        'vrdisplayconnected',
        'vrdisplaydisconnected',
        'vrdisplaypresentchange'
    ];
```

**Comment by JiaLiPassion** [comment]
@initplatform, just like @gkalpak said, the `unload` is added by `fbevents.js`

```
 g.addEventListener("unload", function() {
                        return m.forceEndBatch()
                    });
```

**Comment by gkalpak** [comment]
Here is what I believe happens:
`fbevents.js` registers an `unload` listener. When `zone.js` is loaded, it monkey-patches the `addEventListener()` method, so any calls to that method appear as if they are coming from `polyfills.js`. Depending on whether `zone.js` has been loaded before `fbevents.js` registers the `unload` listener, it might appear to LightHouse that the `addEventListener()` call is coming from `polyfills.js` or `fbevents.js`.

So, as @JiaLiPassion has said above, `zone.js` does not register any `unload` listeners. You can also see this by running LightHouse on an Angular app that does not import any 3rd party library that registers `unload` listeners (for example https://angular.io/).

I am going to close this, since there doesn't seem to be anything to be fixed in Angular or `zone.js`. Feel free to continue the discussion below in case I have missed something or you need more clarification.

**Comment by initplatform** [comment]
Thanks @gkalpak and @JiaLiPassion. Makes sense. Looks like I need to file a bug against facebook :)

**Comment by Splaktar** [comment]
I'm seeing this in https://www.devintent.com/ which does not use `fbevents.js`.

I looked at each of the libraries in my `polyfills.ts` and the only one with the string `'unload'` in it is zone.js.

Then after reading this thread, I thought that I might have been wrong... so I went and looked at https://www.devintent.com/polyfills-es2015.00bf12ee6ad9d54b5a1c.js and searched for the string in there and the only place that it was found was in the zone.js code.

![Screen Shot 2020-12-09 at 16 19 08](https://user-images.githubusercontent.com/3506071/101718943-40a16800-3a70-11eb-8ca8-ed3467e69850.png)

This error alone, takes 7 points off of the Lighthouse Best Practices audit.

I think that many people are going to hit this issue. It might be worth pinning it and providing clear steps for how to track down the actual library that registers the `unload` listener:

1. Open your app in incognito mode to run lighthouse audits
1. If you see this issue in the Best Practices audit, go to your Sources tab
1. Right click on the `top` folder in the left panel

    ![Screen Shot 2020-12-09 at 22 50 42](https://user-images.githubusercontent.com/3506071/101719285-06849600-3a71-11eb-8e81-165358f8a4be.png)

1. Select "Search all files"
1. Search for `addEventListener("unload"`

![Screen Shot 2020-12-09 at 22 52 51](https://user-images.githubusercontent.com/3506071/101719419-49466e00-3a71-11eb-9131-967e2fa78c41.png)

In my case, the offending library is LogRocket.

Should we write up an issue in the Lighthouse repo to ask them to make it smarter? It seems like the audit should be able to do this kind of thing automatically and save us a lot of extra issues.

**Comment by gkalpak** [comment]
It would be cool if Lighthouse could detect this, but I am not sure how feasible it is (without hard-coding a special case for Zone.js). Text-searching for `addEventListener('unload'` is not a very robust approach. I assume Lighthouse is tracking actual calls to `addEventListener()`. So, when a library monkey-patches `addEventListener()`, it is not really possible for Lighthouse to figure that out automatically (in a reasonable way) 🤷‍♂️

<sub>Happy to be proven wrong, though :grin:</sub>
