### ISSUE TITLE
Not possible to insert dynamic components for root components

### ISSUE THREAD

**Issue by mhevery** [angular/angular#39499]
# 🐞 bug report

### Affected Package
`@angular/core`

### Is this a regression?

No, ViewEngine has same behavior.

### Description

A root component (or a dynamically inserted one) should be able to inject `ViewContainerRef` and than into that `ViewContainerRef` insert dynamic components.

## 🔬 Minimal Reproduction

```typescript

  fit('should work', () => {
    @Component({
      selector: 'dynamic',
      template: `DYNAMIC COMPONENT`,
    })
    class Dynamic {
    }

    @Component({
      selector: 'my-app',
      template: `MY APP`,
    })
    class AppComponent {
      constructor(
          public _vcRef: ViewContainerRef, public _cfr: ComponentFactoryResolver,
          public _injector: Injector) {
        appComponent = this;
      }
    }

    @Component({template: `<my-app></my-app>`})
    class Root {
    }

    @NgModule({
      declarations: [Root, AppComponent, Dynamic],
      exports: [Root, AppComponent, Dynamic],
      entryComponents: [Root, AppComponent, Dynamic]
    })
    class AppModule {
    }

    TestBed.configureTestingModule({imports: [AppModule]});
    let bootstrapCmp: Type<any> = AppComponent;
    // Turns out that if we bootstrap `AppComponent` `appComponent._vcRef.insert(cmptRef.hostView);`
    // does not work as no DOM gets inserted for `Dynamic`. Wrapping the test case in additional
    // component (`Root`) makes this work. This behavior is not correct as no `Root` should be
    // needed.
    // bootstrapCmp = Root; // uncommenting this makes this test pass.
    const fixture = TestBed.createComponent(bootstrapCmp);
    let appComponent!: AppComponent;
    fixture.detectChanges();

    const cmptRef =
        appComponent._cfr.resolveComponentFactory(Dynamic).create(appComponent._injector);
    appComponent._vcRef.insert(cmptRef.hostView);
    expect((fixture.nativeElement as HTMLElement).outerHTML).toContain('DYNAMIC COMPONENT');
  });
```

## 🔥 Exception or Error

I would expect that root (or dynamic components) should be able to insert children into their corresponding `ViewContainerRef`s 

## 🌍  Your Environment

**Angular Version:**
<pre><code>
v11.1.0-next.0
</code></pre>

**Anything else relevant?**
Same issue is found in ViewEngine

**Comment by JiaLiPassion** [comment]
The `dynamic component` is rendered, but not under `app component`, it is under `body`.
![Screen Shot 2020-10-30 at 5 44 30](https://user-images.githubusercontent.com/1442575/97630529-16bd5480-1a73-11eb-99a9-0f19d1cf2c9a.png)

**Comment by mhevery** [comment]
OK, I got confused. This works as intended. The `fixture.nativeElement` points to `<div id="root0">` which is the root components host. So any dynamic components should be inserted as siblings to the host, which is exactly what is happening. So working as intended.
