### ISSUE TITLE
What the versions of second-layer dependencies are currently supported by angular?

### ISSUE THREAD

**Issue by WuglyakBolgoink** [angular/angular#39500]
Hallo guys!

it will be great to know which versions support @angular for this packages:

- tslib
- ts-node
- zone.js
- typescript

per release!

For example, we use `exact version` for each package and we do upgrade manually. And sometimes we have something like this: 
![image](https://user-images.githubusercontent.com/2271337/97629891-0f745780-1a2f-11eb-8bb3-8bbcbb243df0.png)

and I'm pretty sure or not, that angular@10.2.x doesn't support this libs...

**Comment by jelbourn** [comment]
These dependencies are listed in each Angular packge's `package.json`, e.g.:
https://unpkg.com/browse/@angular/core@10.2.1/package.json
