### ISSUE TITLE
Chaining Http requests catch only on first one

### ISSUE THREAD

**Issue by vahidvdn** [angular/angular#39530]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common/http

### Is this a regression?

 No

### Description

I'm chaining Angular Http request as following. The issue is when the first request fails, I get it on error callback, but if the second one fails, nothing happens.

```typescript
this.myService.requestOne(this.data)
.pipe(mergeMap(dataOne=>{
  return this.myService.requestTwo(dataOne);
}))
.subscribe(dataTwo=>{
  this.loading = false;
},
(err)=>{
  // this fires when only requestOne get failed
  this.loading = false;
});
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>

@angular-devkit/architect       0.1001.4
@angular-devkit/build-angular   0.1001.4
@angular-devkit/core            10.1.4
@angular-devkit/schematics      10.1.6
@angular/animations             10.1.5
@angular/cdk                    10.2.4
@angular/material               10.2.4
@schematics/angular             10.1.6
@schematics/update              0.1001.4 (cli-only)
rxjs                            6.6.3
typescript                      4.0.3

</code></pre>

**Anything else relevant?**

**Comment by destus90** [comment]
I don't think that is a bug in the Angular framework. This is the default behavior for RxJS: when an error is thrown, the Subscriber unsubscribes from the source observable.
https://github.com/ReactiveX/rxjs/blob/c746fec4ec8a1e8238ac79290ed3c9113996226f/src/internal/operators/OperatorSubscriber.ts#L47

**Comment by spock123** [comment]
@vahidvdn  I also had this issue inside ngrx effects.

You need to use catchError to cache issues , otherwise, as @destus90 wrote, you'll lose the subscription.

**Comment by vahidvdn** [comment]
@spock123 Thanks. Would you please give me an example based on my code?

**Comment by spock123** [comment]
> @spock123 Thanks. Would you please give me an example based on my code?

```
`

... import { catchError } from 'rxjs/operators';

this.myService.requestOne(this.data)
.pipe(mergeMap(dataOne=>this.myService.requestTwo(dataOne)), 
  catchError(err) => { console.error('error: ', err); throw err; }
)
.subscribe(dataTwo=>{
  this.loading = false;
},
(err)=>{
  // this fires when only requestOne get failed
  this.loading = false;
});`
```

**Comment by djleonskennedy** [comment]
@vahidvdn Hello! 
here a example how to do it prop

https://stackblitz.com/edit/a-bit-error-handling-for-man?file=index.ts

your pattern with `mergeMap` is incorrect for your task

BR

**Comment by vahidvdn** [comment]
@spock123 your code has some syntax errors.

@djleonskennedy Thanks, but I don't want to run them together. I want to run one after another. As I mentioned in the issue.

**Comment by spock123** [comment]
> @spock123 your code has some syntax errors.
> 
> @djleonskennedy Thanks, but I don't want to run them together. I want to run one after another. As I mentioned in the issue.

Of course it has syntax errors, it was just conceptually from the top of my mind. Hopefully it was enough for you to get the idea of how to use `catchError`

**Comment by vahidvdn** [comment]
@spock123 I tried the right syntax but it didn't work either. As following:

```TS
return this.cancelSubscriptionService.recordCancelReason(data).pipe(catchError(err => throwError(err)))
```

**Comment by spock123** [comment]
> @spock123 I tried the right syntax but it didn't work either. As following:
> 
> ```ts
> return this.cancelSubscriptionService.recordCancelReason(data).pipe(catchError(err => throwError(err)))
> ```

Is the error caught? Other than that I'm not sure what it could be

**Comment by djleonskennedy** [comment]
@vahidvdn use `switchMap` then and the most **important** close issue, there is nothing related to angular

BR

**Comment by maroon1** [comment]
@vahidvdn 
```diff

this.myService
  .requestOne(this.data)
  .pipe(
-    mergeMap((dataOne) => {
+    switchMap((dataOne) => {
      return this.myService.requestTwo(dataOne);
    }),
  )
  .subscribe(
    (dataTwo) => {
      this.loading = false;
    },
    (err) => {
      // this fires when only requestOne get failed
      this.loading = false;
    },
  );
```

**Comment by vahidvdn** [comment]
@djleonskennedy @maroon1 No change. Still the same issue

**Comment by djleonskennedy** [comment]
@vahidvdn All works

https://stackblitz.com/edit/rxjs-qvmry5?devtoolsheight=60

**Comment by vahidvdn** [comment]
@djleonskennedy Would you please see my comments in the code?

https://stackblitz.com/edit/rxjs-vaduaj?devtoolsheight=60

**Comment by djleonskennedy** [comment]
> @djleonskennedy Would you please see my comments in the code?
> 
> https://stackblitz.com/edit/rxjs-vaduaj?devtoolsheight=60

That `map` just represents http failing, even if second http fails, 
error of second http call will be captured by second callback in subscribe method
with means error callback

**Comment by AndrewKushnir** [comment]
Hi, I'm closing this ticket based on the comments above - it doesn't seem to be an issue in the framework. Thank you.
