### ISSUE TITLE
Importing FORM_DIRECTIVES breaks compilation

### ISSUE THREAD

**Issue by w1zeman1p** [angular/angular#3953]
When importing `FORM_DIRECTIVES` and adding to the list of directives on the view like so:
```ts
/// <reference path="typings/angular2/angular2.d.ts" />
import {Component, View, FORM_DIRECTIVES, bootstrap} from 'angular2/angular2'
@Component({ selector: 'my-app' })
@View({
  template: '<input #f>',
  directives: [FORM_DIRECTIVES]
})
class MyAppComponent {}
bootstrap(MyAppComponent);
```

The following error occurs:

```
Unexpected directive value 'undefined' on the View of component 'MyAppComponent'

Error: Unexpected directive value 'undefined' on the View of component 'MyAppComponent'
    at new BaseException (https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:7248:25)
    at execute.Compiler._compile (https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:27803:21)
    at https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:27835:35
    at Function.execute.ListWrapper.forEach (https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:7726:15)
    at execute.Compiler._compileNestedProtoViews (https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:27830:23)
    at https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:27781:27
    at Zone.run (https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:115:17)
    at Zone.execute.NgZone._createInnerZone.zone.fork.fork.$run [as run] (https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:13116:38)
    at zoneBoundFn (https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:88:19)
    at lib$es6$promise$$internal$$tryCatch (https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:1338:16)
```

**Comment by debanjanbasu** [comment]
FORM_DIRECTIVES are a part of angular alpha > 35. Please upgrade to at least version 35 or even better 36. But I'm facing issues with version 36 with the router.

**Comment by robwormald** [comment]
FORM_DIRECTIVES are in the `angular2/forms` module, so you need to import them from there.

For future reference, the first thing you should check whenever you see an error like this is that things you import are actually defined.

**Comment by pkozlowski-opensource** [comment]
@w1zeman1p  `FORM_DIRECTIVES` are only available starting from alpha.35 and you are using 2.0.0-alpha.28. Upgrade to the latest release.

**Comment by w1zeman1p** [comment]
Thanks for your help! That (incorrect version) was it. I had the typings for 36 but was using the .28 version so in my editor the types were importing fine, but weren't actually available.

**Comment by cdcooksey** [comment]
For posterity, `angular2/forms` no longer exists. It is now imported as such:

```typescript
import {ControlGroup, Control, FORM_DIRECTIVES} from "angular2/common";
```

**Comment by ericmartinezr** [comment]
@cdcooksey since alpha 46, where PLATFORM_DIRECTIVES was introduced, you don't need to explicitely import FORM_DIRECTIVES, nor CORE_DIRECTIVES. Those are included implictely in your app. `PLATFORM_DIRECTIVES` contains `COMMON_DIRECTIVES` by default, which contains `CORE_DIRECTIVES` and `FORM_DIRECTIVES`.

**Comment by cdcooksey** [comment]
@ericmartinezr  My project fails when I do not explicitly import `FORM_DIRECTIVES`.  We're using 2.0.0-beta.7

```
  "dependencies": {
    "@ngrx/store": "^1.2.1",
    "angular2": "^2.0.0-beta.7",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.5.15"
  }
```

This works:

```typescript
import {ControlGroup, Control, FORM_DIRECTIVES} from "angular2/common";

@Component({
    selector: 'person-form',
    directives: [FORM_DIRECTIVES],
    template: require('./person_form.html')
})

export class PersonForm { ... } 
```

This fails with `FORM_DIRECTIVES` as _undefined_:

```typescript
import {ControlGroup, Control} from "angular2/common";

@Component({
    selector: 'person-form',
    directives: [FORM_DIRECTIVES],
    template: require('./person_form.html')
})

export class PersonForm { ... } 
```

It doesn't seem to be explicitly included. That is if unless there's a setting I should enable?

**Comment by ericmartinezr** [comment]
@cdcooksey you simply don't need to do this anymore `directives: [FORM_DIRECTIVES],`, don't include it as a directive since is part of platform directives and those are available in your whole app.

**Comment by cdcooksey** [comment]
@ericmartinezr Ah. Apologies. I didn't quite understand exactly what you meant.  I tried it, and it works great.

```typescript
import {ControlGroup, Control} from "angular2/common";

import {Person} from "../model/person";

@Component({
    selector: 'person-form',
    template: require('./person_form.html')
})
```

Removing `directives: [FORM_DIRECTIVES]` works great.

Thanks for clearing up my confusion!

**Comment by ericmartinezr** [comment]
@cdcooksey sorry for not being clear enough since the beginning, actually I read my comment again and to be honest it was a mess. Sorry for that, and I'm glad now you understood :+1:  :smile:
