### ISSUE TITLE
The keyvalue pipe does not work correctly with types. (Since v11-next.4)

### ISSUE THREAD

**Issue by infacto** [angular/angular#39533]
# 🐞 bug report

### Affected Package
The issue is caused by package `@angular/common` ([/src/pipes/keyvalue_pipe.ts](https://github.com/angular/angular/blob/master/packages/common/src/pipes/keyvalue_pipe.ts))

### Is this a regression?

The pipe from Angular version [11.0.0-next.3](https://github.com/angular/angular/blob/11.0.0-next.3/packages/common/src/pipes/keyvalue_pipe.ts) works. But [11.0.0-next.4](https://github.com/angular/angular/blob/11.0.0-next.4/packages/common/src/pipes/keyvalue_pipe.ts) does **not** work.

I included the source code to my repository with another pipe name `mykeyvalue` and checked both versions on the latest Angular version.

### Description

The `keyvalue` pipe does not work correctly with types. Since `11.0.0-next.4`. Changes:

![image](https://user-images.githubusercontent.com/60390085/97866339-0ecc1180-1d0c-11eb-8953-a966a0adf595.png)

## 🔬 Minimal Reproduction

**Screenshots**

![demo](https://user-images.githubusercontent.com/60390085/97168146-3e1cd480-1788-11eb-929d-ea4b82aa7f9a.gif)
(Gif Animation. Wait for the first frame in `app.component.html`)

**Additional context**

[**Download** Demo Project](https://github.com/angular/vscode-ng-language-service/files/5438507/keyvalue-pipe-test.zip)

**To Reproduce**

1. Use the `keyvalue` pipe on a property with a custom type. See my source code blocks / graphics or download the demo (see below).
2. See that all properties of `value` are marked as error. The pipe does not pass the type correctly.
3. Build it. It works. But the error in editor persists. It seems to be related to the ng extension. 
4. Try restart of VS Code. Nothing helped.

**Source Code**

app.component.html
```html
<ul>
  <li *ngFor="let entry of menuService.menu | keyvalue">
    <span>{{ entry.value.text }}</span>
  </li>
</ul>
```

menu-items.model.ts
```ts
export interface MenuItem {
  text: string;
}

export interface Menu {
  [key: string]: MenuItem;
}
```

Other (Snippets):
```ts
// app.component.ts
import { MenuService } from './menu-items/menu-items.service';
export class AppComponent {
  constructor(public menuService: MenuService) {}
}

// menu-items.service.ts
import { Menu, MenuItem } from './menu-items.model';
public menu: Menu = {};
// See model (above).
```

## 🔥 Exception or Error
<pre><code>
Identifier 'text' is not defined. 'V' does not contain such a member. (ng)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.0-rc.0
Node: 10.22.1
OS: win32 x64

Angular: 11.0.0-rc.0    
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.0-rc.0
@angular-devkit/build-angular   0.1100.0-rc.0
@angular-devkit/core            11.0.0-rc.0
@angular-devkit/schematics      11.0.0-rc.0
@schematics/angular             11.0.0-rc.0
@schematics/update              0.1100.0-rc.0
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

VS Code:

```text
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

**Anything else relevant?**

Also see: https://github.com/angular/vscode-ng-language-service/issues/946

**Comment by infacto** [comment]
@ranma42 @kyliau @AndrewKushnir CC (https://github.com/angular/angular/pull/37447)

**Comment by JoostK** [comment]
This is a bug in the language service as reported in #21224. The change in #37447 is not at fault, given that building still works as before.
