### ISSUE TITLE
ANGULAR 9: Timpicker AM/PM is not being translated locale 'de' with with ngx-bootstrap

### ISSUE THREAD

**Issue by UdayAppam** [angular/angular#39531]
When I worked with Angular 7 and ngx-bootstrap 5.4 version Timepicker locale being working as expected, Please refer below screenshot.
![image](https://user-images.githubusercontent.com/10434967/97825652-525f5500-1ce5-11eb-9fac-c2f2018161f1.png)

After upgrading the angular 9, locale is not working.(**Ngx-Bootstrap 6.1.0**)
![image](https://user-images.githubusercontent.com/10434967/97825701-70c55080-1ce5-11eb-869e-7e16255f601d.png)

Using  ` registerLocaleData(localeDE, "de");` is from common module.
  locale in angular 9.x [de.ts](https://github.com/angular/angular/blob/9.1.x/packages/common/locales/de.ts).
Locale in angular 7.x  [de.ts](https://github.com/angular/angular/blob/7.1.2/packages/common/locales/de.ts).

After comparing both versions got to know that AM/PM translated labels are missed.
Attaching the basic demo from Stackblitz to reproduce the issue.
Could you please check and help me to fix this.
[Angular 7 and ngx-BS 5.4](https://stackblitz.com/edit/ngx-bootstrap-etv8hf?file=app%2Fapp.module.ts)

[Angular 9 and ngx-BS 6.1.0](https://stackblitz.com/edit/ngx-bootstrap-vjan8b?file=app%2Fapp.module.ts)

**Comment by petebacondarwin** [comment]
This issue is also here https://github.com/valor-software/ngx-bootstrap/issues/5975

**Comment by JoostK** [comment]
The CLDR data for Germany has changed in [version 33.1](http://cldr.unicode.org/index/downloads/cldr-33-1), and is being discussed in [CLDR-10789](https://unicode-org.atlassian.net/browse/CLDR-10789).

**Comment by petebacondarwin** [comment]
Yes, see https://github.com/angular/angular/commit/c77faf566e01e76c7f3488265a84d3029d5cf8cc#diff-953934962fd5a4ff2ae5199b647632c3afd9875bf0aeeac6cc65b55974b4839aR21.

Closing since the Angular locales are generated directly from the CLDR and so this is not actionable by the Angular project.

As a workaround, you could modify the DE locale data manually when you load it in your project.
