### ISSUE TITLE
Reactive Forms guide could be more precise on HTML5 native validators

### ISSUE THREAD

**Issue by lukasmatta** [angular/angular#39549]
In the [Reactive Forms guide](https://angular.io/guide/reactive-forms), a user is encouraged to use native HTML5 attributes for validation such as `required`, `minlength` or `maxlength`. However, the default behavior of Angular reactive form is that it adds `novalidate` attribute to the form, which prevents native validators from functioning. 

To prevent misunderstanding, I would suggest adding information, that in order for HTML5 validators to work properly, one needs to add `ngNativeValidate` directive to the form.

**Comment by iRealNirmal** [comment]
I agree
We can add  section information regarding default behaviour of novalidate and how one can use directive ngNativeValidate.
But I would prefer it to be added in form validation section
[https://angular.io/guide/form-validation#validating-form-input](https://angular.io/guide/form-validation#validating-form-input)

**Comment by dylhunn** [comment]
Looks good, I will amend the docs as described.

**Comment by iRealNirmal** [comment]
This ticket can be closed now.
