### ISSUE TITLE
Dynamic Component not insert into shadowDOM

### ISSUE THREAD

**Issue by mhartington** [angular/angular#39556]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/10x

### Is this a regression?

Unsure. 

### Description

 
When rendering a dynamic component via `ComponentFactoryResolver` and `ViewContainerRef.createComponent`, if the ViewContainerRef is a web component with ShadowDom, the component is never rendered into the DOM. This was brought to our attention through https://github.com/ionic-team/ionic-framework/issues/22421

## 🔬 Minimal Reproduction

https://github.com/mhartington/ng-wc-component-factory-issue

## 🔥 Exception or Error

No exception or error is thrown

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.2.0
Node: 14.11.0
OS: darwin x64

Angular: 10.2.1
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.0.8
@angular-devkit/schematics      10.0.8
@angular/cli                    10.2.0
@schematics/angular             10.0.8
@schematics/update              0.1002.0
rxjs                            6.5.5
typescript                      3.9.7
</code></pre>

**Anything else relevant?**

It's worth noting that in the example, we have 

```
<ion-content> <! -- web component -->
  <button (click)="add()">Add</button>
  <div #target></div>
</ion-content>
```

If the `#target` is changed to a `ng-template` or the `ion-content` is removed, the issue does not happen.

**Comment by jelbourn** [comment]
Just to clarify- you're expecting the dynamically created content to be rendered within the shadow root's light DOM?

**Comment by mhartington** [comment]
Technically, yes. The internals of the component define a slot in the shadowRoot

```
<host>
  <shadow-root>
    <!-- default slot, render to light dom -->
    <slot></slot>
  </shadow-root>
</host>
```

So when the component is consumed 

```
<comp-a>
  <div>Content gets composed in the default slot, but will render in light dom</div>
</comp-a>
```


The dom tree will be 

```
<comp-a>
  #shadow-root
  <slot></slot>

<!-- light dom -->
  <div>Content gets composed in the default slot, but will render in light dom</div>
</comp-a>
```

So they dynamic component should just appear in the light DOM as it does with a regular div. 
I hope I explained this well 😄

**Comment by crisbeto** [comment]
#39599 should resolve it. For what it's worth, this has nothing to do with shadow DOM, but it breaks because you're injecting the `ViewContainerRef` from a node that's at the root of a component. Another way to work around it until the fix lands is to wrap the `#testShadow` element in a `div`.

**Comment by mhartington** [comment]
Thanks for the information @crisbeto!
