### ISSUE TITLE
Router broken after update to alpha 36 from alpha 35

### ISSUE THREAD

**Issue by debanjanbasu** [angular/angular#3955]
EXCEPTION: Error during instantiation of function (_platformStrategy, href) {! (function (router) { -> Router -> function (_platformStrategy, href) {).
angular2.dev.js:22746 ORIGINAL EXCEPTION: TypeError: Rx.Subject is not a function
angular2.dev.js:22746 ORIGINAL STACKTRACE:
angular2.dev.js:22746 TypeError: Rx.Subject is not a function
    at new EventEmitter (angular2.dev.js:23257)
    at new <anonymous> (location.js:34)
    at execute.reflect.factory (angular2.dev.js:8904)
    at Injector.execute._proto._instantiate (angular2.dev.js:27887)
    at Injector.execute._proto._new (angular2.dev.js:27824)
    at InjectorDynamicStrategy.execute.injector.getObjByKeyId (angular2.dev.js:27738)
    at Injector.execute._proto._getByKeyDefault (angular2.dev.js:28012)
    at Injector.execute._proto._getByKey (angular2.dev.js:27966)
    at Injector.execute._proto._getByDependency (angular2.dev.js:27954)
    at Injector.execute._proto._instantiate (angular2.dev.js:27853)
angular2.dev.js:22746 ERROR CONTEXT:
angular2.dev.js:22746 _Context {element: inventman-app, componentElement: null, injector: Injector}

I did make certain changes as routerInjectables is no longer a part of the router.d.ts

Please correct me on how to make the required changes for version 36

**Comment by debanjanbasu** [comment]
And yes I've set the base href in the html.

**Comment by kweheliye** [comment]
I'm getting same error. Also I  renamed (routerInjectables => ROUTER_BINDINGS)

**Comment by debanjanbasu** [comment]
Yet it doesn't seem to work. I doubt there might be something that we are missing. I tried to even change the location strategy in vain.

**Comment by TiagoBraga39** [comment]
Check if anything helps https://github.com/angular/angular/issues/3935

**Comment by debanjanbasu** [comment]
Nope... It still did not fix the error. Is this something related to RxJS as "TypeError: Rx.Subject is not a function" might be the cause of the error?

**Comment by TiagoBraga39** [comment]
Just a quick reminder: Did you change the router injectables and directives names?
Now they are: ROUTER_BINDINGS and ROUTER_DIRECTIVES.

Are you including an 3rd party RxJS? Now the HTTP module includes that on its own.

**Comment by debanjanbasu** [comment]
1. I am not including the HTTP module, as I am depending on the es6 standard fetch for HTTP calls.
2. Yes I've modified routerInjectables to ROUTER_BINDINGS
3. Do we need http module to make the router work?
4. The standard RxJS is in use no 3rd party library imported/used.

**Comment by debanjanbasu** [comment]
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Inventman v1.0.1. Real-Time smart inventory Management and Prediction</title>
    <meta name="description" content="Real-Time smart inventory Management and Prediction">
    <meta name="author" content="Debanjan Basu">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/custom.css">
</head>

<body>
    <inventman-app>Loading...</inventman-app>
    
    <script src="bower_components/traceur-runtime/traceur-runtime.min.js"></script>
    <script src="jsts/lib/system@0.16.11.js"></script>
    <script src="jsts/lib/angular2.dev.js"></script>
    <script src="jsts/lib/router.dev.js"></script>
    <script>
    'use strict';
    System.import('./jsts/components/app');
    </script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.js"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
</body>

</html>


This is my index.html and only a few JS libraries imported.

**Comment by TiagoBraga39** [comment]
Answers:
1. I actually really like the NG HTTP module.
2. Same with routerDirectives?
3 and 4. We don't.

Rx.Subject is not a function? Dig onto Rx.Subject. Is it undefined?
If not, when you use Rx.Subject, are you using any callback function after? 
Can you provide your code when you use Rx.Subject? It's hard this way.

**Comment by debanjanbasu** [comment]
I am avoiding the NG HTTP module as it is non-standard. The standard es6 fetch API gives more flexibility and is already integrated in most of the evergreen browsers, i.e. no extra download of http.js. You should give it a try. Not only does it perform better, but is the defined standard and future proof. This is the main reason angular2 team took out the HTTP module from the core into a separate js.

Yes I've modified routerDirectives to ROUTER_DIRECTIVES.

The Rx.Subject() is not a code that I've typed. It's on line 23257 of the latest angular2.dev.js
this._subject = new Rx.Subject();

**Comment by ericmdantas** [comment]
@debanjanbasu try ```angular2.js``` instead of ```angular2.dev.js```.

**Comment by debanjanbasu** [comment]
Well with angular2.js it is giving me another form of error.

My index.html file looks like this with angular2.js
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Inventman v1.0.1. Real-Time smart inventory Management and Prediction</title>
    <meta name="description" content="Real-Time smart inventory Management and Prediction">
    <meta name="author" content="Debanjan Basu">
    <!-- <base href="/"> -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/custom.css">
</head>

<body>
    <inventman-app>Loading...</inventman-app>
    <!--Load AngularJS-->
    <script src="bower_components/traceur-runtime/traceur-runtime.min.js"></script>
    <script src="jsts/lib/system@0.16.11.js"></script>
    <script src="jsts/lib/angular2.dev.js"></script>
    <script src="jsts/lib/router.dev.js"></script>
    <script>
    'use strict';
    System.import('./jsts/components/app');
    </script>
    <!-- Jquery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.js"></script>
    <!--Bootstrap-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
    <!-- D3 graphing library -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
</body>

</html>
```

and the error encountered now is:
```
GET https://registry.jspm.io/jsts/components/app.js 404 (Not Found)i @ es6-module-loader@0.16.6.src.js:2612$__Object$defineProperty.value @ es6-module-loader@0.16.6.src.js:2787n @ es6-module-loader@0.16.6.src.js:377t @ es6-module-loader@0.16.6.src.js:365$__Object$defineProperty.value @ es6-module-loader@0.16.6.src.js:2786$__global.upgradeSystemLoader.e.fetch @ system@0.16.11.src.js:739$__global.upgradeSystemLoader.e.fetch @ system@0.16.11.src.js:1806$__global.upgradeSystemLoader.e.fetch @ system@0.16.11.src.js:1921(anonymous function) @ es6-module-loader@0.16.6.src.js:1525D @ es6-module-loader@0.16.6.src.js:1183I @ es6-module-loader@0.16.6.src.js:1142s.7.O.when @ es6-module-loader@0.16.6.src.js:930s.7.w.run @ es6-module-loader@0.16.6.src.js:821s.3.e._drain @ es6-module-loader@0.16.6.src.js:97s.3.e.drain @ es6-module-loader@0.16.6.src.js:62t @ es6-module-loader@0.16.6.src.js:268
es6-module-loader@0.16.6.src.js:140 Potentially unhandled rejection [3] Error loading "jsts/components/app" at https://registry.jspm.io/jsts/components/app.js
Not Found: https://registry.jspm.io/jsts/components/app.js (WARNING: non-Error used)````

So basically it is searching the jspm.io cdn and not the local directory. I have wondered about this error earlier too.

**Comment by Zyzle** [comment]
> So basically it is searching the jspm.io cdn and not the local directory.

I think this is related to using an outdated version of Systemjs #3602

**Comment by kweheliye** [comment]
@Zyzle  Thanks, alpha.36 router is working for me

**Comment by debanjanbasu** [comment]
@Zyzle Thanks a ton. Finally your guide explained me how to use the latest systemJS. The earlier angular versions could not use them. They should've mentioned in the changelog that is one of the breaking changes. Finally it is working again.
