### ISSUE TITLE
ngcc deep import warnings for generated types

### ISSUE THREAD

**Issue by klemenoslaj** [angular/angular#39552]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler-cli

### Is this a regression?

Probably not a regression.

### Description

We have two repositories, both full of Angular libraries.
Both repositories have generated typings in the root folder called `generated` which is ignored by git.
Libraries from one repository depend on libraries of another (one direction only).

What happens is that once we install certain library, that library expects `generated` path with typings inside.
This actually works perfectly fine, but ngcc throws warning like:

```
WARNING in Entry point ‘library/name’ contains deep imports into ‘absolute-path/generated/globalTypes.d.ts’. This is probably not a problem, but may cause the compilation of entry points to be out of order
```

Additionally we use TS Paths in order for ngcc to recognize the folder in the first place:

```
      "generated/*": [
        "generated/*"
      ],
```

I know it's possible to silence the warning with the snippet bellow, but we would have to repeat the entry for each and every library we produce.

```js
// ngcc.config.js
module.exports = {
  packages: {
    'library/name': {
      ignorableDeepImportMatchers: [
        /generated\//,
      ]
    },
  },
};
```

Another workaround would be to release `ngcc.config.js` with each library, looking like:

```js
module.exports = {
  ignorableDeepImportMatchers: [/generated\//]
};
```

## 🔬 Minimal Reproduction

This would take a massive effort to reproduce. I will attempt on doing so if we cannot proceed verbally only.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.2.0
Node: 12.18.2
OS: darwin x64

Angular: 10.2.0
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.2.0
@angular-devkit/schematics      10.2.0
@angular/cdk                    10.2.6
@angular/flex-layout            10.0.0-beta.32
@angular/material               10.2.6
@angular/pwa                    0.1002.0
@schematics/angular             10.2.0
@schematics/update              0.1002.0
ng-packagr                      10.1.2
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by JoostK** [comment]
Hi @klemenoslaj,

There's a couple of things you can do to silence the warning. The easiest would probably be to ship an `ngcc.config.json` file with the libraries itself:

```js
module.exports = {
  ignorableDeepImportMatchers: [
    /generated\//,
  ],
};
```

This avoids the need for a project-level config of all package names. And actually I notice now that you amended this into the issue description as well.

Alternatively, you could extend the project-level config file to build the config file dynamically, as it's just a JS file that will be executed when ngcc loads it.

IMO ngcc is already offering the necessary tools here and no further action is needed. Feel free to continue the discussion below; I'll close this for now.

**Comment by klemenoslaj** [comment]
Yes, I discovered that I can ship the `ngcc.config.json` with the libraries and adjusted the issue, sorry for that.
For some reason I did not think of adjusting the config dynamically 🤦‍♂️ That will work pretty well I guess.

I am only left with the concern of this multi repo setup with typings being a bit too exotic and Angular CLI might accidentally stop supporting it 🤔 That's a different story tho.

Thanks for your suggestions!

**Comment by petebacondarwin** [comment]
> I am only left with the concern of this multi repo setup with typings being a bit too exotic and Angular CLI might accidentally stop supporting it 🤔 That's a different story tho.

I am concerned about this too. It is always better if you can ensure that you have no deep imports into libraries...

**Comment by klemenoslaj** [comment]
Well technically it is not a library nor is it intended to behave like one. Just a folder with bunch of `.d.ts` files, which are imported like `import { MyType } from 'generated/someTypes';`.
`ngcc` sees the `paths` in tsconfig and apparently confuses it with a library.

What is exotic in my opinion is having the installed library typings depend on typings within workspace that is consuming the library itself (these things are hard to explain :D).
