### ISSUE TITLE
Support safe navigation operator when using string literal to access object properties in templates

### ISSUE THREAD

**Issue by bampakoa** [angular/angular#39565]
# 🐞 bug report

### Affected Package

 N/A

### Is this a regression?

 N/A

### Description

I am accessing an object property using string literal notation such as `{{user.info[propName]}}` where `propName` is filled automatically from a `*ngFor` directive. Sometimes, the `user` object does not have an `info` property filled in so I am trying to use the safe navigation operator as `{{user.info?[propName]}}`

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-nrmgtw?file=src/app/app.component.html

## 🔥 Exception or Error
<pre>

Template parse errors:
Parser Error: Conditional expression user.info?[propName] requires all 3 expressions at the end of the expression [ {{user.info?[propName]}} ] in /~/src/app/app.component.html@6:4 ("
<div *ngFor="let user of users">
<p *ngFor="let propName of props">
[ERROR ->]{{user.info?[propName]}}
</p>
</div>"): /~/src/app/app.component.html@6:4
</pre>

## 🌍  Your Environment

**Angular Version:**
<pre>

Angular CLI: 10.1.2
Node: 12.16.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1001.2 (cli-only)
@angular-devkit/core         10.1.2 (cli-only)
@angular-devkit/schematics   10.1.2 (cli-only)
@schematics/angular          10.1.2 (cli-only)
@schematics/update           0.1001.2 (cli-only)
</pre>

**Anything else relevant?**
I would ❤️ to work on that issue if it is something that could be fixed by an external contributor without sacrificing the time of the Angular team 😃

**Comment by JoostK** [comment]
There is an open feature request for aligning with the optional chaining spec in #34385. Let's continue tracking it there, as I don't think there is a bug here (it's just not supported template expression syntax).

FYI: there is currently ongoing work to the parser to support the language service better, so it may not be the best time to change the parser to support this syntax (which would also require rework of AST nodes, which would quickly touch _a lot_ of compiler code and probably come with breaking changes of some sort.)
