### ISSUE TITLE
Broken Link on i18n page

### ISSUE THREAD

**Issue by anurag-bug** [angular/angular#39563]
# 📚 Docs or angular.io bug report

### Description

 Broken link on https://angular.io/guide/i18n
https://angular.io/generated/live-examples/i18n/stackblitz.html

### What's the affected URL?**
 https://angular.io/guide/i18n

### Reproduction Steps**

Go to this line
To explore the sample app with French translations used in this guide, see the live example / download example.

### Expected vs Actual Behavior**

Link should be working

## 📷Screenshot

![image](https://user-images.githubusercontent.com/29235137/98108702-73c96800-1ec2-11eb-8135-7ba02a98dc44.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Browser info

Not browser specific

**Comment by petebacondarwin** [comment]
Continuing the investigation to this issue at #41838.
