### ISSUE TITLE
Clarification for documentation (Interceptors)

### ISSUE THREAD

**Issue by bagatka** [angular/angular#39578]
# 📚 Docs or angular.io bug report

### Description

There is an example in documentation how to make AuthInterceptor. There's a step that helps to clone the request and replace the original headers with cloned headers, updated with the authorization. AuthToken was received with a help of AuthService. The method getAuthorizationToken() seems like never return null, even if there's no token yet. My own service returns null if user is not authorizated (there's no token in local storage). That's why I got a mistake: "Cannot read property 'length' of null". It was hard to find out the problem, so may be you can add a comment in documentation that authToken can't be null or just add null check?

### What's the affected URL?**
https://angular.io/guide/http#setting-default-headers

## 🔥 Exception or Error
<pre><code>
core.js:4352 ERROR TypeError: Cannot read property 'length' of null
    at HttpHeaders.applyUpdate (http.js:235)
    at http.js:207
    at Array.forEach (<anonymous>)
    at HttpHeaders.init (http.js:207)
    at HttpHeaders.forEach (http.js:270)
    at Observable._subscribe (http.js:1580)
    at Observable._trySubscribe (Observable.js:42)
    at Observable.subscribe (Observable.js:28)
    at innerSubscribe (innerSubscribe.js:67)
    at MergeMapSubscriber._innerSub (mergeMap.js:57)

</code></pre>

### Anything else relevant?
Maybe it's obvious, but not for me :) Thank you!

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
