### ISSUE TITLE
Query string parameters are not available via the RouteParams instance.

### ISSUE THREAD

**Issue by peter-svintsitskyi** [angular/angular#3957]
When user visits URL like the http://example.com/path/part?queryParam=value, there is no access to the "queryParam" via RouteParams in the component that is configured to match the "/path/part" route.

When the RootRouter class calls to the navigate method in its constructor, it passes in as a parameter only the path part of a URL discarding all query string parameters.

**Comment by btford** [comment]
You can get ahold of `queryParam` with `<RouteParams>params.get('queryParam')`.

If this isn't working, please open a new issue that includes a reproduction showing the expected vs. actual behavior. Thanks!

**Comment by peter-svintsitskyi** [comment]
It doesn't work after page refresh. This is part of the RootRouter::constructor()
```
this.navigate(location.path());
```
Thanks for closing!

**Comment by btford** [comment]
Ah, I misunderstood.

Yes, I see the issue now.

**Comment by user414** [comment]
This is still not working for me in alpha 48 if I have a route like

 { path: "/:foo",      as: "Home",      component: Home },

and a url like 

http://www.example.com/index.html?foo=bar

I still cannot read the foo param with <RouteParams>params.get('foo') I get "index.html" instead of "bar". However if I change to 

 { path: "/*wildcard",      as: "Home",      component: Home },

I get the correct result. Not sure if this is the same bug, a new bug or just misunderstanding on my part.

**Comment by user414** [comment]
@btford This is still not working in beta1 as well as 
https://github.com/angular/angular/issues/4089
the reloading of parameters on refresh is still not working in beta1 for me as well. Maybe we should reopen?

**Comment by talmog** [comment]
+1

**Comment by mofirouz** [comment]
I'm on Beta.13 and this is still an issue. I have the following URL structure and I'm using HashLocationStrategy:

`const Route(path: '/:owner/:name/players', component: PlayerManagementComponent, name: 'PlayerManagement')`

When I use a `[routerLink`] it works fine. However when I refresh the page, I get the following error:
```Route generator for 'owner' was not included in parameters passed.```

Please re-open and address this issue.

**Comment by novabyte** [comment]
+1 does not work for me on BETA 13 either.

**Comment by mofirouz** [comment]
Just a quick update. The problem that I was facing was different to the one mentioned in this issue. The problem was that the urlParams were available under certain circumstances. After further investigation, I found that it was indeed a piece of bad code (my own) that was causing this problem. I'm not affected by this issue.

**Comment by matthewdenobrega** [comment]
@btford  This does not work for me on beta 15:

GET http://localhost:8081/learn/cart/voucher?v=1234 (this will be a deep link from an email)

    ngAfterContentInit(): void {
        console.log(this.routeParams)
        this.voucherCode = this.routeParams.get('v')
        console.log('Voucher code: ' + this.voucherCode)
    }

Log (notice params is an empty object): 
RouteParams {params: Object} params: Object__proto__: Object__proto__: Object
cartVoucherComponent.ts:69 Voucher code: null

I can use window.location.search but this should be supported by the framework.

**Comment by dietergeerts** [comment]
I still have a similar issue: I get route params from the Router as I need one of them to add to a request header. This works fine when navigating through the application, but when I reload a page, The router state is just for route '/', and not the one I want to get to.....

**Comment by osazemeu** [comment]
Am currently encountering similar issue @dietergeerts explained.

**Comment by Msnow90** [comment]
I have a work around, concerning preserving the parameters in your URL route only for @angular/router version 3.0.2. I realized that with @angular/router version 4.0.0 this hack sadly no longer works as the routing module will throw an error if it can't resolve the url  - which it still doesn't recognize parameters or queries >;( . 

Basically as long as you configured your server properly, on the app.component's load capture the URL in the constructor, you can implement the life cycle method AfterContentInit(), and properly redirect using the Router object's navigate method. This is obviously terribly inefficient and frustrating, especially if you have multiple routes with parameters...you'll end up writing your own custom routing table code.

**Comment by lostation** [comment]
Yep params are not recoverable... "ç!è§('é !!!!
So I'm facing this routing issue after "accidental" page refresh...
Any changes or improvements ? ...

**Comment by JA-AmbosImmo** [comment]
This still doesn't work with @angular/router 4.4.6. 
Any news?

**Comment by janega** [comment]
I have something similar to this issue. When I reload I cannot get the route Params, they are undefined or NaN.

my route:
```
 path: 'mytools/Manage Access',
    component: AdminComponent,
    children: [
      {
        path: 'tenants',
        component: TenantsComponent,
        children: [
          { path: ':id/:displayName', component: DetailComponent }
        ]
      },
```
in component ngOnInit():
```
  this.route.params
        .subscribe(params => {
          const id = params['id'];
          const name = params['name'];

          console.log(id);
          console.log(name);
        })
```
I got undefined for both and my URL has both param in it. Happens on refresh of page F5.

**Comment by janega** [comment]
@btford wondering why this is closed, if it is still an issue for many? Is there a workaround or fix? Thanks.

**Comment by LironHazan** [comment]
I lost so much time on it and eventually faced the following who made it clear:
https://stackoverflow.com/questions/42947133/parent-components-gets-empty-params-from-activatedroute

**Comment by rukkumani** [comment]
is there any solution for this issue

**Comment by Splash34** [comment]
+1 should someone open a new issue?
