### ISSUE TITLE
ElementInjector hierarchy fails to find Parent

### ISSUE THREAD

**Issue by jdt3969** [angular/angular#39581]
# 🐞 bug report

### Affected Package
I don't know

### Is this a regression?
I don't know

### Description

Using pieces of the full stackblitz below:

Create a provider and a consumer component:
```ts
@Component({
  selector: "app-provider",
  template: `<ng-content></ng-content>`,
  providers: [TestService]
})
export class ProviderComponent {}

@Component({
  selector: "app-consumer",
  template: `<p>Value: {{ testService.value }}</p>`
})
export class ConsumerComponent {
  constructor(public testService: TestService) {}
}
```

Create an indirection component:
```ts
@Component({
  selector: "app-outer",
  template: `<ng-content></ng-content>`
})
export class OuterComponent {}
```

And app works they way you expect:
```ts
@Component({
  selector: "my-app",
  template: `
    <app-outer>
      <app-provider>
        <app-consumer></app-consumer>
      </app-provider>
    </app-outer>
  `
})
export class AppComponent {}
```

But change the indirection component to be:
```ts
@Component({
  selector: "app-outer",
  template: `
    <app-provider>
      <ng-content></ng-content>
    </app-provider>
  `
})
export class OuterComponent {}
```

and the app component to be
```ts
@Component({
  selector: "my-app",
  template: `
    <app-outer>
      <app-consumer></app-consumer>
    </app-outer>
  `
})
export class AppComponent {}
```

and the provider can no longer be found even though the element structure remained the same.

I would expect the level of component abstraction not to affect the ElementInjector hierarchy

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-10-base-template-cgkcmt

## 🔥 Exception or Error
<pre><code>
Error: R3InjectorError(AppModule)[TestService -> TestService -> TestService]:
NullInjectorError: No provider for TestService!
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
v10.0.2
</code></pre>

**Comment by jelbourn** [comment]
The `providers` API specifically makes content available to a component's _content_ (your first example). There's another API, `viewProviders`, for making things available to your component's _view_ (second example). https://angular.io/api/core/Component#viewProviders

**Comment by jdt3969** [comment]
@jelbourn Thanks for the response. Changing this to `viewProviders` doesn't fix it though. I'm still a bit confused because `app-provider` in all cases above remains the same with `<ng-content></ng-content>` as it's template which means everything should be content and not view right?
