### ISSUE TITLE
fix(router 1.x) navigation broken when using ngLink directive

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#3959]
Trying to navigate by clicking links generated by the ngLink directive fail to display the content. The ngLink is generating a relative path instead of an absolute path, which causes the instruction to not be found. If you use an href with an absolute path, navigation works correctly. The routerLink directive generates an absolute path. Link to an example gist below.

https://gist.github.com/brandonroberts/3e956355202a5d6047d1

**Comment by btford** [comment]
Thanks! I'll spend some time investigating next week. In the meantime, can you see if this is still an issue with alpha-37? There were many fixes in that release, which may have addressed this problem.

**Comment by brandonroberts** [comment]
I tested it with the new build and it does work correctly now. Thanks!
