### ISSUE TITLE
Cannot use "map" on a type of Array<T> | QueryList<T> because of signature mismatches

### ISSUE THREAD

**Issue by lazarljubenovic** [angular/angular#39602]
# 🐞 bug report

### Affected Package

 
The issue is caused by package `@angular/core`.

### Is this a regression?

 No.

### Description

 
I have a function that I wish to work with both `QueryList` and `Array`. Both types have the `map` method, but their types are not inter-compatible:

```text
Error:(7, 12) TS2349: This expression is not callable.
  Each member of the union type '(<U>(callbackfn: (value: any, index: number, array: any[]) => U, thisArg?: any) => U[]) | (<U>(fn: (item: any, index: number, array: any[]) => U) => U[])' has signatures, but none of those signatures are compatible with each other.
```

## 🔬 Minimal Reproduction

 Trivial to try out and quickly reproduce in any project you have open by writing this:

```ts
import { QueryList } from '@angular/core'
function test (x: Array<any> | QueryList<any>) {
  return x.map(x => x)
}
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.5
Node: 14.3.0
OS: linux x64

Angular: 10.0.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.5
@angular-devkit/build-angular     0.1000.5
@angular-devkit/build-optimizer   0.1000.5
@angular-devkit/build-webpack     0.1000.5
@angular-devkit/core              10.0.5
@angular-devkit/schematics        10.0.5
@angular/cli                      10.0.5
@ngtools/webpack                  10.0.5
@schematics/angular               10.0.5
@schematics/update                0.1000.5
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0

</code></pre>

**Anything else relevant?** No.

**Comment by JoostK** [comment]
Relates to #38446.

**Comment by JeanMeche** [comment]
I wasn't able to reproduce. 

[Playground](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&allowUnreachableCode=true&allowUnusedLabels=true&noUnusedLocals=true&noUnusedParameters=true&noImplicitOverride=true&noFallthroughCasesInSwitch=true&noPropertyAccessFromIndexSignature=true&exactOptionalPropertyTypes=true&useUnknownInCatchVariables=true#code/JYWwDg9gTgLgBAbzgRQK4FMoE8AywDO8AvnAGZQQhwDkAAgIYB2A5qgDb1QD0AxtOtQBQg0qkY8YwCIzgx0hABQAPAFxwAglCj0sAHiZYAfHAA+KDNjyF9jIwEpEguM7hR0MVFBlKAdCHpgynAAvMZKdoJEwnKKjOgA7uaYuAQwCnZ2QA)

**Comment by JeanMeche** [comment]
@JoostK can you close this ? 😊
