### ISSUE TITLE
Support injecting @Attributes()

### ISSUE THREAD

**Issue by mhevery** [angular/angular#3961]
```
class MyClass {
  constructor(@Attributes() atts: Map<string, string>)
}
```

**Comment by pkozlowski-opensource** [comment]
Sounds exactly like https://github.com/angular/angular/issues/1818 -probably can close one as a duplicate of another

**Comment by tbosch** [comment]
With the new compiler refactoring this will be easy to implement. Please wait until then...

**Comment by mhevery** [comment]
Closing as dup of #1818
