### ISSUE TITLE
Improve usability when AIO build process detects broken links

### ISSUE THREAD

**Issue by aikidave** [angular/angular#39610]
# 📚 Docs or angular.io bug report

### Description

When building AIO, if there are any broken links, the links show up, along with a stack trace. The stack trace is unnecessary to writers (we can't do anything about it). It would be more user-friendly if we just saw the list of broken links. Can we put the stack trace behind a flag or something so we only see it if we explicitly ask for it?

### What's the affected URL?**

AIO

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by petebacondarwin** [comment]
Unfortunately the bit that displays the stack trace is the `dgeni` tool itself, so we will need to change that and publish a new version....

**Comment by petebacondarwin** [comment]
Strictly, we can't close this until we update the dependency in AIO for dgeni
