### ISSUE TITLE
Order of custom ControlValueAccessors

### ISSUE THREAD

**Issue by Airblader** [angular/angular#39625]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/forms

### Description

When there are multiple matching ControlValueAccessors for a component, [Angular guarantees](https://github.com/angular/angular/blob/master/packages/forms/src/directives/shared.ts#L253) custom > built-in > default, but there is no guaranteed way of ordering custom ControlValueAccessors.

This is important if you're using an external UI library and need to use a custom ControlValueAccessor on it. This would currently depend on the order of the injected array of ControlValueAccessors, and I'm not sure Angular even makes any guarantees about that based on injector hierarchy(?). 

It would therefore be nice if there was either a way to enforce a specific CVA is used.

**Comment by Airblader** [comment]
@AndrewKushnir I understand this was an automated process, but closing issues with an explanation of "just implement it as a library" is a bit of a smack in the face for issues that ask Angular to do something so that external libraries can be implemented.

**Comment by mgechev** [comment]
Hey @Airblader, considering to host the feature as a third-party extension is just a suggestion applicable to features that make sense. Do you have a proposal how to make the comment more helpful and practical?
