### ISSUE TITLE
bug(ng-template): ng-template in multiple instances of component always get last instance state data

### ISSUE THREAD

**Issue by KevinZhang19870314** [angular/angular#39622]
Reproduction
Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-ivy-rpwg8j?file=src/app/app.component.html

Steps to reproduce:

1. Click button 'Set app-test-1 data';
2. Click button 'Set app-test-2 data';
3. Click text 'name3' (Click name3 first, NOT name2);
4. Click text 'name2'.

Expected Behavior
When click text 'name2', console will output 'this.name = app-test-1';

Actual Behavior
When click text 'name2', console will output 'this.name = app-test-2';

Environment
Angular: 7.2.16
Browser(s): Chrome 86.0.4240.183 x64
Operating System (e.g. Windows, macOS, Ubuntu): windows 10

**Comment by basherr** [comment]
@kevhuang Seems like `this` isn't referring to the class scoped **name**. I tried to listen `ngOnChanges` on `test.component.ts` to detect the change for **name** but it didn't. The issue is quite complicated as you can see in the following example, the **name** variable changes inside **ng-template** but does not reflect in the other parts of the component.

[Stalkblitz Modified](https://stackblitz.com/edit/angular-ivy-5cyrzd?file=src/app/app.component.html   )

**Comment by kevhuang** [comment]
> @kevhuang Seems like `this` isn't referring to the class scoped **name**.

@basherr Looks like you tagged the wrong person.

**Comment by basherr** [comment]
> > @kevhuang Seems like `this` isn't referring to the class scoped **name**.
> 
> @basherr Looks like you tagged the wrong person.

Oops! Sorry for that.

**Comment by KevinZhang19870314** [comment]
@basherr Thanks! 
Anyway, finally I found a workaround for this: pass in two reference of columns with same content to each app-test component, then resolve my issue. 

Maybe this cause by the same ColumnDef reference pass into two instance of table component, so each instance of test component will use the same ng-template instace, which will defer render the content inner ng-template with latest instance. 

[https://stackblitz.com/edit/angular-ng-template-wr?file=src/app/app.component.html](https://stackblitz.com/edit/angular-ng-template-wr?file=src/app/app.component.html)

**Comment by jelbourn** [comment]
This is working as intended; you're using the same `ng-template` via the bound `column` property in both tables, which gets updated when you push the second button. You would need to use two separate column defs.

**Comment by KevinZhang19870314** [comment]
> This is working as intended; you're using the same `ng-template` via the bound `column` property in both tables, which gets updated when you push the second button. You would need to use two separate column defs.

Thank you for your explaination. As you can see above, it actually works as expected when I use two column defs. But I still can't understand why this changes will impact the app-test instance, you can see there are two instance of app-test in app.component.html template, columns just as a @Input for app-test component, why it will imapct other property (like name) in app-test component?
