### ISSUE TITLE
ngFor over functions causes type error with Ivy

### ISSUE THREAD

**Issue by ersimont** [angular/angular#39634]
# 🐞 bug report

### Affected Package

@angular/common, maybe? It's a compile-time error using nothing special except `*ngFor`

### Is this a regression?

This appeared as I was upgrading from Angular 9.1.0, though @JoostK below (https://github.com/angular/angular/issues/39634#issuecomment-725341454) was able to reproduce it on the latest 9.0.x and 9.1.x.

### Description

When looping over an array of functions using *ngFor, a strange typing error occurs when calling that function in the template. For example in this template it gives an error like the following:

```
export class AppComponent  {
  functions = [() => 1, () => 2];
}

<p *ngFor="let fn of functions">
	{{ fn() }}
</p>

Property 'fn' does not exist on type '() => number'.
```

You'll see that it somehow is trying to find `fn` on the function itself? It works fine if you turn off Ivy.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-vttvch?file=src/app/app.component.html

## 🔥 Exception or Error
<pre><code>Property '__' does not exist on type '___'.</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.2.0
Node: 12.18.1
OS: win32 x64

Angular: 10.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.2.0
@angular-devkit/schematics      10.2.0
@angular/cdk                    10.2.7
@angular/cli                    10.2.0
@angular/material               10.2.7
@schematics/angular             10.2.0
@schematics/update              0.1002.0
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**
Must be using ivy

**Comment by zero-1** [comment]
Not really relevant.... but you should try to not call methods from the template....

Here is a fix though...

functions = [
    (() => 1)(), 
    (() => 2)()
    ];

<p *ngFor="let fn of functions">
	{{ fn }}
</p>

**Comment by JoostK** [comment]
Confirmed as broken, but does not appear to be a (recent) regression. Latest 9.0.x and 9.1.x also produce the same error.

**Comment by ersimont** [comment]
Oh that's a surprise - sorry for the misinformation. This appeared as I was upgrading from 9.1 to 10! I'll update the description.

**Comment by AleksanderBodurri** [comment]
> Not really relevant.... but you should try to not call methods from the template....
> 
> Here is a fix though...
> 
> functions = [
> (() => 1)(),
> (() => 2)()
> ];
> 
> {{ fn }}

@zero-1 
There's nothing wrong with calling methods from the template as long as the time complexity of the method is reasonable. Any method with linear time complexity or better that is run from the template is **usually** fine.

@ersimont 

Here are some possible work arounds for now until this is fixed,

Workaround 1.

```ts
export class AppComponent  {
  functions = [() => 1, () => 2];
}
```

```html
<p *ngFor="let fn of functions">
	{{ fn.call(this) }}
</p>
```

Workaround 2.

```ts
export class AppComponent  {
  functions = [() => 1, () => 2];

  eval(method: Function): number {
    return method();
  }
}
```

```html
<p *ngFor="let fn of functions">
	{{ eval(fn) }}
</p>
```

**Comment by ersimont** [comment]
@AleksanderBodurri Nice ideas. Thank you, that workaround unblocks me for now!

**Comment by AleksanderBodurri** [comment]
@ersimont 

No worries.

Another possible workaround that I missed,
```ts
<p *ngFor="let fn of functions">
	{{ (fn)() }}
</p>
```
