### ISSUE TITLE
Problems with Mobile Safari

### ISSUE THREAD

**Issue by GlauberF** [angular/angular#39648]
# 🐞 bug report

### Affected Package
@angular/*

### Description

I am having problems that in other browsers I don't have, I will put some of the errors in Exception and here I will also put the configuration of my .browserslistrc file and the device settings.

Brand | Apple
-- | --
Family | iPhone
Model | iPhone

OPERATING SYSTEM
Name | iOS
-- | --
Version | 13.7

BROWSER
name | Mobile Safari
-- | --
version | 13.1.2

.browserslistrc
> 0.5%
last 2 versions
Firefox ESR
Chrome 41 # Support for Googlebot
not dead
not IE 9-11 # For IE 9-11 support, remove 'not'.

## 🔥 Exception or Error

1 -  https://sentry.io/share/issue/6d3c5510d6704a25b9e3db59d393327e/
<pre><code>
null is not an object (evaluating 'Object.keys(t)')
{snip} is.updateValueAndValidity(e)}patchValue(t,e={}){Object.keys(t).forEach(n=>{this.controls[n]&&this.controls[n].patchValue(t[n],{onlySelf:!0,e {snip}
</code></pre>

2 - https://sentry.io/share/issue/fca6ab487cfc4d10a05a7297311140e3/
<pre><code>
null is not an object (evaluating 'e.cpf_cnpj')
{snip}  0:u.length)&&(O.edf_autorizados=O.edf_autorizados.map(e=>e.cpf_cnpj)),null===(m=null===(d=null==E?void 0:E.ven_id)||void 0===d?void 0:d._pe {snip}
    query ${E.a.graphqlList}(
            $limit: Int!, 
            $page: Int!, 
            $orderBy: [String!],
            $edf_status: String,
</code></pre>

3 - https://sentry.io/share/issue/2de6f60d486747258e57c12cc752ec2d/
<pre><code>
 null is not an object (evaluating 't._index=e+1')
{snip} l&&a.a.check(this.model).isArray&&(this.model.map((t,e)=>(t._index=e+1,t)),this._changeDetectorRef.markForCheck())}_dataManagementStrength() {snip}
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.2.0
Node: 12.18.1
OS: linux x64

Angular: 10.2.0
... animations, cli, common, compiler, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1002.0
@angular-devkit/build-angular      0.1002.0
@angular-devkit/build-optimizer    0.1000.8
@angular-devkit/core               10.2.0
@angular-devkit/schematics         10.2.0
@angular/cdk                       10.2.5
@angular/compiler-cli              10.2.1
@angular/flex-layout               10.0.0-beta.32
@angular/language-service          10.2.1
@angular/material                  10.2.5
@angular/material-moment-adapter   10.2.5
@nguniversal/builders              10.1.0
@nguniversal/express-engine        10.1.0
@schematics/angular                10.2.0
@schematics/update                 0.1002.0
rxjs                               6.6.3
typescript                         3.9.7

</code></pre>

**Comment by AndrewKushnir** [comment]
Hi @GlauberF, we've reviewed this ticket and it looks like it's missing a repro. Without a repro we are unable to perform any investigation. I'm closing this ticket for now, feel free to reopen once a minimal repro is available.
