### ISSUE TITLE
dgeni should output Type Annotation for all var, const (currently, some missed)

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#3965]
The following var and const don't output a varType in dgeni:
```
directives	CORE_DIRECTIVES
forms	FORM_BINDINGS
forms	FORM_DIRECTIVES
http	HTTP_BINDINGS
http	JSONP_BINDINGS
pipes	DEFAULT_PIPES
pipes	DEFAULT_PIPES_TOKEN
router	CanActivate
router	RouteConfig
router	APP_BASE_HREF
router	ROUTE_DATA
router	ROUTER_BINDINGS
router	ROUTER_DIRECTIVES
test	afterEach
test	expect
test	ELEMENT_PROBE_BINDINGS
```

**Comment by btford** [comment]
I suspect that this is because of how I read the type information from the AST. I'll take a closer look when I get a chance.

**Comment by IgorMinar** [comment]
Is this related to dgeni's doc generation or d.ts generation? if it's the latter then we don't need to fix it because the whole d.ts generation will soon be replaced with a different process once #4550 lands

**Comment by naomiblack** [comment]
moving out to alpha-42.

**Comment by naomiblack** [comment]
@petebacondarwin any chance this might be a quick fix for you?

**Comment by IgorMinar** [comment]
we don't care about this any more since we now publish d.ts files in the non-bundled form.

I expect that we'll completely remove our dgeni based d.ts bundle generation soonish.
