### ISSUE TITLE
angular upgrade website doesnt have the material upgrade command

### ISSUE THREAD

**Issue by crh225** [angular/angular#39663]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...
If I go here https://update.angular.io/?v=10.0-11.0 and tick I use angular material I dont see the upgrade command for material to angular 11

## 🔬 Minimal Reproduction
 go here https://update.angular.io/?v=10.0-11.0 and tick I use angular material
### What's the affected URL?**
 https://angular.io/...
https://update.angular.io/?v=10.0-11.0
### Reproduction Steps**

If I go here https://update.angular.io/?v=10.0-11.0 and tick I use angular material I dont see the upgrade command for material to angular 11
### Expected vs Actual Behavior**

a command that says ng upgrade @angular/material

## 📷Screenshot

![image](https://user-images.githubusercontent.com/19475195/99009259-540ef100-250d-11eb-9406-ef67c5b18800.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by crh225** [comment]
@mgechev if I go to the upgrade site, I still dont see it. I checked and saw the PR is merged, but the app is not updated.

**Comment by mgechev** [comment]
Deployment in progress
<img width="490" alt="Screen Shot 2020-11-13 at 9 24 52 PM" src="https://user-images.githubusercontent.com/455023/99112662-af68de00-25f6-11eb-8be3-2ee3b7d84c93.png">
