### ISSUE TITLE
Compilation breaks after update to 11 `Duplicate identifier`

### ISSUE THREAD

**Issue by joaodforce** [angular/angular#39660]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core or the Angular Compiler

### Is this a regression?

 Yes, building apps with my library worked normally at least on Angular 9

### Description

Basically what happened is that I updated my own Angular Library to Angular 11, by itself and using the library's built in test project all worked normally. The issue Started happening when I updated the client app that uses this library, I had to update it to Angular 11 as well, all went ok, but after I tried to run it, it started spitting those `Duplicated Identifier` errors.

At first I thought the issue was my project, that maybe I screwed something up on the update process, so I created a clean 
new project, just imported my library and did a minimum setup to get it running and right away the same errors appeared.

I pasted the snippets of the errors happening bellow.

## 🔬 Minimal Reproduction

https://github.com/joaodforce/angular-11-test
I made this simple project that install my Angular Library and imports its module, Simply `npm install` it and `npm start` it, the issue will appear.
Considering the Lib Itself builds and runs fine on its own I'm pretty confident the issue is related with the compiler on the client Application.

There will also be some errors related to some `strings.json` files, but those are unrelated to the matter at hand.

## 🔥 Exception or Error
<pre><code>

static ɵfac: ɵngcc0.ɵɵFactoryDef<TableBuiderComponent, never>;
              ~~~~
node_modules/fre-base-components/lib/dynamic-base-builder/dynamic-base-builder.component.d.ts:37:12 - error TS2300: Duplicate identifier 'ɵfac'.

37     static ɵfac: ɵngcc0.ɵɵFactoryDef<BaseBuiderComponent, never>;39m
              ~~~~
node_modules/fre-base-components/lib/dynamic-alter-builder/dynamic-alter-builder.component.d.ts:32:12 - error TS2300: Duplicate identifier 'ɵfac'.

32     static ɵfac: ɵngcc0.ɵɵFactoryDef<AlterBuilderComponent, never>;
              ~~~~
node_modules/fre-base-components/lib/dynamic-nav-builder/dynamic-nav-builder.component.d.ts:18:12 - error TS2300: Duplicate identifier 'ɵfac'.

18     static ɵfac: ɵngcc0.ɵɵFactoryDef<NavigationBuilderComponent, never>;
              ~~~~
node_modules/fre-base-components/lib/dynamic-login-builder/dynamic-login-builder.component.d.ts:21:12 - error TS2300: Duplicate identifier 'ɵfac'.

21     static ɵfac: ɵngcc0.ɵɵFactoryDef<DynamicLoginBuilderComponent, never>;
              ~~~~
node_modules/fre-base-components/lib/dynamic-report-builder/dynamic-report-builder.component.d.ts:26:12 - error TS2300: Duplicate identifier 'ɵfac'.

26     static ɵfac: ɵngcc0.ɵɵFactoryDef<ReportBuilderComponent, never>;
</code></pre>


## 🌍  Your Environment

**Angular Version:**
<pre><code>
<!-- run `ng version` and paste output below -->
<!-- ✍️-->
Angular CLI: 11.0.0
Node: 12.16.1
OS: darwin x64

Angular: 11.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, material-moment-adapter, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.0
@angular-devkit/build-angular   0.1100.0
@angular-devkit/core            11.0.0
@angular-devkit/schematics      11.0.0
@angular/flex-layout            10.0.0-beta.32
@schematics/angular             11.0.0
@schematics/update              0.1100.0
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**
<!-- ✍️Is this a browser specific issue? If so, please specify the browser and version. -->

<!-- ✍️Do any of these matter: operating system, IDE, package manager, HTTP server, ...? If so, please mention it below. -->
I did some examining on the errors, and noticed something.
After I did `NPM Install` The typing files of the library are normal, matching the ones stored on its repository. BUT after I did `npm start` the files were changed. Bellow its the before and after the Angular Compiler touched it.

Before `npm start`:
<img width="970" alt="Captura de Tela 2020-11-12 às 16 26 35" src="https://user-images.githubusercontent.com/9410916/98992938-8bc96900-250c-11eb-8059-d892786a2499.png">

After `npm start`:
<img width="964" alt="Captura de Tela 2020-11-12 às 16 28 11" src="https://user-images.githubusercontent.com/9410916/98992952-8ec45980-250c-11eb-985b-035f9345a871.png">

Also the closest thing I found that could be related to my issue is this https://github.com/angular/angular/issues/35095 but it is relatively old so it might be an issue that was reintroduced.

**Comment by JoostK** [comment]
This indicates that you published Ivy-compiled AOT code to your repo (`git+https://git.fre.com.br/FREInformatica/angular-fre-base-components-dist.git#v0.7.1`), together with the ViewEngine metadata (pre-Ivy) that seems to be leftover in the Git directory. This causes ngcc (the compatibility compiler for VE libraries) to compile the library for Ivy once again.

I should note that publishing Ivy-compiled AOT code is not supported, as the generated code is not guaranteed to be stable. This may be okay for your use-case if you only use it with a single version. It is generally recommended to ship a library in VE format still, and then let ngcc do the work to make it compatible for Ivy according to the version that is installed in the application where the library is used.
