### ISSUE TITLE
Implement ng.listInvisibleButActiveLightDoms()

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#3967]
As a follow-up to https://github.com/angular/angular/issues/3877 implement API for getting a list of live light DOMs that are not visible on the UI because their projection points are inactive. These views are instantiated and they participate in change detection but because they are not visible in many cases they simply slow down the application.

API:

```javascript
ng.listInvisibleButActiveLightDoms();
```

It would return a list where each element is the path (xpath?) to an invisible light DOM.

/cc @mhevery @tbosch

**Comment by mhevery** [comment]
Will not implement.
