### ISSUE TITLE
Angular v10/v11 are missing from releases dropdown

### ISSUE THREAD

**Issue by KVikram** [angular/angular#39688]
# 📚 Docs or angular.io bug report

### Description

 
Angular release v10 is not visible to be able to select in the releases/version dropdown at the left bottom corner of the angular.io website for document referencing.
Also another observation is when we visit https://v10.angular.io/docs then v11 is missing from the dropdown.

### What's the affected URL?**
 https://angular.io/guide/setup-local

### Reproduction Steps**

Go to Angular.io site and click on left bottom release version dropdown, v10 is missing from the list.
### Expected vs Actual Behavior**

All  released stable angular versions should be available to select for documentation reference.

## 📷Screenshot

When we visit https://angular.io/guide/setup-local - v10 is missing
![image](https://user-images.githubusercontent.com/8777907/99144818-fd1a3080-2660-11eb-9b71-ae67224d2a54.png)

When we visit https://v10.angular.io/docs - v11 is missing
![image](https://user-images.githubusercontent.com/8777907/99144962-8aaa5000-2662-11eb-838e-55385c8f7abc.png)

## 🔥 Exception or Error
<pre><code>

N/A
</code></pre>

## 🌍  Your Environment
Chrome Version 86.0.4240.183 (Official Build) (64-bit)

### Browser info

Not browser specific, happening in every major browser.

**Comment by petebacondarwin** [comment]
I can confirm that the lack of v10 in the dropdown for angular.io is a valid bug.

> Also another observation is when we visit https://v10.angular.io/docs then v11 is missing from the dropdown.

This is expected, none of the "archived" sites show future major versions. See the v9, v8, v7 etc sites.

**Comment by KVikram** [comment]
Thanks @petebacondarwin for the confirmation. Should I change the issue title to reflect the proper issue?

**Comment by petebacondarwin** [comment]
I think it is fine. I'll put together a PR to fix the primary issue now.
We just need to update this file: https://github.com/angular/angular/blob/7ce825011bd2259f671bd2fd595a8428a0785668/aio/content/navigation.json#L1055-L1083

**Comment by petebacondarwin** [comment]
Actually, I decided that hand-coding this for each major is going to be an ongoing problem.
So I changed the doc-gen to compute the list automatically from the tags in GitHub in #39689
