### ISSUE TITLE
@angular/forms ngModel bug

### ISSUE THREAD

**Issue by DbrmnPhrh** [angular/angular#39687]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

 @angular/forms 9, 10, 11 have this issue.  I didn't check another versions of @angular/forms

### Description

Properties order:
[(ngModel)]="test"
(ngModelChange)="testChange()"
emits right value

Properties order:
(ngModelChange)="testChange()"
[(ngModel)]="test"
emits **WRONG (previous)** value

![2020-11-14_135717](https://user-images.githubusercontent.com/15796191/99144082-9c9cea80-2684-11eb-8d51-598a3ac90895.jpg)

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ngmodel-bug

## 🔥 Exception or Error
<pre><code>

No exeptions
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

@angular/forms 9.0.0
@angular/forms 10.0.0
@angular/forms 11.0.0

</code></pre>

**Anything else relevant?**

**Comment by ankit5577** [comment]
put [(ngModel)]="test" before (ngModelChange)="testChange()"
it works fine.
in your case you are executing testChange() before the model can get latest value.

**Comment by ankit5577** [comment]
put [(ngModel)]="test" before (ngModelChange)="testChange()"
it works fine.
in your case you are executing testChange() before "test" gets latest value.

**Comment by DbrmnPhrh** [comment]
It is not obvious and there are no errors in the console(

**Comment by DbrmnPhrh** [comment]
> @DbrmnPhrh put `[(ngModel)]="test"` before `(ngModelChange)="testChange()"`
> it works fine.
> in your case you are executing `testChange()` before `test` gets latest value.

It is not obvious and there are no errors in the console(

**Comment by Pashozator** [comment]
@DbrmnPhrh why there should be any error or warning?

**Comment by lazarljubenovic** [comment]
When you bind multiple times to a single output, it's obvious that one of the methods must run before the other. It's an anti-pattern to do it anyway because developers don't expect the order of bindings to matter. So just don't do it and write the bindings properly.

**Comment by AndrewKushnir** [comment]
Closing this ticket based on the discussion in this thread (there are no action items for the framework).
