### ISSUE TITLE
Improve encapsulation be adding declarations array in @Component metadata

### ISSUE THREAD

**Issue by ywarezk** [angular/angular#39695]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
 Improve component encapsulation while removing cluttering of `NgModule`

### Describe the solution you'd like
 Inside the `@Component` metadata, add the key: `declarations`, that key should accept an array of components, similar to the api used in `@NgModule`.  

```typescript
@Component({
    selector: 'nz-header',
    template: `
        <header>
            <nz-nav></nz-nav>
        </header>
    `,
    declarations: [NavComponent]
})
export class HeaderComponent { ... }
```

### Describe alternatives you've considered
 Yes, Feature module and dynamic components

### Long description

One of the programming concepts that guides us as developers is encapsulation.  
The ability to expose what we need to expose as public, and to hide the rest as private.  
Consider the following components, module.  

Our module `AppModule` contains the following components:

- `HeaderComponent`
  - `NavComponent`
- `FooterComponent`

`HeaderComponent` is placing the `NavComponent`, and the `NavComponent` will be used **only** in the `HeaderComponent`

The `NavComponent` is a component that should only be used in the `HeaderComponent` it's like a private implementation of the `HeaderComponent`.  
Encapsulation rules should not expose `NavComponent` to the other components inside our module.  
So the `FooterComponent` should not be able to place the `NavComponent` since it's private to the `HeaderComponent`.  

Currently to declare the structure above our `AppModule` would look like this:

```typescript
@NgModule({
    declarations: [HeaderComponent, NavComponent, FooterComponent]
})
export class AppModule {}
```

this configuration will allow both the `HeaderComponent` and the `FooterComponent` to place the `NavComponent`.  
In my opinion this breaks encapsulation rules and clutters the `NgModule` with a lot of components which should be private.  
The ideal would be that we can declare the module like this:

```typescript
@NgModule({
    declarations: [HeaderComponent, FooterComponent]
})
export class AppModule {}
```

And declare the `HeaderComponent` like this:

```typescript
@Component({
    selector: 'nz-header',
    template: `
        <header>
            <nz-nav></nz-nav>
        </header>
    `,
    declarations: [NavComponent]
})
export class HeaderComponent { ... }
```

And of course not allow the `FooterComponent` to add the selector of the `NavComponent`.

I can arrange a folder for the `HeaderComponent` and arrange in that same folder all the private components that header is using.  

The result will be:
- cleaner `NgModule` with smaller array of components
- Better encapsulation in the components
- Better communication to the team regarding what components they can use and what is hidden

**Comment by petebacondarwin** [comment]
This has definitely been discussed before, but I can't find a duplicate issue. One of the goals of Ivy was to remove the need for NgModule. So it is definitely on the radar.

**Comment by ywarezk** [comment]
> This has definitely been discussed before, but I can't find a duplicate issue. One of the goals of Ivy was to remove the need for NgModule. So it is definitely on the radar.

I know that with Ivy we can directly create a component, without the need to include the `NgModule` of that component.  

The behaviour I'm describing is a bit different here, than Ivy creating a detached (from module) `NavComponent`.  
Note that regarding DI  the `NavComponent` should still be able to access the `NgModule` providers just like it would if it was declared in the `declarations` array of the module.  
While creating a detached component with Ivy will not allow that component to access it's module providers.

**Comment by jnizet** [comment]
In case you don't know (or some other reader doesn't), note that you *can* already encapsulate by simply introducing a header NgModule, which declares HaderComponent and NavComponent, but only exports HeaderComponent:

```
@NgModule({
  imports: [CommonModule],
  declarations: [HeaderComponent, NavComponent],
  exports: [HeaderComponent]
})
class HeaderModule {}

@NgModule({
  imports: [BrowserModule, HeaderModule],
  declarations: [AppComponent],
  // ...
})
class AppModule {}
```

The NavComponent won't be usable anywhere other than in the components of the HeaderModule (i.e. HeaderComponent in this example).

**Comment by ywarezk** [comment]
> In case you don't know (or some other reader doesn't), note that you _can_ already encapsulate by simply introducing a header NgModule, which declares HaderComponent and NavComponent, but only exports HeaderComponent:
> 
> ```
> @NgModule({
>   imports: [CommonModule],
>   declarations: [HeaderComponent, NavComponent],
>   exports: [HeaderComponent]
> })
> class HeaderModule {}
> 
> @NgModule({
>   imports: [BrowserModule, HeaderModule],
>   declarations: [AppComponent],
>   // ...
> })
> class AppModule {}
> ```
> 
> The NavComponent won't be usable anywhere other than in the components of the HeaderModule (i.e. HeaderComponent in this example).

You are right.

But on the same level I can say: 

Why should we create `Promise.prototype.catch` function if we can use `Promise.prototype.then` and pass null as the first argument, and I could probably think of infinite number of example including examples in angular.

Sometimes an improvement of the api is required, it makes the code cleaner, it forces the developers to think about encapsulation on the component level. I'm sure that a lot of developers will not use the example you placed, either they are not thinking about encapsulation on the component level, or the fact that creating another file with all the code you placed is a bit tedious.

**Comment by jnizet** [comment]
Agreed. I just wanted to make sure you (and others) hadn't missed this possibility.

**Comment by JoostK** [comment]
> This has definitely been discussed before, but I can't find a duplicate issue. One of the goals of Ivy was to remove the need for NgModule. So it is definitely on the radar.

I think I've just found it; #33507. Closing this as a duplicate, I've mentioned this issue number in a comment though.
