### ISSUE TITLE
[Docs] missing documentation for UrlMatcher

### ISSUE THREAD

**Issue by geromegrignon** [angular/angular#39697]
# 📚 Docs or angular.io bug report

### Description

The [UrlMatcher API](https://angular.io/api/router/UrlMatcher) is not currently included in the [Router](https://angular.io/guide/router) part of the documentation on https://angular.io/docs.

@aikidave

**Comment by Pashozator** [comment]
@geromegrignon What do you exactly mean?

**Comment by geromegrignon** [comment]
As it isn't included in any guide of the official docs, it means that it only exists for people exploring the codebase or relying on unofficial guide (by the way i never saw it included in any unofficial guide i know of).

So it's kind of hidden feature (being discoverable as a search result on the official docs isn't enough as you never search for something you aren't aware of).

**Comment by iRealNirmal** [comment]
@geromegrignon do you want below document to be updated ?
[https://angular.io/api/router/Route#pathMatch](https://angular.io/api/router/Route#pathMatch)

**Comment by geromegrignon** [comment]
Hello @iRealNirmal,
This document is fine.

The problem is explained in my previous message.

**Comment by aikidave** [comment]
Fixed with #42138
