### ISSUE TITLE
Manually loading the App

### ISSUE THREAD

**Issue by johnsky95** [angular/angular#39709]
While the app work entirely good, when I try to load it dynamically from a javascript code nothing happens.

`document.body.insertAdjacentHTML(
            'beforeend',
            `       <app-root></app-root>
                    <script type="text/javascript" src="http://localhost:8887/runtime-es2015.js" type="module"></script>
                    <script type="text/javascript" src="http://localhost:8887/runtime-es5.js" nomodule defer></script>
                    <script type="text/javascript" src="http://localhost:8887/polyfills-es5.js" nomod></script>
                    <script type="text/javascript" src="http://localhost:8887/polyfills-es2015.js"></script>
                    <script type="text/javascript" src="http://localhost:8887/main-es2015.js" type="module"></script>
                    <script type="text/javascript" src="http://localhost:8887/main-es5.js" nomodule defer></script>
`
        );`

Resources are accesible and downloaded, but never executed.

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
