### ISSUE TITLE
ng 11: patchValue, valueChanges & async pipe

### ISSUE THREAD

**Issue by sysmat** [angular/angular#39702]
# 🐞 bug report
I don't know if this is a bug or feature.

* I have AbstractControl for the input field on which I want to listen to valueChanges with async pipe. 
* It works fine if user write to the input field async pipe work
* If I programatacly patch value then async pipe doesn't work
* code ts:

```typescript
searchForm: FormGroup;
...
ngOnInit(): void {
    this.initSearchForm();

    this.navigateBack = this.route.snapshot.queryParams.back;
    if (this.navigateBack && this.navigateBack === 'true') {
      this.orgCtrl.patchValue(null);
      // this.orgCtrl.setValue(this.orgStorage.getSearchKey(), { emitEvent: false, onlySelf: true });
      this.orgCtrl.setValue(this.orgStorage.getSearchKey());
      this.result$ = of(this.orgStorage.getSearchResult());
    }
  }

get orgCtrl(): AbstractControl { return this.searchForm.get('org'); }

private initSearchForm(): void {
    this.searchForm = this.formBuilder.group({ org: '' });
    this.result$ = this.orgCtrl.valueChanges
      .pipe(
        filter(v => v.length >= 3),
        tap(v => console.log(v)),
        switchMap(v => this.search(v))
      );
  }
```
* HTML code:

```html
<div *ngIf="orgCtrl?.valueChanges | async">
    <p *ngFor="let r of result$ | async">
        {{r.name}}
    </p>
</div>

```
### Affected Package

* @angular/forms
* @angular/core

### Is this a regression?

I don't know it is a fresh projcet with ng 11

### Description

* When pectValue with a reactive form async pipe doesn't detected valueChanges.

## 🔥 Exception or Error
There is no error in the browser dev console.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.1
Node: 12.6.0
OS: win32 x64

Angular: 11.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.1
@angular-devkit/build-angular   0.1100.1
@angular-devkit/core            11.0.1
@angular-devkit/schematics      11.0.1
@angular/cli                    11.0.1
@schematics/angular             11.0.1
@schematics/update              0.1100.1
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
I think that what you are saying is that `ctrl.patchValue()` does not trigger `valueChanges` to emit, yes?
Could you check that by subscribing directly to the `valueChanges` observable?

From looking at the `patchValue()` implementations in `FormGroup` and `FormControl` it looks like these functions always trigger a `valueChanges` emission, unless the options argument contains `{emitEvent: false}`.

Please could you put your sample code into a StackBlitz that we can run and debug?

**Comment by sysmat** [comment]
```typescript
this.orgCtrl.patchValue(this.orgStorage.getSearchKey(), { emitEvent: true, onlySelf: true });
this.orgCtrl.valueChanges.subscribe(v => console.log(v)); // nothing happens
```

**Comment by petebacondarwin** [comment]
Did you try subscribing before the call to `patchValue()`?

**Comment by sysmat** [comment]
on stackblitz.io not working connecting to dev-server takes for infinity

**Comment by sysmat** [comment]
@petebacondarwin If I subscribe before patchValue it works, thx.
But I still have a problem with my template `*ngIf="orgCtrl?.valueChanges | async"` it is not triggered

**Comment by petebacondarwin** [comment]
Here is a Stackblitz to get started: https://stackblitz.com/edit/angular-ivy-6jxkwu?devtoolsheight=33&file=src/app/app.component.ts

**Comment by sysmat** [comment]
The idea is not to subscribe in typescript but handle everything with async pipe

**Comment by petebacondarwin** [comment]
OK, so it appears to be a problem with timing. If you create the form in `ngOnInit()` but then do the `patchValue()` call in `ngAfterViewInit()` then it works:  https://stackblitz.com/edit/angular-ivy-6jxkwu?file=src%2Fapp%2Fapp.component.ts

**Comment by sysmat** [comment]
@petebacondarwin `ngAfterViewInit` it looks much better, but I get an error in the dev console of browser

`ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'null'. Current value: 'prule'.`

**Comment by sysmat** [comment]
Ok, I force detection with

```
private cd: ChangeDetectorRef
this.cd.detectChanges();
```

**Comment by sysmat** [comment]
@petebacondarwin thx for the help

**Comment by sysmat** [comment]
@petebacondarwin but if you click the button Test, the rendering-page should show 'xxx' but it is not. 
So this is really not a solution, even in my app when I have an input field after(ngAfterViewInit) user type something `valueChanges` is not triggered.

Is this a limit of angular framework or I'm doing something wrong.

Regards

**Comment by Totati** [comment]
Hi, we use a helper `valuesOf` function, that wraps the `AbstractControl` if we want to have an observable stream with the current value at subscription. In the template using just `ctrl.valueChnages | async` is a bit overkill, and most of the time can be replaced with a simple `ctrl.value`. If you want to pipe the `valueChanges`, then using `valuesOf` is even less code. [Example](https://stackblitz.com/edit/angular-ivy-rtqj9p?file=src/app/app.component.ts)

**Comment by alxhub** [comment]
I believe Angular is working as designed here, and the issue is that the timing between `valueChanges`, `patchValue`, and change detection is fundamentally brittle. As others have suggested, using `.value` directly instead of trying to capture `valueChanges` is far more likely to be successful and not run into such problems.
