### ISSUE TITLE
"Introduction to Angular animations" problems

### ISSUE THREAD

**Issue by tdkehoe** [angular/angular#39708]
# 📚 Docs or angular.io bug report

### Description

[Introduction to Angular animations](https://angular.io/guide/animations#animation-api-summary) has several problems. 

The code in ```open-close.component.html```

```html
<div [@openClose]="isOpen ? 'open' : 'closed'" class="open-close-container">
  <p>The box is now {{ isOpen ? 'Open' : 'Closed' }}!</p>
</div>
```

should be

```html
<button (click)="toggle()" [@openClose]="isOpen ? 'open' : 'closed'" class="open-close-container">
  <p>The box is now {{ isOpen ? 'Open' : 'Closed' }}!</p>
</button>
```

Without the ```(click)``` the function ```toggle()``` isn't called.

Another issue is that the tutorial starts by adding code to ```app.component.ts``` and then in the middle of the tutorial tells the learner to add code to ```open-close.component.ts```. All the code should go into ```app.component.ts```.

### What's the affected URL?**
https://angular.io/guide/animations#animation-api-summary

### Reproduction Steps**

Try to run the code provided in the tutorial.

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by iRealNirmal** [comment]
@AndrewKushnir do you agree with all this changes ? If yes I can create PR for this changes

**Comment by AndrewKushnir** [comment]
Hi @iRealNirmal, thanks for the comment.
> do you agree with all this changes ?

Yes, it looks like the `(click)` is missing (i.e. there is nothing in the guide that triggers an animation).

> If yes I can create PR for this changes

Thanks for the help, I've assigned this ticket to you. Please let us know if you have any questions and/or need help.
