### ISSUE TITLE
Reflection transformer rewrites WebWorker bootstrap

### ISSUE THREAD

**Issue by jteplitz602** [angular/angular#3971]
On the UI developers bootstrap a WebWorker application by calling
```Dart
import "package:angular2/web_workers/ui";
bootstrap("file.dart");
```

Currently the transformer will rewrite this to 
```Dart
import "package:angular2/web_workers/ui";
bootstrapStatic("file.dart");
```
Which will throw since bootstrapStatic isn't defined.

**Comment by yjbanov** [comment]
If there are no objections, I'd like to do this one. I needed to get this working for my DDC work anyway, might as well finish it.
