### ISSUE TITLE
dgeni: Typescript 1.6.0-beta incompatible with ng.Type generation in angular-alpha-36

### ISSUE THREAD

**Issue by bestander** [angular/angular#3972]
dgeni generates type in angular2.d.ts with
```js
  interface Type extends Function {
     new(args: any): any;
  }
```
Typescript 1.6.0 throws an error during compilation:  
```js
@Component({
    selector: 'audio-tile',
    properties: ['summaryInfo: summary-info'],
    events: ['tileEvent']
})
@View(<any>{ // TEMP
    template: <string>require('./audio-tile.html'),
    directives: [NgIf, NgClass],
    pipes: [SecsAsMmSsPipe]
})
export class AudioTile {
    constructor (resetPlaybackEventEmitter: ResetPlaybackEventEmitter,
                 resetExpansionEventEmitter: ResetExpansionEventEmitter) {
   }
}
```

```
ERROR in /Users/bestander/work/booktrack/mandrill/app/studio/audio/audio-tile/audio-tile.ts:9:1
Argument of type 'typeof AudioTile' is not assignable to parameter of type 'Type'.
```

If I manually replace what dgeni generated into (as in `modules/angular2/src/core/facade/lang.ts`)
```js
  interface Type extends Function {
     new(...args): any;
  }
```
Then it works fine.

**Comment by rolandjitsu** [comment]
:+1: I have the same issue.

**Comment by shoebox639** [comment]
I'm seeing the same thing with v1.5.3.

**Comment by Zyzle** [comment]
Just noticed, this and I'm having the same issue being reported by the Atom Typescript plugin. The gulp task I use to compile the project however doesn't complain

**Comment by LMFinney** [comment]
Same here.
I locally modified angular2.d.ts with this (using alpha 35 on Typescript 1.5.3):
    interface Type extends Function {
        new(...args: any[]): any;
    }

**Comment by bestander** [comment]
Looks like fixed in 37
