### ISSUE TITLE
Carousel not working as expected

### ISSUE THREAD

**Issue by DaleMFrancis** [angular/angular#39724]
In a properly working carousel, when images exceed the width of the viewport, they should drop off to the left or right of the viewport.  Left and right arrows bring different image into focus. 

But in my attempt, when images exceed the width of the viewport, the overflow images drop down the page to create a new row of images. 

Here is my code: 

                      
                    <div id="myCarousel" class="carousel slide" data-ride="carousel">
                         

                         <ol class="carousel-indicators">
                           <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                           <li data-target="#myCarousel" data-slide-to="1"></li>
                           <li data-target="#myCarousel" data-slide-to="2"></li>
                         </ol>
                       
                         
                         <div class="carousel-inner">
                           <div class="item active">
                              
                            
                            <img class="pics" src="assets/Monaco-and-Spirit.jpeg"> 
                            <img class="pics" src="assets/Monaco-and-Spirit2.jpeg"> 
                            <img class="pics" src="assets/Monaco-and-Spirit3.jpeg"> 
                         </div>

                         
                         

                         
                         <fa-icon [icon] = angleLeft></fa-icon> 
                         

                         <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                           
                           <i class="fas fa-icon"></i>
                           <span class="sr-only">Previous</span>
                         </a>
                         <a class="right carousel-control" href="#myCarousel" data-slide="next">
                           <span class="angles angleRight" alt="" width="40" height="40"></span>
                           <span class="sr-only">Next</span>
                         </a>
                    </div>

Can someone advise why this code isn't working properly?  Thank you.

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
