### ISSUE TITLE
Angular 9 and IE 10 Compatibility

### ISSUE THREAD

**Issue by jeyasekar** [angular/angular#39731]
Am using Angular 9 , My application works fine in IE11 .
My application not loading in IE10 and Getting below console error.

SCRIPT5007: **Object expected, vendor-es5.js (124818,7)**

I have 2 questions:

1. **Does Angular 9 will work in IE10?**
2. If so, Help me to fix the Issue .

Thanks

**Comment by criskrzysiu** [comment]
No, Angular does not support IUE 10.

https://angular.io/guide/browser-support

**Comment by destus90** [comment]
@criskrzysiu 
As I know the support for IE 9,10 was dropped since Angular 11. 
Angular 9 should support IE 9, 10 with no errors, due to https://v9.angular.io/guide/browser-support

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
