### ISSUE TITLE
docs: remove non deployment related sub-sections from deployment guide

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#39735]
# 📚 Docs or angular.io bug report

### Description

At the moment there are several topics in the deployment guide which are not related to [deployment](https://angular.io/guide/deployment) 

All the above sections and sub-section are non deployment related and are actually more "build"/"development"/"optimizations"  topics. 

I think most of the below mentioned sections should be moved under a dedicated "optimizations/performance" section maybe?

**[production optimizations](https://angular.io/guide/deployment#production-optimizations)**
[enable-runtime-production-mode](https://angular.io/guide/deployment#enable-runtime-production-mode)
[lazy-loading](https://angular.io/guide/deployment#lazy-loading)
[measure-performance](https://angular.io/guide/deployment#measure-performance)
[inspect-the-bundles](https://angular.io/guide/deployment#inspect-the-bundles)

I think most of the below mentioned sections should be moved under https://angular.io/guide/build

[the-base-tag](https://angular.io/guide/deployment#the-base-tag)

**[differential-loading](https://angular.io/guide/deployment#differential-loading)**
[differential-builds](https://angular.io/guide/deployment#differential-builds)
[configuring-differential-loading](https://angular.io/guide/deployment#configuring-differential-loading)

**[local-development-in-older-browsers](https://angular.io/guide/deployment#local-development-in-older-browsers)**
[configuring-serve-for-es5](https://angular.io/guide/deployment#configuring-serve-for-es5)
[configuring-the-test-command](https://angular.io/guide/deployment#configuring-the-test-command)
[configuring-the-e2e-command](https://angular.io/guide/deployment#configuring-the-e2e-command)

**Comment by santoshyadavdev** [comment]
Thank Alan, I will work on this.

**Comment by alan-agius4** [comment]
@santoshyadavdev let's wait for @aikidave input first!

**Comment by aikidave** [comment]
Thanks for this, @alan-agius4! Let me take a look at this in more detail before we start doing any major restructuring.

**Comment by JeanMeche** [comment]
I believe this issue is no longer releveant with AIO going into maintenance and the CLI having been rewritten on ADEV.
