### ISSUE TITLE
Issue with locale sv.ts where jan. feb.  '.' appears at the end 

### ISSUE THREAD

**Issue by Ckolhari5353** [angular/angular#39733]
There are '.' at the end ex 'jan.' in locale sv.ts  ['jan.', 'feb.', 'mars', 'apr.', 'maj', 'juni', 'juli', 'aug.', 'sep.', 'okt.', 'nov.', 'dec.'] is this intentional, one of our client raised it as a bug any suggestions?

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
