### ISSUE TITLE
Synk Vulnerability SNYK-JS-Y18N-1021887 transitively in @angular/localize

### ISSUE THREAD

**Issue by Ltchoc221** [angular/angular#39743]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please read https://angular.io/guide/security#report-issues on how to disclose security related issues.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Issue is not directly in angular code, so creating issue as opposed to following the link above.

***Problem:*** @angular/localize [v10.2.3](https://github.com/angular/angular/blob/10.2.3/packages/localize/package.json#L33) and [v9.1.12](https://github.com/angular/angular/blob/9.1.12/packages/localize/package.json#L37) both use [yargs@15.13.0](https://github.com/yargs/yargs/blob/v15.3.0/package.json#L31), which in turn uses y18n@^4.0.0.  y18n has the following Prototype Pollution [synk vulnerability](https://snyk.io/vuln/SNYK-JS-Y18N-1021887), with a remediation of upgrading y18n to v5..0.5 or higher.

[yargs@16.1.1](https://github.com/yargs/yargs/blob/v16.1.1/package.json#L52) upgrades to y18n@^5.0.5.  Is it possible to update the 9.x and 10.x lines of @angular/localize to use this higher version of yargs?

**Comment by gauravshah27** [comment]
I am hitting the same issue on my angular project. Any solution?

**Comment by petebacondarwin** [comment]
This sounds like a reasonable request. I will put together a PR today.
