### ISSUE TITLE
Angular CLI: ng update to 11 duplicates multi-line comments in app.module.ts

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#39752]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
@angular/cli

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
Angular CLI: ng update to 11 duplicates multi-line comments in app.module.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.2
Node: 14.15.0
OS: darwin x64

Angular: 11.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@angular/cli                    11.0.2
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment]
Hi @johnpapa, could you please provide a bit more information on this issue? It'd be helpful to look at the duplicated lines (and also at the original content) and also please let us know from which version you upgraded. Thank you.

**Comment by petebacondarwin** [comment]
Closing due to lack of response.
