### ISSUE TITLE
Mat Table one custom filter and global filter getting issue.

### ISSUE THREAD

**Issue by ayyappa12345** [angular/angular#39771]
i have a table with multiple columns, from that table i need single column filter and global filter, Can any one suggest me how to handle it for in a better way, when i am trying to create filters both are working fine independently, like if enter some thing in global filter filtering is working fine and then filtering in column filter then it doesn't care about global filter, filter is happening overrall data. sorry for my bad engilsh.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
