### ISSUE TITLE
Permit additional redirects after an absolute redirect

### ISSUE THREAD

**Issue by Seemspyo** [angular/angular#39770]
# 🐞 bug report

### Affected Package

 @angular/router

### Is this a regression?

 No, it's not

### Description

When router has `redirectTo` chain, redirection not working as expected.

## 🔬 Minimal Reproduction

[here is the repo](https://github.com/Seemspyo/ng-issue/tree/child-router)

## 🔥 Exception or Error
`app-routing.module.ts`
```ts
    { path: 'depth-test', children: [

        { path: '', redirectTo: '/depth-test/depth-1', pathMatch: 'full' },

        { path: 'depth-1', component: Depth1Component, children: [

            { path: '', redirectTo: '/depth-test/depth-1/child-depth-1', pathMatch: 'full' },
            { path: 'child-depth-1', component: Depth1childComponent }

        ] }

    ] }
```

when navigate like below
```ts
this.router.navigateByUrl('/depth-test');
```
angular redirect to `/depth-test/depth-1`, not `/depth-test/depth-1/child-depth-1` as expected. Neither `routerLink` nor `Router.navigate` working.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.1.7
Node: 14.12.0
OS: win32 x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cli                    10.1.7
@schematics/angular             10.1.7
@schematics/update              0.1001.7
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

**Comment by eneajaho** [comment]
I can confirm that this is not working, I also reproduced in Stackblitz, so you can better debug it.  Here's the [re-production](https://stackblitz.com/edit/redirecting-to-child-cmp?file=src/app/app.module.ts)

**Comment by ulrikwalter** [comment]
I think it's better to use relative links in this case. If path of parent/child changed (for example: 'parent' => 'newparent'), you don't need rewrite all redirects.

```ts
  {
    path: "parent",
    // component: ParentComponent,
    children: [
      {
        path: "",
        redirectTo: "child-1",
        pathMatch: "full"
      },
      {
        path: "child-1",
        component: Child1Component,
        children: [
          {
            path: "",
            redirectTo: "child-2",
            pathMatch: "full"
          },
          {
            path: "child-2",
            component: Child2Component
          }
        ]
      }
    ]
  }

```

**Comment by destus90** [comment]
@ulrikwalter 
Does changing absolute urls to relative ones rectify the issue?

**Comment by Seemspyo** [comment]
With relative link this case working fine in my environment(11.0.2).

**Comment by mojoaxel** [comment]
I can confirm that this is also an issue with `redirectToChildren: true` for nested routes in angular@13.3
