### ISSUE TITLE
[NPM] Support Typescript 4.1.2 on angular-cli

### ISSUE THREAD

**Issue by kevinLB** [angular/angular#39772]
Actually I upgraded this morning the typescript version (4.1.2 from 4.0.5).

I got this error :

`Error: The Angular Compiler requires TypeScript >=4.0.0 and <4.1.0 but 4.1.2 was found instead.`

I found the peerDependencie problem : 
https://github.com/angular/angular/blob/master/packages/compiler-cli/package.json

Is it possible to plan an upgrade ?

**Comment by alan-agius4** [comment]
This is currently in progress. 

Since https://github.com/angular/angular/pull/39571
