### ISSUE TITLE
Add template input variable to glossary

### ISSUE THREAD

**Issue by kapunahelewong** [angular/angular#39783]
# 📚 Docs or angular.io bug report

### Description

Currently, we do not have glossary entry for template input variable.

### What's the affected URL?**
Anywhere where template input variables are referenced in the docs.

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Anything else relevant?

It would be very helpful if we could link to a glossary definition whenever we mention template input variables.

**Comment by kapunahelewong** [comment]
Here's a helpful section that could serve as a reference: [Structural directives template input variables section](https://angular.io/guide/structural-directives#template-input-variable)

**Comment by rox117** [comment]
is this still open

**Comment by petebacondarwin** [comment]
yes

**Comment by andrewasche** [comment]
https://github.com/angular/angular/pull/41593
Attempted my first pull request for this issue

**Comment by sumitgsh** [comment]
Is it Still Open would love to work on this!!

**Comment by petebacondarwin** [comment]
@sumitgsh - there is a PR from @andrewasche that is about to be merged: https://github.com/angular/angular/pull/41632

**Comment by aikidave** [comment]
Closing this issue as `template input variable` is now in the glossary!
