### ISSUE TITLE
Extend docs for ng build

### ISSUE THREAD

**Issue by eLeontev** [angular/angular#39780]
I started to investigate possible prod build optimization and faced with lack of details in official documentation.

More interesting for me were **buildOptimizer** and **optimization**. Even if for the first one is can be guessed like it removes and reduce build size based on new AOT compiler results, but for the second one the description describes nothing.

![image](https://user-images.githubusercontent.com/15786916/99803750-00bf2300-2b4b-11eb-9ef4-ee263358279c.png)

I asked this request on gitHub instead of slack/stackoverflow questions since there I will receive subjective answers.

Here I hope to receive and objective answer about role of `optimization` flag or updating of the appropriate docs from the framework maintainers.

Link to the current docs: https://angular.io/cli/build

**Comment by destus90** [comment]
May be `optiomization` is related to https://angular.io/guide/workspace-config#optimization-and-source-map-configuration ?

**Comment by eLeontev** [comment]
@alan-agius4  thanks
