### ISSUE TITLE
Add microsyntax to the glossary

### ISSUE THREAD

**Issue by kapunahelewong** [angular/angular#39784]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
Any page that references microsyntax. For example, https://angular.io/guide/structural-directives and https://angular.io/guide/built-in-directives.

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by abadi003** [comment]
is this still open?

**Comment by kapunahelewong** [comment]
We decided to go with "shorthand". Because it has the same meaning in the context of programming as it does in standard English, we don't need to include it in the glossary. I should have closed this issue, but if you see any more examples of the term, please feel free to submit a PR and tag me. Thank you for reminding me, @abadi003!
