### ISSUE TITLE
showing 2 Month In Angular Material Date Picker (angular 2+)

### ISSUE THREAD

**Issue by AlirezaPhf** [angular/angular#39795]
it possible displaying 2 month in material date picker ?
like this:
![calendar](https://user-images.githubusercontent.com/48950088/99875353-22301580-2c04-11eb-83ee-4320b9184bcb.jpg)

directive write by fragaria has for angularJS.
https://github.com/fragaria/angular-daterangepicker.

pls help with angular 2+.
thnx.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
