### ISSUE TITLE
Polyfills / browser support confusion

### ISSUE THREAD

**Issue by andreaslarssen** [angular/angular#39793]
# 📚 Docs or angular.io bug report

### Description

A brand new Angular (10) installation comes with a `polyfills.ts` file saying: 
```
The current setup is for so-called "evergreen" browsers; the last versions of browsers that
automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),
Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.

Learn more in https://angular.io/guide/browser-support
```
It has *no* polyfills as default.

The `https://angular.io/guide/browser-support` link says:

| Browsers (Desktop & Mobile)                           | Polyfills Required
| -----------------------------------------------------------   |:------------------------:|
| Chrome, Firefox, Edge, Safari, Android, IE 11  | ES2015

So, the pollyfills.ts comment says that Angular (seemingly) out of the box, with no polyfills supports Safari >= 10, Chrome >= 55 (including Opera), Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile. While the documentation says you need the ES2015 polyfill to support Chrome, Firefox, Edge, Safari, Android, IE 11.

It also suggest polyfills: `ES7/array`, `ES2015` (which already is documented as *required* above) , `classList`, `Intl` and `Web Animations`.

Then, the `.browserslistrc` file says: 

```
not IE 11 # Angular supports IE 11 only as an opt-in. To opt-in, remove the 'not' prefix on this line.
```

I thought Browserslist only took care of css, but .browserslistrc says:

```
# This file is used by the build system to adjust CSS and JS output to support the specified browsers below.
```

...so apparently it also affect the JS output in some way.

Can someone shed a light on how this is all connected, and how Angular uses these tools behind the curtains? Both here, and in the documentation somewhere. If I missed it, please direct me. 

### What's the affected URL?**

https://angular.io/guide/browser-support#polyfill-libs

### Reproduction Steps**

`ng new myapp`

### Expected vs Actual Behavior**

?

**Comment by jelbourn** [comment]
@kyliau can someone from the tooling team confirm whether the aio guide and the comments in the polyfills and browserlist file all line up?
