### ISSUE TITLE
Issue in Router Navigate in Guards

### ISSUE THREAD

**Issue by GaneshSingaravelu** [angular/angular#39806]
Hi,

I am trying to redirect to the login page if the user doesn't log in. So I have implemented the guards for "canActivate" and try to redirect. But it is not working as I expected. It is not redirecting and goes an endless loop. Please do the needful.

**_Guards_**

```
import { Injectable } from '@angular/core';
import { CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot, UrlTree, Router } from '@angular/router';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class LoginGuard implements CanActivate {

   constructor(private storage: LocalStorageService, private router: Router) {    
   }

    canActivate(
    route: ActivatedRouteSnapshot,
    state: RouterStateSnapshot): Observable<boolean | UrlTree> | Promise<boolean | UrlTree> | boolean | UrlTree {
      let userInfo = JSON.parse(this.storage.retrieve('_userDetails'));
      if (userInfo && parseInt(userInfo.IsValidUser) === 1) {
        this.router.navigate(['stocky/commondashboard']);
        return false;
      }
      this.router.navigate(['/login']);
      return true;
  }  
}
```

**_routing.module.ts_**

```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { LoginGuard } from 'src/app/guards/login.guard';
import { LoginComponent } from './login/login.component';
import { UserComponent } from './user.component';

const UserRoutes: Routes = [ 
  {
    path: '', 
    component: UserComponent, 
    canActivate: [LoginGuard],
    children: [
      {path: 'login', component: LoginComponent},
    ]
    
  }, 
];

@NgModule({
  imports: [RouterModule.forChild(UserRoutes)],
  exports: [RouterModule]
})
export class UserRoutingModule { }

```
Thanks

**Comment by JeetChaudhari** [comment]
It seems it is working correctly. I did not test your code but it seems you are applying `LoginGuard` to `login` path, which would cause endless loop. login page should not be restricted by guard.

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
