### ISSUE TITLE
Use the Record utility type for key-value properties in documentation samples

### ISSUE THREAD

**Issue by bampakoa** [angular/angular#39804]
# 📚 Docs or angular.io bug report

### Description

 Hello all,

I have noticed some occurrences of key-value pairs in the aio documentation that use the form `{[key: string]: any}` or any of its variances. Do you think it should be beneficial to land a PR that changes them to use the, more readable, `Record` utility TypeScript type such as `Record<string, any>`?

### What's the affected URL?**
 Here is one of the pages that contains the key-value pair form: https://angular.io/guide/attribute-binding#binding-to-multiple-css-classes

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by abarghoud** [comment]
@jelbourn I would like to submit a PR regarding this feature request

**Comment by petebacondarwin** [comment]
Sure go for it @abarghoud! Be careful that the `Record` type prevents you from naming the `key` property, which is sometimes desirable.
