### ISSUE TITLE
better DEVELOPERS.md: how to write tests

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#3980]
Discussed in mtg last week w/ @mhevery , @IgorMinar , and @yjbanov 
It's hard for people to contribute to angular because there are several patterns for how to write tests, and it's unclear which is the best to emulate.
We'd like to document the best way for unit tests and end-to-end tests.

**Comment by wardbell** [comment]
FYI I'm working on a chapter for application testing for the Dev Guide.  Most of it would serve to guide developers in writing tests that explore Ng2 features or confirm bugs.

**Comment by vicb** [comment]
There is a guide on angular.io
