### ISSUE TITLE
Difference between ng build and ng build --prod

### ISSUE THREAD

**Issue by lukasmatta** [angular/angular#39812]
Hello,

I haven't found [in the docs](https://angular.io/cli/build) any information about the default behavior when we do not specify the configuration by using `--configuration` or `--prod` parameter. Is the first configuration stated in `configurations` in the `angular.json` file used? Or is the default configuration the `production` one?

As i don't know which configuration is used when we don't specify any, I am not sure if there is any difference between running `ng build` and `ng build --prod` considering that we have only `production` configuration specified in our `angular.json` file.

**Comment by Vandathron** [comment]
running ng build --prod or ng build --configuration=production sets up your build for production by replacing your environment.ts file with environment.prod.ts file. 
ng build doesn't do this and still assumes you're not building for production hence use your environment.ts file, no bundling, no AOT enabled, source map will be generated e.t.c

**Comment by lukasmatta** [comment]
@Vandathron thanks for your reply. Is this information anywhere in the documentation? I can see that by default there is `production` configuration added to the `configurations` in `angular.json` file with default options such as `"optimization": true, "aot": true...` etc.

However, what are default values for these options? Eg. where in the docs it is stated that `"aot"` is by defualt set to `false`?
