### ISSUE TITLE
Installation tutorial on older documents is installing the latest version of @angular/cli

### ISSUE THREAD

**Issue by Uncodle** [angular/angular#39821]
# 📚 Docs or angular.io bug report

### Description

I was taking a look at the old documentation and I noticed that the installation command was the same used to install the latest version of @angular/cli

<code>
npm i @angular/cli@ -g
</code>

I supposed that the correct command would be something like:

<code>
npm i @angular/cli@^8 -g
</code>

### What's the affected URL?**
https://v8.angular.io/guide/setup-local

### Reproduction Steps**
- Open https://v8.angular.io/guide/setup-local
- See the "Install the Angular CLI" step
- Execute "npm i -g @angular/cli" on terminal
- "Run the command "ng version"

### Expected vs Actual Behavior**

Expected:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.29
@angular-devkit/core         8.3.29
@angular-devkit/schematics   8.3.29
@schematics/angular          8.3.29
@schematics/update           0.803.29
rxjs                         6.4.0

Actual behavior:

@angular-devkit/architect    0.1100.2 (cli-only)
@angular-devkit/core         11.0.2 (cli-only)
@angular-devkit/schematics   11.0.2 (cli-only)
@schematics/angular          11.0.2 (cli-only)
@schematics/update           0.1100.2 (cli-only)

[](url)
## 📷Screenshot
![image](https://user-images.githubusercontent.com/17017573/100032965-f06fa800-2dd7-11eb-855d-3f5b051215f1.png)

**Comment by jelbourn** [comment]
@aikidave this is an interesting problem- do we _want_ archived versions of the docs site to explicitly specify instructions for old versions of Angular? I could see going either way

**Comment by wilmarques** [comment]
Is it possible to use a newer version of the CLI to create different versions of Angular apps?

I think if one is looking the old docs, they might want the old version on the apps as well.
