### ISSUE TITLE
angular 10.x loadChild 不加载子模块组件的动态TemplateUrl

### ISSUE THREAD

**Issue by UtilCore** [angular/angular#39824]
angular 10.x 根模块在调用platformBrowserDynamic().bootstrapModule(AppModule)时执行resolveComponentResources。
但是，用loadChild 加载的子模块，并没有执行resolveComponentResources，这导致子模块中的组件如果包含动态TemplateUrl则不会被请求。

**Comment by petebacondarwin** [comment]
Google translation:

The angular 10.x root module executes resolveComponentResources when calling platformBrowserDynamic().bootstrapModule(AppModule).
 However, the sub-module loaded with loadChild does not execute resolveComponentResources, which causes the components in the sub-module to not be requested if it contains a dynamic TemplateUrl.

**Comment by UtilCore** [comment]
在组件TemplateUrl上使用动态地址非常有用，并且在根模块上表现良好。
示例：
`@Component({
  selector: 'app-root',
  templateUrl: environment.production ? './app.component.html' : 'view/app'
})
export class AppComponent {
}`
在根组件设设置这样的动态URL完全没有问题，能正确加载。
但是如果在延迟加载的子模块中这样使用则无法解析，因为没有触发resolveComponentResources操作。

**Comment by UtilCore** [comment]
我使用asp.net core和angular配合开发，asp.net core提供了TagHelper服务器端标记，我的开发方式是在开发时期使用Angular JIT编译，动态请求TagHelper页面，同时会生成一份静态Html文件。
当我正式发布的时候，采用Angular AOT方式编译，直接访问生成的HTML。
这样可以达到开发时期的高效率，同时在发布时同样具备高性能。
在Angular 8.x,我通过修改@ngtools/webpack中的代码实现了这个功能，升级到Angular 10.x后，Angular代码有重大变化，并且我发现在根模块已经可以直接请求服务端页面，我花了大量精力跟踪调试angular代码，发现在执行platformBrowserDynamic().bootstrapModule(AppModule)时会调用resolveComponentResources请求服务端页面资源，但是采用loadChild延迟加载的子模块，却没有调用resolveComponentResources。
我不清楚这样的设计是一个BUG，还是什么原因导致的，希望Angular团队能够解决这个问题，这对于我的开发方式非常重要。

**Comment by petebacondarwin** [comment]
Further translations:

---

> The use of dynamic addresses on the component TemplateUrl is very useful and performs well on the root module.
> Example:
> @Component({ selector: 'app-root', templateUrl: environment.production ? './app.component.html' : 'view/app' }) export class AppComponent { }
> There is no problem setting such a dynamic URL in the root component, and it can be loaded correctly.
> But if it is used in a lazy-loaded submodule, it cannot be resolved because the resolveComponentResources operation is not triggered.

---

> I use asp.net core and angular to cooperate with development, asp.net core provides TagHelper server-side markup, my development method is to use Angular JIT compilation during development, dynamically request TagHelper page, and generate a static Html file.
> When I officially released, I used Angular AOT to compile and directly access the generated HTML.
> This can achieve high efficiency during the development period, while also having high performance at the time of release.
> In Angular 8.x, I implemented this function by modifying the code in @ngtools/webpack. After upgrading to Angular 10.x, the Angular code has major changes, and I found that the root module can already request the server page directly. I spent a lot of effort to track and debug the angular code, and found that resolveComponentResources was called to request server-side page resources when platformBrowserDynamic().bootstrapModule(AppModule) was executed, but the submodule that was lazily loaded with loadChild did not call resolveComponentResources.
> I don't know if this design is a BUG or what caused it. I hope the Angular team can solve this problem. This is very important to my development method.

**Comment by alan-agius4** [comment]
Hi @UtilCore,

This issue has the same root causes of https://github.com/angular/angular-cli/issues/14144.

At the moment only static assignments of `templateUrl` and `stylesUrl` are not supported.
