### ISSUE TITLE
ByPass Security Trust HTML and ByPass Security Trust Style

### ISSUE THREAD

**Issue by ramanareddygopu** [angular/angular#39820]
I will explain with the issue with the written text 

In my case, From API Response, it is receiving the Styles and HTML. So i have to bind in UI with including the styles. 
I have followed two approaches for this.. 
1) When using the byPassSecurityTrustHTML => all the styles and Html is binded to UI, but the entire application styles are overriden with this styles when i am on this page. 
2) When using the sanitize(SecurityContext.HTML, 'HTML') => the styles are not applied to this 

So, could you please mention, that.. how to use the styles and HTML to the same element, from the api response.. without overriding the application styles.

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
