### ISSUE TITLE
The shadow DOM link doesn't work in ViewEncapsulation document page

### ISSUE THREAD

**Issue by pillsilly** [angular/angular#39822]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

The shadow DOM link doesn't work in ViewEncapsulation document page
The invalid link is under https://angular.io/api/core/ViewEncapsulation#description

When clicking link below
https://angular.io/api/core/ViewEncapsulation#description
![image](https://user-images.githubusercontent.com/13218151/100067636-7be94780-2e71-11eb-9a8b-7eaf11a54929.png)

It links to 
https://w3c.github.io/webcomponents/spec/shadow/
which goes 404.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by gkalpak** [comment]
Thx for submitting an issue, @pillsilly! This is being worked on in #39797.
