### ISSUE TITLE
Some error messages hard-code v9.angular.io after v11

### ISSUE THREAD

**Issue by nseni** [angular/angular#39837]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Kind of.

### Description

I ran into an error:
```
Error: ngcc is already running at process with id 11332.
If you are running multiple builds in parallel then you should pre-process your node_modules via the command line ngcc tool before starting the builds;
See https://v9.angular.io/guide/ivy#speeding-up-ngcc-compilation.
(If you are sure no ngcc process is running then you should delete the lock-file at C:/Work/frontend/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)
```

1. The link https://v9.angular.io/guide/ivy#speeding-up-ngcc-compilation points to the archived documentation for Angular v9
2. Even in the archived documentation there is nothing related to the error, there are no instructions about pre-processing the node_modules.

## 🔬 Minimal Reproduction
Remove node_modules, run `npm ci`, start `ng build` and `ng test` at the same time

## 🌍 Your Environment
<pre><code>Angular CLI: 11.0.2
Node: 12.16.1
OS: win32 x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@angular/cdk                    11.0.1
@angular/google-maps            11.0.1
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by bgotink** [comment]
In my opinion the current issue title hides the actual problem here. The biggest problem for me isn't that the link points to v9, the biggest problem is that the link points to a page that doesn't contain the information the error message is referring to.

Updating the link to the v11 docs doesn't solve the problem, that page still doesn't contain the relevant information.

Googling `speeding-up-ngcc-compilation` yields a PR build of the aio website that does contain the relevant section: https://pr34900-985c0b4.ngbuilds.io/guide/ivy#speeding-up-ngcc-compilation.

**Comment by petebacondarwin** [comment]
I think that is a very good point @bgotink. This section of the docs only existed transiently. It was added at 9.1.0-next.0 (https://github.com/angular/angular/commit/9a840e5021d0a2da320555bd30c065510de9b92c) and removed at 9.1.0-next.5 (https://github.com/angular/angular/commit/4a9514ec4ef4535afdd0b0a30cfa75aa04f283bc). But the error that mentions it was not cleaned up.
