### ISSUE TITLE
OnDestroy in a component without LifecycleEvent.OnDestroy

### ISSUE THREAD

**Issue by barbatus** [angular/angular#3985]
I noticed that onDestroy is being called even if a component does not have
````lifecycle: [LifecycleEvent.OnDestroy]```` defined in alpha36.
Is it intentional behavior?

Thanks

**Comment by vicb** [comment]
**alpha 36**

If you have some `lifecycle` configuration in your directive, they'll have priority over implemented functions. ie when you specify `lifecycle: [LifecycleEvent.OnChanges]`, `onDestroy()` will not get called although it is implemented.

If you don't specify any `lifecycle` configuration in your directive, structural type checking will be used and any lifecycle methods will get called by the CD. This must be our case.

**#3928**

This PR that should be merged soon will remove the lifecycle configuration from the directive. Any implemented hooks will automatically get called.
