### ISSUE TITLE
ngZoneEventCoalescing, a CanActivate guard and pace-js together break Angular's change detection

### ISSUE THREAD

**Issue by tonivj5** [angular/angular#39854]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core or zone.js

### Is this a regression?

 Yes, the previous version in which this bug was not present was: idk

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

https://github.com/tonivj5/ng-bug-can-activate-event-coalescing-and-pace
- npm i
- npm run start
- open two tabs: 1 with the angular app, other with whatever you want
- See that app works okay, then reload and quickly change tab. If you do it with good timing (I scroll tabs), app hasn't been rendered correctly (it logs less ticks than it should)
Here there's a gif with the process:
![bug-can-activate-with-pace](https://user-images.githubusercontent.com/7110786/100376042-1c28a300-300f-11eb-9775-1d71f0664998.gif)

The `true` log represents the CanActivate guard return.

As you can see, it's a strange bug :laughing:... It happens under these conditions:
	- You're not in the tab, other way of reproduce it is if you are in other tab and Angular cli reload your app.
	- You're using pace-js
	- You're using a CanActive guard, and its return an async observable (in my prod app, which is more complex, I have been able of reproduce it using `return true` into the guard)
	- And you have enabled `ngZoneEventCoalescing`.

Without one of these conditions, app works like a charm.

As you can see [here](https://github.com/tonivj5/ng-bug-can-activate-event-coalescing-and-pace/blob/8bb5844efaa0ea468a89836068382254424e4bc6/src/app/app.component.ts#L9-L13), it doesn't work anymore when app breaks. But when app works it log a tick correctly

## 🔥 Exception or Error
none

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.2
Node: 14.14.0
OS: linux x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

It happens in chrome and firefox, but in firefox is more complex to do it

**Comment by JiaLiPassion** [comment]
I can not reproduce this one ... As you said, it need to click the tab at the good timing, is that possible to make it reproduce every time...

**Comment by tonivj5** [comment]
then can I help with anything else? I'd like to enable `ngZoneEventCoalescing` but this issue is a blocker :cry:

Thanks for the attention :-)

**Comment by BioPhoton** [comment]
Hi @tonivj5!

Could you provide flame charts of the issue, please? 🙏
In dev tools use the performance tab and download the JSON profile. 👍
