### ISSUE TITLE
Unknown ng-content is inaccessible 

### ISSUE THREAD

**Issue by BenRacicot** [angular/angular#39875]
# 🐞 bug report

### Affected Package
[ContentChildren](https://angular.io/api/core/ContentChildren) 

### Description

ContentChildren is the correct (only) tool to access elements within ng-content, correct? 
We use it to access a QueryList of the elements, very similar to [querySelectorAll](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll).

However, accessing the elements of ng-content **which we do not know ahead of time is not possible.**

## 🔬 Minimal Reproduction
Here is a [stackblitz](https://stackblitz.com/edit/angular-focus-cycle-directive?file=src%2Fapp%2Ffocus-cycle.directive.ts) of a directive attempting to access the children of ANY element it is used on with `ContentChildren`.

Unless the content contains a template variable, or the selector is known ahead of time, this setup does not work as you'd expect.
(A equivalent to querySelectorAll does not exist within Angular?)

## 🔥 Exception or Error
Some template
```
<div AnyDirective>
    <ng-content></ng-content>
</div>
```

Within AnyDirective
`@ContentChildren("*") elms!: QueryList<unknown>; // undefined children`

**Angular Version:**
11.0.2

**Comment by lazarljubenovic** [comment]
`ContentChildren` doesn't only select things transcluded via `ng-content`. It will select children from the place where you've used the directive.

What's the use-case for querying all children?

**Comment by BenRacicot** [comment]
@lazarljubenovic nice point. I reread the docs with your statements in mind and that makes sense. Is there a more recommended tool to access content within `ng-content` that I have missed?

This specific feature I'm building which revealed the issue is a focus-cycle directive for accessibility. Mean to track focus within the directive and force tabbing to repeat inside this element (not tab to any next elements).

You can see this exemplified in my Stackblitz where the directive is applied to my dynamic stepper content but `ContentChildren` returns no children elements to work with.

```
QueryList {dirty: false, _results: Array[0], changes: {…}, length: 0…}
changes: EventEmitter_
dirty: false
first: undefined
last: undefined
length: 0
_results: Array[0]
```

**Comment by AndrewKushnir** [comment]
Hi @BenRacicot, thanks for creating a ticket and describing the use-case.

Currently there is no wildcard (`*`) support in view/content queries. As a possible solution, you may annotate elements inside the template (using additional attribute that would match another directive) and then use this annotation in the `ContentChildren` query. I've updated your Stackblitz example with extra code to do that, [you can find it here](https://stackblitz.com/edit/angular-focus-cycle-directive-dgjg6t?file=src%2Fapp%2Ffocus-cycle.directive.ts).

This feature request reminds me of #37319 and it can be a good input to #37319. I'll close this ticket for now and it will be re-reviewed as a part of #37319.

Thank you.
