### ISSUE TITLE
ViewEncapsulation

### ISSUE THREAD

**Issue by gidon-handler** [angular/angular#39885]
Hello.
 
New Angular 11 project. 
In main.ts this has no effect:

platformBrowserDynamic().bootstrapModule(AppModule, {
  defaultEncapsulation: ViewEncapsulation.ShadowDom
})

I'm trying to set the default encapsulation to ShadowDom (without setting it on every component).

Thank you

**Comment by JoostK** [comment]
Heya,

Setting default encapsulation is not currently possible in AOT compiled builds, which Angular CLI 11 enables by default. See #12251 for more information.
