### ISSUE TITLE
Angular 11 Lazy Loading with Named Outlets

### ISSUE THREAD

**Issue by qqaimh** [angular/angular#39886]
Relevant Package
@angular/router

Description
Angular 11 support Lazy Loading with Named Outlets, it is a good work. But if the lazy loading module has a RoutingModule which contains some routes, is it support navigate between these routes now?
https://stackblitz.com/github/qqaimh/named-outlet

Describe the solution you'd like
Can I navigate the routes of Lazy Loading with Named Outlets

**Comment by lazarljubenovic** [comment]
What's exactly a bug you're reporting or what's exactly the feature you're requesting? It's difficult to say since the issue reads like a support request (which belongs on [StackOverflow](http://stackoverflow.com/) using tag `angular`).

**Comment by destus90** [comment]
@qqaimh 
Aux-routes not working with empty-path top-level routes at least for the time being. It is the same as https://github.com/angular/angular/issues/10726. The temporary workaround is to set path for the top level feature module but then it is not lazy loaded any more. 
Fixed fork: https://stackblitz.com/edit/github-rpfedv-yb3zk2?file=src%2Fapp%2Fabout%2Fabout-routing.module.ts

**Comment by qqaimh** [comment]
This is a question about the new function.  Ask this on github is more resonable than on  StackOverflow  ,

**Comment by qqaimh** [comment]
> What's exactly a bug you're reporting or what's exactly the feature you're requesting? It's difficult to say since the issue reads like a support request (which belongs on [StackOverflow](http://stackoverflow.com/) using tag `angular`).

This is a question about the new function. Ask this on github is more resonable than on StackOverflow ,

**Comment by qqaimh** [comment]
> @qqaimh
> Aux-routes not working with empty-path top-level routes at least for the time being. It is the same as #10726. The temporary workaround is to set path for the top level feature module but then it is not lazy loaded any more.
> Fixed fork: https://stackblitz.com/edit/github-rpfedv-yb3zk2?file=src%2Fapp%2Fabout%2Fabout-routing.module.ts

Angular 11 had achieve Lazy Loading with Named Outlets. Above all, it should have resolve this problem

**Comment by qqaimh** [comment]
> @qqaimh
> Aux-routes not working with empty-path top-level routes at least for the time being. It is the same as #10726. The temporary workaround is to set path for the top level feature module but then it is not lazy loaded any more.
> Fixed fork: https://stackblitz.com/edit/github-rpfedv-yb3zk2?file=src%2Fapp%2Fabout%2Fabout-routing.module.ts

and you send me  https://stackblitz.com/edit/github-rpfedv-yb3zk2?file=src%2Fapp%2Fabout%2Fabout-routing.module.ts
not work!!

**Comment by qqaimh** [comment]
> @qqaimh
> Aux-routes not working with empty-path top-level routes at least for the time being. It is the same as #10726. The temporary workaround is to set path for the top level feature module but then it is not lazy loaded any more.
> Fixed fork: https://stackblitz.com/edit/github-rpfedv-yb3zk2?file=src%2Fapp%2Fabout%2Fabout-routing.module.ts

I am wrong! you are right ,Thank you

**Comment by qqaimh** [comment]
> @qqaimh
> Aux-routes not working with empty-path top-level routes at least for the time being. It is the same as #10726. The temporary workaround is to set path for the top level feature module but then it is not lazy loaded any more.
> Fixed fork: https://stackblitz.com/edit/github-rpfedv-yb3zk2?file=src%2Fapp%2Fabout%2Fabout-routing.module.ts

I am wrong! you are right ,Thank you
