### ISSUE TITLE
Possibly code missing from the angular.json file created when using this template: tns create my-app-name --template tns-template-tab-navigation

### ISSUE THREAD

**Issue by HannahVGill** [angular/angular#39890]
Possibly code missing from the angular.json file created when using this template: tns create my-app-name --template tns-template-tab-navigation, consequently the code doesn't build.

**Comment by alan-agius4** [comment]
tns is the CLI tool of NativeScript which is not supported by the Angular team. 

Please file an issue in their issue tracker here: https://github.com/NativeScript/NativeScript
