### ISSUE TITLE
Load Function for IMG Element Does Not Work As Expected

### ISSUE THREAD

**Issue by oividioscaeremos** [angular/angular#39893]
# 🐞 bug report

### Is this a regression?

 This is the first version of Angular I'm using. But a question on stackoverflow shows this issue was not present before(4 years ago on Angular 2) [Here's the link](https://stackoverflow.com/questions/39257687/detect-when-image-has-loaded-in-img-tag)

### Description

 A clear and concise description of the problem...
I have an array of objects that contain URL's for several images and I want to show these images on my page. But here's the catch; some images are taller than others or some are wider than others in another statement. So for each picture, to either set their object-fit to scale-down or to cover, I need to know whether the image is wide or tall. I'm trying to get the image's naturalWidth and naturalHight values through the (load) function that Angular provides but the function is repeatedly called for the first element of the array. By repeatedly, I mean for real. The function is getting called for that one element in the array non-stop.

the way I'm using it from IMG element
`
<img [src]="xxx"
                            appPreventDoubleClick
                            (throttledClick)="viewFile(imageId)"
                            (load)="loadImage($event)"
                            class="card-img-top">
`

And my function on the background is 

```
loadImage(evt){
        if (evt && evt.target) {
          const x = (evt.srcElement as HTMLImageElement).naturalWidth;
          console.log('x:' + x);
      
      if ((x === 0 ) && (y === 0)) {
        const width = evt.srcElement.width;
        const height = evt.srcElement.height;
        let portrait = height > width ? true : false;
        console.log('Loaded: ', width, height, 'portrait: ', portrait);
      }
    }
```

the console output of this function is:

![image](https://user-images.githubusercontent.com/24587852/100654736-52da2280-335b-11eb-9d0f-3b57890111d4.png)
(don't mind the socket error)

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular version: 9.0.1
</code></pre>

**Anything else relevant?**

I'm using Chrome.

**Comment by jessicajaniuk** [comment]
@oividioscaeremos Thanks for the bug report. Could you generate a minimal reproduction on stackblitz for us? That would be helpful in understanding what you're seeing. Thank you!

**Comment by oividioscaeremos** [comment]
> @oividioscaeremos Thanks for the bug report. Could you generate a minimal reproduction on stackblitz for us using the latest angular version instead of version 9? That would be helpful in understanding what you're seeing and if it's still an issue. Thank you!

Hey @jessicajaniuk, It works on the latest Angular version on Stackblitz. But, the project I am working on is a corporate project which means version updates may take days or even couple of weeks of work. I don't think my team-leader would approach positively to the upgrading the angular version. Is there any workarounds that you're aware of that I can use until the version update happens?

Thank you for your fast reply.

**Comment by ulrikwalter** [comment]
Do you want a fixed size image-grid? Are all picture boxes the same, and filled top/bottom or left/right a color?)

**Comment by jessicajaniuk** [comment]
It's understandable that upgrades on the corporate side take more effort and prioritization. For workarounds, since v9 and even v10 are not in active support anymore, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular` and outline which specific version there. Since there's no action for us due to the issue being obsolete, I'm marking this issue as closed.

**Comment by ulrikwalter** [comment]
@oividioscaeremos  Is tm.filter:1503 your dev server and do you use angular proxy?

**Comment by oividioscaeremos** [comment]
> Do you want a fixed size image-grid? Are all picture boxes the same, and filled top/bottom or left/right a color?)

All boxes are the same but not all the images are. Some are landscape and some are not. Using scale-down for all makes landscape pictures look bad and other way around makes portrait images look stretched.

> @oividioscaeremos Is tm.filter:1503 your dev server and do you use angular proxy?

we do use a global proxy for node, but how is it only creating an issue on this particular event?

**Comment by ulrikwalter** [comment]
@oividioscaeremos in this case, we use the images as background of divs.

Like this:
```css
.imgdiv {
    background-repeat: none; 
    background-position: 50% 50%; 
    background-size: contain;
    width: 200px;
    height: 200px;
}
```


```html
<div class="imgdiv" [style.background-image]="'url(' + image.url + ')'"></div>
```

Or if all images are larger than containers, you can use max-width/max-height style. (without background-image)

**Comment by oividioscaeremos** [comment]
> @oividioscaeremos in this case, we use the images as background of divs.
> 
> Like this:
> 
> ```css
> .imgdiv {
>     background-repeat: none; 
>     background-position: 50% 50%; 
>     background-size: contain;
>     width: 200px;
>     height: 200px;
> }
> ```
> 
> ```
> <div class="imgdiv" [style.background-image]="'url(' + image.url + ')'"></div>
> ```
> 
> Or if all images are larger than containers, you can use max-width/max-height style. (without background-image)
> 
> This solution might be good for you too.

Before looking at your solution, I solved mine on the backend with some c# code.  Your suggestion seems nice [https://angular-ivy-amhwke.stackblitz.io](url) Thanks for your help 👍
