### ISSUE TITLE
Closing this ticket based on the comment above. Feel free to reopen if the problem still exists. Thank you.

### ISSUE THREAD

**Issue by initplatform** [angular/angular#39891]
Closing this ticket based on the comment above. Feel free to reopen if the problem still exists. Thank you.

_Originally posted by @AndrewKushnir in https://github.com/angular/angular/issues/39484#issuecomment-719840991_

**Comment by initplatform** [comment]
Hi, not sure how to re-open after it's been locked by the bot. 

Still seeing the issue in production. 

You can run lighthouse on our app to see it. 

https://startbootstrap.com/

This is build with :
```
npm run ng -- build --prod --crossOrigin=anonymous --build-optimizer=true --vendor-chunk=true --statsJson=true
```

**Comment by initplatform** [comment]
@JiaLiPassion

**Comment by AndrewKushnir** [comment]
Hi @initplatform, I've reopened the original issue (#39484) and will close this one. Could you please post additional information in #39484? Thank you.

**Comment by initplatform** [comment]
For some reason I am still locked out of #39484

**Comment by initplatform** [comment]
<img width="1091" alt="Screen Shot 2020-11-30 at 1 12 58 PM" src="https://user-images.githubusercontent.com/47506789/100647634-cc4b2400-330d-11eb-99da-659ba161a514.png">

**Comment by AndrewKushnir** [comment]
@initplatform, please try again, it should be working now. Thank you.

**Comment by initplatform** [comment]
Thanks! I am able to add to #39484 again
