### ISSUE TITLE
Improvements for error messages for inexisting bindings

### ISSUE THREAD

**Issue by jhades** [angular/angular#3990]
In alpha 36,  whenever a binding is undefined, a generic error message is thrown like the stacktrace bellow. The binding can be undefined if it was accidentally not imported, or in the case of alpha upgrades if it was renamed. It can happen during app development due to typos as well (the tools are getting better for this).

In order to find which binding is causing this, currently we have to go over the multiple bindings of the project and remove them one by one, then re-run the app. 

I don't know how feasible it is, but it would be great to have in the message at least the component/directive name for which the binding was found to be undefined, and maybe the binding position?

    EXCEPTION: Error during instantiation of    Token(Promise<ComponentRef>)!.
    angular2.dev.js:22746 ORIGINAL EXCEPTION: TypeError: Cannot read property 'toString' of     undefined
    angular2.dev.js:22746 ORIGINAL STACKTRACE:
    angular2.dev.js:22746 TypeError: Cannot read property 'toString' of undefined
        at new InvalidBindingError (angular2.dev.js:9171)
       at _resolveBindings (angular2.dev.js:27377)
      at Function.execute.Injector.resolve (angular2.dev.js:28030)
      at Function.execute.DirectiveBinding.createFromBinding (angular2.dev.js:28611)
      at Function.execute.DirectiveBinding.createFromType (angular2.dev.js:28643)
      at execute.Compiler._bindDirective (angular2.dev.js:29892)
      at execute.Compiler.compileInHost (angular2.dev.js:29908)
      at execute.DynamicComponentLoader.loadAsRoot (angular2.dev.js:17421)
      at angular2.dev.js:30555

**Comment by ericmdantas** [comment]
That'd be great.

**Comment by PhilippGrulich** [comment]
+1

**Comment by AlicanC** [comment]
I have just had the same problem and I have no idea what's going on since the stack trace has nothing related to my code.

**Comment by jhades** [comment]
This was meanwhile fixed. If an unexisting binding `wrongBinding` is passed to a component, the error message is now (in beta-0):

    Error: wrongBinding is not defined(…) "Error bootstrapping app"
