### ISSUE TITLE
[angular/core] make DebugServices treeshakable (~10KB savings)

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#39902]
_From @aitboudad on October 28, 2017 10:20_

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Desired functionality

Uglify is not able to remove unused debug services bocause of condition: [core.js#L13946](https://github.com/angular/core-builds/blob/5.0.0-rc.8/esm5/core.js#L13946) and replacing that condition with `createProdServices()` resulted in ~10KB savings

```patch
-- var /** @type {?} */ services = isDevMode() ? createDebugServices() : createProdServices();
++ var /** @type {?} */ services = createProdServices();
```

_Copied from original issue: angular/devkit#244_

**Comment by jelbourn** [comment]
@IgorMinar this is supposed to be resolved by the combination of Ivy and `ngDevMode`, right?

**Comment by JoostK** [comment]
Closing as obsolete, since these services are ViewEngine specific.
