### ISSUE TITLE
Service Worker registration does not use ErrorHandler

### ISSUE THREAD

**Issue by chrisguttandin** [angular/angular#39913]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/service-worker

### Is this a regression?

No, I don't think so,

### Description

The Service Worker registration logs an error in the console when the it fails. I think that's confusing and it would be better to use the [ErrorHandler](https://angular.io/api/core/ErrorHandler) which other parts of Angular use. That way Angular users could handle the error themselves.

## 🔬 Minimal Reproduction

As far as I know there is not really an easy way to reproduce this besides deploying a broken app. I hope it's okay to point to the source instead.

https://github.com/angular/angular/blob/11cd37fae304720d32b3f010f61ea7065d34b40b/packages/service-worker/src/module.ts#L132-L133

This is where the Service Worker gets registered and possible errors get logged to the console directly.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.2
Node: 12.20.0
OS: darwin x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

I would be happy to create a PR for fixing this. Please let me know if I should do so.

**Comment by gkalpak** [comment]
Sounds reasonable :+1:
I can't think of any reason not to pass it to the `ErrorHandler` and looking at the PR that introduced this (#30876), there doesn't seem it was a deliberate choice not to.

Thx for bringing it up, @chrisguttandin, and for offering to create a PR. That would be great 🤩
Feel free to ping me if you need any help with the process.

**Comment by chrisguttandin** [comment]
Thanks for taking a look, @gkalpak. I created #39990 to address the issue.
