### ISSUE TITLE
CHANGELOG.md does not list the Angular 11.0.3 release or it's changes.

### ISSUE THREAD

**Issue by RobbieTechie** [angular/angular#39947]
Went to read what changed with the 11.0.3  release yesterday, and there is nothing for 11.0.3 even though that's what is listed on NPM and what's the version that it installed. ¯\_(ツ)_/¯
https://github.com/angular/angular/blob/master/CHANGELOG.md

If I've missed something please let me know.
Thank You
https://github.com/angular/angular/blob/master/CHANGELOG.md

**Comment by petebacondarwin** [comment]
So the changelog was updated for 11.0.3 on the 11.0.x branch: https://github.com/angular/angular/blob/11.0.x/CHANGELOG.md
But I agree that it should also have appear on master too.

**Comment by RobbieTechie** [comment]
Thank ALL of you in the entire team for your awesome work and dedication.
I saw the master changelog is updated, so I'm going to close this.
