### ISSUE TITLE
DOM elements are not removed when the root view is removed

### ISSUE THREAD

**Issue by arturovt** [angular/angular#39955]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/animations **(probably)**

### Is this a regression?

I cannot say

### Description

All DOM elements remain when calling `NgModuleRef.destroy()`, but actually, all `ngOnDestroy` hooks are invoked, event listeners are removed, basically, all cleanups are done except removing nodes from DOM.

:warning: This happens only when the `BrowserAnimationsModule` is imported, this doesn't happen with `BrowserModule`.

## 🔬 Minimal Reproduction

1. 
```sh
$ git clone git@github.com:arturovt/ngmoduleref-destroy-issue.git
$ cd ngmoduleref-destroy-issue
$ yarn
```
2. Start dev server `yarn ng s`
3. Go to `http://localhost:4200`, open dev tools, click the "Destroy" button. Notice logs in the console
4. Notice that DOM elements are NOT removed

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.3
Node: 12.20.0
OS: linux x64

Angular: 11.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.3
@angular-devkit/build-angular   0.1100.3
@angular-devkit/core            11.0.3
@angular-devkit/schematics      11.0.3
@schematics/angular             11.0.3
@schematics/update              0.1100.3
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by arturovt** [comment]
Fixed by https://github.com/angular/angular/pull/41001

**Comment by zarend** [comment]
Reverting this in #41056

**Comment by arturovt** [comment]
Fixed by https://github.com/angular/angular/pull/41059
