### ISSUE TITLE
When Upgrading from Angular 10 to Angular 11, missing-injectable Schematic Throws Exception

### ISSUE THREAD

**Issue by mylifeandcode** [angular/angular#39953]
# 🐞 bug report

### Affected Package
@angular-devkit/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9

### Description

When upgrading from Angular 10.0 to Angular 11 using the instructions on the upgrade page, I got the following exception:

Cannot find module '@angular-devkit/core'

Here is the console output (I had to use --force due to peer dependencies on things like @angular/http, which I was unable to resolve one-by-one):

C:\DevGit\Abim.Portal.StaffTwo>ng update @angular/core @angular/cli --force
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 57 dependencies.
Fetching dependency metadata from registry...
                  Package "@angular/cdk" has an incompatible peer dependency to "@angular/common" (requires "^8.0.0 || ^9.0.0-0" (extended), would install "11.0.3").
                  Package "@angular/cdk" has an incompatible peer dependency to "@angular/core" (requires "^8.0.0 || ^9.0.0-0" (extended), would install "11.0.3").
                  Package "@angular/http" has an incompatible peer dependency to "@angular/platform-browser" (requires "7.2.16" (extended), would install "11.0.3").
    Updating package.json with dependency @angular-devkit/build-angular @ "0.1100.3" (was "0.1000.0")...
    Updating package.json with dependency @angular/cli @ "11.0.3" (was "10.0.0")...
    Updating package.json with dependency @angular/compiler-cli @ "11.0.3" (was "10.0.1")...
    Updating package.json with dependency @angular/language-service @ "11.0.3" (was "10.0.1")...
    Updating package.json with dependency karma @ "5.1.1" (was "5.0.9")...
    Updating package.json with dependency ng-packagr @ "11.0.3" (was "10.0.0")...
    Updating package.json with dependency typescript @ "4.0.5" (was "3.9.5")...
    Updating package.json with dependency @angular/animations @ "11.0.3" (was "10.0.1")...
    Updating package.json with dependency @angular/common @ "11.0.3" (was "10.0.1")...
    Updating package.json with dependency @angular/compiler @ "11.0.3" (was "10.0.1")...
    Updating package.json with dependency @angular/core @ "11.0.3" (was "10.0.1")...
    Updating package.json with dependency @angular/forms @ "11.0.3" (was "10.0.1")...
    Updating package.json with dependency @angular/localize @ "11.0.3" (was "10.0.1")...
    Updating package.json with dependency @angular/platform-browser @ "11.0.3" (was "10.0.1")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "11.0.3" (was "10.0.1")...
    Updating package.json with dependency @angular/router @ "11.0.3" (was "10.0.1")...
  UPDATE package.json (4498 bytes)
√ Packages installed successfully.
** Executing migrations of package '@angular/cli' **

> Update 'module' and 'target' TypeScript compiler options.
  Read more about this here: https://v10.angular.io/guide/migration-update-module-and-target-compiler-options
    Unable to update 'e2e/tsconfig.json' target option from 'es5' to 'es2018': Could not read 'e2e/tsconfig.json'.
  Migration completed.

> Removing "Solution Style" TypeScript configuration file support.
  DELETE tsconfig.base.json
  UPDATE tsconfig.json (1234 bytes)
  UPDATE e2e/tsconfig.e2e.json (225 bytes)
  UPDATE projects/esa-service-lib/tsconfig.lib.json (761 bytes)
  UPDATE projects/esa-service-lib/tsconfig.spec.json (263 bytes)
  UPDATE projects/esa-ui-lib/tsconfig.lib.json (761 bytes)
  UPDATE projects/esa-ui-lib/tsconfig.spec.json (263 bytes)
  UPDATE src/tsconfig.app.json (218 bytes)
  UPDATE src/tsconfig.spec.json (274 bytes)
  Migration completed.

> Replace deprecated library builder '@angular-devkit/build-ng-packagr'.
  UPDATE angular.json (8846 bytes)
  UPDATE package.json (4446 bytes)
  Migration completed.

> Add 'declarationMap' compiler options for non production library builds.
  UPDATE projects/esa-service-lib/tsconfig.lib.prod.json (160 bytes)
  UPDATE projects/esa-service-lib/tsconfig.lib.json (790 bytes)
  UPDATE projects/esa-ui-lib/tsconfig.lib.prod.json (160 bytes)
  UPDATE projects/esa-ui-lib/tsconfig.lib.json (790 bytes)
  Migration completed.

> Remove deprecated options from 'angular.json' that are no longer present in v11.
  UPDATE angular.json (8790 bytes)
  Migration completed.

> Update workspace dependencies to match a new v11 project.
  UPDATE package.json (4446 bytes)
√ Packages installed successfully.
  Migration completed.

An unhandled exception occurred: Cannot find module '@angular-devkit/core'
Require stack:
- C:\DevGit\Abim.Portal.StaffTwo\node_modules\@angular\core\schematics\utils\project_tsconfig_paths.js
- C:\DevGit\Abim.Portal.StaffTwo\node_modules\@angular\core\schematics\migrations\missing-injectable\index.js
- C:\Users\ahummel\AppData\Local\Temp\angular-cli-packages-F2PIIN\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\ahummel\AppData\Local\Temp\angular-cli-packages-F2PIIN\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\ahummel\AppData\Local\Temp\angular-cli-packages-F2PIIN\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\ahummel\AppData\Local\Temp\angular-cli-packages-F2PIIN\node_modules\@angular\cli\models\command-runner.js
- C:\Users\ahummel\AppData\Local\Temp\angular-cli-packages-F2PIIN\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\ahummel\AppData\Local\Temp\angular-cli-packages-F2PIIN\node_modules\@angular\cli\lib\init.js
- C:\Users\ahummel\AppData\Local\Temp\angular-cli-packages-F2PIIN\node_modules\@angular\cli\bin\ng
See "C:\Users\ahummel\AppData\Local\Temp\ng-03iok6\angular-errors.log" for further details.

## 🔬 Minimal Reproduction
Run ng update @angular/core @angular/cli --force

It's worth noting that I upgraded a different app from, Angular 10.2 to 11, with no problem.

I'm not able to share the code for this, sorry.

## 🔥 Exception or Error
An unhandled exception occurred: Cannot find module '@angular-devkit/core'
Require stack:
- C:\DevGit\Abim.Portal.StaffTwo\node_modules\@angular\core\schematics\utils\project_tsconfig_paths.js
- C:\DevGit\Abim.Portal.StaffTwo\node_modules\@angular\core\schematics\migrations\missing-injectable\index.js
- C:\Users\ahummel\AppData\Local\Temp\angular-cli-packages-F2PIIN\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\ahummel\AppData\Local\Temp\angular-cli-packages-F2PIIN\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\ahummel\AppData\Local\Temp\angular-cli-packages-F2PIIN\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\ahummel\AppData\Local\Temp\angular-cli-packages-F2PIIN\node_modules\@angular\cli\models\command-runner.js
- C:\Users\ahummel\AppData\Local\Temp\angular-cli-packages-F2PIIN\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\ahummel\AppData\Local\Temp\angular-cli-packages-F2PIIN\node_modules\@angular\cli\lib\init.js
- C:\Users\ahummel\AppData\Local\Temp\angular-cli-packages-F2PIIN\node_modules\@angular\cli\bin\ng
See "C:\Users\ahummel\AppData\Local\Temp\ng-03iok6\angular-errors.log" for further details.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.3
Node: 12.14.1
OS: win32 x64

Angular: 11.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.3 (cli-only)
@angular-devkit/build-angular   0.1100.3
@angular-devkit/core            11.0.3 (cli-only)
@angular-devkit/schematics      11.0.3
@angular/cdk                    8.2.3
@angular/http                   7.2.16
@schematics/angular             11.0.3
@schematics/update              0.1100.3
ng-packagr                      11.0.3
rxjs                            6.6.3
typescript                      4.1.2

</code></pre>
[angular-errors.log](https://github.com/angular/angular/files/5637957/angular-errors.log)

**Anything else relevant?**
Not that I can think of. Sorry for what I'm sure is an ambiguous issue. :/ Log file is attached.

**Comment by alan-agius4** [comment]
This looks like a hosting issue which is similar to (https://github.com/angular/angular-cli/issues/18744 and https://github.com/angular/components/issues/21045), can you try to remove the package-lock and node_modules and run the migrations only?

```
rm -rf node_modules package-lock.json
npm i 
ng update @angular/core --migrate-only --from 10 --to 11
```

**Comment by mylifeandcode** [comment]
That did the trick @alan-agius4 , thanks! The only other anomaly after that was that the version of TypeScript had been bumped past 4.1, and the Angular compiler threw an exception on that:

_ERROR: The Angular Compiler requires TypeScript >=4.0.0 and <4.1.0 but 4.1.2 was found instead._

To correct, I set the version to ^4.0.5 in my package.json, reinstalled the package, and all was well. Thanks again!

**Comment by adamdavidcz** [comment]
I got same message when upgrading from 10.2. Solution mentioned by @alan-agius4 didn't work. Command `ng update @angular/core --migrate-only --from 10 --to 11`  just didn't do any change to any file. This is from terminal where i run it

`
MacBook-Pro:component-md-viewer-ng2 adam$ ng update @angular/core --migrate-only --from 10 --to 11
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 34 dependencies.
`

I tried running normal update after this with same result:

`
MacBook-Pro:component-md-viewer-ng2 adam$ ng update @angular/core @angular/cli --force
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 34 dependencies.
Fetching dependency metadata from registry...
                  Package "@angular-devkit/build-angular" has an incompatible peer dependency to "karma" (requires "~5.1.0", would install "5.2.3")
                  Package "@angular/common" has a missing peer dependency of "rxjs" @ "^6.5.3".
                  Package "@angular/core" has a missing peer dependency of "rxjs" @ "^6.5.3".
                  Package "@angular/core" has an incompatible peer dependency to "zone.js" (requires "~0.10.3", would install "0.11.3")
    Updating package.json with dependency @angular-devkit/build-angular @ "0.1100.4" (was "0.1002.0")...
    Updating package.json with dependency @angular/cli @ "11.0.4" (was "10.2.0")...
    Updating package.json with dependency @angular/compiler-cli @ "11.0.4" (was "10.2.3")...
    Updating package.json with dependency ng-packagr @ "11.0.3" (was "10.1.2")...
    Updating package.json with dependency @angular/common @ "11.0.4" (was "10.2.3")...
    Updating package.json with dependency @angular/compiler @ "11.0.4" (was "10.2.3")...
    Updating package.json with dependency @angular/core @ "11.0.4" (was "10.2.3")...
    Updating package.json with dependency @angular/platform-browser @ "11.0.4" (was "10.2.3")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "11.0.4" (was "10.2.3")...
  UPDATE package.json (2629 bytes)
✔ Packages installed successfully.
** Executing migrations of package '@angular/cli' **

❯ Replace deprecated library builder '@angular-devkit/build-ng-packagr'.
  UPDATE angular.json (1588 bytes)
  UPDATE package.json (2577 bytes)
  Migration completed.

❯ Add 'declarationMap' compiler options for non production library builds.
  UPDATE projects/component-md-viewer-ng2/tsconfig.lib.prod.json (152 bytes)
  UPDATE projects/component-md-viewer-ng2/tsconfig.lib.json (537 bytes)
  Migration completed.

❯ Remove deprecated options from 'angular.json' that are no longer present in v11.
  Migration completed.

❯ Update workspace dependencies to match a new v11 project.
  UPDATE package.json (2577 bytes)
✔ Packages installed successfully.
  Migration completed.

An unhandled exception occurred: Cannot find module '@angular-devkit/core'
Require stack:
- /Users/adam/Repos/component-md-viewer-ng2/node_modules/@angular/core/schematics/utils/project_tsconfig_paths.js
- /Users/adam/Repos/component-md-viewer-ng2/node_modules/@angular/core/schematics/migrations/missing-injectable/index.js
- /private/var/folders/w8/3ymdk5fs563b66d_5gdkjrkh0000gn/T/angular-cli-packages-o4wcF4/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /private/var/folders/w8/3ymdk5fs563b66d_5gdkjrkh0000gn/T/angular-cli-packages-o4wcF4/node_modules/@angular-devkit/schematics/tools/index.js
- /private/var/folders/w8/3ymdk5fs563b66d_5gdkjrkh0000gn/T/angular-cli-packages-o4wcF4/node_modules/@angular/cli/utilities/json-schema.js
- /private/var/folders/w8/3ymdk5fs563b66d_5gdkjrkh0000gn/T/angular-cli-packages-o4wcF4/node_modules/@angular/cli/models/command-runner.js
- /private/var/folders/w8/3ymdk5fs563b66d_5gdkjrkh0000gn/T/angular-cli-packages-o4wcF4/node_modules/@angular/cli/lib/cli/index.js
- /private/var/folders/w8/3ymdk5fs563b66d_5gdkjrkh0000gn/T/angular-cli-packages-o4wcF4/node_modules/@angular/cli/lib/init.js
- /private/var/folders/w8/3ymdk5fs563b66d_5gdkjrkh0000gn/T/angular-cli-packages-o4wcF4/node_modules/@angular/cli/bin/ng
See "/private/var/folders/w8/3ymdk5fs563b66d_5gdkjrkh0000gn/T/ng-pnREPI/angular-errors.log" for further details.
`

**Comment by adamdavidcz** [comment]
Only solution to update without getting errors was to install @angular-devkit/core before update itself.

**Comment by mylifeandcode** [comment]
> Only solution to update without getting errors was to install @angular-devkit/core before update itself.

When you installed @angular-devkit/core, did you install it globally or local to the project?

**Comment by AndreasGassmann** [comment]
@mylifeandcode I installed it as a dev dependency and it worked.

**Comment by adamdavidcz** [comment]
I just tried to update same app and it seems this problem is resolved, update is now finished without errors

**Comment by nzbin** [comment]
I have soled this issue with `yarn`

`rm -rf node_modules package-lock.json && yarn`
