### ISSUE TITLE
entryComponents marked deprecrated, but still needed for npm libraries

### ISSUE THREAD

**Issue by kshetline** [angular/angular#39958]
# 📚 Docs or angular.io bug report

### Description

As instructed by the _Angular Update Guide_, I removed `entryComponents` from my `NgModules` file. Only later on in the development process did I see the warning that an Angular npm library shouldn't use Ivy, and so I disabled Ivy, but at this point the mention of Ivy in the instructions about `entryComponents`, as the reason `entryComponents` was no longer needed, was a distant memory.

Only later when my library failed to work in an application that installed it did I eventually figure out that the fix needed was to restore the removed `entryComponents`.

So it may be that `entryComponents` is no longer needed for most applications, but it shouldn't be deprecated when there's still a situation -- like creating a npm library of Angular components -- where `entryComponents` might be absolutely necessary.

The _Angular Update Guide_ should also warn that there are situations when you should leave `entryComponents` in place.

## 🔬 Minimal Reproduction

Any situation where you're developing an Angular npm library and need to keep `entryComponents`.

### What's the affected URL?**

n/a

### Reproduction Steps**

Any situation where you're developing an Angular npm library and need to keep `entryComponents`.

### Expected vs Actual Behavior**

Documentation and deprecation that doesn't lead me astray into breaking my code.

## 📷Screenshot

n/a

## 🔥 Exception or Error

n/a

## 🌍  Your Environment

n/a

### Browser info

n/a

**Comment by lazarljubenovic** [comment]
I get the issue, but I'm not sure how this would be actionable. Normally for this kind of issue the solution is "let's mention it", but you acknowledge that "ivy only" warning _is_ present.

**Comment by kshetline** [comment]
There is no "ivy only" warning present. The wording is "If you have specified any `entryComponents` in your NgModules or had any uses of `ANALYZE_FOR_ENTRY_COMPONENTS`, you can remove them. They are no longer required with the Ivy compiler and runtime."

That does not at all suggest that there will be times you'll need to deliberately disable Ivy, and that there would then be bad consequences for deleting entryComponents when you do so. If you make this mistake there is no friendly warning at compile time, just a runtime crash because your entryComponents are missing.

This could require a little more than a documentation change, since the deprecation might be annotated as such in your code, and what has happened here isn't true deprecation.

**Comment by jelbourn** [comment]
@petebacondarwin is there any reason ngcc needs `entryComponents` to be specified for libraries that only target Ivy? If not I think this is "working as intended" since we expect the majority of applications to have moved to Ivy by v11.

**Comment by kshetline** [comment]
> @petebacondarwin is there any reason ngcc needs `entryComponents` to be specified for libraries that only target Ivy? If not I think this is "working as intended" since we expect the majority of applications to have moved to Ivy by v11.

Not everything Angular is an application, and that's the point. Even in Angular 11 a library of Angular components can't be Ivy -- Ivy isn't even optional, it's disallowed for a library.

**Comment by petebacondarwin** [comment]
As @kshetline points out, libraries (for now) must be compiled with ViewEngine. And so they need to comply with all the ViewEngine requirements, in this case regarding `entryComponents`. I would be in favour of calling this out somewhere in the docs.

**Comment by jelbourn** [comment]
Ah yeah, the obvious case that escaped me was a library depending on another library. I'd lean towards undeprecating this API until ng-linker is available. @IgorMinar thoughts?

**Comment by JoostK** [comment]
Entry components only affect application codegen (but only for View Engine) and are not relevant when building a library depending on another library, as in that case the compiler is only doing metadata extraction and not codegen<sup>1</sup>. So it could be fine to build a library using View Engine without using `entryComponents`, but that precludes that library from being used in a View Engine application.

I'd personally stick with the deprecation of `entryComponents`, but do agree that this is something to note in the documentation.

---
<sup>1</sup> Well, it does do  re-export generation and compiling of tree-shakeable providers, but that's about it.
