### ISSUE TITLE
Getting "export '__platform_browser_private__' was not found in '@angular/platform-browser' error

### ISSUE THREAD

**Issue by rajubabub84** [angular/angular#39969]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

getting below error when i migrated app from angular2 to angular11

Error: ./node_modules/@angular/http/__ivy_ngcc__/src/backends/xhr_backend.js 282:16-44
"export '__platform_browser_private__' was not found in '@angular/platform-browser'

package.json:
{
  "name": "qandc-ui",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "dev": "ng build --configuration=dev --aot --output-hashing=bundles --base-href /qnc/",
    "prod": "ng build --configuration=prod --aot --output-hashing=bundles --base-href /qnc/",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/build-angular": "^0.1100.2",
    "@angular/animations": "^10.2.3",
    "@angular/cli": "^11.0.2",
    "@angular/common": "^11.0.2",
    "@angular/compiler": "^11.0.2",
    "@angular/core": "^11.0.2",
    "@angular/forms": "^11.0.2",
    "@angular/platform-browser": "^11.0.2",
    "@angular/platform-browser-dynamic": "^11.0.2",
    "@angular/router": "^11.0.2",
    "@angular/tsc-wrapped": "^4.4.6",
    "@ng-idle/core": "2.0.0-beta.12",
    "@ng-idle/keepalive": "2.0.0-beta.12",
    "angular-2-local-storage": "1.0.1",
    "angular2-json2csv": "^1.1.2",
    "angular2-uuid": "^1.1.1",
    "angularjs-datepicker": "^2.1.13",
    "base64-img": "^1.0.4",
    "bootstrap": "^3.3.7",
    "browserslist": "^4.14.7",
    "core-js": "^2.6.12",
    "datatables-bootstrap3-plugin": "^0.6.0",
    "datatables.net": "^1.10.22",
    "font-awesome": "^4.7.0",
    "jquery": "^3.5.1",
    "jspdf": "^1.5.3",
    "jspdf-autotable": "^3.5.13",
    "mime-types": "^2.1.27",
    "mini-css-extract-plugin": "^1.3.1",
    "ng-pdf-make": "^0.1.1",
    "ng2-file-upload": "^1.2.0",
    "ngx-bootstrap": "^5.6.2",
    "ngx-device-detector": "^2.0.1",
    "rxjs": "^6.6.3",
    "rxjs-compat": "^6.6.3",
    "ts-helpers": "^1.1.1",
    "tslib": "^2.0.0",
    "typings": "^2.1.1",
    "webpack": "^4.44.2",
    "webpack-dev-server": "^3.11.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^11.0.2",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.19.7",
    "angular-cli": "1.0.0-beta.28.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "~4.0.0",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~7.0.0",
    "ts-node": "1.2.1",
    "tslint": "~6.1.0",
    "typescript": "~4.0.0"
  }
}

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Hi,

`@angular/http` is no longer supported. the last released version was 7.2.16. When using Angular 8+ you should replace the usages of `@angular/http` with `@angular/common/http`.

See: https://angular.io/guide/deprecations#angularhttp
