### ISSUE TITLE
Why didn't Angular has an offical debug tool?

### ISSUE THREAD

**Issue by PeterChen1997** [angular/angular#39968]
# 🚀 feature request

### Relevant Package

angular has angury, but it's no longer maintained

vue has vue-debug-tool

react has react-debug-tool

### Description

I think many developers need a useful debug tool in developing large scales project.

Am i miss some useful tool instead? It's really hard for me to find some struct info in chrome debug, wish one day we can have one.

### Describe the solution you'd like

Take over Angury and fix it for new version of ng?

### Describe alternatives you've considered

Maybe take time to do it or store in the roadmap?

**Comment by KrakenZ** [comment]
You can use an extension called "angular state inspector", which helps. 
But indeed some official tool would be handy.
Especially if we could filter the unwanted "internal" exceptions (zone.js, core.js, rxjs...) that gets in the error stack and makes it harder to debug.

**Comment by PeterChen1997** [comment]
> You can use an extension called "angular state inspector", which helps.
> But indeed some official tool would be handy.
> Especially if we could filter the unwanted "internal" exceptions (zone.js, core.js, rxjs...) that gets in the error stack and makes it harder to debug.

thx bro, i'll have a try~

**Comment by criskrzysiu** [comment]
there is one on the way, it was shown on some ng-conf few weaks ago https://youtu.be/FsNTuzBfLxU?t=1961

**Comment by PeterChen1997** [comment]
> https://youtu.be/FsNTuzBfLxU?t=1961

thx bro, let me see

**Comment by mgechev** [comment]
>https://github.com/angular/angular/issues/39968#issuecomment-738717732

Yes, this is something we've been working on. You can follow the progress [in the roadmap](https://angular.io/guide/roadmap).
