### ISSUE TITLE
Reopen Issue 39973

### ISSUE THREAD

**Issue by TUTUBIG** [angular/angular#39984]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please help us process issues more efficiently by filing an
issue using one of the following templates:

https://github.com/angular/angular/issues/new/choose

origin issue https://github.com/angular/angular/issues/39973
please have a look  comments of the origin issue

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by aksdevac** [comment]
you can comment on closed issue for reopen request may be they will reopen instead of creating new issue which only refers to closed issue.

**Comment by AndrewKushnir** [comment]
Closing based on https://github.com/angular/angular/issues/39973#issuecomment-739135943. Please post additional information as a comment to #39973. Thank you.
