### ISSUE TITLE
Highlight components that has been visited by change detector triggered by a certain event in development mode

### ISSUE THREAD

**Issue by yuwu9145** [angular/angular#39999]
# 🚀 feature request

### Relevant Package

This feature request is for @angular/core

### Description
Inspired by a [demo](https://pankajparkar.github.io/demystifying-change-detection/#/default-strategy) from this [post](https://medium.com/ngconf/simplified-angular-change-detection-e74809ff804d), it would be very useful to know which components that has been visited by change detector during development & testing.

Especially when developing large-scale application that has many components in one page, developers will be able to verify a certain event only triggers change detection on expected components, which makes it very straightforward to avoid any unnecessary change detections

### Describe the solution you'd like
Visually hightlight the components that has been visited by change detector with an option to enable/disabled based on environment

**Comment by mgechev** [comment]
On EnterpriseNG we announced that we're working on development tooling which includes most of the functionality you described. You can follow the progress [in the roadmap](https://angular.io/guide/roadmap) and check the [keynote video](https://youtu.be/FsNTuzBfLxU?t=1961)
