### ISSUE TITLE
Only I have problems with - router-outlet?

### ISSUE THREAD

**Issue by Vladislav-wn** [angular/angular#40003]
Hi,
Node version - v14.15.1;
NG-version - 11.0.3;

error NG8001: 'router-outlet' is not a known element:
1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

if you do: ng serve  - everything is good.
you make changes to the project - again a mistake.
if you do: ng serve  - everything is good.

**Comment by rohitadittya** [comment]
Hi,
1) If you have added your routes in appRoutingModule.ts, make sure you are exporting them properly in appRoutingModule.ts as exports: [RouterModule] and using it app.module.ts.
2) If you have directly added your routes in app.module.ts, make sure you are not exporting Router Module in exports array in app.module.ts

**Comment by Vladislav-wn** [comment]
I revoke the error. This is not Angular's problem. This is a problem Visual Studio Code. Autosave of changes is enabled and apparently does not save correctly. I disabled autosave. I save the changes manually. Angular works correctly.
