### ISSUE TITLE
App compiles successfully but nothing is rendered after upgrade from Angular 10 to 11

### ISSUE THREAD

**Issue by power-f-GOD** [angular/angular#40019]
# 🐞 bug report

### Affected Package
N/A

### Is this a regression?

 Yes, the previous version in which this bug was not present was v10

### Description

 Basically, the app compiles successfully, but nothing is rendered in the browser and they are no errors whatsoever. :/

## 🔬 Minimal Reproduction
N/A

It's a private repo.

## 🔥 Exception or Error
<pre><code>

None
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.0-next.1
@angular-devkit/build-angular   0.1101.0-next.1
@angular-devkit/core            11.1.0-next.1
@angular-devkit/schematics      11.1.0-next.1
@angular/cdk                    11.0.2
@angular/http                   7.2.16
@angular/material               11.0.2
@schematics/angular             11.1.0-next.1
@schematics/update              0.1101.0-next.1
rxjs                            7.0.0-beta.9
typescript                      4.1.2
</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by power-f-GOD** [comment]
BTW, a fellow teammate 'fixed' this.
The issue was that I had upgraded to *Angular 11.0 Next* (which doesn't seem to render anything after build).
But upgrading (or should I say downgrading) to *Angular 11.0* fixed it.
