### ISSUE TITLE
Estimated Beta or v1.0 Release Date?

### ISSUE THREAD

**Issue by anik786** [angular/angular#4002]
When is the estimated/ targeted beta or v1.0 release date?

Unfortunately the milestones section https://github.com/angular/angular/milestones only show the esitmated dates for the next 2 alphas and there is not any information on how many alpha's there's going to be!

**Comment by mhevery** [comment]
When we feel it is ready. Sorry we don't know either.

**Comment by pavel06081991** [comment]
And how do you feel now? :)
