### ISSUE TITLE
Angular 9 lazy loading components - proper pattern

### ISSUE THREAD

**Issue by directcuteo** [angular/angular#40024]
Hi, I am trying to improve my application using Ivy's lazy loading of components.

**The context**
I have an app where the user can access several views/components in a side panel, but none of them is visible at the beginning. Each of them is personally triggered on a click event.

**My logic**
There is no reason why I should include them in the initial bundle, so I have to load them when the user wants them.
I will create a Module, I won't import it anywhere and I will load the components using the `ComponentFactoryResolver` at the right time (click event).

All good, I use `<ng-template #containerRef></ng-template>` and I inject one component but surprise:
`can't bind ngif since it's not a known property of div...`
After some research I understand that I never imported the module anywhere and the component does not have access not even to the `CommonModule`(neither any module).

**Questions**
1. If I load the module dynamically before the loading of the component, will other components be included in the bundle as well? If yes, then I'm supposed to declare a _non-exported_ module for each lazy component? What's the catch? Doesn't seem to be the proper way.
2. If I load the module in the same function where I load the component, then the module will be loaded again when executing the function again for another click eventt? What's the solution?

I appreciate your guidance!

My dependencies:
```
    "@agm/core": "^3.0.0-beta.0",
    "@angular/animations": "^10.1.4",
    "@angular/cdk": "~10.2.3",
    "@angular/common": "^10.1.4",
    "@angular/compiler": "^10.1.4",
    "@angular/core": "^10.1.4",
    "@angular/forms": "^10.1.4",
    "@angular/material": "~10.2.3",
    "@angular/platform-browser": "^10.1.4",
    "@angular/platform-browser-dynamic": "^10.1.4",
    "@angular/router": "^10.1.4",
    "@reactivex/rxjs": "^6.5.5",
```

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
