### ISSUE TITLE
Transformers should record property metadata

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#4003]
Example

```
class ClassWithDecorators {
  @PropDecorator("p1") @PropDecorator("p2") a;
 
  @PropDecorator("p3")
   set b(value) {}

  @PropDecorator("p4")
   get b { return null;}
}
```

Should create an instance of ReflectionInfo  with propMetadata set to

```
var m = {
  "a": [const PropDecorator("p1"), const PropDecorator("p2")],
  "b": [const PropDecorator("p3"), const PropDecorator("p4")],
};
```

Closes https://github.com/angular/angular/issues/3267 and https://github.com/angular/angular/issues/1800

**Comment by kegluneq** [comment]
I'm currently refactoring the `DirectiveProcessor` step (where this would happen), so once that is in I'll focus on this next. I do not expect it will be committed in time for alpha-38

**Comment by kegluneq** [comment]
@vsavkin , should we register only for `@Component`s? Only for `@Directive`s? Only for `@Injectable`s? Or for any class with annotations on its properties?

**Comment by vsavkin** [comment]
It was merged into master some time ago.
