### ISSUE TITLE
Autoconfigurable bindings for modules and automatic application bootstraping

### ISSUE THREAD

**Issue by alfonso-presa** [angular/angular#4004]
I think the binding mechanism is great and very powerful, but I find it very verbose to configure and also it generates unnecessary coupling between the applications and the framework. It would be great to introduce the ability for the modules to be self configured so that Angular 2 becomes more opinionated, providing some sensible defaults out-of-the-box. I know there are those *binding constants* available like the `ROUTER_BINDINGS` or the `HTTP_BINDINGS`, but they do feel just like shortcuts.

IMHO there should be a mechanism for the modules to get autoconfigured so a http hello world application could look like this:

```typescript
import {Component, View, NgFor, Autoconfigured} from 'angular2/angular2';
import {autobootstrap as main} from 'angular2/angular2';
import {Http, Response} from 'angular2/http';
import {ObservableWrapper} from 'angular2/src/core/facade/async';

@Autoconfigured()
@Component({selector: 'http-app'})
@View({
  directives: [NgFor],
  template: `
    <h1>people</h1>
    <ul class="people">
      <li *ng-for="#person of people">
        hello, {{person['name']}}
      </li>
    </ul>
  `
})
export class HttpCmp {
  people: Object;
  constructor(http: Http) {
    ObservableWrapper.subscribe<Response>(http.get('./people.json'),
                                          res => this.people = res.json());
  }
}

autobootstrap();
```

As you can see, the autoconfiguration eliminates a lot of boilerplate code (in this case allowing to use Http object by just including the http module) and also makes component bootstrapping easier. For the developer, the binding process is completely transparent. Of course the other bootstrapping mechanism with explicit binding is still supported.

ngHttp get's auto configured by default by including the following:

```
@Configuration()
class HttpConfiguration {

	constructor() {}
	
	getBindings() {
		return [
                        HTTP_BINDINGS
		];
	}
}
```

For this to work a Registry will be needed in order to keep track of all the classes implementing annotations. Something like this:

```
export class ReflectRegistry {
  public _annotationRegistry: Map<any, Array<any>> = new Map<any, Array<any>>();
  
  constructor () {};
  
  add (annotation: any, cls: any) : void {
    var annotationList: Array<any> = this._annotationRegistry[annotation] || (this._annotationRegistry[annotation] = []);
    annotationList.push(cls);
  }
  
  getForAnnotation (annotation) : Array<any> {
    return this._annotationRegistry[annotation];
  }
}

export var reflectRegistry: ReflectRegistry = new ReflectRegistry();
```

The `makeDecorator` function in `modules\angular2\src\core\util` should register all the annotations and the classes annotated inside that object.

During the application's bootstrapping process angular should check the registry and get the bindings of all the configuration classes joining them
 in priority order.

The application itself, or some third party module/framework/tooling, can add more configuration classes to override the defaulted bindings when needed.

It might be useful also to have some `@Conditional` or some `@Profile` annotation to make those configuration classes be taken into account or not depending on the environment. For example this might be useful to change the bindings depending on the device/browser capabilities (i.e. touch screen, resolution, CORS support, etc.). 

This not only leads to an easier to use module system (plug&play... or import&play ) but also at the end it enables automatic bootstrapping of the application as the bindings can automatically be loaded and it's also possible to annotate the "main" component of the application with another annotation (i.e. `@Main`), get it from the registry and bootstrap it automatically.

Please let me know what you think. I truly don't know every detail of Angular 2's source code or it's road-map, so I  might be missing something when writing this feature request. If so, please, don't hesitate letting me know and also excuse me.

If you think my proposal can be useful I can try to build it and PR.

**Comment by alfonso-presa** [comment]
As I think a line of code is worth a hundred words, I've decided to implement it in [my own fork](https://github.com/alfonso-presa/angular/tree/AutoConfiguration) and it's working very nicely.

This is the code of the http sample using the autoconfiguration:

```typescript
import {Component, View, NgFor, Autoconfigured} from 'angular2/angular2';
export {autobootstrap as main} from 'angular2/angular2';
import {Http, Response} from 'angular2/http';
import {ObservableWrapper} from 'angular2/src/core/facade/async';

@Autoconfigured()
@Component({selector: 'http-app'})
@View({
  directives: [NgFor],
  template: `
    <h1>people</h1>
    <ul class="people">
      <li *ng-for="#person of people">
        hello, {{person['name']}}
      </li>
    </ul>
  `
})
export class HttpCmp {
  people: Object;
  constructor(http: Http) {
    ObservableWrapper.subscribe<Response>(http.get('./people.json'),
                                          res => this.people = res.json());
  }
}
```

As you can see, the autoconfiguration eliminates a lot of boilerplate code (in this case allowing to use Http object by just including the http module) and also makes component bootstrapping easier. For the developer, the binding process is completely transparent. Of course the other bootstrapping mechanism with explicit binding is still supported.

I've implemented it also for dart using mirrors

**Comment by mhevery** [comment]
Will not implement, since this prevents Code generation feature.
