### ISSUE TITLE
Feature Request: async pipe optionally keeps latest value of former observable until first value of new observable arrives

### ISSUE THREAD

**Issue by matze1234** [angular/angular#40042]
# 🚀 feature request

 This feature request is for @angular/common/AsyncPipe

### Description
When i use the async pipe within a template and the referenced observable changes (e.g. due to some ngOnChanges() code), sometimes it would be nice if the template expression would keep the last value of the former observable, until it receives the 1st value of the new observable, to avoid a flickering user experience.

### Describe the solution you'd like
A solution might be an additional parameter to enable the described behavior.
`myArray | async : true`

within async pipe:
`transform<T>(obj: ..., fallbackToFormerValue?: boolean)`

**Comment by lazarljubenovic** [comment]
If I understand your use-case correctly, this sounds way too specific to be included in `@angular/common` (i.e. not common at all). Also `: true` is not really a good way to name this feature, as it's impossible to know what it does just by looking at the usage site.

**Comment by AndrewKushnir** [comment]
Hi @matze1234, thanks for submitting a feature request. I believe the behavior that you described is specific to the use-case and you can achieve it by creating a custom pipe based on the existing [AsyncPipe](https://github.com/angular/angular/blob/master/packages/common/src/pipes/async_pipe.ts). More information on creating custom pipes can be found [here](https://angular.io/guide/pipes#creating-pipes-for-custom-data-transformations). Thank you.
