### ISSUE TITLE
Angular dynamic components issue in production mode (Aot)

### ISSUE THREAD

**Issue by aliBlaybel** [angular/angular#40043]
Dears,

we have to compile and load Dynamic Components… works in dev but in production mode (AOT enabled) we get the error “**template must be a string**”.

“@angular/core”: “~9.1.6”,

```
@Component({
 template: componentTemplate,
 selector: templateDef.name,
 })
 class TemplateComponent extends DynamicUiBaseComponent implements OnInit {
 
 ngOnInit() {
 super.ngOnInit();
 }
 }
....
this.compiler.compileModuleAndAllComponentsSync(DynamicModule);

```

**Comment by mlc-mlapis** [comment]
@aliBlaybel You can't because you need to inject JitCompiler first to do such things. This theme is discussed many times here, so look around for more detailed explanations and what to do.

**Comment by JoostK** [comment]
You'll have to either set `jit: true` in the decorator to preclude it from AOT compilation, or use the decorator as a function:

```ts
@Component({
  template: componentTemplate,
  selector: templateDef.name,
  jit: true,
})
class TemplateComponent extends DynamicUiBaseComponent implements OnInit {
}
```

or

```ts
class TemplateComponent extends DynamicUiBaseComponent implements OnInit {
}

Component({
  template: componentTemplate,
  selector: templateDef.name,
})(TemplateComponent);
```

**Comment by JoostK** [comment]
I'll go ahead and close this as there doesn't appear to be an issue with the framework. Feel free to continue the discussion below.
