### ISSUE TITLE
Async validators do not output errors when sync validators do

### ISSUE THREAD

**Issue by blidblid** [angular/angular#40041]
# 🐞 bug report

### Affected Package
`"@angular/forms": "^11.0.0"`

### Is this a regression?
No.

### Description
When validating a `FormControl`, if there is a mix of sync validators and async validators, the resulting error object `FormControl.errors` will not contain the async error if there are sync errors present. For example, with a setup of

```typescript
  formControl = new FormControl(
    "",
    [Validators.minLength(5), Validators.min(100)],
    () => of({ actual: "async error",  expected: "no async error" })
  );
```

and 

```html
  <input [formControl]="formControl">
```

the error `{ actual: "async error",  expected: "no async error" }` will only be present if all sync validators return `null`.

The same issue applies for a combination of `NG_VALIDATORS` and `NG_ASYNC_VALIDATORS`.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-qzjboy?file=src%2Fapp%2Fapp.component.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.3
Node: 14.15.0
OS: win32 x64

Angular: 11.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.3
@angular-devkit/build-angular   0.1100.3
@angular-devkit/core            11.0.3
@angular-devkit/schematics      11.0.3
@angular/cdk                    11.0.2
@angular/material               11.0.2
@schematics/angular             11.0.3
@schematics/update              0.1100.3
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Comment by petebacondarwin** [comment]
This is by design and documented. See https://angular.io/guide/form-validation#creating-asynchronous-validators

> Asynchronous validation happens after the synchronous validation, and is performed only if the synchronous validation is successful. This check allows forms to avoid potentially expensive async validation processes (such as an HTTP request) if the more basic validation methods have already found invalid input.
