### ISSUE TITLE
Angular 9 Error “NullInjectorError: No provider for Router!”

### ISSUE THREAD

**Issue by nchetbani** [angular/angular#40046]
I’ve got a published library containing a component that uses [routerLink] in it’s template.
With Angular **8.2.14** all work fine after installing the library in my application. But with Angular **9.1.12**, I get the error **NullInjectorError: R3InjectorError(AppModule)[Router -> Router -> Router]:
NullInjectorError: No provider for Router!**

Within the module in the library the RouterModule is imported and looks like this:

```
@NgModule({
  declarations: [
    Component
  ],
  exports: [
    Component
  ],
  imports: [
    CommonModule,
    RouterModule,
    ...
  ]
})
export class LibWithComponentModule {
}
```

Within my application, the RouterModule is configured as follows:

```
const routes: Routes = [{
  path: '',
  component: RootComponent
}];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }

The app.module.ts looks like this:
```

```
declarations: [
    AppComponent,
    RootComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    LibWithComponentModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

But I thought the RouterModule is going to be provided? What am I doing wrong?

For information I'm using the **ng-packgr** library to generate the library

**Comment by lazarljubenovic** [comment]
This is neither a bug report or feature request. This GitHub issue tracker is not suitable for support requests. Please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.
