### ISSUE TITLE
Cannot update @angular/common integrity checksum failed

### ISSUE THREAD

**Issue by iulianmarius** [angular/angular#40057]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

npm update @angular/common
npm ERR! code EINTEGRITY
npm ERR! sha512-4R2ALj71J6EAHVCKNnHHCKL7wcosMsv3gcMXbMTE+Wpzo3khEhM0Tej+I1qmMbVmGXVlRb//4+rjE4gff6FvQw== integrity checksum failed when using sha512: wanted sha512-4R2ALj71J6EAHVCKNnHHCKL7wcosMsv3gcMXbMTE+Wpzo3khEhM0Tej+I1qmMbVmGXVlRb//4+rjE4gff6FvQw== but got sha512-58efdRw08MJTDwhNN/fy8ePcosHc0UytSKSwFo8fSZTfrcLtljVif6u/sHnJEC6x33ds5/4YbwRCefks8oqhRw==. (1391057 bytes)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

 Angular CLI: 11.0.3
Node: 12.16.3
OS: win32 x64

Angular: 11.0.4
... animations, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.3
@angular-devkit/build-angular   0.1100.3
@angular-devkit/core            11.0.3
@angular-devkit/schematics      11.0.3
@angular/cdk                    11.0.2
@angular/cli                    11.0.3
@angular/common                 11.0.2
@angular/flex-layout            11.0.0-beta.33
@angular/material               11.0.2
@schematics/angular             11.0.3
@schematics/update              0.1100.3
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular.

Please try to verify that the NPM cache is not corrupted by running the below:

```
npm cache verify 
```

If the problem persist after running the above remove your package-lock file.

```
rm -f package-lock.json
```

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
