### ISSUE TITLE
How to update angular 8 to 11

### ISSUE THREAD

**Issue by anhtuan96a8** [angular/angular#40076]
Can anyone help me? I have updated angular 8 to 9 and it has 1 bug that I cannot fix. Thank you so much.
![image](https://user-images.githubusercontent.com/23031958/101849697-d204fd00-3b8a-11eb-8d88-afbc364ca362.png)
![image](https://user-images.githubusercontent.com/23031958/101849711-d7fade00-3b8a-11eb-8c73-806e017352af.png)

**Comment by trungvoq** [comment]
Add config: baseUrl, exclude, types, typeRoots

**Comment by anirugu** [comment]
Will creating a new project in angular11 and  replace this file will work?. I see the file much similar to the one I have for angular 11 project.

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
