### ISSUE TITLE
Angular 10 Deploy Issue

### ISSUE THREAD

**Issue by kursatsaka** [angular/angular#40073]
I updated my angular project from angular6 to angular10. I can serve, build and prod build my project just fine. There is no error when I serve the project in my local. When i deploy the project there is no error on console but the screen is blank. Thanks for your help.

Screenshot: 
![Capture](https://user-images.githubusercontent.com/47352541/101814929-d8b25680-3b2f-11eb-9ee6-e52b35a765fb.PNG)

**Comment by petebacondarwin** [comment]
It appears from your screenshot that there is indeed an error in the console related to rxjs. I wonder if you need to check your dependencies.

In any case having reviewed this issue, it doesn't appear to fall into the bug report or feature request category.
This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
