### ISSUE TITLE
Using indexedDB for data storage in service worker

### ISSUE THREAD

**Issue by ishaqueahmed-mev** [angular/angular#40079]
Hello all,

**I have been using @angular/pwa for making app work in offine mode and made my own required changes in ngsw.json file and its working absolutely fine. One thing I noticed in browser and in ngsw-worker file in dist that it uses cachestorage for storing data. What I need to know is, is there any way I could change my data storage from cache to indexedDb? Is there any way I could make it work with indexedDB. I have checeked various blogs and tutorials, but wasn't able to find anything relatable for implementing the same in angular.**

Any help would be very much helpful :)

Thanks.

**Comment by gkalpak** [comment]
Hi, @ishaqueahmed-mev!

The Angular ServiceWorker does indeed use `CacheStorage` (which is more suitable for caching reponses). It is not possible to switch to `IndexedDB` (unless you modify the `ngsw-worker.js` script and create your own SW script).

OOC, why do you want to use `IndexedDB`?

<sub>(I am going to close the issue, but feel free to continue the discussion below.)</sub>

**Comment by ishaqueahmed-mev** [comment]
@**gkalpak** thanks for the quick response, and sorry for the late reply.

Its my requirement for an project to store data in `indexedDb` as data length could be larger, though I can still go through `cachestorage` if that doesn't works.

Also can you guide me through as to how would I proceed, if possible, to manipulate `ngsw-worker.js` script to manage storage through `indexedDb`?


Thanks.

**Comment by gkalpak** [comment]
> Its my requirement for an project to store data in `indexedDb` as data length could be larger

From what I understand (e.g. by reading resources such as [this one][1]), `IndexedDB` and `CacheStorage` share the same storage quota. So, I don't think there is any benefit in using `IndexedDB` over `CacheStorage` wrt to size limitations (but I could be wrong).

##
> Also can you guide me through as to how would I proceed to manipulate `ngsw-worker.js` script to manage storage through `indexedDb`?

I'm there is not specific guidance to offer here 😅
The process would be to go through the SW script, find all places where `CacheStorage` APIs are used and re-write the logic to use `IndexedDB`. This is not a trivial undertaking, though, and I definitely do not recommend doing it. `CacheStorage` is specifically designed for caching responses and replicating the same functionality with a low-level API such as `IndexedDB` won't be easy.

[1]: https://web.dev/storage-for-the-web

**Comment by ishaqueahmed-mev** [comment]
**@gkalpak**, thanks for your response :+1:
