### ISSUE TITLE
Service Worker does not update

### ISSUE THREAD

**Issue by guimaraesSalgado** [angular/angular#40070]
I'm always getting this error and I don't know why, nor where to fix it, when debugging ngsw-worker.json, I noticed that it is always hash error similar to this image, how to fix it?

Driver state: EXISTING_CLIENTS_ONLY (Degraded due to failed initialization: Hash mismatch (cacheBustedFetchFromNetwork): https://web.com.br/14-es2015.6806b9c668313a11cde0.js: expected 349c6ced18fc268ba4dd20de5ce154ede22fabcb, got bc1a96f58626b312d0e28fca0b1be7a00c9a5350 (after cache busting)
Error: Hash mismatch (cacheBustedFetchFromNetwork): https://web.com.br/14-es2015.6806b9c668313a11cde0.js: expected 349c6ced18fc268ba4dd20de5ce154ede22fabcb, got bc1a96f58626b312d0e28fca0b1be7a00c9a5350 (after cache busting)
    at PrefetchAssetGroup.<anonymous> (https://web.com.br/ngsw-worker.js:699:35)
    at Generator.next (<anonymous>)
    at fulfilled (https://web.com.br/ngsw-worker.js:320:62))
Latest manifest hash: a8946d0d38ec74561d50d3d469db70b776215549
Last update check: 35m19s796u

=== Version a8946d0d38ec74561d50d3d469db70b776215549 ===

Clients: 

**=== Idle Task Queue ===
Last update tick: 9u
Last update run: 35m22s647u
Task queue:**

my ngsw.json
![image](https://user-images.githubusercontent.com/49767698/101820053-d25ab500-3b04-11eb-8881-ffd6c6883937.png)

my config 
![image](https://user-images.githubusercontent.com/49767698/101820105-e999a280-3b04-11eb-926f-ad91bf0ae34b.png)

**Comment by gkalpak** [comment]
@guimaraesSalgado, there is nothing more to say than what has already been discussed in #40049. Please see https://github.com/angular/angular/issues/40049#issuecomment-742578878 for some suggestions.

If you need more help, you can reach out on our [general support channels][1].

Note that this issue tracker is not suitable for support requests. If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation][2].

[1]: https://github.com/angular/angular/blob/d39d64c15dcba74aa673cacfc1365bd35a1d4f95/CONTRIBUTING.md#question
[2]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem
