### ISSUE TITLE
Support events containing - in the event name

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#4007]
Say we have this directive:

```
@Directive({
  selector: 'my-dir',
  events: ['event: el-event']
})
class MyDirective {
  event = new EventEmitter();
}
```

The following should work `<my-dir (el-event)="doStuff()">`, but it does not. Currently, I have to specify the element event name as follows: `events: ['event: elEvent']`.

**Comment by pkozlowski-opensource** [comment]
Related: https://github.com/angular/angular/issues/2600

**Comment by pkozlowski-opensource** [comment]
It is solved now that we've got our own HTML parser.
