### ISSUE TITLE
HttpIntercept issues after run npm link

### ISSUE THREAD

**Issue by JulioCesGO** [angular/angular#40083]
Hi ,
I have a lib that contains an class `HttpInterceptor`. After performing the procedure with the npm link, from this lib to my project, the entire request that passes in `event instanceof HttpResponse` returns false. When I run a `console.log (event)`, it returns an object of type `HttpResponse`.

```
@Injectable()
export class LoadingHttpInterceptor implements HttpInterceptor {

    intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {

        LoadingService.show();
        return next.handle(req).pipe(
            tap( (event: HttpEvent<any>) => {
                if (event instanceof HttpResponse){
                    LoadingService.hide();      
                }                
            }),
            catchError(error => {
                LoadingService.hide();
                return throwError(event);
            })
        );
    }
}
```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

The link will likely result in pulling in a duplicates of dependencies, as resolved from the linked directory. You can probably avoid this [using `preserveSymlinks`](https://github.com/angular/angular-cli/issues/10896#issuecomment-389936048).
