### ISSUE TITLE
Language service optional chaining + generics + null loses typing

### ISSUE THREAD

**Issue by antoinebrault** [angular/angular#40085]
# 🐞 bug report

### Affected Package
@angular/language-service 10.x 11.x

### Is this a regression?
Not sure if this affects previous versions. I've seen it in 10 and 11.

### Description
Language service loses the type when used with generics and null in optional chaining. I added a screenshot from WebStorm.

## 🔬 Minimal Reproduction
```typescript
interface ObjectType {
  prop: string;
}
interface StateGenericWithNull<T> {
  object?: T | null;
}
interface StateGeneric<T> {
  object?: T;
}
interface StateWithNull {
  object?: ObjectType | null;
}
interface State {
  object?: ObjectType;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  stateGenericWithNull: StateGenericWithNull<ObjectType> = {};
  stateGeneric: StateGeneric<ObjectType> = {};
  stateWithNull: StateWithNull = {};
  state: State = {};
}
```
```html
{{ stateGenericWithNull.object?.prop }}
{{ stateGenericWithNull.object.prop }}

{{ stateGeneric.object?.prop }}
{{ stateGeneric.object.prop }}

{{ stateWithNull.object?.prop }}
{{ stateWithNull.object.prop }}

{{ state.object?.prop }}
{{ state.object.prop }}
```
![image](https://user-images.githubusercontent.com/852552/101922983-d1756200-3b9c-11eb-814f-03ce319972c7.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.4
@angular-devkit/build-angular   0.1100.4
@angular-devkit/core            11.0.4
@angular-devkit/schematics      11.0.4
@schematics/angular             11.0.4
@schematics/update              0.1100.4
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by JoostK** [comment]
AFAIK WebStorm does not use `@angular/language-service`, JetBrains has fairly advanced code analysis themselves.
