### ISSUE TITLE
DI should support custom error messages

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#4008]
I should be able to do the following:

```
var INCLUDE_MODULE_ERROR = "Did you include my module? See here...."
class MyDirective {
  constructor(@NoBindingErrorMessage(INCLUDE_MODULE_ERROR) s:MyDependency)
}
```

When DI cannot find MyDependency, it will throw a meaningful message, asking, for instance, to include some module.

I don't expect this to be used by app developers, but this can be very useful for libraries and frameworks.

cc @IgorMinar @mhevery

**Comment by mhevery** [comment]
Will not implement.
