### ISSUE TITLE
Use ngDevMode to tree shake error messages in pipes

### ISSUE THREAD

**Issue by dev054** [angular/angular#40096]
# 🚀 feature request

### Description
Currently all the errors throwed by pipes are not being tree-shaked in production mode.

### Relevant Package
`@angular/common/(pipes)`

Example:
https://github.com/angular/angular/blob/884f743baa667ee5b62d67c3fb9dabab1b03d2d8/packages/common/src/pipes/case_conversion_pipes.ts#L37-L39

### Describe the solution you'd like
I have seen that you made a lot of progress with `ngDevMode`, so I think it would be a case of using it for the purpose of making the package smaller.

**Comment by alan-agius4** [comment]
I don’t think these errors should be removed when not ngDevMode is false.

Data can be non statically analysable such as from an API. In which case invalid value type should result in a meaningful and actionable errors.

Although it does feel weird that we allow `undefined` as an input just to throw that it’s an invalid value. Maybe this is for compatibility reasons?

**Comment by dev054** [comment]
> I don’t think these errors should be removed when not ngDevMode is false.

@alan-agius4 Hmm, would you mind to share how do you decide an error message should be thrown in production mode or not? I'm asking it to understand as I saw `ngDevMode` being used in many places in `@angular/router`.

> Although it does feel weird that we allow `undefined` as an input just to throw that it’s an invalid value. Maybe this is for compatibility reasons?

Maybe. I also found it strange (because even the `async pipe` which could be a problem, doesn't return `undefined`, but `null`), and I noticed that it was added in https://github.com/angular/angular/pull/37447.

**Comment by lazarljubenovic** [comment]
> Data can be non statically analysable such as from an API. In which case invalid value type should result in a meaningful and actionable errors.

I thought Ivy now propery checks the type of pipes? 

https://github.com/angular/angular/blob/884f743baa667ee5b62d67c3fb9dabab1b03d2d8/packages/common/src/pipes/case_conversion_pipes.ts#L32-L35

The function will already scream at you during compilation for passing a wrong argument type.

**Comment by alan-agius4** [comment]
In this particular case `undefined` is a valid argument type, but when passed it causes a runtime exception.

**Comment by alan-agius4** [comment]
Actually never mind, I just noticed that it’s `value == null` and not `value === null`.

So you are right 😊

**Comment by AndrewKushnir** [comment]
I think it should be safe to tree-shake away this error in prod mode (in all pipes within the `case_conversion_pipes.ts` script).

@ramthir this looks similar to other changes you made recently. Please let us know if you might be interested in helping with this code?

**Comment by ramthir** [comment]
> I think it should be safe to tree-shake away this error in prod mode (in all pipes within the `case_conversion_pipes.ts` script).
> 
> @ramthir this looks similar to other changes you made recently. Please let us know if you might be interested in helping with this code?

Great @AndrewKushnir, I'll raise a PR on this. 👍
