### ISSUE TITLE
Router shallowEqual util throws error in IE

### ISSUE THREAD

**Issue by agale123** [angular/angular#40090]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 No

### Description

I can't get this to reproduce locally, but our logs show that users using IE and Edge are getting an error message of "Object expected" on line [29 of collection.ts](https://github.com/angular/angular/blob/master/packages/router/src/utils/collection.ts#L29). This indicates that the second object being passed into the shallowEqual is not an object. The call is coming from [updateSegmentGroup](https://source.corp.google.com/piper///depot/google3/third_party/javascript/angular2/rc/packages/router/src/create_url_tree.ts;l=197?q=updateSegmentGroupChildren&ct=os&sq=package:piper%20file:%2F%2Fdepot%2Fgoogle3%20-file:google3%2Fexperimental) which calls prefixedWith which calls shallowEqual. It seems like additional checks in compare to ensure that the two objects being passed to shallowEqual are in fact objects should resolve this issue.

## 🔬 Minimal Reproduction

 The errors are from logs so I don't have a reliable way to reproduce the issue, but we are seeing many reports of this error.

## 🔥 Exception or Error
<pre><code>

Object expected
</code></pre>

## 🌍  Your Environment

**Angular Version:**
We run with the latest version of Angular. The errors from today were probably cut from an Angular version a week or two ago.

**Anything else relevant?**
This only occurs in Edge and IE as far as we can tell.

**Comment by crisbeto** [comment]
I looked into it and while the quick and easy fix would be to add a couple of null checks to `shallowEqual`, I'm wondering whether this doesn't indicate a different issue somewhere else in the router. Working my way backwards from the `compare` function, I think the error will be thrown if the `path` [passed in here](https://github.com/angular/angular/blob/master/packages/router/src/create_url_tree.ts#L272) doesn't have a `parameters` value. The `parameters` are required in the `UrlSegment` constructor, but there's nothing stopping somebody from doing `new UrlSegment('/', null!)`. Do you happen to have places in your app where `UrlSegment` is constructed manually?

**Comment by agale123** [comment]
I just checked our codebase and there are only two places that manually construct a UrlSegment and one directly passes {} as the second argument and the other passes an object that is constructed immediately before it is passed to UrlSegment. I feel like there might be some weird edge case or race condition where the UrlSegment is getting constructed will null, but I couldn't find any obvious patterns between which of our URLs are hitting this error.
