### ISSUE TITLE
ng-required overrides type=email initial validation in chrome

### ISSUE THREAD

**Issue by tompi** [angular/angular#401]
Details in the plnkr:

http://plnkr.co/edit/1iphMDUloBtUQJ4vHxdz?p=preview

It seems since 1.3.4, ngmodel set from controller, will not get ng-invalid initially if I use both type=email and ng-required in latest chrome. works fine in firefox, or with just required attribute.

**Comment by pkozlowski-opensource** [comment]
Wrong repo: https://github.com/angular/angular.js
