### ISSUE TITLE
Exception in abstract_change_detector is masking real exception in onInit method

### ISSUE THREAD

**Issue by vikerman** [angular/angular#4010]
Alpha 36:

We have a test component that loads the Angular 2 component under test. However the test component had a bug in it's onInit lifecycle callback handler. However this was completely masked by another exception within Angular 2 in the abstract_change_detector code. We are left with an exception that's not useful.

The following is the stack trace that is actually displayed in the browser console  - 

[dart:core                                                                   List.[]
package:angular2/src/change_detection/abstract_change_detector.dart 297:31  AbstractChangeDetector._currentBinding
package:angular2/src/change_detection/abstract_change_detector.dart 281:14  AbstractChangeDetector._throwError
package:angular2/src/change_detection/abstract_change_detector.dart 123:12  AbstractChangeDetector.detectChangesInRecords
package:angular2/src/change_detection/abstract_change_detector.dart 98:10   AbstractChangeDetector.runDetectChanges
package:angular2/src/change_detection/abstract_change_detector.dart 89:10   AbstractChangeDetector.detectChanges
package:angular2/src/core/life_cycle/life_cycle.dart 78:28                  LifeCycle.tick
package:xxx.xxxx.xxxx.xxxx.xxxx_xxxx/xxxx.dart 34:16            Angular2ManagedZone.capturedTurnDone
dart:async                                                                  _ZoneDelegate.run
package:angular2/src/core/zone/ng_zone.dart 216:20                          NgZone._run

Setting a breakpoint in _throwError I can see that the stack this going to be printed which is pretty useful.

> e_stack.toString()
"#0      List.first (dart:core-patch/growable_array.dart:207)
#1      QueryList.first (package:angular2/src/core/compiler/query_list.dart:108:27)
#2      ComponentTest.onInit (-----:155:39) ---------------------------------> Bug is here but got masked.
#3      DynamicChangeDetector.detectChangesInRecordsInternal (package:angular2/src/change_detection/dynamic_change_detector.dart:125:65)
#4      AbstractChangeDetector.detectChangesInRecords (package:angular2/src/change_detection/abstract_change_detector.dart:121:12)
#5      AbstractChangeDetector.runDetectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:98:10)
#6      AbstractChangeDetector.detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:89:10)
#7      LifeCycle.tick (package:angular2/src/core/life_cycle/life_cycle.dart:78:28)
#8      Angular2ManagedZone.capturedTurnDone (package:xxxx.dart:34:16)
#9      _rootRun (dart:async/zone.dart:904)
#10     _ZoneDelegate.run (dart:async/zone.dart:503)
#11     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:216:20)
#12     _CustomZone.run (dart:async/zone.dart:803)
#13     _CustomZone.runGuarded (dart:async/zone.dart:709)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#16     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#17     _ScheduleImmediateHelper._handleMutation (dart:html:42567)
"

**Comment by IgorMinar** [comment]
I can take a look at this next week if @vsavkin doesn't beat me to it.

**Comment by binarious** [comment]
Same here. Any news on this?

**Comment by mhevery** [comment]
this should be fixed in the latest compiler. Closing.
