### ISSUE TITLE
schematic for waitforasync not taking effect?

### ISSUE THREAD

**Issue by EvtK** [angular/angular#40100]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?
No, it's a schematic for 11 migration

### Description
As I understand correctly, the added migration in this PR: https://github.com/angular/angular/pull/39212 should replace async with waitForAsync. I have a ton of spec files lined up like this:

```
import { async, TestBed } from '@angular/core/testing';
describe('@myApp, () => {
  describe('AppComponent', () => {
    beforeEach(async(() => {
      TestBed.configureTestingModule({
        imports: [TestHostModule],
      }).compileComponents();
    }));

```
I do get the deprecation warning for the use of async. But the schematic is not taking effect.

I have tried to figure out why it is not happening. The file seems to be loaded by the schematic, but it never validates this:

```
      if (!asyncImportSpecifier || !asyncImport) {
        return;
      }

```

as being false. The typescript helper function 'getImportSpecifier' simply always returns false on: "node.moduleSpecifier.text === moduleName"

## 🌍  Your Environment
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1100.4
@angular-devkit/core            10.1.7
@angular-devkit/schematics      11.0.4
@angular/localize               10.1.3
@schematics/angular             11.0.4
@schematics/update              0.1100.4
rxjs                            6.5.5
typescript                      4.0.3

**Comment by crisbeto** [comment]
I just gave it a quick try on a new CLI project created at v10.2.0 and updated to v11.0.0 using `ng update @angular/core` and it worked as expected. I also used a similar code snippet to the one you posted above:

![app component spec ts_(Working_Tree)_-_schematic-t_2020-12-13_09-53-07](https://user-images.githubusercontent.com/4450522/102007395-15956d80-3d29-11eb-987e-18fccfce6093.png)

One thing I noticed was that the snippet above has a syntax error (missing quote after `@myApp`). Could that be the issue?

Since you mentioned that you had been debugging it, what does the `node.moduleSpecifier.text` look like for you at runtime?

**Comment by EvtK** [comment]
@crisbeto thanks for checking in. That missing quote you are seeing is a typo, sorry. I removed the name of test since I do not want to disclose any corporate info :).

so, here is a snippet of what the .text looks like at runtime.

```
@ngrx/store
@ngrx/store-devtools
@nrwl/angular
../environments/environment
./app-routing.module
./app.component
./app.constants
./app.initializers
./app.types
@angular/core
@angular/platform-browser-dynamic
./app/app.module
./environments/environment
core-js/features/array/includes
core-js/features/object/entries
zone.js/dist/zone
```

I'm starting to wonder if the schematic is somehow exclude spec files. Just for the sake of complete-ness: we are running a NX repo, and the migration is triggered with the NX tooling. I might as well open up an issue at there side? Maybe the context provided for this schematic is not the right one?

```
{
  "migrations": [
    {
      "version": "11.0.0-beta",
      "description": "`async` to `waitForAsync` migration. The `async` testing function has been renamed to `waitForAsync` to avoid confusion with the native `async` keyword.",
      "factory": "./migrations/wait-for-async/index",
      "package": "@angular/core",
      "name": "migration-v11-wait-for-async"
    }
  ]
}
```

**Comment by crisbeto** [comment]
The configuration above seems correct. I think you might be onto something about test files being excluded somehow. We determine whether a file should be migrated by looking for a `tsconfig.json` and creating a compiler program from it. Do you happen to have something like `excludes: ["**/*.spec.ts"]` in a `tsconfig` somewhere?

**Comment by EvtK** [comment]
ah, that's interesting. Every lib in our repo has a tsconfig.lib.json file which excludes the spec files. Here is a typical setup:

```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../../../dist/out-tsc",
    "target": "es2015",
    "declaration": true,
    "inlineSources": true,
    "types": [],
    "lib": [
      "dom",
      "es2018"
    ]
  },
  "angularCompilerOptions": {
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "enableResourceInlining": true
  },
  "exclude": [
    "src/test-setup.ts",
    "**/*.spec.ts"
  ],
  "include": [
    "**/*.ts"
  ]
}
```

other than this no exclusion of spec files.

could this be the issue?

**Comment by crisbeto** [comment]
It's definitely worth trying to remove it and running the migration again. If we can confirm that this is the issue, I can add something to the schematic to handle it.

**Comment by EvtK** [comment]
changing the tsconfig to include the spec file did not fix it sadly. I'm now thinking it might be related to the nx setup. I have just scaffold a fresh angular NX workspace with `npx create-nx-workspace@latest` and then changed the spec file of the generated app (I called it 'sample') to include the async import:

```
import { async, TestBed } from '@angular/core/testing';
import { AppComponent } from './app.component';

describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [AppComponent],
    }).compileComponents();
  }));

  it('should create the app', () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.componentInstance;
    expect(app).toBeTruthy();
  });

  it(`should have as title 'sample'`, () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.componentInstance;
    expect(app.title).toEqual('sample');
  });

  it('should render title', () => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const compiled = fixture.nativeElement;
    expect(compiled.querySelector('h1').textContent).toContain(
      'Welcome to sample!'
    );
  });
});

```

then running the migrations again, did not convert it to the waitForAsync. Can you confirm this on your side, very curious about this :)

**Comment by crisbeto** [comment]
Sorry for the delayed response. I just gave it a try, but I'm getting some unrelated error. Looking at your last comment, maybe creating the NX project at the `latest` version is already at v11 so the migration doesn't run? I believe it's currently set up to run when you're going from a lower version to 11.

**Comment by EvtK** [comment]
No worries mate. Already glad you are on this :).

So I have performed the migration starting from a v10 -> v11 version. No difference. I decided to log what's inside the 'allPaths' in the async migration.

```
Running migration migration-v11-wait-for-async
[ 'apps/sample/tsconfig.app.json' ]
Successfully finished migration-v11-wait-for-async
```

so we are definitely seeing here that the spec file is not picked up! And I found the reason for this as well. 

NX doesn't include the tsconfig test path in the test target:

```
"test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "apps/sample/jest.config.js",
            "passWithNoTests": true
          },
          "outputs": [
            "coverage/apps/sample"
          ]
        }
```

as soon as I add `          "tsConfig": "apps/sample/tsconfig.spec.json" ` to this configuration, the spec files are in fasted picked up and the migration is run for the spec files.


```
Running migration migration-v11-wait-for-async
[ 'apps/sample/tsconfig.spec.json' ]
[ 'apps/sample/tsconfig.app.json', 'apps/sample/tsconfig.spec.json' ]
Successfully finished migration-v11-wait-for-async
```

I'm not sure it this address should be addressed at the angular team or the NX team, so I will open up an issue on the NX tracker as well.

**Comment by crisbeto** [comment]
Looks like the related issue will be resolved in Nx so I'll close the issue. Thank you for taking the time to investigate it!
