### ISSUE TITLE
Better error detection for components used in app-routing.module.ts but not registered in app.module.ts

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular#40119]
I did a write up here: 
https://fireflysemantics.medium.com/the-pipe-async-could-not-be-found-a42f8eb1b12d

**Comment by lazarljubenovic** [comment]
> Also the application will compile and render fine without any warnings.

Even in production?

**Comment by AndrewKushnir** [comment]
This issue looks like a duplicate of #17446, so I'm closing this one in favor of #17446.

**Comment by fireflysemantics** [comment]
> > Also the application will compile and render fine without any warnings.
> 
> Even in production?

I did not try running a `--prod` build.  It's mostly a development environment issue that's hard to detect.  Also if the issue is corrected by  updating `app.module.ts` with the component declaration, the build server needs to be stopped and started again for the issue to correct itself.  Otherwise the error will still show in the browser.

**Comment by JoostK** [comment]
I believe this would report an error when AOT is enabled (without necessarily needing `--prod`). The issue that a restart is needed is due a current limitation in the CLI's Webpack integration, which is tracked in #39431.
