### ISSUE TITLE
$localize tagged template fails in library production build (ViewEngine)

### ISSUE THREAD

**Issue by klemenoslaj** [angular/angular#40128]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler or @angular/compiler-cli (guessing)

### Is this a regression?

Unlikely.

### Description

Adding the `@angular/localize/init` import to the library entry file enables the usage of `$localize` to translate the text in TypeScript source code.
The build succeeds, unless the `$localize` is used in the providers:

```TS
providers: [{ provide: 'example', useValue: $localize`Translated` }],
```

## 🔬 Minimal Reproduction

- checkout: https://github.com/klemenoslaj/library-localize-failure
- install dependencies (yarn)
- execute `ng build library --prod`

> NOTE: if we execute `ng build library` (Ivy) the error will not be thrown

## 🔥 Exception or Error
<pre><code>
ERROR: <absolute-path>/projects/library/src/lib/library.module.ts:4:1: Error encountered in metadata generated for exported symbol 'LibraryModule': 
 <absolute-path>/projects/library/src/lib/library.module.ts:7:47: Metadata collected contains an error that will be reported at runtime: Tagged template expressions are not supported in metadata.
  {"__symbolic":"error","message":"Tagged template expressions are not supported in metadata","line":6,"character":46}
An unhandled exception occurred: <absolute-path>/projects/library/src/lib/library.module.ts:4:1: Error encountered in metadata generated for exported symbol 'LibraryModule': 
 <absolute-path>/projects/library/src/lib/library.module.ts:7:47: Metadata collected contains an error that will be reported at runtime: Tagged template expressions are not supported in metadata.
  {"__symbolic":"error","message":"Tagged template expressions are not supported in metadata","line":6,"character":46}
See "/private/var/folders/6z/77kchyrx2wz7898g96g0jxf0vwwy9k/T/ng-5deZ0E/angular-errors.log" for further details.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.4
Node: 14.15.0
OS: darwin x64

Angular: 11.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.4
@angular-devkit/build-angular   0.1100.4
@angular-devkit/core            11.0.4
@angular-devkit/schematics      11.0.4
@schematics/angular             11.0.4
@schematics/update              0.1100.4
ng-packagr                      11.0.3
rxjs                            6.6.3
</code></pre>

**Comment by JoostK** [comment]
Yes, this syntax is not supported in ViewEngine builds (which libraries currently require).

You can work around it using:

```ts
providers: [{ provide: 'example', useFacory: () => $localize`Translated` }],
```

Or perhaps using an explicitly exported function:


```ts
export function provideExample() {
  return $localize`Translated`;
}

providers: [{ provide: 'example', useFacory: provideExample }],
```

(as I am not sure if the lambda expression is supported)

**Comment by klemenoslaj** [comment]
I actually tried both already (something I should mention in the issue itself, sorry) and neither of them worked 🤔 
Resulted in the same error.

I created two branches in the same repository for easy reproduction:
- `exported-named-function`
- `inlined-arrow-function`

**Comment by JoostK** [comment]
I got working with the named export syntax and a `@dynamic` marker:

```ts
export function provideExample() {
  return /* @dynamic */ $localize`Translated`;
}
```

Additionally, since v12 now allowing libraries to be compiled with the Ivy compiler I'll close this as resolved.
