### ISSUE TITLE
Ivy preview report: Error: ASSERTION ERROR: Reached the max number of directives

### ISSUE THREAD

**Issue by ibmhack2020** [angular/angular#40121]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

I have using ngx-permissions library and facing issue while using  *ngxPermissionsOnly="perm" inside *ngFor.

Please file any Angular Components issues at: https://github.com/angular/components/issues/new
![59981633-d512d300-960e-11e9-8620-9903817311e0](https://user-images.githubusercontent.com/67802892/102178945-5083d680-3ecc-11eb-9e46-e4459ba3782b.png)

For the time being, we keep Angular Components issues in a separate repository.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by petebacondarwin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
