### ISSUE TITLE
trackBy incorrectly changes item type

### ISSUE THREAD

**Issue by vbraun** [angular/angular#40125]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core

### Description

Using the ngFor trackBy function sets the item type to exactly the type of its argument

In the example below, use of the trackByBase function widens (i.e makes less specific) `item` in the template up to `Base`, even though it actually is a `Derived`. This is unexpected; the ngFor source array is already typed and the expectation is that the inferred type in the template is the type of the array, not the type of the trackBy argument.

## 🔬 Minimal Reproduction

Stackblitz: https://stackblitz.com/edit/angular-ivy-urqcqm

~~~
import { Component, VERSION } from '@angular/core';


interface Base {
    id: string;
}


interface Derived extends Base {
    name: string;
}


const DERIVED_ARRAY: Derived[] = [
    { id: 'one', name: 'First' },
    { id: 'two', name: 'Second' },
];


@Component({
    selector: 'my-app',
    templateUrl: './app.component.html',
    styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
    array = DERIVED_ARRAY;

    trackByBase(index: number, item: Base): string {
        return item.id;
    }
}
~~~
and template
~~~
<div *ngFor="let item of array; trackBy:trackByBase">
    {{ item.name }}
</div>
~~~

## 🔥 Exception or Error

<pre><code>
Error in src/app/app.component.html (10:13)
Property 'name' does not exist on type 'Base'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.3
Node: 12.18.4
OS: linux x64

Angular: 11.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, upgrade
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.3 (cli-only)
@angular-devkit/build-angular   0.1100.3
@angular-devkit/core            11.0.3
@angular-devkit/schematics      11.0.3
@angular/cdk                    11.0.2
@angular/material               11.0.2
@schematics/angular             11.0.3
@schematics/update              0.1100.3
ng-packagr                      11.0.3
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by lazarljubenovic** [comment]
Weird, I can't reproduce this locally with a clean Angular CLI project at `11.0.4`. `ng serve`, `ng build` and `ng build --prod` all seem to work fine without any errors.

This is the TCB I'm getting from the template:

```ts
import * as i0 from './app.component';
import * as i1 from '@angular/common';
import * as i2 from '@angular/core';


const _ctor1: <T = any, U extends i2.NgIterable<T> = NgIterable<T>>(init: Pick<i1.NgForOf<T, U>, "ngForOf" | "ngForTrackBy" | "ngForTemplate">) => i1.NgForOf<T, U> = (null!);

/*tcb1*/
function _tcb1(ctx: i0.AppComponent) { if (true) {
    var _t1 /*T:DIR*/ /*0,53*/ = _ctor1({ "ngForOf": ((((ctx).array /*25,30*/) /*25,30*/ as any)) /*22,32*/, "ngForTrackBy": ((((ctx).trackByBase /*40,51*/) /*40,51*/ as any)) /*32,51*/, "ngForTemplate": (null as any) }) /*D:ignore*/;
    _t1.ngForOf = ((((ctx).array /*25,30*/) /*25,30*/ as any)) /*22,32*/;
    _t1.ngForTrackBy = ((((ctx).trackByBase /*40,51*/) /*40,51*/ as any)) /*32,51*/;
    var _t2: any = (null!);
    {
        var _t3 = _t2.$implicit /*13,22*/;
        "" + (((_t3 /*59,63*/).name /*64,68*/) /*59,68*/);
    }
} }

export const IS_A_MODULE = true;
```

**Comment by lazarljubenovic** [comment]
Here's a stripped down version of what happens.

```ts
export interface Base {
  id: string;
}

export interface Derived extends Base {
  name: string;
}

type TrackByFn<T> = (index: number, item: T) => any;

const array = [] as Array<Derived>;
const trackByDerived = (() => {}) as TrackByFn<Derived>;
const trackByBase = (() => {}) as TrackByFn<Base>;

interface AngularForOf<T, U extends T[] = T[]> {
  ngForOf: U;
  ngForTrackBy: TrackByFn<T>;
}

function ctor<T, U extends T[]>(init: AngularForOf<T, U>): AngularForOf<T, U> {
  return init as any;
}

const base = ctor({
  ngForOf: array,
  ngForTrackBy: trackByBase,
});

const derived = ctor({
  ngForOf: array,
  ngForTrackBy: trackByDerived,
});
```

Looking at it this way, it seems obvious that the inferred type would be `<Base, Derived[]>`. 

The only fix I can think of is for `ctor` to return `AngularForOf<U[number], U>`. That worn't work for things which are not arrays, but you could still unwrap the `NgIterable` with something like `UnwrapNgIterable<T> = T extends NgIterable<infer U> ? U : never`. For this simplified example, `U[number]` seems to do the job:

```ts
function ctor<T extends V, U extends T[], V = T>(init: AngularForOf<T, U>): AngularForOf<U[number], U> {
  return init as any;
}

// ForOf<Base, Base[]>, simple case
const baseByBase = ctor({
  ngForOf: arrayOfBase,
  ngForTrackBy: trackByBase,
});

// ForOf<Derived, Derived[]>, with error because you can't track base by derived
const baseByDerived = ctor({
  ngForOf: arrayOfBase, // Type 'Base[]' is not assignable to type 'Derived[]'.
  ngForTrackBy: trackByDerived,
});

// ForOf<Derived, Derived[]>, checks that you can track derived by base, but doesn't infer item type  as base because of that
const derivedByBase = ctor({
  ngForOf: arrayOfDerived,
  ngForTrackBy: trackByBase,
});

// ForOf<Derived, Derived[]>, simple case
const derivedByDerived = ctor({
  ngForOf: arrayOfDerived,
  ngForTrackBy: trackByDerived,
});
```

----

I also tried replicating a more "realistic" snippet of what happens in Angular [in this TypeScript playground](https://www.typescriptlang.org/play?ts=4.0.5#code/KYDwDg9gTgLgBDAnmYcByBzAkjYUCGARgDbAA8AKgHxwC8cAglAYpVQD455GlsDcAKAGhIsOAEsAdrigAzfAGNUFAgoDWAIUQAxAK6SFMcREls4AbwFw4ACikATUAC44k3QFtCeADQTc7lwoAShd8SURBAF8hEWh4BWJ8AGckuABRUndgaQAlYFlKOjgwxBpLazBdEnEFV3wjADdgDOAs6UDBawUTJJgoXUNoG0l68SaWtphAoIsrawQAC3EkgDoRxubM7Ph6dbHN1u3OuGjo4XA44sJe1XjElLgAYQWwjGAAEWBcQag82VnrEQbop4O58FA1NpoM9gOobCE4A0IOJ7McgX0QXBHDBFAt4S4kSi0dcMYYsV9YTBnq9gEl8Yjkai5ujbnAFAtYWo0BBqZI3nSEYSmYCSayoMB6jj2fShVEhOdRPAWZiEslUgA1cTAADufzgoFwknsqV5b0+3xg0D15SuwLJjhuEEQMsZxLt8De8AdfSdwHs9MIEAgpDCbtJ8BMn0dzoU+GIxEIijULj0BiMJgRJQEZwVl2VZNVDzSnj9jnsmp1fzIjxoBuyxrgFd1+QBtvDcE9bJMuBAMHpjzDrM7UCDMG5DvpJQA2gBdOUxC5ifN3NVwCitMCJXBVmut5cdr76ra5fL0ibbP6DlXi+rNEv2MtNmzdaQGlyPBHFrwPv1NndUedYjEQtUkwKEoAAeVkR5uwNShfAAVX1Xt61A7AZB4chqCKTAuAIEgsKoMo5hfG4BktKAbEqapagAEnEdxNxqcQpjXXxqOIGpXAwcCoJcBD2KqTjagcZxXA8LwoEEmiu30Vi3BLKAZnMM5rE7WRxCgXoAyDENJFbaxxRgXQoH0mAllWUSQDoWh6AABmOVSD3ge4+wRQNgwlfSbUMr4TLMiyVismz6HM5YVm6OS4AAWjgABGRyhDUw9gCaSQdM8sIDLgIz-MWcLgoAUjgAAmEK4AcuYnM7CAHwyvTsty0y4AAQjC1ZUuyRKcyAlcHjA6AoPguAkLrI00LwzCzHoXCMIIthiOsJJDz5XjZGGHjBtkfiADJZu4ebqHYfRHA0yQ-XYNx42Uqq5lW6AVCTLQWsCVRNB0fRDGMUxqCSuBlvge6oHXRit2AGwGjjXRgECDcwarAbIOg2De2GhCiJu6wnN6UZaj5EHN1vGDX17ABxXRwXsNHkMNBt9vw3hqCoGx7E0lxEaGihEKoXxDBAUJwhCOZ5jZGBrOWdBNqR4mexgNHFvmJqzP6YBuqEKQZHkJQ4A0ZJUBtFEXBuKQMHnDW8C11BPigfZ7Bp1Cdb11sRiyI2+hN+dSPgd40hyLB1TSd4AH0GByHIGAATRca3bdnIopzmcwJHsFwAHITGAVPfBdmG4FT7RNN6VOTm8RPk7TmBtQgLO6ldvOAGVYRMexi8iUu5wXRU2XuVIGDAMAYMYjPpD3Zh8EQIofb9gPg9D8OI8EOZSXe3Xltep6PrTb6yFX4AaHoOwjTEhTJN8FjWhcXeEWNvk6AV3zjOa8-3CC4UTmzIQvbgIOfjilxCnoCURC9txqS0modfeYC5qMyIofFiLgAAKNQ1BkA5gULmI0eZ5yBlBYu7BsFS0euoLQeCCHgQJmDVOVAZi0BoGg+WRRhi6HjC1IIi8AD0AAqGAChCBxU4ewgQshPrpn0kHHhfDnxixcH3AeEAh7nWkJjLskhejfxgHFOAXCKBOHeFgHIAitGcLst4AArAAZkMfQH+FE4o2B8txNaLgbAuL5kEFY4IWBGJKqY7w5i7ICJmFwnxfiAnsKCZwkqJU-ElQEaXEWQMiHvWca4sW7jl5aF3kYgALCY0x-Dwk5LyQUiJ5jon5LicLRxD04a3mcVdYgxRUglCCPEk4ET3hOHEBgSQ0BgACOOOIuKawpZQUYakkA7jPHj28b4-xgTZmhIWcE6JZSBlzCGSM8hb0tDjKkZMlYGTEBZK4bksxJSinnOWZwspVz2HHC-uIkqAsJ4Hwaaw444h-g2DQSMihRMUYwHJpTGwQzfBPIiSYgA7AADgWQ4x5MBzFFCeSseioNmLwC4XFcx3gonrJFqnYuABqWwLjxHIq4aYgAnN4AAbJY8Jax8BZCMXS7J9K4WFKpbSulXK2G3TOL1FRaisD1xDkHAAshBd4CEAAyaQih9GhovIAA), but for some reason it actually does the coercion from `Base` to `Derived`:

![image](https://user-images.githubusercontent.com/7661457/102315447-7664b600-3f74-11eb-85f6-b55c812b202c.png)

I probably removed something that I shouldn't have when copying classes and interfaces for the required context, but can't put my finger on it at the moment.

**Comment by alxhub** [comment]
> I probably removed something that I shouldn't have when copying classes and interfaces for the required context, but can't put my finger on it at the moment.

The difference between your contrived example and the more realistic one is the type of `ngForOf` - in your contrived example it's `U`, but be more like `U&T[]` to align with the real type of `NgForOf.ngForOf`.

**Comment by alxhub** [comment]
Looking at this more closely, I noticed that the inferred type of `NgForOf` seems dependent on the TypeScript flag `strictFunctionTypes` (which makes sense, given that flag controls how the `ngForTrackBy` function affects inference).

With `strictFunctionTypes: false` the type is inferred as `NgForOf<Base, Derived[]>`.

With `strictFunctionTypes: true` the type is (correctly) inferred more narrowly as `NgForOf<Derived, Derived[]>`.

Thanks for the super interesting issue report. I think we should make a note of this in our template type-checking documentation. I recommend turning on this flag for the best possible type inference.

**Comment by JoostK** [comment]
This can be made to work regardless of `strictFunctionTypes`, by declaring `TrackByFunction` using a type parameter to allow widening `T` to a subtype:

```ts
type TrackByFunction<T> = <U extends T>(index: number, item: U) => any;
```

[TS Playground](https://www.typescriptlang.org/play?strictFunctionTypes=false&ssl=16&ssc=17&pln=16&pc=13#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgIUwGc8BvAWACg5EATALjiJimQHMBuKgXyqtEixEKNFlxwAImgQA3YLTihUSWkQLEyVGkkwBbYI2asknHn0owAnmDwAVKDgDW+SwDEkAHlsA+OAF44DwBVRRBlVTgfAApkWlBGJABXXQAjNAAaRFRdRiCASn9fTCRLLkoqbAgkZjhMKAdLfzgAbQBdWrUAQXrMSw8pVjlabzLK6vgWJxcB2XkmqKiCv19SbgLiOBiVeLgk1Iys4BzJaSGlopKOUaqayexnS0ISecXCuFX1tS24kATktKgmQQ2UYT2A51qlzKVGQqAwODwnRMiQANnVXNAAPLoLyZEJKYAqNS2NpNEmtFZaXZsDFQbG5ABk5LK2hp0HsU0sjA59xc7i8IzM5Uo6ESSGwMAQVTgEuguLg+LChIi5O8W2BjCRbFR6KxONseO8eU1yLRUFp2PlQUp1DgUGAMESUCQwmBHUhpSFFRu8BSGiasqgUQotpMFvQjDqDXSVLD7IcvK5cDuDzBMcoa2hlDGNTigzmAUDwdjbLpEdqPUs6dZtJ5D0YKemp3k6czQA)

**Comment by lucakohlgraf** [comment]
This change breaks our previously working code (Angular 12.0.x in strict mode) like this:

>error TS2322: Type '(_: number, item: Item) => number | undefined' is not assignable to type 'TrackByFunction<any>'.

`<ng-container *ngFor="let item of items; last as isLast; trackBy: trackItemById">`

`readonly trackItemById = (_: number, item: Item) => item.id;`

**Comment by petebacondarwin** [comment]
@lucakohlgraf - if you feel this has caused a regression, please create a new issue with a runnable reproduction (e.g. StackBlitz) that demonstrates the error so that we can investigate.

**Comment by JoostK** [comment]
There's already an issue for it: #42609.
