### ISSUE TITLE
ci: `test_win` CI job is flaky due to `bazelbuild/rules_nodejs` linker

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#40130]
Since recently(?) the `test_win` CI job has been flaking (see below for details on the errors).
(Initially reported by @petebacondarwin [here][1].)

The errors are thrown in the `bazelbuild/rules_nodejs` [linker][2] and seem to be caused by race conditions between several linker instances running in parallel and operating on the same `node_modules/` directory.
(As pointed out by @petebacondarwin, these were potentially introduced by bazelbuild/rules_nodejs@2979fad6579641f2b28f16702812437ae361c40b - fyi @devversion)

##
I looked at a few recent CI failures and summarize some observations here in case they mean something to someone more familiar with Bazel's and `bazelbuild/rules_nodejs`'s internals :grin:

- I looked at the the following failing CI jobs (54 total errors): [881590], [881841], [881877], [881927], [881958], [881987], [882096], [882116], [882203]

- The errors seem to involve the `@angular/upgrade` package much more often than other packages. (In the inspected errors, 52 out of 54 were about the `@angular/upgrade` package. The remaining two involved `@angular/compiler-cli` and `@angular/localize`.)
    Not sure if it is related, but `@angular/upgrade` is also the last Angular package alphabetically.

- The errors appear much more often in the `//packages/compiler-cli/ngcc/test:integration` target (31 out of 54 errors).

##
Below is a summary of the errors organized in two different ways:

<details>
<summary><b>Per Bazel test target</b> <i>(Click to expand)</i></summary>

- <details open>
    <summary><code>//packages/compiler-cli/ngcc/test:integration</code> - shard 1 of 4 <b>(ERRORS: 9)</b></summary>

    - [881927], [881987]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, rename 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade__linker_tmp' -> 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade'
    - [882096]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, rmdir 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade'
    - [881927]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, rmdir 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade\src'
    - [881877], [882116]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, scandir 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade'
    - [882116]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, scandir 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade\src'
    - [881841], [881987]:
        > [link_node_modules.js] An error has been reported: Error: File does not exist, but is listed as directory entry: @angular\upgrade\src
        >   at C:\users\circleci\_bazel_circleci\u4uoan2j\external\build_bazel_rules_nodejs\internal\linker\index.js:85:23
        >   at Generator.next (<anonymous>)
        >   at fulfilled (C:\users\circleci\_bazel_circleci\u4uoan2j\external\build_bazel_rules_nodejs\internal\linker\index.js:5:58) Error: File does not exist, but is listed as directory entry: @angular\upgrade\src
        >   at C:\users\circleci\_bazel_circleci\u4uoan2j\external\build_bazel_rules_nodejs\internal\linker\index.js:85:23
        >   at Generator.next (<anonymous>)
        >   at fulfilled (C:\users\circleci\_bazel_circleci\u4uoan2j\external\build_bazel_rules_nodejs\internal\linker\index.js:5:58)
    </details>

- <details open>
    <summary><code>//packages/compiler-cli/ngcc/test:integration</code> - shard 2 of 4 <b>(ERRORS: 7)</b></summary>

    - [881958]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, rename 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\localize__linker_tmp' -> 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\localize'
    - [881590], [881877], [881958], [882203]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, rename 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade__linker_tmp' -> 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade'
    - [881877]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, scandir 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade'
    - [881841]:
        > [link_node_modules.js] An error has been reported: Error: File does not exist, but is listed as directory entry: @angular\upgrade\src
        >   at C:\users\circleci\_bazel_circleci\u4uoan2j\external\build_bazel_rules_nodejs\internal\linker\index.js:85:23
        >   at Generator.next (<anonymous>)
        >   at fulfilled (C:\users\circleci\_bazel_circleci\u4uoan2j\external\build_bazel_rules_nodejs\internal\linker\index.js:5:58) Error: File does not exist, but is listed as directory entry: @angular\upgrade\src
        >   at C:\users\circleci\_bazel_circleci\u4uoan2j\external\build_bazel_rules_nodejs\internal\linker\index.js:85:23
        >   at Generator.next (<anonymous>)
        >   at fulfilled (C:\users\circleci\_bazel_circleci\u4uoan2j\external\build_bazel_rules_nodejs\internal\linker\index.js:5:58)
    </details>

- <details open>
    <summary><code>//packages/compiler-cli/ngcc/test:integration</code> - shard 3 of 4 <b>(ERRORS: 11)</b></summary>

    - [881590], [881841], [881927], [882096], [882116], [882203]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, rename 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade__linker_tmp' -> 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade'
    - [881987], [882203]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, scandir 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade'
    - [881590], [881841], [881927]:
        > [link_node_modules.js] Error: ENOTEMPTY: directory not empty, rmdir 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade'
    </details>

- <details open>
    <summary><code>//packages/compiler-cli/ngcc/test:integration</code> - shard 4 of 4 <b>(ERRORS: 4)</b></summary>

    - [881927], [882203]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, rename 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade__linker_tmp' -> 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade'
    - [881877], [882116]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, scandir 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade'
    </details>

- <details open>
    <summary><code>//packages/compiler-cli/test/diagnostics:check_types</code> <b>(ERRORS: 9)</b></summary>

    - [881841], [881877], [881987], [882096], [882116], [882203]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, rename 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade__linker_tmp' -> 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade'
    - [881841], [882203]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, scandir 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade'
    - [882096]:
        > [link_node_modules.js] Error: ENOTEMPTY: directory not empty, rmdir 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade'
    </details>

- <details open>
    <summary><code>//packages/compiler-cli/test:extract_i18n</code> <b>(ERRORS: 7)</b></summary>

    - [881841], [881958], [882096], [882203]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, rename 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade__linker_tmp' -> 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade'
    - [881877]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, rmdir 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade\src'
    - [881927], [882096]:
        > [link_node_modules.js] Error: ENOTEMPTY: directory not empty, rmdir 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade'
    </details>

- <details open>
    <summary><code>//packages/compiler-cli/test/metadata:test</code> <b>(ERRORS: 1)</b></summary>

    - [882116]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, scandir 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\compiler-cli\src'
    </details>

- <details open>
    <summary><code>//packages/compiler-cli/test:ngc</code> <b>(ERRORS: 1)</b></summary>

    - [881987]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, rename 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade__linker_tmp' -> 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade'
    </details>

- <details open>
    <summary><code>//packages/compiler-cli/test/transformers:test</code> <b>(ERRORS: 5)</b></summary>

    - [881877]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, rename 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade__linker_tmp' -> 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade'
    - [881590], [881987], [882096]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, scandir 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade'
    - [881927]:
        > [link_node_modules.js] Error: ENOENT: no such file or directory, scandir 'C:\users\circleci\_bazel_circleci\u4uoan2j\external\npm\node_modules\@angular\upgrade\src'
    </details>

</details>

<details>
<summary><b>Per failed operation</b> <i>(Click to expand)</i></summary>

- <details open>
    <summary>Operation: <a href="https://github.com/bazelbuild/rules_nodejs/blob/c148138928665c47d0537e2bdf6e5be347e2bd91/internal/linker/index.js#L85"><code>deleteDirectory()</code></a> <b>(ERRORS: 3)</b></summary>

    - Involved path(s): `@angular/upgrade/src` _(errors: 3)_:
        - Bazel target: `//packages/compiler-cli/ngcc/test:integration` - shard 1 of 4: [881841], [881987]
        - Bazel target: `//packages/compiler-cli/ngcc/test:integration` - shard 2 of 4: [881841]
    </details>

- <details open>
    <summary>Operation: <code>rename ==> ENOENT</code> <b>(ERRORS: 27)</b></summary>

    - Involved path(s): `@angular/localize__linker_tmp -> @angular/localize` _(errors: 1)_:
        - Bazel target: `//packages/compiler-cli/ngcc/test:integration` - shard 2 of 4: [881958]
    - Involved path(s): `@angular/upgrade__linker_tmp -> @angular/upgrade` _(errors: 26)_:
        - Bazel target: `//packages/compiler-cli/ngcc/test:integration` - shard 1 of 4: [881927], [881987]
        - Bazel target: `//packages/compiler-cli/ngcc/test:integration` - shard 2 of 4: [881590], [881877], [881958], [882203]
        - Bazel target: `//packages/compiler-cli/ngcc/test:integration` - shard 3 of 4: [881590], [881841], [881927], [882096], [882116], [882203]
        - Bazel target: `//packages/compiler-cli/ngcc/test:integration` - shard 4 of 4: [881927], [882203]
        - Bazel target: `//packages/compiler-cli/test/diagnostics:check_types`: [881841], [881877], [881987], [882096], [882116], [882203]
        - Bazel target: `//packages/compiler-cli/test:extract_i18n`: [881841], [881958], [882096], [882203]
        - Bazel target: `//packages/compiler-cli/test:ngc`: [881987]
        - Bazel target: `//packages/compiler-cli/test/transformers:test`: [881877]
    </details>

- <details open>
    <summary>Operation: <code>rmdir ==> ENOENT</code> <b>(ERRORS: 3)</b></summary>

    - Involved path(s): `@angular/upgrade` _(errors: 1)_:
        - Bazel target: `//packages/compiler-cli/ngcc/test:integration` - shard 1 of 4: [882096]
    - Involved path(s): `@angular/upgrade/src` _(errors: 2)_:
        - Bazel target: `//packages/compiler-cli/ngcc/test:integration` - shard 1 of 4: [881927]
        - Bazel target: `//packages/compiler-cli/test:extract_i18n`: [881877]
    </details>

- <details open>
    <summary>Operation: <code>rmdir ==> ENOTEMPTY</code> <b>(ERRORS: 6)</b></summary>

    - Involved path(s): `@angular/upgrade` _(errors: 6)_:
        - Bazel target: `//packages/compiler-cli/ngcc/test:integration` - shard 3 of 4: [881590], [881841], [881927]
        - Bazel target: `//packages/compiler-cli/test/diagnostics:check_types`: [882096]
        - Bazel target: `//packages/compiler-cli/test:extract_i18n`: [881927], [882096]
    </details>

- <details open>
    <summary>Operation: <code>scandir ==> ENOENT</code> <b>(ERRORS: 15)</b></summary>

    - Involved path(s): `@angular/compiler-cli/src` _(errors: 1)_:
        - Bazel target: `//packages/compiler-cli/test/metadata:test`: [882116]
    - Involved path(s): `@angular/upgrade` _(errors: 12)_:
        - Bazel target: `//packages/compiler-cli/ngcc/test:integration` - shard 1 of 4: [881877], [882116]
        - Bazel target: `//packages/compiler-cli/ngcc/test:integration` - shard 2 of 4: [881877]
        - Bazel target: `//packages/compiler-cli/ngcc/test:integration` - shard 3 of 4: [881987], [882203]
        - Bazel target: `//packages/compiler-cli/ngcc/test:integration` - shard 4 of 4: [881877], [882116]
        - Bazel target: `//packages/compiler-cli/test/diagnostics:check_types`: [881841], [882203]
        - Bazel target: `//packages/compiler-cli/test/transformers:test`: [881590], [881987], [882096]
    - Involved path(s): `@angular/upgrade/src` _(errors: 2)_:
        - Bazel target: `//packages/compiler-cli/ngcc/test:integration` - shard 1 of 4: [882116]
        - Bazel target: `//packages/compiler-cli/test/transformers:test`: [881927]
    </details>

</details>

[1]: https://angular-team.slack.com/archives/C042EU9T5/p1607978099120600
[2]: https://github.com/bazelbuild/rules_nodejs/blob/2424d1e32b564fcc37b57d593b871461a62f3237/internal/linker/link_node_modules.ts
[3]: https://github.com/bazelbuild/rules_nodejs/blob/c148138928665c47d0537e2bdf6e5be347e2bd91/internal/linker/index.js#L85

[881590]: https://circleci.com/gh/angular/angular/881590
[881841]: https://circleci.com/gh/angular/angular/881841
[881877]: https://circleci.com/gh/angular/angular/881877
[881927]: https://circleci.com/gh/angular/angular/881927
[881958]: https://circleci.com/gh/angular/angular/881958
[881987]: https://circleci.com/gh/angular/angular/881987
[882096]: https://circleci.com/gh/angular/angular/882096
[882116]: https://circleci.com/gh/angular/angular/882116
[882203]: https://circleci.com/gh/angular/angular/882203

**Comment by josephperrott** [comment]
@gregmagolan This is an issue that describes the issue we saw after updating past `rules_nodes@2.3.1` as we discussed.  I figured it would be good for you to see @gkalpak's description of the situation as well.

**Comment by gkalpak** [comment]
Is the update to `bazelbuild/rules_nodejs` version 2.3.3 (in #40581) supposed to fix this?

**Comment by josephperrott** [comment]
Yes, the upgrade to `2.3.3` (and `3.1.0`) should correct it.

**Comment by gkalpak** [comment]
Re-opening, since the issues seem to still happen (potentially with a lower frequency).
Example new occurrences:
- [924051](https://circleci.com/gh/angular/angular/924051)
- [924099](https://circleci.com/gh/angular/angular/924099)

([Discussion][1] (private link - sorry))

[1]: https://angular-team.slack.com/archives/C042EU9T5/p1614027478002100
