### ISSUE TITLE
[class.active] no longer working

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#4013]
In earlier releases there used to be an active.class property that could be used to emit an active class that could be used to style the 'active' nav item.
In alpha 36 this doesn't seem to work. Is this a bug or is there an alternative now? Didn't see this in the change log.

**Comment by gdi2290** [comment]
did you include `CORE_DIRECTIVES`?

**Comment by thelgevold** [comment]
Closing this issue. My assumption was wrong based on changes to the return value of location.path() in the new version of the router. 
@gdi2290 Thanks for the suggestion. However, it still turns out that we don't have to include CORE_DIRECTIVES to get access to [class.active]. It's still accessible by default.
