### ISSUE TITLE
Using `{{` and `}}` in strings in templates breaks the compiler

### ISSUE THREAD

**Issue by elliotleelewis** [angular/angular#40133]
# 🐞 bug report

### Affected Package

I believe this is caused by incorrect lexer grammars in `@angular/compiler`.

### Is this a regression?

Not that I'm aware of.

### Description

Using `{{ ... }}` inside a string inside a template binding throws compile errors, complaining that it cannot parse the input.

For example:

```html
<p>{{ 'This is a string literal which breaks the angular compiler... {{ }} <-------- ' }}</p>
```

<img width="266" alt="image" src="https://user-images.githubusercontent.com/17044667/102240491-d49b8580-3eef-11eb-9523-bddf28c13ebb.png">

This shouldn't be the case. Strings should be by-definition any characters, and shouldn't stop the app from compiling correctly.

In our use-case, we have a custom i18n solution that uses that syntax for variable replacement within localized strings, and without this fixed, we have to define those strings as class properties in the component's class file instead.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-string-brace-bug?file=src/app/app.component.html

## 🔥 Exception or Error
<pre><code>Error: src/app/app.component.html:1:1 - error NG5002: Parser Error: Unexpected token Lexer Error: Unterminated quote at column 16 in expression [ "Hello {{ test ] at column 17 in [{{ "Hello {{ test }}!" }} ] in /PATH/TO/PROJECTS/test/src/app/app.component.html@0:0
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.1.0-next.2
Node: 12.15.0
OS: darwin x64

Angular: 11.1.0-next.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.3
@angular-devkit/build-angular   0.1101.0-next.2
@angular-devkit/core            11.1.0-next.2
@angular-devkit/schematics      11.1.0-next.2
@angular/fire                   6.1.4
@schematics/angular             11.1.0-next.2
@schematics/update              0.1101.0-next.2
rxjs                            6.6.3
typescript                      4.1.2

</code></pre>

**Anything else relevant?**

I don't think so.

**Comment by JoostK** [comment]
I believe this was fixed in #39826 which will be part of this week's release :-)

**Comment by elliotleelewis** [comment]
@JoostK Wow, good timing!! 😂 

This issue can probably be closed then.

**Comment by JoostK** [comment]
Could you test with the snapshot builds?

```json
"@angular/compiler": "https://github.com/angular/compiler-builds"
"@angular/compiler-cli": "https://github.com/angular/compiler-cli-builds"
```

**Comment by elliotleelewis** [comment]
@JoostK Yep that seems to work fine. Although of course my IDE (WebStorm) is still complaining about it.

<img width="989" alt="image" src="https://user-images.githubusercontent.com/17044667/102254599-c013b900-3f00-11eb-807c-5973f73fc199.png">

**Comment by JoostK** [comment]
Great to hear it's indeed been resolved. I am not sure about the LS (Language Service) integration; I suspect that WebStorm has its own parsing infrastructure, and VS Code is somewhat unexpected to m but maybe it uses a different version altogether (although I don't think so). There is currently work underway to more tightly integrate the LS with the compiler itself, but I couldn't tell if that would make a difference here.

**Comment by atscott** [comment]
Closing this as resolved.
With respect to the errors in the language service, Webstorm has its own implementation that we don't control. As for the VScode issue, this would be resolved by the upcoming Ivy Native Language Service, which we'll be releasing as experimental in 11.1. One of the main goals of that project was to ensure the LS diagnostics matched the diagnostics you would get from the compiler.

**Comment by elliotleelewis** [comment]
Sweet! Thanks for your help on this guys! 👍
