### ISSUE TITLE
docs: a snapshot and description for the lifecycle hooks Peek-A-Boo example doesn't match to an actual behavior.

### ISSUE THREAD

**Issue by AlexElin** [angular/angular#40138]
# 📚 Docs or angular.io bug report

### Description

 
A snapshot and description for [the lifecycle hooks Peek-A-Boo example](https://angular.io/guide/lifecycle-hooks#sequence-and-frequency-of-all-lifecycle-events) doesn't match to an actual behavior.

### What's the affected URL?**
https://angular.io/guide/lifecycle-hooks#sequence-and-frequency-of-all-lifecycle-events

### Reproduction Steps**

1. Go to https://angular.io/guide/lifecycle-hooks#sequence-and-frequency-of-all-lifecycle-events
2. Run the corresponding example in [Stackblitz](https://angular.io/generated/live-examples/lifecycle-hooks/stackblitz.html)
3. In the live example click 
>  the Create... button and then the Destroy... button.
4. Compare a log message sequence in the live example with the one in the docs.

### Expected vs Actual Behavior**
**Actual**:  a snapshot and description for [the lifecycle hooks Peek-A-Boo example](https://angular.io/guide/lifecycle-hooks#sequence-and-frequency-of-all-lifecycle-events) doesn't match to an actual behavior.
**Expected**:  a snapshot and description for [the lifecycle hooks Peek-A-Boo example](https://angular.io/guide/lifecycle-hooks#sequence-and-frequency-of-all-lifecycle-events) matches to an actual behavior.

### In the docs
![peek-a-boo](https://user-images.githubusercontent.com/13061803/102275928-2ddad780-3f37-11eb-93c1-f87168262f2e.png)

### Actual behavior
![ang_lifecycle](https://user-images.githubusercontent.com/13061803/102276092-65498400-3f37-11eb-9538-15dbe069a11b.png)

**Comment by lazarljubenovic** [comment]
The additional three lines from the docs screenshot are all "checked" hooks. You can get the same output if you as much as focus any input field on the whole page, as this will trigger the CD cycle and call the "check" hooks. So it's not really a mistake, just a slightly different course of action.

I'm on mobile now so I can't confirm but maybe you can also trigger the additiinal "check" hooks just by *hovering* over something, which makes it even easier to accidentally case a mismatch between what you see and what the person who made the original screenshot saw.

**Comment by AlexElin** [comment]
I was able to trigger the additiinal "check" hooks by focusing input fields for the other examples.

But I find this situation _confusing for a reader_. Becuase there's a smth like unexpected coupling between examples that look independent at first sight. 
I think for the case ".. the user clicked the _Create_... button and then the _Destroy_... button." there should be no such confusing unclear situations. If we want to show the additiinal "check" we should mention explicitly how to reproduce them.

**Comment by lazarljubenovic** [comment]
Yeah, I agree it's not ideal as it stands right now in the docs. We should probably explain in what cases the output might be different from shown and how to trigger it.

**Comment by AlexElin** [comment]
Yeah, it would be good

**Comment by cesperian** [comment]
@aikidave I'm definitely taking this one : ) Thanks!...
