### ISSUE TITLE
Casing issue in HttpClient 

### ISSUE THREAD

**Issue by rohanshenoy96** [angular/angular#40146]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common/http

### Is this a regression?

 Yes, the previous version in which this bug was not present was: I had tested the same in version 9 looks like it works fine in that. Not sure of other versions.

### Description

 A clear and concise description of the problem...
There seems to be issue with casing HttpClient package imported from @angular/common/http

## 🔬 Minimal Reproduction

 
Create a project with the following configurations (follow below package.json file). Try to create a service file with httpClient. Throws some error on npm serve or npm build.

## 🔥 Exception or Error
<pre><code>

Error in terminal when doing npm serve/npm build
![image](https://user-images.githubusercontent.com/37835789/102307822-4bd22780-3f8b-11eb-85e2-4e756a402785.png)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

package.json 
```
{
  "name": "documentations",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "ngcc"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.1.5",
    "@angular/cdk": "^10.2.7",
    "@angular/common": "~10.1.5",
    "@angular/compiler": "~10.1.5",
    "@angular/core": "~10.1.5",
    "@angular/forms": "~10.1.5",
    "@angular/material": "^10.2.7",
    "@angular/platform-browser": "~10.1.5",
    "@angular/platform-browser-dynamic": "~10.1.5",
    "@angular/router": "~10.1.5",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1001.6",
    "@angular/cli": "~10.1.6",
    "@angular/compiler-cli": "~10.1.5",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}
```
Note: HttpClientModule was included in the module file
</code></pre>

**Anything else relevant?**

**Comment by lazarljubenovic** [comment]
Do a case-sensitive search in your project for "@Angular" and fix the casing there to "@angular".

**Comment by rohanshenoy96** [comment]
Hi lazarljubenovic,
I think you're referring that there could be an issue with case. I don't think it's there. I will share you a link to my repo so that debugging could be easy. It's a very small repo too.
Link to repo: https://github.com/rohanshenoy96/documentation
Thanks in advance 😊

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

@lazarljubenovic  is correct. I left a comment on the commit which points to the incorrect casing.
