### ISSUE TITLE
Equivalent to resolve in Component Router?

### ISSUE THREAD

**Issue by robwormald** [angular/angular#4015]
With the removal of the @InjectPromise and @InjectLazy decorators, is there an equivalent functionality to resolve in ngRoute/uiRouter? 

The angular1 version would look something like:
```js
//controller
function MyController(foo){}

//route config
{
  controller: 'MyController',
  url: 'foos/:fooId',
  resolve: {  
    foo: function($routeParams,FooService){ return FooService.getFooById($routeParams.fooId); }
  }
}
```
This is IMO, one of the killer features of the current router and UI-router, as it remove async entirely from the controller and makes it super easy to test. The canActivate etc hooks cover one of the use cases for resolve (preventing access to routes/state), but I can't see a replacement for the above case. Perhaps I'm missing something?

I've been tinkering with an idea like this for NG2, implementing resolve as a decorator:
```js
@Component({ selector: 'foo-detail' })
@View({ template: '<div>{{foo.name}}</div>'})
//token : resolver : injectables
@Resolve(Foo, (params, fooService) => fooService.getFooById(params.fooId), [RouteParams, FooService])
class FooDetailComponent {
  constructor(public foo: Foo){}
}
```
An alternative syntax might look like:
```js
@Resolve({
  foo(params:RouteParams, fooService:FooService){ return fooService.getFooById(params.fooId) }
})
```
Though that limits you to string keys and I can't figure a way to pass bindings, and I'm not sure reflect will allow us to grab the metadata annotations this way.

Under the hood, it keeps async out of the injector, as its "simply" a matter of executing the resolver fn before passing them to the component's overridden bindings. Thoughts?

**Comment by brandonroberts** [comment]
You could implement the OnActivate interface which can be used to resolve data before the component navigation completes. Its called after CanActivate and the component will not be activated until its resolved when using a promise.

**Comment by robwormald** [comment]
@brandonroberts not a bad idea, but my concern there is that it necessarily couples a component to the router I think, vs using the constructor and DI, which would allow you to test/reuse a component independently of the router.

**Comment by btford** [comment]
This is a planned feature. There's another issue where I've expended on my plan for implementing it.

**Comment by endash** [comment]
+1 I've been using DI (with string tokens) in some cases for "giving a component its model" to avoid coupling to a central service class, but something higher level in the router would be awesome.

**Comment by goleafs** [comment]
Actually, I think it may even be desirable to have a resolve (or at least some way to pass additional arguments) into the canActivate itself.

This would be primarily for code reuse.
The other scenario is passing resolves down the line to sub-routes.. how will this work?

Is there a reference to the issue with the expanded plan for implementation?

**Comment by eqbalsajadi** [comment]
+

**Comment by awerlang** [comment]
I'd like that. Most cases `Foo` would be just an object or array, we would achieve that with OpaqueToken I guess.

@goleafs not sure if we need to pass resolves to sub-routes, as the DI provides for shared services from where we could access the data.

**Comment by brandonroberts** [comment]
I have a proposal for the resolvers. Something similar to what I proposed for the CanActivate. Passing an injectable class as the resolver could be an option also.

```js
@Resolve([
    { name: Foo, resolver: (params: RouteParams, someService: SomeService) {
        return new Promise((resolve) => {
            this.someService.doSomething(this.params.get('id')).subscribe((result) => {
                resolve(result);
            });
        });
    }
])
class MyRoute {
    constructor(foo: Foo) {
    }
}
```

**Comment by nigeman** [comment]
I like @brandonroberts suggestion above. Currently it seems we have to mimic this "async resolve" via your CanActivate DI workaround that @brandonroberts came up with a few months ago.Any movement on this? Just curious :)

**Comment by gdi2290** [comment]
the meta data emitted by ts for the constructor doesn't work on function so you have to change it a bit
```typescript
@Resolve([
  {
    name: Foo,
    deps: [RouteParams, SomeService], 
    resolver: (params: RouteParams, someService: SomeService) => {
      return new Promise(resolve => {
        someService.doSomething(params.get('id')).subscribe((result) => {
          resolve(result);
        });
      });
    }
  }
])
class MyRoute {
  constructor(foo: Foo) {}
}
```

**Comment by brandonroberts** [comment]
@gdi2290 good catch

**Comment by fxck** [comment]
Is wrapping things in promises necessary? Same goes CanActivate(https://github.com/angular/angular/issues/4112#issuecomment-187507011).. wouldn't

```
        someService.doSomething(params.get('id')).take(1).subscribe((result) => {
          resolve(result);
        });
```

do the same job?

**Comment by brandonroberts** [comment]
@fxck currently, all the router lifecycle hooks need to return a boolean or a promise that resolves a boolean so that the route isn't activated until the promise(s) settle. Using an observable wouldn't immediately resolve the value, so it wouldn't wait. You could return a converted observable:

```
return someService.doSomething(params.get('id')).take(1).toPromise();

```

**Comment by cquillen2003** [comment]
+1 for @Resolve decorator.

Data-fetching belongs in a decorator instead of in ngOnInit() or routerOnActivate() IMHO.

**Comment by syndicatedshannon** [comment]
I agree that given the current design I would intuitively look for a "Resolve" decorator.

The suggested format is very bulky when compared to what was necessary for UI Router, especially with the likely scenario that we'll be bridging observables. My current implementation of Brandon's workaround is actually a little slimmer, although it is quite specific to my needs, and subject to the workaround's weaknesses, such as using magic strings:

`
@CanActivate(RootResolver('Foo', fooSvc: FooService => fooSvc.getFoo()))
...
	routerOnActivate(to) {
		this.foo = to.routeData.data['Foo'];
	}
`

And the receiver could probably be trimmed down further by stuffing the injector. I appreciate the software, just wanted to mention I was surprised it wasn't more terse.

I also don't understand what is going on with the name property: What value type does the "Foo" keyword represent here? I wasn't aware that you could

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166442.
------------------------------------------------------------------------------------------------------------


[[7fbc0494b9745b2c370577e7cefbedcf0b18334b-673073289]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166457.
------------------------------------------------------------------------------------------------------------


[[4e2c0b4e4ee56564d5b88c924eeda028c4afc5c8-673073410]]

**Comment by syndicatedshannon** [comment]
I'm glad this is on the hotlist.

Can someone please comment on the intention (or lack of intention) to support this on AuxRoute as well?

We're in a bind where, since AuxRoute does not process the CanActivate hook, the workaround is not working; and we cannot build aux components that are responsible for their own data, or move/reuse components between Aux and Primary routes.

Also, does anyone listening have a suggestion on a similar workaround for AuxRoutes?

**Comment by syndicatedshannon** [comment]
An older discussion by contributors on this topic:
https://github.com/angular/router/issues/100

**Comment by syndicatedshannon** [comment]
Did anyone attend Brandon's workshop (https://www.ng-conf.org/#/sessions/bdogg64FD) yesterday? It was scheduled to discuss "resolving data before loading routes", and appears to have been using the new-new router (with CanActivate moved/relocated).

**Comment by brandonroberts** [comment]
I attended :-). I didn't cover resolving data before loading routes because that mechanism doesn't exist in the new router yet.

**Comment by syndicatedshannon** [comment]
Oh noes! And CanActivate is toast :). Keep us apprised please!

So, how did you like Brandon's workshop, Brandon?

**Comment by brandonroberts** [comment]
Will do. I thought Brandon's workshop went pretty well. The other attendees spoke positively about it also :+1:

**Comment by alexmady** [comment]
Hi - any ideas when the CanActivate mechanism will be available to use? 
 What is the suggested approach for an authentication mechanism in the mean time for those of us who are developing apps agains rc1? 

Cheers

**Comment by danielpquinn** [comment]
In my opinion this is the most critical piece of functionality missing from Angular 2.0 today. I was able to get by using @brandonroberts OnActivate workaround, but now that it's gone in the release candidate I'm feeling a little high and dry here! I hesitate to use a third party solution like ngrx/router or ui-router so early in the life of this project.

That being said, I'm excited to see that progress is being made on the router after so many months of waiting, please continue the good work :) I feel like this is a situation where releasing a working implementation soon will be more valuable than debating implementation details for another six months in an attempt to come up with a perfect api or pattern. I have a fairly large app built on Angular 2 right now and overall it's been a dream to work with, but the component loading experience is negatively affected by the limitations of the router. I apologize if the tone of this comment is a little negative, but I desperately need this feature!

Please keep us updated, thanks!

**Comment by fxck** [comment]
@danielpquinn one of the two people behind @ngrx/router is @brandonroberts. Not to mention that @ngrx/router team is actually in talks with angular team, to them improve the new router. So believe me, it's a safe bet, I've been using for almost two months, and it's been a breeze, the community and the rate it gets improved without breaking changes is amazing, it allowed me to do all the things I wanted from the component router. And since I'm going fully reactive, it's even better alternative than the ui-router.

**Comment by syndicatedshannon** [comment]
I hear you Daniel and I agree that, for my needs, that this is the most critical piece missing from the RC.

However, precisely because that I don't want to end up resorting to a plug-in AFTER integrating the stock router, I would like to see the Angular designers get it nearly-right this time. We've already seen the design in 1.x was insufficient pretty early-on, as was the 2beta. I personally don't need another highly-incomplete refactor that results in rework without long-term benefit.

Like you, we also decided to start building our new app on Angular 2 beta a year early, knowing full well that it was not recommended. However, that doesn't mean I would urge the Angular team to sacrifice the quality of this integral piece of the platform for everyone's future, including my own.

Instead my team is building our own components to meet our specific needs for now; and we look forward to a routing solution that does 90-95% of what 90-95% of teams need.

**Comment by danielpquinn** [comment]
Thanks for the feedback @fxck and @syndicatedshannon. I think you're right about taking time to get it right, and maybe @ngrx/router is the safest bet for now. I'll see how far that gets me today.

**Comment by syndicatedshannon** [comment]
Also keep in mind that you can still used router-deprecated. I didn't mean it was removed entirely, it just wasn't brought forward into the new router (which has other issues as well). So, if you started a solution on 2beta router, just change your code to point at router-deprecated. There are a few minor inconsistencies, but... 'dems da breaks when using beta, I suppose!

**Comment by fxck** [comment]
@danielpquinn feel free to join the gitter channel at gitter.im/ngrx/router there's always someone to help you out when you don't know how to do something.

**Comment by michaeljohnbennett** [comment]
Been a while since this was last updated, are we any closer to a solution in the new RC router?

**Comment by IgorMinar** [comment]
this is already handled by router v3

**Comment by nigeman** [comment]
Link to some documentation about this ? Is it purely the life cycle hooks ? And DI inject into them ? Was that the final solution ? Cheers!

**Comment by michaeljohnbennett** [comment]
@nigeman +1 I coudn't see any documentation about these features in the API docs or cookbooks.

**Comment by syndicatedshannon** [comment]
RC4 includes this.
[Günter Zöchbauer on StackOverflow](http://stackoverflow.com/questions/34289761/angular-2-equivalent-to-router-resolve-data-for-new-router/38138019#38138019)
[The patch.](https://github.com/angular/angular/commit/f2f1ec0)
[Latest ChangeLog](https://github.com/angular/angular/blob/master/CHANGELOG.md)

**Comment by ammar91** [comment]
@syndicatedshannon As of beta 2, Resolve is a generic interface. What type should I suppose to pass in it?

**Comment by awerlang** [comment]
According to this definition, it can be anything. The generic parameter type ain't used to constraint anything. I'll put the return type of the method `resolve` though, like `string` if I return an `Observable<string>`.

```ts
export interface Resolve<T> {
  resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot):
      Observable<any>|Promise<any>|any;
}
```

**Comment by ammar91** [comment]
@awerlang Thanks for the quick help.
