### ISSUE TITLE
Passing dynamic value in @Input not working in web components (angular-elements)

### ISSUE THREAD

**Issue by nitishwebgentle** [angular/angular#40155]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/10.0.4

### Is this a regression?

 No: ....

### Description

Hi There,

I have created a web component using angular-element. Lets say the name of component for this web-component is `TestComponent`. This TestComponent accepts a value using `@Input`.

```
export class TestComponent{

@Input() userId: string;

 // other code goes here

}
```

Here is the custom html tag for this component.

`<dev-test></dev-test>`

Now, I need to use this web-component in some other angular application (consuming application).
If I use this web-component in the consuming application using hard coded values, then everything works fine like below.

`<dev-test user-id="10"></dev-test>`

This works fine as TestComponent gets value 10 to userId.
Now If I make this value as dynamic like:

```
export class AddTestComponent{
  public userId = 10;
  constructor() { }
}

and use the following html for web component - 

<dev-test user-id="userId "></dev-test>
```

Then `@Input` userId gets userId (text) not the value i.e. 10.

I have tried following - 

```
<dev-test user-id="userId "></dev-test>

<dev-test [userId]="userId "></dev-test>

<dev-test user-id="{{userId}} "></dev-test>
```

But nothing works.

Kindly suggest how to pass the dynamic values in the `@Input` in web component (angular -elements).

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 10.1.4
Node: 12.17.0
OS: win32 x64

Angular: 10.1.4
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.4
@angular-devkit/build-angular   0.1001.4
@angular-devkit/core            10.1.4
@angular-devkit/schematics      10.1.4
@schematics/angular             10.1.4
@schematics/update              0.1001.4
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Anything else relevant?**

**Comment by mlc-mlapis** [comment]
You should probably realize that web components have only standard properties and attributes as any pure HTML element, so you need to script the changes by your code, as you certainly do with pure HTML elements. The same is also true for catching events, where you need to use pure JS `addEventListener` method.

**Comment by mlc-mlapis** [comment]
@nitishwebgentle Hmm, what I wrote above I valid for using Angular Elements directly from the non-Angular world.

If you want to use Angular Elements inside another Angular application, then the syntax:

`<dev-test user-id="userId "></dev-test>`  will pass always the value `userId` as string when instantiating the component (native HTML syntax).

`<dev-test user-id="{{userId}} "></dev-test>` will pass the value contained in the property `userId` as string when instantiating the component (valid Angular binding).

`<dev-test [userId]="userId"></dev-test>`  will pass the value contained in the property `userId` when instantiating the component and also on each its change in the data type, as it's saved in the property `userId` (valid Angular dynamic binding).

If you want to look at a working example, you can use, for example, https://github.com/leebrandt/angular-elements-example, specifically, look at the line `<ct-click-tracker [step]="2" (increase)="logEvent($event)"></ct-click-tracker>` in the file app.component.html. It is the same case as you are talking about.

**Comment by nitishwebgentle** [comment]
Thanks @mlc-mlapis. I have already tried the syntax that you have mentioned.

```
<dev-test user-id="userId "></dev-test>      // This gives userId text not the value

<dev-test [userId]="userId "></dev-test>    // This gives undefined

<dev-test user-id="{{userId}} "></dev-test>   // This gives undefined
```

I have also tried `@Input('myInputProp') inputProp` syntax for the input property, still I am getting the same error.

My only requirement is pass a dynamic values in the component from consuming app.

**Comment by mlc-mlapis** [comment]
@ I understand, but you have to have a mistake somewhere. I personally tried the example: https://github.com/leebrandt/angular-elements-example, I mentioned above (with those changes to simulate your case), and it worked. You can also try and see.

**Comment by gkalpak** [comment]
@mlc-mlapis said, this should work. If it doesn't work for you, please create a minimal reproduction and open a new issue.
(You can use [this StackBlitz template][1] to create your reproduction.)

[1]: https://stackblitz.com/fork/ngelements-playground
