### ISSUE TITLE
RouteParams not available to top level directives

### ISSUE THREAD

**Issue by rightisleft** [angular/angular#4016]
I have a primary component named Ticket which has a nested directive of TopNav

```
part of ticket_client;

@Component(
    selector: 'tickets'
)
@View(
    template: '<topnav></topnav><router-outlet></router-outlet>',
    directives: const [Topnav, RouterOutlet, RouteParams]
)
@RouteConfig(const [
  const Route(path: '/landing', component: Landing, as: 'landing'),
  const Route(path: '/flights', component: ViewFlights, as: 'flights'),
  const Route(path: '/contact', component: Picker, as: 'contact'),
  const Route(path: '/picker/:cityDepart/:cityArrival/:dateDepart/:dateArrival/', component: FlightDisplay, as: 'picker'),
  const Route(path: '/order/:id/:level/:dateDepart/:dateArrival/', component: ViewOrder, as: 'order'),
  const Route(path: '/order/complete', component: ViewComplete, as: 'orderComplete')
])
class Tickets {
  String name = 'Jit Ticket Application';
  Router router;

  Tickets(this.router) {
    router.subscribe( (value) {
      print("Route changed to: $value");
    });
  }
}
```

It exists outside of the first level router-outlet

If i try an acquire RouteParams through DI inside of TopNav - i get the following error:

Exception: No provider for RouteParams! (Topnav -> RouteParams)
  ExceptionHandler.call	
  <anonymous closure>	
  NgZone._onErrorWithoutLongStackTrace@693253716	
  NgZone.<anonymous closure>	

Moving topnav into the child of an outlet seems to solve the issue, but then i have to include topnav in each child view.

I would assume that RouteParams are a top level global object. Might be similar to the comments here on Angular Dart V1

http://japhr.blogspot.com/2013/10/routing-without-scope-in-angulardart.html

**Comment by rigoleto** [comment]
I'm running into this same exact issue on alpha 46. I have a navigation component, outside the router outlet of course, since I want it on every page. I can inject Location, but not RouteParams. Did you figure out a nicer way around this, or just stick with having your nav on every page?

**Comment by daviesian** [comment]
Same issue here on `2.0.0-beta.0`. I wonder why this was closed...

**Comment by mcot2** [comment]
Can confirm, for both RouteParams and RouteData it is not available on top level components, only the children of the router-outlet.

**Comment by CaptainCodeman** [comment]
Same here. It also doesn't seem to be accessible in a 'dumb' (non-routed) component that isn't loaded by a routed parent.

**Comment by ericmartinezr** [comment]
RouteData and RouteParams are provided by [RouterOutlet](https://github.com/angular/angular/blob/master/modules/angular2/src/router/router_outlet.ts#L60). The only way to get access them is through routing. If you want them in some non routed component you can use services to pass the data across the app.

**Comment by aarmora** [comment]
@ericmartinezr Can you give an example of this?  I added routeparams to a service and removed any reference to RouteParams in my non routed component (app.component, which has my nav).  It's still throwing the error.

**Comment by ericmartinezr** [comment]
@aarmora this is a super basic example, and it's kind of raw. You would be much better by making an observable, see http://plnkr.co/edit/s20OPsN88U4npD95qEx3?p=preview hopefully you'll understand it. Press the link and then the button.

**Comment by aarmora** [comment]
@ericmartinezr Nice work!  It took me a bit to sort through it (not by any fault of yours) but I think I got it.  So the service itself is not getting the route parameters, they are coming from the routable component, to the service, which gives them to the non routable component.  Brilliant!
