### ISSUE TITLE
extract-i18n produces wrong equiv-text for files with CRLF 

### ISSUE THREAD

**Issue by tbastyns** [angular/angular#40169]
# 🐞 bug report

### Is this a regression?

Yes, the previous version in which this bug was not present was: 10.x.x

### Description

When extracting i18n from files with CRLF as line endings instead of LF, the equiv-text (interpolation) will be incorrect: it will be offset by a certain amount of characters, perhaps due to the extra character in newlines (CR)?
Example: https://github.com/tbastyns/ng11-i18n/blob/master/src/locale/messages.xlf

This wasn't an issue in angular v10, but suddenly occurred after upgrading to angular 11.
Diff when bumping from v10 -> 11: https://github.com/tbastyns/ng11-i18n/commit/5dfd3688ed737cc296d047aa0e1441be96f9822c#diff-db1a03e3781e595fd8985e7f0deb2201c3f15c507b620907ed0b4aacd5b2dd83 

I understand that generally the use of LF is recommended. I noticed the above issue on a project I recently joined, that still uses CRLF. I figured some other people might find themselves in a similar situation.

## 🔬 Minimal Reproduction

Since the issue occurs due to line endings, I figured a github repo would be safer than stackblitz
https://github.com/tbastyns/ng11-i18n
Depending on your git cli settings, it might auto-convert line endings. To reproduce the bug, make sure to set the line endings of app.component.html to CRLF

## 🔥 Exception or Error

Unfortunately, no exception or errors are logged. The command runs as if nothing went wrong (which is somewhat true - i18n can still be used etc.)
In case CRLF is not supported in v11, it would be nice if extract-i18n would log warnings/errors for each file that doesn't use the correct line endings.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.4
Node: 12.18.3
OS: win32 x64

Angular: 11.0.5
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.4
@angular-devkit/build-angular   0.1100.4
@angular-devkit/core            11.0.4
@angular-devkit/schematics      11.0.4
@angular/cli                    11.0.4
@schematics/angular             11.0.4
@schematics/update              0.1100.4
rxjs                            6.5.5
typescript                      4.0.5
</code></pre>

**Anything else relevant?**
TS files that use $localize are also impacted when using CRLF. I forgot to include it in the repo, sorry!

If only LF is supported, it would be nice to see a warning when running the i18n extraction. Or perhaps even include adding it as an option in .editorconfig when running ng update?
Also depends on user git settings, IDE settings, project settings, ...

Might be related to some things in #39654 ? Not sure

**Comment by petebacondarwin** [comment]
I believe that this is a bug in the source-map processing on this line: https://github.com/angular/angular/blob/master/packages/compiler-cli/src/ngtsc/sourcemaps/src/source_file.ts#L449

It should be:

```ts
function computeLineLengths(str: string): number[] {
  return (str.split(/\n/)).map(s => s.length);
}
```

**Comment by petebacondarwin** [comment]
And I have what I believe to be a fix in a separate PR: https://github.com/angular/angular/pull/40087/commits/c3febe3edf003c9e5a6b3c7cbdf6254f386ab65d

**Comment by tbastyns** [comment]
Thanks a lot for the quick response!
Do you expect your fix to be released soon-ish? Or would you recommend that I convert all files to LF in the meantime to work around the issue?

**Comment by petebacondarwin** [comment]
I can convert that specific fix to a PR today. But we don't plan another patch release of Angular until after the New Year now.
