### ISSUE TITLE
ngcc error: Attempted to get members of a non-class but is class

### ISSUE THREAD

**Issue by JanMalch** [angular/angular#40178]
# 🐞 Bug report

### Command

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes

### Description

When compiling the `@ngxs-labs/entity-state` UMD bundle the following error occurs:

```
> ngcc --tsconfig ./tsconfig.app.json

Compiling @ngxs-labs/entity-state : main as umd
Error: Error on worker angular/angular-cli#1: Error: Attempted to get members of a non-class: "class Add {
    /**
     * Generates an action that will add the given entities to the state.
     * The entities given by the payload will be added.
     * For certain ID strategies this might fail, if it provides an existing ID.
     * In all other cases it will overwrite the ID value in the entity with the calculated ID.
     * @param target The targeted state class
     * @param payload An entity or an array of entities to be added
     * @see CreateOrReplace#constructor
     */
    constructor(target, payload) {
      return generateActionObject(exports.EntityActionType.Add, target, payload);
    }
  }"
    at UmdReflectionHost.Esm2015ReflectionHost.getMembersOfClass...
```

## 🔬 Minimal Reproduction

```
ng new testapp && cd testapp
npm i @ngxs-labs/entity-state
ngcc --tsconfig ./tsconfig.app.json
```

## 🔥 Exception or Error

See above or [here](https://github.com/ngxs-labs/entity-state/issues/280#issue-752070838)

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / Ôû│ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.8
Node: 14.13.0
OS: win32 x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cli                      10.0.8
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Anything else relevant?**

The other bundle is fine and changing the `enableIvy` flag doesn't change the behaviour. I guess because there isn't anything Angular specific in the library and just plain TypeScript classes and functions.

**Comment by JoostK** [comment]
The issue here is that the UMD bundle is ES2015, whereas it's typically ES5. I notice that `@ngxs-labs/entity-state` is not using ng-packagr but instead a custom Rollup build to bundle everything, which explains the discrepancy in target language (ng-packagr writes UMD bundles using ES5 syntax).

I don't think we'll address this in ngcc, so I'd recommend that `@ngxs-labs/entity-state` changes its UMD bundle to be downleveled to ES5.
