### ISSUE TITLE
Add option for Validators.pattern to be provided with an custom error to differentiate multiple pattern validators.

### ISSUE THREAD

**Issue by HeathJared** [angular/angular#40173]
# 🚀 feature request

### Relevant Package

@angular/forms

### Description

Angular forms that have controls with multiple `Validator.pattern` validators (which sometimes are very large regex strings) are difficult to map to the correct `<mat-error>` messages.

This can be done by comparing the `requiredPattern` property which is not ideal for large regex strings on large forms. Instead, we are currently forking the `Validator.pattern` code for just to set a different "error" than the default value of "pattern".

### Describe the solution you'd like

Extend the `Validator.pattern` method with an optional parameter that either replaces the `pattern` key or adds a new property inside of the validation error.

Example:

`Validator.pattern( ... , 'my custom error')`

would return an error like:

`{'my custom error': {'requiredPattern': regexStr, 'actualValue': value}};`

or:

`{'pattern': {'error': 'my custom error', 'requiredPattern': regexStr, 'actualValue': value}};`
 

instead of the current:

`{'pattern': {'requiredPattern': regexStr, 'actualValue': value}};`

**Comment by AndrewKushnir** [comment]
Hi @HeathJared,

Currently the `Validators.pattern` provides a way to identify which validator was invoked (by including the `requiredPattern` field into the error object). This information should cover most of the cases, so I don't think we should extend validator function with extra fields.

If you have a complex logic and you need additional ways to handle errors, you may create your custom validator, call `Validators.pattern` inside it and augment the result with extra fields.

Thank you.
