### ISSUE TITLE
support bower package management

### ISSUE THREAD

**Issue by david-gang** [angular/angular#4018]
This feature request may be connected to #3257 .

One of the main workflows today, for maintaining dependencies to 3rd parties is through bower.

The bower.json contains all dependencies. Then the bower command line is used to download all modules transitively. Afterwards we use modules like [main-bower-files] (https://www.npmjs.com/package/main-bower-files) to create a list of files which have to be fetched into the application.

The gulp snippet looks like this 

```
gulp.src(bower_files)
        .pipe(js_filter)
        .pipe(sourcemaps.init())
        .pipe(concat('vendor.js'))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('lib'));
```

Afterwards the vendor.js is included into the index.html

The situation now with angular 2 is that it can be just downloaded through npm. Also the [bower.json] (https://github.com/angular/angular/blob/master/bower.json) file is missing the main property. 

Would it be possible to maintain the bower workflow?
This would mean that packages should be uploaded to bower and the bower.json should be filled out properly.

If not which workflow do you envision ?

**Comment by PascalPrecht** [comment]
I think we actually try to get away from using bower and simply stick with
npm because it's the best package manager out there. With bower you could
simply install from github endpoint tho, so that should solve your issue.

**Comment by david-gang** [comment]
Hi @PascalPrecht ,

Installing from the bower endpoint would solve halve of my problem.
I would need additionally to modify the bower.json file. 

We would need to add the main property.
```
{
  "name": "angular2",
"main": ["./bundles/angular2.js", "./bundles/http.js", "./bundles/router-dev.js" ],
  "dependencies": {
    "polymer": "dart-lang/polymer_js#0.8.0-preview"
  }
}
```
Otherwise the workflow with main-bower-files which is mentioned above would not work.
I could create a PR here if it is the way we would want to go.

If not and we go the npm way, how would we get the list of dependencies and their transitive dependencies which would have to be included in the browser? I did not find an equivalent module for these tasks which could be integrated with gulp.

Thanks,
David

**Comment by PascalPrecht** [comment]
Transitive dependencies would need to be declared in your package.json as well AFAIK, just as you'd do with bower. I don't know what's the planned story for bower here, but my latest status was that bower is dead.

**Comment by david-gang** [comment]
I agree.
After reading http://blog.npmjs.org/post/122450408965/npm-weekly-20-npm-3-is-here-ish it looks like we can get away just with npm.
It is not clear to me what the equivalent of the bower main property in package.json is, but i am sure that they will have to provide it sooner or later.
