### ISSUE TITLE
docs: No Id's in products.ts in the getting started guide

### ISSUE THREAD

**Issue by Kovoltcher** [angular/angular#40189]
# 📚 Docs or angular.io bug report

### Description

The repo you should fork for the getting started https://stackblitz.com/angular/oeypoedalxr?file=src%2Fapp%2Fproducts.ts has no property for id in the arry products

### What's the affected URL?**

https://angular.io/start/start-routing

### Reproduction Steps**

If you followed the steps of the first tutorial and this tutorial https://angular.io/start/start-routing the products in the array product have **no Id**

### Expected vs Actual Behavior**

The url should show: `../products/{id}` but as there is no id it shows `../products/undefined` and also the product details are not shown, because of that.

## 📷Screenshot

product.ts
![grafik](https://user-images.githubusercontent.com/71433252/102608972-0a787e00-412b-11eb-853f-24bedb2f7d07.png)

results in
![grafik](https://user-images.githubusercontent.com/71433252/102609282-7f4bb800-412b-11eb-9a26-8c36c13bf97b.png)

## ✍️Solution
Change code to this in products.ts to fix the guide
<pre><code>
export const products = [
  //added id's for fix
  {
    id: 1,
    name: "Phone XL",
    price: 799,
    description: "A large phone with one of the best screens"
  },
  {
    id: 2,
    name: "Phone Mini",
    price: 699,
    description: "A great phone with one of the best cameras"
  },
  {
    id: 3,
    name: "Phone Standard",
    price: 299,
    description: ""
  }
];
[</code></pre>]

edited: links

**Comment by gkalpak** [comment]
Good catch! Thx for reporting this, @Kovoltcher :+1:

This seems to be an artifact from back when we used the `products` array index to identify each product.
#40197 should take care of making the remaining changes to fully switch the examples to using `product.id`.

**Comment by Kovoltcher** [comment]
Thanks @gkalpak.
I'm glad that I could help, especially because I'm relativly new to coding. I realy like the Tutorial, keep up the good work 🥇
