### ISSUE TITLE
BrowserAnimationModule - keyframes Angular Universal

### ISSUE THREAD

**Issue by todorpavlovic** [angular/angular#40183]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....

### Description
For BrowserAnimationModule to work with Angular Universal It is needed to import NoopAnimationsModule into app.server.module, then I need to create app.browser.module insert there BrowserAnimationsModule then it will work or it's showing "document is undefined".
But if i'm using keyframes it's showing this error.
`
ERROR TypeError: Cannot read property 'display' of undefined
    at cloakElement ...
`
So I'm not able to use keyframes, and example of this code won't work..
`
import { trigger, animate, style, transition, keyframes } from '@angular/animations';

const $timing = '450ms cubic-bezier(.8, -0.6, 0.2, 1.5)';

export let $animations = [

  trigger('beat', [
    transition('* => *',
      animate($timing,
        keyframes([
          style({ transform: 'scale(0.8)' }),
          style({ transform: 'scale(1.5)' }),
          style({ transform: 'scale(1)' })
        ])
      )
    )
  ])
];

`

**Comment by AndrewKushnir** [comment]
Related PR: #17792.

**Comment by alan-agius4** [comment]
This is expected as when using Universal.

When using the animations modules, you'll always need to import `NoopAnimationsModule` in the server module.

Closing as this is working as expected.
