### ISSUE TITLE
:enter animation .done callback gets triggered on element destroy

### ISSUE THREAD

**Issue by 4javier** [angular/angular#40186]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/animations

### Description
Binding to `.done` callback of animation with `:enter` transition applied to a dynamically generated view, makes the callback getting triggered when the view gets destroyed.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-s2lvp8?file=src/app/app.component.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.4
Node: 15.4.0
OS: linux x64

Angular: 11.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.4
@angular-devkit/build-angular   0.1100.4
@angular-devkit/core            11.0.4
@angular-devkit/schematics      11.0.4
@angular/cdk                    11.0.2
@schematics/angular             11.0.4
@schematics/update              0.1100.4
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by 4javier** [comment]
I think this problem is related
https://github.com/angular/angular/issues/21546

Could the call to `finish()` `inside destroy()`
https://github.com/angular/angular/blob/e0e2157a28558b388670ad2da4bdcdede8070c7d/packages/animations/src/players/animation_player.ts#L182
be the culprit?

https://github.com/angular/angular/blob/e0e2157a28558b388670ad2da4bdcdede8070c7d/packages/animations/src/players/animation_player.ts#L133-L139

**Comment by jelbourn** [comment]
Duplicate of #21546
