### ISSUE TITLE
Exception in component constructor is masked by Angular

### ISSUE THREAD

**Issue by vikerman** [angular/angular#4019]
Alpha:36 Angular Dart.

When there is an exception in the constructor it is not reported properly in the Exception message. It just says "Error during instantiation of <class>". When I set the breakpoint in the Injector class I do see the actual stack trace being stored in the inner exception which would help me exactly pinpoint the problem. That stack trace is much more valuable than the current one being thrown.

ERROR: Error during instantiation of ActivityComponent!.
[package:angular2/src/di/injector.dart 732:7                              Injector._instantiate
package:angular2/src/di/injector.dart 564:17                             Injector._new
package:angular2/src/di/injector.dart 201:26                             InjectorInlineStrategy.instantiateBinding
package:angular2/src/core/compiler/element_injector.dart 849:11          ElementInjectorInlineStrategy.hydrate
package:angular2/src/core/compiler/element_injector.dart 459:20          ElementInjector.hydrate
package:angular2/src/core/compiler/view_manager_utils.dart 218:29        AppViewManagerUtils._hydrateView
package:angular2/src/core/compiler/view_manager_utils.dart 116:10        AppViewManagerUtils.hydrateRootHostView
package:angular2/src/core/compiler/view_manager.dart 164:17              AppViewManager.createRootHostView
package:angular2/src/core/compiler/dynamic_component_loader.dart 116:43  DynamicComponentLoader.loadAsRoot.<fn>
package:stack_trace                                                      StackZoneSpecification.registerUnaryCallback.<fn>
package:angular2/src/core/zone/ng_zone.dart 231:40                       NgZone._runUnary.<fn>
dart:async                                                               _ZoneDelegate.run
package:angular2/src/core/zone/ng_zone.dart 207:21                       NgZone._run
package:angular2/src/core/zone/ng_zone.dart 231:7                        NgZone._runUnary
package:stack_trace                                                      StackZoneSpecification.registerUnaryCallback.<fn>
package:angular2/src/core/zone/ng_zone.dart 231:40                       NgZone._runUnary.<fn>
dart:async                                                               _ZoneDelegate.run
package:angular2/src/core/zone/ng_zone.dart 207:21                       NgZone._run
package:angular2/src/core/zone/ng_zone.dart 231:7                        NgZone._runUnary
dart:async                                                               _Future._asyncComplete.<fn>
package:angular2/src/core/zone/ng_zone.dart 240:11                       NgZone._scheduleMicrotask.<fn>
dart:async                                                               _ZoneDelegate.run
package:angular2/src/core/zone/ng_zone.dart 207:21                       NgZone._run
, dart:async                                                                           _Future.then
package:angular2/src/core/compiler/dynamic_component_loader.dart 115:56              DynamicComponentLoader.loadAsRoot

**Comment by IgorMinar** [comment]
this is a known issue that @vsavkin is working on already.

**Comment by jbdeboer** [comment]
This is likely a dup of #3408

**Comment by naomiblack** [comment]
@vsavkin is this closed by https://github.com/angular/angular/commit/f6cc57368768e0c2f47c6646620c4cff73e5d5a7?
