### ISSUE TITLE
docs: an animation for the lifecycle hooks SpyDirective example doesn't match to an actual behavior

### ISSUE THREAD

**Issue by AlexElin** [angular/angular#40193]
# 📚 Docs or angular.io bug report

### Description

 
A snapshot and description for [the lifecycle hooks SpyDirective example](https://angular.io/guide/lifecycle-hooks#use-directives-to-watch-the-dom) doesn't match to an actual behavior.

### What's the affected URL?**
https://angular.io/guide/lifecycle-hooks#use-directives-to-watch-the-dom

### Reproduction Steps**

1. Go to https://angular.io/guide/lifecycle-hooks#use-directives-to-watch-the-dom
2. Run the corresponding example in [Stackblitz](https://angular.io/generated/live-examples/lifecycle-hooks/stackblitz.html)
3. In the live example click _Add Hero_ button. It adds Herbie 
4. Compare a log message sequence in the live example with the one in the docs. 
In the docs' animation there's a # 3 event. But it's missed in the live example.

### Expected vs Actual Behavior**
**Actual**:  an animation for [the lifecycle hooks SpyDirective example](https://angular.io/guide/lifecycle-hooks#use-directives-to-watch-the-dom) doesn't match to an actual behavior.
**Expected**: an animation for [the lifecycle hooks SpyDirective example](https://angular.io/guide/lifecycle-hooks#use-directives-to-watch-the-dom) matches to an actual behavior.

### In the docs
![spy-directive](https://user-images.githubusercontent.com/13061803/102643595-8d6ff780-4170-11eb-9328-661579d68e19.gif)
### Actual behavior
![ang_lifecycle](https://user-images.githubusercontent.com/13061803/102643565-83e68f80-4170-11eb-8050-6024d43364da.png)

**Comment by AlexElin** [comment]
I noticed the problem goes away when I comment out `counter-parent` compoment in `app.component.html` template.
How I understand this problem happens due to `nextId` global scope in `spy.directive.ts`. In fact both `spy-parent` and `counter` components increment the same variable `nextId`.

**Comment by AlexElin** [comment]
But I find this situation _confusing for a reader_. Becuase there's a smth like unexpected coupling between examples that look independent at first sight.
I think this should be fixed somehow.

**Comment by gkalpak** [comment]
More importantly, you get complitely different results in the actual example vs the gif when detroying the components.
The gif shows:

```
Spy #5 onDestroy
Spy #4 onDestroy
Spy #3 onDestroy
Spy #2 onDestroy
Spy #1 onDestroy
```

...while in the actual example you get:

```
Spy #7 onDestroy
Spy #8 onDestroy
Spy #9 onDestroy
Spy #10 onDestroy
Spy #11 onDestroy
```
