### ISSUE TITLE
Docs: Transfer in-memory-web-api into main repo

### ISSUE THREAD

**Issue by SijmenHuizenga** [angular/angular#40190]
# 📚 Transfer in-memory-web-api component documentation into main repo

### Description

In #37182 the [in-memory-web-api](https://github.com/angular/in-memory-web-api) module was moved into [this repo](https://github.com/angular/angular/tree/master/packages/misc/angular-in-memory-web-api). It seems the documentation has not yet been updated accordingly. There are two problems:

- [ ] At the moment the aio docs still have some links to the archived repo: `aio/content/guide/http.md` and `aio/content/tutorial/toh-pt6.md`
- [ ] The [readme](https://github.com/angular/in-memory-web-api/blob/master/README.md) is still only available in the old repo.

I propose to copy the [readme](https://github.com/angular/in-memory-web-api/blob/master/README.md) to `packages/misc/angular-in-memory-web-api/README.md` and update the links.

If you agree that this is the way forward let me know, I can create pr's.

**Comment by gkalpak** [comment]
I think that sounds reasonable. Feel free to create a PR, @SijmenHuizenga 🚀
