### ISSUE TITLE
Not installed Angular 11.0.5

### ISSUE THREAD

**Issue by Vladislav-wn** [angular/angular#40200]
Hi,
NPM 6.14.9
Project template is not installed
_____________________________________________________________________________________________________________________________
/ Installing packages (npm)...npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! Unexpected end of JSON input while parsing near '...4399,"npm-signature":'

× Package install failed, see above.
The Schematic workflow failed. See above.

**Comment by petebacondarwin** [comment]
I'm sorry but you haven't provided us with enough information to help. Also it looks like this is an issue while using the Angular CLI. If you believe there is actually a bug in the CLI please open an issue at https://github.com/angular/angular-cli, providing reproduction instructions.
