### ISSUE TITLE
writeValue called before ngOnInit in nested ControlValueAccessors with initial form data

### ISSUE THREAD

**Issue by phip1611** [angular/angular#40209]
I have nested `ControlValueAccessor`s (two components), where the outer `ControlValueAccessor` takes the inner `ControlValueAccessor` via `<ng-content>`, i.e. via `@ContentChild("#cvDelegate")`. If I pass initial form data (which is handled by Angular via `writeValue()`, `ngOnInit()` get's called after `writeValue()` on the inner  `ControlValueAccessor` (**too late**).

I think my bug is different to https://github.com/angular/angular/issues/29218 because I'm using `NG_VALUE_ACCESSOR` and passing components via `ng-content` rather than passing NgControl via constructor.

# 🐞 bug report

### Affected Package
Not sure, probably @angular/core

### Is this a regression?
No, the Bug also occurs in Angular 8, 9, 10, and 11. (I tested all)

### Description
I have nested `ControlValueAccessor`s (two components), where the outer `ControlValueAccessor` takes the inner `ControlValueAccessor` via `<ng-content>`, i.e. via `@ContentChild("#cvDelegate")`. If I pass initial form data (which is handled by Angular via `writeValue()`, `ngOnInit()` get's called after `writeValue()` on the inner `ControlValueAccessor` **(too late)**. I use it like this:

```html
<form *ngIf="form" [formGroup]="form">
	Comma-Separated list:
        <!-- outer control value accessor; directly interacts with form -->
        <!-- form.get("list") is string array, and my mapper component let me edit it as a comma separated string -->
	<app-control-value-mapper formControlName="list" [fromModel]="reduceListWithComma" [toModel]="commaStringToList">
	    <!-- inner control value accessor; used by ControlValueMapperComponent -->	
            <app-form-input #cvDelegate></app-form-input>
	</app-control-value-mapper>
</form>
```

The order of events is the following:
```
AppComponent: ngOnInit
ControlValueMapperComponent: constructor
FormInputComponent: constructor
ControlValueMapperComponent: ngOnInit    <--- fine (ControlValueAccessor on first level)
ControlValueMapperComponent: writeValue  <--- fine
FormInputComponent: writeValue           <--- NOT fine (ControlValueAccessor on second level)
ERROR: writeValue called BEFORE ngOnInit!
FormInputComponent: ngOnInit             <--- NOT fine, TOO LATE
```

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/writevalue-called-before-ngoninit-in-nested-controlvalueaccesso?devtoolsheight=33&file=src/app/control-value-mapper.component.ts

## 🔥 Exception or Error
In the inner `ControlValueAccessor` (`FormInputComponent` in my example on Stackblitz) `ngOnInit()` is called too late.

## 🌍  Your Environment

**Angular Version:**
11, but also in 8, 9, and 10

## Workaround
Exists with setTimeout. Inside `ControlValueMapperComponent#writeValue` (see my example on Stackblitz):
```ts
  writeValue(obj: any): void {
    // Should work but doesn't
    // this.delegate.writeValue(this.fromModel(obj));
    // Workaround that definitely works
    window.setTimeout(() => this.delegate.writeValue(this.fromModel(obj));`
  }
```

PS: Thank you very much in advance for your comments on this. Happy holidays/merry christmas :)

**Comment by alvaromartmart** [comment]
Related: https://github.com/angular/angular/issues/29218

**Comment by alvaromartmart** [comment]
Comparison of `NG_VALUE_ACCESSOR` provider vs injected `ngControl`: https://stackblitz.com/edit/angular-ivy-mmcdey?file=src/app/custom-input-ngcontrol/custom-input-ngcontrol.component.html

**Comment by JeanMeche** [comment]
Let's merge the disucssion in #29218
