### ISSUE TITLE
The ngOnDestroy handler crashes after upgrade to Angular 11 on 'ng test' (zone.js issue)

### ISSUE THREAD

**Issue by pkwasnik** [angular/angular#40215]
# 🐞 bug report

### Affected Package
The issue is caused by package zone.js

### Is this a regression?

Yes, the previous version in which this bug was not present was: Angular 10

### Description

After updating Angular to version 11 and using the latest zone.js (0.11.3),  on `ng test` the ngOnDestroy handler crashes throwing:
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'data-ck-expando' of undefined
TypeError: Cannot read property 'data-ck-expando' of undefined
```

It is because `Object.prototype.toString.call( undefined )` returns `[Object Window]` instead of `[Object Undefined]` when the strict mode isn't turned on.

A similar issue was already reporter in the past: https://github.com/angular/angular/issues/31678

The workaround is to import zone.js in `polyfills.js` like this `import 'zone.js/dist/zone.js'` instead of `import 'zone.js/dist/zone'` or `import 'zone.js'`

## 🌍  Your Environment

<pre>
@angular-devkit/architect       0.1100.4
@angular-devkit/build-angular   0.1100.4
@angular-devkit/core            11.0.4
@angular-devkit/schematics      11.0.4
@schematics/angular             11.0.4
@schematics/update              0.1100.4
ng-packagr                      11.0.3
rxjs                            6.6.3
typescript                      4.0.3
webpack                         4.44.2
</pre>

**Comment by jelbourn** [comment]
@JiaLiPassion did something change in Zone's packaging that would cause this?

**Comment by JiaLiPassion** [comment]
@jelbourn , I will check it, @pkwasnik , could you give me a reproduce repo? thanks,

**Comment by pkwasnik** [comment]
@JiaLiPassion Thanks for taking this up. Here is the repo: [`https://github.com/ckeditor/ckeditor5-angular`.](https://github.com/ckeditor/ckeditor5-angular.) Just change there importing `zone.js` in `src\polyfills.ts` from `import 'zone.js/dist/zone.js';` to `import 'zone.js'` or `import 'zone.js/dist/zone'`. Then after running `ng test` there will be a bunch of errors.

**Comment by JiaLiPassion** [comment]
@pkwasnik , thanks, I can reproduce it, and I am not completely understand the root cause, but I have some direction, I will update the status after I find out the real reason.

**Comment by JiaLiPassion** [comment]
The reason is `import 'zone.js'` from `0.11.x` will import `esm2015` bundle, but zone.js esm2015 bundle is a little special, since `zone.js` is a bundle with pure side effect and without any export, so when running `ng test`, webpack load it by concat the zone.js script without adding `use strict` statement, so the following code will not return correct result.

```
const toString = function() {
   return Object.prototype.toString.call(this);
}

toString.apply(undefined); // should be [Object Undefined], but in non-strict mode, it becomes [Object Window]
```

And cause `ckeditor` run into unexpected logic route. 
I have created a PR to force zone.js bundle to be strict.
