### ISSUE TITLE
Question: Custom-Validator and template-driven-forms

### ISSUE THREAD

**Issue by manfredsteyer** [angular/angular#4021]
Hi,

the sample at [1] shows how to use template-driven forms and how to use custom validators in such a scenario. I've tried to create an own sample on the basis of this with the current Alpha (2.0.0-alpha.36/angular2.dev.js). Unfortunately I experienced some general show-stoppers:

- I can not import NG_VALIDATORS when I use the mentioned code-base
- The same is true for CONST_EXPR

Do I see it right, that the mentioned code base does not contain everything that is necessary for this scenario or is there a solution/ workaround?

Btw: I also wonder how to tell the Injector to resolve this kind of multi-binding that is used in [1].

Best Wishes,
Manfred

[1] angular/modules/examples/src/template_driven_forms/index.ts

**Comment by cexbrayat** [comment]
the new `NG_VALIDATORS` is not yet released. In alpha-36, you can do:

    bindings: [bind(NgValidator).toAlias(MyValidator)]

**Comment by manfredsteyer** [comment]
Thx for your help. I should have used the corrent for alpha-36. 

But I'm still wondering how to use thouse multi-bindings directly with the Injector.

Thx again and best wishes,
Manfred

**Comment by cexbrayat** [comment]
The multi binding is also not yet release, so you can't use it in alpha 36

**Comment by PascalPrecht** [comment]
@manfredsteyer also, what is your use case here for multi bindings? You should be able to resolve your problem without'em

**Comment by manfredsteyer** [comment]
@PascalPrecht Yes, I can resolve my problem without them. But it seems, that the ng-model-directive uses it, to get its validators injected. Everything one binds to NgValidator (or NG_VALIDATORS in the future) is injected for validation into ng-model. So I wondered how this works under the covers ...

I guess, in future releases, the injector will have a method to get several dependencies for one token (getAll or something) ...

**Comment by mhevery** [comment]
obsolete
