### ISSUE TITLE
Angular/core 11.0.3 E2E tests error

### ISSUE THREAD

**Issue by BrunoBeraudPW** [angular/angular#40221]
# 🐞 bug report

Hello !

Since 11.0.3 angular/core version, E2E tests are not working on a project with the default configuration.

### Affected Package
angular/core

### Is this a regression?
Yes, error are appearing since angular/core 11.0.3, it was working in previous version

### Description

When executing "ng e2e" cmd.

## 🔬 Minimal Reproduction

https://github.com/BrunoBeraudPW/issue-angular-11.0.3

It's a default project angular 11.0.3 where I have updated all packages to their latest version

I have updated "manually" all packages because the "ng new" cmd was creating an angular 10 app and so I was thinking that maybe the problem came because of the others packages.

But even when I have just updated angular packages, the error was still here 

## 🔥 Exception or Error
When using fakeAsync :
<pre><code>
Failed: zone-testing.js is needed for the async() test helper but could not be found.
                Please make sure that your environment includes zone.js/dist/zone-testing.js
</code></pre>
Several errors in selenium-webdriver libs (promise)
<pre><code>
 C:\dev-phoenix\1-Photoweb-Forks\test\node_modules\selenium-webdriver\lib\promise.js:3067:27
              this.pending_ = {task: task, q: this.subQ_};
              task.promise.queue_ = this;
              result = this.subQ_.execute_(task.execute);
                                  ~
              this.subQ_.start();
            } catch (ex) {
</code></pre>
Several errors in internal/modules/cjs/loader.js
<pre><code>
internal/modules/cjs/loader.js:955:30
        jasmine-spec-reporter: unable to open 'internal/modules/cjs/loader.js'
        Error: ENOENT: no such file or directory, open 'internal/modules/cjs/loader.js'
</code></pre>

It seem to not recognize jasmine functions, it underlines in red the name of the main functions describe, it, fit, etc., like if it didn't include test.ts and its import 'zone.js/dist/zone-testing';
![image](https://user-images.githubusercontent.com/62344493/102784185-50884880-439c-11eb-9417-7adccc6b9762.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect       0.1100.3
@angular-devkit/build-angular   0.1100.3
@angular-devkit/core            11.0.3
@angular-devkit/schematics      11.0.3
@schematics/angular             11.0.3
@schematics/update              0.1100.3
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

Thank !

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by ArcosBinary** [comment]
Make sure to update your test.ts file. The zone import has to be before the zone-testing import.

```
import "zone.js/dist/zone";
import 'zone.js/dist/zone-testing';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

declare const require: {
  context(path: string, deep?: boolean, filter?: RegExp): {
    keys(): string[];
    <T>(id: string): T;
  };
};

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);
// Then we find all the tests.
const context = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);
```
Or maybe the src/polyfills.ts file is missing / the import is missing:

`import 'zone.js/dist/zone';  // Included with Angular CLI.`
