### ISSUE TITLE
Router: property 'parentView' of undefined when missing selector in nested router

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular#4022]
I know this is being tracked here https://github.com/angular/angular/issues/1662, but I didn't want to contaminate that thread with this issue.

From the issue referenced I understand that `@Component` without a selector is valid, so this works (I tried it and it does)

```Javascript
@Component()
@View({
  template : ``
})
@RouteConfig([
  new Route({path:'test', component: AnotherComponent, as :'test'})
])
class NestedRouter {}

@Component({ selector: 'hello' })
@View({
	template: `<router-outlet></router-outlet>`,
	directives : [RouterOutlet]
})
@RouteConfig([
  new Route({path:'/nested/...', component : NestedRouter, as : 'nested'})
])
class ...
```
But personally I'm too used to use selectors for components, so at first I tried adding a selector and I forgot to specify one

```Javascript
@Component({selector:''}) // <-- Empty selector, silly me!
@View({
  template : ``
})
@RouteConfig([
  new Route({path:'test', component: AnotherComponent, as :'test'})
])
class NestedRouter {}

@Component({ selector: 'hello' })
@View({
	template: `<router-outlet></router-outlet>`,
	directives : [RouterOutlet]
})
@RouteConfig([
  new Route({path:'/nested/...', component : NestedRouter, as : 'nested'})
])
class ...
```
in the latter case it throws this error message : 

```
EXCEPTION: TypeError: Cannot read property 'parentView' of undefined
angular2.dev.js:22746 STACKTRACE:
angular2.dev.js:22746 TypeError: Cannot read property 'parentView' of undefined
    at execute.AppViewManager.getComponent (angular2.dev.js:26763)
    at angular2.dev.js:17442
    at Zone.run (angular2.dev.js:136)
    at Zone.execute.$__3._createInnerZone.zone.fork.fork.$run [as run] (angular2.dev.js:16756)
    at zoneBoundFn (angular2.dev.js:109)
    at lib$es6$promise$$internal$$tryCatch (angular2.dev.js:1391)
    at lib$es6$promise$$internal$$invokeCallback (angular2.dev.js:1403)
    at lib$es6$promise$$internal$$publish (angular2.dev.js:1374)
    at angular2.dev.js:187
    at execute.$__3._createInnerZone.zone.fork.fork.$scheduleMicrotask.microtask (angular2.dev.js:16782)
```

Adding a selector, or just removing everything inside `@Component` make everything works again.

Plnkr reproducing : http://plnkr.co/edit/SAXClK?p=preview

If this case is also being attacked in the issue referenced please close.

PS: Using alpha36

**Edit** plnkr updated to a54

**Comment by ericmartinezr** [comment]
Quite old issue, but it's still failing although the error is different

```
Uncaught (in promise): TypeError: Cannot read property 'visitExpression' of undefined
```

b.16 http://plnkr.co/edit/fhrc89?p=preview

Considering that the router is being rewritten I don't know if this should still be open. Up to anyone in charge.

**Comment by ericmartinezr** [comment]
Router is deprecated an dead, closing.

**Comment by arloduff** [comment]
The error `Uncaught (in promise): TypeError: Cannot read property 'visitExpression' of undefined` still comes up sometimes, and seems to be related to the router. I just got it because of a stray comma at the end of one of my routes:

    { path: 'foo', outlet: 'modal', component: FooComponent },,

**Comment by ericmartinezr** [comment]
@arloduff the error message doesn't show up anymore by a component without a selector which was the original issue reported here. The new one https://github.com/angular/angular/issues/12387 has a reproduction for your issue, track that one :+1:

**Comment by arloduff** [comment]
@ericmartinezr Thanks! I saw #1662 but didn't realize they had encountered that issue on #12387. Thanks for the followup!

**Comment by burhanyldz** [comment]
@arloduff Thanks, for double comma tip!
