### ISSUE TITLE
how to render rawhtml with mathml in angular?

### ISSUE THREAD

**Issue by aohan237** [angular/angular#40228]
for example.

using mathjax to render mathml in chrome.

a content modified by ckeditor5 with mathml.

what should i do if i want to render this rawhtml with mathml.

event if i use sanitizer.bypassSecurityTrustHtml, the rawhtml still cant render mathml.

**Comment by petebacondarwin** [comment]
Hello @aohan237, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by aohan237** [comment]
when i add this issue, there is an option that this is an support issue. i thought this may be the one .

thanks anyway

**Comment by petebacondarwin** [comment]
Yeah, sorry it is a bit confusing. When you click on the "support request" option you see this:

<img width="595" alt="Screenshot 2020-12-22 at 11 05 53" src="https://user-images.githubusercontent.com/15655/102882067-baa8f800-4445-11eb-84af-a22161184019.png">

which is supposed to discourage you.
