### ISSUE TITLE
refactor: include http and router in angular2.ts

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#4023]
As discussed in #3458, http and router will be included in the angular 2 bundle. So they should be imported in `modules/angular2/angular2.ts`. They should also be included in the `angular2.d.ts` typings.

This was planned to be done in #3713, but I decided to defer the change so I could land the giant PR ASAP.

**Comment by IgorMinar** [comment]
@jeffbcross is this still valid. should we close this?
