### ISSUE TITLE
Is there a way to support Android (6.0) or (5.0, 5.1) or (4.4) on Angular 9.0 or higher?

### ISSUE THREAD

**Issue by iamsjy17** [angular/angular#40231]
# 🚀 feature request

### Description

We are developing and serving web services using angular 8.

I've been using Angular for a long time and I've been constantly updating the version, but in Angular 9 I can't update the version due to the range of browser support.

I am worried that this problem will not be resolved over and over again.

Is there a way to support Android 4.4 to 6.0 on Angular 9+ including Polyfill?

or can we solve it by providing a different build option?
or is there any other way? 

I would like to solve this problem while keeping one source as possible.

**Comment by petebacondarwin** [comment]
While we are no longer testing against older versions of Android, I am not aware of any reason why they would not currently work with Angular 9+. Have you tried it?

The team will not be providing support for these versions but it is possible that they just work (perhaps dependent upon the features of Angular you use) or that it is possible to add polyfills. In any case, I would look to the community for support in setting this up - perhaps on StackOverflow (https://stackoverflow.com/questions/tagged/angular) or the Angular Discord (https://discord.gg/angular).
