### ISSUE TITLE
Documentation - explain how environment.ts gets switched by flags with CLI

### ISSUE THREAD

**Issue by ORESoftware** [angular/angular#40246]
# 🚀 feature request

Need to improve documentation for  `ng build --prod` or `ng build --env=prod`

### Relevant Package
Not sure which package

### Description

Here is the problem - it is highly unclear how Angular switches between environment.XXX.ts files.
The flag should also be:

```
ng build --prod --env=prod
ng build --env=dev
ng build --env=test
```

How am I suppose to import the file? If I import environment.prod, how am I not tied to that config? If I import environment.dev, how am I not tied to that config? It makes ZERO sense to me and all the answers on StackOverflow demonstrate that it makes ZERO sense to anyone else.

As you can see here, I can import environment.dev:
--------------------------------

![Screen Shot 2020-12-22 at 4 57 04 PM](https://user-images.githubusercontent.com/11139560/102946994-235c9880-4477-11eb-9c57-0d082bb1510d.png)

And as you can see here, I cannot import just "environment":
-----------------
![Screen Shot 2020-12-22 at 4 57 13 PM](https://user-images.githubusercontent.com/11139560/102946996-25265c00-4477-11eb-851e-88880ae8c930.png)

**Comment by ORESoftware** [comment]
Alright I found the documentation:

https://angular.io/guide/build

so it's not this:

```bash
ng build --prod --env=prod
```

instead it's this:

```bash
ng build --prod --configuration=prod
```

however the remaining problem is that I can't use environment.ts in a library project? only an application project?

**Comment by destus90** [comment]
@ORESoftware see this for more context https://github.com/nrwl/nx/issues/208, https://github.com/angular/angular/issues/36190
Also, there is an [`isDevMode`](https://angular.io/api/core/isDevMode) function that you can use in a lib.

**Comment by alan-agius4** [comment]
> ```shell
> ng build --prod --configuration=prod
> ```

`-—prod` is an alias for `—-configuration production`. The environment file is replaced using file replacements. https://angular.io/guide/build#configure-environment-specific-defaults

And it is correct that this feature is only available at application level.

Dependency injection is the preferred way of change the configuration of a library. If it does need to be configured to run with different context

See the below for more information:
https://angular.io/guide/singleton-services#the-forroot-pattern
https://offering.solutions/blog/articles/2019/12/31/configuring-angular-libraries/

Closing as this issue tracker is not suitable for support requests.

**Comment by ORESoftware** [comment]
my support request is to allow for a configuration switch for libs not just applications

i have the same config for all apps, so putting the config/environment.ts in a lib makes sense to me.
