### ISSUE TITLE
Documentation - how to import file from library generated in projects folder

### ISSUE THREAD

**Issue by ORESoftware** [angular/angular#40245]
# 🚀 feature request

I tried asking on the angular google groups 

### Relevant Package
Probably angular core but uncertain.

### Description

<img width="1000" alt="Screen Shot 2020-12-22 at 4 38 04 PM" src="https://user-images.githubusercontent.com/11139560/102945991-3752cb00-4474-11eb-85c4-d94ec3a5ce25.png">

### Describe the solution you'd like

The only solution I can think of is symlinking the tools library to node_modules?
Something like:

```
ln -sf "$PWD/projects/tools" "$PWD/node_modules/@self/tools"
```

but is this feature built in? right now i have this ugly imports path:

```
import {AuthService} from "../../../tools/src/lib/auth.service";

```

**Comment by alan-agius4** [comment]
The answer on discord is correct, that is how to consume a library. For more information please see the relevant documentation here: https://angular.io/guide/creating-libraries#using-your-own-library-in-apps 

To avoid collisions you can name the packages using a scope. Example: `@myorg/tools`.
