### ISSUE TITLE
what features I wanted to be supported

### ISSUE THREAD

**Issue by shybaLen** [angular/angular#40248]
# 🚀 feature request

### Relevant Package

1. support json to component render. now only define in component template can works to binding. but I think ivy can support json to component binding. json define is a component that can be rendered when a componet use it.
2. support template anonymous declaration
3. support input output spread binding. spread a object binding. angular can detect on object property change. and spread it to class input. may be [...inputs] (...outputs) / [...]="inputs" (...)="outputs"
4. remove zone.js
5. support none host tag render. host tag behavior as template. component host tag can not be rendered. maybe supported as `@Template()` component, can be renderred by ng-template outlet

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by josephperrott** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate

We are happy to investigate feature requests you have, however to be able to understand and investigate them properly, we rely on the consistency provided by the feature request template.
