### ISSUE TITLE
Angular 5 minimum browser version allowed

### ISSUE THREAD

**Issue by JLOPE71** [angular/angular#40256]
Hi, I am interested to obtain the minimum versions in Chrome, Firefox and Safari to well-run an Angular 5 Application with Typescript 2.6.2.

Thanks.

**Comment by itea-dev** [comment]
You can find all supported browsers in the docs for version 2 of Angular. 

https://v2.angular.io/docs/ts/latest/guide/browser-support.html

If you have more questions, please join the discord server or the gitter/matrix channel for Angular. 

https://discord.gg/nJMXZK9V7f

**Comment by pranavkumar389** [comment]
https://dev-custhub.lle.risecredit.com/

**Comment by josephperrott** [comment]
You can find our browser support for each version on our docs pages (including the archived docs for the older versions).  For version five you can find the supported browsers [here](https://v5.angular.io/guide/browser-support).
