### ISSUE TITLE
Angular Library Project: How to allow the user to import the files from the folder which are publicly available

### ISSUE THREAD

**Issue by FahadRS** [angular/angular#40258]
we are creating the angular library project which contains all services, models, pipes, directives

following is the folder structure which i have created the library project

![image](https://user-images.githubusercontent.com/48184059/103066830-79e2e780-45db-11eb-8e3c-f6c56a9816fb.png)

i have exposed all these files in the public-api file like below 

```
export * from './lib/services/shared.services/app-events.shared.service';
export * from './lib/services/shared.services/campaign-action-bar.shared.service';
```

now when i try to import the files in the main project i am able to import it like this

`import { AppEventSharedService } from '@ngcore'`

my questions is, is there any way i can customize my imports to 

`import { AppEventSharedService } from '@ngcore/services'`

**Comment by sonukapoor** [comment]
You can use the tsconfig's `path` property to do that:

"paths": {
    "@ngcore/services/*": ["dist/services/*"]
}

Please note that this issue doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
