### ISSUE TITLE
service-worker not initializing when 'enabled' is a variable 

### ISSUE THREAD

**Issue by capc0** [angular/angular#40252]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/service-worker

### Is this a regression?

 No

### Description

Setting the enabled property of the ServiceWorkerModule.register function to a boolean variable instead of a const expression (true/false) does not register the service worker even if the variable becomes true.

Propably because of AoT compilation(?)

## 🔬 Minimal Reproduction

 

this does not work
```ts
const serviceWorkerEnabled = !!(config.general.production && (window as any).cordova == null);
console.log(`[ServiceWorker] enabled: ${serviceWorkerEnabled}`); // prints true

ServiceWorkerModule.register('./ngsw-worker.js', {
            enabled: serviceWorkerEnabled ,
            registrationStrategy: 'registerImmediately',
        }),
```
this does work
```ts

ServiceWorkerModule.register('./ngsw-worker.js', {
            enabled: true,
            registrationStrategy: 'registerImmediately',
        }),
```

I have tested it with the following override to make sure that the function is not called
```ts
const originalFn = navigator.serviceWorker.register;
navigator.serviceWorker.register = (a: any, b: any) => {
    console.log('registration called');
    return originalFn(a,b);
};
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 11.0.4
Node: 14.15.0
OS: win32 x64

Angular: 11.0.4
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: No

Package                         Version
---------------------------------------------------------       
@angular-devkit/architect       0.1100.4
@angular-devkit/build-angular   0.1100.4
@angular-devkit/core            11.0.4
@angular-devkit/schematics      11.0.4
@angular/service-worker         11.0.5
@schematics/angular             11.0.4
@schematics/update              0.1100.4
rxjs                            6.5.5
typescript                      4.0.5

</code></pre>

**Comment by petebacondarwin** [comment]
What happens if you do the following?

```ts
ServiceWorkerModule.register('./ngsw-worker.js', {
            enabled: !!(config.general.production && (window as any).cordova == null) ,
            registrationStrategy: 'registerImmediately',
        }),
```

**Comment by capc0** [comment]
That also does not register the service worker.

Can I check in any of the build output files what the expression gets transpiled to? After ng-build (without --prod) the app.module basically only becomes this in the main.js chunk

```js
class AppModule {
}
exports.AppModule = AppModule;
```

**Comment by petebacondarwin** [comment]
Can you try turning on ivy?

**Comment by capc0** [comment]
Yes, with ivy its working.

part of the main-es2015.js

```js
service_worker_1.ServiceWorkerModule.register('./ngsw-worker.js', {
                enabled: !!(config_1.config.general.production && window.cordova == null),
                registrationStrategy: 'registerImmediately',
            }),
```

also working at runtime.

**Comment by petebacondarwin** [comment]
This is a limitation of the ViewEngine compiler, which has been fixed in Ivy. It will not be fixed in ViewEngine, as this is now deprecated. I suggest you try to upgrade your project to use Ivy instead.

**Comment by capc0** [comment]
Thank you for the quick responses.

I can understand and accept that it will not be fixed in ViewEngine anymore.

We will migrate over to ivy as soon as the blocker issues (atleast in our perspective - especially # 20007) have been resolved. But that should not be the topic of this issue.

**Comment by gkalpak** [comment]
@capc0, I believe you can work around this ViewEngine limitation by using the [SwRegistrationOptions][1] DI token. (See the docs for an example.)

[1]: https://angular.io/api/service-worker/SwRegistrationOptions
