### ISSUE TITLE
Problem with Tour of heroes app for Angular 9 [solved]

### ISSUE THREAD

**Issue by srahul123** [angular/angular#40268]
# 📚 Docs or angular.io bug report

### Description

In the Tour of Heroes app, angular two way binding as given here - https://v9.angular.io/tutorial/toh-pt1#two-way-binding is not working. Even when I type something into the input box, the heading is not updated. It works if I replace placeholder="name" with placeholder="name123". I don't know the reason. If that is the expected behaviour, please update the documentation.

### What's the affected URL?**
https://v9.angular.io/tutorial/toh-pt1#two-way-binding

### Reproduction Steps**

Installed angular in a docker container and followed the steps given in the "Tour of Heroes" tutorial .

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Browser info
Chromium 87.0.4280.88 on OpenSUSE

**Comment by sonukapoor** [comment]
@srahul123 I tried this in the provided stackblitz of the page and can see that this is working as expected. 

https://stackblitz.com/angular/xerrqenrqjb?file=src%2Fapp%2Fheroes%2Fheroes.component.html

Can you double-check your code with the one from the stackblitz? You can also download it from here:

https://v9.angular.io/generated/zips/toh-pt1/toh-pt1.zip

**Comment by gkalpak** [comment]
As @sonukapoor said, this should work as expected. If you are still running into issues, please provide a minimal reproduction (for example, a StackBlitz project demonstrating the problem).

**Comment by huhansome** [comment]
阿里云服务器低至96/年，学生价9.5/年
https://www.aliyun.com/minisite/goods?source=5176.11533457&userCode=j6bryttg

阿里云数据库限时折扣，低至188/年
https://www.aliyun.com/activity/ambassador/database?source=5176.11533457&userCode=j6bryttg

阿里云企业级服务器1折限时特惠
https://promotion.aliyun.com/ntms/act/enterprise-discount.html?source=5176.11533457&userCode=j6bryttg

阿里云建站 速成美站 - 千套模板，价格低至500元
https://ac.aliyun.com/application/webdesign/sumei?source=5176.11533457&userCode=j6bryttg

CDN爆款产品低至5.5折
https://yqh.aliyun.com/live/cdncarnival?userCode=j6bryttg&source=5176.11533457&userCode=j6bryttg
