### ISSUE TITLE
@ViewChild(MatPaginator, {static: true}) public paginator:MatPaginator not use angular 11

### ISSUE THREAD

**Issue by dtelthai** [angular/angular#40263]
<!--🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅
@ViewChild(MatPaginator, {static: true}) public paginator:MatPaginator not use angular 11 but i make to @ViewChild(MatPaginator, {static: true}) public paginator!:MatPaginato i add ! back  public paginator! plase tel me true write for me thank your

**Comment by dtelthai** [comment]
"strictPropertyInitialization": false,   
write to tsconfig.json
is ok

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "strictPropertyInitialization": false, //********* ok 
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true,
    "enableIvy": false
  }
}

**Comment by sonukapoor** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
