### ISSUE TITLE
Docs: Add 'Adding reactivity' section to 'Try It' in the 'Getting Started' guide

### ISSUE THREAD

**Issue by eneajaho** [angular/angular#40275]
# 📚 Docs or angular.io bug report

### Description

In the **[Try It](https://angular.io/start)** section the shopping app that is being created is small and doesn't fully show the power of Angular's (with RxJS) reactivity system. 
 - What do I mean by that? 
In the current app, the user can buy things, and they get added to the cart. 
On click of the buy button, the app shows just an alert that the item was bought and that's all
(the item is added in the cart items array in the service in the background). 
If we want to show the number of the cart items on the **top bar component** we cannot do it by just showing the length of the cart items array.  Like this: 
```ts
export class TopBarComponent {
  count = this.cart.getItems().length;
  constructor(private cart: CartService) {}
}
```
```html
<a routerLink="/cart" class="button fancy-button">
  <i class="material-icons">shopping_cart</i>
  Checkout {{ count }}
</a>
```

It won't work, because when we buy another item the change detection will not be triggered for that component, because Angular isn't listening to that value.  And here is where RxJS comes into play. 

What we can do is to introduce a `BehaviourSubject` in the cart service and explain it and the pros of using RxJS for this kind of use-cases.
It can be a simple pattern like this:  
```ts
export class CartService {
  private items = new BehaviorSubject<Product[]>([]);
  items$ = this.items.asObservable().pipe(distinctUntilChanged());

  cartCount$ = this.items$.pipe(map(items => items.length));

  addToCart(product: Product): void {
    const currentItems = this.items.getValue();
    this.items.next([...currentItems, product]);
  }

  clearCart(): void {
    this.items.next([]);
  }
}
```
and use it like this: 
```ts
@Component({
  ...
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class TopBarComponent {
  cartCount$ = this.cartService.cartCount$;

  constructor(private cartService: CartService) {}
}
```
```html
<a routerLink="/cart" class="button fancy-button">
  <i class="material-icons">shopping_cart</i>
  Checkout ({{ cartCount$ | async }})
</a>
```

I also have created a repo with the app and it uses the RxJS functionalities to add reactivity to the app. [Try It App with RxJS.](https://stackblitz.com/edit/angular-hhwc8c?file=src/app/cart.service.ts)

Also, if this gets added, we can also introduce the dev to `async` pipe, `ChangeDetectionStrategy.OnPush` and Immutability

**Comment by Airblader** [comment]
If it does get added, which as a fan of reactivity I'd favor, let's please lead with a good example and not access `value`.

> Important note from the author of RxJS 5: Using getValue() is a HUGE red flag you're doing something wrong. It's there as an escape hatch. Generally everything you do with RxJS should be declarative. getValue() is imperative. If you're using getValue(), there's a 99.9% chance you're doing something wrong or weird.

https://stackoverflow.com/questions/37089977/how-to-get-current-value-of-rxjs-subject-or-observable/45227115

On another side note, I don't know what the purpose of `distinctUntilChanged` would be in this case as it will never do anything.

**Comment by eneajaho** [comment]
> If it does get added, which as a fan of reactivity I'd favor, let's please lead with a good example and not access `value`.
> 
> > Important note from the author of RxJS 5: Using getValue() is a HUGE red flag you're doing something wrong. It's there as an escape hatch. Generally everything you do with RxJS should be declarative. getValue() is imperative. If you're using getValue(), there's a 99.9% chance you're doing something wrong or weird.
> 
> https://stackoverflow.com/questions/37089977/how-to-get-current-value-of-rxjs-subject-or-observable/45227115
> 
> On another side note, I don't know what the purpose of `distinctUntilChanged` would be in this case as it will never do anything.

Hello, 
I understand that we should not get the value directly and why it's not a good approach. 
But in this use-case, what is the best way to get the current value of the `items` `BehaviorSubject`, in order to use it to create a new array of items? 
```ts
  addToCart(product: Product): void {
    const currentItems = this.items.value;
    this.items.next([...currentItems, product]);
  }
```

**Comment by huhansome** [comment]
阿里云服务器低至96/年，学生价9.5/年
https://www.aliyun.com/minisite/goods?source=5176.11533457&userCode=j6bryttg

阿里云数据库限时折扣，低至188/年
https://www.aliyun.com/activity/ambassador/database?source=5176.11533457&userCode=j6bryttg

阿里云企业级服务器1折限时特惠
https://promotion.aliyun.com/ntms/act/enterprise-discount.html?source=5176.11533457&userCode=j6bryttg

阿里云建站 速成美站 - 千套模板，价格低至500元
https://ac.aliyun.com/application/webdesign/sumei?source=5176.11533457&userCode=j6bryttg

CDN爆款产品低至5.5折
https://yqh.aliyun.com/live/cdncarnival?userCode=j6bryttg&source=5176.11533457&userCode=j6bryttg

**Comment by mgechev** [comment]
We'll be reworking our getting started journey. Let's close this feature request for now and consider it as part of the refactoring efforts.
