### ISSUE TITLE
refactor: deprecate angular2/angular2 import for dart

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#4027]
As discussed with @yjbanov, we should deprecate the angular2/angular2 export in Dart since users are encouraged to import `angular2/core` most often, as well as `angular2/bootstrap` when defining root components. The `angular2/angular2` import is most useful for JavaScript developers who are using the full angular2.js bundle.

I'd originally added this line at the top of angular2.dart as part of #3713, but Dart Analyzer complained about this since some tests and examples were still importing angular2/angular2. So I deferred the change so that I could land the massive PR more quickly.

Here is the deprecation line I originally included at the top of angular2.dart:

```dart
@Deprecated('use import angular2/core and angular2/bootstrap instead of angular2')
```

**Comment by IgorMinar** [comment]
@yjbanov could you send a PR for this tomorrow please?

**Comment by yjbanov** [comment]
This is more than PR. We need to migrate existing code prior to landing this. Putting `@deprecated` on `angular2/angular2.dart` would throw a tsunami of warnings into people's code. I'm expecting that migration should be relatively easy using an automated tool.

**Comment by mhevery** [comment]
Will not implement.
