### ISSUE TITLE
Strange behaviour with ngModel and looping over the array

### ISSUE THREAD

**Issue by kucharzyk** [angular/angular#40271]
# 🐞 bug report

### Description

I've created simple input using ngFor and ngModel connected to array element.

```ts
 data = [
   "","","","","","","","","","",
   "","","","","","","","","","",   
 ]
```

```html
<input 
*ngFor="let el of data;let i = index"
[(ngModel)]="data[i]"
type="text"/>
```

After focusing first input and typing one character:
* input value changes
* focus is lost and moves to next input
* the following input value is set to previous input value
* after typing another character whole text is copied to next input and it gain focus 

Can anyone explain this behaviour?  It looks like the bug

## 🔬 Minimal Reproduction

https://angular-ivy-zqddgu.stackblitz.io

## Solution
Adding trackBy function to *ngFor (using array index) solves the issue

## 🌍  Your Environment

**Angular Version:**
<pre>
Tested with both angular 10 and 11
</pre>

**Comment by jnizet** [comment]
You need to use an array of objects, and bind to a property of those objects, or to use trackBy and track by index: your ngModel replaces a string in the array by another string, thus forcing Angular to delete the DOM node which has the focus and recreate it, causing the focus to be lost.

**Comment by kucharzyk** [comment]
Thanks for the details @jnizet it make sense about losing focus.
But what's about input value - it's copied from one input to another?

**Comment by jnizet** [comment]
AFAIU, the focus is given to the next input node as soon as the input event has been processed by Angular, and the keydown event thus happens while the next input node has the focus, causing the browser to display the character in the next input node, too.

**Comment by AndrewKushnir** [comment]
Hi @kucharzyk, it looks like @jnizet provided an answer, so I'm going to close this ticket. Please reopen if the problem still exists. Thank you.
