### ISSUE TITLE
How to align breadcrumbs using recursive components Angular 9

### ISSUE THREAD

**Issue by afeef1915** [angular/angular#40278]
Question
>How to align breadcrumbs in recursive template using ngTemplateOutlet Angular 9

![image](https://user-images.githubusercontent.com/16572202/103347114-10bc1200-4abc-11eb-850e-ecfdf53dcbaa.png)

List view
![image](https://user-images.githubusercontent.com/16572202/103347123-187bb680-4abc-11eb-876f-5d2e9b66bb19.png)

I need output

Home/A/A1/B1/C/C1/F/F1

Home/Org/Org Child

       <div *ngIf="nodes && nodes.length > 0">
             <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <ng-container *ngFor="let child of nodes">
                <li class="breadcrumb-item active">
                    {{child.name}}
                    <ng-container *ngTemplateOutlet="treetest;context:{nodes:child.children}">
                    </ng-container>
                </li>
            </ng-container>
        </ol>
    </nav>
     </div>

import { Component, OnInit } from "@angular/core";

@Component({
  selector: "my-app",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent implements OnInit {
  name = "Angular";
  jsonValue: any;
  childernNodes = [];
  dataSet: any = {};
  jsonNodes = [];
  constructor() {}

  jasonData = {
    api_details: {
      api_success: "Y",
      data: {
        main_menu_items: [
          {
            id: "149",
            code: "DD",
            name: "Home"
          },
          {
            id: "150",
            code: "RR",
            name: "A",
            children: [
              {
                id: "151",
                code: "GG",
                name: "A1"
              },
              {
                id: "152",
                code: "RTRT",
                name: "B1"
              },
              {
                id: "153",
                code: "ERFTERTE",
                name: "C",

                children: [
                  {
                    id: "154",
                    code: "ERTEEER",
                    name: "C1"
                  },
                  {
                    id: "154",
                    code: "ERTEEER",
                    name: "F",
                    children: [
                      {
                        id: "154",
                        code: "ERTEEER",
                        name: "F1"
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            id: "164",
            code: "ERER",
            name: "Org",

            children: [
              {
                id: "167",
                code: "fsfsdrert",
                name: "Org Child"
              }
            ]
          }
        ]
      }
    }
  };
  ngOnInit() {
    let jsonValues = JSON.stringify(this.jasonData);
    const fecthobject = JSON.parse(jsonValues);
    this.jsonNodes = fecthobject.api_details.data.main_menu_items;
    console.log(this.jsonNodes);
  }
}

**Comment by petebacondarwin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
