### ISSUE TITLE
ability to receive data that service worker fetch from network

### ISSUE THREAD

**Issue by Zuckjet** [angular/angular#40277]
# 🚀 feature request

### Relevant Package
This is for @angular/service-worker

### Description
As [Angular Service worker doc](https://angular.io/guide/service-worker-config) described:

> You can also emulate a third strategy, staleWhileRevalidate, which returns cached data (if available), but also fetches fresh data from the network in the background for next time.

If we can receive the `fresh data` in our code, we can compare the `fresh data` with the `cache data `that the application is using, and to do sth like: **Show content from cache, update cache in background and show updated content as soon as it arrives**

### Describe the solution you'd like
I would like to do this in my code like:
```
this.serviceWorker.subscribe((data, url)=> {
  if (data != old data) {
    update application
  }
})
```

**Comment by huhansome** [comment]
阿里云服务器低至96/年，学生价9.5/年
https://www.aliyun.com/minisite/goods?source=5176.11533457&userCode=j6bryttg

阿里云数据库限时折扣，低至188/年
https://www.aliyun.com/activity/ambassador/database?source=5176.11533457&userCode=j6bryttg

阿里云企业级服务器1折限时特惠
https://promotion.aliyun.com/ntms/act/enterprise-discount.html?source=5176.11533457&userCode=j6bryttg

阿里云建站 速成美站 - 千套模板，价格低至500元
https://ac.aliyun.com/application/webdesign/sumei?source=5176.11533457&userCode=j6bryttg

CDN爆款产品低至5.5折
https://yqh.aliyun.com/live/cdncarnival?userCode=j6bryttg&source=5176.11533457&userCode=j6bryttg
