### ISSUE TITLE
@angular/compiler-cli downleveling decorators possibly causing RangeError: Maximum call stack size exceeded with isReferencedAliasDeclaration

### ISSUE THREAD

**Issue by simply10w** [angular/angular#40276]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler-cli version >=10

### Is this a regression?

 Yes, the previous version in which this issue was not happening was: 9

It started happening in Angular 10 with the introduction of decorator downleveling: 
```
compiler-cli: downlevel angular decorators to static properties (#37382) (323651b), closes #30586 #30106 #30586 #30141
```
PR: https://github.com/angular/angular/pull/37382 
### Description

We just did an upgrade from Angular 9->11 and started seeing this problem in our biggest application when we run ng serve. 

We have a monorepo setup with Nx. After the upgrade we were able to start 3 other applications that are a little bit smaller than previously mentioned one.

Since the error is quite unclear i started investigating what could be the cause and found only one issue report similar to this one here:

https://github.com/angular/angular-cli/issues/18792 

But that seemed to be an issue that was caused in their own setup. I also looked if we had anything similar, but with no luck. 

I also tried doing divide and conquer approach removing some modules from the application and that made it work. However there was no exact rule which modules work and which dont, the distribution was quite random expect one thing if i made the app smaller, then it worked(by removing bigger modules).

Next on my list was to add some logging in `patchAliasReferenceResolutionOrDie` for the nodes that were being traversed and I did not see any circular dependency that would cause an infinite recursion.

Then i tried adjusting the implementation of `isReferencedAliasDeclaration` and was able to make this work by changing this part here:

```ts
// Before 
emitResolver.isReferencedAliasDeclaration = function(node, ...args) {
    if (isAliasImportDeclaration(node) && referencedAliases.has(node)) {
      return true;
    }
    return originalReferenceResolution.call(emitResolver, node, ...args);
  };

// After 
emitResolver.isReferencedAliasDeclaration = function(node, checkChildren) {
    if (isAliasImportDeclaration(node) && referencedAliases.has(node)) {
      return true;
    }
    return originalReferenceResolution.call(emitResolver, node, checkChildren);
  };
``` 
https://github.com/angular/angular/blob/master/packages/compiler-cli/src/transformers/patch_alias_reference_resolution.ts#L87

This change was made so that `isReferencedAliasDeclaration` looks exactly like the typescript implementation https://sourcegraph.com/github.com/microsoft/TypeScript@3eaa7c65f6f076a08a5f7f1946fd0df7c7430259/-/blob/src/compiler/checker.ts#L36179-36192 

And this fixed the issue. 

My 2 cents on why this fixed it is better explained when looking at compiled code of the function

```js
// Before
emitResolver.isReferencedAliasDeclaration = function (node) {
    var args = [];
    for (var _i = 1, _len = arguments.length; _i < _len; _i++) {
      args[_i - 1] = arguments[_i];
    }
    if (isAliasImportDeclaration(node) && referencedAliases.has(node)) {
       return true;
    }
    return originalReferenceResolution.call.apply(originalReferenceResolution, tslib_1.__spread([emitResolver, node], args));
};

// After 
emitResolver.isReferencedAliasDeclaration = function (node, checkChildren) {
    if (isAliasImportDeclaration(node) && referencedAliases.has(node)) {
        return true;
    }
    return originalReferenceResolution.call(emitResolver, node, checkChildren);
};
```

During tree traversal `isReferencedAliasDeclaration` in each call is creating its own local array copying the arguments and then spreading that back again to original implementation, so i suppose after certain number of calls the memory just gets over allowed threshold and breaks. 

## 🔥 Exception or Error
<pre><code>

Error: RangeError: Maximum call stack size exceeded
    at Set.has (<anonymous>)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:84:69)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:87:53)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:87:53)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:87:53)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:87:53)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:87:53)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:87:53)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:87:53)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:87:53)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:87:53)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:87:53)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:87:53)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:87:53)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:87:53)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:87:53)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

    _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 11.0.5
Node: 12.18.2
OS: darwin x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1100.5
@angular-devkit/build-angular      0.1100.5
@angular-devkit/core               11.0.5
@angular-devkit/schematics         11.0.5
@angular/cdk                       11.0.3
@angular/flex-layout               11.0.0-beta.33
@angular/google-maps               11.0.3
@angular/material                  11.0.3
@angular/material-moment-adapter   11.0.3
@nguniversal/express-engine        11.0.1
@schematics/angular                11.0.5
@schematics/update                 0.1100.5
rxjs                               6.5.5
typescript                         4.0.5
</code></pre>

**Anything else relevant?**

I am still not sure if this is something that is specific to our application, since i suppose there are bigger apps out there that would then have the same issue and would be known. 

If you think this is something specific to us, can you please give some ideas how we could debug this further?

**Comment by petebacondarwin** [comment]
Thanks for the detailed investigation @simply10w. The proposed fix looks like a reasonable change in any case, especially if it prevents the problem for you.

It seems strange that, from the call stack, the code appears to be recursing into itself at `isReferencedAliasDeclaration()`...

Oh!

Here is a thing... I see that we are capturing the original `isReferencedAliasDeclaration()` method in `originalReferenceResolution` and then calling it in the patched version of the method. I wonder if `patchAliasReferenceResolutionOrDie()` is being called more than once, with a `ts.TransformationContext` that is returning the same object from `context.getEmitResolver()`. This would result in use "patching" the method twice, which would also capture the original value of the method again but this time capturing itself.

**Comment by petebacondarwin** [comment]
This analysis also appear to fit with the line numbers in the stack trace...

```ts
79 | emitResolver.isReferencedAliasDeclaration = function (node) {
80 | var args = [];
81 | for (var _i = 1; _i < arguments.length; _i++) {
82 | args[_i - 1] = arguments[_i];
83 | }
84 | if (isAliasImportDeclaration(node) && referencedAliases.has(node)) {
85 | return true;
86 | }
87 | return originalReferenceResolution.call.apply(originalReferenceResolution, tslib_1.__spread([emitResolver, node], args));
88 | };
```

Line 87 is calling line 84

**Comment by simply10w** [comment]
Yeah, that makes sense, basically re-patching on itself

 - if this happens only twice, then worst case scenario would be its just extra call overhead that could increase time and memory
 - if this happens multiple times over and over at some point for some node it will be invoked to many times that would break
 
 Btw, i have used git patch with above fix in the meantime to wrap up the upgrade process on our end and so far everything works good both ng serve and build(including server side builds)

**Comment by JoostK** [comment]
It does indeed look like the patch is applied multiple times, more specifically for each source file:

https://github.com/angular/angular/blob/0929099e41794d422c2a6ddf76a9eef85e7e6920/packages/compiler-cli/src/transformers/downlevel_decorators_transform.ts#L597-L603

so the patch function has to call through all previously installed patch functions, which could certainly introduce a lot of stack frames. I don't see how the proposed change addresses this problem, but perhaps the stack frames become smaller due to certain optimization opportunities such that more stack frames are available.

**Comment by simply10w** [comment]
Then a check here if isReferencedAliasDeclaration has already been patched on emitResolver would solve it i suppose?

https://github.com/angular/angular/blob/0929099e41794d422c2a6ddf76a9eef85e7e6920/packages/compiler-cli/src/transformers/patch_alias_reference_resolution.ts#L75-L88

**Comment by JoostK** [comment]
I suspect the `patchAliasReferenceResolutionOrDie` call I mentioned before can be moved outside of the source file callback, so that the patch is only registered once for the context.

**Comment by simply10w** [comment]
I've just tested this with moving the patching outside the visitor function but in the scope of the function that provides the context 

```ts
//Before
return function (context) {
  ...
  return (sf: ts.SourceFile) => {
    patchAliasReferenceResolutionOrDie(context, referencedParameterTypes);
    return ts.visitEachChild(sf, decoratorDownlevelVisitor, context); 
  };
}

//After
return function (context) {
  ...
  patchAliasReferenceResolutionOrDie(context, referencedParameterTypes);
  return (sf: ts.SourceFile) => {
    return ts.visitEachChild(sf, decoratorDownlevelVisitor, context); 
  };
}
```

and got similar error

```
Error: RangeError: Maximum call stack size exceeded
    at Object.isBinaryExpression (/monorepo/node_modules/typescript/lib/typescript.js:25788:32)
    at isAliasSymbolDeclaration (/monorepo/node_modules/typescript/lib/typescript.js:44450:20)
    at isReferencedAliasDeclaration (/monorepo/node_modules/typescript/lib/typescript.js:76121:17)
    at Object.isReferencedAliasDeclaration (/monorepo/node_modules/typescript/lib/typescript.js:76442:35)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:88:53)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:88:53)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:88:53)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:88:53)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:88:53)
    at Object.emitResolver.isReferencedAliasDeclaration (/monorepo/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:88:53)
```

When i added the same optimisation as before by using checkChildren instead of spreading arguments it works properly

**Comment by petebacondarwin** [comment]
I note that `getDownlevelDecoratorsTransform()` actually returns a transform function, and moving this call to `patchAliasReferenceResolutionOrDie()` up one level means that it is still called every time the transform is run, which could actually be for every source-file (or perhaps every root-file?).

So I think that the patching would need to be moved even further up, but of course then you don't have direct access to the `context` that needs to be patched. Since `emitResolver` appears to be a simple object (and not class) we cannot try to monkeypatch the method on the prototype. So I think the only option is to detect whether the function has already been patched - perhaps by storing the original method on the object (e.g. `isReferencedAliasDeclaration__original`).

**Comment by JoostK** [comment]
I did some more investigation and found that the `ts.EmitResolver` that is being patched is owned by the `ts.TypeChecker`, whereas the `ts.TransformationContext` is created multiple times for each source file. That explains why moving the line as suggested didn't work, as already hinted by Pete.

I have opened #40374 with a fix, which ensures that the patch is only applied once.

**Comment by galczo5** [comment]
Hi, can you tell me how long it usually takes to deploy a fix like this? It blocks my upgrade from version 9 to 11.

**Comment by JoostK** [comment]
> Hi, can you tell me how long it usually takes to release a fix like this? It blocks my upgrade from version 9 to 11.

I expect the PR to be merged today, so that it'll be in the next release (usually on Wednesday).

**Comment by VlasovSergey** [comment]
Hi, will you apply for angular 10? We have the same issue on Angular 10.

**Comment by JoostK** [comment]
> Hi, will you apply this fix for angular 10? We have the same issue on Angular 10.

Hi, sorry, this won't get patched in Angular 10. A workaround might be to enlarge the max stack size of the Node process using the `--stack_size` option.
