### ISSUE TITLE
refactor: move angular2/lifecycle into angular2/core

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#4028]
3d38ec8aacaaaeb5a4b1e563243ed927bb4d0f03 introduces a new module for `angular2/lifecycle_hooks`, but I think this should be exported from `angular2/core` since our current approach is for core to have all of the basic building blocks of an angular application. 

Task:
 * Move `modules/angular2/lifecycle_hooks.ts` to `modules/angular2/src/core/lifecycle_hooks.ts`
 * Re-export all `lifecycle_hooks` exports from `modules/angular2/core.ts`

@vicb I landed a big PR for #3713 right after this merged in, which reduced the amount of import targets for angular2. Does this change make sense, or is there some use case I'm not thinking about?

**Comment by vicb** [comment]
I've only moved the hooks in a separate file for doc purpose (ie to have all of them documented in one  place and be able to link to the module from directives inline doc).

If moving them to core still allows that, I'm +1

**Comment by tyleranton** [comment]
Is this already being worked on? I'd like to start contributing to this project.

**Comment by jeffbcross** [comment]
@tyleranton please take it!

**Comment by tyleranton** [comment]
@jeffbcross awesome, will do!

**Comment by tyleranton** [comment]
There's an existing lifecycle folder in `src/core`

Should it go in

`modules/angular2/src/core/lifecycle/lifecycle_hooks.ts`

instead of 

`modules/angular2/src/core/lifecycle_hooks.ts`

**Comment by jeffbcross** [comment]
@tyleranton I would just move it into `src/core`.

**Comment by tyleranton** [comment]
@jeffbcross Cool, got it done. Last question.

> Re-export all lifecycle_hooks exports from modules/angular2/core.ts

When re-exporting all `lifecycle_hooks` exports, should it be done like so:

```
export {
  AfterContentInit,
  AfterContentChecked,
  AfterViewInit,
  AfterViewChecked,
  OnChanges,
  OnDestroy,
  OnInit,
  DoCheck
} from 'modules/angular2/core';
```

Or is there a way to specify exporting only `lifecycle_hooks` from `angular2/core`?

**Comment by mhevery** [comment]
This should be in `angular2/core/contracts` per #4834

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/commit/125fa3885ec7f3ccfbc75849071eb88a9d663a14
