### ISSUE TITLE
Feature request : how we can add the root in the Class Decorator in angular 

### ISSUE THREAD

**Issue by achrefabdeljalil** [angular/angular#40291]
# 🚀 feature request

### Relevant Package
 This feature request is for @angular/router

### Description
Recently, after discovering many programming techniques, I found that all techniques are used **annotation**
like we sees in the photo           
But I found that **Angular** put it in the **appModule** file or in a separated file but all the root are in the same places          
That is why I said, why don't we work on making the technology similar to the rest of the technologies 
for exemple if your component is a page in your template you can add @({root:"/RootName"}) as a decorator to the component class
         
```
// this the decorator 
@Route({ root: "/todo" })
@Component({
  selector: 'app-todos',
  templateUrl: './todos.component.html'
})
export class TodosComponent implements OnInit {
  newTodo: any;
  todos: Todo[]
...
```

### Describe the solution you'd like
I have not a Solution 😓😓

**Comment by geromegrignon** [comment]
There is no `@angular/root` package.
Are you talking about **routes** and `@angular/router`?

**Comment by achrefabdeljalil** [comment]
Big thaanks @geromegrignon for your  interaction ❤💚💙
In this case i'm talking about : how we can  add the root option in the decorator of class component that display like a page 
like in other Backend framework technologies for exemple (spring boot , symfony ...)
`
// src/Controller/BlogApiController.php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BlogApiController extends AbstractController
{
    /**
     * @Route("/api/posts/{id}", methods={"GET","HEAD"})
     */
    public function show(int $id): Response
    {
        // ... return a JSON response with the post
    }

    /**
     * @Route("/api/posts/{id}", methods={"PUT"})
     */
    public function edit(int $id): Response
    {
        // ... edit a post
    }
}
`
in place of making a **routes** array in app.module.ts

**Comment by geromegrignon** [comment]
Please update your both messages by changing **root** by **route/routes/router** (these words have a real different meaning).
It's really confusing.

**Comment by yunuseon** [comment]
This should be closed, shouldn't it? It would break the seperation of concerns between the router and components.
There is a number of issues:

- Routes declared like this, would have to be relative, as component can be imported in multiple modules
- It has to be determined, which component has preference if there is a conflict with an existing route with the same path but differing associated component.
- Assume: A component with an associated route like this is imported in two lazy loaded modules. We necessarily would have to fetch both modules when the given route is navigated

**Comment by JoostK** [comment]
One of the constraints that Angular needs to consider is tree-shakability of code, to allow dropping components that aren't used. Having a `@Route` decorator is problematic from this perspective, as just that allows the component itself to be tree-shaken away. You'd need a strong reference to the component, which the router achieves today using its `Routes` configuration objects.

The `Routes` configuration is also in control of allowing lazy loading of components based on the route. This implies that route information needs to be available without having loaded the components.

Overall, closing as infeasible.
