### ISSUE TITLE
Router tutorial: tour of heroes refers to non-existent code.

### ISSUE THREAD

**Issue by roninbar** [angular/angular#40299]
# 📚 Docs or angular.io bug report

### Description

**Router tutorial: tour of heroes** refers to non-existent code.

## 🔬 Minimal Reproduction
Follow the tutorial up to (and including) **Milestone 3: Heroes feature**.

### What's the affected URL?**

[Router tutorial: tour of heroes](https://angular.io/guide/router-tutorial-toh)

### Reproduction Steps**

1. Complete the first two milestones.
2. Follow the instructions in [Add heroes functionality](https://angular.io/guide/router-tutorial-toh#add-heroes-functionality).
3. The [Route Parameters](https://angular.io/guide/router-tutorial-toh#route-parameters) section is where things start to get confusing. The text refers to this code
```html
<a [routerLink]="['/hero', hero.id]">
```
but it doesn't seem to appear anywhere in the original Tour of Heroes tutorial; neither in [Part 4 (Services)](https://stackblitz.com/angular/dkjekblappg?file=src%2Fapp%2Fheroes%2Fheroes.component.html) nor in [Part 5 (In-App Navigation)](https://stackblitz.com/angular/lkeoljvavbl?file=src%2Fapp%2Fheroes%2Fheroes.component.html).

4. In the following section, [`ActivatedRoute` in action](https://angular.io/guide/router-tutorial-toh#activated-route-in-action), we're told to paste the following code in `ngOnInit()`
```typescript
ngOnInit() {
  this.hero$ = this.route.paramMap.pipe(
    switchMap((params: ParamMap) =>
      this.service.getHero(params.get('id')))
  );
}
```
but this yields several compilation errors because neither the `hero$` property in `HeroDetailComponent` nor the `getHero` method in `HeroService` have been declared yet. (`getHero` is defined in Part 5 of the TOH Tutorial, but the page refers to Part 4.)

The same section also contains this paragraph:

> AsyncPipe handles the observable subscription and the component's hero property will be (re)set with the retrieved hero.

However, `hero-detail.component.html` doesn't contain any references to `hero$`, nor does it contain the `async` pipe. It _does_ refer several times to the `hero` property, so I tried to replace these references with `(hero$ | async)` but this turns out to be illegal in the context of a two-way binding using `[(ngModel)]`.

5. The following section, [Navigating back to the list component](https://angular.io/guide/router-tutorial-toh#navigating-back-to-the-list-component), talks about the `HeroDetailComponent` "Back" button, but no such button exists in `hero-detail.component.html`.

### Expected vs Actual Behavior**

It should be possible to follow along the instructions in this tutorial using the sample code.
It seems that whoever wrote this tutorial was using a different version of the TOH tutorial.

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by Flusinerd** [comment]
Hi I‘m interested in working on this, I will take a look at it tomorrow and will try to reproduce it. 

If it can be reproduced I‘ll propose some changes.

**Comment by roninbar** [comment]
Great! Thanks, @Flusinerd!

I have some more input regarding the remainder of the tutorial but I don't know if I'll have time to post it before next Wednesday.

**Comment by Flusinerd** [comment]
@roninbar 
Just to make sure what you mean with "first two milestones":
Do you mean Part 1: "The Hero Editor" and Part 2: "Display a List"?

https://github.com/Flusinerd/angular-tour-of-the-heroes
I created a repo where I go through the tutorial and tag each finished chapter.

**Comment by roninbar** [comment]
> @roninbar
> Edit: I see what you mean with milestones 🤦
> 
> https://github.com/Flusinerd/angular-tour-of-the-heroes
> I created a repo where I go through the tutorial and tag each finished chapter.

It looks like you're doing the original Tour of Heroes tutorial.
The one I was talking about was the [Routing TOH tutorial](https://angular.io/guide/router-tutorial-toh).

**Comment by Flusinerd** [comment]
Ahh okay, now I get it.
Will have a look later 👍

**Comment by kapunahelewong** [comment]
Thanks for bringing this up and for taking the time to explain it with the details, @roninbar. I tried it and at milestone three before I even got to the part where you were having issues, I found a few places that could use some clarification. I'd like to loop in  our docs team lead, @aikidave, because the solution to this issue might be involved (unless you and @Flusinerd have an alternative solution).

**Comment by cesperian** [comment]
@aikidave let me know if I can help with this or similar TOH doc issues

**Comment by aikidave** [comment]
This tutorial really needs a thorough edit rewrite. Not only are some steps likely to be inaccurate, but we can bring the content in line with our tutorial guidelines so the steps are easier to understand. Will work on this!

**Comment by JeanMeche** [comment]
Angular.io is now in maintenance mode. We recommend having a look at the new tutorials on https://angular.dev
