### ISSUE TITLE
Using formControlName in <form> tag is throwing error in Angular 11 but works with <div>

### ISSUE THREAD

**Issue by v-ashivhare** [angular/angular#40298]
**So, I am seeing a weird issue in Angular 11.0.5.
I have nested form group structure which was working in Angular 9.1.0

form formGroupName="Switch" *ngIf="rule?.controls?.Switch"  -- Works in Angular 9 but doesn't work in Angular 11.

But when i change the form tag to div tag, it starts working again.

div formGroupName="Switch" *ngIf="rule?.controls?.Switch"  /div -- Work in both Angular 9 & 11.**

**Comment by mlc-mlapis** [comment]
@v-ashivhare You should create a simple reproduction demo. You can use https://stackblitz.com for it. Without it, it's hard to guess what it could be.

**Comment by AndrewKushnir** [comment]
As @mlc-mlapis mentioned above, we can not perform any investigation without a repro. I'm closing this ticket for now, feel free to reopen (or create a new one following issue template) once repro is available. Thank you.
