### ISSUE TITLE
bundled http.js throws errors in Firefox

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#4029]
I'm using the `http.js` file from `bundles` and when I run some unit tests on Travis I get the following [error](https://travis-ci.org/rolandjitsu/ng2-play#L589):
```js
ERROR
  SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function
  at /home/travis/build/rolandjitsu/ng2-play/node_modules/angular2/bundles/http.js:2286
```
Could it be because the way it was compiled?

**Comment by jeffbcross** [comment]
@rolandjitsu is it the same as this file? https://code.angularjs.org/2.0.0-alpha.36/http.js

Can you provide a reproduction, and more of a stack trace?

**Comment by rolandjitsu** [comment]
@jeffbcross as you can see the travis [built](https://travis-ci.org/rolandjitsu/ng2-play#L587), the only this it spits out it's that strict mode error. I am not sure if it is the same file as the one on CDN, but it's the one that is available at the npm distribution under the `bundles` folder. And the line it complains about is:

```js
function onGlobalPostMessage(event) {
    // Only if we're a match to avoid any other global events
    if (typeof event.data === 'string' && event.data.substring(0, MSG_PREFIX.length) === MSG_PREFIX) {
        runTask(event.data.substring(MSG_PREFIX.length));
    }
}
```

**Comment by jeffbcross** [comment]
Hmm, that's a problem with Rx, probably from this commit where it was changed from assignment to declaration (I think assignment is okay in strict mode, i.e. `var onGlobalPostMessage = function(){}`). https://github.com/Reactive-Extensions/RxJS/commit/5555090ec1524178c417a8f0f7cf846cb85b4040

**Comment by rolandjitsu** [comment]
@jeffbcross is there any way to fix this, as it fails my tests?

**Comment by rolandjitsu** [comment]
@jeffbcross oh, I just saw that angular has moved to RxNext, thus I suppose this issue will not persist anymore.
