### ISSUE TITLE
In Safari, using a SafeResourceUrl in <object> with type="application/pdf", crashes the entire tab

### ISSUE THREAD

**Issue by P-de-Jong** [angular/angular#40309]
# 🐞 bug report

### Affected Package

Using versions 10 and 11 of Angular

### Description
When using a `SafeResourceUrl` as data source of an `<object> element, in Safari 14.0.1 on MacOS Big Sur, the browser tab completely crashes.

The weird thing is, this only happens in combination when the attribute `type="application/pdf"` is added. 

I don't know if this is a Safari issue, or an Angular issue :(

## 🔬 Minimal Reproduction

Below are 2 stackblitz links.
- One with the attribute set on the `<object>` element.
- Another without the attribute

**WITH attribute**
When clicking the button, this will crash your brower tab in Safari 14.0.1 on MacOS
https://stackblitz.com/edit/angular-ivy-w8wyhq?file=src/app/app.component.html

**WITHOUT attribute**
When clicking the button, this will **NOT** crash your brower tab in Safari 14.0.1 on MacOS
https://stackblitz.com/edit/angular-ivy-ucr2rf?file=src%2Fapp%2Fapp.component.html

## 🌍  Your Environment

**Angular Version:**
Angular 10 and 11 (haven't tested other versions)

**Anything else relevant?**
Only seems to happen in Safari 14.0.1 on MacOS Big Sur.

**Comment by jelbourn** [comment]
Confirmed w/ @jessicajaniuk and @atscott that this is happening. I forked the StackBlitz to see if just updating the `data` property or swapping out the `object` without Angular had the same issues: https://stackblitz.com/edit/angular-ivy-z6bais?file=src%2Fapp%2Fapp.component.ts

Those are buggy, but they don't crash the browser tab the same way. @jessicajaniuk did find that pressing the buggton several times in quick succession could crash the tab, so maybe there's a hint there.

**Comment by shamoon** [comment]
Ah! Had this problem in a project I work on https://github.com/jonaswinkler/paperless-ng/issues/65 , tracking for a fix. We had to switch to using an entirely different library for PDF rendering.

Is there any issue with removing `type="application/pdf"`?

**Comment by gabynevada** [comment]
Got the same issue, in the meantime had to *ngIf the object without the type="application/pdf" just for the Safari platform.

**Comment by jessicajaniuk** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
