### ISSUE TITLE
Error during instantiation of Token(Promise<ComponentRef>)!.

### ISSUE THREAD

**Issue by svrcekmichal** [angular/angular#4030]
Hi, I'm getting error while trying to resolve all parameters for class in version .36

Here's documentation about `FormBuilder`:
```
   * @Component({
   *   selector: 'login-comp',
   *   viewBindings: [
   *     FormBuilder
   *   ]
   * })
   * @View({...})
   * class LoginComp {
   *   loginForm: ControlGroup;
   * 
   *   constructor(builder: FormBuilder) {
...
```

I'm using angular2-seed setup from @mgechev, trying to create small form with following code:
 ```
import {
    Component,
    View,
    bootstrap,
    FORM_DIRECTIVES,
    FORM_BINDINGS,
    FormBuilder,
    ControlGroup,
    StringMap

} from 'angular2/angular2';

@Component({
    selector: 'app',
    viewBindings:[FormBuilder]
})
@View({
    directives:[FORM_DIRECTIVES],
    styleUrls: [
        './bootstrap.css'
    ],
    template: `
    <div class="col-sm-6">
        <h2>Demo Form: SKU</h2>
        <form [ng-form-model]="skuForm" (submit)="onSubmit()">
            <div class="form-group">
                <input ng-control="sku" placeholder="sku" class=form-control>
            </div>
            <input type="submit" class="btn btn-default">
        </form>
    </div>``
})
class App {
    private skuForm:ControlGroup;

    constructor(fb:FormBuilder) {
        this.skuForm = fb.group(new StringMap({
            sku: ['ABC123']
        }));
    }

    onSubmit(form){
        console.log(form);
        return false;
    }
}

bootstrap(App);
```

Already tried to set `viewBindings` to value `[FORM_BINDINGS]`,`[FormBuilder]`, never with success, always getting error:

```
angular2.dev.js?v=0.0.0:22750 EXCEPTION: Error during instantiation of Token(Promise<ComponentRef>)!.
angular2.dev.js?v=0.0.0:22746 ORIGINAL EXCEPTION: Cannot resolve all parameters for App(?). Make sure they all have valid type or annotations.
angular2.dev.js?v=0.0.0:22746 ORIGINAL STACKTRACE:
angular2.dev.js?v=0.0.0:22746 Error
    at NoAnnotationError.BaseException (http://localhost:5555/lib/angular2.dev.js?v=0.0.0:7767:25)
    at new NoAnnotationError (http://localhost:5555/lib/angular2.dev.js?v=0.0.0:9180:63)
    at _extractToken (http://localhost:5555/lib/angular2.dev.js?v=0.0.0:26224:13)
    at http://localhost:5555/lib/angular2.dev.js?v=0.0.0:26187:14
    at Array.map (native)
    at Function.execute.ListWrapper.map (http://localhost:5555/lib/angular2.dev.js?v=0.0.0:8528:26)
    at _dependenciesFor (http://localhost:5555/lib/angular2.dev.js?v=0.0.0:26186:24)
    at execute.Binding.resolve (http://localhost:5555/lib/angular2.dev.js?v=0.0.0:26316:28)
    at Function.execute.metadata.createFromBinding (http://localhost:5555/lib/angular2.dev.js?v=0.0.0:28609:30)
    at Function.execute.metadata.createFromType (http://localhost:5555/lib/angular2.dev.js?v=0.0.0:28643:37)
```

**Comment by svrcekmichal** [comment]
After a while looking for solution a found that i can use inject in constructor

`constructor(@Inject(FormBuilder) fb:FormBuilder) {` 

the guestion is , why `viewBindings` isn't able to resolve `FormBuilder`? Or can someone explain to me, what am i making wrong? Thanks

**Comment by PascalPrecht** [comment]
Hey @svrcekmichal can you leave some information on what your dev stack looks like? I'm experiencing the same issue with @pkozlowski-opensource 's ng2-play repositories.

**Comment by svrcekmichal** [comment]
@PascalPrecht as i have mentioned above I'm using @mgechev 's anguar2-seed

**Comment by ericmartinezr** [comment]
I've seen this behaviour before and, in my case, is because I was using some feature without importing it.

Although is a little specific to my case, the error message is the same. See this plnkr : http://plnkr.co/edit/M9SzHP?p=preview

If you comment, for example : `Route`, or `RouteConfig` you'll get a message indicating that `Route` or `RouteConfig` is not defined which gives you an  idea of what's going on. But if you comment `Router` (not the same as `Route`) it will fail with that message.

That message is thrown for every class being used and missing in the imports, the only difference between `Router` and the others is that is being injected in the constructor, just like your issue with `FormBuilder`, although I didn't have to use `@Inject`, I just had to add the missing import.

**Comment by mhevery** [comment]
absolete
