### ISSUE TITLE
ng test always fails by sorting zone-testing import order

### ISSUE THREAD

**Issue by noxi515** [angular/angular#40305]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core/testing

### Is this a regression?

YES.
Angular 10.2.1 is OK, but 11.0.5 is not.

### Description

Sorting `zone.js/dist/zone-testing` imports on `src/test.ts` causes all tests failure.

## 🔬 Minimal Reproduction

1. Run `ng new` to create new Angular app.
2. Sort imports section on `src/test.ts` ( `zone.js/dist/zone-testing` import line to the last line).
3. Run `ng test` .

## 🔥 Exception or Error
<pre><code>
Error: zone-testing.js is needed for the async() test helper but could not be found.
        Please make sure that your environment includes zone.js/dist/zone-testing.js
Error: zone-testing.js is needed for the async() test helper but could not be found.
        Please make sure that your environment includes zone.js/dist/zone-testing.js
    at resetFakeAsyncZone (node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:274:1)
    at UserContext.&lt;anonymous&gt; (node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:2426:1)
    at &lt;Jasmine&gt;
    at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone-evergreen.js:399:1)
    at Zone.runTask (node_modules/zone.js/dist/zone-evergreen.js:167:1)
    at drainMicroTaskQueue (node_modules/zone.js/dist/zone-evergreen.js:569:1)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.5
Node: 14.15.4
OS: win32 x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by petebacondarwin** [comment]
The import of `zone.js/dist/zone-testing` is a side-effect import, which needs to be run before importing the rest of the testing infrastructure.

We should check why this side-effect import now affects the other imports when it appears that it did not in v10.2.1.
@JiaLiPassion ?

The obvious workaround is not to touch the `test.ts` file, which is not really user-code anyway.

**Comment by petebacondarwin** [comment]
OK, so I tried this (moving the zone.js import below the `getTextBed` import) and I saw:

```
Error: zone-testing.js is needed for the async() test helper but could not be found.
        Please make sure that your environment includes zone.js/dist/zone-testing.js
```

This seems like a reasonable requirement. Perhaps we should change this error message to be more explicit that the import not only must exist but also must appear before the import of `@angular/core/testing`.

**Comment by petebacondarwin** [comment]
Looking a bit further I see that the error is thrown because the `fakeAsyncTestModule` was not defined.
At the top of the file I can see: 

https://github.com/angular/angular/blob/1cba56e11fc647a424aecfe4ab3213dbf9ad00d2/packages/core/testing/src/fake_async.ts#L8-L9

Perhaps we could change this module level assignment to be lazy, so that the assignment of `Zone` and `fakeAsyncTest` are only done on their first request?

**Comment by petebacondarwin** [comment]
This change was introduced by https://github.com/angular/angular/commit/1cba56e11fc647a424aecfe4ab3213dbf9ad00d2

**Comment by IT-CASADO** [comment]
Imports should be side-effect free so that the order doesn't matter. 

I notice this error too, because of auto-fix "Organize imports" in VS Code.
This can also happen if you use TsLint/EsLint auto fixes....

**Comment by petebacondarwin** [comment]
> Imports should be side-effect free so that the order doesn't matter.

This is not strictly true. Imports can have side-effects. In particular ones that modify the global object (as zone.js does) must be side-effectful.

Generally if a module has side-effects then the convention is that it should not export anything. So that you have imports that look like

```
import 'zone.js/dist/zone-testing';
```

**Comment by petebacondarwin** [comment]
To be honest the import organizing tooling ought not to reorder potentially side-effectful imports. Tooling that reorders these will always be prone to problems.

I see that https://marketplace.visualstudio.com/items?itemName=alfnielsen.vsc-organize-imports has an option to ensure that "direct" imports will go first. Similarly eslint has the option to put "none" imports first.

Given that the two tools cited here can be configured to avoid this problem - and that they should be configured like this anyway irrelevant of Angular - I don't think this is something we should be changing in the framework.

**Comment by IT-CASADO** [comment]
"Organize Imports" is a out-of-the-box feature of TypeScript.
Then this is a "buggy" implementation of Microsoft feature in TypeScript, because they [recommendations](https://www.typescriptlang.org/docs/handbook/modules.html#import-a-module-for-side-effects-only) is to put side-effect code in imports without exports.

But I agree with you, this is always possible.
But imports with exports is for me a no-go (bad practice)!

With ESLint this would be also a good option:

[https://github.com/lydell/eslint-plugin-simple-import-sort/#grouping](https://github.com/lydell/eslint-plugin-simple-import-sort/#grouping)

**Comment by JiaLiPassion** [comment]
Yeah, this is a known issue, I created a PR to make it better here https://github.com/angular/angular/pull/39941

**Comment by ruimarques** [comment]
You might be able to work around this issue by adding to your `test.ts`:

`// tslint:disable:ordered-imports`

**Comment by Startouf** [comment]
I have a mix of IDE extensions and ESlint/TSlint rules. it is somewhat a pain to figure out what is reordering my imports (I've tried disabling sorting in a couple places and it still does auto-sorting on save) 

Auto-ordering imports was a desired feature for a more readable git diff and letting the machine do the boring stuff.

I understand the need to have side-effects before everything else, but in this case, especially for testing purposes, shouldn't there be a solution like a list of ordered global imports that we could declare in `karma.conf` or somewhere similar ?

**Comment by JeanMeche** [comment]
I'm going to close this as an issue not due to angular  and it can also be mitigated easily: 

* Using the `polyfill` entry in `angular.json` : `polyfills: ['zone.js', 'zone.js/testing'],`
* disable the tslint rule `tslint:disable:ordered-imports`
* Using ESLint that sort is correctly.
