### ISSUE TITLE
core.js:1673 ERROR Error: Value must be an array in multiple-selection mode

### ISSUE THREAD

**Issue by malaniderrick** [angular/angular#40319]
![image](https://user-images.githubusercontent.com/45063835/103744526-f508bc80-5023-11eb-8522-11f2972edf2a.png)

Why this given error i have also set on HTML file->   multiple="true"
Component.ts 

 'categoryId': [[], [Validators.required]],
 'subCategoryId': [[], [Validators.required]],

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by malaniderrick** [comment]
@JoostK  hope you doing well i have found solutions my self thanks @JoostK
