### ISSUE TITLE
datePipe unexpected return value on 2021-01-01 and 2021-01-02

### ISSUE THREAD

**Issue by peter-nieuwenhuyse** [angular/angular#40320]
# 🐞 bug report

### Affected Package
The issue is caused by package '@angular/common'.

### Description

When i try to use  DatePipe.transform('2021-01-01', 'dd/MM/YYYY') the outcome is 01/01/2020 same for 2021-01-02, dates higher than these 2 seem to format fine

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 11.0.2
Node: 13.8.0
OS: win32 x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: No

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
I cannot reproduce this problem. Here is a StackBlitz showing it working as expected: https://stackblitz.com/edit/ivy-lvhy5x?file=src/app/app.component.ts

**Comment by peter-nieuwenhuyse** [comment]
@petebacondarwin thx for the quick response, looks like use the lowercase yyyy solved the issue
