### ISSUE TITLE
fix(DynamicComponentLoader): make it work with ViewEncapsulation.Native

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#4032]
Having a simple scenario like this:

```
@Component({
  selector: 'child-component'
})
@View({
  template: 'I\'m loaded!'
})
class ChildComponent { }

@Component({...})
@View({
  template: '<div id="child"></div>',
  encapsulation: View.NATIVE
})
class DynCmp {
  constructor(dcl: DynamicComponentLoader, inj: Injector) {
    dcl.loadAsRoot(ChildComponent, '#child', inj);
  }
}
```

Results in the following runtime error:

```
EXCEPTION: The selector "#child" did not match any elements
angular2.min.js:16 STACKTRACE:
angular2.min.js:16 Error: The selector "#child" did not match any elements
    at new t (angular2.min.js:4)
    at r.execute.$traceurRuntime.createClass.createRootHostView (angular2.min.js:19)
    at execute.$traceurRuntime.createClass.createRootHostView (angular2.min.js:19)
    at angular2.min.js:12
    at r.run (angular2.min.js:1)
    at r.execute.$traceurRuntime.createClass._createInnerZone.e.fork.fork.$run [as run] (angular2.min.js:12)
    at r.bind (angular2.min.js:1)
    at O (angular2.min.js:1)
    at T (angular2.min.js:1)
    at P (angular2.min.js:1)
```

This is obviously due to DCL not querying inside ShadowRoot when `ViewEncapsulation.NATIVE` is used. Note that this works with either `ViewEncapsulation.NONE` or `ViewEncapsulation.EMULATED`.

I consider this a bug. What's the intended behaviour here?

**Comment by rolandjitsu** [comment]
@PascalPrecht I use `/deep/` selector to be able to query into shadow roots so it should be fairly easy to implement. I think this should be implemented if the view encapsulation is set to `ViewEncapsulation.NATIVE`, because how else would we use the DCL to add child components when we use native shadow DOM?

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

Due to latest way dynamic components are loaded.
