### ISSUE TITLE
queryParms observable always fires empty initially

### ISSUE THREAD

**Issue by dudewad** [angular/angular#40339]
# 🐞 bug report

### Affected Package
@angular/router

### Is this a regression?
No, this has always been an issue.

### Description
I know there have been issues opened for this in the past, e.g. #12157

The Angular team has seemingly decided that this is not a bug, however I, and apparently others, strongly disagree.

Let's just talk about the feature and what one _expects the feature to do_ first:

Per the documentation [here](https://angular.io/api/router/ActivatedRoute#queryParams), the queryParams object on an ActivatedRoute is:

`An observable of the query parameters shared by all the routes.`

This could be taken ambiguously, given that observables are asynchronous constructs. However, and this is the critical point, _as a developer, I expect query string parameters to be available when visiting a route with query string parameters on it, full stop._

When a component first loads, however, queryParams is _always an empty object_, regardless of whether or not there actually are query string params. The problem here is not a simple matter of then subscribing and `.skip(1)`-ing (which in and of itself is a hack, since we _already know we are going to be getting an empty object every single time,_). The important case is the very real, arguably more frequent case where there _are no query string params_, then the queryParams subscription never fires.

Yes, we could just subscribe, but then developers are left open to a race condition with early executing code. An added negative to this approach is that we now have created an open subscription for something that in my experience, 9 times out of 10, we only want once.

The expectation of the developer, if you simply look at the evidence in threads across the internet around this issue, is that `queryParams` gives you the query string parameters of the URL at the time the component is created. I believe this is very hard to argue against, given that this is simply how web development works. The reason I argue this is because if I go to `mysite.com?foo=bar`, I am, before the page has even loaded, specifying query string params - so why in any case ever would I expect the first retrieval of query string params to be empty - let alone _expect_ them to be empty on the first check _every single time_? This leads to literally writing extra "workaround code" everywhere, all the time, to get around a shortcoming - re: bug - in the framework that is of no use and provides no tangible benefit that I've been able to discern.

All arguments that I've read around "it's hard for Angular to know because..." are engineering problems on the Angular side that I strongly believe should be solvable.

Solutions provided (a.k.a. workarounds) include all the way up to manual parsing of the URL itself which defeats a lot of the purpose of having a queryParams observable to begin with.

I'm not going to opine about the technical limitations that I know nothing about within the Angular engine, I am just opening this issue because I find it hard to belive that we cannot make something as integral to web infrastructure as query string parameters available when components are instantiated. The amount of back-bending and weird code required to do something as simple as get qs params on component start up in a non-hacky, non-racey way is kind of surprising. I hate to say this, but I am resorting to manual parsing, or a simple timeout with 10ms on it, which is, yet again, another race condition.

I hope the Angular team is willing to reconsider this, because none of the arguments I've seen against fixing this bug have convinced me that 1) it isn't fixable and 2) there is an actual, valid reason for not doing so.

Thanks!

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-r7e2ib?file=src%2Fapp%2Fapp.component.ts

For repro with qs params in url, go here (this is that stackblitz app):

https://angular-ivy-r7e2ib.stackblitz.io/?foo=bar

## 🌍  Your Environment

This is all versions of angular to my knowledge.

**Comment by atscott** [comment]
#12157 has been re-opened. Closing this one as a duplicate.
