### ISSUE TITLE
slow performance on gtmetrix speed due to polyfills

### ISSUE THREAD

**Issue by sudhakarverma610** [angular/angular#40332]
I Use angular8 as ssr, and we found out that our application has heavy and serious problems with gtmetrix speed and all the issues are funnelling to polyfills.ts.
in pollyfills.ts i have only one line 
import 'zone.js/dist/zone'; 
i have  problem due to polyfills.ts i have implemented lazy loading and defer for js files  but i am unable to resolve total CPU time>2.5 second and Script Evaluation >2 second which lead bad performance please Tell me How can i Resolve this ASAP

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
