### ISSUE TITLE
ngcc clean

### ISSUE THREAD

**Issue by wazio** [angular/angular#40337]
# 🚀 Feature request

### Description
I've been searching for it many times but I cant find any command that would clean all ngcc build files. Is it possible that this command exists but I cant find it? ngcc is failing very often and it's extremely strange that command to clean all ngcc data is so hard to find.

### Describe the solution you'd like
Command ngcc clean? 

### Describe alternatives you've considered
Remove node_modules directory :)

**Comment by petebacondarwin** [comment]
The official answer is (as you suggest) `rm -rf node_modules`.
If ngcc comes across a package that was compiled using a different version of ngcc then it will actually clean that package itself before reprocessing.

But I am concerned by "ngcc is failing very often". Could you elaborate on this? It should be happening.

**Comment by anandsoni143** [comment]
I am new to opensource , can u please guide me , how to do so ? in any simple issues

**Comment by petebacondarwin** [comment]
Closing as this has shown no community support and we now have the partial-ivy mode and linker as a long term replacement for ngcc.
