### ISSUE TITLE
Docs : Confusing messaging around usage & deprecation of entryComponents

### ISSUE THREAD

**Issue by jdpearce** [angular/angular#40341]
### Description

It's currently stated that `entryComponents` is deprecated. 

https://angular.io/guide/deprecations#entryComponents

This implies that we shouldn't be using it at all. However, in the documentation for Angular Elements the example illustrates adding a component to `entryComponents` to "exclude it from compilation and avoid startup warnings or errors".

https://angular.io/guide/elements#example-a-popup-service

As far as I'm aware, it's still required to add Angular Elements to `entryComponents` in order to register them, but its deprecation suggests there ought to be another way to do it?

Is that something that needs documenting or is the deprecation warning something that should be ignored?

Either way the messaging here seems confusing.

**Comment by AndrewKushnir** [comment]
Hi @jdpearce, thanks for reporting this issue. There is no need to use `entryComponents` with Ivy, so I've created a PR #42324 to remove `entryComponents` references from the mentioned doc.
