### ISSUE TITLE
Documentation for relativeLinkResolution is confusing

### ISSUE THREAD

**Issue by Airblader** [angular/angular#40359]
### Description

The [documentation for relativeLinkResolution](https://angular.io/api/router/ExtraOptions#relativeLinkResolution) helpfully provides an example and talks about fixing a bug. However, it doesn't really state which of the two behaviors is considered "correct"(ed) or bugged, and thus it isn't entirely clear which option a user would have to choose.

### What's the affected URL?**
https://angular.io/api/router/ExtraOptions#relativeLinkResolution

### Expected vs Actual Behavior**

It would be nice if the documentation was a bit more clear on which value for the flag produces which behavior.

**Comment by atscott** [comment]
Fixed by #40384
