### ISSUE TITLE
Comma placement issue for Currency Pipe (observed for Indian Rupee - INR)

### ISSUE THREAD

**Issue by vwithv1602** [angular/angular#40350]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Not Sure

### Description

 While using CurrencyPipe, the placement of comma (,) is not correct for Indian Rupee. ₹ 1,00,000 is represented as ₹ 100,000. 

## 🔬 Minimal Reproduction

 https://angular-fe7xrx.stackblitz.io

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.1.7
Node: 14.5.0
OS: linux x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.1.7
@angular/cdk                      9.2.4
@angular/cli                      9.1.7
@angular/language-service         9.0.4
@angular/material                 9.2.4
@ngtools/webpack                  9.0.7
@schematics/angular               9.1.7
@schematics/update                0.901.7
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
In your example you have set the currency being displayed but you are still using the `en-US` locale to process the currency value. You need to also change the locale to `en-IN`. See https://stackblitz.com/edit/angular-cdh8to?file=src%2Fapp%2Fapp.component.ts
