### ISSUE TITLE
discuss: remove angular2/bootstrap and angular2/render.

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#4036]
In the process of shifting around modules in #3713, it was still necessary to have modules for bootstrap and render that would not be included in the angular dart core module. This is so users can choose if they want the reflective bootstrap exported from `angular2/bootstrap`, or the static bootstrap exported from `angular2/bootstrap_static`. So when dart users are creating their root component, they'd import both `angular2/core` and `angular2/bootstrap`. But libraries would just import `angular2/core`, without worrying that it imports `dart:html` somewhere, which would make it not run in a server environment.

This is unfortunate because now `angular2/core` has different contents in JavaScript and Dart. I don't have ideas on how we can satisfy the needs of "pick-your-own-bootstrap" for dart, while keeping the core module as representing "everything you need to make an angular app" for both platforms. I think it would be better to not deviate between platforms in this case if we're not able to have the core module have the same contents in both environments. I.e. removing bootstrap from JS `angular2/core` would be preferable to me than to leave `angular2/core` as it is now.

@yjbanov do you have some ideas for options?

**Comment by mhevery** [comment]
Superseded by: #4834
