### ISSUE TITLE
undefined or null HostBindings for `style.xy` are rendered by universal

### ISSUE THREAD

**Issue by sod** [angular/angular#40361]
angular 11.0.4 / ivy enabled

Add `@HostBinding('style.padding') public padding?: string;` to a component, and ssr will output:
`<my-component style="padding:"></my-component>`

And the client will output:
`<my-component></my-component>`

**Comment by jelbourn** [comment]
Could you share a more full reproduction?

**Comment by sod** [comment]
Given that my prior tickets were I provided a reproduction get no feedback. No.
