### ISSUE TITLE
Can we embed LWC component in angular App?

### ISSUE THREAD

**Issue by ajay312** [angular/angular#40365]
Steps to follow to add LWc component into angular application--

Thank You!

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
