### ISSUE TITLE
chore: move src/compiler/* to src/core/compiler/

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#4037]
In the middle of some shifting around of folders, it looks like some files were added to `modules/angular2/src/compiler` which should now be in `modules/angular2/src/`**`core`**`/compiler`.

@tbosch I'm happy to make the move if this is correct.

**Comment by tbosch** [comment]
I just did this: move current `core/compiler` into `core/linker` and `compiler` into `core/compiler`.
