### ISSUE TITLE
angular v11 - bug in 2 functions in angular/packages/common/src/i18n/format_date.ts

### ISSUE THREAD

**Issue by slany** [angular/angular#40377]
# 🐞 bug report - bad working with new Date() in format_date.ts

### Affected Package
@angular/common - source file https://github.com/angular/angular/blob/master/packages/common/src/i18n/format_date.ts

### Description
There are 2 functions with follow implementation:
https://github.com/angular/angular/blob/master/packages/common/src/i18n/format_date.ts#L364
https://github.com/angular/angular/blob/master/packages/common/src/i18n/format_date.ts#L370

```typescript
const JANUARY = 0;
const THURSDAY = 4;
function getFirstThursdayOfYear(year: number) {
  const firstDayOfYear = (new Date(year, JANUARY, 1)).getDay();
  return new Date(
      year, 0, 1 + ((firstDayOfYear <= THURSDAY) ? THURSDAY : THURSDAY + 7) - firstDayOfYear);
}

function getThursdayThisWeek(datetime: Date) {
  return new Date(
      datetime.getFullYear(), datetime.getMonth(),
      datetime.getDate() + (THURSDAY - datetime.getDay()));
}
```
###Problem is 
javascript new Date has different behaviour than original code expects:
```typescript
new Date(2000,0,31) // return date with year = 2000
new Date(100,0,31) // return date with year = 100
new Date(99,0,31) // return date with year = 1999, because if inYear is in interval <0,100), result FullYear  = 1900+inYear
new Date(0,0,31) // return date with year = 1900, because if inYear is in interval <0,100), result FullYear  = 1900+inYear
new Date(-1,0,31) // return date with year = -1
```

Fix of this problem is very simple:
```typescript
const JANUARY = 0;
const THURSDAY = 4;
function getFirstThursdayOfYear(year: number) {
  const firstDayOfYear = (new Date(year, JANUARY, 1)).getDay();
  const ret = new Date(
      year, 0, 1 + ((firstDayOfYear <= THURSDAY) ? THURSDAY : THURSDAY + 7) - firstDayOfYear);
  ret.setFullYear(year); // added line
  return ret;
}

function getThursdayThisWeek(datetime: Date) {
  const ret = new Date(
      datetime.getFullYear(), datetime.getMonth(),
      datetime.getDate() + (THURSDAY - datetime.getDay()));
  ret.setFullYear(datetime.getFullYear()); // added line
  return ret;
}
```

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-rlvhyx?file=src%2Fapp%2Fapp.component.ts

## 🌍  Your Environment

**Angular Version: 11**
<pre><code>
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.5
Node: 12.6.0
OS: linux x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@schematics/angular             11.0.5
@schematics/update              0.1100.5
ng-packagr                      11.0.3
rxjs                            6.6.3
typescript                      4.0.5
    
Done in 0.36s.

</code></pre>

**Comment by Sergey19842** [comment]
ok

**Comment by jelbourn** [comment]
Summarizing here: this is a bug with date **parsing* (not formatting). The `Date` constructor treats the `year` parameter specially, such that if it's a value between `0` and `99`, it "helpfully" makes it `1900` - `1999`. The behavior here should use `setFullYear` to make the behavior consistent.

Updated stackblitz that shows the issue from Pete: 
https://stackblitz.com/edit/angular-ivy-5hb4hr?file=src%2Fapp%2Fapp.component.html

**Comment by abarghoud** [comment]
Hello @jelbourn, I would like to submit a PR concerning this one.

**Comment by petebacondarwin** [comment]
@abarghoud - great! Let me know if you need help with this.
