### ISSUE TITLE
Angular SSR error "This.debug is not a function".

### ISSUE THREAD

**Issue by jy967845** [angular/angular#40386]
I was using angular 11. I added universal into my project using command ng add @nguniversal/express-engine.
It added successfully. But while running the command "npm run dev:ssr",  I am getting error on CMD "this.debug is not a function".

![Screenshot_105](https://user-images.githubusercontent.com/41678444/104151398-f0b51880-5402-11eb-97b9-349699c9aa7f.png)

This is my package.json
{
  "name": "evisa",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "dev:ssr": "ng run evisa:serve-ssr",
    "serve:ssr": "node dist/evisa/server/main.js",
    "build:ssr": "ng build --prod && ng run evisa:server:production",
    "prerender": "ng run evisa:prerender"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.0.0-beta.5",
    "@angular/animations": "^11.0.7",
    "@angular/common": "^11.0.7",
    "@angular/compiler": "^11.0.7",
    "@angular/core": "^11.0.7",
    "@angular/forms": "^11.0.7",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^11.0.7",
    "@angular/platform-browser-dynamic": "^11.0.7",
    "@angular/platform-server": "^11.0.7",
    "@angular/router": "^11.0.7",
    "@nguniversal/express-engine": "^11.0.1",
    "@ngx-meta/core": "^6.0.0",
    "angular-font-awesome": "^3.1.2",
    "angular-mat-datepicker": "0.0.2",
    "angular2-autosize": "^1.0.2",
    "angular2-datepicker": "^1.0.5",
    "angular2-tooltip": "^3.1.0",
    "angular2-tooltips": "^1.0.10",
    "autosize": "^4.0.2",
    "bootstrap": "^3.4.1",
    "core-js": "^2.5.4",
    "express": "^4.15.2",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jquery": "^3.5.1",
    "jw-angular-social-buttons": "^1.0.0",
    "ng-autosize": "^1.1.0",
    "ng-recaptcha": "^3.0.5",
    "ng2-social-share": "0.0.10",
    "ngx-progressbar": "^2.1.1",
    "ngx-textarea-autosize": "^2.0.0",
    "payumoney_nodejs": "^2.0.2",
    "rxjs": "^6.6.3",
    "rxjs-compat": "^6.6.3",
    "wowjs": "^1.1.3",
    "zone.js": "^0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1100.6",
    "@angular/cli": "^11.0.6",
    "@angular/compiler-cli": "^11.0.7",
    "@angular/language-service": "^11.0.7",
    "@fortawesome/fontawesome-free": "^5.6.3",
    "@nguniversal/builders": "^11.0.1",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~7.0.0",
    "ts-node": "~5.0.1",
    "tslint": "~6.1.3",
    "typescript": "~4.0.5"
  }
}

**Comment by jy967845** [comment]
"jw-angular-social-buttons" module is not processed with angular 11.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
