### ISSUE TITLE
Memory leak in tests with zone.js >= 0.9.0

### ISSUE THREAD

**Issue by belchevgb** [angular/angular#40387]
# 🐞 bug report

### Affected Package

 The issue is caused by package:
**zone.js: 0.9.0**

### Is this a regression?

Yes. The tests didn't cause Chrome to crash.

### Description
When I've upgraded zone.js from 0.8.26 to 0.9.0 or higher, this problem appeared. I have 3000 unit/integration tests. We use heavily dynamic component creation. Our tests currently cannot be executed at once, because zone.js(the timers patch) keeps a reference to tasks created from **setTimeout()** in **tasksByHandleId** in the patch method.  When I call **clearTimeout()** in ngOnDestroy() I can see that the task is not removed from tasksByHandleId because it's status is **notScheduled**.

## 🔬 Minimal Reproduction
https://github.com/belchevgb/zonejs-memory-leak

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.6
Node: 14.3.0
OS: win32 x64

Angular: 11.0.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.6
@angular-devkit/build-angular   0.1100.6
@angular-devkit/core            11.0.6
@angular-devkit/schematics      11.0.6
@angular/cli                    11.0.6
@schematics/angular             11.0.6
@schematics/update              0.1100.6
rxjs                            6.6.3
typescript                      4.0.5
zone.js                         0.10.2
</code></pre>

**Anything else relevant?**
[SNAPSHOT](https://drive.google.com/file/d/1T7tUuZZPBdiOS1amHcBLWNXWhRNzArKo/view?usp=sharing)
![image](https://user-images.githubusercontent.com/15705336/104160957-a92a8e80-53fa-11eb-870b-656e9e946189.png)

**Comment by belchevgb** [comment]
Any info if this will be resolved in some minor version or in v12?

**Comment by JiaLiPassion** [comment]
@belchevgb , I will check this one, thanks!

**Comment by JiaLiPassion** [comment]
@belchevgb , I am not quite understand your reproduce logic, 

```
ngAfterViewInit(): void {
    this.timeoutId = setTimeout(() => {
      // do some work
    });
  }

  ngOnDestroy(): void {
    clearTimeout(this.timeoutId);
  }
```

the `setTimeout` in `ngAfterViewInit` has been invoked after `0ms`, and in `ngDestroy`, `clearTimeout` will do nothing since the timeout is already done.

So could you create reproduce repo to show the issue?

**Comment by belchevgb** [comment]
The problem is that when you call setTimeout in afterViewInit this async task gets scheduled and the task is stored in tasksByHandleId. When we call ngOnDestroy and clearSetTimeout, this tries to remove the given task from tasksByHandleId cache, but it is with status "not scheduled", so this task never gets removed.

**Comment by belchevgb** [comment]
Here is the repro repo https://github.com/belchevgb/zonejs-memory-leak

**Comment by JiaLiPassion** [comment]
@belchevgb , I can reproduce now, thanks for reporting this issue, I will create a PR to fix it asap.

**Comment by JiaLiPassion** [comment]
@belchevgb , BTW, even after this memory leak issue is fixed, the test case you wrote may still have issues.


1. After the issue is fixed, in your code, You create a `setTimeout` inside a `it()` with a `fakeAsync()`, and `clearTimeout()` inside a `afterEach()`.

```
afterEach(() => {
    fixture.destroy();
    fixture = null;
  });

  it("test 1", fakeAsync(() => {
    fixture.detectChanges();
    tick();
  }));
```

So even without memory leak, the `fixture.destroy() -> ngOnDestroy() -> clearTimeout()` will not really clear the timer since 
they are not in the same `it()` or `afterEach()` testBody, it will not become a issue in this case (there will be no memory leak in this case) but it may become an issue for more complex case, so you need to call `fixture.destroy()` in the `it()` test body.

```
 it("test 1", fakeAsync(() => {
    fixture.detectChanges();
    tick();
    fixture.destroy();
  }));
```

I understand it is bolierplate code, so you may write some high order function like

```
function fakeAsyncWithAutoDestroy(testName, testFunc) {
  return it(testName, fakeAsync(() => {
    testFunc();
    fixture.destroy();
  });
}
itWithAutoDestroy('test', () => {
   ...
});
```

2. In your sample code, if your `leaky.component.ts` `ngAfterViewInit` code, if you give a delay of the `setTimeout`, 
```
    this.timeoutId = setTimeout(() => {
      // do some work
    }, 200);
```  
Then in your test code

```
 it("test 1", fakeAsync(() => {
    fixture.detectChanges();
    tick();
  }));
```

It will report `pending timer still remains in fakeAsync()`, since the timeout is not consumed or cleared.

**Comment by belchevgb** [comment]
Hey @JiaLiPassion, thanks for the fast response. I understand the issues from above, but is it possible to provide some testing API, that crawls the tree of zones and clear all stored data in globalAfterEach for example or to unregister give zone.js patch in my case the timers patch, which should cause garbage collection of all stored ZoneTasks?

**Comment by belchevgb** [comment]
We have 4k+ tests and it's much effort to modify every it()

**Comment by JiaLiPassion** [comment]
@belchevgb , I will fix the memory leak first, and the `globalAfterEach` feature request, I will try to find the solution in another PR.

**Comment by belchevgb** [comment]
Thank you very much @JiaLiPassion !
