### ISSUE TITLE
User `ngTemplateOutletContext` been modified unexpectedly

### ISSUE THREAD

**Issue by JounQin** [angular/angular#40385]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 No

### Description

 
User `ngTemplateOutletContext` is been modified at https://github.com/angular/angular/blob/master/packages/common/src/directives/ng_template_outlet.ts#L104 because the `_viewRef.context` is pointed at https://github.com/angular/angular/blob/master/packages/core/src/render3/instructions/shared.ts#L137.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ivy-tstyd6?file=src%2Fcomponents%2Fselect.component.ts

## 🔥 Exception or Error

Click `label: option2-5`, the top value will change correctly, be then click `label: option1` the top value will not change which is incorrect.

This is because the `ngTemplateOutletContext` is pointed to the first context and always been modified, but when clicking `label: option1`, the context has been changed to last context content https://github.com/angular/angular/blob/master/packages/common/src/directives/ng_template_outlet.ts#L68.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 11.0.3
Node: 12.20.0
OS: darwin x64

Angular: 11.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1002.0
@angular-devkit/core         10.2.0
@angular-devkit/schematics   11.0.3
@angular/cdk                 11.0.2
@angular/flex-layout         11.0.0-beta.33
@schematics/angular          11.0.3
@schematics/update           0.1100.3
rxjs                         6.6.3
typescript                   4.1.2
</code></pre>

**Anything else relevant?**

**Comment by crisbeto** [comment]
Should be fixed by https://github.com/angular/angular/pull/40360. Also see the PR for more context around why it currently works this way.

**Comment by JounQin** [comment]
@crisbeto Thanks for your reply. Close in favor of #24515.
