### ISSUE TITLE
ng: command not found when try "ng build -prod" in my project

### ISSUE THREAD

**Issue by balajimoba** [angular/angular#40399]
whenever i try run the code by ng, it's always say command not found, still i couldn't understand why it come and how.

can anyone explain ?

**Comment by petebacondarwin** [comment]
Hello @balajimoba, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
