### ISSUE TITLE
Router.navigate should have an overload that accepts the tuple

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#4040]
Currently `router.navigate()` only accepts a url as a string, like this

`    this._router.navigate(``${ROUTES.detail}/${this.currentHero.id}``);`

This works, but it would be great to be able to pass the tuple to it like this as another option:

    this._router.navigate([ROUTES.detail, {id: this.currentHero.id}]);

**Comment by johnpapa** [comment]
cc // @wardbell

**Comment by btford** [comment]
100% agree. I may even have already filed this issue.

**Comment by btford** [comment]
ah– better yet, I already had a fix in progress. PR incoming.

**Comment by johnpapa** [comment]
@btford thanks, thats great!
