### ISSUE TITLE
Cant build or test in parallel due to ngcc lock file

### ISSUE THREAD

**Issue by sir-captainmorgan21** [angular/angular#40405]
# 🐞 bug report

### Affected Package
The issue is caused by ivy.
We are the following angular versions...
"@angular/animations": "10.0.7",
"@angular/cdk": "10.1.1",
"@angular/common": "10.0.7",
"@angular/compiler": "10.0.7",
"@angular/core": "10.0.7",
"@angular/cli": "10.0.4",
"@angular/compiler-cli": "10.0.7"

### Is this a regression?

This use to work prior to Ivy

### Description

We use NX to manage a monorepo of sorts. When we attempt to build apps or test packages in parallel, we get the following error...

`Another process, with id 68108, is currently running ngcc.
Waiting up to 250s for it to finish.
(If you are sure no ngcc process is running then you should delete the lock-file at /Users/zach.morgan/Development/Web.Seeker/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)`

We already have the `postinstall` script set up. We have tried it with various commands (listed below).
- `ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points`
- `ngcc --create-ivy-entry-points`
- `ngcc`

We have dug through many issues related to this, and cannot find a solution. We think this answer https://github.com/angular/angular/issues/35000#issuecomment-580136837 by @petebacondarwin is our problem, but the PR he opened to solve this was closed. We aren't quite sure why ngcc is still being run for our builds when we have it run postinstall. We have a number of third party packages, so this may be the cause. I can list them below. Not sure if it will help or not.
"@adobe/target-node-client": "0.15.0",
  "@angular/animations": "10.0.7",
  "@angular/cdk": "10.1.1",
  "@angular/common": "10.0.7",
  "@angular/compiler": "10.0.7",
  "@angular/core": "10.0.7",
  "@angular/forms": "10.0.7",
  "@angular/material": "10.1.0",
  "@angular/material-moment-adapter": "9.2.0",
  "@angular/platform-browser": "10.0.7",
  "@angular/platform-browser-dynamic": "10.0.7",
  "@angular/platform-server": "10.0.7",
  "@angular/router": "10.0.7",
  "@angular/service-worker": "10.0.7",
  "@contentful/rich-text-html-renderer": "13.1.0",
  "@ngneat/until-destroy": "8.0.1",
  "@ngrx/effects": "10.0.0",
  "@ngrx/router-store": "10.0.0",
  "@ngrx/store": "10.0.0",
  "@ngrx/store-devtools": "10.0.0",
  "@nguniversal/aspnetcore-engine": "10.0.1",
  "@nguniversal/common": "10.0.1",
  "@nguniversal/express-engine": "10.0.1",
  "@ngx-translate/core": "13.0.0",
  "@ngx-translate/http-loader": "6.0.0",
  "@nrwl/schematics": "8.12.11",
  "@sentry/angular": "5.22.3",
  "@sentry/browser": "5.22.3",
  "@sentry/node": "5.22.3",
  "angular2-text-mask": "9.0.0",
  "backoff-rxjs": "6.3.2",
  "body-parser": "1.18.3",
  "bowser": "2.11.0",
  "classlist.js": "1.1.20150312",
  "compression": "1.7.2",
  "connect-datadog": "0.0.6",
  "cookie-parser": "1.4.3",
  "core-js": "2.5.4",
  "express": "4.16.3",
  "express-healthcheck": "0.1.0",
  "flatted": "2.0.1",
  "git-branch": "2.0.1",
  "helmet": "3.12.1",
  "hot-shots": "5.7.0",
  "http-status-codes": "1.4.0",
  "jspdf": "1.5.3",
  "memcached": "2.2.2",
  "moment": "2.24.0",
  "ng-recaptcha": "4.3.0-beta.1",
  "ngx-dfp": "1.6.2",
  "ngx-img-cropper": "9.0.1",
  "ngx-infinite-scroll": "9.0.0",
  "ngx-page-scroll": "6.0.0-beta.1",
  "ngx-page-scroll-core": "6.0.0-beta.1",
  "ngx-swiper-wrapper": "8.0.2",
  "ngx-utils-cookies-port": "1.0.1",
  "numeral": "2.0.6",
  "parse-address": "1.1.0",
  "rxjs": "6.5.4",
  "smoothscroll-polyfill": "0.4.3",
  "ts-loader": "4.3.1",
  "tslib": "2.0.0",
  "twilio-video": "2.7.0",
  "typedoc": "0.15.0",
  "uuid": "3.3.2",
  "web-vitals": "^0.2.4",
  "winston": "2.4.2",
  "zone.js": "0.10.3"

## 🔬 Minimal Reproduction
I cant provide a reproduction as Im not sure what I would be providing besides the packages we use above and that we are just trying to build a app in parallel. So I guess it would be...
- Install those packages above
- run npm install (make sure you have the postinstall setup)
- then build the apps in parallel

## 🔥 Exception or Error
<pre><code>
Another process, with id 68108, is currently running ngcc.
Waiting up to 250s for it to finish.
(If you are sure no ngcc process is running then you should delete the lock-file at /Users/zach.morgan/Development/Web.Seeker/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.4
Node: 12.0.0
OS: darwin x64

Angular: 10.0.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: <error>

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.4
@angular-devkit/build-angular      0.1000.4
@angular-devkit/build-ng-packagr   0.1000.4
@angular-devkit/build-optimizer    0.1000.4
@angular-devkit/build-webpack      0.1000.4
@angular-devkit/core               8.3.23
@angular-devkit/schematics         8.3.23
@angular/cdk                       10.1.1
@angular/cli                       10.0.4
@angular/material                  10.1.0
@angular/material-moment-adapter   9.2.0
@ngtools/webpack                   10.0.4
@nguniversal/aspnetcore-engine     10.0.1
@nguniversal/builders              9.1.0
@nguniversal/common                10.0.1
@nguniversal/express-engine        10.0.1
@schematics/angular                9.1.0
@schematics/update                 0.1000.4
ng-packagr                         10.0.3
rxjs                               6.5.4
typescript                         3.9.7
webpack                            4.43.0

</code></pre>

**Anything else relevant?**
I think I have covered it. Please let me know if you need any more information before closing this issue. Would really like to get this solved. Thanks!

**Comment by petebacondarwin** [comment]
@sir-captainmorgan21 - sorry you are getting problems with you parallel builds.

The message that you quote is actually for information only and is not an error. Your build should continue when the other parallel build releases the lock-file. Given that you have pre-processed the packages then the wait should be quite small (it polls every 500ms).

Can you clarify if the build actually files or whether this is just noise in your build?

**Comment by sir-captainmorgan21** [comment]
@petebacondarwin Sorry. You are right. I should have been more specific to our problem. Doing research got me hung up on "builds". Our problem is actually "testing" in parallel. We are testing in parallel using NX. We are getting another error that we thought was tied to the error posted in this original issue. That error is...

`Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory`

**Comment by petebacondarwin** [comment]
This issue on the Cyprus repo looks related: https://github.com/cypress-io/cypress/issues/4925. Are you using Docker?
In any case I don't believe that the error you are seeing is related specifically to Angular, so I am going to close this.
Please open a new one if you can create a reproduction that we can debug.
