### ISSUE TITLE
Mistake in "Templates" docs in "Text Interpolation" section

### ISSUE THREAD

**Issue by nilayk777** [angular/angular#40403]
# 📚 Docs or angular.io bug report

### Description

 In the sub-section titled "Expression context", following is mentioned:
"The previous example presents such a name collision. The component has a customer property and the *ngFor defines a customer template variable."
However, there is no customer property in the example's code of component, which is stored in "app.component.ts"

### What's the affected URL?**
 https://angular.io/guide/interpolation#expression-context

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by petebacondarwin** [comment]
Thanks for this issue report. Indeed, the component does not have a `customer` property. Instead it has a `currentCustomer` property - see https://github.com/angular/angular/blob/0b5b24abd70fd04c8cc322e10607b57bb0d04b4d/aio/content/examples/interpolation/src/app/app.component.ts#L13.

We should modify the example (perhaps by creating an "alternate" component file (e.g. `app.component.1.ts` to demonstrate this; then update the guide itself to point to this.
