### ISSUE TITLE
feat(core): allow for multiproviders to be a map/dictionary as well as an array

### ISSUE THREAD

**Issue by damienwebdev** [angular/angular#40413]
# 🚀 feature request

### Relevant Package
`@angular/core`

### Description
As a developer, I'd like to be able to my provider lookups in O(1) time instead of O(n) time. I often find myself having to to do something like:

```ts
@Inject(SomeToken) private myToken: SomeInterface[]
const type = "SomeDiscriminator";
const theTokenImLookingfor = myToken.filter((t) => t.type === type).shift();
```

In order to support this goal, I think that `multi` providers need to be expanded to support `Map` types.

### Describe the solution you'd like
```ts
export enum MultiProviderType {
 Array = 1,
 Map = 2
}
providers: [
  { provide: SomeToken, multi: MultiProvider.Map, key: "some-key", useValue: "SomeValue" },
]
```

### Describe alternatives you've considered
There isn't REALLY an alternative here that I can see.

**Comment by petebacondarwin** [comment]
One (sort of) workaround for this would be to create a service that does a one-time bundling of the multiproviders into an object or map:

```ts
export interface MyInterface {
  type: string;
  toString();
}

export class Service1 implements MyInterface {
  type = "service1";
  toString(): string {
    return "This is service 1";
  }
}

export class Service2 implements MyInterface {
  type = "service2";
  toString(): string {
    return "This is service 2";
  }
}
export const TOKENS = new InjectionToken<MyInterface[]>("TOKENS");
export const TOKEN_MAP = new InjectionToken<Map<string, MyInterface>>(
  "TOKEN_MAP"
);

export function createTokenMap(
  tokens: MyInterface[]
): Map<string, MyInterface> {
  return new Map<string, MyInterface>(tokens.map(t => [t.type, t]));
}
```

and then in a module:

```ts
    { provide: TOKENS, multi: true, useClass: Service1 },
    { provide: TOKENS, multi: true, useClass: Service2 },
    { provide: TOKEN_MAP, useFactory: createTokenMap, deps: [TOKENS] }
```

See https://stackblitz.com/edit/angular-ivy-yx4ume?file=src%2Fapp%2Fapp.module.ts

**Comment by damienwebdev** [comment]
@petebacondarwin this works, but I believe has the limitation that it isn't really kept in sync as lazy-loaded modules are added into the app.

I think it's worthy to keep this issue open as a feature, but not sure if it would ever get implemented.
