### ISSUE TITLE
`this` missing from template

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#4041]
In angular 1 it was great having access to `this` in the template syntax since you can intuitively write something like this
```html
<pre ng-repeat="prop in this">this.{{ prop }} = {{ this[prop] }}</pre> 
```
for quick debug info when teaching angular. This is not the case in Angular 2 as the keyword `this` does not work.

### proposal 
allow `this` keyword in template to reference the component instance

**Comment by PascalPrecht** [comment]
Prolly better suited for teaching: `<pre>{{this | json}}</pre>`

However, I don't think that this should be supported in A2. it's not really convenient to write template expressions like this and I also don't think we should give ppl the option to do so. There's no real additional value afaics..

**Comment by kentcdodds** [comment]
I use `this` in angular-formly templates. It's handy to have in a library context, though I would recommend people doing this very much in application code. I say :+1: to this.

**Comment by kentcdodds** [comment]
If you're reading this from email, you wont get my update:

"...though I would recommend..."   --->    "...though I wouldn't recommend..." pretty crucial three characters. :-)

**Comment by mhevery** [comment]
Will not implement.
