### ISSUE TITLE
Error in `HttpHeaders#applyUpdate()`: null is not an object (evaluating 'n.length')

### ISSUE THREAD

**Issue by hungyapp** [angular/angular#40424]
# 🐞 bug report

### Affected Package
dist/master/node_modules/@angular/common/fesm2015/http.js:234:26applyUpdate

### Is this a regression?
Not sure

### Description

I have an observable fetching data. using the HTTP module,  and am using BugSnag to track errors. 

I. have been getting the following error:

TypeError · null is not an object (evaluating 'n.length')
dist/master/node_modules/@angular/common/fesm2015/http.js:234:26applyUpdate

if (typeof value === 'string') {
  value = [value];
}
if (value.length === 0) {
return;
}
this.maybeSetNormalizedName(update.name, key);

## 🔬 Minimal Reproduction
This happens randomly, I can't. reproduce it.

## 🔥 Exception or Error
By reading the Angular code, the verification is that if the type of value is a string, it was converting. it into an. array.
I'm not sure the full code functionality, but my recommendation would be:

//Maybe this make more sense
if (value && !Array.isArray(value)) {
  value = [value];
}

// and definitely a check before accessing the length
if (!Array.isArray(value) ||  value.length === 0) {
return;
}

** Note: As I can't reproduce, I'm. not sure what kind of value is going through the value variable (and why it's null)

## 🌍  Your Environment

**Angular Version:**

    "@angular/animations": "10.1.1",
    "@angular/cdk": "^10.2.7",
    "@angular/common": "^10.2.3",
    "@angular/compiler": "^10.2.3",
    "@angular/core": "^10.2.3",
    "@angular/forms": "^10.2.3",
    "@angular/material": "^10.2.7",
    "@angular/material-moment-adapter": "^10.2.7",
    "@angular/platform-browser": "^10.2.3",
    "@angular/platform-browser-dynamic": "^10.2.3",
    "@angular/router": "^10.2.3",
    "@angular/service-worker": "^10.2.3",

**Comment by gkalpak** [comment]
I looked at the code and the only way this can happen is if someone (outside of the framework - i.e. either the app or a 3rd-party library) calls one of the methods with incorrect arguments. For example, call (directly or indirectly) [HttpRequest#clone()][1] with an incorrect `setHeaders` value or call `HttpHeaders`' [append()][2] or [set()][3] with an incorrect `value` argument, etc.

So, it sounds like the issue lies outside Angular (unless I've missed something). Could you search your code for places where you interract with `@angular/common/http` methods and ensure you are not passing incorrectly typed values? Do you use any 3rd-party libraries that would use `HttpClient`?

[1]: https://github.com/angular/angular/blob/5013a7e12dc917ca65e57c018f7e002105d8a717/packages/common/http/src/request.ts#L330
[2]: https://github.com/angular/angular/blob/5013a7e12dc917ca65e57c018f7e002105d8a717/packages/common/http/src/headers.ts#L148
[3]: https://github.com/angular/angular/blob/5013a7e12dc917ca65e57c018f7e002105d8a717/packages/common/http/src/headers.ts#L161

**Comment by hungyapp** [comment]
Hi. @gkalpak ,


Thanks to. get back to me. My application uses some 3rd party libraries such Google Analytics, Amplitude, QR Code (no ajax request: generator,  momentjs, ...),  so pretty. usual third party libraries.

None of the third parties interact. with the. angular. code.  - it's been. so. hard to track it, as it only happens in production - I use bugsnag and they provide a good. track,  however it's hard to understand why and how to reproduce.

However,  the Angular code doesn't seems right - if there Is a check to understand if the value is string, to convert it into an array, prior checking the .length property,  it seems that it should check. if the variable is an array and/or if it's null. 

I have along my code. a base. class. the unsubscribe all the subscriptions as below (I've noticed that this error is. being triggering randomically in other part. of the code):


`
export class ComponentBase implements OnDestroy {

	private subscriptions: Subscription[] = [];

	public set gc(value: Subscription) {
		this.subscriptions.push(value);
	}
	public get gc(): Subscription {
		if (this.subscriptions.length > 0)
			return this.subscriptions[0];

		return new Subscription();
	}

	constructor() {
	}

	ngOnDestroy(): void {
		this.subscriptions.forEach((item: Subscription) => item.unsubscribe());
	}



}

`

this is full stack trace bugsnag provides:

TypeError null is not an object (evaluating 'n.length') 
    dist/master/node_modules/@angular/common/fesm2015/http.js:234:26 applyUpdate
    [native code] forEach
    dist/master/node_modules/@angular/common/fesm2015/http.js:206:40 init
    dist/master/node_modules/@angular/common/fesm2015/http.js:269:13 forEach
    dist/master/node_modules/@angular/common/fesm2015/http.js:1566:32 
    dist/master/node_modules/rxjs/_esm2015/internal/Observable.js:42:35 _trySubscribe
    dist/master/node_modules/rxjs/_esm2015/internal/Observable.js:28:35 subscribe
    dist/master/node_modules/rxjs/_esm2015/internal/Observable.js:23:35 subscribe
    dist/master/node_modules/rxjs/_esm2015/internal/Observable.js:23:35 subscribe
    dist/master/node_modules/rxjs/_esm2015/internal/operators/mergeMap.js:57:49 _innerSub
    dist/master/node_modules/rxjs/_esm2015/internal/operators/mergeMap.js:51:23 _tryNext
    dist/master/node_modules/rxjs/_esm2015/internal/operators/mergeMap.js:34:26 _next
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:23 next
    dist/master/node_modules/rxjs/_esm2015/internal/util/subscribeToArray.js:3:24 
    dist/master/node_modules/rxjs/_esm2015/internal/Observable.js:42:35 _trySubscribe
    dist/master/node_modules/rxjs/_esm2015/internal/Observable.js:28:35 subscribe
    dist/master/node_modules/rxjs/_esm2015/internal/Observable.js:23:35 subscribe
    dist/master/node_modules/rxjs/_esm2015/internal/Observable.js:23:35 subscribe
    dist/master/node_modules/rxjs/_esm2015/internal/Observable.js:23:35 subscribe
    dist/master/node_modules/rxjs/_esm2015/internal/Observable.js:23:35 subscribe
    dist/master/webpack:/src/app/components/covid-19/covid-status/covid-status.component.ts:59:54 save
    dist/master/webpack:/src/app/components/covid-19/covid-status/covid-status.component.ts:49:14 
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:183:20 __tryOrUnsub
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:122:34 next
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:72:30 _next
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:23 next
    dist/master/node_modules/rxjs/_esm2015/internal/Subject.js:39:29 next
    dist/master/node_modules/@angular/material/fesm2015/bottom-sheet.js:323:38 
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:183:20 __tryOrUnsub
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:122:34 next
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:72:30 _next
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:23 next
    dist/master/node_modules/rxjs/_esm2015/internal/operators/take.js:35:34 _next
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:23 next
    dist/master/node_modules/rxjs/_esm2015/internal/Subject.js:39:29 next
    dist/master/node_modules/@angular/cdk/fesm2015/overlay.js:953:30 dispose
    dist/master/node_modules/@angular/material/fesm2015/bottom-sheet.js:320:24 
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:183:20 __tryOrUnsub
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:122:34 next
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:72:30 _next
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:23 next
    dist/master/node_modules/rxjs/_esm2015/internal/operators/take.js:35:34 _next
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:23 next
    dist/master/node_modules/rxjs/_esm2015/internal/operators/filter.js:33:34 _next
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:23 next
    dist/master/node_modules/@angular/core/fesm2015/core.js:24869:37 
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:183:20 __tryOrUnsub
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:122:34 next
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:72:30 _next
    dist/master/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:23 next
    dist/master/node_modules/rxjs/_esm2015/internal/Subject.js:39:29 next
    dist/master/node_modules/@angular/core/fesm2015/core.js:24859:19 emit
    dist/master/node_modules/@angular/material/fesm2015/bottom-sheet.js:159:41 _onAnimationDone
    dist/master/node_modules/@angular/material/bottom-sheet/index.d.ts.MatBottomSheetContainer.html:1:28 
    dist/master/node_modules/@angular/core/fesm2015/core.js:22477:36 dispatchEvent
    dist/master/node_modules/@angular/core/fesm2015/core.js:27493:39 onInvoke
    dist/master/webpack:/node_modules/zone.js/dist/zone-evergreen.js:130:49 run
    dist/master/node_modules/@angular/platform-browser/fesm2015/animations.js:181:27 scheduleListenerCallback
    dist/master/node_modules/@angular/platform-browser/fesm2015/animations.js:333:32 
    [native code] forEach
    dist/master/node_modules/@angular/animations/fesm2015/browser.js:4461:36 _onFinish
    dist/master/node_modules/@bugsnag/browser/dist/bugsnag.js:2606:35 
    dist/master/webpack:/node_modules/zone.js/dist/zone-evergreen.js:174:57 runTask
    dist/master/webpack:/node_modules/zone.js/dist/zone-evergreen.js:483:41 invokeTask
    dist/master/webpack:/node_modules/zone.js/dist/zone-evergreen.js:1596:20 invokeTask
    dist/master/webpack:/node_modules/zone.js/dist/zone-evergreen.js:1622:27 globalZoneAwareCallback

* sorry the. dots but my mac. keyboard is. buggy

**Comment by hungyapp** [comment]
I've found. the. following code int he @bugnsnag code. - which if they get any error in. the application, they need to. use HTTP. to. push the error to their library - does it make any sense?


moduleRef.onDestroy(() => remove(this._modules, moduleRef));
--
  | ngZone.runOutsideAngular(() => ngZone.onError.subscribe({
  | next: (error) => {
  | exceptionHandler.handleError(error);
  | }
  | }));
  | return _callAndReportToErrorHandler(exceptionHandler, ngZone,

**Comment by hungyapp** [comment]
This is my interceptor class that manipulates the. HTTP header (in angular. yet):

`
@Injectable()
export class InterceptorRequestService implements HttpInterceptor {

	constructor(
		private messageService: MessageService,
		private userAuthService: UserAuthService,
		private progressBarService: ProgressBarService) {
	}

	private resolveUrl(req: HttpRequest<any>): string {
		if (req.url.includes('/assets'))
			return req.url;

		const url = environment.apiUrl.concat(req.url);
		return url;
	}

	private addUserTokenHeader(req: HttpRequest<any>, url: string): HttpRequest<any> {
		const token = this.userAuthService.token;
		const utid = this.userAuthService.utid;
		const subdomain = this.userAuthService.subdomain;

		const headers = (!token ? {} : { Authorization: `Bearer ${token}` });

		headers['x-subdomain'] = subdomain;
		if (utid)
			headers['x-utid'] = utid;

		const request = req.clone({ url, setHeaders: headers });
		return request;
	}

	intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
		const url = this.resolveUrl(req);
		const request = this.addUserTokenHeader(req, url);
		this.progressBarService.add();
		return next.handle(request);
	}
}

`

**Comment by hungyapp** [comment]
Hi @gkalpak ,

One of my. guess was. the ComponentBase. where I handle. subscriptions. onNgDestroy, however I've just remove it last. night and this morning I. already got it in. production again:

**Comment by hungyapp** [comment]
Side Note: I've been speaking witht he venue that runs my product and they said some users get a message with an error. They managed them to kill. the page. and open it again.
However, I have 5 mobiles at home that I have been. trying to emulate the issue and can't get it. It's hard to. reproduce, however. I get several error log along the day :/

**Comment by gkalpak** [comment]
The `HttpInterceptor` seems like a good suspect :smiley:
Especially this line: `headers['x-subdomain'] = subdomain;`

Is it possible that `subdomain` is null? What does the `UserAuthService` implementation look like?

**Comment by hungyapp** [comment]
@gkalpak thats a good point! It miss the same treatment as the utid header. 

Ideally the subdomain is mandatory as the application has a Router Guard that do not enable access pages that require http request without the sub domain. 

However, it’s also a good point to track .. I’ll add a check and also a logger at this point. 

Just to share, interestingly I’ve removed all the ngDestroy strategy to unsubscribe the observable and yesterday I noticed a huge drop in the logs. It was also showing it in a few “ForkJoin” subscriptions. 

Yesterday I have also migrated the application from angular 10 to 11. I’m monitoring it, and report it back when I get some news. 

I’m doing my best to reproduce it, but it’s been hard!

**Comment by hungyapp** [comment]
Hi @gkalpak , you were right!

The  issue was  that  somehow the localStorage  was  loosing  the subdomain ,  and the header was with a null  value.


I'll be closing this bug  as  it solved my issue, but  I'm not  sure  if Angular should accept  or ignore nullable value for the header.

I believe that if the value was null,  angular  could skip that header  property  and the backend would manage the value not being sent,  for example.


Thanks for  your help!
