### ISSUE TITLE
Angular CLI 11 Namespace 'google.maps'

### ISSUE THREAD

**Issue by viky0157** [angular/angular#40428]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Error: node_modules/@agm/core/lib/directives/circle.d.ts:72:43 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

72     circleClick: EventEmitter<google.maps.MouseEvent>;
                                             ~~~~~~~~~~
node_modules/@agm/core/lib/directives/circle.d.ts:76:46 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.       

76     circleDblClick: EventEmitter<google.maps.MouseEvent>;
                                                ~~~~~~~~~~
node_modules/@agm/core/lib/directives/circle.d.ts:80:36 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

80     drag: EventEmitter<google.maps.MouseEvent>;
                                      ~~~~~~~~~~
node_modules/@agm/core/lib/directives/circle.d.ts:84:39 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

84     dragEnd: EventEmitter<google.maps.MouseEvent>;
                                         ~~~~~~~~~~
node_modules/@agm/core/lib/directives/circle.d.ts:88:41 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

88     dragStart: EventEmitter<google.maps.MouseEvent>;
                                           ~~~~~~~~~~
node_modules/@agm/core/lib/directives/circle.d.ts:92:41 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

92     mouseDown: EventEmitter<google.maps.MouseEvent>;
                                           ~~~~~~~~~~
node_modules/@agm/core/lib/directives/circle.d.ts:96:41 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

96     mouseMove: EventEmitter<google.maps.MouseEvent>;
                                           ~~~~~~~~~~
node_modules/@agm/core/lib/directives/circle.d.ts:100:40 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

100     mouseOut: EventEmitter<google.maps.MouseEvent>;
                                           ~~~~~~~~~~
node_modules/@agm/core/lib/directives/circle.d.ts:104:41 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

104     mouseOver: EventEmitter<google.maps.MouseEvent>;
                                            ~~~~~~~~~~
node_modules/@agm/core/lib/directives/circle.d.ts:108:39 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

108     mouseUp: EventEmitter<google.maps.MouseEvent>;
                                          ~~~~~~~~~~
node_modules/@agm/core/lib/directives/circle.d.ts:116:42 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

116     rightClick: EventEmitter<google.maps.MouseEvent>;
                                             ~~~~~~~~~~
node_modules/@agm/core/lib/services/google-maps-api-wrapper.d.ts:51:41 - error TS2314: Generic type 'MapHandlerMap<T>' requires 1 type argument(s).

51     subscribeToMapEvent<N extends keyof google.maps.MapHandlerMap>(eventName: N): Observable<google.maps.MapHandlerMap[N]>;
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@agm/core/lib/services/google-maps-api-wrapper.d.ts:51:94 - error TS2314: Generic type 'MapHandlerMap<T>' requires 1 type argument(s).

51     subscribeToMapEvent<N extends keyof google.maps.MapHandlerMap>(eventName: N): Observable<google.maps.MapHandlerMap[N]>;
                                                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@agm/core/lib/services/managers/marker-manager.d.ts:26:50 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.
39m
26     createEventObservable<T extends (google.maps.MouseEvent | void)>(eventName: google.maps.MarkerMouseEventNames | google.maps.MarkerChangeOptionEventNames, marker: AgmMarker): Observable<T>;
                                                    ~~~~~~~~~~
node_modules/@agm/core/lib/services/managers/marker-manager.d.ts:26:93 - error TS2694: Namespace 'google.maps' has no exported member 'MarkerMouseEventNames'.     

26     createEventObservable<T extends (google.maps.MouseEvent | void)>(eventName: google.maps.MarkerMouseEventNames | google.maps.MarkerChangeOptionEventNames, marker: AgmMarker): Observable<T>;
                                                                                               ~~~~~~~~~~~~~~~~~~~~~
node_modules/@agm/core/lib/services/managers/marker-manager.d.ts:26:129 - error TS2694: Namespace 'google.maps' has no exported member 'MarkerChangeOptionEventNames'.

26     createEventObservable<T extends (google.maps.MouseEvent | void)>(eventName: google.maps.MarkerMouseEventNames | google.maps.MarkerChangeOptionEventNames, marker: AgmMarker): Observable<T>;
                                                                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~    
node_modules/@agm/core/lib/directives/marker.d.ts:104:41 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

104     dragStart: EventEmitter<google.maps.MouseEvent>;
                                            ~~~~~~~~~~
node_modules/@agm/core/lib/directives/marker.d.ts:108:36 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

108     drag: EventEmitter<google.maps.MouseEvent>;
                                       ~~~~~~~~~~
node_modules/@agm/core/lib/directives/marker.d.ts:112:39 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

112     dragEnd: EventEmitter<google.maps.MouseEvent>;
                                          ~~~~~~~~~~
node_modules/@agm/core/lib/directives/marker.d.ts:116:41 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

116     mouseOver: EventEmitter<google.maps.MouseEvent>;
                                            ~~~~~~~~~~
node_modules/@agm/core/lib/directives/marker.d.ts:120:40 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

120     mouseOut: EventEmitter<google.maps.MouseEvent>;
                                           ~~~~~~~~~~
node_modules/@agm/core/lib/directives/polygon.d.ts:132:40 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

132     polyDrag: EventEmitter<google.maps.MouseEvent>;
                                           ~~~~~~~~~~
node_modules/@agm/core/lib/directives/polygon.d.ts:136:43 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

136     polyDragEnd: EventEmitter<google.maps.MouseEvent>;
                                              ~~~~~~~~~~
node_modules/@agm/core/lib/directives/polygon.d.ts:140:45 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

140     polyDragStart: EventEmitter<google.maps.MouseEvent>;
                                                ~~~~~~~~~~
node_modules/@agm/core/lib/directives/polyline.d.ts:89:40 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

89     lineDrag: EventEmitter<google.maps.MouseEvent>;
                                          ~~~~~~~~~~
node_modules/@agm/core/lib/directives/polyline.d.ts:93:43 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

93     lineDragEnd: EventEmitter<google.maps.MouseEvent>;
                                             ~~~~~~~~~~
node_modules/@agm/core/lib/directives/polyline.d.ts:97:45 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

97     lineDragStart: EventEmitter<google.maps.MouseEvent>;
                                               ~~~~~~~~~~
node_modules/@agm/core/lib/directives/rectangle.d.ts:76:46 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

76     rectangleClick: EventEmitter<google.maps.MouseEvent>;
                                                ~~~~~~~~~~
node_modules/@agm/core/lib/directives/rectangle.d.ts:80:49 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

80     rectangleDblClick: EventEmitter<google.maps.MouseEvent>;
                                                   ~~~~~~~~~~
node_modules/@agm/core/lib/directives/rectangle.d.ts:84:36 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

84     drag: EventEmitter<google.maps.MouseEvent>;
                                      ~~~~~~~~~~
node_modules/@agm/core/lib/directives/rectangle.d.ts:88:39 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

88     dragEnd: EventEmitter<google.maps.MouseEvent>;
                                         ~~~~~~~~~~
node_modules/@agm/core/lib/directives/rectangle.d.ts:92:41 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

92     dragStart: EventEmitter<google.maps.MouseEvent>;
                                           ~~~~~~~~~~
node_modules/@agm/core/lib/directives/rectangle.d.ts:96:41 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

96     mouseDown: EventEmitter<google.maps.MouseEvent>;
                                           ~~~~~~~~~~
node_modules/@agm/core/lib/directives/rectangle.d.ts:100:41 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

100     mouseMove: EventEmitter<google.maps.MouseEvent>;
                                            ~~~~~~~~~~
node_modules/@agm/core/lib/directives/rectangle.d.ts:104:40 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

104     mouseOut: EventEmitter<google.maps.MouseEvent>;
                                           ~~~~~~~~~~
node_modules/@agm/core/lib/directives/rectangle.d.ts:108:41 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

108     mouseOver: EventEmitter<google.maps.MouseEvent>;
                                            ~~~~~~~~~~
node_modules/@agm/core/lib/directives/rectangle.d.ts:112:39 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

112     mouseUp: EventEmitter<google.maps.MouseEvent>;
                                          ~~~~~~~~~~
node_modules/@agm/core/lib/directives/rectangle.d.ts:116:42 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

116     rightClick: EventEmitter<google.maps.MouseEvent>;
                                             ~~~~~~~~~~
node_modules/@agm/core/lib/directives/map.d.ts:222:40 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

222     mapClick: EventEmitter<google.maps.MouseEvent | google.maps.IconMouseEvent>;
                                           ~~~~~~~~~~
node_modules/@agm/core/lib/directives/map.d.ts:227:45 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

227     mapRightClick: EventEmitter<google.maps.MouseEvent>;
                                                ~~~~~~~~~~
node_modules/@agm/core/lib/directives/map.d.ts:232:43 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

232     mapDblClick: EventEmitter<google.maps.MouseEvent>;

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by petebacondarwin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
