### ISSUE TITLE
Error: "inject() must be called from an injection context" after upgrading to Angular 11

### ISSUE THREAD

**Issue by falk-stefan** [angular/angular#40430]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

Yes, the previous version in which this bug was not present was Angular 9.

### Description

I am linking a generated web-client into my Angular 11 Web-Application:

**package.json**

```
"meditation-rest-client": "./generated/meditation-rest-client",
```

After running `ng serve` the app crashes. See error message below.

## 🔥 Exception or Error
<pre><code>
Error: inject() must be called from an injection context
    at injectInjectorOnly (core.js:4901)
    at Module.ɵɵinject (core.js:4911)
    at Object.ApiModule_Factory [as factory] (meditation-rest-client.js:2885)
    at R3Injector.hydrate (core.js:11158)
    at R3Injector.get (core.js:10979)
    at core.js:11016
    at Set.forEach (<anonymous>)
    at R3Injector._resolveInjectorDefTypes (core.js:11016)
    at new NgModuleRef$1 (core.js:25046)
    at NgModuleFactory$1.create (core.js:25100)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
$ ng version
Angular CLI: 11.0.6
Node: 10.19.0
OS: linux x64

Angular: 11.0.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1100.6
@angular-devkit/build-angular      0.1100.6
@angular-devkit/core               11.0.6
@angular-devkit/schematics         11.0.6
@angular/cdk                       11.0.3
@angular/cli                       11.0.6
@angular/flex-layout               11.0.0-beta.33
@angular/http                      7.2.16
@angular/material                  11.0.3
@angular/material-moment-adapter   11.0.3
@schematics/angular                11.0.6
@schematics/update                 0.1100.6
rxjs                               6.6.3
typescript                         4.0.5
</code></pre>

**Anything else relevant?**

I have already applied suggested fixes without success from

- https://github.com/angular/angular/issues/25813
- https://github.com/OpenAPITools/openapi-generator/issues/5246

I do not know if the issues comes from Angular or OpenAPI. But this used to work previously without a problem.

**Comment by JoostK** [comment]
Hi @falk-stefan, I'm sorry for the trouble you're experiencing with the upgrade to 11. This error also reminds me of having multiple versions of `@angular/core` (as was the case in #40416), as `inject` depends on global state for it to work but with multiple copies of `@angular/core` you'll end up with multiple copies of the global state at runtime, which causes problems like these.

Could you please check if there are indeed multiple versions of `@angular/core` being bundled?

**Comment by falk-stefan** [comment]
@JoostK Hi! Sorry, I didn't see https://github.com/angular/angular/issues/40416 and it seems somewhere along the way I fixed the issue from there. This here (https://github.com/angular/angular/issues/40430) seems different to me as it happens at runtime and not at compile time.

I'm not sure how to find out, or how it would even be mossible for multiple `@angular/core` versions to be installed but .. how can I check if what you describe is happening?

What I know is that the API-Client which I am using depends on `"@angular/core": "^11.0.6"` (see below).

**Web-Appp `web-app/package.json`**

```json
{
  "name": "mobile-client",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "node server.js",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "ngcc"
  },
  "engines": {
    "node": "10.19.0",
    "npm": "6.14.4"
  },
  "private": true,
  "dependencies": {
    ...
    "@angular/core": "11.0.8",
    ...
  },
  "devDependencies": {
    ...
  }
}
```

**API-Client `web-app/generated/meditation-rest-client/package.json`**

```json
{
  "name": "meditation-rest-client",
  "version": "0.0.0",
  "description": "OpenAPI client for meditation-rest-client",
  "author": "OpenAPI-Generator Contributors",
  "keywords": [
    "openapi-client",
    "openapi-generator"
  ],
  "license": "Unlicense",
  "peerDependencies": {
    "@angular/core": "^11.0.6",
    "rxjs": "^6.6.0"
  },
  "main": "bundles/meditation-rest-client.umd.js",
  "module": "fesm2015/meditation-rest-client.js",
  "es2015": "fesm2015/meditation-rest-client.js",
  "esm2015": "esm2015/meditation-rest-client.js",
  "fesm2015": "fesm2015/meditation-rest-client.js",
  "typings": "meditation-rest-client.d.ts",
  "metadata": "meditation-rest-client.metadata.json",
  "sideEffects": false,
  "dependencies": {
    "tslib": "^2.0.0"
  }
}
```

This issue blocks me completely at the moment ^^

Please let me know if I can provide more information as I really need to resolve this.

**Comment by falk-stefan** [comment]
#### Update


I have installed [`npm-why`](https://github.com/amio/npm-why) 

```none
$ ./node_modules/.bin/npm-why @angular/core

  Who required @angular/core:

  mobile-client > @angular/core@11.0.8
```

**Comment by falk-stefan** [comment]
The issues was that there was a `node_modules/` folder created which, I'm sure, wasn't there, or wasn't a problem, with Angular 9.

I don't know what exactly changed in Angular 9 but I was able to fix this thanks to some help in https://github.com/OpenAPITools/openapi-generator/issues/8447. 

As or me, this issue can be closed.
