### ISSUE TITLE
Compiler does not complain undecorated class using angular features

### ISSUE THREAD

**Issue by phoenix09208** [angular/angular#40438]
# 🐞 bug report

### Affected Package

 Not sure maybe @angular/compiler

### Is this a regression?

 Angular 9.1 did not enforce this, although its deprecated as far as i know

### Description

 We use lot of inheritance based components, most base class uses angular features such as `@ViewChild`, in Angular 9 it works fine without adding any decorators to base class, as i understand from Angular 10 onwards, it enforces to have decorator on any class using Angular features, if not it will throw error during compilation:

`error NG2007: Class is using Angular features but is not decorated. Please add an explicit Angular decorator`

What's weird is, we updated our project from Angular 9 to Angular 10, it did not complain about it when buildlng, even the base classes does not have any decorator. And migration did not add any decorate as well.  Angular features such as `@ViewChild` still works in some base classes (well, long story short some class does not evaluate `@ViewChild`, thats reason we update to 10, anyway very long story.)

## 🔬 Minimal Reproduction

 Cannot reproduce on new project, only happens to the project im working on.

## 🔥 Exception or Error

It supposes to throw error 
`error NG2007: Class is using Angular features but is not decorated. Please add an explicit Angular decorator`, however it **DID NOT**.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 10.2.1
Node: 10.15.2
OS: win32 x64

Angular: 10.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.1
@angular-devkit/build-angular   0.1002.1
@angular-devkit/core            10.2.1
@angular-devkit/schematics      10.2.1
@angular/cdk                    10.2.7
@angular/cli                    10.2.1
@angular/material               10.2.7
@schematics/angular             10.2.1
@schematics/update              0.1002.1
rxjs                            6.5.5
typescript                      4.0.5

</code></pre>

**Anything else relevant?**
The reason we upgrade to Angular 10 is because [this issue](https://stackoverflow.com/questions/65718785/strange-behavior-with-undecorated-base-class-in-angular-10)

**Comment by petebacondarwin** [comment]
It is interesting that you cannot reproduce this on a new project. This implies that there is something else going on. Without a reproduction we can't help to diagnose this problem.

**Comment by phoenix09208** [comment]
> It is interesting that you cannot reproduce this on a new project. This implies that there is something else going on. Without a reproduction we can't help to diagnose this problem.

I agree this is project specific issue, anything you can recommend to check on? Is there any option in angular.json will possible omit this error? Thanks

**Comment by petebacondarwin** [comment]
Can you give an example of the code that you expect to show an error?

**Comment by phoenix09208** [comment]
> Can you give an example of the code that you expect to show an error?

Sure, im using one very simple example here, suppose i have base class

`export abstract class BaseClass implements OnInit {
  @ViewChild('test', {static: false})
  test: ElementRef;

  protected constructor() {
  }

  ngOnInit(): void {
  }
}
`
and a component inherit from base class

`export class TestComponent extends BaseClass implements OnInit {
  constructor() {
    super();
  }

  ngOnInit(): void {
  }
}`

because base class is using angular feature without decorator, on building the project it should throw
`error NG2007: Class is using Angular features but is not decorated. Please add an explicit Angular decorator`
however it does not complain in my project, if i move those classes to a new project, it throws the error as expected

**Comment by petebacondarwin** [comment]
Are these classes in the main application or in a library? I note in the commit that introduced this error that ngcc will not trigger the warning: https://github.com/angular/angular/commit/4c92cf43cf26d2df356093c67c4b8ea1d5c5def6#diff-05f578fb87d52034f577816e2947eb548b539febf8a7ac4a6b14203c4b926674R112

**Comment by petebacondarwin** [comment]
Can you confirm that no part of your application is actually running in ViewEngine mode? This error will only be shown if Ivy is enabled.
Also can you check whether you have multiple versions of `@angular/compiler-cli` installed by accident?

**Comment by phoenix09208** [comment]
> Are these classes in the main application or in a library? I note in the commit that introduced this error that ngcc will not trigger the warning: 4c92cf4#diff-05f578fb87d52034f577816e2947eb548b539febf8a7ac4a6b14203c4b926674R112

These classes are in main application.

> Can you confirm that no part of your application is actually running in ViewEngine mode? This error will only be shown if Ivy is enabled.

The application is running in Ivy, ViewEngine is not used.

> Also can you check whether you have multiple versions of `@angular/compiler-cli` installed by accident?
- Only  `-- @angular/compiler-cli@10.2.4 is used

**Comment by petebacondarwin** [comment]
Hmm... can you try debugging `ng build` putting a break-point at https://github.com/angular/angular/blob/10.2.4/packages/compiler-cli/src/ngtsc/annotations/src/directive.ts#L81

**Comment by phoenix09208** [comment]
> Hmm... can you try debugging `ng build` putting a break-point at https://github.com/angular/angular/blob/10.2.4/packages/compiler-cli/src/ngtsc/annotations/src/directive.ts#L81

Maybe a noob question, but how do you attach debugger to actual build process?

**Comment by petebacondarwin** [comment]
That's a great question. It used to be not so easy but recent improvements to VS Code actually make it much easier, I have found.

* If you can open your project in VS Code, then navigate to the file above (at `node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/directive.ts`) and add a breakpoint at line 81.
* Then in the TERMINAL view of VS Code select the drop-down and click on `Create JavaScript Debug Terminal`.
* Finally in this terminal simply run the `ng build` command.
* The debugger should attach automatically and then stop on the breakpoint eventually.

**Comment by phoenix09208** [comment]
> That's a great question. It used to be not so easy but recent improvements to VS Code actually make it much easier, I have found.
> 
> * If you can open your project in VS Code, then navigate to the file above (at `node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/directive.ts`) and add a breakpoint at line 81.
> * Then in the TERMINAL view of VS Code select the drop-down and click on `Create JavaScript Debug Terminal`.
> * Finally in this terminal simply run the `ng build` command.
> * The debugger should attach automatically and then stop on the breakpoint eventually.

Hi thanks for the instruction,  always good to know new things. So i did debugging both sample application and my project build process, this is where i find very weird, break points hit DirectiveDecoratorHandler contructors and analyze() method in sample application, however they are not hit in my project, lol

**Comment by phoenix09208** [comment]
Ok, issue solved! Thanks heaps @petebacondarwin for helping, it ends up to be `aot` not turned on for `dev` build, only turned on for `prod`, the debugging process is very helpful, i can compare side to side with a sample project stack trace to see where it actually skipped the `DirectiveDecoratorHandler `

**Comment by petebacondarwin** [comment]
Glad you worked it out!
