### ISSUE TITLE
node error

### ISSUE THREAD

**Issue by rahiyansafz** [angular/angular#40437]
How to run/use Angular using DENO or without node???

**Comment by petebacondarwin** [comment]
Can you clarify what you mean by "run/use Angular"? Angular runs in the browser so there is no relation to Node.js (or Deno) there. You can host an Angular app with any backend HTTP server, so you could run a Deno backend if you wanted.

If you mean building an Angular app using the Angular CLI, then that indeed does rely upon Node.js. We currently do not support running the CLI in Deno - and in any case this is not the correct project for that. Instead you would need https://github.com/angular/angular-cli.

Finally, if you are referring to server side rendering (SSR), then I suggest you ask on the Universal project at https://github.com/angular/universal.

Closing as this question is not actionable by this project.
