### ISSUE TITLE
@angular/http throws errors only in Firefox randomly

### ISSUE THREAD

**Issue by hubinbin91** [angular/angular#40443]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/http

### Description

When I try to use Firefox to request(POST), I will randomly catch the following exception, but the back end can accept the request.

![adas](https://user-images.githubusercontent.com/29529563/104689737-034e8b00-573e-11eb-9cf1-81e6d3d79d5d.png)

## 🔬 Minimal Reproduction

It happened randomly, I can't provide it.

## 🔥 Exception or Error
<pre><code>
const request: Request = new Request(
  new RequestOptions({
    headers: headers,
    method: method,
    url: url,
    body: body ? JSON.stringify(body): undefined
  })
);

return this.http.request(request).map(res => {
  return res.text() !== '' ? res.json() : {}
}).catch(e => {
  console.log(e);
  this.errorHandler.handleError(e);
});
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 1.7.4
Node: 8.17.0
OS: win32 x64
Angular: 4.4.7
"@angular/animations": "^4.1.0",
"@angular/common": "^4.1.0",
"@angular/compiler": "^4.1.0",
"@angular/core": "^4.1.0",
"@angular/forms": "^4.1.0",
"@angular/http": "^4.1.0",
</code></pre>

**Anything else relevant?**

only in Firefox.

**Comment by petebacondarwin** [comment]
The version of Angular that you are using is very old and no longer supported. Please can you try updating to the latest version (currently 11.0.x).

**Comment by AndrewKushnir** [comment]
Just to add to what Pete mentioned, the package that you refer to (`@angular/http`) is deprecated, the replacement is the `@angular/common/http` one. Please try to upgrade Angular packages to the latest version and switch to `@angular/common/http`. If the problem still exists, please reopen this ticket or create a new one. Thank you.
