### ISSUE TITLE
Angular CLI 11 Namespace 'google.maps'

### ISSUE THREAD

**Issue by viky0157** [angular/angular#40441]
[src.zip](https://github.com/angular/angular/files/5818636/src.zip)

Error: node_modules/@agm/core/lib/directives/circle.d.ts:72:43 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

72 circleClick: EventEmitter<google.maps.MouseEvent>;

**Comment by JonWallsten** [comment]
@viky0157: Angular Google Maps is not developed by the Angular team. I propose you add an issue here instead: https://github.com/SebastianM/angular-google-maps/issues

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
