### ISSUE TITLE
Unable to open new PWA window in PWA app

### ISSUE THREAD

**Issue by JeanBaptisteINITIATIVES** [angular/angular#40447]
# 🐞 bug report

### Affected Package
None

### Is this a regression?

No

### Description

When I deploy in production my Angular app, I can install it as a PWA without any problem, with Chrome. But in my code, I have to open in several case another window, but it always opens in a new Chrome tab instead of new PWA window, despite many configurations...
Here is what i tried :
- change the target in the window.open
- use router with createUrlTree
- use [routerLink] in html for navigation with target attribute
- configure scope and start_url properly in manifest.webmanifest (start_url: ./ and scope: .)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.6
Node: 14.4.0
OS: darwin x64
@angular-devkit/architect           0.1100.6
@angular-devkit/build-angular   0.1100.6
@angular-devkit/core                  11.0.6
@angular-devkit/schematics      11.0.6
@angular/cdk                               11.0.2
@angular/cli                                  11.0.6
@angular/google-maps               10.1.0
@angular/material                        11.0.2
@angular/service-worker            11.0.7
@schematics/angular                  10.0.8
@schematics/update                    0.1100.6
</code></pre>

**Anything else relevant?**
The same issue on Chrome, Firefox and Safari.

Thanks

**Comment by petebacondarwin** [comment]
I am not an expert in PWA but as far as I can tell it is not possible to open a new application window. You can either open a new page within the current PWA app or open a new page in an external browser (in this case Chrome). Which of these occurs is governed by the [`scope` in the manifest file](https://web.dev/add-manifest/#scope) (as I suspect you know).

I don't think there is anything that can be done from an Angular framework point of view.

**Comment by JeanBaptisteINITIATIVES** [comment]
@petebacondarwin,

Thanks for your answer, I thought there was a little hack to do this, as we can do it manually through the PWA menu options (we can open in web browser or open a new in-app window)...
I know that the Angular framework is SPA-oriented, but if somebody has a solution to make it works, I think it should be great for many people, well I think ;-)

Best regards

**Comment by gkalpak** [comment]
Based on the discussion above, I am going to close this issue. As @petebacondarwin said, there is not something we can do in the Angular framework to affect how URLs are opened in PWAs.

AFAIK, opening multiple instances of a standalone PWA is currently not possible anyway (at least on Android).
