### ISSUE TITLE
Refactor RuntimeErrors thrown outside of ngDevMode

### ISSUE THREAD

**Issue by twerske** [angular/angular#40450]
### Description
In https://github.com/angular/angular/pull/40326 we introduce a TODO to refactor current RuntimeErrors which are exposed in the prod bundle and not wrapped by ngDevMode.

We should revisit all instances where `RuntimeError` is thrown and see if `ngDevMode` can be added there instead to tree-shake more devmode-only code (and eventually remove `ngDevMode` check in `packages/core/src/render3/error_code.ts`

**Comment by AndrewKushnir** [comment]
The mentioned TODO was removed recently (as no longer needed), so we can close this ticket.
