### ISSUE TITLE
Angular data tables not working in Stack blitz in Angular 9 

### ISSUE THREAD

**Issue by afeef1915** [angular/angular#40466]
Problem

![image](https://user-images.githubusercontent.com/16572202/104882789-acd58c80-5989-11eb-8e52-0981040561ee.png)

Error in Angular core Libraries.

I have tried 
https://l-lin.github.io/angular-datatables/#/extensions/colreorder

Stack blitz links 
https://stackblitz.com/edit/angular-ivy-ij7ax4

I have also asked the same from angular data tables they have advised me its Stack blitz issue

https://github.com/l-lin/angular-datatables/issues/1496

Please  can you advice  me ow to fix this issue  please.

Pkg json

 						{
						  "name": "daata",
						  "version": "1.0.0",
						  "scripts": {
							"ng": "ng",
							"start": "ng serve",
							"build": "ng build",
							"test": "ng test",
							"lint": "ng lint",
							"e2e": "ng e2e"
						  },
						  "private": true,
						  "dependencies": {
							"@angular/animations": "9.1.13",
							"@angular/cdk": "9.2.4",
							"@angular/common": "9.1.13",
							"@angular/compiler": "9.1.13",
							"@angular/core": "9.1.13",
							"@angular/forms": "9.1.13",
							"@angular/platform-browser": "9.1.13",
							"@angular/platform-browser-dynamic": "9.1.13",
							"@angular/router": "9.1.13",
							"@auth0/angular-jwt": "3.0.1",
							"@ng-select/ng-option-highlight": "0.0.2",
							"@ng-select/ng-select": "3.7.3",
							"@types/jquery": "^3.5.5",
							"angular-archwizard": "5.0.1",
							"angular-datatables": "v10.1.0",
							"angular2-ladda": "2.0.2",
							"bootstrap": "4.5.3",
							"classlist.js": "1.1.20150312",
							"core-js": "3.8.2",
							"datatables.net": "1.10.23",
							"datatables.net-bs4": "^3.2.2",
							"datatables.net-colreorder": "1.5.3",
							"datatables.net-colreorder-dt": "1.5.3",
							"datatables.net-dt": "1.10.23",
							"datatables.net-responsive": "2.2.7",
							"datatables.net-responsive-dt": "2.2.7",
							"file-saver": "2.0.5",
							"jquery": "^3.5.1",
							"moment": "2.29.1",
							"ngx-scrollbar": "7.5.3",
							"popper.js": "1.16.1",
							"rxjs": "6.5.5",
							"sweetalert2": "10.13.0",
							"tslib": "1.14.1",
							"zone.js": "0.10.3"
						  },
						  "devDependencies": {
							"@angular-devkit/build-angular": "~0.901.0",
							"@angular/cli": "^9.1.0",
							"@angular/compiler-cli": "~9.1.0",
							"@angular/language-service": "^9.1.0",
							"@fortawesome/fontawesome-free": "^5.13.0",
							"@types/datatables.net": "^1.10.18",
							"@types/jasmine": "^3.5.10",
							"@types/jasminewd2": "^2.0.8",
							"@types/jquery": "^3.3.34",
							"@types/node": "^12.11.1",
							"codelyzer": "^5.2.2",
							"jasmine-core": "~3.4.0",
							"jasmine-spec-reporter": "~4.2.1",
							"karma": "~4.1.0",
							"karma-chrome-launcher": "~2.2.0",
							"karma-coverage-istanbul-reporter": "^2.1.1",
							"karma-jasmine": "~2.0.1",
							"karma-jasmine-html-reporter": "^1.5.3",
							"protractor": "^5.4.3",
							"ts-node": "~7.0.0",
							"tslint": "~5.15.0",
							"typescript": "~3.8.3"
						  }
						}

Thanks

**Comment by petebacondarwin** [comment]
Please note that Angular version 9 is no longer supported. Please update to the latest v11 and try again. There were a number of changes to `ngcc`, which is responsible for upgrading libraries to the Ivy runtime, that may help here.

**Comment by JoostK** [comment]
This doesn't look like an Angular issue to me. `angular-datatables` relies on jQuery to be loaded as an ambient module, which it isn't in StackBlitz. This may be an issue with how StackBlitz works. The console error is reported in `core.umd.js` as that is because the default `ErrorHandler`  logs any error that occurs during rendering to the console, but ultimately the error occurs in `angular-datatables.umd.js`  as can be seen in the stacktrace.

**Comment by alexzuza** [comment]
AFAIK, it is related to Stackblitz issue reported here https://github.com/stackblitz/core/issues/700

**Comment by AndrewKushnir** [comment]
Closing this ticket based on the comments in this thread.
