### ISSUE TITLE
Make SwUpdate's API more coherent and useful

### ISSUE THREAD

**Issue by TheParad0X** [angular/angular#40467]
This feature request is for @angular/service-worker

The current API is not very user-friendly. **So far, in order to check for updates, I have to do the following:**

- Call checkForUpdate() every N minutes. When it returns, **I don't know if the check was successful and if there is an update**
- I have to subscribe to SwUpdate.available(), and I can act accordingly, for example prompt the user
- SwUpdate.available() **seems to fire only once**, I need to save (or remember) that an UpdateAvailableEvent is available (if the user clicks "No" in my "Would-you-like-to-reload-prompt". Also, SwUpdate.available() seems to be firing twice in a row from time to time, I have not been able to reproduce it consistently.
- SwUpdate.activateUpdate() also does not give my anything useful in return.

**How I would like the API to be:**
- checkForUpdate() returns Observable<UpdateAvailableEvent> if there is an update, or undefined if not. And an error if the check failed (no connection?)
- activateUpdate() returns Observable<boolean> with true if it was successful, or false if not
- available() would not be needed anymore

Does this make sense?

Cheers

**Comment by gkalpak** [comment]
I agree that the `SwUpdate` API could use some improvement. This is also being discussed in #39840.

BTW, regarding your comment that "`SwUpdate#available` would not be needed anymore", this is not necessarily true. `SwUpdate#available` will emit to notify about updates even if they were not a result of `SwUpdate#checkForUpdate()`. The update could be discovered as a result of calling `checkForUpdate()` on a different tab or as a result of the SW's automatic check for updates (e.g. on navigation requests).

(But the rest sounds reasonable.)

##
In the interest of having a single point of tracking this feature request, could you close this issue and add your ideas in #39840? 🙏

**Comment by TheParad0X** [comment]
Sure. Thanks
