### ISSUE TITLE
Building of Angular project runs out of memory after introducing strict mode

### ISSUE THREAD

**Issue by henrikdahl8240** [angular/angular#40468]
I have an Angular project. Initially it was not using strict mode because there was no strict mode. When building this non-strict variant of my Angular project, the Nodejs process running the Typescript compiler takes up to approximately 8GB of RAM.

Now Angular and typescript have come to support strict mode, so I have introduced strict mode.

I have done many changes like this:

Before strict mode:
friend: Person;

After strict mode:
friend: Person | undefined;

Now I cannot build the Angular project anymore because the Node process fails with the usual out of heap space error as approximately 30 GB has been allocated by the Node process. It also takes much, much longer time to run the build process until it finally fails.

As far as I have read, the Typescript compiler consumes much more memory when using union types which you just need to do, when using the strict mode.

My machine only has 32 GB of RAM.

Will there be something done to the Typescript compiler, so it's not so RAM hungy when using union types or I must face, that I need a machine with more than 32 GB RAM for building my Angular project?

Is there some flag which can be used, so the Nodejs process can allocate more memory than the amount of physical RAM and hereby using virtual memory in addition? If I for instance do "NODE_OPTIONS=--max_old_space_size=65536" I cannot make Nodejs to allocate more than the amount of physical RAM.

**Comment by JoostK** [comment]
Hi @henrikdahl8240,

Such extensive memory usage sounds like a bug to me. It is unclear from the issue description what version you are using (please fill in the issue template which requests this information) but I'd request that you update to Angular 11.1.0-rc.0 to be able to test with TypeScript 4.1, as that version of TS has some fixes for issues like these.

**Comment by henrikdahl8240** [comment]
OK. I'll do that.

Is it possible to get some additional relevant information concerning the processe to the output e.g. by adding some flag? 

For your information, I think it's around 500 components I have.

**Comment by JoostK** [comment]
It is generally quite difficult to locate the cause of issues like these. I tend to attach a debugger and then start a profiling session, which more often than not gives an idea of where the bottleneck occurs. This isn't necessarily true for _memory_ related issues like this, in which case inspecting heap dumps may be of help, but those can be difficult to analyze if you don't know what to look for.

**Comment by henrikdahl8240** [comment]
OK. Now I have done as you wrote. The filled-in template:

# 🐞 bug report

### Affected Package
I have now also tried with version v11.1.0-rc.0 and Typescript version 4.1.3.

The error occurs when building, e.g.: `ng build --base-href / --prod`

I cannot pinpoint a specific package, but please read the description in my first post.

### Is this a regression?

As I described in the initial post, it built fine before introducing the changes needed for the strict mode.


### Description

Please find the description in my initial post.


## 🔬 Minimal Reproduction
I cannot make a small case which shows the problem. I have in the magnitude of 500 components. I clearly think, that the volume of code makes the error to occur.


## 🔥 Exception or Error
<pre><code>

Output when running the command ng build --base-href / --prod:

- Generating browser application bundles...

<--- Last few GCs --->

[8132:00000176DA4F82A0]   731065 ms: Scavenge 29481.8 (30030.3) -> 29478.2 (30036.3) MB, 71.2 / 0.0 ms  (average mu = 0.495, current mu = 0.491) allocation failure 
[8132:00000176DA4F82A0]   809424 ms: Mark-sweep 29487.7 (30036.3) -> 29478.3 (30047.6) MB, 78252.2 / 1.0 ms  (average mu = 0.333, current mu = 0.069) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 00007FF7B528540F v8::internal::Isolate::ArchiveSpacePerThread+4447
 2: 00007FF7B52202E6 DSA_meth_get_flags+65078
 3: 00007FF7B52211E6 node::OnFatalError+294
 4: 00007FF7B5B1D8AE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF7B5B01F7D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF7B599AFAC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF7B5985EC8 v8::internal::NativeContextInferrer::Infer+59352
 8: 00007FF7B596AA9F v8::internal::MarkingWorklists::Local::SwitchToContextSlow+60639
 9: 00007FF7B597EE41 v8::internal::NativeContextInferrer::Infer+30545
10: 00007FF7B5975F9D v8::internal::MarkCompactCollector::EnsureSweepingCompleted+6285
11: 00007FF7B597DF6E v8::internal::NativeContextInferrer::Infer+26750
12: 00007FF7B598222B v8::internal::NativeContextInferrer::Infer+43835
13: 00007FF7B598C112 v8::internal::ItemParallelJob::Task::RunInternal+18
14: 00007FF7B598C0A1 v8::internal::ItemParallelJob::Run+641
15: 00007FF7B595E24D v8::internal::MarkingWorklists::Local::SwitchToContextSlow+9357
16: 00007FF7B597653E v8::internal::MarkCompactCollector::EnsureSweepingCompleted+7726
17: 00007FF7B5974C84 v8::internal::MarkCompactCollector::EnsureSweepingCompleted+1396
18: 00007FF7B5972388 v8::internal::MarkingWorklists::Local::SwitchToContextSlow+91592
19: 00007FF7B59A0DF1 v8::internal::Heap::LeftTrimFixedArray+945
20: 00007FF7B59A2FD5 v8::internal::Heap::PageFlagsAreConsistent+709
21: 00007FF7B59981D1 v8::internal::Heap::CollectGarbage+1969
22: 00007FF7B5996465 v8::internal::Heap::AllocateExternalBackingStore+1493
23: 00007FF7B59B84F0 v8::internal::Factory::NewFillerObject+192
24: 00007FF7B56DE77A v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1386
25: 00007FF7B5BA4BBD v8::internal::SetupIsolateDelegate::SetupHeap+456749
26: 0000005C62D9C47B 
</code></pre>


## 🌍  Your Environment

**Angular Version:11.1.0-rc.0
<pre><code>


     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.1.0-rc.0
Node: 15.6.0
OS: win32 x64

Angular: 11.1.0-rc.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.0-rc.0
@angular-devkit/build-angular   0.1101.0-rc.0
@angular-devkit/core            11.1.0-rc.0
@angular-devkit/schematics      11.1.0-rc.0
@schematics/angular             11.1.0-rc.0
@schematics/update              0.1101.0-rc.0
rxjs                            6.6.3
typescript                      4.1.3
    

</code></pre>

**Anything else relevant?**
My machine is a Lenovo ThinkPad having 32 GB of RAM running Windows 10 Pro.

**Comment by JoostK** [comment]
Thank you for trying with the RC and TS 4.1. I was hoping it could have resolved the issue, but it doesn't look like that's the case.

I'm afraid that without a reproduction I won't be able to help you further. Are you able to share a repo in private with me?

**Comment by nirmal-mobiquity** [comment]
@JoostK no progress in this issue, can we close this if no action required in it.

**Comment by iRealNirmal** [comment]
@JoostK if there isn't anything we can do here, can we close this issue ? Or you still working in It after getting repo in private.

**Comment by henrikdahl8240** [comment]
@iRealNirmal Let's close it for now and potentially get back to it.
