### ISSUE TITLE
Router: use UrlHandlingStrategy from DI

### ISSUE THREAD

**Issue by glebmachine** [angular/angular#40478]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/router

### Description
Could you please use `UrlHandlingStrategy` from DI in Router. 
This will allow to prepend language to all `routerLink` and direct `navigate`, `navigateByUrl` calls.
So, all l10n packages will be able to avoid unmet `localize` pipes

it's already defined in providers, but directly declared as property in Router:
https://github.com/angular/angular/blob/4e8198d60f421ce120e3a6b57afe60a9332d2692/packages/router/src/router.ts#L440

### Describe the solution you'd like
Just move `UrlHandlingStrategy` from here property:
https://github.com/angular/angular/blob/4e8198d60f421ce120e3a6b57afe60a9332d2692/packages/router/src/router.ts#L440
to constructor:
https://github.com/angular/angular/blob/4e8198d60f421ce120e3a6b57afe60a9332d2692/packages/router/src/router.ts#L484

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by pumano** [comment]
would like to use it when it will be available because sometimes required to prepend language before router part for example: `host/en/users/1` or `host/it/users/1`

**Comment by JoostK** [comment]
Isn't it already exposed? The `Router` is registered in DI using a factory function that takes an optional `UrlHandlingStrategy` token:

https://github.com/angular/angular/blob/605775398f0ae1893a0a02a6eb3c1200f20475e9/packages/router/src/router_module.ts#L51-L59

So I think it should be possible to provide that token with a custom implementation?

**Comment by glebmachine** [comment]
Unfortunately it's not exposed : /
https://github.com/angular/angular/blob/4e8198d60f421ce120e3a6b57afe60a9332d2692/packages/router/src/router.ts#L440

**Comment by JoostK** [comment]
It should be re-assigned from within the factory function:

https://github.com/angular/angular/blob/605775398f0ae1893a0a02a6eb3c1200f20475e9/packages/router/src/router_module.ts#L437-L439

**Comment by glebmachine** [comment]
@JoostK I missed that, thank you! 🍺
