### ISSUE TITLE
Angular repo packages incompatibilities with Apple M1 ARM64 processor

### ISSUE THREAD

**Issue by abarghoud** [angular/angular#40498]
# 🚀 feature request
Update some packages versions to be able to work on Angular repo locally on new Apple M1 machines.

### Relevant Package
angular:dev-infra

### Description
Some packages do not work properly on Apple M1 machine.

### Prerequisites
1. Modify node version fixed at 13.0.0 maximum in package.json to at least 15.3 as nodejs started running natively on M1 machines with this version.

```
yarn
yarn install v1.22.5
$ node tools/yarn/check-yarn.js
[1/5] 🔍  Validating package.json...
error angular-srcs@11.2.0-next.0: The engine "node" is incompatible with this module. Expected version ">=10.9.0 <13.0.0". Got "15.6.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

2.  Update bazelisk to at least 1.6.0 version in which arm64 is supproted as you can see here https://github.com/bazelbuild/bazelisk/releases/tag/v1.6.0.

When I try to run `yarn bazel test //packages/...`, I get:
```

yarn run v1.22.5
$ /Users/anasbarghoud/WebstormProjects/angular/node_modules/.bin/bazel test //packages/...
FATAL: Your platform/architecture combination darwin - arm64 is not yet supported.
    You may need to compile Bazelisk yourself, or use the Python version.
    See instructions at https://github.com/bazelbuild/bazelisk/blob/master/README.md.
node:internal/validators:129
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received an instance of Promise
    at new NodeError (node:internal/errors:329:5)
    at validateString (node:internal/validators:129:11)
    at normalizeSpawnArguments (node:child_process:455:3)
    at spawn (node:child_process:617:13)
    at spawnWithSignal (node:child_process:757:17)
    at main (/Users/anasbarghoud/WebstormProjects/angular/node_modules/@bazel/bazelisk/bazelisk.js:54:14)
    at Object.<anonymous> (/Users/anasbarghoud/WebstormProjects/angular/node_modules/@bazel/bazelisk/bazelisk.js:68:3)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32) {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

3. Update puppeteer to a version that supports arm64.

Once node maximum version modified, running yarn install causing the following error when trying to run `node install.js`:

```
...
warning " > tsickle@0.38.1" has incorrect peer dependency "typescript@~3.8.2".
warning " > inquirer-autocomplete-prompt@1.0.2" has incorrect peer dependency "inquirer@^5.0.0 || ^6.0.0".
warning " > tslint-eslint-rules@5.4.0" has incorrect peer dependency "tslint@^5.0.0".
warning " > tslint-eslint-rules@5.4.0" has incorrect peer dependency "typescript@^2.2.0 || ^3.0.0".
warning " > typed-graphqlify@2.3.0" has incorrect peer dependency "typescript@^3.5.1".
[5/5] 🔨  Building fresh packages...
[1/17] ⠁ fsevents
[13/17] ⠁ protobufjs
[10/17] ⠁ puppeteer
[14/17] ⠁ spawn-sync
error /Users/anasbarghoud/WebstormProjects/angular/node_modules/puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/anasbarghoud/WebstormProjects/angular/node_modules/puppeteer
Output:
The chromium binary is not available for arm64: 
If you are on Ubuntu, you can install with: 

 apt-get install chromium-browser

/Users/anasbarghoud/WebstormProjects/angular/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:112
            throw new Error();
            ^
```

I don't know if there are more things to do, the points above are what I identified when I tried to execute some yarn commands.

**Comment by petebacondarwin** [comment]
You are ahead of the curve @abarghoud - hopefully we will catch up as more team members get an M1 mac.
If you are interested you could offer small PRs that move us in the right direction, but I suspect this is quite a big task that would also involve the CLI project.

**Comment by Splaktar** [comment]
I've switched to an m1Max MacBook Pro as my main device now and this is a problem that I'm running into. Can someone point me in the right direction to where I can start to look at this?

I've got Bazel `4.2.1` installed locally, but the build seems to be trying to install Bazel `4.0.0` and failing. Is there a way that I can define an environment variable to tell it to look at my local Bazel installation?

**Comment by devversion** [comment]
@Splaktar `export BAZEL=$(which bazel)` in your zshrc. Using that across all of Angular! 😄

**Comment by Splaktar** [comment]
@devversion thank you. I've done that, but I am still getting the same errors where it tries to download Bazel 4.0.0. Do I need to clear out some local state?

**Comment by devversion** [comment]
@Splaktar It might be that `yarn test` for COMP repo does not support it, but `./build-packages-dist` in FW should work. What failed for you from the both now?

**Comment by Splaktar** [comment]
@devversion I'm still getting both of these: https://github.com/angular/angular/issues/40498#issuecomment-973146883. I restarted my terminal, etc.

**Comment by Splaktar** [comment]
OK, I got it. I had to use `export BAZEL=/opt/local/bin/bazel`.

`export BAZEL=$(which bazel)` was picking up `/Users/splaktar/Git/angular/angular/node_modules/.bin/bazel` for some strange reason.

**Comment by JoostK** [comment]
The Angular repo is now on Node 16 and Bazel 5, which both support arm64. I personally don't experience any build issues with an M1 Max so I'll go ahead and close this as resolved; please open a new issue if there's incompatibilities in areas I may not be aware of.
