### ISSUE TITLE
ARB Serializer -> missing "meaning" on extracted translation files

### ISSUE THREAD

**Issue by meriturva** [angular/angular#40506]
# 🐞 bug report

### Is this a regression?
No, ARB file format is new on Angular 11.1

### Description

We would like to support ARB format for our component translations files (to avoid the use of XML parser library to handle xliff files: xml2js or cheerio). After update our solution to Angular 11.1 we are now testing ARB extraction format but what we have noted is that there is no more _meaning_ information extracted:

```
"71788121164220023": "no tags found",
  "@71788121164220023": {
    "description": "No tags found placeholder",
    "x-locations": [
      {
        "file": "projects\\xxxxx\\hardware-editors\\src\\lib\\elements\\channelEditor.component.html",
        "start": { "line": "70", "column": "25" },
        "end": { "line": "70", "column": "38" }
      }
    ]
  },
```

Why not to use [Customized Attribute]( https://github.com/google/app-resource-bundle/wiki/ApplicationResourceBundleSpecification#customized-attributes) on ARB format (as ready did with x-location) and add an `x-meaning` property?

For example:

```
"71788121164220023": "no tags found",
  "@71788121164220023": {
    "description": "No tags found placeholder",
    "x-meaning": "My meaning",
    "x-locations": [
      {
        "file": "projects\\xxxxx\\hardware-editors\\src\\lib\\elements\\channelEditor.component.html",
        "start": { "line": "70", "column": "25" },
        "end": { "line": "70", "column": "38" }
      }
    ]
  },
```

**Comment by petebacondarwin** [comment]
That is a reasonable request. Would you be interested in providing a PR to add this?

**Comment by meriturva** [comment]
So thanks @petebacondarwin for that opportunity! We use now the meaning to split translations and place them in the correct library resource folder (we are also waiting for new APF format based on Ivy). Due to the missing meaning information on ARB format, we are testing now to run extraction tool on all single library and see performance on CI.

So if we really need x-meaning property I guess we could arrange a PR.
Keep in touch and thanks again!

**Comment by meriturva** [comment]
So thanks @crisbeto !
