### ISSUE TITLE
HttpClient *sometimes* sends invalid HTTP requests after updating from Angular 10 to Angular 11

### ISSUE THREAD

**Issue by mrctrifork** [angular/angular#40508]
# 🐞 bug report

### Affected Package

I would say it's part of the @angular/common package

### Is this a regression?

I don't think it is 🤷 

### Description

Sometimes performing an HTTP request with the client results in a buggy HTTP request.

Example of the buggy request:

![imagen](https://user-images.githubusercontent.com/45353144/105360199-a1d46380-5bf8-11eb-85f4-f58f56b89463.png)

As you can see on the first header we should have  {HTTP_VERB} {LOCATOR} {HTTP_VERSION} but seems that the HTTP_VERSION got lost somewhere in the javascript. This issue was not occurring in Angular 10.

![imagen](https://user-images.githubusercontent.com/45353144/105360393-d21c0200-5bf8-11eb-810a-50728166fcf8.png)

^^^ Here's an example of a valid HTTP request. Note the presence of the HTTP version

## 🔬 Minimal Reproduction

I've just performed a GET request to our backend. I'll try to create an example I can share here

## 🔥 Exception or Error
Backend doesn't answer back or answers with a 400: Bad Request

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.1.0
Node: 14.15.0
OS: darwin x64

Angular: 11.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.0
@angular-devkit/build-angular   0.1101.0
@angular-devkit/core            11.1.0
@angular-devkit/schematics      11.1.0
@schematics/angular             11.1.0
@schematics/update              0.1101.0
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**
I don't think so. let me know if you'd like to get more info

**Comment by petebacondarwin** [comment]
The Angular code is not responsible for setting this HTTP protocol version. In fact I can't find anywhere that documents how it could even be done via the `XmlHttpRequest` API that `HttpClient` uses.

I wonder if in the cases where it does happen the browser has a some plugin installed that is intercepting the request?
I notice that the failing example you give is being triggered from `localhost`. Can you confirm that you can reproduce this locally?

To be able to investigate, we would need a reproduction to debug.

**Comment by mrctrifork** [comment]
I have some plugins installed, I'll do more tests around it and I'll let you know

**Comment by mrctrifork** [comment]
The problem was the openapi-generator-cli generated code. Switched to another version and worked.

**Comment by petebacondarwin** [comment]
Glad you got to the bottom of it!
