### ISSUE TITLE
Support preloading of templates, at least for testing

### ISSUE THREAD

**Issue by wardbell** [angular/angular#4051]
As it stands (alpha-36) one cannot write unit tests of the actual template when the template is supplied via `templateUrl`.

I can't even fake it if component A's template (even a template override) depends on component B which gets its template via `templateUrl`.   I have been unsuccessful using `overrideDirective` to mock the dependent component B ... not that I should have to bother.

Could we use something like the Ng1 template-cache?

**Comment by kara** [comment]
I think there is a related discussion here: 
https://github.com/angular/angular/issues/1610

**Comment by wardbell** [comment]
Yes, there it is! 

I looked for that issue specifically before adding this on.  But I looked for it only among the open issues. That issue is **closed** although the problem seems yet to be solved.  What am I missing?

**Comment by kara** [comment]
I think it was closed because there is an npm plugin now that should help:
https://www.npmjs.com/package/karma-redirect-preprocessor

And looks like in the angular2 project,  #3605 might address this?

**Comment by juliemr** [comment]
Some updates here - we have tests verifying that you can use templateUrl: https://github.com/angular/angular/blob/master/modules/angular2/test/testing/testing_public_spec.ts#L472 and https://github.com/angular/angular/blob/master/modules_dart/angular2_testing/test/angular2_testing_test.dart#L89

This will not work for `fakeAsync` tests. We should definitely have a way to preload templates with Karma - for speed, and for completely synchronous tests.

**Comment by rogerpadilla** [comment]
Or alternatively just use the "proxies" functionality which Karma has built-in, for redirecting template requests to the original ones, [like this](https://github.com/rogerpadilla/angular2-minimalist-starter/blob/master/karma.conf.js):

```
// list of files / patterns to load in the browser
files: [
  ...
  { pattern: 'client/**/*.html', included: false, watched: true, served: true },
  'test-main.js'
],

proxies: {
  '/base/tmp/test/': '/base/client/'
},
```

**Comment by wardbell** [comment]
@rogerpadilla Will karma proxies work for synchronous tests?

**Comment by rogerpadilla** [comment]
@wardbell I'm not sure.

**Comment by juliemr** [comment]
Done.

**Comment by vsakaria** [comment]
Why is it marked as done? The two links by Juilemr are 404s
