### ISSUE TITLE
Get an error after updateting zone.js from 0.11.1 to 0.11.2

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular#40518]
# 🐞 bug report

### Affected Package

 The issue is caused by package zone.js

### Is this a regression?

 Yes, the previous version I didn't get the error

### Description

 
I use devextreme-angular package. After updating zone.js I see the error in devextreme-angular
I tried to understand why but didn't find the cause of the error.
Also, I read the changelog of zone.js I didn't fond BC connected with my problem

## 🔬 Minimal Reproduction

 
Try to drag a row in the Datagrid ([an example to reproduce](https://codesandbox.io/s/local-reordering-devextreme-data-grid-forked-j5yzf?file=/src/polyfills.ts))

## 🔥 Exception or Error
<pre><code>
TypeError
Cannot use 'in' operator to search for 'id' in null

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by JiaLiPassion** [comment]
@dxvladislavvolkov, could you provide a repo instead of a codesandbox, so I can debug easier, thanks.
