### ISSUE TITLE
is not a known element

### ISSUE THREAD

**Issue by denversaka** [angular/angular#40537]
### Description
I imported the module containing the component and I get: "is not a known element"

```
/pages
    /partials
        /header
        /footer
        partials.module
   /page1
   ...
   pages.module
app.module
```
## 🔬 Minimal Reproduction

partials.module
```ts
  declarations: [HeaderComponent,
  exports: [HeaderComponent,
```

pages.module
```ts
  imports: [ PartialsModule,
```

app.module
```ts
  imports: [ pages.module,
```
app.component.html
```html
<app-header></app-header>            <======   is not a known element
<router-outlet></router-outlet>
```
## 🔥 Exception or Error
is not a known element

## secondary solution

app.module
```ts
  imports: [ 
    pages.module,        // duplicate partials
    partials.module,     // duplicate partials
```

## 🌍  Your Environment

Angular 11

**Comment by jnizet** [comment]
That's expected since your pages module does not export the partials module

**Comment by denversaka** [comment]
indeed, thank you
