### ISSUE TITLE
setControl in reactive forms does not bind disabled status to controls in html

### ISSUE THREAD

**Issue by SunilManthenaG01** [angular/angular#40530]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

 No

### Description

when using setControl and trying to reinitialize the form( when the status of the form is disabled), the disabled property of the form group is changed but the input control does not reflect the changed status.

## 🔬 Minimal Reproduction

1. type anything into the input field and click disabled.
2. And then click reinitialize.
3. We see the output of form enabled as true but the input element does not change.

https://stackblitz.com/edit/angular-ivy-s9xwzf?file=src%2Fapp%2Fapp.component.html

## 🔥 Exception or Error
<pre><code>

NONE
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

11.0.8

</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment]
@SunilManthenaG01 thanks for reporting the issue. It looks like the underlying issue is the same as the one described in #35309, so I'm closing this ticket in favor of #35309. Please subscribe to #35309 to get further updates. Thank you.
