### ISSUE TITLE
The canDeactivate guard is called with a null component 

### ISSUE THREAD

**Issue by rchod** [angular/angular#40545]
# 🐞 bug report

### Is this a regression?
Yes

### Description

The canDeactivate guard is called with a null component

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/injected-component-in-the-candeactivate-guard-is-null?file=src%2Fapp%2Fapp.module.ts

</code></pre>

## 🌍  Your Environment

**Angular Version:**
11.0.8 (but not specific to this version, I can reproduce it in other versions)

</code></pre>

**Comment by jaradehr1** [comment]
> # 🐞 bug report
> ### Is this a regression?
> Yes
> 
> ### Description
> The injected component in the canDeactivate guard is null
> 
> ## 🔬 Minimal Reproduction
> https://stackblitz.com/edit/injected-component-in-the-candeactivate-guard-is-null?file=src%2Fapp%2Fapp.module.ts
> 
> ## 🌍 Your Environment
> **Angular Version:**
> 11.0.8

I just bumped into the same issue today
https://stackoverflow.com/questions/65865384/why-i-cannot-access-my-component-within-my-deactivate-guard-in-angular-11?noredirect=1#comment116455148_65865384

**Comment by iftee-hussain** [comment]
It seems for component-less routes (without `router-outlet`), the `CanDeactivate` guard is initialized with `null` component.
If you add   `router-outlet`, the `CanDeactivate` guard will be  initialized with the component from the current route context
Have a look at this
https://stackblitz.com/edit/injected-component-in-the-candeactivate-guard-is-null-fq6u6x

**Comment by jaradehr1** [comment]
> It seems for component-less routes (without `router-outlet`), the `CanDeactivate` guard is initialized with `null` component.
> If you add `router-outlet`, the `CanDeactivate` guard will be initialized with the component from the current route context
> Have a look at this
> https://stackblitz.com/edit/injected-component-in-the-candeactivate-guard-is-null-fq6u6x

Cool, thanks a lot! I was just injecting the child component into the parent component and not using the **<router-outlet>**. This also explains why my resolvers won't get triggered on the child level but only the parent level.

**Comment by atscott** [comment]
Closing as working as expected. There's no `router-outlet` in the application so there is also no activated component. In this case `null` makes sense. We tried introducing a warning message for this case, but it's a very common scenario in tests, see https://github.com/angular/angular/issues/38804#issuecomment-694997458.
