### ISSUE TITLE
Casting in template expressions

### ISSUE THREAD

**Issue by henrikdahl8240** [angular/angular#40549]
Let's assume, that I have a usual case, an abstract class `Employee` having two concrete sub classes `Manager` and `Staff`.

Let's assume, that a Manager has a company car.

In a template expression, can I cast an Employee reference to e.g. a Manager, if I from the context know, that the Employee is actually a Manager?

I think of something like:
`<car-details [car]="(someEmployee as Manager).companyCar"></car-details>`
or:
`<car-details [car]="(<Manager> someEmployee).companyCar"></car-details>`

or am I limited to only being able to opt out of type checking using $any() like:
`<car-details [car]="$any(someEmployee).companyCar"></car-details>`

At least it doesn't work as expected, as I try to use such casting. Is it an error in Angular 11.0.9 or casting should not work? I guess it's difficult with FullTemplateCheck if casting is not supported.

**Comment by petebacondarwin** [comment]
Angular templates do not support casting.

Really the question is "how do you know it is a Manger?" Good use of type guard functions should avoid having to do dynamic casting like this. Here is an example of how this can be done: https://stackblitz.com/edit/angular-ivy-ny46sh?file=src%2Fapp%2Fapp.component.html

Closing as this is either a feature request for downcasting in templates, which will not be supported, or support request for how to handle subclasses in templates, for which there is an example above.

**Comment by henrikdahl8240** [comment]
@petebacondarwin  Thank you for the extensive example at Stackblitz.

In your example, why doesn't `{{ employee.companyCar}}` result in an error when building, that `companyCar` is not a property of `Employee`?

Does the type-checker know it due to the return type of `isManager`, i.e.:
```
  isManager(employee: Employee): employee is Manager {
    return employee instanceof Manager;
  }

```

Could you perhaps share a link for documentation, that you may have such return types and that they have this implication concerning type-checking, because this I have never seen before, please?
