### ISSUE TITLE
fix(router): wildcard routes with redirects

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#4055]
As of alpha 36 there is no `otherwise` route condition. The use case is where you want an invalid route or set of routes to either go to specific route or run a function that can do custom logic and re-route.

As another option for simple redirection, I would expect this to work, but it does not

```
@RouteConfig([
  { path: '/*', redirectTo: ROUTES.heroes }, //TODO: Need an otherwise in some way
  { path: ROUTES.about, as: 'about', component: AboutComponent },
  { path: ROUTES.heroes, as: 'heroes', component: HeroesComponent },
  { path: ROUTES.detail + '/:id', as: 'detail', component: HeroDetailComponent }
])
```

I'm requesting both an `otherwise` and the * pattern above to work.

cc // @btford

**Comment by johnpapa** [comment]
See this app for details https://github.com/johnpapa/angular2in22-docs

**Comment by btford** [comment]
@johnpapa this is sort of a dup of #2965.

I'm going to amend your original post to better reflect your original issue (wildcard + redirect does not work).

**Comment by johnpapa** [comment]
adjustments look good. thank you Brian

**Comment by itslenny** [comment]
I spent some time digging in to this and I noticed that the redirect RegExp for the wild cards requires a name (like params). This *might* make sense as a way to get the data in the wildcard. For the original example the path would have to be something like `/*foo` to actually work. a plan `/*` is NOT recognized as a wild card and will actually literally define a route `/*`.

Is there a reason for this? Should wild cards be changed to just `*` or perhaps `*` with optional extra characters. 

Current RegExp:
```
var wildcardMatcher = /^\*([^\/]+)$/g;
```
(https://github.com/angular/angular/blob/master/modules/angular2/src/router/path_recognizer.ts#L91)

**Comment by btford** [comment]
@itslenny you're completely right.

I think a good behavior would be to recognize this and provide some default name for the param (like `wildcard`, for instance).

**Comment by gmfun** [comment]
I have notices
```
@RouteConfig([
  { path: '/**', redirectTo: ROUTES.heroes }, //TODO: Need an otherwise in some way
  { path: ROUTES.about, as: 'about', component: AboutComponent },
  { path: ROUTES.heroes, as: 'heroes', component: HeroesComponent },
  { path: ROUTES.detail + '/:id', as: 'detail', component: HeroDetailComponent }
])
```
this works

**Comment by aburakab** [comment]
For the time being i did this hack :)

`
import { AppRoutes } from './_Models/ModuleRoutes';
@Routes(AppRoutes)
export class EvAppComponent implements OnInit {

    constructor(private _router: Router) { }

    ngOnInit() {

        var validRoute = false;
        for (let i = 0, len = AppRoutes.length; i < len; i++) {
            let route = AppRoutes[i];
            let urlTree = this._router.createUrlTree([route]);
            validRoute = this._router.urlTree.contains(urlTree);
            if (validRoute)
                continue;
        }
        if (!validRoute) {
            this._router.navigateByUrl('/inboxes');
        }
    }
}`

`import { RouteMetadata } from '@angular/router/src/metadata/metadata';
export var AppRoutes: RouteMetadata[] = [
    { path: '/inboxes', component: InboxesCmp },
    { path: '/deliveryReports', component: DeliveryReportCmp },
    { path: '/reports', component: DeliveryReportCmp },
    { path: '/search', component: SearchCmp },
];`

**Comment by IgorMinar** [comment]
this is already handled by router v3

**Comment by jakegraves** [comment]
IgorMinar - I keep trying to find documentation on how router v3 handles it or how to get it to handle it and I can't and it doesn't seem to. All google searches lead me here or to the Angular RC3 documentation which says nothing about v3 routing wildcards or defaults. Here's what I've been doing so far to overcome this: 
app.routes.ts:
```
export const routes: RouterConfig = [
    ...SomeRoutes,
    ...OtherRoutes,
    {
        path: "",
        component: HomeComponent,
        terminal: true,
        canActivate: [AuthenticationProvider]
    }
];
```
AppComponent:
```
public ngOnInit() {
        this.router.events.subscribe((event) => {
            if (event instanceof NavigationEnd) {
                var navigationEnd = event as NavigationEnd;
                if (navigationEnd.urlAfterRedirects.indexOf("?AccessToken")) {
                    var baseHref = window.location.href.split("?")[0];
                    window.history.replaceState({}, "Site Title", baseHref);
                }
            }
            if (event instanceof NavigationError) {
                this.router.navigateByUrl("/");
            }
        });
  }
```

If you could point me in the right direction, I'd be grateful instead of pounding my head painfully on my shiny desk.

**Comment by ericmartinezr** [comment]
@jakegraves

```
{path : '**', component : SomeComponent} // or redirectTo : '/404'
```
Sorry, from top of my head, don't remember exactly.  You can come to gitter to ask https://gitter.im/angular/angular you'll find someone who knows

**Comment by slayerfat** [comment]
The router documentation and the [cheat sheet](https://angular.io/docs/ts/latest/cheatsheet.html) IMHO should say something about @ericmartinezr solution
