### ISSUE TITLE
docs: Missing code sample in Basics of testing components

### ISSUE THREAD

**Issue by saifabusaleh** [angular/angular#40558]
# 📚 Docs or angular.io bug report

### Description

Go to: https://angular.io/guide/testing-components-basics
Go to By.css() section
You will see: `The code sample is missing for testing/src/app/banner/banner-initial.component.spec.ts#import-by`

### What's the affected URL?**
https://angular.io/guide/testing-components-basics

## 📷Screenshot

![image](https://user-images.githubusercontent.com/15147809/105738961-44198180-5f40-11eb-921a-2aa104df0ac7.png)

**Comment by iftee-hussain** [comment]
Hi, If the issue is available I would like to take this

**Comment by petebacondarwin** [comment]
Go for it. The problem is that the `docregion` here is empty - https://github.com/angular/angular/blob/4a9f7daf37102a808534372f01bb935a38dd1e18/aio/content/examples/testing/src/app/banner/banner-initial.component.spec.ts#L2-L3

**Comment by iftee-hussain** [comment]
@petebacondarwin Thanks. I have created a PR https://github.com/angular/angular/pull/40565 :)
