### ISSUE TITLE
[Feature Request] Form validation should be better

### ISSUE THREAD

**Issue by HosMercury** [angular/angular#40552]
As for Laravel , form validation should supply a default message ..
I would suggest errors object just has a default  validation  message ... 

          fieldErrorsObject : {
             validationMsg: 'this is required'
          }

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand this feature request, so I'm closing this ticket. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) which describes why we can't act on issues that are lacking important information.

Feel free to create a new one if your feature request belongs to Angular framework and once there is more info available.
