### ISSUE TITLE
App Shell stops building when using a timer in an NgRx effect

### ISSUE THREAD

**Issue by hadrien-toma** [angular/angular#40564]
# 🐞 bug report

### Affected Package

I think the issue is caused by package @angular/pwa.

### Is this a regression?

I don't think it is a regression.

### Description

App shell stops building successfully as soon as using an RxJS `timer` in an NgRx effect.

### Use a working state as base

```
git clone https://gitlab.com/hadrien-toma/issue
cd issue/workspace
yarn install
yarn run nx run frontend:app-shell:production
```

### Introduce the bug

- Uncomment line 24 in `workspace/apps/frontend/src/app/effects/index.effects.ts` in order to have this stream:

```
	µStartLooping__µLoop$ = createEffect(
		() =>
			combineLatest([this.actions$.pipe(ofType(µStartLooping))]).pipe(
				withLatestFrom(this.store.pipe(select($looperDueTime)), this.store.pipe(select($looperPeriod))),
				exhaustMap(([_, looperDueTime, looperPeriod]) => timer(looperDueTime, looperPeriod)),
				mapTo(µLoop())
			),
		{ dispatch: true }
	);
```

Now running `yarn run nx run frontend:app-shell:production` never ends, without errors.

## 🔥 Exception or Error

No error but never ends.

## 🌍  Your Environment

**Dependencies:**
<pre><code>
    "@angular/animations": "^11.0.0",
    "@angular/common": "^11.0.0",
    "@angular/compiler": "^11.0.0",
    "@angular/core": "^11.0.0",
    "@angular/forms": "^11.0.0",
    "@angular/platform-browser": "^11.0.0",
    "@angular/platform-browser-dynamic": "^11.0.0",
    "@angular/platform-server": "^11.0.0",
    "@angular/router": "^11.0.0",
    "@ngrx/effects": "^10.1.2",
    "@ngrx/router-store": "^10.1.2",
    "@ngrx/store": "^10.1.2",
    "@nrwl/angular": "^11.1.5",
    "immer": "^8.0.1",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "^0.10.2"
</code></pre>

**Comment by jessicajaniuk** [comment]
Thanks for reporting this. Do you know if this issue occurs with an app created by the Angular CLI without using nx tools? If so, can you provide a reproduction of that? Also can you do that with the `11.1.0` latest version? Thanks!

**Comment by alan-agius4** [comment]
This is expected. 

There is a good explanation in the below to why this happen.

https://github.com/angular/universal/blob/master/docs/gotchas.md#application-is-slow-or-worse-wont-render

**Comment by hadrien-toma** [comment]
Thank you both for your answers, after reading the link of @alan-agius4 I confirm this is expected (by Angular Universal, this is not linked to Nx).
Unfortunately I didn't find a documentation explaining how to solve this simple use case where the App needs to repeatidly do some thing. Does it mean I have to abandon the idea of generating the App Shell?

**Comment by alan-agius4** [comment]
No absolutely not, It just means that you want to go for a different approach. Such as you cannot use `timers` among other RxJs functionality when using App-Shell and/or Universal. 

The app-shell is a static view that is generated at build time, hence there is no reason why the application needs to perform such polling operations when it's running on the server during build time. This operations only makes sense when it is run in the browser.

To achieve this you have 2 main options.
- Use `isPlatformServer`  https://angular.io/api/common/isPlatformServer and only run the polling when it's `false`.
- Have different Effects based on the platform. You can use `USER_PROVIDED_EFFECTS` token for this NGRX

Some resources:
https://ngrx.io/guide/effects#alternative-way-of-registering-effects 
https://medium.com/@caerus.karu/isplatformbrowser-is-not-your-friend-5ee52b06da89

**Comment by hadrien-toma** [comment]
Very nice information and resources here! This is perfectly clear, thank you very much!

**Comment by hadrien-toma** [comment]
I updated the repository with the following effect, like that, the app shell successfully ends :yum: :

```typescript
	µStartLooping__µLoop$ = createEffect(
		() =>
			combineLatest([this.actions$.pipe(ofType(µStartLooping))]).pipe(
				exhaustMap((actionArray) => of(actionArray).pipe(
				  withLatestFrom(this.store.pipe(select($looperDueTime)), this.store.pipe(select($looperPeriod)))
				)),
				filter(() => !isPlatformServer(this.platform)),
				exhaustMap(([_, looperDueTime, looperPeriod]) => timer(looperDueTime, looperPeriod)),
				mapTo(µLoop())
			),
		{ dispatch: true }
	);
```
