### ISSUE TITLE
Angular 11: Module parse failed: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ezforw** [angular/angular#40567]
Facing the same problem as stated in https://github.com/auth0/auth0-angular/issues/54, I'm creating this issue here, as it seems related to Angular rather than the Auth0 side.

This is happening when I was trying to upgrade Angular from v10 to v11, and this did not happen on v10.

If I remove `"webWorkerTsConfig": "tsconfig.worker.json"` from `angular.json`, then the error was gone.

**Comment by petebacondarwin** [comment]
Is the reproduction at https://github.com/cenguidanos/angular-test-auth0-log still valid for this issue?
