### ISSUE TITLE
support json as i18n language file 

### ISSUE THREAD

**Issue by calidion** [angular/angular#40569]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/localize

### Description
 
JSON file is simpler than xml.

### Describe the solution you'd like
 
reference https://github.com/ngx-translate/core

### Describe alternatives you've considered
 
reference
https://github.com/ngx-translate/core

**Comment by petebacondarwin** [comment]
We already support two JSON formats. 

* A simple format (which I believe is equivalent to what you link to in ngx-translate): see [parser](https://github.com/angular/angular/blob/master/packages/localize/src/tools/src/translate/translation_files/translation_parsers/simple_json_translation_parser.ts) and [serializer](https://github.com/angular/angular/blob/master/packages/localize/src/tools/src/extract/translation_files/json_translation_serializer.ts).
* A semi-standard ARB format: see [parser](https://github.com/angular/angular/blob/master/packages/localize/src/tools/src/translate/translation_files/translation_parsers/arb_translation_parser.ts) and [serializer](https://github.com/angular/angular/blob/master/packages/localize/src/tools/src/extract/translation_files/arb_translation_serializer.ts).

Both these formats are already supported in the CLI. See `--format` in https://angular.io/cli/extract-i18n.
