### ISSUE TITLE
[BUG]: "export 'ɵɵstaticViewQuery' was not found in '@angular/core' and ASSERTION ERROR: Expecting flags [Expected=> number === boolean <=Actual]

### ISSUE THREAD

**Issue by splincode** [angular/angular#40574]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core

### Is this a regression?

Yes

### Description

After upgrade to Angular 11.1.0 I have problem with build in my local PC

```
Error: ./node_modules/@angular-ru/ng-table-builder/fesm2015/angular-ru-ng-table-builder.js 2392:8-25
"export 'ɵɵstaticViewQuery' was not found in '@angular/core'
```

But if I have stackblitz example:
https://stackblitz.com/edit/ng-table-builder-failed?file=src/app/app.component.html

![image](https://user-images.githubusercontent.com/12021443/105845740-4e915500-5fec-11eb-882c-2e54a5edc510.png)

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/ng-table-builder-failed

## 🔥 Exception or Error
<pre><code>
preview-fef3604083950c709c52b.js:1 Error: ASSERTION ERROR: Expecting flags [Expected=> number === boolean <=Actual]
    at throwError (core.umd.js? [sm]:213)
    at assertNumber (core.umd.js? [sm]:144)
    at Object.ɵɵcontentQuery (core.umd.js? [sm]:27212)
    at Object.AbstractTableBuilderApiImpl_ContentQueries [as contentQueries] (table-builder.api.ts:59)
    at executeContentQueries (core.umd.js? [sm]:10001)
    at ɵɵelementStart (core.umd.js? [sm]:15281)
    at Object.ɵɵelement (core.umd.js? [sm]:15331)
    at AppComponent_Template (app.component.html:1)
    at executeTemplate (core.umd.js? [sm]:9985)
    at renderView (core.umd.js? [sm]:9792)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular: latest
@angular-ru/ng-table-builder: 15.78.1
</code></pre>

**Comment by JoostK** [comment]
Are you consuming prebuilt Ivy libraries, perhaps? The instructions have changed a bit such that precompiled libraries are now referring to non-existent instructions.

**Comment by alan-agius4** [comment]
It does appear that this mentioned package is indeed being published using Ivy.

https://unpkg.com/browse/@angular-ru/ng-table-builder@15.78.2/

Kindly open an issue in the mentioned library issue tracker and mentioned that libraries should published using View Engine.

**Comment by crh225** [comment]
@alan-agius4 on the roadmap for angular it says they are supporting ivy compiled libraries: https://angular.io/guide/roadmap. Shouldn't we be able to publish internal libraries not on npm to be consumed with our own ivy angular application?

**Comment by petebacondarwin** [comment]
Note that the item in the road map is "in progress" which means it is not yet ready.
We are working on a distributable format for libraries that is ivy compiled but we have not solidified that yet.
In the meantime the message is to build and publish your libraries using the ViewEngine compiler, not ivy.

**Comment by petebacondarwin** [comment]
Regarding internal libraries, it is fine to use Ivy internally, as long as you re-compile and re-publish your libraries to have the same Angular version as the consuming application projects.
