### ISSUE TITLE
Static option for ngTemplateOutlet

### ISSUE THREAD

**Issue by mixalistzikas** [angular/angular#40570]
Right now we have the option to set static: true when we set a @ViewChild

    @ViewChild("target", { read: ViewContainerRef, static: true }) target: ViewContainerRef;

But we don't have this option if we use *ngTemplateOutlet

    <ng-container *ngTemplateOutlet="myService.element$ | async"> </ng-container>

Am I understanding something wrong? The problem is the first cycle of the ElementRef I'm passing (with the async observable)

So, I want to find a solution to set the outlet (elementRef) before the change detection cycle

**Comment by petebacondarwin** [comment]
This issue could do with a more explicit reproduction of the problem. Can you describe more explicitly what you see happening and what you expect to happen?

Are you saying that there is a round of change detection where the result of the `async` pipe is `null`?

Given that observables can be async in nature, I don't see how you could expect the change detection to wait for this observable to emit.

Depending upon my understanding of this I think you might be able to achieve what you want (I'm guessing) by wrapping your `ngTemplateOutput` in an `ngIf`?

```html
<ng-container *ngIf="(mySevice.element$ | async) as element">
  <ng-container *ngTemplateOutlet="element"></ng-container>
</ng-container>
```

**Comment by alxhub** [comment]
Closing due to no response.
