### ISSUE TITLE
Slow incremental rebuild

### ISSUE THREAD

**Issue by piernik** [angular/angular#40573]
# 🚀 Feature request

Option to turn off tree shaking (which is suppose to be slow).

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
I have quite big `angular@11` project. App folder has 4MB within 2100 files. I know it is big. Initial compilation takes over 130 seconds. My command is `node --max_old_space_size=10000 ./node_modules/@angular/cli/bin/ng serve` so I'm giving node extra memory.

Problem is with recompilation. I've made an isolated lazy loaded module:
```
{
    path: 'dev',
    loadChildren: () => import('@dev/dev-pages/dev-pages.module').then(m => m.DevPagesModule)
  },
```

In that module I have only one, auto generated page component:

```
<p>page-dev-test works!</p>
```

If I add any string to template it takes almost 20 seconds to recompile (file is only 7kB) :/ Is it normal? Can I speed this up?

<img width="456" alt="ng" src="https://user-images.githubusercontent.com/420691/105702837-a789bc00-5f0c-11eb-9d18-9f075650ff2d.png">

### Describe the solution you'd like
One of stackoverflowers (https://stackoverflow.com/a/65882673/979911) suggested that tree shaking is very have process which takes lot of time. How about turning it off in development?

**Comment by JoostK** [comment]
Hi @piernik, do you think it's possible to share your repo privately with me? I have been working on several performance optimizations over te past couple months and I have an idea of why the incremental rebuild is so costly, but would like to confirm for your case.

**Comment by piernik** [comment]
@JoostK I can do that. Give me Your email or something

**Comment by JoostK** [comment]
> @JoostK I can do that. Give me Your email or something

<summary>That would be
<details>joost.koehoorn and then gmail dot com</details>
</summary>

**Comment by piernik** [comment]
Sent it. You can delete Your email. Thanks for help.

**Comment by JoostK** [comment]
@piernik Got it, thanks. I'll have a look in the coming days.

**Comment by sod** [comment]
As you use sass you maybe have a similar issue. We used to import bootstrap mixins in every component out of convenience. But dart-sass has no intelligent caching for this in place so it parsed through a giant tree of sass files to collect all the mixins repeatedly which added 500ms for every component.

**Comment by piernik** [comment]
@sod No I have all styles in dedicated theme files. Don't use styles in components (sometimes but very simple).

**Comment by sod** [comment]
If you want to profile the build yourself you can do
`node --inspect --max_old_space_size=10000 ./node_modules/.bin/ng serve`

then open the chrome dev tools and click the node icon
![image](https://user-images.githubusercontent.com/905328/105985161-683da580-609b-11eb-867f-ad16eb2715c7.png)

Then wait. This could take a while until it's done as with a debugger attached the process is ~1.2x to 3x slower. Don't even try to profile the build start as a 130s build may just crash the debugger.

But if the build completed, then click start in the profile tab
![image](https://user-images.githubusercontent.com/905328/105985496-d1bdb400-609b-11eb-8c2a-62cf1a979d36.png)

then change a file and wait until the incremental build completed. Then press stop and look at the flamechart.

![image](https://user-images.githubusercontent.com/905328/105985836-53addd00-609c-11eb-9424-ec1b4ac855de.png)

Sometimes you spot the issue right away. Or you can dig deeper from there. E.g. if you see a similar pattern repeated over and over again you can add a logpoint or debugger statement there and see what the build is doing there.

**Comment by JoostK** [comment]
Thanks @sod, that's super helpful.

In fact it's what I have done using the reproduction and there's a couple things to share here:

the `ngc` incremental build took 17s, most of which was type-checking. `ngc` doesn't do incremental type-checking so each rebuild incurs the full cost. The Angular compiler was actually not adding much overhead here.

The CLI does have incremental type checking in rebuilds (since 11.1, coincidentally) and it's a lot better in that case. Unfortunately, the CLI adds Webpack bundling, circular dependencies checks and bundle source-maps. Those steps add quite a bit of overhead.

Disabling source maps and the circular dependency check improves the times quite a bit. This can be done by extending the build configuration in `angular.json` using the following two flags:

```json
            "showCircularDependencies": false,
            "sourceMap": false,
```

I can't say whether it's acceptable for these features to be disabled; for the circular dependencies plugin I'd suggest to have it at least enabled for `prod` builds; or perhaps introduce a dedicated "fast" configuration with those options configured.

Even with those flags, the rebuild is still ~10s. Most time (~80%) is spent in Webpack chunk plugins; that looks rather inefficient but I haven't yet determined what could be done here.

**Comment by sod** [comment]
for dev mode we use these webpack chunk options:
```javascript
            splitChunks: {
                cacheGroups: {
                    // disable the two default cache groups
                    default: false,
                    vendors: false,

                    // pull all node_modules from main.js into vendor.js
                    mainVendors: {
                        name: 'vendor',
                        test: /[\\/]node_modules[\\/]/,
                        priority: -10,
                        chunks: (chunk) => chunk.name === 'main',
                    },
                },
            },
```

With the `chunk.name` condition to compare against your entry chunk. This leaves webpack to do no optimizations at all and is quite fast. Just pulling out the vendors into a separate file. Don't know how to apply those rules to angular/cli though, we use webpack directly.

**Comment by alan-agius4** [comment]
That can be done using the `—vendor-chunk ` option.

See: https://angular.io/cli/build

**Comment by JoostK** [comment]
With the help of @alan-agius4 I got to a point where the rebuild is only ~3seconds; we needed to set `"extractLicenses": false` to disable license extraction. We are yet to figure out why that would have been enabled, as it should be disabled by default.

**Comment by alan-agius4** [comment]
It appears to be a bug in previous versions of `ngx-build-plus`. where it was enabled by default https://github.com/manfredsteyer/ngx-build-plus/blob/8e58880a279d329934a1c7e556b9cac6523ea284/lib/src/browser/schema.json#L246

License extraction is not intended to be used for incremental builds. Following the above, it appears that there is no action needed from the Angular team. 

Thanks everyone for chiming in.

**Comment by piernik** [comment]
Thanks for help. I updated `ngx-build-plus` and it is faster - 10 seconds. Not as fast as Your 3 sec, but maybe it is hardware issues.

BTW. Is `ngx-build-plus` still needed? I'm using it only to get rid of additional locales from `moment js`?

**Comment by JoostK** [comment]
The 3s require that you also set the flags as mentioned in https://github.com/angular/angular/issues/40573#issuecomment-768233599. It could indeed be that your milage may vary depending on hardware.

**Comment by sod** [comment]
You could try switching from moment.js to https://github.com/iamkun/dayjs - it has a similar api (it's kinda meant as a replacement for moment.js) and you don't need webpack tricks to get it small.

**Comment by piernik** [comment]
@JoostK Where should I paste these flags? I'm putting it into and I cannot see deference in time with or without them ~10sec. 
```
"projects": {
  "frontend": {
    "architect": {
      "serve": {
        "configurations": {
          "production": {
              "browserTarget": "frontend:build:production",
              "showCircularDependencies": false,
              "sourceMap": false
            }
}}}}}
```

BTW:  In docs there is no info about `angular.json` file (or maybe there is? I'm using search bar).

**Comment by sergidt** [comment]
Hi,

I am having same problem. I have a huge project and recompiling with angular 9 was around 5-10 seconds, now, the recompilation time is, minimum 50 seconds.

Not acceptable, of course.

**Comment by piernik** [comment]
@sergidt I have much better times. 
set flag `"showCircularDependencies": false,` in `angular.json` `architect, build, options` key.

**Comment by sergidt** [comment]
@piernik yes but enough to reduce this increment?

In my case any change is taking 60 seconds.

Thanks any way, I will check it
