### ISSUE TITLE
Can't use large RegExp as pattern validator

### ISSUE THREAD

**Issue by ocket8888** [angular/angular#40589]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/forms

### Is this a regression?
Not as far as I know. Tested on angular 8 and 10, both have the issue.

Unless you count it working in AngularJS with `ng-pattern` as being a regression - I've used these exact same RegExp objects (constructed literally just like in the linked example) with no problems in AngularJS.

### Description
Large RegExp objects (I think large ones, because I've seen smaller used with no issue) throw errors in the console when you try to bind them to `pattern`. I know these regular expressions are actually fine, because they compile and I can use them to test strings and they appear to pass/fail as expected.

## 🔬 Minimal Reproduction
https://plnkr.co/edit/5N7CZU6K60xFjXH5

## 🔥 Exception or Error
<pre><code>

Unable to check <input pattern='/^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\:){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$|^\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?(\/(12[0-8]|1[0-1][0-9]|[0-9][0-9]?))?$|^((25[0-5]|2[0-4][0-9]|[0-1]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[0-1]?[0-9][0-9]?)(\/(3[0-2]|[0-2]?[0-9]))?$/'> because the pattern is not a valid regexp: invalid identity escape in regular expression

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.2.1
Node: 15.7.0
OS: linux x64

Angular: 10.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.1
@angular-devkit/build-angular   0.1002.1
@angular-devkit/core            10.2.0
@angular-devkit/schematics      10.2.1
@angular/cli                    10.2.1
@nguniversal/builders           10.1.0
@nguniversal/express-engine     10.1.0
@schematics/angular             10.2.1
@schematics/update              0.1002.1
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

... but the issue also occurs in that plunk I linked, which is using Angular 8

**Anything else relevant?**
Looks like it's possibly specific to Firefox - I'm using version 84.0.2 (64-bit)

**Comment by petebacondarwin** [comment]
I can confirm that this appears to error only on Firefox - I tested it on 85.0 (64-bit).
But interestingly I cannot get the FF debugger to stop on the error being thrown, nor does it appear to throw an error if I step through the code one line at time.

I suspect that this is just a bug in FF... I'll see if I can reproduce without Angular.

**Comment by petebacondarwin** [comment]
What I can see is that (apart from this console log) the application appears to run as expected...
So I think that Angular is not at fault here.

**Comment by petebacondarwin** [comment]
Ahah! The error appears to be that FireFox attempts to do the pattern validation natively. See https://stackoverflow.com/questions/36953775/firefox-error-unable-to-check-input-because-the-pattern-is-not-a-valid-regexp

This would explain why we cannot debug into the exception.

I think the workaround would be to use a string instead of a regexp as the source of the pattern: see https://plnkr.co/edit/resZCaJu42dx8J7r?preview

**Comment by ocket8888** [comment]
> I think the workaround would be to use a string instead of a regexp as the source of the pattern

Doesn't appear to be the case:
```
Unable to check <input pattern='(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\:){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$|^\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?(\/(12[0-8]|1[0-1][0-9]|[0-9][0-9]?))?$|^((25[0-5]|2[0-4][0-9]|[0-1]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[0-1]?[0-9][0-9]?)(\/(3[0-2]|[0-2]?[0-9]))?'> because the pattern is not a valid regexp: invalid identity escape in regular expression
```

**Comment by petebacondarwin** [comment]
Yes, you are right. But I now see that the problem is with the escaping of the `:`. This plunker shows two shorter regular expressions. The first is escaping the `:` and the second not. You'll see that typing in the second input does not trigger the warning: https://plnkr.co/edit/resZCaJu42dx8J7r

**Comment by ocket8888** [comment]
Well that's just really... strange. I can copy/paste that into my dev tools in the exact same browser where it's failing and use it just fine:

![image](https://user-images.githubusercontent.com/6013378/106051590-e2732780-60a5-11eb-98bb-bce6dade96ff.png)

It's only when I try to use it as a pattern validator that it complains. The RegExp itself is valid as far Gecko is concerned - so why the problem escaping a colon?

**Comment by petebacondarwin** [comment]
¯\_(ツ)_/¯

**Comment by ocket8888** [comment]
Removing the `\` before the `:`s worked, in that it didn't print the console error, but the input control in my more complex app where I first noticed the problem was still highlighted red because it had the `:-moz-ui-invalid` pseudo-class. I tried working around that with some styling changes, but the form still cannot be submitted because Firefox sees the contents as invalid (even though rudimentary testing in the dev console shows it is not).

So although Angular considers the input valid, the browser does not, and I cannot submit the form.

I've updated [my original plunk](https://plnkr.co/edit/5N7CZU6K60xFjXH5) to show this; you can see by inspecting the element it has both the `ng-valid` and `:-moz-ui-invalid` pseudo classes.
