### ISSUE TITLE
docs(http): Improve documentation on how to pass a stringified parameter list to `HttpClient`

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#40618]
The options.params parameter of `HttpClient.request()` and similar methods only accept the type `HttpParams|{[param: string]: string | string[]}` for the `params` property. This means that the user cannot directly pass a pre-stringified list of params. E.g. `angular=awesome&angular5=yes`.

There are actually two ways to achieve this:

* Append the the params string to the requested URL:

```ts
httpClient.get(url + '?' + paramString)
```

* Create a new `HttpParams` object:

```
httpClient.get(url, new HttpParams({fromString: paramString})
```

We should update the documentation to make it clear how to use these approaches.

**Comment by cesperian** [comment]
@petebacondarwin IMO this kind of documentation would be added to [https://angular.io/api/common/http/HttpRequest#params](https://angular.io/api/common/http/HttpRequest#params).

There's already an existing description for params (and others) but it's pretty brief.

Maybe then add a link to the HttpRequest page in the 'See all' section of HttpClient? 

You can assign this to me, please...
