### ISSUE TITLE
angular display static text to dynamic value

### ISSUE THREAD

**Issue by vijaybKatta1** [angular/angular#40631]
I'm having 2 JSONs. The first one is having the format of the JSON value and the second one is having the actual value which is I want to display in the UI.

But I'm seeing the "application.appID" instead of 101. Does any help please?

component.ts

 this.json1={
label:"applicaiton.appID"
};

this.application ={
appID:101
};

ui.html

<mat-label> {{json1.label}} </mat-label>
<mat-label [innterHtml]="json1.lable"> </mat-label>

**Comment by mlc-mlapis** [comment]
@2vijaybKatta1 `json1.label` contains the value of the string "application.appID". This a correct fact.

**Comment by vijaybKatta1** [comment]
yes. But, we are getting controls from json1 and values are getting from API (this.application). So, here we are having 2 JSON objects.

**Comment by mlc-mlapis** [comment]
@vijaybKatta1 Shouldn't be it then:

```
this.json1={
   label: this.application.appID
};
```

The string `"application.appID"` is a string, a primitive value, not a reference.

**Comment by vijaybKatta1** [comment]
I've tried as per your suggestion , but  no luck.
this.application ={
appID:101
};

this.json1={
label:"this.applicaiton.appID"
};

**Comment by vijaybKatta1** [comment]
Here we need like {{ {{ }} }} or {{# json1.lable #}} or ... I've tried all these. we need to bind twice here.

**Comment by mlc-mlapis** [comment]
@vijaybKatta1 You don't listen to me. I repeat that the value of the property `label` is a string -> `label: "this.application.appID"`, so if you want it as a relation, it has to be `label: this.application.appID`.

**Comment by vijaybKatta1** [comment]
Working.
Thank you mlc-mlapis.

**Comment by vijaybKatta1** [comment]
How can I do if I want do with the string?
