### ISSUE TITLE
Conditional routing is not working in prod build, while it works in the development mode. (ng serve)

### ISSUE THREAD

**Issue by saurabh47** [angular/angular#40643]
This Issue already raised here https://github.com/angular/angular/issues/37664 
but closed due to inactivity. 

# 🐞 bug report

### Affected Package
@angular/router

### Is this a regression?
it is not working on an older version also

### Description
Description
When we add a conditional route on routing.module.ts, it works on development mode (```ng serve```) , but when we make a production build (```ng build --prod```), it does not work.
eg.
`app.routing.module.ts`
```
import { environment } from '../environments/environment';

const specialRoutes = [];

if(environment.includeSpecialRoute){
  specialRoutes.push({
    path: 'special-component',
    component: SpecialComponent
  });
}

const routes: Routes = [
  { path: "", redirectTo: "login", pathMatch: "full" },
  { path: 'login', component: LoginComponent },
  ...specialRoutes,
  { path: '**', component: NotFoundComponent }
];
@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```
## 🔬 Minimal Reproduction

https://github.com/saurabh47/Angular-routing-issue
1. create a build-in prod mode ```ng build --prod```
2.  Try the ```/special-component``` route. 
3. It doesn't work
4. now run the project using ```ng serve```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.28
Node: 10.16.`
OS: Windows 10
Angular: 8.2.14
</code></pre>

**Anything else relevant?**

**Comment by dianmonblan** [comment]
Hello @saurabh47 

### **Try the following:**
**Option one variable type declaration**
`
const specialRoutes: Routes = [];
**...**
`

**Option two single variable declaration routes**
`
let routes: Routes = [
  { path: "", redirectTo: "login", pathMatch: "full" },
  { path: 'login', component: LoginComponent }
];

if(environment.includeSpecialRoute){
  routes.push({
    path: 'special-component',
    component: SpecialComponent
  });
};

routes.push({ path: '**', component: NotFoundComponent };

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
`
_Note:_  You must keep in mind the step by reference for the `constants` [Symbol](https://www.typescriptlang.org/docs/handbook/symbols.html)

**Comment by saurabh47** [comment]
Hi @dianmonblan ,
as per your recommendation, I have made that changes in ```app-routing.module.ts```

https://github.com/saurabh47/Angular-routing-issue/tree/dev
when we create a build using ```ng build --prod``` & host the app using ```nginx``` it doesn't work.
Produt Build -> https://github.com/saurabh47/Angular-routing-issue/blob/dev/angular-conditional-routes.zip
it throws the error
```
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'special-component'
Error: Cannot match any routes. URL Segment: 'special-component'
```
This ```{ path: '**', component: NotFoundComponent }``` also not working.

**Comment by petebacondarwin** [comment]
The reason this is working in non-prod mode, is that you have AOT compilation turned off for that mode.

In AOT mode, the compiler has to be able to statically analyze the route information. So I am not sure that this approach is at all supported in Angular generally.

**Comment by petebacondarwin** [comment]
I also note that your reproduction is using Angular v8 and ViewEngine. I will test updating it to Ivy (and the latest Angular) since Ivy does a better job of statically analysing code.

**Comment by petebacondarwin** [comment]
I can confirm that this works in the lastest version of Angular with Ivy enabled. Please update your application to use the Ivy compiler.
