### ISSUE TITLE
Display value from the string path which is in JSON

### ISSUE THREAD

**Issue by vijaybKatta1** [angular/angular#40642]
m having 2 JSONs. The first one is having the format of the JSON value and the second one is having the actual value which is I want to display in the UI.

But I'm seeing the "application.appID" instead of 101. Does any help please?

Not working if label:"applicaiton.appID". I'm having label: "string". How can I display the value?

working if label: applicaiton.appID

component.ts

 this.json1={
label:"applicaiton.appID"
};

this.application ={
appID:101
};
ui.html

<mat-label> {{json1.label}} </mat-label>
<mat-label [innterHtml]="json1.lable"> </mat-label>

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
