### ISSUE TITLE
FormGroup.value is not updated with FormControl.valueChanges

### ISSUE THREAD

**Issue by junekpavel** [angular/angular#40649]
# 🐞 bug report

### Affected Package
@angular/forms

### Description

When observing FormControl value changes, the form group value is not updated when accessed in subscription.

For example, when FormControl value is changed from `oldValue` to `newValue`:

```
formControl.valueChanges.subscribe(value => {
  console.log(value); // `newValue` is logged
  console.log(this.form.value); // `{ myControl: 'oldValue' }` is logged
});
```

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-aqyc81

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular 11.0.8
</code></pre>

**Comment by mlc-mlapis** [comment]
@junekpavel You forgot that those elements are not processed synchronously:

```
private observeMyControlChanges(): void {
    this.form.controls.myControl.valueChanges.subscribe(value => {
      console.log(value);
      setTimeout(() => console.log(this.form.value), 0); // Works as expected
    });
  }
```

**Comment by petebacondarwin** [comment]
Yes, that's right. It is not strictly asynchronous, but the parent form is updated after the `FormControl` itself emits its `valueChanges` event. See https://github.com/angular/angular/blob/c9fe455fa2c34ba0de6edbecfeca8c86ccbebe3a/packages/forms/src/model.ts#L743-L750

**Comment by petebacondarwin** [comment]
Closing as works as expected.

**Comment by junekpavel** [comment]
Thank you both for the explanation. Ended up with:

```
private observeMyControlChanges(): void {
    this.form.controls.myControl.valueChanges.subscribe(value => {
      console.log(value);
      this.form.updateValueAndValidity({emitEvent: false, onlySelf: true});
      console.log(this.form.value)
    });
  }
```
