### ISSUE TITLE
Need to run ngcc twice to output Ivy compatible files for modules with dependencies on other modules needing Ivy outputs

### ISSUE THREAD

**Issue by aburkowsky9** [angular/angular#40656]
# 🐞 bug report

### Affected Package
`ngcc`

### Is this a regression?
No, I have noticed this behavior on Angular v9 - 11.

### Description
I am building a components library that exposes each component as its own individual package with isolated versioning and installation. I understand this is an odd pattern and we are considering moving away from it due to a variety of difficulties, but it has exposed an issue with the ngcc cli tool. 

Per Angular documentation [guidelines](https://angular.io/guide/creating-libraries#publishing-your-library), I do not publish the Ivy version of these components. Because we publish View Engine compatible components, our consumers must run ngcc if they want to use the Ivy compiler in their own applications. Due to this individual component publish architecture, there are instances where a component is dependent on a different component. For example, our `Button` component is dependent on our `Icon` component.

When consumers run `ngcc` after installing both the `Button` and `Icon` packages to their `node_modules`,  `ngcc` fails to output Ivy compatible files for the `Button` package on the first run because it says its dependency `Icon` is not Ivy compatible. Interestingly, the first run of `ngcc`  outputs Ivy compatible files for the `Icon` package after this initial error. On a second run, since the `Icon` package is now Ivy compatible, it properly outputs Ivy compatible files for the `Button` package.

First Run of `ngcc`:
![Screen Shot 2021-02-01 at 10 37 13 AM](https://user-images.githubusercontent.com/38677277/106502868-c68ecd80-6479-11eb-9f1b-c3f57062d8df.png)
![Screen Shot 2021-02-01 at 10 38 09 AM](https://user-images.githubusercontent.com/38677277/106502877-c989be00-6479-11eb-92cb-281eed87ad7c.png)
![Screen Shot 2021-02-01 at 10 39 23 AM](https://user-images.githubusercontent.com/38677277/106502885-ce4e7200-6479-11eb-8faa-58ea59ed9ded.png)

Second Run of `ngcc`:
![Screen Shot 2021-02-01 at 10 41 01 AM](https://user-images.githubusercontent.com/38677277/106503061-08b80f00-647a-11eb-8888-658dd385dcaa.png)
![Screen Shot 2021-02-01 at 10 41 09 AM](https://user-images.githubusercontent.com/38677277/106503068-09e93c00-647a-11eb-9f87-0c50ccbce4e0.png)

## 🔬 Minimal Reproduction
Unfortunately, these npm modules are internal to my company and require credentials to access/install. In order to replicate this issue, one could publish two dummy packages to npm with one having a dependency on the other then try to install them. This would take some work to setup and doesnt seem entirely necessary to pinpoint the issue as explained above. I am happy to screenshare or walk through some debugging steps if need be.

## 🔥 Exception or Error
![Screen Shot 2021-02-01 at 10 46 02 AM](https://user-images.githubusercontent.com/38677277/106503609-baefd680-647a-11eb-8257-9fc902d3b049.png)
![Screen Shot 2021-02-01 at 10 46 11 AM](https://user-images.githubusercontent.com/38677277/106503619-bcb99a00-647a-11eb-932c-b94e8ca7489c.png)

## 🌍  Your Environment

**Angular Version:**

**Behavior noted in Angular CLI v9.1+ through v11.1.1**
<pre><code>
Angular CLI: 11.1.1
Node: 12.18.4
OS: darwin x64

Angular: 11.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.1
@angular-devkit/build-angular   0.1101.1
@angular-devkit/core            11.1.1
@angular-devkit/schematics      11.1.1
@schematics/angular             11.1.1
@schematics/update              0.1101.1
ng-packagr                      11.1.2
rxjs                            6.6.3
typescript                      4.1.3
</code></pre>

**Comment by petebacondarwin** [comment]
Hi!

First of all, it should not be necessary to run `ngcc` directly any more. The Angular CLI takes care of it and ensures that the packages used by the program are processed.

My main thought is that there must be something strange going on with the dependencies between these packages. Perhaps they refer to each other via relative path imports (e.g. `../relative/path`) which means that ngcc would not realise that this is a dependency on a different package that needs processing separately?

I would be happy to screenshare to take a look. I will email you directly.

**Comment by petebacondarwin** [comment]
Alex and I debugged into the project. The short story is that the `ng.icon` appeared to have an invalid package.json `typings` property. It didn't point to the correct typings file path, and therefore ngcc was not able to find the `metadada.json` file, which led to it ignoring this dependency and so not processing it.

There is also a compounding problem that it was a nested dependency from `ng.button` to `ng.icon`. Since there was also a copy of `ng.icon` at the top level too, this may be the reason why this works on the second build, since perhaps we pick up the top level one in the TS build?

**Comment by aburkowsky9** [comment]
Thanks again for debugging with me, Pete. As far as my library is concerned this issue can be closed unless the second build working is an edge case the Angular team wants to continue to explore.

**Comment by petebacondarwin** [comment]
I am going to close this. Since we are getting close with the new linker, we are not spending much time on tweaking ngcc unless really necessary. Thanks @aburkowsky9
