### ISSUE TITLE
DatePipe renders German 'short day' (EE) incorrectly

### ISSUE THREAD

**Issue by Alken0** [angular/angular#40654]
# 🐞 bug report

### Affected Package
The issue is caused by packages
@angular/common/DatePipe
@angular/common/locales/de

### Is this a regression?
unknown
earliest report I could find: https://stackoverflow.com/questions/51101949/german-date-localization-without-the-dot

### Description

When formatting the Date with a shortend Day Format in German, a dot is applied automatically.
Expected behaviour: As in english I would expect that there is no dot in the end. 
The dot should be added through the 'date-string' given to the pipe.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-oh7wqk?file=src%2Fapp%2Fapp.component.html

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Package                         Version
---------------------------------------------------------
@angular/common      11.0.8

</code></pre>

**Comment by petebacondarwin** [comment]
Hi @Alken0 - I am afraid that the definitions of these formats are taken directly from the CLDR project. See https://github.com/unicode-org/cldr/blob/master/common/main/de.xml#L2029-L2037

If you feel this format is incorrect then you would need to raise an issue in their issue tracker: https://unicode-org.atlassian.net/jira/software/c/projects/CLDR/issues
