### ISSUE TITLE
Make `Testability` and `TestabilityRegistry` tree-shakable

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#40662]
The `packages/core/src/testability/testability.ts` file contains some classes (such as `Testability` and `TestabilityRegistry`) that are used for testing only, but the way they are provided in Angular (see `packages/core/src/platform_core_providers.ts`) and used (see `packages/core/src/application_ref.ts`) are not tree-shakable.

Quick investigation done by Misko indicated that this would require some complex deprecation of code and or have the testability be lazy loaded by the protractor. We can also try to use a pattern that was used by `HammerModule` (so if testability logic is needed, a new NgModule should be imported), but this would likely be a breaking change.

**Comment by StanislavKharchenko** [comment]
Hi Andrew @AndrewKushnir .
We're using Testability functionality in our selenium and protractor (and also plan to use in webdriver-io) testing projects to identify if Angular application stable and so our tests could interact with page.
What does "tree-shakable" means? How this refactoring could affect "Testability" functionality in scope of e2e testing?

Thanks in advance.

**Comment by AndrewKushnir** [comment]
Hi @StanislavKharchenko, currently the `Testability` and `TestabilityRegistry` symbols are references in Angular framework code directly, which prevents tree-shaking (i.e. eliminating unused code fro the bundle). The goal of the described refactoring is to make sure the `Testability` and `TestabilityRegistry` symbols are only present in the bundle when they are actually used. More investigation is needed to determine how to implement that in the best way possible (to minimize the impact on the apps that do use these symbols). One potential scenario is that this logic can be moved to a new NgModule that can be imported when `Testability` subsystem is in use (similar to the `HammerModule` that was introduced to make HammerJS logic tree-shakable). However there are no specific actions planned yet and we will perform the necessary communication to let everyone know if any modifications are needed on applications side.

**Comment by AndrewKushnir** [comment]
Just a quick update: I've performed some additional investigation to better understand the impact of having Testability always present in production bundle. Here is a test PR: #44356. I've measured the difference on the AIO app and the delta is **~4KB** (459032 vs 454982 bytes), i.e. the production bundle is 4KB bigger when Testability-related logic is present.
