### ISSUE TITLE
Create "declare" functions for everything

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#40677]
- [x] pipes: https://github.com/angular/angular/pull/40803
- [x] modules: https://github.com/angular/angular/pull/41080
- [x] factories: https://github.com/angular/angular/pull/41231
- [x] injectables: #41316
- [x] setClassMetadata: #41200

**Comment by jelbourn** [comment]
@petebacondarwin is this issue still relevant?

**Comment by petebacondarwin** [comment]
This is indeed complete! Thanks for the reminder.
