### ISSUE TITLE
describe format of DecimalPipe's digitsInfo parameter

### ISSUE THREAD

**Issue by AlexElin** [angular/angular#40671]
# 📚 Docs or angular.io bug report

### Description

Describe format of DecimalPipe's digitsInfo parameter.
Currenlty it's unclear from the [docs](https://angular.io/api/common/DecimalPipe) what _each number_ in '3.1-5' (taken as ane example) _means_.
Yes, there're examples in the docs but I think there's sense to add more formal description of the format.

### What's the affected URL?**
https://angular.io/api/common/DecimalPipe

**Comment by petebacondarwin** [comment]
That is a very reasonable request. This would be a great opportunity for a community PR.
