### ISSUE TITLE
npm install angular2 installs typings bundles to root typings folder

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#4068]
When I run npm install angular2 , it installs typings bundles to root typings folder. This is fine if that is where I put them but my project keeps the typings folder under the /src folder. So I end up with 2 sets.

Is there a way to make them go to the folder that my tsconfig.json specifies?

this is my `src/tsd.json` file 

```
{
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "path": "typings",
  "bundle": "typings/tsd.d.ts",
  "installed": {
    "rx/rx.d.ts": {
      "commit": "2031893e963cb986db7eea00d9e83c9b2b0fffee"
    },
    "angular2/angular2.d.ts": {
      "commit": "2031893e963cb986db7eea00d9e83c9b2b0fffee"
    },
    "es6-promise/es6-promise.d.ts": {
      "commit": "2031893e963cb986db7eea00d9e83c9b2b0fffee"
    },
    "angular2/router.d.ts": {
      "commit": "2031893e963cb986db7eea00d9e83c9b2b0fffee"
    },
    "rx/rx-lite.d.ts": {
      "commit": "2031893e963cb986db7eea00d9e83c9b2b0fffee"
    }
  }
}
```

**Comment by johnpapa** [comment]
cc // @wardbell

**Comment by johnpapa** [comment]
I'm seeing inconsistent behavior on this now.

when installing angular2 alpha 37 i sometimes see a typings folder in the root with references to the 3 typings files that are in the node_modules/angular2/bundles folder. Other times this `typings/t.d.ts` file does not get create at all.

I think it would be ideal if this would be create in a customizable location.

**Comment by gdi2290** [comment]
is also a `tsd` problem. 
`tsd` released  breaking change as a patch which run `tsd link` on install which in turn links the type definition files to any in `node_modules/`. They released another patch to revert that change so you might have a conflict of a local copy install for your project and your global copy of tsd. Which would cause the inconsistent behavior

What I did was update both copies of tsd to latest and during install I run `tsd link` and remove any angular typing from `tsconfig.json`

**Comment by mhevery** [comment]
Closing since it is a DefinitelyTyped/tsd#204 issue
