### ISSUE TITLE
Missing return value documentation for HostListener callbacks

### ISSUE THREAD

**Issue by dwilches** [angular/angular#40708]
# 📚 Docs or angular.io bug report

### Description

The documentation for [HostListener](https://angular.io/api/core/HostListener) doesn't mention what return type the method can have, nor it provides a link of clues about where to go to search for that information.

For example, when using the `HostListener` with a return value (like in [Angular's routerLink's source code](https://github.com/angular/angular/blob/master/packages/router/src/directives/router_link.ts)), we can return `true` or `false`, like this:
```
  @HostListener("click")
  onClick() {
    console.log("pressed");
    return false;
 }
```

There is no mention in that page about how the return type of the `onClick` method affects navigation (`false` prevents the default behaviour of an `a` link for example).

If adding this information is out of the scope for the `HostListener` documentation, at least a link to a list of events with more documentation would be appreciated in there, as this is the page where we go to search such information.

### What's the affected URL?**
https://angular.io/api/core/HostListener

**Comment by petebacondarwin** [comment]
You're right. It is mentioned here:https://angular.io/api/core/Directive#host

> For event handling:
> 
> The key is the DOM event that the directive listens to. To listen to global events, add the target to the event name. The target can be window, document or body.
> The value is the statement to execute when the event occurs. If the statement evaluates to false, then preventDefault is applied on the DOM event. A handler method can refer to the $event local variable.

We should add this to the `@HostListener` decorator docs too.

Community PR welcome!!

**Comment by Airblader** [comment]
@petebacondarwin Does that mean Angular actively _calls_ preventDefault? In a regular event handler when false is returned, preventDefault is AFAIK not called, it just sets the canceled flag on the event as well, but even for that there are some intricacies on how exactly that is handled.

**Comment by petebacondarwin** [comment]
So it depends upon the renderer... 

If the function explicitly returns `false` then is prevents the default event.
Here is the relevant code: https://github.com/angular/angular/blob/fc1cd07eb002662c21177f28ef59714f3b2876ed/packages/core/src/render3/instructions/listener.ts#L232

But in `wrapListener()` you can see that it only actually calls `e.preventDefauly()` if `wrapWithPreventDefault` is set to true.
And the procedural renderer handles this itself, so `wrapWithPreventDefault` is false in that case.

**Comment by petebacondarwin** [comment]
I also note that this is documented here: https://github.com/angular/angular/blob/3b2e5be6cb5ee7d0d7630a6cc3a2d7111dc3dad9/packages/core/src/metadata/directives.ts#L848-L853

But this is not rendered in the angular.io docs for this decorator. Instead the text here is displayed: https://github.com/angular/angular/blob/3b2e5be6cb5ee7d0d7630a6cc3a2d7111dc3dad9/packages/core/src/metadata/directives.ts#L823-L826

So the fix is to copy the former text to the later.

**Comment by abarghoud** [comment]
Hello @petebacondarwin, I would like to submit a PR to add this piece of doc
