### ISSUE TITLE
Impoort JS file as module issue

### ISSUE THREAD

**Issue by halimpuckjava** [angular/angular#40703]
hi

when try to import js file as module, an exception appear "can't use import outside of module"

**Comment by petebacondarwin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
