### ISSUE TITLE
Angular auto binding issue

### ISSUE THREAD

**Issue by skwsccss** [angular/angular#40713]
Auto-updating/binding component dynamically is not working in angular 10.0.x when using the API data.
It appears the updated data only when you give any keyboard or mouse click event

https://user-images.githubusercontent.com/52093657/106979345-1c74b580-6799-11eb-9dc0-1ee9d53f0025.mp4

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

You're likely initiating the API request outside of the Angular zone, so when its response arrives Angular won't rerender.
