### ISSUE TITLE
JS files can't use as module 

### ISSUE THREAD

**Issue by halimpuckjava** [angular/angular#40723]
hi

i create angular (11.1.0) project and i add manually mdb 5 pro (sass, js, fonts) to the project, i create a new js file (script.js) and inside this file i import mdb.pro.js

when i build project, nothing happen so when move to dev mode i see in console "can't use import outside of module" this error appear in script.js (contain only one line:  import 'path/to/mdb.pro.js')

so why angular can't allow import js files as module (i try to add in package.json  "type": "module" but not thing change)

**Comment by petebacondarwin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
