### ISSUE TITLE
More precise type for APP_INITIALIZER token

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#40729]
Currently the `APP_INITIALIZER` token is typed as:

https://github.com/angular/angular/blob/d067dc0cb9a3088a7c3443d33d35f7a0856b8a49/packages/core/src/application_init.ts#L31

The type should be more precise and contain actual type that Angular handles, something like:

```
export const APP_INITIALIZER = new InjectionToken<Array<() => Promise<unknown>>>('Application Initializer');
```

Note:

- this would be a breaking change
- it makes sense to implement this after PR #33222 lands, since it'd introduce `Observable` support as well

**Comment by abarghoud** [comment]
Hello @AndrewKushnir, I would like to work on this issue, I will wait for PR #33222 to land before, could you assign me please.

**Comment by AndrewKushnir** [comment]
Thanks @abarghoud, I've added you to the Assignee list.

**Comment by AndrewKushnir** [comment]
@abarghoud FYI PR #33222 has landed, so this ticket is now unblocked.
