### ISSUE TITLE
Provide usage examples for APP_INITIALIZER token

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#40730]
Currently the pages that refer to `` and `` symbols don't contain examples of how `APP_INITIALIZER` can be used, see:

- https://angular.io/api/core/ApplicationInitStatus
- https://angular.io/api/core/APP_INITIALIZER

If there are some examples in guides that I missed, it'd be great to add links to the mentioned doc pages.

Note: it makes sense to update docs once PR #33222 lands, since it adds support for `Observable`s as well (so we can have both Promise and Observable-based examples).

**Comment by abarghoud** [comment]
Hello @AndrewKushnir, I would like to work on this issue, I will wait for PR #33222 to land before, could you assign me please.

**Comment by AndrewKushnir** [comment]
Thanks @abarghoud, I've added you to the Assignee list.

**Comment by Pragyansh99** [comment]
Does APP_INITIALIZER stop the angular app from being loaded in the client-side browser or it stops initializing the app? 
I want to fetch a JSON file before starting the app execution! And the JSON file is in the assets folder of the app! Is using APP_INITIALIZER is a good idea or there is another better way of doing this?

**Comment by AndrewKushnir** [comment]
@Pragyansh99 Angular awaits for all `APP_INITIALIZER` to complete before initializing an app, so I believe it might be a godo solution for your scenario.

**Comment by AndrewKushnir** [comment]
@abarghoud FYI PR #33222 has landed, so this ticket is now unblocked.

**Comment by abarghoud** [comment]
Thank you for the information, I will get started soon
