### ISSUE TITLE
The structural directive type check docs section is incomplete

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular#40739]
The following docs section is incomplete:

https://angular.io/guide/structural-directives#directive-type-checks

```ts
export type Loaded = { type: 'loaded', data: T };
export type Loading = { type: 'loading' };
export type LoadingState = Loaded | Loading;
export class IfLoadedDirective {
    @Input('ifLoaded') set state(state: LoadingState) {}
    static ngTemplateGuard_state(dir: IfLoadedDirective, expr: LoadingState): expr is Loaded { return true; };
}

export interface Person {
  name: string;
}

@Component({
  template: `<div *ifLoaded="state">{{ state.data }}</div>`,
})
export class AppComponent {
  state: LoadingState;
}
```

> The type guard allows the type checker to infer that the acceptable type of state within the template is a Loaded<T>, and further infer that T must be an instance of Person.

- Where is `T` comes from?
- How do we use the `Person` interface? 
- The directive decorator is missing.

**Comment by JoostK** [comment]
The fact that `T` and the usage of `Person` is missing appears to be a rendering issue; it is authored as expected in the source:

https://github.com/angular/angular/blob/d067dc0cb9a3088a7c3443d33d35f7a0856b8a49/aio/content/guide/structural-directives.md#L876-L893

I suspect that the angle brackets need to be converted into html entities.

**Comment by gkalpak** [comment]
Yes, the brackets need to be HTML-escaped.
 
Yet another case where hard-coded code snippets don't serve us well 😛
Ideally we should convert these to [doc-regions][1].

[1]: https://angular.io/guide/docs-style-guide#code-snippets-and-code-samples

**Comment by petebacondarwin** [comment]
👍  to doc regions. Of course if the code was in backticks then the code would be escaped but not in `code-example` tags.

**Comment by ArielGueta** [comment]
Thanks. I don't know if it's the right place, but it doesn't seems to work. I copied the code from the example and this is result:

<img width="707" alt="Screen Shot 2021-02-07 at 7 25 19" src="https://user-images.githubusercontent.com/20522870/107137474-b6616d00-6915-11eb-9e43-ab345cab9b17.png">

The `fullTemplateTypeCheck` is set to `true`, and I'm using Ivy.

**Comment by JoostK** [comment]
You'll want to use`strictTemplates` set to true instead of `fullTemplateTypeCheck`.

**Comment by iftee-hussain** [comment]
If anyone is already not working on it, I can give it a try to create a PR converting these to `doc-regions`

**Comment by iftee-hussain** [comment]
This not working https://stackblitz.com/edit/angular-bwvsh3
Am I missing something?

**Comment by JoostK** [comment]
> This is not working https://stackblitz.com/edit/angular-bwvsh3
> Am I missing something?

The example in the docs is only concerning the type-check capabilities of the directive, its actual runtime implementation of rendering its template when in the `loaded` state is not included (so in your StackBlitz nothing actually happens). Also note that the `ngTemplateContextGuard` function is never executed at runtime: its sole purpose is to provide a TypeScript signature to model the type narrowing behavior of the directive; this explains why the `console.log` inside that static method is not logged in StackBlitz.

**Comment by ArielGueta** [comment]
@JoostK switched to `strictTemplates` and still the same:

![image](https://user-images.githubusercontent.com/20522870/107326363-efcfdf00-6ab3-11eb-9f29-488e3b20caab.png)

**Comment by mariusgau** [comment]
> 
> 
> > This is not working https://stackblitz.com/edit/angular-bwvsh3
> > Am I missing something?
> 
> The example in the docs is only concerning the type-check capabilities of the directive, its actual runtime implementation of rendering its template when in the `loaded` state is not included (so in your StackBlitz nothing actually happens). Also note that the `ngTemplateContextGuard` function is never executed at runtime: its sole purpose is to provide a TypeScript signature to model the type narrowing behavior of the directive; this explains why the `console.log` inside that static method is not logged in StackBlitz.

I want to help and create a PR. @JoostK the documentation (https://angular.io/guide/structural-directives#directive-type-checks) says 

> The IfLoadedDirective definition declares the static field ngTemplateGuard_state, which expresses the narrowing behavior. Within the AppComponent template, the *ifLoaded structural directive should render this template only when state is actually Loaded|Person|.

So I don't understand why ist `<div *ifLoaded="loading">Loading...</div>` rendered in @iftee-hussain example when `loading: Loading` (https://stackblitz.com/edit/angular-bwvsh3)

**Comment by DMezhenskyi** [comment]
> Thanks. I don't know if it's the right place, but it doesn't seems to work. I copied the code from the example and this is result:
> 
> <img alt="Screen Shot 2021-02-07 at 7 25 19" width="707" src="https://user-images.githubusercontent.com/20522870/107137474-b6616d00-6915-11eb-9e43-ab345cab9b17.png">
> 
> The `fullTemplateTypeCheck` is set to `true`, and I'm using Ivy.

Hi @ArielGueta!
Did you try to change `static ngTemplateGuard_state` to `static ngTemplateGuard_ifLoaded`?
