### ISSUE TITLE
proxy-config do not work

### ISSUE THREAD

**Issue by ahl5esoft** [angular/angular#40734]
cli: 
`
√ Compiled successfully.
[HPM] Rewriting path from "/api/bg/find-menus" to "/bg/find-menus"
[HPM] POST /api/bg/find-menus ~> http://localhost:10000
`

proxy.conf.json: 
`{
  "/api/*": {
    "changeOrigin": true,
    "logLevel": "debug",
    "pathRewrite": {
      "^/api": ""
    },
    "secure": false,
    "target": "http://localhost:10000"
  }
}`

chrome:
`core.js:27891 Angular is running in development mode. Call enableProdMode() to enable production mode.
zone-evergreen.js:2845 POST http://localhost:9999/api/bg/find-menus 400 (Bad Request)
scheduleTask @ zone-evergreen.js:2845
scheduleTask @ zone-evergreen.js:389
onScheduleTask @ zone-evergreen.js:279
scheduleTask @ zone-evergreen.js:382
scheduleTask @ zone-evergreen.js:217
scheduleMacroTask @ zone-evergreen.js:240
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:675
(anonymous) @ zone-evergreen.js:2878
proto.<computed> @ zone-evergreen.js:971
(anonymous) @ http.js:1785
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
innerSubscribe @ innerSubscribe.js:67
_innerSub @ mergeMap.js:57
_tryNext @ mergeMap.js:51
_next @ mergeMap.js:34
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ mergeMap.js:19
subscribe @ Observable.js:23
call @ filter.js:13
subscribe @ Observable.js:23
call @ map.js:16
subscribe @ Observable.js:23
(anonymous) @ Observable.js:91
ZoneAwarePromise @ zone-evergreen.js:1383
toPromise @ Observable.js:89
(anonymous) @ http.service.ts:26
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone-evergreen.js:1383
__awaiter @ tslib.es6.js:72
post @ http.service.ts:25
(anonymous) @ index-menu.component.ts:41
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone-evergreen.js:1383
__awaiter @ tslib.es6.js:72
find @ index-menu.component.ts:40
ngOnInit @ index-menu.component.ts:31
callHook @ core.js:2512
callHooks @ core.js:2483
executeInitAndCheckHooks @ core.js:2434
refreshView @ core.js:9383
refreshEmbeddedViews @ core.js:10488
refreshView @ core.js:9392
refreshComponent @ core.js:10534
refreshChildComponents @ core.js:9165
refreshView @ core.js:9418
renderComponentOrTemplate @ core.js:9482
tickRootContext @ core.js:10708
detectChangesInRootView @ core.js:10733
detectChanges @ core.js:22751
tick @ core.js:29473
(anonymous) @ core.js:29357
invoke @ zone-evergreen.js:368
onInvoke @ core.js:28494
invoke @ zone-evergreen.js:367
run @ zone-evergreen.js:130
run @ core.js:28378
next @ core.js:29356
schedulerFn @ core.js:25848
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:25838
checkStable @ core.js:28431
onHasTask @ core.js:28511
hasTask @ zone-evergreen.js:422
_updateTaskCount @ zone-evergreen.js:443
_updateTaskCount @ zone-evergreen.js:270
runTask @ zone-evergreen.js:191
drainMicroTaskQueue @ zone-evergreen.js:578
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:561
scheduleTask @ zone-evergreen.js:392
scheduleTask @ zone-evergreen.js:217
scheduleMicroTask @ zone-evergreen.js:237
scheduleResolveOrReject @ zone-evergreen.js:1262
then @ zone-evergreen.js:1406
bootstrapModule @ core.js:29143
zUnb @ main.ts:11
__webpack_require__ @ bootstrap:79
0 @ main.js:11
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
Show 45 more frames
core.js:6156 ERROR Error: Uncaught (in promise): HttpErrorResponse: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":400,"statusText":"Bad Request","url":"http://localhost:9999/api/bg/find-menus","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://localhost:9999/api/bg/find-menus: 400 Bad Request","error":null}
    at resolvePromise (zone-evergreen.js:1209)
    at resolvePromise (zone-evergreen.js:1163)
    at zone-evergreen.js:1275
    at ZoneDelegate.invokeTask (zone-evergreen.js:402)
    at Object.onInvokeTask (core.js:28481)
    at ZoneDelegate.invokeTask (zone-evergreen.js:401)
    at Zone.runTask (zone-evergreen.js:174)
    at drainMicroTaskQueue (zone-evergreen.js:578)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:487)
    at invokeTask (zone-evergreen.js:1596)
defaultErrorLogger @ core.js:6156
handleError @ core.js:6204
next @ core.js:29101
schedulerFn @ core.js:25848
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:25838
(anonymous) @ core.js:28520
invoke @ zone-evergreen.js:368
run @ zone-evergreen.js:130
runOutsideAngular @ core.js:28423
onHandleError @ core.js:28520
handleError @ zone-evergreen.js:372
runGuarded @ zone-evergreen.js:143
api.microtaskDrainDone @ zone-evergreen.js:1070
drainMicroTaskQueue @ zone-evergreen.js:585
invokeTask @ zone-evergreen.js:487
invokeTask @ zone-evergreen.js:1596
globalZoneAwareCallback @ zone-evergreen.js:1633
load (async)
customScheduleGlobal @ zone-evergreen.js:1748
scheduleTask @ zone-evergreen.js:389
onScheduleTask @ zone-evergreen.js:279
scheduleTask @ zone-evergreen.js:382
scheduleTask @ zone-evergreen.js:217
scheduleEventTask @ zone-evergreen.js:243
(anonymous) @ zone-evergreen.js:1903
(anonymous) @ http.js:1773
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
innerSubscribe @ innerSubscribe.js:67
_innerSub @ mergeMap.js:57
_tryNext @ mergeMap.js:51
_next @ mergeMap.js:34
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ mergeMap.js:19
subscribe @ Observable.js:23
call @ filter.js:13
subscribe @ Observable.js:23
call @ map.js:16
subscribe @ Observable.js:23
(anonymous) @ Observable.js:91
ZoneAwarePromise @ zone-evergreen.js:1383
toPromise @ Observable.js:89
(anonymous) @ http.service.ts:26
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone-evergreen.js:1383
__awaiter @ tslib.es6.js:72
post @ http.service.ts:25
(anonymous) @ index-menu.component.ts:41
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone-evergreen.js:1383
__awaiter @ tslib.es6.js:72
find @ index-menu.component.ts:40
ngOnInit @ index-menu.component.ts:31
callHook @ core.js:2512
callHooks @ core.js:2483
executeInitAndCheckHooks @ core.js:2434
refreshView @ core.js:9383
refreshEmbeddedViews @ core.js:10488
refreshView @ core.js:9392
refreshComponent @ core.js:10534
refreshChildComponents @ core.js:9165
refreshView @ core.js:9418
renderComponentOrTemplate @ core.js:9482
tickRootContext @ core.js:10708
detectChangesInRootView @ core.js:10733
detectChanges @ core.js:22751
tick @ core.js:29473
(anonymous) @ core.js:29357
invoke @ zone-evergreen.js:368
onInvoke @ core.js:28494
invoke @ zone-evergreen.js:367
run @ zone-evergreen.js:130
run @ core.js:28378
next @ core.js:29356
schedulerFn @ core.js:25848
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:25838
checkStable @ core.js:28431
onHasTask @ core.js:28511
hasTask @ zone-evergreen.js:422
_updateTaskCount @ zone-evergreen.js:443
_updateTaskCount @ zone-evergreen.js:270
runTask @ zone-evergreen.js:191
drainMicroTaskQueue @ zone-evergreen.js:578
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:561
scheduleTask @ zone-evergreen.js:392
scheduleTask @ zone-evergreen.js:217
scheduleMicroTask @ zone-evergreen.js:237
scheduleResolveOrReject @ zone-evergreen.js:1262
then @ zone-evergreen.js:1406
bootstrapModule @ core.js:29143
zUnb @ main.ts:11
__webpack_require__ @ bootstrap:79
0 @ main.js:11
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
Show 65 more frames
client:52 [WDS] Live Reloading enabled.`

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by ahl5esoft** [comment]
angular cli 11.1.1 do not work in win10

**Comment by ahl5esoft** [comment]
> Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.
> 
> If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

angular cli 11.1.1 proxy-config do not work in win10

**Comment by JoostK** [comment]
I am sorry but it is unclear what the problem is, nor that it's caused by the CLI. What does it mean for it to "not work"? Please provide additional information and ideally a reproduction of the problem.
