### ISSUE TITLE
The library uses environment variables to package an error

### ISSUE THREAD

**Issue by fengzhihenxs** [angular/angular#40747]
Hello, I use environment variables in my angular library. When packaging this library, it says "File'C:/Test/src/environments/environment.ts' is not under'rootDir''C:\Test\projects\x -shared\src'.''C:\Test\projects\x-shared\src'.'rootDir' is expected to contain all source files.". I want to know why and how to use environment in angular library?

Thank you!

**Comment by petebacondarwin** [comment]
Please open an issue on https://github.com/ng-packagr/ng-packagr
