### ISSUE TITLE
AMP generation of webpage

### ISSUE THREAD

**Issue by pandeynandancse** [angular/angular#40748]
# 🚀 feature request

I have developed a web application and that follows server side rendering with the help of angular universal. But now I am unable to generate accelerated mobile pages for any page.
Can you suggest any way of implementing same or any progress in this field.

**Comment by petebacondarwin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
