### ISSUE TITLE
currency pipe Perú error

### ISSUE THREAD

**Issue by jimyhdolores** [angular/angular#40743]
### Description

this problem is related to the following 
https://github.com/angular/angular/issues/23419

the example they gave does not work in angular 11; if I use {{100000 | currency: 'PEN': 'symbol': '': 'es-PE'}} causes an error, but if I use {{100000 | currency: 'PEN': 'symbol': '': 'en-PE'}} if it works but does not bring the correct symbol since it should return "S/" but it returns "PEN"

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-currency-peru?file=src/app/app.component.ts

**Angular Version:**
11

**Comment by jnizet** [comment]
I added `{{100000 | currency: 'PEN': 'symbol': '': 'es-PE'}}` to your app component template in the stackblitz you linked to, and it doesn't cause any error as you claim it does, and it displays `S/ 100,000.00`: https://stackblitz.com/edit/angular-currency-peru-upndf4?file=src%2Fapp%2Fapp.component.html.

Using 'en-PE' doesn't make much sense to me:

- there is no such locale
- even if ithere was suche a locale, you would need to register the locale data for this locale

So what exactly is the issue? Could you clarify?

**Comment by petebacondarwin** [comment]
There are a number of issues with the provided reproduction, as described by @jnizet above. Moreover the call to `getCurrencySymbol()` is passing a `locale` string as the `code` argument. The `code` argument in this case should be the currency code, not the locale. The aim of `getCurrencySymbol()` is to find the currency symbol for a currency code within a given locale.

As @jnizet - the `en-PE` locale doesn't make sense. It doesn't exist and so Angular will use its fallback mechanism to return the `locale` for `en`. Instead the first argument ought to be `PEN`.

So as far as I can tell this is all working as expected and so I am going to close this issue.

@jimyhdolores - if there is still a problem you believe is a bug in Angular, please open a new issue with a suitable reproduction.
