### ISSUE TITLE
"Usage notes" in API reference are hard to discover

### ISSUE THREAD

**Issue by ychaikin** [angular/angular#40753]
# 📚 Docs or angular.io bug report

### Description

This all important paragraph is THE last paragraph in the docs on FormArray:
*********
**Adding or removing controls from a form array**
To change the controls in the array, use the push, insert, removeAt or clear methods in FormArray itself. These methods ensure the controls are properly tracked in the form's hierarchy. Do not modify the array of AbstractControls used to instantiate the FormArray directly, as that result in strange and unexpected behavior such as broken change detection.
*********

I would highly suggest to place this paragraph in the **Description** section of the doc. (https://angular.io/api/forms/FormArray#description).

I don't think anyone expects to find some super important general information about how this *specialized* array isn't like a regular array at all after the description of every method on the object. That seems to be more of a general information about how the entire API behaves and belongs in a more prominent position in the doc.

### What's the affected URL?**
https://angular.io/api/forms/FormArray#adding-or-removing-controls-from-a-form-array

**Comment by jelbourn** [comment]
@aikidave looking at this, I agree that there's a problem with the discoverability of "Usage notes" in the API reference. Unless you look at the table of contents and spot them at the bottom, they're very easy to miss.

**Comment by aikidave** [comment]
We're working on a fix to help increase the visibility of usage notes. Thanks for calling this out, @ychaikin!

**Comment by AndrewKushnir** [comment]
Closing this ticket since corresponding PR #40753 was merged.
