### ISSUE TITLE
Zone ES2015 distribution: patched toString returns wrong results for null or undefined

### ISSUE THREAD

**Issue by vannhi** [angular/angular#40750]
# 🐞 bug report

### Affected Package
The issue is caused by package zone.js@0.11.3

### Is this a regression?

Yes, it works well with ES5 distribution

### Description

`Object.prototype.toString.call(undefined)` returns **[object Window]** instead of **[object Undefined]**
`Object.prototype.toString.call(null)` returns **[object Window]** instead of **[object Null]**

## 🔬 Minimal Reproduction
https://codepen.io/htnfr/pen/bGBeNVe

## 🔥 Exception or Error
None

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.1.0
Node: 14.15.1
OS: win32 x64

Angular: 11.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.0
@angular-devkit/build-angular   0.1101.0
@angular-devkit/core            11.1.0
@angular-devkit/schematics      11.1.0
@schematics/angular             11.1.0
@schematics/update              0.1101.0
rxjs                            6.6.3
typescript                      4.1.3

</code></pre>

**Anything else relevant?**
It breaks a lib which uses toString

**Comment by JiaLiPassion** [comment]
@vannhi , this has been fixed here https://github.com/angular/angular/pull/40456, please wait for the next `0.11.4` release of zone.js
