### ISSUE TITLE
i18n localization/Merging with Xliffmerge not working in angular 10

### ISSUE THREAD

**Issue by coder123er** [angular/angular#40757]
Angular CLI: 10.2.0
Node: 12.14.1
OS: win32 x64

Angular: 10.1.6
... common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.10
@angular-devkit/build-angular     0.1001.7
@angular-devkit/build-optimizer   0.13.10
@angular-devkit/build-webpack     0.1001.7
@angular-devkit/core              10.2.0
@angular-devkit/schematics        10.2.0
@angular/animations               10.2.1
@angular/cdk                      10.2.6
@angular/cli                      10.2.0
@angular/http                     7.2.16
@angular/material                 7.3.7
@ngtools/webpack                  10.2.0
@schematics/angular               10.2.0
@schematics/update                0.1002.0
rxjs                              6.6.3
typescript                        4.0.5

Above mentioned is my configuration for Angular 10.

We have recently upgraded from Angular 7 to angular 10.
Our project supports 4 different locales and we were handling localization through below commands.

**"extract-i18n": "ng xi18n projectName --i18n-format xlf --output-path assets/locale --i18n-locale en && ng run projectName:xliffmerge"**

This was working fine in Angular 7. But now it has stopped working for us and gives error as

ERROR: language "C:\Users\centraluser\source\repos\FinxFrontend2\node_modules\@ngx-i18nsupport\ngx-i18nsupport\xliffmerge\xliffmerge" is not valid
ERROR: language "C:\Users\centraluser\source\repos\FinxFrontend2\node_modules\@ngx-i18nsupport\ngx-i18nsupport\xliffmerge\xliffmerge" is not valid
ERROR: i18nFile "messages.xlf" is not readable

Is there any other way to extract and merge already created xlf files.

**Comment by alan-agius4** [comment]
Hi @coder123er,

Without a reproduction it's hard to tell what is happening.  Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by petebacondarwin** [comment]
Please provide us with a concrete reproduction of your problem that we can run to diagnose the issue.
I am surprised by the error message you are receiving. See this line in xliffmerge:

https://github.com/martinroob/ngx-i18nsupport/blob/986552de86b4e61fe438003e3c479fdab2aefd64/projects/xliffmerge/src/xliffmerge/xliff-merge-parameters.ts#L328

I would expect your error message to be something like `Language en-Fr is not valid` but you appear to have the xliffmerge executable as the language, which suggests you have a problem with how you have configured xliffmerge??

**Comment by coder123er** [comment]
On executing below command 

----  ng xi18n angular --format=xlf --output-path assets/locale && ng run angular:xliffmerge

it gives below error ----

An unhandled exception occurred: Could not find the implementation for builder @ngx-i18nsupport/tooling:xliffmerge
See "C:\Users\CENTRA~1\AppData\Local\Temp\ng-r6zg82\angular-errors.log" for further details.

if something comes up your mind??

**Comment by petebacondarwin** [comment]
The problem you have there is this:

```
ng run angular:xliffmerge
```

I think you meant

```
npm run angular:xliffmerge
```

Currently you have not demonstrated any bug in Angular or its tooling. It seems like you have issues with how you are configuring the tools in your project. Please provide a runnable example that demonstrates a problem with Angular otherwise there is no action for us to take here.

**Comment by coder123er** [comment]
I am sorry for not updating you with runnable example at the moment. it seems like xliffmerge doesn't work in angular 10 anymore. I have generated the message.xlf file but now I need to merge it with other already generated localized files(es, fr, de) etc. 

Is there some other tool or command which I can use for the same??

**Comment by petebacondarwin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by coder123er** [comment]
The project we are working on goes as below

we have 4 different locales as messages.en.xlf, messages.fr.xlf etc...

on running  **ng xi18n angular --format=xlf --output-path assets/locale** this command

we get a new messages.xlf file.

How to merge new strings generated in messages.xlf file into messages.fr.xlf, messages.de.xlf, messages.es.xlf ??

earlier we were using **ng run angular:xliffmerge** command and it does the work in angular 7.

But now this command throws an error

**An unhandled exception occurred: Could not find the implementation for builder @ngx-i18nsupport/tooling:xliffmerge
See "C:\Users\CENTRA~1\AppData\Local\Temp\ng-r6zg82\angular-errors.log" for further details.**

Is there any alternative for the same to merge newly generated messages.xlf with all locale files.??

**Comment by coder123er** [comment]
We have also tried the following command

**"ng xi18n && xliffmerge"** as specified in link[]( https://www.gitmemory.com/issue/martinroob/ngx-i18nsupport/159/592059670)

But this is also not working for us?

Please suggest us some way to achieve the same with angular 10.
