### ISSUE TITLE
Create a "Directives Overview"or similar topic

### ISSUE THREAD

**Issue by aikithoughts** [angular/angular#40755]
# 📚 Docs or angular.io bug report

### Description
We do not have a concise topic that provides an overview of directives. Having one would reduce duplication of content in our other directive topics

### What's the affected URL?**
angular.io

### Reproduction Steps**
n/a

### Expected vs Actual Behavior**
n/a

**Comment by mgechev** [comment]
Closing for now since we'll be reevaluating our intro documentation with the upcoming standalone components and directives.
