### ISSUE TITLE
Alternative of Xliffmerge in angular 10 

### ISSUE THREAD

**Issue by coder123er** [angular/angular#40762]
[Link](https://github.com/angular/angular/issues/40757)

https://github.com/angular/angular/issues/40757

The above link specifies my problem and I need a solution to it.

**Comment by petebacondarwin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by MahimaFullStack** [comment]
We are facing same issue. @petebacondarwin Can you please suggest how to incorporate the strings in various languages which we have added language packs in UI.

There might be numerous applications which are using Internationalization in Angular and generating localized strings from development standpoint.

Can you please look into same and suggest approach.

**Comment by petebacondarwin** [comment]
If xliffmerge is no longer working then that is the project where an issue should be raised. Other than that, this still appears to be a support request, and I suggest that you try other channels like the Angular mailing list, Stackoverflow, the Angular Discord server etc. You could also try contacting the team at https://locl.app who are looking at tooling around this.
