### ISSUE TITLE
The behavior of ActivatedRoute's Observables are not documented (only emit when shallow equality check fails)

### ISSUE THREAD

**Issue by GenaANTG** [angular/angular#40769]
# 🐞 bug report 

## Description

I have two modules:

```ts
const routes: Routes = [
  { path: 'users', loadChildren: () => import('./modules/users/users.module').then(m => m.UsersModule) },
  { path: 'chats', loadChildren: () => import('./modules/chats/chats.module').then(m => m.ChatsModule) }
];
```

Those modules contains some routes with the resolvers. E.g:

#### users-routing.module.ts
```ts
const routes: Routes = [
  {
    path: '',
    component: UsersComponent,
    resolve: { 
      users: UsersResolver 
    },
    runGuardsAndResolvers: 'always', // <-- Resolver works fine, always
    children: [
      { path: 'create', component: UsersCreateComponent },
      { path: 'update/:token', resolve: { user: UserResolver }, component: UsersUpdateComponent },
      { path: 'details/:token', resolve: { user: UserResolver }, component: UsersDetailsComponent },
    ]
  },
];
```
#### users.resolver.ts

```ts
import { Injectable } from '@angular/core';
import { Resolve, ActivatedRouteSnapshot } from '@angular/router';
import { Observable } from 'rxjs';
import { take } from 'rxjs/operators';

import { UsersService } from '../services/users.service';

@Injectable({
  providedIn: 'root'
})
export class UsersResolver implements Resolve<any[]> {

  constructor(private usersService: UsersService) { }

  resolve(route: ActivatedRouteSnapshot): Observable<any[]> {
    return this.usersService.fetchUsers().pipe(take(1));
  }

}
```

When i navigate from the **children** path to the **parent** path e.g. `/users`, `UsersResolver` works fine, but the code listed below **won't works if a resolver returns an  empty  array**:

#### users.component.ts

```ts
ngOnInit(): void {
    // Doesn't fired up when a resolver returns an empty data.users array
    // But if i have at least one object in the array, then this code works fine
    this.route.data.subscribe(data => {
      this.users = data.users;
      console.log(this.users);
    });
}
```

The **important thing** is that resolver sends requests to the server, but `this.route.data.subscribe(...)` still doesn't works when resolver returns an empty array. A bug exists only between the **parent <-> children** navigation. Navigation between the modules and `this.route.data.subscribe(...)` with the resolvers works fine.

## Minimal Reproduction

Thanks to @destus90: https://stackblitz.com/edit/angular-ivy-9ajhzu?file=src%2Fapp%2Fmodules%2Fusers.service.ts

My previous report, same problem: #37365

## Expected behaviour

`this.router.data.subscribe(...)` should works if a resolver returns an empty array between the **parent <-> children** navigation.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.7
Node: 14.15.3
OS: linux x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.7
@angular-devkit/core         9.0.7
@angular-devkit/schematics   9.0.7
@schematics/angular          9.0.7
@schematics/update           0.900.7
rxjs                         6.5.3
</code></pre>

**Comment by GenaANTG** [comment]
Same problem with `router.navigate` / `router.navigateByUrl`. When i tried make redirect to the path like `/users` from the path `/users/create` resolver works but `route.data.subscribe(...)` doesn't works.

**Comment by GenaANTG** [comment]
The problem arises when you navigate between **parent <-> childs** routes. Between modules `route.data.subscribe(...)` works properly.

**Comment by GenaANTG** [comment]
I added a redirect from the resolver if an users array is empty, it's fixed some issues. But behaviour of the `route.data.subsrcibe(...)` is still very unexpectable and need a fix.

**Comment by destus90** [comment]
Don't see any issues with the framework. Runnable example works as expected (empty array is printed when resolver completes).
https://stackblitz.com/edit/angular-ivy-hxbmu1?file=src%2Fapp%2Fmodules%2Fusers.component.ts

**Comment by GenaANTG** [comment]
@destus90 

> Most important that the problem arises when you navigate between the parent <-> children routes and resolver returns an empty array. Between the modules a route.data.subscribe(...) works properly.

**Comment by destus90** [comment]
I found out that when a resolver returns the same value as in a previous call a subscriber for `route.data` is not notified.  Once I return some `Math.random()` value, my subscription is activated and a returned value is printed when navigating between `Parent <> Child` routes.
https://stackblitz.com/edit/angular-ivy-9ajhzu?file=src%2Fapp%2Fmodules%2Fusers.service.ts

**Comment by GenaANTG** [comment]
@destus90 Exactly! But you can try add some object to the array and `route.data.subscribe` will work, with same object in the array.

**Comment by GenaANTG** [comment]
My old report, same problem: #37365

**Comment by jelbourn** [comment]
@atscott is this working as intended, where the resolver emits only when the router sees the value as changed?

**Comment by atscott** [comment]
@jelbourn - Yes, this is working as designed. The data (and other properties on the snapshot) only emit when something has changed: https://github.com/angular/angular/blob/2a851c0924d09644014ad3bbe0608aa5fdf12652/packages/router/src/router_state.ts#L457-L459
@GenaANTG Can you describe your use-case for why you need this to emit duplicate values? Or is the issue just that this behavior is not documented?

**Comment by GenaANTG** [comment]
@atscott This works with the duplicate values. If a resolver returns at least one (and same) object in the array `route.data.subscribe(...)` will work. This bug is not about duplicates. Emitter should works in every case, e.g. i want to check if an array is empty and then do some logic in `route.data.subscribe(...)`, it's expected behaviour. If i want to check duplicates i can release my own logic, but emitter should works as expected. A lot of peoples have issues with this unexpectable behaviour.

**Comment by GenaANTG** [comment]
@atscott Second moment is that `shallowEquals` works only with the array with scalar types. if we change next line in an example above: 
`fetchUsers() {
    // return of([]);
    return of([Math.random()]); <-- Works, because it's new value every time.
}`

to this:
`
fetchUsers() {
    // return of([]);
    return of([ { a: 1 } ]); <-- Same object in the array, same data, but `route.data.subscribe(...)` **works** as expected.
}
`

This will work.

Next examples doesn't works as expected:

`fetchUsers() {
    return of([ ]);    <-- `route.data.subscribe(...)` do nothing because empty value. Why? Data is changed, why no emitting?

    return of([ 1 ]); <-- `route.data.subscribe(...)` do nothing because same value. Why? I can add my own logic to avoid duplicates.

}`

**Comment by atscott** [comment]
> If a resolver returns at least one (and same) object in the array route.data.subscribe(...) will work.

This isn't entirely true. The comparison is reference equality for each data value if they are objects and reference equality for each array value if the data is an array type. Two objects created at different times do not have the same reference.

Edit: It looks like you've found this as well after looking at `shallowEquals`.

> i want to check if an array is empty and then do some logic in route.data.subscribe(...), it's expected behaviour.  If i want to check duplicates i can release my own logic, but emitter should works as expected.

The expected behavior isn't currently documented. It _is_ working as it was designed and should be documented. I would still be curious what your specific use-case for this is. Note that you _can_ accomplish this by subscribing to the Router's navigation events and filter on `NavigationEnd`, then grab the current `data` from the snapshot.

We cannot change the behavior here as it would be a breaking change. I'm not convinced that this warrants an option for being configured either. As mentioned, there are existing options for achieving this that avoid an increased API surface. Certainly, the current behavior should be documented.

**Comment by GenaANTG** [comment]
`This isn't entirely true. The comparison is reference equality for each data value if they are objects and reference equality for each array value if the data is an array type. Two objects created at different times do not have the same reference.`

I understood this. By this way i can't use `route.data.susbcribe` properly because we have no emits for the scalar types and empty arrays. Somethting happens only with the objects (different references).

It's a wrong way. **We no need to check shallowEqual**. We can add our own implementation to avoid duplicates, if we want.

**Comment by atscott** [comment]
> It's a wrong way. We no need to check shallowEqual. Emitter should return fresh data in every case.
We can add our own implementation to avoid duplicates, if we want.

I understand, and if we were designing this from the ground up, we could consider the tradeoffs here. However, we cannot simply change the existing implementation without affecting every application that already uses the feature in its current state.

**Comment by GenaANTG** [comment]
@atscott I understand you :) It's breaking changes. Maybe in new major releases we can change this behaviour? Expectable, easy to understand and more clean way. This will helps to many peoples.

**Comment by GenaANTG** [comment]
I have many real-world projects on the angular and every time i've stopped with this behaviour.

**Comment by atscott** [comment]
> I have many real-world projects on the angular and every time i've stopped with this behaviour.

Have you tried subscribing to the navigation events instead? This should unblock you - https://stackblitz.com/edit/angular-ivy-5wtfjy?file=src%2Fapp%2Fmodules%2Fusers.component.ts


> @atscott I have next question: why emitter doesn't check `shallowEqual` for the parent routes and do this for the children routes? 

I'm not sure I follow this exactly. Is it shown in the reproduction? I would guess this is unrelated and actually has to do with component reuse or lack thereof.

**Comment by GenaANTG** [comment]
@atscott Thanks you! This works as expected. But now i should add new code-stub for this, instead of use one access point (`route.data.subscribe(...)`) to catch all emits. Here is a problem. Sure, i understand that i can fix it with different ways, but is not clean and expected like should be. Hope, that in new major releases you fix it.
