### ISSUE TITLE
FormGroupDirective reset and submit hosts conflicts

### ISSUE THREAD

**Issue by abarghoud** [angular/angular#40764]
# 🐞 bug report

### Affected Package
 The issue is caused by package @angular/forms

### Is this a regression?
I don't know

### Description

Using `[formGroup]` directive on a component that have an output called `reset` is causing conflicts with hosted [FormGroupDirective](https://github.com/angular/angular/blob/master/packages/forms/src/directives/reactive_directives/form_group_directive.ts#L53) reset and submit outputs.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-4mefoc?file=src%2Fapp%2Fapp.component.html

## 🔥 Exception or Error
The problem is when emiting on reset output of a component that's called with a formGroup in input the form is being reset.

**Comment by jelbourn** [comment]
@abarghoud this is working as intended; directive/component inputs and outputs are based purely on the string name, so creating a custom directive that emits an event with a duplicate name (even for native events like `reset`) will be captured by anyone listening for that event name. 

My personal suggestion is to avoid creating `@Output` names that match the names of any native events.

**Comment by abarghoud** [comment]
@jelbourn I see that it works as intended, but would it be possible to at least show a compilation warning to indicate that there  is a conflict of Inputs/Outputs, because it's not that obvious to know the outputs/inputs of other components/directives, and we are not supposed to do so.
