### ISSUE TITLE
Angular app-shell is not working when i use APP_INITIALIZER. How can i use app-shell with APP_INITIALIZER

### ISSUE THREAD

**Issue by naressaini1506** [angular/angular#40776]
Angular app-shell is not working when i use APP_INITIALIZER. How can i use app-shell with APP_INITIALIZER

**Comment by gkalpak** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
