### ISSUE TITLE
Adding Photosphere like VRview, Aframe, etc. in angular web app

### ISSUE THREAD

**Issue by luckyhero613** [angular/angular#40777]
I can't getting how to add the photosphere feature in my angular web application. I tried to simply add
`<div id="vrview></div>` 
but it didn't work.

After that I tried Aframe but it shows on whole screen and it neither shows the back button or cut button.

So, suggest me if there's any other way so that I can add photosphere in angular web application. As world is moving towards virtual world. so this feature of Angular will be highly beneficial for whole community and very user friendly.

**Comment by petebacondarwin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
