### ISSUE TITLE
API reference for HttpClient is unreadable

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#40780]
Page in question: https://angular.io/api/common/http/HttpClient#description

![image](https://user-images.githubusercontent.com/838736/107539937-56b7cb80-6b7a-11eb-8569-5cf70c4dc512.png)

The method signatures are so complex, with so many overloads, that the output is incomprehensible. I don't know what a good solution to this would be, but it's worth doing some brainstorming.

**Comment by dev054** [comment]
It was proposed in #38999, but as the PR got no attention, the author closed it.

**Comment by twerske** [comment]
Adding to adev tags too since it has been raised by other community members - IMO this issue persists and may be the underlying API type signature more than the docs.

**Comment by jelbourn** [comment]
IMO the formatting on angular.dev makes this much better- it's now at least _readable_, even if the end result is that the signatures are so complicated as to not be _useful_. I think we've reached the point of diminishing returns on trying to make the docs more readable/useful given that the actual signature is just so complicated. Changing the signature is also a big challenge in and of itself, since it's likely to be rather breaking at this point.
