### ISSUE TITLE
Incorrect code in "Observable HeroService" section of Angular Tour of Heroes

### ISSUE THREAD

**Issue by connorshea** [angular/angular#40788]
# 📚 Docs or angular.io bug report

### Description

Incorrect code in "Observable HeroService" section of Angular Tour of Heroes section "Part 4: Add services".

At least, as far as I can tell it's incorrect, or at the least not very obvious.

### What's the affected URL?**
https://angular.io/tutorial/toh-pt4#observable-heroservice

### Reproduction Steps**
Follow the steps up to that point in the guide, see that this code in `hero.service.ts` is referencing a `heroes` variable that does not exist:

```ts
getHeroes(): Observable<Hero[]> {
  return heroes;
}
```

### Expected vs Actual Behavior**
It _seems_ like the intent is to use `const heroes = of(HEROES);`, based on the docs immediately after the code snippet and the code snippets later in the page?

## 📷Screenshot

<img width="842" alt="Screen Shot 2021-02-10 at 1 47 10 PM" src="https://user-images.githubusercontent.com/2977353/107570245-8086e780-6ba6-11eb-804f-a0bb61901eff.png">

## 🔥 Exception or Error
<pre><code>
Error: src/app/hero.service.ts:14:12 - error TS2552: Cannot find name 'heroes'. Did you mean 'HEROES'?

14     return heroes;
              ~~~~~

</code></pre>

## 🌍  Your Environment

### Browser info
<!-- ✍️Is this a browser specific issue? If so, please specify the device, browser, and version. -->

### Anything else relevant?
<!-- ✍️Please provide additional info if necessary. -->

**Comment by petebacondarwin** [comment]
This is a regression in the docs due to the following commit https://github.com/angular/angular/commit/2a851c0924d09644014ad3bbe0608aa5fdf12652

The change did not take into account which regions were being referenced in the tutorial.

I'll prepare a fix.
