### ISSUE TITLE
dev-infra: check that param names in JsDoc match actual parameter names

### ISSUE THREAD

**Issue by AlexElin** [angular/angular#40808]
I think the Angular project should add/implement some rule to check that param names in JsDoc match actual parameter names.
This rule should fail a build if it finds the problems.
For example this could be done by adding lint rules (see the plugin https://github.com/gajus/eslint-plugin-jsdoc).

**Goal**: is to protect from issues like https://github.com/angular/angular/pull/40746

**Comment by petebacondarwin** [comment]
I assume that this is referring to the generation of the Angular docs rather than for Angular projects in general.

**Comment by petebacondarwin** [comment]
So I think this is actually a talk for dev-infra not docs-infra, since we would be setting up linting for the actual package sourec code.

**Comment by dylhunn** [comment]
This is an internal improvement for dev-infra. Closing this unless somebody wants to champion it.
