### ISSUE TITLE
To protect assets folder for the environment. 

### ISSUE THREAD

**Issue by AnilBhandare09** [angular/angular#40819]
Hi Team,

Could you please suggest me how  protect asset folder ? 

Angular-Version: 11
Description

I am able to access the HTML pages from the assets folder if the token is available or not.

If the token expires page to be redirected to the login page.
Access the asset folder when the token is present.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
