### ISSUE TITLE
Async pipe fails when using an observable from a ControlValueAccessor initial value

### ISSUE THREAD

**Issue by mdetweilerk** [angular/angular#40826]
# 🐞 bug report

### Description

When setting an observable from writeValue() of a ControlValueAccessor component, the DOM will not update when using an async pipe.  This only happens when the ControlValueAccessor is set with an initial value (setting it after load will result in the correct behavior).  

There are obvious work-arounds, such as not using an observable, or using a setTimeout.  However, it would be nice if this worked as expected without needing a work-around.

The aim of the code: while the code example below is simple and has no real point besides showing the bug, we need to set observables based on the incoming value.  In our specific use case, we alter the option lists of dropdowns based on the object passed in.  This bug also occurs if we have a form-control in our child and are piping off the .valueChanges of that form-control.

## 🔬 Minimal Reproduction

The following is the minimal code needed to reproduce the bug.  

````typescript
import { Component } from '@angular/core';
import { FormControl } from '@angular/forms';

@Component({
  selector: 'app-bug-show',
  template: `<app-child [formControl]="bla"></app-child>`,
})
export class BugShowComponent {
  bla = new FormControl('hi');
}
````
````typescript
import { Component } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import { Subject } from 'rxjs';
@Component({
  selector: 'app-child',
  template: '<p *ngFor="let val of array$ | async">{{val}}</p>',
  providers: [{
    provide: NG_VALUE_ACCESSOR,
    useExisting: ChildComponent,
    multi: true
  }]
})
export class ChildComponent implements ControlValueAccessor {
  public array$ = new Subject<any[]>();

  writeValue() {
    // Uncomment the setTimeout for this to work
    //setTimeout(() => {
      this.array$.next([ '1', '2', '3']);
    //}, 0);
  }

  registerOnChange(fn: any): void {
    throw new Error('Method not implemented.');
  }
  registerOnTouched(fn: any): void {
    throw new Error('Method not implemented.');
  }
  setDisabledState?(isDisabled: boolean): void {
    throw new Error('Method not implemented.');
  }
}
````

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.1.4
Node: 10.16.3
OS: win32 x64

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1101.4 (cli-only)
@angular-devkit/core         11.1.4 (cli-only)
@angular-devkit/schematics   11.1.4 (cli-only)
@schematics/angular          11.1.4 (cli-only)
@schematics/update           0.1101.4 (cli-only)
</code></pre>

**Comment by garrettld** [comment]
I threw your reproduction into StackBlitz: https://stackblitz.com/edit/form-control-issue

I've added a couple of console.log's that show the issue, which is that the writeValue method is called before the async pipe is initialized in the view. This means that the Subject has already emitted its value when the async pipe subscribes.

Changing the Subject to a ReplaySubject with a buffer size of 1 fixes the problem by replaying the initial value when the async pipe subscribes to it. You could use a BehaviorSubject instead if you had a default value (maybe an empty array, in this case).

This same problem would occur in your other example with formControl.valueChanges -- the async pipe is only going to "see" values that occur after it subscribes to the observable. You'd need to use the shareReplay operator or something similar in that case.

**Comment by mdetweilerk** [comment]
Thanks for finding reason for the issue and providing some additional ways to work around the issue!  I was hoping there would be a way for Async pipe to get that initial value, but as you point out, it would be impossible without a shareReplay operator on the observables consumed.
