### ISSUE TITLE
how consume https calls using httpclientmodule and add ca, keys,cert.pem files for api call

### ISSUE THREAD

**Issue by achyutannigeri7** [angular/angular#40820]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by JoostK** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by achyutannigeri7** [comment]
how access https calls in angular by including key, certificates. As we are using http requests using httpclientmodule. 
for reference:
function status(obj, server) {
    let res = "";
    const options = {
        hostname: server.ip_fqdn,
        port: parseInt(server.port),
        path: '/iothub/registration/Association/Registration/Status',
        method: 'POST',
        key: fs.readFileSync('../../Certificates/Demo.key.pem'),
        cert: fs.readFileSync('../../Certificates/Demo.crt.pem'),
        ca: fs.readFileSync('../../Certificates/iothub-ca.ca.chain.crt.pem'),
        headers: {
            'api-version': '1.0',
            'accept': 'application/json',
            'Content-Type': 'application/json'

        },
    }

    const req = https.request(options, (res) => {
        console.log(`statusCode: ${res.statusCode}`)

        res.on('data', (d) => {
            res = JSON.parse(d);
            // process.stdout.write(d)
            //console.log(res.registrationInfo.regStatus + "\n")
            console.log(JSON.stringify(JSON.parse(d)));
            if(res.statusCode==204){
                self.postMessage(['Device details not found']);
            }
            self.postMessage([res.registrationInfo.regStatus, res.registrationInfo.nameTag]);
        })
    })

    req.on('error', (error) => {
        console.error(error)
        self.postMessage(['Unable to connect'])
    })

    req.write(obj)
    req.end()
}

**Comment by mlc-mlapis** [comment]
@achyutannigeri7 Angular means SPA client-side application and not NodeJS server-side code.
