### ISSUE TITLE
Router Proposal: adopt convention for route alias

### ISSUE THREAD

**Issue by btford** [angular/angular#4083]
I propose that we adopt an enforced convention of naming convention were route names are TitleCase: `MyRoute` rather than camelCase `myRoute`.

I think it helps distinguish between URLs and the DSL. Consider:

```
@RouteConfig([
  { path: '/foo', component: FooCmp, as: 'MyRoute' }
])
class MyCmp
```

~~~I also think this goes nicely with #3496.~~~

**Comment by mhevery** [comment]
`MyRoute` is not found in the example provided, not sure what you are referring to.

**Comment by btford** [comment]
Updated

**Comment by IgorMinar** [comment]
lgtm

**Comment by johnpapa** [comment]
I the changelog and error message it says CamelCase. I think you meant TitleCase

`router: enforce convention of CamelCase names in route aliases (5298eb0), closes #4083`

@btford

**Comment by jessegood** [comment]
Nitpick, but isn't the correct terminology `PascalCase`? `Title Case` I thought has spaces in between words.

**Comment by johnpapa** [comment]
PascalCase is not known everywhere, I found. So I have been calling it UpperCamelCase

**Comment by jessegood** [comment]
Now that you mention it, I've only seen `PascalCase` on MSDN or other MS-related documentation, although we are using Typescript and the [TypeScript Guidlines](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines) use it.

**Comment by ericmartinezr** [comment]
Now that we have to write aliases `LikeThis`,  I ended writing a link this way

```
<a href="#" [router-link]="['./Fb/Login']">...</a>
```

It just doesn't feel natural :/

**Comment by basvandenheuvel** [comment]
This should have been added to the breaking changes?
