### ISSUE TITLE
@angular/compiler duplicate nodes on elements with structural directive and bound properties

### ISSUE THREAD

**Issue by detljh** [angular/angular#40838]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler

### Is this a regression?

 Using the ASTExplorer parser 10.1.4 still has the issue

### Description

 For an element with both a structural directive and bound properties, there will be duplicate bound property nodes.

```
<div
  *ngIf="veryTrue$ | async"
  [disabled]="disabled$ | async"
>
</div>
```

## 🔬 Minimal Reproduction

 
You can see the duplication of the `disabled` bound property in
https://astexplorer.net/#/gist/3de2535c3ec6b85e77a038f41adf0d3e/95f0531b38bf25d2768760f3629e4b64c79802df

**Comment by JoostK** [comment]
This is done on purpose, see

https://github.com/angular/angular/blob/72a00dcc6b25d2cb0b90e09922314e03a1f54e29/packages/compiler/src/render3/r3_template_transform.ts#L205-L208

**Comment by petebacondarwin** [comment]
Also, could explain why this is a problem for you @detljh ?

**Comment by detljh** [comment]
I'm creating custom angular eslint rules and when I use BoundAttribute as the selector in this scenario, it will match the bounded property twice creating two errors

**Comment by petebacondarwin** [comment]
Why are you linting the code generated by the Angular compiler?

**Comment by detljh** [comment]
I'm using the @angular-eslint/template-parser for the custom rules which uses the Angular compiler

**Comment by petebacondarwin** [comment]
I see that you have opened an issue on that eslint plugin too: https://github.com/angular-eslint/angular-eslint/issues/336

**Comment by petebacondarwin** [comment]
Since the AST that is being generated is by-design, it is up to the eslint plugin to accommodate that. I have commented accordingly on that issue.

Closing as there is no action to be done here.
