### ISSUE TITLE
docs: additional package.json for strict mode

### ISSUE THREAD

**Issue by AlexElin** [angular/angular#40841]
### Description

The [docs ](https://angular.io/guide/file-structure#application-source-files)states

> If you create an application using Angular's strict mode, you will also have an additional package.json file in the src/app directory. For more information, see Strict mode.

But I don't see such file after creating project in a strict mode.
Also https://angular.io/guide/strict-mode#strict-mode says nothing on additional `package.json`
Is the docs incorrect? Or I missed smth?

## 🔬 Minimal Reproduction

Create new project via `ng new <my-project> --strict`
See whether `src/app` contains additional `package.json`

**Comment by petebacondarwin** [comment]
This documentation block was introduced in https://github.com/angular/angular/commit/cb566add3cfcd0e8a7b5dc339b3678c9636705a7.
Perhaps it was never implemented or subsequently removed from the actual generated project?
Maybe @aikidave, @alan-agius4 or @clydin know more?

**Comment by petebacondarwin** [comment]
Further, I see here https://github.com/angular/angular-cli/commit/1559ad6ffbe9a49e6ea05977ae8f9d15f5e41956 that the schematic does have an option to add this package.json.

**Comment by petebacondarwin** [comment]
Ahah! But it was removed here https://github.com/angular/angular-cli/commit/ae73e44b2a27bd5e65ca58101e69ad2b93c50d80

So I think we just need to update the docs.

**Comment by alan-agius4** [comment]
The extra package.json, is no longer generated in v11+, hence the reference to that file was also removed from the documentation.

In version 12, strict mode is on opt-out bases, so we should also update this document to reflect that.

**Comment by alan-agius4** [comment]
I going to assign this to me for the time being. If anyone want to take this task before I get to this. Please feel free to do so.

**Comment by nirmal-mobiquity** [comment]
@alan-agius4 need help here for document update only right ?

**Comment by alan-agius4** [comment]
@nirmal-mobiquity, feel free to open a PR. Indeed it’s a docs only change.

**Comment by iRealNirmal** [comment]
thanks @alan-agius4 let me take this task
