### ISSUE TITLE
Angular query params when refreshing Page

### ISSUE THREAD

**Issue by IvanLoPes** [angular/angular#40859]
0

I have an issue, that is struggling me. Scenario - Page A and Page B:

In Page A I have a button that navigate to Page B adding a query params

this.router.navigate(['asignaturas', 2, 'datosgenerales'], {queryParams: {edit: false}}); 

Page B is loaded correctly. BUT if I click refresh in browser i got an error

ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'asignaturas/2/datosgenerales%3Fedit%3Dfalse'
Error: Cannot match any routes. URL Segment: 'asignaturas/2/datosgenerales%3Fedit%3Dfalse'
The URL is adding the query params also. That I wouldn't like to.

I tried to check when is page reload with this code and recreate the navigation
 ngOnInit() {
    this.browserRefresh = browserRefresh; // Give true | false if is page refresh
    if(this.browserRefresh) {
      this.router.navigate(['asignaturas/2/datosgenerales'], {queryParams: {edit: true}});
    }
Even trying to recreate the url, it still throw me the error. It there a way to fix it, or ignore the query params

**Comment by petebacondarwin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you believe that that this is actually a bug in the framework, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template, including providing a clear reproduction of the issue that we can debug.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
