### ISSUE TITLE
core.js:12853 Can't bind to 'ngIf' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by JainSia** [angular/angular#40850]
Hi 

I am using Angular 9.

and I am having a use case of loading dynamic components 

In one of my component, I am getting the warning 

**core.js:12853 Can't bind to 'ngIf' since it isn't a known property of 'div'**

I have included **commonModule** in my app.module.ts

![image](https://user-images.githubusercontent.com/35490075/107907905-dbd82180-6f7a-11eb-897d-a158ba8ebbd0.png)

This is my component where I am using ngIf

![image](https://user-images.githubusercontent.com/35490075/107908004-1641be80-6f7b-11eb-85b6-dedf15389026.png)

and here is the object I am getting in my above component

![image](https://user-images.githubusercontent.com/35490075/107908130-4f7a2e80-6f7b-11eb-9f00-443918ecd156.png)

As I have seen many posts and got solution like Import Common Module I did it but my problem is still the same

**Comment by PrathameshAshra** [comment]
Assign a new variable a false/ true value and check if your *ngIf is working or not, if its working than its issue with the field.otherOptionAvailable.

**Comment by lazarljubenovic** [comment]
This is neither a bug report or feature request. This GitHub issue tracker is not suitable for support requests. Please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

**Comment by JainSia** [comment]
> Assign a new variable a false/ true value and check if your *ngIf is working or not, if its working than its issue with the field.otherOptionAvailable.

No, It's not working. And this field is an array actually

**Comment by JainSia** [comment]
> This is neither a bug report or feature request. This GitHub issue tracker is not suitable for support requests. Please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

ok

**Comment by petebacondarwin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
