### ISSUE TITLE
Updating input value works incorrectly

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular#40871]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 I don't know

### Description

 I created simple components and added two identical components to one page and tried to update a value. But how to result after updating one of them I see that second component also has updated value 

## 🔬 Minimal Reproduction

[Example to reproduce](https://codesandbox.io/s/frosty-kowalevski-gx88g)

1. Click on the first button ---> you will see that value is updated
2. Click in the second button ---> you will see that value has already been updated

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

angular@11.2.0
</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
The example you provide appears to be using ViewEngine.
Here is an example on Stackblitz which uses Ivy and appears not to display this problem : https://stackblitz.com/edit/angular-ivy-vl4xsd?file=src/app/app.component.html

**Comment by dxvladislavvolkov** [comment]
@petebacondarwin  I didn't understand how it was fixed. What do I need to do in my project to fix the issue?

**Comment by petebacondarwin** [comment]
Do you have Ivy enabled in your project?

**Comment by JoostK** [comment]
This was fixed for Ivy in #33705.

**Comment by petebacondarwin** [comment]
Closing as this is only a problem in ViewEngine, which is deprecated. The solution is to update your application to run under Ivy compilation and rendering.
