### ISSUE TITLE
Form controls aren't cleaning up their value change listeners.

### ISSUE THREAD

**Issue by snotmare** [angular/angular#40877]
Hello!

I am using angular 10.1.1. I think you have a bug related to form_group_directive.ts. When you add a control, you eventually register to listen to value changes, but you aren't removing those listeners when the directive is destroyed. Here are some details...

When the addControl() method is called, it calls setUpControl()...
```
  addControl(dir: FormControlName): FormControl {
    const ctrl: any = this.form.get(dir.path);
    setUpControl(ctrl, dir);
    ctrl.updateValueAndValidity({emitEvent: false});
    this.directives.push(dir);
    return ctrl;
  }
```
This calls setUpModelChangePipeline() which in turn calls control.registerOnChange().

Later in form_group_directive.ts when the removeControl() method is called, it simply calls removeDir() from shared.ts. This simply splices the element out of the array, but never removes the on change listeners from before.

We noticed this error because we have custom controls that use the writeValue() method to initialize the component. This method was being called an increasing number of times over the life of our app.

In our case, we have a form with controls. We reset the form with an object of data. We later reset the form with another object of data. While the 2nd object of data is being loaded, we hide the form on the page using *ngIf. Once the data is loaded, we show the form again with new data. It seems that this re-displaying of the form is causing the controls to re-register for changes. This is fine, except the old ones were never cleaned up.

I hope that is enough information for you to find the error.

**Comment by AndrewKushnir** [comment]
Hi @snotmare, thanks for reporting the issue and referencing specific parts of code.

I believe the problem was resolved by PR #39235 (changes are available in v11). The `removeControl` function now includes the call to `cleanUpControl`, which reverts the setup performed by the `setUpControl` function.

Please try upgrading to the most latest version of Angular and feel free to reopen this issue if the problem still exists.

Thank you.
