### ISSUE TITLE
Style Guide still recommends Codelyzer which is being deprecated

### ISSUE THREAD

**Issue by bcarson** [angular/angular#40903]
# 📚 Docs or angular.io bug report

### Description

The Style Guide still recommends Codelyzer which is being deprecated in v11 according to blog.angular.io (11/12/20).

### What's the affected URL?**
https://angular.io/guide/styleguide > Appendix > Codelyzer (Style A-01)

## 📷Screenshot

![Screen Shot 2021-02-18 at 1 32 34 PM](https://user-images.githubusercontent.com/1154098/108357538-dafaf600-71ed-11eb-91da-19ff57348828.png)

![Screen Shot 2021-02-18 at 1 31 59 PM](https://user-images.githubusercontent.com/1154098/108357405-af780b80-71ed-11eb-8f9c-e07df14fd97d.png)

**Comment by cesperian** [comment]
@petebacondarwin I'll take this one. 

Should the reference be removed? Or just ammended with the deprecation warning in above screenshot?...

**Comment by petebacondarwin** [comment]
I think you can just remove it, since it was just a recommendation.
