### ISSUE TITLE
Destroy of components trigger events

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular#40906]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 I don't know

### Description

 I found that when I destroy a component some events triggered. Some of them have emitters and as to how result I get some strange behavior.

## 🔬 Minimal Reproduction

 [My example](https://codesandbox.io/s/compassionate-ardinghelli-eexu5)
 
 I have a simple input component and I try to detect changes using blur (or change) event.
Follow the next step to reproduce:
1. Click to input.
2. Waiting for 5 sec.
3. You will see a console.log in devtools that the value is changed. But why? Component was destroyed
Why did the blur event trigger? It seems like a bug

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by davudk** [comment]
I don't think this is related to Angular since the `blur` event is raised when the element is removed from the DOM.

Semantically this seems to make sense since the event is raised when the focus has been removed from the element. Removing the element from the DOM implies that the focus is removed from the element.

**Comment by dxvladislavvolkov** [comment]
what about a change event?
Try to type something and then wait
https://codesandbox.io/s/late-browser-erxoy?file=/src/app/custom.component.ts

**Comment by indraraj26** [comment]
I don't think so Angular is going to support it. Since we have same behavior even without angular
Link : https://jsbin.com/hehuvecaqa/edit?html,js,console,output

**Comment by jelbourn** [comment]
Yes, this behavior is a native browser behavior that isn't related to Angular.
