### ISSUE TITLE
Can't bind to ngClass, ngModel since it isn't a known property of div only for production build

### ISSUE THREAD

**Issue by suraj740** [angular/angular#40921]
Is this a regression?
Yes, the previous version in which this bug was not present was: 8
Description
When upgrading from Angular 8.0 to Angular 11 using the instructions on the upgrade page, I got the following exception

Can't bind to ngClass, ngModel since it isn't a known property of div,
Same error is coming for all templates.

ng serve -> works fine
ng build -> works fine
ng build --prod -> doesnt work(getting above errors)

**Comment by petebacondarwin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
