### ISSUE TITLE
Question: Why main.js bundle size decreased 👍  

### ISSUE THREAD

**Issue by elvirdolic** [angular/angular#40938]
Hi,

we have a quiet big nx monorepo with a lot of apps. Since upgrade to angular 12.2.1 from 11.1.1 the main.js of all our apps is now in average 200-300kb less than before.

I checked all release notes and blog posts about the latest version but there is no relevant information that something was improved regarding bundle size.

Bundle size build before and bundle size of main.js after upgrade of some of the apps.
![image](https://user-images.githubusercontent.com/17769458/108696456-daba6d80-7501-11eb-864c-3c2f521dc08d.png)

**Comment by alan-agius4** [comment]
Transferring to the FW repo, maybe someone with better knowledge about what changes caused this.

**Comment by jelbourn** [comment]
In general we're always working to decrease the size of the framework- I'm glad to hear you saw a significant improvement recently. We wouldn't be able to know which change exactly impacted your app the most, but you can always check out the changelog to see the work we've done in any given release.
