### ISSUE TITLE
Support discriminating union type in template. (e.g. switch-case)

### ISSUE THREAD

**Issue by y0nd0** [angular/angular#40934]
# 🚀 feature request

### Relevant Package
`@angular/core`

### Description
At first at all, check out the TypeScript docs [discriminating-unions](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions) (the last section about switch-case).

It seems that Angular cannot resolve deeper types in template. For example union types. In my case in a switch case template.

In TypeScript (ts), the type is detected after e. g. `if` or `switch` conditions. But let me explain the issue in some code. 

**model.ts**

```ts
interface MyBase {
  id?: string;
}

interface MyText extends MyBase{
  type: 'text';
  value: string;
}

interface MyNumber extends MyBase{
  type: 'number';
  value: number;
  unit?: string;
}

export type MyType = MyText | MyNumber;
```

**component.ts**

```ts
class MyComponent {
  items: MyType[];
}
```

**component.html**

```html
<ng-container *ngFor="let item of items" [ngSwitch]="item.type">
  <ng-container *ngSwitchCase="'text'">
    <p>{{ item.value }}</p>
  </ng-container>
  <ng-container *ngSwitchCase="'number'">
    <p>{{ item.value }} {{ item.unit }}</p> <!-- Red line. `unit` does not exist. -->
  </ng-container>
</ng-container>
```

It claims that unit does not exist. But in this case, it's sure what item has type `'number'`.
I also tried a type map - which also works great in TypeScript, but not in Angular. In TypeScript you can find such type map in methods like `document.createElement()`. Example:  

**model.ts**

```ts
interface MyTypesMap{
  text: MyText;
  number: MyNumber;
}

export const getItemAs = <K extends keyof MyTypesMap>(
  item: MyType,
  _type: K
): MyTypesMap[K] => {
  return item as MyTypesMap[K];
};
```

**component.ts**

```ts
class MyComponent {
  getItemAs = getItemAs;
}
```

**component.html** (pseudo, it's about declare variable.)

```html
<ng-container *ngFor="let item of items" [ngSwitch]="item.type">
  <ng-container *ngSwitchCase="'text'; item = getItemAs (item, 'text')">
    <p>{{ item.value }}</p>
  </ng-container>
  <ng-container *ngSwitchCase="'number'; item = getItemAs (item, 'number')"">
    <p>{{ item.value }} {{ item.unit }}</p>
  </ng-container>
</ng-container>
```

An *alternative* could be: Allow type casting or variable declaring on the fly in template to either cast directly in template or overwrite the variable (`item`) with another value from a method in component which returns the correct type. But in this case, it would be awesome if genric type map works (like described above). But the very best solution is to detect the type like TypeScript do. Maybe the following topic helps you to find a solution: `type-guards` Switch-case could use [type-guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards). But I'm not sure how Angular works in source code.

Again, in TypeScript it works:

```ts
switch(item.type) {
  case 'text': console.log(`${item.value}`); break;
  case 'number': console.log(`${item.value} ${item.unit}`); break;
}
// No errors.
```

## Setup Info

Some infos about my setup. It's a simple Angular app (Ionic 5) with strict mode: 

**tsconfig.json**

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": ["es2018", "dom", "esnext"],
    "esModuleInterop": true,
    "strict": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
```

Angular 11.0.x

Feel free to transform this to a bug. 
Let me know if you need more infos.

**Comment by JoostK** [comment]
Thank you for putting this together. This is indeed a current limitation of the template type checking capabilities, for which there is existing issue #20780; I'll close this as a duplicate.
