### ISSUE TITLE
`Error: Failed to find exported name of node` reported from pkg bundled by `ng-packagr`

### ISSUE THREAD

**Issue by JounQin** [angular/angular#40959]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

Yes, `@angular/compiler-cli@10.21` with `ng-packagr@10.1.2` works

### Description

 

[`@alauda/common-snippet`](https://www.npmjs.com/package/@alauda/common-snippet) is [bundled](https://unpkg.com/browse/@alauda/common-snippet/) by `ng-packagr`, there is no error when bundling itself, but when using it in project, it can not be handled correctly by `ngcc`.

We've just upgrading `@angular/core` and `ng-packagr` to `11.0` recently.

## 🔬 Minimal Reproduction

https://github.com/JounQin/test/tree/angular

run `yarn start`

## 🔥 Exception or Error
<pre><code>

Compiling @alauda/common-snippet : es2015 as esm2015
Error: Error on worker angular/angular-cli#1: Error: Failed to find exported name of node (class UtilsModule {
}) in '/Users/JounQin/Workspaces/Local/test/node_modules/@alauda/common-snippet/fesm2015/alauda-common-snippet.js'.
    at Object.findExportedNameOfNode (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/find_export.js:36:19)
    at LogicalProjectStrategy.emit (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:233:38)
    at ReferenceEmitter.emit (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:72:44)
    at Object.toR3Reference (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/util.js:249:31)
    at NgModuleDecoratorHandler._toR3Reference (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:416:31)
    at /Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:195:72
    at Array.map (<anonymous>)
    at NgModuleDecoratorHandler.analyze (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:195:38)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:345:40)
    at analyze (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:296:58)
    at ClusterMaster.onWorkerMessage (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:195:27)
    at /Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:55:95
    at ClusterMaster.<anonymous> (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:293:57)
    at step (/Users/JounQin/Workspaces/Local/test/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/JounQin/Workspaces/Local/test/node_modules/tslib/tslib.js:124:57)
    at /Users/JounQin/Workspaces/Local/test/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/JounQin/Workspaces/Local/test/node_modules/tslib/tslib.js:113:16)
    at EventEmitter.<anonymous> (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:287:32)
    at EventEmitter.emit (events.js:314:20)
An unhandled exception occurred: NGCC failed.
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 11.2.1
Node: 12.20.0
OS: darwin x64

Angular: 11.2.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.1
@angular-devkit/build-angular   0.1102.1
@angular-devkit/core            11.2.1
@angular-devkit/schematics      11.2.1
@angular/cdk                    11.2.1
@angular/cli                    11.2.1
@schematics/angular             11.2.1
@schematics/update              0.1102.1
rxjs                            6.6.3
typescript                      4.1.5
</code></pre>

**Anything else relevant?**

**Comment by JounQin** [comment]
@alan-agius4 I tried last version of `@alauda/common-snippet` with latest `@angular/compiler-cli`, it compiles successfully, what means the bundled content from `ng-packagr` is the problem. I don't know is it correct.

**Comment by JounQin** [comment]
After downgrading `ng-packagr` to `10.1.2` it just works correctly.

@alan-agius4 Should this issue be moved to `ng-packagr`'s repo instead?

**Comment by alan-agius4** [comment]
Had a quick look at this, it appears that a collision is being caused when generating the FESM, Notice the following export for `ts-essentials/dist/types` In https://unpkg.com/browse/@alauda/common-snippet@2.7.0/fesm2015/alauda-common-snippet.js

```ts
export { ANNOTATIONS, ANONYMOUS_APIS, API_GATEWAY, APP_ENTRY, AccountMenuComponent,
 AccountMenuModule, ArrayFormTableComponent, ArrayFormTableFooterDirective, ArrayFormTableHeaderDirective, ArrayFormTableModule, ArrayFormTableRowControlDirective, ArrayFormTableRowDirective, 
ArrayFormTableZeroStateDirective, Bracket, CLUSTER, CODE_KEY, CREATION_TIMESTAMP, 
CREATOR, ContentDirective, DATA, DATE_FORMAT, DATE_TIME_FORMAT, DEFAULT_CODE_EDITOR_OPTIONS, DEFAULT_ERROR_GUARD_URL, DEFAULT_REASON, DESCRIPTION, DISPLAY_NAME, 
DOWNGRADE_WATCH_ENABLED, DateTimePipe, DependencyType, DescriptionDirective, DrawerComponent, DrawerModule, DrawerService, EMPTY, FALSE, FIELD_NOT_AVAILABLE_PLACEHOLDER, 
FeatureGateDirective, FeatureGateService, FeatureGuard, FeatureStage, FieldNotAvailablePipe, FieldSetColumnComponent, FieldSetColumnGroupComponent, FieldSetGroupComponent,
 FieldSetItemActionDirective, FieldSetItemComponent, GET_CURRENT_CLUSTER, GuardStatus,
 HeaderNotifyComponent, HeaderNotifyModule, HelpMenuComponent, HelpMenuModule, ID_TOKEN_KEY, K8sAnnotationPipe, K8sCreationTimestampPipe, K8sCreatorPipe, K8sDescriptionPipe,
 K8sDisplayNamePipe, K8sLabelPipe, K8sNamePipe, K8sNamespacePipe, K8sProjectPipe, K8sResourceAction, K8sUnionDisplayNamePipe, K8sUpdatedAtPipe, K8sUtilService, LABELS,
 LoadingMaskComponent, METADATA, MODULES_API, NAME, NAMESPACE, NOTIFY_ON_ERROR_HEADER, NOTIFY_ON_ERROR_HEADERS, NOT_NOTIFY_ON_ERROR_HEADERS, ObservableInput, OperationDirective, PROJECT, PUBLIC_NAMESPACE, PageGuardComponent, PageGuardModule, 
ProjectGuard, ProjectNamespaceGuard, PurePipe, REASON_MAP, REFRESH_TOKEN_KEY,
 Reason, RelativeTimePipe, SPACE, 
StandardDatePipe, StandardTimePipe, TEMPLATE_OPTIONS, TOKEN_BASE_DOMAIN, TOKEN_BASE_HREF, TOKEN_CALLBACK_API, TOKEN_GLOBAL_NAMESPACE, TOKEN_INFO_API, TOKEN_LOGIN_API, TOKEN_NON_ADMIN_REDIRECT_PATH, TOKEN_REFRESH_API, TOKEN_RESOURCE_API_PREFIXES, TOKEN_RESOURCE_DEFINITIONS, TRUE, TimeService, TranslateDirective, 
TranslateMatchDirective, TranslateTextDirective, TranslateView, UPDATED_AT, UtilsModule, ValueHook, WORKSPACE_PARAMS, WidgetModule, ZeroStateComponent, anonymousApis, appEntry, baseDomain, catchPromise, codeKey, createRecursiveFilter, filterTrees, findPath, firstPath, getBaseHref, 
globalNamespace, handlePixel, idTokenKey, ifExist, isAbsoluteUrl, mapTrees, modulesApi, noop, parseJSONStream, publishRef, reduceTrees, refreshTokenKey, resourceApiPrefixes, resourceDefinitions,
 rowBackgroundColorFn, setNode, skipError, toKeys, tokenCallbackApi, tokenInfoApi, tokenLoginApi, 
tokenNonAdminRedirectPath, tokenRefreshApi, withLoadState, wrapText, ɵ1 } from 'ts-essentials/dist/types';
```

It looks like [Rollup](https://rollupjs.org/) is attached every export to `ts-essentials/dist/types`. I believe this was solved in later versions of Rollup, can you please try to using `ng-packagr@latest`.

This can be closed and if needed a new issue should be opened in the ng-packagr repo (since a transfer of issue cannot be done across organisations). If the problem persists after update ng-packagr, please file an issue in their issue tracker including a minimal reproduction of the library.

**Comment by JounQin** [comment]
I tried all latest versions of `rollup` and `ng-packagr`, it occurred still.

Maybe that's a rollup bug because I'm exporting a same identifier named `ValueOf` which is exported from `ts-essentials/dist/types` too.

I'll try to reproduce it and report to rollup.
