### ISSUE TITLE
Route page is not reloaded

### ISSUE THREAD

**Issue by dolphinsd** [angular/angular#40957]
Version 11.2.1
It worked fine in version 10.x

We use routes to load page dynamically, here is an example
https://www.rvseasy.com/about/resource/mihaela-living-large-with-popup-penthouse

There is recommendation for Rafael, if you click on it, load the same route but different page. 

The problem on OnInit is not called on component or children, it is a different map of the route, it used to work.

Here is our routing code
  RouterModule.forChild([
            {
                path: '',
                component: ViewComponent,
                children: [
                  {
                        path: 'resource/:url',
                        component: ViewResourcePageComponent,
                        data: { showClose: false, showBack: true }
                    },

**Comment by dolphinsd** [comment]
Attached is a console log, while router find a route, a component never loaded again. Route changes without reloading component.
[localhost-1614099793441.log](https://github.com/angular/angular/files/6030588/localhost-1614099793441.log)

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by dolphinsd** [comment]
@atscott , we put a workaround to listen to change in route params with subscribe.
You might want to document that components for a route are not reloaded when route is matched via url params like this
path: 'resource/:url',

**Comment by atscott** [comment]
@dolphinsd - Based on your description, everything seems to be working as expected. Without a reproduction, there's no more investigation that can be done.
From the small code snippet you provided, it looks like you probably have a `loadChildren` route somewhere else. There was a bug in the router which reloaded this configs for `**` `loadChildren` routes every time and would also prevent correct component reuse. https://github.com/angular/angular/commit/4906bf6a50f307fb69080d276c3b91a60ba7fbae#diff-c4958945d247eb3842b4117e948efc54b776ad843626c0adca169e5d416582fb. This is now the correct behavior.
If you want your components to _not_ be re-used, you need to provide your own [RouteReuseStrategy](https://angular.io/api/router/RouteReuseStrategy) and implement some custom logic in `shouldReuseRoute`.
