### ISSUE TITLE
Add NgStyle to CORE_DIRECTIVES

### ISSUE THREAD

**Issue by mlynch** [angular/angular#4096]
`NgStyle` is not exported in the `CORE_DIRECTIVES` array. However, it's being referenced in the `angular/directives.ts` file. Can this be added to the array?

https://github.com/angular/angular/blob/f14b212dc997a021d874ac0fc3e0e4d57a734fe4/modules/angular2/src/core/directives.ts#L63

**Comment by PascalPrecht** [comment]
@mlynch Fancy a PR?
