### ISSUE TITLE
ANGULAR 11 some items return error Cannot read property 'provide' of undefined

### ISSUE THREAD

**Issue by harleenarora** [angular/angular#40961]
Hi, 

I have export all service files in one index.ts and import is component and module like that::

`import { IpAddressServ, LoadrServ, PageTitleServ } from './Services';`

Some time return error::

```
`core.js:6150 ERROR TypeError: Cannot read property 'provide' of undefined
at resolveProvider$1 (core.js:20883)
at resolveProvider$1 (core.js:20877)
at providersResolver (core.js:20864)
at Object.definition.providersResolver (core.js:21111)
at instantiateRootComponent (core.js:10071)
at createRootComponent (core.js:12389)
at ComponentFactory$1.create (core.js:25072)
at ViewContainerRef.createComponent (core.js:23112)`
```

**Comment by petebacondarwin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
