### ISSUE TITLE
event errors in firefox

### ISSUE THREAD

**Issue by amirhosein5858** [angular/angular#40971]
hi,i create an angular app and its works in chrome .
its have some checkboxes and they are not working
in console i see this errors:
ERROR TypeError: event.path is undefined
also when i ckick on buttons ifaced this error again!
any solutions?
thanks

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
