### ISSUE TITLE
HostBinding not working the way it used to Angular 11.2

### ISSUE THREAD

**Issue by tcoz** [angular/angular#40979]
I'm posting this as a non-template issue, as I suspect this isn't a bug etc, it's just one of those "you probably never should have done it this way, so crying about it now isn't very compelling, but still, lots of people did do it this way so here's a note on it," things. 

I work on a portfolio of apps where I've seen this quite a bit:

@HostBinding(class.MyComponent) true;

It always had code smell to me, if felt like a potential no-op. But it worked as expected so that was that; leave it alone. 

Until Angular 11.2. Now that class does not get applied to the host. There's just nothing there, the element has no class. I roll back to 11.0.9, everything works, you see the class on the element in the inspector, etc. I update to 11.2, it breaks. 

This fixes it:

@HostBinding(class.MyComponent) get hostclass() { return 'true' };

(This is how the decorator is doc'd in Angular.io as well). 

I can kind of surmise why this might be the case, being as I was always suspicious of how it was being done originally. This is just a note that perhaps something needs to be made visible insofar as a change that makes reading and applying this information more strict, and maybe it'll save some poor soul out there a headache.

**Comment by JoostK** [comment]
The prior behavior was a bug that was fixed in #40233. The fix you describe is indeed the expected way to achieve the desired effect. I'm not sure how widespread this situation is and whether it should be documented, let alone where it should be documented.

**Comment by AndrewKushnir** [comment]
@tcoz thanks for creating this ticket and sharing the solution. As Joost mentioned this was working incorrectly before and was resolved in #40233. This fix was included into Angular compiler since v11.1.0 and it's being used in Google's codebase since early Jan. I will close this ticket for now, if we receive more feedback we can always reopen it and consider adding extra docs to cover this behavior. Thank you.

**Comment by Airblader** [comment]
This is also only an issue in apps which don't use noImplicitAny — a flag that is really worth enabling, and is enabled by the CLI by default for a while now.

**Comment by tcoz** [comment]
The issue will occur for any codebase that uses the "hacky" format (which always worked fine, but again, I know that's not a reason to object to the change). I can't go into details but I can assure you I know of two large organizations...like, LARGE ones...that have codebases containing a lot of this. I myself had to clean it up across four applications. 

The how and why this was done is important in the broader sense, but not the immediate one. I'm on your side here but I guarantee you there's more of this issue, and possibly other related ones, out there.

**Comment by tcoz** [comment]
The issue will occur for any codebase that uses the "hacky" format (which always worked fine, but again, I know that's not a reason to object to the change). I can't go into details but I can assure you I know of two large organizations...like, LARGE ones...that have codebases containing a lot of this. I myself had to clean it up across four applications. 

The how and why this was done is important in the broader sense, but not the immediate one. I'm on your side here but I guarantee you there's more of this issue, and possibly other related ones, out there.
