### ISSUE TITLE
Input type number pattern regex for integers not working properly

### ISSUE THREAD

**Issue by niksajanjic** [angular/angular#4098]
Hi, I can't quite say this is 100% Angular issue but let me give an example to point out the problem:

    <input type="number" ng-model="integer" pattern="^[0-9]\d*$" />

Problem is that it will set input to valid with any Integer number plus one '.', so these inputs will be valid:

123.
563.
7523452.
565632.

This shouldn't happen as RegEx doesn't allow anything other that Integer value which any of the previous ones really isn't.

Workaround for this is to set input to type Text with the given pattern but I don't like that idea.

**EDIT** Seems like '.' is bound to number input alone and has nothing to do with ng-model value, even after submitting form model will not contain '.', just the number in front, even after changing that value the '.' will still be there inside number input, only different number value will pop-up. I guess this can be closed.

**Comment by vicb** [comment]
Angular2 does not currently use the `pattern` attribute. 

What you see is because [pattern] (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-pattern) is not applicable to number inputs.

_As a side note `^` & `$` are implicit in the attribute value and need not be specified_
