### ISSUE TITLE
 Where can I view the document address(URL) of angular 5

### ISSUE THREAD

**Issue by yutao-lin** [angular/angular#40990]
Where can I view the document address(URL) of angular 5

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by petebacondarwin** [comment]
https://v5.angular.io/docs ??
