### ISSUE TITLE
Set LOCALE_ID dynamically after a service call

### ISSUE THREAD

**Issue by patolax** [angular/angular#41003]
I want to change the the LOCALE_ID dynamically. The culture code is coming from an api (http call).

My app module has following and LocalizationService depends on a SettingsApiService to call the api and get the value.

The problem I have is culture is applied sometimes and its not really consistent in every application load. Is there a better way to implement this.

```
providers: [
// Load the app-config.json and identity-config.json files on startup
{
  provide: LOCALE_ID,
  deps: [LocalizationService],
  useFactory: (sessionService) => sessionService.getLocale()
},
```

**LocalizationService**

```
@Injectable({ providedIn: 'root' })
   export class LocalizationService implements OnDestroy {
  private locale: string;
  private destroyed$ = new Subject();

  constructor(
    private readonly settingsService: SettingsApiService,
  ) {

    registerLocaleData(localeDe);
    registerLocaleData(localeGB);
    this.settingsStoreService.getSettings()
      .pipe(
        filter((t) => !!(t && t.culture)),
        takeUntil(this.destroyed$),
      )
      .subscribe((settings) => {
        this.setlocale(settings.culture);
        this.registerCulture(settings.culture);
      });
  }


  setlocale(value: string) {
    this.locale = value;
  }

  getLocale(): string {
    console.log(this.locale);
    return this.locale || 'en-US';
  }

  registerCulture(culture: string) {
    if (!culture) {
      return;
    }
    this.locale = culture;
    if (culture.startsWith('de')) {
      registerLocaleData(localeDe);
    } else if (culture.startsWith('en-GB')) {
      registerLocaleData(localeGB);
    }
  }

  ngOnDestroy(): void {
    this.destroyed$.next();
    this.destroyed$.complete();
  }
}
```

**Comment by zarend** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
