### ISSUE TITLE
Critical - Selectors should be known 

### ISSUE THREAD

**Issue by pedropbazzo** [angular/angular#41006]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

HTML, SVG, and MathML define the selectors which can be used in a CSS. A selector that is not part of them is likely to be a typo or a misunderstanding of the CSS syntax.

![issue](https://user-images.githubusercontent.com/32115702/109250293-31f16400-77c8-11eb-8e91-4a009e187a38.png)

**Comment by petebacondarwin** [comment]
I'm sorry I don't understand the problem you are reporting. `little-hero` is a perfectly valid CSS element selector.

**Comment by zarend** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
