### ISSUE TITLE
Support change events from custom elements

### ISSUE THREAD

**Issue by jteplitz** [angular/angular#4100]
Custom elements have no way to send values to the WebWorker. For now, we should just always grab the value field of a change event. The long term plan is to allow developers to specify custom events and serializers for them (#3350).

**Comment by IgorMinar** [comment]
I'm bumping this to 42. if you need this for Angular Connect please let us know, otherwise it will likely happen only after.

**Comment by jeffbcross** [comment]
This may be solved when #2409 is implemented.

**Comment by jelbourn** [comment]
Closing all issues related to web-workers since Angular's experimental web-worker renderer has been deprecated and it now being removed completely in Angular v11.
