### ISSUE TITLE
The provided callback is no longer runnable ('innerHTML' of null)

### ISSUE THREAD

**Issue by blazkablatnik** [angular/angular#41015]
# 🐞 bug report

### Affected Package

The issue is caused by package **@angular/core 11.x.y**

### Is this a regression?

Yes, the previous version in which this bug was not present was: **angular/core 10.x.y**

### Description
We are using Angular with Electron and after we upgraded to Angular 11.x.y, we are getting error `Cannot read property 'innerHTML' of null at _sanitizeHtml`. The error is always reproducable if breakpoint is set in specific place but also in some other runtime cases. We assume it is caused when event is triggered via Electron IPC.

After debugging, it looks like error is thrown when calling `createHTML()`  but `The provided callback is no longer runnable`: https://github.com/angular/angular/blob/980f6a4958ee3df6007d716a7c32ea7c64700b51/packages/core/src/util/security/trusted_types.ts#L63

We are using `bypassSecurity` methods in our app. Enforcing Trusted Types does not fix the issue (or we are using it wrongly).

## 🔬 Minimal Reproduction

This is a repo for reproducing the issue: https://github.com/blazkablatnik/rep_example_angular_electron
The instructions on how to setup, run and reproduce are at the top of readme. The error seems different but it is what we are seeing in our app.

## 🔥 Exception or Error
Exception in our code
<pre><code>
TypeError: Cannot read property 'innerHTML' of null at _sanitizeHtml
</code></pre>

Exception in reproducable example, that we think is caused by the same reason:
<pre><code>
core.js:6150 ERROR Error: Failed to execute 'invoke' on 'CreateHTMLCallback': The provided callback is no longer runnable.
    at trustedHTMLFromStringBypass (core.js:5278)
    at ɵɵsanitizeHtml (core.js:5913)
    at elementPropertyInternal (core.js:9961)
    at ɵɵproperty (core.js:14693)
    at AppComponent_Template (template.html:2)
    at executeTemplate (core.js:9538)
    at refreshView (core.js:9407)
    at refreshComponent (core.js:10573)
    at refreshChildComponents (core.js:9204)
    at refreshView (core.js:9457)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.1.4
Node: 12.17.0
OS: win32 x64

Angular: 11.1.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1101.4
@angular-devkit/build-angular     0.1101.4
@angular-devkit/build-optimizer   0.1101.4
@angular-devkit/core              11.1.4
@angular-devkit/schematics        11.1.4
@angular/cli                      11.1.4
@ngtools/webpack                  11.1.4
@schematics/angular               11.1.4
@schematics/update                0.1101.4
rxjs                              6.6.3
typescript                        4.1.5
webpack                           4.44.2
electron                          11.2.x
</code></pre>

**Anything else relevant?**
We use webpack to package the app and do not use Ivy to compile.

**Comment by petebacondarwin** [comment]
@bjarkler is something for you to look into?

**Comment by bjarkler** [comment]
Hey, thanks for the report! I just wanted to give a quick update that I was able to reproduce the error with your example application. In fact, by removing the `| bypass` from app.component.html I did get the same "Cannot read property 'innerHTML' of null at _sanitizeHtml" error as you described. That said, I think the real error is indeed that "The provided callback is no longer runnable".

My initial guess at why this happens is that the Trusted Types policy is being created in one execution context, but then used in another execution context in response to the Electron IPC message. I'll try reproduce this with a smaller example, to make it easier to figure out what's going on, but so far I've only seen this while setting a breakpoint. @blazkablatnik, if you manage to find a way to reproduce this without a breakpoint, that would be very helpful. Even just a confirmation that you are indeed seeing this at runtime with no breakpoints enabled would be valuable.

**Comment by blazkablatnik** [comment]
@bjarkler thanks for looking into it.

We didn't think it was possible to hit this error without breakpoint but once we pushed the product to production we could see in logs that users were getting this error without breakpoints.

The stack trace in logs was:
```
TypeError: Cannot read property 'innerHTML' of null
    at xr (file:///<path>/resources/app.asar/ui.cafec0160d0e70ee358d.bundle.js:495:3883)
    at ff.sanitize (file:///<path>/resources/app.asar/ui.cafec0160d0e70ee358d.bundle.js:1700:759)
    at file:///<path>/resources/app.asar/ui.cafec0160d0e70ee358d.bundle.js:1190:3358
    at ed (file:///<path>/resources/app.asar/ui.cafec0160d0e70ee358d.bundle.js:1197:4)
    at file:///<path>/resources/app.asar/ui.cafec0160d0e70ee358d.bundle.js:1226:5097
    at file:///<path>/resources/app.asar/ui.cafec0160d0e70ee358d.bundle.js:1226:5344
    at Qd (file:///<path>/resources/app.asar/ui.cafec0160d0e70ee358d.bundle.js:1226:8044)
    at $d (file:///<path>/resources/app.asar/ui.cafec0160d0e70ee358d.bundle.js:1233:4298)
    at Object.updateRenderer (file:///<path>/resources/app.asar/ui.cafec0160d0e70ee358d.bundle.js:2485:138331)
    at Object.updateRenderer (file:///<path>/resources/app.asar/ui.cafec0160d0e70ee358d.bundle.js:1233:1170)
```

I did try to reproduce it without breakpoints with no luck 😕

**Comment by bjarkler** [comment]
I created a more direct reproduction over at https://github.com/bjarkler/electron-tt-error that doesn't use Angular, but have still only managed to trigger this by setting a breakpoint. The cause of this seems to be the following issue in Chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=1131368

The question remains whether there is another issue at play here that doesn't involve the debugger. @blazkablatnik, do you have any metrics on how many of your users are running into this, or how frequently? Is there a chance that this is caused by a handful of tech-savvy users that are playing around with the debugger in your application?

**Comment by blazkablatnik** [comment]
@bjarkler thank you for this. Seems like this is not even a bug with angular directly so thank you for taking your time with this. 🙏

We have limited history of logs and once we noticed that users were hitting this error, we forked angular/core and implemented some "naive" handling for that error.

I can get this statistics from my logs: in **12 days** this error occurred **27 times** to 11 different users (that is around **3%** of all active users). 

We have devTools enabled on production but they are not easily accessible to end user. I am also very certain that this 11 users are not tech-savvy to the point of looking into our debugger. But I do understand why you would ask this as it seems impossible to hit this issue without breakpoints.

Also my initial guess was that a callback is deemed not runnable because the context it was defined in is paused (because of a breakpoint or something else ([nested event loops](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/public/mojom/frame/lifecycle.mojom;l=23;drc=e7a94292addb60f3317addf44c0fe4f402655bbe;bpv=1;bpt=1))?). Assuming from [this](https://chromium.googlesource.com/chromium/src/+/ac85ca2a9cb8c76a37f9d7a6c611c24114f1f05d/third_party/WebKit/Source/bindings/core/v8/GeneratedCodeHelper.cpp#34) function called from [here](https://chromium.googlesource.com/chromium/src/+/ea30c011e479b55a0c14a864709ad64fdf481dbf/third_party/blink/renderer/bindings/tests/results/core/v8_void_callback_function.cc#38). But I know very little about that.

Is there anything I can place in my logs to get more data from production? Can I get any info about the context or anything?

**Comment by amakhrov** [comment]
We also observe this "The provided callback is no longer runnable" error in our app (Angular 12). Extremely rare, probably not worth further investigation at our side. Posting here in case it's helpful

**Comment by alxhub** [comment]
Closing as this issue has been inactive for a year+ and is not an issue with Angular directly.
