### ISSUE TITLE
Can't use ngModel/formControl on type="radio" in dynamic component

### ISSUE THREAD

**Issue by sod** [angular/angular#41017]
Angular 11.2.3

If FormsModule is not present in main module but needed in a dynamic module, I see errors in the console and the radios don't render:

![image](https://user-images.githubusercontent.com/905328/109316773-3d866e80-784c-11eb-951e-9547c0813001.png)

Reproduction https://github.com/sod/issue-angular-forms via commit https://github.com/sod/issue-angular-forms/commit/b5f5d214529f753adbae9270c8a231cd20b9f652
Just do
```bash
git clone git@github.com:sod/issue-angular-forms.git
cd issue-angular-forms
npm ci
ng serve
```
then go to http://localhost:4200, click the button and see in the console.

I guess I need a `FormsModule.forRoot()`, but that doesn't exist. I'd provide `RadioControlRegistry` myself, but that reference is private and not importable. But I'd rather have a way that doesn't require to tap into the forms bundle at all from the main module as the idea was to not download, parse and compile the 60kb heavy @angular/forms fesm bundle if not needed.

**Comment by sod** [comment]
I'd rather have a way for not having to tap into the forms bundle at all from the main module as the idea was to not download, parse and compile the 60kb heavy @angular/forms fesm bundle if not needed.

**Comment by sod** [comment]
Couldn't `RadioControlRegistry` and `FormBuilder` from https://github.com/angular/angular/blob/a6971ba89adc253bfa4260036ee4a1e0bd76159f/packages/forms/src/form_providers.ts#L43 both become marked as `{providedIn: 'root'}`?

**Comment by JoostK** [comment]
I have written why this doesn't work [in a comment here](https://github.com/angular/angular/issues/35759#issuecomment-601444856). The summary is that the lazy-loaded component should be rendered using a component factory that was obtained from an NgModule that does indeed provide FormsModule.

Is this meant as a bug report, or feature request? I can't quite tell what the intention is here.

**Comment by sod** [comment]
> The summary is that the lazy-loaded component should be rendered using a component factory that was obtained from an NgModule that does indeed provide FormsModule

but I do exactly that in the reproduction

![image](https://user-images.githubusercontent.com/905328/109334491-171efe00-7861-11eb-977e-7178e28c8e20.png)

And I on purpose included a `type="text" [ngModel]="..."` in the reproduction to clearly show, that forms works, just type="radio" doesn't work

> Is this meant as a bug report, or feature request

It's a feature request I guess. A request to be able to not having to ship @angular/forms with the main module.

**Comment by JoostK** [comment]
> but I do exactly that in the reproduction

There are two sides of the import of `FormsModule` into `LazyFormsModule`:

1. It provides all template-driven form directives to be usable in the template of `LazyFormsComponent`
2. It registers providers that will be loaded into the NgModule injector. Either `LazyFormsModule` itself is instantiated into an `NgModuleRef` to obtain this injector, or an NgModule that imports `LazyFormsModule` is instantiated to create an `NgModuleRef` and associated `Injector`.

The reproduction only _loads_ the `LazyFormsComponent` from the lazily loaded module; the `LazyFormsModule` is never used and no `NgModuleRef` is created from it. As a result, no `Injector` is instantiated to provide `RadioControlRegistry` to the application. This is what https://github.com/angular/angular/issues/35759#issuecomment-601444856 was trying to explain.

**Comment by sod** [comment]
thx, gonna try that. 

But having `RadioControlRegistry` being provided automatically would be nice, given that is private anyway (so no way for me to provide something different) and the current way prevents tree shaking it if not used anyway (as stated in https://github.com/angular/angular/issues/41011).
