### ISSUE TITLE
Confusion around parameters order in RouteReuseStrategy.shouldReuseRoute()

### ISSUE THREAD

**Issue by lebesnec** [angular/angular#41012]
# 🐞 bug report

### Affected Package
@angular/router

### Is this a regression?
Yes

### Description
I'm upgrading from Angular 9 to Angular 11, and I'm facing problem with our `RouteReuseStrategy`. 
With Angular 11, after login our app would not redirect  properly (the url would change but the component did not show up). I was able to pinpoint the problem to our `RouteReuseStrategy` (see https://stackoverflow.com/questions/66283571/upgrading-from-angular-9-to-11-prevents-router-navigate-from-loading-new-compone for a similar issue).
From https://update.angular.io/?l=3&v=10.2-11.0 I noticed this point:

> If you use the Router's RouteReuseStrategy, the argument order has changed. **When calling RouteReuseStrategy#shouldReuseRoute previously when evaluating child routes, they would be called with the future and current arguments swapped.** If your RouteReuseStrategy relies specifically on only the future or current snapshot state, you may need to update the shouldReuseRoute implementation's use of future and current ActivateRouteSnapshots.

So I swapped the argument and the redirection after login works again. But now it's the redirection after logout that doesn't work anymore (from my understanding angular try to reuse our "shell" component on the logout page although he shouldn't on that specific page).

Then I checked [the documentation](https://angular.io/api/router/RouteReuseStrategy#shouldreuseroute) and [the code](https://github.com/angular/angular/blob/master/packages/router/src/route_reuse_strategy.ts) and it appear that the argument are NOT swapped.
I'm honestly confused at what to do here.

## 🔬 Minimal Reproduction
Here is the code from our RouteReuseStrategy:
<pre><code>
import { ActivatedRouteSnapshot, DetachedRouteHandle, RouteReuseStrategy } from '@angular/router';
import { Injectable } from "@angular/core";

/**
 * A route strategy allowing for explicit route reuse.
 * Used as a workaround for https://github.com/angular/angular/issues/18374
 * To reuse a given route, add `data: { reuse: true }` to the route definition.
 */
@Injectable()
export class RouteReusableStrategy extends RouteReuseStrategy {

  public shouldDetach(route: ActivatedRouteSnapshot): boolean {
    return false;
  }

  public store(route: ActivatedRouteSnapshot, detachedTree: DetachedRouteHandle | null): void { }

  public shouldAttach(route: ActivatedRouteSnapshot): boolean {
    return false;
  }

  public retrieve(route: ActivatedRouteSnapshot): DetachedRouteHandle | null {
    return null;
  }

  public shouldReuseRoute(curr: ActivatedRouteSnapshot, future: ActivatedRouteSnapshot): boolean {
    return (future.routeConfig === curr.routeConfig) || future.data.reuse;
  }

}
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.2
Node: 12.16.3
OS: win32 x64

Angular: 11.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1102.2
@angular-devkit/build-angular      0.1102.2
@angular-devkit/core               11.2.2
@angular-devkit/schematics         11.2.2
@angular/cdk                       11.2.2
@angular/cli                       11.2.2
@angular/flex-layout               11.0.0-beta.33
@angular/material                  11.2.2
@angular/material-moment-adapter   11.2.2
@schematics/angular                11.2.2
@schematics/update                 0.1102.2
rxjs                               6.5.5
typescript                         4.0.7
</code></pre>

**Comment by atscott** [comment]
@lebesnec - There was a bug in the router where these _were_ swapped but they no longer are (https://github.com/angular/angular/commit/3817e5f1dfeb9de26fa2ea4068a37565f435214f#diff-a655d62becd522d808a607905e22b79610a910364071ae8e1fc9c57714900463). `future` should always be the second param. If you're seeing something different, please provide a reproduction in stackblitz or a github repo.

**Comment by atscott** [comment]
Closing, see comment above. 

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template that include info on how to create a reproduction using our template.

**Comment by lebesnec** [comment]
from what I've seen `future` is indeed the first param. Thanks for the clarification.
