### ISSUE TITLE
Keyboard highlighting

### ISSUE THREAD

**Issue by 24hfish** [angular/angular#41019]
I dont want to post the same thing twice across platform so ill link it here, but there is an issue with keyboard keys getting highlighted on my keyboard after ive visited the demo sandbox
https://github.com/stackblitz/core/issues/1395#issue-817481622

**Comment by zarend** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
