### ISSUE TITLE
List ng-mocks on resources - development

### ISSUE THREAD

**Issue by satanTime** [angular/angular#41025]
# 📚 Docs or angular.io bug report

### Description

I would like to discuss with you if it is fine to list https://github.com/ike18t/ng-mocks on this page, or what should be done to make it possible.

### What's the affected URL?
https://angular.io/resources?category=development

**Comment by gkalpak** [comment]
@satanTime, you can find more info on getting listed on angular.io/resources [here][1].
I think it would be best to close this issue and open a pull request and we can discuss there, if needed.

[1]: https://github.com/angular/angular/blob/master/aio/content/marketing/resources-contributing.md

**Comment by satanTime** [comment]
Hi @gkalpak, thanks for the info.

Done: https://github.com/angular/angular/pull/41027
