### ISSUE TITLE
Codelyzer versus angular-eslint on resources page

### ISSUE THREAD

**Issue by Airblader** [angular/angular#41029]
# 📚 Docs or angular.io bug report

### Description

The [resources page](https://angular.io/resources?category=development) lists codelyzer, but not angular-eslint. Since tslint and in consequence codelyzer is deprecated and codelyzer is [being removed from the styleguide](https://github.com/angular/angular/pull/40992), we should consider

1. adding angular-eslint (should be a no-brainer)
2. removing codelyzer (or maybe still keep it?)

### What's the affected URL?**

https://angular.io/resources?category=development

**Comment by gkalpak** [comment]
I checked with @mgechev and @twerske ([internal discussion][1]) and they confirmed it sounds reasonable to remove `codelyzer` and add `angular-eslint` to resources.

@Airblader, is this something you would be interested to take on?

[1]: https://angular-team.slack.com/archives/C18F9SF3L/p1614599093002800

**Comment by Airblader** [comment]
I'm happy for some new contributor to pick this up as an easy task to get started.
