### ISSUE TITLE
extract-i18n with HTML entities and interpolation

### ISSUE THREAD

**Issue by pKrupaJunior** [angular/angular#41034]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, I also tested this with the old extraction tool (`"@angular/cli": "~9.1.15"`) and it works correctly with `ng xi18n`.

### Description

Placing an [HTML entity](https://dev.w3.org/html5/html-author/charref) (e.g. `&nbsp;`) inside a translated text which also contains interpolated variables
(`<div i18n>&nbsp;Interpolation: {{ variable }}</div>`)
results in an incorrect value of the `equiv-text` attribute inside the extracted message's `INTERPOLATION` tag
(`<x id="INTERPOLATION_1" equiv-text="ion: {{ v"/>`).
Seems like the value is shifted by the difference in amount of characters taken up by the HTML entity and it's actual representation.

This is a minor and rather unimportant issue since it does not affect the actual interpolation or translation. From what I understand this `equiv-text` attribute has an informative role for translators.

## 🔬 Minimal Reproduction

[https://github.com/pKrupaJunior/extract-i18n-issue](https://github.com/pKrupaJunior/extract-i18n-issue)

1. Create project:
  ```shell
  ng new extract-i18n-issue -s -t --minimal -g -S --style css --create-application false
  ```
2. Create sample application:
  ```shell
  ng g application demo -s -t --minimal --style css -S --routing false
  ```
3. Add localization support:
  ```shell
  ng add @angular/localize
  ```
4. Add an HTML template containing `i18n` attribute on a tag with **interpolated variables** and **HTML entities**:
  ```html
  <div i18n>Interpolation: {{ one }}&nbsp;Interpolation: {{ two }}</div>
  ```
5. Run `extract-i18n`:
  ```shell
  ng extract-i18n --output-path projects/demo/src/i18n
  ```

## 🔥 Result
The generated `messages.xlf` file contains this:
```xml
<trans-unit id="4906579891802234912" datatype="html">
  <source>Interpolation: <x id="INTERPOLATION" equiv-text="{{ one }}"/> Interpolation: <x id="INTERPOLATION_1" equiv-text="ion: {{ t"/></source>
  ...
</trans-unit>
```
The second `equiv-text` attribute value is incorrect: `<x id="INTERPOLATION_1" equiv-text="ion: {{ t"/>`.
While it should be: `<x id="INTERPOLATION_1" equiv-text="{{ two }}"/>`.

## 🌍 Your Environment
<pre><code>Angular CLI: 11.1.4
Node: 12.13.0
OS: win32 x64

Angular: 11.1.2
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.4
@angular-devkit/build-angular   0.1101.4
@angular-devkit/core            11.1.4
@angular-devkit/schematics      11.1.4
@angular/cli                    11.1.4
@schematics/angular             11.1.4
@schematics/update              0.1101.4
rxjs                            6.6.6
typescript                      4.1.5
</code></pre>

**Comment by petebacondarwin** [comment]
So the problem is that our lexer decodes such entities into their actual characters but the whole decoded text block is passed to the parser that then splits out the interpolation blocks, which is done on a character basis, which has lost the original position of the encoded characters...

**Comment by petebacondarwin** [comment]
The only real solution is to actually capture these interpolations as tokens in their own right with their own source-spans, and then change the parsers to handle this.
