### ISSUE TITLE
optimize angular template compile progress

### ISSUE THREAD

**Issue by joebnb** [angular/angular#41044]
current template compile progress really slow,if not use aot to pre process, it cost 70% script timing,and it not let the template compile task with asnyc,it seems compile all once js ready,i think if compile it when module require and memo for next time will better.

![image](https://user-images.githubusercontent.com/1646883/109589294-129a6400-7b45-11eb-9b2b-92601b43af77.png)

could optimise for sence of none aot

**Comment by petebacondarwin** [comment]
I note from your screenshot that there is a call to `compileNgModuleFactory__PRE_R3__()`. This implies you have not enabled Ivy in this project. Is that correct?

The ViewEngine compiler is deprecated, so will not receive any improvements to performance at this stage.

Perhaps you could try enabling ivy to see if there is a boost?

**Comment by joebnb** [comment]
> I note from your screenshot that there is a call to `compileNgModuleFactory__PRE_R3__()`. This implies you have not enabled Ivy in this project. Is that correct?
> 
> The ViewEngine compiler is deprecated, so will not receive any improvements to performance at this stage.
> 
> Perhaps you could try enabling ivy to see if there is a boost?

thank you for reply

i'm using self hosted webpack conf like this link:

https://github.com/anandshende/angularSetupWithWebpack/blob/master/webpack.config.js

in my project if use ng build,the assert will take 600ms-900ms to execute javascript(AOT),but use self hosted webpack build ,the assert will take 3.7s-4.2s to  execute javascript(none AOT),the biggest different seems is template formate, string or processed template function(AOT).

i'm wonder about why html compile so heavily(it coast almost 3s to compile html)

and not sure how to avoid to use compileNgModuleFactory__PRE_R3__() function in self hosted webpack

**Comment by petebacondarwin** [comment]
Please can you specify the versions of Angular packages you are using, and also the contents of the tsconfig.json that you use to build?

**Comment by joebnb** [comment]
> Please can you specify the versions of Angular packages you are using, and also the contents of the tsconfig.json that you use to build?

i'm using angular 10.1.5

and tsconfig is:
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "emitDecoratorMetadata": true,
    "target": "es2015",
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    }
  }
}
```

**Comment by petebacondarwin** [comment]
So this should be building with Ivy by default. So I am not sure why we see the `__PRE_R3__` in the stack.
Can I ask why you are not precompiling with AOT?

**Comment by joebnb** [comment]
> So this should be building with Ivy by default. So I am not sure why we see the `__PRE_R3__` in the stack.
> Can I ask why you are not precompiling with AOT?

sure,because i'm not using ng-cli to build,instad of a customed webpack to build.

it not using anuglar/compiler to transform code like https://github.com/anandshende/angularSetupWithWebpack/blob/master/webpack.config.js this config,so it not running precompiling.

i think we have different curious point, i just want run it with customed webpack config and  without aot,that's can make all things transparent when exception,by the way this project also can hold up by ng-cli.

**Comment by joebnb** [comment]
could this question will be improve?

**Comment by alxhub** [comment]
You appear to be using Angular's View Engine compiler and runtime, which will be removed in a future version. I highly recommend you switch to Angular Ivy. Since you aren't using the Angular CLI but instead using a custom Webpack build and JIT mode, you will need to manually run `ngcc` on your `node_modules` to upgrade Angular to use Ivy, and make sure you `import '@angular/compiler';` in your application.

As this is an issue against View Engine and we are not considering any performance changes to View Engine, I'm going to close this issue now - feel free to open a new one if you upgrade to Ivy and are still experiencing performance challenges.
