### ISSUE TITLE
I have a **hack** that seems to work. After looking at the source code, it looks like `this.update()` is also called any time the inputs are changed. So, if you add an `routerLinkActiveOptions` property and give it a throw-away value that is changed based on the URL, then the inputs will technically change. Example:

### ISSUE THREAD

**Issue by AbdurRaziqUtor** [angular/angular#41067]
I have a **hack** that seems to work. After looking at the source code, it looks like `this.update()` is also called any time the inputs are changed. So, if you add an `routerLinkActiveOptions` property and give it a throw-away value that is changed based on the URL, then the inputs will technically change. Example:

```
<a
routerLink="/foo/:id/bar"
routerLinkActive="on"
[routerLinkActiveOptions]="{ exact: false, __change_detection_hack__: id }"> Link </a>
```

Here, the `__change_detection_hack__` key will change when the `id` changes (ie, after navigation has completed and the template is reconciled), which will cause the inputs to change, which will cause the `this.update()` method to run. And, at that point, the `QueryList<RouterLink>` should be in the proper state.

It's janky, but it works as a stop-gap.

_Originally posted by @bennadel in https://github.com/angular/angular/issues/18469#issuecomment-345436335_

**Comment by petebacondarwin** [comment]
It is not clear why you opened this issue with the content (and title) that you did. 

The original issue was closed as it was resolved. If you still have this issue or a similar one, then please open a bug report and follow the instructions there.
