### ISSUE TITLE
docs: Missing docs for Optional, Self, SkipSelf, Host, etc. decorator.

### ISSUE THREAD

**Issue by infacto** [angular/angular#41065]
# 📚 Docs or angular.io bug report

There are some sections without descriptions. I was triggered by example of the page: 
https://angular.io/guide/singleton-services#how-forroot-works (where I see the `@Optional` decorator).

Examples of missing docs:
https://angular.io/api/core/Optional
https://angular.io/api/core/Self
https://angular.io/api/core/SkipSelf
https://angular.io/api/core/Host
etc.

Add some descritpion. What and what is it for? Use case?

![image](https://user-images.githubusercontent.com/60390085/109788515-afc1cf00-7c0f-11eb-88d0-269f46084405.png)

![image](https://user-images.githubusercontent.com/60390085/109788545-b6504680-7c0f-11eb-8a2e-2fe3315cc8b8.png)

**Comment by petebacondarwin** [comment]
This is actually an issue with the doc-gen. The docs you are seeing are being sourced from https://github.com/angular/angular/blob/11.2.3/packages/core/src/di/metadata.ts#L238-L243

But we should be getting them from https://github.com/angular/angular/blob/11.2.3/packages/core/src/di/metadata.ts#L212-L226

**Comment by destus90** [comment]
This resembles another issue (https://github.com/angular/angular/issues/40851) created a few week ago.

**Comment by petebacondarwin** [comment]
LOL Yes @destus90 thank you. I thought I recognised this. I'll close this as a duplicate and try to provide a fix over the weekend.
