### ISSUE TITLE
NgZone onEventDone cannot accept different type callbacks

### ISSUE THREAD

**Issue by gfanzh** [angular/angular#4106]
NgZone overrideOnEventDone cannot have waitForAsync and non-waitForAsync callbacks at the same time.

Google ACX project activity tracking need non-waitForAsync callback to determine VM event loop end, while test bed used waitForAsync callback to determine Angular isStable.

Now they are conflict. We give up activity tracking callback in test as workaround but that makes integration test not possible.

Have a draft fix at cl/100424191

**Comment by naomiblack** [comment]
obsolete by #7345
