### ISSUE TITLE
Can I use $localize in the latest stable version of Angular?

### ISSUE THREAD

**Issue by martijn-van-den-bergh** [angular/angular#41077]
# 📚 Docs or angular.io bug report

### Description

I am starting a new Angular 11 project and I don't want to use the old way of implementing i18n because well ... it was pretty bad. 
I heard that Ivy should be better at implementing i18n and I have read about the $localize function, but I don't know if it is already supported at this moment. The official guide only describes the old way.
Is there a place where I can follow this specific topic? 

### What's the affected URL?**

https://angular.io/guide/i18n

**Comment by petebacondarwin** [comment]
I have a PR to expose the `$localize` API: https://github.com/angular/angular/pull/40317
I think you are safe making use of `$localize` in your code if you are using the latest Angular versions.
Be aware that translation of strings in templates still works the same way (i.e. using `i18n` attributes) whether you are using Ivy or not. `$localize` would only be used if you want to have translatable text in application code.

**Comment by martijn-van-den-bergh** [comment]
Oooh right, thanks for pointing that out! I missed have missed that.
