### ISSUE TITLE
ErrorHandler intercepts HttpErrorResponse with HttpStatusCode 0

### ISSUE THREAD

**Issue by tinosteinort** [angular/angular#41089]
# 🐞 bug report

### Affected Package
Angular 11

### Is this a regression?
In Angular 10 there is no problem. In Angular 11 there is an error thrown
Yes, the previous version in which this bug was not present was: Angular 10.0.0

### Description

Open an URL which should open a component which is saved by a guard. The guard
 causes a full page reload to redirect to another URL.

## Problem
* With Angular 10:
  The browser is redirected without an error
* With Angular 11:
  The browser is redirected, but the `HttpErrorInterceptor` catches a `HttpErrorResponse` with
  HttpStatusCode `0`.

After an update from `Angular 10` to `Angular 11`, you need to update your `HttpErrorInterceptor`
to handle additionally the HttpStatusCode `0`, because the behaviour has changed.
Since the HttpStatusCode `0` does not exist, this may not be the correct behaviour.

If you call the URL http://localhost:4200/assets/i18n/en-GB.json you will see the resource exist.

## 🔬 Minimal Reproduction

I have prepared a git repository to show this issue: https://github.com/tinosteinort/angular11-http-error-code-0-example
The `main` branch shows an angular 11 app with the problem 
The `angular10` branch contains the same app, only with angular 10 -> no problem

* Start app (from `main` branch):
  ```
  npm run start
  ```
* Open `localhost:4200` in FireFox and open DeveloperTools to see the javascript console
* Enable `Persist Logs` in Developer Tools for `Console` and for `Network` tab
* Click `Go to restricted`
    * all is fine, in the console there is no error visible
    * use the browser "go back" button
* Open `localhost:4200/restricted` in the browser directly (without clicking the link)
    * redirection happened as expected, but before the browser location has changed,
      there is an error in the console
    * The `HttpErrorInterceptor` get an error with HttpStatusCode `0`

## 🔥 Exception or Error
```
  ERROR 
    {
    "headers": {
    "normalizedNames": {},
    "lazyUpdate": null,
    "headers": {}
    },
    "status": 0,
    "statusText": "Unknown Error",
    "url": "http://localhost:4200/assets/i18n/en-GB.json",
    "ok": false,
    "name": "HttpErrorResponse",
    "message": "Http failure response for http://localhost:4200/assets/i18n/en-GB.json: 0 Unknown Error",
    "error": {
    "isTrusted": true
    }
    }
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.3
Node: 12.20.2
OS: linux x64

Angular: 11.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.3
@angular-devkit/build-angular   0.1102.3
@angular-devkit/core            11.2.3
@angular-devkit/schematics      11.2.3
@angular/cli                    11.2.3
@schematics/angular             11.2.3
@schematics/update              0.1102.3
rxjs                            6.6.6
typescript                      4.1.5
</code></pre>

**Anything else relevant?**
Does not work in Firefox 86 (20210222142601)
In Chrome there is no problem

**Comment by Brandinga** [comment]
sounds because of #40786 

redirecting in your guard cancles the request to your i18n file

**Comment by tinosteinort** [comment]
Thanks for the info, this ([#40786](https://github.com/angular/angular/pull/40786)) should be the reason.
In my setup I was not offline.

Since the only change I made was from angular version `10` to `11` and the error has occured, would it make sence to update the migration guide (10 -> 11) and give a hint about this?

Because: if your `http-error-interceptor` looks somehow like that:
```
public intercept( req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
  if (error.status !== 401) {
    // do something, maybe redirect
  }
  return throwError(error);
}
```
after the update, your application will behave in an unexpected way. You HAVE TO update your interceptor, but you have no clue, that you need to do this.

**Comment by jelbourn** [comment]
Looking at the behavior change, it falls into the category of "bug fix", which we don't usually detail in the migration guide (though it is captured in the changelog). Realistically, we can't document every behavior change, even though any change could break _someone_ ([Hyrum's Law](https://www.hyrumslaw.com/))
