### ISSUE TITLE
Tomar cuidado com as atualizações

### ISSUE THREAD

**Issue by AdamTeodoro** [angular/angular#41082]
### **Tomar muito cuidado com as atualizações!**

Os desenvolvedores já têm muitos problemas para resolver, preparar ou ajustar uma configuração em um ambiente de desenvolvimento para cada vez que uma das centenas de ferramentas que o desenvolvedor usa pode ser catastrófico para o contínuo uso da tecnologia, isso afeta tanto que muitos desenvolvedores procuram não atualizar as ferramentas com medo das possíveis configurações e ajustes que terão de fazer, isso torna o ambiente de trabalho cansativo e estressante!

**Comment by petebacondarwin** [comment]
Closing as there is no action for the Angular project to take here.
