### ISSUE TITLE
VS Code Debugger Step Over into skipFiles in Angular App

### ISSUE THREAD

**Issue by re4388** [angular/angular#41098]
# 🐞 bug report

### Description

When I try to use VS Code debugger to Step Over Angualr code, it seems that the debugger still always step over into files I had set into skipFiles.

launch.json setting (both 2 settings are not working)
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-chrome",
      "request": "launch",
      "name": "Launch Chrome",
      "url": "http://localhost:4200",
      "webRoot": "${workspaceFolder}",
      "skipFiles": [
        "${workspaceFolder}/node_modules/**/*.js",
        "${workspaceFolder}/lib/**/*.js",
        "<node_internals>/**/*.js"
      ],
    }
  ]
}
```
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-chrome",
      "request": "launch",
      "name": "Launch Chrome",
      "url": "http://localhost:4200",
      "webRoot": "${workspaceFolder}",
      "skipFiles": [
        "${workspaceFolder}/node_modules/**/*.js",
        "${workspaceFolder}/lib/**/*.js",
        "<node_internals>/**/*.js"
      ],
      "sourceMaps": true,
      "sourceMapPathOverrides": {
        "webpack:/*": "${webRoot}/*",
        "/./*": "${webRoot}/*",
        "/src/*": "${webRoot}/*",
        "/*": "*",
        "/./~/*": "${webRoot}/node_modules/*"
      }
    }
  ]
}
```

## 🔬 Minimal Reproduction

1. clean angular cli setup new app
```
npm install -g @angular/cli
ng new my-dream-app
cd my-dream-app
ng serve
```

2. set breakpoint enter image description here
![a1](https://user-images.githubusercontent.com/5414334/110190915-b430f680-7e60-11eb-9dd9-1a68d7cf4dbe.png)

3. Start debuggining by click the below panel enter image description here
![a2](https://user-images.githubusercontent.com/5414334/110190930-c6ab3000-7e60-11eb-8200-f5ad7cf773b3.png)

4. Stop at breakpoint enter image description here
![a3](https://user-images.githubusercontent.com/5414334/110190936-ce6ad480-7e60-11eb-83bf-e63ae98d6e5f.png)

5. After 3 Step Over, we end up in the below screenshot (sometimes, it seems to skip, but sometimes not) On the right, we see those files are indeed skipped in the call stack? But the Step Over still stop inside the file. enter image description here
![a4](https://user-images.githubusercontent.com/5414334/110190938-d3c81f00-7e60-11eb-8d33-8cb57e08355c.png)

## 🌍  Your Environment
VS Code Version:
Version: 1.54.1 (user setup)
Commit: f30a9b7
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0

OS: Windows_NT x64 10.0.18363

OS Version:
win10 1909

All Vscode extensions are disabled.

**Angular Version:**
<pre><code>

Angular CLI: 11.2.3
Node: 14.9.0
OS: win32 x64

Angular: 11.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.3
@angular-devkit/build-angular   0.1102.3
@angular-devkit/core            11.2.3
@angular-devkit/schematics      11.2.3
@angular/cli                    11.2.3
@schematics/angular             11.2.3
@schematics/update              0.1102.3
rxjs                            6.6.6
typescript                      4.1.5

</code></pre>

**Anything else relevant?**
I am confused if this is more about Angular or more about VS Code, so I also create a similar issue on VS Code issue
https://github.com/microsoft/vscode/issues/67039

_EDIT(@gkalpak): microsoft/vscode#118282_

**Comment by gkalpak** [comment]
This definitely looks like an issue with VSCode or the debugger. (Esp. since it also happens with extensions disabled, it can't be related to the Language Service extension.)

I am going to close this. Let's follow microsoft/vscode#118282 instead.
