### ISSUE TITLE
Debug module `ng` has no types

### ISSUE THREAD

**Issue by pemu69** [angular/angular#41137]
# 🚀 feature request

### Relevant Package
 This feature request is for @angular/core

### Description
I would want to use the `ng.getComponent()` method in jasmine tests. But the name `ng` is not known to typescript. 

[Just a question aside: is `ng.getComponent()` a stable API?] 

### Describe the solution you'd like
Have typescript definitions for the `ng` module.

### Describe alternatives you've considered
It works with @ts-ignore

**Comment by nanashj** [comment]
[]()

**Comment by nanashj** [comment]
Nana is

**Comment by ThehackerNsw** [comment]
Want to watch

**Comment by VlasovSergey** [comment]
+1
