### ISSUE TITLE
Angular 2 Http not working version : alpha-36

### ISSUE THREAD

**Issue by shatakshidixit** [angular/angular#4113]
MyHttp.ts

import {Component, View, NgFor} from 'angular2/angular2';
import {Http, Response, HTTP_BINDINGS} from 'http/http';
import {ObservableWrapper} from 'angular2/src/facade/async';

@Component({
  selector: 'navbar',
  viewBindings: [HTTP_BINDINGS],
  })
@View({
  directives: [NgFor],
  templateUrl: 'components/navbar/navbar.html'
  })
export class Navbar {
  people: Object;
    constructor(http : Http) 
    {
      alert("a");  \\alert also not working
      ObservableWrapper.subscribe<Response>(http.get('people.json'),res => this.people = res.json());
    }
}

For the above Code the error is showing : Cannot resolve all parameters for Navbar(?). Make sure they all have valid type or annotations.

"Even the alert in the constructor is not showing"

**Comment by shatakshidixit** [comment]
MyHttp.ts

import {Component, View, NgFor} from 'angular2/angular2';
import {Http, Response, HTTP_BINDINGS} from 'http/http';
import {ObservableWrapper} from 'angular2/src/facade/async';

@Component({
selector: 'navbar',
viewBindings: [HTTP_BINDINGS],
})
@View({
directives: [NgFor],
templateUrl: 'components/navbar/navbar.html'
})
export class Navbar {
people: Object;
constructor(http : Http) 
{
alert("a"); \alert also not working
ObservableWrapper.subscribe(http.get('people.json'),res => this.people = res.json());
}
}

For the above Code the error is showing : Cannot resolve all parameters for Navbar(?). Make sure they all have valid type or annotations.

"Even the alert in the constructor is not showing"

**Comment by ericmdantas** [comment]
@shatakshidixit are you importing the http module separately?

https://code.angularjs.org/2.0.0-alpha.36/

**Comment by shatakshidixit** [comment]
yes My main file is app.ts and through routing this file is getting loaded

**Comment by shatakshidixit** [comment]
Yes

**Comment by ericmdantas** [comment]
It's working fine, see [this plnkr](http://plnkr.co/edit/73PVI5onqf7nt8Ge9aLP?p=preview).

I suggest you share a bit more code so we can help you better.

**Comment by shatakshidixit** [comment]
Your code is perfectly fine but its not working in  my project.
The Complete Http code is given above in the issue.
In My app.ts I did nothing related to HTTP except routing to the page.

Can You  Please help me out.

**Comment by ericmdantas** [comment]
@shatakshidixit have you tried to use ```@Inject```?

**Comment by thelgevold** [comment]
In version .37 this is no longer necessary with TypeScript 1.6-beta
Added a working solution here: https://github.com/thelgevold/angular-2-samples

**Comment by ericmdantas** [comment]
[Here's a plnkr](http://plnkr.co/edit/5MLXovEbnkPfVOgULlrT?p=preview) with an updated version (.37)

**Comment by yfain** [comment]
I tried removing @Inject from the constructor's argument in Alpha 37 and TS 1.6-beta, and still getting an "Unhandled promise rejection" error. 

This works:
constructor( @Inject(ProductService) productService: ProductService) {}

This doesn't:
constructor(productService: ProductService) {  }

**Comment by shatakshidixit** [comment]
@ericmdantas thanks
My code is perfectly working now.

**Comment by shatakshidixit** [comment]
@yfain 

have you included http.js file in your index.html?

**Comment by ericmdantas** [comment]
@shatakshidixit No problem :smile: 

Can you close this, please?

**Comment by shatakshidixit** [comment]
Yes Sure
