### ISSUE TITLE
Native select performance issue

### ISSUE THREAD

**Issue by bhanna1693** [angular/angular#41138]
# 🐞 bug report

### Affected Package
native `<select>` element

### Is this a regression?
This bug appears to be prevalent on versions 10 and 11. Have not tested on other versions.

### Description

Performance problem on Chromium based browsers: Clicking on a native  `<select>` element appears to cause a significant lag.
Additionally, the lag is more noticeable on pages with more content on them. Meaning it cannot be reproduced with just a simple select tag with nothing else on the page. However, the amount of content on the page does not justify the lag. The stackblitz provided is one such example that should be handled.

## 🔬 Minimal Reproduction
[StackBlitz](https://stackblitz.com/edit/angular-ivy-6xgj3e?file=src%2Fapp%2Fstudents-table-home%2Fstudents-table%2Fstudents-table.component.html)

This bug can also be reproduced by inspecting any website built with Angular, and pasting the following code:
```
<select>
    <option>One</option>
    <option>Two</option>
    <option>Three</option>
    <option>Four</option>
</select>
```
Try this using Chrome (Firefox appears to be unaffected by this issue).

## 🔥 Exception or Error
no error. just a lot of lag

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.3
Node: 12.18.3
OS: win32 x64

Angular: 11.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1102.3
@angular-devkit/build-angular      0.1102.3
@angular-devkit/core               11.2.3
@angular-devkit/schematics         11.2.3
@angular/cdk                       11.2.3
@angular/cli                       11.2.3
@angular/material                  11.2.3
@angular/material-moment-adapter   11.2.3
@schematics/angular                11.2.3
@schematics/update                 0.1102.3
rxjs                               6.6.6
typescript                         4.0.7

</code></pre>

**Anything else relevant?**

Browsers running with chromium appear to be affected most (Chrome, Edge, etc...). Firefox does not appear to be affected by this bug.

**Comment by JoostK** [comment]
The StackBlitz works just fine for me in Chrome 89.0.4389.72; I don't notice any lag when interacting with the select in the top-left corner.

**Comment by gkalpak** [comment]
FWIW, I do see a small (but noticeable - esp. compared to Firefox) lag when clicking on the select.
I'm on Chrome v89.0.4389.82 (on Windows).

**Comment by bhanna1693** [comment]
I've also noticed this issue on the Bootstrap documentation site: [Bootstrap documentation site]( https://getbootstrap.com/docs/5.0/forms/validation/#supported-elements).  So this might be an issue for the Chromium team. Ticket is here in case interested: [https://bugs.chromium.org/p/chromium/issues/detail?id=1186233](https://bugs.chromium.org/p/chromium/issues/detail?id=1186233).

**Comment by gkalpak** [comment]
Thx for the update, @bhanna1693 :+1:

It seems that this is not related to Angular then. I could reproduce the same lag by copying the HTML from the StackBlitz you provided and using it on a page without Angular loaded.

Based on the above, I am going to close this issue. Let's track https://bugs.chromium.org/p/chromium/issues/detail?id=1186233.
If any indications comes up that this is somehow related to or affected by Angular, feel free to open a new issue.
