### ISSUE TITLE
[commit conventions] Make `:` after `BREAKING CHANGE` optional

### ISSUE THREAD

**Issue by gr2m** [angular/angular#4114]
Hey, 

I've already run into this several times. I usually do breaking change commits like [this](https://github.com/eHealthAfrica/kazana-server/commit/f0543c3c6de472161136451bc161d55949f43acc) 

```
BREAKING CHANGE

Before

    var Server = require('kazana-server')

    var kazana = new Server('path/to/kazana-app-or-plugin')
    kazana.start(function () {
      console.log('Server running at %s', kazana.info.uri)
    })

Now

    var startKazanaServer = require('kazana-server')

    startKazanaServer('path/to/kazana-app-or-plugin', /*options ,*/ function (error, server) {
      if (error) {
        throw error
      }
      console.log('Server running at %s', kazana.info.uri)
    })
```

I tend to forget the `:` because I do line breaks instead. Any chance we could make the `:` optional?

This is causing quite some headaches for me, because I use [semantic-release](https://github.com/semantic-release/semantic-release) everywhere, (which uses https://github.com/ajoslin/conventional-changelog, which strictly implements angular commit messages), and end up with minor releases on GitHub/npm, but with breaking changes :(

Thanks :bouquet: 

---

follow up for https://github.com/ajoslin/conventional-changelog/issues/103, cc @jo

**Comment by vicb** [comment]
@jeffbcross is this fixed with the conventional changelog update ?

**Comment by vicb** [comment]
seems like this is not fixed yet....

https://github.com/conventional-changelog/conventional-commits-parser/blob/61d3809e6d95a52922172c6ecaace9f3c91cc39d/lib/regex.js#L21

**Comment by vicb** [comment]
fixed
