### ISSUE TITLE
Document return value for bodyless HTTP response status codes

### ISSUE THREAD

**Issue by kputh** [angular/angular#41148]
# 📚 Docs feature request

### Description

The current documentation does not state which value (_null_, _undefined_, _''_) the HttpClient will return when a server responds with an HTTP status code like _204 No Content_. Please add this information to either the Developer Guide or the API Reference.

### What's the affected URL?**
* https://angular.io/guide/http
* https://angular.io/api/common/http/HttpClient

**Comment by kputh** [comment]
@flash-me, I think the HttpClient **does** return null when an empty body is received.

**Comment by flash-me** [comment]
The code: https://github.com/angular/angular/blob/master/packages/common/http/src/response.ts#L274
So in case of 204 that should be undefined, right?

Good opportunity to contribute  ☺

cheers
flash ⚡

**Comment by iRealNirmal** [comment]
@petebacondarwin as related PR is closed, can we close this ticket if we are not going to do changes.

**Comment by petebacondarwin** [comment]
I think we can close this since the body property of `HttpResponse` is documented here https://angular.io/api/common/http/HttpResponse#body
