### ISSUE TITLE
feature request - parseDate - localizable date parsing, supporting different date formats into date object

### ISSUE THREAD

**Issue by Chiff** [angular/angular#41169]
# 🚀 feature request - parseDate - localizable date parsing, supporting different date formats into date object
### Relevant Package
This feature request is for @angular/common

### Description
Hello,

on behalf of [Annotation Slovakia s.r.o](https://github.com/AnnotationSro), we would like to propose an extension for date manipulation. 

Throughout multiple projects we have found ourselves dwelling on missing **native** support for date parsing in angular. As a result of this we have been forced to use another "unnecessary" libraries, such as moment.js, or components without ControlValueAccessor, each with custom date parsing implementation.

We have been internally working on [@annotation/ng-datepicker](https://github.com/AnnotationSro/ng-a-datepicker) where we implemented [`parseDate()`](https://github.com/AnnotationSro/ng-a-datepicker/blob/main/ng-a-date-picker/projects/ng-datepicker/src/lib/parsers/parse-date.ts) function, which is based on angular `formatDate()` and we believe it should be part of angular framework. 

We hope you will consider adding this function into framework and as soon as discussion is resolved we will create PR.

Regards.

Martin Filo,
Annotation Slovakia s.r.o.

_Side note:
We are aware of PR #31143, but it was declined as exported utility and it would only work with one date format without localization_

### Demonstartion of `parseDate()` function
**API:**
```
export type BasicDateFormat = 'short' | 'medium' | 'long' | 'full' | 'shortDate' | 'mediumDate' | 'longDate' | 'fullDate' | 'shortTime' | 'mediumTime' | 'longTime' | 'fullTime';
export function parseDate(value: string, format: BasicDateFormat | string, locale: string, oldValue?: Date): Date;
```

**Example usage 1:** 
```
const dateString: string = '2021-01-27T22:37:44+02:00';
const format: string = 'yyyy-MM-ddTHH:mm:ssZZZZZ';

const date: Date = parseDate(dateString, format, 'sk', undefined);
// date = Wed Jan 27 2021 21:37:44 GMT+0100 (Central European Standard Time)
```

**Example usage 2:** 
```
const dateString: string = '1.1.2020';
const format: BasicDateFormat = 'shortDate';

const date: Date = parseDate(dateString, format, 'sk', undefined);
// date = Wed Jan 01 2020 01:00:00 GMT+0100 (Central European Standard Time)
```

### Describe the solution you'd like
We would like to open a discussion about this feature and as soon as it is approved we will create PR

**Comment by petebacondarwin** [comment]
Hi @Chiff - Thank you for this very neat and clear request. I'll discuss it with the rest of the team and return with a response.

**Comment by petebacondarwin** [comment]
Hi - we discussed this yesterday.

Similar to what @IgorMinar said in the related PR (https://github.com/angular/angular/pull/31143#issuecomment-523540182) adding this feature would add an additional burden to the team's maintenance costs going forward - as does any new public API that we support, while at the same time not adding anything that is actually needed internally to the framework - we would not be able to use `parseDate()` internally for things like `DatePipe` without destroying the ability to tree shake the function it is not used by the application.

As such we feel that this is not a feature that we should add to the core framework of Angular. Instead, it would be great for you to continue your current implementation in a separate library. Once it is stable we would be happy to add it to our list of resources linked from our docs website: https://angular.io/resources?category=development

Thank you again for helping to make Angular applications better, and sorry that we are not going to add it to the framework.

**Comment by Chiff** [comment]
Hi @petebacondarwin ,

We are sorry to hear that, but we understand the reasoning behind the maintenance cost and why it’s not needed internally.

However, we would be happy to change your mind about the neediness of this functionality. One might say that working with dates is a **crucial part of developing an application** (dates are everywhere - from small to big applications - humanity is kinda attached to that time concept 😄 )



**1.  Consider the view of the developer (user of Angular)** 

Many of the functions implemented by Angular are available in order to provide developers with enough tools for **easier application development** - it’s one of the reasons why this framework is so widely used.

Considering the fact that Angular already provides date formatting functionality for dates, it’s important to note that **parsing functionality seems missing**. While you might point out that other formatters (like `currencyPipe`) don't have parses, we believe you would agree **date parsing is not as trivial**. 

We are sure that extending the core framework with our functionality would **simplify and unify date operations** throughout applications (without breaking existing ones) while being flexible/generic enough.

To summarize the potential of this function:
* no need to use external libraries,
* easier development of angular libraries working with date,
* easier date manipulation, accounting multiple external APIs with different time formats, locales, time zones.



**2. The current situation is that developers are looking for other solutions**

Because `parseDate()` is (almost) a simple function, we feel that it would be a waste to be a standalone library, mainly because it is dependent on existing features of the core framework. Also, maintenance costs of developing standalone library would be much higher, compared to preparation for a new release. 

As a matter of fact, we have already found one existing library (https://www.npmjs.com/package/angular-dateParser) that tried to do the same as you are suggesting. It was intended for quite an older version of angular and yet it seems to have **+/-800 weekly downloads**, which is proof why **it’s really needed functionality for the core framework**.
 


**3. We agree that adding new features might increase maintenance costs**

Therefore **we would like to offer our help and share our resources**. We believe we can come to an agreement with your team that we will take part in covering for parseDate and also formatDate (also in upcoming features)

We hope you will revisit the discussion.


On behalf of @AnnotationSro dev team,
Sincerely,
Martin Filo

**Comment by petebacondarwin** [comment]
Thanks again for your commitment to helping Angular. It is appreciated.
While I can empathise with your points it does not really change the situation.

There are a lot of 3rd party Angular libraries out there that cover even more vital aspects of application development. Consider things like ngrx or the many component libraries. Just because it is useful to a number of developers, doesn't mean that it should necessarily be in the core.

Angular was always designed from the start to be an extendable platform and as such libraries adding additional functionality has always been part of its ecosystem.

As a team we don't have the capacity to maintain lots of the code that we own already. So adding even more is not something we can consider right now. I appreciate your offer to share your resources to help with this feature, but I believe that this effort would be best placed in creating and maintaining a high quality library that developers who need this feature will go to.

**Comment by Chiff** [comment]
Thanks for your time and patience explaining your point of view. We understand and respect your opinion.
