### ISSUE TITLE
Wrong import in the app.module.ts file. [Tour of  Heroes]

### ISSUE THREAD

**Issue by Ambuj8105** [angular/angular#41160]
Docs issue

Tour of Heroes has wrong import in the app.module.ts file. It can be seen in the final code review section in the Add Service Page

### What's the affected URL?**
https://angular.io/tutorial/toh-pt4

### Expected vs Actual Behavior**
If go through the documentation. We have not generated hero details component till Add service Page. So it expected that app module.ts should only contains necessary import.

Actual - It contains import { HeroDetailComponent } from './hero-detail/hero-detail.component';

## 📷Screenshot
![test](https://user-images.githubusercontent.com/76941074/110684364-13955a80-8203-11eb-9ee6-7aaea1e23346.png)

**Comment by MichaelDjs** [comment]
Hey @Ambuj8105 

maybe you missed one step: The HeroDetailComponent gets imported in [Make the HeroDetailComponent](https://angular.io/tutorial/toh-pt3#make-the-herodetailcomponent). In this section `ng generate component hero-detail` gets executed and this will automatically import the newly created hero-detail-component.ts to the app.module.ts file.

**Comment by Ambuj8105** [comment]
HI MichaelDjs

I checked and i saw the missed step.  Thanks
