### ISSUE TITLE
Crawling Problem

### ISSUE THREAD

**Issue by rajeshkumar1977** [angular/angular#41170]
We developed clickandhire.in in February first week. First time index in google on 4 to 16 feb. then after not crawling in google for the last one month. What is the problem with my site? I have updated the sitemap and robots.txt. but not recrawl in google. We inspect the URL but any impacts on the url.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/).

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
