### ISSUE TITLE
export '?isSubscribable' was not found in '@angular/core'

### ISSUE THREAD

**Issue by ericfoongcheesoon** [angular/angular#41172]
I use the HttpClient module in angular 11

import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

This is the content of package.json:
{
  "name": "application",
  "version": "1.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "dev:ssr": "ng run application:serve-ssr",
    "serve:ssr": "node dist/server/main.js",
    "build:ssr": "ng build --prod && ng run application:server:production",
    "prerender": "ng run application:prerender"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "1.1.0",
    "@angular/animations": "11.0.5",
    "@angular/cdk": "11.0.3",
    "@angular/common": "^11.2.5",
    "@angular/compiler": "11.0.5",
    "@angular/core": "^11.2.5",
    "@angular/flex-layout": "11.0.0-beta.33",
    "@angular/forms": "11.0.5",
    "@angular/http": "^7.2.16",
    "@angular/material": "11.0.3",
    "@angular/platform-browser": "11.0.5",
    "@angular/platform-browser-dynamic": "11.0.5",
    "@angular/platform-server": "11.0.5",
    "@angular/router": "11.0.5",
    "@fullcalendar/core": "^5.5.1",
    "@nguniversal/express-engine": "11.0.1",
    "@ngx-translate/core": "13.0.0",
    "@ngx-translate/http-loader": "6.0.0",
    "@swimlane/ngx-charts": "16.0.0",
    "angular-in-memory-web-api": "0.11.0",
    "chart.js": "^2.9.4",
    "express": "^4.17.1",
    "fullcalendar": "^5.5.1",
    "google-maps": "^4.3.3",
    "google-recaptcha": "^1.1.0",
    "ngx-input-file": "10.2.0",
    "ngx-pagination": "5.0.0",
    "ngx-perfect-scrollbar": "10.0.1",
    "ngx-spinner": "10.0.1",
    "ngx-swiper-wrapper": "10.0.0",
    "primeflex": "2.0.0",
    "primeicons": "^4.1.0",
    "primeng": "^11.3.0",
    "quill": "^1.3.7",
    "rxjs": "6.6.3",
    "swiper": "6.4.5",
    "tslib": "2.0.3",
    "zone.js": "0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.1100.5",
    "@angular/cli": "^11.2.4",
    "@angular/compiler-cli": "11.0.5",
    "@angular/language-service": "11.0.5",
    "@nguniversal/builders": "11.0.1",
    "@types/express": "4.17.0",
    "@types/jasmine": "3.6.2",
    "@types/jasminewd2": "2.0.8",
    "@types/node": "14.14.19",
    "codelyzer": "6.0.1",
    "jasmine-core": "3.6.0",
    "jasmine-spec-reporter": "6.0.0",
    "karma": "5.2.3",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage-istanbul-reporter": "3.0.3",
    "karma-jasmine": "4.0.1",
    "karma-jasmine-html-reporter": "1.5.4",
    "protractor": "7.0.0",
    "ts-node": "9.1.1",
    "tslint": "6.1.2",
    "typescript": "4.0.5"
  }
}

When I execute "ng serve", the command prompt shows "export '?isSubscribable' was not found in '@angular/core'", and then application fail to start.

The problem only happens when I use the Httpclient module. When I removed the httpclient module, then the application works fine.

**Comment by JoostK** [comment]
Heya, please ensure that you're using the same versions of `@angular` packages. Only `@angular/cli`, `@angular/cdk, `@angular/material`, and `@angular/flex-layout` can deviate from the main `@angular` packages (and `@angular/http` should ideally be migrated away from, as it's not been released since Angular 7 or 8)

**Comment by ericfoongcheesoon** [comment]
How to make sure these packages are in same version? Use the same version number?

Which version can work properly?

**Comment by JoostK** [comment]
Running `ng update @angular/core @angular/cli @angular/material` should get you a long way. Possibly it needs the `--force` flag.

**Comment by ericfoongcheesoon** [comment]
I delete node_modules, execute "npm install", then "ng update @angular/core @angular/cli @angular/material --force", then "ng serve"

The command prompt shows this error:
Error: ./node_modules/@angular/cdk/__ivy_ngcc__/fesm2015/table.js 2338:8-32 "export '??staticViewQuery' (imported as '?ngcc0') was not found in '@angular/core'

**Comment by JoostK** [comment]
That's still the same issue; incompatible versions. If the `ng update` step didn't resolve it then I suggest you manually update the version strings in package.json to be aligned, at least for the following package:

```
"@angular/animations": "11.0.5",
"@angular/common": "^11.2.5",
"@angular/compiler": "11.0.5",
"@angular/core": "^11.2.5",
"@angular/forms": "11.0.5",
"@angular/platform-browser": "11.0.5",
"@angular/platform-browser-dynamic": "11.0.5",
"@angular/platform-server": "11.0.5",
"@angular/router": "11.0.5",

"@angular/compiler-cli": "11.0.5",
"@angular/language-service": "11.0.5",
```

as you can see above, `@angular/core` and `@angular/common` are at version `^11.2.5` while the rest is still at `11.0.5` and that is not supported.

**Comment by ericfoongcheesoon** [comment]
I change all the packages you mentioned to 11.0.5, but I still get this error:
Error: ./node_modules/@angular/cdk/ivy_ngcc/fesm2015/table.js 2338:8-32 "export '??staticViewQuery' (imported as '?ngcc0') was not found in '@angular/core'

**Comment by ericfoongcheesoon** [comment]
Can you please help to check the problem?

**Comment by JoostK** [comment]
The new error in your latest comment indicates the same problem still: multiple incompatible versions of Angular. It could be that e.g. symlinks are causing trouble, but I have no way of knowing without the current information. What does `ng version` output?

**Comment by ericfoongcheesoon** [comment]
The result of "ng version ":

Angular CLI: 11.2.4
Node: 12.2.0
OS: win32 x64

Angular: 11.2.5
... common, core
Ivy Workspace: Yes

Package                             Version
------------------------------------------------------
@angular-devkit/architect           0.1100.5
@angular-devkit/build-angular       0.1100.5
@angular-devkit/core                11.0.5
@angular-devkit/schematics          11.2.4
@angular/animations                 11.0.5
@angular/cdk                        11.2.4
@angular/cli                        11.2.4
@angular/compiler                   11.0.5
@angular/compiler-cli               11.0.5
@angular/flex-layout                11.0.0-beta.33
@angular/forms                      11.0.5
@angular/http                       7.2.16
@angular/language-service           11.0.5
@angular/material                   11.2.4
@angular/platform-browser           11.0.5
@angular/platform-browser-dynamic   11.0.5
@angular/platform-server            11.0.5
@angular/router                     11.0.5
@nguniversal/builders               11.0.1
@nguniversal/express-engine         11.0.1
@schematics/angular                 11.2.4
@schematics/update                  0.1102.4
rxjs                                6.6.3
typescript                          4.0.5

**Comment by ericfoongcheesoon** [comment]
For your information, I restore my project to previous version.
then "npm install", then "npm update", then "ng serve", now the application works properly.

this is the package.json:

"dependencies": {
    "@agm/core": "1.1.0",
    "@angular/animations": "11.0.5",
    "@angular/cdk": "11.0.3",
    "@angular/common": "11.0.5",
    "@angular/compiler": "11.0.5",
    "@angular/core": "11.0.5",
    "@angular/flex-layout": "11.0.0-beta.33",
    "@angular/forms": "11.0.5",
    "@angular/material": "11.0.3",
    "@angular/platform-browser": "11.0.5",
    "@angular/platform-browser-dynamic": "11.0.5",
    "@angular/platform-server": "11.0.5",
    "@angular/router": "11.0.5",
    "@fullcalendar/core": "^5.5.1",
    "@nguniversal/express-engine": "11.0.1",
    "@ngx-translate/core": "13.0.0",
    "@ngx-translate/http-loader": "6.0.0",
    "@swimlane/ngx-charts": "16.0.0",
    "angular-in-memory-web-api": "0.11.0",
    "chart.js": "^2.9.4",
    "express": "^4.17.1",
    "fullcalendar": "^5.5.1",
    "google-maps": "^4.3.3",
    "google-recaptcha": "^1.1.0",
    "ngx-input-file": "10.2.0",
    "ngx-pagination": "5.0.0",
    "ngx-perfect-scrollbar": "10.0.1",
    "ngx-spinner": "10.0.1",
    "ngx-swiper-wrapper": "10.0.0",
    "primeicons": "^4.1.0",
    "primeng": "^11.0.0",
    "primeflex": "2.0.0",
    "quill": "^1.3.7",
    "rxjs": "6.6.3",
    "swiper": "6.4.5",
    "tslib": "2.0.3",
    "zone.js": "0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.1100.5",
    "@angular/cli": "^11.2.1",
    "@angular/compiler-cli": "11.0.5",
    "@angular/language-service": "11.0.5",
    "@nguniversal/builders": "11.0.1",
    "@types/express": "4.17.0",
    "@types/jasmine": "3.6.2",
    "@types/jasminewd2": "2.0.8",
    "@types/node": "14.14.19",
    "codelyzer": "6.0.1",
    "jasmine-core": "3.6.0",
    "jasmine-spec-reporter": "6.0.0",
    "karma": "5.2.3",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage-istanbul-reporter": "3.0.3",
    "karma-jasmine": "4.0.1",
    "karma-jasmine-html-reporter": "1.5.4",
    "protractor": "7.0.0",
    "ts-node": "9.1.1",
    "tslint": "6.1.2",
    "typescript": "4.0.5"
  }
