### ISSUE TITLE
Can not send 'null' to BehaviorSubject

### ISSUE THREAD

**Issue by OrhanOzkercin** [angular/angular#41171]
I can not set null to BehaviorSubject. How to handle this situation, could not figure it out.
![image](https://user-images.githubusercontent.com/25130814/110752827-d490f480-8256-11eb-85c5-be2edd0bf4a8.png)

**Comment by AwesomeObserver** [comment]
Is not the Angular API, this is the RxJS
You should fix a type in the BehaviorSubject to `<User | null>`

**Comment by OrhanOzkercin** [comment]
> User | null

Thank you for your response, I wrote the question here because rxjs coming default with Angular, if it was a mistake sorry for that. On the other hand I already tried your solution but another problem I faced is this: 

![image](https://user-images.githubusercontent.com/25130814/110758077-263c7d80-825d-11eb-8663-bdb602dc5922.png)

**Comment by destus90** [comment]
@OrhanOzkercin 
```
public get currentUserValue(): User | null {
 ...
}
```
