### ISSUE TITLE
docs: add section on how to client side render the app when using angular universal

### ISSUE THREAD

**Issue by eneajaho** [angular/angular#41187]
# 📚 Docs or angular.io bug report

### Description

In the docs, there isn't a section that explains how to opt-out server-side rendering and to use client-side rendering when using @angular/universal.

### What's the affected URL?**
 https://angular.io/guide/universal#filtering-request-urls

##  Simple solution
<pre><code>
/**
 * EXCLUDED_ROUTES contains all the paths that we don't want to render on the server
 *  Examples:
 *    '/test'
 *    '/back(/)?*' // regex: string starts with /back, '/' is optional, '*' it can be anything
 */
const EXCLUDED_ROUTES: string[] = [
  '/test',
  '/auth(/)?*',
  '/back(/)?*',
];

/**
 * Is used to exclude the routes from rendering on the server. Ex. Auth Page, Admin Page
 * To add or remove excluded routes modify the EXCLUDED_ROUTES array
 */
server.get(EXCLUDED_ROUTES, (req, res) => {
  res.sendFile(join(distFolder, 'index.html'));
});
</code></pre>

Should I create a pull request and add this information?

**Comment by Niladri24dutta** [comment]
Is this still open?

**Comment by mgechev** [comment]
We did an advancement of hybrid rendering with prerendering and SSR, but have not yet discussed what are the best practices for introducing CSR into the story.

I'd close the issue for now and we can reevaluate once this is an officially supported use case, rather than a server update.
