### ISSUE TITLE
Docs: Update testing coverage guide

### ISSUE THREAD

**Issue by mycql** [angular/angular#41188]
# 📚 Docs or angular.io bug report

### Description

https://angular.io/guide/testing-code-coverage section of angular website shows outdated section on **Code coverage enforcement**.

Karma coverage documentation says otherwise:

https://github.com/karma-runner/karma-coverage/blob/master/docs/configuration.md

<pre><code>
coverageReporter: {
  check: {
    global: {
      statements: 50,
      branches: 50,
      functions: 50,
      lines: 50,
      excludes: [
        'foo/bar/**/*.js'
      ]
    },
    each: {
      statements: 50,
      branches: 50,
      functions: 50,
      lines: 50,
      excludes: [
        'other/directory/**/*.js'
      ],
      overrides: {
        'baz/component/**/*.js': {
          statements: 98
        }
      }
    }
  }
}
</code></pre>

### What's the affected URL?**
https://angular.io/guide/testing-code-coverage 

## 📷Screenshot
Current documentation:
![image](https://user-images.githubusercontent.com/4702161/110884493-23569100-8320-11eb-9719-fbeab8b4ed4e.png)

Karma coverage doc:
![image](https://user-images.githubusercontent.com/4702161/110884866-bbed1100-8320-11eb-9f08-65e4a637f299.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by iRealNirmal** [comment]
@AndrewKushnir isn't this covered under
https://github.com/angular/angular/pull/41246

**Comment by AndrewKushnir** [comment]
@mycql thanks for reporting the issue. As @iRealNirmal mentioned above, the docs were updated to avoid references to the deprecated `karma-coverage-istanbul-reporter` package. I'm closing this ticket, but feel free to reopen if needed.

@iRealNirmal thanks for looking into that.
