### ISSUE TITLE
Adding click event handler with capture set to true interferes with click handlers on items generated by NgFor.

### ISSUE THREAD

**Issue by spectacular-clarinet** [angular/angular#41192]
# 🐞 bug report

### Description
When adding an event listener for click events onto the document object with capture set to true, there is a strange edge case where the click handler on items generated by an ngFor loop is not called. This only seems to happen when the array is returned from a function (and thus recreated on rerender). This doesn't happen if capture is not set to true.

Additionally, it seems to interfere with preventing any default action on those ngFor items, e.g. click on <a [routerLink]="..."> elements will reload the application rather than causing an internal routing change.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-w6utr9?devtoolsheight=33&file=src/app/app.component.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>
  "dependencies": {
    "@angular/animations": "^11.0.8",
    "@angular/common": "^11.0.8",
    "@angular/compiler": "^11.0.8",
    "@angular/core": "^11.0.8",
    "@angular/forms": "^11.0.8",
    "@angular/platform-browser": "^11.0.8",
    "@angular/platform-browser-dynamic": "^11.0.8",
    "@angular/router": "^11.0.8",
    "core-js": "^3.8.2",
    "rxjs": "^6.6.3",
    "tslib": "^2.1.0",
    "zone.js": "^0.11.3"
  }
</code></pre>

**Comment by jelbourn** [comment]
@mhevery I suspect this is working as expected. My hunch is that setting `useCapture` somehow affects change detection timing such that the items in the second `ngFor` get destroyed and re-created before their click handler is called. Do you know off the top of your head is it would work this way?

**Comment by mhevery** [comment]
This is not expected at all and seems like a bug. A quick investigation seems to suggest that this is an issue with Zone.js. (@JiaLiPassion can you look?)

**Comment by JiaLiPassion** [comment]
@spectacular-clarinet , this is not an issue, since you are using a function to return an arrary.
```
<div *ngFor="let _ of getArray()" (click)="click()">
  CLICK ME (Blocked)
</div>
```

```
getArray(): any[] {
    return [{ id: 1 }];
  }
```

So every `change detection` will generate a new `div` of `ngFor`, so the current process is, 
1. a div (let us call it `div1`) is created by `ngFor` when the UI is first rendered. A click handler is added to this div(`div1`), and another capture event handler is added to the document.
2. user click the div (`div1`), the document capture event handler is triggered, and also trigger a change detection, which cause `ngFor` to get a new array and generate a new div (let us call it `div2`), and the `div1` is removed from the dom. So the event handler will not be triggered on `div1` any longer.

So this is working as expected, so is there any reason you want to use a function to return the data source of `ngFor`?

**Comment by spectacular-clarinet** [comment]
I support a library and wish to use useCapture: true in a directive but not to break existing code that might exist in the application, over which I have no control.

**Comment by ChellappanRajan** [comment]
If I add track By function to ngFor, it's working fine  https://stackblitz.com/edit/angular-httpsgithubcomangularangularissues41192?file=src/app/app.component.ts

**Comment by spectacular-clarinet** [comment]
I am aware that the trackBy solves the issue, presumably by preventing rerender, but I don't have control over all the code in the application so I can't add trackBy in the appropriate places. Is there no alternative other than warning users that they should avoid this particular edge case?

**Comment by JiaLiPassion** [comment]
I don't think there is a warning here since this is a `valid` use case, sometimes the user may want to change `data source` by a function. If you can provide your project repo, maybe we can find a better solution.

**Comment by spectacular-clarinet** [comment]
Can't link to the actual repo, but I can give a gist of what I'm trying to achieve. We have a use case for a directive that detects when there is a click event outside of the host element. Our original implementation involved attaching a click event to the document and listening for changes in the bubble phase, the comparing the event target with the host element to determine if it was outside the element. We were running in to issues where stopPropagation was used elsewhere in the application and thus preventing the listener from firing, so were hoping that useCapture would solve this for us. Unfortunately we came across this unexpected side-effect where other click handlers were being interfered with due to rerendering being triggered.

**Comment by JiaLiPassion** [comment]
@spectacular-clarinet , sure, if you can provide a repo with detailed requirement, I would like to look into it.

**Comment by spectacular-clarinet** [comment]
I'm afraid I can't link to it, as it isn't publicly available. The minimal reproduction I linked is essentially a distilled version of the code in that repo, and replicates the same issue present there.

**Comment by JoostK** [comment]
Just chiming in here: this does appear to work if you bootstrap with `ngZoneEventCoalescing`:

```ts
platformBrowserDynamic().bootstrapModule(AppModule, { ngZoneEventCoalescing: true })
```

because then the capture event does not immediately trigger change detection for the `div` with a pending click event to be removed before the click event is actually dispatched.

**Comment by HipsterSantos** [comment]
@spectacular-clarinet  could you link the **repo**   ,in order to help you solve this .

**Comment by JiaLiPassion** [comment]
Yeah, @JoostK 's solution is great, you can also try to use 
```
ngZone.runOutsideOfAngular(() => {
  document.addEventListener(...);
})
``` 
to let `document` not trigger change detection.
But still using a function to return the data source of `ngFor` may cause other unexpected behaviors.

**Comment by spectacular-clarinet** [comment]
@JoostK That's an interesting configuration option. I don't think it solves my particular problem, since I don't have control over how the applications consuming my library are bootstrapped, but it's useful to know, thanks.

@JiaLiPassion That does seem to work for logging in the console, but in order for there to be any change in the application as a result of the click event, surely change detection will have to be triggered at some point? I'm not sure where that point would be.

**Comment by JiaLiPassion** [comment]
@spectacular-clarinet , I am not sure I understand your requirement, could you update your stackblitz to describe it?

**Comment by spectacular-clarinet** [comment]
> @spectacular-clarinet , I am not sure I understand your requirement, could you update your stackblitz to describe it?

https://stackblitz.com/edit/angular-4zxfkb?devtoolsheight=33&file=src/app/app.component.ts

For example here, the DOM doesn't update to reflect any changes in document click count because the listener is added and the handler is running outside of Angular. It only updates when you click the items and their click events trigger a change detection cycle. If the handler runs in the Angular zone we end up with the same problem as before, so I'm wondering when/how I should trigger change detection.

**Comment by JiaLiPassion** [comment]
@spectacular-clarinet , so you still want the `capture event listener` of document to trigger change detection? I assume you just want to detect whether there is click event there or not. So what is your exact requirement?

**Comment by spectacular-clarinet** [comment]
@JiaLiPassion I want it to detect if there is a click event, but then the UI needs to eventually react to that in some way, not just log to the console.

My exact requirement is that I need to detect when a click event has been triggered outside an element, and this should not be prevented by the event being cancelled by stopPropagation, and should not interfere with other click event handlers. For example, say there is a side-menu that should close when the user clicks outside of it, then the UI needs to react to that event by hiding the element in the DOM.

**Comment by JiaLiPassion** [comment]
@spectacular-clarinet , could you post an example (such as the `side-menu` case) to describe the case?

**Comment by gkalpak** [comment]
@spectacular-clarinet, (if I understand correctly) I believe your's is an edge case and supporting it is probably outside the scope of Angular/Zone.js. (I.e. Angular/Zone.js work as intended here.)

To summarize (my understanding of) the problem/usecase:
1. You want to be notified for `click` events on `document`.
2. You want to have change detection (CD) run for these `click` events.
3. You want to capture these `click` events on `document` even if the event's propagation is stopped from a descendant element.
4. You don't want to trigger CD before the event has reached its target.

As a work-around, you could do the following:
1. Register both a `capture` and non-`capture` listener for `click` events on `document`.
2. In the `capture` listener, schedule an asynchronous task (`setTimeout()`, `requestAnimationFrame()`, `Promise`, etc.) to trigger CD.
3. If the non-`capture` listener is triggered, cancel the asynchronous task from the previous step and trigger CD immediately.

_**NOTE 1:** This could result in an extra CD run (if CD did already run as part of the regular event flow - which is the case most of the time). Depending on how much control you have over where this logic is used, you might be able to track whether CD has run and not run it again. Alternatively, you might be able to run CD on a particular element, if that is sufficient for your usecase._

_**NOTE 2:** The logic can be simplified further by getting rid of the non-`capture` listener and always triggering CD asynchronously. (The downside is that there might be a slight delay.)_

Here is how the code for this could look like:

```ts
constructor(zone: NgZone) {
  zone.runOutsideAngular(() => {
    const runCd = () => {
      console.log('running CD');
      zone.run(() => undefined);
    };
    let timeoutId = null;

    document.addEventListener('click', () => {
      console.log('document click (capture)');

      this.documentClickCount++;

      if (timeoutId !== null) {
        clearTimeout(timeoutId);
      }
      timeoutId = setTimeout(() => {
        console.log('timeout triggered');
        runCd();
      }, 0);
    }, true);

    document.addEventListener('click', () => {
      console.log('document click (bubble)');

      if (timeoutId !== null) {
        clearTimeout(timeoutId);
      }
      runCd();
    });
  });
}
```

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
