### ISSUE TITLE
MicroFrontend with Angular OpenComponent

### ISSUE THREAD

**Issue by m-korkut** [angular/angular#41190]
Is there any example of using openComponent with angular in microFrontend structure?

**Comment by mlc-mlapis** [comment]
@m-korkut What do you mean by `OpenComponent`?

**Comment by vugar005** [comment]
You mean approach for microfront end? I suggest this [book ](https://go.nrwl.io/angular-enterprise-monorepo-patterns-new-book ) and talks of Malfred on youtube.

**Comment by petebacondarwin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mlc-mlapis** [comment]
@vugar005 No, it was meant just the concrete name `OpenComponent` you used without any context.

**Comment by m-korkut** [comment]
I'm talking about OpenComponent. Does angularJS have an instance in [OpenComponent((https://opencomponents.github.io/).

**Comment by mlc-mlapis** [comment]
@m-korkut It's Angular and not AngularJS, to be precise.

Citation at https://github.com/opencomponents/oc/wiki#components-management

> The view in charge to output the final markup. OC supports Handlebars and Jade out of the box, but comes with a powerful template system to support components built with any javascript UI framework like React, Angular, Vue ...

Btw, I don't know all details, as I have read only some overview, but I didn't find probably the most important fact, and it is, on which W3C specification is OC based. Is it WebComponents standard or not? I didn't find the exact mentioning of it. If it's WebComponents then there is full compatibility with Angular Elements (the brand name for Angular components in WebComponents world.)
