### ISSUE TITLE
Module parse failed: Identifier 'ɵngcc0' has already been declared

### ISSUE THREAD

**Issue by retorres9** [angular/angular#41198]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

 No

### Description

When import the Forms Module I get an error message, It doesn't matter where the FormsModule is imported, If remove the FormsModule import the application compile succesfully

## 🔥 Exception or Error
<pre><code>
Error: ./node_modules/@angular/forms/__ivy_ngcc__/fesm2015/forms.js 27:12
Module parse failed: Identifier 'ɵngcc0' has already been declared (27:12)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders.
|  */
| import * as ɵngcc0 from '@angular/core';
> import * as ɵngcc0 from '@angular/core';
| const NG_VALUE_ACCESSOR = new InjectionToken('NgValueAccessor');
|
</code></pre>

## 🌍  Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.4
Node: 10.15.3
OS: win32 x64

Angular: 11.2.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.4
@angular-devkit/build-angular   0.1102.4
@angular-devkit/core            11.2.4
@angular-devkit/schematics      11.2.4
@angular/cli                    11.2.4
@schematics/angular             11.2.4
@schematics/update              0.1102.4
rxjs                            6.6.6
typescript                      4.1.5
</code></pre>

**Comment by petebacondarwin** [comment]
Please can you provide a reproduction of this problem that we can debug?
It looks like you have, somehow, managed to run ngcc twice on the same package. Perhaps this is due to symlinking the packages??

**Comment by JoostK** [comment]
I found the problem and will have a fix available in a bit.

**Comment by shepherd1530** [comment]
Is there any fix available yet. Just encountered the error too.

**Comment by petebacondarwin** [comment]
This was fixed by #41209 which landed in 11.2.6 and 12.0.0-next.5.
