### ISSUE TITLE
docs: content with new inline code style is difficult to read

### ISSUE THREAD

**Issue by bampakoa** [angular/angular#41196]
# 📚 Docs or angular.io bug report

### Description

 As I was reading some guides through the angular.io, I had a hard time reading some of them due to the new style for inline code. In cases, where the content contained a lot of code, I found it difficult to differentiate between the raw text and the code. I have attached an example from the Structural Directives guide for your convenience.
I think that if the font size and style were different for inline code, reading would be much easier. 

### What's the affected URL?**
 https://angular.io/...

## 📷Screenshot

![image](https://user-images.githubusercontent.com/7170892/110996504-b5908080-8384-11eb-9a53-685ec60f9245.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by petebacondarwin** [comment]
> I found it difficult to differentiate between the raw text and the code.

Did you mean to say "differentiate"? It is pretty clear which is code and which is normal text.
Did you mean that the code is off-putting and makes it difficult to read the text fluently?

**Comment by petebacondarwin** [comment]
Would it be less jarring to match the `inline code` used in the github UI?

**Comment by bampakoa** [comment]
>Did you mean that the code is off-putting and makes it difficult to read the text fluently?

Yes, that is actually what I wanted to say. It happens mostly in cases where there are a lot of inline code occurrences and I need to go from the text to the code block that refers and back again multiple times.

>Would it be less jarring to match the inline code used in the github UI?

That would be a great idea. Generally, I think that a different font style with smaller size would do the job

**Comment by gkalpak** [comment]
I am confused. What is the difference of GitHub UI's inline code style and ours?

**Comment by petebacondarwin** [comment]
The font size of the inline code is set to (I think) 87%, which makes it more similar to the size of the non-code font.
Also I think that the background is slightly lighter...

**Comment by gkalpak** [comment]
We also set the code font-size to 90% to make it the same size as non-code font. 
(Our background is indeed darker, though.)
