### ISSUE TITLE
When we load module built with 11.2.5 it crashes with record.factory is not a function on Angular 11.2.4 shell

### ISSUE THREAD

**Issue by vasicvuk** [angular/angular#41193]
# Description

We have dynamic module loading inside our Angular project. We built one of the modules to Ivy with packages of 11.2.5 and tried to load it within the app built with 11.2.4 it crashes with function.

Fixing package.json version to 11.2.4 solves the issue.

## 🔥 Exception or Error
<pre><code>
main.ts:18 TypeError: record.factory is not a function
    at R3Injector.hydrate (core.js:16747)
    at R3Injector.get (core.js:16509)
    at core.js:16439
    at Set.forEach ()
    at new R3Injector (core.js:16435)
    at createInjector (core.js:16386)
    at new NgModuleRef$1 (core.js:35526)
    at NgModuleFactory$1.create (core.js:35629)
    at core.js:41676
    at ZoneDelegate.invoke (zone-evergreen.js:365)
</code></pre>

# 🐞 bug report

### Affected Package
@angular/* 11.2.5

### Is this a regression?

The compatiblity within the same Major version worked so far.

## 🌍  Your Environment

**Angular Version: 11.2.4 and 11.2.5**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 11.2.4
Node: 10.16.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.4
@angular-devkit/core         11.2.4
@angular-devkit/schematics   11.2.4
@schematics/angular          11.2.4
@schematics/update           0.1102.4
</code></pre>

**Comment by JoostK** [comment]
Packages must be compiled and ran using the exact same version of Angular; any other combination is not supported and likely to break in subtle ways.

**Comment by vasicvuk** [comment]
@JoostK  Why then there is SemVer for god sake if there are such a breaks in Patch releases ?

**Comment by petebacondarwin** [comment]
Ivy is not a public API. so you cannot expect it not to change between patch versions.

**Comment by vasicvuk** [comment]
@petebacondarwin Then there should be statement somewhere with big letters informing users that they should not use Ivy yet as it is not backwards compatible as VE is until VE is completely replaced for example.

**Comment by petebacondarwin** [comment]
Do you mean this? https://angular.io/guide/creating-libraries#publishing-your-library

> For now, it is not recommended to publish Ivy libraries to NPM because Ivy generated code is not backward compatible with View Engine, so apps using View Engine will not be able to consume them. Furthermore, the internal Ivy instructions are not yet stable, which can potentially break consumers using a different Angular version from the one used to build the library.
> 
> When a published library is used in an Ivy app, the Angular CLI will automatically convert it to Ivy using a tool known as the Angular compatibility compiler (ngcc). Thus, publishing your libraries using the View Engine compiler ensures that they can be transparently consumed by both View Engine and Ivy apps.

**Comment by JoostK** [comment]
I believe @vasicvuk's situation does not involve libraries, but the fact that generated template code is considered internal and non-stable is true even when no libraries are involved. This was also true for VE; its generated code was internal and not stable much like Ivy's instructions are internal and non stable.

Angular packages do specify their peer dependencies of other framework packages to be of the identical version. Since the generated code is internal to the runtime (be it VE or Ivy) we don't consider this as semver breaking.

**Comment by vasicvuk** [comment]
Not because I am not publishing any library and it is not the same context. This made me assumed that you will brake functionalities between major versions so the compatibility would not be the same at it was for VE using different Angular versions. (ng10 and ng11 for example)

Angular CLI is something that is not available in runtime when importing modules

**Comment by vasicvuk** [comment]
@JoostK  This means that having micro fronted with some shared dependencies with Angular is not possible unless all micro frontends bundle all dependencies within?

**Comment by JoostK** [comment]
If all those microfrontends share a single Angular runtime, then yes. This constraint hasn't changed with Ivy, it's more to do with the fact that Ivy is actively being developed for changes to occur still. And yes, this includes changes in patch releases as it's sometimes necessary for a bugfix.

**Comment by JoostK** [comment]
Don't get me wrong, I do understand where you're coming from and I think your request in #41194 is very reasonable.

**Comment by vasicvuk** [comment]
@JoostK  I fully understand, thanks for clarifying. So the answer is it is currently not possible to share any Angular components between micro frontends because of VE and Ivy breaking changes happen in Minor and Patch changes.

I will explain this scenario with micro frontends  in feature request as well. Thanks
