### ISSUE TITLE
 Vulnerability in Node.js Package: y18n ≤ 5.0.4

### ISSUE THREAD

**Issue by GowriAradhya** [angular/angular#41215]
@angular/compiler-cli is having dependency on Yargs ,Yargs is having internal dependency on y18n. 
Found Vulnerability in Node.js Package: y18n ≤ 5.0.4
https://snyk.io/vuln/SNYK-JS-Y18N-1021887

After updating @angular/compiler-cli to latest version(11.2.5 ),we found that y18n package version is not getting updated .

Thank you

**Comment by jelbourn** [comment]
The issue you reference is for server environments; we generally don't expect `compiler-cli` to run in such environments

**Comment by GowriAradhya** [comment]
On creating new project in angular, @angular/compiler-cli is having dependency on Yargs , Yargs is having internal dependency on y18n. Found Vulnerability in y18n.
