### ISSUE TITLE
How are you handling request and response models

### ISSUE THREAD

**Issue by OrhanOzkercin** [angular/angular#41217]
I wonder what is the right way to handle request and response model in Angular.  Should we always create 2 different model for get and post operations, or can keywords like partial fix our problem? 

Lets say I want to create user and API asks me those fields: 

`
name: string;
username: string;
canRead: boolean;
roleId: string;
`
 and some other fields.

But when we get user we have also some additional fields. How to handle the difference between those models

Lets say the model when we get user:

`
name: string;
username: string;
canRead: boolean;
roleName: string; 
roleId: string;
`

**Comment by PierreDemailly** [comment]
Hi @OrhanOzkercin Do what make the more sense for you to consume your api, I see 2 ways
* use optionnal property:
```typescript
// roleName is optionnal, will be undefined when creating user, 
// will have a value when retrieve user, you have only one model.
roleName?: string;
```

* use dedicated model for created user.
```
.get<User> 
.post<CreatedUser>
```

I would check API models, if API use 2 models, one for CREATING and one for READ, then I would use 2 models frontside. If API use one model and doesn't require xxx fields for CREATING, I would set optionnal property in the model frontside.

**Comment by OrhanOzkercin** [comment]
[Here ](https://stackoverflow.com/questions/66633699/how-to-create-request-and-response-models-in-angular) are some other ideas about this topic, if someone interested!
