### ISSUE TITLE
AoT error with `@Inject` and global interface type

### ISSUE THREAD

**Issue by seravifer** [angular/angular#41218]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/common maybe

### Is this a regression?

Probably yes

### Description

I have a constructor that uses @Inject to get the `DOCUMENT` global value, and references her global interface from Typescript `Document`. When I compile the lib, I get an error.

## 🔬 Minimal Reproduction

Repo: [https://github.com/seravifer/angular-playground](https://github.com/seravifer/angular-playground)
<pre><code>
import { Injectable, Inject } from '@angular/core';
import { DOCUMENT } from '@angular/common';

@Injectable({
  providedIn: 'root'
})
export class LibraryPlaygroundService {

  constructor(
    @Inject(DOCUMENT) public document: Document
  ) { }

 ...

}
</code></pre>

## 🔥 Exception or Error
With command `ng build library-playground --prod`
<pre><code>
 .../angular-playground/projects/library-playground/src/lib/library-playground.service.ts:10:40: Metadata collected contains an error that will be reported at runtime: Could not resolve type Document.
  {"__symbolic":"error","message":"Could not resolve type","line":9,"character":39,"context":{"typeName":"Document"}}
See "...\savilafe\AppData\Local\Temp\ng-Vq4KZV\angular-errors.log" for further details.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.1.4
Node: 14.6.0
OS: win32 x64

Angular: 11.2.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.4
@angular-devkit/build-angular   0.1101.4
@angular-devkit/core            11.1.4
@angular-devkit/schematics      11.1.4
@angular/cli                    11.1.4
@schematics/angular             11.1.4
@schematics/update              0.1101.4
ng-packagr                      11.2.4
rxjs                            6.6.3
typescript                      4.1.5
</code></pre>

**Comment by JoostK** [comment]
This is a known issue of the VE compiler as reported in #20351 and #23395. There are a few workarounds mentioned in those issues, the easiest would probably be to declare a local, exported, type alias for the ambient `Document` type and use that instead.

**Comment by JoostK** [comment]
Alternatively, you may want to consider disabling `strictMetadataEmit` if you don't expect the library to be used in View Engine, but just Ivy.

**Comment by alxhub** [comment]
Closing as this is not an actionable issue for us:

1. This is not an issue with Ivy.
2. There exist workarounds in View Engine builds (such as libraries) that allow the problem to be bypassed until Ivy library builds become the norm.

Given that the workarounds are effective, that it would be a considerable change to VE and its metadata to support this case correctly, and that VE is slated for removal, it doesn't make sense to invest in a full fix at this moment.
