### ISSUE TITLE
bug(MatSlideToggleModule): Identifier engcc0 has already been declared when importing MatSlideToggleModule

### ISSUE THREAD

**Issue by Juarrow** [angular/angular#41221]
#### Reproduction

Steps to reproduce:
1. create new angular project
2. ng add @angular/material
3. import MatSlideToggleModule into AppModule
 
 
#### Expected Behavior

No errors and being able to use mat-slide-toggle.

#### Actual Behavior

````
Error: ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/slide-toggle.js 22:12
Module parse failed: Identifier 'ɵngcc0' has already been declared (22:12)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders.
| import * as ɵngcc3 from '@angular/cdk/observers';
|
> import * as ɵngcc0 from '@angular/core';
| import * as ɵngcc1 from '@angular/cdk/a11y';
|
````

#### Environment

- Angular: 11.2.5
- CDK/Material: 11.2.4
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by JoostK** [comment]
This is a known issue when used together with the language service; it was reported in #41198 and a fix is pending in #41209.

**Comment by JoostK** [comment]
Btw, Angular 11.2.4 introduced this bug; the CDK/Material version shouldn't be relevant.

**Comment by buhosiliscodirococo** [comment]
I have tried all the recommendations mentioned here about the versions and the problem is still in my case.

I uninstalled everything, installed everything again, errors were displayed and when installing 'ng bootstrap' I get the same error again.

#41206

**Comment by Juarrow** [comment]
@JoostK that's weird, because - as i wrote in my first comment to my post - it works after downgrading angular to 11.2.4.

**Comment by JoostK** [comment]
@Juarrow that could indeed be the case. The issue is that ngcc can accidentally run twice (or multiple times even) for a given package if the language service is running and invoking `ngcc` before `ng build`/`ng serve`. So the bug may appear to occur randomly depending on the ordering.
