### ISSUE TITLE
Support dollar sign character in output names

### ISSUE THREAD

**Issue by DzmVasileusky** [angular/angular#41244]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?

Yes, but not sure from what version it was broken. The feature was added on 10 Feb 2016

### Description
There was a request to make a directive to be selectable by an output attribute only
https://github.com/angular/angular/issues/6394

It was fixed in this PR
https://github.com/angular/angular/commit/231773ea762ad45df1612efaeeec29d9b4ebca68

According to the test from the PR it should work like
```
@Directive({
    selector: '[myAction]'
})
...

<p (myAction)="doNothing()"></p>
```

But it's not working currently if output name is "myAction$"

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-f14xma?file=src/app/directive/directive.ts

## 🌍  Your Environment

**Angular Version:**
<pre>11<code>

**Comment by gkalpak** [comment]
The StackBlitz you provided works fine as long as you use `(myAction)` (and not `(myDirective)`) on the element, since that is the selector you have specified.

Closing as everything seems to work as expected, but feel free to continue the discussion below in case I've missed something.

**Comment by DzmVasileusky** [comment]
@gkalpak Sorry edited the planker. Actually issue is more specific. It isn't working if there is a dollar sign in the output name

**Comment by JoostK** [comment]
This regex doesn't accept the dollar sign:

https://github.com/angular/angular/blob/d1ea1f4c7f3358b730b0d94e65b00bc28cae279c/packages/compiler/src/selector.ts#L11-L21

I'm not sure that this should be supported in selectors, but if the selector fails to parse then it should arguably report an error.

**Comment by gkalpak** [comment]
FWIW, I don't see why not support `$`. (Other characters would probably be valid too, but using `$` in observables (and thus `@Output` names) is fairly common.)

**Comment by DzmVasileusky** [comment]
@gkalpak Exactly, dollar sign suffix was in our project styleguide for using for Output names.
Now I had to skip that rule for the case above.
If output name with $ sign is supported then selector should as well. Just a logical conclusion.

**Comment by iRealNirmal** [comment]
I have created Pull Request to support this feature.

[https://github.com/angular/angular/pull/41560](https://github.com/angular/angular/pull/41560)
