### ISSUE TITLE
Support i18n in string literals in templates

### ISSUE THREAD

**Issue by UrKr** [angular/angular#41264]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/localize

### Description
String literals in templates can't, as far as I can tell, be extracted for internationalisation.

There is a solution for plain attributes.
`<img [src]="logo" i18n-title title="Angular logo" />`

But the issues comes when you have something like this
`<component [input]="'some string literal'"></component>`

### Describe the solution you'd like
There's an `$any` marker which can be used in templates. I would think adding `$localize` would do the trick.
`<component [input]="$localize('some string literal')"></component>`

### Describe alternatives you've considered
Declare all string literals on the component's class instance and reference them in the template. That seems cumbersome.

**Comment by UrKr** [comment]
Right after posting this I realised that I can do this for cases where the input is a string literal.
`<component i18n-input input="some string literal"></component>`

So I suppose the only case where this is an issue is for this:
`{{ 'string literal' }}`
Which I guess makes even less sense than what I was doing.

**Comment by petebacondarwin** [comment]
Yeah, given that if you are just passing a string literal to an input you can indeed use `i18n-input` then I don't think there is a strong enough case for adding this to the template syntax.
