### ISSUE TITLE
Include special elements such as ng-content, ng-template, and ng-container in API reference

### ISSUE THREAD

**Issue by aikidave** [angular/angular#41273]
# 📚 Docs or angular.io bug report

### Description

At present, we do not have a location in our documentation to provide reference content for special elements, such as ng-content, ng-template, and ng-container. As a result, it's difficult for users to understand what these elements are and how to use them.

We should update our API documentation to include content for these elements. Although they don't exactly match content for directives, they are similar enough that we could probably treat them as such in the API reference.

### What's the affected URL?**
None, as this request is for new content.

### Reproduction Steps**
Search for an element like ng-content. No reference content exists.

### Expected vs Actual Behavior**
Users should find an API-like reference topic for ng-content (and others), that explains what they are, how they should be used, and what attributes and other aspects they include.

**Comment by IgorMinar** [comment]
@petebacondarwin could we somehow convince dgeni to treat these as if they were directives and then reuse the rest of the docs pipeline to document them as such? We are talking just about 3 or 4 symbols that would need to be documented in this way, so it would be great to have a solution that makes this possible without adding too much complexity to the system.

**Comment by petebacondarwin** [comment]
I'll have a think about how this might be achieved...
