### ISSUE TITLE
Console log problem with pointers

### ISSUE THREAD

**Issue by brandonfl** [angular/angular#41281]
# 🐞 bug report

### Affected Package

I am currently not sure where the bug is coming from. I did the test with Javascript as well as typescript and the problem is not present. So I think the problem comes from Angular

### Is this a regression?

I do not think

### Description

When we make a console log of an object and the object is modified afterwards, the previous console logs that have already been sent are modified with the new value. However, only the complex objects are modified and not the primitive objects like  `number` or `string`.

(Personally, I do a lot of debugging with the console and this side effect made me lose a lot of time)

## 🔬 Minimal Reproduction

Stackblitz with Angular : https://stackblitz.com/edit/console-log-error?file=src/app/app.component.ts

You can see that into logs there is : 

![Capture d’écran de 2021-03-19 18-22-19](https://user-images.githubusercontent.com/25805069/111818957-0ef63380-88e0-11eb-9676-5ef33432baf3.png)

The console print a array of 2 that is a array of 0 cause the array as been **modified afterwards** the console log

You can also see that with [javascript](https://jsbin.com/fikukob/edit?js,console,output) the error is not present

## 🔥 Exception or Error

![Capture d’écran de 2021-03-19 18-22-19](https://user-images.githubusercontent.com/25805069/111818957-0ef63380-88e0-11eb-9676-5ef33432baf3.png)

## 🌍  Your Environment

**Angular Version:**
```
"rxjs": "6.1.0",
"core-js": "2.5.5",
"zone.js": "0.8.26",
"@angular/core": "6.0.0",
"@angular/forms": "6.0.0",
"@angular/common": "6.0.0",
"@angular/router": "6.0.0",
"@angular/compiler": "6.0.0",
"@angular/platform-browser": "6.0.0",
"@angular/platform-browser-dynamic": "6.0.0"
```

**Anything else relevant?**

I tested on **chrome** but it seems to be also present into **Firefox** 

![Capture d’écran de 2021-03-19 18-29-16](https://user-images.githubusercontent.com/25805069/111819837-19fd9380-88e1-11eb-8914-ca3e77973644.png)

**Comment by petebacondarwin** [comment]
This is not related to Angular. It is how browser consoles work. See https://stackoverflow.com/a/7389177
