### ISSUE TITLE
@angular/animations transition function doesn't work

### ISSUE THREAD

**Issue by RazvanStoica0806** [angular/angular#41297]
Hello everyone !

I have a problem with the implementation of animations in one of my project. 
So here I have 2 situations: 
One project(Project A  where the animations transition prop is not working and one project(Project B) where I implement them in the same way and it is working. 
Let me show you the configuration of the project A where is not working:  

Package json:
  "dependencies": {
    "@angular/animations": "^7.2.7",
    "@angular/common": "^7.2.3",
    "@angular/compiler": "^7.2.3",
    "@angular/core": "^7.2.3",
    "@angular/forms": "^7.2.3",
    "@angular/http": "^7.2.3",
    "@angular/platform-browser": "^7.2.3",
    "@angular/platform-browser-dynamic": "^7.2.3",
    "@angular/router": "^7.2.3",
    "@angular/service-worker": "^7.2.3",
    "@fortawesome/fontawesome-free": "^5.1.0",
    "@ng-bootstrap/ng-bootstrap": "^4.2.2",
    "@ng-idle/core": "^7.0.0-beta.1",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "bootstrap": "^3.3.7",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.6.3",
    "jquery": "^3.4.1",
    "lodash": "^4.17.11",
    "ng2-cookies": "^1.0.12",
    "ng2-pdf-viewer": "^5.3.3",
    "ng5-slider": "^1.2.4",
    "ngx-bootstrap": "^5.1.1",
    "ngx-select-dropdown": "^1.4.0",
    "ngx-swiper-wrapper": "^8.0.2",
    "ngx-useful-swiper": "^8.0.1",
    "rxjs": "^6.5.2",
    "swiper": "^4.5.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.0",
    "@angular/cli": "~7.3.0",
    "@angular/compiler-cli": "^7.2.3",
    "@angular/language-service": "^7.2.3",
    "@biesbjerg/ngx-translate-extract": "^2.3.4",
    "@ngx-rocket/scripts": "^3.0.0",
    "@types/jasmine": "^3.3.8",
    "@types/jasminewd2": "^2.0.3",
    "@types/lodash": "^4.14.112",
    "@types/node": "^8.10.51",
    "@types/swiper": "^4.4.4",
    "codelyzer": "^5.0.0",
    "hads": "^1.7.3",
    "htmlhint": "^0.11.0",
    "https-proxy-agent": "^2.0.0",
    "husky": "^1.3.1",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "jsencrypt": "3.0.0-rc.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "~2.0.0",
    "karma-coverage-istanbul-reporter": "^2.0.2",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "karma-junit-reporter": "^1.2.0",
    "prettier": "^1.16.3",
    "pretty-quick": "^1.10.0",
    "protractor": "~5.4.0",
    "stylelint": "~10.0.1",
    "stylelint-config-prettier": "^5.1.0",
    "stylelint-config-recommended-scss": "~3.3.0",
    "stylelint-config-standard": "~18.3.0",
    "stylelint-scss": "~3.6.0",
    "ts-node": "~8.1.0",
    "tslint": "~5.16.0",
    "tslint-config-prettier": "^1.14.0",
    "typescript": "~3.2.0"
  }

Animations Component:

import {Component, Input, OnInit} from '@angular/core';
import {animate, state, style, transition, trigger} from '@angular/animations';

@Component({
  selector: 'app-animate',
  templateUrl: './animations.component.html',
  styleUrls: ['./animations.component.scss'],
  animations: [
    trigger('changeState', [
      state('state1', style({
        backgroundColor: 'green',
        transform: 'scale(1)'
      })),
      state('state2', style({
        backgroundColor: 'red',
        transform: 'scale(1.5)'
      })),
      transition('*=>state1', animate('300ms')),
      transition('*=>state2', animate('2000ms'))
    ])
  ]
})
export class AnimationsComponent implements OnInit {

  @Input() currentState: any;

  constructor() { }

  ngOnInit(): void {
  }

}

Animations comp HTML:
<div [@changeState]="currentState" class="myblock mx-auto"></div>

Template component where I implement animations: 
<div class="container p-4">
  <div class="row">
    <div class="col text-center">
      <a (click)="changeState('state2')" class="btn btn-danger">Change To State 2</a>
    </div>
    <div class="col text-center">
      <a (click)="changeState('state1')" class="btn btn-info">Change To State 1</a>
    </div>
  </div>
  <div class="row justify-content-center align-items-center">
    <app-animate [currentState]="toState"></app-animate>
  </div>
</div>

TS Component
  toState = 'state1';

  changeState(state: any) {
    this.toState = state;
  }

Same implementation on the other project where the animations work and the difference is the version of angular : 10 . 
Let me show you the package json of the project B where the transition is working: 
  "dependencies": {
    "@angular/animations": "^10.2.4",
    "@angular/common": "^10.2.4",
    "@angular/compiler": "^10.2.4",
    "@angular/core": "^10.2.4",
    "@angular/forms": "^10.2.4",
    "@angular/localize": "^10.0.0",
    "@angular/platform-browser": "^10.2.4",
    "@angular/platform-browser-dynamic": "^10.2.4",
    "@angular/router": "^10.2.4",
    "@angular/service-worker": "^10.2.4",
    "@fortawesome/fontawesome-free": "^5.13.1",
    "@ng-bootstrap/ng-bootstrap": "8.0.0",
    "@ng-idle/core": "^10.0.0-beta.1",
    "@ngx-translate/core": "^13.0.0",
    "@types/jest": "^26.0.20",
    "@types/lodash": "^4.14.157",
    "@types/pdfjs-dist": "2.1.3",
    "@types/uuid": "8.3.0",
    "bootstrap": "^3.3.7",
    "cap-integration": "3.0.1",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "george-library": "^1.0.5-dcl-138",
    "jquery": "^3.5.1",
    "lodash": "^4.17.11",
    "ng2-cookies": "^1.0.12",
    "ng2-pdf-viewer": "6.1.3",
    "ng5-slider": "^1.2.6",
    "ngx-bootstrap": "^5.1.1",
    "ngx-swiper-wrapper": "^8.0.2",
    "ngx-useful-swiper": "^8.0.1",
    "path": "^0.12.7",
    "pdfjs-dist": "^2.6.347",
    "rxjs": "^6.6.0",
    "swiper": "^4.5.1",
    "tslib": "^1.10.0",
    "zone.js": "^0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1002.2",
    "@angular-eslint/builder": "1.2.0",
    "@angular-eslint/eslint-plugin": "1.2.0",
    "@angular-eslint/eslint-plugin-template": "1.2.0",
    "@angular-eslint/schematics": "1.2.0",
    "@angular-eslint/template-parser": "1.2.0",
    "@angular/cli": "~10.2.2",
    "@angular/compiler-cli": "^10.2.4",
    "@angular/language-service": "^10.2.4",
    "@angularclass/hmr": "^2.1.3",
    "@biesbjerg/ngx-translate-extract": "^7.0.2",
    "@ngx-rocket/scripts": "^4.0.0",
    "@types/jasmine": "^3.3.13",
    "@types/jasminewd2": "^2.0.3",
    "@types/node": "12.11.1",
    "@types/swiper": "^4.4.10",
    "@typescript-eslint/eslint-plugin": "4.3.0",
    "@typescript-eslint/parser": "4.3.0",
    "codelyzer": "^6.0.0",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "eslint-plugin-react": "latest",
    "htmlhint": "^0.11.0",
    "https-proxy-agent": "^2.0.0",
    "husky": "^3.0.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "jsencrypt": "^3.0.0-rc.1",
    "karma": "^4.2.0",
    "karma-chrome-launcher": "^3.0.0",
    "karma-cli": "~2.0.0",
    "karma-coverage-istanbul-reporter": "^2.0.2",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "karma-junit-reporter": "^1.2.0",
    "prettier": "^1.16.3",
    "pretty-quick": "^1.11.1",
    "protractor": "^7.0.0",
    "stylelint": "~10.1.0",
    "stylelint-config-prettier": "^5.1.0",
    "stylelint-config-recommended-scss": "~3.3.0",
    "stylelint-config-standard": "~18.3.0",
    "stylelint-scss": "~3.9.0",
    "ts-node": "^8.10.2",
    "typescript": "~4.0.5",
    "uuid": "8.3.2",
    "webpack-bundle-analyzer": "^4.4.0"
  }

Could it be there is some module misconfiguration or some dependencies that transition property of @angular/animations needs to be in synchronization ?

**Comment by RazvanStoica0806** [comment]
> Hello everyone !
> 
> I have a problem with the implementation of animations in one of my project.
> So here I have 2 situations:
> One project(Project A where the animations transition prop is not working and one project(Project B) where I implement them in the same way and it is working.
> Let me show you the configuration of the project A where is not working:
> 
> Package json:
> "dependencies": {
> "@angular/animations": "^7.2.7",
> "@angular/common": "^7.2.3",
> "@angular/compiler": "^7.2.3",
> "@angular/core": "^7.2.3",
> "@angular/forms": "^7.2.3",
> "@angular/http": "^7.2.3",
> "@angular/platform-browser": "^7.2.3",
> "@angular/platform-browser-dynamic": "^7.2.3",
> "@angular/router": "^7.2.3",
> "@angular/service-worker": "^7.2.3",
> "@fortawesome/fontawesome-free": "^5.1.0",
> "@ng-bootstrap/ng-bootstrap": "^4.2.2",
> "@ng-idle/core": "^7.0.0-beta.1",
> "@ngx-translate/core": "^11.0.1",
> "@ngx-translate/http-loader": "^4.0.0",
> "bootstrap": "^3.3.7",
> "classlist.js": "^1.1.20150312",
> "core-js": "^2.6.3",
> "jquery": "^3.4.1",
> "lodash": "^4.17.11",
> "ng2-cookies": "^1.0.12",
> "ng2-pdf-viewer": "^5.3.3",
> "ng5-slider": "^1.2.4",
> "ngx-bootstrap": "^5.1.1",
> "ngx-select-dropdown": "^1.4.0",
> "ngx-swiper-wrapper": "^8.0.2",
> "ngx-useful-swiper": "^8.0.1",
> "rxjs": "^6.5.2",
> "swiper": "^4.5.0",
> "web-animations-js": "^2.3.2",
> "zone.js": "~0.8.26"
> },
> "devDependencies": {
> "@angular-devkit/build-angular": "^0.13.0",
> "@angular/cli": "~7.3.0",
> "@angular/compiler-cli": "^7.2.3",
> "@angular/language-service": "^7.2.3",
> "@biesbjerg/ngx-translate-extract": "^2.3.4",
> "@ngx-rocket/scripts": "^3.0.0",
> "@types/jasmine": "^3.3.8",
> "@types/jasminewd2": "^2.0.3",
> "@types/lodash": "^4.14.112",
> "@types/node": "^8.10.51",
> "@types/swiper": "^4.4.4",
> "codelyzer": "^5.0.0",
> "hads": "^1.7.3",
> "htmlhint": "^0.11.0",
> "https-proxy-agent": "^2.0.0",
> "husky": "^1.3.1",
> "jasmine-core": "~3.4.0",
> "jasmine-spec-reporter": "~4.2.1",
> "jsencrypt": "3.0.0-rc.1",
> "karma": "~4.1.0",
> "karma-chrome-launcher": "^2.2.0",
> "karma-cli": "~2.0.0",
> "karma-coverage-istanbul-reporter": "^2.0.2",
> "karma-jasmine": "^2.0.1",
> "karma-jasmine-html-reporter": "^1.4.0",
> "karma-junit-reporter": "^1.2.0",
> "prettier": "^1.16.3",
> "pretty-quick": "^1.10.0",
> "protractor": "~5.4.0",
> "stylelint": "~10.0.1",
> "stylelint-config-prettier": "^5.1.0",
> "stylelint-config-recommended-scss": "~3.3.0",
> "stylelint-config-standard": "~18.3.0",
> "stylelint-scss": "~3.6.0",
> "ts-node": "~8.1.0",
> "tslint": "~5.16.0",
> "tslint-config-prettier": "^1.14.0",
> "typescript": "~3.2.0"
> }
> 
> Animations Component:
> 
> import {Component, Input, OnInit} from '@angular/core';
> import {animate, state, style, transition, trigger} from '@angular/animations';
> 
> @component({
> selector: 'app-animate',
> templateUrl: './animations.component.html',
> styleUrls: ['./animations.component.scss'],
> animations: [
> trigger('changeState', [
> state('state1', style({
> backgroundColor: 'green',
> transform: 'scale(1)'
> })),
> state('state2', style({
> backgroundColor: 'red',
> transform: 'scale(1.5)'
> })),
> transition('_=>state1', animate('300ms')), transition('_=>state2', animate('2000ms'))
> ])
> ]
> })
> export class AnimationsComponent implements OnInit {
> 
> @input() currentState: any;
> 
> constructor() { }
> 
> ngOnInit(): void {
> }
> 
> }
> 
> Animations comp HTML:
> <div [@changeState]="currentState" class="myblock mx-auto"></div>

> Template component where I implement animations:
> 
> Change To State 2
> Change To State 1
> TS Component
> toState = 'state1';
> 
> changeState(state: any) {
> this.toState = state;
> }
> 
> Same implementation on the other project where the animations work and the difference is the version of angular : 10 .
> Let me show you the package json of the project B where the transition is working:
> "dependencies": {
> "@angular/animations": "^10.2.4",
> "@angular/common": "^10.2.4",
> "@angular/compiler": "^10.2.4",
> "@angular/core": "^10.2.4",
> "@angular/forms": "^10.2.4",
> "@angular/localize": "^10.0.0",
> "@angular/platform-browser": "^10.2.4",
> "@angular/platform-browser-dynamic": "^10.2.4",
> "@angular/router": "^10.2.4",
> "@angular/service-worker": "^10.2.4",
> "@fortawesome/fontawesome-free": "^5.13.1",
> "@ng-bootstrap/ng-bootstrap": "8.0.0",
> "@ng-idle/core": "^10.0.0-beta.1",
> "@ngx-translate/core": "^13.0.0",
> "@types/jest": "^26.0.20",
> "@types/lodash": "^4.14.157",
> "@types/pdfjs-dist": "2.1.3",
> "@types/uuid": "8.3.0",
> "bootstrap": "^3.3.7",
> "cap-integration": "3.0.1",
> "cors": "^2.8.5",
> "express": "^4.17.1",
> "george-library": "^1.0.5-dcl-138",
> "jquery": "^3.5.1",
> "lodash": "^4.17.11",
> "ng2-cookies": "^1.0.12",
> "ng2-pdf-viewer": "6.1.3",
> "ng5-slider": "^1.2.6",
> "ngx-bootstrap": "^5.1.1",
> "ngx-swiper-wrapper": "^8.0.2",
> "ngx-useful-swiper": "^8.0.1",
> "path": "^0.12.7",
> "pdfjs-dist": "^2.6.347",
> "rxjs": "^6.6.0",
> "swiper": "^4.5.1",
> "tslib": "^1.10.0",
> "zone.js": "^0.10.3"
> },
> "devDependencies": {
> "@angular-devkit/build-angular": "^0.1002.2",
> "@angular-eslint/builder": "1.2.0",
> "@angular-eslint/eslint-plugin": "1.2.0",
> "@angular-eslint/eslint-plugin-template": "1.2.0",
> "@angular-eslint/schematics": "1.2.0",
> "@angular-eslint/template-parser": "1.2.0",
> "@angular/cli": "~10.2.2",
> "@angular/compiler-cli": "^10.2.4",
> "@angular/language-service": "^10.2.4",
> "@angularclass/hmr": "^2.1.3",
> "@biesbjerg/ngx-translate-extract": "^7.0.2",
> "@ngx-rocket/scripts": "^4.0.0",
> "@types/jasmine": "^3.3.13",
> "@types/jasminewd2": "^2.0.3",
> "@types/node": "12.11.1",
> "@types/swiper": "^4.4.10",
> "@typescript-eslint/eslint-plugin": "4.3.0",
> "@typescript-eslint/parser": "4.3.0",
> "codelyzer": "^6.0.0",
> "eslint": "^7.6.0",
> "eslint-plugin-import": "2.22.1",
> "eslint-plugin-jsdoc": "30.7.6",
> "eslint-plugin-prefer-arrow": "1.2.2",
> "eslint-plugin-react": "latest",
> "htmlhint": "^0.11.0",
> "https-proxy-agent": "^2.0.0",
> "husky": "^3.0.0",
> "jasmine-core": "~3.5.0",
> "jasmine-spec-reporter": "~4.2.1",
> "jsencrypt": "^3.0.0-rc.1",
> "karma": "^4.2.0",
> "karma-chrome-launcher": "^3.0.0",
> "karma-cli": "~2.0.0",
> "karma-coverage-istanbul-reporter": "^2.0.2",
> "karma-jasmine": "^2.0.1",
> "karma-jasmine-html-reporter": "^1.4.0",
> "karma-junit-reporter": "^1.2.0",
> "prettier": "^1.16.3",
> "pretty-quick": "^1.11.1",
> "protractor": "^7.0.0",
> "stylelint": "~10.1.0",
> "stylelint-config-prettier": "^5.1.0",
> "stylelint-config-recommended-scss": "~3.3.0",
> "stylelint-config-standard": "~18.3.0",
> "stylelint-scss": "~3.9.0",
> "ts-node": "^8.10.2",
> "typescript": "~4.0.5",
> "uuid": "8.3.2",
> "webpack-bundle-analyzer": "^4.4.0"
> }
> 
> Could it be there is some module misconfiguration or some dependencies that transition property of @angular/animations needs to be in synchronization ?

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
