### ISSUE TITLE
Not able to access documentation

### ISSUE THREAD

**Issue by priyanshichauhan903** [angular/angular#41301]
Site is not responding ,I am not able to click and reach to any doc page ,please resolve issue as soon as possible.

**Comment by petebacondarwin** [comment]
I assume you mean this page? https://angular.io/
It is responding fine for me. Can you give some more details of the problem?

**Comment by vugar005** [comment]
@priyanshichauhan903  @petebacondarwin  I had this issue also often. It is resolved when you hard reload the page. I assume it is because after new deployment, it tried to find old cache like main32324.js but it cannot find. So I force to empty and hard reload the page.

**Comment by geromegrignon** [comment]
I second that : if i can't provide a way to reproduce it, i often experiment this issue too.

**Comment by gkalpak** [comment]
Unfortunately, there is not much we can do without more concrete info (or a repro).

Howevr, I would very much like to get to the bottom of such issues (which are potentially related to #28114). In fact, we just recently put [code in place][1] to print more debug info to help diagnose similar problems.

So, if you run into this again, please open a new issue and provide as much info as possible, such as:
- any console logs
- any error stack traces
- what actions led to the problem:
    - Did you have other tabs open on angular.io?
    - If not, how long ago had you visited angular.io?
    - How did you try to navigate to the failing page (google search, link from a different page, link in angular.io, navigation on the same tab or opening a new tab, etc.)?

:pray:

[1]: https://github.com/angular/angular/blob/5eb7f3491f37a8f71717525b0d0e901c00a8c4e8/aio/src/app/layout/doc-viewer/doc-viewer.component.ts#L257-L314
