### ISSUE TITLE
Execute code in component after the style has been applied to the template (new lifecycle hook ?)

### ISSUE THREAD

**Issue by Seiifer** [angular/angular#41309]
Is  there any way to do something in a component after all the style has been applied ?

For instance, I have a basic use case with an horizontal scrollbar with something like this :
```
  ngAfterViewInit(): void {
    const element = document.getElementById('someList');
    this.isScrollable = element.scrollWidth > element.clientWidth;
  }
```

However, it seems the styles from my css have not been applied yet, therefore `scrollWidth` and `clientWidth` have the same value.

I also tried with `ngAfterViewChecked()` but the result is the same. Maybe a new lifecycle hook could be added ?

How can I execute my code after the style has been applied ?

Also, here is the relevant CSS (I'm using scss if that matters) :
```
#someList {
    position: relative;
    top: 220px;
    display: flex;
    flex-direction: row;
    overflow-x: auto;
}
```

Currently, I have to use a timeout to make it work but obviously I'm not fond of this solution.

**Comment by geromegrignon** [comment]
Hey, could you provide a stackblitz sample?
I can't reproduce your issue (working fine with AfterViewInit).

**Comment by Seiifer** [comment]
@geromegrignon 
Here is a stackblitz illustrating my issue :
https://stackblitz.com/edit/angular-ivy-dvjwty?file=src%2Fapp%2Fapp.component.ts

Basically, the scrolling buttons (left and right svg arrows) are not being displayed because the `clientWidth` and `scrollWidth` have the same value. This is due to the style of the element not being applied yet.
Uncommenting the timeout will fix it but this is not ideal.

Note: The issue occurs on the first page load, after that, it seems to work fine with some random failure, this is probably due to some caching made by Stackblitz.
It might be easier to see the issue directly here : https://angular-ivy-dvjwty.stackblitz.io/

**Comment by geromegrignon** [comment]
It happens only once with Stackblitz because it caches the images.
Your issue isn't about css but the loading of the assets (here the images).

When `AfterViewInit` is triggered, the images aren't loaded yet into the browser.
So not only the scrollWidth equals the clientWidth but both values equals the actual width of the browser (not the width required to display the images).

Angular can't catch the loading of the images on its own, you need to 

You can listen to the `load` event on images to do so : 

```html
<!-- add a template reference to retrieve them -->
<img #img src="{{element.img}}">
```

```ts
@ViewChildren("img", { read: ElementRef }) imgs: QueryList<ElementRef>;

  elements = elements;

  ngAfterViewInit(): void {
    combineLatest([...this.imgs.map(img => fromEvent(img.nativeElement, 'load'))]).subscribe(() => {
       // once all images are loaded
      const element = document.getElementById("someList");
      console.log(element.scrollWidth);
      console.log(element.clientWidth);
      this.isScrollable = element.scrollWidth > element.clientWidth;

    if (this.isScrollable) {
      this.canScrollLeft = element.scrollLeft > 0;
      this.canScrollRight =
        element.scrollLeft < element.scrollWidth - element.clientWidth;
    }
    });
  }
```

**Comment by Seiifer** [comment]
Working like a charm.
I am not very familiar with the rxjs methods and the `nativeElement`  you used but it solved it.
I'm gonna try to look into it.

Thanks.
