### ISSUE TITLE
DEFAULT_CURRENCY_CODE is not the right way for default currency code

### ISSUE THREAD

**Issue by e-cloud** [angular/angular#41323]
# 🚀 feature request

### Relevant Package
 @angular/common

### Description
With current implementation, developers have to mannually specify the `DEFAULT_CURRENCY_CODE`, if they use a different locale rather than `en-us` and want to use the currency meta along with that locale.

here is how currency pipe implements:
https://github.com/angular/angular/blob/c49b28013a6c017c9afc73bbc00bb4fdcf15c70e/packages/common/src/pipes/number_pipe.ts#L205-L208

In fact, there is a function to get currency code from a target locale
https://github.com/angular/angular/blob/c49b28013a6c017c9afc73bbc00bb4fdcf15c70e/packages/common/src/i18n/locale_data_api.ts#L488

I believe using the currency code from specified locale is the right way to go, rather than specifying it mannually.

### Describe the solution you'd like
deprecate the use of `DEFAULT_CURRENCY_CODE`, in favor of `getLocaleCurrencyCode` in currency pipe.

### Describe alternatives you've considered
There are always the alternatives, but not the elegant way.

**Comment by JoostK** [comment]
This has been proposed before, but deemed an inappropriate change to make. See https://github.com/angular/angular/pull/34724#issuecomment-614496201 for the rationale.
