### ISSUE TITLE
After upgrade to Angular 10 getting error in polyfills.ts Can't resolve 'core-js/es7/reflect' 

### ISSUE THREAD

**Issue by kiransuri88** [angular/angular#41320]
Hi,

I have upgraded my project to angular 10 and getting this error.

ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es2018/reflect' in 'C:\Kiran\Dev\EnelX\fdr-mom-ui\src'

Can you please help me with this.

Thanks,

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: 
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by aburkowsky9** [comment]
Hey you checked the `node_modules` to see if your `core-js` package is still structured as you are importing it? In mine, the `es2018` directory is no longer available. Latest `core-js` has just an `es` directory now. So the import in your `polyfills.ts` might have to change to:

```ts
import `core-js/es/reflect`
```

**Comment by kiransuri88** [comment]
Thanks heaps. resolved now.
