### ISSUE TITLE
ngTable Coloumn Customization

### ISSUE THREAD

**Issue by hazdik** [angular/angular#4132]
Dear Team,

As i have an One table it was some customized Filters and Sorting, but i want to make some column wise customization like

    In top of the table i have an One Button, if i click the Button it will shows some one Multi Select Box with Drag Drop option.
    In Side of Lpanel I have an options are table header title
    Cpanel is select a coloumn title selective options like Lpanel to rpanel, Rpanel to Lpanel, All to Rpanel, All to lapnel insid ehave Drag Drop.
    In table header name(data) are loaded into the Select Box. whatever i action will perform like L to R R to L, Drag and Drop
    I want to hide the columns and i want make the column positions too

Kindly Help me for an custom Directive / Controller,

Hazdik DA, India

**Comment by vicb** [comment]
Closing as this repo is for Angular2. Angular.js repo is at https://github.com/angular/angular.js. However this seems related to https://github.com/esvit/ng-table
