### ISSUE TITLE
issue while referencing external image in receding in same server (NFS shared drive mounted location) in angular 11

### ISSUE THREAD

**Issue by kartiki-sahu** [angular/angular#41322]
I have an issue while referencing image in NFS drive in angular 11. Please can someone guide me with it

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests. Please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular` (or if you would like to chat about the question in real-time, you can reach out via [our Discord server](https://discord.gg/angular)).

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
