### ISSUE TITLE
When launching an app to / a Router redirectTo is not kicking in

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#4133]
I just tried this where 

When I have a redirectTo for the `/` path it does not redirect to the heroes route on load.

```
@RouteConfig([
  { path: '/', redirectTo: '/heroes' },  // TODO: Prefer an otherwise when its ready. Is Redirect working?
  { path: '/heroes', as: 'heroes', component: HeroesComponent },
  { path: 'detail/:id', as: 'detail', component: HeroDetailComponent }
])
```

I also tried the `redirectTo: 'heroes'` with no luck. No error, it just loads the app with nothing int he `router-outlet`

To get around this for now I launch an additional route that goes to a dashboard component which is mapped to a `/` route

**Comment by johnpapa** [comment]
CC / @wardbell

**Comment by naomiblack** [comment]
this will be fixed by #4170 getting resolved. There's a slight chance of this landing in 41, but it is not critical.

**Comment by mhevery** [comment]
closing as dup of #4170

**Comment by petebacondarwin** [comment]
#4170 was closed by cf7292f but the relevant test in the code at https://github.com/angular/angular/blob/6ddfff5cd59aac9099aa6da5118c5598eea7ea11/modules/angular1_router/test/integration/shim_spec.js#L160 still fails.

**Comment by aburakab** [comment]
For the time being i did this hack :)
```
import { RouteMetadata } from '@angular/router/src/metadata/metadata';

export var AppRoutes: RouteMetadata[] = [
        { path: '/inboxes', component: InboxesCmp },
        { path: '/deliveryReports', component: DeliveryReportCmp },
        { path: '/reports', component: DeliveryReportCmp },
        { path: '/search', component: SearchCmp },
];
-------------------------------------------------------------------------
import { AppRoutes } from "./_Models/ModuleRoutes";

    @Routes(AppRoutes)
    export class EvAppComponent implements OnInit {
        constructor(private _router: Router) { }
        ngOnInit() {
            var validRoute = false;
            for (let i = 0, len = AppRoutes.length; i < len; i++) {
                let route = AppRoutes[i];
                let urlTree = this._router.createUrlTree([route]);
                validRoute = this._router.urlTree.contains(urlTree);
                if (validRoute)
                    continue;
             }
             if (!validRoute) {
                this._router.navigateByUrl('/inboxes');
            }
        }
    }
```

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

by the latest router

**Comment by acostaf** [comment]
Please Reopen, broken on 3.0.0-beta.2 doesn't mattter if I use it  { path: '', redirectTo: '/Settings', terminal: true } or  { path: '', redirectTo: 'Settings', terminal: true }, pathMatch : 'full' or prefix

**Comment by zoechi** [comment]
@acostaf I guess it's better to create a new issue with a Plunker to reproduce.
