### ISSUE TITLE
Angular 10.2.4 xi18n with --ivy: equiv-text contains wrong value when using CRLF line endings

### ISSUE THREAD

**Issue by stefan-schweiger** [angular/angular#41346]
# 🐞 bug report

### Affected Package
Probably
@angular/cli
@angular/compiler
@angular/localize

### Is this a regression?

Similar bugs were already fixed multiple times #38694 #38711 #39654

### Description

From what I've gathered from the other bugs when you have Windows line endings CRLF the source maps only generate one character for it, which causes the source maps to become misaligned. This causes the `equiv-text` to contain the wrong value:

```
<p i18n="@@test-key-asdf">
  <span>Test asdf</span>
</p>
```

Becomes **equiv-text="y-asdf"**:

```
<trans-unit id="test-key-asdf" datatype="html">
  <source><x id="START_TAG_SPAN" ctype="x-span" equiv-text="y-asdf"/>Test asdf<x id="CLOSE_TAG_SPAN" ctype="x-span" equiv-text="an&gt;Test"/></source>
  <context-group purpose="location">
    <context context-type="sourcefile">src/app/app.component.html</context>
    <context context-type="linenumber">13</context>
  </context-group>
</trans-unit>
```

In the latest Angular 11 version this is fixed, but since Angular 10 is LTS I really hope you will fix this for the older version as well.

## 🔬 Minimal Reproduction

https://github.com/stefan-schweiger/angular-10-xi18n-crlf-bug 

You need to make sure to check out the project with CRLF line endings (or format the files yourself).

Then just run `ng xi18n --output-path src/locale --ivy`

## 🌍  Your Environment

**Angular Version:**
10.2.4 (10.2.3 for cli)

**Comment by petebacondarwin** [comment]
Sorry not to reply to this sooner. In LTS we only release [critical fixes and security patches](https://angular.io/guide/releases#lts-fixes). As such I'm afraid that this fix does not come in that category.

Please update your application to a more recent version of Angular.
