### ISSUE TITLE
`extends` in `tsconfig` logic is different with TypeScript's

### ISSUE THREAD

**Issue by JounQin** [angular/angular#41343]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler-cli

### Is this a regression?

 No

### Description

 A clear and concise description of the problem...

```jsonc
{
  "extends": "@1stg/tsconfig/angular" // should resolve `@1stg/tsconfig/angular.json`

  "extends": "./tsconfig.app" // should resolve `./tsconfig.app.json` if there is no `./tsconfig.app` file
}
```

## 🔬 Minimal Reproduction

 Unnecessary

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 11.2.6
Node: 14.16.0
OS: darwin x64

Angular: 11.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.2
@angular-devkit/core         11.2.6
@angular-devkit/schematics   11.2.6
@angular/cdk                 11.2.6
@angular/cli                 11.2.6
@angular/flex-layout         11.0.0-beta.33
@schematics/angular          11.2.6
@schematics/update           0.1102.6
rxjs                         6.6.6
</code></pre>

**Anything else relevant?**

cc @alan-agius4

**Comment by alan-agius4** [comment]
As a temporary workaround you can try to add an extension to the extends `@1stg/tsconfig/angular.json`

**Comment by JounQin** [comment]
Yes, I'm using this workaround
