### ISSUE TITLE
<app-root>loading</app-root>,"loading" can not see

### ISSUE THREAD

**Issue by huangfeihong1860** [angular/angular#41355]
int the index.html  ,<app-root>loading</app-root>   ,"loading" can not see  in firefox ,ie,chrome

version
angular 11
ionic 6

**Comment by rahiyansafz** [comment]
do you have any idea how and why and when it shows?

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
