### ISSUE TITLE
The `done` fn created by jasmine-patch.js does not support `done.fail`

### ISSUE THREAD

**Issue by wardbell** [angular/angular#4136]
The [`done.fail` option in Jasmine 2.0](http://jasmine.github.io/2.3/introduction.html#section-53) makes it easy to report the error from a failed promise but `done.fail` isn't implemented by the zone-aware version from *jasmine-patch.js*.

Therefore, the following test reports an async timeout instead of the actual error:
```
  // this test fails the wrong way
  it('async test with rejected promise reports error as expected via "done.fail"', done => {
    Promise.reject('failed on purpose')
      .then(result => {
        fail('should not get here');
      })
      .then(done,
        reason => {
          done.fail(reason); // written this way for easy breakpointing
        });
  });
```
Not a huge priority but worth fixing and easy to fix.

**Comment by juliemr** [comment]
This was fixed with the move to the new angular2/testing library - now we don't mask `done.fail`.
