### ISSUE TITLE
docs: links to non-existing CLI wiki

### ISSUE THREAD

**Issue by bartvanraaij** [angular/angular#41362]
# 📚 Docs or angular.io bug report

### Description

The docs' ["Component Styles" guide](https://angular.io/guide/component-styles) has links to the "CLI Wiki" at `https://github.com/angular/angular-cli/wiki/stories-global-styles` on several locations. 
This URL doesn't exist (302 redirects to `https://github.com/angular/angular-cli`)

### What's the affected URL?
https://angular.io/guide/component-styles and
https://github.com/angular/angular-cli/wiki/stories-global-styles

### Anything else relevant?
I'm curious as to where the info about css preprocessors (which supposedly was in the Wiki before) is available now.

**Comment by andrewasche** [comment]
I'd would like a try at this. I'm guessing that that whole line and the link ("See the CLI wiki to learn more.") should be deleted.

**Comment by alan-agius4** [comment]
The link should be updated to https://angular.io/guide/workspace-config#styles-and-scripts-configuration

**Comment by aishuo07** [comment]
I want to contribute Too

**Comment by andrewasche** [comment]
I'm assuming this is solved.
I was doing the test and non-ivy is not completely passing yet

**Comment by arizala13** [comment]
@andreabalducci Looks like this fixes it https://github.com/angular/angular/pull/41516

**Comment by bartvanraaij** [comment]
#41516 is incomplete: there are three references/links to "CLI wiki" on this page, that PR only changes 1.
