### ISSUE TITLE
Auxilliary Routes are not properly deactivated

### ISSUE THREAD

**Issue by sueltschi-sbb** [angular/angular#41379]
# 🐞 Auxilliary Routes are not properly deactivated

### Affected Package

@angular/router

### Description
Given an auxiliary route that is activated in a `<router-outlet>`,

If we deactivate the outlet and then remove `<router-outlet>` and add it back to the DOM, the `<router-outlet>` will be activated with the last active route and is now out of sync with the router.

## 🔬 Minimal Reproduction

Starting [here](https://stackblitz.com/edit/angular-aux-route-issue)

1. Click on "Aux 1234" => the `<router-outlet>` is activated
2. Click on "Deactivate Aux" => the `<router-outlet>` is deactivated
3. Click twice on "Toggle Outlet" => the `<router-outlet>` is falsely activated again with the last active route `(aux:1234)` and out of sync with the browser URL

I expected the `<router-outlet>` to be deactivated

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.6
Node: 14.15.4
OS: win32 x64

Angular: 11.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.6
@angular-devkit/build-angular   0.1102.6
@angular-devkit/core            11.2.6
@angular-devkit/schematics      11.2.6
@angular/cli                    11.2.6
@schematics/angular             11.2.6
@schematics/update              0.1102.6
rxjs                            6.6.7
typescript                      4.1.5

</code></pre>

**Comment by joshbowdoin** [comment]
This bug fix broke our ionic app's navigation.... Is there a way to fix this issue without breaking our behavior as described here: https://github.com/ionic-team/ionic-framework/issues/23230?
