### ISSUE TITLE
ngcc throw error if I use KendoUI and pnpm

### ISSUE THREAD

**Issue by Stas-tolpekin** [angular/angular#41372]
# 🐞 bug report

### Affected Package
ngcc

### Is this a regression?
Yes, as I can see this problem is not reproducing at pre-ivy angular versions

### Description
In my project, I use the latest version of KendoUI for Angular. I try to use `pnpm` as a package manager. I can see that angular cli supports pnpm and I assume that angular supports it too. After package installation, I run `ng build`. But I get ngcc error and build finishes with error. After that, I run build again and ngcc works fine and build finishes successfully.

## 🔬 Minimal Reproduction
Repository for reproducing:
https://github.com/Stas-tolpekin/ng11-pnpm-kendoui-bug-reproduce

Steps:
1. Run `pnpm i` for install packages
2. Run 'pnpm run build' (it will run default script `ng build` without `--prod`). You get error:
```
PS C:\projects\ng11test1> pnpm run build

> ng11test1@0.0.0 build C:\projects\ng11test1
> ng build


Compiling @angular/core : es2015 as esm2015

Compiling @angular/common : es2015 as esm2015

Compiling @angular/platform-browser : es2015 as esm2015

Compiling @angular/platform-browser-dynamic : es2015 as esm2015

Compiling @angular/animations : es2015 as esm2015

Compiling @progress/kendo-angular-l10n : es2015 as esm2015

Compiling @progress/kendo-angular-common : es2015 as esm2015

Compiling @progress/kendo-angular-common : es2015 as esm2015

An error occurred during the build:
Error: Tried to overwrite C:/projects/ng11test1/node_modules/@progress/kendo-angular-common/dist/es2015/draggable/draggable.directive.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.
```
3. Run 'pnpm run build' again. Build will be finished successfully.

I can see strange things in the console output:
* extra line between `Compiling <package> : es2015 as esm2015` lines. If I use Yarn or NPM there are no extra lines.
* for package `@progress/kendo-angular-common` processing started twice. And just after this the error occurs

And more: 
* If I run ngcc manually it does nothing. 
  ```shell
    PS C:\projects\ng11test1> pnpm run run-ngcc
    
    > ng11test1@0.0.0 run-ngcc C:\projects\ng11test1
    > ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points
    
    PS C:\projects\ng11test1>
  ```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.6
Node: 12.18.2
OS: win32 x64

Angular: 11.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.6 (cli-only)
@angular-devkit/build-angular   0.1102.6
@angular-devkit/core            11.2.6 (cli-only)
@angular-devkit/schematics      11.2.6 (cli-only)
@angular/cli                    11.2.6
@schematics/angular             11.2.6 (cli-only)
@schematics/update              0.1102.6 (cli-only)
rxjs                            6.6.7
typescript                      4.1.5

</code></pre>

**Anything else relevant?**
pnpm version: 5.18.9

**Comment by petebacondarwin** [comment]
I'm afraid that ngcc does not support pnpm and will not do so - other previous reports of this include https://github.com/angular/angular/issues/38023 and https://github.com/angular/angular/issues/32087#issuecomment-523225437).

The solution will be to have all libraries compiled with partial-ivy code, which can be published to npm, rather than ViewEngine. This approach will avoid the need for ngcc and allow support for symlink based scenarios like pnpm. 

Partial ivy-compilation will be available for libraries after v12 but it won't be until v13 at the latest that you are likely to see the core framework libraries (and many other popular ones) migrate their published output to this format, since they would then no longer support ViewEngine projects.
