### ISSUE TITLE
ng update from version 9 to 10 fails with following error.

### ISSUE THREAD

**Issue by sanket-bhalerao** [angular/angular#41389]
ng update @angular/core@10 @angular/cli@10
Using package manager: 'npm'
Collecting installed dependencies...
Found 72 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/build-angular @ "0.1002.3" (was "0.901.15")...
    Updating package.json with dependency @angular/cli @ "10.2.3" (was "9.1.15")...
    Updating package.json with dependency @angular/compiler-cli @ "10.2.4" (was "9.1.13")...
    Updating package.json with dependency @angular/language-service @ "10.2.4" (was "9.1.13")...
    Updating package.json with dependency typescript @ "4.0.7" (was "3.8.3")...
    Updating package.json with dependency @angular/animations @ "10.2.4" (was "9.1.13")...
    Updating package.json with dependency @angular/common @ "10.2.4" (was "9.1.13")...
    Updating package.json with dependency @angular/compiler @ "10.2.4" (was "9.1.13")...
    Updating package.json with dependency @angular/core @ "10.2.4" (was "9.1.13")...
    Updating package.json with dependency @angular/forms @ "10.2.4" (was "9.1.13")...
    Updating package.json with dependency @angular/platform-browser @ "10.2.4" (was "9.1.13")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "10.2.4" (was "9.1.13")...
    Updating package.json with dependency @angular/router @ "10.2.4" (was "9.1.13")...
  UPDATE package.json (3948 bytes)
- Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @angular-devkit/build-angular@0.901.15
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"~0.1002.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"~0.1002.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/compiler-cli@10.2.4
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   peer @angular/compiler-cli@"^10.0.0" from @angular-devkit/build-angular@0.1002.3
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~0.1002.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\user\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2021-03-31T05_25_39_288Z-debug.log
× Package install failed, see above.
× Migration failed. See above for further details.

>I have tried with --force and --legacy-peer-deps option as well but result is the same.

**Comment by sanket-bhalerao** [comment]
with --legacy-peer-deps
![image](https://user-images.githubusercontent.com/9264813/113111077-6d4adc80-9225-11eb-9290-440ef253d347.png)

**Comment by sanket-bhalerao** [comment]
had to downgrade npm to version 6 and then do ng update.

**Comment by rtpHarry** [comment]
Thanks for the tip! 

I was trying to do version 8 to 9 and had a similar set of issues.

I had `nvm` installed and when I checked it was using node v10. 

I also had node v12.14.1 already installed so I switched to that and then it upgraded successfully.
