### ISSUE TITLE
Component requires inline type-checking when using generic types

### ISSUE THREAD

**Issue by MuMaestro** [angular/angular#41395]
# 🐞 bug report

### Affected Package
I don't know if this is caused by a specific package, but related problems indicated these: 
`@angular/compiler-cli - oob.js`
`@angular/language-service - ivy.js`
### Is this a regression?

I didn't work much in the previous versions, but I've tried disabling the experimental Ivy language features as other issues like these indicated as a workaround, so I suppose that like the other (like the directive version, which was already fixed) it's a regression since the Ivy update. 

### Description

When using generic types with restrictions for a class definition it causes the language service to indicate that the current environment does not support inline type-checking. The angular compiler successfully concludes compilation and the app does behave as expected using the built class. 

## 🔬 Minimal Reproduction
I've tried reproducing the error in stackblitz [here](https://stackblitz.com/edit/angular-ivy-dwdyev?file=src/app/app.component.ts), but there are no error matchers. I'm using VScode, and it does appear wherever any variation of the problem is made. [Here](https://imgur.com/SmRW3pq) is a screenshot of the error in my VScode
## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.6
Node: 15.11.0
OS: linux x64

Angular: 11.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1102.6
@angular-devkit/build-angular      0.1102.6
@angular-devkit/core               11.2.6
@angular-devkit/schematics         11.2.6
@angular/cdk                       11.2.6
@angular/cli                       11.2.6
@angular/flex-layout               11.0.0-beta.33
@angular/material                  11.2.6
@angular/material-moment-adapter   11.2.6
@schematics/angular                11.2.6
@schematics/update                 0.1102.6
rxjs                               6.6.7
typescript                         4.1.5
</code></pre>

**Comment by zarend** [comment]
Hello @MuMaestro , thanks for adding the screenshot and the StackBlitz example.

We recently fixed a bug with the `the current environment does not support inline type-checking` error. Please make sure you are using the latest version of the vscode angular extension to get the bug fix.

Can you confirm which version of the vscode extension you are using?

<img width="359" alt="Screen Shot 2021-03-31 at 9 35 20 AM" src="https://user-images.githubusercontent.com/7720245/113179462-7bd4cc00-9204-11eb-9c18-922c8df3ea12.png">
