### ISSUE TITLE
i18n discovery in templates uses different placeholders than in components

### ISSUE THREAD

**Issue by pburkindine** [angular/angular#41398]
# 🐞 Bug report

### Command (mark with an `x`)

- [X] extract-i18n

### Is this a regression?

No

### Description

We love the ability to use $localize i18n strings from component code!  However, we found that we cannot re-use units between HTML template code and TS component code if they contain any interpolation, because the units constructed in the XLF have different placeholders.  At the moment we are creating duplicate units with slightly different names (adding `--comp` to the name, e.g.), but for T-DRY we would prefer to have only one unit shared wherever we need it.

## 🔬 Minimal Reproduction

```
<span
i18n="@@General__n-stars"
>{{ opt }} stars</span>
```

produces a different unit in the messages.xlf file than
```
return $localize`:@@General__n-stars:${this.rating} stars`;
```

... and the result is that whichever reaches the parser last "wins" and breaks the other.
 
the unit created from in component ($localize) syntax looks like:
```
<source><x id="PH" equiv-text="this.rating"/> stars</source>
```
... but in template syntax it's
```
<source><x id="INTERPOLATION" equiv-text="{ opt }"/>​ stars</source>
```

## 🔥 Exception or Error

Whichever unit gets overwritten will break during the compile, saying it can't find a match.

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.1.7
Node: 12.18.3
OS: darwin x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cdk                    10.2.7
@angular/cli                    10.1.7
@angular/material               10.2.7
@schematics/angular             10.1.7
@schematics/update              0.1001.7
rxjs                            6.5.5
typescript                      4.0.3
</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
A hidden feature in i18n markers is that you can actually give placeholders names:

```html
<span i18n="@@General__n-stars">{{ stars // i18n(ph="STARS") }} stars</span>
```

You can also do the same in `$localize` tagged strings (this is documented - see [naming placeholders](https://next.angular.io/api/localize/init/$localize#description)).

```ts
  message = $localize`:@@General__n-stars:${this.stars}:STARS: stars`;
```

This will result in the following extracted XLIFF:

```xml
<trans-unit id="General__n-stars" datatype="html">
  <source><x id="STARS" equiv-text="{{ stars // i18n(ph=&quot;STARS&quot;) }}"/> stars</source>
  <context-group purpose="location">
    <context context-type="sourcefile">src/app/app.component.html</context>
    <context context-type="linenumber">1</context>
  </context-group>
  <context-group purpose="location">
    <context context-type="sourcefile">src/app/app.component.ts</context>
    <context context-type="linenumber">10</context>
  </context-group>
</trans-unit>
```

Of course you could just rename only one half to the generated property of the other one (e.g. `PH` or `INTERPOLATION`) but if you are going to go to the effort of custom ids then why not custom placeholders too?

**Comment by petebacondarwin** [comment]
Hope that helps. Closing as this is working as designed.
