### ISSUE TITLE
Proposal: Easy component rendering dynamically

### ISSUE THREAD

**Issue by mikehaas763** [angular/angular#4140]
It's easiest to explain what/why with a use case.

I have a "dashboard" application. The dashboard is used to render a number of different isolated components.

The problem is that which components are being rendered can change based on a number of different factors in the app. User preferences being one of them. Although only a handful of components will ever be rendered at one time, there are hundreds of components in the pool that *can* be rendered. It's a completely dynamic experience.

I don't want to have a massive switch or other conditional construct that lists everything. Although not the nicest this is possible by using the $compile service directly in ng1.

It would be awesome and I know it would solve this problem for a lot of people if there was an easy to use API. I don't want to get away from declarative UI programming but it's not reasonable to expect devs to maintain a switch like declaration with hundreds of code paths.

**Comment by robwormald** [comment]
@mikehaas763 DynamicComponentLoader might be the API you'd want to use for this - with loader.loadAsRoot, .loadIntoLocation and .loadNextToLocation you should be able to assemble an interface based on whatever. I did a plunk for somebody the other day, similar idea : http://plnkr.co/edit/jAmMZKz2VqponmFtPpes?p=preview

**Comment by mikehaas763** [comment]
@robwormald I wasn't aware of that. I like the plunk you created it's a pretty elegant solution. Guess I can close this. Thanks.

**Comment by alexfluger** [comment]
Hi @robwormald, can you improve your plunk or point me to some documentation on how to bind data to these dynamically loaded widgets? Ideally, I want to have two-way binding between container and dynamically loaded child. Thank you in advance.

**Comment by drew-moore** [comment]
@alexfluger +1
