### ISSUE TITLE
DatePipe return wrong week of year

### ISSUE THREAD

**Issue by Yberion** [angular/angular#41412]
# 🐞 bug report

### Affected Package

The issue is caused by `DatePipe` from `@angular/common`

### Is this a regression?

 I have no idea

### Description

I'd like to get the week of year following the `ISO8601` standard but the number returned is wrong.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-kffpiy?file=src/app/app.component.ts

In this case it should return `11` according to the `ISO8601`.

https://www.epochconverter.com/weeks/2021

No matter the localisation I put it doesn't change.

Even if I use a `Date` object and convert it using `toISOString()` it doesn't change.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.4
Node: 15.11.0
OS: win32 x64

Angular: 11.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.4
@angular-devkit/build-angular   0.1100.4
@angular-devkit/core            11.0.4
@angular-devkit/schematics      11.0.4
@angular/cdk                    11.0.3
@angular/material               11.0.3
@schematics/angular             11.0.4
@schematics/update              0.1100.4
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
You are correct that `w` does not correspond to the ISO date week. It matches the definition used by US and a number of other non-European countries, where the first day of the week is a Sunday. I updated your StackBlitz to make this clear:

https://stackblitz.com/edit/angular-ivy-9sekcq?file=src%2Fapp%2Fapp.component.html

You can see that the first week of the year begins on 2021-01-03 (Sunday).

This is a known issue and is being tracked here https://github.com/angular/angular/issues/39606
