### ISSUE TITLE
Angular Language Service does not work anymore (VS Code)

### ISSUE THREAD

**Issue by bojidaryovchev** [angular/angular#41431]
Hello, I started a new project using Angular v11, so I updated my Angular Language Service extension to v11.2.9

I am using VS Code

It doesn't seem to work anymore (sometimes it does for a bit, but then it stops again)

I don't see any problem in the Output section, however I am no longer able to, lets say, press F12 in the HTML of a component and get navigated to the corresponding function / property, or even have suggestions of known type properties of an object as I type...

This is kind of a bummer as it defies the purpose of using it.. I am opening this issue to find out if it's something on my side or perhaps other people are too encountering the problem.

Cheers!

**Comment by bojidaryovchev** [comment]
Update:

I tried having strictTemplates set to true in the tsconfig.json angularCompilerOptions and now it seems to work, however I am pretty sure the Angular Language Service should be working regardless of whether the flag is enabled or not

**Comment by atscott** [comment]
Closing as this appears to be working as expected based on the information provided. The language service provides information based on what is defined by the compiler options. This is aligned with the behavior of other services as well. For example, changing the TypeScript compiler options has an affect on the diagnostics provided by the Typescript language service. `strictTemplates` will become the default for new CLI applications in v12 and we also have an informational popup that indicates features may not be available without the option enabled along with links for more information.

**Comment by atscott** [comment]
Reoponing to track as a documentation issue. @alxhub and I are going to work on documenting this in a few more places ahead of the v12 release.

**Comment by atscott** [comment]
Closing as this information has been added to angular.io and the main README.md in https://github.com/angular/vscode-ng-language-service/

https://github.com/angular/vscode-ng-language-service/commit/24ce70a9281c05bf103c108999c57abeee97c0db
https://angular.io/guide/language-service#configuring-compiler-options-for-the-angular-language-service
