### ISSUE TITLE
Even though Ivy is disabled still getting the Uncaught TypeError: Cannot read property 'id' of undefined at registerNgModuleType 

### ISSUE THREAD

**Issue by rameshep1989** [angular/angular#41433]
tsconfig.app.json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": ["node"],
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "src/test.ts",
    "src/**/*.spec.ts"
  ]
}

package.json

{
  "name": "TestApp",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.1.2",
    "@angular/cdk": "~8.2.3",
    "@angular/common": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/material": "~8.2.3",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@ionic-native/android-permissions": "^5.31.1",
    "@ionic-native/app-rate": "^5.31.1",
    "@ionic-native/app-version": "^5.31.1",
    "@ionic-native/camera": "^5.31.1",
    "@ionic-native/clipboard": "^5.31.1",
    "@ionic-native/contacts": "^5.31.1",
    "@ionic-native/core": "^5.31.1",
    "@ionic-native/deeplinks": "^5.31.1",
    "@ionic-native/device": "^5.31.1",
    "@ionic-native/facebook": "^5.31.1",
    "@ionic-native/file": "^5.31.1",
    "@ionic-native/google-analytics": "^5.31.1",
    "@ionic-native/image-resizer": "^5.31.1",
    "@ionic-native/in-app-browser": "^5.31.1",
    "@ionic-native/ionic-webview": "^5.31.1",
    "@ionic-native/keyboard": "^5.31.1",
    "@ionic-native/native-audio": "^5.31.1",
    "@ionic-native/network": "^5.31.1",
    "@ionic-native/onesignal": "^5.31.1",
    "@ionic-native/screen-orientation": "^5.31.1",
    "@ionic-native/social-sharing": "^5.31.1",
    "@ionic-native/splash-screen": "^5.31.1",
    "@ionic-native/status-bar": "^5.31.1",
    "@ionic-native/unique-device-id": "^5.31.1",
    "@ionic-native/vibration": "^5.31.1",
    "@ionic-native/video-editor": "^5.31.1",
    "@ionic-super-tabs/angular": "^6.4.0",
    "@ionic/angular": "^4.11.13",
    "@types/hammerjs": "^2.0.39",
    "aws-sdk": "^2.879.0",
    "copy-webpack-plugin": "^5.1.0",
    "cordova-android": "8.1.0",
    "cordova-clipboard": "^1.3.0",
    "cordova-gallery-access": "^3.0.3",
    "cordova-plugin-android-permissions": "^1.1.2",
    "cordova-plugin-app-version": "^0.1.12",
    "cordova-plugin-apprate": "^1.7.2",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-contacts": "^3.0.1",
    "cordova-plugin-dialogs": "^2.0.2",
    "cordova-plugin-facebook4": "^6.4.0",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-google-analytics": "^1.9.0",
    "cordova-plugin-inappbrowser": "^3.2.0",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.2.1",
    "cordova-plugin-nativeaudio": "^3.0.9",
    "cordova-plugin-nativestorage": "^2.3.2",
    "cordova-plugin-network-information": "^2.0.2",
    "cordova-plugin-screen-orientation": "^3.0.2",
    "cordova-plugin-vibration": "^3.1.1",
    "cordova-plugin-video-editor": "^1.1.3",
    "cordova-plugin-x-socialsharing": "^5.6.8",
    "core-js": "^2.6.12",
    "es6-promise-plugin": "^4.2.2",
    "hammerjs": "^2.0.8",
    "info.protonet.imageresizer": "^0.1.1",
    "ion-bottom-drawer": "^2.0.0",
    "ionic-image-loader": "^7.0.0-beta.2",
    "ionic-plugin-deeplinks": "^1.0.22",
    "ionic-pullup": "^4.0.0-beta.6",
    "jwt-decode": "^2.2.0",
    "libphonenumber-js": "^1.9.11",
    "ng-click-outside": "^6.0.0",
    "ng-lazyload-image": "^7.1.0",
    "ngx-infinite-scroll": "^8.0.2",
    "ngx-linkifyjs": "^1.3.0",
    "ngx-mask": "^8.1.6",
    "ngx-pinch-zoom": "^1.2.5",
    "ngx-socket-io": "^3.2.0",
    "onesignal-cordova-plugin": "^2.11.3",
    "pica": "^5.3.0",
    "rxjs": "^6.6.6",
    "socket.io-client": "^2.4.0",
    "timeago.js": "^4.0.2",
    "tslib": "^1.14.1",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@ionic/angular-toolkit": "^2.3.3",
    "@ionic/app-scripts": "^3.2.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^8.10.66",
    "codelyzer": "^5.2.2",
    "com.subitolabs.android.cordova.galleryapi": "git+https://github.com/Collaborne/cordova-gallery-api.git",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-splashscreen": "^5.0.4",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-whitelist": "^1.3.4",
    "html-webpack-plugin": "^4.5.2",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "protractor": "^5.4.4",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3",
    "webpack": "^4.46.0"
  },
  "description": "An Ionic project",
    "platforms": [
      "android"
    ]
  }
}

angular.json

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "defaultProject": "app",
  "newProjectRoot": "projects",
  "projects": {
    "app": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "www",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "assets": [
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "assets"
              },
              {
                "glob": "**/*.svg",
                "input": "node_modules/ionicons/dist/ionicons/svg",
                "output": "./svg"
              }
            ],
            "styles": [
              "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
              {
                "input": "src/theme/variables.scss"
              },
              {
                "input": "src/global.scss"
              }
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "15mb",
                  "maximumError": "15mb"
                }
              ]
            },
            "ci": {
              "progress": false
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "app:build:production"
            },
            "ci": {
              "progress": false
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "app:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "styles": [
              "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css"
            ],
            "scripts": [],
            "assets": [
              {
                "glob": "favicon.ico",
                "input": "src/",
                "output": "/"
              },
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "/assets"
              }
            ]
          },
          "configurations": {
            "ci": {
              "progress": false,
              "watch": false
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json",
              "e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "app:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "app:serve:production"
            },
            "ci": {
              "devServerTarget": "app:serve:ci"
            }
          }
        },
        "ionic-cordova-build": {
          "builder": "@ionic/angular-toolkit:cordova-build",
          "options": {
            "browserTarget": "app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "app:build:production"
            }
          }
        },
        "ionic-cordova-serve": {
          "builder": "@ionic/angular-toolkit:cordova-serve",
          "options": {
            "cordovaBuildTarget": "app:ionic-cordova-build",
            "devServerTarget": "app:serve"
          },
          "configurations": {
            "production": {
              "cordovaBuildTarget": "app:ionic-cordova-build:production",
              "devServerTarget": "app:serve:production"
            }
          }
        }
      }
    }
  },
  "cli": {
    "defaultCollection": "@ionic/angular-toolkit"
  },
  "schematics": {
    "@ionic/angular-toolkit:component": {
      "styleext": "scss"
    },
    "@ionic/angular-toolkit:page": {
      "styleext": "scss"
    }
  }
}

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template. It'd be great if you could include a minimal repro in a form of GitHub repository and the necessary instructions on how to reproduce the issue.
