### ISSUE TITLE
Unable to install Angular CLI on CentOS(Without Internet)

### ISSUE THREAD

**Issue by kurianlinu** [angular/angular#41449]
Hi,
I installed NodeJS, But I am unable to install AngularCLI, My machine is a CentOS 7 based VM. There is no Internet connectivity to perform below command to install AngularCLI. Can you please direct me, how to install Angular CLI offline(without Internet)?
"npm install -g @angular/cli".

Thanks,
Linu

[CLI.](url
![Angular CLI](https://user-images.githubusercontent.com/81944664/113536815-9a680800-95f4-11eb-89fe-4106668f4324.JPG)
)

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
