### ISSUE TITLE
Angular HttpResponse.clone() returns body reference, instead of deep copy

### ISSUE THREAD

**Issue by JoshThunar** [angular/angular#41454]
# 🐞 bug report

### Affected Package

HttpResponse.clone() in packages/common/http/src/response.ts
https://github.com/angular/angular/blob/154129b9defa9295f4684c595d1981c9b3c970c5/packages/common/http/src/response.ts#L289-L303

### Is this a regression?

The implementation of this method was not changed since the release (4.3.0, commit 37797e2b4e1ddc6560ae6c8364ea678ffbaa3de1).

### Description

HttpResponse.clone() does not create a deep copy of fields (body, headers...). Instead, it just uses the standard JavaScript approach to copy the object reference. Therefore, passing cloned HttpReponse can allow receiver to edit the original object

SO thread:
https://stackoverflow.com/questions/66926776/angular-httpresponse-clone-does-not-create-a-new-object

## 🔬 Minimal Reproduction

Example with HttpInterceptor:
https://stackblitz.com/edit/angular-interceptors-rtrycu?file=app%2Finterceptors.ts

```
// Interceptor
cache: Map<string, HttpResponse<any>> = new Map();

intercept(
// ...
  if (cachedResponse) {
    return of(cachedResponse.clone());
  else {
    return next.handle(req);
  }
)

// Subscription in the component
this.http.get<any>(url).subscribe(res => {
  res.title = "Invalid title!"; // cached data in interceptor is modified!
```

**Comment by jelbourn** [comment]
@alxhub do you remember if this was intentional? I could definitely see avoiding a deep clone since that can end up being expensive.

**Comment by jessicajaniuk** [comment]
We believe this is WIA. A deep clone is costly for performance and might fail if the content has a circular reference, which could be added by an interceptor.
