### ISSUE TITLE
Command Injection [High Severity] in @angular/localize

### ISSUE THREAD

**Issue by kiet-ba-huynh** [angular/angular#41466]
High Security Issue with Command Injection when running a `snyk test`:
![image](https://user-images.githubusercontent.com/67493335/113672377-06349880-96fb-11eb-95ca-ed09698e1795.png)

Upgrade to the latest @angular/localize@11.2.8 does not help. I think because a fixed version @babel/core@7.8.3 is used as a dependency. 

Perhaps the fix is simply upgrade @babel/core to a newer version or even remove it if you no longer need it?

**Comment by RA80533** [comment]
It appears that @babel/core@7.8.3 depends on lodash with a semver of ^4.17.13 which would be compatible with the fixed version. Do exact versions have the side effect of requiring the lowest version in a semver range?

**Comment by RA80533** [comment]
@kiet-ba-huynh What version of lodash is actually installed in node_modules?

**Comment by alan-agius4** [comment]
The problem looks like the old version of lodash is being installed. This is typically caused by an unmaintained lock file.

Deleting node_modules and lock file prior to running yarn/npm install will solve the above problem.
