### ISSUE TITLE
Facing the Issue while creating a new Project "The file will have its original line endings in your working directory"

### ISSUE THREAD

**Issue by UV74RAJ** [angular/angular#41462]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

![Capture](https://user-images.githubusercontent.com/45942420/113646406-62210200-96a6-11eb-99b3-bbb49071d60f.JPG)

**Comment by RA80533** [comment]
Windows terminates lines with both a carriage return character (CR) and a line feed (LF) character whereas other systems just use a line feed character. The warnings are simply telling you that the line endings in the files being generated are going to be different from the files they’re based on.

**Comment by gkalpak** [comment]
As @RA80533 said, this is standard git behavior. See [here][1] for more info on how git works with whitespace and how you can configure your git client.

[1]: https://git-scm.com/book/it/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace
