### ISSUE TITLE
Packages published from the repository have incorrect permission bits

### ISSUE THREAD

**Issue by RA80533** [angular/angular#41461]
# 🐞 bug report

### Affected Package

- @angular/animations
- @angular/common
- @angular/compiler
- @angular/compiler-cli
- @angular/core
- @angular/forms
- @angular/platform-browser
- @angular/platform-browser-dynamic
- @angular/router
- zone.js

The issue likely affects all packages published from this repository.

### Is this a regression?

Versions prior to Angular 6 do not exhibit the issue.

### Description

Permission bits are set to 755 rather than 644.

### Expected

```console
$ ls -ln node_modules/zone.js/package.json
-rw-r--r--  1 501  20  1406 Mar 21 20:41 node_modules/zone.js/package.json
```

### Actual

```console
$ ls -ln node_modules/zone.js/package.json
-rwxr-xr-x  1 501  20  1406 Mar 21 20:41 node_modules/zone.js/package.json
```

**Comment by JeanMeche** [comment]
This issue is no longer.
