### ISSUE TITLE
Angular migration from 8.1.13 to 9.1  problem in custom library

### ISSUE THREAD

**Issue by Madhu-nair** [angular/angular#41469]
while migrating from angular 8 to 9.1 

using command "ng update @angular/core@9 @angular/cli@9"

> ** Executing 'migration-v9-undecorated-classes-with-di' of package '@angular/core' **
> 
> ❯ Undecorated classes with DI migration.
>   As of Angular 9, it is no longer supported to use Angular DI on a class that does not have an Angular decorator.
>   Read more about this here: https://v9.angular.io/guide/migration-undecorated-classes
> 
>     This migration uses the Angular compiler internally and therefore projects that no longer build successfully after the update cannot run the migration. Please ensure there are no AOT compilation errors and rerun the migration. The following project failed: src/tsconfig.app.json

error pattern 
 Error: error TS100: Cannot determine the module for class partDirective in path.
 projects/mylibrary/lib/core/part/part-pro.directive.ts  and  add partDirective  to the NgModule to fix it 

fails to  compile even after disabling IVY and AOT  .

**Comment by petebacondarwin** [comment]
Did you try adding `@Directive()` to the `partDirective` class?

**Comment by Madhu-nair** [comment]
> Did you try adding `@Directive()` to the `partDirective` class? For example:
> 
> ```ts
> @Directive()
> export class partDirective {
>  ...
> }
> ```

@Directive({
  selector: '[partplan]',
  exportAs: 'partplan'
})
export class partDirective implements AfterViewInit, OnDestroy, OnChanges {
...
 }

**Comment by jelbourn** [comment]
@Madhu-nair can you share any sort of reproduction? There's not much we can do without seeing the affected code
