### ISSUE TITLE
@angular/localize localized interpolation only updates once

### ISSUE THREAD

**Issue by 2troger** [angular/angular#41478]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/localize

### Is this a regression?

Yes, this works in a out of the box new angular project.

### Description

Changing the value of an interpolated field does not update the displayed text when running with a locale that is not the source.
I have `en` (source) and `es` localizations with nothing different between them and the `es` messages file has `<target>` tags that match the `<source>`. 
When I run with `en`, I can click a button and change the displayed value.
When I run with `es`, I can click a button but nothing changes on the display.

Here is an example:
This is in a template
`<div class="label" (click)="click()" i18n>{{ test }}</div>`

This is the component
<pre><code>
@Component({
  selector: 'application-info-header',
  templateUrl: './application-info-header.component.html',
  styleUrls: ['./application-info-header.component.scss'],
})
export class ApplicationInfoHeaderComponent implements OnInit {
  @Input()
  currentApplication: Application;

  test = false;

  click() {
    this.test = !this.test;
  }
}
</code></pre>

When I click the label with the source locale, I see the text change from False -> True -> False - etc.
When I click the label with the `es` locale, I never see the text change.

## 🔬 Minimal Reproduction

I could not reproduce this in a regular Angular project and I cannot create a new NX workspace because the command errors every time.

## 🌍  Your Environment

I work in an NX Angular workspace with components spread across a couple libraries.

**Angular Version:**
<pre><code>
Angular CLI: 11.0.7
Node: 13.14.0
OS: darwin x64

Angular: 11.2.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cdk                    11.2.7
@angular/cli                    11.0.7
@angular/material               11.2.7
@schematics/angular             11.0.7
@schematics/update              0.1100.7
rxjs                            6.6.7
typescript                      4.0.7
</code></pre>

**Comment by petebacondarwin** [comment]
Can you provide the relevant translation messages from the extracted file and the translated file?

**Comment by 2troger** [comment]
Here is a part of messages.xlf.
```
<trans-unit id="96505126c5c4484cc7fec7911b53cdd0e4c24269" datatype="html">
  <source><x id="INTERPOLATION" equiv-text="{{ test }}"/></source>
  <context-group purpose="location">
    <context context-type="sourcefile">libs/connect/applications/src/lib/application-info-header/application-info-header.component.html</context>
    <context context-type="linenumber">14</context>
  </context-group>
</trans-unit>
```

Here is a part of messages.es.xlf. 
```
 <trans-unit id="96505126c5c4484cc7fec7911b53cdd0e4c24269" datatype="html">
  <source><x id="INTERPOLATION" equiv-text="{{ test }}"/></source>
  <target><x id="INTERPOLATION" equiv-text="{{ test }}"/> (es)</target>
    <context-group purpose="location">
      <context context-type="sourcefile">libs/connect/applications/src/lib/application-info-header/application-info-header.component.html</context>
      <context context-type="linenumber">14</context>
    </context-group>
</trans-unit>
```

Could be related but I don't want to derail the ticket:
I have also seen the translations behave strangely when running in the `es` locale. All of these translations have " (es)" at the end of their `<target>` tags. But as the image below shows, some of those " (es") became " (s)", " (en)", or " (is)".

![image](https://user-images.githubusercontent.com/9057168/113937668-23329f80-97bf-11eb-860e-a9313fd4c2ee.png)

**Comment by petebacondarwin** [comment]
Thanks for providing this additional information. There is nothing here that I can see would be the cause of the problem.
I would need access to a runnable reproduction to be able to help you any further.
You may also wish to raise an issue with Nx if you say that this is not reproducible with standard Angular CLI.

**Comment by 2troger** [comment]
I figured this out...

The issues were with Chrome "translating" things. I hadn't tried in another browser but I realized Chrome has been acting odd and thinking English Pages were French or Spanish and translating them back to English somehow. 

Thanks for your time, this ate way too much of my time haha.

We can close this ticket.

**Comment by petebacondarwin** [comment]
Thanks for updating us. I'm glad you got to the bottom of it. It is always good to turn off any extensions when debugging.
