### ISSUE TITLE
Router animation not working when also animating an outer container

### ISSUE THREAD

**Issue by mduft** [angular/angular#41483]
# 🐞 bug report

### Affected Package
This seems to be a problem in `@angular/animations`.

### Is this a regression?
No, it also does not work in previous versions AFAICT (tested 7, 10 and 11).

### Description

I have an issue with my angular router animation(s). I have various animations on the page. A quick outline:

 1. There is a main content router-outlet. It uses a simple fade-in/fade-out animation - works great
 2. There is a secondary "panel" router-outlet, which shows additional data. It uses the very same router animation, which also works great.
 3. The "panel" on the side *also* supports a "maximized" mode. This makes the panel wider. In this case the width of the panel is animated (which is an indirect parent div of the actual router-outlet). If this happens, the router animation of the panel does not play properly. While animating the width of the panel, one can see the content of *both* components, the leaving and the entering one on screen for a brief duration.

I already tried to add `group` with `animateChild()` blocks to my animations to no avail...

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-gci3kd?file=src/app/app.component.ts

Switch between 'One' and 'Two' - this will trigger two animations through different mechanisms - the container width resizing (the one with the red border) and the router animation. The router animation is not played correctly, it will have both components visible without any animation styles applied to them.

Switch between 'Two' and 'Three' - this will trigger only the router animation as the animation state of the container stays the same - in this case the animation is rendered correctly.

## 🔥 Exception or Error
No visible error, just does not work.

## 🌍  Your Environment

**Angular Version:**
7 - 11, stackblitz uses the current stackblitz template using 11.0.8

**Anything else relevant?**
It happens with both chrome and firefox

**Comment by dario-piotrowicz** [comment]
Hi @mduft I believe your use of `animateChild` in the `containerAnimation` trigger to be incorrect as it needs to be applied inside a `query()` (as specified here: https://angular.io/api/animations/animateChild#usage-notes)

I've modified your stackblitz in the following way:
```diff
- transition("* => *", group([animateChild(), animate("0.2s ease")]))
+ transition("* => *", group([query('@routeAnimations', animateChild()), animate("0.2s ease")]))
``` 
in this way you can see that the animation of the components does work between __one__ and __two__ as well (https://stackblitz.com/edit/angular-ivy-uwhqvy?file=src/app/app.component.ts)

but now we get another issue :sweat: , after the animations complete you will actually get both components on the screen, that is actually a real bug, I've spent a bunch of time getting to the bottom of it and I think I've found the reason/a solution for it

I'll try to open a PR for the fix in a few days :slightly_smiling_face:

**Comment by mduft** [comment]
Hey, thats great news :) Thanks a ton for working on it!

**Comment by dario-piotrowicz** [comment]
@mduft PR merged :slightly_smiling_face: 

with the small change I mentioned above + using the latest package all works as expected :slightly_smiling_face: 

[stackblitz](https://stackblitz.com/edit/angular-ivy-jm8qmq?file=src/app/app.component.ts) :rocket:

**Comment by mduft** [comment]
Yay, this is great news. Thanks a ton! Will update immediately :)
