### ISSUE TITLE
Run CanDeactivate guards before cross-origin navigation

### ISSUE THREAD

**Issue by BFunk86** [angular/angular#41498]
# 🐞 bug report

### Description

CanDeactivate does not get triggered on first page load when pressing the browser back button. If you navigate to a website like google.com. THen navigate to https://angular-ivy-fz356o.stackblitz.io and press the browser back button the canDeactivate guard is not triggered. It only works after going to another route.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-fz356o?file=src/app/second-page/second-page.component.html

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1102.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@angular/cdk                    11.0.3
@angular/flex-layout            11.0.0-beta.33
@angular/material               11.0.3
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.5.4
typescript                      4.0.5
webpack                         4.42.0

</code></pre>

**Comment by atscott** [comment]
This is due to a browser limitation  - we can't intercept and prevent the navigation with our async guard logic. 

You have the option of adding your own `onbeforeunload` hook.

This may also be available in the future with the proposed App History API. Relevant discussion is here: https://github.com/WICG/app-history/issues/32

**Comment by BFunk86** [comment]
Thanks @atscott for the quick response. I had a feeling this had something to do with the browser. I tried to use the beforeunload event, but unfortunately in my use case I don't want the alert that happens.
