### ISSUE TITLE
when use zone.js & ant design, the page will Endless loop

### ISSUE THREAD

**Issue by nuonuoge** [angular/angular#41506]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/zone.js

### Is this a regression?

0.11

### Description
when use select tooltip popover, th page will in Endless loop
https://github.com/ant-design/ant-design/issues/28537
![image](https://user-images.githubusercontent.com/16378798/114008257-a40f9b00-9894-11eb-9e7d-a72feeea4972.png)

## 🔬 Minimal Reproduction
https://codesandbox.io/s/sanchonghongfafangshi-antd494-forked-92z1j?file=/index.js

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

angular: 11
ant-desing>= 4.7

</code></pre>

**Anything else relevant?**

**Comment by nuonuoge** [comment]
use with [rc-trigger v4.5.0](https://github.com/react-component/trigger),when import zone.js the setstate never refresh value, endless loop，if use settimout instead promise.resolve() will slove, But I don't know this is caused by zone.js Or trigger
![image](https://user-images.githubusercontent.com/16378798/114968256-910a5580-9ea8-11eb-9196-b66e2a08ade1.png)

**Comment by JiaLiPassion** [comment]
@nuonuoge , I can not reproduce (click the `popover` and the `click` button`, popup menu is displayed correctly), could you give more details steps to reproduce the issue?

**Comment by nuonuoge** [comment]
@JiaLiPassion you can use select，when click it is  recurrence 100%，the codebox example you must click quickly when the page appears

**Comment by nuonuoge** [comment]
@JiaLiPassion you can use select，when click it is  recurrence 100%，the codebox example you must click quickly when the page appears

**Comment by JiaLiPassion** [comment]
@nuonuoge , I can reproduce now, it is an edge case, I will try to figure out how to make a workable solution...

**Comment by nuonuoge** [comment]
@JiaLiPassion when use micro-frontends(angular&vue&react), it's a big side effects, hope can be resolved quickly

**Comment by Archao-ME** [comment]
I have the same issues too. Is it possible to stop the zone for some components?

**Comment by imcuttle** [comment]
has the same issues too   +1

**Comment by imcuttle** [comment]
I guess the issue is because of single-spa's side effect.
https://github.com/single-spa/single-spa-angular/issues/113

**Comment by AnteaterKit** [comment]
I have the same problem. I use ant design with runOutsideAngular, but PopOver trigger zone js. And i have Endless loop. It's produced after migration from angular 10 to 11.

**Comment by kbakba** [comment]
Temporary solution:

patch for `rc-trigger`:

```diff
diff --git a/node_modules/rc-trigger/es/Popup/PopupInner.js b/node_modules/rc-trigger/es/Popup/PopupInner.js
index 66e4ac8..837e69d 100644
--- a/node_modules/rc-trigger/es/Popup/PopupInner.js
+++ b/node_modules/rc-trigger/es/Popup/PopupInner.js
@@ -78,9 +78,9 @@ var PopupInner = /*#__PURE__*/React.forwardRef(function (props, ref) {
       setAlignedClassName(nextAlignedClassName); // Repeat until not more align needed

       if (alignedClassName !== nextAlignedClassName) {
-        Promise.resolve().then(function () {
+        setTimeout(function () {
           forceAlign();
-        });
+        }, 0);
       } else {
         goNextStatus(function () {
           var _prepareResolveRef$cu;
diff --git a/node_modules/rc-trigger/lib/Popup/PopupInner.js b/node_modules/rc-trigger/lib/Popup/PopupInner.js
index 0fc3e2f..cc7149b 100644
--- a/node_modules/rc-trigger/lib/Popup/PopupInner.js
+++ b/node_modules/rc-trigger/lib/Popup/PopupInner.js
@@ -98,9 +98,9 @@ var PopupInner = /*#__PURE__*/React.forwardRef(function (props, ref) {
       setAlignedClassName(nextAlignedClassName); // Repeat until not more align needed

       if (alignedClassName !== nextAlignedClassName) {
-        Promise.resolve().then(function () {
+        setTimeout(function () {
           forceAlign();
-        });
+        }, 0);
       } else {
         goNextStatus(function () {
           var _prepareResolveRef$cu;
```

Patch maybe used via [yarn patch](https://yarnpkg.com/cli/patch) or [patch-package](https://www.npmjs.com/package/patch-package)

**Comment by xiaody** [comment]
I managed to create a reproduction without ant design, but havn't figured out why this happens.

https://stackblitz.com/edit/react-ylox6f

**Comment by xiaody** [comment]
After quite some debugging, I made a pure JS reproduction without any React thing https://stackblitz.com/edit/angular-41506 .
This reproduction kinda simulates React's scheduler and invoke guard, and obviously `zone-patch-message-port` fixes the issue.

For the two React reproductions above in this thread, adding `import 'zone.js/plugins/zone-patch-message-port';` **BEFORE** `import ... from 'react-dom'` also does the fix.


> @JiaLiPassion https://stackblitz.com/edit/react-mfqbxp you can use this repo, sometimes it's work, you can reopen it times, when click this page will endless loop delete zone.js，it's work

--> https://stackblitz.com/edit/react-hisbdi?file=src%2Findex.js fixed


> I managed to create a reproduction without ant design, but havn't figured out why this happens.
> 
> https://stackblitz.com/edit/react-ylox6f

--> https://stackblitz.com/edit/react-zyezvq?file=src%2Findex.js fixed


Unfortunately for old version's antd Select, `zone-patch-message-port` is not enough. There seems some other issues about ResizeObserver. But the latest antd(4.17.3) seems compatible as I tried.

**Comment by JiaLiPassion** [comment]
Sorry for the late reply, I created a PR to fix this one.

**Comment by Sherry-Lee** [comment]
Is this issue solved? I'm using the angular 11 and ant, facing the same problem :(

**Comment by yanhaijing** [comment]
https://github.com/react-component/trigger/commit/017131d9afdc0181a8f2441370ff938386aa1212?diff=split
新的rc-trigger改成了useEffect实现，测试已经不存在这个问题了

**Comment by auzmartist** [comment]
@nuonuoge - wondering if you were able to resolve the issue? I am seeing the same in my own micro-front-end app.

**Comment by yanhaijing** [comment]
> @nuonuoge - wondering if you were able to resolve the issue? I am seeing the same in my own micro-front-end app.

Two ways to solve the problem:

1. to upgrade antd

> [react-component/trigger@017131d?diff=split](https://github.com/react-component/trigger/commit/017131d9afdc0181a8f2441370ff938386aa1212?diff=split) 新的rc-trigger改成了useLayoutEffect 实现，测试已经不存在这个问题了

2. Fix node_modules rc-trigger by self, you can apply it via [yarn patch](https://yarnpkg.com/cli/patch) or [patch-package](https://www.npmjs.com/package/patch-package)



> Temporary solution:
> 
> patch for `rc-trigger`:
> 
> ```diff
> diff --git a/node_modules/rc-trigger/es/Popup/PopupInner.js b/node_modules/rc-trigger/es/Popup/PopupInner.js
> index 66e4ac8..837e69d 100644
> --- a/node_modules/rc-trigger/es/Popup/PopupInner.js
> +++ b/node_modules/rc-trigger/es/Popup/PopupInner.js
> @@ -78,9 +78,9 @@ var PopupInner = /*#__PURE__*/React.forwardRef(function (props, ref) {
>        setAlignedClassName(nextAlignedClassName); // Repeat until not more align needed
> 
>        if (alignedClassName !== nextAlignedClassName) {
> -        Promise.resolve().then(function () {
> +        setTimeout(function () {
>            forceAlign();
> -        });
> +        }, 0);
>        } else {
>          goNextStatus(function () {
>            var _prepareResolveRef$cu;
> diff --git a/node_modules/rc-trigger/lib/Popup/PopupInner.js b/node_modules/rc-trigger/lib/Popup/PopupInner.js
> index 0fc3e2f..cc7149b 100644
> --- a/node_modules/rc-trigger/lib/Popup/PopupInner.js
> +++ b/node_modules/rc-trigger/lib/Popup/PopupInner.js
> @@ -98,9 +98,9 @@ var PopupInner = /*#__PURE__*/React.forwardRef(function (props, ref) {
>        setAlignedClassName(nextAlignedClassName); // Repeat until not more align needed
> 
>        if (alignedClassName !== nextAlignedClassName) {
> -        Promise.resolve().then(function () {
> +        setTimeout(function () {
>            forceAlign();
> -        });
> +        }, 0);
>        } else {
>          goNextStatus(function () {
>            var _prepareResolveRef$cu;
> ```
> 
> You can apply it via [yarn patch](https://yarnpkg.com/cli/patch) or [patch-package](https://www.npmjs.com/package/patch-package)
