### ISSUE TITLE
Boolean attributes stopped working

### ISSUE THREAD

**Issue by rkj** [angular/angular#4150]
Until recently code like this:

    <div [attr.foo]="null></div>

would not set foo on the div at all, at this is very useful for interacting with html boolean attributes. In current version it produces:

    <div [attr.foo]="null" foo="null"></div>

**Comment by pkozlowski-opensource** [comment]
Yeh, can reproduce it with alpha.37.

**Comment by pkozlowski-opensource** [comment]
OK, so this is a regression introduced in 6c3c6060a58761734abb7304b044fb87f8deeb20. We are definitively missing a test for this case, PR is on the way.

**Comment by typotter** [comment]
This bug appears to be happening again, at least in angular-dart.

**Comment by zoechi** [comment]
Same here in Dart as well

```html
<div [attr.hidden]="false">
```
results in
```html
<div hidden="false">
```

**Comment by zoechi** [comment]
```html
<div [attr.hidden]="null">
```
works though, but I don't think this is satisfying.

**Comment by PascalPrecht** [comment]
AFAIK this is the intended behaviour

**Comment by zoechi** [comment]
@PascalPrecht thanks for confirming. After I found out that it works with `null` it got that suspicion, but I don't find this pretty. 
In Polymer when the property of type boolean is bound to an attribute, it treats it as boolean attribute. I find this a better approach. 
If I want the binding result in `<div hidden="true">` I can use a string property with value `"true"` or `"false"`.

**Comment by vicb** [comment]
Could any one create an issue for true/false to be supported ? thanks
