### ISSUE TITLE
Make HttpErrorResponse mimic toString() Error class behavior

### ISSUE THREAD

**Issue by orkisz** [angular/angular#41505]
# 🚀 feature request

### Relevant Package

This feature request is for @angular/common

### Description
Currently HttpErrorResponse class does not override default Object's toString() method so it returns [Object object] string. This is a bit problematic when using logging libraries, especially MS AppInsights which rely on toString() to get meaningful exception description.

### Describe the solution you'd like
I would be good to include an override into HttpErrorResponse class:
```
export class HttpErrorResponse extends HttpResponseBase implements Error {
  // ...original content here...

  toString(): string {
    return this.message;
}
```

I can prepare PR if this idea will gain an attention.

### Describe alternatives you've considered
Currently I have workaround:
```
HttpErrorResponse.prototype.toString = function(): string {
  return this.message;
};
```
in my app but it's hacky a bit.

**Comment by petebacondarwin** [comment]
I'll check with the rest of the team next week to see if this is something we would like to be implemented.

**Comment by petebacondarwin** [comment]
@orkisz thanks for your patience with this issue. We discussed it today in our team meeting. Unfortunately we decided that we would rather not add this feature. It would add a non-tree-shakable size increase to bundles and the workaround is straightforward.
