### ISSUE TITLE
namespace angular v1 vs v2

### ISSUE THREAD

**Issue by samio80** [angular/angular#4151]
I there anyway to have both versions running without namespaces collating?

**Comment by gdi2290** [comment]
if you're talking about ES5 ng2 is namespaced as `window.ng` while ng1 `window.angular`

see code [angular2_sfx.ts](https://github.com/angular/angular/blob/master/modules/angular2/angular2_sfx.ts)

**Comment by S-YOU** [comment]
it looks like a workaround, since there is no other choice. "angular2" is named "angular" in project title. ng-change become [chnage] in angular2, and but global names space changed from angular to ng. inconsistent I would say.

**Comment by pkozlowski-opensource** [comment]
IMO this issue is part of the whole ng1 -> ng2 upgrade story, I don't think there is anything specific enough here to be actionable. Closing as the full upgrade / co-existance story is being worked on.

@samio80 happy to re-open if you've got more specific questions / bug reports.
