### ISSUE TITLE
Location.replaceState does not remove history item.

### ISSUE THREAD

**Issue by LucHighwalker** [angular/angular#41514]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/common

### Is this a regression?

I've used this before as expected ages ago, couldn't tell you which version that was though. Probably sometime around v8 give or take a version number.

### Description

I need to remove the url containing a hash parameter from the browser's history. But no matter what I tried, it seems like Location.replaceState behaves the same as Location.go in that it simply pushes a history entry rather than replacing it.

## 🔬 Minimal Reproduction

https://github.com/LucHighwalker/locationReplaceBug

- run `ng serve`
- navigate to http://127.0.0.1:4200/?hash=thishashshouldberemovedfromhistory
- note the hash being removed from url.
- check history to see if url with hash has been removed.

I'm expecting a singular history entry with the url http://127.0.0.1:4200/
Instead there are two entries with the lower one containing the hash parameter.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 11.0.7
Node: 15.11.0
OS: linux x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cli                    11.0.7
@schematics/angular             11.0.7
@schematics/update              0.1100.7
rxjs                            6.6.7
typescript                      4.0.7

</code></pre>

**Anything else relevant?**
I've tried this in both chrome and firefox with the same results.

Some other things I tried is using all available options with Router.forRoot's initialNavigation property. Including disabling initial navigation and processing the hash before using Location.ReplaceState and then initializing the navigation.

I've also tried using Router.navigate (with the replaceUrl option set to true) to navigate to the base url both alone and in combination with Location.replaceState in all possible combinations and order I could think of.

**Comment by atscott** [comment]
Hi @LucHighwalker - I can't reproduce this issue using the repository you've linked. Here is the bit of code that would be relevant and it looks correct to me:
https://github.com/angular/angular/blob/61bfa3d9dfc7c9daecde098aca595b731c3312a0/packages/common/src/location/platform_location.ts#L181-L185
