### ISSUE TITLE
[zonejs] An exception in event handler breaks execution of remaining handlers

### ISSUE THREAD

**Issue by mleibman** [angular/angular#41522]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/zone.js.

### Is this a regression?
AFAICT, it has always been like this.

### Description
W3C event handlers are supposed to be called regardless if one of them throws an exception.
However when global callback handling is used (default), if any of the registered event handlers result in an unhandled exception, execution of all remaining handlers is aborted. This represents a significant and hard-to-detect breakage in event handling just from loading ZoneJS.

https://github.com/angular/angular/blob/51bb922a081a1059929cb549ffbc3cf1d1366e2a/packages/zone.js/lib/common/events.ts#L150-L155

## 🔬 Minimal Reproduction
When run w/o ZoneJS, clicking the button prints both `click 1` and `click 2`.
When run with ZoneJS loaded, only `click 1` is printed.

```javascript
(function() {
  const btn = document.body.appendChild(document.createElement('button'));
  btn.textContent = 'Click me';

  btn.addEventListener('click', () => {
    console.log('click 1');
    throw new Error();
  });

  btn.addEventListener('click', () => {
    console.log('click 2');
  });
})()
```

**Comment by mleibman** [comment]
@JiaLiPassion

**Comment by mleibman** [comment]
This seems pretty bad. Can we prioritize the fix?

**Comment by JiaLiPassion** [comment]
@mleibman, Got it, I will fix this ASAP

**Comment by jelbourn** [comment]
@JiaLiPassion let me or @mhevery know if you need any assistance on this

**Comment by JiaLiPassion** [comment]
@mleibman, just to confirm, in the `Angular` application, since the app runs in the `ngZone`, so the error are caught and handled by the `ngZone`, so the result is all the event listeners will be executed even some listener throw errors.

So in your case, the event listeners are not registered in the `ngZone`, is that correct?

**Comment by JiaLiPassion** [comment]
@jelbourn , got it, thank you!

**Comment by mleibman** [comment]
@JiaLiPassion Yes, but only if those event listeners were registered in `NgZone`. Anything registered outside of it or handled by another zone delegate that throws or returns `true` from `handleError()` will abort event handler chain execution.

**Comment by JiaLiPassion** [comment]
@mleibman , got it, thanks!

**Comment by mleibman** [comment]
Thanks for a quick fix!

**Comment by AndrewKushnir** [comment]
@mleibman FYI we are rolling back the change due to some issues on CI that need more investigation. Please do avoid relying on this behavior for now. Thank you.

**Comment by AndrewKushnir** [comment]
FYI, reopening this issue due to the rollback of the change, see https://github.com/angular/angular/pull/41562#issuecomment-822696973.
