### ISSUE TITLE
bug: service-worker, UNRECOVERABLE_STATE is not working

### ISSUE THREAD

**Issue by expcapitaldev** [angular/angular#41555]
# 🐞 bug report
UNRECOVERABLE_STATE is not triggered from ngsw-worker.js as expected with case below

### Affected Package

 The issue is caused by package @angular/service-worker

### Is this a regression?
Feature with UNRECOVERABLE_STATE is not working , see https://angular.io/guide/service-worker-communications#handling-an-unrecoverable-state

### Description
With case below in ngsw-worker.js file we go to the "cacheBustedFetchFromNetwork" method and have "response.ok" === true, SW trigger "throw new SwCriticalError(`Hash mismatch (cacheBustedFetchFromNetwork) error" but expected "throw new SwUnrecoverableStateError(`Failed to retrieve hashed resource from the server."

We can fix that issue
See Minimal Reproduction
 

## 🔬 Minimal Reproduction
Easy Reproduction, without repo example.

1. Create build with SW and 1 minimum chunk
2. Open url and waiting while SW created (unregister your SW if exist before )
3. Open "Cache storage in from dev tools"
<img width="1183" alt="ngsw unrecoverable" src="https://user-images.githubusercontent.com/19390317/114274753-9db22800-9a28-11eb-9484-0e1dd0090b49.png">

4. Remove one chunk cache (see screen below), that can be removed from browser
5. close page
6. new release + restart server
7. reopen url (update available you will see, but not update)
8. try to open page with deleted chunk
9. ErrorHandler: {"message":"Uncaught (in promise): ChunkLoadError: Loading chunk 20 failed.

## 🔥 Exception or Error
<pre><code>

ErrorHandler: {"message":"Uncaught (in promise): ChunkLoadError: Loading chunk 20 failed.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

11.2.9
</code></pre>

**Anything else relevant?**

I tested in Chrome with angular-http-server

**Comment by gkalpak** [comment]
Thx for reporting this, @expcapitaldev. Unfortunately, the provided instructions are not sufficient to reproduce the problem (or at least I wasn't able to 🤷‍♂️). Please open a new issue providing a minimal reproduction (for example, a repo we can check out and build to see the problem in action).
