### ISSUE TITLE
HashBangs not supported in the angular 2 router

### ISSUE THREAD

**Issue by fuzing** [angular/angular#4155]
The HashLocationStrategy supports hash fragments of the form '#<location>' but there appears to be no mechanism to change the prefix to '#!' (to support Google's AJAX crawl spec [https://developers.google.com/webmasters/ajax-crawling/docs/specification]).

**Comment by ericmartinezr** [comment]
@fuzing I think you can do `bind(APP_BASE_HREF).toValue('#!')`

**Comment by fuzing** [comment]
Great - I'll try that and let you know!

Cheers,

Peter B.

**Comment by fuzing** [comment]
bind(APP_BASE_HREF).toValue('!') -   i.e. without the '#' worked great - thank you!

**Comment by ericmartinezr** [comment]
Glad it worked

I think that if you use `PathLocationStrategy` (former HTML5LocationStrategy) you should use `#!`. And if you are using `HashLocationStrategy` just add the `!`.

**Comment by fuzing** [comment]
Greatly appreciate your help.  Didn't expect a response today, so an extra
thank you!!

**Comment by ypaliwal** [comment]
I'm trying to figure out where exactly to use this "bind" function. I'm using angular-cli. Anyone know where exactly it needs to be added?

**Comment by ericmartinezr** [comment]
@ypaliwal that example is reaaaallly old. You can look at the new syntax in the docs for [APP_BASE_HREF](https://angular.io/docs/ts/latest/api/common/index/APP_BASE_HREF-let.html).
