### ISSUE TITLE
ViewEncapsulation.ShadowDom

### ISSUE THREAD

**Issue by simmy12** [angular/angular#41564]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by simmy12** [comment]
When the selector name of a component in Angular is name with one word like 'son' or 'app' I get the error in console
ERROR DOMException: Failed to execute 'attachShadow' on 'Element': This element does not support attachShadow
When changing selector to two word like 'my-son' or 'app-a' then the error is gone.

**Comment by geromegrignon** [comment]
I advice you to edit the first message to fill it with the content of the second one : it'll be easier for the maintainers to go through your issue rather than reading an empty template they provide.

**Comment by geromegrignon** [comment]
About your issue, Angular advices to use a prefix to avoid conflicts with native html tags (even if 'son' and 'app' aren't existing html tags)

**Comment by petebacondarwin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#submit-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
