### ISSUE TITLE
using a dynamic outerHTML attribute somewhere in component template break tests

### ISSUE THREAD

**Issue by kkoo95** [angular/angular#41576]
# 🐞 bug report

### Affected Package
tested with angular 11.2 and karma 6.3.2

### Is this a regression?
I think so yes. Never saw this error with ng9 + ivy and karma 5

### Description
As soon as a component property (string) is bound to an [outerHtml] dynamic attribute somewhere in its template, and is not empty, tests fail with the following error:

```console
NoModificationAllowedError: Failed to set the 'outerHTML' property on 'Element': This element has no parent node.
```
<pre><code>error properties: Object({ code: 7, INDEX_SIZE_ERR: 1, DOMSTRING_SIZE_ERR: 2, HIERARCHY_REQUEST_ERR: 3, WRONG_DOCUMENT_ERR: 4, INVALID_CHARACTER_ERR: 5, NO_DATA_ALLOWED_ERR: 6, NO_MODIFICATION_ALLOWED_ERR: 7, NOT_FOUND_ERR: 8, NOT_SUPPORTED_ERR: 9, INUSE_ATTRIBUTE_ERR: 10, INVALID_STATE_ERR: 11, SYNTAX_ERR: 12, INVALID_MODIFICATION_ERR: 13, NAMESPACE_ERR: 14, INVALID_ACCESS_ERR: 15, VALIDATION_ERR: 16, TYPE_MISMATCH_ERR: 17, SECURITY_ERR: 18, NETWORK_ERR: 19, ABORT_ERR: 20, URL_MISMATCH_ERR: 21, QUOTA_EXCEEDED_ERR: 22, TIMEOUT_ERR: 23, INVALID_NODE_TYPE_ERR: 24, DATA_CLONE_ERR: 25 })
Error: Failed to set the 'outerHTML' property on 'Element': This element has no parent node.
    at DefaultDomRenderer2.setProperty (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/platform-browser/__ivy_ngcc__/fesm2015/platform-browser.js:761:1)
    at elementPropertyInternal (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9974:1)
    at ɵɵproperty (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:14684:1)
</pre></code>

## 🔬 Minimal Reproduction
just generate an new angular 11 workspace with one library (named 'lib') and change the generated component to:
```ts
@Component({
  selector: 'lib-lib',
  template: `
    <p [outerHTML]="html">
      lib works!
    </p>
  `
})
export class LibComponent {
  @Input() html: string;
}
```
change the generated test case to:
```ts
  it('should create', () => {
    expect(component).toBeTruthy();
    let content = (<HTMLElement>fixture.nativeElement).textContent;
    expect(content).not.toContain('test', 'not set yet');

    component.html = 'test';
    fixture.detectChanges(); // break somewhere in here
    content = (<HTMLElement>fixture.nativeElement).textContent;
    expect(content).toContain('test', 'html var should take over template');
  });
```
running `ng test` will fail as indicated before second assertion

## 🌍  Your Environment
**Angular Version:**
<pre><code>Angular CLI: 11.2.6
Node: 12.16.1
OS: win32 x64

Angular: 11.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.6
@angular-devkit/build-angular   0.1102.6
@angular-devkit/core            11.2.6
@angular-devkit/schematics      11.2.6
@angular/cli                    11.2.6
@schematics/angular             11.2.6
@schematics/update              0.1102.6
ng-packagr                      11.2.4
rxjs                            6.6.7
typescript                      4.0.7
</code></pre>

**Comment by jelbourn** [comment]
Angular doesn't support binding to `outerHTML` like this because `outerHTML` replaces the element upon which it is set.
