### ISSUE TITLE
alpha-37: default pipes are missing in angualr2.d.ts

### ISSUE THREAD

**Issue by todoubaba** [angular/angular#4158]

**Comment by pkozlowski-opensource** [comment]
@todoubaba could you please elaborate? What is exactly missing? How are you getting `angualr2.d.ts` (npm or definitively typed)?

**Comment by todoubaba** [comment]
The angular2.d.ts is from `npm install`.

**Comment by todoubaba** [comment]
They are also not found in [definitively typed](https://github.com/borisyankov/DefinitelyTyped/blob/master/angular2/angular2.d.ts)

**Comment by erictsangx** [comment]
I am using alpha-40 and I can import default pipes without a problem (found in jspm and tsd), is this solved?

**Comment by mhevery** [comment]
obsolete
