### ISSUE TITLE
Better error message for misplaced NgSwitchDefault

### ISSUE THREAD

**Issue by jrsun** [angular/angular#41591]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/common.

### Is this a regression?

No.

### Description

This is a request for clearer error messaging. When an NgSwitchDefault directive erroneously exists outside of a NgSwitch, the error message appears to be import-related, rather than a syntax error: `No provider for NgSwitch found in NodeInjector...`

## 🔬 Minimal Reproduction

1) https://stackblitz.com/edit/angular-ivy-zexnwp?file=src/app/app.component.ts
2) See console for error.

## 🔥 Exception or Error
<pre><code>

ERROR Error: NG0201: No provider for NgSwitch found in NodeInjector
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

any
</code></pre>

**Anything else relevant?**

**Comment by stefanoww** [comment]
I can take it. Some proposal for descriptive error message?

**Comment by jelbourn** [comment]
It would be something like "NgSwitchDefault must be inside NgSwitch". The error should also only be reported in dev mode

**Comment by petebacondarwin** [comment]
I imagine that this will have to be achieved by making the injection optional and then checking the argument for `null` in the constructor? This will add a small amount to the size of applications built with common. Any better ideas?

**Comment by AndrewKushnir** [comment]
> This will add a small amount to the size of applications built with common. Any better ideas?

We can also wrap it in `if (ngDevMode) { ... }` ([example](https://github.com/angular/angular/blob/master/packages/core/src/application_ref.ts#L738-L742)) to tree-shake away extra code (the check itself + the error message) in prod bundles.

**Comment by AndrewKushnir** [comment]
Btw, I think it'd be worth adding the same check into the `NgSwitchCase` directive as well (in addition to the `NgSwitchDefault` one).

**Comment by stefanoww** [comment]
I am really egear to help with that, but for sure I will need your help. Current error as I well figuret out is quite generic and is throw by the `throwProviderNotFoundError` method. Does your proposal is to make the `NgSwitch` optional in `NgSwitchDefault` and check in the constructor wheter it's exist and if not throw an custom error in dev mode?

**Comment by petebacondarwin** [comment]
> I am really egear to help with that, but for sure I will need your help. Current error as I well figuret out is quite generic and is throw by the `throwProviderNotFoundError` method. Does your proposal is to make the `NgSwitch` optional in `NgSwitchDefault` and check in the constructor wheter it's exist and if not throw an custom error in dev mode?

Yes - that was my suggestion. I don't know if there would be any better way...?

**Comment by sumitgsh** [comment]
Is this still open..

**Comment by rox117** [comment]
I would like to work on this issue if it is still available

**Comment by petebacondarwin** [comment]
This is currently being worked on at https://github.com/angular/angular/pull/41704

**Comment by JoostK** [comment]
This was addressed in #41704 which landed in the latest patch.
