### ISSUE TITLE
view dehydration

### ISSUE THREAD

**Issue by vicb** [angular/angular#416]
Views are not automatically de-hydrated when removed from a viewport (they are hydrated when created).

`NgRepeat` removes views when:
- items are being removed from the list of items,
- items are being moved in the lists of items.

When items are being moved, there is no need to dehydrate the view as the view will still be present in the end DOM. However when views are being removed, they should be de-hydrated.

`ViewPort.clear()` remove all the attached view. They should probably also be dehydrated there.

**Comment by vsavkin** [comment]
+1

**Comment by rkirov** [comment]
Yep, you are correct, that's a bug and fixing it is a bit tricker because we have to support move correctly.
