### ISSUE TITLE
Added non-passive event listener to a scroll-blocking 'touchstart' event.

### ISSUE THREAD

**Issue by patrickrioux** [angular/angular#41622]
# 🐞 bug report

### Affected Package

 The issue is caused by package zone-evergreen.js

### Is this a regression?

 No.

### Description

 My application is showing the following warning in console.log
zone-evergreen.js:1752 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

## 🔥 Exception or Error
<pre><code>

zone-evergreen.js:1752 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.2
@angular-devkit/build-angular   0.1101.2
@angular-devkit/core            11.2.8
@angular-devkit/schematics      11.2.3
@angular/cdk                    11.2.3
@angular/cli                    11.2.3
@schematics/angular             11.2.3
@schematics/update              0.1102.3
rxjs                            6.6.3
typescript                      4.1.3
webpack                         4.46.0
</code></pre>

**Anything else relevant?**

**Comment by JiaLiPassion** [comment]
There are several ways to support `passive` event listener.

1. Provide your own `EventManager`.
2. Define a global variable like this in the `polyfills.ts` before `importing zone`.

```
(window as any)__zone_symbol__PASSIVE_EVENTS = ['touchstart'];
import 'zone.js/dist/zone';
```

**Comment by patrickrioux** [comment]
I've tried adding this code prior import but it does nothing and still have those warnings.
Still looking for a global solution.

**Comment by JiaLiPassion** [comment]
@patrickrioux , could you provide a reproduce repo?

**Comment by patrickrioux** [comment]
Not really sure how easy this will be. It sounds like zone.js and zone-evergreen.js do not have support for passive events.
There were an issue created with this but was closed due to inactivity.
https://github.com/angular/zone.js/issues/1002

**Comment by ajuanjojjj** [comment]
Happening for me on version "0.11.4". 

Also, a quick search on the node_modules folder for __zone_symbol__PASSIVE_EVENTS seems to show that while it's defined on both zone.d.ts and zone.configurations.api.ts as `__zone_symbol__PASSIVE_EVENTS?: string[];`, it's not actually read anywhere.
