### ISSUE TITLE
[Doc Request] Last updated date on each page

### ISSUE THREAD

**Issue by PingPongSet** [angular/angular#41647]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...
Is it possible to add the last updated date on each page? As this helps tracking the version of each page.

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by petebacondarwin** [comment]
For the time being, it is fair to assume that if the document has no such date then it has not been reviewed for some time and can benefit from a review.

**Comment by jelbourn** [comment]
@aikidave I know this is more of a work-in-progress- is there value in keeping this issue open?

**Comment by aikidave** [comment]
@petebacondarwin is correct: If there isn't a review date, consider it a candidate for review!

@jelbourn I don't think we need to keep this issue open. I'm working on a plan to get the rest of the content reviewed over the next couple of months.

**Comment by PingPongSet** [comment]
> 
> 
> For the time being, it is fair to assume that if the document has no such date then it has not been reviewed for some time and can benefit from a review.

@petebacondarwin 

I do feel there is room for improvement for some of the contents and the sequence of the contents.

**Comment by aikidave** [comment]
@PingPongSet I agree! But we should remember that, when reviewing a topic, our first focus is on whether the content is accurate. Then we can think about: "Is there a better way to explain this information?" (Answer: Always. There's always a better way to explain something. :) )

**Comment by PingPongSet** [comment]
@aikidave 

Angular requires steep learning, that is why the learning resources on this site are so important for beginners to experts.

In addition to better content, some code sample could be simplified. 

Having code sample for each section is huge important as it is currently providing, but code example for some section could be simplified, and explanations for associated code are missing in some cases.

**Comment by aikidave** [comment]
@PingPongSet I agree. I think we've made great progress in making Angular a little easier for developers to understand. We have more work to do, however.

If you have specific ideas regarding a specific topic, feel free to file an issue or a PR! Let me know how I can help!
