### ISSUE TITLE
onChange exists in Alpha37, but not in d.ts

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#4164]
In Alpha 36 we could use `LifecycleEvent.onChange` ... it  still works in 37, but the typings file appears to now list it as `OnChanges`.

`error TS2339: Property 'onChange' does not exist on type 'typeof LifecycleEvent'.`

**Comment by vicb** [comment]
The enum members have been renamed in https://github.com/angular/angular/commit/551d9a16882d144d62e38161670a1a1c9a0c4db9

Also see https://github.com/angular/angular/blob/effbb54f3d4b4925c564cefcb998bcb310037c7b/CHANGELOG.md#lifecycle

**Comment by ericmartinezr** [comment]
@johnpapa in alpha 37 de LifecycleEvent was removed, now yo must import every lifecycle hook like `import {OnChanges} from ...}` and then implement ir like `class X implements OnChanges { onChanges() {} }`

Ps : sorry for the messy example, I'm on the phone.

**Comment by ericmartinezr** [comment]
Oops, already answered, I'll delet these comments later.

**Comment by johnpapa** [comment]
Ah, missed that change when I was reviewing them today and updating my apps . Thanks. For others who may see this, here is the after condition ...

```
import { Component, View, OnChanges, EventEmitter } from 'angular2/angular2';
import {FORM_DIRECTIVES} from 'angular2/angular2';

@Component({
  selector: 'filter-text',
  events: ['changed'],
  properties: ['text']
})
@View({
  template: ` html goes here  `,
  directives: [FORM_DIRECTIVES]
})
export class FilterTextComponent implements OnChanges {
  onChanges(changes: any) {
    console.log(changes);
  }

  // ... more code here
}
```
