### ISSUE TITLE
no-filterpipe-or-orderbypipe appendix missing

### ISSUE THREAD

**Issue by ajuanjojjj** [angular/angular#41652]
# 📚 Docs or angular.io bug report

### Description

At some point between 2020/05/07 and 2020/09/23, the page https://angular.io/guide/pipes was updated to remove the no-filterpipe-or-orderbypipe appendix.  

While is true that in AngularJS (v1) there was a filter pipe and it was necessary to explain why there wasn't one in Angular v2, it's still possible to use pipes to filter arrays, and all the links to why this is "definitely discouraged" (Just one search on stackoverflow for "angular filter pipe" reveals a lot of them) are now pointing to a documentation that doesnt even mention filter pipes at all, which might lead to believe that this might be no longer discouraged.

It'd be a good idea to recover this section, even if it's no longer as important as it was back then, if only to avoid confusion on whether it still is discouraged

**Comment by gkalpak** [comment]
As a (temporary?) work-around, these links can be updated to https://v9.angular.io/guide/pipes#appendix-no-filterpipe-or-orderbypipe.

**Comment by ajuanjojjj** [comment]
Idk if linking to an archived old documentation would do more good though, since it almost further implies that using pipes to filter _was_ discouraged :/

**Comment by aikidave** [comment]
This raises an interesting question: Do we document what people should *not* do when building their applications? I'm not sure that's a good idea. There are many things one could do with any library, platform, or framework that are not good ideas. In general, I've found it to be a better practice to focus on what developers *should* do, and not what they should not do.

What might make more sense is to create content that describes how to filter arrays--if in fact that's something that is unique to Angular. Thoughts?

**Comment by ajuanjojjj** [comment]
Haven't said that we should document what not to do, but to maintain the docs already present (Although I can also see the point of removing it). 

As for the suggestion to create something that explains how to properly do it; Personally I ran into all the broken links trying to find info about filtering an array, so if there was a guide on how to do it I wouldn't have found myself in that situation, so it's a +1 from me

**Comment by ydmitry** [comment]
Was removed in this PR: https://github.com/angular/angular/pull/36820 . Didn't find comments regarding this
