### ISSUE TITLE
router.d.ts in Angular2 Alpha 37 is different from the one in DefinatelyTyped

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#4165]

**Comment by btford** [comment]
@johnpapa why not just use the d.ts file that comes with the published bundle?

@mprobst @alexeagle Do either of you know why this is? Is DefinitelyTyped behind? Do we have control over what appears in there?

**Comment by johnpapa** [comment]
Hi @btford ... let me explain my scenario ...

I use `tsd` to install the typings for everything. Now, I can change this moving forward, but follow me for this story first. tsd looks at the `tsd.json` file. TypeScript looks for a `tsconfig.json` file's location as the root of the TypeScript project. If these are at the root, then everything is used ... and I would have to exclude folders like node_modules, jspm, etc. Also the root is often not the best place as we generally keep source code deeper down in at least one folder like `/src/`. And if I have server code and client code in the project (angular code and node express server), then I may have this structure:

```
src/
    client/
        typings/
        tsd.json
        tsconfig.json
    server/
        typings/
        tsd.json
        tsconfig.json
```

So now I have a different setup for each because I want t use some typings for node and different ones for angular and client code. I also may want the settings on the tsconfig to be different, for different targets, whatever.

Now we have this setup tsd.json allows for the target of its typings folders to be set. SO I can tell each tsd.json where to put its typings.

Enter `npm install angular2` ... which bundles typings with it (which I think is fantastic). However it puts the typings folder in the root. OK, so now I have typings at the root ... and when I compile TypeScript, TS sees the root of the TS project is where the tsconfig.json is and it cannot go up a few levels to see the root's typings folder.

This problem happens even with a single folder like this

```
src/
        typings/
        tsd.json
        tsconfig.json
```

The solution I'd love to see is for a way to have the typings that angular brings, be installed to a configurable location.

**Comment by btford** [comment]
Ah, gotcha. That's pretty painful.

@IgorMinar – is this something Angular CLI can help us with?

**Comment by alexeagle** [comment]
Sorry, I'm having trouble following the issue - I don't understand "it puts the typings folder in the root" - if you npm install angular2 then you get `node_modules/angular2/bundles/typings` right?

We just chatted with the typescript team, and it looks like we'll have a much more usable story for using the typings shipped via NPM starting with TS 1.6, maybe as early as this week.

**Comment by alexeagle** [comment]
Oh and I am working on this in https://github.com/angular/angular/issues/3082

**Comment by btford** [comment]
@alexeagle @johnpapa is it alright to close this as a duplicate then? Sounds like this is a specific symptom of the problem in #3082.

**Comment by alexeagle** [comment]
Well the issue title is that we have two files which ought to be identical
but are not. Maybe this issue has got off on a tangent, and we should
investigate that?

**Comment by johnpapa** [comment]
@alexeagle `npm install` does put it there, but `npm install` also gives a `/typings/tsd.d.ts` file that has references to those 3 files. I then have to copy and paste those references to my `tsd.d.ts` file due to folder structures all being different.

If I had the choice where to put it, it would be easier and more flexible.

**Comment by johnpapa** [comment]
I'd like to keep this linked at least.

If we could NOT use Def Typed, that would be fine ... but then wouldnt we still need it for non angular stuff? I think thats a very realistic scenario.

**Comment by alexeagle** [comment]
I just verified that https://raw.githubusercontent.com/borisyankov/DefinitelyTyped/master/angular2/router-2.0.0-alpha.37.d.ts is identical to `bundles/typings/angular2/router.d.ts` from the alpha.37 npm package.

Let's have a separate issue for how the files get laid out by npm. (@johnpapa and I are discussing on slack)
