### ISSUE TITLE
not found template variable on `ng-content`

### ISSUE THREAD

**Issue by AlexElin** [angular/angular#41658]
# 🐞 bug report

### Description

When specifying a [template variable](https://angular.io/guide/template-reference-variables) on `<ng-content>` and using it the compiler prints an error.  
Maybe it's as designed behavior. In such case I think it should be mentioned in the [template variable docs](https://angular.io/guide/template-reference-variables)

## 🔬 Minimal Reproduction
```
<ng-content #content></ng-content>
<span *ngIf="content.hasChildNodes()">Default</span>
```

## 🔥 Exception or Error
```
Error: src/app/widget/output/output.component.html:10:20 - error TS2339: Property 'content' does not exist on type ....

       <span *ngIf="content.hasChildNodes()">Default</span>
```

## 🌍  Your Environment

**Angular Version:**
v11.2.0

**Comment by iRealNirmal** [comment]
@AlexElin is it possible to provide minimal reproduction code via  stackblitz or other way.

**Comment by petebacondarwin** [comment]
https://stackblitz.com/edit/angular-ivy-lcopfv?file=src%2Fapp%2Fapp.component.html

**Comment by jessicajaniuk** [comment]
This is working as intended. `<ng-content>` is a compiler primative that works as a placeholder for your content and is not a real element. The request to add this information to the docs has been noted on PR #41143.
