### ISSUE TITLE
No error message if redirect at page load goes to nowhere

### ISSUE THREAD

**Issue by Ablu** [angular/angular#4166]
This is a followup of #3979.

@btford's fix apparently only checks for non-terminal routes referenced from a link object.

If my main component I have this config:
~~~ ts
  { path: '/', redirectTo: './grid' },
  { path: './grid/...', component: Grid, as: 'grid' },
~~~

and in my grid component:
~~~ ts
  { path: './:id', component: Dialog },
~~~

I get no exception at the page load, but also no working redirect.

With my limited code knowledge I tried to debug this.
It looks like the code runs through https://github.com/angular/angular/blob/master/modules/angular2/src/router/route_registry.ts#L151 and from that point on simply returns `null` up to the `navigateByUrl` function of the RootRouter called here: https://github.com/angular/angular/blob/master/modules/angular2/src/router./router.ts#L470).

I would love to contribute a plnkr. But I do not see how I can create one which is using the latest git master version of angular.

The same applies for manual router.navigateXXX calls then of course. Though I am not sure how the error messages should be handeled there. In theory those can have a `.catch()` which could handle this, but currently `
    router.navigateByUrl('/grid').catch(() => console.log('error')).then(() => console.log('ok'));` logs `ok` for me... So the error is silently ignored there too.

**Comment by Ablu** [comment]
I uploaded my small messy project in which i tested this: https://docs.google.com/uc?id=0B8JQlPw3d8dCRTVxVlBTNFVTVzA&export=download

I manually replaced the angular and router.js files in `node_modules/angular2/bundles` with ones I got from `gulp build` which i ran against git revision effbb54f3d4b4925c564cefcb998bcb310037c7b.

**Comment by btford** [comment]
Thanks for the reproduction.

I agree that there needs to be more visibility into an incorrectly configured redirect. What do you think of #4170? This would be a good start to making redirects easier to understand. For instance, we'd be able to assert at config-time that your example case is misconfigured and redirects nowhere.

A nitpick: I don't think rejecting the promise is the right choice from an API perspective. Rejections should be reserved for error cases, not non-matches.

**Comment by Ablu** [comment]
> I agree that there needs to be more visibility into an incorrectly configured redirect. What do you think of #4170? This would be a good start to making redirects easier to understand. For instance, we'd be able to assert at config-time that your example case is misconfigured and redirects nowhere.

I already replied with `+1` there :)

> A nitpick: I don't think rejecting the promise is the right choice from an API perspective. Rejections should be reserved for error cases, not non-matches.

I would not have expected this to result in a .catch() only since it would supress any error messages for the initial page redirection. But I checked what the Promise returned anyway just to be sure :)

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router robust.

Could you reproduce the problem using the new router and submit a separate issue?

Closing this issue.
