### ISSUE TITLE
Dart - ViewEncpasulation no longer accepting enums?

### ISSUE THREAD

**Issue by rightisleft** [angular/angular#4169]
In Angular Dart 2 Alpha 35 the @view component accepted an enum value:

    @View(
      styleUrls: const ["package:tickets/client/components/flight_display/flight_display.css"],
      templateUrl: "package:tickets/client/components/flight_display/flight_display.html",
      directives: const[CORE_DIRECTIVES],
      encapsulation: ViewEncapsulation.NONE
    )

The   encapsulation: ViewEncapsulation.NONE now throws the following error:

> Error:(11, 18) Arguments of a constant creation must be constant
> expressions

**Question:**
What is the proffered way to pass the value from an enum to the ViewEncapsulation object in alpha 37? 

**Context**

Here is the Enum for the Angular.Dart 2 Lib:

    enum ViewEncapsulation {
      /**
       * Emulate scoping of styles by preprocessing the style rules
       * and adding additional attributes to elements. This is the default.
       */
      Emulated,
      /**
       * Uses the native mechanism of the renderer. For the DOM this means creating a ShadowRoot.
       */
      Native,
      /**
       * Don't scope the template nor the styles.
       */
      None
    }

**Stackoverflow**
http://stackoverflow.com/questions/32542950/

**Comment by woppa684** [comment]
Isn't the problem here that there's a , missing after const[CORE_DIRECTIVES] ?

**Comment by rightisleft** [comment]
**EDITED** I changed the original code above to reflect to missing comma in the example.

**Comment by woppa684** [comment]
Isn't the problem then that CORE_DIRECTIVES isn't a constant expression? The error seems to point in that direction...

**Comment by zoechi** [comment]
and `ViewEncapsulation.NONE` should be `ViewEncapsulation.None`

**Comment by rightisleft** [comment]
Must have changed between 35 and 37 - thanks

**Comment by zoechi** [comment]
Can you close this issue?
