### ISSUE TITLE
Router RFC: `redirectTo` should use the link DSL rather than a URL fragment

### ISSUE THREAD

**Issue by btford** [angular/angular#4170]
Currently, `redirectTo` in a Redirect route takes a string representing the remaining (unmatched) URL that should be recognized.

```
@RouteConfig([
  { path: '/', redirectTo: '/bar' }, // is "/bar" relative, or absolute?
  // ...
])
class MyClass {}
```

This makes it hard to tell whether the redirection is local, or absolute.

Instead, I propose that we use the route link DSL (same as what the RouterLink directive uses):

```
@RouteConfig([
  { path: '/', redirectTo: ['/bar'] }, // aha! bar is absolute
  // or... { path: '/', redirectTo: ['./bar'] }, // aha! bar is relative
  // ...
])
class MyClass {}
```

Related to #4133, #4166, and https://github.com/angular/angular/issues/3751#issuecomment-136520533

**Comment by Ablu** [comment]
+1 I think that makes it a lot clearer to use.

**Comment by johnpapa** [comment]
I like that.

But help me understand this ... We have a route like this

```
import {HeroesComponent} from './heroes-component';
import {HeroDetailComponent} from './hero-detail-component';
import {DashboardComponent} from './dashboard-component';

export var Routes = {
	dashboard: {
		path: '/',
		as: 'dashboard',
		component: DashboardComponent
	},
	heroes: {
		path: '/heroes',
		as: 'heroes',
		component: HeroesComponent
	},
	detail: {
		path: '/detail/:id',
		as: 'detail',
		component: HeroDetailComponent
	}
};

export const APP_ROUTES = [this.Routes.dashboard, this.Routes.detail, this.Routes.heroes];
```

Now, if I `redirectTo` am I redirecting to the `url` or to the `as`? It sounds like I am redirecting to the `as` (the name).

Is that correct?

**Comment by btford** [comment]
Yes.

With #4083, this'll be even easier to see.

**Comment by johnpapa** [comment]
cool. Cuz ideally I'd liked to have `/` and another name like `/dashboard` go to the same place. And using the name makes that possible while using the url makes it harder.

**Comment by IgorMinar** [comment]
not critical for a39/g3 sync, bumping

**Comment by matsko** [comment]
I'm working on this one.

**Comment by rosendi** [comment]
@btford could you please explain me why `name` option isn't available with the `redirectTo` option at the same time? 

Lets say I have a "hub" route definition called `Home` that currently redirects to another route. I use `Home` route in many places such as redirection after login/logout, redirection after a deleting a model, etc. Later I would implement a home component. To use my new home component all I have to do is just to change `redirectTo` to `component: Home`.

@btford could we file a separate issue with a todo list that includes trending router issues?
