### ISSUE TITLE
ag-grid pagination is broken after migration from angular version 4 to version 10

### ISSUE THREAD

**Issue by CathrineAnupriya** [angular/angular#41701]
paginationGetPageSize() method of ag-grid stopped accepting arguments to the method and we were forced to removed the argument of which broke the pagination. Pagination is now unstable. Do we have an alternative method for paginationGetPageSize() which accepts the arguments and does the same work as this method does.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

This question sounds specific to ag-grid, so please check their documentation or Github issues.
