### ISSUE TITLE
Angular linker fails with literal expression in component template

### ISSUE THREAD

**Issue by klemenoslaj** [angular/angular#41703]
# 🐞 bug report

### Is this a regression?

No

### Description

With the latest versions of Angular CLI and Angular

## 🔬 Minimal Reproduction

Clone: https://github.com/klemenoslaj/angular-linker-fail-template-literal-expression
Execute: `yarn install`
Execute: `ng build library --prod && ng build`

## 🔥 Exception or Error
<pre><code>
Error: ./dist/library/fesm2015/library.js
Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string '/path-from-root/angular-linker-fail-template-literal-expression/dist/library/fesm2015/library.js: Errors found in the template:
Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.) ("0", type: LibraryComponent, selector: "lib-library", ngImport: i0, template: ` ${"Foo" /* First */} [ERROR ->]`, isInline: true, changeDetection: i0.ChangeDetectionStrategy.OnPush, encapsulation: i0.ViewEncapsul"): /path-from-root/angular-linker-fail-template-literal-expression/dist/library/fesm2015/library.js@6:166
Invalid ICU message. Missing '}'. ("0", type: LibraryComponent, selector: "lib-library", ngImport: i0, template: ` ${"Foo" /* First */} [ERROR ->]`, isInline: true, changeDetection: i0.ChangeDetectionStrategy.OnPush, encapsulation: i0.ViewEncapsul"): /path-from-root/angular-linker-fail-template-literal-expression/dist/library/fesm2015/library.js@6:166
   5 | }
   6 | LibraryComponent.ɵfac = function LibraryComponent_Factory(t) { return new (t || LibraryComponent)(); };
>  7 | LibraryComponent.ɵcmp = i0.ɵɵngDeclareComponent({ version: "11.2.10", type: LibraryComponent, selector: "lib-library", ngImport:[39m i0, template: ` ${"Foo" /* First */} `, isInline: true, changeDetection: i0.ChangeDetectionStrategy.OnPush, encapsulation: i0.ViewEncapsulation.None });
     |                                                                                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^
   8 | (function () { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassMetadata(LibraryComponent, [{
   9 |         type: Component,
  10 |         args: [{'
    at run (/path-from-root/angular-linker-fail-template-literal-expression/node_modules/@babel/core/lib/transformation/index.js:39:15)
    at run.next (<anonymous>)
    at Function.transform (/path-from-root/angular-linker-fail-template-literal-expression/node_modules/@babel/core/lib/transform.js:27:41)
    at transform.next (<anonymous>)
    at step (/path-from-root/angular-linker-fail-template-literal-expression/node_modules/gensync/index.js:261:32)
    at /path-from-root/angular-linker-fail-template-literal-expression/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/path-from-root/angular-linker-fail-template-literal-expression/node_modules/gensync/index.js:223:11)
 @ ./src/app/app.module.ts 2:0-58 7:68-84 8:65-78 9:126-139
 @ ./src/main.ts
 @ multi ./src/main.ts
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.9
Node: 14.15.0
OS: darwin x64

Angular: 11.2.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.9
@angular-devkit/build-angular   0.1102.9
@angular-devkit/core            11.2.9
@angular-devkit/schematics      11.2.9
@angular/cli                    11.2.9
@schematics/angular             11.2.9
@schematics/update              0.1102.9
ng-packagr                      11.2.4
rxjs                            6.6.7
typescript                      4.0.7
</code></pre>

**Comment by petebacondarwin** [comment]
The template that is failing is:

```ts
template: ` ${Values.First} `,
```

where `Values` was defined earlier in the template.

I believe that this has been fixed by https://github.com/angular/angular/pull/41583, which landed on `master` 3 days ago.

**Comment by petebacondarwin** [comment]
I tested that PR against the reproduction repo above and it appears to solve the issue: https://github.com/klemenoslaj/angular-linker-fail-template-literal-expression/pull/1
