### ISSUE TITLE
docs: "How forRoot() works": `providers` in the live example

### ISSUE THREAD

**Issue by AlexElin** [angular/angular#41726]
# 📚 Docs or angular.io bug report

### Description

In the [docs](https://angular.io/guide/singleton-services#how-forroot-works)

> In the [live example](https://stackblitz.com/angular/kopljbedqoee?file=src%2Fapp%2Fapp.module.ts) / download example the root `AppModule` imports the `GreetingModule` and adds the `providers` to the `AppModule` providers

But in the live example I don't see `AppModule` adding  `providers` to itself as it's stated in the docs (root AppModule imports the GreetingModule and _adds the providers to the AppModule providers_.)

Could you clarify what is meant in the docs? And fix it if it will be required.

### What's the affected URL?**
https://angular.io/guide/singleton-services#how-forroot-works
https://stackblitz.com/angular/kopljbedqoee?file=src%2Fapp%2Fapp.module.ts

**Comment by gkalpak** [comment]
What the docs say is that by adding a [ModuleWithProviders][1] object (which is what `GreetingModule.forRoot()` returnes) to an `NgModule`'s `imports` array (here `AppModule`'s), all providers in the `ModuleWithProviders` object will be added to the `NgModule`'s (again, here `AppModule`) providers. 

(Leaving it up to the docs team to decide whether this needs re-wording/clarification.)

[1]: https://angular.io/api/core/ModuleWithProviders

**Comment by jessicajaniuk** [comment]
This sentence means that when you import a module, you are importing all of its providers as well. Closing this because it would be a relatively minor rewording change. Feel free to submit a PR if you have a good suggestion for rewording.
