### ISSUE TITLE
Template errors after angular version update from 8 to 9

### ISSUE THREAD

**Issue by shripadgodse** [angular/angular#41722]
# 🐞 bug report

### Is this a regression?
Yes, disabling ivy engine from tsconfig.json everything works as expected (v9.1.13)

### Description
I am trying to update angular application from version 7 to latest version. For this i am following recommended process i.e. updating application to one bigger version step by step, so till now i was able to update application from version 7 to 8(where application compiles and runs successfully) and followed by version 8 to 9. Since i moved from View Engine to Ivy as rendering engine i am getting template errors for all the templates from application, from which i have attached some of them in a text file below for the reference. I tried running application by disabling Ivy from tsconfig.json file and its running without any problem, but as soon as i enable Ivy it gives template errors all over the application. 
**I updated package.json file for "postinstall": "ngcc" and executed npm install by removing node_modules files**. 

Seems like templates are not able to identify the angular tags though i have imported all the required modules into respective modules.

## 🔥 Exception or Error

382                         <mat-menu #menu="matMenu">
                                             ~~~~~~~

  src/app/layout/components/document/document-search/document-search.component.ts:24:18
    24     templateUrl: 'document-search.component.html',
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component DocumentSearchComponent.
src/app/layout/components/document/document-search/document-search.component.html:456:18 - error NG8004: No pipe found 
with name 'json'.

456         {{ step | json }}
                     ~~~~

  src/app/layout/components/document/document-search/document-search.component.ts:24:18
    24     templateUrl: 'document-search.component.html',
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component DocumentSearchComponent.
src/app/layout/components/report-charts/view-report-charts/view-report-charts.component.html:272:51 - error[90m NG8003: No directive found with exportAs 'matAutocomplete'.

272               <mat-autocomplete #servicePlanAuto="matAutocomplete">
                                                      ~~~~~~~~~~~~~~~

  src/app/layout/components/report-charts/view-report-charts/view-report-charts.component.ts:17:16
    17   templateUrl: './view-report-charts.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ViewReportChartsComponent.
src/app/layout/components/report-charts/data-grid/data-grid.component.html:176:38 - error NG8004: No pipe found with name 'date'.

176                   {{row.updatedDate | date:'MM/dd/yyyy hh:mm a'}} </td>
                                         ~~~~

  src/app/layout/components/report-charts/data-grid/data-grid.component.ts:17:16
    17   templateUrl: './data-grid.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component DataGridComponent.
src/app/layout/components/report-charts/data-grid/data-grid.component.html:235:78 - error NG8004: No pipe found with name 'date'.

235                  <span *ngIf="row.approvedDate != null">{{row.approvedDate | date:'MM/dd/yyyy hh:mm a'}}</span>    
                                                                                 ~~~~

  src/app/layout/components/report-charts/data-grid/data-grid.component.ts:17:16
    17   templateUrl: './data-grid.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component DataGridComponent.
src/app/layout/components/report-charts/charges-grid/charges-grid.component.html:177:38 - error NG8004: No pipe found with name 'date'.

177                   {{row.updatedDate | date:'MM/dd/yyyy hh:mm a'}} </td>
                                         ~~~~

  src/app/layout/components/report-charts/charges-grid/charges-grid.component.ts:18:16
    18   templateUrl: './charges-grid.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ChargesGridComponent.
src/app/layout/components/report-charts/charges-grid/charges-grid.component.html:236:78 - error NG8004: No pipe found with name 'date'.

236                  <span *ngIf="row.approvedDate != null">{{row.approvedDate | date:'MM/dd/yyyy hh:mm a'}}</span>    
                                                                                 ~~~~

  src/app/layout/components/report-charts/charges-grid/charges-grid.component.ts:18:16
    18   templateUrl: './charges-grid.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ChargesGridComponent.
## 🌍  Your Environment

**Angular Version:**
Angular CLI: 9.1.15
Node: 12.13.0
OS: win32 x64

Angular: 9.1.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.15
@angular-devkit/build-angular      0.901.15
@angular-devkit/build-optimizer    0.901.15
@angular-devkit/build-webpack      0.901.15
@angular-devkit/core               9.1.15
@angular-devkit/schematics         9.1.15
@angular/cdk                       9.2.4
@angular/cli                       9.1.15
@angular/flex-layout               11.0.0-beta.33
@angular/material                  9.2.4
@angular/material-moment-adapter   9.2.4
@ngtools/webpack                   9.1.15
@schematics/angular                9.1.15
@schematics/update                 0.901.15
rxjs                               6.6.7
typescript                         3.8.3
webpack                            4.42.0

My package.json 
{
  "name": "fuse",
  "version": "7.1.0",
  "license": "https://themeforest.net/licenses/terms/regular",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.config.json --port 4444 --open",
    "start-hmr": "ng serve --configuration hmr --source-map=false --hmr-warning=false",
    "start-hmr-sourcemaps": "ng serve --configuration hmr --source-map=true --hmr-warning=false",
    "build": "node --max_old_space_size=6144 ./node_modules/@angular/cli/bin/ng build --prod --namedChunks",
    "build-stats": "node --max_old_space_size=6144 ./node_modules/@angular/cli/bin/ng build --prod --namedChunks --stats-json",
    "build-prod": "node --max_old_space_size=6144 ./node_modules/@angular/cli/bin/ng build --prod",
    "build-prod-stats": "node --max_old_space_size=6144 ./node_modules/@angular/cli/bin/ng build --prod --stats-json",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "bundle-report": "webpack-bundle-analyzer dist/stats.json",
    "postinstall": "ngcc"
  },
  "dependencies": {
    "@agm/core": "1.0.0-beta.5",
    "@angular/animations": "9.1.13",
    "@angular/cdk": "9.2.4",
    "@angular/common": "9.1.13",
    "@angular/compiler": "9.1.13",
    "@angular/core": "9.1.13",
    "@angular/flex-layout": "11.0.0-beta.33",
    "@angular/forms": "9.1.13",
    "@angular/material": "9.2.4",
    "@angular/material-moment-adapter": "9.2.4",
    "@angular/platform-browser": "9.1.13",
    "@angular/platform-browser-dynamic": "9.1.13",
    "@angular/router": "9.1.13",
    "@microsoft/signalr": "3.1.7",
    "@ng-bootstrap/ng-bootstrap": "4.2.1",
    "@ng-idle/core": "8.0.0-beta.4",
    "@ng-idle/keepalive": "8.0.0-beta.4",
    "@ngrx/effects": "7.0.0",
    "@ngrx/router-store": "7.0.0",
    "@ngrx/store": "7.0.0",
    "@ngrx/store-devtools": "7.0.0",
    "@ngx-formly/core": "5.1.4",
    "@ngx-formly/material": "5.1.4",
    "@ngx-loading-bar/core": "4.2.0",
    "@ngx-loading-bar/http-client": "4.2.0",
    "@ngx-loading-bar/router": "4.2.0",
    "@ngx-translate/core": "11.0.1",
    "@progress/telerik-angular-report-viewer": "7.19.618",
    "@swimlane/dragula": "3.7.3",
    "@swimlane/ngx-datatable": "14.0.0",
    "@types/crypto-js": "3.1.43",
    "@types/prismjs": "1.9.0",
    "ang-jsoneditor": "1.7.5",
    "angular-calendar": "0.26.4",
    "angular-in-memory-web-api": "0.8.0",
    "angular-svg-icon": "7.2.1",
    "angular2-signaturepad": "2.8.0",
    "angular4-material-table": "0.7.0",
    "chart.js": "2.7.3",
    "classlist.js": "1.1.20150312",
    "core-js": "2.6.2",
    "crypto-js": "3.1.9-1",
    "csvtojson": "2.0.10",
    "d3": "5.7.0",
    "date-fns": "1.30.1",
    "hammerjs": "2.0.8",
    "i": "0.3.6",
    "install": "0.13.0",
    "jquery": "3.5.0",
    "jsoneditor": "5.32.4",
    "lac-mat-tel-input": "2.0.0-alpha.2",
    "libphonenumber-js": "1.7.20",
    "lodash": "4.17.15",
    "luxon": "1.13.2",
    "moment": "2.23.0",
    "moment-timezone": "0.5.33",
    "ng2-currency-mask": "5.3.1",
    "ng2-img-cropper": "0.9.0",
    "ng2-pdfjs-viewer": "5.0.7",
    "ngrx-store-freeze": "0.2.4",
    "ngx-ckeditor": "0.4.0",
    "ngx-color-picker": "7.3.0",
    "ngx-cookie-service": "2.1.0",
    "ngx-daterangepicker-material": "2.1.1",
    "ngx-device-detector": "1.4.5",
    "ngx-file-drop": "10.0.0",
    "ngx-image-cropper": "3.2.1",
    "ngx-mask": "8.0.3",
    "ngx-mat-select-search": "3.2.0",
    "ngx-material-file-input": "2.1.1",
    "ngx-material-timepicker": "3.3.1",
    "ngx-perfect-scrollbar": "8.0.0",
    "ngx-tour-core": "4.1.1",
    "ngx-tour-md-menu": "4.1.1",
    "node-sass": "4.14.1",
    "npm": "6.14.4",
    "perfect-scrollbar": "1.4.0",
    "prismjs": "1.15.0",
    "rxjs": "6.6.7",
    "tslib": "^1.10.0",
    "vanilla-text-mask": "5.1.1",
    "web-animations-js": "^2.3.2",
    "webfontloader": "1.6.28",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.15",
    "@angular/cli": "9.1.15",
    "@angular/compiler-cli": "9.1.13",
    "@angular/language-service": "9.1.13",
    "@angularclass/hmr": "2.1.3",
    "@types/jasmine": "2.8.14",
    "@types/jasminewd2": "2.0.6",
    "@types/lodash": "4.14.119",
    "@types/node": "12.20.10",
    "codelyzer": "^5.1.2",
    "jasmine-core": "2.99.1",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "6.3.2",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage-istanbul-reporter": "2.0.4",
    "karma-jasmine": "1.1.2",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "7.0.0",
    "ts-node": "7.0.1",
    "tslint": "6.1.3",
    "typescript": "3.8.3",
    "webpack-bundle-analyzer": "3.7.0"
  }
}
**Anything else relevant?**

[ErrorsInDetail.txt](https://github.com/angular/angular/files/6343660/ErrorsInDetail.txt)

[angular.json.txt](https://github.com/angular/angular/files/6343676/angular.json.txt)

**Comment by jessicajaniuk** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
