### ISSUE TITLE
Alpha 37 Changes

### ISSUE THREAD

**Issue by TiagoBraga39** [angular/angular#4172]
Hi all!

This is mostly post to help anyone upgrading to Alpha 37.

Alpha 37 Changes I came accross:
1. Http Module imported by 'angular2/http'
2. Http RequestMethods Naming now with capital letter case: RequestMethods.GET -> RequestMethods.Get
3. onChange lifeCycle Event now is onChanges

Best regards,
Tiago Braga

**Comment by ericmdantas** [comment]
@TiagoBraga39 maybe do a PR?

**Comment by webteckie** [comment]
Doesn't the angular team keep a running list of changes between versions?   Seems like something to do, if not.

**Comment by pkozlowski-opensource** [comment]
Yep, normally all those things should be part of the "Breaking changes" in the CHANGELOG: https://github.com/angular/angular/blob/master/CHANGELOG.md#200-alpha37-2015-09-09

@TiagoBraga39 if you believe things are missing from the breaking changes section, please send a PR with an update. Thnx!
