### ISSUE TITLE
Missing forwardRef in Query/ViewQuery should throw

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular#4174]
Consider the following code

```javascript
@Component({selector: 'accordion'})
@View({
  template: `
        <accordion-item></accordion-item>
        <accordion-item></accordion-item>`,
  directives : [forwardRef(() => AccordionItem)]
})
export class Accordion implements OnInit {
    constructor(el: ElementRef, @ViewQuery(AccordionItem) items:QueryList<AccordionItem>) {
          this.items = items;
    }
    onInit() {
         console.log(this.items);
    }
}

@Component({selector: 'accordion-item'})
@View({template: `...`})
export class AccordionItem {}
```

This works, but `items` returns 0 results, which is wierd since there are two children (see plnkr below). The problem here is a missing `forwardRef`.

If you remove `forwardRef` from the `directives` property in `Accordion` you'll get this error message. Pretty useful.

```
Unexpected directive value 'undefined' on the View of component 'Accordion'
```
But if you miss `forwardRef` in `@ViewQuery` instead of an error you'll get 0 results, while it should throw a similar error to the above one.

See [repro](http://plnkr.co/edit/MmRqUP?p=preview), switch between the constructors in `Accordion` class and you'll see that no errors are thrown but the length of the results changes.

PS: The title includes `Query` which I didn't test, but I'm assuming that both works similar.

**Comment by jessegood** [comment]
Agreed. It would be nice if Angular told you when the type is `undefined` inside of `@ViewQuery`.
Also, maybe in the future the TypeScript transpiler will add support for checking before use:
https://github.com/Microsoft/TypeScript/issues/4114

**Comment by PascalPrecht** [comment]
Just mentioning here that `@Query` and `@ViewQuery` are going away in favour of `@ContentChildren` and `@ViewChildren` via https://github.com/angular/angular/pull/4237

Your issue might remain tho.

**Comment by ericmartinezr** [comment]
I'm updating this issue to a38, still reproducible

```typescript
@Component({selector : 'parent'})
@View({
  template : `
  <child></child>
  <child></child>
  `,
  directives: [forwardRef(() => Child)]
})
class Parent implements AfterViewInit {
  
  // Length : 2
  //@ViewChildren(forwardRef(() => Child)) children: QueryList<Child>;
  
  // Length : 0
  @ViewChildren(Child) children: QueryList<Child>;

  afterViewInit() {
    console.log(this.children);
  }
}

@Component({selector : 'child'})
@View({template : 'I\'m a child!'})
class Child {}
```

Repro http://plnkr.co/edit/zWmKMQ
