### ISSUE TITLE
Add pre-defined numerical formats to DatePipe

### ISSUE THREAD

**Issue by twopelu** [angular/angular#41743]
# 🚀 Feature request

### Relevant Package
This feature request is for @angular/common in particular for the DatePipe.

### Description
The available pre-defined formats for DatePipe as per [documentation] supports textual formats (i.e. "June 15, 2015" or "9:03 AM") that show month names or AM/PM times.

For some applications it would be useful to support long numerical formats (i.e. "6/15/2015 09:03.00") and take into account the locale to switch day and month in english and non-english format.

[documentation]: https://angular.io/api/common/DatePipe#pre-defined-format-options

### Describe the solution you'd like
I would suggest adding these pre-defined formats:
- "numerical" = "MM/dd/yyyy HH:mm:ss" (english) and "dd/MM/yyyy HH:mm:ss" (non-english)
- "numericalDate" = "MM/dd/yyyy" (english) and "dd/MM/yyyy" (non-english)
- "numericalTime" = "HH:mm:ss" (both english and non-english)

### Describe alternatives you've considered
At this moment the only supported option is using  a custom format and manually take into account the locale, which requires extra effort and is error-prone.

**Comment by Airblader** [comment]
The entire logic of the pipe is exposed as a function, `formatDate`, so it's also quite easy to make your own pipe with your own presets and call that function.

**Comment by Totati** [comment]
As far as I know these formats are not defined by the Angular Team, they get all these formats for every locale from http://cldr.unicode.org/translation/date-time-1/date-time-patterns. I dare to say they won't include new predefined formats, cause they should figure out all these new formats for all locales. 
Your way to go is like Airblader said.

**Comment by twopelu** [comment]
> As far as I know these formats are not defined by the Angular Team, they get all these formats for every locale from **http://cldr.unicode.org/translation/date-time-1/date-time-patterns**. I dare to say they won't include new predefined formats, cause they should figure out all these new formats for all locales.
> Your way to go is like Airblader said.

I think the formats I'm proposing are part of that specification also (see "Numeric representation" in patters details) and it would be no problem to implement them in Angular based on this and take into account the locale.

I have amended the numerical formats in the description of the feature request to fit in the specification and avoid confusion. 

Many thanks!

**Comment by petebacondarwin** [comment]
Numerical dates are already available via the `shortDate` format.
There are similar `shortTime` and `mediumTime` formats, but these do include the `AM/PM` string at the end.
Also there is the `short` format which is a combination of `shortDate` and `shortTime`.

The "numerical" named formats that you describe above do not appear in the CLDR 37 data. I just downloaded it and found the following:

```
"dateFormats": {
  "full": "EEEE, MMMM d, y G",
  "long": "MMMM d, y G",
  "medium": "MMM d, y G",
  "short": "M/d/y GGGGG"
},
"timeFormats": {
  "full": "h:mm:ss a zzzz",
  "long": "h:mm:ss a z",
  "medium": "h:mm:ss a",
  "short": "h:mm a"
},
"dateTimeFormats": {
  "full": "{1} 'at' {0}",
  "long": "{1} 'at' {0}",
  "medium": "{1}, {0}",
  "short": "{1}, {0}"
}
```

Given that the numerical time that you want does not appear to change between locales, I would propose that you went with something like: 

See https://stackblitz.com/edit/angular-ivy-n4gjcp?file=src%2Fapp%2Fapp.component.html

**Comment by twopelu** [comment]
> Numerical dates are already available via the `shortDate` format.
> There are similar `shortTime` and `mediumTime` formats, but these do include the `AM/PM` string at the end.
> Also there is the `short` format which is a combination of `shortDate` and `shortTime`.
> 
> The "numerical" named formats that you describe above do not appear in the CLDR 37 data. I just downloaded it and found the following:
> 
> ```
> "dateFormats": {
>   "full": "EEEE, MMMM d, y G",
>   "long": "MMMM d, y G",
>   "medium": "MMM d, y G",
>   "short": "M/d/y GGGGG"
> },
> "timeFormats": {
>   "full": "h:mm:ss a zzzz",
>   "long": "h:mm:ss a z",
>   "medium": "h:mm:ss a",
>   "short": "h:mm a"
> },
> "dateTimeFormats": {
>   "full": "{1} 'at' {0}",
>   "long": "{1} 'at' {0}",
>   "medium": "{1}, {0}",
>   "short": "{1}, {0}"
> }
> ```
> 
> Given that the numerical time that you want does not appear to change between locales, I would propose that you went with something like:
> 
> See https://stackblitz.com/edit/angular-ivy-n4gjcp?file=src%2Fapp%2Fapp.component.html

Many thanks for your response and the code example :-)

It is ok and it works fine, but this way I would have to copy-paste everywhere  the "numericalDateTime()" or create a service to reuse it in my code. I will also loose some of the great features of the DatePipe, such as using the pipe, or maybe I could implement a custom pipe myself.

I expected to have such a common numerical dateformat I proposed as a pre-defined option in Angular :-(

**Comment by petebacondarwin** [comment]
It is easy enough to compose this in your template using pipes too: https://stackblitz.com/edit/angular-ivy-wkt1xj?file=src%2Fapp%2Fapp.component.html

```
{{now | date : 'shortDate'}} {{ now | date : 'HH:mm:ss' }}
```

Or you could indeed create your own pipe.

**Comment by twopelu** [comment]
> Or you could indeed create your own pipe.

Thanks again, I will probably go with the custom pipe, to make it right :-)
