### ISSUE TITLE
Upgrade component's scope is not available to subclasses

### ISSUE THREAD

**Issue by smdunn809** [angular/angular#41756]
# 🐞 bug report

### Affected Package

@angular/upgrade

### Is this a regression?

No

### Description

When extending UpgradeComponent, it creates a new scope for the upgraded component. In my case, I need to be able to access this scope to ensure any other controllers or components I create are created using this new scope. 

## 🔬 Minimal Reproduction

```ts
export class ExtensionClass extends UpgradeComponent {
  constructor(elementRef: ElementRef, injector: Injector) {
    super(COMPONENT_NAME, elementRef, injector);

    // Currently, we can't access this component scope because its private. If it was a protected field this line would work.
    this.scope = this.$componentScope;
  }
}
```

**Comment by petebacondarwin** [comment]
@smdunn809 - could you please provide a concrete use-case for needing to access this scope? It is not clear to us why you would need to do this from the Angular side.

**Comment by smdunn809** [comment]
Here is my example use case (simplified a bit):

1) Define an angularJS component wrapper for a view and controller. 
2) Use UpgradeComponent to create a wrapper directive for the angularJS component:

@Directive({
  selector: 'legacy-upgraded-component',
})
export class LegacyUpgradedComponent extends UpgradeComponent {
  >> In super class UpgradeComponent defines this component in an angularJS scope

  >> Here we need the scope so this controller's scope is created in the correct scope. If we can just access super class component scope this becomes easy:
  this.ctrl = $controller(this.ctrlType, {
      $scope: this.$componentScope,
    ...
    });
  }
}

**Comment by petebacondarwin** [comment]
Where is `this.ctrlType` coming from? Normally, the AngularJS component would provide this, and then `UpdateComponent` will do this work for you. See https://github.com/angular/angular/blob/4456e7e4dec87f237cee0ed2eb6eb4431e806ea5/packages/upgrade/static/src/upgrade_component.ts#L133-L141

**Comment by smdunn809** [comment]
Theoretically we could use the built in "buildController", but there are some ng2 services that we downgraded that we want to use rather than the angular injected versions of those services. 

For background, this is for an angular router migration project, where we're upgrading our pages and hooking them up to the new router and then we will get rid of our angularJS router entirely. This requires providing any angular router dependent services from the angular code to the angularJS code. Here's an example:

  this.ctrl = $controller(this.getCtrlType(), {
      $routeParams: {...this.activatedRoute.snapshot.params},
      // Needs to be scope from $componentScope in upgrade component
      $scope,
      url: this.url,
      appPath: this.appPath,
    });

These other services (routeParams, url, appPath) are missing if I directly create the controller via upgradecomponent. 

Is there a workaround for providing these other services directly to the controller?

**Comment by petebacondarwin** [comment]
How do you pass `activatedRoute`, `url` and `appPath` to your `UpgradeComponent` class?

If these are services that you downgraded, then they ought to be available on the `$injector`, which would mean that the AngularJS directive could inject them directly into its controller. There should be no need to create the controller manually.

I feel like I am still missing some piece of the puzzle here.
