### ISSUE TITLE
ES5 Step By Step Yields a Blank Screen in Browser

### ISSUE THREAD

**Issue by knicholes** [angular/angular#4176]
Using Chrome 45.0.2454.85 (64-bit) or Firefox 40.0.3 and OSX 10.10.3, I follow the first steps at
https://angular.io/docs/js/latest/guide/gettingStarted.html "Angular 2 for Javascript"

I create my index.html and copy/paste the provided text from the guide.
I create my app.js and copy/paste the provided text from the guide.
I start my python SimpleHTTPServer on port 8000.
I hit localhost:8000 and see three requests in my Network tab:
    - localhost (containing my html)
    - angular2.sfx.dev.js
    - app.js

I look at my browser's display and see a blank screen.  There are no console errors.  Inspecting the response from "localhost" I see my html with the "<my-app>" tags.

I expected to see that HTML tag's contents either populated or replaced with the template declared in my AppComponent's View's template value.

**Comment by brandonroberts** [comment]
Its missing a bootstrap at the bottom of the app.js

     ng.bootstrap(AppComponent);

And the index.html should look something like

  ```
<!DOCTYPE html>
<html>
  <head>
    <script src="https://code.angularjs.org/2.0.0-alpha.34/angular2.sfx.dev.js"></script>
  </head>
  <body>
    <my-app></my-app>
    <script src="app.js"></script>
  </body>
</html>
```

Once you make those changes, you should see the component

Hope this helps

**Comment by knicholes** [comment]
@brandonroberts Yes, that's what's wrong, but the guide still fails to include that.  I think if Angular2 wants developers to preview their code, they ought to make sure the getting started guide works as described.

**Comment by brandonroberts** [comment]
:+1:

**Comment by albertosantini** [comment]
I would close this issue.

PR ready in `angular.io` repo: https://github.com/angular/angular.io/pull/226.

**Comment by brandonroberts** [comment]
The quick start guide has been deprecated. See https://github.com/angular/angular.io/pull/207

**Comment by albertosantini** [comment]
Thanks for the notice.
