### ISSUE TITLE
getNumberOfCurrencyDigits IQD value

### ISSUE THREAD

**Issue by Pattsu** [angular/angular#41779]
# 🐞 bug report

### Affected Package
https://github.com/angular/angular/blob/a92a89b0eb127a59d7e071502b5850e57618ec2d/packages/common/src/i18n/currencies.ts#L69

### Description
May I ask someone for a small value change? :)

IQD is the Iraqi dinar value and is subdivided into 1,000 fils.

https://en.wikipedia.org/wiki/Iraqi_dinar

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-n5nxat?file=src/app/app.component.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.2.3
Node: 12.14.1
OS: darwin x64

Angular: 10.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.5
@angular-devkit/build-angular   0.1002.3
@angular-devkit/core            11.2.5
@angular-devkit/schematics      10.2.3
@angular/cdk                    10.2.7
@angular/cli                    10.2.3
@angular/material               10.2.7
@schematics/angular             10.2.3
@schematics/update              0.1002.3
rxjs                            6.6.6
typescript                      4.0.7
</code></pre>

**Comment by PabloPeinado15** [comment]
I think the way to proceed is to make a pull request by changing the third value in the array to 3. I don't know if there is anything wrong with that.

**Comment by petebacondarwin** [comment]
As indicated at the top of the file that was mentioned in this issue:

```
// THIS CODE IS GENERATED - DO NOT MODIFY
// See angular/tools/gulp-tasks/cldr/extract.js
We do not accept updates to these files directly. They are generated directly from CLDR data, which is downloaded.
If the CLDR data is incorrect then you should submit an issue there.
(It might be that we need to update to a newer version of CLDR data. See #41778)

Closing as there is no action to take here.
