### ISSUE TITLE
angular is not listening to html5 history.pushState

### ISSUE THREAD

**Issue by shivasai09** [angular/angular#41777]
when i do `history.pushState(null , null, path)` which is outside of my angular app. the URL changes.
but the component associated with it never renders. is this normal. 

how do i make angular to listen changes to html5 history?

https://stackoverflow.com/questions/67224820/how-to-use-html5-history-pushstate-with-angular

**Comment by atscott** [comment]
This is working as intended. Rather than using `history.pushState`, you should use the Router API to perform navigations (`Router.navigate` and `Router.navigateByUrl`)
