### ISSUE TITLE
test-lib module should export `dispatchEvent`

### ISSUE THREAD

**Issue by wardbell** [angular/angular#4177]
As of alpha-37 it is only available through 'angular2/src/test_lib/utils'

Maybe I'm missing a better technique but the way I know to trigger DOM events is through something like  `dispatchEvent`.  For example, I have test code that looks like this:

          // get the HTML element and change its value in the DOM
          var input = rootTC.query(By.css('input')).nativeElement;
          input.value = "Dog Man"
          dispatchEvent(input, 'change'); // event triggers Ng to update model

I think I stole it from one of the Angular core tests.

Alternative (perhaps better?), expose `DOM` so we can do it ourselves (and more) as in:

      DOM.dispatchEvent(input, DOM.createEvent('change'));

**Comment by juliemr** [comment]
Done with a1fa2e472fc50ceecef37e7c5da2ae760a8ad88c

**Comment by IgorMinar** [comment]
dispatchEvent was not meant to be public api. it's an internal helper that leaked.

we should provide a more ergonomic way to trigger events post AngularConnect. in the meantime you can use regular dom apis to create and dispatch events. https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent
