### ISSUE TITLE
Deprecated API in examples for StaticProvider

### ISSUE THREAD

**Issue by destus90** [angular/angular#41783]
# 📚 Docs or angular.io bug report

### Description

For the time being, there are some examples in the docs which are using deprecated API.
From v5 use the new signature `Injector.create(options)` (https://angular.io/api/core/Injector#create)

### What's the affected URL?**
https://angular.io/api/core/ValueProvider#usage-notes
https://angular.io/api/core/ExistingProvider#usage-notes
https://angular.io/api/core/StaticClassProvider#usage-notes
https://angular.io/api/core/ConstructorProvider#usage-notes
https://angular.io/api/core/FactoryProvider#usage-notes

**Comment by AndrewKushnir** [comment]
Closing this issue since the PR #42006 with the necessary changes was merged.
