### ISSUE TITLE
requestAnimationFrame callback arguments not passed in

### ISSUE THREAD

**Issue by adamdbradley** [angular/angular#4179]
In alpha36, a requestAnimationFrame's callback correctly gets the timestamp argument:
http://plnkr.co/edit/6ZkphwlO7hUKpoLrBDJw?p=preview

In alpha37, the rAF callback does not get the timestamp argument:
http://plnkr.co/edit/H9bYRx7gDivc5qxkdVB1?p=preview

This causes javascript animations to fail.

**Comment by mhevery** [comment]
https://github.com/angular/zone.js/issues/187
