### ISSUE TITLE
Improve ApplicationRef.bootstrap function docs

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#41791]
The [ApplicationRef.bootstrap](https://angular.io/api/core/ApplicationRef#bootstrap) docs can be improved by:
- fixing an example code, which doesn't reference the ApplicationRef.bootstrap
- add a new example on how to work with the second argument (the `rootSelectorOrNode` arg)

There are also some places in guides that can benefit from similar updates, see https://github.com/angular/angular/pull/38688#issuecomment-701021968 for additional info.

**Comment by umairhm** [comment]
@AndrewKushnir I can see the PR #38688 was marked closed due to lack of response, so if it is okay, I can try working on it as my first contribution. Is it okay if I assign it to myself?

**Comment by petebacondarwin** [comment]
Thanks @umairhm - I have assigned this issue to you.

**Comment by umairhm** [comment]
Hi @AndrewKushnir & @petebacondarwin, I've submitted a PR for this issue. Please take a look and let me know what needs improvement. I am pretty excited about this being my first ever open-source contribution.

P.S: For the docs, I have used a modified example from [this article](https://medium.com/angular-in-depth/how-to-manually-bootstrap-an-angular-application-9a36ccf86429) by [Max Koretskyi](https://medium.com/@maxkoretskyi) with their permission. Is there a way to refer back to this article somehow?

**Comment by petebacondarwin** [comment]
> P.S: For the docs, I have used a modified example from this article by Max Koretskyi with their permission. Is there a way to refer back to this article somehow?

Probably the simplest way would be to mention it in the commit message.

**Comment by umairhm** [comment]
> > P.S: For the docs, I have used a modified example from this article by Max Koretskyi with their permission. Is there a way to refer back to this article somehow?
> 
> Probably the simplest way would be to mention it in the commit message.

Thanks for the reply, Pete! I will try to include in any future commits, if required, else amend the last commit.

**Comment by umairhm** [comment]
@petebacondarwin & @AndrewKushnir I had to close the previous PR and delete the branch. I've created a PR again for your kind review, please.

**Comment by umairhm** [comment]
Hi @petebacondarwin, I believe we can close this issue as the PR was merged.

**Comment by petebacondarwin** [comment]
Thanks @umairhm
