### ISSUE TITLE
Submit error on searching for NgStyle

### ISSUE THREAD

**Issue by ibellon** [angular/angular#41805]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by ibellon** [comment]
Hi everyone,
I was just searching for NgStyle docs and my browsers, Firefox or Chrome, didn't response.
Thanks. Regards,

**Comment by gkalpak** [comment]
You can find docs on `NgStyle` [here][1] and [there][2]. However, currently, it is preferable to use `style` attribute binding for styling (see [here][3])

[1]: https://angular.io/api/common/NgStyle
[2]: https://angular.io/guide/built-in-directives
[3]: https://angular.io/guide/attribute-binding#binding-to-the-style-attribute
