### ISSUE TITLE
error componente input date  - class ng-invalid  { Solutions Ref  - (badInputChecker() ) }

### ISSUE THREAD

**Issue by mxnho** [angular/angular#4180]
scenario :

I have a input type = "Date" not required in my form linked to an ng - model = "date" , when I add a value to the component and then use the delete key to erase the value , the angular adds ng -invalid class component and adds to the value undefined , making my form invalid.

The solution is the function which adds badInputChecker undefined for the component , the solution would be to add null !

Thus, the only component will be invalid if requirid.

Solutions
-->angular.js
function badInputChecker(scope, element, attr, ctrl) {
  var node = element[0];
  var nativeValidation = ctrl.$$hasNativeValidators = isObject(node.validity);
  if (nativeValidation) {
    ctrl.$parsers.push(function(value) {
      var validity = element.prop(VALIDITY_STATE_PROPERTY) || {};
      // Detect bug in FF35 for input[email] (https://bugzilla.mozilla.org/show_bug.cgi?id=1064430):
      // - also sets validity.badInput (should only be validity.typeMismatch).
      // - see http://www.whatwg.org/specs/web-apps/current-work/multipage/forms.html#e-mail-state-(type=email)
      // - can ignore this case as we can still read out the erroneous email...
       // old - return validity.badInput && !validity.typeMismatch ? undefined: value;    
   
        return validity.badInput && !validity.typeMismatch ? null : value;      <------------------HERE 
 });
  }
}

Best regards

**Comment by PascalPrecht** [comment]
Hi

This is the Angular 2 repository, please file an issue at angular/angular.js and close this one.

Thanks!
