### ISSUE TITLE
For input type=radio, value attribute is missing if the radio button group is rendered inside ngFor 

### ISSUE THREAD

**Issue by shivbijlani** [angular/angular#41808]
# 🐞 bug report

### Affected Package
The issue is likely caused by package @angular/FormGroup

### Is this a regression?
Possibly

### Description

the value attribute is missing from radio button elements - if the radio button is rendered in a for loop

## 🔬 Minimal Reproduction
1. https://stackblitz.com/edit/angular-ivy-cqpukz?file=src/app/app.component.html
2. inspect the radio button. Observe that the "value" attribute is missing, even though `ng-reflect-value` is present and correct

## 🔥 Exception or Error
n/a

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 9.1.4
Node: 14.15.4
OS: win32 ia32

Angular: 9.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.42.0

**Comment by petebacondarwin** [comment]
This is working as designed. In Angular bindings update properties on the DOM nodes not attributes.
If you want to actually change the attribute then you should bind to the attribute using the following syntax.

```html
[attr.value]="actionVM.type"
```

See https://stackblitz.com/edit/angular-ivy-bokmhw?file=src%2Fapp%2Fhello.component.ts
