### ISSUE TITLE
(docs) Incorrect documentation - markForCheck doesn't call scheduleTick

### ISSUE THREAD

**Issue by cozmy** [angular/angular#41810]
The source code docs of `markForCheck` states that:

> "Marks a view and all of its ancestors dirty. It also triggers change detection by calling `scheduleTick` internally, which coalesces multiple `markForCheck` calls to into one change detection run."
Source: https://github.com/angular/angular/blob/a92a89b0eb127a59d7e071502b5850e57618ec2d/packages/core/src/render3/view_ref.ts#L101

But from what I see, this is not the case. 

This means that if we call markForCheck from outside the Zone, ApplicationRef.tick won't be called, thus the change Change Detection won't kick in.

**Comment by atscott** [comment]
You're correct, `markForCheck` does not schedule a change detection on its own. Would you like to open a PR to remove this sentence from the internal documentation?

**Comment by cozmy** [comment]
Just opened a PR: https://github.com/angular/angular/pull/41845

**Comment by cozmy** [comment]
This can be closed as my changes from https://github.com/angular/angular/pull/41845 were merged

**Comment by cozmy** [comment]
It's me again 😄

I feel that i didn't yet fully understood why `markForCheck` doesn't call `scheduleTick` anymore. I found out that it has been removed in this PR: https://github.com/angular/angular/pull/28048

Please see the example below. Without a scheduleTick, although the async pipe called `markForCheck` (https://github.com/angular/angular/blob/master/packages/common/src/pipes/async_pipe.ts#L146), the change won't be reflected in the view without an `applicationRef.tick`

![image](https://user-images.githubusercontent.com/5887290/116536451-9bd3da00-a8ed-11eb-8aa5-16e20b490ae2.png)

https://codesandbox.io/s/markforcheck-doesnt-call-scheduletick-or-applicationreftick-499se?file=/src/app/app.component.ts

**Comment by atscott** [comment]
Closing. The documentation was corrected by #41845 as you mentioned. #28048 fully explains why `scheduleTick` was removed. We may be introducing APIs in the future that both mark for check and schedule a change detection along with our work to make zones optional but for backwards compatibility reasons, `scheduleTick` cannot be added to `markForCheck`
