### ISSUE TITLE
[Angular 12] Node 16.0.0: Creating new angular workspace failed

### ISSUE THREAD

**Issue by prabh-62** [angular/angular#41819]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
N/A

### Description
Angular CLI is unable to create an angular workspace if the runtime is Node 16.0.0

## 🔬 Minimal Reproduction
```shell
❯ npx @angular/cli@12.0.0-rc.0 new web-apps --create-application false
```

## 🔥 Exception or Error
<pre><code>
⠦ Installing packages (yarn)...warning @angular/cli > pacote > @npmcli/run-script > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @angular/cli > pacote > @npmcli/run-script > node-gyp > request > har-validator@5.1.5: this library is no longer supported
error @angular/animations@12.0.0-rc.0: The engine "node" is incompatible with this module. Expected version ">=12.14.1 <16.0.0". Got "16.0.0"
error Found incompatible module.
✖ Package install failed, see above.
The Schematic workflow failed. See above.
</code></pre>
<img width="1395" alt="angular_12_node_16_fail" src="https://user-images.githubusercontent.com/13006107/116123056-83b34f00-a690-11eb-9534-f594dbf2d005.png">

## 🌍 Your Environment
<pre><code>
❯ node --version
v16.0.0
❯ yarn --version
1.22.10
❯ sw_vers
ProductName:	macOS
ProductVersion:	11.2.3
BuildVersion:	20D91
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
//cc @josephperrott, thoughts?

**Comment by josephperrott** [comment]
I have opened https://github.com/angular/angular/pull/41820 to make our supported versions clearer as the understanding of the terms Node.js uses around their versions has solidified.

As noted on Node.js's [Releases page](https://nodejs.org/en/about/releases/), only active LTS and maintenance LTS versions should be used for production applications, and as such they are the only ones that Angular supports. 

Specific to version 16 usage, it will become an LTS version, however it is not slated to become LTS until 2021-10-26.  As @alan-agius4 noted, you should be able to use it while using the `--ignore-engines` flag, though it will not be officially supported by Angular until after it becomes an LTS version.

**Comment by prabh-62** [comment]
<img width="926" alt="angular_12_node_16_fail_ignore_engines" src="https://user-images.githubusercontent.com/13006107/116131232-202e1f00-a69a-11eb-87a4-3e107e01e6a8.png">

```shell
❯ npx @angular/cli@next new web-apps --create-application false --ignore-engines
```

I might not be using `--ignore-engines` flag correctly

**Comment by josephperrott** [comment]
@prabh-62 I believe that to use an unsupported version of node while creating new project, you would need to do the following (using `npx @angular/cli@next` or installing `@angular/cli` and running `ng`):

```
ng new web-apps --create-application false --skip-install;

# After completion of the `ng new` setup
yarn install --ignore-engines
```

This would skip performing the install that is failing and allow you to run the install yourself with the `--ignore-engines` flag.

**Comment by prabh-62** [comment]
Thanks @josephperrott 

I tried your suggestion
```shell
❯ npx @angular/cli@next new web-apps --create-application false --skip-install
❯ cd web-apps && yarn install --ignore-engines
❯ yarn ng generate app admin-console --skip-install # --skip-install again for package `@angular-devkit/build-angular`
❯ yarn install --ignore-engines
```

I recall that angular team decided to throw warnings to stdout instead of erroring out if unsupported Node runtime is found. Has this changed recently?

**Comment by prabh-62** [comment]
Workaround: 
```shell
❯ yarn config set ignore-engines true
```

I am able to workaround all these issues by setting `ignore-engines` flag to true globally

**Comment by alan-agius4** [comment]
@prabh-62, 
> I recall(angular/angular-cli#20050 (comment)) that angular team decided to throw warnings to stdout instead of erroring out if unsupported Node runtime is found. Has this changed recently?

Indeed we display a warning when using an unsupported Node.JS version. In this case however when not using strict engines, the package manager (yarn) will throw an error before the CLI is invoked.
