### ISSUE TITLE
Incorrect version number for next.angular.io and rc.angular.io

### ISSUE THREAD

**Issue by destus90** [angular/angular#41829]
# 📚 Docs or angular.io bug report

### Description

Both of those domains show an incorrect version number on the API page.

### What's the affected URL?**
https://rc.angular.io/api/
https://next.angular.io/api

### Expected vs Actual Behavior**
Expected: v.12
Actual: v.10

## 📷Screenshot
![image](https://user-images.githubusercontent.com/17944366/116191148-42c94200-a745-11eb-90ef-23f3362ce496.png)
![image](https://user-images.githubusercontent.com/17944366/116191194-583e6c00-a745-11eb-8496-cb21d79e0cfe.png)

### Browser info
Chrome v.90

**Comment by petebacondarwin** [comment]
Good spot @destus90 - I'll take a look into why this is happening.

**Comment by petebacondarwin** [comment]
OK so this is because the `git` Dgeni package assumes that tagged versions start with a `v`. See https://github.com/angular/dgeni-packages/blob/master/git/services/getPreviousVersions.js#L22

And it turns out that there is exactly one such tag in the Angular repo: v10.2.5!
