### ISSUE TITLE
Docs: update supported node.js versions

### ISSUE THREAD

**Issue by prabh-62** [angular/angular#41821]
As per [Angular docs](https://angular.io/guide/setup-local), Angular supports current, active LTS, or maintenance LTS version of [Node.js](https://nodejs.org)
<img width="890" alt="node_angular_version_compatibility" src="https://user-images.githubusercontent.com/13006107/100033189-b26a8800-2dc7-11eb-9443-f2089635a66c.png">

And, according to [testing docs](https://angular.io/guide/testing), Karma is the default test runner.

Does this mean tools provided by default in Angular CLI follow same node compatibility? Specifically, Should the default test framework, Karma, support node v15 (current)?

Issues: https://github.com/karma-runner/karma/issues/3570, https://github.com/karma-runner/karma/issues/3571

**Comment by jessicajaniuk** [comment]
This will be fixed by PR #41820.
