### ISSUE TITLE
Spy in test fails in nested templated components

### ISSUE THREAD

**Issue by wnvko** [angular/angular#41836]
# 🐞 bug report

### Affected Package

Not sure, this is tests related issue.

### Is this a regression?
No, I can reproduce this in Angular 11

### Description
I have a templatable component with default template. I am passing a service method in the template container context. In the template I have another templatable container where I am calling passed method. This works fine with default and custom templates. However, when I try to test if the passed in the context method is called in the custom template the test fails with `Expected spy myMethodName to have been called`. When I debug the test I can see the method is called but jasmine's spy somehow miss this.

## 🔬 Minimal Reproduction
[Here](https://github.com/wnvko/teamplateAngular12) is a repo containing a sample. Clone, call `npm i` and then `ng test` to reproduce the issue.

## 🔥 Exception or Error

Here is the test's output:
<pre><code>
        Error: Expected spy logInput to have been called.
            at <Jasmine>
            at UserContext.<anonymous> (src/app/templatable/templatable.component.spec.ts:35:60)
            at ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:372:1)
            at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:287:1)</code></pre>
## 🌍  Your Environment

**Angular Version:**
<pre><code>
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0-rc.0
@angular-devkit/build-angular   12.0.0-rc.0
@angular-devkit/core            12.0.0-rc.0
@angular-devkit/schematics      12.0.0-rc.0
@schematics/angular             12.0.0-rc.0
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Comment by atscott** [comment]
This is working as expected. Here's an example without Angular, attempting to spy on a method that is called through a `bind` indirect: https://stackblitz.com/edit/jasmine-testing-wdye1a?file=src%2Fidentity.spec.ts

**Comment by wnvko** [comment]
yeah I see why this not working. However switching from `bind` to `$impicit` and test still fails. Here is my new template:
```
<ng-container *ngTemplateOutlet="customTemplateContainer; context: { $implicit: logger.logInput}">
</ng-container>

<ng-template #defaultTemplate let-templatedLogMethod>
    <h1>I am the default template</h1>
    <ng-container
        *ngTemplateOutlet="customLoggerTemplate ? customLoggerTemplate : defaultLoggerTemplate; context { $implicit: templatedLogMethod }">
    </ng-container>
</ng-template>

<ng-template #defaultLoggerTemplate>
    <button (click)="logger.logInput('From default template')">This is default logger</button>
</ng-template>
```
@atscott any idea why `jasimne.spy` miss this too?

**Comment by atscott** [comment]
@wnvko That would have the same issue: https://stackblitz.com/edit/jasmine-testing-lxdvb5?file=src%2Fidentity.spec.ts

**Comment by wnvko** [comment]
@atscott So there is no way to pass a method in the template context, and then to test if the method was called. This looks like an oversight from Angular, or I am missing something.
