### ISSUE TITLE
Interpolation does not parse after Angular 11.0.2 Outlook AddIn

### ISSUE THREAD

**Issue by MehyarSawas** [angular/angular#41837]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 11.0.2

### Description

 I am running an angular app in outlook addin with version 11.0.2. After updating angular to version 11.2.10, the interpolation parsing was not working in the whole app. When i downgrade the angular vendor files to 11.0.2 again, the interpolation parsing works agian. The console does not show any errors and the app renders the components properly except for the interpolations.

### Reproduction
Clone and deploy the following angular project and add it in your outlook addin.
Upload the project to a remote server. 
Manifest file should be adjusted to the server where the project is uploaded on. 
https://stackblitz.com/edit/angular-outlook-addin?devtoolsheight=33&file=src/main.ts

**Comment by JoostK** [comment]
Hello, I'm afraid there is insufficient information provided for us to investigate or offer any actionable advice here. Please provide a reproduction.

**Comment by faustus7** [comment]
@MehyarSawas I think the issue you are encountering is related to this https://github.com/OfficeDev/generator-office/issues/601#issuecomment-844042603.

**Comment by petebacondarwin** [comment]
Closing as this is a bug with MS Office - there are a couple of workarounds suggested in the link above.
