### ISSUE TITLE
remove es6-shim from the router angular1 bundle

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#4184]
in e4f94f067847e1dbfcbdd241eb2833a3e8da8e55 I lazy-required the shim to unblock the master from breakages, but we should not bundle the shim with the router at all, instead we should document that the shim is required for the router bundle to work on older browsers.

**Comment by IgorMinar** [comment]
@btford or @shahata can you take a look at this please?

**Comment by btford** [comment]
I have an enormous WIP PR refactoring angular 1 + router code incoming that addresses this.

**Comment by btford** [comment]
Addressed in #4266.
