### ISSUE TITLE
Unable to build on Windows 10

### ISSUE THREAD

**Issue by MrJithil** [angular/angular#41843]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
`scripts/build`, `bazel`

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
While issuing `node ./scripts/build/build-packages-dist.js`, the build getting failed. 

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>
PS D:\OpenSource\angular> node ./scripts/build/build-packages-dist.js >>  buil_error.txt
INFO: Repository npm instantiated at:
  D:/opensource/angular/WORKSPACE:30:13: in <toplevel>
  C:/users/anusername/_bazel_anusername/idexbm2i/external/build_bazel_rules_nodejs/index.bzl:78:18: in yarn_install
Repository rule yarn_install defined at:
  C:/users/anusername/_bazel_anusername/idexbm2i/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:652:31: in <toplevel>
DEBUG: C:/users/anusername/_bazel_anusername/idexbm2i/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:342:14: _
DEBUG: C:/users/anusername/_bazel_anusername/idexbm2i/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:343:14: <unknown object com.google.devtools.build.lib.bazel.repository.starlark.StarlarkExecutionResult>
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
        File "C:/users/anusername/_bazel_anusername/idexbm2i/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 618, column 15, in _yarn_install_impl
                _copy_file(repository_ctx, repository_ctx.attr.package_json)
        File "C:/users/anusername/_bazel_anusername/idexbm2i/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 345, column 17, in _copy_file
                fail("mkdir -p %s failed: \nSTDOUT:\n%s\nSTDERR:\n%s" % (dirname, result.stdout, result.stderr))
Error in fail: mkdir -p _ failed:
STDOUT:

STDERR:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("mkdir" -p _): The system cannot find the file specified.     
 (error: 2)
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/users/anusername/_bazel_anusername/idexbm2i/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 618, column 15, in _yarn_install_impl
                _copy_file(repository_ctx, repository_ctx.attr.package_json)
        File "C:/users/anusername/_bazel_anusername/idexbm2i/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 345, column 17, in _copy_file
                fail("mkdir -p %s failed: \nSTDOUT:\n%s\nSTDERR:\n%s" % (dirname, result.stdout, result.stderr))
Error in fail: mkdir -p _ failed:
STDOUT:

STDERR:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("mkdir" -p _): The system cannot find the file specified.     
 (error: 2)
ERROR: no such package '@npm//@bazel/protractor': mkdir -p _ failed: 
STDOUT:

STDERR:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("mkdir" -p _): The system cannot find the file specified.     
 (error: 2)
child_process.js:655
    throw err;
    ^

Error: Command failed: yarn --cwd "D:\OpenSource\angular" --silent bazel info bazel-bin
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at exec (D:\OpenSource\angular\scripts\build\package-builder.js:132:18)
    at Object.<anonymous> (D:\OpenSource\angular\scripts\build\package-builder.js:40:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  status: 1,
  signal: null,
  output: [ null, Buffer(0) [Uint8Array] [], null ],
  pid: 15276,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: null
}
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

Windows 10 Pro. Build: 19042.867

**Comment by petebacondarwin** [comment]
Can you try adding `C:\msys64\usr\bin` to your PATH? 
I was getting the same problem as this. It turned out that despite having setup `BAZEL_SH` to correctly point to the msys2 bash program, the PATH was not allowing the scripts being run in that shell to access the relevant tools, such as `mkdir`.

**Comment by MrJithil** [comment]
@petebacondarwin Yeah. Will add the suggestion and will revert back soon. 
Thank You So Much.

**Comment by MrJithil** [comment]
The issue still exists after adding the `C:\msys64\usr\bin` to `PATH`.

**Comment by petebacondarwin** [comment]
Did you check that this is the path to your actual msys2 binaries? Is that PATH update definitely getting included in the console  where you are running the commands? I'm afraid I don't have many other ideas.

**Comment by petebacondarwin** [comment]
Agh! I just tried building on Windows and I am now also hitting this issue again.

I was sure I had fixed this a few months back...

**Comment by petebacondarwin** [comment]
OK, so I pulled the latest master, did a full `git clean -xfd`, ensure I was on the correct `yarn` and `node` versions. Then ran `yarn` and finally `node scripts\build\build-packages-dist.js`, and the script completed successfully.

Although I had the `C:\msys64\usr\bin` in my user PATH, it wasn't appearing when I ran `PATH` from the command line, so I added it to the system PATH. So my PATH now contains:

```
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\WINDOWS\System32\OpenSSH\;
C:\Users\Admin\AppData\Roaming\nvm;
C:\Program Files\nodejs;
C:\Program Files\Git\cmd;
C:\msys64\usr\bin;
C:\Users\Admin\.windows-build-tools\python27\;
C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\bin;
C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;
```

**Comment by MrJithil** [comment]
@petebacondarwin I will check it out soon. And I will update you about my results.

Thanks for the helping hands. I really appreciate it.

**Comment by MrJithil** [comment]
@petebacondarwin In my case, also the `C:\msys64\usr\bin` were in the `USER` path. Once I added it to the `SYSTEM` path and followed the build steps, everything is worked,

I really appreciate the helps you provided. It was a blocker to my contributions here.

**Comment by MrJithil** [comment]
Wonderful suggestions. I am working on it.

**Comment by MrJithil** [comment]
@petebacondarwin I have added it, Please suggest in case any text changes.
