### ISSUE TITLE
onPush Change detection - complex object values are getting updated even if you are mutating the Object.

### ISSUE THREAD

**Issue by nitin15j** [angular/angular#41853]
# 🐞 bug report

### Affected Package
@angular-devkit/core            11.2.10
@angular-devkit/schematics      11.2.10
@angular/cli                    11.2.10

### Is this a regression?

I tested this same behavior in Angular 8, and it was working as per the angular docs

### Description

While choosing onPush change detection strategy, if I pass values from parent to child component using @input parameters like **number** (primitive) and a **string array** (reference), it gets updated in the child every time even I am not changing the reference of string array[]. **On the other hand**, as per docs, in the onPush scenario, we need to change the reference of the complex object to get the updated values to reflect in the child component.

The same scenario works differently if I only pass string[] as @input to my child. In this case, updating the array values in the parent doesn't get reflected in the child component. Once I change the reference on a string[] then only its value gets updated in the child component

for your reference, I am passing two variables in the below fashion...

 @Input()
  inputNumber: number;

  @Input()
  arrItems: string[];

## 🔬 Minimal Reproduction
 https://stackblitz.com/edit/angular-ivy-rvmqxu

## 🔥 Exception or Error
No error in the chrome dev tool, but the application should not behave in this manner

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect       0.1102.10
@angular-devkit/build-angular   0.1102.10
@angular-devkit/core            11.2.10
@angular-devkit/schematics      11.2.10
@angular/cli                    11.2.10
@schematics/angular             11.2.10
@schematics/update              0.1102.10
rxjs                            6.6.7
typescript                      4.1.5
</code></pre>

**Comment by mlc-mlapis** [comment]
@nitin15j You probably missed the principal fact, how the `OnPush` strategy works. It's based on immutability, so you need to change the array reference when you update its content.

**Comment by nitin15j** [comment]
that's the whole point, without changing the array reference, it should not get updated in the child component. But in my example, it's working, i.e. I am only pushing new values in the array still its getting updated in the child component with onPush CD.

**Comment by JoostK** [comment]
This is working as expected. From the grand parent, you're mutating the values of `inputText` and `inputNumber` which causes the OnPush component to be checked, as its input had changed. Therefore, the inserted items in `arrItems` are also reflected in the UI, as the whole view is change detected.

If you do not change the value of `inputText` nor `inputNumber` in `grandParentClicked` you'll see that the OnPush child does not update, as none of its inputs changed by reference. If you then click the "onPush" button the child view does update, as events that have been dispatched from a component will mark that component for check.

Closing as working as expected, but feel free to continue the discussion below.

**Comment by nitin15j** [comment]
I understood, but have we mentioned this information anywhere in our Angular docs? could you please provide here the link?

**Comment by JoostK** [comment]
It is mentioned briefly [in the documentation of `ChangeDetectorRef.markForCheck`](https://angular.io/api/core/ChangeDetectorRef#markforcheck):

> Components are normally marked as dirty (in need of rerendering) when inputs have changed or events have fired in the view. Call this method to ensure that a component is checked even if these triggers have not occured.

It is also mentioned [in the glossary on change detection](https://angular.io/guide/glossary#change-detection):

> If you set the OnPush ("CheckOnce") change-detection strategy, the change detector runs only when explicitly invoked, or when it is triggered by an Input reference change or event handler. This typically improves performance. For more information, see Optimize Angular's change detection.

Other than that, there's #36345 and #12865 for better documentation around this subject.
