### ISSUE TITLE
Cache issue in angular 

### ISSUE THREAD

**Issue by Nayana-9397** [angular/angular#41852]
Changes are not reflecting in the browser when deployed to prod. Need to refresh/reload the browser for at-least for 2-3 times. Please in resolving this issue as this causing to much of problems to the end-users.

**Comment by gkalpak** [comment]
Based on the povided info, this does not sound like an Angular issue. (It is more likely an issue with the configuration of the server/proxy.)

Closing, but feel free to continue the discussion below if you still think it is an issue with Angular.

**Comment by Nayana-9397** [comment]
It is more likely an issue with the configuration of the server/proxy.

hi, can you please elaborate on the solution provided
