### ISSUE TITLE
Do we need the Contributor Over Time chart?

### ISSUE THREAD

**Issue by starsz** [angular/angular#41856]
Hi, we have generated a chart of the contributor over time, which may be helpful to you.

You can take a look here:
https://contributor-graph-api.apiseven.com/contributors-svg?chart=contributorOverTime&repo=angular/angular

Thank you!

**Comment by petebacondarwin** [comment]
Thanks for creating this chart @starsz - it does not seem particularly informative as it is. I am not sure it is particularly helpful to us.
