### ISSUE TITLE
Compiler doesn't infer types from pipes with class-level generics

### ISSUE THREAD

**Issue by lincolnthree** [angular/angular#41861]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler or @angular/language-service

### Is this a regression?

 Maybe? I don't know. This may never have worked. Stackblitz doesn't show the error when running with Angular 11 deps, so maybe?

### Description

 A clear and concise description of the problem...
As seen in: https://github.com/rx-angular/rx-angular/issues/634

Create a pipe with a class-level generic type argument that is used as a return value in the `transform(...)` method signature. All type information is subsequently lost during compilation of the template, and variables resolve as "unknown" type:

Here for example, `md.isMobile$` is an `Observable<boolean>`:

![image](https://user-images.githubusercontent.com/362329/116436008-f7349800-a819-11eb-9ee3-073ca67a68e3.png)

In the pushPipe implementation:
```
// Replacing this:
export class PushPipe<U> implements PipeTransform, OnDestroy {
   transform (...): U { }
}

// With this:
export class PushPipe implements PipeTransform, OnDestroy {
   transform<U> (...): U { }
}

```

## 🔬 Minimal Reproduction
Broken:
```
@Pipe({ name: 'push', pure: false })
export class PushPipe<U> implements PipeTransform {
  transform(obj: Observable<U>): U | null | undefined {
    return null;
  }
}
```

Works:
```
@Pipe({ name: 'push', pure: false })
export class PushPipe implements PipeTransform {
  transform<U>(obj: Observable<U>): U | null | undefined {
    return null;
  }
}
```

 https://stackblitz.com/edit/angular-ivy-zdl5xa?file=src%2Fapp%2Fapp.component.html

## 🔥 Exception or Error
<pre><code>
[ng]     Error occurs in the template of component TestPage.
[ng] Error: src/app/pages/test.page.html:10:40 - error TS2339: Property 'type' does not exist on type 'unknown'.
[ng] 10                     format="{{ payload.type }}">
[ng]     

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.0-rc.0
Node: 14.15.0
OS: darwin x64

Angular: 12.0.0-rc.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, pwa, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0-rc.0
@angular-devkit/build-angular   12.0.0-rc.0
@angular-devkit/core            12.0.0-rc.0
@angular-devkit/schematics      12.0.0-rc.0
@angular/fire                   6.1.4
@schematics/angular             12.0.0-rc.0
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
It is indeed the case that a pipe with generic type parameter does not allow type inference to flow correctly. More information on why this is the case can be found in https://github.com/angular/angular/pull/40870#issuecomment-780882880.

I'd recommend to change the pipe such that only `transform` has a generic type parameter and not the class itself.

**Comment by alxhub** [comment]
I'm going to close this, as I don't believe we're going to change how generics and pipes work.

Consider the case of a pipe that is `pure: true`. One possible optimization we _could_ do is to share the instance of such a pipe over the whole template. A class-level generic for such a pipe would then make no sense, as multiple types of values may pass through the single instance's `transform()` method.

Whether this is a safe optimization is a different question - Angular documents that pure pipes should have side effect-free `transform` implementations, but developers may not have followed this practice.
