### ISSUE TITLE
[NgZone] shouldCoalesceChangeDetection option results in infinite change detections

### ISSUE THREAD

**Issue by mleibman** [angular/angular#41870]
The `shouldCoalesceChangeDetection` option added in https://github.com/angular/angular/pull/39422 results in infinite change detections done as a `requestAnimationFrame`.

### Repro ###

Repro: https://stackblitz.com/edit/angular-1ucpvz

This happens in an empty Angular app just by turning on the option:

```typescript
platformBrowserDynamic()
  .bootstrapModule(AppModule, {
    ngZoneRunCoalescing: true
  })
```

**Comment by mleibman** [comment]
@JiaLiPassion

**Comment by JiaLiPassion** [comment]
@mleibman, got it, I will check it.

**Comment by JiaLiPassion** [comment]
@mleibman , this issue has been fixed here https://github.com/angular/angular/pull/40540
@AndrewKushnir , since the PR https://github.com/angular/angular/pull/40540 is `target: minor`, so it will not be included in the `Angular 11` release, is that correct?

**Comment by AndrewKushnir** [comment]
> since the PR #40540 is target: minor, so it will not be included in the Angular 11 release, is that correct?

@JiaLiPassion yes, the mentioned changes was merged Feb 22 after [v11.2.0](https://github.com/angular/angular/releases/tag/11.2.0) was released (Feb 11), so the change would be released in v12.0.0. 

@mleibman the change that @JiaLiPassion refers to was already merged into Google's codebase. Do you experience this issue in an internal project or external?

**Comment by mleibman** [comment]
> @mleibman the change that @JiaLiPassion refers to was already merged into Google's codebase. Do you experience this issue in an internal project or external?

I see. I have run into test failures turning this option on in GCP Frontend, but I haven't looked into why and decided to start the investigation by trying it in a Stackblitz instead.

**Comment by mleibman** [comment]
That said, given that the option exists but doesn't work correctly in Angular 11, shouldn't it be merged there?

**Comment by alxhub** [comment]
Closing as obsolete, as this has been fixed in Angular 12+.
