### ISSUE TITLE
Testing with BehaviourSubject and debounceTime.

### ISSUE THREAD

**Issue by JeviScript** [angular/angular#41879]
Hello there! 
I cannot unit test a component which uses rxjs observable built with BehaviourSubject and which uses debounceTime.
## Component example:
```
public gg = 1;
private subject = new BehaviorSubject("blabla");
private please = this.subject.asObservable();
// private please = of("blabla"); // it works

public wp$ = this.please.pipe(
    debounceTime(300),
    switchMap(() => {
      this.gg = 2;
      return of("new blabla");
    })
);
```
## Test example:
```
describe('test', () => {
  let fixture: ComponentFixture<AppComponent>;
  let component: AppComponent;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [AppModule]
    })
    
    fixture = TestBed.createComponent(AppComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  })

  it('works', fakeAsync(() => {
    tick(300);
    expect(component.gg).toBe(2);
  }))
});
```

I subscribe to `wp$` in html file using async pipe. The test does not pass. However, interestingly, if I change the source observable to something like `of('blabla')`, i.e. observable which completed right away, the test would pass. 

## 🔬 Full example reproduction
https://stackblitz.com/edit/angular-ivy-ue7wkw?file=src%2Fapp%2Fapp.component.ts

**Comment by JoostK** [comment]
This doesn't work as demonstrated because of the `fixture.detectChanges();` invocation in `beforeEach`. That means that the observable is subscribed to outside of `fakeAsync`, such that the timer is not faked.  Delaying change detection to occur within the `fakeAsync` block causes the subscription to happen within the `fakeAsync` block.

**Comment by JeviScript** [comment]
I still do not understand why the test pass when I use another observable as the source. If I used that would work:
```
  private please = of("blabla"); // it works

  public wp$ = this.please.pipe(
    debounceTime(300),
    switchMap(() => {
      this.gg = 2;
      return of("new blabla");
    })
  );
```
or If I kept my BehaviourSubject but piped it with `take(1)` what would also work. That's what I don't understand about this situation

**Comment by JoostK** [comment]
That is because `of` completes the observable, which means that the `debounceTime` operator no longer awaits the timer as it certain there won't be any additional values. This means that the `switchMap` callback is triggered synchronously, during the completion of the `of` observable.

**Comment by JeviScript** [comment]
Huge Thanks !
