### ISSUE TITLE
Router LocationStrategy not a "local URL", baseHref results in 404

### ISSUE THREAD

**Issue by OzBob** [angular/angular#41889]
### Description
Doc is misleading '[LocationStrategy and browser URL styles
]'(https://angular.io/guide/router#locationstrategy-and-browser-url-styles) says:

"this is a strictly local URL the browser won't send this URL to the server and will not reload the page"
and
"a technique that changes a browser's location and history **without** triggering a server page request"

## 🔬 Minimal Reproduction
https://mysite.com/basehref/app/route/featuremoduleroute
shows 
404

The angular browser navigation **does** trigger server a page request.

### What's the affected URL?**
_private, can supply on request_

### Reproduction Steps**
I have a azure static website and am hosting the angular app in a sub-folder called /cp/
To build the angular app:

```ng build --prod --output-path dist/cp/ --base-href /cp/```

which is fine for viewing the root url, but as soon as I navigate to feature module child route, the server redirects my page to 404 as that URL route does not exist.

I have had to resort to 'useHash:true' on the router [extraOptions](https://angular.io/api/router/ExtraOptions#useHash).

### Expected vs Actual Behavior**
Docs should say:
Some applications will be on shared infrastructure and end up being hosted in a sub-folder. A hosted server's routing re-write rules should redirect all traffic to your application, e.g. /baseHref/* to /baseHref/
If you do not have access to the server routing definition, even on modern browsers, use a baseHref during build and set 'useHash:true' on the app router [extraOptions](https://angular.io/api/router/ExtraOptions#useHash) as detailed in the [HashLocationStrategy](https://angular.io/guide/router#hashlocationstrategy) docs.

**Comment by OzBob** [comment]
The "[configure a fallback route on your server](https://github.com/angular/angular/issues/19009#issuecomment-326727616)" solution proposed by @Toxicable, and the [Apache deployment solution](https://github.com/mgechev/angular-seed/wiki/Deploying-prod-build-to-Apache-2) both suggest either add server routes or use hashLocationStrategy.

**Comment by atscott** [comment]
Arguably, the documentation is correct there because it's talking about router navigations, which _are_ strictly a local url and do not result in a server request. A direct url navigation or hard page refresh is a navigation triggered by the browser rather than the Angular router. But I agree that there could be some clarification in the docs there.

**Comment by OzBob** [comment]
When the app is hosted on a Web server with no error rewrite rules and I navigate to
/basehref/index.html OK
But
When I go 'deep' I get server generated 404.

From that experience I was wondering if the change in URL actually does get validated at the server.

**Comment by jnizet** [comment]
@OzBob this is explained in https://angular.io/guide/deployment#routed-apps-must-fallback-to-indexhtml

**Comment by OzBob** [comment]
Thank you for the link. It says: "The browser makes a direct request to the server for that URL, bypassing the router." just reinforces the misleading statement of "as this is a strictly local URL the browser won't send this URL to the server" on  https://angular.io/guide/router#locationstrategy-and-browser-url-styles

**Comment by atscott** [comment]
@OzBob - Again, the statement you’re pointing to is referring to navigations through the Angular router. Deep links go to the server because there’s no page loaded. My opinion is that it’s not misleading at all but could potentially use clarification.
