### ISSUE TITLE
Custom Component two way binding

### ISSUE THREAD

**Issue by TiagoBraga39** [angular/angular#4189]
Hi all!

Is it possible to have a <b>component</b> with two way binding?
As in:
```html
<custom-cmp [(custom-property)]="property"></custom-cmp>
```

CustomComponent is supposed to have an input and a button, for example.

If no, is it possible to do so by accessing to host? And how?

I've read about it on this article: http://victorsavkin.com/post/119943127151/angular-2-template-syntax

And read your implementation of NgModel. Should I do my component with a similar behaviour? https://github.com/angular/angular/blob/70f6a46f1cbe090c946fd5ffea13f78be216ac05/modules/angular2/src/core/forms/directives/ng_model.ts

Best regards,
Tiago Braga

By the way, I am not using TypeScript, so I can't implement interfaces (I saw some solutions with that).

**Comment by TiagoBraga39** [comment]
@vicb Could you help please?

**Comment by TiagoBraga39** [comment]
@vsavkin Since the article is yours, could you help please?

**Comment by pkozlowski-opensource** [comment]
@TiagoBraga39 you can definitively have a custom component using the `[(foo)]="bar"` syntax. Here is a simple example: http://plnkr.co/edit/oeLejuZW1dF1CFFfr9zt?p=preview

> If no, is it possible to do so by accessing to host? And how?

Not sure what you mean.... Just have a look at the linked plunker. And remember that `[(foo)]` is just a short-cut for `[foo]="bar" (foo)="bar = $event"`

I hope that the above answers so your question so I'm, going to close this issue for now. Let's move the discussion to gitter if you need more info.

**Comment by TiagoBraga39** [comment]
@pkozlowski-opensource Thank you very much for the answer.
After I posted this, I saw some examples with what you presented.

But I couldn't understand what this was:
![image](https://cloud.githubusercontent.com/assets/8090726/9877594/ba4969e0-5bb5-11e5-93e4-ac158a808053.png)

So, I rewrote a lot of times.
And the problem was the instanciation of the EventEmitter... I was doing that on onInit() method.
Why? Not so sure, but my components constructor methods only resolve dependecies. Like this:

```javascript
constructor(elementRef: ElementRef, service : EntityService, router : Router) {
    this.element = elementRef;
    this.service = service;
    this.router = router;
}
onInit()  {
    this.valueUpdate = new EventEmitter();
}
```
I thought onInit would trigger right after constructor and before evaluating sent DOM properties.
Anyway, at least it is working now.

Thank you! :+1: 

Best regards,
Tiago Braga

**Comment by pkozlowski-opensource** [comment]
Yeh, the error message in case of not initializing EventEmitter properly isn't ideal - I've opened an issue in the past to improve it: https://github.com/angular/angular/issues/3664

**Comment by TiagoBraga39** [comment]
@pkozlowski-opensource Hi again!

It is all working, but the exposed property can't have hyphens?
http://plnkr.co/edit/Y6o4CpV6OlHppgY4R8YU?p=preview

The event does not completely resolve?

**Comment by pkozlowski-opensource** [comment]
It works if you do `events: ['valueUpdate: selectedValue']`: http://plnkr.co/edit/TnUqxetDhbgcO1ZEX63U?p=preview

Having said this I agree that this is not super-consistent.... Could you file a separate issue for this?

**Comment by TiagoBraga39** [comment]
Yes, right away.

**Comment by afontang** [comment]
Hi.
It seems that this sample don't work with the beta of Angular 2. ¿Is it possible to update it?
