### ISSUE TITLE
Support for rxjs 7

### ISSUE THREAD

**Issue by prabh-62** [angular/angular#41897]
# Description

Angular 12 workspace comes bundled with rxjs `6.6.0`
```shell
❯ npx @angular/cli@12.0.0-rc.1 new web-apps --create-application false --skip-install
```
<img width="420" alt="angular_12_rxjs_6 6" src="https://user-images.githubusercontent.com/13006107/116716857-3ee82a80-a9a6-11eb-866f-1ef17a3e7f3d.png">

### Describe the solution you'd like

Angular 12 workspace should come bundled with [rxjs 7](https://www.npmjs.com/package/rxjs)

RxJS 7 Slides: https://docs.google.com/presentation/d/1-LU7YE3NWw8jHeAgdmLu4CBfG7osCx6MsSIeFs16k60

I see pull request https://github.com/angular/angular-cli/pull/20669 was closed recently.

**Comment by jelbourn** [comment]
rxjs v7 won't be stable for v12, so it won't be included by default. 

Related: #41590

**Comment by PowerKiKi** [comment]
> rxjs v7 won't be stable for v12, so it won't be included by default.

@jelbourn, actually [rxjs 7.0.0 was released 1 day before](https://github.com/ReactiveX/rxjs/releases/tag/7.0.0) you said that. Were you not aware of that release at that time or did you mean that rxjs 7 _support in Angular_ won't be stable enough for v12 ?

**Comment by alxhub** [comment]
> > rxjs v7 won't be stable for v12, so it won't be included by default.
> 
> @jelbourn, actually [rxjs 7.0.0 was released 1 day before](https://github.com/ReactiveX/rxjs/releases/tag/7.0.0) you said that. Were you not aware of that release at that time or did you mean that rxjs 7 _support in Angular_ won't be stable enough for v12 ?

v12's first Release Candidate (rc0) was cut 2 weeks ago. After that, the versions of dependencies such as RxJS are generally fixed.

**Comment by jelbourn** [comment]
Yeah, it caught me by surprise- I wasn't expecting it until after v12 since there are still outstanding issues w/ v7 inside Google.

**Comment by BenRacicot** [comment]
I had read somewhere that V7 was good to go on V12, hmm.
Should we not force it? `npm i --legacy-peer-deps`

➜  client git:(master) ✗ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: aspectratia@0.0.0
npm ERR! Found: rxjs@7.0.1
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"~7.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^6.5.3" from @angular/core@12.0.0
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"~12.0.0" from the root project
npm ERR!   peer @angular/core@"12.0.0" from @angular/animations@12.0.0
npm ERR!   node_modules/@angular/animations
npm ERR!     @angular/animations@"~12.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/bracicot/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bracicot/.npm/_logs/2021-05-15T01_52_18_845Z-debug.log

**Comment by zijianhuang** [comment]
Angular 12 with rxjs 7.0.1 could be built and run, however, the VS IDE could not check reference. And tsconfig with strict=true has NG CLI complaining no reference to rxjs could be found and suggesting downloading type info.

**Comment by vitaly-t** [comment]
Now that RXJS v7.1 is out, can we expect Angular v12.1.0 to start using it?

This new RXJS is so much better and smaller, it will be a shame not to start using it with v12 of Angular.

**Comment by arobinson** [comment]
`@angular/core` has a peer dependency on RxJS 6, is it possible to allow RxJS 7 as a peer dependency so that Angular can support 6 or 7 but still have a minimum of 6?

**Comment by crisbeto** [comment]
We can't update the minimum required version of rxjs until Angular 13, because rxjs version 7 includes breaking changes. We're exploring how to support both 6 and 7 for projects that want to opt into it earlier.

**Comment by eugene-stativka** [comment]
@crisbeto thank you! It would be great to be able to use RxJS 7. It brings so many benefits.

**Comment by klizter** [comment]
BUMP!

**Comment by theodorejb** [comment]
I'm still getting incompatible peer dependency errors for @angular/cdk and @angular/material when using RxJS 7:

> Package "@angular/cdk" has an incompatible peer dependency to "rxjs" (requires "^6.5.3", would install "7.1.0")
> Package "@angular/material" has an incompatible peer dependency to "rxjs" (requires "^6.5.3", would install "7.1.0")

**Comment by crisbeto** [comment]
Ah, we never bumped the allowed version on the non-core packages. I'll do it now.

**Comment by princemaple** [comment]
If you simply update angular packages then install rxjs 7, it would just work fine. Given that you are still on node 14 and npm 6. It would probably have issues on npm 7

**Comment by destus90** [comment]
@princemaple 
Both flags `--force` and `--legacy-peer-deps ` should resolve the issue when using npm7.
