### ISSUE TITLE
[Reopen] ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by rabraghib** [angular/angular#41909]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/common/http

### Description
checkout #41311 & https://github.com/angular/angular/issues/41311#issuecomment-803955901

**Comment by AndrewKushnir** [comment]
Hi @rabraghib, I will reopen the ticket that you mentioned and  close this one (since the original ticket contains more context). Please provide any additional info in #41311, so that the team can help look into that.
