### ISSUE TITLE
Failed to compile entry-point @angular/material/core with Bidi

### ISSUE THREAD

**Issue by TicTak21** [angular/angular#41917]
# 🐞 bug report

### Affected Package
@angular/cdk/bidi
@angular/material/core

### Is this a regression?
I dont know

### Description
When I run `ng serve` compiling fails on `@angular/material/core` with bidi

## 🔥 Exception or Error
<pre><code>
Compiling @angular/material/core : es2015 as esm2015
Error: Failed to compile entry-point @angular/material/core (`es2015` as esm2015) due to compilation errors:
../../node_modules/@angular/cdk/bidi/bidi-module.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of MatCommonModule, but could not be resolved to an NgModule class.

This likely means that the library (@angular/cdk/bidi) which declares BidiModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

8 export declare class BidiModule {
                       ~~~~~~~~~~
../../node_modules/@angular/cdk/bidi/bidi-module.d.ts:8:22 - error NG6003: Appears in the NgModule.exports of MatCommonModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class.

This likely means that the library (@angular/cdk/bidi) which declares BidiModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

8 export declare class BidiModule {
                       ~~~~~~~~~~
../../node_modules/@angular/cdk/platform/platform-module.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of NativeDateModule, but could not be resolved to an NgModule class.

This likely means that the library (@angular/cdk/platform) which declares PlatformModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

8 export declare class PlatformModule {
                       ~~~~~~~~~~~~~~
node_modules/@angular/material/fesm2015/core.js:787:7 - error NG6002: Appears in the NgModule.imports of MatNativeDateModule, but itself has errors

787 class NativeDateModule {
          ~~~~~~~~~~~~~~~~
node_modules/@angular/material/fesm2015/core.js:71:7 - error NG6002: Appears in the NgModule.imports of MatLineModule, but itself has errors

71 class MatCommonModule {
         ~~~~~~~~~~~~~~~
node_modules/@angular/material/fesm2015/core.js:71:7 - error NG6003: Appears in the NgModule.exports of MatLineModule, but itself has errors

71 class MatCommonModule {
         ~~~~~~~~~~~~~~~
node_modules/@angular/material/fesm2015/core.js:71:7 - error NG6002: Appears in the NgModule.imports of MatRippleModule, but itself has errors

71 class MatCommonModule {
         ~~~~~~~~~~~~~~~
../../node_modules/@angular/cdk/platform/platform-module.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of MatRippleModule, but could not be resolved to an NgModule class.

This likely means that the library (@angular/cdk/platform) which declares PlatformModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

8 export declare class PlatformModule {
                       ~~~~~~~~~~~~~~
node_modules/@angular/material/fesm2015/core.js:71:7 - error NG6003: Appears in the NgModule.exports of MatRippleModule, but itself has errors

71 class MatCommonModule {
         ~~~~~~~~~~~~~~~
node_modules/@angular/material/fesm2015/core.js:71:7 - error NG6002: Appears in the NgModule.imports of MatPseudoCheckboxModule, but itself has errors

71 class MatCommonModule {
         ~~~~~~~~~~~~~~~
node_modules/@angular/material/fesm2015/core.js:1288:7 - error NG6002: Appears in the NgModule.imports of MatOptionModule, but itself has errors

1288 class MatRippleModule {
           ~~~~~~~~~~~~~~~
node_modules/@angular/material/fesm2015/core.js:71:7 - error NG6002: Appears in the NgModule.imports of MatOptionModule, but itself has errors

71 class MatCommonModule {
         ~~~~~~~~~~~~~~~
node_modules/@angular/material/fesm2015/core.js:1358:7 - error NG6002: Appears in the NgModule.imports of MatOptionModule, but itself has errors

1358 class MatPseudoCheckboxModule {
           ~~~~~~~~~~~~~~~~~~~~~~~

Warning: Skipping processing of @angular/material/divider because its dependency @angular/material/core failed to compile.
Warning: Skipping processing of @angular/material/badge because its dependency @angular/material/core failed to compile.
Warning: Skipping processing of @angular/material/button because its dependency @angular/material/core failed to compile.
Warning: Skipping processing of @angular/material/checkbox because its dependency @angular/material/core failed to compile.
Warning: Skipping processing of @angular/material/icon because its dependency @angular/material/core failed to compile.
Warning: Skipping processing of @angular/material/list because its dependency @angular/material/core failed to compile.
Warning: Skipping processing of @angular/material/menu because its dependency @angular/material/core failed to compile.
Warning: Skipping processing of @angular/material/toolbar because its dependency @angular/material/core failed to compile.
Error: There are still unprocessed tasks in the queue and no tasks are currently in progress, yet the queue did not return any available tasks: ParallelTaskQueue
  All tasks completed: true
  Unprocessed tasks (0): 
  In-progress tasks (0): 
  Blocked tasks (0): 
    at ClusterMaster.maybeDistributeWork (streetster/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:134:27)
    at ClusterMaster.onWorkerTaskCompleted (streetster/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:228:18)
    at ClusterMaster.onWorkerMessage (streetster/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:197:33)
    at streetster/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:55:95
    at ClusterMaster.<anonymous> (streetster/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:293:57)
    at step (streetster/node_modules/tslib/tslib.js:143:27)
    at Object.next (streetster/node_modules/tslib/tslib.js:124:57)
    at streetster/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (streetster/node_modules/tslib/tslib.js:113:16)
An unhandled exception occurred: NGCC failed.
See "/private/var/folders/wy/slmqdxgs7h91gw7m4d1f52w00000gn/T/ng-zhDdiw/angular-errors.log" for further details.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.11
Node: 14.16.0
OS: darwin x64

Angular: 11.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.11
@angular-devkit/build-angular   0.1102.11
@angular-devkit/core            11.2.11
@angular-devkit/schematics      11.2.11
@angular/cdk                    11.2.11
@angular/cli                    11.2.11
@angular/material               11.2.11
@schematics/angular             11.2.11
@schematics/update              0.1102.11
rxjs                            6.6.7
typescript                      4.1.5
</code></pre>

package.json

<pre><code>
"dependencies": {
    "@angular/animations": "~11.2.12",
    "@angular/cdk": "11.2.11",
    "@angular/common": "~11.2.12",
    "@angular/compiler": "~11.2.12",
    "@angular/core": "~11.2.12",
    "@angular/forms": "~11.2.12",
    "@angular/material": "11.2.11",
    "@angular/platform-browser": "~11.2.12",
    "@angular/platform-browser-dynamic": "~11.2.12",
    "@angular/router": "~11.2.12",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@streetster/types": "^0.0.1",
    "@angular-devkit/build-angular": "~0.1102.11",
    "@angular-eslint/builder": "4.2.0",
    "@angular-eslint/eslint-plugin": "4.2.0",
    "@angular-eslint/eslint-plugin-template": "4.2.0",
    "@angular-eslint/schematics": "4.2.0",
    "@angular-eslint/template-parser": "4.2.0",
    "@angular/cli": "~11.2.11",
    "@angular/compiler-cli": "~11.2.12",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "4.16.1",
    "@typescript-eslint/parser": "4.16.1",
    "eslint": "^7.6.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "typescript": "~4.1.5"
  }
</code></pre>

1) I tried to disable Ivy in `tsconfig.json` with `"enableIvy": false`.
Than I got this error:
<pre><code>
Initial Chunk Files | Names         |    Size
main.js             | main          | 0 bytes
polyfills.js        | polyfills     | 0 bytes
runtime.js          | runtime       | 0 bytes
styles.css          | styles        | 0 bytes
vendor.js           | vendor        | 0 bytes

                    | Initial Total | 0 bytes

Build at: 2021-05-02T13:41:39.326Z - Hash: d8ec7649b38b0a863bd8 - Time: 7076ms

Error: Unexpected value 'BidiModule in 'streetster/node_modules/@angular/cdk/bidi/index.d.ts' imported by the module 'MatCommonModule in '../ng-admin/node_modules/@angular/material/core/index.d.ts'. Please add a @NgModule annotation.

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
</code></pre>

2) I also tried to remove `node_modules` and install clean packages. It didn't work.

3) Link to my repo: https://github.com/TicTak21/streetster/tree/master/packages/ng-admin
Unfortunately I can't create minimal reproducible repo.

**Comment by JoostK** [comment]
The usage of Yarn workspaces is causing issues here. The `yarn.lock` is in a state such that some packages are installed into `/node_modules`, whereas others are installed into `/packages/ng-admin/node_modules`. Serving the Angular app from within `/packages/ng-admin` will process the local `node_modules` directory before the root `node_modules` has been processed; this fails because the dependent libraries have not yet been compiled.

You can either setup [nohoist rules](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/) to prevent hoisting all `**/@angular/**` packages to the root, or you can run `ngcc` manually from the command line for the root `node_modules`. Either approach allows the app to compile. For the nohoist to start working you might need to remove the `yarn.lock` file.

I don't think we'll be addressing this scenario in ngcc nor the CLI.

**Comment by TicTak21** [comment]
Thank you. 

I used option with "nohoist rules". It helped me. 
Just added a few lines to the top level(root) `package.json`:

```
"workspaces": {
    "nohoist": [
      "**/@angular/**"
    ]
  }
```
