### ISSUE TITLE
Remove heroes.component.1.ts  in toh-pt4 and heroes.component.1.html in toh-pt2

### ISSUE THREAD

**Issue by iRealNirmal** [angular/angular#41921]
# 📚 Docs or angular.io bug report

### Description

Clean up and remove heroes.component.1.ts  in toh-pt4 and heroes.component.1.html in toh-pt2
as it's not being used

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Anything else relevant?

[https://github.com/angular/angular/blob/master/aio/content/examples/toh-pt2/src/app/heroes/heroes.component.1.html](https://github.com/angular/angular/blob/master/aio/content/examples/toh-pt2/src/app/heroes/heroes.component.1.html)

[https://github.com/angular/angular/blob/master/aio/content/examples/toh-pt4/src/app/heroes/heroes.component.1.ts](https://github.com/angular/angular/blob/master/aio/content/examples/toh-pt4/src/app/heroes/heroes.component.1.ts)

**Comment by petebacondarwin** [comment]
@iRealNirmal - do you want to create a PR for this?

**Comment by iRealNirmal** [comment]
@petebacondarwin same `getHeroes() `method is covered under 
[https://github.com/angular/angular/blob/master/aio/content/examples/toh-pt4/src/app/heroes/heroes.component.ts](https://github.com/angular/angular/blob/master/aio/content/examples/toh-pt4/src/app/heroes/heroes.component.ts)

so no need of second file. But with this your pointed document should be updated together from my perspective.

**Comment by petebacondarwin** [comment]
The `ctor` doc-region is definitely different between the two files.

**Comment by iRealNirmal** [comment]
@petebacondarwin closing this ticket, as having this files separately with *.1.ts is expected. Thanks for providing quick insight of it.
