### ISSUE TITLE
EntryComponents marked deprecrated

### ISSUE THREAD

**Issue by akiraplusplus** [angular/angular#41925]
As instructed by the Angular Update Guide, I removed entryComponents from my NgModules file. Only later on in the development process did I see the warning that an Angular npm library shouldn't use Ivy, and so I disabled Ivy, but at this point the mention of Ivy in the instructions about entryComponents, as the reason entryComponents was no longer needed, was a distant memory.

Only later when my library failed to work in an application that installed it did I eventually figure out that the fix needed was to restore the removed entryComponents.

The Angular Update Guide should also warn that there are situations when you should leave entryComponents in place.

**Comment by JoostK** [comment]
Thanks for noticing; the `entryComponents` array is indeed still required in a ViewEngine based application. It should be possible to remove `entryComponents` even in a library, as long as that library is only used in Ivy applications.

See existing issue #39958 which raises the same problem.
