### ISSUE TITLE
ServiceWorker Caching of Cross-domain URLs fails

### ISSUE THREAD

**Issue by byronlbailey** [angular/angular#41931]
# 🐞 bug report

### Affected Package
ngsw-worker.js

### Is this a regression?
No

### Description
We are trying to use the service worker to cache resources pulled from an S3 bucket.  However, we receive CORS errors which prevents the resources from loading.  When the service worker is disabled, the fetching of the resources works fine.

Note that my CORS policy on the s3 bucket is set to allow all origins, which is confirmed by the fact it works when the service worker is disabled.

I have done some debugging of the code and found that when new requests are objects are created in the service worker, that the new request's mode is set to "cors" whereas the original ones are "no-cors".  For example, this line:

                    const res = yield this.fetchAndCacheOnce(this.adapter.newRequest(req.url));

console.log(req.mode); // outputs no-cors
console.log(this.adapter.newRequest(req.url)); //outputs cors

I'm not sure if it's related, but that's where am in triage.

## 🔬 Minimal Reproduction

https://github.com/byronlbailey/swissue
1) Clone the repo to local workstation
2) ng build --prod
3) cd dist/swissue
4) http-server (may need to install this npm module)
5) open incognito browser to url specified by http-server
6) The image may show the first, time, but after refreshing your browser it typically disappears

## 🔥 Exception or Error
`Access to fetch at 'https://eksplor.s3.us-east-2.amazonaws.com/game/diamondlakes1/main.png' from origin 'http://127.0.0.1:8081' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
The FetchEvent for "https://eksplor.s3.us-east-2.amazonaws.com/game/diamondlakes1/main.png" resulted in a network error response: the promise was rejected.
Promise.then (async)
onFetch @ ngsw-worker.js:2053
(anonymous) @ ngsw-worker.js:1988
ngsw-worker.js:662 Uncaught (in promise) Error: Response not Ok (fetchAndCacheOnce): request for https://eksplor.s3.us-east-2.amazonaws.com/game/diamondlakes1/main.png returned response 504 Gateway Timeout
    at LazyAssetGroup.<anonymous> (ngsw-worker.js:662)
    at Generator.next (<anonymous>)
    at fulfilled (ngsw-worker.js:196)`

## 🌍  Your Environment
Angular CLI: 11.0.7
Node: 14.15.4
OS: darwin x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cli                    11.0.7
@schematics/angular             11.0.7
@schematics/update              0.1100.7
rxjs                            6.6.7
typescript                      4.0.7

No additional environmental-specific concerns identified.

**Comment by byronlbailey** [comment]
Update:
It appears that this issue is more straightforward than I initially thought.  When the browser returns the response from the internal cache, res.ok is false.  Hence, in situations where resources are loaded before the service worker is loaded the first time, res.ok always shows false and the resources fail to load.  For now, I have done the following as a workaround:

if(res.status >= 400){
   throw new Error(`Response not Ok (fetchAndCacheOnce): request for ${req.url} returned response ${res.status} ${res.statusText}`);
}

**Comment by byronlbailey** [comment]
I noticed that the gateway timeout/cors message magically went away when i fixed the issue above, which didn't make sense.  It turns out that there are two issues here.  If the browser initially has the image cached from a request prior to the SW being installed, then you may avoid the cors issue.  However, if the SW is the first one to load it, then it results in CORS errors.  I worked around it by changing the newRequest utility function, which causes "no-cors" flags to get dropped throughout the module.  A better solution would be to copy the cors setting from the source request (when available) or perhaps set the origin header from the sw scope?

newRequest(input, init) {

            var options = init || {}
            if(!options.mode){
                options.mode = "no-cors";
            }
            return new Request(input, options);
        }

**Comment by gkalpak** [comment]
Thx for the detailed info, @byronlbailey (and sorry for the late response 😞).
It is true that we might be a bit over-aggressive with stripping off request headers and other metadata (such as `mode`) in the SW (see #24227 for a related discussion).

I think it makes sense to start relaxing the stripping off of such metadata, such as the `mode` (except for `navigate`) and maybe [simple headers][1].

##
@byronlbailey, would be interested in submitting a pull request for (some of) that?

[1]: https://fetch.spec.whatwg.org/#simple-header

**Comment by gkalpak** [comment]
I took a deeper look at this today. Originally I set out to implement passing `mode` through to the server, but down the road I realized this is also problematic and probably not what we want here. here are my findings/thoughts:

1. The S3 bucket is actually not configured correctly for CORS, which is evident by the error message:
    ```
    No 'Access-Control-Allow-Origin' header is present on the requested resource.
    ```

2. The reason the image works without the ServiceWorker is exactly because the browser requests images with `no-cors` mode. This results in an opaque response, which means that the response cannot be accessed by JavaScript, but it fine for the purposes of an `<img>` element.

3. From the possible values of [Request#mode][1], the ones that make sense for asset requests are: `cors`, `no-cors`, `same-origin`
    - `cors` is the default value for programmatic `fetch()` requests (such as those the ServiceWorker creates), so passing it through doesn't make any difference here.
    - `same-origin` will behave the same as `cors` for same-origin requests (afaict) and it shouldn't be used for cross-origin assets requests. So, if an asset request with `mode: 'same-origin'` gets to the ServiceWorker it is either an error (if it is a cross-origin request) or will succeed with the default `mode: 'cors'` anyway. So, again, passing `same-origin` through to the server will not make much of a difference.
    - `no-cors` is the only value that might be useful to pass through, but comes with its own set of issues:
        It would result in a opaque response, meaning that the ServiceWorker would not be able to access the request fields. This is particularly problematic for asset requests, for which the ServiceWorker needs to be able to compute hashes or read headers to determine if the resource needs to be updated.

##
Based on the above, I don't think that preserving the request `mode` for asset requests is desirable (or at least it is a much more involved/risky endeavor). For asset requests, I think it makes more sense to expect any external origins to be correctly set up for CORS.

I will create a PR to add a note about that in the docs.

I hope this makes sense. Please let me know if I am missing anything.

[1]: https://developer.mozilla.org/en-US/docs/Web/API/Request/mode
