### ISSUE TITLE
zone is not defined ( Uncaught ReferenceError: Zone is not defined )

### ISSUE THREAD

**Issue by aanchal88** [angular/angular#41940]
This is my polyfills.ts

/**
 * This file includes polyfills needed by Angular and is loaded before the app.
 * You can add your own extra polyfills to this file.
 *
 * This file is divided into 2 sections:
 *   1. Browser polyfills. These are applied before loading ZoneJS and are sorted by browsers.
 *   2. Application imports. Files imported after ZoneJS that should be loaded before your main
 *      file.
 *
 * The current setup is for so-called "evergreen" browsers; the last versions of browsers that
 * automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),
 * Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.
 *
 * Learn more in https://angular.io/guide/browser-support
 */

/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
// import 'classlist.js';  // Run `npm install --save classlist.js`.

/**
 * Web Animations `@angular/platform-browser/animations`
 * Only required if AnimationBuilder is used within the application and using IE/Edge or Safari.
 * Standard animation support in Angular DOES NOT require any polyfills (as of Angular 6.0).
 */
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.

/**
 * By default, zone.js will patch all possible macroTask and DomEvents
 * user can disable parts of macroTask/DomEvents patch by setting following flags
 * because those flags need to be set before `zone.js` being loaded, and webpack
 * will put import in the top of bundle, so user need to create a separate file
 * in this directory (for example: zone-flags.ts), and put the following flags
 * into that file, and then add the following code before importing zone.js.
 * import './zone-flags.ts';
 *
 * The flags allowed in zone-flags.ts are listed here.
 *
 * The following flags will work for all browsers.
 *
 * (window as any).__Zone_disable_requestAnimationFrame = true; // disable patch requestAnimationFrame
 * (window as any).__Zone_disable_on_property = true; // disable patch onProperty such as onclick
 * (window as any).__zone_symbol__UNPATCHED_EVENTS = ['scroll', 'mousemove']; // disable patch specified eventNames
 *
 *  in IE/Edge developer tools, the addEventListener will also be wrapped by zone.js
 *  with the following flag, it will bypass `zone.js` patch for IE/Edge
 *
 *  (window as any).__Zone_enable_cross_context_check = true;
 *
 */

/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
import '@angular/localize/init'; 
import 'node_modules/zone.js/dist/task-tracking';
(window as any).global = window;
// import 'zone.js/dist/zone'; // Included with Angular CLI.

/***************************************************************************************************
 * APPLICATION IMPORTS
 */

/***************************************************************************************************
 * SCULLY IMPORTS
 */
// tslint:disable-next-line: align

This is my test.ts

import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting,
} from '@angular/platform-browser-dynamic/testing';
import 'node_modules/zone.js/dist/async-test';
import 'node_modules/zone.js/dist/fake-async-test';
import 'node_modules/zone.js/dist/jasmine-patch';
import 'node_modules/zone.js/dist/long-stack-trace-zone';
import 'node_modules/zone.js/dist/proxy';
import 'node_modules/zone.js/dist/sync-test';
import 'node_modules/zone.js/dist/zone';
import 'node_modules/zone.js/dist/zone-testing';

(window as any).global = window;
declare let Zone: any;
declare const require: {
  context(path: string, deep?: boolean, filter?: RegExp): {
    keys(): string[];
    <T>(id: string): T;
  };
};

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting(),
);
// Then we find all the tests.
const context = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);

and after running ng test, getting error

Uncaught ReferenceError: Zone is not defined
  at http://localhost:9876/_karma_webpack_/polyfills.js:1024:5
  
  ReferenceError: Zone is not defined
      at Object.<anonymous> (http://localhost:9876/_karma_webpack_/polyfills.js:1024:5)
      at http://localhost:9876/_karma_webpack_/polyfills.js:946:37
      at Object.FGvd (http://localhost:9876/_karma_webpack_/polyfills.js:950:2)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/polyfills.js:20:30)
      at Module.hN/g (http://localhost:9876/_karma_webpack_/polyfills.js:2472:97)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/polyfills.js:20:30)
      at Object.0 (http://localhost:9876/_karma_webpack_/polyfills.js:180:1)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/polyfills.js:20:30)
      at http://localhost:9876/_karma_webpack_/polyfills.js:84:18
      at http://localhost:9876/_karma_webpack_/polyfills.js:87:10

Chrome Headless 88.0.4324.182 (Linux x86_64) ERROR
  Uncaught ReferenceError: Zone is not defined
  at http://localhost:9876/_karma_webpack_/polyfills.js:1024:5
  
  ReferenceError: Zone is not defined
      at Object.<anonymous> (http://localhost:9876/_karma_webpack_/polyfills.js:1024:5)
      at http://localhost:9876/_karma_webpack_/polyfills.js:946:37
      at Object.FGvd (http://localhost:9876/_karma_webpack_/polyfills.js:950:2)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/polyfills.js:20:30)
      at Module.hN/g (http://localhost:9876/_karma_webpack_/polyfills.js:2472:97)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/polyfills.js:20:30)
      at Object.0 (http://localhost:9876/_karma_webpack_/polyfills.js:180:1)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/polyfills.js:20:30)
      at http://localhost:9876/_karma_webpack_/polyfills.js:84:18
      at http://localhost:9876/_karma_webpack_/polyfills.js:87:10

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by aanchal88** [comment]
While running ng test, I faced the issue that zone is not defined and that too in the test.ts file. I have provided the test.ts file please let me know what else I have to provide.

**Comment by AndrewKushnir** [comment]
@aanchal88 in order to investigate the problem, we'd need a repro in a form of a [Stackblitz](https://stackblitz.com/) demo or a GitHub repo (with minimal setup and only relevant code). 

Also after looking at the error, it seems like it's a configuration problem, not a bug in Angular/ZoneJS. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
