### ISSUE TITLE
HttpClient get cannot parametrized

### ISSUE THREAD

**Issue by leomayer** [angular/angular#41951]
# Bug Report

### Affected Package
The issue is caused by package @angular/common in the class http.d.ts

### Description
The methods in http:HttClient#get cannot be parameterized as soon as the `responseType` `text` is interfered. The version without parameter allows setting the `responseType` to `text`

It would be great to have the same functionality independent if parameters are present or not. Especially since the error messages are misleading.

## Minimal Reproduction
```
 constructor(private http: HttpClient) { }
test(){
this.http.get<string>(this.myURL, {responseType: 'text'} )
}
```

## Exception or Error
The compiler cannot find the appropriate overload.
```
  Overload 1 of 15, '(url: string, options: { headers?: HttpHeaders | { [header: string]: string | string[]; }; observe: "events"; params?: HttpParams | { [param: string]: string | string[]; }; reportProgress?: boolean; responseType?: "json"; withCredentials?: boolean; }): Observable<...>', gave the following error.
    Type '"text"' is not assignable to type '"json"'.
  Overload 2 of 15, '(url: string, options: { headers?: HttpHeaders | { [header: string]: string | string[]; }; observe: "response"; params?: HttpParams | { [param: string]: string | string[]; }; reportProgress?: boolean; responseType?: "json"; withCredentials?: boolean; }): Observable<...>', gave the following error.
    Type '"text"' is not assignable to type '"json"'.
  Overload 3 of 15, '(url: string, options?: { headers?: HttpHeaders | { [header: string]: string | string[]; }; observe?: "body"; params?: HttpParams | { [param: string]: string | string[]; }; reportProgress?: boolean; responseType?: "json"; withCredentials?: boolean; }): Observable<...>', gave the following error.
    Type '"text"' is not assignable to type '"json"'.
```

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.2
Node: 15.11.0
OS: linux x64

Angular: 11.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.2 (cli-only)
@angular-devkit/build-angular   0.1102.2
@angular-devkit/core            11.2.2
@angular-devkit/schematics      11.2.2
@angular/cli                    11.2.2
@schematics/angular             11.2.2
@schematics/update              0.1102.2
rxjs                            6.6.6
typescript                      4.0.2

</code></pre>

**Comment by JoostK** [comment]
The problem you're having is that the `HttpClient.get` overload that takes `responseType: 'text'` is not generic; its response body is always `string`. Your usage of an explicit `<string>` generic type confuses TypeScript as to what overload to select, as it only looks for the overloads which take a generic type.

**Comment by JoostK** [comment]
Oh, sorry, after reading the description again this is precisely what you already pointed out.

**Comment by alxhub** [comment]
I suppose in theory we could type that particular overload as `<T extends string = string>`, but I think this is tricky path to walk. Overload resolution is already pretty complex in TypeScript and has a lot of weird corner cases and unintuitive behaviors - I think we should err on the side of simplicity and leave the non-generic signatures non-generic.

**Comment by leomayer** [comment]
If it's only for the string why not provide a simple specific parameter like `<string>`?

I don't see how this makes the whole code over complicated. 

Anyway - when you are not used to the type of complains from the compiler one has a hard time to figure what's wrong when you refactor a piece of code.
