### ISSUE TITLE
When is the release for Angular 12 planned?

### ISSUE THREAD

**Issue by vj619vj** [angular/angular#41963]
When is the release for Angular 12 planned? 
Kindly shed some light on the release timelines for Angular 12 as we are planning to migrate our current project to Angular 12.

**Comment by literalpie** [comment]
According to [this](https://docs.google.com/document/d/1rC5dz7AkCZP813daT_bccbS-20OLmXgBVi50CSKx148/pub) the release is on track for May 12th.

**Comment by petebacondarwin** [comment]
Yes the release of 12.0.0 is still on schedule.
