### ISSUE TITLE
Add clarity to bundle sizes reduction in strict mode guide for v12

### ISSUE THREAD

**Issue by twerske** [angular/angular#41966]
# Docs or angular.io Bug Report

### Description
Developers looking into strict mode for the first time with v12 have some confusion over the reduction in bundle size in the [guide](https://angular.io/guide/strict-mode):
```
Bundle size budgets have been reduced by ~75%.
```
We should add clarity that this is just a 75% reduction in the `angular.json` predefined error and warning budgets *during ng new only* from:
- 2MB warning and 5MB error budget for the initial JavaScript we send to the browser
- 6KB warning and 10KB error budget for the styles of any component

to:
- 500KB warning and 1MB error budget for the initial JavaScript we send to the browser
- 2KB warning and 4KB error budget for the styles of any component

and does not edit an app migrating to strict mode's budget size to 75% of it's original value.

### What's the affected URL?**
https://angular.io/guide/strict-mode

**Comment by johnpapa** [comment]
Much clearer.  Thank you
