### ISSUE TITLE
Route definitions that have both redirectTo and data ignore the data property

### ISSUE THREAD

**Issue by adamdport** [angular/angular#41968]
# Bug Report

### Affected Package

 The issue is caused by package @angular/....
The issue is caused by package @angular/router

### Is this a regression?

Not that I'm aware

### Description
If a route is defined with both `redirectTo` and `data` properties defined, the redirect works but the data is lost.

## Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-ucv5aw?file=src/app/app.component.html

## Exception or Error
<pre><code>

</code></pre>

## Your Environment

**Angular Version:**
<pre><code>
    "@angular/animations": "^11.0.8",
    "@angular/common": "^11.0.8",
    "@angular/compiler": "^11.0.8",
    "@angular/core": "^11.0.8",
    "@angular/forms": "^11.0.8",
    "@angular/platform-browser": "^11.0.8",
    "@angular/platform-browser-dynamic": "^11.0.8",
    "@angular/router": "^11.0.8",

</code></pre>

**Anything else relevant?**

I see in the source that [Angular will throw helpful errors if certain combinations of properties are used together](https://github.com/angular/angular/blob/a92a89b0eb127a59d7e071502b5850e57618ec2d/packages/router/src/utils/config.ts#L45-L66). If it is decided that this is working as intended and `redirectTo` and `data` should _not_ be used together, I'd ask that another warning message is added there to warn developers that it won't work.

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
