### ISSUE TITLE
Angular 9 Upgrade leading to App crash

### ISSUE THREAD

**Issue by sanumolu90** [angular/angular#41965]
# Bug Report

### Description
Hey Team, recently we upgrade our application from Angular 7 -> 9 and once we deploy the application to our production environment, we started seeing an increase in the memory consumption eventually leading to a crash. We didn't face any memory issues with the Angular 7 version.

We were not able to replicate the issue in our lower environments even with the same amount of data. We tried few things to identify or replicate the problem, without any success

- Check if there were any upgraded dependencies that might be the root cause of the memory leak.
- Take memory snapshots and CPU profiles to further see what is taking up memory when the application is being hit.

It would be helpful if you have suggestions on how to find any solution to our problem?

## Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.1.15
Node: 10.15.3
OS: darwin x64

Angular: 9.1.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.901.15
@angular-devkit/build-angular              0.901.15
@angular-devkit/build-optimizer            0.901.15
@angular-devkit/build-webpack              0.901.15
@angular-devkit/core                       9.1.15
@angular-devkit/schematics                 9.1.15
@angular/cli                               9.1.15
@angular/platform-server                   9.1.6
@ngtools/webpack                           9.1.15
@nguniversal/builders                      10.0.0-rc.0
@nguniversal/common                        10.0.0-rc.0
@nguniversal/express-engine                10.0.0-rc.0
@nguniversal/module-map-ngfactory-loader   7.0.2
@schematics/angular                        9.1.15
@schematics/update                         0.901.15
rxjs                                       6.6.7
typescript                                 3.8.3
webpack                                    4.42.0
</code></pre>

**Comment by AndrewKushnir** [comment]
Hi @sanumolu90, I'd recommend trying to upgrade to the most recent version (either latest `11.2.13` or release candidate version `12.0.0-rc.2`) and see if that improves the situation (there were a few memory leak fixes that landed since v9). Thank you.

**Comment by sanumolu90** [comment]
Thanks, @AndrewKushnir. Do you suggest any path based on your experience that we should take while upgrading to the latest version? Anything to avoid?

**Comment by AndrewKushnir** [comment]
@sanumolu90 you can find more info about upgrading Angular in our docs here: https://angular.io/guide/updating-to-version-11.

**Comment by AndrewKushnir** [comment]
Closing this issue for now, please reopen (or create a new ticket) if the problem still exists after upgrading to the most recent version (v12.1.1 at this moment).
