### ISSUE TITLE
Detecting Changes on actions triggered outside Component

### ISSUE THREAD

**Issue by jpsfs** [angular/angular#4197]
Hi,

Found an issue when updating a component's property, that is bound to the template. It appears the ChangeDetector is not detecting the changes.

Here is a plunker that shows this happening: http://plnkr.co/edit/j5YLW0mL3bCBslC5mkzJ?p=preview

This only happens when the event is triggered outside angular. If you comment line 62 and uncomment line 45 everything works as expected. **This was working on alpha 35**, has you can test easily on the example.

Not sure this is a bug or a known limitation. Nevertheless, how should we proceed in these situations?

Putting @pkozlowski-opensource in CC, we have talked about this on gitter although I didn't had a plunker that reproduced the issue at that time.

PS: Don't mind the extreme complexity for such a simple use case. The idea was to incorporate everything that is used (jquery, EventEmitter2) in the real world scenario where I first detected the issue.

**Comment by mhevery** [comment]
This works as expected. The issue is that bootstrap returns a promise which is outside the angular zone, and as a result the `then`s also execute outside the zone. The plan is to remove the Promise return from here to prevent these kinds of issues.
