### ISSUE TITLE
AIO docs generation on local failing

### ISSUE THREAD

**Issue by ajitsinghkaler** [angular/angular#41979]
# Bug Report
When I run yarn setup on my local machine(Linux 20.04) for AIO folder it fails in doc generation. I tries to run yarn docs-only that also fails on the step "generateKeywordsProcessor" I'm not sure why. I ran yarn test also if the tests are working fine but it also failed. I'm attaching the logs if they can be of any help.

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
 A clear and concise description of the problem...

## Minimal Reproduction

 https://stackblitz.com/...

Run Yarn setup or yarn docs-only

## Exception or Error
<pre><code>

test logs
`yarn docs-test
yarn run v1.22.10
$ node tools/transforms/test.js
Randomized with seed 24532
Started
......................................................Building marketing docs
error:   Error running processor "generateKeywordsProcessor":
Not supported
error:   Failed to process the docs
Error generating docs Error: Error running processor "generateKeywordsProcessor":
Not supported
    at Object.$process (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.js:25:31)
    at /home/ajit/Documents/angular/aio/node_modules/dgeni/lib/Dgeni.js:195:54
FBuilding API docs for forms
error:   Error running processor "generateKeywordsProcessor":
Not supported
error:   Failed to process the docs
Error generating docs Error: Error running processor "generateKeywordsProcessor":
Not supported
    at Object.$process (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.js:25:31)
    at /home/ajit/Documents/angular/aio/node_modules/dgeni/lib/Dgeni.js:195:54
FBuilding guide doc: architecture.md
error:   Error running processor "generateKeywordsProcessor":
Not supported
error:   Failed to process the docs
Error generating docs Error: Error running processor "generateKeywordsProcessor":
Not supported
    at Object.$process (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.js:25:31)
    at /home/ajit/Documents/angular/aio/node_modules/dgeni/lib/Dgeni.js:195:54
FBuilding tutorial docs
error:   Error running processor "generateKeywordsProcessor":
Not supported
error:   Failed to process the docs
Error generating docs Error: Error running processor "generateKeywordsProcessor":
Not supported
    at Object.$process (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.js:25:31)
    at /home/ajit/Documents/angular/aio/node_modules/dgeni/lib/Dgeni.js:195:54
FBuilding tutorial docs
The following example files are referenced in this tutorial:
 - examples/toh-pt5/src/app/app-routing.module.0.ts
 - examples/toh-pt5/src/app/app-routing.module.1.ts
 - examples/toh-pt5/src/app/app-routing.module.ts
 - examples/toh-pt5/src/app/app-routing.module.ts
 - examples/toh-pt5/src/app/app-routing.module.ts
 - examples/toh-pt5/src/app/app.component.html
 - examples/toh-pt5/src/app/app.component.html
 - examples/toh-pt5/src/app/dashboard/dashboard.component.1.html
 - examples/toh-pt5/src/app/dashboard/dashboard.component.ts
 - examples/toh-pt5/src/app/dashboard/dashboard.component.css
 - examples/toh-pt5/src/app/dashboard/dashboard.component.ts
 - examples/toh-pt5/src/app/app-routing.module.ts
 - examples/toh-pt5/src/app/app-routing.module.ts
 - examples/toh-pt5/src/app/app-routing.module.ts
 - examples/toh-pt5/src/app/app.component.html
 - examples/toh-pt5/src/app/app-routing.module.ts
 - examples/toh-pt5/src/app/app-routing.module.ts
 - examples/toh-pt5/src/app/app-routing.module.ts
 - examples/toh-pt5/src/app/dashboard/dashboard.component.html
 - examples/toh-pt4/src/app/heroes/heroes.component.html
 - examples/toh-pt5/src/app/heroes/heroes.component.html
 - examples/toh-pt5/src/app/heroes/heroes.component.ts
 - examples/toh-pt5/src/app/hero-detail/hero-detail.component.ts
 - examples/toh-pt5/src/app/hero-detail/hero-detail.component.ts
 - examples/toh-pt5/src/app/hero-detail/hero-detail.component.ts
 - examples/toh-pt5/src/app/hero.service.ts
 - examples/toh-pt5/src/app/hero-detail/hero-detail.component.html
 - examples/toh-pt5/src/app/hero-detail/hero-detail.component.ts
 - examples/toh-pt5/src/app/app-routing.module.ts
 - examples/toh-pt5/src/app/app.module.ts
 - examples/toh-pt5/src/app/hero.service.ts
 - examples/toh-pt5/src/app/app.component.html
 - examples/toh-pt5/src/app/app.component.css
 - examples/toh-pt5/src/app/dashboard/dashboard.component.html
 - examples/toh-pt5/src/app/dashboard/dashboard.component.ts
 - examples/toh-pt5/src/app/dashboard/dashboard.component.css
 - examples/toh-pt5/src/app/heroes/heroes.component.html
 - examples/toh-pt5/src/app/heroes/heroes.component.ts
 - examples/toh-pt5/src/app/heroes/heroes.component.css
 - examples/toh-pt5/src/app/hero-detail/hero-detail.component.html
 - examples/toh-pt5/src/app/hero-detail/hero-detail.component.ts
 - examples/toh-pt5/src/app/hero-detail/hero-detail.component.css
error:   Error running processor "generateKeywordsProcessor":
Not supported
error:   Failed to process the docs
Error generating docs Error: Error running processor "generateKeywordsProcessor":
Not supported
    at Object.$process (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.js:25:31)
    at /home/ajit/Documents/angular/aio/node_modules/dgeni/lib/Dgeni.js:195:54
FBuilding guide doc: architecture.md
error:   Error running processor "generateKeywordsProcessor":
Not supported
error:   Failed to process the docs
Error generating docs Error: Error running processor "generateKeywordsProcessor":
Not supported
    at Object.$process (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.js:25:31)
    at /home/ajit/Documents/angular/aio/node_modules/dgeni/lib/Dgeni.js:195:54
FBuilding tutorial docs
The following example files are referenced in this tutorial:
 - examples/toh-pt3/src/app/hero-detail/hero-detail.component.html
 - examples/toh-pt3/src/app/hero-detail/hero-detail.component.ts
 - examples/toh-pt3/src/app/heroes/heroes.component.html
 - examples/toh-pt3/src/app/hero-detail/hero-detail.component.ts
 - examples/toh-pt3/src/app/hero-detail/hero-detail.component.ts
 - examples/toh-pt3/src/app/heroes/heroes.component.html
 - examples/toh-pt3/src/app/heroes/heroes.component.html
 - examples/toh-pt3/src/app/hero-detail/hero-detail.component.ts
 - examples/toh-pt3/src/app/hero-detail/hero-detail.component.html
 - examples/toh-pt3/src/app/heroes/heroes.component.html
 - examples/toh-pt3/src/app/app.module.ts
error:   Error running processor "generateKeywordsProcessor":
Not supported
error:   Failed to process the docs
Error generating docs Error: Error running processor "generateKeywordsProcessor":
Not supported
    at Object.$process (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.js:25:31)
    at /home/ajit/Documents/angular/aio/node_modules/dgeni/lib/Dgeni.js:195:54
FBuilding API docs for forms
error:   Error running processor "generateKeywordsProcessor":
Not supported
error:   Failed to process the docs
Error generating docs Error: Error running processor "generateKeywordsProcessor":
Not supported
    at Object.$process (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.js:25:31)
    at /home/ajit/Documents/angular/aio/node_modules/dgeni/lib/Dgeni.js:195:54
F......................................................................................................................................................FFFFFFFF.FFF..........................................................................................................................................................................................................................................................

Failures:
1) authors-package (integration tests) should generate marketing docs if the "fileChanged" is a marketing doc
  Message:
    Expected spy writeFile to have been called.
  Stack:
    Error: Expected spy writeFile to have been called.
        at <Jasmine>
        at /home/ajit/Documents/angular/aio/tools/transforms/authors-package/index.spec.js:28:28
  Message:
    Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/docs/about.json'.
  Stack:
    Error: Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/docs/about.json'.
        at <Jasmine>
        at /home/ajit/Documents/angular/aio/tools/transforms/authors-package/index.spec.js:29:21
  Message:
    Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/navigation.json'.
  Stack:
    Error: Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/navigation.json'.
        at <Jasmine>
        at /home/ajit/Documents/angular/aio/tools/transforms/authors-package/index.spec.js:30:21
  Message:
    Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/contributors.json'.
  Stack:
    Error: Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/contributors.json'.
        at <Jasmine>
        at /home/ajit/Documents/angular/aio/tools/transforms/authors-package/index.spec.js:31:21
  Message:
    Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/resources.json'.
  Stack:
    Error: Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/resources.json'.
        at <Jasmine>
        at /home/ajit/Documents/angular/aio/tools/transforms/authors-package/index.spec.js:32:21

2) authors-package (integration tests) should generate API doc if the "fileChanged" is an API doc
  Message:
    Expected spy writeFile to have been called.
  Stack:
    Error: Expected spy writeFile to have been called.
        at <Jasmine>
        at /home/ajit/Documents/angular/aio/tools/transforms/authors-package/index.spec.js:73:28
  Message:
    Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/docs/api/forms/FormBuilder.json'.
  Stack:
    Error: Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/docs/api/forms/FormBuilder.json'.
        at <Jasmine>
        at /home/ajit/Documents/angular/aio/tools/transforms/authors-package/index.spec.js:74:21

3) authors-package (integration tests) should generate guide doc if the "fileChanged" is a guide example
  Message:
    Expected spy writeFile to have been called.
  Stack:
    Error: Expected spy writeFile to have been called.
        at <Jasmine>
        at /home/ajit/Documents/angular/aio/tools/transforms/authors-package/index.spec.js:66:28
  Message:
    Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/docs/guide/architecture.json'.
  Stack:
    Error: Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/docs/guide/architecture.json'.
        at <Jasmine>
        at /home/ajit/Documents/angular/aio/tools/transforms/authors-package/index.spec.js:67:21

4) authors-package (integration tests) should generate tutorial docs if the "fileChanged" is the tutorial index
  Message:
    Expected spy writeFile to have been called.
  Stack:
    Error: Expected spy writeFile to have been called.
        at <Jasmine>
        at /home/ajit/Documents/angular/aio/tools/transforms/authors-package/index.spec.js:45:28
  Message:
    Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/docs/tutorial.json'.
  Stack:
    Error: Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/docs/tutorial.json'.
        at <Jasmine>
        at /home/ajit/Documents/angular/aio/tools/transforms/authors-package/index.spec.js:46:21

5) authors-package (integration tests) should generate tutorial docs if the "fileChanged" is a tutorial doc
  Message:
    Expected spy writeFile to have been called.
  Stack:
    Error: Expected spy writeFile to have been called.
        at <Jasmine>
        at /home/ajit/Documents/angular/aio/tools/transforms/authors-package/index.spec.js:38:28
  Message:
    Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/docs/tutorial/toh-pt5.json'.
  Stack:
    Error: Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/docs/tutorial/toh-pt5.json'.
        at <Jasmine>
        at /home/ajit/Documents/angular/aio/tools/transforms/authors-package/index.spec.js:39:21

6) authors-package (integration tests) should generate guide doc if the "fileChanged" is a guide doc
  Message:
    Expected spy writeFile to have been called.
  Stack:
    Error: Expected spy writeFile to have been called.
        at <Jasmine>
        at /home/ajit/Documents/angular/aio/tools/transforms/authors-package/index.spec.js:59:28
  Message:
    Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/docs/guide/architecture.json'.
  Stack:
    Error: Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/docs/guide/architecture.json'.
        at <Jasmine>
        at /home/ajit/Documents/angular/aio/tools/transforms/authors-package/index.spec.js:60:21

7) authors-package (integration tests) should generate tutorial docs if the "fileChanged" is a tutorial example
  Message:
    Expected spy writeFile to have been called.
  Stack:
    Error: Expected spy writeFile to have been called.
        at <Jasmine>
        at /home/ajit/Documents/angular/aio/tools/transforms/authors-package/index.spec.js:52:28
  Message:
    Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/docs/tutorial/toh-pt3.json'.
  Stack:
    Error: Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/docs/tutorial/toh-pt3.json'.
        at <Jasmine>
        at /home/ajit/Documents/angular/aio/tools/transforms/authors-package/index.spec.js:53:21

8) authors-package (integration tests) should generate API doc if the "fileChanged" is an API example
  Message:
    Expected spy writeFile to have been called.
  Stack:
    Error: Expected spy writeFile to have been called.
        at <Jasmine>
        at /home/ajit/Documents/angular/aio/tools/transforms/authors-package/index.spec.js:80:28
  Message:
    Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/docs/api/forms/FormBuilder.json'.
  Stack:
    Error: Expected [  ] to contain '/home/ajit/Documents/angular/aio/src/generated/docs/api/forms/FormBuilder.json'.
        at <Jasmine>
        at /home/ajit/Documents/angular/aio/tools/transforms/authors-package/index.spec.js:81:21

9) generateKeywords processor should use `doc.searchTitle` as the title in the search index
  Message:
    Error: Not supported
  Stack:
    Error: Not supported
        at Object.$process (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.js:25:31)
        at UserContext.<anonymous> (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.spec.js:117:34)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

10) generateKeywords processor should add heading words to the search terms
  Message:
    Error: Not supported
  Stack:
    Error: Not supported
        at Object.$process (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.js:25:31)
        at UserContext.<anonymous> (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.spec.js:128:34)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

11) generateKeywords processor should add member doc properties to the search terms
  Message:
    Error: Not supported
  Stack:
    Error: Not supported
        at Object.$process (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.js:25:31)
        at UserContext.<anonymous> (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.spec.js:147:34)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

12) generateKeywords processor should add inherited member doc properties to the search terms
  Message:
    Error: Not supported
  Stack:
    Error: Not supported
        at Object.$process (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.js:25:31)
        at UserContext.<anonymous> (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.spec.js:211:34)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

13) generateKeywords processor should compute `doc.searchTitle` from the doc properties if not already provided
  Message:
    Error: Not supported
  Stack:
    Error: Not supported
        at Object.$process (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.js:25:31)
        at UserContext.<anonymous> (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.spec.js:101:34)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

14) generateKeywords processor should not collect keywords that look like HTML tags
  Message:
    Error: Not supported
  Stack:
    Error: Not supported
        at Object.$process (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.js:25:31)
        at UserContext.<anonymous> (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.spec.js:83:34)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

15) generateKeywords processor should ignore internal and private exports
  Message:
    Error: Not supported
  Stack:
    Error: Not supported
        at Object.$process (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.js:25:31)
        at UserContext.<anonymous> (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.spec.js:41:34)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

16) generateKeywords processor should ignore docs that are in the `docTypesToIgnore` list
  Message:
    Error: Not supported
  Stack:
    Error: Not supported
        at Object.$process (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.js:25:31)
        at UserContext.<anonymous> (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.spec.js:54:34)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

17) generateKeywords processor should include both stripped and unstripped "ng" prefixed tokens
  Message:
    Error: Not supported
  Stack:
    Error: Not supported
        at Object.$process (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.js:25:31)
        at UserContext.<anonymous> (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.spec.js:234:34)
        at <Jasmine>
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7)

18) generateKeywords processor should generate compressed encoded renderedContent property
  Message:
    Error: Not supported
  Stack:
    Error: Not supported
        at Object.$process (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.js:25:31)
        at UserContext.<anonymous> (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.spec.js:257:34)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

19) generateKeywords processor should not collect keywords from properties that are in the `propertiesToIgnore` list
  Message:
    Error: Not supported
  Stack:
    Error: Not supported
        at Object.$process (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.js:25:31)
        at UserContext.<anonymous> (/home/ajit/Documents/angular/aio/tools/transforms/angular-base-package/processors/generateKeywords.spec.js:68:34)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

474 specs, 19 failures`

yarn docs-only log
`$ dgeni ./tools/transforms/angular.io-package
info:    running processor: readFilesProcessor
info:    running processor: extractJSDocCommentsProcessor
info:    running processor: collectExamples
info:    running processor: readTypeScriptModules
info:    running processor: linkInheritedDocs
info:    running processor: processPseudoClasses
info:    running processor: parseTagsProcessor
info:    running processor: extractTagsProcessor
info:    running processor: codeNameProcessor
info:    running processor: addNotYetDocumentedProperty
info:    running processor: splitDescription
info:    running processor: fixupRealProjectRelativePath
info:    running processor: convertPrivateClassesToInterfacesProcessor
info:    running processor: mergeDecoratorDocs
info:    running processor: extractDecoratedClassesProcessor
info:    running processor: extractPipeParams
info:    running processor: filterMembers
info:    running processor: removeInjectableConstructors
info:    running processor: createOverviewDump
info:    running processor: markBarredODocsAsPrivate
info:    running processor: mergeParameterInfo
info:    running processor: addMetadataAliasesProcessor
info:    running processor: addGlobalApiDataProcessor
info:    running processor: collectPackageContentDocsProcessor
info:    running processor: computeIdsProcessor
info:    running processor: processAliasDocs
info:    running processor: processPackages
info:    running processor: checkContentRules
info:    running processor: filterContainedDocs
info:    running processor: filterPrivateDocs
info:    running processor: computePathsProcessor
info:    running processor: disambiguateDocPathsProcessor
info:    running processor: updateGlobalApiPathProcessor
info:    running processor: processNgModuleDocs
info:    running processor: filterHiddenCommands
info:    running processor: createSitemap
info:    running processor: computeStability
info:    running processor: generateApiListDoc
info:    running processor: matchUpDirectiveDecorators
info:    running processor: computeApiBreadCrumbs
info:    running processor: processClassLikeMembers
info:    running processor: simplifyMemberAnchors
info:    running processor: processCliContainerDoc
info:    running processor: processCliCommands
info:    running processor: processErrorDocs
info:    running processor: processErrorsContainerDoc
info:    running processor: processNavigationMap
info:    running processor: renderDocsProcessor
info:    running processor: unescapeCommentsProcessor
info:    running processor: inlineTagProcessor
info:    running processor: renderExamples
info:    running processor: checkForUnusedExampleRegions
info:    running processor: copyContentAssetsProcessor
info:    running processor: postProcessHtml
info:    running processor: computeSearchTitleProcessor
info:    running processor: generateKeywordsProcessor
error:   Error running processor "generateKeywordsProcessor":
Not supported
error:   Failed to process the docs
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
</code></pre>

## Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by gkalpak** [comment]
Thx for reporting this, @ajitsinghkaler!
What version of Node.js are you using?

**Comment by ajitsinghkaler** [comment]
v12.14.1

**Comment by gkalpak** [comment]
Can you try with Node.js v14?

**Comment by ajitsinghkaler** [comment]
It worked Thanks @gkalpak

**Comment by gkalpak** [comment]
Thx for confirming, @ajitsinghkaler :rocket:

Maybe we should update [aio/package.json > engines][1] to require Node.js >=14.


[1]: https://github.com/angular/angular/blob/e29eb8abfbfdfb793e08ac88e14b7ba6d2ff2136/aio/package.json#L82

**Comment by ajitsinghkaler** [comment]
That sure will be helpful

**Comment by ajitsinghkaler** [comment]
If we want to document that I can re open this issue

**Comment by petebacondarwin** [comment]
@ajitsinghkaler - rather than opening this one. Perhaps you could open a new issue to update the AIO package.json engines to the necessary minimum? Or even better just create a PR to fix it 😄
