### ISSUE TITLE
Content projection with ngIf and asyncPipe: Observables still subscribed to even though they are not in the DOM

### ISSUE THREAD

**Issue by biltongza** [angular/angular#41985]
# Bug Report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?
Not sure

### Description
Using asyncPipe on an observable that is ngIf'd out of the DOM still seems to fire the observable when combined with content projection (`ng-content`).
I expected the observable to only be subscribed to when the content in the expansion bar is expanded (and thus present in the DOM).

This is a simplified example, where in my application because of this we are seeing multiple network calls happening upfront where we only want them to happen upon expansion of the expansion bar.

## Minimal Reproduction
https://stackblitz.com/edit/angular-observable-ngif-behaviour
If you inspect the DOM you will note that the contents of the expansion bars are not present, but the console shows that the observables fired.

**Comment by mlc-mlapis** [comment]
@biltongza Content projection elements are instantiated in the context and time of its parent host, and this process is not directly related to the DOM manipulation (like `*ngIf` sensitivity or so).

**Comment by biltongza** [comment]
That feels a bit counterintuitive, how should I accomplish this otherwise?

**Comment by mlc-mlapis** [comment]
@biltongza It's by design now.

**Comment by ramanathan23** [comment]
Content projection will be resolved at first before projecting it. For these kind of scenarios we can use ng-templates which we can have better control over ng-content. Please have a look at the below link, 

https://stackblitz.com/edit/angular-observable-ngif-behaviour-rlhwzm?file=src%2Fapp%2Fapp.component.ts

I modified your code with ng-template for the use case.

![image](https://user-images.githubusercontent.com/7834282/117550962-cac21c80-b060-11eb-847c-ee707c815059.png)

**Comment by jelbourn** [comment]
Yeah, as mentioned above, this is working as expected. The content of a component is always instantiated even if that content would never be projected/rendered anywhere. We have a new doc on content projection with v12 that goes into this in more depth: https://next.angular.io/guide/content-projection
