### ISSUE TITLE
The shell code in the documentation is not visible

### ISSUE THREAD

**Issue by lsbbd** [angular/angular#41984]
# Docs or angular.io Bug Report

### Description

All the shell code in the `Router tutorial: tour of heroes` chapter is invisible

### What's the affected URL?**

https://angular.io/guide/router-tutorial-toh

### Reproduction Steps**

- Click https://angular.io/guide/router-tutorial-toh
- See the section where there are examples of shell commands

### Expected vs Actual Behavior**

- Actual Behavior: Shell commands are not visible
- Expected: Shell commands can be displayed normally

## Screenshot

![image](https://user-images.githubusercontent.com/18237955/117422571-54cf8f80-af52-11eb-949d-723e8c66b288.png)

## Exception or Error
![image](https://user-images.githubusercontent.com/18237955/117422635-6b75e680-af52-11eb-86c8-d9e2d03e8f70.png)

### Browser info

- system: win10 
- browser: chrome  90.0.4430.93

**Comment by petebacondarwin** [comment]
Good spot @lsbbd - the text is actually there but the styling is off, which makes the foreground color and background color the same!
