### ISSUE TITLE
Uncaught Error: Type HotelComponent does not have 'ɵmod' property.

### ISSUE THREAD

**Issue by Arie-Bervoets** [angular/angular#41983]
Where can I find any information about this message: "**core.js:1141 Uncaught Error: Type HotelComponent does not have 'ɵmod' property.**"?

**Comment by petebacondarwin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#submit-issue) to understand why we can't act on issues that are lacking important information.

The `ɵmod` property should appear on NgModule classes after they are compiled by Ivy. It is surprising for it to be on a component class. Without knowing what versions you are using, what build tools you are using, what this `HotelComponent` identifies and how you are using it in your application, there is not much more we can provide. Even a better stack trace would be more helpful. 

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
