### ISSUE TITLE
angular.io search result return links with production urls instead of relative urls

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#4199]
When I spin up a local harp server and try to search for an api doc, I'm redirected to `https://angular.io/` when I click on any of the links. This makes looking up things in the local version of the docs impossible.

It would be great if the search results returned relative urls.

**Comment by IgorMinar** [comment]
@alexwolfe are you the right owner of this?

**Comment by naomiblack** [comment]
we currently use a third-party (swiftype) for in-site search. this gives us granular control over search on angular.io but a known limitation is that you have to push to production to review. this is probably a low priority to fix right now.

**Comment by vicb** [comment]
Wring repo, use https://github.com/angular/angular.io if still an issue
