### ISSUE TITLE
Need Info about using Angular 11 SPA without Typescript 

### ISSUE THREAD

**Issue by krithivasanchandran** [angular/angular#41997]
Angular 11 (angular.io) official documentations states only about using Angular 11 only with typescript (code samples also in typescript) .

I would require official documentation url on using Angular 11 with ES5 or ES6 - Folder paths , configurations used or any skeleton code sample repos to start off with. 

Thanks

**Comment by krithivasanchandran** [comment]
Any pointers will be good.

**Comment by petebacondarwin** [comment]
Angular is not really designed to work without TypeScript, as you really need the Angular compiler to process the decorators and to compile the templates into code. The Angular AOT compiler is an extension of the TypeScript compiler. While it is feasible to hack together non-TS code that the Angular JIT compiler could consume, it is not recommended, nor really supported. And further, it is not a direction that the team want to move or encourage users to try.

If you want to dig further into this, I would recommend asking on one of the support channels, perhaps the [Angular DIscord](https://discord.gg/angular).
