### ISSUE TITLE
HTTP Module using post updaload file

### ISSUE THREAD

**Issue by Wendingchuan** [angular/angular#42002]
```
Angular CLI: 11.2.6
Node: 12.13.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.6 (cli-only)
@angular-devkit/core         11.2.6 (cli-only)
@angular-devkit/schematics   11.2.6 (cli-only)
@schematics/angular          11.2.6 (cli-only)
@schematics/update           0.1102.6 (cli-only)

```

# Bug Report

there is no problem in normal

```
this.http.post(_url,formdata) 
```

![image](https://user-images.githubusercontent.com/73323618/117535133-fb856000-b026-11eb-8dc4-f7ead5aa3ded.png)

if I add  header in options, the formdata will  exsit request payload
suppost exsit formdata file: (binary)

```
this.http.post(_url,formdata,{
       Authorization: this.commonService.getToken() || ''
  })
```

![image](https://user-images.githubusercontent.com/73323618/117534841-b3197280-b025-11eb-8a27-a0247fcb5e2a.png)

**Comment by petebacondarwin** [comment]
I'm sorry but we don't understand the problem you are reporting.

Are you saying that if you add a content-type to a HTTP POST request then the form data is no longer sent?

**Comment by Wendingchuan** [comment]
sorry,  I delete the content-type,  I try to add a Authorization to Header, then form date  becomes request payload

**Comment by Wendingchuan** [comment]
sorry, It's my mistake, I deleted the content-type, then code working
