### ISSUE TITLE
Angular router CLI code snippets are invisible

### ISSUE THREAD

**Issue by MajesticString** [angular/angular#42007]
# Docs or angular.io Bug Report

### Description

On the routing guide, the code snippets for the CLI are the same color as the background

### What's the affected URL?**
 https://angular.io/guide/router

### Reproduction Steps**

Head to https://angular.io/guide/router
Then look for a CLI snippet

## Screenshot

![image](https://user-images.githubusercontent.com/66224939/117556869-51a3d480-b022-11eb-9bf5-8ca3708562c9.png)
With the text highlighted:
![image](https://user-images.githubusercontent.com/66224939/117556912-b2cba800-b022-11eb-8145-71832c931619.png)

### Browser info
Window 10 20H2 running
Chrome 91, Edge 91, and Firefox 89

**Comment by JoostK** [comment]
Thank you for reporting. This has already been fixed in #41986 but pending a backport to the stable site in #41994. As an alternative you can look at the RC site where it did get fixed: https://rc.angular.io/guide/router
