### ISSUE TITLE
There is a parameter description that does not exist in the example command

### ISSUE THREAD

**Issue by lsbbd** [angular/angular#42013]
# Docs or angular.io Bug Report

### Description

The explanation of the command in the ‘Developer Guides / Service Worker & PWA / App Shell / Step 2: Create the app shell’ chapter is confusing

### What's the affected URL?**

https://angular.io/guide/app-shell#step-2-create-the-app-shell

### Reproduction Steps**

- open https://angular.io/guide/app-shell#step-2-create-the-app-shell
- see the example command

### Expected vs Actual Behavior**

- Expected: The example command is consistent with its explanation
- Actual: There is a parameter description that does not exist in the example command

## Screenshot

![image](https://user-images.githubusercontent.com/18237955/117601841-d22d1700-b181-11eb-977c-f7e494b6e400.png)

## Exception or Error
<pre><code>

</code></pre>

### Anything else relevant?

There is no such problem in the V8 version of the document

![image](https://user-images.githubusercontent.com/18237955/117601903-f7218a00-b181-11eb-87e3-415572b7f1a6.png)

**Comment by petebacondarwin** [comment]
Thanks for reporting this @lsbbd .

It is already fixed in `master`, which can be seen at https://next.angular.io/guide/app-shell#step-2-create-the-app-shell.
Since v12.0.0 will be released this week, I am going to close this issue, as it is effectively resolved.
