### ISSUE TITLE
header not passing when httpclient sending request  

### ISSUE THREAD

**Issue by Sanjayavidbrio** [angular/angular#42012]
angular 11.2.13

```
import { HttpClient, HttpHeaders, HttpParams,HttpParamsOptions  } from '@angular/common/http';

 httpHeader = {
    headers: new HttpHeaders({
      'Content-Type': 'application/json2',
      "x-rapidapi-key": "341a24f84fmsh11a160f27832cc6p17baf1jsn8XXXXXXXXXX",

    })
  }  

```

# Bug Report

![image](https://user-images.githubusercontent.com/78072091/117581562-0de0c600-b11b-11eb-9c09-09f4c367e25a.png)

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
i don't know  i am new in angular 

yes i create new fresh angular repo but still same issue 
Issues that don't have enough info and can't be reproduced will be closed.

## Your Environment

**Angular Version:**  11.2.13
![image](https://user-images.githubusercontent.com/78072091/117581545-ea1d8000-b11a-11eb-85a7-e589e4eb66b3.png)

</code></pre>

**Comment by petebacondarwin** [comment]
I cannot reproduce this issue. Here is a StackBlitz demonstrating it working as expected: https://stackblitz.com/edit/angular-ivy-jr3iqp?file=src%2Fapp%2Fapp.component.ts

![Screenshot 2021-05-09 at 18 49 08](https://user-images.githubusercontent.com/15655/117581901-440c4e80-b0f7-11eb-877a-e04bca96a478.png)


Perhaps you need support in how to use the `HttpClient`. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).
