### ISSUE TITLE
enableDebugTools no longer works with result of bootstrap

### ISSUE THREAD

**Issue by hterkelsen** [angular/angular#4202]
`enableDebugTools` (documented here: https://github.com/angular/angular/blob/master/TOOLS_JS.md) takes an ApplicationRef, but `bootstrap` returns a ComponentRef

**Comment by hterkelsen** [comment]
cc @yjbanov

**Comment by yjbanov** [comment]
Fixed by https://github.com/angular/angular/pull/4203
