### ISSUE TITLE
The new chnagelog format does not highlight the linked issues and commits

### ISSUE THREAD

**Issue by stagefright5** [angular/angular#42043]
# Bug Report

### Is this a regression?

No. But, it is used to be like this:
![image](https://user-images.githubusercontent.com/15051871/117815737-6501aa80-b283-11eb-8a4c-3d9f85d48f25.png)

### Description
As you can see in the below image, the issues and commits mentioned does not actually link to the respctive resources (as it used to before)

![image](https://user-images.githubusercontent.com/15051871/117815346-ffadb980-b282-11eb-8f38-4e7528712c9b.png)

## Minimal Reproduction
go to https://github.com/angular/angular/blob/master/CHANGELOG.md#1200-rc3-2021-05-10

## Your Environment

Irrelevant

**Comment by JoostK** [comment]
The changelog template has been updated in #42732 to make the commit and PR number links again. The existing changelog entries were also updated to have links, so this has been resolved.
