### ISSUE TITLE
Docs/Testing: Can't resolve all parameters for SomeDirective(?).

### ISSUE THREAD

**Issue by infacto** [angular/angular#42044]
The test example here does not work: https://angular.io/guide/testing-attribute-directives You'll get an error like:

> Can't resolve all parameters for SomeDirective(?).

Because [ElementRef](https://angular.io/api/core/ElementRef) does not resolved / work. I can't find a solution or explanation.

**Comment by AndrewKushnir** [comment]
Hi @infacto, 

Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

Could you please provide a minimal repro (in a form of a [Stackblitz](https://stackblitz.com/) demo), so that we can look at this issue?

**Comment by infacto** [comment]
Here is a demo from the code of [this docs page](https://angular.io/guide/testing-attribute-directives):

**demo-test/demo.directive.ts**

```ts
import { Directive, ElementRef, Input, OnChanges } from '@angular/core';

@Directive({ selector: '[highlight]' })
export class DemoDirective implements OnChanges {
  public defaultColor = 'rgb(211, 211, 211)';

  @Input('highlight') public bgColor: string;

  constructor(private el: ElementRef) {
    el.nativeElement.style.customProperty = true;
  }

  public ngOnChanges(): void {
    this.el.nativeElement.style.backgroundColor = this.bgColor || this.defaultColor;
  }
}
```

**demo-test/demo.module.ts**

```ts
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { IonicModule } from '@ionic/angular';
import { DemoDirective } from './demo.directive';

@NgModule({
  imports: [CommonModule, IonicModule],
  declarations: [DemoDirective],
  exports: [DemoDirective],
})
export class DemoModule {}
```

**demo.directive.spec.ts**

```ts
import { Component, DebugElement } from '@angular/core';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { By } from '@angular/platform-browser';
import { DemoDirective } from './demo.directive';

@Component({
  template: `<h2 highlight="yellow">Something Yellow</h2>
    <h2 highlight>The Default (Gray)</h2>
    <h2>No Highlight</h2>
    <input #box [highlight]="box.value" value="cyan" />`,
})
class TestComponent {}

let fixture: ComponentFixture<TestComponent>;
let des: DebugElement[];
let bareH2: DebugElement;

beforeEach(() => {
  fixture = TestBed.configureTestingModule({
    declarations: [DemoDirective, TestComponent],
  }).createComponent(TestComponent);

  fixture.detectChanges();

  des = fixture.debugElement.queryAll(By.directive(DemoDirective));
  bareH2 = fixture.debugElement.query(By.css('h2:not([highlight])'));
});

it('should have three highlighted elements', () => {
  expect(des.length).toBe(3);
});
```

This results in: 

> Can't resolve all parameters for DemoDirective: (?).

The `?` means the `ElementRef` which does not resolved / injected in the unit tests.

I tested it in a fresh new Angular project and cannot reproduce it. *sigh*
