### ISSUE TITLE
Support @Input() default values

### ISSUE THREAD

**Issue by carguellos** [angular/angular#42048]
# Feature Request

### Relevant Package
Main component API, Input on Angular/Core

### Description
It would be very helpful to support @Input() default values. There are very complicated and unnatural workarounds for this but it would be a lot better if this is just a simple native feature.

### Describe the solution you'd like
@Input() myValue: string = 'abcd'
If there's an input value this value gets an override, else the component works with the default value.

### Describe alternatives you've considered
There are complex implementations for this using NgOnChanges. For someone who is constantly working on design systems, this is very innefficient

**Comment by mlc-mlapis** [comment]
@carguellos But it works as you want: `@Input() myValue = 'abcd';
