### ISSUE TITLE
SubForm Field Validators, but Parent has no Validator

### ISSUE THREAD

**Issue by nickwinger** [angular/angular#42051]
Hello,

i'm currently a little bit unsure what is going on.
I have made a reusable Reactive SubForm Component let's call it Adress.
It has Validators on it, so that the required fields for an Adress are there.
However when i use this subForm in a parent form, and i set no Validator.required on the adress field of the parent Form the subForm is still invalid and so the parentForm, although on the parentForm i have no validators.

I think something is not running correct here, because when i say on the parent i don't want validator on the adress field, the subForm should ignore it's validators, or at least set itself to valid.

I think it would be bad programming if the subForm has to listen for the required Validator on the parent and then set the field to be required or not...

Also i don't know how to listen if the parentForm has a Validator on this field or not.

Please give me any hints into the right direction,

Thanks,
Nick

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
