### ISSUE TITLE
Template directives should throw if they are using without the template element or *

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#4205]
A common mistake is to forget to add `*` before `ng-if`. If a developer makes this mistakes, then the following errors are thrown:

```
EXCEPTION: No provider for TemplateRef! (function (_viewContainer, _templateRef) { -> TemplateRef)
...
EXCEPTION: TypeError: Cannot read property 'location' of undefined
...
```

These errors are not actionable and don't provide a sufficient hint to the developer to fix the problem.

It would be great if we detected any situation when a template/structural directive is used without the required `template` element or `*` syntactic sugar and throw an actionable error.

**Comment by pkozlowski-opensource** [comment]
Hmm, it might be a regression from the recent compiler refactorings since from what I remember we used to have an error saying that `ng-if` is not a property of a `<template>` element. We definitively need integration tests for those corner cases....

**Comment by vicb** [comment]
Still in 2.0.0 
http://plnkr.co/edit/FdO19wscsuzwOLRDdXQY?p=preview

**Comment by pkozlowski-opensource** [comment]
Current reproduce: https://stackblitz.com/edit/angular-su6xga?file=src%2Fapp%2Fapp.component.html
We should really add proper error message here...

**Comment by trotyl** [comment]
What if someone writes:

```typescript
class MyDirective {
  constructor(@Optional() template: TemplateRef) {
    if (template) { doSomething(); }
    else { doSomethingElse(); }
  }
}
```

Technically there's no definition of what a structural directive is.

**Comment by pkozlowski-opensource** [comment]
> Technically there's no definition of what a structural directive is.

Sure. I'm not suggesting that we should "fix" in any generic way but rather that we should add explicit check in `ngIf` / `ngFor`...
