### ISSUE TITLE
UnCaught Error: Cannot find module 'tslib' : Angular 11

### ISSUE THREAD

**Issue by krithivasanchandran** [angular/angular#42058]
I need help in resolving the below error stack trace : 

rendering sync:2 Uncaught Error: Cannot find module 'tslib'
    at webpackEmptyContext (rendering sync:2)
    at renderer.js:13
    at renderer.js:3
    at Object.y7y4 (renderer.js:9)
    at __webpack_require__ (bootstrap:79)
    at Module.2ptm (remediate-master-table-view.component.ts:7)
    at __webpack_require__ (bootstrap:79)
    at Module.ZAI4 (app.module.ts:1)
    at __webpack_require__ (bootstrap:79)
    at Module.zUnb (main.js:2056)

- I could see the tslib in the node_modules folder 
- After giving the path to tslib folder in path: variable in tsconfig.json am still seeing the same error. 
- Below is my tsconfig.json and package.json file

/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "paths": {
      "tslib" : ["C:\\Users\\KRICHANDRAN\\Risk-Team-Workspace\\remediationtoolnodeweb\\node_modules\\tslib\\tslib.d.ts"]
    },
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false
  }
}

package.json 

{
  "name": "remediatetool",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "jasmine",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "ngcc"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^11.2.6",
    "@angular/cdk": "^11.2.5",
    "@angular/common": "^11.2.6",
    "@angular/compiler": "^11.2.6",
    "@angular/core": "^11.2.6",
    "@angular/forms": "^11.2.6",
    "@angular/material": "^11.2.5",
    "@angular/platform-browser": "^11.2.6",
    "@angular/platform-browser-dynamic": "^11.2.6",
    "@angular/router": "^11.2.6",
    "angular2-uuid": "^1.1.1",
    "constants": "^0.0.2",
    "fs-extra": "^4.0.2",
    "graceful-fs": "^4.2.5",
    "ngx-cookie": "^5.0.2",
    "rxjs": "~6.6.0",
    "tslib": "^2.2.0",
    "xlsx": "^0.16.9",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1102.12",
    "@angular-devkit/core": "^11.2.11",
    "@angular/cli": "^11.2.5",
    "@angular/compiler-cli": "^11.2.6",
    "@types/jasmine": "^3.6.7",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.5"
  },
  "browser": {
    "fs": false,
    "path": false,
    "os": false,
    "stream": false
  }
}

Please help me resolve this issue as it is a blocker for a long time.

**Comment by petebacondarwin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).
