### ISSUE TITLE
Unable to set Referrer-Policy HTTP header using the Angular HTTP client

### ISSUE THREAD

**Issue by bgibb95** [angular/angular#42056]
# Bug Report

### Affected Package
The issue is caused by package `@angular/common/http`

### Is this a regression?
Unknown. Most likely not.

### Description
Is not possible to change the `Referrer-Policy` HTTP header using the Angular HTTP client.

## Minimal Reproduction
See https://stackblitz.com/edit/angular-ivy-abg9st?file=src%2Fapp%2Fapp.component.ts or see code snippet below:
```
const url = `https://jsonplaceholder.typicode.com/todos/1`;

return this.httpClient.get(url, {
  headers: new HttpHeaders({
    'Referrer-Policy': 'no-referrer'
  })
});
```

## Exception or Error
The `Referer` and `Referrer-Policy` HTTP headers are unchanged.

We expect the `Referer` header to be hidden and `Referrer Policy` to be `no-referrer`

Expected:
<pre><code>Referrer Policy: no-referrer</code></pre>

Actual:
<pre><code>Referrer Policy: origin-when-cross-origin</code></pre>

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.6
Node: 14.15.4
OS: darwin x64

Angular: 11.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                          Version
----------------------------------------------------------
@angular-devkit/architect        0.1102.6
@angular-devkit/build-angular    0.1102.6
@angular-devkit/core             11.2.6
@angular-devkit/schematics       11.2.6
@angular-devkit/schematics-cli   0.1102.6
@angular/cdk                     11.2.6
@angular/cli                     11.2.6
@angular/fire                    6.1.4
@angular/flex-layout             11.0.0-beta.33
@angular/material                11.2.6
@nguniversal/builders            11.2.1
@nguniversal/express-engine      11.2.1
@schematics/angular              11.2.6
@schematics/update               0.1102.6
ng-packagr                       11.2.4
rxjs                             6.6.7
typescript                       4.1.5
</code></pre>

**Anything else relevant?**

The issue persists across browsers.

**Comment by petebacondarwin** [comment]
It appears that this is a restriction on the native XHR object. See https://stackblitz.com/edit/js-exv4hs

**Comment by petebacondarwin** [comment]
Further it seems that you cannot set the referrerPolicy via the headers of a `fetch()` call. But you can set it using a special option. See https://stackblitz.com/edit/js-vurj81

I would suggest in that case that you either:

1. Use `fetch()` directly in your application, if you are not relying on other aspects of `HttpClient`, or
2. Implement your own `FetchHttpBackend` class and provide that in your application to override the standard `XhrBackend`.

**Comment by petebacondarwin** [comment]
Marking this a feature, since we may consider (now that are dropping support for IE11) implementing a `fetch` based backend.

**Comment by bgibb95** [comment]
Thanks for the response and the suggestions @petebacondarwin.

Yes it would be very helpful to have a `fetch` based backend used in order to have an option to set the referrer policy with the `HttpClient`.

We reply on the `HttpClient` as we use several Angular `HttpInterceptors`, so we'll investigate an alternative solution to control the visibility of the `referer` header.

**Comment by alxhub** [comment]
Closing as this is not possible to provide currently (using the XHR backend to HTTP)
