### ISSUE TITLE
Support for AngularJS aHrefSanitizationTrustedUrlList feature 

### ISSUE THREAD

**Issue by jcompagner** [angular/angular#42061]
I can't find a way to port the feature we have in our AngularJS to our Angular app:
 
https://docs.angularjs.org/api/ng/provider/$compileProvider#aHrefSanitizationTrustedUrlList

If i google around they all say use the https://angular.io/api/platform-browser/DomSanitizer but thats not the same,
As far as i can see that only tells us that we want to trust more (possible unsafe stuff)
But we want the other way around we want to be more stricter if sanitize happens..
If we have a following html template:

`
<span>hello</span><a href="https://evil.com">My Nice Link</a><span>please click</span>
`

And i place that on an Angular component that displays that html 
Then i want that angular makes it:

`
<span>hello</span><a href="unsafe:https://evil.com">My Nice Link</a><span>please click</span>
`

or something like that, in AngularJS it just fully removes the href attribute if i i set an allowed/trusted url list.
(which doesnt include evil.com)

But no matter where i look that just isn't possible right now? it seems only if i do:

`
<span>hello</span><a href="javascript:xxxx">My Nice Link</a><span>please click</span>
`

angular makes it

`
<span>hello</span><a href=""unsafe:javascript:xxxx">My Nice Link</a><span>please click</span>
`

I would love to have a hook that after the current Angular implementation says i don't do anything with that url that i can still say no this is also unsafe.

**Comment by petebacondarwin** [comment]
Angular templates are implicitly trusted. We do not sanitize values that are hardcoded in to the template. So I don't think your example will be sanitized at all as it stands. See https://stackblitz.com/edit/angular-ivy-yftnhh?file=src%2Fapp%2Fapp.component.html

Perhaps what you mean is when you bind the `href` to an expression? https://stackblitz.com/edit/angular-ivy-43mu92?file=src%2Fapp%2Fapp.component.html

By default the `DomSanitizer` only checks for certain safe protocols and blocks the rest. See https://github.com/angular/angular/blob/master/packages/core/src/sanitization/url_sanitizer.ts#L36-L47

**Comment by petebacondarwin** [comment]
While one ought to be able to override the DomSanitizer with your own implementation, I don't quite see how we can do this with Ivy code, since it doesn't rely upon the DI to get the sanitizer implementation. See https://stackblitz.com/edit/angular-ivy-n9a6jc?file=src%2Fapp%2Fapp.module.ts

**Comment by jcompagner** [comment]
i am not talking about angular templates, i am talking about components like

`
 	<span  ng-bind-html='someVar'></span>
`

and that "someVar" has a value like 

`
<span>hello</span><a href="https://evil.com">My Nice Link</a><span>please click</span>
`

that is sanitized by angular and that is fine and perfect, but its not sanitized enough because that href is just shown and can be clicked on.

So this is all about ng-bind-html directive to inject pieces of html, our users can use that.
Some stuff comes from the server and is not user input and they can say i trust it (for that we use the DomSanitizer: this.domSanitizer.bypassSecurityTrustHtml(input);)

but thats the other way around we trust more then angular by default does.

i like to trust less when we don't do that bypass..
