### ISSUE TITLE
bug(docs-infra): AIO cannot build with Node.js v12

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#42086]
# Docs or angular.io Bug Report

### Description

https://github.com/angular/angular/blob/2e7eb270dfe26d157b8bf819fcb669d9f0d0a066/aio/tools/transforms/angular-api-package/processors/processNgModuleDocs.js#L100

Because optional chaining is supported since Node.js v14, the current AIO build process fails on Node.js v12.
But AIO allows both v12 and v14. This is inconsistent.

https://github.com/angular/angular/blob/2e7eb270dfe26d157b8bf819fcb669d9f0d0a066/aio/package.json#L82

Option 1. fix code for Node.js v12 compatibility
Option 2. allow v14 only

I can submit a patch for whichever, but I'd like to know which AIO team prefers.

**Comment by lacolaco** [comment]
cc/ @gkalpak @petebacondarwin

**Comment by petebacondarwin** [comment]
We should not allow node v12 in aio. Thanks @lacolaco

**Comment by vladimiry** [comment]
Should not the range to be `>=14.0.0` vs currently used `^14.0.0`? See https://github.com/angular/angular/issues/42076.

**Comment by petebacondarwin** [comment]
@vladimiry - yes you are correct. Do you want to submit a further PR?

**Comment by vladimiry** [comment]
> Do you want to submit a further PR?

Nope, going to sleep soon.

**Comment by petebacondarwin** [comment]
> > Do you want to submit a further PR?
> 
> Nope, going to sleep soon.

A very sensible thing to do. I should do the same 👍

**Comment by zarend** [comment]
#42367 sets the range in aio to `>=14.0.0`
