### ISSUE TITLE
update.angular.io says no UMD bundles, but there are

### ISSUE THREAD

**Issue by ersimont** [angular/angular#42081]
# Docs or angular.io Bug Report

### Description

The upgrade guide at https://update.angular.io/ when going from version 11->12 at `Medium` level says:

> Make sure you don't rely on Angular's UMD bundles in your build pipeline because they will no longer be part of the v12 distribution.

However, UMD bundle DO exist in the 12.0.0 distribution. Also, `CHANGELOG.md` only mentions removing _**minified**_ UMD bundles. Should the upgrade app only warn about minified bundles? Or are even the un-minified versions deprecated now? It seems like the documentation is inconsistent.

### What's the affected URL?
https://update.angular.io/?l=2&v=11.0-12.0

**Comment by mgechev** [comment]
Just updated the guide. Thanks for the heads up!
