### ISSUE TITLE
After upgrading angular 11 to 12, CPU utilization goes 100%

### ISSUE THREAD

**Issue by webcat12345** [angular/angular#42098]
# Bug Report

### Affected Package

This issue is caused by package `@angular/core` and `@angular/cli` but not sure yet.

### Is this a regression?

With Angular 11, everything is fine, but after upgrading to 12, cup goes 100%.

### Description
Our project is not that big, maybe small. And we were using Angular 11 with Angular Material and also Angular universal for SSR.
Today, I read about Angular 12 release so updated project version to 12. 
After that server went down every 10 minutes and we made some investigation and found that pm2 instance occupying CPU utilization 102%. 

As a temporary solution, I downgraded it again to 11 and all became fine. 

## Minimal Reproduction

Not sure how can I reproduce error, just reporting this issue to Angular team. But I am attaching screenshot.
![angular12](https://user-images.githubusercontent.com/19761422/118306958-0ec97d00-b4b8-11eb-9a7b-9eecccd1aaa7.png)
![angular11](https://user-images.githubusercontent.com/19761422/118307076-31f42c80-b4b8-11eb-8b57-74e5351bc8a6.png)

## Exception or Error

Please check the screenshots.

## Your Environment

**Angular Version:**

<pre><code>
Angular: 12.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@nguniversal/builders           12.0.0
@nguniversal/express-engine     12.0.0
@schematics/angular             12.0.0
@schematics/update              0.1102.5
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Comment by JoostK** [comment]
Heya, I'm sorry to hear you're having issues after the update. Unfortunately however I don't think there's enough information in this report for us to investigate further, so I'm afraid this isn't actionable right away.

Can you try to determine where the CPU time is spent? Ideally you can attach a debugger and trigger some requests, which could hopefully provide some insights into what's going on.

**Comment by webcat12345** [comment]
Hello, Thank you very much for your quick response. Yes, sure, we will try to get some more detailed information but actually this is a production server and we can't make the server down to investigate this issue. Anyway, I will try to use QA server for this one. 

Regards

**Comment by webcat12345** [comment]
Just cherry-picked commits for ng update and deployed things to the QA server. I will be here again once I got some metrics.

**Comment by webcat12345** [comment]
For now, I am sharing video which is comparing 11 server and 12 server `htop` watcher.


https://user-images.githubusercontent.com/19761422/118347298-2b919f00-b510-11eb-9a0f-32068c523d29.mp4

**Comment by webcat12345** [comment]
`pm2 monit` gives some more detailed insight, I found.

### Angular 12

When this error happens, CPU usage increases to about 108 ~ 116%.

```
landing-v2 > ERROR ReferenceError: gtag is not defined                                                           │
landing-v2 >     at SafeSubscriber._next (/home/ubuntu/projects/uh-landing-v2/dist/uh-landing/server/main.js:1:  │
landing-v2 >     at SafeSubscriber.__tryOrUnsub (/home/ubuntu/projects/uh-landing-v2/dist/uh-landing/server/mai  │
landing-v2 >     at SafeSubscriber.next (/home/ubuntu/projects/uh-landing-v2/dist/uh-landing/server/main.js:1:3  │
landing-v2 >     at Subscriber._next (/home/ubuntu/projects/uh-landing-v2/dist/uh-landing/server/main.js:1:3036  │
landing-v2 >     at Subscriber.next (/home/ubuntu/projects/uh-landing-v2/dist/uh-landing/server/main.js:1:30358  │
landing-v2 >     at FilterSubscriber._next (/home/ubuntu/projects/uh-landing-v2/dist/uh-landing/server/main.js:  │
landing-v2 >     at FilterSubscriber.next (/home/ubuntu/projects/uh-landing-v2/dist/uh-landing/server/main.js:1  │
landing-v2 >     at Subject.next (/home/ubuntu/projects/uh-landing-v2/dist/uh-landing/server/main.js:1:3031517)  │
landing-v2 >     at SafeSubscriber._next (/home/ubuntu/projects/uh-landing-v2/dist/uh-landing/server/main.js:1:  │
landing-v2 >     at SafeSubscriber.__tryOrUnsub (/home/ubuntu/projects/uh-landing-v2/dist/uh-landing/server/mai
```

After 1 second, this error happens. (Note: This only happens on Angular 12 server)

```
landing-v2 > 1 rules skipped due to selector errors:                                                             │
landing-v2 >   .custom-file-input:lang(en)~.custom-file-label -> unmatched pseudo-class :lang  
```

### Angular 11

The same `gtag` error happens, but CPU usage is only 5 ~ 9%.

```
uh-landing > ERROR ReferenceError: gtag is not defined                                                           │
uh-landing >     at SafeSubscriber._next (/home/ubuntu/uh-landing-v2/dist/uh-landing/server/main.js:1:4825555)   │
uh-landing >     at SafeSubscriber.__tryOrUnsub (/home/ubuntu/uh-landing-v2/dist/uh-landing/server/main.js:1:61  │
uh-landing >     at SafeSubscriber.next (/home/ubuntu/uh-landing-v2/dist/uh-landing/server/main.js:1:613938)     │
uh-landing >     at Subscriber._next (/home/ubuntu/uh-landing-v2/dist/uh-landing/server/main.js:1:612597)        │
uh-landing >     at Subscriber.next (/home/ubuntu/uh-landing-v2/dist/uh-landing/server/main.js:1:612359)         │
uh-landing >     at FilterSubscriber._next (/home/ubuntu/uh-landing-v2/dist/uh-landing/server/main.js:1:3391371  │
uh-landing >     at FilterSubscriber.next (/home/ubuntu/uh-landing-v2/dist/uh-landing/server/main.js:1:612359)   │
uh-landing >     at Subject.next (/home/ubuntu/uh-landing-v2/dist/uh-landing/server/main.js:1:1839585)           │
uh-landing >     at SafeSubscriber._next (/home/ubuntu/uh-landing-v2/dist/uh-landing/server/main.js:1:3917982)   │
uh-landing >     at SafeSubscriber.__tryOrUnsub (/home/ubuntu/uh-landing-v2/dist/uh-landing/server/main.js:1:61 
```
And that the second error never happens on Angular 11 server.

**Comment by alan-agius4** [comment]
I have a hunch that this is related to critical css inlining. 

Can you try disabling it in your server file.

```ts
    ngExpressEngine({
      bootstrap: AppServerModule,
      inlineCriticalCss: true,
    }),
```

**Comment by webcat12345** [comment]
Trying this one, but can't deploy to the server due to Github Action Incident, been 6 hours. Btw, @alan-agius4 if your solution is correct then does this mean that we can't use Inlining Critical CSS feature for Angular 12?

**Comment by webcat12345** [comment]
@alan-agius4 That actually resolved the problem.

Also after that update, this error disappeared.

```
landing-v2 > 1 rules skipped due to selector errors:                                                             │
landing-v2 >   .custom-file-input:lang(en)~.custom-file-label -> unmatched pseudo-class :lang  
```

But still have a question that we really can't use Inlining Critical CSS with Angular 12?

**Comment by alan-agius4** [comment]
> @alan-agius4 That actually resolved the problem.
> 
> Also after that update, this error disappeared.
> 
> ```
> landing-v2 > 1 rules skipped due to selector errors:                                                             │
> landing-v2 >   .custom-file-input:lang(en)~.custom-file-label -> unmatched pseudo-class :lang  
> ```
> 
> But still have a question that we really can't use Inlining Critical CSS with Angular 12?

I am not really sure what's causing the problem in your case. Without a reproduction or at the very minimum CPU profiling snapshots it's impossible to determine the root cause.

The performance of the extraction tools depends on a number of variables such as the DOM tree depth, number of nodes in DOM, and number of CSS selectors. Are you using any type of caching service for your SSR'd request?

**Comment by webcat12345** [comment]
Actually no. But FYI, we have integrated Service Worker and use that SW for the site update detector. Nothing special other than that. And honestly speaking, the site is kinda simple, only a few pages there. https://unitedhardscapes.com

The strange thing is that problem appeared only with Angular 12.

**Comment by Splaktar** [comment]
You may want to take a look at running [sass-migrator](https://sass-lang.com/documentation/cli/migrator) for your repo and checking for any `@import`s of the old theming API as discussed in https://github.com/angular/components/issues/22676.

**Comment by alan-agius4** [comment]
In v12, inline critical css is enabled by default.

Let’s continue tracking this issue here https://github.com/angular/universal/issues/2106, although I suspect that without a caching layer it would be hard to use this feature successfully on certain apps.
