### ISSUE TITLE
stackblitz example of http are not working

### ISSUE THREAD

**Issue by iRealNirmal** [angular/angular#42116]
I was checking docs of http and found that stackblitz examples are not working

# Docs or angular.io Bug Report

### Description

Stackblitz example under [https://angular.io/guide/http#setup-for-server-communication](https://angular.io/guide/http#setup-for-server-communication) is  some time working and some time failing with error 

```Error in src/test.css
Error: ENOENT: No such file or directory., '/dev/null'
```

while other stackblitz example under [https://angular.io/guide/http#testing-http-requests](https://angular.io/guide/http#testing-http-requests) is failing every time.

It gives error
```Error in src/testing/global-jasmine.ts (1:28)
Cannot find module 'jasmine-core/lib/jasmine-core/jasmine.js' or its corresponding type declarations.
```

## Minimal Reproduction
Visit Angular docs
### What's the affected URL?**

[https://angular.io/guide/http#testing-http-requests](https://angular.io/guide/http#testing-http-requests)
### Reproduction Steps**
Provided in description

### Expected vs Actual Behavior**
stackblitz example shouldn't fail

## Screenshot
<img width="1673" alt="Screenshot 2021-05-16 at 9 33 50 PM" src="https://user-images.githubusercontent.com/4091874/118403917-615c9200-b68e-11eb-84ba-57f710889e33.png">
<img width="1674" alt="Screenshot 2021-05-16 at 9 33 43 PM" src="https://user-images.githubusercontent.com/4091874/118403924-6c172700-b68e-11eb-908d-04bc786ee75f.png">

## Exception or Error
provided  in description

### Browser info
Any browser

### Anything else relevant?
No

**Comment by petebacondarwin** [comment]
The testing Stackblitz was actually broken by your PR 😄 https://github.com/angular/angular/pull/42001.
We need to check what other examples use `jasmine-core` and add this to their `devDependencies` property in `stackblitz.json`.

**Comment by iRealNirmal** [comment]
Yes I thought same, I was checking one issue and found this one. I will just quickly check all live examples and will push this.

**Comment by iRealNirmal** [comment]
Just went through all live examples only above 2 reported issues are breaking, So I will work on it and will raise PR at earliest.
