### ISSUE TITLE
Angular v12 is too slower than v11 in compile time.

### ISSUE THREAD

**Issue by Wenrong108** [angular/angular#42119]
### description

I upgraded v12 from v11 and working some days, but it is too slow whenever compile changed code.
I wonder why it is...

Thanks

**Comment by the-ult** [comment]
See: https://github.com/angular/angular-cli/issues/20792

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.

Additionally, if you are using Angular Material, you may want to take a look at https://github.com/angular/components/issues/22676.
