### ISSUE TITLE
Error in https://angular.io/tutorial/toh-pt6

### ISSUE THREAD

**Issue by easybreather** [angular/angular#42113]
# Docs or angular.io Bug Report

- checked for relevant reports, nothing apparently related...

### Description

In the Tour of Heroes demo, pt6, https://angular.io/tutorial/toh-pt6
Hereo-Search Component

...
export class HeroSearchComponent implements OnInit {
  heroes$: Observable<Hero[]>;
  private searchTerms = new Subject<string>();

  constructor(private heroService: HeroService) {}
...

This-> heroes$: Observable<Hero[]>; generates 

Build at: 2021-05-16T09:59:31.630Z - Hash: a7c9271139b046466154 - Time: 328ms

Error: src/app/hero-search/hero-search.component.ts:17:3 - error TS2564: Property 'heroes$' has no initializer and is not definitely assigned in the constructor.

17   heroes$: Observable<Hero[]>;

Solution: heroes$!: Observable<Hero[]>;

## Your Environment
latest (v12) npm setup

### Browser info
n/a

### Anything else relevant?
no idea - am learning angular

**Comment by JoostK** [comment]
This is being addressed in #41999.

**Comment by JoostK** [comment]
Closing this as #41999 was merged.
