### ISSUE TITLE
i18n dynamic data localization message extraction

### ISSUE THREAD

**Issue by Romko775** [angular/angular#42129]
# Feature Request

### Relevant Package
@angular/localize

### Description
For now you can localize text only if it is in the html file (i18n attribute) or signing to value like `title = $localize
:@@myTitle:Title';`, but this is not covering the translation of data that can be received via http (keys, strings other). If you define custom values in xlf file they can be erased in next xlf message extract.

for instance

```
// keys -> FR locale
// ['Crow ', 'Dove ', 'Goose '] -> ['Corbeau', 'Pigeon', 'OIE']
birdNames = this.service.getBirds().map( name => localize(name))
```

### Describe alternatives you've considered
Can we somehow predefine some translations than we can translate in runtime dynamic data ?

**Comment by petebacondarwin** [comment]
Given that `$localize` is primarily designed to run at compile-time, how would these translations be handled?

Ideally, IMO, what you need to do is provide a locale key to the server when making such requests and let it do the translation of the response for you.
If this is not possible then you could provide your own Angular service, which you load up with translations for any possible data that might be sent from the server.

This feature request is out of scope of the `$localize` tooling, so I am going to close this as we do not intend to implement such a feature.
