### ISSUE TITLE
Allow forwardRef in Host

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular#4213]
Having the following code

```javascript
@Directive({selector:'[child]'})
class Child {
  constructor(@Host() @SkipSelf() p: Hello) {
    console.log(p);
  } 
}

@Component({selector: 'hello',})
@View({
	template: `<div child></div>`,
	directives : [Child]
})
export class Hello {}
```
This will obviously fail because Hello is defined before Child. The only option available is to move Child below Hello and use forwardRef in the `directives` property. It works, but I think it is too much annoyance moving an entire Directive/Component, so I think it would be nice as well to be able to use forwardRef in the `@Host()` annotation.

I tried to pass forwardRef on the right side, like this

```
constructor(@Host() @SkipSelf() p: (forwardRef(() => Hello)))
```
But that didn't work, for what I saw forwardRef is transpiled into a function, so it would end up in this (just guessing since TS didn't even compile the line above, but I saw what is tranpiled into when using it in a `directives` property)
```
constructor(@Host() @SkipSelf() p: function() { return Hello;}))
```
And that seems not be possible. 

So considering that we can use `forwardRef` in a `Query`/`ViewQuery`, for example, it would be nice to be able to do the same in `@Host()`
```
@Host((forwardRef() => MyNotYetDefinedClass))
```

**Comment by PascalPrecht** [comment]
I think you're using it wrong. You have to use `@Inject` for `forwardRef`. `@Host` and `@SkipSelf` are really just DI qualifiers. Did you try:

```
constructor(@Host, @SkipSelf() @Inject(forwardRef(() => Hello)) p)  {

}
```

**Comment by ericmartinezr** [comment]
@PascalPrecht Interesting... I didn't think of that. The way we use ViewQuery/Query made me think that this would be possible. Thanks for pointing out. Although I think it wouldn't be a bad idea to be more specific and add something inside `@Host`. Anyway, closing, thanks :+1:
