### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by chenyunhsin** [angular/angular#42144]
# Docs or angular.io Bug Report

### Description
this page
https://angular.io/start#pass-data-to-a-child-component
this line

```ts
import { Product } from '../products';
```

cause error, there isn't exist any class of Product in products.js

### What's the affected URL?**
https://angular.io/start#pass-data-to-a-child-component

### Expected vs Actual Behavior**
Maybe a class named Product should be exist

## Screenshot
<img width="1305" alt="截圖 2021-05-18 下午5 09 54" src="https://user-images.githubusercontent.com/58776036/118626675-a8b56080-b7fd-11eb-9a20-64fc0ea7e575.png">

## Exception or Error

```
`./products` has no exported member named 'Product`
```

### Anything else relevant?
after added this in product.js will fix the bug, answer from Discord guy dO_ob FRED DUCK do_O

```ts
export interface Product {
  id: number;
  name: string;
  price: number;
  description: string;
}
```

**Comment by Owain94** [comment]
It seems someone has updated the getting started tutorial with either types for the product structure or changed the products implementation and forgot to update the linked stackblitz on the website.

The stackblitz sample project is linked in the "Create the sample project" section of the tutorial.

**Comment by petebacondarwin** [comment]
This was fixed in #41999 but it does not appear to have been deployed to the website correctly yet...

**Comment by petebacondarwin** [comment]
Actually, you are right. This file ([getting-started-v0/src/app/product.ts](https://github.com/angular/angular/blob/master/aio/content/examples/getting-started-v0/src/app/products.ts)) was not updated when the other file ([getting-started/src/app/product.ts](https://github.com/angular/angular/blob/master/aio/content/examples/getting-started/src/app/products.ts)) was updated.

**Comment by petebacondarwin** [comment]
A PR would be welcomed!

**Comment by chenyunhsin** [comment]
> A PR would be welcomed!

ok !
