### ISSUE TITLE
My public IPs cannot access Angular.io

### ISSUE THREAD

**Issue by minh0607** [angular/angular#42168]
Hi Angular Admin Team,
My Public IP was filtered by Angular Hosting and I cannot access Angular from my Public IP.
Could you give me the contact point of Angular's website admin ? 
Thank you.

**Comment by josephperrott** [comment]
@minh0607 angular.io is hosted on firebase, using firebase hosting.  

We do not perform any sort of manual prevention of access on our instance based on IP addresses.  You can look at the DNS A record to see the IPs from which our site is served to see if something on your end has prevented the site from being made accessible.

Unfortunately, there is not much else we are able to provide as the angular.io site should be publicly accessible and we do not prevent access to it.

```
$ dig -t a angular.io

; <<>> DiG 9.10.6 <<>> -t a angular.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7868
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;angular.io.			IN	A

;; ANSWER SECTION:
angular.io.		3600	IN	A	151.101.65.195
angular.io.		3600	IN	A	151.101.1.195

;; Query time: 78 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Wed May 19 08:16:01 PDT 2021
;; MSG SIZE  rcvd: 71
```
