### ISSUE TITLE
Configurable Guards & Resolvers

### ISSUE THREAD

**Issue by homj** [angular/angular#42171]
# Feature Request

### Relevant Package
This feature request is for @angular/router

### Description
I want to use a guard or a resolver across the app in many places, but always with a slightly different configuration. E.g. a guard should redirect to different pages when some request fails or a resolver should load data from different endpoints.

The current solution is to either pass data in the route and let the guard/resolver access this data, or create a subclass of a guard / resolver for each specific configuration. However, there is no type-safety for route data and the data may be overwritten from a parent route when `paramsInheritanceStrategy` is active. Additionally, this can get really bloated when using several configured guards or resolvers:

```ts
// routes.ts
{
    path: 'page-a',
    component: PageAComponent,
    data: {
        authGuard: {
            failureRedirect: '/login'
        }
    },
    canActivate: [ AuthGuard ],
    resolve: {
        foo: FooContentResolver,
        bar: BarContentResolver
    }
},
{
    path: 'page-b',
    component: PageBComponent,
    data: {
        authGuard: {
            failureRedirect: '/signup'
        }
    },
    canActivate: [ AuthGuard ]
}
```

```ts
// resolvers

@Injectable()
abstract class ContentResolver implements Resolve<any> {
    // ...
}

@Injectable()
class FooContentResolver extends ContentResolver {

    readonly options: IContentResolverOptions = {
        url: '/api/foo',
        method: 'get'
    };

    // ...
}

@Injectable()
class BarContentResolver extends ContentResolver {

    readonly options: IContentResolverOptions = {
        url: '/api/bar',
        method: 'get'
    };

    // ...
}

```
### Describe the solution you'd like

To solve this issue, I'm imagining something similar to the `forRoot`/ `ModuleWithProviders` approach, that would let you pass options to some injectable (like here, a guard/resolver). So the `canActivate`, `canActivateChild` and `canLoad` attributes of a `Route` could also accept some kind of `InjectableWithProviders` object next to the `InjectionToken` / `string`.

```ts
// routes.ts
{
    path: 'page-a',
    component: PageAComponent,
    canActivate: [ AuthGuard.withOptions({ failureRedirect: '/login' }) ],
    resolve: {
        foo: ContentResolver.load({
            url: '/api/foo',
            method: 'get'
        }),
        bar: ContentResolver.load({
            url: '/api/bar',
            method: 'get'
        })
    }
},
{
    path: 'page-b',
    component: PageBComponent,
    canActivate: [ AuthGuard.withOptions({ failureRedirect: '/signup' }) ]
}
```

```ts
const AUTH_GUARD_OPTIONS = new InjectionToken<IAuthGuardOptions>('auth-guard-options');

@Injectable()
class AuthGuard implements CanActivate {

    static withOptions(options: IAuthGuardOptions): InjectableWithProviders<AuthGuard> {
        return {
            injectable: AuthGuard,
            providers: [
                { provide: AUTH_GUARD_OPTIONS, useValue: options }
            ]
        };
    }

    // ...

}
```

```ts
const CONTENT_RESOLVER_OPTIONS = new InjectionToken<IContentResolverOptions>('content-resolver-options');

@Injectable()
class ContentResolver implements Resolve<any> {

    static load(options: IContentResolverOptions): InjectableWithProviders<ContentResolver> {
        return {
            injectable: ContentResolver,
            providers: [
                { provide: CONTENT_RESOLVER_OPTIONS, useValue: options }
            ]
        };
    }

    // ...

}
```

### Describe alternatives you've considered

An alternative would be to use something similar to `MAT_DIALOG_DATA` used in `@angular/material`. We wouldn't need a fully flexible `InjectableWithProviders`, but every guard / resolver could inject a common token, e.g. `GUARD_OPTIONS`  / `RESOVLER_OPTIONS` that should be configurable in the route, e.g.:

```ts
// routes.ts
{
    path: 'page-a',
    component: PageAComponent,
    canActivate: [
        { guard: AuthGuard, options: { failureRedirect: '/login' } }
    ],
    resolve: {
        foo: {
            resolver: ContentResolver,
            options: {
                url: '/api/foo',
                method: 'get'
            }
        },
        bar: {
            resolver: ContentResolver,
            options: {
                url: '/api/bar',
                method: 'get'
            }
        }
    }
},
{
    path: 'page-b',
    component: PageBComponent,
    canActivate: [
        { guard: AuthGuard, options: { failureRedirect: '/signup' } }
    ]
}
```

I also tried to dynamically create a subclass in the static method and return it, but I assume this is not optimal for dependency discovery (and is currently failing with an error when using dependencies in the constructor of the guard: `Error: This constructor is not compatible with Angular Dependency Injection because its dependency at index 0 of the parameter list is invalid.`):

```ts
@Injectable()
class AuthGuard implements CanActivate {

    static withOptions(options: IAuthGuardOptions) {

        @Injectable({ providedIn: 'root' })
        class ConfiguredAuthGuard extends AuthGuard {
            _options = options;
        }

        return ConfiguredAuthGuard
    }

    // ...

}
```

### Related Issues
#18247 seems related to this, but suggests some more substantial changes to routes & guards in general (which I would like to see as well!)

**Comment by sg-gdarnell** [comment]
I don't think the object-oriented solution that you mentioned is really that bad, but I suppose I could see it being a pain if you had 50 of them.

You can accomplish this today using an `InjectionToken` with the `factory` option. See this StackBlitz for an example: https://stackblitz.com/edit/configurable-resolver

Last I checked the `factory` option isn't well-documented, but it's very useful for cases like this.

**Comment by SchnWalter** [comment]
You can use the `Route.data` to pass configuration to resolvers and guards, it's always available in the snapshot. But there is one problem: you can't use more than one resolver instance, because there's no way to know under which key the InjectionToken is located.

You can blame `resolveNode()` for that:

https://github.com/angular/angular/blob/e99af184abef53feecff121675ee64a7cf7c51ff/packages/router/src/operators/resolve_data.ts#L66-L69

This can have a backwards compatible fix in 2 different ways:

1) By introducing an optional key argument to the resolve method:
    ```ts
    export interface Resolve<T> {
      resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot, key?: string): Observable<T>|Promise<T>|T;
      //                                                                 ^^^ This is new!
    }
    ```

    The change required to implement this is minimal: `getResolver()` needs to receive the key and pass it along to the resolver.

2) By changing the `Route.resolve` to accept the current `ResolveData` (a map of `InjectionTokens`) or a single `InjectionToken`, for which the service will have to return multiple keys to add to the data object (both `foo` and `bar`).
    ```
    export interface Route {
      // ...
      /**
      * A map of DI tokens used to look up data resolvers, or a single DI token that returns a map of data. See `Resolve`.
      */
      resolve?: ResolveData | InjectionToken;
      // ...
    }
    ```
    Here, we just need to figure out a way to distinguish between a plain object for `ResolveData` and the full spectrum of values allowed the injection token (which is `any`, see `ResolveData`).

**Comment by moniuch** [comment]
What if `resolve`, `canActivate`, `data`, and other route properties, could accept a function, so that devs could provide custom factories and substitute the OOP model? With `inject()` in place, a lot more seems to be achievable using plain functions.

```
canActivate: () => getAccessGuard(Permissions.CanSeeDashboard)
```

Could be naive what I'm thinking, and not bulletproof for sure, but seems to be opening a lot of possibilities. Maybe worth consideration.

**Comment by atscott** [comment]
Closing as resolved by the feature which allows guards as plain functions (https://github.com/angular/angular/commit/0abb67af59a92a2b29082a259aa9f4ea3fbaab7d). You can now accomplish this configurability by having a factory function that accepts configuration and returns a guard/resolver function.
