### ISSUE TITLE
changing component name while serving doesnt' work

### ISSUE THREAD

**Issue by mhamri** [angular/angular#42183]
# Bug Report

### Affected Package
tested with 12.0.0

### Is this a regression?
it wasn't in pre Ivy versions

### Description
1- create a fresh project
2- rename the app-root to something else, there will be no build error
3- nothing going to render in the page. 
4- stop the app and try to rebuild, it won't work

![VkpBEotVse](https://user-images.githubusercontent.com/8991783/118871200-ec9d8800-b919-11eb-8f6d-8cad998d9720.gif)

## Exception or Error
I expect to see an error or just render the page 

## Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.0.0
Node: 14.16.0
Package Manager: npm 6.14.11
OS: win32 x64

Angular: 12.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@angular/cli                    12.0.0
@schematics/angular             12.0.0
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Comment by zarend** [comment]
It appears this behaves as expected. When the selector is `app-root`, the page renders. When it is misspelled as `ap-root`, the page does not render and gives the error "the selector 'app-root' did not match any elements.
 
 If you still feel there is an issue, please provide further details in a new issue.

**Comment by mhamri** [comment]
@zarend yes, this is expected, but it shouldn't get done with no error during build. also the error message isn't clear. after this change the index.html is in a wrong state, but build step doesn't catch the error and the console error isn't clear about if the problem is in index.html or somewhere else. a cached js file could endup with the same error msg, isn't it?
