### ISSUE TITLE
Paths generated for child outlets relative to empty path named outlet parent are incorrect

### ISSUE THREAD

**Issue by RSalo** [angular/angular#42191]
# Bug Report

### Affected Package
Angular 11 and lower

### Is this a regression?
Yes

### Description
I have 2 outlets. Primary - for child pages. Main-page - using only to display main page template. It can not to work if outlet is root of router tree.

## Minimal Reproduction
https://stackblitz.com/edit/outlet-example-veyabe
After clicking on the "Link to innerRoute" there is should to show another page. But it's not.

## Exception or Error
<pre><code>
Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'innerRoute'
Error: Cannot match any routes. URL Segment: 'innerRoute'

</code></pre>

## Your Environment

**Angular Version:**
<pre><code>
angular 12 fresh install

</code></pre>

**Anything else relevant?**
Are there related issues? Sorry if there are exist any.

**Comment by atscott** [comment]
@RSalo Just to clarify, this doesn't appear to be a regression. It appears to be the same behavior in all the versions I've tried.

**Comment by atscott** [comment]
The link should really go to `(main-page:innerRoute)` but it's generated incorrectly.

As a workaround, you can change the `routerLink` to be `<a [routerLink]="[{outlets: {'main-page': 'innerRoute'}}]">Link to innerRoute</a>`

**Comment by RSalo** [comment]
@atscott your variant with workaround looks good for me but it's don't work either, causing the same exception in the console. This issue is not so critical for me so i can just change my file structure to a workaround.
