### ISSUE TITLE
Reactive Forms:property 'email'  not found on component 

### ISSUE THREAD

**Issue by IshanKBG** [angular/angular#42197]
# Bug Report
### Steps to Reproduce
I am trying to create a form validator using reactive forms
form.component.html
```
<app-nav>
  <form [formGroup]="form">
    <label for="email">Email</label>
    <input
      type="email"
      class="input"
      formControlName="email"
      required
    />
    <div *ngIf="email.invalid && email.dirty">
     Wrong 
    </div>
  </form>
</app-nav>
```
form.component.ts 
```
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, Validators, FormBuilder } from '@angular/forms';


@Component({
  selector: 'app-form',
  templateUrl: './form.component.html',
  styleUrls: ['./form.component.scss']
})
export class FormComponent implements OnInit{
form: FormGroup;
loading = true

constructor(private fb: FormBuilder){

}
   ngOnInit(): void {
    this.form = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      name: ['', [Validators.required, Validators.minLength(2)]],
      description: ['', [Validators.required, Validators.minLength(50)]]
    })
  }
  get hasName(){
    return this.form.get('name');
  }
get hasEmail(){
  return this.form.get('email')
}
get hasDescription(){
  return this.form.get('description')
}

}


```
### Error
I am getting errors that the property email does not exist in FormComponent when i use it show error messages.
### Other Information
```
Node: 16
Angular: 12
NPM: 7
OS: Arch Linux
```

**Comment by petebacondarwin** [comment]
You are referring to `email` on this line:

```ts
<div *ngIf="email.invalid && email.dirty">
```

This reference is looking for an `email` property on `FormComponent`. which does not exist. I think you mean to reference `this.form.get('email')`.

This issue doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).
