### ISSUE TITLE
Add cookie prompt to angular.io

### ISSUE THREAD

**Issue by cindygk** [angular/angular#42209]
1) Create a cookie pop up for the site (in the style of https://web.dev)
2) Add the following text
"This site uses cookies from Google to deliver its services and to analyze traffic.
  Learn more.    Ok, Got it." 
Notes: 
Clicking the “Ok, Got it” button should dismiss the cookie bar. Clicking the “Ok, Got it” button should be recorded on the client (either local storage or cookie) so that we can remember the user’s choice and the user does not see the cookie bar again unless they have cleared their cookies.
Note: there is no option to decline - only to "[Learn More](https://policies.google.com/technologies/cookies)" or click "Ok, Got it."

**Comment by petebacondarwin** [comment]
When you say in the style of web.dev, do you mean their general banner:

<img width="988" alt="Screenshot 2021-05-21 at 07 42 07" src="https://user-images.githubusercontent.com/15655/119093829-1e8d1800-ba08-11eb-9cbd-445c31660736.png">

As far as I can tell web.dev does not have a cookie banner for the purposes described here.

Regarding our implementation, we already have banner infrastructure, which we can reuse quite easily I believe.

**Comment by gkalpak** [comment]
They do have a cookie popup. You probably need to clear your `localStorage` to see it :wink:

![web-dev-cookie-popup](https://user-images.githubusercontent.com/8604205/119108148-90755980-ba28-11eb-9d50-6da011a852a2.png)

**Comment by petebacondarwin** [comment]
> They do have a cookie popup. You probably need to clear your localStorage to see it 😉

LOL! Ironically I only cleared my cookies (not local-storage)!

**Comment by ajitsinghkaler** [comment]
Can I work on this

**Comment by gkalpak** [comment]
Thx for offering to help out, @ajitsinghkaler ❤️
I have already started working on this and am  (hopefully) about half-way through 😅

**Comment by crisbeto** [comment]
In case anybody is curious and wants to align the designs, here's what I ended up with for material.angular.io https://github.com/angular/material.angular.io/pull/988.

**Comment by Airblader** [comment]
Have you considered going a bit further and allowing opting out? I realize you're not bound to EU law here but lots of people probably don't like being forced into this to read documentation (me excluded). It's kind of a strings-attached for the framework.
