### ISSUE TITLE
MIN and MAX attributes in Angular 12 templated forms not working with decimal values

### ISSUE THREAD

**Issue by robinwebbnhs** [angular/angular#42215]
# Bug Report

### Affected Package

FormsModule
@angular/forms

Commit: 8fb83ea1b524663bd804908308d528c338450270
* feat(forms): introduce min and max validators (#39063)

validators.ts:

Using parseInt rather than parsefloat ?

```
normalizeInput = (input: string): number => parseInt(input, 10);
```

### Is this a regression?

MIN/MAX attributes didn't participate in templated forms validity < v12 so not a regression as such.

### Description

MIN and MAX attributes not honouring decimal values in v12. In the example below, the form becomes invalid with a maximum over 37, e.g. 37.1 makes form invalid when it should be > 37.5

```html
<form #someform="ngForm">
  <input
    [(ngModel)]="model.formContractHours"
    required
    name="ContractHours"
    type="number"
    [min]="0.1"
    [max]="37.5"
    step="0.1"
  />
</form>
```
## Minimal Reproduction

MIN/MAX attributes ignored in V11 templated form
https://stackblitz.com/edit/angular11minmaxdecimals

MIN/MAX attributes validated in V12 in templated form but not respecting decimals.
https://stackblitz.com/edit/angular12minmaxdecimals

**Comment by petebacondarwin** [comment]
This was actually brought up before we removed the original implementation: https://github.com/angular/angular/pull/17436
I think this is valid request. Would anyone like to submit a PR?

**Comment by iRealNirmal** [comment]
hi @petebacondarwin I will be happy to work on it.

**Comment by PowerKiKi** [comment]
A possible workaround (or permanent solution) to opt-out of those new validators is to use `[attr.min]`, as mentioned in 
 https://github.com/angular/angular/issues/42267#issuecomment-847220016.
