### ISSUE TITLE
Can deactivate guard issue

### ISSUE THREAD

**Issue by jointMedia** [angular/angular#42220]
My can deactivate guard preventing my app to change URL and in browser URL section I have the same URL,
But router event gives new URL.

which should not be the case until unless browser has a new URL.

this.router.events
      .subscribe((event: NavigationStart) => {
        if (event instanceof NavigationStart && !!event.url) {
        //here I am getting new url
        }
        });

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by indraraj26** [comment]
i think you should change little bit here

event instanceof NavigationEnd
// event.url
