### ISSUE TITLE
Content children is empty when content projection done via Index.html page in angular cli application.

### ISSUE THREAD

**Issue by ecemitrasharma** [angular/angular#42222]
Please consider below mentioned problem using angular-cli (angular 9) application. 

Code sample : 

```
< tabs > 
     < tab >< /tab >
     < tab >< /tab >
< /tabs >
```
in tabs component class trying to read the total tab content using content children : 
  @ContentChildren(forwardRef(() => TabComponent))  tabs: QueryList<TabComponent>  = new QueryList<TabComponent>(); 

Test Scenario 1: 
When above code run inside app.component.html it is working fine. In ngAfterContentInit the contentchildren length is 2 which is correct. 

Test Scenario 2 : 
When tab code added in index.html in ngAfterContentInit the contentchildren length is 0.

Is it possible to do content projection in Index.html file of angular cli application ? 

url of dummy project : https://stackblitz.com/edit/angular-tabs-example-kmxpzk?file=index.html

**Comment by alxhub** [comment]
No, it's not possible to do content projection from `index.html`.

The contents of your app component in `index.html` serves a different purpose: it's what gets displayed until Angular renders the app for the first time. So `index.html` content of:

```html
<app-cmp>
  <h2>Loading...</h2>
  <img src="loading-spinner.gif">
</app-cmp>
```

is common, to show a loading screen of some sort while waiting for the app to download and initialize.

**Comment by ecemitrasharma** [comment]
In my scenario angular fails to achieve my requirement : 

Scenario : 
I have aspx page where i need to implement angular elements. I created Tabs element and in my aspx page loaded runtime.js, polyfills.js and main.js.
Now i added my element only content children is not working whereas simple elements is rendered.

**Comment by ecemitrasharma** [comment]
I request to open this post again so that others also add their comments.
