### ISSUE TITLE
Iframe not calling onLoad when integrating with PDFTron WebViewer Javascript SDK?

### ISSUE THREAD

**Issue by achenPDFTron** [angular/angular#42228]
First time posting. Sorry in advance if this is not the right place to post this. Please let me know where to post this if this is the not correct place.

# Bug Report

### Affected Package
No particular packages affected as far as I know.

### Is this a regression?
I do not think this is a regression.

### Description
Please see "Minimal Reproduction" on the issue and how to reproduce it.

More details:
Not sure if Angular is doing something weird.

This could be an issue with the WebViewer Javascript SDK library.

But from what we are noticing, the iframe "onload" function is not being called internally in the code.

What is strange is that: 
- this issue does not occur when using vanilla JS on Chrome 
- it does not occur using React on Chrome: https://github.com/PDFTron/webviewer-custom-ui.
- if I manually insert an iframe in Angular, "onload" is being called correctly.

## Minimal Reproduction
1. Clone: https://github.com/achenPDFTron/angular-custom-ui-webviewer.git
2. run `npm install`
3. go to localhost:4200

Observe: You will see just a blank page
Actual: The page should not be blank  Some kind of PDF should show up on the page.
E.g Something similar to the following should appear:
![image](https://user-images.githubusercontent.com/54084743/119188962-409a9080-ba30-11eb-8a7b-9898db803872.png)

## Exception or Error
No error is thrown.

## Your Environment

Angular CLI: 11.2.11
Node: 12.13.0
OS: win32 x64

Angular: 11.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.11
@angular-devkit/build-angular   0.1102.11
@angular-devkit/core            11.2.11
@angular-devkit/schematics      11.2.11
@angular/cli                    11.2.11
@schematics/angular             11.2.11
@schematics/update              0.1102.11
rxjs                            6.6.7
typescript                      4.0.7

**Anything else relevant?**
This issue seems to mainly occur on Chrome.
I was able to reproduce this issue on Chrome 86 and Chrome 90 64 bit.
Note that I did not test on any Chrome version pre-86.

This issue is also reproducible on Edge (using Chromium).

This issue is NOT reproducible on Firefox (latest version at this time of writing).

Not sure if it matters, I'm reproducing the issue on a Windows 10 laptop.

**Comment by gkalpak** [comment]
I haven't gotten to the bottom of it, but it seems to be an issue with Zone.js.
If you remove `zone.js` from `polyfills.ts` and change your module to be bootstrapped without zone.js (i.e. `bootstrapModule(AppModule, {ngZone: 'noop'})`), it works fine.

@JiaLiPassion, any idea what might be causing this.
I wonder if this is related to some errors being thrown in the console. Without Zone.js, it eventually works despite the errors. Could it be that the errors somehow cause a Zone.js-patched event listener to stop triggering or something?

**Comment by JiaLiPassion** [comment]
@achenPDFTron, the reason is both `zone.js` and `pdf CoreControls.js` monkey patch the `iframe.addEventListener` method.

1. `zone.js` monkey patch `onload` property and redirect it to `addEventListener`.
2. `pdf CoreControls.js` override `iframe.addEventListener` and doesn't really register the event listener to the native window but only keep the event listeners locally ( I can not find how to trigger the event listener unless the event is a message event).

So finally the `onload` will not be triggered.

The walkaround is to disable `on properties` monkey patch from `zone.js`.

1. create a file `src/zone_flags.ts` with the following content.
```
(window as any).__Zone_ignore_on_properties = [
  {
    target: window,
    ignoreProperties: ["load"],
  },
  {
    target: HTMLIFrameElement.prototype,
    ignoreProperties: ["load"],
  },
  {
    target: HTMLElement.prototype,
    ignoreProperties: ["load"],
  },
]; // disable patch specified eventNames

```

2. Import this file from `polyfills.ts`.
```

/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
import "./zone_patch";
import "zone.js/dist/zone"; // Included with Angular CLI
```

**Comment by achenPDFTron** [comment]
@gkalpak @JiaLiPassion Thank-you very much for taking the time to look into the issue.
I have tried the workaround proposed and it looks to have worked.

You are correct that we internally in the WebViewer code we are doing the following:
pdf CoreControls.js override iframe.addEventListener and doesn't really register the event listener to the native window but only keep the event listeners locally.

I will check internally with my team of why we are doing things this way.

**Comment by gkalpak** [comment]
Thx for getting to the bottom of this, @JiaLiPassion! And thx, @achenPDFTron for confirming.
I am going to close this issue since there doesn't seem to be any action to be taken by us at the moment, but feel free to continue the discussion below (or open a new issue) if you think there is something we need to fix/change.
