### ISSUE TITLE
Content children of angular element is not working in non angular application. 

### ISSUE THREAD

**Issue by ecemitrasharma** [angular/angular#42236]
[Problem Statement : 
I have existing aspx application where I wanted to replace old controls with angular elements. 

I developed below sample component 

```
<tabs>
    <tab-item [title]="tab1">Some content</tab-item>
    <tab-item [title]="tab2">Some content</tab-item>
</tabs>
```
 
I have 2 component 
1. Tabs Component 
2. TabItem

So in Tabs component I have defined content children to read list of content inside tab. 

`@ContentChildren(forwardRef(() => TabItemComponent))  tabs: QueryList<TabItemComponent>  = new QueryList<TabItemComponent>();
 `
in ngAfterContentInit i am printing length of tab.

I defined my Tab conponent as angular element and build the solution, Output in dist folder ==> main.js, polyfills.js and runtime.js.

I added all 3 JS reference in my aspx page I observe always content children length is 0 although I can see in dom tags added properly. 

Same I tested inside angular component it is working fine length is 2. 

Normally we use angular elements if we have non angular application so is angular not supporting content projection. 

Thanks in advance.
Mitra

**Comment by petebacondarwin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).
