### ISSUE TITLE
Support ICU messages (e.g. Plurals) at runtime $localize and create feature parity with template i18n

### ISSUE THREAD

**Issue by Kamshak** [angular/angular#42238]
# Feature Request

### Relevant Package

@angular/localize

Previous issue about this feature: https://github.com/angular/angular/issues/35912 (auto closed)

### Description

With the new `$localize` in Ivy we are finally able to do translations in code. This allows us to have strings in services or components (.ts files - "code") that are translated, which allows for very nice APIs. For example we can now open a modal or toast from an error handler somewhere inside of a service without creating a new component for every error message. 

Tagging strings in components is very similar to using templates:

```<div i18n="@@myId.buttonLabel">Submit</div> ```
```const buttonLabel = ':@@myId.buttonLabeal:Submit';```

However there is a difference in functionality. **In code, you cannot use plurals or other ICU messages**. For example, we have a pipe like this since our api returns numbers as `{ value: number, unit: string }`: 

```ts
const value: number = input.value;
const transformedValue = this.decimalPipe.transform(value, '1.0-2');
const unitMessages = {
    gal: $localize`:@@units.gal.long:{${value}, plural, =1 {1 gallon} other {${transformedValue} gallons}}`,
    gallons: $localize`:@@units.gallons.long:{${value}, plural, =1 {1 gallon} other {${transformedValue} gallons}}`,
    hl: $localize`:@@units.hl.long:{${value}, plural, =1 {1 hectoliter} other {${transformedValue} hectoliters}}`,
    liters: $localize`:@@units.liters.long:{${value}, plural, =1 {1 liter} other {${transformedValue} liters}}`,
    litres: $localize`:@@units.litres.long:{${value}, plural, =1 {1 liter} other {${transformedValue} liters}}`,
    pg: $localize`:@@units.pg.long:{${value}, plural, =1 {1 proof gallon} other {${transformedValue} proof gallons}}`,
    kg: $localize`:@@units.kg.long:{${value}, plural, =1 {1 kilogram} other {${transformedValue} kilograms}}`,
    lbs: $localize`:@@units.lbs.long:{${value}, plural, =1 {1 pound} other {${transformedValue} pounds}}`,
    tonne: $localize`:@@units.tonne.long:{${value}, plural, =1 {1 tonne} other {${transformedValue} tonnes}}`,
    tons: $localize`:@@units.tons.long:{${value}, plural, =1 {1 ton} other {${transformedValue} tons}}`,
}
return unitMessages[input.unit]: // Will return a translated ICU message - without replacing the plural
```

This is because in templates the compiler actually rewrites ICU pluralMessages into an ngSwitch. This also has the drawback that it only supports a subset of what is supported in ICU (see https://github.com/angular/angular/issues/9117)
 
### Describe the solution you'd like

It would be great to have feature parity between code i18n and template i18n. It could make sense to have a separate ICU message parser / compiler that does not generate an angular template AST but a JS AST instead. That way we could use the same implementation both from code and template.

For example js-lingui does it this way - messages are parsed during build time and compiled into functions. E.g. ```{value, plural, = 1 {1 gallon} other {# gallons}``` gets compiled to something like ```const t1 = value => value === 1 ? "1 gallon" : value + " gallons";```. There are libraries that use this concept, for example lingui or @messageformat/compiler. Alternatively the message could be parsed and interpreted at runtime. 

### Describe alternatives you've considered

To solve this without a change to angular it would be possible to expose a global function and ship a library like @messageformat/core to parse & execute the translated ICU messages returned by $localize. This would increase bundle size a lot.

Another alternative would be to stick to template translations. This requires the kind of ugly workaround that are luckily no longer needed for strings without plurals - thanks to the fantastic `@angular/localize` package!

**Comment by petebacondarwin** [comment]
This can already be achieved without any changes to the core framework, as described in the original issue, by importing the `intl-messageformat` package.

Moreover as long as you are not targeting IE11 you get the majority of the behaviour for free in browsers so the increase to the size of the bundles is quite small (~32Kb). This would also be comparable to what would be needed whether it was rolled in the core framework or not.

Here is the gist of the solution:

```ts
import { Component } from '@angular/core';
import IntlMessageFormat from 'intl-messageformat';

function formatIcu(icu: string) {
  const msg = new IntlMessageFormat(icu, $localize.locale);
  return (context: any) => msg.format(context);
}

const someICUMessage = formatIcu($localize`{count, plural, =0 {none} =1 {one} other {more}}`);

@Component({
  selector: 'app-root',
  template: `
    <div i18n>{{count}} - {count, plural, =0 {none} =1 {one} other {more}}</div>

    <button (click)="count = count + 1">+1</button>
    <button (click)="count = count - 1">-1</button>

    <pre>{{message}}</pre>
  `,
})
export class AppComponent {
  count = 0;


  get message() {
    return someICUMessage(this);
  }
}
```

Here is the repository to try it out: https://github.com/petebacondarwin/localize-icu-test

I would suggest that there is no benefit in additionally wrapping this up in the `@angular/localize` package since the solution is straightforward and cost effective.

**Comment by petebacondarwin** [comment]
Closing as this feature is very unlikely to be implemented as part of the core framework.
