### ISSUE TITLE
DI should not require nesting arrays when specifying deps

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#4224]
Currently the following does not work `bind(token).toFactory((one) => "one", [new Inject("one")]);` because the deps array has to be nested, as follows `bind(token).toFactory((one) => "one", [[new Inject("one")]]);`

DI should be able to handle it, so that the examples 1 and 2 should be equivalent.

**Comment by PascalPrecht** [comment]
I this only a problem when using `new Inject()` expression? Because with Types, this just works already...

**Comment by vsavkin** [comment]
Fixed https://github.com/angular/angular/commit/6514b8ced006c258fcb6334076a60b85a62277bd
