### ISSUE TITLE
Read query parameters from route

### ISSUE THREAD

**Issue by sumigoma** [angular/angular#4225]
Is there currently a way to read query parameters from the route? For instance, if RouteConfig is configured with { path: '/articles/:id', as: 'article', component: Article } and the user navigates in the browser to 

http://localhost:3000/articles/someId?sort=ASC&page=2

how do I get access to the value of "sort" and "page"? Will this be supported in the router?
(N.B. I can get id: "someId" through routeParams without a problem but I would like the query params. I see bits to generate queryParams and a "routeRecognizer" class, but no public methods..)

**Comment by PascalPrecht** [comment]
This should actually work as we can see here: https://github.com/angular/angular/blob/master/modules/angular2/test/router/integration/router_integration_spec.ts#L185-L203

Did you use `.get()` to get access to the value? https://github.com/angular/angular/blob/master/modules/angular2/test/router/integration/router_integration_spec.ts#L252

**Comment by sumigoma** [comment]
Ah, I see that this works indeed - where "sort" and "page" come in through routeParams.
```<a href="#" [router-link]="['/articles', {id:'someId',sort:'Asc',page:'2'}]">Some Link</a> ```

but I have a usecase where I'd like to share the URL i.e. have someone jump into that page directly through the browser address bar. Right now the router just redirects the user, omitting all query params and leaving only the first id param. Is there a workaround for this?

**Comment by btford** [comment]
@sumigoma there's a related known bug right now: #3957

**Comment by mhevery** [comment]
closing as dup
