### ISSUE TITLE
ivy/i18n - LOCALE_ID does not get replaced when provided in the app.module

### ISSUE THREAD

**Issue by bboehm86** [angular/angular#42266]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes. Without ivy enabled it works as before.

### Description

When using Ivy and [providing](https://github.com/bboehm86/bug-angular-locale-id-build/blob/master/src/app/app.module.ts#L9) a `LOCALE_ID` in the `app.module.ts` (e.g. "**en-US**") and building/serving the app with a different `i18nLocale` (e.g. "**de-DE**") set in the `angular.json` file, the `LOCALE_ID` will always be the provided one of the `app.module.ts` (so "**en-US**"). The rest is ok (eg `<html lang="de-DE">` and the translations...)

(When not providing a `LOCALE_ID` in the `app.module.ts` it does work correctly!)

## 🔬 Minimal Reproduction

1. Clone https://github.com/bboehm86/bug-angular-locale-id-build & `npm install`
2. Run `yarn start -c de` (or `yarn build -c de`)
3. Check the served site printing the current `LOCALE_ID` -> "**en-US**" but it should be "**de-DE**" as it was set in the `angular.json` for the [de configuration](https://github.com/bboehm86/bug-angular-locale-id-build/blob/master/angular.json#L89) 

4. Open the `tsconfig.app.json` and change `"enableIvy": true` to ` "enableIvy": false`
5. Run `yarn start -c de` (or `yarn build -c de`) again
6. Check the served site printing the current and correct `LOCALE_ID` -> "**de-DE**"

## 🔥 Exception or Error
-

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-rc.8
Node: 12.13.1
OS: linux x64

Angular: 9.0.0-rc.8
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.8
@angular-devkit/build-angular     0.900.0-rc.8
@angular-devkit/build-optimizer   0.900.0-rc.8
@angular-devkit/build-webpack     0.900.0-rc.8
@angular-devkit/core              9.0.0-rc.8
@angular-devkit/schematics        9.0.0-rc.8
@angular/localize                 9.0.0-rc.0
@ngtools/webpack                  9.0.0-rc.8
@schematics/angular               9.0.0-rc.8
@schematics/update                0.900.0-rc.8
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Anything else relevant?**
If the change was intend it would be nice to mention it in the Update Guide :-)

**Comment by Blucbo** [comment]
@clydin 
Also, have this issue with A10, but I do not override LOCALE_ID.
After the localized build, LOCALE_ID do not replaced
@bboehm86 How do solve this issue?

**Comment by jessicajaniuk** [comment]
Recently the [documentation for i18n](https://angular.io/guide/i18n-overview) was fully revamped with the most detailed information on how to properly do i18n. If you find some missing pieces of documentation, please file a new issue.
