### ISSUE TITLE
`zone.js/lib/jasmine/jasmine.ts` references `process` which causes runtime errors in browser

### ISSUE THREAD

**Issue by NikGovorov** [angular/angular#42260]
# Bug Report

### Affected Package
https://github.com/angular/angular/blob/master/packages/zone.js/lib/jasmine/jasmine.ts#L69

### Is this a regression?
Partially

### Description
Angular CLI 12 switched to Webpack 5 which dropped support of  automatic node polyfills: https://github.com/webpack/changelog-v5#automatic-nodejs-polyfills-removed

## Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.0.1
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@schematics/angular             12.0.1
ng-packagr                      12.0.0
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Comment by JiaLiPassion** [comment]
I will check it, thank for posting the issue. @NikGovorov NikGovorov
