### ISSUE TITLE
HTML debugging mode for templates

### ISSUE THREAD

**Issue by kutec** [angular/angular#42269]
# Add HTML debugging mode for templates

### Description
I am not sure if this is a good idea or not but this idea just popped up in my mind and I think that this can be a good feature for developers.

The idea is to add data attributes automatically based on added other attributes over the element. Consider below HTML code for example:

**HTML**
```
<span [innerHtml]="config?.variableName"></span>
```
**HTML output with debugging feature enabled**
```
<span data-inner="config?.variableName"
      [innerHtml]="config?.variableName"></span>
```
OR maybe this

**HTML**
```
<ng-container *ngIf='someIfCondition'>
    <span [innerHtml]="config?.variableName"></span>
</ng-container>
```
**HTML output with debugging feature enabled**
```
<ng-container *ngIf='someIfCondition'>
    <span data-if="someIfCondition"
          data-inner="config?.variableName"
          [innerHtml]="config?.variableName"></span>
</ng-container>
```

This would make debugging and searching in HTML code even more efficient and faster.

Thanks.

**Comment by alxhub** [comment]
@kutec Angular already does this! In dev mode, bindings also add an `ng-reflect-` prefixed attribute with the bound value stringified, for easier debugging.

**Comment by kutec** [comment]
@alxhub thanks for your reaction here. 

However, I think, `ng-reflect-` is not the same thing for which I have raised this request for.

`ng-reflect-` does resolve **the values for model, dynamic classes**, etc. Whereas, here I have suggested adding `data-` attributes to clearly visible the bounded object keys over the HTML element. 

(Please revisit the example above under the description.) 
Quick example: 
```
// input
<ng-container *ngIf="objectName?.keyName"><div [innerHtml]="objectName?.keyName"></div></ng-container>

// output
<div [innerHtml]="objectName?.keyName" data-inner="objectName?.keyName" data-if="objectName?.keyName"></div>
```
**_Pease notice the output above that we are passing object keys as passed to `innerHtml` and `ngIf`` and NOT THE VALUE OF IT_**. And I guess this is a big difference here while comparing this feature with `ng-reflect-`.

Requesting to reopen the issue as this is for a different purpose than what you've closed with.

Thanks.

**Comment by petebacondarwin** [comment]
I can see that this request is different to what we provide via `ng-reflect-...`
`ng-reflect-` shows the evaluated binding value, while you want the original expression to be displayed.

Let's reopen this issue and let the voting show the level of interest.

**Comment by kutec** [comment]
Thanks, @petebacondarwin.

**Comment by JoostK** [comment]
We've discussed this request and don't want to go forward with this at the time.
