### ISSUE TITLE
Can i set dynamically the templateUrl in component meta data

### ISSUE THREAD

**Issue by tripurarisingh1994** [angular/angular#42270]
Hi,
    Can i set dynamically the templateUrl in component meta data. I am setting like below

const env = true

@Component({
  selector: "app-product-tile",
  templateUrl: env ? "./product-tile.component-v2.html" : "./product-tile.component.html",
  styleUrls: ["./product-tile.component.scss"],
})

but It was not working as expected. It was showing me file name on view page
[
![image](https://user-images.githubusercontent.com/22842922/119368857-26331200-bcd1-11eb-9d13-fa7446503e94.png)
](url)

Can anyone suggest me how can i set templateUrl dynamically

Thank you!

**Comment by petebacondarwin** [comment]
There is the question of why and how you want to dynamically set the templateUrl.
You can see from this Stackblitz that it is possible: https://stackblitz.com/edit/angular-ivy-u45lkx?file=src%2Fapp%2Fapp.component.ts
I suspect you may have an error on your side. You may also want to check what version of Angular and whether you are using Ivy or not.

We reviewed this issue and determined that this issue doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).

**Comment by tripurarisingh1994** [comment]
Thanks!
