### ISSUE TITLE
nginclude - properties declared in onload can't be modified

### ISSUE THREAD

**Issue by pelallemant** [angular/angular#4227]
Hi,

When I use `<nginclude ... onload="element = some_scope_element"></nginclude>` :

I can edit "element" with:  `<a ng-click="element.someattribute = somevalue;">click here</a>`

I can't change the "element" with: `<a ng-click="element = {name: "mynewelement"};">click here</a>`

I'm searching a way to modify a property set inside the onload, and I didn't find it, so I think it's an issue.

Best regards,

Pierre-Emmanuel

**Comment by pkozlowski-opensource** [comment]
@pelallemant this is wrong repo. This one is for ng2, I guess you meant to open in https://github.com/angular/angular.js

Having said this it sounds like a general support question so you should try a support channel first: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
GitHub issues are only for bug reports / feature requests.
