### ISSUE TITLE
aio's `yarn serve` fails due to Injector.json and INJECTOR.json conflict 

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#42296]
# Bug Report

### Affected Package

`/aio/`

### Is this a regression?

yes, this used to work

### Description
 A clear and concise description of the problem...

## Minimal Reproduction

```
cd aio
yarn install
yarn start
```
## Exception or Error
<pre><code>
✖ ｢wdm｣: Error: Prevent writing to file that only differs in casing or query string from already written file.
This will lead to a race-condition and corrupted files on case-insensitive file systems.
/usr/local/google/home/iminar/Development/angular/aio/dist/generated/docs/api/core/Injector.json
/usr/local/google/home/iminar/Development/angular/aio/dist/generated/docs/api/core/INJECTOR.json
    at checkSimilarFile (/usr/local/google/home/iminar/Development/angular/aio/node_modules/webpack/lib/Compiler.js:625:22)
    at writeOut (/usr/local/google/home/iminar/Development/angular/aio/node_modules/webpack/lib/Compiler.js:807:11)
    at /usr/local/google/home/iminar/Development/angular/aio/node_modules/webpack/lib/util/fs.js:227:5
    at Immediate._onImmediate (/usr/local/google/home/iminar/Development/angular/aio/node_modules/memory-fs/lib/MemoryFileSystem.js:303:5)
    at processImmediate (internal/timers.js:462:21)
</code></pre>

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 12.0.1
Node: 14.17.0
Package Manager: yarn 1.22.10
OS: linux x64

Angular: 12.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@schematics/angular             12.0.1
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Anything else relevant?**

It seems that the conflict has been around for a while but it was silently ignored before. It's possible that it was the upgrade of cli to webpack v5 that surfaced this issue.

`ng build`/`yarn build` in aio works just fine, which explains why this has not failed on CI.

I've tested this on linux only so far, and I'm a bit surprised that none of the docs authors raised this issue. If we confirm that this is indeed a problem affecting all platforms then we might want highly prioritize this fix.

Update: workaround for the problem is to use `yarn serve-and-sync` - this explains why docs folks have not been blocked by this issue.

**Comment by petebacondarwin** [comment]
This should not be an issue since https://github.com/angular/angular/pull/41788.
Can you clean out and regenerate the docs via a call to `yarn setup`.

**Comment by IgorMinar** [comment]
I think you are right. I deleted node_modules and everything works well now. It's odd that my node_modules got into a bad state. thanks for the note.
