### ISSUE TITLE
Support safe function calls in templates

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#42298]
This ticket is a followup from PR #41911, which introduces safe keyed read expressions. We should also consider adding a support for safe function calls in templates such as:

```
{{ someObj.method?.() }}
```

See https://github.com/angular/angular/pull/41911#issuecomment-840828102 (and related discussion in PR #41911) for additional information.

**Comment by crisbeto** [comment]
I'll look into adding this once https://github.com/angular/angular/pull/41911 is merged since it'll touch the same files.
