### ISSUE TITLE
In tests: Cannot delete property 'ɵcmp' of class

### ISSUE THREAD

**Issue by ersimont** [angular/angular#42299]
# Bug Report

### Is this a regression?

Yes, the previous version in which this bug was not present was: 11.0.2

### Description

Cannot `enableProdMode()` with tests that contain a component that comes from a library. I usually run my tests with `enableProdMode()` to speed them up.

## Minimal Reproduction

```ts
// A library component written like this...
//
// @Component({ template: '' })
// class MyComponent {}
//
// ...ends up in its dist/ like this:
class MyComponent {}
(MyComponent as any).decorators = [
  { type: Component, args: [{ template: '' }] },
];

// Uncomment to to activate the bug:
// enableProdMode();

describe('MyComponent', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({ declarations: [MyComponent] });
  });

  it('can run two tests in a row', () => {
    TestBed.createComponent(MyComponent);
  });

  it('can run two tests in a row', () => {
    TestBed.createComponent(MyComponent);
  });
});
```

## Exception or Error
<pre><code>
TypeError: Cannot delete property 'ɵcmp' of class MyComponent {
}
</code></pre>

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 12.0.1
Node: 12.18.1
Package Manager: yarn 1.19.1
OS: win32 x64

Angular: 12.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@angular/fire                   6.1.5
@schematics/angular             12.0.1
rxjs                            6.6.3
typescript                      4.2.4
</code></pre>

**Comment by jessicajaniuk** [comment]
Thanks for submitting this. The use case here is not common and writing tests in prod mode is not something we intend to support.
