### ISSUE TITLE
Missing NG_VALIDATORS from angular2.d.ts

### ISSUE THREAD

**Issue by cghislai** [angular/angular#4229]
Using alpha37, I expected the changes introduced by this commit (https://github.com/angular/angular/commit/79994b2abfd598ffbdee2cf1b29442e90c6b414d) to be present.

But compiler complains that NG_VALIDATORS has not been exported.

Edit: My tsd.d.ts contains the following:
```
/// <reference path="../node_modules/angular2/bundles/typings/angular2/angular2.d.ts" />
/// <reference path="../node_modules/angular2/bundles/typings/angular2/http.d.ts" />
/// <reference path="../node_modules/angular2/bundles/typings/angular2/router.d.ts" />
```
Angular2.d.ts contains the following header:
```
// Type definitions for Angular v2.0.0-local_sha.7374153
```

**Comment by pkozlowski-opensource** [comment]
> Using alpha37, I expected the changes introduced by this commit (79994b2) to be present.

Nope, this is not the case, see:
https://github.com/angular/angular/commits/7374153db562fecad3490f5bf8ad8193523ab21a

We can release an arbitrary point and .37 has commits till ~ 2nd of September.
