### ISSUE TITLE
ng-if bug: model not updated controller-side in select

### ISSUE THREAD

**Issue by marcesso** [angular/angular#4230]
Hello,

Here is the pluker:
http://plnkr.co/edit/6ak03OKD996ybeGWA3YS?p=preview
You can see 2 drop down lists: the 1st one is always displayed, the 2nd is displayed if ng-if=true (my case study was to display the 2nd if the 1st one had a selected item).
I print in the console the value selected in the 2nd drop down, via ng-change function. You can see that the value of select doesn't change.
Remove ng-if, and it works. You can try with ng-hide or ng-show, the model is correcty updated as well.
Look at {{selectedAccount}}, the value always matches the selected item (with ng-if, ng-hide or nothing), the bug is controller-side only.

Thanks for having a look
Marie

**Comment by pkozlowski-opensource** [comment]
@marcesso this is wrong repo. This one is for ng2, I guess you meant to open in https://github.com/angular/angular.js

Having said this it sounds like a general support question so you should try a support channel first: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
GitHub issues are only for bug reports / feature requests. 

After having a quick look at your code you seem to missing how scopes works in AngularJS, make sure to go over this doc: https://github.com/angular/angular.js/wiki/Understanding-Scopes

**Comment by marcesso** [comment]
sorry about wrong repo
I read the doc about scopes but I didn't found nothing about ng-if behaviour
the code is broken only if I add ng-if so I think that there is a bug

**Comment by pkozlowski-opensource** [comment]
> the code is broken only if I add ng-if so I think that there is a bug

There is _no_ bug. ngIf is simply creating a new scope with all its consequences. Go over the linked doc or google for "angular dot in model", ex.: http://stackoverflow.com/questions/17606936/angularjs-dot-in-ng-model

**Comment by marcesso** [comment]
Thanks for your answer, I didn't see that ng-if documentation explained how a new scope was created.
Sorry about that and many thanks for your help
