### ISSUE TITLE
App not running up on removing unsafe-eval for restricted CSP

### ISSUE THREAD

**Issue by 404shades** [angular/angular#42303]
# Bug Report

### Description
My Application has restricted CSP which does not allow unsafe-eval for scripts. On adding a Content-Security-Policy header without unsafe-eval my application fails to load up.

## Minimal Reproduction
 I am passing this restrictive CSP header through nginx proxy configuration file .
<pre><code> add_header Content-Security-Policy "default-src 'self';  script-src 'self' 'nonce-$request_id'   </code></pre>
I have removed the unsafe-eval here which is causing this issue while loading up the application
<pre><code>Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'</code></pre>

You can add this CSP directly in index.html file for reproducing this error
<pre><code class="language-html">&lt;meta http-equiv="Content-Security-Policy" content= "default-src 'self' 'nonce-$request_id' ; script-src 'self' 'nonce-$request_id' ; style-src 'self' 'unsafe-inline'; frame-ancestors 'self';"&gt;
</pre></code>

I am using angular version 9 with aot enabled in my project.

## Exception or Error
<pre><code>
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'nonce-17279687d574ebf5358210888e9e9395'".

    at new Function (<anonymous>)
    at b.N (vendor.c63b596435f6d085789d.js:1)
    at b.c (vendor.c63b596435f6d085789d.js:1)
    at Object.D [as resolveRef] (vendor.c63b596435f6d085789d.js:1)
    at Object.t.exports [as code] (vendor.c63b596435f6d085789d.js:1)
    at Object.t.exports [as validate] (vendor.c63b596435f6d085789d.js:1)
    at Object.t.exports [as code] (vendor.c63b596435f6d085789d.js:1)
    at t.exports (vendor.c63b596435f6d085789d.js:1)
    at N (vendor.c63b596435f6d085789d.js:1)
    at b.t (vendor.c63b596435f6d085789d.js:1

</code></pre>

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.13
Node: 16.2.0
OS: win32 x64

Angular: 9.1.13
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.13
@angular-devkit/build-angular     0.901.13
@angular-devkit/build-optimizer   0.901.13
@angular-devkit/build-webpack     0.901.13
@angular-devkit/core              9.1.13
@angular-devkit/schematics        9.1.13
@angular/cdk                      9.2.4
@angular/material                 9.2.4
@ngtools/webpack                  9.1.13
@schematics/angular               9.1.13
@schematics/update                0.901.13
rxjs                              6.6.3
typescript                        3.8.3
webpack                           4.42.0
    

</code></pre>

**Comment by zarend** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by TekSiDoT** [comment]
@zarend This does indeed not seem to be a support request. It may well be a duplicate or related to #6361, but imho it's a valid (and important) issue.

**Comment by petebacondarwin** [comment]
Re-opening just until we can check whether the Angular framework is generating eval statements. This should not be happening in AOT Ivy code, AFAIK. It would happen if you are using some JIT compilation, or perhaps if a 3rd party library is doing something dynamic. Please can you provide a runnable reproduction to demonstrate that this `new Function()` call is actually coming from the Angular framework? Perhaps turning off minimization of the code so the call stack is more helpful.

**Comment by 404shades** [comment]
Sorry Cant reproduce the issue due to some confidential stuff I can't share the details here. But I have figured out a package is causing this issue. and when I migrated my angular project to v12 without that package it is working fine without unsafe-eval. Thanks for helping out 😀

**Comment by JoostK** [comment]
Closing as it appears this has been resolved. Thanks for confirming you no longer have this issue, @404shades.

**Comment by 404shades** [comment]
I am getting issue when i removed unsafe-inline from headers. 
vendor.d69c112a367a1fcd435e.js:152721 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.
