### ISSUE TITLE
componentFactory.resolveComponentFactory() is not working in Edge chromium post Ver. (90.0.818.51) and Chrome Ver. (90.0.4430.85)

### ISSUE THREAD

**Issue by abhis00786** [angular/angular#42318]
# Bug Report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, it is compatible with previous version of chrome
 Yes, the previous version in which this bug was not present was: Yes

### Description
 I am using below snippet for rendering dynamic model content loaded into popup body. This code fine with the older version of below **Edge chromium post Ver. (90.0.818.51) and Chrome Ver. (90.0.4430.85)** but it not version on mentioned version or post version.

Though we are not getting any error for the same and log. The code execute fine with no error.

**Code Snippet**

let componentFactory = this.componentFactoryResolver.resolveComponentFactory(component);
let viewComponentRef= this.popBodyContainer.viewContainerRef;
viewComponentRef.clear();

let componentRef= this.viewComponentRef.createComponent(componentFactory);

## Minimal Reproduction

 https://stackblitz.com/...

## Exception or Error
<pre><code>

let componentFactory = this.componentFactoryResolver.resolveComponentFactory(component);
let viewComponentRef= this.popBodyContainer.viewContainerRef;
viewComponentRef.clear();

let componentRef= this.viewComponentRef.createComponent(componentFactory);
</code></pre>

## I am getting this issue on UAT,PROD,DEV all the enviornment.

**Angular Version:**
<pre><code>
Angular CLI: 1.7.4
Node:12.7.0
Angular:4.4.7
@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.9.2
webpack-dev-starter: 2.5.1
webpack-merge: 4.2.2
webpack: 3.12.0

</code></pre>

**Anything else relevant?**

Edge chromium post Ver. (90.0.818.51) and Chrome Ver. (90.0.4430.85)

**Comment by JoostK** [comment]
Hi, could you please provide a runnable reproduction, either a StackBlitz or a Github repo, that shows this issue. Also please share the versions of Angular you are using as without this information this issue isn't actionable for us.

**Comment by JoostK** [comment]
I notice you have amended the post with version information, and I'm sorry to tell you that Angular 4 is no longer supported. I'd recommend updating to a recent version of Angular.
