### ISSUE TITLE
ngAnimate doesn't work when you use ngView on the body

### ISSUE THREAD

**Issue by dantheman999301** [angular/angular#4232]
http://plnkr.co/edit/PgfQaoDE5iCaxV2AX8OA

Example here. Basically it doesn't add the intermediate classes when showing and hiding.

The workaround is pretty simple, just don't use ngView on the body. In the example if you move ngView down onto a div it works fine. 

There are a few scattered issues on stackoverflow where it does say you get some odd behaviour when adding ngView to the body but most of them aren't serious. If we shouldn't be doing this, I think there should be a warning in the docs about it.

**Comment by PascalPrecht** [comment]
@dantheman999301 this is the Angular 2 repository. Please close this one and file your issue at http://github.com/angular/angular.js

Thanks!

**Comment by dantheman999301** [comment]
My apologies!
