### ISSUE TITLE
Child canLoad executes before parent canActivate on child reload (ref 27826)

### ISSUE THREAD

**Issue by skwny** [angular/angular#42328]
[Issue 27826 ](https://github.com/angular/angular/issues/27826) was closed and locked, but this is still an issue and I constantly run into friction when designing routes due to this issue. Please re-open.

It also appears as an issue in [15670](https://github.com/angular/angular/issues/15670).

**Comment by atscott** [comment]
This is working as intended. All `canLoad` guards execute as part of the initial stage of determining the final url of the navigation. Other guards and resolvers execute at a later stage after the router has determined the config activation path.
