### ISSUE TITLE
docs: `BannerComponent` test setup issue

### ISSUE THREAD

**Issue by swseverance** [angular/angular#42325]
# Docs or angular.io Bug Report

### Description

The "Component Testing Scenarios" documentation provides the following example:

```ts
// app/banner/banner.component.spec.ts (setup)

let component: BannerComponent;
let fixture: ComponentFixture<BannerComponent>;
let h1: HTMLElement;

beforeEach(async () => {
  await TestBed.configureTestingModule({
    declarations: [ BannerComponent ],
  });
  fixture = TestBed.createComponent(BannerComponent);
  component = fixture.componentInstance; // BannerComponent test instance
  h1 = fixture.nativeElement.querySelector('h1');
});
```

There's a small issue in the use of `await TestBed.configureTestingModule(...)` in that the method does not return a promise, so it does not make sense to `await` it. There are two potential fixes to the documentation:

1. simply add `.compileComponents()` to get:

```ts
// app/banner/banner.component.spec.ts (setup)

let component: BannerComponent;
let fixture: ComponentFixture<BannerComponent>;
let h1: HTMLElement;

beforeEach(async () => {
  await TestBed.configureTestingModule({
    declarations: [ BannerComponent ],
  }).compileComponents();
  fixture = TestBed.createComponent(BannerComponent);
  component = fixture.componentInstance; // BannerComponent test instance
  h1 = fixture.nativeElement.querySelector('h1');
});
```

2. recognize that `BannerComponent` has both an inline template and inline styles, therefore `.compileComponents()` is not necessary so references to `async` and `await` can be removed. this leads to:

```ts
// app/banner/banner.component.spec.ts (setup)

let component: BannerComponent;
let fixture: ComponentFixture<BannerComponent>;
let h1: HTMLElement;

beforeEach(() => {
  TestBed.configureTestingModule({
    declarations: [ BannerComponent ],
  });
  fixture = TestBed.createComponent(BannerComponent);
  component = fixture.componentInstance; // BannerComponent test instance
  h1 = fixture.nativeElement.querySelector('h1');
});
```

**I'd like to submit a PR to fix the issue. Can you tell me which approach you would like me to take?**

### What's the affected URL?**

https://angular.io/guide/testing-components-scenarios

### Reproduction Steps**

Visit https://angular.io/guide/testing-components-scenarios

## Exception or Error
<pre><code>

</code></pre>

**Comment by petebacondarwin** [comment]
So reading through the guide the problem is that this code snippet is being used in two places.

- The [Component binding](https://angular.io/guide/testing-components-scenarios#component-binding) section, which I think is the one you are referring to, where we should remove the async-await keywords. 
- The [Calling compileComponents](https://angular.io/guide/testing-components-scenarios#calling-compilecomponents) section, where we actually do want this broken code, because that is the point of the section.

Perhaps the solution is to split up the example into these two parts?
