### ISSUE TITLE
bug(router): target attribute not respected when used with router-link

### ISSUE THREAD

**Issue by btford** [angular/angular#4233]
```html
<a [router-link]="['/account']" target="_blank">Account</a>
```

The expectation is that this link should open in a separate tab/window.

Tracks internal b/24125739.

**Comment by btford** [comment]
@jeffbcross Could you please help with this? It should be as easy as checking the value of the `target` attribute and not cancelling the event here: https://github.com/angular/angular/blob/master/modules/angular2/src/router/router_link.ts#L67-L69

**Comment by jeffbcross** [comment]
I'm on it!
