### ISSUE TITLE
Angular JS 1 api reference page is broken

### ISSUE THREAD

**Issue by tpiere** [angular/angular#4234]
I'm not sure if this is the correct place to report an issue with the angular.js website....but the API reference page is not working:

https://docs.angularjs.org/api

See attached screenshot.  It looks like the version is missing from the url to load angular scripts.

![angular-js-api-reference-errors](https://cloud.githubusercontent.com/assets/1138652/9934468/47757c48-5d17-11e5-9503-f3462d3d29a7.png)

**Comment by pkozlowski-opensource** [comment]
Right, tracked in https://github.com/angular/angular.js/issues/12877
