### ISSUE TITLE
ng is working but ng serve is not working i.e problem in serve

### ISSUE THREAD

**Issue by Manikkashyap** [angular/angular#42348]
My ng serve is not working suddenly  when i command for ng g c for creating component for me but when i use ng serve it does not show any error only terminate the command and goes to the next line .

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
