### ISSUE TITLE
inconsistent css behavior in inline SVGs

### ISSUE THREAD

**Issue by takahser** [angular/angular#42345]
# Bug Report

### Affected Package
unknown

### Is this a regression?
unknown

### Description
I want to display an inline svg in 100% width. The following code works when using vanilla html/css without any framework:

HTML:
```
<div class="svg-box">
  <svg class="svg-box-content" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewbox="0 0 2000 857">
    <!--etc-->
  </svg>
</div>
```

CSS:
```
.svg-box {
    width: 100%;
    height: 0;
    padding-top: 100%; /* Aspect ratio */ 
    position: relative;
}

.svg-box-content {
    position: absolute;
    top: 0;
    left: 0;
}
```
![image](https://user-images.githubusercontent.com/5393704/119630018-d5293800-be0e-11eb-8515-92a92ac1fcb5.png)

However, when using the exact same code in Angular the svg is cut off. 

![image](https://user-images.githubusercontent.com/5393704/119630069-e114fa00-be0e-11eb-95c4-2a6e495d5b02.png)

## Minimal Reproduction

without Angular: https://jsfiddle.net/q07fp6nx/
with Angular: https://stackblitz.com/edit/angular-vvmcnk?file=src%2Fapp%2Fapp.component.css

## Exception or Error
-

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.1.4
Node: 12.22.1
OS: darwin x64

Angular: 10.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.4
@angular-devkit/build-angular   0.1001.4
@angular-devkit/core            10.1.4
@angular-devkit/schematics      10.1.4
@angular/cdk                    10.2.4
@angular/flex-layout            10.0.0-beta.32
@angular/material               10.2.4
@schematics/angular             10.1.4
@schematics/update              0.1001.4
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Anything else relevant?**
- tested on OS X, Brave v1.24.85 and Safari v14.0.3

**Comment by Totati** [comment]
Hi, replace `viewbox` with `viewBox` and it will work:
https://stackblitz.com/edit/angular-gthrqx?file=src%2Fapp%2Fapp.component.html

**Comment by petebacondarwin** [comment]
SVG is [case-sensitive](http://thenewcode.com/1151/Understanding-the-SVG-viewBox#:~:text=Also%20note%20the%20capitalization%20of,it%20is%20to%20be%20recognized.&text=It's%20important%20to%20note%20that,%E2%80%9Cinto%E2%80%9D%20the%20viewable%20area.).

Closing as this is not an issue with the Angular framework.

**Comment by takahser** [comment]
@Totati Thanks, yes that works. You're correct, when inspecting the output on jsfiddle the `viewBox` is actually corrected and hence different from the source code. So not an Angular issue.
