### ISSUE TITLE
Transformer: refactor to use new TemplateCompiler

### ISSUE THREAD

**Issue by tbosch** [angular/angular#4235]
See https://github.com/angular/angular/blob/master/modules/angular2/src/compiler/template_compiler.ts

## Process

Phase 1:

1. walk over all files that contain directives and create an instance of [`DirectiveMetadata`](https://github.com/angular/angular/blob/master/modules/angular2/src/compiler/directive_metadata.ts#L142)
2. normalize this `DirectiveMetadata` via a call to `TemplateCompiler. normalizeDirective` (this also reads in the template)
3. optionally serialize the normalized meta data via a call to `TemplateCompiler.serializeDirective` into a JSON string

Phase 2:

1. walk over all files again, read the metadata of components defined in this file and the metadata of all directives that are referenced by the `@View` annotation of these components
2. call `TemplateCompiler. compileTemplatesCodeGen` which will output a dart file called `<input-file>.template.dart`. This will contain exports with the host views for every component in the form `var Host<CompClassName>Template = new CompiledTemplate(...)`
3. provision these `CompiledTemplate` as annotations into the reflector. I.e. the annotation for the class `CompiledTemplate` of a component class should have the value of the host `CompiledTemplate`.

Phase 3 (in parallel to Phase 2):

1. walk over all stylesheets (`*.css`) and call `TemplateCompiler. compileStylesheetCodeGen`, which will generate a dart file that is included by the generated template file.

## Notes

- The output of the codegen methods are `SourceModule`s. These have a method `getSourceAndImports` which will return the source and the imports (import alias and module id) that need to be added to the source.
- `SourceModule`s also have a `moduleId` which is the filename of the file that should be generated without the `.dart` suffix. Keeping the filename is important as generated files reference each other.

**Comment by tbosch** [comment]
Note: This needs to be merged at the same time as the runtime parts of the new compiler land...

**Comment by kegluneq** [comment]
Closed in (and around) 52236bd76570088b3856282cbbe9fd91d0d0a9a7
