### ISSUE TITLE
FormBuilder.group typings doesn't work as expected

### ISSUE THREAD

**Issue by lilotop** [angular/angular#4239]
Found during js-il ng2 hackathon.

fb.group({street: [this.address.street, required]});
throws an error - unexpected type.

Victor Savkin of the angular team suggested the following workaround for now:

fb.group(<any>{street: [this.address.street, required]});

**Comment by tcigrand** [comment]
Those two lines are identical.

**Comment by yanivefraim** [comment]
@lilotop - can you explain what is not working? Those two lines you gave are identical. 
10x

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
