### ISSUE TITLE
Use StackBlitz WebContainers in Angular tutorials and examples 

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#42404]
# Feature Request

It would be awesome if Angular tutorials and examples used WebContainers (see https://blog.stackblitz.com/posts/introducing-webcontainers/).

Using this technology would enable the reader to have a full CLI experience in the browser without having to go through any local installation or setup.

Additionally we would be able to simplify our docs and some docs infrastructure.

A good example of where our current approach fails is https://angular.io/start where we heavily rely on StackBlitz without webcontainers (which emulates Angular CLI but has gaps) and the conclusion of the tutorial https://angular.io/start/start-deployment where we ask people to install CLI, generate a new project, and copy their stackblitz code manually into the CLI project (which can be confusing, see #32524).

With webcontainers, the readers would be using the CLI from the beginning without a local environment setup, since the CLI would run in the browser.

**Comment by IgorMinar** [comment]
btw I tried to create an Angular CLI project in a webcontainer and ran into an issue saving a project: https://github.com/stackblitz/webcontainer-core/issues/109

I was able to create the project and start the dev server, so it seems that at a fundamental level this will work, but the webcontainer needs a bit more polish.

**Comment by EricSimons** [comment]
Thanks for filing the issue over in our repo- totally agree that this provides a better UX especially for the tutorial section 💪

**Comment by iRealNirmal** [comment]
Just FYI, when I visited it in safari browser it says
`StackBlitz v2 Beta currently works in Chrome and Chromium-based browsers. We’re hoping to add support for more browsers as they implement the necessary Web Platform features.`

Waiting for it to be more stable would be better approach here.

 But I am really looking for this change.

**Comment by IgorMinar** [comment]
@iRealNirmal yup. I suspect that some new WebAssembly APIs are needed for this to work, but I'm hopeful that Safari and Firefox will adopt them soon.

**Comment by IgorMinar** [comment]
I created a demo project that works around the current limitations and documents the current gotchas in the Readme.md: https://stackblitz.com/edit/ng-webcontainer

**Comment by BojanKogoj** [comment]
Why exactly is there a vote for this feature? Both Angular and Material docs will already open in StackBlitz which use WebContainers - using docs in Firefox is now pretty useless.
