### ISSUE TITLE
Possibility to add class="" using <ng-content>

### ISSUE THREAD

**Issue by mackelito** [angular/angular#42408]
# Feature Request
### Description
Currently the ng-content tag is just a placeholder that will be replaced.
When creating eg. a component library we might get code that is encapsulated and not easily styled by the library consumers.

eg.
````
<ng-content select="header"></ng-content>
<div class="content">
  <div class="body">
    <ng-content></ng-content>
  </div>
</div>
````
in this case the body class has a padding and to be able to change that padding library consumer need to use something like ::ng-deep.

### Describe the solution you'd like
Something like this perhaps?
````
<ng-content select="header"></ng-content>
<ng-content class="content"  select="content">
  <ng-content class="body"  select="body">
  </ng-content>
</ng-content>
````
and the classes would be merged..
This would allow ui component creator to have default styling and also make it easier to the consumers of the component to add styling :)

**Comment by vugar005** [comment]
Hi @mackelito , I wonder why `:host` or ` :host-context` not solved this issue? What problems did you experience?

**Comment by mackelito** [comment]
Well.. It might work (have not tested) but I also believe it to be a matter of mindset.. this override is not in any host context.. this should be the... "default override"? :)

**Comment by mackelito** [comment]
I'm not that experienced with `:host-context` but that would require a class on the host element.. right?
So each time we use the `<panel>` component we need to specify `<panel class="panel">` or something like that... right?

**Comment by vugar005** [comment]
Well, it depends on your taste.  You just specify class in parent div or components and apply those styles either in child component via host-context or via global styles. See: [this blog](https://blog.angular-university.io/angular-host-context/)

**Comment by indraraj26** [comment]
@mackelito I see even with :host-context css class is not getting applied for an ng-content. i don't know how Angular treat element as Host but We really need a way to inject classes directly from parent.

Playground To Test : https://stackblitz.com/edit/angular-ivy-9smnwr?file=src%2Fapp%2Fapp.component.html

With (:host-context).
I would say we need to find the way to inject the CSS directly from parent to child component and it will improve the bundling size, Right now what we do with :ng-context(.parent) in child component even for small changes, We write lot of :host-context(). User might not use other modules but still we load the CSS for them. 

Fancy Popup :host-context 
A Module -> A Component -> I want popup to be small, font size and color
B Module -> B Component -> I want popup to be large, font-size and color

But fancy popup will load the both component css :host-context and user might not use B Component.
 
It would be great to have some other way A module is loaded then its respective fancy popup host-context will be load.

**Comment by vugar005** [comment]
Hi @indraraj26 ,
Thanks for example. The problem in example is  you are using 
```
.child-body :host-context(.body) {
  color: red;
}
```
But element with body class is not parent, it is sibling. I changed it to 
```
.child-body :host-context(.outer-box) {
  color: red;
}
```
and it worked.

**Comment by indraraj26** [comment]
Thank you for your solution.

.child-body is an extra div element which needs to be wrap in order to apply css. but i would like to avoid this

is this possible?
example: 
1) parent will have 

```
<div class="outer-box">
<app-child>
<div class="body">Parent body</div>
</app-child>
</div>
```
```
.body {
color:orange;
}
```
child.html
```
<ng-content select=".body"><ng-content>
```

```
:host-context(.outer-box) :host-context(.body) {
 color: red
}
```

Priority is given to child css which is red and will override the parent body css.

(from mobile)

**Comment by vugar005** [comment]
@indraraj26  child-body is not needed, just remove child-body html and change 
```
.child-body :host-context(.outer-box) {
  color: red;
}
```
to 
```
:host-context(.outer-box) {
  color: red;
}
```

**Comment by vugar005** [comment]
> I'm not that experienced with `:host-context` but that would require a class on the host element.. right?
> So each time we use the `<panel>` component we need to specify `<panel class="panel">` or something like that... right?

Yes it requires parent class, but it is not required to have direct parent class.

**Comment by AndrewKushnir** [comment]
It looks like the problem described in this ticket is resolved, so I'm closing this ticket. Please reopen if needed.

**Comment by mackelito** [comment]
Sorry for being late to the party..
Here is an example of the situation:
https://stackblitz.com/edit/angular-ll37ir?file=src%2Fapp%2Fwrapper%2Fwrapper.component.html

As you can see the ::ng-deep selector is required
