### ISSUE TITLE
Application tutorial doesn't load throws error in console

### ISSUE THREAD

**Issue by zohorakhanum** [angular/angular#42413]
# Docs or angular.io Bug Report

### Description

Open angular.io, Try to access https://angular.io/guide/file-structure#library-project-files , blank page opens with the loading bar running for a long time. In the Console the following error has occured 
main-es2015.f87d58d17d647ca45b10.js:1 ERROR Error: [DocViewer] Error preparing document 'guide/file-structure': ChunkLoadError: Loading chunk 16 failed.

### What's the affected URL?**
https://angular.io/guide/file-structure#library-project-files

### Reproduction Steps**
Open angular.io
Click on 'Get started' for tutorial
Open the Creating libraries section from the Left menu
From the section click on link '**Project File structure**' available in the following text 'For more details on how a library project is structured, refer to the Library project files section of the Project File Structure guide.
Page doesn't load

### Expected vs Actual Behavior**
Expected : To be able to see info of project file structure
Actual: Empty section with loading bar running 
## Screenshot

![image](https://user-images.githubusercontent.com/61377829/120061405-b4fdb100-c07a-11eb-999c-c4204ab1cb64.png)

## Exception or Error
<pre><code>
![image](https://user-images.githubusercontent.com/61377829/120061406-b62ede00-c07a-11eb-8785-435a277cd7bf.png)

</code></pre>

## Your Environment

https://angular.io/guide/file-structure#library-project-files
### Anything else relevant?

Occurs only at some instances, but opening the project structure file from the menu doesn't cause error

**Comment by gkalpak** [comment]
I assume this should go away after a reload. Did you get any other info in the console when the error occcurred?

**Comment by zohorakhanum** [comment]
Hi,

I have tried the reload, it doesn't work for around 7-8 reloads, post which
the error is not seen and behaves as expected.

Also I have noted this happens whenever I open a new angular tab for any of
tutorial entities (page).

Regards,
Zohora Khanum Z L
Web Application Developer
Ph: 9600018676

**Comment by gkalpak** [comment]
Sorry, I dropped the ball on this one, @zohorakhanum.

You have hopefully been able to resolve the issue by now (i.e. load the docs successfully) 😅

Anyway, the error you were facing was most probably an occurrence of # #28114. We have deployed some potential fixes and are gathering debug info in #41117 (in case you run into the error again).

The error in the last image is a Firebase bug (see https://github.com/angular/angular/issues/42518#issuecomment-858545483 for more details) and has been fixed (read: worked around) in #42547.

##
I am going to close this now, but if you run into a similar error in the future please report it in a new issue (along with the console output) 🙏
