### ISSUE TITLE
Error Angular 12 parallel script launch

### ISSUE THREAD

**Issue by dvkudashev** [angular/angular#42416]
Error  __ngcc_lock_file__:

- If you are sure no ngcc process is running then you should delete the lock-file at `.../node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__`

- Another process, with id 31479, is currently running ngcc.
- Waiting up to 250s for it to finish.

Did not help:
```
  "scripts": {
    "postinstall": "ngcc"
  }
```

**Comment by gkalpak** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#submit-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
