### ISSUE TITLE
Angular build in cli way of i18n language translation depending on browser locale or browser default language

### ISSUE THREAD

**Issue by maheshwalasang** [angular/angular#42422]
I am using angular's build in i18n language translation. The way some blog post explains, but I want to switch the language by default, by looking into browser's default language. If my browser locale is French (fr) and when I browse my site as https://www.myi18nexample.com, content of the page should get loaded with french language labels/constants/strings. Can you please suggest how can I achieve this ?

Other few points to consider:

I want to show alert messages as per browser default language.
I want to show API response messages as alert or want to display as default language translated text. Ex: language ru: API response is Success but should alert message show as 'Успех'
Deployed app should not have path like https://www.myi18nexample.com/en/index.html or https://www.myi18nexample.com/ru/index.html should be as normal when we deploy without multi language deployment. And routing should also be normal without /en or /ru should be just https://www.myi18nexample.com/about_us as example
Can it behave as we deploy with ngx-translator library used.

Can we differentiate what is possible and what is not possible with i18n and ngx-translate. Compare both as apple to apple comparison.

browserlocale, localization by default browser language, no slash in url for language change, should behave as we deploy without localization

thanks

**Comment by petebacondarwin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).
