### ISSUE TITLE
google document in architecture.md isn't public

### ISSUE THREAD

**Issue by iRealNirmal** [angular/angular#42424]
I was going through readme.md of architecture 

[https://github.com/angular/angular/blob/master/packages/compiler/design/architecture.md](https://github.com/angular/angular/blob/master/packages/compiler/design/architecture.md)

Go to paragraph

`Additionally, more advanced type-checking as described in [Type Checking Templates](https://goo.gl/Q3tSgP) also requires determining the types of the directives that apply to an element as well as how the attributes map to the properties of the directives.
`
Document requires to send request for access.
### What's the affected URL?**
[https://github.com/angular/angular/blob/master/packages/compiler/design/architecture.md](https://github.com/angular/angular/blob/master/packages/compiler/design/architecture.md)

**Comment by mgechev** [comment]
The document is no longer relevant, so I opened #42840 to remove the link.

I'd recommend following the [ng-conf YouTube channel](https://www.youtube.com/c/ngconfonline/videos). Soon they'd publish the videos for the latest edition of the conference, which includes a talk by @alxhub and @JoostK, which focuses on how we perform type checking with the Ivy compiler.

**Comment by iRealNirmal** [comment]
@mgechev shouldn't we update architecture.md as well ? and thanks for the tip I have subscribed channel
