### ISSUE TITLE
Creator indication for resources page

### ISSUE THREAD

**Issue by bampakoa** [angular/angular#42430]
# Feature Request

### Relevant Package

 This feature request is for @angular/resources

### Description

Hello all,

I make extensive use of the Resources page of the angular.io and I was thinking that if I had a small indication (just like the API labels) of which resources are built specifically from the Angular team, it would be great. Knowing that a resource is maintained by a well-known team, makes you confident about the tool. The indication could be further improved and used even for adding a subcategory to each resource (such as which resource is made from another team such as Nx)

### Describe the solution you'd like
 
Below I have put an image from a PR that I am currently working on. What do you think?

![image](https://user-images.githubusercontent.com/7170892/120227063-28f1b200-c251-11eb-926e-f5dff60f270b.png)

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by Leosoft** [comment]
good

**Comment by mgechev** [comment]
Let's keep this outside the resources page for now. We're planning using a difference source for developer resources.
