### ISSUE TITLE
Improve Binding errors for directives

### ISSUE THREAD

**Issue by morsdyce** [angular/angular#4244]
In the hackaton today I've come across some very confusing error messages that could be greatly improved.

Here are some suggestions to improve these error messages if its possible to detect each case individually, the actual messages need some more work (english is not my first language) but the main direction should be letting you know what you did wrong.

I can see many people falling for these things, specially when new to angular2 syntax and not realising what they did wrong.

Ng-For Of
-------------
Example:
`*ng-for="item of collection"`

Result:
`EXCEPTION: Can't bind to 'ngFor' since it isn't a known property of the '<template>' element and there are no matching directives with a corresponding property`

Suggested: 
`EXCEPTION: Can't bind to 'ngFor' are you missing a reference? e.g #item of collection`

Ng-For In
-------------
Example:
`*ng-for="#item in collection"`

Result:
`Can't bind to 'ngForIn' since it isn't a known property of the '<template>' element and there are no matching directives with a corresponding property`

Suggested:
 `EXCEPTION: Missing ngForIn directive, did you remember to include it?`

Comments:
This is really unclear that you are supposed to inject NgForIn instead of NgFor, it is not obvious for most developers that they should use `of` instead of `in` in loops as many are still not using ES6 or typescript and even though who do remember the angular1 syntax which was `in`.

Either set in as the default NgFor or rename it to NgForOf, the template syntax would suffer a bit but it could save weird errors.
The perfect solution in my opinion is having only a single NgFor directive which will work with either `in` or `of`

Ng-For Of (no *)
-------------
Example:
`ng-for="#item of collection"`

Result:
No related error

Suggested: 
`EXCEPTION: Cannot use ng-for without asterisk declaration e.g *ng-for`

Comments:
I've called it asterisk declaration because I do not know the name for it, if there isn't one maybe there should be so we can reference it more easily.

Directive & Component missing properties
-------------
Example:
```
@Component({
 selector: 'my-app',
 properties: [],
})
@View({
 template: '<div>{{version}}</div>'
})
class MyApp {
  version:string;
}
```

Result:
`EXCEPTION: Can't bind to 'version' since it isn't a known property of the '<my-app>' element and there are no matching directives with a corresponding property`

Suggested: 
`EXCEPTION: Can't bind to 'version' since it isn't a known property of the '<my-app>' element. Did you remember to include it in the properties field?`

cc /@pkozlowski-opensource

**Comment by DennisRoam** [comment]
I wanted to add that [Viktor Savkin's blog article](http://victorsavkin.com/post/119943127151/angular-2-template-syntax) on the template syntax uses "in" instead of "of" which is confusing as that article is referenced all over the place.

I See now that "#items of collection" is correct but for-in makes more sense to me coming from Angular 1 and the basic forEach from other languages..

**Comment by vladimir-ivanov** [comment]
getting the same issue after upgrading to alpha53
<ul>
    <li *ng-for="#item of items">{{item}}</li>
</ul>

**Comment by ericmartinezr** [comment]
@vladimir-ivanov check the [changelog for a52](https://github.com/angular/angular/blob/master/CHANGELOG.md#200-alpha52-2015-12-10) and the [migration guide](https://github.com/angular/angular/blob/master/modules/angular2/docs/migration/kebab-case.md)

**Comment by DominikDitoIvosevic** [comment]
And what about `Can't bind to '*ngFor' since it isn't a known native property (` ?
Has it got something to do with nested ngFor's since the parent one is the same as this one and it works but this one doesn't?

**Comment by vicb** [comment]
This has been fixed in the latest releases
