### ISSUE TITLE
Router improperly serializes empty arrays with other params

### ISSUE THREAD

**Issue by krojew** [angular/angular#42445]
# Bug Report

### Affected Package
@angular/router

### Is this a regression?

Don't know.

### Description

When adding an array along with another param as a query param, the router tries to combine them using & during serialization to url. If the array is empty, this results in an empty text segment followed by &..

## Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-v6arzj?file=src/app/app.component.html

Take a look at the generated url.

## Exception or Error
<pre><code>

</code></pre>

## Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 11.2.4
Node: 12.13.0
OS: darwin x64

Angular: 11.2.5
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router, upgrade
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1102.4
@angular-devkit/build-angular      0.1102.4
@angular-devkit/core               11.2.4
@angular-devkit/schematics         11.2.4
@angular/cdk                       11.2.4
@angular/cli                       11.2.4
@angular/material                  11.2.4
@angular/material-moment-adapter   11.2.4
@schematics/angular                10.0.4
@schematics/update                 0.1102.4
ng-packagr                         11.2.4
rxjs                               6.5.4
typescript                         4.1.5
</code></pre>

**Anything else relevant?**

**Comment by natealcedo** [comment]
I'd like to take this up if it's up for grabs :)
