### ISSUE TITLE
docs: amend DeepDive podcast

### ISSUE THREAD

**Issue by dario-piotrowicz** [angular/angular#42446]
In the `resources.json` file the link for the deepDive podcast points to a 404 page:
https://github.com/angular/angular/blob/ea14b7f1e60aaaa815a14af2d62a93fb8d4effc8/aio/content/marketing/resources.json#L92

I am not sure what url should be used for the podcast (by googling it I could not find an official website for it).

I would suggest to just remove the podcast from the file as it does not really seem to be on par with the others in regards to the number of episodes and popularity.

**Comment by mgechev** [comment]
Thanks for the catch! Opened #42840.

**Comment by dario-piotrowicz** [comment]
Hi @mgechev, I actually already created a PR for the podcast's removal 😕 😞 😢

**Comment by mgechev** [comment]
@dario-piotrowicz I'm sorry I didn't see your PR :(. I saw you did extra changes to improve the keys in the map. Would you rebase and we should be able to merge?

**Comment by dario-piotrowicz** [comment]
@mgechev Ah no problem don't mention it :slightly_smiling_face: , after all I wasn't assigned to the issue and the PR was not linked to it, so I understand that you could have just missed it :slightly_smiling_face: 

Rebase done! :smiley:

**Comment by dario-piotrowicz** [comment]
PS: I am fan of yours, I love your content out there! :smiley:
