### ISSUE TITLE
Angular12 node_modules/@ngx-meta/core/meta.module.d.ts:8:21 - error TS2694: Namespace '"F:/demo/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDefWithMeta'

### ISSUE THREAD

**Issue by yangjunfocus** [angular/angular#42444]

**Comment by JoostK** [comment]
Heya, `@ngx-meta/core` is published to NPM using internal Ivy instructions for v9, which means that the library can only be used in an application using the exact same Angular version. Please contact the authors of `@ngx-meta/core` to publish their library in View Engine format (if targeting v9, v10, and/or v11) or using Ivy partial compilation for v12.
