### ISSUE TITLE
fix(http): should throw an exception if input to `http.request` is not string or `Request`

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#4245]
I forgot to import `Request` in an example where I instantiate `Request` manually, which meant I was instantiating the global `Request` object instead of `Request` provided by `angular2/http`. When passing this to `Http.prototype.request`, the input didn't match the string or `instanceof Request` check, so the method was returning `undefined. Instead, an exception should be raised.

**Comment by jeffbcross** [comment]
Here's where the change should occur: https://github.com/angular/angular/blob/2acc1ad08be7ee2f71e0173558cb6f7c14739e6f/modules/angular2/src/http/http.ts#L121

**Comment by bkyarger** [comment]
I'd like to tackle this one.

**Comment by jeffbcross** [comment]
It's all you, @bkyarger! LMK if you need help writing/running unit tests.

**Comment by bkyarger** [comment]
@jeffbcross can you show me an example of how you instantiate the global ```Request``` object manually?  I'm not sure how to do that in Typescript for my test.

**Comment by jeffbcross** [comment]
@bkyarger what we could do instead of instantiating a global `Request` (which isn't present in all test environments) is just provide a value to the request function that isn't really a `Request` or string, but tell typescript that it is.

```typescript
var req = <Request>{};
expect(() => http.request(req)).toThrow('some error');
```

**Comment by bkyarger** [comment]
Awesome, I'll do that.  Thanks!

**Comment by bkyarger** [comment]
@jeffbcross I've got the change implemented with a test, but I'm having trouble getting the entire ```npm test``` suite to complete.  When it launches firefox to perf tests FF is crashing (I think when installing the xpi) so the perf tests eventually time out.  I'm on OSX and my FF is up to date.  Any suggestions or workarounds?

**Comment by jeffbcross** [comment]
@bkyarger If unit tests are passing, and if `gulp check-format` passes, I would just go ahead and open a PR and let Travis run the tests. If `gulp check-format` fails, it provides a script you can run to automatically clean up formatting.

**Comment by bkyarger** [comment]
Yep, both of those are passing.  PR on the way.  Thanks!
