### ISSUE TITLE
FormGroup valuechanges doesn't emit when referenced from Observable chain

### ISSUE THREAD

**Issue by sanyi3k** [angular/angular#42464]
# Bug Report

### Affected Package
@angular/forms 11.2.14

### Is this a regression?
As far as I know it is not

### Description
When using an Observable<FormGroup> (forms$) to provide a FormGroup then creating a new Observable from this Observable<FormGroup> (fieldOneValuechanges$), the valueChanges of the new Observable's output does not emit.

If I subscribe to form.valueChanges inside forms$, it is working as it should be.
If I subscribe to form.valueChanges inside fieldOneValuechanges$, it is not working (not logging to the console)
As I debugged the (forms$'s emitted FormGroup) === (fieldOneValuechanges$ received FormGroup)
Also their valueChanges' references are equal.

## Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-sx3fez
problematic rows (2) marked with "[problem] this one never triggered" 

## Your Environment
11.2.14

**Comment by JoostK** [comment]
Heya, this is not a bug in Angular but a bug in your example. You're subscribing to two observable chains that both call `this.createForm()` in the observable pipeline, resulting in two different form instances across the two subscriptions. The UI is showing the form that is bound through `[formGroup]="form$ | async"`, so the form that originates from `{{ bothChanges$ | async }}` is completely independent from the one that is actually shown in the UI.

If you want only a single form, you'll have to do something like `shareReplay(1)` or similar at the end of the `this.form$` observable chain (please research what sharing approach is desirable for your case and how unsubscriptions should affect the shared subject, as there's several options provided by RxJS for this).
