### ISSUE TITLE
HttpClient does not send custom CSRF headerName, but sends default X-XSRF-Token

### ISSUE THREAD

**Issue by mspace** [angular/angular#42465]
# Bug Report

### Description

Sometimes angular doesn't respect custom headerName for CSRF token, but sets default X-XSRF-TOKEN:

![image](https://user-images.githubusercontent.com/1265588/120601442-36be5780-c44a-11eb-95f1-b9e4291cef40.png)

We investigated a little bit, and our assumption is, that this has something todo with http Cache-Control. Once we added for next pages:
- spa/index.html
- all api calls

Response headers:
- cache-control: no-cache,no-store,max-age=0,must-revalidate

Angular (or browser I'm not sure anymore) correctly sends this:

![image](https://user-images.githubusercontent.com/1265588/120601734-99afee80-c44a-11eb-85bb-546889446a5c.png)

We're using next code to use Xsrf module:

```
@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    HttpClientModule,
    HttpClientXsrfModule.withOptions({headerName: '__RequestVerificationToken'}),
    TranslateModule.forRoot(),
    LoggerModule.forRoot(undefined),
  ],
```

On backend side (we're using .NET) we have next code:

```
public class ValidateJsonAntiForgeryTokenAttribute : FilterAttribute, IAuthorizationFilter
    {
        public void OnAuthorization(AuthorizationContext filterContext)
        {
            using (new Tracer("ValidateJsonAntiForgeryTokenAttribute.OnAuthorization"))
            {
                try
                {
                    if (filterContext == null)
                    {
                        throw new ArgumentNullException("filterContext");
                    }

                    HttpContextBase httpContext = filterContext.HttpContext;
                    HttpCookie httpCookie = httpContext.Request.Cookies[AntiForgeryConfig.CookieName];
                    // kendo will send the token as a parameter in grid datasource requests
                    string token = httpContext.Request.Headers["__RequestVerificationToken"] ??
                        httpContext.Request.Params["__RequestVerificationToken"];
                    // validate AntiForgeryToken
                    AntiForgery.Validate(httpCookie != null ? httpCookie.Value : null, token);
                }
                catch (Exception e)
                {
                    TracingService.Instance.Trace(TracingType.Error, "OnAuthorization", $"Exception: {e.Message}", e);
                    throw;
                }
            }
        }
    }
```

This happens always if we deploy new version of angular. 

## Your Environment

**Angular Version:**
<pre><code>Angular CLI: 11.2.11
Node: 14.16.1
OS: win32 x64

Angular: 11.2.12
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.11
@angular-devkit/build-angular   0.1102.11
@angular-devkit/core            11.2.11
@angular-devkit/schematics      11.2.11
@angular/cli                    11.2.11
@schematics/angular             11.2.11
@schematics/update              0.1102.11
rxjs                            6.6.7
typescript                      4.1.5
</code></pre>

**Comment by alxhub** [comment]
Hello @mspace, 

I suspect this is not a framework bug, but rather multiple instances of `HttpClientXsrfModule` in your application (possibly in different lazy-loaded injectors). Overriding the `XSRF_HEADER_NAME` DI token can cause this behavior.

Other than that intuition, I don't think we'll be able to investigate this issue without a minimal reproduction.

**Comment by alxhub** [comment]
I'm going to close this, as no reproduction was provided and we have a pretty good theory about what was going on.

@mspace, if you do end up encountering this bug again and can provide a small reproduction, feel free to open another issue!. Cheers!

**Comment by mspace** [comment]
For now, we removed custom headerName and use it like this:

```
@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    HttpClientModule,
    HttpClientXsrfModule.withOptions(),
    TranslateModule.forRoot(),
    LoggerModule.forRoot(undefined),
  ],
  providers:
```

After we added no-cache, we were unable to repeat the mentioned bug anymore.
