### ISSUE TITLE
NgxGalleryModule

### ISSUE THREAD

**Issue by rohitEzimax** [angular/angular#42466]
I have upgrade angular 8 to angular 12 recently . After upgrading I am getting below error-
 NgxGalleryComponent.push.goJk.NgxGalleryComponent.setBreakpoint (ngx-gallery.umd.js:2398)

It is working fine in v8 but having problem in v12

Thank you!

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
