### ISSUE TITLE
When imported NoopAnimationsModule causes weird behaviour on select dropdowns

### ISSUE THREAD

**Issue by mfrancekovic** [angular/angular#42482]
# Bug Report

### Affected Package

The issue is caused by package @angular/platform-browser/animations

### Description
The problem is that when NoopAnimationsModule is imported (or BrowserAnimationsModule for that matter), either one, the select dropdown starts acting weirdly.
In my example, there is a FormControl that should be used to save a value of a selected option in the dropdown. The options are filled via *ngFor that comes in as an array from a BehaviorSubject.
The problem happens as soon as the value of the async pipe changes, the first option in is visually selected in the option, but it's actually not selected in the formControl. Also, you can't select that first option anymore.
```
<select [formControl]="someCtrl">
  <option *ngFor="let item of values$ | async" [value]="item">{{item}}</option>
</select>
```

But when the NoopAnimationsModule is removed, everything works as expected -> and that is if the value of the array that feeds the option *ngFor changes, nothing gets selected by some random chance.

## Minimal Reproduction

[https://stackblitz.com/edit/angular-ivy-cqzoee](https://stackblitz.com/edit/angular-ivy-cqzoee)

In the example above, try clicking the Values above 2 button -> that button filters the array that feeds the ngFor. You will notice that the first value is 'visually' prefilled in the select -> and that is faulty behavior.
Now try removing the import of NoopAnimationsModule from the app.module.ts -> now the behavior is correct; no matter if the options array changes, nothing will be selected unless the user specifically selects something.

## Your Environment

Locally this is my environment 👇 , on stackblitz from my example it's a bit different, but it still doesn't work.

**Angular Version:**
<pre><code>
Angular CLI: 11.2.14
Node: 14.17.0
OS: win32 ia32

Angular: 11.2.14
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.14
@angular-devkit/build-angular   0.1102.14
@angular-devkit/core            11.2.14
@angular-devkit/schematics      11.2.14
@schematics/angular             11.2.14
@schematics/update              0.1102.14
rxjs                            6.6.7
typescript                      4.1.5
</code></pre>

**Comment by mfrancekovic** [comment]
Update: I've also tried to reproduce this issue on Angular 9 and Angular 8. It works the same on all those versions.
Without the imported NoopAnimationsModule it works as expected.
When NoopAnimationsModule (or BrowserAnimationsModule) is imported the thing starts working funny.

**Comment by AndrewKushnir** [comment]
Thanks for reporting the issue. It looks like a duplicated of #18430. Closing this ticket, please reopen if needed.
