### ISSUE TITLE
Clarify when updateValueAndValidity is necessary.

### ISSUE THREAD

**Issue by vitaly-t** [angular/angular#42505]
From `AbstractControl` class documentation...

![image](https://user-images.githubusercontent.com/5108906/121022558-5632e880-c79a-11eb-8228-e3582e406f1a.png)

Documentation for methods `setValidators` and `setAsyncValidators` says that we **must** call `updateValueAndValidity` after setting validators dynamically.

We have been using those methods without knowing it, because everything worked perfectly without calling `updateValueAndValidity`. It took a special case to find out that `updateValueAndValidity` was required. Shouldn't the documentation at least say **should** instead of **must**, and perhaps with some clarification when it is actually needed?

---

Angular v12.02, in Chrome v91

**Comment by AndrewKushnir** [comment]
Hi @vitaly-t, thanks for the comment. What happens is that the mentioned methods update models, but the change is not propagated to the UI (and the model validity doesn't change either) as a result of a call. If you have an extra logic to trigger change detection for a view, the `updateValueAndValidity` would be called as a part of the `FormControlDirective` or `FormControlNameDirective` directive invocation, thus removing the need to call it explicitly. However I think that in the general case that note makes sense as it highlights the fact that the changes are not propagated to the view immediately and provides a hint on how to do that. I'll close this ticket for now and we'll revisit the docs if we get additional feedback. Thank you.
