### ISSUE TITLE
Parent guard function is calling while a child guard function is pending result

### ISSUE THREAD

**Issue by lopatnov** [angular/angular#42508]
# Bug Report

### Packages
"@angular/common": "~9.1.12",
"@angular/compiler": "~9.1.12",
"@angular/core": "~9.1.12",
...

### Description

I have next routes:

```
/nodes
/items
/items/subitems/:sid
```

Every route is routing module. 

I have guards "canDeactivate" for `items` module and for `/items/subitems/:sid` module. 

When I navigate in browser from `/items/subitems/:sid` to `/nodes`, Angular calls guards "canDeactivate". The guard for `/items/subitems/:sid` returns `Promise<boolean>` result, so it's asynchronous result and it's pending, but after this guard, Angular calls `/items` guard. 

Parent route (for `/items`) doesn't have result from child guard (for `/items/subitems/:sid`), because it's pending, but Angular calls it. It looks like a bug.

Should Angular call guard for `/items` while `/items/subitems/:sid` is pending?

**Comment by criskrzysiu** [comment]
You need to add better explanation or some code, cause I don't understand what guard is called for parent root. Is it canDeactivate as well?

**Comment by lopatnov** [comment]
app-routing.module.ts
```ts
const appRoutes: Routes = [
    {
        path: '',
        component: ...,
        canActivate: ...,
        children: [
            {
                path: '',
                component: PageContainerComponent,
                children: [
                    //...
                    {
                        path: 'area-configuration',
                        loadChildren: () => import('./area-configuration/area-configuration.module').then(m => m.AreaConfigurationModule),
                        canDeactivate: [AreaConfigurationCleanerService], //<-- There I clean all data related to page 'area-configuration'
                    },
                    //...
                ]
            }
			//...
        ]
    }
	//...

];

@NgModule({
  imports: [
      RouterModule.forRoot(
          appRoutes
    ],
  //...
})

export class AppRoutingModule { }
```

area-configuration.module.ts
```ts
import { AreaConfigurationRoutingModule } from './area-configuration-routing.module';

@NgModule({
  //...
  imports: [
    //...
    AreaConfigurationRoutingModule,
    //...
  ]
})
export class AreaConfigurationModule { }
```

area-configuration-routing.module.ts
```ts
const areaConfigurationRouts: Routes = [
  //...
  {
    path: 'org-units/:orgUnitGuid',
    component: OrgDetailsLayoutComponent,    
    children: [
      {
        path: 'details',
        component: OrgDetailsComponent,
        canDeactivate: [AskToSaveService], //<-- 
      }
    ]
  },
  //...
];

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    RouterModule.forChild(areaConfigurationRouts)
  ]
})
export class AreaConfigurationRoutingModule {

}
```

AskToSaveService
```ts
@Injectable()
export class AskToSaveService implements CanDeactivate<IHasUnsavedChanged> {

    constructor(private alertService: AlertService) {
    }

    public async canDeactivate(component: IHasUnsavedChanged,
        currentRoute: ActivatedRouteSnapshot,
        currentState: RouterStateSnapshot,
        nextState?: RouterStateSnapshot): Promise<boolean> {            
        return !component?.hasUnsavedChanges || await this.alertService.confirm(); // Promise<boolean>
    }
}
```

1. I open page `/area-configuration`
2. In this page I open sub-page `/org-units/123`, so I have url `/area-configuration/org-units/123`
3. I leave the page `/area-configuration/org-units/123` and going to `/managers` page
4. AskToSaveService starts canDeactivate guard and creates dialog window "Do you want to save changes?" and return Promise<boolean> result.
5. AreaConfigurationCleanerService starts canDeactivate guard and clean all data related to page `/area-configuration`. And this is mistake, why Angular doesn't wait for Promise<boolean> from `/area-configuration/org-units/123` page, that is sub-page of `/area-configuration`?

**Comment by criskrzysiu** [comment]
> This is working as intended. Please refer to #40577 and specifically [#40577 (comment)](https://github.com/angular/angular/issues/40577#issuecomment-768209703) if you have guards which are order-dependent.

Again Angular team is shuting down issue without reasoning why It is working this way and picking up discussion, even though we now have 20 upvotes rule.

second thing it’s not a duplicate either as in mentioned issue there are multiple async guards in one node of routing and workaround is to use some hacky way with external que service or to separate those guards into separate empty string path nodes of routing and then It works fine. Here we already have multiple nodes so why CanDeactivate is working differently than all other guards and resolvers? And if there is a good reason mayby it’s not mentioned clearly in documentation, Also why not add option to change this behavior to match other guards? 

Please stop closing issues just beacause - this is so annoying.
