### ISSUE TITLE
ERROR in ./webapp/manifest.webapp 2:8

### ISSUE THREAD

**Issue by Prasanth-FrontEnd** [angular/angular#42510]
While the building the Angular 9 version application I'm getting this error by using this command - ng build. But it was working fine using yarn start.

Please get back to me ASAP.

ERROR in ./webapp/manifest.webapp 2:8
Module parse failed: Unexpected token (2:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| {

"name": "sampleproject",
| "short_name": "sampleproject",
| "icons": [
@ ./webapp/app/polyfills.ts 52:0-29

**Comment by gkalpak** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#submit-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
