### ISSUE TITLE
In readme collaborators pointing to incorrect link and also we should add link for angular team  

### ISSUE THREAD

**Issue by iRealNirmal** [angular/angular#42513]
For collaborators link is mentioned [https://team.angular.io/collaborators](https://team.angular.io/collaborators) while it should be `https://angular.io/about?group=Collaborators` and also we should add link for angular team as it's already exists as well and point it to [https://angular.io/about?group=Angular](https://angular.io/about?group=Angular)

# Bug Report

### Affected Package

check page [https://angular.io/README](https://angular.io/README)

**Comment by petebacondarwin** [comment]
Do you want to take this one @iRealNirmal ?

**Comment by iRealNirmal** [comment]
yes @petebacondarwin you can assign it to me. Thanks.
