### ISSUE TITLE
Failed to load module script

### ISSUE THREAD

**Issue by GlauberF** [angular/angular#42548]
# Bug Report

### Description
When trying to load the application, sometimes it doesn't load and returns the error in the console mentioned below in Exception.
This is only possible to see, in production, after the build is done.

## Exception or Error
<pre><code>
main-es2015.f3680287ceabf840d31f.js:1
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

runtime-es2015.bc87756d9695c684fb53.js:1 
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
</code></pre>

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.12
Node: 14.16.1
OS: linux x64

Angular: 11.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1102.11
@angular-devkit/build-angular      0.1102.12
@angular-devkit/build-optimizer    0.1101.4
@angular-devkit/core               11.2.11
@angular-devkit/schematics         11.2.12
@angular/cdk                       11.2.12
@angular/cli                       11.2.12
@angular/flex-layout               11.0.0-beta.33
@angular/material                  11.2.12
@angular/material-moment-adapter   11.2.12
@nguniversal/builders              11.2.1
@nguniversal/express-engine        11.2.1
@schematics/angular                11.2.12
@schematics/update                 0.1102.12
rxjs                               6.6.7
typescript                         4.1.5

</code></pre>

**Anything else relevant?**
Base URL in my index.html `<base href="/">`

**Comment by JoostK** [comment]
This is due to a server misconfiguration where JavaScript bundles don't have the correct `Content-Type` header set. Please refer to https://angular.io/guide/deployment#configuring-correct-mime-type-for-javascript-assets and #30835 where this was discussed at length.
