### ISSUE TITLE
URL filepath Typo on "Localizing your app" doc

### ISSUE THREAD

**Issue by alzaki-cl** [angular/angular#42540]
# Docs or angular.io Bug Report

### Description

 `myapp/fr` is written when `myapp.com/fr` should be written

### What's the affected URL?**
 https://angular.io/guide/i18n#merge

## Screenshot

![Screen Shot 2021-06-09 at 4 52 36 PM](https://user-images.githubusercontent.com/64810019/121443836-1ce9ac80-c943-11eb-8f06-8b09e6a84b8c.png)

## Exception or Error
<pre><code>

</code></pre>

**Comment by gobika21** [comment]
I would like to work on this issue
