### ISSUE TITLE
Angular AOT compiler is not able to evaluate javascript in decorator 

### ISSUE THREAD

**Issue by andre-ellrich-adup** [angular/angular#42550]
### Is this a regression?

I don't think so.

### Description

AOT compiler can't evaluate a "simple" piece of javascript.

in the stackblitz when we look into the console we can see that `ARR1 `and `ARR2` are identical. So no js-error prominent.

## Minimal Reproduction

1. https://stackblitz.com/edit/angular-ivy-eedqth?file=src%2Fapp%2Fapp.module.ts
2. swap

```
@NgModule({
  imports:      [ BrowserModule, FormsModule ],
  declarations: [ AppComponent, ...ARR2 ],
//declarations: [ AppComponent, ...ARR1 ],
  bootstrap:    [ AppComponent ]
```

into

```
@NgModule({
  imports:      [ BrowserModule, FormsModule ],
// declarations: [ AppComponent, ...ARR2 ],
  declarations: [ AppComponent, ...ARR1 ],
  bootstrap:    [ AppComponent ]
# Bug Report
```

## Exception or Error
We get the the error message:
ng-version 11 (stackblitz)
```
Error in src/app/app.module.ts (19:17)
Value at position 1 in the NgModule.declarations of AppModule is not a reference
Value could not be determined statically.
```

in my ng-version 8 project i get:
```
ERROR in Cannot read property 'members' of null
```

**Comment by petebacondarwin** [comment]
This is expected behaviour. There is a limit to the amount of "static" analysis that the compiler is willing to do.

```ts
const ARR1 = Object.keys(OBJ1).map((k: keyof typeof OBJ1) => OBJ1[k]);
```

Expecting the compiler to evaluate a call to `map` on an array is outside of what we (do/will) support.

I'm going to mark this as a feature request, just to give it a fair opportunity to receive support from the community. But expect that it is very unlikely to be implemented.

**Comment by andre-ellrich-adup** [comment]
Do you know any trick that would work with the current implementation of the compiler to solve this problem?

**Comment by JoostK** [comment]
In this particular case you can derive the dynamic code om the static array:

```ts
const ARR2 = [HelloComponent];
const OBJ1 = ARR2.reduce((obj, component) => {
  obj[component.name] = component;
  return obj;
}, {});
```

Then Angular can interact with `ARR2` and your other use-case (outside of the interest of the Angular compiler) can operate using `OBJ1`.

**Comment by andre-ellrich-adup** [comment]
@JoostK 
> and your other use-case (outside of the interest of the Angular compiler)

The "object of types" is still aot-relative because its used in a `forFeature` method. I have updated my stackblitz to reflect something similar to my usecase. (thank you for your tip so far)

https://stackblitz.com/edit/angular-ivy-eedqth?file=src%2Fapp%2Fapp.module.ts

The idea was to have only one data structure to maintain and the other one is "derived" from it.

**Comment by JoostK** [comment]
> The "object of types" is still aot-relative because its used in a forFeature method. I have updated my stackblitz to reflect something similar to my usecase. (thank you for your tip so far)

That's fine actually; Angular doesn't need to know the argument to `forFeature` statically, so it can be a derived object.

**Comment by andre-ellrich-adup** [comment]
@JoostK 
thats super cool I didn't know about the static field "name".

The bad thing, (I just came aware of it again after trying your solution.) Im using that "Object of Types" for typing purposes. It contains all the string-literals (component names) at IDE-time. component.name is of type string and therefore it seams I have to start with the object to have my string literals ('HelloComponent' | 'LolComponent' | ...)

**Comment by JoostK** [comment]
Yeah so as I mentioned, the `.name` property will reflect the class' minified name whereas the object property shorthand you used didn't have that problem. That also means that you can in fact no longer refer to these properties by their name, as their name is unknown (not just the typings are missing, it won't actually work at runtime when minified). So it may well be that it's not a viable solution for you to use it like I suggested.

**Comment by JoostK** [comment]
Closing this as infeasible for now; there will always be limitations to what the AOT compiler is able to statically analyze.
