### ISSUE TITLE
Missing type signatures in api docs

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#4255]
Check out https://angular.io/docs/js/latest/api/core/ViewContainerRef-interface.html

- [ ] `element` (will be renamed to anchorElement soon) is a field and it is missing the type signature
- [ ] `length` is a getter and is missing the type signature
- [ ] `createEmbeddedView` is a method and is missing the return type in the signature

**Comment by petebacondarwin** [comment]
These "should" be fairly simple to fix.

**Comment by mhevery** [comment]
This should be fixed by switching to `--no-implicit-any`. Replacing with https://github.com/angular/angular/issues/4924

**Comment by IgorMinar** [comment]
@mhevery the problem is that we don't have templates for this stuff so #4924 is not going to solve this problem.

reopening
