### ISSUE TITLE
Ugly toggle animation bug related to aio docs's nav-items chevron icons

### ISSUE THREAD

**Issue by dario-piotrowicz** [angular/angular#42552]
# Docs or angular.io Bug Report

### Description

On [angular.io/docs](https://angular.io/docs) the left side-bar nav items produce an ugly effect when they are animated after you click on them

## Minimal Reproduction

Go to [angular.io](https://angular.io/docs) and just toggle some of the toggable nav-items

This works as long as the side-bar is visible and the browser's font-size is medium

## Screenshot

Close up: 
![vlcsnap-2021-06-10-19h28m01s776](https://user-images.githubusercontent.com/61631103/121579388-95c03580-ca23-11eb-88e4-6706d18ddf27.png)

And here you can see the issue with also a one liner solution for it (just a simple overflow hidden):
![Peek 2021-06-10 19-50](https://user-images.githubusercontent.com/61631103/121580979-42e77d80-ca25-11eb-8cc4-da83d092380d.gif)

## Your Environment

Operative System: Ubuntu 20.04.2 LTS
Browser: Chromium Version 91.0.4472.77

## Extra

I understand that this is a very very minor issue but as I showed in the gif above the solution is really just a one liner, so if possible I would love to just fix this just to make the site more polished

There is also one other thing that I noticed and I would like to have a look at, if you increase the browser's font-size the chevron icons vary in size, basically where there is a line-break the icon size decreases, I would also like to look into that if possible:
![Screenshot at 2021-06-10 19-29-44](https://user-images.githubusercontent.com/61631103/121580480-b50b9280-ca24-11eb-9881-2582d8bca89d.png)

**Comment by petebacondarwin** [comment]
These sound like good things to fix, if you would like to go for it, @dario-piotrowicz - thanks!

**Comment by dario-piotrowicz** [comment]
Awesome! thanks a lot @petebacondarwin :)

**Comment by dario-piotrowicz** [comment]
I've found another issue

sometimes the outline of the items can get cropped:
![Screenshot at 2021-06-11 23-05-01](https://user-images.githubusercontent.com/61631103/121753108-887d7680-cb09-11eb-9401-0525a187a615.png)


I've fixed it by just putting 2px left and right margins on the nav container (2px because that is exactly the width of the outline)
This is how it looks:
![Screenshot at 2021-06-11 22-58-44](https://user-images.githubusercontent.com/61631103/121752787-d776dc00-cb08-11eb-9329-56a6710f9bf0.png)

The 2 margins are barely noticeable but fix the outline being cropped

Would you mind if I added this to the PR?

**Comment by petebacondarwin** [comment]
Sounds good, as an extra commit

**Comment by dario-piotrowicz** [comment]
awesome thanks! :)

**Comment by dario-piotrowicz** [comment]
Ok it's all done for the PR :)

But before opening it I am looking at one last issue around the nav:
![nav_last_issue](https://user-images.githubusercontent.com/61631103/121772575-007d8800-cb6e-11eb-9bbc-c70a35d01f1d.gif)

(ps: in the gif it may seem that sometimes it works fine, but it is not, it's always creating that effect in on the site)

As you can see when the scrollbar appears it's placed inside the nav and pushes the content to the left, then the scrollbar moves to the right and the content returns to normal

This creates an ugly effect with the chevron because you see the icon jumping to the left and the right, also it is unpleasant to see the scrollbar appearing and then moving on the right

I'll have a look at this too if it's ok

Anyway I am not sure if I can do anything about that, I am afraid it has to do with the material sidenav

**Comment by dario-piotrowicz** [comment]
The last one I mentioned does not seem related to this codebase, to me it seems a bug with the material sidenav

I've been looking in this codebase but there wasn't anything suggesting the issue lives here, 
I tried to reproduce it with a material stackblitz and this is what I've got:

![Peek 2021-06-12 15-23](https://user-images.githubusercontent.com/61631103/121779299-d7bbb980-cb92-11eb-9b72-3e1b8c588b94.gif)
(Link: https://stackblitz.com/edit/angular-unlegu?file=src%2Fapp%2Fsidenav-responsive-example.ts)

Actually in the stablitz it looks even worse, not sure why...

Anyways, this leads me to believe that this small bug lies with material and not here so I will ignore it in this issue

Please let me know if you don't agree
(and if you think that I should create an issue for this in the material repo)

**Comment by dario-piotrowicz** [comment]
All fixed aside the sidenav "jumping" which anyways depends on the material project
