### ISSUE TITLE
QueryList .first and .last should include undefined in type

### ISSUE THREAD

**Issue by baines** [angular/angular#42563]
# Bug Report

### Affected Package
`@angular/core`

### Is this a regression?
No

### Description
The [QueryList](https://angular.io/api/core/QueryList) `.first` and `.last` properties have the type `T`, but can be `undefined` when the list is empty - the type should be `T | undefined` so that the compiler can more correctly check their usage.

## Minimal Reproduction

The following component compiles without any errors, but it is not valid to access `this.list.first.nativeElement` without checking `.first` for `undefined` beforehand.

```typescript
import { Component, ViewChildren, QueryList, ElementRef, AfterViewInit } from '@angular/core';
@Component({
  selector: 'app-bug',
  template: `
    <ng-container *ngIf="false">
      <div #something></div>
    </ng-container>
  `
})
export class BugComponent implements AfterViewInit {
  @ViewChildren("something") list!: QueryList<ElementRef<HTMLDivElement>>;
  ngAfterViewInit() {
    console.log(".first and .last have type T but can be undefined:", this.list.first.nativeElement);
  }
}
```

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 12.0.4
Node: 14.17.0
Package Manager: npm 6.14.13
OS: linux x64

Angular: 12.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.4
@angular-devkit/build-angular   12.0.4
@angular-devkit/core            12.0.4
@angular-devkit/schematics      12.0.4
@schematics/angular             12.0.4
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Comment by dario-piotrowicz** [comment]
Is just around changing the type signature and checking that it all works and compiles with no problems, if that the case and @baines doesn't want to pick this up I would not mind working on it :)

Also I'd just to point out something, if we do add the `undefined` type there, could that not break existing code? wouldn't that be considered a breaking change? (someone would have they project compiling one moment and not in the next, regardless on the runtime errors they could have received)

**Comment by petebacondarwin** [comment]
I think you are right that this would be a breaking change, since in many case the query would never produce `undefined`, since the thing being queried is actually always there in the template, and so most people would not add checks for `undefined` and the compiler would now error.

I would say that this is a valid fix, though, and should be marked as a breaking change.

**Comment by tapish1822** [comment]
Hi, I am Tapish Pawar, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you!

**Comment by dario-piotrowicz** [comment]
> Hi, I am Tapish Pawar, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you!

Hi Tapish :slightly_smiling_face: , sorry for the confusion but I've already been working on this issue and have a PR open for it :sweat: , I hope you haven't spent much time on it on your side?

**Comment by JeanMeche** [comment]
Signal Queries will land in 17.2, they will provide a type safe alternative to QueryList. 
As this introduces a breaking change and a migration, we prefer to spare of the effort to land this change. 

To work around this issue, we recommanded to use `viewChildren()`/`contentChildren` signal queries.
