### ISSUE TITLE
Navigating to a docs url with a fragment causes the the browser to over-scroll

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#4256]
go to https://angular.io/docs/js/latest/api/core/ViewContainerRef-interface.html#createEmbeddedView

the title of the `createEmbeddedView` is hidden behind the top-level site header.

**Comment by gkalpak** [comment]
`$anchorScroll` had a solution for this in ng1 :)
(Hint: [`yOffset`][1])

[1]: https://docs.angularjs.org/api/ng/service/$anchorScroll#yOffset

**Comment by manekinekko** [comment]
@IgorMinar your link is currently dead.

**Comment by DzmitryShylovich** [comment]
@IgorMinar is this still valid? the link is dead + new angular.io is under dev
