### ISSUE TITLE
Angular Compilation is not FIPS-Compliant

### ISSUE THREAD

**Issue by BurntCoffee543** [angular/angular#42577]
# Bug Report

### Affected Package
The issue is caused by package @angular/compiler-cli, specifically...
@angular/compiler-cli/ngcc/src/packages/configuration.js
@angular/compiler-cli/ngcc/src/packages/entry_point_manifest.js

### Is this a regression?
This appears to have worked before Angular 9 when these hashes were introduced.

### Description
When building an Angular application, an MD5 hash is produced as a part of the compilation process. However, for FIPS-enabled systems, such outdated hashing algorithms are not allowed and breaks the build.

## Minimal Reproduction
Building any Angular application on a FIPS-enabled system. I cannot easily link a StackBlitz as [fips has to be enabled on the Node distribution](https://nodejs.org/dist/latest-v14.x/docs/api/cli.html#cli_enable_fips).

## Exception or Error
<pre><code>error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips
    at new Hash (internal/crypto/hash.js:48:19)
    at Object.createHash (crypto.js:115:10)
    at NgccConfiguration.computeHash (omitted_root_path/node_modules/@angular/compiler-cli/ngcc/src/packages/configuration.js:253:29)
    <... omitted for space ...>
 
An error occurred during the build:
Error: NGCC failed.
    at NgccProcessor.process (omitted_root_path/node_modules/@ngtools/webpack/src/ngcc_processor.js:129:19)
    at omitted_root_path/node_modules/@ngtools/webpack/src/ivy/plugin.js:112:27
    at SyncHook.eval [as call] (eval at create omitted_root_path/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:13:1)
    <... omitted for space ...>
An unhandled exception occurred: NGCC failed.</code></pre>

## Your Environment

**Angular Version:**
<pre><code>11.2.14</code></pre>

**Anything else relevant?**
The issue appears to be caused by these two lines...

- https://github.com/angular/angular/blob/master/packages/compiler-cli/ngcc/src/packages/configuration.ts#L381
- https://github.com/angular/angular/blob/master/packages/compiler-cli/ngcc/src/packages/entry_point_manifest.ts#L162

FIPS will break any procedure that attempts to use outdated hashing algorithms, such as MD5. The algorithm would need to be changed or provide the ability to be customized.

Other relevant articles...

- https://access.redhat.com/solutions/5266791
- https://stackoverflow.com/questions/67427243/cant-build-angular-9-project-on-rhel-8-with-fips-enabled

**Comment by petebacondarwin** [comment]
I guess we could update our hashing here to solve the problem, but this is a shame, since we are not actually using the hashes for any sensitive data, it is just for a simple hash table lookup.  Note that [this Microsoft advice](https://techcommunity.microsoft.com/t5/microsoft-security-baselines/why-we-8217-re-not-recommending-8220-fips-mode-8221-anymore/ba-p/701037) indicates that it is not mandatory or necessarily desirable to turn on FIPS:

>  Note that the requirement to use approved and validated algorithms applies only to the protection of sensitive data. Systems and applications are always free to use weak or non-validated cryptographic implementations for non-security purposes, such as in a hash table for indexing and lookup purposes.

**Comment by petebacondarwin** [comment]
To clarify, I believe the fix is to change the `md5` to `sha256`, right?

**Comment by BurntCoffee543** [comment]
@petebacondarwin Yep definitely get the heartache about it breaking over non-sensitive usage. SHA-256 is currently supported by FIPS, so that should work fine. For future-proofing, projects like webpack offer [the ability to configure the underlying hashing algorithm](https://webpack.js.org/configuration/output/#outputhashfunction) -- just something that may be helpful in case SHA-256 gets deprecated in the unforeseeable future :)
