### ISSUE TITLE
TestRequest.flush() throwing Unsupported responseType: text/csv

### ISSUE THREAD

**Issue by NavidG23** [angular/angular#42578]
# Support Request

## Affected Package
`@angular/common/http/testing --> HttpTestController and TestRequest`

## Is this a regression
Not sure.

## Description
Attempting to mock a GET endpoint returning a CSV using HttpTestController.expectOne() and TestRequest.flush() to mock/resolve request/response. Receiving an error on flush().

### test.service.ts
```
import { ConfigService } from '../config/config.service';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root',
})
export class TestService {
  constructor(
    private httpService: HttpClient,
    private configService: ConfigService
  ) {}


public downloadFileById(id: string) {
    let httpOptions: Object = {
      responseType: 'text/csv'
    };

    const endpoint = `${this.configService.config.api_url} + ':id/download'.replace(':id', id)}`;

    return this.httpService.get(endpoint, httpOptions);
  }
}
```
### test.service.spec.ts
```
import { TestBed, getTestBed } from '@angular/core/testing';
import { TestService } from './test.service';
import { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';
import { ConfigService } from '../config/config.service';

describe('TestService', () => {
  let service: TestService;
  let injector: TestBed;
  let httpMock: HttpTestingController;
  let MockConfigService;

  beforeEach(() => {
   MockConfigService = {
      config: {
         api_url: 'http://localhost:3000/api'
       }
   };
   TestBed.configureTestingModule({
     imports: [
        HttpClientTestingModule
     ],
     providers: [
        { provide: ConfigService, useValue: MockConfigService }
     ]
     });
     injector = getTestBed();
     service = TestBed.inject(TestService);
     httpMock = injector.inject(HttpTestingController);
  });

  afterEach(() => {
    httpMock.verify();
  });

  it('should download file', () => {
      const mockFile = (): File => {
        const blob = new Blob(['a', 'b', 'c', 'd'], { type: 'text/csv' });
        return blob as File;
      };

      service.downloadFileById('1234').subscribe(data => {
        expect(data).toEqual(mockFile);
      });
      const req = httpMock.expectOne(MockConfigService.config.api_url + '/1234/download');

      expect(req.request.url).toBe(MockConfigService.config.api_url + '/1234/download');
      expect(req.request.method).toEqual('GET');

      req.flush(mockFile);
  });
});
```

## Exception or Error
Throwing error --> `Error: Unsupported responseType: text/csv`
Stack trace -->
`Error: Unsupported responseType: text/csv
at _maybeConvertBody (http://localhost:9876/_karma_webpack_/node_modules/@angular/common/__ivy_ngcc__/fesm2015/http/testing.js:373:1)
    at TestRequest.flush (http://localhost:9876/_karma_webpack_/node_modules/@angular/common/__ivy_ngcc__/fesm2015/http/testing.js:211:1)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/app/sahar/services/test.service.spec.ts:239:9)
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:365:1)
    at ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:305:1)
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:364:1)
    at Zone.run (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:124:1)
    at runInTestZone (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:554:1)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:569:1)
    at <Jasmine>`

## Environment
* Angular Version used: 9.0.6
*  Jasmine Version used: 3.5.0

## Expected Behavior
Once the file has been mocked and flushed I expect there to be no error and be able to compare the expected and actual result.

## Possible Solution
The ability to mock and set response content-type through HttpTestingController could be a possible solution. According to documentation, I don't see a way of currently doing that with the response. Just on the mock request.

**Comment by jnizet** [comment]
I don't think it has anything to do with testing, but only with setting the responseType to `text/csv`, instead of choosing one of the accepted values for this property, as described in the documentation: https://angular.io/api/common/http/HttpClient#get. 

If you look at all the overloads, it should be, depending on what you want, set to 'json', 'text', 'blob' or 'arraybuffer'. And the options should be passed inline, to let the TypeScript compiler know which overload of the get method you want to call. So, if your goal is to get back a blob as a result, you would use the overload number 2 of the get method, which is described as returning a blob, and which is chosen if you set the responseType in the options to 'blob':

```
 public downloadFileById(id: string): Observable<Blob> {
    const endpoint = `${this.configService.config.api_url} + ':id/download'.replace(':id', id)}`;
    return this.httpService.get(endpoint, { responseType: 'blob' });
  }
```

**Comment by NavidG23** [comment]
Interesting... the test seems to be functioning as expected now after the change. I'm just wondering why this error wasn't thrown during manual testing. On function execution, this was properly receiving and outputting a CSV formatted string.
