### ISSUE TITLE
Combine api member title and type signature into a single line

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#4258]
Currently our docs for [createHostView](https://angular.io/docs/js/latest/api/core/ViewContainerRef-interface.html#createEmbeddedView) view look like this:

```
createHostView

createHostView(protoViewRef?: ProtoViewRef, atIndex?: number, dynamicallyCreatedBindings?: ResolvedBinding[])
```

The member name is present there twice. It would be great to have just a single title that contains both the name and signature (the signature should be syntax highlighted in a different style than our examples to prevent visual confusion).

While we are at it, we should also add a github style link icon or pi character that shows up to the left of the title when user mouses over the title. Clicking on this icon or character updates the window.location with a deep link to this title. ([example](https://github.com/angular/zone.js#running-within-a-zone) - mouse over the heading)

**Comment by naomiblack** [comment]
@petebacondarwin could you help with this in dgeni?

**Comment by IgorMinar** [comment]
@naomiblack has this been implemented but not deployed yet? the current angular.io doesn't have this issue resolved.

**Comment by petebacondarwin** [comment]
I think that https://github.com/angular/angular.io/issues/339 has not yet been deployed.
Also, that PR does not fix the problem of adding links to the headings.

**Comment by naomiblack** [comment]
it was auto-closed by github when I merged that PR because the description contains "fixes #XXXX" (it was "partially fixes" :)

Reopened. Also, the site has the latest fixes now. Pete is correct -- I merged but had not redeployed yet.
