### ISSUE TITLE
CurrencyPipe is missing parameter documentation

### ISSUE THREAD

**Issue by DanieleScalco** [angular/angular#42590]
# Uncomplete Docs

### Description

I'm taking an Angular course online and while learning pipes I saw in the video the old documentation of 'currency pipe' and I also checked the new one. How is it possible that the old documentation has a full and detailed description of the parameters saying what we can use for each parameter and what it does while the new one said nothing about that?
I dont' understand why the old documentation is more complete.

## Screenshot

![old-documentation](https://user-images.githubusercontent.com/78651340/122365216-c68bf780-cf5a-11eb-8651-cd81e6701eea.jpeg)
Old documentation ↑

![new-documentation](https://user-images.githubusercontent.com/78651340/122365219-c7bd2480-cf5a-11eb-870b-db6e55cbb6b3.jpeg)
New documentation ↑

**Comment by petebacondarwin** [comment]
That is a good question. It might be a bug in our documentation generation. Let me investigate. Thanks for bringing this up.

**Comment by petebacondarwin** [comment]
I believe that this loss of documentation was introduced by 7b2aac97df63717fd2dfbb81903d12221ae29ba1 where we added more overloads to the `transform()` function. The doc-gen looks at the primary function signature (i.e. the last one) but the JSDOC comments are only being attached to the first overload.
