### ISSUE TITLE
the sample project error on site https://angular.cn/start

### ISSUE THREAD

**Issue by Vigor2017** [angular/angular#42604]
I'm a new augular man.
follow by the sample project step  in StackBlitz
at step 3 of "Pass data to a child component", i got a error:

![image](https://user-images.githubusercontent.com/29243224/122637181-cdb03280-d11f-11eb-96af-cf2e401bc963.png)

if i resolve like this:
![image](https://user-images.githubusercontent.com/29243224/122637320-92623380-d120-11eb-845b-8f2ffaef1968.png)
I got another issue.

how to resolve?

**Comment by JoostK** [comment]
This was fixed on angular.io in #42147, please see the needed code in https://github.com/angular/angular/pull/42147/files. The angular.cn documentation is community maintained in https://github.com/angular/angular-cn, please report the issue there.
