### ISSUE TITLE
A single error in the compiler is reported as 3+ errors

### ISSUE THREAD

**Issue by rkirov** [angular/angular#4261]
See #4246 for a sample error, but any compiler error will work. After the error is reported other errors are thrown:

```
...
EXCEPTION: TypeError: Cannot read property 'elementBinders' of undefined
```

This makes is very confusing for users as only the first error is useful.

cc @tbosch (compiler) @alxhub (in case this is bootstrap specific)

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

covered by the new compiler
