### ISSUE TITLE
how to use long in angular?i get json from api ,the long type identity ID last two wiil be zero.

### ISSUE THREAD

**Issue by pengqi1991** [angular/angular#42611]

**Comment by mlc-mlapis** [comment]
@pengqi1991 Angular still means using JS.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
