### ISSUE TITLE
Ivy + Angular Elements = "NullInjectorError: No provider for CompilerFactory"

### ISSUE THREAD

**Issue by murugan1992info** [angular/angular#42612]
[#30262](https://github.com/angular/angular/issues/30262)  Please share if we have any update on this, still we are facing this issue.  @robwormald

**Comment by murugan1992info** [comment]
@robwormald

**Comment by hadrien-toma** [comment]
Is it in this issue that we track the fact that Ivy and Angular Elements are not compatible together? It feels strange to me, is there no other opened issue regarding this feature?

**Comment by alxhub** [comment]
Closing as Elements and Ivy do work together :)
