### ISSUE TITLE
Angular 12 Build Issue - FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by Seshuggina** [angular/angular#42618]
Getting below build error after angular upgrade to 12.

**FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory**

![image](https://user-images.githubusercontent.com/1551596/122907030-5a512f80-d370-11eb-97fc-3a7f2054ab3c.png)

I have increased the --max_old_space_size to 8192 but still getting the same issue while building

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by Seshuggina** [comment]
We have 5 modules in our application. If remove one specific module, application its working fine. I need to find way to replicate the issue in a seperate project to share the code.

**Comment by xjrcode** [comment]
Same thing is happening to me runing Angular 12 in a node v16.3.0 Docker container with npm 7.15.1

This error appears randomly:
```
<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
npm ERR! path /usr/src/app
npm ERR! command failed
npm ERR! signal SIGABRT
npm ERR! command sh -c ng serve --host 0.0.0.0 --disable-host-check

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-25T05_59_12_713Z-debug.log
```

This is the content of the erro log:
```
0 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
1 info using npm@7.15.1
2 info using node@v16.3.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/usr/src/app/.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/root/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 timing npm:load:configload Completed in 10ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing npm:load:cleanupLog Completed in 3ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 1ms
25 timing npm:load Completed in 17ms
26 timing config:load:flatten Completed in 3ms
27 timing command:run-script Completed in 42598997ms
28 verbose stack Error: command failed
28 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
28 verbose stack     at ChildProcess.emit (node:events:394:28)
28 verbose stack     at maybeClose (node:internal/child_process:1067:16)
28 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
29 verbose pkgid frontend@0.0.0
30 verbose cwd /usr/src/app
31 verbose Linux 5.10.25-linuxkit
32 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
33 verbose node v16.3.0
34 verbose npm  v7.15.1
35 error path /usr/src/app
36 error command failed
37 error signal SIGABRT
38 error command sh -c ng serve --host 0.0.0.0 --disable-host-check
39 verbose exit 1
```

**Comment by Tallyb** [comment]
@JoostK 
This is an example repo: https://github.com/tallyb/coreui-free-angular-admin-template
Since the project is relatively small, I run it with lower node memory (1024). 
Adding the build-optimizer option on the CLI makes it crash with the above. 

@Seshuggina - can you please reopen. The details above should be sufficient for identifying the issue.

**Comment by yutao331763646** [comment]
The same for me. After I upgraded from 11 to 12, the memory usage increased from 2.75G to 4.1G
