### ISSUE TITLE
Class/Interface members marked as @private should not be present in the d.ts files

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#4262]
We have cases where class members are "package private" - used internally by Angular, but not part of the external api. Currently the documentation for these members is hidden, but the d.ts file contains them. We should hide them from the d.ts files as well.

We can't use Typescripts visibility markers like `private` for this, because we need Angular core code outside of the current class to be able to access it.

It would be great to solve this properly in Typescript, but in the meantime, we should adjust our .d.ts generation template to look for these members and not emit them during the d.ts generation process.

cc: @alexeagle, @mprobst, @rkirov

**Comment by mprobst** [comment]
Have you considered solving this problem using the normal language internal mechanisms that don't need a special language feature?

E.g. if you have a class that needs a field exposed to other Angular code, you could define a separate interface that's used in the public API, and doesn't declare that property. Export only the interface in the public API, use the class in the private API.

**Comment by IgorMinar** [comment]
We did and in the future we will likely refactor the code, but this change
will require a lot of casting on the public api perimeter which we are not
keen on to do right now.
