### ISSUE TITLE
TSLint is the default linting tool for angular? 

### ISSUE THREAD

**Issue by whatwouldmarvindo** [angular/angular#42639]
# Docs or angular.io Bug Report

### Description
It says that TSLint is the default linting tool for Angular which is not correct since V12, right? 

Look [here](https://angular.io/guide/workspace-config#configuring-builder-targets)

**Comment by petebacondarwin** [comment]
Good spot @whatwouldmarvindo - if anyone would like to fix this, please send in a PR.

**Comment by sonukapoor** [comment]
@whatwouldmarvindo the commit in your repo looks good. Don't forget to create a PR in this repo as well 👍

**Comment by whatwouldmarvindo** [comment]
you're sneaky @sonukapoor! How did you realize that I cloned it and all? This is my first time contributing and trying out the vscode remote repo plugin and I'm not happy with the commit msg and there is no way to change it without with the plugin as far as I know 🤦 

Thank you for your supportive words! I will change the commit msg and create a PR.

**Comment by sonukapoor** [comment]
> This is my first time contributing and trying out the vscode remote repo plugin and I'm not happy with the commit msg and there is no way to change it without with the plugin as far as I know 🤦
> 
> Thank you for your supportive words! I will change the commit msg and create a PR.

No worries. We appreciate all the help we get. 
Let us know if you need any help.

**Comment by JoostK** [comment]
Fixed in #42655 (thanks to @whatwouldmarvindo himself, thanks)
