### ISSUE TITLE
Disabled form form.value shows all controls, as opposed to partially disabled form which shows only enabled controls.

### ISSUE THREAD

**Issue by anisabboud** [angular/angular#42630]
# Bug Report

### Affected Package
@angular/forms - Angular 12

## Minimal Reproduction
1. Create a reactive form group with 2+ controls.
2. Add `<pre>{{form.value | json}}</pre>` to the html.
3. Disable one control => form.value shows only the other enabled control. (Correct behavior. It hides the disabled controls.)
4. Disable all controls (e.g., using form.disable()) => form.value shows both controls, instead of being empty. (Incorrect behavior.)

**Comment by anisabboud** [comment]
StackBlitz: https://stackblitz.com/edit/angular-zrstua-v1vsv4?file=src%2Fapp%2Finput-errors-example.ts

```typescript
import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';

@Component({
  selector: 'input-errors-example',
  templateUrl: 'input-errors-example.html',
  styleUrls: ['input-errors-example.css'],
})
export class InputErrorsExample implements OnInit {
  form: FormGroup;

  constructor(private formBuilder: FormBuilder) {}
  
  ngOnInit() {
    this.form = this.formBuilder.group({
      field1: '',
      field2: '',
    });

    console.log(this.form.value);  // Prints {field1: "", field2: ""} ✅

    this.form.get('field1')?.disable();
    console.log(this.form.value);  // Prints {field2: ""} ✅

    this.form.get('field2')?.disable();
    console.log(this.form.value);  // Prints {field1: "", field2: ""} ❌ instead of {}.
  }
}
```

**Comment by indraraj26** [comment]
I had an similar issue https://github.com/angular/angular/issues/36894#issuecomment-650570763
requested for feature that will have additional optional param which will be emitValue true | false
https://github.com/angular/angular/issues/36894

When you will set emitValue : false that it will not emit the disable control in form.value
When you will set emitValue: true even if it is disabled it will be shown to you on form.value

**Comment by petebacondarwin** [comment]
This is working as expected. When a form is disabled its value still includes all its children's values in its `value` property.
When all a form's children are disabled, then the form is implicitly disabled itself. So again will include all the values of the disabled children.

You can check the`form.disabled` property before reading the `form.value` property if you want a different value for the form when it is disabled.

See https://stackblitz.com/edit/angular-zrstua-lcsktg?file=src%2Fapp%2Finput-errors-example.ts

**Comment by indraraj26** [comment]
> You can check the`form.disabled` property before reading the `form.value` property if you want a different value for the form when it is disabled.

Suppose there are childrens of children formGroup and one of formGroup of control is disabled then you will have to check till end, It would be great if we can have optional param like emitValue with that we will always have control value even if it is disabled.  Hence when you will try to access it, It will not throw the error.

**Comment by anisabboud** [comment]
Thank you for the quick response and explanation, @petebacondarwin. 

I don't understand why this is the intended behavior, but if you say it's by design, this issue can be closed.

**Comment by destus90** [comment]
This is described in the docs

https://angular.io/api/forms/AbstractControl#value

> For a disabled FormGroup, the values of all controls as an object with a key-value pair for each member of the group.

**Comment by petebacondarwin** [comment]
Closing as working as expected.
