### ISSUE TITLE
HttpParams instantiation using fromObject option with number or boolean parameters does not convert them to string

### ISSUE THREAD

**Issue by aanaya-deltacom** [angular/angular#42641]
# Bug Report

### Affected Package

The issue is caused by package @angular/common/http

### Is this a regression?

No

### Description

From Angular version 12, the `HttpParamsOptions` allows `number` and `boolean` types in `fromObject`, introduced with commit #40663

When a new `HttpParams` object is created using that option, then the parameters are not converted to string, so when using the `get` and `getAll` methods the value does not match the expected `string | null` type.

This causes type errors and tests failing.

Check this comment for more info about the fix: https://github.com/angular/angular/issues/42637#issuecomment-867520993

## Minimal Reproduction

```
const params = new HttpParams({ fromObject: { numericParam: 5 } });
console.log(
  typeof params.get('numericParam') === 'number', // true
  params.get('numericParam') === '5', // false
  // params.get('numericParam') === 5, // does not compile
);
```

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 12.0.3
Node: 14.15.4
Package Manager: npm 6.14.10
OS: linux x64

Angular: 12.0.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.3
@angular-devkit/build-angular   12.0.3
@angular-devkit/core            12.0.3
@angular-devkit/schematics      12.0.3
@angular/cli                    12.0.3
@angular/flex-layout            12.0.0-beta.34
@schematics/angular             12.0.3
rxjs                            6.6.7
typescript                      4.2.4</code></pre>

**Comment by petebacondarwin** [comment]
@cexbrayat - do you want to take this one?

**Comment by cexbrayat** [comment]
Sure, I'll take a look
