### ISSUE TITLE
Content-type problem when sending json AND file in same FormData

### ISSUE THREAD

**Issue by Yberion** [angular/angular#42653]
# Bug Report

Hello.

### Affected Package

The issue is caused by package `@angular/common/http` (`HttpClient`)

### Is this a regression?

I have no idea. I never did anything similare before I post this issue there.

### Description

I am sorry, I won't be able to provide a **Minimal Reproduction** since it require a back-end as well (I use Spring Boot here) so the description will contain all the detail you'll need.

#### -- Short: 

What I want:
I'm trying to send a FormData that contains a JSON and a File (in the same FormData).

What I expect:
The function on the back-end that is responsible of the API (a DTO, a Multipartfile) should be able to get the JSON + the file.

What I have:
The DTO contains only null values, I correctly get the file.

Additional information: Why I'm posting here is because, using Postman, all works as expected.

#### -- Long:

Here is an example of what I'm doing.

Front-End service function:
```typescript
createToto(totoDTO: TotoDTO, file: File): Observable<void> {
    const formData = new FormData();

    formData.append('toto', JSON.stringify({ totoDTO }));
    formData.append('file', file, file.name);

    return this.http.post<void>(`${TotoService.URL}`, formData);
}
```
Back-End controller function:
```java
@PostMapping(consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
public void createToto(@RequestPart("toto") TotoDTO totoDTO, @RequestPart("file") MultipartFile multipartFile, Principal loggedUser) throws IOException {
    System.out.println(totoDTO);
    System.out.println(multipartFile.getOriginalFilename());
    //totoService.createToto(totoDTO, multipartFile, loggedUser.getName());
}
```
So when I send a request from the Front-End to the Back-End, the Back-End tell me that `Content type 'application/octet-stream' not supported`:
```
2021-06-24 16:04:17.812  WARN 18820 --- [nio-8080-exec-5] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotSupportedException: Content type 'application/octet-stream' not supported]
```
The request header looks like this (it's a content-type multipart):
```
------WebKitFormBoundary4WervCkSHzbAcd2L
Content-Disposition: form-data; name="toto"

{"toto":{"id":6,"unChamp":"coucou"}}
------WebKitFormBoundary4WervCkSHzbAcd2L
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain


------WebKitFormBoundary4WervCkSHzbAcd2L--
```
I did some research and then found out that for the DTO it should be stored in a Blob like this:
```typescript
...
formData.append(
    'toto',
    new Blob([JSON.stringify({ totoDTO })], {
        type: 'application/json'
    })
);
...
```
The request header looks like this, here the DTO have `Content-Type: application/json` which should be fine:
```
------WebKitFormBoundaryocSMA44WAWzYVkwC
Content-Disposition: form-data; name="toto"; filename="blob"
Content-Type: application/json

{"toto":{"id":6,"unChamp":"coucou"}}
------WebKitFormBoundaryocSMA44WAWzYVkwC
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain


------WebKitFormBoundaryocSMA44WAWzYVkwC--
```
Fine, the Back-End doesn't cry anymore but the json received on the Back-End seems to be empty or isn't in the good form:
```java
TotoDTO(id=null, unChamp=null)
test.txt
```
So, why am I posting an issue here?

Because if I'm using Postman, all works as intended:
![Image collée à 2021-6-24 16-43](https://user-images.githubusercontent.com/4186385/123330727-ac47b000-d53e-11eb-8e78-8100e36ebea5.png)

I get the proper DTO (nothing null) and the file.

I suspect something being wrong on the Angular side, either it's my fault on not properly setting something or it's a "bug".

Maybe I'm not thinking properly and shouldn't send a file with a json (DTO) ?
I don't want to use 2 differents request for that. Maybe It's better to send a base64 file?

## Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 11.2.11
Node: 14.16.1
OS: win32 x64

Angular: 11.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.11
@angular-devkit/build-angular   0.1102.11
@angular-devkit/core            11.2.11
@angular-devkit/schematics      11.2.11
@angular/cdk                    11.2.11
@angular/cli                    11.2.11
@angular/material               11.2.11
@schematics/angular             11.2.11
@schematics/update              0.1102.11
rxjs                            6.6.7
typescript                      4.1.5

</code></pre>

**Comment by JoostK** [comment]
You appear to be hitting specific Spring Boot behavior where a request part with a `filename` in its `Content-Disposition` header is interpreted as a file:

https://github.com/spring-projects/spring-framework/blob/ddbb7c1b5b003018ee4ebd483ca4a22dd60a53c7/spring-web/src/main/java/org/springframework/web/multipart/support/StandardMultipartHttpServletRequest.java#L98-L108

When making the request from Postman it's likely not including the `filename="blob"` data, which avoids Spring from interpreting it as a file.

I'm afraid there isn't anything we can do from the Angular side of things, as handling of `FormData` is entirely up to the browser.

**Comment by Yberion** [comment]
Hello, thank you for the fast answer!

If you have a minute, what's the best practice to send a file along with json data using Angular using a single request so we can validate the json and then upload the file ?

I mean, isn't it quite common to send a file in the same request as other data (json DTO)?

Should I send the file in base 64 and then avoid using FormData?

FormData are only meant to be used for file then?

Thank you for your time.

**Comment by JoostK** [comment]
> I mean, isn't it quite common to send a file in the same request as other data (json DTO)?

It sounds like a fine approach to me.

You should probably verify whether the `filename="blob"` data is indeed causing your issue, by sending the raw request using something like curl, or possibly even Postman would be capable of creating a raw HTTP message. You can get access to the request using Chrome's Web Inspector, in the Network tab; right click on the request and then:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/123679/123337358-5e837580-d547-11eb-9fd9-b2e34a76a90d.png">

> FormData are only meant to be used for file then?

Not necessarily. I can't tell you where that `filename="blob"` is coming from though, so I'm afraid I won't be of much more help here.

**Comment by Yberion** [comment]
Hello,

It was my fault it seems.

```typescript
formData.append(
    'toto',
    new Blob([JSON.stringify({ totoDTO })], {
        type: 'application/json'
    })
);
```
Provide a JSON with this form:
```json
{"toto":{"id":6,"unChamp":"coucou"}}
```
Removing the `{ }` around `totoDTO`:
```typescript
formData.append(
    'toto',
    new Blob([JSON.stringify( totoDTO )], {
        type: 'application/json'
    })
);
```
Provide a JSON with this form:
```json
{"id":6,"unChamp":"coucou"}
```
And this is the last form that my Back-End is waiting, I wasn't fully understanding everything, now it's fine and it have nothing to do with `filename` on Spring Boot it seems.
