### ISSUE TITLE
Documentation should not be considered a feature request

### ISSUE THREAD

**Issue by rooby** [angular/angular#42657]
I’ve seen a lot of requests for additions or fixes to documentation being tagged as feature requests.
I’m not sure if this is because they were initially lodged under the wrong category or if someone is tagging them as such after they are opened (seems like they’re manually added).

Now that there is the policy of feature requests being closed without enough “votes” this means that a lot of documentation issues might be closed as a result.

This is bad because quality documentation is very important documentation should be considered a requirement, not an optional additional feature.
I believe that missing or broken documentation should be considered a bit more than a feature.

Please consider stopping the tagging of documentation as feature requests and exclude them from the feature voting system.

**Comment by aikidave** [comment]
Hi @rooby!

You're correct, not all documentation issues should necessarily be feature requests. I'll look into whether all doc issues are getting tagged as such; if they are, I'll work on fixing it.

That said, some documentation issues do fall into the feature request category. For example, we often get issues like:

"Need better docs on <feature>"

"Add tutorial on <something interesting>"

I'd love to tackle all these, but the reality is that they're more feature requests than actual bugs. A doc bug, in my opinion, is something like:

"Code example in <topic> does not work"

"Topic says X, should be Y"

And you're right--those aren't feature requests and should be tagged accordingly.

Thanks for voicing your opinion on this! You made some excellent points!

**Comment by bob-watson** [comment]
Thanks, again, for your suggestion. I agree with your sentiments and also @aikithoughts' earlier comment.
As such, there's not much more to do on this issue beyond keeping an eye on issues as they come in and make sure they are categorized appropriately, so I'm going to close this issue.
