### ISSUE TITLE
d.ts file contains several symbols marked as @private

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#4265]
We have some classes, functions, etc marked with `@private` doc annotation that are part of the d.ts file.

This looks like an reexport error that should be fixed. Once fixed, we can throw an error if we see this during the d.ts generation.

@mhevery please review the d.ts file and determine if these are being reexported by mistake.

**Comment by IgorMinar** [comment]
Based on the discussion with @vsavkin it seems that these should be private. @mhevery?

**Comment by mhevery** [comment]
SGTM. But then they should also be prefixed by `_` so that they are private in Dart as well.

**Comment by mhevery** [comment]
Closing as we no longer generate our own `.d.ts` file.
