### ISSUE TITLE
Negative sign not a valid value for input type number FormControl

### ISSUE THREAD

**Issue by AG-58** [angular/angular#42668]
# Bug Report

### Affected Package

The issue is caused by package `@angular/forms`

### Is this a regression?

 No

### Description
 Negative sign `-` is not allowed to be set using FormControl `patchValue` method on input type `number`.
It is a valid value as per https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number and using something like the following should work:
```
this.inputFormControl.patchValue('-');
```

## Minimal Reproduction

Angular v11.0.8: https://stackblitz.com/edit/angular-btkzby?file=src/app/app.component.ts
Angular v12.1.0: https://stackblitz.com/edit/angular-ivy-orrz1w?file=src/app/app.component.ts

Button 'Set negative sign' does not work
Button 'Set negative value' works

## Your Environment

**Angular Version:**
<pre>
<code>11.0.8</code>
<code>12.1.0</code>
</pre>

**Comment by crisbeto** [comment]
I think that this is a browser limitation, because all the Forms module does is set `someInput.value = '-';` which isn't a valid number. The browser allows you to type it in manually, because otherwise there would be no way of typing in negative numbers.

**Comment by AG-58** [comment]
I suppose there is no workaround for this then, apart from using a type=text input? Can force it to behave like a number but it won't be as nice as the native one.

**Comment by shehan96** [comment]
I think that this is a browser limitation.

**Comment by sonukapoor** [comment]
> I suppose there is no workaround for this then, apart from using a type=text input? Can force it to behave like a number but it won't be as nice as the native one.

Correct, you could use a regular expression along with the `type=input` to achieve your validation.

**Comment by petebacondarwin** [comment]
Closing as this is the behaviour of the browser as can be seen in this example with no Angular: https://stackblitz.com/edit/js-t7aeb1?file=index.js
