### ISSUE TITLE
What is Angular?: Unclear interpolation example in Templates section

### ISSUE THREAD

**Issue by Chealer** [angular/angular#42665]
# Docs or angular.io Bug Report

### Description

[The _Templates_ section of the _What is Angular?_ page](https://angular.io/guide/what-is-angular#templates) contains:

> The following is an example of interpolation and bindings within an Angular template:
> 
> hello-world-bindings.component.ts
> hello-world-bindings.component.html
> ```
> <button (click)="sayMessage()" [disabled]="canClick">Trigger alert message</button>
> <p [id]="sayHelloId" [style.color]="fontColor">You can set my color in the component!</p>
> ```

It would help to clarify where interpolation occurs in that example.

### What's the affected URL?**
https://angular.io/guide/what-is-angular

### Reproduction Steps**
This does not report a behavioral bug.

### Expected vs Actual Behavior**
This does not report a behavioral bug.

## Screenshot
![image](https://user-images.githubusercontent.com/486141/123482942-021a6780-d5d4-11eb-8807-e4e53fe2da06.png)

### Browser info
 No

**Comment by petebacondarwin** [comment]
I think the fix here is actually to remove the word interpolations from the sentence, since the example has no interpolations:

> The following is an example of bindings within an Angular template:

Earlier on in the document interpolations are discussed and illustrated.

**Comment by codebriefcase** [comment]
@petebacondarwin  Interpolation, Bindings, and Event Listeners are also discussed previous to this example in the docs.
I think the idea here is to provide a conclusive example of all these three ideas. So, the sentence should be something like this -

> The following is an example of Interpolation, Property Binding, and Event Binding within an Angular template:

Raising a PR for the same.

Your thoughts?

**Comment by petebacondarwin** [comment]
But the example does not contain interpolations AFAICT.

**Comment by iRealNirmal** [comment]
@petebacondarwin you can assign this to me

**Comment by petebacondarwin** [comment]
@iRealNirmal - it was not clear whether @codebriefcase wanted to take this already...

> Raising a PR for the same.

I am happy for either of you to take it. Please negotiate between yourselves 😄 

But make sure that the final wording and the example match each other.

**Comment by iRealNirmal** [comment]
@petebacondarwin please assign it to @codebriefcase as he already raised PR. Earlier I was also not sure whether he wants to take it.

**Comment by petebacondarwin** [comment]
@codebriefcase  can you make sure that the commit in your PR includes

```
Fixes #42665
```

**Comment by behroozbc** [comment]
hi 
what is state of this issue ??
