### ISSUE TITLE
Duplicate identifier

### ISSUE THREAD

**Issue by mu5er** [angular/angular#42662]
# Bug Report

### Affected Package
ngcc

### Is this a regression?
No

### Description
I'm trying to update libraries to Angular 12 from Angular 10 using Ivy partial compilation mode. One of libraries (library A) depends on the other (library B), so when I build it, ngcc adds duplicate identifiers to the library B's components and services sources, and build fails.

## Exception or Error
<pre><code>
node_modules/@repo/library/src/template/file.uploader/file.uploader.component.d.ts:36:12 - error TS2300: Duplicate identifier 'ɵfac'.

36     static ɵfac: ɵngcc0.ɵɵFactoryDeclaration<FileUploaderComponent, never>;

</code></pre>

## Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 12.1.0
Node: 12.16.1
Package Manager: npm 6.13.1
OS: win32 x64

Angular: 12.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.0
@angular-devkit/build-angular   12.1.0
@angular-devkit/core            12.1.0
@angular-devkit/schematics      12.1.0
@schematics/angular             12.1.0
ng-packagr                      12.1.0
rxjs                            6.5.4
typescript                      4.3.4

</code></pre>

**Comment by JoostK** [comment]
Hi @mu5er,

ngcc shouldn't be touching partially compiled libraries and it's not clear what's happening in your case. Please provide a reproduction, ideally a Github repo.

**Comment by mu5er** [comment]
@JoostK,

It's a commercial project, so now I'm how to share code without any problems.

**Comment by alxhub** [comment]
Is it possible that the partially compiled library is being copied into `node_modules` overtop of an older, View Engine built library? `ngcc` should only target a library if it sees `metadata.json` files next to the `.js` files in `node_modules`.

**Comment by mu5er** [comment]
@JoostK, @alxhub

Thanks for such a rapid feedback. Didn't expect that. 

I believe, I just fucked up with publish the first time.
