### ISSUE TITLE
Poor <ng-template> aio docs

### ISSUE THREAD

**Issue by dario-piotrowicz** [angular/angular#42678]
# Docs or angular.io Bug Report

### Description

I stumbled across the aio docs for the `ng-template` element they are quite underwhelming, I understand that it is not the most important element in Angular but it does have some relevance and I'd imagine there would be more to say about it

For example:
 - how it is used in structural directives
 - relation with `TemplateRef` and `ngTemplateOutlet`
 - its context (more on this below)
 - how it can be assigned a template variable so that it can be used in other parts of the template or by `viewChild`

(Please let me know if there are other aspects that could be mentioned)

Also personally I find the current wording a bit confusing:
> that doesn't render anything by default

this to me sort of sounds like you could get the `ng-template` to render something
(maybe _"that doesn't get rendered by default"_ would be better?)

### What's the affected URL?**
https://angular.io/api/core/ng-template

## Screenshot
![Screenshot at 2021-06-27 19-37-00](https://user-images.githubusercontent.com/61631103/123555676-1189e400-d77f-11eb-9032-51d4bbfa70f0.png)

### Extra

The `templateRef`'s `createEmbeddedView` docs ([link](https://angular.io/api/core/TemplateRef#createembeddedview)) include the following:
 > The data-binding context of the embedded view, as declared in the [\<ng-template>](https://angular.io/api/core/ng-template) usage.

Suggesting that the `ng-template` docs are supposed to contain something about the template's context (but they don't)

**Comment by dario-piotrowicz** [comment]
I just wanted to mention that if this issue gets approved and I would be allowed to, I would love to possible be assigned to it and come up with the content for the `ng-template` docs :slightly_smiling_face:

**Comment by petebacondarwin** [comment]
Go for it @dario-piotrowicz

**Comment by dario-piotrowicz** [comment]
Awesome! I'll do my best! Thanks a lot! :smiley:

**Comment by dario-piotrowicz** [comment]
Hi @petebacondarwin :slightly_smiling_face:

I jotted down something for the docs, I would love it if you could have a look and tell me if you can see this sort of useful :slightly_smiling_face: 
 
I've created a draft PR: https://github.com/angular/angular/pull/42704

I've written it this was as I saw that headings are banned for the ng-template docs, if you can see the rendered version it does not look too bad :slightly_smiling_face: (by the way, I just wanted to mention that I noticed that I could still use headings using the [alternate syntax](https://www.markdownguide.org/basic-syntax/#alternate-syntax) :stuck_out_tongue_winking_eye: )

(by the way, I also noticed that the other 2 special elements have very little in their documentation, if things go well here I would love to add some info there too :slightly_smiling_face: )

**Comment by petebacondarwin** [comment]
You are correct that we disallow all headings in "description" and "shortDescription" blocks for API docs.
You are

**Comment by dario-piotrowicz** [comment]
@petebacondarwin thanks a lot for the awesome review and the `aio: preview` tag :slightly_smiling_face: 

I honestly had no idea about `@usageNodes` so I stayed very concise and used the list to divide things instead of using headings, so yeah, many of your comments derive from that and I will amend as you suggested

For the same reason I did not put any example in

I will see to amend all following your comments

Thanks a lot again for all your help :slightly_smiling_face:

**Comment by petebacondarwin** [comment]
Great - I look forward to the new version!

**Comment by AndrewKushnir** [comment]
Closing this ticket since PR #42704 (with the necessary updates) was merged.
