### ISSUE TITLE
Linker Babel Plugin needs to explicitly run on partially compiled Ivy libraries

### ISSUE THREAD

**Issue by robertvanhoesel** [angular/angular#42677]
# Bug Report
`@angular/compiler-cli/linker/babel` does not detect/compile partial Ivy libraries when compiling application code. This results in a runtime error `Uncaught Error: Angular JIT compilation failed: '@angular/compiler' not loaded!`

When running the loader explicitly on partial ivy libraries they are compiled correctly.

### Affected Package
`@angular/compiler-cli/linker/babel`

### Is this a regression?

No, Angular 12 is the first version that includes the loader.

### Description
In order to consume modern libraries that published partial Ivy code, the Angular Linker is used to compile it to full Ivy. To use the linker outside of the CLI you would use the babel-loader `@angular/compiler-cli/linker/babel`. 

It is ill advised to run babel over the entirety of `node_modules/` so you include the loader in the babel config running only on application code. In this case the loader is able to detect from imports what libraries need to be compiled. This works fine for legacy libraries published in the View Engine format (with a metadata entry in package.json), but it is ignoring partial Ivy libraries.

## Minimal Reproduction
Later this week I would be able to create a minimal reproduction if deemed necessary – this is however quite involved. 

## Exception or Error
Since the linker is able to detect legacy libraries used in application code, it is expected that it would also pick up partial Ivy libraries, instead an explicit webpack rule needs to be configured to run over modern libs.

Because the library stays uncompiled, it results in runtime errors like `Uncaught Error: Angular JIT compilation failed: '@angular/compiler' not loaded!`. 

## Your Environment

**Angular Version:**
`12.1.0`

**Anything else relevant?**
Custom build using `@ngtools/webpack` and `@angular-devkit/build-optimizer/webpack-loader`
`ngcc` is also ignoring the library (as is expected?).

## Workaround
Posting here for others that might encounter the issue. Make sure you set up `webpack.config.json` to run the babel loader explicitly over the libraries that need to be compiled to full Ivy.
```js
/* Explicit rule to rune the linker over partial libraries */
rules: [{
    test: /.*\.(js|ts)$/,
    include: /node_modules\/(ngx\-tiptap|ngx\-another\-lib)/,
    use: [
        {
            loader: 'babel-loader',
            options: {
                configFile: false,
                plugins: ['@angular/compiler-cli/linker/babel'],
            },
        },
    ],
},
/* your regular build, excluding packages */
{
    test: /.*\.(js|ts)$/,
    exclude: /node_modules/,
    use: [
        { loader: 'babel-loader' },
        { loader: '@ngtools/webpack' },
        { loader: '@angular-devkit/build-optimizer/webpack-loader' },
    ],
},
// ... other rules
]
```

**Comment by JoostK** [comment]
This is working as intended. The linker needs to be incorporated into a custom build pipeline manually.

> It is ill advised to run babel over the entirety of node_modules/ so you include the loader in the babel config running only on application code

A Webpack loader is only run when a module is requested to be included in the final bundle, so the linker will not run on _everything_ in `node_modules`. Still, if it's included in a Webpack rule without conditions then it will indeed also run Babel on modules that don't contain partially compiled code.

> Since the linker is able to detect legacy libraries used in application code [...]

I don't quite understand what is meant here. The linker is not involved in ngcc-processed libraries, if that's what you mean by "legacy libraries". The linker also doesn't detect anything, it gets invoked as long as it's configured to run in a Babel loader.

From sibiraj-s/ngx-tiptap#10 I notice your following comment:

> Now the linker is unable to detect the lib as needing to be compiled to Ivy and is ignored. Unless we specifically run the babel-loader over the libraries we want compiled, it stays like it is and outputs runtime errors, like the once shared above.

That is indeed exactly how it's designed. We should probably improve the reported error message when the JIT compiler is not present.

**Comment by robertvanhoesel** [comment]
Thanks for your reply @JoostK – and thanks for providing this plugin, it allows us to migrate a chunky legacy codebase to 12 while still working on adopting the CLI.

> I don't quite understand what is meant here. [...] The linker also doesn't detect anything, it gets invoked as long as it's configured to run in a Babel loader. 

I made a wrong assumption and thought the below log output was the result the of Babel Plugin (since I removed the post install script calling `ngcc` and added the loader in the same move). I guess the below is triggered by the Angular Webpack Plugin?

```
Compiling @angular/core : main as umd
Compiling @angular/common : main as umd
Compiling @angular/platform-browser : main as umd
Compiling @uirouter/core : main as commonjs
```

I can work with explicitly running the loader on libs now I know this is by design. I would suggest adding to the documentation that it needs to explicitly run on the dependencies source. Simply adding the plugin to `babel.config.js`, which was my instinctive action, might not be enough if you use a fairly vanilla webpack+babel setup.

Any thoughts on how we could trigger the plugin dynamically on partially compiled libraries only? How does the CLI conceptually optimize when the linker gets invoked?

**Comment by JoostK** [comment]
> I guess the below is triggered by the Angular Webpack Plugin?

I believe that's the case, indeed. The invocation of ngcc is incorporated into `@ngtools/webpack`, but the linker is not. This is partially because ngcc must run on View Engine libraries for the app to even compile, whereas partial compilation is fully independent from the app's compilation.

So the responsibility of `@ngtools/webpack` is to compile TypeScript sources using the Angular compiler. Any other JS modules that need to be bundled are not handled by `@ngtools/webpack`.

> Any thoughts on how we could trigger the plugin dynamically on partially compiled libraries only? How does the CLI conceptually optimize when the linker gets invoked?

The CLI uses the `needsLinking` function that is exposed from `@angular/compiler-cli/linker` and configures the Babel plugin dynamically based on the result. Here's the [relevant loader definition](https://github.com/angular/angular-cli/blob/ada64401d0ad723e829aab2614870de9bf130072/packages/angular_devkit/build_angular/src/babel/webpack-loader.ts) if you're interested (I believe this isn't meant to be just imported into any custom Webpack config though).

**Comment by robertvanhoesel** [comment]
Thanks, interesting! As far as I see it is actually using an AST-like structure to understand if there are still uncompiled decorators in a library and then marking it for linking. I don't think we can or should preprocess that in an similar way without doing a lot of similar work twice.
