### ISSUE TITLE
Async Validators should not be fired on disabled control

### ISSUE THREAD

**Issue by daniel-seitz** [angular/angular#42684]
# Bug Report

### Affected Package
Reactive Forms

### Is this a regression?
Not sure

### Description
The Async Validation of a FormControl fires when the control is disabled. My understanding, i.e. from https://github.com/angular/angular/issues/11287 is that this behavior should not be the case.

It depends on the initialization as you can see in the stackblitz which is a simple example where in our actual case we have abstractions and nesting. passing the disabled state to where the control is actually created would be cumbersome. 

## Minimal Reproduction
https://stackblitz.com/edit/components-issue-sjrujv?file=src/app/example-component.html

**Angular Version:**
Angular v11.2
Angular v12.0.1

**Anything else relevant?**
Also when SyncValidators are present at the same time, the asyncValidators are never executed. Not sure if this works as designed.

Thank you for looking into this.

**Comment by iRealNirmal** [comment]
On doing further analysis what I found it's combination of not passing any validator and marking it disabled is creating issue.

I  created more simpler version of stackblitz to confirm it.
[https://stackblitz.com/edit/components-issue-dlnzwm?file=src%2Fapp%2Fexample-component.ts](https://stackblitz.com/edit/components-issue-dlnzwm?file=src%2Fapp%2Fexample-component.ts)

From my perspective issue seems legit but I will still like any one from angular team to confirm it.

**Comment by daniel-seitz** [comment]
Thank you @iRealNirmal but your example now is a bit misleading:

- the template now ie. says Bug, null: not ok, should be null
- it doesnt show the working path anymore where you pass the disabled state immediately during initialization.
- using a validator in addition to an async one will lead to the async one not being fired when the sync one fails. Not 100% sure but I think I read somewhere that this was by design, just wanted to clarify. However thinking about this, it would make sense to remember the sync ones, fire the async one and then merge the results. i.e. when you have a field that checks whether an required email already exists. Question is whether to show one or more errors at the same time...

Please still use my example to evaluate if there is a problem (and let me know if I should simplify it)

Thank you, 
Daniel

**Comment by iRealNirmal** [comment]
thanks @daniel-seitz 
I updated point 1 in template for other points I tried to replicate with other approach including minimal code to validate issue, but if you think that's not correct then please ignore.

**Comment by dylhunn** [comment]
Even if this is WAI, it should be consistent between sync and async validators

**Comment by JeanMeche** [comment]
Looks like everything works as expected, the validators (sync+async)  are fired before the control is being disabled. 

#54790 is a feature request to allow a control to be in a disable state at initialization (which would prevent the execution of validators).
