### ISSUE TITLE
HttpParams is now turning null/undefined parameters into strings

### ISSUE THREAD

**Issue by everix1992** [angular/angular#42689]
# Bug Report

### Affected Package

The issue is caused by package @angular/common/http

### Is this a regression?

Maybe? Not sure if this is a desired or intentional change in behavior or not.

### Description
When you instantiate an instance of HttpParams and set one of the parameters to null or undefined, it sets the value of the parameter to "null" or "undefined" as a string, causing them to get passed in the query string later as param=null. This seems to be a change in behavior from Angular 11 where it was stored as null, the value instead of a string.

## Minimal Reproduction

```
let params = new HttpParams();
params = params.set('testParam', null);
const paramValue = params.get('testParam');
console.log(paramValue);
console.log(params); // taking a look at the value stored in the map property, it looks like it was stored internally as the value null in Angular 11 and is now stored as a string with the value of "null" in Angular 12
```

## Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 12.0.5
Node: 14.17.1
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@schematics/angular             12.0.5
rxjs                            7.1.0
typescript                      4.2.4
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
This was changed in #40663. The typings of e.g. `HttpParams.set` does not accept `null` or `undefined`, so these values have been invalid according to the API definition. This may have gone unnoticed if `strictNullChecks` is not enabled, though.

**Comment by petebacondarwin** [comment]
The `HttpParams` class always converted its values to strings when serializing to a URL query. E.g.

```ts
const p = new HttpParams();
const p2 = p.set('a', null);
console.log(p2.toString());
```

This will output:

```
a=null
```

in both v11 and v12.

The main difference between v11 and v12 is that you could force a non-string into the internal map, probably if you did not have strict null checks on (as @JoostK suggests). Then when you `get()` the value back out it is still a non-string.

Now we enforce that these values are strings at runtime when you add them to the `HttpParams` array.

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
