### ISSUE TITLE
Compiler CLI typings cannot be processed with typescript 4.2.4

### ISSUE THREAD

**Issue by wszydlak** [angular/angular#42685]
# Bug Report

### Affected Package

The issue is caused by package @angular/compiler-cli

### Is this a regression?

Don't know

### Description
Compiler CLI uses **ts.MemberName** type, which in typescript 4.2.4 is not present, probable added in typescript 4.3 which reports error:

```
node_modules/@angular/compiler-cli/src/ngtsc/translator/src/typescript_ast_factory.d.ts:38:73 - error TS2694: Namespace 'ts' has no exported member 'MemberName'.
```

## Minimal Reproduction

 Try to compile compiler-cli ts files with ts 4.2.4

## Exception or Error
<pre><code>
node_modules/@angular/compiler-cli/src/ngtsc/translator/src/typescript_ast_factory.d.ts:38:73 - error TS2694: Namespace 'ts' has no exported member 'MemberName'.

</code></pre>

## Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 12.1.0
</code></pre>

**Anything else relevant?**
Probably compiler-cli should require at last typescript 4.3 or should not use types which were not present in typescript 4.2.4

**Comment by petebacondarwin** [comment]
We don't actually use this type directly. Instead we have the following in our `TypeScriptAstFactory` class:

```ts
  createPropertyAccess = ts.createPropertyAccess;
```

And when TS 4.3 compiles this we get:

```ts
    createPropertyAccess: (expression: ts.Expression, name: string | ts.MemberName) => ts.PropertyAccessExpression;
```

So this is a result of us using 4.3 to compile our own source code...

**Comment by JoostK** [comment]
I think the main scenario where this may break consumers is when custom build tooling written in TS is used that uses the non-public compiler-cli APIs. Otherwise I also don't see a reason why the declaration files of compiler-cli should be present in a TS compilation. For this use-case I think it's reasonable to set `skipLibCheck: true` to workaround the issue.

**Comment by wszydlak** [comment]
Yes, we detected this problem using custom build tools with `skipLibCheck: false` and we would like to keep this option. We don't use non-public compiler-cli APIs but because of skipLibCheck typescript is reporting this error.

**Comment by JoostK** [comment]
> We don't use non-public compiler-cli APIs

Everything in `compiler-cli` is non-public, so having that included in a TypeScript compilation means that there is some usage of non-public API.

**Comment by wszydlak** [comment]
As i said - we don't even import anything from `compiler-cli`, just from `@ngtools/webpack` which has imports to `compiler-cli`.

**Comment by JoostK** [comment]
Ah, yes that sounds likely!

**Comment by alan-agius4** [comment]
Discussed this with @devversion and we feel that the best course of action here is that if you are using the compiler-cli **types/API** both directly or transitively via `@ngtools/webpack`. The better option would be to use the same TypeScript version used to compile the package. This is typically the max version which is supported by the Angular Compiler. If for a reason or another this is not possible using `skipLibCheck` as an interim solution is a good enough workaround.

The reasoning behind this is that while making `@angular/compiler-cli` work with TypeScript 4.2 **type-wise** is straightforward in this case, it sets the precedent for us "caring" about such things which might complicate things in the future.

While we do guarantee the the compiler will compile source files when using TypeScript 4.2, we don't guarantee that its' types are compatible with this version.

**Comment by wszydlak** [comment]
I understand your point of view. It would be cool if compiler will have types compatibile with peerDependency typescript version. Maybe information about used typescript version when compiling using custom tools should be documented somewhere? If `compiler-cli` doesn't have any public APIs, then maybe this should be documented in `@ngtools/webpack`? Or maybe even `@ngtools/webpack` should have peerDependency of typescript which satisfies compiler types?

**Comment by devversion** [comment]
@wszydlak yeah, you're probably right that `ngtools/webpack` should make this requirement clear either through docs or a peer dependency if `@ngtools/webpack` is considered public. cc. @alan-agius4

**Comment by alan-agius4** [comment]
`@ngtools/webpack` supports the exact versions of TypeScript versions that the framework support, in terms of which version of TypeScript can be used to compile an application. 

 Therefore, changing the TypeScript peer dependency to the upper bound version would not be correct here and technically it would be a breaking change. 

We can add it to the docs, although from my experience this is the first time that someone experienced this problem and seeing that this issue didn't receive any community interest. I'd say it doesn't warrant to do any change from our end and having this issue on GitHub should be sufficient.

We can always revisit this if we see that it impacts the community in a greater manner, but for the time being my suggestion would be to close this issue as also by using `@ngtools/webpack` directly you are opting to off the "happy path".

**Comment by devversion** [comment]
yeah, I agree. Let's close this. thanks Alan! 

We can always revisit if more people
hit such an issue.
