### ISSUE TITLE
Angular 12 - Uncaught Error: Angular JIT compilation failed: '@angular/compiler' not loaded!

### ISSUE THREAD

**Issue by bhaukumar** [angular/angular#42686]
Hi,

We have upgraded to Angular 12 and facing JIT Compilation failed issue during runtime. Even though IVY is enabled and AOT is true, it throws 'Angular JIT compilation failed'. Why does it compile during runtime if AOT is true? 
We are stuck in this issue since few days .

Uncaught Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
    at getCompilerFacade (core.js:4031)
    at Module.ɵɵngDeclareFactory (core.js:33079)
    at primeng-api.js:113
    at Module.IpNV (primeng-api.js:114)
    at __webpack_require__ (bootstrap:79)
    at Module.rlfA (vendor.js:323316)
    at __webpack_require__ (bootstrap:79)
    at Module.6tCy (vendor.js:26460)
    at __webpack_require__ (bootstrap:79)
    at Module.X366 (vendor.js:250158)

Angular.json:
-----
     "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "build/ng",
            "index": "ngsrc/index.html",
            "main": "ngsrc/main.ts",
            "polyfills": "ngsrc/polyfills.ts",
            "tsConfig": "ngsrc/tsconfig.app.json",
            "assets": [
              { "glob": "**/*", "input": "web/images", "output": "/assets/" },
			  { "glob": "env.js", "input": "ngsrc/environments", "output": "." },
              { "glob": "**/*", "input": "web/Resources", "output": "/Resources/" }
            ],
            "styles": [
              "../node_modules/font-awesome/css/font-awesome.css",
              "../node_modules/primeng/resources/themes/nova/theme.css",
              "../node_modules/primeng/resources/primeng.css",
              "../node_modules/primeicons/primeicons.css",
              "../node_modules/primeflex/primeflex.css",
              "ngsrc/styles/grid.css",
              "ngsrc/styles/common.scss"
            ],
            "scripts": ["../node_modules/chart.js/dist/Chart.js"],
            "aot": true,
            "buildOptimizer": true
          },--------

Package.json:
{
  "name": "app",
  "version": "9.5.0",
  "scripts": {
    "ng": "ng",
    "build": "ng build",
    "gzipper": "gzipper compress",
    "compress": "gzipper compress"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^12.0.5",
    "@angular/cdk": "^12.0.5",
    "@angular/common": "~12.0.5",
    "@angular/compiler": "~12.0.5",
    "@angular/core": "~12.0.5",
    "@angular/forms": "~12.0.5",
    "@angular/platform-browser": "~12.0.5",
    "@angular/platform-browser-dynamic": "~12.0.5",
    "@angular/router": "~12.0.5",
    "@types/file-saver": "^2.0.0",
    "angular-split": "~3.0.2",
    "angular2-hotkeys": "~2.1.5",
    "chart.js": "~2.9.4",
    "classlist.js": "^1.1.20150312",
    "core-js": "^3.15.1",
    "dom-to-image": "^2.6.0",
    "file-saver": "^2.0.1",
    "font-awesome": "^4.7.0",
    "gojs": "^2.1.43",
    "gojs-angular": "^0.0.5",
    "lodash": "~4.17.19",
    "moment": "^2.24.0",
    "ng2-date-picker": "^2.11.0",
    "ng2-pdf-viewer": "^6.0.0",
    "pdfjs-dist": "2.2.228",
    "pdfmake-lite": "^0.1.66",
    "primeflex": "^1.3.1",
    "primeicons": "^4.1.0",
    "primeng": "^12.0.0",
    "rxjs": "~6.6.3",
    "stream": "^0.0.2",
    "timers": "^0.1.1",
    "uuid": "^3.3.3",
    "web-animations-js": "^2.3.2",
    "xml2js": "^0.4.23",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1002.1",
    "@angular-devkit/build-ng-packagr": "~0.1002.1",
    "@angular/cli": "~12.0.5",
    "@angular/compiler-cli": "~12.0.5",
    "@angular/language-service": "~12.0.5",
    "@types/node": "~12.20.15",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^10.1.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tsickle": "^0.39.1",
    "tslib": "^2.0.3",
    "tslint": "~6.1.0",
    "typescript": "~4.2.4",
    "webpack-bundle-analyzer": "~3.8.0",
    "compression-webpack-plugin": "~4.0.0",
    "gzipper": "^4.0.1"
  }
}

Any help would be appreciated.

Thanks,
--Bhau

**Comment by JoostK** [comment]
`primeng` has been updated [to use partial compilation](https://unpkg.com/browse/primeng@12.0.0/fesm2015/primeng-api.js), which requires post-processing by the linker in order to get AOT compiler. That should happen transparently when using the CLI. I notice in the stack trace that `primeng-api.js` is present verbatim, hinting that it has not been loaded through Webpack but manually?

**Comment by JoostK** [comment]
Actually, Pete's keen eyes noticed the following in your package.json:

```
"@angular-devkit/build-angular": "~0.1002.1",
"@angular-devkit/build-ng-packagr": "~0.1002.1",
```

That indicates that you may not be using the latest build tooling that is needed to run the linker. Could you please update the `"@angular-devkit/build-angular"` dependency to "~12.0.5" and drop the `"@angular-devkit/build-ng-packgr"` dependency as that no longer exists in v12.

**Comment by bhaukumar** [comment]
Thanks for the response.

We just upgraded from PrimeNg11 (which was working fine) . There is no code change in application. 

Let me update devDependencies as you suggested and see if it resolves the issue. Shouldn't angular (ng update) and 'npm update' upgraded (or warned) that?

--Bhau

**Comment by bhaukumar** [comment]
Hi,
I am getting error during build time (instead of runtime)  after modification.

Error:
An unhandled exception occurred: Cannot find module '@angular-devkit/build-ng-packagr/package.json'
Require stack:
- D:\devenv\ii\NG11\components\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- D:\devenv\ii\NG11\components\node_modules\@angular-devkit\architect\node\index.js
- D:\devenv\ii\NG11\components\node_modules\@angular\cli\models\architect-command.js
- D:\devenv\ii\NG11\components\node_modules\@angular\cli\commands\build-impl.js
- D:\devenv\ii\NG11\components\node_modules\@angular-devkit\schematics\tools\export-ref.js
- D:\devenv\ii\NG11\components\node_modules\@angular-devkit\schematics\tools\index.js
- D:\devenv\ii\NG11\components\node_modules\@angular\cli\utilities\json-schema.js
- D:\devenv\ii\NG11\components\node_modules\@angular\cli\models\command-runner.js
- D:\devenv\ii\NG11\components\node_modules\@angular\cli\lib\cli\index.js
- D:\devenv\ii\NG11\components\node_modules\@angular\cli\lib\init.js
- D:\devenv\ii\NG11\components\node_modules\@angular\cli\bin\ng
- 


New Package.json:

{
  "name": "app",
  "version": "9.5.0",
  "scripts": {
    "ng": "ng",
    "build": "ng build",
    "gzipper": "gzipper compress",
    "compress": "gzipper compress"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^12.0.5",
    "@angular/cdk": "^12.0.5",
    "@angular/common": "~12.0.5",
    "@angular/compiler": "~12.0.5",
    "@angular/core": "~12.0.5",
    "@angular/forms": "~12.0.5",
    "@angular/platform-browser": "~12.0.5",
    "@angular/platform-browser-dynamic": "~12.0.5",
    "@angular/router": "~12.0.5",
    "@types/file-saver": "^2.0.0",
    "angular-split": "~3.0.2",
    "angular2-hotkeys": "~2.1.5",
    "chart.js": "~2.9.4",
    "classlist.js": "^1.1.20150312",
    "core-js": "^3.15.1",
    "dom-to-image": "^2.6.0",
    "file-saver": "^2.0.1",
    "font-awesome": "^4.7.0",
    "gojs": "^2.1.43",
    "gojs-angular": "^0.0.5",
    "lodash": "~4.17.19",
    "moment": "^2.24.0",
    "ng2-date-picker": "^2.11.0",
    "ng2-pdf-viewer": "^6.0.0",
    "pdfjs-dist": "2.2.228",
    "pdfmake-lite": "^0.1.66",
    "primeflex": "^1.3.1",
    "primeicons": "^4.1.0",
    "primeng": "^12.0.0",
    "rxjs": "~6.6.3",
    "stream": "^0.0.2",
    "timers": "^0.1.1",
    "uuid": "^3.3.3",
    "web-animations-js": "^2.3.2",
    "xml2js": "^0.4.23",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.0.5",
    "@angular/cli": "~12.0.5",
    "@angular/compiler-cli": "~12.0.5",
    "@angular/language-service": "~12.0.5",
    "@types/node": "~12.20.15",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^10.1.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tsickle": "^0.39.1",
    "tslib": "^2.0.3",
    "tslint": "~6.1.0",
    "typescript": "~4.2.4",
    "webpack-bundle-analyzer": "~3.8.0",
    "compression-webpack-plugin": "~4.0.0",
    "gzipper": "^4.0.1"
  }
}


I noticed ng-packagr is configured in all the local libraries I am including in angular.json. Should I remove ng-packagr reference in that also (if yes, what would it replace by)?

angular.json:
----
   "uiplatform": {
      "root": "platform/UIPlatform",
      "sourceRoot": "platform/UIPlatform/ngsrc",
      "projectType": "library",
      "prefix": "ng",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "platform/UIPlatform/tsconfig.ui.json",
            "project": "platform/UIPlatform/ng-package.json"
          }
        }
      }
    },

Tahnks,
--Bhau

**Comment by JoostK** [comment]
Something seems to have gone wrong during your upgrade path, as the `ng-packagr` builder should have been replaced with `"@angular-devkit/build-angular:ng-packagr"`.

**Comment by bhaukumar** [comment]
How it was working fine with Angular 7, 8, 9,10 and now 11. But failing with 12?
--Bhau

**Comment by JoostK** [comment]
Because Angular 12 introduced a new publication format for libraries that requires latest tooling. `primeng` 12 has switched to using the new publication format, so now the tooling needs to be up-to-date to support it.

**Comment by bhaukumar** [comment]
Make sense. 

Let me replace build options for all libraries in angular.json and try again. 

Thanks,
--Bhau

**Comment by bhaukumar** [comment]
Hi,

It went little farther but getting new error during build time again:

----

../node_modules/@angular-devkit/build-angular/src/webpack/es5-polyfills.js:106:0-37 - Error: Module not found: Error: Can't resolve 'zone.js/plugins/zone-legacy' in 'D:\devenv\ii\NG11\components\node_modules\@angular-devkit\build-angular\src\webpack'



> Task :buildAngularClient FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildAngularClient'.
> Process 'command 'C:\Users\pbhawnani\.gradle/sdks/node/14.17.1/node-v14.17.1-win-x64/node.exe'' finished with non-zero exit value 1

Thanks,
--Bhau

**Comment by JoostK** [comment]
You'll need to update `zone.js` to `~0.11.0`. Please also review your installation logs are these issues should be reported as peer dependency warnings.

**Comment by petebacondarwin** [comment]
You could also try:

```
ng update @angular/cli --migrate-only --from 11
```

which should run the migrations that were missed.

**Comment by bhaukumar** [comment]
Hi,

Thanks for the help. 

After upgrading zone.js to version 11, it builds and runs fine. 

However I noticed following things during build process:
1) Build process logged many 'Circular dependency' warnings. Which were not the case earlier. May be it is Angular 12 related. I will take a look for these and refactor the code. Is there any command to generate  only circular dependency warmings at one place?

2) There are many warnings regarding 'imported from external module.. but never used in.. ' which was not the case with earlier versions. 
For example: 'WARNING: "HttpClient" is imported from external module "@angular/common/http" but never used in "..\DashboardFramework\build\ng\esm2015\services\dashboardframework.service.js" and "..\DashboardFramework\build\ng\esm2015\dashboardframework.module.js".'

When I looked corresponding typescript file (dashboardframework.service.ts) , I noticed that 'HttpClient' is being used in many 'places. Not sure why generated javascript file says not used. Am I missing something or is it a bug with Angular 12? 

3) We are building many custom libraries and publishing these to shared node_modules before building the application . So that other internal applications can use common custom libraries. So far we are running ngcc script across node_modules (and custom libraries) to make it work since we upgraded from Angular 7 to Angular 9 and beyond. But Angular 12 sometimes show ngcc lock related errors. Not sure do we still need to run ngcc any more with Angular 12 or can we skip that process?

 Thanks,
--Bhau

**Comment by petebacondarwin** [comment]
I believe we started reporting circular dependency warnings in v12. Those dependencies would have been there before but we were not warning about them. Note that libraries will not be allowed to contain circular dependencies.

**Comment by petebacondarwin** [comment]
Regarding your internal libraries. If you control the version of Angular used to build the libraries and run the app (and can ensure that they are identical) then you can actually just build you libraries with full ivy AOT turned on.
If you don't control that then you can build in `partial` compilation-mode, which is a portable form of Ivy specifically designed for libraries. These libraries will be "linked" to full ivy at bundling time by the Angular CLI.
If your libraries might need to be used by apps running Angular earlier than v12 then you will still need to build using ViewEngine mode and run ngcc on them.

**Comment by bhaukumar** [comment]
We build all our products with same Angular version (now 12) . So we removed running ngcc post install script and tried to build. But we are getting errors for building of many libraries (not all). As per error details it seems build process is trying to run concurrent processes for ngcc script.  Even though we are not running running any ngcc script anywhere. 
1) Does angular build process runs ngcc internally? 
2) Do we still need to run ngcc post install script (as it works fine with ngcc post install script) ?

----------------------------------
Building entry point 'Base':
---------------------------------

Compiling TypeScript sources through ngc
ERROR: ngcc is already running at process with id 25820.
If you are running multiple builds in parallel then you might try pre-processing your node_modules via the command line ngcc tool before starting the builds.
(If you are sure no ngcc process is running then you should delete the lock-file at D:/devenv/ii/NG12/components/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)
An unhandled exception occurred: ngcc is already running at process with id 25820.
If you are running multiple builds in parallel then you might try pre-processing your node_modules via the command line ngcc tool before starting the builds.
(If you are sure no ngcc process is running then you should delete the lock-file at D:/devenv/ii/NG12/components/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)

------------------------------
Building entry point 'ImpExp':
----------------------------
Compiling TypeScript sources through ngc
ERROR: ngcc is already running at process with id 25820.
If you are running multiple builds in parallel then you might try pre-processing your node_modules via the command line ngcc tool before starting the builds.
(If you are sure no ngcc process is running then you should delete the lock-file at D:/devenv/ii/NG12/components/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)
An unhandled exception occurred: ngcc is already running at process with id 25820.
If you are running multiple builds in parallel then you might try pre-processing your node_modules via the command line ngcc tool before starting the builds.
(If you are sure no ngcc process is running then you should delete the lock-file at D:/devenv/ii/NG12/components/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)

------------------------------------------------------------------------------
Building entry point 'directory'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
ERROR: ngcc is already running at process with id 25820.
If you are running multiple builds in parallel then you might try pre-processing your node_modules via the command line ngcc tool before starting the builds.
(If you are sure no ngcc process is running then you should delete the lock-file at D:/devenv/ii/NG12/components/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)
An unhandled exception occurred: ngcc is already running at process with id 25820.
If you are running multiple builds in parallel then you might try pre-processing your node_modules via the command line ngcc tool before starting the builds.
(If you are sure no ngcc process is running then you should delete the lock-file at D:/devenv/ii/NG12/components/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)

Thanks,
--Bhau

**Comment by JoostK** [comment]
> Does angular build process runs ngcc internally?
Indeed, as ngcc is still needed for many libraries.

> Do we still need to run ngcc post install script (as it works fine with ngcc post install script) ?

I would advise to keep the postinstall script if removing it is causing concurrency issues.

**Comment by JoostK** [comment]
I should also add that ng-packagr is outdated and also needs to be updated to the latest version:

```
"ng-packagr": "^10.1.2",
```

That should be `"^12.0.0"`, in line with the rest of the Angular dependencies. This may resolve the `imported from external module.. but never used` messages.

**Comment by bhaukumar** [comment]
I modified ng-packagr version to "^12.0.8"  . But it does not remove warnings about 'imported..never used...' messages. 
Most of the build log is filled with either this or circular dependencies warning messages. Is there any flag or configuration to suppress these warnings? I see default value ('showCircularDependencies') in schema.json is  false . But it still does show these warnings. May be there is some different flag to avoid these warnings?

**Comment by bhaukumar** [comment]
Thanks for the help to resolve the issue . 
Warnings are not an issue. It is just extra information to make our code better. I will keep looking to suppress these warnings. But the original issue is resolved.
