### ISSUE TITLE
lazy load from ngComponentOutlet is broken after v12

### ISSUE THREAD

**Issue by irowbin** [angular/angular#42683]
# Bug Report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: v11

### Description
 
We have this lazy components that loads using `*ngComponentOutlet` directive in v11 but after upgrade to v12, the same code didn't worked as it displays errors like
` Can't bind to 'ngIf' since it isn't a known property`
or 
`The pipe 'async' could not be found!` etc., I think this is because of the common module isn't get referenced.

## Minimal Reproduction

I have created [this stackblitz repo](http://stackblitz.com/edit/angular-nested-lazy-component-nxuaoj) so just open the console and you'll see the issues.

If you downgrade it into v11, the same code works.

```ts
// alzy-two component

@Component({
  selector: 'app-lazy-2',
  template: `
    <h4>loading lazy level 2</h4>
  `
})
export class LazyTwoComponent {}

// lazy-two module
import { LazyTwoComponent } from './lazy-two.component';

@NgModule({
  imports: [CommonModule],
  declarations: [LazyTwoComponent]
})
export class LazyTwoModule {}

```

```ts
// lazy one

import { LazyTwoComponent } from '../lazy2/lazy-two.component';

@Component({
  selector: 'app-lazy-1',
  template: `
    <h1 *ngIf="title">{{title}}</h1>
    <ng-template [ngIf]="lazyComp | async">
     <ng-container *ngComponentOutlet="lazyComp | async"></ng-container>
    </ng-template>
  `
})
export class LazyOneComponent implements AfterViewInit {
  title = 'hello from one'
  lazyComp: Promise<Type<LazyTwoComponent>>
  ngAfterViewInit(){
    this.lazyComp = import('../lazy2/lazy-two.component')
    .then(({LazyTwoComponent})=> LazyTwoComponent)
  }
}

// lazy-one.module

import { LazyOneComponent } from './lazy-one.component';

@NgModule({
  imports: [CommonModule],
  declarations: [LazyOneComponent]
})
export class LazOneModule {}

```

```ts
// app.ts

import { LazyOneComponent } from './components/lazy1/lazy-one.component';

@Component({
  selector: 'my-app',
  template`<ng-container *ngComponentOutlet="lazyComp | async"></ng-container>`
})
export class AppComponent implements AfterViewInit  {

  lazyComp: Promise<Type<LazyOneComponent>>

  ngAfterViewInit(){
    this.lazyComp = import('./components/lazy1/lazy-one.component').then(({LazyOneComponent}) => LazyOneComponent)
  }
}

// app.module

import { AppComponent } from './app.component';

@NgModule({
  imports:      [CommonModule, BrowserModule],
  declarations: [ AppComponent],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }
```

## Exception or Error
<pre><code>

NG0303: Can't bind to 'ngIf' since it isn't a known property of 'h1'.
NG0302: The pipe 'async' could not be found!.
</code></pre>

## Your Environment

**Angular Version:** 
<pre><code>

@angular-devkit/architect       0.1201.0
@angular-devkit/build-angular   12.1.0
@angular-devkit/core            12.1.0
@angular-devkit/schematics      12.1.0
@schematics/angular             12.1.0
rxjs                            6.6.7
typescript                      4.3.4
</code></pre>

**Comment by mlc-mlapis** [comment]
@irowbin Hmm, it looks like you use `this.lazyComp = import('./components/lazy1/lazy-one.component').then(({LazyOneComponent}) => LazyOneComponent)` to import that `LazyOneComponent` and the corresponding `LazOneModule ` is not located in the same TS file. Or is it?

**Comment by irowbin** [comment]
> @irowbin Hmm, it looks like you use `this.lazyComp = import('./components/lazy1/lazy-one.component').then(({LazyOneComponent}) => LazyOneComponent)` to import that `LazyOneComponent` and the corresponding `LazOneModule ` is not located in the same TS file. Or is it?

Which file you're referring?  I have imported the `LazyOneComponent` to  `LazOneModule` and used `LazyOneComponent` in app component doing `import('./components/lazy1/lazy-one.component').then(...)` 

It'd be nice if you throw an example here cause, the same code works in v11 but after v12, it didn't.

**Comment by mlc-mlapis** [comment]
@irowbin If you have `lazy-one.component.ts` and you use `import('./components/lazy1/lazy-one.component').` then the `LazOneModule` definition should be part of the file `lazy-one.component.ts If I know, there are no changes between v11 and v12 in this area..`

**Comment by irowbin** [comment]
> definition should be part of the file

you mean should point it as 
`*ngComponentOutlet="lazyComp | async; ngModuleFactory: LazOneModule;"` though, it'll worked but I was curious that, in v11, i don't have to do such thing and it still works. Don't know how 🤔

**Comment by JoostK** [comment]
This appears to be working as expected. If the `lazy-one.module.ts` file is never imported from anywhere, the compiler won't be aware of its existence depending on the TypeScript configuration. You'll typically see something like `includes: ["src/index.ts"]` in `tsconfig.app.json` which means that a single file is included which will then pull in additional files as they are discovered through `import` statements. I suspect that in v11 this was configured differently, e.g. using an `includes` rule in `tsconfig.app.json`, such that the `lazy-one.module.ts` was part of the compilation and therefore made the list of declarations available to `LazyOneComponent`.

**Comment by mlc-mlapis** [comment]
@irowbin I simply meant to have a file `lazy-one.component.ts` that includes both `LazyOneComponent ` and `LazyOneModule `:

```
@Component({
  selector: 'app-lazy-1',
  template: `
    {{title}}
    ...
  `
})
export class LazyOneComponent {
  title = 'Hello from One';
  ...
}

@NgModule({
  imports: [CommonModule],
  declarations: [LazyOneComponent]
})
export class LazyOneModule {}
```

**Comment by irowbin** [comment]
@mlc-mlapis 

I have done exactly the same and if i put `*ngIf, async` etc., it throws errors like `Can't bind to 'ngIf' since it isn't a known property` but if i don't have any kind of common directives, there is no errors and complied successfully. 😕

**Comment by mlc-mlapis** [comment]
@irowbin Hmm, so it means that the implicit relation to the `LazyOneModule` is not understandable now in v12, and it was in v11. And because the code is still in one TS file, even variants of `includes` in `tsconfig.app.json` shouldn't play any role.

PS: I checked originally your Stackblitz reproduction, where a component and its module were in separated files.

**Comment by mlc-mlapis** [comment]
@irowbin And if I changed your Stackblitz reproduction to https://stackblitz.com/edit/angular-nested-lazy-component-hmf344?file=src%2Fapp%2Fcomponents%2Flazy1%2Flazy-one.component.ts, it works.

**Comment by irowbin** [comment]
@mlc-mlapis So you're saying that, to achieve the compilation successfully in v12,  we need to write `@component` and `@NgModule` in a single file? 🤔  But this is not the case if we go back to v11.  I'd say, either its breaking changes or should have warn/throw error before v12 when doing such declaration in separate files.  And if we check on [this doc](http://angular.io/api/common/NgComponentOutlet), it has way minimal example/scenario covered. I think this should have mentioned to the documentation as well.

**Comment by JoostK** [comment]
There is absolutely no need to declare the component and NgModule in the same file. As long as the NgModule class is imported somewhere you'll be fine.

**Comment by mlc-mlapis** [comment]
> As long as the NgModule class is imported somewhere, you'll be fine.
Yep, it's true, but is there a more logical place where to do it?

**Comment by irowbin** [comment]
@JoostK We have this countless lazy component in our project without having `Module` imported where the lazy component was imported into `declarations` array. During compilation, it was picked automatically till v11 but, after we upgrade it into v12, we are having this issues. So I wanna know, if it wasn't breaking changes, why it was worked previously and why this stop working after v12? Doesn't makes any sense. I mean we haven't touched the config part but this all happing after we upgrade it into v12. Thanks.

**Comment by mlc-mlapis** [comment]
@irowbin The logic is the same in v11 and v12. As I know, there is no difference between both versions.

**Comment by JoostK** [comment]
Indeed, there is no difference in how the compiler handles this. I suspect there has been a change to the tsconfigs in some way.

**Comment by irowbin** [comment]
> Indeed, there is no difference in how the compiler handles this. I suspect there has been a change to the tsconfigs in some way.

As you can check in the stackblitz like I have posted, the same behavior is happening. I haven't touched to the `tsconfig` there.

**Comment by mlc-mlapis** [comment]
@irowbin Do you have also a Stackblitz reproduction for v11 that works?

**Comment by mlc-mlapis** [comment]
@irowbin Your Stackblitz reproduction doesn't work with v11: https://stackblitz.com/edit/angular-nested-lazy-component-grfx52

**Comment by irowbin** [comment]
@mlc-mlapis 
Isn't the way it works is that the angular compiler analyzes `NgModules` and figures out what components or directives are available to the component in its module scope. Once it has this reference like `CommonModule, FormMoule`, it adds it to the component definition?  

A year ago in this medium post, [an author](http://netbasal.com/welcome-to-the-ivy-league-lazy-loading-components-in-angular-v9-e76f0ee2854a) wrote about this directive `ngComponentOutlet` 

Not sure since which version requires to import `LazyModule` within the app so compiler takes it as reference of lazy component where `FormModule, CommonModule` are used.

Should I close this issue?

**Comment by mlc-mlapis** [comment]
@irowbin Sure, but the main point is that the Angular compiler must understand that such a module should be taken into account. That's why there should be something that did it in your case, and **it's not clear what it was**.

> There is absolutely no need to declare the component and NgModule in the same file. As long as the NgModule class is imported somewhere, you'll be fine.

> The way it works is that the Angular compiler analyzes your NgModules and figures out what components or directives are available to the component in its module scope. Once it has this data, it adds it to the component definition.

Netanel Basal's article uses the variant of a single file for declaring a component and its module.
