### ISSUE TITLE
When using ng-template context object binding with ngModel, if the object instance changes, the binding output still applies to the old object

### ISSUE THREAD

**Issue by ori9933** [angular/angular#42698]
# Bug Report

### Affected Package

 The issue is caused by package @angular/core 12

### Is this a regression?

 Yes, the previous version in which this bug was not present was: @angular/core 11

### Description

1. Use ng-template and pass to it a context object.
2. Use ngmodel two-way binding to one of the object's fields.
3. Update the instance of the object.

Result: The binding output applies to the initial object instance instead of the new one.

## Minimal Reproduction

[https://stackblitz.com/edit/angular-ivy-ggda6d?file=src/app/app.component.html](https://stackblitz.com/edit/angular-ivy-ggda6d?file=src/app/app.component.html)

To reproduce follow these steps:
1. Update the input text and observe how it is updating the initial object properly.
2. Click on replace button - this will replace to object instance so the binding should work now with the new object.
3. Update the input text and observe how it is still updating the initial object instead of the new object.

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 12.0.2
Node: 12.18.3
Package Manager: npm 6.14.6
OS: darwin x64

Angular: 12.0.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.2
@angular-devkit/build-angular   12.0.2
@angular-devkit/core            12.0.2
@angular-devkit/schematics      12.0.2
@schematics/angular             12.0.2
rxjs                            6.6.3
typescript                      4.2.4
</code></pre>

**Comment by ChellappanRajan** [comment]
Hi @crisbeto https://stackoverflow.com/questions/68295743/ngtemplateoutletcontext-does-not-work-with-function-bindthis-in-angular-ivy Is this similar issue?
