### ISSUE TITLE
Dynamic type for form input doesn't get correct control value accessor

### ISSUE THREAD

**Issue by princemaple** [angular/angular#42695]
# Bug Report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

No

### Description
```html
<input [type]="dynamicType" ngModel />
```

with `dynamicType = 'number'` does not get `NumberValueAccessor` - value is string

## Minimal Reproduction

https://stackblitz.com/edit/dynamic-input-type?file=src%2Fapp%2Fapp.component.html

## Exception or Error
N/A

## Your Environment

**Angular Version:**
<pre><code>@angular/animations 12.1.0
@angular/common 12.1.0
@angular/compiler 12.1.0
@angular/core 12.1.0
@angular/forms 12.1.0
@angular/platform-browser 12.1.0
@angular/platform-browser-dynamic 12.1.0
@angular/router 12.1.0</code></pre>

**Anything else relevant?**
N/A

**Comment by JoostK** [comment]
This is a known limitation and being tracked in #13243.

**Comment by princemaple** [comment]
Thanks! Somehow failed to locate that issue.
