### ISSUE TITLE
Angular NGRX-data can't custom the URL

### ISSUE THREAD

**Issue by sfiller23** [angular/angular#42707]
here are my screen shots at stuckoverflow:
https://stackoverflow.com/questions/68188703/why-my-custom-url-for-ngrx-data-dont-work

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
