### ISSUE TITLE
Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self' data:".

### ISSUE THREAD

**Issue by nimatrazmjo** [angular/angular#42709]
# Bug Report

### Affected Package

 The issue is caused by package @angular 12.0.1

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
I have upgraded my angular from 10.* to 12. the build was successful, however, when I browse my CDN links does not work.

## Minimal Reproduction

 https://stackblitz.com/...

## Exception or Error
<pre><code>

<img width="1561" alt="Screen Shot 2021-06-30 at 11 26 21 AM" src="https://user-images.githubusercontent.com/3712526/123915772-1aa0ce00-d996-11eb-90f8-6ef812d60deb.png">

</code></pre>

## Your Environment

**Angular Version:**
<pre><code>

nr@nr application % ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.1.0
Node: 14.17.0
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 12.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic
... platform-server, pwa, router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.1000.8
@angular-devkit/build-angular              0.1000.8
@angular-devkit/core                       10.0.8
@angular-devkit/schematics                 12.1.0
@nguniversal/common                        10.1.0
@nguniversal/express-engine                12.1.0
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        12.1.0
rxjs                                       7.1.0
typescript                                 4.2.3
webpack                                    4.46.0
</code></pre>

**Anything else relevant?**

I debugged and went to the source code and found out that following code has been added in `server.js` for SSR and `main.js` file

```
res.setHeader('Content-Type', 'text/html; charset=UTF-8')
  res.setHeader('Content-Length', Buffer.byteLength(doc))
  res.setHeader('Content-Security-Policy', "default-src 'none'")
  res.setHeader('X-Content-Type-Options', 'nosniff')
```

in the mentime if have added following line in my `index.html` file. It didnt work

```
	<meta http-equiv="Content-Security-Policy" content="default-src *;
	   img-src * 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' *;
	   style-src  'self' 'unsafe-inline' *">
```

**Comment by gkalpak** [comment]
This sounds like an issue for https://github.com/angular/universal.

**Comment by alan-agius4** [comment]
If you have critical CSS enabled, you might want to disable that, see: https://github.com/angular/angular-cli/issues/20864

Otherwise, the root cause can be due to incorrect CSPs configured in your HTML file. See https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP for more information on how to configure CSPs and which policy you need to add for various file types.

If the problem persist please open a new issue with a minimal reproduction. Thanks.
