### ISSUE TITLE
RFC: routing to template/controller pairs in Angular 1 router

### ISSUE THREAD

**Issue by btford** [angular/angular#4270]
In order to aid migration to Component Router, we need a convenient way to configure a route as controller + template pair.

We have a couple options:

- support this in route declaration, overloading the `component` property
- provide this mechanism through the `module.component` API

**Comment by satish860** [comment]
Components of angular 2 will be similar to the controller-view pair. In this case when we provide controller(Component) name we are making it work the similar as angular 2 component. 

Also I am not aware of module.component Api. Can you please throw some light on the same.

**Comment by PascalPrecht** [comment]
@satish860 the `module.component` helper API has been proposed a very long time ago right here https://github.com/angular/angular.js/issues/10007. AFAIK this is under consideration to land in Angular 1.5.

**Comment by satish860** [comment]
Oh, Didnt know this.. But component API looks great..  In that case it will be great to have the Router coming out to support the API

**Comment by btford** [comment]
Closing since the component API has landed, and the mechanisms for the angular 1 branch have drastically changed.
