### ISSUE TITLE
Angular 8: Css selectors with escaped sequence not working

### ISSUE THREAD

**Issue by nmfzone** [angular/angular#42712]
# Bug Report

### Affected Package

The issue is caused by package @angular/compiler@^8.3.29

### Is this a regression?

No

### Description

I know this issue has been resolved via #40264, but it's targeting Angular 11 if I'm not mistaken. Is it possible to fix this issue in Angular 8?

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.29
Node: 14.15.5
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.29
@angular-devkit/build-angular      0.803.29
@angular-devkit/build-ng-packagr   0.803.29
@angular-devkit/build-optimizer    0.803.29
@angular-devkit/build-webpack      0.803.29
@angular-devkit/core               8.3.29
@angular-devkit/schematics         8.3.29
@angular/cdk                       6.4.7
@angular/cli                       8.3.29
@ngtools/webpack                   8.3.29
@schematics/angular                8.3.29
@schematics/update                 0.803.29
ng-packagr                         5.7.1
rxjs                               6.3.3
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Comment by JoostK** [comment]
Angular 8 is no longer supported and only security fixes are backported to LTS versions. Please review [the support policy](https://angular.io/guide/releases#support-policy-and-schedule) for further details.
