### ISSUE TITLE
you can make it either a feature request or a bug I dont care. Fact is when the page loads and I have subscribed to the router.events then inside the router/route should not be null. When I am inside a component I am already that far in the pipeline that a router must be there else something is broken.

### ISSUE THREAD

**Issue by msqaddura** [angular/angular#42711]
you can make it either a feature request or a bug I dont care. Fact is when the page loads and I have subscribed to the router.events then inside the router/route should not be null. When I am inside a component I am already that far in the pipeline that a router must be there else something is broken.

Its just a matter of time when the router/route is available. For this I have outcommented a setTimeout function in the router.events.subscribe(... setTimeout...) put some miliseconds there and I can access the router/route. That even worked in angularJS ui router where I had a global route change handler in the app.js. Angular 2 shouldn`t make it worse?

_Originally posted by @bastienJS in https://github.com/angular/angular/issues/13829#issuecomment-271105894_

**Comment by msqaddura** [comment]
Basically it is a lifecycle issue, 
you can only get the routes in the constructor. if however you try to do so in lifecycle hook `ngOnInit` then it is too late. 

donnu if this is an issue or normal behaviour, but at least you know  how to solve the original issue as it was just ignored

**Comment by JoostK** [comment]
Please open a new issue that provides all the details, according to the issue template. It's not clear currently what your setup is exactly and the original reproduction on plunkr is no longer working, so I'd ask to prepare a new reproduction that shows the problem you're having. Thanks.
