### ISSUE TITLE
Upgrade Material 10 to 11

### ISSUE THREAD

**Issue by SummersT** [angular/angular#42714]
# Docs or angular.io Bug Report

### Description

 When running the provided command: **ng update @angular/material**, the update errored due to incompatible peer dependency in @angular-devkit/build-angular.

Recommend **ng update @angular/material@11** which worked for me

## Minimal Reproduction
1. Run **ng update @angular/core@11 @angular/cli@11**
2. Run **ng update @angular/material**

Project at Angular 10.2 to start.

### What's the affected URL?**
 https://update.angular.io/?v=10.2-11.0  (possibly others)

## Exception or Error
<pre><code>

</code></pre>

**Comment by petebacondarwin** [comment]
The correct repo for this issue is https://github.com/angular/angular-update-guide.
And there already appears to be a PR there to fix this: https://github.com/angular/angular-update-guide/pull/135.
