### ISSUE TITLE
Chrome autofill on mobile makes login fail

### ISSUE THREAD

**Issue by tbnovaes** [angular/angular#42716]
#### Bug, feature request, or proposal:
When using chrome to autofill username and password on mobile chrome, login fails as soon as page loads, and it is not possible to login until, edit at least one character of each field manually

#### What is the expected behavior?
Login not to fail

#### What is the current behavior?
Login keeps failing until the username and password fields are edited manually

#### What is the use-case or motivation for changing an existing behavior?
It misleads people to think their saved password is wrong

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 7.0.3
Material: 7.0.2
OS: macOS 10.14
Typescript: 3.1.3
Browsers: Chrome Mobile

#### Is there anything else we should know?
May be related to angular/components#3414

**Comment by dylhunn** [comment]
I think this is a duplicate of #30616.
