### ISSUE TITLE
`router-link` and URL have divergent behaviour with respect to non-string params

### ISSUE THREAD

**Issue by endash** [angular/angular#4272]
Using the `[router-link]` directive, a param can be bound to an array:

    <a [router-link]="['/card', {card_ids: cardIds}]">cards</a>

    ...
    @RouteConfig([
        { path: '/cards/:card_id', component: Cards, as: 'card' }
    ])
    ...
    class App {
        public cardIds: number[] = [1, 2];
    }

This results, for my dev environment, in the URL `http://localhost:5555/cards/1,2`, and a `RouteParams` argument in my `Cards` component with `{card_ids: [1, 2]}`. So far, so good.

The problem is using that URL as a URL. Now the `RouteParams` are `{card_ids: "1,2"}`. This behaviour extends to anything that isn't a string. As far as I can tell, the only solution at present is to manually coerce your parameters into a standard string representation for use in `router-link`, so that all incoming params can be treated uniformly.

Absent an API for typing params, I suppose this could just be left to documentation. It would remain a nuisance, however. The issue might seem trivial, since obviously only strings can be directly passed in a URL, but the broader capability of the internal linking behaviour is too useful to disregard off-hand from a developer's perspective, so ideally some best practice would obtain.

**Comment by btford** [comment]
Non-string params are not yet supported. See #2959.

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router robust.

This is not an issue in the new router.
