### ISSUE TITLE
AIO header's search can partially overlap/cover the blog nav link

### ISSUE THREAD

**Issue by dario-piotrowicz** [angular/angular#42724]
# Docs or angular.io Bug Report

### Description

The header's search can partially overlap and cover the blog link

### What's the affected URL?**
any page in https://angular.io/

### Reproduction Steps**
Start from a desktop wide window and slowly decrease it's width, before the nav is hidden the search input can slightly cover the blog link

### Expected vs Actual Behavior**
The nav should be hidden before the search can overlap any nav link

## Screenshot

![Peek 2021-06-30 21-36](https://user-images.githubusercontent.com/61631103/124028636-25864d80-d9ec-11eb-831a-8f3dc3c6ff61.gif)

### Browser info

Chormium: Version 91.0.4472.114 (Official Build) snap (64-bit)

### Anything else relevant?

This does not happen with small or very small browser font-sizes but happens for all medium and up

**Comment by dario-piotrowicz** [comment]
This is unrelated to the issue, but I am also confused on what happens to the navigation, I instinctively thought it would go in the left side menu, but that and the top one seem unrelated.

So, does the top nav's links just gets removed on smaller screens? :open_mouth:

**Comment by ohois** [comment]
Strange. It looks different on my machine:

![image](https://user-images.githubusercontent.com/7329097/124098652-04117a00-da5d-11eb-8ee6-ffbc89028e88.png)

The top nav items are under "About Angular"
![image](https://user-images.githubusercontent.com/7329097/124098727-1ab7d100-da5d-11eb-8942-c0b24f92c692.png)

**Comment by dario-piotrowicz** [comment]
@ohois ahhh ok that's where the links go! thanks! :stuck_out_tongue: 

About the actual bug, so on your machine the search never overlaps the BLOG link? :open_mouth: 
(but even if not I can see it gets quite close to it)

**Comment by petebacondarwin** [comment]
The issue does not happen on my setup with "Medium (recommended)" size font: MacOS 11.4 - Chrome 91.0.4472.114.
I can see it a bit when I set the font to "Large".

**Comment by petebacondarwin** [comment]
But I do notice that your page is showing the vertical scroll bars on the right of the view. I don't have this on my setup - I think it is a configurable setting? - I am not sure if the extra space that scrollbar is taking up is messing with our width calculations?

I also notice that with "Large" font, not only does the search overlap the "Blog" link but also the YouTube link on the far right falls off the page.

**Comment by ohois** [comment]
@dario-piotrowicz 

Ahh, my bad. I've used dev console from the browser to resize the page.

When scrollbars are shown it is the samee on my machine:

![image](https://user-images.githubusercontent.com/7329097/124114476-e815d480-da6c-11eb-9e63-34793867bf6a.png)

My setup:
Windows 10 1909
Chrome: 91.0.4472.124

**Comment by dario-piotrowicz** [comment]
@petebacondarwin ah yeah you're right about the YouTube link!

... Have you tried with "Vary Large"? :stuck_out_tongue_winking_eye: 
![Peek 2021-07-01 12-23](https://user-images.githubusercontent.com/61631103/124116927-6ec7b300-da67-11eb-8f48-af83c471e6fa.gif)

**Comment by dario-piotrowicz** [comment]
Hi @gkalpak, so sorry for bothering you

I am looking into this one and I have seen that the issue is the `showTopMenuWidth` set in the app component

I noticed you fixing the overlapping already around a year ago: https://github.com/angular/angular/commit/79850983e6fcedb82377f2784e6d59c62727b71e

You also decoupled the width values in which the top nav and the side nav are displayed: https://github.com/angular/angular/commit/fc7e77934fd9b5d9aacea0c5a132d7dbd13bcd3b

To solve the current issue increasing the `showTopMenuWidth` seems to solve the problem, but I was wondering if we could find a better/simpler solution

So I just wanted to ask you (I really hope you don't mind! :stuck_out_tongue_winking_eye:):
 - why is the implementation done programmatically by checking the window's innerWidth and not by hiding/showing the elements in media queries? just to actually remove the dom elements? wouldn't just be cleaner to keep the dom elements but set the display to none?
 - why did you do the decoupling? in which circumstances you'd want not to have either nav present?

anyways again sorry for bothering you, I just wanted to ask you as I am not sure I understand completely why this was implemented as it is :slightly_smiling_face: 

please let me know if you'd like me to just increase the `showTopMenuWidth` or it the implementation here can actually be changed a bit :slightly_smiling_face: 

(also instead of increasing the `showTopMenuWidth` another feasible solution could be to just reduce the margin between the link on smaller screens I'd imagine)

**Comment by dario-piotrowicz** [comment]
Ah, also I noticed that on specific width the Angular icon can overlap the search input :cry: 
![Screenshot at 2021-07-01 22-52-14](https://user-images.githubusercontent.com/61631103/124193671-2936d480-dabf-11eb-9b9e-2b6aa3ebba84.png)

(on all chrome font-sizes excluded very small)

**Comment by gkalpak** [comment]
Good questions, @dario-piotrowicz 🤔 

> So I just wanted to ask you (I really hope you don't mind! 😜):

I really, really don't mind :wink:

##
> To solve the current issue increasing the `showTopMenuWidth` seems to solve the problem, but I was wondering if we could find a better/simpler solution.

I am all for better/simpler solutions 👂 👂 👂

##
> why is the implementation done programmatically by checking the window's `innerWidth` and not by hiding/showing the elements in media queries? Just to actually remove the DOM elements?

I assume it is to remove the DOM elements. Note that these menus are implemented via Angular components (for example, [here][1] and [there][2]), which contain other components, so it is not completely inexpensive to leave them in the DOM (and just hide them via CSS).

There is also some logic to highlight the currently active nav-item and I am not sure if the current implementation can cope with multiple nav-items corresponding to the same URL being simultaneously present in the DOM (not that it can't be solved, but something to look out for).

##
> Why did you do the decoupling? In which circumstances you'd want not to have either nav present?

The decoupling is not about whether to show each nav. Both nav's are conditionally shown based on `showTopMenu` (so exactly one will be shown at each time). What I decoupled were these two things:
1. Whether to show the top menu or show the nav-items in the sidenav.
2. Whether the sidenav should be docked (i.e. if the [MatSidenav][3]'s `mode` property will be set to `side` or `over`). This, basically, determines whether a sidenav will be always shown next to the docs content (on docs pages) or whether the user has to click the hamburger button at the top left to show the sidenav.

Previously, the breakpoint for both these things was the same value, but it didn't have to be (they are not inherently coupled). As the top-menu gets more cluttered (with more nav-items, the social icons, the theme toggle, etc.) it makes sense to move the nav into the sidenav sooner, but that doesn't have to also affect the sidenav's mode (`side` vs `over`).

##
> Please let me know if you'd like me to just increase the `showTopMenuWidth` or it the implementation here can actually be changed a bit 🙂

Increasing `showTopMenuWidth` is a fine solution (at least in the sense that it improves things). If you have a better/simpler solution to propose, I would be more than happy to discuss :smiley:

##
> Also I noticed that on specific width the Angular icon can overlap the search input 😢

:cry:
At some point we should probably re-think the top-menu layout/styling 😅
I wish it were more responsive/fluid. The top-menu content has become more complex over time (with more buttons, links, separators) and the current styling implementation requires "manual intervention" on every change 😞

I don't think I'll have time to play with this some time soon, but if you feel compelled, you can give it a go, @dario-piotrowicz 😛
<sub>(TBH, the value-to-effort ratio is probably not that high 🤷‍♂️)</sub>

[1]: https://github.com/angular/angular/blob/ffeea63f43e6a7fd46be4a8cd5a5d254c98dea08/aio/src/app/app.component.html#L27
[2]: https://github.com/angular/angular/blob/ffeea63f43e6a7fd46be4a8cd5a5d254c98dea08/aio/src/app/app.component.html#L49
[3]: https://material.angular.io/components/sidenav/api#MatSidenav

**Comment by dario-piotrowicz** [comment]
Wow :scream: thank you so very much for such thorough explanation!!!!!! :heart_eyes: 

About the `side` and `over` part, I totally didn't notice that before! yeah I can see what you mean now!!

About a different solution I was thinking or re-engineering it a bit, hide the content with css and stuff (the listening of window resize events immediately struck me as suboptimal, I am really not a big fan of that), but you are making a good point that there can be better things to spend time working on as this is not the most crucial thing ever.... (especially if we, as you mentioned, would need to cater for various different aspects like the link highlights and running the risk to break something in the process)

If it's fine by you I think I will just increase the `showTopMenuWidth`  and make small quality of life improvements like making the nav items a bit more responsive and make the angular icon not overlap the search.

Sorry if the solution is anticlimactic, but yeah putting too much effort in such minor cosmetic changes may not be the best use of time

Also either way, thank you so very much again for the explanation and the help! I really do appreciated it so very much!!! :slightly_smiling_face:

**Comment by dario-piotrowicz** [comment]
should be better now :slightly_smiling_face: 

(not changed significantly but tweaked enough to remove the overlapping)
