### ISSUE TITLE
bug: `ModuleWithProviders` + `overrideComponent()` causes NgModule to be skipped

### ISSUE THREAD

**Issue by ngRevan** [angular/angular#42734]
# Bug Report

### Affected Package
I think the issue is caused by @angular/core or @angular/core/testing.

### Is this a regression?

Yes, the previous version in which this bug was not present was: 10.1.2.
Although I did use ViewEngine to run tests before.

### Description
I have a test for a component that uses `async` pipe and is declared in a module that uses `static forRoot(): ModuleWithProviders<...>` syntax. When test uses `overrideComponent` to override component providers, I get the error: `The pipe 'async' could not be found!`. The issue does not occur when to module is imported directly instead of using `.forRoot()`.

## Minimal Reproduction

https://github.com/ngRevan/override-component-sample

Run: `ng test my-lib`

**In [my-lib.component.spec.ts](https://github.com/ngRevan/override-component-sample/blob/16c78118fbba775b62aba06f1eb6dc2bd106160e/projects/my-lib/src/lib/my-lib.component.spec.ts#L20)**
Error when using:
```ts
TestBed.configureTestingModule({
  imports: [MyLibModule.forRoot()],
  declarations: [TestComponent],
})
```

No error when using:
```ts
TestBed.configureTestingModule({
  imports: [MyLibModule],
  declarations: [TestComponent],
})
```

## Exception or Error
<pre><code>
Error: NG0302: The pipe 'async' could not be found!. Find more at https://angular.io/errors/NG0302
        error properties: Object({ code: '302' })
        Error: NG0302: The pipe 'async' could not be found!. Find more at https://angular.io/errors/NG0302
            at getPipeDef$1 (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:25804:1)
            at ɵɵpipe (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:25761:1)
            at MyLibComponent_Template (ng:///MyLibComponent.js:8:9)
            at executeTemplate (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9579:1)
            at renderView (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9383:1)
            at renderComponent (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:10663:1)
ne.js:372:1)
            at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:287:1)
            at ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:371:1)
            at Zone.run (node_modules/zone.js/fesm2015/zone.js:134:1)
            at runInTestZone (node_modules/zone.js/fesm2015/zone-testing.js:567:1)
            at UserContext.<anonymous> (node_modules/zone.js/fesm2015/zone-testing.js:582:1)
            at <Jasmine>
</code></pre>

## Your Environment

**Angular Version:**
<pre><code>
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@schematics/angular             12.0.5
ng-packagr                      12.0.8
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
Thanks for the excellent reproduction @ngRevan, it really helped to narrow down what was going on.

We did some debugging and found that the the `.forRoot()` resulting in a `ModuleWithProviders` object was not being picked up in the `R3TestBedCompiler.queueTypesFromModulesArray()` function. Since that function was only prepared to handle items that were NgModule instances or arrays of NgModules, and not instances of ModuleWithProviders`.

This doesn't appear to have come up before because it also required that the component being compiled had been given additional providers by the call to `overrideComponent()` in the test; and it seems that the combination of the two is rare.

**Comment by ngRevan** [comment]
Thanks for the fast response @petebacondarwin!

Ah right that makes sense. I can imagine that the combination of the two is pretty rare.

Just for information, I got my tests to run simply by also importing the NgModule instance itself which is an easy enough workaround until this is fixed.
```ts
TestBed.configureTestingModule({
  imports: [
    MyLibModule,
    MyLibModule.forRoot()
   ],
  declarations: [TestComponent],
})
```

Thank you all for your outstanding work on Angular.
