### ISSUE TITLE
FormControl interop with web standards/vanillaJS web-components

### ISSUE THREAD

**Issue by GeorgeTailor** [angular/angular#42746]
# Bug Report

### Affected Package
@angular/forms

### Is this a regression?

all versions are affected.

### Description
Using angular with vanilla JS (web-components, for example) is hard and requires a lot of boilerplate code to be written to achieve simplest tasks.
For example consider setting a value of a formControl with
`this.form.controls.username.setValue('george');`
the above code will not emit a `change` event. 
Suppose the parent element of this formControl is a web-component which listens on change event and changes its styles accordingly, since the event is not dispatched, the result is that the value is changed, but styles stay the same.

A workaround would be to manually dispatch an event, but that requires a reference to that specific element (the bigger the form -> more references -> more code) + the code that will actually dispatch the event, something like 
```
this.usernameInput.nativeElement.dispatchEvent('change');
```

### Desired behavior
`control.setValue()`, `control.reset()` etc should dispatch a change event whenever these functions are called.

## Minimal Reproduction
https://stackblitz.com/edit/angular-a3vn2y?file=src%2Fapp%2Fapp.component.ts

**Comment by flash-me** [comment]
HI @GeorgeTailor 

I'm curious. Can you provide a link to the web standards you are talking about? Something like [W3C](https://www.w3.org/TR/html52/) or [WHATWG](https://html.spec.whatwg.org/multipage/)? 

Also I tried this with a native `input` Element, on which I listen to the `change` Event and set the value programmatically with javascript. The change event is never emitted. See 
https://stackblitz.com/edit/angular-ivy-gprzhp?file=src%2Fapp%2Fapp.component.ts

May you provide a working example of a native html element? I could be doing something wrong

cheers
flash ⚡

**Comment by lazarljubenovic** [comment]
>  but that requires a reference to that specific element

What about [this](https://angular.io/api/forms/FormControl#setValue)?

```ts
this.form.controls.username.setValue('george', { emitEvent: true })
```

**Comment by GeorgeTailor** [comment]
> 
> 
> > but that requires a reference to that specific element
> 
> What about [this](https://angular.io/api/forms/FormControl#setValue)?
> 
> ```ts
> this.form.controls.username.setValue('george', { emitEvent: true })
> ```

`emitEvent` is not a native `change` event, it only notifies the `this.form` that something has changed, for example when you have `this.form.valueChanges` listener set up.

**Comment by dylhunn** [comment]
We are unlikely integrate forms more deeply with angular elements in the near future. There are several possible DIY solutions, such as emitting the event, or implementing a custom CVA.
