### ISSUE TITLE
CSRF token not added in windows.nativeWindow.location.assign

### ISSUE THREAD

**Issue by RomaRathi** [angular/angular#42744]
There is logout api is being called and returning a view from backend as follows
doLogout = () => {
    this.errorMessageService.ping().then((response) => {
      if (response !== true) {
        return;
      }
      this.server.logOut();

      if (!this.server.isOAuth())
        **this.windows.nativeWindow.location.assign('/logout');**
    }, function (error) {
      console.log('Error in Ping Service');
    });

  }

Now when this logout is called the csrf token is not appended in the request.

# Bug Report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
 A clear and concise description of the problem...

## Minimal Reproduction

 https://stackblitz.com/...

## Exception or Error
<pre><code>

</code></pre>

## Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
