### ISSUE TITLE
Proposal: Compiler should attempt to resolve view directives from injector

### ISSUE THREAD

**Issue by StacyGay** [angular/angular#4275]
Currently directives used by a component are resolved only by type or binding specified in the directives property of the View decorator.  This is fine to prevent selector collision and to help for testing but it does not truly allow dependency injection for components or directives.  It would be incredibly useful for directives to be resolved from the parent injector, especially in multi-tenant apps.

Take a look at this example:

    abstract class GreetingComponent{
    	whomToGreet: string;
    }

    @Component({
    	selector: 'greeting'
    })
    @View({
    	template: `<h3>Hello {{whomToGreet}}!</h3>`
    })
    class GenericGreetingComponent extends GreetingComponent{ 
    	constructor() {
    		this.whomToGreet = 'Everyone';
    	}
    }

    @Component({
    	selector: 'greeting'
    })
    @View({
    	template: `<h3>Well hello there {{whomToGreet}}.</h3>`
    })
    class BobGreetingComponent extends GreetingComponent{
        constructor() {
    	    this.whomToGreet = 'Bob';
        }
    }

    var config = {
    	useBobGreeting: true
    };

    var bindings = [];

    if(config.useBobGreeting)
    	bindings.push(bind(GreetingComponent).toClass(BobGreetingComponent));
    else
    	bindings.push(bind(GreetingComponent).toClass(GenericGreetingComponent));

    @Component({
    	selector: 'app'
    })
    @View({
    	directives: [GreetingComponent]
    	template: `<h1>Welcome to my app!</h1>
    				<greeting></greeting>`

    })
    class AppComponent { }

    bootstrap(AppComponent, bindings);

Here I have an obviously great app and everyone loves it but Bob up in accounting absolutely has to have his name on everything.  If the directives defined in the View decorator's directives property were resolved from the parent injector this would be easy peasy and I wouldn't have clutter my main template with conditionals.

This should also extend to the router:

    @RouteConfig([
        { path: "/greeting", component: GreetingComponent, as: "greeting" }
    ]);

The component property of the RouteConfig elements should attempt to resolve from the parent injector as well.

How does this look?  In the spirit of dependency injection I think components and directives should get the same love as services.  What do you guys think?

**Comment by DannyMeister** [comment]
Agreed.  So far I haven't been getting any traction on getting injectable component support within the framework.  I'd want it to be taken a little further as well, as the projects I'm working on can't really be done with a static DI binding like you show in your example.  Right now I've gotten around it by creating my own DynamicComponentLoader-based solution.

**Comment by StacyGay** [comment]
@DannyMeister do you have a public example of this DynamicComponentLoader I could peek at?  I've been meaning to get at a workaround but haven't found the time yet.

**Comment by mhevery** [comment]
I am sorry, this is not something we will support. This is how things worked in AngularDart v1.0 and it created many issues. Namely that it was not possible to analyze the templates locally. You could get to situations where depending who is above you different directives are active on the same template, and this is something which negatively impacts speed.

**Comment by StacyGay** [comment]
@mhevery A solution for this would be not to resolve a created instance from the injector, but to instead just pull the binding containing the type from the injector.  In this way it could pass though  and be processed by the Compiler._bindDirective() method in the same way that a type or binding does now.  The only side affect in this case is that you couldn't have a directive as a singleton.
