### ISSUE TITLE
ng-class and class bugs

### ISSUE THREAD

**Issue by ruwhan** [angular/angular#4276]
This issue is related with _jqplot_,

Following code will make the jqplot appear
```
ng-class="{'success collapse row-details': build.state == 'Complete' || build.state == 'Accepted', 'info collapse row-details': build.state == 'Running', 'danger collapse row-details': build.state == 'Rejected'}"
```

But **not** with this code:
```
ng-class="{'success': build.state == 'Complete' || build.state == 'Accepted', 'info ': build.state == 'Running', 'danger': build.state == 'Rejected'}" class="collapse row-details"
```

As additional note, another element appear normally, just the _jqplot_ chart missing.

It is seems this is an Angular bug.

EDIT: I'm using Angular 1.3.0

**Comment by PascalPrecht** [comment]
@ruwhan this is the Angular 2 repository. Please submit your issue at http://github.com/angular/angular.js/issues and close this one, thanks!
