### ISSUE TITLE
AIO docs: TOC not behing over-sidenav backdrop

### ISSUE THREAD

**Issue by dario-piotrowicz** [angular/angular#42778]
# Docs or angular.io Bug Report

### Description
On narrow window widths when we the over sidenav appearts the table of contents on the right is still interactable and not behind the backdrop (opposite to the content)

### What's the affected URL?**
https://angular.io/guide/what-is-angular and any docs page with a toc

### Expected vs Actual Behavior**
I think that the toc should be behind the backdrop as the content is and should not be interactable

## Screenshot
![Peek 2021-07-05 21-27](https://user-images.githubusercontent.com/61631103/124517242-64951400-dddb-11eb-81f6-98379b710dc5.gif)

### Browser info
Chomium Version 91.0.4472.114 (Official Build) snap (64-bit)

**Comment by dario-piotrowicz** [comment]
Not sure if this is ok this way, to me it looks quite weird, the toc also allows you to navigate to sections which you cannot actually  read because they are behind the sidenav and its backdrop.

(to me it also looks off aesthetically, as I would expect everything except the header, and the sidenav to fall behind the backdrop)

**Comment by gkalpak** [comment]
Good catch :+1:

Here is my attempt at fixing it: #42787
It would be great if you could take a look and see if I have missed something.

**Comment by dario-piotrowicz** [comment]
Yeah of course it looks perfect now! :slightly_smiling_face: :heart_eyes: 

( but you stole my thunder! after confirming that this was not the desired behaviour I wanted to fix it :stuck_out_tongue_closed_eyes: :see_no_evil:  )

**Comment by gkalpak** [comment]
> but you stole my thunder!

Guilty as charged 😇
(To my defense, I thought I was doing you a favor 😛)
