### ISSUE TITLE
Missing step in the getting-started documentation

### ISSUE THREAD

**Issue by aniacm** [angular/angular#42771]
There is a missing step in the page of [Managing Data](https://angular.io/start/start-data). When defining "items", the "Product" interface is not imported so there will be an error. 
`import { Product } from './products';` should be inserted at the top.
![image](https://user-images.githubusercontent.com/24854507/124433885-d05c8a00-dda5-11eb-8e30-8779483b7d84.png)

**Comment by Nabeelhassan** [comment]
What would be the correct place to define the import step ?

**Comment by aniacm** [comment]
> What would be the correct place to define the import step ?

Between the "Define a cart service" step 1 and step 2, you can add another step to import the Product. Or you can also import it in the step 1. Hope it helps. :)

**Comment by Nabeelhassan** [comment]
I have made a pull request, lets see.

**Comment by Nabeelhassan** [comment]
This issue was fix in https://github.com/angular/angular/pull/42701. 
It can be closed now.
