### ISSUE TITLE
Add fakeAsync to the bundle

### ISSUE THREAD

**Issue by wardbell** [angular/angular#4277]
I see that Igor started exporting fakeAsync on Sept 3rd  in commit 687e7b.  And alpha37 was released on Sept 9th. Is it possible that a Sept 9th release missed a Sept 3rd commit?

All I can say for sure is that fakeAsync is not in the bundle. It does not turn up in a text search of  `angular2.dev.js` or `test_lib.dev.js` of the alpha37 bundles.

P.S. There is a lot of work to be done to make this developer friendly.

**Comment by juliemr** [comment]
This is done after the test library renaming changes.
