### ISSUE TITLE
Service worker registration failed in Safari

### ISSUE THREAD

**Issue by tekayaslim** [angular/angular#42775]
# Bug Report

### Affected Package

 The issue is caused by package 
<pre><code>"@angular/service-worker": "9.1.12"</code></pre>

### Is this a regression?

 Yes, the previous version in which this bug was not present was: angular 7 and iOS 13.

### Description

When I tried running the PWA application with no internet connection, on the Android devices the app ran just fine offline. 
However, on an iPad or iPhone running iOS 14.6, I got the message "Safari cannot open the page because your iPad is not connected to the Internet.

When I tested the application on iPad with internet connection:
The browser does not download the service worker script and ngsw.json manifest file.
I checked the Angular service worker is enabled using SwUpdate.isEnabled.

## Exception or Error
<pre><code>

"Safari cannot open the page because your iPhone is not connected to the internet"
</code></pre>

## Your Environment
**Safari Version: 14.6**

**Angular Version:**
<pre>
Angular CLI: 9.1.12
Angular: 9.1.12
... animations, cli, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.15
@angular-devkit/build-optimizer   0.901.15
@angular-devkit/build-webpack     0.901.15
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/common                   9.1.13
@angular/localize                 9.1.13
@ngtools/webpack                  9.1.15
@schematics/angular               9.1.12
@schematics/update                0.901.12
@angular/service-worker           9.1.12
rxjs                              6.6.2
typescript                        3.8.3
webpack                           4.42.0
<code>

</code></pre>

**Comment by gkalpak** [comment]
This sounds like an issue specific to your app. Angular.io (which also uses the `@angular/service-worker`) seems to have its ServiceWorker registered fine on iOS. I suggest trying to debug this on your app and find out at which point the registration workflow breaks on iOS for you and see if you get any errors in the browser DevTools console.

I am going to close this, since there is no indication this is an issue with Angular, but feel free to continue the discussion below.
