### ISSUE TITLE
KeyValueDiffers forEachRemovedItem proposes wrong removed element

### ISSUE THREAD

**Issue by FritzHerbers** [angular/angular#42786]
# Bug Report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?

 Do not know, using it for the first time.

### Description
The forEachRemovedItem within the KeyValueDiffers proposes a wrong item removed, it always proposes the last item added.

## Minimal Reproduction

I used the example from https://www.concretepage.com/angular/angular-ngdocheck and created the following StackBlitz: 

https://stackblitz.com/edit/angular-ivy-gbew2x?file=src%2Fapp%2Femployee-kvdiff.component.ts

- Press the "remove" button next to 100/Mahesh
- The KeyValueDiffers log message is "Removed Shiva" (correct is the IterableDiffers log message "Removed Mahesh").

Why does forEachRemovedItem propose a wrong removed element?

## Your Environment

Angular Version: 12.1.1

Asked also on SO:
https://stackoverflow.com/questions/68275033/keyvaluediffers-foreachremoveditem-proposes-wrong-removed-element

**Comment by JoostK** [comment]
This is working as expected. `KeyValueDiffers` can be used to determine difference in key-value pairs, where the key is used as identity. In the example, an array is passed into the differ. An array has numeric keys, and removing an item from an array shifts all subsequent items to one position earlier. This is how the last item appears to be removed as far as the key-value differ is concerned.

For arrays, using an iterable differ is typically more appropriate. In that case, you can create the differ using a "track by function" which determines the identity of an item in the array.

The `IterableDiffers` warns for the fact that the reported changes may not be the actual changes:

https://github.com/angular/angular/blob/c9b47f21822343286d056fd70aec882acc0ae788/packages/core/src/change_detection/differs/iterable_differs.ts#L57-L59
