### ISSUE TITLE
Test debug instructions unclear

### ISSUE THREAD

**Issue by ajsaraujo** [angular/angular#42781]
# Docs or angular.io Bug Report

### Description

In the documentation's [Debugging Tests](https://angular.io/guide/test-debugging) section, we're told to look for the `1st.spec.ts` file. Looking at it's name, one might think it is an specific file generated by Jasmine or something, when it actually is a regular spec file. It took me a while to figure this out 🤪 

Hence, I suggest editing the 5th step to something along these lines:
```diff
- 5. Open the `1st.spec.ts` test file (Control/Command-P, then start typing the name of the file).
+ 5. Open your test file. To find it, press Control/Command-P and start typing it's name.
```

### What's the affected URL?**
https://angular.io/guide/test-debugging

**Comment by Pashozator** [comment]
@ajsaraujo it could be a good change but how these screenshots are related to issue?

**Comment by ajsaraujo** [comment]
Oh boy. I pasted the wrong screenshot. Just edited it, thanks for the input.
