### ISSUE TITLE
Cant get the page for property binding on angular.io

### ISSUE THREAD

**Issue by Sevil-Ince** [angular/angular#42782]
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/67275429/124648158-2fe69280-de97-11eb-81a4-561e07efebd4.png">

# Docs or angular.io Bug Report

### Description

I wanted to look at something in de Documentation, so then this exception was logged in the console.
### What's the affected URL?**
 https://angular.io/...

## Exception or Error
<pre><code>

</code></pre>

## Your Environment
Macbook
### Browser info

Chrome

**Comment by gkalpak** [comment]
Thx for reporting this, @Sevil-Ince. Unfortunately, there is not much we can do with a partial image of the logs 😅
If this happens again, please post the full logs from the console (in plain text) :pray:
