### ISSUE TITLE
registration.getNotifications(), service worker, pwa

### ISSUE THREAD

**Issue by marijadstankovic** [angular/angular#42795]
# Feature Request

### Relevant Package

 This feature request is for @angular/service-worker

### Description
I would like to be able to clear all notifications when user sees one. Something like described [here](https://stackoverflow.com/questions/49488408/remove-a-web-push-notification). I think registration.getNotifications() would help but I don't know how to access it in Angular. I'm not sure if this is a bug or a new feature .

**Comment by gkalpak** [comment]
This is independent of the ServiceWorker implementation. You should be able to get the active notifications as usual:

```ts
const reg = await navigator.serviceWorker.getRegistration();
const notifs = await reg.getNotifications();
notifs.forEach(n => n.close());
```

**Comment by marijadstankovic** [comment]
oo thank you! And sorry for troubling you
