### ISSUE TITLE
Angular 12.1.0 big rebuild time

### ISSUE THREAD

**Issue by artaommahe** [angular/angular#42799]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

It was much faster for rebuilds with ng11.1.2 + NG_BUILD_IVY_LEGACY=1 (see the table below).

### Description

Rebuild time for AppComponent changes (adding console.logs) increase drastically with the amount of code.

We have relatively big application. Here are some measures for starting server and rebuilding on changes in AppComponent for different cases.

|                               | server | AppComponent |
| ----------------------------- | ------ | ------------ |
| default                       | 180s    | 65s          |
| default, --aot=false            | 105s   | 3.5s         |
| 12 of 24 lazy routes disabled | 125s   | 45s         |
| 18 of 24 lazy routes disabled | 100s   | 8.5s         |
| all lazy routes disabled      | 52s    | 2.2s          |
| ng11 default | 350s   | 14s         |

(ng11 - 11.1.2 version with NG_BUILD_IVY_LEGACY=1)  
(all changes are adding console.log() statements to AppComponent, median of 3-4 passes excluding first on)

## 🔬 Minimal Reproduction

Don't have a public reproduction. Attaching rebuild performance profiling for `18 of 24 lazy routes disabled` case.

CPU-20210707T141946.cpuprofile
https://drive.google.com/file/d/1LQzweIGTErNLmjcLhDjnGOSWiVbol-gR/view?usp=sharing

![image](https://user-images.githubusercontent.com/1944061/124751835-c2d30b80-df2f-11eb-9712-224f215f5325.png)

Cant profile the `default` case with all routes enabled - chrome crashes trying to dump all this stuff :(

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.1.0
Node: 12.18.1
Package Manager: yarn 2.4.2
OS: win32 x64

Angular: 12.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, platform-server, router
... youtube-player

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.0
@angular-devkit/build-angular   12.1.0
@angular-devkit/core            12.1.0
@angular-devkit/schematics      12.1.0
@angular/flex-layout            12.0.0-beta.34
@ngtools/webpack                12.1.0
@nguniversal/builders           12.1.0
@nguniversal/express-engine     10.1.0
@schematics/angular             12.1.0
rxjs                            6.6.7
typescript                      4.3.4
webpack                         5.40.0
</code></pre>

**Anything else relevant?**

This issue affects several of our projects relatively same size.  Most of our code is inside `libs/` subfolders and is imported directly by sources (nrwl/nx like monorepo).

Can debug something else, share screen or provide TeamViewer access to our codebase to check anything (discord drow#4335)

**Comment by JoostK** [comment]
I think I have an idea for where the remaining time comes from. The template type checker may need to add type-checking code to user code, if the same effect cannot be achieved from within the type-check file (e.g. when a directive has an internal generic type, it cannot generate the type constructor external to the directive). If this adds imports to the file, the program structure cannot be reused and also incremental type-checking is not as effective, as imports affect the computed shape. This incurs significant costs on program creation and type-checking time.

**Comment by vugar005** [comment]
Seems this blog by @brandonroberts  fix this issue https://dev.to/brandontroberts/speeding-up-the-development-serve-after-upgrading-to-angular-v12-5db5

**Comment by artaommahe** [comment]
Is not related to our issues. Already have these config after regular ng migration command

**Comment by JoostK** [comment]
I have been doing some experiments with the repo I typically use for perf issues, but this does not reproduce for me. I have forced the usage of inline type constructors but then #42759 is sufficient to mitigate the performance issues (that PR will be in this week's release).

I'm afraid that without a reproduction we can run locally this isn't actionable at the moment.

**Comment by pichuser** [comment]
@artaommahe do you find any solution? hugely slow

**Comment by artaommahe** [comment]
@pichuser nope, dunno what to debug. Still 16s to rebuild main.ts for a big project

**Comment by vugar005** [comment]
Hi @artaommahe  can you check the fix in the last comment of [#20792](https://github.com/angular/angular-cli/issues/2079). CC: @JoostK, @alan-agius4

**Comment by artaommahe** [comment]
@vugar005 
- already using regular angular builder for that project
- cant just remove yarn.lock and update all packages in our monorepo and i don't think i would help in any way
- re-checked all migrations adjustments to angular.json and it looks fine (under the spoiler)

<details>

  ```
  "student-cabinet": {
    "projectType": "application",
    "schematics": {},
    "root": "packages/student-cabinet",
    "sourceRoot": "packages/student-cabinet/src",
    "prefix": "app",
    "architect": {
      "build": {
        "builder": "@angular-devkit/build-angular:browser",
        "options": {
          "outputPath": "packages/student-cabinet/dist",
          "index": "packages/student-cabinet/src/index.html",
          "main": "packages/student-cabinet/src/main.ts",
          "polyfills": "packages/student-cabinet/src/polyfills.ts",
          "tsConfig": "packages/student-cabinet/tsconfig.app.json",
          "assets": [
            "packages/student-cabinet/src/favicon.ico",
            "packages/student-cabinet/src/robots.txt",
            "packages/student-cabinet/src/assets",
            {
              "glob": "**/*",
              "input": "libs/shared/ui-kit-v2/assets/stratos-skyeng-font",
              "output": "./assets"
            },
            {
              "glob": "apple-developer-merchantid-domain-association.txt",
              "input": "packages/student-cabinet/src/",
              "output": "/.well-known"
            }
          ],
          "styles": ["packages/student-cabinet/src/assets/styles/studcab-styles.scss"],
          "scripts": [
            {
              "input": "packages/student-cabinet/src/assets/js/glider.min.js",
              "bundleName": "glider-bundle"
            }
          ],
          "stylePreprocessorOptions": {
            "includePaths": ["packages/student-cabinet/src/assets/styles/", "libs/"]
          },
          "allowedCommonJsDependencies": [
            "zone.js",
            "lodash",
            "js-cookie",
            "ua-parser-js",
            "ios-version",
            "util",
            "hammerjs",
            "vimbox-player",
            "react",
            "react-dom",
            "uuid",
            "date-fns-timezone"
          ]
        },
        "configurations": {
          "production": {
            "fileReplacements": [
              {
                "replace": "packages/student-cabinet/src/environments/environment.ts",
                "with": "packages/student-cabinet/src/environments/environment.prod.ts"
              }
            ],
            "outputHashing": "all",
            "vendorChunk": true,
            "budgets": [
              {
                "type": "initial",
                "maximumWarning": "2.6mb",
                "maximumError": "5mb"
              },
              {
                "type": "anyComponentStyle",
                "maximumWarning": "30kb",
                "maximumError": "45kb"
              }
            ]
          },
          "development": {
            "buildOptimizer": false,
            "optimization": false,
            "vendorChunk": true,
            "extractLicenses": false,
            "sourceMap": false,
            "namedChunks": true
          }
        },
        "defaultConfiguration": "production"
      },
      "serve": {
        "builder": "@angular-builders/custom-webpack:dev-server",
        "options": {
          "browserTarget": "student-cabinet:build",
          "port": 443,
          "ssl": true,
          "disableHostCheck": true
        },
        "configurations": {
          "production": {
            "browserTarget": "student-cabinet:build:production"
          },
          "development": {
            "browserTarget": "student-cabinet:build:development"
          }
        },
        "defaultConfiguration": "development"
      },
      "test": {
        "builder": "@nrwl/jest:jest",
        "options": {
          "jestConfig": "packages/student-cabinet/jest.config.js",
          "passWithNoTests": true
        },
        "outputs": ["coverage/packages/student-cabinet"]
      },
      "lint": {
        "builder": "@nrwl/linter:eslint",
        "options": {
          "lintFilePatterns": [
            "packages/student-cabinet/**/*.ts",
            "packages/student-cabinet/**/*.html",
            "packages/student-cabinet/**/translation/*.json"
          ]
        }
      }
    }
  },
  ```
</details>

**Comment by alan-agius4** [comment]
@artaommahe, I noticed that you are using `@angular-builders/custom-webpack:dev-server` for your serve command. Can you check it the problem persists if you use the official builder `@angular-devkit/build-angular:dev-server`?

**Comment by artaommahe** [comment]
> Removing "emitDecoratorMetadata": true from tsconfig.json reduced our build time significantly for production.

and

> Deleted node_modules and package_lock.json
> Ran npm install

haven't helped at all. Same ~16s for second+ rebuild of main.ts file

> I noticed that you are using @angular-builders/custom-webpack:dev-server for your serve command.

🤦‍♂️ forgot to replace... Fixed it - nothing changed :(

ng 12.1.3

Just tried ng 12.2.1 - same 16s 😕

**Comment by artaommahe** [comment]
> even shared privately it will not be possible to get to the bottom of this.

as i said in first post - i can debug anything or provide teamviewer access. Discord tag also there.

**Comment by alxhub** [comment]
Closing as obsolete - please feel free to reopen if you're still experiencing pathological slowness with v13.2+
