### ISSUE TITLE
Protractor wait integration: implement whenStable for Testability API

### ISSUE THREAD

**Issue by tbosch** [angular/angular#428]
Issue: Angular 2 should provide a way to tell when the list of pending tasks for a turn is 0.

First step:

Inject a JS script after calling the main method in JS / including the main script in Dart that allows protractor to call this in the browser (see https://github.com/angular/protractor/blob/master/lib/clientsidescripts.js#L37)
```
angular.getTestability(el).whenStable(callback);
```

**Comment by naomiblack** [comment]
this is blocking for internal issue b/21869186

**Comment by jbdeboer** [comment]
Some feature requests:

This API should be a standard Future/Promise, which will allow us to use ```await``` in Dart.

The function should return a status code indicating how much work was done during the "whenStable".  One use of this feature is to assert that some work was done during all "whenStable" calls. This will prevent test developers from adding unnecessary "whenStable"s to their tests.

**Comment by yjbanov** [comment]
Pushing to alpha-29. Didn't make it to alpha-28

**Comment by IgorMinar** [comment]
I've had a brief discussion about this after with @yjbanov after coming across this issue when working on the router.

It seems that @yjbanov as well as the internal bug report is referring to a different but related issue than the one referred to in the original post.

The original issue is to expose something similar to testabilityApi's whenStable callback in Angular JS 1. This is needed for proper protractor integration. We are primarily interested in waiting for the system to finish all the async tasks that were spawned from within Angular's change detection zone. (things like animations and tasks that don't require change detection can be omitted)

@yjbanov and the internal bug is about having a way to do similar from unit tests and they do want to include task that are not relevant for change detection (like animations).

**Comment by juliemr** [comment]
cc @hankduan

**Comment by IgorMinar** [comment]
this should be implemented using the result of #2808

**Comment by hankduan** [comment]
closed via https://github.com/angular/angular/commit/a8b75c3d419622928402f7eae7329aa8f5f2c399
