### ISSUE TITLE
ng-change inside directive not work

### ISSUE THREAD

**Issue by ckrad** [angular/angular#4280]
```javascript
angular.module('app').directive('categoryselect', function() {
...
scope: {},
template: '<select ng-change="change()">...</select>',
link: function($scope, element, attrs) {
    $scope.change = function() {
        console.log('work');
    }
}
})
```

it will not work.

**Comment by mgechev** [comment]
This repository is for Angular 2 only. You can post AngularJS 1.x related issues [here](https://github.com/angular/angular.js/issues).

**Comment by pkozlowski-opensource** [comment]
@mgechev is right. On top of this it sounds like a general support question that should be asked using a dedicated support channel: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
