### ISSUE TITLE
sourcemap not work in chrome

### ISSUE THREAD

**Issue by Litor** [angular/angular#4281]
i run 'gulp serve.js.dev' in cmd and is worked in chrome,  but in chrome debug tools i see only .js file is loaded, the .js.map is not loaded. in server dist folder .js.map is existed in the same directory.

the end of .js file like this:
exports.AnimateApp = AnimateApp;
//# sourceMappingURL=animate-app.js.map
}).apply(__cjsWrapper.exports, __cjsWrapper.args);

**Comment by mhevery** [comment]
known issue. Closing as dup

**Comment by jesperronn** [comment]
Sorry to bring this up: What's this a dup of? (i found this issue via google, and want to see if there is a workaround I can use for my own project)

@Litor @mhevery, can you help me with a link to the dup? THanks!
