### ISSUE TITLE
Fix Creating observables demo code

### ISSUE THREAD

**Issue by xianshenglu** [angular/angular#42822]
### Description

for `Create with custom fromEvent function` demo code, `observer` in `fromEvent` `Observable` missing `unsubscribe` method

### What is the affected URL?

https://angular.io/guide/observables#creating-observables

**Comment by JoostK** [comment]
I believe the example is correct; [the subscribe callback for `Observable`'s constructor](https://rxjs.dev/api/index/class/Observable#constructor()) can return [`TeardownLogic`](https://rxjs.dev/api/index/type-alias/TeardownLogic), which can be an `Unsubscribable` as used in the first example or a closure function as used in the second sample.

Still, I agree this can be improved in the docs.
