### ISSUE TITLE
Angular Router roadmap?

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [angular/angular#42825]
### Which @angular/* package(s) are relevant/releated to the feature request?

router

### Description

Is there any kind of roadmap available for Angular Router? Are there any changes/improvements planned for it in the near future? 

I find Angular Router to be *extremely* unwieldy and hard to work with, especially when pitched against the fantastic UI Router. For now, I can still use that router as an alternative, but there's only so much time developers of that project can devote to it and ultimately, the "default" solution, should be the best one possible, not to mention that other solutions (Ionic, SSR) rely on default router only. 

As it is now, Angular is in a very similar situation, that Angular JS was many years before - its router was abysmal, so UI Router was created. Alas, that work hasn't been incorporated into Angular Router, for the reasons that remain unclear to me.

It's 2021 and in Angular Router...

- events don't carry enough information at certain stages 
- it's sometimes hard to extract the simplest of information (i.e. current full url)
- activation logic is applied per route, no way to apply in general
- there are no named routes (the mindset still revolves around urls...)
- parameters are resolved only as strings, no way to use types, even basic ones, like booleans or numbers

### Proposed solution

Well, ideally replace it with UI Router altogether, but one can dream...

### Alternatives considered

Live with it as it is for now and hope for the better.

**Comment by zeljkoantich** [comment]
> Well, ideally replace it with UI Router altogether, but one can dream...
At first it seemed this was a joke.

I find Angular Router to be extremely manageable and easy to work with, on the other side I find UI Router unmanageable and very hard to comprehend.

@sebastian-zarzycki-es Sorry that you have difficulties using Angular Router.

I'm aware that UI Router is not maintained regularly and that it has unclosed issues which are older then 2 years. 
My feeling is that UI Router should change if it want's to stay alive as a project.

**Comment by sebastian-zarzycki-es** [comment]
A lot of people are also using similar argument against Angular in general, but I have an inkling that we actually disagree on what that usually foreshadows.

**Comment by atscott** [comment]
There's no public roadmap for the router specifically or any other individual packages within Angular. As projects are prioritized by the team, they will show up in the overall Angular roadmap here: https://angular.io/guide/roadmap.

That said, the Router and Forms packages are certainly ones that we are intending to take a closer look at soon, as we're aware of the many current pains developers have with the state they're currently in.

Specific points that you've noted in the bullets of the report would be best served as issue/feature requests so they can get increased visibility, upvoted, and prioritized individually. We do keep an eye on the reactions on issues to inform our decisions for prioritization.

**Comment by sebastian-zarzycki-es** [comment]
Thank you. I'll try to come up with a more detailed list of issues / feature requests in the near future.
