### ISSUE TITLE
rebind expressions by filter

### ISSUE THREAD

**Issue by leibale** [angular/angular#4283]
my filter has config that my change at any time,
i need listen to `config.change` and rebind all the expressions using this filter (and only them, i don't want to set the `$stateful` on the filter to `true` and run `$rootScope.$apply();` when i need to rebind).

**Comment by mgechev** [comment]
This repository is for Angular 2 only. You can post AngularJS 1.x related issues [here](https://github.com/angular/angular.js/issues).
