### ISSUE TITLE
All `PROP_METADATA` of component gets lost if `@Input` or `@Output` of parent component is overwritten

### ISSUE THREAD

**Issue by stefan-schweiger** [angular/angular#42847]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No (not as far as I know)

### Description

When you try to get the `PROP_METADATA` of a component which overwrites for example a `@Input` property of it's parent you loose all metadata information of the parent. If you don't overwrite a decorated property it works without a problem.

I'm guessing this problem potentially does occur in every library which depends on `PROP_METADATA` but I've encountered it in storybook.
Storybook relies on the metadata to create it's `StorybookWrapperComponent` this can lead to random errors because storybook can't correctly reflect the input/output properties. In my case this lead to storybook overwriting an `@Output` because without the metadata it looks like a normal property and then "crashing".

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-vyzzgx?file=src%2Fapp%2Fapp.component.ts

### Please provide the exception or error you saw

```true
Prop Metadata of component which overwrites input props
{otherInputProperty: Array[1]}

Prop Metadata of component which doesn't overwrites input props
{otherInputProperty: Array[1], value: Array[1]}
```

### Please provide the environment you discovered this bug in

```true
Angular 12.1.1
(reproducable in stackblitz example)
```

### Anything else?

![image](https://user-images.githubusercontent.com/3532342/125621490-f4d81436-08d0-4a4c-952b-f756cc3b821c.png)

**Comment by JoostK** [comment]
AFAIK this is internal metadata stored on the class for the JIT compiler to use, in combination with `ReflectionCapabilities`.

You'll notice that `ReflectionCapabilities` only considers own properties (not properties on the prototype) :

https://github.com/angular/angular/blob/cd2d82a91a5f547ae4c3d369f7f777245324c9e5/packages/core/src/reflection/reflection_capabilities.ts#L218-L245

And `propMetadata` explicitly merges multiple inheritance levels:

https://github.com/angular/angular/blob/cd2d82a91a5f547ae4c3d369f7f777245324c9e5/packages/core/src/reflection/reflection_capabilities.ts#L247-L271

So this appears to be working as expected.

**Comment by stefan-schweiger** [comment]
@JoostK as you can see in the stackblitz repro as long as you don't overwrite any `@Input`/`@Output` properties the metadata contain all `@Input`/`@Output` properties of the parent. As soon as you overwrite an arbitrary property all metadata of the parent is gone. I don't see how this is working as expected.

Either the child should have ALL or NONE of the metadata of the parent. But it only inheriting the metadata depending on having a single overwritten property seems wrong.

**Comment by JoostK** [comment]
You're seeing the effect of property inheritance. The _own_ property only contains the own metadata, but a read using element access syntax (`[PROP_METADATA]`) traverses the prototype chain to also read the properties from the base class. A class without decorators does not set `PROP_METADATA` on the class, so reading `PROP_METADATA` will actually end up reading the `PROP_METADATA` of the base class.

You can use `TestComponent.hasOwnProperty(PROP_METADATA)` to detect if you're dealing with own metadata or inherited metadata and act accordingly. Please do note though that `__prop_metadata__` is still internal data that is stored on the class, so use with caution.
