### ISSUE TITLE
href="#" navigates to the application home

### ISSUE THREAD

**Issue by dmccormack3** [angular/angular#42849]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

This has been raised previously here: https://github.com/angular/angular/issues/7294

Clicking on a link with href=# will navigate to the application homepage. 

`<a href="#">Navigates to home </a>`

There are workarounds such as replacing the href with javascript:void(0);. However this assumes the href code belongs to the angular application. I have encountered the problem when using a Web Component built with React. The webcomponent works as expected when used in other Frameworks, but when in Angular the href='#' link is navigating the user from the current page. 

Can this functionality be disabled? 

### Please provide the exception or error you saw

```true
I would expect href="#" not to navigate users from the current page.
```

**Comment by atscott** [comment]
This is actually the behavior of the browser when using the `<base>` element. See [in-page anchors](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base#in-page_anchors) in the MDN web docs.

If this is undesirable behavior for your application, you can use [APP_BASE_HREF](https://angular.io/api/common/APP_BASE_HREF) instead.
