### ISSUE TITLE
ts-api-guardian requires TypeScript v3 as peer dependency

### ISSUE THREAD

**Issue by SchnWalter** [angular/angular#42843]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

The `ts-api-guardian` package uses `typescript@4.3.4` as a dependency during development, but the last release (`0.6.0`) still requires `typescript@~3.9.2` as a peer dependency when it's installed in another project, making it imposible to use in existing Angular v12 workspaces

### Please provide the exception or error you saw

```true
> npm show ts-api-guardian peerDependencies
{ typescript: '~3.9.2' }
```

### Anything else?

To keep backwards compatibility it should accept both TS v3 and v4, or it should use TypeScript as a direct dependency on v3.

**Comment by JoostK** [comment]
FYI `ts-api-guardian` is likely going away, per #42735.

**Comment by SchnWalter** [comment]
So, we can probably close this as "won't fix", since [@microsoft/api-extractor](https://www.npmjs.com/package/@microsoft/api-extractor) seems to be the way to go and `ts-api-guardian` has like 2k weekly downloads.

Thanks.
