### ISSUE TITLE
listeners invoked inside embedded views cause a memory leak

### ISSUE THREAD

**Issue by s3141p** [angular/angular#42848]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

When a component has a button with click handler and ngIf it won't be destroyed after user click

### Please provide a link to a minimal reproduction of the bug

https://github.com/s3141p/Ng-leak

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.1.1
Node: 14.15.1
Package Manager: npm 6.14.8
OS: linux x64

Angular: 12.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            12.1.1
@angular-devkit/schematics      12.1.1
@schematics/angular             12.1.1
rxjs                            6.6.7
typescript                      4.2.4
```

### Anything else?

To  reproduce:
1. Clone the repo 
2. `ng serve`
3.  Click on `To B Component` link
4. Click on `B button` (!! Important step)
5. Make Memory snapshot 
6. Click on `To A Component`
7. Run GC
8. Make Memory snapshot

Last snapshot will show that `BComponent` wasn't destroyed.

**Comment by JoostK** [comment]
[Heap-20210714T145500.zip](https://github.com/angular/angular/files/6816170/Heap-20210714T145500.zip)

I can confirm that this is indeed happening, per the heapdump above.

**Comment by JoostK** [comment]
The retainer looks like this:

![image](https://user-images.githubusercontent.com/123679/125625967-b5726f83-424b-49a8-ba80-35f96030ddf0.png)

The event listener captures the `LView` for `BComponent` in Ivy's `instructionState.lFrame.contextLView`, which is apparently never cleared.

**Comment by petebacondarwin** [comment]
Thanks for the awesome reproduction @s3141p - this bit is 75% of the effort :-)

Looking at the generated Ivy code for the button click. Because it is in a template (due to the `*ngIf`) we get the following:

```ts
ɵɵlistener("click", function BComponent_button_2_Template_button_click_0_listener() {
  ɵɵrestoreView(_r2);
  const ctx_r1 = ɵɵnextContext();
  return ctx_r1.doNothing();
});
```

Both the call to `ɵɵrestoreView()` and `ɵɵnextContext()` attach objects to the current `LFrame.contextLView` property. The second call is the one responsible for attaching the `LComponentView_BComponent` object.

It seems like when the `BComponent` is destroyed we are not clearing this `contextLView` property.

One solution might be for the generated code to clear the current view at the end of the handler:

```ts
ɵɵlistener("click", function BComponent_button_2_Template_button_click_0_listener() {
  ɵɵrestoreView(_r2);
  const ctx_r1 = ɵɵnextContext();
  const result = ctx_r1.doNothing();
  ɵɵleaveView();
  return result;
});
```

**Comment by s3141p** [comment]
I'm looking forward to resolving this issue :)

For those who faced this problem replacing `*ngIf` with `[hidden]` might be a temporary solution

**Comment by JoostK** [comment]
@s3141p the leak would occur for _any_ embedded view though, so you'd also see this inside of `ngFor` for example.

**Comment by crisbeto** [comment]
I decided to give the proposal from @petebacondarwin a quick try, but it ended up breaking a bunch of event listener tests so we may need to do something more sophisticated. Here's the code for reference: https://github.com/angular/angular/commit/a11c156292f230e9d2dfa8be64a59c10e9e45c3f

**Comment by JoostK** [comment]
I think _leaveView_ is not the correct call; that pops an `LFrame` from the instruction stack whereas `restoreView` never pushed a frame, so the stack ends up being inconsistent. The `contextLView` that is set in `restoreView` is set on the currently active frame, which I think would typically be the root frame. Clearing `contextLView` on that frame should be sufficient to avoid the memory leak.

**Comment by CalinaCristian** [comment]
is this issue being solved soon? These leaks get very big if you're unit testing your application.
