### ISSUE TITLE
Angular/Elements: DOM not updated when using a *ngIf and async pipe

### ISSUE THREAD

**Issue by narendrapolasamn** [angular/angular#42855]
### Which @angular/* package(s) are the source of the bug?

elements

### Is this a regression?

No

### Description

i have  made a variation of this as an npm package: elements-zone-strategy

change app.module.ts:
import { ElementZoneStrategyFactory } from 'elements-zone-strategy';

const strategyFactory = new ElementZoneStrategyFactory(MyElementComponent, injector);
const element = createCustomElement(MyElementComponent, { injector, strategyFactory });

The above logic is not working any idea.

Thank you.

### Please provide the exception or error you saw

```true
angular element Dom is not rendering using *ngIf
```

**Comment by alxhub** [comment]
@narendrapolasamn without the actual code in question, there is no way we will be able to understand or investigate this bug. Please provide a link to a Stackblitz or a Github repository with clear instructions on how to demonstrate the problem.

**Comment by narendrapolasamn** [comment]
@alxhub 

I am creating angular elements web components. inside the web component html template i use ngIf directive. Unfortunately it is not working in the DOM.(please refer this link for more details https://github.com/angular/angular/issues/24577)

i used the below code even though it was not help me.

 app.module.ts:
import { ElementZoneStrategyFactory } from 'elements-zone-strategy';

const strategyFactory = new ElementZoneStrategyFactory(MyElementComponent, injector);
const element = createCustomElement(MyElementComponent, { injector, strategyFactory });

Thank you.

**Comment by dadigud** [comment]
@narendrapolasamn
![image](https://user-images.githubusercontent.com/16044275/126018307-8d4b8500-7eaa-46b0-8b96-9f9d6b99c936.png)

**Comment by narendrapolasamn** [comment]
@dadigud 

I install and used  elements-zone-strategy. unfortunately it is not working

**Comment by gkalpak** [comment]
I'm sorry but we can't reproduce the problem you are reporting. We require that reported issues have a minimal reproduction that showcases the problem.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template that include info on how to create a reproduction using our template.
