### ISSUE TITLE
This looks like it has the same underlying cause as #24181. There is a proposed fix here: #24185.

### ISSUE THREAD

**Issue by narendrapolasamn** [angular/angular#42853]
This looks like it has the same underlying cause as #24181. There is a proposed fix here: #24185.
To verify, as a workaround, you can install this: [elements-zone-strategy](https://www.npmjs.com/package/elements-zone-strategy) and change your appModule constructor to:

    import { ElementZoneStrategyFactory } from 'elements-zone-strategy';

    const strategyFactory = new ElementZoneStrategyFactory(ButtonComponent, this.injector);
    const customButton = createCustomElement(ButtonComponent, { injector, strategyFactory });

_Originally posted by @remackgeek in https://github.com/angular/angular/issues/24732#issuecomment-401870389_

**Comment by JoostK** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
