### ISSUE TITLE
@remackgeek  Try this solution:  described in this [article](https://github.com/angular/angular/issues/26158)

### ISSUE THREAD

**Issue by narendrapolasamn** [angular/angular#42854]
@remackgeek  Try this solution:  described in this [article](https://github.com/angular/angular/issues/26158)
It SOLVED my issues with *ngFor, and i had same issue as you are describing....

elements-zone-strategy:
This library provides an Angular Elements Strategy Factory which always runs in the NgZone, allowing automatic change detection

Solution fixed my issues is:
install the package:
`npm i --save elements-zone-strategy`

use the new strategy in "app.module.ts":
`import { ElementZoneStrategyFactory } from 'elements-zone-strategy';

const strategyFactory = new ElementZoneStrategyFactory(HelloComponent, this.injector);
const helloElement = createCustomElement(HelloComponent, { injector: this.injector, strategyFactory });
customElements.define('my-hello', helloElement)`

_Originally posted by @gonadn in https://github.com/angular/angular/issues/23841#issuecomment-450676660_

**Comment by JoostK** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by narendrapolasamn** [comment]
@remackgeek 

i was trying to use above solution unfortunately it is not working any idea bout this.

Thank you.

**Comment by remackgeek** [comment]
@narendrapolasamn,
Not sure I'm following what you're asking. But the basic change detection problem for elements was resolved in 10.1 with this pull request: [#37814](https://github.com/angular/angular/pull/37814)
