### ISSUE TITLE
Input type radio with FormBuilder

### ISSUE THREAD

**Issue by splintercode** [angular/angular#4285]
Radio inputs does not work with FormBuilder. Looks like radio buttons are not yet implemented?

https://github.com/angular/angular/tree/master/modules/angular2/src/core/forms/directives

**Comment by PascalPrecht** [comment]
I think you can use `ng-control` etc with input radios as well. What exactly is not implemented?

Note that Angular 2 doesn't need to "reimplement" all form input as a directive due to zones. As you can see, there's also no checkbox or input directive etc.

Anything you ran into that didn't work?

**Comment by splintercode** [comment]
Hmm ok let me go back and double check and try to make a plunker. I had issues using a radio list created with a form builder.  It was probably my mess up. Do you know of any examples?

**Comment by mhevery** [comment]
reopen once you have a plunker

**Comment by nidin** [comment]
Radio button example using custom RadioControlValueAccessor similar to CheckboxControlValueAccessor
https://github.com/angular2-school/angular2-radio-button

**Comment by PardeepJain** [comment]
Same Problem i had faced from few days back....unable to get the values of radio and checkboxes using FormBuilder. anyone out here having working code for getting value from radio and checkbox ?

**Comment by nidin** [comment]
@Pradeep Did you checkedout my plunker?

**Comment by PardeepJain** [comment]
sry and thanx its working. one thing more i am using ngControl but via this i am unable to get the value of readonly input field. why so do you have any idea ? it shows undefiend.

**Comment by GregWoods** [comment]
So, just to be clear... as the original question was "Looks like radio buttons are not yet implemented?"

In angular 1.x, I can add `ng-model` and `ng-value` to my radio button input markup, and I get full 2-way data binding with my model.
But in Angular 2, to get the same thing working, I need to write a custom RadioControlValueAccessor as in @nidin's plunker?

That seems to me to be a definition of something that is "not implemented".

I'm happy to be pointed in the direction of how this should be done (although the docs have no references to radio button that I can find)
I'm also happy for someone to admit that something is not implemented yet
But this has been closed with none of the above.

**Comment by zoechi** [comment]
I guess 5506 needs to be merged first

**Comment by GregWoods** [comment]
Thanks @zoechi that seems to be it

**Comment by smkamranqadri** [comment]
not able to find CONST_EXPR in ng2 rc1? which was import in RadioControlValueAccessor.

**Comment by zoechi** [comment]
@smkamranqadri no need for it anyway. This is only necessary for ts2dart for Dart code generation.

**Comment by nidin** [comment]
@smkamranqadri There are breaking changes in ng2 rc1.
I have already updated my github repo.
https://github.com/angular2-school/angular2-radio-button

**Comment by smkamranqadri** [comment]
@nidin yeah got your updated from from stackoverflow. well thanks.

**Comment by joeSaad** [comment]
it took me a while to find some form that uses angular2 formbuilder, valuechanges method and subscribing. Here's a plunker if someone still may need that. http://plnkr.co/edit/ioIH4NZnzCIJcvKqdOTI?p=preview
