### ISSUE TITLE
Forms: Unified Control State Change Events

### ISSUE THREAD

**Issue by dylhunn** [angular/angular#42862]
### Which @angular/* package(s) are relevant/releated to the feature request?

forms

### Description

The ability for `AbstractControl`-based classes (such as `FormControl`) to produce more events is a highly requested feature (lots of feedback in #10887, also #41088 and others; #24444 is also a use case). Adding more observables similar to the current `valueChanges` and `statusChanges` is the most straightforward way to extend `AbstractControl`, however, as the number of such observables increases (for example `pristine`, `dirty`, etc) it might become less ergonomic and more expensive to maintain.

### Proposed solution

We could introduce a new observable (and still support `valueChanges` and `statusChanges` for backwards compatibility) containing all events produced in various situations, so it's possible to subscribe, stream, and filter as needed. Each event in this stream might contain additional meta information such as a reference to an instance that produced the event, event type, etc. We would need a unified payload design that works with all the event types, and satisfies the use cases in the above linked issues.

However before making a final decision, we'd need to perform more research and design work, to make sure that this approach is viable.

Also note that adding this stream could simplify `ControlValueAccessor`, as per #24444 and #27315.

### Alternatives considered

Adding individual observables on a case-by-case basis is likely infeasible, both from an API consistency perspective and an API bloat perspective.

**Comment by AndrewKushnir** [comment]
FYI #31963 has some proposals on how event payload may look like.

**Comment by pauldraper** [comment]
It has now been well over a month since @dylhunn closed the working 40-line #32806 , saying "I will likely design and implement this in the next few weeks."

I am so excited to see what the Angular team has to offer.

**Comment by dylhunn** [comment]
We are consolidating this into #10887 as part of cleaning up our issue tracker.

@pauldraper We do recognize that it has taken a while, and we are sorry about that. I've been pulled onto g3 internal work, so I can't guarantee an ETA for this. However, we did discuss #32806, and we don't want to just merge as-is. There are a couple problems -- adding individual observables for all the states would result in quite a lot of them (that PR doesn't actually have all the needed states). And it wouldn't just affect this class; whatever we do really ought to be compatible with `ControlValueAccessor`s as well, for which state changes are currently a bit of a mess. So we think this "simple" approach will cost a lot more in code duplication and bundle size than it initially appears.
