### ISSUE TITLE
angular.io content overflow

### ISSUE THREAD

**Issue by swseverance** [angular/angular#42867]
### Description

Content is overflowing on this page: https://angular.io/cli/generate#application

### What is the affected URL?

https://angular.io/cli/generate#application

### Please provide the steps to reproduce the issue

Visit https://angular.io/cli/generate#application

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/18009315/125832521-28116137-adb2-4396-a5bf-109244f47652.png)

### Is this a browser specific issue? If so, please specify the device, browser, and version.

```true
I see this behavior in Chrome on MacOS and Windows
```

**Comment by gkalpak** [comment]
Thx for reporting this, @swseverance :+1:
I accidentally introduced it in #42787 😇
Should be fixed by #42884.
