### ISSUE TITLE
"Votes required" / "Under consideration" tweaks

### ISSUE THREAD

**Issue by flash-me** [angular/angular#42868]
Asking out of curiosity: Are the voters checked? Like their accounts?

Or can we just create 19+ additional accounts and vote for our own suggestion?

🤷‍♂️

cheers
flash ⚡

**Comment by petebacondarwin** [comment]
How could we even check them?

Note that this voting process is purely to give us some insight into how important a feature is to people in the community.
While this is taken into account, the final decision whether to implement a feature comes down to how it fits into our overall strategy and how it fits with other features; how complex it is for the benefit; how big a breaking change it might require; but also what capacity the team has.

**Comment by flash-me** [comment]
Not sure, I'm not that familiar with all the Github API's. 

But yes, the process surely makes sense and probably even necessary to handle all the issues. 
I see some potential gaps, since the voting process is timelined and e.g. if an issue was raised long before said process has been there, that they will be overlooked or not even recognized. 
On the other side, what would be the alternatives? Hm. It's kinda difficult.

cheers
flash ⚡

**Comment by petebacondarwin** [comment]
> Not sure, I'm not that familiar with all the Github API's.

What I meant by this is even if we can get hold of all the usernames of each voter. What would that tell us?
Even if we could get an email address for each one, we can't necessarily tell that they are a valid voter.
We could look at their github history, perhaps, but then who is to say that someone who only just joined github is not a valid user?

**Comment by flash-me** [comment]
Sure they are. I mean, one can use angular for a long time without even being in github. That's truly valid. 
...difficult.

I'm closing this to prevent attention about this.

cheers
flash ⚡

**Comment by petebacondarwin** [comment]
Thanks! And thank you for taking time to think about this stuff. It is important that we try our best to get it right.
