### ISSUE TITLE
(node:8756) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (Use `node --trace-deprecation ...` to show where the warning was created)

### ISSUE THREAD

**Issue by kia9372** [angular/angular#42873]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

i want to run angular universal on IIS windows 10 .

when i run the project on srver that show me this error : 

`(node:8756) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)`

and my application carashed . 

how can fix this bug ? 

i install new version of `"xhr2": "^0.2.1",`  in my project . and update all of my project . 

the @angular/platform-server are using the xhr2 0.2.0 . 

and this is my package.json

> `{
  "name": "main-gclanding",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "dev:ssr": "ng run MainGCLanding:serve-ssr",
    "serve:ssr": "node dist/MainGCLanding/server/main.js",
    "build:ssr": "ng build --configuration production && ng run MainGCLanding:server:production",
    "prerender": "ng run MainGCLanding:prerender"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.1.2",
    "@angular/common": "~12.1.2",
    "@angular/compiler": "~12.1.2",
    "@angular/core": "~12.1.2",
    "@angular/forms": "~12.1.2",
    "@angular/platform-browser": "~12.1.2",
    "@angular/platform-browser-dynamic": "~12.1.2",
    "@angular/platform-server": "^12.1.2",
    "@angular/router": "~12.1.2",
    "@nguniversal/express-engine": "^12.1.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "contentful": "^8.4.2",
    "domino": "^2.1.6",
    "express": "^4.15.2",
    "ngx-captcha": "^9.0.1",
    "rxjs": "~6.6.0",
    "sitemap": "^7.0.0",
    "tslib": "^2.0.0",
    "xhr2": "^0.2.1",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.1.2",
    "@angular/cli": "~12.1.2",
    "@angular/compiler-cli": "~12.1.2",
    "@nguniversal/builders": "^12.1.0",
    "@types/express": "^4.17.13",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.20.16",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.4",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.7.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "^4.3.5"
  }
}

`

**Comment by petebacondarwin** [comment]
It is not clear from your report which node.js package is using the outdated `Buffer` API.
The `xhr2` package was updated to use the new `Buffer` API for v0.2.0, (see https://github.com/pwnall/node-xhr2/commit/e6529e87b266b0ff5274b1ebcab36284ea58b61b) so this should not be causing the problem.

**Comment by kia9372** [comment]
@petebacondarwin 

This has confused me . i dont know whats the problem and i dont use any `new Buffer` in my code .

**Comment by petebacondarwin** [comment]
Can you try applying the `--trace-deprecation` flag to get more information about where the usage is?

**Comment by kia9372** [comment]
@petebacondarwin 

how can i use --trace-deprecation

**Comment by petebacondarwin** [comment]
How are you running the server side rendering of `@angular/platform-server`?

**Comment by kia9372** [comment]
@petebacondarwin 

i run this command `ng build --configuration production && ng run MainGCLanding:server:production`  and run the dist project in IIS

**Comment by petebacondarwin** [comment]
Then try:

```
node --trace-deprecation node_modules/.bin/ng build --configuration production
node --trace-deprecation node_modules/.bin/ng run MainGCLanding:server:production
```

**Comment by kia9372** [comment]
@petebacondarwin 

it show me this error : 

C:\Projects\gc-landing-ng\node_modules\.bin\ng:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by JoostK** [comment]
You'll need the following on Windows:

```
node --trace-deprecation .\node_modules\@angular\cli\bin\ng build --configuration production
node --trace-deprecation .\node_modules\@angular\cli\bin\ng run MainGCLanding:server:production
```

**Comment by kia9372** [comment]
i run thats command in the CMD and it show me this result : 

![image](https://user-images.githubusercontent.com/8811020/126125892-af132cab-3aee-4223-b930-d4a1d47f56ef.png)

**Comment by kia9372** [comment]
@JoostK 

ok . thanks . i try that . now it not show me anythings . that just how me success build .

**Comment by petebacondarwin** [comment]
There are two commands here. `build` and `run`.

Which one gives you the deprecation warning?

It is also possible that this will not help much since there will be no source-mapping to the `@angular/platform-server` package and its dependencies.

**Comment by kia9372** [comment]
@petebacondarwin 

every command show me success and not show me any warning  .

**Comment by petebacondarwin** [comment]
Then where is the original warning coming from?

**Comment by kia9372** [comment]
@petebacondarwin 

when i upload project in the server and using the IIS .

**Comment by petebacondarwin** [comment]
I'm afraid without further insight into the setup and processes running on the server there is not much more we can do to help here. Perhaps your server is using outdated packages? Perhaps your local environment is on an old version of node.js that is not showing the deprecation notices? You might want to try to SSH on to the server and try running the same commands above.

As far as I am aware, the latest versions of `@angular/platform-server` do not contain the usages described in the error above.

**Comment by kia9372** [comment]
i using the `IISNode V 0.2.26.0` . when i run the website with command `node main.js` it dose not show me any error or warning . but when i run that in the iis show me taht error

**Comment by petebacondarwin** [comment]
It looks like this is a bug with IISNode. See https://github.com/Azure/iisnode/issues/107

Closing as I don't believe this is an issue with Angular.
