### ISSUE TITLE
refactor(EventEmitter): rename "next" to "emit"

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#4287]
As `EventEmitter`'s ultimate fate is being decided in #4149, small steps should be taken to start de-coupling it from Rx, since it is an abstraction of Rx. One small step to disambiguate `EventEmitter` from Subject is to change the `next` method to `emit`.

Note that in #4149, there's more substantial discussion about how to properly leverage Observables inside the Angular codebase.

**Comment by IgorMinar** [comment]
moving this to a40 so that we avoid breaking changes in a39 due to g3 sync

**Comment by naomiblack** [comment]
pr #4604 should resolve this

**Comment by jeffbcross** [comment]
Moving this into 41, working on a simple solution to manually add the combinators we need to EventEmitter without changing anything about its inheritance.

**Comment by jeffbcross** [comment]
@robwormald are you planning to implement this?

**Comment by robwormald** [comment]
Yessir.

**Comment by IgorMinar** [comment]
@robwormald please deprecate the old api instead of outright removing it.

**Comment by robwormald** [comment]
Noted. I don't think I can remove it anyway - emit will just be an alias for .next().
