### ISSUE TITLE
export 'ɵRuntimeError' was not found in '@angular/core

### ISSUE THREAD

**Issue by agoussec** [angular/angular#42880]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

Getting this below issue -
      
![Screenshot from 2021-07-17 15-47-20](https://user-images.githubusercontent.com/16516713/126033825-c3b378ef-d377-4a11-8c08-51796830befc.png)

here is my angular package json 

        {
            "name": "angular-folder-structure",
            "version": "2.0.0",
            "license": "MIT",
            "scripts": {
              "ng": "ng",
              "start": "ng serve",
              "dev": "ng serve --aot",
              "build": "ng build",
              "test": "npm run lint && ng test --configuration=test",
              "lint": "ng lint",
              "e2e": "ng e2e",
              "watch": "ng test --configuration=test --browsers ChromeHeadless --watch",
              "build:prod": "ng build --prod --vendor-chunk",
              "clean": "rimraf ./dist/",
              "format:write": "prettier {src,e2e,cypress}/**/*.{ts,json,md,scss} --write",
              "format:test": "prettier {src,e2e,cypress}/**/*.{ts,json,md,scss} --list-different",
              "analyze": "npm run clean && npm run build:prod -- --stats-json && webpack-bundle-analyzer ./dist/stats.json",
              "compodoc": "compodoc -p src/tsconfig.app.json"
            },
            "husky": {
              "hooks": {
                "pre-commit": "npm run lint"
              }
            },
            "commitlint": {
              "extends": [
                "@commitlint/config-conventional"
              ]
            },
            "lint-staged": {
              "{src,e2e,cypress}/**/*.{ts,json,md,scss}": [
                "prettier --write",
                "git add"
              ]
            },
            "private": true,
            "dependencies": {
              "@angular/animations": "^11.2.0",
              "@angular/cdk": "^11.2.0",
              "@angular/common": "^11.2.0",
              "@angular/compiler": "^11.2.0",
              "@angular/core": "^11.2.0",
              "@angular/forms": "^11.2.0",
              "@angular/localize": "^11.2.0",
              "@angular/material": "^11.2.0",
              "@angular/platform-browser": "^11.2.0",
              "@angular/platform-browser-dynamic": "^11.2.0",
              "@angular/router": "^11.2.0",
              "@fortawesome/angular-fontawesome": "^0.6.0",
              "@fortawesome/fontawesome-free": "^5.12.1",
              "@fortawesome/fontawesome-svg-core": "^1.2.27",
              "@fortawesome/free-brands-svg-icons": "^5.12.1",
              "@fortawesome/free-solid-svg-icons": "^5.12.1",
              "@ng-bootstrap/ng-bootstrap": "6.1.0",
              "@testing-library/angular": "^10.3.2",
              "@testing-library/dom": "^5.6.1",
              "bootstrap": "^4.5.0",
              "browser-detect": "^0.2.28",
              "core-js": "^2.6.11",
              "masonry-layout": "^4.2.2",
              "ngx-masonry": "^11.0.0",
              "rxjs": "^6.5.5",
              "rxjs-compat": "^6.5.5",
              "tslib": "^2.0.0",
              "web-animations-js": "^2.3.2",
              "zone.js": "~0.10.3"
            },
            "devDependencies": {
              "@angular-devkit/build-angular": "~0.1102.0",
              "@angular-devkit/core": "^11.2.0",
              "@angular-eslint/builder": "1.2.0",
              "@angular-eslint/eslint-plugin": "1.2.0",
              "@angular-eslint/eslint-plugin-template": "1.2.0",
              "@angular-eslint/schematics": "^12.0.0",
              "@angular-eslint/template-parser": "1.2.0",
              "@angular/cli": "^11.2.0",
              "@angular/compiler-cli": "^11.2.0",
              "@angular/language-service": "^11.2.0",
              "@commitlint/cli": "^12.1.4",
              "@commitlint/config-conventional": "^7.1.2",
              "@compodoc/compodoc": "^1.1.11",
              "@types/jasmine": "~3.6.0",
              "@types/jasminewd2": "^2.0.8",
              "@types/node": "^12.11.1",
              "@typescript-eslint/eslint-plugin": "4.3.0",
              "@typescript-eslint/parser": "4.3.0",
              "codelyzer": "^6.0.0",
              "eslint": "^7.6.0",
              "eslint-plugin-import": "2.22.1",
              "eslint-plugin-jsdoc": "30.7.6",
              "eslint-plugin-prefer-arrow": "1.2.2",
              "husky": "^1.1.3",
              "jasmine-core": "~3.6.0",
              "jasmine-marbles": "^0.4.0",
              "jasmine-spec-reporter": "~5.0.0",
              "karma": "^6.1.1",
              "karma-chrome-launcher": "~3.1.0",
              "karma-coverage-istanbul-reporter": "~2.0.4",
              "karma-jasmine": "~4.0.0",
              "karma-jasmine-html-reporter": "^1.5.0",
              "karma-spec-reporter": "~0.0.32",
              "lint-staged": "^7.3.0",
              "prettier": "^1.19.1",
              "protractor": "^7.0.0",
              "rimraf": "^2.7.1",
              "ts-node": "~5.0.1",
              "tslint": "~6.1.0",
              "typescript": "~4.1.5",
              "webpack-bundle-analyzer": "^3.8.0"
            }
          }

### Please provide the environment you discovered this bug in

Development

**Comment by JoostK** [comment]
Please share the output of `ng version`. There's very likely a dependency incompatibility in your case.

**Comment by agoussec** [comment]
Angular CLI: 11.2.0
                Node: 14.17.0
                OS: linux x64
                
                Angular: 11.2.0
                ... animations, cdk, cli, compiler, compiler-cli, core, forms
                ... language-service, localize, material, platform-browser
                ... platform-browser-dynamic, router
                Ivy Workspace: Yes
                
                Package                         Version
                ---------------------------------------------------------
                @angular-devkit/architect       0.1102.0
                @angular-devkit/build-angular   0.1102.13
                @angular-devkit/core            11.2.0
                @angular-devkit/schematics      11.2.0
                @angular/common                 11.2.14
                @schematics/angular             11.2.0
                @schematics/update              0.1102.0
                rxjs                            6.6.3
                typescript

**Comment by JoostK** [comment]
Ah! Notice how `@angular/common` is at 11.2.14 while the rest of the Angular packages are at 11.2.0. The 11.2.0 version of `@angular/core` does not have `ɵRuntimeError` as version 11.2.14 of `@angular/common` suggests.

Please run `ng update @angular/core @angular/cli` to update the versions to be in sync (or remove the `package-lock.json` or `yarn.lock` file and reinstall which should also help in this case)
