### ISSUE TITLE
View not updated if using JSPM package

### ISSUE THREAD

**Issue by Mc128k** [angular/angular#4288]
Hi all,
I am pretty new to Angular, and I am starting to learn the whole JS stack using the latest technologies (TypeScript, Angular2, node, SystemJS, ES6). During the development of a specific test code I see that the view does not get updated, while it works perfectly if I link different Angular2 and Traceur libraries. Installing them via JSPM does not create any error in the console, but it just doesn't work.

As this could be one of my endless mistakes, I created a package with the code I was testing, to make debugging as easy as possible, the RUN.sh file holds the required installation steps. After hours searching online and studying the libraries I came out with the conclusion that data binding could be the culprit in this case. I see the JS events in the browser, but the view still remains the same after every update (for example a timeout or a button event).
https://www.dropbox.com/s/w2h6hruo3ytge1u/play_5.zip?dl=1

Thanks a lot

**Comment by Jandalf** [comment]
I have the exact same problem. I created a very simple todo app with angular2+jspm and on adding a todo the console will log the bigger todo array but the view won't update.

https://github.com/Jandalf/angular2-jspm-docker-vscode-template/tree/master/client

(using alpha.37)

**Comment by ericmartinezr** [comment]
My two cents. 

[This user had the same issue](http://stackoverflow.com/questions/32581373/angular-2-binding-issue-on-child-routes) and although he didn't find the solution per se, he found out that the config generated by JSPM is causing the issue.

 I had a similar issue using Promise from `es6-promise` directly, then I was suggested to remove the import and just use `Promise` which is patched by zone.js and this fixed my problem. 

So, in this case it may be difficult to find out what's going on, every loaded library might be interfering somehow with the binding system and for what I saw in [this config file](https://github.com/Jandalf/angular2-jspm-docker-vscode-template/blob/master/config.js) it would take you ages to find out which one(s) is(are) interfering. 

So my recommendation is to start from the bottom, an empty html file and follow the instructions from angular.io, one step at a time so you can have control over everything being loaded, and loading only the necessary.

Track this issue too https://github.com/angular/angular/issues/4278, it will be super useful for this kind of issues.

**Comment by Mc128k** [comment]
Hi, thanks for the update. In the code I am trying I am not even importing es6, I just use systemjs to import Angular2 and reflect-metadata, using Traceur to handle code in the browser. About the config file you mentioned, I don't think there could be anything interesting, it's primarily made of file mappings; what is *really* loaded is then specified in the .ts files I think (correct me if I'm wrong, systemjs should *not* load all the libraries at runtime).

In the files I posted the example is really simple, if I just change the libraries to some external static source, it just works. Take [https://github.com/pkozlowski-opensource/ng2-play](ng-play) as a reference.

**Comment by robwormald** [comment]
might be a zoneJS issue, though I would expect it to throw...

try out the steps here: https://gist.github.com/robwormald/429e01c6d802767441ec

note the zone.js import

**Comment by Mc128k** [comment]
Great, that was even the guide I followed, I just forgot to include zone.js. After doing that, data binding works. Still it's weird that no message are raised. Is this a bug or an expected feature? Should I notify it to zone.js? 

Thanks a lot

**Comment by pkozlowski-opensource** [comment]
Yes, zone.js is required. We've got an issue to throw if it is not present: https://github.com/angular/angular/issues/2683

**Comment by Jandalf** [comment]
thanks, that did it
