### ISSUE TITLE
Lifecycle callback `onChange` is not in sync with directive creation order

### ISSUE THREAD

**Issue by tbosch** [angular/angular#4289]
Directives are created in the order defined by the dependency information of their constructors. However, the order of directives when calling the `onChanges` callback of directives is only depending on the order defined by the `SelectorMatcher`.

E.g. in forms: `DefaultValueAccessor#ngClassUntouched` relies on the fact that `NgControlName#onChanges()` has already been called when both of them match the same element.

**Comment by tbosch** [comment]
Note that this is non trivial as the transformer also has to read out these dependencies and calculate the correct order!

**Comment by tbosch** [comment]
Will be solved together with https://github.com/angular/angular/issues/3605

**Comment by tbosch** [comment]
Also, right now, the transformer does not have a type resolver, it only copies the imports from the original source code..

**Comment by tbosch** [comment]
We could also determine the order of directives when creating the `ProtoElementInjector`, as we need to do this anyways when creating the injector...

**Comment by tbosch** [comment]
Note that this needs to be done while we generate code for the change detectors already!

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

covered by the latest compiler
