### ISSUE TITLE
Add article on how to add app Version number

### ISSUE THREAD

**Issue by alvipeo** [angular/angular#42896]
### Description

I'm sure lots of projects need to show their version. And the version is usually kept in package.json (and incremented at build).
Please add an article with code examples on how to do this.

Currently, it's not a 5 min task. Trust me.

### Proposed solution

Please ask angular advocates/team to provide this info and examples. I'd add this to Tutorial.

### Alternatives considered

Lots

**Comment by gkalpak** [comment]
Unless I am missing something, this doesn't sound like something that is specific/related to Angular, so I don't think it makes sense to include it in our docs.

<sub>(Closing, but feel free to continue the discussion below.)</sub>

**Comment by alvipeo** [comment]
Well, if you tried it you'd know.

**Comment by gkalpak** [comment]
> Well, if you tried it you'd know.

Sorry, I am not sure what you mean by this 😕
Can you please elaborate?
