### ISSUE TITLE
How to update angular version to latest version?

### ISSUE THREAD

**Issue by TortuC** [angular/angular#42893]
My current version is angular 8, but i would like to upgrade it to latest version.

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
