### ISSUE TITLE
Input() default value is not honored

### ISSUE THREAD

**Issue by ychaikin** [angular/angular#42913]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

A component defines a default value for an `Input()` as in the following:
```
  @Input()
  test? = 'default value';
```

The value of `test` should now be assumed to be `default value` unless the client sets the `[test]="some value"`. However, if the client sets `[test]="undefined"` or `[test]="null"`, it seems that `test` should ALSO be `default value`.

However, that's not what happens. Instead, `[test]="undefined"` sets the `test` property to `undefined`.

That doesn't seem consistent with the idea of a default value, which should be triggered when the value is `undefined` or `null`.

Why would you care? Who in their right mind does this `[test]="undefined"`?

Well, for example, frameworks like Storybook do and it messes up the story setup unless once is explicitly setting the default value. See this link: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#no-longer-inferring-default-values-of-args . Pay attention to these words: `In 6.3 we no longer infer default values and instead set arg values to undefined when unset, allowing the framework to supply the default value.`

Well, in Angular, that doesn't work out to be the "default value". I believe Storybook is correct in their assumption here and Angular behavior is the one that needs to change to take care of this case.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-p89jvp?file=src%2Fapp%2Ftest.component.ts

**Comment by MurhafSousli** [comment]
Once you passed a value to the input, it should use it as the new value, `null` or `undefined` are also considered as new values.
It might not make sense to some people, but what if someone developed a library and has written some logic in case a null value is passed to the input! should Angular ignores it?

**Comment by ychaikin** [comment]
@MurhafSousli Angular wouldn't ignore it. As the developer of this particular component, you already told Angular (as per its docs) that you want this value to be the default. Now, the question becomes what "default" means. 

I might be wrong, but I think just about everywhere else in Javascript/Typescript, "default" is used for values that are `undefined` or `null`.

Yes, you can write custom logic in `ngOnChanges`, in `ngOnInit`, in a `set`, etc. to guard for this sort of thing, but seems to me that you shouldn't have to.

Providing the default value, as you did in your example, in the client of your component, defeats the whole purpose of having a default value in the component itself.

I am proposing that Angular does something like prior to firing its `ngOnChanges` lifecycle method:
```
currentValue = value ?? defaultValueFromClass
```

**Comment by JoostK** [comment]
This is working as expected; the initializer expression of a field is only evaluated when constructing the component/directive instance; it's invisible to Angular's data binding mechanism. The data binding mechanism only concerns itself with bindings in a template and writes the bound value into the appropriate backing field, thereby overriding any initial value form the initializer expression.

Please see #38556 for a recent discussion on a feature request for this behavior.
