### ISSUE TITLE
Add option to not reset Url and Router state to Angular Router on Navigation Errors

### ISSUE THREAD

**Issue by DiegoRGonzalez** [angular/angular#42915]
### Which @angular/* package(s) are relevant/releated to the feature request?

router

### Description

Currently the Angular router resets the state and the url on navigation errors [1] and on Navigation cancels that do not redirect [2]. Due to this, if someone is navigating from “a” -> “b” and hits a navigation error or a failed canActivate guard, the url stays on “a”. Furthermore, if the url update strategy is ‘eager’, the url actually gets changed from ‘a’ to ‘b’ prior to the error and is then changed back to ‘a’, resulting in the url flickering for the user from the destination url back to their origin url. 

This makes it difficult to show an error page while maintaining the context of the destination url “b”, and is somewhat counterintuitive when using the url update strategy of ‘eager’ as the url changes back and forth. See https://github.com/angular/angular/issues/17004 for a similar feature request that focuses on showing an error page on pages that have failed canActivate guards.

[1] https://github.com/angular/angular/blob/e2aa7652e5270e2a0c825ee2f0dde8e307a3b959/packages/router/src/router.ts#L955
[2] https://github.com/angular/angular/blob/e2aa7652e5270e2a0c825ee2f0dde8e307a3b959/packages/router/src/router.ts#L923

### Proposed solution

Add a new setting in ExtraOptions[1] named resetUrlOnError that is by default true.
```
export interface ExtraOptions{
...
resetUrlOnError?: boolean;
}
```
And then where `resetStateAndUrl` is called, we reference this option to conditionally skip calling it if that setting is disabled.
```
if(this.resetUrlOnError){
	this.resetStateAndUrl(t.currentRouterState, t.currentUrlTree, t.rawUrl);
}
```

However, this only results in the behaviour we want when the url update strategy is set to eager, as the url is updated prior to when the navigation error is encountered. Due to this, we will also only skip this call if the url update strategy is set to eager. We would also make sure to call out in a comment for `resetUrlOnError` that it only works in eager mode.

```
if(this.resetUrlOnError || this.urlUpdateStrategy !== ‘eager’){
	this.resetStateAndUrl(t.currentRouterState, t.currentUrlTree, t.rawUrl);
}
```

[1] https://github.com/angular/angular/blob/1d9d02696eadbee2c2f719e432efca22f1e494e9/packages/router/src/router_module.ts#L256

### Alternatives considered

Along with the above change, we could modify the state and url for navigation errors that are encountered when the url update strategy is set to deferred. However as we do not know where in the navigation the error occurred, and therefore we do not know what state the url and router state will be in, it seems safer to only support this setting with the url update strategy set to eager. This also makes more sense with the eager url update strategy as we are specifically choosing to not wait until after the navigation ends to change the url.

Another alternative would be to move the resetStateAndUrl call into the default ErrorHandler [1], which would allow users to overwrite this and define their own error handling in that handler. However this function is currently empty and is often overwritten, so moving this call into this function would require a careful migration process to ensure no angular users are broken by the change.

https://github.com/angular/angular/issues/27148 would also enable us to achieve this by giving us more options to set during failed guards. However, those settings would need to be set for every guard and as it is focused on guards, it would not solve the more general case of errors encountered during a navigation.

On top of all this, this proposed change is fairly simple and straightforward, which results in no change in behavior by default. Each of the above alternatives add complexity which would require more investigation to ensure that no existing users of Angular are broken by a change to the Router code.

[1] https://github.com/angular/angular/blob/e2aa7652e5270e2a0c825ee2f0dde8e307a3b959/packages/router/src/router.ts#L223

**Comment by Airblader** [comment]
> This change also fixes the same issue that #27148 aims to fix.

I don't understand how this change would solve #27148. Can you elaborate on that?

It seems to me that #27148 is about the guard defining this behavior while the proposal here aims to define the behavior on the navigation attempt itself. Wouldn't that mean that you need to set this flag potentially for every navigation in the entire app (including routerLink)?

**Comment by DiegoRGonzalez** [comment]
> > This change also fixes the same issue that #27148 aims to fix.
> 
> I don't understand how this change would solve #27148. Can you elaborate on that?
> 
> It seems to me that #27148 is about the guard defining this behavior while the proposal here aims to define the behavior on the navigation attempt itself. Wouldn't that mean that you need to set this flag potentially for every navigation in the entire app (including routerLink)?

Good catch, thanks! I actually meant to add it to the RouterModule's ExtraOptions, not the NavigationBehaviourOptions, which would define this setting for all navigations, the same as the UrlHandlingStrategy. I've edited my feature request to reflect that.

**Comment by Airblader** [comment]
Thanks for the clarification! I'd still like to add that this wouldn't solve the use case presented in #27148 because we wouldn't want to have this globally, but only for the redirects done from (a certain) guard.

**Comment by DiegoRGonzalez** [comment]
Ah I see, that does seem distinct, thanks for clearing that up! I've modified my comment to specify that https://github.com/angular/angular/issues/27148 would allow us to achieve our desired behavior for guards instead of saying that both of these fix the same issue.

**Comment by atscott** [comment]
Closing. This feature was requested as a potential fix for an internal application's needs. After further investigation, I don't believe this is the direction we would want to address the issues there. Some notes:

* `resetStateAndUrl` is only called when the navigation fails due to an error. However, it really should always be called when a navigation fails. This change to make the reset consistent would affect the desired outcome for this request.
* Navigations are canceled with an error due to a URL not matching or a thrown error in guards, resolvers, components, etc. These two situations are certainly not equivalent and shouldn't be treated as such. The proposed feature wouldn't really differentiate between the two.
