### ISSUE TITLE
problem with the es6-shim under ie (edge) v 11

### ISSUE THREAD

**Issue by cmsdesigner** [angular/angular#4291]
Hi ,
i have a angular 2 sample (ng2-play)
 when i execute gulp play i have my ie browser is launched automatically and my page browser show only Loading...., and when i check a console i have an error on
Fichier : localhost:9000, ligne : 19, colonne : 5 and it says in french 
System.config({defaultJSExtensions: true});
L’objet ne gère pas la propriété ou la méthode « config »
But the strange is it works on chrome
im working under windows 7
node v4.1.0
npm v3.3.3
gulp cli v3.9.0

**Comment by PascalPrecht** [comment]
@cmsdesigner this is rather an issue for the https://github.com/pkozlowski-opensource/ng2-play.ts repository. Please file an issue there. Thanks!

**Comment by pkozlowski-opensource** [comment]
@PascalPrecht nope, this is not an issue about the starter repo but rather about browsers support.

**Comment by pkozlowski-opensource** [comment]
Although I'm afraid it is hardly actionable in the current form. @mlaval is doing tons of work on various browsers support so this issue will be resolved as part of this work.

**Comment by cmsdesigner** [comment]
Tank's very much for you reply , and hop that is will be solved soon 
  
Good luck 
  
----- Mail original -----

De: "Pawel Kozlowski" <notifications@github.com> 
À: "angular/angular" <angular@noreply.github.com> 
Cc: "mjhdesigner" <mjhdesigner@laposte.net> 
Envoyé: Lundi 21 Septembre 2015 19:59:29 
Objet: Re: [angular] problem with the es6-shim under ie (edge) v 11 (#4291) 



Although I'm afraid it is hardly actionable in the current form. @mlaval is doing tons of work on various browsers support so this issue will be resolved as part of this work.
