### ISSUE TITLE
router.navigate not pushing history when changing queryParams

### ISSUE THREAD

**Issue by mhosman** [angular/angular#42927]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

When changing queryParams with router.navigate, a new state in the story is not being pushed so if we go back with the browser, is not gonna take the old queryParams in that particular page.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by atscott** [comment]
@mhosman A reproduction of the issue is required for us to be able to investigate it.
