### ISSUE TITLE
FIltering router.events not working

### ISSUE THREAD

**Issue by codeandcloud** [angular/angular#42920]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

When I try to use, 

```
class MyService {
  constructor(public router: Router) {
    router.events.pipe(
       filter((e: Event): e is RouterEvent => e instanceof RouterEvent)
    ).subscribe((e: RouterEvent) => {
      console.log(e.id, e.url);
    });
  }
```
as per the documentation, I get this error

Documentation Link: https://angular.io/api/router/RouterEvent#description

Why is this happening?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-ls4jgl

### Please provide the exception or error you saw

```true
Argument of type 'MonoTypeOperatorFunction<Event>' is not assignable to parameter of type 'OperatorFunction<Event, Event>'.
Types of parameters 'source' and 'source' are incompatible.
Type 'import("/turbo_modules/rxjs@7.1.0/dist/types/internal/Observable").Observable<import("/turbo_modules/@angular/router@12.1.0/router").Event>' is not assignable to type 'import("/turbo_modules/rxjs@7.1.0/dist/types/internal/Observable").Observable<Event>'.
Type 'import("/turbo_modules/@angular/router@12.1.0/router").Event' is not assignable to type 'Event'.
Type 'RouterEvent' is not assignable to type 'Event'.
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.1.0
rxjs: 7.1.0
```

### Anything else?

The stackblitz.com example is using rxjs 7.1.0(default). Can reproduce the same error with rxjs 6.6.7

**Comment by JoostK** [comment]
The example is missing the import statement for the `Event` type union from `@angular/router`. This means that the `Event` type will instead be resolved to the ambient DOM `Event` type, which is not compatible with the router's event type.

You'll need to adjust the import statement as follows:

```ts
import { Router, RouterEvent, Event } from '@angular/router';
```
