### ISSUE TITLE
integrate multiple angular applications into single application like "WORKSPACE"

### ISSUE THREAD

**Issue by muthuramanm** [angular/angular#42925]
Hi Experts,
  I need to integrate multiple angular applications into single application like "WORKSPACE". But the problem is managing the repository codes commit in each project varies, it have dependencies when build (change in package.json, build each project, put it inside the single project like copy,paste). It's a tedious process. please share your thoughts and suggest how to do that in optimized way and how can host it as workspace application like google(gmail,docs,sheets,calendar etc)?..

Thanks

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).
