### ISSUE TITLE
`done` event is fired when state have changed whereas animation have not end

### ISSUE THREAD

**Issue by owl-from-hogvarts** [angular/angular#42946]
### Which @angular/* package(s) are the source of the bug?

animations, platform-browser

### Is this a regression?

No

### Description

In my understanding `@animation.done` callback should be fired only when annimation is really completed, meaming delay is expired, transition is completed, styles are *completely* applyed. At this point animation is really done and event can be fired.

### But

Now `done` callback is called also on **state change** (when changing state while other animation is still running) even if animation haven't completed yet. Here angular doing next things:
1. Instantly finish running animation
2. Fire `done` event for this animation
3. Perform animation to go to the next state
4. Fire `done` event for that animation

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-vgcynl?file=src%2Fapp%2Fapp.component.ts

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.1.1
Node: 14.15.3
Package Manager: pnpm 6.10.3
OS: linux x64

Angular: 12.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            12.1.1
@angular-devkit/schematics      12.1.1
@angular/cdk                    12.1.2
@angular/material               12.1.2
@schematics/angular             12.1.1
rxjs                            6.6.7
typescript                      4.3.5
```

### Anything else?

In the provided example wait a while. When you will see that card is disappeared by a about half, move mouse over and out of card and check console. You will see two events fired: first for `show => hide` animation and seccond for `hide => show` which is preformed immediately and while `show  => hide` animation is still in process therefor aborting it. I think, first event *should* ***not*** be fired since in my understanding `done` means that animation is completely done: delay is expired, transition is done, all styles are fully applyed which is not applicable for first event, where animation is only about half done!

**Comment by dario-piotrowicz** [comment]
Hi @owl-from-hogvarts, I do believe that this is working as expected, when you hover over the item you actually "kill"/"stop" the old animation and a new one starts

I have slightly tweaked your stackblitz to show better what I mean: [slightly tweaked stackblitz](https://stackblitz.com/edit/angular-ivy-rdfs4h?file=src%2Fapp%2Fapp.component.ts)

You can see the various animations starting/ending when you hover in/out the element:
![Peek 2021-12-04 21-55](https://user-images.githubusercontent.com/61631103/144725820-38ac3342-4ecb-48de-8ad8-be1070745d80.gif)

What do you think? :slightly_smiling_face:

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

**Comment by owl-from-hogvarts** [comment]
Sorry for my english. It is quite hard to express my thought clear enough as it is not my native language) I mean that angular should tell to the app whether animations is aborted by whatever reason (including state change) or complited as normal.

P.S. thanks for reply)

**Comment by dario-piotrowicz** [comment]
> Sorry for my english. It is quite hard to express my thought clear enough as it is not my native language) I mean that angular should tell to the app whether animations is aborted by whatever reason (including state change) or complited as normal.
> 
> P.S. thanks for reply)

Not a problem, thanks for your reply :smiley: 

I see what you mean now, you would want to know that the animation hasn't run its full course right? :slightly_smiling_face:   but I believe that the animation start and end callbacks are correct here as the animation is actually starting and ending, also I checked and the [AnimationEvent](https://angular.io/api/animations/AnimationEvent) does not seem to have useful info about your aborted/cancelled animation (totalTime indicates the animation totalTime and does not take into consideration the cancellation of it).

Maybe if you want we can open a feature request to add a `cancelled` field to the AnimationEvent object so that it can show if the animation has been cancelled? what do you think?
(if you'd want I would not mind opening the feature request for you :slightly_smiling_face:)

**Comment by owl-from-hogvarts** [comment]
> I see what you mean now, you would want to know that the animation hasn't run its full course right?


Yes. Kind of)
Your suggestion about `cancelled` field looks like good solution.

Since i am not working with angular now for considerable time, it would be really cool, if you will open feature request by your self. If you have any questions here, you can ask me)

**Comment by dario-piotrowicz** [comment]
Cool, I'll open a feature request and see if people agree that this would be a nice addition :slightly_smiling_face::+1:
