### ISSUE TITLE
Classes with static members cannot have private constructors (d.ts)

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#4294]
```
class MyClass {
  /** @private */
  constructor() {}

  static func(){}
}
```

Generates the following d.ts file:

```
interface MyClass {
  static func(){}
}
```

This is incorrect because interfaces cannot have static members.

We should probably generate the MyClass namespace in addition to the MyClass interface.

**Comment by petebacondarwin** [comment]
@vsavkin and @mhevery - if you could agree what is the best solution here then I can implement it.

**Comment by mhevery** [comment]
My first thought is:

1. can we not just have both static and `@private`? @vsavkin what are some examples where this is an issue.
2. If 1 can not be fixed then the proposal is correct one.

**Comment by alexeagle** [comment]
I think this will be fixed by removing the magic interface -> class logic, @mhevery and I have proposed to create abstract parent classes for those which have internal constructors.

**Comment by petebacondarwin** [comment]
@alexeagle - what is the action needed here?

**Comment by mhevery** [comment]
This is obsolete, as we no longer need the `@private` which converts a class to interface.
