### ISSUE TITLE
How to troubleshoot ngcc TypeError: Cannot read property 'fileName' of null

### ISSUE THREAD

**Issue by scomo** [angular/angular#42954]
# 🐞 Bug report

when running ng build I get an exception during what I understand to be ngcc compiling @angular/core: 

I am at a loss for how to troubleshoot this. This is a separate feature branch of a recently upgraded angular 12 project, incorporating changes from another developer. The base branch build correctly.

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 No

### Description

 
When running ng build, I see the following output: 
⠋ Generating browser application bundles (phase: setup)...
Compiling @angular/core : es2015 as esm2015

at which point I see the exception and the stack trace below. 
Note after an npm ci command, I also see the same message appear and complete successfully before it builds other node packages. 

## 🔥 Exception or Error

<pre><code>

An error occurred during the build:
TypeError: Cannot read property 'fileName' of null
    at Object.getImportRewriter (C:\Projects\xxxx\ngapp\node_modules\@angular\compiler-cli\ngcc\src\rendering\utils.js:23:72)
    at DtsRenderer.renderDtsFile (C:\Projects\xxxxx\ngapp\node_modules\@angular\compiler-cli\ngcc\src\rendering\dts_renderer.js:77:72)
    at C:\Projects\xxxx\ngapp\node_modules\@angular\compiler-cli\ngcc\src\rendering\dts_renderer.js:69:158
    at Map.forEach (<anonymous>)
    at DtsRenderer.renderProgram (C:\Projects\xxxx\ngapp\node_modules\@angular\compiler-cli\ngcc\src\rendering\dts_renderer.js:69:26)
    at Transformer.transform (C:\Projects\xxxx\ngapp\node_modules\@angular\compiler-cli\ngcc\src\packages\transformer.js:93:52)
    at C:\Projects\xxxx\ngapp\node_modules\@angular\compiler-cli\ngcc\src\execution\create_compile_function.js:52:42
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (C:\Projects\xxxx\ngapp\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:36:17)
    at C:\Projects\xxxx\ngapp\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:59
    at SyncLocker.lock (C:\Projects\xxxx\ngapp\node_modules\@angular\compiler-cli\ngcc\src\locking\sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (C:\Projects\xxxx\ngapp\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:27)
    at Object.mainNgcc (C:\Projects\xxxx\ngapp\node_modules\@angular\compiler-cli\ngcc\src\main.js:74:25)
    at Object.process (C:\Projects\xxxx\ngapp\node_modules\@angular\compiler-cli\ngcc\index.js:29:23)
    at NgccProcessor.processModule (C:\Projects\xxxx\ngapp\node_modules\@ngtools\webpack\src\ngcc_processor.js:175:16)
    at C:\Projects\xxxx\ngapp\node_modules\@ngtools\webpack\src\ivy\host.js:146:18
    at C:\Projects\xxxx\ngapp\node_modules\@ngtools\webpack\src\ivy\host.js:76:24
An unhandled exception occurred: Cannot read property 'fileName' of null
See "C:\Users\xxxxxx\AppData\Local\Temp\ng-caDDPE\angular-errors.log" for further details.
</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.1.3
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.1.3
... animations, cli, common, compiler, co
... elements, forms, language-service, lo
... platform-browser, platform-browser-dy
... router

Package                         Version
-----------------------------------------
@angular-devkit/architect       0.1201.3
@angular-devkit/build-angular   12.1.3
@angular-devkit/core            12.1.3
@angular-devkit/schematics      12.1.3
@schematics/angular             12.1.3
rxjs                            6.6.7
typescript                      4.3.4
webpack                         5.41.1
</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
@scomo - I have a feeling this is a version skew issue.

Can I ask if you have done the obvious and removed the node_modules folder and re-run `npm install` (or equivalent)? Does the feature branch modify any of the dependencies in package.json (or the appropriate lock file)?

**Comment by scomo** [comment]
removing the node_modules folder entirely, as well as npm ci have been tried.

**Comment by scomo** [comment]
the package.json differences include addition of @ngrx/store as well as simplebar-angular packages.  Below is the current package.json file.

**Comment by scomo** [comment]
{
  "name": "AngularUI",
  "version": "0.0.0",
  "license": "UNLICENSED",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "concat-es5": "concat -o dist/ng-elements-es5.js ./dist/runtime-es5.js ./dist/polyfills-es5.js ./dist/scripts.js ./dist/main-es5.js",
    "concat-es2015": "concat -o dist/ng-elements-es2015.js ./dist/runtime-es2015.js ./dist/polyfills-es2015.js ./dist/scripts.js ./dist/main-es2015.js",
    "concat": "npm run concat-es5 && npm run concat-es2015",
    "build": "ng build",
    "serve": "http-server",
    "test:old": "ng test",
    "test": "ng test --no-watch --no-progress --browsers=ChromeHeadlessCI",
    "test:ci": "ng test --no-watch --no-progress --browsers=ChromeHeadlessCI",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^12.1.3",
    "@angular/common": "^12.1.3",
    "@angular/compiler": "^12.1.3",
    "@angular/core": "^12.1.3",
    "@angular/elements": "^12.1.3",
    "@angular/forms": "^12.1.3",
    "@angular/localize": "^12.1.3",
    "@angular/platform-browser": "^12.1.3",
    "@angular/platform-browser-dynamic": "^12.1.3",
    "@angular/platform-server": "^12.1.3",
    "@angular/router": "^12.1.3",
    "@ant-design/icons-angular": "12.0.3",
    "@ng-select/ng-select": "7.0.1",
    "@ngx-translate/core": "13.0.0",
    "@types/lodash": "^4.14.170",
    "@webcomponents/webcomponentsjs": "2.5.0",
    "chalk": "4.1.1",
    "classlist.js": "1.1.20150312",
    "concat": "3.0.0",
    "core-js": "3.15.2",
    "document-register-element": "1.14.10",
    "file-saver": "2.0.5",
    "html5-history-api": "4.2.10",
    "http-server": "0.12.3",
    "intl": "^1.2.5",
    "moment": "2.29.1",
    "ng-zorro-antd": "^12.0.1",
    "ng2-cookies": "^1.0.12",
    "ng2-dragula": "2.1.1",
    "ng5-slider": "1.2.6",
    "ngx-bootstrap": "6.2.0",
    "ngx-swiper-wrapper": "10.0.0",
    "rxjs": "6.6.7",
    "tslib": "2.3.0",
    "web-animations-js": "^2.3.2",
    "webpack": "5.41.1",
    "zone.js": "0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "12.1.0",
    "@angular/cli": "12.1.0",
    "@angular/compiler-cli": "^12.1.3",
    "@angular/language-service": "12.1.0",
    "@types/jasmine": "3.7.7",
    "@types/jasminewd2": "2.0.9",
    "@types/node": "15.12.4",
    "codelyzer": "6.0.2",
    "gulp": "4.0.2",
    "jasmine-core": "3.7.1",
    "jasmine-spec-reporter": "7.0.0",
    "karma": "6.3.4",
    "karma-chrome-launcher": "~3.1.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "3.0.3",
    "karma-jasmine": "4.0.1",
    "karma-jasmine-html-reporter": "1.6.0",
    "protractor": "~7.0.0",
    "swiper": "6.7.1",
    "ts-node": "10.0.0",
    "tslint": "6.1.3",
    "typescript": "4.3.4"
  }
}

**Comment by scomo** [comment]
so question: Is this ngcc phase of the build strictly based on the dependencies defined in package.json? it has not gotten anywhere near the point where it would be detecting compilation errors in my project, which i'm sure will exist based on some of the problems that show up in vscode while sifting through the changes..

**Comment by petebacondarwin** [comment]
In the versions of Angular CLI that you are using ngcc is invoked in two different ways:

- asynchronously - before the TS compilation and bundling begins
- synchronously - during TS compilation when each imported library is requested from webpack

The async phase looks at the tsconfig.json that is being used to compile. It reads the root files and the paths mappings, which allows it to work out what libraries are going to need to be processed. From each root file, we tokenize the source and find every import statement, recursively following relative paths, and capturing absolute library paths. Once this is done it runs ngcc on each of the libraries in the order in which they depend upon each other.

Normally this async phase is enough to capture and process all the dependent libraries for a project. But in some cases, such as when a new dependency is imported during a watched build, we must rely upon processing the new library synchronously during the TS compilation.

Hopefully this should explain how ngcc is able to process libraries even if there are build errors in the application code itself.

**Comment by JoostK** [comment]
Can you provide the list of files in `node_modules/@angular/core/`, `node_modules/@angular/core/src/` and `node_modules/@angular/core/esm2015/src/`?

**Comment by petebacondarwin** [comment]
I note that the error is being thrown on this line:

```ts
return new imports_1.R3SymbolsImportRewriter(r3SymbolsFile.fileName);
```

**Comment by petebacondarwin** [comment]
So I guess that `r3SymbolsFile` is `null`.

**Comment by petebacondarwin** [comment]
So it seems that this file is missing `https://unpkg.com/browse/@angular/core@12.1.3/src/r3_symbols.d.ts` from the program files that are being compiled...

**Comment by scomo** [comment]
@petebacondarwin yes rs3SymbosFile is null, at one point I was putting console.warn in there to detect that and spit out the three parameters passed into that method, but couldn't determine what it was doing from the json that ensued..

**Comment by scomo** [comment]
@JoostK here is the current contents of node_modules/@angular/core.. why the @angular directory?

**Comment by petebacondarwin** [comment]
You could try putting a break point at https://github.com/angular/angular/blob/d100a15998155bf4b882471d3747df877d8b2b5f/packages/compiler-cli/ngcc/src/packages/bundle_program.ts#L51

**Comment by petebacondarwin** [comment]
The next line is where it computes the r3SymbolsPath

**Comment by petebacondarwin** [comment]
Or even better put a breakpoint in the `findR3SymbolsPath()` function

**Comment by scomo** [comment]
I am seeing different behavior now, i just realized i had an errant node_modules folder farther up the directory tree (two levels above src). upon removing that, I am now seeing the true compilation errors from the application.

**Comment by scomo** [comment]
I had read other comments about having two versions of @angular/core installed on a SO ticket, but never saw that in my npm list searches. Did not think about going farther up the tree.

**Comment by petebacondarwin** [comment]
Does that mean we can close this ticket?

**Comment by scomo** [comment]
yes. thank you for your time..
