### ISSUE TITLE
Angular 12 in prod mode change incoming blob file

### ISSUE THREAD

**Issue by IrwinJuice** [angular/angular#42969]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Is this a regression? -  Don't know.

On the backend I have an API that returns a formatted XSD (XML Schema) file (with indentation, spaces, etc.).
A small part for an example:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:annotation>
		<xs:documentation>F3VX</xs:documentation>
		<xs:appinfo>Published: 16.06.2021 11:50:49</xs:appinfo>
		<xs:appinfo>Start date: 01.07.2021</xs:appinfo>
	</xs:annotation>
	
	....
```

In Angular, I have a method that receives a file from the backend and gives it to the user.

V1 - downloading with file-saver.js (lib)
```
generateXML(sls: SLoadSource) {
	// ...
    this.service.generateXML(sls.idsrc).subscribe(blob => saveAs(blob, `${sls.name}.xsd`));
}
```

OR I tried

V2 - downloading with native methods
```
generateXML(sls: SLoadSource) {
	// ...
    return this.service.generateXML(sls.idsrc).subscribe(blob => this.downloadFile(blob, `${sls.name}.xsd`));
}
downloadFile(data: Blob, fileName: string) {
  
    const a = this.document.createElement('a');

    a.href = URL.createObjectURL(data);
    a.download = fileName;
    a.click();
}
```

When I download the file in "ng serve" or in "ng build"  mode, it works fine. The file is formatted as shown above.

But when I build a project with "ng build --configuration production", then the downloaded file loses formatting and comes in one line.

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">	<xs:annotation>		<xs:documentation>F3VX</xs:documentation>		<xs:appinfo>Published: 16.06.2021 11:50:49</xs:appinfo>		<xs:appinfo>Start date: 01.07.2021</xs:appinfo>	</xs:annotation>	<xs:simpleType name="CTREPORTDATE">`

This happens regardless of whether I'm using file-saver.js or URL.createObjectURL (data).

### Please provide the environment you discovered this bug in

```true
"dependencies": { 
    "@angular/animations": "~12.1.2",
    "@angular/cdk": "^12.1.2",
    "@angular/common": "~12.1.2",
    "@angular/compiler": "~12.1.2",
    "@angular/core": "~12.1.2",
    "@angular/flex-layout": "^12.0.0-beta.34",
    "@angular/forms": "~12.1.2",
    "@angular/material": "^12.1.2",
    "@angular/material-moment-adapter": "^12.1.2",
    "@angular/platform-browser": "~12.1.2",
    "@angular/platform-browser-dynamic": "~12.1.2",
    "@angular/router": "^12.1.2",
    "@types/file-saver": "^2.0.2",
    "file-saver": "^2.0.5",
    "jwt-decode": "^3.1.2",
    "moment": "^2.29.1",
    "rxjs": "~6.5.4",
    "tslib": "^2.0.0",
    "uuid": "^8.3.1",
    "zone.js": "~0.11.4"
}

"devDependencies": {
    "@angular/cli": "~12.1.2",
    "@angular/compiler-cli": "~12.1.2",
    "@angular/language-service": "~12.1.2",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "protractor": "~7.0.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.1.0",
    "typescript": "~4.3.5"
}
```

**Comment by petebacondarwin** [comment]
Please can you provide a running example of this problem for us to investigate. Without this it is not possible to look into this issue.

**Comment by IrwinJuice** [comment]
I'll try create demo project tomorrow.

**Comment by IrwinJuice** [comment]
@petebacondarwin I'm sorry for wasting your time.  I forgot to change the environment in production mode. The link was to the old API. 🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by petebacondarwin** [comment]
No worries. Thanks for the update.
