### ISSUE TITLE
Routing triggered twice and in the process losing on added query params

### ISSUE THREAD

**Issue by msachin1** [angular/angular#42968]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

Added a lazy loading module configuration
{
    path: service-list,
    loadChildren: () => import('./service-list/service-list.module').then(m => m.ServiceListModule),
  },

In the service-list routing module module defined the route as
{
    path: '',
    component: ServiceListContainerComponent,
  }

when, the navigation is triggered to this component with some added query params, the query params are getting lost due to re-routing
this.router.navigate(['service-list'], { queryParams: { test: true } }); 

On enabling trace and checking in console, NavigationStart event is triggered twice and in the process the query params passed are lost

1st 
Router Event: NavigationStart
platform-browser.js:87 NavigationStart(id: 6, url: '/service-list?test=true')
platform-browser.js:87 NavigationStart {id: 6, url: "/service-list?test=true", navigationTrigger: "imperative", restoredState: null}

2nd
Router Event: NavigationStart
platform-browser.js:87 NavigationStart(id: 7, url: '/service-list')
platform-browser.js:87 NavigationStart {id: 7, url: "/service-list", navigationTrigger: "imperative", restoredState: null}

### Anything else?

Angular CLI: 9.1.15
Node: 16.3.0
OS: win32 x64

Angular: 9.1.13

**Comment by atscott** [comment]
@msachin1 Could you please provide a stackblitz reproduction. From the description, it is not clear what is causing the second navigation. If you trigger a new navigation when one is still in progress, the first is canceled and the second takes over. The query params would not be merged.

**Comment by msachin1** [comment]
@atscott Hi, thanks for replying. The issue root cause has been identified. Actually, the third party library has some bug because of which the additional navigation was getting fired which was overwriting the query params. I will go ahead and close this issue. Thank you.
