### ISSUE TITLE
How to prevent caching of the post method

### ISSUE THREAD

**Issue by GNURub** [angular/angular#42975]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

No

### Description

I have a method to save the translations. And angular is responding to me from the service worker, and the request does not reach the server.

![post_sw](https://user-images.githubusercontent.com/1318648/127289749-06309126-da46-415b-89da-e40688746370.png)

ngsw-config.json

![ngsw-config](https://user-images.githubusercontent.com/1318648/127289850-8c966035-ebd3-404e-a436-e7978aa87616.png)

any idea why it might be? Thanks!

### Please provide the environment you discovered this bug in

```true
Angular CLI: 10.2.0
Node: 16.4.1
OS: linux x64

Angular: 10.1.6
... animations, common, compiler, core, forms, localize
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1001.7
@angular-devkit/build-angular      0.1001.7
@angular-devkit/core               10.2.0
@angular-devkit/schematics         10.2.0
@angular/cdk                       10.2.5
@angular/cli                       10.2.0
@angular/compiler-cli              10.2.0
@angular/language-service          10.2.0
@angular/material                  10.2.7
@angular/material-moment-adapter   10.2.7
@nguniversal/builders              10.1.0
@nguniversal/express-engine        10.1.0
@schematics/angular                9.1.12
@schematics/update                 0.1002.0
rxjs                               6.6.3
typescript                         3.9.7
```

**Comment by gkalpak** [comment]
As can be seen [here][1], the SW should just forward mutation requests (including POST requests) to the server.
What does the request list in the DevTools Network tab look like?

[1]: https://github.com/angular/angular/blob/0d81b007e48a0ac801d2614601fb8180a3517865/packages/service-worker/worker/src/data.ts#L307-L338

**Comment by alxhub** [comment]
Closing due to no response.
