### ISSUE TITLE
template.createEmbeddedView will never run change detection

### ISSUE THREAD

**Issue by Akxe** [angular/angular#42977]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

When a template is created via `template.createEmbeddedView(...)`, the contents will not be initialized and change detection will never run either. Every change detection would have to be called manually via `view.detectChanges()`.

Any components inside created template will not fire the `ngOnInit` life cycle hook until the `detectChanges` is called.

Might be related to: https://github.com/angular/angular/issues/41501

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-aldx8q?file=src%2Fapp%2Fhello.component.ts

### Please provide the exception or error you saw

```true
The error is that no change detection is ran for any templates/components created this way.
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.1.3
Node: 14.16.0
Package Manager: npm 7.16.0
OS: win32 x64

Angular: 12.1.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, google-maps, language-service, material
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.3
@angular-devkit/build-angular   12.1.3
@angular-devkit/core            12.1.3
@angular-devkit/schematics      12.1.3
@schematics/angular             12.1.3
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by alxhub** [comment]
@Akxe, can you expand a little bit more on what this reproduction is supposed to be showing? Having looked through the code a little, I believe this is working as intended. `TemplateRef.createEmbeddedView` creates a view that's not attached to the application's view hierarchy in any way, so I wouldn't expect it to be change detected unless manually triggered or manually attached.

**Comment by Akxe** [comment]
I use models created like this in google maps, thus they are outside of angular DOM, but they still need to react to changes in the angular app. My current solution is to create them inside a view and then move every element in `view.rootNodes` to the new location... is seems hacky and wacky, but it worked before and works now...

Also, the fact, that `EmbeddedViewRef` has a method `attach` that may do nothing is very misleading. It should at least print a warning that it will do nothing if not part of angular tree

**Comment by pkozlowski-opensource** [comment]
I'm with @alxhub here - the act of creating an embedded view (`TemplateRef.createEmbeddedView`) corresponds to the "creation" part of a template. In this (one-time) phase we create DOM elements but don't evaluate dynamic parts. In order to evaluate dynamic parts one needs to change-detect views.

You can totally create "standalone" views and attach those to a change detection tree "outside" of the DOM tree by [attaching view to ApplicationRef](https://angular.io/api/core/ApplicationRef#attachView). 

It all might not be super-intuitive but it seems to behave as designed.

**Comment by Akxe** [comment]
@pkozlowski-opensource Attaching view to `ApplicationRef` is a logical solution.
