### ISSUE TITLE
Injectable with params useFactory and deps(use parameters decorator) throw error

### ISSUE THREAD

**Issue by wszgrcy** [angular/angular#42987]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

No

### Description

origin code
```ts
@Injectable({
  useFactory: (a) => new AppService(a),
  providedIn: 'root',
  deps: [[new Optional(), 'aa']],
})
export class AppService {
  constructor(aa) {}
}

```
compile code
```ts
class AppService {
    constructor(aa) { }
}
AppService.ɵfac = function AppService_Factory(t) { _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵɵinvalidFactory"](); };
AppService.ɵprov = /*@__PURE__*/ _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵɵdefineInjectable"]({ token: AppService, factory: function AppService_Factory(t) { let r = null; if (t) {
        r = new t();
    }
    else {
        r = ((a) => new AppService(a))(_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵɵinject"]([new _angular_core__WEBPACK_IMPORTED_MODULE_0__.Optional(), 'aa'], 8));
    } return r; }, providedIn: 'root' });
```

And When I run without `new Optional()` the code must throw error
I guess  in `ɵprov` member, `factory` use ɵɵinject not remove decorator instance so make error

### Please provide a link to a minimal reproduction of the bug

in Description

### Please provide the exception or error you saw
if I remove `new Optional()` throw as follow

```shell
vendor.js:12652 ERROR NullInjectorError: R3InjectorError(AppModule)[AppService -> [aa] -> [aa] -> [aa]]: 
  NullInjectorError: No provider for [aa]!
    at NullInjector.get (vendor.js:17273)
    at R3Injector.get (vendor.js:17439)
    at R3Injector.get (vendor.js:17439)
    at R3Injector.get (vendor.js:17439)
    at injectInjectorOnly (vendor.js:10924)
    at Module.ɵɵinject (vendor.js:10928)
    at Object.AppService_Factory [as factory] (main.js:122)
    at R3Injector.hydrate (vendor.js:17608)
    at R3Injector.get (vendor.js:17428)
    at NgModuleRef$1.get (vendor.js:31530)
defaultErrorLogger @ vendor.js:12652
main.js:179 NullInjectorError: R3InjectorError(AppModule)[AppService -> [aa] -> [aa] -> [aa]]: 
  NullInjectorError: No provider for [aa]!
    at NullInjector.get (vendor.js:17273)
    at R3Injector.get (vendor.js:17439)
    at R3Injector.get (vendor.js:17439)
    at R3Injector.get (vendor.js:17439)
    at injectInjectorOnly (vendor.js:10924)
    at Module.ɵɵinject (vendor.js:10928)
    at Object.AppService_Factory [as factory] (main.js:122)
    at R3Injector.hydrate (vendor.js:17608)
    at R3Injector.get (vendor.js:17428)
    at NgModuleRef$1.get (vendor.js:31530)

```
NgModule
```ts
@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule],
  providers: [{ provide: 'aa', useValue: '11' }],
  bootstrap: [AppComponent],
})
export class AppModule {}
```
### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.0.3
Node: 14.17.1
Package Manager: yarn 1.22.10
OS: darwin x64

Angular: 12.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.3
@angular-devkit/build-angular   12.0.3
@angular-devkit/core            12.0.3
@angular-devkit/schematics      12.0.3
@schematics/angular             12.0.3
ng-packagr                      12.0.5
rxjs                            6.5.5
typescript                      4.2.4
```

### Anything else?

If this is a bug , can i fix by myself?I read source code and can understand part of logic , and want to contribute

**Comment by jnizet** [comment]
It seems you've specified `[['aa']]` as your dependencies instead of `['aa']`. So Angular look for a provider registered with the token `['aa']` instead of `'aa'`.

See https://stackblitz.com/edit/angular-ivy-wh7h4w?file=src%2Fapp%2Fapp.service.ts.

**Comment by alxhub** [comment]
@wszgrcy thanks for the report!

The problem here is that the Angular compiler (which compiles `@Injectable`) and the runtime injector (which handles `{provide: X, useFactory: factoryFn, deps: [...]}` don't use the same structure for `deps`.

The runtime injector will accept `deps: [new Optional(), 'aa']` - anything in this array that isn't an injection flag like `Optional` is considered to be the token to inject.

The compiler, on the other hand, expects all elements to be injection flags, so in your example this would need to be specified as `[new Optional(), new Inject('aa')]`.

I think the compiler is clearly in the wrong here - `[new Optional(), 'aa']` should be legal. We should follow the same logic as the runtime.

If you're interested in taking on this bug yourself, the logic in question is here: https://github.com/angular/angular/blob/master/packages/compiler-cli/src/ngtsc/annotations/src/injectable.ts#L272-L317. It should be relatively readable, but let me know if you have any questions and I'd be happy to explain anything confusing there.

**Comment by wszgrcy** [comment]
> @wszgrcy thanks for the report!
> 
> The problem here is that the Angular compiler (which compiles `@Injectable`) and the runtime injector (which handles `{provide: X, useFactory: factoryFn, deps: [...]}` don't use the same structure for `deps`.
> 
> The runtime injector will accept `deps: [new Optional(), 'aa']` - anything in this array that isn't an injection flag like `Optional` is considered to be the token to inject.
> 
> The compiler, on the other hand, expects all elements to be injection flags, so in your example this would need to be specified as `[new Optional(), new Inject('aa')]`.
> 
> I think the compiler is clearly in the wrong here - `[new Optional(), 'aa']` should be legal. We should follow the same logic as the runtime.
> 
> If you're interested in taking on this bug yourself, the logic in question is here: https://github.com/angular/angular/blob/master/packages/compiler-cli/src/ngtsc/annotations/src/injectable.ts#L272-L317. It should be relatively readable, but let me know if you have any questions and I'd be happy to explain anything confusing there.

I think so.And try to make it more robustness.
