### ISSUE TITLE
Module parse failed: Identifier 'ɵngcc0' has already been declared

### ISSUE THREAD

**Issue by SnowFall98** [angular/angular#42993]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

I'm doing a personal project but at the moment of using: import {NgForm} from '@ angular / forms'; The error appears, I've tried the command of "npm ci" and then re-installing node_modules, update the Node but the problem persists. I did the respective validation in app.module.ts when importing the library but the problem still persists. Any help, guidance or advice I really appreciate.

### Please provide a link to a minimal reproduction of the bug

https://www.mediafire.com/file/dvdrdxp29lokddk/20210729_195935.mp4/file

### Please provide the exception or error you saw

```true
Failed to compile.

./node_modules/@angular/forms/__ivy_ngcc__/fesm2015/forms.js 27:12
Module parse failed: Identifier 'ɵngcc0' has already been declared (27:12)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders.
|  */
| import * as ɵngcc0 from '@angular/core';
> import * as ɵngcc0 from '@angular/core';
| const NG_VALUE_ACCESSOR = new InjectionToken('NgValueAccessor');
|
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.1.3
Node: 14.17.3
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.3
@angular-devkit/build-angular   12.1.3
@angular-devkit/core            12.1.3
@angular-devkit/schematics      12.1.3
@schematics/angular             12.1.3
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by petebacondarwin** [comment]
@SnowFall98 - sorry for the delay in getting back to you. It is not clear to me why this file is being updated by ngcc twice.
Is it possible that there are multiple projects referencing the same node_modules?
In order to help to resolve this issue, I would need to have access to a reproduction.

**Comment by SnowFall98** [comment]
@petebacondarwin Hello, it turns out that there were failures with the node_modules and therefore it did not allow me to use the function, already after updating again it works perfectly.
Thank you very much for the help.

**Comment by petebacondarwin** [comment]
Thanks for the update. Glad it is working for you now.
