### ISSUE TITLE
@private should work for classes

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#4301]
```
/** @private */
export class MyClass {}
```

MyClass should appear neither in the d.ts file nor in the docs.

@IgorMinar

**Comment by mhevery** [comment]
if you don't want it then don't export it. I think `@private` is only meant for hiding parts of the implementation.

**Comment by IgorMinar** [comment]
there was a case where it was not possible to not reexport the class. @vsavkin what was the exact scenario?
