### ISSUE TITLE
Broken example for adding ProductAlertsComponent

### ISSUE THREAD

**Issue by TomCats** [angular/angular#43020]
### Description

Broken step in the 'Pass data to child component' section of the getting started guide.  In order to fix this, I had to modify app.module.ts to import the additional component.  Perhaps this is something that stackblitz.com used to do automatically when using the Angular Generator.

I added:

added line 9: import { ProductAlertsComponent } from './product-alerts/product-alerts.component';
changed line 22: ProductListComponent --> ProductListComponent,  (added a comma)
added line 23: ProductAlertsComponent

### What is the affected URL?

https://angular.io/start

### Please provide the steps to reproduce the issue

I followed the steps under 'Pass data to child component' where during step 6 the example breaks. 

### Please provide the exception or error you saw

```true
Error in src/app/product-list/product-list.component.html (21:3)
'app-product-alerts' is not a known element:
1. If 'app-product-alerts' is an Angular component, then verify that it is part of this module.
2. If 'app-product-alerts' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

**Comment by vugar005** [comment]
related #43053

**Comment by JoeKrupinsky** [comment]
I managed to get past this by adding ProductAlertsComponent to the declarations in app.module.ts after some googling.
![image](https://user-images.githubusercontent.com/68128086/128612496-353651e0-d5d7-40bd-be95-bb1c400b770e.png)

**Comment by majew7** [comment]
Yes, I ran into the error `'app-product-alerts' is not a known element:` as well today.
I too fixed it by manually editing `app.module.ts`

**Comment by Zheng7426** [comment]
I have encountered this problem as well. Thanks for the tip to add the declaration inside app.module.ts.
