### ISSUE TITLE
SwUpdate#checkForUpdate promise not triggered on iOS

### ISSUE THREAD

**Issue by vcs38** [angular/angular#43029]
Hi,

On any devices, this code on my application works well except on iOS devices where promise is never resolved nor rejected:
`this.swUpdate.checkForUpdate().then(() => {
      console.log('test OK');
    },
      () => {
        console.log('test KO');
      });`

I can not understand why. 

Thanks for your help.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
