### ISSUE TITLE
docs: investigate whether Web Animations polyfill is still needed

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#43035]
Currently we recommend adding Web Animations polyfill in case `AnimationBuilder` is used, see:
https://angular.io/guide/browser-support#optional-browser-features-to-polyfill

Investigate whether this is still needed, since according to the https://caniuse.com/web-animation, in all supported browsers (starting from Angular v13 where we drop IE 11 support) all the necessary features are supported.

**Comment by AndrewKushnir** [comment]
Based on the https://caniuse.com/web-animation the only unsupported feature of Web Animations is t[he "composite" option](https://css-tricks.com/additive-animation-web-animations-api/#a-new-option) (unsupported in Safari). However it looks like this option is [unused in WebAnimations inside `@angular/animations`](https://github.com/angular/angular/blob/master/packages/animations/browser/src/render/web_animations/web_animations_driver.ts#L56-L61). So it should be ok to drop the Web Animations polyfill.

**Comment by clydin** [comment]
If this polyfill is no longer needed, there are also several potential additional actions that could be considered:
1) Remove mention of the polyfill from a newly generated project's `polyfills.ts` file ([code](https://github.com/angular/angular-cli/blob/7dcfffafff6f3d29bbe679a90cdf77b1292fec0b/packages/schematics/angular/application/files/src/polyfills.ts.template#L21-L26)).
2) Create an update migration that removes usage of the polyfill from existing project's `polyfills.ts` file

**Comment by ZituzZ34** [comment]
Hey,l I prepare a doc for this issue
