### ISSUE TITLE
createUrlTree create a infinite  loop from while craete Url from rootpath

### ISSUE THREAD

**Issue by Prabin1111** [angular/angular#43040]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I have created a public and secured layout on UI 
one is secured and another is public guard 

i can move from secured to public if is there is not token  but not form public to secured if there is token in localhost

so it have different routing from root 
`
const routes: Routes = [
  {
    path: '',
    loadChildren: () =>
      import('@publicLayout/public.module').then(
        (module) => module.PublicModule
      ),
    canLoad: [CanLoadPublicGuard],
  },
  {
    path: securedPageInitials,
    loadChildren: () =>
      import('@securedLayout/secured.module').then(
        (module) => module.SecuredModule
      ),
    canLoad: [CanLoadSecuredGuard],
  },
];
`

secured guard
`export class CanLoadSecuredGuard implements CanLoad {
  constructor(
    private _navigationService: NavigationService,
    private _localStorageService: LocalStorageService,
    private _authentication: AuthenticationService,
  ) {}
  canLoad(
    route: Route,
    segments: UrlSegment[]
  ):
    | Observable<boolean | UrlTree>
    | Promise<boolean | UrlTree>
    | boolean
    | UrlTree {
    return this.isLoggedIn();
  }
  isLoggedIn(): boolean | UrlTree {
    console.log('isLoggedIn sdhfhdskj');
    if (this._authentication.checkLogin()) {
      return true;
    }
    this._authentication.logout();
    this._localStorageService.clear();
    return this._navigationService.createUrlTree([loginPage]);
  }
}`

public guard
`
export class CanLoadPublicGuard implements CanLoad {
  constructor(
    private _navigationService: NavigationService,
    private _localStorageService: LocalStorageService,
    private _authentication: AuthenticationService,
  ) {}
  canLoad(
    route: Route,
    segments: import('@angular/router').UrlSegment[]
  ):
    | Observable<boolean | UrlTree>
    | Promise<boolean | import('@angular/router').UrlTree>
    | boolean
    | UrlTree {
    return this.isLoggedOut(route);
  }
  isLoggedOut(route: Route): boolean | UrlTree {
    if (this._authentication.checkLogin()) {
      console.log('isLoggedOut sdhfhdskj');
      return this._navigationService.createUrlTree(['/main']);
    }
    return true;
  }
}`

### Please provide the exception or error you saw

```true
create a infinite loop from while craete Url from rootpath so i had console on public gurad its was loop infinite time
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.1.1
Node: 14.17.2
Package Manager: npm 6.14.13
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1201.1 (cli-only)
@angular-devkit/core         12.1.1 (cli-only)
@angular-devkit/schematics   12.1.1 (cli-only)
@schematics/angular          12.1.1 (cli-only)
```

**Comment by Prabin1111** [comment]
@atscott 
Step to reproduce 
 1 Set value in local-storage with key-name "access_token"
2 Now try to move to secure layout by adding url "/main" in url section like  http://localhost:4200/main
3 ckeck the console log i had added one log to watch the gurad


github repo link 
[https://github.com/Prabin1111/angular-createUrlTree-](url)

**Comment by atscott** [comment]
This doesn't appear to be an issue with Angular. Your canLoad guard continuously redirects to main, which runs the canLoad, which redirects to main, which runs the canLoad, ad-infinitum.
