### ISSUE TITLE
Unable to get query string value using $location in angular.js 1.4.6.

### ISSUE THREAD

**Issue by subhrajyotiw5rtc** [angular/angular#4305]
Hi, i have a big issue here.I have a URL like this ```localhost://phpdemo/edit_data.php?edt_id=1```.Here i need the query string value ```i.e-1```.I used two process such as 1) $location.search() 2) $location.search()['edt_id'] but did not get any required value in browser's console.I am explaining my code below.

```
var app=angular.module("edit_data", []);
app.controller("updateController",function($scope,$http,$location){
	$scope.errors = [];
    $scope.msgs = [];
	var id=$location.search();
	console.log("id is :",id);
	$http.get('js/edit.php',{"user_id":$location.hash()}).success(function(response){
		console.log('response',response);
	});
	$scope.update_data=function(){
		$http.post('js/update.php',{"first_name":$scope.first_name,"last_name":$scope.last_name,"city":$scope.city}
		).success(function(data, status, headers, config){
			if(data.msg!=''){
			$scope.msgs.push(data.msg);
			}else{
				$scope.errors.push(data.error);
			}
		}).error(function(data, status) { // called asynchronously if an error occurs
               // or server returns response with an error status.
              $scope.errors.push(status);
        });
	}
});
```
Please help me to resolve this issue and find out the required value.

**Comment by gdi2290** [comment]
this is the Angular 2 repo. could you create an issue in the Angular 1 repo?
https://github.com/angular/angular.js

**Comment by pkozlowski-opensource** [comment]
As @gdi2290 pointed out, this is wrong repo. Having said this I _suspect_ that you are using #-mode for routing and want to read server-side request params using client-side routing API, which obviously won't work. I would suggest that you carefully go over https://docs.angularjs.org/guide/$location and ask support questions using one of the support channels (https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question)

Closing, this question doesn't belong to the GitHub issue.
