### ISSUE TITLE
Unexpected value 'Base64Validator' declared by the module 'CustomFormsModule'. Please add a @Pipe/@Directive/@Component annotation.

### ISSUE THREAD

**Issue by pramodhk** [angular/angular#43050]
I upgrade angular 6 to angular 9 after upgrade thhis issue coming

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
