### ISSUE TITLE
Angular Material Demos in stackblitz are broken

### ISSUE THREAD

**Issue by borangecpn** [angular/angular#43069]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When pulling up the examples of how to use various components in the Angular Materials guide, every one of them that I pulled up doesn't work. Having clean, clear, easy to understand demos to see how to code these examples is vital. I'd really like to use the Angular Materials to style my application, instead of getting a third party library or using bootstrap. However, if what you demonstrate doesn't work properly and can't be rendered, then it's really difficult for me to take the time to learn how to use this code with my application. This same error appears in literally every example I tried to view in stackblitz.

![AngularMaterialStackblitzExamplesBroken](https://user-images.githubusercontent.com/40000549/128565748-170d6d14-6f31-411e-b7c8-28924408eee6.png)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/angular/lppbjloxpgg?file=src%2Fapp%2Fsidenav-open-close-example.ts

### Please provide the exception or error you saw

```true
Error in turbo_modules/@angular/material@12.2.0/table/table-module.d.ts (8:22)
Appears in the NgModule.exports of DemoMaterialModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class.

This likely means that the dependency (@angular/material/table) which declares MatTableModule has not been processed correctly by ngcc.
```

### Anything else?

I tired to search for a similar error in reported bugs but did not see one.

**Comment by rafaelss95** [comment]
I guess you reported it in the wrong repository and there's already an open issue in correct one: https://github.com/angular/components/issues/23270.

**Comment by JoostK** [comment]
Thanks @rafaelss95, let's keep the discussion in one place in angular/components#23270. Unfortunately it looks like it was expected that the 12.2.0 artefacts would not show this error but apparently it's broken for 12.2 as well.
