### ISSUE TITLE
 canLoad guard continuously redirects

### ISSUE THREAD

**Issue by Prabin1111** [angular/angular#43063]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I have created a public and secured layout on UI 
so created 2 can-load guard
one is secured and another is public guard

guard check for simple condition is there token or not  from authservice 
and created a createUrlTree as condition  but found out canLoad guard continuously call same method 

Step to reproduce
1 Set value in local-storage with key-name "access_token"
2 Now try to move to secure layout by adding url "/main" in url section like http://localhost:4200/main
3 ckeck the console log i had added one log to watch the gurad

github repo link
https://github.com/Prabin1111/angular-createUrlTree-

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.1.1
Node: 14.17.2
Package Manager: npm 6.14.13
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1201.1 (cli-only)
@angular-devkit/core         12.1.1 (cli-only)
@angular-devkit/schematics   12.1.1 (cli-only)
@schematics/angular          12.1.1 (cli-only)
```

**Comment by flash-me** [comment]
Hi @Prabin1111,

Your issue: Your `CanLoadPublicGuard` is set on a path with the route ''. This results that the `CanLoadPublicGuard` will be called on every route.
You can this by setting the `pathMatch` property

**Comment by Prabin1111** [comment]
@flash-me Thank you
