### ISSUE TITLE
Significantly slower animations when using * or % as width/height/translateX/Y pos.

### ISSUE THREAD

**Issue by And2s** [angular/angular#43072]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

No

### Description

Slow, when using percentage or * (as width/height):
` style({ transform: 'translateY(100%)' }), animate(`250ms ease`, style({transform: 'translateY(0)'})),`

Fast, when using fixed size:
` style({ transform: 'translateY(400px)' }), animate(`250ms ease`, style({transform: 'translateY(0)'})),`

The slower animations are very noticeable on >=120HZ screen.

Also, I have noticed it is slower when container has many elements. It does not matter if elements has any content. For example, using percentage sizes animation will be slower if container contains something like `<div *ngFor="let i of [0,0,0,0,0,0,0,0,0,0,0]"></div>`, on the other hand it will be will be fast  if container is empty. Seems like when using percentage sizes there is some kind of heavy calculation to determine height/width and it causes laggy animations. 

I have tested on Safari and Chrome, same behavior. For me, animations seems much much smoother when using fixed sizes instead of percentage. I don't know if it is Angular specific or if it is a bug. I would name it some kind of performance issue.

### Please provide the environment you discovered this bug in

```true
Chrome, Safari
Angular 12
```

**Comment by pkozlowski-opensource** [comment]
> I don't know if it is Angular specific or if it is a bug. I would name it some kind of performance issue.

Could you please try to create a stackblitz with the exact scenario so we are sure that we are talking about / debugging the same use-case?

**Comment by flash-me** [comment]
FYI: There is a similar question on SO. 
https://stackoverflow.com/questions/50409008/css-transform-transition-using-%C2%B4px%C2%B4-more-smooth-performant-than-percentage

Probably not related to Angular, but to CSS / Browser Rendering in general?

cheers
flash ⚡

**Comment by alxhub** [comment]
Closing as no reproduction was provided - feel free to reopen with a reproduction if this is still an issue for you.
