### ISSUE TITLE
Template variables: contradiction about references (scope)

### ISSUE THREAD

**Issue by Chealer** [angular/angular#43071]
### Description

[The _Syntax_ section of the _Template variables_ page](https://angular.io/guide/template-reference-variables#syntax) contains:

> Refer to a template variable anywhere in the component's template.

This should probably be removed, as it contradicts the _Template variable scope_ section, which already contains an equivalent statement:

> Refer to a template variable anywhere within its surrounding template.

By the way, the following statement from same page has strange phrasing, to say the least:

> The following template variable, #phone, declares a phone variable on an <input> element.

### What is the affected URL?

https://angular.io/guide/template-reference-variables#syntax

### Please provide the steps to reproduce the issue

This does not report a behavioral bug.

### Please provide the expected behavior vs the actual behavior you encountered

This does not report a behavioral bug.

### Please provide the exception or error you saw

```true
This does not report a behavioral bug.
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
No
```

**Comment by AndrewKushnir** [comment]
Hi @Chealer, thanks for reporting the issues (I noticed you've also created #43070 and #43068) 👍 Please let us know if you might be interested in contributing and creating a PR to address them - we'll be happy to review and accept a PR that would improve docs. Thank you.

**Comment by subson** [comment]
Hi there, created a PR to remove the line - #43182

**Comment by AndrewKushnir** [comment]
Closing this issue based on https://github.com/angular/angular/pull/43182#issuecomment-899930123.
