### ISSUE TITLE
Optional `params` argument in create method of KeyValueDifferFactory and IterableDifferFactory

### ISSUE THREAD

**Issue by bharathm03** [angular/angular#4307]
Apart from `ChangeDectorRef`, it is better to have optional `params` argument in the `create` method of `DifferFactory`. This could be useful in sending additional settings to Factory for creating customized Differ while using custom DifferFactory. 

Also it could be useful to make `DefaultIterableDiffer` and `DefaultKeyValueDiffer` public.

**Comment by mhevery** [comment]
Could you provide a concrete use case?

**Comment by bharathm03** [comment]
Hi mhevery

I’m developing custom component in angular2. For change detection, I’m writing custom Differ which will merge some features of KeyValue and Iterable differs. For ex, refer following object, differ can detect the changes in name, hobbies and city & country in knownAddresses. 
```javascript
var person  = {
	name: 'Bob',
	hobbies: ['Sports', 'Reading'],
	knownAddresses: [{
			city: 'NY',
			country: 'US'
		}, {
			city: 'NC',
			country: 'US'
		}]
}
```
For this differ, I need an extra parameter like `detectLevel`, which I will use to determine how deep the change detector should watch for changes. If you have any other ideas please share.

Thanks 
Bharath

**Comment by mhevery** [comment]
@bharathm03 Why don't you just subclass the differ or create your own, and then override it in the `bindings`?

I think this is better left for third parties rather then the core.
