### ISSUE TITLE
DebugElement.classes not working without Ivy enabled

### ISSUE THREAD

**Issue by platon-rov** [angular/angular#43074]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

If the application runs the View Engine (not Ivy) then `DebugElement.classes` not working, but there are no notices about that.

```
@Component({
  selector: 'app-root',
  template: `<div class="custom"></div>`
})
export class AppComponent {
  title = 'my-app';
}

// Specs

it('should query', () => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();

    const customDe = fixture.debugElement.query(By.css('.custom'));

    console.log(customDe.nativeElement.classList); // DOMTokenList {0: 'custom'}
    console.log(customDe.classes['custom']); // undefined

    expect(customDe.classes['custom']).toBeTrue();
  });
  ```

### Please provide the exception or error you saw

```true
Error: Expected undefined to be true.
    at <Jasmine>
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/app/app.component.spec.ts:29:40)
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:364:1)
    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:292:1)
```

### Please provide the environment you discovered this bug in

```true
Angular 8 up to 12.
```

### Anything else?

https://angular.io/api/core/DebugElement

**Comment by crisbeto** [comment]
Did this used to work for you? My understanding is that the `DebugElement.classes` in ViewEngine only works for class bindings like `[class.custom]="true"`.

**Comment by AndrewKushnir** [comment]
Closing this ticket since it was marked as ViewEngine-specific and ViewEngine is deprecated. Please reopen if the problem still exists in the latest version of Angular (powered by Ivy).
