### ISSUE TITLE
Extended Directive: Parent host properties not applied to child

### ISSUE THREAD

**Issue by platon-rov** [angular/angular#43084]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When extending directive with `host: { ... }` properties set and not overriding them in child directive - these host properties applied if an app runs Ivy, but not View Engine.

#### Obsesses behavior (View Engine):
<img width="819" alt="Screenshot 2021-08-09 at 15 34 30" src="https://user-images.githubusercontent.com/20265336/128700213-e84c306f-12d4-4b24-ab25-15baf8580477.png">

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-fzrgqt?file=src/app/app.component.ts

### Please provide the environment you discovered this bug in

```true
* Angular 12.1.0;
* StackBlitz.
```

**Comment by JoostK** [comment]
This is mentioned in [the Ivy compatibilty guide](https://angular.io/guide/ivy-compatibility):

> Properties like host inside @Component and @Directive decorators can be inherited (previously, only properties with explicit field decorators like @HostBinding would be inherited).

FYI: View Engine is deprecated and its behavior will not be changed at this point.

**Comment by eneajaho** [comment]
```
@HostBinding('class.app-custom') setClass() {
   return true;
}
```
Something like this would work on ViewEngine.
