### ISSUE TITLE
Binding datepicker to formgroup

### ISSUE THREAD

**Issue by anup0001-kj** [angular/angular#43082]
![image](https://user-images.githubusercontent.com/57554437/128669324-7921e745-90cb-4f95-920f-f7a41d63ae63.png)

Once we bind datepicker to formgroup, dates are less by one day on the binded object.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).
