### ISSUE TITLE
Angular 12 warning ./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by amer-yousuf** [angular/angular#43092]
I'm getting these warnings after ng build (Angular 12):

```
./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:35289:13-34 - Warning: Critical dependency: the request of a dependency is an expression

./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:35301:13-100 - Warning: Critical dependency: the request of a dependency is an expression
```

I'm using @angular-builders/custom-webpack to extract the moment.js from the initial bundle.

**If I disabled the @angular-builders/custom-webpack, then everything goes well and the warnings disappear.**

Also, the warnings disappeared if I add the following within custom-webpack.config.js:

```
new webpack.ContextReplacementPlugin(
    /\@angular(\\|\/)core(\\|\/)__ivy_ngcc__(\\|\/)fesm2015/,
    path.join(__dirname, './src'),
    {}
),
```
So kindly, what causing these warnings exactly? and is there any other solution to handle it without adding the plugin to the webpack config like above? Thanks.

**Comment by JoostK** [comment]
This comes from code in the deprecated [`SystemJsNgModuleLoader`](https://github.com/angular/angular/blob/12.2.x/packages/core/src/linker/system_js_ng_module_factory_loader.ts) and is normally suppressed [when using the CLI builders](https://github.com/angular/angular-cli/blob/12.2.x/packages/angular_devkit/build_angular/src/webpack/configs/common.ts), which also uses `ContextReplacementPlugin`. I don't think there is an alternative to suppress them, other than to not suppress them and ignore the warnings.
