### ISSUE TITLE
feat(language-service): ability to view AST for a template

### ISSUE THREAD

**Issue by atscott** [angular/angular#43090]
Like https://astexplorer.net/, it would be nice to have the ability to view the AST of a template. This would help get a quicker understanding of the AST structure when working with the compiler. It would help ramp up new contributors as well. Currently, the only way to really look at the AST would be to step into a test and pause in the debugger after the AST  is created.

**Comment by JoostK** [comment]
Did you know that AST Explorer does allow using the Angular parser?

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/123679/128754846-c2feaa3f-80ea-43b4-9e57-b26fc2d124eb.png">

It's not the latest version though.

**Comment by atscott** [comment]
> Did you know that AST Explorer does allow using the Angular parser?

Oh wow, I did _not_ know that! Closing this since I don't think this is important enough to duplicate the work that's already been done there.
