### ISSUE TITLE
getting started doc small typo mistake

### ISSUE THREAD

**Issue by echonax** [angular/angular#4311]
"live-server --open src" in the getting started section (Run it!) should be "live-server --open=src"

**Comment by PascalPrecht** [comment]
@echonax thanks! Do you mean the getting started guide on angular.io?

**Comment by echonax** [comment]
@PascalPrecht yes exactly, the typescript part. I thought I should point that out just to save people a couple of seconds :)

**Comment by PascalPrecht** [comment]
Could you file that issue over at http://github.com/angular/angular.io then?

Thanks!

**Comment by mhevery** [comment]
Dup of https://github.com/angular/angular.io/issues/219
