### ISSUE TITLE
Observable is returning a wrong-sounding 'Event_2' type

### ISSUE THREAD

**Issue by jetxr** [angular/angular#43124]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

`router.events` Observable is returning a 'Event_2' type [in the API](https://github.com/angular/angular/blob/master/goldens/public-api/router/router.md)

This seems like an issue with the API Generator. It's causing autocomplete to hint and add the wrong 'Event_2' type to code.

### Please provide a link to a minimal reproduction of the bug

https://github.com/angular/angular/blob/master/goldens/public-api/router/router.md

### Please provide the exception or error you saw

```true
`readonly events: Observable<Event_2>;`
```

**Comment by JoostK** [comment]
The API files over at https://github.com/angular/angular/blob/master/goldens/public-api/router/router.md exist to guard the public API surface; it's not used nor published in the `@angular/router` NPM package.

What you are seeing is the https://unpkg.com/browse/@angular/router@12.2.1/router.d.ts file. That declaration file has also been created by API Extractor and also includes the `Event_2` name, but that is its internal name only. The public export is `Event`, so autocomplete tooling that suggests `Event_2` is wrong.

This behavior ultimately comes from [API Extractor](https://api-extractor.com/), a tool that is used to flatten declaration files. If you think this is a real problem then I'd suggest opening an issue in their repo.

**Comment by jetxr** [comment]
Thanks @JoostK, you're right about it being an issue with the autocomplete to try and add add unexported `Event_2`.

It's definitely a real issue, because the hinting itself* is going to lend to folks adding `Event_2` to their own docs/code comments.

I agree that API Extractor should be smarter here to use the exported type name if available instead of an inaccessible internal type. I'll open an issue in the API Extractor project.

As a stop gap, is it possible to make the Observable return the `Event` type? It would be straightforward for every tool's logic to  get it right..

*Insofar as any type hinting logic is concerned, it would not be the prerogative of the tool to resolve internal types to available exported ones, the internal types can be exported multiple times with different names or not at all.

**Comment by intellix** [comment]
I'm getting this error whilst trying to use [untilDestroyed()](https://github.com/ngneat/until-destroy):

```
Type 'Observable<Event_2>' is not assignable to type 'Observable<RouterEvent>'.
  Type 'Event_2' is not assignable to type 'RouterEvent'.
    Type 'RouteConfigLoadStart' is missing the following properties from type 'RouterEvent': id, url
```

**Comment by petebacondarwin** [comment]
@intellix - this sounds more like there are two versions of the `Router` typings in your compilation scope. What versions of Angular and the `until-destroy` package are you using?

**Comment by debugmodedotnet** [comment]
Hi , 

I am getting the same issues with the Event_2  type for RouterEvent. How could we possibly fix it?


` this.router.events.pipe(
      filter((e:Event): e is RouterEvent => e instanceof RouterEvent)).subscribe(
        (e:RouterEvent)=>{

        })
    )`

**Comment by LorenzoCruccu** [comment]
I'm sharing the workaround that worked for me:
the error:
```
	this.router.events.filter(event => {
			// do something
		       return event instanceof NavigationEnd;
			})

```
that generates:

>  Property 'filter' does not exist on type 'Observable<Event_2>


Basically wrapping filter function of rxjs inside the pipe function:

```
	this.router.events.pipe(filter(event => {
		        // do something
			return event instanceof NavigationEnd;
		}))
```

**Comment by kirilmaz** [comment]
Hi,

I have the same issue. "Event_2" type for "RouterEvent".

<img width="590" alt="Screenshot 2023-06-16 at 15 51 10" src="https://github.com/angular/angular/assets/16680133/95fccf1c-019a-48ce-ac2d-fe2b25758951">

**Comment by adrian-stroe** [comment]
Has anyone come up with a solution for this or workaround ? @LorenzoCruccu 's workaround was not working for me, I am using .filter inside .pipe and this eslint type annotation missing is bugging me

**Comment by kirilmaz** [comment]
This one worked for me but I haven't tested yet. Sorry for not sharing.

<img width="933" alt="Screenshot 2023-06-26 at 13 44 33" src="https://github.com/angular/angular/assets/16680133/6bdbe15d-6ed3-4039-a929-59721f13ab1e">

**Comment by adrian-stroe** [comment]
> > This one worked for me but I haven't tested yet. Sorry for not sharing.
> > <img alt="Screenshot 2023-06-26 at 13 44 33" width="933" src="https://user-images.githubusercontent.com/16680133/248769333-6bdbe15d-6ed3-4039-a929-59721f13ab1e.png">
> 
> Thanks for replying so fast, nice to see people do that here, I tried that and it seems to be working.
> 
> What also seems to be working is just use `Event` instead of `Event_2` the only thing that I haven't noticed was that when writing `Event` the auto import wouldn't trigger for me so if you find yourself in my situation make sure to ` import { Event } from '@angular/router';`

**Comment by IvanAmdaris** [comment]
I very rarely write here. So my solution was a bit dumber than that:
`
this.router.events
      .pipe(
        filter((event) => event instanceof NavigationEnd),
        map((e) => e as NavigationEnd)
      )
`

map will only hit after the filter here, so we just trick to return it as NavigationEnd type.

**Comment by JeanMeche** [comment]
@IvanAmdaris You can drop the `map()` and use a predicate instead ! 

```
const events = this.router.events.pipe(
  filter((event): event is NavigationEnd => event instanceof NavigationEnd),
);
```

**Comment by Tyler-V** [comment]
Nothing in here was working for me, here is what I had to use - kind of odd router.events if of type `Event_2` I even updated angular/core to ^16.2.1 today to confirm

```
        this.router.events.pipe(
            map((event: any) => event.routerEvent as RouterEvent),
            filter((event): event is NavigationEnd => event instanceof NavigationEnd)
        );
```

**Comment by rolanddeboer** [comment]
I was having a similar issue where
```
import { Event, RouterEvent, NavigationEnd } from '@angular/router';

this.router.events
      .pipe(filter((event: RouterEvent) => event instanceof NavigationEnd))
```

produced the following error during build:

```
Error: src/app/_services/config/route-params.service.ts:25:13 - error TS2345: Argument of type 'MonoTypeOperatorFunction<RouterEvent>' is not assignable to parameter of type 'OperatorFunction<Event_2, RouterEvent>'.
  Types of parameters 'source' and 'source' are incompatible.
    Type 'Observable<Event_2>' is not assignable to type 'Observable<RouterEvent>'.
      Type 'Event_2' is not assignable to type 'RouterEvent'.
        Type 'ActivationEnd' is missing the following properties from type 'RouterEvent': id, url

25       .pipe(filter((event: RouterEvent) => event instanceof NavigationEnd))
```

In the [Angular Update Guide](https://update.angular.io/?l=2&v=15.0-16.0), one of the bullet points for updating an app from Angular 15 to 16 is:
- The Event union no longer contains RouterEvent, which means that if you're using the Event type you may have to change the type definition from (e: Event) to (e: Event|RouterEvent)

Following this guidance, I changed the line from
```
.pipe(filter((event: RouterEvent) => event instanceof NavigationEnd))
```
to
```
.pipe(filter((event: Event|RouterEvent) => event instanceof NavigationEnd))
```
and this resolved the issue for me.

**Comment by CSchulz** [comment]
Just my two cents about this issue, the `Event` type is part of the router package and furthermore it could be possible you need also a type guard to be able to use that event later.

import { Event, RouterEvent, NavigationEnd } from '@angular/router';

```
this.router.events.pipe(
  filter(
    (event: RouterEvent): event is NavigationEnd => event instanceof NavigationEnd)
  ),
  map(event: NavigationEnd) => ...

```

**Comment by sparklineIT** [comment]
+1

**Comment by narendrasinghrathore** [comment]
```
import { Event, RouterEvent, NavigationEnd } from '@angular/router';

this.router.events
  .pipe(
    untilDestroyed(this),
    filter((event: Event | RouterEvent) => event instanceof NavigationStart),
    tap(() => this.dialogRef.close()),
  )
  .subscribe();
```

**Comment by CaiCharles01** [comment]
Angular source code:
`declare type Event_2 = NavigationStart | NavigationEnd | NavigationCancel | NavigationError | RoutesRecognized | GuardsCheckStart | GuardsCheckEnd | RouteConfigLoadStart | RouteConfigLoadEnd | ChildActivationStart | ChildActivationEnd | ActivationStart | ActivationEnd | Scroll | ResolveStart | ResolveEnd | NavigationSkipped;
export { Event_2 as Event }`
Before use `event: Event | RouterEvent` we need to `import Event from '@angular/router'`

**Comment by jensonraby91** [comment]
**V16**

  this._router.events
          .pipe(
            filter((evt: Event | RouterEvent): boolean => {
              return evt instanceof NavigationEnd;
            }),
            take(1)
          )
          .subscribe((): void => {

          });

**Comment by JeanMeche** [comment]
`Router. events` returns a type `Event`.  `Event` is a union type that includes types that extend `RouterEvent` but not only. `ChildActivationEnd` or `Scroll` events do not extend `RouterEvent`. 

Using `RouterEvent` as a type for `Router.event` is wrong. Please use `Event` and narrow the type as you fit your needs. 

Btw the ts extractor probably creates a `Event_2` name to prevent coliding with the native `Event` type.
