### ISSUE TITLE
is not a known element

### ISSUE THREAD

**Issue by v1d3rm3** [angular/angular#43121]
### Which @angular/* package(s) are the source of the bug?

common, Don't known / other

### Is this a regression?

No

### Description

I have the app module with a async route to other module. A component of this async module calls a component of a third module. The component of main module gives no problem when calling the third module, but the async module gives an error.

### Please provide a link to a minimal reproduction of the bug

https://github.com/v1d3rm3/ng-test-bug

### Please provide the exception or error you saw

```true
error NG8001: 'app-button' is not a known element:
1. If 'app-button' is an Angular component, then verify that it is part of this module.
2. If 'app-button' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.1
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.2.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.1
@angular-devkit/build-angular   12.2.1
@angular-devkit/core            12.2.1
@angular-devkit/schematics      12.2.1
@schematics/angular             12.2.1
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Additional comment: I've looked at the code and found out that the `ButtonComponent` component is declared in [the `ButtonModule` module](https://github.com/v1d3rm3/ng-test-bug/blob/31d56419094849d14c0ccfb8de77c316f94a575d/src/app/components/button/button.module.ts#L6), but that module is not imported anywhere, which is likely an issue.

**Comment by v1d3rm3** [comment]
Thanks, @AndrewKushnir.
Just one thing, the ButtonModule is imported in [DesignSystem module](https://github.com/v1d3rm3/ng-test-bug/blob/31d56419094849d14c0ccfb8de77c316f94a575d/src/app/design-system/design-system.module.ts), and then it's used in [design-system.component.html](https://github.com/v1d3rm3/ng-test-bug/blob/31d56419094849d14c0ccfb8de77c316f94a575d/src/app/design-system/design-system.component.html). Could it be a bug?

**Comment by v1d3rm3** [comment]
@JoostK It's being imported here [app-routing.module.ts](https://github.com/v1d3rm3/ng-test-bug/blob/31d56419094849d14c0ccfb8de77c316f94a575d/src/app/app-routing.module.ts). Lazy loading

**Comment by JoostK** [comment]
Nope that is only the routing module!

**Comment by JoostK** [comment]
The problem you're seeing is because your lazily loaded NgModule is only concerned with routing; the component scope is managed by `DesignSystemModule` but that particular file is not imported from anywhere.

You can either join together `DesignSystemModule` and `DesignSystemRoutingModule` into a single NgModule, _or_ add `DesignSystemModule` to the `@NgModule.imports` of `DesignSystemRoutingModule`.
