### ISSUE TITLE
Adding libraries to `compilerOptions.paths` break export scope calculation 

### ISSUE THREAD

**Issue by blidblid** [angular/angular#43139]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

No

### Description

I have one app and two libraries:

- app
  - child
  - parent

When I only link parent and not child through `compilerOptions.paths`

```
    "paths": {
      "parent": [
        "projects/parent/src"
      ]
    }
```   

and run `ng s`, I get an error:

> Error: Debug error: DtsModuleScopeResolver.read(ParentModule from C:/workspace/partial-link/projects/parent/src/lib/parent.module.ts), but not a .d.ts file

It seems that when calculating export scope, the recursive calls inside `MetadataDtsModuleScopeResolver.resolve` do not check whether `ref` is a type declaration or a module. So when `ParentModule` is linked through `compilerOptions.paths`, the compilation of `ChildModule` will incorrectly call `resolve` as if `ParentModule` was a type declaration.

If there's a check if `ref` is a type declaration before the recursive call to `resolve`, and `LocalModuleScopeRegistry.getScopeOfModuleReference` gets called instead, then the app works without error.

 

### Please provide a link to a minimal reproduction of the bug

https://github.com/blidblid/partial-link

### Please provide the exception or error you saw

```true
Error: Debug error: DtsModuleScopeResolver.read(ParentModule from C:/workspace/partial-link/projects/parent/src/lib/parent.module.ts), but not a .d.ts file
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.1
Node: 14.16.0
Package Manager: npm 6.14.11
OS: win32 x64

Angular: 12.2.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.1
@angular-devkit/build-angular   12.2.1
@angular-devkit/core            12.2.1
@angular-devkit/schematics      12.2.1
@schematics/angular             12.2.1
ng-packagr                      12.2.0
rxjs                            6.6.7
typescript                      4.3.5
```

### Anything else?

It would be amazing if partially linking libraries worked. If a developer wants to modify parent-library in the above example, they have to link child-library too. This is a big issue for projects with many libraries.

**Comment by flash-me** [comment]
Hi @blidblid,

your `child` library links to `projects/parents/src`, which seems to be causing the error.

I did the following steps:

First, I removed the path mappings in the root `tsconfig.json`.

Second, I added path these mappings to `projects/app/tsconfig.json`
```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "paths": {
      "parent": [
        "projects/parent/src"
      ],
      "child": [
        "projects/child/src"
      ]
    }
  }
}
```

Third, I added a path mapping to `parent` for the `child` project in `projects/child/tsconfig.lib.json`
```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "paths": {
      "parent": [
        "./dist/parent/"
      ]
    }
  }
}
```

With these changes, all builds are successful. Since `child` requires `parent`, you need to build `parent` at first apparently.
Since app maps the paths directly to the sources, it can be build independently.

![image](https://user-images.githubusercontent.com/5240450/129371994-f1455a88-7142-44f4-a0a0-ec61c8568686.png)

I hope this may help you further.

cheers
flash ⚡

**Comment by blidblid** [comment]
Hi @flash-me!

Thanks for looking into this.

What I'm trying to do is actually to run parent-lib linked and child-lib from `node_modules`. I want to get around having to create secondary links to libraries just to run one library linked. The company I work at have tons of libraries, some projects even have 30+ libraries.

I don't know if that's even possible, or if it's supposed to be possible. But in any case, if I add the workaround mentioned in the issue, I can run child out of `node_modules` and parent linked.

**Comment by flash-me** [comment]
Alrighty. Seems there was a similar issue https://github.com/angular/angular/issues/29361 which has been solved already, but occurs again.

cheers
flash ⚡

**Comment by Mihail04** [comment]
Hi. Have same error whe after update angular from 10 to 12 and migrate from "@angular-devkit/build-ng-packagr:build", to  "@angular-devkit/build-angular:ng-packagr". Don’t know affected migration on build-angular:ng-packagr or not.

**Comment by Mihail04** [comment]
i add
 "@angular/*": [ "./node_modules/@angular/*" ],
"@ngrx/*": ["./node_modules/@ngrx/*"],
"@ngx-translate/*": ["./node_modules/@ngx-translate/*"]
in paths and this fix my problem, but i don't know why

**Comment by JoostK** [comment]
This configuration is not supported and we don't intend to support it. The compiler expects that compilation units are in fact "stacked", so linking against source files for an upstream library but not for an intermediate library is not accepted.

We may be able to provide a better error, though.

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
