### ISSUE TITLE
docs: special treatment / template for directive docs

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#4313]
Currently documentation generated for directives is using the same template / contains the same info as any other regular TypeScript class (so all the annotations, constructor, members etc.). While this makes the documentation complete it is not very useful for people using directives in templates. 

Taking the example of the [NgClass directive](https://angular.io/docs/js/latest/api/core/NgClass-class.html) we can see a lot of irrelevant info (or the info only relevant to someone that wants to modify / extend this directive):
* constructor
* members: 
    * property setters (`initialClasses`, `rawClass`)
    * lifecycle hooks (`doCheck`, `onDestroy`)

The only info useful for template authors is present as part of the `Annotations` section, but it is not very readable.

### The proposal

Let's introduce a special template for directives. Such template should _not_ contain the `Members` section. The info contained in the `Annotations` section should be presented differently: we should parse the `@Component / @Directive` decorator and clearly present info relevant to template authors:
* selector
* type of a directive (what I mean here is that we should be able to clearly distinguish structural directives that require `*` or a `template` element 
* properties (as used in a template)
* events (as used in a template) with a place of describing when a given event is fired and what local variables it declares (ex.: `$event`), if any

cc: @naomiblack @IgorMinar @petebacondarwin

**Comment by petebacondarwin** [comment]
I can knock up a PR for this...

**Comment by petebacondarwin** [comment]
Oh and this issue should probably in the https://github.com/angular/angular.io project, since we have moved the doc generation there.

**Comment by pkozlowski-opensource** [comment]
@petebacondarwin glad to hear that it sounds doable :-)

Thinking about the topic some more we've got now `@Property` and `@Event` decorators which probably make things a bit more complex. On the other hand it gives us opportunity to have type information for properties.

Oh, and feel free to move it over to https://github.com/angular/angular.io if this is a better place.

**Comment by pkozlowski-opensource** [comment]
Most of the work on this was done as part of https://github.com/angular/angular.io/pull/221 - thnx @petebacondarwin !

IMO what remains is figuring out the best way of hiding "irrelevant" details:
* "private" variables / methods (those used only internally in a component class / template)
* constructors (?)

The real question here is this: who do we target with those docs: directive users who stick them in a template? Or also people extending directives / calling methods on them.

Somehow a directive class is a combination of a ng1 directive and directive controller. In ng1 we had 2 separate pieces of doc for those different usage patterns. We need to decide what is the best approach for ng2.

**Comment by pkozlowski-opensource** [comment]
@petebacondarwin what would be best way of "hiding" private vars / methods? Would marking them as `private` in TS do the trick? Or do we need `@private` doc annotation?

**Comment by petebacondarwin** [comment]
Currently I don't think the docs hide members marked at `private` in TypeScript - we should probably do that. What we do is hide members that start with `_` - we should probably stop doing that (it was a Traceur thing).

**Comment by pkozlowski-opensource** [comment]
@petebacondarwin OK, I see. So if I understand correctly, the way to go, as of today, would be to add the `@private` doc annotation. Is that right?

**Comment by petebacondarwin** [comment]
Right now we ignore any `@private` tag. We do, though, hide members that are marked with the `@internal` tag. So perhaps this is the way to go.
