### ISSUE TITLE
Show/hide part of the form will not render controls

### ISSUE THREAD

**Issue by alvipeo** [angular/angular#43142]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

This is weird - I have a reactive form with '*Mailing Address*' and '*Business Address*' parts. The latter has a checkbox '_Same as mailing address_'. Here's a code snippet for this part of the form:
```
         <fieldset>
            <legend>Physical Address</legend>
            <div class="two-cols full-w p-1">
               <mat-checkbox #sameAsMailingCb formControlName="sameAsMailingAddr">Same as mailing address</mat-checkbox>
            </div>
            <div *ngIf="!sameAsMailingCb.checked">
               <div class="two-cols">
                  <mat-form-field appearance="fill">
                     <mat-label>State</mat-label>
                     <mat-select required formControlName="ph_state">
                        <mat-option *ngFor="let state of usStates" [value]="state.abbreviation">{{ state.name }}</mat-option>
                     </mat-select>
                     <mat-error *ngIf="isTouchedAndInvalid('ph_state')">{{ getErrorMessage("ph_state") }}</mat-error>
                  </mat-form-field>
                  <mat-form-field appearance="fill">
                     <mat-label>Zip Code</mat-label>
                     <input matInput type="text" formControlName="ph_zipCode" required minlength="5" />
                     <mat-error *ngIf="isTouchedAndInvalid('ph_zipCode')">{{ getErrorMessage("ph_zipCode") }}</mat-error>
                  </mat-form-field>
               </div>
     .........
         </fieldset>
```

So initially this part of the form is shown, no problem here. When I click on a checkbox the form is expanded and controls are there, but they're like invisible! They appear again only if I select something in a dropdown, for example. Please watch the attached video as I can't repro this in stackblitz :( I tried.

I tried this in different browsers and platforms - all the same.

`changeDetection: ChangeDetectionStrategy.OnPush` for the component.

v.12.2.1

https://user-images.githubusercontent.com/1990415/129419045-ee0af56d-f915-4f27-a49a-4904e9934fad.mp4

### Please provide the exception or error you saw

```true
Please see the attached video.
```

### Please provide the environment you discovered this bug in

```true
12.2.1
```

**Comment by alvipeo** [comment]
An addition - if the field under _Physical address_ has a value, everything works as expected. Could this rendering issue be related to validation somehow?

**Comment by AndrewKushnir** [comment]
Hi @alvipeo. Unfortunately it'd not be possible for us to investigate this issue without a repro.

I also noticed that the code which you provided contains a lot of different fields, components and text interpolations. As a possible next step in debugging the issue you could try to simplify the template and keep only the parts that are relevant to the issue (for example, try removing material component and see if the problem still exists).

**Comment by alvipeo** [comment]
ok, I continued the development of this form, just added other fields below and the problem is gone :/ I have no idea what happened. I suppose we may close it now.
