### ISSUE TITLE
Styles not applied properly on content from DomSanitizer

### ISSUE THREAD

**Issue by SiddharthShyniben** [angular/angular#43144]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

If you pass an element with a class through the `DomSanitizer`, and try to style the class, it won't work.

#### For example:

> app.component.ts
```ts
import {Component} from '@angular/core';
import {DomSanitizer} from '@angular/platform-browser';

@Component({
  selector: 'app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor(private sanitizer: DomSanitizer) {}

  getSanitized() {
    return this.sanitizer.bypassSecurityTrustHtml(
      '<span class="foo">Hello World!</span>'
    );
  }
}
```
> app.component.css
```css
.foo {
  color: red;
}
```
> app.component.html
```html
<p [innerHTML]='getSanitized()'></p>
```

If you run this code, the content won't be styled

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-wpqnhp

### Please provide the exception or error you saw

NA

### Please provide the environment you discovered this bug in

```true
❯ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.12
Node: 14.17.0
OS: darwin x64

Angular: 11.2.13
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.12
@angular-devkit/build-angular   0.1102.13
@angular-devkit/core            11.2.12
@angular-devkit/schematics      11.2.12
@angular/cli                    11.2.12
@schematics/angular             11.2.12
@schematics/update              0.1102.12
ng-packagr                      11.2.4
rxjs                            6.6.7
typescript                      4.1.5
```

### Anything else?

NA

**Comment by JoostK** [comment]
This is working as expected. Angular components emulate style encapsulation by default, based on `@Component.encapsulation` defaulting to `ViewEncapsulation.Emulated`. Any HTML that is created outside of Angular will not have gone through the emulation process, which hides those elements from the component's CSS rules.

There are two potential ways to go about this. Either you can switch to `ViewEncapsulation.None`, or change the CSS rules to use the `::ng-deep` selector to escape out of view encapsulation. In your StackBlitz, that would mean to change the `.foo` CSS rule to become `:host ::ng-deep .foo`; the `:host` is there to still prevent leaking the styles into parts of the DOM outside of the component.
