### ISSUE TITLE
fix(build): restore pub serve version of PR Travis Job

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#4316]
Currently all PRs are failing on Travis, but master and presubmit jobs are unaffected. This is due to an unknown issue with `pub serve`, which is how PRs are tested as opposed to dart2js compilation that happens on presubmit and master branches.

I'm submitting a PR to run dart2js for all PRs until this issue can be investigated. This will add about 10m to each PR, but it's better than outright failing.

**Comment by alfonso-presa** [comment]
Dart tests are failing for me when running them locally. `benchmarks_external` doesn't seem to be found when running `node_modules/.bin/protractor protractor-dart2js.conf.js --benchmark --dryrun --browsers=Dartium` along with `gulp serve.js.dart2js`. It does work when running it with `gulp serve.dart`. Is this related with this issue's patch? If so it seems like currently running the full test suite locally is not possible... or am I making something wrong?

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
