### ISSUE TITLE
Router stackblitz Live Example is not working

### ISSUE THREAD

**Issue by rahiyansafz** [angular/angular#43167]
### Description

The routing guide's stackblitz live example link is broken

### What is the affected URL?

https://angular.io/generated/live-examples/routing-overview/router.stackblitz

### Please provide the steps to reproduce the issue

Angular Docs > Developer Guides > Routing & Navigation > Overview > live example

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/70625091/129490762-3c34f1e9-d28c-4826-8a7a-0028fa985919.png)

**Comment by gkalpak** [comment]
Thx for reporting this, @rahiyansafz :+1:
It will be fixed by #43180.
