### ISSUE TITLE
Angular 12 Unit test failed when adding web worker

### ISSUE THREAD

**Issue by vupham-zingbox** [angular/angular#43183]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I generate a new project in angular 12, and generate web worker. Then run `ng test` and unit test failed with error `Error during loading: Uncaught SecurityError: Failed to construct 'Worker': Script at 'file:///Users/xxx/src/new-angular12/test-web-worker/src/app/app.worker' cannot be accessed from origin 'http://localhost:9876'. in http://localhost:9876/_karma_webpack_/main.js line 100`

### Please provide the exception or error you saw

```true
Error during loading: Uncaught SecurityError: Failed to construct 'Worker': Script at 'file:///Users/xxx/src/new-angular12/test-web-worker/src/app/app.worker' cannot be accessed from origin 'http://localhost:9876'. in http://localhost:9876/_karma_webpack_/main.js line 100
```

**Comment by vupham-zingbox** [comment]
upgrading global angular cli fixed it.

**Comment by ryankugel** [comment]
@vupham-zingbox Do you have any more detail about how you resolved this issue? I've created a test Angular 12 project as well and am having this exact same issue.
