### ISSUE TITLE
macroTask 'requestAnimationFrame': can not transition to 'running' 

### ISSUE THREAD

**Issue by amakhrov** [angular/angular#43194]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Basically the same as the earlier issue (which is now locked: https://github.com/angular/angular/issues/42486)

After upgrading to Angular 12 two days ago we started seeing 
> macroTask 'requestAnimationFrame': can not transition to 'running', expecting state 'scheduled', was 'scheduling'.

In all cases so far it's coming from Material/Tabs
<details>
  <summary>Stack trace</summary>
  
  ![Screen Shot 2021-08-18 at 9 13 23 AM](https://user-images.githubusercontent.com/1004015/129933867-2301ca01-d091-481d-aa2a-4ba578c01ac3.png)

</details>

It's quite rare; only logged for a dozen users so far - but it's clearly something brand new.

In case it's relevant - we also see similar (and similarly rare) `macroTask` errors for setInterval and setTimeout.

### Please provide a link to a minimal reproduction of the bug

Don't know how to repro. All recorded cases so far are Chrome on Windows

### Please provide the exception or error you saw

```macroTask 'requestAnimationFrame': can not transition to 'running', expecting state 'scheduled', was 'scheduling'.```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.1.2
Node: 12.20.2
Package Manager: yarn 1.22.10
OS: darwin x64

Angular: 12.1.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.2
@angular-devkit/build-angular   12.1.2
@angular-devkit/core            12.1.2
@angular-devkit/schematics      12.1.2
@nguniversal/builders           12.1.0
@nguniversal/express-engine     12.1.0
@schematics/angular             12.1.2
rxjs                            6.6.3
typescript                      4.2.4
```

**Comment by amakhrov** [comment]
A quick follow-up. It's still happening. Not too often - but at a rather constant rate. And it's always Chrome 88 on Windows 10.
In addition to `requestAnimationFrame` (executed by Material), we also have some custom code that implements debouncing via `window.setInterval` - this results in a similar`macroTask 'setInterval': can not transition...` error.

**Comment by jessicajaniuk** [comment]
@amakhrov Can you provide a reproduction for us on stackblitz? We were never able to get one on the prior issue, which makes it near impossible to debug / triage.

**Comment by amakhrov** [comment]
I wish I knew how to reproduce it...
I have never observed it myself. I only see it in a form of error logs collected from the app from real users (5-10 events logged every day).

Interesting that there seem to be multiple patterns here.
The `requestAnimationFrame` macrotask issue seems to occur entirely in Chrome on Windows.

However, similar errors with `setTimeout` and `setInterval` macrotasks seem to always happen in Firefox (on various OSs).

In all cases is seems to happen during initial page rendering rather than as a response to some user actions (clicks etc).

**Comment by JiaLiPassion** [comment]
@amakhrov , is that possible to deliver a debug version of zone.js in your environment? Or is that possible I can access the reproducable environment to check the issue?

**Comment by JiaLiPassion** [comment]
@amakhrov , sure the error log will help, please post it here, or send it to me through email, thank you.

**Comment by jessicajaniuk** [comment]
I'm sorry but we can't reproduce the problem you are reporting. We require that reported issues have a minimal reproduction that showcases the problem.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template that include info on how to create a reproduction using our template.
