### ISSUE TITLE
Aw, Snap! error often happening after 12.2.0 version upgrade(same works well with 12.1.2) 

### ISSUE THREAD

**Issue by dean-g** [angular/angular#43207]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

No

### Description

Getting Aw, Snap! error often after the Angular 12.2.0 upgrade!. (same works well with 12.1.4). 

<img width="560" alt="Screen Shot 2021-08-19 at 1 58 30 PM" src="https://user-images.githubusercontent.com/12157452/130128927-c5be1749-7f2c-4084-8077-705fdee7dd55.png">

Can someone please help me with this? 

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.0
Node: 14.17.0
Yarn: 1.22.5
```

**Comment by petebacondarwin** [comment]
It's going to be really hard to diagnose this problem without some more information.
Is it possible to share a reproduction that can be debugged?

**Comment by JoostK** [comment]
This looks related: https://piunikaweb.com/2021/07/05/google-chrome-on-mac-aw-snap-error-5-when-opening-tabs-accessing-settings/

**Comment by dean-g** [comment]
Thanks, @petebacondarwin. I can not share my private code base. 
why this is happening only after I upgraded to 12.2.0? 
Is there anything that I need to take care of it with this upgrade? 

Thanks in advance.

**Comment by dean-g** [comment]
something fishy and difficult to debug this issue!. 

my app is getting crashed often in chrome and edge browser. but it works well in firefox. 

Can someone please give some idea to troubleshoot this issue?

**Comment by dean-g** [comment]
here is the screenshot from edge browser: 

<img width="610" alt="Screen Shot 2021-08-20 at 1 58 02 AM" src="https://user-images.githubusercontent.com/12157452/130193199-c684e87a-3ddc-4537-a514-2c264b973c00.png">

**Comment by eneajaho** [comment]
Can you try this command: `node --max-http-header-size=100000 ./node_modules/@angular/cli/bin/ng serve` ?

**Comment by dean-g** [comment]
Thanks, @eneajaho for the response!. I finally found the issue's root cause. One of my API header payload requests was holding huge data. I just optimized that part and the aw snap error is gone. Thanks for the direction you have suggested!. that helped me!..
