### ISSUE TITLE
Update checkAnchorLinksProcessor processor feedback

### ISSUE THREAD

**Issue by josmar-crwdstffng** [angular/angular#43214]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

For the `checkAnchorLinksProcessor` processor.

*   Update the displayed warning to indicate the source (markdown) file.
*   Update the list of links to indicate the context of the link.
*   Stagger (tab in) the warnings associated with a processor.

### Please provide the exception or error you saw

```true
info:    running processor: checkAnchorLinksProcessor
warn:    Dangling Links Found in "guide/i18n-overview.json":
 - guide/i18n-commo#work-with-translation-files
error:   Error running processor "checkAnchorLinksProcessor":
1 unmatched links
error:   Failed to process the docs
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.1.1
Node: 14.16.1
Package Manager: yarn 1.22.10
OS: darwin x64

Angular: 12.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            12.1.1
@angular-devkit/schematics      12.1.1
@schematics/angular             12.1.1
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by petebacondarwin** [comment]
* Update the displayed warning to indicate the source (markdown) file.
  _We can do this._
* Update the list of links to indicate the context of the link.
  _Unfortunately this information is not available at the point this check is made, since the check is done by parsing the generated HTML and there is no mapping back from the HTML `<a>` elements to the original source locations._
* Stagger (tab in) the warnings associated with a processor.
  _We can add a bit more space between the `warn:` prefix and the message for this particular case - but to do a more general change would require significant refactoring to the logging services in dgeni._

**Comment by josmar-crwdstffng** [comment]
> *    Update the displayed warning to indicate the source (markdown) file.
>      *We can do this.*

Please add this issue number to the PR for the change.

> *   Update the list of links to indicate the context of the link.
>      *Unfortunately this information is not available at the point this check is made, since the check is done by parsing the generated HTML and there is no mapping back from the HTML `<a>` elements to the original source locations.*

Understood.  If this can be implemented in the future, please add this issue number to the PR for the change.

> *    Stagger (tab in) the warnings associated with a processor.
>      *We can add a bit more space between the `warn:` prefix and the message for this particular case - but to do a more general change would require significant refactoring to the logging services in dgeni.*

Understood.  Smaller changes are possible and will help.  Please add this issue number to the PR for the change.

**Comment by petebacondarwin** [comment]
I can generate output like the following:


```
...
info:    running processor: fixInternalDocumentLinks
info:    running processor: checkAnchorLinksProcessor
warn:        Dangling links - doc "guide/accessibility" (content)  - from file "guide/accessibility.md" - contains links to the following URLs that do not exist:
        - guide/attribute-bindingX
error:   Error running processor "checkAnchorLinksProcessor":
1 unmatched links
error:   Failed to process the docs
```

How does that look @josmar-crwdstffng ?

**Comment by josmar-crwdstffng** [comment]
Can we indent the `warn:` and `error:` headings associated with an `info:` heading similar to the following?

```output
info:    running processor: checkAnchorLinksProcessor
    warn:    Dangling Links Found in "guide/i18n-overview.json":
                 - guide/i18n-commo#work-with-translation-files
    error:   Error running processor "checkAnchorLinksProcessor":
                1 unmatched links
    error:   Failed to process the docs
        error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
        error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by petebacondarwin** [comment]
> Can we indent the warn: and error: headings associated with an info: heading similar to the following?

Sadly the `warn` and `error` prefixes are added by the generic logging part of the system, and so it is not possible to change this without a massive rewrite of the logging service.

> Since the .json and .md appear to be 1:1, can we also replace instances of warn: Dangling Links Found in "guide/i18n-overview.json": with warn: Dangling Links Found in "guide/i18n-overview.md": when displayed?

Yes, the example I gave earlier does indeed already do this:

```
warn:    Dangling links - doc "guide/accessibility" (content)  - from file "guide/accessibility.md" - contains links to the following URLs that do not exist:
```

**Comment by josmar-crwdstffng** [comment]
Looks good to me.
Please move forward with the PRs to get your examples implemented.
Thank you

**Comment by petebacondarwin** [comment]
This should only close once https://github.com/angular/angular/pull/43317 lands
