### ISSUE TITLE
Object is possibly 'undefined'.

### ISSUE THREAD

**Issue by alexalannunes** [angular/angular#43222]
### Description

Hi, i'm new in Angular!

I can't fix this

Error in src/app/product-details/product-details.component.html (4:18)
Object is possibly 'undefined'.

![Captura de tela de 2021-08-21 13-01-09](https://user-images.githubusercontent.com/16847836/130327848-8ee912a5-e39c-4f9a-8701-dd1c1c28b04f.png)

```html
<h2>Product Details</h2>

<div *ngIf="product">
  <h3>{{ product.name }}</h3>
  <h4>{{ product.price | currency }}</h4>
  <p>{{ product.description }}</p>
</div>
```

I copied and paste the original code from doc
But I got Error

### What is the affected URL?

https://angular.io/start/start-routing#view-product-details

**Comment by vugar005** [comment]
Starting from Angular 12, the Angular uses `"strict": true `of Typescript configuration.  To resolve this
1. You can disable it: by navigating to tsconfig and add  ` "strict": false` to `"angularCompilerOptions"`
2. Use ! operator like  `product!: Product;` , which literally means: 'Hey typescript, I know it is undefined now, but it should be defined on runtime. Do not worry'.

**Comment by alexalannunes** [comment]
woowww, Thanks @vugar005 .
I tried the option 3 but nothing was shown. I will try on my local setup and test this options: 1 and 2

I will close this issue!

Thanks a lot
