### ISSUE TITLE
I have implemented Angular Google Maps with Places Search 

### ISSUE THREAD

**Issue by JKAngular** [angular/angular#43236]
### Which @angular/* package(s) are the source of the bug?

compiler, forms

### Is this a regression?

Yes

### Description

Hi

I have implemented Angular Google Maps with Places Search . But facing issue embedded image.

I have using this command for package installation

npm install @agm/core --save
npm install @types/googlemaps --save-dev

![image](https://user-images.githubusercontent.com/59573064/130567049-30dd3084-39b0-4014-be65-eb4322c4becf.png)

I have tried also like this in package.json
    "@types/googlemaps": "^3.43.3",

### Please provide the environment you discovered this bug in

```true
Angular CLI: 11.2.13
Node: 14.17.1
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.13
@angular-devkit/core         11.2.3
@angular-devkit/schematics   11.2.3
@schematics/angular          11.2.13
@schematics/update           0.1102.12
```

**Comment by gkalpak** [comment]
This issue doesn't seem to be related to Angular, so there is not much we can do. It is likely an incompatibility between the versions of `@agm/core` and `@types/googlemaps` that you use. You could try contacting the authors of project `@agm/core` or file issue on their issue tracker.
