### ISSUE TITLE
Anchor Tags should open the links in new tab

### ISSUE THREAD

**Issue by helloankit** [angular/angular#43266]
### Description

All links to external resources from angular.io should open the links in a new tab, instead of the same tab.

### What is the affected URL?

https://angular.io/

### Please provide the steps to reproduce the issue

1. Click on any hyperlink to the external resource
2. Observe the behavior

Example Pages - 
https://angular.io/guide/creating-libraries#integrating-with-the-cli-using-code-generation-schematics
https://angular.io/cli/usage-analytics-gathering

### Please provide the expected behavior vs the actual behavior you encountered

The idea of adding external references is to let the user have a look at them in case he wants to know more about the topic or to clarify something. By doing so, he/she doesn't want to get distracted or redirected away from what he/she was reading. That's a poor UX.

Expected Behavior:
Links should open in a new tab instead of the same one.

Actual Behaviour:
Links are opening in the same tab, navigating the user away from angular.io
Although a lot of links like (Stackblitz examples, etc) are loading in a separate tab, but this behavior is not consistent throughout

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/61384771/130962149-87cb82da-d5c1-4c86-9e4f-a00acd269992.png)

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
No
```

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
