### ISSUE TITLE
Dependencies (package.json [dev]Dependencies) cannot be commented (locally in manifest)

### ISSUE THREAD

**Issue by Chealer** [angular/angular#43279]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

Dependencies of an Angular application are specified in the `dependencies` (and `devDependencies`) key of `package.json`, as documented in [_Workspace npm dependencies_](https://angular.io/guide/npm-packages). This structure is inherited from npm, and with it comes [a limitation which has been known for a long time](https://github.com/npm/npm/issues/4482) and discussed in [more](https://www.techiediaries.com/add-comments-package-json/) than [one place](https://stackoverflow.com/questions/14221579/how-do-i-add-comments-to-package-json-for-npm-install).

While the dependencies can be specified one per line in a readable way, it is (basically - hacks ignored) not possible to add a comment about a given dependency on the same line (or on the line above). This limitation itself comes from the format used by npm, JSON.

There are many reasons to comment dependencies. I work on a single Angular project which is not huge, but we have well over 30 direct dependencies, and I have hit problems which could have been avoided or largely mitigated by simply commenting dependencies, more than once just during this quarter. For example, today I needed to add a version constraint on our dependency on @types/node to workaround [DefinitelyTyped #55430](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/55430), and it already looks like that constraint may become unnecessary in a matter of days thanks to an upstream fix. But since I couldn't justify it right in the manifest, that constraint could remain unwarranted for a long time because no one wants to take a chance. Other reasons to comment a dependency include indicating that:

- it should be removed
- it should be updated (but there have been issues with an earlier attempt)
- it could be replaced with an alternative rather than updated
- it is deprecated in favor of another dependency
- it is low-quality

### Proposed solution

The obvious solution would be to support an alternative to npm which supports manifests in a format richer than strict JSON (such formats include JSON5, JSON6, and the better-known XML and YAML).  The only alternative which looks serious that I see is [pnpm](https://pnpm.io/), which supports JSON5 and YAML.

Disclaimer: I have never used pnpm, and while it is obviously better than npm on that front, I cannot even claim that pnpm is generally superior to npm.

### Alternatives considered

- [yapm](https://github.com/rlidwka/yapm) is an npm alternative which supports YAML, but which despite its great name would apparently require lots of effort to bring to maturity.
- Insisting for npm itself to introduce support. While the original ticket was closed by an npm developer who constructively complained of "bikeshedding", [a newer and more much articulated ticket](https://github.com/npm/rfcs/issues/291) has replaced it.

**Comment by itea-dev** [comment]
Your issue with comments in the package.json can be solved easily in other ways like opening an issue in your issue tracker so you can remember to remove, update or replace that dependency.

**Comment by Chealer** [comment]
Thanks @itea-dev 
There are obviously a number of workarounds indeed possible, some of which are mentioned in the Techiediaries article linked above and in [npm issue #4482](https://github.com/npm/npm/issues/4482).

**Comment by JoostK** [comment]
The goal of the Angular project is not to provide custom package management features. https://github.com/npm/rfcs/issues/291 seems to be the right place for this request (thank you for providing this context up front).

**Comment by Chealer** [comment]
Is there a reason why this ticket is closed?

**Comment by JoostK** [comment]
Please see https://github.com/angular/angular/issues/43279#issuecomment-991642142

**Comment by Chealer** [comment]
I am sorry @JoostK but I do not see an explanation for this ticket's closure in the comment you mention. To prevent any confusion, this is an issue tracking system, not actually a request tracker. This report is **not** asking to change the Angular project's goal, and relying on an external component for all package management is fine, as long as the available choices offer enough features.

**Comment by JoostK** [comment]
You can use any package manager you like. pnpm's approach is known to be problematic for ngcc to work (it needs to write to `node_modules`, which isn't compatible with how pnpm installs packages) but with Angular 13 ngcc is only needed to use some libraries.

**Comment by Chealer** [comment]
Thank you @JoostK but the issue is not so much supporting other package managers as supporting the better formats allowed by these. As long as package.json is required, alternative package managers will not help for this issue.
