### ISSUE TITLE
Docs: Property binding and string initialization, small possible improvements

### ISSUE THREAD

**Issue by dario-piotrowicz** [angular/angular#43287]
### Description

In the property binding docs, there is a [section about one-time string initialization](https://docs.angular.lat/guide/property-binding#one-time-string-initialization) which simply states that the square brackets for property binding are not to be used for simple strings defined in the template

as in:
```html
   <app-string-init prefix="This is a one-time initialized string."></app-string-init>
```
instead of:
```html
   <app-string-init [prefix]="'This is a one-time initialized string.'"></app-string-init>
```

\
and it says that this *should* be done (not *could*), so I was just thinking that this could be added to the [property binding best practices page](https://angular.io/guide/property-binding-best-practices) (something like "Avoid unnecessary expression evaluations", which could refer to the section I mentioned on top of the issues's description)

\
\
I've also found that a few places in the docs do not follow this, as for example:

![Screenshot at 2021-08-30 14-21-50](https://user-images.githubusercontent.com/61631103/131345852-cd3b4903-ecb5-4da0-bf6d-ef8bb52dea39.png)
![Screenshot at 2021-08-30 14-14-34](https://user-images.githubusercontent.com/61631103/131345833-ebaed2a9-cf0b-4cb3-be3b-eedb4ace8248.png)

So I would think it would be good to amend such docs/examples.

**Comment by dario-piotrowicz** [comment]
I just wanted to make sure my understanding on this is correct and this is indeed be a best practice which should be followed, if it is I would gladly made the changes I mentioned in the description :slightly_smiling_face:

**Comment by gkalpak** [comment]
Sounds reasonable to me :smiley:

**Comment by dario-piotrowicz** [comment]
Awesome, I'll make the changes then, thanks :smiley: 

( if I could be assigned to this issue that would be great :smiley:  )

**Comment by dario-piotrowicz** [comment]
@gkalpak thanks! :heart:

**Comment by dario-piotrowicz** [comment]
I've been making the changes and I noticed that the one-time string initialization is not actually in angular.io but in docs.angular.lat :man_facepalming:  (I am not completely sure how I got there... :man_shrugging: the text is indeed in english :sweat_smile: ) so I can't actually link to that, so I will just add the thing in the best practices itself, I hope that is fine :slightly_smiling_face:

**Comment by gkalpak** [comment]
Looking through the related files' history, it seems that the section on omitting brackets for static string values was deliberately removed in #38799 (see https://github.com/angular/angular/pull/38799#discussion_r492375710). So, I don't think we should be bringing the section back. (It is still OK to follow this practice in code snippets in other docs, though 😉)

**Comment by dario-piotrowicz** [comment]
I see, I am very sorry, I should have thought of that and checked the file's history :sweat: 

Anyways I believe that the example code is not used anymore but it's still there, should I remove it?

Also I will amend the commit so that I only fix the code snippets in the docs as you mentioned, and only when it is crystal clear that that doesn't go again the example itself, thanks! :slightly_smiling_face:

**Comment by gkalpak** [comment]
No worries, @dario-piotrowicz :smiley:

If some code is not used/needed, feel free to remove it. Let's move the discussion to the PR :wink:
