### ISSUE TITLE
Need a solution to speed up Angular2!!

### ISSUE THREAD

**Issue by butaixianran** [angular/angular#4328]
Angular 2 is really wonderful in many ways, but A BIG problem is: It's tooo slow when you open an Angular 2 page for the first time.

Here is an example: (in Chinese)
https://771dian.com/danmu

![2015-09-23 11-10-03](https://cloud.githubusercontent.com/assets/5558722/10037119/35722218-61e4-11e5-8e5b-b9bb910466aa.jpg)

This simple page includes nearly 20 angular2 components, each one with a .js file and a html template.

Which means, when somebody open this simple page, server need to send more then 40 files to client, including angular.js, system.js and traceur-runtime.js.

That's really too many files even with SPDY or HTTP/2.

The example site above is using SPDY, but I still need to wait for a long time before chrome shows anything.
(By the way, for the server side, I'm using node.js with KOA web framework, which should be fast.)

And think about an index page for a CMS, it's gonna be more than 50 components for a single page, which means when you open that page, server need to send more than 100 files to client.

Is there a solution for this "too many files problem"? Thanks.

**Comment by mgechev** [comment]
@butaixianran you can inline the component templates (for example you can try this [gulp task](https://github.com/ludohenin/gulp-inline-ng2-template) by @ludohenin) and after that create a single bundle with all your scripts.

This will reduce the requests dramatically.

**Comment by gdi2290** [comment]
can you provide a github repo? perhaps a clone showing similar problems in case you can't share the current codebase. There are many ways to optimize initial loads include one method that is yet to be released

**Comment by devmark** [comment]
just minify js or html.

**Comment by S-YOU** [comment]
your server is just slow, it took 10s to download angular2.dev.js. (non-minified, no gzip)

![2015-09-23 20 16 06](https://cloud.githubusercontent.com/assets/1001175/10043684/fdab4390-622f-11e5-9585-c5bcd836e3df.png)

while google cdn can serve it around 100ms for angular 1x (non-minified, with gzip)
![2015-09-23 20 18 15](https://cloud.githubusercontent.com/assets/1001175/10043731/4efc73ae-6230-11e5-98f9-8d80e0331e5d.png)

what you can do is concat, minify, gzip etc as other said.

**Comment by pkozlowski-opensource** [comment]
@butaixianran I think that people in this thread have identified a number of optimizations that you can make today. At the same time @tbosch is working hard on the compiler changes that will make it possible to pre-compile all the templates as part of the build step. This means that you will be able to compile templates off-line and combine / minify resulting JS output.

But yeh, for now you need to bundle your files and make sure that your server performs reasonably.

Closing for now as the further startup optimizations are being worked on.

**Comment by butaixianran** [comment]
@pkozlowski-opensource , that's great news. And thanks guys. My target is Chinese people, my server is in China for now, so your visiting should be slow. For now, I may try gulp-inline-ng2-template, looks like a great tool for me.

**Comment by butaixianran** [comment]
Update: after move angular2.js, system.js, traceur-runtime and rx.js to cdn, now it's pretty fast. Http2 works very well with Angular2.

**Comment by Toadskin** [comment]
This is not an Angular issue it's a build issue with the same solutions as any other client-side framework.  Putting 20 components on your landing page, on the other hand, is poor design.  Nevertheless, use the template cache as suggested.  Along with basic minification and bundling, and test as you go (rather than discovering your completed project takes too long to load in production).

**Comment by ps2goat** [comment]
@pkozlowski-opensource do you have a link to an issue regarding the template pre-compilation so we can track this?

**Comment by alzalabany** [comment]
@S-YOU  did you notice you are comparing angular2.dev (3.1MB) to angular1 (2.5k) ?

angular2 is fat. and it will take time to load. try ionic2 which is based on angular2, empty project is nearly 7mb ! 

+1 for we need a solution to compress/ pick remove unused components from build

**Comment by CaptainCodeman** [comment]
If you are deploying and comparing dev versions then you are doing it wrong.

There are lots of tools to bundle an Angular 2 app and reduce the number of requests and the payload size.

As an example, here's a bare-bones page that loads Angular 2 in a couple of hundred Kb:
http://captain-codeman.appspot.com/

**Comment by S-YOU** [comment]
@alzalabany, see screen shots **correctly**, before stupid assumptions.

angular2 was 1.1M, and angular1 is 1M (after gzip its 256K)

**Comment by donew** [comment]
CaptainCodeman Can you please give an example of much complex project. With complex routing and view manipulation.

**Comment by CaptainCodeman** [comment]
Sorry, I did have a more complex project but I've since given up on Angular 2 and don't use it anymore.

There are simpler and better frameworks that don't require so much work and provide a much nicer dev + runtime experience (esp. without all the headaches of recent WebPack breaking changes).

I can strongly recommend looking at Polymer.
