### ISSUE TITLE
Cant unsubscribe from MediaQueryList using removeListener

### ISSUE THREAD

**Issue by DimaPateuk** [angular/angular#43292]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

Cant unsubscribe a listener from the MediaQueryList using removeListener

```javascript
export const BREAKPOINTS: any = {
  screenKey: 500,
  screenKey2: 600,
};

const mqls: any = {
  screenKey: null,
  screenKey2: null,
};

export class AppComponent implements AfterViewInit {
  ngAfterViewInit() {
    Object.keys(mqls).forEach((key) => {
      mqls[key] = window.matchMedia(`(max-width: ${BREAKPOINTS[key]}px)`);
    });
    this.createListeners();
  }

  listener = () => {
    for (const key in mqls) {
      if (mqls[key].matches) {
        console.log('emitted from method', key);
        break;
      }
    }
  }

  createListeners() {
    Object.keys(mqls).forEach((key) => {
      mqls[key].addListener(this.listener);
    });

    setTimeout(() => {
      this.remove();
    }, 5000);
  }

  remove() {
    Object.keys(mqls).forEach((key) => {
      console.log(mqls[key]);
      mqls[key].removeListener(this.listener);
    });

    console.log('removed all listeners');
  }
}
```

### Please provide a link to a minimal reproduction of the bug

https://github.com/DimaPateuk/media-test

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.3
Node: v12.20.1
Package Manager: npm 6.14.10
OS: ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G9216
```

### Anything else?

for the latest version of the Angular  removeEventListener works as expected

**Comment by flash-me** [comment]
Hi @dimakuba,

 When using the `change Event`  as described [here](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList#examples), instead of using the [depraced `addListener` method](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener), everything works as expected. 

- `mqls[key].addListener(this.listener);` → `mqls[key].addEventListener('change', this.listener);`
- `mqls[key].removeListener(this.listener);` → `mqls[key].removeEventListener('change', this.listener);`

cheers
flash ⚡

**Comment by dimakuba** [comment]
@flash-me seems like it should be addressed to @DimaPateuk 🙃

**Comment by DimaPateuk** [comment]
@flash-me, I know that that is why I added it in the description, take a look on **Anything else?** section there is note about it:
for the latest version of the Angular removeEventListener works as expected

the question is why it does not work with removeListener? 

or if it is deprecated then just do not care about it?

**Comment by flash-me** [comment]
Oh my fault, didn't see that! 

cheers
flash ⚡

**Comment by DimaPateuk** [comment]
any updates related to that issue?

**Comment by Totati** [comment]
What does this do with Angular? You should ask this on stackoverflow.com

**Comment by DimaPateuk** [comment]
nothing, but some part of the angular break this functionality that is why I am asking the angular team about it and not stackoverflow

**Comment by DimaPateuk** [comment]
any updates? I really want to understand why removeListener does not work

**Comment by pkozlowski-opensource** [comment]
> nothing, but some part of the angular break this functionality that is why I am asking the angular team about it and not stackoverflow

Agree with @Totati - this sounds like a support question not related to Angular and as such it is not a good fit for our issue tracker.
