### ISSUE TITLE
bower-angular-resource broken with browserify

### ISSUE THREAD

**Issue by slively** [angular/angular#433]
index.js is being generated with this (which is not valid javascript):
```javascript
require('./angular-resource');
module.exports = angular-resource;
```

Changing it to this fixes it:
```javascript
module.exports = require('./angular-resource');
```

It also looks like package.json used to have the below instead of using the index.js:
```
"main": "angular-resource.js",
```

**Comment by caitp** [comment]
This is the wrong repository for this issue, could you please open this at https://github.com/angular/angular.js? We will try to get that resolved tomorrow

**Comment by slively** [comment]
@caitp Sorry about that and thank you!
https://github.com/angular/angular.js/issues/10760
