### ISSUE TITLE
ngComponentOutlet need support pass data

### ISSUE THREAD

**Issue by zhuchenghuFF** [angular/angular#43302]
When I use ngComponentOutlet directive; I need pass data to the target component; but ngComponentOutlet not support; I think ngComponentOutlet can support  an attribute like 'ngComponentOutletParams'; we  can pass data by this. thank you!

**Comment by destus90** [comment]
The issue is already created https://github.com/angular/angular/issues/15360

**Comment by pkozlowski-opensource** [comment]
@destus90 is completely right, this is indeed a duplicate of #15360

**Comment by pkozlowski-opensource** [comment]
Duplicate of #15360

**Comment by zhuchenghuFF** [comment]
Oh， When I see those comments above，I'm in a terrible mood, Such a good function is limited by @input&@output；Worse still this issue was opened some years ago but still open! I look forward to solving this problem quickly.
