### ISSUE TITLE
help(product-list-component): 'app-product-alerts' is not a known element

### ISSUE THREAD

**Issue by zlaski** [angular/angular#43306]
This is the tutorial found on `https://angular.io/start`.  I'm getting the following compile-time error:

Error in src/app/product-list/product-list.component.html (16:3)
'app-product-alerts' is not a known element:
1. If 'app-product-alerts' is an Angular component, then verify that it is part of this module.
2. If 'app-product-alerts' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

I've checked in the source at `https://github.com/zlaski/angular-fs3udy` (I couldn't figure out how to make it accessible via StackBlitz).

Thank you.

**Comment by gkalpak** [comment]
Thx for reporting this, @zlaski.

This has been fixed in #43229. (If you visit the tutorial now, you should see the updated guide with the instructions on how to make the `ProductAlerts` component available to the app.)
