### ISSUE TITLE
Option to get the current Validators on Control/FormGroup/FormArray 

### ISSUE THREAD

**Issue by abhijitchikane** [angular/angular#43305]
### Which @angular/* package(s) are relevant/releated to the feature request?

forms

### Description

Add option to get the current Validators on Control/FormGroup/FormArray 

### Proposed solution

Right now there is no method which will get the list of current validators applied on the control/formGroup/formArray

### Alternatives considered

Not as of now

**Comment by dylhunn** [comment]
Please use the new `hasValidator`, `addValidator`, and `removeValidator` APIs.

Discussed at length here: #13461
