### ISSUE TITLE
Exception raised when dynamic load component with template

### ISSUE THREAD

**Issue by todoubaba** [angular/angular#4330]
Plunker demo http://plnkr.co/edit/OjK2u16P3ZcO1fSPnNAf?p=preview

```
import {Component, View, bootstrap, CORE_DIRECTIVES,
  ElementRef, DynamicComponentLoader
} from 'angular2/angular2';

@Component({
  selector: 'my-cmp'
})
@View({
  directives: [CORE_DIRECTIVES],
  template: `
<div>
    <div *ng-for="#i of values">{{i}}</div>
</div>
`
})
class MyCmp {
  constructor() {
    this.values = [1, 2, 3]
  }
}

@Component({
  selector: 'my-app'
})
@View({
  directives: [MyCmp],
  template: `
<div>static:<my-cmp></my-cmp><div>
<button (click)="load()">Load</button>
`
})
class MyApp {
  constructor(elementRef: ElementRef, loader: DynamicComponentLoader) {
    this.elementRef = elementRef;
    this.loader = loader;
  }
  
  load() {
    this.loader.loadNextToLocation(MyCmp, this.elementRef).then((ref) => {
      document.querySelector("body").appendChild(ref.location.nativeElement);
    });
  }
}

bootstrap(MyApp);
```

When click load button, throws the following exception:
```
EXCEPTION: No provider for function (factories) {! (function (viewContainer, templateRef, iterableDiffers, cdr) { -> function (factories) {)
```

**Comment by todoubaba** [comment]
It is caused by DI can't find `IterableDiffers` binding for `ng-for`. The temp workaround is passing a new `ResolvedBinding` into `loadNextToLocation`.

**Comment by todoubaba** [comment]
It works in beta.6
http://plnkr.co/edit/oRUC1Lli1fTg2lHvhdZu?p=preview

**Comment by ajspera** [comment]
@todoubaba I'm having a similar issue with app wide providers. As an example I would want to put an api service that has previously set data for auth headers from another component. If I need the same provider instance as the app does in my component I will end up with the missing provider issue.

http://plnkr.co/edit/FvekxB1URuBuMy7a7viG?p=preview I added an app wide provider in your plunkr that is shared with the component for an example.

**Comment by todoubaba** [comment]
@ajspera 
```
  constructor(elementRef: ElementRef, loader: DynamicComponentLoader, 
      private apiService: ApiService) {
    this.elementRef = elementRef;
    this.loader = loader;
  }
  
  load() {
    let resolvedProviders = Injector.resolve([provide(ApiService, {useValue: this.apiService})]);
    this.loader.loadNextToLocation(MyCmp, this.elementRef, resolvedProviders).then((ref) => {
      document.querySelector("body").appendChild(ref.location.nativeElement);
    });
  }
```

**Comment by ajspera** [comment]
@todoubaba Yeah that's fine in this small case, but I was thinking about larger scale including the case of providers potentially changing on the app level. It would be preferable in some cases to load the child component the same way it would if it was in the template, with the fully resolved providers from the parent component's injection tree.

I saw in the Injector docs createChildFromResolved (https://angular.io/docs/ts/latest/api/core/Injector-class.html#!#createChildFromResolved-anchor), which I think is what I'm looking for, but I'm not clear on how someone would pull the parent injector to derive from or if thats really even possible to access.

**Comment by todoubaba** [comment]
@jspera In current api, there is not way to pass an injector instance to the `loadNextToLocation`.
