### ISSUE TITLE
Content Security Policy directive: "img-src 'self'" error

### ISSUE THREAD

**Issue by dvt63894** [angular/angular#43319]
i am using  "pdfmake" to download the PDF file. In one environment it works fine. But in other environment it is giving following error:
Refused to load the image 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAA/CAYAAABXXxDfAAAAAXNSR0IArs4c6QAACUtJREFUaAXVm39sVtUZx+3LW0qhgEBtEwlloRSQYtQVZQXMiIMW+88m/ojgH8oPl23J1OgfZpEsC7IlS0ayOKOJP5AlGv5ANP5TaSUbibSlShUiVQO0Wwpd0tbYbu0olLbs8325t7nvvefe99d9u/c9yc0553me8zzP9/y+555bcEuWQm1tbfGCBQuqUb/uxo0bNcSrCgoKFpO+lXQxT5R8AfkbpMd5RskOkf0X8bfEHTztAwMDnR0dHVfghx4KwtRYU1NTWFpaujESiWxD7xZAVBFHMrAxSQVc4DnOc/Ty5cstnZ2dYxnoiysaCvj6+vqFAH0c0LvQrlbOVuhA8TsTExOHm5qavs/USEbg6+rq5syYMUOAnwV8ZabOJFueXtDF88rk5OTbzc3N/022nFsubfC09lZa+veA/qFb6...TrZS7fw+vnFPonfvfwPN3eBtjV1TVQWVl5jgrYBs34akvFLIH3GMPke4bLGbtslmPdwNyNbbX4ygBbuoO7HeCtfjK+LW8XwNDjGDnEU2TTTDG94GPo+xhbekvMSpjWu7c2AiognVvXqnHPkbGtM4XYvnWtnxt0/TywEZAJ79a17SRL4LTet1+0aNFKhtwWwAqwrpH4Tc62i4r76IE76X3qhQlDwm7v1BDWnxb6FMbp8DCgYn9akJ9rnRYvg5Z7f1rYlaDlhX9sXsbJX0HznTBt+YA4rH9stIF5Pev/2DiBWHfx9bZX46RPZxrQGf1dlXbLsRRenDdv3rtz5szpA/AKesLC6QIO6C5s/Y7h8gxL2Tfp2k1pzPsZ2bhx44KSkhKtCLuQyWZP6GDtPjgyMnL45MmTGV9dCwW8XSnWX1Gxf2npCZuhr+BJZpa2VbhjzQu5/S+t22Plrft9af9FjYrTtPJn2fyL+n+Xr04TVUB0jwAAAABJRU5ErkJggg==' because it violates the following Content Security Policy directive: "img-src 'self'".

Code and configurations are same for both the environments.
pdkmake and angular version is:
"pdfmake": "^0.2.2",
"@angular/cli": "~12.2.1",

Can you please check what could be the issue?

Thank you

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
