### ISSUE TITLE
How to lazy load a script located in node_modules?

### ISSUE THREAD

**Issue by directcuteo** [angular/angular#43316]
Hi!
I have a script object inside my `scripts` array from `angular.json` which is loaded when the page starts.
```
...
"options": {
   ...
   "scripts": [
                 {
                   "input": "node_modules/swagger-ui-dist/swagger-ui-bundle.js",
                   "inject": true,
                   "bundleName": "swagger-ui-bundle"
                 }
              ]
}
```

I would want my app to load this script only when it's needed (which is actually in a lazy loaded Angular module).
This way I will reduce the traffic when the app loads.
Or even better would be to load the script in a way similar to `RouterModule`'s `preloadingStrategy: PreloadAllModules` strategy, which basically loads the js files in the background while user interacts with the app.

How can I do this in a "by the book" way?
Having the file inside "node_modules" affects me?
What is the purpose of having `"inject": false` if it never actually injects the script? Can it be accessed somehow? Angular docs does not cover this.

Thank you!

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
