### ISSUE TITLE
Breaking changes in Angular version 12: Broken TypeScript entry

### ISSUE THREAD

**Issue by Chealer** [angular/angular#43311]
### Description

[The _Breaking changes in Angular version 12_ section of the _Updating to Version 12_ page](https://angular.io/guide/updating-to-version-12#breaking-changes-in-angular-version-12) starts with:

> Add support for TypeScript 4.2. TypeScript <4.2.3 is no longer supported. The supported range of TypeScript versions is 4.2.3 to 4.2.x. See PR #41158.

There are obviously several things wrong, but I will not file a ticket for each, so please basically take this as a request to review that entry. I will file further tickets in case something is missed.

Specific issues and observations:

- The removal of support for TypeScript < 4.2.3 and the addition support for TypeScript 4.2 (if this makes sense) should be treated separately.
- It would be best to have a section dedicated to breaking changes and deprecations.
- "The supported range of TypeScript versions is 4.2.3 to 4.2.x." should be moved, perhaps to [_Angular versioning and releases_](https://angular.io/guide/releases), or at least fixed.
- The list of issues on that page usually uses proper sentences, but has several elements like "Add support for TypeScript 4.2" and lacks uniformity.

### What is the affected URL?

https://angular.io/guide/updating-to-version-12#breaking-changes-in-angular-version-12

### Please provide the steps to reproduce the issue

This does not report a behavioral bug.

### Please provide the expected behavior vs the actual behavior you encountered

This does not report a behavioral bug.

### Please provide the exception or error you saw

```true
This does not report a behavioral bug.
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
No
```

**Comment by alxhub** [comment]
I think the original issue here was correct that the wording was confusing, but the update page is now for v14, so it's no longer relevant.
