### ISSUE TITLE
Support Policy Unclear

### ISSUE THREAD

**Issue by dirthsj** [angular/angular#43326]
### Description

[This page](https://angular.io/guide/releases#support-policy-and-schedule) lists angular 9 as supported, but also lists support ending August 06, 2021 which has already past.

### What is the affected URL?

https://angular.io/guide/releases#support-policy-and-schedule

### Please provide the steps to reproduce the issue

Observe Page

### Please provide the expected behavior vs the actual behavior you encountered

Supported releases should have a future date for Active or LTS end date.

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/3802881/131897839-235682ff-6adb-4a69-beac-1f990d243c59.png)

### Please provide the exception or error you saw

```true
N/A
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
N/A
```

**Comment by atscott** [comment]
The LTS end date is correct. We should remove the `9.0.0` line from the table since the LTS end date has passed.

**Comment by JoostK** [comment]
Closing as resolved in #43350
