### ISSUE TITLE
fix(router): router-link does not respect location strategy

### ISSUE THREAD

**Issue by btford** [angular/angular#4333]
In particular, binding the `HashLocationStrategy` still makes router-link produce an href without the leading hash, which obviously does not work when copying or opening a link in another tab.

Tracks internal bug b/24126114.

**Comment by devmark** [comment]
So all href link should add hash?

router_link.ts
```
  onClick(): boolean {
    if((<KeyboardEvent>window.event).metaKey || (<KeyboardEvent>window.event).ctrlKey || (<KeyboardEvent>window.event).shiftKey || typeof this.targetParams !== 'undefined'){
      return true;
    }
    
    this._router.navigateByInstruction(this._navigationInstruction);
    return false;
  }
```

**Comment by btford** [comment]
No, but apps where `HashLocationStrategy` is used should generate links with hashes.

**Comment by rvramesh** [comment]
This is my first time looking at angular 2  source code. My analysis is as below. Please let me know if it is right.

The location_strategy.ts should expose a method `generateNavigationUrl` which should accept a string and return it as is (which is default implementation).

The hash_location_strategy.ts should override the `generateNavigationUrl` method and return the string with "#" + url passed. 

The location.ts should expose a new method `normalizedNavigationUrl` which should accept a stringified instruction just like `normalizeAbsolutely` and internally call normalizeAbsolutely and pass that output to 'generateNavigationUrl' of the platformStrategy

**Comment by btford** [comment]
@rvramesh – exactly right.
