### ISSUE TITLE
Allow for additional modules to be imported within a module's `static forRoot(...): ModuleWithProviders`

### ISSUE THREAD

**Issue by jkossis** [angular/angular#43332]
### Which @angular/* package(s) are relevant/releated to the feature request?

common

### Description

Right now, the `ModuleWithProviders` construct allows for one to dynamically/conditionally add providers based on config passed into the module's `forRoot` method. Could the same idea be extended for allowing dynamic module imports as well?

As an example, if we wanted to avoid importing a module in production within an ng library, we could pass the consuming app's `production` property into the library's module's `forRoot` method.

### Proposed solution

```
export class Module {
  static forRoot(config: Config): ModuleWithProviders<Module> {
    return {
      ngModule: Module,
      imports: [
        config.blah ? [ BlahModule ] : []
      ]
      providers: [
        { provide: FOO_TOKEN, useValue: config.foo }
      ]
    };
  }
}
```

### Alternatives considered

N/A

**Comment by rothsandro** [comment]
With the conditional module import the BlahModule itself will always be part of the JS bundle. Angular will three-shake the components of the module (when not used) but the module itself (and all modules that the BlahModule imports) are included in the bundle. Admittedly, an empty module class (no logic in the constructur, no static methods, ...) does not have a big impact on the final bundle size but the pattern must be used with care.

**Comment by JoostK** [comment]
We discussed this feature request and cannot go forward with it, as the array of `imports` must be statically known at compile time. The list of imported NgModules affect directive matching which is handled during AOT compilation (it has to be to allow unused components to be tree-shaken) and so its presence cannot be based on a dynamic conditional.

The Angular AOT compiler does support conditional imports, but only if the conditional can be determined at compile time. This is supported in the CLI using its environment files, which get replaced at compile time such the condition becomes statically known.

Within an application you may be able to do the following:

```ts
export class Module {
  static forRoot(config: Config) {
    return [
      config.blah ? [ BlahModule ] : [],
      {
        ngModule: Module,
        providers: [
          { provide: FOO_TOKEN, useValue: config.foo }
        ],
      },
    ];
  }
}
```

This cannot work in libraries though, as the above code would be compiled into JavaScript when compiling the library after which the AOT compiler only ever looks at the `.d.ts` output of libraries, not its `.js` sources. This is why `ModuleWithProviders` has a generic type parameter: it is encoded into the `.d.ts` files such that application compilations can statically know which NgModule is being imported based on the generic type arg. This would not be the case for any conditional imports though, as that cannot be expressed in `.d.ts` output.
