### ISSUE TITLE
Resolving service as a dependency

### ISSUE THREAD

**Issue by TiagoBraga39** [angular/angular#4334]
Hi all!

I am having troubles while instanciating dependencies. The dependency is called NagivationMapper.
```javascript
export class NagivationMapper {
    foo() { }
}
```

I have a Component that I bootstrap:
```javascript
@ComponentMetadata({
    selector: 'application',
    bindings: [ NagivationMapper ]
})
@ViewMetadata({
    templateUrl: 'app/shell/shell.html',
    directives: [ Home ]
})
@RouteConfig([
    new Route({ path: 'home', as: 'home', component: Home })
])
export class Shell {
    constructor(navigationMapper : NagivationMapper) {
        this.navigationMapper = navigationMapper;
    }
}
bootstrap(Shell, [ ]);
```
As you can see, I inject the NavigationMapper service and I also have a Home component in my router.
This time only, the dependency is resolved.
```javascript
@ComponentMetadata({
    selector: 'home'
})
@ViewMetadata({
    templateUrl: 'app/shell/home/home.html'
})
export class Home {
    constructor(navigationMapper : NagivationMapper) {
        this.navigationMapper = navigationMapper;
    }
```

As far as I am concerned, I don't need to inject the NavigationMapper also on the Home Component. Isn't that how child injectors are supposed to work?

Anyway, even if I inject with the bindings component, the error is the same:
![image](https://cloud.githubusercontent.com/assets/8090726/10044033/569def66-61ef-11e5-839a-d8ee054dd102.png)

Any ideas? Any help would be great.
I already used this strategy before (resolving dependencies that a parent component has resolved. Should be the same instance).

Could the router be blocking the instances?

Best regards,
Tiago Braga

**Comment by pkozlowski-opensource** [comment]
For a start the "ReferenceError: NavigationMapper is not defined" would probably mean that you are not importing it (ES6 import) in your code. Share a plunk so we can help more.

**Comment by TiagoBraga39** [comment]
@pkozlowski-opensource I forgot to say that I am importng on both components

**Comment by mgechev** [comment]
I think there're a couple of problems here:
- Incorrect use of `ComponentMetadata` and `ViewMetadata`. Both are not decorators, instead you need to use `Component` and `View` (take a look [here](https://github.com/angular/angular/blob/cc0c30484f52ceff81a95318c883ffe7eb280fa1/modules/angular2/src/core/metadata.ts#L536-L547))
- You haven't declared `navigationMapper` as property of `Shell` 

However, none of the issues above is related with the problem you have. [Here's a repo](https://github.com/mgechev/app-navigation-mapper-reproduce) where I tried to reproduce your issue, unfortunately without any results.

**Comment by pkozlowski-opensource** [comment]
> Incorrect use of ComponentMetadata and ViewMetadata

This depends on the setup. This would work with traceur. 

> I tried to reproduce your issue, unfortunately without any results.

This is why I've asked for a plunk - there is just not enough context to help here.

**Comment by TiagoBraga39** [comment]
I am using traceur yes.
I know, I am working on the plunkr which still has some issues.

**Comment by mgechev** [comment]
@pkozlowski-opensource @TiagoBraga39 ah, my mistake. Excuse me for my ignorance.

**Comment by TiagoBraga39** [comment]
My plunkr keeps on sending this:
![image](https://cloud.githubusercontent.com/assets/8090726/10046213/3d84ddea-61ff-11e5-8666-86cd6fa71297.png)

This only happens with the router in the constructor (I searched on github for the error, but nothing solved)...

This is the plunkr: http://plnkr.co/edit/HC9qA16QiSt8TZMwziZN?p=preview
Keep in mind this is not happening in my "real" code.

Best regards,
Tiago Braga

**Comment by pkozlowski-opensource** [comment]
@TiagoBraga39 is router essential to reproducing your pb? If not - drop it.

**Comment by TiagoBraga39** [comment]
Getting the same error while instanciating: http://plnkr.co/edit/HC9qA16QiSt8TZMwziZN?p=preview

**Comment by pkozlowski-opensource** [comment]
@TiagoBraga39 you are trying to use type annotations with Babel - I'm not sure it supports those...

**Comment by TiagoBraga39** [comment]
@pkozlowski-opensource  removed types. Still the same :/
http://plnkr.co/edit/0XaZLeiaUPZO9woQ0dzI?p=preview

**Comment by brandonroberts** [comment]
@TiagoBraga39 You had a couple of typos in your example. Here is a working example

http://plnkr.co/edit/OVSfJ0xqUpPH7XIW6wag?p=preview

**Comment by pkozlowski-opensource** [comment]
@brandonroberts are you sure you've linked a good plunk? Look at the console, it is full of errors.

**Comment by brandonroberts** [comment]
@pkozlowski-opensource missed a typo myself. It should be correct now

**Comment by pkozlowski-opensource** [comment]
@brandonroberts yep, it works OK now. Thnx for helping out!
@TiagoBraga39 I hope it answers your question, at least with this setup. Let's move this discussion to gitter since I don't think we are seeing a bug here.

**Comment by TiagoBraga39** [comment]
@brandonroberts Thank you very much for helping!
@pkozlowski-opensource 
Well, I told you this second bug was not my original issue. It was an issue that only showed up on plunkr (because in my local project I use traceur, which does not need that Component.parameters property and goes fine with types)...

So the issue is still up, but I agree this is more of a gitter discussion. I will ask about the issue there, to avoid creating more issue threads.

Thank you very much for your time!

Stay awesome,
Tiago Braga
