### ISSUE TITLE
TypeError by using locale Angular-Template

### ISSUE THREAD

**Issue by maravondra** [angular/angular#43354]
I have followed tutorila in medium.com about create lib-componente in angular (tutorial). In short I did:

1 - Create lib-project with comand:

`ng generate library mv-logo`
2 - Build library

`ng build --configuration production `
3 - Create link

I am sure that link was created, because I check the list of all with command

`npm list -g`

```
usr/local/lib
├── mv-logo@0.0.6 -> ./../../../Users/vondramk/Documents/angular/lib-workspace/dist/mv-logo
```

If I start this template in my app it is showed immer the same error code.

```
main.ts:12 TypeError: Cannot read property 'bindingStartIndex' of null
  at Module.ɵɵelementStart (core:14847)
  at MvLogoComponent_Template (mv-logo.component.ts:6)
  at executeTemplate (core.js:9598)
  at renderView (core.js:9402)
  at renderComponent (core.js:10682)
  at renderChildComponents (core.js:9267)
  at renderView (core.js:9427)
  at renderComponent (core.js:10682)
  at renderChildComponents (core.js:9267)
  at renderView (core.js:9427)
```

**Comment by maravondra** [comment]
Hi @atscott , please is it some error which will be fixed in some future releases?

**Comment by petebacondarwin** [comment]
I think the `locale` in the title is a redherring here. So I have removed the i18n label.
@maravondra - please can you provide more specific steps to reproduce the problem, or perhaps share a git repository we can look at?

**Comment by maravondra** [comment]
Hello @petebacondarwin , yes of course. I am glad to share all with you.

1) Library you can find here [library](https://github.com/maravondra/angular_library). This library componete was with `ng generate library mv-logo`

2) Build the library-component. Go in Folder `cd projects/mv-logo` and build

`ng build mv-logo --configuration production`

3) go to  dist-folder due to create link

```
cd ../../dist/mv-logo
npm link mv-logo
```

4) <optional> check  if the link was created correct
`npm list -g`

5) Using the local library in [project](https://github.com/maravondra/using_lib)

Thank you very much for

**Comment by petebacondarwin** [comment]
I'll take a look next week.

**Comment by petebacondarwin** [comment]
I can't actually even build the libraries...

**Comment by petebacondarwin** [comment]
Also the package-lock.json appears to be invalid?

**Comment by JoostK** [comment]
This is a duplicate of #35586. When linking a library, it's typical for another copy of `@angular/core` to become included in the bundle which prevents sharing the runtime state, causing errors like these. This can typically be resolves using `"preserveSymlinks": true` in the Angular builder (see [here for details](https://github.com/angular/angular/issues/35586#issuecomment-598067833)).

**Comment by maravondra** [comment]
> "preserveSymlinks": true

super... thank you very much....
