### ISSUE TITLE
Disabled initial navigation responds to history change

### ISSUE THREAD

**Issue by zehavibarak** [angular/angular#43356]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

We're importing the router package with initialNavigation: 'disabled' option.

However, the router responds to location change and tries to resolve url.

The `setUpLocationChangeListener` is called decpite initial navigation been disabled in appInitializer.

```js
 if (opts.initialNavigation === 'disabled') {
                router.setUpLocationChangeListener();
                resolve(true);
            }
```

**Comment by atscott** [comment]
This is working as expected. `initialNavigation === 'disabled'` does not mean that the router will not sync with browser navigation events. This behavior is also documented:

>'disabled' - The initial navigation is not performed. The location listener is set up before the root component gets created. Use if there is a reason to have more control over when the router starts its initial navigation due to some complex initialization logic.


https://angular.io/api/router/InitialNavigation#description
