### ISSUE TITLE
docs: jsdoc links unable to read file

### ISSUE THREAD

**Issue by wSedlacek** [angular/angular#43357]
### Description

Attempting to open JSDoc links fail in VSCode

### Please provide the steps to reproduce the issue

Import `HttpClient` in VSCode then hover over the symbol to get a tooltip and click on `HTTP Guide` link.

### Please provide the expected behavior vs the actual behavior you encountered

I would expect the [HTTP Guide](https://angular.io/guide/http) to open, perhaps even versioned with the version of Angular installed.

What actually happens is I get an error due to the missing relative path.

### Please provide a screenshot if possible

![Screen Shot 2021-09-05 at 14 23 20](https://user-images.githubusercontent.com/8206108/132141804-7e1d0ec5-d492-4a5e-9e2c-bcc6e9d619a6.png)

### Please provide the exception or error you saw

```
Unable to read file '/guide/http' (Error: Unable to resolve non-existing file '/guide/http')
```

**Comment by petebacondarwin** [comment]
Hmm, this is a bit of a tricky problem.

These links were never designed to be clickable from the IDE. They are there because they get rendered in angular.io API pages: https://angular.io/api/common/http/HttpClient#see-also.

They are also not clickable in GitHub when looking directly at the source code either: https://github.com/angular/angular/blob/12.2.4/packages/common/http/src/client.ts#L105

I guess we might be able to get it to work by changing all such links to be relative to the file itself. But this would be very difficult to maintain.

**Comment by petebacondarwin** [comment]
@aikidave - what do you think?

**Comment by wSedlacek** [comment]
Maybe some post processing of the JSDocs before they get published as an npm package could be done?

**Comment by gkalpak** [comment]
Just to be clear, this is about the quick info shown as part of a TS intellisense when using the **published** Angular packages (not when reading the source code in VSCode). So, making links relative to the source file path would not help.

Ideally, we should process such links to make them actual URLs (pointing to `vX.angular.io/...`), but I am sure if our current tooling would cater to something like that 🙈

**Comment by wSedlacek** [comment]
> Just to be clear, this is about the quick info shown as part of a TS intellisense when using the published Angular packages 

Yes

**Comment by aikidave** [comment]
I like @gkalpak's ideal solution, but I do not know the full scope of impact of such a change. Is there a way we could gauge the impact this change would have on the community?

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
