### ISSUE TITLE
@angular/localize 12.2.4 still using vunerable version 1.0.6 of path parse

### ISSUE THREAD

**Issue by praveenphoenix42** [angular/angular#43358]
@angular/localize 12.2.4 is still using vunerable version 1.0.6 of path parse. It is vulnerable to Regular Expression Denial of Service (ReDoS) via splitDeviceRe, splitTailRe, and splitPathRe regular expressions. ReDoS exhibits polynomial worst-case time complexity. 

@angular/localize should use latest version at least 1.0.7 of path parse.

**Comment by petebacondarwin** [comment]
I just installed `@angular/localize` in a blank project and the version of `path-parse` is 1.0.7.
I believe you just need to update your lock file to get your project to update to the latest version.
