### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by Mayur2306** [angular/angular#43368]
Below is the issue and solution as well

Issue since angular 9 not allowing number as formGroupName. This is due to strict type checking in angular.Below solution worked for me.

ERROR CODE : <ng-container *ngFor="let configurationCtrl of configurationForm.get('configurations').value; let i = index" [formGroupName]="i">

SOLUTION : <ng-container *ngFor="let configurationCtrl of configurationForm.get('configurations')['controls']; let i = index" [formGroupName]="i">

Note : I  replaced value with controls

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
