### ISSUE TITLE
Using <source> inside <picture> in an angular component leads to multiple image requests in safari

### ISSUE THREAD

**Issue by maximilianochs** [angular/angular#43389]
### Which @angular/* package(s) are the source of the bug?

platform-browser, Don't known / other

### Is this a regression?

No

### Description

I've created a component that generates a `picture` tag with multiple `source` elements and one `img` tag for different viewports and devices. The html looks something like this: 

```html
<picture>
  <source srcset="https://via.placeholder.com/400.webp" type="image/webp" media="(max-width: 400px)">
  <source srcset="https://via.placeholder.com/400.jpg" type="image/jpeg" media="(max-width: 400px)">
  <source srcset="https://via.placeholder.com/800.webp" type="image/webp">
  <source srcset="https://via.placeholder.com/800.jpg" type="image/jpeg">
  <img src="https://via.placeholder.com/800.png" alt="">
</picture>
```

Chrome and Firefox behave as expected: On Devices with a max-width of 400px, the first webp image is used and everything else is ignored. As soon as the viewports width exceeds 400px, the 800px webp image is used. The jpeg fallback images and the one png image specified in the img-tags src attribute are ignored. 

But Safari doesn't care about our bandwidth and loads the first fitting webp-image AND the fallback image specified in the img-tag. 

Example: https://angular-ivy-8fpphn.stackblitz.io/

At first, I assumed that his was a bug with safari. However, if you open a static html page with the same markup you see above, even safari behaves correctly and only loads the first fitting webp image. 

To test this, just copy the `html` from above in a new html file, serve it statically on your local machine and open the network inspector tab in safari.  

Even with server side rendering enabled, safari still loads more than one image (though I can't provide a quick example for that right now, sorry)

Any idea what's causing this behavior? 

### Please provide a link to a minimal reproduction of the bug

https://angular-ivy-8fpphn.stackblitz.io/

### Please provide the exception or error you saw

```true
If you open the network inspector tab in safari, you can see that multiple images are being loaded.
```

### Please provide the environment you discovered this bug in

```true
OS: MacOS 11.5.2
Browser: Safari 14.1.2
Angular: 12.1.0
```

**Comment by sorin-davidoi** [comment]
This seems like a Safari bug and not something related to Angular: https://github.com/facebook/react/issues/15215.

**Comment by pkozlowski-opensource** [comment]
Correct, this looks like a browser specific issue. Sadly we can't do much here...
