### ISSUE TITLE
Angular 10  hook ngAfterViewInit() not working as expected

### ISSUE THREAD

**Issue by Madhu-nair** [angular/angular#43396]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

i have migrated from `Angular 9.1 ` to `Angular 10.2`  everything is working fine except ngAfterViewInit() where data is still loading when you keep debugger in the above hook .

` this.elementRef.nativeElement.querySelector(
      '[element]'
    ).appendChild(data);`

previously this used to work in angular 9 but in angular 10 it  throws null pointer exception.

### Please provide the environment you discovered this bug in

```true
Angular CLI: 10.2.3
Node: 14.17.6
OS: darwin x64

Angular: 10.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.3
@angular-devkit/build-angular   0.1002.3
@angular-devkit/core            10.2.3
@angular-devkit/schematics      10.2.3
@angular/cdk                    8.2.3
@angular/cli                    10.2.3
@schematics/angular             10.2.3
@schematics/update              0.1002.3
rxjs                            6.6.7
typescript                      4.0.8
```

### Anything else?

The logic seems to work in  angular 9 but the logic inside angular 10 does not work  -out of 10 may be 3 times it works

**Comment by pkozlowski-opensource** [comment]
Could you please provide a minimal stackblitz that shows the described behaviour?

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
