### ISSUE TITLE
benchpress: rewrite chromedriver integration to use tracing data

### ISSUE THREAD

**Issue by tbosch** [angular/angular#434]
Right now we are using the old timeline data. However, the Timeline in DevTools already uses tracing data.

See https://sites.google.com/a/chromium.org/chromedriver/logging/performance-log

Use category `disabled-by-default-devtools.timeline`

Open problem: How to get the process id of a page in chromedriver, as the performance log contains all tabs

**Comment by tbosch** [comment]
Done.

**Comment by 66eli77** [comment]
Hi, I try to get the new format timeline data from performance log(I already got the old format data and able to display it on older chrome devtools). I followed the instructions from the webpage you listed above, but had no luck to enable tracing log even with  capabilities['perfLoggingPrefs'] = {'tracingCategories':'disabled-by-default-devtools.timeline'}     I'm writing in python.
I wonder if you have any clues on this. Thank you beforehand : )

**Comment by tbosch** [comment]
Hi,
can you verify that you used the right capabilities?
For a full example, see here: https://github.com/jeffbcross/benchpress-tree/blob/master/protractor.conf.js#L6

**Comment by 66eli77** [comment]
hiya, Thank you so much for your quick response! my problem is solved by using the latest version of Chromedriver.

**Comment by axemclion** [comment]
@tbosch In http://github.com/axemclion/browser-perf, I use [this](https://github.com/axemclion/browser-perf/blob/81ab4ac73df05b672ae28cf3a9cef8fa60837e9d/lib/metrics/util/RenderingStats.js#L44) to find the processId. Basically assumes that no other tab is open, and pick up the title of the page.

This also fails if the page does not have a title.
