### ISSUE TITLE
Template variables: documentation contradictory about template input variables vs template variables

### ISSUE THREAD

**Issue by Chealer** [angular/angular#43405]
### Description

Angular features what it calls "template variables", as well as what it calls "template input variables". Linguistic logic and the fact that [the documentation for the latter](https://angular.io/guide/template-reference-variables#template-input-variable) is part of the documentation for the former would want template input variables to be template variables. Yet, the last section contradicts that:

> In contrast, you declare a template variable by prefixing the variable name with #, as in #var.

> Template input variables and template variables names have their own namespaces. The template input variable hero in let hero is distinct from the template variable hero in #hero.

Note that the URL of the documentation for template variables suggests they may be called "template reference variables".

I really do not know what the right solution to this problem is, but I imagine that if there is actually a dichotomy between "template variables" and "template input variables", the former should be renamed.

### What is the affected URL?

https://angular.io/guide/template-reference-variables#template-input-variable

### Please provide the steps to reproduce the issue

This does not report a behavioral bug.

### Please provide the expected behavior vs the actual behavior you encountered

This does not report a behavioral bug.

### Please provide the exception or error you saw

```true
This does not report a behavioral bug.
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
No
```

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
