### ISSUE TITLE
Angular 13 routerLink migration makes invalid change

### ISSUE THREAD

**Issue by mcalmus** [angular/angular#43416]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When migrating from Angular 12 to 13 the `Migrates '[routerLink[=""' in templates to '[routerLink]="[]" because these links are likely intended to route to the current page with updated fragment/query params.` migration incorrectly modified a component.

### Please provide the exception or error you saw

```true
Have a component that looks like this:

@Component({
  selector: 'my-component',
  template: `
    <div class="a-logo">
      <div class="a-logo__text">
        <div class="a-logo__text-top">TOP</div>
        <div class="a-logo__text-middle">MIDDLE</div>
        <div class="a-logo__text-bottom">BOTTOM</div>
        <div class="a-logo__bar"></div>
      </div>
    </div>`,
  styleUrls: ['./my-component.component.css', '../another-dir/antoehr-file.css']
})
export class MyComponent {}
```

After migration the file was changed such the final line looks like:

```    </div>  </div>`,```
```


### Please provide the environment you discovered this bug in

```true
Angular CLI: 13.0.0-next.4
Node: 14.15.0
Package Manager: npm 7.21.0
OS: win32 x64

Angular: 13.0.0-next.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                          Version
---------------------------------------------------
@angular-devkit/architect        0.1300.0-next.4
@angular-devkit/build-angular    13.0.0-next.4
@angular-devkit/core             13.0.0-next.4
@angular-devkit/schematics       13.0.0-next.4
@angular/cdk                     13.0.0-next.4
@angular/cli                     13.0.0-next.4
@angular/material                13.0.0-next.4
@schematics/angular              13.0.0-next.4
rxjs                             6.6.7
typescript                       4.3.5
```

**Comment by atscott** [comment]
@mcalmus Can you please provide a sample project? The problem cannot be reproduce with the given example. The migration doesn't even apply to the template since there's no bound attribute with the name `routerLink`.

**Comment by mcalmus** [comment]
@atscott Yeah. It certainly shouldn't match since it has no routerLink. I was able to replicate by moving the component into a bare project. The only thing different from what I pasted in are names and the inclusion of CSS. Can I provide code privately for replication?

**Comment by atscott** [comment]
@mcalmus - If you were able to reproduce it by moving the component to a bare project, can you share that bare project + the component? You can also look at removing some of the private information from that reproduction until it's down to something you're comfortable sharing.

**Comment by mcalmus** [comment]
Ended up being easier than I expected.
[my-logo.component.txt](https://github.com/angular/angular/files/7170021/my-logo.component.txt)

**Comment by mcalmus** [comment]
Ended up being easier than I expected.
[my-logo.component.txt](https://github.com/angular/angular/files/7170040/my-logo.component.txt)

**Comment by atscott** [comment]
@mcalmus I was again not able to reproduce this with that component added to a CLI project with no other changes. Can you share a project where I can simply run `ng update --next @angular/core` to reproduce the issue?

**Comment by mcalmus** [comment]
This should work after installing from npm using migrate-only. I reproduced on both macOS and Windows.

`ng update --migrate-only --from=12 --to=13 @angular/core`

[test-angular.tar.gz](https://github.com/angular/angular/files/7189934/test-angular.tar.gz)

**Comment by mcalmus** [comment]
This should work after installing from npm using migrate-only. I reproduced on both macOS and Windows.

`ng update --migrate-only --from=12 --to=13 @angular/co`
[test-angular.tar.gz](https://github.com/angular/angular/files/7194718/test-angular.tar.gz)
re
