### ISSUE TITLE
Question: Accessing files near workspace configuration files.

### ISSUE THREAD

**Issue by aminkosh** [angular/angular#43418]
Hi,

I have some generated txt  files near the package.json, angular.json, package-lock.json, etc... Is there any way to access this files and read their content in typscript?
I am asking it, because these files are out of project structure but i need them. 

Any help appreciated

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
