### ISSUE TITLE
Why don't reactive forms have a 'message' field directed to each validator's messages?

### ISSUE THREAD

**Issue by CarvalhoWesley** [angular/angular#43423]
### Description

It would be very useful if the reactive forms had the possibility to add messages for each validator. This would make it easier to change the text of messages when needed.

### Proposed solution

TS:

```
this.form = this.fb.group({
    name: [
      '',
      [
        Validators.required({ message: 'Field required' }),
        Validators.minLength({ lenght: 15, message: 'Min. length: {0}' }),
      ],
    ],
  });
```

HTML:

```
<label *ngIf="this.form.get('name').hasError('required') && this.form.get('name').touched">
  {{this.form.get('name').errors.get('required').message}}
</label>
```

### Alternatives considered

Something similar to flutter's reactive forms:

![image](https://user-images.githubusercontent.com/19750283/132898925-8231906a-cd0a-41c4-92f1-ed3b5d2e6441.png)

**Comment by indraraj26** [comment]
basically this should be {{this.form.get('name').errors.message}}

So that it will apply the message according to validation error.

1. For this i have been using validationList which will iterate using NgFor but that was causing the change detection.
2.  Now i have moved out this ngFor to pipe so that it will not Re-render multiple times even if source is not changed.

**Comment by AndrewKushnir** [comment]
Hi @CarvalhoWesley, thanks for creating this feature request. We'll discuss it during one of the upcoming team syncs and provide an update on whether we decide to move forward with this feature or not. Thank you.

**Comment by CarvalhoWesley** [comment]
Hi @AndrewKushnir, thanks for the answer. I identified some bugs and thought of some improvements to my code, I think I was a bit hasty when sending the pull request, but I will wait for your response after the team syncs and I will make a new pull request with the appropriate ones changes.

**Comment by dylhunn** [comment]
Closing as per [this comment](https://github.com/angular/angular/pull/46449#issuecomment-1165006664).
