### ISSUE TITLE
Manual refresh or entering directly to a url takes me to home page

### ISSUE THREAD

**Issue by usamadanish4** [angular/angular#43432]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I have two routes
`/` and `/details/:number` both are publicly accessible, but when I directly enter to `details/:number` routes it takes me to the home page and when I refresh staying at `/details/:number` page it takes me to the home page again

**Comment by yuvgeek** [comment]
Can you share the stackblitz URL to reproduce this issue?

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).
