### ISSUE TITLE
NGx formly in Angular library?

### ISSUE THREAD

**Issue by ajay312** [angular/angular#43434]
Hi Team
We are creating library using NGx formly. could we implement NGX formly in Angular Library?

**Comment by petebacondarwin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).
