### ISSUE TITLE
Navigating back using browser UI causes unexpected NavigationCancel event on firefox

### ISSUE THREAD

**Issue by kosmoz** [angular/angular#43447]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

When trying to navigate back to a previous route using either the browser's back button, the mouse button or even `history.back()` (via the JavaScript console), a `NavigationCancel` event with `reason` "Navigation ID x is not equal to the current navigation id x+1" is emitted and no navigation occurs. 

For this behavior to occur, the following must be true:
- Using Firefox (I used 91.0.2 on Linux and 68.0.2 on Windows 10),
- Using `useHash: true` in router config and
- Using a Resolver with at least one millisecond of delay (using rxjs or Promise).

The bug does not occur on Chrome and Edge and although we observed a similar bug in Safari, it does not occur using the minimal reproduction repo.

### Please provide a link to a minimal reproduction of the bug

https://github.com/kosmoz/routertest

### Please provide the exception or error you saw

```true
12:20:55.658 Routing: NavigationStart app.component.ts:47:18
12:20:55.659 Routing: RoutesRecognized app.component.ts:49:18
12:20:55.659 Routing: GuardsCheckStart app.component.ts:57:18
12:20:55.660 Routing: ChildActivationStart app.component.ts:61:18
12:20:55.660 Routing: ActivationStart app.component.ts:65:18
12:20:55.660 Routing: GuardsCheckEnd app.component.ts:59:18
12:20:55.660 Routing: ResolveStart app.component.ts:53:18
12:20:55.660 BResolver: resolve called resolvers.ts:20:12
12:20:55.662 Routing: NavigationCancel: Navigation ID 3 is not equal to the current navigation id 4 app.component.ts:70:18
```

### Please provide the environment you discovered this bug in

```true
Browser: Firefox 91.0.2
Angular CLI: 12.2.5
Node: 16.8.0 (Unsupported)
Package Manager: npm 7.21.1
OS: linux x64

Angular: 12.2.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.5
@angular-devkit/build-angular   12.2.5
@angular-devkit/core            12.2.5
@angular-devkit/schematics      12.2.5
@schematics/angular             12.2.5
rxjs                            6.6.7
typescript                      4.3.5
```

### Anything else?

When using a delay of 1 millisecond in the resolver, the bug occurs only occasionally. I noticed that the `NavigationCancel` event is emitted 1-3 milliseconds after the resolve method is called.

**Comment by kosmoz** [comment]
Maybe related to https://github.com/angular/angular/issues/43446?

When I set the Angular version to 12.2.1, a `NavigationCancel` event is still emitted but the navigation completes regardless.

**Comment by atscott** [comment]
This should be resolved by https://github.com/angular/angular/commit/0e8548f667e5fdefa3ac7cdf1ba47e3e17011ffc which will be included in the patch release this week. I'll keep this open for now until we can confirm that's the case.

**Comment by atscott** [comment]
I verified that this now works with `12.2.6`. The first navigation does get canceled but the new one completes without error. The duplicate navigation will be resolved in v13 (see https://github.com/angular/angular/issues/43446#issuecomment-919363041)
