### ISSUE TITLE
Unclear messaging around app and library version differences

### ISSUE THREAD

**Issue by HazzMan2409** [angular/angular#43458]
### Description

[Here](https://angular.io/guide/creating-libraries#ensuring-library-version-compatibility) it states "_The Angular version used to build an application should always be the same or greater than the Angular versions used to build any of its dependent libraries. For example, if you had a library using Angular version 12, the application that depends on that library should use Angular version 12 or later. Angular does not support using an earlier version for the application._".

Apologies if I have misunderstood this, but I am fairly sure that you should not have an application that uses a different major version than the libraries it consumes. So if I have an app which uses version 12 it should not consume a library that is version 11. The docs should explicitly state this, as it does for the case when the library is a greater version than the application.

### What is the affected URL?

https://angular.io/guide/creating-libraries#ensuring-library-version-compatibility

**Comment by petebacondarwin** [comment]
It is quite common for library authors to build their library using an earlier version of Angular so that it can be consumed by applications built with a variety of later versions. So this description is accurate.

Generally it is uncommon for breaking changes between major versions of Angular to affect the public API of a library, so it mostly safe to do this.

**Comment by HazzMan2409** [comment]
@petebacondarwin Thanks for the explanation. The thing that made me think along those lines was the peer dependency warnings (a library will have peer dependencies of a specific version of Angular) when installing the library. Am I good to just ignore those?

**Comment by petebacondarwin** [comment]
It is definitely worth noting peer dependency versions for the libraries that you use. If there is a warning but you test it and it works for you, then I think you are safe.

Interestingly, I note that ngxs is built with v5 and has a peer dependency on `@angular/core` of `^5.0.0` which should preclude v6+, but I know that they actually test against all versions of Angular from 5 onwards so it is safe to use their library for all these versions.
