### ISSUE TITLE
hasValidator "@angular/forms": "12.2.5" not working

### ISSUE THREAD

**Issue by sysmat** [angular/angular#43454]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

in unit test, I want to check validators in form control

```typescript
this.userForm = this.formBuilder.group({
      orgId: null,
      name: [null, [Validators.required, Validators.minLength(3), Validators.maxLength(30)],
        [specialCharAsyncValidator(this.infoService)]
      ],
....
get orgIdCtrl(): AbstractControl { return this.userForm.get('orgId'); }
get nameCtrl(): AbstractControl { return this.userForm.get('name'); }
```

```typescript
it('form control check for validators', () => {

    expect(component.orgIdCtrl.hasValidator(Validators.required)).toBeFalse();

    const nameCtrl = component.nameCtrl;
    expect(nameCtrl.hasValidator(Validators.required)).toBeTruthy(); // OK
    expect(nameCtrl.hasValidator(Validators.minLength(3))).toBeTruthy(); // it is false, so NOT OK
    expect(nameCtrl.hasValidator(Validators.maxLength(30))).toBeTruthy(); // it is false, so NOT OK
    expect(nameCtrl.hasAsyncValidator(specialCharAsyncValidator(infoService))).toBeTruthy(); // it is false, so NOT OK

  });
```

### Please provide the exception or error you saw

```true
1) form control check for validators
     testing AddComponent
     Error: Expected false to be truthy.
    at <Jasmine>
    at UserContext.<anonymous> (src/app/components/user-add/add/add.component.spec.ts:86:60)
```

### Please provide the environment you discovered this bug in

```true
❯ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.5
Node: 14.15.4
Package Manager: npm 6.14.10
OS: win32 x64

Angular: 12.2.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.5
@angular-devkit/build-angular   12.2.5
@angular-devkit/core            12.2.5
@angular-devkit/schematics      12.2.5
@schematics/angular             12.2.5
rxjs                            7.3.0
typescript                      4.3.5
```

**Comment by destus90** [comment]
Maybe this is because `Validators.minLength(3)` gives you another reference after calling that static method inside your test function.

**Comment by sysmat** [comment]
Yes, it is a different reference

> The validator to check for presence. Compared by function reference.

So it is not testable

**Comment by sysmat** [comment]
my test is about to test form in component, not to have it in tests, so if somebody change form, test should fail

**Comment by sysmat** [comment]
Even if I define validators func in component still not work, maybe because of testbed:

- in component

```typescript
min3 = Validators.minLength(3);
...
name: [null, [Validators.required, this.min3, Validators.maxLength(30)],
        [specialCharAsyncValidator(this.infoService)]
      ],

```
- in test `expect(nameCtrl.hasValidator(component.min3)).toBeTruthy();`

bit is still false

**Comment by sysmat** [comment]
Even if I declere as static validator func not working:

- component:

```typescript
static min3 = Validators.minLength(3);
...
name: [null, [Validators.required, AddComponent.min3, Validators.maxLength(30)],
```

- test
```typescript
expect(nameCtrl.hasValidator(AddComponent.min3)).toBeTruthy(); // it is still false
```

**Comment by jnizet** [comment]
If I try to reproduce the issue (with a validator stored as in instance variable of the component), I can't: the test passes as I expected. 
See https://github.com/jnizet/has-validator-repro.

@sysmat My test passes, so my guess is that yours fails for a different reason. But IMHO, this is not the best way to test your component anyway: testing that a control has a validator `min3`, which could be... any validator, doesn't really test a requirement. IMHO, it would be best to treat the component as a black box and write the test as an end user would test it:
- fill the input with 2 characters
- check that an error is displayed informing that the field must contain at least 3 characters
- fill the input with 3 characters
- check that the error disappears

**Comment by dylhunn** [comment]
> Maybe this is because Validators.minLength(3) gives you another reference

This is the answer.

`hasValidator` checks for the presence of the **exact same function**. Therefore, it works with `Validators.required`, but not with `Validators.min(9)`, which returns a new function.

This is the same design as event handlers in JS -- they are just functions, and you need to keep references to them to check if they are present.

Conceptually this is a pretty major shortcoming of how validators work, but barring a redesign, this is working as intended.
