### ISSUE TITLE
TitleCasePipe performs incorrect transformation for word starting with digit

### ISSUE THREAD

**Issue by 95th** [angular/angular#43459]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Word such as `2nd` is transformed to `2Nd` which is incorrect. 

Expected Behavior is that the word remains unchanged. If input word was `2ND` it should change to lowercase `2nd`

### Please provide the exception or error you saw

```true
No exception
```

**Comment by petebacondarwin** [comment]
Reproduction https://stackblitz.com/edit/angular-ivy-srb5cc?file=src%2Fapp%2Fapp.component.html
