### ISSUE TITLE
Extend Management of AbstractControl.errors

### ISSUE THREAD

**Issue by JaimeStill** [angular/angular#43480]
### Which @angular/* package(s) are relevant/releated to the feature request?

forms

### Description

When manually implementing asynchronous validation on reactive forms, there is no standard way of adding and removing error states without fully affecting additional error states that may be present.

### Proposed solution

The following function worked for my use case, but it would be nice to see a formal means of adding / removing error states from an `AbstractControl`:

```ts
private setErrorState = (control: AbstractControl, error: string, value?: boolean) => {
  if (value) {
    const errors = control.errors
      ? {
        ...control.errors,
        [error]: value
      }
      : {
        [error]: value
      }

    control.setErrors(errors);
  } else if (control.errors) {
    if (control.errors.hasOwnProperty(error))
      delete control.errors[error];

    if (Object.keys(control.errors).length > 0)
      control.setErrors(control.errors);
    else
      control.setErrors(null);
  }
}
```

This function is implemented in a service that I wrote for registering asynchronous validators, which execute when the validator is registered if the target control has a value, and any time the target control changes (filtered with `debounceTime` and `distinctUntilChanged` to optimize the execution of the validation):

```ts
registerValidator = async <T>(
  validator: (obj: T) => Promise<boolean>,
  form: FormGroup,
  control: AbstractControl,
  error: string = 'api'
): Promise<Subscription> => {
  if (control.value) {
    const res = await validator(form.value);
    this.setErrorState(control, error, res ? null : true);
  }

  return control
    .valueChanges
    .pipe(
      debounceTime(350),
      distinctUntilChanged()
    )
    .subscribe(async (value: string) => {
      if (value) {
        const res = await validator(form.value);
        this.setErrorState(control, error, res ? null : true);
      } else
        this.setErrorState(control, error);
    });
}
```

Fully functional demo: https://jaimestill.github.io/async-form-validation/  
Source: https://github.com/JaimeStill/async-form-validation

### Alternatives considered

I initially wanted to use the native method of registering custom `asyncValidators`, but the approach did not suit the intended strategy the way this has. With this, I can send the object represented by the form to my validation function, but still target the `FormControl` relevant to the property I am validating. Additionally, I am able to have the validation execute in an efficient manner based on the target `FormControl` value changes, further optimized by filtering with RxJS.

**Comment by garrettld** [comment]
If I'm understanding your problem correctly, you can accomplish everything you need without having to call setErrors explicitly.

There are a number of ways to accomplish this, but here's one that avoids `setErrors` and avoids any `subscribe`s that might cause memory leaks:

```typescript
function buildValidator<T>(
  validator: (obj: T) => Observable<boolean>,
  error: string = 'api'
): AsyncValidatorFn {
  const values = new ReplaySubject<T>(1);
  let previousValidationResult: ValidationErrors | null = null;
  const validationErrors = values.pipe(
    debounceTime(500),
    // double startWith to get past pairwise
    startWith(null),
    startWith(null),
    pairwise(),
    switchMap(([previousValue, currentValue]) => {
      if (previousValue === currentValue) {
        return of(previousValidationResult);
      }
      return validator(currentValue).pipe(
        // should probably put a catchError() here
        map((errored: boolean): ValidationErrors | null =>
          errored ? { [error]: true } : null
        ),
        tap((validationResult: ValidationErrors | null) => {
          previousValidationResult = validationResult;
        })
      );
    }),
    // could use publishReplay(1) instead of share(...) if you're on rxjs v6
    share({
      connector: () => new ReplaySubject(1),
      resetOnError: false,
      resetOnComplete: false,
      resetOnRefCountZero: false,
    })
  );

  return (control: AbstractControl): Observable<ValidationErrors | null> => {
    values.next(control.value);
    // skip(1) to skip the previous validation result, because it'll be emitted again
    // anyway if the value hasn't changed.
    return validationErrors.pipe(skip(1), take(1));
  };
}
```

Working example: https://stackblitz.com/edit/angular-ivy-fff3wr?file=src/app/app.component.ts

**Comment by JaimeStill** [comment]
@garrettld my issue is more of a request for further fleshing out the API of interacting with the error state of the form in the event that you want to manually handle error state (in my case, I don't want to work with an `AsyncValidatorFn` because I would rather have fine-tuned control over when the validation occurs). Also, in my solution memory leaks are prevented in that the `Subscription` generated by the `registerValidator` function is returned to be handled by the caller.

**Comment by dylhunn** [comment]
To be honest, I think this is probably not something we are going to consider for implementation. If the built in async validator support isn't sufficiently useful, we should be asking why and addressing the root cause instead.
