### ISSUE TITLE
404 routing

### ISSUE THREAD

**Issue by MatthewShelby** [angular/angular#43481]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Hi.
I have been trying to resolve the "Not Found" issue on my website.
I have been tried this: https://stackoverflow.com/a/26152011

it does not work.
I searched more and I found this: https://stackoverflow.com/a/52495793/11125592
and it solved the problem.
I think it deserves to have considered having been replaced with the one which is exists in the documentation.

### Please provide the environment you discovered this bug in

```true
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.2
@angular-devkit/build-angular   12.2.2
@angular-devkit/core            12.2.2
@angular-devkit/schematics      12.2.2
@schematics/angular             12.2.2
rxjs                            6.6.7
typescript                      4.3.5
```

### Anything else?

I love Angular <3

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
