### ISSUE TITLE
Angular Upgrade 11 -> 12 Error: Error: inject() must be called from an injection context at injectInjectorOnly

### ISSUE THREAD

**Issue by HockeyJustin** [angular/angular#43482]
In line with the protocol, I have tried asking on [StackOverflow](https://stackoverflow.com/questions/69212072/angular-upgrade-error-inject-must-be-called-from-an-injection-context-at-in) first, but am not getting any answers.

I have an angular site:

Site1
- Module1
- Module2
- SharedModule <- NOT in a library, just a module

Site2
- Module3
- Module4
- SharedModule <- calls module in Site1 directly

It was created in Angular 8 and has upgraded just fine so far. But going 11 -> 12, I'm having trouble.

Site1 runs just fine. Site 2 builds, but at runtime errors with the following:

> Error: inject() must be called from an injection context
>     at injectInjectorOnly (core:4745)
>    at Module.ɵɵinject (core:4755)
>     at Object.RouterModule_Factory [as factory] (router:5999)
>     at R3Injector.hydrate (core.js:11438)
>     at R3Injector.get (core.js:11257)
>     at core.js:11295
>     at Set.forEach (<anonymous>)
>     at R3Injector._resolveInjectorDefTypes (core.js:11295)
>     at new NgModuleRef$1 (core.js:25325)
>     at NgModuleFactory$1.create (core.js:25379)

I've researched this extensively, but can't fix it. The error message is meaningless, so I'm just guessing the issue is that shared module.

Reading another github issue, I've tried adding `"preserveSymlinks": true,` to projects.$name.architect.build.options, but that doesn't work. I'm not using `npm link` as the other module isn't a library (I know it should have been set up that way, but it isn't).

I'm facing a lot of work to re-architect the site, so would appreciate any help getting the upgrade to work.

Do you know how to fix this please?

If this can't be fixed, could Angular 13 at least give a more helpful error message / _a build time failure_?

**Comment by JoostK** [comment]
Without a reproduction we're unable to help you here, unfortunately. Can you provide a Github repo with reproduction?

**Comment by HockeyJustin** [comment]
@JoostK  - I'll have a go

**Comment by HockeyJustin** [comment]
I've made a repo [here](https://github.com/HockeyJustin/angularmodulesissue). "Main" is the app with the shared library and "Site1" tries to import it.

This is actually giving a different error, but is similar in that it builds fine but errors at runtime.

Maybe the answer is just to stop working this way completely and move everything over to a library. I've started looking into that [here](https://github.com/HockeyJustin/AngularLibAndMain), but it's a massive amount of work.

As stated, this setup did work fine until Angular 12.

**Comment by JoostK** [comment]
Oh, I see. You have two distinct workspace trees that import from each other. That is bound to suffer from duplicate `@angular/core` versions which confuses the runtime, resulting in the rather obscure runtime error you're seeing. You can workaround this using paths mappings, as explained [in the library guide here](https://angular.io/guide/creating-libraries#use-typescript-path-mapping-for-peer-dependencies) (which also applies to your situation without libs). Not sure why it worked in earlier versions, it has always been prone to these kinds of issues.

**Comment by HockeyJustin** [comment]
Thanks. That fixes my sample, but not my main app. 

I think we probably just need to redo the shared stuff as a library, as it was meant to be.

If the issue is confusion over the cli, I don't understand why it fails at runtime, rather than build time.

I really need to get it going though. The error is so ambiguous. Is there any way of getting more info about the cause please?

**Comment by JoostK** [comment]
The cause is that the two separate workspaces both have their own `@angular/core` packages, and both end up in the bundled application. The Angular runtime keeps its state in top-level module variables that are private to that module, but having two occurrences of that module (from both instances of `@angular/core`) you run into situations where state is only initialized correctly in one instance, not the other. In this case the injection context is only available in the "primary" runtime, but the parts of the app that were bundled from the "secondary" library parts will depend on the "secondary" runtime state.

**Comment by HockeyJustin** [comment]
@JoostK - Thanks for your help. I'll close this issue.
