### ISSUE TITLE
Unable to load JS script via InnerHTML in Angular 11

### ISSUE THREAD

**Issue by harsh13799** [angular/angular#43489]
### Which @angular/* package(s) are the source of the bug?

core, Don't known / other

### Is this a regression?

No

### Description

I have an HTML string in the JSON, which contains some text content, an external js script tag, and an embedded js script tag.
Eg:
<p role="none" class="reading-passage" *ngIf="Item.Content && Item.Content.Text" [innerHTML]="SomeContent | safe: 'html'"></p> 

I need to render that HTML string in any HTML element of the existing angular component. But when I try to do it does not load the external js script and neither it runs the embedded script code.

Could someone please help with it?

Example of stackblitz : 
https://stackblitz.com/edit/angular-dom-sanitization-eg-lrjmfb?file=src/app/app.component.ts

**Comment by jessicajaniuk** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
