### ISSUE TITLE
how to call a function when ng-for has finished

### ISSUE THREAD

**Issue by peishan0528** [angular/angular#4349]
how to call a function when ng-for has finished?

**Comment by pkozlowski-opensource** [comment]
@peishan0528 please direct general support questions like this one to an appropriate support channel: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by gdi2290** [comment]
@peishan0528  what's your goal? you can message me on https://gitter.im at @gdi2290

**Comment by ericmartinezr** [comment]
@peishan0528 check out this issue https://github.com/angular/angular/pull/3991
