### ISSUE TITLE
Asynch Validator is firing API call when it is attached to a formcontrol

### ISSUE THREAD

**Issue by ravisangar** [angular/angular#43509]
Asynch Validator is getting executed when it is attached to a formcontrol during the initial configuration of form.

Here is the scenario:

I have a component that populates form fields on ngOnInit.
As part of populating fields, all the validators are attached to the formcontrol and as soon as it is attached, API call in the asynch validator is getting called.

reviewing the angular code reveals, there is no way to configure to skip the asynch validator execution during initial load.
this is causing a performance issue.

in the addControl method from ng_form.ts, updateValueAndValidity method is always called.

`  addControl(dir: NgModel): void {
    resolvedPromise.then(() => {
      const container = this._findContainer(dir.path);
      (dir as {control: FormControl}).control =
          <FormControl>container.registerControl(dir.name, dir.control);
      setUpControl(dir.control, dir);
      dir.control.updateValueAndValidity({emitEvent: false});
      this._directives.push(dir);
    });
  }`

is there a workaround to stop asynch validator execution in the initial load ( when validator is added to fromcontrol).

**Comment by daniel-seitz** [comment]
We also didn't expect this behavior, rather that the firing happens when the form actually is being used/displayed. Like a cold observable that first needs to be subscribed to.

**Comment by JeanMeche** [comment]
I'd consider this a "work as designed". 

* I'm not sure I get the performance issues, async validators are cancelled if something triggers them while they're not finished executing
* FormControls are an abstraction of a form and independent. Adding a controls triggers an update of the value/status. You might want to check the status of the form independently from the display.

**Comment by JeanMeche** [comment]
Beside my previous comment, I'll close this as we have a more generic issue about this in #54260.
