### ISSUE TITLE
How `const enum HttpStatusCode` works?

### ISSUE THREAD

**Issue by splincode** [angular/angular#43516]
@alan-agius4 @petebacondarwin  Hello, I know that `const enum` doesn't compile to javascript. 

![image](https://user-images.githubusercontent.com/12021443/134041080-e52a801f-a1d2-4af5-9eae-a773cf1e4805.png)

And angular exported:
https://github.com/angular/angular/blob/master/packages/common/http/src/response.ts#L357

But how it works?

![image](https://user-images.githubusercontent.com/12021443/134041183-700fc301-9521-4e8d-af60-9f583ca9473f.png)

I tried to search `preserveConstEnums` in the project, but couldn't find anywhere, how do you do it? :)

![image](https://user-images.githubusercontent.com/12021443/134041534-0ca9ca64-c063-4993-8c3f-3c6818f04345.png)

https://www.typescriptlang.org/tsconfig#preserveConstEnums

**Comment by jessicajaniuk** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by JoostK** [comment]
It's emitted into [the `.d.ts` file of `@angular/common/http`](https://unpkg.com/browse/@angular/common@12.2.6/http/http.d.ts). The numeric values are emitted into your compiled JS instead of references to the enum values (as those won't exist at runtime).

**Comment by splincode** [comment]
@JoostK thank you for your answer! Please, tell me how can we did it (as you) in our pipeline without `preserveConstEnums`?

Because we have a problem:
https://stackblitz.com/edit/taiga-starter-jyc65p?file=src%2Fapp%2Fapp.component.ts

https://github.com/TinkoffCreditSystems/taiga-ui/blob/main/projects/addon-commerce/enums/currency.ts
![image](https://user-images.githubusercontent.com/12021443/134044926-06b7f891-7e3f-49af-9c30-d0b708686d86.png)

**Comment by JoostK** [comment]
Actually `HttpStatusCode` also does not work in that example. `preserveConstEnums` and `isolatedModules cannot be used when a library is compiled without `preserveConstEnums`. There's [loads of issues reported in the TS repo](https://github.com/microsoft/TypeScript/search?l=TypeScript&q=preserveConstEnums&type=issues) that might give more insight.

**Comment by splincode** [comment]
@JoostK https://stackblitz.com/edit/angular-12-form-validation-hwmyaf?file=src%2Fapp%2Fapp.component.ts

sorry, it's work for current example

![image](https://user-images.githubusercontent.com/12021443/134049740-e2bb36c9-a0d6-4fea-b2b9-68503fa26b4c.png)
