### ISSUE TITLE
Add official documentation about injecting Pipes into another Pipes

### ISSUE THREAD

**Issue by ahelmel** [angular/angular#43525]
### Description

I would like to know if it is desirable or a good practice to inject Pipes into another Pipes:
```
import { Injectable, Pipe, PipeTransform } from '@angular/core';

import { FormatPipe } from './format.pipe';

@Pipe({ name: 'message' })
export class MessagePipe implements PipeTransform {
  constructor(private formatPipe: FormatPipe) {}

  transform(value: string): string {
    const message = `Message => ${value}`;
    return this.formatPipe.transform(message);
  }
}
```

I did not find anything on the official documentation page. Maybe it is anti-pattern. It would be great if the official documentation would provide some explanation about this. I found also some other people asking this in several threads, so it would also help them to understand this better.

### Proposed solution

Add some explanation about using/injecting Pipes into another Pipes on the official Angular documentation website.

### Alternatives considered

-

**Comment by angelfraga** [comment]
@ahelmel I just found this ticket by accident and I think this topic is already documented by the chaining pipes section.

https://angular.io/guide/pipes#example-applying-two-formats-by-chaining-pipes

Here it is explain how two pipes might work together. In your example you could apply a `toMessage` pipe followed of the `formatPipe`

eg. `value | toMessage | format`

**Comment by JeanMeche** [comment]
It is not recommended to compose pipes, please read [here](https://github.com/angular/angular/issues/49043#issuecomment-1427909702) for more info on this.
