### ISSUE TITLE
Component interaction error

### ISSUE THREAD

**Issue by aryaarun** [angular/angular#43520]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Fetch API cannot load stackblitz:/node_modules/%40angular/cli/lib/config/schema.json. URL scheme "stackblitz" is not supported.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-bdvuuo?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.html

### Please provide the exception or error you saw

```true
​ Fetch API cannot load stackblitz:/node_modules/%40angular/cli/lib/config/schema.json. URL scheme "stackblitz" is not supported.
```

**Comment by petebacondarwin** [comment]
I do not see the same error as reported here.
What I do notice is that some of the components (the ones loaded via routes) have not been declared in any NgModule, which causes the components to be unaware of other directives such as `NgIf`.
Adding them to the `AppModule` declarations solves this and the StackBlitz works as expected:

```ts
  declarations: [
    AppComponent,
    TopBarComponent,
    ProductListComponent,
    ProductAlertsComponent,
    ProductDetailsComponent,
    CartComponent,
    ShippingComponent,
  ],
```

I wonder if the error you were seeing was just a transitive issue with the StackBlitz environment when you were working on it?

Closing as this is working as expected.
