### ISSUE TITLE
Angular's EventEmitter is somehow messing with mixins

### ISSUE THREAD

**Issue by angelaki** [angular/angular#43524]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When using a mixin of a generic type this type somehow gets _lost_ for the EventEmitter, while the type is stillt known for a custom generic object. Here is an easy, minimal reproduction:

```
import { EventEmitter } from "@angular/core";

declare type Constructor<T> = new (...args: any[]) => T;

class MyObject {
    prop: string;
}

class MyGenericObject<T>{
    obj: T;
}

class MyGeneric<T> {
    field: T;
    fieldChange: EventEmitter<T>;
    generic: MyGenericObject<T>;
}

class MyComp extends MyGeneric<MyObject>{
    test() {
        this.field.prop = 'X';
        this.fieldChange.subscribe(v => {
            v.prop = 'XY';
        });
    }
}

function mixinUnknown<T extends Constructor<MyGeneric<unknown>>>(Base: T) {
    abstract class MixinUnknown extends Base {
        anything() { }
    };

    return MixinUnknown;
}

function mixinAnything<T extends Constructor<MyGeneric<any>>>(Base: T) {
    abstract class MixinAnything extends Base {
        anything() { }
    };

    return MixinAnything;
}

//Everything is OK here, except "field" is of type any
class MyCompMixed extends mixinAnything(MyGeneric)<MyObject> {
    test() {
        this.field.prop = 'X';
        this.fieldChange.subscribe(v => {
            //error TS2339: Property 'prop' does not exist on type 'unknown'
            v.prop = 'XY';
        });
    }
}

//Everything is OK here, except "fieldChange" is of type "EventEmitter<unknown> & EventEmitter<MyObject>"
class MyCompMixed2 extends mixinUnknown(MyGeneric)<MyObject> {
    test() {
        this.field.prop = 'X';
        this.generic.obj.prop = 'X';
        this.fieldChange.subscribe(v => {
            //error TS2339: Property 'prop' does not exist on type 'unknown'
            v.prop = 'XY';
        });
    }
}
```

For some reasons I have the correct type on the `field` and the `generic` property, but the type information is lost (or more an "and" of both) for the EventEmitter.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-fuirpc

### Please provide the exception or error you saw

```true
error TS2339: Property 'prop' does not exist on type 'unknown'
```

### Please provide the environment you discovered this bug in

```true
Angular 12.1.0
```

**Comment by angelaki** [comment]
@JoostK sorry, you're absolutely right! Didn't get this. But if you already checked: do you maybe have a solution for my problem, even it is not EventEmitter related?

**Comment by JoostK** [comment]
I'm sorry, I do not.

**Comment by angelaki** [comment]
Too bad! Thank you anyway ... This issue is really driving me nuts ...

**Comment by gkalpak** [comment]
I am not exactly sure what you want to use this for, @angelaki, but would something like that work for you:

```ts
function mixin<T>(Base: Constructor<MyGeneric<T>>) {
    abstract class Mixin extends Base {
        something() {}
    }
    return Mixin;
}

class Foo extends extends mixin<MyObject>(MyGeneric) {
  // ...
}
```

**Comment by angelaki** [comment]
Thank you for your advice! But that's just a pretty simplified example - my mixin needs to be used with any kinds of business objects.
