### ISSUE TITLE
Angular should not subscribe to an event unless user subscribes to it

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#4352]
Currently, Angular will subscribe to every event published by a component, whether or not the use site declared a subscriptions via `(event)` binding. This prevents components from tracking subscriptions (e.g. to allocate resources on demand rather than eagerly).

**Comment by vsavkin** [comment]
This should be done during compilation. Reassigning to @tbosch.

**Comment by tbosch** [comment]
This will be fixed in #6270

**Comment by tbosch** [comment]
This done now.
