### ISSUE TITLE
Angular language prefix

### ISSUE THREAD

**Issue by ShintaroNippon** [angular/angular#43531]
HI, Im trying to implement :language prefix on url.
I have a dropdown with multi language and I want to change url prefix
as language selected.

Can you help ?
I'm using angular 8 -
"@angular/router": "^8.2.14",
"@ngx-translate/core": "^11.0.0",
"@ngx-translate/http-loader": "^4.0.0",

thanks in advance

**Comment by petebacondarwin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).
