### ISSUE TITLE
@angular-devkit/build-angular package link points to 404

### ISSUE THREAD

**Issue by dario-piotrowicz** [angular/angular#43542]
### Description

The link in the section [Configuring Builder targets](https://angular.io/guide/workspace-config#default-architect-builders-and-targets) of the Angular workspace configuration page
redirects to :
https://github.com/angular/angular-cli/blob/master/packages/angular/cli/lib/config/schema.json
which results in a 404 github page

I think (not 100% sure) that the url should be:
https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/builders.json

![Screenshot at 2021-09-22 22-43-48](https://user-images.githubusercontent.com/61631103/134426588-c3065a72-dcb5-4201-a900-4f7e5304dcd6.png)

**Comment by alan-agius4** [comment]
I think the best action here would be to add a link to each builder schema, the main reason for this is that there is no similar schema as https://github.com/angular/angular-cli/blob/master/packages/angular/cli/lib/config/schema.json

Example:
app-shell: https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/builders/app-shell/schema.json
browser: https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/builders/browser/schema.json
....

Also, in version 13 we should remove tslint from the list.
