### ISSUE TITLE
Throw error when using unsupported CSS selector for Directives/Components

### ISSUE THREAD

**Issue by martinmcwhorter** [angular/angular#43548]
### Which @angular/* package(s) are relevant/releated to the feature request?

compiler, core

### Description

Currently if a component or directive uses an unsupported CSS combinator selector, such as `selector: 'parent child'`, the component or directive is applied to every `child` element.  

### Proposed solution

At compile time do a best-effort validation of component/directive selectors and fail builds if the selector is not supported. 

```
@Component({
  selector: 'parent child'
})
```
```
Error: Combinator selectors are not supported for Angular components or directives. 
```
If this is a change that would likely be accepted, I can create a Pull Request. 

### Alternatives considered

An alternative and/or parallel validation would be to add this as a linting rule to the Angular-Eslint project.

**Comment by JoostK** [comment]
There is already an issue for this here: #6600. A PR is welcome but since it would be a breaking change it can only be accepted in a major, and just to set expectations we're likely too late to make the v13 cut.
