### ISSUE TITLE
upgrade systemjs builder 

### ISSUE THREAD

**Issue by rkirov** [angular/angular#4354]
The repo is using system.js `0.18`, but still on systemjs-builder `0.10` (roughly corresponding to system 0.16). There has been a number of breaking changes in the way path configuration works, so this is not be trivial - https://github.com/systemjs/builder.

// cc @IgorMinar @pkozlowski-opensource

**Comment by pkozlowski-opensource** [comment]
Right, I was raising it already in https://github.com/angular/angular/issues/3562 (going to close it as a duplicate of this one, as it is more specific - we've updated the loader already).

And yes, there are some breaking changes - I gave it a go at one point in the past but couldn't figure out things quickly (<1h).

**Comment by mhevery** [comment]
Dup of #3562

**Comment by pkozlowski-opensource** [comment]
@mhevery re-opening since #3562 was closed as a dup of this one :-)

**Comment by naomiblack** [comment]
@robwormald can you have a look and see if this can be resolved today/tomorrow -- it is blocking for other tasks. Otherwise, push to alpha-40 and complete by EOW?

**Comment by robwormald** [comment]
Yep, will let you know within the hour

**Comment by robwormald** [comment]
@naomiblack should be good for today

**Comment by robwormald** [comment]
@naomiblack actually, no, let's bump this to alpha-40. it has some implications for how files are loaded so want to discuss with @pkozlowski-opensource

**Comment by pkozlowski-opensource** [comment]
@robwormald what are the implications? Let's kick off the discussion on it in the packaging channel

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
