### ISSUE TITLE
Packages from same (lib) repo looks different installed

### ISSUE THREAD

**Issue by andreaslarssen** [angular/angular#43540]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I've build several libs in a repo that I've got. When I just build a new one, pushed it to npm and installed it in another project, for some reason it seems to be installed differently than the others?

This is how two of the packages looks in the repo where they're build. The top one (let's call it A) works just fine when installing the published npm package. The bottom one (let's call it B) does not.

![lib](https://user-images.githubusercontent.com/3169836/134407952-d522f60e-a6b2-4369-93f8-e1708746a25f.png)

This is how they look when installing them in an Angular project running Angular 10:

![inst](https://user-images.githubusercontent.com/3169836/134407960-b14236b9-0918-4217-962f-e384d65c4325.png)

Obviously, package A is somehow installed (?) differently than package B. They're both packaged, published and installed the same way, with the same version of the lib and the same config.

### Please provide the environment you discovered this bug in

```true
LIB PROJECT:

Angular CLI: 8.2.2
Node: 12.18.4
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.802.2
@angular-devkit/build-angular      0.802.2
@angular-devkit/build-ng-packagr   0.802.2
@angular-devkit/build-optimizer    0.802.2
@angular-devkit/build-webpack      0.802.2
@angular-devkit/core               8.2.2
@angular-devkit/schematics         8.2.2
@angular/cli                       8.2.2
@ngtools/webpack                   8.2.2
@schematics/angular                8.2.2
@schematics/update                 0.802.2
ng-packagr                         5.7.1
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.38.0

----------------------------

APP PROJECT:

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cli                      10.0.8
@angular/http                     7.2.16
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.5.5
typescript                        3.9.9
webpack                           4.43.0
```

**Comment by petebacondarwin** [comment]
The differences you are seeing is the result of our "ngcc" tool, which processes and modifies Angular libraries compiled for ViewEngine so that they can be used by Ivy. This is triggered by the Angular CLI when it first builds a project with such packages. Note that Ivy is enabled by default from 9.0.0 onwards. 

To confuse you a bit more, as of v13.0.0 all libraries are built in a mode called "ivy partial", which will look slightly different again; but the good news is that these do not need to be processed by ngcc and so will not appear mutated in your node_modules directory.

Closing as this is expected behaviour.

**Comment by andreaslarssen** [comment]
@petebacondarwin What I don't understand is that all the packages are installed the same way, in the same Angular project running version 10. It's just one package that fails.

Also:
 When you say "This is triggered by the Angular CLI when it first builds a project with such packages.", do you mean that you actually have to run ng build on the target project after installing a package? According to this article: https://blog.ninja-squad.com/2021/01/27/angular-linker/ running npm install, followed by ng serve should run the ngcc compiling.

**Comment by petebacondarwin** [comment]
`ng serve` does build the project, which also triggers ngcc.

Can you explain, by the way, what you mean by the package failing?

**Comment by andreaslarssen** [comment]
@petebacondarwin For the time being, I can't reproduce the error I got the first time I installed the package. But from memory it said that it seemed like the package wasn't built correctly, and a link to the definition of the Angular package format, as far as I can remember.

The thing is, after installing the package, I can't import the Module in my project. It's exported from the public-api.ts file. When "forcing" an import (my IDE says it can't find the package), and runing ng serve, the app says `Cannot find module '@namespace/package' or its corresponding type declarations`.

Running ng serve / npm start does nothing to that one package. I got four packages installed that I've built in the same library repo, with the same command and same config (as far as I can tell. I've been over it char by char over 20 times). 

I suppose ngcc should compile all packages? Could there be anything in the way I build the package, install the package, config the package or naming or anything at all that somehow makes ngcc not compile that particular package?

**Comment by andreaslarssen** [comment]
@petebacondarwin Seems like this covers the bug I'm experiencing: https://github.com/angular/angular/issues/40357

**Comment by petebacondarwin** [comment]
That bug was resolved in 11.1.0 onwards, so I recommend upgrading to a newer version.

**Comment by andreaslarssen** [comment]
@petebacondarwin Thanks. 

So for a lib built w/ ViewEngine installed on an Angular 9 - pre-11.1.0 project, how can you make it compile correctly? Explicitly install an ngcc version?

**Comment by petebacondarwin** [comment]
I'm afraid that you cannot mix and match versions of ngcc with the rest of the framework. You will need to update your project to v11.1 or later.

**Comment by andreaslarssen** [comment]
@petebacondarwin Ok, so just to be clear. That means that noone running Angular 9 - pre-11.1.0 project can use those libs, and there's no way to fix it?

**Comment by petebacondarwin** [comment]
Honestly I am not sure that the problem you described in this issue is the same as that in the linked issue.
But if it is then, yes the application would need to update to the version that contains the fix.

**Comment by andreaslarssen** [comment]
@petebacondarwin Yeah, I haven't verified it yet. Good to know what could be the case anyway. Thanks for your help.
