### ISSUE TITLE
Angular 8 router - language prefix

### ISSUE THREAD

**Issue by ShintaroNippon** [angular/angular#43551]
I have a route like ":language/activities", I can get the language param, but I have also a dropdown with multi-language.

How can I change the URL prefix when changing the dropdown.

And not using language in routerlink

`[routerLink]="['/'+lang+'/activities']" [queryParams]="{ activityId: activity.id }"
`
Anyone can help?

Thanks in advance

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
