### ISSUE TITLE
Better syntax for multi-element structural directives

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#4355]
Currently I can do this:

```
<ul>
  <li *ng-for="#item of items">...</li>
</ul>
```

but there are many use-cases when ng-for, ng-if, or other structural directive should be applied to multiple elements. it's possible to do it today using `<template>` element, but the syntax is ugly and unnatural because I'm forced to manually desugar the data-binding:

```
<ul>
  <template ng-for var-item [ng-for-of]="items">
    <li>...</li>
    <li>...</li>
  </template>
</ul>
```

What I'd like is:

```
<ul>
  <template ng-for="#item of items">
    <li>...</li>
    <li>...</li>
  </template>
</ul>
```

I'm intentionally avoiding `*` in front of ng-for because, conceptually `*` means "template", but we are already on the template element.

The problem with this is that without the `*` marker we don't know how to desugar the micro-syntax, but that can be solved by imposing a limitation that a `<template>` element can only have a single attribute directive placed on it. any other data/event binding or multiple directives should throw an error (it really doesn't make sense to use these with the `<template>` element).

Other proposals are welcome as long as the resulting syntax is natural.

**Comment by pkozlowski-opensource** [comment]
Ha! This is _exactly_ what I was discussing with some folks yesterday when introducing them to ng2 :-)

**Comment by wardbell** [comment]
Love the direction.

What other attribute could there be than `ng-for`?  It the answer is "none", then we may be able to come up with an obvious approach that does not need a micro syntax.  I'm thinking about that approach so that we don't have to come up with extra rules for `template`

**Comment by PascalPrecht** [comment]
I think that users are going to have a hard time grasping that they won't need the `*`, after they learned why they normally have to. Not sure, but maybe it's worth considering keeping the `*` here too?

**Comment by wardbell** [comment]
My thought was to treat the template as a component with properties such as `list`

You might end up with
```
<template #hero [list]="heroes">...<template>
```
Not sure how to handle the `index`

**Comment by mhevery** [comment]
Will not implement.
