### ISSUE TITLE
Linux CentOS - ERROR in src/app/app.module.ts:18:42 - error TS2307: Cannot find module '@app/modules/

### ISSUE THREAD

**Issue by olemalik** [angular/angular#43567]
Hi!
I am getting the following error when I am running the build command in CesntOS, but same command works for Windows Server 
![image](https://user-images.githubusercontent.com/24887117/134673416-8d7a278e-c52a-40ae-95d2-63c78c9ca840.png)

this is my angular version 
![image](https://user-images.githubusercontent.com/24887117/134673694-c0f98e17-3280-44bf-a10f-0de0f9d9c769.png)

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

You may want to check the capitalization of the files, as some filesystems are case-sensitive.
