### ISSUE TITLE
Size regression in `cli-hello-world-ivy-minimal` integration test

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#43568]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

The `cli-hello-world-ivy-minimal` payload size limit has been increased from `17597` to `20064` in https://github.com/angular/angular/pull/43417/files. This has been done as a workaround to bump the Angular tooling packages to version 13.

The regression appears to have been introduced in Angular CLI 12.1.x, when the CLI migrated to use the new Babel based build-optimizer. 

Likely we missed some PURE annotations in https://github.com/angular/angular/pull/43344

This is also a side-effect that the framework is using https://github.com/filipesilva/check-side-effects to check for side effects which uses the deprecated `@angular-devkit/build-optimizer`

**Comment by devversion** [comment]
@alan-agius4 Just wanted to check on this. Have you looked into this?

**Comment by alan-agius4** [comment]
@devversion, not yet.

**Comment by alan-agius4** [comment]
Closing as this test no longer exists.
