### ISSUE TITLE
Feature request: Ability to manually clear or initialize Router url

### ISSUE THREAD

**Issue by sri1980** [angular/angular#43561]
### Description

Router url is getting persisted and couldn't find any way to reset or initialize the url. This is causing issues when we switch angular apps backend forth in a browser window.

1. Load app1
2. Navigate to route1
3. Navigate to route2
4. Load app2
5. Navigate to route1
6. Navigate to route2
7. Load app1 - notice that automatically route2 will be displayed automatically

### Proposed solution

* Implement option to clear or initialize the router url.

### Alternatives considered

none

**Comment by atscott** [comment]
Could you provide a reproduction?
