### ISSUE TITLE
BrowserPlatformLocation cannot handle credentials in the URL in Firefox

### ISSUE THREAD

**Issue by julmot** [angular/angular#43573]
### Which @angular/* package(s) are the source of the bug?

router, Don't known / other

### Is this a regression?

No

### Description

Supposed you have a working Angular app with working routing (a component is generated after `<router-outlet>`). When opening the same working application with credentials embedded into the URL (basic auth), Angular's router stops working. No component is generated after `<router-outlet>`. When removing those embedded credentials from the URL, the applications works again.

You can reproduce this by using an example Angular application like this:
https://github.com/gothinkster/angular-realworld-example-app

The example URL would be:

https://test:test@angular.realworld.io/ => Renders an empty app body

![with-credentials](https://user-images.githubusercontent.com/8310677/134725548-aefe614d-fb5c-4fd0-8fcd-6a2f4fa5e140.png)

https://angular.realworld.io/ => Renders successfully

![without-credentials](https://user-images.githubusercontent.com/8310677/134725538-573aaa21-5886-4006-b2b7-793c348a2c3d.png)

### Please provide a link to a minimal reproduction of the bug

https://test:test@angular.realworld.io/

### Please provide the exception or error you saw

```true
No exception itself - only an empty app body respectively nothing generated after `<router-outlet>`.
```

### Please provide the environment you discovered this bug in

```true
The example application (https://github.com/gothinkster/angular-realworld-example-app) seems to be using Angular v11.2.8. However, I can reproduce this in my own application too which is running on the latest version: v12.2.6.
I'm on Windows 10 with Firefox v92.
```

**Comment by julmot** [comment]
@atscott Thanks for your reply! We want to release our Angular application soon for a selection of customers before releasing it to all customers. Thus, we'd like to have basic auth credentials in the URL since their system embeds our application in an iframe.

Therefore, is there any chance to tell me when this is going to be fixed? Debugging this myself will take a significant amount of time to get the stack up and running and find the corresponding code that needs to be fixed.

**Comment by atscott** [comment]
@julmot There is no timeline for a fix for this. I mentioned in the previous comment exactly what you can do to make it work in your application. It should not take long to create a fix for your use-case.

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
