### ISSUE TITLE
Upgrading to Angular 12 Causes Application Not To Start

### ISSUE THREAD

**Issue by vwang4536** [angular/angular#43584]
Hi,
   I just upgraded my Angular application to Angular 12 from Angular 11 and now the application does not seem to be able to run past the compile when I run yarn start. It exits out with an error code 1 without a specific error to depict what the issue is. The yarn error log as well as angular error log also are not generated when this error occurs. I have attached a screenshot to the issue along with the dependencies that are used with this message. It seems to occur only on Windows and not Mac.  Please help. pls
[yarn start output.txt](https://github.com/angular/angular/files/7228743/yarn.start.output.txt)

![yarn start output 2](https://user-images.githubusercontent.com/44247404/134748486-aedfb1fc-ddc2-4415-ae93-733b72f318d3.png)

![dependencies](https://user-images.githubusercontent.com/44247404/134748363-bc6afb6a-68b9-4876-a485-8a5256229540.png)
![devDependencies](https://user-images.githubusercontent.com/44247404/134748366-3de19155-1c73-4e94-b72a-38877ee71164.png)

**Comment by JoostK** [comment]
Hi there, what's the output of `ng version`? I don't expect that it will provide sufficient insight into why you're having problems on Windows but it may reveal some more info of your environment.

**Comment by vwang4536** [comment]
Hi guys, thanks for responding. Here is the output for ng version

```
Angular CLI: 12.2.7
Node: 14.17.1
Package Manager: yarn 1.22.5
OS: win32 x64

Angular: 12.2.7
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.7
@angular-devkit/build-angular   12.2.7
@angular-devkit/core            12.2.7
@angular-devkit/schematics      12.2.7
@angular/flex-layout            11.0.0-beta.33
@schematics/angular             12.2.7
rxjs                            6.3.3
typescript                      4.2.3

```

> Hi there, what's the output of `ng version`? I don't expect that it will provide sufficient insight into why you're having problems on Windows but it may reveal some more info of your environment.

**Comment by JoostK** [comment]
That looks all as expected, so all is fine there. Unfortunately that does leave us in the dark as to what might be going on; we'd need to be able to reproduce this to get to the bottom of it.

**Comment by vwang4536** [comment]
> That looks all as expected, so all is fine there. Unfortunately that does leave us in the dark as to what might be going on; we'd need to be able to reproduce this to get to the bottom of it.

I tried to create a reproduction environment including the above dependencies and it looks like the application was able to start up fine so it seems that there is an issue on my end regarding the application's environment configurations. I will go through the configurations and see what is causing the problem. Thank you for the assistance!

**Comment by AndrewKushnir** [comment]
Closing this ticket based on https://github.com/angular/angular/issues/43584#issuecomment-929603380. Please reopen if the issue still exists and there is a repro available.
