### ISSUE TITLE
Support OnChanges and OnInit hooks in service

### ISSUE THREAD

**Issue by vthinkxie** [angular/angular#43598]
### Which @angular/* package(s) are relevant/releated to the feature request?

core

### Description

The OnDestory hook is supported in service, but the OnChanges and OnInit hooks are not supported in service yet, it is hard to reuse the OnInit and OnChanges logic across multiple components

### Proposed solution

support OnChanges and OnInit hooks in service, after that, we can abstract the generic logic of multiple component OnChanges and OnInit into the service components

### Alternatives considered

Here is the demo: https://stackblitz.com/edit/angular-ivy-ihhxy9?file=src%2Fapp%2Fhello.component.ts

**Comment by JoostK** [comment]
The request for `OnInit` is tracked in #23235.

As for `OnChanges`, I don't quite understand what you're asking for. The concept of _changes_ is directly associated with input bindings and services do not have inputs, so the changes concept does not apply for services. I can see how you might "share" the lifecycle hooks of a component with its providers, but there's several gotchas there:

- `ngOnChanges` would receive the changed inputs from a completely different (and unrelated) type, resulting in type-safety concerns (especially if the service is provided by multiple, different components). I realize that `ngOnChanges` is not type-safe today but the current design at least allows it to be.
- Services are lazy by default, which means that they won't automatically take part in the lifecycle hooks at all. The lazy nature also means that the time of instantiation of a service may differ from the component, which introduces tricky situations for things like `SimpleChange.isFirstChange`.

Taking this into consideration I would not be in favor of "lifecycle hook delegation" to services.

**Comment by vthinkxie** [comment]
Hi @JoostK 

Thanks for your reply, I want make the lifehook of angular reactive in programing, with the onDestroy hook, we can abstract the destroy logic, and get destroy$ without declaration new Subject.

If angular support onChanges hook in service, we can get change$ Observable without new Subject too, with change$ we can make all logic reactive without a hack.

here is the demo:

https://stackblitz.com/edit/angular-ivy-ihhxy9?file=src%2Fapp%2Fhello.component.ts

**Comment by petebacondarwin** [comment]
So what you are saying, @vthinkxie, is that if a service is actually provided in a component, then there should be some way to hook into the component's ngOnChanges hook.

It kind of works with ngOnDestroy, because when you destroy a component, any services that are provided directly on that component are also destroyed.

**Comment by petebacondarwin** [comment]
I think this would add too much churn to the way components are defined. Currently no change detection life-cycle hooks are implemented for a component if it does not have an `ngOnChanges()` method defined at the point it is compiled. To do what you want would mean the compiler would need to look at all the providers, but the actual value of the provider is only known at runtime - imagine that the provide has a `useFactory` clause.

**Comment by petebacondarwin** [comment]
Perhaps we could add an event emitter to the `ChangeDetectorRef` object that is available to components:

```
@Component(...)
class My Component {
  constructor(cd: ChangeDetectorRef) {
    cd.onChanges(this).subscribe(...);
  }
}
```
