### ISSUE TITLE
Memory leak when creating/destroying Web Components exported with @angular/elements

### ISSUE THREAD

**Issue by aetzlecx** [angular/angular#43606]
### Which @angular/* package(s) are the source of the bug?

elements

### Is this a regression?

No

### Description

While experimenting to get the hang behind https://github.com/angular/angular/issues/38778 I discovered that the heap memory increases over the time when web-components are created and destroyed (removed from the DOM).

Within this simple GH project it can be reproduced: https://github.com/aetzlecx/ng-elements-memory-leak

After a couple of thousand creations/destroys it can be seen that the heap increases:

![gh_bug_heap_detailed2](https://user-images.githubusercontent.com/90193552/134869601-bc10db82-d14a-461a-8fb6-e9a577c88949.png)

### Please provide a link to a minimal reproduction of the bug

https://github.com/aetzlecx/ng-elements-memory-leak

### Please provide the exception or error you saw

```true
there are no exceptions/errors, just an increasing heap
```

**Comment by aetzlecx** [comment]
Could it be that this issue is related to https://github.com/angular/angular/issues/41047?

**Comment by gkalpak** [comment]
Thx for reporting this, @aetzlecx :+1:
Yes, #41047 could be related. Can you please check whether this also happens when using AOT and also if it happens in production mode (or only in dev mode)?

**Comment by JeanMeche** [comment]
I did some tests on the provided repo (v11, which does not include the fix for #41001 ). There is indeed a high memory usage but its cleared by the garbage collector. 

![Screenshot 2023-07-05 at 01 08 48](https://github.com/angular/angular/assets/1300985/9fd6d956-f56e-4b35-816b-b3797e1be68a)

So no issue !

**Comment by aetzlecx** [comment]
> I did some tests on the provided repo (v11, which does not include the fix for #41001 ). There is indeed a high memory usage but it's cleared by the garbage collector.
> 
> ![Screenshot 2023-07-05 at 01 08 48](https://user-images.githubusercontent.com/1300985/251002194-9fd6d956-f56e-4b35-816b-b3797e1be68a.png)
> 
> So no issue !

Thanks for cross checking. Can I ask how you tested this? Did you use my original code or something else?

**Comment by JeanMeche** [comment]
Yes, I did use the repo you provided !
