### ISSUE TITLE
No hint for the next section at the end of the each section

### ISSUE THREAD

**Issue by ajsaraujo** [angular/angular#43612]
### Description

It would be nice if we had a hint for the next section at the end of each topic. Currently, the reader has to click the :hamburger:  button at the top-left and select the next section himself.

For example, say one wants to learn about component testing. He clicks on "Developer Guides > Testing > Basics of Testing Components". 

![image](https://user-images.githubusercontent.com/34658414/134946813-620e8f07-7701-4504-9a12-81e9ee89b0d7.png)

He reads the article through the end... and sees something like this:

![image](https://user-images.githubusercontent.com/34658414/134947262-0bd6b30e-da2f-48dd-b07b-4831a2bb34dd.png)

The "next section" can be found at the sidebar, but it doesn't draw much attention to the eye. Especially considering that some users prefer to keep the sidebar closed. In my case, by the end of the tutorial I was wondering "Is that it...?". I completely forgot there was another section on component testing (which would be the next one, "Component Testing Scenarios").

Hence, my suggestion is to include a more visual hint by the end of each section, taking the user to the next one. I'd add it both to the end of the content and to the bar at the right. Something like this:

![image](https://user-images.githubusercontent.com/34658414/134948092-77e1bdba-0654-43aa-bc1c-d195ba203ccc.png)

**Comment by bob-watson** [comment]
Lowered priority to P3 and docs-infra.
This is definitely a worthwhile idea, but it would be better implemented in the tooling than to manually add and maintain these links in each topic.

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
