### ISSUE TITLE
Allow host components to register `data` attributes

### ISSUE THREAD

**Issue by matsko** [angular/angular#4362]
If I try something like this then Angular gets angry:

```ts
@Component({
  selector: 'notification-panel',
  host: {
    '[data-state]': 'state'
  }
})
class {
   state = "on";
}
```

What's the plan for supporting this?

**Comment by pkozlowski-opensource** [comment]
You can do `[attr.data-state]: state` since you want to set an attribute. There is no `data-state` property, right?

**Comment by matsko** [comment]
Ah yes that's correct. I wasn't aware that the host values are properties and not attributes. Thank you Pawel for clearing this up.
