### ISSUE TITLE
[Docs] Tutorial review

### ISSUE THREAD

**Issue by geromegrignon** [angular/angular#43634]
# Description

This issue is about a [tutorial](https://angular.io/start) review requested from @aikidave on the Angular Discord server.

# List of issues

> Each issue title is created as a task list so you can create a dedicated issue out of it with [GitHub](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists#about-issue-task-lists)

- [ ] **Core Documentation tied to Tour of Heroes**

All links from the Tutorial lead to the core documentation. This documentation is tied with Tour of Heroes. It might be misleading when you discover Angular through the non-TOH tutorial.

- [ ] **[Docs][Tutorial] Typo on 'description'**

section: https://angular.io/start#create-the-product-list

Change from `Add the product descriptions.` to `Add the product description.`

- [ ] **[Docs][Tutorial] Product import not explained**

section: https://angular.io/start#pass-data-to-a-child-component

The Product import is included in the snippet but the related task only refers to the Input.

```typescript
import { Component, OnInit } from '@angular/core';
import { Input } from '@angular/core';
import { Product } from '../products';
```

- [ ] **[Docs][Tutorial] typing consistency**

section: https://angular.io/start#pass-data-to-a-parent-component

The product `@Input` was previously defined using the non-null assertion operator:  `@Input` product!: Product;. The tutorial should be consistent about its usage.
```typescript
export class ProductAlertsComponent {
  @Input() product: Product | undefined;
  @Output() notify = new EventEmitter();
}
```

- [ ] **[Docs][Tutorial] Pass data to a parent component title misleading**

section: https://angular.io/start#pass-data-to-a-parent-component

As no data is passed with the example with the event, i would expect a title more close to the one used in the documentation core: Parent listens for child event (https://angular.io/guide/component-interaction#parent-listens-for-child-event)

- [ ] **[Docs][Tutorial] ProductDetailsComponent declaration missing in AppModule**

section: https://angular.io/start/start-routing#associate-a-url-path-with-a-component

- [ ] **[Docs][Tutorial] CartService not provided**

section:  https://angular.io/start/start-data#use-the-cart-service

Unlike Angular CLI, the generation of a Service with Stackblitz doesn't provide it by default with providedIn: 'root'.
So by clicking on an item, the product-details page doesn't load as expected as the service isn't provided.
There are 2 solutions :
- to update the `@Injectable` decorator metadatas
- to provide the Service in the providers array of AppModule

I would consider using the first solution for the sake of further usage of the framework: we more likely have to use providedIn: 'root' with Services rather than providing them 'manually' in Modules (which might lead to different behavior depending on the Module).

- [ ] **[Docs][Tutorial] CartComponent  declaration missing in AppModule**

section: https://angular.io/start/start-data#set-up-the-cart-component

- [ ] **[Docs][Tutorial] reduce min-width of items for Stackblitz**

Change min-width of the cart-item to 300px as the stackblitz iframe is too small by default to match the 450px min-width:
```css
.cart-item, .shipping-item {
  min-width: 300px;
}
```

- [ ] **[Docs][Tutorial] ShippingComponent declaration missing in AppModule**

section: https://angular.io/start/start-data#create-a-shipping-component

On creation, there is a snippet with both route and component added to AppModule but the related description only refers to the route (and not the declaration)

- [ ] **[Docs][Tutorial] wording changes on CartService**

section: https://angular.io/start/start-data#configuring-the-shippingcomponent-to-use-cartservice

I would change 
```
Define a shippingCosts property that sets the shippingCosts property using the getShippingPrices() method from the CartService.
```
to
```
Define a shippingCosts property and initialize it using the getShippingPrices() method from the CartService.
```

- [ ] **[Docs][Tutorial] Usage of $ for observable property naming**

section: https://angular.io/start/start-data#configuring-the-shippingcomponent-to-use-cartservice

We create an observable property into a component: I would challenge the usage of the good practice of suffixing the property name with $.

- [ ] **[Docs][Tutorial] Change console.warn to window.alert**

section: https://angular.io/start/start-forms#define-the-checkout-form-model

I would consider moving from **console.warn** to **window.alert** as it's been the preferred solution to provide feedback in this tutorial so far.
```typescript
onSubmit(): void {
    // Process checkout data here
    this.items = this.cartService.clearCart();
    console.warn('Your order has been submitted', this.checkoutForm.value);
    this.checkoutForm.reset();
  }
```

- [ ] **[Docs][Tutorial] Promote Firebase to host the tutorial**

section: https://angular.io/start/start-deployment

As Stackblitz provides an easy way to deploy to Firebase, I would consider adding a dedicated section as it would both:
- provide an easy solution for new devs who might struggle to find/use hosting solutions
- promote a Google solution

**Comment by helloankit** [comment]
Thanks @geromegrignon for the wonderful issue description.
@aikidave  Are you working on the fix? If not, I would be glad to raise the PR for these fixes!

**Comment by aikidave** [comment]
@helloankit I am not working on a fix yet! If you'd like to take this one, please do! Let me know how I can help!

**Comment by helloankit** [comment]
I have raised a PR (#43692) for a set of issues described in this Issue Document and will raise another PR to address the remaining ones.
@geromegrignon  Need Help from you regarding the following Issues -
1. Core Documentation tied to Tour of Heroes - I didn't get that completely. What can be the possible solution that you can think of for resolving this issue?

2. Promote Firebase to host the tutorial - We already have a section for deployment on firebase at https://angular.io/guide/deployment. Do you feel the need for another section?

**Comment by bob-watson** [comment]
Changed to `P3` for review/inclusion with other ToH tutorial updates.

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
