### ISSUE TITLE
"New Issue" wizard confused

### ISSUE THREAD

**Issue by Chealer** [angular/angular#43638]
When reporting a new issue, a wizard starts by asking to choose the type of issue reported, as can be seen in the following screenshot:
![image](https://user-images.githubusercontent.com/486141/135349834-496e9c69-fe90-498a-93a0-586d6949401e.png)

As this doesn't cover all issues, there is an alternative link at the bottom:

> Don’t see your issue here? Open a blank issue. 

There are 2 problems with that.

The first is merely terminological. Obviously, no one will see their issue, as the list only lists issue types, not specific issues.

The second comes from the "Open a blank issue." link. Clicking it brings to a form which contains the following:

> Please help us process issues more efficiently by filing an
> issue using one of the following templates:
> 
> https://github.com/angular/angular/issues/new/choose
> 
> Thank you!

The problem is that the URL is that of the first step, from which the contributor just came. In other words, someone careless would just keep looping from the first to the second step infinitely.

**Comment by gkalpak** [comment]
Thx for reporting this, @Chealer!

AFAICT, that message at the bottom is displayed by GitHub and we have no way of customizing it. We would really, really want people to use one of the templates (thus the fallback template points people back to `issues/new/choose`).

I am not too worried about the human infinite loop (as I don't expect it to be an issue in practice). But if you concerned, feel free to send a pull request to update the [fallback template][1] to make sure we break out of the loop :wink:

[1]: https://github.com/angular/angular/blob/a07cb097e9124738880f7978658a2972d25b892e/.github/ISSUE_TEMPLATE.md

**Comment by Chealer** [comment]
> Thx for reporting this, @Chealer!

My "pleasure" (I guess :-D ) @gkalpak 


> That message at the bottom is indeed a little confusing. Unfortunately, afaict that message is displayed by GitHub and we have no way of customizing it.

Ah, wow. Sorry to learn that, but thanks

 
> Regarding redirecting people back to `issues/new/choose` from the fallback template: We really, really want people to use one of the templates 😃 

Hehe, that is probably a good thing indeed, but we need to stay realistic until the (featured) templates cover all situations.


> I am not too worried about the human infinite loop (as I don't expect it to be an issue in practice). But if you are concerned, feel free to send a pull request to update the [fallback template](https://github.com/angular/angular/blob/a07cb097e9124738880f7978658a2972d25b892e/.github/ISSUE_TEMPLATE.md) to make sure we break out of the loop 😉

Hehe, the report might seem exaggerated, but the current situation is certainly confusing / sub-optimal. If you are referring to a "merge request", I have not changed anything, but it seems trivial.
Is there a reason why this ticket is closed?

**Comment by gkalpak** [comment]
> Hehe, that is probably a good thing indeed, but we need to stay realistic until the (featured) templates cover all situations.

If you have a specific suggestion on what situation is not covered or a new template we should add, we would gladly consider it. Please open a new issue (or even a pull request :wink:).

> Hehe, the report might seem exaggerated, but the current situation is certainly confusing / sub-optimal.

Again, we are open to specific suggestions.
(FWIW, I don't find the current situation confusing, but I am sure that is related to me being too familiar with the repo and our processes. So, any concrete feedback on how we could make the process more clear/easy to follow from someone outside the team is very welcome.)

> If you are referring to a "merge request", I have not changed anything, but it seems trivial.

Sorry, I am not following 😅 I am referring to a [pull request][1].
In case it is not clear, GitHub issue templates are kept in the [.github/][2] and [.github/ISSUE_TEMPLATE/][3] directories of the repo, so they can be updated with regular pull requests. You can read more about GitHub issue templates in [their docs][4].

> Is there a reason why this ticket is closed?

It is not actionable for us in its current form.

[1]: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests
[2]: https://github.com/angular/angular/tree/c721135e370b34c840756bcfb22c8119b4c8c452/.github
[3]: https://github.com/angular/angular/tree/c721135e370b34c840756bcfb22c8119b4c8c452/.github/ISSUE_TEMPLATE
[4]: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates
