### ISSUE TITLE
HostListener stopping working randomly

### ISSUE THREAD

**Issue by ryanmattos** [angular/angular#43636]
Hey, i'm using Angular ```6.0.3``` on a production project and i been facing a trouble while in homologation.

I had to build a term of use component, and had to use ```HostListener``` to know if user has scrolled the term totally. But the problem is: After development, i've noticed that, **RARELY** but not **NEVER**, the function i've used to check if the content is totally scrolled, with ```HostListener```, stop working sometimes.

After reporting this issue, i've been trying to reproduce it repeatedly to check it out and try to solve the problem, but i was unsuccessfull.

I don't know what i can do anymore, because this problem isn't either a real problem, it's just like a Russian roulette, and the error is solved by simply closing Google Chrome and opening again.

**Comment by Airblader** [comment]
Angular 6 has been out of support for quite a while now. You may want to upgrade your app to a supported version first.

**Comment by ryanmattos** [comment]
> Angular 6 has been out of support for quite a while now. You may want to upgrade your app to a supported version first.

Thanks!

**Comment by sonukapoor** [comment]
Closing this issue as Angular 6 is not supported anymore. See [here](https://angular.io/guide/releases#support-policy-and-schedule) 

> Angular versions v4, v5, v6, v7, v8, and v9 are no longer under support.
