### ISSUE TITLE
Cannot use `press` as event name

### ISSUE THREAD

**Issue by cristinecula** [angular/angular#4363]
I have a component defined like so:

```js
@Component({
  selector: 'w-keyboard',
  properties: [
    'on',
  ],
  events: [
    'press',
  ],
})
```

Here it is used in the template:

```html
<w-keyboard on="m" (press)="audio.toggleMute()"></w-keyboard>
```

An exception is thrown regarding the press event.

```
EXCEPTION: Hammer.js is not loaded, can not bind press event
angular2.sfx.dev.js:27036 STACKTRACE:
angular2.sfx.dev.js:27036 Error: Hammer.js is not loaded, can not bind press event
```

I renamed the event to `pressed` but I expected that component event definitions would take precedence over defaults.

Angular2 version alpha.35

**Comment by PascalPrecht** [comment]
@cristinecula As the error states, there's a missing Hammer.js dependency in your code. `press` event is apparently implemented in Hammer.js, however if it's not there, the event can't be used/bound by your component. Make sure to include Hammer.js as well.

**Comment by cristinecula** [comment]
@PascalPrecht Thank you for the quick response. I understand that including Hammer.js would make the exception go away, but I am not trying to use the `press` event supplied by Hammer.js. I am trying to define my own component that launches a custom event named `press` when a given key combination is pressed.

**Comment by zoechi** [comment]
I just run into this while trying to listen to the `tap` event of a Polymer element (in Dart)
