### ISSUE TITLE
ng universal

### ISSUE THREAD

**Issue by elycheikhsmail** [angular/angular#43645]
### Description

ng universal now support node(express) and .NET.
I hope ng universal support deno

### Proposed solution

I don't know how but I think it will possible because node and deno are two runtime for js and opine is express equivalent in deno

### Alternatives considered

may be build new project angular-deno for develop and build angular app usining deno instead of node

**Comment by petebacondarwin** [comment]
Please can you open this issue at https://github.com/angular/universal
