### ISSUE TITLE
The DOM by Karma rendered is not the same as the DOM by Angular rendered

### ISSUE THREAD

**Issue by leochen0818** [angular/angular#43648]
I found a problem that is the DOM by Karma rendered is not the same as the DOM by Angular rendered, and I actually submit the issue on Karma's repository. 
But they told me that I should come here to submit the question for help.

The issue's link is: [https://github.com/karma-runner/karma/issues/3700](https://github.com/karma-runner/karma/issues/3700)

And I also prepare the sample: [https://github.com/leochen0818/angular-30days-form-and-testing/blob/fcc478d2191710c9bd5374d46ceeb785e5562993/src/app/app.component.spec.ts#L304-L309](https://github.com/leochen0818/angular-30days-form-and-testing/blob/fcc478d2191710c9bd5374d46ceeb785e5562993/src/app/app.component.spec.ts#L304-L309)

**Comment by JeanMeche** [comment]
I just took a closer look to it, it is not a Karma issue. There are missing changes, that can be fixed by calling `fixture.autoDetectChanges(true);` for example.
