### ISSUE TITLE
Deprecate `bind-`, `bindon-`, `on-`, and `ref-` syntax in templates

### ISSUE THREAD

**Issue by atscott** [angular/angular#43669]
### Which @angular/* package(s) are relevant/releated to the feature request?

compiler, core

### Description

These template syntaxes are rarely used and unnecessarily expand the API surface of our template language. This issue is for tracking the deprecation of `bind-`, `bindon-`, `on-`, and `ref-`.

### Proposed solution

Deprecate `bind-`, `bindon-`, `on-`, and `ref-` in v14 and create a migration for when they are removed.

### Alternatives considered

N/A

**Comment by LayZeeDK** [comment]
This would leave only the syntactic sugar behind, right?

How about `bind-animate`?

| Syntactic sugar | HTML-like |
|---|---|
| `[property]="value"` | `bind-property="value"` |
| `[(property)]="value"` | `bindon-property="value"` |
| `(event)="eventHandler($event)"` | `on-event="eventHandler($event)"` |
| `#variable` | `ref-variable` |
| `[@trigger]="value"` | `bind-animate-trigger="value"` |

**Comment by atscott** [comment]
> This would leave only the syntactic sugar behind, right?

That's right


> How about `bind-animate`?
> 
> Syntactic sugar	HTML-like
> `[property]="value"`	`bind-property="value"`
> `[(property)]="value"`	`bindon-property="value"`
> `(event)="eventHandler($event)"`	`on-event="eventHandler($event)"`
> `#variable`	`ref-variable`
> `[@trigger]="value"`	`bind-animate-trigger="value"`

Good catch! I totally missed that one.

**Comment by LayZeeDK** [comment]
I guess a reason for the HTML-like de-sugared template syntax back in the day was not to break tooling such as language support in editors. Nowadays, that seems to be less of a problem considering an official language server is provided by Angular.

I guess another reason was to support [*valid HTML*](https://validator.w3.org/). With AOT compilation, I guess that's less of an issue. In general, it doesn't seem to be as big of a deal as it was 6-7 years ago when features like these were designed.

**Comment by flash-me** [comment]
> I guess a reason for the HTML-like de-sugared template syntax back in the day was not to break tooling such as language support in editors. Nowadays, that seems to be less of a problem considering an official language server is provided by Angular.
> 
> I guess another reason was to support [_valid HTML_](https://validator.w3.org/). With AOT compilation that's less of an issue. In general, it doesn't seem to be as big of a deal as it was 6-7 years ago when features like these were designed.

[Thrid reason](https://www.reddit.com/r/angular/comments/if3ipa/comment/g2mo9j7/?utm_source=share&utm_medium=web2x&context=3) ? :) 

cheers
flash ⚡

**Comment by LayZeeDK** [comment]
That's a good one, @flash-me 😊 In light of that, the template syntax planned for deprecation might be a familiar looking data binding syntax for Vue and Aurelia developers.

**Comment by atscott** [comment]
Resolved by #43671. This syntax will be deprecated in v13.
