### ISSUE TITLE
Order of mixins somehow breaks Angular

### ISSUE THREAD

**Issue by angelaki** [angular/angular#43681]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Angular seams to have problems with some mixin scenarias. I've created a short Stackblitz to show the problems:

- `Hello2Component` works while `HelloComponent` does not work - the only difference is the mixin-order that shouldn't mind, does it?
- `Hello3Component` builds fine while the only difference is, that the mixins get _mixed in_ step by step and not at once
- And when creating this stackblitz already: is there a chance that `model$ (Observable<T>)` does not lose it's type infromations (or gets merged to `unknown | T`) when using mixins?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-i9prsf?file=src%2Fapp%2Fhello.component.ts

### Please provide the exception or error you saw

```true
Property 'model' does not exist on type 'HelloComponent'.(2339)
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.1.0
```

**Comment by JoostK** [comment]
I don't see anything specific to Angular in your issue; this is plain TypeScript that is reporting errors. As such, this is probably better suited for StackOverflow.

If you think I'm missing something please feel free to follow up; I'll close for now.

**Comment by angelaki** [comment]
@JoostK  on Stackoverflow my topic got corrected to be not Typescript but Angular compiler specific. But maybe they were wrong. But is there an easy way out? This seams so trivial, I'm sure im mistaken somehiw ...

**Comment by JoostK** [comment]
[Here you go in plain TS4.3.5](https://www.typescriptlang.org/play?strictPropertyInitialization=false&ts=4.3.5#code/JYOwLgpgTgZghgYwgAgMoFcBGArCCwA8AKgHzIDeAsAFDLIDOW9CUwmEAFDCAFzIcA3PkQCUyALxkBAe2AATEXxnyA3DQC+NGhAAeAB2lQwyOXgA2cKCjABPPSgCCmemCiIwAYWkgXUdPkNiCWRpHDwwMnFkOGdXd2QQCAB3fho6ADpMywBzej44EBsAbQBdGjFJZCI1ahoY33iEC3p6ZC8AWwNE8AAhOHoUck1a6nq4-GQm-taAWWlTMw6uiF7+iGIyXUgQOVal7xWwPoGKNOR2+YgzYRq6C4WAEj4MMPwNmuGaGHQQfGBvc7AHSgACMQS2K12yCcDXwXh8rn8YEC+26RzWJBIHGOEGEYiotGisTcEymLWQMyBoOQEJ2rRxp0JdAA9MyADLSbLABDIAAW0AgZ0+hKsYHQUBAFKpIBBHy01F0BiMyG+vzA-0l7WlACYCGciDSdNsoTDxp5vL4kYE5gtUYccQQfgBrEDSJIgTE0LE4vGMuhjEnGMmzHWG430tZ+ujIVkcrk8-lWIXyuii8WSynAkDauUjYMUy5mKMCOBmdC4hiuUDZXPafSGIPNVoACSuZmkdvAYchrS1WZBHD7oG1HBtV076IGIhEBDHZjIBLoIDg7QrvmrNTOkBcHEUyGUcijdDAvOA9HS9yuwXI+9L5b4AHIQQ-kOpbq+NPLFQ3Jk3kK2zHbbUJ27OlASzEchxlUdCwnHFp1nQsFzOZdVz4dcQBrFNkG3MBdyUWRD0XaMTzPC9C2vW8ywrJ8XzfZNqGFBALSDZEoGCKCBznOC1hEGpmIRSY2O1DidQ4AIoD4r962VfMAPbABmEDaShCTdTnZDCVQtcq0wzdCVw-D90Io8cNPc9LyLKIbxLajH2fV932PczyMedJGGcFg2E4QQKjIAT6GkMwIHSdtskEdJbPLad32GYYgA). The mixin ordering does not raise an error [in TS 4.4 though](https://www.typescriptlang.org/play?strictPropertyInitialization=false&ts=4.4.3#code/JYOwLgpgTgZghgYwgAgMoFcBGArCCwA8AKgHzIDeAsAFDLIDOW9CUwmEAFDCAFzIcA3PkQCUyALxkBAe2AATEXxnyA3DQC+NGhAAeAB2lQwyOXgA2cKCjABPPSgCCmemCiIwAYWkgXUdPkNiCWRpHDwwMnFkOGdXd2QQCAB3fho6ADpMywBzej44EBsAbQBdGjFJZCI1ahoY33iEC3p6ZC8AWwNE8AAhOHoUck1a6nq4-GQm-taAWWlTMw6uiF7+iGIyXUgQOVal7xWwPoGKNOR2+YgzYRq6C4WAEj4MMPwNmuGaGHQQfGBvc7AHSgACMQS2K12yCcDXwXh8rn8YEC+26RzWJBIHGOEGEYiotGisTcEymLWQMyBoOQEJ2rRxp0JdAA9MyADLSbLABDIAAW0AgZ0+hKsYHQUBAFKpIBBHy01F0BiMyG+vzA-0l7WlACYCGciDSdNsoTDxp5vL4kYE5gtUYccQQfgBrEDSJIgTE0LE4vGMuhjEnGMmzHWG430tZ+ujIVkcrk8-lWIXyuii8WSynAkDauUjYMUy5mKMCOBmdC4hiuUDZXPafSGIPNVoACSuZmkdvAYchrS1WZBHD7oG1HBtV076IGIhEBDHZjIBLoIDg7QrvmrNTOkBcHEUyGUcijdDAvOA9HS9yuwXI+9L5b4AHIQQ-kOpbq+NPLFQ3Jk3kK2zHbbUJ27OlASzEchxlUdCwnHFp1nQsFzOZdVz4dcQBrFNkG3MBdyUWRD0XaMTzPC9C2vW8ywrJ8XzfZNqGFBALSDZEoGCKCBznOC1hEGpmIRSY2O1DidQ4AIoD4r962VfMAPbABmEDaShCTdTnZDCVQtcq0wzdCVw-D90Io8cNPc9LyLKIbxLajH2fV932PczyMedJGGcFg2E4QQKjIAT6GkMwIHSdtskEdJbPLad32GYYgA).

**Comment by angelaki** [comment]
Oh - wow! Thank you for your effort! So it will probably work with Angular 13, right?

**Comment by JoostK** [comment]
Yes and no; you may run into #42594 when using mixins, please see https://github.com/angular/angular/issues/42594#issuecomment-868091258.

**Comment by angelaki** [comment]
Thank you! Yes, I know / have this design issue and it's ok for me. I try not to use annotations in my mixins at all - that's why I use both mixins and inheritance. If I really need it, I repeat it in my implementation.
