### ISSUE TITLE
Migration to Angular 12 broke trackBy (previously was perfectly working)

### ISSUE THREAD

**Issue by 4skinSkywalker** [angular/angular#43701]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Hi guys,

I'm having problems mentioned [here](https://github.com/angular/angular/issues/42609) and [here](https://github.com/angular/angular/issues/40125).

I've migrated from Angular 10 to Angular 12 and my trackBy isn't working anymore, my code is simple:

```html
<app-box-received
    *ngFor="let box of paginatedBoxes; index as i; trackBy: identifier"
    [box]="box"
></app-box-received>
```

```ts
// This piece of code instructs Angular how to track boxes efficiently, when and where to touch the DOM
identifier(index, box) {
    return `${box.sender}-${box.recipient}-${box.taken}-${box.timestamp}`;
}
```

Guys please stop the automatic closing of issues it they are not solved.

Thanks,
Fredo

### Please provide the exception or error you saw

```true
No exception, just doesn't work and it worked in previous versions
```

### Please provide the environment you discovered this bug in

```true
"name": "...",
  "version": "0.0.0",
  "browser": { "crypto": false },
  "resolutions": { "webpack": "^5.0.0" },
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.2.10",
    "@angular/common": "~11.2.10",
    "@angular/compiler": "~11.2.10",
    "@angular/core": "~11.2.10",
    "@angular/forms": "~11.2.10",
    "@angular/platform-browser": "~11.2.10",
    "@angular/platform-browser-dynamic": "~11.2.10",
    "@angular/router": "~11.2.10",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.9",
    "@angular/cli": "~11.2.9",
    "@angular/compiler-cli": "~11.2.10",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.5"
  }
}
```

**Comment by petebacondarwin** [comment]
@4skinSkywalker - it seems from your issue description that you are on Angular v11 not v12. The issue was fixed in v12.1.x and v12.2.x, so I recommend upgrading to that version. If that still doesn't work, please can you provide a runnable reproduction that demonstrates the problem so that we can investigate.

**Comment by 4skinSkywalker** [comment]
I'm running some tests to check if I'm doing some mistake... But the objects that I've in the array are basically the same...

```js
// Getting boxes...

// Run a check to see if anything changed
let trackBy = (i, box) => !box ? "" : `${box.sender}-${box.recipient}-${box.taken}-${box.timestamp}`;
let hasChanged = boxes.some((box, i) => {
    let isDiff = trackBy(i, box) !== trackBy(i, this.preIncBox[i]);
    console.log(trackBy(i, box), trackBy(i, box));
    return isDiff;
});
console.log("Has changed?", hasChanged);
this.preIncBox = boxes;
if (hasChanged) {
    this.count++
    if (this.count > 1) {
        throw new Error();
    }
}
```

```
[...]
main.js:1 Has changed? true
[First time a change is expected]
[...]
main.js:1 Has changed? false
[Then changed is always false as expected]
```

Not only this but I've also tried the following:

```js
currBoxes.some((b, i) => {
    return JSON.stringify(b) !== JSON.stringify(prevBoxes[i]);
});
```
And it evaluated to false, which means no distinction were found between the two.

I went from Angular 10 to Angular 11 to Angular 12 and already in Angular 11 was not working anymore.

I can't share a reproducible of this exact thing now cause I'm running short of time for a feature, I'll have to implement this trackBy feature on my own.

**Comment by JoostK** [comment]
I am really confused now. You referred to #42609 and #40125 which describe an issue that affect type-checking when using `trackBy`, yet those examples show programmatic samples and appear to indicate that there is an issue with runtime behavior.

**Comment by 4skinSkywalker** [comment]
Sorry for the incovenience, I had an error in my code!
For the compilation being slow I've solve by changing a couple of entries in angular.json and now it's blazing fast.
Thank you!
