### ISSUE TITLE
How to get the injector of the compiled module using compileModuleAsync?

### ISSUE THREAD

**Issue by jon9090** [angular/angular#43715]
I want to compiler ngModule using compileModuleAsync.

```
 const module = await this.compiler.compileModuleAsync(FooModule);
```
I try to use this code:
```
 const injector = module.create(this.injector);
```

This code gives me the injector of the **current module** But I need the injector of the ngmodule itself (FooModule).
 
So how I get the correct injector?

**Comment by flash-me** [comment]
The `create` method of the `NgModuleFactory` returns an `NgModuleRef`, which has the `injector` property.
- [NgModuleFactory](https://angular.io/api/core/NgModuleFactory#create)
- [NgModuleRef](https://angular.io/api/core/NgModuleRef)

For you case, this would be 
```ts
const moduleFactory = await this.compiler.compileModuleAsync(FooModule);
const moduleRef = moduleFactory.create(this.injector);
const moduleInjector = moduleRef.injector;
```

cheers
flash ⚡
