### ISSUE TITLE
Add JoinPipe to @angular/common

### ISSUE THREAD

**Issue by EliHowey** [angular/angular#43711]
### Which @angular/* package(s) are relevant/releated to the feature request?

common

### Description

In component templates, it's common to join an array of data with some separator:

```html
<p>{{ myData.join(', ') }}</p>
```

But function calls are evaluated every change detection cycle, so this could incur a hefty performance cost for large arrays. In those cases, a pipe could improve the performance of the operation.

### Proposed solution

`@angular/common` should offer a `JoinPipe` that accepts an `Array` as input and returns the result of `Array.prototype.join` called with a given `separator` (`,` by default, matching the spec).

### Alternatives considered

Applications can create a `JoinPipe` if they need it (large applications have probably done this already). But this could result in many different implementations of the pipe in the wild, several of which might unintentionally reimplement `Array.prototype.join`, resulting in unnecessary code shipped to users. A standard implementation is preferred.

**Comment by petebacondarwin** [comment]
While it is true that a `join` pipe is fairly common and would benefit from being in a shared package, this could be said for a number of other similar operations. There are already libraries out there that offer this, which application developers could leverage. Consider https://fknop.gitbook.io/angular-pipes/documentation/array for example. This library has dozens of pipes for many scenarios.

**Comment by pkozlowski-opensource** [comment]
We do not plan to extend the set of the built-in pipes at the moment. The `join` pipe is pretty trivial to write and share as a library. This is a great candidate for a community library.
