### ISSUE TITLE
How to process @angular packages with the linker without @angular/cli

### ISSUE THREAD

**Issue by flash-me** [angular/angular#43716]
### Which @angular/* package(s) are relevant/releated to the feature request?

compiler-cli

### Description

Before 13.0.0.-next.10 it was possible to execute `ngcc` and let it process the `@angular/*` packages to get ivy output in full compilation mode.

With the current release, 13.0.0-next.11, the exeuction of `ngcc` does not process the `@angular/*` packages. Therefore, these packages remain in partially compilated outputs and can't be used directly in the browser. 

Running ngcc:
![image](https://user-images.githubusercontent.com/5240450/135995016-8c4355fe-7058-4549-a88e-1252dd104ce2.png)

Browser error:
![image](https://user-images.githubusercontent.com/5240450/135995099-90657231-554c-4bc0-8af4-83ac32800909.png)

Imports packages:
![image](https://user-images.githubusercontent.com/5240450/135995180-52b5f20b-1dbe-48eb-a4d2-f67542a7a40c.png)

### Proposed solution

It would be great to have some sort of tooling / option to process the `@angular/*` packages with the linker without having to use the `@angular/cli`.

### Alternatives considered

One alternative would be to also publish the `@angular/*` packages in fully compilated mode. 

cheers
flash ⚡

**Comment by JoostK** [comment]
We expose a Babel plugin under the `@angular/compiler-cli/linker/babel` entry-point. There's likely plugins to integrate a Babel into a build pipeline (e.g. `babel-loader` for Webpack) which can then be configured to use the linker plugin.

**Comment by JoostK** [comment]
There's a mini example here:

https://github.com/angular/angular/blob/c15b8c75fa1bd8115e2dd10221919d03cf55ea24/integration/platform-server/base-config.mjs

**Comment by flash-me** [comment]
Which basically means a third party tooling must be used in order to get the fully compiled packages.

This is sad.

Are there any plans for the future to change this?

cheers
flash ⚡

**Comment by petebacondarwin** [comment]
Hi @flash-me - good question! We have exposed a Babel plugin that will do the linking at `@angular/compiler-cli/linker/babel` see https://github.com/angular/angular/tree/master/packages/compiler-cli/linker/babel. This requires that you have a Babel transform somewhere in your build pipeline.

We felt that this was the best compromise between only providing a solution for our recommended tooling (Angular CLI) and having to provide solutions for all the build tools. As I understand it many tools such as WebPack, Rollup, etc can implement such a Babel plugin fairly easily. The tricky bit is then what level of caching you are able to do to avoid having to run the linker on every build. In the Angular CLI the linker is part of a WebPack loader and we cache the results of this loader to avoid having to run the linker too often.

I would be interested in whether this would fit with your own build setups and any other ideas you have about how we could expose the linker in a way that works for you.

**Comment by flash-me** [comment]
Alright. The "minimal" option to get this work is to install `@babel/cli` and use that directly to "link" the packages. 
e.g. for the `@angular/core` package:
`babel node_modules/@angular/core/fesm2020/core.mjs -d dist --plugins=@angular/compiler-cli/linker/babel`

I think i can live with that. Nonetheless it is a dependency to an external third party tooling in order to make full use of the angular packages, which comes with a bitter after test when thinking about it.

It would be still interesting, if you are planning to get "independent" again in the future.

cheers
flash ⚡

**Comment by flash-me** [comment]
Background information:
I'm trying to use any kind of bundler as few as possible, since I'm heavily making use of ESM together with [import-maps](https://github.com/WICG/import-maps), which has been introduced with Chrome 89. 
This approach comes truly handy when using some sort of runtime composition of smaller, independent packages.

I'm kinda fan of standardized Specs and API's and try to avoid third party toolings, but as I said, the additional step with `@babel/cli` instead of running `ngcc` is something I/we can live with. 

cheers
flash ⚡

**Comment by petebacondarwin** [comment]
One way or another we need to provide AST transformation.
As it turns out the underlying transforms are agnostic to the particular AST that is being used. See https://github.com/angular/angular/tree/master/packages/compiler-cli/linker/src/ast

We chose to use Babel because it fits well with many 3rd party build tools and has a lot less overhead than using TypeScript.

Conceivably, you could build your own AST manipulation library and then implement the `AstHost` interface, allowing you to completely drop Babel (and TypeScript) from the transformation. But do you really want to have to maintain that?

**Comment by flash-me** [comment]
> Conceivably, you could build your own AST manipulation library and then implement the AstHost interface, allowing you to completely drop Babel (and TypeScript) from the transformation. But do you really want to have to maintain that?

TBH: Probably not 😄 
It's just the step away from just using `ngcc` to introducing another dependency to get things work. But since my approach is not the casual use case of the majority, I'm aware that I might have to solve some stuff on my own. 

But as I said, the use of `@babel/cli` is acceptable for me. 

cheers
flash ⚡

**Comment by flash-me** [comment]
Thanks for the information and the hints regarding the linker babel plugin! I'm closing this, since I got my stuff working. :) 

cheers
flash ⚡

**Comment by petebacondarwin** [comment]
@flash-me - I just realised, given your low bundler tooling approach, that you should be aware that the new Angular Package Format (APF) for v13 will  default to ES2020, which is not compatible out-of-the-box with Zone.js if they are using the `async await` syntax.

There are a couple of options:

- only use libraries that do not use `async - await` functions.
- apply a transform (e.g. Babel 😱 ) to downlevel the ES2020 to ES2015 (or at least downlevel the `async-await` syntaxes.
- configure your import-maps to point at the special FESM2015 export in the new format. (Is that possible?)
