### ISSUE TITLE
using (ng-model) instead of [(ng-model)] does nothing

### ISSUE THREAD

**Issue by kasperpeulen** [angular/angular#4373]
I have this simple example:

```
@Component(selector: 'app')
@View(
    template: r'''
      <input (ng-model)="text = $event">
      {{text}}
   ''',
    directives: const[FORM_DIRECTIVES]
)
class App {
  String text;
}
```

Which I thought would work as setting the text to be the same as the value of the input element, but that doesn't work. If I set also an `ng-model` attribute,  it works as expected:
```
@Component(selector: 'app')
@View(
    template: r'''
      <input ng-model (ng-model)="text = $event">
      {{text}}
   ''',
    directives: const[FORM_DIRECTIVES]
)
class App {
  String text;
}
```

Is this by design? Or is this a bug?

**Comment by vicb** [comment]
An `(ng-model)` attribute would not match the directive's selector [`[ng-model]:not([ng-control]):not([ng-form-control])`](https://github.com/angular/angular/blob/5bf6a3af152ac9e9bf5c62def396575fc82db903/modules/angular2/src/core/forms/directives/ng_model.ts#L36) - while `ng-model`, `[ng-model]` and `[(ng-model)] would.

**Comment by kasperpeulen** [comment]
I see @vicb thanks

Is it possible to have a selector match `(ng-model)` ?

**Comment by vicb** [comment]
> Is it possible to have a selector match (ng-model)

It's not and I don't think I would make sense
