### ISSUE TITLE
With routerLinkActive the root URL is always active - see #9885

### ISSUE THREAD

**Issue by alkgreer** [angular/angular#43736]
I know this issue is old and closed, but just faced this and I have to say: this is weird. Especially if you fin yourself only having to apply it to the root route 🤔

_Originally posted by @emilio-martinez in https://github.com/angular/angular/issues/9885#issuecomment-434138833_

Having the same problem a fix would be nice.

**Comment by atscott** [comment]
https://github.com/angular/angular/issues/9885#issuecomment-231242287
> This is by design. The `routerLinkActive` directive marks a routerLink as active if contained in the UrlTree. Since the root is always contained, you need to use the `[routerLinkActiveOptions]="{ exact: true }"` which will only mark it as active if the current url is an exact match to the routerLink url.
