### ISSUE TITLE
Add `type` field to the router event object

### ISSUE THREAD

**Issue by Smrtnyk** [angular/angular#43762]
### Which @angular/* package(s) are relevant/releated to the feature request?

router

### Description

I have a piece of code that gets invoked by user with router as a parameter.
In that code I subscribe to router events.
If an app is minified, constructor names of events are obfuscated and then I need to do some naive checking like 
```ts
function isNavigationEnd(event: Event): event is NavigationEnd {
    return event["constructor"]["name"] === RouterEvents.NAVIGATION_END
        || ("id" in event
            && typeof event["id"] === "number"
            && !!event["url"]
            && "urlAfterRedirects" in event
            && !!event["urlAfterRedirects"]
            && objectKeys(event).length === 3);
}
```
I am not so familiar with angular.
The issue I currently have is that I do some action in `RouteConfigLoadStart` and keep a reference to it
and I clean that reference in `NavigationCancel` or `NavigationEnd`
Now for some reason `NavigationEnd` or `NavigationCancel` never happens and references keep growing when I enter the `RouteConfigLoadStart`.
If event constructor names would be preserved I would know which event I am currently working with and could easier do the logic.
Keep in mind that my piece of code is external to the angular app, and it gets called with router as a parameter, so I am not in an non obfuscated environment of the app.

### Proposed solution

Add a `type` field to the event or preserve name of its constructor.

### Alternatives considered

I am using an alternative to do the naive checking but some events have same fields and then it could match more events than it should.

**Comment by Smrtnyk** [comment]
ok seems like if I do the `e.toString()` it would spit out the `RouteConfigLoadStart(path: )` even when the app is obfuscated

**Comment by Smrtnyk** [comment]
![Capture](https://user-images.githubusercontent.com/31451544/136414184-eb413ddb-ab31-4838-b4d3-024d945bfcc3.PNG)

**Comment by Smrtnyk** [comment]
I do understand your advice and I agree with them.
However I am not in control of this software I am working on.

Users have angular apps compiled and hosted.
Then they buy our service and include our script on the page as the first script. We work as an apm tool.
Angular app and our script are completely separated, and we have 0 prod dependencies.
Also we have our own rollout mechanism and users can disable injection of our script via UI on demand.
We are working in sprints and users can only use latest version of our software month in the past.

I do get the router instance passed in as a parameter but from a compiled app which is already live in the page.
I am able to subscribe to the router events via `router["events"]["subscribe"](createRouterEventHandler());`
Is there maybe something on the compiled router instance that I could use more in this regards?

If not at least having stringified event as a name is a second option, which is better than only one option.
Event type property would be great if there would be a plan to add that to angular. Would simplify things a lot for us.

**Comment by atscott** [comment]
Wouldn’t this have more to do with your build configuration? You can disable renaming/obfuscation to accomplish this or configure the js compiler / webpack to specifically not rename these, no?

**Comment by Airblader** [comment]
Just to throw in another (admittedly also not pretty) workaround: since your users need to call an init function from their Angular app, you could extend that to pass all relevant objects to which you need access:

```
init({
    router: this.router,

    navigationEnd: NavigationEnd,
    // ...
});
```

This snippet would even always be exactly the same for the user, so to hide that you could also offer a small Angular library for them to add which wraps the init function and passes the types along internally.

Then your init function would receive a map to the classes and you can convert the class constructor names and use it as a lookup table.

**Comment by Smrtnyk** [comment]
Hi again,
I see this landed to backlog and under consideration label.
Just wanted to check, if it is possible to expect this being implemented in the near future?

**Comment by atscott** [comment]
resolved by https://github.com/angular/angular/pull/44189
