### ISSUE TITLE
Memory leak with shadow DOM

### ISSUE THREAD

**Issue by richardmoore725** [angular/angular#43761]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

No

### Description

When I repeat opening and closing component with `ViewEncapsulation.ShadowDom`, I meet memory leak.
Of cause, I tried GC whenever I repeat it.
Following screenshots are case when I tried 6times.
![image](https://user-images.githubusercontent.com/39081818/136361624-d724fb4a-af6a-46c6-b4bd-43e32ec89a19.png)
![image](https://user-images.githubusercontent.com/39081818/136361649-c0300155-e5e0-44db-8936-a509cd77d3f5.png)
![image](https://user-images.githubusercontent.com/39081818/136361682-4ad50e8b-d54a-4987-b72d-3f465f30bb94.png)
![image](https://user-images.githubusercontent.com/39081818/136361718-cacc8ed8-6471-41d1-853d-f1c48cbc0cec.png)

![image](https://user-images.githubusercontent.com/39081818/136361162-01e0e621-8e22-4e19-9aa8-457129e32e5b.png)
![image](https://user-images.githubusercontent.com/39081818/136363335-632ae82a-6b60-4d70-a08b-082c3cc5b762.png)

**Comment by petebacondarwin** [comment]
@richardmoore725 - thanks for sending in this issue report. Please can you do two things:

1. Show the same charts but with emulated encapsulation to prove that it is the shadow DOM path that is at fault - I expect you have done this locally already.
2. Provide us with a runnable reproduction since the information you have provided here is not enough to diagnose the issue.

**Comment by beibean** [comment]
Hi all,

I'm running the same issue reported by @richardmoore725. Tested inboth Angular v10.2.5 (version for my project) and new v13.0.2, experiencing same DOM NODEs leak and therefore, memory leak.

[Here you can find a simple repro project](https://stackblitz.com/edit/angular-ivy-dkpp9u?devtoolsheight=33&file=src/app/components/modal-panels/leak-panel/dummy/dummy.component.ts)

To see the leak, just open and close the panel several times and see how DOM Nodes keep increasing (even if you click GC).

As noted above, leak seems to be related with ShadowDom on destroyed component *dummyComponent*. 
@petebacondarwin If you change encapsulation of dummyComponent to either **.None** or **.Emulated**, leak dissapears.

I have tried several things like setting __ngContext__ to null with no success.

Any workaround to fix this??

Thanks in advance.

**Comment by JoostK** [comment]
Based on the comment from @beibean and the lack of response otherwise, I'll close this as a duplicate of #36655, which has been fixed in Angular 11.2.4 and up.
