### ISSUE TITLE
`host` does not support directives

### ISSUE THREAD

**Issue by wesleycho** [angular/angular#4379]
I have an example [here](http://plnkr.co/edit/blhYNtxDtZxUFB4IQdsf?p=preview) in attempting to reimplement a dropdown, and I tried refactoring it to be simpler & not as reliant on a template [here](http://plnkr.co/edit/ZqpoOsWkdkO2XikRV9fc?p=preview) - however, this causes a problem because it seems to error out on a directive being used as a host property.

Is my understanding of this correct? Should this be potentially allowed with Angular, or is this behavior explicitly forbidden?

**Comment by pkozlowski-opensource** [comment]
I really don't think we want to go into supporting directives in the `host` property as this would open a can of wired corner use-cases. 

Having said this you can easily set a particular class on the host using:

```javascript
 host: {
    '[class.open]': 'open'
  }
```

See: http://plnkr.co/edit/VTQbCQ44g7YoyZ115uNS?p=preview
