### ISSUE TITLE
Angular2's property binding not working with Polymer element

### ISSUE THREAD

**Issue by tapas4java** [angular/angular#4380]
I am trying to use Polymer elements inside Angular2 component. There are no errors on console and polymer paper input is rendering fine but message is blank. 

```
@Component({
	selector: 'home'
})
@View({
	template: `
		<h1>This is HOME!</h1>
		<paper-input [label]="message" ></paper-input>
	`
})
export class Home {
	message: string = '';
	constructor() {
		this.message = 'Tapas Jena @Home!';
	}
}
```

**Comment by pkozlowski-opensource** [comment]
@tapas4java there is not enough context here to help. Property bindings should work without problems for custom elements, including ones created with Polymer.

Please prepare a live reproduce scenario using plunker or similar so we can take a look. Thnx.

**Comment by vagabondtt1503** [comment]
@tapas4java, @pkozlowski-opensource I tried angular 2.0 with polymer starter Kit. Polymer component render quite good. But, when I used angulard router (ex. <router-outlet></router-outlet>). My app is broken. I am waiting for next version polymer or next version angular which can run together.

**Comment by tapas4java** [comment]
Thanks @pkozlowski-opensource, 

It worked when i tried on a fresh repo.
