### ISSUE TITLE
Improve error message "No value accessor for form control with unspecified name attribute" to suggest what to do to fix the issue

### ISSUE THREAD

**Issue by zlepper** [angular/angular#43821]
### Which @angular/* package(s) are relevant/releated to the feature request?

forms

### Description

When you get the error `No value accessor for form control with unspecified name attribute`, there are generally two things that possibly has gone wrong:

You are using `ngModel` with a third party control that doesn't register a `NG_VALUE_ACCESSOR`. In this case you need to use `ngDefaultControl` on the element. 

Alternatively you have forgotten to register a `NG_VALUE_ACCESSOR` for your custom form input:
```
providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => MyInputField),
      multi: true
    }
  ]
  
```

### Proposed solution

It would be very nice if the error message Angular generated would actually suggest on of those things as being the actually problem, and thus what you should probably do to fix it, in the error message. 

### Alternatives considered

I mean, Angular could just leave it as is, and people can keep using Google I guess, though that is a suboptimal solution in my opinion.

**Comment by KurtGokhan** [comment]
It can also happen when you forgot to import the component's module. I think the error message should be improved for clarity.

**Comment by piyushdanej** [comment]
> It can also happen when you forgot to import the component's module. I think the error message should be improved for clarity.

Thanks a ton !
I was having this exact same issue in my test case where my component's template had a component from shared module .
Just had to import shared module in my test case.

**Comment by lufo88ita** [comment]
Hi,
It also happens when you put a ngModel on a html element that cannot have a value (of course is an error on my side)

In my case this happens:
```
<div  [(ngModel)]="myModel"> <--- my error
    <select>
         <!-- code not relevant -->
    </select>
</div>
```
The error message does not help me and is very confusing because I do not use <form> in this context.

**Comment by mikebellcoder** [comment]
I just ran into this error occurring as output for a failing test. 
In the component with a failing test I used a custom form control which itself uses the NG_VALUE_ACCESSOR custom form control API. 

The solution was to add the missing custom form component to the Testbed.configureTestingModule component declarations and the error went away. 

Noting this here as another scenario where this error can be seen and not understood.

**Comment by LoaderB0T** [comment]
I came across this error under fairly specific circumstances while migrating an angular project to Nx with **Module Federation**. Just in case anyone comes across this issue with a similar situation.

I have a shared library that declares a custom control with the `NG_VALUE_ACCESSOR` and `ControlValueAccessor` mechanics that is used in different Module-Federation-enabled apps in my workspace.

Worked fine at first but when I declared in the webpack.config.js that the shared library should *actually* be shared and not be included twice the controls broke with the mentioned very unhelpful error message:
```typescript
sharedMappings.register(tsConfigPath, ['@myapp/shared', ...]) 
//                                       ^-- added shared lib to the sharedMappings declaration 
//                                           of '@angular-architects/module-federation'
```

In my case, the root cause of this error was that I did not share the `@angular/forms` package in the `webpack.config.js`
To fix edit your `webpack.config.js` files from all affected apps:

```typescript
module.exports = {
...
  plugins: [
    new ModuleFederationPlugin({
      remotes: {
         ...
      },
      shared: share({
        '@angular/forms': { // <-- This was missing
          singleton: true,
          strictVersion: true,
          requiredVersion: 'auto',
          includeSecondaries: true
        },
        ...
      }),
      ...
    }),
    ...
  ]
};
```

**Comment by marleypowell** [comment]
> I came across this error under fairly specific circumstances while migrating an angular project to Nx with **Module Federation**. Just in case anyone comes across this issue with a similar situation.
> 
> I have a shared library that declares a custom control with the `NG_VALUE_ACCESSOR` and `ControlValueAccessor` mechanics that is used in different Module-Federation-enabled apps in my workspace.
> 
> Worked fine at first but when I declared in the webpack.config.js that the shared library should _actually_ be shared and not be included twice the controls broke with the mentioned very unhelpful error message:
> 
> ```ts
> sharedMappings.register(tsConfigPath, ['@myapp/shared', ...]) 
> //                                       ^-- added shared lib to the sharedMappings declaration 
> //                                           of '@angular-architects/module-federation'
> ```
> 
> In my case, the root cause of this error was that I did not share the `@angular/forms` package in the `webpack.config.js` To fix edit your `webpack.config.js` files from all affected apps:
> 
> ```ts
> module.exports = {
> ...
>   plugins: [
>     new ModuleFederationPlugin({
>       remotes: {
>          ...
>       },
>       shared: share({
>         '@angular/forms': { // <-- This was missing
>           singleton: true,
>           strictVersion: true,
>           requiredVersion: 'auto',
>           includeSecondaries: true
>         },
>         ...
>       }),
>       ...
>     }),
>     ...
>   ]
> };
> ```
> 
> I know this is very specific, but still, the error message did not lead me anywhere useful :) So would be cool if the message would give a better hint at what is broken.

Thanks for this. This was exactly the problem I had :)

**Comment by JimiSweden** [comment]
just adding my issue and resolution (add ngDefaultControl):  
Using mat-buton with [formControl]="control", inside ng-template. 

This works in another project (angular 12.2.3) but not in this 13.3.0. (not sure if it has to do with that...

**the code, works with ngDefaultControl but not without it,** 
_adding a name to the button didn't solve the issue either_

```
 <ng-template #filterButtonsStepper let-control="control">

       <button mat-icon-button [formControl]="control" ngDefaultControl
      (click)="filterButtonsStepperAdvance(control)">
      <mat-icon class="green-icon" *ngIf="control.value == 'true'">
        check_circle_outline
      </mat-icon>
     <!-- more icons... -->
    </button>
  </ng-template>

     <!-- using the template -->
<ng-template [ngTemplateOutlet]="filterButtonsStepper"
                [ngTemplateOutletContext]="{control: filerFormControls.availableForBooking}"></ng-template>


```

**Comment by Asanmohameds** [comment]
gfhgfhf

**Comment by matew17** [comment]
Thank you so much !!, 

You just saved me hours of debugging, I had the exact same error.


> I came across this error under fairly specific circumstances while migrating an angular project to Nx with **Module Federation**. Just in case anyone comes across this issue with a similar situation.
> 
> I have a shared library that declares a custom control with the `NG_VALUE_ACCESSOR` and `ControlValueAccessor` mechanics that is used in different Module-Federation-enabled apps in my workspace.
> 
> Worked fine at first but when I declared in the webpack.config.js that the shared library should _actually_ be shared and not be included twice the controls broke with the mentioned very unhelpful error message:
> 
> ```ts
> sharedMappings.register(tsConfigPath, ['@myapp/shared', ...]) 
> //                                       ^-- added shared lib to the sharedMappings declaration 
> //                                           of '@angular-architects/module-federation'
> ```
> 
> In my case, the root cause of this error was that I did not share the `@angular/forms` package in the `webpack.config.js` To fix edit your `webpack.config.js` files from all affected apps:
> 
> ```ts
> module.exports = {
> ...
>   plugins: [
>     new ModuleFederationPlugin({
>       remotes: {
>          ...
>       },
>       shared: share({
>         '@angular/forms': { // <-- This was missing
>           singleton: true,
>           strictVersion: true,
>           requiredVersion: 'auto',
>           includeSecondaries: true
>         },
>         ...
>       }),
>       ...
>     }),
>     ...
>   ]
> };
> ```
> 
> I know this is very specific, but still, the error message did not lead me anywhere useful :) So would be cool if the message would give a better hint at what is broken.

**Comment by dylhunn** [comment]
Thank you to everyone who commented. I have opened PR #47969 to cause this error message to link to an error guide with debugging suggestions, based on your comments.

**Comment by dylhunn** [comment]
Thank you to everyone who commented, @zlepper @KurtGokhan @lufo88ita @mikebellcoder @LoaderB0T. I have opened https://github.com/angular/angular/pull/47969 to link this error message to a guide with debugging suggestions. (Feel free to let me know and/or edit the guide if you come up with other cases or want to improve it further.)
