### ISSUE TITLE
require() of ES modules is not supported

### ISSUE THREAD

**Issue by jponeill** [angular/angular#43833]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

It looks like a change between 13.0.0-next.9 and 13.0.0-next.10 breaks using @graphql-tools/webpack-loader with @angular-builders/custom-webpack. (PR  #43431 ?) 

To reproduce:

npm i -g @angular/cli@13.0.0-next.9

1 ng new graphql 
2. npm i @angular-builders/custom-webpack --save-dev
3. npm i @graphql-tools/webpack-loader
4. Change angular.json line to  "builder": "@angular-builders/custom-webpack:browser"
5. Create extra-webpack.config.js in project root directory
module.exports = {
  module: {
    rules: [
      {
        test: /\.(graphql|gql)$/,
        exclude: /node_modules/,
        loader: '@graphql-tools/webpack-loader'
      }
    ]
  }
}

... run ng build and get error: "An unhandled exception occurred: Must use import to load ES Module"

If I run npm i @angular/compiler-cli@13.0.0-next.9 @angular/compiler@13.0.0-next.9 and then ng build again the error goes away. 

(This might be an issue w/ @graphql-tools/webpack-loader and I'd appreciate any suggestions of how to handle it)
 

### Please provide the exception or error you saw

```true
An unhandled exception occurred: Must use import to load ES Module: /Users/jimoneill/WebstormProjects/graphql/node_modules/@angular/compiler-cli/bundles/index.js
require() of ES modules is not supported.
require() of /Users/jimoneill/WebstormProjects/graphql/node_modules/@angular/compiler-cli/bundles/index.js from /Users/jimoneill/WebstormProjects/graphql/node_modules/@angular-builders/custom-webpack/node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/jimoneill/WebstormProjects/graphql/node_modules/@angular/compiler-cli/package.json.

See "/private/var/folders/rx/t07d1gy51252srmyqqngvp840000gn/T/ng-6zi4GO/angular-errors.log" for further details.
jimon
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 13.0.0-next.9
Node: 14.18.1
Package Manager: npm 6.14.15
OS: darwin x64

Angular: 13.0.0-rc.0
... animations, common, core, forms, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.10
@angular-devkit/build-angular   13.0.0-next.9
@angular-devkit/core            12.2.10
@angular-devkit/schematics      13.0.0-next.9
@angular/cli                    13.0.0-next.9
@angular/compiler               13.0.0-next.15
@angular/compiler-cli           13.0.0-next.15
@schematics/angular             13.0.0-next.9
rxjs                            7.4.0
typescript                      4.4.4
```

**Comment by jponeill** [comment]
The following issue might be related and require() is used, but I'm not sure why it broke between @angular/compiler-cli@13.0.0-next.9 @angular/compiler@13.0.0-next.9  and @angular/compiler-cli@13.0.0-next.10 @angular/compiler@13.0.0-next.10.

https://github.com/just-jeb/angular-builders/issues/978

**Comment by JounQin** [comment]
https://github.com/rx-ts/synckit may help.

See https://github.com/angular-eslint/angular-eslint/issues/715#issuecomment-945539868 for example.

**Comment by piotrtomiak** [comment]
@jponeill Please follow https://youtrack.jetbrains.com/issue/WEB-53312 . There was a slight change in the format of *.d.ts files and NgModules are not picked up by our model. Expect a fix in 2021.3 release.

**Comment by pinich** [comment]
> `jest-preset-angular` is also impacted by this because we use downlevel ctor transformer function directly from `@angular/compiler-cli` via `require`.
> 
> A workaround now that `jest-preset-angular` adopts Jest async transformer.
> 
> It would be nice if there is a fallback somehow for this issue.

Is there any workaround this issue , After updating to Angular 13 our Jest tests unable to run and fail with

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module :
..\@angular\compiler-cli\bundles\index.js        
require() of ES modules is not supported.
```

**Comment by pinich** [comment]
> > `jest-preset-angular` is also impacted by this because we use downlevel ctor transformer function directly from `@angular/compiler-cli` via `require`.
> > A workaround now that `jest-preset-angular` adopts Jest async transformer.
> > It would be nice if there is a fallback somehow for this issue.
> 
> Is there any workaround this issue , After updating to Angular 13 our Jest tests unable to run and fail with
> 
> ```
> Error [ERR_REQUIRE_ESM]: Must use import to load ES Module :
> ..\@angular\compiler-cli\bundles\index.js        
> require() of ES modules is not supported.
> ```

When I try to run Jest test I get:
` FAIL  src/app/shared/utils/utils.spec.ts
  ● Test suite failed to run

    Cannot find module '@angular/core/testing' from 'node_modules/jest-preset-angular/build/setup-jest.js'

    Require stack:
      node_modules/jest-preset-angular/build/setup-jest.js
      node_modules/jest-preset-angular/setup-jest.js
      setup-jest.ts

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)`
For each test

**Comment by ahnpnl** [comment]
@pinich please use **jest-preset-angular@11.0.0-rc.3** in the meanwhile.

**Comment by JoostK** [comment]
I'll close this issue now as all major tooling we're aware of (Jest, eslint and Nx) have released updates in support of Angular 13. Thanks to everyone involved in making these updates available, your effort is hugely appreciated 🙏

**Comment by mattiLeBlanc** [comment]
I also get this issue using `@biesbjerg/ngx-translate-extract`:
```
node:internal/modules/cjs/loader:979
    throw new ERR_REQUIRE_ESM(filename, true);
    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/matti/www/dashboard/node_modules/@angular/compiler/fesm2015/compiler.mjs not supported.
Instead change the require of /Users/matti/www/dashboard/node_modules/@angular/compiler/fesm2015/compiler.mjs to a dynamic import() which is available in all CommonJS modules.
```
Is there a way to get this resolved?

**Comment by JoostK** [comment]
@mattiLeBlanc Please see https://github.com/biesbjerg/ngx-translate-extract/issues/246; that would be something for that project to address.

**Comment by mattiLeBlanc** [comment]
@JoostK Thanks for the reference.

**Comment by phihochzwei** [comment]
i got the exact same when trying to run Angular Universal:

`C:\__GIT\frontend\dist\apps\storefront-ssr\main.js:26409
module.exports = require("@angular/core");
^
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\__GIT\frontend\node_modules\@angular\core\fesm2015\core.mjs not supported.
  Instead change the require of C:\__GIT\frontend\node_modules\@angular\core\fesm2015\core.mjs to a dynamic import() which is available in all CommonJS modules.
  at Object.@angular/core (C:\__GIT\frontend\dist\apps\storefront-ssr\main.js:26409:18)
at __webpack_require__ (C:\__GIT\frontend\dist\apps\storefront-ssr\main.js:26505:41)
at C:\__GIT\frontend\dist\apps\storefront-ssr\main.js:26526:16
at C:\__GIT\frontend\dist\apps\storefront-ssr\main.js:26565:3
at Object.<anonymous> (C:\__GIT\frontend\dist\apps\storefront-ssr\main.js:26570:12)`

Anyone an idea?

**Comment by nhhockeyplayer** [comment]
so terrible
one would think after the version 12 upheaval they would learn from their mistakes
all they care about is making a name for one SELF
AND THEN CLOSE THE ISSUE AS SOON AS POSSIBLE

**Comment by nhhockeyplayer** [comment]
More development shutdown and halted

the open source is now out of control

whoever is prompting the world to be taken out... those committers need severe dope slaps and removal

**Comment by nhhockeyplayer** [comment]
I got same thing... no solution as of yet? can someone post a workaround?
```

> nx run api-typegoose:serve 
chunk (runtime: main) main.js (main) 26.6 KiB [entry] [rendered]
webpack compiled successfully (971839507369f1c5)
Debugger listening on ws://localhost:9229/c43e256e-b661-45af-8ce2-f83585f6b639
Debugger listening on ws://localhost:9229/c43e256e-b661-45af-8ce2-f83585f6b639
For help, see: https://nodejs.org/en/docs/inspector
Issues checking in progress...

file:///Users/meanstack02/new/starter/dist/apps/api-typegoose/webpack:/starter/external commonjs "tslib":1
module.exports = require("tslib");
^
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/Users/meanstack02/new/starter/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at Object.tslib (file:///Users/meanstack02/new/starter/dist/apps/api-typegoose/webpack:/starter/external commonjs "tslib":1:1)
    at __webpack_require__ (file:///Users/meanstack02/new/starter/dist/apps/api-typegoose/webpack:/starter/webpack/bootstrap:19:1)
    at file:///Users/meanstack02/new/starter/dist/apps/api-typegoose/main.js:889:17
    at file:///Users/meanstack02/new/starter/dist/apps/api-typegoose/main.js:949:3
    at file:///Users/meanstack02/new/starter/dist/apps/api-typegoose/main.js:954:12
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at loadESM (node:internal/process/esm_loader:88:5)
    at handleMainPromise (node:internal/modules/run_main:65:12)
No issues found.
```

**Comment by leonzhang51** [comment]
Solved problem by 
1. ng update -- to update angular for the local project
2.  open package.json to change all the angular items in "dependencies" and "devDependencies" from 12 to 13 
ex:
"dependencies": {
    "@angular/animations": "~13.1.1",
    "@angular/cdk": "^13.1.1",
    "@angular/common": "~13.1.1",
    "@angular/compiler": "~13.1.1",
    "@angular/core": "~13.1.1",
    "@angular/forms": "~13.1.1",
    "@angular/material": "^13.1.1",
    "@angular/platform-browser": "~13.1.1",
    "@angular/platform-browser-dynamic": "~13.1.1",
    "@angular/router": "~13.1.1",
}
"devDependencies": {
    "@angular-devkit/build-angular": "~13.1.1",
    "@angular/cli": "~13.1.1",
    "@angular/compiler-cli": "~13.1.1",
"typescript": "~4.5.4"
}

3. npm install

All done

**Comment by filipwiniarski** [comment]
I also get this one:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /___/tailwind.config.js from /Users/___/node_modules/tailwindcss/lib/lib/setupWatchingContext.js not supported.
Instead change the require of tailwind.config.js in /Users/___/node_modules/tailwindcss/lib/lib/setupWatchingContext.js to a dynamic import() which is available in all CommonJS modules.
    at Module.require (/___/node_modules/@nrwl/tao/src/compat/compat.js:13:40)
    at getTailwindConfig (/___/node_modules/tailwindcss/lib/lib/setupWatchingContext.js:167:53)
    at /___/node_modules/tailwindcss/lib/lib/setupWatchingContext.js:227:92
    at /___/node_modules/tailwindcss/lib/processTailwindFeatures.js:37:11
    at plugins (/___/node_modules/tailwindcss/lib/index.js:22:68)
    at LazyResult.runOnRoot (/___/node_modules/@angular-devkit/build-angular/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/___/node_modules/@angular-devkit/build-angular/node_modules/postcss/lib/lazy-result.js:393:26)
    at async Object.loader (/___/node_modules/postcss-loader/dist/index.js:97:14)
```

**Comment by FrancescoBorzi** [comment]
I got the same using ngapimock

**Comment by FrancescoBorzi** [comment]
I got the same using ngapimock. This is affecting Angular 13, while it worked fine until Angular 12.

**Comment by tonysamperi** [comment]
Hope this helps: I had the same problem, until I realized I forgot to update (yes, I updated the package.json manually) ng-packagr which was still v12. After setting v13 everything was fine.

**Comment by FrancescoBorzi** [comment]
> I got the same using ngapimock. This is affecting Angular 13, while it worked fine until Angular 12.

cc @mdasberg

**Comment by mdasberg** [comment]
@FrancescoBorzi thanks for reporting this. I will create a ticket for ng-apimock and investigate

**Comment by jlavric** [comment]
I got the same problem after update from 12.x to 13. I have noticed that my @angular-devkit/build-angular package was somehow misaligned. After I installed 13.x version of @angular-devkit/build-angular everything was fine again.
Maybe it will help someone!
Have fun!

**Comment by windmateus** [comment]
> Hope this helps: I had the same problem, until I realized I forgot to update (yes, I updated the package.json manually) ng-packagr which was still v12. After setting v13 everything was fine.

This solved my problem.
Thanks!

**Comment by eng-dibo** [comment]
> I'll close this issue now as all major tooling we're aware of (Jest, eslint and Nx) have released updates in support of Angular 13. Thanks to everyone involved in making these updates available, your effort is hugely appreciated 🙏

your [build-webpack](https://github.com/angular/angular-cli/issues/22547) still has the same issue

**Comment by just-jeb** [comment]
I've [done](https://github.com/just-jeb/angular-builders/issues/1101#issuecomment-1019559724) some research with `custom-webpack` builder and either I'm missing something or `@angular-devkit/architect` is not fully compatible with ESM: 
```console
An unhandled exception occurred: Must use import to load ES Module: /Users/jeb/angular-builders/packages/custom-webpack/dist/browser/index.js
require() of ES modules is not supported.
require() of /Users/jeb/angular-builders/packages/custom-webpack/dist/browser/index.js from /Users/jeb/angular-builders/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/jeb/angular-builders/packages/custom-webpack/package.json.
```

**Comment by eng-dibo** [comment]
> I've [done](https://github.com/just-jeb/angular-builders/issues/1101#issuecomment-1019559724) some research with `custom-webpack` builder and either I'm missing something or `@angular-devkit/architect` is not fully compatible with ESM:
> 
> ```
> An unhandled exception occurred: Must use import to load ES Module: /Users/jeb/angular-builders/packages/custom-webpack/dist/browser/index.js
> require() of ES modules is not supported.
> require() of /Users/jeb/angular-builders/packages/custom-webpack/dist/browser/index.js from /Users/jeb/angular-builders/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
> Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/jeb/angular-builders/packages/custom-webpack/package.json.
> ```

check [this pull request](https://github.com/angular/angular-cli/pull/22553)

**Comment by thanhbinhtran93** [comment]
I had a similar error. For me the package was old `"@angular-devkit/build-angular": "^0.901.15"`. Update to newest version `v13.1.4` fixed the error
