### ISSUE TITLE
ngModel for contenteditable - html entities bug

### ISSUE THREAD

**Issue by fronterweb** [angular/angular#4383]
As in this example: https://docs.angularjs.org/api/ng/type/ngModel.NgModelController#custom-control-example

Try to remove 'Change me!' from input. When caret will move to space between 'change' and 'me' you will notice, that in textarea below content will contain: "Change&nbsp;"

So there're some weird issue with handling html entities.
This is unwanted behaviour. I'd expect "Change " instead of "Change&nbsp;"

**Comment by pkozlowski-opensource** [comment]
Wrong repo, I guess you wanted to open it here: https://github.com/angular/angular.js
This repository is for Angular 2.
