### ISSUE TITLE
Guide for 1.5.0 Beta is Broken

### ISSUE THREAD

**Issue by carlosrymer** [angular/angular#4384]
Just noticed that the guide with the latest release is broken:

https://docs.angularjs.org/guide

There seems to be a module that's not being injected because it's missing.

![error-angular-guide](https://cloud.githubusercontent.com/assets/4654390/10123905/1cb94b10-6514-11e5-9538-88850decc511.png)

**Comment by pkozlowski-opensource** [comment]
Already reported, see: https://github.com/angular/angular.js/issues/12960
