### ISSUE TITLE
routerLink directive does not respect `event.preventDefault()` to prevent navigation

### ISSUE THREAD

**Issue by willydee** [angular/angular#43877]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

This is a follow-up to the unresolved issue in https://github.com/angular/angular/issues/21457.

Detailed information:
* The event is not triggered on the element having the `[routerLink]` attribute, but on a child element (common use case, for triggering menus, pop-ups etc.)
* The event is already handled before reaching the directive, and `preventDefault()` has been called.
* The event **needs to bubble up in the DOM** because a `@HostListener` exists on an ancestor further up in the DOM (also a common use case to implement close handlers for menus, pop-ups etc). `stopPropagation()` cannot be considered a universal option to prevent navigation.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-6gwvrf

### Please provide the exception or error you saw

```true
After clicking on a `Show Price...` button (and closing the alert), undesired navigation occurs.
```

### Please provide the environment you discovered this bug in

```
@angular/router 12.1.5
```

### Anything else?

See also https://github.com/angular/angular/issues/10431

**Comment by atscott** [comment]
This was discussed at length in #21457. The goal of disabling the `routerLink` is to set the input to `null` or `undefined`. This was a change in behavior and landed for the v13 release. `preventDefault` will not be respected.

**Comment by willydee** [comment]
@atscott I am well aware of the discussion in that issue. Please consider the use case described, instead of closing the issue with WONTFIX.

**Comment by atscott** [comment]
@willydee Can you address @jelbourn’s last point with respect to accessibility? Here’s another thread on the issue as well https://stackoverflow.com/questions/62092211/html-validation-why-is-it-not-valid-to-put-an-interactive-element-inside-an-int. In fact, having an anchor inside another anchor isn’t even valid html. 

This feature seems like it would encourage less accessible components. `[routerLink]=“null”` would work in all cases except when the answer to whether the link should be enabled isn’t known until the click actually happens. Is there a use-case for this that doesn’t imply nested interactive elements?

You can also handle this in two other ways: 

1. not using `routerLink` at all and just having your own click handler with `router.navigate`
 2. Forking the `routerLink`  It doesn’t use any private APIs so this is relatively easy to do. Many teams do this internally for various reasons.

**Comment by flash-me** [comment]
> This feature seems like it would encourage less accessible components. 

On top of that is the combination of buttons and anchors, which are separate "interactions" in terms of semantics.
- Anchor for navigation
- Button for actions

By nesting them, and even putting a heading inside of the anchor, a user with a screen reader will be totally confused. 
He won't even realize that it's an anchor which will trigger a navigation. 

**Please don't do things like this**

Results: (Tested with [JAWS](https://www.freedomscientific.com/products/software/jaws/))

https://user-images.githubusercontent.com/5240450/138172126-b7b6321a-2945-4dad-8c1b-e50420340716.mp4

Sound is required

cheers
flash ⚡

**Comment by atscott** [comment]
@hbycr1 Did you update to the v13 rc? This was a breaking change so it had to land in a major version.

**Comment by atscott** [comment]
Closing. After discussions, this isn't something we're going to do.

* The use-case described here ("The event is already handled before reaching the directive") isn't something we want to support or encourage due to the nested interactive controls.
* `stopPropagation` works for disabling the click event for a given nested area.
* `[routerLink]="null"` disables the link (in v13+)
* Forking `RouteLink` or using a `(click)` handler with `router.navigate` is always an option
