### ISSUE TITLE
feat: NgCache Service?

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#4389]
### summary 
it would be great to have a `Cache` service similar to Angular 1. For server-rendering we're able to hook into all `Http` calls made during bootstrap and we can even wait for all calls to be done via `zone.js`. Transferring state to the client should be transparent to the developer at least for the framework. 

### problem
If I have to create my own `Cache` service just for for `Http` that would mean that everyone would have to do the same if they want to transfer state to the client from the server. The developer would also have to hook into the lifecycle of server rendering and provide their own way of relaying it to the client

### current workaround 
At the moment I created a subclass `Http` as `NodeHttp` and introduce a `Cache` service where I'm able to serialize the responses when I rendering the `index.html`. On the client I'm then preloading the Cache so the `Http` calls will hit the cache and avoid another trip to the server.

### background/why
In other ecosystems they don't have the luxury of di which means they're forced to create Universal Modules at the IO level (file swap rather than class swap, e.g. [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch)). For Angular 2 there's a huge benefit of converting only one class into another environment since we depend on interfaces not concrete types. We do this for testing but we also end up with a huge benefit when dealing with Universal Code.  For example, the server version of `Http` only requires one line change `bind(BrowserXhr).toClass(NodeXhr)` assuming you create `NodeXhr` and import `xhr2`. (Keep in mind the di env swap is an awesome feature that no other framework can touch at the moment since they don't use a di framework)

#### proposal
introduce Cache service or a better Cache factory for namespacing similar to Angular 1
```typescript
abstract class Cache {
  abstract has(key: string): boolean;
  abstract get(key: string): any; // most likely not strings
  abstract set(key: string, value: any): void; // return the item that was set
  abstract toJSON(): {[key: string]: any};
  abstract serialize(): string;
}


class InMemory extends Cache {}
// class Redis extends Cache {}
// class LocalStorage extends Cache {}

const CACHE_PROVIDERS = [
  {provide: Cache, useClass: InMemory}
//   {provide: Cache, useClass: Redis}
//   {provide: Cache, useClass: LocalStorage}
]
```

**Comment by ericmdantas** [comment]
Would it be part of the main module or a separated one?

**Comment by gdi2290** [comment]
Hopefully a main module. The idea is that someone can use the `Cache` service in their 3rd party module then I can transfer the data to the client for server rendering e.g. `Http`. At the moment I'm relying on my own implementation of `Http` with a cache that I bind to on the server.  Someone can use their own prefered ajax service as well as bind it to the `Http` token. Since the framework is coupled by interfaces I much rather hook into the `Cache` service rather than relying on my `Http` implementation with a in-memory cache. 

This is what facebook/Relay (framework using react) does server-rendering. With Angular 2 we only need to rely on zone.js, di, and hopefully a `Cache` service otherwise `Http`. This is only for the lowest stage of data transfer to the client since you would optimise by doing same method as Relay (statically declaring the queries/requests on each component then walking the component tree to build with a query to make a batch call then transfer the cache with queries/requests to the client).  Having `Cache` provides a better server rendering story with `FalcorJS` (a universal Data Model similar to Relay) which would be the next stage of data transfer for Angular 2

**Comment by TiagoBraga39** [comment]
:+1: I like this. Also would drop my custom cache, which is nice :)

**Comment by mhevery** [comment]
supported through `CachedXHR`

**Comment by m98** [comment]
@mhevery, excuse me, I could not find anything related to `CachedXHR` on the documents. Could you please provide a link about how we can use `CachedXHR`?
Thanks

**Comment by gdi2290** [comment]
@m98 this is later changed to https interceptors and creating your own cache system

**Comment by m98** [comment]
@gdi2290, Could not you use http interceptors to share variables between server and client side?

I think your issue here is related to caching and serving data between browser and server which was a problem, but it seems that [this pull request](https://github.com/angular/angular/pull/19134) is going to solve this problem.

**Comment by Toxicable** [comment]
@m98 The TransferStore API isn't exactly this, it's the backing API.
An interceptor will be provided in a follow up PR to TransferStore to handle it however

**Comment by m98** [comment]
But still, there is not TransferStore functionality from the platform-server itself. am I right?
Maybe there should be something that developers can handle those things. 

In my case, I just need to store data from server-side and receive those data from client-side to make that flicker smother (making another HTTP request and assigning new values to variables takes some times)

**Comment by Toxicable** [comment]
@m98 TransferStore is the core API that allows for sharing data between Server and client.
As part of the TransferStore implementation there will also be a interceptor built that you can use to automate caching Http request from server to client.
Both of these will live under `paltform-server`

**Comment by m98** [comment]
I thought you meant already there is TransferStore on the Angular core, but they will implement it.
For now, what do you mean from `TransferStore`?
Because I could not find something related to TransferStore on Angular docs, or source code

**Comment by Toxicable** [comment]
`TransferStore` is the API being introduced in the PR you linked
https://github.com/angular/angular/pull/19134/files#diff-7245bb1112dbfca39c7a58794176bcb3R40

**Comment by gdi2290** [comment]
here's the design doc
https://docs.google.com/document/d/1Hv3VTRQC0H5yPe8ivJXaGst93yRAtD6nEFkQDLiK_IU/edit#
