### ISSUE TITLE
Angular 12 does not compile using latest TypeScript 4.4.4 (it requires >=4.2.3 and <4.4.0)

### ISSUE THREAD

**Issue by somehan** [angular/angular#43897]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Running 
`ng build` 
errors out with 
`An unhandled exception occurred: The Angular Compiler requires TypeScript  but 4.4.2 was found instead.`

### Please provide a link to a minimal reproduction of the bug

https://github.com/somehan/angular12-typescript4.4.4

### Please provide the exception or error you saw

```true
`An unhandled exception occurred: The Angular Compiler requires TypeScript  but 4.4.2 was found instead.`
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.5
Node: 14.18.1
Package Manager: npm 6.14.15
OS: linux x64

Angular: 12.2.5
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.5
@angular-devkit/build-angular   12.2.5
@angular-devkit/core            12.2.5
@angular-devkit/schematics      12.2.5
@schematics/angular             12.2.5
rxjs                            6.6.7
typescript                      4.4.4
webpack                         5.52.1
```

**Comment by JoostK** [comment]
This is expected; Angular 12 only support TS4.2 and 4.3. Support for TS4.4 has been added in Angular 13 which is currently in prerelease.

If you want to try Angular 12 with TS4.4 you'd have to opt in to disabling the error using the `disableTypeScriptVersionCheck` compiler option. You'd have to add it to a tsconfig.json file in your repo:

```json
{
  // ...
  "angularCompilerOptions": {
    "disableTypeScriptVersionCheck": true
  }
  // ...
}
```

**Comment by somehan** [comment]
Thanks for the quick and comprehensive answer!
