### ISSUE TITLE
docs: unused link in i18n docs

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#43903]
The `AioApiCoreLocaleId` link is not used in these docs:

* https://github.com/angular/angular/blob/master/aio/content/guide/i18n-common-locale-id.md?plain=1#L68
* https://github.com/angular/angular/blob/master/aio/content/guide/i18n-optional-overview.md?plain=1#L47

**Comment by josmar-crwdstffng** [comment]
The changes were merged to primary branch.
