### ISSUE TITLE
docs: overriding LOCALE_ID in CurrencyPipe

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#43902]
### Description

In the current i18n docs that describes locale specific formatting, there is a box after the example:

> NOTE: The language and locale you set for LOCALE_ID token is ignored for the CurrencyPipe.

In retrospect (after the original review of this), I think this is misleading, since it could be inferred that the LOCALE_ID is "always" ignored by the CurrencyPipe. This is not the case. What is actually happening here is that the locale provided as a parameter to the pipe is overriding the default LOCALE_ID, "in this case" only.

### What is the affected URL?

(https://angular.io/guide/i18n-common-format-data-locale#override-current-locale-for-currencypipe)

**Comment by petebacondarwin** [comment]
Sounds good. I get a bit confused by "language and locale" since it feels like it is two separate things, where the CurrencyPipe only has a `locale` parameter, not a `language` parameter. So perhaps we could also drop the "language and" words?

**Comment by josmar-crwdstffng** [comment]
The changes were merged to primary branch.
