### ISSUE TITLE
How can I use an observable / watch?

### ISSUE THREAD

**Issue by danicomas** [angular/angular#4393]
I am trying to do something like this:

```js
this.variable = "d";
ObservableWrapper.subscribe(this.variable, (value) => { console.log(value + " changed"); });
this.variable = "d1";
```

is it correct? this.variable is not an EventEmitter.

**Comment by gdi2290** [comment]
you can create a component where you're able to hook into the `onChange` lifecycle hook for when the bindings change

**Comment by danicomas** [comment]
Sorry @gdi2290 @vicb could you do some plunker example?

**Comment by gdi2290** [comment]
@danicomas here's one
http://plnkr.co/edit/HfdjvOxGcP0FuAsVeD71?p=preview

**Comment by vicb** [comment]
@danicomas in the future, please use the [gitter channel](https://gitter.im/angular/angular) for support request, thanks. GH should be used to report bugs only.

**Comment by danicomas** [comment]
Thanks @gdi2290 but is it only possible statically via template and directives? I would like to do it dinamically.

**Comment by danicomas** [comment]
Opened a new issue. It is not solved with variables:
https://github.com/angular/angular/issues/4576
