### ISSUE TITLE
Angular Light

### ISSUE THREAD

**Issue by tamtakoe** [angular/angular#43939]
### Description

This is PR/marketing feature. Maybe it is incorrect place. Sorry for this.

Position of Angular around JS frameworks is lower and lower. No vacancies and companies don't chose Angular because of no specialists. Vicious circle. Angular trend is falling down. Developers prefer React or Vue. They think that Angular is so difficult. Of course it is not true and they will have lots of problem with bad architecture, bad components and bugs but nevertheless they afraid of Angular and they are right.

I see community hard working, but no one will be able to appreciate it very soon. You have to break this negative trend and I can see how to do it. You should release the Angular Light (or you can use any other name).

What is Angular Light? It is nothing. Just separate section of documentation, blog posts and marketing noise. It should be presented as very small, fast and easy to learn. Version of Angular for juniors.

It is special customised Angular with template-driven form (ngIf, ngFor, ngModel should work out of the the box), with Promise oriented HttpModule (RxJS is too difficult for many developers), without Router (it should be by default in full version), etc.

Documentation of Angular Light should be shorter, but contains more examples. Lets kick Workers, SS rendering/prerendering, Dynamic components, Directives, Guards, Injection tokens, Lazy loading etc. You should drop out 80% features and show how to make any project without deep diving. Don't encourage people to create difficult directives by Angular (the easiest way is to wrap JS-component), create services and use DI (Stupid ES6-import is the best way for many cases if you don't write tests). Translate Angular Light documentation into multiple languages.

And of course add some spice. E.g. you can say that Angular Light don't use (or use 10%) of core code inside the build (smth like Svelte). Or something else that no one understands, but everyone thinks it's cool.

Angular is perceived as a huge and difficult monolith. You can make Angular faster or lighter or polish documentation but it doesn't help you because of developers who chose Vue or React don't try Angular at all. I see only way - rebrending or separate brand. Something light and fashion. And let the old Angular be under the hood, no one will dig so deep.

### Proposed solution

Make separate fake version of Angular for juniors

### Alternatives considered

Carry on the old way and become one more ExtJS

**Comment by antoinebrault** [comment]
> According Template-driven and Reactive forms. The only thing that developers should know is you can rewrite TD-form in Reactive form in couple of days. It is easy. I start any project with TD-forms, because it simple and stupid and 80% of projects don't need something else. If I see page became more interactive I rewrite it in Reactive form, Redux etc. The killer feature of Angular is you can do simple thing by simple way but any time you can add advance layer without using other framework and headache, because Angular has all instruments which you need. Unfortunately Angular team don't explain this way to developers

That's the problem. People have different opinions and it's hard for new devs to get on board.

I've been working with Angular for the past 4 years. TD forms are the way to go for me. I would never go back to reactive forms. Personally, I wish they would've stick with TD forms like Angular 1 and show people how to use Reactive programming on those controls (you can still export ngModel/ngForm and listen to valueChanges/statusChanges).

There are so many difficult things to do with reactive forms like dynamic form fields (hidden by ngIf or inside sub components), 
dynamic validators (like comparing one field to another or simply having a validator enabled based on a condition), typing inexistant, adding/removing controls in an array, etc.

That video is spot on https://www.youtube.com/watch?v=L7rGogdfe2Q

Just imagine a new dev trying to do Reactive forms. It's really hard and the documentation keeps mentionning Reactive forms has the preferred way https://angular.io/guide/forms-overview

**Comment by alxhub** [comment]
I'm going to close this as discussion seems to have come to a stop over a year ago, and in general the original issue isn't specific and actionable for us.

However, our thinking on the team is very much along these same lines - we're working to dramatically simplify the experience for new developers (via efforts like standalone components, etc), to reduce boilerplate, etc.
