### ISSUE TITLE
Documentation for angular animation asterisk token for height and width might be wrong

### ISSUE THREAD

**Issue by nemanjagVtool** [angular/angular#43952]
### Description

On the link explaining "style" function for angular animations, asterisk is explained to compute/take value of parent height and animate to it:

"The following example uses auto-styling to allow a component to animate from a height of 0 up to the height of the parent element:"

I think it computes/takes children's height and uses that value.

### What is the affected URL?

https://angular.io/api/animations/style

### Please provide a screenshot if possible

![Screen Shot 2021-10-26 at 2 06 30 PM](https://user-images.githubusercontent.com/72609369/138874758-03664f5c-9212-49eb-84f6-6db18ee279fd.png)

**Comment by dario-piotrowicz** [comment]
I agree that it does not look right, the wildcard definitely uses the element's styles

as it is for example written in the docs:
[![Screenshot at 2021-10-30 20-31-12](https://user-images.githubusercontent.com/61631103/139556385-89dcc834-9018-4b7d-a115-d0e29f911f36.png)](https://angular.io/guide/transition-and-triggers#boolean-values-in-transitions)

The change was introduced in PR #23682 and you can also see that the original text did state that the value is taken from the element being animated:
![Screenshot at 2021-10-30 20-46-18](https://user-images.githubusercontent.com/61631103/139556628-f80efa8f-3ac5-4d74-95fe-1bb5d93897e1.png)

I imagine that the committer with "the parent element" could have meant something like "the element housing the animation", implying that the element is the parent of the animation... so it may actually be somewhat correct... but definitely not the best way to put it and it is pretty misleading in my opinion

So @nemanjagVtool I think your comment is valid and if I were you I'd feel free to open a PR with whatever text you think would be most appropriate there :slightly_smiling_face: 
(PS: I would forget about parents and children as that is not helping here)

(PS: if you are not interested in actually making the change and open the PR please let me know and I'll be happy to do that, as I do believe you have a point here :slightly_smiling_face::+1: )

**Comment by dario-piotrowicz** [comment]
@nemanjagVtool since I didn't hear from you in ~ 2 weeks I just went ahead and created the PR to improve the text, I hope that's fine :slightly_smiling_face:
