### ISSUE TITLE
DI doesn't work Angular 13

### ISSUE THREAD

**Issue by SamShekhovtsov** [angular/angular#43988]
### Which @angular/* package(s) are the source of the bug?

common, core

### Is this a regression?

No

### Description

I have a very weird situation. When followed exactly to the official Angular documentation I got error in the application. The app crashes and Dependency Injection doesn't work as it should [https://angular.io/tutorial/toh-pt4](https://angular.io/tutorial/toh-pt4)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/angular/mamnmyrnvam

### Please provide the exception or error you saw

```true
This constructor is not compatible with Angular Dependency Injection because its dependency at index 0 of the parameter list is invalid.
    This can happen if the dependency type is a primitive like a string or if an ancestor of this class is missing an Angular decorator.
​
    Please check that 1) the type for the parameter at index 0 is correct and 2) the correct Angular decorators are defined for this class and its ancestors.
```

### Please provide the environment you discovered this bug in

```true
Angular: 13.0.0-rc.2
Angular CLI: 13.0.0-rc.2
Node: 16.12.0
Package Manager: yarn 1.22.15
OS: linux x64

@angular-devkit/architect       0.1300.0-rc.2
@angular-devkit/build-angular   13.0.0-rc.2
@angular-devkit/core            13.0.0-rc.2
@angular-devkit/schematics      13.0.0-rc.2
@schematics/angular             13.0.0-rc.2
rxjs                            7.4.0
typescript                      4.4.4
webpack                         5.60.0
```

### Anything else?

probably this happens due to the webpack integration.

**Comment by AndrewKushnir** [comment]
@SamShekhovtsov I've just looked at the Stackblitz link that you shared and it looks like v12 is used there and everything works as expected (I don't see any errors). Could you please let us know if the problem still exists and if so, how can we reproduce it? Thank you.

**Comment by SamShekhovtsov** [comment]
@AndrewKushnir after creating a clean project at the Stackblitz I confirm that it is working as expected. [https://stackblitz.com/edit/angular-ivy-rc7vm1](https://stackblitz.com/edit/angular-ivy-rc7vm1) . There are something wrong with webpack setup or ts configuration that I've done. We can close this ticket I think.
