### ISSUE TITLE
Using key-value pair is much less confusing than property-value pair

### ISSUE THREAD

**Issue by pstricks-fans** [angular/angular#43995]
### Description

In Angular the terms **attributes** and **properties** are very special. Reusing **properties** to refer to **keys** (in CSS key-value pairs) can cause confusion. That is why I suggest to change them as follows. 

In the following screenshot, we are talking about style attribute binding. The term **style property** is potentially ambiguous (at least for me as a newbie). 

![key](https://user-images.githubusercontent.com/50270635/139555664-34754b93-4fbc-4b37-a981-dd5790d7767b.png)

### What is the affected URL?

https://angular.io/guide/attribute-binding#class-binding

**Comment by bampakoa** [comment]
MDN docs refer to individual style properties as *CSS properties*, e.g. https://developer.mozilla.org/en-US/docs/Web/CSS/background-color

So maybe changing it to **CSS property** would be more appropriate and would convey the true meaning in this context.

**Comment by dario-piotrowicz** [comment]
Totally agree with @bampakoa never heard of anyone calling them keys...

For examples, if you google "css properties" you get lots of css results, if you google "css keys" you get a small number of results which are totally unrelated to cascading style sheets

Also every site/resource refers to them as properties, often in the definition of a css rule itself, as for example css tricks (just to name something different from MDN):
[![css-ruleset-terminology](https://user-images.githubusercontent.com/61631103/139943541-ef8444ba-6cb8-4273-aa44-ae716f7c79a8.png)](https://css-tricks.com/css-ruleset-terminology/)

so honestly if I would see somewhere the term key, I think I would just get very confused :confused:
