### ISSUE TITLE
HttpClient doesn't honor multiple key / value pairs in HttpParams

### ISSUE THREAD

**Issue by bjornharvold** [angular/angular#43999]
### Which @angular/* package(s) are the source of the bug?

common/http

### Is this a regression?

Yes

### Description

HttpClient get() only adds the last param (urlName) to the url. Don't know when this started happening but it has definitely been working before.

```
@Injectable({providedIn: 'root'})
export class PropertyUrlNameService {
  isUrlNameAvailable(propertyIdentifier: string, urlName: string): Observable<UniqueResult> {
   
    const params = new HttpParams()
    .set('propertyIdentifier', propertyIdentifier)
    .set('urlName', urlName)
    ;

    return this.httpClient.get<UniqueResult>(`${this.environment.baseURL}/api/property/urlname`, { params });
  }

  constructor(private readonly httpClient: HttpClient,
              @Inject(ENVIRONMENT) private readonly environment: any) {
  }
}
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.12
Angular: 12.2.12
Node : 12.22.7
OS   : darwin x64
yarn : 1.22.17
```

**Comment by JoostK** [comment]
This does not reproduce for me [in a simple StackBlitz](https://stackblitz.com/edit/node-ytge5c?file=test%2Fsrc%2Fapp%2Fapp.component.ts) (look in the network tab of Web Inspector to see the correct URL being requested).

**Comment by bjornharvold** [comment]
Closing this issue. It has nothing to do with angular/router. It's another http caching plugin that is causing this.
