### ISSUE TITLE
ng update issue handling routerLink without a value

### ISSUE THREAD

**Issue by Brocco** [angular/angular#44005]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Unsure, the code being updated is no longer valid.

### Description

running `ng update @angular/cli --next --force` against an v12 app that contains `[routerLink]` with no value.

the expected output would be `[routerLink]="[]"` with the update conversion/migration.

## 🔬 Minimal Reproduction

I have no shareable v12 applications.

## 🔥 Exception or Error

no exceptions are thrown, but the converted code goes from the above to this in one instance:

```
[routerLink]="[]"="[]"="[]"="[]"="[]"="[]"
```

and this in another instance (in the same file):

```
="[]"<a
  ="[]"     ="[]"   [r="[]"outer="[]"Link]="[]"
```

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.0.0-rc.2
Node: 14.18.1
Package Manager: npm 6.14.15
OS: linux x64

Angular: 13.0.0-rc.2
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.1
@angular-devkit/build-angular   13.0.0-rc.2
@angular-devkit/core            12.1.4
@angular-devkit/schematics      12.2.12
@angular/cdk                    12.2.1
@angular/google-maps            12.2.1
@schematics/angular             12.2.12
ng-packagr                      12.2.5
rxjs                            7.4.0
typescript                      4.4.4

</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
This migration was recently updated in https://github.com/angular/angular/pull/43519.

I note in the specs for this migration we do not test the case of `<a [routerLink]>` with no value at all.

**Comment by petebacondarwin** [comment]
Actually there is a test case for an input binding with no value: 

https://github.com/angular/angular/blob/77bd2538cb8fe114a326209791d7ec043d65ea9e/packages/core/schematics/test/routerlink_empty_expr_migration_spec.ts#L122

**Comment by petebacondarwin** [comment]
OK - we talked off line and it looks like it might be more newline woes. The test case looks like:

```html
    <div>
      <some-comp
        [routerLink]
        [otherInput]="expression"
      ></some-comp>
    </div>
```

**Comment by JoostK** [comment]
We may need to configure the parser used in schematics to handle whitespace using the same options as is done for template diagnostic reporting. i.e. here:

https://github.com/angular/angular/blob/a07cb097e9124738880f7978658a2972d25b892e/packages/core/schematics/utils/parse_html.ts

may need some of these options:

https://github.com/angular/angular/blob/d015ac214f4e372607403e6e93c48f8a2b5014f9/packages/compiler-cli/src/ngtsc/annotations/src/component.ts#L1235-L1260

**Comment by petebacondarwin** [comment]
Yeah I think it is something like that. I note that I think that it is only a problem with CRLF combinations...
