### ISSUE TITLE
Platform-browser animation engine possible inaccurate "parentNode" behavior.

### ISSUE THREAD

**Issue by raman-savitski** [angular/angular#44023]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

No

### Description

https://github.com/angular/angular/blob/fd1e7d4f0d73df42422caa056957aeaad2944a4a/packages/platform-browser/animations/src/animation_renderer.ts#L37-L39

Isn't it should be: `delegate.removeChild(delegate.parentNode(element), element); `

I'm creating custom renderer using Renderer2 and expecting that `removeChild` will be called on my custom `delegate.parentNode(...)` not the actual `element.parentNode`.

**Comment by JoostK** [comment]
Sounds reasonable to store `delegate?.parentNode(element)` in a variable and pass that to `removeChild`; feel free to create a PR with that change.
