### ISSUE TITLE
Angular 13: document config changes necessary when using @ngtools/webpack

### ISSUE THREAD

**Issue by vanackere** [angular/angular#44026]
Hi,

When trying to update my angular app built using @ngtools/webpack from angular 12 to the upcoming angular 13, I get the following error at runtime:

```
JIT compilation failed for injectable 
class PlatformLocation {}
core.mjs:4060
Uncaught Error: The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.

The injectable is part of a library that has been partially compiled.
However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.

Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
    Angular 3
    Webpack 9
core.mjs:4079
```

The same project works fine when built with angular 12.x (with no other change than a minor adjustment in webpack.config.mjs) so it looks like a regression.

I made a minimal self-contained repository to reproduce the issue at https://github.com/vanackere/ngtools-webpack-bug

To reproduce, simply run `npm run dev` then `npm run serve`

Thanks by advance for looking at this !

**Comment by jpike88** [comment]
I use fusebox, not web pack. To be compatible with Angular 12, I ran this on post install, and things worked fine:

```ngcc --properties es2015 es5 browser module main --first-only --create-ivy-entry-points```

However I get this error with Angular 13, even after using ngcc. A webpack babel-loader recommendation doesn't apply to me, and never did. Can you explain this breaking change a little better for those in my situation?

**Comment by petebacondarwin** [comment]
@jpike88 - the linker is just a Babel plugin that can be added at an appropriate point in your build pipeline. See https://angular.io/guide/creating-libraries#consuming-partial-ivy-code-outside-the-angular-cli and https://github.com/angular/angular/tree/master/packages/compiler-cli/linker/babel.

**Comment by JonWallsten** [comment]
@petebacondarwin / @joostK: I have a follow up question. We build an internal lib with `ng-packagr` that we then consume in our app.
I get the same error message as above. What do I have to do to make our lib "fully AOT compiled"? 
We don't use Babel.

**Comment by petebacondarwin** [comment]
I believe that you should be able to set the `compilationMode` setting in the tsconfig.json to `full`.
@alan-agius4 - does ng-packagr override this? I don't think so...

**Comment by JonWallsten** [comment]
Can it be something in the application itself and not the lib?
Let me start by deleting my node_modules in case something wasn't properly updated. Has happened with Angular updates before.
I don't have to run `ngcc --properties es2015 es5 browser module main --first-only --create-ivy-entry-points` anymore?

**Comment by petebacondarwin** [comment]
Hi @JonWallsten

No, you have to configure it at the library, since this is what is being compiled into a format (either partial or full).
If it is compiled to partial then the application (the consumer of the library) must run the linker (one way or another).
If it is compiled to full then the library and the application must be on exactly the same patch version of Angular.

**Comment by JonWallsten** [comment]
Thanks! It's a monorepo, so they should always be the exact same verson.

**Comment by JonWallsten** [comment]
@petebacondarwin: 
```
| ------------------------------------------------------------------------------
 | - Compiling with Angular sources in Ivy full compilation mode.
 | Another process, with id 47240, is currently running ngcc.
 | Waiting up to 250s for it to finish.
 | (If you are sure no ngcc process is running then you should delete the lock-file at C:/Users/jway52/repo/oas-web/node_modules/@angular/compiler-cli/bundles/ngcc/__ngcc_lock_file__.)
 | Another process, with id 32640, is currently running ngcc.
 | Waiting up to 250s for it to finish.
 | (If you are sure no ngcc process is running then you should delete the lock-file at C:/Users/jway52/repo/oas-web/node_modules/@angular/compiler-cli/bundles/ngcc/__ngcc_lock_file__.)
 | Another process, with id 39992, is currently running ngcc.
 | Waiting up to 250s for it to finish.
 | (If you are sure no ngcc process is running then you should delete the lock-file at C:/Users/jway52/repo/oas-web/node_modules/@angular/compiler-cli/bundles/ngcc/__ngcc_lock_file__.)
 | ✔ Compiling with Angular sources in **Ivy full compilation mode**.
 | - Generating FESM2020
 | ✔ Generating FESM2020
 | - Generating FESM2015
```

**Comment by alan-agius4** [comment]
> I believe that you should be able to set the `compilationMode` setting in the tsconfig.json to `full`.
@alan-agius4 - does ng-packagr override this? I don't think so...

It does not, with ng-packagr, you can generate both partial and full Ivy compilations. This is actually what is also done when using the Angular CLi.

**Comment by petebacondarwin** [comment]
Can you look at the output of building the library and determine whether it contains full or partially compiled code?
(Full will have things like `ɵɵdefineDirective` whereas partial will have `ɵɵngDeclareDirective`.)

Secondly, can you confirm that your setup does not accidentally contain more than one copy of Angular? Perhaps in a nested dependency?

**Comment by petebacondarwin** [comment]
> @JonWallsten, in your case\ however, you still need to use Babel, that is unless you are using the Angular CLI to build your library, since packages which are shipped to the public NPM repository like @angular/are not in Ivy full compilation mode.

Ahah! Yes. Of course. This is not about your library. It is about the Angular ones. They are in partial mode. So you do still need to link those ones, whether or not your own libraries are in partial mode.

**Comment by JonWallsten** [comment]
Ah, then I'm with you guys! Thanks!
Is there a minimum setup for Babel where I add as few deps as possible to make this happen?

**Comment by alan-agius4** [comment]
@JonWallsten, I am assuming you are using Webpack to build your application. In which case all you need is to install `babel-loader`. See: https://angular.io/guide/creating-libraries#consuming-partial-ivy-code-outside-the-angular-cli

**Comment by JonWallsten** [comment]
@alan-agius4: Perfect! Thanks! Should I add ES2020 as a mainField in my webpack conf?
Current values are: `mainFields: ['es2015', 'browser', 'module', 'main']`

I added the babel-loader and end up with this:
```
[webpack-cli] Failed to load 'C:\Users\meee\repo\oas-web\packages\web-app-edit\config\webpack.dev.ts' config
[webpack-cli] TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for C:\Users\meee\repo\oas-web\packages\web-app-edit\config\webpack.dev.ts
    at new NodeError (internal/errors.js:322:7)
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at async Loader.import (internal/modules/esm/loader.js:177:17)
    at async WebpackCLI.tryRequireThenImport (C:\Users\meee\repo\oas-web\node_modules\webpack-cli\lib\webpack-cli.js:254:18)       
    at async loadConfigByPath (C:\Users\meee\repo\oas-web\node_modules\webpack-cli\lib\webpack-cli.js:1710:19)
    at async Promise.all (index 0)
    at async WebpackCLI.loadConfig (C:\Users\meee\repo\oas-web\node_modules\webpack-cli\lib\webpack-cli.js:1763:29)
    at async WebpackCLI.createCompiler (C:\Users\meee\repo\oas-web\node_modules\webpack-cli\lib\webpack-cli.js:2185:18) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

Seems like the Webpack/ts-node setup does not work as soon as some package with `type: "module"` is involved.

**Comment by alan-agius4** [comment]
@JonWallsten, you can copy https://github.com/angular/angular-cli/blob/be32c9aa34761f7ee5f6c7eafd8872e76350061d/packages/angular_devkit/build_angular/src/webpack/configs/common.ts#L322-L325

**Comment by JonWallsten** [comment]
@alan-agius4 
> I am not quite sure of your build setup and Webpack configurations, maybe you are targeting CJS as the TypeScript module?

Here's my setup. 
All applications and libraries use them same settings:
```
{
  "compilerOptions": {
    "rootDir": ".",
    "baseUrl": ".",
    "target": "ES2020",
    "module": "CommonJS",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "alwaysStrict": true,
    "preserveConstEnums": true,
    "downlevelIteration": true,
    "strictNullChecks": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "strictFunctionTypes": true,
    "strictBindCallApply": true,
    "noImplicitOverride": true,
    "lib": [
        "dom",
        "es2015",
        "es2017.object",
        "es2016.array.include",
        "es2017.string",
        "es2018.promise",
        "es2019.string"
    ],
    "paths": {
      "@project/web-lib-core": ["./packages/web-lib-core/dist"],
      "@project/web-lib-common": ["./packages/web-lib-common/dist"],
      "@project/web-lib-angular": ["./packages/web-lib-angular/dist"],
      "@project/internal-lib-e2e": ["./packages/internal-lib-e2e/dist"]
    }
  },
  "include": [
    "./build-tools/"
  ],
  "compileOnSave": false,
  "buildOnSave": false
}
```

**Comment by JonWallsten** [comment]
Seems to be answered here:
https://github.com/webpack/webpack-cli/issues/2458#issuecomment-811448600

**Comment by JonWallsten** [comment]
@alan-agius4: Wow, that was a rabbit hole if I ever been in one. So many different errors, node options, versions, targets, modules. Still haven't succeeded. 

I found this:
https://github.com/TypeStrong/ts-node/discussions/1290

It at least allows me to import the babel-loader linkerPlugin.
But I get this error now:
```
ERROR in ../../node_modules/@fortawesome/angular-fontawesome/fesm2020/angular-fontawesome.mjs
Module build failed (from ../../node_modules/babel-loader/lib/index.js):
Error: .plugins[0] must be a string, object, function
    at assertPluginTarget (C:\Users\mmmmmme\repo\oas-web\node_modules\@babel\core\lib\config\validation\option-assertions.js:278:11)  
    at assertPluginItem (C:\Users\mmmmmme\repo\oas-web\node_modules\@babel\core\lib\config\validation\option-assertions.js:270:5)     
    at C:\Users\mmmmmme\repo\oas-web\node_modules\@babel\core\lib\config\validation\option-assertions.js:236:30
    at Array.forEach (<anonymous>)
    at assertPluginList (C:\Users\mmmmmme\repo\oas-web\node_modules\@babel\core\lib\config\validation\option-assertions.js:236:9)     
    at C:\Users\mmmmmme\repo\oas-web\node_modules\@babel\core\lib\config\validation\options.js:118:5
    at Array.forEach (<anonymous>)
    at validateNested (C:\Users\mmmmmme\repo\oas-web\node_modules\@babel\core\lib\config\validation\options.js:94:21)
    at validate (C:\Users\mmmmmme\repo\oas-web\node_modules\@babel\core\lib\config\validation\options.js:85:10)
    at loadPrivatePartialConfig (C:\Users\mmmmmme\repo\oas-web\node_modules\@babel\core\lib\config\partial.js:80:50)
```

**Comment by JonWallsten** [comment]
@alan-agius4: Will this affect unit testing with Jest as well?
```
Cannot find module '@angular/core/testing' from 'config/jest.setup.ts'

      18 | import 'jest-zone-patch';
      19 |
    > 20 | import { getTestBed } from '@angular/core/testing';
         | ^
      21 | import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing';   
      22 |
      23 | getTestBed().initTestEnvironment(

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (config/jest.setup.ts:20:1)
```

**Comment by alan-agius4** [comment]
@JonWallsten, no since for testing JIT is used. That said, there are a number of changes that need to be done for Jest to work properly with version 13. This is because Jest has its' own module resolution strategy and very limited support to ES modules.

See: https://thymikee.github.io/jest-preset-angular/docs/guides/angular-13+ for more information about using Jest with Angular.

**Comment by JonWallsten** [comment]
@alan-agius4: Ah, I see! Thanks. I've tried using the upgrade guide but it didn't work for us. Now at least I know where to put my focus.

**Comment by JonWallsten** [comment]
@alan-agius4: So I kind of got it to work. It no longers complains about any `@angular` related imports.
But it does complain about our internal lib built with `ng-packagr`. Same error message: 
```
Test suite failed to run

    Cannot find module '@oas/web-lib-angular' from 'src/app/common/services/schedule.service.ts'

    Require stack:
      src/app/common/services/schedule.service.ts
      src/app/common/services/schedule.service.unit-spec.ts

      1 | import { Injectable } from '@angular/core';
    > 2 | import { nextTickAwait } from '@oas/web-lib-angular';
```

**Comment by Rush** [comment]
I don't get it. Why do we suddenly have to use Babel when `ngcc` used to work fine? I am getting the error "The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available." and nothing makes any sense. Why would Angular libraries trigger the error? Aren't they supposed to be AOT compatible now?

Switching `ngcc` for Babel would be a REALLY BAD trade as while `ngcc` runs once per node modules installation, babel runs every time.

**Comment by JoostK** [comment]
> I don't get it. Why do we suddenly have to use Babel when `ngcc` used to work fine? I am getting the error "The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available." and nothing makes any sense. Why would Angular libraries trigger the error? Aren't they supposed to be AOT compatible now?

Angular libraries are compiled into _partial compilation output_, which is not yet fully AOT compiled. If the linker is not involved during the final build then there is a fallback available using the JIT compiler, which is likely what you're seeing.

> Switching `ngcc` for Babel would be a REALLY BAD trade as while `ngcc` runs once per node modules installation, babel runs every time.

You may be missing some key points about ngcc and how using Babel does not have these limitations.

First, ngcc mutates the `node_modules` directory to store its built artifacts, which is incompatible with package managers such as pnpm/Yarn PnP.
Secondly, the output of ngcc can hardly be cached. Any changes to the `node_modules` tree would invalidate its output, as there is no clear set of inputs that can be used as cache key (apart from the full lock-file of the `node_modules` installation).
Thirdly, ngcc does not parallelize as effectively as Babel can, as ngcc requires topological sorting of its build tasks.

None of these are issues with the linker approach. The linker is able to process a single input file independently, making parallelization and caching more effective. Granted, you have to configure your Babel plugin integration to actually use caching.

**Comment by Rush** [comment]
I think it makes sense why `babel` seems a better solution than `ngcc`  but in that case why would the build process without `babel` fail for Angular's core libraries and when no external libs are used?

Shouldn't the approach of applying babel to old Angular libs only be sufficient?

```ts
rules: [{
  test: /some-old-angular-lib/\/.*\.m?js$/,
  loader: 'babel-loader',
  options: {
    compact: false,
      plugins: [linkerPlugin.default],
    },
    resolve: {
      fullySpecified: false
  }
}]
```

Also this is kind of a huge change, especially for folks who ship products written using Angular:
- who use `ngcc` in CI
- and those who have rolled out custom webpack scripts and not using angular CLI (my case)
Could such changes be better communicated with the community in the future? And for this specific change, could there be an official migration guide provided?

Thanks again. I just wish to get to the bottom of this. PS. If my tone reads ungrateful, this is not the case. :) I am super grateful for your work. @JoostK

**Comment by Rush** [comment]
Also another point ... couldn't `@ngtools/webpack` just apply a babel transform on the code by itself? It would avoid the need for users of Angular to become Babel experts.

**Comment by JoostK** [comment]
> Shouldn't the approach of applying babel to old Angular libs only be sufficient?

Quite the opposite, actually! The _new_ approach of library distribution uses the linker, which is currently implemented as a Babel transform.

> Could such changes be better communicated with the community in the future? And for this specific change, could there be an official migration guide provided?

I agree that these changes could've been made more explicit in the changelog. As for a migration guide, since we have no knowledge of custom build setups I'm really not sure how we'd provide a _migration_ guide without knowing the state of a project. A basic example was added in [#44027](https://github.com/angular/angular/pull/44027/files), which should get you started. Feel free to open a PR to add a link to this doc from the changelog, it sounds reasonable to me to mention in under breaking changes (strictly speaking, the new setup has been necessary from v12 for the libraries that had already switched to Ivy's distribution format by then)

If you're interested, background information on the design and approach has been discussed in the [Ivy Library Distribution RFC](https://github.com/angular/angular/issues/38366).

**Comment by thw0rted** [comment]
Has anybody gotten this to work without `fullySpecified: false` (in addition to using Babel with the Linker plugin)?  I got errors like

````text
ERROR in ./node_modules/@angular/material/fesm2015/select.mjs 23:0-40
Module not found: Error: Can't resolve '@angular/cdk/bidi' in '...\node_modules\@angular\material\fesm2015'
Did you mean 'bidi.mjs'?
BREAKING CHANGE: The request '@angular/cdk/bidi' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
 @ ./src/app/material.module.ts 21:0-59 41:404-419 41:930-945
 @ ./src/app/app.module.ts 17:0-51 54:227-241
 @ ./src/main.ts 5:0-45 12:54-63
````

until I made sure to set `fullySpecified: true`.

@sokra makes the point in https://github.com/webpack/webpack/issues/11467 that `mjs` files must use fully specified import paths (like `../../cdk/bidi`), instead of legacy Node-style module resolution (e.g. `@angular/cdk/bidi`).  Should the distributed Angular MJS files use relative specifiers, to be "technically correct"?

**Comment by jpike88** [comment]
Can someone point to or explain how on earth this 'babel linker' and 'loader' would be used outside a Webpack example?

**Comment by JoostK** [comment]
> Can someone point to or explain how on earth this 'babel plugin' would be used outside a Webpack example?

That depends entirely on your build pipeline. One of the options is to use [the Babel CLI](https://babeljs.io/docs/en/babel-cli#using-plugins) to process files:

```
babel ... --plugins=@angular/compiler-cli/linker/babel
```

**Comment by johncrim** [comment]
@JoostK  - thank you for the pointer on a way to perform library linking from command-line. I was just going to submit an issue asking the Angular team to provide CLI support for linking.

I think it would be great to add that example to the docs (next to [Consuming partial-Ivy code outside the Angular CLI
](https://angular.io/guide/creating-libraries#consuming-partial-ivy-code-outside-the-angular-cli) ), eg "run this in your postinstall to link @angular/cdk, @angular/common, @angular/router and @angular/forms" if you're not using the angular CLI for building and not using webpack.
