### ISSUE TITLE
Two-Way Binding documentation does not mention getters and setters

### ISSUE THREAD

**Issue by CraigComeOnThisNameCantBeTaken** [angular/angular#44029]
### Description

You can use getters and setters with a single @Input with getters and setters to achieve the same result as with @Output and EventEmitters as below:

```
  private _childItem: any;

  @Input()
  get childItem() {
    return this._childItem;
  }
  set childItem(val) {
    this._childItem = val;
  }

  ngOnInit() {
    this.childItem = 'hello'; // whether I set the private field or the public setter I get the same result
  }
```

Would it be possible to explain why this is a worse approach than EventEmitters please?

### What is the affected URL?

https://angular.io/guide/two-way-binding

**Comment by JoostK** [comment]
I don't understand the question. Your example does not include any `EventEmitter`, could you please clarify the situation?

**Comment by CraigComeOnThisNameCantBeTaken** [comment]
I mean that the code I have written above seems to work in the same way as an event emitter. It still updates the parent component with the new value.

**Comment by JoostK** [comment]
There's ony one component in your example, so I don't see the relation to a parent component.

**Comment by alxhub** [comment]
Closing as not actionable - the example given is not showing any kind of two-way binding.
