### ISSUE TITLE
angular2.d.ts contains ViewFactory twice

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#4403]
```
interface ViewFactory {
```

The content looks the same. There might be more dupes like this. Can someone investigate?

**Comment by jgw96** [comment]
I can take this bug if needed? It will be my first time contributing to Angular (hardcore Mozillian here).

**Comment by IgorMinar** [comment]
Thanks for the offer but we are completely rewamping how the d.ts
generation works and this problem will go away with it. See #3082

**Comment by mhevery** [comment]
no longer generating our own `.d.ts` file. Not applicable.
