### ISSUE TITLE
Links to StackBlitz Examples for testing directives don't compile

### ISSUE THREAD

**Issue by nateClicks** [angular/angular#44047]
### Description

The webpage mentions:

"For a hands-on experience, [run tests and explore the test code](https://angular.io/generated/live-examples/testing/specs.stackblitz.html) in your browser as your read this guide.

If you'd like to experiment with the application that this guide describes, [run it in your browser](https://angular.io/generated/live-examples/testing/stackblitz.html) or download and run it locally."

The StackBlitz that open give the error

```
Error in ~/src/main.ts
ngcc failed to run on jasmine-marbles@0.8.4, tslib@2.1.0, angular-in-memory-web-api@0.11.0, @angular/common@13.0.0, @angular/animations@13.0.0, @angular/core@13.0.0, jasmine-core@3.9.0, @angular/compiler@13.0.0, zone.js@0.11.4, @angular/platform-browser@13.0.0, rxjs@7.4.0, lodash@4.17.21, tslib@2.3.1, @angular/platform-browser-dynamic@13.0.0, @angular/router@13.0.0, @angular/forms@13.0.0.
```

### What is the affected URL?

https://angular.io/guide/testing-attribute-directives

### Please provide the steps to reproduce the issue

1. Go to page [https://angular.io/guide/testing-attribute-directives](https://angular.io/guide/testing-attribute-directives).
2. Click on links in the alert area that take you to the StackBlitz 

- https://angular.io/generated/live-examples/testing/specs.stackblitz.html
- https://angular.io/generated/live-examples/testing/stackblitz.html

3. Observe example not compling

### Please provide the expected behavior vs the actual behavior you encountered

I expected it to compile. It did not.

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/72458025/140200158-644926f1-98b3-4448-b259-1cc2ecd511e6.png)

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
Mac OSX: 11.6
Chrome: Version 95.0.4638.69 (Official Build) (x86_64)
```

**Comment by alxhub** [comment]
This is a known issue with Stackblitz and 13.0.0 format packages. A fix upstream in Stackblitz is in progress, and we're temporarily switching angular.io to use Stackblitz Web Containers for examples (which works around this problem).

**Comment by josephperrott** [comment]
This issue on angular.io has been resolved.

**Comment by petebacondarwin** [comment]
The original issue was resolved but we now have a different issue with a similar result. So I am reopening this while I fix it.
