### ISSUE TITLE
checkForUpdate never resolved in production (13.0.0)

### ISSUE THREAD

**Issue by Enngage** [angular/angular#44044]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

Hey,

I'm trying to determine if new update is available, but for some reason, in following code:

```
    constructor(appRef: ApplicationRef, private swUpdate: SwUpdate) {
        if (this.swUpdate.isEnabled) {
            const appIsStable$ = appRef.isStable.pipe(first((isStable) => isStable === true));
            const intervalObs$ = interval(30* 1000);
            const stableIntervalObs$ = concat(appIsStable$, intervalObs$);
            stableIntervalObs$.subscribe(() => {
                swUpdate.checkForUpdate().then(response => {
                     // This is never hit
                });
            });
        }
    }
``` 

The `swUpdate.checkForUpdate` is never resolved. Strangely, this happens **only in production mode**. It works perfectly fine when tested locally with service worker & HTTP server. It should return true / false depending on whether a new update is available, but it never returns anything. Really no idea why it works like a charm locally, but not on production. (I've tried clearing cache, removing service worker, anonymous window and all the usual stuff)

In network tab I can see that the `ngsw.json?ngsw-cache-bust=0.0010572762505560718` is being hit as expected (every 30 sec in my case), however the timestamp is the same for all requests. 

Can you guys think of any reason the `checkForUpdate` would never resolve on production? Is there something I can test / check? 

### Please provide the environment you discovered this bug in

```true
Angular 13.0.0
```

**Comment by kemsky** [comment]
I can confirm that this happens. The easiest way to reproduce is to hit ctrl+f5. @gkalpak

**Comment by alexkushnarov** [comment]
Same for me.

Also available method never hits for me (was working well in v12)
```
private subscribeOnServiceWorkerUpdate() {
    return this.swUpdate.available.subscribe(() => {
      // This is never hit
      this.swUpdate.activateUpdate()
        .then(() => this.openUpdateAvailablePopup());
    });
  }
```

  available method is deprecated so angular doc provide a new method but it also never hits.
  https://angular.io/api/service-worker/SwUpdate#available
  ```
private subscribeOnServiceWorkerUpdate() {
    return this.swUpdate.versionUpdates.pipe(
        filter((evt: VersionReadyEvent) => evt.type === 'VERSION_READY'),
        map((evt: VersionReadyEvent) => ({
          type: 'UPDATE_AVAILABLE',
          current: evt.currentVersion,
          available: evt.latestVersion,
        }))
      )
      .subscribe(() => {
        // This is never hit
        this.swUpdate.activateUpdate()
          .then(() => this.openUpdateAvailablePopup());
      });
  }
```

**Comment by alexkushnarov** [comment]
@Enngage @kemsky  I was facing the same issue on my angular site v13, also when I updated any code new app version was not installing, then I created a new test angular project from scratch and tested this issue I couldn't reproduce it. 
I looked at the implementation and I found out that in past I customized ngsw-worker.js file and was replacing it with generated one once build is finished, that was causing the issue.
checkForUpdate func from old ngsw-worker.js from v12:
```
checkForUpdate() {
            return __awaiter$5(this, void 0, void 0, function* () {
                let hash = '(unknown)';
                try {
                    const manifest = yield this.fetchLatestManifest(true);
                    ...
```

checkForUpdate func from new v13 ngsw-worker.js:
```
async checkForUpdate() {
            let hash = '(unknown)';
            try {
                const manifest = await this.fetchLatestManifest(true);
                ...
```
See in old ngsw-worker.js it returns __awaiter$5 thats why callback never hit.

If you didn't customize ngsw-worker.js another possible issue that you facing that its using ngsw-worker.js from v12
because it has caching  
Cache-Control: public, max-age=31536000

Try to update your code where you register ServiceWorker with **ngsw-worker.js?version=13**
Example:
from:
```
ServiceWorkerModule.register('ngsw-worker.js'),
```
to
```
ServiceWorkerModule.register('ngsw-worker.js?version=13'),
```

**Comment by kemsky** [comment]
@alexkushnarov, in my case it is clearly not caching. I see that `checkForUpdate` is triggered two times (I guess one of those is some automatic trigger), at least one message is posted back by `ngsw-worker.js`, but `NgswCommChannel` did not receive any events. I assume there is race condtion. I invoke  `checkForUpdate` in the `APP_INITIALIZER`.

**Comment by Enngage** [comment]
I've managed to solve this issue by making sure Angular is in **stable** state. This didn't work because my app was never stable. Once I fixed the underlying issue, everything works like a dream. I feel we can close this issue. 

To learn more about stable state see https://angular.io/api/core/ApplicationRef#isstable-examples-and-caveats
