### ISSUE TITLE
canDeactivate guard has component null

### ISSUE THREAD

**Issue by leocharrua** [angular/angular#44068]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I'm working with Ionic 5 and Angular 12.

In app-routing.module.ts I have this route with the guard:

```
const routes: Routes = [
     ...
     {
    path: 'visita',
    loadChildren: () => import('./pages/visita/visita.module').then( m => m.VisitaPageModule),
    canDeactivate: [CanDeactivateVisitaGuard]
  },
...
];
@NgModule({
  imports: [
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules })
  ],
  exports: [RouterModule]
})
export class AppRoutingModule {}
```

In the guard code:

```
@Injectable({
  providedIn: 'root'
})
export class CanDeactivateVisitaGuard implements CanDeactivate<CanComponentDeactivate> {
  canDeactivate(
    component: CanComponentDeactivate,
    currentRoute: ActivatedRouteSnapshot,
    currentState: RouterStateSnapshot,
    nextState?: RouterStateSnapshot): Observable<boolean | UrlTree> | Promise<boolean | UrlTree> | boolean | UrlTree {

      // Here: component is null ***********
      return component.canDeactivate ? component.canDeactivate() : true;
  }
```

And in the page with the guard:

```
canDeactivate(): Observable<boolean> | Promise<boolean> | boolean {
      // The code here is not relevant ...
}
```

The problem is that marked with the asteriks (*).

How I can get the component in the guard?

Thanks

### Please provide the environment you discovered this bug in

```true
Ionic:

   Ionic CLI                     : 6.17.1 (C:\Users\leoch\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.8.5
   @angular-devkit/build-angular : 12.2.13
   @angular-devkit/schematics    : 12.2.13
   @angular/cli                  : 12.2.13
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.4
   @capacitor/android : not installed
   @capacitor/core    : 3.2.4
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v14.17.5 (C:\Program Files\nodejs\node.exe)
   npm    : 2.15.12
   OS     : Windows 10
```

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template, including a link to a minimal reproduction of the bug

**Comment by leocharrua** [comment]
Hello. 

The issue is clear I think. If you set a canDeactivate guard for a page with a route (app-routing.module.ts) like this:

```
 {
    path: 'visita',
    loadChildren: () => import('./pages/visita/visita.module').then( m => m.VisitaPageModule),
    canDeactivate: [CanDeactivateVisitaGuard]
  },
```

In the guard when you try to access the "component" parameter, it's null (see the asteriks).

I think it happens because I don't set component in the route like this:

```
{
    path: 'visita',
    component: VisitaPage,
    canDeactivate: [CanDeactivateVisitaGuard]
  },
```

But If I do that, I get multiple errors when the page is rendered (I think because I don't set the module)

Here, my question ... What is the best way to get the component in the guard?

Thanks

**Comment by atscott** [comment]
I know that Ionic implements their own router outlet, which controls this behavior. It's entirely possible the issue is in the Ionic outlet rather than Angular. It's also likely this is a duplicate of #27696. Without a reproduction, this investigation cannot be done.

**Comment by leocharrua** [comment]
I found the solution here:

https://ionicthemes.com/tutorials/ionic-navigation-and-routing-ultimate-guide

Basically, this is the way:

1) **app-routing.module.ts**: Nothing to do here. Define the route as always:

```
{
    path: 'page1',
    loadChildren: () => import('./pages/page1/page1.module').then( m => m.Page1PageModule),  
},
``` 
  **Important Note: NOT INCLUDE the guard here**

2) In the page module (**page1.module.ts**):

a) Add the route with path empty string, add component and the guard
b) Comment the imports part with the page routing module:  Page1PageRoutingModule

**page1.module.ts**

```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

import { IonicModule } from '@ionic/angular';

// import { Page1PageRoutingModule } from './page1-routing.module';

import { Page1Page } from './page1.page';

import { RouterModule, Routes } from '@angular/router';
import { CanDeactivateGuard } from 'src/app/guards/can-deactivate.guard';

const routes: Routes = [
  {
    path: '',
    component: Page1Page,
    canDeactivate: [CanDeactivateGuard]
  }
];

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
    // Important: comment the next line 
    // Page1PageRoutingModule
    RouterModule.forChild(routes),
  ],
  declarations: [Page1Page],
  providers: [CanDeactivateGuard]
})
export class Page1PageModule {}
```

c) The guard code not need any change either.

That's all folks ;)
