### ISSUE TITLE
Optional chaining of method calls may generate invalid instructions

### ISSUE THREAD

**Issue by ties-s** [angular/angular#44069]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

When passing a form control value to a function that is end the end of an optional chain, the value is `null`.

Expected (works in v12), console:
`Thu Nov 04 2021 22:42:39 GMT+0100 (CET)  – Thu Nov 04 2021 22:42:39 GMT+0100 (CET)`

Actual in v13:
`Thu Nov 04 2021 22:42:39 GMT+0100 (CET)  – null`

This problem does not occur when using `!` instead of `?` on the form value, or when using the value outside a function that is part of an optional chain.

### Please provide the exception or error you saw

```true
// app.component.ts
import { Component } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';

@Component({
	selector: 'app-root',
	templateUrl: './app.component.html',
	styleUrls: ['./app.component.scss']
})
export class AppComponent {
	form = this.fb.group({
		test: [new Date(), Validators.required]
	})

	constructor(private fb: FormBuilder) {}

	public a?= {
		fn(_: any) {
			return true;
		}
	}

	test(e: any) {
		console.log(this.form.get('test')?.value, e);
	}
}

```
```
// app.component.html
<div [formGroup]="form">
	<button class="show" (click)="a?.fn(test(form.get('test')?.value))">SHOW</button>
</div>
```

### Please provide the environment you discovered this bug in

```
Angular CLI: 13.0.1
Node: 16.11.1
Package Manager: npm 8.1.2
OS: darwin arm64

Angular: 13.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.1
@angular-devkit/build-angular   13.0.1
@angular-devkit/core            13.0.1
@angular-devkit/schematics      13.0.1
@angular/cli                    13.0.1
@schematics/angular             13.0.1
rxjs                            6.6.7
typescript                      4.4.4
```

### Anything else?

Checked exact same sample in latest Angular 12, no problems there.

**Comment by ties-s** [comment]
Repro: https://github.com/ties-s/ng-form-chained-repro

**Comment by petebacondarwin** [comment]
I think that this is indeed a bug in how the Angular expression is being converted to TS in the ivy handler.

The following expression

```ts
a?.fn(test(form.get('test')?.value))
```

is converted to

```ts
let tmp_b_0;
ctx.a == null ? null : ctx.a.fn(ctx.test((tmp_b_0 = tmp_b_0) == null ? null : tmp_b_0.value));
```

while the following expression

```ts
test(form.get('test')?.value)
```

is converted to

```ts
ctx.test((tmp_b_0 = ctx.form.get("test")) == null ? null : tmp_b_0.value);
```

Note that in the first case we have:

```ts
ctx.test((tmp_b_0 = tmp_b_0) == null ? null : tmp_b_0.value)
```

while in the second:

```ts
ctx.test((tmp_b_0 = ctx.form.get("test")) == null ? null : tmp_b_0.value);
```

So in the first case tmp_b_0 is always undefined...

**Comment by ties-s** [comment]
Yeah I noticed that too. So this is a bug. A pretty big one for my code base.

**Comment by JoostK** [comment]
I have a hunch this got broken in #42882. I'll be looking at a fix.

**Comment by ties-s** [comment]
Thank for the quick fix! Any info on when a new release will be cut?

**Comment by JoostK** [comment]
Typically on Wednesdays (US timezone)
