### ISSUE TITLE
Support md files in components

### ISSUE THREAD

**Issue by splincode** [angular/angular#44078]
### Which @angular/* package(s) are relevant/releated to the feature request?

compiler-cli

### Description

It would be convenient to have support to write documentation for your applications using angular components

### Proposed solution

```ts
@Component({
  selector: 'my-doc',
  templateUrl: './my-doc.component.md'
})
export class MyDocumentationComponent {
  public indexes: string[] = [1, 2];
}
```

my-doc.component.md

```md
# Hello every one

<div *ngFor="let index of indexes">
   **{{ index }}**   
</div>
```

### Benefits

Strict compilation of documentation templates, so the documentation is always up to date!

### Alternatives considered

Boilerplate
https://stackoverflow.com/questions/56435358/how-to-dynamically-render-a-markdown-file-in-angular

**Comment by M-a-c-Carter** [comment]
@splincode I am not sure the needs of your project but you may benefit from storybook if you're looking for more robust documentation on the front end. It comes with its own headaches but there are advantages over just having md's
