### ISSUE TITLE
Ready-made project in StackBlitz has no Angular Generator menu!

### ISSUE THREAD

**Issue by masmangan** [angular/angular#44079]
### Description

Since yesterday, ready-made project in StackBlitz has no Angular Generator menu and is listed as a Node.js project on Dashboard.

Problem reported in StackBlitz:
https://github.com/stackblitz/webcontainer-core/issues/383

### What is the affected URL?

https://angular.io/start

### Please provide the steps to reproduce the issue

Go to 'https://angular.io/start'.
Find Create the sample project section.
Open "To create the sample project, generate the ready-made sample project in StackBlitz" from "https://angular.io/generated/live-examples/getting-started-v0/stackblitz.html".
Move mouse to 'app' inside 'src' on the new project.
Right-click on app. Menu should have an Angular Generator.

### Please provide the expected behavior vs the actual behavior you encountered

Ready-made sample project in StackBlitz should have an Angular Generator menu, hot reload, and be listed as Angular project on StackBlitz dashboard.

### Please provide a screenshot if possible

Open project from here:
![image](https://user-images.githubusercontent.com/595430/140514393-1b6d4b77-f73f-438d-88d3-c65e99bbff42.png)

No Angular Generator menu:
![image](https://user-images.githubusercontent.com/595430/140514347-83365af1-6200-4fa9-9b1f-e76112318716.png)

Project listed as Node.js

### Please provide the exception or error you saw

```true
Error: project is listed as Node.js in StackBlitz Dashboard.
Error: Angular Generator is not available.

Possible solution: fall back to older Angular 12 ready-made sample project.
This new Angular 13 project is not working as expected.
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
Tested on Safari, Edge, and Chrome. Not related to browser.
```

**Comment by petebacondarwin** [comment]
Hi - thanks for reporting this.
We have temporarily moved to the webcontainer approach for the Stackblitz examples while the support for Angular v13 is added to the original version of Stackblitz.
