### ISSUE TITLE
Problem in Angular Tour of Heroes Tutorial Step 6

### ISSUE THREAD

**Issue by songyang-dev** [angular/angular#44073]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] serve

### Description

 I'm following the tutorial on the website called Tour of Heroes (https://angular.io/tutorial/toh-pt6). There is a bug at step 6 when importing 
```typescript
import { InMemoryDataService } from './in-memory-data.service';
```

## 🔬 Minimal Reproduction

Follow the tutorial until you need to import `./in-memory-data.service`.

## 🔥 Exception or Error

<pre><code>

 Error: src/app/app.module.ts:9:37 - error TS2307: Cannot find module './in-memory-data.service' or its corresponding type declarations.
</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.2.9
Node: 14.17.6
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 12.2.9
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.9
@angular-devkit/build-angular   12.2.9
@angular-devkit/core            12.2.9
@angular-devkit/schematics      12.2.9
@schematics/angular             12.2.9
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**

**Comment by Kp0c** [comment]
This service is added a few paragraphs after:
![image](https://user-images.githubusercontent.com/4789526/140476807-9bf49e4b-b68b-4051-971f-cd0e924f0717.png)

But I still see that it may confuse novices who go through the tutorial step-by-step. Probably it makes sense to rearrange paragraphs a bit?

**Comment by petebacondarwin** [comment]
Thanks for reporting this @Kp0c. The text before this block of code does say "which you will create in a moment":

<img width="851" alt="Screenshot 2021-11-05 at 09 05 05" src="https://user-images.githubusercontent.com/15655/140485667-9b2be775-32f0-49f4-987c-0f69790c8dab.png">

but I agree that this probably could be organized to be less confusing.

cc @aikidave
