### ISSUE TITLE
Failed to load plugin '@angular-eslint' declared in

### ISSUE THREAD

**Issue by dean-g** [angular/angular#44086]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

No

### Description

I am getting the following error on linting. 

> nx run test-lib:lint 

Linting "test-lib"...
Failed to load plugin '@angular-eslint' declared in 'libs/test/.eslintrc.json

Can you please check this and advise?

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mlc-mlapis** [comment]
@dean-g Do you use the package eslint@8.1.0?
