### ISSUE TITLE
[Dart] transformers handling of queries

### ISSUE THREAD

**Issue by vicb** [angular/angular#4408]
Similarly to #4407 there are two way to define queries on an Angular component:

- The queries key in a `@Component`,
- The `@ContentChild`, `@ContentChildren`, `@ViewChild` and `@ViewChildren` property decorators.

Shouldn't the queries be recorded in the metadata for the component some around [here](https://github.com/angular/angular/blob/8ff65a30c724e99f4b48935024751180baa9477a/modules_dart/transform/lib/src/transform/common/directive_metadata_reader.dart#L219) ?

The current code merge the query definitions from the `@Component` with the definition generated from the property decorators. AFAIU the definitions from the `@Component` will be ignored in the transformed Dart code and only the property decorators will work.

If this understanding is correct the transformers would benefit from the same kind of updates as the ones described in #4407.

@vsavkin @kegluneq please comment.

**Comment by kegluneq** [comment]
I agree with the approach you outline, but see my comment on #4407: I do not think we should do this prior to the compiler-integration changes landing.

If this is an urgent update, @vicb you or @vsavkin could branch off compiler-integration and update `DirectiveMetadataReader` to understand property annotations. I'd be happy to point you in the right direction.
