### ISSUE TITLE
zone.js propertyPatch breaks spread for objects with Symbol keys.

### ISSUE THREAD

**Issue by wesselvdv** [angular/angular#44095]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When compiling with `optimizations: true` in angular.json it'll enable esbuild which will transpile to ES2015 which causes spreads to be replaced with a polyfill. zone.js has a property patch that overrides `Object.defineProperties` where it's using `Object.keys()` to iterate over the properties of the object to merge into the spread. This causes all symbol keys to be omitted: `Object.keys({ a: 1, b: Symbol() }) === ['a']`

https://github.com/angular/angular/blob/a92a89b0eb127a59d7e071502b5850e57618ec2d/packages/zone.js/lib/browser/define-property.ts#L38-L43

**Comment by JiaLiPassion** [comment]
@wesselvdv , I will check it. thanks.
