### ISSUE TITLE
The pipeline has some problems in idea

### ISSUE THREAD

**Issue by MunMunMiao** [angular/angular#44106]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Every project created with angular cli 13.0.1

### Please provide the exception or error you saw

```true
Idea can't recognize pipe.
The 13 version does not work. No problem with version 12.
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 13.0.1
Node: 17.0.1 (Unsupported)
Package Manager: npm 8.1.1
OS: darwin x64
IntelliJ IDEA: 2021.2.3 (Ultimate Edition)
Plugin: Angular and AngularJS 212.5457.46

Angular: 13.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, material-moment-adapter, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.1
@angular-devkit/build-angular   13.0.1
@angular-devkit/core            13.0.1
@angular-devkit/schematics      13.0.1
@angular/cli                    13.0.1
@schematics/angular             13.0.1
rxjs                            7.4.0
typescript                      4.4.4
```

### Anything else?

Angular material 13 version of the pipe is no problem.

![20211107-235408.png](https://i.loli.net/2021/11/07/kSdpsI9ZOn8fveo.png)

**Comment by petebacondarwin** [comment]
I'm sorry but you have not provided enough information for us to help with this issue.

Please providers to reproduce this error.

**Comment by MunMunMiao** [comment]
> I'm sorry but you have not provided enough information for us to help with this issue.
> 
> Please providers to reproduce this error.

You can create a new project using angular cli 13.0.1. Then use idea 2021.2.3 to open the project, open the Angular and AngularJS plug-in in idea, you can reproduce this error

**Comment by JoostK** [comment]
This is a JetBrains issue, [you can find more details here](https://youtrack.jetbrains.com/issue/WEB-53312).
