### ISSUE TITLE
BrowserModule has already been loaded error when importing an angular library that imports BrowserModule

### ISSUE THREAD

**Issue by jbistis** [angular/angular#44102]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

Yes

### Description

BrowserModule has already been loaded error when importing an angular library that imports BrowserModule. See issue #44015

### Please provide a link to a minimal reproduction of the bug

 https://github.com/angular/angular/issues/44015

### Please provide the exception or error you saw

```true
See https://github.com/angular/angular/issues/44015 I closed prematurely.
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.6
Node: 12.19.0
Package Manager: npm 6.14.8
OS: darwin x64

Angular: 12.2.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
```

**Comment by JoostK** [comment]
#44015 is still open, so closing this one.
