### ISSUE TITLE
Generated services have no providedIn: 'root' by default

### ISSUE THREAD

**Issue by pstricks-fans** [angular/angular#44103]
### Description

I am following [this tutorial](https://angular.io/start/start-data). The given screenshot shows a different result compared to mine.
![di](https://user-images.githubusercontent.com/50270635/140628042-03ab277f-d809-4b1d-875d-a9ba3838976d.png)

Mine is as follows.

```
import { Injectable } from '@angular/core';

@Injectable()
export class CartService {

  constructor() { }

}
```

It means `providedIn: 'root'` is missing in mine.

### What is the affected URL?

https://angular.io/start/start-data

### Please provide the steps to reproduce the issue

Right click on the `app` folder, select `Angular Generator` and `Service`.  Name it `cart`.

However  I cannot reproduce this issue with `ng g s cart` on Visual Studio Code, I strongly believe it is caused by `Angular Generator`  that might be using old template generator.

### Please provide the expected behavior vs the actual behavior you encountered

`providedIn: 'root'`  should be automatically provided.

**Comment by petebacondarwin** [comment]
The current version of the tutorial uses the Stackblitz web-containers mode, where the Angular CLI is actually run in the browser to generate the service (e.g. `ng generate service cart`). This approach does indeed generate the `providedIn: 'root'` option of the `@Injectable`.
