### ISSUE TITLE
Angular elements does't run in production

### ISSUE THREAD

**Issue by gcherem** [angular/angular#44128]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Angular Element (https://angular.io/guide/elements) doesn't run in production. If both host application and element application have the ```--prod``` flag, you are going to see the error bellow. Otherwise (at least one of them **without** ```--prod``` flag), everything works fine.

### Please provide a link to a minimal reproduction of the bug

https://github.com/gcherem/problem-with-elements

### Please provide the exception or error you saw

```true
main.js:1 DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "my-widget" has already been used with this registry
    at CustomElementRegistry.K.t.<computed> [as define] (http://localhost:8887/polyfills.js:1:39666)
    at e.ngDoBootstrap (http://localhost:8887/main.js:1:116837)
    at e._moduleDoBootstrap (http://localhost:8887/main.js:1:85899)
    at http://localhost:8887/main.js:1:85340
    at l.invoke (http://localhost:8887/polyfills.js:1:20438)
    at Object.onInvoke (http://localhost:8887/main.js:1:78683)
    at l.invoke (http://localhost:8887/polyfills.js:1:20378)
    at s.run (http://localhost:8887/polyfills.js:1:15850)
    at http://localhost:8887/polyfills.js:1:30646
    at l.invokeTask (http://localhost:8887/polyfills.js:1:21056)
```

### Please provide the environment you discovered this bug in

```true
Host application:
Angular CLI: 11.2.15
Node: 14.15.1
OS: darwin x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.15
@angular-devkit/build-angular   0.1102.15
@angular-devkit/core            11.2.15
@angular-devkit/schematics      11.2.15
@angular/cli                    11.2.15
@schematics/angular             11.2.15
@schematics/update              0.1102.15
rxjs                            6.6.7
typescript                      4.1.6

Widget:
Angular CLI: 11.2.15
Node: 14.15.1
OS: darwin x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, elements
... forms, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.15
@angular-devkit/build-angular   0.1102.15
@angular-devkit/core            11.2.15
@angular-devkit/schematics      11.2.15
@angular/cli                    11.2.15
@schematics/angular             11.2.15
@schematics/update              0.1102.15
rxjs                            6.6.7
typescript                      4.1.6
```

### Anything else?

Yes. The repository https://github.com/gcherem/problem-with-elements has both host (host application) and widget (angular element). 

I used [Web Server for Chrome](https://github.com/kzahel/web-server-chrome/) for the widget.

If you run the host app with ```start-prod``` and the widget with  ```build-prod```, you are going to see the error. If you run the host with ```start``` or the widget with ```build```, everything will work.

**Comment by flash-me** [comment]
Ok this is really WEIRD.

I added some logs to the AppModule of the Widgets build: 

![image](https://user-images.githubusercontent.com/5240450/141186307-de3e0e03-373b-4a4c-b39f-c372d208b4a4.png)

And this is what i get (both production build):
![image](https://user-images.githubusercontent.com/5240450/141186398-b1bf781f-bd99-4c31-8346-fdf78668762f.png)


Seems like the scripts in the [index.html](https://github.com/gcherem/problem-with-elements/blob/main/host/src/index.html) are being executed TWICE???

I am honestly really interestied in WTF is going on here 😲

P.S. @gcherem In prod build there is no vendor.js chunk created. (But for this issue, this is not relevant)

cheers
flash ⚡

**Comment by gkalpak** [comment]
I believe this is essentially a duplicate of #23732. That is an old issue and the specifics might be outdated, but the general idea of the problem still holds:

Fundamentally, this is a packaging/bundling issue and our tooling does not currently support this usecase.
See the thread at https://github.com/angular/angular/issues/23732#issuecomment-388536241 for more details.

In the mean-time, you probably have to rely on some 3rd-party tools and custom configs.
There are several resources online, such as [this][1], [this][2] or [this][3] (and although they are not super up-to-date, they should be a good starting point).

##
I am going to close this issue, since the general problem of being able to more easily consume independently built Angular Elements is being tracked in #25421.

[1]: https://medium.com/swlh/angular-elements-create-a-component-library-for-angular-and-the-web-8f7986a82999
[2]: https://www.angulararchitects.io/aktuelles/angular-elements-part-i
[3]: https://www.youtube.com/watch?v=_QU0mpyF7bQ

**Comment by flash-me** [comment]
> In the mean-time, you probably have to rely on some 3rd-party tools and custom configs.

Naa. My gut feeling tells me there are solutions with plain angular toolchain. Even for angular elements. 

But could also be just some flatulences

cheers
flash ⚡
