### ISSUE TITLE
WebStorm IDE After Update to Angular 13: No directive is matched on attribute ngIf, Property ngClass is not provided by any applicable directives nor by div element 

### ISSUE THREAD

**Issue by BeSaRa** [angular/angular#44132]
### Which @angular/* package(s) are the source of the bug?

common, forms, upgrade

### Is this a regression?

No

### Description

after Updating to version [13.0.0] all common/forms directives    like [*ngIf , ngClass , formControlName , etc] getting highlighted underline as they have a problem 

here is image from fresh application 
![image](https://user-images.githubusercontent.com/8113320/141093116-534ec5a5-1cc7-4ce8-ba3c-6b8237d29816.png)

![image](https://user-images.githubusercontent.com/8113320/141093355-de86fd75-d603-4816-a04d-6ef35c9f9409.png)

### Please provide the exception or error you saw

```true
there is no Exceptions or error while building/run the application , but the WebStorm IDE blaming for those tags as it is not defined somehow
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 13.0.1
Node: 14.17.0
Package Manager: npm 7.14.0
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1300.1 (cli-only)
@angular-devkit/core         13.0.1 (cli-only)
@angular-devkit/schematics   13.0.1 (cli-only)
@schematics/angular          13.0.1 (cli-only)
```

**Comment by petebacondarwin** [comment]
This is an issue with Webstorm - see https://youtrack.jetbrains.com/issue/WEB-53312?_ga=2.257230859.1620342828.1636539335-1936045001.1636539335

**Comment by BeSaRa** [comment]
thanks @petebacondarwin
