### ISSUE TITLE
Upgrade to Angular 13 installing @angular/localize@13.0.0 gives babel dependency error

### ISSUE THREAD

**Issue by aishwaryasharma14** [angular/angular#44135]
### Which @angular/* package(s) are the source of the bug?

localize

### Is this a regression?

No

### Description

While upgrading to Angular 13, installing npm i @angular/localize@13.0.0 gives following error -

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/core@7.8.6.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@angular/localize'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\we333\AppData\Roaming\npm-cache\_logs\2021-11-10T18_59_00_115Z-debug.log

### Please provide a link to a minimal reproduction of the bug

npm i @angular/localize@13.0.0

### Please provide the exception or error you saw

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/core@7.8.6.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@angular/localize'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\we333\AppData\Roaming\npm-cache\_logs\2021-11-10T18_59_00_115Z-debug.log

### Please provide the environment you discovered this bug in

```true
Angular CLI : 13.0.1
"dependencies": {
    "@angular-devkit/schematics": "^13.0.1",
    "@angular/animations": "^13.0.0",
    "@angular/cdk": "^13.0.0",
    "@angular/cdk-experimental": "^13.0.0",
    "@angular/common": "^13.0.0",
    "@angular/compiler": "^13.0.0",
    "@angular/core": "^13.0.0",
    "@angular/forms": "^13.0.0",
    "@angular/localize": "^13.0.0",
    "@angular/platform-browser": "^13.0.0",
    "@angular/platform-browser-dynamic": "^13.0.0",
    "@angular/router": "^13.0.0"
},
  "devDependencies": {
    "@angular-devkit/build-angular": "^13.0.1",
    "@angular-devkit/build-ng-packagr": "~0.1002.0",
    "@angular-eslint/builder": "^12.6.1",
    "@angular-eslint/eslint-plugin": "^12.6.1",
    "@angular-eslint/eslint-plugin-template": "^12.6.1",
    "@angular-eslint/schematics": "^12.6.1",
    "@angular-eslint/template-parser": "^12.6.1",
    "@angular/cli": "^13.0.1",
    "@angular/compiler-cli": "^13.0.0",
    "@angular/language-service": "^13.0.0",
    "@babel/core": "^7.16.0"
}
```

**Comment by petebacondarwin** [comment]
The package `@babel/core@7.6.8` referenced by `@angular/localize` does exist. See https://unpkg.com/browse/@babel/core@7.8.6/

I wonder if this is a problem with your npm cache or a corruption with the local `node_modules`?
Have you tried deleting both?

**Comment by aishwaryasharma14** [comment]
> The package `@babel/core@7.6.8` referenced by `@angular/localize` does exist. See https://unpkg.com/browse/@babel/core@7.8.6/
> 
> I wonder if this is a problem with your npm cache or a corruption with the local `node_modules`? Have you tried deleting both?

Yes I did try that. Still the same error.

**Comment by petebacondarwin** [comment]
What happens if you run:

```sh
npm i @babel/core@7.8.6
```

**Comment by aishwaryasharma14** [comment]
> What happens if you run:
> 
> ```shell
> npm i @babel/core@7.8.6
> ```

It gives the same error.

**Comment by petebacondarwin** [comment]
In that case, I am afraid this is a problem with your npm setup or connectivity, and not an issue with Angular itself.
Therefore I will close this as not actionable by us.

**Comment by mukundkatpatal** [comment]
@petebacondarwin Thank you for your answer. On a different note, why does angular need a version of angular which was published two years back? There are newer versions of babel available, why cant we use that?

**Comment by petebacondarwin** [comment]
Good question. I don't actually know. I remember that in the past when we tried to upgrade there were loads of typings issues, causing the builds to fail. But perhaps these have been resolved now...

**Comment by mukundkatpatal** [comment]
in our NPM internal private npm feeds we have a retention policy. Even after changing the retention policy in the azure devops artifacts, this old package is not being downloaded. So this package is not there in our internal package registry. It would be great if angular allows us to use the higher versions. Any help in this regard would be helpful

**Comment by petebacondarwin** [comment]
I just attempted this upgrade of Babel. The problem we have is that there is something really broken in how the different packages of Babel associate with `@typings` packages. So there ends up being multiple copies (sometimes at different versions) of the various types. I remember now that this is the problem we hit before.
Assuming it is even solvable without going and sending updates to the typings repositories, it is by no means trivial.
