### ISSUE TITLE
Query string parameters are lost when entering a route

### ISSUE THREAD

**Issue by nosachamos** [angular/angular#4413]
I have a small test app on alpha 38 with three routes, configured as follows:

```
@RouteConfig([
  { path: '/', component: Home, as: 'home' },
  { path: '/errors', component: Errors, as: 'errors' },
  { path: '/about', component: About, as: 'about' }
])
```

I can access the routes using router-link, and when I place query string params in the URL I can read them just fine. However, a few instants after I read the parameters, I noticed that the route loads fine and the URL is updated, removing the query string parameters.

In other words, accessing this route:

**http://localhost:5555/errors?test=abc**

Loads the /errors route, but right after the application loads the URL turns into:

**http://localhost:5555/errors**

I have asked in SO and on Gitter, but one one seems to know what is happening or if I am missing something. I looked through the source code and I didn't find any missing configurations I should be providing, so I'm assuming it's a bug.

**Comment by binarious** [comment]
This seems fixed since Alpha 41 (https://github.com/angular/angular/commit/8bc40d3f4da8244b7cd6bea2f0eeb444ecd5d676).

**Comment by nosachamos** [comment]
Very true. I just validated this again on alpha 42. Ready to be closed.

**Comment by anderslyman** [comment]
Reproduced (to the best of my knowledge) on Angular 4.3.1, 4.4.6 and 5.0.4: https://stackoverflow.com/questions/47598762/angular-erasing-all-query-parameters#47598970

**Comment by tburnett80** [comment]
Also running into this issue with 4.3.1
