### ISSUE TITLE
Compiler doesn't compile when using exactOptionalPropertyTypes

### ISSUE THREAD

**Issue by Airblader** [angular/angular#44157]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

When bootstrapping a new project and setting `"exactOptionalPropertyTypes": true` in the TypeScript configuration, the project will not compile.

### Please provide the exception or error you saw

```true
Error: node_modules/@angular/compiler/src/render3/view/template.d.ts:229:22 - error TS2420: Class 'BindingScope' incorrectly implements interface 'LocalResolver'.
  Types of property 'globals' are incompatible.
    Type 'Set<string> | undefined' is not assignable to type 'Set<string>'.
      Type 'undefined' is not assignable to type 'Set<string>'.

229 export declare class BindingScope implements LocalResolver {
                         ~~~~~~~~~~~~
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 13.0.1
Node: 16.11.0
Package Manager: npm 7.21.0
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1300.1 (cli-only)
@angular-devkit/core         13.0.1 (cli-only)
@angular-devkit/schematics   13.0.1 (cli-only)
@schematics/angular          13.0.1 (cli-only)
```

**Comment by petebacondarwin** [comment]
That is really weird since we have these two definitions:

```ts
export class BindingScope implements LocalResolver {
  ...
  private constructor(
      public bindingLevel: number = 0, private parent: BindingScope|null = null,
      public globals?: Set<string>) {...}
  ...
}
```

and 

```ts
export interface LocalResolver {
  ...
  globals?: Set<string>;
  ...
}
```

which seem entirely compatible.

**Comment by petebacondarwin** [comment]
Ahah! The typings file contains:

```ts
export declare class BindingScope implements LocalResolver {
  ...
  globals?: Set<string> | undefined;
  ...
}
```

see https://unpkg.com/browse/@angular/compiler@13.0.1/src/render3/view/template.d.ts#L232

**Comment by petebacondarwin** [comment]
Compared to https://unpkg.com/browse/@angular/compiler@13.0.1/src/compiler_util/expression_converter.d.ts#L17

```ts
export interface LocalResolver {
   ...
   globals?: Set<string>;
   ...
}
```

**Comment by petebacondarwin** [comment]
So I think this may be a bug in the TS compiler...

**Comment by petebacondarwin** [comment]
Actually re-opening because it will still be a problem until we release a new version of Angular built with 4.5.

**Comment by Airblader** [comment]
Thanks for the quick investigation, I appreciate it.

**Comment by petebacondarwin** [comment]
A possible workaround is to turn off type checking of libraries... [`--skipLibCheck`](https://www.typescriptlang.org/tsconfig#skipLibCheck)
