### ISSUE TITLE
Reduce the size of each new Angular project, notably the size of node_modules

### ISSUE THREAD

**Issue by XsongyangX** [angular/angular#44166]
### Description

I just tried the Angular tutorial on Tour of Heroes. The resulting project size is over 300+ MB. Most of the space is taken up by `node_modules`. When I make a new empty Angular project, it also starts at 300 MB. 

Could this repetitive minimum size be made global? Each project could then start around a few MB in size. And save me some disk space and new project generation time. :)

### Proposed solution

Centralize in one place the minimum `node_modules` required to begin an empty project.

### Alternatives considered

Not really. Just be careful each time you `ng add` something. I use `npm uninstall` to remove the added library. Unless there is an equivalent in `ng`?

**Comment by JoostK** [comment]
This comes down to a package manager concern, for example pnpm and Yarn PnP provide this capability. Angular has not supported these ways of package management as they're incompatible with ngcc, but Angular 13 should've unblocked supporting that as far as the core framework goes (third-party libraries may still require ngcc). This is being tracked in the CLI repo in angular/angular-cli#16980.
