### ISSUE TITLE
File structure lists no longer generated TSLint file

### ISSUE THREAD

**Issue by Airblader** [angular/angular#44163]
### Description

The table on the file structure page has an entry for the `tslint.json`, however this file is no longer generated by the CLI.

### What is the affected URL?

https://angular.io/guide/file-structure#workspace-configuration-files

### Please provide a screenshot if possible

![screenshot-2021-11-13_08-15-10](https://user-images.githubusercontent.com/2392216/141609794-d940d435-befd-4185-92f0-62658a6679cb.png)

**Comment by ravichandra480** [comment]
@alan-agius4 Is it ok If I make a pull request for this change?

**Comment by alan-agius4** [comment]
@ravichandra480, go for it.

**Comment by ravichandra480** [comment]
Thanks @alan-agius4, I am on it.
