### ISSUE TITLE
Lazy loading with two named router outlet

### ISSUE THREAD

**Issue by DislayPS** [angular/angular#44178]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

A route with two named router-outlet is hard to initialize with lazy loading in place (eg: /lazyroute/(outlet1:list, outlet2: details)
We would like to initialize the bare /lazyroute to display the list in outlet1

Minimal reproduction is available here: https://stackblitz.com/edit/angular-ivy-vahsaa

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-vahsaa

**Comment by atscott** [comment]
@DisplayPS I don't think I understand what the question is here. You want to make the `/lazy` route impossible to go on its own but always redirect to `/lazy/(list:list)` instead? Why have the `(list:list)` route at all and not just include that content in `LazyPageComponent`?

Anyhow, yes, there is a way to do this: https://stackblitz.com/edit/angular-ivy-kylltj?file=src%2Fapp%2Flazy%2Flazy.module.ts

You want a `UrlMatcher` which only matches the redirect when there are no segments _and_ parent group only has one child (the primary outlet). If the parent group has more than one child (i.e. it has an entry for an auxiliary route), you do not want it to match.

**Comment by atscott** [comment]
Closing since I _think_ I eventually understood what was being asked. Please let me know if you were looking for something else.

**Comment by DislayPS** [comment]
Hey @atscott thanks so much for looking into this.
Sorry if it was explained poorly =) 

Yes this is what I was looking for, so thank you so much for helping me out!

Note: the list outlet can have a multiple views as well, but I wanted to initialize it with one at first on the higher level /lazy route.

Thanks so much again!
