### ISSUE TITLE
[Bug & Proposal] can't set the "control" property of <label> elements (it's not recognized by the compiler)

### ISSUE THREAD

**Issue by iuliust** [angular/angular#44182]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

No

### Description

Hi everyone!
I recently discovered that one can link a <label> to a checkbox without using any id.
According to [the W3C's own documentation](https://html.spec.whatwg.org/multipage/forms.html#the-label-element), since 2016, the HTMLLabelElement has an optional "control" property which allows a developer to link a <label> element to any HTML element in the page by its DOM reference instead of using its ID.

However, Angular's template typechecker does NOT recognize that property:
```html
<input #checkboxRef type="checkbox">
<label [control]="checkboxRef">check me</label>
```
triggers the following error:
```
Error: src/app/site/demos/translation-system/translation-system.page.html:98:8 - error NG8002: Can't bind to 'control' since it isn't a known property of 'label'.

98 <label [control]="checkboxRef">
          ~~~~~~~~~~~~~~~~~~~~~~~
```

I think that solving this bug could also simplify a problem that I've often encountered while making web apps: if it were not for this "control" property, we have to always create a unique Id and then reference it in the html, which is quite cumbersome and always complicates the typescript code just a bit more (provided one wants to avoid having duplicate ids).

I think it should be quite quick & easy to fix and it would have a good added benefit.

### Please provide the exception or error you saw

```true
Error: src/app/site/demos/translation-system/translation-system.page.html:98:8 - error NG8002: Can't bind to 'control' since it isn't a known property of 'label'.

98 <label [control]="checkboxRef">
```
```


### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.1
Node: 16.13.0
Package Manager: yarn 3.1.0
OS: linux x64

Angular: 13.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.1
@angular-devkit/build-angular   13.0.1
@angular-devkit/core            13.0.1
@angular-devkit/schematics      13.0.1
@angular/cli                    13.0.1
@schematics/angular             13.0.1
rxjs                            7.4.0
typescript                      4.4.4
```

### Anything else?

I'm not accustomed to Angular's code base, but I could maybe I could make a pull request, provided I get just enough help to know which file I should change in the project.

**Comment by JoostK** [comment]
From reading the docs you linked, the `HTMLLabelElement.control` is a readonly property to get the "labeled control" that the browser has associated with this label. That is determined by the `for` attribute, or derived from the label's content. It does not work as a setter, as far as the specification is concerned.

As such, I'll be closing this as working as expected but feel free to follow up below.

**Comment by iuliust** [comment]
Damn you're right!
Sorry!
