### ISSUE TITLE
FormArray insert and setControl insert items on wrong index #13128

### ISSUE THREAD

**Issue by Viktor-Bredihin** [angular/angular#44198]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

https://github.com/angular/angular/issues/13128
I want to reopen this issue, because it hasn't been fixed, and I'm confused why it was closed

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.2.4
Node: 16.13.0 (Unsupported)
Package Manager: npm 8.1.0
OS: linux x64

Angular: 12.2.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router
```

**Comment by AndrewKushnir** [comment]
Hi @Viktor-Bredihin, I've checked the mentioned thread (#13128), the code of [the insert method](https://github.com/angular/angular/blob/master/packages/forms/src/model.ts#L2040-L2045) and other `FormArray` methods like `removeAt` and `setControl`. None of them have checks in case an index is greater than a length of the array, so the internal logic relies on the `splice` behavior. Changing this behavior to throw in case of invalid index would be a big breaking change for the code that relies on the current behavior. Given the fact that `FormArray` provides an API to get the length of the controls array (see the `length` method), it's possible to update app logic to check that the index is inside the range of existing controls. I think the best solution for now would be to update docs to have a note on this behavior as it was proposed in https://github.com/angular/angular/issues/13128#issuecomment-280799097.
