### ISSUE TITLE
Nullish Coalescing Operator in template expression ( not interpolation )

### ISSUE THREAD

**Issue by TomaszCz** [angular/angular#44207]
### Which @angular/* package(s) are relevant/releated to the feature request?

@angular/angular
and specifically
https://github.com/angular/angular/blob/master/packages/compiler/src/expression_parser/parser.ts

### Description

```
<div [class]="null ?? 'test'" >
  <!--  -->
</div>
```

This is not compiling and we get:
error NG5002: Parser Error: Unexpected token ? at column 7 in [null ?? 'test'] in ...

![image](https://user-images.githubusercontent.com/20865719/142373537-6dda7d45-3636-429b-b120-71b06a381999.png)

I found this PR which extended angular to support Nullish coalescing in templates
https://github.com/angular/angular/pull/41437

It seems only interpolation expressions has been extended.

I found some interesting comment, which is partially clear for me
https://github.com/angular/angular/blob/master/packages/compiler/src/expression_parser/parser.ts#L84

Let me quote the quote here:
// Quotes expressions use 3rd-party expression language. We don't want to use
// our lexer or parser for that, so we check for that ahead of time.

Does that mean that we wait for the 3rd-party expression language to support it? 
What package is it?

All the best
Tomek

### Proposed solution
```

<div [class]="null ?? 'test'" >
  <!--  -->
</div>
```

such code should of course evaluate to
```
<div class="test" >
  <!--  -->
</div>
```

### Alternatives considered

No alternatives

**Comment by JoostK** [comment]
What Angular version are you using? Please share the output of `ng version`.

**Comment by TomaszCz** [comment]
Ah! My mistake. After update to angular 12 it works well. Sorry.
