### ISSUE TITLE
Angular docs missing way to lazy load a component

### ISSUE THREAD

**Issue by ashwinikumar01** [angular/angular#44206]
### Description

As of current angular docs, we have support for lazy loading modules as given in the docs but still lazy loading for particular component inside another component is missing as it is increasing **main.js** bundle size during initial load. Even apart from that, how to load that particular component as soon as the use reaches to the viewport of that component and all those handling stuffs.

Other possible ways to reduce main.js bundle size are also still missing. A package named GZipper gives the opputunity to reduce main.js size but still no crystal clear idea regarding those optimizations in Angular docs.

### Please provide a screenshot if possible

<img src="https://user-images.githubusercontent.com/69667369/142360299-d11d80eb-0049-4cbf-9400-d45dcf94a3b7.png" width="400" height="200" />

**Comment by AndrewKushnir** [comment]
Hi @ashwinikumar01,

There is a guide on lazy loading NgModules: https://angular.io/guide/lazy-loading-ngmodules.
With Standalone Components feature ([see RFC](https://github.com/angular/angular/discussions/43784)) it should be possible to get better ergonomics to load Components (see the `Components: lazy loading and instantiation` section of the RFC).

We'll be updating docs as a part of the Standalone Components feature, so I will close this ticket for now.

Thank you.

**Comment by ashwinikumar01** [comment]
Thanks, @AndrewKushnir for your quick response.
