### ISSUE TITLE
Add more useful info to navigation events, in particular whether only params where changed for example

### ISSUE THREAD

**Issue by mrahhal** [angular/angular#44248]
### Which @angular/* package(s) are relevant/releated to the feature request?

router

### Description

I'm migrating from ui-router to the angular router, and while I'm missing a few minor niceties here and there, there's a particular blocking issue we're facing. The navigation events are extremally barebones when it comes to the info they provide. Here's the current `NavigationStart` event, only having a string url and the trigger as info:
https://github.com/angular/angular/blob/d015ac214f4e372607403e6e93c48f8a2b5014f9/packages/router/src/events.ts#L47-L108

We have a particularly common workflow, we update query params in response to user input (for example a search page) so that state is preserved on refreshes. But we also subscribe to navigation events to centrally handle showing spinners for loading among other things. This causes the input to lose focus when this happens (so every time the user actually is writing text), so this is a huge blocking issue in almost all our pages.

In ui-router, we were easily able to tell transitions that are dynamic apart (i.e transitions that only changed query params) and so we could ignore these kinds of navigations in our handlers.

### Proposed solution

I'm proposing adding more useful info to the navigation events, in particular info relating to _what actually changed_ in this transition.

I'm proposing the following additional properties on all navigation events:
- `dynamic`: Whether the navigation only changes params or query params. (maybe can have a better name?)

Additional props that I think would be helpful in certain situations:
- `snapshot`: The current route snapshot. Why not expose this in the event instead of making the user retrieve it through DI and the router service.
- `extras`: The `NavigationExtras` object that was supplied when navigation was called, if the trigger is imperative.

Looking at the code, this looks straightforward. I'm ready to work on a PR for this as I'm completely blocked by it right now.

### Alternatives considered

In the event object, there's simply no way to know what the transition actually changed from the event itself without doing some tracking myself. For the same goal, you can use the `pairwise` rxjs operator to get the previous event, and then compare to see what changed. This has one big problem, it fails when a navigation is canceled/errors as it's taking a cancelled previous url that is stale. This is completely unfeasible.

Second, I tried working around this by actually tracking the active element and restoring that after the navigation to restore lost focus. This is very hacky and unstable, I'm not comfortable at all with this kind of solution.

**Comment by Airblader** [comment]
Have you looked at the information provided in `getCurrentNavigation()`? I use that for [https://ngqp.io](ngqp) which seems to do exactly what you're doing, too, along with some other tricks like using `state` to identify navigations triggered by the library.

**Comment by mrahhal** [comment]
@Airblader thanks. I can actually get the successful current and previous navigations in this way which is a better workaround for the alternative I mentioned. But yeah I still think having some of the proposed additions above will be much more useful.

**Comment by atscott** [comment]
As mentioned by @Airblader, the information is generally available already in `getCurrentNavigation` and won't be duplicated to the events. This specific proposal for a helper function should be opened as a new feature request:

> dynamic: Whether the navigation only changes params or query params. (maybe can have a better name?)
