### ISSUE TITLE
Provider class deps type safety

### ISSUE THREAD

**Issue by dsimon-onventis** [angular/angular#44256]
### Which @angular/* package(s) are relevant/releated to the feature request?

core

### Description

I have an interceptor which needs to inject a service. I followed [this SO thread](https://stackoverflow.com/questions/49238907/injected-service-in-httpinterceptor-not-initialized) and added the required service to the `deps`, so I can inject it.

However, I just realized that the types of the injected services in the interceptor and the types of the provided `deps` are not checked against. So it can happen that in the `deps`, the wrong service is used. But this does neither lead to a build nor to a runtime error. That means, it can easily happen that an interceptor breaks without being noticed.

I've set up a repo for demonstration: https://stackblitz.com/edit/angular-ivy-xgjm7m?file=src%2Fapp%2Fapp.module.ts
When adding the correct service to the provider deps, an additional header will be added to the HTTP request. However, when injecting a wrong service, e.g. HttpClient, the header will not be added, but no error is thrown.

### Proposed solution

When using class providers with depency injection, the injected elements in the class constructor and the `deps` of the providers should be compared by the framework. In case of a mismatch, an error should be thrown.

### Alternatives considered

The type of the injected services can be manually checked:

```typescript
@Injectable()
export class MyInterceptor implements HttpInterceptor {
  constructor(private myService: MyService) {
    if (!(this.myService instanceof MyService)) {
      throw new Error('expected type MyService');
    }
  }

  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    // ... interceptor logic
    return next.handle(request);
  }
}
```

**Comment by JoostK** [comment]
Closely related to #33883.

This is not trivial to achieve. The `deps` array contains _tokens_, which have some underlying type provided. We'd have to somehow attempt to figure out the type of a token: for `InjectionToken` this would be its generic type argument, for a type reference we'd have to assume the provided service has that type, and for string tokens we'd presumably need to fallback to `any`. In the case of `useClass` we'd then have to relate those types to the constructor arguments; I'm not sure if we can do that using the type definitions of `ClassProvider`.
