### ISSUE TITLE
AIO: UI improvements for deprecated APIs

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#44265]
### Description

Sometimes it's a bit unclear that a particular API is deprecated, for example take a look at the "entryComponents" at https://angular.io/api/core/NgModule. It'd be great to highlight deprecated APIs as such a bit more. Here are some ideas:

- on the summary list we can add a "deprecated" label/tag and also strikethrough the name:

<img width="828" alt="deprecated-ui-1" src="https://user-images.githubusercontent.com/43554145/143310138-daef73fb-cb51-48ca-a662-842f0b2e635c.png">

- on a method/property details section we can do the same:

<img width="811" alt="deprecated-ui-2" src="https://user-images.githubusercontent.com/43554145/143310201-8bce2695-ee54-486e-a315-973657112581.png">

Also for some reasons the deprecation message itself is missing as well (see the message at https://github.com/angular/angular/blob/master/packages/core/src/metadata/ng_module.ts#L200-L203).

### What is the affected URL?

https://angular.io/api/core/NgModule

**Comment by alan-agius4** [comment]
I like what @AndrewKushnir is proposing here, especially making the deprecated text a bit more prominent. 

In the CLI MAN pages https://angular.io/cli/update something similar is displayed but the deprecated text isn't as prominent. 

![Screenshot 2021-11-25 at 10 05 29](https://user-images.githubusercontent.com/17563226/143411906-76fb3859-325e-4770-a180-b95382302d04.png)
