### ISSUE TITLE
docs-infra: deprecated APIs are not highlighted as such

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#44264]
### Description

Deprecated APIs are not highlighted as such on some of the AIO pages, for example:

https://angular.io/api/core/PlatformRef

The `bootstrapModuleFactory` is deprecated, but it has no line through to indicate it. It looks like the CSS class is there and there is a problem with CSS rule specificity (correct rule is overridden by more specific one), see screen shot attached.

<img width="1088" alt="deprecated-api-ui" src="https://user-images.githubusercontent.com/43554145/143308493-96f1be7b-b74a-4fde-8860-4b5f37d45f56.png">

### What is the affected URL?

https://angular.io/api/core/PlatformRef

**Comment by petebacondarwin** [comment]
I have a fix for this.
