### ISSUE TITLE
Unable to test / mock dom sanitizer - unsafe value used in a resource URL context

### ISSUE THREAD

**Issue by LPCmedia** [angular/angular#44271]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes, this showed up with angular 13 + mjs fesm2020

### Description

When testing a component that contains an iframe with a url binding, we cannot mock bypassSecurityTrustResourceUrl from the DomSanitizer. Running fixture.detectChanges() generates an error:  

unsafe value used in a resource URL context (see https://g.co/ng/security#xss)

Seems that angular core is internally not using DomSanitizer in core.mjs' elementPropertyInternal which leads to the attached  error. 

looking for a clear way / guide to test in this case and/or fix. This is new with ng13 and mjs modules. 

### Please provide a link to a minimal reproduction of the bug

https://github.com/LPCmedia/sanitizer-test-issue

### Please provide the exception or error you saw

```true
unsafe value used in a resource URL context (see https://g.co/ng/security#xss)

      at ɵɵsanitizeResourceUrl (../../node_modules/@angular/core/fesm2020/core.mjs:6023:11)
      at elementPropertyInternal (../../node_modules/@angular/core/fesm2020/core.mjs:10062:37)
      at ɵɵproperty (../../node_modules/@angular/core/fesm2020/core.mjs:14770:9)
      at AppComponent_Template (../../ng:/AppComponent.js:7:21)
      at executeTemplate (../../node_modules/@angular/core/fesm2020/core.mjs:9637:9)
      at refreshView (../../node_modules/@angular/core/fesm2020/core.mjs:9503:13)
      at refreshComponent (../../node_modules/@angular/core/fesm2020/core.mjs:10674:13)
      at refreshChildComponents (../../node_modules/@angular/core/fesm2020/core.mjs:9299:9)
      at refreshView (../../node_modules/@angular/core/fesm2020/core.mjs:9553:13)
      at renderComponentOrTemplate (../../node_modules/@angular/core/fesm2020/core.mjs:9617:9)
      at tickRootContext (../../node_modules/@angular/core/fesm2020/core.mjs:10848:9)
      at detectChangesInRootView (../../node_modules/@angular/core/fesm2020/core.mjs:10873:5)
      at RootViewRef.detectChanges (../../node_modules/@angular/core/fesm2020/core.mjs:21796:9)
      at ComponentFixture._tick (../../node_modules/@angular/core/fesm2015/testing.mjs:141:32)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.3
Node: 14.17.0
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 13.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.3
@angular-devkit/build-angular   13.0.3
@angular-devkit/core            13.0.3
@angular-devkit/schematics      13.0.3
@angular/cli                    13.0.3
@schematics/angular             13.0.3
rxjs                            7.4.0
typescript                      4.4.4
```

**Comment by JoostK** [comment]
Please push your repo to the GitHub repo as it's currently empty.

**Comment by LPCmedia** [comment]
yes, that's done. let me know if you still have issues.

**Comment by JoostK** [comment]
Thanks for pushing the repo. I don't quite understand the intention of the `DomSanitizer` stub. It is stubbed as the identify function, meaning that the value won't actually be a `SafeValue`. This means that the runtime will not accept the value, as the `iframe[src]` binding is security-sensitive and therefore requires trusted input. Without the `SafeValue` bypass the value won't be safe, hence the runtime throws an error.

It is unclear to me what the behavior was in Angular 12.

**Comment by LPCmedia** [comment]
Thanks for the reply. I can confirm that this was working for us in angular 12 ...however if I backport the attached reproduction its failing the same way. I would have to back track to confirm this is a regression and see when this broke. 

But really we need clarity on how I can stub `DomSanitizer` and have it work when I run the tests preferably with `fixture.DetectChanges()`. 

- When I run the app, the run-time is fine and inserts the `SafeRessourceUrl` into the iframe
- when I test and call `ngOnInit` the test passes. 
- As soon as a `fixture.detectChanges()` is called the test errors out with unsafe value used in a resource URL context 

I added another basic tests to illustrate this, with a valid value for 

But following @JoostK 's comment above, I removed the stubs and changed our tests a bit. **Testing is fine if we don't stub the `DomSanitizer`.** This can probably be closed even if it seems that we should be able to stub this.

**Comment by JoostK** [comment]
It might be that your v12 setup is using View Engine instead of Ivy (I noticed you are using Nx + Jest, which may require manual invocation of ngcc to switch to Ivy); the sanitization infrastructure changed quite a bit in Ivy.

**Comment by LPCmedia** [comment]
Right it is possible, we have been on Ivy for a while though and to be honest, now that the test is working there's not a lot of justification to pinpoint the exact cause on our end. 

Looking forward with ng13+, mjs + ivy, should it be possible to stub `DomSanitizer` and expect `fixture.detectChanges()` to work ? or at least info on how to test this scenario ? If not I can close this.

**Comment by alxhub** [comment]
There's not a way for a user to provide a custom `DomSanitizer`, even in testing, and this is by design.
