### ISSUE TITLE
The swPush.notificationClicks does not fire in google chrome if it is started using "user-data-dir"

### ISSUE THREAD

**Issue by luiz-telles** [angular/angular#44279]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

No

### Description

I'm working in a project using ionic+angular and I noticed that when I start the google chrome: "chrome.exe"   --user-data-dir=\Users\user1\src\tmpChrome01, I dont know why but the swPush.notificationClicks is not fired after click on the message.

The same test was did without "user-data-dir" and it worked fine. 

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.2
Node: 16.10.0
Package Manager: npm 7.24.0
OS: win32 ia32

Angular: 13.0.1
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.2
@angular-devkit/build-angular   13.0.2
@angular-devkit/core            13.0.2
@angular-devkit/schematics      13.0.2
@angular/cli                    13.0.2
@schematics/angular             13.0.2
rxjs                            7.4.0
typescript                      4.4.4
```

**Comment by gkalpak** [comment]
Tha for reporting this, @luiz-telles :+1:

This is unexpected (unless it is a browser quirk - unrelated to Angular). I don't think there is anything that the Angular ServiceWorker could have done to cause this (again, unless the browser behaves differently in the two cases) 😕

Would you be able to debug this further and gather some more info? 
For example:
- Does the `notificationclick` event fire in the SW ([corresponding source code][1])?
- Is a `NOTIFICATION_CLICK` event sent to all clients ([corresponding source code][2])?
- Is the raw `NOTIFICATION_CLICK` event caught on the client ([corresponding source code][3])?

[1]: https://github.com/angular/angular/blob/b31973c176f67fda563e77c8c5d59ae45881de4c/packages/service-worker/worker/src/driver.ts#L169
[2]: https://github.com/angular/angular/blob/b31973c176f67fda563e77c8c5d59ae45881de4c/packages/service-worker/worker/src/driver.ts#L387-L390
[3]: https://github.com/angular/angular/blob/b31973c176f67fda563e77c8c5d59ae45881de4c/packages/service-worker/src/low_level.ts#L168

**Comment by luiz-telles** [comment]
I set a breakpoint in ngsw-worker.js in the Chrome console for the first two cases and it didn't stop after the click. For the latter case, could you help me by showing how  the best way to get it?

**Comment by gkalpak** [comment]
If the first two breakpoints weren't hit, then the third one won't either.
So, if the browser does not call the `notificationclick` listener, then there is nothing that the Angular SW can do here.

Maybe report this to the Chromium bug tracker.
I am going to close this issue, since it doesn't seem to be related to Angular, but fell free to continue the discussion below.
