### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'match') when running application

### ISSUE THREAD

**Issue by jethas-bennettjones** [angular/angular#44286]
### Which @angular/* package(s) are the source of the bug?

compiler, Don't known / other

### Is this a regression?

Yes

### Description

After upgrading to Angular 13, I have started seeing this error whenever I start up the application:
```
TypeError: Cannot read properties of undefined (reading 'match')
    at extractCommentsWithHash (:5000/vendor.js:290935)
    at ShadowCss.shimCssText (:5000/vendor.js:290454)
    at :5000/vendor.js:306725
    at Array.map (<anonymous>)
    at compileStyles (:5000/vendor.js:306724)
    at compileComponentFromMetadata (:5000/vendor.js:306169)
    at CompilerFacadeImpl.compileComponentFromMeta (:5000/vendor.js:306920)
    at CompilerFacadeImpl.compileComponent (:5000/vendor.js:306908)
    at Function.get (:5000/vendor.js:348767)
    at getComponentDef (:5000/vendor.js:321523)
```

I believe this might be regression as I have seen other tickets mention this issue, but most of them say that the culprit is the existence of `module: commonjs` in the tsconfig file, but this is not the case for me.

I have also manually modified the angular.json file to explicitly say that I am using scss, but the error still persists, and only at runtime.

### Please provide the exception or error you saw

```true
TypeError: Cannot read properties of undefined (reading 'match')
    at extractCommentsWithHash (:5000/vendor.js:290935)
    at ShadowCss.shimCssText (:5000/vendor.js:290454)
    at :5000/vendor.js:306725
    at Array.map (<anonymous>)
    at compileStyles (:5000/vendor.js:306724)
    at compileComponentFromMetadata (:5000/vendor.js:306169)
    at CompilerFacadeImpl.compileComponentFromMeta (:5000/vendor.js:306920)
    at CompilerFacadeImpl.compileComponent (:5000/vendor.js:306908)
    at Function.get (:5000/vendor.js:348767)
    at getComponentDef (:5000/vendor.js:321523)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.3
Node: 16.13.0
Package Manager: npm 8.1.3
OS: win32 x64

Angular: 13.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.3
@angular-devkit/build-angular   13.0.3
@angular-devkit/core            13.0.3
@angular-devkit/schematics      13.0.3
@angular/cli                    13.0.3
@schematics/angular             13.0.3
rxjs                            6.6.7
typescript                      4.4.4
```

**Comment by JoostK** [comment]
Please provide a repro so we can investigate. Thanks!

**Comment by alan-agius4** [comment]
For reference the CJS issue mentioned above is https://github.com/angular/angular-cli/issues/21588

**Comment by jethas-bennettjones** [comment]
> For reference the CJS issue mentioned above is [angular/angular-cli#21588](https://github.com/angular/angular-cli/issues/21588)

Thanks for linking the tickets, Alan. I had initially come across this ticket, but removing all of the `CommonJS` references I could find didn't resolve my issue. I'll try to get a minimum repro done today.

**Comment by alan-agius4** [comment]
@jethas-bennettjones what is the value of `module` in your tsconfigs?

**Comment by jethas-bennettjones** [comment]
> @jethas-bennettjones what is the value of `module` in your tsconfigs?

It isn't set for production, but it was set to commonjs for testing. I removed it from there but I'm still having issues.

**Comment by alan-agius4** [comment]
If you don’t have any module set it will default to `commonjs` if the syntax `target` is `es5` or lower.

Can you try to set the `module` to `es2020` in your root level tsconfig?
