### ISSUE TITLE
more BROKEN BUILD with no solution

### ISSUE THREAD

**Issue by nhhockeyplayer** [angular/angular#44299]
### Which @angular/* package(s) are the source of the bug?

common, compiler-cli, compiler, core, language-service, Don't known / other

### Is this a regression?

Yes

### Description

cannot build

### Please provide a link to a minimal reproduction of the bug

Im sorry I do not have time to spend on fixing broken angular I know the team needs repo's but this is way out of control now 

### Please provide the exception or error you saw

```true
> nx run mobile-app:build:production 
require() of ES Module /Users/meanstack02/new/starter/node_modules/@angular/compiler-cli/bundles/index.js from /Users/meanstack02/new/starter/node_modules/@angular-builders/custom-webpack/node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js not supported.
Instead change the require of index.js in /Users/meanstack02/new/starter/node_modules/@angular-builders/custom-webpack/node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js to a dynamic import() which is available in all CommonJS modules.
```
```


### Please provide the environment you discovered this bug in (run `ng version`)

```
>  NX  Report complete - copy this into the issue template

  Node : 16.13.0
  OS   : darwin x64
  yarn : 1.22.17
  
  nx : 13.2.2
  @nrwl/angular : 13.2.2
  @nrwl/cli : 13.2.2
  @nrwl/cypress : 13.2.2
  @nrwl/devkit : 13.2.2
  @nrwl/eslint-plugin-nx : 13.2.2
  @nrwl/express : 13.2.2
  @nrwl/jest : 13.2.2
  @nrwl/linter : 13.2.2
  @nrwl/nest : 13.2.2
  @nrwl/next : undefined
  @nrwl/node : 13.2.2
  @nrwl/nx-cloud : 12.5.4
  @nrwl/react : 13.2.2
  @nrwl/react-native : undefined
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 13.2.2
  @nrwl/web : 13.2.2
  @nrwl/workspace : 13.2.3
  @nrwl/storybook : 13.2.2
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
  	 @angular/animations: 13.0.2
  	 @angular/cdk: 13.0.2
  	 @angular/common: 13.0.2
  	 @angular/compiler: 13.0.2
  	 @angular/core: 13.0.2
  	 @angular/forms: 13.0.2
  	 @angular/material: 13.0.2
  	 @angular/platform-browser: 13.0.2
  	 @angular/platform-browser-dynamic: 13.0.2
  	 @angular/router: 13.0.2
  	 @fortawesome/angular-fontawesome: 0.9.0
  	 @ionic/angular: 5.9.1
  	 @ngrx/effects: 13.0.1
  	 @ngrx/entity: 13.0.1
  	 @ngrx/router-store: 13.0.1
  	 @ngrx/schematics: 13.0.1
  	 @ngrx/store: 13.0.1
  	 @ngrx/store-devtools: 13.0.1
  	 @nxtend/capacitor: 12.0.0
  	 @nxtend/ionic-angular: 11.1.1
  	 angular-builder-custom-terser-options: 1.0.1
  	 ngx-bootstrap: 7.1.0
  	 @angular-builders/custom-webpack: 12.1.3
  	 @angular-devkit/build-angular: 13.0.3
  	 @angular/cli: 13.0.3
  	 @angular/compiler-cli: 13.0.2
  	 @angular/language-service: 13.0.2
  	 @nxtend/capacitor: 12.0.0
```

### Anything else?



I tried adding this to my package.json

`    "type": 'module',`

but trusting new releases should be backward compatible I should not need to add that and my code build

nope

nothing works

**Comment by nhhockeyplayer** [comment]
ok I had to temporarily bastardize up my projects with a webpack builder over the summer to get past the incompetence across the ecosystem that wiped out angular 12

Im glad to revert these bastardizations

trying it now to see if things are the way they should be

results pending

**Comment by alan-agius4** [comment]
The issue appears to be caused by the usage of `@angular-builders/custom-webpack`. 

This package is not supported by the Angular team.

**Comment by nhhockeyplayer** [comment]
Thank you apologies, I tried to factor out webpack from the start last JUNE until angular 12 was disrupted by all flanking ecosystem dependencies npm, webpack, sass and more...

Angular is building now fine and I am able to perform my own Object Oriented modeling for all biz objects with copy ctor, hash, clone, equals for maximum polymorphism as opposed to just interfaces which are rare find in the field from all the hip scripters

thanks to the team for holding thru
