### ISSUE TITLE
[NgZone] Enabling bootstrap option ngZoneRunCoalescing prevents app from loading when opened in a new tab

### ISSUE THREAD

**Issue by JasonDickens** [angular/angular#44314]
### Which @angular/* package(s) are the source of the bug?

Zone

### Is this a regression?

Yes

### Description

After enabling the Angular option `ngZoneRunCoalescing`, all change detection is stopped when the tab is not visible since the NgZone option `shouldCoalesceRunChangeDetection` relies on `requestAnimationFrame` to trigger the next change detection. 

> ...requestAnimationFrame() calls are paused in most browsers when running in background tabs or hidden iframe...
>
> [Window.requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)

As a result, components that rely on change detection to begin or complete work will be blocked until the page becomes visible. In this case, users who try to open an Angular app with long load time in a separate window/tab to let it load in the background will potentially make no progress on the load.

Here is a minimal app that shows the problem [run SimpleApp](https://angular-ivy-2selqj.stackblitz.io/) - [SimpleApp source](https://stackblitz.com/edit/angular-ivy-2selqj?file=src%2Fmain.ts). If you open this in a new tab, the count doesn't begin until the tab becomes visible, but if you turn off `ngZoneRunCoalescing` and open in a new tab, the count starts and continues through the end if you leave the tab hidden long enough.

I am working on an app that reads data from a potentially slow external connection, then creates a bunch of components that each further process and visualize the received data, potentially creating more components. These components rely on the Angular lifecycle to receive input bindings and update several times through services, sometimes relying on the output of other components to further process the data before it can be rendered. This is all blocked until the tab becomes visible.

Without `ngZoneRunCoalescing`, users can open the app in a separate tab and allow it to load in the background while doing other work, but with this turned on, the app sits there and doesn't start loading until the tab becomes visible.

I really want to use this option as I'm seeing a 10-30% improvement in load performance with it turned on (as long as the page is visible during the entire load)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-2selqj

### Please provide the exception or error you saw

```true
App load blocked due to all change detection stopped
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: no
Node: v14.15.4
Package Manager: npm 6.14.10
OS: Windows 10

Angular: 12.2.11
@angular/animations: 12.2.11,
@angular/cdk: 12.2.11,
@angular/common: 12.2.11,
@angular/core: 12.2.11,
@angular/elements: 12.2.11,
@angular/forms: 12.2.11,
@angular/material: 12.2.11,
@angular/platform-browser: 12.2.11,
@angular/platform-browser-dynamic: 12.2.11,
@angular/platform-server: 12.2.11,
@angular/router: 12.2.11,
@angular/upgrade: 12.2.11,
typescript: 4.3.5,
```

**Comment by JasonDickens** [comment]
@JiaLiPassion - After spending time digging into ngZone to find a way around this problem, this is a patch that I came up with that resolves the problem, but since it's not a one-line patch, there is concern with checking this in and using it in my production code.

```
diff --git a/node_modules/@angular/core/esm2015/src/zone/ng_zone.js b/node_modules/@angular/core/esm2015/src/zone/ng_zone.js
index 5202a28..5424ed6 100644
--- a/node_modules/@angular/core/esm2015/src/zone/ng_zone.js
+++ b/node_modules/@angular/core/esm2015/src/zone/ng_zone.js
@@ -256,10 +256,23 @@ function delayChangeDetectionForEvents(zone) {
      * so we also need to check the _nesting here to prevent multiple
      * change detections.
      */
-    if (zone.isCheckStableRunning || zone.lastRequestAnimationFrameId !== -1) {
+    if (zone.isCheckStableRunning || zone.lastRequestAnimationFrameId !== -1 || document.hidden) {
         return;
     }
-    zone.lastRequestAnimationFrameId = zone.nativeRequestAnimationFrame.call(global, () => {
+    var animationFrameTimeout;
+    var triggerChangeDetection = () => {
+        if (animationFrameTimeout) {
+            clearTimeout(animationFrameTimeout);
+        }
+        if (zone.lastRequestAnimationFrameId !== -1) {
+            zone.lastRequestAnimationFrameId = -1;
+            updateMicroTaskStatus(zone);
+            zone.isCheckStableRunning = true;
+            checkStable(zone);
+            zone.isCheckStableRunning = false;
+        }
+    };
+    zone.lastRequestAnimationFrameId = zone.nativeRequestAnimationFrame.call(_global, () => {
         // This is a work around for https://github.com/angular/angular/issues/36839.
         // The core issue is that when event coalescing is enabled it is possible for microtasks
         // to get flushed too early (As is the case with `Promise.then`) between the
@@ -271,15 +284,17 @@ function delayChangeDetectionForEvents(zone) {
         // eventTask execution.
         if (!zone.fakeTopEventTask) {
             zone.fakeTopEventTask = Zone.root.scheduleEventTask('fakeTopEventTask', () => {
-                zone.lastRequestAnimationFrameId = -1;
-                updateMicroTaskStatus(zone);
-                zone.isCheckStableRunning = true;
-                checkStable(zone);
-                zone.isCheckStableRunning = false;
+                triggerChangeDetection();
             }, undefined, () => { }, () => { });
         }
         zone.fakeTopEventTask.invoke();
     });
+    // To prevent change detection from halting if a page is hidden after sending a
+    // requestAnimationFrame, set a timeout to ensure the change detection event is triggered
+    animationFrameTimeout = setTimeout(() => {
+        animationFrameTimeout = undefined;
+        triggerChangeDetection();
+    }, 500);
     updateMicroTaskStatus(zone);
 }
 function forkInnerZoneWithAngularBehavior(zone) {
```

**Comment by JiaLiPassion** [comment]
@JasonDickens , thank you for the detailed information, I will check this one.

**Comment by JiaLiPassion** [comment]
@JasonDickens , sorry for the very late reply. I am not sure it is a good apporach to update `ng_zone`, but I think you can `monkey patch` the native `requestAnimationFrame`.

1. add a new `zone_patch.ts`.
```
const nativeRaf = window.requestAnimationFrame;
window.requestAnimationFrame = function(callback: FrameRequestCallback) {
  if (document?.hidden) {
    return setTimeout(callback, 16);
  }
  return nativeRaf.apply(this, arguments);
}
```
2. import this file before `import zone.js` in the `polyfills.ts`.
