### ISSUE TITLE
Default encapsulation doesn't work after init in boostrapModule

### ISSUE THREAD

**Issue by splincode** [angular/angular#44325]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

```ts
const bootstrap = () =>
    platformBrowserDynamic().bootstrapModule(AppBrowserModule, {
        defaultEncapsulation: ViewEncapsulation.ShadowDom
    });
```

find `example-avatar`

![image](https://user-images.githubusercontent.com/12021443/144211355-5bb0a625-5c37-45e4-abd9-9930efc97fc2.png)

### Please provide the exception or error you saw

```true
I expect behavior to change encapsulation!
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 9
Node.js 16
npm 6
```

### Anything else?

ps: other question
why is there no property defaultChangeDetection in CompilerOptions?

![image](https://user-images.githubusercontent.com/12021443/144211737-f3879bf2-bc1f-44ff-b29e-72cd5d7a27eb.png)

**Comment by JoostK** [comment]
What _exact_ Angular version is this? There were fixes in #35534 that landed in Angular 9.1.0. Does this still reproduce using Angular 13 (please note that Angular 9 is not supported).

**Comment by splincode** [comment]
we have 9.1.12 version

**Comment by splincode** [comment]
@JoostK what about defaultChangeDetection?
I can somehow determine at the level

**Comment by JoostK** [comment]
> tK what about defaultChangeDetection?
> I can somehow determine at the level

I don't understand what you mean by `defaultChangeDetection`.

**Comment by JoostK** [comment]
Oh, it appears that `bootstrap` is wrapped into a closure, which presumably means that its called at a later point in time. That is a problem if the components have already been loaded at that point: loading of the components will have used the compilation configuration _before_ the bootstrap call reconfigured the jit options.

**Comment by JoostK** [comment]
I'd request that you provided a reproduction using latest Angular 13 so that we can investigate further. But TBH I doubt that this is something that we'll end up addressing.

**Comment by splincode** [comment]
@JoostK could you throw an exception that someone is trying to reset the value again?

**Comment by JoostK** [comment]
We already throw an exception when the configuration is actively being changed between bootstrap calls. However, if components have compiled _before_ any bootstrap then there won't be an error. We might be able to add something like that, but it would arguably be a breaking change.

**Comment by splincode** [comment]
@JoostK `I don't understand what you mean by defaultChangeDetection.` 

I mean

```ts
const bootstrap = () =>
    platformBrowserDynamic().bootstrapModule(AppBrowserModule, {
        defaultEncapsulation: ViewEncapsulation.ShadowDom,
        defaultChangeDetection: ChangeDetectionStrategy.OnPush
    });
```

```
@Component({
  selector: 'app',
  template: 'hello world'  // default OnPush
})
```

**Comment by JoostK** [comment]
> @JoostK `I don't understand what you mean by defaultChangeDetection.`
> 
> I mean
> 
> ```ts
> const bootstrap = () =>
>     platformBrowserDynamic().bootstrapModule(AppBrowserModule, {
>         defaultEncapsulation: ViewEncapsulation.ShadowDom,
>         defaultChangeDetection: ChangeDetectionStrategy.OnPush
>     });
> ```
> 
> ```
> @Component({
>   selector: 'app',
>   template: 'hello world'  // default OnPush
> })
> ```

That sounds like a feature request unrelated to this issue report. We don't have any intentions to widen the JIT configuration options, quite the opposite: these options don't work in AOT compilations (and never will) and we tend to prefer self-contained components.

**Comment by lazarljubenovic** [comment]
Hitting this issue with a freshly created app using the latest CLI.

```text
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.2.7
Node: 18.18.2
Package Manager: pnpm 8.9.2
OS: linux x64

Angular: 16.2.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.7 (cli-only)
@angular-devkit/build-angular   16.2.7
@angular-devkit/core            16.2.7 (cli-only)
@angular-devkit/schematics      16.2.7 (cli-only)
@angular/cli                    16.2.7
@schematics/angular             16.2.7 (cli-only)
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
```

**Comment by JeanMeche** [comment]
As stated above, these options only work with JIT (and not with AOT which is the default now).

**Comment by lazarljubenovic** [comment]
So it's not possible to set the default encapsulation with AOT?

**Comment by splincode** [comment]
![image](https://github.com/angular/angular/assets/12021443/09d217a5-3140-4a87-bb58-8fcc5060b940)
