### ISSUE TITLE
Docs footer uses <h3> out of order

### ISSUE THREAD

**Issue by twerske** [angular/angular#44338]
### Description

The footer uses h3 out of order and likely should switch to a table or other styling instead of header elements.
`Heading elements are not in a sequentially-descending order`

<img width="830" alt="Screen Shot 2021-12-01 at 2 32 47 PM" src="https://user-images.githubusercontent.com/15061394/144325129-f98464b3-a1f4-4549-beb8-6aaa69b3782e.png">

**Comment by noobyogi0010** [comment]
Hi @twerske 
I would like to work on this issue.
I will be switching the h3 tag into a table or another styling.

**Comment by twerske** [comment]
> Hi @twerske I would like to work on this issue. I will be switching the h3 tag into a table or another styling.

That'd be awesome! Can't wait to see the PR!
