### ISSUE TITLE
Multiple docs contrast ratios too low

### ISSUE THREAD

**Issue by twerske** [angular/angular#44337]
### Description

AIO contrast ratios should meet the minimum threshold, here are issues:

<img width="329" alt="Screen Shot 2021-12-01 at 2 29 54 PM" src="https://user-images.githubusercontent.com/15061394/144324632-0686bab6-0785-42d4-83fc-13a1a367d81d.png">
<img width="416" alt="Screen Shot 2021-12-01 at 2 41 52 PM" src="https://user-images.githubusercontent.com/15061394/144326057-e19ff360-4f27-450d-848a-db022008a7f4.png">
<img width="447" alt="Screen Shot 2021-12-01 at 2 41 39 PM" src="https://user-images.githubusercontent.com/15061394/144326066-0e6aea31-01ed-4936-98ee-20a2532c967f.png">
<img width="459" alt="Screen Shot 2021-12-01 at 2 41 30 PM" src="https://user-images.githubusercontent.com/15061394/144326071-a8a5eb11-68bd-4169-8f56-33021be26ace.png"
<img width="1242" alt="Screen Shot 2021-12-01 at 4 01 13 PM" src="https://user-images.githubusercontent.com/15061394/144333804-089ea931-96ee-4fa3-8cc0-6afe523715a5.png">
<img width="1242" alt="Screen Shot 2021-12-01 at 4 01 13 PM" src="https://user-images.githubusercontent.com/15061394/144334001-79b9ea48-8bef-456c-8a9a-4ba9a2d63c40.png">

**Comment by JiaHua-Zou** [comment]
Is this issue still available? I would like to fix this issue.
