### ISSUE TITLE
Docs announcement component needs more detailed context on close action

### ISSUE THREAD

**Issue by twerske** [angular/angular#44344]
### Description

The close icon on the announcement should read "Close {description of banner}", this is a reusable component so even though the banner ends on 12/4 this would still be useful to add.

<img width="1639" alt="Screen Shot 2021-12-01 at 3 35 33 PM" src="https://user-images.githubusercontent.com/15061394/144331595-d2de1701-0ceb-48e0-b1f4-60c8db2a5a1e.png">

**Comment by noobyogi0010** [comment]
Hey @twerske 
I would like to work on this issue if it's not taken up by someone else.
Thanks

**Comment by jessicajaniuk** [comment]
@noobyogi0010 You're welcome to work on this. Thanks for offering!

**Comment by ferrorenan** [comment]
Is anyone working on this right now? Would love to give it a shot.

**Comment by jessicajaniuk** [comment]
@ferrorenan Please do! We look forward to seeing your PR.

**Comment by ferrorenan** [comment]
I did a PR for the possible problem, in case I understood the problem correctly! PR: https://github.com/angular/angular/pull/47681

**Comment by jessicajaniuk** [comment]
Fixed by #47681
