### ISSUE TITLE
Angular Contributors page focus lost after clicking on a card

### ISSUE THREAD

**Issue by zarend** [angular/angular#44346]
### Description

Angular Contributors page using a pattern where cards are displayed which flip over when clicking on them. this creates a11y problems because focus is lost when flipping the card. Also, this is explicitly not allowed in the material design spec.

### What is the affected URL?

https://angular.io/about?group=Angular

### Please provide the steps to reproduce the issue

1. navigate to https://angular.io/about?group=Angular
2. press tab until focused on "Alan Agius" card
3. press space
4 (Alan's card flips over)
5. press space again
6. browser scrolls down on the page

### Please provide the expected behavior vs the actual behavior you encountered

this pattern of having cards that flip should not be used at all. Focus show not be lost after clicking on a card.

**Comment by aikidave** [comment]
Thanks for filing this, @zarend!

@jelbourn Do you have any thoughts on this?

**Comment by jelbourn** [comment]
@aikidave this is just a pretty common a11y bug (Emma, Zack, and I spent a couple hours before the holidays doing some manual a11y testing)

**Comment by zarend** [comment]
If I'm understanding correctly, okay to leave this as is until we make significant changes to this.

The actual fix would be to shop for a component or pattern thats more a11y-friendly and will better meet our other needs. I wouldn't spend a lot of time trying to make the flipping cards pattern work well, since this does not seem to be an a11y-friendly approach.

https://material.angular.io/components

**Comment by zarend** [comment]
AFAIK there is no specific requirement that this needs to be interactive. Some kind of list would seem like a reasonable improvement to me

**Comment by dario-piotrowicz** [comment]
@zarend what do you think then, is it can I look into trying something and put a PR together for it? :slightly_smiling_face:

**Comment by dario-piotrowicz** [comment]
@zarend I ended up giving it a try :grin: 

Feel free to give the PR a look if you want :grin:
