### ISSUE TITLE
Type narrowing doesn't work as expected in templates in Angular 13

### ISSUE THREAD

**Issue by th0r** [angular/angular#44353]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

Angular 12 allowed to use type-narrowing methods in component templates, but Angular 13 shows compilation error in the following case:
```ts
class SomeComponent {
  asyncData?: {foo: string};
  
  isDataLoaded(): this is Required<SomeComponent> {
    return Boolean(this.asyncData);
  }
}
```

```html
<ng-container *ngIf="isDataLoaded()">
  <!-- This compiled successfully in Angular 12 but throws compilation error in Angular 13 -->
  {{ asyncData.foo }}
</ng-container>
```
I've created a reproduction repo - just run `npm start` and you'll see compilation error.

### Please provide a link to a minimal reproduction of the bug

https://github.com/th0r/ng-13-templates-type-narrowing-bug

### Please provide the exception or error you saw

```
Error: src/app/app.component.html:2:14 - error TS2322: Type 'PageData | undefined' is not assignable to type 'PageData'.
  Type 'undefined' is not assignable to type 'PageData'.

2   <app-page [data]="pageData"></app-page>
               ~~~~

  src/app/app.component.ts:15:16
    15   templateUrl: './app.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```
Angular CLI: 13.0.4
Node: 14.17.3
Package Manager: npm 6.14.15
OS: darwin x64

Angular: 13.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cli                    13.0.4
@schematics/angular             13.0.4
rxjs                            7.4.0
typescript                      4.4.4
```

**Comment by flash-me** [comment]
Hi @th0r 

I think you have an typo there. I'm not sure its only in your issue here or also in your code.
Shouldn't this be 
```
<ng-container *ngIf="isDataLoaded()">
```

instead of 

```
<ng-container *ngIf="isDataLoaded">
```

? Without parentheses the `*ngIf` would check if such a method exists, but not the result of calling it.

cheers
flash ⚡

**Comment by JoostK** [comment]
This broke in #42882. The changes to the AST structure have introduced additional parenthesis into the type-check code, rendering the narrowing behavior of TypeScript inaccurate.

I'll be working on a fix.

**Comment by henrikdahl8240** [comment]
In which version of Angular will this finally be?

**Comment by JoostK** [comment]
@henrikdahl8240 It should be in 13.1.2

**Comment by henrikdahl8240** [comment]
@JoostK Thank you very much. It seems to work as it should.
