### ISSUE TITLE
Number input model change not triggered when number incremented using stepUp()

### ISSUE THREAD

**Issue by TMInnovations** [angular/angular#44367]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I extended a number input with a button that triggers the inputs stepUp() method to increment and decrement values.
The number-model's value doesn't change as the button gets clicked.

A naive addition in the "model-world" leads to wrong results => see plnkr

**Is there any way to trigger the input's change event in angular OR another way to trigger correct incrementation?**

Same bug/behavior as in angular.js:
https://github.com/angular/angular.js/issues/15146

### Please provide a link to a minimal reproduction of the bug

https://plnkr.co/edit/V9tmBbhr4VNG4FM5

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "core-js": "2.6.11",
    "rxjs": "6.5.4",
    "zone.js": "0.10.2"
```

**Comment by pkozlowski-opensource** [comment]
Converted plunker to stackblitz to use the latest Angular version (not that it matters the whole lot in this particular use-case): https://stackblitz.com/edit/angular-ivy-bmuecl

So what is going on here seems to be mismatch between your expectations and what is actually expressed in the code. In the linked example you've got `[value]="num"` which is equivalent to saying: "whenever `num` changes update the internal state of the input DOM control".

We should notice, though, that the `num` variable is _never updated_! The `inp.stepUp();` just changes the internal state of the input DOM element - but doesn't touch the  `num` variable

It is not clear to me what is your exact use-case but the code in the linked example is behaving as written :-)

**Comment by TMInnovations** [comment]
Sorry that I have to reopen the issue.
Thank you for the quick response!

You were right. I extracted the problem from a big private repo and was a bit "too fast". 
[value]="num" should be replaced by [(ngModel)]="num"

A new stackblitz example https://stackblitz.com/edit/angular-ivy-dgz1hg shows the problem I wanted to depict initially: https://stackblitz.com/edit/angular-ivy-dgz1hg
The Model gets updated by directly inputting sth via keyboard or changing the value with arrowUp and arrowDown keys.

**The Model doesn't get updated by calling stepUp() (=> Click +0.2 Button) although the view gets updated.**

I added a short demo to show that naively incrementing the model is a bad idea/alternative.

How can the inputs ngModelChange Event be triggered manually (as a better workaround)?

**Comment by pkozlowski-opensource** [comment]
@TMInnovations I've got an impression that there are 2 separate issues at play here:
* manipulating model vs. manipulating the DOM - Angular is all about model-driven UIs. As such we seldom do manual DOM manipulation. In you recent stackblitz you still increase value of the input DOM control. `ngModel` won't change anything here. I _believe_ that your use case should be coded as follows: https://stackblitz.com/edit/angular-ivy-xt3h9p (again, not sure as I'm missing lots of context here);
* floating point numbers representation in JavaScript - (ex.: `0.6000000000000001` "instead" of `0.6`) - this has nothing to do with Angular but the actual number representation in JavaScript (and many other programming languages) - see https://stackoverflow.com/questions/11695618/dealing-with-float-precision-in-javascript 

I'm happy to re-open the issue given that there are problems that we could fix on the Angular side - but so far things seem to behaving as designed.
