### ISSUE TITLE
node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration' - Angular 10

### ISSUE THREAD

**Issue by rakhikhengar** [angular/angular#44366]
Hello!

We are facing an issue as mentioned in the title. When we are doing ng build than its shows an error, see attached. We have tried all possible ways as already shared in GitHub / StackOverflow community. But still, we are facing the same error. 

We are unable to create the build. Please help us to get it resolved.

Here, are my package.json dependencies :
```
"dependencies": {
"@angular/animations": "~10.1.6",
"@angular/cdk": "^10.2.5",
"@angular/common": "~10.1.6",
"@angular/compiler": "~10.1.6",
"@angular/core": "~10.1.6",
"@angular/forms": "~10.1.6",
"@angular/material": "^10.2.5",
"@angular/platform-browser": "~10.1.6",
"@angular/platform-browser-dynamic": "~10.1.6",
"@angular/router": "~10.1.6",
"@angular/service-worker": "~10.1.6",
"@iplab/ngx-file-upload": "^3.1.1",
"angular-datatables": "10.0.0",
"angular-pipes": "^10.0.0",
"bootstrap": "^4.5.3",
"braintree-web": "^3.71.1",
"datatables.net": "^1.10.23",
"datatables.net-bs4": "^1.10.23",
"datatables.net-buttons": "^1.7.1",
"datatables.net-buttons-dt": "^1.7.1",
"jquery": "^3.5.1",
"jszip": "^3.6.0",
"laravel-echo": "^1.10.0",
"moment": "^2.29.1",
"ng-connection-service": "^1.0.4",
"ngx-bootstrap": "^6.1.0",
"ngx-chips": "^2.2.2",
"ngx-drag-scroll": "^9.0.0-beta.4",
"ngx-mask": "^11.1.4",
"ngx-pagination": "^5.0.0",
"ngx-pipes": "^2.7.5",
"ngx-select-dropdown": "1.5.0",
"popper.js": "^1.16.1",
"pusher-js": "^7.0.2",
"rxjs": "~6.6.0",
"sweetalert2": "^10.15.7",
"tslib": "^2.0.0",
"uuid": "^8.3.2",
"zone.js": "~0.10.2"
```
Here, are my tsconfig.json
```

/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": ["es2018", "dom"],
    "esModuleInterop": true,
    "skipLibCheck": true,
    "paths": {
      "@angular/*": ["./node_modules/@angular/*"]
    }    
  },
  "angularCompilerOptions": {
    "enableIvy": true
  },
}

```
We are using version as below : 

```
Angular CLI: 10.1.7
Node: 14.14.0
OS: linux x64
```

![image](https://user-images.githubusercontent.com/27191001/144607189-f2aeca30-5209-4738-bc30-80644109f08a.png)

Thanks!

**Comment by JoostK** [comment]
Hi, the errors originate in the `ng2-material-dropdown` library. It's unclear to me why this library is present as it's not listed among your dependencies; it might be used by some other library that you use.

Anyway, this error indicates that `ng2-material-dropdown` depends on a newer version of Angular than v10. `ɵɵFactoryDeclaration` was introduced in Angular 12.

**Comment by chriscarpenter12** [comment]
@JoostK How did you identify it was from `ng2-material-dropdown`? I don't use that package specifically, but am migrating a library from Angular 11 -> 12 and after running a build with `partial` I have these errors for every export.

**Comment by JoostK** [comment]
It's in the screenshot:

<img width="693" alt="image" src="https://user-images.githubusercontent.com/123679/145478846-079c4cff-faa5-4a5f-a677-71ae063eaa79.png">

Are you using your newly built library using `partial` mode in an Angular 12 app? These errors hint that it is being used in an Angular 11 app, which is not something you can do with an Angular 12 lib.

**Comment by rakhikhengar** [comment]
Hi @JoostK 

Just want to know that our issue gets resolved by adding custom version of ng2-material-dropdown in package.json 
see attached.
![image](https://user-images.githubusercontent.com/27191001/145753877-2fe40df6-bcd5-4d9b-bafa-4dc16d142b3f.png)


Thanks!

**Comment by danilolopesabreu** [comment]
> Hi @JoostK
> 
> Just want to know that our issue gets resolved by adding custom version of ng2-material-dropdown in package.json see attached. ![image](https://user-images.githubusercontent.com/27191001/145753877-2fe40df6-bcd5-4d9b-bafa-4dc16d142b3f.png)
> 
> Thanks!

Thanks, you help-me!
