### ISSUE TITLE
Angular 13.0.3 Type guards do not work

### ISSUE THREAD

**Issue by henrikdahl8240** [angular/angular#44373]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

In Angular 13, as you use a type guard in a template like *ngIf="myMammal.IsDog()", the compiler does not take the type the type guard resolves into consideration. It means, that inside the *ngIF body, myMammal has the type Mammal and not Dog.

In Angular 12 it worked perfectly.

Can it be fixed to work again?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 13.0.3
```

**Comment by JoostK** [comment]
It looks like something did indeed regress, as this was also reported yesterday in #44353. I'll follow up in that issue in the coming days, please follow that instead.
