### ISSUE TITLE
Binding to datastore attributes (data-*) within a template

### ISSUE THREAD

**Issue by matsko** [angular/angular#4438]
Currently doing this throws an error:

```html
<div [data-something]="property"></div>
```
Variations such as `data-something="{{ }}"` also do not work.

Are there plans to add support for `data-*` attributes?

**Comment by vicb** [comment]
see https://github.com/angular/angular/pull/2719

the consensus there was to have a `[data.something]="expr"`. 

@pkozlowski-opensource has the corresponding been created ?

**Comment by pkozlowski-opensource** [comment]
@vicb nope, sorry, forgotten, creating straight away.

@matsko you are trying to bind to an _attribute_ so you can make it work today by doing `[attr.data-foo]="exp"`

**Comment by pkozlowski-opensource** [comment]
Well, actually, we can keep this issue open - I will just rename it sligtly

**Comment by LaurentGoderre** [comment]
Thanks! That worked great for us!
