### ISSUE TITLE
Documentation on Routing is too sparse

### ISSUE THREAD

**Issue by SetTrend** [angular/angular#44397]
### Description

The documentation on Routing isn't explanatory.

It's too much focussing on some arcane example the author had in mind while writing instead of providing elementary explanation and education.

Most paragraphs leave the reader alone and confused behind bearing the – unanswered – questions: "Why should I do that??" or "What is that good for??"

### Examples

> Provide optional route parameters in an object, as in `{ foo: 'foo' }`:

Why?? Is this mandatory?

> However, with a child router, such as in the crisis center, you create new link array possibilities.

What kind of possibilities?? Why is the crisis center a child router??
<br/>

Humbly, and with all due respect, I consider the current state of this chapter a waste of precious reading time.

Please enhance.
<hr/>

### What is the affected URL?

https://angular.io/guide/router

### Please provide a screenshot if possible

![screenshot](https://user-images.githubusercontent.com/9283914/145127430-ddea80f1-6ae8-4e5d-b765-6b0710f0f4e0.png)

**Comment by atscott** [comment]
[My understanding is that the page](https://angular.io/guide/router) is meant as a quick cheat-sheet. Fuller explanations of router APIs are available in the tutorials: https://angular.io/guide/router-tutorial and https://angular.io/guide/router-tutorial-toh

**Comment by SetTrend** [comment]
@atscott:
I apprehend. Yet, shouldn't these pages still yield some value, though?

Does it make sense to publish confusing material?
