### ISSUE TITLE
angular 2.0 persistence - How can we help?

### ISSUE THREAD

**Issue by shairez** [angular/angular#444]
Is there an open project for angular 2.0 persistence?

How can we help to move the ideas of the following doc forward:
https://docs.google.com/document/d/1DMacL7iwjSMPP0ytZfugpU4v0PWUK0BT6lhyaVEmlBQ

?

**Comment by benjamingr** [comment]
That document looks awesome good work @jeffbcross !

**Comment by Alxandr** [comment]
As a supplement to "prior art" of that document, https://github.com/gritzko/swarm is also quite interesting with how it handles offline/online and realtime.

**Comment by jeffbcross** [comment]
We're working on updated designs and roadmaps, and will publish some proposals for feedback within the next couple of weeks, starting with the new HTTP library. 

(and Thanks @benjamingr!)

**Comment by jeffbcross** [comment]
(intentionally leaving this issue open)

**Comment by shairez** [comment]
Cool thanks @jeffbcross !

**Comment by naomiblack** [comment]
closing this since it's not really a bug or a feature.
