### ISSUE TITLE
Grammar issues

### ISSUE THREAD

**Issue by mcalmus** [angular/angular#44403]
### Description

packages/animations/browser/src/dsl/animation_timeline_builder.ts was modified by pull request #44203 to fix some spelling and grammar errors.

However, there is still a tense mismatch.

`Given that each of the keyframe styles are objects that prototypically inherits from the backFill object, this means that if a value is added into the backFill then it will automatically propagate any missing values to all keyframes.`

Should either be:

`Given that each of the keyframe styles is an object that prototypically inherits from the backFill object, this means that if a value is added into the backFill then it will automatically propagate any missing values to all keyframes.`

or:

`Given that keyframe styles are objects that prototypically inherit from the backFill object, this means that if a value is added into the backFill then it will automatically propagate any missing values to all keyframes.`

**Comment by khushi-2123** [comment]
Given that keyframe styles are objects that are prototypically inherit from the backFill objects, this means that if a value is added into the backFill then it will automatically propagate any missing value to all keyframes.

**Comment by aikidave** [comment]
Thanks, @mcalmus! This seems to be a good first issue for someone to address! Anyone interested in taking it on?
