### ISSUE TITLE
Missing LICENSE file in shipped packages from npm

### ISSUE THREAD

**Issue by mgaert** [angular/angular#44428]
### Description

If the command "ng build -c production" runs it will produce a text file called "3rdpartylicenses.txt" here there are all licenses included which are bundeld together. One thing is that there are some with no licenseText provided. Becuse there is no LICENSE file shippt to the npm package.

The package cdk provides it. The other like animations, common, core .. and aothers not.

### Proposed solution

ship the LICENSE file in the generatet tar file for the npm repository.

### Alternatives considered

no

**Comment by JeanMeche** [comment]
Looks like licences are shipped now in the npm packages. 
https://www.npmjs.com/package/@angular/core?activeTab=code
