### ISSUE TITLE
Improvement Request: Add Structural Information On Angular Key Terms

### ISSUE THREAD

**Issue by SetTrend** [angular/angular#44431]
## Description

Currently, I'm learning Angular. Reading through the documentation I noticed heavy use of terms like "application", "module", "feature modules", ... – whereas all these proprietary terms are not getting explained to the reader.

Thus, I'd like to suggest to add an introductory page to [Angular Routing](https://angular.io/guide/routing-overview), explaining …
a. these terms
b. their task
c. their general structure, and
d. their relationship among each other.

### Description Of Angular Key Terms

|Type|Task|Structure|Description|
|-|-|-|-|
|Application|…|…|…|
|Module|…|…|…|
|…|…|…|…|

### Relationship
![Hierarchy](https://user-images.githubusercontent.com/9283914/145627468-7c58bf70-b337-4548-a322-b0a335528212.png)

## What is the affected URL?

https://angular.io/guide/routing-overview

**Comment by SetTrend** [comment]
After reading the documentation thoroughly, I noticed that this general, architectural, introductory information has been put to the [*end* of the documentation](https://angular.io/guide/architecture).

For didactic reasons, I propose to move this information to the beginning of the documentation.

**Comment by mgechev** [comment]
@SetTrend thanks for the feedback. We're in a process of restructuring our introduction documentation and as part of the effort we'll take your input into our consideration.

I'll close the issue for now since we'll resolve it as part of a larger effort.
