### ISSUE TITLE
ngOnChanges not changing img [src]

### ISSUE THREAD

**Issue by sysmat** [angular/angular#44441]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

- html: `<img [src]="src" />`
- ts:
```typescript
export class ImageComponent implements OnInit, OnChanges {
@Input()
changeImg = false;
src = './assets/img/big.png';

ngOnChanges(_changes: SimpleChanges): void {
    if (this.changeImg) {
      this.src = './assets/img/small.png';
    } else {
      this.src = './assets/img/big.png';
    }
    console.log(this.src); 
  }
}
```
- error:  src is changed to small.png but not in the browser is still big.png
- even if forced with ChangeDetectorRef is not working

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 13.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.0
@angular-devkit/build-angular   13.1.0
@angular-devkit/core            13.1.0
@angular-devkit/schematics      13.1.0
@schematics/angular             13.1.0
rxjs                            7.4.0
typescript                      4.4.4
```

**Comment by sysmat** [comment]
using  `const img = (<HTMLImageElement>document.getElementById('img_1'));` and then set src it works in browser

**Comment by mlc-mlapis** [comment]
First of all you should start with a template reference variable `<img [src]="src" #myImg/>`. See https://angular.io/guide/template-reference-variables.

Direct parsing of the document using `getElementById` is not a recommended Angular way.

**Comment by JoostK** [comment]
Could you please share a reproduction? I tried to setup [a simple StackBlitz](https://stackblitz.com/edit/angular-ivy-rwsmjk?file=src%2Fapp%2Fapp.component.ts) but it does update the image's `src` as desired and that does trigger network requests to load the image.

@mlc-mlapis I don't think that was the point of the comment about `getElementById`; @sysmat was just showing that using native browser APIs this issue does not occur.

**Comment by sysmat** [comment]
@mlc-mlapis I try with that and only with native element casting it to HTMLImageElement then setting src attribute worked

**Comment by mlc-mlapis** [comment]
@JoostK, I know. It was just a hint of eliminating direct DOM parsing under Angular control. Nothing else.

**Comment by sysmat** [comment]
- img component is child 
```
--parent
  -- child
       -- img comp
```

- parent is not properly rendered in browser

**Comment by JoostK** [comment]
Please share a StackBlitz or Github repo with your reproduction, not just textual steps of your approach.

**Comment by sysmat** [comment]
I thoth that is so basic approced covered by unit test
