### ISSUE TITLE
Why ngIF is not working synchronously?

### ISSUE THREAD

**Issue by Vetagiri-Hrushikesh** [angular/angular#44454]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

```
  functionName() {
      this.progressBarValue = true    -------------------- **(1)**
    new Promise((resolve, reject) => {
          ----- CordovaPluginApi -----
    }).then((message) => {
      console.log(message);
      ------
      --------
      this.progressBarValue = true   -------------------- **(1)**
      } else {
           ----
          ------
      }

    });
  }
```

```
<mat-progress-bar *ngIf="progressBarValue">
```

Here the progress is not displaying when it hits **(1)** but displays when it hits **(2)**. I displays properly if there is no call for Cordova Plugin API. I tried **.detectChange()**, **.markChange()** and **NgZone()** nothing worked for me Can you please help me with this.

### Please provide the exception or error you saw

```true
I cannot see any exception. The mentioned progress bar is not displaying in the view.
```

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
