### ISSUE TITLE
Feature Request: Adding the option to ignore skipped animation callbacks

### ISSUE THREAD

**Issue by dario-piotrowicz** [angular/angular#44473]
### Which @angular/* package(s) are relevant/releated to the feature request?

animations

### Description

Trigger callbacks for disabled and skipped animations are still being executed, this may not always be the desired behavior and may not be what developers always want.

But it does seem to be the intended code's behavior so it is not a bug (as the users can still get useful information in skipped animation callbacks).

So I was just thinking that maybe we could want to provide an option to avoid the execution of such callbacks

### Proposed solution

I think it could be nice to add a new field to the [BrowserAnimationsModuleConfig](https://angular.io/api/platform-browser/animations/BrowserAnimationsModuleConfig), something like `skipNoopAnimationCallbacks` or something like that, so that the user has the option to skip those callback if they prefer to 

### Alternatives considered

This proposed feature is only for convenience, I don't think that those callbacks are a big hindrance and that they can be manually ignored by checking the event's `totalTime` or `disabled` property in the function itself

**Comment by dario-piotrowicz** [comment]
This is related to https://github.com/angular/angular/issues/42125 I just figured we could look into whether we would like such option :slightly_smiling_face: 

@4javier what do you think? does this sound like something that could be useful to you? :slightly_smiling_face:

**Comment by 4javier** [comment]
Hi @dario-piotrowicz 
My original ticket was submitted over an half-year ago, and sincerely I remember vaguely the situation the brought me to open it.
(there's a view's div where I dynamically show some components alternatively, and I want the animation of the exiting one to complete before the entering animation of the second starts)
I'm not sure I can test anything soon.
The thing that made me think after our last exchanges, was that probably if I really want to have the triggers separated for creation and destruction of the component, I should bound them to properties setup inside the respective hooks.
So maybe there's no need for any change.

**Comment by dario-piotrowicz** [comment]
@4javier thanks for the reply, I see, you're making a good point there :slightly_smiling_face: 

I thought this sounded nice and could be interesting (as a nice-to-have feature, not something absolutely necessary), but if even you don't think it sounds useful I may just close the issue :thinking: 

I guess I can keep the issue still open for another couple of days in case anyone chips in and can maybe says that this would actually be useful to them, if not I'll just close the issue :slightly_smiling_face::+1:
