### ISSUE TITLE
Bug Dialog in AngularJS@1.4.4

### ISSUE THREAD

**Issue by moacir-selinger** [angular/angular#4448]
Built a module to manage the loading templates for Modal Bootstrap. After upgrading my version of *angularjs@1.4.4*, to close a Modal, I can not open it.

**Simulation**: (http://embed.plnkr.co/3fLH5OaVQrnzalj8831U/preview)
Open your console in the browser, click the "Open Modal" button, it opened perfectly and the island was writing an element I scored. After open, close the Modal and try to open it again, see that it was no longer displayed. Note that the console the writing element is different from the first time it was opened.

**Note**: Change the version of *angularjs@1.4.3* and see that the problem does not happen.

**Comment by mgechev** [comment]
This repository is for Angular 2 related issues only. You can use https://github.com/angular/angular.js/issues.

**Comment by moacir-selinger** [comment]
Sorry, I will be enrolling there.

**Comment by mgechev** [comment]
It's ok, would you close this issue?

**Comment by fernandomoraes** [comment]
I have ta same problem...

**Comment by mgechev** [comment]
@fernandomoraes as I mentioned above, this repository is for Angular 2 related issues only. This occurs in 1.x.

**Comment by fernandomoraes** [comment]
oh, sorry for my mistake.
