### ISSUE TITLE
Feature Request: A new abstract class that allows to specify the appropriate type for FormGroup

### ISSUE THREAD

**Issue by s-duu-jp** [angular/angular#44491]
### Which @angular/* package(s) are relevant/releated to the feature request?

      @angular/forms

### Description

If you currently specify your own type for FormGroup, the value of those properties is specified by `AbstractControl` as `value: any`.

[You can check here](https://stackblitz.com/edit/angular-ivy-qupgqb?file=src%2Fapp%2Fapp.component.ts) (stackblitz)
![Screenshot from 2021-12-16 00-19-43](https://user-images.githubusercontent.com/70936215/146215322-44c030d0-4f6b-45b3-ac5b-fbb714bf5cc5.png)

However, `Value: any` often compromises the intellisense as TypeScript therefore The `Value` must define the correct type defined in the interface.

### Proposed solution

Implementation of new `AbstractControlValue<T>`

### Alternatives considered

No response

**Comment by dylhunn** [comment]
See comment: https://github.com/angular/angular/pull/44492#issuecomment-995028009
