### ISSUE TITLE
forms: typed forms migration does not run on lazy-loaded modules

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#44524]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

The migration available in v13.2.0-next.1 fails to pick up forms in lazy-loaded modules in a CLI app.

The repo provided as reproduction is a simple CLI app, with a lazy-loaded module containing a component with a FormControl (added in the second commit).

steps:
```
git clone https://github.com/cexbrayat/typed-forms.git
npm i
ng update @angular/core --migrate-only migration-v14-typed-forms
```

### Please provide a link to a minimal reproduction of the bug

https://github.com/cexbrayat/typed-forms

### Please provide the exception or error you saw

```true
❯ ng update @angular/core --migrate-only migration-v14-typed-forms
The installed Angular CLI version is outdated.
Installing a temporary Angular CLI versioned 13.1.2 to perform the update.
✔ Package successfully installed.
Using package manager: 'npm'
Collecting installed dependencies...
Found 23 dependencies.
** Executing 'migration-v14-typed-forms' of package '@angular/core' **

❯ Experimental migration that adds <any>s for Typed Forms.
  Migration completed.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.0-next.1
Node: 16.13.1
Package Manager: npm 6.14.14
OS: darwin x64

Angular: 13.2.0-next.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.0-next.1
@angular-devkit/build-angular   13.2.0-next.1
@angular-devkit/core            13.2.0-next.1
@angular-devkit/schematics      13.2.0-next.1
@schematics/angular             13.2.0-next.1
rxjs                            7.4.0
typescript                      4.5.4
```

### Anything else?

This happened in every application I tried to run the migration. I think it even sometimes doesn't find components in modules, but I struggled to reproduce in a bare application.

**Comment by dylhunn** [comment]
Thank you for this great reproduction @cexbrayat, we really appreciate it! This only affected external migrations (not google3 migrations), so we might not have caught it in time. This will be fixed in #44881.
