### ISSUE TITLE
Use '**' wildcard as catch-all to lazy loaded module with child routes

### ISSUE THREAD

**Issue by tmk1991** [angular/angular#44527]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

This issue needs to be re-opened. https://github.com/angular/angular/issues/13848

this fails (module is loaded, no component is shown for url /):

{
  path: '**',
  loadChildren: './+content/content.module#ContentModule'
}
setting to constant value works (module loaded, component shown for url /content)

{
  path: 'content',
  loadChildren: './+content/content.module#ContentModule'
}
prefixing with a path and a catch-all fails (error message Promise rejection: Cannot match any routes. URL Segment: 'content/foo' for url /content/foo):

{
  path: 'content/**',
  loadChildren: './+content/content.module#ContentModule'
}
setting to empty string works (module loaded, component shown):

{
  path: '',
  loadChildren: './+content/content.module#ContentModule'
}

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.2.13
Node: 16.13.1 (Unsupported)
Package Manager: npm 8.1.2
OS: darwin x64

Angular: 12.2.13
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.13
@angular-devkit/build-angular   12.2.13
@angular-devkit/core            12.2.13
@angular-devkit/schematics      12.2.13
@angular/fire                   6.1.5
@nguniversal/builders           12.1.3
@nguniversal/express-engine     12.1.3
@schematics/angular             12.2.13
rxjs                            6.5.5
typescript                      4.3.5
```

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

Based on the description, it appears that the scenario that doesn't work is the `'**'` with a `/` route but it does appear to work in this demo
https://stackblitz.com/edit/angular-zvfrs8?file=src%2Fapp%2Fapp.component.html
Even with that said, `**` is meant to consume all remaining segments in the URL so it's almost surprising that this works at all. You should instead do the following:
```
// app routing
{
path: '',
loadChildren: './+content/content.module#ContentModule'
}
// content module
{
path: '**',
loadChildren: ContentComponent
}
```
demo: https://stackblitz.com/edit/angular-zvfrs8-hkzgds?file=src%2Fapp%2Forders%2Forders-routing.module.ts
