### ISSUE TITLE
LanguageService does not recognize directive attributes on ng-template

### ISSUE THREAD

**Issue by kemsky** [angular/angular#44525]
### Which @angular/* package(s) are the source of the bug?

language-service

### Is this a regression?

No

### Description

We are using `ng-template` as pure data containers, because it does not produce unwanted dom nodes (there was feature request sometime ago to allow nodes that are not rendered).
<img width="908" alt="image" src="https://user-images.githubusercontent.com/3826972/146589072-4b00a2d2-ef9b-428e-b3f2-78cea5d3c8d5.png">

### Please provide the exception or error you saw

```true
Everything compiles but language service does not recognize this scenario.

```
<img width="425" alt="image" src="https://user-images.githubusercontent.com/3826972/146589454-3a82ed21-67ff-42a7-96cd-995a21a326cf.png">

### Please provide the environment you discovered this bug in (run `ng version`)

```true
OS: win32 x64

Angular: 13.1.1
... animations, cdk, common, compiler, compiler-cli, core
... elements, forms, language-service, material
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.1
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
rxjs                            7.4.0
typescript                      4.5.4
```

**Comment by JoostK** [comment]
Could you please check if this is the same as #44453, i.e. do you have the `Use legacy View Engine language service.` option enabled?

**Comment by kemsky** [comment]
@JoostK, I'm using IntellijIdea, there are no settings that mention `Use legacy View Engine language service` however I tried in VSCode and it does not show any errors. Is there any way to check that Intellij uses this flag?

**Comment by JoostK** [comment]
Which version of IntelliJ? JetBrains has their own analysis pipeline, I'm not even sure if they're using the language-service at all.

**Comment by atscott** [comment]
Closing since the issue does not appear in VSCode, which is where we publish our language service extension. As @JoostK mentioned, JetBrains has their own language service that they manage. Please open an issue with them instead.
