### ISSUE TITLE
I want to get a fully compiled Angular ({compilationMode: "full"})

### ISSUE THREAD

**Issue by aswezxqcc** [angular/angular#44521]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

In my project, we used the micro-front-end mode of the externals structure, which required an angular program to use the aot mode.
When using ng12, we can use the NGCC converted program to package again to get the available package;
After upgrading ng13, because ng13 only released the middle layer media at NPM repository（{"compilationMode": "partial"}）, it was impossible to obtain the required packages and could not complete the upgrade work;
I just want to get an angular program that can be used directly in the browser；
Original：
在我的项目中，使用了externals结构的微前端模式，需要使用到aot模式的angular程序。
使用ng12时，可以利用ngcc转化后的程序再次打包获得可用的程序包；
在升级ng13之后，由于ng13在npm只发布了中间层的介质，导致无法获取到需要程序包，而无法完成升级工作；

### Please provide the exception or error you saw

```true
For example ：PlatformLocation.ɵfac
compilationMode = partial ：
  PlatformLocation.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "13.1.1", ngImport: i0, 
  type: PlatformLocation, deps: [], target: i0.ɵɵFactoryTarget.Injectable });
compilationMode = full(i hope)：
  PlatformLocation.ɵfac = function PlatformLocation_Factory(t) {
   return new (t || PlatformLocation)();
 };
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.2
Node: 14.18.1
Package Manager: yarn 1.19.1
OS: win32 x64

Angular: 13.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
ng-packagr                      13.0.3
rxjs                            7.4.0
typescript                      4.4.4
```

**Comment by JoostK** [comment]
Libraries will not ship using full compilation mode to NPM.

ngcc was an intermediate solution to allow using ViewEngine-built packages with the Ivy compiler. For Ivy this has been replaced with partial compilation, which requires a linking step to become fully AOT.

The typical setup to achieve linking is to configure a loader that runs the linker's Babel plugin, [as documented here for Webpack](https://angular.io/guide/creating-libraries#consuming-partial-ivy-code-outside-the-angular-cli). Alternatively, you could use the [Babel CLI binary](https://babeljs.io/docs/en/babel-cli) and some configuration to obtain fully AOT compiled library packages.

I'd be happy to provide more information if you get stuck, but shipping fully compiled code to NPM is not something that we'll want to do.
