### ISSUE TITLE
Error when loading module to another module

### ISSUE THREAD

**Issue by VincentThomas06** [angular/angular#44530]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

I have a issue with the angular compiler. I can't seem to use my own components. I have a components folder where all the dumb* components are in every component in that folder i have a module. The file structure is like this.

components/
  - no-data/
    - [ no-data component here ]
    - [ module for no-data here ]

pages/
  - dashboard/
    - [ dashboard component here ]
    - [ dashboard module here ]

I would like to use the no-data component in the dashboard component, i did this by importing the no-data module to the dashboard module but its not working!

Here are the files that are needed.

app/private/pages/dashboard/dashboard.module.ts
```
import { Routes } from '@angular/router';
import { NgModule } from '@angular/core';
import { DashboardComponent } from './dashboard.component';
import { NoDataModule } from '@private/components/no-data/no-data.module'; // <-- this one!!
import { RouterModule } from '@angular/router';

const routes: Routes = [
  {
    path: '',
    component: DashboardComponent,
  },
];

@NgModule({
  declarations: [DashboardComponent],
  imports: [RouterModule.forChild(routes), NoDataModule],
})
export class DashboardModule {}

```

app/private/components/no-data/no-data.module.ts
```
import { NoDataComponent } from '@private/components/no-data/no-data.component'; // <-- This is the component i want to use
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

@NgModule({
  imports: [CommonModule],
  declarations: [NoDataComponent],
  exports: [NoDataComponent],
})
export class NoDataModule {}

```

I don't know what i'm doing wrong, if someone can help me that would be great! I'm relatively new so maybe i'm just stupid

### Please provide a link to a minimal reproduction of the bug

Clone this github repo: https://gitlab.com/VincentThomas/passwrd-website

**Comment by VincentThomas06** [comment]
Forgot to include the versions:

Angular CLI: 13.0.3
Node: 16.13.0
Package Manager: npm 8.1.0
OS: win32 x64

Angular: 13.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1300.3
@angular-devkit/build-angular       13.0.3
@angular-devkit/core                13.0.3
@angular-devkit/schematics          13.0.3
@angular/cdk                        13.0.3
@angular/cli                        13.0.3
@angular/fire                       7.2.0
@angular/material                   13.0.3
@angular/platform-browser-dynamic   13.0.3
@schematics/angular                 13.0.3
rxjs                                7.4.0
typescript                          4.4.4

**Comment by JoostK** [comment]
Please always include the actual error you're seeing in the issue report, as that is usually a big hint in what the issue could be. Also, the reproduction didn't quite work, I had to add some dependencies to get it to compile.

The actual error I'm seeing is the following:

```
Error: src/app/private/pages/dashboard/dashboard.component.html:28:9 - error NG8001: 'app-no-data' is not a known element:
```

Even though `DashboardModule` properly imports `NoDataModule` which exports `NoDataComponent`, this error occurs because the source file that declares `DashboardModule` is not included in the compilation, and therefore not seen by the compiler at all. This can be confirmed by looking at the set of files in the program with the help of the TypeScript compiler:

```
./node_modules/.bin/tsc -p tsconfig.app.json --listFiles | grep src/app/
```

You'd have to import `DashboardModule` somewhere to include it in the compilation, which resolves the problem.

**Comment by VincentThomas06** [comment]
Thank you! This was my first github issue so thanks for the quick and positive answer!
