### ISSUE TITLE
Import Parent Module in Child Module

### ISSUE THREAD

**Issue by KalpanaPagariya** [angular/angular#44537]
### Description

We have requirement where parent module component is used in parent module and its child Modules.

Is it good practice to import parent module in child module? Nothing is mentioned about this in Angular docs.
Curious to know if this is good practice.

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
