### ISSUE TITLE
Changelog for version 13.0.0 is missing

### ISSUE THREAD

**Issue by YegorBobrovski** [angular/angular#44548]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Angular 13.0.0 version's changelog is missing in the changelog.md file. Seems to be accidentally removed by 532d7d436fa1e7a1ea97ea3288f0f6c6c4e34b71

**Comment by JoostK** [comment]
This is being fixed in #44518.

**Comment by YegorBobrovski** [comment]
Hmm, that PR will also restore changelog for "13.1.0-next.0"...
