### ISSUE TITLE
new Date().getMonth();

### ISSUE THREAD

**Issue by chprsk** [angular/angular#44546]
### Which @angular/* package(s) are the source of the bug?

common, core, language-service

### Is this a regression?

Yes

### Description

While using new Date().toLocaleDateString() for december 22 2021 it is giving 12/22/2021. But new Date().getMonth(); is printing 11. It is resulting limbo.

**Comment by JoostK** [comment]
This is a native browser API and not Angular related. `Date.getMonth` is 0-based, [as you can find here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth),
