### ISSUE TITLE
Does ngOnChanges() trigger when @Output property changed?

### ISSUE THREAD

**Issue by thirumanidev** [angular/angular#44559]
### Description

https://angular.io/guide/glossary#lifecycle-hook
As per this document, ngOnChanges() method can trigger for both @Input and @Output properties, but.

I tested the ngOnChanges() method while changes occurring for the @Input and @Output properties.
The ngOnChanges() method triggers well in Child component if @input properties changed, but nothing happened on both Parent & Child components' ngOnChanges() method while changes occurring in @Output properties.

### What is the affected URL?

https://angular.io/guide/glossary#lifecycle-hook

### Parent Component
```
ngOnChanges(): void {
  console.log("ngOnChanges from Parent");
}
child1OutputValue!: string;
  child1OutputPrint(event: any) {
  console.log(event);
  this.child1OutputValue = event;
}
```

`<app-child1 (child1Output)="child1OutputPrint($event)"></app-child1>`

### Child Component
```
ngOnChanges(): void {
  console.log("ngOnChanges from Child");
}
@Output() child1Output = new EventEmitter();
outputPass() {
  this.child1Output.emit('Test output 123');
}
```
`<button (click)="outputPass()">Output</button>`

### Please provide the expected behavior vs the actual behavior you encountered

As per the official document, I expected the ngOnChanges() method triggers on either Parent's or Child's. But neither triggered.

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/55808656/147287008-ad7959b8-a58a-403d-87a1-63a9fe75fd4a.png)

**Comment by AlirezaEbrahimkhani** [comment]
I think you got it wrong because it is written in the documentation of the Angular section of the Component lifecycle that ngOnChange respond when Angular sets or resets data-bound input properties. The method receives a SimpleChanges object of current and previous property values and it Called before ngOnInit() (if the component has bound inputs) and whenever one or more data-bound input properties change.

Read [this](https://angular.io/guide/lifecycle-hooks) section of the documentation for more information

**Comment by thirumanidev** [comment]
Hi @AlirezaEbrahimkhani 
My question is "Does ngOnChanges() get triggered when @Output property changed?"

**Comment by AlirezaEbrahimkhani** [comment]
Hi @thirumanidev
As I saw and experienced ngOnChange triggered only when `@Input` property changed

**Comment by thirumanidev** [comment]
Yeah, I'm also suspecting the same only, then why there is documented as the ngOnChange will getting triggered for @ouput also?

**Comment by mlc-mlapis** [comment]
@thirumanidev Yep, it's a mistake.

> ngOnChanges: When an input/output binding value changes.

**Comment by AlirezaEbrahimkhani** [comment]
@thirumanidev 
Yes you are right this is a mistake in the Angular official documentation.

**Comment by DaSchTour** [comment]
> @thirumanidev Yep, it's a mistake.
> 
> > ngOnChanges: When an input/output binding value changes.

I think that's not a mistake. It would change, if the biding to the output would change. So if you have change the function/method that is bound to a given output. Which is probably not done very often.

But it does not say anything about ngOnChanges beeing called if the output emits an event.

**Comment by thirumanidev** [comment]
Can you anyone tell this, is it a mistake or not? Why this ticket has been closed without a proper reason?
