### ISSUE TITLE
Route Guards - Evaluation different from Documentation - question

### ISSUE THREAD

**Issue by avrim-tr** [angular/angular#44554]
### Description

Hey,

I saw from this [PR](https://github.com/angular/angular/issues/28082 ) that the order of execution of canActivate and canActivateChild is not as is written in DOCs

After This [fix](https://github.com/angular/angular/commit/2ff5bfe139b089d0a89f128c8f4bda0a46343bb8) I was sure that the angular's execution is as written in [Docs](https://angular.io/guide/router-tutorial-toh#milestone-5-route-guards), however, after running the example attached in that doc, at : 
https://stackblitz.com/run?file=src/app/app-routing.module.ts
I tested like this:
Attached here some code example from my test:
{
    path: 'Admin',
    component: AdminComponent,
    canActivate: [AuthGuard],
    canActivateChild: [AuthGuard],
    children: [
      {
        path: 'innerAdmin',
        canActivateChild: [AuthGuard1],
        children: [
          { path: 'crises', component: ManageCrisesComponent },
          { path: 'heroes', component: ManageHeroesComponent },
          { path: '', component: AdminDashboardComponent },
        ],
      },
    ],
  }

---> Above, we have parent route: Admin, which has one child, innerAdmin, and that has 3 children.
Note for this:
"Admin" has  canActivateChild: [AuthGuard],
"innerAdmin" has  canActivateChild: [AuthGuard1],

Both AuthGuard and AuthGuard1 just print to console something and return true

Take these 2 cases:

case 1:
If you were at route that is NOT at Admin at all, and suppose you go to 
Admin/innerAdmin/crises
Then, for canACtivateChild, AuthGuard is used first and then AuthGuard1

case2:
If you were at Admin/innerAdmin/crises and go to Admin/innerAdmin/heroes, via relative routing, then 
 for canACtivateChild, AuthGuard1 is used first and then AuthGuard

Why dose it happen? it is as not as written in the docs
https://angular.io/guide/router-tutorial-toh#milestone-5-route-guards

 

### What is the affected URL?

https://angular.io/guide/router-tutorial-toh#milestone-5-route-guards

### Please provide the steps to reproduce the issue

Provided at Description section

### Please provide the expected behavior vs the actual behavior you encountered

Provided at Description section

**Comment by atscott** [comment]
The order described in the documentation is both accurate and not. `canActivateChild` guards run for _each_ route being activated.

Example config:
```
[
        {
          path: 'admin',
          canActivateChild: [Guard1],
          component: BlankCmp,
          children: [
            {
              path: 'innerAdmin',
              canActivateChild: [Guard2],
              component: BlankCmp,
              children: [{path: 'crises', ...}, {path: 'heroes'}]
            }
          ]
        }
   ]
```

When navigating to `admin/innerAdmin/crises`, the execution is
1. `Guard1` executes for the activation of `'innerAdmin'`. 
2. `Guard2` and `Guard1` _both_ activate for `crises`. First `Guard2`, then `Guard1`

code reference: https://github.com/angular/angular/blob/8ebc946c0e7bf80d26ec8268acb4ff0af9e5c34a/packages/router/src/operators/check_guards.ts#L135-L136

The same execution of the guards in step 2 would hold true when using relative navigation between `crises` and `heroes`. 

[stackblitz example](https://stackblitz.com/edit/angular-ivy-router-guards-xue5yb?file=src%2Fapp%2Fapp.module.ts)

**Comment by aikidave** [comment]
Thanks, @avrim-tr! And thanks for the explanation, @atscott!

I've labeled this issue as a feature so we can prioritize updating and addressing it in the documentation.

**Comment by avrim-tr** [comment]
Thanks @atscott ! for canActivateChild,it dose activate per inner child, as of Guard1 in the example you attached.
What about canActivate? for such of our case I tested it and it is not called per inner child, is it ok?

**Comment by atscott** [comment]
@avrim-tr That's right. `canActivate` relates only to a particular `Route`.

`canActivate`: "Can I activate this Route?"
`canActivateChild`: "Can I activate children of this route? What about this particular child? How about this other child (when there are many)?" etc

**Comment by avrim-tr** [comment]
Thanks @atscott, but my question was not accurate :), I wanted to ask about inner children depth of routing : when you talked about canActivateChild, it is not only for direct children but also children's children and children's children's children, and so on....
What about this case for example:
Assuming we try to activate such path:  root/child-1/child-2/.../child-n 
Assuming **only** root has some canActiavateChild, others has no guards at all..., root is parent of child-1, child-1 is parent of child-2,.... child-n-1 is parent of child-n then, assuming I will try to go "root/child-1/child-2/.../child-n", then that canActiavateChild of root will be called n times.
On the other hand, same case above, instead of canActiavateChild, we have canActivate attached on root **only**, then, it is called once.

As in the example you provided, Guard1 for canActiavateChild , is called 3 times
If I try to go to : 
innerAdmin/crises -->
for "innerAdmin" -->  invocation Nu 1
for "" --> invocation Nu 2
for "crises" --> invocation Nu 3

But Guard1 for canActivate  is called once.

This part was quite surprise :)

**Comment by atscott** [comment]
@avrim-tr I'm not sure I understand. A given route is only activated once so its `canActivate` guards would only activate once. `canActivateChild` can activate more than once because it runs for each descendent route being activated during the navigation. This is the same as what I said above so I'm not sure if this clarifies things at all.

**Comment by avrim-tr** [comment]
@atscott, in your first example, when we navigated to "admin/innerAdmin/crises", I did not know that Guard1 canActiavedChild, would run twice: one time for path 'innerAdmin' **and second for 'crises' which is descendent of innerAdmin**
In the documents, I only thought that canActiavedChild should run for **direct children only**

**Comment by atscott** [comment]
@avrim-tr Yes, the documentation is incorrect. The code I linked to above does `path.slice(0, path.length - 1)` for each route being activated which means it grabs the `canActivateChild` from each of the ancestors. This code hasn't changed for several years so I'm guessing it has just always been like this and the documentation was just incorrect.

**Comment by avrim-tr** [comment]
@atscott, thanks a lot! because till now I was not sure about if I understood or not.
Also, about what you said in last comment, "canActivate" would run only once, right?

**Comment by atscott** [comment]
> thanks a lot! because till now I was not sure about if I understood or not.

No problem! I don't think I understood it either until I looked at the code carefully and made that example.

> Also, about what you said in last comment, "canActivate" would run only once, right?

Yes, that's correct.
