### ISSUE TITLE
route param is not emit the last value for withLatestFrom operator 

### ISSUE THREAD

**Issue by wizardnet972** [angular/angular#44552]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

When I subscribe to `Subject` and want to get the last value of the route `params` from `withLatestFrom` operator, I get the previous value although the last value is emitted.

I switch between the params using buttons:   
```
<button [routerLink]="'/foo/1'">1</button>
<button [routerLink]="'/foo/2'">2</button>
...
const routes = [{ path: 'foo/:id', component: FooComponent }];
```
And getting the `:id` by `pluck`: `id$ = this.route.params.pipe<number>(pluck('id'));`

Then in `ngOnInit` I subscribe to `id$` get when I click on the buttons, it works great.  In the console I get the correct `id` value:
```
  ngOnInit() {
    this.id$.subscribe((id) => {
      console.log({ id });
    })
);
```

But when I trigger the `Subject` then `id$` was changed I don't get the correct id:

```
  load$ = new Subject();

  loadEffect = this.load$.pipe(
    withLatestFrom(this.id$), 
    tap(([, idRoute]) => {
      console.log({ idRoute }); // <----- this is not the correct id!!
    })
  );
```

And the results I get in the console are not match:
```
id: 1
idRoute: 2
..
id: 2
idRoute: 1
...
```

How to solve this?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-bnnqjm?file=src%2Fapp%2Ffoo.component.ts

### Please provide the exception or error you saw

```true
There is no exception.
```

**Comment by destus90** [comment]
Wondering why `withLatestFrom` didn't give the correct value while `switchMap` fixes the issue.
https://stackblitz.com/edit/angular-ivy-nbmgbm?file=src%2Fapp%2Ffoo.component.ts

**Comment by JoostK** [comment]
This is not an Angular router issue; it's an issue with the ordering in which events are emitted.

```ts
id$ = this.route.params.pipe<number>(pluck('id'));

  load$ = new Subject();

  loadEffect = this.load$.pipe(
    withLatestFrom(this.id$),
    tap(([, idRoute]) => {
      debugger;
      console.log({ idRoute });
    })
  );

  constructor(private route: ActivatedRoute) {}

  ngOnInit() {
    this.id$.subscribe((id) => {
      console.log({ id });

      this.load$.next(null);
    });

    this.loadEffect.subscribe();
  }
```

The subscription in `ngOnInit` is the first subscriber to `this.id$`, so it will receive a notification first. It emits into `this.load$` synchronously, _before_ the subscriber within the `this.loadEffect` subscription has received the notification. Hence, the `withLatestFrom` subscriber has not yet received the new value.

If you move the `this.loadEffect.subscribe()` call _before_ the subscription to `this.id$` then it works as you expect.
