### ISSUE TITLE
Incorrect DatePipe year formatter

### ISSUE THREAD

**Issue by ZBAGI** [angular/angular#44569]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

`DatePipe` has incorrect `Y`, `YY`, `YYY` and `YYYY` formatter for dates that first thursday happens to be in previous year.
All of the year formats listed above uses [`weekNumberingYearGetter`](https://github.com/angular/angular/blob/fe691935091aaf7090864c8111a15f7cc7e53b6c/packages/common/src/i18n/format_date.ts#L486) that internally uses [`getThursdayThisWeek`](https://github.com/angular/angular/blob/fe691935091aaf7090864c8111a15f7cc7e53b6c/packages/common/src/i18n/format_date.ts#L434) which causes year to be shifted back before parsed to string.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.4
Node: 16.13.0
Package Manager: npm 8.1.4
OS: win32 x64

Angular: 13.0.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cli                    13.0.4
@angular/flex-layout            13.0.0-beta.36
@schematics/angular             13.0.4
rxjs                            7.4.0
typescript                      4.4.4
```

**Comment by JoostK** [comment]
This sounds like a duplicate of #44350, which notes that you'll probably want `yyyy`, not `YYYY`. But I'm not entirely certain as there isn't any actual vs expected behavior cases that would help confirm this.

**Comment by ZBAGI** [comment]
I wasn't aware of `week-numbering year` special behavior. Switching to `yyyy` seems to solve issue.
