### ISSUE TITLE
In dart extending a lifecycle class like `OnInit` does not register the hook.

### ISSUE THREAD

**Issue by rkirov** [angular/angular#4457]
It is very easy to mistakenly write `class MyComponent extends OnInit` instead of `class MyComponent implements OnInit` and currently we won't call the hook in the first case.

**Comment by kegluneq** [comment]
This is currently working as intended, there's even a [unit test](https://github.com/angular/angular/blob/master/modules_dart/transform/test/transform/directive_processor/all_tests.dart#L275) for this behavior (and [here](https://github.com/angular/angular/blob/master/modules_dart/transform/test/transform/directive_processor/superclass_lifecycle_files/soup.dart) is the file that test operates on).

But that doesn't mean we can't change the intention.

@vsavkin or @yjbanov, do you remember why we did not allow `extends`? I know we wanted to ensure that people were explicit about opting in to lifecycle events, so inheriting from superclasses is out, but we could allow `extend`ing these pretty easily.

**Comment by yjbanov** [comment]
I think for consistency we should make people implement them. Perhaps the transformer should emit a warning?

**Comment by kegluneq** [comment]
Works for me - @rkirov , what's your take?

**Comment by rkirov** [comment]
This came straight from a confused user. It is very frustrating when you expect a framework to call a callback and it doesnt. There was no way for the user to debug it.

If we are shooting for consistency, we should at least throw in the transformer when lifecycle hooks are `extended` and hence ignored by angular.

**Comment by mhevery** [comment]
I would vote to make it an error. There is no reason to extend it. Maybe put a throw in the constructor of the interface to throw?
