### ISSUE TITLE
A Programmatic Animations guide is missing in aio

### ISSUE THREAD

**Issue by dario-piotrowicz** [angular/angular#44588]
I believe that the animations aio guides are missing a section about programmatic animations, nothing there explains how to create and use an `AnimationPlayer` (via `AnimationBuilder` and `AnimationFactory`) to programmatically create animations.

Some minimal information about it can be found in the [`AnimationBuilder`'s API Docs Usage Notes](https://angular.io/api/animations/AnimationBuilder#usage-notes), but it is very minimal and in my opinion not complete/correct as it sort of suggests that only `animate()` can be used in the `AnimationBuilder#build` method, which is not the case (`group()`, `query()`, `stagger()`, etc... can be used too)

Currently the animations guides comprise of the following guides/pages:
 - Introduction
 - Complex Sequences
 - Reusable Animations
 - Route Transition Animations

I'm suggesting that a new guide/page (called "Programmatic Animations" or something like that) could be added
to explain how to programmatically create and play animations (with explanations as to why going such route, examples, etc...).

(__Note:__ the guide/page should also make clear that programmatic animations are not the suggested use of animations and that they should be used just when needed and that the standard ones via the `animations` field in the `Component` decorator should generally be preferred)

Also the animations live examples should get an additional example of programmatic animations.

**Comment by dario-piotrowicz** [comment]
@jessicajaniuk please let me know what you think :slightly_smiling_face: 

(needless to say I would love to help out in writing this guide if we think it would be a worthwhile addition :smile:)

**Comment by mgechev** [comment]
Hey @dario-piotrowicz, thank you for opening this feature request! There's definitely a gap in the documentation for these APIs. Since animations are not on the immediate backlog for the docs team and we did not collect a sufficient number of votes, I'll close the issue for now and reevaluate in the future.
