### ISSUE TITLE
docs: No longer valid link in https://angular.io/guide/npm-packages

### ISSUE THREAD

**Issue by yuriybelike** [angular/angular#44583]
### Description

The "Library support" link in the blue "Library developers" alert in https://angular.io/guide/npm-packages#:~:text=Library%20Support,. no longer points to anything useful. It is redirected to the repo main URL.

### What is the affected URL?

https://angular.io/guide/npm-packages#packagejson

### Please provide the steps to reproduce the issue

1. Go to https://angular.io/guide/npm-packages
1. Scroll down to "package.json" section, to the blue alert at the end
1. Click on "Library Support"
1. Be navigated to main page of the Angular CLI repo

### Please provide the expected behavior vs the actual behavior you encountered

Expected: A "CLI wiki page"
Actual: Main page of the Angular CLI repo (https://github.com/angular/angular-cli)

**Comment by yousafnawaz** [comment]
I think Library support link should point to: [https://angular.io/guide/creating-libraries](https://angular.io/guide/creating-libraries)

**Comment by gkalpak** [comment]
Thx for reporting this, @yuriybelike :+1:
I think @yousafnawaz's suggestion sounds reasonable.

Would any of you be interested in submitting a pull request?

**Comment by yousafnawaz** [comment]
@gkalpak Thanks. Sure, I will submit a PR to this issue.

**Comment by aikidave** [comment]
Thanks, @yuriybelike! @yousafnawaz I will keep an eye out for your PR!

**Comment by yousefalaqra** [comment]
@yousafnawaz  Any updates on this?

**Comment by yousafnawaz** [comment]
@yousefalaqra , I have my PR ready. however, if you want to work on it, go ahead.

**Comment by yousefalaqra** [comment]
@yousafnawaz  thanks! since you have it already go for it.
