### ISSUE TITLE
new angular 13  and @nguniversal/express-engine

### ISSUE THREAD

**Issue by vaka440** [angular/angular#44591]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

Yes

### Description

ng new angular-test
cd angular-test
ng add @nguniversal/express-engine

### Please provide the exception or error you saw

```true
The package @nguniversal/express-engine@13.0.1 will be installed and executed.                      
Would you like to proceed? Yes                                                                      
npm ERR! code ERESOLVE                                                                              
npm ERR! ERESOLVE unable to resolve dependency tree                                                 
npm ERR!                                                                                            
npm ERR! While resolving: angular-hosting-firebase-ssr@0.0.0                                        
npm ERR! Found: @angular/animations@13.0.3                                                          
npm ERR! node_modules/@angular/animations                                                           
npm ERR!   @angular/animations@"~13.0.0" from the root project                                      
npm ERR!                                                                                            
npm ERR! Could not resolve dependency:                                                              
npm ERR! peer @angular/animations@"13.1.1" from @angular/platform-server@13.1.1                     
npm ERR! node_modules/@angular/platform-server                                                      
npm ERR!   peer @angular/platform-server@"^13.0.1" from @nguniversal/express-engine@13.0.1          
npm ERR!   node_modules/@nguniversal/express-engine                                                 
npm ERR!     @nguniversal/express-engine@"13.0.1" from the root project                             
npm ERR!                                                                                            
npm ERR! Fix the upstream dependency conflict, or retry                                             
npm ERR! this command with --force, or --legacy-peer-deps                                           
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.                     
npm ERR!                                                                                            
npm ERR! See C:\Users\dukepro\AppData\Local\npm-cache\eresolve-report.txt for a full report.        
                                                                                                    
npm ERR! A complete log of this run can be found in:                                                
npm ERR!     C:\Users\dukepro\AppData\Local\npm-cache\_logs\2022-01-01T08_38_16_549Z-debug.log      
× Package install failed, see above.
```

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 13.0.4
Node: 16.13.1
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 13.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cli                    13.0.4
@angular/material               13.1.1
@schematics/angular             13.0.4
rxjs                            7.4.0
typescript                      4.4.4

**Comment by JoostK** [comment]
This appears to be a defect in NPM 7+. `@nguniversal/express-engine` requests `@angular/platform-server@^13.0.1` as peer dependency, and NPM concluded to install `@angular/platform-server@13.1.1` which is incompatible with the currently installed version of `@angular/animations`, which is only 13.0.3 whereas `@angular/platform-server@13.1.1` requires `13.1.1`. NPM _could_ have installed `@angular/platform-server@13.0.3` which satisfies all peer dependency requests.

I'd recommend updating to the latest 13.1.x releases of the Angular FW _before_ installing `@nguniversal/express-engine`. Your reproduction steps don't reproduce for me, so that should be working as expected.
