### ISSUE TITLE
Windows execution policy not mentioned in docs

### ISSUE THREAD

**Issue by bitshiftnetau** [angular/angular#44598]
### Description

The issue is described [here](https://github.com/angular/angular-cli/issues/22256#issuecomment-1003678055) 

You cannot possibly be held responsible for all contingencies for every system, that would be unreasonable. However, it would benefit the community, especially those of newcomers, were this issue at least mentioned as known in your docs. A timestamped solution would be most advantageous.

Whether or not this is normal behaviour is irrelevant, most other projects which encounter these issues make mention of the fact. The reality is that this particular problem is not documented and has fallen between the cracks, rendering your getting started doc unhelpful as completing it is left up to chance for the uninitiated. It is cost-free to add this and would speed up the education of those learning the framework. 

It serves no-one and nothing to omit this problem and solution from your docs and it should be noted there are 5 or 6 disparate solutions listed on SO, where only one is necessary.

More importantly, these solutions vary in their awareness and consideration of security measures. This alone makes it necessary to guide the user based on your framework's limited requirements.

### Please provide the steps to reproduce the issue

On a fresh Windows 10 install, your getting started examples do not work do to limitations on the Execution Policy.

### Please provide the expected behavior vs the actual behavior you encountered

Your starting examples should provide adequate information for execution, including minimal permissions required on a system-by-system basis.

**Comment by bdshanto** [comment]
Need to Execute this 
`Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned` then everything will work fine. 
Ref: [Set-ExecutionPolicy (Microsoft)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7.2)

**Comment by bitshiftnetau** [comment]
> Need to Execute this `Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned` then everything will work fine. Ref: [Set-ExecutionPolicy (Microsoft)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7.2)

Yes. Please add that to the getting started docs for the benefit of new users.

**Comment by gkalpak** [comment]
I think this sounds reasonable, if it's something that people with a fresh/default install will face. Would any of you be interested in creating a pull request?

**Comment by yousefalaqra** [comment]
@gkalpak  Call for a duty! I'm on it!

**Comment by aikidave** [comment]
Hi @bitshiftnetau! Thanks for re-filing this issue. (And thanks, @gkalpak for providing your technical insight!)

@yousefalaqra, please feel free to loop me in when your pull request is ready!

**Comment by yousefalaqra** [comment]
@aikidave 
Could you please review the [PR](https://github.com/angular/angular/pull/44606)

**Comment by ngtanthanh** [comment]
text
