### ISSUE TITLE
request add  `angular-miniprogram` project in `Cross-Platform Development` resources catalog

### ISSUE THREAD

**Issue by wszgrcy** [angular/angular#44593]
### Description

I am a developer of `angular-miniprogram` [link](https://github.com/wszgrcy/angular-miniprogram).
This project support develop a `miniprogram` use Angular
Now support [wechat miniprogram](https://developers.weixin.qq.com/miniprogram/en/dev/framework/),[alipay miniprogram](https://opendocs.alipay.com/mini/introduce),[bytedance miniprogram](https://microapp.bytedance.com/docs),[baidu miniprogram](https://smartprogram.baidu.com/docs/develop/tutorial/intro/)

**Comment by gkalpak** [comment]
@wszgrcy, you are welcome to create a pull request to add `angular-miniprogram` to our resources list. See [resources-contributing.md][1] for instructions.

<sub>Closing this issue to keep the backlog clean, but (as I said) you are welcome to create a pull request.</sub>

[1]: https://github.com/angular/angular/blob/8ebc946c0e7bf80d26ec8268acb4ff0af9e5c34a/aio/content/marketing/resources-contributing.md
