### ISSUE TITLE
HTML tag <time> is unsupported

### ISSUE THREAD

**Issue by const8ine** [angular/angular#44605]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

The tag `<time>` is not supported. When using `<time>` tag with its attribute `datetime`, user gets a compilation error:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time#attr-datetime

```
 NG8002: Can't bind to 'datetime' since it isn't a known property of 'time'
```

## Steps to reproduce
1. Wrap any string in a `<time>` tag
2. Set `datetime` attribute with a formatted date (valid example: `2011-11-18`)

## Expected result
The bundle compiles

## Actual result
Bundle fails to compile:
```
 NG8002: Can't bind to 'datetime' since it isn't a known property of 'time'
```

### Please provide the exception or error you saw

```true
NG8002: Can't bind to 'datetime' since it isn't a known property of 'time'
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.2
Node: 12.20.0
Package Manager: npm 6.14.8
OS: darwin x64

Angular: 13.0.1
... animations, cdk, common, compiler, compiler-cli, core
... elements, forms, language-service, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.2
@angular-devkit/build-angular   13.0.2
@angular-devkit/core            13.0.2
@angular-devkit/schematics      13.0.2
@angular/cli                    13.0.2
@schematics/angular             13.0.2
rxjs                            6.6.2
typescript                      4.4.4
```

**Comment by JoostK** [comment]
Angular binds to _properties_, and the property is named `dateTime` which you should be able to use.
