### ISSUE TITLE
Single-Input-Form Safari

### ISSUE THREAD

**Issue by m-andresen** [angular/angular#44602]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Given a HTML-Form with one single input element which has the required attribute and a button.

**Scenario:** Focus the input element and hit the enter key

**In vanilla HTML:** This results in a message and the html form wont be submitted.
**In Angular:** No message is being displayed and the html form will be submitted.

**Hints:**
* Safari seems to be the only affected browser.
* If there are two or more input elements the form wont be submitted by angular, too.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-76njbm?file=src%2Findex.html

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.4
Node: 16.13.1
Package Manager: npm 8.1.2
OS: darwin arm64

Angular: 13.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cli                    13.0.4
@schematics/angular             13.0.4
rxjs                            7.4.0
typescript                      4.4.4
```

**Comment by dylhunn** [comment]
@AndrewKushnir Have you seen this? Just confirmed it, really strange behavior.

**Comment by JeanMeche** [comment]
This looks like a Safari bug to me. I cannot reproduce it in Safari 17.4.
