### ISSUE TITLE
ngform disable validation when control disabled

### ISSUE THREAD

**Issue by batdelger** [angular/angular#4460]
I think ng-control validators should be disabled when control is disabled. For example: Control's disabled property could change depending on value of other control. Also I need functionality of disable/enable validity on NgControl.

**Comment by RodrigoQuesadaDev** [comment]
+1

I have this issue on Angular 1.4.8 with a couple of fields that are disabled using ng-disabled but Angular keeps validating them (some use the required attribute while others use a different validation), and that's definitely very problematic and annoying ('cause you need to use workaround code).
