### ISSUE TITLE
Is it correct to mutate Component Type ? 

### ISSUE THREAD

**Issue by montella1507** [angular/angular#44610]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Angular is mutating Types (eg. component type) - and specially - during runtime (with every createComponent(CompType) call), for the instance in the  bloomAdd() function.

Is this behavior correct?  Why it isn't considered as unecessary monkey patching and harmfull? Should not be ComponentType something like sealed class?   At least "after startup"? At the moment, component type is mutated every time you create new instance with createComponent() 

It denies the usage  of a component in NgRx with immutability checks etc (however it may be possible to walkaround this by passing Type getter).

### Please provide a link to a minimal reproduction of the bug

bloomAdd() function in Angular/Core

### Please provide the exception or error you saw

```true
TypeError: Cannot add property __NG_ELEMENT_ID__, object is not extensible
    at bloomAdd (core.mjs:3111)
    at diPublicInInjector (core.mjs:3243)
    at createRootComponentView (core.mjs:12496)
    at ComponentFactory.create (core.mjs:21893)
    at ViewContainerRef.createComponent (core.mjs:23163)
    at FilterEditComponent.ngOnInit (filter-edit.component.ts:46)
    at callHook (core.mjs:2533)
    at callHooks (core.mjs:2502)
    at executeInitAndCheckHooks (core.mjs:2453)
    at refreshView (core.mjs:9494)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
ng --version 
13.2.3

node -v
16.13.1

macOS
```

### Anything else?

NO

**Comment by alxhub** [comment]
This is working as intended - we don't support `Object.freeze` of component types. Angular is free to monkey-patch properties onto component types, and does so as performance optimizations (such as in the case shown here with `NG_ELEMENT_ID`).
