### ISSUE TITLE
Interface 'Document' incorrectly extends interface 'FontFaceSource'

### ISSUE THREAD

**Issue by fauconjona** [angular/angular#44614]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Today, I pulled my project I updated 2 weeks ago and I can no more start it.

I found this issue: https://github.com/microsoft/TypeScript/issues/47100 , but it seems to be related to angular, so I ask here :smile: 

### Please provide the exception or error you saw

```true
Error: node_modules/typescript/lib/lib.dom.d.ts:4179:11 - error TS2430: Interface 'Document' incorrectly extends interface 'FontFaceSource'.
  Types of property 'fonts' are incompatible.
    Type 'FontFaceSet' is missing the following properties from type 'FontFaceSet': onloading, onloadingdone, onloadingerror, forEach, and 3 more.

4179 interface Document extends Node, DocumentAndElementEventHandlers, DocumentOrShadowRoot, FontFaceSource, GlobalEventHandlers, NonElementParentNode, ParentNode, XPathEvaluatorBase {
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.2
Node: 14.17.3
Package Manager: npm 8.3.0
OS: linux x64

Angular: 13.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
rxjs                            6.6.7
typescript                      4.5.4
```

### Anything else?

I have no idea why this happen and it's really strange. I tried to delete node_modules, update with ng (all up to date) and tried with typescript 4.4.3.

**Comment by JoostK** [comment]
Angular doesn't provide declaration files for DOM types. It could be that some library is pulling those in, introducing the error. I doubt that this is caused by the CLI's build pipeline, but please share a reproduction and I'll be happy to take a look.

**Comment by fauconjona** [comment]
I solved my problem by deleting my package-lock.json file. I don't know what caused the issue but everything works now, sorry for the inconvenience.

**Comment by JoostK** [comment]
Thanks for following up. There may have been a bad library that has since been updated.
