### ISSUE TITLE
doc errors introduced by recent bootstrap API changes

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#4463]
There are two issues in the docs that seem to be related to the latest set of bootstrap API changes (links that don't have a target). Alex, please review and fix?

You can reproduce the errors below (plus others not related to your changes) with the command gulp/docs.angular.io

```
"Promise" - doc "angular2/core/PlatformRef" (interface)  - from file "angular2/src/core/application_ref.ts"
"ControlGroups" - doc "angular2/core/NgForm" (class)  - from file "angular2/src/core/forms/directives/ng_form.ts"
```

**Comment by alxhub** [comment]
Fixed with #4696.
