### ISSUE TITLE
doc errors introduced by recent compiler/View API doc changes

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#4464]
There's a new issue in the docs that seems to be related to your recent set of compiler/view API changes (links that don't have a target). Igor, please review and fix?

You can reproduce the errors below (plus others not related to your changes) with the command gulp/docs.angular.io

```
"ViewContainer" - doc "angular2/core/ViewRef" (interface)  - from file "angular2/src/core/compiler/view_ref.ts"
```

**Comment by IgorMinar** [comment]
There is a whole bunch of broken links in the docs because some of the docs are still missing.

I want to do a complete sweep through the links once we have all the docs in place.
