### ISSUE TITLE
Add Interpolation {{  }} to Template Variable Naming like #name_{{ index }} so dynamic names can be used

### ISSUE THREAD

**Issue by SheldonHage** [angular/angular#44640]
### Which @angular/* package(s) are relevant/releated to the feature request?

Unknown - CLI?

### Description

The following works well for template element references that have static variable names (ex: #some_name):
`@ViewChild('some_name') some_name: ElementRef`

But if you try something like this:
`<div *ngFor="let item of items; let index = index">`
&nbsp;&nbsp;&nbsp;&nbsp;`  <div #some_name_{{ index }}></div>`
`</div>`
... interpolation **does not** work.

However if you try something like this:
`<div *ngFor="let item of items; let index = index">`
&nbsp;&nbsp;&nbsp;&nbsp;`<div id="some_name_{{ index }}"></div>`
`</div>`
...interpolation **does** work.

This means that it is impossible to get a @ViewChild reference using a template variable for elements in a dynamic list.  For dynamically built DOM elements that need a component reference the result is to use something like this from within  (non-Angular):
`let myRef = document.getElementById("item_0");`

-Sheldon Hage

### Proposed solution

Support dynamic template variables using interpolation like one can do with the id.

Both of these should ideally work:
`<div id="item_{{ index }}"></div>`
`<div #item_{{ index }}></div>`

### Alternatives considered

There is no alternative except:
1.  Many lines of @ViewChildren / QueryList code
2.  By using the document.getElementById() approach.

**Comment by pkozlowski-opensource** [comment]
This was discussed in the past (see https://github.com/angular/angular/issues/33233) and we decided to not implement it as there are other, existing means of achieving the desired functionality.

Going to close this feature request, please refer to https://github.com/angular/angular/issues/33233 for more details.

**Comment by SheldonHage** [comment]
I would say that after reading #33233 I do not see a solution for the problem I faced.

Consider this please:  the discussion states that nothing exists at runtime, duplicates, etc.   But here I am saying that interpolation works for the element id name (which doesn't exist at runtime either).   Seems like a no-brainer to me that this would absolutely work.

Anyway...   cheers.
