### ISSUE TITLE
Update docs to include angular#bundler trusted type policy

### ISSUE THREAD

**Issue by bsbechtel** [angular/angular#44647]
### Description

The webpack fix for trusted types appears to have introduced a [new trusted type policy](https://github.com/angular/angular-devkit-build-angular-builds/blob/767febd16b2f1a05168be1c5ee68976c2c7c9791/src/webpack/configs/common.js#L252) `angular#bundler`. The docs need to be updated to reflect this policy in the [security section](https://angular.io/guide/security#enforcing-trusted-types).

### What is the affected URL?

https://angular.io/guide/security#enforcing-trusted-types

### Please provide the steps to reproduce the issue

N/A, when enforcing trusted types, an error requiring an 'angular#bundler' policy is thrown.

### Please provide the expected behavior vs the actual behavior you encountered

The docs provide additional information about the `angular#bundler` trusted types policy.

**Comment by tiddlypip** [comment]
angular#bundler is required for aot builds while the jit type is only required for jit builds.

**Comment by tiddlypip** [comment]
I've recently found a third undocumented type: angular#components
