### ISSUE TITLE
Outdated docs

### ISSUE THREAD

**Issue by tianyangren** [angular/angular#44662]
### Description

In the third paragraph: "For example, HeroListComponent has a heroes property that holds an array of heroes." 

I don't see "HeroListComponent" in the "Tour of Heroes tutorial" - mentioned in the first paragraph where doc examples are drawn from, docs might be outdated. 

### What is the affected URL?

https://angular.io/guide/architecture-components

**Comment by aikidave** [comment]
Hi @tianyangren! Thank you for filing this issue. I'll have someone on my team check this out!
