### ISSUE TITLE
Invalid binding, error message & input vs property

### ISSUE THREAD

**Issue by vicb** [angular/angular#4469]
As of a251df9df4a34592afb4984f7a3e13a186562234 if the template contains ie `<p *ng-if="..."></p>` and the `NgIf` directive is not added to the view, Ng will generate the following errors:

```
Can't bind to 'ngIf' since it isn't a known native property in HelloCmp > p:nth-child(0)[*ng-if=cond()]
Property binding ngIf not used by any directive on an embedded template in HelloCmp > p:nth-child(0)[*ng-if=cond()]
```

The first error should probably read: "is not an **input of** HelloComp".

We can bind to either an input (ie `ngIf`) or a property (ie `title`). Should we now call `title` an input instead of a property ? or what are the plans ?

May be `'ngIf' is not an input of HelloCmp nor a property on '<p>'` ?

Also we use the  `ElementSchemaRegistry` to check if an input/property exists using its `hasProperty()` method. This is an other place where we have decide whether to use "input" or "property" or ?

**Comment by pkozlowski-opensource** [comment]
@vicb IMO if you say "input of a div" people will be really confused....

**Comment by jessegood** [comment]
>IMO if you say "input of a div" people will be really confused.... 
I agree.
And that's where the input/output analogy breaks down... :wink:

**Comment by mhevery** [comment]
I think the error message is fine the way it is. 

Closing as no action.
