### ISSUE TITLE
Usage of ngZone.run for new async apis that zone.js hasn't pathced

### ISSUE THREAD

**Issue by Alan-LOL** [angular/angular#44714]
### Description

Is this demo correct? how ngZone knows when to update the view as zone.js hasn't patch `someNewAsyncAPI`
```
export class AppComponent implements OnInit {
  constructor(private ngZone: NgZone) {}
  ngOnInit() {
    // New async API is not handled by Zone, so you need to
    // use ngZone.run() to make the asynchronous operation in the Angular zone
    // and trigger change detection automatically.
    this.ngZone.run(() => {
      someNewAsyncAPI(() => {
        // update the data of the component
      });
    });
  }
}
```

### What is the affected URL?

https://angular.io/guide/zone#ngzone-run-and-runoutsideofangular

### Please provide the expected behavior vs the actual behavior you encountered

I think the demo code should be updated as below:
``` diff
export class AppComponent implements OnInit {
  constructor(private ngZone: NgZone) {}
  ngOnInit() {
    // New async API is not handled by Zone, so you need to
    // use ngZone.run() to make the asynchronous operation in the Angular zone
    // and trigger change detection automatically.
-    this.ngZone.run(() => {
      someNewAsyncAPI(() => {
+        this.ngZone.run(() => {
        // update the data of the component
+        });
      });
-    });
  }
}
```

**Comment by JoostK** [comment]
I believe you are correct; `NgZone.run` needs to be within the async closure, not around its registration.

**Comment by Alan-LOL** [comment]
@JoostK Thanks for your reply, it's been confusing me for two days now. I dug deep into zone.js, but still didn't find out how `zone` knew when the async callback was triggered in this demo.

**Comment by wbeeftink** [comment]
This issue can be closed, right? The docs are fixed as far as I can tell and the PR was closed too.

**Comment by JoostK** [comment]
Indeed!
