### ISSUE TITLE
`ViewChild` usage example is not working

### ISSUE THREAD

**Issue by Zuckjet** [angular/angular#44718]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

the code sample is not working, this line `this.selectedPane = v.id;`, v is undefined. see: https://angular.io/api/core/ViewChild#usage-notes

**Comment by JoostK** [comment]
I suspect the issue here is that `Pane` may not have been declared in an NgModule, as the example doesn't include an NgModule.

**Comment by inanemed** [comment]
I confirm that the example works as expected,did you add the Pan Directive to your Module ?

**Comment by Zuckjet** [comment]
Thanks, i will close this
