### ISSUE TITLE
Invalid nested binding & error message

### ISSUE THREAD

**Issue by vicb** [angular/angular#4471]
Consider `MyCmp` with the following template `<p [tittle]="'should be title'">I'am a P</p>` (spot the typo in "tittle")

The error message would be: `Can't bind to 'tittle' since it isn't a known native property in MyCmp > p:nth-child(0)[[tittle]='should be title']`

While it should be: `Can't bind to 'tittle' since it isn't a known native property in <p> > p:nth-child(0)[[tittle]='should be title']`

**Comment by mgechev** [comment]
What is the status of this issue given https://github.com/angular/angular/issues/4569

**Comment by pkozlowski-opensource** [comment]
With rc.1 the error message we get is:

```
EXCEPTION: Template parse errors:
Can't bind to 'tittle' since it isn't a known native property (" 
    <div>
      <p [ERROR ->][tittle]="'should be title'">I'am a P</p>
      <template #myTipContent>
        Some <b>content</b>
"): App@2:9
```

which precielly shows place in a template where the problem occurs (notice `[ERROR ->]`). I think that this one is as precise as it can get. Closing.
