### ISSUE TITLE
`UrlSegmentGroup` constructor error - `Cannot assign to read only property 'parent' of object '[object Object]`

### ISSUE THREAD

**Issue by wencakisa** [angular/angular#44719]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

Hi 👋🏼 

As I was updating Angular from `v11` to `v12` with the help of [update.angular.io](https://update.angular.io/?l=3&v=11.0-12.0) - I noticed that the navigation suddenly stopped working. Based on the stack trace, I've come to this conclusion:

[The part in the `UrlSegmentGroup` constructor where the `parent` files are generated (recursively)](https://github.com/angular/angular/blob/6a55affacd9b027b43f898f76e666dcfdbac7863/packages/router/src/url_tree.ts#L238) is now unable to do this because the `parent` property is read-only.

```ts
forEach(children, (v: any, k: any) => v.parent = this);
// ____________________________________^
```

This is executed because I have the following line in my code:

```ts
import { DefaultUrlSerializer } from '@angular/router';

const url = new DefaultUrlSerializer().parse(redirectUrl);
```

The [`DefaultUrlSerializer.parse`](https://angular.io/api/router/DefaultUrlSerializer#parse) method parses the passed string to a `UrlTree`.

Finally, once I pass the previously generated `UrlTree` to [`router.navigateByUrl`](https://angular.io/api/router/Router#navigatebyurl) - this exception gets raised.

---

When I downgrade to `v11` - everything is correct. ✅ 

> Note: There's a huge chance I'm missing something in the process, but from what I've concluded looking at the stack trace - it seems like an Angular regression.

Thanks in advance! 🙌🏼 

### Please provide the exception or error you saw

```true
ERROR Error: Uncaught (in promise): TypeError: Cannot assign to read only property 'parent' of object '[object Object]'
TypeError: Cannot assign to read only property 'parent' of object '[object Object]'
    at router.js:755:37
    at forEach (router.js:572:13)
    at new UrlSegmentGroup (router.js:755:9)
    at split (router.js:2493:15)
    at ApplyRedirects.apply (router.js:2619:28)
    at applyRedirects (router.js:2607:93)
    at SwitchMapSubscriber.project (router.js:2952:27)
    at SwitchMapSubscriber._next (switchMap.js:28:27)
    at SwitchMapSubscriber.next (Subscriber.js:49:18)
    at SwitchMapSubscriber.notifyNext (switchMap.js:66:26)
    at resolvePromise (zone.js:1213:31)
    at resolvePromise (zone.js:1167:17)
    at zone.js:1279:17
    at ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.js:28679:33)
    at ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:582:35)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:21)
    at invokeTask (zone.js:1600:14)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.2.14
Node: 16.13.2 (Unsupported)
Package Manager: yarn 1.22.17
OS: linux x64

Angular: 12.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1202.14
@angular-devkit/build-angular      12.2.14
@angular-devkit/core               12.2.14
@angular-devkit/schematics         12.2.14
@angular/cdk                       12.2.13
@angular/cli                       12.2.14
@angular/material                  12.2.13
@angular/material-moment-adapter   12.2.13
@schematics/angular                12.2.14
rxjs                               6.6.3
typescript                         4.3.5
```

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

As far as I can see, there were no changes in that bit of logic between 11 and 12. It's also a very common code path so if it was really a problem in Angular, it's surprising that the issue wasn't raised long ago. The description of the exception "cannot assign to read only property" points to properties that are [not read only](https://github.com/angular/angular/blob/6a55affacd9b027b43f898f76e666dcfdbac7863/packages/router/src/url_tree.ts#L231-L238) so I don't quite see how it's possible that Angular caused the issue. It may have been some other change that happened when attempting to upgrade from v11 to v12.
