### ISSUE TITLE
Error with FormBuilder

### ISSUE THREAD

**Issue by silas-bovolin** [angular/angular#44725]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

I'm following the angular docs to build a simple login form. When I use FormControl and FormGroup works well. However, if I use FormBuilder, gives me the error: Type 'FormGroup' is missing the following properties from type 'FormBuilder': group, control, array. 

My component.ts (entire script):
![image](https://user-images.githubusercontent.com/66489635/149637890-f6007815-e937-43be-8cf3-692887bbfbcd.png)

My component.html (entire script):
![image](https://user-images.githubusercontent.com/66489635/149637774-18219a41-2401-47f6-b91f-af4e178b03f7.png)

My app module:
![image](https://user-images.githubusercontent.com/66489635/149637790-a8207e11-2ed7-4a6a-acab-9eae908797f8.png)

Errors:
![image](https://user-images.githubusercontent.com/66489635/149637919-94767bc2-855e-4d36-a445-9e5dcb23b240.png)
![image](https://user-images.githubusercontent.com/66489635/149637924-87415153-c0f5-4e53-ae17-cb92da727b06.png)
![image](https://user-images.githubusercontent.com/66489635/149637928-e0862654-9c15-475d-aa0f-9a3c8cd13eaa.png)

### Please provide the exception or error you saw

```true
Type 'FormGroup' is missing the following properties from type 'FormBuilder': group, control, array.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.3
Node: 16.13.2
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 13.1.2
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.3
@angular-devkit/build-angular   13.1.3
@angular-devkit/core            13.1.3
@angular-devkit/schematics      13.1.3
@angular/cli                    13.1.3
@schematics/angular             13.1.3
rxjs                            7.4.0
typescript                      4.5.4
```

**Comment by jnizet** [comment]
Hi @silas-bovolin 

The issue is in your code: you declared `loginForm` as a FormBuilder. But it's supposed to be a `FormGroup`. The FormBuilder is used to *build* the form group. It *is not* a form group.

**Comment by silas-bovolin** [comment]
@jnizet  thanks for helping
