### ISSUE TITLE
Routes with parameter not loaded css and javascript files

### ISSUE THREAD

**Issue by srht** [angular/angular#44727]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I tried to add a route with parameter but that route didn't worked properly. When I visit the route with parameter javascript and route files couldn't be loaded. There were 404 errors on console.  The other routes were running normal.
After a while, I found the problem **APP_BASE_HREF** provider line. 
I had added   
`providers: [{provide: APP_BASE_HREF, useValue: '/'}`, 

inside AppModule class as a provider. But didn't work at all. So I added 
`<base href="/"> `
tag under head in the index.html file, then it worked.

### Please provide the exception or error you saw

```true
404 not found of asset files in the web console.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.3
Node: 16.13.1
Package Manager: npm 8.3.0
OS: win32 x64

Angular: 12.0.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router     

Package                         Version
---------------------------------------------------------  
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      13.1.3 (cli-only)
@angular/google-maps            12.2.13
@schematics/angular             13.1.3 (cli-only)
rxjs                            6.6.7
typescript                      4.2.4
```

**Comment by atscott** [comment]
Closing as outside of Angular. 

Not providing the base href would have given the error "No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document". Adding the `providers: [{provide: APP_BASE_HREF, useValue: '/'}` can potentially fix the error in Angular but the resources not being found is an issue with the client's configuration for requesting server resources (outside of Angular). `<base href="/">` properly fixed that for you.
