### ISSUE TITLE
DatePipe adds a whole year for dates at the end of December

### ISSUE THREAD

**Issue by plonkaadam** [angular/angular#44722]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Date pipe adds a whole year in some cases for last three days of December

for example:

`new DatePipe('en-US').format('2024-12-29', 'YYYY-MM-dd')`

returns

`2025-12-29`

### Please provide a link to a minimal reproduction of the bug

https://codesandbox.io/s/fervent-voice-rvieg?file=/src/app/app.component.html

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.4
```

**Comment by JoostK** [comment]
`YYYY` is the week-numbering year, you'll want to use `yyyy`.

**Comment by plonkaadam** [comment]
> `YYYY` is the week-numbering year, you'll want to use `yyyy`.

oh wow, that sounds like an useless and misleading feature. thank you, it took almost a full year to find this bug in our application
