### ISSUE TITLE
The click event does not work for list items when *ngFor is used in a certain scenario

### ISSUE THREAD

**Issue by egaluza** [angular/angular#44720]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

The issue:

The click event for standard elements stops working after a module from our @devextreme-angular library is imported to the application.

We found out that the problem is reproduced only when *ngFor is used to create items with the click event handlers and a getter/function is used to return an array of objects.

For example:

```html

<ul>

<li *ngFor="let b of buttons" (click)="btnClick(b)">{{ b.label }}</li>

</ul>

```

```ts

get buttons() {

return [{ label: "Button1" }, { label: "Button2" }, { label: "Button3" }];

}
```

or

```html

<ul>

<li *ngFor="let b of getButtons()" (click)="btnClick(b)">{{ b.label }}</li>

</ul>

```

```ts

getButtons() {

return [{ label: "Button1" }, { label: "Button2" }, { label: "Button3" }];

}

```

We found that the issue is not reproducible in the following cases:

1. A getter/function returning an array of numbers, not objects, works correctly.

```ts

get numbers() {
return [1, 2, 3];
}

```

At the same time, if the array contains both numbers and objects, the issue is not reproducible for numbers and is reproducible for objects:

```ts

get numbers() {
return [{label:'button1'}, 2, 3];
}

```

2. If an array is set as a constant:

```ts

buttonsArray = [
{ label: "Button1" },
{ label: "Button2" },
{ label: "Button3" }
];

```

We understand that the problem is related to our library, but it is not clear how to start the research because the following points are unclear:

1. the difference between the code generation when a getter and a constant array are used in *ngFor;
2. how this can be related to the event subscriptions.

It will be very helpful if you clarify these (or add some more) details. This will allow us to investigate and resolve the issue on our end.

Thanks in advance.

An example is included in the code-sandbox

### Please provide a link to a minimal reproduction of the bug

https://codesandbox.io/s/kind-varahamihira-b50dt?file=/src/app/app.component.html

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 9.1.12
Node: 12.14.0
OS: win32 x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.6.2
typescript                        3.8.3
webpack                           4.42.0
```

### Anything else?

 Anything else:

The issue is also reproducible in the latest version @angular/cli: 13.1.3.

**Comment by JoostK** [comment]
Does devextreme somehow adds capturing event listeners? Then you'd hit #41192.

**Comment by criskrzysiu** [comment]
This is all because on click event You trigger change detection and recreate whole component (ng-for loop). Add a ng for ``trackBy`` and it should start working probably?
