### ISSUE TITLE
refactor(http): convert Connection interface to be Observable of Response

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#4472]
(recapping discussion with @blesh, who will probably correct me)

## Current State

Right now, the [`Connection`](https://github.com/angular/angular/blob/a251df9df4a34592afb4984f7a3e13a186562234/modules/angular2/src/http/interfaces.ts#L22) interface, which is implemented by `XHRConnection`, `JSONPConnection`, and `MockConnection`, has simple interface:

```typescript
interface Connection {
  readyState: ReadyStates;
  request: Request;
  response: Observable<Response>;
}
```

Calls to the [Http](https://github.com/angular/angular/blob/a251df9df4a34592afb4984f7a3e13a186562234/modules/angular2/src/http/http.ts) service return the `connection.response` observable, so end users don't really interact with this interface too much in application code. In tests, however, users will be working with `MockConnection` instances created by [`MockBackend`](https://github.com/angular/angular/blob/a251df9df4a34592afb4984f7a3e13a186562234/modules/angular2/src/http/backends/mock_backend.ts) in order to create mock responses for requests.

```typescript
myService.getUsers().subscribe(users => {
  expect(users[0].name).toBe('Rob');
  async.done();
});
mockBackend.connections.subscribe(connection => {
  connection.mockRespond(mockUsers);
});
```
(Note that the mock responding mechanism should be further improved, but that's outside the scope of this proposal).

## Proposal

Change `Connection` itself to be an Observable of `Response`, and keep `request` property intact. @blesh says it aint so bad to add properties to Observables (though adding methods is a bad idea because observable methods are expected to be operators).

```typescript
interface Connection extends Observable<Response> { //Observable interface doesn't actually exist yet
  readyState: ReadyStates; // I would like to get rid of this property
  request: Request;
}
```

`MockConnection` should extend subject, so that it can be `next`-ed with `Response`s.

```typescript
class MockConnection extends Subject<Response> implements Connection {
  readyState: ReadyStates;
  request: Request;
}
```

This change is actually pretty minor from an end-user perspective, other than the change of calling `next` on the `MockConnection` rather than the current `mockRespond`. But internally, it reduces cruft and simplifies logic.

CC: @robwormald

**Comment by blesh** [comment]
> Observable interface doesn't actually exist yet

You could use the `.ts` files from RxJS directly. At this point, and given your contributor status and our level of partnership, I really doubt there will be any reason to change the guts of `Observable` any time soon.

**Comment by robwormald** [comment]
Sounds good to me, makes a lot of sense. 

> change of calling next on the MockConnection rather than the current mockRespond. But internally, it reduces cruft and simplifies logic.

Is there any reason not to add mockRespond / mockError methods to the mockConnection? Trying to avoid too many new concepts to end users ("you have to call next() and then complete() on every request")
```
mockRespond(res){
  this.next(res);
  this.complete();
}
mockError(err){
  this.error(err)
}
```

> You could use the .ts files from RxJS directly.
This would simply stuff nicely, but it would mean distributing Rx as part of the Angular codebase (vs as an npm dependency) I think? Any issues with that?

**Comment by jeffbcross** [comment]
> You could use the .ts files from RxJS directly.

@blesh yeah, I think we should try that. My real meaning about typings was that we haven't yet brought the new Rx typings into angular since our own typings distribution process has been changing, and we just wanted to get the new Rx in, so right now we have `any` in places where it shouldn't.

**Comment by blesh** [comment]
> This would simply stuff nicely, but it would mean distributing Rx as part of the Angular codebase (vs as an npm dependency) I think? Any issues with that?

Distributing a library that returns an Observable type with no combinators is like distributing kegs of beer and no taps.

**Comment by jeffbcross** [comment]
> Distributing a library that returns an Observable type with no combinators is like distributing kegs of beer and no taps.

@blesh whoa.

**Comment by jeffbcross** [comment]
The current state is also preventing retry from working correctly, as @robwormald and I have recently discovered :(

**Comment by blesh** [comment]
> The current state is also preventing retry from working correctly

Try it with RxJS 5.0.0-alpha.6 ... there were some bugs with `retry` and `retryWhen` that have been corrected.

**Comment by robwormald** [comment]
This issue was moved to angular/http#63
