### ISSUE TITLE
&ngsp; does not produce a space anymore, does it?

### ISSUE THREAD

**Issue by henrikdahl8240** [angular/angular#44743]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

`&ngsp;` does not produce a space anymore, does it?

According to https://angular.io/api/core/Component `&ngsp;` should produce a single space, which it also did several versions ago, but I don't think, that it produces any space anymore.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.3
Node: 16.13.0
Package Manager: npm 6.14.11
OS: win32 x64

Angular: 13.1.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.3
@angular-devkit/build-angular   13.1.3
@angular-devkit/core            13.1.3
@angular-devkit/schematics      13.1.3
@angular/cli                    13.1.3
@schematics/angular             13.1.3
rxjs                            6.6.7
typescript                      4.5.4
```

**Comment by JoostK** [comment]
Please provide a reproduction.

**Comment by henrikdahl8240** [comment]
I am sorry, I hadn't noticed, that the new version of Bootstrap defines a flex container for the parent. Therefore the space was being ignored.

**Comment by henrikdahl8240** [comment]
@JoostK I would suggest you to delete this issue. It appears to me, that I cannot delete it myself.

**Comment by JoostK** [comment]
Neither can I, issues are immortal (well, they require admin rights). This would not qualify for deletion; it's fine to keep it around; maybe it helps others.
