### ISSUE TITLE
mouseleave() not firing on disappearing objects

### ISSUE THREAD

**Issue by nikita-fuchs** [angular/angular#44740]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

The current implementation of `mouseleave()` leads to the following behaviour, which is technically correct, but not logically:

Example (see gif): 

1. I show a fontawesome icon that changes on `mouseenter()` and `mouseleave()`
2. Clicking a button hides the icons and makes new elements appear.
3. Going back and making the old elements appear, the mouse technically never "left" the icons, so the fontawesome icon for the hovering state is still displayed.
4. 
![hover issue](https://user-images.githubusercontent.com/11761828/149915996-75e48a13-f8fe-4f9d-9a3d-cbb2da53863d.gif)

I know, technically `onmouseleave()` represents just that, a mouse leaving an element, but logically it did so, when the element disappears. The only workaround seems to be to make the `(click)` reset a hover-state representing var.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.1.4
Node: 14.18.1
Package Manager: npm 8.3.0
OS: darwin x64

Angular: 12.1.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.4
@angular-devkit/build-angular   12.1.4
@angular-devkit/core            12.1.4
@angular-devkit/schematics      12.1.4
@angular/cli                    12.1.4
@schematics/angular             12.1.4
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by nikita-fuchs** [comment]
I found out that `(blur)`  is there for handling this case. I would like to hear your opinion on this though, feel free to close.

**Comment by gkalpak** [comment]
This is how browsers behave, I'm afraid. Angular just registers the event listener, but it is up to the browser when to fire an event. As such, I don't think there is anything Angular could (or should) do differently here.

Maybe you could attach the `mouseleave` behavior to the `click` handler as well.
