### ISSUE TITLE
ngOnInit doesn't compile the code

### ISSUE THREAD

**Issue by Alroyfernz** [angular/angular#44754]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

ngOnInit doesn'y compile the code line by line, Just executes first 2-3 line and never reaches the end in most cases.

### Please provide a link to a minimal reproduction of the bug

ngOnInit doesn'y compile the code line by line, Just executes first 2-3 line and never reaches the end in most cases.

### Please provide the exception or error you saw

```true
ngOnInit doesn'y compile the code line by line, Just executes first 2-3 line and never reaches the end in most cases.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
ngOnInit doesn'y compile the code line by line, Just executes first 2-3 line and never reaches the end in most cases.
```

### Anything else?

ngOnInit doesn'y compile the code line by line, Just executes first 2-3 line and never reaches the end in most cases.

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
