### ISSUE TITLE
Develop Angular Improvement Process

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#4475]
So far we've been leaning upon learnings from the previous versions of Angular to drive feature development in Angular 2. We sort of *knew* what we wanted to do, and are doing it. However, we are slowly exhausting this body of knowledge. We should prepare to take the framework beyond simply improving on the old stuff, and accept proposals to improve based on Angular 2's own usage, which is growing very quickly now, and state of the Web and new usage patterns.

To that end I propose that we introduce an **Angular Improvement Process**. This process would document a clear path from a (crazy) idea to accepted proposal to a prototype and finally to implementation in the core framework. The process would mimic similar processes from Python ([PEP](https://www.python.org/dev/peps/)), Dart ([DEP](https://github.com/dart-lang/dart_enhancement_proposals)), and Java ([JCP](https://www.jcp.org)).

**Comment by gdi2290** [comment]
do we post these crazy ideas here?

**Comment by yjbanov** [comment]
@gdi2290: no, here we only develop a process, but the process would have to define where to post ideas, how to communicate/review them to the Angular team and the community, prototype them and finally accept/reject them.

**Comment by aholbreich** [comment]
Yes please! Angular 2.0 need to be stabilized quickly as is! New features should go throu some process. Otherwise, there is signifivcant danger for the whole project.
