### ISSUE TITLE
View caching leads to unexpected reuse of stateful elements (e.g. <input>)

### ISSUE THREAD

**Issue by alxhub** [angular/angular#4478]
See this [Plunker](http://plnkr.co/edit/EmY16weMpjzpVxKjz5AV?p=preview) example.

`NgFor` creates and destroys views as its underlying iterable changes. If those views contain a stateful element like `<input>`, when rehydrated their state remains unchanged. For example, if the user enters text into the `<input>` element, then that element is removed and a new view is requested (by adding to the `NgFor`, perhaps), the view cache will deliver the old `<input>` element with its old input instead.

**Comment by mhevery** [comment]
# Fix

**Comment by tbosch** [comment]
+1, agree

**Comment by jpsfs** [comment]
Any news on this topic?

**Comment by mhevery** [comment]
We no longer do view reuse.
