### ISSUE TITLE
Code Coverage breaks constructor inheritance

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#44781]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, the previous version in which this bug was not present was: 7.2

### Description

Running with code coverage enabled breaks constructor inheritance.

Inserting a constructor in the `ValidationDirective` also fixes the error.

## 🔬 Minimal Reproduction
https://github.com/CSchulz/angular-code-coverage-breaks-constructor-inheritance

Run `npm test` results into

> TypeError: Cannot read property 'get' of undefined

Run `npm test -- --codeCoverage false` succeeds.

## 🔥 Exception or Error

For some reason the dependencies of the `ValidationDirective` don't get resolved correctly.
You can see in the `createClass` method that the deps of `ValidationDirective` are empty.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.3
Node: 10.15.3
OS: darwin x64
Angular: 8.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.3
@angular-devkit/build-angular      0.800.3
@angular-devkit/build-ng-packagr   0.800.3
@angular-devkit/build-optimizer    0.800.3
@angular-devkit/build-webpack      0.800.3
@angular-devkit/core               8.0.3
@angular-devkit/schematics         8.0.3
@angular/cli                       8.0.3
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.3
@schematics/angular                8.0.3
@schematics/update                 0.800.3
ng-packagr                         5.3.0
rxjs                               6.4.0
typescript                         3.4.5
webpack                            4.30.0
</code></pre>

**Comment by JoostK** [comment]
Duplicate of #31337.

**Comment by Platonn** [comment]
Thank you @alan-agius4 for [fixing](https://github.com/angular/angular/commit/ed67a074ceed6440bf7f638512a20bbd3be8cbd4) it and releasing in [13.2.0-rc.1](https://github.com/angular/angular/blob/master/CHANGELOG.md#1320-rc1-2022-01-24)!

**Comment by alan-agius4** [comment]
@JoostK, actually beat me to it!
