### ISSUE TITLE
ngTemplateOutletInjector - component injector should be stronger the wrapping component injector

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular#44791]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

Hey, I discovered this new feature from this [blog](https://netbasal.com/new-in-angular-13-pass-an-injector-to-embedded-views-cb71155025b4) post, and I believe I have found a bug. Let's use the example from the blog post and modify it as follows:

```ts
@Component({
  selector: 'app-foo',
  template: `
   <ng-template [ngTemplateOutlet]="tpl" [ngTemplateOutletInjector]="injector"></ng-template>
  `,
  providers: [{ provide: 'name', useValue: 'Ariel' }]
})
export class FooComponent {
  @Input() tpl!: TemplateRef<any>;

  constructor(public injector: Injector) { }
}
```

```ts
@Component({
  selector: 'app-bar',
  template: `{{ name }}`
})
export class BarComponent {
  constructor(@Inject('name') public name: string) {
  }
}
```

```ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
      <app-foo [tpl]="tpl"></app-foo>

        <ng-template #tpl>
          <app-bar></app-bar>
        </ng-template>

   `,
  providers: [{ provide: 'name', useValue: 'app' }]
})
export class AppComponent {
}
```

You will see `app` on the screen if you run the code. I expected `Ariel` because I provided the Foo component injector, which should be stronger than the App injector. If you remove the provider from the app component you will get `Ariel`.

**Comment by crisbeto** [comment]
This came up during the code review. See https://github.com/angular/angular/pull/44666#discussion_r785217924 on the reasoning.

**Comment by ArielGueta** [comment]
Thanks. I think that this behaviour should be well documented.

**Comment by crisbeto** [comment]
This feedback has come up a few times now. I'll bring it up again in our next meeting.

**Comment by ArielGueta** [comment]
Thank you.

**Comment by crisbeto** [comment]
We ended up reverting the feature and will re-asses for v14.
