### ISSUE TITLE
createComponent results in  

### ISSUE THREAD

**Issue by jbistis** [angular/angular#44790]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

Error: NG0201: No provider for FormContainerComponent found in NodeInjector...when trying to use the createComponent.

### Please provide a link to a minimal reproduction of the bug

https://github.com/prometheus-partners/form-issue.git

### Please provide the exception or error you saw

```true
Error: NG0201: No provider for FormContainerComponent found in NodeInjector. Find more at https://angular.io/errors/NG0201
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.2
Node: 14.18.2
Package Manager: npm 6.14.15
OS: darwin x64

Angular: 13.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@angular/fire                   6.1.5
@angular/google-maps            13.1.3
@schematics/angular             13.1.2
rxjs                            6.6.7
typescript                      4.5.4
```

### Anything else?

To recreate the issue, simply serve the app and try to view in the browser and the error will appear.  This configuration works for us in angular 9.1.15.

**Comment by JoostK** [comment]
It looks like the issue here is with the usage of `@Host()` as injection flag for `FormFieldComponent` in `InputNumberComponent`. The `@Host()` injection flag used to be ignored for dynamically created components, but Ivy properly adheres to that flag. This is noted in the [Ivy compatibility guide](https://v9.angular.io/guide/ivy-compatibility):

> If a token is injected with the `@Host` or `@Self` flag, the module injector is not searched for that token (previously, tokens marked with these flags would still search at the module level).

**Comment by jbistis** [comment]
Thanks, I will review.  I made an a13 version so you do not have to deal with the This is a simple server for use in testing or debugging Angular limitations in console.log.  a13 version is at https://github.com/prometheus-partners/input-fields.git

**Comment by jbistis** [comment]
Thanks. I also read https://github.com/angular/angular/issues/31539 which seems related.  Code is still not functioning as intended.  Will provide an update shortly.

**Comment by JoostK** [comment]
Closing per https://github.com/angular/angular/issues/44790#issuecomment-1019484208.
