### ISSUE TITLE
`Route#pathMatch` API doc text style is incorrect

### ISSUE THREAD

**Issue by wilmarques** [angular/angular#44795]
### Description

Some parts of the text style of the description available for the `pathMatch` property on the `Route` object are incorrect.

Instead of code snippets being presented inside a `<code>` element, a part of the "normal" text are.

### What is the affected URL?

https://angular.io/api/router/Route#pathMatch

### Please provide the steps to reproduce the issue

Go to <https://angular.io/api/router/Route#pathMatch> and read the description text for the `pathMatch` property.

### Please provide the expected behavior vs the actual behavior you encountered

The actual version of the doc shows a part of the text as code and the code as normal text, like below:

![Incorrect text styling on Route API doc](https://user-images.githubusercontent.com/1015148/150689787-83af9920-4e53-4b5b-92a0-9f69d2b808b4.png)

The expected is that code should be styled as code:

<img width="711" alt="image" src="https://user-images.githubusercontent.com/1015148/150689898-80d9b4e2-bbd6-47e5-8dbc-bf0527378230.png">

**Comment by AndrewKushnir** [comment]
Closing this PR since PR #44796 is merged.
