### ISSUE TITLE
SecurityError: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by aniket-kale** [angular/angular#44802]
### Description

I have used a `sessionStorage` in my Angular Application to store token and user information. It's working perfectly in the normal Chrome but in the incognito mode of Chrome, it's throwing a below error.

`ERROR Error: Uncaught (in promise): SecurityError: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.`

![AngularError](https://user-images.githubusercontent.com/35553614/150771510-148bdb36-5685-455a-be30-4aec3a4c719b.png)

I am able to load my site only when I go to my chrome settings and select "Allow all cookies".

This will break the app for all my users and I can't expect them all to "Allow all cookies" as that in itself is a security risk from the user's point of view.

Is there any workaround for this? Thanks.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.3
Node: 17.3.0
Package Manager: npm 8.3.0
OS: linux x64

Angular: 13.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.3
@angular-devkit/build-angular   13.0.3
@angular-devkit/core            13.0.3
@angular-devkit/schematics      13.0.3
@angular/cli                    13.0.3
@schematics/angular             13.0.3
rxjs                            6.6.3
typescript                      4.4.4
```

**Comment by crisbeto** [comment]
This doesn't have to do with Angular. Browsers will block access to things like `localStorage` and `sessionStorage` in incognito mode for privacy reasons. You should wrap your code in a `try/catch` to safely handle such cases.
