### ISSUE TITLE
fix(docs): add support for type aliases in doc generation process

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#4480]
I was documenting a couple of type aliases in http/interfaces.ts, and the Jade output was not parsing correctly, therefore causing errors when serving locally from angular.io (at SHA 34518f0f2d23019f34829bb49eb3d3f4efe80516). The problems only become obvious when I add code samples, because Jade tries to parse my sample's indentations as Jade statements.

Comments with sample code, followed by source code:

```typescript
/**
 * Interface for options to construct a {@link RequestOptions} object, based on
 * [RequestInit](https://fetch.spec.whatwg.org/#requestinit) from the Fetch spec.
 *
 * ### Example ([live demo](http://plnkr.co/edit/sJ47XTYAdF7YWv9DDH68?p=preview))
 *
 * ```
 * import {
 *   RequestOptionsArgs
 * } from 'angular2/http';
 * ```
 */
export type RequestOptionsArgs = {
  url?: string;
  method?: string | RequestMethods;
  search?: string | URLSearchParams;
  headers?: Headers;
  body?: string;
}
```

Jade output:

```jade

<h1>RequestOptionsArgs <span class="type">type alias</span></h1>
<p class="module">exported from <a href='../http'>angular2/http</a><br/>
defined in <a href="https://github.com/angular/angular/tree/2.0.0-alpha.37/modules/angular2/src/http/interfaces.ts#L26-L46">angular2/src/http/interfaces.ts (line 26)</a></p>
<p><p>Interface for options to construct a <a href='RequestOptions-class.html'><code>RequestOptions</code></a> object, based on
<a href="https://fetch.spec.whatwg.org/#requestinit">RequestInit</a> from the Fetch spec.</p>
h2 Example (live demo)
pre(class="prettyprint linenums")
  code.
import {
  RequestOptionsArgs
} from 'angular2/http';</p>
```

If I change to an interface, the output is fine:

<div class="highlight highlight-source-jade">
<pre>
p.location-badge.
  exported from <a href='../http'>angular2/http</a>
  defined in <a href="https://github.com/angular/angular/tree/2.0.0-alpha.37/modules/angular2/src/http/interfaces.ts#L26-L46">angular2/src/http/interfaces.ts (line 26)</a>

:markdown
  Interface for options to construct a <a href='RequestOptions-class.html'><code>RequestOptions</code></a> object, based on
  [RequestInit](https://fetch.spec.whatwg.org/#requestinit) from the Fetch spec.
  
  ### Example ([live demo](http://plnkr.co/edit/sJ47XTYAdF7YWv9DDH68?p=preview))
  
  ```
  import {
    RequestOptionsArgs
  } from 'angular2/http';
  ```
</pre>
</div>

CC: @petebacondarwin

**Comment by mhevery** [comment]
This may be obsolete with @alexeagle change in the way we generate the `.d.ts` file.

**Comment by alexeagle** [comment]
yes give me a few more days to land the needed changes and then we can confirm this is obsolete

**Comment by naomiblack** [comment]
@alexeagle I'm pretty sure this is obsolete?

**Comment by alexeagle** [comment]
Wait, this issue is for .ts -> dgeni -> HTML right? That's not obsoleted by new typings, it's still on the path for generating human-readable docs. @jeffbcross ?

**Comment by alexeagle** [comment]
I'm not please re-assign if needed, Pete

**Comment by petebacondarwin** [comment]
@jeffbcross why did you want to use a type-alias rather than an interface for this anyway?
In the TypeScript language specification it discourages type aliases where interfaces can be used instead:

> Interface types have many similarities to type aliases for object type literals, but since interface types offer more capabilities they are generally preferred to type aliases.
> Doing so means the following capabilities are lost:
* An interface can be named in an extends or implements clause, but a type alias for an object type
literal cannot.
*  An interface can have multiple merged declarations, but a type alias for an object type literal
cannot.
* An interface can have type parameters, but a type alias for an object type literal cannot

**Comment by petebacondarwin** [comment]
I can apply a naive patch to the angular.io dgeni package to ensure that type-aliases don't crash jade but to do a proper job of describing the type properly is a more involved job.

**Comment by jeffbcross** [comment]
@petebacondarwin I am not sure why those were originally changed from interfaces to types. @mhevery originally made the change.

**Comment by mhevery** [comment]
I thought there was a difference. I was mistaken, so I think we should go back to interfaces and close this issue.
