### ISSUE TITLE
replaceUrl: true not changing the URL in URL bar of browser

### ISSUE THREAD

**Issue by anwarulislam** [angular/angular#44808]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

`replaceUrl: true` property is not working as expected. It's not changing the URL in the URL bar but it's not keeping the URL in the history which is okay. 

I want to replace the URL but don't want to keep the previous URL in history. Previously, I was using `replaceUrl: true` in the `router.navigate(['url'], { replaceUrl: true })` method. After updating my Angular application to the latest version it's not working as before. 

Wrong:
![image](https://user-images.githubusercontent.com/26295990/150845537-c37ec454-2266-448c-ae5a-3f98a79e8239.png)

Expectation:
![image](https://user-images.githubusercontent.com/26295990/150845597-ca4c71ad-0d75-4b3d-9a26-7e00923289fa.png)

**Comment by atscott** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

stackblitz demonstrating behavior working as expected: https://stackblitz.com/edit/angular-ivy-1clkby?file=src%2Fapp%2Fapp.component.html
