### ISSUE TITLE
Static Access to Validation Error Strings

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular#44829]
### Which @angular/* package(s) are relevant/releated to the feature request?

forms

### Description

We can retrieve the boolean value for a specific Validator like this:

```
this.email.hasError('email')
```

I would be nice if we could get programmatic access to the correct `email` string like this:

```
this.email.hasError(Validators.EMAIL_KEY)
``` 

### Proposed solution

```
this.email.hasError('Validators.EMAIL_KEY')
``` 

### Alternatives considered

Just type the string ...  `email` ...

The thing is ... if we make a mistake ... for example typing `minLength` ... instead of `minlength` ...

**Comment by Totati** [comment]
Well, there is this relatively new functionality [AbstractControl#hasValidator](https://angular.io/api/forms/AbstractControl#hasvalidator).
It's not self-evident how to use it, as some of the validators are higher-order functions, like `Validators.min` and the ones you have to call with an argument. These returned `ValidatorFn` functions has to be stored somewhere, so you can check it with `hasValidator`.
``` javascript
const control = new FormControl();
const validator = Validators.min(10);
control.addValidators(validator);
control.hasValidator(validator); // this returns true;
control.hasValidator(Validators.min(10)); // this returns false
```

**Comment by fireflysemantics** [comment]
@Totati IIUC `control.hasValidator` checks whether the `control` has a specific validator.

This is different from:

```
this.email.hasError(Validators.EMAIL_KEY)
```

Which checks whether the `errors` property on the control has a specific keyed error.

**Comment by Totati** [comment]
Sorry, I missunderstood!
