### ISSUE TITLE
when click refresh button in chrome browser, cannot stop the refreshing or show a modal

### ISSUE THREAD

**Issue by ahmedabdelhafez** [angular/angular#44820]
### Which @angular/* package(s) are relevant/releated to the feature request?

common, core, forms

### Description

hello dears:
when i click the F5 on keyboard, or click the refresh button on browser i cannot stop the page from refreshing and when i add a modal or show confirm it appears but the page still refreshing and i cannot take the decision from the modal or confirmation popup 

### Proposed solution

how to not refresh the page till the user select yes or no

### Alternatives considered

how to not refresh the page till the user select yes or no

**Comment by geromegrignon** [comment]
Blocking the browser default behavior is unrelated to Angular.

**Comment by atscott** [comment]
I'm sorry but this issue is not caused by Angular.

**Comment by ahmedabdelhafez** [comment]
any one have a solution

**Comment by geromegrignon** [comment]
@ahmedabdelhafez you'll find proper channels there: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem
