### ISSUE TITLE
Can't import the named export 'BehaviorSubject' 

### ISSUE THREAD

**Issue by bonnybros** [angular/angular#44846]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

While trying to use the package angular-in-memory-web-api i am getting the following error. 

./node_modules/angular-in-memory-web-api/fesm2015/angular-in-memory-web-api.mjs 631:38-53
Can't import the named export 'BehaviorSubject' from non EcmaScript module (only default export is available)

### Please provide the exception or error you saw

```true
Namespace '"/Users/~/angular-tour-of-heroes/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

Module '"@angular/common"' has no exported member 'XhrFactory'.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 8.0.6
Node: 14.15.4
OS: darwin x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cli                      8.0.6
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.4.0
typescript                        2.9.2
webpack                           4.30.0
```

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

Could you please provide a minimal reproduction in a form of a GitHub repo (with the minimal possible setup to reproduce the issue), so that we can investigate the problem?

**Comment by JoostK** [comment]
You're seemingly using a recent version of `angular-in-memory-api` for Angular 13 together with Angular 8. This is not a supported configuration.

For Angular 8 you'd probably need to install `angular-in-memory-web-api@0.8.0`. But you should consider updating to a more recent version of Angular, as versions older than Angular 11 are not supported anymore.
