### ISSUE TITLE
Horizontal Content overflow in mobile browsers

### ISSUE THREAD

**Issue by fru2** [angular/angular#44850]
### Description

Some pages in mobile device can be scrolled horizontally if they contain a wide table in it. 

### What is the affected URL?

https://angular.io/guide/workspace-config, https://angular.io/guide/releases

### Please provide the steps to reproduce the issue

Page like https://angular.io/guide/workspace-config (and many more) when opened in mobile browser.

### Please provide the expected behavior vs the actual behavior you encountered

Only the table(s) need to be scrolled horizontally in order to fit all columns rather than allowing the whole page to be scrolled in horizontal direction.

### Please provide a screenshot if possible

<img width="435" alt="image" src="https://user-images.githubusercontent.com/27368177/151318944-77411686-0c3f-4eef-9d64-dced2036f26c.png">

**Comment by gkalpak** [comment]
Reopening, because we are reverting the fix (as it broke tables in a different way): #44899
