### ISSUE TITLE
core: better errors for malformed bindings

### ISSUE THREAD

**Issue by btford** [angular/angular#4485]
Consider `[router-link="['/HomeCmp']"]` (as opposed to `[router-link]="['/HomeCmp']"`; the closing square bracket is in the wrong place).

Right now, this silently fails.

**Comment by pkozlowski-opensource** [comment]
@btford Ha, this is an interesting one! So, when a browser parses this it will come up with `<a [router-link="['/HomeCmp']" ]="">` (BTW, it also proves, in a funny way, that using `]` as an attribute name is "legal" :-))

I still have to dive into the new compiler, but we will have hard time tracking down / properly reporting such errors if we use browsers to parse things. One more argument to consider https://github.com/angular/angular/issues/4417 ?

**Comment by btford** [comment]
Closing as this is stale
