### ISSUE TITLE
can't call the function with parameter

### ISSUE THREAD

**Issue by ali0707** [angular/angular#44874]
### Description

I just integrated amchart5 with Angular 13 ( it's a hierarchy chart with nodes)  every thing works fine the problem is in the call of the function that i did ( by the way when i call the function from html like this (<button (click)="function()"></button>) it works But i don't like to call it there i want to call the function inside the component file ( in the amchart5 button) 
![function](https://user-images.githubusercontent.com/35613425/151513488-4871c2ef-0b86-4700-8385-b6db8e509b1e.png)
![Screenshot 2022-01-28 092622 - Copie](https://user-images.githubusercontent.com/35613425/151513492-402f38e6-4253-4d8f-b989-63d6ac7c9f7d.png)

### Proposed solution

I just integrated amchart5 with Angular 13 ( it's a hierarchy chart with nodes)  every thing works fine the problem is in the call of the function that i did ( by the way when i call the function from html like this (<button (click)="function()"></button>) it works But i don't like to call it there i want to call the function inside the component file ( in the amchart5 button) 
![function](https://user-images.githubusercontent.com/35613425/151513488-4871c2ef-0b86-4700-8385-b6db8e509b1e.png)
![Screenshot 2022-01-28 092622 - Copie](https://user-images.githubusercontent.com/35613425/151513492-402f38e6-4253-4d8f-b989-63d6ac7c9f7d.png)

### Alternatives considered

I just integrated amchart5 with Angular 13 ( it's a hierarchy chart with nodes)  every thing works fine the problem is in the call of the function that i did ( by the way when i call the function from html like this (<button (click)="function()"></button>) it works But i don't like to call it there i want to call the function inside the component file ( in the amchart5 button) 
![function](https://user-images.githubusercontent.com/35613425/151513488-4871c2ef-0b86-4700-8385-b6db8e509b1e.png)
![Screenshot 2022-01-28 092622 - Copie](https://user-images.githubusercontent.com/35613425/151513492-402f38e6-4253-4d8f-b989-63d6ac7c9f7d.png)

**Comment by eneajaho** [comment]
Convert `function(ev) {}` to an arrow function: `(ev) => {}` ;
Because inside function you loose `this` reference, because it has it's own, that's why arrow function is recommended, because it doesn't introduce it's own `this`. 

More here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions
