### ISSUE TITLE
Avoid Clipboard Copy / paste

### ISSUE THREAD

**Issue by NiranjanShah** [angular/angular#44877]
### Which @angular/* package(s) are relevant/releated to the feature request?

forms

### Description

Is it possible to avoid Clipboard copy / paste in the textarea.

### Proposed solution

Event or notification required, in case, the copy / paste option is triggered from clipboard

### Alternatives considered

Custom Keyboard !!!!!

**Comment by JoostK** [comment]
Could you please expand on what you expect from Angular, as this sounds like a request for some browser feature to me?

**Comment by jessicajaniuk** [comment]
I'm going to close this as you can just add your own event listener to prevent pasting to any input field already.

**Comment by NiranjanShah** [comment]
Basically we want to prevent user from copying the clipboard contents in the mobile browser.

Unfortunately there are limitations in custom keyboard in terms of getting the char codes of few of the keys in android mobile browser, so we cannot use custom keyboard and now to restrict the users from copy / paster, we are dependent on Angular.

Hope it is clear now.

Regards,

Niiranjan G Mandan

**Comment by NiranjanShah** [comment]
We had done the same, however the paste event is not triggered when paste is done from Clipboard.

PS: As of mobile phone keyboards, have the capability to store the content and the same can be pasted by selecting it from options available in the keyboard.

Regards,

Niiranjan G Mandan
