### ISSUE TITLE
Better error message for nullish coalescing a pipe argument

### ISSUE THREAD

**Issue by dgp1130** [angular/angular#44871]
### Which @angular/* package(s) are relevant/releated to the feature request?

compiler-cli

### Description

Operator precedence between nullish coalescing an a pipe argument can be confusing. Often they are used together in this way:

```html
<span>{{ birthday | date: 'YYYY-MM-dd' ?? 'Unknown' }}</span>
```

In this case the developer probably intended for the birthday to be formatted like "YYYY-MM-dd", and if that format returned `null` or `undefined` for some reason (such as `birthday` being `null` or `undefined`), then it should fall back to "Unknown". However in practice, the `??` has higher precedence than the `|`, so it actually does `'YYYY-MM-dd' ?? 'Unknown'`, which is useless.

```html
<!-- How the developer wanted it to work. -->
<span>{{ (birthday | date: 'YYYY-MM-dd') ?? 'Unknown' }}</span>

<!-- How it actually works. -->
<span>{{ birthday | date: ('YYYY-MM-dd' ?? 'Unknown') }}</span>
```

This mistake should be highlighted to users to bring awareness about the issue and how to properly parenthesize the expression to do what they want.

### Proposed solution

We already have [an extended diagnostic for a useless nullish coalescing operator](https://angular.io/extended-diagnostics/NG8102), which is triggered by `'YYYY-MM-dd' ?? 'Unknown'` and [correctly identifies this mistake](https://github.com/angular/angular/pull/43419). Unfortunately the error message is a bit unclear. We should either adjust the diagnostic or add a new one to specifically call out this pipe use case and suggest adding parentheses in the right manner.

### Alternatives considered

Alternatively we could just leave the existing diagnostic as is and accept a less-accurate error message. It does correctly identify the mistake, just with a less-than-ideal error message.

**Comment by atscott** [comment]
Closing as won't fix for the time-being / insufficient votes. As mentioned, the existing diagnostic does warn about the mistake and does have the correct error. It's just less descriptive than it could be. The template AST does not maintain a reference to parent nodes so modifying the existing diagnostic to have more contextual knowledge would be difficult/impossible.
