### ISSUE TITLE
Type '(formGroup: FormGroup) => null | undefined' is not assignable to type 'ValidatorFn'.

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular#44880]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

I created a SO post for it here:

https://stackoverflow.com/questions/70895216/declaring-the-correct-type-for-an-angular-reactive-forms-cross-property-validato

When passing in the third argument to `new FormGroup(...,...,...)` the following linting error is produced:

```
Type '(formGroup: FormGroup) => null | undefined' is not assignable to type 'ValidatorFn'
```

And IIUC the `ValidatorFn` type does not fit the signature`'(formGroup: FormGroup) => null | undefined' ` which is passed to the third argument of `new FormGroup(...,...,...)`.

### Please provide a link to a minimal reproduction of the bug

https://stackoverflow.com/questions/70895216/declaring-the-correct-type-for-an-angular-reactive-forms-cross-property-validato

### Please provide the exception or error you saw

```true
Argument of type '(formGroup: FormGroup) => null | undefined' is not assignable to parameter of type 'ValidatorFn | ValidatorFn[] | AbstractControlOptions | null | undefined'.
  Type '(formGroup: FormGroup) => null | undefined' is not assignable to type 'ValidatorFn'.
    Types of parameters 'formGroup' and 'control' are incompatible.
      Type 'AbstractControl' is missing the following properties from type 'FormGroup': controls, registerControl, addControl, removeControl, and 3 more.ts(2345)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Node: 16.13.0
Package Manager: npm 8.1.0
OS: darwin x64

Angular: 12.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@angular/cdk                    12.0.2
@angular/material               12.0.2
@schematics/angular             12.0.1
ng-packagr                      12.0.2
rxjs                            6.6.7
typescript                      4.2.4
```

**Comment by JoostK** [comment]
That error seems correct to me. The `ValidatorFn` only guarantees that it is called with an `AbstractControl`, so typing it as `FormControl` makes a leap of faith that TypeScript isn't happy with. The `undefined` return value is also not expected, as only `ValidationErrors|null` are correct return types.

Can you please share a repro with Angular 12 and 13 that shows this wasn't previously an error?

**Comment by fireflysemantics** [comment]
@Joost I did create a Stackblitz with the implementation from the tutorial:

https://stackblitz.com/edit/angular-ivy-nurvy5

The Stackblitz runs on Angular 12.  When I tried to port the implementation to Angular 13 I started getting the error.

**Comment by JoostK** [comment]
Please share the Angular 13 repo, in that case.

**Comment by inanemed** [comment]
You are using an deprecated FormBuilder.group method because your cross fields validation methods does not respect the type, i tried to make your code functional in Angular 13 here is what i've done :
in your component change that  
`this.v.passwordMatch('password', 'confirmPassword')` To `{ validators: this.v.passwordMatch('password', 'confirmPassword') }`
in the ValidationService change the method signature To `(formGroup: AbstractControl): ValidationErrors | null` 
and in order to acces to form fields you need to use
 `const passwordControl = formGroup.get(password);
  const confirmPasswordControl = formGroup.get(confirmPassword);`
  here is a link to the stackblitz i used : 
  https://stackblitz.com/edit/angular-zyp8yr

**Comment by fireflysemantics** [comment]
I can't share the repo because it's private and part of a library, however these are the minimal pieces needed to reproduce the error and putting these in any Angular 13 component or service should produce the error:

1) A very basic cross validator function:

```
  passwordMatch(password: string, confirmPassword: string) {
    return (formGroup: FormGroup) => {
         return null
     }
}
```

1) A new FormGroup instance with the `passwordMatch` function passed in as the second argument: 

```
  public registrationForm: FormGroup = new FormGroup(
    {
      firstName: new FormControl('', [Validators.required])
    },
    passwordMatch('password', 'confirmPassword')
  );
```

**Comment by fireflysemantics** [comment]
@inanemed I'm using a `new FormGroup` directly instead of using the `FormBuilder`.

**Comment by inanemed** [comment]
@fireflysemantics i updated the stackblitz to use the new FormGroup and it work as expected.

**Comment by fireflysemantics** [comment]
@inanemed did you try it in a local Angular project?  The Angular linter is configured different on Stackblitz than on local projects ...

**Comment by JoostK** [comment]
If I do that then I do get an error, but I get the same error in v12 and the error is expected: the validator is only guaranteed to be called with an `AbstractControl`, not a `FormGroup`, per the `ValidatorFn` declaration.

Here's [a TS Playground repo](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgNUwBsEATTGaAMSTgG8AoOOACmwhSgiIC44BBAEYBnGFBwwAwhzHcAlHzoBfAD5IArkSIBuBkoYNsRTMOECRYidM7d6TZnEwXx2eAF44Y9cF37Dx0zgqaABbAHEudTA4UFQkUjMhURcpGS4iOwc4AHNI6I8vHwMs9iRk9VdoFnsssHVBEmw4UtkiYUUAbQBrYABPPmTkbIBdPiTLV2tWpQAaGocAN2IyCmgAeSg1sBhhAH4+QhJySigaFUOVk5oO4bVNIjlMh2EotBY5XSzmfT90dSRXAgOHAwCZhAB3aCkACyFGwAAsWKDTJCoKQBmIhjNmhx0AgoCEAApg1HouCDJDZR6MLJQYAwdRQWgsdChCIQKJ8YIE9lRR5uAB8T1p9MZtA0Wk+DiUUr8pVEcDp2QQyQoQKQ3JCcA8SGA4KCbLy1WYNIc9lm9mREKhsJgCJYAHIraSHdiHaU8QTiSioQ65AwPgwgA). The error is only reported under `strictFunctionTypes`, perhaps that's where the difference comes from.

**Comment by fireflysemantics** [comment]
@JoostK IIUC the purpose of the second argument to `FormGroup` is pass in Validator instances that can perform cross property / cross field validation.

And so the interface:

```
    return (formGroup: FormGroup) => {
         ...
     }
```

Is what is required in order to be able to do the validation, because we need to be able to grab multiple controls from the `formGroup` instance.

In the articles example these are `password` and `confirmPassword`.

**Comment by JoostK** [comment]
If you want to do that then you'd need to use an explicit cast from `AbstractControl` to `FormGroup`, or disable `strictFunctionTypes`.

**Comment by fireflysemantics** [comment]
@JoostK I don't think this is something that just "I" want to do.

Isn't the purpose of the second argument, which accepts Validators that are not explicitly tied to form controls, to perform cross property validation?

And if so shouldn't the API for `FormGroup` be such that it accepts the signature:

```
 return (formGroup: FormGroup) => {
         ...
     }
```

**Comment by JoostK** [comment]
> It seems to me like the second argument needs a different type from ValidatorFn. It seems ValidatorFn is designed to handle validation of one control and the second argument for FormGroup is designed to accept a validator or multiple validators that do cross property validation, so the type should reflect that ...?

That sounds unrelated to the issue reporting a regression about a compile error.

I can't comment on reporting errors on other controls from within the validator of a parent group, I don't know if that's an intended use-case. You certainly can do that, and you can even use `AbstractControl.get` instead of relying on `FormGroup.controls`.

**Comment by inanemed** [comment]
@fireflysemantics your validator should always return either "nul" or "ValidationErrors" when i see your code the method passwordMatch doesn't return anything in this part of code : 
`if (passwordControl.value !== confirmPasswordControl.value) {` 
`        confirmPasswordControl.setErrors({ passwordMismatch: true });
`
`      } else {
`
`        confirmPasswordControl.setErrors(null);
`
`      }
`
i think it should return somthing like this either null or { passwordMismatch: true }.
because cross field validation try to set errors to FormGroup

**Comment by fireflysemantics** [comment]
Can we clarify one thing?  What is the purpose of the second argument to `FormGroup`?

**Comment by JoostK** [comment]
It's just like any other form control validator: computing the validation status of that control. There is no difference in individual controls, form arrays or form groups from this perspective; they all have validation errors and corresponding status.

**Comment by fireflysemantics** [comment]
@JoostK the second. argument to `FormGroup` does not tie to any specific control ...

**Comment by JoostK** [comment]
`FormGroup` _is_ a control (it inherits from `AbstractControl`)

**Comment by fireflysemantics** [comment]
@JoostK do you have a concrete example that you can show.  Why does the `FormGroup` have a second argument at all?

**Comment by JoostK** [comment]
Why wouldn't it have? A form group can have a validator associated with it to compute its errors and status of the whole group, just like any other control.

**Comment by fireflysemantics** [comment]
@JoostK do you have a single example of how a validator can be associated with the `FormGroup` as a whole to compute its errors?

**Comment by JoostK** [comment]
It's just any regular validation function:

```ts
function matchingPasswordsValidator(group: AbstractControl) {
  if (group.get('password')!.value !== group.get('passwordConfirm')!.value) {
    return {'differentPasswords': true};
  } else {
    return null;
  }
};
```

**Comment by JoostK** [comment]
I can imagine how typing the validators of a control using the appropriate type would be beneficial, but that's an entirely different question than this regression report.

**Comment by fireflysemantics** [comment]
@JoostK I think I get what you are saying now ... :) ... I'll play around with this for a little ...

**Comment by fireflysemantics** [comment]
OK!!  @JoostK and @inanemed thanks so much for all your input on this.  It's working fine now.  This is the new implementation.

```
   passwordMatch(password: string, confirmPassword: string):ValidatorFn {
    return (formGroup: AbstractControl):{ [key: string]: any } | null => {
      const passwordControl = formGroup.get(password);
      const confirmPasswordControl = formGroup.get(confirmPassword);
      
      if (!passwordControl || !confirmPasswordControl) {
        return null;
      }

      if (
        confirmPasswordControl.errors &&
        !confirmPasswordControl.errors.passwordMismatch
      ) {
        return null;
      }

      if (passwordControl.value !== confirmPasswordControl.value) {
        confirmPasswordControl.setErrors({ passwordMismatch: true });
        return { passwordMismatch: true }
      } else {
        confirmPasswordControl.setErrors(null);
        return null;
      }
    };
  }
```

One thing to not, for anyone looking to do something similar is that the implementation both returns the error and sets the error on the control for which the error should display.

I think this can be closed now, unless there are any regression questions.  I noticed that there's very little documentation for this scenario ... I'll write an article and link it.  Thanks again for all the help!

**Comment by JoostK** [comment]
Cool, thanks for following up.

**Comment by fireflysemantics** [comment]
This is a writeup with embedded demo:

https://developer.fireflysemantics.com/tasks/tasks--angular--validating-passwords-with-angular-reactive-forms
