### ISSUE TITLE
Missing forwardRef in ViewChild/ViewChildren should throw

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular#4489]
Follow up of https://github.com/angular/angular/issues/4174

I'm updating this issue to a38, still reproducible. I added an issue with `@ViewChild` that returns null instead when there's no `forwardRef`.

```typescript
@View({
  template : `
  <child></child>
  <child></child>
  `,
  directives: [forwardRef(() => Child)]
})
class Parent implements AfterViewInit {
  
  // Length : 2
  //@ViewChildren(forwardRef(() => Child)) children: QueryList<Child>;
  
  // Length : 0
  @ViewChildren(Child) children: QueryList<Child>;
  
  // Returns the child
  //@ViewChild(forwardRef(() => Child)) child : Child;

  // Returns null
  @ViewChild(Child) child : Child;

  afterViewInit() {
    console.log(this.child);
    console.log(this.children);
  }
}

@Component({selector : 'child'})
@View({template : 'I\'m a child!'})
class Child {}
```

Again, I assume that ContentChild/ContentChildren works the same way that ViewChild/ViewChildren so I didn't test the issue against both of them.

Repro http://plnkr.co/edit/zWmKMQ

**Comment by mgechev** [comment]
@pkozlowski-opensource I guess the `DirectiveResolver` should be responsible for throwing an error here?

**Comment by mgechev** [comment]
Same issue is valid for `ContentChildren` and `ContentChild` as well. I'm working on this issue.

**Comment by ericmartinezr** [comment]
Still reproducible with beta 16 http://plnkr.co/edit/2Jp2p51nWATtqoTR1kSj?p=preview

**Comment by mgechev** [comment]
I can take this one next week or the week after ng-conf.
