### ISSUE TITLE
Typed forms

### ISSUE THREAD

**Issue by InternalVoice** [angular/angular#44894]
### Description

The problem is to update a form with new data when you have sophisticated form structure: a set of `FormGroups` with nested `FormArray`s which can be populated both with `FormControl`s or `FormGroup`s which contain another level of nested `FormArray`s and even deeper. So when we create the form we have empy `FromArray`s at top level so we can't just use `setValue`/`patchValue` and that's where it becomes a real hell to update such "empty" form with real data.

### Proposed solution

Can we have a possibility to somehow supply a form with it's future structure despite that fact the form itself is empty from the beginning? This way we have an ability to simply use `setValue`/`patchValue` on the "root" form of any complexity and nesting level.

### Alternatives considered

I don't really see any alternatives to simply use `setValue`/`patchValue` on complex nested forms with multilevel `FormArray`s

**Comment by dylhunn** [comment]
I assume you are talking about typed forms, when that project lands. It will be possible to do something like this by using optional controls:

```
const restaurant = new FormGroup<{menu?: FormGroup<{entree?: FormControl<string>}>}>({});
restaurant.value; // {}
restaurant.addControl('menu', new FormGroup({})); // Dynamically add a control
```

**Comment by InternalVoice** [comment]
Basically, that's what I'm want to do:

```
const form = new FormGroup({
  project: new FormControl(null);
  tasks:   new FormArray([]); // (*1)
});

const formData = {
  project: "My super project",
  tasks: [
    { _id: "1", name: "Implement splash page": priority: 3 },
    { _id: "2", name: "Implement home page": priority: 1 },
    { _id: "3", name: "Implement settings page": priority: 4 },
  ],
};

form.patchValue(formData); // Or setValue, no matter
```

But I can't do this way bc `tasks` `FormArray` at line (*1) doesn't have information about items (even don't know does each item is a `FormGroup` or a `FormControl`) so I need a possibility to explicitly explain a `form` it's full structure and data node types or so

**Comment by InternalVoice** [comment]
> > even don't know does each item is a FormGroup or a FormControl
> 
> In that case it will not be possible to provide useful type information. Of course, you can still use a dynamic form.

Dynamic forms is not a solution bc main idea is to use `patchValue` to update complex supernested forms w/o tons of manual code for every form within a project
