### ISSUE TITLE
style bugs

### ISSUE THREAD

**Issue by mahdiyehnorouzi** [angular/angular#44891]
### Which @angular/* package(s) are the source of the bug?

elements

### Is this a regression?

Yes

### Description

In NgForOf document style has one bug:
At the end of this page in methods item When you click at the view source button and go to the page below
https://github.com/angular/angular/blob/13.2.0/packages/common/src/directives/ng_for_of.ts#L201-L231
after this when you click at the back button to go back to the previous page the table style get display : block and the table goes wrong 

![bug](https://user-images.githubusercontent.com/68499628/151658456-113c8424-f4fc-4a58-b8ee-2319da0458d5.png)

### Please provide a link to a minimal reproduction of the bug

https://angular.io/api/common/NgForOf

**Comment by dario-piotrowicz** [comment]
Seems like the issue was caused by this PR 3 days ago: https://github.com/angular/angular/pull/44851

**Comment by gkalpak** [comment]
Thx for investigating this, @dario-piotrowicz! I don't know how I missed this when reviewing #44851 🤦‍♂️

**Comment by dario-piotrowicz** [comment]
> Thx for investigating this, @dario-piotrowicz! I don't know how I missed this when reviewing #44851 man_facepalming

No problem, sorry I could not find a good solution :sweat: 

It happens to the best of us to miss stuff :smile:  (also this is an annoying one because the styling is shared and has minor variations, so you might as well have seen it working nicely in an instance and it just doesn't in another :sweat:)

**Comment by fru2** [comment]
> Seems like the issue was caused by this PR 3 days ago: https://github.com/angular/angular/pull/44851

Sorry for the inconvenience. I didn't knew that it was breaking on other devices.

**Comment by dario-piotrowicz** [comment]
> > Seems like the issue was caused by this PR 3 days ago: #44851
> 
> Sorry for the inconvenience. I didn't knew that it was breaking on other devices.

Don't worry it happens to everyone :blush: , I am sure your next contribution will be perfect :smile:
