### ISSUE TITLE
Reactive Form when settings SetErrors on formControl and doing NgIf error disappears.

### ISSUE THREAD

**Issue by verce190** [angular/angular#44908]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

We have a situation where we receive error from the Server and what we do next is set the error to particular form field in our reactive form. We then have a case where we switch tabs with ngIf directive and when we get back the error is gone. We believe this is an angular bug. Sorry if we're wrong. :)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-le2syp?file=src/app/app.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.4
Node: 16.13.0
Package Manager: yarn 1.22.17
OS: darwin arm64

Angular: 13.1.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.4
@angular-devkit/build-angular   13.1.4
@angular-devkit/core            13.1.4
@angular-devkit/schematics      13.1.4
@angular/cli                    13.1.4
@schematics/angular             13.1.4
rxjs                            6.6.7
typescript                      4.4.4
```
_No response_

**Comment by AndrewKushnir** [comment]
@verce190 thanks for reporting the issue and providing a repro. You mentioned that this is a regression, could you please let us know which versions you used before where the behavior was different? Thank you.

**Comment by verce190** [comment]
Sorry, I've updated the post. We've only noticed this on the version listed above.

**Comment by JeanMeche** [comment]
I'd say this behaviour is expected. 

`*ngIf="false" will destroy the form which will then trigger `onDestroy` the `FormGroup` directive, which will trigger the validators. The validators will reset the errors. 

When the error is set by a validator, the `error` object is not reset to null.

**Comment by AndrewKushnir** [comment]
@verce190 as @JeanMeche mentioned above, when the form is re-created after the hide->show transition, the validation is triggered (to bring the form to the up-to-date state), which returns "success", because there are no validators applied. The solution would be to either re-apply the errors once the tab (that contains the form) in your app becomes active, or create a custom validator (and apply it on a form group level), which would use the data that you provide from the server-side. Thank you.
