### ISSUE TITLE
Project not buildable when using styleUrls in a library project component

### ISSUE THREAD

**Issue by hwanders** [angular/angular#44902]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

#### Summary
In a fresh workspace with a newly generated library, externalizing inline styles into a separate file next to a component, makes project builds fail.

#### Detailed steps
1. Create a new Angular workspace: `ng new angular-style-bug --no-create-application` and enter the created folder
2. Create a new library: `ng generate library test-lib`
3. Create a `test-lib.component.css` next to the generated demo component `test-lib.component.ts`
3. In `test-lib.component.ts` replace the inline `styles` by a single external style using `styleUrls` containing one element `'./test-lib.component.css'`
4. Run `ng build` (in the project root)

During the build, an error will appear on the console (see below).

I think
* this should build a component with styles
* even if I missed a configuration, a more helpful error message should appar
 

### Please provide a link to a minimal reproduction of the bug

https://github.com/hwanders/angular-library-component-styles

### Please provide the exception or error you saw

```true
Building Angular Package

------------------------------------------------------------------------------
Building entry point 'test-lib'
------------------------------------------------------------------------------
✖ Compiling with Angular sources in Ivy partial compilation mode.
Transform failed with 1 error:
error: Invalid version: "15.2-15.3"
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.0
Node: 16.13.2
Package Manager: npm 8.4.0
OS: win32 x64

Angular: 13.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.0
@angular-devkit/build-angular   13.2.0
@angular-devkit/core            13.2.0
@angular-devkit/schematics      13.2.0
@schematics/angular             13.2.0
ng-packagr                      13.2.0
rxjs                            7.5.2
typescript                      4.5.5
```

### Anything else?

Removing the single element in the component's `styleUrls` metadata property will make the project build successfully again.

**Comment by JoostK** [comment]
This is caused by some downstream dependency update that breaks the CLI; this is being tracked in angular/angular-cli#22606.
