### ISSUE TITLE
Forms: improve `email` validator directive docs

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#44937]
### Description

Currently, [the `Validators.email` page](https://angular.io/api/forms/Validators#email) explains the email validator logic and talks about the standard that we rely on. However [the `EmailValidator` page](https://angular.io/api/forms/EmailValidator), which describes the email validator for template-driven forms doesn't have that info. The proposal is to add a sentence that would mention the email validation format and refer to the `Validators.email` page (something like: `The email validation is based on the WHATWG HTML specification with some enhancements to incorporate more RFC rules. More information can be found on the [Validators.email page](api/forms/Validators#email).`).

**Comment by ameryousuf** [comment]
@AndrewKushnir If no one is working on this issue, I can take care of it.

**Comment by AndrewKushnir** [comment]
@ameryousuf sure, thanks for the help!

**Comment by ameryousuf** [comment]
@AndrewKushnir I created the PR, thanks!

**Comment by AndrewKushnir** [comment]
Closing this PR since https://github.com/angular/angular/pull/45014 is now merged.

@ameryousuf thanks for improving Angular docs!
