### ISSUE TITLE
@angular/router: strict typing for `title` property

### ISSUE THREAD

**Issue by markostanimirovic** [angular/angular#44936]
### Which @angular/* package(s) are relevant/releated to the feature request?

router

### Description

The `title` type in [`Route`](https://github.com/angular/angular/pull/43307/files#diff-8720c33fa3535768ea516ea7c7ac148d769f82eb0f69cff63352071edba8569dR377) interface is `string | unknown`. 

### Proposed solution

The `title` type should be `string | Type<Resolve<string>>`.

- [`Type`](https://github.com/angular/angular/blob/master/packages/core/src/interface/type.ts#L37) interface from `@angular/core`
- [`Resolve`](https://github.com/angular/angular/blob/master/packages/router/src/interfaces.ts#L387) interface from `@angular/router`

Moreover, we can create a new type for title resolve:

```ts
type TitleResolve = Resolve<string>;

interface Route {
  title?: string | Type<TitleResolve>;
}

// usage
class CustomTitleResolver implements TitleResolve {
  resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): string | Promise<string> | Observable<string> {
    // ...
  }
}
```

**I will submit the PR for this feature if the feature request is accepted.** 🙂 

### Alternatives considered

👀

**Comment by atscott** [comment]
@markostanimirovic thanks for the suggestion. I'm definitely in favor `Type<Resolve<string>>` and it's a good improvement. I'm not sold on the new type alias `TitleResolve`. Could you send a PR for `Type<Resolve<string>>` and we can discuss the other option during the public API review?

**Comment by markostanimirovic** [comment]
> @markostanimirovic thanks for the suggestion. I'm definitely in favor `Type<Resolve<string>>` and it's a good improvement. I'm not sold on the new type alias `TitleResolve`. Could you send a PR for `Type<Resolve<string>>` and we can discuss the other option during the public API review?

Sure!
