### ISSUE TITLE
DevTools for Firefox

### ISSUE THREAD

**Issue by ltennstedt** [angular/angular#44945]
### Description

Please publish the Chrome extension as Firefox add-on on addons.mozilla.org!

### Proposed solution

The Chrome extension has to be ported to a Firefox add-on and then publish to addons.mozilla.org.

### Alternatives considered

I have to move to Brave.

**Comment by pavankjadda** [comment]
👀👀👀👀

**Comment by ltennstedt** [comment]
I'm very happy about the fact that there are still some Firefox users out there.

**Comment by pavankjadda** [comment]
@mgechev I see #44952 merged. When can we expect this to be published to Firefox store (if not already done so)?

**Comment by mgechev** [comment]
@gatlinnewhouse could you update your app to v12+ and try again? Do you hit the same issue in Chrome?

**Comment by gatlinnewhouse** [comment]
> @gatlinnewhouse could you update your app to v12+ and try again? Do you hit the same issue in Chrome?

Ah. I thought it might be an issue with this specific app. Unfortunately cannot update this app to v12+

**Comment by mgechev** [comment]
What's the blocker for updating to v12+? We strongly encourage keeping up to date with latest stable release. Are you hitting any `ng update` blockers?

**Comment by annervisser** [comment]
Looks like it's live :eyes::rocket:: https://addons.mozilla.org/en-US/firefox/addon/angular-devtools

**Comment by pavankjadda** [comment]
> Looks like it's live 👀🚀: https://addons.mozilla.org/en-US/firefox/addon/angular-devtools

I see it. Thanks @mgechev and team

**Comment by ltennstedt** [comment]
Thanks for all the work

**Comment by JoostK** [comment]
Closing as DevTools is now available for Firefox!
