### ISSUE TITLE
ApplicationRef is missing createComponent now that ComponentFactoryResolver is deprecated

### ISSUE THREAD

**Issue by penfold** [angular/angular#44947]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

With the deprecation of ComponentFactoryResolver, we should be using ViewContainerRef.createComponent().

But when we are creating a component and adding it to ApplicationRef, we need an ApplicationRef.createComponent.

Otherwise, we still need to use ComponentFactoryResolver to create the component before we ApplicationRef.attachView().

Here is what we are trying to achieve for a popover menu: https://medium.com/hackernoon/angular-pro-tip-how-to-dynamically-create-components-in-body-ba200cc289e6

Or is there a better way to dynamically add a component to the body?

### Please provide a link to a minimal reproduction of the bug

https://medium.com/hackernoon/angular-pro-tip-how-to-dynamically-create-components-in-body-ba200cc289e6

### Please provide the exception or error you saw

```true
N/A
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.0
Node: 16.13.2
Package Manager: npm 8.1.4
OS: win32 x64

Angular: 13.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router

Package                          Version
----------------------------------------------------------
@angular-devkit/architect        0.1302.0
@angular-devkit/build-angular    13.2.0
@angular-devkit/core             13.2.0
@angular-devkit/schematics       13.2.0
@nguniversal/aspnetcore-engine   13.0.2
@nguniversal/common              13.0.2
@schematics/angular              13.2.0
rxjs                             7.5.2
typescript                       4.5.5
```

**Comment by penfold** [comment]
Looking through some old issues is this an approved solution?

i.e. getting the root ViewContainerRef from ApplicationRef.

https://github.com/angular/angular/issues/6446#issuecomment-248912305

**Comment by AndrewKushnir** [comment]
As a part of the upcoming [Standalone Components](https://github.com/angular/angular/discussions/43784), we plan to add extra (more ergonomic) APIs to bootstrap and render a component. We will take this scenario into account as well to make sure that it's covered by the new APIs.

For now, you could still use `ComponentFactory` to achieve the necessary functionality. The `ComponentFactory` will not be removed until we make sure that fundamental scenarios (including this one) are covered by other APIs.

I'm closing this ticket for now, since this question would be a part of a larger design work related to the Standalone Components APIs.

**Comment by MaKCbIMKo** [comment]
We also use `ComponentFactory` to create components. And here is some of our context:

- We create components dynamically within service (not component) -> we don't have direct access to `ViewContainerRef`
- We create components using `ComponentFactory.create` method and pass third argument `rootSelectorOrNode`
- After creating components, we control their lifetime via `ApplicationRef.attachView(...)` and `ApplicationRef.detachView(...)` and it just works by using the same view reference. In case with `ViewContainerRef` it requires us either to somehow control indexes or to somehow use different `ViewContainerRef` for each created component

I was trying to come up with any work-around on how to achieve the same with using only `ViewContainerRef`, but it seems like 'new' API is less flexible: yes, it makes simple case even simpler, but advanced case seems to be impossible to achieve at all.
