### ISSUE TITLE
ViewEncapsulation.Emulated no longer default in alpha38?

### ISSUE THREAD

**Issue by endash** [angular/angular#4494]
I've just updated from alpha37 to alpha38, and all my components are now seemingly rendered with the behaviour `ViewEncapsulation.None`. Manually setting a component's encapsulation to `Emulated` restores the previous behaviour.

Going through the ng2 source, there no longer seems to be any code to make `Emulated` the default. In particular, this line:

`this.encapsulation = isPresent(encapsulation) ? encapsulation : ViewEncapsulation.Emulated;`

formerly of `core/render/api`, in a block of code that seems to have been moved to `core/metadata/view`, is no longer present in the same block of code. While that might be a red herring, it does seem that all remaining references to `ViewEncapsulation.Emulated` are strict comparisons, without any faculty for it to be the fallback.

**Comment by tbosch** [comment]
Thanks.
Yes, ViewEncapsulation.Emulated should be the default!

**Comment by endash** [comment]
Thanks for the fix :+1:
