### ISSUE TITLE
Provide multiple providers from the single provision

### ISSUE THREAD

**Issue by Azbesciak** [angular/angular#44940]
### Which @angular/* package(s) are relevant/releated to the feature request?

core

### Description

Hi, I wonder whether is it possible to add an option to provide multiple providers by single provision;  this way it is possible to make the app more customizable and inject providers on any level - through `useFactory` and dependency, for example. The important thing is that injectors create a tree, so other dependencies visibility matters at this point - that is why providing something further in the tree in a 'lazy' manner is feasible - now you should somehow fetch the lower injector and create the new one based on it, or make some nasty delegation.

### Proposed solution

Let us assume that there is the token `TOKEN_PROVIDER` which should provide `Provider[]`  - this way you could return different providers based on some condition, or just pass these 'created' before - like for `Injector.create()`.

### Alternatives considered

As mentioned in the description now there is a possibility to provide some dummy-delegate implementation and fill it later, but it still does not solve the problem in total, because it could be shared between different nodes in the injector tree.

**Comment by Airblader** [comment]
Can you give a concrete example for this where it would be useful? I'm having a hard time understanding what it is you're wanting to do.

**Comment by Azbesciak** [comment]
Now we have 2 ways (at least which come to my mind) to provide providers:
1) by module/component provision, in decorator like
```ts
@Component({
...
   providers: [{
       provide: SOME_TOKEN,
       deps: [a, b, c],
       useFactory: (a, b, c) => y
   }]
})
export class X {}
```
at this point new injector node is created, so if this component belongs to module `Y`, providers of class `X` see `Y` providers (maybe with `@SkipSelf` requirement), but these from `Y` cannot see these from class `X`, because we have a tree structure. The same applies for lazy loaded modules (in general - for everything which is not on the same injector level).

2) When you create some instance of your own component, for example for overlays, dialog, etc, or when you want to provide  lazy modules (with `loadChildren`) compiled with `Compiler` or `NgModuleFactory`,  you can provide your own `Injector`. At least in my use case, I often need to extend that injector with my own providers (with `Injector.create({providers:[]})`). 

So, the problem is that these approaches currently are not mergeable, I mean - if I want to do something like in 2) I need to provide these providers directly or inject these to the call place (the variable need to be accessible for `Injector.create()`). And it is not a problem as long as I _want to call `Injector.create()`_, because sometimes I would just want to do the same in `@NgModule`/`@Component` in `providers` scope (sometimes I just cannot call `Injector.create` [my desired `Injector` is created by the `@Component`] or the call place is not accessible/it is too depth). But, the problem is that there is no flexible way to provide (or not) tokens I want. 

From high abstraction, the example of what I expect - the higher-order components provide consumers for internally created injectors in sub components with their own providers (so `@Component` with `providers`), then you would have something like this:
```ts
@Component({
...
   providers: [{
       provide: TOKEN_PROVIDER,
       deps: [CONFIG],
       useFactory: (cfg) => cfg.a ? [providerA, providerB] : [providerC] // or even nothing
   }, providerE,
      provider F,
    ]
})
```

Then `providerA`, `providerB` and `providerC` would also see and depend on `providerF` (or these would depend on `providerA/B`, which otherwise is not possible, because:
1) when I would provide `providerA/B` on the higher than this component level (in parent) these would not see `providerE/F`
2) when I would use the injector created in this component, there are some ways to allow `providerA/B` to use `providerE/F`, but it is only via `injector.get()`, and these cannot cooperate, not to mention the case when you have multiprovider and you just want to extend some behavior/processing pipe (ok, there is `@SkipSelf`, but still you can lose some functionality if you are one/n levels higher than the consumer).

Hope it helps, if not let me know.

**Comment by alxhub** [comment]
I don't believe there's a sufficiently strong use case for this in Angular. A similar effect is possible today, as long as the config doesn't need to be injected:

```
providers: [
  cfg.a ? [...] : [...]
]
```

**Comment by Azbesciak** [comment]
But the case is that the config need to be injected, or providers from 'above'.

> there's a sufficiently strong use case for this in Angular

What does it mean? internally in Google? Guys, if you provide tree-based injector, and at the same time there is a possibility to use multiple providers of the same type... I think this is a must have, and was for the last 5 years. I need this for the last 3 years, but now I am a bit frustated of those workarounds with delegating providers, which is still not perfect.

Most of your users use just DI as injecting type, I suppose that 90% even do not use multi providers. Do not expect requests like this. Rest of these users probably write their own proxy frameworks on this if they need something. Please, take look at the dates and your approach - I made this ticket a week ago, provided extended example and a couple of reasons, and the only answer is that 'there is no suitable use case in angular'...

**Comment by alxhub** [comment]
> What does it mean? 

I mean that the cost of supporting this feature is high, and it's not clear the benefits are worth it.

To assess this tradeoff, we look at things like:

* What is the implementation cost? In this case, it would add significant complexity to our injector implementations.
* Are there existing challenges in component design that would be addressed by this feature? Are there alternative patterns for addressing these challenges that don't require changes to Angular?
* Are there existing design patterns that could be improved or simplified with this feature?
* How hard is the new behavior to explain to developers? Does adding this functionality make Angular's behavior significantly harder to understand?

We'll leave this ticket open, to gauge community interest via our feature request voting process and to discover these use cases. In particular, I'd be interested in learning more about your use case - what are you doing in your component designs that requires runtime-configurable providers?

**Comment by Azbesciak** [comment]
Ok, so my own example. I am preparing Map application (like GMaps). It can act as a separate app, but also as embedded as an angular component inside another angular (or even not) app.

There are multiple piplines, one of them are services which provide map visualizations (markers, polylines, shapes) on their own. For this they need the `MapService` which is served in the component scope (I do not use root scope, or in very Little scope - I prefer high isolation);these services can be provided on the same level or further than the `MapService`. 

Now imagine that I want to allow my conponent's client to add their own markers. The component is isolated, the Service is in the component scope. So now there are two ways
- own delegate which satisfy some existing in the component scope token injection, which is later filled with the actual provider (based on the injector create in the isolated component and passed somehow later, very bad and complex) 
- a bit more simple, but very limited - use patent scope and in callback argument pass all required services. The problem is that in that case there are more that just map Service, for example markers factory Service, tooltip factory, some other behaviors, some specific services. So, again I can pass the injector again. The problem is that this is not the only place where I can customize the app, so in practice I should add injector to the every in most of services' metod call. 

Not to mention that this is only static use case. The second one is a Dynamic configuration - for example I pass that in the given component I need a route view or geocode, and then I can prepare the view as I want. Ok, now I can do it with the router for example, and I do so. But then - what if some use cases use the some share between them functionalities, like we have view A, B And C, A uses X and Y, B uses Y and Z, C uses X and Z. Now these views need to use these scopes inline. It may be clean (separated use), but if I could provide a factory, I would even expose pro vision of given services outside, so my client would decide whether the given view has some capabilities (X, Y, Z, etc). 

Please remember that the root scope is not an option.

And The Last use case - imagine that you have multiple components, which need some component scope Service, like Input with autosuggest. These services can have state, to make things more complex. Now it cannot be achieved (ok, you can keep the state in the component and pass it via the metod arguments do given Service, but please notice that we use multiple providers, things get a bit complicated - you need to keep the map of provider-state inside the component). 
With proposed solution you just could provide the factory which is able to provide given Service instance in every required scope, and each of these scopes could be separated and on the different level. 

Hope it shapes the a idea a bit. Also deffered provision would be a great idea (something like lazy loading) but this is a different topic.
-

**Comment by marcinmilewicz** [comment]
This is exactly what I've looked for recently.

**Comment by kemsky** [comment]
@Azbesciak, maybe I did not understood something, but you can provide services at any level using directive and 'ng-container'.

Provide default services with a single directive (using providers):
```html
<ng-container gmapScope="optional: params/name">
    ...
    // default services here
   <component>
       // some default services were replaced by component
        <gmap></gmap>
   </component>
    ...
</ng-container>
```
Another approach with directives as services:
```html
<ng-container provideMarkerService provideConfigService provideShapeService>
    ...
    // default services here
   <component>
       // some default services were replaced by component via providers serction
        <gmap></gmap>
   </component>
    ...
</ng-container>
```

**Comment by Azbesciak** [comment]
@kemsky Ok, now imagine that `gmap` provides his own services via multple provision, in component scope `providers`. You want to provide the same type of service (token actually), and at the same time you want that this service see others provided by `gmap`, and notice that we are not in the `root` scope.

**Comment by kemsky** [comment]
@Azbesciak, in my example `gmap` does not provide any services on its own, it consumes 'above' services from scope or directives, so if you need to acces resulting set of  services you can do it at the component level or anywhere in between. Services flow through any nested components, you don't have to limit yourself to view-only or host-only providers, it also works for dynamic componets if you use correct injector. You can even handle multiple scopes if you want.

**Comment by Azbesciak** [comment]
@kemsky Yup, and my issue target at injecting in a given scope, actually. Of course, that scope needs to allow for it. Now there is a very limited way for it. Please, read my ticked once again.

Above services are not anything special, you have @SkipSelf and @Self. But, please notice that these services from @SkipSelf do not see ones from @Self. I need this. The only way is to get the child injector and introspect it, but it is still a) not perfect b) dirty c) do not satisfy all needs d) need to be done manually - not at the framework level
