### ISSUE TITLE
Extended diagnostics quick fix

### ISSUE THREAD

**Issue by dgp1130** [angular/angular#44941]
### Which @angular/* package(s) are relevant/releated to the feature request?

compiler-cli, language-service

### Description

Extended diagnostics often have a suggestion solution. This is by design, since they are intended to identify specific mistakes often made by developers with clear solutions or best practices. Since these fixes are so mechanical, we should give an easy, automated way to apply them to a diagnostic.

### Proposed solution

Extended diagnostics should be able to generate a set of possible "quick fix" transformations which IDE's can use to address the diagnostic. In the case of `invalidBananaInBox`, we could automate a change like:

```html
<div ([foo])="bar">Hello</div>
<!-- Fixes to... -->
<div [(foo)]="bar">Hello</div>
```

@danieltre23 came up with a prototype in https://github.com/danieltre23/angular/commit/52f6a7af6c36ee05eef0c67e159c5a8828a42bc3 and was able to demo the feature. It's a relatively small commit so I don't think this is a significant amount of effort. The work here is to define the "quick fix" data type in the compiler, we'll need something custom since we don't want to depend on VSCode / LSP types here (curious how `tsc` does this?). The language service / VSCode extension will then need to transform the "quick fix" type into VSCode-compatible "code actions", which the IDE can show and apply with a single click.

### Alternatives considered

N/A

**Comment by JamesHenry** [comment]
FYI we intend to deprecate the banana-in-box lint rule once auto-fixing is implemented: https://github.com/angular-eslint/angular-eslint/issues/660

**Comment by atscott** [comment]
@JamesHenry Good to know! I've removed the `insufficient votes` label since I think this is relatively low hanging fruit and really is something we should take on. As a note, we do make use of upvotes on feature requests to gauge community interest and prioritize projects so it's really helpful to hit that thumbs up button on issues :)

**Comment by ivanwonder** [comment]
@JamesHenry 

FYI, I have opened a PR to support fixing the invalid banana in box.
