### ISSUE TITLE
CHANGELOG.md size over 1MB cannot be read with format through github

### ISSUE THREAD

**Issue by jmbarbier** [angular/angular#44953]
### Description

Angular CHANGELOG.md is a precious piece of info.
With the latest versions, the file size is now over GitHub md viewer limits, and the file can only be seen as raw
Even if markdown is not the worst human reading format in the world, this is way harder than rendered html.

Maybe the CHANGELOG.md could be splitted, only keeping the N more recent releases, and have linked follow-ups (CHANGELOG.x.md or CHANGELOG.yyyy.md, or any) in order to ensure readability.

### What is the affected URL?

https://github.com/angular/angular/blob/master/CHANGELOG.md

### Please provide the steps to reproduce the issue

Just go to https://github.com/angular/angular/blob/master/CHANGELOG.md

### Please provide the expected behavior vs the actual behavior you encountered

Seeing rendered HTML vs seeing raw markdown

**Comment by spock123** [comment]
You're quick :)

**Comment by AndrewKushnir** [comment]
@jmbarbier thanks for reporting the issue!

We'll do some cleanup in https://github.com/angular/angular/pull/44956 and will followup with additional tooling/process to move old release notes to a separate file.
