### ISSUE TITLE
alpha.38: The actual type of QueryList<T>.changes is EventEmitter

### ISSUE THREAD

**Issue by todoubaba** [angular/angular#4496]
So the [changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes) and [the jsdoc of `QueryList`](https://github.com/angular/angular/blob/master/modules/angular2/src/core/linker/query_list.ts#L25) is misleading, `changes` does not have the `subscribe` method.

**Comment by ericmartinezr** [comment]
You can use as a workaround

```typescript
query.changes()._subject.subscribe()
```

[EventEmitter](https://github.com/angular/angular/blob/master/modules/angular2/src/core/facade/async.ts) is not exposing `Subject` anymore (through `toRx()`).  I don't know if that is intended and the usage changed too, or is just a mistake.

**Comment by rkirov** [comment]
Not exposing Subject is a bug due to be fixed when #4540 lands. It is intended for `query.changes` to behave like any other observable in the system.

**Comment by ericmartinezr** [comment]
@rkirov if that's the case [this line](https://github.com/angular/angular/blob/master/modules/angular2/src/core/linker/query_list.ts#L34) should return `this._emitter.toRx()`

**Comment by rkirov** [comment]
@ericmartinezr that doesn't sound crazy, let me check with the RX experts and reopen if it makes sense. In any case the urgency of this fix is lower given `query.changes().toRx().subscribe()` workaround.

**Comment by todoubaba** [comment]
@ericmartinezr +1
