### ISSUE TITLE
Packeges are not appear in the installation

### ISSUE THREAD

**Issue by Omer2604** [angular/angular#44967]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I miss the packege of the bootstrap (where the new modules) although it appear in the installation of my teacher
Someone know why it happens and how can I fix this?
thnak you 

### Please provide a link to a minimal reproduction of the bug

https://imgur.com/k9qBQpM

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.2
Node: 16.13.1
Package Manager: npm 8.3.0
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1302.2 (cli-only)
@angular-devkit/core         13.2.2 (cli-only)
@angular-devkit/schematics   13.2.2 (cli-only)
@schematics/angular          13.2.2 (cli-only)
```

**Comment by JoostK** [comment]
I am sorry but this seems like a problem with your setup/configuration. Please ask your teacher for help, they should be able to help you out here.
