### ISSUE TITLE
alpha-38: Need @Inject to inject ElementRef and DynamicComponentLoader

### ISSUE THREAD

**Issue by todoubaba** [angular/angular#4497]
DI works fine in alpha-37, now it needs `@Inject`.

**Comment by PascalPrecht** [comment]
@todoubaba could you provide more context here (ideally a plunk)? Usually you need to use `@Inject` if no metadata is generated, which is usually the case when injecting services into services. But it's hard to tell if there's no actual code we can take a look at.

**Comment by todoubaba** [comment]
@PascalPrecht code.angularjs.org does not have alpha.38, I can not create a plunker.
HTML:
```HTML
<!DOCTYPE html>
<html>
<head>
	<title>test</title>
	<script src="../../dist/dev/lib/traceur-runtime.js"></script>
	<script src="../../dist/dev/lib/system.js"></script>
	<script>
		System.config({
			defaultJSExtensions: true
		});
	</script>
	<script src="../../dist/dev/lib/angular2.min.js"></script>
	<script src="../../dist/dev/lib/ts-lib.js"></script>
</head>
<body>
	<my-app></my-app>
	<script>
		System.import("../../dist/dev/test/error");
	</script>
</body>
</html>
```

TS file:
```typescript
import {Component, View, ElementRef, bootstrap} from 'angular2/angular2';

@Component({
	selector: 'my-app'
})
@View({
	template: `<h1>hello</h1>`
})
class MyApp {
	constructor(elementRef: ElementRef) {
		console.log(elementRef);
	}
}
bootstrap(MyApp);
```

error:
```
EXCEPTION: Cannot resolve all parameters for MyApp(?). Make sure they all have valid type or annotations.
angular2.min.js:15 EXCEPTION: Cannot resolve all parameters for MyApp(?). Make sure they all have valid type or annotations.t.logError @ angular2.min.js:15
angular2.min.js:15 STACKTRACE:t.logError @ angular2.min.js:15
angular2.min.js:15 Error: Cannot resolve all parameters for MyApp(?). Make sure they all have valid type or annotations.
    at t [as constructor] (http://localhost/ng27/dist/dev/lib/angular2.min.js:12:22777)
    at new t (http://localhost/ng27/dist/dev/lib/angular2.min.js:2:25365)
    at d (http://localhost/ng27/dist/dev/lib/angular2.min.js:15:31195)
    at http://localhost/ng27/dist/dev/lib/angular2.min.js:15:30698
    at Array.map (native)
    at Function.e.map (http://localhost/ng27/dist/dev/lib/angular2.min.js:2:10165)
    at p (http://localhost/ng27/dist/dev/lib/angular2.min.js:15:30673)
    at i (http://localhost/ng27/dist/dev/lib/angular2.min.js:15:29244)
    at Object.o [as resolveBinding] (http://localhost/ng27/dist/dev/lib/angular2.min.js:15:29514)
    at Function.t.createFromBinding (http://localhost/ng27/dist/dev/lib/angular2.min.js:20:27148)
```

The following code works fine:
```typescript
import {Component, View, ElementRef, Inject, bootstrap} from 'angular2/angular2';

@Component({
	selector: 'my-app'
})
@View({
	template: `<h1>hello</h1>`
})
class MyApp {
	constructor(@Inject(ElementRef) elementRef: ElementRef) {
		console.log(elementRef);
	}
}
bootstrap(MyApp);
```

**Comment by mgechev** [comment]
I started debugging your issue and found that `MyApp` gets transpiled to:

```javascript
// ...
var MyApp = (function () {
    function MyApp(elementRef) {
        console.log(elementRef);
    }
    MyApp = __decorate([
        angular2_1.Component({
            selector: 'my-app'
        }),
        angular2_1.View({
            template: "<h1>hello</h1>"
        }), 
        __metadata('design:paramtypes', [Object])
    ], MyApp);
    return MyApp;
})();
angular2_1.bootstrap(MyApp);
```

Which means that the generated metadata for the param types is wrong. However, if you use `@Inject` instead of `Object` you get `angular2_1.ElementRef`, which is correct.

Another thing I noticed - when using [angular2-seed](https://github.com/mgechev/angular2-seed) with gulp task with the following [src](https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/build.js.dev.js#L14), I get the error. However, if I use target `../app/*.ts` instead everything works.

---

PS: I tried digging into the TypeScript's compiler and saw that parameter type of `elementRef` inside the constructor is incorrect:

```
[ { pos: 186,
    end: 208,
    decorators: undefined,
    dotDotDotToken: undefined,
    name: { pos: 186, end: 196, text: 'elementRef', parent: [Circular] },
    questionToken: undefined,
    type:
     { pos: 197,
       end: 208,
       typeName: [Object],
       parent: [Circular],
       id: 14776 },
    initializer: undefined,
    parent:
     { pos: 169,
       end: 250,
       decorators: undefined,
       typeParameters: undefined,
       parameters: [Circular],
       body: [Object],
       parent: [Object],
       symbol: [Object],
       locals: [Object],
       id: 14775 },
    symbol:
     { flags: 1,
       name: 'elementRef',
       declarations: [Object],
       valueDeclaration: [Circular],
       parent: undefined,
       id: 15949 } },
```

**Comment by r-park** [comment]
I've experienced this same issue with `ChangeDetectorRef` as well.

**Comment by robwormald** [comment]
@r-park could you paste your tsconfig? i'll often see this when i forget to turn on "emitDecoratorMetadata" in the ts compiler options...

**Comment by r-park** [comment]
@robwormald here's my tsconfig:
```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "listFiles": true,
    "module": "system",
    "noEmitHelpers": false,
    "noImplicitAny": false,
    "noLib": false,
    "removeComments": true,
    "sourceMap": true,
    "target": "es5"
  }
}
```

**Comment by Krustie101** [comment]
In alpha-37, ElementRef was a class, now it is an interface.

**Comment by robwormald** [comment]
well, that would explain @mgechev's comment - `[Object]` is the expected result (i believe) when interfaces get transpiled - which is obviously not the expected result for consumers.

**Comment by mgechev** [comment]
@Krustie101 @robwormald [`ElementRef`](https://github.com/angular/angular/blob/2.0.0-alpha.38/modules/angular2/src/core/linker/element_ref.ts#L15) is still a class.

**Comment by Krustie101** [comment]
@mgechev It is a class in angular2/src/core/linker but an interface in the typings file. That is why we got hit by it but not the Angular team itself.

**Comment by todoubaba** [comment]
@Krustie101 You're right. When I change it from `interface` to `class` in typing file, DI works again.

There are many classes like this one, such as `TemplateRef` and `ViewRef`. And there are **two** same declarations for one type in the typing, for example `ElementRef`, one is at line 5365, another is at line 13894.

**Comment by todoubaba** [comment]
The issue is caused by commit https://github.com/angular/angular/commit/4bffd97edd77fc3ed70b043d3c3e373d9221a935#diff-c64239da878646eaecd9a47f36187dceR3.

It converts class with private constructor into interfalce

**Comment by IgorMinar** [comment]
This looks like some type/transpilation issue

A class with a decorator and a constructor like:
```
constructor(private _heroService: HeroService, private _router: Router, private hostElement: ElementRef) { }
```

gets transpiled to:

```
__metadata('design:paramtypes', [hero_service_1.HeroService, router_1.Router, Object])
```

Note that the last paramtype is an Object rather than ElementRef var.

**Comment by IgorMinar** [comment]
This affects everything that is defined in the d.ts file as `InjectableReference`.

e.g. `ElementRef` is defined as:

```
var ElementRef: InjectableReference;
```

@alexeagle, @mhevery did this ever work properly? maybe it didn't and only our recent expansion of classes that got converted to interfaces surfaced this problem.

@alexeagle how close are we with #4518? if #4518 is going to land on tomorrow (Wednesday) then we can skip a fix for this, otherwise we should work on an intermediate fix.

**Comment by alexeagle** [comment]
I am really close, just working through some test failures.. @tbosch is helping me with a failure due to injecting Renderer, then I'll rebase and should be close. Still need a review on that PR as well (misko is out today)

**Comment by IgorMinar** [comment]
alright, so we are going to wait for #4518 to fix this. @tbosch can you please work with @alexeagle to expedite the fix?

**Comment by alexeagle** [comment]
More post-mortem analysis: we have tests in our typings, but these tests only assert that we can compile, not that an angular application runs. Further, our hello world examples don't use custom bindings. We should have an end-to-end test which uses our typings distribution, starts a non-trivial app with custom bindings, and verifies that it starts.

**Comment by IgorMinar** [comment]
fixed as of a40
