### ISSUE TITLE
NG0901

### ISSUE THREAD

**Issue by marin14000** [angular/angular#45003]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

Got an NG0901 and found no docs on internet. The error occurs when i want to navigate into a new page.
This error only occurs from only one page. All the others work correctly.

Here is a link of the bug in video : https://drive.google.com/file/d/1US97vGf5BWp3mq80B563m4cBdO2AOVlq/view?usp=sharing

### Please provide the exception or error you saw

```true
NG0901
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 13.2.2
Node: 16.13.0
Package Manager: npm 8.1.0
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1302.2 (cli-only)
@angular-devkit/core         13.2.2 (cli-only)
@angular-devkit/schematics   13.2.2 (cli-only)
@schematics/angular          13.2.2 (cli-only)
```

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
