### ISSUE TITLE
Route typing not compiling with type ng.Type 

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#4500]
I was updating my Routing code to reflect the latest Angular 2.0 source example. However I noticed that the Router typings for Alpha.38 don't compile:
To work around it I had to tweak the component part from ng.Type to 'any' 
```
class Route implements RouteDefinition {
    
    constructor({path, component, as, data}:
                     //Had to change component to 'any' from ng.Type
                      {path: string, component: any, as?: string, data?: any});
    
    data: any;
    
    path: string;
    
    component: ng.Type;
    
    as: string;
    
    loader: Function;
    
    redirectTo: string;
    
  }
```

**Comment by IgorMinar** [comment]
I can't reproduce this. with a38 or a39. ensure that your typings are up to date (ideally use tsd link to link them from the npm distribution) and if the problem still exists please file a new issue with repro instructions. thanks!
