### ISSUE TITLE
feat: open @see link online documentation from VSCode

### ISSUE THREAD

**Issue by rjanma** [angular/angular#45000]
# 🐞 bug report

### Is this a regression?

Not to my knowledge.

### Description
Intellisense @see links not opening online documentation but instead trying to open local nonexistent file.
If I manually prefix any @see with "https://angular.io" in *.d.ts file link works.

e.g. 
not working: `@see [Using change detection hooks](guide/lifecycle-hooks#using-change-detection-hooks)`
working: `@see [Using change detection hooks](https://angular.io/guide/lifecycle-hooks#using-change-detection-hooks)`

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction
Hover any class or property to get intellisense and if @see link is present it will behave like described.

**Expected behavior**

Online documentation should be opened in browser.

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 13.0.4
Node: 12.22.7
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 13.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cli                    13.0.4
@schematics/angular             13.0.4
rxjs                            7.4.0
typescript                      4.4.4
</code></pre>

Extension Version:
<pre><code>
v13.2.2
</code></pre>

VSCode Version:
<pre><code>
Version: 1.62.3 (system setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
</code></pre>

Operating System:
<pre><code>
Windows_NT x64 10.0.19044
</code></pre>

Extension options:
<pre><code>
"angular.enable-strict-mode-prompt": true,
"angular.log": "off",
"angular.suggest.includeAutomaticOptionalChainCompletions": true,
"angular.suggest.includeCompletionsWithSnippetText": true,
"angular.trace.server": "off",
"angular.view-engine": false,
</code></pre>

**Comment by atscott** [comment]
The `@see` in the documentation notes aren't meant to be links for navigation from vscode. They're used for generating the correct link for `angular.io` when deployed. This _might_ be a feature that could be added to the Angular.io documentation utilities extension. (//cc @gkalpak)

**Comment by rjanma** [comment]
Thank You Andrew, I suspected that might be the case but since I'm relative 'noob' in Angular and learning by inspecting the code, beeing able to open online documentation from VSCode would help all beginers a lot.

Thanks again for considering this as feature request.

br
Marjan Burazer

**Comment by gkalpak** [comment]
As @atscott said, the `@see` annotations are mostly intended to be processed by the doc-generation pipeline and generate links. For example, most of the annotations have backticked code instead of links (for example, `` @see `AnimationBuilder` ``), which the doc-generation pipeline knows how to convert to links.

Maybe we could tweak the DTS files (which I assume is where intellisense retrieves information from to prefix relative links with `https://angular.io/` or alternatively use absolute links in the code and remove the `https://angular.io/` prefix when generating the docs.

##
> This might be a feature that could be added to the Angular.io documentation utilities extension. (//cc @gkalpak)

The Angular.io documentation utilities extension is intended for docs authors, not for Angular app developers.
So, it wouldn't help much :smiley:
