### ISSUE TITLE
Custom validators on blur, not ran when blurring without value change

### ISSUE THREAD

**Issue by GillesVercammen** [angular/angular#45015]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

It seems that custom validators do not run on blur when value is not changed. Which results in unwanted behavior.

**AS-IS**
I have a formGroup with multiple required fields (default angular required validator) and with updateOn: 'blur'. 
On the formGroup i have 1 validator which checks if any one of the fields is touched and invalid, then an error message should be displayed.
When initially entering the page, all fields are invalid, but none of them are touched --> no error message
When i enter a value in the first field and blur --> first field is valid and touch, other invalid and untouched --> no error message
BUT when i enter the next field, and immediately tab to the next without entering a value, the field is touched and invalid --> but still no error message is shown.

**EXPECTED**
In the last use-case above, 
 when i enter the next field, and immediately tab to the next without entering a value --> I expect the field to be invalid and touched and run my custom validator which then result in the error being displayed.

**CAUSE**
it seems that custom validators are only being ran on actual value change, and not on the actual blur functionality.
Even when not changing values, but just blurring, i do want the custom validator to run.

**SOLUTION FOR MYSELF (NOT IDEAL)**
Currently i use the (blur) event on each field to update the value and validity of that field only when an empty field is blurred.
I attached a link to a stackblitz where you can play around with the code.
In here you can see by the console log, that the custom validator is not being ran when click in and out a field.
I commented out the fix, you can just uncomment these lines in the .ts and .html file, and then you have my current solution.

In my opinion this should not be the expected behavior of running these validators on blur.
Open for discussion ofcourse

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-iznhmk?file=src/app/app.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/animations": "^12.1.0",
    "@angular/common": "^12.1.0",
    "@angular/compiler": "^12.1.0",
    "@angular/core": "^12.1.0",
    "@angular/forms": "^12.1.0",
    "@angular/platform-browser": "^12.1.0",
    "@angular/platform-browser-dynamic": "^12.1.0",
```

**Comment by JeanMeche** [comment]
I wouldn't use a validator for that. 
Semantically, the form is invalid with or without being touched. 

What ui libraries do (like Angular Material), they display the errors depending on several conditions (invalid + submitted or invalid + touched) etc. 

That being said, it makes sense to keep the actual behavior.
