### ISSUE TITLE
Animations not working on iOS 12 / 13: animate is undefined

### ISSUE THREAD

**Issue by javiermarinros** [angular/angular#45016]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

Yes

### Description

I have found a regression in Angular animations v13.2.2 for users using iOS v13 and older versions. Please find the stack trace attached.

### Please provide the exception or error you saw

```true
Error: D.animate is not a function. (In 'D.animate(P,Y)', 'D.animate' is undefined)
			_triggerWebAnimation@...:1:1039926
			_buildPlayer@...:1:1039652
			play@...:1:1040066
			play@...:1:1034903
			...:1:1031449
			forEach@[native code]
			_flushAnimations@...:1:1031324
			flush@...:1:1026173
			flush@...:1:1037791
			...:1:1045273
			run@...:1:11157
			end@...:1:1045224
			$_@...:1:810666
			Zl@...:1:817366
			$d@...:1:817386
			detectChanges@...:1:855490
			tick@...:1:885371
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.2
Node: 16.13.0
Package Manager: npm 8.1.0
OS: win32 x64

Angular: 13.2.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.2
@angular-devkit/build-angular   13.2.2
@angular-devkit/core            13.2.2
@angular-devkit/schematics      13.2.2
@angular/cli                    13.2.2
@angular/fire                   7.2.0
@schematics/angular             13.2.2
rxjs                            7.5.2
typescript                      4.5.5
```

**Comment by alan-agius4** [comment]
Angular only supports the [latest 2 major versions of Safari](https://angular.io/guide/browser-support) which at the time of this post are v14 and v15.

The element animate API is available from Safari 13.1 onwards. You should be able to polyfill this API using [web-animations-js](https://www.npmjs.com/package/web-animations-js) however this is not a supported use-case.

**Comment by pongells** [comment]
I am having the same issue, but when running jest.

**Comment by parse** [comment]
@pongells Experiencing the same issue after bumping to minor patch.

**Comment by javiermarinros** [comment]
To fix this issue, I'm using this snippet at `polyfills.ts`:

```
// TypeError: D.animate is not a function
if (!('animate' in document.documentElement) || (navigator && /iPhone OS (8|9|10|11|12|13)_/.test(navigator.userAgent))) {
  const script = document.createElement('script');
  script.src = 'https://cdn.jsdelivr.net/npm/web-animations-js@2.3.2';
  document.head.appendChild(script);
}

```

**Comment by svzi** [comment]
We also encountered the error in our project. We also use Jest and not Jasmine. The error occurs since version 13.2.1. 

Below is a code snippet that causes the error in our case:

``ts
@Component({
  ...,
  animations: [
    trigger('fade', [
      transition(':enter', [
        style({ opacity: '0' }),
        animate('200ms ease-in-out', style({ opacity: '1' })),
      ]),
      transition(':leave', [
        style({ opacity: '1' }),
        animate('200ms 200ms ease-in-out', style({ opacity: '0' })),
      ]),
    ]),
  ],
})
```

I hope this can help to identify the root of the error!

**Comment by sburnicki** [comment]
I observed that only a couple of our users are still using Safari < 14, which are the users with an iPhone 6 as they are stuck with iOS 12.
So I first decided to not increase the bundle size, but only load web-animations polyfill for those users:
```
npm i -D web-animation-js
```

angular.json:
```
{
...
"projects:" {
  ...
  "architect": {
    ....
    "build": {
      ...
      "scripts": [
              {
                "input": "node_modules/web-animations-js/web-animations.min.js",
                "inject": false,
                "bundleName": "web-animations-js"
              }
            ],
```

ployfills.ts:
```ts
if (!('animate' in document.documentElement) || (navigator && /iPhone OS (8|9|10|11|12|13)_/.test(navigator.userAgent))) {
  const script = document.createElement('script');
  script.src = 'web-animations-js.js';
  document.head.appendChild(script);
}
```


This worked fine. But after all I chose another approach by reverting the steps above and disable animations for those people with iPhone6/old Safari, because they have a hard time anyway and lagging animations don't add to a good user experience:

app.module.ts
```ts
const disableAnimations =
  !('animate' in document.documentElement)
  || (navigator && /iPhone OS (8|9|10|11|12|13)_/.test(navigator.userAgent));


@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    disableAnimations ? NoopAnimationsModule : BrowserAnimationsModule,
...
```

**Comment by pongells** [comment]
I just realized we were importing `BrowserAnimationsModule` instead of `NoopAnimationsModule` in our unit tests.

Switching the import to  `NoopAnimationsModule` fixes the issue.

**Comment by davija** [comment]
> I observed that only a couple of our users are still using Safari < 14, which are the users with an iPhone 6 as they are stuck with iOS 12. So I first decided to not increase the bundle size, but only load web-animations polyfill for those users:
> 
> ```
> npm i -D web-animation-js
> ```
> 
> angular.json:
> 
> ```
> {
> ...
> "projects:" {
>   ...
>   "architect": {
>     ....
>     "build": {
>       ...
>       "scripts": [
>               {
>                 "input": "node_modules/web-animations-js/web-animations.min.js",
>                 "inject": false,
>                 "bundleName": "web-animations-js"
>               }
>             ],
> ```
> 
> ployfills.ts:
> 
> ```ts
> if (!('animate' in document.documentElement) || (navigator && /iPhone OS (8|9|10|11|12|13)_/.test(navigator.userAgent))) {
>   const script = document.createElement('script');
>   script.src = 'web-animations-js.js';
>   document.head.appendChild(script);
> }
> ```
> 
> This worked fine. But after all I chose another approach by reverting the steps above and disable animations for those people with iPhone6/old Safari, because they have a hard time anyway and lagging animations don't add to a good user experience:
> 
> app.module.ts
> 
> ```ts
> const disableAnimations =
>   !('animate' in document.documentElement)
>   || (navigator && /iPhone OS (8|9|10|11|12|13)_/.test(navigator.userAgent));
> 
> 
> @NgModule({
>   declarations: [AppComponent],
>   imports: [
>     BrowserModule,
>     BrowserAnimationsModule.withConfig({ disableAnimations }),
> ...
> ```

Awesome, this restored sanity after a couple of hours of searching.  The route of disabling animations worked like a charm.  I tried using `NoopAnimationsModule` in tests as @pongells mentioned, but that did not resolve my issue at all.

Thanks!!!!!!

**Comment by MrKrabat** [comment]
> I observed that only a couple of our users are still using Safari < 14, which are the users with an iPhone 6 as they are stuck with iOS 12. So I first decided to not increase the bundle size, but only load web-animations polyfill for those users:

On my website, this crash also occurs for iPad users. Affected User-Agents:
```
Mozilla/5.0 (iPad; CPU OS 12_5_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1
Mozilla/5.0 (iPad; CPU OS 12_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/91.0.4472.80 Mobile/15E148 Safari/604.1
```

Crash:
```
TypeError: d.animate is not a function. (In 'd.animate(l,_)', 'd.animate' is undefined)
```

**Comment by javiermarinros** [comment]
@MrKrabat try to add this to `polyfills.ts`

```
// TypeError: D.animate is not a function
// https://github.com/angular/angular/issues/45016
if (!('animate' in document.documentElement) || (navigator && /(iPhone OS|iPad; CPU OS) (8|9|10|11|12|13)_/.test(navigator.userAgent))) {
  const script = document.createElement('script');
  script.src = 'https://cdn.jsdelivr.net/npm/web-animations-js@2.3.2';
  document.head.appendChild(script);
}
```

**Comment by KirstenStake** [comment]
Also experiencing this issue suddenly after a minor Angular version update for our Ionic 6 app making it completely unusable for any iOS version lower than 14. Considering Ionic 6 is supposed to support Angular 13+ this is quite strange and a big inconvenience, as now only iOS14+ seems to be fully compatible with the latest Angular updates.

Tested @sburnicki app.module implementation, however this doesn't work with Ioinic as the app hangs on the splashscreen and cannot dismiss it. Then tried his second approach with the web-animation-js and this solves the issue for us and makes the app usable for iOS13 users. 

Does anyone know if this will be fixed or handled with a future Angular update? Or is this web-animation-js code piece something we need to keep "forever" at this point?

**Comment by javiermarinros** [comment]
> Also experiencing this issue suddenly after a minor Angular version update for our Ionic 6 app making it completely unusable for any iOS version lower than 14. Considering Ionic 6 is supposed to support Angular 13+ this is quite strange and a big inconvenience, as now only iOS14+ seems to be fully compatible with the latest Angular updates.
> 
> Tested @sburnicki app.module implementation, however this doesn't work with Ioinic as the app hangs on the splashscreen and cannot dismiss it. Then tried his second approach with the web-animation-js and this solves the issue for us and makes the app usable for iOS13 users.
> 
> Does anyone know if this will be fixed or handled with a future Angular update? Or is this web-animation-js code piece something we need to keep "forever" at this point?

We are need to keep the web-animation-js polyfill at least for some months / years until iOS < 13 devices are gone. As @alan-agius4 pointed out, Angular only supports the [latest 2 major versions of Safari](https://angular.io/guide/browser-support).
