### ISSUE TITLE
[minLength] does not impact form.invalid

### ISSUE THREAD

**Issue by rudyhadoux** [angular/angular#45029]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

Hi,
If I use minLength=3 in an input, it impacts form.invalid.
But if I use [minLength]=min with min=3 in the component, it does not impact form.invalid.
Why ?
Is it a bug ?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.1
Node: 16.13.2
Package Manager: npm 8.4.0
OS: darwin x64
```

**Comment by jnizet** [comment]
Hi @rudyhadoux 

Because the directive selector is `minlength`, not `minLength`. See https://angular.io/api/forms/MinLengthValidator, and https://stackblitz.com/edit/angular-ivy-a4irtj?file=src%2Fapp%2Fapp.component.html for a demo.

**Comment by rudyhadoux** [comment]
Thanks a lot.
Exactly what I want.
