### ISSUE TITLE
Jest Testing failing due to missing decorator (@Inject) in constructor of service files. 

### ISSUE THREAD

**Issue by jeschris45** [angular/angular#45021]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Jest testing is failing due to dependency injection in service files after migrating from angular 12 to angular 13. Adding another service as dependency injection or including HttpClient as part of the constructor to the service errors out. 

The below is in a sample service file

`import { Inject, Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { BehaviorSubject, Subscription, Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class FooService {

  constructor(
    private httpClient: HttpClient
  ) { }

}`

The below is in the spec file

`import { HttpClientModule } from '@angular/common/http';
import { HttpTestingController, HttpClientTestingModule, TestRequest } from '@angular/common/http/testing';
import { TestBed } from '@angular/core/testing';
import { Subject } from 'rxjs';
import { FooService } from './foo.service';

describe('FooService', () => {
  let httpTestingController: HttpTestingController;
  let fooService: FooService;
  const ngUnsubscribe: Subject<any> = new Subject();

  beforeEach(() => {
    TestBed.configureTestingModule({
    imports: [HttpClientTestingModule, HttpClientModule],
    providers: [FooService],
    teardown: { destroyAfterEach: false }
});
    // Returns a service with the MockBackend
    fooService = TestBed.inject(FooService);
    // Inject the http service and test controller for each test
    httpTestingController = TestBed.inject(HttpTestingController);
  });

  test('dummyTest', () => {
    expect(true).toEqual(true);
  })
});`

The line that errors out is at,  fooService = TestBed.inject(FooService);

### Please provide a link to a minimal reproduction of the bug

https://github.com/jeschris45/JestTesing

### Please provide the exception or error you saw

```true
The following is the error message that is outputted to the console: "This constructor is not compatible with Angular Dependency Injection because its dependency at index 0 of the parameter list is invalid.
    This can happen if the dependency type is a primitive like a string or if an ancestor of this class is missing an Angular decorator.

    Please check that 1) the type for the parameter at index 0 is correct and 2) the correct Angular decorators are defined for this class and its ancestors."
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.2
Node: 14.18.3
Package Manager: npm 6.14.15
OS: darwin x64

Angular: 13.2.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.2
@angular-devkit/build-angular   13.2.2
@angular-devkit/core            13.2.2
@angular-devkit/schematics      13.2.2
@angular/cli                    13.2.2
@schematics/angular             13.2.2
rxjs                            7.5.2
typescript                      4.5.5
```

### Anything else?

When adding @inject to the constructor of the service file resolves the error, but not sure why it is needed.

**Comment by JoostK** [comment]
The problem here is that the necessary decorator metadata is not available to Angular. Although `emitDecoratorMetadata` is enabled, the `reflect-metadata` package is not included which means that this metadata is not visible to Angular's JIT compiler.

Angular typically uses a custom transform to handle decorator metadata slightly differently than what vanilla TypeScript produces, as TypeScript's output has a bug w.r.t TDZ issues in ES2015 and later. `jest-preset-angular` also applies this transform, however you're overriding `transform` in `jest.config.js` with other transformers than those provided by `jest-preset-angular`, hence this transformation is not actually applied.

I can't suggest what is the exact correct setup in your case, but Angular is working as expected here so I'll go ahead and close this. Feel free to continue the discussion below.
