### ISSUE TITLE
VersionReadyEvent UpdateInfo Property

### ISSUE THREAD

**Issue by Jun711** [angular/angular#45044]
### Which @angular/* package(s) are relevant/releated to the feature request?

service-worker

### Description

Regarding [VersionReadyEvent](https://angular.io/api/service-worker/VersionReadyEvent#latestVersion)'s currentVersion and latestVersion objects, is it possible to have them contain a new property `updateInfo: string` so that we can use this updateInfo to customize or set the update notification text?  

interface [VersionReadyEvent](https://angular.io/api/service-worker/VersionReadyEvent) {
  [type: 'VERSION_READY'](https://angular.io/api/service-worker/VersionReadyEvent#type)
  [currentVersion: {...}](https://angular.io/api/service-worker/VersionReadyEvent#currentVersion)
  [latestVersion: {...}](https://angular.io/api/service-worker/VersionReadyEvent#latestVersion)
}

https://angular.io/api/service-worker/SwUpdate
```
import {filter, map} from 'rxjs/operators';
// ...
const updatesAvailable = swUpdate.versionUpdates.pipe(
  filter((evt): evt is [VersionReadyEvent](https://angular.io/api/service-worker/VersionReadyEvent) => evt.type === 'VERSION_READY'),
  map(evt => ({
    type: 'UPDATE_AVAILABLE',
    current: evt.currentVersion,
    available: evt.latestVersion,
  })));
  ```

### Proposed solution

Regarding [VersionReadyEvent](https://angular.io/api/service-worker/VersionReadyEvent#latestVersion)'s currentVersion and latestVersion objects, is it possible to have them contain a new property `updateInfo: string` so that we can use this updateInfo to customize or set the update notification text?  

### Alternatives considered

Create an extra endpoint to set the update text

**Comment by Jun711** [comment]
I think `appData` is what I am looking for and I can set it in the `src/manifest.json` file. Is that right?
```
currentVersion: {
    hash: string;
    appData?: object;
}
```

**Comment by gkalpak** [comment]
Yes, `appData` can be used for that purpose. You set it in `ngsw-config.json` (see [SW configuration][1]).
I am going to close this issue, since what you are asking is already possible, but feel free to continue the discussion below.

[1]: https://angular.io/guide/service-worker-config#appdata
