### ISSUE TITLE
stack trace in transformer when importing angular.dart as ng.

### ISSUE THREAD

**Issue by skybrian** [angular/angular#4505]
In one of my dart files, I tried changing this statement:

    import 'package:angular2/angular2.dart';

To this:

    import 'package:angular2/angular2.dart' as ng;

After fixing up all the references, I get a build error:

Build error:
Transform TemplateCompiler on miniml|lib/src/playground/app.ng_deps.dart threw error: Invalid argument(s)
dart:core-patch/regexp_patch.dart 151                                          _JSSyntaxRegExp.allMatches
package:angular2/src/core/facade/lang.dart 167                                 RegExpWrapper.matcher
package:angular2/src/core/render/dom/compiler/selector.dart 47                 CssSelector.parse
package:angular2/src/core/render/dom/compiler/directive_parser.dart 32         DirectiveParser.DirectiveParser
package:angular2/src/transform/template_compiler/compile_step_factory.dart 21  CompileStepFactory.createSteps
package:angular2/src/transform/template_compiler/generator.dart 125            _TemplateExtractor.extractTemplates.<async>
dart:async/zone.dart 911                                                       _rootRunUnary
dart:async/zone.dart 811                                                       _CustomZone.runUnary
dart:async/future_impl.dart 494                                                _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 577                                                _Future._propagateToListeners
dart:async/future_impl.dart 368                                                _Future._completeWithValue
dart:async/future.dart 299                                                     Future.wait.<fn>
dart:async/zone.dart 911                                                       _rootRunUnary
dart:async/zone.dart 811                                                       _CustomZone.runUnary
dart:async/future_impl.dart 494                                                _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 577                                                _Future._propagateToListeners
dart:async/future_impl.dart 368                                                _Future._completeWithValue
dart:async/future_impl.dart 422                                                _Future._asyncComplete.<fn>
dart:async/zone.dart 904                                                       _rootRun
dart:async/zone.dart 803                                                       _CustomZone.run
dart:async/zone.dart 736                                                       _CustomZone.bindCallback.<fn>
dart:async/schedule_microtask.dart 43                                          _microtaskLoop
dart:async/schedule_microtask.dart 52                                          _microtaskLoopEntry
dart:isolate-patch/isolate_patch.dart 96                                       _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149                                      _RawReceivePortImpl._handleMessage

dart:core                                                                      _JSSyntaxRegExp.allMatches
package:angular2/src/core/facade/lang.dart 167                                 RegExpWrapper.matcher
package:angular2/src/core/render/dom/compiler/selector.dart 47                 CssSelector.parse
package:angular2/src/core/render/dom/compiler/directive_parser.dart 32         DirectiveParser.DirectiveParser
package:angular2/src/transform/template_compiler/compile_step_factory.dart 21  CompileStepFactory.createSteps
package:angular2/src/transform/template_compiler/generator.dart 125            _TemplateExtractor.extractTemplates.<async>

**Comment by skybrian** [comment]
In this file, I'm not using a template at all. (It is a @Directive which I changed to @ng.Directive.)

**Comment by kegluneq** [comment]
This appears to be a compiler issue, note the stack trace:

> package:angular2/src/core/render/dom/compiler/selector.dart 47 CssSelector.parse
> package:angular2/src/core/render/dom/compiler/directive_parser.dart 32 DirectiveParser.DirectiveParser

Although this is related to an old version of the compiler - I'll take a look if this still repros.

**Comment by kegluneq** [comment]
This appears to have been fixed in one of the recent compiler updates.

Process:
In the angular2 github project:
1. `gulp build/packages.dart`
2. `cd dist/dart/playground`
3. `$EDITOR web/src/hello_world/index.dart`
4. Update imports to use prefix "ng"
5. `pub get && pub serve`

This worked for me without issues.
