### ISSUE TITLE
SVG elements are rendering incorrectly (alpha.38)

### ISSUE THREAD

**Issue by r-park** [angular/angular#4506]
SVG elements inside templates are not visible with alpha.38. From what I can see, the browser is not recognizing the svg element.

Works in alpha.37: http://plnkr.co/edit/GOEp4DSa0Q3HGZGxXVAi
Breaks in alpha.38: http://plnkr.co/edit/thIhnOB9zhzIQeEnmZUA

```
import {bootstrap, bind, Component, View} from 'angular2/angular2';

@Component({
  selector: 'app-cmp'
})
@View({
  template: `
    <div>
      <svg fill="000000" width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path d="M9 16.2L4.8 12l-1.4 1.4L9 19 21 7l-1.4-1.4L9 16.2z"></path>
      </svg>
    </div>
  `
})
class App {
  constructor() {}
}

bootstrap(App);
```

**Comment by vicb** [comment]
must be linked to the new compiler
/cc @tbosch

**Comment by rolandjitsu** [comment]
:+1: I have the same issue.

**Comment by xbtequila** [comment]
Same here.

Using this for current Workaround:

```javascript
import {BrowserDomAdapter} from 'angular2/src/core/dom/browser_adapter';

BrowserDomAdapter.prototype.createElement = function(tagName, doc) {
    if (doc === void 0) {
		doc = document;
    }

	if(/^(svg|g|use|path|rect|path|text)$/i.test(tagName)) {
  		return doc.createElementNS('http://www.w3.org/2000/svg', tagName);
	} else {
  		return doc.createElement(tagName);
	}
};
```

**Comment by tbosch** [comment]
Yes, this is a know issue. Working on this right now.

**Comment by markharding** [comment]
@tbosch - @xbtequila fix works well but should be extended to include polygon, polyline etc

**Comment by sasha7** [comment]
@xbtequila I tried your workaround but it doesn't work for SVG that looks like this:

```
<svg role="img" class="icon icon--large" xmlns="http://www.w3.org/2000/svg">
          <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/static/persiceApp/src/public/icons/icons.svg#icon-crowd"></use>
        </svg>
```

Do you happen to know why it is not working?

**Comment by xbtequila** [comment]
@sasha7 The "xlink" Attribute is not working in my quick workaround, because it has to be created in the correct namespace. A fork with node and attribute namespaces can be found here: https://github.com/xbtequila/angular

**Comment by cajoy** [comment]
Is there any updates on the issue? As it looks like new compiler breaks not just svg but some other CSS calculations..

**Comment by tbosch** [comment]
Quick update: A similar hotfix has just landed on master, the real fix is still open though...

**Comment by larrifax** [comment]
@tbosch binding to the `xlink:href` attribute still does not seem to work. Example:
```
<svg>
   <use [attr.xlink:href]="iconUrl"></use>
</svg>
```

**Comment by Tragetaschen** [comment]
Let's handle it here then:

A component in 2.0.0-alpha.45 with
```
template: `<svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"></svg>`
```
arrives in the DOM as
```
<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 100 100" version="1.1"></svg>
```

Note the lower-case `b` of `viewbox`. That way, the SVG doesn't render correctly.

As a workaround, I'm using an `ElementRef` in the constructor to manually set the correct property.

**Comment by wfalkwallace** [comment]
@Tragetaschen wow, that's annoying. I didn't see that for the longest time and was wracking my brain figuring out what was going wrong. Thanks!

**Comment by Tragetaschen** [comment]
And because it's so annoying (and cost me again some hair :) )

`stdDeviation` in a `feGaussianBlur` also loses its capitalization.

**Comment by Tragetaschen** [comment]
With alpha.46, all SVG attributes are now rendered correctly. Yay!

However, SVG element names still are converted to lower-case. I'm seeing this with `feOffset`, `feGaussianBlur`, `feComposite`, or `feFlood`. SVG elements referencing such a `<filter>` are not rendered (Firefox) or don't show the filter (Edge).

**Comment by wfalkwallace** [comment]
I'm also seeing an error with some bound properties (eg. height) on SVGs: `Cannot set property height of #<SVGSVGElement> which has only a getter`

**Comment by bradlygreen** [comment]
Reported working, YAY!
