### ISSUE TITLE
Documentation: Typo in Docs of Component Testing

### ISSUE THREAD

**Issue by mubashir-irfan** [angular/angular#45075]
### Description

In the following part of Docs of Component Testing, 'an' needs to be replaced with 'a' for the adjective 'straightforward':

"But in many cases, testing the component class alone, without DOM involvement, can validate much of the component's behavior in an straightforward, more obvious way."

### What is the affected URL?

https://angular.io/guide/testing-components-basics

### Please provide the steps to reproduce the issue

N/A

### Please provide the expected behavior vs the actual behavior you encountered

N/A

### Please provide a screenshot if possible

![Screenshot 2022-02-14 at 5 49 06 PM](https://user-images.githubusercontent.com/68643034/153867628-0380ff0e-ffa2-4912-b816-e50db367cbf6.png)

### Please provide the exception or error you saw

```true
N/A
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
N/A
```

**Comment by AlirezaEbrahimkhani** [comment]
@pkozlowski-opensource 
I solved this problem, please review this [PR](https://github.com/angular/angular/pull/45092)
