### ISSUE TITLE
Cannot compile browser_tree with type checking on.

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#4507]
@vsavkin accidentally turned off our type checking for the non-cjs tree.
I'm turning it back on, but it fails because of
`upgrade/typings/jquery/jquery.d.ts (3186, 13): Subsequent variable declarations must have the same type.  Variable '$' must be of type 'cssSelectorHelper', but here has type 'JQueryStatic'.`
The reason is well-known and documented at https://github.com/borisyankov/DefinitelyTyped/issues/2734 : Both JQuery and Selenium define a runtime variable in the global scope named `$` so the typings files `jquery.d.ts` and `angular-protractor.d.ts` both define the symbol for the benefit of the type-checker, but with different types.

The right solution is to compile the `modules/upgrade` separately from the testing code that depends on protractor. This is a non-trivial change to the build.

**Comment by todoubaba** [comment]
Similar problem when the VS Code project contains both anguar2 and jquery, the IDE always uses 'node_modules/angular2/ts/typings/augular-protractor.d.ts' first and complains about the $ sign.
