### ISSUE TITLE
Broken link to angular.json complete schema

### ISSUE THREAD

**Issue by Dok11** [angular/angular#45072]
### Description

Here the text https://angular.io/cli#workspace-and-project-configuration the link "complete schema" contains broken URL "https://github.com/angular/angular-cli/wiki/angular-workspace" which redirects to "https://github.com/angular/angular-cli"

**Comment by yousafnawaz** [comment]
@Dok11, I think "complete schema" link should point to [https://angular.io/guide/workspace-config#angular-workspace-configuration](https://angular.io/guide/workspace-config#angular-workspace-configuration)

**Comment by yousafnawaz** [comment]
@pkozlowski-opensource  I submit a PR for this?

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular/pull/45095
