### ISSUE TITLE
Remove constraint that abstract classes requires an angular decorator

### ISSUE THREAD

**Issue by MBAatEJOT** [angular/angular#45086]
### Which @angular/* package(s) are relevant/releated to the feature request?

compiler

### Description

When compiling a library, which since angular 13 forces you to use the Ivy-Compiler it creates errors like

> Class is using Angular features but is not decorated. Please add an explicit Angular decorator

even on abstract classes.

This is totally illogical because by definition a abstract class can not be instantiated. Therefore a decorate would not make sense.

### Proposed solution

Remove this compilation error for abstract classes. 

### Alternatives considered

If you insist on an decorator for some reasons, because the Ivy compiler is not able to differ between "normal" and abstract classes implement an `@Abstract()` decorator.

**Comment by JoostK** [comment]
> If you insist on an decorator for some reasons, because the Ivy compiler is not able to differ between "normal" and abstract classes implement an @Abstract() decorator.

This already exists, it's `@Directive()`.

Angular requires decorators on classes with Angular features because it needs to capture the necessary metadata for the runtime to work.

**Comment by MBAatEJOT** [comment]
> > If you insist on an decorator for some reasons, because the Ivy compiler is not able to differ between "normal" and abstract classes implement an @abstract() decorator.
> 
> This already exists, it's `@Directive()`.
> 
> Angular requires decorators on classes with Angular features because it needs to capture the necessary metadata for the runtime to work.

Yeah but thats only the alternative. That's no good solution. Also the real class is the derived class not the abstract class. The abstract class only provides features for the derived on. So Angular should only need to capture the necessary metadata on the derived classes.

Please re-open
