### ISSUE TITLE
add markAsTouched to ControlValueAccessor interface

### ISSUE THREAD

**Issue by bolemeus** [angular/angular#45089]
### Which @angular/* package(s) are relevant/releated to the feature request?

forms

### Description

When using the ControlValueAccessor in a component you can update the value on the parent form with the onChange callback and you write a value from the parent in the component using the writeValue implementation.
Similarly you can update the touched status on the parent with the onTouched callback, but there is no way for the parent to signal to the component that it should update it's internal touched status...

Consider using ControlValueAccessor in a component to wrap a date field using dropdowns for each individual date part.
So a dropdown for day, month and year. Currently it is nog possible to mark these dropdowns as touched, when the `markAllAsTouched` method on the parent form is called. In order to do this you have to update the component yourself some other way

### Proposed solution

add an optional `markAsTouched()` or `writeTouched(value: boolean)` method to the ControlValueAccessor interface, that gets called whenever the parent form tries to update the touched status of the formControl.

### Alternatives considered

I've included the parent FormControl in the component with `FormGroupDirective`. Like this...

```typescript
constructor(private rootFormGroup: FormGroupDirective) {
}

ngOnInit() {
  ...
  this.rootControl = this.rootFormGroup.get(this.formControlName);
}
```

and then just use the touched property of the rootControl in addition to the touched property of the individual child controls

Another alternative is to just declare another `Input() touched = false` in the component, and update that value manually whenever you call the `markAllAsTouched` on the parent form.

**Comment by spock123** [comment]
@bolemeus I use the last alternative.

Gets annoying quick when using lots of components. Your proposed feature would be super helpful.

**Comment by dylhunn** [comment]
Related to #10887. We should support all events in both the controls API and CVA API with a unified API.

**Comment by dylhunn** [comment]
Disregard angular-robot, the linked issue already has plenty of votes.

**Comment by bolemeus** [comment]
angular-robot is quite stubborn. :p

**Comment by kekel87** [comment]
Hi, we are also very interested in this feature.

Because we want to display invalid fields when users press the submit button on large CVA forms.

For the moment we are using this not [very clean directive](https://stackblitz.com/edit/angular-ivy-zr9src?file=src/app/fix-cva.directive.ts), but it does the job.

**Comment by MasDevProject** [comment]
Any news for this useful proposal?

**Comment by vberJandJ42** [comment]
proposal..., posal..., posal..., sal...

**Comment by JeanMeche** [comment]
This is now possible with the new `event` observable in v18. 

Here is an example of a CVA that handles that:

```
@Component({
  selector: 'child-cva',
  template: `
    @if(touched) {
      TOUCHED !!
    } @else {
      UNTOUCHED !!
    }
  `,
  standalone: true,
  providers: [
    { provide: NG_VALUE_ACCESSOR, multi: true, useExisting: CvaWChild },
  ],
})
class CvaWChild implements ControlValueAccessor {
  injector = inject(Injector);
  touched = false;

  onChange!: Function;

  writeValue(value: any) {}

  registerOnChange(fn: (value: any) => void) {}
  registerOnTouched(fn: any) {}

  ngAfterViewInit() {
    console.log(this.injector.get(NgControl).control!.events.subscribe((event) => {
      if(event instanceof TouchedEvent) {
        this.touched = event.touched
      }
    }))
  }
}
```

Stackblitz demo : https://stackblitz.com/edit/v18-cva-touched

**Comment by JeanMeche** [comment]
Since we don't intend to add new methods to CVA and have this alternative, we consider it as fixed.
