### ISSUE TITLE
Information Regarding the GSoC Event  in April 2022

### ISSUE THREAD

**Issue by iamhardikat11** [angular/angular#45081]
### Description

I wanted to ask about the GSoC Program 2022 to Apply for this Sumer. I would like to contribute? What should be my approach?

**Comment by mgechev** [comment]
Hi @iamhardikat11, Angular is not part of Google Summer of Code. To find the participating projects and the timeline visit [summerofcode.withgoogle.com](https://summerofcode.withgoogle.com/).
