### ISSUE TITLE
Remove "no suitable injecttion token" error for abstract classes

### ISSUE THREAD

**Issue by MBAatEJOT** [angular/angular#45087]
### Description

When compiling a library, which since angular 13 forces you to use the Ivy-Compiler it creates errors like

> No suitable injection token for parameter 'someParameter' of class 'SomeBaseComponent'.

even on abstract classes.

This is totally illogical because by definition a abstract class can not be instantiated. The constructor is only called by a derived class. The constructor of this derived class may uses a different type as injection token than the base class requires

For Example:

```typescript
export abstract class BaseComponent implements OnInit, OnDestroy {

	constructor(protected showThisAndThat: boolean) {
	}

	// ... 
```

```typescript
export class MyDerievedClass extends BaseComponent {

	constructor(@Inject(COMPONENT_SETTINGS) private _componentSettings: IComponentSettings) {
		super(this._componentSettings.showThisAndThat);
	}
}
```

### Proposed solution

Remove this error for abstract classes. Injecttion tokens are defined in the real component. Not in the abstract class.

### Alternatives considered

There is none

**Comment by JoostK** [comment]
This is something we want to address and is being tracked in #37914.
