### ISSUE TITLE
Disabled buttons will run ng-click when triggered with jQuery ```.click``` or ```.trigger('click')``` in 1.2.28

### ISSUE THREAD

**Issue by melcher** [angular/angular#451]
Disabled button elements are not supposed to respond to or propagate click events.
However, in angular 1.2.28 (and as far back as 1.2.16) disabled button elements with ng-click directives do respond to javascript click events, though they do not respond to actual mouse clicks.

The method of disabling doesn't matter, either a disabled attribute or ng-disabled work.
When triggered with a javascript click event (e.g. ```$(button).click()``` or ```$(button).trigger('click')```) I expect the ng-click expression of the button not to execute, but instead it executes.

This is a problem for E2E and other testing, as one would *not* expect a 'click' event on a disabled button to run it's ng-click.

Fiddle is here:
http://jsfiddle.net/e78xjvLu/4/

This does not seem to be an issue in 1.2.1
http://jsfiddle.net/e78xjvLu/5/

**Comment by vicb** [comment]
Please reopen this issue on https://github.com/angular/angular.js 
This repo is for angular2
