### ISSUE TITLE
ResizeObserver callback is not running in zone

### ISSUE THREAD

**Issue by bene-starzengruber** [angular/angular#45105]
### Which @angular/* package(s) are the source of the bug?
core, zone

### Is this a regression?
I dont think so, same behaviour as in Angular 12

### Description

The callback of a `ResizeObserver` is not running in the ngZone and does therefore **not** trigger change detection, even if `.markForCheck()` is called manually

### Please provide a link to a minimal reproduction of the bug

angular 13: https://stackblitz.com/edit/angular-ivy-cuegz9?file=src/app/app.component.ts
(have a look at the comments in `ngOnInit` and resize the preview tile on the right to see the effect)

angular 12: https://stackblitz.com/edit/base-angular-12-app-uh71an?file=src/app/app.component.ts

### Anything else?

there are issues regarding the `ResizeObserver` and `fakeAsync` but I'm not sure if this is related
https://github.com/angular/angular/issues/31695

also there are efforts vom Jia but it seemed that this did not find its way into Angular 
https://github.com/angular/zone.js/issues/1011

**Comment by JoostK** [comment]
This is indeed essentially the same as #31695; `ResizeObserver` is not patched by zone.js and therefore requires manually entering the zone within the resize callback.

**Comment by Timebutt** [comment]
Hi @JoostK, I'm just running into this exact same issue in some code I'm developing and started digging into code. I did indeed find out that the `ResizeObserver` is not patched by default by `zone.js`, but oddly enough there is [an implementation](https://github.com/angular/angular/blob/master/packages/zone.js/lib/browser/webapis-resize-observer.ts) for just that present in the `zone.js` codebase.

If I add an `import 'zone.js/dist/zone-patch-resize-observer';` to my `polyfills.ts`, the `ResizeObserver` callback is correctly patched as I would expect, and needs no explicit `zone.run()` anymore. Furthermore, if I add below code to `zone.js`:

```
Zone.__load_patch('IntersectionObserver', (global: any, Zone: ZoneType, api: _ZonePrivate) => {
  patchClass('IntersectionObserver');
});
```

similar to [the implementation here](https://github.com/angular/angular/blob/c3614662cb0ae5f93eb4d77f97f68fbba3cc360e/packages/zone.js/lib/browser/browser.ts#L78), it also just works.

I'm trying to understand why that code is provisioned if it isn't used by default? Is there a reasoning in which we incur a performance hit by patching `ResizeObserver` using the existing implementation, or is this just an oversight and as such a bug in `zone.js`?

**Comment by JoostK** [comment]
I don't know, TBH. Maybe @JiaLiPassion recalls.
