### ISSUE TITLE
Fixture.whenStable resolves immediately when using rxjs observables.

### ISSUE THREAD

**Issue by Mekacher-Anis** [angular/angular#45109]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

**Setup and Tests**:
In my project I have a complex rxjs Pipeline with multiple rxjs operators.
In the tests I call a function on this component which in turn calls a service that loads mock data and then updates the view based on this mock data.
So after calling this function I call `fixture.whenStable()` to wait for the rxjs pipeline to resolve and for the component to get updated as expected. 
The tests are wrapped in a `waitForAsync`

**Problem:**
The `fixture.whenStable` function resolves immediately and doesn't wait for the rxjs pipe to finish which causes the expects to fail.
I have made a working (broken) example in the link below.
Please check the console in Stackblitz, it shows that the order in which they're executed is wrong.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-13-fixture-whenstable?file=src/app/app.component.spec.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.4
Node: 14.17.0
Package Manager: npm 8.3.0
OS: linux x64

Angular: 13.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cli                    13.0.4
@schematics/angular             13.0.4
rxjs                            7.4.0
typescript                      4.4.4
```

### Additional Note
I don't know if this is that useful, but in this line
https://github.com/angular/angular/blob/db4a658bebfb18fea7ad8f558d72f53ee5cff3d5/packages/core/testing/src/component_fixture.ts#L82
if you change it to `ngZone.onStable.pipe(debounceTime(3000)).subscribe(...)` 
it should work fine, which I think means that the `ngZone.onStable` is fired multiple times with a small delay in between events but the `whenStable` Promise resolves directly on the first one, which also means that when it resolves the zone isn't really stable yet.

**Comment by JiaLiPassion** [comment]
The reason is the `fixture.componentInstance.click()` is not running inside `ngZone`, and this is confusing to the user, I will try to find out how to make this test more make sense.

**Comment by Mekacher-Anis** [comment]
@JiaLiPassion awesome !! but shouldn't `click()` be ran automatically in the ngZone of the fixture ?

**Comment by JiaLiPassion** [comment]
@Mekacher-Anis , no, the `click()` function of the component is just a normal function, it will run in the zone context where it is called, so in the application, it is running in the ngZone since the `click()` is bound to the dom event listener which will auto run into the ngZone, but if you call the `component.click()` in the test just like your example, it will not.
