### ISSUE TITLE
Contribute emitDecoratorMetadata to esbuild and use it

### ISSUE THREAD

**Issue by sod** [angular/angular#45106]
### Description

Once you lived with unit tests executing in 50 milliseconds and the build just taking a second, you dread coming back to webpack & karma. It's like coming back from vacation. 

### Proposed solution

The missing pieces in the puzzle are:

* angular supporting async compilation in jit mode
* component templates being able to resolve async in jit mode
* esbuild supporting `emitDecoratorMetadata` (even if it's just a crude version of that)
  * or alternatively just a dependency injection preprocessor written in go/rust/dart - pick your native language of choice - so it can run swiftly as a preprocessor before esbuild

### Alternatives considered

Feel free to close. Just wanted to get this off my chest. I try to keep my team on swc and jest for fast builds and unit-tests. But I wish angular would move officially into that direction.

**Comment by sod** [comment]
This is kinda a duplicate of https://github.com/angular/angular/issues/38732 - one year later. But as the vite lifestyle grows around me, you just feels the pressure around me growing. When you say "angular" you just hear "ugg, long builds"

**Comment by alan-agius4** [comment]
Looks to me that what is being required here is covered in https://github.com/angular/angular/issues/43131.

**Comment by sod** [comment]
You are right. I forgot about that ticket. Love that you have it on the radar :party
