### ISSUE TITLE
How to add / update lazy loading module routes

### ISSUE THREAD

**Issue by soori-reddy** [angular/angular#45112]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

setup routing module

const routes: Routes = [
  { path: '', component: SetupComponent },
  { path: 'usermanagement',  loadChildren: () => import('./usermanagement/usermanagement.module').then(m => m.UsermanagementModule) },
  { path: 'organization',loadChildren: () => import('./organization/organization.module').then(m => m.OrganizationModule) },
];

user management routes

const routes: Routes = [
  { path: 'users',  loadChildren: () => import('./users/users.module').then(m => m.UsersModule) },
  {  path: 'roles',  loadChildren: () => import('./roles/roles.module').then(m => m.RolesModule) },
];
user routes.
const routes: Routes = [
  {  path: '', component: UsersComponent },
  { path: 'new', component: UserNewComponent },
  {path: 'edit/:id', component: UserEditComponent }
];

at the application start would like to inject route in Users Module  /usermanagement/users/delete 
path : 'delete' , component : DynamicComponent

(<any>this.router).configLoader.load(this.injector, parentRoute).subscribe({
                                next: (moduleConf: any) => {
                                    let routestoUpdate: Routes = moduleConf.routes;

                                      routestoUpdate.push(
                                        {
                                            path: `delete`,
                                            component: DynamicComponent,
                                         },
                                         ..... // may replace old route
                                      );

                                   **// how to update  router , so that I can access new route  /usermanagement/user/delete ?**

                                      moduleConf.routes = routestoUpdate;
                                       await this.compiler.compileModuleAsync(moduleConf.module.injector.instance);
                                       // this.router.config.unshift(...routestoUpdate);
                              

   }
              });

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
