### ISSUE TITLE
Table contents are hidden behind the right-side panel, when Side-Nav is open.

### ISSUE THREAD

**Issue by Abhishek-90** [angular/angular#45121]
### Description

When the side navigation is close, the contents of the Properties table is visible correctly.

But when the side navigation is open, the table shifts to the right and parts of the content of the table gets hidden behind the the right side panel. 

### What is the affected URL?

https://angular.io/api/router/RouterLinkActive

### Please provide the steps to reproduce the issue

Click on the hamburger option on the top left of the page and Notice the Properties table closely

### Please provide the expected behavior vs the actual behavior you encountered

Actual Behavior : The table is being shifted towards right to accommodate the side Nav bar, thus hiding the table contents:

Expected Behavior : The **SIZE** of the table should be changed (Table should not be shifted) depending on whether the Side nav is open or closed. 

### Please provide a screenshot if possible

Screenshot when Navigation bar is open:

<img width="960" alt="Open" src="https://user-images.githubusercontent.com/43419831/154468483-3f1452aa-aefd-4b21-b035-3b6cfeaf9146.png">

Screenshot when Navigation bar is Closed:

<img width="960" alt="Closed" src="https://user-images.githubusercontent.com/43419831/154468526-bb3d5f64-41f1-4fbf-8967-61aa7d8ecaeb.png">

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
I tested it on Firefox and Chrome Browser.
```

**Comment by dario-piotrowicz** [comment]
Hi @Abhishek-90, this is sort of a know issue (you are specifically relating the side-nav, but this is a more generic issue that happens in general depending on the available width), there was already an issue related to this: #44850

The issue then was closed by PR #44851, unfortunately that solution created other issues so it was reverted (#44899)
(I also did try to fix things here #44896) unfortunately as it stands changing this behavior may require quite some refactoring in the site, so I am not completely sure if it's worth it :sweat:

**Comment by Abhishek-90** [comment]
Hi @dario-piotrowicz, I see what you are trying to say. 
I am sure you have tried the best approach. 
However, I feel that it might be solved by fixing the div container the Table and changing the size of the table and the div depending on whether the nav bar is open or closed. 

Please let me know about the flaws in this approach.

**Comment by Abhishek-90** [comment]
@dario-piotrowicz hey thankyou so such good explanation about the issue.. after reading it I agree that it will require lots of refactoring and the structure depends on many factor.

**Comment by bob-watson** [comment]
This doesn't seem to be related to documentation content so I removed `comp: docs` label.

**Comment by JeanMeche** [comment]
That's basicaly the same problem reported here #47535
