### ISSUE TITLE
router.navigateByUrl() promise is not rejected when route guard has restricted the route navigation 

### ISSUE THREAD

**Issue by bhaskerchari** [angular/angular#45120]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

The promise returned by method this.router.navigateByUrl() is not rejected instead it is resolved even when AuthGuard's canActivate method returns false though the route navigation didn't happen which is correct.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-routerlink-state-3owveu

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/cli": "^11.2.13"
"typescript": "4.1.5"
```

**Comment by Brandinga** [comment]
you have to inspect the return value of the promise

```
this.router.navigateByUrl('routed-navigate', { state: this.state }).then(
      (returnValue) => {
        alert('navigation returnValue: ' + returnValue);
      },
      () => {
        alert('navigation rejected.');
      }
    );
```

see:
https://angular.io/api/router/Router#navigateByUrl
Returns:
Promise<boolean>: A Promise that resolves to 'true' when navigation succeeds, to 'false' when navigation fails, or is rejected on error.

**Comment by atscott** [comment]
As @Brandinga mentioned in https://github.com/angular/angular/issues/45120#issuecomment-1042958212, this is working as documented.

**Comment by bhaskerchari** [comment]
Thanks @Brandinga [Brandinga](https://github.com/Brandinga) for pointing out the reference to the documentation. I didn't think of looking at the return value of the promise but was more focused on it would call the error handler. But I guess it would still call errorHandler in certain cases and also we need to depend on the return value of the  promise as well in the success handler.
