### ISSUE TITLE
"Service worker generation failed: Too many open files" with an assets folder with large number of files

### ISSUE THREAD

**Issue by LucaBruni** [angular/angular#45133]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

We recently migrated our large single page application from Angular 9 to Angular 13.
Our production build enables the service worker generation, and the "assetsGroups->resources->files " section  include  "/assets/**"
During our first production build on a Windows 10 machine (16GB ram), we received this message: 

Service worker generation failed.
EMFILE: too many open files,

Our application's assets folder contains all the dictionaries for at least 13 different languages: every folder cointains at least a thousand files: the service worker generation stops right in the middle.
We tried to split the assetsGroups in multiple elements (one for each language folder), but the service worker generation stopped exactly in the same spot.

Next we checked the source code for the assetsGroups generation and the difference between angular 9 and 13. If we are looking in the right source file, from what we saw seems like that the hashing of all assets files is responsible for the error (\node_modules\@angular-devkit\build-angular\src\utils\service-worker.js)

Attached to the issue you'll find a zip with our sample app: (in any case, we merely create a new app with "ng new", added the angular/service-worker package and the assetsGroup section, and used "ng build --configuration=production"

[ang13Test.zip](https://github.com/angular/angular/files/8095737/ang13Test.zip)

### Please provide the exception or error you saw

```true
Service worker generation failed: Too many open files
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.2
Node: 16.14.0
Package Manager: npm 8.4.1
OS: win32 x64

Angular: 13.2.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.2
@angular-devkit/build-angular   13.2.2
@angular-devkit/core            13.2.2
@angular-devkit/schematics      13.2.2
@angular/cli                    13.2.2
@angular/flex-layout            13.0.0-beta.38
@schematics/angular             13.2.2
ng-packagr                      13.2.1
rxjs                            6.5.5
typescript                      4.5.5

Intel I7 4771 3.50Ghz
16GB Ram
```

**Comment by ajafff** [comment]
The issue seems to be this line: https://github.com/angular/angular/blob/235bffc5f9a0faf00b9aeb4ef5f15c696ad4b522/packages/service-worker/config/src/generator.ts#L70

it basically tries to read and hash all files in parallel. instead it should use some kind of queue to limit the parallelism. that ensures only a limited number of files is open at the same time.

**Comment by gkalpak** [comment]
Thx for reporting this, @LucaBruni :+1:
@ajafff is spot on!

Would any of you be interested in creating a pull request? :smiley:

**Comment by LucaBruni** [comment]
In our solution we used a non-configurable "100" elements limit.
If that's ok, and adding a dependency to "p-limit" is not a problem, we'll submit a PR.
Otherwise we can create a suboptimal solution: just let us know.

**Comment by LucaBruni** [comment]
Thanks for the response: 500 is ok: our 100 limit was maybe too much on the safe side :D
Our critical threshold was around 5000, but I have no idea if that limit is ram-dependant or not.
Your batch solution works well for me.

**Comment by gkalpak** [comment]
That's great! So, if you wanted to put that code in a PR and throw in a test or two, I would be happy to review and get it merged :smiley:

**Comment by LucaBruni** [comment]
We are ready to create PR: we did not create additional tests as the existing ones should cover our needs.
Also, we have no idea how to create a test that involves hashing of 10000 files :)
Let us know.

**Comment by gkalpak** [comment]
Regarding the test:
We use a `MockFilesystem` in tests ([example][1]). I was thinking that we could construct a `MockFilesystem` instance with more files than the limit we have set and also overwrite the `hash` method to keep track of how many calls there are simultaneously. Then we could check that our limit was not exceeded.

I.e. something like:

```ts
class HashTrackingMockFilesystem extends MockFilesystem {
  public maxConcurrentHashings = 0;
  private concurrentHashings = 0;

  /** @override */
  async hash(path: string): Promise<string> {
    // Increase the concurrent hashings count.
    this.concurrentHashings += 1;
    this.maxConcurrentHashings = Math.max(this.maxConcurrentHashings, this.concurrentHashings);

    // Artificial delay to check hashing concurrency.
    await new Promise(resolve => setTimeout(resolve, 250));

    // Decrease the concurrent hashings count.
    this.concurrentHashings -= 1;
    
    return super.hash(path);
  }
}
```

Does that make sense?

[1]: https://github.com/angular/angular/blob/ec0a0e0669ef5d2f524fbf9a540eb2b306b2e24a/packages/service-worker/config/test/generator_spec.ts#L17-L25

**Comment by LucaBruni** [comment]
Yes, it does make sense: we used your HashTrackingMockFilesystem and added a single test.
Thanks
