### ISSUE TITLE
Matrix parameter missing from route.paramMap

### ISSUE THREAD

**Issue by egonknapen** [angular/angular#45137]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

I want to use and extract a matrix parameter 'site' from the following url:

https://localhost:44370/clientname;site=sitename/lazypage/someid

I tried the following 3 routings, so I could use an ActivatedRouteSnapshot in my resolver-service to get 'client' and an optional 'site' parameter

1)

{ path: ':client/lazypage', loadChildren: () => import('./+lazymodule/lazymodule.module').then(m => m.LazyModule) },

2)

{ path: ':client', children: [
	{ path: 'lazypage', loadChildren: () => import('./+lazymodule/lazymodule.module').then(m => m.LazyModule) }
]}

3)

{ path: ':client;site=:site/lazypage', loadChildren: () => import('./+lazymodule/lazymodule.module').then(m => m.LazyModule) },

The 2th notation works, but it prevents a lot of routing after that, which can't be combined. So I tried to use the first one, it's kind of an exception to the rest of my routing, the problem now is, that in my resolver 'site' is always unknown:

let client: string = route.paramMap.get('client');
let site: string = route.paramMap.get('site');

The third path notation was just an idea, but the problem/bug I noticed, is that paramMap now has a variable called ':client;site=:site' which contains only the clientname, and the sitename is filtered from it, not the matrix notification, I would suggest that's also wrong, at least it should know that a variable name never should be called '....;....'.

My suggestion should be, that angular knows about the matrix parameter, because it filters it from the 'client' variable, but it forgets to add it to the paramMap.

My workaround at the moment is using the first routing notation, and in the resolver extract the ';site=' part from document.location.href by hand.

### Please provide the exception or error you saw

```true
1) I don't see the 'site' matrix when using ':client/lazypage' in the 1st routing example

2) paramMap contains a :client;site=:site variable in the 3th routing example
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular v13 (latest)
Windows 10
```

**Comment by atscott** [comment]
This is working as documented here: https://angular.io/api/router/ExtraOptions#paramsInheritanceStrategy. Matrix parameters must appear at the end of the last `UrlSegment` in the `Route` in order to be parsed.

**Comment by atscott** [comment]
Matrix params are associated with a `Route`. In your first example, the matrix params do not logically belong to any route. Copying a response for @jasonaden with respect to this in the past

> The path for the route is `entities/query`. If there's matrix parameters inserted after `entities` (e.g. `entities;type=user/query), they don't logically belong to any route. My first reaction would be to say this should throw an error as it can't match a route. However, matrix params are optional so the fact that we seem to just parse them out and ignore them in terms of URL matching makes sense.

> If we were to look at this with path params, it seems like it would make more sense. A config like `entities/query/:type` should never work if you pass a URL such as `entities/user/query`. It would simply error as it can't find a match.

> Also, I can see a world where this could make for very confusing behavior in an application. Let's say an app configured `entities/query` to render `QueryComponent` and supported `entities;type=user/query` such that the `type` param made it to the `QueryComponent`. Later, the same application changes the configuration to support more URLs under `entities`:

```
path: 'entities', component: EntitiesDashboard, children: [
  {path: 'query', component: QueryComponent},
  {path: 'users', component: UsersComponent}
]
```

> Now if the `EntitiesDashboard` looks for a `type` matrix param, it's going to get it from all the bookmarked URLs that went to `entities;type=user/query` prior to the config change (when this might not actually be the intended behavior).

There's also no reproduction in the report here and the statement "The 2th notation works, but it prevents a lot of routing after that, which can't be combined" does not seem true to me. Without a more concrete example, I don't actually know what this means. Maybe there's something here, but as far as the current report of "matrix params should be retained at segments in the middle of the route" goes, this is not the behavior we want in the Router.
