### ISSUE TITLE
tslint replacement

### ISSUE THREAD

**Issue by digeomel** [angular/angular#45153]
### Description

Although tslint is deprecated and the Angular team suggests switching to eslint, our team tried 3-4 times already to switch to the latter and it has always been painful. With the latest release of all packages, Angular 13, eslint 8.9.0, angular-eslint 13.1.0 and typescript-eslint 5.11.0, our project takes around 40 minutes 😱 to lint, which of course makes it impossible to integrate into any CI workflow. The experience is much better on individual files within vscode.

I've read all the articles about improving the performance, and I tried some solutions without any result, but really, this is a tool that's supposed to work out-of-the-box with minimal configuration, we can't spend so much time trying to get it right, especially when tslint just worked.

Furthermore, I noticed that even the Angular and Angular Material teams haven't switched to eslint yet, you're both still on tslint. In fact, I couldn't find any Angular project of considerable size on github that has switched to eslint. Granted, I didn't expect to find any, because I guess Angular is used mostly in corporate environments, intranet applications and so on, so it's difficult to find code hosted on public repos.

### Proposed solution

So, perhaps we should revisit the decision to drop tslint or suggest a better alternative? I don't have a suggestion of course, just pointing out the obvious issues.

I'd really like to hear from people working on big Angular projects, especially with monorepo structures, multiple projects and libraries inside.

### Alternatives considered

eslint with angular-eslint.

**Comment by crisbeto** [comment]
Note on Angular Material: we haven't switched yet, because we have a lot of custom lint rules which need to be rewritten to eslint. We have switched the material.angular.io site to eslint without much of a CI time degradation: https://github.com/angular/material.angular.io

**Comment by digeomel** [comment]
@crisbeto thank you for your answer, I just checked your configuration and you seem to have a lot of rules turned off:

```
"rules": {
        "@angular-eslint/component-class-suffix": "off",
        "@angular-eslint/component-selector": "off",
        "@angular-eslint/directive-class-suffix": "off",
        "@angular-eslint/directive-selector": "off",
        "@typescript-eslint/dot-notation": "off",
        "@typescript-eslint/member-delimiter-style": "off",
        "@typescript-eslint/explicit-member-accessibility": [
          "off",
          {
            "accessibility": "explicit"
          }
        ],
        "@typescript-eslint/no-inferrable-types": "off",
        "@typescript-eslint/member-ordering": "off",
        "@typescript-eslint/no-unused-vars": "error",
        "@typescript-eslint/no-non-null-assertion": "off",
```

Maybe that's why you didn't incur a big CI time degradation?

**Comment by crisbeto** [comment]
It's possible. I was turning off the rules that didn't match our previous setup when I first switched us over to eslint.

**Comment by dario-piotrowicz** [comment]
@digeomel You said you already tried a bunch of stuff, so, sorry if I am just suggesting something you've already tried, a while back a migrated the aio examples from using tslint to eslint, the linting time really went through the roof, but then we've applied some suggestions provided by the creator of `typescript-eslint` and `angular-eslint`:  https://github.com/angular/angular/pull/43218#issuecomment-907072083

That really helped a lot and made the linting still slower than it was before but not painfully so.

Have you already tried these solutions? if not would you mind giving it a go? :slightly_smiling_face:

**Comment by digeomel** [comment]
@dario-piotrowicz I did try some of these suggestions, namely creating a separate `tsconfig.eslint.json` file with the settings provided in the instructions, include only `"**/*.ts"` files, exclude some folders like `node_modules`, and most importantly, set the parameter `"createDefaultProgram": false`. Then I debugged it again using the command `DEBUG=typescript-eslint:* ng lint` and I saw that it was still creating a new program for almost every single file. At that point I gave up. Maybe I should give it another try, but really, I'm at a loss on what to try next.

I also read this very nice article: https://duncanleung.com/why-slow-plugin-typescript-eslint-performance-issues/
and I quote:

> I wasn't able to discover many large optimizations to improve the runtime performance.
> The underlying issue is still the overhead of the TypeScript compiler generating an AST, and the @typescript-eslint/typescript-estree work of converting this AST to an ESLint compatible AST.

**Comment by dario-piotrowicz** [comment]
@digeomel I'm sorry to hear that, I am not really knowledgeable in eslint stuff so if you tried those suggestions I don't really have much else to suggest :sweat: 

The article you provided is indeed very interesting thanks for sharing it :slightly_smiling_face: 

If you have a large repo it could still make sense to divide it up and run the linting separately as for example using NX, but yeah not all projects are suited for something like that, nor it makes much sense to go that route just to have the linting work in a sensible amount of time

(For what is worth anyways 40 minutes are really really surprising to me :open_mouth:)

**Comment by digeomel** [comment]
@dario-piotrowicz @crisbeto after a lot of trials and errors, and following the advice also mentioned above in https://github.com/angular-eslint/angular-eslint#eslint-configs-and-performance, namely to create separate `tsconfig.eslint.json` files for each sub-project and library in our monorepo and adding a ton of folders and files in `.eslintignore`, I finally managed to bring down our total linting time from 50 minutes to 2 minutes!

So I guess you can close this issue, although I am sure a lot of other developers will stumble upon this (I know another team in our organization did) and waste a lot of time like I did. I don't know if this can be automated by the eslint-angular schematics, but I suppose this is not an issue for the Angular team to resolve.

**Comment by dario-piotrowicz** [comment]
Ah wow @digeomel that's awesome! congrats! :smile: :partying_face: 

I will have a look at the docs, I think that Angular tried to be unopinionated regarding linting, if that's actually the case it may be as you mentioned out of Angular's scope to provide information regarding eslint's performance.

But if somewhere in the docs we advise eslint then I think we could definitely add some info regarding performance I think

___

Could it also be helpful opening an issue in `angular-eslint` suggesting to make the performance information easier to find and more prominent?

**Comment by digeomel** [comment]
@dario-piotrowicz I created a new issue here:
https://github.com/angular-eslint/angular-eslint/issues/935
not to update the documentation as you suggested, but to ask why these settings are not the defaults in the builder.

**Comment by dario-piotrowicz** [comment]
By the way, I checked and in the angular docs there doesn't seem to be much regarding eslint (it is just briefly mentioned in a couple of places)

**Comment by digeomel** [comment]
@dario-piotrowicz I know, but IMHO this just points to the fact that we're currently in a state of limbo. We know we need a linting solution, but we're too reluctant to suggest eslint, I assume because of all these issues. Tslint with codelyzer just worked out of the box.

**Comment by dario-piotrowicz** [comment]
Yes I understand what you mean, unfortunately I think Angular policy on linting and e2es is just to leave the choice to the developer, thus they don't really lean toward any specific tooling/libraries (nor suggest them etc...)

That in my opinion goes against the idea of Angular as an opinionated framework which provides clear directions to developers, so I am not really a big fan of it.

I'd imagine that there must be valid reasons as to why the Angular team does not want to be opinionated regarding such tooling, but yeah that can leave us developers to sometimes struggle :man_shrugging: 

Anyways yeah I totally agree with you and it is a shame that tslint worked out of the box but for eslint we need to jump hoops to get it working, but it is what it is I'd imagine, and thankfully there are projects like angular-eslint that help in that regard from their side :slightly_smiling_face:

**Comment by alan-agius4** [comment]
As mentioned above, Angular is less opinionated on linting in general. Eslint is not as fast or memory efficient as tslint. That said, the recommended approach is to use [angular-eslint](https://github.com/angular-eslint/angular-eslint/) which does integrate nicely with the Angular CLI and with it's built-in schematics it configures the project using the optimal settings.

**Comment by digeomel** [comment]
> As mentioned above, Angular is less opinionated on linting in general. Eslint is not as fast or memory efficient as tslint. That said, the recommended approach is to use [angular-eslint](https://github.com/angular-eslint/angular-eslint/) which does integrate nicely with the Angular CLI and with it's built-in schematics it configures the project using the optimal settings.

The default settings coming out of angular-eslint are far from optimal, except only for the simplest projects. It took me several days to get the right configuration in our previous project, so that I could bring down linting time from several minutes to some tenths of seconds as it was before with tslint. But many people are still using tslint.
