### ISSUE TITLE
Multiple documentation routes not rendering on firefox

### ISSUE THREAD

**Issue by meridsa** [angular/angular#45158]
### Description

Using firefox v97.0.1 (64-bit) on macos Monterey 12.2.1 Intel. Multiple routes are not rendering with the error message: 

ERROR Error: [v13.2.2] [DocViewer] Error preparing document 'guide/using-libraries': 

This includes:

- https://angular.io/guide/using-libraries
- https://angular.io/guide/creating-libraries
- https://angular.io/guide/angular-package-format
- https://angular.io/guide/router

amongst others, though not the overview page for routing and navigation, or library overview.

### What is the affected URL?

https://angular.io/guide/router

### Please provide the steps to reproduce the issue

Please see description.

### Please provide the expected behavior vs the actual behavior you encountered

Expected: Page renders.
Observed: Page does not render, and loading bar runs forever.

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/35993351/154997705-0f1c140e-324e-43b9-bed2-22a8405e374d.png)

### Please provide the exception or error you saw

```true
ERROR Error: [v13.2.2] [DocViewer] Error preparing document 'guide/creating-libraries':
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
macos monterey 12.2.1 (Intel)
firefox 97.0.1
```

**Comment by dario-piotrowicz** [comment]
Same here on Ubuntu :sweat: 
![Screenshot at 2022-02-21 21-03-45](https://user-images.githubusercontent.com/61631103/155026032-b54ff146-c23d-4c97-9944-514fc5d23487.png)

**Comment by gkalpak** [comment]
It seems to work fine for me. Are you still getting it, @meridsa?
Does it happen on other browsers? Can you post the complete console output?

**Comment by ersatzhero** [comment]
Hello,

I have the same issue on Firefox aswell. I noticed when I deactive/pause the Ghostery plugin it works again.

Regards

**Comment by meridsa** [comment]
Still does not work. Pausing the Ghostery plugin worked for me too. So it seems that Ghostery/spooky tracking of yours is causing this issue.

**Comment by alxhub** [comment]
Closing as not actionable - the issue appears to be triggered by a third-party extension. We would of course be happy to accept a PR that fixes this issue if there is a workaround we can apply in AIO, but this is not something that we otherwise have the bandwidth to investigate/support.
