### ISSUE TITLE
Creating a checkbox with the type attribute as a bound variable (instead of explicitly declaring type="checkbox") does not appear to bind the FormControl value to the input

### ISSUE THREAD

**Issue by jamesbrobb** [angular/angular#45150]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Not sure

### Description

If you create a checkbox input using a dynamic value for the `type` attribute, the FormControl value does not appear to be bound correctly to the input value.

Dynamic definition for control:

```
control = {
    key: 'test',
    type: 'checkbox',
    value: true
  }

form = new FormGroup({
  [control.key]: new FormControl(control.value)
});
```

Template markup:

```html
<form [formGroup]="form">
    <input [formControlName]="control.key"
      [id]="control.key"
      [name]="control.key"
      [type]="control.type">
</form>
```

The resulting html wrongly includes a `value` attribute that is set to the initial value of `true`. And the initial visual checked state of the checkbox is incorrect - it's unchecked

```html
<input  id="test" name="test" type="checkbox" value="true" class="ng-valid ng-dirty ng-touched">
```

When the checkbox is toggled the FormControl value is set to 'true' and then does not change.

--------------------------------------------------------------------------------------

When the `type` attribute of the input is explicitly set to `'checkbox'` the `value` attribute is not set on the input and it functions correctly (https://stackblitz.com/edit/angular-ivy-fypwkc?file=src%2Fapp%2Fapp.component.html)

```html
<form [formGroup]="form">
    <input [formControlName]="control.key"
      [id]="control.key"
      [name]="control.key"
      type="checkbox">
</form>
```

Results in:

```html
<input type="checkbox" id="test" name="test" class="ng-pristine ng-valid ng-touched">
```

This issue can also be demonstrated using an extended version of the 'Building dynamic forms' example that can be found here https://angular.io/guide/dynamic-form

https://stackblitz.com/edit/angular-qxye7f?file=src%2Fapp%2Fapp.component.ts

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-n7qtgf?file=src%2Fapp%2Fapp.component.html

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.2
Node: 16.13.2
Package Manager: npm 8.3.1
OS: darwin x64

Angular: 13.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
rxjs                            7.4.0
typescript                      4.5.4
```

**Comment by Airblader** [comment]
This is because the CVAs select on the type, and having that be bound prevents Angular from applying the appropriate CVA. This is a duplicate of the same issue that exists for input type number.

**Comment by jamesbrobb** [comment]
Thanks for the explanation @Airblader
