### ISSUE TITLE
using @Attrbute in TS throws an error during compilation

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#4515]
It looks like if I use the `@Attribute` on a class constructor:
```js
constructor(@Attribute('tabindex') tabindex: string) {}
```
it causes the TS compiler to throw a semantic error:
```sh
src/app/components/checkbox/checkbox.ts(63,14): error TS1239: Unable to resolve signature of parameter decorator when called as an expression. Supplied parameters do not match any signature of call target.
```

**Comment by pkozlowski-opensource** [comment]
What version of ng2? Could you please provide a minimal plunker? AFAIK you can't inject attributes on the top-level element, this _might_ by your issue.

Anyway, send a plunk.

**Comment by rolandjitsu** [comment]
@pkozlowski-opensource I am not sure how to create a plunk with the TS compiler, but you can see the [line](https://github.com/rolandjitsu/ng2-lab/blob/master/src/app/components/checkbox/checkbox.ts#L62) at which this occurs. I've been having this error around for a while. It has no impact on the output, but it keeps complaining.

I am not sure what you mean by I cannot inject attributes on top level elements. Could you elaborate on that please?

**Comment by naomiblack** [comment]
@alexeagle is this something you can reproduce?

**Comment by alexeagle** [comment]
My guess is our typings are related, and they are completely changing in the alpha-41 release, so please see if you can reproduce next week.

**Comment by rolandjitsu** [comment]
@alexeagle sure, I will try it as soon as the release is out and close if it doesn't occur anymore.

**Comment by Fank** [comment]
I can confirm this issue, after upgrading to alpha44 it still exists:
```
typescript/app/shared/input.ts(56,4): error TS1239: Unable to resolve signature of parameter decorator when called as an expression.
  Supplied parameters do not match any signature of call target.
typescript/app/shared/input.ts(57,4): error TS1239: Unable to resolve signature of parameter decorator when called as an expression.
  Supplied parameters do not match any signature of call target.
typescript/app/shared/input.ts(58,4): error TS1239: Unable to resolve signature of parameter decorator when called as an expression.
  Supplied parameters do not match any signature of call target.
typescript/app/shared/input.ts(59,4): error TS1239: Unable to resolve signature of parameter decorator when called as an expression.
  Supplied parameters do not match any signature of call target.
```

Line 56-59 are the `@Attribute` lines
```typescript
	constructor(
		@Inject(ElementRef) elementRef: ElementRef
		,@Attribute("type") type: string
		,@Attribute('editable') editable: string
		,@Attribute('rows') rows: number
		,@Attribute('required') required: boolean
	) {
		var self = this;
		this.type = type || 'text';
		this.editable = editable || 'default';
		this.rows = rows || 1;
		this.required = required || false;
		this._element = elementRef;
	}
```

**Comment by rolandjitsu** [comment]
Yes, still there.

**Comment by alexeagle** [comment]
I can't repro - can you help?
```
$ cat tsconfig.json
{
    "compilerOptions": {
        "target": "es5",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "module": "commonjs",
        "noImplicitAny": false,
        "outDir": "built",
        "rootDir": ".",
        "sourceMap": false
    },
    "exclude": [
        "node_modules"
    ]
}alexeagle-macbookpro2:test777 alexeagle$ cat app.ts
import {Component, Attribute} from 'angular2/angular2';

@Component({
   selector: 'greet',
   template: 'Hello {{name}}!'
 })
 class Greet {
   name: string;
   type: string;
   constructor(@Attribute("type") type: string) {
     this.name = 'World';
	 this.type = type;
   }
 }
 alexeagle-macbookpro2:test777 alexeagle$ tsc
```

**Comment by rolandjitsu** [comment]
@alexeagle my `tsconfig.json` looks like:
```js
{
	"compilerOptions": {
		"declaration": false,
		"module": "system",
		"target": "es5",
		"emitDecoratorMetadata": true,
		"listFiles": true,
		"noImplicitAny": false,
		"noLib": false,
		"removeComments": true,
		"sourceMap": true,
		"experimentalDecorators": true
	},
	"exclude": [
		"node_modules"
	]
}
```
But you could just clone my [repo](https://github.com/rolandjitsu/ng2-lab) and try it locally.

**Comment by rolandjitsu** [comment]
Just that the repo is at an old version, though I still have the same message when compiling with the latest alpha version.

**Comment by alexeagle** [comment]
When I run tsc with your repo at head, I get tons of errors, including
duplicate definitions from typescriptServices.d.ts

One thing I see is that you use "module": "system" which requires
"moduleResolution": "node", otherwise it assumes you are loading in the
browser and uses the classic module resolution.
Also your tsconfig.json has a version:1.5.3 at the top which is really
fishy, angular2 requires TS 1.6

If adding that doesn't fix it, could you make a more minimal repro?

**Comment by rolandjitsu** [comment]
Yeah, the tons of errors it's because `"moduleResolution": "node"`. Locally I have:
```js
{
	"compilerOptions": {
		"declaration": false,
		"module": "system",
		"target": "es5",
		"emitDecoratorMetadata": true,
		"listFiles": true,
		"noImplicitAny": false,
		"noLib": false,
		"removeComments": true,
		"sourceMap": true,
		"experimentalDecorators": true
	},
	"exclude": [
		"node_modules"
	]
}
```
And as soon as I add the `moduleResolution` option, I do get tons of errors too. Lots of `Duplicate identifier ...`. I am unsure what the option does, but not adding it will solve all the tons of errors. On top of that from [Compiler Options](https://github.com/Microsoft/TypeScript/wiki/Compiler%20Options), that options is experimental, so it might be that is not very stable and that is why is causing all these errors.

**Comment by alexeagle** [comment]
If you want angular2 typings to work, they need to come from node_modules.
If you get duplicate identifier from adding it, that's because the
typescript node_module comes with typings included, and you're providing
them to the compiler a second time.
One of these is
./node_modules/gulp-tslint/node_modules/tslint/typings/typescriptServices.d.ts
which I also ran into. (if you get stuck, I can research what I did to fix
that)

**Comment by rolandjitsu** [comment]
I see. I actually switched to the typing from `node_modules`, at least the ones for angular, 2 versions back, I think. I also think I know why I get duplicates errors, if I follow what you are saying, if I use that option, everything will be resolved from `node_modules` and I will not need to be include again by me sourcing them in the gulp task. And I actually do include the typings myself during the gulp task.

I just removed that and the duplicate errors are gone, but now I get problems with my own modules. Do I need to have the declaration option enabled for my own modules so I don't get things like `Cannot find module 'app/components'.`? Or how do I fix that?

**Comment by rolandjitsu** [comment]
So it looks like now I need to reference modules that I write with absolute paths as such `../../../common/animation` as an example. Before I could just use `common/animation` without the compiler complaining. Is there a way around this?

**Comment by alexeagle** [comment]
Actually I have that problem as well, and inside angular we are using
classic module resolution.
https://github.com/angular/angular/issues/4704
I hope to work on that tomorrow, and using relative paths is the obvious
fix I had in mind, but the team would prefer a way around it just as you
suggest.

**Comment by rolandjitsu** [comment]
That is a shame. I'll try other things as well tomorrow, hopefully I'll find something that works. Also, I think that this error message might be gone, but right now there are way to many errors to be sure of it. I hope that you will figure out a way to fix this and share it :+1:

**Comment by alexeagle** [comment]
Sounds like there is not an issue in Angular at present. We will follow up in #4704 on the remaining issues we both share.
