### ISSUE TITLE
Set __Zone_disable_xxx to true sill trigger change detection.

### ISSUE THREAD

**Issue by wellwind** [angular/angular#45161]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I'm trying set some zone flags by Angular guide to disable requestAnimationFrame and timers patch.

https://angular.io/guide/zone#setting-up-zonejs

```typescript
(window as any).__Zone_disable_requestAnimationFrame = true;
(window as any).__Zone_disable_timers = true;
import 'zone.js';
```

In the component, I have added following code:

```typescript
  ngAfterViewInit() {
    setTimeout(() => {
      this.value1 = 1;
    }, 1000);

    requestAnimationFrame(() => {
      this.value2 = 2;
    });
  }
```

Update field data in `setTimeout` and `requestAnimationFrame` should not trigger change detection.

But updated `value1` and `value2` still are displayed on screen.

### Please provide a link to a minimal reproduction of the bug

https://github.com/wellwind/ng-zone-flag-demo

### Please provide the exception or error you saw

```true
No error, but change detection should not trigger.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 13.2.4
Node: 14.15.0
Package Manager: npm 6.14.8
OS: darwin x64

Angular: 13.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.4
@angular-devkit/build-angular   13.2.4
@angular-devkit/core            13.2.4
@angular-devkit/schematics      13.2.4
@angular/cli                    13.2.4
@schematics/angular             13.2.4
rxjs                            7.5.4
typescript                      4.5.5
```

**Comment by JiaLiPassion** [comment]
@wellwind , you need to create a `zone-flag.ts` file to include

```
(window as any).__Zone_disable_requestAnimationFrame = true;
(window as any).__Zone_disable_timers = true;
```

and import it in `polyfills.ts`

```
import `./zone-flags`;
import 'zone.js';  // Included with Angular CLI.
```

Please reference the doc https://angular.io/guide/zone#setting-up-zonejs here.

**Comment by JiaLiPassion** [comment]
Closes this one since this is not an issue. @wellwind , if you still have question after following this guide https://angular.io/guide/zone#setting-up-zonejs, please reopen this issue.

**Comment by wellwind** [comment]
import `zone.js` first make sence, after move code into `zone-flag.ts` and import it before `zone.js` it works as well.

Thanks :)
