### ISSUE TITLE
URL sanitization breaks URLs containing commas in srcset

### ISSUE THREAD

**Issue by edenstrom** [angular/angular#45164]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Hey,

We're using `[innerHTML]="content"` in angular, where content is HTML from WordPress. WordPress is using cloudinary which generates URLs like 

```
https://res.cloudinary.com/<container>/images/w_844,h_562/f_auto,q_auto/<id>/image.jpg
```

The code that sanitizes `srcset` splits on `,` and joins on `, ` which breaks the URL above.

Code reference: https://github.com/angular/angular/blob/master/packages/core/src/sanitization/url_sanitizer.ts#L58

### Please provide a link to a minimal reproduction of the bug

https://codesandbox.io/s/sparkling-resonance-8dyt3u?file=/src/app/app.component.ts

### Please provide the exception or error you saw

```true
If you look at the HTML output, one of the images are broken. The other one works.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.0.4
Node: 16.14.0
Package Manager: npm 6.14.13
OS: darwin arm64

Angular: 12.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.4
@angular-devkit/build-angular   12.0.4
@angular-devkit/core            12.0.4
@angular-devkit/schematics      12.0.4
@angular/cdk                    12.1.0
@angular/material               12.1.0
@nguniversal/builders           12.0.2
@nguniversal/express-engine     12.0.2
@schematics/angular             12.0.4
rxjs                            6.6.7
typescript                      4.2.4
```

### Anything else?

A fix could be to join on "," instead. Though it will try to sanitize URLs which aren't URLs.

**Comment by JoostK** [comment]
If you have control over how those URLs are generated/inserted then you may be able to percent-encode the comma to `%2c`, avoiding the issue.
