### ISSUE TITLE
Retire the magic re-writing of private-constructor-Class to Interface

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#4518]
As part of https://github.com/angular/angular/issues/3082
I want to use the Typescript compiler's outputs to distribute our typings to users.
So the magic we have in dgeni for re-writing classes-which-should-not-be-constructed to be represented as interfaces can't be retained.
Anyway this did not satisfy Dart users, to whom these classes still appear instantiatable.

Instead, we should create abstract superclasses for each of the types where we have an `@private` constructor. These classes should take the name and documentation of the existing class. The concrete implementation needs a name, and there is no great choice. I propose eg. 
```
abstract class Compiler {}
class Compiler_ extends Compiler {}
```

Note, I talked to @mhevery about this, there is one concern which is that these new classes bloat our codesize. But I checked in our current minified bundle and this becomes
`m=function(){function e(){}return e}();t.Compiler=m;`
for each of O(10) classes, and that could potentially be further optimized.

**Comment by naomiblack** [comment]
@alexeagle I put this in alpha-41 since I think it's not essential/urgent for anyone speaking at angular connect. Please move it up to alpha-40 if you think it's blocking anyone.

**Comment by alexeagle** [comment]
This is part of the change in typings I demo'ed. We can't release typings
that expose our private constructors. I'll move to alpha-40

**Comment by alexeagle** [comment]
Here is the proposal:
http://www.typescriptlang.org/Playground#src=%2F%2F%20re-exported%20to%20users%0Aexport%20abstract%20class%20Compiler%20%7B%0A%09%2F**%20%40internal%20*%2F%0A%09protected%20_foo%3A%20number%3B%0A%09do()%3A%20void%20%7B%0A%09%09console.log(this._foo)%3B%0A%09%7D%0A%7D%0A%0A%2F%2F%20Not%20re-exported%20to%20top-level%0Aexport%20class%20Compiler_%20extends%20Compiler%20%7B%0A%09constructor(foo%3A%20number)%20%7B%0A%09%09super()%3B%0A%09%09this._foo%20%3D%20foo%3B%0A%09%7D%0A%7D%0A
```
// re-exported to users
export abstract class Compiler {
	/** @internal */
	protected _foo: number;
	do(): void {
		console.log(this._foo);
	}
}

// Not re-exported to top-level
export class Compiler_ extends Compiler {
	constructor(foo: number) {
		super();
		this._foo = foo;
	}
}
```

Note that the protected member will be exposed in the .d.ts file even though private members are not, so it needs `@internal`. It must be protected so the subclass can assign to it.

**Comment by alexeagle** [comment]
@mhevery @tbosch can you take a look at the above and comment before I make this change widely?
cc: @IgorMinar as a sol'n to the current problem of symbols not injectable because their runtime value disappeared

**Comment by mhevery** [comment]
Why do we need to put `_foo` in `Compiler` rather then `Compiler_`?

Otherwise this seem reasonable to me.

**Comment by alexeagle** [comment]
Because it is referenced in Compiler. Is there another way?
Also I have not yet thought about how this will translate to dart. I know
we don't allow protected right now.

**Comment by mhevery** [comment]
Ohh, did not see that. I would make Compiler totally abstract.

```
// re-exported to users
export abstract class Compiler {
  abstract do(): void;
}

// Not re-exported to top-level
export class Compiler_ extends Compiler {
    protected _foo: number;

    constructor(foo: number) {
        super();
        this._foo = foo;
    }

    do(): void {
        console.log(this._foo);
    }
}
```

**Comment by alexeagle** [comment]
ah, yes of course. a bigger change, but then protected is not needed, and we can keep our shorthand property declarations in the constructor signature as well

**Comment by IgorMinar** [comment]
@alexeagle why will Misko's version result in a bigger change? I'd expect your code splitting version to be more complicated to implement.

**Comment by alexeagle** [comment]
Sorry I wrote that in a hurry - it's only bigger in the sense that a different transformation is needed, but either way it's simple and mechanical. Working on it now.

**Comment by alexeagle** [comment]
One other complication is getters. We currently have readonly properties, by implementing a getter and no setter in our concrete class (eg `DebugElement.componentInstance`)
I believe from discussion in https://github.com/Microsoft/TypeScript/issues/12 that we have no way to model this in the abstract class - the typechecker will allow users to modify these properties.

**Comment by IgorMinar** [comment]
fixed as of a40
