### ISSUE TITLE
Explain handling of Promise result for router.navigate()

### ISSUE THREAD

**Issue by coyoteecd** [angular/angular#45202]
### Description

The documentation for Router.navigate/navigateByUrl mentions that these methods return a Promise, resolving with the navigation result. The examples however ignore the promise result, treating navigation as a fire-and-forget.

When using linters with [rules that catch these "floating promises"](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md), all our router.navigate() calls in various component functions legitimately trigger lint warnings.

### What is the affected URL?

https://angular.io/api/router/Router#navigate

### Please provide the steps to reproduce the issue

An example below:

```ts
@Component({
  selector: 'app-comp',
  templateUrl: './my.component.html'
})
export class MyComponent {

  constructor(
    private router: Router,
  ) {}

  onButtonClick() {
     if (... some condition ...) {
       // should this be awaited? 
       // what if navigate is inside ngOnInit(), which is not async?
       this.router.navigate(['some-path']);
    }
  }
}
```

### Please provide the expected behavior vs the actual behavior you encountered

I would like an official statement from the Angular team that it's okay to ignore the result of `router.navigate()` in our components, and - if possible - the design rationale for why it's returning a Promise that can be ignored. Ideally, this should be included as a note in the documentation, for instance a comment in the Usage notes section would be useful.

**Comment by Airblader** [comment]
The main reason to me to look at the result is to check for errors in case the navigation failed. However, virtually all apps I've worked on redirect when guards reject a navigation attempt, once again rendering it unnecessary to look at the result.

**Comment by atscott** [comment]
The use-case might be that you're interested in the result of the navigation at the call-site and/or perform some additional action after navigation completes but I don't have any specific examples. It's pretty uncommon but removing the feature would be a breaking change and anyone actually using the feature would have a much harder time getting equivalent functionality.

Yes, you can ignore the result. My opinion is that this does not require additional documentation but I'm happy to review a PR if you feel strongly about this.

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
