### ISSUE TITLE
Use @angular/serviceworker@13.2.4 with Angular 12

### ISSUE THREAD

**Issue by frankyvij** [angular/angular#45215]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

I am trying to make the @angular/serviceworker@13.2.4 work with Angular 12. Due to some limitations, specially browser compatibility, I cannot upgrade to Angular 13, however, I need access to swUpdate.versionUpdates so that I can manage Service Worker and our app updates more effectively.

What exactly this version of service worker needs that it needs to run on Angular 13, and cannot run with Angular 12?

### Please provide the exception or error you saw

```true
npm run build

> ic2web@0.0.0 build C:\Development\IC.Web.Mobile
> ng build --sourceMap=true --base-href /mini/

Option "extractCss" is deprecated: Deprecated since version 11.0. No longer required to disable CSS extraction for HMR.
Warning: Support was requested for IE 11 in the project's browserslist configuration. IE 11 support is deprecated since Angular v12.
For more information, see https://angular.io/guide/browser-support
✔ Browser application bundle generation complete.
✔ ES5 bundle generation complete.
✔ Copying assets complete.
✔ Index html generation complete.
✖ Service worker generation failed.
Must use import to load ES Module: C:\Development\IC.Web.Mobile\node_modules\@angular\service-worker\fesm2015\config.mjs
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ic2web@0.0.0 build: `ng build --sourceMap=true --base-href /mini/ `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ic2web@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fvij\AppData\Roaming\npm-cache\_logs\2022-02-28T17_27_05_274Z-debug.log
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Your global Angular CLI version (12.2.10) is greater than your local version (12.0.3). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.3
Node: 14.15.1
Package Manager: npm 6.14.8
OS: win32 x64

Angular: 12.0.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1200.3
@angular-devkit/build-angular      12.0.5
@angular-devkit/core               12.0.3
@angular-devkit/schematics         12.0.3
@angular/flex-layout               12.0.0-beta.34
@angular/material-moment-adapter   13.1.0
@angular/service-worker            13.2.4
@schematics/angular                12.0.3
rxjs                               6.6.7
typescript                         4.2.4
```

### Anything else?

I would really appreciate if we could maintain at least one to two versions of backward compatibility especially with the packages like this which are generally available outside of Angular.

**Comment by alan-agius4** [comment]
Hi @frankyvij,

Unfortunately, this is not possible as all Angular framework packages needs to be the same exact versions.

JFYI: version 13 brought a lot of changes in [APF](https://angular.io/guide/angular-package-format).

**Comment by frankyvij** [comment]
I understand but this is a highly unscalable approach to be taking forward every single angular version update.

Is there a way for me to fork and make it work?

**Comment by alan-agius4** [comment]
@frankyvij, to avail of the latest bug fixes and features you need to consume the latest versions, this is true for almost all packages out there.

You can fork the framework, build it and release it on a private NPM repo, but by doing so you choose to go on the unsupported path.
