### ISSUE TITLE
CORS problem on requests

### ISSUE THREAD

**Issue by Landris18** [angular/angular#45236]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I'm trying to make a POST request like this : 

`return this.http.post("http://192.168.28.88:6010/api"+ '/login', user);`

But this error happens : 

`Access to XMLHttpRequest at 'http://192.168.88.28:6010/api/login' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status. `

### Please provide the exception or error you saw

```true
`Access to XMLHttpRequest at 'http://192.168.88.28:6010/api/login' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status. `
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 11.2.14
Node: 17.5.0
OS: linux x64

Angular: 11.2.14
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.14
@angular-devkit/build-angular   0.1102.14
@angular-devkit/core            11.2.14
@angular-devkit/schematics      11.2.14
@angular/cdk                    12.1.1
@schematics/angular             11.2.14
@schematics/update              0.1102.14
rxjs                            6.6.7
typescript                      4.1.6
```

### Anything else?

I've tried to configure the proxy but doesn't work 

Thanks for your help.

**Comment by jessicajaniuk** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Landris18** [comment]
Ok , but i still don't understand why you don't help me 😉
