### ISSUE TITLE
Angular 13 Universal (SSR) slow after migration from Angular 11

### ISSUE THREAD

**Issue by dirk-jacobs** [angular/angular#45238]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Our Angular 11 Universal application  had a first page loaded after 75ms

After upgrading to Angular 13, no other code changes, loading time is about 1.6s !!!

### Please provide the exception or error you saw

```true
None
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.4
Node: 14.15.5
Package Manager: npm 6.14.11
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1302.4 (cli-only)
@angular-devkit/core         13.2.4 (cli-only)
@angular-devkit/schematics   13.2.4 (cli-only)
@schematics/angular          13.2.4 (cli-only)
```

**Comment by jessicajaniuk** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
