### ISSUE TITLE
Angular project features support hot swap

### ISSUE THREAD

**Issue by lee-200** [angular/angular#45231]
### Description

In the case where the deployment environment cannot be stopped, I hope that angular can support the hot-plug function like Java，

### Proposed solution

无

### Alternatives considered

无

**Comment by lee-200** [comment]
Or are there any suggestions or solutions that can achieve the function of hot swapping? thanks

**Comment by lee-200** [comment]
Or is there any way to build separate components to be hot swappable

**Comment by JoostK** [comment]
After building an Angular app you end up with a bunch of files that need to be deployed somewhere. Those are just static resources at that point, so new requests will then be served using the new code and there is no concept of hot reloading.

In development environments the CLI already supports both incremental compilations and Hot Module Replacement (HMR).
