### ISSUE TITLE
Singleton Service Constructor being called for every route change

### ISSUE THREAD

**Issue by PavanDhulipalla** [angular/angular#45232]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I am just trying to use a Service to share data across the application, I have provided this service for Root in service itself, I do not have the same service provided anywhere else, followed all recommended practices yet the Service is getting invoked fro every route change and the constructor is being called, getting a different instance for every component which is not the expected behaviour.

Ideally, the singleton service should get instantiated just once - but it's creating instances for every root change!

MetaTagsService  - 

@Injectable({
  providedIn: 'root',
})
export class MetaTagsService {
  ///
}

AppModule is clean - I don't have the above provided here
RouterModule is provided forRoot 

ContactUsComponent - 
import { Component, OnInit } from '@angular/core';
import { MetaTagsService } from '../services/meta-tags.service';
import { Subscription } from 'rxjs';
@Component({
  selector: 'app-contact-us',
  templateUrl: './contact-us.component.html',
  styleUrls: ['./contact-us.component.css'],
})
export class ContactUsComponent implements OnInit {
  //For sharing data across components
  subscription: Subscription;

  constructor(
    private metaTagDataService: MetaTagsService
  ) {
    //
  }
///
}

### Please provide the exception or error you saw

```true
No errors - Just unexpected behaviour.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI - 11.0.2
Core - 11.0.1
```

**Comment by JoostK** [comment]
Please share a runnable reproduction for us to investigate, as otherwise this isn't actionable.

**Comment by PavanDhulipalla** [comment]
@jnizet Thank you very much! Although this is more logical but somehow I did not pay attention to the detail. Yes I was using href  and using routerLink sorted the issue.
