### ISSUE TITLE
Links to animation guide and browser suport guide are returning 404

### ISSUE THREAD

**Issue by dionatan-g** [angular/angular#45258]
### Description

Both links listed on the md file of the package animation are returning 404.

https://github.com/angular/angular/blob/master/packages/animations/guide/browser-support
https://github.com/angular/angular/blob/master/packages/animations/guide/animations

### What is the affected URL?

https://github.com/angular/angular/blob/master/packages/animations/PACKAGE.md

### Please provide the steps to reproduce the issue

Navigate to https://github.com/angular/angular/blob/master/packages/animations/PACKAGE.md and click in one of the two listed links.

### Please provide the expected behavior vs the actual behavior you encountered

Should be able to navigate to the desired link.

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/44219120/156731222-a39f0714-e862-4df5-b4bd-978db5b16a9a.png)

### Please provide the exception or error you saw

```true
404 not found
```

**Comment by JoostK** [comment]
These files are authored for consumption [on angular.io](https://angular.io/api/animations), not as raw Markdown.

This is similar enough to #45000 that I'll close this as a duplicate, where `@see` tags only result in correct URLs when deployed on angular.io.
