### ISSUE TITLE
Cannot create component without inserting into DOM without the deprecated `ComponentFactory`

### ISSUE THREAD

**Issue by PowerKiKi** [angular/angular#45263]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Since Angular 13 `ComponentFactory.create()` is deprecated. It is advertised that we should instead use `ViewContainerRef.createComponent()`. However the behavior between those two methods are different and cannot necessarily replace each other for all use-cases.

My use-case is to create a component dynamically, **not** insert it into DOM, call a few custom methods on it, and then destroy the component. But `ViewContainerRef.createComponent()` will always insert the newly created component into DOM, wreaking havoc in my layout.

Basically I'd like to do something like that:

```ts
private validate(component: Type<DropdownComponent>): boolean {
    const injector = Injector.create({providers: this.getMyCustomProvider(), parent: this.getMyParentInjector()});
    const factory = this.componentFactoryResolver.resolveComponentFactory<DropdownComponent>(component);

    const dropdownComponentRef = factory.create(injector);
    const result = dropdownComponentRef.instance.isValid();
    dropdownComponentRef.destroy();

    return result;
}
```

Was it intentional that a component cannot be instantiated without being inserted into DOM anymore ? Or should it be considered a regression in the feature set of the framework ?

Or is there an alternative API that would allow me to instantiate and destroy components without ever inserting them into DOM ?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.5
Node: 14.19.0
Package Manager: yarn 1.22.17
OS: linux x64

Angular: 13.2.5
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.5
@angular-devkit/build-angular   13.2.5
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
@angular/flex-layout            13.0.0-beta.38
@schematics/angular             13.2.5
ng-packagr                      13.2.1
rxjs                            7.5.4
typescript                      4.5.5
```

**Comment by sibiraj-sr** [comment]
And previously, components can be created outside components and directives. And, now that `ComponentFactoryResolver` is deprecated couldn't find any alternatives for the same.

```ts
const componentFactoryResolver = injector.get(ComponentFactoryResolver);
this.applicationRef = injector.get(ApplicationRef);

const factory = componentFactoryResolver.resolveComponentFactory(MyComponent);

this.componentRef = factory.create(injector, []);
this.applicationRef.attachView(this.componentRef.hostView);
```

**Comment by GeorgianStan** [comment]
I also face this issue and a workaround is to inject ViewContainerRef inside the service.
Like in this [example](https://stackoverflow.com/revisions/71364435/1)

**Comment by patryk-zielinski93** [comment]
> And previously, components can be created outside components and directives. And, now that `ComponentFactoryResolver` is deprecated couldn't find any alternatives for the same.
> 
> ```ts
> const componentFactoryResolver = injector.get(ComponentFactoryResolver);
> this.applicationRef = injector.get(ApplicationRef);
> 
> const factory = componentFactoryResolver.resolveComponentFactory(MyComponent);
> 
> this.componentRef = factory.create(injector, []);
> this.applicationRef.attachView(this.componentRef.hostView);
> ```
> 
> Mostly when rendering outside angular app.

I have the same problem

**Comment by JGrancha** [comment]
I have a similar problem that I mentioned in this issue but nobody has been able to answer yet. I also think that both forms should be maintained. They are complementary.
#44926

**Comment by AndrewKushnir** [comment]
Hi, just a quick update: we plan to look into replacement APIs for the described use-case. The new API should provide an ability to create a `ComponentRef` instance, i.e. you should be able to do something like this:
```
const appRef = injector.get(ApplicationRef);
const compRef = createComponentRef(MyComponent, injector);
appRef.attachView(compRef.hostView);
```
We don't have an ETA yet, but we'd make sure that it's available before we remove `ComponentFactory` from the public API.

**Comment by fhljys** [comment]
Following

**Comment by Ghostbird** [comment]
We've got the same problem. We need to pop a modal that shows a `TemplateRef` constructed by the component initialisation.

In this case the component is never added anywhere in the page, only that specific sub-view is shown.
In this case the `viewRef` where the template is rendered is ultimately supplied through Angular Material's `MatDialog` service, but this is abstracted away (as it should be).

**Comment by id1945** [comment]
//====================================================//
👉 https://stackblitz.com/edit/angular-lazy-loading-compiler-module-async-v13 👈
//====================================================//

`  /**
   * Lazy component
   */
  public async loadComponent() {
    await import('./lazy/lazy.module').then((m) => {
      // Register
      const componentA = m.LazyModule.components.LazyAComponent;
      const componentB = m.LazyModule.components.LazyBComponent;
      const module = (<any>m)[Object.keys(m)[0]];
      const moduleRef: NgModuleRef<any> = createNgModuleRef(module, this.injector);
      // Reset
      this.anchor.clear();
      // Create component
      const componentRefA = this.anchor.createComponent(componentA, { ngModuleRef: moduleRef });
      const componentRefB = this.anchor.createComponent(componentB, { ngModuleRef: moduleRef });
      // @Input data
      componentRefA.instance.test = "Update input string A";
      componentRefB.instance.test = "Update input string B";
    });
  }`

**Comment by LubosD** [comment]
@id1945 How is this relevant? You're obviously placing these components into the DOM.

**Comment by Ghostbird** [comment]
@id1945 This issue is about the case where you _cannot_ have a `this.container` to call `createComponent` on, for whatever reason.

**Comment by pitAlex** [comment]
I have another use case where I am struggling with what to replace componentFactoryResolver with. In my situation, I have a page that is fully done in angular, but the result is a mostly static page. So it is rendered with node and on the client-side, I use compileModuleAsync along with componentFactoryResolver to target the 1 or 2 sections that are the already rendered in DOM to make them controllable with angular on the client-side so that they become functional. 
Imagine a page where at the bottom it has a QnA section and that section would be controllable by angular. Node renders the initial view and then in comes angular on the client-side and replaces it with the interactable version where it has things like loading more answers via ajax, having a reply form, voting, etc. This helps us a lot with web core vitals where the js size is smaller and by having only parts of the page be in angular on the client-side we avoid triggering a high LCP as the entire DOM would get replaced in case of a full-page bootstrap.
In my case, I benefited from "factory.create(injector,[],selector)" where "selector" would be the target section.

**Comment by Ghostbird** [comment]
@pitAlex I may misunderstand your use-case, but I think we have a similar use-case. However in that case we use [Web Components](https://developer.mozilla.org/en-US/docs/Web/Web_Components). In that case we don't need the `componentFactoryResolver`. An example of how to build one in Angular can be found [here](https://coryrylan.com/blog/using-web-components-in-angular). But maybe you already knew that, and there's a reason why it's not appropriate for your use case.

**Comment by pitAlex** [comment]
@Ghostbird web components are not good in my case. I don't see them being good for big sections, I am not sure they are very SEO friendly either.

**Comment by pkozlowski-opensource** [comment]
@tonysamperi the alternative is being worked on in #46685

**Comment by tonysamperi** [comment]
@pkozlowski-opensource I saw the commits, cool! Thanks for letting me know!
