### ISSUE TITLE
PreloadAllModules doesn't work for modules under a lazy loading module

### ISSUE THREAD

**Issue by changhuixu** [angular/angular#45264]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

PreloadAllModules works only for lazy loading modules registered under the Root Router Module.
If a lazy loading module has a few other child lazy loading modules, then these "grand-children" won't be preloaded.
Note: there's no config in `RouterModule.forChild()`

**Comment by JoostK** [comment]
Please fill in all details of the issue template, including a reproduction.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
