### ISSUE TITLE
Unclear how to start discussions about Angular's development

### ISSUE THREAD

**Issue by Chealer** [angular/angular#45272]
### Description

Angular's documentation and website does not offer to initiate a discussion on a forum about its development as far as I can see. The only discussion forum that I can see is in [the _Discussions_ tab of its GitHub project](https://github.com/angular/angular/discussions) (here). Strangely, there appears to be no way to start a discussion there at this time (which may explain why only 2 were started, even though the first one was started several months ago).

### What is the affected URL?

None in particular

### Please provide the steps to reproduce the issue

This does not report a behavioral defect.

### Please provide the expected behavior vs the actual behavior you encountered

This does not report a behavioral defect.

### Please provide the exception or error you saw

This does not report a behavioral defect.

### Is this a browser-specific issue?

No

**Comment by AlirezaEbrahimkhani** [comment]
@AndrewKushnir 
Is there a forum approved by the Angular team that you would like to add to the documentation?
If so, I can add them to the documentation.
I know [Angular nation](https://www.angularnation.net/) that really helpful for someone who wants to have discussion with others and the discord server also.

**Comment by alan-agius4** [comment]
@AlirezaEbrahimkhani, 

There is a list of available channels in the [community](https://github.com/angular/angular#community) section of our read m. In the footer of the documentation application https://angular.io these are listed in the help section. 

Discussions on Github can only started by team members and this is typically used to discuss and gather feedback on RFCs.

**Comment by AndrewKushnir** [comment]
Closing based on Alan's comment above.

**Comment by Chealer** [comment]
@AndrewKushnir Alan's comment was intended for @AlirezaEbrahimkhani
