### ISSUE TITLE
Overwritten DOCUMENT injection token causes tests to fail

### ISSUE THREAD

**Issue by krilllind** [angular/angular#45278]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

#### Summary
Overriding InjectionToken `DOCUMENT` from `@angular/common` package in any test causes all tests to fail. This is because angular internally is relying on the same injection token during DOM cleanup routine introduced in
Angular 12 (`teardown: { destroyAfterEach: true }`). See [this line of code](https://github.com/angular/angular/blob/4332897baa2226ef246ee054fdd5254e3c129109/packages/platform-browser-dynamic/testing/src/dom_test_component_renderer.ts#L31) for reference.

#### Steps to Reproduce
1. Create a new Angular 13 project (running `ng new`)
2. Edit `providers` property of TestBed within `app.component.spec.ts` with the following
```ts
describe('AppComponent', () => {
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [
        RouterTestingModule
      ],
      declarations: [
        AppComponent
      ],
      providers: [
        {
          provide: DOCUMENT,
          useValue: { location: { origin: "https://test" } } as Document
        }
      ]
    }).compileComponents();
  });
});
```
3. Run `npm test`

### Please provide the exception or error you saw

```true
TypeError: this._doc.querySelectorAll is not a function
            at DOMTestComponentRenderer.removeAllRootElements (node_modules/@angular/platform-browser-dynamic/fesm2015/testing.mjs:37:36)
            at DOMTestComponentRenderer.insertRootElement (node_modules/@angular/platform-browser-dynamic/fesm2015/testing.mjs:30:14)
            at TestBedRender3.createComponent (node_modules/@angular/core/fesm2015/testing.mjs:1760:1)
            at Function.TestBed [as createComponent] (node_modules/@angular/core/fesm2015/testing.mjs:1616:1)
            at UserContext.<anonymous> (src/app/app.component.spec.ts:31:21)
            at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:372:1)
            at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:287:1)
            at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:371:1)
            at Zone.run (node_modules/zone.js/fesm2015/zone.js:134:1)
            at runInTestZone (node_modules/zone.js/fesm2015/zone-testing.js:567:1)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.5
Node: 14.17.5
Package Manager: npm 6.14.14
OS: win32 x64

Angular: 13.2.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.5
@angular-devkit/build-angular   13.2.5
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
@schematics/angular             13.2.5
rxjs                            7.5.4
typescript                      4.5.5
```

### Anything else?

Issue was initially discovered in Angular version 12.2.5 when enabling teardown setting for tests, however issue was also reproducible in latest version 13.2.5.

When disabling teardown, every test pass as expected in 12.2, however this was not the case for version 13.2 as tests were still failing with `{ teardown: { destroyAfterEach: false } }`

Here is the environment information where issue was initially discovered:
```true
Angular CLI: 12.2.5
Node: 14.17.5
Package Manager: npm 6.14.14
OS: win32 x64

Angular: 12.2.5
... animations, cli, common, compiler, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.5
@angular-devkit/build-angular   12.2.5
@angular-devkit/core            12.2.5
@angular-devkit/schematics      12.2.5
@angular/cdk                    10.2.7
@angular/compiler-cli           12.2.3
@angular/http                   7.2.16
@schematics/angular             12.2.5
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by JoostK** [comment]
This was also reported in #45031. The `DOCUMENT` token should be a `Document` and providing only a subset of features in a stub may get you into trouble once more methods from the interface start being used. Please update the test to provide the necessary methods.
