### ISSUE TITLE
ngsw-worker.js cache files which are not in dataGroups

### ISSUE THREAD

**Issue by UchihaYuki** [angular/angular#45280]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

No

### Description

Following is my ngsw-config.json
```json
{
  "$schema": "./node_modules/@angular/service-worker/config/schema.json",
  "index": "/index.html",
  "appData": {
    "version": "1.0.11"
  },
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "resources": {
        "files": [
          "/favicon.ico",
          "/index.html",
          "/manifest.webmanifest",
          "/*.css",
          "/*.js"
        ]
      }
    },
    {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/assets/**",
          "/*.(eot|svg|cur|jpg|png|webp|gif|otf|ttf|woff|woff2|ani)"
        ]
      }
    }
  ],
  "dataGroups": [
    {
      "name": "s3",
      "version": 2,
      "urls": [
        "https://s3.${BASE_DOMAIN}/**/*.7z",
        "https://s3.${BASE_DOMAIN}/**/*.csv",
        "https://s3.${BASE_DOMAIN}/**/*.gif",
        "https://s3.${BASE_DOMAIN}/**/*.midi",
        "https://s3.${BASE_DOMAIN}/**/*.png",
        "https://s3.${BASE_DOMAIN}/**/*.tif",
        "https://s3.${BASE_DOMAIN}/**/*.zip",
        "https://s3.${BASE_DOMAIN}/**/*.avi",
        "https://s3.${BASE_DOMAIN}/**/*.doc",
        "https://s3.${BASE_DOMAIN}/**/*.gz",
        "https://s3.${BASE_DOMAIN}/**/*.mkv",
        "https://s3.${BASE_DOMAIN}/**/*.ppt",
        "https://s3.${BASE_DOMAIN}/**/*.tiff",
        "https://s3.${BASE_DOMAIN}/**/*.zst",
        "https://s3.${BASE_DOMAIN}/**/*.avif",
        "https://s3.${BASE_DOMAIN}/**/*.docx",
        "https://s3.${BASE_DOMAIN}/**/*.ico",
        "https://s3.${BASE_DOMAIN}/**/*.mp3",
        "https://s3.${BASE_DOMAIN}/**/*.pptx",
        "https://s3.${BASE_DOMAIN}/**/*.ttf",
        "https://s3.${BASE_DOMAIN}/**/*.apk",
        "https://s3.${BASE_DOMAIN}/**/*.dmg",
        "https://s3.${BASE_DOMAIN}/**/*.iso",
        "https://s3.${BASE_DOMAIN}/**/*.mp4",
        "https://s3.${BASE_DOMAIN}/**/*.ps",
        "https://s3.${BASE_DOMAIN}/**/*.webm",
        "https://s3.${BASE_DOMAIN}/**/*.bin",
        "https://s3.${BASE_DOMAIN}/**/*.ejs",
        "https://s3.${BASE_DOMAIN}/**/*.jar",
        "https://s3.${BASE_DOMAIN}/**/*.ogg",
        "https://s3.${BASE_DOMAIN}/**/*.rar",
        "https://s3.${BASE_DOMAIN}/**/*.webp",
        "https://s3.${BASE_DOMAIN}/**/*.bmp",
        "https://s3.${BASE_DOMAIN}/**/*.eot",
        "https://s3.${BASE_DOMAIN}/**/*.jpg",
        "https://s3.${BASE_DOMAIN}/**/*.otf",
        "https://s3.${BASE_DOMAIN}/**/*.svg",
        "https://s3.${BASE_DOMAIN}/**/*.woff",
        "https://s3.${BASE_DOMAIN}/**/*.bz2",
        "https://s3.${BASE_DOMAIN}/**/*.eps",
        "https://s3.${BASE_DOMAIN}/**/*.jpeg",
        "https://s3.${BASE_DOMAIN}/**/*.pdf",
        "https://s3.${BASE_DOMAIN}/**/*.svgz",
        "https://s3.${BASE_DOMAIN}/**/*.woff2",
        "https://s3.${BASE_DOMAIN}/**/*.class",
        "https://s3.${BASE_DOMAIN}/**/*.exe",
        "https://s3.${BASE_DOMAIN}/**/*.js",
        "https://s3.${BASE_DOMAIN}/**/*.pict",
        "https://s3.${BASE_DOMAIN}/**/*.swf",
        "https://s3.${BASE_DOMAIN}/**/*.xls",
        "https://s3.${BASE_DOMAIN}/**/*.css",
        "https://s3.${BASE_DOMAIN}/**/*.flac",
        "https://s3.${BASE_DOMAIN}/**/*.mid",
        "https://s3.${BASE_DOMAIN}/**/*.pls",
        "https://s3.${BASE_DOMAIN}/**/*.tar",
        "https://s3.${BASE_DOMAIN}/**/*.xlsx"
      ],
      "cacheConfig": {
        "maxSize": 100,
        "maxAge": "4h"
      }
    }
  ]
}



```
You can see that *.json files shouldn't be cached. There is no entry for it in dataGroups. But I found my JSON files cached under:
```
ngsw:/:2:data:dynamic:s3:cache - https://mydomain.com
```

### Please provide a link to a minimal reproduction of the bug

No

### Please provide the exception or error you saw

```true
You can see that *.json files shouldn't be cached. But I found my JSON files cached under:

ngsw:/:2:data:dynamic:s3:cache - https://mydomain.com
```
```


### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 11.2.18
Node: 16.13.1
OS: win32 x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router     
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------  
@angular-devkit/architect       0.1102.18
@angular-devkit/build-angular   0.1102.18
@angular-devkit/core            11.2.18
@angular-devkit/schematics      11.2.18
@angular/cli                    11.2.18
@schematics/angular             11.2.18
@schematics/update              0.1102.18
rxjs                            6.6.7
typescript                      4.0.8
```

### Anything else?

No

**Comment by gkalpak** [comment]
Thx for reporting this, @UchihaYuki. This happens because the conversion of the URL globs to RegExp patterns does not insert `^`/`$` assertions at the beginning/end of the pattern. So a glob of `https://s3.mydomain.com/**/*.js` gets essentially converted to the regex `/https:\/\/s3\.mydomain\.com\/(?:.+\/)?[^/]*\.js/`, which would match both `https://s3.mydomain.com/foo/bar.js` as well as `https://s3.mydomain.com/foo/bar.json`.

One could argue that it would make more sense for Angular to automatically insert `^` and `$`, but that would be a significant breaking change at this point. As a work-around, you could add `^` and `$` yourself:

```diff
   "dataGroups": [
     {
       "name": "s3",
       "version": 2,
       "urls": [
         // ...
-        "https://s3.${BASE_DOMAIN}/**/*.js",
+        "^https://s3.${BASE_DOMAIN}/**/*.js$",
         // ...
```

##
I am also going to leave this open in order to discuss changing the behavior of the Angular SW to automatically wrap glob patterns in `^`/`$`.

**Comment by andreaslarssen** [comment]
@gkalpak Holy moly! This cost me a day of extra work.Why are urls globs instead of regexes when they in fact are converted behind the scenes? Regexes would give us more control over the urls, and probably avoid crazy bugs like this.

**Comment by andreaslarssen** [comment]
@gkalpak If the Angular team pushes a bug patch that handles the ^ and $ chars literally (like the glob pattern should as far as I can tell), all apps with that workaround will break.

**Comment by gkalpak** [comment]
> Why are urls globs instead of regexes when they in fact are converted behind the scenes? Regexes would give us more control over the urls, and probably avoid crazy bugs like this.

I am 100% with you on this one. I think globs were seen as easier for most people originally.

##
> If the Angular team pushes a bug patch that handles the ^ and $ chars literally (like the glob pattern should as far as I can tell), all apps with that workaround will break.

True. (It's a work-around, so not an ideal long-term solution 🤷‍♂️)
Also: LoL - #45738 (I don't know if it a coincidence or was inspired by this thread :grin:)

That said, we would not push a breaking change like this without good reason (and without following our [deprecation practices][1]). So, that's a low rick work-around imo.

##
Maybe it is best to add support for regexes and let people that need more complex patterns to use that (which avoids any breaking change). I've been thinking about something like:

```json5
"urls": [
  "https://example.com/**/*.js",  // Treat as a glob (with the current rules).
  "re:^https:\\/\\/example\\.com\\/(?:.+\\/)?[^/]*\\.js$"  // Treat as a regex (after stripping the `re:` prefix).
]
```

WDYT, folks?

[1]: https://angular.io/guide/releases#deprecation-practices

**Comment by andreaslarssen** [comment]
> I am 100% with you on this one. I think globs were seen as easier for most people originally.

I can see how that's an argument, yes.

> Also: LoL - https://github.com/angular/angular/pull/45738 (I don't know if it a coincidence or was inspired by this thread)

I can't believe this hasn't been reported before, knowing this bug probably would affect anyone caching non-mutating requests. This bug, in combination with the `maxSize` option yields some interesting scenarios.

> That said, we would not push a breaking change like this without good reason (and without following our [deprecation practices](https://angular.io/guide/releases#deprecation-practices)).

This issue could be considered by some as non-breaking as the workaround isn't really intended, and fixing a bug in itself isn't breaking, so it's good to hear that you'll treat it as one.

If you're going to change it, why not be more specific? Do you want tit to be as backwards compatible as possible? 

```
"urls": [
  {
    type: 'glob',
    url: "https://example.com/**/*.js"
  },
  {
    type: 'regex',
    url: ""^https:\\/\\/example\\.com\\/(?:.+\\/)?[^/]*\\.js$"
  }
]
```

**Comment by gkalpak** [comment]
Being more explicit would work too. We could keep the string form (defaulting to `glob`) for backwards compatibility and also support the more explicit forms (with `type`). We would need to increment the `configVersion` in the config generator, so that older ServiceWorkers know not to try and parse the new format.

BTW, we would need to apply this to [assetGroups > resources][2], [dataGroupd > urls][3] and [navigationUrls][4].
And we also need a strategy for handling negative patterns. Currently, a glob pattern is considered negative if it starts with `!`.

[1]: https://github.com/angular/angular/blob/2f5fd41a1987509fc0250c1441554984b6e11abc/packages/service-worker/config/src/generator.ts#L34
[2]: https://angular.io/guide/service-worker-config#resources
[3]: https://angular.io/guide/service-worker-config#urls
[4]: https://angular.io/guide/service-worker-config#navigationurls

**Comment by jekru** [comment]
> Also: LoL - #45738 (I don't know if it a coincidence or was inspired by this thread 😁)

This was not inspired by this thread, I used an api with a dollar sign in the route `users/{userPrincipalName}/contacts/{id}/photo/$value` and noticed that the caching wasn't working. You can read more about it in my issue #45737.

> As this issue could be considered by some as non-breaking as the workaround isn't really intended, and fixing a bug in itself isn't breaking, it's good to hear that you'll treat it as one.

Also my first thought but I can understand both sides.


I like the solution with an explicit `type`. And maybe we should add a description to pay attention that `glob` is not escaping all characters and that `regex` is recommended to avoid unexpected behavior.

**Comment by gkalpak** [comment]
@UchihaYuki, @andreaslarssen, @jekru: Would any one of you be up to creating a PR that updates docs to more clearly describe the current behavior? :pray: (That should be a good immediate improvement, while we plan out/implement the regex support.)

**Comment by andreaslarssen** [comment]
> @UchihaYuki, @andreaslarssen, @jekru: Would any one of you be up to creating a PR that updates docs to more clearly describe the current behavior? 🙏 (That should be a good immediate improvement, while we plan out/implement the regex support.)

I could, but not sure I completely understand the full current behavior. Seems like @jekru has a better overview considering the issue and PR.

**Comment by jekru** [comment]
> @UchihaYuki, @andreaslarssen, @jekru: Would any one of you be up to creating a PR that updates docs to more clearly describe the current behavior? 🙏

Yes, I can do that. Do I have to create a new issue to link the PR or can I just use this issue and note that changing the docs will be a quick fix?

**Comment by gkalpak** [comment]
Thx, @jekru :+1:
No need for a new issue. You can reference the discussion in this one.

**Comment by jekru** [comment]
@gkalpak I created a PR, see #45909.
