### ISSUE TITLE
[test] RootTestComponent no longer extends DebugElement

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#4528]
Previously (alpha-37), unit tests could use:

    tcb.createAsync(components.TestCmp)
      .then((rootTC) => {
         rootTC.componentInstance.expression = 'Dynamic text';
      });

Now (alpha-38), `rootTC` is no longer a `DebugElement` but has an attribute `debugElement`, so the test must be written:

    tcb.createAsync(components.TestCmp)
      .then((rootTC) => {
         rootTC.debugElement.componentInstance.expression = 'Dynamic text';
      });

(same thing for accessing `nativeElement`).

That was already a bit verbose, but it is now a bit unreadable, don't you think?
That should also be mentioned in the changelog as a breaking change maybe?

**Comment by IgorMinar** [comment]
this was changed in 787d1f955f4f52be2f47d96111ce0299581a3900

@yjbanov @jteplitz602 was this intentional? the commit message doesn't mention this change at all.

**Comment by IgorMinar** [comment]
marking P1 until we determine if this was intentional...

**Comment by yjbanov** [comment]
Let's check with @mhevery first. He reviewed this change. I'm not aware of the reasons why this was done.

**Comment by IgorMinar** [comment]
I spoke with @mhevery, this was an intentional change needed to hide some internal apis, but it also makes sense. We should not make Components looks like Elements whether they are test components or not.

@yjbanov can you please update the change log and close this issue? thanks!

**Comment by yjbanov** [comment]
Done (https://github.com/angular/angular/commit/5600a95e97fcfc09c803906069f5b1431bcbd414)

**Comment by IgorMinar** [comment]
thanks!

**Comment by cexbrayat** [comment]
@yjbanov @IgorMinar Thanks for considering this issue (and adding it to the changelog).

May I inquire if there is a plan to have a better test API? Because currently, between this and #4573, tests are borderline readable IMHO...

**Comment by IgorMinar** [comment]
Yes, we are in the process of improving the testing apis.

Cc: @juliemr
