### ISSUE TITLE
Add helper method to Router class for clearing outlets 

### ISSUE THREAD

**Issue by leonelvsc** [angular/angular#45296]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

It'll be nice if the router had a helper method for closing any outlet processing the current urlTree and removing the outlet in question.

https://github.com/angular/angular/pull/40272

OutletCloserService created by @atscott 
https://stackblitz.com/edit/close-outlet-from-anywhere

### Proposed solution

`this.router.clearOutlet('secondary')`

### Alternatives considered

Currently if i want to close the outlet i've to pass a navigation command like this

`this.router.navigate([{outlets: {modal: null}}], {relativeTo: this.activatedRoute.root.children[0].firstChild});`

i've to know where the secondary outlet `modal` is activated in the urlTree, this happens because `children[0].firstChild` is a lazy module that adds more routes definitions to the outlet `modal`

if i do 
`this.router.navigate([{outlets: {modal: null}}], {relativeTo: this.activatedRoute});`
it doesn't work, neither 
`this.router.navigate([{outlets: {modal: null}}])`
like docs says https://angular.io/guide/router-tutorial-toh#clear-secondary-routes

**Comment by Solomon40** [comment]
'Releated' has no English meaning. Should it be 'Related' instead? Present in every feature request issue - #45227, #4508
![typo](https://user-images.githubusercontent.com/54350721/157775512-409e7383-fa44-49f5-a02a-a745ce4baffb.jpg)
9
