### ISSUE TITLE
 Can angular support feature components to be compiled separately to support hot-swappable functions，Or is it possible to configure the path of his dependencies somewhere like maven in java

### ISSUE THREAD

**Issue by lee-200** [angular/angular#45294]
### Description

We have special requirements that need to implement hot-swappable functions for angular deployed projects. Can we support separate compilation of feature modules, thanks

### Proposed solution

No

### Alternatives considered

No

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
