### ISSUE TITLE
DevTools not visible on latest chrome

### ISSUE THREAD

**Issue by jeffschulzusc** [angular/angular#45291]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Chrome: Version 99.0.4844.51 (Official Build) (arm64)
Edge: Version 99.0.1150.36 (Official build) (arm64)

After adding Angular Devtools extension to browser, i can not see it as a tab nor in more-tools ...
previously it was added and selectable
I checked that it is enabled chrome://extensions/ and i tried remove and re-add

I pinned the extension and it is visible on the top bar, and turns red when i load localhost app with debug build

### Please provide a link to a minimal reproduction of the bug

Load any angular app with debug build

### Please provide the exception or error you saw

```true
No errors seen
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Mac Monterey 12.2.1 M1


Chrome: Version 99.0.4844.51 (Official Build) (arm64)
Edge: Version 99.0.1150.36 (Official build) (arm64)


Node : 14.18.1
  OS   : darwin x64
  npm  : 6.14.15
  
  nx : 13.3.11
  @nrwl/angular : 13.3.11
  @nrwl/cli : 13.3.11
  @nrwl/cypress : 13.3.11
  @nrwl/devkit : 13.3.11
  @nrwl/eslint-plugin-nx : 13.3.11
  @nrwl/express : undefined
  @nrwl/jest : 13.3.11
  @nrwl/linter : 13.3.11
  @nrwl/nest : 13.3.11
  @nrwl/next : undefined
  @nrwl/node : 13.3.11
  @nrwl/nx-cloud : 13.0.0
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.11
  @nrwl/web : undefined
  @nrwl/workspace : 13.3.11
  @nrwl/storybook : 13.3.11
  @nrwl/gatsby : undefined
  typescript : 4.5.4
  rxjs : 7.5.1
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.1.1
         @angular/cdk: 13.1.1
         @angular/common: 13.1.1
         @angular/compiler: 13.1.1
         @angular/core: 13.1.1
         @angular/forms: 13.1.1
         @angular/material: 13.1.1
         @angular/platform-browser: 13.1.1
         @angular/platform-browser-dynamic: 13.1.1
         @angular/router: 13.1.1
         @ngrx/effects: 12.5.0
         @ngrx/entity: 12.5.0
         @ngrx/router-store: 12.5.0
         @ngrx/schematics: 12.5.0
         @ngrx/store: 12.5.0
         @ngrx/store-devtools: 12.5.0
         @angular-devkit/build-angular: 13.0.4
         @angular/cli: 13.0.4
         @angular/compiler-cli: 13.1.1
         @angular/language-service: 13
```

**Comment by AleksanderBodurri** [comment]
@jeffschulzusc Thank you for opening this issue.

 I am not able to replicate this on my end with a fresh install of chrome Version 99.0.4844.51 (Official Build) (arm64) and a fresh install of Angular DevTools from the [chrome web store](https://chrome.google.com/webstore/detail/angular-devtools/ienfalfjdbdpebioblfackkekamfmbnh).

It's strange that the tab wouldn't appear. The devtools_page for Angular DevTools should be creating the Angular DevTools panel whenever a user opens Chrome DevTools (regardless of whether the current page has an Angular app or not).

Are you able to replicate this issue on other devices?

**Comment by jeffschulzusc** [comment]
hi, thanks for checking on your end ...

i restarted my chrome and now it is showing up there ok ... 
but is still not showing up in edge ... i double-checked that it is installed,enabled,can read all sites,etc...

**Comment by pogopaule** [comment]
same problem here

**Comment by AleksanderBodurri** [comment]
@pogopaule can you share what version of chrome you are using? If possible can you try updating to the latest release and see if that helps.

@jeffschulzusc do you still get this issue on the latest release of microsoft edge (99.0.1150.46)? I'm able to see the Angular tab on my end.

**Comment by pogopaule** [comment]
@AleksanderBodurri I can see the tab now, thanks 👍

**Comment by jeffschulzusc** [comment]
Microsoft Edge
Version 99.0.1150.46 (Official build) (arm64)

macOD Monterey
Version 12.2.1
(Apple chip)

i still have same problem

i did not try any of the insider channel versions

**Comment by AleksanderBodurri** [comment]
@jeffschulzusc just tried it again on Microsoft Edge Version 99.0.1150.52 on the same system specs. If possible, could you do a clean install of Microsoft Edge to see if it resolves the issue?

**Comment by jeffschulzusc** [comment]
yes, after a fresh install of edge i am now able to access angular devtools ...
maybe has something to do with edge updates ... i notice after it automatically updates i seem to lose some of extensions i had installed

**Comment by AleksanderBodurri** [comment]
@jeffschulzusc glad you're able to see it. It's hard to say what was causing the initial issue but I don't think it has anything to do with how Angular DevTools has been implemented. Will close this issue for now
