### ISSUE TITLE
inject(token) within an InjectionToken is not finding a "local" provider

### ISSUE THREAD

**Issue by tjlav5** [angular/angular#45303]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Component provides an injectable "Foobar" but the component is unable to inject an InjectionToken which itself is trying to inject "Foobar".

```ts
@Injectable()
class Foobar {}

const FOOBAR = new InjectionToken('Foobar', {
  factory: () => {
    return inject(Foobar); // This throws an error that Foobar is not found
  },
  providedIn: null, // The docs suggest this is the same as undefined, and should use the local injector
});

@Component({
  selector: 'my-app',
  template: 'Hello',
  providers: [Foobar],
})
export class AppComponent {
  constructor(@Inject(FOOBAR) foobar: Foobar) {
    console.log(foobar);
  }
}
```

I would expect `inject(Foobar)` within the InjectionToken to return the local Foobar provided in this component.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-uxxfsd?file=src/app/app.component.ts

### Please provide the exception or error you saw

```true
Error: R3InjectorError(AppModule)[InjectionToken Foobar -> Foobar -> Foobar -> Foobar]:
NullInjectorError: No provider for Foobar!
```
```


### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 13.2.0
```

**Comment by tjlav5** [comment]
Thanks Joost - perhaps I conflated the providedIn from Injectables and InjectionTokens since they both seem to say: `providedIn?: Type<any> | 'root' | 'platform' | 'any' | null;`, and the docs I'm referring to _do_ belong to [Injectable](https://angular.io/api/core/Injectable#options).

I don't want to turn this into a tutorial so feel free to close if this WAI - but am I surprised that there is no way for an injection token to take into account the local injector.

**Comment by JoostK** [comment]
> perhaps I conflated the providedIn from [Injectable](https://angular.io/api/core/Injectable#options)s and InjectionTokens since they both seem to say: providedIn?: Type<any> | 'root' | 'platform' | 'any' | null;, and the docs I'm referring to do belong to Injectable.

Ah, I see. Indeed, they look similar but are different things, and the behaviour w.r.t. `null`/`undefined` is indeed different between the two.

> I don't want to turn this into a tutorial so feel free to close if this WAI - but am I surprised that there is no way for an injection token to take into account the local injector.

Some technical details if you're interested: the node injector is highly optimized and its providers are registered when a component type is rendered for the first time, and this allocates the necessary space for each provider. Each component instance is then created using this same size to fit exactly the providers that have been registered, so there is no room to provide arbitrary tokens ad-hoc. The module injector tree OTOH stores the tokens and instances in a `Map`, so it's trivial to insert additional instances based on `InjectionToken`s with `providedIn`.

There can also be many "local" injectors in a single component, as each element in the template can act as its own `Injector`.

**Comment by JoostK** [comment]
I'll go ahead and close this, if you have suggestions to improve the docs please feel free to continue the discussion below or open a PR :-)

**Comment by tjlav5** [comment]
Thanks for quick response!
