### ISSUE TITLE
Add how to access the  resolved data of the Resolver

### ISSUE THREAD

**Issue by laggage** [angular/angular#45313]
### Description

It may helps if there are some docs about how to access the resolved data on the [angular.io/router/Resolve](https://angular.io/api/router/Resolve) page

### What is the affected URL?

https://angular.io/api/router/Resolve

**Comment by laggage** [comment]
It may be something like this that can be appened to the [usage-notes](https://angular.io/api/router/Resolve#usage-notes) section

> To access the resolved data, you can inject `ActivatedRoute` to the component or service
> 
> ```ts
> export class ExampleComponent implements OnInit {
>     construct(private activatedRoute: ActivatedRoute) {}
> 
>     ngOnInit() {
>         // resolved data
>         const childData = this.activatedRoute.snapshot.data.childData;
>     }
> }
> ```

**Comment by AlirezaEbrahimkhani** [comment]
Hi @pkozlowski-opensource 
Please assign me to this issue i could try to add docs for it if you don't mind.
