### ISSUE TITLE
Polymer _zone error in alpha 38

### ISSUE THREAD

**Issue by Zyzle** [angular/angular#4531]
After upgrading to alpha 38 it seems Polymer no longer wants to play nice with ng2.

```
Uncaught TypeError: Cannot read property '_zone$addEventListener' of undefined
  n.addEventListener @ angular2.min.js:1
  e.addEventListener @ angular2.min.js:1
  (anonymous function) @ polymer-micro.html:14
  (anonymous function) @ polymer-micro.html:22
```

I'm not really sure what the root source of this error is so the best I can do is supply a plunkr that worked in alpha 37 but breaks in 38

* 37 Working: http://plnkr.co/edit/OYBXYz?p=preview
* 38 Error: http://plnkr.co/edit/jIL2uS?p=preview

**Comment by IgorMinar** [comment]
@vicb can you own this? please look into it today and determine if we must fix this in a39 (due tomorrow/wed). On the surface this looks serious enough that it should be in 39.

**Comment by vicb** [comment]
Not sure if I can find time to look at this today. If not, I'll check it first thing tomorrow.

**Comment by vicb** [comment]
The pb is in `var target = isWebWorker() && !this ? self : this;` which returns undefined while it should return the `window` when Polymer does `addEventListener('WebComponentsReady', resolve);`

I'll try to come with a fix ASAP

**Comment by IgorMinar** [comment]
thanks!

**Comment by vicb** [comment]
@Zyzle Thanks for the bug report, zone.js has been fixed. The next angular release will include this fix.

**Comment by Zyzle** [comment]
@vicb thanks! :+1:
