### ISSUE TITLE
Tour of Heroes Docs: Missing CSS Styles in src/styles.css

### ISSUE THREAD

**Issue by lee-cooper** [angular/angular#45328]
### Description

Tour of Heroes (TOH) Part 0 is missing button styles in `src/styles.css`. As a result, when developers go through the TOH, button CSS styles that are present in the live examples in src/styles.css are not present in the code snippets at the end of the lesson. This is most apparent in [TOH part-2](https://angular.io/tutorial/toh-pt2), where a list of buttons are shown without the expected styles.

### What is the affected URL?

https://angular.io/tutorial/toh-pt0

### Please provide the steps to reproduce the issue

1. Create new project in TOH Part 0 and apply code snippets to project
2. Follow steps in TOH part 1 and apply code snippets
3. Follow steps in TOH part 2 and apply code snippets
4. View output project styling for heroes.component.html without the expected button styling

Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-3vttek?file=src%2Fstyles.css

### Please provide the expected behavior vs the actual behavior you encountered

**Expected**: heroes.component.html will have expected button styles applied as seen in the [live example ](https://stackblitz.com/run?file=src/app/heroes/heroes.component.html)for TOH part 2
**Actual**: heroes.component.html does not have button styles applied.

### Please provide a screenshot if possible

Actual
<img width="331" alt="TOH-p2-button-styles-actual" src="https://user-images.githubusercontent.com/20045743/157781153-7268ae58-6ac6-4110-a9a8-a2420ce76340.png">

Expected
<img width="331" alt="TOH-p2-button-styles-expected" src="https://user-images.githubusercontent.com/20045743/157781181-0bdf8ea3-80aa-45a2-a935-1bcaf9f953f2.png">

### Please provide the exception or error you saw

```true
N/A
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
N/A
```

**Comment by geromegrignon** [comment]
There is already a dedicated section in TOH part 2 explaining how to add styles after adding buttons: https://angular.io/tutorial/toh-pt2#style-the-heroes

**Comment by lee-cooper** [comment]
@geromegrignon It explains how to add, but not what to add. Giving a code snippet provides an example for this section and reinforces differences between component-styles and global-styles. 

I'd be happy to update this issue to instead suggest a code snippet addition to the Final code review in TOH part 2, rather than TOH part 0, since that flows better with the rest of the documentation.

**Comment by geromegrignon** [comment]
The `what to add ` is in the last part of the section (with related explanation about component vs global styles):

```
Open the heroes.component.css file and paste in the private CSS styles for the HeroesComponent. You'll find them in the [final code review](https://angular.io/tutorial/toh-pt2#final-code-review) at the bottom of this guide.
```

About:

```
I'd be happy to update this issue to instead suggest a code snippet addition to the Final code review in TOH part 2
```

The code snippet is already in the final code review part 2

**Comment by geromegrignon** [comment]
Oh, i see sorry, I thought it was about button styles from the component not being featured in part 2.

Then I would be in favor of fixing it in part 0 as such styles are details beginners shouldn't have to care about to focus on Angular framework itself for this tutorial.

**Comment by lee-cooper** [comment]
No worries friend, I could have explained it better.

And agreed 👍🏻
