### ISSUE TITLE
RouterLink should add a class "router-link" to HTML

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#4532]
Given the following template, I can assign a class for the active route because `router-link-active` is added by Angular2 to the element. But I cannot style the inactive router links. For now, I can add my own `router-link` class to each element. 

here is what I currently do ..

```
    <a [router-link]="['/${Routes.dashboard.as}']" class="router-link">Dashboard</a>
    <a [router-link]="['/${Routes.heroes.as}']" class="router-link">Heroes</a>
    <router-outlet></router-outlet>
```

and the CSS
```
    .router-link {padding: 5px;text-decoration: none;}
    .router-link:visited {color: #444;}
    .router-link.router-link-active {color: white; background-color: #52b9e9; text-decoration: none;}
```

I propose that Angular2 add `router-link` to all router link elements and additionally add  `router-link-active` to the active one. This way i could just do this:

```
    <a [router-link]="['/${Routes.dashboard.as}']">Dashboard</a>
    <a [router-link]="['/${Routes.heroes.as}']">Heroes</a>
    <router-outlet></router-outlet>
```

cc / @btford

**Comment by thelgevold** [comment]
This might not be exactly what you want, but I have been using [class.active] in my samples since it gives me an active class for the active route based on a boolean check. 
Here is an example of how I do it:
http://www.syntaxsuccess.com/viewarticle/routing-in-angular-2.0
Maybe I should wrap this in a directive though to hide the url being passed into the function.

**Comment by PascalPrecht** [comment]
@johnpapa maybe I'm getting it wrong but after all you just want to style a
list of links, and the ones that are active, differently. No matter if they
are Angular 2 router-links or not right? Couldn't you just use a parent CSS
selector, or as you already do, introduce your own class for each link if
needed?

Thing is that every router-link that is not active is inactive. It's
basically the default anyways. And unless you want to make your links that
are router-links look exactly the same in your entire application (which I
doubt you do), you don't need to add extra classes to provide this
information as all router-links can be considered "inactive" by default.

**Comment by johnpapa** [comment]
Yes I can do it by applying to all anchors.  But then that's too broad. Or by a container class or element that contains the anchors. There are ways by adding our own classes. The code generated by router link does not supply any attributes or way to identify the elements. So we can use hierarchical parent child ones or ass one to each anchor. 

I just thought it made sense that if we are adding a active class we could add a regular one too.

**Comment by PascalPrecht** [comment]
I'm not sure if it's common to style all links that are router links the
same way. Actually we shouldn't even know in CSS that those links are
upgraded with router-link.

router-link-active Also should rather allow to add CSS classes defined by
the user. Because you never know if those will conflict with the
surrounding CSS.

I would down vote here. If you want to style a list of links you rather
define those in a context of a CSS module. And it shouldn't matter how
those links are generated. If you happen to remove the router-link
directive because for some reason you have to navigate imperatively, your
CSS won't work anymore.

**Comment by thelgevold** [comment]
@johnpapa @PascalPrecht 
I guess it would be ok to add both an active and an inactive class, but in both cases it relates to just the anchor tag. I find that I typically add my styles to the element around the anchor (often an li element)
That's where I find the [class.active] approach to be desirable since it's decoupled from the anchor tag.

**Comment by evanplaice** [comment]
@thelgevold I was stuck on this for a bit until I stumbled onto your demo app. I'm using Semantic UI which has built-in definitions for 'active' so your approach worked perfectly.

The documentation for using angular2 with ES6/7 syntax is a bit spotty so I had some trouble figuring out how to DI. Once I figured that out, adapting your code was really simple.

*header.html*
```html
<a [class.active]="getLinkStyle('/thoughts')" class="item" [routerLink]="['/Thoughts']">Thoughts</a>
<a [class.active]="getLinkStyle('/designs')" class="item" [routerLink]="['/Designs']">Designs</a>
<a [class.active]="getLinkStyle('/projects')" class="item" [routerLink]="['/Projects']">Projects</a>
<a [class.active]="getLinkStyle('/vitae')" class="item" [routerLink]="['/Vitae']">Vitae</a>
```
*Source: https://github.com/evanplaice/evanplaice.com/blob/master/app/components/header/header.html*

*header.js*
```javascript
...
// Location is required to match the route path
import { ROUTER_DIRECTIVES, Location } from 'angular2/router';
...
export class HeaderComponent {
  // required for ES7 dependency injection
  // equivalent to a Typescript typed variable declaration
  static get parameters() {
    return [[Location]];
  }

  // bind location to the component
  constructor(location) {
    this.location = location;
  }

  // true on a path match, false for the rest
  getLinkStyle(path) {
    return this.location.path().indexOf(path) > -1;
  }
```
*Source: https://github.com/evanplaice/evanplaice.com/blob/master/app/components/header/header.js*

@johnpapa For your specific use case, I think it makes a lot more sense to wrap the links with a parent element. Then select the children of that parent element to set the default (ie non-active) styles. For example...

*html*
```html
<nav>
    <a [router-link]="['/${Routes.dashboard.as}']">Dashboard</a>
    <a [router-link]="['/${Routes.heroes.as}']">Heroes</a>
</nav>
<router-outlet></router-outlet>
```

*css*
```css
nav > a { padding: 5px;text-decoration: none; }
nav > a:visited { color: #444; }
.router-link-active { color: white; background-color: #52b9e9; text-decoration: none; }
```

Alternatively, you could also use my first approach, reverse the logic on `getLinkStyle()` and change `[class.active]` => `[class.router-link]`. 

IMHO, adding a `router-link` class to everything that isn't active doesn't make much sense.

**Comment by vsavkin** [comment]
1. I am not sure how common it is to style all router-aware a tags in the same way. If it is the case for a particular application, you can always define your own platform directive with the `[routerLink]` selector. That directive can add the desired class.

2. The new router has the RouterLinkActive directive that allows the developer to set the class on the link itself or on its parent. This is different from how the deprecated router works. And I'm not sure if adding the "router-link" class is meaningful in this new arrangement.

So I'm closing this issue. If you think the issue makes sense in the context of the new router and RouterLinkActive, please reopen it.
