### ISSUE TITLE
Lazy Loaded Component template file not recognizing imported modules

### ISSUE THREAD

**Issue by sskasim** [angular/angular#45324]
### Which @angular/* package(s) are the source of the bug?

language-service

### Is this a regression?

Yes

### Description

I am using VS Code as my IDE and I have a lazy loaded component with the NgModule at the bottom of the .ts file that has various imports for Angular Material modules that the component needs. But the template file (html) for this lazy loaded component is showing all kinds of errors (such as below) in the editor as well as the PROBLEMS tab in the terminal section below. (Although, the application is compiling and running fine. Also, this started happening couple of weeks ago.)

ERRORS:
---------

Can't bind to 'ngClass' since it isn't a known property of 'div'.

'mat-toolbar' is not a known element:
1. If 'mat-toolbar' is an Angular component, then verify that it is part of this module.
2. If 'mat-toolbar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

'mat-icon' is not a known element:
1. If 'mat-icon' is an Angular component, then verify that it is part of this module.
2. If 'mat-icon' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

### Please provide the exception or error you saw

```true
ERRORS:
---------

Can't bind to 'ngClass' since it isn't a known property of 'div'.

'mat-toolbar' is not a known element:
1. If 'mat-toolbar' is an Angular component, then verify that it is part of this module.
2. If 'mat-toolbar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

'mat-icon' is not a known element:
1. If 'mat-icon' is an Angular component, then verify that it is part of this module.
2. If 'mat-icon' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.5
Node: 14.19.0
Package Manager: npm 6.14.16
OS: win32 x64

Angular: 13.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.5
@angular-devkit/build-angular   13.2.5
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
@angular/cdk                    13.2.5
@angular/cli                    13.2.5
@angular/flex-layout            12.0.0-beta.34
@angular/material               13.2.5
@schematics/angular             13.2.5
rxjs                            7.5.5
typescript                      4.5.5
```

**Comment by alxhub** [comment]
Hello @sskasim,

Without an example project (likely in the form of a Github repository) that illustrates this problem, it's unlikely we'll be able to be of much assistance here. Can you please upload such a project? It should be as minimal as possible to make debugging easier.

**Comment by sskasim** [comment]
Okay, I will try. Will need time. Thanks

**Comment by sskasim** [comment]
Hi @alxhub,
I have uploaded a sample at [github](https://github.com/sskasim/ng-lang-svc-bug)
After you npm install 
and run the app, click the "Load Lazy Loaded ..." button at the top and it will tell you which file the issue is in the VS Code IDE

Environment for the sample:
Angular CLI: 13.2.4
Node: 14.19.0
Package Manager: npm 6.14.16
OS: win32 x64

Angular: <error>
... animations, cdk, common, compiler, compiler-cli, core
... flex-layout, forms, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.4 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            13.2.4 (cli-only)
@angular-devkit/schematics      13.2.4 (cli-only)
@angular/cli                    13.2.4 (cli-only)
@schematics/angular             13.2.4 (cli-only)
rxjs                            6.6.7 (cli-only)
typescript                      4.5.5 (cli-only)

**Comment by alxhub** [comment]
Hi @sskasim,

Looking through the repro code, I don't see a few things that might be important:

* there's no `tsconfig.json`, so there's no way to actually build the project
* parts of the AppComponent are missing (which might include things like the route configuration)

**Comment by alxhub** [comment]
A tsconfig defines the compilation, especially for the editor and the Language Service.

I suspect what's going on in your case is that your lazily loaded component isn't referenced anywhere, and your tsconfig is defined such that it doesn't end up getting included in the TypeScript project that our Language Service is using to understand your code. Having an application with all of the references in place and a tsconfig which defines the project is _essential_ to diagnosing this issue.

**Comment by jessicajaniuk** [comment]
I'm sorry but we can't reproduce the problem you are reporting. We require that reported issues have a minimal reproduction that showcases the problem.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template that include info on how to create a reproduction using our template.
