### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by christinanguyen332** [angular/angular#45337]
### Description

On the following posts:
https://angular.cn/guide/testing
https://v10.angular.cn/guide/testing

this is broken on both:
https://circleci.com/add-projects

### What is the affected URL?

https://angular.cn/guide/testing

### Please provide the steps to reproduce the issue

This is a broken link:
https://circleci.com/add-projects

### Please provide the expected behavior vs the actual behavior you encountered

Please update with the following:
https://circleci.com/docs/2.0/projects/

**Comment by Nutza974** [comment]
Reply

ในวันที่ อา. 13 มี.ค. 2022 05:04 น. christinanguyen332 <
***@***.***> เขียนว่า:

**Comment by geromegrignon** [comment]
Hi @christinanguyen332,

Localized documentation is a community effort.
Please move your issue to the dedicated repository: https://github.com/angular/angular-cn

**Comment by christinanguyen332** [comment]
Gerome,

I have no idea how to move my issue too the dedicated repo:
https://github.com/angular/angular-cn
<https://urldefense.com/v3/__https://github.com/angular/angular-cn__;!!Nhk69END!JbPVA3Iv13eKVAb65gWwzouTrJoVTseVAYksnWaKkCv222T5xz_0lsjPvN-fCxxeMzWxYw$>

Can you help?

Thanks,
Christina

Christina Nguyen | Program Manager

she/her

***@***.***

**Comment by geromegrignon** [comment]
Hi, there is no built-in solution for you to transfer this issue.
You'll need to create a new issue in the angular-cn repository.
