### ISSUE TITLE
Use generic type on FormGroup class to support [formControl] directive in strict templates

### ISSUE THREAD

**Issue by alshdavid** [angular/angular#45331]
### Which @angular/* package(s) are relevant/releated to the feature request?

@angular/forms

### Description

Currently when targeting a `FormControl` embedded within a `FormGoup` via the `[formGroup]` directive, we have this issue on `<input />` elements 

![image](https://user-images.githubusercontent.com/12656294/157986211-a743cae4-2668-4fe2-bd7b-8bf86f7b3746.png)

### Proposed solution

This can be solved by using a type constraint generic type on the `FormGroup` class:

```typescript
export declare class FormGroup<T extends Record<string, AbstractControl> = {}> extends AbstractControl {
    controls: T;
    /**
     * Creates a new `FormGroup` instance.
```

### Alternatives considered

> Use the `formControlName` directive

I prefer programmatic solutions

> Separate the `FormControl` from the `FormGroup` and reference them directly

This is a solution but it's a but ugly and repetitive

**Comment by JoostK** [comment]
Please have a look at the [typed forms RFC](https://github.com/angular/angular/discussions/44513), which is currently being implemented.
