### ISSUE TITLE
Broken link (2)

### ISSUE THREAD

**Issue by christinanguyen332** [angular/angular#45338]
### Description

There is a broken link on the following page.

### What is the affected URL?

https://v10.angular.cn/guide/testing

### Please provide the steps to reproduce the issue

This is a broken link:
https://circleci.com/add-projects

### Please provide the expected behavior vs the actual behavior you encountered

Please update to:
https://circleci.com/docs/2.0/projects/

**Comment by Nutza974** [comment]
Reply

ในวันที่ อา. 13 มี.ค. 2022 05:06 น. christinanguyen332 <
***@***.***> เขียนว่า:

**Comment by geromegrignon** [comment]
Hi @christinanguyen332,

Localized documentation is a community effort.
Please move your issue to the dedicated repository: https://github.com/angular/angular-cn
