### ISSUE TITLE
Allow to wrap Angular Decorators such as NgModule for preconfiguration and the creation of TestingModules

### ISSUE THREAD

**Issue by centigrade-julian-lang** [angular/angular#45333]
### Which @angular/* package(s) are relevant/releated to the feature request?

core

### Description

With Angular 13 it is currently not possible to wrap the `NgModule` to allow for a common pattern, where some of the declarations are exported, and others are internal:

~~~ts
import { NgModule } from '@angular/core';

export function FeatureModule(moduleConfig: FeatureObj) {
  const publicDeclarations = moduleConfig.public ?? [];
  const internalDeclarations = moduleConfig.internal ?? [];
  const exports = moduleConfig.exports ?? [];

  return NgModule({
    ...moduleConfig,
    declarations: [...publicDeclarations, ...internalDeclarations],
    exports: [...publicDeclarations, ...exports],
  });
}

// use it somewhere else:
@FeatureModule({
  imports: [CommonModule],
  public: [SomeComponentToExport],
  internal: [SomeDeclarationOnly]
})
export class MyFeatureModule {}
~~~

This might not be a huge benefit at first glance, but for a library having a whole lot of these kinds of Modules, it would be great to be allowed writing it that way.

In the current version this breaks with the error: `error NG6002: Appears in the NgModule.imports of XguideModule, but could not be resolved to an NgModule class. Is it missing an @NgModule annotation?`

## Testing Modules

The second use case is more like a workaround, but I used it to create TestingModules like this:

~~~ts
// decorators.ts
import { NgModule } from '@angular/core';

export const NgTestingModule = NgModule;

// some-module.ts
@NgModule({ 
   declarations: [SomeComponent],
   providers: [SomeService]
})
export class SomeModule {}

@NgTestingModule({
   // would break when also using NgModule because "SomeComponent appears in more than one module"
  declarations: [SomeComponent],
  providers: [SomeTestingService]
})
export class SomeTestingModule
~~~

Am I missing something or is this approach considered bad practice?

### Proposed solution

Allow Ng* decorators to be wrapped like shown above and do not throw error `error NG6002: Appears in the NgModule.imports of XguideModule, but could not be resolved to an NgModule class.`

### Alternatives considered

Did not find anything else that might work as well.

I tested something like this:

~~~ts
export function featureConfig(moduleConfig: NgModule) {
  return {
     ...moduleConfig,
    declarations: [...publicDeclarations, ...internalDeclarations],
    exports: [...publicDeclarations, ...exports],
  };
}

// some feature module
@NgModule(featureConfig({ /* ... */}))
export class SomeFeatureModule {}
~~~

But this throws the error that the config must be a object literal

**Comment by JoostK** [comment]
This isn't feasible for the AOT compiler. It needs to statically analyze code to detect the decorators and convert them into precompiled definitions for the runtime to execute. Hiding the metadata behind a different decorator means that certain properties are no longer within the same lexical scope, meaning that the runtime definition cannot refer to the same properties. This is also why your example with `featureConfig` is not accepted; the function's lexical scope is not available in  scope of the AOT compiled definition.

**Comment by JulianLang** [comment]
Thanks for the clarification! Could you give me some hints on how to do testing modules properly then? My workaround that apparently worked until angular 13 was the only way I got it to work unfortunately :/
