### ISSUE TITLE
Can we have a disposable TestBed?

### ISSUE THREAD

**Issue by alshdavid** [angular/angular#45359]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

When writing tests I like to setup/teardown an environment between every test. This ensures my tests are not dependant on any sort of global state that could render my tests brittle and that the dependencies going into the test are what I expect them to be.

The second point is particularly painful as sometimes it can be unclear what is being provided to a component via the dependency injection framework. 

Current usage of TestBed requires us to `TestBed.configureTestingModule` which is a shared global state used between test blocks. 

It would be great if TestBed offered the ability to setup/teardown against a specified target `Window`, and provided an object to interact with, allowing us to create a new injector for each test block.

This would add versatility to how Angular could be tested, Jest in Node or Karma in browser, all you would just need to do is provide the test module bootstrapper an appropriate `Window` target where a module would construct around that.

### Proposed solution

Add the following methods to the `TestBed` interface

```typescript
interface TestBed {
  platformTestingDynamic(options: { windowRef?: any }): TestPlatformRef
}
```
So given a simple component like this:

```typescript
@Component({
  selector: 'app-root',
  template: `<h1>{{ title }}</h1>`
})
export class AppComponent {
  constructor(
    @Inject('titleProvider') public title: string
  ) {}
}
```

I could then write a test suite that, at the start of each test will construct the module, render the template and tear it down such that there is no global state (except the document, which I can also choose to bootstrap/teardown if I wanted).

Further I could reference a local `windowRef` or a global `Window` - so when running in a browser I would be able to use a real window, however when running in node I could use a substitution like JSDOM.
 
```typescript
import { TestBed } from '@angular/core/testing'
import JSDOM from 'jsdom'
import { AppComponent } from './app.component'

const html = `<!DOCTYPE html><body></body>` 
const { window: windowRef, document: documentRef } = new JSDOM(html);

const MOCK_TITLE = 'MOCK_TITLE'

describe('AppComponent', () => {
  let testPlatformRef: TestPlatformRef
  let testModuleRef: TestNgModuleRef

  beforeEach(async () => {
    // Create outlet for application
    documentRef.body.appendChild(documentRef.createElement('app-root'))

    // Construct around my specified Window reference
    testPlatformRef = TestBed.platformTestingDynamic({ windowRef })

    // Bootstrap a test module
    testModuleRef = testPlatformRef.bootstrapModule({
      declarations: [AppComponent],
      providers: [
        { provide: 'titleProvider', useValue: MOCK_TITLE }
      ]
    })

    // Bootstrap component and wait for stable
    await testModuleRef.bootstrapComponent(AppComponent)
  })

  afterEach(() => {
    testPlatformRef.destroy()
    // This will automatically delete the `app-root` element 
    testModuleRef.destroy()
  })

  it('Should render title', () => {
    expect(documentRef.querySelector('h1').innerHTML).toBe(MOCK_TITLE)
  })
})

```

### Alternatives considered

Just use the global state offered by TestBed like everyone else

**Comment by crisbeto** [comment]
Have you tried the `teardown` option in `configureTestingModule`?

**Comment by alxhub** [comment]
Also, `TestBed` has `initTestEnvironment` and `resetTestEnvironment` which I believe do exactly this.
