### ISSUE TITLE
TestBed to prefer components from the declarations array if same component is already declared on an imported module

### ISSUE THREAD

**Issue by marcioggs** [angular/angular#45362]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

On the TestBed, if a service is declared on both a module in the `imports` array and directly in the `providers` array, the one on the `providers` array will be used, which facilitates mocking services.

This same behavior is not observed on components that are both imported on a module in the `imports` array and on the `declarations` array, as can be verified by running the test below.

```ts
import { Component, NgModule } from '@angular/core';
import { ComponentFixture, TestBed } from '@angular/core/testing';

@Component({
  selector: 'app-parent-component',
  template: '<app-child-component></app-child-component>',
})
class RealParentComponent {}

@Component({
  selector: 'app-child-component',
  template: '<p>Real child component</p>',
})
class RealChildComponent {}

@Component({
  selector: 'app-child-component',
  template: '<p>Mocked child component</p>',
})
class MockedChildComponent {}

@NgModule({
  declarations: [RealParentComponent, RealChildComponent],
})
export class RealModule {}

fdescribe('RealParentComponent', () => {
  it('should use mocked component instead of real component', async () => {
    TestBed.configureTestingModule({
      imports: [RealModule],
      declarations: [MockedChildComponent],
    });

    const fixture: ComponentFixture<RealParentComponent> = TestBed.createComponent(RealParentComponent);

    expect(fixture.nativeElement.querySelector('p').textContent).not.toEqual('Real child component'); // Error: Expected 'Real child component' not to equal 'Real child component'.
    expect(fixture.nativeElement.querySelector('p').textContent).toEqual('Mocked child component'); // Expected 'Real child component' to equal 'Mocked child component'.
  });
});
```

This is especially useful when you want to isolate tests and the dependent component depends on other components/services and you want to avoid having to mock this chain of dependencies.

### Proposed solution

TestBed to ignore components declared on an imported module if there's an equivalent component on the `declarations` array.
An equivalent component would be one that has the same `selector` attribute in the `@Component` decorator.

### Alternatives considered

Create a specific module to be used only on the tests without the real component and including the mocked component.

**Comment by atscott** [comment]
This is working as intended. There's nothing special about the TestBed providers here. Overriding a provider token is possible in all modules, but you cannot override components/directives. The TestingModule created by TestBed works the same way. What you're looking for to override the component is [TestBed.overrideComponent](https://angular.io/api/core/testing/TestBed#overrideComponent).

**Comment by marcioggs** [comment]
Thanks, @atscott .

Test passes if the TestBed declaration is changed to:
```ts
    TestBed.configureTestingModule({
      imports: [RealModule],
    }).overrideComponent(RealChildComponent, {
      set: { selector: 'app-child-component', template: '<p>Mocked child component</p>' },
    });
    //.overrideComponent(RealChildComponent, MockedChildComponent); // Does not compile
    //.overrideComponent(RealChildComponent, new MockedChildComponent()); // Does not replace object
```

If anyone knows how extract at runtime a [MetadataOverride](https://angular.io/api/core/testing/MetadataOverride) from a Component, please let me know.

For anyone searching for more info about `overrideComponent`, tests can be found here:
https://github.com/angular/angular/blob/master/packages/platform-browser/test/testing_public_spec.ts
