### ISSUE TITLE
ngFor local variable is not accessible inside same element

### ISSUE THREAD

**Issue by ChellappanRajan** [angular/angular#45373]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

ngFor local variable is not accessible inside same element

**component.ts**

```
list = [
  { id: 0, name: 'Demo' },
  { id: 1, name: 'Demo1' },
  { id: 2, name: 'Demo2' },
];
```

**component.html**

```
<ul *ngFor="let item of list; key: item.id;">
</ul>
```

I am trying to pass local variable item.id value to key directive but it's throwing item does not exist error.

![image](https://user-images.githubusercontent.com/22997191/158773032-9317935f-cd82-449c-931e-be24f053d097.png)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-xsmnyn?file=src/app/key.directive.ts

**Comment by JoostK** [comment]
This is expected; the microsyntax expression of a structure directive is an _input_ to that directive (and other directives can also bind to those inputs if desired, like you're doing in the example). There is no template context at this point, so `item` is not within scope of this expression.
