### ISSUE TITLE
Elements using custom type incorrectly treated as <any> when strictTemplates are OFF

### ISSUE THREAD

**Issue by mcalmus** [angular/angular#45370]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler

### Is this a regression?

No

### Description

I have a simple custom type in the class and iterate over them in the template. When compiled using strictTemplates this works fine, but with that turned off which should be more lenient it gives errors indicating the types are `any`.

The same errors occur using Angular 13.

Sample project attached.

### Please provide the exception or error you saw

```true
Error: src/app/app.component.html:17:28 - error TS7053: Element implicitly has an 'any' type because expression of type 'any' can't be used to index type 'numberFoo'.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.2.16
Node: 14.16.0
Package Manager: npm 8.5.4
OS: darwin x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1202.16 (cli-only)
@angular-devkit/core         12.2.16 (cli-only)
@angular-devkit/schematics   12.2.16 (cli-only)
@schematics/angular          12.2.16 (cli-only)
```

**Comment by mcalmus** [comment]
[test-angular.tar.gz](https://github.com/angular/angular/files/8271438/test-angular.tar.gz)

**Comment by JoostK** [comment]
That repro seems incorrect; it doesn't build without updating TypeScript and then it builds fine, even after disabling `strictTemplates`. Could you please provide a repro?

**Comment by mcalmus** [comment]
I have updated the typescript dependency. The intent of the test case is that it will not compile as included, but adding `"strictTemplates": true` makes it compile successfully/

[test-angular2.tar.gz](https://github.com/angular/angular/files/8311209/test-angular2.tar.gz)

**Comment by JoostK** [comment]
Ah, that repro includes a lot more code to actually reproduce the issue (all of `FOO`/`BAR` stuff was not present in the first archive).

This is an interesting case, and one could argue that the error is correct but maybe a bit unfortunate. Without `strictTemplates` we don't infer types of embedded view contexts, meaning that `f` in the `ngFor` directive ends up being of type `any`. Under `noImplicitAny` would TS then report TS7053 for the indexed access, as the resulting type of that indexed access would also be `any`, which is disallowed under `noImplicitAny`.

The TypeScript error can be suppressed wholesale using the `suppressImplicitAnyIndexErrors` TS compiler option. That also affects the rest of your code though, so may be a bit undesirable. An alternative is to cast the index type to match the index signature, such that the indexed access itself also won't become `any`:

```ts
  castToFooType(v: any): FOO_TYPE {
    return v;
  }

  // total[castToFooType(f)]
```

Theoretically, the Angular type-checker could suppress TS7053 when `strictTemplates` is disabled (which has to take into account some more specific `strict*` flags are well), but I'm not convinced this would be the right thing to do as there are counterexamples where the error is correct, for example:

```ts
  getIndex(): any {
    return 1;
  }

  // {{ indexType[getIndex()] }}
```

An alternative could be to make `$any(total[f])` suppress the error, as it essentially makes the `any` explicit (this doesn't work today, unfortunately).

**Comment by alxhub** [comment]
As @JoostK's analysis shows, this is an interaction between `strictTemplates: false` and `noImplicitAny`. I don't think we're going to make any changes to the non-`strictTemplates` mode at this point - it mainly only exists for compatibility and `strictTemplates` has been the default in Angular for years now. At some point soon we'll probably deprecate the old mode(s) entirely.
