### ISSUE TITLE
A mixin that extends a decorated, Angular class will not leave an *.d.ts artifact in the dist folder.

### ISSUE THREAD

**Issue by gstatenii** [angular/angular#45382]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

When I use a Mixin that extends a decorated, abstract class, in a library, the Mixin is never exported to the dist folder.

This works in an Angular application but not in a library.

For example, both of the attached files will transpile to the dist folder for an application project, but only service-one-mixin.d.ts will make its way to the dist folder for a library project.

In versions before 10.0, we did not need decorations and this mixins of classes that used angular features could be transpiled and written to the dist folder.

[service-mixins.zip](https://github.com/angular/angular/files/8288403/service-mixins.zip).

### Please provide the exception or error you saw

```true
No error, just no *.d.ts file in the dist folder.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular Cli 12.2.13
Node: 14.18.0
Package Manager: npm 6.14.5
OS: Windows Server 2016

"@angular/animations": "12.2.13",
"@angular/cdk": "12.2.13",
"@angular/common": "12.2.13",
"@angular/compiler": "12.2.13",
"@angular/core": "12.2.13",
"@angular/forms": "12.2.13",
"@angular/platform-browser": "12.2.13",
"@angular/platform-browser-dynamic": "12.2.13",
"@angular/router": "12.2.13",
```

**Comment by JoostK** [comment]
Can you share a runnable repro? The two files alone don't tell me much.

I'd suspect this is TypeScript behaviour, as Angular itself is not concerned with `.d.ts` emit.

**Comment by gstatenii** [comment]
Hi JoostK,

Here is a project that builds.  I hade to set SkipLibCheck to true in order for the entire project to build, so that you can see one mixin is there but the other is not.

Thank you for looking at this.

[soccs-web-libraries.zip](https://github.com/angular/angular/files/8290641/soccs-web-libraries.zip)
.

**Comment by JoostK** [comment]
This looks like an ng-packagr bug on first glance; when I manually run `tsc` against the `tsconfig.lib.json` there's quite a few errors, in particular:

```
projects/core-container/src/lib/feature-c/mixins/service-two-mixin.ts:25:14 - error TS4094: Property 'initializeAll' of exported class expression may not be private or protected.

25 export const MixUpADecoratedOne = <T extends Constructor<AbstractTextClass>>(base: T) => {
                ~~~~~~~~~~~~~~~~~~

projects/core-container/src/lib/feature-c/mixins/service-two-mixin.ts:25:14 - error TS4094: Property 'preInitialize' of exported class expression may not be private or protected.

25 export const MixUpADecoratedOne = <T extends Constructor<AbstractTextClass>>(base: T) => {
                ~~~~~~~~~~~~~~~~~~


Found 2 errors.
```

(these occur only after fixing some other errors and enabling `"declaration": true` as a compiler option, which ng-packagr does automatically when deriving an appropriate tsconfig file)

I don't have time right now to look into this further, but the above error explains why the `.d.ts` file is missing. These errors should be shown during the library compilation, so there is some bug there.

**Comment by gstatenii** [comment]
That's it!!!!  When I make the methods public, the file compiles and exports.

But, why @angular-devkit/build-angular:ng-packagr so different from @angular-devkit/build-angular:browser?

In an application, mixins behave exactly as they should, with protected or private methods properties.  Perhaps disallowing protected or private is a library, specific rule. 

Thanks for your discovery.

Are there configurations for ng-packagr that can change this behavior?

**Comment by gstatenii** [comment]
The *.d.ts is an interface file, so naturally, we want only public methods and properties.

And I thought I could, easily, take the core pieces of my application and make a library from them.

Well I, now, know I still can, with a few changes.

**Comment by gstatenii** [comment]
Thanks for the help, Joost!!!
