### ISSUE TITLE
Error injecting elementRef

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#4538]
In alpha.38 I get an error when trying to inject elementRef.

This used to work in previous versions, so I am wondering if the API has changed:

I get the following error:
EXCEPTION: Cannot resolve all parameters for JqueryIntegration(?). Make sure they all have valid type or annotations. in [null]
angular2.js:18606 EXCEPTION: Cannot resolve all parameters for JqueryIntegration(?). Make sure they all have valid type or annotations. in [null]BrowserDomAdapter.logError @ angular2.js:18606BrowserDomAdapter.logGroup @ angular2.js:18617ExceptionHandler.call @ angular2.js:4259(anonymous function) @ angular2.js:19287NgZone._onError @ angular2.js:11859errorHandling.onError @ angular2.js:11778run @ angular2.js:123(anonymous function) @ angular2.js:11799NgZone.run @ angular2.js:11755outsideHandler @ angular2.js:17875run @ angular2.js:120zoneBoundFn @ angular2.js:93
angular2.js:18606 ORIGINAL EXCEPTION: Cannot resolve all parameters for JqueryIntegration(?). Make sure they all have valid type or annotations.

Sample code bellow:
```
import {Component, View, ElementRef} from 'angular2/angular2';

declare var jQuery:any;

@Component({
    selector: 'jquery-integration'
})

@View({
    templateUrl: './components/jquery-integration/jquery-integration.html'
})

export class JqueryIntegration {
    elementRef: ElementRef;

    constructor(elementRef: ElementRef) {
        this.elementRef = elementRef;
    }

    onInit() {
        jQuery(this.elementRef.nativeElement).draggable({containment:'#draggable-parent'});
    }
}
```

**Comment by ericmartinezr** [comment]
@thelgevold see this https://github.com/angular/angular/issues/4497

**Comment by thelgevold** [comment]
@ericmartinezr Thanks!

**Comment by naomiblack** [comment]
closing as dup of https://github.com/angular/angular/issues/4497
