### ISSUE TITLE
title service doesn't work in SSR when the module is lazy loaded

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular#45388]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

No

### Description

when you load a module normally, title service works fine in SSR, and the source code updated with the new title
```
// example.module.ts
let routes = [
  { path: '**', component:  ExampleComponent }
]
```
```
// example.component.ts
if(this.platform.isPlatformServer()){
  this.titleService.setTitle('example');
}
```

but when the module is lazy loaded, title and meta services don't work in SSR (only works in client-rendering)
```
// app.module
  {
    path: '**',
    loadChildren: () =>
      import('./example.module').then(
        (modules) => modules.ExampleModule
      ),
  },
```

`ExampleComponent` is rendered in the server as expected, (tested by logging `this.platform.platformId` to the console)
but title and meta services only works when the condition `if(this.platform.isPlatformServer()` is removed.

I set this condition to test the behavior of title and meta services in server side. also Angular doesn't insert the added meta tags and the new title in the source code if rendered in client-side which makes issue with SEO and when scratching meta tags from the app or sharing to social media platform, that's why updating title and meta tags doesn't matter to me in client-side rendering.

also, it seems that if the module is lazy-loaded `fileReplacements` doesn't work, so `environment` has different values in the server and the browser
`console.log({ environment })` gives different values in the server's console that the browser's console if you build the app in development mode.

it seems that `ngOnChanges` doesn't fire on the server when the module loaded lazily
[minimal repro](https://github.com/eng-dibo/issue-meta-tags/blob/main/src/app/feature/lazy-child.component.ts#L13)

run `npm start`

in `feature/lazy-child.component.ts` the title should be set when a change is detected,but it don't.

also `console.log({ changes })` appears in the browser's console, but doesn't appear in the server's console

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.6
Node: 16.14.2
Package Manager: npm 8.5.4
OS: linux x64

Angular: 13.2.6
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.6
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.2.6
@angular-devkit/schematics      13.2.6
@nguniversal/express-engine     13.0.2
@schematics/angular             13.2.6
rxjs                            7.5.5
typescript                      4.5.5
```

**Comment by eng-dibo** [comment]
it seems that `ngOnChanges` doesn't fire on the server when the module loaded lazily
[minimal repro](https://github.com/eng-dibo/issue-meta-tags/blob/main/src/app/feature/lazy-child.component.ts)

run `npm start`

in `feature/lazy-child.component.ts` the title should be set when a change is detected,but it don't.

**Comment by hiepxanh** [comment]
it work normal with me, it must be your code not trigger change detection

**Comment by eng-dibo** [comment]
> it work normal with me, it must be your code not trigger change detection

do your server's console logged 'ngOnChanges works'?
