### ISSUE TITLE
 providedIn: 'platform'  is not working as expected

### ISSUE THREAD

**Issue by vugar005** [angular/angular#45399]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Hello team,
When we provide service with  `providedIn: 'platform' ` it is expected to be singleton among applications.
In my case I have shell app which uses angular custom element. But when I inject `SampleService`, noticed that the service is initiated twice. Screenshot is attached later below.

You can reproduce it from [branch](https://github.com/vugar005/youtube-webapp-turborepo/pull/22).
[Documentation ](https://github.com/vugar005/youtube-webapp-turborepo) for running application.

### Please provide a link to a minimal reproduction of the bug

https://github.com/vugar005/youtube-webapp-turborepo/pull/22

### Please provide the exception or error you saw

```true
No exception error but service is initiated twice. See below:
```
Navigate to localhost:4200 then choose any video card. See the console.    

![image](https://user-images.githubusercontent.com/28726265/159175287-bf041fab-5af0-4e77-8f02-4470cc6e88db.png)

As a confirmation we see that both shell and custom element are in the same **Platform**.

![tempsnip](https://user-images.githubusercontent.com/28726265/159176529-3337b61e-cb83-42ca-8895-37ed82a63825.png)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular:13.2.2
```

### Anything else?

This might be related to #43198. But it is mentioned there too that we should use  `providedIn: 'platform'`  but it is not working as expected.

**Comment by artaommahe** [comment]
> When we provide service with providedIn: 'platform' it is expected to be singleton among applications

nope, it's shared between bootstraped angular modules inside one angular instance. You can bootstrap multiple angular modules and share some services between them. Like this

```ts
bootstrapModules.forEach(bootstrapModule => {
  getPlatform()!
        .bootstrapModule(bootstrapModule)
        .catch(error => console.error(error))
});
```

Angular doesn't provide anything to share services between different angular instances nowdays.

**Comment by vugar005** [comment]
Hi @artaommahe, thanks for reply. Okey I created new issue for that.
