### ISSUE TITLE
navigate().back() ---iteration

### ISSUE THREAD

**Issue by Ravi220** [angular/angular#4541]
Protractor tool is new to me, could you please help me with the following.

How to iterate through browser.navigate().back()??

I have a page to automate where I need to click on all the links in home page, and then go back to the home page to click on the remaining links.

For time being I derived like the following:

HomePage.HomegMenuItem.click();
HomePage.reference.click();
browser.navigate().back();
HomePage.machine.click();
browser.navigate().back();
HomePage.connectivity.click();
browser.navigate().back();

Homepage and other var's are declared in page objects.

Thanks!!

**Comment by mgechev** [comment]
Hey @Ravi220. This repository is for Angular 2 only. If you've found any issues in Protractor you can report them here https://github.com/angular/protractor. If you need support you can use the gitter channel [here](https://gitter.im/angular/protractor).

**Comment by Ravi220** [comment]
Hey Minko,

Thanks for the directing me to the right page. I'm new to github as well. I'm learning. :)
