### ISSUE TITLE
In developer tools > Angular there is no data in component tree section.

### ISSUE THREAD

**Issue by Mateusz19021996** [angular/angular#45429]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I'm using angular 10.2.0 and I have no option to change it now... 

When I want to use Angular Dev Tools kit it detects angular application in dev mode but it doesn't show anything in Components section. I know that this issue was raised before, but what in case when I don't have option to change version?

I can see only view like that
![image](https://user-images.githubusercontent.com/62713072/159943105-04c0ff5a-555b-4f8a-bd1b-eb25b8a3c74a.png)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 10.2.0
Node: 14.17.0
OS: Windows 10
```

**Comment by mgechev** [comment]
Make sure you update to Angular v12+. We introduced new debugging APIs that provide more complete view of the component tree even with dynamically added content. Check https://github.com/rangle/angular-devtools/issues/773 for more details.

**Comment by Mateusz19021996** [comment]
@mgechev Hi, thanks for response, but as I sad above, I have no option to change it to another version than 10.2.0... is there another workaround?

**Comment by mgechev** [comment]
Would you share why you have no option to change? We're strongly encouraging all developers using Angular to use our `ng update` experience to keep up to date.

**Comment by jessicajaniuk** [comment]
v10 is actually not supported anymore, and v12 came with additional APIs as @mgechev said. DevTools now explicitly supports v12 and later. You can check out our [support policy](https://angular.io/guide/releases#support-policy-and-schedule) for more information.
