### ISSUE TITLE
Non-indicated compile time (type) error when using generic component in template

### ISSUE THREAD

**Issue by Jonas-Seiler-Wave** [angular/angular#45439]
# 🐞 bug report

### Is this a regression?

I don't know

### Description

 A clear and concise description of the problem...

I have a generic component that looks something like this
```typescript
export class SearchListingComponent<T extends Names> implements OnInit {
  @Input() type!: T;
  page$!: Observable<Type<T>[]>;
}
```
where the type `Names` is in this case just the String Literal Union `'user' | 'group' | 'servicePrincipal'`

The problem is that, when I try to do the following in a template, the compiler correctly errors, but this behavior does not get indicated in the editor.
```html
<app-search-listing type="something else"></app-search-listing> <!-- not indicated as type error -->
```

In contrast, if the component or rather the input type is not generic, it works as expected
```typescript
export class SearchListingComponent implements OnInit {
  @Input() type!: Names;
  page$!: Observable<Type<Names>[]>;
```
```html
<app-search-listing type="something else"></app-search-listing> <!-- correctly indicated as type error -->
```

Unfortunately, even when it compiles, the component also gets initialized with `any` instead of the correct type, thus rendering the type annotation on the exposed observable useless, but I assume that is more likely to be an issue with the compiler not being able to infer the type correctly and has nothing to do with the language service.

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [] Angular Language Service server

**Expected behavior**

## 🌍  Your Environment
**Angular Version:**
<pre><code>

Angular CLI: 13.2.4
Node: 14.17.5
Package Manager: npm 6.14.14
OS: win32 x64

Angular: 13.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
@angular-devkit/architect       0.1302.4
@angular-devkit/build-angular   13.2.4
@angular-devkit/core            13.2.4
@angular-devkit/schematics      13.2.4
@angular/cli                    13.2.4
@schematics/angular             13.2.4
rxjs                            7.5.4
typescript                      4.5.5
</code></pre>

Extension Version:
<pre><code>

v13.3.0
</code></pre>

VSCode Version:
<pre><code>

Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
</code></pre>

Operating System:
<pre><code>

Microsoft Windows 10 Enterprise
Version 10.0.19044 Build 19044

</code></pre>

Extension options:
<pre><code>

none
</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by Jonas-Seiler-Wave** [comment]
@atscott Sorry, I was on vacation. Maybe I should have just not included the very last paragraph, as that actually has nothing to do with this issue now that I think about it...  What I meant by "even when it compiles" was the case in which a correct string literal was used in the template, but that's actually besides the point.

The Problem is: 
Generic Component -> No error indicated in editor even though compiler does throw error

**Comment by atscott** [comment]
@Jonas-Seiler-Wave There are edge cases where we do expect the language service to not be able to provide as much information as the regular compiler (see the issues linked in https://github.com/angular/angular/issues/45439#issuecomment-1079177006). Without a reproduction, I can't be sure this is exactly what you're experiencing, but it does sound a lot like it. The long and short of it is that the compiler for the language service is using with the actual files on the disk that your editing for the program. There are situations (generic components which use a type that isn't exports, non-exported components, etc.) where the compiler needs to make an inline edit to the file in order to do its type checking. Of course, we can't actually make changes to the files you're actively editing so we instead have to fall back to an `any` type.

**Comment by Jonas-Seiler-Wave** [comment]
@atscott That would certainly explain the issue. Can you guide me to any sources on how to properly provide a reproduction?

**Comment by atscott** [comment]
@Jonas-Seiler-Wave I would expect if you created a fresh project and then copy-pasted the component in question into that (as well as adding/removing things so it builds correctly), you would be able to reproduce it. Then create a new github repository and push the project there.

**Comment by Jonas-Seiler-Wave** [comment]
@atscott Will this suffice? I managed to reproduce the exact behavior, at least on my end.
https://github.com/Jonas-Seiler-Wave/AngularLanguageServiceBugReproduction

**Comment by atscott** [comment]
@Jonas-Seiler-Wave Yes, that's exactly enough. As expected, this is a situation that requires an inline edit to the file. I mentioned in my previous comment that having a generic which references a non-exported type will cause this. If you export  the `Names` type in `generic-search-listing.component.ts`, that will fix your issue for the language service.

**Comment by Jonas-Seiler-Wave** [comment]
Thank you so much
