### ISSUE TITLE
Possibility of create a new observable as valueChanges  in FormGroup  return only key with values

### ISSUE THREAD

**Issue by renatodysouza** [angular/angular#45432]
### Description

Normally you need get only form fields that contains values, for example when  you need save only parts do form.
It is easy to resolve, but if angular FormGroup had a subscribe to return only values different of undefined and null.

Example:
  this.myForm = this.formBuilder.group({
    name: '',
    email: '',
    message: 'mock'
  });
  this.myForm.valueChanges.subscribe(val => {
       console.log(val)   //  {name: ' ', email: ' ', message: 'mock'}
  });

### Proposed solution

class [FormGroup](https://angular.io/api/forms/FormGroup) extends [AbstractControl](https://angular.io/api/forms/AbstractControl) {
.....

valueChanges: Observable<any>
valuePartialChanges: Observable<any>

Find a name is not easy :)

Example:

### Alternatives considered

  this.myForm = this.formBuilder.group({
    name: '',
    email: '',
    message: 'mock'
  });  

this.myForm.valuePartialChanges.subscribe(val => {
       console.log(val)   //  { message: 'mock'}
  });

**Comment by dylhunn** [comment]
You can do this pretty easily with rxjs `pipe`.

First, write a function that removes keys from your object with undefined/null values:
```
function removeUndefinedProps<T extends {}>(obj: T): Partial<T> {
  let r: any = {};
  for (const [k, v] of Object.entries(obj)) {
    if (v != null) r[k] = v;
  } 
  return r;
}
```

Then, use the `pipe` operator on the `valueChanges` observable:

```
myForm.valueChanges.pipe(
  map(removeUndefinedProps)
).subscribe(value => doStuff(value));
```

**Comment by renatodysouza** [comment]
@dylhunn  the problem is not resolve the problem outside of Angular , my suggestion is put this solution inside of Angular :)

**Comment by dylhunn** [comment]
Thank you for the feature request! I don't think we want to include this in the framework though -- there are many different ways you could filter your keys, and we want you to use `pipe` to construct your own event stream.
