### ISSUE TITLE
Make DevTools usable on virtual desktop without internet connection

### ISSUE THREAD

**Issue by dsmf** [angular/angular#45430]
### Description

We would love to use DevTools. But our customer allows development on a virtual desktop without internet connection only. We found a way to install DevTools in this environment but it looks pretty broken, because icons / images are obviously loaded from the web.

![screenshot](https://user-images.githubusercontent.com/19529362/159951390-b88f38f7-4828-4f89-b2b5-201b490237b6.png)
 

### Proposed solution

Include images instead of loading them via internet

### Alternatives considered

At least use alternative texts that are short enough so the layout does not become almost unusable.

**Comment by mgechev** [comment]
We should do this and the high number of votes confirms the feature's importance.

We're currently focused on Firefox support and dependency injection debugging. If anyone wants to take this feature and implement it, I'll be happy to guide them through the process.

**Comment by hereiskeith** [comment]
Hi @mgechev, I'd like to give it a try if possible, how may I contact you for more info and details about the codebase and the feature? Thanks in advance!

**Comment by cissoko97** [comment]
Hello @mgechev , I would like to contribute for this feature. How can I contact you for more information about?

**Comment by mgechev** [comment]
I assigned to @hereiskeith, but feel free to collaborate together.

**Comment by mgechev** [comment]
Ideally we'd like to have all the SVG icons available locally too so the application works offline identically to the way it functions online.

It's not yet clear to me what would be the best way to achieve this. Can we do anything at build time to download all the icons so that we don't have to commit them to the codebase here? cc @crisbeto

**Comment by crisbeto** [comment]
I'm not super familiar with how the DevTools is set up, but there are icons sets which are published to npm. E.g. here's the Material Design icon set from Google https://www.npmjs.com/package/material-design-icons. Then you can inline them using a Webpack loader and `require` or you could have Bazel copy them into the Chrome extension directory.

**Comment by AleksanderBodurri** [comment]
I imagine a solution looking something like

1. Add material-design-icons as a dependency
2. Use bazel to copy the material icon svgs to the assets directory at build time
3. Refactor each MatIcon component to be used with the method highlighted [here](https://material.angular.io/components/icon/api#:~:text=Specify%20the%20svgIcon%20input%20to%20load%20an%20SVG%20icon%20from%20a%20URL%20previously%20registered%20with%20the%20addSvgIcon)

**Comment by hereiskeith** [comment]
Thanks, @crisbeto @AleksanderBodurri! 

Are you suggesting adding a `genrule` in the BUILD.bazel from shell-chrome/src/assets and creating a custom tool (.bzl) to help copy only the icon svgs used in devtools?

**Comment by AleksanderBodurri** [comment]
@hereiskeith Probably it would be good enough to add `"@npm//:node_modules/<path to svgs>/**/*.svg` in the assets bazel file in `shell-chrome`. This will include the exposed files in the final build under the path `npm/node_modules/<path to svgs>/...`. You should be able to use those paths with `MatIconRegistry`'s  `addSvgIcon`

**Comment by hereiskeith** [comment]
@AleksanderBodurri When I do something like  
`srcs = glob(["@npm//:node_modules/material-design-icons/**/*.svg"]`
in `filegroup`

The build ends up in this error `Error in glob: empty segment not permitted`

It looks like glob may not support "@": https://github.com/bazelbuild/bazel/issues/1346

Also from the docs looks like Glob only searches files in its own package, and looks only for source files?

May I have your insights on this? Thanks

**Comment by AleksanderBodurri** [comment]
@hereiskeith 
Ahh, I see, we may need to try a different approach. @devversion pointed out that there is a subset of material-design-icons vendored already in this repo in https://github.com/angular/angular/blob/master/third_party/github.com/google/material-design-icons.

Could we try bringing in the font from there with bazel and using it in DevTools? We can consider bringing in targeted material svgs if the font approach does not work.

Apologies for the late reply

**Comment by hereiskeith** [comment]
@AleksanderBodurri No worries at all! I saw that font file as well when I was trying to solve the issue last week lol. The approach you suggested here is also recommended by https://developers.google.com/fonts/docs/material_icons#setup_method_2_self_hosting

I think I have made it work with your suggestion, just need to check if the tests passed. The PR is still in draft, but please feel free to let me know if you think there is anything (coding rules, coding styles) I should make changes to. 

Many thanks again👍

**Comment by AleksanderBodurri** [comment]
closed in https://github.com/angular/angular/pull/45743
