### ISSUE TITLE
Input-Placeholder is empty after resetting an auto-completed input-field in firefox

### ISSUE THREAD

**Issue by 5te1n** [angular/angular#45436]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

I have a strange behavior after I fill an input field using the autocomplete feature of the Firefox browser.
The placeholder disappears, then I reset the connected form control. This happens only in Firefox. The placeholder reappears, then I write a new value and delete it by hand.

![image](https://user-images.githubusercontent.com/1822816/160112863-1f360b3c-f8c3-4b82-993c-7e9e82180635.png)

Autocomplete
![image](https://user-images.githubusercontent.com/1822816/160113455-598e0ab0-4c55-4c64-85cb-19b6de4bef6d.png)

After resetting 
![image](https://user-images.githubusercontent.com/1822816/160112903-9ba4841e-30b7-46fc-9825-dfba52dbf257.png)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-48sfbh?file=package.json

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 13.0.3
```

**Comment by geromegrignon** [comment]
I can't reproduce it.
Firefox version: 98.0.2 (64 bits)

**Comment by AlirezaEbrahimkhani** [comment]
@5te1n 
Yeah, I can see the problem and I think it doesn't relate to angular and relate to firefox.

@geromegrignon 
My firefox version is 98.0.2 (64-bit) too but the problem still exists.

**Comment by jessicajaniuk** [comment]
We tried following the steps with Firefox 100.0.1 but we weren't able to reproduce this following your steps. You could try to reproduce this with vanilla javascript to verify that it's a browser issue with Firefox. If it is reproducible in that case, then it's definitely a Firefox issue and unrelated to Angular.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template that include info on how to create a reproduction using our template.
