### ISSUE TITLE
httpClient doesn't work in SSR when the module is lazy loaded

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular#45453]
### Which @angular/* package(s) are the source of the bug?

common, platform-server

### Is this a regression?

No

### Description

when a module is lazy loaded, and a component subscribes to a httpClient.get() to set a variable that fulfills the condition to render a child component, it seems that the child component never rendered in the server.

consider the following sitiuation:

1- appModule contains a router to load `feature.module` lazely when the path matches 'lazy', and in its turn it loads the component `lazy.component`

```
// app.module

const routes=[
  {
    path: 'lazy',
    loadChildren: () =>
      import('./feature/feature.module').then(
        (modules) => modules.FeatureModule
      ),
  },
]
```
```
// feature.module
const routes: Routes = [{ path: '**', component: LazyComponent }];
```
2- now `lazy.component` should be loaded when we go to the path `/lazy`
```
// lazy.component
@component(
    template: '<lazy-child-comp *ngIf="ready"></lazy-child-comp>',
}
export class LazyComponent {
  ready=false
  constructor(private httpClient:HttpClient) {
     this.httpClient.get('https://jsonplaceholder.typicode.com/todos/1').subscribe(()=>{
       this.ready=true
     })
  }
}
```
lazy.component` performs an http request, and when it is completed it set `this.ready=true` so `<lazy-child-comp>` starts to be rendered

when `<lazy-child-comp>` renderes it log `'===> lazy-child: constructor'` to the console.
this logs to the browser's console, but doesn't log to the server's console

**tests**
- the exactly same sinario is made with `normal.component` when you go to the path `/normal` and it works in both browser and server sides.
- when you replace `http.get()` with `of('')` to simulate an Observable, it works with `lazy.component` in both browser and server sides, even when you pipe `delay(1000)` to it.

### Please provide a link to a minimal reproduction of the bug

https://github.com/eng-dibo/issue-meta-tags

### Please provide the exception or error you saw

```true
1- run `npm start`
2- navigate to localhost:4200/lazy
3- check browser's and server's consoles, you should see the same log in both
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.0
Node: 16.14.2
Package Manager: npm 8.5.0
OS: linux x64

Angular: 13.3.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.0
@angular-devkit/build-angular   13.3.0
@angular-devkit/core            13.3.0
@angular-devkit/schematics      13.3.0
@nguniversal/builders           13.0.2
@nguniversal/express-engine     13.0.2
@schematics/angular             13.3.0
rxjs                            7.5.5
typescript                      4.6.2
```

**Comment by alan-agius4** [comment]
Hi @eng-dibo, 

The problem appears to be that you are adding the `HttpClientModule` in the `FeatureModule`. This is causing the server override of [`XhrFactory` ](https://github.com/angular/angular/blob/aebf165359ad6de5a8bacd9cb91651fc4175aaad/packages/platform-server/src/http.ts#L139) to be overridden by the browser version in the lazy module.

```diff
 @NgModule({
   declarations: [LazyComponent, LazyChildComponent],
-  imports: [CommonModule, RouterModule.forChild(routes),HttpClientModule],
+  imports: [CommonModule, RouterModule.forChild(routes)],
 })
```
