### ISSUE TITLE
Add support to the router for handle components that are having an @Attribute as parameter in their consturctor

### ISSUE THREAD

**Issue by DavidGangel** [angular/angular#4545]
Hi,

I'm having the following component implementation:
```
/// <reference path="../../../custom_typings/_custom.d.ts" />

import { Component, View } from 'angular2/angular2';
import { Attribute } from 'angular2/angular2';

@Component({
	selector: this.selector
})

@View({
	templateUrl: this.templateUrl
})

export class BaseComponent {
	selector: String;
	templateUrl: String
	
	constructor(@Attribute('selector') selector: String, @Attribute('templateUrl') templateUrl: String) {
		this.selector = selector;
		this.templateUrl = templateUrl;		
	}
}
```

Now I would like to assign a route for this component in a RouteConfig and I need to give the values for the constructor parameters.

**Comment by mhevery** [comment]
`@Attribute` is being depricated/removed, hence we should not be adding support here.

**Comment by DavidGangel** [comment]
Hi,

but then how can I achive the same scenario?
I still don't see how is my case supported.

**Comment by ericmartinezr** [comment]
@DavidGangel I think this may be useful for your case https://github.com/angular/angular/issues/4452

**Comment by DavidGangel** [comment]
@ericmartinezr thank you.
Then I'm going to wait for the final outcome from the linked ticket and see how can I use it.
