### ISSUE TITLE
Can't set routerLinkActive Class when used named outlet as null

### ISSUE THREAD

**Issue by Sumon-TWeb** [angular/angular#45456]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

In a module I defined a named router-outlet 
`<router-outlet name="aside"></router-outlet>`

In that same module, I have some lazy-loaded component, some are using primary outlet, One component using named outlet or secondary outlet.

![image](https://user-images.githubusercontent.com/61141437/160356168-a6c696a8-50d2-4940-af94-00ed2db21f61.png)

Please check the attach image, here "LP" and "CP" required a secondary outlet, but "start" has no requirement for secondary outlet. So, I had reset the  secondary outlet "aside" to null for navigating "LP" to "start". It is working as expected. But routerLinkActive directive is working well for the "LP" and "CP" link, but unfortunately it is not working for "start" link.

Can you please explain why it is behave like this?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.2.14
Node: 12.22.8
Package Manager: npm 6.14.15
OS: linux x64

Angular: 12.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1202.14
@angular-devkit/build-angular      12.2.14
@angular-devkit/core               12.2.14
@angular-devkit/schematics         12.2.14
@angular/cdk                       12.2.13
@angular/cli                       12.2.14
@angular/material                  12.2.13
@angular/material-moment-adapter   12.2.13
@schematics/angular                12.2.14
rxjs                               6.6.7
typescript                         4.3.5
```

**Comment by atscott** [comment]
Can you please provide a reproduction? I was not able to reproduce this. https://stackblitz.com/edit/angular-ivy-router-base-hwswzm?file=src%2Fapp%2Fapp.component.ts demonstrates the correct behavior.

**Comment by Sumon-TWeb** [comment]
Hi @atscott, Okay sure. I will share a reproduction.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
