### ISSUE TITLE
Support type casting with 'as' in template

### ISSUE THREAD

**Issue by calebegg** [angular/angular#45468]
### Description

With strict type checking, types sometimes need to be cast

### Proposed solution

Support `foo as Bar` syntax in the template

### Alternatives considered

None

**Comment by alxhub** [comment]
Unfortunately we can't support this - the scope for Angular components is the component class, and classes in TypeScript don't have type-valued members. That means there is no direct way to bring a type into the namespace of a component in a way that any casting syntax in the template could reference.

Instead, either:

1. structure types in the component such that casts happen there, not in the template.
2. use type assertion functions (example: `castToFoo(value: any): value is Foo { return true; }`) in the component to allow casting specific types in the template.
