### ISSUE TITLE
Angular 2::alpha-38

### ISSUE THREAD

**Issue by shatakshidixit1** [angular/angular#4546]
npm install angular2 is not working.
it throws error:

**npm ERR! 404 'reactivex' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.
npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "angular2"
npm ERR! cwd /home/shatakshi/Documents/a
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code E404
npm http 304 https://registry.npmjs.org/zone.js/0.5.7
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/shatakshi/Documents/a/npm-debug.log
npm ERR! not ok code 0**

**Comment by jessegood** [comment]
See https://github.com/angular/angular/issues/4516 (need to update npm to at least 2.7.0)

**Comment by shatakshidixit1** [comment]
closing this as a duplicate of #4516
