### ISSUE TITLE
Unexpected token '.' in Ipad mini with ios v12.2 [env dev]

### ISSUE THREAD

**Issue by yaiceltg** [angular/angular#45499]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When we create a new project in angular and open it on an iPad mini using ios v12.2, the application breaks and does not continue execution, that is, the page does not load and the console only throws the next error

```
SyntaxError: Unexpected token '.'
promiseReactionJob	@	(program):1
```

**Device** 

> iPad Mini 2019 v12.2
> Release 2019, March
> OS iOS, v12.2
> Browser Safari
> Screen Size 7.9 in - 4.74 x 6.32 in
> Resolution 1536 x 2048 px
> Viewport 768 x 1024 dp
> Aspect Ratio 4 : 3

### Please provide a link to a minimal reproduction of the bug

1 - Create new project and open into ipad mini with ios 

### Please provide the exception or error you saw

```true
SyntaxError: Unexpected token '.'
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.3
Node: 14.18.2
Package Manager: npm 6.14.15
OS: linux x64

Angular: 13.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                              Version
--------------------------------------------------------------
@angular-devkit/architect            0.1300.3
@angular-devkit/build-angular        13.0.3
@angular-devkit/core                 13.0.3
@angular-devkit/schematics           13.0.3
@angular/cli                         13.0.3
@angular/flex-layout                 13.0.0-beta.36
@angular/material-date-fns-adapter   13.2.5
@angular/service-worker              13.0.3
@schematics/angular                  13.0.3
ng-packagr                           13.0.6
rxjs                                 7.4.0
typescript                           4.4.4
```

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

Could you please provide a repro in a form of a GitHub repository, so that we can try to reproduce an issue?

**Comment by atscott** [comment]
Closing. We support the two most recent versions of safari: https://angular.io/guide/browser-support

The most recent version of safari is 15
