### ISSUE TITLE
refactor(linker): move common functions to util file

### ISSUE THREAD

**Issue by mgechev** [angular/angular#4549]
There're some duplicate declarations, for instance:

- `isValidDirective` (both in `directive_resolver.ts` and `runtime-metadata.ts`, in case https://github.com/angular/angular/pull/4548 gets merged)
- `flattenList` (both in `runtime-metadata.ts` and `proto_view_factory.ts`)

It'll be nice if we extract them to separate file and include them wherever they are required.

If it makes sense I can take this one.

**Comment by phamcharles** [comment]
What commit/branch should I work on this off of?

**Comment by pkozlowski-opensource** [comment]
> What commit/branch should I work on this off of?

[master[(https://github.com/angular/angular/commits/master)

**Comment by mgechev** [comment]
If @phamcharles is not yet working on it, can I take it?

**Comment by phamcharles** [comment]
@mgechev Go for it. My other work picked up, didn't have time.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
