### ISSUE TITLE
The `../../../dist/angular/ngcnq.module.d.ts:3:21` path indicates that the library's sources exist outside of your workspace root. From within that file, there is no `node_modules` directory reachable that contains `@angular/core`, hence the error. This is not an Angular bug but rather an effect of how module resolution works.

### ISSUE THREAD

**Issue by f1ames0ff** [angular/angular#45517]
The `../../../dist/angular/ngcnq.module.d.ts:3:21` path indicates that the library's sources exist outside of your workspace root. From within that file, there is no `node_modules` directory reachable that contains `@angular/core`, hence the error. This is not an Angular bug but rather an effect of how module resolution works.

If the library is set up using a symlink then using the `preserveSymlinks` TypeScript option may help, but it won't when this setup is accomplished using path mappings.

_Originally posted by @JoostK in https://github.com/angular/angular/issues/45515#issuecomment-1086941799_

**Comment by f1ames0ff** [comment]
> The ../../../dist/angular/ngcnq.module.d.ts:3:21 path indicates that the library's sources exist outside of your workspace root. From within that file, there is no node_modules directory reachable that contains @angular/core, hence the error. This is not an Angular bug but rather an effect of how module resolution works.
> 
> If the library is set up using a symlink then using the preserveSymlinks TypeScript option may help, but it won't when this setup is accomplished using path mappings.

But it exists.

**Comment by f1ames0ff** [comment]
I've found a temporal bypass. Added @angular/core to dependencies of the library.

// package.json
  "dependencies": {
    "@angular/core": "^13.3.0",
  // ng-package.json
  "allowedNonPeerDependencies": [
    "@angular/core"
  ]
But it should not be like this. This is not the first time the ng-packager has messing things up.

**Comment by JoostK** [comment]
Please keep the discussion in #45515.

**Comment by f1ames0ff** [comment]
@JoostK Please don't close the discussions.
