### ISSUE TITLE
alpha.38: Incorrect ViewContainerRef injected w/ nested components

### ISSUE THREAD

**Issue by adamdbradley** [angular/angular#4551]
It appears that ViewContainerRef is getting the wrong references when components are nested. I tried to come up with some plnkrs that show how nested components are injecting the wrong ViewContainerRef.

In the examples, I'm printing out the native element's tag name to show the component is referencing the wrong one:

alpha.38 does not inject the correct ref:
http://plnkr.co/edit/lyBBvYiAWs7hG1Cjkob0?p=preview

alpha.37 injects the correct ref:
http://plnkr.co/edit/1XexLiqbBrzThZwFtlYH?p=preview

**Comment by tbosch** [comment]
@adamdbradley could you retry with the current master? We had a bug where element indices were mixed up...

**Comment by tbosch** [comment]
Just released alpha.39, this bug is fixed there: http://plnkr.co/edit/hgxdCdbsg5x4xGEODB31?p=preview

**Comment by adamdbradley** [comment]
Yup, everything's working in alpha39, thanks!

**Comment by TiagoBraga39** [comment]
Are you sure?
It is supposed to be:
```html
CmpD: viewContainerRef element is CMP-D
CmpC: viewContainerRef element is CMP-C
```

**Comment by TiagoBraga39** [comment]
Wait!
The content for components are swapped... Check the html
```html
<cmp-c>
  CmpD: viewContainerRef element is CMP-D
</cmp-c>
```

**Comment by tbosch** [comment]
@TiagoBraga39 yes, you are right, this is still buggy!

**Comment by adamdbradley** [comment]
Oh great catch @TiagoBraga39! Thanks for pointing that out, I didn't even notice.
