### ISSUE TITLE
Cannot find module '@angular/core' or its corresponding type declarations.

### ISSUE THREAD

**Issue by f1ames0ff** [angular/angular#45518]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

After building of a library and adding it to the project I'm constantly getting this error.

### Please provide the exception or error you saw

```true
Error: ../../../dist/angular/ngcnq.module.d.ts:3:21 - error TS2307: Cannot find module '@angular/core' or its corresponding type declarations.

3 import * as i0 from "@angular/core";
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 13.3.0
Node: 12.22.10
Package Manager: npm 6.14.16
OS: win32 x64

Angular: 13.3.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.1
@angular-devkit/build-angular   13.3.1
@angular-devkit/core            13.3.1
@angular-devkit/schematics      13.3.1
@schematics/angular             13.3.1
ng-packagr                      13.3.0
rxjs                            7.5.5
typescript                      4.6.3
```

### Anything else?

> The ../../../dist/angular/ngcnq.module.d.ts:3:21 path indicates that the library's sources exist outside of your workspace root. From within that file, there is no node_modules directory reachable that contains @angular/core, hence the error. This is not an Angular bug but rather an effect of how module resolution works.
> 
> If the library is set up using a symlink then using the preserveSymlinks TypeScript option may help, but it won't when this setup is accomplished using path mappings.

No, it doesn't work like that. Please don't close bug tickets if you don't even understand how Angular works.

**Comment by JoostK** [comment]
Please keep in mind that I'm only trying to help here, and keeping it in a single issue is better to keep things organized.

**Comment by f1ames0ff** [comment]
@JoostK Why then you're closing issues without resolving it? 
The more you do it - the less bugs will be reported. Simple.
