### ISSUE TITLE
Cannot find module '@angular/core' or its corresponding type declarations.

### ISSUE THREAD

**Issue by f1ames0ff** [angular/angular#45515]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

After building of a library and adding it to the project I'm constantly getting this error:

### Please provide the exception or error you saw

```true
Error: ../../../dist/angular/ngcnq.module.d.ts:3:21 - error TS2307: Cannot find module '@angular/core' or its corresponding type declarations.

3 import * as i0 from "@angular/core";
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 13.3.0
Node: 12.22.10
Package Manager: npm 6.14.16
OS: win32 x64

Angular: 13.3.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.1
@angular-devkit/build-angular   13.3.1
@angular-devkit/core            13.3.1
@angular-devkit/schematics      13.3.1
@schematics/angular             13.3.1
ng-packagr                      13.3.0
rxjs                            7.5.5
typescript                      4.6.3
```

**Comment by JoostK** [comment]
The `../../../dist/angular/ngcnq.module.d.ts:3:21` path indicates that the library's sources exist outside of your workspace root. From within that file, there is no `node_modules` directory reachable that contains `@angular/core`, hence the error. This is not an Angular bug but rather an effect of how module resolution works.

If the library is set up using a symlink then using the `preserveSymlinks` TypeScript option may help, but it won't when this setup is accomplished using path mappings.

**Comment by f1ames0ff** [comment]
> The `../../../dist/angular/ngcnq.module.d.ts:3:21` path indicates that the library's sources exist outside of your workspace root. From within that file, there is no `node_modules` directory reachable that contains `@angular/core`, hence the error. This is not an Angular bug but rather an effect of how module resolution works.
> 
> If the library is set up using a symlink then using the `preserveSymlinks` TypeScript option may help, but it won't when this setup is accomplished using path mappings.

But it exists.

**Comment by f1ames0ff** [comment]
I've found a temporal bypass. Added `@angular/core` to dependencies of the library.

```
// package.json
  "dependencies": {
    "@angular/core": "^13.3.0",
```

```
  // ng-package.json
  "allowedNonPeerDependencies": [
    "@angular/core"
  ]
```

But it should not be like this. This is not the first time the ng-packager has messing things up.

**Comment by JoostK** [comment]
> > The `../../../dist/angular/ngcnq.module.d.ts:3:21` path indicates that the library's sources exist outside of your workspace root. From within that file, there is no `node_modules` directory reachable that contains `@angular/core`, hence the error. This is not an Angular bug but rather an effect of how module resolution works.
> 
> > 
> 
> > If the library is set up using a symlink then using the `preserveSymlinks` TypeScript option may help, but it won't when this setup is accomplished using path mappings.
> 
> 
> 
> But it exists.

What does "it" mean?

> But it should not be like this. This is not the first time the ng-packager has messing things up.

Indeed, it should not be like that. You'd need to include the library's output in the workspace root where you're using the library, as otherwise the library cannot "see" any `@angular/core` (it only searches in its ancestor directories for `node_modules`). This is unrelated to Angular, ng-packagr and the CLI; it's how package management in the Node ecosystem works.

**Comment by f1ames0ff** [comment]
> What does "it" mean?

It means that reachable `node_modules` folder is exists.  

> Indeed, it should not be like that. You'd need to include the library's output in the workspace root where you're using the library, as otherwise the library cannot "see" any `@angular/core` (it only searches in its ancestor directories for `node_modules`). This is unrelated to Angular, ng-packagr and the CLI; it's how package management in the Node ecosystem works.

Exactly. Parent folder contains `node_modules` which contains `@angular/core`. But this error presents. That's what I want to explain, but I constantly late, after ticket is already "Closed".
And thanks for the explanation how Node eosystem works, but I'm working with it almost 10 years, so I quite understand what's going on without your explanation, and I would notice if there wouldn't dependency in a reachable folder and would not open this ticket accordingly.

**Comment by JoostK** [comment]
Can you share a reproduction (repo on Github)?
