### ISSUE TITLE
Create TS module exports for NgModule exports

### ISSUE THREAD

**Issue by pauldraper** [angular/angular#45529]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

NgModule requires repeating exported components three times: (1) NgModule declaration (2) NgModule export (3) TS export.

&#35;1 and &#35;2 are semantically distinct, but &#35;3 isn't. This makes an already dubious NgModule experience even more confusing and onerous.

Example:

**lib/package.json**

```json
{
  "devDependencies": {
    "@angular/core": "~13.3.0"
  },
  "name": "example-lib",
  "private": true,
  "version": "0.0.0"
}
```

**lib/tsconfig.json**

```json
{
  "compilerOptions": {
    "declaration": true,
    "outDir": ".",
    "rootDir": "src",
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "target": "es2015"
  },
  "include": ["src/**/*"],
  "exclude": []
}
```

**lib/src/lib.component.ts**

```ts
import { Component } from "@angular/core";

@Component({ selector: "example-lib", template: "" })
export class LibComponent {}
```

**lib/src/module.ts**

```ts
import { NgModule } from "@angular/core";
import { LibComponent } from "./lib.component";

@NgModule({
  declarations: [LibComponent],
  exports: [LibComponent],
})
export class LibModule {}
```

**main/index.ts**

```ts
import { Component, NgModule } from "@angular/core";
import { LibModule } from "example-lib/module";

@Component({ template: "<example-lib></example-lib>" })
export class MainComponent {}

@NgModule({
  bootstrap: [MainComponent],
  declarations: [MainComponent],
  imports: [LibModule],
})
export class MainModule {}
```

**main/package.json**

```json
{
  "dependencies": {
    "@angular/core": "~13.3.0",
    "example-lib": "file:../lib"
  },
  "name": "example-main",
  "private": true,
  "version": "0.0.0"
}
```

**main/tsconfig.json**

```json
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "target": "es2015"
  }
}
```

Run

```sh
(cd lib && npm i)
(cd main && npm i)
ngc -p lib
ngc -p main
```

Compiling the main project fails:

```
index.ts:5:14 - error NG3004: Unable to import component LibComponent.
  The symbol is not exported from /home/paul/example/lib/module.d.ts (module 'example-lib/module').

5 export class MainComponent {}
               ~~~~~~~~~~~~~

  ../lib/lib.component.d.ts:2:1
      2 export declare class LibComponent {
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      3   static ɵfac: i0.ɵɵFactoryDeclaration<LibComponent, never>;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ... 
     12   >;
        ~~~~
     13 }
        ~
    The component is declared here.
```

To resolve this error, the developer must add `export { LibComponent }` to `lib/module.ts`.

To make matters worse, this is only an issue when the reference is external; path-relative references are fine, so it's easy for the lib developer to neglect the export.

### Proposed solution

Rather than requires its users to double-export, NgModule exports produce TS exports automatically.

That is, the compiler should internally create the following:

```
import { NgModule } from "@angular/core";
import { LibComponent } from "./lib.component";

@NgModule({
  declarations: [LibComponent],
  exports: [LibComponent],
})
export class LibModule {}

export { LibComponent as θcomponent0 }
```

### Alternatives considered

Write Everything Twice

**Comment by JoostK** [comment]
Have you tried the `generateDeepReexports` compiler option? It is meant for library compilations that do not follow Angular Package Format (with the `flatModuleOutFile` compiler option). APF precludes deep imports and requires that declarations are exported from the entry-point (this is verified during library compilation when using `flatModuleOutFile`) but if you don't intent to follow the APF specification (e.g. in a monorepo) then `generateDeepReexports` does what you suggest it should.

https://github.com/angular/angular/blob/035ba83b16772b7322745f9a5308b3287f5726bc/packages/compiler-cli/src/ngtsc/core/api/src/public_options.ts#L310-L339

**Comment by pauldraper** [comment]
Thanks, I just found that in the code.

`generateDeepReexports` solves it.

It's a shame it's not in the web docs :/ https://angular.io/guide/angular-compiler-options
