### ISSUE TITLE
What if providedIn: 'root' and module forRoot provide the same service?

### ISSUE THREAD

**Issue by pengrongbo** [angular/angular#45522]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

In my case, I would like to use forRoot to customize the implementation, but I still need default implementation in the root scope.
So my question is if I add the providedIn: root and specified usedClass, at the same time, the module forRoot has been called in AppModule.

Which implementation will take precedence between forRoot and providedIn: root?

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

An NgModule provider wins over `providedIn: 'root'`. You can easily experiment with this yourself.

**Comment by pengrongbo** [comment]
Thanks, that's exactly what I need.
