### ISSUE TITLE
wrong punctuation in angular doc

### ISSUE THREAD

**Issue by hossein13m** [angular/angular#45538]
### Description

In the following link, the wrong punctuation has been used. Instead of `:` we should write `,`.
https://angular.io/guide/forms-overview#choosing-an-approach

### What is the affected URL?

https://angular.io/guide/forms-overview#choosing-an-approach

### Please provide the expected behavior vs the actual behavior you encountered

Expected behavior: using `,` for more than one element in a sentence.

Actual behavior: It is using `:` which is incorrect.

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/45146636/161900212-0c218626-08b2-4204-97f4-396d5d64146b.png)

**Comment by alxhub** [comment]
I see you're working on a PR to fix this - I don't think we need to track this as an open issue.
