### ISSUE TITLE
Documented way of Checking SW updates produces false 'update' every time

### ISSUE THREAD

**Issue by WLK4Tower** [angular/angular#45536]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

No

### Description

Using Angular v10, and according to [this documentation](https://angular.io/guide/service-worker-communications#checking-for-updates):

An 'update' will always be available on the specified interval when the promise is fulfilled.

```
import { ApplicationRef, Injectable } from '@angular/core';
import { SwUpdate } from '@angular/service-worker';
import { concat, interval } from 'rxjs';
import { first } from 'rxjs/operators';

@Injectable()
export class CheckForUpdateService {

  constructor(appRef: ApplicationRef, updates: SwUpdate) {
    // Allow the app to stabilize first, before starting
    // polling for updates with `interval()`.
    const appIsStable$ = appRef.isStable.pipe(first(isStable => isStable === true));
    const everySixHours$ = interval(6 * 60 * 60 * 1000);
    const everySixHoursOnceAppIsStable$ = concat(appIsStable$, everySixHours$);

    everySixHoursOnceAppIsStable$.subscribe(() => updates.checkForUpdate().then(() => {
       //always get here, regardless of interval size. Ideally here is where we could prompt the user then applyUpdate() and refresh
    }));
  }
}
```

### Please provide a link to a minimal reproduction of the bug

https://bitbucket.org/WLK4Tower/swupdatetest/src/main/

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 10.0.8
Node: 12.18.3
OS: win32 x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker
Ivy Workspace: No

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cdk                      10.1.3
@angular/cli                      10.0.8
@angular/flex-layout              10.0.0-beta.32
@angular/material                 10.1.3
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.6.2
typescript                        3.9.10
webpack                           4.44.1
```

### Anything else?

My guess could be that the app is stable, then unstable, then stable again? Let me know what you see from the linked repo. Tested using http-server.

**Comment by alxhub** [comment]
I would expect your current code to do exactly what you say. The `appIsStable$`observable will emit once, the first time `isStable` becomes `true`. `concat` will subscribe to `appIsStable$` and propagate that emit, which then triggers a `checkForUpdate` call, which always returns a `Promise<boolean>` depending on whether an update is available or not.

Note that the documentation for `checkForUpdate` does not say that it only resolves if an update is available, but rather that it returns a `Promise` which indicates whether one is available.

**Comment by gkalpak** [comment]
In addition to what Alex said, keep in mind that the behavior of [SwUpdate#checkForUpdate()][1] was slightly different in v10. The returned promise used to resolve to no value and one had to rely on [SwUpdate#available][2] to know whether an update was found.

(NOTE: The docs on https://angular.io/ pertain to the latest stable version.)

[1]: https://v10.angular.io/api/service-worker/SwUpdate#checkForUpdate
[2]: https://v10.angular.io/api/service-worker/SwUpdate#available

**Comment by WLK4Tower** [comment]
George, Alex -

Thank you both for the clarification. I cannot update angular yet due to
certain dependencies in the project, but I will try that additional call to
.available and see if that solves it!

I appreciate the quick response and the clarification. Thank you both!
