### ISSUE TITLE
Angular.io website is not GDPR compliant

### ISSUE THREAD

**Issue by BarthDELUY** [angular/angular#45541]
### Description

Hi,

I searched the issue tracker, for both open and closed issue, with keywords "GDPR" and "Google", but no issue seemed related.

When first loading the angular.io website, there is a small pop-in on the lower-left corner of the site, stating that 

> This site uses cookies from Google to deliver its services and to analyze traffic. 

When looking at the [source code](https://github.com/angular/angular/blob/master/aio/src/index.html), one can see that : 

- the websites asks the browser to connect to GA
- the website asks the browser to connect to doubleclick
- 2 GA scripts are instantiated
- angular.io uses google fonts

[GDPR article 7](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679&from=FR#d1e2001-1-1) states that the consent has to be collected _prior_ to any sharing of personal data.

A German court ruled in January 2022 that Google Fonts usage was effectively illegal in the EU, without collecting users' consent prior to downloading them : https://thehackernews.com/2022/01/german-court-rules-websites-embedding.html
The French CNIL (Internet regulator) also sentenced a website owner because of GA in February 2022 : https://www.cnil.fr/en/use-google-analytics-and-data-transfers-united-states-cnil-orders-website-manageroperator-comply

Possible workarounds are :
 - either switch to a self-hosted analytics tool, OR collect consent before enabling any connection to Google's infrastructure
 - locally host the fonts

### What is the affected URL?

https://angular.io/

### Please provide the steps to reproduce the issue

Connect to the page (possibly using a private window if you accepted cookies before).

### Please provide the expected behavior vs the actual behavior you encountered

Expected behaviour : a banner/pop-in is displayed, asking for consent prior to using GA, doubleclickn and Google Fonts; if consent is refused, none of those tools is used during the browsing session.

Actual behaviour : a pop-in tells the user his personal data has been shared with Google.

### Please provide a screenshot if possible

https://i.imgur.com/7bTG7uy.png

### Please provide the exception or error you saw

```true
N/A
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
No
```

**Comment by spock123** [comment]
Loading a script/library does not equal loading data.
We do it a my work as well, but we don't push any tags to Analytics unless the consent is given.

**Comment by IRod22** [comment]
What is the explanation for this? Why is the @angular team not responding to something that involves potential litigation? Just because Angular is a Google project does ***not*** mean Google's analytics can be used without consent.

**Comment by mgechev** [comment]
Thank you for your report. We are committed to respecting people's privacy, and are reviewing our practices. I'm going to close this issue for now, but thank you again for filing this issue.

PS: I'll thumbs-down my comment because I recognize I'd react in a similar way if I were you.
