### ISSUE TITLE
http client reading content type from request instead of request

### ISSUE THREAD

**Issue by kinglau66** [angular/angular#45540]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

http client will read from req.content-type rather than header.get('content-type') for getting the response's content.

**Comment by kinglau66** [comment]
https://github.com/angular/angular/blob/master/packages/common/http/src/xhr.ts#L158
its reading the request content-type to determine the response body is json

**Comment by JoostK** [comment]
This is working as designed; please see https://github.com/angular/angular/issues/36274#issuecomment-636121537 for details.
