### ISSUE TITLE
Angular 13: Getting Uncaught SyntaxError: Unexpected token 'export' when I run the app

### ISSUE THREAD

**Issue by deepak-prabhu** [angular/angular#45557]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I have updated the Angular from 12 to 13. When I run the app I am getting the error **"Uncaught SyntaxError: Unexpected token 'export"**. Adding below few details to get the context.

Earlier in angular.json config, I had below dependent entries in scripts section.

"**scripts**": [
"./node_modules/@angular/core/bundles/core.umd.min.js",
"./node_modules/@angular/common/bundles/common.umd.min.js",
]

After the angular update to 13, I noticed that in place of umd JS files we have **.mjs file** (Modular JS files) "./node_modules/@angular/core/esm2020/**core.mjs**". So I have added .mjs file location inside scripts section of angular json configuration

When I run the app I'm getting the error from **scripts.js** and it's pointing to the line "export * from './index';" (this line is from **core.mjs** file)

Please let me know how to fix this issue?

I tried adding the type "**module**" in main package.json. But still getting the same issue.

**Note:**

If I execute the above script manually eg: node --es-module-specifier-resolution=node ./node_modules/@angular/core/esm2020/core.mjs it works fine

**How To Reproduce**

1. Take any Angular 13 app and add below entries like "./node_modules/@angular/core/esm2020/core.mjs" in scripts section of Angular.json configuration file
2. Build and run the app
3. In browser console, you will see the error Uncaught SyntaxError: Unexpected token 'export'

**Expected Behaviour**

1. App should run without any JS errors
2. Should be able to identify the export keyword

### Please provide the exception or error you saw

Uncaught SyntaxError: Unexpected token 'export'

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.1
Node: 14.15.5
Package Manager: npm 6.14.11
OS: darwin x64

Angular: 13.3.1
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, router, upgrade

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.1
@angular-devkit/build-angular   13.3.1
@angular-devkit/core            13.3.1
@angular-devkit/schematics      13.3.1
@angular/cdk                    13.3.2
@schematics/angular             13.3.1
ng-packagr                      13.3.0
rxjs                            6.6.7
typescript                      4.6.3
webpack                         5.71.0
```

### Anything else?

The mentioned script files inside scripts section of Angular.json file are main dependent files. As we have .mjs files, we are getting the error due to which app is not working

**Comment by jessicajaniuk** [comment]
This is an intentional behavioral change in v13. We switched over to ES Modules and dropped support for commonjs and UMD formats. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
