### ISSUE TITLE
control.hasError() return unexpected value

### ISSUE THREAD

**Issue by jpoyard** [angular/angular#45556]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

When control has the following errors object: `{min: 0}`
Then `control.hasError('min')` return `false` instead of `true`

When control has the following errors object: `{min: '0'}`
Then `control.hasError('min')` return `true`

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.1
Node: 16.13.1
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 13.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.1
@angular-devkit/build-angular   13.2.1
@angular-devkit/core            13.2.1
@angular-devkit/schematics      13.2.1
@angular/cli                    13.2.1
@schematics/angular             13.2.1
rxjs                            7.4.0
typescript                      4.4.4
```

### Anything else?

I propose to replace in /packages/forms/src/model/abstract_model.ts file:
```
hasError(errorCode: string, path?: Array<string|number>|string): boolean {
  return !!this.getError(errorCode, path);
}
```
by:
```
hasError(errorCode: string, path?: Array<string|number>|string): boolean {
  return this.getError(errorCode, path) != null;
}
```

**Comment by JeanMeche** [comment]
We should close it per what has been said on #24344  !
