### ISSUE TITLE
Cannot find module 'photoswipe/lightbox' or its corresponding type declarations.ts

### ISSUE THREAD

**Issue by zedL** [angular/angular#45565]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Hello,

I want to use new photoswipe 5 with Angular 13, but not get the imports to work.

![162205574-07b7aa71-ffea-4d8f-bb4c-d17236f4808b](https://user-images.githubusercontent.com/12039628/162452755-b8004aa8-54ff-4a54-9a95-26159649a27d.png)

On their [homepage](https://photoswipe.com/getting-started/) they have samples for plain javascirpt, vue, react, but not with angular.
Any idea what is to do to get it work?

Thanks

### Please provide the exception or error you saw

```true
Cannot find module 'photoswipe/lightbox' or its corresponding type declarations.ts(2307)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.2
Node: 16.13.1
Package Manager: npm 8.5.5
OS: win32 x64

Angular: 13.3.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.2
@angular-devkit/build-angular   13.3.2
@angular-devkit/core            13.3.2
@angular-devkit/schematics      13.3.2
@schematics/angular             13.3.2
rxjs                            7.5.5
typescript                      4.6.3
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
