### ISSUE TITLE
ReferenceError: HTMLElement is not defined

### ISSUE THREAD

**Issue by Amitshaale** [angular/angular#45571]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

While running SSR build I am getting the error HTMLElement is not defined I have tried the below solution.

// in server.ts

const domino = require('domino');
const fs = require('fs');
const path = require('path');
const template = fs.readFileSync('dist/shaale/browser/index.html').toString();
const win = domino.createWindow(template);

global['window'] = win;
global['document'] = win.document;
global['DOMTokenList'] = win.DOMTokenList;
global['Node'] = win.Node;
global['Text'] = win.Text;
global['HTMLElement'] = win.HTMLElement;
global['navigator'] = win.navigator;

### Please provide the exception or error you saw

```true
ReferenceError: HTMLElement is not defined
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 12
```

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
