### ISSUE TITLE
Angular 2 EXCEPTION_BINDING swallows exceptions

### ISSUE THREAD

**Issue by mark-buer** [angular/angular#4558]
For what reason does EXCEPTION_BINDING, the default ExceptionHandler, swallow exceptions instead of re-throwing them?

It certainly leads to *very* unexpected and hard to diagnose behaviour.

For a minimalistic sample that demonstrates the surprising behaviour that this default causes, please see [this example](https://github.com/mark-buer/ng2-play).

**Comment by mark-buer** [comment]
The sample code:
```typescript
import {Inject, ElementRef, DynamicComponentLoader, ComponentMetadata as Component, ViewMetadata as View, bootstrap, CORE_DIRECTIVES} from 'angular2/angular2';

@Component({
    selector: 'burner'
})
@View({
    template: `<div>Hello World</div>`,
    directives: [CORE_DIRECTIVES]
})
export class Burner {
    constructor() {
        // Yeah, raze it all to the ground. Mhuh mhuh mhuh!
        throw new Error();
    }
}

@Component({
    selector: 'root'
})
@View({
    template: `<button (click)="burn()">Burn</button>`,
    directives: [CORE_DIRECTIVES]
})
export class Root {
    constructor(@Inject(ElementRef) elementRef, @Inject(DynamicComponentLoader) dynamicComponentLoader) {
        this.elementRef = elementRef;
        this.dynamicComponentLoader = dynamicComponentLoader;
    }
    burn() {
        // The Burner component throws an exception within it's constructor...
        this.dynamicComponentLoader.loadNextToLocation(Burner, this.elementRef)
        .then((componentRef) => {
            // We don't expect this code to run... the promise above should've been rejected.
            // Yet we find the code does execute.
            console.log('wat?');
            throw new Error('crazy nightmare');
        })
        .then(() => {
            // We *definitely* don't expect this to run... checkout the exception thrown in the resolve handler above!
            // Yet we find the code does execute.
            console.log('wtf?');
        });
    }
}

bootstrap(Root);
```

The console output:
```text
EXCEPTION: Error during instantiation of Burner!.
wat?
EXCEPTION: Error: crazy nightmare
wtf?
```

**Comment by mark-buer** [comment]
And because I just discovered how easy it is to create a TypeScript+AngularJS plnkr (awesome!), [here is the sample in an online-runnable form](http://plnkr.co/edit/FBlwUcDQuzguBtZenbN1?p=preview).

**Comment by jessegood** [comment]
See https://github.com/angular/angular/issues/1489
It's more with how promises work and isn't directly related to Angular

**Comment by mark-buer** [comment]
@jessegood 
Unless I'm missing something, issue #1489 doesn't seem relevant. Please correct me if I'm wrong.

This issue is not about unhandled exceptions.

This issue is about an Angular API method, in combination with the default Angular ExceptionHandler, returning a promise that does not behave like promises should behave.

In short, running this (with the default ExceptionHandler):
```typescript
promiseReturnedFromOneOfTheAngularLoadMethods
.then(() => {
    throw new Error();
})
.then(() => {
    console.log('Something somewhere went terribly wrong');
});
```
Results in `Something somewhere went terribly wrong` being output to the console. That should NEVER happen. It breaks the promise specification.

This is crazy and unintuitive, and could be solved by either fixing whatever bug might be causing this (perhaps some ZoneJs issue) or alternatively, by changing the default ExceptionHandler (`EXCEPTION_BINDING`) to rethrow exceptions instead of swallowing them.

**Comment by mark-buer** [comment]
If I hack the Angular library, and change the default ExceptionHandler to rethrow exceptions instead of swallowing them, the promises behave as expected.

In other words, changing `platform_bindings.ts` from:
```typescript
export const EXCEPTION_BINDING =
    bind(ExceptionHandler).toFactory(() => new ExceptionHandler(DOM, false), []);
```
to:
```typescript
export const EXCEPTION_BINDING =
    bind(ExceptionHandler).toFactory(() => new ExceptionHandler(DOM, true), []);
```
appears to fix the problem.
(note that false means swallow exceptions and true means rethrow exceptions)

Which brings me to the original question I posed in this issue:
> For what reason does EXCEPTION_BINDING, the default ExceptionHandler, swallow exceptions instead of re-throwing them?

**Comment by jessegood** [comment]
I see now. My impression from the linked issue was `just log, because throwing is meaningless and/or spammy in many cases in the library`, but would have to get an official comment from the Angular team.

**Comment by mhevery** [comment]
The idea behind throwing, is that it is helpful for tests, since if something goes wrong in a test, you want an error in your test runner not a message on the console.

The exception handler is last line of defense, when an exception happened and we don't know what to do with it, so by default we log it into console. 

Are you implying that throwing is a better user experience then logging in all cases?

**Comment by LMFinney** [comment]
promiseReturnedFromOneOfTheAngularLoadMethods
    .then(() => {
        throw new Error();
    })
    .then(() => {
        console.log('Something somewhere went terribly wrong');
    })
    .catch(() => {
        console.log('I want to handle this problem, but I don't get to');
    });

Looking at this expansion of the simple example from above, it shouldn't be a matter of a last line of defense. In this case, the Promises contract is violated because an exception is handled before I get a chance to deal with it myself.

If the exception handler is getting involved in responding to errors within Promise chains, then it is inserting itself as the first line of defense. It's preventing me from adding any other lines of defense.

Maybe the bug here is that the exception handler is involved at all in Promise chains?

**Comment by LMFinney** [comment]
> In this case, the Promises contract is violated

Mea culpa. When I wrote this, I didn't realize that the ES2015 definition of Promises doesn't follow the A+ spec for Promises. The behavior I was complaining about is apparently the intended behavior of Promises in ES2015, and it's not an Angular issue at all.

**Comment by mark-buer** [comment]
@LMFinney I don't understand which aspects of promises you are referring to when you state that the specs differ between A+ and ES2015.

The promise implementations currently shipping in stable Chrome and Firefox behave as though they are compatible with the A+ spec, at least for the use-cases I've encountered.

Trying this in the browser (on a fresh page!):
```
Promise.resolve(true)
.then(function() {
    throw new Error();
})
.then(function() {
    console.log('Something somewhere went terribly wrong');
})
.catch(function() {
    console.log('I want to handle this problem, but I don\'t get to');
});
```
Logs to the console "`I want to handle this problem, but I don't get to`" as expected.

**Comment by LMFinney** [comment]
@mark-buer I was discussing this issue with someone else, and he said that TC39 chose a different implementation than that standard A+ spec. Unfortunately, I'm not sure how to parse that parse of the spec, but I can see for sure that there was debate on the implementation before it was final: https://github.com/domenic/promises-unwrapping/issues/55

**Comment by mark-buer** [comment]
@LMFinney The points at that link don't appear to have any relevance to this discussion regarding an exception thrown within a `then` handler.

**Comment by LMFinney** [comment]
@mark-buer You're right. I just tried in the node REPL. I think my original point stands, then.

**Comment by radek-holy** [comment]
I just hit this too... Try this:
```
import {Component, bootstrap} from 'angular2/angular2'

function test(where:string):void {
  Promise.resolve()
    .then(() => {throw new Error();})
    .then(() => alert(where + ": fulfilled"),
          () => alert(where + ": rejected")
  );
}

@Component({
  selector: 'my-app',
  template: ``
})
export class App {
  constructor() {
    test("inside") // Does not work.
  }
}
test("outside") // Works fine.

bootstrap(App).catch(err => console.error(err));
```

(or this Plunk if you prefer: http://plnkr.co/edit/rAlbqqW2pY6d8Z7KL639)

You'll see two alerts:
1. "outside: rejected"
2. "inside: fulfilled"

**Comment by starjumper30** [comment]
Problem can be solved by registering your own ExceptionHandler that rethrows. I have forked example from @radek-holy to show this:
http://plnkr.co/5v389CRSowSDhdPa8DXh

**Comment by mhevery** [comment]
I think the current implementation is consistent with the current mental model. The example with promises is how promises work, and hence out of our control.

**Comment by mark-buer** [comment]
Yep, I can this confirm this looks much improved in 2.0.0-beta.1.

The default behaviour of promises returned from `dynamicComponentLoader.loadNextToLocation(...)` and friends now seems sane :-)

**Comment by benjamingr** [comment]
This is not related to A+ vs. ES2015, this is only Angular being inconsistent. I'm very surprised to see @mhavery defend this - and I'm glad it was resolved.
