### ISSUE TITLE
Polish chars and angular variables in templates - IE Only

### ISSUE THREAD

**Issue by colejarczyk** [angular/angular#456]
This is a very specific bug. Variable placed after polish character is not resolved by angular. Instead it is just plain text. When I remove this char, everything is good. This happens only in Internet Explorer and only if variable is right after special char. Here is an example.

var some_variable = 1;
var currency = 'PLN';

```
ść [[ some_variable ]] # not work, output "ść [[ some_variable ]]"
zł [[ currency ]] # not work, output "zł [[ currency ]]"
sc [[ some_variable ]] # works, output "sc 1"
zl [[ currency ]] # works, output "zl PLN"
```

I'm using AngularJs version 1.3.10 with custom start and end symbol ($interpolateProvider), IE version 11 on Windows 7.

**Comment by caitp** [comment]
hey, could you re-open this on the https://github.com/angular/angular.js repository? Thanks!
