### ISSUE TITLE
KeyUp not able to stop with event.preventDefault() or event.stopPropogation()

### ISSUE THREAD

**Issue by chaxul** [angular/angular#45618]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Hello, I am using keyUp event and I have condition that if someone enter "0" it should not let them allow. and I want to use event.preventDefault() or event.stopPropogatiopn(). But with keyUp I am not able to do that. Can someone help me how can I stop keyUp event as I keyUp is best event trigger for me.

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
