### ISSUE TITLE
KeyDown event requires extra click to update input field

### ISSUE THREAD

**Issue by chaxul** [angular/angular#45617]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I am using input field as number and keyDown event with ngModel. When I enter any value it requires me to have another click to update my input field values. Can Someone help me on this. Also, input type = number is not taking any decimal values as well. I am using Angular 9. I have also tried changeDetectionStrategy as well but not worked.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
