### ISSUE TITLE
min and max validators not accepting date values

### ISSUE THREAD

**Issue by Akxe** [angular/angular#45610]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

`input[type="date"]` does not have validators for `min` and `max`.

### Proposed solution

I would propose that `min` & `max` validators should also accept `Date` or ``${number}`-`${number}`-`${number}``.

### Alternatives considered

Creating a custom validator and setting the `min` & `max` attributes manually is an option.

**Comment by AndrewKushnir** [comment]
Currently, Angular doesn't provide built-in mechanisms to work with date inputs via Forms APIs to read/write values (search for `ControlValueAccessor` on angualr.io to see the list of supported input types). The set of built-in validators can not be updated until there is a proper support on the `ControlValueAccessor` side. We do not have plans to extend the list of built-in `ControlValueAccessor`s, but Angular's architecture provides a way for you to create your own for other input types, so this can be implemented as a set of custom directives/functions in your application.
