### ISSUE TITLE
KeyDown requires one more event to update value

### ISSUE THREAD

**Issue by chaxul** [angular/angular#45620]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Hello, I have my input field as below
 **<input class="test" appTwoDecimalOnly type="number" ngModel placeholder="X%" (keyDown)="onChange()" />**
when I try to add any value in my input field my onChange function calls and it suppose to update value in real-time to my input field but it updates after second keyboardEvent. 

Expected behavior: Input field should be updated when I enter any keyboard value without requiring extra event.

Current Behavior: Input field updates value after another keyboard event. 

Also, <input type="number"> is not allow to enter decimal value meaning not able to enter "1.0"

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

I attempted to reproduce this given the information in https://stackblitz.com/edit/angular-ivy-ipoodf?file=src%2Fapp%2Fapp.component.html but everything behaves as expected. Please create a minimal reproduction in stackblitz or a github repo
