### ISSUE TITLE
[IOS] show whitespace when rotate screen with dialog

### ISSUE THREAD

**Issue by tungnguyen020394** [angular/angular#45628]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

this bug in youtube and my source code using angular.

When I rotate the screen while displaying a dialog, a space appears.

Device test: iPhone 7 (15.3), iPhone 8 (15.0)

version: ios 15

https://user-images.githubusercontent.com/22971618/163336120-a7410aee-c635-4eb9-a446-c0350242338b.MP4

**Comment by atscott** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
