### ISSUE TITLE
Devtools > Evaluate "Date" type when inspecting elements

### ISSUE THREAD

**Issue by btvanhooser** [angular/angular#45623]
### Which @angular/* package(s) are relevant/related to the feature request?

DevTools

### Description

Currently when you inspect and component that has a property that is a "Date" type you just get "<property name> -> Date()" listed to represent that property, but it would be nice to actually see what that value is

### Proposed solution

Either evaluate .toString() on the property when the value is updated, or allow the user to click the Date() as a link to pop up the current evaluation. 

### Alternatives considered

To get this information without building in an automatic or triggerable evaluation from the user, the user would need to use some sort of logging statement in the code base itself.

**Comment by crisbeto** [comment]
Maybe this is fixed already in master? I just tried building the extension locally and inspecting something with a `Date` property looks like this:

<img width="391" alt="image" src="https://user-images.githubusercontent.com/4450522/163757915-b22f9122-2551-4d38-ba96-60760a93c055.png">

**Comment by AleksanderBodurri** [comment]
Thank you @crisbeto, you're correct. Looks like this was implemented in https://github.com/angular/angular/pull/44864.

This feature will be available in the next Angular DevTools release. You can also use it today if you want to by building DevTools from `master`.
