### ISSUE TITLE
Changelog got too big, cannot be viewed anymore

### ISSUE THREAD

**Issue by EmaGht** [angular/angular#45635]
### Description

Angular's changelog in github now shows this:

![image](https://user-images.githubusercontent.com/12494403/163420090-6447886d-041b-49c6-9d79-d72f99ce7edd.png)

which cannot quench my thirst for juicy Angular updates

Can you guys come up with something?
Thanks

**Comment by AndrewKushnir** [comment]
@EmaGht thanks for reporting the problem, we'll update the changelog in https://github.com/angular/angular/pull/45638.
