### ISSUE TITLE
NgForOf incorrect behaviour with array of strings and inputs

### ISSUE THREAD

**Issue by ChrisHamilton91** [angular/angular#45647]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

The `ngForOf` directive has strange behaviour when rendering inputs linked to an array of strings. At first glance it looks like it makes your cursor jump around, but putting breakpoints on lines `9598` (`refreshView(tView, lView, templateFn, context);`) and `9602` (`rendererFactory.end();`) of `@angular/core/fesm2015/core.mjs`, you can see that Angular is actually generating a new input, causing the list to grow and other inputs to move, and then deleting another input. This does not seem to be the case when using objects. 

You might say I should add a trackBy function to track by index, but the thing is, this behaviour is solved by passing in ANY trackBy function, even a void one. Surely if a void trackBy function fixes this issue, then it should just work by default, otherwise, you should be able to just add a flag to the directive to make this example work.

Here's how to reproduce:
```html
<div *ngFor="let val of array; let i = index">
  <input [(ngModel)]="array[i]" />
</div>
```
```typescript
export class OneComponent {
  array = '000000'.split('');
}
```
Then try to type into the inputs.

For whatever reason this works fine:
```html
<div *ngFor="let val of array; let i = index; trackBy: trackByFn">
  <input [(ngModel)]="array[i]" />
</div>
```
```typescript
export class OneComponent {
  array = '000000'.split('');
  trackByFn() {}
}
```

Here's a picture of the intermediate extra input while debugging - I typed 1 into index 2, it moved down to index 3, and then there were two index 5s.

![ngForBug](https://user-images.githubusercontent.com/60244464/163540388-653a4b7d-2a08-492a-8e4e-d94138934408.png)

The end result looks like this - having 1s in two inputs instead of one, the focus moves down an input as well.

![ngForBug2](https://user-images.githubusercontent.com/60244464/163540962-ff55303e-b26d-49bb-b1d5-118ebce6a7de.png)

As far as I can tell, with an array of objects this weird intermediate input doesn't appear, so what gives? Why does passing ANY trackBy function produce correct behaviour?

---

**Update: you can actually reproduce this error with objects:**

```html
<div *ngFor="let value of objs; let i = index">
  <input [ngModel]="objs[i].v" (ngModelChange)="setObj(i, $event)" />
</div>
```
```typescript
export class OneComponent {
  obj = {v: '0'};
  objs = [this.obj, this.obj, this.obj, this.obj];

  setObj(i: number, value: string) {
    this.objs[i] = {v: value};
  }
}
```

The bug is reproducible as long as the trackBy function returns the same value for any two entries in the array. So weird behaviour can occur with any duplicate values.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-wjkczw?file=src/app/app.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.2
Node: 16.14.0
Package Manager: npm 8.6.0
OS: win32 x64

Angular: 13.3.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.2
@angular-devkit/build-angular   13.3.2
@angular-devkit/core            13.3.2
@angular-devkit/schematics      13.3.2
@schematics/angular             13.3.2
rxjs                            7.5.5
typescript                      4.6.3
```

**Comment by pkozlowski-opensource** [comment]
This is _exactly_ the use-case for `trackBy`, more info in https://angular.io/api/core/TrackByFunction

**Comment by ChrisHamilton91** [comment]
@pkozlowski-opensource that use case describes an object with a unique identifier, not an array of primitives. It also specifies that the funciton needs to return unique value for all unique inputs. So why does passing an empty function fix the issue? Clearly that is not the intention of trackBy.

**Comment by ChrisHamilton91** [comment]
I have a fix for this where I change the default trackBy function to this:

```typescript
const trackByIdentityOrIndex =
    (index: number, item: any) => {
      if (typeof item === 'object') return item;
      return index;
    }
```

I think this should be the default behaviour, because duplicate primitives are normally allowed in an iterable. As it is now, duplicate primitive values cause undefined behaviour, since change detection will associate whichever item happens to be the first entry under that key.

This prevents all the incorrect behaviour from duplicate primitive keys. Change detection will no longer try to guess that a primitive value has been moved or not, it will only update the values. The downside is that you lose some functionality when using an array of unique primitive values like `[0,1,2,3]`. Change detection won't be able to keep track of a value being moved from one index to another, or a value being added / removed at an existing index.

The thing is though, if I change `[0,1,2]` to `[2,0,1]` it's impossible to know whether I moved the values or I just did some math on them. Another example is going from `[0,1,1,1,1,1,2]` to `[0,1,1,1,1,2]` I removed a one from the middle but which one? You can't know, so we shouldn't see it as an element being removed, rather just the values at each index changing.

To whoever this concerns, let me know what you think.

**Comment by mlc-mlapis** [comment]
@ChrisHamilton91 The `trackBy` should always return a unique identity of the item. Items, like `[0,1,1,1,1,1,2]`, don't have a sense. The recommendation is to use a unique and unchangeable value, similar to a primary index in the database world.

**Comment by ChrisHamilton91** [comment]
@mlc-mlapis Hmmm, I think it's a bit off to not allow duplicate primitives in an iterable by default. It's very unintuitive and produces undefined behaviour for unaware users.

**Comment by mlc-mlapis** [comment]
@ChrisHamilton91 But duplicated primitives would create strange behavior in DOM manipulations. What is the concrete case that you are trying to implement?

**Comment by ChrisHamilton91** [comment]
@mlc-mlapis The use case from the issue. Two way binding on a list of inputs and their string values. The default behaviour as it is now causes strange DOM behaviour (see the stackblitz above). The solution I'm proposing is essentially a no-op for DOM manipulations, just an update of the value. Exactly the same as updating a property on an object.

**Comment by mlc-mlapis** [comment]
@ChrisHamilton91 Hmm, it's simply a wrong assumption. I think that you are trying to solve something, that doesn't have an objective justification. Sorry.

![image](https://user-images.githubusercontent.com/5693835/163725446-8f70bea8-4e5e-4a1e-ae5f-7deccc294421.png)

**Comment by ChrisHamilton91** [comment]
@mlc-mlapis Have you looked at the stackblitz?

**Comment by mlc-mlapis** [comment]
@ChrisHamilton91 Ops, I understand now. The suggested change of `trackByIdentity` to:

```
const trackByIdentityOrIndex = (index: number, item: any) => {
   if (typeof item === 'object') return item;
   return index;
}
```

seems logical, then. 😄

**Comment by ChrisHamilton91** [comment]
Ah, glad you agree!

**Comment by ChrisHamilton91** [comment]
So after looking into this, the current operations are:

- add empty input @ index 2
- delete last input in list
- update index 2 to '1'

When it should be:

- delete input @ index 2
- add empty input @ index 2
- update index 2 to '1'

The focus should actually be expected to disappear entirely, since it is considered a new item. You would have to track by index to maintain focus, in which case change detection would no longer track add / remove / moves - due to the item's `trackById` always being the same for each index.

**Comment by felixgeissler** [comment]
> 

I still can't wrap my head around, why iterating over primitives will not work as expected. I can imagine a lot of simple cases, where a basic "todo list" behaviour is desired. Providing a `trackBy` function doesn't seem to solve this issue for primitives. I guess highlighting this behaviour in the documentation for NgFor would be a good idea.

Here is my minimal reproduction example:
[https://stackblitz.com/edit/stackblitz-bug-ngfor-reference](https://stackblitz.com/edit/stackblitz-bug-ngfor-reference)

**Comment by JeanMeche** [comment]
The issue doesn't reproduce with the new `@for` block. We'll consider this as fixed.
