### ISSUE TITLE
Types of property 'directives' are incompatible. When using RouterLink and RouterOutlet

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#4564]
In alpha.38/39 I started seeing an issue when compiling against the new typing files.

Specifically I get an error when adding RouterLink and RouterOutlet to the directives array.

There seems to be a miss match between the types expected in the directives array
Did something related to directive definitions change?

I am not doing anything special - other than populating the array with injected directives.

Also, if I change the typings from
```
directives?: Array<Type | any[]> to 
directives?: any
```
it compiles fine.

I am using TypeScript 1.6

tsc --watch -m commonjs -t es5 --emitDecoratorMetadata --experimentalDecorators --jsx react app.ts

Here is a link to my code: https://github.com/thelgevold/angular-2-samples/blob/master/app.ts

Error message:
error TS2345: Argument of type '{ templateUrl: string; directives: InjectableReference[]; }' is not assignable to parameter of type '{ templateUrl?: string; template?: string; directives?: (Type | any[])[]; pipes?: (Type | any[])[...'.
  Types of property 'directives' are incompatible.
    Type 'InjectableReference[]' is not assignable to type '(Type | any[])[]'.
      Type 'InjectableReference' is not assignable to type 'Type | any[]'.
        Type 'InjectableReference' is not assignable to type 'any[]'.
message TS6042: Compilation complete. Watching for file changes.

**Comment by thelgevold** [comment]
Seems to perhaps be related to adding 
```[RouterOutlet, RouterLink]``` to the directives array.

**Comment by thelgevold** [comment]
A solution is to instead import ROUTER_DIRECTIVES and add that to the directives array.

**Comment by r-park** [comment]
I've experienced this as well. I've temporarily added `<any>` :
```javascript
@View({
  directives: <any>[
    RouterOutlet
  ]
})
```

**Comment by jeffbcross** [comment]
+1 I ran into this, too, when using directives individually.

**Comment by btford** [comment]
Hm, this seems like an issue with typings. @alexeagle @mprobst – can you offer any advice?

**Comment by thelgevold** [comment]
Yeah, it's just a typings issue since I can get around it by changing the type to 'any' or just inject ROUTER_DIRECTIVES. There are no runtime issues.
In general I don't mind using "umbrella" constructs like ROUTER_DIRECTIVES or CORE_DIRECTIVES, so this is not a big deal to me.   
I basically just added this issue for awareness in case other developers come across it.

**Comment by btford** [comment]
I think (hope!) we can improve the experience for the next dev who runs into this issue.

**Comment by mprobst** [comment]
@btford this looks as if `InjectableReference` was not a subtype of `Type`. It is not a subtype of `any[]` (because that is an `Array`). I actually cannot find that type at all in angular2, am I looking in the wrong place?

**Comment by jeffbcross** [comment]
@mprobst `InjectableReference` is only defined in our d.ts template https://github.com/angular/angular/blob/master/docs/typescript-definition-package/templates/angular2/angular2.d.ts.template.html

**Comment by mprobst** [comment]
@jeffbcross I see. Well, `InjectableReference` is an empty interface (i.e. no requirements on its type), whereas `Type` is `Function` essentially, so that explains why these are not compatible.

I don't know enough about the DI to say what's the right way to fix that, though. You could make `InjectableReference` extend `Type`, or make `Type` just a marker/empty interface. Maybe @vsavkin has an opinion?

**Comment by btford** [comment]
I think this has since been resolved.

@thelgevold can you please let me know if this is still an issue? If so, I'll happily re-open this.

Thanks!

**Comment by thelgevold** [comment]
@btford I have confirmed that this is fixed. Thanks!

**Comment by agentcodesmith** [comment]
fuck

**Comment by milap123** [comment]
Hahahahahahahahah
