### ISSUE TITLE
Form Builder Chain

### ISSUE THREAD

**Issue by wokier** [angular/angular#45649]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

Hi

I have made a fluent api for form builder.
Especially because the addControl method does not return the FormGroup

### Proposed solution

https://gist.github.com/wokier/46ddb0aa49ddf104b456e0f1e90a99bf
Usage
```
return this.fbc.group({
      origine: [data?.origine],
      destination: [data?.destination : null],
    }).add('another', this.manuallyCreatedController, data.another)
      .add('yetanother', this.alsoManuallyCreatedController.selectedCtrl, data?.yetanother)
      .build();
```

### Alternatives considered

```
FormGroup formGroup = this.fb.group({
      origine: [data?.origine],
      destination: [data?.destination : null],
    });
formGroup.add('another', this.manuallyCretedController, data.another);
formGroup.add('yetanother', this.alsoManuallyCretedController.selectedCtrl, data?.yetanother);
return formGroup;
```

**Comment by dylhunn** [comment]
This is neat, you should consider publishing it on npm! We are unlikely to change the FormBuilder API in this way though.

**Comment by wokier** [comment]
Hi

A third approach would be to have the formGroup returned on the `add` call
It is a non-breaking change.
It would be used this way
```
return this.fb.group({
      origine: [data?.origine],
      destination: [data?.destination : null],
    }).add('another', this.manuallyCreatedController, data.another)
      .add('yetanother', this.alsoManuallyCreatedController.selectedCtrl, data?.yetanother);
```
