### ISSUE TITLE
angular library v13 adding :local in all component 

### ISSUE THREAD

**Issue by ietabhi** [angular/angular#45667]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Angular library compilation is adding :local for all component CSS .
In one component each css is under :local() which is causing issue after upgraded current app to 13x version.

No documentation available for :local pseudo class 

Compiled code used .mjs file :- 

[_ngcontent-%COMP%]:local

### Please provide a link to a minimal reproduction of the bug

Issue in generated code, No link

### Please provide the exception or error you saw

```true
No Error - UI CSS not getting applied in parent App
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
dependencies:- 

"@angular/animations": "^13.2.4",
"@angular/common": "^13.2.4",
"@angular/compiler": "^13.2.4",
"@angular/core": "^13.2.4",
"@angular/forms": "^13.2.4",
"@angular/platform-browser": "^13.2.4",
"@angular/platform-browser-dynamic": "^13.2.4",
"@angular/router": "^13.2.4",
"rxjs": "^6.5.5",
"tslib": "^2.0.0",
"zone.js": "~0.11.4"

devDependencies:--


"@angular-devkit/build-angular": "~13.2.5",
"@angular-eslint/builder": "13.1.0",
"@angular-eslint/eslint-plugin": "13.1.0",
"@angular-eslint/eslint-plugin-template": "13.1.0",
"@angular-eslint/schematics": "13.1.0",
"@angular-eslint/template-parser": "13.1.0",
"@angular/cli": "^13.2.5",
"@angular/compiler-cli": "^13.2.4",
"ng-packagr": "^13.2.1",
"typescript": "~4.5.5"
```

### Anything else?

No

**Comment by JoostK** [comment]
Please provide a reproduction.

**Comment by ietabhi** [comment]
able to fix with latest angular.json and tscofig skeleton project

**Comment by JoostK** [comment]
Closing as no reproduction has been provided and you mentioned you managed to resolve the issue.
