### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Failed to fetch

### ISSUE THREAD

**Issue by shrek-kurata** [angular/angular#45664]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

```
core.mjs:6485 ERROR Error: Uncaught (in promise): TypeError: Failed to fetch
TypeError: Failed to fetch
    at zone.js:1505:1
    at proto.<computed> (zone.js:973:1)
    at PresentationComponent.<anonymous> (presentation.component.ts:43:21)
    at Generator.next (<anonymous>)
    at tslib.es6.js:76:1
    at new ZoneAwarePromise (zone.js:1427:1)
    at __awaiter (tslib.es6.js:72:1)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.3
Node: 16.10.0
Package Manager: npm 7.22.0
OS: darwin arm64

Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1303.3
@angular-devkit/core         13.3.3
@angular-devkit/schematics   13.3.3
@schematics/angular          13.3.3
typescript                   4.6.3
```

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

---

The `fetch` call originates from your own code; it is unclear how Angular is involved here.
