### ISSUE TITLE
Don't destroyAfterEach on Focused or Failed Tests

### ISSUE THREAD

**Issue by rgant** [angular/angular#45662]
# 🚀 Feature request

Don't remove the host element from the DOM when a test fails, nor when it is focused (`fit`/`fdescribe`). 

### Command (mark with an `x`)

- [x] test

### Description

Trying to debug DOM tests it is frequently helpful to actually have the failing DOM to inspect in the test browser after failing. By destroying the host element we lose access to this value.

### Describe the solution you'd like

It would be great if we could only have this feature for CI and not while actively developing tests.

### Describe alternatives you've considered

Trying to find some way to give `ng test` a flag or some other setting that lets me toggle off `destroyAfterEach` during local development and on again during CI. But no luck. Ideas welcome.

**Comment by H4TIEL** [comment]
Issue can be closed

**Comment by jessicajaniuk** [comment]
The best solution here is to add a debugger statement before the end of your test to prevent destroy.
