### ISSUE TITLE
There is an html tag in the Angular install sample

### ISSUE THREAD

**Issue by JenPeleva** [angular/angular#45676]
### Description

In this article https://angular.io/guide/setup-local, the install globally sample has an html tag inside it:

"npm install -g @angular/cli<aio-angular-dist-tag class="pln"></aio-angular-dist-tag"

### What is the affected URL?

 https://angular.io/guide/setup-local

### Please provide the steps to reproduce the issue

Go to **Install the Angular CLI**

### Please provide the expected behavior vs the actual behavior you encountered

The correct console message shouldn't contain html

### Please provide a screenshot if possible

https://www.screencast.com/t/p2lQs2vt

**Comment by AndrewKushnir** [comment]
Thanks for reporting the problem, the issue should be resolved in PR #45644.
