### ISSUE TITLE
Angular Library issue for paths aliases declared in tsconfig.json not working: Module not found: Error: Can't resolve

### ISSUE THREAD

**Issue by mobilityvalley** [angular/angular#45677]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

I'am developing an Angular (v12) library and a small app to test it that have the following structure:

    ├── projects
    │   ├── my-app
    │   │   ├── karma.conf.js
    │   │   ├── src
    │   │   ├── tsconfig.app.json
    │   │   └── tsconfig.spec.json
    │   └── my-lib
    │       ├── README.md
    │       ├── karma.conf.js
    │       ├── ng-package.json
    │       ├── node_modules
    │       ├── package-lock.json
    │       ├── package.json
    │       ├── src
    │       ├── tsconfig.lib.json
    │       ├── tsconfig.lib.prod.json
    │       └── tsconfig.spec.json
    └── tsconfig.json

In the root ./tsconfig.json I declare paths aliases (as I understand to be recognized by VS Code):

     {
      "compileOnSave": false,
      "compilerOptions": {
        "baseUrl": "./",
        "outDir": "./dist/out-tsc",
        "forceConsistentCasingInFileNames": true,
        "strict": true,
        "noImplicitOverride": true,
        "noPropertyAccessFromIndexSignature": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "sourceMap": true,
        "paths": {
          "my-lib": [
            "dist/my-lib/my-lib",
            "dist/my-lib"
          ],
          "@services/*": [
            "projects/my-lib/src/lib/services/*"
          ]
        },
        "declaration": false,
        "downlevelIteration": true,
        "experimentalDecorators": true,
        "moduleResolution": "node",
        "importHelpers": true,
        "target": "es2017",
        "module": "es2020",
        "lib": [
          "es2020",
          "dom"
        ]
      },
      "angularCompilerOptions": {
        "enableI18nLegacyMessageIdFormat": false,
        "strictInjectionParameters": true,
        "strictInputAccessModifiers": true,
        "strictTemplates": true
      }
    }

In the ./projects/my-lib/tsconfig.lib.json I declare again the paths aliases (as I understand to be interpreted by the ng-packagr compiler):

    {
        "compileOnSave": false,
        "compilerOptions": {
          "baseUrl": "./",
          "outDir": "./dist/out-tsc",
          "paths": {
            "@services/*": [ "src/lib/services/*" ],
          },
          "sourceMap": true,
          "declaration": false,
          "module": "es2015",
          "moduleResolution": "node",
          "emitDecoratorMetadata": true,
          "experimentalDecorators": true,
          "target": "es5",
          "typeRoots": [
            "node_modules/@types"
          ],
          "lib": [
            "es2017",
            "dom"
          ]
        }
      }

The ./angular.json is referencing the tsconfig.lib.json:

    {
      "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
      "version": 1,
      "newProjectRoot": "projects",
      "projects": {
        "my-lib": {
          "projectType": "library",
          "root": "projects/my-lib",
          "sourceRoot": "projects/my-lib/src",
          "prefix": "lib",
          "architect": {
            "build": {
              "builder": "@angular-devkit/build-angular:ng-packagr",
              "options": {
                "project": "projects/my-lib/ng-package.json"
              },
              "configurations": {
                "production": {
                  "tsConfig": "projects/my-lib/tsconfig.lib.prod.json"
                },
                "development": {
                  "tsConfig": "projects/my-lib/tsconfig.lib.json"
                }
              },
              "defaultConfiguration": "production"

The Library is compiling without any errors.

When I import the library in my-app and I want to import a service for example, It does not resolve the paths aliases :

    ./node_modules/my-lib/fesm2015/my-lib.mjs:11:0-56 - Error: Module not found: Error: Can't resolve '@services/my-lib/my-lib.service' in '/Users/***/projects/ANGULAR/angular-tour-of-heroes/node_modules/my-lib/fesm2015'
        
        Error: node_modules/my-lib/lib/custom-page/custom-page.component.d.ts:2:30 - error TS2307: Cannot find module '@services/my-lib/my-lib.service' or its corresponding type declarations.
        
        2 import { MyLibService } from '@services/my-lib/my-lib.service';
    
    Error: node_modules/my-lib/lib/custom-page/custom-page.component.d.ts:2:30 - error TS2307: Cannot find module '@services/my-lib/my-lib.service' or its corresponding type declarations.
    
    2 import { MyLibService } from '@services/my-lib/my-lib.service';

I tried any combinations of configuration in the world, paths seems to be impossible to be used in an Angular Library

### Please provide the exception or error you saw

```true
./node_modules/my-lib/fesm2015/my-lib.mjs:11:0-56 - Error: Module not found: Error: Can't resolve '@services/my-lib/my-lib.service' in '/Users/***/projects/ANGULAR/angular-tour-of-heroes/node_modules/my-lib/fesm2015'
        
Error: node_modules/my-lib/lib/custom-page/custom-page.component.d.ts:2:30 - error TS2307: Cannot find module '@services/my-lib/my-lib.service' or its corresponding type declarations.  
2 import { MyLibService } from '@services/my-lib/my-lib.service';   
Error: node_modules/my-lib/lib/custom-page/custom-page.component.d.ts:2:30 - error TS2307: Cannot find module '@services/my-lib/my-lib.service' or its corresponding type declarations.
2 import { MyLibService } from '@services/my-lib/my-lib.service';
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.1.2
Node: 16.13.1
Package Manager: npm 8.1.2
OS: darwin arm64

Angular: 13.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
ng-packagr                      13.1.2
rxjs                            7.4.0
typescript                      4.5.4
```

**Comment by JoostK** [comment]
If you can share a runnable reproduction then I can take a look, although this is most likely not specific to Angular. Libraries in general shouldn't depend on path mappings, as this means that any application that uses such libraries would also need a path mapping configuration meaning that the library is not self-contained. It effectively means that libraries should use relative imports into source files within the same entry-point of a library, _not_ absolute path-mapped module specifiers.

**Comment by IslombekMe** [comment]
I'm actually facing the same issue. @mobilityvalley have you found a workaround then?

**Comment by Marcel0024** [comment]
Same issue here @IslombekMe did you find a way?

**Comment by IslombekMe** [comment]
@Marcel0024 I ended up using secondary entry point, so `@services` ended up becoming `@my-library-name/services`.
read a brief here https://github.com/ng-packagr/ng-packagr/blob/main/docs/secondary-entrypoints.md

if you need help, reach me out at my mail - Islombekhasanov at gmail dot com

**Comment by mobilityvalley** [comment]
> I'm actually facing the same issue. @mobilityvalley have you found a workaround then?

I ended up by not using path aliases in libraries. After reading a lot about it, the ng-packgr does not support aliases and it is not a good practice in library.
