### ISSUE TITLE
Emulated view encapsulation incorrectly transforms CSS that uses `:is()` or `:where()`

### ISSUE THREAD

**Issue by ChrisTM** [angular/angular#45686]
### Which @angular/* package(s) are the source of the bug?

compiler, Don't known / other

### Is this a regression?

No

### Description

When using emulated view encapsulation, component CSS that uses the `:is` or `:where` pseudo class selector functions gets compiled incorrectly.

# Example 1

Consider the following 2 selectors, which differ only in the number of items inside of `:is`:

```css
:is(.foo) {}
:is(.foo, .bar, .baz) {}
```

I expected each item in the `:is` selector list to be transformed the same, but the first and last items are treated differently from the middle items. This is the compiled result:

```css
[_ngcontent-uly-c97]:is(.foo) {}
[_ngcontent-uly-c97]:is(.foo, .bar[_ngcontent-uly-c97], .baz)[_ngcontent-uly-c97] {}
```

# Example 2

When used before or after `:host`, the number of items *inside* of `:is` unexpectedly affects the presence of an  `[_ngcontent]` qualifier *outside* of `:is`. The qualifier is missing for 1 item, but added for >1 item. This component CSS:

```css
:is(.foo) :host {}
:is(.foo, .bar) :host {}

:host :is(.foo)  {}
:host :is(.foo, .bar)  {}
```

Compiles to:

```css
:is(.foo)   [_nghost-kfp-c134] {}
[_ngcontent-kfp-c134]:is(.foo, .bar)   [_nghost-kfp-c134] {}

[_nghost-kfp-c134]   [_ngcontent-kfp-c134]:is(.foo)  {}
[_nghost-kfp-c134]   [_ngcontent-kfp-c134]:is(.foo, .bar)[_ngcontent-kfp-c134]  {}
```

# Reproduction

https://stackblitz.com/edit/angular-ivy-yc96o6?file=src/app/app.component.css demonstrates a live reproduction of this issue.

For my specific use case, I had a selector that looked like`:is(a, b, c) :host`. I was able to work around the problem by rewriting it to either of `:host-context(a, b, c) :host` or `a :host, b :host, c :host` (both compile to the same output). But in general, using `:is` and `:where` seems either unsupported or broken. If it's unsupported, I think it would be helpful if the compiler threw an error because the current behavior is hard to predict and does not seem useful.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-yc96o6?file=src/app/app.component.css

### Please provide the environment you discovered this bug in (run `ng version`)

```true
I'm not using `ng`, so I can't provide `ng version` output. But the reproduction in StackBlitz is using @angular/* packages at version 13.3.3.
```

**Comment by dario-piotrowicz** [comment]
good catch @ChrisTM :slightly_smiling_face: , I've found the bug causing this issue, it does look pretty small and easy to fix

I've practically solved it, I need to check things, add unit tests and open a PR, I should hopefully be able to do it in the next few days :slightly_smiling_face::+1: 

(@dylhunn , @JoostK if either of you could assign me to this issue that'd be awesome :pray: :slightly_smiling_face: :bow:)

**Comment by dario-piotrowicz** [comment]
Thanks @JoostK! :smiley:

**Comment by JWess** [comment]
Here is an example of what isn't working in my project:

```
.x ::ng-deep :is(.y, .z) { }
```
Compiles to:
```
.x[_ngcontent-fuj-c336] :is(.y, .z)[_ngcontent-fuj-c336] { }
```

**Comment by montella1507** [comment]
Hey @dario-piotrowicz  what is the status please? It makes :dark utility classes not usable in Tailwind + Angular... Is it possible to release a fix to this issue?

**Comment by JeanMeche** [comment]
@montella1507 Do you think my PR #49169 solves your issue ?

**Comment by montella1507** [comment]
> @montella1507 Do you think my PR #49169 solves your issue ?
<img width="740" alt="image" src="https://github.com/angular/angular/assets/10418323/efe01968-49f9-4c10-ad1e-58fc142b68b3">
I have manually monkeypatched these 3 files based on your commit 
<img width="674" alt="image" src="https://github.com/angular/angular/assets/10418323/569a0abe-4712-49f3-8117-e92f1617a911">

<img width="688" alt="image" src="https://github.com/angular/angular/assets/10418323/79e5b555-af39-4049-89d5-c8fa51a928d1">


however.. i dont think it solved my prpoblem

**Comment by montella1507** [comment]
<img width="502" alt="image" src="https://github.com/angular/angular/assets/10418323/3f9ea9e0-b070-4da1-b2e9-1fe801f6ce04">
<img width="680" alt="image" src="https://github.com/angular/angular/assets/10418323/cad79ef4-918d-46a6-a11b-4d90b9e558fd">

**Comment by montella1507** [comment]
But you are close 
:-)

Generated from your code (not working - misaligned whitespace):
:is(.dark )[_nghost-hvk-c87]

Working:
:is(.dark) [_nghost-hvk-c87]

**Comment by JeanMeche** [comment]
@montella1507 Can you check with the change I just made in #49169. It should fix your issue !
