### ISSUE TITLE
Ability to find out where router navigation came from

### ISSUE THREAD

**Issue by ychaikin** [angular/angular#45685]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

The angular router lacks what the "referer" header does in HTTP, so to speak.

### Proposed solution

Create `previousRoute` as part of the API.

### Alternatives considered

None.

**Comment by atscott** [comment]
What is the use-case for this? The Angular router provides access to the previous successful navigation through `Router.getCurrentNavigation().previousNavigation`: https://angular.io/api/router/Navigation#previousNavigation

Of course, this is only available when a navigation is ongoing, but you could also save this value somewhere by subscribing to the events and filtering to `NavigationEnd`.

Is there a reason you can't use the existing APIs to accomplish your goal?

**Comment by ychaikin** [comment]
@atscott Thanks for the response.

The use case, which I have encountered quite a number of times, is when you want to do something inside of a component based on where the navigation was triggered from. By the time you are dealing with that type of logic, that information is not available in the current Router API.

In the most recent use case, I was using NGRX and triggering an "executeSearch" action from multiple places (some components, some not). The effect that handles that action is quite disconnected from the component and the "executeSearch" action can be triggered in many different ways, some because of navigation, some not. The solution to this is a bit of a "pretzel" where I have to create yet another effect that I listen to the router navigation event and then trigger some other chain of actions based on that. The whole chain is unnecessarily complicated simply because I can't look into `this.router.previousUrl` in the "executeSearch" action and change the logic based on that.

So, yes, of course, it is possible to get around this lack of "previous" and I can even create a state which keeps track of previously successful navigation and keep updating it. I am asking precisely that I shouldn't have to. 

This is especially true since this comes up so often (not sure why I haven't ventured to create an issue for this until now).

It seems the API is great at telling you information while navigation is ongoing, thus `getCurrentNavigation()`, which allows you to look at previous navigation "mid-flight". This is great if you want to code to some functionality/decision that SHOULD be occurring mid-flight of navigation, not when navigation has already completed.

When it comes to information that's kept in the router "state", i.e., the `Router`, only the current `url` property is provided. `previousUrl` or some such would help a lot. I just feel like the HTTP "referer" header data has been lost here (i.e., the developer has to implement it).

Let me know what you think.

**Comment by atscott** [comment]
@ychaikin Thanks for the thoughtful response. That's totally fair and given that `previousSuccessfulNavigation` is already available in the public API (but only during an ongoing navigation), I don't think it's that significant of a change to the public API surface to make the value accessible all the time. That is to say, when looking informations that is private implementation detail, I want to ensure that the underlying details are stable enough to expose as public API. Since this is already exposed, there wouldn't be any additional support burden on maintaining the behavior/preventing breakages.

**Comment by ychaikin** [comment]
@atscott Thanks!

**Comment by angelnikolov** [comment]
@atscott @ychaikin I just stumbled upon this issue. We were basically using both `this.router.getCurrentNavigation().previousNavigation` and a custom `state` paramter accessed through `this.router.getCurrentNavigation().extras.state['parameter']` to figure out the correct back route of our application.
I also found https://github.com/angular/angular/issues/48744 and from there I understand that in Angular 15 we can no longer use `getCurrentNavigation()` for nested routes, but should rather use `location.getState()` to extract the state parameters via the history API. However, how can we go about getting the `previousNavigation` now? That's not provided by the location service and we seem to be in a dead end with our migration.

**Comment by atscott** [comment]
@angelnikolov Ah, that's interesting. Exposing the `lastSuccessfulNavigation` would probably make upgrading easier. For me, that would bump the priority here. It's unfortunate that this didn't come up earlier since we just released v15.2 so this feature can't go in until v16 at the earliest now.

> Is using the private (this.router as any).navigationTransitions.lastSuccessfulNavigation a good resolution for this?

I could never recommend accessing private API unless you're prepared to have it break at any time without a replacement. Is there a reason you couldn't just track this information in your own service by subscribing to `NavigationEnd`/`ActivationEnd`?

**Comment by angelnikolov** [comment]
@atscott Thanks!

Reason is that we wanted to avoid an extra service for something that could be derived based on a `state` parameter and the `previousNavigation` object.

Basically, what we do in our component is show a back button, and we only show it if we are coming from a really specific previous route.

So what we do is pass `goBackAware` state parameter when navigating from that said page. Then in the next page we check if `goBackAware` is passed and then we fetch the `previousNavigation.extractedUrl` which we use for actually navigating back to the previous page.
We could of course pass the url as a state parameter, but then we gotta do that everywhere where we use this back button, while the way we've done it is that it's automatic.
