### ISSUE TITLE
[alpha39] Error message excessively long when missing builtin directives

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular#4569]
When missing `NgFor`, `NgIf`, for example, throws in both alpha38 and alpha39

```
EXCEPTION: Template parse errors:
Can't bind to 'ngForOf' since it isn't a known native property in Hello > div:nth-child(1)[*ng-for=#item of items]
Property binding ngForOf not used by any directive on an embedded template in Hello > div:nth-child(1)[*ng-for=#item of items]
```
*Note* the message will be as long as it can depending on your html structure. It will print the entire tree.

The error message above represents this piece of code

```typescript
@View({template: `<div *ng-for="#item of items"></div>`}) // no NgFor directive
```

While in alpha37 the error is much shorter

```
EXCEPTION: Can't bind to 'ngForOf' since it isn't a known property of the '<template>' element and there are no matching directives with a corresponding property
```

Repro with a39 : http://plnkr.co/edit/exK8Nj?p=preview 
Repro with a37 : http://plnkr.co/edit/K0R54f?p=preview

PS: When NgFor or NgIf are empty there's no error message, is that intended?

**Comment by tbosch** [comment]
I am working on a new parser that will output the source line/column and
with that make the reporting a lot nicer...

**Comment by ericmartinezr** [comment]
@tbosch thanks, I'm closing it as a dup of https://github.com/angular/angular/issues/4471
