### ISSUE TITLE
Navigating back while having querry params unsyncs `Title` service from tab's title actual value.

### ISSUE THREAD

**Issue by pokermanx** [angular/angular#45694]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

No

### Description

Having dynamic querry parameters within the same tab title, navigating back will change the tab title value to previuos one while the tab title from `title.getTitle()` will return previously setted one. Resetting it dirrectly is not possible, since (as far as I've tried), it is compared with current one (which is invalid) thus is not updated.
Problems forces you to set some character to the end and set the valid title back like
`this.title.setTitle(title + '|');`
`this.title.setTitle(title);`

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.6
Node: 14.17.5
Package Manager: npm 6.14.14
OS: win32 x64

Angular: 13.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.6
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.2.6
@angular-devkit/schematics      13.2.6
@angular/cli                    13.2.6
@schematics/angular             13.2.6
rxjs                            7.5.5
typescript                      4.5.5
```

**Comment by atscott** [comment]
Could you please provide a reproduction? Note that the title service directly accesses the `document.title` to get and set the value so this could very likely be an application or browser issue. In fact, I can't really imagine there being anything actionable here for the title service itself given the simplicity of its implementation:

https://github.com/angular/angular/blob/47e5b056ecd3c8f01d9a3c91a78bc25acccbf292/packages/platform-browser/src/browser/title.ts#L36-L46

There's no attempt to interact/interface with the browser history here so it's not something that's being fumbled or mismanaged in its implementation.

**Comment by jessicajaniuk** [comment]
I'm sorry but we can't reproduce the problem you are reporting. We require that reported issues have a minimal reproduction that showcases the problem.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template that include info on how to create a reproduction using our template.
