### ISSUE TITLE
HostListener on specific keys negates effect of ngZoneEventCoalescing

### ISSUE THREAD

**Issue by bene-starzengruber** [angular/angular#45698]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

We can use `ngZoneEventCoalescing` to group change detection cycles of events into an animationFrame
So if we have a listener like this on a component that appears multiple times in the dom

```
  @HostListener('document:keydown', ['$event'])
  onKeydown(event: KeyboardEvent) {
    ...
  }
```
there is only one change detection cycle triggered on each keydown event

but if we now specify the key, we loose this effect and there is one change detection cycle per component
```
  @HostListener('document:keydown.a')
  onKeydown() {
    ...
  }
```

I've provided a stackblitz link with both variations in the `BoxComponent` and added logging for the change detection cycles to the console.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-qza2cj?file=src%2Fmain.ts

### Anything else?

I guess the key event manager plugin causes the cycles here 

https://github.com/angular/angular/blob/b5ab7aff433a67cddaa55e621d17b1a1b07b57c2/packages/platform-browser/src/dom/events/key_events.ts#L176-L182

if we activate the `ngZoneRunCoalescing` flag as well, then we have the desired behaviour again.
the question is if the event plugin should be modified so that it already applies to the `ngZoneEventCoalescing` flag like one would expect from the name.

**Comment by JiaLiPassion** [comment]
@dylhunn , yes, not only `ngZoneEventCoalescing`, there are some other behavior differences between `keyevent` and the others. The keyevent handler will always run into NgZone and the other event listeners will run into the ngZone or root Zone depends on where the component is initialized. 
Maybe we should unify the keyevent to be the same with EventManagerPlugin...
