### ISSUE TITLE
Facing issue on updating the angular packages

### ISSUE THREAD

**Issue by Ajithamarlin** [angular/angular#45713]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler, upgrade

### Is this a regression?

No

### Description

Facing issue on updating the angular packages

steps to replicate:

1. Download the attached angular sample.
2. Give npm install command.

Facing below issue
![image](https://user-images.githubusercontent.com/69242214/164467816-1ba46599-400c-44ff-8577-52dad9335f20.png)
[angular app.zip](https://github.com/angular/angular/files/8531389/angular.app.zip)

### Please provide the exception or error you saw

```true
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: envoy-global@1.0.0
npm ERR! Found: @angular/compiler@7.2.16
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"7.2.16" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"^2.3.1 || >=4.0.0-beta <5.0.0" from codelyzer@3.2.2
npm ERR! node_modules/codelyzer
npm ERR!   dev codelyzer@"~3.2.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\AjithamarlinEdward\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AjithamarlinEdward\AppData\Local\npm-cache\_logs\2022-04-21T13_25_50_129Z-debug-0.log
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.3
Node: 16.13.1
Package Manager: npm 8.6.0
OS: win32 ia32

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1303.3 (cli-only)
@angular-devkit/core         13.3.3 (cli-only)
@angular-devkit/schematics   13.3.3 (cli-only)
@schematics/angular          13.3.3 (cli-only)
```

**Comment by jessicajaniuk** [comment]
The Angular compiler version should be a the same version as the rest of the packages: 13.3.3. It looks like your package.json locks the compiler version to below 5.0, which is not going to resolve when updating. You'll need to fix that in your package json file. codelyzer may have a similar issue.

Regardless, this is probably a question better suited for StackOverflow as it's more of a support request. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
