### ISSUE TITLE
Getting started tutorial missing "npm install traceur" step?

### ISSUE THREAD

**Issue by ultrasonicsoft** [angular/angular#4571]
Hi All,
I was going through each step given in updated getting started page below:
https://angular.io/docs/ts/latest/guide/gettingStarted.html

When I did launch live-server --open=src, browser couldn't load page as it didn't find traceur-runtime.js file. 

I think the npm install package command given in tutorial is missing for traceur package.
Currently it is as below

    npm install --save angular2@2.0.0-alpha.37 systemjs@0.19.2

I think it should be like

    npm install --save angular2@2.0.0-alpha.37 systemjs@0.19.2 traceur

Correct me if I am wrong.

Thanks!

-
Balram

**Comment by IgorMinar** [comment]
as of alpha-38 we no longer require traceur-runtime. please update to alpha-38

**Comment by ultrasonicsoft** [comment]
I do agree Igor. I am able to run it with alpha 38 and also by installing traceur with alpha 37.

But my point is the given tutorial on official angular2 website uses alpha37 and if anybody try to follow "getting started" page
https://angular.io/docs/ts/latest/guide/gettingStarted.html

They will face this error unless they install traceur which is missing on website step.

So this issue is to update website "npm install" step either of below: 
npm install --save angular2@2.0.0-alpha.38 systemjs@0.19.2
npm install --save angular2@2.0.0-alpha.37 systemjs@0.19.2 traceur

**Comment by IgorMinar** [comment]
sorry about that. we are doing docs refresh that should be posted later
this week.
