### ISSUE TITLE
Add an `injectAsync` helper to the test_lib

### ISSUE THREAD

**Issue by juliemr** [angular/angular#4572]
The problem:

Currently, using the test injector with an async test is wordy and unintuitive:
```js
import {it, inject, AsyncTestCompleter} from 'angular2/test_lib';

it('does stuff', inject[ClassA, ClassB, AsyncTestCompleter], (a, b, async) => {
  async.done();
});
```

There's a split in the code path anyway for async / not-async, so let's just make this explicit:

```js
import {it, injectAsync} from 'angular2/test_lib';

it('does stuff', injectAsync[ClassA, ClassB], (a, b, done) => {
  done();
});
```

We could deprecate the AsyncTestCompleter separately if we don't want two ways of doing the same thing.

Thoughts?

cc @wardbell and see his version at https://github.com/angular/angular/issues/4035#issuecomment-143937352

cc @vicb for thoughts.

**Comment by vicb** [comment]
Why not.

**Comment by IgorMinar** [comment]
do we even need injectAsync? we can't we just provide `done` as the last argument to the callback?

I'm also thinking that we should make `inject` callback return a promise back to `inject` and then we automatically know when to call done, and more importantly, we can propagate and display errors automatically without users having to do anything:

```
it('does stuff', inject([TestComponentBuilder], (tcb: TestComponentBuilder) => 
  tcb.createAsync(HeroesComponent) // notice implicit return of the returned promise
      .then((rootTestComponent: RootTestComponent) => {
        // assert here
       });   
));
```

it could be shortened even further by a TCB specific helper but since we need to be able to override metadata via tcb before creating an instance of a component, things get tricky.

**Comment by vicb** [comment]
> we can't we just provide done as the last argument to the callback?

It depends if we have plan to drop mirrors (reflection) from the tests (Dart)

**Comment by juliemr** [comment]
Here's a stab at this:

https://github.com/angular/angular/compare/master...juliemr:testapi

I haven't looked at how it would work with Dart at all yet.

**Comment by tbosch** [comment]
Victor, the tests need the runtime compiler, which only works with Mirrors

**Comment by IgorMinar** [comment]
We should design the best api possible for js/ts and if necessary create
separate api for Dart. Keep in mind that this api is meant for angular apps
and doesn't need to be used by the angular core test suite which needs to
be transpilable (if that's a real world) to dart.

**Comment by juliemr** [comment]
Agreed - however, if possible, it's really helpful to be able to use the angular core test suite as examples and documentation of how to test, so if we can make it work smoothly with both, I would be very happy.

**Comment by wardbell** [comment]
Hi folks.  When I took my first stab at this, I made `done` the *first* parameter. It is the only parameter that is essential to the callback and a reliable home for the `done` function. I don't think this is a huge deal for the tester. I'm just saying that it seems easier in first position other things being equal.

I'm thrilled that you found a way to have one `inject` that can be either sync or async ... in approximately the same manner as the Jasmine `it` callback. Not sure how you did it but I like. How do you know if the `done` fn is in the parameter list?

**Comment by juliemr** [comment]
@wardbell my current implementation is pretty naive - I just check if the length of the parameters to the injected function is greater than the length of the types to inject :)

**Comment by wardbell** [comment]
Igor mentioned a feature I had in my version, namely that the callback returns a promise and the wrapper appends the requisite `catch(fail).then(done)` trailer. This alleviates the need for the developer to remember that sequence (which I find absent in many tests).

This works great as long as the test function has a ready promise to return ... which is most of the time. It's a bit clumsy when you're testing something that uses observables instead of promises.  I don't have enough observable testing experience to recommend a "best practice" yet.

**Comment by wardbell** [comment]
@juliemr That is sweetly naive ... and probably sufficient most of the time. 

We must tell the test developer about it. I have, in the past, injected a service for some side-effect without actually needing it. In some such cases I listed it in trailing inject list position  in which case I could omit it from the end of the parameter list. Maybe that was being too clever and I'd have a hard time recommending that approach. It obviously won't work here.

I'm cool with a less than perfect `inject` function. The folks are a bit more forgiving and sophisticated than the broader Angular audience.

OTOH, if we want this API to approach the same standard as mainstream Angular APIs, we probably should not play these games and should go with separate explicit `inject` and `injectAsync` methods.

I don't have strong feelings either way.

**Comment by juliemr** [comment]
Note: I can get this working with dart, see https://github.com/angular/angular/compare/master...juliemr:testapi-2

**Comment by juliemr** [comment]
OK! Here is the latest and greatest (and still in progress) idea: https://github.com/juliemr/angular/tree/testapi-3

The strategy here is:
- Make a separate test library for use outside of core angular. We may merge the two later, but for now, this lets us develop without worrying about transpiling to Dart and without having to make massive changes to all the core angular2 tests.

- Wait for returned promises in tests.

Example tests are in https://github.com/juliemr/angular/blob/testapi-3/modules/angular2/test/test_lib/test_lib_public_spec.ts

_Problem area_: If the user does some asynchronous work, but forgets to `return` the promise, it's masked as a synchronous test pass. See [this test](https://github.com/juliemr/angular/blob/testapi-3/modules/angular2/test/test_lib/test_lib_public_spec.ts#L172). It may even cause a later, unrelated test to fail.

Would appreciate any comments!

**Comment by juliemr** [comment]
Also @wardbell I'm not sure what you mean - the entire Angular audience writes tests, right? :)

**Comment by wardbell** [comment]
I don't know what else to do but document that test goes bad if don't return a promise.

That's not much different than failing to provide a done param in a standard jasmine test.

The good news is that vs code displays a massive number of red squiggles if you forget to return a promise (or it did with my injectAsync prototype). Maybe that's another reason for separate inject and injectAsync methods?

**Comment by juliemr** [comment]
Done with a1fa2e472fc50ceecef37e7c5da2ae760a8ad88c
