### ISSUE TITLE
Tutorial TOH part 5 : Wrong Files in Final Code Review Section

### ISSUE THREAD

**Issue by LeifHenriksen** [angular/angular#45736]
### Description

Hi,

The Final Code Review section is showing the wrong files, for example, for [AppComponent](https://angular.io/tutorial/toh-pt5#final-code-review) I get the **hero-search/hero-search.component.html** instead of **app.component.html**, same issue for the [AppRoutingModule, AppModule, and HeroService](https://angular.io/tutorial/toh-pt5#final-code-review) section.

Thanks.

### What is the affected URL?

https://angular.io/tutorial/toh-pt5#final-code-review

### Please provide the expected behavior vs the actual behavior you encountered

For the AppComponent we should get the appcomponent HTML same for AppRoutingModule, AppModule, and HeroService.

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/44870274/164915494-c1ef1577-abcf-4c49-8b1f-e3435840fd11.png)

**Comment by TarekVisch** [comment]
The issue persists.

**Comment by gkalpak** [comment]
@TarekVisch, it will be fixed by #45830.
