### ISSUE TITLE
[test] Text bindings are not bound elements anymore

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#4573]
With the new compiler (introduced in alpha-38), elements with a simple text binding like `<div>{{username}}</div>` are not bound element anymore.

When writing tests, that means they don't appear in `rootTC.debugElement.componentViewChildren` or in `rootTC.debugElement.query(By.css('div'))`.

It leads to write less readable tests, relying on something like `DOM.childNodes(rootTC.debugElement.nativeElement)[4]`.

These tests are less readable and more fragile.
Is there a plan to fix or improve this?

**Comment by pkozlowski-opensource** [comment]
@cexbrayat did you try alpha.39? There were number of fixes that went into it and it was released just yesterday.

**Comment by cexbrayat** [comment]
@pkozlowski-opensource I've got to admit I did not yet (I wanted to have all my 300 tests green before moving on to 39). As far as I saw in the commits in 39 though, there are no changes on this part.

**Comment by pkozlowski-opensource** [comment]
@cexbrayat .38 had several problems and .39 has several fixes so I would advise going straight to .39. .38 is just too unstable.

**Comment by cexbrayat** [comment]
@pkozlowski-opensource I can confirm this is the same in alpha-39

**Comment by mhevery** [comment]
I don't think we will make them bound elements. @tbosch  please comment. The reason we had to do it was that we used a different mechanism of locating text nodes. The new mechanism is faster, so it is very unlikely that we would add this back.

Perhaps you could suggest better syntax for your tests and we could work on that?

**Comment by cexbrayat** [comment]
Thanks for considering this. I understand your point and that's not really a problem. I think what we really need is an easy way to query elements in tests, among other things. I've got around 300 tests right now for my ebook, testing pretty much everything, and I think it's not friendly enough (at least with what I know/we have right now).

Let's take a simplified example.

````
let html = `
<form (ng-submit)="register()">
  <div>
    <label>Username</label><input [(ng-model)]="user.username">
    <small>{{ user.username }} is an awesome username!</small>
  </div>
</form>
`;

tcb.overrideTemplate(RegisterFormCmp, html)
  .createAsync(RegisterFormCmp)
  .then((formCmp) => {
    formCmp.debugElement.componentInstance.user.username = 'Cédric';
    formCmp.detectChanges();
    // asserts
    let input = formCmp.debugElement.query(By.css('input')).nativeElement;
    expect(input.value).toBe('Cédric');        
    let small = DOM.childNodes(DOM.childNodes(formCmp.debugElement.query(By.css('form')).nativeElement)[1])[4];
    expect(small).toHaveText('Cédric is an awesome username!');
  
    async.done();
  });
````

A few things could be straightforward/less verbose:
- `formCmp.debugElement.componentInstance.user.username = 'Cédric';` is really long. Maybe we could have something like `formCmp.user.username = 'Cédric';`
- `DOM.childNodes(DOM.childNodes(formCmp.debugElement.query(By.css('form')).nativeElement)[1])[4];` is horrible. As the elements with text bindings are not bound elements, the css query `formCmp.debugElement.query(By.css('small')).nativeElement` does not work anymore.
`DOM.childNodes` is a quick fix to make my tests green right now, but I don't know what I could do to access an element that can't be queried at the moment... (Am I missing something obvious?)
Something like `$(formCmp).find('small')` would be better perhaps?

That would give:

````
let html = `
<form (ng-submit)="register()">
  <div>
    <label>Username</label><input [(ng-model)]="user.username">
    <small>{{ user.username }} is an awesome username!</small>
  </div>
</form>
`;

tcb.overrideTemplate(RegisterFormCmp, html)
  .createAsync(RegisterFormCmp)
  .then((formCmp) => {
    formCmp.user.username = 'Cédric';
    formCmp.detectChanges();
    // asserts
    let input = $(formCmp).find('input');
    expect(input.value).toBe('Cédric');        
    let small = $(formCmp).find('small');
    expect(small).toHaveText('Cédric is an awesome username!');
  
    async.done();
  });
````

**Comment by juliemr** [comment]
I agree that this is annoying, I ran into it myself yesterday. Assigning myself to take a look and see if we can modify `DebugElement` to search through text bindings in addition to normal bound elements.

FYI this is going in the 'After AngularConnect' priority bucket for me.

**Comment by juliemr** [comment]
@rkirov and I were thinking that maybe the `DebugElement` API just isn't useful for most users. It seems like getting at the native element and doing plain old DOM manipulation from there is what most people will want. So @cexbrayat  your test would look something like:

```js
// Note that this should all already work with angular as in master right now.

let html = `
<form (ng-submit)="register()">
  <div>
    <label>Username</label><input [(ng-model)]="user.username">
    <small>{{ user.username }} is an awesome username!</small>
  </div>
</form>
`;

return tcb.overrideTemplate(RegisterFormCmp, html)
  .createAsync(RegisterFormCmp)
  .then((formCmp) => {
    formCmp.componentInstance.user.username = 'Cédric'; // the need for `debugElement here is now removed
    formCmp.detectChanges();
    // asserts
    let htmlRoot = formCmp.nativeElement; // again, no debugElement

    let input = htmlRoot.querySelector('input');
    expect(input.value).toBe('Cédric');        
    let small = htmlRoot.querySelector('small');
    expect(small).toHaveText('Cédric is an awesome username!');
  });
```

It would require significant changes to `DebugElement#query` to make it work with text nodes - at the moment, it only returns other `DebugElement`s, and those must be backed by an `ElementRef`. Bound text nodes no longer have an `ElementRef`, and as Misko mentioned, probably won't be changed.

Thoughts @tbosch?

**Comment by cexbrayat** [comment]
Indeed, I rewrote my tests to look exactly like what you suggest. DOM queries are more readable than using `query` or  `componentViewChildren` for a lot of cases.

In my apps, the only time that I can see `query` needed is when we want to grab a reference to the children directive to test something. At least, that's what I suggest in our ebook, feel free to tell me if there is something I'm missing:

```
let pony = fixture.query(By.directive(PonyCmp));
expect(pony.componentInstance.name).toBe('Rainbow Dash');
```

**Comment by juliemr** [comment]
@cexbrayat yeah, that looks good to me. 

There's a similar discussion at https://github.com/angular/angular/issues/5385 - let's continue there and close this issue for now, since the particular case of the bound text element is shut.
