### ISSUE TITLE
RouterLink full reload 50% of times in DevMode

### ISSUE THREAD

**Issue by albanx** [angular/angular#45745]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

I have a property website homezone.al, where customer can search and a list of properties is displayed. How does the bug happens:
- I search, and I see a list of properties (ngFor on a <property component)
- I click a property to open a details ([routerLink]='/property/somedesc-id'
- I go back to the search list
- I click the property again and causes a full reload of the page

I am gonna attach a video to explain better.

### Please provide a link to a minimal reproduction of the bug

https://homezone.al/properties/sale/city/Vlore

### Please provide the exception or error you saw

```true
No error on the dev console
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.5
Node: 16.13.0
Package Manager: npm 8.1.0
OS: darwin x64

Angular: 13.2.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material, platform-browser
... router

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1302.5
@angular-devkit/build-angular       13.2.5
@angular-devkit/core                13.2.5
@angular-devkit/schematics          13.2.5
@angular/cli                        13.2.5
@angular/platform-browser-dynamic   13.3.1
@angular/platform-server            13.3.1
@nguniversal/builders               13.1.0
@nguniversal/express-engine         13.1.0
@schematics/angular                 13.2.5
rxjs                                7.5.4
typescript                          4.4.3
```

### Anything else?

Happens only in DEV mode right now, and ONLY on Chrome Mobile Simulation.

https://user-images.githubusercontent.com/1130664/164986973-69b69e09-c37a-4357-a6b7-e6ae8b78e32c.mp4

**Comment by albanx** [comment]
another wired behavoiur that I notice while trying to fix this issue is:
- Search Result page calls the API with a limit of 20 items
- The next pagination, the old first 20 items are not removed from DOM never and the new items are added to the DOM
I verified the NGFOR is getting only 20 items but somehow randomly I see 40.

Snippet of code:
```
      <ng-container *ngIf="!isSearching">
        <property
          *ngFor="let ad of results.properties; let idx = index"
          [ad]="ad"
          [agency]="results.agencies[ad.agency_id]"
          [index]="idx"
          [@fadeIn]="results.properties.length"
        ></property>
      </ng-container>
```
where `results.properties` has always 20 items in the array, but randomly on the page it shows 40: the very first 20 and the 20 of the results.properties

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by albanx** [comment]
@atscott This issue looks like an angular bug, it is not a support request. I have googled it before opening the ticket and I have found different reports of the same bug, like this one https://stackoverflow.com/questions/57901223/routerlink-seems-to-just-reload-the-current-page-most-of-the-time

**Comment by albanx** [comment]
to add more info: right now it is not happening any more, I did some refactoring around some code... either previuosly I had some error and Angular was not reporting it, still I suspect the bug remains as you can see from the video.

**Comment by albanx** [comment]
+both the bugs above seems to persist very badly when using a cache route strategy

**Comment by albanx** [comment]
definitively the issue is in the RouteReuseStrategy combined with lazy modules

**Comment by albanx** [comment]
The issue is deeper, after lot of debugging and retries it happens with this conditions:
- RouteReuseStrategy enabled on a page that shows a list of component in a loop
- Component having an animation (fadeIn in my case) on enter for every item (targeting *)
- Internal component elements have an IF condition to show

this is an attempt to replicate it https://stackblitz.com/edit/angular-8chhcg?file=src%2Fapp%2Fviews%2Fdetails%2Fdetails.component.html

but cannot. 

Happens consistenly on my project, it works as fine when I remove the animation. At the moment I removed all animations.

**Comment by albanx** [comment]
@atscott Yep finally got it fully reproduction-able, took a while, got me somehow to confusion with routerLink, because the "left over" items of ngFor were having routerLink broken as well
