### ISSUE TITLE
Code font weight on documentation

### ISSUE THREAD

**Issue by ocombe** [angular/angular#4574]
Hello,
I find the font used in the code samples from angular.io really hard to read. The problem comes from the "bold" style.
If you remove the `font-weight: 600;` from the `.prettyprint ol` class it becomes much more readable.
Ex: on the following page: https://angular.io/docs/js/latest/api/core/FormBuilder-class.html (try changing this code style from your dev tools).

Any chance that you could consider this style update ?

**Comment by pkozlowski-opensource** [comment]
@ocombe could we please move it over to https://github.com/angular/angular.io? 

Thnx!

**Comment by ocombe** [comment]
Woops sorry :) Doing that
