### ISSUE TITLE
Tutorial uses broken button example

### ISSUE THREAD

**Issue by jdob** [angular/angular#45758]
### Description

On step 2 of the tutorial (link below), it says to:

`Add a <button> with a click event binding in the <li> like this:

heroes.component.html (template excerpt)
content_copy
<li *[ngFor](https://angular.io/api/common/NgForOf)="let hero of heroes">
  <button type="button" (click)="onSelect(hero)">`

That snippet is incomplete; the button is never closed, so I get an error like:

`error NG5002: Unexpected closing tag "li". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags`

### What is the affected URL?

https://angular.io/tutorial/toh-pt2

### Please provide the steps to reproduce the issue

Follow the tutorial directions up until the "Add a click event binding" section

### Please provide the expected behavior vs the actual behavior you encountered

The instructions read as if I'm supposed to make the changes locally, which cause my app to break. If this is just an informative snippet that's not meant to be pasted in, it should be more clear that it was an example and not a step I had to take.

### Please provide the exception or error you saw

```true
Error: src/app/heroes/heroes.component.html:6:5 - error NG5002: Unexpected closing tag "li". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags
```

**Comment by jdob** [comment]
Forgot to mention, I was able to get around it by manually closing the button after the text:

```
<li *ngFor="let hero of heroes">
        <button type="button" (click)="onSelect(hero)">
        <span class="badge">{{hero.id}}</span> {{hero.name}}
        </button>
</li>
```

**Comment by dario-piotrowicz** [comment]
Hi @jdob :slightly_smiling_face: 

Thanks for flagging it, that is an excerpt so it doesn't contain the while code, the completed code for the `li` is shown a bit later:
![Screenshot at 2022-04-30 10-28-56](https://user-images.githubusercontent.com/61631103/166100105-2b5fd763-0339-4ea4-bb15-9b0ed467f5b7.png)

(and you can also see the full result in the final code review section)

So I would be tempted to say that this is as is intended :thinking: 

But maybe all of the code snippet should create compilable code? or maybe it should be made more clear that that code snippet is incompleted? :thinking: What do you think @gkalpak? :slightly_smiling_face:

**Comment by gkalpak** [comment]
In this case, I think it is fine that the code-snippet is not complete, but we could make it more clear by adding some ellipsis or a comment or something.

This would be particularly easy in this case, because the code-snippet is not extracted from an actual template. So, it is just about updating this docregion:

https://github.com/angular/angular/blob/a88bf2090e2e56415241b0ec5b499e7c8b5109cd/aio/content/examples/toh-pt2/src/app/heroes/heroes.component.1.html#L14-L17

##
@jdob or @dario-piotrowicz, would any one of you be up to creating a PR?

**Comment by dario-piotrowicz** [comment]
@gkalpak PR created :slightly_smiling_face: 

@jdob, I hope it's fine by you :bow:
