### ISSUE TITLE
Inaccurate error message on step 2 of the tutorial

### ISSUE THREAD

**Issue by jdob** [angular/angular#45759]
### Description

Following the tutorial step 2, it has me add a details section and specifies that the application is broken. That part is right, it is broken. But instead of the documented:

`HeroesComponent.html:3 ERROR TypeError: Cannot read property 'name' of undefined`

Instead I get:

`Error: src/app/heroes/heroes.component.html:11:25 - error TS2532: Object is possibly 'undefined'.`

Also note that the file mentioned in the documented error message doesn't exist. The rest of the tutorial correctly referenced heroes.component.html, but the documented error shows `HeroesComponent.html`. I'm guessing that's from an older version of Angular and just got missed when the other pieces were being updated.

### What is the affected URL?

https://angular.io/tutorial/toh-pt2#add-a-details-section

### Please provide the steps to reproduce the issue

Follow the tutorial through "Add a details section"

### Please provide the expected behavior vs the actual behavior you encountered

Mentioned in the description; the expected behavior is one error message, but in practice I see a different one.

### Please provide the exception or error you saw

```true
Error: src/app/heroes/heroes.component.html:14:51 - error TS2532: Object is possibly 'undefined'.
```

**Comment by dario-piotrowicz** [comment]
Thanks @jdob good catch, I've opened a PR for clarifying that section :slightly_smiling_face::+1:
