### ISSUE TITLE
JIT compiler unavailable using Angular 13

### ISSUE THREAD

**Issue by ignaciorecuerda** [angular/angular#45755]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

No

### Description

After upgrading our library to Angular 12 (and it also happens on Angular 13) we are facing the error `Uncaught Error: JIT compiler unavailable` when using a component of the library, causing the component doesn't work and neither does the web application.

I think the error is happening since Angular 12 is using the new engine `Ivy` which is forced to be used since Angular 12, and the compilation mode `partial`.

For the upgrade, we have followed the steps described in the [official guide](https://update.angular.io/)

The angular compiler options used is:
```
"angularCompilerOptions": {
    "enableIvy": true,
    "fullTemplateTypeCheck": true,
    "compilationMode": "partial",
    "strictInjectionParameters": true
  },
```

### Please provide the exception or error you saw

```true
When the component of the library is deployed, the error is: Uncaught Error: JIT compiler unavailable.

But when the application is running locally, the error is: Uncaught Error: The injectable 'AnyService' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available. 
The error was fixed by us locally adding "import @angular/compiler" but the JIT compiler unavailable still there when a component of the library is used
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.3         
Node: 14.17.6               
Package Manager: npm 6.14.15
OS: win32 x64               

Angular: 13.3.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.3
@angular-devkit/build-angular   13.3.3
@angular-devkit/core            13.3.3
@angular-devkit/schematics      13.3.3
@schematics/angular             13.3.3
ng-packagr                      13.3.1
rxjs                            7.5.5
typescript                      4.6.3
```

### Anything else?

The same error using Angular 12 and Angular 13

**Comment by JoostK** [comment]
The linker needs to run for the _application_, not the library. Does the application use the CLI?

**Comment by ignaciorecuerda** [comment]
Thanks for your answer @JoostK 
Of course, the application use the CLI

**Comment by JoostK** [comment]
In that case, can you share a reproduction? We've never seen issues with the CLI in this area, so it's unclear how you're experiencing an issue here.

**Comment by ignaciorecuerda** [comment]
It's a private code and I cannot share it, but I would like to prepare an example for you. What exactly do you need to reproduce the error?

**Comment by JoostK** [comment]
A GitHub repo with a minimal example would likely work best
