### ISSUE TITLE
Offensive hero name

### ISSUE THREAD

**Issue by jorge-aceves** [angular/angular#45769]
### Description

In the tour of heroes app (https://angular.io/tutorial) the name of the first hero is "narco". Being from Mexico I don't find it particularly nice that narcos are being referred to as heroes in this app. Our country has more than 150K deaths since 2006 due to cartel violence (https://www.cfr.org/global-conflict-tracker/conflict/criminal-violence-mexico). It feels almost like a joke to be writing an app where I have to call a Narco a Hero. 

### What is the affected URL?

https://angular.io/tutorial and related links

**Comment by mgechev** [comment]
That's a valid concern. We'll prioritize and address the update.

**Comment by bob-watson** [comment]
Screenshots & images in `/angular/aio/content/images/guide/toh` that should be updated along with the text
* dashboard-top-heros.png
* heros-dashboard-1.png
* heros-list-1.png
* heros-list-2.png
* nav-diagram.png
* toh-anim.gif
* top-http.anim.gif

**Comment by PhiLhoSoft** [comment]
The problem is that this list is named "heroes" while actually it just lists characters from the Marvel Universe, including villains. Narcos is among the villains, not the heroes… You can find the Sentinels, Kingpin, and other villains.
