### ISSUE TITLE
RouteReuseStrategy with components having animation bug in clearing/updating the NGFOR elements

### ISSUE THREAD

**Issue by albanx** [angular/angular#45765]
### Which @angular/* package(s) are the source of the bug?

animations, core, router

### Is this a regression?

Yes

### Description

When reusing an component that has a list of elements that shows in a ngFor 4
The bug happens under this conditions:
- RouteReuseStrategy on a component that shows a list of element
- Having a fadeIn animation with enter target for the element of the list
- when switching between the list component and another route (which kicks the store and the retrive of RouteReuseStrategy)

Minimal live example with bug replication:
https://stackblitz.com/edit/angular-8chhcg?file=src%2Fapp%2Fviews%2Fdetails%2Fdetails.component.html

replication steps
- Go To Catalog Page
- Click Search 1, Search 2, Search 3 button (works fine)
- Go to Home or Login page (click the links)
- Go back to Catalog Page, and click search 1 search 2 or search 3
- You will see that clicking for example search 1 will show the list of search 1 and search 2 without removing the old list

**This bug happens on Angular 13.4**, but **Does not happen on Angular 12.4**

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-8chhcg?file=src%2Fapp%2Fviews%2Fdetails%2Fdetails.component.html

### Please provide the exception or error you saw

```true
No error on the console
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.5
Node: 16.13.0
Package Manager: npm 8.1.0
OS: darwin x64

Angular: 13.2.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material, platform-browser
... router

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1302.5
@angular-devkit/build-angular       13.2.5
@angular-devkit/core                13.2.5
@angular-devkit/schematics          13.2.5
@angular/cli                        13.2.5
@angular/platform-browser-dynamic   13.3.1
@angular/platform-server            13.3.1
@nguniversal/builders               13.1.0
@nguniversal/express-engine         13.1.0
@schematics/angular                 13.2.5
rxjs                                7.5.4
typescript                          4.4.3
```

**Comment by atscott** [comment]
@jessicajaniuk This looks like the same issue as https://github.com/angular/angular/issues/45381. Should it be closed as a duplicate?

**Comment by albanx** [comment]
I think it is same issue at the root, but I believe mine one replicates more clearly what happens, showing a list generated from a ngFor duplicating accross

**Comment by JoostK** [comment]
I'm working on handling detaching elements in the animations package in #45516, I wonder if those changes resolve the issue in these cases as well. The PR is not yet done but its build artifacts are available for testing (as if it were Angular 14, that is)

**Comment by albanx** [comment]
The issue is kind of more wired: even after removing the animation, if I am in a page and I change parameters (like query params) it does not trigger a full update, it triggers it for some part of the page...

**Comment by jessicajaniuk** [comment]
Closing as duplicate but also have referenced this issue for the useful context on #45381.
