### ISSUE TITLE
Add support to observe / watch a variable (not a property)

### ISSUE THREAD

**Issue by danicomas** [angular/angular#4576]
Now I can have something like that. Why?
https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Object/observe

- onChanges doesn't works because it only works with props.
- eventEmitter and return Rx.Observable only returns the first https://github.com/angular/angular/issues/3580#issuecomment-144948976

How can I watch/observe a variable? @gdi2290 @vicb @mhevery

**Comment by gdi2290** [comment]
what are you trying to accomplish? could you provide a plnkr with a reason why you want to watch a variable

**Comment by danicomas** [comment]
With the same example that your plnkr: http://plnkr.co/edit/HfdjvOxGcP0FuAsVeD71?p=preview

@gdi2290 we should be able to watch or observe component variables. For example, if you want to create a service or some library you will need an observe variables without relate the props with the template.

**Comment by vicb** [comment]
@danicomas could you expand on your use case ?

A component property should only change in result to an event which should trigger the change detection thanks to zone.js.

**Comment by danicomas** [comment]
I have used the ES7 standard https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Object/observe and it works well. To create services, some components or librares can work well. Look at this:

```
import {Component, View, bootstrap} from 'angular2/angular2';

@Component({
	selector: 'my-app'
})
@View({
	template: '<h1>Hello {{ name }}</h1>'
})
class MyAppComponent {
  name: string;
  constructor() {
    this.name = 'Alice';

    Object.observe(this, function(changes) {
	  console.log(changes);
    });
	
    this.name = 'dd5';
  }
}

bootstrap(MyAppComponent);
```

**Comment by mhevery** [comment]
I believe what you asking is to arbitrary watch properties on objects like you can do in Angular 1 with `$watch`. This can not be added in Angular 2 because it requires that we would ship the parser with every release, which would prevent offline compilation and fast bootstrap on mobile devices. So this is a tradeoff which we have knowingly made.

WONT_FIX

**Comment by danicomas** [comment]
Ok @mhevery I know but do you recommend to use Observe or is not a good idea? Look at this: https://github.com/Microsoft/TypeScript/issues/2075

**Comment by ericmartinezr** [comment]
@danicomas 

I commented you this in gitter, but probably other people may be interested as well. It looks like `Object.observe` will be removed from ES7 spec, see [this mailing list](https://mail.mozilla.org/pipermail/es-discuss/2015-November/044684.html)

**Comment by danicomas** [comment]
Thanks for the information @ericmartinezr . Now I am confused can we use use something like that in Angular2?

**Comment by deepakgd** [comment]
I want to watch my cookie value isAuthenticate continuously. because if isAuthenticate is false i need to redirect to login page or if isAuthenticate is removed(cookie cleared) i need to redirect into login page. so can you please provide some idea?

**Comment by zoechi** [comment]
Use an `Observable` or `Subject` in a service. That allows to subscribe interested components or services and act on update events. There are examples on StackOverflow.

@deepakgd GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by deepakgd** [comment]
ok thanks

**Comment by BojDom** [comment]
@danicomas  found a solution?

**Comment by ochanje210** [comment]
Still no solution? It would be nice to have such feature that watches specific value changes.

**Comment by zoechi** [comment]
@ochanje210 not necessary, not planned, and already explained https://github.com/angular/angular/issues/4576#issuecomment-146955427

**Comment by aino-gautam** [comment]
@ochanje210 couldn't you use Proxy instead of Object.observe ( deprecated ) ?
