### ISSUE TITLE
Inconsistency in step 2

### ISSUE THREAD

**Issue by jdob** [angular/angular#45760]
### Description

Near the beginning of step two, it says the details view should look like the following:

```
<ul class="heroes">
  <li>
    <span class="badge">{{hero.id}}</span> {{hero.name}}
  </li>
</ul>
```

Further down, in the "Style the selected hero" section, the HTML changes without telling the user about it:

```
<li *[ngFor](https://angular.io/api/common/NgForOf)="let hero of heroes">
  <button [class.selected]="hero === selectedHero" type="button" (click)="onSelect(hero)">
    <span class="badge">{{hero.id}}</span>
    <span class="name">{{hero.name}}</span>
  </button>
</li>
```

Note the specific spans for id v. name. It's a very minor issue, but potentially confusing to users following along (it made me wonder if I missed a step). It also prevented the names from being styled, so my output looked different then the screenshot (mine was in a roman font and not aligned properly). 

Like I said, minor issue, but easy enough to correct.

### What is the affected URL?

https://angular.io/tutorial/toh-pt2

### Please provide the steps to reproduce the issue

Follow the tutorial through "Style the selected hero"

**Comment by dario-piotrowicz** [comment]
Thanks for pointing that out @jdob, PR created with a potential fix :slightly_smiling_face::+1:
