### ISSUE TITLE
Access component variables from SCSS file.

### ISSUE THREAD

**Issue by AmerAnsari** [angular/angular#45779]
### Description

Let's explain it with an example:

I have a variable that holds color and I want to use them for styling the elements. 
I know we can change the styles via renderer or something like that.
And I can't do that in the template with `ngStyle` or etc because I want to use that color in SCSS mixin functions.

### Proposed solution

None.

### Alternatives considered

None.

**Comment by otodockal** [comment]
@AmerAnsari I know it's not the same, but what about using CSS variables? You can read/write CSS variable values in SCSS, HTML, TS, it's pretty universal.

https://stackblitz.com/edit/angular-ivy-6k2bse?file=src%2Fapp%2Fapp.component.ts

**Comment by maroon1** [comment]
There is workaround @AmerAnsari , but the CSS variable is **not scoped** in component.
```typescript
import { Component, HostBinding } from '@angular/core';

@Component({
  selector: 'app-root',
  template: ``,
  styles: [
    `
      :host {
        background: var(--background);
      }
    `,
  ],
})
export class AppComponent {
  @HostBinding('style.--background')
  background = 'red';
}
```

**Comment by AndrewKushnir** [comment]
Closing based on https://github.com/angular/angular/issues/7251#issuecomment-871739705.
