### ISSUE TITLE
Angular runtime created components aren't listed in @ViewChildren

### ISSUE THREAD

**Issue by angelaki** [angular/angular#45771]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

As you can see in this example Angular doesn't seam to list runtime created components (via viewContainerRef.createComponent(HelloComponent)) in it's @ViewChildren(HelloComponent).

Is this an expected behavior or a bug? Do I need to mark it somehow so it get's listed?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-knbzcs?file=src%2Fapp%2Fapp.component.html

### Please provide the exception or error you saw

```true
HelloComponent-Count is still one (due to the only markup created component)
```

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 13.3.3
Node: 16.13.2
Package Manager: npm 8.5.4
OS: win32 x64

Angular: 13.3.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, material-moment-adapter, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.3
@angular-devkit/build-angular   13.3.3
@angular-devkit/core            13.3.3
@angular-devkit/schematics      13.3.3
@angular/cli                    13.3.3
@schematics/angular             13.3.3
rxjs                            7.5.5
typescript                      4.5.5

**Comment by JoostK** [comment]
I'd personally argue this is working as designed. The _view_ concept relates to a component's own template and a dynamically inserted component is _not_ part of that template, so it wouldn't be queried for using `ViewChild`.

**Comment by angelaki** [comment]
If it is by design this issue can surely be closed. I just wanted to make sure my componend won't get _double tracked_ some day.

**Comment by JoostK** [comment]
That is unlikely to happen, and it would be a breaking change.

**Comment by angelaki** [comment]
So this issue can be closed. Since I've created the component I know the pointer anyway! 👍
