### ISSUE TITLE
Routing query parameters do not work with reoload

### ISSUE THREAD

**Issue by rasoulMrz** [angular/angular#45792]
### Which @angular/* package(s) are the source of the bug?

router

### Description

Routing to a path with queryParams will route into something like: `xyz?param=value` which works as expected. But when you are on a page with that URL (some URL with query params) and reload the page, you will get an exception like:
`Error: Cannot match any routes. URL Segment: 'xyz%3Fparam%3Dvalue'`! in fact, the `?` and `=` marks are changed into  `%3F` and `%3D` and the router gets confused!

I thought this was related to my browser but the issue exists on both chrome and firefox! another check is that query params work fine on other websites e.x. GitHub. I can reload [this url](https://github.com/angular/angular/issues/new?assignees=&labels=&template=1-bug-report.yaml) with no issues! So it seems to be s.th. wrong with angular!

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.0
Node: 16.14.2
Package Manager: npm 8.7.0
OS: linux x64

Angular: 13.3.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1303.3
@angular-devkit/build-angular      13.3.0
@angular-devkit/core               13.3.3
@angular-devkit/schematics         13.3.0
@angular/cdk                       13.3.1
@angular/flex-layout               13.0.0-beta.38
@angular/material                  13.3.1
@angular/material-moment-adapter   13.3.1
@schematics/angular                13.3.0
ng-packagr                         13.3.0
rxjs                               6.6.7
typescript                         4.6.3
```

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
