### ISSUE TITLE
Lazy loaded modules not loaded in production

### ISSUE THREAD

**Issue by mhalp** [angular/angular#45791]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Hi,y 
My app includes a few lazy-loaded modules. It works fine in development and in ng serve --prod,
But in  --prod build, the lazy loaded modules are loaded only if I use a <link> from the appModule component, and not directly from the browser. 
In direct link from the browser, the request to the source code looks like server regular requests and not encoded, and the result is 404 error.

### Please provide the exception or error you saw

```true
Failed to load resource: the server responded with a status of 404 ()
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.4
Node: 17.5.0 (Unsupported)
Package Manager: npm 8.4.1
OS: linux x64

Angular: 13.1.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.3
@angular-devkit/build-angular   13.2.3
@angular-devkit/core            13.2.3
@angular-devkit/schematics      13.1.4
@angular/cdk                    13.2.2
@angular/cli                    13.1.4
@angular/material               13.2.2
@schematics/angular             13.1.4
ng-packagr                      13.2.1
rxjs                            7.4.0
typescript                      4.5.5
```

### Anything else?

Any help will be most appreciated!

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
