### ISSUE TITLE
Out of date docs regarding component styling

### ISSUE THREAD

**Issue by krilllind** [angular/angular#45799]
### Description

In version 12 of Angular was support to use inline sass styling in components added (`Component.styles` property), however documentation has not been updated to reflect this change. See [this document](https://github.com/angular/angular/blob/2f5fd41a1987509fc0250c1441554984b6e11abc/aio/content/guide/component-styles.md?plain=1#L281).

In the same file it is also talked about sass `@import` keyword; however this is no longer the recommended way and has been deprecated. See [timeline here](https://github.com/sass/sass/blob/main/accepted/module-system.md#timeline) for complete removal.

This feature is talked about on [this line of code](https://github.com/angular/angular/blob/master/aio/content/guide/component-styles.md?plain=1#L242) and we should instead replace this with usage of `@use` and `@forward`.

### What is the affected URL?

https://angular.io/guide/component-styles

**Comment by dario-piotrowicz** [comment]
Hi @krilllind yeah I think you're totally correct about the line being outdated

Regarding the sass `@import` however, I believe that the document is just talking about the plain css one which is (slightly) unrelated to the sass one (and not deprecated as far as I can tell)

**Comment by dario-piotrowicz** [comment]
I've been trying to look around in angular.io but I can't find any mention of the `inlineStyleLanguage` option in the whole site! :open_mouth: 

What do you think @gkalpak, could it really be that option which has been available since v12 has never made it to aio? :open_mouth: 

I don't mind adding it if that's the case (and you want me to :smile:), I might do it here or open an issue specific for that if that'd make more sense, please let me know what you think :slightly_smiling_face:

**Comment by krilllind** [comment]
@dario-piotrowicz Otherwise, I think this issue lands itself as a perfect beginner issue for those wanting to help out with Angular! Maybe tag it as "good first issue" 😊

**Comment by gkalpak** [comment]
Not sure, @dario-piotrowicz :smiley:
Since this is related to docs content (not tooling), let's wait to hear from the docs team.

**Comment by dario-piotrowicz** [comment]
@gkalpak sure, please let me know if there'll be anything I can do to help :slightly_smiling_face::+1:

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
