### ISSUE TITLE
Rails Assets gem on Ruby Gems.

### ISSUE THREAD

**Issue by BenMorganIO** [angular/angular#458]
[Rails Assets](https://rails-assets.org/) is a ruby gem to bower proxy. This makes including angular inside of rails applications easier and far more manageable.

The purpose of this issue is to notify the angular team that someone has decided to make an angularjs ruby gem on rubygems.org with the same name as the rails asset gem. Their source code points to bower-angular repo setting the version number to 9000.

https://rubygems.org/gems/rails-assets-angular

Are we able to bock people from using the "rails-assets-" prefix to ensure gems that are supposed to be fetched from rails assets, are?

**Comment by rkirov** [comment]
Sounds like an issue for AngularJs repo (https://github.com/angular/angular.js), please reopen there. This repo is for the upcoming Angular2.0
