### ISSUE TITLE
Public esbuild plugin to run the angular linker

### ISSUE THREAD

**Issue by arobinson** [angular/angular#45801]
### Description

I have managed to get a `bazel` based build working for our application using `bazel` + `esbuild`, but I still need to run `babel` to get the Ivy processing done for partial Angular libraries. The `babel` with the plugin is not very fast. I'd love to only run `esbuild` and drop the `babel` portion of the code.

I see that `@angular/dev-infra-private/shared-scripts/angular-linker` is being used in the code internally. It looks like this code can be used to run in an `esbuild` environment.

Unless I missed something, I don't see that the Angular project is providing a public `esbuild` version of the linker plugin to be able to convert all the code to Ivy compatible usage for Angular 13.

It appears that this should be possibly by looking at [this code](https://github.com/angular/angular/blob/master/devtools/tools/esbuild/esbuild-spec.config.mjs)

Please let me know if there is a way that I have not found. The only documentation I see is using `babel`, not `esbuild` as seen in the [documentation here](https://angular.io/guide/creating-libraries#consuming-partial-ivy-code-outside-the-angular-cli)

### Proposed solution

Expose a public `esbuild` plugin for the Angular linker instead of having it depend on `babel`

### Alternatives considered

1. Continue using the `babel` plugin and deal with slower build times
2. Import the internal code and use it with `esbuild`

**Comment by JoostK** [comment]
Hi @arobinson,

this is not currently feasible to implement, for two reasons:

1. esbuild's plugin model is limited to "loader-style" plugins, meaning that a plugin can only transform a file before it's bundled by esbuild. esbuild does not expose its AST to apply the linker transform from within esbuild itself and it is not a goal of esbuild to enable such plugins (esbuild's architecture is highly focused on performance, not extensibility).
2. The Angular compiler is written in Javascript today, so the linker transform needs to execute within a Javascript VM as well.

What you're seeing in [the code you linked](https://github.com/angular/angular/blob/main/devtools/tools/esbuild/esbuild-spec.config.mjs) is really just the Babel linker plugin operating as a loader plugin for esbuild. The source file on disk is first processed by Babel and its transformed result is then further processed by esbuild.

I'll refer you to #43165 for further details on being able to achieve better build performance in the future, but I'll go ahead and close this as not actionable at the moment. Feel free to follow up below if you have questions on getting the linker Babel plugin operating as esbuild plugin.
