### ISSUE TITLE
Dynamic displayed `required` + `formControlName` in template validates failed

### ISSUE THREAD

**Issue by JounQin** [angular/angular#45817]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

```html
<form [formGroup]="form">
  <button type="button" (click)="show = !show">Toggle</button>
  <input *ngIf="show" formControlName="name" required />
  {{ form.get('name').status }}
  {{ form.status }}
</form>
```

When first click `Toggle` button, it should display `INVALID INVALID`, but it is `VALID VALID` now.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-tpggkc?file=src%2Fapp%2Fapp.component.html

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/animations": "^13.3.2",
"@angular/cdk": "^13.3.2",
"@angular/common": "^13.3.2",
"@angular/compiler": "^13.3.2",
"@angular/core": "^13.3.2",
"@angular/flex-layout": "^13.0.0-beta.38",
"@angular/forms": "^13.3.2",
"@angular/platform-browser": "^13.3.2",
"@angular/platform-browser-dynamic": "^13.3.2",
"@angular/router": "^13.3.2",
"@angular/cli": "^13.3.2",
"@angular/compiler-cli": "^13.3.2",
```

**Comment by AndrewKushnir** [comment]
@JounQin thanks for providing the repro. It looks like the code mixes template-drive and reactive approaches, which is not recommended. I'd propose moving the required validator to the data model layer and dropping the `required` from the template. Here is an [updated Stackblitz demo](https://stackblitz.com/edit/angular-ivy-f9bvyj?file=src%2Fapp%2Fapp.component.ts), which seems to be working as expected when I click the toggle button.

I'm closing this ticket for now, please reopen if the problem still exists.

**Comment by JounQin** [comment]
@AndrewKushnir 

> It looks like the code mixes template-drive and reactive approaches, which is not recommended

Thanks for replying. Is there any documentation mentioned that? And there is no warning message like `disabled` template attribute in reactive forms.

**Comment by JounQin** [comment]
@AndrewKushnir 

Besides, your proposed change is not working as expected, because when `show === false`, `name` should not be `required`, I have to mark it as `disabled` on init, and toggle its disable status on `show` change, it's not much cleaner.
