### ISSUE TITLE
unable to create dynamic anchor-names for DynamicComponentLoader.loadIntoLocation

### ISSUE THREAD

**Issue by frickt** [angular/angular#4581]
I need to create unique anchor-names in a ng-for loop to use it with DynamicComponentLoader.loadIntoLocation. A litte example for that you can see below:

    <div>
      <table>
        <tr *ng-for="#vIndex of vArr">
          <td *ng-for="#hIndex of hArr">
            <div #uniqueanchorname{{vIndex}}_{{hIndex}}></div>
          </td>
        </tr>
      </table>
    </div>

the resulting html should look something like that:

    <div>
      <table>
        <tr>
          <td>
            <div #uniqueanchorname0_0></div>
          </td>
          <td>
            <div #uniqueanchorname0_1></div>
          </td>
        </tr>
        ...
      </table>
    </div>
With that I could load dynamic content with DynamicComponentLoader.loadIntoLocation into each table element. the problem is that the mustache does not get replaced:

    <div>
      <table>
        <tr>
          <td>
            <div #uniqueanchorname{{vIndex}}_{{hIndex}}></div>
          </td>
          <td>
            <div #uniqueanchorname{{vIndex}}_{{hIndex}}></div>
          </td>
        </tr>
        ...
      </table>
    </div>

Is there an other way to create anchors or to provide the DynamicComponentLoader with something else than an anchor?

see [http://stackoverflow.com/questions/32977271] for the stackoverflow question.

**Comment by mhevery** [comment]
Sorry, anchors have to be statically analyzable and hence can not be dynamically generated. Same way as you can not dynamically create local variables in programing languages.

Perhaps you can place a directive at those locations and then query for the directive using a `@Query` and retrieve the `ElementRef` that way?

**Comment by jmaronge** [comment]
Frickt,

Have you found a way to do this?  I am having the same issue.  I am using LoadIntoLocationto allow me to use the Telerik Kendo Window.  The only way to get Angular to run inside the window is to use LoadIntoLocation, but not adding dynamic elements with anchorNames limit me to only one window at a time.

**Comment by frickt** [comment]
Yes, create directives and use them as anchor.

something like that:

```
import {
  Directive, 
  Component, 
  CORE_DIRECTIVES, 
  ElementRef, 
  DynamicComponentLoader,
  Input,
  QueryList,
  ViewChildren
} from 'angular2/angular2'

@Component({
  selector: 'my-cmp',
  template: 'my component'
})
class MyCmp {}

@Directive({
  selector: '[location]'
})
class Location {
  @Input() h: number;
  @Input() v: number;
  constructor(public elementRef: ElementRef) {
  }
}

@Component({
  selector: 'my-table',
  template: `
  <table border>
    <tr *ng-for="#v of vArr">
      <td *ng-for="#h of hArr">
        <div location v="{{v}}" h="{{h}}">{{v}}-{{h}}</div>
      </td>
    </tr>
  </table>
  h:<input #hi value="1"><br>
  v:<input #vi value="2"><br>
  <button (click)="load(hi.value, vi.value)">load</button>
  `,
  directives: [CORE_DIRECTIVES, Location]
})
class MyTable {
  vArr = [1, 2, 3];
  hArr = [1, 2, 3];
  @ViewChildren(Location) locations: QueryList;
  constructor(
    private loader: DynamicComponentLoader,
    ) {
  }

  load(h, v) {
    let elementRef = null;
    for(let i = 0; i < this.locations._results.length; i++) {
       if(this.locations._results[i].h == h && this.locations._results[i].v ==v) {
         elementRef = this.locations._results[i].elementRef;
       }
    }

    if(elementRef) {
      this.loader.loadNextToLocation(MyCmp, elementRef);
    }
  }
}

@Component({
  selector: 'my-app',
  template: `<my-table></my-table>`,
  directives: [MyTable]
})
export class App {}
```

**Comment by frickt** [comment]
see http://stackoverflow.com/questions/32977271

**Comment by tbosch** [comment]
have a look at the new `read` property of `@ViewChild` / `@ViewChildren`
and the test 'should support reading a ViewContainer' in
query_integration_spec.ts (see
https://github.com/angular/angular/blob/master/modules/@angular/core/test/linker/query_integration_spec.ts#L378
).

With that, you can query a `ViewContainerRef` from any element, without an
additional directive.
