### ISSUE TITLE
FormControl on number input returns null value when the last character in the field is a period

### ISSUE THREAD

**Issue by DevinloperNL** [angular/angular#45812]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

When a form-control is attached to an input[type="number"], the value will immediately become `null` after typing a period.
To me this seems like unwanted behaviour, since users tend to use `.` and `,` interchangeably when typing decimal numbers.

The way I would expect this to work is the same as when a comma is used as the last character in the input field.

The current behaviour is: 
- `input` => `FormControl.value`
- `1111,` => `1111`
- `1111,1` => `1111.1`
- `1111.` => `null`
- `1111.1` => `1111.1`

Expected behaviour would be:
- `1111,` => `1111`
- `1111,1` => `1111.1`
- `1111.` => `1111`
- `1111.1` => `1111.1`

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-5388f6?file=src/index.html

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.4
Node: 16.10.0
Package Manager: npm 7.24.0
OS: darwin x64

Angular: 13.3.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.4
@angular-devkit/build-angular   13.3.4
@angular-devkit/core            13.3.4
@angular-devkit/schematics      13.3.4
@angular/cli                    13.3.4
@schematics/angular             13.3.4
rxjs                            7.4.0
typescript                      4.5.5
```

**Comment by DevinloperNL** [comment]
> Hi @DevinloperNL
> 
> I don't think Angular can do anything about it. This is just the behavior of the browser, which sets the value to an empty string for `1.` and not for `1,`. See this demo: https://stackblitz.com/edit/angular-ivy-n3bq2j?file=src%2Fapp%2Fapp.component.html

Is there a proper way to work around this?

**Comment by vbnr** [comment]
Hi @DevinloperNL 

Is still can be reproduce (the described bug) ?

I have tried the example of the link and here is the result:
![image](https://user-images.githubusercontent.com/33627564/172175331-576485f9-d20e-4fe1-bdb3-08d86b481c63.png)

**Comment by DevinloperNL** [comment]
Chromium 102.0.5005.61 (Brave Browser uses this version) still has this issue, but I noticed that never versions might have changed this behaviour.

**Comment by vbnr** [comment]
It seems that the bug is really browser specific.
Example:

**Environment**:
Browser: Firefox 100.0.2 (64-bit) canonical for ubuntu

**Steps**:
1111**,** => null
1111**,**1 => null
1111. => 1111
1111.1 => 1111.1

**Result**:
In the current test the problematic character is comma not period.

Maybe will be good to add in the environment section your browser version.
I think there is no general solution for the problem as @jnizet said.

**Comment by alxhub** [comment]
Yep - I agree that this is more of a browser problem then Angular. We _do_ consider adding workarounds to the FW if it makes sense, but I'm not sure there's anything we can do in this case.
