### ISSUE TITLE
Update error message for an unknown tag in standalone components

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#45818]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Currently the error for unknown element tags looks like follows:

```
src/app/app.component.ts:7:14 - error NG8001: 'admin-s' is not a known element:
1. If 'admin-s' is an Angular component, then verify that it is part of this module.
2. If 'admin-s' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

7   template: '<admin-s></admin-s>',
```
This error message needs to be updated for standalone components to:
* mention `@Component.imports` / `@Component.schemas' 
* _not_ mention NgModule

**Comment by AndrewKushnir** [comment]
@dario-piotrowicz just wanted to ask if you might be interested in submitting a PR to improve the error message?

**Comment by dario-piotrowicz** [comment]
> @dario-piotrowicz just wanted to ask if you might be interested in submitting a PR to improve the error message?

Of course!!! :grinning: 

Please leave this with me! :slightly_smiling_face:

**Comment by pkozlowski-opensource** [comment]
Go @dario-piotrowicz , go! I've updated the issue description (it was badly formatted, sorry about that).

The basic idea is to determine the type of a component (standalone or not) and adjust the error message based on this type (the standalone flag can be read from the component def).

 LMK if you've got any questions.

**Comment by AndrewKushnir** [comment]
Thanks @dario-piotrowicz 👍

**Comment by dario-piotrowicz** [comment]
@AndrewKushnir my pleasure, thanks for thinking of me!!! :heart_eyes:

**Comment by dario-piotrowicz** [comment]
I've opened 2 PRs, respectively for the aot and jit compilations which seem pretty self-contained

I did it so that if I am getting something wrong in one implementation at least it won't stop the other PR from progressing/change

I hope that is fine, please let me know if it isn't, in that case I can merge the two PRs into onw :slightly_smiling_face:

**Comment by AndrewKushnir** [comment]
@dario-piotrowicz great, thanks a lot for submitting 2 PRs! 👍

I had a quick look at the JIT PR and I'm sorry that it turned out a bit more involved. I was thinking that we already have the necessary information somewhere close to the code that throws an error. The change in the PR makes sense, I'll perform additional review asap and let you know if there is any additional feedback.

Thank you.

**Comment by pkozlowski-opensource** [comment]
@dario-piotrowicz oh, I didn't realize that we don't have the owning component def info when matching directives on elements :-/ Yeh, TView seems to be the best place - not happy about growing this data structure for error message purposes but can't immediately see any different solution.

In any case we will need additional tests for this change, most probably located in https://github.com/angular/angular/blob/main/packages/core/test/acceptance/standalone_spec.ts#L605
We need to make sure that an appropriate message is logged for a standalone component. There is also an interesting case to be taken into account, when an unknown element is part of an embeeded view, ex.:

```html
<can-be-unknown-in-component-view><can-be-unknown-in-component-view>
<ng-template [ngIf]="true">
   <can-be-unknown-in-embedded-view></can-be-unknown-in-embedded-view>
</ng-template>
```

**Comment by JoostK** [comment]
One way around storing it in `TView` might be to get the component definition from the `LView`'s component view context:

```ts
const declarationLView = lView[DECLARATION_COMPONENT_VIEW] as LView<Type<unknown>>;
const context = declarationLView[CONTEXT];
const def = getComponentDef(context.constructor);
const isStandalone = def.standalone;
```

**Comment by dario-piotrowicz** [comment]
@nthypes Thank you so very much, you're too kind! :pray:
