### ISSUE TITLE
run ngcc recursively

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular#45821]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler-cli

### Description

for monorepos, when you install dependencies, you don't know exactly which dependencies will be hoisted to the root workspace and whitch will be installed inside the workspace.

you need to run `ngcc` in each workspace that depends on angular libraries, this makes an issue
1- if you added `postinstall: ngcc` to each package, and it's dependencies hoisted to the root workspace, node_module dir will not be created and running `npm run postinstall -ws` will cause this error  `no such file or directory, scandir '/workspace-a/node_modules'`
2- if you removed `postinstall:ngcc` from a workspace and it's dependencies didn't hoisted, so you will have some angular libraries without running `ngcc`

### Proposed solution

**the solution** is to add `--recursively (-r)` option to ngcc, to run it in the root package and all workspaces packages

### Alternatives considered

..

**Comment by alan-agius4** [comment]
Running NGCC as a post install hook is not recommended.

NGCC will run on the needed packages when using the Angular CLI to compile your application or libraries.
