### ISSUE TITLE
alpha.39: ng-content projection is not working for all selects

### ISSUE THREAD

**Issue by adamdbradley** [angular/angular#4582]
In the example below, the third `<ng-content>` that selects by `[item-right]` is not finding children with the `item-right` attribute.

```
@Component({
  selector: 'my-item'
})
@View({
  template: `
    <ng-content select="[item-left]"></ng-content>
    <ng-content></ng-content>
    <ng-content select="[item-right]"></ng-content>`
})
export class MyItem {}


@Component({
  selector: 'my-app'
})
@View({
  template: `
  <my-item>
    <span item-left>Left</span>
    <span item-right><b>Right</b></span>

    Center
  
  </my-item>`,
  directives: [MyItem]
})
export class App {}
```

Not working in alpha.39:
http://plnkr.co/edit/PrPnQy5Timk6ZkgSFAQs?p=preview

Working in alpha.37:
http://plnkr.co/edit/SthQ8qZjRcTHe0CBqAIg?p=preview

**Comment by vicb** [comment]
Looks like a bug fix in .39: element that have already been projected can not be projected again.

`<ng-content></ng-content>` would already have projected `item-right` and it would not be projected again.

Feel free to re-open if you think something is wrong here.

**Comment by pkozlowski-opensource** [comment]
@vicb are you saying it is not a bug? I must say that while I could understand that `ng-content` "takes it all" and there is nothing more to re-project, this looks like a very valid / common use-case.

I must say that I don't know how to solve this properly here. Can we use negation in selectors?

**Comment by vicb** [comment]
> are you saying it is not a bug? 

Yep, works as expected.

> this looks like a very valid / common use-case.

Well it seems like `select` has been removed from the WC standard (using `slot` instead) because it was not that useful / used.

**Comment by pkozlowski-opensource** [comment]
@vicb I hear what you are saying. But do you have an alternative solution / suggestion for what @adamdbradley is trying to achieve? 

I must say that I've bumped into similar use-cases and had to resort to hacks / drop functionality....

**Comment by vicb** [comment]
`<span item-center>Center</span>` would be one solution but as you're in control of both the templates you can probably come with other solutions.

**Comment by vicb** [comment]
One other solution could be 
```
    <ng-content select="[item-left]"></ng-content>
    <ng-content select="[item-right]"></ng-content>
    <ng-content></ng-content>
```

+ CSS

**Comment by adamdbradley** [comment]
I guess I can see what's happening here, where the second `<ng-content>` is grabbing everything, to include the third ng-content that should be on the right. However, I think this is a valid use case where developers would want projected content to go in specific areas of their template. Up until alpha.38 this has been working great. Does alpha.39 now work the same way web components do, or does this have a different output than web components?

**Comment by vicb** [comment]
@tbosch could here to describe what has been changed and what the future plans are

**Comment by tbosch** [comment]
The above problem will stay, even with the slots proposal, as it also
distributes based on the order of the used <slot> nodes.

However, as <content> is going away as a standard, we are more free do
define our own meaning.
The right thing would be to project into ng-content elements based on the
selector specifity:
I.e. first project into an <ng-content> with a long selector, and only
project the remaining ones into the ng-content with no selector.

I created an issue to track this:
https://github.com/angular/angular/issues/4598
Adam, please feel free to +1 this other issue...

Tobias
