### ISSUE TITLE
Wrong transpilation when there's no type specified in @Input

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular#4585]
Consider the following code
```typescript
@Input() myProp; // <-- Missing type
```
It gets transpiled to
```
__decorate([
        angular2_1.Input('prop'), 
        __metadata('design:type', ) // <-- Missing type, throws Uncaught SyntaxError: Unexpected token )
    ], MyClass.prototype, "myProp");
```
But when I add a type it works nicely
```typescript
@Input() myProp: string; // <-- Missing type

// Transpiles to
__decorate([
        angular2_1.Input('prop'), 
        __metadata('design:type', String) // Yay!
    ], MyClass.prototype, "myProp");
```

Shouldn't the first case fallback to a *default* type?

I can't reproduce this in a plnkr because I can't see the transpiled code. In plnkr you get the same `SyntaxError` pointing to `@Input()`

**Comment by pkozlowski-opensource** [comment]
@ericmartinezr plunker with the syntax error would be useful as well :-)

But yeh, I can confirm that this happens - saw this today as well, but didn't have time to dig into it.

**Comment by ericmartinezr** [comment]
@pkozlowski-opensource ok then, there it goes http://plnkr.co/edit/8h7i6r?p=preview

**Comment by naomiblack** [comment]
This affects the quick reference. @IgorMinar can you have a look and potentially assign to someone for alpha-41?

**Comment by vicb** [comment]
@ericmartinezr Can you still reproduce this error ? 

This is related to TS (not Angular) and it seems to be fixed in 1.6.2 - the type would be `Object` when no explicit type is given i.e. `@Input() myProp;`

Not sure what version of the compiler is used on Plunker but it still fails there.

**Comment by ericmartinezr** [comment]
@vicb Thanks! That was the issue. I was using TS1.6.0-beta, like you said now transpiles to `Object`. I posted here thinking that ng2 may could do something about it. Thanks for the advice!

**Comment by IgorMinar** [comment]
works for me with tsc 1.6.2, plunker is using 1.6.0-beta, see #4653

**Comment by ericmartinezr** [comment]
@IgorMinar yes, I was using TS1.6.0-beta on my machine too, so I upgraded to 1.6.2 and now works nice, thanks ;)
