### ISSUE TITLE
Improve error NG2010: 'imports' is only valid on a component that is standalone.

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#45850]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Creating a component like follows:

```typescript
@Component({
  selector: 'non-standalone',
  template: '',
  imports: []
})
class NonStandalone {
}
```

will result in the following error:

```
Error: src/app/app.component.ts:7:12 - error NG2010: 'imports' is only valid on a component that is standalone.

7   imports: []
             ~~
```

This error is good (says what is going on and where it happens) but could be improved. Some suggestions:
* mention the name of a standalone component type;
* include "call to action" (ex. "Did you mean to add `standalone: true` to the `FoBarComponent`?")

@crisbeto also suggested that we might be able to constraint things on the TypeScript level.

**Comment by alxhub** [comment]
> mention the name of a standalone component type;

We explicitly don't do this in error messages as TypeScript already provides all necessary context with its highlighting and diagnostic locations. It keeps the error messages shorter and less cluttered.
