### ISSUE TITLE
FormArray is incorrectly pristine

### ISSUE THREAD

**Issue by AugustZellmer** [angular/angular#45854]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

I have a FormArray containing a FormGroup containing a FormControl. When a FormControl is edited (by the user through an `input`), the FormGroup is correctly set as dirty, but the FormArray incorrectly stays pristine.

### Please provide a link to a minimal reproduction of the bug

https://embed.plnkr.co/plunk/MemMp3sni5MEtdSV

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.2.2
Node: 14.19.1
Package Manager: npm 
OS: linux x64

Angular: 12.2.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.2
@angular-devkit/build-angular   12.2.2
@angular-devkit/core            12.2.2
@angular-devkit/schematics      12.2.2
@angular/cdk                    10.2.7
@angular/flex-layout            12.0.0-beta.34
@angular/google-maps            12.2.11
@angular/material               10.2.7
@schematics/angular             12.2.2
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by AugustZellmer** [comment]
Plunkr has a bug where you have to hit the "refresh" button once before the app will run.

**Comment by dylhunn** [comment]
You are writing directly to the `controls` field:

```ts
this.form.controls = [
  new FormGroup({
    name: new FormControl('testName')
  })
];
```

Instead, you should use any of our provided APIs, such as `push`, `setControl`, `setValue`, etc:

```ts
this.form.push(
  new FormGroup({
    name: new FormControl('testName')
  })
);
```

(We could consider adding a setter for `controls` to alleviate this error, although that might cause a lot of breakage.)

**Comment by AugustZellmer** [comment]
Okay. Thank you for explaining how to do this.

But why is it possible to use FormArray incorrectly? It should not be possible for a calling class to put a called class in an invalid state just by setting a public, settable field. 

You've helped me write my app, but you haven't fixed the problem.

**Comment by dylhunn** [comment]
> adding a setter might be the right choice here

I'm sort of inclined to agree, but it's going to cause massive breakage unfortunately. The docs we can fix though.
