### ISSUE TITLE
firebase: add support for redirects from an old link#section to a new link#section

### ISSUE THREAD

**Issue by josmar-crwdstffng** [angular/angular#45861]
### Description

Current state:

```
{"type": 301, "source": "/guide/i18n", "destination": "/guide/i18n-overview"},
```

Add support for section refs in the `source` and `destination` parameters to better handle content moves.

### Proposed solution

Add the ability to use and test uris with following structure.

```
path/to/resource#section
```

### Alternatives considered

The redirects point from a top-level to another top-level.

**Comment by bob-watson** [comment]
Lowered the priority to P4. If there is data to show how the significance of the impact of redirecting on anchors is, please attach it so we can re-evaluate the priority.
