### ISSUE TITLE
add node 18 support

### ISSUE THREAD

**Issue by damingerdai** [angular/angular#45870]
### Description

Node.js 18 is now available in 2022-04-09 and will be promoted to Long-term Support (LTS) in October 2022.
So please add node 18 support and consider dropping node14.

### Proposed solution

add node 18 support

### Alternatives considered

add node 18 support

**Comment by dylhunn** [comment]
@devversion Do you know if this is something that's already in the works?

**Comment by devversion** [comment]
@dylhunn Nothing from dev-infra on this side, but @clydin is usually the expert on our NodeJS plans.

**Comment by clydin** [comment]
Angular officially supports all Node.js versions currently in active LTS or maintenance LTS (https://angular.io/guide/setup-local#prerequisites).  From the current Node.js release calendar (https://nodejs.org/en/about/releases/), Node.js v18 will enter LTS on 2022-10-25. Based on the Angular release cadence, Node.js v18 would then be officially supported by Angular in v15 at the earliest. Node.js v14 will reach its end-of-life on 2023-04-30 and would then no longer be supported by Angular v16 at the earliest.

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
