### ISSUE TITLE
DevTools: Make each directive in the component explorer inspectable

### ISSUE THREAD

**Issue by AleksanderBodurri** [angular/angular#45882]
### Description

Currently we can inspect the source code components in DevTools by clicking the code icon on the top right of the directive inspector.
<img width="240" alt="Screen Shot 2022-05-04 at 7 37 47 PM" src="https://user-images.githubusercontent.com/39253660/166842097-2b4c2a7a-62d1-4e0d-a36f-1dd421907eac.png">

We should also be able to inspect each directive on the component/element as well. In the example above we should be able to inspect source code of NgControlStatus and NgModel.

### Proposed solution

Duplicate the inspect functionality that we're currently using for inspecting component source code for directives.

Relevant files:
https://github.com/angular/angular/blob/e4538e03d6baf3e0968a9491b70a209fb6ba5053/devtools/projects/ng-devtools/src/lib/devtools-tabs/directive-explorer/directive-explorer.component.ts#L211
https://github.com/angular/angular/blob/e4538e03d6baf3e0968a9491b70a209fb6ba5053/devtools/projects/shell-browser/src/app/chrome-application-operations.ts#L29-L38
https://github.com/angular/angular/blob/e4538e03d6baf3e0968a9491b70a209fb6ba5053/devtools/projects/shell-browser/src/app/chrome-window-extensions.ts#L48

**Comment by 0xKC** [comment]
Hi I can take this if its available

**Comment by AleksanderBodurri** [comment]
Thanks @0xKC :smile:

I've assigned it to you

**Comment by sbrshkappa** [comment]
Does 
> ...inspecting component source code for directives

 mean, viewing the source code in the sources tab?  I ask this with the understanding that "inspection" in the code seems to look up something in the elements tab.

**Comment by JoostK** [comment]
Closed per #47334, thanks @sbrshkappa!
