### ISSUE TITLE
DevTools: Create browser specific styles for chrome and firefox

### ISSUE THREAD

**Issue by AleksanderBodurri** [angular/angular#45889]
### Description

Currently Angular DevTools is designed to mimic the styling of Chrome DevTools.  Now that DevTools can be built for Firefox, we can style Angular DevTools with some browser specific styling to match the DevTools of the browser that it was built for. 

### Proposed solution

Let’s create some styles for each browser and then programmatically toggle them based on the browser environment. We can use https://material.angular.io/cdk/platform/overview to detect which browser we're running in.

**Comment by MariusTilvanDev** [comment]
Hi, I would like to take this if it is available.

**Comment by AleksanderBodurri** [comment]
@MariusTilvanDev thank you for taking this issue! I've assigned it to you.

I see you have a PR open already. Let me know when it's ready for review 😄

**Comment by MariusTilvanDev** [comment]
> 

The PR is ready for review :)

**Comment by dylhunn** [comment]
Closing, as this appears to have been fixed.
