### ISSUE TITLE
DevTools: Variables initialized to undefined appearing as [setter] in property inspector

### ISSUE THREAD

**Issue by AleksanderBodurri** [angular/angular#45888]
### Description

When a variable is initialized in a directive or component as `undefined`, it appears in the component inspector as `[setter]`.
This should be displaying as `undefined`
<img width="840" alt="Screen Shot 2022-05-04 at 10 28 12 PM" src="https://user-images.githubusercontent.com/39253660/166855602-faa7ee69-f2b7-422a-8a11-eb8010a61f4c.png">

### Proposed solution

Correct the logic in 
https://github.com/angular/angular/blob/main/devtools/projects/ng-devtools-backend/src/lib/state-serializer/serialized-descriptor-factory.ts
that determines property descriptors so that this bug does not happen anymore.

**Comment by Ahm3rIjaz** [comment]
Hi,

I am willing to fix this issue. Just want to ask that the tests also need to change after the fix or the tests remain same?

**Comment by AleksanderBodurri** [comment]
Hello @Ahm3rIjaz, thanks for taking this issue 😃

Yes there should be some new tests created in https://github.com/angular/angular/blob/main/devtools/projects/ng-devtools-backend/src/lib/state-serializer/state-serializer.spec.ts that capture the fix.
