### ISSUE TITLE
Fix async pipe so it works with Http / proper Observables

### ISSUE THREAD

**Issue by robwormald** [angular/angular#4588]
Now that Http returns Observables proper, the async pipe doesn't work with it. Should be fixed to work with either Proper Observables or our abstraction, until EventEmitter refactor is complete.

**Comment by naomiblack** [comment]
Rob and Jeff have https://github.com/angular/angular/pull/4604 that will address this. (today/tomorrow)

**Comment by jeffbcross** [comment]
Moving this into 41, working on a simple solution to manually add the combinators we need to EventEmitter without changing anything about its inheritance.

**Comment by robwormald** [comment]
fixed in #4893
