### ISSUE TITLE
Hero Search feature not available

### ISSUE THREAD

**Issue by rishabgt** [angular/angular#45918]
### Description

The Tour of heroes application provided in the angular homepage doesn't have the hero-search component up to that section but the final code review of the "Add navigation with routing" has the hero-search component code which either should be included only after adding the feature in the tour of heroes application or shouldn't be added to the final code review.

### What is the affected URL?

https://angular.io/tutorial/toh-pt5

### Please provide the steps to reproduce the issue

The issue can be seen on checking the final code review section of the "Add navigation with routing" section of the "Tour of Heroes" tutorial in the provided URL.

### Please provide a screenshot if possible

![Screenshot from 2022-05-08 10-22-26](https://user-images.githubusercontent.com/38859689/167282422-2670dede-1d47-46db-b36c-5ea86baf6244.png)

**Comment by immitsu** [comment]
It's an artifact.
Everything about `hero-search` is contained in the next chapter, [6.Get data from a server](https://angular.io/tutorial/toh-pt6#add-search-to-the-dashboard).

**Comment by gkalpak** [comment]
Thx for reporting this, @rishabgt :+1:

@immitsu, The `HeroService` is actually introduced in chapter 4 (i.e. the previous chapter).

The snippets shown in the "Final code review" section are indeed incorrect though. This is being tracked in #45736.
(Closing this issue as a duplicate.)
