### ISSUE TITLE
Build: support serving examples without a full `gulp build` again

### ISSUE THREAD

**Issue by tbosch** [angular/angular#4591]
Since https://github.com/angular/angular/commit/f7b75330e020d942be21fa704b02c57ec59a4f59, the targets `gulp serve.js.dev`, ... don't work unless a manual `gulp build` was done before.
This prevents incremental development on examples and makes debugging errors extremely hard

**Comment by IgorMinar** [comment]
all the e2e examples and tests now use bundles. we should have a way to switch between using bundle vs individual files.

supporting incremental rebundling is not an option at the moment because it takes too long

**Comment by vicb** [comment]
outdated
