### ISSUE TITLE
Improve TestBed error when standalone types are present in "declarations"

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#45923]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Currently, when standalone component/directive/pipe is present in the "declarations" field of the `TestBed.configureTestingModule`, the following error is thrown:

```
Error: Unexpected "MyStandaloneComponent" declaration in "DynamicTestModule" NgModule. 
"MyStandaloneComponent" is marked as standalone and can't be declared in any NgModule - did
you intend to import it?
```

Which is good, but we can improve it further to mention `TestBed.configureTestingModule` specifically (since this is an API that developers interact with in this case) instead of `DynamicTestModule`:

```
Error: Unexpected `MyStandaloneComponent` found in the `declarations` array during the
`TestBed.configureTestingModule` call. The `MyStandaloneComponent` class is marked as
standalone and can't be declared in any NgModule - did you intend to import it instead (by
adding to the `imports` array)?
```

Implementation note: we should probably reuse the same function that produces the error, but allow providing some specific details (as a string) about the "origin" of the error (i.e. whether it's a generic error like we have now vs some specific call, e.g. `TestBed.configureTestingModule`). Basically we can use the proposed error message and in one case we can pass the "in "DynamicTestModule" NgModule" string and in another case - "during the `TestBed.configureTestingModule` call".

**Comment by AndrewKushnir** [comment]
@dario-piotrowicz just wanted to ask if this is something you might be interested in contributing as well if you get a chance?

**Comment by dario-piotrowicz** [comment]
> @dario-piotrowicz just wanted to ask if this is something you might be interested in contributing as well if you get a chance?

yes! would love to! :smiley: 

unfortunately my coming week is looking a bit busy so I'll likely won't be able to look into this in the next coming few days, but later in the week or at the latest next weekend I can definitely spend time on it, so if that's ok, I'm all for making the change :smile:

**Comment by AndrewKushnir** [comment]
@dario-piotrowicz sure, no problem! 👍 There is no rush at all, we can improve that error message anytime and release it once it's ready (i.e. we don't need to wait for any specific release).

**Comment by dario-piotrowicz** [comment]
@AndrewKushnir Awesome! thanks! :smile:
