### ISSUE TITLE
Add transparency to image

### ISSUE THREAD

**Issue by Henry-Santa** [angular/angular#45929]
### Description

use transparency in the image for the ecosystem picture on the readme.

for example I made one here
![angular-ecosystem-logos](https://user-images.githubusercontent.com/98135968/167439152-63b9066f-0fe0-45eb-8b37-4fde02acd408.png)
and it works in dark mode and in light mode because of the transparency

### What is the affected URL?

https://github.com/angular/angular/blob/main/README.md

### Please provide the steps to reproduce the issue

Use dark mode on github and look at the readme

### Please provide the expected behavior vs the actual behavior you encountered

I expected the background to not be hardwired in.

### Please provide a screenshot if possible

<img width="488" alt="image" src="https://user-images.githubusercontent.com/98135968/167439476-c4355166-a6d2-4649-b008-69847d2751ad.png">

### Please provide the exception or error you saw

```true
none
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
no it shouldn't be browser specific
```

**Comment by kaznovac** [comment]
Decription of icons in `alt` or `title` would also ne appreciated

**Comment by MariusTilvanDev** [comment]
Hi, I would like to take this if it is available.

**Comment by gkalpak** [comment]
Fixed by #45993.
