### ISSUE TITLE
5 min quickstart JavaScript documentation shows TypeScript code

### ISSUE THREAD

**Issue by mochang** [angular/angular#4595]
[https://angular.io/docs/js/latest/quickstart.html] (https://angular.io/docs/js/latest/quickstart.html) shows the TypeScript tutorial, it should show the JavaScript tutorial.

**Comment by jigargandhi** [comment]
Shouldn't this issue be posted in [Angular.io](http://github.com/angular/angular.io/issues) as it is related to documentation?

**Comment by pkozlowski-opensource** [comment]
Yes, this belongs to angular.io
