### ISSUE TITLE
AngularJS Security Issue ReDoS

### ISSUE THREAD

**Issue by deleonio** [angular/angular#45951]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

https://github.com/advisories/GHSA-m2h2-264f-f486

### Please provide the environment you discovered this bug in (run `ng version`)

```true
AngularJS 1.8.3
```

**Comment by alan-agius4** [comment]
AngularJS support has officially ended as of January 2022.

[See what ending support means](https://docs.angularjs.org/misc/version-support-status) and [read the end of life announcement](https://goo.gle/angularjs-end-of-life).

**Comment by gkalpak** [comment]
Just to be clear, the reported vulnerability is about the discontinued [AngularJS v1.x][1] (as Alan mentioned).
This repository here is for the new Angular (v2+) that is not affected by the vulnerability.

[1]: https://github.com/angular/angular.js
