### ISSUE TITLE
Define Angular Custom element without ngModules

### ISSUE THREAD

**Issue by vugar005** [angular/angular#45969]
### Which @angular/* package(s) are relevant/related to the feature request?

elements

### Description

Hello team,
So without standalone on to define a custom element as you know we use below syntax:
```
export class AppModule implements DoBootstrap {
  constructor(private injector: Injector) {}

  public ngDoBootstrap(): void {
    const ce = createCustomElement(AppComponent, { injector: this.injector });
    customElements.define('likes-app-element', ce);
  }
}
```
But how should we do this without `NgModules`?
I tried to add above snippet to `AppComponent` but seems it does not create custom element and we receive error:
`the selector "likes-app-root" did not match any elements.`
I think this is because we already bootstrap AppComponent in main.ts file. With ngModules we could prevent bootstrapping by specifying bootstrap: [].  To prevent bootstrapping we could just create custom element in bootstrap.ts but we have to provide Injector there.
Thanks.

### Proposed solution

I think we should be able to define elements in AppComponent.

### Alternatives considered

Alternative was trying to define element in AppComponent but not working as expected.

### Version
Angular 14.0.0-rc.0
Plaground branch: https://github.com/vugar005/youtube-webapp-turborepo/tree/feature/preview-angular-v14.0.0-rc.0/apps/likes-app

**Comment by pkozlowski-opensource** [comment]
PR https://github.com/angular/angular/pull/46475 has a sketch of our initial thinking on the API, if anyone is interested. The gist of it is:

```typescript
import {createRootEnvironment} from '@angular/platform-browser';
import {createCustomElement} from '@angular/elements';

const envInjector = await createRootEnvironment({providers: ...});
const MyCustomElementCtor = createCustomElement(MyCustomElement, {injector: env});
```

The concepts / details might change but the above captures our current thinking.

**Comment by vugar005** [comment]
Hi @pkozlowski-opensource 
Thank you.
I just saw Angular 14.1.1 was released but there is no mention of angular element.
Could you tell please whether is it expected?
Thanks in advance
