### ISSUE TITLE
i18n $localize function with custom IDs when using variables inside template literals

### ISSUE THREAD

**Issue by robertmazzo** [angular/angular#45960]
### Which @angular/* package(s) are the source of the bug?

localize

### Is this a regression?

No

### Description

When calling the $localize function as follows:

When I run the `ng extract-i18` command against a bunch of $localize calls that look similar to this:

       return $localize`Must be at least ${setting.SettingValue}:minLen: characters long.`;

Angular will generate the following xlf output:

    `<trans-unit id="2927300519471273952" datatype="html">
        <source>Must contain at least <x id="nonAlphaNum" equiv-text="setting.SettingValue"/> symbols.</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/core/modals/password-edit-modal/password-edit.modal.ts</context>
          <context context-type="linenumber">105</context>
        </context-group>
      </trans-unit>`

However, if I try and use a CUSTOM ID instead - it doesn't work.
   For example, only changing the `id` attrib: `<trans-unit **id="passwordNonAlphNum"** datatype="html">`

I am using a website service to store all the source translations, so having a custom ID makes it easier to search up and distinguish btwn other related messages.

### Please provide the exception or error you saw

```true
If I use a custom ID in place of the random ID which Angular generates, then it will NOT pull the translation from the `<target>` element of my xlf.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.3
Node: 12.21.0
Package Manager: npm 6.14.11
OS: win32 x64

Angular: 13.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.3
@angular-devkit/build-angular   13.0.3
@angular-devkit/core            13.0.3
@angular-devkit/schematics      13.0.3
@angular/cli                    13.0.3
@angular/flex-layout            13.0.0-beta.36
@schematics/angular             13.0.3
rxjs                            6.6.7
typescript                      4.4.4
```

**Comment by JoostK** [comment]
I am confused; are you changing _just_ the `id` in the XLF file? If you want a custom translation id you need to include that [in the `$localize` call](https://angular.io/api/localize/init/$localize).

**Comment by robertmazzo** [comment]
> I am confused; are you changing _just_ the `id` in the XLF file? If you want a custom translation id you need to include that [in the `$localize` call](https://angular.io/api/localize/init/$localize).

Hi @JoostK 
Yes in fact I did change it in the code as well, but it doesn't appear to accept an ID with the template literal syntax - for example:

      `   return $localize`Must be at least ${setting.SettingValue}:minLen: characters long:Password Modal**@@passwordMinChars**`;`

As per their docs: `$localize `There are ${items.length}:itemCount: items`;` it does not begin with the colon character ("**:**").  

But one question please. Shouldn't I be able to simply change the randomly-generated ID to my custom ID? Or do I break Angular when I attempt to change it from:

   `<trans-unit id="2927300519471273952" datatype="html">`

to:

   `<trans-unit id="passwordNumChars" datatype="html">`

thanks,
Bob

**Comment by JoostK** [comment]
```ts
`return $localize`Must be at least ${setting.SettingValue}:minLen: characters long:Password Modal|Min num of chars@@passwordMinChars`;
```

That is not according to the documented format, where the message "metadata" should be specified as prefix of the message string, surrounded by colons.

> Shouldn't I be able to simply change the randomly-generated ID to my custom ID?

No, the ID is used for translation lookup so you can't change the translations without also changing the `$localize` call.
