### ISSUE TITLE
Content projection: prioritize ng-content projection by selector specifity

### ISSUE THREAD

**Issue by tbosch** [angular/angular#4598]
E.g.
```
<ng-content select="[item]"></ng-content>
<ng-content></ng-content>
<ng-content select="a[item]"></ng-content>
```

Here, we would first find nodes that fit the `a[item]` selector. 
Then we would use the remaining nodes and filter out the ones that match `[item]` selector.
And only the nodes that don't match any other selector would go into the `<ng-content>` without a selector.

With this, projection is independent of the order of `<ng-content>` elements.

**Comment by tbosch** [comment]
Note: This is in contrast to how the original `<content>` and the new `<slot>` elements for ShadowDom work. They always project using the order of the `<content>` / `<slot>` elements.

**Comment by adamdbradley** [comment]
+1 I think this approach is very useful for ng-content and allows devs to create templates without any gotchas.

**Comment by vicb** [comment]
/refs
- https://hacks.mozilla.org/2015/06/the-state-of-web-components/
- https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Slots-Proposal.md

> Both Apple and Microsoft pushed back on this [select] approach due to concerns around complexity and performance.

We should be careful with perf implication of whatever we choose to implement.

Let's start by collecting use cases where the selector specificity would be useful.

**Comment by tbosch** [comment]
@vicb This happens only during compilation, which eventually will be done in a build step. Also, as I know the new compiler, this will have almost no impact on the compile performance. Essentially we add the cost of one sort operation over the ng-content elements in a template, and need to calculate the specifity of a css selector that we already parsed (via `CssSelector`) as a number...

**Comment by tbosch** [comment]
Remember, our `ng-content` is very static, see https://docs.google.com/document/d/1BXUFVpImyWN7ynyPKehAesctP0UJTaDYbDTNVkarSeQ/edit

**Comment by vicb** [comment]
Useful link, thanks !

**Comment by pkozlowski-opensource** [comment]
+1, this is very common scenario. Another real-life example with a simple bootstrap panel directive: https://github.com/pkozlowski-opensource/ng2-bs/blob/master/src/panel/panel.html

**Comment by tbosch** [comment]
Pawel, but your example does not require a special projection order as the
selectors don't overlap

**Comment by pkozlowski-opensource** [comment]
@tbosch I was under the impression that with the template I've linked I would hit the same pb as described in https://github.com/angular/angular/issues/4582. From what I understand from the description in #4582 `<ng-content></ng-content>` would project everything and there would be "nothing left" for `<ng-content select="bs-panel-footer"></ng-content>`.

Anyway, I'm going to re-test my scenario with alpha.39 / alpha.40 and will report back here.

**Comment by tbosch** [comment]
We prioritize the wildcard last. Let's not change the priority for non wildcard selectors, as such selectors can be changed to be unique / non overlapping.
