### ISSUE TITLE
Conditional (ternary) operator not short-circuited in template expressions

### ISSUE THREAD

**Issue by danculley** [angular/angular#4599]
In expressions in a template, all branches of the conditional (ternary) operator are evaluated. Therefore, with an expression like the below:
```html
<button (click)="aBoolean ? doIfTrue() : doIfFalse()">Click me!</button>
```
both ```doIfTrue()``` and ```doIfFalse()``` are executed.

Here is a simple plunk demonstrating the issue: http://plnkr.co/edit/4cowZb

**Comment by ericmartinezr** [comment]
@danculley this may be related https://github.com/angular/angular/issues/3701, I have a similar problem with that too, but I'm waiting for the fix to be merged and test again.

**Comment by vicb** [comment]
At some point we had a different code path for template bindings `{{aBoolean ? doIfTrue() : doIfFalse()}}` and actions `(event) = aBoolean ? doIfTrue() : doIfFalse()` & we would short-circuit only in the later case.

As of today there is a single code path within the change and we do not short-circuit any more (both template bindings & actions have the same behavior).

@vsavkin do you remember when this change occurred ? Do we have a plan for short-circuiting in the future ?

**Comment by vicb** [comment]
See #4790
