### ISSUE TITLE
Specific keys binding on MacOs should work

### ISSUE THREAD

**Issue by GitHubish** [angular/angular#45992]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I try to subscribe to the keyboard shortcut `Alt + s` or `Alt + p` but it does not work. 
Tested on MacOs only

### Please provide a link to a minimal reproduction of the bug

https://codesandbox.io/s/amazing-nightingale-u2k92f?file=/src/app/app.component.html

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular Cli: 13
Node: 16
Package manager: yarn 1.22.10
OS: MacOs Apple Silicon
```

**Comment by GitHubish** [comment]
@jessicajaniuk I'm not trying to make a shortcut with the command key but with the Alt key, in other words on the Mac the key is called Option. So I want to make the shortcut `Alt (option) + s` for example and not `Command + s` (command which corresponds to the Windows key).

**Comment by jessicajaniuk** [comment]
@GitHubish Thanks for the clarification.

**Comment by jessicajaniuk** [comment]
This looks like it's a bug in how we parse the presses. It's seen as `ß` instead of `s`. A workaround for now would be to listen to `keydown` and match the key codes in the event handler.

**Comment by JoostK** [comment]
I think it's because you get ß when typing option+S on Mac, so that is also the key that's triggered by the browser event. Binding a listener to `keydown.alt.ß` does trigger the listener.

**Comment by jessicajaniuk** [comment]
@JoostK It seems to see that it's `KeyS` though, which is interesting. The full output looks like `{isTrusted: true, key: "ß", code: "KeyS", location: 0, ctrlKey: false…}`. Perhaps we should be relying on the `code` rather than the `key`.

**Comment by GitHubish** [comment]
exactly. The problem is that depending on the language of the user and I imagine if his keyboard is in Azerty, Qwerty or other the character is not the same. By doing `Option + s` I get the character : Ò

I think that it should be based on the property `code: "KeyS"`.

**Comment by jessicajaniuk** [comment]
@GitHubish The fix for this just landed in `main`. I'll put up a PR this week adding documentation on how to use the keyboard event code properly so it's clear.

**Comment by GitHubish** [comment]
@jessicajaniuk Great thanks!
