### ISSUE TITLE
"providedIn and NgModules" part in documentation is misleading. 

### ISSUE THREAD

**Issue by ArtemFrontendACTUM** [angular/angular#46002]
### Description

"providedIn and NgModules" part in documentation is misleading. 

This part of the documentation describing approach that could not be achieved in Angular since version 6+;
Please remove it to not confuse the developers community.

https://angular.io/guide/providers#providedin-and-ngmodules

The relevant issues are opened and not solved for years:

https://github.com/angular/angular/issues/25784

### What is the affected URL?

 https://angular.io/guide/providers#providedin-and-ngmodules

### Please provide the steps to reproduce the issue

Steps described in the docs themselves.

**Comment by jessicajaniuk** [comment]
@ArtemFrontendACTUM We actually use a [similar pattern in FormBuilder](https://github.com/angular/angular/blob/6952a0a3e68481564b2bc4955afb3ac186df6e34/packages/forms/src/form_builder.ts#L81-L82), and we're unclear why this pattern wouldn't work in Angular 6+. Is it just that it's unclear? Could you provide a reproduction for us?

**Comment by ArtemFrontendACTUM** [comment]
> @ArtemFrontendACTUM We actually use a [similar pattern in FormBuilder](https://github.com/angular/angular/blob/6952a0a3e68481564b2bc4955afb3ac186df6e34/packages/forms/src/form_builder.ts#L81-L82), and we're unclear why this pattern wouldn't work in Angular 6+. Is it just that it's unclear? Could you provide a reproduction for us?

For me it's also unclear why this pattern wouldn't work. But it doesn't work.
Because this is internal code and it compiled differently via `ng-packager` as a library, unlike real application which compiled via ng `@angular/compiler`. Library compilation is different.

But I will provide the reproduction shortly.

**Comment by alxhub** [comment]
`@angular/forms` is published as a library with `ng-packagr` and uses this pattern, so empirically it does work, at least in some cases. If you have a reproduction that would be great, as we can look into it and see if there are any parts of the configuration which might be causing it to not work.

**Comment by alxhub** [comment]
Closing as no reproduction was provided.
