### ISSUE TITLE
runGuardsAndResolvers documentation doesn’t clearly describe when it’s used

### ISSUE THREAD

**Issue by thavus** [angular/angular#46001]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

The Documentation suggests that you can supply a function to [runGuardsAndResolvers ](https://angular.io/api/router/RunGuardsAndResolvers). The link will take you to the documentation where it gives the type.

So I supplied the following and saw that not only was my route guard still being run, but the console log was not output.
```
((from: ActivatedRouteSnapshot, to: ActivatedRouteSnapshot) => {
          console.log(from,to);

          return false;
})
```

It seems something is not working as described in the documentation. So either it's a bug or the documentation is misleading?

### Please provide a link to a minimal reproduction of the bug

I don't have time to do this. I'll figure out another solution if needed.

### Please provide the exception or error you saw

```true
There were no errors. The guards ran when they should not have.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.6
Node: 16.14.0
Package Manager: npm 8.3.1
OS: win32 x64

Angular: 13.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.6
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.2.6
@angular-devkit/schematics      13.2.6
@angular/cdk                    13.3.6
@angular/cli                    13.2.6
@angular/flex-layout            13.0.0-beta.38
@angular/material               13.3.6
@schematics/angular             13.2.6
rxjs                            7.5.5
typescript                      4.5.5
```

### Anything else?

I have seen runGuardsAndResolvers work in an older version of angular, but it was about a year and a half ago since I implemented that and it was for a different website.

**Comment by thavus** [comment]
I was able to do what I need with resolvers, but it seems extremally hacky to do it this way because a resolver is a not a route guard. T_T

**Comment by thavus** [comment]
Ah and if it helps narrow this down. This is how my route looked before the resolver fix:
```
RouterModule.forChild([
      {
        path: '',
        pathMatch: 'full',
        component: StoryDetailsComponent,
        canDeactivate: [UnsavedDataGuard, RequiredDataGuard],
        runGuardsAndResolvers: ((from: ActivatedRouteSnapshot, to: ActivatedRouteSnapshot) => {
          console.log(from,to);

          return false;
        }),
        data: { animation: 'story-details' }
      }
    ])
```

UnsavedDataGuard returns a Promise<boolean> and RequiredDataGuard returns a boolean. All my routes are lazy loaded and they work fine as far as I can tell.

**Comment by thavus** [comment]
Found a better solution which let me use only the route guard. 
![image](https://user-images.githubusercontent.com/35311178/168492783-4b898ceb-d753-45e9-ac54-f2e1736a8a4a.png)

This does exactly what I need and does not rely on resolvers and does not rely on runGuardsAndResolvers, which does not appear to be working. Hopefully this helps someone else who gets stuck on this. :)

**Comment by atscott** [comment]
This is an issue with the documentation. RunGuardsAndResolvers only applies when the navigation doesn’t change the activated route. Probably would have been better named “rerunGuardsAndResolvers”.

**Comment by najmiehsa** [comment]
@atscott Hi, the documentation for ``RunGuardsAndResolvers`` is archived and read only. How can I edit that?

**Comment by atscott** [comment]
@najmiehsa Documentation is generated from the JSDoc comments [here](https://github.com/angular/angular/blob/b7394bf77f1444611cf1cb74d7629e9a243e141f/packages/router/src/models.ts#L143-L152) and [here](https://github.com/angular/angular/blob/b7394bf77f1444611cf1cb74d7629e9a243e141f/packages/router/src/models.ts#L494-L501)

**Comment by yndue736** [comment]
This is very similar issues that I am facing here but recently took some content from [best garden scooter](https://gardenvila.com/best-garden-scooter/) blog you can click here and suggest me about it.

**Comment by najmiehsa** [comment]
This is a poor way of attempting to build a link to your blog!

**Comment by najmiehsa** [comment]
This is the relevant documentations for this issue:

  * - `RunGuardsAndResolvers`: Will always run when a route is activated or
 * deactivated or, when a navigation causes a change in the active route. In case
 * where a route is unchanged, the default behavior is the same as `paramsChange`.

 * By default, guards and resolvers run only when the matrix parameters of the route change.
   * `paramsChange` : In case of no mode specification `paramsChange` is
   * the default mode. Rerun the guards and resolvers when path or
   * path param changes. This does not include query parameters.

   * - `pathParamsChange` : Rerun guards and resolvers when the path params
   * change. This does not compare matrix or query parameters.
   * - `paramsOrQueryParamsChange` : Run when path, matrix, or query parameters change.
   * - `pathParamsOrQueryParamsChange` : Rerun guards and resolvers when the path params
   * change or query params have changed. This does not include matrix parameters.


Make sure you format it before submitting a PR.
