### ISSUE TITLE
Improve error message when adding a non-standalone component into @Component.imports

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#46004]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

Consider the following example:

```typescript
@Component({
  selector: 'non-standalone',
  template: `I'm NOT standalone`,
})
export class NotAStandalone {
}

@NgModule({
  declarations: [NotAStandalone],
})
class AModule {
}

@Component({
  selector: 'app-root',
  template: `...`,
  standalone: true,
  imports: [NotAStandalone],
})
export class AppRoot {
}
```

It will result in the following error:

```
Error: src/main.ts:39:13 - error NG2011: The component 'NotAStandalone' appears in 'imports', but is not standalone and cannot be imported directly.

39   imports: [NotAStandalone],
               ~~~~~~~~~~~~~~

  src/main.ts:19:7
    19 class AModule {
             ~~~~~~~
    It's declared in the NgModule 'AModule', but is not exported. Consider exporting it.
```

This is a good suggestion since indeed the `NotAStandalone` will have to be exported from `AModule`. But this error doesn't tell users that they will have to import the `AModule` instead of `NotAStandalone` - which is the follow up action that will have to be performed.

Adding `NotAStandalone`  to the `AModule` exports will result in an actionable message:

```
Error: src/main.ts:40:13 - error NG2011: The component 'NotAStandalone' appears in 'imports', but is not standalone and cannot be imported directly.

40   imports: [NotAStandalone],
               ~~~~~~~~~~~~~~

  src/main.ts:20:7
    20 class AModule {
             ~~~~~~~
    It can be imported using its NgModule 'AModule' instead.
```

Maybe we could combine the 2 steps (export  'NotAStandalone' _and_ import `AModule`) into one error message?

**Comment by dario-piotrowicz** [comment]
I wouldn't mind giving this one a try :slightly_smiling_face:
