### ISSUE TITLE
DevTools | Settings options storage

### ISSUE THREAD

**Issue by WarGreyGon** [angular/angular#46019]
### Description

Currently, Google Chrome´s Angular DevTools settings are not saved anywhere loosing selections each time the browser reloads, e.g.

**Dark mode enabled** 

![image](https://user-images.githubusercontent.com/24290388/168784035-10f6adc3-d504-46cc-923d-08227470e140.png)

**Browser refresh (e.g. each time you make a change in your lovely Angular application)**

![image](https://user-images.githubusercontent.com/24290388/168784354-3bf86274-a93c-4951-ba47-29076872c443.png)

Dark mode is disabled again

### Proposed solution

Store user preferences in user device storage like other Google Chrome extensions (such as Redux DevTools) in C:\Users\{user}\AppData\Local\Google\Chrome\User Data\Default\Extensions

### Alternatives considered

NA

**Comment by AleksanderBodurri** [comment]
@WarGreyGon Angular DevTools is currently using [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) to toggle between light mode and dark mode. It's surprising to me that the styles would be reset to light mode (Chrome DevTools looks like its in dark mode in the second picture). Is Angular DevTools not respecting the color scheme configured in your OS or user agent?

**Comment by WarGreyGon** [comment]
@AleksanderBodurri I must qualify my issue description. I am facing this issue in [Ghost Browser](https://ghostbrowser.com/). 

As you mentioned, Google Chrome browser behavior is exactly as you described, where theme is set based on my OS preferences. However this value (In my case Dark Theme as my OS) cannot be overwritten, e.g. 

- Open Angular DevTools
- Dark Theme is set by defaul
- Switch to Light theme and refresh browser
- Dark theme is back 

Could my proposal solve my issue in both browsers? 🤔

**Comment by AleksanderBodurri** [comment]
Implementing this feature would require us to review our policy on storing data on user devices. Currently DevTools does not store any data. 

Given this, and that the current behaviour in DevTools is intentional and consistent across browsers, I'm going to close this issue for now
