### ISSUE TITLE
Add FormControl constructor for FormControlOptions and Validators

### ISSUE THREAD

**Issue by jmcooper** [angular/angular#46024]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

The strongly typed forms in [v14.0.0-rc.0](https://github.com/angular/angular/releases/tag/14.0.0-rc.0) allow for a FormControlOptions object to be passed in to the FormControl constructor in order to enable initialValueIsDefault. There are three constructor overloads, but, unless I'm missing something, none of them allow for providing FormControlOptions AND Validators, which seems like a common need. I also don't see a way to add FormControlOptions after construction (although I could add validators after construction). 

### Proposed solution

Add a constructor for FormControl(value, Validators, FormControlOptions).

### Alternatives considered

I don't see a way to add FormControlOptions after construction. I could add validators after construction, but this seems much more verbose than being able to add them via the constructor.

**Comment by JoostK** [comment]
`FormControlOptions` extends from `AbstractControlOptions`, which has all the validator fields. Does that work for you?

**Comment by jmcooper** [comment]
Ah, yes. Sorry, I missed that you can pass validators on the FormControlOptions. 

It is still more a little more verbose, though, to pass via options:
```
firstName: new FormControl('', {
  initialValueIsDefault: true,
  validators: Validators.required,
})
```

vs. 

```
firstName: new FormControl('', Validators.required, {initialValueIsDefault: true})
```

I can see, though, how a constructor that allows both would add opportunities for conflicts with setting validators both in the options and in a separate constructor parameter.

**Comment by JoostK** [comment]
> It is still more a little more verbose, though, to pass via options:

This is intentional, though. Optional arguments become cumbersome when there's multiple of them, so we prefer to use object literals to specify optional options. This allows for extending the API with additional optional options in future versions, exactly what happened with `initialValueIsDefault` hence everything got combined into an object now.

**Comment by AndrewKushnir** [comment]
Closing this ticket based on the conversation above (no action items for the framework).
