### ISSUE TITLE
Angular Universal: HTTP requests in lazy-loaded modules only run if there are HTTP requests in AppModule

### ISSUE THREAD

**Issue by paulheising** [angular/angular#46025]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Scenario as follows:

- Angular app with lazy-loaded module
- Angular Universal set up
- Lazy-loaded module loads data via `HttpClient` and attempts to show this data in its HTML template
- `AppModule` (the bootstrapped root module) doesn't

When I inspect the HTML delivered by the server (for the lazy-loaded route), I realize:

- It contains the basic HTML from the lazy loaded module, but the async data, loaded via HTTP is missing in the template
- When I add some logging to the lazy component, I can see it executes the ngOnInit, where the HTTP call is invoked, and it also executes ngOnDestroy server side, *before* it gets a response from the external API
- The full app's HTML is delivered to the client before the external HTTP call is resolved
- However, if we also add an HTTP call to the AppComponent, it would also await the HTTP call in the lazy component and show the data in the HTML

## Expected behaviour

- It should always contain the HTML generated from the HTTP call in a lazily loaded module, even if there is not HTTP call in the app modules

## Example output from the sample app I provided

The order of outputs is not quite what I expect:

```
GET /bar

BarComponent init, triggering HTTP call now

BarComponent destroyed

res.render callback - response will be sent to client now!

BarComponent received the result from the HTTP call
```

But if I add an HTTP request to the `AppComponent`, like described above:

```
GET /bar

BarComponent init, triggering HTTP call now

BarComponent received the result from the HTTP call

BarComponent destroyed

res.render callback - response will be sent to client now!
```

This is basically what I always expect, no matter if AppComponent makes API calls or not.

### Please provide a link to a minimal reproduction of the bug

https://github.com/paulheising/ng-universal-lazy-loading-bug

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.3.5
Node: 16.15.0
Package Manager: npm 8.5.5
OS: linux x64

Angular: 13.3.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.5
@angular-devkit/build-angular   13.3.5
@angular-devkit/core            13.3.5
@angular-devkit/schematics      13.3.5
@angular/cli                    13.3.5
@nguniversal/builders           13.1.1
@nguniversal/express-engine     13.1.1
@schematics/angular             13.3.5
rxjs                            7.5.5
typescript                      4.6.4
```

**Comment by paulheising** [comment]
Found a workaround: It is possible to load the data for the lazy route with a resolver - then, server side data is also filled, even if there is no HTTP request made in AppComponent

**Comment by jessicajaniuk** [comment]
Angular Universal is a separate repository at https://github.com/angular/universal, and the issue seems to be there. Closing, but feel free to open an issue in that repo.

**Comment by paulheising** [comment]
Thanks, I'll do it

**Comment by paulheising** [comment]
For the sake of completeness, I'll just link the new issue in the universal project here: https://github.com/angular/universal/issues/2656
