### ISSUE TITLE
Get Element Reference of a DOM Element created dynamically from a library.

### ISSUE THREAD

**Issue by ShantanuParode** [angular/angular#46033]
### Which @angular/* package(s) are the source of the bug?

elements

### Is this a regression?

No

### Description

I want to add a class to a DOM Element by taking it's reference. But the element is created by a library and I cannot access it directly, means I can't use ViewChild or HostBinding on that DOM Element. 

I can access it directly using document.querySelector(<.classname>) and then add another class to it. But it is Javascript, right?
Is there any way to do it in Angular? How to do DOM Manipulation for a dynamically created DOM Element not having an id or #reference?
 
I want to add a class "hidden" to image layer element of Openlayers. I am using the above method but how to do it in angular?

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

You can just use regular DOM APIs to query for the desired elements; Angular doesn't provide mechanisms to access nodes in other components, as that breaks down the encapsulation of a component.
