### ISSUE TITLE
bug(pipe): currency pipe missing whitespace on negative amount

### ISSUE THREAD

**Issue by DwieDima** [angular/angular#46038]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

When you use currencies, where the symbol is on the left side, there is no whitespace between the symbol and amount, when amount is negative.

Example negative:
<img width="95" alt="image" src="https://user-images.githubusercontent.com/26873275/169091622-d4c1fb34-62f8-40a5-bb50-fb747e209ef1.png">

Example positive:
<img width="95" alt="image" src="https://user-images.githubusercontent.com/26873275/169092158-3ee6e82f-4105-406b-80a5-46f2d96bf9de.png">

Expected when negative:
<img width="95" alt="image" src="https://user-images.githubusercontent.com/26873275/169092082-41cbae38-275c-4a6f-8f5b-e65029588c2f.png">

### Please provide a link to a minimal reproduction of the bug

app.module.ts:

```typescript
import { CurrencyPipe, registerLocaleData } from '@angular/common';
import localeCh from '@angular/common/locales/de-CH';
import localeChExtra from '@angular/common/locales/extra/de-CH';
import { DEFAULT_CURRENCY_CODE, LOCALE_ID, NgModule } from '@angular/core';

registerLocaleData(localeCh, localeChExtra);

@NgModule({
  ...
  providers: [
    { provide: DEFAULT_CURRENCY_CODE, useValue: 'CHF' },
    {
      provide: LOCALE_ID,
      useValue: 'de-CH',
    },
    CurrencyPipe
  ]
})
```

app.component.html

```html
<!-- CHF-300.00 -->
<div>{{ -300 | currency }}</div
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.3
Node: 16.14.2
Package Manager: npm 8.5.0
OS: darwin arm64

Angular: 13.2.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
```

### Anything else?

My current workaround is to override the currencyPipe:

```typescript
import { CurrencyPipe } from '@angular/common';
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'currency',
})
export class CurrencyOverridePipe implements PipeTransform {
  public constructor(private currencyPipe: CurrencyPipe) {}

  public transform(
    value: string | number,
    currencyCode?: string,
    display?: string | boolean,
    digitsInfo?: string,
    locale?: string,
  ): string {
    const result = this.currencyPipe.transform(
      value,
      currencyCode,
      display,
      digitsInfo,
      locale,
    );
    // if the value is negative add whitespace between currency and amount
    if (+value < 0) {
      return result.replace(/-(?=[^-]*$)/, ' -');
    }
    return result;
  }
}
```

**Comment by jessicajaniuk** [comment]
@DwieDima Could you create a reproduction of this within stackblitz? That would be really helpful for us to debug this.

**Comment by DwieDima** [comment]
@jessicajaniuk sure here's the link:
https://stackblitz.com/edit/angular-ivy-kgttd3?file=src/app/app.component.html

**Comment by JoostK** [comment]
Relates to #33803.

**Comment by JeanMeche** [comment]
For what it's worth, `(-1000).toLocaleString('de-CH', {style: 'currency', currency: 'CHF', currencyDisplay:'code'}) ` returns `'CHF-1’000.00'` on Chrome, Firefox and Safari.

**Comment by JeanMeche** [comment]
The latest CLDR has following for `de-CH` currencies : 

`"¤ #,##0.00` and `¤-#,##0.00`

So I'd say `CHF-310.00` is expected !

**Comment by JeanMeche** [comment]
I'll close this as this is related to the CLDR. And if it is a real bug, it should reported there.
