### ISSUE TITLE
Implement ZoneScheduler for Observable / EventEmitter integration

### ISSUE THREAD

**Issue by robwormald** [angular/angular#4603]
Background: see insightful / useful comment from @bman654 here https://github.com/angular/zone.js/issues/51#issuecomment-118863100

My initial thoughts are this could provide nice performance and testability boosts - most Observable things can run outside the zone / not trigger UI updates, and things like the async pipe would provide an easy way to hook into the appropriate zone. As we have an internal implementation of Observable/EventEmitter this would provide a nice place to implement this. 

Additionally we could possibly leverage the virtual scheduler in tests for more fine grained control.

cc @jeffbcross @vsavkin @jeffbcross - could use some of your brainpower here

**Comment by endash** [comment]
I just wrote this up this morning, describing issues I've been running into that ZoneScheduler would solve: https://gist.github.com/endash/1f961830d0c5b744598a

**Comment by jeffbcross** [comment]
@robwormald I guess I got double-mentioned here, so I have to reply.

To make sure I follow, you're saying the performance benefit would be that we can avoid intermediate digests while an observable chain is progressing with async tasks as part of the chain? This would be great. I don't think the implementation could rely on the `async` pipe though.

TBH zones are kind of mysterious to me, so I'm not sure how the zone scheduler implementation would actually achieve this, but this would be great to have.

**Comment by mleibman** [comment]
What is the status of this?

I am currently hitting the issue described in https://github.com/angular/zone.js/issues/51.
According to Misko (https://github.com/angular/zone.js/issues/51#issuecomment-150346946), callbacks should always run in the same zone as when it was registered, regardless of what scheduler is running, but that doesn’t seem to be happening.  They run in the angular zone, but they do not run in the zone in which they were registered.

**Comment by splincode** [comment]
@robwormald Is the issue relevant?
