### ISSUE TITLE
http: improve error message with null header

### ISSUE THREAD

**Issue by mgechev** [angular/angular#46048]
### Description

When a header value of an HTTP call is `null` we throw a `TypeError`: `Cannot read properties of null (reading 'length')`.

That's accurate and could be more useful if we also specify the header with `null` value.

You can find a reproduction [on StackBlitz](https://stackblitz.com/edit/angular-ivy-cjwehw?file=src%2Fapp%2Fapp.component.ts).

Based on a discussion on Twitter [here](https://twitter.com/SureshNagar21/status/1527031130339221505).

### Proposed solution

Throw an error `Cannot read the "length" property of the header "bar" because it has value null`

### Alternatives considered

Stricter typings of the `headers` so that we can show a type error.

**Comment by varthc** [comment]
Oh please, a big yes to this! This was a bug I came across like 6 months ago and it was a really pain in the neck to debug (value was null for some users not all).
