### ISSUE TITLE
[pipes] chaining a pipe after slice

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#4605]
Chaining a pipe after a `slice` is broken:

    {{ users | slice:0:1 | json }} // outputs [object Object]

See here for quick repro http://plnkr.co/edit/UFrCtQ?p=preview

**Comment by vicb** [comment]
What you are printing is `{{ users | slice:0:1|json } }}` 

You should add parents `{{ (users | slice:0:1) | json }}`

**Comment by gkalpak** [comment]
It sounds like a pain when chaining multiple pipes (which is quite common).
Couldn't the associativity be changed, so that it is possible to chanin pipes without needing paranthesis ?

**Comment by pkozlowski-opensource** [comment]
@gkalpak exactly my thoughts. Especially that it works just fine in ng1.

I'm going to re-open this one, @vicb let's have some more conversation on this one.

**Comment by Gillespie59** [comment]
@gkalpak :+1: We should have exactly syntax than the one we currently have in angular 1 !

**Comment by mhevery** [comment]
Agreed, the parenthesis should not be necessary.

**Comment by wardbell** [comment]
FWIW, the problem appears limited to pipes with parameters. `This works fine: <div>{{ title | uppercase | lowercase }}</div>`
