### ISSUE TITLE
Add variable prefix to angular routing not working children's routes

### ISSUE THREAD

**Issue by solangeDev** [angular/angular#46064]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I added prefix using providers in my app-routing.module.ts. This prefix is a variable string value

app-routing.module.ts.

```ts
const routes: Routes = [
  { path: '404',
    component: NotFoundComponent
  },
  {
    path: '',
    loadChildren: () => PosClientModule,
    canActivate: [AuthGuard],
    data: {acl: 'pos:view'}
  }
];

@NgModule({
  imports: [RouterModule.forRoot(routes,{ onSameUrlNavigation: "ignore" })],
  exports: [RouterModule],
  providers: [{ provide: APP_BASE_HREF, useValue: `${version ? '/' + version : ''}/pos-clients` }]
})
export class AppRoutingModule {}
```

pos-client-routing.module.ts

```ts
const routes: Routes = [
  {
    path: 'open',
    component: OpeningComponent
  },
  {
    path: 'close',
    component: CloseComponent
  },
  {
    path: 'quotes',
    loadChildren: () => QuotesModule,
    canActivate: [AuthGuard],
    data: {acl: 'pos:view'},
  },
  {
    path: 'payment',
    loadChildren: () => PaymentModule,
    canActivate: [AuthGuard],
    data: {acl: 'pos:view'}
  },
  {
    path: '',
    component: ListComponent
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class PosClientRoutingModule {
}
```

quotes-routing.module

```ts
const routes: Routes = [
  {
    path: '',
    component: QuoteComponent,
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class QuotesRoutingModule {
}
```

But when try redirect a quote path using `this.route.navigate(['quotes'])` or I do request by url "https://app.metises.com/unstable/pos-clients/quotes" the app doesn't recognize the url, I have this error

```
"instrument.js:109 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'unstable/pos-clients/quotes'"
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.1
Node: 14.16.0
Package Manager: npm 8.1.3
OS: linux x64

Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1301.1 (cli-only)
@angular-devkit/core         13.1.1 (cli-only)
@angular-devkit/schematics   13.1.1 (cli-only)
@schematics/angular          13.1.1 (cli-only)
```

**Comment by atscott** [comment]
I'm sorry but we can't reproduce the problem you are reporting. We require that reported issues have a minimal reproduction that showcases the problem. I attempted to reproduce this in https://stackblitz.com/edit/angular-ivy-wuzgvt?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html but it behaves as expected.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template that include info on how to create a reproduction using our template.
