### ISSUE TITLE
@Attribute decorator should be able to use parameter name for its name property

### ISSUE THREAD

**Issue by Gillespie59** [angular/angular#4607]
Right now, we have to specify the attribute name as a parameter of the @Attribute decorator. 

```typescript
@Directive({selector: 'input})
class Component {
   constructor(@Attribute('type') private type:String, private element:ElementRef){
		if(type === 'date') {
		}   		
   }
}
```

It would be very interesting to be able to specify this attribute name directly by naming correctly the corresponding parameter, in order to avoid duplicates code. 

So for example : 

```typescript
@Directive({selector: 'input})
class Component {
   constructor(@Attribute() private type:String, private element:ElementRef){
		if(type === 'date') {
		}   		
   }
}
```

What do you think ?

**Comment by mgechev** [comment]
It makes sense to me. I think this is already supported by some property decorators (such as `@Input` and `@Output`).

**Comment by pkozlowski-opensource** [comment]
Would this "survive" minification?  And what about attribute names that are not valid JS identifiers (ex.: `foo-bar`)?

**Comment by mgechev** [comment]
@pkozlowski-opensource the attribute names, which are not valid JS identifiers could be normalized to lowerCamelCase (like the HTML property names normalization), no?

Minification definitely seems like a valid point.

**Comment by pkozlowski-opensource** [comment]
> @pkozlowski-opensource the attribute names, which are not valid JS identifiers could be normalized to lowerCamelCase (like the HTML property names normalization), no?

Of course, but this introduces yet another thing to remember

**Comment by mhevery** [comment]
We will not be taking on such tricks as they are not consistent, and not possible in all supported platforms (ie Dart)
