### ISSUE TITLE
Allow `inject` to receive multiple inject flags

### ISSUE THREAD

**Issue by EricPoul** [angular/angular#46075]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

The `inject` function accepts 2nd argument `flags`, which is a plural form and it's confusing because I can pass only one flag. 
Also(as a suggestion to discuss) we can have better typings here. We can explicitly return `T | null` only if we pass `InjectFlags.Optional`. I think it will be much safer and more explicit.

[playground with typings](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAE2AYwDYEMrDgSwHYzBQBm6y2AKgJ5jAA8FAfHKIXggM5wBiArnshg4IeOAG8AUHGlw8wAO5wAFADo1mAOYcAXHHR4qAbQC6ASl0UA3BIC+EiaEixEKDFlwEipcnACCAIw4YKDIYaloGZlZgdi4+ASERcSkZMCgIGAyaYAtrOwdwaHgkNExsUo4uAEk8ACsURLwKCABrGMjkmTg0jIbgBDgAfSQOZF0gqHwNay6sdAQRVCo4QFcgHoA3XX4WvAh5PGsU6WQRCd5BaCVh4FHx4KmAGjgIMEaOAH5dSS6ujZwkBA1T5wcL0fRUZgAHzgAHJ0hkYXBoTCwBgYMRoABbRHI8E42S8VCoGY-aTeTJQKi6JSmOAAXmYViOcBsphJ0kyAGV7ngNDS7pNeXl7I4ii5Su4YrxMXAavVBNwMFpOjIACLAUiE+B0uAABgezIAEhAgvS4ABGA1dTnAVDEM0AJitMk5LRwYBtdrNABZndIAPKvYR4dCoM0ADlsIsKzhKbmwMGycAACul1v8iM02ngOjrQR1oQEJqF80wkbK6g1g1n2kxDhJE7Q-FAQlQAKKoYCYmIwOi+FvoKiglggNicODbXb7EzMHX91vD6KxZutuj4YhEOAdrs90HMd5bzvdgjD3RydZEQ6i2OuMpwYj8QTB1YrfDy3tMJSZbO6VMQdNIFANY5kw5ggleMbFLe7gPgkz4rK+laCAwTyciOY7VEhMCKugWiMF+rQxL+aYZkBhEgYwTzEEqHy6JyYFoUu45yg0OFaCogaNKGcAHhQ5Z4ISYa5NGThQRK2CwU+SQIW+DQoXAjGjjE47zoO27Hr2LEKjRM74d+REpiRgHAZEVE0cCaHQpyJgMehymYe+bEcBxQYiNxvH8YJcDCRIFRcBQNzwGI+QAPQhXAWAwLwUCiAFQS+ac8DoGaMlYUocUwGyEhhRFwBRTFIKBQleCmv4KWIe+6WBU8WnYTRKiesQWU5ZF0WxUVJwlfAyDlbJghVUETyGLVTkNbaxBmNYLV5W1hXxZ1poDDqqWVRlQ0jfV6qaqgMA1Vho2uu6jV7Y59XGkEk3ZeFrUFRlnlEsVprYMtFUNANu0VqduHOZxwahs110zbdgX3agj3wPaL19TA73rft9W-W5qCXdN+Xtaa0ICQ9C3wBovVpWtcDDfD31jXaJ2sQjrkhsjAO5Wjc3wJjgng3AAAW+OrdVRMbaTiM0xT2mk41KOAwzd3M9jiW4Jzb2E8TX3scdn2U3z1OhoLdWk+dMCi-Ts0SwSUtdXAtSy-18u80r42a6NOu21TXG09YQA)

### Proposed solution

There're cases where I what to use this `inject` function like that:
`inject(TOKEN, InjectFlags.Optional)`
`inject(TOKEN, [InjectFlags.Optional, InjectFlags.Self])`

### Alternatives considered

If wee need `InjectFlags.Optional` being always first then make explicit typings is even easier

**Comment by eneajaho** [comment]
You can provide multiple Inject flags like this: 

```ts
inject(TOKEN, InjectFlags.Default | InjectFlags.Host)
```

**Comment by EricPoul** [comment]
Oh, it works in this way, didn't know, thanks. But I guess this way we can't make a return type more explicit

**Comment by JoostK** [comment]
Closing in favor of #46075 as it is already possible to provide multiple flags using a bit mask; #46075 is about excluding `null` from the return type if `Optional` is not provided.
