### ISSUE TITLE
Systemjs is not loading well the dependencies (alpha 39 with cdn)

### ISSUE THREAD

**Issue by danicomas** [angular/angular#4608]
```html
<!DOCTYPE html>
<html>
<head>
  <title>Angular 2 Quickstart</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://code.angularjs.org/tools/system.js"></script>  
  <script src="https://code.angularjs.org/2.0.0-alpha.39/angular2.dev.js"></script>  
  <script src="https://code.angularjs.org/2.0.0-alpha.39/http.js"></script>  

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <style>
    html, body {
      height: 100%;
    }
  </style>
</head>
<body>
<my-app></my-app>
<script>
  	System.config({
        packages: {'': {defaultExtension: 'js'}}
      });
  System.import('app');</script>
</body>
</html>
```

![image](https://cloud.githubusercontent.com/assets/4038192/10360632/56c17a76-6da2-11e5-9312-7f78f259feb8.png)

or

```html
<!DOCTYPE html>
<html>
<head>
  <title>Angular 2 Quickstart</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://code.angularjs.org/tools/system.js"></script>
  
  <script>
	System.config({
        packages: {'': {defaultExtension: 'js'}}
      });
  </script>
  
  <script src="https://code.angularjs.org/2.0.0-alpha.39/angular2.dev.js"></script>
  
  <script src="https://code.angularjs.org/2.0.0-alpha.39/http.js"></script>  

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <style>
    html, body {
      height: 100%;
    }
  </style>
</head>
<body>
<my-app></my-app>
<script>  	
  System.import('app');</script>
</body>
</html>
```

![image](https://cloud.githubusercontent.com/assets/4038192/10360694/c9d1f496-6da2-11e5-8d58-05ceb0376fde.png)

**Comment by pkozlowski-opensource** [comment]
It doesn't look like your systemjs config is correct, see a working on in action here: https://github.com/pkozlowski-opensource/ng2-play/blob/master/index.html (alpha.39).

Send a plunk if you need more help, but above all please direct those support questions to https://gitter.im/angular/angular so we can keep GitHub issues for bug reports and feature requests. Thnx!

**Comment by danicomas** [comment]
I don't know why you close the issue :S

The same with your example:

```html
<!DOCTYPE html>
<html>
<head>
  <title>Angular 2 Quickstart</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">  

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <style>
    html, body {
      height: 100%;
    }
  </style>
</head>
<body>
<my-app></my-app>
</body>
<script src="https://jspm.io/system@0.19.1.js"></script>
<script>
    //configure system loader
    System.config({defaultJSExtensions: true});
</script>
<script src="https://code.angularjs.org/2.0.0-alpha.39/angular2.js"></script>
  <script src="https://code.angularjs.org/2.0.0-alpha.39/http.js"></script>
  <script>System.import('app');</script>
</html>
```

It doesn't work.

![image](https://cloud.githubusercontent.com/assets/4038192/10361497/c70a7dc2-6da8-11e5-8b0d-c0a482bdb395.png)

 Please don't use node_modules, use CDN's. I have changed systemjs to https://raw.githubusercontent.com/systemjs/systemjs/master/dist/system-csp-production.js but this error occurs:

![image](https://cloud.githubusercontent.com/assets/4038192/10361511/e152ebce-6da8-11e5-841a-2e3ddeef4868.png)

**Comment by pkozlowski-opensource** [comment]
I closed the issue since there is nothing we can do on the Angular side here. This is a pb of the SystemJS configuration and as such this is a support question. Such questions belong to gitter support channel and I was talking to you on gitter. I've explicitly asked you to provide a plunker so I can help you more.

In short: GitHub is not a place for support questions, let's have this conversation on gitter

**Comment by danicomas** [comment]
Ok I thought that it was a ng2 problem. Sorry @pkozlowski-opensource
