### ISSUE TITLE
Improve unknown element and property errors in JIT

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#46080]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Currently, when an unknown element or unknown property errors are thrown, there is no information about the class that owns the template where the problem happened. As a result, it's not obvious from the error message where to start an investigation, other than starting a search based on the tag name mentioned in an error (which might be problematic in case a tag is used in various templates on only some of the components are misconfigured). The proposal is to improve the error messages to also include the name of the component. 

## Unknown element error
Current state:
```
'unknown-tag' is not a known element: ...
```
Proposed error message:
```
The 'MyDialog' component template contains the 'unknown-tag' tag, but is not a known element: ...
```
## Unknown element error
Current state:
```
Can't bind to 'ngIf' since it isn't a known property of 'my-component'.
```
Proposed error message:
```
Can't bind to 'ngIf' since it isn't a known property of 'my-component', which is used in the 'MyDialog' component template.
```

Note: it's a JIT-only problem, since the AOT has a way to highlight a particular area in a template, so this extra context info is already present there.

**Comment by AndrewKushnir** [comment]
@dario-piotrowicz it looks like this improvement can be made on top of the changes from #45920, it'd add the code that obtains a declaration component class instance, which we can reference in the error message. Please let me know if you might be interested in helping with this improvement.

**Comment by dario-piotrowicz** [comment]
> @dario-piotrowicz it looks like this improvement can be made on top of the changes from #45920, it'd add the code that obtains a declaration component class instance, which we can reference in the error message. Please let me know if you might be interested in helping with this improvement.

Sure! I'd love to give this a try! :smiley:
