### ISSUE TITLE
zone-js causing message "Audit usage of navigator.userAgent ..."

### ISSUE THREAD

**Issue by arthur-clifford** [angular/angular#46092]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

zone-js as installed by the polyfills uses navigator.userAgent for a lot of its detections.

In Google Chrome it causes an "issue" pasted in the exception section below:
While a warning at the moment , it is an issue that will need to be dealt with.

The zone-js npm package points to this repo. And that is why I'm posting here. If there is a better place to post this please do as this affects all Angular projects that include the polyfill.js script that requires zone-js by default.

### Please provide a link to a minimal reproduction of the bug

Load an angular app on local host and look at the console in Chrome

### Please provide the exception or error you saw

```true
Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform

A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.

Note, when reviewing the code in the browser for polyfill.js it was referring to the zone-js code which is the only polyfill I have in my current project.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.2
Node: 14.17.0
Package Manager: npm 8.6.0
OS: win32 x64

Angular: 13.3.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.2
@angular-devkit/build-angular   13.3.2
@angular-devkit/core            13.3.2
@angular-devkit/schematics      13.3.2
@schematics/angular             13.3.2
rxjs                            6.6.7
typescript                      4.6.3
```

### Anything else?

Please don't deflect this as "just a warning" as it is a warning that zone may not work as expected in a future version or might throw worse errors. I don't like Chrome dictating rewrites of long functioning code any more than anybody else. But I'd rather not get caught in browser upgrades breaking my dependencies hell if it is at all avoidable.

**Comment by atscott** [comment]
Thanks for bringing this up. I double checked the zone.js code and verified that `navigator.userAgent` is only used to determine if the browser is IE or Edge. Regardless of what Chrome does to limit the information, this will not be an issue for the current usages.

https://github.com/angular/angular/blob/c3205d0962f1ff0d2dd4fa26c70372f6fe80f5e3/packages/zone.js/lib/common/utils.ts#L489-L515
