### ISSUE TITLE
ANGULAR JS IS SHIT - REACT 4 EVER

### ISSUE THREAD

**Issue by LucaCodez1** [angular/angular#46099]
### Which @angular/* package(s) are the source of the bug?

animations, common

### Is this a regression?

Yes

### Description

SHIT FRAMEWORK SHIT FRAMEWORK SHIT FRAMEWORK SHIT FRAMEWORK

REACT FOR EVER

### Please provide a link to a minimal reproduction of the bug

REACT REACT REACT REACT

### Please provide the exception or error you saw

```true
REACT REACT REACT REACTR CKING BEST
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
FUCK U ANGULAR
```

### Anything else?

REACR REACT REACT REACT

**Comment by CertifiedRice** [comment]
lmao wtf
whats the point of this issue? I get the angular is pretty bad, and React is good
but, please do not send an issue because of this. 
Going to twitter is better 😄

**Comment by LucaCodez1** [comment]
lmao no
