### ISSUE TITLE
Change Detection: add a test for pure functions

### ISSUE THREAD

**Issue by vicb** [angular/angular#461]
@vsavkin as we discussed the current dynamic change detector would evaluate pure function on every single run even if arguments have not changed.

The reason is that the former behavior has not yet been ported to the new cd architecture but will be soon.

However it seems like we don't have a test to make sure that pure function are evaluated only when needed, we should add such a test (xited if added before the feature is reintroduced)

**Comment by vsavkin** [comment]
@vicb I did not keep the test because I did not consider it a feature, but rather an optimization. But I agree that we should not forget about it. 

I am planning to reintroduce this behaviour in the next few days. So I am not sure if it is worth adding a disabled test.

**Comment by mhevery** [comment]
Update?

**Comment by vsavkin** [comment]
The behavior was ported long time ago: https://github.com/angular/angular/blob/master/modules/angular2/src/change_detection/dynamic_change_detector.ts#L165

**Comment by yjbanov** [comment]
Assigned it to myself since I'm working on https://github.com/angular/angular/issues/2556

**Comment by mhevery** [comment]
Closing since it is a dup of #2556 (an @vicb says it has been done)

**Comment by yjbanov** [comment]
Fixed by https://github.com/angular/angular/pull/2596
