### ISSUE TITLE
[routerLink] does not get updated with Observable / async

### ISSUE THREAD

**Issue by vilarneto** [angular/angular#46108]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

When `[routerLink]` is configured to read values from an Observable with `| async` pipe it only resolves to the first value, and only if a value is readily emitted at subscription.

Other issues seem to report the same or related bugs (see #13865, #13075, #18469, #9825); unfortunately they were all closed without an actual fix and the bug is still present.

## Steps to reproduce

(The resulting project is publicly available at https://github.com/vilarneto/angular-routerlink-bug.)

1. Create a new Angular project with `ng new`. Add routing when asked.
2. (optional) Strip the contents of `app.component.html` to:
```html
<router-outlet></router-outlet>
```
3. Create a test component with `ng generate component test`.
4. Add this component to the routing table in `app-routing.module.ts`:
```javascript
const routes: Routes = [
  {path: ":id", component: TestComponent}
];
```
5. In `test.component.ts` create the following getter:
```javascript
  get linkRoute(): Observable<string[]> {
    // [1] This one gives the correct link
    // return of(["/", "2"]);

    // [2] This one gives an inactive link
    // (notice that the only difference is that the value is not ready at subscription)
    return of(["/", "2"]).pipe(delay(0));

    // [3] This one does create a link to /1 but does not update it to /2:
    // return concat(
    //   of(["/", "1"]),
    //   of(["/", "2"]).pipe(delay(0)));
  }
```
6. Replace the contents of `test.component.html` with:
```html
<a [routerLink]="linkRoute | async">Link</a>
```
7. Run `ng serve` and open the browser at `http://localhost:4200/1`.

## Expected behavior

At the end of the page there must be an active link to `/2` for all provided versions of `get linkRoute()` source code.

## Actual behavior

If the return value of `get linkRoute()` is at version `[1]` then the link works as expected.

If the return value of `get linkRoute()` is at version `[2]` then the link is not active; in fact the generated `<a>` element does not contain the `href` attribute.

If the return value of `get linkRoute()` is at version `[3]` then the link is active, but `href` is not updated (it stays at `/1`).

### Please provide a link to a minimal reproduction of the bug

https://github.com/vilarneto/angular-routerlink-bug

### Please provide the exception or error you saw

```true
No exception nor console error, but the link does not work as expected.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.6
Node: 16.15.0
Package Manager: npm 8.5.5
OS: darwin x64

Angular: 13.3.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.6
@angular-devkit/build-angular   13.3.6
@angular-devkit/core            13.3.6
@angular-devkit/schematics      13.3.6
@angular/cli                    13.3.6
@schematics/angular             13.3.6
rxjs                            7.5.5
typescript                      4.6.4
```

**Comment by JoostK** [comment]
Your `linkRoute` getter is retuning a new `Observable` instance during each change detection cycle, so the async pipe cancels the prior subscription and resubscribes to the new `Observable` instance, initiating a new 0s delay. This means that a value never actually arrives at the `routerLink`. You can avoid this problem by storing a single `Observable` instance, for example as an instance field.

**Comment by vilarneto** [comment]
Thank you @JoostK for the fast and instructive answer.
