### ISSUE TITLE
colspan is not recognized as native element in td/th table elements

### ISSUE THREAD

**Issue by frickt** [angular/angular#4610]
I need to bind colspan to a td element, unfortunately it's not working:

template.html:
```javascript
    <div>
      <table>
        <tr *ng-for="#v of arr;#i = index">
          <th *ng-for="#h of arr[i]" colspan="{{h}}">
            <div>{{i}}-{{h}}</div>
          </th>
        </tr>
      </table>
    </div>
```

error:

    Can't bind to 'colspan' since it isn't a known native property in ShowTypeControlComponent > div:nth-child(0) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(0) > th:nth-child(1)[colspan={{h}}]

is there a way to add native properties to elements?

**Comment by pkozlowski-opensource** [comment]
colspan="{{h}}" is just sugar for [colspan]="h" and this in turn means: bind h to colspan property. There is no colspan property in html, only colspan attribute.

If you want to bind to an attribute use [attr.colspan]="h" syntax

**Comment by forwardadvance** [comment]
True, but not explanatory. If the DOM is deficient, perhaps Angular should make a special case exception to paper over the crack?

**Comment by zoechi** [comment]
You can find an extensive explanation at http://stackoverflow.com/questions/35615751/why-is-colspan-not-a-known-native-attribute-in-angular-2
I don't think Angular should do something special here. 
The error message could be point to the right direction. 

> If you intended to bind to the attribute use attr.colspan instead.
