### ISSUE TITLE
Angular 2 Material

### ISSUE THREAD

**Issue by TiagoBraga39** [angular/angular#4612]
@jelbourn Sorry to open a thread here, I have a couple of questions.

1. Is there any date we can expect to start using angular material?
2. Since it is not ready, do you recomend any other framework for now? I need to keep things on going. And when this is ready, I'll change to angular material.
3. Regarding to MdInputContainer being a directive: Did you choose it that way to avoid retargeting events / ids / validation? The thing is I will need to build a wrapper around the ng material, and if so I want to do so like the experts :)
4. Again about the MdInput, why do you access to the it's container with Host, and call a function there? Couldn't you do the same with @Query on the parent? It also seems a bit less intrusive.

Thank you!
Stay awesome,
Tiago Braga

**Comment by jelbourn** [comment]
@TiagoBraga39 
1. Nope.
2. Angular 2 itself is still in alpha, so there's not exactly a wealth of component libraries for it.
3. The current state of the components is super experimental. MdInput is definitely going to change before too long. For now it's not a `Component` simply because it doesn't have a template.
4. `Query` didn't exist when I wrote it.

**Comment by TiagoBraga39** [comment]
Got it! Thank you very much :)

**Comment by Mellbourn** [comment]
@jelbourn Hi jelbourn, Mellbourn here ;)

About your point 2:
> Any existing JS libraries can be used via a wrapper (just like angular 1).

Are you saying that angular material 1 can be used inside an angular 2 project? 
As far as I can see, there are currently no public tools to consume angular 1 components inside angular2. [ngUpgrade](https://github.com/angular/ngUpgrade) seems to be a collection of ideas.
So, how would I use angular material 1 inside angular 2? Do you know of any sample project?

Thanks!

**Comment by jelbourn** [comment]
@Mellbourn It would be with ngUpgrade once that tool is a bit more developed.

**Comment by abhishekisnot** [comment]
I believe this is in parts covered under https://github.com/angular/material/issues/6336
