### ISSUE TITLE
İs it my fault or bug i dont know but  i wanna write

### ISSUE THREAD

**Issue by cay3428** [angular/angular#46151]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

    

 this is my html
      
      <div class="mb-3">
        <label for="filterText" class="form-label">Ürün ara</label>
        <input type="text"   class="form-control" id="filterText" 
        placeholder="arama ifadesi giriniz">
      </div>
     
      
      <h4 style="text-align: left">Müşteriler</h4>
      <table class="table">
        <thead class="table-light">
          <tr>
            <td scope="col">Id</td>
            <td scope="col">İsim</td>
            <td scope="col">Email</td>
            <td scope="col">Soyisim</td>
           
        </thead>
        <tbody>
          <tr *ngFor="let users of users">
              <td>{{users.Id}}</td>
          </tr>
      </tbody>
      
      

this is my .ts

    import { Component, OnInit } from "@angular/core";
     import { Users } from "src/app/models/Users";
    import { AuthService } from "src/app/services/auth.service";
     
    
     
    
    @Component({
      selector: 'app-users',
      templateUrl: './users.component.html',
      styleUrls: ['./users.component.css'],
    })
    export class UsersComponent implements OnInit {
      user: Users   ;
      users : Users[] = []
      dataLoaded = false;
      filterText="";
    
      constructor(private authservice: AuthService
       ) {}
    
        ngOnInit(): void {
      this.getusers()
      }
    
    
      getusers() {
        this.authservice.getusers().subscribe(response=>{
          this.user = response.data
          console.log(this.users)
          this.dataLoaded = true;
        })   
      }
    
      getById(Id:number) {
        this.authservice.getById(Id).subscribe(response=>{
          this.user= response.data
          this.dataLoaded = true;
        })   
      }
      
      
     
    
    
    
    
    
    
    }

this is error when i start the browser 

NG0303: Can't bind to 'ngForOf' since it isn't a known property of 'tr'. core.mjs:10178
        Angular 3
        UsersComponent_Template users.component.html:21
        Angular 22
        RxJS 6
        Angular 8
            emit
            checkStable
            onHasTask
            hasTask
            _updateTaskCount
            _updateTaskCount
            runTask
            drainMicroTaskQueue

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

You need to ensure that `CommonModule` is included in the `NgModule.imports` of the `NgModule` that declares `UsersComponent `.

**Comment by cay3428** [comment]
okay thanks
________________________________
Gönderen: Joost Koehoorn ***@***.***>
Gönderildi: 26 Mayıs 2022 Perşembe 14:37
Kime: angular/angular ***@***.***>
Bilgi: cay3428 ***@***.***>; Author ***@***.***>
Konu: Re: [angular/angular] İs it my fault or bug i dont know but i wanna write (Issue #46151)


Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on StackOverflow<http://stackoverflow.com/> using tag angular.

If you are wondering why we don't resolve support issues via the issue tracker, please check out this explanation<https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem>.

________________________________

You need to ensure that CommonModule is included in the NgModule.imports of the NgModule that declares UsersComponent .
