### ISSUE TITLE
Can't add event listener (output binding) without body

### ISSUE THREAD

**Issue by alexpods** [angular/angular#4615]
This example doesn't work:
```html
<input #myname (input)>
<p>{{myname.value}}</p>
```
while this works perfectly well:
```html
<input #myname (input)="true">
<p>{{myname.value}}</p>
```
See [this plunker](http://plnkr.co/edit/Q47Nw9UCIKx7MifMTtPP?p=preview) and [this StackOverflow question](http://stackoverflow.com/questions/33021557/angular2-with-typescript-simple-example-with-local-variables)

**Comment by ericmartinezr** [comment]
@alexpods see https://github.com/angular/angular/issues/3754, I saw the question too, but the error he showed didn't seem anything like the one you see in the repro

**Comment by alexpods** [comment]
@ericmartinezr Ouh, thanks. I didn't see it before.
Close this as a dup.
