### ISSUE TITLE
Lots of UnsubscriptionError after angular13 migration

### ISSUE THREAD

**Issue by nishadthajudeen001** [angular/angular#46152]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

This error is being thrown on console for all the service subscribe which return HTTP observable(api response)

UnsubscriptionErrorImpl {message: "1 errors occurred during unsubscription:\n1) TypeEr…not read properties of undefined (reading 'push')", name: 'UnsubscriptionError', errors: Array(1)}
errors: [TypeError: Cannot read properties of undefined (reading 'push') at Subscription.<anonymous> (ht…]
message: "1 errors occurred during unsubscription:\n1) TypeError: Cannot read properties of undefined (reading 'push')"
name: "UnsubscriptionError"
[[Prototype]]: Error

### Please provide the exception or error you saw

```true
"zone.js": "^0.11.5"
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.6
Node: 12.22.8
Package Manager: yarn 1.22.11
OS: win32 x64

Angular: 13.3.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.6
@angular-devkit/build-angular   13.3.6
@angular-devkit/core            13.3.6
@angular-devkit/schematics      13.3.6
@angular/cdk                    13.3.7
@angular/cli                    13.3.6
@angular/fire                   7.3.0
@angular/flex-layout            13.0.0-beta.38
@schematics/angular             13.3.6
rxjs                            6.6.3
typescript                      4.6.4
```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
