### ISSUE TITLE
Weird typescript error using ngFor and enum maps

### ISSUE THREAD

**Issue by tonysamperi** [angular/angular#46156]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Coul be, since it didn't happen in Angular v11. Probably started with v12, not sure though.

### Description

The following error occurs at compile:

```
Error: projects/kik-launch/src/lib/components/launch/kik-launch.comp.html:120:32 - error TS7053: Element implicitly has an 'any' type because expression of type 'any' can't be used to index type 'Record<KikCsvKeys, KikProductSt
ates>'.

120    <mat-radio-group [ngModel]="stateOverrides[csvKey]"
                                   ~~~~~~~~~~~~~~~~~~~~~~

  projects/kik-launch/src/lib/components/launch/kik-launch.comp.ts:27:18
    27     templateUrl: "kik-launch.comp.html",
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component KikLaunchComponent.




× Failed to compile.
```

having this template:

```
<ng-container *ngFor="let csvKey of [kikCsvKeys.global, kikCsvKeys.country]">
    <mat-radio-group [ngModel]="stateOverrides[csvKey]" (ngModelChange)="onStateOverrideChange($event, csvKey)">
	    <mat-radio-button *ngFor="let state of states" [value]="state">
                {{state}}
	    </mat-radio-button>
    </mat-radio-group>
</ng-container>
```

having this variables:

```
// Models

export enum KikCsvKeys {
  country = "country",
  global = "global"
}

export enum KikProductStates {
  "unapproved",
  "approved",
  "check"
}

// kik-launch.comp.ts

kikCsvKeys: typeof KikCsvKeys = KikCsvKeys;
stateOverrides: Record<KikCsvKeys, KikProductStates> = {
    [KikCsvKeys.country]: void 0,
    [KikCsvKeys.global]: void 0
};
```

The error doesn't occur if I use a function returning the property value, instead of reading the object directly:

```
<mat-radio-group [ngModel]="getStateOverrideModel(csvKey)"
    (ngModelChange)="onStateOverrideChange($event, csvKey)">
	<mat-radio-button *ngFor="let state of states"
		  [value]="state">
				{{state}}
	</mat-radio-button>
</mat-radio-group>
```

Where `getStateOverrideModel` in my `ts` is: 

```
    getStateOverrideModel(csvKey: KikCsvKeys): KikProductStatesRef {
        return this.stateOverrides[csvKey];
    }
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-web-container-r2hybx

### Please provide the exception or error you saw

```true
Error: projects/kik-launch/src/lib/components/launch/kik-launch.comp.html:120:32 - error TS7053: Element implicitly has an 'any' type because expression of type 'any' can't be used to index type 'Record<KikCsvKeys, KikProductSt
ates>'.
```

### Anything else?

It's quite interesting that I can't reproduce the bug with the standard template of stackblitz, which from what I understand uses Angular 11 compiler under the hood?
So I retrieved a webcontainer version and created both the v13 (linked above) 
and here is the v11, where the error is not happening.

https://stackblitz.com/edit/angular-web-container-mzu9lj?file=src/app/app.component.html

I'll add an extra check using the same kind of loop in `ts` file, to see if the error happens even there...

**Comment by JoostK** [comment]
This has the same cause as #45370, please refer to https://github.com/angular/angular/issues/45370#issuecomment-1073341524 for more details.

**Comment by tonysamperi** [comment]
@JoostK damn thank you! I thought one of those params in tsconfig could be responsible, but I wasn't aware of `strictTemplates`.

Thanks a lot! I really couldn't stand those workaround function calls 😂😂😂
