### ISSUE TITLE
Router is appending not replacing previous node in zoneless mode when using BrowserAnimationModule

### ISSUE THREAD

**Issue by dsun-copperleaf** [angular/angular#46162]
### Which @angular/* package(s) are the source of the bug?

animations, core

### Is this a regression?

No

### Description

Routing breaks when the these two conditions happen together: (1)running the Angular app in zoneless mode (2) import `BrowserAnimationsModule` into AppModule.

When click around router links, new component is appeneded to the previous routing node instead of replacing it.

The core steps to reproduce the issue is:
1. Disable zone: https://angular.io/guide/zone#noopzone
2. import `BrowserAnimationsModule` to app.module

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-zm1tf1

### Please provide the exception or error you saw

No exception , no console error.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.7
Node: 14.17.0
Package Manager: npm 8.5.5
OS: win32 x64

Angular: 13.3.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router     

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.7
@angular-devkit/build-angular   13.3.7
@angular-devkit/core            13.3.7
@angular-devkit/schematics      13.3.7
@angular/cli                    13.3.7
@schematics/angular             13.3.7
rxjs                            7.5.5
typescript                      4.6.4
```

**Comment by atscott** [comment]
This is because you need to trigger change detection since you've disabled NgZone. 
https://stackblitz.com/edit/angular-ivy-1vz51c?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

Closing as working as expected.
