### ISSUE TITLE
Problem with createNgModuleRef typing

### ISSUE THREAD

**Issue by mlc-mlapis** [angular/angular#46172]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

The current typing of the createNgModuleRef function is:
```
export declare function createNgModuleRef<T>(ngModule: Type<T>, parentInjector?: Injector): NgModuleRef<T>;
```
The problem with this is in cases when more lazy loaded modules should be processed with the same generic code, like:
```
export enum LazyModules {
	EDITOR = 'editor',
	PROFILE = 'profile'
}

export const lazyLoadedModules = {
	[LazyModules.EDITOR]: {
		loadChildren: async () => (await import('@pall/lazy-modules/editor')).LazyEditorModule
	},
	[LazyModules.PROFILE]: {
		loadChildren: async () => (await import('@pall/lazy-modules/profile')).LazyProfileModule
	}
};

lazyLoadedModules[lazyModule].loadChildren().then(module => {
	const moduleRef = createNgModuleRef(module, this._injector);
	...
}
```
because the createNgModuleRef typing is not able to process type variants and the following error is appearing:
```
The argument of type 'typeof LazyEditorModule | typeof LazyProfileModule' is not assignable to the parameter of type 'Type<LazyEditorModule>'.
  Type 'typeof LazyProfileModule' is not assignable to type 'Type<LazyEditorModule>'.
```

When this happens the less efficient code is necessary to use:
```
export const lazyLoadedModuleEditor = {
	loadChildren: async () => (await import('@pall/lazy-modules/editor')).LazyEditorModule
};

export const lazyLoadedModuleProfile = {
	loadChildren: async () => (await import('@pall/lazy-modules/profile')).LazyProfileModule
};

switch (lazyModule) {
	case LazyModules.EDITOR:
		lazyLoadedModuleEditor.loadChildren().then(module => {
			const moduleRef = createNgModuleRef(module, this._injector);
			...
		})
		break;
	case LazyModules.PROFILE:
		lazyLoadedModuleProfile.loadChildren().then(module => {
			const moduleRef = createNgModuleRef(module, this._injector);
			...
		})
		break;
```

The typing of the createNgModuleRef function should be instead:
```
export declare function createNgModuleRef(ngModule: Type<any>, parentInjector?: Injector): NgModuleRef<any>;
```
to allow a more universal code structure.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.6
Node: 14.17.0
Package Manager: NPM 6.14.13
OS: Windows 10

Angular: 13.3.9
```

**Comment by JoostK** [comment]
This appears to happen because `Type` is an interface, not a type declaration; preventing distributivity of the different types.

The proposed alternative is undesirable by itself, as 1) it allows any input instead of being limited to class references, and 2) it prevents flowing the type into `NgModuleRef.instance`.

You can easily get the behavior you want by calling `createNgModuleRef` using an explicit `<any>` type argument list.

Please also share a runnable reproduction instead of separate code snippets, as it avoids quite a bit of work to replicate the exact setup you experienced the problem with.
