### ISSUE TITLE
Simple Docs for Router Reference | RouterLinks and Active Router Link.

### ISSUE THREAD

**Issue by ChaitanyaBabar** [angular/angular#46188]
### Description

Hi All,

The documentation code for use routerLink and routerLinkActive [here](https://angular.io/guide/router-reference#router-links) is as follows.

![image](https://user-images.githubusercontent.com/6712223/171006298-538e5aed-f09f-444c-bbe7-69c924d0463e.png)

But ideally the routerLink and routerLinkActive should be having syntax one way binding.
Although it is mentioned in docs below , the code snippet needs to be updated.

### What is the affected URL?

https://angular.io/guide/router-reference#router-links

### Please provide the steps to reproduce the issue

N/A.

### Please provide the expected behavior vs the actual behavior you encountered

The docs should provide the correct code snippet for use of routerLink and routerLinkActive.

### Expected Behavior :-

The docs should have code snippet as follows , i.e. showing one-way binding syntax for routerLink and routerLinkActive attributes.

![image](https://user-images.githubusercontent.com/6712223/171007425-a4dbecac-5fbd-43ce-a7ff-360e99c5153c.png)

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/6712223/171006298-538e5aed-f09f-444c-bbe7-69c924d0463e.png)

### Please provide the exception or error you saw

```true
N/A
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
N/A
```

**Comment by atscott** [comment]
The current documentation is correct. This is sufficient for binding static strings. Closing.
