### ISSUE TITLE
DevTools: Clarify Angular version support

### ISSUE THREAD

**Issue by dzhavat** [angular/angular#46191]
### Description

The second sentence in the [DevTools overview guide](https://angular.io/guide/devtools) says: "Angular DevTools supports Angular v9 and later, with Ivy enabled."

However, the [Firefox Addons](https://addons.mozilla.org/en-GB/firefox/addon/angular-devtools/) page has a similar sentence that says: "Angular DevTools supports Angular v12 and later."

So does it support v9 or v12?

### What is the affected URL?

https://angular.io/guide/devtools

**Comment by AleksanderBodurri** [comment]
The docs have already been updated in the repo, you can see the updated docs here https://next.angular.io/guide/devtools. The change has not propagated over to https://angular.io/guide/devtools yet. The version of DevTools on the Firefox add-on site was built with a more recent version of Angular DevTools that supports v12 above. I believe the version of DevTools in the chrome web store still supports v9 and above, but this will likely change when we make our next release. Going to close this issue for now.

**Comment by dzhavat** [comment]
@AleksanderBodurri Thanks for the clarification :)

**Comment by lentz** [comment]
Hi @AleksanderBodurri, do you know when the next Chrome Devtools release will occur? I'm eagerly awaiting some of the features that have been merged since the 1.0.4 release that's currently available. Thanks!

**Comment by lentz** [comment]
Awesome, thanks so much!
