### ISSUE TITLE
[Question] Horizontal visibility for directive injection

### ISSUE THREAD

**Issue by mlaval** [angular/angular#462]
In the documentation, the visibility constraints specified are all vertical (@ancestor, @parent, @child and @descendant).
What about horizontal ones please? Have they been considered ?

I'm raising this question because, for me, it would quite quite natural and elegant to write something like this in a template:
```
<div>
    <template [ng-if]="booleanCondition"><copy-me>hello2</copy-me></template>
    <template [ng-else]><copy-me>helloElse</copy-me></template>
</div>
```
or
```
<div>
    <copy-me template="ng-if booleanCondition">hello2</copy-me>
    <copy-me template="ng-else">helloElse</copy-me>
</div>
```

To implement such a `ng-else` directive, a visibility constraint like @previous or @before is needed.
More generally, it seems a good idea to be able to link sibling directives without having to create an extra parent directive.
What do you think please ?

For information, I did quick and dirty implementation of `ng-else` to find out how it could be done: https://github.com/mlaval/angular/commit/df56d40ef1589cb8f14c97e3f61ec3ca956a08f1
Before moving forward and implementing that in a cleaner way, I wanted to discuss it with you.

**Comment by mhevery** [comment]
Sounds interesting. @vsavkin do you have thoughts?

**Comment by mlaval** [comment]
To translate the vertical ones with the same spirit, I would create @Before, @Previous, @Next and @After.
- @Previous and @Next would only inject a directive from the very previous/next element (not considering comment nodes in between)
- @Before and @After would inject a directive from any element before/after.
For sure, the elements created by the `ViewSplitter` should not interfere.

What do you think?

**Comment by mhevery** [comment]
Given the current injector design, this seems less likely. Going to close, let me know if you feel strongly about reopening it.
