### ISSUE TITLE
'$locationShim': Not a valid '@angular/upgrade' application.

### ISSUE THREAD

**Issue by vzakharov-rxnt** [angular/angular#46211]
### Description

I'm getting issues implementing ngUpgrade according to the official docs.
I am at the stage when everything works, except navigation from Angular 1 to Angular 13.
It is not clear from the docs where this code should be put:

```
angular.module('rxntBillingApp')
          .factory('$location', downgradeInjectable($locationShim));
```
I tried putting it before `app.bootstrap(el)` in LazyLoaderService, but this results in an error:

> lazy-loader.service.ts:21 Error: Error while instantiating injectable '$locationShim': Not a valid '@angular/upgrade' application. Did you forget to downgrade an Angular module or include it in the AngularJS application?

This is a valid angular upgrade application because when this `$locationShim` downgrade is removed, everything works fine. The reason to introduce location shim is to unify routing, so that AngularJS application can route back to Angular 13 app.

It's not very clear from the docs, but I changed `this.upgrade.bootstrap` inside app.module.ts to bootstrap a regular AppComponent, which then has `<router-outlet>` and routes to Angular 13 test component or to AngularJS component which lazily loads all the static assets and performs the bootstrap.

```ts
// app-routing.module.ts
export const routes: Routes = [
  // Routes rendered by Angular
  { path: 'test-component', component: TestComponent },

  // AngularJS routes
  { path: '**', component: AngularJSComponent },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```

```ts
// angular-js.component.ts
export class AngularJSComponent implements OnInit, OnDestroy {
  constructor(
    private lazyLoader: LazyLoaderService,
    private elRef: ElementRef
  ) {}

  ngOnInit() {
    this.lazyLoader.load(this.elRef.nativeElement);
  }

  ngOnDestroy() {
    this.lazyLoader.destroy();
  }
}
```

And here is the code for `LazyLoaderService`, which is following the official example:

```ts
import { Injectable } from '@angular/core';
import angular from 'angular';
import { downgradeInjectable } from '@angular/upgrade/static';
import { $locationShim } from '@angular/common/upgrade';

@Injectable({
  providedIn: 'root'
})
export class LazyLoaderService {
  private app: angular.auto.IInjectorService | undefined;

  load(el: HTMLElement): void {
    import(/* webpackChunkName: "main.legacy" */ '../../app/index').then(app => {
      try {
        angular.module('rxntBillingApp')
          .factory('$location', downgradeInjectable($locationShim));  // tried adding this code:
        
        this.app = app.bootstrap(el);
      } catch (e) {
        console.error(e);
      }
    });
  }

  destroy() {
    if (this.app) {
      this.app.get('$rootScope').$destroy();
    }
  }
}
```

app.bootstrap code is as follows:

```ts
export function bootstrap(el: HTMLElement) {
  return angular.bootstrap(el, ['rxntBillingApp']);  
}
```

Please advise if you can see anything wrong with the above implementation.

### What is the affected URL?

https://angular.io/guide/upgrade#using-the-unified-angular-location-service

**Comment by vzakharov-rxnt** [comment]
@gkalpak Can you give an example with source code, or a link to it?

This doesn't look like valid JS/TS syntax:
```
[UpgradeModule#$injector][3]
```

**Comment by gkalpak** [comment]
Something like that. `upgrade.$injector` could be undefined (for example, if you haven't bootstrapped an AngularJS app yet), so you could have something like: `this.upgrade.$injector?.get('$rootScope').destroy()`

**Comment by vzakharov-rxnt** [comment]
@gkalpak Thank you, George. Please update the official docs when you can, this section:
- https://angular.io/guide/upgrade#create-a-service-to-lazy-load-angularjs
