### ISSUE TITLE
Unit tests ignore template binding syntax

### ISSUE THREAD

**Issue by jzabinski-dolios** [angular/angular#46220]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Template binding syntax seems to be ignored when components are compiled for unit testing.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/unit-test-template-mucb89?file=src%2Fapp%2Fapp.component.html

### Please provide the exception or error you saw

```true
Not applicable
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.3
Node: 16.13.0
Package Manager: npm 8.3.0
OS: darwin x64

Angular: 13.3.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.3
@angular-devkit/build-angular   13.3.3
@angular-devkit/core            13.3.3
@angular-devkit/schematics      13.3.3
@angular/fire                   7.3.0
@schematics/angular             13.3.3
rxjs                            6.6.7
typescript                      4.5.5
```

### Anything else?

The basic issue is that when a variable is defined in a Component:
```
cliLabel = 'cli';
```

And the template binds an element's `id` to the variable:
```
id="{{cliLabel}}"
```

And that component is compiled via `TestBed.compileComponents`, the resulting HTML element lacks the `id` attribute. This can be seen from the browser itself, not just in Angular's `fixture.nativeElement.querySelector`.

The link provided shows the broken version. Note that running Angular unit tests in Stackblitz requires some hacking, and the only way that I know of to get that hack to work is using Jasmine 3.4.0, so that is what the example is using. But projects unit testing outside Stackblitz should encounter the same problem.

Normal `ng serve` does not have this problem. Check the HTML for [this Stackblitz](https://stackblitz.com/edit/angular-ivy-vefalw?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html) to see the `id` successfully being applied.

**Comment by JoostK** [comment]
This happens because your test is not running any change detection on the created component. This is included in the documentation [here](https://angular.io/guide/testing-components-scenarios#detectchanges), which states that this is intentional.
