### ISSUE TITLE
refactor(router): rename "as" to "name" in RouteConfig

### ISSUE THREAD

**Issue by btford** [angular/angular#4622]
John Papa proposes we rename `as` to `name` in `RouteConfig` to reduce some of the confusion about its purpose:

So this:

```
@RouteConfig([
  { path: '/foo', component: MyCmp, as: 'MyCmp' }
])
```

Would become this:

```
@RouteConfig([
  { path: '/foo', component: MyCmp, name: 'MyCmp' }
])
```

/cc @johnpapa

**Comment by johnpapa** [comment]
`component: MyCmp` above should be a variable, not a string ... right?

**Comment by ericmartinezr** [comment]
If that's the alias, why not just call it `alias`?

**Comment by btford** [comment]
@johnpapa – correct. It should be a reference to a type.

@ericmartinezr – I'm not opposed to "alias," but I don't think that it serves to explain meaning better than "name." "Alias" suggests to me that this is an alternative way to refer to the route, not the primary typical case.

**Comment by johnpapa** [comment]
I `name` i most clear as it conveys the name of the route.

**Comment by DanWahlin** [comment]
I like `name` better as well.

**Comment by petebacondarwin** [comment]
If you don't provide a name does it default to something? Perhaps something defined in the component?

**Comment by gdi2290** [comment]
I guess you can even make a default case using the component name

```es6
 { path: '/foo', component: MyCmp, name: MyCmp.name }
/// with defaults
 { path: '/foo', component: MyCmp }
```

**Comment by tommymcdonald** [comment]
`name` seems more semantic to me over `as` as well. Is it set to default to the component name currently?

**Comment by btford** [comment]
> I guess you can even make a default case using the component name

If you're talking about the `fn.name`, this would break during minification.

I don't like the idea of basing a default name off some property of the component, especially because it'd have to be a static property. It moves the route name away from where the route is defined, so a developer would have to mentally map between the route and its component.

**Comment by Gillespie59** [comment]
Prefer also `name` to the previous `as` propery

**Comment by PascalPrecht** [comment]
I'm fine either way. Would love to hear what the confusions with `as` were tho :)

**Comment by johnpapa** [comment]
@PascalPrecht 

Here is what folks asked me: 

1. "as? as what?"

2. "is as an alias for another route I want to mimic?"

3. "where do i put the name of the route?"

**Comment by PascalPrecht** [comment]
Ha! The third one is nice. I have to admit that @cburgdorf also asked me what the `as` property is for in the first place. Especially, if you just have a single component that is being loaded.

So yea, let's go with `name` then.

**Comment by johnpapa** [comment]
Yeah, this is an easy win, IMO

**Comment by cburgdorf** [comment]
yep, `name` seems like a better fit :+1:

**Comment by tyleranton** [comment]
Would this be considered a good first contribution? I'd be interested in tackling this if so.

**Comment by btford** [comment]
@tyleranton Yep, that'd be great! For now, I think accepting either `name` or `as` would be best, and then we'll fully depreciate the `as` option a bit later.

**Comment by vamsivarikuti** [comment]
Hi @btford, I'm working on this. I have added `name?: string` to all classes implementing `RouteDefinition` interface. In constructors `this.name = name || as`, renamed `as` to `name` everywhere including unit tests, left one test with `as` syntax. 

Q. Should we throw an error (or) prefer one of the `as` and `name` if both are passed?

**Comment by btford** [comment]
It should throw.

**Comment by naomiblack** [comment]
adding this for the beta, since it's a breaking change and we have a PR open for it

**Comment by mistercorea** [comment]
So is there a documentation how to use this? I have gave it a name(alias) but I am not sure how to generate the url on the template.
