### ISSUE TITLE
Missing release of zone.js along with Angular 14.0.0

### ISSUE THREAD

**Issue by Platonn** [angular/angular#46230]
### Which @angular/* package(s) are the source of the bug

I wouldn’t call it a bug strictly, but those are the related packages:
@angular/core, zone.js

### Is this a regression?

No

### Description

Angular 14.0.0 Changelog [mentions some changes in zone.js](https://github.com/angular/angular/blob/main/CHANGELOG.md#zonejs) (related to this commit https://github.com/angular/angular/commit/f19b36f462803b3b3b9410391c039649541b10bc), however new version of zone.js was not released yet. 

By any chance, do you plan to release new zone.js@0.11.6 (or 0.12.0?) and point it as a peerDependency of angular/core@14.0.1?

If not, I think we should remove the zone.js changes from Angular 14 changelog. 

cc @JiaLiPassion

### Please provide a link to a minimal reproduction of the bug

N/A

### Please provide the exception or error you saw

```true
N/A
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 14.0.0
```

### Anything else?

I’m not sure if the issue template for bug is appropriate for this issue, but other templates like “feature request” or “docs” didn’t look more appropriate to me.

**Comment by Platonn** [comment]
Hi @alxhub would you mind explaining why this issue was closed?
I can see the PR https://github.com/angular/angular/pull/46232 by @JiaLiPassion is not merged and `zone.js@0.11.6` [was not released yet](https://www.npmjs.com/package/zone.js?activeTab=versions).

**Comment by dylhunn** [comment]
@Platonn We intended to release `zone.js` as well; I think Alex is working on getting it released soon.

**Comment by Julien-Marcou** [comment]
A new angular version has just been released, but it's still missing the zone.js release (despite the merge of #46232 before the release of the new angular version), is it expected ?

**Comment by dylhunn** [comment]
@Julien-Marcou No. #46232 was just merged, and I think that @alxhub is releasing it (correct me if I'm wrong)

**Comment by Platonn** [comment]
Thank you @JiaLiPassion for cutting of the release branch and thank you folks for releasing `zone.js@0.11.6` 🙌
