### ISSUE TITLE
Migration guide unclear on steps

### ISSUE THREAD

**Issue by phalgunv** [angular/angular#46236]
### Description

While googling for how to use ES2020 with Angular, I stumbled upon the below link https://angular.io/guide/migration-update-module-and-target-compiler-options

It starts by saying "This migration adjusts the target and module settings ...". Upon reading the whole document, I did not find what "this migration" meant. Is it referring to some command which needs to be run?

I searched angular repository on github for pages that refer "migration-update-module-and-target-compiler-options" to understand context, but I did not find any other docs referring to it.

### What is the affected URL?

https://angular.io/guide/migration-update-module-and-target-compiler-options

### Please provide the steps to reproduce the issue

None

### Please provide a screenshot if possible

None

### Please provide the exception or error you saw

```true
None
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
No
```

**Comment by alan-agius4** [comment]
Angular provides code mods or so called migrations out-of-the-box. These are ran when update from one major version to another when updating using the recommended [update procedure](https://update.angular.io/). These migrations transform your project and apply various changes such as replacing deprecated APIs with the newer versions, modernizing config settings and more.

**Comment by alan-agius4** [comment]
That migration will run from version 13 to 14.

**Comment by phalgunv** [comment]
Looking at the history of the file, I see es2020 was mentioned in the first commit on 24 June 2020 for v10 tooling migration. 
https://github.com/angular/angular/commit/424e20f76e558060c05624052ac8308d32e1c395
So it seems like the documentation was intended for migration from v9 to v10.

Also, there is a statement about "The minimum Node.js version for the Angular CLI (v10.13) supports features in ES2018 and earlier."

So, if the documentation is for the latest version, which at the moment is v14, should there not be a statement about Angular CLI v14 instead of v10.13?

**Comment by alan-agius4** [comment]
You are correct. The documentation is indeed for version 10.

This doc definitely doesn’t apply for version 14, thus I suggest that this page is completely removed. 

Unlike the linked migration, the version 14 migration just changes the compilation target to es2020.
