### ISSUE TITLE
Overridden properties hidden if both getter and setter not overridden

### ISSUE THREAD

**Issue by mcalmus** [angular/angular#46243]
### Which @angular/* package(s) are the source of the bug?

core, Don't known / other

### Is this a regression?

No

### Description

I have a set of directives that inherit from an abstract class. Each directive has an @Input property that writes to a corresponding property in the parent class. If only the setter is overridden, calling the getter returns undefined.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/components-issue-93s3yy?file=src/app/demo-property.directive.ts

### Please provide the exception or error you saw

```true
No error shown. If you click the text field in the demo, it should print the value of "myProperty" as set by the component. It is showing undefined unless the commented-out get property is included.

This should not be necessary.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Happens in Angular 12, 13, 14RC
```

### Anything else?

No.

**Comment by JoostK** [comment]
This is ECMAScript behavior, unrelated to Angular. Declaring the setter in the derived class redefines the property _without_ a getter, meaning that the getter in the base type is no longer accessible.

[TypeScript playground](https://www.typescriptlang.org/play?#code/FAQwRgzgLgTiDGUAE8A2IISQQUrBUACiDAKYB2yA3sEigPbnQwCui9MAFAJRJUC+wWkgAOMAJYA3EFFJIA+gFsAnoRj0RpGFGUAuJM3HkA5kgA+SFuQAmpAGZHS1gNzCRLMKnHwkx0shU1DS0dHn1DE3NLG3tHaz5hOjIoFhhyJCgAC3EIADolVXVNbWVXOkE6d09vA38kQKKQ5U4G4JLw2CNTCytbB3InXho6Oiyc-NbinSQAXnrCtp0ypArRdVlEJzX6eFJMMKRJenF44ZH4Rgh6VFJc1HpjTgByMUXlQ5BUFlIngBoM7J5SZNbjLQSCYBoDBYAAipEU9CCU2UMPEZEQUjkpAAHrIbFhcMwCMQyJQEnR6JItBJbLUAgtkS0GU0OhJIj0Yv1BuSRhAWMVcsCSrN5kimmDhAB6ABUohYyDGWCMSBANgBcguTGucgA7hwANYQYSU6knOR+elikoHCLdaJ9OI8pL+VLpPkCoVLYSraWS4AQzXQJC2BEigY6pBwhFWnSo9FQTE8VzAEP0QXM4VzJ6yaBPVyB7V3B6cVPpmPKUHAIA).
