### ISSUE TITLE
word shouldn't be capitalized

### ISSUE THREAD

**Issue by walaazahran** [angular/angular#46244]
### Description

HeroService.getHeroes() must have an asynchronous signature of some kind.
should be 
heroService.getHeroes() 
as it's instance of the service in heroes.component.ts

### What is the affected URL?

https://angular.io/tutorial/toh-pt4

### Please provide the expected behavior vs the actual behavior you encountered

[](url)

### Please provide a screenshot if possible

![screenshot of error](https://user-images.githubusercontent.com/91201117/171870804-38413820-f852-43ec-8cab-50bd8245f931.PNG)

### Please provide the exception or error you saw

```true
captalized word in documentation
```

**Comment by JoostK** [comment]
`getHeroes` is a method of class `HeroService`, hence the current use of an uppercase letter. The docs refer to the signature of the method (its parameter list and return type) which is declared on the class, not an instance, so the docs are correct here.
