### ISSUE TITLE
ComponentRouter - Use canActivate in Angular 1 application

### ISSUE THREAD

**Issue by mediacad** [angular/angular#4626]
How can I use the CanActivate method (in the ComponentRouter) in an Angular 1 ES5 application ?

**Comment by dpogue** [comment]
It's been renamed `$canActivate` and it must be specified on the function that returns the directive definition:

```typescript
function PageDirective() {
  return {
    restrict: 'A',
    templateUrl: '...',
    // etc.
  };
}

PageDirective.$canActivate = function(injectables) {
}

angular.module('myapp', []).directive('page', PageDirective);
```

**Comment by mediacad** [comment]
Thanks !

**Comment by vguede** [comment]
```javascript
PageDirective.$canActivate = function($injector) {
  var myService = $injector.get('myService');
}
```
works fine but I can't minify this code.
How can in use DI in $canActivate method in strict DI ?

**Comment by vguede** [comment]
I found the solution !
```javascript
PageDirective.$canActivate = function(myDependance) {
  var myService = myDependance.get('myService');
}
PageDirective.$canActivate.$inject = ['$injector'];
```

**Comment by winnemucca** [comment]
On current angular_1_router.js file I am playing with the $canActivate.   Trying to understand it as I go.

    function defaultCanActivateRouterHook(componentName) {
            return function() {
                console.log("${componentName}: $canActivate called with", arguments);
                return true;
            }
        }


Above is a function to test if it is called

below is $canActivate in action

    demo.value('$routerRootComponent', 'demoApp');
        
        demo.component('demoApp', {
            restrict: 'E',
            $routeConfig: [
                { path: '/about', name: 'About', component: 'demoAbout' },
                { path: '/list/...', name: 'List', component: 'demoList', useAsDefault: true }
            ],
            $canActivate: defaultCanActivateRouterHook('DempAppComponent'),
            controller: function ($router) {         
                console.log('DemoAppCtrl: constructor called');
            },
            template: function($element, $attrs) {
            	return "<h1> My demo App</h1> <ng-outlet></ng-outlet>";
            }
        });

I have been getting and pasting from open issues.  Beyond authenticity is there a need or use for $canActivate?
