### ISSUE TITLE
DevTools: Does not work with bootstrapApplication

### ISSUE THREAD

**Issue by rch850** [angular/angular#46260]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Currently Angular DevTools does not work with an app with `bootstrapApplication`.

### Please provide a link to a minimal reproduction of the bug

https://angular-ivy-snyrzm.stackblitz.io

### Please provide the exception or error you saw

```true
> Angular Devtools only supports Angular versions 9 and above with [ivy](https://angular.io/guide/ivy) enabled.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
* Angular: 14.0.0
* Angular DevTools: 1.0.4
```

### Anything else?

Source code of the reproduction: https://stackblitz.com/edit/angular-ivy-snyrzm

**Comment by JoostK** [comment]
This should have been resolved in #45983, but perhaps it hasn't been published yet.

A workaround would be to bootstrap with Protractor tooling:

```
bootstrapApplication(AppComponent, {
  providers: [provideProtractorTestingSupport()],
}).catch((err) => console.error(err));
```

**Comment by rch850** [comment]
I could confirm the workaround works. It saved me 👍 

* https://angular-ivy-eepv6j.stackblitz.io
* https://stackblitz.com/edit/angular-ivy-eepv6j?file=src%2Fmain.ts

**Comment by AndrewKushnir** [comment]
Closing this ticket based on the comments above.
