### ISSUE TITLE
BrowserAnimationsModule error in standalone component

### ISSUE THREAD

**Issue by lycHub** [angular/angular#46278]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

Yes

### Description

When I introduce BrowserAnimationsModule in app.component.ts, I get the following error.
![image](https://user-images.githubusercontent.com/29920553/172299693-993bc821-3a44-41cb-a71f-3319799c62fb.png)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-qmfq4r?file=src/app/app.component.ts

### Please provide the exception or error you saw

```true
Providers from the `BrowserModule` have already been loaded. If you need access to common directives such as NgIf and NgFor, import the `CommonModule` instead.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.0
Node: 16.13.2
Package Manager: npm 8.1.2 
OS: win32 x64

Angular: 14.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router 

Package                         Version
---------------------------------------------------------     
@angular-devkit/architect       0.1400.0
@angular-devkit/build-angular   14.0.0
@angular-devkit/core            14.0.0
@angular-devkit/schematics      14.0.0
@schematics/angular             14.0.0
rxjs                            7.5.5
typescript                      4.6.4
```

**Comment by ChellappanRajan** [comment]
Addd BrowserModule in main.ts. It will fix the issue

```
bootstrapApplication(AppComponent, {
  providers: [
    { provide: NZ_I18N, useValue: zh_CN },
    importProvidersFrom(RouterModule.forRoot(routes)),
    importProvidersFrom(BrowserAnimationsModule)
  ]
}).catch(err => console.error(err));
```

**Comment by lycHub** [comment]
> Add BrowserModule in main.ts. It should fix the issue
> 
> ```
> bootstrapApplication(AppComponent, {
>   providers: [
>     { provide: NZ_I18N, useValue: zh_CN },
>     importProvidersFrom(RouterModule.forRoot(routes)),
>     importProvidersFrom(BrowserAnimationsModule)
>   ]
> }).catch(err => console.error(err));
> ```
thank you very match
