### ISSUE TITLE
Shadow CSS and @import in Firefox

### ISSUE THREAD

**Issue by mlaval** [angular/angular#4628]
Due to https://bugzilla.mozilla.org/show_bug.cgi?id=625013 , our trick to transform CSS string into rules fails in Firefox when there is an @import rule.
See https://github.com/angular/angular/blob/master/modules/angular2/src/core/dom/generic_browser_adapter.ts

Currently, there is a try/catch to avoid the error, but it means that the rules are lost in the transformation.The new test introduced by @yjbanov to check that @import rules are not modified cannot succeed in Firefox.

**Comment by vicb** [comment]
This is no longer applicable as we don't use cssRules any more but manual parsing
