### ISSUE TITLE
routerLink and attr.href work together

### ISSUE THREAD

**Issue by doleance** [angular/angular#46284]
### Description

With both routerLink and attr.href attribute on, when routerLink set undefined (or null), the href attribute is not generated on the anchor DOM element.

```
<a
  [attr.href]="link"
  [routerLink]="routerNav ? link : undefined"
>
```

### Proposed solution

Even with routerLink set, do not block href attribute of the element.

**Comment by atscott** [comment]
`routerLink` necessarily binds to the `href` attribute of the anchor. Setting the value to `null` removes the `href` to disable the navigation. This is working as intended. You can create a different directive to fine tune application-specific behavior.
