### ISSUE TITLE
Update Angular DevTools manifest version

### ISSUE THREAD

**Issue by mgechev** [angular/angular#46287]
### Description

We currently use Manifest version 2, which is deprecated and Chrome will no longer support it starting in 2023. [Read more](https://developer.chrome.com/blog/mv2-transition/).

### Proposed solution

Explore the v3 format and update.

### Alternatives considered

None.

**Comment by vteotia9** [comment]
Please assign it to me.

**Comment by vteotia9** [comment]
https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/

**Comment by vteotia9** [comment]
https://angular.io/guide/devtools

I have tested all the flows mentioned in the above doc after updating manifest version to 3.

**Comment by mgechev** [comment]
@vteotia9 could you open a pull request?

**Comment by AleksanderBodurri** [comment]
Closed by #47575
