### ISSUE TITLE
@Output not working properly from global context even with ngzone.run()

### ISSUE THREAD

**Issue by KostyaTretyak** [angular/angular#46288]
### Which @angular/* package(s) are the source of the bug?

core

### Description

If for `@Output` you create a callback in a global context (for example, as a property of a `window` object) and then try to emits events from this callback, only the first call will work. Further attempts to make emits will not work even with `ngzone.run()`.

You can see this bug on [stackblitz](https://stackblitz.com/github/KostyaTretyak/angular-global-output-bug?file=src%2Fapp%2Fchild.component.ts) or on [my repository](https://github.com/KostyaTretyak/angular-global-output-bug). If you try to click the "first" link and then the "second" link, everything will work as expected. But if you try to do it again, when you click on "second" you will not see the output message from the child `mesage from child @Output`.

In my case, I created several child components, each of which works with its vendor to login through social networks (Facebook, Google, etc.). These vendors call callbacks from a global context. In this case, I can't rely on using `@Output` because they don't work properly.

### Environment

```true
Angular CLI: 13.3.7
Node: 16.15.0
Package Manager: yarn 1.22.1
OS: linux x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.7
@angular-devkit/build-angular   13.3.7
@angular-devkit/core            13.3.7
@angular-devkit/schematics      13.3.7
@angular/cli                    13.3.7
@schematics/angular             13.3.7
rxjs                            7.5.5
typescript                      4.6.4
```

**Comment by JoostK** [comment]
You are assigning `testCallback` here which closes over `this`, i.e. the first component instance of `app-child`:

```ts
    (window as any).testCallback = () => {
      this.zone.run(() => {
        this.someEvent.emit('mesage from child @Output');
      });
    };
```

New instances of `app-child` don't rebind that closure, so the closure state still refers to the original component that has since been destroyed. Hence, emitting into its output has no effect.

**Comment by KostyaTretyak** [comment]
I felt that would be the case. It's a shame, but relief still came. Thank you!
