### ISSUE TITLE
zone.js Mocha patch regression in v0.11.5

### ISSUE THREAD

**Issue by Alorel** [angular/angular#46297]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

The patch for `it.skip` disappeared in v0.11.5.

zone.js v0.11.4, `fesm2015/zone-testing.js`, line 1061:

```javascript
    global.xit = global.xspecify = Mocha.it.skip = function () {
        return mochaOriginal.it.skip.apply(this, wrapTestInZone(arguments));
    };
```

zone.js v0.11.5, line 1061:

```javascript
    global.xit = global.xspecify = function () {
        return mochaOriginal.it.skip.apply(this, wrapTestInZone(arguments));
    };
```

The function [is still part of the Mocha API](https://mochajs.org/#inclusive-tests) and shouldn't have been removed.

### Please provide the exception or error you saw

```true
it.skip is not a function
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.0
Node: 16.13.2
Package Manager: npm 8.3.2 
OS: linux x64

Angular: 14.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.0
@angular-devkit/build-angular   14.0.0
@angular-devkit/core            14.0.0
@angular-devkit/schematics      14.0.0
@schematics/angular             14.0.0
rxjs                            7.5.5
typescript                      4.7.3
```

**Comment by JiaLiPassion** [comment]
I will check it, thank you for posting the issue.

**Comment by luislobo** [comment]
I'm having the same issue

**Comment by JiaLiPassion** [comment]
Sorry this is a regression, I have created a PR to fix it.

**Comment by JiaLiPassion** [comment]
The PR is merged, I will close this one.
