### ISSUE TITLE
Wrong example of FormRecord usage

### ISSUE THREAD

**Issue by igornowosad** [angular/angular#46298]
### Description

Docs got an example which goes like this

> 
> FormRecord accepts one generic argument, which describes the type of the controls it contains.
```
let numbers = new FormRecord({bill: '415-123-456'});
numbers.addControl('bob', '415-234-567');
numbers.removeControl('bill');
```

But when I use that example in my code I got an error

```
let numbers = new FormRecord({bill: '415-123-456'}); // TS2322: Type 'string' is not assignable to type 'AbstractControl<never, never>'. 
numbers.addControl('bob', '415-234-567'); // TS2345: Argument of type 'string' is not assignable to parameter of type 'AbstractControl '.

```

### What is the affected URL?

https://angular.io/api/forms/FormRecord

### Please provide the steps to reproduce the issue

1. Use FormRecord as docs says
2. Look at Typescript compiler errors

### Please provide the expected behavior vs the actual behavior you encountered

I expect to use example from docs and get 0 errors.

### Please provide the exception or error you saw

```true
TS2322: Type 'string' is not assignable to type 'AbstractControl<never, never>'. 
TS2345: Argument of type 'string' is not assignable to parameter of type 'AbstractControl '.
```

**Comment by dylhunn** [comment]
This should be fixed in #46299.
