### ISSUE TITLE
Please add a guide to upgrade Angular Universal apps in the upgrade guide.

### ISSUE THREAD

**Issue by ashwingairola** [angular/angular#46306]
### Description

Currently there is no guide for upgrading `@nguniversal/express-engine` when upgrading Angular versions.

Please add this to the documentation on [update.angular.io](https://update.angular.io/). There are presently no guides for this.

**Comment by alan-agius4** [comment]
This is more of a devrel decision if we should add universal to the update guide.

@mgechev what do you think?

**Comment by UTSOURCE** [comment]
I think so. We should supplement the documents in this regard

**Comment by mgechev** [comment]
Let's reevaluate when we explore hydration. I'd suggest to keep it open to gauge the interest.

**Comment by bob-watson** [comment]
Assigned P5 pending additional feedback from community, after which it's priority can be changed.

**Comment by JeanMeche** [comment]
Angular SSR is now better documented on angular.dev.
