### ISSUE TITLE
New discussion button doesn't work

### ISSUE THREAD

**Issue by RazRes** [angular/angular#46303]
### Description

Hi, I think there is a bug with the "New" button on Discussions section. When it is clicked doesn't do anything. 
Thanks!

### What is the affected URL?

https://github.com/angular/angular/discussions

### Please provide the steps to reproduce the issue

Go to Angular -> Discussions -> Press button "New"

### Please provide the expected behavior vs the actual behavior you encountered

I expect a new page or a section appears to create a new discussion

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/92641928/172620960-724000fa-41f5-451b-8fa4-1e54fa814bbe.png)

**Comment by JoostK** [comment]
The Angular repo doesn't have support for discussions enabled for everyone, only the team can open discussions. The button being shown as clickable would be a Github bug, I'd suggest you report this issue with Github.

**Comment by gkalpak** [comment]
In addition to what @JoostK, that "New" button there is not for creating a new discussion. It is for applying a filter to sort discussions by "newest". (Alternatively, you could choose to see discussions created today, or last year, etc., but choosing an option in the drop-down next to "New".)

This UI is indeed confusing to me too, but that is an issue for GitHub. Angular does not have control over the UI there.
