### ISSUE TITLE
problem with ng-content within a ng-for

### ISSUE THREAD

**Issue by gustavoq-infocorp** [angular/angular#4631]
When a component has a `ng-content` within a `ng-for` only one `ng-content` is rendered.

## Component with the for and content   ( list.ts )
```
<li *ng-for="#item of listRows">
    <ng-content></ng-content>
 </li>

```
## Component using the List component  ( app.ts )
```
<list [list-rows]="myRows" >
      <listRow ></listRow>
</list>

```
Can see the code with the problem here http://plnkr.co/edit/RbvRWV0O1jiWoCcs6dAF?p=preview 

Maybe  @tbosch can see the problem here

**Comment by tbosch** [comment]
This is how `ng-content` is supposed to work: If you have 2 `ng-content` that match the same nodes, only the first `ng-content` gets the nodes. Similar to a template with:

```
<ng-content></ng-content>
<ng-content></ng-content>
```

I.e. a given node in the light dom is only projected once.

**Comment by tbosch** [comment]
What you are looking for is `ng-for-template`, which I just added to master (will be released soon): https://github.com/angular/angular/commit/6207b1af8838661fb38ab6c13b0d54956970db50

Have a look at the integration test...

**Comment by tbosch** [comment]
Closing as this works as expected.

**Comment by gustavoq-infocorp** [comment]
Excellent news, looking forward for the release 

Thanks !!!

**Comment by nawalgupta** [comment]
Any Simple Example for ngForTemplate? for the above use case?

http://plnkr.co/edit/YL4mwrLv7cVsHQgxbAf6?p=preview

**Comment by mcchae7** [comment]
Simple List Component Example with dynamic ngTemplate: https://stackblitz.com/edit/angular-list-ngtemplateoutlet
