### ISSUE TITLE
VM1689 angular.js:15697 NullInjectorError: StaticInjectorError(AppModule)[UserFeedbackService -> http_HttpClient]:    StaticInjectorError(Platform: core)[UserFeedbackService -> http_HttpClient]:      NullInjectorError: No provider for http_HttpClient!

### ISSUE THREAD

**Issue by JonnyRamblur** [angular/angular#46316]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

I have an AngularJS/Angular hybrid app updgraded with ngUpgrade. All has been working well. The new Angular components (downgraded) work fine in the AngularJS app.

However, I cannot get the HttpClient module to instantiate.

I have followed the doc and examples of this, but no success.

This is the full error:

NullInjectorError: StaticInjectorError(AppModule)[UserFeedbackService -> http_HttpClient]: 
  StaticInjectorError(Platform: core)[UserFeedbackService -> http_HttpClient]: 
    NullInjectorError: No provider for http_HttpClient!
    at NullInjector.get (core.js:11545:27)
    at resolveToken (core.js:12281:24)
    at tryResolveToken (core.js:12226:16)
    at StaticInjector.get (core.js:12121:20)
    at resolveToken (core.js:12281:24)
    at tryResolveToken (core.js:12226:16)
    at StaticInjector.get (core.js:12121:20)
    at resolveNgModuleDep (core.js:24381:29)
    at _createClass (core.js:24430:29)
    at _createProviderInstance (core.js:24400:26) '<angular-feedback-component _nghost-gam-c0="">'

You can see that is is actually complaining about http_HttpClient, which is strange as most cases I have seen of this report that it is HttpClient. I am not using the http_HttpClient reference anywhere.

This is app.ts:

import { HttpClientModule } from '@angular/common/http';

@NgModule({
  imports: [
    HttpClientModule,
    BrowserModule,
    UpgradeModule,
    MatDialogModule,
    BrowserAnimationsModule,
    FormsModule,
  ],
  declarations: [
    FeedbackComponent,
    UserFeedbackComponent,
  ],
  entryComponents: [
    FeedbackComponent,
    UserFeedbackComponent,
  ],
  providers: [
    UserFeedbackService,
  ],
})
This is the Angular service:

import { Inject, Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';

constructor(@Inject(HttpClient) private http: HttpClient, private dialog: MatDialog) { }

or

constructor(private http: HttpClient, private dialog: MatDialog) { }

The service works fine without the reference to HttpClient. It is not a problem with the service as if I try to inject HttpClient into the controller I get the same error.

FYI, this is how the hybrid app is bootstrapped in app.ts:

export class AppModule {

constructor(private upgrade: UpgradeModule) { }

// Bootstrap using the UpgradeModule
platformBrowserDynamic().bootstrapModule(AppModule).then(platformRef => {
  console.log("Bootstrapping in Hybrid mode with Angular & AngularJS");
  const upgrade = platformRef.injector.get(UpgradeModule) as UpgradeModule;
  upgrade.bootstrap(document.body, ['angularjsApp'], {strictDi: true});
});

Using Angular 12.2.16 and AngularJS 1.8.3.

Spent several days trying to resolve this so any help would be appreciated.

### Please provide a link to a minimal reproduction of the bug

Will provide later

### Please provide the exception or error you saw

```true
NullInjectorError: StaticInjectorError(AppModule)[UserFeedbackService -> http_HttpClient]: 
  StaticInjectorError(Platform: core)[UserFeedbackService -> http_HttpClient]: 
    NullInjectorError: No provider for http_HttpClient!
    at NullInjector.get (core.js:11545:27)
    at resolveToken (core.js:12281:24)
    at tryResolveToken (core.js:12226:16)
    at StaticInjector.get (core.js:12121:20)
    at resolveToken (core.js:12281:24)
    at tryResolveToken (core.js:12226:16)
    at StaticInjector.get (core.js:12121:20)
    at resolveNgModuleDep (core.js:24381:29)
    at _createClass (core.js:24430:29)
    at _createProviderInstance (core.js:24400:26) '<angular-feedback-component _nghost-mwx-c0="">'
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1202.0
@angular-devkit/build-angular      12.2.0
@angular-devkit/core               12.2.17
@angular-devkit/schematics         12.2.17
@angular/cdk                       12.2.13
@angular/elements                  12.2.16
@angular/localize                  12.2.16
@angular/material-moment-adapter   12.2.13
@angular/upgrade                   12.2.16
@schematics/angular                12.2.17
rxjs                               6.6.7
typescript                         4.7.3
webpack                            4.46.0
```

### Anything else?

I have followed the Angular doc on how to use ngUpgrade and downgrade a service and use HttPClient, but no luck as can't get past the above error.

**Comment by jessicajaniuk** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
