### ISSUE TITLE
Error building Angular source code

### ISSUE THREAD

**Issue by phalgunv** [angular/angular#46317]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

No

### Description

Hello,

This is my first attempt to build source code for Angular repository. I have ran the below commands:

1. git clone https://github.com/angular/angular.git
2. npm install

`npm install` fails with "ERESOLVE unable to resolve dependency tree" error. Please see the command output below:

> PS C:\code\angular> npm install 
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: angular-srcs@14.1.0-next.0
> npm ERR! Found: typescript@4.7.2
> npm ERR! node_modules/typescript
> npm ERR!   typescript@"~4.7.2" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:                                                                  che\tmp\OJihu0\package.json'
> npm ERR! peer typescript@">=4.4.2 <4.7" from @angular/compiler-cli@13.3.11
> npm ERR! node_modules/@angular/compiler-cli
> npm ERR!   peer @angular/compiler-cli@"^13.0.0 || ^13.3.0-rc.0" from @angular-devkit/build-angular@13.3.6
> npm ERR!   node_modules/@angular-devkit/build-angular
> npm ERR!     @angular-devkit/build-angular@"13.3.6" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR! See C:\Users\pvaddepa\AppData\Local\npm-cache\eresolve-report.txt for a full report.

In the root Angular repo package.json has typescript version 4.7.2
https://github.com/angular/angular/blob/main/package.json#L174

It depends on "@angular-devkit/build-angular": "13.3.6"
https://github.com/angular/angular/blob/main/package.json#L46

"@angular-devkit/build-angular": "13.3.6" has peer dependency for "@angular/compiler-cli": "^13.0.0 || ^13.3.0-rc.0"
https://github.com/angular/angular-cli/blob/13.3.6/packages/angular_devkit/build_angular/package.json#L78

 @angular/compiler-cli@13.3.11 has peer dependency for "typescript": ">=4.4.2 <4.7"
https://github.com/angular/angular/blob/13.3.11/packages/compiler-cli/package.json#L69
 
Since the typescript version is 4.7.2 does not satisfy the constraint, ">=4.4.2 <4.7", it results in error. "ERESOLVE unable to resolve dependency tree"

It seems like this is an issue. Is this the correct way to start building Angular source code?

### Please provide the exception or error you saw

```true
PS C:\code\angular> npm install 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: angular-srcs@14.1.0-next.0
npm ERR! Found: typescript@4.7.2
npm ERR! node_modules/typescript
npm ERR!   typescript@"~4.7.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:                                                                  che\tmp\OJihu0\package.json'
npm ERR! peer typescript@">=4.4.2 <4.7" from @angular/compiler-cli@13.3.11
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   peer @angular/compiler-cli@"^13.0.0 || ^13.3.0-rc.0" from @angular-devkit/build-angular@13.3.6
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     @angular-devkit/build-angular@"13.3.6" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\pvaddepa\AppData\Local\npm-cache\eresolve-report.txt for a full report.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Node: v16.10.0
OS: Windows 10 version 20H2(Build 19042.1466)
```

**Comment by JoostK** [comment]
The Angular repo uses `Yarn` as package manager, not NPM. More information on building Angular [can be found here](https://github.com/angular/angular/blob/main/docs/DEVELOPER.md).
