### ISSUE TITLE
http.post(url, postData, options) does not set header

### ISSUE THREAD

**Issue by robhicks** [angular/angular#4632]
This doesn't add the content type to the header. The header remains "text/plain".

```JavaScript
var url = "/login";
var postData = JSON.stringify({username: username, password: password});
var options = {
  headers: [
    {"Content-Type": "application/json"}
  ]
};
return this.http.post(url, postData, options).subscribe(response => {
  console.log(response);
});
```

**Comment by mgechev** [comment]
The code above won't compile in TypeScript because `options` is with the wrong type.

Try this instead:

```ts
    var url = "/login";
    var postData = JSON.stringify({username: 'foo', password: 'bar'});
    let headers = new Headers({
      "Content-Type": "application/json"
    })
    var options = {
      headers: headers
    };
    return this.http.post(url, postData, options).subscribe(response => {
      console.log(response);
    });
```

**Comment by robhicks** [comment]
@mgechev Thanks for your help. 

While doing it this way doesn't make a lot of sense to me, I tried it with the same result. The Content-Type does not get changed.

**Comment by mgechev** [comment]
@robhicks would you send a plnkr that reproduces your issue?

**Comment by robwormald** [comment]
This issue was moved to angular/http#62

**Comment by natejgardner** [comment]
@robwormald could you please link to this issue's continuation in angular/http#62?
