### ISSUE TITLE
angular-in-memory-web-api Angular 14 support

### ISSUE THREAD

**Issue by spierala** [angular/angular#46332]
Currently it is not possible to use angular-in-memory-web-api with Angular 14.

The latest angular-in-memory-web-api version has Angular 13 peer dependencies (see here: https://github.com/angular/angular/blob/main/packages/misc/angular-in-memory-web-api/package.json#L8-L9).

This is the error when running `npm i`:

![image](https://user-images.githubusercontent.com/1272446/173120284-93e9b280-2906-4306-8b21-9f66eda3959b.png)

I can get around the error locally with `npm i --force` but the CI runs `npm ci` and then the error is back.

It would be great if Angular 14 support could be added. Thanks. 

### Environment

These are the Angular versions:

"@angular/animations": "14.0.1",
"@angular/common": "14.0.1",
"@angular/compiler": "14.0.1",
"@angular/core": "14.0.1",
"@angular/forms": "14.0.1",
"@angular/platform-browser": "14.0.1",
"@angular/platform-browser-dynamic": "14.0.1",
"@angular/router": "14.0.1",

"@angular/cli": "~14.0.0",
"@angular/compiler-cli": "14.0.1",
"@angular/language-service": "14.0.1",

I am using NX workspace: 
        
"@nrwl/angular": "14.2.4",

**Comment by bthharper** [comment]
Same issue for me, preventing ng14 upgrade.
