### ISSUE TITLE
Update Docs for FormGroups with Optional Nested Objects

### ISSUE THREAD

**Issue by arambazamba** [angular/angular#46338]
### Description

I have a person object with an optional Address that somehow looks like this:

export class Person {
  id: number = 0;
  age: number = 0;
  name: string = '';  
  address?: Address = { street: '', city: '', postalCode: '' };
}

My approach would be to type the form somehow like this:

export interface PersonFormType {
  id: FormControl<number | null>;
  name: FormControl<string | null>;
  age: FormControl<number | null>;
  address?: FormGroup<{
    street: FormControl<string | null>;
    city: FormControl<string | null>;
    postalCode: FormControl<string | null>;
  }>;

and assign the value like this:

    this.personForm = this.fb.group({
      id: [this.person.id],
      name: [this.person.name, Validators.required],
      age: [this.person.age],     
      address: this.fb.group({
        street: [this.person.address?.street],
        city: [this.person.address?.city],
        postalCode: [this.person.address?.postalCode],
      }),
    });

which gives an err that can not be read properly because it is shortend:

Type 'FormGroup<{ id: FormControl<number | null>; name: FormControl<string | null>; age: FormControl<number | null>; address: FormGroup<{ street: FormControl<string | null | undefined>; city: FormControl<...>; postalCode: FormControl<...>; }>; }>' is not assignable to type 'FormGroup<PersonFormType>'.
  Types of property 'controls' are incompatible.
    Type '{ id: FormControl<number | null>; name: FormControl<string | null>; age: FormControl<number | null>; address: FormGroup<{ street: FormControl<string | null | undefined>; city: FormControl<...>; postalCode: FormControl<...>; }>; }' is not assignable to type 

Please provide an advanced sample in the docs on how to type forms with nested optional objects and maybe make error messages fully expandable (in VS Code)

**Comment by dylhunn** [comment]
What Angular version are you using?

**Comment by alxhub** [comment]
You declare `address.street` as a control accepting `string|null`, but you use optional chaining (`this.person.address?.street`) to actually create the control. Because optional chaining returns `undefined` values, the actual type of the created control is `string|undefined|null`. This control is therefore not assignable to the type of `street`, as TS says:

```
Types of property 'controls' are incompatible.
Type '{ ... street: FormControl<string | null | undefined>; ....' is not assignable to type '... street: FormControl<string | null> ...';
```
