### ISSUE TITLE
Update instructions should include the context in which to run the update command

### ISSUE THREAD

**Issue by bob-watson** [angular/angular#46331]
### Description

While following the instructions in https://update.angular.io/?v=13.0-14.0, I got the following error:
```
ng update @angular/core@14 @angular/cli@14
The installed Angular CLI version is outdated.
Installing a temporary Angular CLI versioned 14.0.1 to perform the update.
✔ Package successfully installed.
Error: Unknown arguments: update, @angular/core@14, @angular/cli@14
```
This was also reported in: https://github.com/angular/angular-cli/issues/23274

### What is the affected URL?

https://update.angular.io/?v=13.0-14.0

### Please provide the steps to reproduce the issue

See description.

### Please provide the expected behavior vs the actual behavior you encountered

The general documentation and the update documentation should:
* specify the directory in which to run the update command to update an existing workspace
* provide general update instructions to update the CLI separate from a project

### Please provide the exception or error you saw

```true
See description.
```

**Comment by JeanMeche** [comment]
This has been done in the following version, closing as we won't update these rather old docs.
