### ISSUE TITLE
FormGroup valueChanges type is Partial<T> but should be just T

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/angular#46341]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

The type of valuechanges event payload is Partial<T> but should be just T. See the stackblitz demo.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-nzd6vs?file=src/app/app.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 14.0.0
```

**Comment by JoostK** [comment]
I believe this is working as intended, as disabled controls are excluded from the value (add `this.form.controls.bar.disable();` before you change the value to see the difference). This is also how `FormGroup.value` is different from `FormGroup.getRawValue()`
