### ISSUE TITLE
"export 'ɵRuntimeError' was not found in '@angular/core' in angular 11

### ISSUE THREAD

**Issue by PiyushAgrawal1243** [angular/angular#46349]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I don't know much about it but when I delete my node_module and again reinstalled the node module this error arises.

core.js:27478 Uncaught TypeError: Cannot redefine property: ɵfac
    at Function.defineProperty (<anonymous>)
    at addDirectiveFactoryDef (core.js:27478:1)
    at compileComponent (core.js:27361:1)
    at ɵ3$1 (core.js:27674:93)
    at TypeDecorator (core.js:3758:1)
    at __decorate (tslib.es6.js:58:53)
    at Module.ENgC (collection-list-section-form.component.ts:46:48)
    at __webpack_require__ (bootstrap:84:1)
    at Module.GCp2 (sub-action-file-upload.component.ts:9:42)
    at __webpack_require__ (bootstrap:84:1)

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.19
Node: 12.22.9
OS: linux x64

Angular: 11.2.4
... core
Ivy Workspace: Yes

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1102.19
@angular-devkit/build-angular       0.1102.19
@angular-devkit/core                11.2.19
@angular-devkit/schematics          11.2.19
@angular/animations                 11.2.14
@angular/cdk                        11.2.13
@angular/cli                        11.2.19
@angular/common                     11.2.14
@angular/compiler                   11.2.14
@angular/compiler-cli               11.2.14
@angular/forms                      11.2.14
@angular/language-service           11.2.14
@angular/localize                   11.2.14
@angular/material                   11.2.13
@angular/platform-browser           11.2.14
@angular/platform-browser-dynamic   11.2.14
@angular/router                     11.2.14
@schematics/angular                 12.2.17
@schematics/update                  0.1102.19
rxjs                                6.6.7
typescript                          4.0.8
```

### Anything else?

package.json

{
  "name": "frontend-apps",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "build-production": "ng build --prod --configuration production",
    "build-staging": "ng build --prod --configuration staging",
    "build-develop": "ng build --prod --configuration develop",
    "test": "ng test --code-coverage",
    "lint": "ng lint --ts-config tsconfig.json --tslint-config tslint.json",
    "e2e": "ng e2e",
    "sonar": "sonar-scanner"
  },
  "private": true,
  "dependencies": {
    "@angular-material-components/datetime-picker": "^6.0.2",
    "@angular-material-components/moment-adapter": "^6.0.0",
    "@angular/animations": "~11.2.4",
    "@angular/cdk": "~11.2.3",
    "@angular/common": "~11.2.4",
    "@angular/core": "~11.2.4",
    "@angular/forms": "~11.2.4",
    "@angular/localize": "^11.2.4",
    "@angular/material": "^11.2.3",
    "@angular/platform-browser": "~11.2.4",
    "@angular/platform-browser-dynamic": "~11.2.4",
    "@angular/router": "~11.2.4",
    "@material-extended/mde": "^3.0.3",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@ngxs/storage-plugin": "^3.7.1",
    "@ngxs/store": "^3.7.1",
    "@swimlane/ngx-datatable": "^19.0.0",
    "angular-google-tag-manager": "1.4.2",
    "angularx-social-login": "^3.5.7",
    "bootstrap": "^4.4.1",
    "hammerjs": "^2.0.8",
    "i": "^0.3.6",
    "ngx-bootstrap": "^5.3.2",
    "ngx-captcha": "^10.0.0",
    "ngx-color-picker": "^8.2.0",
    "ngx-csv-parser": "0.0.7",
    "ngx-google-places-autocomplete": "^2.0.5",
    "ngx-infinite-scroll": "^8.0.0",
    "ngx-quill": "13.2.0",
    "ngx-youtube-player": "^12.0.1",
    "ngxs-reset-plugin": "^1.3.1",
    "quill": "^1.3.6",
    "rxjs": "~6.6.6",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1102.3",
    "@angular/cli": "~11.2.3",
    "@angular/compiler": "^11.2.4",
    "@angular/compiler-cli": "^11.2.0",
    "@angular/language-service": "~11.2.4",
    "@ngxs/devtools-plugin": "^3.7.1",
    "@schematics/angular": "^12.2.9",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^14.14.31",
    "codelyzer": "^6.0.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~6.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage": "^2.0.3",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "protractor": "~7.0.0",
    "sonar-scanner": "^3.1.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.1.3",
    "typescript": "~4.0.7"
  }
}

**Comment by JoostK** [comment]
The error indicates that you have misaligned packages, at least some require a newer version of `@angular/core` than what you have installed.

---

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
