### ISSUE TITLE
FormBuilder.group controls with array values requires an extra [ ]

### ISSUE THREAD

**Issue by zstundys** [angular/angular#46340]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

Given the following:

```ts
interface FormModel {
  favorites: string[];
}

...

form = this.fb.group<FormModel>({
  favorites: []
})
```

I would expect the initial form value would be `{ favorites: [] }`, but it results in `{ favorites: null }`.
To achieve the expected result, I need the following:

```ts
form = this.fb.group<FormModel>({
  favorites: [ [] ]
})
```

But it produces type-checking errors - same thing happens with `NonNullableFormBuilder`

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-y5vvdq?file=src/app/app.component.ts

### Please provide the exception or error you saw

```true
Type '[]' is not assignable to type 'string'.(2322)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.1
Node: 16.13.0
Package Manager: npm 8.12.1 
OS: linux x64

Angular: 14.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.7
@angular-devkit/build-angular   14.0.1
@angular-devkit/core            13.3.7
@angular-devkit/schematics      14.0.1
@angular/flex-layout            13.0.0-beta.38
@schematics/angular             14.0.1
rxjs                            7.5.5
typescript                      4.7.3
```

**Comment by dylhunn** [comment]
Your model type is incorrect -- you need to use control types, not value types. You should do something like this instead:

```
interface FormModel {
  favorites: FormArray<FormControl<string>>;
}

...

form = this.fb.group<FormModel>({
  favorites: [];
})
```

**Comment by visma-zanas-stundys** [comment]
@dylhunn This doesn't really fit our use case -- we have controls with ControlValueAccessor implementations that specificaly handle array values for FormControls (not FormArrays) -- we use this approach, since it's generally easier to patch the whole form value with arrays in it.

I've set up an example that illustrates our situation a bit better:
https://stackblitz.com/edit/angular-ivy-wycnub?file=src/app/app.component.ts

**Comment by zstundys** [comment]
I see ;) Thanks for the follow-up -- I'll proceed with the approach you've suggested :)

**Comment by zstundys** [comment]
Seems like using the constructor pattern is not so bad -- after making some abstractions:

```ts
interface FormModel {
  name: string;
  age: number | undefined;
  favorites: string[]
}

...

@Component(...)
export class FormComponent {
  // Type safe & terse definition
  form = buildForm<FormModel>({
    name: [''],
    age: [undefined],
    favorites: [[], [Validators.minLength(1)]]
  });
}
```

<details>
<summary> Source code

</summary>

```ts
type ControlsOf<T extends Record<string, any>> = {
  [K in keyof T]: FormControl<T[K]>;
};

type ControlsConfig<T> = {
  [K in keyof T]: readonly [initialValue: T[K] | FormControlState<T[K]>, validators?: ValidatorFn | ValidatorFn[]];
};

export function buildForm<T extends Record<any, any>>(config: ControlsConfig<T>): FormGroup<ControlsOf<T>> {
  return new FormGroup(
    Object.entries(config).reduce((acc, [key, [value, validators]]: [keyof T, any]) => {
      acc[key] = new FormControl(value, { validators, nonNullable: true });
      return acc;
    }, {} as ControlsOf<T>)
  );
}
```

</details>

**Comment by dylhunn** [comment]
Glad to hear that the direct approach is working better. I will keep this in mind for future improvements to `FormBuilder` as well -- we are thinking of replacing it with a less polymorphic API.
