### ISSUE TITLE
route with only canActiveGuard 

### ISSUE THREAD

**Issue by Karman40** [angular/angular#46354]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Not working code:
```
const routes: Routes = [
  {path: '', component: UsersListComponent, children: [
      {path: '', canActivate: [RedirectToListGuard]}, // this guard redirect to /admin/:type (eg users)/all
      {path: 'all', loadChildren: () => import('./users-all/users-all.module').then(m => m.UsersAllModule)},
      {path: 'new', loadChildren: () => import('./users-new/users-new.module').then(m => m.UsersNewModule)},
    ]}
];
```
```
  {path: '', canActivate: [AuthAdminGuard], children: [
      {path: '', loadChildren: () => import('./pages/home-page/home.module').then(m => m.HomeModule)},
      ...
   ]}
```

In this case i get a following error message:
ERROR Error: Uncaught (in promise): Error: Invalid configuration of route ''. One of the following must be provided: component, loadComponent, redirectTo, children or loadChildren
Error: Invalid configuration of route ''. One of the following must be provided: component, loadComponent, redirectTo, children or loadChildren

### Solution:
```
      {path: '', redirectTo: '', pathMatch: 'full', canActivate: [RedirectToListGuard]},
```

Is it possible to work without redirectTo and pathMatch?

Thanks a lot!!

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.1
Node: 16.15.0
Package Manager: npm 8.12.1
OS: win32 x64

Angular: 14.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.1
@angular-devkit/build-angular   14.0.1
@angular-devkit/core            13.2.6
@angular-devkit/schematics      13.2.6
@angular/fire                   7.4.1
@schematics/angular             13.2.6
rxjs                            7.5.5
typescript                      4.7.3
```

**Comment by atscott** [comment]
A route without redirectTo, component, or children can't really be activated in what the Router defines "activated" as so `canActivate` on its own doesn't fit the script.

The better fit here is https://github.com/angular/angular/issues/13373.
