### ISSUE TITLE
Request to keep User Input documentation that has been marked for archival

### ISSUE THREAD

**Issue by runette** [angular/angular#46371]
### Description

This page is marked for archive :

https://angular.io/guide/user-input#key-event-filtering-with-keyenter

This is EXACTLY the sort of page - providing good practical examples and advice as opposed to theoretical reference - that Angular needs more of - not less!

The alternative suggested is not useful in the least!

### What is the affected URL?

https://angular.io/guide/user-input#key-event-filtering-with-keyenter

**Comment by bob-watson** [comment]
Assigned P2 to review this request and determine whether to archive or not.

**Comment by bob-watson** [comment]
See also https://github.com/angular/angular/issues/18870

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
