### ISSUE TITLE
Currency bug with MT currency

### ISSUE THREAD

**Issue by DudeThatsErin** [angular/angular#46378]
### Which @angular/* package(s) are the source of the bug?

localize

### Is this a regression?

No

### Description

I am coding something for work, I am using this code:

```<span><b>{{ player.balanceBonus + player.balanceCash | currency: 'MT' : '$': '4.2-2' }} MT</b></span>```

That displays: $17,525.00 MT.

I need it to display: $17.525,00 MT.

Comma and period need to be flipped. This does not work.

### Please provide a link to a minimal reproduction of the bug

N/A

### Please provide the exception or error you saw

```true
N/A
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.5
Node: 16.15.0
Package Manager: npm 8.5.5
OS: win32 x64

Angular: 13.3.6
... animations, cdk, common, compiler, compiler-cli, core
... elements, forms, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.5
@angular-devkit/build-angular   13.3.5
@angular-devkit/core            13.3.5
@angular-devkit/schematics      13.3.5
@angular/cli                    13.3.5
@schematics/angular             13.3.5
rxjs                            7.5.5
typescript                      4.6.4
```

**Comment by JoostK** [comment]
The formatting depends on the _locale_, not the currency. You're not providing an explicit locale to the pipe invocation, such that the value from [`LOCALE_ID`](https://angular.io/api/core/LOCALE_ID) is used, or `en-US` if none is set. You can either provide `LOCALE_ID` with the desired locale or add an additional argument to the pipe invocation (and load the locale files as needed)
