### ISSUE TITLE
CurrencyPipe: Setting LOCALE_ID does not change _defaultCurrencyCode

### ISSUE THREAD

**Issue by Frimlik** [angular/angular#46387]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

I have this provider:
`
//app.module.ts
const initLocaleProvider = {
  provide: LOCALE_ID,
  useFactory: (confService: ConfigService) => confService.config.uiCulture,
  deps: [ConfigService]
};

@NgModule({
  providers: [
    initLocaleProvider
  ]
})
`

Config is loaded to `ConfigService` one step before through `APP_INITIALIZER` and it's loaded correctly. I tried it with decimal numbers and their punctuation was correct.
Now, if the uiCulture is set to `en-GB` or `de-DE`, `CurrencyPipe` (used either in template or component) always outputs `$` instead of `£` or `€`, respectively. And it's `_defaultCurrencyCode` is still set to `USD`.

Am I setting anything badly or what's the reason of this behavior?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 10.0.8
Node: 14.17.3
OS: win32 x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cdk                      10.2.7
@angular/cli                      10.0.8
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
```

**Comment by JoostK** [comment]
This is working as intended. Please see https://github.com/angular/angular/pull/34724#issuecomment-614496201 for details.

**Comment by Frimlik** [comment]
@JoostK I found this solution in meantime, but thanks for the link.
