### ISSUE TITLE
nyc instrumentation on the Angular ts files having decorators then it moves the export before the decorator so compilation is failed

### ISSUE THREAD

**Issue by ssuparna2010** [angular/angular#46396]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Hi,

I tried to instrument the angular scripts using nyc  where as the ts files having decorators. when we do nyc instrumentation on the Angular ts files having decorators then it moves the export before the decorator so compilation is failed..

**original file** 
import {Component, HostListener} from '@angular/core';
import {Model} from 'src/app/model/model';
import {EnvironmentService} from 'src/app/services/utility/environment.service';
import { environment } from 'src/environments/environment';

@Component({
  selector: 'pap-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class PapComponent {

  public model: Model = null;
  public expanded: boolean = false;

  // EnvironmentService is injected in order to be initialized when the app is bootstrapped
  public constructor(private _environmentService: EnvironmentService) {
  }

  @HostListener('window:beforeunload', ['$event'])
  public beforeUnloadHandler($event): boolean {
    // show dialog, prompting for leaving page only in production mode
    return !environment.production;
  }
}

**After NYC instrumentation**
function cov_2lyzoknbcf() {
  var path = "C:\\CODECOVERAGE\\pap-ui\\pap-ui\\src\\app\\app.component.ts";
  var hash = "5da6d7495dd282e9467a2e01e230d1c145764c2d";
  var global = new Function("return this")();
  var gcv = "__coverage__";
  var coverageData = {
    path: "C:\\CODECOVERAGE\\pap-ui\\pap-ui\\src\\app\\app.component.ts",
    statementMap: {
      "0": {
        start: {
          line: 13,
          column: 24
        },
        end: {
          line: 13,
          column: 28
        }
      },
      "1": {
        start: {
          line: 14,
          column: 29
        },
        end: {
          line: 14,
          column: 34
        }
      },
      "2": {
        start: {
          line: 23,
          column: 4
        },
        end: {
          line: 23,
          column: 35
        }
      }
    },
    fnMap: {
      "0": {
        name: "(anonymous_0)",
        decl: {
          start: {
            line: 17,
            column: 2
          },
          end: {
            line: 17,
            column: 3
          }
        },
        loc: {
          start: {
            line: 17,
            column: 70
          },
          end: {
            line: 18,
            column: 3
          }
        },
        line: 17
      },
      "1": {
        name: "(anonymous_1)",
        decl: {
          start: {
            line: 20,
            column: 2
          },
          end: {
            line: 20,
            column: 3
          }
        },
        loc: {
          start: {
            line: 21,
            column: 46
          },
          end: {
            line: 24,
            column: 3
          }
        },
        line: 21
      }
    },
    branchMap: {},
    s: {
      "0": 0,
      "1": 0,
      "2": 0
    },
    f: {
      "0": 0,
      "1": 0
    },
    b: {},
    _coverageSchema: "1a1c01bbd47fc00a2c39e90264f33305004495a9",
    hash: "5da6d7495dd282e9467a2e01e230d1c145764c2d"
  };
  var coverage = global[gcv] || (global[gcv] = {});

  if (!coverage[path] || coverage[path].hash !== hash) {
    coverage[path] = coverageData;
  }

  var actualCoverage = coverage[path];
  {
    // @ts-ignore
    cov_2lyzoknbcf = function () {
      return actualCoverage;
    };
  }
  return actualCoverage;
}

cov_2lyzoknbcf();
import { Component, HostListener } from '@angular/core';
import { Model } from 'src/app/model/model';
import { EnvironmentService } from 'src/app/services/utility/environment.service';
import { environment } from 'src/environments/environment';
export @Component({
  selector: 'pap-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
class PapComponent {
  public model: Model = (cov_2lyzoknbcf().s[0]++, null);
  public expanded: boolean = (cov_2lyzoknbcf().s[1]++, false); // EnvironmentService is injected in order to be initialized when the app is bootstrapped

  public constructor(private _environmentService: EnvironmentService) {
    cov_2lyzoknbcf().f[0]++;
  }

  @HostListener('window:beforeunload', ['$event'])
  public beforeUnloadHandler($event): boolean {
    cov_2lyzoknbcf().f[1]++;
    cov_2lyzoknbcf().s[2]++;
    // show dialog, prompting for leaving page only in production mode
    return !environment.production;
  }

}

So while we try to compile it throws an error

**Comment by atscott** [comment]
I'm sorry but this issue is not caused by Angular. Please contact the author(s) of project NYC or file issue on their issue tracker.
