### ISSUE TITLE
Use CurrencyPipe to output ONLY currency symbol

### ISSUE THREAD

**Issue by Frimlik** [angular/angular#46393]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

Nowadays there is no option how to use "pure" `CurrencyPipe` (and nothing else) to show only currency symbol, when `LOCALE_ID` is set.
There is [getCurrencySymbol](https://angular.io/api/common/getCurrencySymbol) function, but this requires locale as a parameter, which could be avoided by using `CurrencyPipe`.

### Proposed solution

Update `CurrencyPipe` so it would allow to output only currency symbol.

### Alternatives considered

-

**Comment by pkozlowski-opensource** [comment]
I don't think that we want to expand the meaning of the `CurrencyPipe` the way you suggest. Let's keep it focused on one task - formatting monetary values.

Given that the [getCurrencySymbol](https://angular.io/api/common/getCurrencySymbol) function is exposed you can always get the current locale from the [LOCALE_ID](https://angular.io/api/core/LOCALE_ID) token. And wrap it in a custom function or a pipe if needed.

Going to close this one as it is perfectly valid to have this functionality living in the user-land.
