### ISSUE TITLE
Bug in angular.jp website

### ISSUE THREAD

**Issue by Aman-askar** [angular/angular#46406]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

there is an error in the angular.jp website 

### Please provide a link to a minimal reproduction of the bug

https://angular.jp/

**Comment by JoostK** [comment]
This should be reported in https://github.com/angular/angular-ja, but it would need information as to what is wrong because this issue isn't currently indicating where the issue is.
