### ISSUE TITLE
domNode not being garbage collected by browser, causing major memory leak

### ISSUE THREAD

**Issue by marco5872** [angular/angular#46403]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

We have an angular 13 app which generated multiple domNodes when using the page in firefox and edge. It is not getting released when reloading the page or when moving to a different route. It was working in angular 8 with any browser. When it happens, I can see the memory growing using firefox's about:memory. I found the majority of the memory sitting in heap-unclassified and not getting garbage collected.

This is working completely fine with the latest chrome and we have no memory leakage. I have also checked the subscription to ensure each is getting .next() and .complete() at the ngOnDestroy();

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/animations": "13.3.11",
    "@angular/cdk": "^13.3.9",
    "@angular/common": "13.3.11",
    "@angular/compiler": "13.3.11",
    "@angular/core": "13.3.11",
    "@angular/flex-layout": "^13.0.0-beta.38",
    "@angular/forms": "13.3.11",
    "@angular/material": "^13.3.9",
    "@angular/platform-browser": "13.3.11",
    "@angular/platform-browser-dynamic": "13.3.11",
    "@angular/router": "13.3.11",
```

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information (including a minimal repro) when filling out the issue template.
