### ISSUE TITLE
Application stays in memory even after being destroyed

### ISSUE THREAD

**Issue by rajib-g** [angular/angular#46408]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

Yes

### Description

I am not sure of the source module but it is from Angular application.

I have created a basic Angular application using ng new command. Then I only modify the app.component.ts file. The same is written below:

`import { Component, HostListener, OnDestroy } from '@angular/core';
import { platformBrowser } from '@angular/platform-browser';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnDestroy {
  ngOnDestroy(): void {
    console.log('ngOnDestroy called');
  }
  @HostListener('window:message',['$event'])
  onMessage(e:any)
  {
    console.log(e);
    if(e["data"] == "close")
      this.closeForm();
  }
  closeForm() {
    platformBrowser().destroy();
  }
  title = 'demo';
}
`

I have made a index.html file which is being served by IIS. On pressing add the angular application is being loaded inside an iframe and on pressing remove button the application is being destroyed and iframe is removed from DOM. 

The content of index.html file which is being served by IIS is written below:
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="width: 100vw; height: 100vh;">
    <div id="a"></div>
    <button onclick="add()">Add</button>
    <button onclick="remove()">Remove</button>
</body>
<script>
    function add() {
        let body = document.getElementById('a');
        let rand = Math.floor(Math.random() * 1000);
        // body.innerHTML = `<iframe src="http://localhost/app5/#/?_dc=${rand}" title="Miscellaneous Entry Form" id="miscEntFrm" style="width:100%; height:99%; border:none;"></iframe>`;
        // body.innerHTML = `<iframe src="http://localhost/app1/#/misc?userId=125334675" title="Miscellaneous Entry Form" id="miscEntFrm" style="width:100%; height:99%; border:none;"></iframe>`;
        body.innerHTML = `<iframe src="http://localhost:4200" title="Memory Leak Demo" id="miscEntFrm" style="width:100%; height:99%; border:none;"></iframe>`;
    }
    function remove() {
        document.getElementById('miscEntFrm').contentWindow.postMessage("close", "*");

        setTimeout(() => {
            let frame = document.getElementById('miscEntFrm');
            //frame.contentWindow.location.reload();
            frame.src = 'about:blank';
            frame.remove();
            frame = undefined;
        }, 1000);
    }
</script>
</html>

But the thing is, when observing memory tab performance monitor I notice that heap memory is constantly increasing when adding and removing the angular application along with iframe. Along with heap memory there is also an increase in DOM nodes, document and event listeners which decrease to some extinct but equals the previous number.

I have also build the app for production but the issue is still there.

![memory leak heap snapshot](https://user-images.githubusercontent.com/107666716/174235712-f08a4db0-3ca1-46a5-a34d-43d7fc535751.PNG)

### Please provide a link to a minimal reproduction of the bug

https://github.com/rajib-g/MemoryLeakDemo.git

### Please provide the exception or error you saw

```true
OnDestroy called but application not releasing resources.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.6
Node: 16.15.0
Package Manager: npm 8.5.5
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1303.6 (cli-only)
@angular-devkit/core         13.3.6 (cli-only)
@angular-devkit/schematics   13.3.6 (cli-only)
@schematics/angular          13.3.6 (cli-only)
```

### Anything else?

We are developing a hybrid application where the angular application should be inside an iframe. If you need any other information please let me know.

**Comment by AndrewKushnir** [comment]
@rajib-g thanks for providing an example of an HTML page and a component that you use for testing. I performed additional investigation and ran 2 scenarios:

1. Add/remove logic **within the same page** (without iframes). The add button invoked `platformBrowser().bootstrapModule(...)` call and the remove button invoked `platformBrowser().destroy()`. The outcome is that there is **no** memory leak: the amount of memory remains the same after multiple rounds of add-remove operations.
2. The second test was performed using a **static `index.html` page**, which embeds an Angular app using a static `index.html` file from the `dist` folder, generated using `ng build` (I've used a Python web server: `python3 -m http.server 4200`). This resulted in **no** memory leak.

I noticed that you've mentioned Angular v13.3.6 and I was using 14.0.1. Could you please check if the problem still exists with v14.0.1 in your scenario? If yes, I'd like to ask if you could try to put together a repro that we can run, which might consist of:
- HTML/JS/TS files as a wrapper that loads an Angular app in an iframe
- an Angular app itself (**not** your entire app, just a simple `ng new`-generated app with the minimal possible code sufficient to repro the problem)
- instructions on which commands you use to build/serve the scripts + a sequence of steps to take to repro the issue

Thank you.

**Comment by rajib-g** [comment]
Yes the memory leak is still there. I have tried using Angular CLI version 14.0.2.

I am sharing a video link demonstrating how I can reproduce the same.
https://drive.google.com/file/d/1NEkoYFvHyltE6LIs4SSoLkgdau7ZPvlv/view?usp=sharing

Steps to reproduce the same:
1. Create a new Angular application.
2. Copy the app.component.ts file from the link https://github.com/rajib-g/MemoryLeakDemo.git.
3. Create a static html file outside the angular directory. And copy the index.html file from the link https://github.com/rajib-g/MemoryLeakDemo.git.
4. Host the static html file using IIS.
5. Serve the angular application by ng serve. And serve the static html file from IIS
6. Use inspect to observe performance monitor and heap snapshots.
7. Add and remove the Angular app from the static html served by IIS. 
8. You can now observe the heap memory is continuously increasing along with DOM nodes. And from console tab you can see the ngOnDestroy is executing when platformBrowser().destroy() exexutes.

I am also sharing the zip of folder I have created while demonstrating the same.
https://drive.google.com/file/d/1s2zAvGU2JCYYzNGw_mnkuenVcrtyGTP_/view?usp=sharing

I have even tried by building the app, then hosting the same using IIS and then changing the Iframe src to new url after that serving the same from IIS. The result is same.

**Comment by hiepxanh** [comment]
I have this memory leak experience with bootstrapApplication on standalone components too. I'm going to try to create an example. Right now I'm busy making a cronjob to manually reset the SSR container to prevent memory leaks first.

**Comment by rajib-g** [comment]
@AndrewKushnir Hi did you able to reproduce the issue from your end? Do you need any help or any further clarification from my side?

I have already made a video on how to reproduce the memory leakage. The link is https://drive.google.com/file/d/1NEkoYFvHyltE6LIs4SSoLkgdau7ZPvlv/view?usp=sharing

I have also shared a zip of folder I have created while demonstrating the same.
https://drive.google.com/file/d/1s2zAvGU2JCYYzNGw_mnkuenVcrtyGTP_/view?usp=sharing

**Comment by AndrewKushnir** [comment]
@rajib-g thanks for additional information. I'll be looking into that (try to reproduce) and also the problem reported in #46473 by @hiepxanh.

@rajib-g quick question/clarification: do you see the memory leak when you do **not** use `ng serve`, i.e. when the app is built in prod mode and JS/HTML files are served statically by a web server?

**Comment by rajib-g** [comment]
@AndrewKushnir  Yes, when the angular application is built in prod mode the problem is still exists.

But what I observe that when I am serving using ng serve the iframe source are getting stacked everytime in source tab
![Capture2](https://user-images.githubusercontent.com/107666716/175466018-486992e2-81a7-43d6-9721-ab5ff39cc442.PNG)

And when I built the Angular app and host the same using IIS and then serve both the Angular app and the static HTML file from IIS the iframe source are not getting stacked. 
![Capture3](https://user-images.githubusercontent.com/107666716/175467519-36c1e2b8-e620-485c-a268-c411be0d44b8.PNG)

But the leakage is still more or less same because the heap memory is increasing on every add and remove button click.

![Capture4](https://user-images.githubusercontent.com/107666716/175467288-f39223d5-8ee6-491c-9989-e23dc32af345.PNG)

You can see that ngOnDestroy is executing when platformBrowser().destroy(); executes. When ngOnDestroy executed most of the memory get released but it never returns to the previous number.
Even, number of documents and document frames keep rising.
Before adding Angular application
![Capture5](https://user-images.githubusercontent.com/107666716/175468685-6df6ef53-703f-4565-99bb-de300e131aa9.PNG)
After adding and removing iframe having Angular application
![Capture6](https://user-images.githubusercontent.com/107666716/175468697-baeaf295-6bf5-49f4-a861-1b13b17f5e30.PNG)

**Comment by AndrewKushnir** [comment]
@rajib-g I've created a PR with a proposed fix, which might resolve the problem that you are observing, see more info in https://github.com/angular/angular/issues/46473#issuecomment-1166174742. Could you please try testing the app using the instructions from the mentioned comment and let us know if you see any improvements? Thank you.

**Comment by rajib-g** [comment]
@AndrewKushnir  I have tested the way it is mentioned in https://github.com/angular/angular/issues/46473#issuecomment-1166174742. But the result is same, there is memory leakage. 

I think static HTML file is confusing for us and we are not on the same page. So let's try another scenario where I have observed the memory leakage also. This time we will have another Angular app instead of static HTML file. 

I am sharing the zip of the folder which contains the application that I have created while reproducing.
https://drive.google.com/file/d/1yR6kEPVK1HTKgDK4q798CuNKv0mcmCZq/view?usp=sharing

I have just updated the package.json in both of the app like https://github.com/angular/angular/issues/46473#issuecomment-1166174742 (and run npm i). Then write a simple logic for cross app communication. In this approach there are two apps, one is Parent that will contain the iframe and another is InsideFrame which will be hosted inside iframe.

I have built both of the apps and then host them on IIS. I have seen the same memory leakage here also. Another thing is these apps are hosted as such they are of same-origin by that I mean these application have shared local-storage.

Please ask if you need any help from my side. Thank you.

**Comment by AndrewKushnir** [comment]
@rajib-g thanks for testing the change. I will try to debug more once the mentioned fix lands. Meanwhile, could you please create a new GitHub repository and put the contents of the archive there? For security reasons, we can't use such archives locally.

**Comment by rajib-g** [comment]
@AndrewKushnir Hi, I have created two repository one for parent application which will host iframe and another for application which will be hosted on the parent application. The following links are:
https://github.com/rajibghosal2016/Parent
https://github.com/rajibghosal2016/InsideFrame

I have also deployed the 2 applications in Github pages. The link of both is given below:
https://rajibghosal2016.github.io/Parent/
https://rajibghosal2016.github.io/InsideFrame/

You can open https://rajibghosal2016.github.io/Parent/ and check for memory leakage.

**Comment by AndrewKushnir** [comment]
@rajib-g thanks for additional information. I was able to reproduce the issue using https://rajibghosal2016.github.io/Parent/.

We've just released Angular v14.0.4 which contains the fix to a memory leak related to bootstrapped standalone components. Could you please try to update the `@angular/core` to `14.0.4` version on that page when you get a chance?

Also, you've mentioned in the issue description that this problem is a regression. I was wondering if you have any additional info on Angular versions that you've used before, when memory leak wasn't present. I'm curious if you saw an issue in Angular v13.0.0 or v13.1.0.

Thank you.

**Comment by AndrewKushnir** [comment]
@rajib-g one more thing that I noticed during my testing is that the `MessageEvent` is being logged into the console. The `MessageEvent` instance has the `source` property that points back to the window in the child `<iframe>`. As a result, the `window` is being retained in memory while the console is open. In my test after a few times of adding/removing an iframe, I've ran `console.clear()` in the console, triggered a garbage collection (using the trash can icon) and the memory was successfully released and got back to the original level. Could you please try to comment out that `console.log` and/or call the `console.clear()` and let me know if you see any differences. Thank you.

**Comment by rajib-g** [comment]
@AndrewKushnir Yes commenting out all of the console.log solves the issue. You are right that MessageEvent instance has the source property that points back to the window in the child <iframe> and that was creating the memory leakage.

Thanks for pointing out the actual issue.

I have seen various Github threads regarding memory leakage and I thought there is a high probability that this might be a regression. Some of those Github threads is given below:

1. https://github.com/angular/angular/issues/22106
2. https://github.com/angular/angular/issues/13725
3. https://github.com/DzmitryShylovich/angular/commit/b9f6585b162a0ab2e03bfa521bbc123d94a64e62
4. https://github.com/angular/angular/pull/22238

Again thanks a lot for helping me to solve the issue.
