### ISSUE TITLE
Dependency Injection - doc questions unclear

### ISSUE THREAD

**Issue by avri87** [angular/angular#46409]
### Description

Hey, reading about documents in that subject, I found out 2 things unclear:

1. In [Should I add other providers to a module or a component](https://angular.io/guide/ngmodule-faq#should-i-add-application-wide-providers-to-the-root-appmodule-or-the-root-appcomponent) it is said: ".....Lazy-loaded modules and their components can inject AppModule services; they **can't** inject AppComponent services...." the bold part is not correct, a very simple example can proves it, also I found out that there already opened [git issue about this](https://github.com/angular/angular/issues/29468), from some reason, they close it, but the example which the issuer opened, was good --> same service instance in AppComponent's providers can be reached in LAzyModule's component, **even** if lazy module has providers, I think the reason for this is that the resolution is starting in element tree and then module for resolving dependencies, I did test this in an example, I can share if needed
2. About [Limiting provider scope by lazy loading modules](https://angular.io/guide/providers#limiting-provider-scope-by-lazy-loading-modules), there is this part: "...The router **adds** all of the providers from the root injector to the child injector. When the router creates a component within the lazy-loaded context, Angular prefers service instances created from these **providers** to the service instances of the application root injector....":
    2.1) First, the bold part, **add**, what dose it mean? because it dose not just "add" from root to child injector, child inherits parent, them and if you **don't** provide same token in lazymodule, then it can access **same** instance in root injector, I found a discussion about this [here](https://stackoverflow.com/questions/52638901/is-lazy-loading-creating-new-injector-in-angular)
    2.2)  The second **providers**,  what "providers" is refered here? I think maybe you intended to the child injector that inherits the parent one, and if child injector also provide same token, then , lazy context get a copy instnace, else get the root one, right?

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
