### ISSUE TITLE
bug in angular.jp

### ISSUE THREAD

**Issue by Aman-askar** [angular/angular#46416]
### Description

there is an error in angular.jp website where a div aligned wrong

### What is the affected URL?

https://angular.jp/

### Please provide a screenshot if possible

![Screenshot from 2022-06-17 18-08-10](https://user-images.githubusercontent.com/84726046/174300759-076d8eb6-5f3d-42bc-883d-ed2a2a7bcf64.png)

**Comment by JoostK** [comment]
Please report in https://github.com/angular/angular-ja as this site is not maintained in this repo.
