### ISSUE TITLE
Component Styles are not shared anymore but duplicated per component with Ivy

### ISSUE THREAD

**Issue by rothsandro** [angular/angular#46418]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

**Use Case**:  
We use Angular Elements to define multiple WebComponents. Each WebComponent uses `ViewEncapsulation.ShadowDom` and includes a SCSS file that provides some "global" (= inside Shadow DOM) classes that can be used by all child components (which use default encapsulation).

**Problem**:  
Multiple Angular Components include the same SCSS file via styleUrls. After building the app, the main bundle now includes these CSS styles once per component, the styles are duplicated - which results in a large bundle (and thus requires to increase the budget limit).

We use Angular 13/14 but the problem can be reproduced in a newly created Angular 11 app. After disabling Ivy (which is not possible in newer Angular versions) the styles are not duplicated anymore but only included once in the bundle and referenced by all components. And that's the behavior I would expect.

I don't know if this change was intended or not but I couldn't find any information about that in the update guide / changelog / PRs.

For components with `ViewEncapsulation.Emulated` styles cannot be (easily) shared because the selectors are made unique but it's possible for Shadow DOM (and `ViewEncapsulation.None` I guess).

### Please provide a link to a minimal reproduction of the bug

https://github.com/rothsandro/repro-angular-duplicated-component-styles

### Please provide the exception or error you saw

**Angular 11, Ivy disabled**  
The styles are centralized and reused across all components:

![ivy-disabled](https://user-images.githubusercontent.com/16229645/174296323-3eaf6b45-086b-4255-bc6b-2adef0b1c5f1.png)

**Angular 11+, Ivy enabled**:  
The styled are directly part of the component and duplicated:

![ivy-enabled](https://user-images.githubusercontent.com/16229645/174296342-245d962f-12f8-4dcb-9318-d490696f01e3.png)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 11.2.19
Node: 14.18.3
OS: darwin x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: No

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.19
@angular-devkit/build-angular   0.1102.19
@angular-devkit/core            11.2.19
@angular-devkit/schematics      11.2.19
@angular/cli                    11.2.19
@schematics/angular             11.2.19
@schematics/update              0.1102.19
rxjs                            6.6.7
typescript                      4.1.6
```

**Comment by rothsandro** [comment]
Ah, you're right. I set `aot: false` for the first screenshot but that's not necessary to reproduce the behavior.

Styles are reused
- when I set `enableIvy: false` (aot can be enabled or disabled, doesn't matter) OR
- when I keep Ivy enabled but set `aot: false`

**Comment by alan-agius4** [comment]
Quoting @alxhub  
 


> Yes, this was an intentional change in Ivy.
> 
> In VE, each component CSS file was compiled into an .ngstyle.js file, which exported the CSS text as a constant. Each component which referenced that CSS file would then import that constant from the shared .ngstyle.js.
> 
> In Ivy, we made a choice that we didn't want any extra output files (no ngfactory, ngsummary, or ngstyle) - we'd follow pure TS semantics for ES modules. The result is that we inline CSS from resources now into each component, with no deduping.

**Comment by JoostK** [comment]
Ivy's style sharing only occur within a single source file, not across source files.
