### ISSUE TITLE
The type of falsy property is not properly inferred within the template of `*ngIf` directive

### ISSUE THREAD

**Issue by markostanimirovic** [angular/angular#46421]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

If we pass the property whose type contains only falsy types to the `*ngIf` directive:

```ts
@Component({
  selector: 'app-root',
  template: `
    <p *ngIf="falsy as f">
      <!-- no compilation errors -->
      <app-child [str]="f"></app-child>
      <app-child [str]="falsy"></app-child>
    </p>
  `,
  standalone: true,
  imports: [CommonModule, ChildComponent],
})
export class AppComponent {
  falsy: false | null | undefined = false;
}

@Component({
  selector: 'app-child',
  template: '{{ str }}',
  standalone: true,
})
export class ChildComponent {
  @Input() str = '';
}
```

the type of the passed property, as well as its alias, will be `any` within the `*ngIf` template.

Based on the context type guard:

```ts
static ngTemplateContextGuard<T>(
  dir: NgIf<T>, ctx: any
): ctx is NgIfContext<Exclude<T, false | 0 | '' | null | undefined>> {
  return true;
}
```

I expected the type to be `never`.

### Please provide a link to a minimal reproduction of the bug

https://github.com/markostanimirovic/ng-if-falsy-types

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.2
Node: 16.10.0
Package Manager: npm 7.24.0
OS: win32 x64

Angular: 14.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.2
@angular-devkit/build-angular   14.0.2
@angular-devkit/core            14.0.2
@angular-devkit/schematics      14.0.2
@schematics/angular             14.0.2
rxjs                            7.5.5
typescript                      4.7.4
```

**Comment by JoostK** [comment]
This does not reproduce for me; [`never` is assignable to `string`](https://stackoverflow.com/a/53748099/171436) so you won't get an error as you expected, which is also true if you write this code with just TypeScript.

[Here's a playground where you can see the types](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM52ARjgMyhEOAcgAFkA7AcwFcAbZKAegGMCQJyiBuAKB-OQgApqjDJmQjAAY4Abx5w4QgB6RYcZvVToAgmDABhApHJDy8eYsU5ktVAE8AXLlupJAHzjk6tOJ+rkACZCOMCmgXAAvC52QrwKVjCoACoiMAAUAJRyCVYYOHDpMAAWwKgAdDZ29tmWeVa0QvCoMFDOLVBhlFFwJWWVrva89XAAvrljCeMJKmrwmmjoBqW0gUbgHGYWEx09RNxTfNOs5C1wAPrMMNCYzgA8yT0BANbkEADu5AB86WHAMM4AArAZjPO5YcoAOUoAEkcA8vgAaOAAIiocJRflR6JwyWKZkxnjRsJwAFFYiivtlIl8MJgoSSET1vLRaABCeI4AJXYAcC4wZgAIwATEVSqhnMApOU9IZjJtzLV8oVWtQhLUJgA3Bj87CMBDJRwAERhACUEIw4PrhQBOAAsiIAzMKAOwWnqXa5QTDpWTYkko5zpYN9VCZAbVK0IR2YACsTuFUgt2X1MfjzqTjBT0akNoTmAtyOJcLxBOcLN8aBQ5HsRZx5Lcga8PhQ6Ao9jG2aNjmAlDeUCEFuGVnOMHpOKjjtzTswjvd0WDYrK4aqDkncYTmezac3ycn0+dBcYw8U2qg-OFznbzJ8HImwAKv3p0Lh5SoqXA9BgQiM5hUMAAcWoBhAnSUdMGRUdhWzW0HTtYU50tAAyJDCiXMMIzXVMNwzPdsPTRN3X1bte37QcsxyEZTx1UdHUnYUHWdWN50KKC3xJfc8xjRDtwPYVmOPCY8kYS04AAPQAfiEqwz35O1JWlZZgFWdYTC2KNDRNc1LVTF0pCdG0jxvVk7youTyl2VMAA5hSdKyBJ6MCYDo6yrLsm08OjKyIMdG1MxPSZRkmIA), in particular the type of `_t3` is correctly inferred as `never`.

**Comment by markostanimirovic** [comment]
Oh, my bad. I didn't even think that `never` is assignable to any type. 🤯 Thanks @JoostK!
