### ISSUE TITLE
Package "@angular/bazel" was found but does not support schematics.

### ISSUE THREAD

**Issue by mfbieber** [angular/angular#46423]
### Which @angular/* package(s) are the source of the bug?

bazel

### Is this a regression?

Yes

### Description

When trying to generate a new ng project with the cli, the following occurs:
````
ng new project --defaults --collection=@angular/bazel
Package "@angular/bazel" was found but does not support schematics.
````
`@angular/bazel` was previously installed via npm, so was `@angular/cli` - both on 14.0.2. I freshly installed Node.js and npm (Latest LTS Version: 16.15.1 (includes npm 8.11.0)). I also could not get it to work with previous Angular versions, going also down to Node.js v14.9.13 (and a 6.x npm version).

I know that `@angular/bazel` has been deprecated (https://github.com/angular/angular/blob/main/packages/bazel/docs/BAZEL_SCHEMATICS.md).

My suggestion would be to remove it entirely if we are not supporting it.

Or I am doing this completely wrong - if so, please help ;)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.0.2
Node: 16.15.1
Package Manager: npm 8.11.0 
OS: darwin x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1400.2 (cli-only)
@angular-devkit/core         14.0.2 (cli-only)
@angular-devkit/schematics   14.0.2 (cli-only)
@schematics/angular          14.0.2 (cli-only)
```

**Comment by alan-agius4** [comment]
The `@angular/bazel` schematics has been deprecated and removed. However the `@angular/bazel` package itself is not deprecated as this package contains several bazel rules that can be used.

To use Bazel with Angular please take a look at https://dev.to/bazel/angular-bazel-leaving-angular-labs-51ja where a number of options are mentioned. 

It important to point out that the Angular team no longer supports Bazel integrations.

**Comment by AndrewKushnir** [comment]
Closing based on the comment from Alan above.
