### ISSUE TITLE
Template variables above the top of the viewport are stale after doing a browser refresh

### ISSUE THREAD

**Issue by jakobadam** [angular/angular#46434]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Variables in the Angular template above the top of the viewport are stale when doing a browser refresh. In other words, when scrolled down in the document and hitting refresh, the variables above the viewport top are not reflecting value changes.

The following image shows the problem.

![Unavngivet-png-1272×858-](https://user-images.githubusercontent.com/139791/174549769-30b30427-2c72-4747-9c57-2052de590683.png)

Can't point to a Stackblitz since it after refresh goes back to the top of the document. However, I added a pointer to a GitHub project.

In the example, I'm calculating the position of an element relative to the viewport top, in order to show some fixed positioned content when an element is reached. The workaround in this case, however, is easy. Move the thing that needs updating - the fixed header in this case - down to the bottom of the template...

It also happens in the `ng build` version of the app.

kind regards,
Jakob
 

### Please provide a link to a minimal reproduction of the bug

https://github.com/jakobadam/angular-browser-refresh-issue

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.2
Node: 14.19.0
Package Manager: npm 8.12.1
OS: win32 x64

Angular: 14.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.2
@angular-devkit/build-angular   14.0.2
@angular-devkit/core            14.0.2
@angular-devkit/schematics      14.0.2
@schematics/angular             14.0.2
rxjs                            7.5.5
typescript                      4.7.4
```

### Anything else?

no

**Comment by JoostK** [comment]
This is an issue with your code related to how change detection works. Change detection occurs top down and must be stable, meaning that you cannot change state after it has been rendered.

In your case, you're emitting the event `positionChange` from the `ngOnInit` lifecycle hook of `PositionDirective `, which subsequently updates the `fixed` variable. This reports a `ExpressionChangedAfterItHasBeenChecked` in development mode.

One way to fix it coud be to make the `positionChange` EventEmitter asyncrhonous, by passing `true` to its constructor. This would delay the `positionChange` event that currently occurs during the render (from within `ngOnInit`) to a _new_ render cycle, allowing the render to become consistent.

**Comment by jakobadam** [comment]
Thanks for the swift reply, the info and the tip:) Much appreciated.
