### ISSUE TITLE
Controls inside FormBuilder.group<T>() are not typed

### ISSUE THREAD

**Issue by theideasaler** [angular/angular#46432]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

Considering this code:

```
constructor( private _fb: FormBuilder) {}

ngOnInit() {
  this.form = this._fb.group<{name: FormControl<string|null>}>({
    name: new FormControl(null),
  });
  
  // Below code should throw error but not.
  this.form.controls.name.setValue(1234); 
}
```

**Expected**: the form field `name` should be typed as `string` or `null`, and should show error when setting its value to any other types.
**Actual**:   `this.form.controls.name.setValue(1234);` succeed without any warnings

### Please provide the environment you discovered this bug in (run `ng version`)

Angular: 14.0.2
IDE: VS Code

**Comment by jnizet** [comment]
Hi @theideasaler 

You left out the most important part: how you declared the `form` property. With the correct type declaration, the code does not compile, correctly complaining about the incorrect type of 1234:

```ts
  form!: FormGroup<{name: FormControl<string|null>}>;

  constructor( private _fb: FormBuilder) {}

  ngOnInit() {
    this.form = this._fb.group<{name: FormControl<string|null>}>({
      name: new FormControl(null),
    });

    // Below code does cause a compilation error
    this.form.controls.name.setValue(1234);
  }
```

**Comment by theideasaler** [comment]
> Hi @theideasaler
> 
> You left out the most important part: how you declared the `form` property. With the correct type declaration, the code does not compile, correctly complaining about the incorrect type of 1234:
> 
> ```ts
>   form!: FormGroup<{name: FormControl<string|null>}>;
> 
>   constructor( private _fb: FormBuilder) {}
> 
>   ngOnInit() {
>     this.form = this._fb.group<{name: FormControl<string|null>}>({
>       name: new FormControl(null),
>     });
> 
>     // Below code does cause a compilation error
>     this.form.controls.name.setValue(1234);
>   }
> ```

Hi @jnizet ,

Thanks for pointing that out. I think I missed it.
