### ISSUE TITLE
Docs: Broken html tag appears in a note

### ISSUE THREAD

**Issue by nakano531** [angular/angular#46430]
### Description

"&lt;header&lt;base href&gt;" appears in the first note on the URL.

### What is the affected URL?

https://angular.io/guide/router

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/8080915/174483175-d3819e05-b2a8-4e33-875f-f64c62d7f301.png)

**Comment by behroozbc** [comment]
My merge request was merged.
I think it is time to close this issue.
