### ISSUE TITLE
Nativescript Client authentication certificate support

### ISSUE THREAD

**Issue by abdallahkadour** [angular/angular#46444]
### Which @angular/* package(s) are relevant/related to the feature request?

HTTP
### Description

I am using this library in nativescript to communicate to a backend server, all CRUDE requests are working as expected. In the meantime the server configuration has changed and we need now to authenticate using an SSL certificate
In node I am able to do it  using `AgentOptions`as follow:

```js
 agentOptions: {
    pfx: fs.readFileSync(__dirname + '/file.pfx'),
    passphrase: 'password'
  },
```
Is this feature supported?

***Full code:***
```js

var request = require('request')
//const pem = require('pem')
const fs = require('fs')

const qr =
  'HC1:....'

console.log(fs.readFileSync(__dirname + '/file.pfx'))
var options = {
  method: 'POST',
  url: 'https//.../verify',
  headers: {
    'X-Validate-For': 'DE',
    'Content-Type': 'application/cbor+base45',
    accept: 'application/json',
    'X-Transaction-Id': 'uuid'
  },
  agentOptions: {
    pfx: fs.readFileSync(__dirname + '/file.pfx'),
    passphrase: 'password'
  },
  body: qr
}

request(options, function (error, response, body) {
  console.log('headers', options.headers)
  if (error) throw new Error(error)

  console.log(response.headers)
  console.log(body)
})

```

### Proposed solution

_

### Alternatives considered

_

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
