### ISSUE TITLE
ERROR in Cannot resolve type entity i64.ToolBarModule to symbol

### ISSUE THREAD

**Issue by inphadalem** [angular/angular#46441]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I added kendo-angular-editor and I got this issue
Any thoughts? Please help.

![image](https://user-images.githubusercontent.com/35090794/174736242-f9f93e73-f59e-47dc-8549-95611595b61d.png)

Below is my package.json
`{
  "name": "client-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "echo Starting... && ng serve --host 0.0.0.0",
    "build": "ng build",
    "builddev": "ng build --aot --configuration=development --extract-css",
    "buildtest": "ng build --aot --configuration=test --extract-css",
    "buildprod": "ng build --aot --configuration=production --extract-css",
    "build:ssr": "npm run build -- --app=ssr --output-hashing=media",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "doc": "npx compodoc -p src/tsconfig.app.json -n \"TemplateAngularAppdocumentation\""
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.2.4",
    "@angular/cdk": "^10.2.7",
    "@angular/common": "~10.2.4",
    "@angular/compiler": "~10.2.4",
    "@angular/core": "~10.2.4",
    "@angular/forms": "~10.2.4",
    "@angular/localize": "^10.2.4",
    "@angular/material": "^10.2.7",
    "@angular/platform-browser": "~10.2.4",
    "@angular/platform-browser-dynamic": "~10.2.4",
    "@angular/router": "~10.2.4",
    "@aspnet/signalr": "^1.1.4",
    "@auth0/angular-jwt": "^3.0.1",
    "@progress/kendo-angular-buttons": "^5.5.2",
    "@progress/kendo-angular-common": "^2.0.0",
    "@progress/kendo-angular-dateinputs": "^4.4.1",
    "@progress/kendo-angular-dropdowns": "^4.4.1",
    "@progress/kendo-angular-editor": "^4.1.2",
    "@progress/kendo-angular-excel-export": "^3.1.6",
    "@progress/kendo-angular-grid": "^4.8.4",
    "@progress/kendo-angular-inputs": "^6.7.4",
    "@progress/kendo-angular-intl": "^2.0.4",
    "@progress/kendo-angular-l10n": "^3.0.0",
    "@progress/kendo-angular-pdf-export": "^2.1.0",
    "@progress/kendo-angular-popup": "^3.0.7",
    "@progress/kendo-angular-upload": "^7.1.5",
    "@progress/kendo-data-query": "^1.5.4",
    "@progress/kendo-drawing": "^1.9.3",
    "@progress/kendo-licensing": "^1.2.1",
    "@progress/kendo-schematics": "^1.2.1",
    "@progress/kendo-theme-default": "^4.30.0",
    "@types/chart.js": "^2.9.29",
    "bootstrap": "^4.5.3",
    "chart.js": "^2.9.4",
    "chartjs-plugin-datalabels": "^0.7.0",
    "core-js": "^2.6.12",
    "file-saver": "^2.0.5",
    "jquery": "^3.5.1",
    "jspdf": "^2.3.1",
    "ng2-charts": "^2.4.2",
    "ng2-tooltip-directive": "^2.9.22",
    "ngx-spinner": "^10.0.1",
    "ngx-toastr": "^11.3.3",
    "popper.js": "^1.16.1",
    "rxjs": "^6.6.3",
    "tslib": "^2.3.1",
    "typescript": "^4.0.5",
    "xlsx": "^0.15.6",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1002.1",
    "@angular/cli": "^10.2.1",
    "@angular/compiler-cli": "~10.2.4",
    "@angular/language-service": "~10.2.4",
    "@types/jasmine": "^2.8.17",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "^12.19.9",
    "codelyzer": "^5.2.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.1.0"
  }
}
`

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Node	: 14.176
NPM	: 6.14.15
```

**Comment by JoostK** [comment]
This typically happens when a library is linked from another directory tree, where the necessary dependencies do not resolve (as there is no corresponding `node_modules` directory from within that tree).

If it is due to symlinks, then enabling `preserveSymlinks` in the `angular.json` file may help. Otherwise, explicit path mappings for the unresolved dependency may also help, but I can't give any more advice without a reproduction.

**Comment by inphadalem** [comment]
I tried enabling `preserveSymlinks` in the `angular.json` file .. but no luck.
How to do explicit path mappings for the unresolved dependency ?

**Comment by JoostK** [comment]
As mentioned, I can't give any more advice without a reproduction.

**Comment by inphadalem** [comment]
I installed old version of Editor now.. it resolved my issue.

npm i @progress/kendo-angular-editor@0.10.0	 
npm i @progress/kendo-angular-dialog@4.1.0
npm i @progress/kendo-angular-layout@4.1.4
npm i @progress/kendo-angular-toolbar@2.2.0
