### ISSUE TITLE
ng test doesn't support index.ts imports

### ISSUE THREAD

**Issue by lukasmatta** [angular/angular#46452]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Hello,
`ng test` fails when there are folder imports that use `index.ts` file. On the other side, `ng build` works ok.

### Please provide a link to a minimal reproduction of the bug

https://github.com/lukasmatta/angular-index-import

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.2
Node: 16.13.1
Package Manager: npm 8.12.2
OS: darwin x64

Angular: 14.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.2
@angular-devkit/build-angular   14.0.2
@angular-devkit/core            14.0.2
@angular-devkit/schematics      14.0.2
@schematics/angular             14.0.2
rxjs                            7.5.5
typescript                      4.7.4
```

**Comment by JoostK** [comment]
This seems to work as expected; the `app.component.spec.ts` test defines a testing module that declares `AppComponent`, meaning that its original declaration in `AppModule` no longer applies. Consequently, you also need to include the declarations for `HelloOneComponent` and `HelloTwoComponent` in the testing module for everything to work.

**Comment by alan-agius4** [comment]
Hi @lukasmatta, 

I had a look at the reproduction and it appears that the tests are failing because the expect is no longer correct due to the changes in https://github.com/lukasmatta/angular-index-import/blob/master/src/app/app.component.html

You are also getting the below error
```
ERROR: 'NG0304: 'app-hello-one' is not a known element (used in the 'AppComponent' component template):
1. If 'app-hello-one' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
2. If 'app-hello-one' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'
```

And the reason for that is that both `HelloOneComponent` and `HelloTwoComponent` are not included in the declarations of the testing module. 

```ts
 await TestBed.configureTestingModule({
      imports: [RouterTestingModule],
      declarations: [AppComponent, HelloOneComponent, HelloTwoComponent],
    }).compileComponents();
```

**Comment by lukasmatta** [comment]
@JoostK, @alan-agius4 Hello guys, thanks for the fast response. I've updated the repository to reproduce the error correctly. 

If I try to build the project from the `master` branch, everything works correctly, however `ng test` fails. I've also added branch `fix/import` in which I've replaced the import with the absolute one. In this branch, `ng test` works correctly.

**Comment by JoostK** [comment]
That is most likely due to a cycle in your code:

```
>  ./node_modules/.bin/ngc -p tsconfig.app.json
> npx madge --circular out-tsc/app/main.js
Processed 12 files (268ms) (3 warnings)

✖ Found 1 circular dependency!

1) app/ads/ad-banner.component.js > app/ads/index.js
```
