### ISSUE TITLE
Standalone Components not working properly if they rely on BrowserAnimationsModule

### ISSUE THREAD

**Issue by SiddAjmera** [angular/angular#46467]
### Which @angular/* package(s) are the source of the bug?

core, platform-browser

### Is this a regression?

No

### Description

Was trying to refactor an old side project to use Standalone Component in Angular. Went pretty smoothly but with a catch. I'm using animations in `PokemonCardComponent`. So:

If I add in `BrowserAnimationsModule` to the `imports` of the standalone Component, I'm getting an error:

> Error: Uncaught (in promise): Error: Providers from the `BrowserModule` have already been loaded. If you need access to common directives such as NgIf and NgFor, import the `CommonModule` instead.
> Error: Providers from the `BrowserModule` have already been loaded. If you need access to common directives such as NgIf and NgFor, import the `CommonModule` instead.

If I get rid of `BrowserAnimationsModule` from the `imports` of the standalone Component, I'm getting an error:

> Error: Unexpected synthetic property @fadeAnimation found. Please make sure that:
> - Either `BrowserAnimationsModule` or `NoopAnimationsModule` are imported in your application.
> - There is corresponding configuration for the animation named `@fadeAnimation` defined in the `animations` field of the `@Component` decorator.

And as expected, my App isn't loading and working as expected.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-pokemon-card-grid-nftda9?file=src%2Fapp%2Fapp.component.ts

**Comment by ChellappanRajan** [comment]
Try this:https://github.com/angular/angular/issues/46278
