### ISSUE TITLE
Add a method to remove a specified `AbstractControl` from a `FormArray`

### ISSUE THREAD

**Issue by framasev** [angular/angular#46477]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

`FormArray` has the `removeAt` method, that allows to remove a control at a given index, but it's not enough to simply solve some range of problems: an implementation requires to keep track of indices and state. 

Example problem: remove controls that satisfy a condition.
```typescript
let removedCount = 0;

[...formArray.controls].forEach((control, index) => {
  if (condition) {
    formArray.removeAt(index - removedCount);
    removedCount++;
  }
});
```

A method to remove a specified `AbstractControl` from a `FormArray` would allow us to simply solve such problems:
```typescript
formArray.controls
  .filter(control => condition)
  .forEach(control => formArray.remove(control));
```

### Proposed solution

Add a new `remove` method to `FormArray` that will allow to remove a specified control:

```typescript
class FormArray {
  /**
   * Remove a specified control from an array.
   */
  remove(control: AbstractControl): void {
    ...
  }
}
```

### Alternatives considered

No alternatives considered.

**Comment by AndrewKushnir** [comment]
@framasev thanks for creating a feature request. With the current implementation of the `AbstractControl` and other classes that extend it, adding new helper methods would cause bundle size increase, even if the function is unused. There is more info about this in #39640. I'm closing this ticket for now and we'll review all proposals related to additional helpers when the tree-shaking of the core Forms implementation is improved.
