### ISSUE TITLE
@angular/core/global is not exposed

### ISSUE THREAD

**Issue by mattcrouzet** [angular/angular#46487]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

From what I can see in the documentation @angular/core/global is an entry-point.
But it's not expose when I install @angular/core I don't have @angular/core/global in my node modules.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.1
Node: 16.13.1
Package Manager: yarn 3.2.1
OS: darwin x64

Angular: 13.3.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.1
@angular-devkit/build-angular   13.3.1
@angular-devkit/core            13.3.1
@angular-devkit/schematics      13.3.1
@angular/cdk                    13.3.2
@angular/material               13.3.2
@schematics/angular             13.3.1
ng-packagr                      13.3.0
rxjs                            7.5.5
typescript                      4.5.5
webpack                         5.70.0
```

**Comment by JoostK** [comment]
The `@angular/core/global` doesn't actually exist as an entry-point, it's only declared like this so that it shows up on angular.io:

https://github.com/angular/angular/blob/d1ea1f4c7f3358b730b0d94e65b00bc28cae279c/packages/core/global/index.ts#L9-L10

I'm not sure what can be done to improve this to avoid any confusion there might be.

**Comment by mattcrouzet** [comment]
Is there a way I can access to the methods typings exposed in the window.ng ?
I would not expect to re-define the typings on my side.
