### ISSUE TITLE
Lazy loaded component does not render dynamic templates (via ViewContainerRef.createComponent)

### ISSUE THREAD

**Issue by vzakharov-rxnt** [angular/angular#46493]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

The approach I'm using to lazy load a component is based on this code:
- https://github.com/wittyprogramming/lazy-load-component-angular13/blob/master/src/app/app.component.ts

Probably the most relevant part of the code:
```
 async ngOnInit(): Promise<void> {
    await this.lazyLoad();
  }

  private async lazyLoad() {
    const { TestModule } = await import(/* webpackChunkName: "main.test" */ "../test/test.module");
    const { TestComponent } = await import(/* webpackChunkName: "main.test" */ "../test/test.component");

    const moduleRef = createNgModuleRef(TestModule, this.injector);
    this.lazyComponent.clear();
    this.lazyComponent.createComponent(TestComponent, {ngModuleRef: moduleRef});
  }
```

When a lazily loaded component (here `TestComponent`) has a structural directive such as `*ngIf`, that part of html is not rendered. Instead, `<!-- container -->` is rendered.

![image](https://user-images.githubusercontent.com/85562318/175571898-d39766e7-4133-4a31-a953-48e044bacaea.png)

I originally found this issue when working on Angular upgrade from 1.x to 13.x, following this guide:
- https://angular.io/guide/upgrade

However, it does not seem related to AngularJS or the Hybrid app. The official guide mentions use of Angular components inside of AngularJS, but does not mention how to lazy load those components. I hesitated between opening this issue as a bug or a doc issue. If there is another route-independent way to lazy load a component which is compatible with ngUpgrade, please let me know. I could not find it.

### Please provide a link to a minimal reproduction of the bug

https://github.com/vzakharov-rxnt/ng14-dynamic-template-issue

### Please provide the exception or error you saw

No errors but any dynamic content, for example anything under `*ngIf`, `*ngFor` or `*ngTemplateOutlet`, is not rendered. Instead, it rendered `<!-- container -->` in every case when a structural directive was used.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.3
Node: 16.15.0
Package Manager: yarn 1.22.15
OS: win32 x64

Angular: 14.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router, upgrade

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.3
@angular-devkit/build-angular   14.0.3
@angular-devkit/core            14.0.3
@angular-devkit/schematics      14.0.3
@schematics/angular             14.0.3
rxjs                            7.5.5
typescript                      4.7.4
```

### Anything else?

Issue happens in both Angular 13.x and 14.x.
Change detection strategy does not matter.

**Comment by atscott** [comment]
This is working as expected. Your `TestLazyComponent` is marked as `OnPush` and creating the component inside the `lazyComponent` `ViewContainerRef` is a change that needs to be captured by change detection. After you call `createComponent`, you need to call [ChangeDetectorRef#markForCheck](https://angular.io/api/core/ChangeDetectorRef#markForCheck)
