### ISSUE TITLE
add nonNullable to FormGroup and change the nonNullable design for FormBuilder

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#46499]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

I see we have implemented for formBuilder but I don't like the syntax, We should pass nonNullable as param instead of extending the nonNullable.

```
const fb = new FormBuilder()
const login = fb.group({
    email: '',
    password: '',
}, {nonNullable: true});
```

Also do support on FormGroup
 ```
 myForm = new FormGroup({
    name: new FormControl('indra',),
    work: new FormControl(true),
  }, {nonNullable: true});
```

### Proposed solution

Change the syntax 
```
const fb = new FormBuilder();
const login = fb.nonNullable.group({
    email: '',
    password: '',
});
```

To
 
```
const fb = new FormBuilder();
const login = fb.group({
    email: '',
    password: '',
}, {nonNullable: true});
```
Also do support on FormGroup

 ```
 myForm = new FormGroup({
    name: new FormControl('indra',),
    work: new FormControl(true),
  }, {nonNullable: true});
```

### Alternatives considered

N/A

**Comment by shaurya074** [comment]
hey! Can i work on it?

**Comment by alxhub** [comment]
This isn't technically possible unfortunately, because `nonNullable` is a property of _controls_, not the group. The type of a control needs to be inferred only based on the `new FormControl` operation and can't consider the context in which it's used. Consider this slightly modified:

```typescript
const name = new FormControl('indra');
myForm = new FormGroup({
   name,
   work: new FormControl(true),
 }, {nonNullable: true});
```

Here, `name` would get an inferred type of `FormControl<string|null>` because it doesn't have the `nonNullable` option set. Including that in a `FormGroup` with a `nonNullable` option set doesn't really "fit" from an API sense.

**Comment by indraraj26** [comment]
There I am getting as `(property) name: FormControl<string>` instead of `<string|null>` since we initialized with string value 'indra'.  We should keep the `nonNullable` on `FormControl` too. 

With current implementation, You will have to mark `nonNullable` on each control. We should have one public API  that can pass down the `nonNullable`  to each control.

Same for `FormArray`, We should passed down the `nonNullable` to `FormGroup` if there is one then that will pass down to `FormControl` otherwise directly to the `FormControl`

If it is not doable then It is fine, Feel free to close the issue. 

Thank you
