### ISSUE TITLE
After update to Angular 14: Cannot find module '@angular/compiler/src/compiler_facade_interface' or its corresponding type declarations.

### ISSUE THREAD

**Issue by CodeLiftSleep** [angular/angular#46490]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular 13

### Description

 A clear and concise description of the problem...
Followed angular.io update procedures and ran: 

ng update @angular/core@14 @angular/cli@14

Everything updated and then attempted an ng build(ng build and serve worked fine in Angular 13 and the project ran without issue)

Build fails with the following message: "Cannot find module '@angular/compiler/src/compiler_facade_interface' or its corresponding type declarations."

Attempting to import {StringMap} from '@angular/compiler/src/compiler_facade_interface' in one of the modules.  Has something changed or is this no longer the proper place to try and import it from?

## 🔬 Minimal Reproduction

-Upgrade from Angular 13 to Angular 14 via running: ng update @angular/core@14 @angular/cli@14
-run npm i 
-attempt to import {StringMap} from '@angular/compiler/src/compiler_facade_interface' in a module
-run ng build(which will fail with the error noted)

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 14.0.3
Node: 16.15.0
Package Manager: npm 7.5.6
OS: win32 x64

Angular: 14.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.3
@angular-devkit/build-angular   14.0.3
@angular-devkit/core            14.0.3
@angular-devkit/schematics      14.0.3
@schematics/angular             14.0.3
rxjs                            6.6.7
typescript                      4.7.4

</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
Deep imports to non-public API methods are not supported.
