### ISSUE TITLE
Got TS2322 error when instantiate FormControl<string> with typescript 'strict' flag

### ISSUE THREAD

**Issue by ISTAnsver** [angular/angular#46494]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

Hello everyone!

I'm not sure but seems it's strange behaviour when I try to instantiate `FormControl<string>` object. I have enabled strict mode for TypeScript and then I've got the next error message from compiler:  
```
error TS2322: Type 'FormControl<string | null>' is not assignable to type 'FormControl<string>'.
  Type 'string | null' is not assignable to type 'string'.
    Type 'null' is not assignable to type 'string'.
```
I don't wanna change generic type of declared variable to `string | null`. I absolutely know that `null` value isn't possible and it must be forbiden to assign. Field is initialized with empty string in the constructor.  If `null` is possible then once it will be certainly happened .
I think that this behaviour should be changed.

It's relative to  #13721 feature.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-n7wfaq?file=src/app/hello.component.ts

### Please provide the exception or error you saw

```true
error TS2322: Type 'FormControl<string | null>' is not assignable to type 'FormControl<string>'.
  Type 'string | null' is not assignable to type 'string'.
    Type 'null' is not assignable to type 'string'.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.0
Node: 16.13.2
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 14.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router
```

**Comment by JoostK** [comment]
This is working as intended; you have to use the `nonNullable` option:

```ts
    this.name = new FormControl<string>('', {
      asyncValidators: [],
      validators: [],
      nonNullable: true,
    });
```

Please consult [the typed forms docs](https://angular.io/guide/typed-forms#nullability) for more information.
