### ISSUE TITLE
Angular 14 version not supported PrimeNG ver 13?

### ISSUE THREAD

**Issue by JKAngular** [angular/angular#46498]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

Yes

### Description

How to resolve this

![image](https://user-images.githubusercontent.com/59573064/175758398-c13ba115-cc79-4fc6-bd81-64d67e96cc7b.png)

### Please provide the exception or error you saw

```true
I canot install PrimeNg in Angular 14 version
```

**Comment by JoostK** [comment]
Please see https://github.com/primefaces/primeng/issues/11586.

**Comment by JKAngular** [comment]
Angular 14 version PrimeNg 13.4.1 version

**Comment by ces6jedi** [comment]
+1
