### ISSUE TITLE
MatDialog as route with router-outlet in template will freeze the app by opening infinite dialogs

### ISSUE THREAD

**Issue by bboehm86** [angular/angular#46500]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

I want to have (child)-routes rendered in an open `mat-dialog`, so I can navigate to different tabs in the dialog. This was working in the past, but now it will freeze the app.

When adding a `router-outlet` into a `ng-template` for a `mat-dialog` (or using a component for the dialog) it renders the route of the first `router-outlet`s route of the app into the dialogs `router-outlet` (in the example the `app-dialog` component). This will lead to infinitely rendered dialogs since each dialog will open another one with the same route and the app is frozen. 

### Please provide a link to a minimal reproduction of the bug

https://github.com/bboehm86/bug-routing-and-dialog-test

### Please provide the exception or error you saw

```true
No error, just a frozen app
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.0.3
Node: 18.0.0 (Unsupported)
Package Manager: npm 8.6.0 
OS: darwin arm64

Angular: 14.0.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.3
@angular-devkit/build-angular   14.0.3
@angular-devkit/core            14.0.3
@angular-devkit/schematics      14.0.3
@schematics/angular             14.0.3
rxjs                            7.5.5
typescript                      4.7.4
```

### Anything else?

 **Before opening the started dev app of the reproduction in the browser, open the devtools to hit the debugger statement, otherwise it will freeze your tab**

**Comment by atscott** [comment]
You've essentially created an infinite look in your route configuration and component. Your component opens a new dialog that has a totally new `router-outlet` that matches the component's config which renders the component which opens a dialog with a new and detached`router-outlet` that matches the component's config, etc. etc.

You need to ensure the `router-outlet` in the routed component is a logic child of the one in `AppComponent`. You can do this by setting the `viewContainerRef` property of [MatDialogConfig](https://material.angular.io/components/dialog/api#MatDialogConfig)

> Where the attached component should live in Angular's logical component tree. This affects what is available for injection and the change detection order for the component instantiated inside of the dialog. This does not affect where the dialog content will be rendered.

```
export class DialogRouteComponent implements AfterViewInit {
  @ViewChild('dialog') dialogTemplate: any;

  constructor(private _dialog: MatDialog, private vcr: ViewContainerRef) {
    /* alert(`Dialog nested in itself ${++dialogCount}`); */
  }

  ngAfterViewInit(): void {
    this._dialog.open(this.dialogTemplate, {viewContainerRef: this.vcr});
  }
}
```

**Comment by bboehm86** [comment]
@atscott massive THANK YOU! I totally missed that! 

That it worked somehow before was just a coincidence then, you just keep on learning I guess... Thanks again for the detailed answer, and sorry for the trouble 🙂
