### ISSUE TITLE
`scrollPositionRestoration: 'enabled'` causing issue with class and style bindings

### ISSUE THREAD

**Issue by ruvkr** [angular/angular#46501]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I have some styles
```css
.title {
  margin-top: 200px;
  background-color: skyblue;
  color: green;
  transition: all 2000ms;
}
```
This is the template
```html
<h1 [class.title]="true" [style.margin-left]="'100px'">Home</h1>
```
The class `title` and style `margin-left` should always be in html and there should be no transitions. Which is true when first load or navigate using `routerLink`. But if I scroll the page and come back to it using browser navigation buttons, I can see transitions. In Firefox I can always see transitions.

https://user-images.githubusercontent.com/34903858/175776581-390302a5-8fb1-4555-811a-656f8e623d36.mp4

https://user-images.githubusercontent.com/34903858/175776590-7fbbcc2e-46c5-4c99-84d1-df6aca001bec.mp4

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-zxjftn?file=src/app/pages/home.component.ts

Open the preview url in new tab while testing
https://angular-ivy-zxjftn.stackblitz.io

1. In home scroll down a little
2. Go to about page and scroll down
3. Navigate using browser navigation buttons

### Please provide the exception or error you saw

```true
No exceptions
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.2
Node: 16.15.1
Package Manager: npm 8.12.2 
OS: linux x64

Angular: 14.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.2
@angular-devkit/build-angular   14.0.2
@angular-devkit/core            14.0.2
@angular-devkit/schematics      14.0.2
@nguniversal/builders           14.0.1
@nguniversal/express-engine     14.0.1
@schematics/angular             14.0.2
rxjs                            7.5.5
typescript                      4.7.3
```

### Anything else?

No

**Comment by atscott** [comment]
This is really a timing issue and browser quirk unrelated to the router or scroll restoration. When using `attr.` and `style.`, those _are not_ "always" in the HTML. The `h1` element gets created _without_ the class and style and those get added when the next change detection happens. The interaction with scrollRestoration happens to make the change detection run later so the browser picks up the addition of the `class` and `style`. 

If the intent is to have those values be static and always present, I would recommend not using `attr.` and `style.`

**Comment by ruvkr** [comment]
@atscott I have a use case where I need dynamic host class binding.
```ts
@Component({
  selector: '[app-button]',
  host: {'[class]': 'variant'}
})

@Input() variant: 'primary' | 'secondary' = 'primary'
```
Is there any other way I can do this?

**Comment by atscott** [comment]
Yes and no. Your host bindings are dynamic so they rely on a change detection running before they get applied. 

You can add attributes to the native element in the constructor to have them there at creation time:
```
constructor(elementRef: ElementRef) {
    elementRef.nativeElement.classList.add('primary');
    elementRef.nativeElement.style.someProperty('10px');
}
```

If you have an animation on 'primary'/'secondary', that will still show if it changes to `secondary` from the binding.

Another option might be to force synchronous change detection immediately on `NavigationEnd` event (https://stackblitz.com/edit/angular-ivy-tsiy14?file=src%2Fapp%2Fapp.component.ts) rather than waiting for the next animation frame. This will actually also have the side-effect of fixing the scroll restoration for things that aren't immediately visible during creation mode (i.e., they require change detection to run).

**Comment by ruvkr** [comment]
@atscott Yes, I need the transitions when changing class. This is exactly what I needed. Thanks for the help.
