### ISSUE TITLE
Facing issue while implementing lazy-loading on angular 13 application

### ISSUE THREAD

**Issue by lakhvir1994** [angular/angular#46534]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

Implemented lazy loading as described in the angular document https://angular.io/guide/lazy-loading-ngmodules.
After implementing it I try to load routes but whenever I access any route then all the other modules are also called, which should not.

app-routing.module.ts

import { NgModule } from '@angular/core';
import { RouterModule, Routes, ExtraOptions } from '@angular/router';
import { MainComponent } from './Main/Main.component';
import { ExistingPageComponent } from './ExistingPage/ExistingPage.component';
// Services
import { AuthGuard } from './Core/_guards'; // Auth services
// Components
import { JobDetailsComponent, BlogDetailsComponent, AuthorBlogComponent } from './ThemeElements';
import { QuoteRedirectionComponent } from './QuoteRedirection/QuoteRedirection.component';
// Session components
import { SessionComponent, LoginComponent, SignupComponent, ForgotPasswordComponent, ResetPasswordComponent, PasswordProtectComponent, ReferralSignupComponent } from './Session';

const routes: Routes = [
    { path: '', component: MainComponent},
    { path: "password-protected", component: PasswordProtectComponent },
    { path: "job-details/:slug", component : JobDetailsComponent },
    { path: "blog/:slug", component : BlogDetailsComponent },
    { path: "author/:type/:slug", component : AuthorBlogComponent },
    { path: "category/:type/:slug", component : AuthorBlogComponent },
    { path: 'booking-quote/:qid/:slink', component: QuoteRedirectionComponent},
    { path: 'booknow', loadChildren: () => import('./AddBookings/AddBookings.module').then(m => m.AddBookingsModule)},
    { path: 'reschedule-booking', loadChildren: () => import('./RescheduleBookings/RescheduleBookings.module').then(m => m.RescheduleBookingsModule), canActivate: [AuthGuard], runGuardsAndResolvers: 'always'},
    { path: 'dashboard', loadChildren: () => import('./Dashboard/Dashboard.module').then(m => m.DashboardModule), canActivate: [AuthGuard], runGuardsAndResolvers: 'always'},
    { path: 'appointments', loadChildren: () => import('./Appointments/Appointments.module').then(m => m.AppointmentsModule), canActivate: [AuthGuard], runGuardsAndResolvers: 'always'},
    { path: 'gift-cards', loadChildren: () => import('./GiftCards/GiftCards.module').then(m => m.GiftCardsModule) },
    { path: 'referrals', loadChildren: () => import('./Referrals/Referrals.module').then(m => m.ReferralsModule), canActivate: [AuthGuard], runGuardsAndResolvers: 'always'},
    { path: 'contact-us', loadChildren: () => import('./LeadForm/LeadForm.module').then(m => m.LeadFormModule), runGuardsAndResolvers: 'always'},
    { path: 'info', loadChildren: () => import('./UserPages/UserPages.module').then(m => m.UserPagesModule), canActivate: [AuthGuard], runGuardsAndResolvers: 'always'}
    { path: '**', component : MainComponent }
];

const routeOptions: ExtraOptions = {
    onSameUrlNavigation: 'reload',
    scrollPositionRestoration: 'top',
    relativeLinkResolution: 'legacy',
    anchorScrolling: 'enabled',
    // initialNavigation: 'enabled',
    paramsInheritanceStrategy: 'always'
}

@NgModule({
    imports: [RouterModule.forRoot(routes, routeOptions)],
    exports: [RouterModule]
})
export class AppRoutingModule { }

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.8
Node: 14.19.3
Package Manager: npm 6.14.17
OS: linux x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.8
@angular-devkit/build-angular   13.3.8
@angular-devkit/core            13.3.8
@angular-devkit/schematics      13.3.8
@angular/cdk                    13.3.9
@angular/cli                    13.3.8
@angular/material               13.3.9
@nguniversal/builders           13.1.1
@nguniversal/express-engine     13.1.1
@schematics/angular             13.3.8
rxjs                            7.4.0
typescript                      4.6.4
```

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
