### ISSUE TITLE
Update typescript version used in plunkers to 1.6.2

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#4653]
The [plunker template](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5) uses TS version 1.6.0-beta [pulled from code.angularjs.org](https://github.com/angular/code.angularjs.org/tree/master/tools). This version is buggy.

Can we get it upgrade to 1.6.2 please?

Related to https://github.com/angular/angular/issues/4585#issuecomment-147103749

**Comment by ericmartinezr** [comment]
@IgorMinar besides that you could update ng2 version to a40 and remove traceur :+1:

**Comment by vicb** [comment]
@IgorMinar are you sure that this `typescript.js` is used at all ? (I don't see this mentionned in http://embed.plnkr.co/suu7Yg/preview) - wouldn't the implicit mode kick in before `config.js` is used ?

_I've sent a PR to plunker to update TS, see the #4585_

**Comment by robwormald** [comment]
@IgorMinar see https://github.com/angular/code.angularjs.org/pull/29

@vicb the plunkers request `somefile.ts` and thus plunker isn't involved at all, it's SystemJS doing the compilation. once plunker bumps to 1.6.2 i can adjust the plunker template.

**Comment by IgorMinar** [comment]
it's in index.html

@ericmartinezr we'll remove traceur later as it would break all the relatively recent plunks

**Comment by IgorMinar** [comment]
landed
