### ISSUE TITLE
docs: clearly explain if/when we need to unsubscribe from HttpClient calls

### ISSUE THREAD

**Issue by digeomel** [angular/angular#46542]
### Description

Hello, I've been going through the documentation of the `HttpClient` service (https://angular.io/guide/http) trying to find any mention of whether  it is necessary to unsubscribe from the generated observables or not, and the only mention I could find was about using the `AsyncPipe`, which is irrelevant (because we don't have to or might not want to use it).

So, I think the documentation should clarify when (if ever) we need to unsubscribe from calls.

**Update**:
Perhaps I should clarify a bit more. This article:
https://medium.com/angular-in-depth/why-you-have-to-unsubscribe-from-observable-92502d5639d0
explains very well the reasons why we should unsubscribe from all HttpClient observables *always*.
Personally, I've struggled to convince my team to do it, because their usual answer is that HttpClient will do it automatically and of course very few people bother to read beyond the official documentation _which doesn't mention anything about unsubscribing_.
I have been doing it for a long time with Net Basal's excellent [ng-neat/until-destroy](https://github.com/ngneat/until-destroy) library, but I feel that this is such a core concept of any real-life Angular app that it *should* be clearly documented.

**Comment by digeomel** [comment]
@bob-watson that's great and as I wrote above this is exactly what I recommend my team to do, but can we please have it written in the documentation, instead of just having the generic mention of the `async` pipe?

**Comment by digeomel** [comment]
Related to this topic, another pain point that I struggled to convince my team about it to never create such observables in (singleton) services, at least not without an extra mechanism to unsubscribe from the previous observable before creating a new one. I suppose this should be obvious coming from the recommendation to always unsubscribe when a component is destroyed, but again, would be nice to clarify in the documentation.

**Comment by ileil** [comment]
Under "Starting the request", added the following note:

You should always unsubscribe from an observable when a component is destroyed. You can use the [`AsyncPipe`](api/common/AsyncPipe) to subscribe to and unsubscribe from an observable automatically.

**Comment by Tomassito** [comment]
@pkozlowski-opensource sorry, I don't think I understand how this is solving the issue here. It's been stated that the documentation of HttpClient is not clear regarding the need to unsubscribe. 
Here we have https://stackoverflow.com/a/35043309/6456946 a lot of discussion regarding the topic and it shows how different opinions devs have. Now it would be fair if angular provided their recommendation as to if and why.

**Comment by digeomel** [comment]
@Tomassito @pkozlowski-opensource @ileil I would word it slightly different, explaining why always unsubscribing is important:

You should *always* unsubscribe from observables, even those created by the HttpService, because of edge cases (e.g. slow network) where the built-in unsubscribe mechanism may not kick in when the component is destroyed. When the observable is used in a component, you can use the `AsyncPipe` in the component template to achieve this.

But the line added by @ileil and the clarifications provided here are already an improvement 😄 👍🏼 Maybe we can link to this discussion from the docs?

**Comment by Tomassito** [comment]
Yes, there should be definitely more information on what to expect from the observables exposed by angular services, especially the httpClient. Do docs even mention the fact that an http request auto completes?
