### ISSUE TITLE
Properties binding in Angular 2

### ISSUE THREAD

**Issue by ssougnez** [angular/angular#4655]
Hi,

I'm currently trying to understand the properties binding with Angular 2 and... I'm struggling. 

Here is my component:

```javascript
/// <reference path="typings/tsd.d.ts" />

import { Component, View, bootstrap } from "angular2/angular2";

@Component({
  selector: "my-component",
  properties: ['name']
})
@View({
  templateUrl: "/templates/app.html"
})
class MyComponent
{
  name: string;
}

bootstrap(MyComponent)
```

Here is my view:

```html
<div>{{ name }}</div>
```

And here is my page:

```html
<my-component [name]=" 'Test' "></my-component>
```

When I display my page, I have nothing. If I add some literal before "{{name}}" in my view, the literal gets displayed but not "Test". Moreover, if I initialize "name" in the constructor of my class, it works, it gets displayed... 

What I'm trying to do is just set a property of my component though the HTML. What am I doing wrong ?

FYI: I'm using angular2 alpha-40.

**Comment by gdi2290** [comment]
you might be looking at the outdated docs. Here's a working example for you
http://plnkr.co/edit/MkuZaCfWxMgw4c8DcR5c?p=preview
if this works then you can close the issue

**Comment by ssougnez** [comment]
OK, I see the difference. Actually, I was wondering if it was possible to directly put "<my-component ...>" in the index.html without creating an "app" component ?

**Comment by PascalPrecht** [comment]
@ssougnez No, you always need at least a single root component to bootstrap your application.

**Comment by pkozlowski-opensource** [comment]
Closing this one as hopfully all the questions were clarified. If not let's move this discussion over to https://gitter.im/angular/angular
