### ISSUE TITLE
DevTools for Firefox listing: Add icon, screenshots and mark them as stable?

### ISSUE THREAD

**Issue by rklec** [angular/angular#46588]
### Description

The devtools listing on AMO needs some love IMHO: https://addons.mozilla.org/firefox/addon/angular-devtools/

In contrary [to the same Chrome/ium listing](https://chrome.google.com/webstore/detail/angular-devtools/ienfalfjdbdpebioblfackkekamfmbnh), it...
* is marked as experimental, which de-lists it a lot (IMHO not needed, the Chrome/ium version also seems stable and it is > v1.0.0)
* has no icon (please just add one, it's two clicks)
* has no screenshots 
* has an older, shorter description
* has less users, which could be a result from the stuff before (especially marking
* the Chromeium/Chrome version is even featured, which has an equivalent on AMO and which [you could thus also become in the Firefox extension store](https://extensionworkshop.com/documentation/publish/recommended-extensions/).

### Proposed solution

Add the mentioned stuff.

Generally have a look at this guide to see how to make such an add-on listing more appealing:
https://extensionworkshop.com/documentation/develop/create-an-appealing-listing/

For both listings, IMHO one thing is also still needed:
* You should IMHO link to https://angular.io/guide/devtools. Such a link is really missing on both sites and would allow users to quickly check out the great videos etc. to see what the extension can actually do.
  (Maybe just add it to the description.)

### Alternatives considered

Leave it as it is?
* The Firefox version seems to be as up-to-date as the Chrome/ium version. The versions seem currently is 1.0.6.
* As such, I guess it is also not experimental anymore.

**Comment by mgechev** [comment]
Just marked it as not experimental and updated details. Thanks for pointing this out.
