### ISSUE TITLE
support incremental work on e2e tests

### ISSUE THREAD

**Issue by rkirov** [angular/angular#4659]
After switching to using the bundles for e2e, it is no longer possible to start `gulp serve.js.dev` and work iteratively.

A possible fix is to revert to old per-file loading with system.js when starting `gulp serve.js.dev` and use a different target for Travis.

**Comment by IgorMinar** [comment]
we could change the SCRIPT replacement to check if the current url contains `?debug` and if it does it won't load the bundle. would that work?

it'd rather not create yet another set of build artifacts. single artifact that uses bundle by default, but can load individual files based on a url flag is going to be easier to maintain.

we could make non-bundled version the default, but then we need to change all of the e2e tests and benchmarks

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
