### ISSUE TITLE
Reset Form to Default Values Instead of Null

### ISSUE THREAD

**Issue by Halfist** [angular/angular#46595]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

As per https://github.com/angular/angular/issues/19747 and https://github.com/angular/angular/pull/44434, this seems to be done.

However, `form.reset()` still resets to `null` instead of initial values even in Angular 14.

See https://stackblitz.com/edit/angular-ivy-stvefj.

### Proposed solution

`form.reset()` should reset the form to its default values, passed to `formBuilder.group()`.

```
ngOnInit(): void {
  this.form = this.formBuilder.group({
    firstName: ['John', Validators.required],
    lastName: ['Doe', Validators.required]
  });
}
```

After `form.reset()`, `this.form.get('firstName')?.value` should be `"John"` and `this.form.get('lastName')?.value` should be `"Doe"`. Now they both are `null`.

### Alternatives considered

The best alternative so far is saving form initial state right after its creation, and using it for reset.

```
ngOnInit(): void {
  this.form = this.formBuilder.group({
    firstName: ['John', Validators.required],
    lastName: ['Doe', Validators.required]
  });
  this.formInitialState = this.form.value;
}

resetForm(): void {
  this.form.reset(this.formInitialState);
}
```

**Comment by destus90** [comment]
You should use `nonNullable` API

https://stackblitz.com/edit/angular-ivy-o5abqe?file=src%2Fapp%2Fapp.component.ts

**Comment by Halfist** [comment]
Closing as per @destus90 response.
