### ISSUE TITLE
router: get access to the Router service from within CanActivate hook

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#4661]
I am implementing user authentication in my example app and I was just looking into what would be the best approach to doing it.

And I found that in order to be flexible I should go for:
```js
@CanActivate((route: ComponentInstruction) => {
    // check if user is authenticated
});
```
So that I can require authentication only on specific routes.

But the problem at this point is, how do I do a redirect at this point? At least, how do I navigate to a desired route from the `@CanActivate()` hook?

I thought I could have access to the `Router` class so that I can `router.navigateByUrl()`, but by the looks of it, that is not possible. Thus, this lead me to this post, is it possible to access the `Router` this way and if not could this be a new feature?

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/2965

**Comment by rolandjitsu** [comment]
@ericmartinezr thanks :)
