### ISSUE TITLE
feat(Http, Jsonp) Jsonp Callback 

### ISSUE THREAD

**Issue by LoganArnett** [angular/angular#4663]
### Jsonp Question

May be missing something in the documentation but I am messing around with Alpha39 and some Http and Jsonp. 

I am able to get http calls working just fine but then I attempted a few API's that supported jsonp out of curiosity. I then fell back to my Angular 1.x self and just threw in JSON_CALLBACK into my url to no avail. This just got me thinking if there is a default callback for the jsonp requests or not in Angular 2.

Thanks in advance

**Comment by PascalPrecht** [comment]
Yes, it's called `JSON_CALLBACK` in A2 too ~ https://github.com/angular/angular/blob/master/modules/angular2/src/http/backends/jsonp_backend.ts#L45-L50

**Comment by mhevery** [comment]
thanks @PascalPrecht
