### ISSUE TITLE
npm ERR! 404  '@types/eslint@https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz' is not in this registry.

### ISSUE THREAD

**Issue by mrsants** [angular/angular#46650]
### Which @angular/* package(s) are the source of the bug?

upgrade, Don't known / other

### Is this a regression?

No

### Description

when trying to install new angular i get the following error, i am using nvm and node 16

### Please provide the exception or error you saw

```true
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz - Not found
npm ERR! 404 
npm ERR! 404  '@types/eslint@https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
angular 14.0.0
nvm 0.39.1
node 16.15.1
os Monterey
```

**Comment by jnizet** [comment]
It's an npm registry issue being investigates: https://status.npmjs.org/incidents/6wr25yb0b2dd
See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/61032 for workarounds, or just be patient I guess.

**Comment by jessicajaniuk** [comment]
Closing since it's an issue with npm and not angular. Thanks for reporting and thanks @jnizet for the comment.
