### ISSUE TITLE
Multi data providers do not work correctly on safari 15.5

### ISSUE THREAD

**Issue by KostyaTretyak** [angular/angular#46656]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

I do not know. I am currently using Angular 13.3.8

### Description

On my [website](https://mblog.dev/post/10) Angular calls two data providers like this:

```ts
const routes: Routes = [
  {
    path: '',
    component: PostComponent,
    resolve: {
      result1: ApiPostLeadResolver,
      result2: ApiPostBodyResolver,
    },
  };
```

In Google Chrome this code works correctly and in console you can see this two requests, but in Safari 15.5,  Angular calls only `ApiPostLeadResolver` and incorrectly set the result to `this.activatedRoute.snapshot.data.result2`.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by KostyaTretyak** [comment]
@atscott, what information is missing in this issue?
