### ISSUE TITLE
Docs are on DecoratorFactory classes, but users will navigate to Decorator

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#4668]
For example, in my demo I start with
`import {Component} from 'angular2/angular2';
and then I immediately show how cool it is that I can navigate to definition of that symbol and read the documentation, and how it's guaranteed to be the correct docs for this version (unlike some blog post).

But the documentation says
`{@link ComponentMetadata} factory function.`
so okay, I can click through again to the definition, by observing that it probably lives on the type declared on the following line
`export declare var Component: ComponentFactory;`
and on `ComponentFactory` I find what I want.

But this makes the demo kind of lame, and has an unneeded extra hop for what's likely to be the most common "jump to docs" use case. (Also the Java jokes will commence when users see everything is a "Factory").

Can we still change this, or is there a reason it has to be this way? @mhevery?

- the docs don't appear for properties like 'templateUrl' because that is re-declared separate from the Metadata class
- the {@link} syntax is not navigable in VSCode

**Comment by mhevery** [comment]
You rise a very good point. Do you have specific ideas on how we could make this better?

The issue is that `Component` is not a class. The reason for this is that we want it to be able to be called in three different ways.

1. `new Component()`
2. `Component({}).Class(...)`
3. `@Component()`

So the declaration needs to be

```
var Component: {
  new(args): ComponentMetadata; // for new Component();
  (args): ViewFactory; // for Component({}).View(...)
  (fn: Function): Function; // for @Component
}
```

The issue is that when you click through `Component` you probably want to see `ComponentMetadata.`

Ideas?

**Comment by alexeagle** [comment]
The obvious answer is to place the docs on the declaration of Component. Is it a problem that it's a var?
Does that  break how dgeni presents the docs?

**Comment by alexeagle** [comment]
I'll try this out this morning, if nothing else I think we should duplicate the TS-specific portion of the docs in both places.

**Comment by alexeagle** [comment]
Another problem: the docs don't appear for properties like 'templateUrl'

**Comment by naomiblack** [comment]
@alexeagle is this still coming in for 41?

**Comment by alexeagle** [comment]
There is more to do, but will wait till later release.
