### ISSUE TITLE
Add possibility to use FormArray controls with OnPush components

### ISSUE THREAD

**Issue by Binek115** [angular/angular#46681]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

Right now, it is not possible to use `controls` property with `OnPush` change detection components when we add or remove control in `FormArray` because it modifies the existing array of controls.

### Proposed solution

Add an observable to `FormArray` class that will notify whenever we add or remove control.

### Alternatives considered

Instead of modifying existing controls, create new controls array whenever we add or remove control.

**Comment by destus90** [comment]
Calling `changeDetector.markForCheck()` won't help in such cases?

**Comment by Binek115** [comment]
It probably would, but I am not in favor of calling change detector manually.

**Comment by AndrewKushnir** [comment]
Closing this issue as potentially related to #10887. We'll review which events should be covered as a part of the #10887.
