### ISSUE TITLE
Quickstart requires users to add some typescript compiler options by hand

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#4669]
Our quickstart would be awesome if the installation instructions for angular2 were simply
`npm install angular2`
but we are not quite there, because they will get typescript errors in the editor unless they also run another command
`tsc --init --experimentalDecorators --target es5`.

Not great because:
- We could make a working installation literally with a single command.
- Easy for users to run the wrong typescript version and get error that the flag doesn't exist eg. if they tried an earlier alpha and installed 1.5. We could tell them to run `./node_modules/.bin/tsc` but some will ignore it. (and see https://github.com/Microsoft/TypeScript/issues/5157)
- This feels a bit leaky. Why should users need to know which flags are required?
- This is the first 5 minutes of the first-time user experience, so polishing micro-optimizations are worth considering.
- If we add some other flag in another release, users could easily follow older instructions and miss it.
- If they already have a `tsconfig.json` file, this command will fail, and they need to edit the file instead.

I propose that we add a bit of magic in the `postinstall` script of angular2 that runs the command, after hacking the working directory to be the parent of `node_modules`, and piping errors to hide them. If typescript is not installed (maybe user plans to use ES5/ES6) then the file isn't created. Likewise if it already exists.

Note we would still need to explain what to do if the tsconfig exists but is missing one of our flags.

**Comment by vicb** [comment]
> Note we would still need to explain what to do if the tsconfig exists but is missing one of our flags.

Would it be possible to parse the existing file, check for the required flags / values and display a warning if not configured properly ?

**Comment by alexeagle** [comment]
Yes, we could ask `tsc --init` to do that, but we'd have to wait for next release to be widely available.
Or we could do it ourselves as you say.
What do you think about the bigger question?

**Comment by Gillespie59** [comment]
Totally agree with you. we have to improve the first 5 minutes a newcomer spent on our framework. 

Is also possible/necessary to download type definition files ? 

```
 tsd install angular2 es6-promise rx rx-lite
```

Manu

**Comment by alexeagle** [comment]
no there is no tsd step. typings are now included in the angular2 npm distro.
see https://docs.google.com/document/d/1jiB1SHfM2AXacKdTbQBoPyKlp7ZSH-LBbfc5gzeMKVY/edit# for context.

**Comment by rkirov** [comment]
> I propose that we add a bit of magic in the postinstall script of angular2 that runs the command, after
> hacking the working directory to be the parent of node_modules, and piping errors to hide them.

Too much magic? How about shipping with `recommended_tsconfig.json` in npm and saying `cp node_modules/angular2/recommended_tsconfig.json tsconfig.json`.

**Comment by robwormald** [comment]
alternately npm install -g angular-cli and add this as the simplest first step? `ng init` npm installs angular2 and inits a tsconfig?

**Comment by Gillespie59** [comment]
@alexeagle Thanks !

**Comment by alexeagle** [comment]
Yeah since we'll have a CLI this won't be the primary FTUE at some point, so maybe this is not worth the trouble.
Plus I'm never convinced that hiding everything from programmers is useful in the end, since they are denied the chance to build a good mental model for how things work.

**Comment by alexeagle** [comment]
And another argument against: putting the tsconfig.json at the top-level is probably not how angular-cli will do it, so then if the user re-installs angular2, they get an extra file they shouldn't have.
