### ISSUE TITLE
Dynamic form guide does not use new typed forms

### ISSUE THREAD

**Issue by Cephyric-gh** [angular/angular#46701]
### Description

In a couple of my projects I used the dynamic form guide as a base for setting up a form builder (which has become vastly more complicated nowadays than the original guide) which I use everywhere to handle all forms (all the projects it is used in are form-heavy, so stumbling across the guide a number of years ago was a blessing in disguise!).

With the release of typed forms in angular 14, I returned to the guide in order to get some pre-emptive information on what it'd look like to convert my builder to use the new system. However, it looks like the guide has not yet been updated to use either of the new classes (TypedFormControls or UntypedFormControls).

### What is the affected URL?

https://angular.io/guide/dynamic-form

### Please provide a screenshot if possible

![Screenshot 2022-07-04 at 16 42 45](https://user-images.githubusercontent.com/15064965/177186428-cbd74a2a-1e3a-455f-b423-643caa43dbc9.png)

**Comment by alxhub** [comment]
The example in the guide _does_ compile, so it is (by definition) using one or the other :)

The key seems to be:
```typescript
const group: any = {};
...
return new FormGroup(group);
```

The explicit `any` type for `group` causes the created `FormGroup` to be `FormGroup<any>`, which is `UntypedFormGroup`.

However, we should definitely update the guide to be more explicit about this (and maybe use `FormRecord`?)

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
