### ISSUE TITLE
[HTTPClient] Error reading response of Azure Devops B2C api

### ISSUE THREAD

**Issue by Jordanternullo** [angular/angular#46712]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

Hi,
I report a bug concerning HttpClient following the connection between Angular and the Azure Devops API (B2C).
The return returned by the api is not interpreted in the HttpClient (401 error). We cannot Catch or Subscribe the return. Do you have any information about this?

### Please provide the exception or error you saw

```true
We have nothing in catchError of subscribe and in next of subscribe (error 401)
```

### Anything else?

Angular CLI : 9 and 14
Node 16.15.1
OS : Windows

Angular: 9 and 14
HttpClient in common module 14

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
