### ISSUE TITLE
publish angular@next

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#4671]
We should have an hourly/nightly build available on npm. This would allow people to verify our fixes easily at HEAD without waiting for a release, and give us some quicker feedback from 'dogfood' users.

**Comment by PascalPrecht** [comment]
Yes please!

**Comment by gdi2290** [comment]
:+1: 
sorta related? https://github.com/angular/angular/issues/3476

**Comment by tamascsaba** [comment]
:thumbsup:

**Comment by dsebastien** [comment]
+1

**Comment by Moncef12** [comment]
:+1:

**Comment by IgorMinar** [comment]
Yeah, I was thinking about the same thing this weekend as well!

We have this for Angular 1 and it's awesome.

**Comment by Gillespie59** [comment]
:+1:

**Comment by alexeagle** [comment]
Note, if you have a SHA of any commit, and the build_only run in travis succeeded, you can do this already, eg
`npm install angular/angular#2.0.0-build.16b5217.js`
 is a recent snapshot.

**Comment by laco0416** [comment]
+1
I think releases should be separated on stability. 
We need _Stable_ and _Latest_ labels.

**Comment by IgorMinar** [comment]
all the "next"/"latest" releases are being pushed to github.com/angular/core-builds and other github.com/angular/<packagename>-builds repos from where they can be installed via 

```
npm install angular/<packagename>-builds
```

or 

```
npm install angular/<packagename>-builds#<tagname>
```

where tag names points to sha's of the upstream angular/angular repo.

at the moment we don't see publishing separate `@next` build to npm as well as that would just create a unnecessary churn on npm.

**Comment by petebacondarwin** [comment]
The correct command to get this to work is:

```bash
npm install  --save https://github.com/angular/<packagename>-builds
```
