### ISSUE TITLE
Ivy URL shows page not found

### ISSUE THREAD

**Issue by Arihant416** [angular/angular#46717]
### Description

On updating angular version 11 to 12, the CLI shows a message
> For additional information or if the build fails, please see [Ivy Guide](https://angular.io/guide/ivy)
The URL opens up to show page not found.

### What is the affected URL?

https://angular.io/guide/ivy

### Please provide the steps to reproduce the issue

You can reproduce this issue by pasting the URL on the browser directly or by redirecting from the CLI message.

### Please provide the expected behavior vs the actual behavior you encountered

Expected behavior
* There should have been some documentation about the Ivy compiler 

Actual behavior
* The URL redirects to a Page Not Found page.

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/43008186/177461681-7e4d3240-9928-47ed-ac3e-9df424098645.png)

**Comment by JoostK** [comment]
This happens because the page has since been removed as obsolete in v14+, but older versions of Angular always link to _just_ angular.io instead of a particular version; in this case that would be https://v12.angular.io/docs, which is still available.

We have an issue #44650 to reflect the version of Angular in links to documentation.

As for this specific problem, let's see what @gkalpak's thoughts are here.

**Comment by gkalpak** [comment]
I see that the Ivy-related guides have been removed in #43860.
For those that we use in CLI/compiler error messages, we could create redirects to v12.angular.io, but I am not sure if it was a conscious choice not to do this. Maybe @dgp1130 remembers.

**Comment by dgp1130** [comment]
I think we just never got around to linking errors messages to the current version of Angular. There's a lot of error messages with links like this and they would need to be updated for every major version, which can lead to a lot of churn.

One alternative approach to consider is to leave a "tombstone" in angular.io which tells users "This doc is deleted, but it previously existed in vX - link". Not sure how hard that is to do, but it's one solution to this problem.

I do agree that the ideal solution is for errors messages to link to their versions of the documentation. It's just something which hasn't been prioritized.

**Comment by dgp1130** [comment]
Sounds reasonable to me. I could see some users getting confused about why they're getting redirected to older versions, but it's probably more important to get them to the content they want in the easiest way possible.
