### ISSUE TITLE
Typescript utility type "Record" not working on FormGroup

### ISSUE THREAD

**Issue by xXNickznXx** [angular/angular#46721]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

Typescript utility type "Record" not working on FormGroup

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/typescript-record-not-working-on-formgroup

### Please provide the exception or error you saw

```true
Conversion of type 'AbstractControl<never, never>' to type 'FormGroup<any>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
Type 'AbstractControl<never, never>' is missing the following properties from type 'FormGroup<any>': controls, registerControl, addControl, removeControl, and 2 more.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.4
Node: 16.15.0
Package Manager: npm 8.11.0
OS: win32 x64

Angular: 14.0.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.4
@angular-devkit/build-angular   14.0.4
@angular-devkit/core            14.0.4
@angular-devkit/schematics      14.0.4
@schematics/angular             14.0.4
rxjs                            7.5.5
typescript                      4.7.4
```

### Anything else?

In the example project is also a working example with the type which would generate out of the utility type.

**Comment by criskrzysiu** [comment]
It is not `Record` that is the problem but using `enum` in `Record` as a key. It will work if instead You will use `export type NumberEnum = 'one' | 'two' | 'three';`

**Comment by xXNickznXx** [comment]
Its confusing that the generated type of Record looks correct but in reality its not. Good to know for the future and thanks for your help @criskrzysiu
