### ISSUE TITLE
How to convert Angular Application from MonoRepo to PolyRepo ?

### ISSUE THREAD

**Issue by GuruNadh552** [angular/angular#46734]
### Which @angular/* package(s) are the source of the bug?

compiler, elements

### Is this a regression?

No

### Description

I have created three angular applications separately that have an `individual workspace` or `individual projects` and `individual repositories`.

I can share the modules among them by using the `@angular-architects/module-federation`. But I am unable to share the components and services.

How can I share the services and components among different workspaces or projects ?

Or 

How can I implement Poly Repo based Angular Application?

Thank You.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
