### ISSUE TITLE
How To Implement Micro-Frontends with Poly Repo Architecture ( instead of Mono Repo) ?

### ISSUE THREAD

**Issue by GuruNadh552** [angular/angular#46735]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

There are some `n applications`. They are not in the same workspace.
We have made each application into an `individual MFE`.

**How can we share the `data` among them if they follow Poly Repo Architecture?**

or

**How can we create a poly repo-based angular application?**

Kindly help me with this.

Thank you.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
