### ISSUE TITLE
[Feature request] Element level "bind only on event" behavior

### ISSUE THREAD

**Issue by djvs** [angular/angular#4674]
Apologies in advance if there is already an issue regarding this...or if it's not even applicable...or already implemented.

What I am proposing is that there be some method to basically abstract an arbitrary portion of the DOM into a sort of enclosure where the apply/digest cycles (or analogues) will not touch the parts inside of it unless the element itself is marked as requiring an update.  The idea behind this is to help performance inside e.g. an ng-repeat, in which dozens or even thousands of objects are iterated over.  If the application can predict when a given object is going to change, it can then mark that model as needing a change, necessitating the inspection of only a single attribute instead of all of the attributes of the object that are bound in that element.  As far as I know (not far) this is how React etc. work?  Anyway there are several directives which already sort of implement this behavior, notably "bindonce", but I notice they are a bit buggy and poorly supported - I suspect this is a common enough use case, and vital enough to performance, to be included in the core of Angular.

**Comment by mhevery** [comment]
Already supported: http://victorsavkin.com/post/110170125256/change-detection-in-angular-2

**Comment by djvs** [comment]
Just to be clear (I read that article and posted this right after) - there is a way described therein, where you can mark a Component only to update on a specific property being triggered, or event being received, etc., without having to watch its individual properties?
