### ISSUE TITLE
Libs published with Angular 14 cannot be used with previous versions in apps (unlike before)

### ISSUE THREAD

**Issue by santam85** [angular/angular#46748]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

In a library I am maintaining, I declare a peerDependency for Angular libs with a range of `>=`, to avoid having to republish often ( it's using only very stable APIs from Angular that hardly change).

This worked well for me in the past, but when publishing the lib with Angular 14, users of the library that were still on Angular 13 started to receive the following error when building:

```
./node_modules/ng2-charts/fesm2015/ng2-charts.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string '/Users/marco/workspace/ng2-charts-bar-template/node_modules/ng2-charts/fesm2015/ng2-charts.mjs: This application depends upon a library published using Angular version 14.0.3, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
  143 | }
  144 | BaseChartDirective.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "14.0.3", ngImport: i0, type: BaseChartDirective, deps: [{ token: i0.ElementRef }, { token: i0.NgZone }, { token: ThemeService }], target: i0.ɵɵFactoryTarget.Directive });
> 145 | BaseChartDirective.ɵdir = i0.ɵɵngDeclareDirective({ minVersion: "14.0.0", version: "14.0.3", type: BaseChartDirective, selector: "canvas[baseChart]", inputs: { type: "type", legend: "legend", data: "data", options: "options", plugins: "plugins", labels: "labels", datasets: "datasets" }, outputs: { chartClick: "chartClick", chartHover: "chartHover" }, exportAs: ["base-chart"], usesOnChanges: true, ngImport: i0 });
```

This is unexpected for me, as the only direct/peer dependency of the app shoul allow using it with older versions, and it's not clear to me which API was changed to make v14 of Angular needed for this library (nothing seems to have changed in the signature of the directive). As an Angular library developer I came to have the expectation that I would be able to support multiple major versions of Angular in apps that consume my library. This is not the case anymore.

How is the `minVersion: "14.0.0"` metadata generated? Do we have any control as developers on which value should be used? Can we get a warning when this happens to be different from the peerDependencies declared? Is mine an unreasonable expectation?

### Please provide a link to a minimal reproduction of the bug

https://github.com/santam85/ng2-charts-bar-template/tree/ng-13

### Please provide the exception or error you saw

```true
ypeError: Cannot create property 'message' on string '/Users/marco/workspace/ng2-charts-bar-template/node_modules/ng2-charts/fesm2015/ng2-charts.mjs: This application depends upon a library published using Angular version 14.0.3, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.8
Node: 16.13.0
Package Manager: npm 8.5.4
OS: darwin x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.8
@angular-devkit/build-angular   13.3.8
@angular-devkit/core            13.3.8
@angular-devkit/schematics      13.3.8
@angular/cli                    13.3.8
@schematics/angular             13.3.8
rxjs                            6.6.7
typescript                      4.6.4
```

**Comment by pkozlowski-opensource** [comment]
This is absolutely expected. We do guarantee that libs compiled with an older Angular version can be used in a never Angular version (ex. library compiled with v13 can be used in v14) but not other way around. We can't  guarantee forward-compatibility since it would block us from making any changes in the compiler output (and would pretty much null and void many benefits of having a compiler that can evolve over time).
