### ISSUE TITLE
Language Service: This component requires inline template type-checking, which is not supported by the current environment.(-998900)

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#46747]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, language-service

### Is this a regression?

Yes

### Description

After upgrading to angular 14.0.2 and higher some of components displays following error

`This component requires inline template type-checking, which is not supported by the current environment.(-998900)`

And in these component html templates no intellisense is working.

Reproduction steps:
- `git clone https://github.com/kukjevov/ng-universal-demo demo`
- `cd demo`
- `npm install`
- `code .`
- open `home.component.html` or `home.component.ts` and you can see error 

### Please provide a link to a minimal reproduction of the bug

https://github.com/kukjevov/ng-universal-demo

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 14.0.5
NodeJs: 16.15.0
Npm: 6.14.13
OS: Windows 10.0.19044 Build 19044
```

**Comment by kukjevov** [comment]
**Additional Info**

Output of Angular Language Server
```
[Info  - 11:43:25] Angular language server process ID: 27960
[Info  - 11:43:25] Using typescript/lib/tsserverlibrary v4.7.2 from d:\git\universal-demo\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 11:43:25] Using @angular/language-service v14.0.0 from c:\Users\marek.bukovsky\.vscode\extensions\angular.ng-template-14.0.1\node_modules\@angular\language-service\index.js
[Info  - 11:43:25] Log file: c:\Users\marek.bukovsky\AppData\Roaming\Code\logs\20220708T114134\exthost1\Angular.ng-template\nglangsvc.log
[Error - 11:43:30] No config file for d:/git/universal-demo/app/pages/+default/home/home.component.html
[Info  - 11:43:31] Enabling Ivy language service for d:/git/universal-demo/tsconfig.json.
```

**Comment by alxhub** [comment]
Hi @kukjevov,

The reproduction you provided is pretty big - I suspect there's a _lot_ of code in here that's not necessary for reproducing the bug. Can you narrow it down at all?

**Comment by kukjevov** [comment]
- `git clone https://github.com/kukjevov/ng-universal-demo demo`
- `cd demo`
- `git checkout bug/1.0`
- `git pull`
- `npm install`
- `code .`
- open `home.component.html` or `home.component.ts` and you can see error

**Comment by kukjevov** [comment]
Hi @alxhub,

I have created new branch (i have changed guide in previous comment) it contains only app component and component with problem and i have also found out, that is caused by `NgSelectModule` (its @anglr/select), but interesting thing is that this was working in all versions until `14.0.2`, so there were some changes that caused this.

Thanks for any help.

**Comment by JoostK** [comment]
This is introduced by #46096, which fixed a bug that could result in compiler crashes for certain pipes. However, there is a pre-existing bug in _which_ pipes are considered in this check; the compiler incorrectly looks at _all_ pipes in the compilation scope of the NgModule, whereas it should only consider the _used pipes_ in the template.
