### ISSUE TITLE
Renderer2 click listener called when clicked on scrollbar

### ISSUE THREAD

**Issue by sameerthekhans** [angular/angular#46746]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

**Renderer2 click listener** invoked the callback even when click on scrollbar of the target element, which is not the case for native JavaScript `addEventListener` or `(click)`

To reproduce
Step 1: Visit given stackblitz link
Step 2: Open console
Step 3: Click anywhere on the dialog and then scrollbar
Step 4: See the printed console for differences

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-vp9c9d?file=src/app/app.component.ts

### Please provide the exception or error you saw

```true
No Exception or Error
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.0
Node: 16.14.2
Package Manager: npm 7.17.0 
OS: linux x64

Angular: 14.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/build-angular   14.0.0
@angular-devkit/core            14.0.0
@angular-devkit/schematics      14.0.0
@angular/cli                    14.0.0
@schematics/angular             14.0.0
rxjs                            7.5.5
typescript                      4.7.2
```

### Anything else?

I am using primeng's dialog modal with scroll enabled for dialog's mask, and when user clicks outside of the dialog, the dialog closes even when user clicks on scrollbar

**Comment by JoostK** [comment]
I am confused by the StackBlitz; the listener that is registered using `Renderer2` uses a `mousedown` event, whereas the listener registered using native DOM APIs uses `click`. I get the same behavior between both registrations if they are changed to be the same event: `mousedown` does trigger within the scrollbar, `click` does not.

**Comment by sameerthekhans** [comment]
My bad, I didn't pay attention to primeng's code, I directly pasted and started to test, I better raise a bug in their repository to change the event from `mousedown` to `click`, I think they used `mousedown` to support for touch devices.

Closing this bug, thanks @JoostK
