### ISSUE TITLE
When using pwa and settings value of: '"orientation": "landscape", the pwa app ignores hard setting

### ISSUE THREAD

**Issue by born2net** [angular/angular#46767]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Running PWA with latest Angular 14, setting the app to orientation mode is ignored and you are still able to use the app in both landscape and portrait, depending on device mode.

no way to hard code and force app to always be in one mode.

```
{
  "name": "SignStudio",
  "short_name": "SignStudio",
  "theme_color": "#434342",
  "background_color": "#000000",
  "display": "standalone",
  "orientation": "landscape",
  "scope": "https://galaxy.americas.me/signstudio/",
  "start_url": "signstudio/",
```

### Please provide a link to a minimal reproduction of the bug

latest Angular 14 and latest Android OS

### Please provide the exception or error you saw

```true
no error
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Android
Angular 14
PWA App with latest CLI
```

### Anything else?

nothing else.

**Comment by gkalpak** [comment]
Thx for filing an issue, @born2net. However, this is not something that Angular controls (or affects). It is the OS/browser that applies (or not) these settings.

Closing since this is not something we can fix on our side.
