### ISSUE TITLE
5 Min Quickstart does not work with v2.0.0-alpha.37

### ISSUE THREAD

**Issue by KillerCodeMonkey** [angular/angular#4676]
Hey guys,

i tried your quickstart and it worked with the used 2.0.0-alpha.28, but if you try to include a newer version (>alpha 36) it failed with:
`GET https://registry.jspm.io/app.js 404 (Not Found)`
and
`Potentially unhandled rejection [3] Error loading "app" at https://registry.jspm.io/app.js
Not Found: https://registry.jspm.io/app.js (WARNING: non-Error used)`

It seems that the app.js is not found locally and the module loader searchs in the module registry and failed. After that angularjs 2 is not able to resolve my-app component.

**Comment by doukasd** [comment]
I believe I had the same issue and it was fixed by loading the system.js before some other scripts. But I can't remember the details.

Until the documentation is updated you can get your app to work by re-arranging it like this: http://plnkr.co/edit/iRUP8B5OUbxCWQ3AcIDm?p=preview

**Comment by KillerCodeMonkey** [comment]
this is strange because if you follow the guide it results in something like that:
```
<html>
  <head>
    <title>Angular 2 Quickstart</title>
    <script src="https://github.jspm.io/jmcriffey/bower-traceur-runtime@0.0.91/traceur-runtime.js"></script>
    <script src="https://jspm.io/system@0.16.js"></script>
    <script src="https://code.angularjs.org/2.0.0-alpha.37/angular2.dev.js"></script>
  </head>
  <body>
    <!-- The app component created in app.ts -->
    <my-app></my-app>
    <script>System.import('app');</script>
  </body>
</html>
```

so system is loaded before angularjs. I do not how typescript internally loads the app.js (???).

**Comment by ericmartinezr** [comment]
@KillerCodeMonkey in alpha37 they moved to system v0.18.x. But I would recommend you to upgrade to a40, so you can remove traceur as well.

**Comment by KillerCodeMonkey** [comment]
@ericcarraway 
thanks for your respond. i have played around with the versions before, but did not know, that they upgraded system with alpha 37.

Do i have to change something else in my source code above?
After upgrading and removing of traceur system can not find my app.js.

Do i need to load my app.js manually in the index.html?

Thanks in advance!

**Comment by ericmartinezr** [comment]
@KillerCodeMonkey you can follow this template http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

Two things about that template (it's the official one btw) :

- It's using a39, but you can safely move to a40
- It includes traceur, but just to avoid recent plnkrs to break. You can safely remove it as well.

Note that there's a config file, that's the pilar thing, it will make everything work as expected. 

See this plnkr http://plnkr.co/edit/agkHAL?p=preview, I took your config, I removed traceur, updated system and ng2 versions, added the config file from the official template and it works :D!

**Comment by pkozlowski-opensource** [comment]
@ericmartinezr @doukasd thnx for helping out with the issues!

@KillerCodeMonkey hopefully with the plunks provided by @ericmartinezr you will be able to figure out the setup. If you need a simple server-side compilation alternative you might want to look at: https://github.com/pkozlowski-opensource/ng2-play

We are currently doing massive overhaul of the entire documentation, including quick start and other guides. Those updates should be live shortly and will have setup covered in great details.

**Comment by KillerCodeMonkey** [comment]
@ericmartinezr 
it works in the plunker but not on my local system... but thanks for your help ( @ericmartinezr @doukasd )
i will play around a little bit

**Comment by ericmartinezr** [comment]
@KillerCodeMonkey probably it's a typescript thing. In your local machine it differs a little bit. You have to transpile it manually (with `tsc` command). plnkr seems to do that automagically. Follow @pkozlowski-opensource repo, see that his [index.html](https://github.com/pkozlowski-opensource/ng2-play/blob/master/index.html) file is almost identical to plnkr's, but he also has a [step to convert .ts to .js](https://github.com/pkozlowski-opensource/ng2-play/blob/master/gulpfile.js#L13). I think you might be missing that.

**Comment by KillerCodeMonkey** [comment]
i have a generated app.js
```var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") return Reflect.decorate(decorators, target, key, desc);
    switch (arguments.length) {
        case 2: return decorators.reduceRight(function(o, d) { return (d && d(o)) || o; }, target);
        case 3: return decorators.reduceRight(function(o, d) { return (d && d(target, key)), void 0; }, void 0);
        case 4: return decorators.reduceRight(function(o, d) { return (d && d(target, key, o)) || o; }, desc);
    }
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var angular2_1 = require('angular2/angular2');
var Hello = (function () {
    function Hello() {
    }
    Hello = __decorate([
        angular2_1.Component({
            selector: 'hello'
        }),
        angular2_1.View({
            template: 'Hello world!'
        }), 
        __metadata('design:paramtypes', [])
    ], Hello);
    return Hello;
})();
exports.Hello = Hello;
angular2_1.bootstrap(Hello);```

But it does not load automatically (not in the network section of chrome developer console)

**Comment by ericmartinezr** [comment]
@KillerCodeMonkey can you ask in [gitter's channel](https://gitter.im/angular/angular)? Provide a plnkr,  repo, or at least a pastebin to see how your set up looks like.

**Comment by KillerCodeMonkey** [comment]
@ericmartinezr 
i found it out --> if i put my ts and compiled ts files in a subfolder everything works.

If i lay them directly in the root dir it does not work without any error (maybe system can  not find the app.js).

But i changed the config.js to and set the app-dir to './' ...
However thanks for your help.

**Comment by shatakshidixit1** [comment]
@KillerCodeMonkey  same problem with me .all errors have gone but there is no output at all.
Can you Please help me

**Comment by KillerCodeMonkey** [comment]
You need to put your app.ts in a subfolder of your project dir (e.g. ./src)
