### ISSUE TITLE
Route Animations are not working when using named router-outlets

### ISSUE THREAD

**Issue by JustDoItSascha** [angular/angular#46765]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

No

### Description

When using the route animation exactly like provided in the docs, everything is working fine. But if you use the exact same thing, but a named router-outlet like `<router-outlet name="outlet"></router-outlet>` (and change the routes accordingly), then the animation is not triggered anymore...

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 14.0.5
```

**Comment by atscott** [comment]
Are you talking about this documentation? https://angular.io/guide/route-animations
If your outlet isn’t the primary outlet then you have to do `this.contexts.getContext('outlet') `… instead. 

If this isn’t what you mean, please provide additional information along with a reproduction

**Comment by JustDoItSascha** [comment]
I think you are right, my problem is something else:

I'm using a named router-outlet inside a dynamically created modal. I create the modal like this:

```
open<T>(content: new (...args: any) => T) {
        const contentContainerComponentFactory = this.componentFactoryResolver.resolveComponentFactory(ModalContentContainerComponent);
        const contentContainerComponent = contentContainerComponentFactory.create(this.injector);
        this.appRef.attachView(contentContainerComponent.hostView);

        const contentRef = contentContainerComponent.instance.contentRef.createComponent<T>(content as any);

        this.renderer.appendChild(this.document.body, contentContainerComponent.location.nativeElement);
}
```

Now I have the problem that `:enter` gets triggered on the first load of the modal and everything is fine. BUT when I route inside the named router-outlet then `:enter` and `:leave` are not selecting the routed components anymore. They are selecting child components inside the routed components.

Take for example I have Component A and B and this routing configuration:

```
[
    {
        path: 'a',
        component: A,
        outlet: 'named',
        data: {
            position: 1,
        }
    },
    {
        path: 'b',
        component: B,
        outlet: 'named',
        data: {
            position: 2,
        }
    },
]
```

And I have this animation:

```
trigger('routeAnimations', [
            transition(
                ':increment',
                [
                    style({ position: 'relative' }),
                    query(':enter, :leave', [
                        style({
                            position: 'absolute',
                            top: 0,
                            left: 0,
                            width: '100%',
                        })
                    ], {optional: true}),
                    query(':enter', [
                        style({ left: '100%' })
                    ], {optional: true}),
                    query(':leave', animateChild(), {optional: true}),
                    group([
                        query(':leave', [
                            animate('3000ms ease-out', style({ left: '-100%' }))
                        ], {optional: true}),
                        query(':enter', [
                            animate('3000ms ease-out', style({ left: '0%' }))
                        ], {optional: true}),
                        query('@*', animateChild(), {optional: true})
                    ]),
            ]),
        ])
```

Everything is fine when I add the named router-outlet to the AppRoot. But inside the given modal the `:enter` does not select component A or B, BUT for example when I have an `*ngIf` INSIDE component A, this node gets selected. But only the second route. The very first time when opening the modal everything is correct...

**Comment by atscott** [comment]
@JustDoItSascha At this point, this report doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by JustDoItSascha** [comment]
@atscott I don't think that this is a support request, because I have different behavior whether i add the exact same animation in a "normal" component or in a dynamically created one. This sounds like a bug for me...
