### ISSUE TITLE
when http request why mat-select multiple selected the form value will be reset?

### ISSUE THREAD

**Issue by biaogebusy** [angular/angular#46763]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

my template use OnPush, when i subscribe the valueChange the http request, the form value will be reset. the form was dynamic build form:
`case 'select':
          if (item.multiple) {
            const value = item?.value?.split('+') || '';
            group[item.key] = item.params?.required
              ? new FormControl(value, Validators.required)
              : new FormControl(value);
          } else {
            group[item.key] = item.params?.required
              ? new FormControl(item.value || '', Validators.required)
              : new FormControl(item.value || '');
          }
          break;`

 ` <mat-select panelClass="custom-select" *ngIf="content.multiple && content.search" [formControlName]="content.key"
    multiple disableRipple #select>
    <mat-option *ngIf="content?.none">{{content.none?.label || '无'}}</mat-option>
    <mat-option *ngFor="let option of filteredOptions | async" [value]="option.value">{{option.label}}
    </mat-option>
  </mat-select>`
 
if remove multiple it working, why?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 11.0.1
Node: 14.15.1
OS: darwin x64

Angular: 11.0.1
... cli, common, core
Ivy Workspace: Yes

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1100.7
@angular-devkit/build-angular       0.1100.7
@angular-devkit/core                11.0.7
@angular-devkit/schematics          11.0.1
@angular/animations                 11.2.14
@angular/cdk                        11.2.13
@angular/compiler                   11.0.9
@angular/compiler-cli               11.0.9
@angular/flex-layout                11.0.0-beta.33
@angular/forms                      11.0.9
@angular/material                   11.2.13
@angular/platform-browser           11.0.9
@angular/platform-browser-dynamic   11.0.9
@angular/platform-server            11.1.1
@angular/router                     11.0.9
@nguniversal/builders               11.2.1
@nguniversal/express-engine         11.2.1
@schematics/angular                 11.0.1
@schematics/update                  0.1100.1
rxjs                                6.6.7
typescript                          4.0.8
webpack                             4.46.0
```

**Comment by AndrewKushnir** [comment]
@biaogebusy could you please provide a repro using [Stackblitz](https://stackblitz.com/), so that we can take a look?

**Comment by alxhub** [comment]
Closing as no reproduction was provided.
