### ISSUE TITLE
Error building project using artifacts created from angular source code build

### ISSUE THREAD

**Issue by phalgunv** [angular/angular#46771]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

In order to inestigate https://github.com/angular/angular/issues/13993, first I build angular-cli from source, then installed the tar balls and created a new angular project with it. This was done so that a new angular project is created with the correct dependencies.

Then I followed instructions at thttps://github.com/angular/angular/blob/main/docs/DEVELOPER.md
to copy angular build artifacts over to the newly created project using `yarn link`. Running "npm start" results in the above error. 

I manually updated the javascript bundle where the issue was found and replaced ExternalExpr as suggested in the error message below. When I ran `npm start` again, I did not get error for `ExternalExpr` but similar error for another named export. Is there anything I am missing?

### Please provide the exception or error you saw

```true
An unhandled exception occurred: Named export 'ExternalExpr' not found. The requested module '@angular/compiler' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@angular/compiler';
const { ExternalExpr, ExternalReference, WrappedNodeExpr } = pkg;
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.1.0-next.0
node: v14.17.0
```

**Comment by phalgunv** [comment]
I have pulled the latest commits from angular repo into my forked repo. The command to build the source code has been updated after I posted raised this issue. The new command is `yarn build`, introduced as part of [Commit detail](https://github.com/angular/angular/commit/d248d83c17150d045d10aca424d711ba032d6319#diff-b5cb61e9179386b5d931cdc81286b4bc9a7bf839bee23315b46ae433bfb1998e) fails with the error:

`
PS C:\code\angular> yarn build
yarn run v1.22.17
error Command "build" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

I see in package.json, scripts->build target is missing. Do I need to raise separate issue for this?

**Comment by JoostK** [comment]
The `build` script does exist:

https://github.com/angular/angular/blob/e58207e444af7347699ff9f01492f886cd09da06/package.json#L28

**Comment by phalgunv** [comment]
My bad.

**Comment by phalgunv** [comment]
When I ran "git pull", it incorrectly showed that my local repository was up to date whereas it was stuck at the commit https://github.com/angular/angular/tree/f94c6f433dba3924b79f137cfcc49d2dfd4d679c from 17-June. Since the "build" was added later "yarn build" was failing as it could not find build. 

I have cloned the repo again, ran `yarn install` and  then `yarn build` fails with the below error when run via Window PowerShell 7.2.5 :
`yarn run v1.22.17
$ ts-node --esm --project scripts/tsconfig.json scripts/build/build-packages-dist.mts`
######################################
  Building release packages...
######################################
`Starting local Bazel server and connecting to it...
Loading: 284 packages loaded
//packages/animations:npm_package  
//packages/bazel:npm_package       
//packages/common:npm_package      
//packages/compiler:npm_package    
//packages/compiler-cli:npm_package
//packages/core:npm_package        
//packages/elements:npm_package
//packages/forms:npm_package
//packages/language-service:npm_package
//packages/localize:npm_package
//packages/platform-browser:npm_package
//packages/platform-browser-dynamic:npm_package
//packages/platform-server:npm_package
//packages/router:npm_package
//packages/service-worker:npm_package
//packages/upgrade:npm_package
C:/users/pvaddepa/_bazel_pvaddepa/hwug4sdk/execroot/angular/bazel-out/x64_windows-fastbuild/bin
INFO: Analyzed 16 targets (364 packages loaded, 44542 targets configured).
INFO: Found 16 targets...
ERROR: <builtin>: BazelWorkspaceStatusAction stable-status.txt failed: Failed to determine workspace status: Process exited with status 1
C:\code\angular_new\node_modules\ts-node\src\index.ts:843
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: Γ¿» Unable to compile TypeScript:
error TS5083: Cannot read file 'C:\.ng-dev\tsconfig.json'.`

    at createTSError (C:\code\angular_new\node_modules\ts-node\src\index.ts:843:12)
    at reportTSError (C:\code\angular_new\node_modules\ts-node\src\index.ts:847:19)
    at createFromPreloadedConfig (C:\code\angular_new\node_modules\ts-node\src\index.ts:858:36)
    at create (C:\code\angular_new\node_modules\ts-node\src\index.ts:613:10)
    at register (C:\code\angular_new\node_modules\ts-node\src\index.ts:580:15)
    at Object.registerAndCreateEsmHooks (C:\code\angular_new\node_modules\ts-node\src\esm.ts:116:34)
    at file:///C:/code/angular_new/node_modules/ts-node/esm.mjs:8:7
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async internal/process/esm_loader.js:57:9 {
    diagnosticCodes: [ 5083 ]
    }
`ERROR: C:/code/angular_new/packages/common/BUILD.bazel:36:11 Assembling npm package packages/common/npm_package failed: Failed to determine workspace status: Process exited with status 1
INFO: Elapsed time: 22.438s, Critical Path: 4.82s
INFO: 9 processes: 9 internal.
FAILED: Build did NOT complete successfully
Error: Command failed: yarn -s bazel build --config=snapshot-build //packages/animations:npm_package //packages/bazel:npm_package //packages/common:npm_package //packages/compiler:npm_package //packages/compiler-cli:npm_package //packages/core:npm_package //packages/elements:npm_package //packages/forms:npm_package //packages/language-service:npm_package //packages/localize:npm_package //packages/platform-browser:npm_package //packages/platform-browser-dynamic:npm_package //packages/platform-server:npm_package //packages/router:npm_package //packages/service-worker:npm_package //packages/upgrade:npm_package
    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at exec (file:///C:/code/angular_new/scripts/build/package-builder.mts:126:18)
    at buildReleasePackages (file:///C:/code/angular_new/scripts/build/package-builder.mts:80:3)
    at performDefaultSnapshotBuild (file:///C:/code/angular_new/scripts/build/package-builder.mts:45:10)
    at file:///C:/code/angular_new/scripts/build/build-packages-dist.mts:17:1
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 22872,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

When I run in Ubuntu using WSL, `yarn build` works fine.

**Comment by fabioemoutinho** [comment]
@alan-agius4 is this the new way of using `ng serve` if you want to use a local Angular build? `node --preserve-symlinks node_modules/.bin/ng s`. It worked for me.
If so, I'm available to open a PR with that command to update the documentation. I'm just starting to try to contribute so this is a good first contribution for me.

**Comment by alan-agius4** [comment]
@fabioemoutinho correct note that `s` above is an alias for `serve` and can be replaced with any Angular CLI command.

**Comment by fabioemoutinho** [comment]
@alan-agius4 I noticed I had to disable cli cache in angular.json in order to be able to make changes, thus only requiring a ng serve restart. Do you think this is a good addition to the documentation? Any other tips about serving you might share?

**Comment by alan-agius4** [comment]
Yeah, you can mention that you need to run `ng cache disable`.

**Comment by bob-watson** [comment]
It looks like the docs part of this has been resolved.
If so, can we remove the `comp: docs` label?

**Comment by alan-agius4** [comment]
This can actually be closed now since this was only a docs related change.
