### ISSUE TITLE
Type AgGridModule does not have 'ɵmod' property

### ISSUE THREAD

**Issue by kunal00731** [angular/angular#46776]
I am currently upgrading my application from Angular 12 to Angular 13. I am using `ag-grid 15.0.0` and `ag-grid-angular 15.0.0`. Now my compilation happens properly as far as the app is concerned . However , when the app tries to load in browser , I see this issue coming up : `Type AgGridModule does not have 'ɵmod' property` .

![image](https://user-images.githubusercontent.com/5189286/178337012-aa3dc8e7-9c1d-4ddf-85a1-4d22a7643d84.png)

Can anyone let me know as to what is wrong here ?

**Comment by JoostK** [comment]
`ag-grid-angular` 15.0.0 was published 5 years ago; with the latest version being 28.0.0. I'd recommend that you update ag-grid and ag-grid to recent releases, as the version you're using appears to be no longer compatible with Angular 13.
