### ISSUE TITLE
We don't get NG0300 if ngDevMode is not set

### ISSUE THREAD

**Issue by lukasmatta** [angular/angular#46772]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Hello,
not sure if this is an issue or not, but from my point of view it can cause unexpected behaviour on production:

**What I expected and what happened**
When we have multiple components with same selector, I expected build to fail with an error [NG0300](https://angular.io/errors/NG0300). It happens, but only if `ngDevMode` is set. With production build, no error is thrown and it renders first defined component *N* times (*N* is the number of components with the same selector).

**How could this cause a problem**
If someone adds a component with the selector that is already present in the app, he will not be warned about it (if he doesn't build it with `ngDevMode` set, which is not necessary). Before Ivy, user was notified about this error in the editor, as checking for this was [part of template parsing.](https://github.com/angular/angular/blob/b2a081a19d6d006023b0f79076e9e499441a7810/packages/compiler/src/template_parser/template_parser.ts#L676)

I think it was introduced with this PR:
https://github.com/angular/angular/pull/38612/files

I have provided git repro repo, as I was not able to reproduce this inside stackblitz.

--- 

Also what is interesting fact and possibly another issue (please let me know if I should open it): If we build with `optimized.scripts` set to true, `ngDevMode` is removed with terser -https://github.com/angular/angular/blob/3a60063a54d850c50ce962a8a39ce01cfee71398/packages/compiler-cli/private/tooling.ts#L26. Not sure if this is an issue, but I can imagine someone running `ng serve` with optimized scripts would be surprised. Try running `ng serve --configuration=optimizedScripts` in the repro repo, `ngDevMode` will be falsy and NG0300 not thrown.

### Please provide a link to a minimal reproduction of the bug

https://github.com/lukasmatta/angular-issue-46772

**Comment by atscott** [comment]
This is working as intended. There are many checks that are dev mode only checks. Keeping these assertions around for production would increase the production bundle sizes.
