### ISSUE TITLE
Alpha 40 @Query 

### ISSUE THREAD

**Issue by TiagoBraga39** [angular/angular#4678]
Hi all!

I guess @Query lifecycle should be changed.

Now (on alpha 40), I can't get the QueryList neither on constructor nor onInit methods...
Check the console on this plunkr: http://plnkr.co/edit/ADhcM0Muq5tX5HGOSKW2?p=preview

Stay awesome,
Tiago Braga

**Comment by TiagoBraga39** [comment]
Also:
```javascript
 this.items.changes.next(() => { console.log("has changes"); } );
```
Never triggers.

**Comment by TiagoBraga39** [comment]
Goddamit!

My mind only remembers the important stuff late :)

Using afterContentInit()

**Comment by ericmartinezr** [comment]
@TiagoBraga39 in gitter's room I told you `@Query` was replaced (which is not, it's still there, sorry for that). Regarding `this.items.changes.next` you have to subscribe to it, with `next` you are emitting, but you have no subscribers, so just change it to `this.items.changes.toRx().subscribe()`. QueryList already emits for you, you just have to subscribe to it.
