### ISSUE TITLE
loadTranslations() not working with static variables

### ISSUE THREAD

**Issue by TheSlimvReal** [angular/angular#46783]
### Which @angular/* package(s) are the source of the bug?

localize

### Is this a regression?

No

### Description

When using the `loadTranslations()` function as described in #38953, static variables or exported variables outside of classes are not translated. Class variables are translated correctly.

This minimal reproduction below shows 3 variables: 

- A class variable that is correctly translated
- A static and a exported variable that are not translated

To try it out just select a different language in the dropdown.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-zbtl9s?file=src/app/app.component.html

### Please provide the environment you discovered this bug in (run `ng version`)

Angular 14

### Anything else?

Interestingly, when the component is updated through the _hot reload_ the translations for the static and exported variable are suddenly working.

To see this just add something to the template in the `app.component.html` file and wait for the hot reload to render the changes.

**Comment by JoostK** [comment]
Thanks for the great repro!

This seems to be working as expected; top-level variables (static members and top-level exports) are initialized when the ES module is loaded. In your setup, the `loadTranslations` call only occurs _after_ having loaded all ES modules so they have already been initialized as if there are no translations.

You can get it to work if you push all ES modules behind a dynamic import boundary, to only initialize the ES modules once translations have been loaded: https://stackblitz.com/edit/angular-ivy-f8jtqd?file=src%2Fbootstrap.ts,src%2Fmain.ts

Compile-time inlining of `$localize` does not have this limitation, as there won't be any timing sensitivity as to when translations are loaded. There is already a note in the docblock of `$localize` that warns about this timing hazard:

> Note that `$localize` messages are only processed once, when the tagged string is first
encountered, and does not provide dynamic language changing without refreshing the browser.
Loading new translations later in the application life-cycle will not change the translated text
of messages that have already been translated.

**Comment by TheSlimvReal** [comment]
@JoostK Thank you some much for the explanation and the very clean workaround/solution to this problem. I just put it into my project and it works like a charm!

Generally, there were quite some difficulties getting the runtime translations through the `loadTranslations()` function running:

- How/when to load the translations
- `registerLocaleData()` with lazy loaded import
- initializing the locale
- maybe also parse `xliff` to `json` (at runtime or compile time)
- finally, what you just shared with me to get ES modules translated

Would you/the Angular project be interested in a extension of the `loadTranslations()` documentation where a simple/minimal setup is provided for getting all of this going? I think a lot of people would be very interested (see #38953).
I would be more than happy to provide that!
