### ISSUE TITLE
TypeScript 4.7.4: strict / full template type checks slow down exponentially with complex ngIf expressions

### ISSUE THREAD

**Issue by imirkin** [angular/angular#46792]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

With TS 4.7.4, it seems like there's a huge slowdown in type checking. Some stats on the repro project "ng build" timing on a moderately powerful desktop:

strict + fullTemplateTypeCheck: 86s
strict: 60s
no strict: 7s

TS 4.6.4 + strict + fullTemplateTypeCheck: 10s

The repro is a pretty simple project. On a much larger project, I think I had let it run for like 10-20 min before giving up, whereas it normally completes in a minute or two.

You can reduce that ngIf to just a handful of values, and you'll see that it builds MUCH faster.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-n2azyw?file=src/app/app.component.html

### Please provide the exception or error you saw

No error, just _very_ slow. Note that I left the stackblitz repro with strict *disabled*, so you'll have to flip it on in tsconfig.json to experience the slowness. The in-browser stuff doesn't work very well when the compilation is super-slow like that.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.0.5
Node: 14.19.3
Package Manager: npm 6.14.17 
OS: linux x64

Angular: 14.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.5
@angular-devkit/build-angular   14.0.5
@angular-devkit/core            14.0.5
@angular-devkit/schematics      14.0.5
@schematics/angular             14.0.5
rxjs                            7.5.6
typescript                      4.7.4
```

### Anything else?

I filed an earlier bug that was closed due to lack of repro, which may have had some relevant info here:

https://github.com/angular/angular/issues/46790

TypeScript bug I had filed initially since stack traces were leading into TS-land:

https://github.com/microsoft/TypeScript/issues/49845

**Comment by JoostK** [comment]
This is definitely a TypeScript 4.7 regression; compiling with Angular 14 and TypeScript 4.6 works without issues.

Here's a minimum, TypeScript only repo:

```ts
declare const arr: string[];
  
(((((((((((((((((!arr.length) && !arr.length) && !arr.length) && !arr.length) && !arr.length) && !arr.length) && !arr.length) && !arr.length) && !arr.length) && !arr.length) && !arr.length) && !arr.length) && !arr.length) && !arr.length) && !arr.length) && !arr.length) && !arr.length);
```

```
 ./node_modules/.bin/tsc index.ts --strict --noEmit --extendedDiagnostics    
Files:                         101
Lines of Library:            27042
Lines of Definitions:        22994
Lines of TypeScript:             4
Lines of JavaScript:             0
Lines of JSON:                   0
Lines of Other:                  0
Nodes of Library:           117711
Nodes of Definitions:       100981
Nodes of TypeScript:           128
Nodes of JavaScript:             0
Nodes of JSON:                   0
Nodes of Other:                  0
Identifiers:                 76712
Symbols:                     70380
Types:                       23792
Instantiations:              20126
Memory used:               126362K
Assignability cache size:     8078
Identity cache size:             2
Subtype cache size:              0
Strict subtype cache size:       0
I/O Read time:               0.01s
Parse time:                  0.24s
ResolveTypeReference time:   0.01s
ResolveModule time:          0.01s
Program time:                0.29s
Bind time:                   0.11s
Check time:                  2.02s
printTime time:              0.00s
Emit time:                   0.00s
Total time:                  2.42s
```

[CPU.20220712.074453.22161.0.001.cpuprofile.zip](https://github.com/angular/angular/files/9089841/CPU.20220712.074453.22161.0.001.cpuprofile.zip)

In particular, the parenthesis do make a difference here.

Closing as this is a TypeScript bug. If you want me to report it with them please let me know, we've seen exponential type checking issues before and worked with them to get them resolved.
