### ISSUE TITLE
Upgrade Angular 12 to 13

### ISSUE THREAD

**Issue by Somnath0603** [angular/angular#46795]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

No

### Description

While upgrading Angular 12 to 13 , i am getting the following issues:

```
ERROR in ./node_modules/@angular/common/fesm2015/http.mjs
Module not found: Error: Can't resolve '@angular/common' in '\src\main\node_modules@angular\common\fesm2015'

ERROR in ./node_modules/@angular/forms/fesm2015/forms.mjs
Module not found: Error: Can't resolve '@angular/common' in '\src\main\node_modules@angular\forms\fesm2015'

ERROR in ./node_modules/@angular/platform-browser-dynamic/fesm2015/platform-browser-dynamic.mjs
Module not found: Error: Can't resolve '@angular/common' in '\src\main\node_modules@angular\platform-browser-dynamic\fesm2015'
```

We are looking for help
Anyone has any suggestions ?

### Anything else?

Angular CLI: 13.3.8
Node: 14.16.1
Package Manager: npm 6.14.12
OS: win32 x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router     

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1303.8
@angular-devkit/core         13.3.8
@angular-devkit/schematics   13.3.8
@angular/cli                 13.3.8
@schematics/angular          13.3.8
rxjs                         6.6.7
typescript                   4.7.4
webpack                      4.43.0

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

---

I notice in your version output that it includes `webpack 4.43.0`; the CLI uses Webpack 5 so you might have some dependency issues in your setup.
