### ISSUE TITLE
Infinite loop in typescript compiler when fullTemplateTypeCheck is enabled

### ISSUE THREAD

**Issue by imirkin** [angular/angular#46790]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

With Angular 14.0.5 and TypeScript 4.6.4, everything is fine. When upgrading to TypeScript 4.7.4, I get an infinite loop. Disabling `fullTemplateTypeCheck` "fixes" this. I originally filed this as a TypeScript issue here: https://github.com/microsoft/TypeScript/issues/49845 to get assistance in debugging, which has led me here.

The template in question has something like

```
<component #asdf *ngIf="someBool && a.length == 0 && b.length == 0 && c.length == 0 && d.length == 0 && ... && z.length == 0" [input]="b" />
<component #asdf *ngIf="a.length > 0"/>
<component #asdf *ngIf="b.length > 0"/>
...
```

Reducing this to a handful of conditions, and it all works fine. Perhaps it's a N^2 issue somewhere? I did let it run for quite a while and it didn't seem to complete.

You can see some sample stacktraces in the referenced TypeScript issue, basically things in checkExpression(). Happy to patch things and debug further if you can provide some direction.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.0.5
Node: 14.19.3
Package Manager: npm 6.14.17 
OS: linux x64

Angular: 14.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.5
@angular-devkit/build-angular   14.0.5
@angular-devkit/core            14.0.5
@angular-devkit/schematics      14.0.5
@schematics/angular             14.0.5
rxjs                            7.5.5
typescript                      4.7.4
webpack                         5.73.0
```

**Comment by jessicajaniuk** [comment]
@imirkin Can you create a reproduction for us in stackblitz? Without a reproduction this isn't actionable for us.

**Comment by imirkin** [comment]
It's a huge (and proprietary) project, I'm not sure it'll reproduce in a smaller self-contained thing. I'm sure it's not just some trivial thing... I was hoping I could get some advice here on how to debug it further myself.

**Comment by jessicajaniuk** [comment]
Unfortunately without a reproduction, there's really nothing we can look at. You can try reaching out on [StackOverflow](https://stackoverflow.com/) using tag `angular` to see if anyone has any suggestions there. I'll close this for now, but if you have a way of creating a repro, feel free to open a new issue.
