### ISSUE TITLE
Upgrading Angular from version 12 to 13 :  Type NgxMyDatePickerModule does not have 'ɵmod' property.

### ISSUE THREAD

**Issue by kunal00731** [angular/angular#46796]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

No

### Description

Currently trying to upgrade my application from Angular 12 to Angular 13 . Faced a lot of issues in the interim and had to upgrade a lot of libs and subsequently changed a lot of the application code . Now I feel I am very near to fixing all the issues but yet I am still stumped by one issue due to which my app is not coming up . In my `package.json`, I am using this library : `"ngx-mydatepicker": "^2.4.11"` . This is currently being imported and used through out the app . This has been added to `app.module.ts` as well like so   :  

```
import { NgxMyDatePickerModule } from 'ngx-mydatepicker';
@NgModule({
  imports: [
                 ........... Other Imports.............
                 NgxMyDatePickerModule.forRoot(), HttpClientModule, 
                 Ng2CompleterModule],

```
Now when I compile my app , I can see the compilation is successful . However , when I try to load my app, I see that the browser console keeps giving me this error :  `Type NgxMyDatePickerModule does not have 'ɵmod' property.` due to which the app does not come up .

**I tried the following steps but that did not help me  :**  

1. Tried to move to `angular-mydatepicker` as per the link : [angular-mydatepicker](https://github.com/kekeh/angular-mydatepicker)  . But it was not helpful. Now instead of `ngxMyDatepicker` , I keep getting :  `angular-mydatepicker does not have emod property.`
2. Next I tried using the `ngcc` as a postinstall script like so :   `"postinstall": "ngcc"` . However , ngcc does not seem to process  `ngxMyDatepicker` as evidenced here :  

`_> ngcc

Processing legacy "View Engine" libraries:
- angular-draggable-droppable [fesm2015/esm2015] (git+https://github.com/mattlewis92/angular-draggable-droppable.git)
- angular-resizable-element [fesm2015/esm2015] (git+https://github.com/mattlewis92/angular-resizable-element.git)
- @ng-idle/core [fesm2015/esm2015] (git+https://github.com/moribvndvs/ng2-idle.git)
- ng2-completer [es2015/esm2015] (oferh/ng2-completer)
- ngx-order-pipe [es2015/esm2015] (git+https://github.com/VadimDez/ngx-order-pipe.git)
- angular-calendar [fesm2015/esm2015] (git+https://github.com/mattlewis92/angular-calendar.git)
- angular-draggable-droppable [fesm5/esm5] (git+https://github.com/mattlewis92/angular-draggable-droppable.git)
- angular-draggable-droppable [esm2015/esm2015] (git+https://github.com/mattlewis92/angular-draggable-droppable.git)
- @ng-idle/keepalive [fesm2015/esm2015] (git+https://github.com/moribvndvs/ng2-idle.git)
- @ng-idle/core [esm2015/esm2015] (git+https://github.com/moribvndvs/ng2-idle.git)
- @ng-idle/keepalive [esm2015/esm2015] (git+https://github.com/moribvndvs/ng2-idle.git)
- @ng-idle/core [main/umd] (git+https://github.com/moribvndvs/ng2-idle.git)
- @ng-idle/keepalive [main/umd] (git+https://github.com/moribvndvs/ng2-idle.git)
- angular-draggable-droppable [esm5/esm5] (git+https://github.com/mattlewis92/angular-draggable-droppable.git)
- angular-resizable-element [fesm5/esm5] (git+https://github.com/mattlewis92/angular-resizable-element.git)
- angular-draggable-droppable [main/umd] (git+https://github.com/mattlewis92/angular-draggable-droppable.git)
- angular-resizable-element [esm2015/esm2015] (git+https://github.com/mattlewis92/angular-resizable-element.git)
- angular-resizable-element [esm5/esm5] (git+https://github.com/mattlewis92/angular-resizable-element.git)
- angular-resizable-element [main/umd] (git+https://github.com/mattlewis92/angular-resizable-element.git)
- angular-calendar [fesm5/esm5] (git+https://github.com/mattlewis92/angular-calendar.git)
- angular-calendar [esm2015/esm2015] (git+https://github.com/mattlewis92/angular-calendar.git)
- angular-calendar [esm5/esm5] (git+https://github.com/mattlewis92/angular-calendar.git)
- angular-calendar [main/umd] (git+https://github.com/mattlewis92/angular-calendar.git)
- ng2-completer [main/umd] (oferh/ng2-completer)
- ng2-completer [module/esm5] (oferh/ng2-completer)
- ngx-order-pipe [main/umd] (git+https://github.com/VadimDez/ngx-order-pipe.git)
- ngx-order-pipe [module/esm5] (git+https://github.com/VadimDez/ngx-order-pipe.git)
Encourage the library authors to publish an Ivy distribution._`

**Any suggestions as to what I can do here  ?**

### Please provide the exception or error you saw

```true
Uncaught Error: Type NgxMyDatePickerModule does not have 'ɵmod' property.
    at getNgModuleDef (core.mjs?b55c:1139:1)
    at recurse (core.mjs?b55c:21827:1)
    at recurse (core.mjs?b55c:21838:1)
    at registerNgModuleType (core.mjs?b55c:21823:1)
    at new NgModuleFactory (core.mjs?b55c:21945:1)
    at compileNgModuleFactory (core.mjs?b55c:25990:1)
    at PlatformRef.bootstrapModule (core.mjs?b55c:26233:1)
    at eval (main.ts?4a58:11:1)
    at ./src/main.ts (app.js:4049:1)
    at __webpack_require__ (app.js:4444:33)
    at app.js:5598:37
    at app.js:5600:12
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.8
Node: 14.16.1
Package Manager: npm 6.14.12
OS: win32 x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1303.8
@angular-devkit/core         13.3.8
@angular-devkit/schematics   13.3.8
@angular/cli                 13.3.8
@schematics/angular          13.3.8
rxjs                         6.6.7
typescript                   4.7.4
webpack                      5.73.0
```

**Comment by JoostK** [comment]
Closing per the above, thanks @lukasmatta.
