### ISSUE TITLE
Angular Devtools: Component Inspector is not working

### ISSUE THREAD

**Issue by ChaitanyaPTank** [angular/angular#46804]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Hello,

I am trying to inspect a particular component by using angular devtools's component picker, however when I go back on browser window running angular app in development mode, it is not piking any component, cursor behaves normal like in normal window, no highlight or any view indication are given.

I searched on internet but couldn't find anything helpful on any platform like stack-overflow etc.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 10.0.4
Node: 16.12.0
OS: linux x64
Angular Devtools Version: 1.0.6

Angular: 10.0.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes
```

**Comment by ChaitanyaPTank** [comment]
Edit: If I create new project with latest cli, then everything works fine.

**Working Environment:**

- Angular CLI: 12.2.17
- Node: 16.12.0 (Unsupported)
- Package Manager: npm 8.1.0
- OS: linux x64
- Angular: 12.2.16

**Comment by AndrewKushnir** [comment]
@ChaitanyaPTank Angular DevTools supports Angular v12 and later (in your original message, you've mentioned Angular v10), see https://angular.io/guide/devtools. I'm closing this ticket, please reopen if the problem still exists after upgrading to v12 or later version.

**Comment by ChaitanyaPTank** [comment]
@AndrewKushnir Thank you. I am not sure if I can upgrade to angular 12(decision is not in my hand), is there any chance I can get it working ?
