### ISSUE TITLE
instanceCleanupFn was called but it was not a function

### ISSUE THREAD

**Issue by lukasmatta** [angular/angular#46818]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Hello,
I was investigating type error reported during runtime of our production app, and I found out that inside `processCleanups` function, `instanceCleanupFn` was called multiple times even it was not a function.

https://github.com/angular/angular/blob/8d2e5e6c4f5dd8ff435152f4a3ce94d7197255aa/packages/core/src/render3/node_manipulation.ts#L484

The error was logged multiple times but I was not able to reproduce it on my side. Should we ignore this error or is this actually an issue?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.3
Node: 16.13.1
Package Manager: npm 8.12.2
OS: darwin x64

Angular: 13.2.2
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.4
@angular-devkit/build-angular   13.2.3
@angular-devkit/core            13.2.3
@angular-devkit/schematics      13.2.3
@angular/cdk                    13.2.3
@angular/cli                    13.2.3
@angular/material               13.2.3
@schematics/angular             13.2.3
ng-packagr                      13.2.1
rxjs                            7.5.4
typescript                      4.5.5
```

**Comment by JoostK** [comment]
There is a development mode assertion that validates the presence of this function (but this is dropped in optimized builds) so it's a bug if it's undefined, but without a reproduction it's nigh impossible to narrow it down

The version output is for the packages in this repository, is that intended?

**Comment by lukasmatta** [comment]
@JoostK Sorry, I accidentally ran `ng version` in wrong folder, updated it with the correct version output. I will try to investigate logs and reproduce it.
