### ISSUE TITLE
XSS vulnerability in @angular/core

### ISSUE THREAD

**Issue by sahilbabbar** [angular/angular#46817]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

On running `npm audit`, 'Cross site scripting in Angular' vulnerability is found(apart from other vulnerabilities). How to fix this?

### Please provide the exception or error you saw

```
                                Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance


  Moderate        Cross site scripting in Angular

  Package         @angular/core

  Patched in      >=11.0.5

  Dependency of   codelyzer [dev]

  Path            codelyzer > @angular/core

  More info       https://github.com/advisories/GHSA-c75v-2vq8-878f
```

### Please provide the environment you discovered this bug in (run `ng version`)

```
Angular CLI: 13.2.3
Node: 14.15.1
Package Manager: npm 6.14.8
OS: win32 x64

Angular: 13.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.3
@angular-devkit/build-angular   13.2.3
@angular-devkit/core            13.2.3
@angular-devkit/schematics      13.2.3
@angular/cli                    13.2.3
@schematics/angular             13.2.3
rxjs                            6.6.3
typescript                      4.4.4
```

### Anything else?

1. The exception says that its patched in `>=11.0.5` but my project is using Angular `13.2.2`. Is it talking about `codelyzer`'s version? 

2. Since the path is `codelyzer > @angular/core`, is it true to say that this vulnerability won't be part of production package?

**Comment by JoostK** [comment]
Indeed, this is brought in through `codelyzer`'s dependency on `@angular/core@9.0.0`. Since Codelyzer was built for TSLint and TSLint is no longer supported, you should be looking to migrate to an alternative linter such as ESLint + [angular-eslint](https://github.com/angular-eslint/angular-eslint).

And yes, this is a development only dependency.
