### ISSUE TITLE
adding the quote key in html usage

### ISSUE THREAD

**Issue by teamIgal** [angular/angular#46816]
### Description

hi there
I am not sure if it is already possible or not but I could find anything on the internet.
I would like to do something like this <input (keydown.shift.quote)> the important thing is the quote part i know i could do this on the typescript part of the component but it would be more nice to do it like the way i showed.
thank you for the help :)

### Proposed solution

adding a name to the quote(") key like arrowUp for example

### Alternatives considered

checking the key in the typescript like event.key === '"'

**Comment by jessicajaniuk** [comment]
@teamIgal Thanks for the submission. This looks like a duplicate of #45992, which would allow using the code field, making using Quote with key events possible. There's an open PR in review right now that should address this. Feel free to follow #46030.
