### ISSUE TITLE
Wrong change detection cycle when using an embedded view 

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular#46837]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

A directive applied to an HTML element inside an embedded view should run change detection only for the closest embedded view instead of the host:

```ts
@Component({
  template: `
  {{ name }}
  <ng-template [ngIf]="true">
    <button myDir>trigger</button>
 </ng-template>
`,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class MovieComponent {
  get name() {
    // should not run when clicking on the button
    console.log('run')
    return 1;
  }
}
```

```ts
@Directive({
  selector: '[myDir]'
})
export class MyDirDirective {

  constructor(cdr: ChangeDetectorRef, host: ElementRef<HTMLElement>) {
    host.nativeElement.addEventListener('click', () => {

     // Why this line runs a change detection cycle on MovieComponent and not only on the embedded view?
      cdr.detectChanges();
    })
  }
}
```

**Comment by alxhub** [comment]
I believe this is working as intended. Embedded views don't have their own `ChangeDetectorRef`s (as far as I understand) - injecting the `ChangeDetectorRef` from an embedded view gives you the declaring component's instance.

**Comment by ArielGueta** [comment]
@alxhub if that's the case, how does the following code works?

```ts
const tpl!: TemplateRef<any>;
const ref = tpl.createEmbeddedView({});
ref.detectChanges();
```
