### ISSUE TITLE
Windows Git Bash fails running scriptlet ng-dev

### ISSUE THREAD

**Issue by jayvdb** [angular/angular#46858]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

https://github.com/angular/angular/commit/63396a1ea715de949aa08a4f59319902e5508f03 (less than a month ago) appears to have broken the `ng-dev` command on Git for Windows Bash.  Occurs here and the `components` repo.

If I replace `TS_NODE_PROJECT=$PWD/.ng-dev/tsconfig.json` with `TS_NODE_PROJECT=.ng-dev/tsconfig.json`, it works.

Presumably `$PWD` is a full path provided by MSYS, but probably using `/c/directory/etc`  style slashes, and something is rewriting it and adding C:\ in front, because `ts-node` is attempting to open `C:\c\Projects\ng\angular\.ng-dev\tsconfig.json`

Note there is no nodejs in the msys/mingw package collection any more: https://github.com/msys2/MINGW-packages/issues/6237
And https://github.com/kentcdodds/cross-env repo has been archived, so this path handling problem cant be solved there https://github.com/kentcdodds/cross-env/issues/257

### Please provide the exception or error you saw

```ts
MINGW64 /c/Projects/ng/angular (main) $ yarn -s ng-dev format changed
C:\Projects\ng\angular\node_modules\ts-node\src\index.ts:843
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS5083: Cannot read file 'C:\c\Projects\ng\angular\.ng-dev\tsconfig.json'.

    at createTSError (C:\Projects\ng\angular\node_modules\ts-node\src\index.ts:843:12)
    at reportTSError (C:\Projects\ng\angular\node_modules\ts-node\src\index.ts:847:19)
    at createFromPreloadedConfig (C:\Projects\ng\angular\node_modules\ts-node\src\index.ts:858:36)
    at create (C:\Projects\ng\angular\node_modules\ts-node\src\index.ts:613:10)
    at register (C:\Projects\ng\angular\node_modules\ts-node\src\index.ts:580:15)
    at Object.registerAndCreateEsmHooks (C:\Projects\ng\angular\node_modules\ts-node\src\esm.ts:116:34)
    at file:///C:/Projects/ng/angular/node_modules/ts-node/esm.mjs:8:7
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24) {
  diagnosticCodes: [ 5083 ]
}
```

### Please provide the environment you discovered this bug in (run `ng version`)

```
Node: 16.16.0 (from Choco package node-lts)
Yarn: 1.22.17 (from Choco)
Git for Windows 2.37.1 (from Choco)
```

**Comment by devversion** [comment]
As stated in the PR, this is a temporary solution, we are working with ts-node to fix this (the initial fix PR landed there already).

I wonder out of curiosity though why `$PWD` is not defined for you? I tested with Git Bash, and another team member, and it worked as expected.

Can you elaborate if you actually use Git Bash, and what does '$PWD' evaluate to for you?

**Comment by devversion** [comment]
I'm confused why the path is ending up like this for you. We specifically tested with Git Bash before we applied this temporary trick.

**Comment by jayvdb** [comment]
As this was a probably in my assessment above, I added https://www.npmjs.com/package/@bahmutov/print-env , and ran `print-env PWD`

```
PWD=/c/Projects/ng/angular
```

Running ` cross-env FOO=$PWD node node_modules/@bahmutov/print-env/bin/print-env.js FOO` also works as expected
```
FOO=/c/Projects/ng/angular
```

So something after the `cross-env` is doing the msys->DOS file path translation.

**Comment by devversion** [comment]
Interesting. If I run this on the components repo, with my Windows machine, it seems to work as expected. If I set an incorrect path for the tsconfig, I can see that the path is converted properly:

<img width="849" alt="image" src="https://user-images.githubusercontent.com/4987015/179372528-96b18d2b-d12a-4cad-af44-4685f12b0a1e.png">

and

```
$ echo $PWD
/c/Users/paul/projects/material2
```

**Comment by jayvdb** [comment]
I ran `ts-node`'s test suite on the same environment - no errors.

I'll try all this under `C:\Users\..` in case that is relevant.

Which git bash version are you using?

**Comment by kiran-pathe** [comment]
Also not working for me on windows. 
Can't we switch back to last working version of ts-node ?

![image](https://user-images.githubusercontent.com/4928576/219942227-525f1d4a-2255-478b-be18-3611f235f2dc.png)

**Comment by devversion** [comment]
We actually should be able to. I have landed a fix on their repository. I don't know if it's released though yet..
