### ISSUE TITLE
Dynamic template Reference variables

### ISSUE THREAD

**Issue by mwave317** [angular/angular#46857]
### Description

I would like to see this as a new feature. I'm currently creating a graph using Angular/cdk/dragdrop. I need to remove an image in the graph. I'm unable to do this using @ViewChild, since the divs are created dynamically. If I could use dynamically created template reference variables this would solve the issue. Currently, I'm only able to use vanilla javascript. I'm aware that is not a best practice, but don't have another way of dealing with the issue. 

### Proposed solution

To add the dynamically created template reference variables. Another option is if the @ViewChild could use the dynamically created id. 

### Alternatives considered

I've tried using @ViewChild with no luck.

**Comment by pkozlowski-opensource** [comment]
We've been discussing dynamic template variables in the past (see #44640 and #33233 as the examples) and decided against implementing it. 

Having said this I don't think I fully understand your use-case. Could you please prepare a minimal stackblitz with an example scenario?

**Comment by alxhub** [comment]
(Closing due to no resposne)
