### ISSUE TITLE
How to dispose of the NgZone?

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#4685]
There's a todo in the [`ApplicationRef#L381`](https://github.com/angular/angular/blob/6abed8d996168f695e638c0c2d0fde1ad7ae273c/modules/angular2/src/core/application_ref.ts#L381) to dispose of NgZone.

For server rendering we bootstrap the application on each request and reuse as much of the providers as we can get away with during each subsequent request. At the moment I'm not sure how `zone.js` and `NgZone` manages itself for something like this. We use `NgZone` to keep track of all `Http` calls made during bootstrap as a way to render the page after all the calls are done for the client

**Comment by mhevery** [comment]
I think the zone will auto GC as soon as all of the async callbacks are closed. So in the app it would mean that all setTimeouts and event listeners are cleaned up.
