### ISSUE TITLE
 Angular2 transformer crashes pub on invalid syntax

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#4687]
Internal issue #24877065

**Comment by kegluneq** [comment]
`pub serve` is designed to gracefully catch & surface transformer exceptions but appears to mis-handling them in some situations.

I'll take a look at catching all errors & reporting them through other mechanisms.

**Comment by zoechi** [comment]
is this like #6384?

**Comment by jbdeboer** [comment]
No, this is where I leave "pub serve" running while I am writing code and return to pub to find that it is not serving requests.  It doesn't sigfault, but it becomes unresponsive.

Based on the last console output, I suspect it the Angular transformer is responsible.

**Comment by kegluneq** [comment]
Unfortunately, it's not something that can be fixed in the transformer, but we should be able to mitigate it.
