### ISSUE TITLE
ngUpgrade documentation appears to self-contradict

### ISSUE THREAD

**Issue by jmwolfe** [angular/angular#46873]
### Description

First this section says:

> So normally **a hybrid application begins life as an AngularJS application**, and it is AngularJS that processes the root template, for example, the index.html. Angular then steps into the picture when an Angular component is used somewhere in an AngularJS template. The template of that component will then be managed by Angular, and it may contain any number of Angular components and directives.

A little later on it says:

> To bootstrap a hybrid application, you must bootstrap each of the Angular and AngularJS parts of the application. **You must bootstrap the Angular bits first and then ask the [UpgradeModule](https://angular.io/api/upgrade/static/UpgradeModule) to bootstrap the AngularJS bits next.**

it's very counter-intuitive that if AngularJS reads the initial index.html and starts the application, that you would be bootstrapping Angular first.  By "starts life" do you mean it was written years ago in AngularJS?

### What is the affected URL?

https://angular.io/guide/upgrade#upgrading-with-ngupgrade

### Please provide the steps to reproduce the issue

It's documentation, n/a

### Please provide the expected behavior vs the actual behavior you encountered

I would expect all the documentation to not contradict itself

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
No
```

**Comment by atscott** [comment]
Yes, "starts life" refers to an application that was written in AngularJS and is being upgraded to Angular gradually.

**Comment by regulas1** [comment]
@bob-watson may I take this up ?

**Comment by mounilKshah** [comment]
If there is no one else working on this issue, may I work on this? @bob-watson @atscott

**Comment by JeanMeche** [comment]
Angular.io is now in maintenance mode and angular.dev doesn't cover angular.js anymore. I'll close this issue.
