### ISSUE TITLE
[Animation]  Extra change detection triggered by BrowserDetails ?

### ISSUE THREAD

**Issue by vicb** [angular/angular#4688]
The constructor of `BrowserDetails` calls `doesElapsedTimeIncludesDelay()` which in turn subscribe to `requestAnimationFrame`.

Because this code is executed inside the Angular zone, it triggers extra change detection runs. What about something like:

```typescript
  doesElapsedTimeIncludesDelay(): void {
    var div = DOM.createElement('div');
    DOM.setAttribute(div, 'style', `position: absolute; top: -9999px; left: -9999px; width: 1px;
      height: 1px; transition: all 1ms linear 1ms;`);
    // Firefox requires that we wait for 2 frames for some reason
    this.ngZone.runOutsideAngular(() => {
      this.raf(timestamp => {
        DOM.on(div, 'transitionend', (event: any) => {
          var elapsed = Math.round(event.elapsedTime * 1000);
          this.elapsedTimeIncludesDelay = elapsed == 2;
          DOM.remove(div);
        });
        DOM.setStyle(div, 'width', '2px');
      }, 2);
    });
  }
```

Notice the wrapping inside `this.ngZone.runOutsideAngular()` - `ngZone` would need to be injected.

@matsko @robertmesserle thoughts ?

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

by the latest animation implementation.
