### ISSUE TITLE
Angular version 14 is not loaded in iphone 6

### ISSUE THREAD

**Issue by ToanNguyenAdamo** [angular/angular#46886]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

After I upgrade from version 13 to 14, I run the app and return blank screen like this in iphone 6:
![image (17)](https://user-images.githubusercontent.com/98306799/179691740-38588d53-7adc-4e54-89a5-ee0436979d0c.png)

I also tried creating new app with ng new command and same result.

I tried replacing the target field from es2020 to es2017 in the tsconfig.json file. The application will be loaded, but a lot of features do not work if I use iphone 6.
Please give me the solution if you also have this problem. Thanks

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.6
Node: 16.13.0
Package Manager: npm 8.1.0
OS: win32 x64

Angular: 14.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.6
@angular-devkit/build-angular   14.0.6
@angular-devkit/core            14.0.6
@angular-devkit/schematics      14.0.6
@schematics/angular             14.0.6
rxjs                            7.5.6
typescript                      4.7.4
```

**Comment by alan-agius4** [comment]
What is the browser that is being used in the mentioned IPhone 6?

**Comment by ToanNguyenAdamo** [comment]
My Iphone version is 12.5.5 and chrome version is 9x. I think you are right. So, I need to update my Iphone to make it work.
Thank you for your response @alan-agius4

**Comment by karptonite** [comment]
Try setting your target to es2015 instead of es2017 or es2020. That seems to have made angular 14 work for our Safari 12 users.

**Comment by ToanNguyenAdamo** [comment]
> Try setting your target to es2015 instead of es2017 or es2020. That seems to have made angular 14 work for our Safari 12 users.

Thank you, It is loaded in safari 12, but a lot of UI parts are not working, for example: clicking mat-button, mat-expansion,...
