### ISSUE TITLE
Bootstrapping Hybrid Applications doc shows two different app.module.ts files with no explanation

### ISSUE THREAD

**Issue by jmwolfe** [angular/angular#46880]
### Description

There are several app.module.ts code files documented within this section. It appears that some of them refer to the angularJS version and some refer to the Angular version, but it's not made clear in the text which one belongs to which.  In attempting to follow the directions, for the last two uses of app.module.ts, it's entirely unclear where I am creating these files and what is the context:

<img width="525" alt="image" src="https://user-images.githubusercontent.com/5149210/179648813-dbdaf1b0-c657-4402-91ca-4e516a433d59.png">

The document may also need to make a statement that "YOUR" AngularjS application that you are upgrading may call the file app.js... as the AngularJS style guide suggested that (See Style [Y152](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y152)). Calling it app.module.ts is very confusing because most angularJS 1.x developers didn't use typescript.

### What is the affected URL?

https://angular.io/guide/upgrade#bootstrapping-hybrid-applications

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
No
```

**Comment by JeanMeche** [comment]
We're looking at deprecating the angular.io documentation in favor of https://angular.dev. 

Feel free to open an issue dedicated for the new doc site if you have suggestions, thank you.
