### ISSUE TITLE
docs tests are absent on travis

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#4690]
errors described in https://github.com/angular/angular/issues/4464 were introduced at some point because we don't enforce this be green on travis.

**Comment by alexeagle** [comment]
@naomiblack can you point me to the docs tests we are currently not running in travis?

**Comment by alexeagle** [comment]
some pointers to fix this.

which HTML files get copied to dist?
https://github.com/angular/angular/blob/3f4628c0b0211824fdc0a6c456c23209d439c7cd/tools/broccoli/trees/browser_tree.ts#L176

how does Travis know to run protractor tests?
https://github.com/angular/angular/blob/3f4628c0b0211824fdc0a6c456c23209d439c7cd/scripts/ci/test_e2e_js.sh

how do we tell Protractor where the tests are?
https://github.com/angular/angular/blob/3f4628c0b0211824fdc0a6c456c23209d439c7cd/protractor-shared.js

**Comment by vicb** [comment]
dup of https://github.com/angular/angular/issues/9322
