### ISSUE TITLE
(pure) pipes as injectables

### ISSUE THREAD

**Issue by oBusk** [angular/angular#46920]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

I'd like to be able to use the common pipes in component code and services. Things such as [`DatePipe`](https://angular.io/api/common/DatePipe), [`CurrencyPipe`](https://angular.io/api/common/CurrencyPipe), and [`TitleCasePipe`](https://angular.io/api/common/TitleCasePipe) defines common problems that has already been solved in `@angular/common`. Most of them are not difficult to re-implement to use in a service, or in the class of a component, but if the code is already there in `@angular/common`, should I not be able to use it in services too? [`AsyncPipe`](https://angular.io/api/common/AsyncPipe), and any other pipe that is not `pure` would obviously be problematic and not make sense as injectable.

In components this can be worked around by adding the Pipe to `providers: []` in the module or the standalone declaration. However this becomes awkward with services where you need to add the pipe as `providers: []` in a Module and then provide the service in that module, which is contrary to the fact that `providedIn: 'root'` is the go-to and recommended way to provide injectables in modern Angular.

It's also related that own defined Pipes could also be useful as injectables, but in those cases it's not too difficult to do

```typescript
@Injectable({ providedIn: 'root' })
@Pipe({ name: 'mypipe', standalone: true })
export class MyPipe implements PipeTransform {
  // ...
}
```

### Proposed solution

Make pipes that are `standalone: true` also injectable. This makes it easy to make utilities that can be used in templates _and_ typescript.

### Alternatives considered

Make all `CommonModule` pipes `@Injectable()` in addition to their `@Pipe({ standalone: true })`. This ensures all the `CommonModule` pipes are injectable, and if you want your own pipes to be injectable, you can do the same with your own pipes.

**Comment by pkozlowski-opensource** [comment]
If I understand the use-case correctly, the intention is to reuse logic currently contained in pipes. I totally see the need but I don't think that we should be making pipes injectable - those are meant to be used in templates. 

What we should do instead, probably, is to export that actual logic as regular JavaScript functions.

**Comment by pkozlowski-opensource** [comment]
Actually, we already _do_ export [formatDate](https://angular.io/api/common/formatDate) function.

As noted above, we don't want to promote using pipes as injectables. The logic in question is already publicly available as a function - you can wrap it into a DI provider if needed.
