### ISSUE TITLE
Isolate scope for only specified elements?

### ISSUE THREAD

**Issue by axos88** [angular/angular#4692]
Hello!

I am creating a nested directive, similar to "how to create directives that communicate" from https://docs.angularjs.org/guide/directive .

My problem is with the nesting of scopes. I would like to access to outer scope from the inside:

```
<div>{{foo.bar}}

<my-tabs>
  <my-pane title="x">
    <input ng-model="foo.bar" />
  </my-pane>
  <my-pane title="y">
    <input ng-model="foo.baz" />
  </my-pane>
</my-tabs>
```

However in order to do this I have to use `$parent.$parent.$parent.$parent`.

Is there a way to isolate the scope of only a select variables (`panes`, `pane`, `addPane()` and `select()` in this case?). E.g. a "reverse isolation", specifying which variables should NOT be inherited.

Using `bindToController` won't do either, because I want to keep the directive reusable, without listing the variables it needs to access in the outer scope.

**Comment by PascalPrecht** [comment]
This is the repo for Angular 2. Please move this issue to
http://github.com/angular/angular.js, or better use the gitter chat for
support questions like these.

Thanks!
