### ISSUE TITLE
dynamic create component in library package not work

### ISSUE THREAD

**Issue by oudi** [angular/angular#46933]
### Which @angular/* package(s) are the source of the bug?

compiler, core

### Is this a regression?

No

### Description

Dynamic create a component and npm publish to a package. when using it in an angular app. it shows the error

`Uncaught (in promise): Error: Unexpected value 'dynamicComponent' declared by the module 'class { }  '. Please add a @Pipe/@Directive/@Component annotation`

If I use it as a library project in the app. everything is ok.

### Please provide the exception or error you saw

```true
         @Component({
            selector: 'Component_' + pageState.PageID + '_' + pageState.PageState,
            template: pageState.Template,
            jit: true,
          })
          class dynamicComponent implements OnInit {

            constructor() { }

            ngOnInit() { }
          };

          @NgModule({
            imports: dynamicDepens,
            declarations: [dynamicComponent],
            entryComponents: [dynamicComponent],
            exports: [dynamicComponent],
            jit: true,
          })
          class dynamicModule { };
          const parent = this;
          this.compiler.compileModuleAsync(dynamicModule).then(moduleFactory => {
            const mod = moduleFactory.create(this.injector);
            const componentFactory = mod.componentFactoryResolver.resolveComponentFactory(dynamicComponent);

            const component = componentFactory.create(this.injector);
            component.instance["parent"] = parent.page.appID;
            component.instance["splitterResizeStop"] = function () {
              parent.cdr.markForCheck();
            };
            this.contentTarget.insert(component.hostView);
            this.cdr.markForCheck();
          })
        }).catch((error) => {
          throw error;
        })
```

```
core.js:4442 ERROR Error: Uncaught (in promise): Error: Unexpected value 'dynamicComponent' declared by the module 'class {
                    }'. Please add a @Pipe/@Directive/@Component annotation.
Error: Unexpected value 'dynamicComponent' declared by the module 'class {
                    }'. Please add a @Pipe/@Directive/@Component annotation.
    at verifySemanticsOfNgModuleDef (core.js:25967:1)
    at Function.get (core.js:25902:1)
    at getInjectorDef (core.js:396:1)
    at R3Injector.processInjectorType (core.js:11187:1)
```
```


### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 10.2.3
Node: 16.15.0
OS: win32 x64

Angular: 10.2.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes
```

**Comment by oudi** [comment]
Debug from chrome

![image](https://user-images.githubusercontent.com/2518192/180387460-3e46081a-4c9a-4a66-9c1a-f7d64650240e.png)

**Comment by oudi** [comment]
```
          Component({
            selector: 'Component_' + pageState.PageID + '_' + pageState.PageState,
            template: pageState.Template,
            jit: true,
          })
          class dynamicComponent implements OnInit {
            constructor() { }
            ngOnInit() { }
          };

          NgModule({
            imports: dynamicDepens,
            declarations: [dynamicComponent],
            entryComponents: [dynamicComponent],
            exports: [dynamicComponent],
            jit: true,
          })
          class dynamicModule { }

          const parent = this;

          const moduleWithComponentFactories = this.compiler.compileModuleAndAllComponentsSync(dynamicModule);
```

tried compileModuleAndAllComponentsSync and published the library. shows Cannot read properties of null (reading 'declarations')

![image](https://user-images.githubusercontent.com/2518192/180396995-b2aaca38-55e0-43cc-afa1-edd7a4474573.png)

**Comment by alxhub** [comment]
@oudi please provide a link to a complete, minimal reproduction demonstrating the issue. Without that it'll be impossible to understand what's actually going on here.

**Comment by oudi** [comment]
@alxhub

I attempted many ways. And find it works with beflow code.

```
          const dynamicComponent = Component({
            selector: 'Component_' + pageState.PageID + '_' + pageState.PageState,
            template: pageState.Template,
            jit: true,
          })(
            class implements OnInit {
              constructor() { }
              ngOnInit() { }
            });

          const dynamicModule = NgModule({
            imports: dynamicDepens,
            declarations: [dynamicComponent],
            entryComponents: [dynamicComponent],
            jit: true,
          })(class { });

          const parent = this;

          const moduleWithComponentFactories = this.compiler.compileModuleAndAllComponentsSync(dynamicModule);
```

just change annotation to a variable and remove `class` declaration. and It works. It may if you declare annotation it will compile to a class with dictators when publish and If it was a variable it will compile in jit.

**Comment by alxhub** [comment]
@oudi,

Without a _runnable_ reproduction, we will not be able to investigate this issue unfortunately. 

For example, what is `dynamicDepens` in your code? It's never defined in the examples you've pasted. Nor is `pageState` or `pageState.Template`. We cannot paste this code into a project and try it to see what fails.

**Comment by oudi** [comment]
@alxhub I reproduction with https://github.com/oudi/AngularDynamicComponent , and state the issue in README.md

The key code is https://github.com/oudi/AngularDynamicComponent/blob/main/od-app/projects/od-core/src/lib/od-part/od-part.component.ts#L19

**Comment by oudi** [comment]
@alxhub  return variable of component works for the library. but I can not use any decorators in it. It shows `TS1206` error.

![image](https://user-images.githubusercontent.com/2518192/180680049-59a59f6d-67f1-4918-a391-d62872a1bb22.png)

**Comment by oudi** [comment]
solved it in a trick way. close.
