### ISSUE TITLE
Why is the HTTP header not sent when added to the Angular HttpClient? 

### ISSUE THREAD

**Issue by hteht** [angular/angular#46934]
### Which @angular/* package(s) are the source of the bug?

common, Don't known / other

### Is this a regression?

Yes

### Description

I'm trying to set the Content-Type for the post method header but it's not working
I tried the following methods:
![image](https://user-images.githubusercontent.com/87110312/180391622-9434821c-e4c5-40f4-9b5c-17f3813c899d.png)

![image](https://user-images.githubusercontent.com/87110312/180392522-30a7b674-cf22-4d3d-813f-a7918cb7a61e.png)

![image](https://user-images.githubusercontent.com/87110312/180392787-558f8564-1d95-4e5e-8611-ce2fac325d88.png)

But they are all content-type  is application/json; charset=utf-8 . 

![image](https://user-images.githubusercontent.com/87110312/180393482-bcbbf135-262a-48f7-a79a-80aa3c0b0090.png)

![image](https://user-images.githubusercontent.com/87110312/180393593-5d5a6add-34f2-452b-81b3-be9faff7fc0c.png)
Tell me how to fix this, please.

**Comment by alxhub** [comment]
I'm not exactly sure why your header gets overridden - it might be `XMLHttpRequest` behavior and not Angular.

But to send `x-www-form-urlencoded` content, you need to use pass the body as an instance of [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) or Angular's version (`HttpParams`). Objects passed will be serialized as JSON.
