### ISSUE TITLE
Auxiliary routes need proper documentation

### ISSUE THREAD

**Issue by Krustie101** [angular/angular#4693]
At the moment it is not at all clear how auxiliary routes should be used. The test code only contains a trivial example that leaves us guessing to the intent of this feature. It seems that we can only target one component into a named router-view: the one that is configured in the RouteConfig with the same path name as the name of the router-view. The only flexibility seems to be in the parameters that we pass to that component in that named router view. If we do not select this auxiliary route in the path, we get an error. So what is the purpose of an auxiliary selector in a path: to offer the possibility of passing parameters? 

As it stands now, it looks to me that in a view with one main (i.e. unnamed) router-view  and several auxiliary (i.e. named) router-views, the named router views are fixed and the main router-view can be changed via the routing path.  

Such an auxiliary router-view has its own router so it is in theory possible to use it for nested views but this functionality seems not to be exposed (at least I could not see how to trigger it). This could be ok but it leaves us with auxiliary views that can only be configured via parameter passing.

I could be missing something in the source code but if this is as designed, the auxiliary routings are different from the multiple view feature in the ui-router because in the philosophy of the ui-router, one could change the "auxiliary" views together with the main view.

**Comment by btford** [comment]
Yep, we're still in the process of working on docs. Please bear with us.

**Comment by mhevery** [comment]
closing as we do not track individual docs here.
