### ISSUE TITLE
*ngVar doesn't work in angular 14

### ISSUE THREAD

**Issue by slypy** [angular/angular#46945]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When I tried to use *ngVar in angular 14 seem like there is something strange or I was missguided in the ng-Book. When I declare a variable in angular 14 like `*ngVar="false as bVar"` and use it to display as test but nothings shows `false`. Should I keep using the ngIf rather than ngVar?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.5
Node: 16.15.1
Package Manager: npm 8.11.0
OS: linux x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1400.5 (cli-only)
@angular-devkit/core         14.0.5 (cli-only)
@angular-devkit/schematics   14.0.5 (cli-only)
@schematics/angular          14.0.5 (cli-only)
```

**Comment by AndrewKushnir** [comment]
The `ngVar` is not a directive provided by Angular, so it's likely a 3rd party directive. Please report the issue to the directive maintainers for further investigation. Thank you.
