### ISSUE TITLE
docs: TemplateRef.createEmbeddedView() mentions attaching the instantiated view to a view container

### ISSUE THREAD

**Issue by Achilles1515** [angular/angular#46955]
### Description

The TemplateRef.createEmbeddedView() method states:
>Instantiates an embedded view based on this template, and attaches it to the view container.

- What view container is this method description referencing? No `ViewContainerRef` is being used here.

I don't believe this description is correct, but please correct me if I am wrong.

### What is the affected URL?

https://angular.io/api/core/TemplateRef#createembeddedview

**Comment by pkozlowski-opensource** [comment]
You are absolutely right - this part of the description is incorrect:

> and attaches it to the view container.
