### ISSUE TITLE
getting this error when running ng serve Namespace '"/home/user/proj/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.

### ISSUE THREAD

**Issue by KLN888** [angular/angular#46969]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When executing ng serve i am getting  a number of errors in ng-bootstrap
Namespace '"/home/user/proj/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.
 static ɵprov: i0.ɵɵInjectableDeclaration<ScrollBar>;

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular cli :8.3.29
Node: 16.0.0
npm:7.10.0
```

**Comment by alan-agius4** [comment]
Angular CLI 8 is no longer supported.

Please update a more recent supported version. See: https://angular.io/guide/releases#support-policy-and-schedule
