### ISSUE TITLE
Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'ɵmod')

### ISSUE THREAD

**Issue by AdilSirva** [angular/angular#46966]
### Which @angular/* package(s) are the source of the bug?

compiler, core, router

### Is this a regression?

Yes

### Description

I have migrated my application from Angular version 9 to 13. After a lot of caveats I reached to ng serve it without any error in Angular CLI. Now, as soon as my application launches in browser, I see below provided error.

I tried different solutions provided by different communities; like; stackoverflow, github etc. but unfortunately no luck so far. I tried below suggestions:

- Delete node_modules, delete package.lock.json, clear the npm cache, clear the .angular cache, restart VS code, do npm i, ng serve.
- Check for circular dependency in application and resolve it.
- If you are using custom pipe in application, don't mention them in imports of ngModule, mention them in providers.

Any help is appreciated. Thanks a lot !!!

![image](https://user-images.githubusercontent.com/104505925/180841821-5da60c34-bbc5-4908-bb75-23a76c689841.png)

### Please provide the exception or error you saw

```true
zone.js:182 Uncaught Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'ɵmod')
TypeError: Cannot read properties of undefined (reading 'ɵmod')
    at getNgModuleDef (core.mjs:1137:1)
    at new NgModuleFactory (core.mjs:21906:1)
    at Compiler.compileModuleSync (core.mjs:25189:1)
    at Compiler.compileModuleAsync (core.mjs:25195:1)
    at router.mjs:3985:43
    at doInnerSub (mergeInternals.js:19:18)
    at outerNext (mergeInternals.js:14:1)
    at OperatorSubscriber._next (OperatorSubscriber.js:13:1)
    at OperatorSubscriber.next (Subscriber.js:31:1)
    at innerFrom.js:61:28
    at resolvePromise (zone.js:1211:1)
    at resolvePromise (zone.js:1165:1)
    at zone.js:1278:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25595:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.8        
Node: 16.16.0
Package Manager: npm 8.11.0
OS: win32 x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.8
@angular-devkit/build-angular   13.3.8
@angular-devkit/core            13.3.8
@angular-devkit/schematics      13.3.8
@angular/cdk                    13.3.9
@angular/cli                    13.3.8
@schematics/angular             13.3.8
rxjs                            7.5.6
typescript                      4.6.4
```

### Anything else?

![image](https://user-images.githubusercontent.com/104505925/180842139-40d83a89-df05-4dc2-964f-f181d4df2b00.png)

![image](https://user-images.githubusercontent.com/104505925/180842004-3de36c6c-59b5-4e58-95c4-1745f7a27309.png)

**Comment by atscott** [comment]
There isn’t enough information here to understand what might be causing the issue. Please provide a minimal reproduction in order for us to determine if this is an issue in Angular.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
