### ISSUE TITLE
Is it possible to consider lazy loading modules

### ISSUE THREAD

**Issue by Vibing** [angular/angular#46967]
### Description

like this:
```
const HelloModule = () => import('../hello.module').then((m) => m.HelloModule);

@NgModule({
  imports: [HelloModule]
})
export class DashboardModule {}
```ts

### Proposed solution

I know this can be cumbersome, but it can help apps save a lot of code

### Alternatives considered

I don't have a solution, it's just a consideration

**Comment by pkozlowski-opensource** [comment]
You can absolutely lazy load modules today - in fact router does it all the time. As you've mentioned, it might be cumbersome at time and this is why we've introduced standalone components in Angular v14: https://angular.io/guide/standalone-components

I'm going to close this issue as the standalone components are our recommended solution for lazy-loading code in Angular. We are not planning on making any adjustments to the scenario around lazy loading modules.
