### ISSUE TITLE
ComponentRef.setInput should validate input names

### ISSUE THREAD

**Issue by javiermarinros** [angular/angular#46978]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

The new ComponentRef [setInput](https://angular.io/api/core/ComponentRef#setInput) API is really useful for dynamic component handling but it has an issue: the input name is not validated against the component input list, allowing any kind of name to be defined, and, even worse, if you try to set a component property not decorated with `@Input()`, it will not change the value and will not warn about it.

Shouldn't Angular warn, at least in development mode, that the specified input name is invalid? The same way the Template Compiler does when trying to define and invalid component input.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.1.0
Node: 16.13.0
Package Manager: npm 8.12.2
OS: win32 x64

Angular: 14.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.0
@angular-devkit/build-angular   14.1.0
@angular-devkit/core            14.1.0
@angular-devkit/schematics      14.1.0
@angular/fire                   7.4.1
@schematics/angular             14.1.0
rxjs                            7.5.6
typescript                      4.7.4
```

**Comment by JoostK** [comment]
> Shouldn't Angular warn, at least in development mode, that the specified input name is invalid?

It should already be doing exactly this. Can you share a reproduction that shows that it does not?

**Comment by pkozlowski-opensource** [comment]
As @JoostK indicated, we've got checks for unknown property names, and a test verifying those checks: https://github.com/angular/angular/blob/3ca985269d3e961321075f0e7facd10ef335be4c/packages/core/test/render3/component_ref_spec.ts#L336-L352

Please provide more details / reproduction scenario if you see those checks not working in specific cases. Please note that we use the same error reporting mechanism as in case of other unknown property bindings on a component.

**Comment by javiermarinros** [comment]
You are right

**Comment by javiermarinros** [comment]
You are right, I replicated the issue and there is a console warning:

https://stackblitz.com/edit/angular-ivy-wcfk7z

Thank you for your help, and sorry for the inconvenience
