### ISSUE TITLE
Possible bug in Ivy using Mixins 

### ISSUE THREAD

**Issue by Nxtivision** [angular/angular#46970]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Hi Everybody, 
I'm struggling with a difficult use case of **mixin in Typescript with Angular.** (not mixin in SCSS)
I'd like to use _mixins to create complex custom form inputs._

It **works in dev environment,** even if I use 3 or more mixins at a time on a same component... Which is the desired behavior.

However, it becomes completely **broken in production environment, with Ivy,** with strange errors...

Example provided in the Stackblitz
containing an example of how I did and used it, including the error. We have the base class containing the Injector, and the other mixins + a custom input component.
As said previously, it works in dev environment but not in Production with Ivy, as you can see in this Stackblitz:

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-wva4z7?file=src/app/mixins/cva-connector.mixin.ts

### Please provide the exception or error you saw

```true
Error: NG0203: inject() must be called from an injection context
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Node 16.13.1
NPM 7.24

@angular/* ^13.1.0
@nrwl/* 14.1.7
```

### Anything else?

Tried to ask this to the communauty, but no answer everywhere.

I remembered I was able to make it work with previous versions of Angular 2 years ago

**Comment by pkozlowski-opensource** [comment]
@Nxtivision there is quite a bit of code in the stackblitz you've shared (100+ LOC) - could you try to simplify the issue to the essential parts?

It is rather hard for us to understand what is going on given the provided example.

**Comment by Nxtivision** [comment]
I just simplified the file, but let me explain in details what's going on:

The idea is to create custom inputs for our forms, using mixins to avoid rewrite some inputs or logic between components.

In the example, we have the **TextComponent** for the basic implementation of our mixins:
https://stackblitz.com/edit/angular-ivy-wva4z7?embed=1&file=src/app/inputs/text.component.ts

as you can see, I use 3 mixins in the **extends:**
* **CvaConnectorMixin**: ControlValueAccessor logic with some basic inputs
* **LengthValidatorMixin**: To add inputs concerning the minLength and maxLength for the input
* **ErrorStateMatcherMixin**: To manage custom ErrorStateMatcher in our input

At the end, we have the **Base** which is the base class containing the Injector and all ready to use lifecycle of Angular:
https://stackblitz.com/edit/angular-ivy-wva4z7?file=src/app/mixins/base-class-injector.ts

It means, in every mixin I use, I should have access to my Injector and all inputs/outputs/properties written in each of my mixin inside my **TextComponent**.

In Development environment, it works, but once I go in production, I get the error:
⚠️  `NG0203: inject() must be called from an injection context`

I hope it is more explicit like this and you'd be able to help me. I plan to write an article on this subject later 😄
