### ISSUE TITLE
Pipes with generic type parameters don't typecheck

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular#46977]
### Which @angular/* package(s) are the source of the bug?

language-service

### Is this a regression?

No

### Description

Lets say we have a pipe that returns a `number`:

```ts
@Pipe({
  name: 'test'
})
export class TestPipe<T> implements PipeTransform {

  transform(value: T): number {
    return 1;
  }
}
```

When we use it on input that expects a `string` it works fine without a `type` error:

```ts
@Component({
  selector: 'app-foo'
})
export class FooComponent {
  @Input() text: string;
}

<app-foo [text]="'bar' | test"></app-foo>
```

This should show a `type` error because the input expects a `string` and the pipe returns a `number`.

### Anything else?

I'm using `strictTemplates: true`

**Comment by JoostK** [comment]
Pipes with generic type parameters are not currently supported. In your case the `T` type parameter can be dropped in favor of using `unknown` where it's used.

**Comment by jarpoole** [comment]
Just got caught by this. Any technical reason or just a nice to have that no one has every tried to implement? Curious because it perhaps its reasonable to take on as a first time contributor?

**Comment by JoostK** [comment]
It would require a different approach to how pipes are declared in the type-checker, specifically using a type constructor. A lot more details are in https://github.com/angular/angular/pull/40870#issuecomment-780882880. There's also [this comment](https://github.com/angular/angular/issues/41861#issuecomment-832774005).

**Comment by alxhub** [comment]
Closing with the same [resolution](https://github.com/angular/angular/issues/41861#issuecomment-832774005) - we don't want to assume that pipes are 1:1 with their usages, because it would block potential optimizations.
