### ISSUE TITLE
FormGroup.updateValueAndValidity() add option to affect descendants

### ISSUE THREAD

**Issue by Leccho** [angular/angular#46971]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

I could have use it a few times now, so I think this could be a nice addition.

Related to https://angular.io/api/forms/AbstractControl#updatevalueandvalidity

### Proposed solution

```typescript
/**
 * Recalculates the value and validation status of the control.
 *
 * By default, it also updates the value and validity of its ancestors.
 *
 * @param opts Configuration options determine how the control propagates changes and emits events
 * after updates and validity checks are applied.
 * *  `affectAncestors`: When false, does not update direct ancestors. When true or not supplied,
 * update all direct ancestors. Default is true.
 * * `affectDescendants`: When true, update direct descendants. When false or not supplied,
 * does not update all direct descendant. Default is false.
 * * `emitEvent`: When true or not supplied (the default), both the `statusChanges` and
 * `valueChanges`
 * observables emit events with the latest status and value when the control is updated.
 * When false, no events are emitted.
 */
updateValueAndValidity(opts: { affectAncestors?: boolean; affectDescendants?: boolean; emitEvent?: boolean; } = {}): void
```
`onlySelf` would be confusing, since we added `affectDescendants`, so we would have to replace it by `affectAncestors`.
`emitEvent` should be passed to the descendants.

Usage:
```FormGroup.updateValueAndValidity({ affectDescendants: true })```

### Alternatives considered

The current alternative is to call `updateValueAndValidity()` on every descendant.

**Comment by dylhunn** [comment]
In general, validation state flows from the bottom to the top of a form structure, so recalculating from the top-down is a bit of a code smell. I'd be curious to see a motivating use case.

**Comment by Leccho** [comment]
@dylhunn It's useful when you have a `FormGroup` in which every `FormControl` `Validators` depends on how the other `FormControl` are used.

Here's a small example of what I mean:
```typescript
public updateValidation(): void {
  if (this.formControl1.value) {
    this.formControl1.setValidators([Validators.required, Validators.pattern(this.somePattern)]);
    this.formControl2.setValidators([]);
    this.formControl3.setValidators([]);
  } else if (this.formControl2.value || this.formControl3.value) {
    this.formControl1.setValidators([]);
    this.formControl2.setValidators([Validators.required]);
    this.formControl3.setValidators([Validators.required, Validators.minLength(3), Validators.maxLength(20)])
  }

  // the following would be replace by this.fg.updateValueAndValidity({ affectDescendants: true })
  this.formControl1.updateValueAndValidity();
  this.formControl2.updateValueAndValidity();
  this.formControl3.updateValueAndValidity();
}
```

Obviously in this case, you don't gain much, but when you have ten `FormContol`, you start to gain a lot of time and readability.

**Comment by dylhunn** [comment]
@Leccho Since the controls depend on each other, why not just put the validator on the enclosing group?

**Comment by Leccho** [comment]
@dylhunn as shown in the example above, I need different `Validators` for each `FormControl`. I mostly use this in a multi input search form where I want to provide feedback to the user. In this search form, depending on which input you fill, other inputs validators should be updated to have enought information to complete the search.

**Comment by dylhunn** [comment]
Ah, OK, I suppose that is a reasonable use case. Although you're right that it's not well-supported.

**Comment by it11ah1** [comment]
Would be a very useful option also on .enable() not to enable all descendants. (This is what I expected using the onlySelf option!)

**Comment by dylhunn** [comment]
We discussed this in team triage. Thank you for your feature request, but we think this is just not likely something we are likley to budget time for in the near future. We will keep this use case in mind for upcoming design work on Forms though.
