### ISSUE TITLE
Support for XML in HttpClient

### ISSUE THREAD

**Issue by yohny** [angular/angular#46982]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

When using `HttpClient` for retrieving remote data, there are few response types available (like `json`, `arraybuffer`, `blob`, `text`), but nothing dedicated to xml. It would be handy to have a response designed to handle xml as it would make talking to XML-based backends easier (like SOAP services).
Currently to talk to XML-based backend you can use response type `text` and then parse the incoming XML on your own, but this can be avoided given that underlying `XMLHttpRequest` already has `responseXML` property that contains parsed incoming XML document that just needs to be exposed and can then directly be worked with.

### Proposed solution

Intorduce another response type `xml` that would expose underlying `responseXML` document

### Alternatives considered

Currenly retrieving xml is doable using response type `text` and then parsing it yourself, however this feature would simlify that a lot and avoid including additional xml parsing libraries/dependecies in your project.

**Comment by dylhunn** [comment]
This is something we discussed, but it would be significant scope expansion for HttpClient. At this time, we are unlikely to implement or accept this feature in Angular itself. We'd encourage you to use a third-party XML parser implementation instead.
