### ISSUE TITLE
Pass data via Input prop not working for component if data is async.

### ISSUE THREAD

**Issue by narendrasinghrathore** [angular/angular#46981]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description
1. From Parent calling API
2. Passing data from parent component to child component via Input property which is exported from different module is not working. 

ngOnChanges in child component is only returning null as currentValue.

Tried with different life cycle hooks still no success.

### Please provide a link to a minimal reproduction of the bug
https://stackblitz.com/edit/angular-ivy-s6xws9?file=src/app/app.component.ts
_No response_

**Comment by indraraj26** [comment]
Hi, 

Can you share minimal reproduction

**Comment by narendrasinghrathore** [comment]
Added in description.
https://stackblitz.com/edit/angular-ivy-s6xws9?file=src/app/app.component.ts

**Comment by EmmanuelRoux** [comment]
@narendrasinghrathore it's because you're updating a bound property inside `ngAfterViewInit`.

Btw, if you set change detection to default mode in your `AppComponent`, you will see an explicit `ExpressionChangedAfterItHasBeenCheckedError` error.

**Comment by narendrasinghrathore** [comment]
It's related to `  changeDetection: ChangeDetectionStrategy.OnPush,` when used we have to either manually trigger `changeDetectorRef.detectChages()` or in my case I have passed on observable `[inputProp]="myAsyncData | async"`

#46536

**Comment by EmmanuelRoux** [comment]
What you say is partially right, BUT it’s not related to the issue in your repro. See the explanation above…
