### ISSUE TITLE
@HostBinding sorts classes alphabetically

### ISSUE THREAD

**Issue by c-kunz** [angular/angular#46999]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

When using

```ts
@HostBinding('class')
classes = 'e b c d a';
```

the rendered HTML is:

```html
<app-root class="a b c d e"></app-root>
```

~~This can cause issues with CSS specificity resulting in wrong styles, especially when using a lot of Tailwind classes.~~

Appears to be a regression of this issue: https://github.com/angular/angular/issues/33111

### Please provide a link to a minimal reproduction of the bug

https://github.com/c-kunz/angular-hostbinding-sorts-classes

### Please provide the exception or error you saw

```true
Classes are sorted alphabetically instead of the order they were given.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.1.0
Node: 16.15.0
Package Manager: npm 8.5.5 
OS: linux x64

Angular: 14.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
```

**Comment by JelleBruisten** [comment]
By my knowledge the order in which css classes are applied does not matter for specificity, what does matter is the order in which they are defined in the CSS.

**Comment by c-kunz** [comment]
You're absolutely right, specificity in this case is defined by the order of definition in CSS.

The linked issue https://github.com/angular/angular/issues/33111 fortified my belief that it did contribute to specificity.

My original solution was based on that wrong assumption. Fortunately, I don't have any weird selector use case.

Anyhow, I think this is still an issue for very specific cases that you mentioned (having selectors like `div[class*="e b"]`).

**Comment by atscott** [comment]
Closing as won't fix. The order in which Angular applies classes should not be relied upon, as it is not guaranteed.
