### ISSUE TITLE
FormGroup.get() should only accept keys of the defined FormGroup 

### ISSUE THREAD

**Issue by DerZyklop** [angular/angular#46993]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

If I type a form like 

```typescript
public myFormGroup : FormGroup<{
  foo: …
  bar: … 
}>
```

I can do `this.myFormGroup.get('keyThatDoesNotExist')` without any error. I expected an error because my type definition clearly says that only the keys `'foo'` and `'bar'` exist.

### Proposed solution

The class FormGroup has a `get` definition like this:

```typescript
get<P extends string | (readonly (string | number)[])>(path : P) : …;
```

I think this can be solved by simply change string to keyof TControl

```typescript
get<P extends keyof TControl | (readonly (keyof TControl | number)[])>(path : P) : …;
```

I tested it. Afterwards it gives the expected error:
`Argument of type '"keyThatDoesNotExist"' is not assignable to parameter of type '"foo" | "bar" | readonly (number | "foo" | "bar")[]' `

### Alternatives considered

–

**Comment by jnizet** [comment]
get also accepts a path: `complexFormGroup.get('user.companies.0.address.street')`. https://angular.io/api/forms/AbstractControl#get

**Comment by DerZyklop** [comment]
@jnizet Right. Thanks for that hint. So a path makes it difficult to get rid of the parameter type `string`. But i think the path could probably also be strongly typed with a [template literal type](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html).

**Comment by dylhunn** [comment]
You should be getting an `AbstractControl<never>`, so actually using the result of `get` should produce type errors.

I agree it would have been better to just return `never` directly, but unfortunately, it was unimplementable due to compiler performance issues. See [my attempt to tighten the types in this PR](https://github.com/angular/angular/pull/46115).
