### ISSUE TITLE
Is data passed to @Input property is passed as value or passed by reference

### ISSUE THREAD

**Issue by narendrasinghrathore** [angular/angular#46992]
### Description

I am using an array in child component which is passed as `@Input` property from parent.
Making any change in child component is also reflecting in parent.

Please update the same in documentation. [Input](https://angular.io/api/core/Input)

### Please provide the steps to reproduce the issue

https://stackblitz.com/edit/angular-ivy-exb6dl?file=src/app/child/child.component.html

**Comment by RAJEEV2510** [comment]
It is passed by reference not value .

**Comment by alxhub** [comment]
@RAJEEV2510 is (sort of) correct.

JavaScript is a pass-by-value language - there is no concept of pass-by-reference. Objects and arrays though are not themselves primitives, but rather pointer types. This means that a value that points to an object (e.g. `const x = {prop: true}`) passed to a function (`foo(x)`) results in the function having access to the same object that the original variable `x` does. That is, the object in memory is [_aliased_](https://en.wikipedia.org/wiki/Aliasing_(computing)).

There is no update to our documentation needed, as this behavior is fundamental to the JS language and not Angular specifically.
