### ISSUE TITLE
Testing: Asynchronous code fails without sleep

### ISSUE THREAD

**Issue by 11joselu** [angular/angular#47006]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Hello :)

I have a component that allows images uploading, once the user adds an image, it emits an event (_the parent should handle it_), but doing some unit test over that component I'm not able to pass the test without doing some sleep (wait for event to be triggered).

[See reproduction](https://stackblitz.com/edit/angular-14-async-code-testing?file=src%2Fapp%2Fapp.component.ts)

I tested:

- With waitForAsync + async fn -> **FAIL**
- With waitForAsync + await whenStabale fn -> **FAIL**
- With fakeAsync + tick -> **FAIL**
- With fakeAsync + flush -> **FAIL**
- With fakeAsync + flushMicrotasks -> **FAIL**
- With fakeAsync + whenStable -> **FAIL**
- Native async with sleep -> **PASS**

I'm missing something or doing something wrong? 🙏🏽 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-14-async-code-testing?file=src%2Fapp%2Fapp.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
My env info:

Angular CLI: 14.1.0
Node: 18.2.0 (Unsupported)
Package Manager: npm 8.9.0 
OS: linux x64

Angular: 14.1.0
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.1
@angular-devkit/build-angular   14.1.0
@angular-devkit/core            14.1.0
@angular-devkit/schematics      14.1.0
@schematics/angular             14.1.0
rxjs                            7.5.6
typescript                      4.7.4
```

**Comment by jessicajaniuk** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
