### ISSUE TITLE
ChangeDetectionStrategy.OnPush is not running with @Input parameter passing inside ng-content

### ISSUE THREAD

**Issue by GirishReddyMS** [angular/angular#47001]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I have two components, checkbox-group(parent) and checkbox(child), here I am able to propagate data from parent component to child component but change detection is not happening when I use onPush. 

Checkbox template - 
@Component({
  selector: 'checkbox-f',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="a-checkbox-group">
      <input
        class="a-checkbox"
        type="checkbox"
        [id]="key"
        [value]="value"
        [checked]="isChecked()"
        (change)="toggleCheck($event)"
      />
      <label [for]="key">
        <ng-content></ng-content>
      </label>
    </div>
  `,
})

Checkbox-group template - 
 
@Component({
  selector: 'checkbox-group',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="a-form-element">
         <label class="a-title">label</label>
        <ng-content></ng-content>
      </label>
    </div>
  `,
})

### Please provide the exception or error you saw

```true
No error produced, Only Change detection is not getting triggered when we use ChangeDetectionStrategy.OnPush
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 13.3.0
Node: 16.14.1
Package Manager: npm 8.5.0
OS: win32 x64

Angular: 13

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1303.0 (cli-only)      
@angular-devkit/core         13.3.0 (cli-only)        
@angular-devkit/schematics   13.3.0 (cli-only)        
@schematics/angular          13.3.0 (cli-only)
```

**Comment by pkozlowski-opensource** [comment]
Please provide a minimal reproduce scenario using stackblitz - otherwise this issue is not actionable for us.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
