### ISSUE TITLE
Canonical: Automatically generate Forms control types from model type

### ISSUE THREAD

**Issue by JustDoItSascha** [angular/angular#47004]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

Sometimes you want to pass the value of a form to another function, like in a service. When you have created a Interface for the form which looks like this:

```
expert interface LoginForm {
  username: FormControl<string>,
  password: FormControl<string>
}
```

Then the `form.value` type looks like this `{username: string, password: string}`. But you have no possibility to pass this type the a service function, only by copying it:

```
performLogin(credentials: {username: string, password: string}) {...}
```

But there is a type for that: ɵFormGroupValue, but it's marked as "internal use only". Why? It would look like this:

```
performLogin(credentials: FormGroupValue<LoginForm>) {...}
```

### Proposed solution

Make ɵFormGroupValue public available.

### Alternatives considered

-

**Comment by dylhunn** [comment]
We actually [did this](https://github.com/angular/angular/pull/45978), but ended up rolling it back. It would be a lot more useful to go in the other direction, from model to controls, but this is impossible in the general case. Here's why:

Consider you have a data model that represents a date:

```
interface Date {
  day: number;
  month: string;
  year: number;
}
```

This could correspond to a form with three fields:

```
{
  day: FormControl<number>;
  month: FormControl<string>;
  year: FormControl<number>;
}
```

Or it could correspond to a datepicker widget, which is a single custom control which returns an object:

```
FormControl<{
  day: number;
  month: string;
  year: number;
}>
```

And it's impossible to know which generally!

If you have forms that never have object-valued controls like this, it's absolutely possible to write a custom type to generate control types from value types -- you can do it using a [mapped type](https://www.typescriptlang.org/docs/handbook/2/mapped-types.html).

This would be something good to improve in the future, but the design for how to solve it is unclear.

**Comment by dylhunn** [comment]
Actually, I'm going to close this in favor of marking #46864 as the canonical issue.

**Comment by JustDoItSascha** [comment]
@dylhunn I understand what you want to say, but that was not what I was asking for ;-) It could make sense to go the way from model to controls, but I just want to pass the form value to a function to handle it and want to type the arguments of this function.

And you have a Mapped Type for it, but don't make it publicly available and even in the other issue you linked, there is no reason why you make it private. Or better, no other reason then "it's not ideal". But "not ideal" is better than nothing.
