### ISSUE TITLE
Silent fail of preprendering

### ISSUE THREAD

**Issue by chernodub** [angular/angular#47039]
# 🐞 Bug report

Hi guys, firstly, I wanted to say thanks for your hard work, truly appreciate that 🙌 

#### What modules are related to this issue?

- [x] **builders**, but I'm not sure
- [ ] common
- [ ] express-engine

### Is this a regression?

Probably, no

### Description

So, I was playing around with the prerendering feature, but faced an issue - some of my routes were empty after prerendering script was executed successfully (a pre-rendered page contained only `<router-outlet></router-outlet><!---->` instead of the component's template). 
It seems that I was able to track it down. The issue only appears when I'm using `localStorage` in the component, but, I guess that could also be affected by the usage of any browser-specific API. 

I believe that `prerender` script should either fail or show some kind of warning in case non-existent API (in the context of server) is used.

## 🔬 Minimal Reproduction
1. Initialize app via latest Angular CLI
2. Add universal
3. Add a new route/component. E.g.: a lazy module `dashboard`
4. Call `localStorage.getItem` in the constructor of the new component
5. Call prerender script (`npm run prerender -- --routes /dashboard /`)
6. See `dist/unversal-test/browser/dashboard/index.html`, there is content from `src/app/dashboard/dashboard.component.html`. And, there are no errors/warnings in the console

Here is the repository where I reproduced the issue, https://github.com/chernodub/ng-universal-reproduced-prerender-issue
This is a breaking change https://github.com/chernodub/ng-universal-reproduced-prerender-issue/commit/656945bd4ad78e085f89fa30ad3d3c8e5acdc524, without it, prerender works fine

## 🔥 Exception or Error

No error or warning, **that's the problem**. In case the application is somehow complex/advanced it may be very hard to understand, why prerender didn't work :(

## 🌍 Your Environment
- [Dependencies](https://github.com/chernodub/ng-universal-reproduced-prerender-issue/blob/master/package.json)
- MacOS Monterey 12.4

**Comment by alan-agius4** [comment]
After looking a bit into this, it appears that the router is not re-throwing the error 

Basically the below is not working as intended.
https://github.com/angular/angular/blob/d583f85701b0424496e263bf1cbc2c619869437e/packages/router/src/router.ts#L1398-L1402

**Comment by atscott** [comment]
@alan-agius4 Can you provide some more details? This will throw an error in the browser. Why is the prerender not throwing?

**Comment by atscott** [comment]
I updated the router bundle  in `node_modules` so the `scheduleNavigation` always just returns `Promise.reject('lkajsdflkjasdf')` and there is no error in the prerender. If I update the function to `throw 'some error'`, then it _does_ cause the prerender to fail. This seems like an issue outside of the Router code.

**Comment by atscott** [comment]
I don't know why the rejected promise is getting swallowed during prerendering. You can at least solve this in user-space by always logging the router errors to the console:

```
RouterModule.forRoot(routes, {
    initialNavigation: 'enabledBlocking',
    errorHandler: (e) => {
      console.error(e);
      throw e;
    }
}
```

**Comment by alan-agius4** [comment]
@atscott, while the above is a workaround, it's far from ideal and it doesn't solve the root cause and would require a migration to update all users that are using universal. 

One thing that caught my eye is that in the router that are a number of floating promises. 

Example: 

```
```

**Comment by alan-agius4** [comment]
@atscott, I debugged this a bit more and as suspected this is indeed the caused by the floating promises. 

I tried to remove a number of floating promises (By patching the `node_modules` directly) and did indeed result in the error to bubble up correctly.

**Comment by alan-agius4** [comment]
This issue surfaced again in https://github.com/angular/universal/issues/3061

**Comment by alan-agius4** [comment]
This should no longer be an issue in version 16 which is currently in pre-release. 

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
