### ISSUE TITLE
scroll back to top is missing

### ISSUE THREAD

**Issue by mohammadaltamas** [angular/angular#47036]
### Description

When i am at bottom of the doc then i can't go bottom to top.
![issue](https://user-images.githubusercontent.com/48707190/182781107-0e213f4f-3215-48bb-a1d4-ad4d35c643d3.png)

### Proposed solution

So for that i think there is either back to top button or back to top there should be.
![btt](https://user-images.githubusercontent.com/48707190/182780215-485972e3-e417-431d-9f7e-22404811471c.png)

### Alternatives considered

Just need back to top

**Comment by atscott** [comment]
We appreciate your suggestion. If you want to implement this, we'd be open to reviewing a PR. Closing since this would be lower priority than just about any other improvement we could make so we wouldn't invest time in it ourselves.
