### ISSUE TITLE
Fix internal typescript build step to allow node-style resolution

### ISSUE THREAD

**Issue by robwormald** [angular/angular#4704]
Current build process uses "classic" style module resolution inside the broccoli tree, and this prevents usage of es6 style imports internally:

works
```typescript
var Observable = require('@reactivex/rxjs')
```
does not work
```typescript
import {Observable} from '@reactivex/rxjs' //cannot find module @reactivex/rxjs
```
This prevents leveraging the new-style typings resolution inside our build step, and prevents (for example) using Observable / Subject and/or extending/inheriting from it (a la EventEmitter)

discussed with @alexeagle IRL

**Comment by jeffbcross** [comment]
Is there a proposed resolution to this?

**Comment by robwormald** [comment]
proposed resolution would be to use node-style resolution and relative paths internally, but @alexeagle said it would take a couple of fixes to make that work. i'll let him comment further on the how.

**Comment by jeffbcross** [comment]
@alexeagle FIX IT NOW

**Comment by rolandjitsu** [comment]
@alexeagle it looks like there might be a [fix](https://github.com/Microsoft/TypeScript/issues/5039) for this on the way.

**Comment by jeffbcross** [comment]
I think this is fixed, closing unless @robwormald says otherwise. Judging by the imports https://github.com/angular/angular/blob/389ed2d941a0b9ef950b76576ae54bc18d0ed68a/modules/angular2/src/core/facade/async.ts#L6

**Comment by rolandjitsu** [comment]
@jeffbcross or @robwormald may I know how was this fixed? I have the same issue in my projects.
