### ISSUE TITLE
Input attribute for autofocus have no effect

### ISSUE THREAD

**Issue by quranc** [angular/angular#47043]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Using the `autofocus` attribute on an `<input>` element is having no effect when using property binding.
It does not change the behaviour, no matter of values.

Not working:
`<input [attr.autofocus]="true"/>`

Working:
`<input autofocus/>`

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-uizk56?file=src/app/app.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.7
Node: 16.13.1
Package Manager: npm 8.12.1 
OS: darwin arm64

Angular: 14.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.7
@angular-devkit/build-angular   14.0.7
@angular-devkit/core            14.0.7
@angular-devkit/schematics      14.0.7
@angular/cdk                    14.0.6
@schematics/angular             14.0.7
ng-packagr                      13.0.8
rxjs                            7.5.6
typescript                      4.7.4
```

### Anything else?

The element seems to only support that you have the attribute `autofocus` or not.
You do not seem to be able to set it as a value (true/false), similar of what you can with `disabled`.
With other words, this will not remove the effect of the attribute:
`<input autofocus="false"/>`

I believe it might boil down to this problem and what could be done is that:
The attribute is used when`<input [attr.autofocus]="true"/>`
The attribute is not used when `<input [attr.autofocus]="null | undefined | false"/>`

**Comment by atscott** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

If you're using static attributes, there's no reason to bind with `attr.`
