### ISSUE TITLE
Rephrasing lazyloaded modules' injector inheritance

### ISSUE THREAD

**Issue by 4javier** [angular/angular#47059]
### Description

> The router adds all of the providers from the root injector to the child injector. When the router creates a component within the lazy-loaded context, Angular prefers service instances created from these providers to the service instances of the application root injector.
> 
> Any component created within a lazy loaded module's context, such as by router navigation, gets the local instance of the service, not the instance in the root application injector.

https://angular.io/guide/providers#limiting-provider-scope-by-lazy-loading-modules

Reading this extract the way is currently formulated, it makes people think a lazy loaded module's component will always get **a new copy of the service**, even if no lazy module provider is overriding its root one.
It looks like RootInjector's providers get **cloned** into ChildInjector and not just referenced.

### What is the affected URL?

https://angular.io/guide/providers

**Comment by atscott** [comment]
Agreed, this could be clarified better. Would you be willing to create a PR to update this?

**Comment by 4javier** [comment]
Yes, I'll take care of it soon.

**Comment by 4javier** [comment]
@atscott 
Re-reading this paragraph, it looks to me not only misleading, but completely wrong.
Did I misinterpreted how injector inheritance works, or this assertion is conceptually wrong and not just misphrased?

> Any component created within a lazy loaded module's context, such as by router navigation, gets the local instance of the service, not the instance in the root application injector. Components in external modules continue to receive the instance created for the application root.

I wanna be sure to not edit a page inserting incorrect informations.
It's clearly referring to inherited providers, and saying that lazy loaded modules gets a distinct instance of the service than eagerly ones.

**Comment by atscott** [comment]
@4javier The documentation was likely written at a time before the `providedIn` feature for injectables. So it was probably more of the case then that injectables were written as `{provide: x, useClass: XImpl}` so any child module that imports a module with that same provider would be an injector boundary where a new instance would get created.

The documentation also often _attempts_ to describe something confusing and complicated in a simple way. I don't think it always gets this right.

Here's an example app with a few instances of a provider: https://stackblitz.com/edit/angular-ivy-vcewyq?file=src%2Fapp%2Fapp.module.ts,src%2Fmain.ts

Essentially any location where a service is specifically listed as a provider becomes a boundary where a new instance might be used (of course, the details are again not quite that clear because you might have `useExisting`).

**Comment by 4javier** [comment]
@atscott 
Ouch. I got to admit I was not used to bootstrapping and provideRoutes, but I think I got the gist.
At this point I'd be more inclined to rewrite the whole paragraph of that page. 
I'd reorganize it this way, tell me what you think about the idea:
two macro-block of providing system `@NgModule/Routes` and `@Injectable`

**@NgModule/Routes**

- Plain old `providers` array in `@NgModule`: every declarable declared inside the module share the same provided instance,
in case the module is the root module (AppModule by default), every lazy loaded module will inherit that
- `Routes.providers`: every component bound to this routes or to its children share the same provided instance
- `provideRoutes` inside `@NgModule.providers` array: component bound to routes passed as argument share the same provided instance of the services listed into the same providers array

**@Injectable**

- `providedIn: 'root'`: a single instance of the service will be provided among the whole app's modules
- `providedIn: 'any'`: a distinct instance will be provided for every child injector 
- `providedIn: ModuleName`: a single instance will be provided for the declarable of the specified module

I would take a little bit more time to extend with a bit of explanation.
Let me know.

**Comment by 4javier** [comment]
@atscott 
Ouch. I got to admit I was not used to bootstrapping and provideRoutes, but I think I got the gist.
At this point I'd be more inclined to rewrite the whole paragraph of that page. 
I'd reorganize it this way, tell me what you think about the idea:
two macro-block of providing system `@NgModule/Routes` and `@Injectable`

**@NgModule/Routes**

- Plain old `providers` array in `@NgModule`: every declarable declared inside the module share the same provided instance,
in case the module is the root module (AppModule by default), every lazy loaded module will inherit that
- `Routes.providers`: every component bound to this routes or to its children share the same provided instance
- `provideRoutes` inside `@NgModule.providers` array: component bound to routes passed as argument share the same provided instance of the services listed into the same providers array

**@Injectable**

- `providedIn: 'root'`: a single instance of the service will be provided among the whole app's modules
- `providedIn: 'any'`: a distinct instance will be provided for every child injector 
- `providedIn: ModuleName`: a single instance will be provided for the declarable of the specified module

I would take a little bit more time to extend with a bit of explanation.
Let me know.

**Comment by atscott** [comment]
@4javier Unfortunately I think we’re getting too deep into the specifics of injector hierarchies. I would say the docs here should be even  _less_ descriptive, but actually just state what’s really happening. 


Ie something more like:
LoadChildren which returns an NgModule creates a new EnvironmentInjector with the module’s providers. A new EnvironmentInjector is also created if a Route has providers. For more info about injector hierarchies, refer to the injector hierarchy guide (link).

**Comment by 4javier** [comment]
Ok. 
I'll take this path.
Worth noting that hierarchical injector page makes no mention about `Route.providers` array and `provideRoutes` function, so it should probably be extended.
