### ISSUE TITLE
Router can no longer be optionally injected

### ISSUE THREAD

**Issue by dzonatan** [angular/angular#47051]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

This was broken in #46914 (released in v14.1.0).

You can no longer optionally inject a `Router` service:

```ts
  constructor(@Optional() private router: Router) { }
```

without importing `RouterModule` (or `RouterTestingModule`) results into:

```
ERROR NullInjectorError: R3InjectorError(AppModule)[Router -> UrlSerializer -> UrlSerializer -> UrlSerializer]: 
  NullInjectorError: No provider for UrlSerializer!
```

Our use case is that we have some general purpose components which have different logic based on the existence of the router.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.1.1
Node: 16.15.1
Package Manager: npm 8.11.0
OS: darwin arm64

Angular: 14.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.1
@angular-devkit/build-angular   14.1.1
@angular-devkit/core            14.1.1
@angular-devkit/schematics      14.1.1
@schematics/angular             14.1.1
rxjs                            7.5.6
typescript                      4.7.4
```

**Comment by atscott** [comment]
The router being optionally injectable was not defined or documented behavior of the Router. Making it a providedIn: root service aligns with the direction of best practice for Injectables. 

I would suggest using a different optionally provided token for your behaviors.

**Comment by atscott** [comment]
@dzonatan can you describe what you’re trying to do with the optional router a bit more concretely? Let’s work together to find a more appropriate solution.

**Comment by atscott** [comment]
Note that the error was a legitimate issue and is fixed by https://github.com/angular/angular/commit/c7fed38cf0fbf072182ec666415ea50f8e84f7f7

However, that isn't really the problem you're trying to work around here since you'll just always get a `Router` when you attempt to inject it. Another option would be to optionally inject `ActivatedRoute` instead. That would work immediately for you, but it's still relying on the details of the Router/RouterModule implementation that I don't think is really the right solution.

**Comment by dzonatan** [comment]
Sorry for the late reply but this https://github.com/angular/angular/commit/c7fed38cf0fbf072182ec666415ea50f8e84f7f7 actually fixes the use case for us. ✌🏻
