### ISSUE TITLE
Angular web component directive its not working

### ISSUE THREAD

**Issue by VarunKumarPalugula** [angular/angular#47071]
### Which @angular/* package(s) are the source of the bug?

elements

### Is this a regression?

No

### Description

I am trying to convert angular components to angular web component, I followed few articles to do it which is good, but when I tried to convert angular directive as web component it throws some error which I am not able to figure out what is wrong I am doing, also I don't have any idea on can we convert an angular directive to angular web component. Below is code which I tried to convert directive as web component.

**Tooltip Directive:**
@Directive({
  selector: '[tooltip]'
})
export class TooltipDirective {
constructor(private el: ElementRef) {
     this.el.nativeElement.classList.add('my-tooltip');
    }
}

**Creation of tooltip web components snippet:**
export class AppModule implements DoBootstrap {
constructor(private injector: Injector) {}
ngDoBootstrap() {    
     const webTooltip = createCustomElement(TooltipDirective, {
         injector: this.injector,
    });
    customElements.define("web-tooltip", webTooltip);
   }
}
How I am trying to use in app HTML file is below code
**Web tooltip selector:**
<span **web-tooltip** id="tooltip" content="This is a tooltip.">
    <web-icon icon="help"></web-icon>
</span>

![image](https://user-images.githubusercontent.com/51329333/183354973-9bc4e064-f5d0-4286-8183-563675656877.png)

**If I try to write same code for any component its working fine but for directive as I shown code above its not working.**

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.9
Node: 14.16.1
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 13.3.11
 animations, common, compiler, compiler-cli, core, elements
 forms, localize, platform-browser, platform-browser-dynamic
 router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.9
@angular-devkit/build-angular   13.3.9
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.3.9
@angular/cdk                    13.3.9
@angular/cli                    13.3.9
@schematics/angular             13.3.9
ng-packagr                      13.3.1
rxjs                            7.5.6
typescript                      4.6.4
```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

Custom elements are registered by their tag name; you can't treat them as directives that attach themselves to an element based on the presence of an attribute.

**Comment by VarunKumarPalugula** [comment]
HI @JoostK
Thankyou for your quick response..

One Confirmation does angular web components  not have support for angular directive?
