### ISSUE TITLE
expose static data from components in templates

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#4707]
We need a way to read the static data, of the component, in the template itself. We also need a way to reference static data from the resolved decorators e.g. `RouteConfig` or any other decorator added by any other 3rd party module. 

for example the current workaround
```typescript
@Component({
  template: `
    <div>{{ App.greetings }}</div>
    <div>{{ constructor.greetings }}</div>
  `
})
export class App {
  App = App;
  static greetings: string = 'oh hai';
}
```
plnkr
http://plnkr.co/edit/SEVHBacgnN2Fe07FHLDt?p=preview
plnkr with constructor
http://plnkr.co/edit/JK1FbSomU15KgKU64Tr1?p=preview

might be related https://github.com/angular/angular/issues/4041
related https://github.com/angular/angular/issues/9962

**Comment by pkozlowski-opensource** [comment]
Related / same as #4340

**Comment by gdi2290** [comment]
I'm mistaken, static data is available in `constructor`

**Comment by vicb** [comment]
Dup of #9962
