### ISSUE TITLE
Headers are getting switched to lazyUpdate

### ISSUE THREAD

**Issue by alucardu** [angular/angular#47074]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

While using Cypress (10.4.0) to test my Angular (10.1.6) application my headers get changed. This doesn't happen in production, only during tests.

![image](https://user-images.githubusercontent.com/779921/183382847-86a9f081-6402-43ae-9314-42d3b40fe98b.png)

As you can see in the image at the top log we have headers but in the bottom log the headers are empty but the `lazyUpdate` headers is filled. 

Which causes an error:
![image](https://user-images.githubusercontent.com/779921/183383176-2f60da81-4a51-4c9d-829f-3636a93905f5.png)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.2
Node: 16.16.0
Package Manager: npm 8.11.0
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1301.2 (cli-only)
@angular-devkit/core         13.1.2 (cli-only)
@angular-devkit/schematics   13.1.2 (cli-only)
@schematics/angular          13.1.2 (cli-only)
```

**Comment by JoostK** [comment]
Angular 10 is no longer supported. It looks like you're setting a header with a `null` value, which is not accepted by the type system of `HttpHeaders.set`. Please check your usages of this method to avoid setting a null value.
