### ISSUE TITLE
[class]="classExpression" is not working in Angular 12.2.16

### ISSUE THREAD

**Issue by K-Vishwak** [angular/angular#47086]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description
```
<p [class]="{'blue-color': isBlue, 'red-background': isRed}">Test</p>
<p [class]="['red-background', 'blue-color']">Test</p>

```

both the types not working as expected. 

### Please provide a link to a minimal reproduction of the bug

https://codesandbox.io/s/morning-hill-t6tevq?file=/src/app/app.component.html

### Please provide the exception or error you saw

```true
Both styles mentioned in expression should be applied.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular version: 12.2.16
```

**Comment by indraraj26** [comment]
Looks like bug in codesandbox. Can you share minimal reproduction via github.

I just tested in stackblitz and it is working as expected.

https://stackblitz.com/edit/angular-ivy-cf2srw?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.css

**Comment by JoostK** [comment]
Object values require the use of the `NgClass` directive, you can't bind objects to the string-based `class` property.

**Comment by K-Vishwak** [comment]
> Looks like bug in codesandbox. Can you share minimal reproduction via github.
> 
> I just tested in stackblitz and it is working as expected.
> 
> https://stackblitz.com/edit/angular-ivy-cf2srw?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.css

Yes. Thanks.

**Comment by K-Vishwak** [comment]
> Object values require the use of the `NgClass` directive, you can't bind objects to the string-based `class` property.

Please refer: https://angular.io/guide/class-binding

**Comment by JoostK** [comment]
> > Object values require the use of the `NgClass` directive, you can't bind objects to the string-based `class` property.
> 
> 
> 
> Please refer: https://angular.io/guide/class-binding

Ooh, sorry, I stand corrected! Glad that this seems to be a Code sandbox issue then.
