### ISSUE TITLE
Docs: Duplicate topic heading on dependency-injection page

### ISSUE THREAD

**Issue by NanditaVora** [angular/angular#47108]
### Description

On the dependency-page [URL](https://angular.io/guide/dependency-injection), there are two topics with the same heading 'Providing Dependency'. 
Can you please get it corrected?

### What is the affected URL?

https://angular.io/guide/dependency-injection

### Please provide the steps to reproduce the issue

To view the issue reported you may visit the page on the link https://angular.io/guide/dependency-injection

### Please provide the expected behavior vs the actual behavior you encountered

The paragraph that explains how the dependency can be consumed could be titled `Injecting Dependency`

**Comment by sonukapoor** [comment]
Closing this as the corresponding PR was merged.
