### ISSUE TITLE
Injector.get throws when default value is provided (when inject flags are present)

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#47109]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

The injector.get documentation explains the usage of the notFoundValue and how it is handled.

https://github.com/angular/angular/blob/bb6e11c7e4927b0bb4da9f636bc1a2aca49c95b3/packages/core/src/di/injector.ts#L48-L53

But the implementation requires the usage of InjectorFlags.Optional

https://github.com/angular/angular/blob/bb6e11c7e4927b0bb4da9f636bc1a2aca49c95b3/packages/core/src/render3/di.ts#L335-L342

### Please provide the exception or error you saw

```true
Error: NG0201: No provider for NgControl found in NodeInjector. Find more at https://angular.io/errors/NG0201
    at throwProviderNotFoundError (node_modules\@angular\core\fesm2020\core.mjs:254:11)
    at notFoundValueOrThrow (node_modules\@angular\core\fesm2020\core.mjs:3349:9)
    at lookupTokenUsingModuleInjector (node_modules\@angular\core\fesm2020\core.mjs:3384:12)
    at getOrCreateInjectable (node_modules\@angular\core\fesm2020\core.mjs:3486:12)
    at NodeInjector.get (node_modules\@angular\core\fesm2020\core.mjs:3661:16)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
The implementation didn't change on the master branch.

Angular CLI: 13.3.9
Node: 16.14.2
Package Manager: npm 8.5.0
OS: win32 x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.9
@angular-devkit/build-angular   13.3.9
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.3.9
@angular/cli                    13.3.9
@schematics/angular             13.3.9
ng-packagr                      13.3.1
rxjs                            7.5.6
typescript                      4.6.4
```

**Comment by bob-watson** [comment]
I added `core:di` as the documentation is in the code and not in the docs source.
I'm not sure if that means it should have other labels, as well.

**Comment by AndrewKushnir** [comment]
@CSchulz I've created a quick demo to illustrate some of the cases around the default value:

https://stackblitz.com/edit/angular-ivy-j7gpll?file=src%2Fapp%2Fapp.component.ts

The behavior looks correct and corresponds to the docs.

Could you please provide additional information about your proposal on how to improve the docs?

**Comment by CSchulz** [comment]
Thanks for the example, in my case I used the InjectFlags.Host modifier:

    const d = injector.get(NON_PROVIDED_TOKEN, 'default value', InjectFlags.Host);
    console.log('d: ', d);

**Comment by AndrewKushnir** [comment]
@CSchulz thanks for additional information. This actually looks like a bug: it's unexpected that the `injector.get` would throw in this case:
```
const d = injector.get(NON_PROVIDED_TOKEN, 'default value', InjectFlags.Host);
```
I've also updated [my Stackblitz demo](https://stackblitz.com/edit/angular-ivy-j7gpll?file=src%2Fapp%2Fapp.component.ts). I update labels on this issue as well.
