### ISSUE TITLE
Test runner does not execute code when using spy

### ISSUE THREAD

**Issue by paddotk** [angular/angular#47111]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When using a spy (with `spyOn()`), the spied-on function prevents its code from being run. So

```ts
// mycomponent.spec.ts
const fixture = TestBed.createComponent(MyComponent);
const component = fixture.componentInstance;
const myspy = spyOn(component, 'someFunc');

// when
doSomething();

// then 
expect(myspy).toHaveBeenCalled(); // Success
expect(component.someValue).toBe(true); // Fail
```
```ts
// mycomponent.ts
someFunc = () => {
  console.log('hello?');
  this.someValue = true;
}
```

When spying on `someFunc`, the spy works for its intended purpose (seeing whether it's been called), but then immediately quits before running the code within. So any other checks, such as the second `expect` in this example, fail. Removing the spy makes the code run as expected.
The same goes for e.g. a console.log I put at the top of that function, so it's not just the actual check that somehow fails.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.3
Node: 16.14.2
Package Manager: npm 8.12.1
OS: win32 x64
```

**Comment by jnizet** [comment]
That's the default behavior of jasmine spies: they replace the function with a function that does nothing (other than recording the calls being made). 
You need to call `.and.callThrough()` on your spy if you want the original method to be called.

**Comment by JoostK** [comment]
You'd likely need to configure the spy to call the original implementation using `spyOn(...).and.callThrough()`.

This is Jasmine behavior and otherwise unrelated to Angular, so I'll go ahead and close this. Feel free to continue the conversation below.

**Comment by paddotk** [comment]
Ah I see, that works, thanks. Is this documented somewhere? Because I couldn't find it.
