### ISSUE TITLE
Rename RootTestComponent to ComponentFixture

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#4711]
Filing issue after discussion with @juliemr 

Take a look at this simple example unit test.
```ts
builder.createAsync(TestApp).then(rootTestComponent => {
  let instance = rootTestComponent.debugElement.componentInstance;
  let element = rootTestComponent.debugElement.nativeElement;
  
  // Do some stuff
  rootTestComponent.detectChanges();

  // Assert some stuff

  async.done();
});
```

Presently, the distinction between `RootTestComponent` and `DebugElement` is hard to define. Calling the former a component fixture, however, makes its role a bit more clear.

cc @mhevery

**Comment by mhevery** [comment]
Agreed!
