### ISSUE TITLE
Allow inclusion of files from node_modules in component styleUrls

### ISSUE THREAD

**Issue by calebdwilliams** [angular/angular#47117]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

I would like to be able to pull in styles from `node_modules` via the `styleUrls` property on the `Component` init object.

### Proposed solution

Modify the `Component` decorator to allow for the following feature

```typescript
@Component({
  /** Interesting config settings */
  styleUrls: ['@scope/package-name/path/to.(css|scss|etc)']
})
export class InterestinComponent {}
```

### Alternatives considered

Currently this can be enabled if you are using Sass or another preprocessor, but that doesn't account for all use cases or provide the same developer ergonomics.

**Comment by crisbeto** [comment]
Supporting this in `styleUrls` would be tricky, because we'd have to duplicate the npm resolution algorithm. You should be able to achieve the same like this:

```
const styles = require(''@scope/package-name/path/to.(css|scss|etc)'');

@Component({
  /** Interesting config settings */
  styles: [styles]
})
export class InterestinComponent {}
```
