### ISSUE TITLE
Injector cant load module from ng11 library  ( using angular 13)

### ISSUE THREAD

**Issue by shaulnaim** [angular/angular#47125]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

if i have an angular app version 12 and above that tries to load a library that uses angular 11.
using Injector.get(Module)  will throw error and the only way to make it work is to upgrade the lib to 12 and above. is there another work around for this?

```javascript
function createTileComponentFactory(manifest, moduleDef, injector, additionalProviders) {
    try {
        const { rootModule } = manifest;
        // Resolve the module
        if (!moduleDef.hasOwnProperty(rootModule)) {
            throw new Error(`Unable to locate rootModule on tile module: '${rootModule}' does not exist.`);
        }
        const dynamicModule = moduleDef[rootModule];
        // Create injector context
        const injectorRef = additionalProviders
            ? (0,_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵcreateInjector"])(dynamicModule, injector, additionalProviders)
            : (0,_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵcreateInjector"])(dynamicModule, injector);
        // Invoke the module via the injector
        const tileModule = injectorRef.get(dynamicModule);
        // Init the tile -- initTile hook forces the module to load its root module
        const componentFactory = tileModule.initTile();  // *** throws error  on tileModule**/
        return componentFactory;
    }
    catch (error) {
        throw new Error(`Unable to load tile. Reason: ${error.message}`);
    }
}
```

### Please provide a link to a minimal reproduction of the bug

none

### Please provide the exception or error you saw

```true
Uncaught (in promise): Error: Unable to load library. Reason: Cannot read properties of undefined (reading 'resolveComponentFactory')Error: Unable to load tile. Reason: Cannot read properties of undefined (reading 'resolveComponentFactory')"
```

### Anything else?

Angular CLI: 13.3.9
Node: 12.22.1
Package Manager: npm 6.14.12
OS: win32 x64

Angular: 13.3.11

**Comment by pkozlowski-opensource** [comment]
I don't think we've got enough info here to help (more specifically, not sure what `tileModule.initTile()` does. Could you please share a GitHub repo with a minimal reproduce scenario?

**Comment by alxhub** [comment]
Also, your listed example is calling private APIs in Angular (`ɵcreateInjector`). These APIs may very well change between Angular major versions -- even between patch versions. There is no guarantee of backwards compatibility in private APIs.

**Comment by JoostK** [comment]
Closing as no reproduction is available. Please open a new issue with reproduction if the problem persists.
