### ISSUE TITLE
Angular 14 Cors issue

### ISSUE THREAD

**Issue by shivaji33** [angular/angular#47124]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Angualr 14 throwing CORS even though my node project handling cors using cors npm package, i tried creating proxy.conf.json but no use

![angular cors issue 1](https://user-images.githubusercontent.com/52051484/184116909-f8d5a265-42b1-44ae-9449-6a879aa33977.png)
![angular cors issue 2](https://user-images.githubusercontent.com/52051484/184116916-26101a4c-12c8-4301-a1be-7040ddcc6fe0.png)
![angular cors issue 3](https://user-images.githubusercontent.com/52051484/184116920-724ec875-d6a1-44f8-975c-f51efdf01260.png)
![angular cors issue 4](https://user-images.githubusercontent.com/52051484/184116921-07b6560d-36e2-4932-9b0e-b85c6630a52d.png)

**Comment by Totati** [comment]
We have a `proxy.conf.js` like this:
```javascript
const PROXY_CONFIG = [
  {
    context: ['/api/v1/'],
    target: 'http://127.0.0.1:8085',
    secure: false,
  }
];
module.exports = PROXY_CONFIG;
```
We are using the version 14.1.0 .

**Comment by shivaji33** [comment]
> We have a `proxy.conf.js` like this:
> 
> ```js
> const PROXY_CONFIG = [
>   {
>     context: ['/api/v1/'],
>     target: 'http://127.0.0.1:8085',
>     secure: false,
>   }
> ];
> module.exports = PROXY_CONFIG;
> ```
> 
> We are using the version 14.1.0 .

can you elaborate plz, in you node project ? if yes where did you using that PROXY_CONFIG export ?

**Comment by Totati** [comment]
![image](https://user-images.githubusercontent.com/17689719/184121053-f0d0a9e8-ef31-4924-a29b-146b5706a20c.png)

**Comment by shivaji33** [comment]
> ![image](https://user-images.githubusercontent.com/17689719/184121053-f0d0a9e8-ef31-4924-a29b-146b5706a20c.png) We use it only during development. :X

what about if we want host the application in server

**Comment by shivaji33** [comment]
i have tried the above solution but still getting the same error

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
