### ISSUE TITLE
(forms) Add a new property validValue for FormGroup<T> that will return a valid object T if the FormGroup is valid.

### ISSUE THREAD

**Issue by Fafnur** [angular/angular#47122]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

In the current implementation of forms, it is impossible to get a valid object of the desired type.

If you create a login form like as here - [Angular Docs](https://angular.io/guide/typed-forms#formgroup-and-formrecord):

```
interface LoginForm {
    email: FormControl<string>;
    password: FormControl<string>;
}

const login = new FormGroup<LoginForm>({
    email: new FormControl('', {nonNullable: true}),
    password: new FormControl('', {nonNullable: true}),
});

```

Then you can get object with type:

```
 const loginValue: Partial<{ email: string, password: string }> = login.value;
```

Validators can change in a FormGroup. And the interface without Partial `{ email: string, password: string }` cannot be retrieved.

### Proposed solution

The main idea is to make FormGroup read-only where validators cannot be changed. This allows control of the interface type if the FormGroup is valid.

For example:

```
interface LoginForm {
    email: FormControl<string>;
    password: FormControl<string>;
}

const login = new FormGroup<LoginForm>({
    email: new FormControl('', {nonNullable: true}),
    password: new FormControl('', {nonNullable: true}),
}, { nonChangeable: true });

```

Then you can get object with type:

```
if (this.login.valid) {
  const loginValidValue: { email: string, password: string } =  login.validValue;
}  
```

If the formGroup is not valid, then `validValue` may return null or a partial value.

### Alternatives considered

I looked at the current issues, but did not find anything similar.

**Comment by jnizet** [comment]
Hi @Fafnur 

The type of `value` is a Partial, not because of validators, but because controls can be disabled, and the value of a disabled control does not appear in the value of its form group. If you call `getRawValue()` though, you'll get back an object of type `{ email: string; password: string; }`.

**Comment by Fafnur** [comment]
@jnizet It works, thanks.
