### ISSUE TITLE
Better documentation/introduction for ng update

### ISSUE THREAD

**Issue by eneajaho** [angular/angular#47133]
### Description

The first thing you see in google search results for "ng update" is this page: [https://angular.io/cli/update](https://angular.io/cli/update).

Because code migrations (for breakages, deprecations, etc) is one of the biggest selling points for Angular, I would say that it needs more content and explanations than what it has for the moment. 

### What is the affected URL?

https://angular.io/cli/update

**Comment by jessicajaniuk** [comment]
We're currently working on an overhaul of aio which you can follow #47047 for details.
