### ISSUE TITLE
upload/list file on s3 bucket

### ISSUE THREAD

**Issue by minhlongmt183** [angular/angular#47139]
Edit by @JoostK: _Redacted_

**Comment by JoostK** [comment]
Thanks for reporting. I have redacted the issue description for now. Please report these kinds of issues using security@angular.io. I have posted this internally for follow-up.

**Comment by minhlongmt183** [comment]
I'll keep this in mind. I appreciate you informing me.

**Comment by pkozlowski-opensource** [comment]
Thnx for the report @minhlongmt183 - I'm going to close this issue here and follow up internally as well come back to you.

**Comment by jelbourn** [comment]
I can confirm that this is not our AWS bucket. (We do not, in fact, use AWS at all)

**Comment by minhlongmt183** [comment]
:( :( :(  Thank you for letting me know about it.
