### ISSUE TITLE
Wrong character of @angular/core-Component

### ISSUE THREAD

**Issue by xiangergou** [angular/angular#47138]
### Description

1. The translation of China that '下免得例子创建了一个带有两个数据绑定属性的组件'  should be '下面的...'
2. There is a translation deficit in 'https://angular.cn/api/core/Component#setting-component-inputs'.

### What is the affected URL?

https://angular.cn/api/core/Component#setting-component-inputs

### Please provide a screenshot if possible

<img width="982" alt="image" src="https://user-images.githubusercontent.com/26449624/184277061-73c558aa-07db-4074-bc27-511a110e959d.png">
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/26449624/184277084-f4a177f8-d3da-45d4-99c3-b9d075c81a5c.png">

**Comment by xiangergou** [comment]
<img width="929" alt="image" src="https://user-images.githubusercontent.com/26449624/184277364-e66cbdd4-6236-42ce-8df0-6727b70c10a1.png">

**Comment by xiangergou** [comment]
https://angular.cn/guide/component-interaction#intercept-input-property-changes-with-a-setter
通过 setter 截听输入属性值的变化  => 通过 setter 监听输入属性值的变化

**Comment by pkozlowski-opensource** [comment]
angular-cn is not maintained here, please open in https://github.com/angular/angular-cn

**Comment by xiangergou** [comment]
> angular-cn is not maintained here, please open in https://github.com/angular/angular-cn

ok， thanks
