### ISSUE TITLE
Form controls are not shown - very annoying bug

### ISSUE THREAD

**Issue by alvipeo** [angular/angular#47146]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

Let's say I have a reactive form and I have a switch which shows/hides some dependent inputs. But when for those dependent inputs FormControls are not defined, those controls do not show up on the UI. And THERE IS NO error, which is really annoying!

See the [stackblitz](https://angular-ivy-1vwhz7.stackblitz.io). On the form, click on a [Have Plates] button.

To see the problem in code, open **_app/components/form-view.component.ts_** and see my comment.

The problem is the error:
> Cannot find control with name: 'licPlatesHowMany'

only shows up in the console when the project is running in the stackblitz, but it does NOT show up when running the project locally (ng serve)! It was really hard to find! Please make sure the error is ALWAYS generated in the console.

### Please provide a link to a minimal reproduction of the bug

https://angular-ivy-1vwhz7.stackblitz.io

### Please provide the environment you discovered this bug in (run `ng version`)

```true
see the stackblitz
```

**Comment by JoostK** [comment]
The StackBlitz reports an error that appears unrelated to the reported issue, but it does mean that it's not currently actionable. The error I get is `TypeError: Right hand side of instanceof is not an object` reported by the Luxon date adapter, as Luxon is not available.

You also mention that the problem does _not_ occur in Stackblitz, yet that is the only reproduction you have provided. Can you share a Github repro with a minimal reproduction for us to investigate? Thanks.

**Comment by KingMario** [comment]
Downloaded it and run with `ng serve`. While click [Have Plates] button got the error:

```
main.js:1 ERROR TypeError: Cannot read properties of null (reading '_rawValidators')
    at _E (main.js:1:152821)
    at Cg (main.js:1:167147)
    at Sc (main.js:1:165992)
    at n.addControl (main.js:1:173621)
    at n._setUpControl (main.js:1:176621)
    at n.ngOnChanges (main.js:1:175969)
    at n.Wk (main.js:1:20640)
    at yI (main.js:1:24973)
    at Uy (main.js:1:24774)
    at Ou (main.js:1:24494)
```

**Comment by alvipeo** [comment]
Sorry, the project involved but it's easy to replicate. Basically, I created a Reactive Form with a template which contains, for example, 10 fields (inputs). Then I started working on a form code and started adding validation. But I added, let's say only 5 out of 10:

```
   frm = this.fb.group<VehicleRegistrationData>({
      vin: new FormControl<string>("", { validators: [Validators.required], nonNullable: true }), // , updateOn: "blur"
      year: new FormControl<number | null>(null, { validators: [Validators.required] }),
      make: new FormControl<string>("", { nonNullable: true }),
      model: new FormControl<string>("", { nonNullable: true }),
      bodyType: new FormControl<string | null>(null),
      licPlatesHowMany: new FormControl<number | null>(null),
      licPlatesValue: new FormControl<string | null>(null),
      sellerAddr: this.fb.group<UsAddressControls>({
         zipCode: new FormControl<number | null>(null),
         state: new FormControl<string>("", { nonNullable: true }),
         city: new FormControl<string>("", { nonNullable: true }),
         // ==> these were not added yet ==> county: new FormControl<string | null>(null),
         // ==> these were not added yet ==> street1: new FormControl<string>("", { nonNullable: true }),
         // ==> these were not added yet ==> street2: new FormControl<string | null>(null),
         // ==> these were not added yet ==> suite: new FormControl<string | null>(null)
      })
   });
```
and run the project. While it works, the controls which are present in the template __but not defined for the `FormGroup`__ are not becoming visible (by switching with `*ngIf`).

**Comment by JoostK** [comment]
I'm sorry, but it's still unclear (to me, at least) what your exact setup is. The stacktrace that @KingMario shared indicates an optimzied production build, where development checks have mostly been removed.

**Comment by jessicajaniuk** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
