### ISSUE TITLE
CanDeactivate guard documentation doesn't state when "nextState" can be undefined

### ISSUE THREAD

**Issue by MinaFayez9** [angular/angular#47153]
### Description

I can't find in any place in the documentation a reference for when "nextState" property of the "CanDeactivate" might be sent by undefined and what is the logic behind it, so could you please explain it here and update the documentation about it ?

### What is the affected URL?

https://angular.io/api/router/CanDeactivate

**Comment by atscott** [comment]
In reality, this should _not_ be typed as an optional parameter. `nextState` was added in https://github.com/angular/angular/pull/13560 and the argument passed was never potentially `undefined` as far as I can tell.
