### ISSUE TITLE
Rename `I18nSelectPipe`

### ISSUE THREAD

**Issue by d-koppenhagen** [angular/angular#47158]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

Angular provides the built-in pipe `I18nSelectPipe`. The name of this pipe is quite confusing as the use case for i18n mappings (e.g. `male`, `female`, etc.) is just one. The pipe can be used to map any value against a key.
The current name suggests that the pipe is somewhat specific for i18n features but it isn’t.

### Proposed solution

The pipe should be renamed to: `select`

### Alternatives considered

- `selectValue`
- `map`
- `mapValue`

**Comment by fmalcher** [comment]
IMO the same applies for i18nPlural: It is not really useful for i18n in the sense of supporting different languages.

**Comment by d-koppenhagen** [comment]
I totally agree. I think, the `i18nPlural` pipe is quite similar.
It will also select a value based on the key. The special thing here is that it will expect the ICU plural format (`=0`, `=1`, `=2`) as a key, but also selects just the referenced value.
IMO `i18nPlural` could be removed completely and it's implementation could be used as an option handled by the renamed `i18nSelect` pipe (`select:"icu"`, `select:'icu':'en-US'`).

**Comment by d-koppenhagen** [comment]
@pkozlowski-opensource maybe this issue is also/more related to `comp: common` (label)

**Comment by AndrewKushnir** [comment]
@d-koppenhagen my understanding is that the I18nSelectPipe and I18nPluralPipe classes exist to support the ICU-like functionality in element attributes and properties in a template (ICUs are not supported in attributes/properties, see #21615), thus they have the `I18n` prefix. Technically, they would not be needed once ICUs are supported in attributes/properties, so I'm closing this ticket with a reference to #21615 (which talks about ICUs).
