### ISSUE TITLE
FormBuilder should have a record method

### ISSUE THREAD

**Issue by james-schwartzkopf** [angular/angular#47159]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

Currently the only way to create a FormRecord is using the constructor, FormBuilder should have a method to create one.  

### Proposed solution

Add a record method to FormBuilder

### Alternatives considered

You can still create one using new FormRecord, but it's an odd omission from FormBuilder

**Comment by jnizet** [comment]
That's already done: https://next.angular.io/api/forms/FormBuilder#record, https://github.com/angular/angular/pull/46485

**Comment by pkozlowski-opensource** [comment]
Ohh, good catch, thnx @jnizet
