### ISSUE TITLE
AsyncTestCompleter should be exported in angular2/testing (a.42)

### ISSUE THREAD

**Issue by r-park** [angular/angular#4715]
`AsyncTestCompleter` is no longer being exported in `angular2/test` and `angular2/testing`.

**Comment by rolandjitsu** [comment]
Indeed, it looks like it's missing. So is `SpyObject`.

**Comment by ludohenin** [comment]
[here](https://github.com/mgechev/angular2-seed/blob/alpha44/app/components/about/about_spec.ts#L17) is a workaround.

**Comment by vicb** [comment]
I think that `AsyncTestCompleter` is being deprecated and replaced by `injectAsync`. @juliemr knows more - probably we should update the `inject` inline doc to remove references to `AsyncTestCompleter` and add some doc for `injectAsync` ?

**Comment by juliemr** [comment]
`angular2/testing` is new and never exported the `AsyncTestCompleter`. You want `angular2/testing_internal` if you need to use that - but yes, as @vicb says the preferred method is now `injectAsync`.

`SpyObject` should be unnecessary - you can just use Jasmine spies. It's in the internal library only to allow transpilation to dart.

**Comment by rolandjitsu** [comment]
@vicb, @juliemr I understand. I will use `injectAsync` as you suggested and I did not know that `AsyncTestCompleter ` is only used internally. As for `SpyObject`, I'll make the switch to Jasmine spies.

**Comment by larrifax** [comment]
@juliemr How should consumers setup their tests when the SUT is an observable (e.g. RxJS observable), and not a promise? `injectAsync` expects a promise to be returned from the test method, and the `AsyncTestCompleter` is supposed to be for internal use only. Is there another way of invoking something like the `done()` callback in jasmine tests?

**Comment by ludohenin** [comment]
@larrifax rxjs has a toPromise method that should do the trick I guess
