### ISSUE TITLE
feat(ServiceWorker): maxSize infinite / maxAge infinite / remove "ngsw-bypass" from query / headers

### ISSUE THREAD

**Issue by angelaki** [angular/angular#47171]
### Description

I'm interested in being able to

- set a cache maxSize of infinite
- set a cache maxAge of infinite
- getting the ngsw-bypass flag removed from query / headers before execution

Would an implementation of these features getting merged? If so, I'd offer myself to implement it.

### Proposed solution

maxSize / maxAge of string 'infinite' / -1 are getting treaded as never expire

`if (req.headers.has("ngsw-bypass") || /[?&]ngsw-bypass(?:[=&]|$)/i.test(requestUrlObj.search)) {`

`event.respondWith(modifedReq);` instead of `return` (configurateable)

### Alternatives considered

Keep as it is? Maybe someone offered already to allow infinite and it was rejected for a reason?

**Comment by gkalpak** [comment]
Thx for opening an issue, @angelaki :+1:

##
**Regarding `maxAge`/`maxSize`:**

I am not sure an `infinite` value would be a good idea to add, mainly for two reasons:
  1. It is not a good idea to try and take up infinite space (for an infinitely long time) on a client's device. Having to set an explicit limit, pushes the developer to think about what would make sense for their app. This is particularly true for data requests, which are typically dynamic in nature.
  2. In the rare cases where it makes sense to have practically infinite `maxAge`/`maxSize`, it is easy to work around it by setting very high values. Like, caching 1 million requests for 100 years is practically infinite for every use-case today (and in the foreseeable future) :smiley:

Therefore, I think it would be better to not add a special value for infinite `maxAge`/`maxSize`.

##
**Regarding removing `ngsw-bypass`:**

It is unfortunately not possible to modify the request in any way (such as removing a header/query value) and not handle the request. If the ServiceWorker had to modify the request, it would have to handle it (even if just passing it through to the server), which would by large beat the purpose of `ngsw-bypass`.

Additionally, it is not always possible to replicate exactly a request that comes from the browser. There are certain request types that cannot be replicated programmatically (for example, a request with [mode: navigate][1]). Thus, it wouldn't even be possible in some cases to modify the request to remove `ngsw-bypass` without drastically changing the request.

##
Based on the above, I am going to close this issue, but feel free to continue the discussion below (or open a new issue if you have more ideas on potentially useful ServiceWorker features to discuss).

[1]: https://developer.mozilla.org/en-US/docs/Web/API/Request/mode#value

**Comment by angelaki** [comment]
Yeah, you're probably right with your answers I guess - you've convinced me :)
