### ISSUE TITLE
The first letter of the day is not in uppercase in the french localized date pipe

### ISSUE THREAD

**Issue by satyamdorville** [angular/angular#47182]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Well surely this is not what We can call a critical issue 😄 but in english the day got his first letter in uppercase and not in French. I dont know for other locales. 

### Anything else?

Have a Nice day

**Comment by JoostK** [comment]
This is working as intended; the data is extracted from the CLDR datasource and the French language does not spell its days with capital letters, unlike the English language where days are capitalized. [See here, for example](https://www.rosettastone.com/languages/days-of-the-week-in-french).
