### ISSUE TITLE
Support `inject` inside host

### ISSUE THREAD

**Issue by splincode** [angular/angular#47184]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

https://github.com/Tinkoff/taiga-ui/blob/main/projects/core/components/root/root.component.ts#L24

in v12

```ts
@Component({
    selector: `tui-root`,
    templateUrl: `root.template.html`,
    styleUrls: [`./root.style.less`],
    changeDetection: ChangeDetectionStrategy.OnPush,
    providers: [TUI_IS_MOBILE_RES_PROVIDER],
    host: {
        'data-tui-version': 'version',
        '[style.--tui-duration]': `duration + "ms"`,
        '($.class._mobile)': `isMobileRes$`,
    },
})
export class TuiRootComponent {
    constructor(
        @Inject(TUI_ANIMATIONS_DURATION) readonly duration: number,
        @Inject(TUI_IS_MOBILE_RES) readonly isMobileRes$: Observable<boolean>,,
        @Inject(VERSION) readonly version: string
    ) {}
}
```

in v14

```ts
@Component({
    selector: `tui-root`,
    templateUrl: `root.template.html`,
    styleUrls: [`./root.style.less`],
    changeDetection: ChangeDetectionStrategy.OnPush,
    providers: [TUI_IS_MOBILE_RES_PROVIDER],
    host: {
        'data-tui-version': 'version',
        '[style.--tui-duration]': `duration + "ms"`,
        '($.class._mobile)': `isMobileRes$`,
    },
})
export class TuiRootComponent {
    readonly duration: number = inject(TUI_ANIMATIONS_DURATION);
    readonly isMobileRes$: Observable<boolean> = inject(TUI_IS_MOBILE_RES);
    readonly version: string = inject(VERSION);
}
```

### Proposed solution

in v14+

```ts
@Component({
    selector: `tui-root`,
    templateUrl: `root.template.html`,
    styleUrls: [`./root.style.less`],
    changeDetection: ChangeDetectionStrategy.OnPush,
    providers: [TUI_IS_MOBILE_RES_PROVIDER],
    host: {
        'data-tui-version': inject(VERSION),
        '[style.--tui-duration]': `${inject(TUI_ANIMATIONS_DURATION)}ms`,
        '($.class._mobile)':  inject(TUI_IS_MOBILE_RES),
    },
})
export class TuiRootComponent {
}
```

### Alternatives considered

inject can only be used in context, however, it creates an extra boilerplate

**Comment by pkozlowski-opensource** [comment]
Thnx for the suggestion but this is not the direction we would like to persuade as it would change the semantics of the host _bindings_. When you write an entry in the `host` object it means:
* key => property of a host element;
* value => _expression_ to be evaluated every time the change detection runs (!)

With your suggestion the `inject()` would be invoked each and every time the change detection runs and this is not our intention. The DI injection and setup should happen only during component creation, not during change detection.

I understand that the current setup adds _some_ boilerplate, but an alternative is to sacrifice the mental model _and_ performance - something we are not willing to do at this point.
