### ISSUE TITLE
Excessive change detection when calling markForCheck inside zone.run

### ISSUE THREAD

**Issue by JonWallsten** [angular/angular#47185]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I'm not sure if this is a bug or a feature, but it causes issues for us none the less.
Due to the issue with native `async/await` and `Zone.js` (https://github.com/angular/angular/issues/31730) we have created a common entry point for `markForCheck` where we always check if we are in the zone or not, and enter the zone if we are outside of it, due to some await call in the code before we trigger `markForCheck`.

```ts
public markViewForCheck (cd: ChangeDetectorRef) {
    if (!NgZone.isInAngularZone()) {
        this.zone.run(() => {
            this.markViewForCheck(cd);
        });
        return;
    }

    cd.markForCheck();
}
```

When using some simple logging we can see the following:
``` 
Initializing app
Parent template checked
Child template checked for child id 1
Child template checked for child id 2
Child template checked for child id 3
Angular is running in development mode. Call enableProdMode() to enable production mode.
Trigger manual markForCheck
Trigger manual markForCheck for child 1
Trigger manual markForCheck for child 2
Trigger manual markForCheck for child 3
In Angular Zone: No
Parent template checked
Child template checked for child id 1
In Angular Zone: No
Parent template checked
Child template checked for child id 2
In Angular Zone: No
Parent template checked
Child template checked for child id3
```

Removing the await instead gives us the wanted behavior:
```
Initializing app
Parent template checked
Child template checked for child id 1
Child template checked for child id 2
Child template checked for child id 3
Angular is running in development mode. Call enableProdMode() to enable production mode.
Trigger manual markForCheck
Trigger manual markForCheck for child 1
In Angular Zone: Yes
Trigger manual markForCheck for child 2
In Angular Zone: Yes
Trigger manual markForCheck for child 3
In Angular Zone: Yes
Parent template checked
Child template checked for child id 1
Child template checked for child id 2
Child template checked for child id 3
```

I'm guessing `NgZone.run` adds a micro task causing the application tick then task is resolved and the queue is empty?
What I don't understand though is how the application tick get's to run between my markForCheck calls?
I thought RxJS Subject was synchronous, hence the markForCheck calls should be synchronous?
Is it possible to achieve this in some other way? Can `NgZone.run` avoid causing an application tick?

Edit: Is the issue that the Subject can't reach the next child before an entire change detection cycle is complete? In that case, is it possible to queue up these calls somehow?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-14-mark-for-check

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.1.2
Node: 16.14.0
Package Manager: npm 8.3.1
OS: win32 x64

Angular: 14.1.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.2
@angular-devkit/build-angular   14.1.2
@angular-devkit/core            14.1.2
@angular-devkit/schematics      14.1.2
@ngtools/webpack                14.1.2
@schematics/angular             14.1.2
ng-packagr                      14.1.0
rxjs                            7.5.6
typescript                      4.7.4
webpack                         5.74.0
```

**Comment by JoostK** [comment]
It looks like you're looking for

```ts
platformBrowserDynamic()
  .bootstrapModule(AppModule, {
    ngZoneRunCoalescing: true,
  })
```

**Comment by JonWallsten** [comment]
@JoostK: We're not using the CLI so it's actually a good thing that Stackblitz behave the way it does, or I wouldn't have been able to reproduce it.
I was playing around with `ngZoneRunCoalescing: true` before when I investigated performance issues, but that time it didn't help, so I guess I removed it! 
I'll try it again. Sounds like exactly what we need. Thanks!

**Comment by JonWallsten** [comment]
@JoostK: Wow, that made some major improvement to our app in certain cases. I see improvements of at least 50% in some cases! Amazing. Thanks a lot!
