### ISSUE TITLE
Using NonNullableFormBuilders still need to use nonNullable: true option

### ISSUE THREAD

**Issue by iErKy** [angular/angular#47191]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

When creating a NonNullableFormBuilder it shouldn't let you assign default null value to FormControl's instanciated with it. 
Appart from this, even though i create the FormGroup with the NonNullableFormBuilder i still need to put the option **nonNullable: true** on each FormControl, else i the provided error TS2322, (can't reproduce this last error on the stackblitz example, but im getting it on the app im working on).

```
readonly formBuilder = inject<NonNullableFormBuilder>(NonNullableFormBuilder);

/**
error TS2322: Type 'FormControl<string | null>' is not assignable to type 'FormControl<string>'.
  Type 'string | null' is not assignable to type 'string'.
    Type 'null' is not assignable to type 'string'.

57             name: new FormControl('', {
**/
 const fb = this.formBuilder.group<PersonForm>({
      name: new FormControl( ' ', {
        validators: [Validators.required] //missing nonNullable: true
      }),
      firstName: new FormControl(
        { value: ' ', disabled: true },
        { validators: [Validators.required], nonNullable: true }
      ),
    });

//Getting same Type error if i set name default value to null
const fb = this.formBuilder.group<PersonForm>({
      name: new FormControl( null , {
        validators: [Validators.required], nonNullable: true
      }),
      firstName: new FormControl(
        { value: ' ', disabled: true },
        { validators: [Validators.required], nonNullable: true }
      ),
    });
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-uzcbsd?file=src/app/app.component.ts

### Please provide the exception or error you saw

```true
error TS2322: Type 'FormControl<string | null>' is not assignable to type 'FormControl<string>'.
  Type 'string | null' is not assignable to type 'string'.
    Type 'null' is not assignable to type 'string'.

57             name: new FormControl('', {
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.1.2
Node: 16.15.1
Package Manager: npm 8.15.0
OS: win32 x64

Angular: 14.1.2
...

Package                      Version
------------------------------------------------------
@angular-architects/ddd 	2.0.0
@angular/animations 		14.1.2
@angular/cdk 			14.1.2
@angular/common 		14.1.2
@angular/compiler 		14.1.2
@angular/core 			14.1.2
@angular/forms 			14.1.2
@angular/material 		14.1.2
@angular/platform-browser 	14.1.2
@angular/platform-browser-dynamic 14.1.2
@angular/router 		14.1.2
@microsoft/signalr 		6.0.1
@ngrx/component-store 		14.1.0
@ngrx/effects 			14.1.0
@ngrx/entity 			14.1.0
@ngrx/component 		14.1.0
@ngrx/router-store 		14.1.0
@ngrx/store 			14.1.0
@ngx-translate/core 		14.0.0
@ngx-translate/http-loader 	7.0.0
@nrwl/angular 			14.5.4
lodash-es 			4.17.21
rxjs 				7.5.0
tslib 				2.0.0
zone.js 			0.11.4
```

**Comment by JoostK** [comment]
This is expected, as you're only creating the _group_ using the form builder, not the individual controls (using `new FormControl` constructor). By using the constructor explicitly instead of going through the `NonNullableFormBuilder`, there is no way that the nullability can flow implicitly as you expected.

**Comment by iErKy** [comment]
> This is expected, as you're only creating the _group_ using the form builder, not the individual controls (using `new FormControl` constructor). By using the constructor explicitly instead of going through the `NonNullableFormBuilder`, there is no way that the nullability can flow implicitly as you expected.

@JoostK thanks for the answer i found out how to do it properly with your answer, my bad, i was doing it wrong.

```
//Like this, it works properly and i don't have to use the **nonNullable: true ** option
           this.formBuilder.control('', {
                validators: [Validators.required, Validators.maxLength(TextFieldMaxLength),
                             uniqueValueValidator(parentArray, true)]
            }),
```
Thanks!
