### ISSUE TITLE
Router briefly renders inner routes with components disregarding the ngIf condition

### ISSUE THREAD

**Issue by ilyakonrad** [angular/angular#47193]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

When a `<router-outlet>` is conditionally rendered, it briefly renders components even if there's `false` in `*ngIf`.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-6l4axr

### Please provide the exception or error you saw

```true
You have to play around with console logs and debugger to see it, which you can easily do in my stackblitz.

Logs:
1. Open the link and the console there.
2. Navigate to Route 2.
3. See the error in the console.

Debugger:
1. Open the link and the devtools.
2. Navigate to Route 2.
3. See Component 2 rendered on the page (which it should not be).

P. S. For some reason debugger doesn't stop the code when devtools are closed on Stackblitz, so make sure you open it.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.1.1
Node: 16.13.1
Package Manager: yarn 1.22.15 
OS: win32 x64

Angular: 14.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                         Version
---------------------------------------------------------    
@angular-devkit/architect       0.1401.1
@angular-devkit/build-angular   14.1.1
@angular-devkit/core            14.1.1
@angular-devkit/schematics      14.1.1
@angular/fire                   7.4.1
@schematics/angular             14.1.1
rxjs                            7.5.6
typescript                      4.7.4
webpack                         5.74.0
```

### Anything else?

There's one more thing I couldn't reproduce in Stackblitz. When stopping the code with debugger on route change event I see not only the component I shouldn't see (`<app-payments>`) but both old and new routes rendered together. Here's my app:

![image](https://user-images.githubusercontent.com/25200186/185626677-06b05191-00e5-4041-8233-f7caf4c89391.png)

Here's what it turns to once all the behind the scenes magic is done (notice no router-outlet):

![image](https://user-images.githubusercontent.com/25200186/185627934-6d5e0e79-1d0b-4a68-a674-550e508fbd3d.png)

It happens regardless of the presence of condition for the router outlet in the template.

Not sure if the whole situation is a regression.

**Comment by atscott** [comment]
This is working as intended.

When you're on the first route, your `ngIf` condition is `true` so the `router-outlet` is shown.
You navigate to the second route, the router state is updated, routes get rendered, and the NavigationEnd event happens. Then change detection runs, evaluates the parent template and finds the condition for the `ngIf` to be `false` and hides the outlet.

**Comment by ilyakonrad** [comment]
Does it mean conditionally rendered `router-outlet` is not safe to use? I find it useful to be able to stay on a restricted nested route but showing some empty state in parent, since the user might get access to that route by changing something in other part of the page.

What would be the best way to overcome this without using route guards then? I'm sure handling it in child components is not the way (my child component in the real situation is a generic table component).

Is there way for Angular to notice changes before it renders a new route?
