### ISSUE TITLE
some code not linted

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#4719]
...or something like that. [1 example is worth 1000 words](https://github.com/angular/angular/blob/f529236bfc7868c3c53438c1b20d821c12bb8d4a/modules/angular2/test/core/zone/ng_zone_spec.ts#L145)

**Comment by mprobst** [comment]
Having that one example here would save me some digging:

```ts
  describe('isInInnerZone',
           () => {it('should return whether the code executes in the inner zone', () => {
             expect(isInInnerZone()).toEqual(false);
             _zone.run(() => { expect(isInInnerZone()).toEqual(true); });
           }, testTimeout)});
```

This code is missing a semicolon after `testTimeout);`. Remember to run the linter, it catches these kinds of things.

**Comment by yjbanov** [comment]
Ha, why don't we run it on Travis?

**Comment by mprobst** [comment]
We should - maybe it happens after clang-format, or clang-format is much faster? @alexeagle to the rescue.

**Comment by alexeagle** [comment]
We do run an ASI linter.
https://github.com/angular/angular/blob/c3ab20cc87dd016517c8945b8fe0adab455cc6ed/gulpfile.js#L297
but I think the paths do not match the file in question?
https://github.com/angular/angular/blob/c3ab20cc87dd016517c8945b8fe0adab455cc6ed/gulpfile.js#L302

So I think we should be linting everything. Any objection? Will probably have a noisy commit when we turn it on.

**Comment by vicb** [comment]
outdated
