### ISSUE TITLE
DevTools components & properties are not updateing in Chrome

### ISSUE THREAD

**Issue by berndgz** [angular/angular#47202]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

DevTools components & properties are not updateing in Chrome

### Please provide the exception or error you saw

```true
DevTools components & properties are not updateing in Chrome
```

### Please provide the environment you discovered this bug in (run `ng version`)

DevTools version 1.0.6

### Anything else?

It works in version 1.0.4

**Comment by mgechev** [comment]
Hey @berndgz, thanks for reporting this issue. What Angular version are you using?

**Comment by berndgz** [comment]
Hey @mgechev i use version 11.2.7 in this project.

**Comment by JoostK** [comment]
Hey @berndgz, devtools support for Angular 11 was dropped in #45883 as v11 as it didn't yet have the APIs available to properly support devtools. Since Angular 11 itself is no longer supported you're best off migrating to Angular v12+.

**Comment by JoostK** [comment]
Closing per the above. Please open a new issue if the issue persists with Angular 12+.
