### ISSUE TITLE
removal of template driven forms

### ISSUE THREAD

**Issue by robertIsaac** [angular/angular#47204]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

template driven is a hassle for the whole Angular community, and every Angular developer needs to learn both reactive forms and template driven ones, because even if I wrote only one I will encounter some code with template driven, and I believe it's also not easy for the Angular team to keep support of both way of forms
and I think now that reactive forms are strongly typed while template driven isn't, then we have more reasons to avoid the template driven forms

and anyone has a case where template driven cover a scenario that can't be accomplished with reactive forms please state it here

### Proposed solution

to start the process of deprecation for template driven forms and after 2-3 future released of Angular to be completely removed
I believe there can be an automated migration from template driven to reactive forms, it won't be easy and probably won't cover all cases but it will make the migration easier for everyone

### Alternatives considered

none

**Comment by pkozlowski-opensource** [comment]
Thank you for sharing your thoughts @robertIsaac, appreciate it. We keep evaluating the need and pros / cons of the 2 forms systems but not ready to deprecate template driven forms at this point.

**Comment by KingMario** [comment]
Hi @pkozlowski-opensource, thanks for your decision not to deprecate template driven forms at this point.

I'd like to have your opinion about a question I raised in stackoverflow (edited).


https://stackoverflow.com/questions/73501914/what-are-the-benefits-of-reactive-form-over-template-driven-form

```
Answers to other similar questions are talking about form scalability and unit testing.

Could you please give some examples of large scaled form that cannot be made by [(ngModel)] with *ngIf and *ngFor?

About the unit testing, Angular official documentation gives samples of view-to-model and model-to-view testing cases. There ARE differences between two approaches.

But aren't those tests responsibility of @angular/forms? Why should we do such tests in our own component? Shouldn't we trust Angular while using its official mature stable modules?

--

The question is now closed as opinion-based.

Right, from my point of view, the Angular official documentation seems deliberately reducing the use of Template-Driven Form's features to reinforce its point that Reactive Form is better than Template-Driven Form. Regarding the view-to-model and model-to-view unit testing examples, shouldn't we have no doubt that both cases should work? After all, view-to-model and model-to-view are not the main job of the form we create. Even if it is a custom Value-Accessor, the relevant cases should be tested in the custom Value-Accessor, not in the Form.

Not mentioned the complexity introduced by the hierarchy of FormGroup, FormArray and FormControl over plain JavaScript object, which is ultimately just used to map the javascript object.

```

**Comment by KingMario** [comment]
Hi @robertIsaac, I don't want to be rude, but

Can you state a case where reactive cover a scenario that can't be accomplished with template driven forms?

Regarding to typed forms, two-way-binding form model is naturally typed because the model is (or can be considered as) plain JavaScript/TypeScript object.

```html
<input [(ngModel)]="loginForm.username">
<input [(ngModel)]="loginForm.password">
```

```typescript
export interface LoginForm {
  username: string;
  password: string;
}

export class MyComponent {

  loginForm: LoginForm = {
    username: '',
    password: '',
  }

  // ...
}
```

Please correct me if I'm wrong.

**Comment by robertIsaac** [comment]
@KingMario 
can you please check this simple example https://stackblitz.com/edit/angular-ivy-wc83nt?file=src/app/app.component.ts

but that's the only case, when you are building complex forms that are being part of multiple components, template driven forms are just terrible in handling them and when you have an error, it's just very difficult to debug, thought that's not my point

my point is that, as an Angular developer you shouldn't have two ways to handle the same exact thing, imagine being a junior developer joining a complex project and half of the forms are template driven and the other half are reactive forms you need to understand both of them how they are working and learn how to manage validation, marking inputs as touched, dirty, ... etc in two different ways

Angular in itself is a huge to learn adding two ways to handle forms just make things worse
