### ISSUE TITLE
ActivatedRoute doesn't work in Route Providers

### ISSUE THREAD

**Issue by jmeinlschmidt** [angular/angular#47207]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

Since ng14 introduced ability to specify Providers in Routes, it would be nice being able to use ActivatedRoute in Provider. In my case, I am using a factory where I am trying to obtain route data from ActivatedRoute and configuring my provided dependencies based on that value.

ActivatedRoute currently works only with "activated component" (see docs), therefore using it in Routes makes it unable to access the data, since the component is not active at that moment.

### Proposed solution

Make ActivatedRoute working in Route Providers.

### Alternatives considered

At this moment, the only possible solution, to make this dependencies configuration, is inside a component.

**Comment by atscott** [comment]
You can access the current router state in a provider via `router.routerState`. This allows you to access the current `ActivatedRouteSnapshot`.
