### ISSUE TITLE
Wrong variable type on type="number" ngModel binding

### ISSUE THREAD

**Issue by aceArt-GmbH** [angular/angular#47211]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

having a `[(ngModel)]` bind of string variable to an `<input>` with `type="number"` does change the run time type/does not complain about the wrong type.

Even with `"fullTemplateTypeCheck": true`, `"strictTemplates": true,` and `"strict": true,`

```ts
@Component({
  selector: 'my-app',
  styleUrls: ['./app.component.css'],
  template: `
  <input type="number" [(ngModel)]="myStringVar">
  <br>
  {{ getTypeOfMyStringVar() }}
  `,
})
export class AppComponent {
  myStringVar: string;

  getTypeOfMyStringVar(): string {
    return typeof this.myStringVar;
  }
}
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-v9mgc7?file=src%2Fapp%2Fapp.component.ts

### Please provide the exception or error you saw

```true
No exception or error was thrown, yet the type did change from declared string to number
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.8
Node: 18.7.0 (Unsupported)
Package Manager: npm 8.12.2
OS: linux x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1303.9
@angular-devkit/build-angular      13.3.9
@angular-devkit/core               13.3.9
@angular-devkit/schematics         13.3.8
@angular/cdk                       13.3.9
@angular/cli                       13.3.8
@angular/flex-layout               13.0.0-beta.38
@angular/material                  13.3.9
@angular/material-moment-adapter   13.3.9
@schematics/angular                13.3.8
rxjs                               6.6.7
typescript                         4.6.4

as well as the linked StackBlitz with Angular 14
```

**Comment by rajratnamaitry** [comment]
Hi @pkozlowski-opensource 

As per my understanding, `typeof` returns Type ``'"string" | "number" | "bigint" | "boolean" | "symbol" | "undefined" | "object" | "function"'`` and that is the string. that is why it's not complaining.

**Comment by aceArt-GmbH** [comment]
hey @rajratnamaitry,
The problem has nothing to do with `typeof`, that was just to show the problem.

`myStringVar` has the defined type `string`. So I can call any string method on it (like `charAt(0)`).
But when entering a digit into the input field, the actual variable type is `number` and a runtime error is thrown `this.myStringVar.charAt is not a function`.

The compiler and IDE think it is a string while it really is a number

**Comment by jessicajaniuk** [comment]
This is currently working as intended. `ngModel` is for template driven forms, and is inherently untyped. Type safety is guaranteed with typed reactive forms, but not with template driven forms.

**Comment by aceArt-GmbH** [comment]
![image](https://user-images.githubusercontent.com/33117017/191460365-b6b978d4-9393-4029-87f5-cbeaead5cf15.png)
