### ISSUE TITLE
angular2 ::alpha42

### ISSUE THREAD

**Issue by shatakshidixit1** [angular/angular#4722]
I am using npm version 2.11.2 and node version of 0.12.5.
when i tried to install angular2 by running npm install angular2 it throws below errors::

npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "angular2"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: angular2@'*'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["2.0.0-alpha.8.dev","2.0.0-alpha.8.prod","2.0.0-alpha.11","2.0.0-alpha.12","2.0.0-alpha.13","2.0.0-alpha.14","2.0.0-alpha.15","2.0.0-alpha.16","2.0.0-alpha.17","2.0.0-alpha.18","2.0.0-alpha.19","2.0.0-alpha.20","2.0.0-alpha.21","2.0.0-alpha.22","2.0.0-alpha.23","2.0.0-alpha.24","2.0.0-alpha.25","2.0.0-alpha.26","2.0.0-alpha.27","2.0.0-alpha.28","2.0.0-alpha.29","2.0.0-alpha.30","2.0.0-alpha.31","2.0.0-alpha.32","2.0.0-alpha.33","2.0.0-alpha.34","2.0.0-alpha.35","2.0.0-alpha.36","2.0.0-alpha.37","2.0.0-alpha.38","2.0.0-alpha.39","2.0.0-alpha.40","2.0.0-alpha.41","2.0.0-alpha.42"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shatakshi/Documents/student.42/npm-debug.log

**Comment by ericmartinezr** [comment]
Just specify the exact version you want to install

`npm install angular2@2.0.0-alpha.42`

**Comment by ericmdantas** [comment]
You want `npm i --save angular2@latest`

**Comment by shatakshidixit1** [comment]
@ericmartinezr  npm install angular2@2.0.0-alpha.42 worked. Thanks

**Comment by ericmartinezr** [comment]
@ericmdantas didn't know that one, I'll keep it in mind, is much easier than specifying the version, thanks :+1:

**Comment by ericmdantas** [comment]
:smile:
