### ISSUE TITLE
angular2.d.ts no longer references es6-shim.d.ts nor jasmine.d.ts

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#4723]
It looks like the typings from `bundles/typings/angular2/angular2.d.ts` from the npm distribution is no longer referencing:
```plain
/// <reference path=".../es6-shim/es6-shim.d.ts">
/// <reference path=".../jasmine/jasmine.d.ts">
```
Is that intentional or just something gone wrong during builds?

**Comment by mhevery** [comment]
I think that is intentional.
