### ISSUE TITLE
ActivatedRoute.children doesn't return available named outlets sort by the order of adding them to the route

### ISSUE THREAD

**Issue by RezaMakvandi** [angular/angular#47239]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I add multiple named outlet routes and in page reload I want to get them back in ActivatedRoute.children sort by the order of adding them to the route. All called named outlet routes are available in ActivatedRoute.children but not in the order of adding them to the route.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular Cli : 14.0.4
Node: 14.17.5
```

**Comment by billfern23** [comment]
test
