### ISSUE TITLE
Zone.js not working with MessageChannel

### ISSUE THREAD

**Issue by fragsalat** [angular/angular#47237]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Zone.js seem to not monkey patch MessageChannel which leads to microtasks scheduled with it not having the correct zone. You have a test using iframes but not with directly posting a message.

Simple reproducable example
```
import "zone.js";

function microtask(cb) {
  const mc = new MessageChannel();
  mc.port1.onmessage = cb;
  mc.port2.postMessage(null);
}

Zone.current.fork({ name: "my root" }).run(() => {
  console.assert(Zone.current.name === "my root");
  microtask(() => console.assert(Zone.current.name === "my root")); // fails
});

```

I would expect Zonejs to monkey patch messagechannel post message to keep the zone context.

### Please provide a link to a minimal reproduction of the bug

https://codesandbox.io/s/zone-message-channel-gr0j2j?file=/src/index.js:0-322

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Zone.js latest
Any browser
```

**Comment by flash-me** [comment]
Hi @fragsalat 

there is a patch for `MessagePort` for zone.js that you can load. 

See available patches here: https://github.com/angular/angular/tree/main/packages/zone.js/plugins

How to apply patches:
https://github.com/angular/angular/tree/main/packages/zone.js#bundles

Just add this import
```ts
import "zone.js";
// MessagePort Zone.js Patch
import "zone.js/dist/zone-patch-message-port.js";
```

Example:
https://codesandbox.io/s/zone-message-channel-forked-les65j?file=/src/index.js

cheers
flash ⚡

**Comment by fragsalat** [comment]
Hey, sorry I came back to this so late. This is already quite good but the problem with the patch implementation I see is that it picks up the zone at the time where the onMessage listener is bound and not where the postMessage is fired. But that's the case in React. It has a global queue and a processing function which is registered right after importing the react files. 

```
  var channel = new MessageChannel();
  var port = channel.port2;
  channel.port1.onmessage = performWorkUntilDeadline;

  schedulePerformWorkUntilDeadline = function () {
    port.postMessage(null);
  };
```

later the `schedulePerformWorkUntilDeadline` is executed to schedule an async queue processing task. As the listener is bound in the root scope, the following tasks always have the root scope. In an ideal scenario I would rather see a patch on the postMessage function to update the task on the MessagePort. I updated the example with this use case.
https://codesandbox.io/s/zone-message-channel-forked-n1yvu2

**Comment by fragsalat** [comment]
I created my own patch to keep the zone in the event handler which was used at the time calling postMessage. May it's interesting for you.
```ts

type PatchedMessage = { originalMessage: unknown; zoneName: string };
type PatchedMessagePort = MessagePort & { zones: { [zoneName: string]: typeof Zone.current } };

const MessagePort = (global as any)['MessagePort'];
if (typeof MessagePort !== 'undefined' && MessagePort.prototype) {
  Object.defineProperty(MessagePort.prototype, 'zones', {
    configurable: true,
    enumerable: true,
    value: {},
  });

  // Custom message handler to pick up zone from patched event and execute callback in it
  function handleMessage(this: PatchedMessagePort, callback: unknown, event: MessageEvent) {
    const isPatchMessage = (message: unknown): message is PatchedMessage =>
      typeof message === 'object' && message !== null && 'zoneName' in message;

    if (typeof callback !== 'function') {
      return;
    }
    if (isPatchMessage(event.data)) {
      this.zones[event.data.zoneName].run(() => {
        const unpackedEvent = new MessageEvent('message', {
          bubbles: event.bubbles,
          source: event.source,
          data: event.data.originalMessage,
          composed: event.composed,
          origin: event.origin,
          lastEventId: event.lastEventId,
          cancelable: event.cancelable,
        });
        callback(unpackedEvent);
      });
    } else {
      callback(event);
    }
  }

  // Patch onmessage property to wrap event listener and get Zone name from event data
  const originalOnMessageDesc = Object.getOwnPropertyDescriptor(MessagePort.prototype, 'onmessage');
  Object.defineProperty(MessagePort.prototype, 'onmessage', {
    configurable: originalOnMessageDesc?.configurable,
    enumerable: originalOnMessageDesc?.enumerable,
    set(callback: unknown) {
      originalOnMessageDesc?.set?.call(this, handleMessage.bind(this, callback));
    },
    get() {
      return originalOnMessageDesc?.get;
    },
  });

  // Patch postMessage to pass zoneName to custom message handler
  const nativePostMessage = MessagePort.prototype.postMessage;
  MessagePort.prototype.postMessage = function patchedPostMessage(message: unknown) {
    this.zones[Zone.current.name] = Zone.current;
    nativePostMessage.call(this, { originalMessage: message, zoneName: Zone.current.name });
  };
}
```

**Comment by JiaLiPassion** [comment]
@fragsalat , I am not quite understand your use cases.
So in my understanding, `MessagePort` created a channel and listen on a port, so the other page can communicate through this channelby `postMessage` to this `port`. So the `onmessage` and the `postMessage` should happen in different pages for most use cases.

And the policy of zone.js is to keep the `Zone` when the listener is registered, so now the `zone` when `onmessage` is set will be used in the `message callback`.

And yeah you can create your own patch, but maybe I didn't catch your use case about whey you need to know the  zone when `postMessage` happened.

**Comment by fragsalat** [comment]
The use case is actually one of the most used use cases world wide for frontend applications. React^^
React uses an internal queuing system to schedule rendering tasks. This queue uses several ways to schedule microtasks depending on the system. First it tries to use setImmediate, as this is usually not supported it tries to use MessageChannel and lastly falls back to setTimeout. 

https://github.com/facebook/react/blob/977bccd24de2b062d2c114e6cf160d2bd9ed9493/packages/scheduler/src/forks/Scheduler.js#L619
https://github.com/facebook/react/blob/977bccd24de2b062d2c114e6cf160d2bd9ed9493/packages/shared/enqueueTask.js#L43

The reason they decided for MessageChannel seem to be because setTimeout seem to have a 4ms delay for scheduling. So starting a Zone and calling a state setter doesn't keep the Zone in the following render. Anyhow I solved it with my own patch.
