### ISSUE TITLE
Error on $ in angular-protractor.d.ts

### ISSUE THREAD

**Issue by basvandenheuvel** [angular/angular#4725]
Hi,

I'm getting an error on 
```
declare var $: cssSelectorHelper; 
```
in the `angular-protractor.d.ts` of angular alpha 42. 
( I just upgraded from .37 to .42, so i don't know if this problem is there since 38.. 39 .. 40...) 

I think it conflicts with the `jquery.d.ts` which exports the `$`.

I'm using VisualStudio 2015. The error i get is `Build: Subsequent variable declarations must have the same type. Variable '$' must be of type 'JQueryStatic', but here has type 'cssSelectorHelper'.`

Does anyone have a solution? Commenting the line seems like a workaround but doesn't feel right.

**Comment by jessegood** [comment]
@basvandenheuvel : See https://github.com/angular/angular/issues/4507. Sorry I don't know the solution for Visual Studio though.

**Comment by basvandenheuvel** [comment]
Thanks, I indeed wasn't able to solve this problem in VS. I just commented the line in the .d.ts file...

**Comment by DennisRoam** [comment]
What is the "correct" way around this issue? I'm using the angular2 seed but added jQuery to run third party scripts and I'm hitting this issue. Commenting out is fine for now but is very hacky..

**Comment by basvandenheuvel** [comment]
@DennisRoam  They closed the issue without giving any kind of solution, sorry. At the moment i just comment the line.... The problem is if you run npm update or npm install, the file is downloaded again and you have to comment the line again. I don't understand why angular would declare a var named $ since thats JQuery's for the past years

**Comment by mbalex99** [comment]
+1 I did the hack that @basvandenheuvel said

**Comment by vladimir-ivanov** [comment]
as a workaround, since jquery does not distribute a jquery.d.ts file, the file definition of jquery.d.ts could be placed in [source-code-base-dir]/typings/jquery.d.ts
and simply change the bottom lines to:
declare module "jquery" {
    export var $:JQueryStatic;
}
//declare var jQuery: JQueryStatic;
//declare var $: JQueryStatic;

or declare a new module as such (a bit hacky):
declare module "jquery" {
    export var $:any;
}
and the error will go away (tested with webpack and ts-loader)

**Comment by devcube** [comment]
Hmm, well I'm not convinced. As @basvandenheuvel said, $ has belonged to jQuery for quite some time. I'm also having this problem and I'm hoping for a more permanent solution than to keep commenting the line in angular2 (or changing the jquery.d.ts file).

**Comment by htakemoto** [comment]
I had the same issue with $.
I downloaded "angular2": "^2.0.0-beta.2", and it worked fine.

**Comment by tonyeung** [comment]
@vladimir-ivanov's solution works
