### ISSUE TITLE
Idea: Hot reload without full reload. (preserve state)

### ISSUE THREAD

**Issue by infacto** [angular/angular#47253]
It would be great if Angular live reload works like [Flutter](https://docs.flutter.dev/development/tools/hot-reload) hot reload. Currently the live reload from Angular completly reloads the full app like a hard reload in browser. The Flutter hot reload only updates changed elements. For example: If you just change text, the route, the page, everything you see is not reloading. Only the changed text is updated. Optionally you can hard reload by a shortcut. This can improve development speed and developer satisfaction. The current behavior is better than nothing, but can be very annoying. Not sure how and if we can implement this is Angular. Webpack dev server is used, right?

**Comment by eneajaho** [comment]
Hi,
Have you tried the `--hmr` command when you serve the application? It is Hot Module Replacement. 

```bash
ng serve --hmr
```

**Comment by infacto** [comment]
Thanks for that hint. I tried it now. But it seems that the behavior is the same. In my vision I want to change some text in HTML hit CTRL + S and see the updated HTML in browser without any reload of the page.

**Comment by eneajaho** [comment]
That's what it's supposed to do, it works good with lazy loaded code as it will replace only those modules and not reload the whole page.

**Comment by akaufmann** [comment]
Angular's current HMR story is semi-optimal. Angular performs a rebootstrap and therefore cannot persist state during an HMR. This is known to the Angular CLI team. For more context see https://github.com/angular/angular-cli/issues/19233#issuecomment-717468987 and https://twitter.com/AlanAgius4/status/1558919988781645825?cxt=HHwWgoCwyYzesqIrAAAA.

**Comment by alan-agius4** [comment]
This is being tracked in https://github.com/angular/angular/issues/39367

**Comment by infacto** [comment]
@alan-agius4 #39367 is only about CSS as I see from title.
