### ISSUE TITLE
Sanitize and set innerHTML in directive when using CSP trusted-types

### ISSUE THREAD

**Issue by bjarketrux** [angular/angular#47252]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

**Goal**: I have a directive that should write to the hosts `innerHTML` after the html has been sanitized.
**Setup**: trusted-types CSP rules are enabled!

The following (abbreviated) example sanitizes the html and sets the `innerHTML` property.

```typescript
@Directive()
export class MyDirective {
  ngOnInit() {
    const rawHtml = '<b>Test</b>';
    const html = this.domSanitizer.sanitize(SecurityContext.HTML, rawHtml);
    this.renderer2.setProperty(this.elementRef.nativeElement, 'innerHTML', html);
  }
}
```

This gives a CSP error when executed in Chrome and the correct CSP rules are added to the angular.json header section:
```json
"headers": {
  "Content-Security-Policy": "trusted-types angular; require-trusted-types-for 'script';"
}
```

I would like Angular to use its `TrustedTypePolicy` (trusted_types_bypass.ts) so that a sanitized html string is not rejected.

### Proposed solution

Possible solution:
1. The `DomSanitizer` has some functionality to return `TrustedHTML`
2. Or `Renderer2.setProperty` sees that the input is of type `SafeHtml` (e.g. by using `bypassSecurityTrustHtml`) and transforms it to `TrustedHTML`

### Alternatives considered

1. If I don't need a Directive I can use property binding `<div [innerHTML]="safeHtml">...`
2. If the html structure is known I can use `renderer2` to create and add elements
3. Use `import { ɵɵsanitizeHtml } from '@angular/core'` as the sanitizer (it returns `TrustedHTML`)

I'm currently using method 3, but I worried that it's an internal function that can change without warning.

**Comment by JoostK** [comment]
Did you try using a host binding?

**Comment by bjarketrux** [comment]
No I had not. Actually I didn't think that was possible.

Revised code

```typescript
@Directive()
export class MyDirective {
  @HostBinding('innerHTML') public innerHtml?: string;

  ngOnInit() {
    const rawHtml = '<b>Test</b>';
    // const html = this.domSanitizer.sanitize(SecurityContext.HTML, rawHtml);
    // this.renderer2.setProperty(this.elementRef.nativeElement, 'innerHTML', html);
    this.innerHtml = rawHtml;
  }
}
```

This seems to be working and the HTML is sanitized.

Thanks.
I'm closing the issue, but let me know if there is a problem with this solution.
