### ISSUE TITLE
angular2 ::alpha42 is not working

### ISSUE THREAD

**Issue by shatakshidixit1** [angular/angular#4727]
***This is my index.html***

```
<!-- index.html -->
<html>
  <head>
    <head>
	  <title>Angular 2</title>
	  <script src="https://github.jspm.io/jmcriffey/bower-traceur-runtime@0.0.87/traceur-runtime.js"></script>
	  <script src="https://jspm.io/system@0.16.js"></script>
	  <script src="https://code.angularjs.org/2.0.0-alpha.42/angular2.dev.js"></script>
	</head>
  </head>
  <body>
    <!-- The app component created in app.ts -->
    <my-app></my-app>
	  <script>System.import('app');</script>
  </body>
</html>
```

***This is my app.ts***

```
import {Component, View, bootstrap} from 'angular2/angular2';


@Component({
  selector: 'my-app'
})
@View({
  templateUrl: 'app.html'

})

class MyApp {}

bootstrap(MyApp);
```

error in console is: GET https://registry.jspm.io/app.js 404 (Not Found)i @ es6-module-loader@0.16.6.src.js:2612$__Object$defineProperty.value @ es6-module-loader@0.16.6.src.js:2787n @ es6-module-loader@0.16.6.src.js:377t @ es6-module-loader@0.16.6.src.js:365$__Object$defineProperty.value @ es6-module-loader@0.16.6.src.js:2786$__global.upgradeSystemLoader.e.fetch @ system@0.16.11.src.js:739$__global.upgradeSystemLoader.e.fetch @ system@0.16.11.src.js:1806$__global.upgradeSystemLoader.e.fetch @ system@0.16.11.src.js:1921(anonymous function) @ es6-module-loader@0.16.6.src.js:1525D @ es6-module-loader@0.16.6.src.js:1183I @ es6-module-loader@0.16.6.src.js:11427.O.when @ es6-module-loader@0.16.6.src.js:9307.w.run @ es6-module-loader@0.16.6.src.js:8213.e._drain @ es6-module-loader@0.16.6.src.js:973.e.drain @ es6-module-loader@0.16.6.src.js:62t @ es6-module-loader@0.16.6.src.js:268
es6-module-loader@0.16.6.src.js:140 Potentially unhandled rejection [3] Error loading "app" at https://registry.jspm.io/app.js
Not Found: https://registry.jspm.io/app.js (WARNING: non-Error used)

***I have heard that angular alpha 42 do not need traceure so i have tried remove it but still not working***

**Comment by ericmartinezr** [comment]
@shatakshidixit1 hey, you can check this issue https://github.com/angular/angular/issues/4676 the solution that worked are for plnkr, if you want something local you have to follow @pkozlowski-opensource repo

**Comment by pkozlowski-opensource** [comment]
Yep, all the pointers are in #4676. New docs with the up-to-date getting started guide will be on-line soon.
