### ISSUE TITLE
Reload page with router + standalone components will not show the right component

### ISSUE THREAD

**Issue by PatrickWe** [angular/angular#47273]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

Currrently my webapp has the version angular 14.1.0 and everything works correctly.
My webapp uses the Standalone components with the router.

After upgrade to 14.1.3 or 14.2.0 I have the problem, if I reload the page the router will not show the correct component.
Only if I navigate in my header-component with routerLink-Directive it works.
But if I reload the full application with the refresh button in the browser, it doesn't work since Angular 14.1.3. Then my router-outlet is empty.

This is my bootstrapApplication-call:

```
bootstrapApplication(AppComponent, {
    providers: [
        importProvidersFrom(
            RouterModule.forRoot(routes, {
                scrollPositionRestoration: 'enabled',
            })
        ),
        importProvidersFrom(HttpClientModule),
        importProvidersFrom(
            HttpClientXsrfModule.withOptions({
                cookieName: 'csrf_token',
                headerName: 'X-CSRF-TOKEN',
            })
        ),
        { provide: Window, useValue: window },
    ],
}).catch((err) => console.error(err));
```

### Please provide the exception or error you saw

```true
I dont see any exceptions or errors in the logs at all.
```

### Anything else?

Angular CLI 14.1.3
or
Angular CLI 14.2.0

**Comment by pkozlowski-opensource** [comment]
@PatrickWe could you please share a minimal reproduce scenario in a stackblitz or similar?

**Comment by PatrickWe** [comment]
Unfortunately BrowserModule was imported in my AppComponent, that was my problem. Now i removed BrowserModule and it works.
