### ISSUE TITLE
Validators executed before all form values are properly set

### ISSUE THREAD

**Issue by devfservant** [angular/angular#47288]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

I have a form service with 3 fields dependent on each other: when one of them is used, the others become required.

```ts
class FormService {
  controlA: FormControl = new FormControl('', [
    requiredIfOtherIsUsedValidator(() => this.controlB),
    requiredIfOtherIsUsedValidator(() => this.controlC),
  ]);

  controlB: FormControl = new FormControl('', [
    requiredIfOtherIsUsedValidator(() => this.controlA),
    requiredIfOtherIsUsedValidator(() => this.controlC),
  ]);

  controlC: FormControl = new FormControl('', [
    requiredIfOtherIsUsedValidator(() => this.controlA),
    requiredIfOtherIsUsedValidator(() => this.controlB),
  ]);

  form = new FormGroup({
    controlA: this.controlA,
    controlB: this.controlB,
    controlC: this.controlC,
  });
}
```

I wrote a custom form validator to make it work:

```ts
/** Marks control as required if other control is not empty */
export function requiredIfOtherIsUsedValidator(
  otherControlGetter: () => AbstractControl | undefined
): ValidatorFn {
  return (control: AbstractControl): ValidationErrors | null => {
    const otherControl = otherControlGetter();
    if (otherControl) {
      const otherIsUsed = !!otherControl.value;
      if (otherIsUsed && !control.value) {
        return { required: true };
      }
    }
    return null;
  };
}
```

When I reset the form (i.e.: when all the form fields are cleared), I expect all the fields to become not required and to be valid.
This is not the case (please check the stackblitz):

![image](https://user-images.githubusercontent.com/43757707/187181562-aead33ee-09f4-469d-9e78-ae56e15d5b2d.png)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-o4y1km?file=src%2Fapp%2Futils%2Frequired-if-other-is-used-validator.spec.ts

### Please provide the environment you discovered this bug in (run `ng version`)

Stackblitz environment with latest version of Angular 14

### Anything else?

I *think* that this is a bug, but maybe it is as expected (?). If so, please explain me why 🙏
In my case, I'll go with the `setValidators` approach as a workaround.
Thank you very much for your help 🙏

**Comment by kbrilla** [comment]
There is another workaround, jsut set the validator on parent FormGroup instead, and pass both child controls to it. Then inside it use `control.setError()` - it's the way I found some time ago on some medium article. Also If You don't want to be required to initialise controls separatly to have their references, You can jsut pass a path to control and then go `(control as FormGroup).get(pathToFirstControl)` in validator

**Comment by jnizet** [comment]
That is expected: a validator on a given form control is only required to be called when that specific control value changes. To have cross-field validation, the validator needs to be set on a parent form group or array containing the dependant fields.

**Comment by AndrewKushnir** [comment]
Closing based on the comments above: for cross-field validation, the validator should be added to the parent form group, see https://angular.io/guide/form-validation#cross-field-validation.
