### ISSUE TITLE
alpha.42: HashLocationStrategy.path() should not append query params

### ISSUE THREAD

**Issue by todoubaba** [angular/angular#4729]
https://github.com/angular/angular/blob/8bc40d3f4da8244b7cd6bea2f0eeb444ecd5d676/modules/angular2/src/router/hash_location_strategy.ts#L65

If url is `http://www.example.com/path?x=y#/route`, path() returns `/route?x=y`. 
When refreshing the browser, url turns into `http://www.example.com/path?x=y#/route?x=y`.

**Comment by btford** [comment]
I actually think this is reasonable behavior.

If you're using HashLocation strategy, there shouldn't be a reason to also use query params.

On IE9, there's no way to update query params client-side without a page refresh.

Can you describe why (aside from perhaps an aesthetic preference) this is problematic to you?

**Comment by todoubaba** [comment]
`http://www.example.com/path?x=y` is my page's base url, in which `x` is not irrelevant to router or angular2.

**Comment by btford** [comment]
Do you see this behavior if you set the app base to `/path?x=y`?

There's no reason to include the domain part of the URL.

**Comment by todoubaba** [comment]
The app base url is '/', and page `/path?x=y` will preload/embed some data from server based on the param `x`. Once the page is loaded, it's just a SPA. If router params is used in the navigration, the path is `/path?x=y#/route?u=v`. It works fine before commit https://github.com/angular/angular/commit/8bc40d3f4da8244b7cd6bea2f0eeb444ecd5d676

**Comment by btford** [comment]
Ah, I see.

This has recently been refactored; I think we're consistent now. Would you mind checking (or providing a reproduction?)

**Comment by todoubaba** [comment]
@btford Here is the plunker http://plnkr.co/edit/ZNRehhKtmwtrbFtfFjny?p=preview

**Comment by btford** [comment]
This is fixed in master.
