### ISSUE TITLE
`(keyup.enter)=""` unable to capture Enter event on Android and iOS

### ISSUE THREAD

**Issue by doggy8088** [angular/angular#47294]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Today, we are suffering by a weird problem specifically on Android mobile devices. When user hit `Enter` key on a text field (`<input type="text">`), the `(keyup.enter)=""` event filtering won't be triggered. After some study, I found [this issue](https://stackoverflow.com/q/36753548/910074) on stackoverflow. I realized the Android will send keyCode with 229 first, then send keyCode 13 after that. That cause `(keyup.enter)=""` won't trigger the event.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-cn3m9s?file=src%2Fapp%2Fapp.component.ts

### Please provide the exception or error you saw

```true
There is no exception. The event simply won't triggered.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.1
Node: 16.16.0
Package Manager: npm 8.11.0
OS: win32 x64

Angular: 14.2.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.1
@angular-devkit/build-angular   14.2.1
@angular-devkit/core            14.2.1
@angular-devkit/schematics      14.2.1
@angular/cli                    14.2.1
@schematics/angular             14.2.1
rxjs                            7.5.6
typescript                      4.7.4
```

### Anything else?

Please check the following steps to reproduce the problem:

Go to my demo site: https://ng14-keyup-enter-bug.stackblitz.io/

- iOS

    Focus on `keyup.enter` field. Hit `Enter` on the virtual keyboard on iOS device. Nothing will be triggered.

    Focus on `keyup` field. Hit `Enter` on the virtual keyboard on iOS device. Everything goes fine.

- Android

    Focus on `keyup.enter` field. Hit `Enter` on the virtual keyboard on Android device. Nothing will be triggered. In my phone, it will jump to the next field.

    Focus on `keyup` field. Hit `Enter` on the virtual keyboard on Android device. Everything goes fine. I'm using Samsung S9+. But inn some other Android devices, the `keyCode` will be always be `229`.

Stackblitz source code: https://stackblitz.com/edit/ng14-keyup-enter-bug?file=src%2Fapp%2Fapp.component.ts

GitHub Repo: https://github.com/doggy8088/ng14-keyup-enter-bug

**Comment by indraraj26** [comment]
similar to this one I reported long back on ionic repo
https://github.com/ionic-team/ionic-framework/issues/22099

Looks like it is related to chromium issue

**Comment by AndrewKushnir** [comment]
As @indraraj26 mentioned, this is likely a chromium issue. As a possible workaround, you can try using the "code." modifier the event binding name (so Angular will use `code` event field instead of `key`), see https://angular.io/guide/event-binding#binding-to-keyboard-events.

**Comment by doggy8088** [comment]
I saw two typo in the doc. 

![image](https://user-images.githubusercontent.com/88981/187671599-fddb76db-286c-42d0-ae22-48cb0c623a2a.jpeg)
