### ISSUE TITLE
SSG (Static Site Generation) support for Angular

### ISSUE THREAD

**Issue by mahmoudparandeh** [angular/angular#47297]
### Description

we want angular support static site generation like React Next .js. SSG is very important for speeding up the site and preventing unnecessary API calls.

### Proposed solution

One of the developers does this. You can see Scully's GitHub for that. But, I suggest considering implementation like React Next js.

### Alternatives considered

nothing

**Comment by jessicajaniuk** [comment]
Static site generation is currently already supported in Angular Universal. You can see how to do this on [the prerendering documentation](https://angular.io/guide/prerendering). We will be taking a look at our SSR tooling, but in the meantime, this is the recommended way to do SSG with Angular.
