### ISSUE TITLE
css shimming in transformers break on rules with `calc(...)`

### ISSUE THREAD

**Issue by tbosch** [angular/angular#4730]
E.g.
```
a { height: calc(100% - 55px); }
```

Gets changed into
```
a { height: calc(;}
```

**Comment by yjbanov** [comment]
This is fixed in csslib `0.12.2`. No change in angular is necessary. I'm adding a test in #4793 for future-proofing.

**Comment by yjbanov** [comment]
This has been fixed by #4793
