### ISSUE TITLE
Angular Testing Error in v14 Compiler error Property 'configureTestingModule' does not exist on type 'TestBedStatic'.

### ISSUE THREAD

**Issue by Rstar-37** [angular/angular#47311]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I've recently started my angular project with angular 14.
Node version 16.17.0

It seems like the compiler isn't recognizing the getter inside @angular\core\testing\index.d.ts
giving the compiler error "Property or signature expected."

### Please provide a link to a minimal reproduction of the bug

https://github.com/Rstar-37/hello-world-angular-14-2/tree/master

### Please provide the exception or error you saw

```true
Compiler error Property 'configureTestingModule' does not exist on type 'TestBedStatic'.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.7
Node: 16.17.0
Package Manager: npm 8.15.0
OS: win32 x64

Angular: 14.2.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.1
@angular-devkit/build-angular   14.2.1
@angular-devkit/core            14.2.1
@angular-devkit/schematics      14.0.7
@angular/cli                    14.0.7
@schematics/angular             14.0.7
rxjs                            7.5.6
typescript                      4.8.2
```

**Comment by JoostK** [comment]
Could you please share a repro/the code that triggers this error?

**Comment by Rstar-37** [comment]
I don't that's the same problem @hamfastgamgee . 
To reproduce it, i just have to create a new project and go to the basic component test file. I can literally create a project now and share it if you're not able to reproduce it

**Comment by Rstar-37** [comment]
all I did was ng new hello-world.  and went to app.component.spec.ts to see the compiler error.
but I added the link to the reproduction to the original post.

**Comment by JoostK** [comment]
I can't repro using that repo. `ng test` succeeds and there are no errors in VS Code in the spec file.

**Comment by Rstar-37** [comment]
@JoostK  That's add, did it download version 14.2 in node modules? what typescript version are you using?

**Comment by Rstar-37** [comment]
I found what was wrong, my VS Code was using version 3.9.7 of typescript. 
![image](https://user-images.githubusercontent.com/66225821/188249723-7d4ff783-b9f9-47ec-afa0-9b37859bd280.png)
I was able to change it by clicking on it. Didn't know I had to tell VS Code which version to use
