### ISSUE TITLE
Provider UseFunction

### ISSUE THREAD

**Issue by mateusrcm** [angular/angular#47314]
### Description

The current `Provider` disponible for us are, most of the time, static, meaning that it couldn't be changed in runtime, only overwritten or used as a multiple value, the proposed solution brings an opportunity to have a `Provider`that could have its own value redefined in runtime

### Proposed solution

it would be amazing to have a provider that assign it's own value every time it's called, it coluld be declared the same as a FactoryProvider, but instead of assigning once when the module/component/injectable is created, it would assign every it's called like shown below

```TypeScript
@Service({
  providedIn: 'root'
})
export class SomeService {
  value: string = 'default' // <== mutable value
}

@NgModule({
  ...
  providers: [
    {
      provide: 'BAR',
      deps: [SomeService],
      useFunction: (ss: SomeService) => {
        return ss.value || 'value'
      },
    }
  ]
})

@Component({
  ....
})
export class FooComponent {
  constructor(@Inject('BAR') private bar: string) {}
  
  doSomething(): void {
    console.log(this.bar) // <== This should get the value everey time its called
  }
}

```

### Alternatives considered

Also, with the `FactoryResolver` itself could be used as shown above with it's own value being reassigned every time that it's called in the app

**Comment by AndrewKushnir** [comment]
Currently, when a token is injected the first time and its value is computed, the value gets stored inside the injector. Subsequent injection of the same token would result in accessing the stored value without re-computing it.

I think the use-case that you described might be implemented without changing the fundamental injector logic: you can create and inject a class that would depend on `SomeService` class instance and expose a public method to read a new value from it.
