### ISSUE TITLE
docs: guide/template-reference-variables is placed twice in the navigation

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#47337]
### Description

`guide/template-reference-variables` is placed twice in the navigation. 

<img width="276" alt="image" src="https://user-images.githubusercontent.com/1529180/188265419-d2a00b23-6f14-4f4e-8eae-9e7f44cd2b9f.png">
<img width="299" alt="image" src="https://user-images.githubusercontent.com/1529180/188265433-9466b6a9-e5c9-4b81-b902-7d65142086e5.png">

### What is the affected URL?

https://angular.io/guide/template-reference-variables

### Please provide the expected behavior vs the actual behavior you encountered

Each guide page should be placed once in the navigation because:

- it may confuse visitors that the same page is listed twice.
- it may break "current page" stuff. For example, the side nav activates the second link of the page even if I've opened the first link.

**Comment by AndrewKushnir** [comment]
FYI, closing based on https://github.com/angular/angular/pull/48829#issuecomment-1455394331.
