### ISSUE TITLE
Documentation states the incorrect default TypeScript target

### ISSUE THREAD

**Issue by TrevorKarjanis** [angular/angular#47335]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

The [documentation states](https://angular.io/guide/typescript-configuration#target) that the default TS [target](https://www.typescriptlang.org/tsconfig#target) is ES2017. However, applications generated with v14 declare ES2020.

### Please provide a link to a minimal reproduction of the bug

https://github.com/TrevorKarjanis/angular-issue-47335/blob/923cc1c264f57494c664e16f7a2528680d6aca0a/tsconfig.json#L19

### Please provide the exception or error you saw

```true
"By default, the target is es2017, which is supported in modern browsers."
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.1
```

### Anything else?

Happy Friday :smiley:

**Comment by JoostK** [comment]
Fixed in #47379
