### ISSUE TITLE
Export the createImageLoader function for custom loaders

### ISSUE THREAD

**Issue by yharaskrik** [angular/angular#47339]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

With the new `NgOptimizedImage` directive custom loaders can be created (and they work!) but the built in images are using an internal `createImageLoader` function that does some additional checks/validations. It would be awesome if the community could get access to this function as well.

### Proposed solution

Export the function in the public API

### Alternatives considered

Copy pasting existing code and reusing per directive (bad)

**Comment by pkozlowski-opensource** [comment]
Closing based on https://github.com/angular/angular/pull/47340#issuecomment-1266584142
