### ISSUE TITLE
Unable to inject standalone pipe into  a service

### ISSUE THREAD

**Issue by penfold** [angular/angular#47347]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

I have a standalone Pipe that I want to inject into a service with @Injectable({ providedIn: 'root' }).

The @Injectable decorator is missing the imports field.

Or am I missing something?

Thanks,
Paul

### Please provide the exception or error you saw

```true
At runtime I get the following error:

R3InjectorError(AppModule)[MyService -> MyStandaloneService]: NullInjectorError: No provider for CurrencySterlingPipe!.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.0
Node: 16.15.0
Package Manager: npm 8.5.5
OS: win32 x64

Angular: 14.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... youtube-player

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.0
@angular-devkit/build-angular   14.2.0
@angular-devkit/core            14.2.0
@angular-devkit/schematics      14.2.0
@nguniversal/common             14.1.0
@schematics/angular             14.2.0
rxjs                            7.5.6
typescript                      4.8.2
```

**Comment by jnizet** [comment]
IMHO, a pipe should never be injected anywhere. If you need the funtionality of the pipe outside of a template, then extract the logic of the pipe in a function and use that function everywhere you need it (including the pipe), or extract the logic of the pipe into a service, and inject that service anywhere you need it (including the pipe).

**Comment by penfold** [comment]
@jnizet In general, I agree. 

In this particular case, I am attempting to reuse the CurrencyPipe that I'm wrapping as a standalone SterlingCurrencyPipe.

I want to avoid writing my own implementation of an NG feature (i.e. the currency transform logic).

**Comment by jnizet** [comment]
Angular uses the technique I describe above, so you can simply use the formatCurrency function: https://angular.io/api/common/formatCurrency

**Comment by penfold** [comment]
Yes, this is the route I've gone down. I've wrapped this logic in a service that is either injected into a simple wrapper Pipe or directly injected into a component.

It just seems that I've written a lot of extra code because I can't import a pipe into a standalone pipe.

**Comment by pkozlowski-opensource** [comment]
As @jnizet indicates, pipes are not meant to be injectable. If needed, code sharing can happen by injecting pure functions.
