### ISSUE TITLE
NG0203 when usage TestBed on standalone component

### ISSUE THREAD

**Issue by davidNHK** [angular/angular#47345]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

When execute test from blank new generated standalone component, it show NG0203 instance of test pass.

### Please provide a link to a minimal reproduction of the bug

https://github.com/davidNHK/ngx-components/blob/main/projects/ngx-components/src/lib/dummy/dummy.component.spec.ts

### Please provide the exception or error you saw

```true
Error: NG0203: inject() must be called from an injection context (a constructor, a factory function or a field initializer). Find more at https://angular.io/errors/NG0203
	error properties: Object({ code: -203 })
	    at injectInjectorOnly (projects/ngx-components/node_modules/@angular/core/fesm2020/core.mjs:4772:15)
	    at ɵɵinject (projects/ngx-components/node_modules/@angular/core/fesm2020/core.mjs:4783:12)
	    at Object.useFactory (projects/ngx-components/node_modules/@angular/core/fesm2020/core.mjs:29583:102)
	    at Object.factory (projects/ngx-components/node_modules/@angular/core/fesm2020/core.mjs:6983:38)
	    at R3Injector.hydrate (projects/ngx-components/node_modules/@angular/core/fesm2020/core.mjs:6896:35)
	    at R3Injector.get (projects/ngx-components/node_modules/@angular/core/fesm2020/core.mjs:6784:33)
	    at injectInjectorOnly (projects/ngx-components/node_modules/@angular/core/fesm2020/core.mjs:4779:33)
	    at ɵɵinject (projects/ngx-components/node_modules/@angular/core/fesm2020/core.mjs:4783:12)
	    at initializer (projects/ngx-components/node_modules/@angular/core/fesm2020/core.mjs:6576:65)
	    at R3Injector.resolveInjectorInitializers (projects/ngx-components/node_modules/@angular/core/fesm2020/core.mjs:6833:17)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.1.3
Node: 16.14.2
Package Manager: npm 8.5.0 
OS: darwin x64

Angular: 14.1.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.3
@angular-devkit/build-angular   14.1.3
@angular-devkit/core            14.1.3
@angular-devkit/schematics      14.1.3
@angular/cli                    14.1.3
@schematics/angular             14.1.3
ng-packagr                      14.1.0
rxjs                            7.5.0
typescript                      4.7.2
```

### Anything else?

I followed create libraries section in angular docs to create the repo

**Comment by JoostK** [comment]
Running `ng test` in the repro succeeds for me:

```
Chrome 104.0.5112.101 (Mac OS 10.15.7): Executed 1 of 1 SUCCESS (0.022 secs / 0.019 secs)
```

**Comment by davidNHK** [comment]
what i can do ? feel like i can remove node_module under ngx-components as workaround . but feel like it not idel

**Comment by JoostK** [comment]
It is advisable to have a single `package.json` file throughout the repro and/or to use npm/Yarn workspaces where compatible packages are all hoisted to the `node_modules` directory in the repository root (as long as dependencies are always installed from the workspace root, instead of per individual workspace).

There's alternative approaches such as using a path mapping for `@angular/*` and mapping it into a single `./node_modules/@angular/*` directory, but I'd try to avoid having multiple copies in the first place.

**Comment by davidNHK** [comment]
coz i need to npm publish my angular library, seem single `package.json` wouldn’t make sense for me.

I will keep in mind don't do npm install under projects. Thanks for support ! 


I would suggest have some warning message when it happen :)
