### ISSUE TITLE
RouteReuseStrategy: Support iframe

### ISSUE THREAD

**Issue by zmpo** [angular/angular#47355]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

**Current behavior**

When inserting iframe in a component, the iframe content can not be reused, but the other component content can be used.

**Expected behavior**
Iframe works like the others.

### Proposed solution

I have no ideal.

### Alternatives considered

Reusing iframe may cause performance problems, i guess?

**Comment by atscott** [comment]
Closing as this is not something we'll aim to support.
