### ISSUE TITLE
No error with 'strictTemplates' and missing dependency (component using attribute selector)

### ISSUE THREAD

**Issue by etavenerInmarsat** [angular/angular#47369]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler

### Is this a regression?

No

### Description

TsConfig.json: 
```
{
  "extends": "./tsconfig.base.json",
  "angularCompilerOptions": {
    "strictTemplates": true,
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "enableResourceInlining": true
  }
}
```

No error:
![Screenshot 2022-09-07 at 11 14 29](https://user-images.githubusercontent.com/109959473/188853645-2f559a9c-568c-4af4-9070-c0de3ef467eb.png)

Error:
![Screenshot 2022-09-07 at 11 15 26](https://user-images.githubusercontent.com/109959473/188853854-875526a4-c520-43db-8889-399ea8409363.png)

'strictTemplates' doesn't seem to check inputs / components using attribute selectors. . 

In the case above, I get no error - not even runtime! The error only occurs if the template uses a dynamic template.

### Please provide the exception or error you saw

```true
I see no error, that's the issue.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Using Angular 14.
```

### Anything else?

If this is not a bug, please tell me how I can get the build to show errors when a dependancy like this is missing.

**Comment by JoostK** [comment]
This is a known limitation of type-checking; please see #46351 for details.
