### ISSUE TITLE
getBoundingClientRect() delay in ngAfterViewInit()

### ISSUE THREAD

**Issue by Kay-Yuan** [angular/angular#47366]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

A similar issue (#17588) has been closed and can not add comment. 

When I tried to use **getBoundingClientRect()** like below in my Ionic(v6) project with Angular, it will get the wrong position.
```
ngAfterViewInit() {
  oneElement.getBoundingClientRect(); 
} 
// it will return 
{
    "x": 0,
    "y": 0,
    "width": 0,
    "height": 0,
    "top": 0,
    "right": 0,
    "bottom": 0,
    "left": 0
}
```

Use **getBoundingClientRect()** in a **setTimeOut()** like below, and then it works correctly. But this is not a good idea due to unsure the internet condition in the client.
```
ngAfterViewInit() {
  setTimeOut(() => {
    oneElement.getBoundingClientRect(); 
  }, 150);     // it will return correct position, delay time varies for internet speed
}
```

I use the two elements one from `ion-page` content and the other from `<ion-tab-bar>`. I supposed it seems like due to render delay. At the time of calling **getBoundingClientRect()**, the DOM or the Page still changing.

I use this function for a dynamic tooltip with [floating-ui](https://floating-ui.com/) and a dynamic arrow with [arrows-svg](https://www.npmjs.com/package/arrows-svg). I tried Angular lifecycle and Ionic lifecycle but couldn't find a solution for dealing with attaching elements processes. Could you please give a hint of how **getBoundingClientRect()** will work as expected in which lifecycle hooks? Or how we are supposed to get the position of elements? Thanks for your time~

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.0
Node: 18.8.0 (Unsupported)
Package Manager: npm 8.18.0 
OS: darwin x64

Angular: 14.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.0
@angular-devkit/build-angular   14.2.0
@angular-devkit/core            14.2.0
@angular-devkit/schematics      14.2.0
@schematics/angular             14.2.0
rxjs                            6.6.7
typescript                      4.7.4
```

**Comment by 70u9H13** [comment]
In order to solve the issues you've come across with try using `MutationObserver`.

`ngAfterViewInit() {
    new MutationObserver((mutationList, observer) => {
      oneElement.getBoundingClientRect();
      observer.disconnect();
    }).observe(oneElement, { attributes: true });
  }`

**Comment by Kay-Yuan** [comment]
> In order to solve the issues you've come across with try using `MutationObserver`.
> 
> ```
> ngAfterViewInit() {
>   new MutationObserver((mutationList, observer) => {
>     oneElement.getBoundingClientRect();
>     observer.disconnect();
>   }).observe(oneElement, { attributes: true });
> }
> ```

Thanks for your advice, I will try it later and come back to you.

**Comment by Kay-Yuan** [comment]
> In order to solve the issues you've come across with try using `MutationObserver`.
> 
> ```
> ngAfterViewInit() {
>   new MutationObserver((mutationList, observer) => {
>     oneElement.getBoundingClientRect();
>     observer.disconnect();
>   }).observe(oneElement, { attributes: true });
> }
> ```

I just tried this function, but it doesn't listen to the CSS of element change. In my case, the attribute of element doesn't change, only the position(css) will be changed. It seems this function can't be a solution.

**Comment by pkozlowski-opensource** [comment]
As of today Angular is missing a primitive that would make reading from the DOM (relatively) safe. Opened a dedicated ticket #47432 to track those needs.
