### ISSUE TITLE
Consider switching [(prefix-foo)] to banana style ([prefix-foo])

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#4737]
I keep on making mistake of using the wrong one all the time (which currently results in frustrating silent failure #3662).

My mental model is: data-bind `prefix-foo` via `[prefix-foo]` and oh, make it two-way biding `([prefix-foo])`. While that's intuitive, it currently doesn't work.

If I wanted to switch my mental model, I would have to say: event-bind `prefix-foo-change` via `(prefix-foo-change)` and oh, make it a two-way binding `[(prefix-foo)]`.

This is a relatively big syntax change, so if we agree on this, we should have a transitional period during which both work, but `[(prefix-foo)]` prints a deprecation warning during compilation.

**Comment by IgorMinar** [comment]
btw "banana" reference comes from [functional programing papers](http://eprints.eemcs.utwente.nl/7281/01/db-utwente-40501F46.pdf) and the term is already used in F#.

cc: @vsavkin

**Comment by thelgevold** [comment]
I don't really care which one you end up with. 
However, maybe it will help change your mental model by considering the current one a "boxed" banana
[()] === a banana in a box :-)

**Comment by IgorMinar** [comment]
@thelgevold :-) that still doesn't solve the `(prefix-foo-change)` -> `[(prefix-foo)]` problem

**Comment by otodockal** [comment]
I like the idea of current style [(prop)], which is based on desugared... 

```js
<cmp [prop]="field" (prop-change)="field=$event"></cmp>
```

but, what about to have double square brackets for two-way biding? It's simple and you can't be wrong. Just an idea.

```js
<cmp [[prop]]="field"></cmp>
```

**Comment by ericmartinezr** [comment]
Personally I think it should be removed, and we should write the desugared form. It's less magical and because of the renaming now it's more confusing IMHO.

**Comment by thelgevold** [comment]
I personally wouldn't mind a meta based binding syntax

``
[firstName,{type:oneTime}]
[firstName,{type:oneWay}]
[firstName,{type:twoWay}]
``

Perhaps one of them could be the default. I know a lot of people disagree with me here, but I have always felt that one-time should be the default. Feels more natural to opt in to change tracking where it's needed as opposed to opting out where it's not needed....That is a "default" performance enhancement since it's very common to just need a one time binding to help compose a default UI.

**Comment by mhevery** [comment]
@IgorMinar havig `([foo])="exp"` would be read as on event `foo`, then you realize that it has `[foo]`. So while I see your confusion, I think you can get equally confused from the other way. To me `[(foo)]="exp"` reads binding to `exp`, ohh I see it is bidirectional.

In other words I see the two syntaxes as wash, and I don't see any one being qualitatively better then the other. My vote is to either leave it as is, or support both.

BTW, We should be throwing an error on unrecognized syntax, so the silent failure should go away.

**Comment by IgorMinar** [comment]
I can live with boxed banana :-) but we should definitely not allow both syntaxes. There is an issue for throwing an error when unrecognized syntax is found.

**Comment by mhevery** [comment]
Closing since no change is required. Once we have schema support we will complain about extra attributes to prevent this. #3769

**Comment by ThomasBurleson** [comment]
FWIW - I disagree with the decision to only throw an error for `([foo])="exp"`. Many developer will suffer from this and it is very easy to mistakenly invert the syntax order. As a compromise to ease the development burden, how about logging a warning and supporting both syntaxes? Mentally, I interpret BOTH to mean two-way data binding... or could there be any other valid interpretation ?

> Apologies in advance for commenting on a closed issue.

**Comment by thelgevold** [comment]
Lol. Boxed bananas is even a thing in the documentation now :-)
