### ISSUE TITLE
APP_BASE_HREF Multiple dynamic settings

### ISSUE THREAD

**Issue by yoonasy** [angular/angular#47388]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

I have an admin page like this
![image](https://user-images.githubusercontent.com/24489180/189168973-6ac5a2b9-3b23-4391-8743-385f4b7954ef.png)

I want to reset `APP_BASE_HREF` when I choose a language

Don't want to use `window.location.href` to refresh the page

### Proposed solution

Could you please provide a function to reset it?

looks like:

constructor(private app: App) {
  this.app.setBaseHref('/fr')
  this.router.navigate(['/foo'])
}

If there is another way that is better, sorry I haven't used angular very long

### Alternatives considered

dynamic change `APP_BASE_HREF`

**Comment by RAJEEV2510** [comment]
You can do with routing and routerLink ,it will work for your scenerio for more .
https://angular.io/guide/forms in this website url change without refresh .

**Comment by atscott** [comment]
Dynamically changing the value of APP_BASE_HREF isn't possible and won't be something we'll do. However, what you're requesting can generally be accomplished with a custom `LocationStrategy` implementation. Here's how it's used in the provided `PathLocationStrategy`: 

https://github.com/angular/angular/blob/32cad55f0d6ad2af6841e05e26a97bad9abc17cc/packages/common/src/location/location_strategy.ts#L107-L117

Your custom strategy can instead read from a service which provides a base href value that you can change programatically.

**Comment by yoonasy** [comment]
thank you very much
