### ISSUE TITLE
Supported locales

### ISSUE THREAD

**Issue by TomaszCz** [angular/angular#47402]
### Description

https://github.com/angular/angular/blob/68a6a075f4aeab1788a1bba736bfcb428cfbbacb/aio/content/guide/i18n-common-locale-id.md

We can see statement:
"The [Angular repository](https://github.com/angular/angular/tree/main/packages/common/locales) includes common locales."

I remember some time ago ( around 2020 ) that this folder contained raw files, each representing locale and the names were exactly like LCID string and it was easy to tell what was supported and what is not.  

The issue now is that locale files are generated through Bazel and are never part of the sources..
So to experiment what is supported and what not i simply try import stuff..

( I remember Norwegian being not supported )
e.g. This line is still failing:
import 'no' from '@angular/common/locales/no';
![image](https://user-images.githubusercontent.com/20865719/189598518-b915d6cb-2614-4ca9-be88-038fce287304.png)

Is there a better way? Can you update your docs after Bazel revolution to ultimately answer what locales are supported and which not?
and btw. what about Norwegian language :)

### What is the affected URL?

https://angular.io/guide/i18n-common-locale-id

### Please provide the steps to reproduce the issue

Visit docs page, see there is no supported locale list. No way to easy find this.

### Please provide the expected behavior vs the actual behavior you encountered

I need list of supported locales.

**Comment by alan-agius4** [comment]
`no` is a valid locale as in version 13+.  See: https://unpkg.com/browse/@angular/common@13.0.0/locales/no.mjs

Prior to version 13, however this used to be `nb`, More information about this can be found on the ICU blog about the changes in Norwegian locales changes in CLDR v39 https://icu.unicode.org/design/norwegian-locales-changes-in-v39

**Comment by dylhunn** [comment]
Glad to hear the `no` local issue is sorted out.

@bob-watson We no longer store the files in that dir; they are generated automatically. We could update the docs if you'd like.

**Comment by TomaszCz** [comment]
@alan-agius4 '@angular/common/locales/nb' indeed works, thank you for fast answer!

**Comment by jessicajaniuk** [comment]
Looks like theres `no` issue here. Feel free to file a new bug if you find something else.
