### ISSUE TITLE
Add an extended diagnostic when using @Input() decorator in an EventEmitter()

### ISSUE THREAD

**Issue by eneajaho** [angular/angular#47420]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler-cli

### Description

While developing web apps, most of the time we just copy and paste stuff, for example @Inputs and when we need an EventEmitter we forget to convert it to a @Output . 

### Proposed solution

Add an extended diagnostic that warns the user when uses @Input with an EventEmitter().

### Alternatives considered

None

**Comment by eneajaho** [comment]
This is something that happens all the time with devs: 
https://twitter.com/prestonjlamb/status/1569693548865519616

**Comment by jessicajaniuk** [comment]
Extended diagnostics are currently specifically _template_ diagnostics. This code is actually in the typescript class. So as it is right now, an extended diagnostic wouldn't work here. Perhaps a lint check would help here.

**Comment by CSchulz** [comment]
You can easily write such rule with ESLint, some example:
https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin/src/rules/no-input-rename.ts

**Comment by JeanMeche** [comment]
As said, this is more a job for a linting rule. Also the new signal inputs/outputs don't suffer from this issue.
