### ISSUE TITLE
 Unhandled Navigation Error: SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL

### ISSUE THREAD

**Issue by zanul-siddiqui-au3** [angular/angular#47426]
### Which @angular/* package(s) are the source of the bug?

platform-browser-dynamic, platform-browser, router

### Is this a regression?

Yes

### Description

Actually we want to serve our application from cdn all bundles and assets(images , icons , fonts etc.) but the problem is when we are using --deploy-url flag during build it only fetch bundle files from cdn still all assets are coming from server but when use --base-href flag it thrown these error and application is not getting loaded and we didn't want to use hash strategy for our application is there any way we can server all assets from cdn . 

### Please provide the exception or error you saw

```true
Unhandled Navigation Error: SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL
```

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
