### ISSUE TITLE
Sketchy block-scoped var in es6 export initializers

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#4742]
https://github.com/angular/angular/blob/f5159389b365ee668d51b48351e6e71d22cd0962/modules/angular2/src/core/facade/browser.ts#L11
```
export const Event = Event;
export const MouseEvent = MouseEvent;
export const KeyboardEvent = KeyboardEvent;
export const EventTarget = EventTarget;
export const History = History;
export const Location = Location;
export const EventListener = EventListener;
```

This will break with typescript@next and looks wrong.

reported by @vladima

**Comment by vamsivarikuti** [comment]
@alexeagle can you provide some more info on this issue, i want to work on this, if its easy fix.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
