### ISSUE TITLE
Missing @Injectable() in the Tutorial Project

### ISSUE THREAD

**Issue by Thanyanit-J** [angular/angular#47425]
### Describe the problem that you experienced

In the tutorial shopping cart project's example code snippet,
@Injectable(), which should be above the `export class CartService { ... }`, is missing from the "[Define a cart service](https://angular.io/start/start-data#define-a-cart-service)" section.

### Enter the URL of the topic with the problem

https://angular.io/start/start-data#define-a-cart-service
https://github.com/angular/angular/blob/3a60063a54d850c50ce962a8a39ce01cfee71398/aio/content/examples/getting-started/src/app/cart.service.ts

### Provide any additional information here in as much as detail as you can

I noticed that [the example code](https://github.com/angular/angular/blob/3a60063a54d850c50ce962a8a39ce01cfee71398/aio/content/examples/getting-started/src/app/cart.service.ts) doesn't have tag for `@injectable()` part. Thus, it doesn't appear in the code example snippet.

**Comment by mauromattos00** [comment]
Hello! I can work on this one 😀

**Comment by jessicajaniuk** [comment]
The PR has been merged. Closing as fixed.
