### ISSUE TITLE
feature request: Allow custom id generation for i18n tags

### ISSUE THREAD

**Issue by kertof** [angular/angular#47434]
### Which @angular/* package(s) are relevant/related to the feature request?

localize

### Description

Currently, when adding i18n tags to our code, the resuting extrated messages have unique, but random IDs.
With this, it is difficult to look back our source code and understand the context of the text to be translated.
We currently override this by adding ID ourselves, whcih usually include the file name, allowing us to find the context faster.

Ideally we would like to, either define a generator function for IDs, which would take some arguments for context (filename, linenumber, element type,...), or allow a way to include the file name in the generated ID, as a default.

### Proposed solution

We currently override this by adding ID ourselves, whcih usually include the file name, allowing us to find the context faster.

Ideally we would like to, either define a generator function for IDs, which would take some arguments for context (filename, linenumber, element type,...).

### Alternatives considered

Allow a way to include the file name in the generated ID, as a default.

**Comment by AndrewKushnir** [comment]
@kertof thanks for creating a feature request. We've discussed this question with the team and the current state is that we do not plan to provide a config option to change a built-in message ID generator with a custom one. We believe that having file/folder names in the message ID might make it unstable and brittle.
