### ISSUE TITLE
Provide a lifecycle hook / signal from the framework when rendering is done and it is safe to read from the DOM

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#47432]
### Description

There are numerous situations when one needs to read from the DOM after Angular finished rendering and is done writing to the DOM (ex.: #47366). 

### Proposed solution

None considered at the moment

### Prior art

* https://reactjs.org/docs/hooks-reference.html#uselayouteffect

**Comment by AndrewKushnir** [comment]
(linking #23784 here as well, this lifecycle hook should help avoid zone.onStable there and make the code synchronous)

**Comment by AndrewKushnir** [comment]
Closing this ticket as completed by PR https://github.com/angular/angular/pull/50607.
