### ISSUE TITLE
query changes dart streams need to be closed

### ISSUE THREAD

**Issue by rkirov** [angular/angular#4747]
I think that the lifecycle of the component querying, the queryList object and the subscription are always exactly the same, and we do release all references. But I am told that is not enough and we should also close the stream before releasing.

Should be as simple as adding `.close` here https://github.com/angular/angular/blob/master/modules/angular2/src/core/linker/element_injector.ts#L1076

**Comment by TedSander** [comment]
Is it possible to get these for other stream  that angular provides? Events?
