### ISSUE TITLE
No Ukrainian Hryvnia in currency pipe

### ISSUE THREAD

**Issue by HannaKogut** [angular/angular#47492]
### Which @angular/* package(s) are the source of the bug?

core, Don't known / other

### Is this a regression?

No

### Description

Hi. I am making my first test app in Angular and when I try to use currency pipe - currency : 'UAH' with my country's currency I can see this: UAH500.00, but when I use it with -  currency : 'USD'  I can see usd symbol like this $500.00.
So maybe I'm doing something wrong or maybe you don't have Ukrainian hryvnia in your data base?
Can you add it please? Here is it **₴**.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.3
Node: 16.17.0
Package Manager: npm 8.15.0 
OS: darwin arm64

Angular: 14.2.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.3
@angular-devkit/build-angular   14.2.3
@angular-devkit/core            14.2.3
@angular-devkit/schematics      14.2.3
@angular/cli                    14.2.3
@schematics/angular             14.2.3
rxjs                            7.5.6
typescript                      4.7.4
```

### Anything else?

I would love to hear from you!

**Comment by JoostK** [comment]
The `ru-UA` locale does contain ₴ as short currency code. You need to load the necessary locale data and then specify the currency and locale when using the `currency` pipe. [StackBlitz example](https://stackblitz.com/edit/angular-ivy-39z9ej?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html).

**Comment by HannaKogut** [comment]
> The `ru-UA` locale does contain ₴ as currency code. You need to load the necessary locale data and then specify the currency and locale when using the `currency` pipe. [StackBlitz example](https://stackblitz.com/edit/angular-ivy-39z9ej?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html).

What does it mean ru-UA? It's two different countries!

**Comment by JoostK** [comment]
Sorry, there is a better locale available: `uk` instead of `ru-UA`. My previous comment was based on finding `UA` as code for Ukraine.

**Comment by HannaKogut** [comment]
> Sorry, there is a better locale available: `uk` instead of `ru-UA`. My previous comment was based on finding `UA` as code for Ukraine.

Yes, I need Ukrainian currency, but I don't understand why there is russian ru?

**Comment by JoostK** [comment]
Please forget about `ru-UA`; I should have pointed you to `uk` from the start.

**Comment by HannaKogut** [comment]
> Please forget about `ru-UA`; I should have pointed you to `uk` from the start.

Great! I see now, thank you very much for helping!
