### ISSUE TITLE
[FR for the docs] Add tracking mechanism for last updated

### ISSUE THREAD

**Issue by josmar-crwdstffng** [angular/angular#47495]
### Description

The markdown content for aio should convey last updated date as well as last reviewed date.

*   `@reviewed 2022-09-20`

### Proposed solution

Add support for last updated to markdown-to-json tooling.

*   `@reviewed 2022-07-20`
*   `@updated 2022-09-20`

### Alternatives considered

n/a

**Comment by bob-watson** [comment]
Thanks for the issue.

Could you explain more why this is needed?

**Comment by josmar-crwdstffng** [comment]
The ability to quickly determine the staleness of content is important.
Currently on `aio` the only indicator could be used for either last changed or last reviewed.
This usage pattern lacks the ability to determine whether the content has been reviewed and signed-off by the SME.
