### ISSUE TITLE
Improve the Stack Trace when an HTML Parsing Error is Encountered

### ISSUE THREAD

**Issue by Lumis-Sage** [angular/angular#47496]
### Description

I have noticed that when I make a syntax mistake in the HTML of a component the Angular Compiler throws a vast amount of errors, so much so that the original offending error is buried in a huge stack trace that is cut off in the terminal window of VS Code, my preferred Code Editor for Angular.  This can be worked around by exporting the stack trace to common error in the form a text file, however it would be very convenient if I could avoid these extra steps to identify the location of bad HTML.  

Ideally, when there is a syntax error in the HTML, I would like an option to be able to have the compiler simply identify the line where the HTML syntax is malformed and skip errors resulting from the malformed HTML syntax which would make the Stack Trace much more useful without needing to resort to workarounds for the issue.  

### Proposed solution

Introduce an option that suppresses all errors in a stack trace except for the first one when the error is caused by a malformed HTML element (syntax error).  

### Alternatives considered

A workaround is to export the output to a txt file and read the text file, but this can become cumbersome and adds friction to the normal workflow of a project.  Being able to simply and easily see where an HTML syntax error is located in the console without having to resort to the above workaround would be ideal.  

Below is an example of the top of the stack trace in VS Code and the syntax error that generated it.  Simply identifying the line with the error without showing all the additional errors would make the error output much more readable and useful

![Top of HTML syntax stack trace](https://user-images.githubusercontent.com/114021657/191356925-85fafd97-efe3-46fe-8bb7-bfd1f7344d7e.PNG)
![Example Syntax Error](https://user-images.githubusercontent.com/114021657/191356928-f7f041ef-c76e-4849-9613-fa10e0e685f3.PNG)

**Comment by pkozlowski-opensource** [comment]
@Lumis-Sage would you mind share an example of the situation where " a syntax mistake in the HTML of a component the Angular Compiler throws a vast amount of errors"?

**Comment by pkozlowski-opensource** [comment]
Going to close this one as we haven't heard back with a reproduce scenario.
