### ISSUE TITLE
Map object - Android polyfill

### ISSUE THREAD

**Issue by drewrygh** [angular/angular#4751]
***Overview of the Issue***
The `Map` object being used throughout [core/facade/collection.ts](https://github.com/angular/angular/blob/master/modules/angular2/src/core/facade/collection.ts) will cause one of the following errors during the app bootstrap process on Android:

***Errors:***  `m.values is not a function`, `undefined is not a function`

***Error Source:*** [core/facade/collection.ts#L65](https://github.com/angular/angular/blob/master/modules/angular2/src/core/facade/collection.ts#L65)

***Motivation for or Use Case***
Can't get a stack trace to see where [`_arrayFromMap`](https://github.com/angular/angular/blob/master/modules/angular2/src/core/facade/collection.ts#L61) is being called, but it seems like it may be getting called during the bootstrap process. If so, it could affect all android browsers.

***Browsers and Operating System***
Seems to only affect android browsers. Confirmed it affects android stock browser and chrome. Doesn't affect firefox. Tested on android 4.4 and 5.1.

**Comment by mlaval** [comment]
Including es6-shim should solve this issue

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular/angular/issues/4754#issuecomment-148320793
