### ISSUE TITLE
MutationObserver stops working when used in a project where @angular/upgrade is used

### ISSUE THREAD

**Issue by AnderssonPeter** [angular/angular#47520]
### Which @angular/* package(s) are the source of the bug?

upgrade, zone.js

### Is this a regression?

No

### Description

We are currently upgrading a project from angularjs to angular 14 and noticed that our callbacks from a MutationObserver are never where called.

If I create a new angular 14 project the callbacks work as intended, but as soon as I added @angular/upgrade they stopped working.

### Please provide a link to a minimal reproduction of the bug

https://github.com/AnderssonPeter/angular-upgrade-mutationobserver

### Please provide the exception or error you saw

```true
The callback defined in src\app\app.component.ts:27 is never called
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.1.3
Node: 18.1.0 (Unsupported)
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 14.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router, upgrade

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.3
@angular-devkit/build-angular   14.2.3
@angular-devkit/core            14.2.3
@angular-devkit/schematics      14.1.3
@angular/cli                    14.1.3
@schematics/angular             14.1.3
rxjs                            7.5.6
typescript                      4.7.4
AngularJS                       1.8.2
```

**Comment by JiaLiPassion** [comment]
@AnderssonPeter , could you show a detailed reproduce steps? I cloned your repo, and clicked the `toggle` button, the `mutation` text is output correctly.

**Comment by AnderssonPeter** [comment]
@JiaLiPassion Seems your right, I was 100% sure I had the issue in that project but now it works as intended again.
I have tested with 3 different versions of chromium and it works as intended in all 3, but I'm 100% sure I had this issue yesterday..
