### ISSUE TITLE
Ability to pass `BootstrapOptions` when bootstrapping standalone application

### ISSUE THREAD

**Issue by edbzn** [angular/angular#47538]
### Which @angular/* package(s) are relevant/related to the feature request?

platform-browser

### Description

Hi there,

I started to convert a Zoneless application to standalone components, and I noticed it's not possible to bootstrap a standalone application without Zone.js, so I have to keep the AppModule to be able to pass the ngZone configuration at bootstrap.

```ts
platformBrowserDynamic()
  .bootstrapModule(AppModule, {
    ngZone: 'noop',
  });
```

### Proposed solution

It would be nice to be able to pass the `BootstrapOptions` to the `bootstrapApplication` function like so:

```ts
bootstrapApplication(AppComponent, { ngZone: 'noop' })
```

### Alternatives considered

N/A

**Comment by BioPhoton** [comment]
Hi @edbzn and THX for opening this issue!

I tried a lot the last days to get it working...

One clean solution could be to use DI and override `NgZone` with `θNgNoopZone`. 
The problem however is that boootstrapApplication has zone.js requirement hardcoded... 

What is a ugly workaround is to provide zone.js in the bundle but flag all used API's so you don't actually patch them.
with this in addition to the `θNgNoopZone` approach it can work. But there is all the bootstrap improvements and bundle size gone 
😢
I really hope this gets fixed soon as I see no real reason why... The module full approach also supports it.

Even if zone-less CD is an active topic I don't think everyone needs is to go standalone.

Happy to hear the teams opinion here. 🙏

**Comment by alxhub** [comment]
This was a deliberate choice we made when designing `bootstrapApplication` - we chose to create a minimal API that didn't carry over any of the options from the `bootstrapModule` API.

`ngZone: 'noop'` is what I would consider an advanced, low-level option. It's not something you can just set - using this option requires completely rethinking how state works in your application and how change detection is triggered.

For now, continue to use `bootstrapModule` if you require a zoneless application. Reactivity, Change Detection, and "zoneless" is an area of focus for us in 2023, so we hope to have a real story here at some point.

**Comment by MaximSagan** [comment]
@alxhub

`ngZone: 'noop'` may be advanced, but `ngZoneEventCoalescing: true` is supposedly an optimization to reduce change detection cycles. Users may switch this option on whether they have a low level understanding of ngZone or not, as was the case with my team. We are now hesitant to migrate our apps to be fully standalone component-based, because losing `ngZoneEventCoalescing: true` could potentially have adverse affects on our app's behavior.

**Comment by pkozlowski-opensource** [comment]
zone.js event coalescing is a good use-case and the option we should support. I'm going to re-open this issue so we can adjust the API.

**Comment by TicTak21** [comment]
Hello.
I would really like to see this feature available. Is there any progress in the discussion?

**Comment by hiepxanh** [comment]
I think this feature is very important, it enable me to make angular work with Vite, please take a look <3

**Comment by hiepxanh** [comment]
btw I think this PR is for this issue? https://github.com/angular/angular/pull/49079

**Comment by JeanMeche** [comment]
Per Andrew Scott's comment in #49079, the team hasn't settled for an API yet but it seems in progress with the landing of the signal proposal.

**Comment by elgreco247** [comment]
This is fixed with https://github.com/angular/angular/pull/49557 (set coalescing options via `provideZoneChangeDetection()` and override `NgZone` implementation using DI => unsupported, but possible).

**Comment by pkozlowski-opensource** [comment]
It is indeed, thnx @elgreco247

Fixed in https://github.com/angular/angular/pull/49557

**Comment by hiepxanh** [comment]
@pkozlowski-opensource  I think current fix is not the purpose of issue, the issue mean add: `ngZone: 'noop'` option to bootstrap option. the `NgZoneOptions` is not the one we expecting because it lack of ngZone: 'noop', or there is an other way to achive zoneless with standalone?

**Comment by hiepxanh** [comment]
![image](https://user-images.githubusercontent.com/16970990/235279986-ec5cf288-7d51-4042-af6b-bc52c2bcf086.png)
this is #47886 expecting, ngZone: 'noop' for standalone application

**Comment by elgreco247** [comment]
> or there is an other way to achive zoneless with standalone?

@hiepxanh IIUC it is now possible using DI: `{provide: NgZone, useClass: ɵNoopNgZone}`; but it is not officially supported (hence the internal import).
