### ISSUE TITLE
Built in trackByIndex

### ISSUE THREAD

**Issue by bryanrideshark** [angular/angular#47549]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

In Angular 1.x, we had a built in "trackByIndex" function on ng-for.

I am now specifying a "trackByIndex" function with the same signature in almost every component I use because of the performance benefits provided by trackByIndex.

````ts
  trackByIndex = <T>(index: number, value: T) => {
    return index;
  };
````

### Proposed solution

Can we find a way to add a built-in `trackByIndex` to Angular Common? Or is there another way that I can easily supply this function without having to define it multiple times over?

### Alternatives considered

I can't think of any alternatives - There is no concept of "global" scope in Angular templates; Unless the function is defined on the component, it's inaccessible. 

If `@NgModule` had a way to ambiently declare a function accessible to the component templates, we could use that; But as far as I know, no such solution exists in Angular.

**Comment by HyperLife1119** [comment]
We can create a directive which will automatically add `trackBy` function for `ngFor` or `cdkVirtualFor`:

```ts
@Directive({
  selector: '[ngForTrackById], [cdkVirtualForTrackById]',
})
export class ForTrackByIdDirective<T extends { id: number | string }> {
  constructor(
    @Host() @Optional() private ngForOf: NgForOf<T>,
    @Host() @Optional() private cdkForOf: CdkVirtualForOf<T>,
  ) {
    if (this.ngForOf) {
      this.ngForOf.ngForTrackBy = (_index: number, item: T) => item.id;
    } else if (this.cdkForOf) {
      this.cdkForOf.cdkVirtualForTrackBy = (_index: number, item: T) => item.id;
    }
  }
}
```
Its usage looks like this:

```html
<ng-container *ngFor="let item of list; trackById"></ng-container>
```

You can modify `trackBy` function to what you want.

**Comment by pkozlowski-opensource** [comment]
> I am now specifying a "trackByIndex" function with the same signature in almost every component I use because of the performance benefits provided by trackByIndex.

There were several discussion about it in the past. The `trackByIndex`, while it might have some performance benefits, is not _correct_ as it might cause desynchronising DOM state with application's model. 

This is _not_ the pattern we want to promote.
