### ISSUE TITLE
'hgroup' is not a known element

### ISSUE THREAD

**Issue by johnnygerard** [angular/angular#47545]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

My issue is identical to #38831 which was closed because "the hgroup element has been removed from the HTML5 (W3C) specification".

Except that the latest HTML5 standard, i.e. [HTML 5.3](https://www.w3.org/TR/2021/NOTE-html53-20210128/), has been retired since January 28, 2021.
The latest HTML standard includes the [hgroup element](https://html.spec.whatwg.org/multipage/sections.html#the-hgroup-element) and all major browsers [support it](https://caniuse.com/?search=hgroup).

Can hgroup be added to the list of known elements?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.2.2
Node: 16.17.0
Package Manager: npm 8.19.2 
OS: linux x64

Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1402.2 (cli-only)
@angular-devkit/core         14.2.2 (cli-only)
@angular-devkit/schematics   14.2.2 (cli-only)
@schematics/angular          14.2.2 (cli-only)
```

**Comment by dylhunn** [comment]
I had never heard of an `hgroup` but this does appear to be a live issuel

**Comment by dylhunn** [comment]
Unsure where exactly this fix goes but it's probably fairly straightforward.
