### ISSUE TITLE
alpha::42 traceur-runtime 

### ISSUE THREAD

**Issue by shatakshidixit1** [angular/angular#4754]
I have heard that angular 2 alpha 42 version do not need use of traceur-runtime.
In my angular 2 alpha 42 version My prpgram is running perfectly with traceur-runtime.
But when i remove traceur there is a error :: 
***Uncaught TypeError: Array.from is not a function***

**Comment by Sabartius** [comment]
You need to include es6-shim instead.

**Comment by Alxandr** [comment]
@Sabartius does this mean it'd work with core-js as well?

**Comment by pkozlowski-opensource** [comment]
Guys, you need ES6 polyfill if you want to run ng2 in browsers that don't support all new ES6 methods (pretty much majority of them at this point :-)). Both  es6-shim and core-js should work well. 

On top of this if want to run in older IEs you might need more polyffils, check what it needed for the framework to run on IE: https://github.com/angular/angular/blob/master/modules/angular2/src/testing/shims_for_IE.js

We don't need traceur-runtime any more - it is just that traceur-runtime had ES6 polyfills inside it so it could act as a polyfills. Having said this, it has much more than polyfills, so using it just to shim ES6 methods is a bit of an overkill.
