### ISSUE TITLE
Can't subclass FormControl<T>

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular#47558]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes, sort of (before Angular 14, FormControl wasn't generic) 

### Description

When trying to subclass `FormControl` , TS triggers the following error : `TS2510 : Base constructors must all have the same return type`

```
import { FormControl, AbstractControl } from '@angular/forms';

export class Control<T> extends FormControl<T> {}
```

I suspect the definition of [ɵFormControlCtor](https://github.com/angular/angular/blob/85b5d125be4c689f892c6c50b94c593b85b513de/packages/forms/src/model/form_control.ts#L358) to be that cause and [#35387](https://github.com/microsoft/TypeScript/issues/35387) to be the root cause of that. 

### Please provide a link to a minimal reproduction of the bug

[Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgMWiAwhAdjKEA2ANHAIIBGAzrgIYDGMmOe+cAvnAGZ4hwDkAAtSwBzAK75qUAPQc0FXgG4AsAChVAUwAekWHFoSKFOI1wEAPABUAfHC0x1WACZHUUDNlP5LNhKyA)

Any thoughts to share on that ?

**Comment by SeriousJul** [comment]
I ran into the same issue. We had typed form for a long time already, with a custom Wrapper of FormControl, FormArray, FormGroup. By the time, we added extra features to it that is simply not provided by default (readonly, visibility, informative validation errors...)

Here is my current workaround to safely extends FormControl, feel free to share yours or to improve this one.
Following pattern used in angular and also described 
https://github.com/angular/angular/blob/14.2.x/packages/forms/src/model/form_control.ts
https://github.com/microsoft/TypeScript/issues/35387 

```ts
export interface IEnhancedAbstractControlOptions { // custom stuff
  readonly: boolean;
  hidden: boolean;
}

const defaultEnhancedAbstractControlOptions: IEnhancedAbstractControlOptions = {
  readonly: false,
  hidden: false,
};

export interface EnhancedFormControl<TValue = any> extends FormControl<TValue> {
  readonly: boolean;
  readonlyChanges: Observable<boolean>;
  hidden: boolean;
  hiddenChanges: Observable<boolean>;
  warnings: EnhancedFormControl['errors'];
}
type EnhancedFormControlInterface<TValue = any> = EnhancedFormControl<TValue>;

// Internal class, rip-off ɵFormControlCtor with enhanced typings
interface ɵEnhancedFormControlCtor {
  new (): EnhancedFormControl<any>;

  new <T = any>(value: FormControlState<T> | T, opts: FormControlOptions & { nonNullable: true }): EnhancedFormControl<T>;

  new <T = any>(
    value: FormControlState<T> | T,
    validatorOrOpts?: ValidatorFn | ValidatorFn[] | FormControlOptions | null,
    asyncValidator?: AsyncValidatorFn | AsyncValidatorFn[] | null,
    _opts?: Partial<IEnhancedAbstractControlOptions>,
  ): EnhancedFormControl<T | null>;

  prototype: EnhancedFormControl<any>;
}

export const EnhancedFormControl: ɵEnhancedFormControlCtor = class EnhancedFormControl<TValue = any>
  extends FormControl
  implements EnhancedFormControlInterface<TValue>
{
  private _readonly: boolean;
  private _readonlyChanges = new Subject<boolean>();
  get readonly() {
    return this._readonly;
  }
  set readonly(readonly: boolean) {
    this._readonly = readonly;
    this._readonlyChanges.next(readonly);
  }
  get readonlyChanges(): Observable<boolean> {
    return this._readonlyChanges;
  }
  private _hidden: boolean;
  private _hiddenChanges = new Subject<boolean>();
  get hidden() {
    return this._hidden;
  }
  set hidden(hidden: boolean) {
    this._hidden = hidden;
    this._hiddenChanges.next(hidden);
  }
  get hiddenChanges(): Observable<boolean> {
    return this._readonlyChanges;
  }
  warnings: EnhancedFormControl['errors'] = null;

  constructor(
    // formState and defaultValue will only be null if T is nullable
    formState: FormControlState<TValue> | TValue = null as unknown as TValue,
    validatorOrOpts?: ValidatorFn | ValidatorFn[] | FormControlOptions | null,
    asyncValidator?: AsyncValidatorFn | AsyncValidatorFn[] | null,
    _opts?: Partial<IEnhancedAbstractControlOptions>,
  ) {
    super(formState, validatorOrOpts, asyncValidator);
    const { readonly, hidden } = { ...defaultEnhancedAbstractControlOptions, ..._opts };
    this._readonly = readonly;
    this._hidden = hidden;
  }
};
```
Usage identical to the one specified there https://angular.io/guide/typed-forms + the custom options in the constructor

Please note also that I removed the deprecated constructors signatures of ɵFormControlCtor

**Comment by JeanMeche** [comment]
By the way :

```
class Foo<T> extends FormControl<T|null> {

} 

```

is valid.

**Comment by SeriousJul** [comment]
If you are willing to loose the ability to use the nonNullable constructor overload, this is indeed a great solution

```ts
const foo = new Foo<string>("bar", {nonNullable: true});
foo.setValue(null); // Does not error!

const foo2 = new FormControl<string>("bar", {nonNullable: true} );
foo2.setValue(null); // error!
```

**Comment by bryanforbes** [comment]
The "simplest" way I found to do this was as follows:

```typescript
import { FormControl, ɵFormControlCtor } from "@angular/forms";

export interface MyFormControl<TValue = any> extends FormControl<TValue> {}

export const MyFormControl: ɵFormControlCtor = class MyFormControl<TValue = any>
  extends FormControl
  implements FormControl<TValue> {
  // override whatever you need here
}
```

This is basically the same as what @SeriousJul suggested, but slimmed down quite a bit (for my purposes, I didn't care about removing deprecated signatures). This also maintains the ability to use `nonNullable: true` and get the typing error for `setValue(null)` that the solution provided by @JeanMeche doesn't.

And while this works, it's quite a bit more work than `export class MyFormControl<TValue = any> extends FormControl<TValue> {` and the latter is preferable if possible.

**Comment by JeanMeche** [comment]
It seems like @bryanforbes, that your solution doesn't work when [`declaration`](https://www.typescriptlang.org/tsconfig#declaration) is true. See microsoft/TypeScript#30355.

**Comment by JeanMeche** [comment]
I'm closing this per https://github.com/angular/angular/blob/16.0.1/docs/PUBLIC_API.md#final-classes
