### ISSUE TITLE
System configuration guides for using and developing angular need more detail.

### ISSUE THREAD

**Issue by bob-watson** [angular/angular#47559]
### Describe the problem that you experienced

Trying to install the required software to develop with and develop for Angular and found the installation instructions have many holes that require numerous trips to stackoverflow et al.

### Enter the URL of the topic with the problem

https://angular.io/guide/setup-local

### Describe what you were looking for in the documentation

The software, and its dependencies, necessary to develop with and for angular.,

### Describe the actions that led you to experience the problem

Trying to prepare a development environment to build and update angular docs

### Describe what you want to experience that would fix the problem

Step by step instructions to install and verify the required software with sufficient information about sequence, and versions 

### Add a screenshot if that helps illustrate the problem

N/A

### If this problem caused an exception or error, please paste it here

```true
N/A
```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
N/A
```

### Provide any additional information here in as much as detail as you can

```true
None
```

**Comment by pkozlowski-opensource** [comment]
A drive-by comment: instructions for setup when _changing_ Angular are in https://github.com/angular/angular/blob/main/docs/DEVELOPER.md

**Comment by bob-watson** [comment]
@pkozlowski-opensource Thanks for the drive-by!
Setting up a system to use and develop with Angular is a key "getting started" experience.
Where should the *source of truth* for that be?
* [Setting up the local environment and workspace](https://angular.io/guide/setup-local)
* [Building and Testing Angular](https://github.com/angular/angular/blob/main/docs/DEVELOPER.md)
* Some new page?

My view from the cheap seats is that: [Setting up the local environment and workspace](https://angular.io/guide/setup-local) should be the *source of truth* and contain what's in [Building and Testing Angular](https://github.com/angular/angular/blob/main/docs/DEVELOPER.md), only divided into specific topics and use-cases.

Is there any reason NOT to have the set up information in the documentation and refer to the documentation from the GitHub repo?

**Comment by pkozlowski-opensource** [comment]
@bob-watson I'm confused... The setup instruction for people _using_ the framework should be different as compare to the setup instructions for people _developing_ the framework. So I don't think that there should be one source of "truth" as there are 2 use-cases and 2 different "truths"...

**Comment by JeanMeche** [comment]
The docs have been revised in angular.dev
