### ISSUE TITLE
Add Module / Global scoped variables to Angular Template Syntax

### ISSUE THREAD

**Issue by bryanrideshark** [angular/angular#47560]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

I propose that a new lexical scope be added to the Angular template syntax - While I don't have a good name, "ambient values" closely captures. what I'm going after.

## Background

Presently, the Angular template language has one lexical scope - The component template. In Angular expressions, we can reference "let-scope" variables, or member properties / components of the containing Component class. If we want to access module level imports, we must access those through careful orchestration with the Dependency Injector.

This decision forces Angular developers to be very explicit about what is accessible to their components. It promotes best practices. But in some circumstances, this aspect of the Angular Template makes it painful for developers and results in a lot of code duplication.

## Proposal

I propose that the concept of a Module Scoped "Ambient Value" be added to the Angular Template syntax. "Ambient Values" would work just like any other reference in an Angular Expression, with the only difference being the template value source.

Ambient Values would need to be declared in the Providers array of an NgModule or Standalone Component, and use the existing Dependency Injection system.

````ts

import { ambientValue } from '@angular/core';

@NgModule({
   providers: [
      { 
        provide: ambientValue('foo'),
        useValue: 'FOO'
      }
   ]
})
export class SampleModule {}
````

The exact syntax for declaring an Ambient Value is up for debate - the important piece of course would be the name used for reference in the Angular Templates, and the value to resolve.

The value of an Ambient Value would be resolved once upon the first time rendering a Component - It would have a lifecycle identical to other providers in an Angular Module.

````
<!-- A sample component importing SampleModule -->

<p>The message is {{foo}}</p>

<!-- renders, The message is FOO -->

````

## Problems this solves

For Component Libraries, there are complicated settings that must be developed. One example is the `Overlay` library from `@angular/cdk`. Charting libraries are another example, any component with a complex object or array of objects requiring configuration.

To configure components with complex settings, library authors must either provide an `InjectionToken` and allow consumers to configure behavior, or, provide factory functions and classes expecting consumers to duplicate code at the component typescript level.

````ts
// Two possible solutions for shared configuration of a hypothetical charting library


// Using Inejction Tokens

import { FooThemeConfigToken } from '@foo-charts/foo-charts-ngx';
import { appSpecificFooTheme } from 'app/shared/foo-theme';

@Component({
   selector: 'foo-charts-consumer-1',
   template: `
   <foo-chart>
   </foo-chart>
`,
   providers: [{
     provide: FooThemeConfigToken,
     useValue: appSpecificFooTheme 
   }]
})
export class FooChartsConsumer1Component {}


// Using declaration of config values

import { FooThemeConfigToken } from '@foo-charts/foo-charts-ngx';
import { appSpecificFooTheme } from 'app/shared/foo-theme';

@Component({
   selector: 'foo-charts-consumer-2',
   template: `
   <foo-chart [theme]="fooTheme">
   </foo-chart>
`,
})
export class FooChartsConsumer2Component {
  fooTheme = appSpecificFooTheme;
}

````

In the real world, this looks like "connectedPositionStrategy", or declaring a `trackBy:` function over and over again.

Ambient Values would result in the following solution for this chart library:

````
import { FooThemeConfigToken } from '@foo-charts/foo-charts-ngx';

@Component({
   selector: 'foo-charts-ambient-value-consumer',
   template: `
   <foo-chart [theme]="appFooTheme">
   </foo-chart>
`,
})
export class FooChartsAmbientValueConsumerComponent {
}
````

## Ramifications for state management

If this were to be introduced to Angular, it would change the game for state management. Right now, services must be directly injected into each component; Every application component that wants to get the login status of a user, a shopping cart inventory, etc. must inject `UserService`, `CartService` etc. and then access methods directly.

````ts
// Before Ambient Values
@Component({
   selector: 'store-page',
   template: `
   <div>
      <store-item></store-item>
   </div>
   <div *ngIf="user.loggedIn">
      Welcome back! Your cart is {{cart.status}}
   </div>
`
})
export class StorePage {
   constructor(
     public user: UserService,
     public cart: CartService
   ) {
   }
}

// After Ambient Values (assuming UserService and CartService are ambiently declared as user and cart in a higher module).
@Component({
   selector: 'store-page',
   template: `
   <div>
      <store-item></store-item>
   </div>
   <div *ngIf="user.loggedIn">
      Welcome back! Your cart is {{cart.status}}
   </div>
`
})
export class StorePage {}
````

It is debatable which the best solution is for this; It's likely a terrible idea for shared component libraries, but whether or not it's a poor strategy for particular applications is less clear. 

I can imagine that in a large application development team with varying team-member experience, a Sr. Developer might develop an "AcmeApplicationState" module, providing a common vernacular for Jr. Developers to easily access business logic.

### Alternatives considered

This feature may be declared either too much work, or too dangerous as it could promote bad coding practices. However, I think that on the main it would provide powerful ergonomics for developers and would be an appreciated improvement to Angular. For situations where common functions, queries, themes, and state is shared across an entire application, declaring it once in a Module versus re-declaring it in each component would save developers time, and enforce consistency.

**Comment by pkozlowski-opensource** [comment]
> This decision forces Angular developers to be very explicit about what is accessible to their components.

This is our intention and deliberate design decision.

> I propose that the concept of a Module Scoped "Ambient Value" be added to the Angular Template syntax.

We are trying to reduce the responsibilities of NgModule so extending is a non-starter. This wouldn't work with standalone components. But I _guess_ what you mean here is having a set of DI tokens that are "automatically" visible in the template expressions... 

> Ambient Values would result in the following solution for this chart library:

```typescript
import { FooThemeConfigToken } from '@foo-charts/foo-charts-ngx';

@Component({
   selector: 'foo-charts-ambient-value-consumer',
   template: `
   <foo-chart [theme]="appFooTheme">
   </foo-chart>
`,
})
export class FooChartsAmbientValueConsumerComponent {
}  
```

I hear what you are saying but this is _not_ the direction we want to take. Mostly because it isn't clear - both to humans _and_ compilers where the  `appFooTheme` is coming from. This would prevent us from properly type-checking a template as we wouldn't know where to look for the type of  `appFooTheme` - or require global, "know the whole world" compilation.

I'm going to close this as "not planed" as the outlined solution goes against the existing design and our plans for the future. Moreover, I don't think that we are doing any improvement here - slightly less code to write, maybe, but at the expense of clarity and slower compilation / reduced type-checking.

**Comment by bryanrideshark** [comment]
@pkozlowski-opensource , many languages have the concept of a "namespace" - What I'm pointing out is that the Angular Template Syntax has no concept.

React, Vue, and other languages are built around a "module" system - ECMAScript modules. They can import constants etc. from the environment and directly embed them into their templates, just using vanilla Javascript. With Angular, you have no ease, as the only thing you can bind to is the component. Want some ambient variable? You're going to have to wrap it up and declare it in the `providers` array, or explicitly declare it in the class, which you then access in the template scope. It's double the work.

I will open a new issue with an alternative solution to this problem that does _not_ grow NgModules.

**Comment by pkozlowski-opensource** [comment]
@bryanrideshark we are absolutely aware of the issue of having template expressions evaluated against the component instance and there are open tracking issue for this already: #25963 - no need to create a new one.

having said this we definitively don't want DI to define template evaluation scope.

**Comment by bryanrideshark** [comment]
Would the suggestion of Native Expressions (putting direct Javascript into an Angular Template) work? #47570
