### ISSUE TITLE
[Edge] Browser disconnects when running the full unit tests campaign

### ISSUE THREAD

**Issue by mlaval** [angular/angular#4756]
As found in PR #4260, Edge disconnects before executing all the tests, when running the full unit test campaign.

Investigations showed that 3 particular tests are causing this, but without any good reason. Executing them individually is successful.
These tests are: https://github.com/mlaval/angular/commit/b42cbcb55987ab6bb05ded876f150e3f93f98ff0

Skipping them is a workaround to make the campaign to complete successfully in Edge.

**Comment by mlaval** [comment]
2 new cases found in #5490

**Comment by Narretz** [comment]
I'm seeing a similar issue for angular.js only. Edge times out after a few hundred tests. How did you find those failing tests? It seems arbitrary.

**Comment by Narretz** [comment]
Found the failing test with poor man's bisect. I really wonder why exactly these tests.

**Comment by mhevery** [comment]
is this still in issue or can it be closed?

**Comment by mlaval** [comment]
Still valid :(

**Comment by mlaval** [comment]
With #10450, this issue is almost solved, only 2 unit tests are still commented out in `slice_pipe_spec.ts`.
According to the preview already available, it won't be a problem with the next version of the browser (14.xxxxx).

**Comment by Narretz** [comment]
@mlaval do you know when a new stable version of Edge will be released? Or are you testing against previews?

**Comment by mlaval** [comment]
Fully solved with preview, almost solved with stable. I'm using VM from modern.ie to run tests.

I don't know when  the release will be.
