### ISSUE TITLE
In ng-app application css media queries not working properly on ie9 and ie10

### ISSUE THREAD

**Issue by rizwangithub** [angular/angular#4757]
In my AngularJS app, CSS media query is not working properly only on IE9 and IE10. Media query defined for small screen is effecting globally. It works only when I resize the browser or inspect the element.

No issues in other browsers like Chrome and Firefox. I've not tested this in IE10+ browser. It works in IE8+ when I remove AngularJS. Here is my media query:

@media (min-width: 0px) and (max-width: 767px) { 
    .col-sidebar{ width:100%}
    .col-content{ width:100%}
}
In large screen on IE10 browser, sidebar shows 100% width.

Here is my global css for large screen:

.col-sidebar{ width:30%}
.col-content{ width:70%}

**Comment by gdi2290** [comment]
I think you might be looking for Angular 1 which lives here https://github.com/angular/angular.js

**Comment by rizwangithub** [comment]
ok am sorry
