### ISSUE TITLE
beforeunload return value is not respected

### ISSUE THREAD

**Issue by datbth** [angular/angular#47579]
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

No

### Description

When zone.js is **not** loaded, returning a value in `beforeunload` event handler causes the browser to ask for confirmation: https://jsfiddle.net/datbth/b57ur4ky/45/

When zone.js is **loaded**, returning a value in `beforeunload` event handler does nothing: https://jsfiddle.net/datbth/b57ur4ky/44/

Reproduction steps:
1. Visit the jsfiddle link
2. Click **Bind Event**
3. Click **Reload**
4. Expected result: browser asking for confirmation 
![image](https://user-images.githubusercontent.com/15865062/192949819-5c302a75-35d2-4fca-97d5-ac075c9e34ff.png)

### Please provide a link to a minimal reproduction of the bug

https://jsfiddle.net/datbth/b57ur4ky/44/

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Chrome Version 105.0.5195.125 (Official Build) (64-bit)  
Ubuntu 22.04.1 LTS
Zone.js 0.11.8
```

### Anything else?

I know that practically almost all browsers are supporting `preventDefault` and `returnValue` to negate the unload ([ref](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event#browser_compatibility)). But my bigger concern is about how zone.js is handling the return values of event handlers and whether it breaks other events as well.

**Comment by Maximaximum** [comment]
Yeah, I'm experiencing this issue as well.

@datbth Have you found, by any chance,  a workaround that would allow you to force the browser to show the confirmation dialog from within an Angular application?

**Comment by JiaLiPassion** [comment]
I created a PR to fix this one.

**Comment by cklogs** [comment]
@alxhub @pkozlowski-opensource 
Has there been any movement on this issue?
After upgrading from Angular 15 -> 16, we are seeing this issue and are no longer able to trigger alerts when the user closes a tab, etc.

This unfortunately is severly breaking behavior, because it makes our forms much more brittle if the user accidentally closes a tab.

Any information on the state of this issue (and the fix) would ne nice.

**Comment by cklogs** [comment]
@alxhub @pkozlowski-opensource @JiaLiPassion 

Curious if there is any movement on this issue. It's still affecting our application on v16.

**Comment by jonsoa** [comment]
Do we have an update on this issue? After migrated our application to Angular 16, the beforeunload doesn't work anymore as expected.  As workaround we did somethind like this and it works.

```
 @HostListener('window:beforeunload', ['$event'])
  beforeUnloadHandler(event) {
    if (condition) {
      event.returnValue = 'close';
    }
  }
```

**Comment by JiaLiPassion** [comment]
I will check it again this week.

**Comment by cklogs** [comment]
@JiaLiPassion Curious if there is an update on the status of this issue.

**Comment by oleh-kazban-gl** [comment]
I have the same problem too [52256](https://github.com/angular/angular/issues/52256)

**Comment by aparzi** [comment]
Hi @JiaLiPassion, have you fixed the problem? In case you could merge it
