### ISSUE TITLE
Service Worker documentation outdated?

### ISSUE THREAD

**Issue by icguy** [angular/angular#47583]
### Describe the problem that you experienced

In the [service worker documentation](https://github.com/angular/angular/blob/bcc4a95c444b555272f89fda7bd04238414b11d5/aio/content/guide/service-worker-getting-started.md?plain=1#L50) it says, that `ng serve` doesn't support service workers. Is this still up-to-date? In the changelog of [v14.2.0](https://github.com/angular/angular-cli/releases/tag/14.2.0) mentions this [feature](https://github.com/angular/angular-cli/pull/23679) that solves this issue. Doesn't this deprecate the docs I mentioned?

### Enter the URL of the topic with the problem

https://angular.io/guide/service-worker-getting-started#serving-with-http-server

**Comment by alan-agius4** [comment]
Indeed that section can be removed, PR welcome.

**Comment by regulas1** [comment]
Hi There,

May I please take this up? 🙏

Regards

**Comment by alan-agius4** [comment]
Sure

**Comment by daxter44** [comment]
@alan-agius4  angular will be participated into hacktoberfest this year ? :)

**Comment by MahijithMenon** [comment]
can you assign this to me @icguy ?

**Comment by icguy** [comment]
@MahijithMenon nope, i cannot assign people to this issue since this is not my repo

**Comment by alan-agius4** [comment]
There is already a PR for this change https://github.com/angular/angular/pull/47613

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular/pull/47613
