### ISSUE TITLE
defaultUrlMatcher performs a 'split' on route.path which is always undefined

### ISSUE THREAD

**Issue by wrabelX** [angular/angular#47581]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

In [router/src/utils/config](https://github.com/angular/angular/blob/36f46c6a9d611962d11aa5e62ab301948e6217a7/packages/router/src/utils/config.ts#L131) we can see that there is a rule not to use 'path' and 'matcher' together. 
```
    if (route.path && route.matcher) {
      throw new RuntimeError(
          RuntimeErrorCode.INVALID_ROUTE_CONFIG,
          `Invalid configuration of route '${fullPath}': path and matcher cannot be used together`);
    }
```
but [defaultUrlMatcher](https://github.com/angular/angular/blob/main/packages/router/src/shared.ts#L136) tries to split route.path (which is undefined from the above assumption) and throws an error that the split method cannot be executed
```
export function defaultUrlMatcher(
    segments: UrlSegment[], segmentGroup: UrlSegmentGroup, route: Route): UrlMatchResult|null {
  const parts = route.path!.split('/');
```
Before it was possible to create a route with only a numeric pathparam (using matcher) - now it is (probably) impossible

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
