### ISSUE TITLE
Redirect url with state parameter does not navigate correctly

### ISSUE THREAD

**Issue by mmartinezcasanova20** [angular/angular#47593]
### Which @angular/* package(s) are the source of the bug?

core, platform-browser, platform-server, router

### Is this a regression?

No

### Description

I am trying to validate a code and state of a url that comes from the slack authorization 0auth flow but when receiving the state parameter it does not navigate correctly and enters through another flow.

Is there a problem in angular projects with the manipulation of state parameters in the url?

Example url:
https://ebde-2800-a4-16d1-c300-3d9c-c45d-4a2e-a781.sa.ngrok.io/slack-connect?code=3386383918165.4149441699380.0af663fdaf6bcd3b23b146164604d0ae027d380c456742ecaa06592595e95c71&state=ABCD

### Please provide the exception or error you saw

```true
Is there a problem in angular projects with the manipulation of state parameters in the url?
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.4
Node: 16.14.2
Package Manager: npm 8.5.0
OS: win32 x64
```

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
