### ISSUE TITLE
Add `style` & `styleUrl` to component definition

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular#47607]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Most components are setting `styles` or `styleUrls` to an array with a single value.

```ts
@Component({
  style: `:host { ... }`
})
class MyCmp {
}
```

P.S.: I hope that this isn't a duplicate. It feels like something that was discussed multiple times but I couldn't find the issue.
Sorry if I missed it.

### Proposed solution

It would be a nice syntactic sugar to allow `style` & `styleUrl` shortcuts.

I'd be happy to help with a PR.

**Comment by JoostK** [comment]
We've just discussed this and our feeling is that we'd rather avoid having multiple ways of achieving the same thing, so introducing two new component metadata properties as alternative to the existing ones—but with fewer capabilities—feels undesirable to the team.

That said, it might make sense to allow `styles` in particular (not `styleUrls`) to be `string | string[]`, as it's still meaningful to have multiple styles in a single template string (thus there wouldn't be a need for the property to become singular).

**Comment by antischematic** [comment]
Allowing styles to be a string instead of a string array would make single file components prettier. https://github.com/prettier/prettier/issues/8214

**Comment by yjaaidi** [comment]
`styles: string | string[]` is a nice alternative. Though, I wonder how many tools this would break as all of them assume that styles is an array.

**Comment by JoostK** [comment]
This has been done for Angular 17, except for `style` which remains `styles` but the array is no longer necessary.
