### ISSUE TITLE
CurrencyPipe should default to LOCALE_ID's currency

### ISSUE THREAD

**Issue by Jacobra93** [angular/angular#47612]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When using CurrencyPipe I expect it to default the currency to the locale supplied by LOCALE_ID, not to USD. 

https://angular.io/api/common/CurrencyPipe#description
From the docs:
"Deprecation notice:
The default currency code is currently always USD but this is deprecated from v9.
In v11 the default currency code will be taken from the current locale identified by the [LOCALE_ID](https://angular.io/api/core/LOCALE_ID) token."

From this description I would expect from v11 onwards, that USD would not be the default currency, but the wording is confusing so I'm not sure if this is intended behavior or a bug. If this is the intended behavior, maybe we could make the docs a little bit clearer.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-eec1py?file=src%2Fapp%2Fapp.module.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.1
Node: 16.14.2
Package Manager: npm 8.5.4
OS: darwin x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1300.1 (cli-only)
@angular-devkit/core         13.0.1 (cli-only)
@angular-devkit/schematics   13.0.1 (cli-only)
@schematics/angular          13.0.1 (cli-only)
```

**Comment by JoostK** [comment]
We explicitly do not want to do this; please see https://github.com/angular/angular/pull/34724#issuecomment-614496201.

**Comment by JoostK** [comment]
Although, that description is certainly inaccurate; I think we backtracked at some point after adding that message and then didn't commit with actually making that change (per my earlier comment)
