### ISSUE TITLE
Angular 14 lib not compatible with ng12/13

### ISSUE THREAD

**Issue by rafael-leal-mccormack** [angular/angular#47622]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

We create an angular 14 lib (built with partial) that is used by other projects internally in our company. We recently upgraded to ng14 and when trying to install the lib in an ng12 or ng13 app, we started receiving this error. I thought libs created through ng were meant to be backwards compatible with at least the previous 2 versions unless stated in the breaking changes log. Any idea why this error shows and why it can't be backwards compatible? Maybe cause of the the higher typescript version i imagine but not 100% sure.

```
TypeError: Cannot create property 'message' on string '/Users/JackD/dls-ignite/packages/sandbox/angular/node_modules/@ignite/angular/fesm2020/ignite-angular.mjs: 
This application depends upon a library published using Angular version 14.2.3, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.3
Node: 16.13.2
Package Manager: npm 8.19.2 
OS: darwin x64

Angular: 14.2.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                          Version
----------------------------------------------------------
@angular-devkit/architect        0.1402.3
@angular-devkit/build-angular    14.2.3
@angular-devkit/core             14.2.3
@angular-devkit/schematics       14.2.3
@angular-devkit/schematics-cli   13.3.6
@schematics/angular              13.3.9
ng-packagr                       14.2.1
rxjs                             7.5.6
typescript                       4.8.4
webpack                          5.74.0
```

**Comment by jackdriscollukg** [comment]
Any help would be appreciated 🙏

**Comment by pkozlowski-opensource** [comment]
>  I thought libs created through ng were meant to be backwards compatible with at least the previous 2 versions unless stated in the breaking changes log

Angular libs are _backward_ compatible - which means that you can use library compiled with v12 or v13 in the Angular application build with v14.

The situation you are describing is the case of _forward_ compatibility - and this is something we never had any guarantees around. Things might have been working "by chance", but again, there are no state guarantees here.

**Comment by alxhub** [comment]
When building a library, use the _minimum_ version of Angular that you would like to support. So if you want your library to be compatible down to v12 applications, use Angular v12 to build it.

**Comment by jackdriscollukg** [comment]
@pkozlowski-opensource @alxhub Thank you for the clarification 🙏  I guess we've been getting lucky up until now

**Comment by rafael-leal-mccormack** [comment]
Cool, appreciate the info. It was wild cause we had gone a couple ng versions that were backwards compatible even when we were 1-2 versions ahead of apps using us (other than ng12 when ivy was included) but we'll keep that in mind as we move forward.
