### ISSUE TITLE
Changes and deprecations in versions prior to 14 are not published

### ISSUE THREAD

**Issue by Chealer** [angular/angular#47627]
### Describe the problem that you experienced

[The _Update Angular_ page](https://angular.io/guide/update-to-latest-version), which [the URL which used to point to documentation of version 12's breaking changes](https://angular.io/guide/updating-to-version-12#breaking-changes-in-angular-version-12) now redirects to, does not document breaking changes in version 12. It only documents those of version 14, and as far as I can see, documentation of previous versions was lost, except when using websites which must mirror the documentation's content, which can be apparently be found via search engines without too much difficulty at this time.

### Enter the URL of the topic with the problem

https://angular.io/guide/update-to-latest-version

### Describe what you were looking for in the documentation

The documentation of changes of previous versions, or a link to it

### Describe the actions that led you to experience the problem

Trying to verify that issue #43311 had been properly solved

### Describe what you want to experience that would fix the problem

I am not sure what is expected to be in this field. An example would clarify.

**Comment by JoostK** [comment]
The Angular docs are versioned, so v12 docs can be found in the v12 space that's reachable from the left sidebar: https://v12.angular.io/guide/updating-to-version-12

**Comment by alan-agius4** [comment]
Closing as per above.

**Comment by Chealer** [comment]
Ah, thank you @JoostK, I missed the documentation of changes between versions 11 and 12 are indeed published on the version 12 of the documentation!

Indeed, each version's documentation seems to cover upgrading from the previous version. Additionally, [the notes for version 10](https://v10.angular.io/guide/updating-to-version-10) link to the notes for version 9.

Apologies for the incorrect report. The redirect bug is now tracked in ticket #47775 .
