### ISSUE TITLE
'Compiler' is deprecated in Angular 14

### ISSUE THREAD

**Issue by ammad172** [angular/angular#47621]
I am facing this issue in Angular 14 where compiler method is Deprecated
i was using .clearCache() method to clear cache.
but what is the alternate for above class and methods now ?

**Comment by alxhub** [comment]
`clearCache()` is a no-op: https://github.com/angular/angular/blob/c3f857975d56cac6ad3939d64f76a51455159c23/packages/core/src/linker/compiler.ts#L99

So there's no need to call it at all :)

In general, the `Compiler` interface dates back to View Engine's compiler semantics. Ivy behaves completely differently, and so all of the various `compileModuleAndAllComponentsAsync()`, etc. operations are just no longer relevant.

**Comment by ammad172** [comment]
> `clearCache()` is a no-op:
> 
> https://github.com/angular/angular/blob/c3f857975d56cac6ad3939d64f76a51455159c23/packages/core/src/linker/compiler.ts#L99
> 
> So there's no need to call it at all :)
> 
> In general, the `Compiler` interface dates back to View Engine's compiler semantics. Ivy behaves completely differently, and so all of the various `compileModuleAndAllComponentsAsync()`, etc. operations are just no longer relevant.

ok this means if I remove it from my code. No issue should be occurring and everything would be fine?
