### ISSUE TITLE
Error 404: NPM package "angular2": "2.0.0-alpha.42"

### ISSUE THREAD

**Issue by DeanB2015** [angular/angular#4764]
I'm getting an NPM error `npm ERR! 404 'reactivex/rxjs' is not in the npm registry.` when I use NPM to download "angular2": "2.0.0-alpha.42"

![reactive](https://cloud.githubusercontent.com/assets/10567383/10524204/5f1520ce-734c-11e5-9e1f-fc35947ff894.PNG)

**Comment by matthewDDennis** [comment]
make sure you are using the latest versions of node and npm.
I was having the same issue in VS2015, but adding a path to the latest node in the Web Tools External Paths fixed this.

**Comment by ericmartinezr** [comment]
see https://github.com/angular/angular/issues/4516

**Comment by DeanB2015** [comment]
@matthewDDennis Thanks for the help!  `VS2015` and an old version of `Node` is the problem.  I updated Node to the latest version and moved the $path up in the external tools order. VS2015 now downloads `angular2`.  Unfortunately, when I make the change I get other errors in VS2015, but atleast I isolated the issue.  Note: I also added the node folder and experience the same problem.  ![0285 tools-options2_15477577 1](https://cloud.githubusercontent.com/assets/10567383/10528571/fa61b70a-7364-11e5-8add-cb76d64c16cc.png)

**Comment by DeanB2015** [comment]
@matthewDDennis I'm curious what Node path your used for Web Tools External Paths?  I'm getting errors with my VS2015 when I add the latest Node version.
I added a question for the VS2015 team here:
http://stackoverflow.com/questions/33160226/how-to-update-vs-2015-cordova-node

Thanks
