### ISSUE TITLE
Grouping providers for lazy loaded standalone component

### ISSUE THREAD

**Issue by marcstee** [angular/angular#47672]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

**Case:**
One standalone component which is lazy loaded uses multiple services. Each of those should have new instance every time lazy loaded component is loaded and they have to be in the same scope to be able to use one another and share some other data (by other providers). 

**Current solution:**
Right now you can either explicitly provide those in `providers` section of component which is not ideal since it require to add every single provider (service) there each time you create a new one. 
Before standalone components you could also create an empty NgModule and use it as `providedIn: MyNgModule` in service decorator and then simply add one provider to your module which of course still works with standalone components but requirers you to use NgModule. 

**Problem:**
Since `providedIn: NgModule` will be deprecated I think it would be nice to came up with some grouping mechanizm so decorators in standalone lazy loaded components would not be blown out of proportion. 

### Proposed solution

One possible solution could be to use `providedIn: InjectionToken` or something like that and then be able to provide just this token into component decorator. 

### Alternatives considered

n/d

**Comment by pkozlowski-opensource** [comment]
> Right now you can either explicitly provide those in providers section of component which is not ideal since it require to add every single provider (service) there each time you create a new one.

The pattern we are trying to promote is to have utility function (ex. `provideRouter`, `provideHttpClient` etc.) that return an array of providers. This utility function could act as a grouping entity. 

Would this work for your use-case?

**Comment by marcstee** [comment]
@pkozlowski-opensource I do not believe it would be any different. The point is to add this token (as right now you can add ngModule) to service (provider) decorator which eliminates the need of some external grouping mechanism into which you need to explicitly declare those providers.

**Comment by pkozlowski-opensource** [comment]
@marcstee it sounds then like you need to better illustrate the use-case in questions + current problems. I'm actually having difficulty understanding what is the problem we are trying to address here. Could you share a concrete use-case with minimal code examples? Thnx!

**Comment by marcstee** [comment]
@pkozlowski-opensource I hope below explanation will be better then:

Here is an example of how I think it can be done right now with standalone components (without NgModule):
https://stackblitz.com/edit/angular-ivy-ian9x6?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Flazy-component%2Flazy-component.component.ts,src%2Fapp%2Flazy-component%2Fa.service.ts,src%2Fapp%2Flazy-component%2Fb.service.ts,src%2Fapp%2Flazy-component%2Fc.service.ts,src%2Fapp%2Flazy-component%2Flazy-component.component.html

And this is how to do it with NgModule: 
https://stackblitz.com/edit/angular-ivy-5qswvb?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Flazy-component%2Flazy-component.component.ts,src%2Fapp%2Flazy-component%2Fa.service.ts,src%2Fapp%2Flazy-component%2Fb.service.ts,src%2Fapp%2Flazy-component%2Fc.service.ts,src%2Fapp%2Flazy-component%2Flazy-component.component.html

The difference is that with NgModule I can just create one NgModule and import it once in Component and each time I like to create new service, I just add:
`@Injectable({providedIn: ProvidersModule})` and I don't have to provide it in any outside file. Just use it like any other service with `providedIn: 'root'`.

**Comment by Totati** [comment]
What about this: https://stackblitz.com/edit/angular-ivy-fsbg52?file=src/app/lazy-component/lazy-component.component.ts

**Comment by marcstee** [comment]
@Totati it still requires you to add every single service into this array. Better then providing it directly into component but still I think current way with `@Injectable({providedIn: ProvidersModule})` is way easier and more natural since basically it works just like `providedIn: 'root'` but gives you singletons on component level not the whole app. So when you need service to be singleton on app level you use `root` and if you need it on standalone component level then you use some other token - currently NgModule.
