### ISSUE TITLE
How to hide the specific parameters from queryparams in url in angular?

### ISSUE THREAD

**Issue by PragGawande** [angular/angular#47675]
### Describe the problem that you experienced

    this.router.navigate(['/'],{queryParams:{a1:a,b1:b,c1:c,d:d}});

I wanted to hide only parametes a1 and b1

Right now the browser url is fetched as
https://localhost:4200/?a1=a&b1=b&c1=c&d1=d

The url should be shown as below
https://localhost:4200/?c1=c&d1=d

Tried skiplocationchange but it is hiding all parameters.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
