### ISSUE TITLE
Creating custom pipes docs contain dead links.

### ISSUE THREAD

**Issue by rod7760** [angular/angular#47679]
### Describe the problem that you experienced

```
To examine the behavior of the exponentialStrength pipe in the [live example](https://angular.io/generated/live-examples/pipes-custom-data-trans/stackblitz.html) / [download example](https://angular.io/generated/zips/pipes-custom-data-trans/pipes-custom-data-trans.zip), change the value and optional exponent in the template.
```

I clicked these links at the bottom of the page to view a live demo, and I received a page not found. 

### Enter the URL of the topic with the problem

https://angular.io/guide/pipes-custom-data-trans

### Describe what you were looking for in the documentation

A live example of a custom pipe.

**Comment by trekladyone** [comment]
Issue appears to be fixed.  Clicked on the links, and they work.
