### ISSUE TITLE
Form / Input .valueChanges fires unexpectedly 

### ISSUE THREAD

**Issue by robwormald** [angular/angular#4768]
When binding to form inputs' valueChanges observable, methods attached to elements will trigger valueChanges to fire unexpectedly.

Reproduction: http://plnkr.co/edit/aBvtMSfBsSZcAH83GUjN?p=preview
Steps: 
- Type in input box, observe valueChanges observable logging values (expected). 
- Click button (which is outside of form) - observe observable logging values (unexpected)

cc @vsavkin

**Comment by Gallopaway** [comment]
This issue still exists when you use md-input

**Comment by dgroh** [comment]
this issue still exists when using `<input type='numeric'>`

**Comment by manpuriasudip** [comment]
this issue still exists when using mat-input
