### ISSUE TITLE
auto import Module or another standalone Component in template like WebStorm for    VS CODE (The most popular and best text editor)

### ISSUE THREAD

**Issue by tu-hai** [angular/angular#47689]
### Description

Automatically or hint to import other modules or standalone components in the html themelate if the component is not already imported  for VS code 

### Proposed solution

Angular 14 version with standalone on VS code does not automatically import other standalone components or modules in .html file for example: automatically Or suggests to import MatCardModule in
@Component if HTML has tag <mat-card></mat -card>

### Alternatives considered

Webstorm has done a great job with this impo
![good job](https://user-images.githubusercontent.com/37888689/194452967-76003050-cd26-4fcd-bd8e-4973f6adea16.jpg)
rt feature. But given the popularity, VS code should also have this features

**Comment by kbrilla** [comment]
Well it's already on its way: #47088

**Comment by pkozlowski-opensource** [comment]
Yep, this is work in progress, no need to track it in a separate issue as we've got PRs already.
