### ISSUE TITLE
Injecting LifeCycle in a root component results in a cyclic dependency.

### ISSUE THREAD

**Issue by rkirov** [angular/angular#477]
I think the simplest way to fix this is to inject `Injector` into the lifecycle, and than manually look up the `ChangeDetector` from the `Injector` in the `tick()` method.

See: https://github.com/angular/angular/blob/master/modules/core/src/life_cycle/life_cycle.js#L10

**Comment by vsavkin** [comment]
Try using `@InjectLazy` to solve the problem.
