### ISSUE TITLE
Angular 14 and Jquery?

### ISSUE THREAD

**Issue by hpellegrino** [angular/angular#47706]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

After moved from angular 8 to 14, I started seeing the following error. 

### Please provide the exception or error you saw

```true
./node_modules/jquery-ui-pack/jquery-ui.css:8:0 - Error: Module parse failed: Unexpected token (8:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
|
> .ui-draggable-handle {
|       -ms-touch-action: none;
|       touch-action: none;

./node_modules/jquery-ui-pack/jquery-ui.structure.css:11:0 - Error: Module parse failed: Unexpected token (11:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  * http://api.jqueryui.com/category/theming/
|  */
> .ui-draggable-handle {
|       -ms-touch-action: none;
|       touch-action: none;

./node_modules/jquery-ui-pack/jquery-ui.theme.css:17:0 - Error: Module parse failed: Unexpected token (17:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| /* Component containers
| ----------------------------------*/
> .ui-widget {
|       font-family: Arial,Helvetica,sans-serif;
|       font-size: 1em;
```

**Comment by JoostK** [comment]
[`jquery-ui-pack` is loading CSS files using `require` statements](https://unpkg.com/browse/jquery-ui-pack@1.12.3/index.js), which is non-standard and not supported by the Angular CLI.

I suspect you could update your import paths from `jquery-ui-pack` to `jquery-ui-pack/jquery-ui` and load the CSS files manually (either using `styles` in `angular.json`, or by @importing them in the apps styles.css file)

---

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by hpellegrino** [comment]
I checked and it is using @import , not require stmt...
