### ISSUE TITLE
Feature: Add/Attach directive to dynamically created component (to component host)

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#47728]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Currently when I am creating component dynamically, using `ViewContainerRef.createComponent()` (or same works for `createComponent` function) i have no option how to add/attach directive to newly created component.

I case that i have list of dynamic components (various components) rendered, all implements same interface it would be awesome to have option to dynamically add/attach `Directive` to host element of component.

This would add ability to creator of dynamic component to manage which directives are attached to which dynamic component instance.

### Proposed solution

Extend *options* for  `ViewContainerRef.createComponent()` (also for `createComponent` function) with array of "Type<AnyDirective>" which would create also instances of specified directives on component host with all life cycle stuff.

Let say `createComponent<C>(componentType: Type<C>, options?: { index?: number; injector?: Injector; ngModuleRef?: NgModuleRef<unknown>; environmentInjector?: EnvironmentInjector | NgModuleRef<unknown>; projectableNodes?: Node[][]; directives?: Type<unknown>[]; }): ComponentRef<C>`

### Alternatives considered

Or some other way how to attach directive to dynamic component dynamically.

**Comment by crisbeto** [comment]
This will be possible with the new directive composition API in Angular v15. E.g. on the component that you're passing into `ViewContainerRef.createComponent`, you can do the following:

```
@Component({
  hostDirectives: [ExtraDirOne, ExtraDirTwo]
})
class SomeComp {}
```

**Comment by mlc-mlapis** [comment]
@crisbeto Not sure how you exactly think your snippet, but it looks like a static definition.

**Comment by crisbeto** [comment]
Regarding changing the directives dynamically: it's unlikely that we'll support it since we generally don't want to have multiple APIs that do roughly the same thing. Also if we allow both `hostDirectives` and directives passed through `createComponent`, the execution order is unclear.

Regarding `setInput`: it works on host directives as well.

**Comment by mlc-mlapis** [comment]
Fine, now it's clear, thanks.

I hope, there will be a way how to define the default behavior.
> Also if we allow both hostDirectives and directives passed through createComponent, the execution order is unclear.

**Comment by kukjevov** [comment]
@crisbeto @pkozlowski-opensource  well this is not good, because we have dynamic components, that are created not by us, but only consumed by us and i need to attach directive to these "3rd party components". And also attaching these directives is configurable, so that means once again we will have to to it old way, that means manualy creating directive instance and calling all its lifecycle methods manually to work properly. 

These directives are not meant to have inputs and outputs just modify and add some functionality over html element.

So once again there will be no clean solution, only work arounds and "hacking". :(

**Comment by Harpush** [comment]
> Regarding changing the directives dynamically: it's unlikely that we'll support it since we generally don't want to have multiple APIs that roughly the same thing. Also if we allow both `hostDirectives` and directives passed through `createComponent`, the execution order is unclear.
> 
> Regarding `setInput`: it works on host directives as well.

Concerning order - I think that's pretty much the same as regular directives. Imagine a component with host directive which I declare in the html. I can put a custom directive on it and there is a known order of execution. I see no difference from creating a dynamic component and adding a directive to it. It's the same as any dynamic API compared to static API in template.

**Comment by mlc-mlapis** [comment]
@crisbeto But it's not the same, doesn't it? Without the possibility to pass directives through `createComponent`, it would mean the creation of wrapped components all the time.

> we generally don't want to have multiple APIs that roughly the same thing.

**Comment by kukjevov** [comment]
@pkozlowski-opensource @crisbeto guys is this even worth consideration? This feature would make awesome change to using angular dynamically. As @Harpush said this should not be problem.

Thx
