### ISSUE TITLE
QueryList: `changes` is initially called with an empty list...

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#4772]
which seems wrong, since nothing changed, it went from empty list to empty list.

I'd expect the first .changes stream event to come in when at least a single item was found.

**Comment by mhevery** [comment]
I think that is correct behavior. It is saying that the list when from unknown to empty. Imagine that the list would be created with 10 items, you would expect the callback. So as you decrease the number of items, in list it gets called until we reach 0 items, we would not call you? that is not right. Empty array is still information and it should be delivered.

**Comment by mhevery** [comment]
This has been resolved as we no longer inject into constructor but rather set properties on component after the query has been resolved.

**Comment by matanlurey** [comment]
:+1:
