### ISSUE TITLE
Feature Request for AbstractControl.value$ and AbstractControl.status$ Observables

### ISSUE THREAD

**Issue by UserGalileo** [angular/angular#47739]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

Angular forms expose 2 Observables: `valueChanges` and `statusChanges`.

Both of them are hot Observables, meaning that if you subscribe after the last change has emitted, you don't receive the value of the control (or its status) until it changes again.

This is annoying in case we want to calculate derived states from the form via RxJS.

Instead of this:

```ts
fullName$ = this.form.valueChanges.pipe(
  map(({ name, surname }) => name + ' ' + surname)
)
```

We'd have to introduce `startsWith`:

```ts
fullName$ = this.form.valueChanges.pipe(
  startsWith(this.form.value),
  map(({ name, surname }) => name + ' ' + surname)
)
```

But this isn't even enough, because if the subscriber arrives too late (eg. ngIf + async pipe), `startsWith` will return the **initial** value of the control, as I explained [in this article](https://michelestieven.medium.com/angular-derived-values-from-forms-with-rxjs-48760807ed1e?sk=93001042b44c39420848ba2764731f67).

In many occasions I suggested something like this:

```ts
function valueChanges(control: AbstractControl) {
  return defer(() => of(control.value)).pipe(
    concatWith(control.valueChanges)
  )
}

// Always reliable
fullName$ = valueChanges(this.form).pipe(map(...));
```

And same for the status. It's not the end of the world, but it's yet something more that the dev has to add to its cauldron of `utilities.tsx` and remember to use.

### Proposed solution

I think it'd be very convenient to provide 2 more Observables: `value$` and `status$`, which always replay the latest value of the control to the subscribers.

```ts
fullName$ = this.form.value$.pipe(map(...));

canSubmit$ = this.form.status$.pipe(map(...));
```

### Alternatives considered

Using getters:

```ts
get fullName() {
  const { name, surname } = this.form.value;
  return name + ' ' + surname;
}
```

But this is not reactive programming and it has several drawbacks, such as:
- Worse performance
- No async flows, debouncing / throttling is hard, no flattening operator capabilities...

**Comment by UserGalileo** [comment]
Sorry, I just found this is part of an open issue, probably: https://github.com/angular/angular/issues/10887

Didn't find it when I opened mine, damn :) I think this should be closed and in case reopened after 15.x if this feature is not included there.

**Comment by angelaki** [comment]
Was just sufferin a similar issue. For now you can go with

`defer(() => this.control.valueChanges.pipe(startWith(this.control.value))).pipe(shareReplay(1))`

The defer will ensure you get the current value **on subscribe**, not on defining the observable. The shareReplay will repeat it for every subsciber.
