### ISSUE TITLE
@angular/flex-layout 14.0.0-beta.40 causes: TS2420: Class 'MockMediaQueryList' incorrectly implements interface 'MediaQueryList'

### ISSUE THREAD

**Issue by VashJuan** [angular/angular#47736]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Just did a minor @angular version update (14.2.4 to 14.2.5) in my typescript app and now get:

`Build at: 2022-10-11T18:45:33.462Z - Hash: 3679546381d116f8 - Time: 2836ms

Error: node_modules/@angular/flex-layout/core/match-media/mock/mock-match-media.d.ts:59:22 - error TS2420: Class 'MockMediaQueryList' incorrectly implements interface 'MediaQueryList'.
  Type 'MockMediaQueryList' provides no match for the signature 'new (): EventTarget'.

59 export declare class MockMediaQueryList implements MediaQueryList {`

### Please provide the exception or error you saw

```true
`Build at: 2022-10-11T18:45:33.462Z - Hash: 3679546381d116f8 - Time: 2836ms

Warning: D:\Projects\RangerTrak\rangertrak\src\app\shared\services\field-report.service.ts depends on 'leaflet'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Error: node_modules/@angular/flex-layout/core/match-media/mock/mock-match-media.d.ts:59:22 - error TS2420: Class 'MockMediaQueryList' incorrectly implements interface 'MediaQueryList'.
  Type 'MockMediaQueryList' provides no match for the signature 'new (): EventTarget'.

59 export declare class MockMediaQueryList implements MediaQueryList {`
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.2.5
Node: 18.3.0 (Unsupported)
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 14.2.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.5
@angular-devkit/build-angular   14.2.5
@angular-devkit/core            14.2.5
@angular-devkit/schematics      14.2.5
@angular/cdk                    14.2.4
@angular/flex-layout            14.0.0-beta.40   <---- How did this get released?!!!!
@angular/google-maps            14.2.4
@angular/material               14.2.4
@schematics/angular             14.2.5
rxjs                            7.5.7
typescript                      4.8.4

Warning: The current version of Node (18.3.0) is not supported by Angular.
```

### Anything else?

I generally use Evergreen Angular (from Visual Studio Code) to update once or twice a week and this just started happening yesterday. I 'NEVER' go for the 'next' version - at least not intentionally! Why did I get the beta version of 
@angular/flex-layout???

My program is at [github.com/eoc.online/rangertrak](https://github.com/EOCOnline/rangertrak), but I'm not doing anything fancy...

**Comment by VashJuan** [comment]
Oh, also reported already as:
https://github.com/angular/flex-layout/issues/1423

**Comment by JoostK** [comment]
Let's track this in https://github.com/angular/flex-layout/issues/1423, as this repo doesn't contain `@angular/flex-layout`.
