### ISSUE TITLE
Classes with the same name from different libraries can trample protoChangeDetectorFactories

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#4774]
since protoChangeDetectorFactories's map keys are based on non-qualified type names.

@vsavkin expects @tbosch's latest compiler changes will fix this bug.

**Comment by mhevery** [comment]
Per @vsavkin this should not be an issue in the new compiler, once it is synced to google3 since we no longer look things up with strings.

**Comment by jbdeboer** [comment]
If you could point to the test case where this is verified, that would be great.
