### ISSUE TITLE
Form Control: If the initial value contains a CRLF code, formControl.value.length will be more than the actual value

### ISSUE THREAD

**Issue by komura-c** [angular/angular#47741]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

If the initial value of a form control contains a CRLF code,`formControl.value.length` will be more than the actual value.
Entering a new value or deleting a value seems to correct it.
My version is version 13, but I reproduced it with newer version.

I tried binding with a textarea tag and an input tag, but both gave the same result.

![formControlSample](https://user-images.githubusercontent.com/37304826/195254832-2ae7034e-0f56-40f0-bf6d-27f0366b412a.gif)

```
    this.form = this.fb.group({
      text: [
        'angular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\nangular\r\n',
        [Validators.required, Validators.maxLength(360)],
      ],
    });
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-enyse3

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.7
Node: 16.17.1
Package Manager: npm 7.24.2
OS: darwin x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.7
@angular-devkit/build-angular   13.3.7
@angular-devkit/core            13.3.7
@angular-devkit/schematics      13.3.7
@angular/cdk                    12.2.13
@angular/cli                    13.3.7
@angular/fire                   7.4.1
@angular/flex-layout            12.0.0-beta.35
@angular/material               12.2.13
@schematics/angular             13.3.7
rxjs                            6.6.7
typescript                      4.5.5
```

**Comment by JeanMeche** [comment]
Is it really a bug or a feature ? 

`'test-angular\r\n'.length` return 14 in JS and that's what value returns.

**Comment by dylhunn** [comment]
I don't think this is angular-specific behavior -- you are actually observing the native behavior of javascript! If you find a place where Angular _differs_ from the JS behavior, that's something we could potentially fix.
