### ISSUE TITLE
Angular 14 breaks lazy loading error handling?

### ISSUE THREAD

**Issue by nunoarruda** [angular/angular#47746]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

In Angular <= 13 I had `loadChildren` error handling, like so:

```TS
{
    path: 'test',
    loadChildren: () =>
      import('./test/test.module')
        .then((m) => m.TestModule)
        .catch((e) => {
          // Add your error handling here
        }),
  }
```

But this broke when I upgraded to Angular 14:
<img width="310" alt="Screenshot 2022-10-12 at 16 58 35" src="https://user-images.githubusercontent.com/1189149/195393282-f61332b5-33b6-4a4d-bf15-663563172ac1.png">

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-mghte3?file=src%2Fapp%2Fapp-routing.module.ts

### Please provide the exception or error you saw

```true
Type 'Promise<void | typeof TestModule>' is not assignable to type 'Type<any> | Routes | NgModuleFactory<any> | Observable<Type<any> | Routes> | Promise<Type<any> | Routes | NgModuleFactory<...>>'.
  Type 'Promise<void | typeof TestModule>' is not assignable to type 'Promise<Type<any> | Routes | NgModuleFactory<any>>'.
    Type 'void | typeof TestModule' is not assignable to type 'Type<any> | Routes | NgModuleFactory<any>'.
      Type 'void' is not assignable to type 'Type<any> | Routes | NgModuleFactory<any>'.(2322)
index.d.ts(1173, 44): The expected type comes from the return type of this signature.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.5
Node: 16.17.1
Package Manager: npm 8.15.0 
OS: darwin x64

Angular: 14.2.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1402.5
@angular-devkit/build-angular      14.2.5
@angular-devkit/core               14.2.5
@angular-devkit/schematics         14.2.5
@angular/cdk                       14.2.4
@angular/flex-layout               14.0.0-beta.40
@angular/material                  14.2.4
@angular/material-moment-adapter   14.2.4
@schematics/angular                14.2.5
rxjs                               7.5.7
typescript                         4.7.4
```

### Anything else?

I also noticed that Angular/TS will not complain if I do not add a `catch` callback:

<img width="242" alt="Screenshot 2022-10-12 at 17 03 59" src="https://user-images.githubusercontent.com/1189149/195392817-5fd0240b-ed82-4bea-93df-c990a092617b.png">

**Comment by JoostK** [comment]
This is likely due to #45524, which was released as breaking change in Angular 14. Your catch handler can return an empty array of routes to avoid the error.

**Comment by nunoarruda** [comment]
For anyone else wondering, @JoostK suggestion is to do the following:

```TS
{
    path: 'test',
    loadChildren: () =>
      import('./test/test.module')
        .then((m) => m.TestModule)
        .catch((e) => {
          // Add your error handling here
          
          // Fix type error
          // https://github.com/angular/angular/issues/47746
          return [];
        }),
}
```

While this works, it feels weird/hacky/unnecessary. If anyone has any other/better way to do lazy loading error handling please let us know.
