### ISSUE TITLE
When lazy loaded module, params is always empty Angular 13

### ISSUE THREAD

**Issue by narendrasinghrathore** [angular/angular#47745]
Is this the solution or we are missing something ?
```
RouterModule.forRoot(
      [ ],
      {paramsInheritanceStrategy: 'always'}
    )
```

make sure that you have uniq "id" names

_Originally posted by @djleonskennedy in https://github.com/angular/angular/issues/31778#issuecomment-513784646_

**Comment by jessicajaniuk** [comment]
@narendrasinghrathore This is not detailed enough for us to really take any action on it. Can you re-create with the issue template and provide a stackblitz reproduction?
