### ISSUE TITLE
Angular 13 `ng new` installs `typescript@~4.6.2` but `~4.4.0` is documented as the supported version

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [angular/angular#47769]
# 🐞 Bug report

### Command

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
No.

### Description
Running `npx @angular/cli@13 new` creates a project with `typescript@~4.6.2` installed. However, the [update guide for Angular 13](https://update.angular.io/?v=12.0-13.0) mentions "Angular now uses TypeScript 4.4". Is the migration guide correct, or is `ng new` correct?

## 🔬 Minimal Reproduction
Run `npx @angular/cli@13 new` and view the version of `typescript` in the generated `package.json`.

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.3.4
Node: 14.17.6
Package Manager: npm 6.14.15
OS: darwin x64

Angular: 13.3.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.4
@angular-devkit/build-angular   13.3.4
@angular-devkit/core            13.3.4
@angular-devkit/schematics      13.3.4
@angular/cli                    13.3.4
@schematics/angular             13.3.4
rxjs                            7.5.5
typescript                      4.6.3
</code></pre>

**Comment by bob-watson** [comment]
It seems to me that if a prerequisite (like a supported version of TypeScript) changes during a minor version, the upgrade tool should mention that. ADDING support for a later version of a prerequisite doesn't seem as high of a priority as removing support for a previously supported version, but it still seems like important info, to me.

**Comment by JeanMeche** [comment]
I'll close this since we have https://angular.io/guide/versions now.
