### ISSUE TITLE
Page Not Found: live example and download example

### ISSUE THREAD

**Issue by neerajkumar161** [angular/angular#47761]
### Describe the problem that you experienced

I was browsing **Angular** docs and there was a [live example](https://angular.io/generated/live-examples/pipes-custom-data-trans/stackblitz.html) at the end of the page. But when I tried to open that link. It says **Page Not Found**.

### Enter the URL of the topic with the problem

https://angular.io/guide/pipes-custom-data-trans#example-transforming-a-value-exponentially

### Describe what you were looking for in the documentation

_I was looking for an example of How to Create Pipes for custom data transformation._

### Describe the actions that led you to experience the problem

Page not found when clicking on [live example](https://angular.io/generated/live-examples/pipes-custom-data-trans/stackblitz.html) and [download example](https://angular.io/generated/zips/pipes-custom-data-trans/pipes-custom-data-trans.zip) link is broken as well.

### Add a screenshot if that helps illustrate the problem

**_Screenshot of pages that causing issues._**

![screencapture-angular-io-guide-pipes-custom-data-trans-2022-10-13-10_14_41](https://user-images.githubusercontent.com/50705472/195505451-54eb9bd0-2d53-4e88-bf06-95e8a653491a.png)
![Screenshot from 2022-10-13 10-15-31](https://user-images.githubusercontent.com/50705472/195505501-dfc3d5d1-6078-4bee-9527-57c290796e99.png)

**Comment by trekladyone** [comment]
Issue fixed in PR #48656.
