### ISSUE TITLE
Wrong redirect for documentation of version 12's changes and deprecations

### ISSUE THREAD

**Issue by Chealer** [angular/angular#47775]
### Describe the problem that you experienced

[The _Update Angular_ page](https://angular.io/guide/update-to-latest-version), which [the URL which used to point to documentation of version 12's breaking changes](https://angular.io/guide/updating-to-version-12#breaking-changes-in-angular-version-12) now redirects to, does not document breaking changes in version 12. It only documents those of version 14.

There are obviously 2 ways to fix this:

1. Easiest: Redirect to [the new URL](https://v12.angular.io/guide/updating-to-version-12)
2. Best (I guess): Merging all upgrade information in https://angular.io/guide/update-to-latest-version

Thanks to @JoostK for [pointing out](https://github.com/angular/angular/issues/47627#issuecomment-1267638974) where the documentation can be found.

### Enter the URL of the topic with the problem

https://angular.io/guide/updating-to-version-12#breaking-changes-in-angular-version-12

### Describe what you were looking for in the documentation

The documentation of changes of version 12

### Describe the actions that led you to experience the problem

Trying to verify that issue #43311 had been properly solved

### Describe what you want to experience that would fix the problem

I am not sure what is expected to be in this field. An example would clarify.

### Provide any additional information here in as much as detail as you can

```true
I verified that some of the earlier redirects still behave properly, but may have missed some more.
```

**Comment by dylhunn** [comment]
Note: the top link on the page does have most of the info via [update guide](https://update.angular.io/?l=3&v=11.0-12.0).

**Comment by Chealer** [comment]
[The URL which used to yield the _Update Angular_ page](https://angular.io/guide/update-to-latest-version) now redirects to [a _Update Angular to v15_ page](https://angular.io/guide/update-to-version-15). Additionally, [the URL which used to point to documentation of version 12's breaking changes](https://angular.io/guide/updating-to-version-12#breaking-changes-in-angular-version-12) now redirects again to where it should.

Perhaps further changes can improve the situation, but I believe the specific issue tracked here is therefore already solved.
