### ISSUE TITLE
Angular & Node.js compatibility matrix

### ISSUE THREAD

**Issue by tayambamwanza** [angular/angular#47771]
### Describe the problem that you experienced

When working on different angular projects with different versions, sometimes I would find that I am using the wrong node.js version to install my node modules and only realize after trying to run the project. I then have to figure out which version to use and add a .nvmrc with the version for future reference. I don't see a reliable page on the documentation site that indicates which node version should be used for a specific version of Angular, rather I have to lookup changelog or blog information.

### Enter the URL of the topic with the problem

n/a

### Describe what you were looking for in the documentation

I think it would be useful to have a page with this information on the official site to make it convenient to know which version of node goes with which version of angular.

@LayZeeDK has written [Angular CLI, Angular, Node.js, TypeScript, and RxJS version compatibility matrix](https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3)

Which has been the most reliable source of this information for me. 

I would like something similar to perhaps appear under the "References" menu item.

I also believe he would be willing to assist with this work.

**Comment by alan-agius4** [comment]
Currently the supported node versions are listed in the prerequisites section in https://angular.io/guide/setup-local#prerequisites

For older version of Angular you can check the specific version of documentation (you can change the version from the left hand side navigation).

Example: https://v13.angular.io/guide/setup-local#prerequisites

I think overall, this enough for the majority of the users. Although maybe instead of the link to the package.json we can mention the version range more explicitly ie the value of the package.json engines field.

**Comment by LayZeeDK** [comment]
I think the numbers speak for themselves.

![Screenshot_20221014-200541~2.png](https://user-images.githubusercontent.com/6364586/195912663-66e6ea59-9f1d-47d2-a3ea-f89235dd9c30.png)

This is a constant source of confusion to Angular developers which is the reason I have maintained this Gist for 4 years.

It's not only a question about Node.js support. In early to not so recent versions, it's a matter of matching the Angular CLI version to the Angular version. It's also a matter of finding compatible TypeScript, RxJS, and Zone.js versions (Zone.js currently missing from my compatibility matrix).

Nx has recently adopted similar compatibility matrices in their documentation.

**Comment by LayZeeDK** [comment]
@alan-agius4 
The documentation page you mention has the same text and links for every Angular version:
> Angular requires an [active LTS or maintenance LTS](https://nodejs.org/about/releases) version of Node.js.
> For information about specific version requirements, see the engines key in the [package.json](https://unpkg.com/browse/@angular/core/package.json) file.

When we browse a previous version of Angular, the documentation states that it requires an LTS version of Node.js even if that version of Angular doesn't support what are now LTS versions of Node.js.

**Comment by tayambamwanza** [comment]
@alan-agius4 Thanks for your response, I didn't think to checkout that page, actually older versions of Angular, e.g. angular 6 were explicit about which version to use.

I know this maybe easy to dismiss, it is a nice to have rather than a need to, I do think there are some advantages to using the Matrix and also just initially my experience that can make this more convenient for angular devs:

- When I googled what version of node should I use for Angular 10 for example, the first result was from stackoverflow, the most upvoted answer is a copy paste of the matrix, and other results link to the matrix or a similar version of it,  this suggests that it's a convenient reference for Angular Devs and for Library maintainers as well (correct rxjs version etc)

- The current method as it is now initially leads to incorrect information and extra steps to see what I need, when I go to the angular 13 Docs, and click package.json it takes me to angular 14 (although I can switch versions there). So basically I would visit angular.io, switch versions, open package.json then switch versions again, vs visiting a page that has all the information I need in a central location.

- Perhaps you might be able to some how get the results to show from a google search too, I'm not 100% sure how it works but I believe you can indicate certain information in your html for google to detect your list and provide specific results, e.g. if I searched what version of Angular X works with Node or RXJS, google could pick it up from the page and give me the answer directly (great DX, cut the process down to basically one step)

- Finally there is the benefit of @LayZeeDK having done most of the groundwork, which would save time in implementing it, then you would only need to update it for every major angular version but the information would stay relevant on every version it's used unlike the current setup.

- I don't know about anyone else but I would definately appreciate it and as I'm bringing my old angular apps up to date I will definately be using it a lot.

**Comment by bob-watson** [comment]
@tayambamwanza @LayZeeDK, I'm the documentation lead for angular.io. I agree that this would be a valuable addition to the documentation. If you'd like to incorporate this table into angular.io, let me know and we can make that happen.

**Comment by LayZeeDK** [comment]
Sounds good, @bob-watson ☺️

This is what Nx have done
- https://nx.dev/workspace/nx-nodejs-typescript-version-matrix#nx,-nodejs-and-typescript-compatibility-matrix
- https://nx.dev/angular-nx-version-matrix#nx-and-angular-version-compatibility-matrix

It's helpful for many use cases whether maintaining a library, dusting off an old example, maintaining, or upgrading an Angular workspace.

How do you suggest we incorporate something similar into the Angular documentation?

**Comment by bob-watson** [comment]
@LayZeeDK  Sorry to drop off the map like that.

The format you have at https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3 seems like a good place to start. I was thinking an AIO page that was formatted in a similar way to that.

If you wanted to create a PR with a new file: `versions.md` in `/angular/aio/content/guide`, I can polish it up and put it into the ToC. We can then add an item to our release version checklist to update it as required going forward.

Likewise, if you just wanted to let one of us on the Angular tech writing team to copy the content from your gist page, we could do that, too.

I'm happy to work with you to make this happen.

**Comment by JeanMeche** [comment]
This issue can be closed with the merge of #48753 (maybe @alan-agius4  you can do it)

**Comment by tayambamwanza** [comment]
Wait can I close it?

**Comment by JeanMeche** [comment]
Yes. The page is available here : https://angular.io/guide/versions !

**Comment by tayambamwanza** [comment]
> Yes. The page is available here : https://angular.io/guide/versions !

Yes! Thank you.

**Comment by LayZeeDK** [comment]
Thank you for your encouragement to contribute this, @tayambamwanza ❤️
