### ISSUE TITLE
Breaking changes in Angular version 12: Broken TypeScript entry

### ISSUE THREAD

**Issue by Chealer** [angular/angular#47777]
### Describe the problem that you experienced

[The _Breaking changes in Angular version 12_ section of the _Updating to Version 12 page_](https://v12.angular.io/guide/updating-to-version-12#breaking-changes-in-angular-version-12) starts with:

> Add support for TypeScript 4.2. TypeScript <4.2.3 is no longer supported. The supported range of TypeScript versions is 4.2.3 to 4.2.x. See [...]

There are obviously several things wrong, but I will not file a ticket for each, so please basically take this as a request to review that entry. I will file further tickets in case something is missed.

Specific issues and observations:

- The removal of support for TypeScript < 4.2.3 and the addition of support for TypeScript 4.2 (if this makes sense) should be treated separately.
- It would be best to have a section dedicated to breaking changes and deprecations.
- "The supported range of TypeScript versions is 4.2.3 to 4.2.x." should be moved, perhaps to [_Angular versioning and releases_](https://angular.io/guide/releases), or at least fixed.
- The list of issues on that page usually uses proper sentences, but has several elements like "Add support for TypeScript 4.2" and lacks uniformity.

### Enter the URL of the topic with the problem

https://v12.angular.io/guide/updating-to-version-12#breaking-changes-in-angular-version-12

### Describe what you were looking for in the documentation

Changes in Angular version 12

### Describe the actions that led you to experience the problem

Reading the changes in Angular version 12

### Describe what you want to experience that would fix the problem

I am not sure what is expected to be in this field. An example would clarify.

### Provide any additional information here in as much as detail as you can

```true
Apologies for filing this ticket, which is a duplicate of #43311 caused by #43639.
```

**Comment by dylhunn** [comment]
To be clear, is this just an issues with the changelog entry? Or is there something applicable to the actual level of Typescript support?

**Comment by Chealer** [comment]
Hi @dylhunn ,
> To be clear, is this just an issue with the changelog entry? Or is there something applicable to the actual level of Typescript support?

Just with the presentation of the information. I don't know of anything wrong with the actual information.

**Comment by Chealer** [comment]
> Actually, I'm going to close this issue. Thank you for contributing, but I just don't agree that this is a problem. Specifically:
> 
>     1. I see no reason to treat TS <4.2.3 and 4.2 separately

Well, it's not really about <4.2.3 and 4.2 but about why they're mentioned. Removal of <4.2.3 support is a breaking change, and therefore topical in that section. Addition of new supported versions, however, is not (adding supported versions is not a breaking change).

> 
>     2. We do list breaking changes separately -- that is the whole list you've linked to :)

Yes, but there is no section dedicated to breaking changes **and deprecations**.

 
>     3. "Angular Versioning and Releases" includes specific version info for _Angular_; versions of _Typescript_ are discussed separately in release notes

Right, but typically, the version mapping of main dependencies is documented together in a way which eases comparisons ([example](https://doc.tiki.org/Requirements#PHP_)).
