### ISSUE TITLE
Documentation error in precedence of bindings and static attributes

### ISSUE THREAD

**Issue by sroucheray** [angular/angular#47784]
### Describe the problem that you experienced

I think this example on precedence is wrong.
```html
<h3>Dynamic vs static</h3>

<!-- If `classExpression` has a value for the `special` class, this value overrides the `class="special"` below -->
<div class="special" [class]="classExpression">Some text.</div>

<!-- If `styleExpression` has a value for the `border` property, this value overrides the `style="border: dotted darkblue 3px"` below -->
<div style="border: dotted darkblue 3px" [style]="styleExpression">Some text.</div>
```
 There is no possible value in `classExpression` that can affect the `special` class. If there is a case I don't see, it should be more precisely indicated in the comment. 

While the above seems wrong there are alternative syntax that would affect the 'special' class, ie:

```html
<div class="special" [class.special]="false">
<div class="special" [ngClass]="{special: false}">
```

I think either the comment and example should be removed or the example should be changed to show the alternative syntaxes.

### Enter the URL of the topic with the problem

https://angular.io/guide/style-precedence#precedence-of-bindings-and-static-attributes
https://angular.io/guide/style-precedence#precedence-and-bindings-from-different-sources

### Describe what you were looking for in the documentation

I was looking over how precedence works with attribute binding.

### Describe the actions that led you to experience the problem

Coding a simple component

### Describe what you want to experience that would fix the problem

Update the documentation.

### Add a screenshot if that helps illustrate the problem

![image](https://user-images.githubusercontent.com/169818/196148839-19cef0fe-bc5e-4875-8e3f-d13d57bee7ad.png)

**Comment by ferrorenan** [comment]
Hey everyone, I solved this problem and made a PR!

Could you guys take a look!? PR: https://github.com/angular/angular/pull/48636

**Comment by JeanMeche** [comment]
This issue can be closed 👍

**Comment by sroucheray** [comment]
Thanks everyone!
