### ISSUE TITLE
Add a function to provide ServiceWorker support without referencing NgModules

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#47793]
### Which @angular/* package(s) are relevant/related to the feature request?

service-worker

### Description

Based on https://github.com/angular/angular/pull/47754#issuecomment-1279952755.

We need to provide a function (like `provideServiceWorkerSupport`) to replace [the `ServiceWorkerModule.register` call](https://github.com/angular/angular/blob/main/packages/service-worker/src/module.ts#L166-L186), so that there is no need to import and use NgModule in standalone use-cases.

**Comment by MaximSagan** [comment]
Would this function be equivalent to the following?
```ts
importProvidersFrom(ServiceWorkerModule.register(...))
```

**Comment by AndrewKushnir** [comment]
@MaximSagan yes, it would be equivalent to the `importProvidersFrom(ServiceWorkerModule.register(...))` call and just return the set of providers similar to the one that is returned by the `ServiceWorkerModule.register` call.

**Comment by DibyodyutiMondal** [comment]
Just a suggestion: Is it not possible to have an overload that allows us to provide a custom url for the service-worker.

That would allow us to use something else (like workbox) to write our own service worker and use that with angular.

**Comment by AndrewKushnir** [comment]
@DibyodyutiMondal the APIs provide a way to define a script location (see https://next.angular.io/api/service-worker/provideServiceWorker). If this is not sufficient, feel free to open a feature request in the Issue tracker.

I'm going to close this ticket, since the PR that addresses it was merged (https://github.com/angular/angular/pull/48247).
