### ISSUE TITLE
Reactive forms page does not list newly added `FormRecord`

### ISSUE THREAD

**Issue by peterblazejewicz** [angular/angular#47808]
### Describe the problem that you experienced

The page skips the newly added class topic and does not `FormRecord` in the API list summary on the page.

### Enter the URL of the topic with the problem

https://github.com/angular/angular/blob/main/aio/content/guide/reactive-forms.md#reactive-forms-api-summary

### Describe what you were looking for in the documentation

The newly added class has been described in the introductory section about typed forms:
https://angular.io/guide/typed-forms#formrecord
but has not in the more generic page describing reactive forms:
https://angular.io/guide/reactive-forms

### Describe the actions that led you to experience the problem

Docs lookup, just looked for more context on `FormRecord`

### Describe what you want to experience that would fix the problem

Wrap a section with similar content already provided on the 'typed forms' page, should be OK for everyone.

**Comment by dylhunn** [comment]
Indeed, this is just missing -- we'd accept a PR to fix it.
