### ISSUE TITLE
Expose ViewResolver so it can be extended and overridden

### ISSUE THREAD

**Issue by StacyGay** [angular/angular#4780]
Expose ViewResolver from core/linker/view_resolver.ts.
ViewResolver is not accessible through the ng module.  Please open it up so we can extend, modify its behavior and override it in the Injector.

DirectiveResolver is available, I'm curious as to why ViewResolver isn't as well since it provides much more function.

**Comment by StacyGay** [comment]
To explain further, I'm looking for a work around of issue https://github.com/angular/angular/issues/4275.

If I were able to override the ViewResolver I could alter the directives being pulled from the ViewDecorator like so:

    import {DirectiveResolver, DirectiveMetadata, Injectable, Injector, Type, bind} from "angular2/angular2";
    import {ViewMetadata, ViewResolver } from 'angular2/angular2';

    @Injectable()
    export class DiViewResolver extends ViewResolver {
        _injector: Injector;
        constructor(injector: Injector) {
            this._injector = injector;
            super();
        }

        resolve(type: Type): ViewMetadata {
            console.log("View Resolver resolve: " + type);
            var metaData = super.resolve(type);
            var directives = [].concat.apply([], metaData.directives);
            metaData.directives = directives.map(d => {
                return this.resolveDirective(d);
            });
            return metaData;
        }

        private resolveDirective(type: any): any {
            var resolvedType = this._injector.getOptional(type);
            return resolvedType === null ? type : resolvedType.constructor;
        }
    }

**Comment by coryshaw1** [comment]
+1

**Comment by mhevery** [comment]
I think it is oversight.
