### ISSUE TITLE
can't bind innerText in unit tests 

### ISSUE THREAD

**Issue by Yohandah** [angular/angular#47811]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Not sure if this is a bug or not?

### Description

Considering the following Angular component :

```typescript
import { Component, Input } from '@angular/core';

@Component({
  selector: 'form-value',
  templateUrl: './form-value.component.html',
  styleUrls: ['./form-value.component.scss'],
})
export class FormValueComponent {
  @Input() label!: string;
  @Input() value!: unknown;
}
```

and its template

```html
<div class="container">
  <span class="label"> {{ label }} </span>
  
  <div class="value" [innerText]="value"></div>
</div>

```
I use `innerText` because I need the displayed text to take `\n` line returns in consideration. Which is not the case with just `{{ value }}`.

The problem is that when I execute the following JEST test for the component :

```typescript
import { ComponentFixture, TestBed } from '@angular/core/testing';

import { FormValueComponent } from './form-value.component';
import { SharedModule } from '../../shared.module';
import { CommonModule } from '@angular/common';
import { NO_ERRORS_SCHEMA } from '@angular/core';

describe('FormValueComponent', () => {
  let component: FormValueComponent;
  let fixture: ComponentFixture<FormValueComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [FormValueComponent],
      imports: [CommonModule],
    }).compileComponents();

    fixture = TestBed.createComponent(FormValueComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});

```

I have the following error :

> Error: NG0303: Can't bind to 'innerText' since it isn't a known property of 'div' (used in the 'FormValueComponent' component template).
> 1. If 'div' is an Angular component and it has the 'innerText' input, then verify that it is a part of an @NgModule where this component is declared.
> 2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

This is an error that often appears when a module is missing from the `imports` from `TestBed`, but I can't find which module `innerText` comes from. How to fix this properly ?

The only option that I thought of for now was to add `schemas: [NO_ERRORS_SCHEMA]` to my TestBed configure but it's not working as well ! Same error !

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.1.3
Node: 16.13.2
Package Manager: npm 8.14.0
OS: win32 x64

Angular: 14.2.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.6
@angular-devkit/build-angular   14.2.6
@angular-devkit/core            14.2.6
@angular-devkit/schematics      14.1.3
@angular/cdk                    14.2.5
@angular/cli                    14.1.3
@schematics/angular             14.1.3
rxjs                            7.5.7
typescript                      4.7.4
```

**Comment by Yohandah** [comment]
It's working with `[attr.innerText]` instead of `[innerText]` but is this normal ?

**Comment by pkozlowski-opensource** [comment]
You should be able to bind to `innerText`, test or not: https://stackblitz.com/edit/angular-ivy-y3cbht?file=src%2Fapp%2Fapp.component.ts

It is hard to say what is going on without a _minimal_ reproduction scenario - please share one, ideally in stackblitz.

**Comment by Yohandah** [comment]
@pkozlowski-opensource the error only occurs when running unit tests !!! Not when running code. 
I will not be able to reproduce in stackblitz then, but I can push a repo on my GitHub if you want

**Comment by pkozlowski-opensource** [comment]
> the error only occurs when running unit tests 

Can you also reproduce it in the standard CLI test setup? Please note that our default setup does _not_ include Jest.

> I will not be able to reproduce in stackblitz then, but I can push a repo on my GitHub if you want

Sure, if this is a _truly_ minimal example of the standard CLI project setup.

**Comment by Yohandah** [comment]
@pkozlowski-opensource Indeed it looks like you were right the issue is Jest specific, which is not supported officially by the Angular team. Closing the issue :(
