### ISSUE TITLE
Pipes in ngIf and others

### ISSUE THREAD

**Issue by mikgross** [angular/angular#47828]
### Description

Support pipes in ngifs and other ng related featuers

### Proposed solution

When defining
````
<button
     (click)="toggleSnooze(ingr, ing | isNoozed: this.selectedBranch)"
>
````
The socket should be taken into accounr

### Alternatives considered

none :)

**Comment by mikgross** [comment]
It would be nice to have this !

**Comment by JoostK** [comment]
I don't quite understand the issue description given the current title.

The title asks for using pipes in `ngIf`, whereas the example does not use `ngIf` but instead requests support for a pipe within an output binding?

**Comment by pkozlowski-opensource** [comment]
Echoing @JoostK comment here - I don't understand the intention nor the problem being solved here. We would need additional background info / justification for considering changes in the framework. More specifically - for pipes in event handler - I'm not sure how it is different / better as compared to a regular function call.

**Comment by pkozlowski-opensource** [comment]
I'm going to close it for now as we haven't heard back with the exact scenario / need.
