### ISSUE TITLE
UploadProgress not working perfectly

### ISSUE THREAD

**Issue by Saytzeff-D** [angular/angular#47822]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

I'm trying to upload an audio to a server, So, i implemented upload progress to enhance the user experience. It works perfecly fine on laptop using progressbar but on mobile devices, it's not working. I need clarifications please.

**Comment by pkozlowski-opensource** [comment]
Closing for now as we haven't heard back with a reproduce scenario.

**Comment by Saytzeff-D** [comment]
The upload progress now works fine. It was the service-worker that was preventing the upload Progress from working properly.
To overcome this, I had to bypass the ngsw by passing an header to the http request
