### ISSUE TITLE
returning false from event no longer cancels prevent default

### ISSUE THREAD

**Issue by mhevery** [angular/angular#4782]
```
  <a href (click)="setupAuthToken(); false">Log in with Github</a>
```

Should prevent default because last statement is `false`. This no longer works as of the new compiler.

**Comment by wardbell** [comment]
Might be.  Victor seemed to think it was setting `preventDefault` ... which isn't the same thing as honoring it in our A2 event handling. Interesting that this reads "... no longer ...".  I couldn't find an alpha in which it worked.

**Comment by cexbrayat** [comment]
@wardbell It used to work a long time ago I think, in alpha-2x, but it doesn't anymore, I think since `(^click)` has become useless to handle bubbling events.

**Comment by vicb** [comment]
This is supposed to work (there is even a test). The problem seems to be with the evaluation of a chained expression (`setupAuthToken() && false` should work)
