### ISSUE TITLE
Typescript error when adding a new Control to FormRecord

### ISSUE THREAD

**Issue by vmuresanu** [angular/angular#47825]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

Adding a new control to an existing FormRecord that has a diferent type than initial control types, result in Argument of type 'FormControl X' is not assignable to parameter of type 'FormControl Y

**Scenario 1 (using FormBuilder):**
```ts
formRecord = this.fb.record({
    name: 'someName',
    isEmpty: true,
 });
...
this.formRecord.addControl('id', new FormControl(123));
```
Will result in error saying that Argument of type 'FormControl number' is not assignable to parameter of type 'FormControl string | FormControl boolean'.
Which is true, but it is not how FormRecord supposed to work. As per [documentation](https://angular.io/api/forms/FormRecord#description) 
[FormRecord](https://angular.io/api/forms/FormRecord) is very similar to [FormGroup](https://angular.io/api/forms/FormGroup), except it can be used with a dynamic keys, with controls added and removed as needed.

**Scenario 2 (using new FormRecord):**
```ts
formRecord = new FormRecord({
    name: new FormControl<string | undefined>('someName'),
    isEmpty: new FormControl(true)
 })
...
this.formRecord.addControl('id', new FormControl(123));
```

The error is the same

**Note:** 
Adding either a string or a boolean type will work.
```ts
this.formRecord.addControl('id', new FormControl('123'));
this.formRecord.addControl('id2', new FormControl(false));
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-tguli6?file=src%2Fapp%2Fapp.component.ts

### Please provide the exception or error you saw

```true
Argument of type 'FormControl<number>' is not assignable to parameter of type 'FormControl<string | boolean>'.
Type 'number' is not assignable to type 'string | boolean'.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular version 14.2.7
```

**Comment by jnizet** [comment]
Hi @vmuresanu 

The documentation says:

> Tracks the value and validity state of a collection of [FormControl](https://angular.io/api/forms/FormControl) instances, **each of which has the same value type**.

and 

> [FormRecord](https://angular.io/api/forms/FormRecord) accepts one generic argument, **which describes the type of the controls it contains**.

(emphasis mine)

So that error is expected, since all the controls in the record are supposed to have the same type.

**Comment by vmuresanu** [comment]
Is there a way to create a dynamic FormGroup / FormRecord with arbitrary value type without casting it to any?
```ts
formRecord = new FormRecord<any>({
    name: new FormControl<string | undefined>('someName'),
    isEmpty: new FormControl(true)
 })
...
this.formRecord.addControl('id', new FormControl(123));
```
This will obviously work

**Comment by jnizet** [comment]
I think UntypedFormGroup is what you need then. Since you can have any key, and that key can be associated with any kind of control, you can't expect much from typing.
