### ISSUE TITLE
reportProgress not working

### ISSUE THREAD

**Issue by rick-chou** [angular/angular#47839]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

I'm using angular 14 and I'm using an upload service, I want to get a progress feedback, the code is below, but it doesn't seem to work

> repo https://github.com/rick-chou/angular-tutorial/blob/issue_reportProgress/src/views/basic-syntax/http/http.service.ts

```typescript
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { environment } from '@env';

@Injectable({ providedIn: 'root' })
export class HttpService {
  constructor(private http: HttpClient) {}

  public uploadFile(formData: FormData, type: 'single' | 'multiple' = 'single') {
    return this.http.put(`${environment.backend}/file-upload/${type}`, formData, {
      reportProgress: true,
      observe: 'events',
    });
  }
}
```

```typescript
import { Component, OnInit } from '@angular/core';
import { HttpService } from './http.service';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzUploadFile, NzUploadModule } from 'ng-zorro-antd/upload';

@Component({
  selector: 'http',
  standalone: true,
  imports: [NzCardModule, NzUploadModule, NzButtonModule],
  templateUrl: './http.component.html',
})
export class HttpComponent implements OnInit {
  public fileList: NzUploadFile[] = [];

  constructor(private http: HttpService) {}
  ngOnInit(): void {}

  public handleUpload = (file: NzUploadFile, fileList: NzUploadFile[]) => {
    const formData = new FormData();
    formData.append('file', file as unknown as File);
    this.http.uploadFile(formData).subscribe((event) => {
      console.log(event);
    });
    return false;
  };
}
```

I always only get the type of upload complete

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/HVrqX.png

### Please provide a link to a minimal reproduction of the bug

https://github.com/rick-chou/angular-tutorial/blob/issue_reportProgress/src/views/basic-syntax/http/http.service.ts

### Please provide the exception or error you saw

```true
I don't get feedback on upload progress (type = 1)
only get a reward when you're done (type = 4)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.6
Node: 16.15.0
Package Manager: npm 8.5.5 
OS: darwin arm64

Angular: 14.2.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.6
@angular-devkit/build-angular   14.2.6
@angular-devkit/core            14.2.6
@angular-devkit/schematics      14.2.6
@schematics/angular             14.2.6
rxjs                            7.5.7
typescript                      4.8.4
```

### Anything else?

my page at http://localhost:4200/basic-syntax/http

**Comment by indraraj26** [comment]
Hi

upload a very large image/file and test the progress event. Also as you are uploading locally hence It is uploading too fast due to that you are not getting event type 1

**Comment by rick-chou** [comment]
> Hi
> 
> upload a very large image/file and test the progress event. Also as you are uploading locally hence It is uploading too fast that you are not getting event type 1.
> 
> Also, it is better to post in StackOverflow.

yes,  i have tried posting in StackOverflow and tried with large files (100 mb) but none seem to work 

but `xhr.upload.onprogress` works for me 

https://stackoverflow.com/questions/74150894/angular-reportprogress-always-only-get-the-type- of-upload-complete

**Comment by indraraj26** [comment]
I am not able to reproduce it. How are you able to run backend/frontend on the same port aka 4200 ?

Stackblitz playground: https://stackblitz.com/edit/angular-ivy-e4jhta?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

**Comment by rick-chou** [comment]
> I am not able to reproduce it. How are you able to run backend/frontend on the same port aka 4200 ?
> 
> Stackblitz playground: https://stackblitz.com/edit/angular-ivy-e4jhta?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

Because I have proxy configured, but it doesn't matter. You can visit this website, I deployed the project, I have the same code as yours on the Stackblitz playground, but I can't get the output of the intermediate process, only after the upload is complete, there will be output in the console.

http://124.223.71.181/rick/angular/basic-syntax/http

**Comment by rick-chou** [comment]
Hi, Is there any progress? @indraraj26

**Comment by pin8marian** [comment]
I see an issue like this [here](https://github.com/angular/angular/issues/32429).
Did you try to add  withCredentials: true in the call? 
Like this: 
 public uploadFile(formData: FormData, type: 'single' | 'multiple' = 'single') {
    return this.http.put(`${environment.backend}/file-upload/${type}`, formData, {
      reportProgress: true,
      observe: 'events',
      withCredentials: true
    });
  }
  
  Also try to get the event type to see what is going on.
  Like this:
  public handleUpload = (file: NzUploadFile, fileList: NzUploadFile[]) => {
    const formData = new FormData();
    formData.append('file', file as unknown as File);
    this.http.uploadFile(formData).subscribe(event => {

        if (event.type === HttpEventType.DownloadProgress) {
            console.log("download progress");
        }
        if (event.type === HttpEventType.Response) {
            console.log("donwload completed");
        }
    });
    return false;
  };

Let me know what was the results

**Comment by rick-chou** [comment]
> I see an issue like this [here](https://github.com/angular/angular/issues/32429). Did you try to add withCredentials: true in the call? Like this: public uploadFile(formData: FormData, type: 'single' | 'multiple' = 'single') { return this.http.put(`${environment.backend}/file-upload/${type}`, formData, { reportProgress: true, observe: 'events', withCredentials: true }); }
> 
> Also try to get the event type to see what is going on. Like this: public handleUpload = (file: NzUploadFile, fileList: NzUploadFile[]) => { const formData = new FormData(); formData.append('file', file as unknown as File); this.http.uploadFile(formData).subscribe(event => {
> 
> ```
>     if (event.type === HttpEventType.DownloadProgress) {
>         console.log("download progress");
>     }
>     if (event.type === HttpEventType.Response) {
>         console.log("donwload completed");
>     }
> });
> return false;
> ```
> 
> };
> 
> Let me know what was the results

Thank you for your reply, in fact, before asking the question I had already tried to solve similar problems in the community, including the two you provided, but none of them worked.

**Comment by alxhub** [comment]
@rick-chou

Thanks for the reproduction. I was able to debug through it, and Angular is working as intended here. You have some kind of HTTP interceptor installed (I can't tell what it's named due to the minification) that is filtering the events out of the HTTP response stream. That's why you don't see events properly logged in the final subscriber.
