### ISSUE TITLE
Angular Test Renderer2:  TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by pacocom** [angular/angular#47856]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Please, could you help me with this problems? Thanks.

I have this problem with  Renderer2: TypeError: Cannot read property 'addEventListener' of null.
**nativeElement and #scroller exist.**

```sh
  TypeError: Cannot read property 'addEventListener' of null

      129 |     };
      130 |
    > 131 |     this.listenerScroller = this.renderer.listen(
          |                                           ^
      132 |       this.elementRef.nativeElement.querySelector('#scroller'),
      133 |       'scroll',
```

```ts
constructor(private renderer: Renderer2, private elementRef: ElementRef) {}

ngAfterViewInit(): void {
  this.scrollToTop();
}

scrollToTop() {
    const callback = (event: MouseEvent) => {
      const el = event.target as HTMLElement;
      if (el.scrollTop > 0) {
        this.hiddenBackToTop = false;
      } else {
        this.hiddenBackToTop = true;
      }
    };

    this.listenerScroller = this.renderer.listen(
      this.elementRef.nativeElement.querySelector('#scroller'),
      'scroll',
      callback
    );
  }
```

### Please provide the exception or error you saw

```true
TypeError: Cannot read property 'addEventListener' of null
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.9
Node: 14.17.6
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.9
@angular-devkit/build-angular   13.3.9
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.3.9
@angular/cdk                    13.3.9
@angular/cli                    13.3.9
@angular/language-service       14.2.2
@schematics/angular             13.3.9
ng-packagr                      13.3.1
rxjs                            6.5.5
typescript                      4.6.4
```

**Comment by jnizet** [comment]
Hi @pacocom 

This simply means that `this.elementRef.nativeElement.querySelector('#scroller')` returns null. It's an issue i your code, not a bug in Angular.
You should ask a question in a support forum, and post a minimal example (as a stackblitz) reproducing the problem if you can't understand it.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
