### ISSUE TITLE
Error in angular2-quickstart docs

### ISSUE THREAD

**Issue by jessejohnson** [angular/angular#4785]
Lines 1 and 2 should read

`var AppComponent = ng.Component({`

instead of 

`var AppComponent = ng
  ng.Component({`

Running the former in Chrome 46.0.2490.71 gave me a ` Error during instantiation of Token Promise<ComponentRef>!.` exception, the original exception being `No Directive annotation found on [object Object]`

**Comment by Foxandxss** [comment]
Thanks. There is already a PR to fix that :)

**Comment by pkozlowski-opensource** [comment]
Closing as duplicate of https://github.com/angular/angular.io/pull/268
