### ISSUE TITLE
navigation error with named router outlet when using lazy loaded module

### ISSUE THREAD

**Issue by fk-fgs** [angular/angular#47867]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I have a navigation error with named router outlet that occurs only when i use a lazy loaded module.
If i set the module to be eager loaded the problem disappears.
I have published an test Angular application which reproduces the problem : https://github.com/fk-fgs/test-aux-router-outlet-with-lazy-loading.

**app.module.ts**

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { Feature1Module } from './modules/feature1/features1.module';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    Feature1Module,
    AppRoutingModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

**app-routing.module.ts**

```
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

const routes: Routes = [
  { path: '', redirectTo: '/feature1/page1', pathMatch: 'full' },
  {
    path: 'feature2',
    loadChildren: () => import('./modules/feature2/features2.module').then((m) => m.Feature2Module)
  }
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule {}
```

**app.component.html**

```
<p>app component</p>

<p>primary router outlet navigation :</p>
<button routerLink="/feature1/page1">feature1 page1</button>
<button routerLink="/feature2/page1">feature2 page1</button>

<p>aux1 router outlet navigation :</p>
<button [routerLink]="['/', { outlets: { aux1: ['feature1', 'page2'] }}]">feature1 page2</button>
<button [routerLink]="['/', { outlets: { aux1: ['feature2', 'page2'] }}]">feature2 page2</button>

<div class="router-outlet">
    <p>primary router outlet :</p>
    <router-outlet></router-outlet>
</div>
<div class="router-outlet">
    <p>aux1 router outlet :</p>
    <router-outlet name="aux1"></router-outlet>
</div>
```

**feature1-routing.module.ts**

```
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

import { Feature1Page1Component } from './pages/page1/feature1-page1.component';
import { Feature1Page2Component } from './pages/page2/feature1-page2.component';

const routes: Routes = [
  {
    path: 'feature1/page1', component: Feature1Page1Component
  },
  {
    path: 'feature1/page2', component: Feature1Page2Component,
    outlet: 'aux1'
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class Feature1RoutingModule {}
```

**feature2-routing.module.ts**

```
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

import { Feature2Page1Component } from './pages/page1/feature2-page1.component';
import { Feature2Page2Component } from './pages/page2/feature2-page2.component';

const routes: Routes = [
  {
    path: 'page1', component: Feature2Page1Component
  },
  {
    path: 'page2', component: Feature2Page2Component,
    outlet: 'aux1'
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class Feature2RoutingModule {}
```

Feature1 and feature2 modules are functionally identical :

- A component page1 with a route to primary router outlet.
- A component page2 with a route to named aux1 router outlet.

Feature1 module is eager loaded :

- No navigation problem.

Feature2 module is lazy loaded :

- page1 navigation works.
- page2 navigation does not work and produces an error :

core.mjs:6494 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'feature2/page2'
Error: Cannot match any routes. URL Segment: 'feature2/page2'
    at ApplyRedirects.noMatchError (router.mjs:2939:16)
    at router.mjs:2921:28
    at catchError.js:10:38
    at OperatorSubscriber._error (OperatorSubscriber.js:23:1)
    at OperatorSubscriber.error (Subscriber.js:40:1)
    at OperatorSubscriber._error (Subscriber.js:64:1)
    at OperatorSubscriber.error (Subscriber.js:40:1)
    at OperatorSubscriber._error (Subscriber.js:64:1)
    at OperatorSubscriber.error (Subscriber.js:40:1)
    at OperatorSubscriber._error (Subscriber.js:64:1)
    at resolvePromise (zone.js:1211:1)
    at resolvePromise (zone.js:1165:1)
    at zone.js:1278:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25595:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:1)
    at invokeTask (zone.js:1661:1)

### Please provide a link to a minimal reproduction of the bug

https://github.com/fk-fgs/test-aux-router-outlet-with-lazy-loading

### Please provide the exception or error you saw

```true
core.mjs:6494 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'feature2/page2'
Error: Cannot match any routes. URL Segment: 'feature2/page2'
    at ApplyRedirects.noMatchError (router.mjs:2939:16)
    at router.mjs:2921:28
    at catchError.js:10:38
    at OperatorSubscriber._error (OperatorSubscriber.js:23:1)
    at OperatorSubscriber.error (Subscriber.js:40:1)
    at OperatorSubscriber._error (Subscriber.js:64:1)
    at OperatorSubscriber.error (Subscriber.js:40:1)
    at OperatorSubscriber._error (Subscriber.js:64:1)
    at OperatorSubscriber.error (Subscriber.js:40:1)
    at OperatorSubscriber._error (Subscriber.js:64:1)
    at resolvePromise (zone.js:1211:1)
    at resolvePromise (zone.js:1165:1)
    at zone.js:1278:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25595:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:1)
    at invokeTask (zone.js:1661:1)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.9
Node: 12.22.3
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.9
@angular-devkit/build-angular   13.3.9
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.3.9
@angular/cli                    13.3.9
@schematics/angular             13.3.9
rxjs                            7.5.7
typescript                      4.6.4
```

**Comment by pkozlowski-opensource** [comment]
@fk-fgs could you please try to reproduce in stackblitz so it is easier for us to investigate? Also simplify the example to the absolute bare minimum to reproduce the error?

**Comment by fk-fgs** [comment]
He is the stackblitz URL of the application i have specially created to easily produce the error : https://stackblitz.com/edit/angular-ivy-qp4j8e.

This application is quite simple :
- Two router outlets in app.component.html : primary one and "aux1" named one.
- A module Feature1Module (eager loaded) with two routed components : Feature1Page1Component routed to primary router outlet, Feature1Page2Component routed to "aux1" named router outlet.
- A module Feature2Module (lazy loaded) with two routed components : Feature2Page1Component routed to primary router outlet, Feature2Page2Component routed to "aux1" named router outlet.

Modules Feature1Module and Feature2Module are functionally identical, except that one is eager loaded and the other is lazy loaded.

In app.component.html there are four buttons with routerLink to trigger navigation for the routed components.
All navigation work except the one for Feature2Page2Component which produces an error in the console.

**Comment by atscott** [comment]
This actually looks like it's working as expected to me. Your routes are _not_ equivalent between the lazy loaded and eagerly loaded module. You have the entire `'feature1/page2'` path as part of the `aux1` named outlet for the eager module but your lazy loaded module has `feature2` in the primary outlet and `page2` in the `aux1` outlet. Your link should instead be `<button [routerLink]="['/feature2', { outlets: { aux1: [ 'page2'] }}]">feature2 page2</button>` to navigate to `https://angular-ivy-nw3gtf.stackblitz.io/feature2/(aux1:page2)`

**Comment by indraraj26** [comment]
I tried this indeed it was working fine but when you will try to navigate to other aux. I was getting outlet is already activated error. Do we have to manually deactivate outlet?

**Comment by atscott** [comment]
@indraraj26 No, this is because the way the routes are written, they conflict with each other. named outlet `aux1` can be activated twice due to 
```
{
    path: 'feature1/page2', component: Feature1Page2Component,
    outlet: 'aux1'
  }
```
and 
```
const routes: Routes = [
  {
    path: 'page1', component: Feature2Page1Component
  },
  {
    path: 'page2', component: Feature2Page2Component,
    outlet: 'aux1'
  }
];
```

That is `aux1` can be activated both on the route `/(aux1:feature1/page2)` and on the route `/feature2/(aux1:page2)`. So you can end up with an attempted navigation to `/feature2/(aux1:page2)(aux1:feature1/page2)` where `aux1` is trying to be activated twice.

Here's a stackblitz with the correct route configuration: https://stackblitz.com/edit/angular-ivy-f5uw78

**Comment by fk-fgs** [comment]
Thank you for your reply.
I have to say that i have some difficulty to fully understand how routing works with named router outlets.
But with the correct route configuration provided, there are cases where when we navigate in the named router outlet then the component displayed in the primary router outlet disappears (and vice versa).

**Comment by indraraj26** [comment]
Indeed @fk-fgs secondary outlet is getting removed while tapping between primary outlet routing and vice versa. Is it expected behavior?

**Comment by fk-fgs** [comment]
This is not the expected behavior.
I need that navigations between primary router outlet and named router outlet are independent and don't interact.

**Comment by atscott** [comment]
The conversation here is generally now a support request rather than a bug report since everything here is working as expected in the Router. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
