### ISSUE TITLE
jspm not loading from the right source (alpha29 - 44)

### ISSUE THREAD

**Issue by KhaosTheory1012** [angular/angular#4786]
Hey,
I tried to start working on my angular2 project from back in May again and wanted to upgrade to the newest alpha release to try some new stuff out but every version newer than alpha28 seems to break jspm for me.

"https://registry.jspm.io/scripts/app.js 404 (Not Found)"
"Potentially unhandled rejection [3] Error loading "scripts/app" at https://registry.jspm.io/scripts/app.js
Not Found: https://registry.jspm.io/scripts/app.js (WARNING: non-Error used)"

I tried to fix it with System.config but then I run into a problem with the file extensions not being used for loading angular2.dev.js and router.dev.js.

I Hope someone can help me ;)

**Comment by ggranum** [comment]
Have you updated JSPM? My package.json points to "jspm": "0.16.2" and "typescript": "^1.5.3" in devDependencies, and in the jspm dependencies the angular version is set to "angular2": "npm:angular2@2.0.0-alpha.36"

I'd just delete my jspm and npm directories and run install again on each of them. But that's me. I'm sure if you'll need to update your config.js file, but it wouldn't surprise me.

**Comment by KhaosTheory1012** [comment]
system.src.js:1021 GET http://localhost:8080/scripts/util/footerComponent 404 (Not Found)

getting this right now and everything else loads up properly (at least it looks like that) but i cant change fileextension to true because the imports wont work because there is no angular2/angular2.js but a .dev.js

**Comment by mhevery** [comment]
we don't support JSPM, it is community only. We recommend this instead: https://angular.io/docs/ts/latest/quickstart.html
