### ISSUE TITLE
[zone.js] Node > 16.17.1: Method Promise.prototype.then called on incompatible receiver

### ISSUE THREAD

**Issue by fmalcher** [angular/angular#47872]
Prerendering throws an error when used with a Node version > 16.17.1

# 🐞 Bug report

#### What modules are related to this issue?

- [x] builders
- [ ] common
- [ ] express-engine

### Is this a regression?

Yes, the previous version in which this bug was not present was: 14.x

## 🔬 Minimal Reproduction

Create a new v15 CLI workspace, add SSR and run prerendering:

```bash
npx -p @angular/cli@next ng new testproject --routing --style=css
cd testproject
npm run ng -- add @nguniversal/express-engine@next
npm run ng -- run testproject:prerender
```

## 🔥 Exception or Error

Warning directly after the start:

```
TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022" and "false" respectively by the Angular CLI. To control ECMA version and features use the Browerslist configuration. For more information, see https://github.com/browserslist/browserslist
```

Error at prerendering:

```
✖ Prerendering routes to testproject/browser failed.
Method Promise.prototype.then called on incompatible receiver [object Object]
```

This happens with Node v16.18.0 🔥  and v18.11.0  🔥. The error does *not* appear with Node v16.17.0 ✅ .

## 🌍 Your Environment

<pre><code>
Angular CLI: 15.0.0-rc.0
Node: 18.11.0
Package Manager: npm 8.15.1
OS: darwin arm64

Angular: 15.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0-rc.0
@angular-devkit/build-angular   15.0.0-rc.0
@angular-devkit/core            15.0.0-rc.0
@angular-devkit/schematics      15.0.0-rc.0
@nguniversal/builders           15.0.0-next.0
@nguniversal/express-engine     15.0.0-next.0
@schematics/angular             15.0.0-rc.0
rxjs                            7.5.7
typescript                      4.8.4
</code></pre>

**Comment by alan-agius4** [comment]
This can be replicated without universal by using the below code

**index.js**
```js
async function loadEsmModule(modulePath) {
  return new Function("modulePath", `return import(modulePath);`)(modulePath);
}

(async ()=> {
  require('zone.js/node')
  await loadEsmModule("@angular/core");
})();
```
```
node index.js 
```

**Comment by alan-agius4** [comment]
This seems to be caused by https://github.com/nodejs/node/pull/43728.

Following a suggestion by @JiaLiPassion I have added a temporary workaround in universal via https://github.com/angular/universal/pull/2879.

**Comment by ohois** [comment]
I can confirm that this workaround fixes this issue on my end.

**Comment by pankaj-yadav0507** [comment]
> I can confirm that this workaround fixes this issue on my end.

Noob question.

Facing the same issue. But don't know how to use that temporary workaround mentioned by @alan-agius4

**Comment by ohois** [comment]
Installed dependencies as usual and then edited the genereted *.js file

**Comment by cipchk** [comment]
@alan-agius4 When will the patch be released?

**Comment by alan-agius4** [comment]
The release is scheduled for tomorrow (Wednesday).

**Comment by renixyyj** [comment]
Still fails when @angular/service-worker is included. 
Above fix works until 
`npx ng add @angular/pwa`

**Comment by cipchk** [comment]
@alan-agius4 Yes, if the project adds `@angular/service-worker` the error is still there.

**Comment by alan-agius4** [comment]
@cipchk & @renixyyj here is a fix for the app-shell/pwa issue https://github.com/angular/angular-cli/compare/14.2.x...alan-agius4:zone-js-patch-worker?expand=1

**Comment by ZacxDev** [comment]
I'm also facing this issue and am on the latest version of angular/cli, nguniversal, and angular-devkit/build-angular

**Comment by submarines-and** [comment]
Issue remains for us trying to update to the following setup.

<img width="445" alt="image" src="https://user-images.githubusercontent.com/3114694/201670563-f695eea7-ad4f-4fec-aa8a-c31523cb1b50.png">


Happens during `prerendering` step (I guess this one might have a different build script)

<img width="805" alt="image" src="https://user-images.githubusercontent.com/3114694/201670836-a8277e19-2b81-4c06-82c5-3e4231e98b01.png">


<img width="434" alt="image" src="https://user-images.githubusercontent.com/3114694/201670929-db7a32c2-acf6-42fd-89c9-6690763edb17.png">

**Comment by alan-agius4** [comment]
@submarines-and, `@nguniversal/builders@14.2.2` should solve the issue. I am no longer able to reproduce on my side. Can you please share a minimal reproduction? Thanks. 

**Note: Node.js 18 is not officially supported in version 14.x of Angular.**

**Comment by submarines-and** [comment]
Here is a minimal repo. It was `@angular/localize` that was the bandit. It works until I add an additional language.

https://github.com/submarines-and/prerender-issue

Same issue in node 16 and 18, sorry I mentioned that version without testing myself first (and sorry I didn't immediately add a reproduction - I know the rules :D ).

**Comment by alan-agius4** [comment]
@submarines-and, thanks for the reproduction. I was able to get to the bottom of this and have a PR in flight to address this issue. 

https://github.com/angular/universal/pull/2910
