### ISSUE TITLE
Allow specifying NgZone options for createApplication()

### ISSUE THREAD

**Issue by christianliebel** [angular/angular#47886]
### Which @angular/* package(s) are relevant/related to the feature request?

core, platform-browser

### Description

The `createApplication()` method currently does not allow specifying which zone should be used. We wanted to use this method for our (NgZone-less) Angular Elements, as the method allows us to create and register the custom elements without declaring any NgModule. Unfortunately, this method internally alway creates the default NgZone, which we don't need and don't want to ship. Thus, our elements break on websites that do not ship zone.js.

### Proposed solution

Add the [`BootstrapOptions`](https://angular.io/api/core/BootstrapOptions) to the `createApplication()` options:

```
createApplication({
  providers: [],
  ngZone: 'noop',
});
```

### Alternatives considered

Currently, we went back to the old `bootstrapModule()` method that allows us to specify NgZone options but requires us to use a NgModule.

**Comment by JoostK** [comment]
Hi @christianliebel, this is something we're considering as part of #47538, but this needs some design for the exact API and ergonomics.
