### ISSUE TITLE
Improve docs with best practices

### ISSUE THREAD

**Issue by gregarega1993** [angular/angular#47890]
### Description

The documentation could use some update when teaching reactivity. I've stumbled at multiple code examples where a manual subscribe is seen as how you should use RxJS. Things like manually subscribing to an Observable and then assigning a value to a property. I think this approach is ok for beginners who are new to the framework but at least it should be mentioned that it is not the best practice. The best practice that should be documented more is the use of an async pipe and also the use of Behavior Subjects in the example.

### Proposed solution

Instead of teaching manual subscribe, the docs should always show the best practice in this case the use of async pipe.

### Alternatives considered

None

**Comment by JeanMeche** [comment]
During dicussion around the scope of the new angular.dev docs, it has been suggested that observables are an external topic and there is already extensive documentation outside.
