### ISSUE TITLE
Queue requests and release after an argument is true with interceptor.

### ISSUE THREAD

**Issue by GlauberF** [angular/angular#47898]
### Which @angular/* package(s) are relevant/related to the feature request?

common, core

### Description

I have a very specific request.
When starting the application until some elements load, I need to hold requests from a certain endpoint and only release them after a variable is true.
I believe that using interceptor is the way, but I don't know how to do that.

**Example**:
All urls that start with https://api must wait/queue.
After the release_api variable exists in the window, I release the requests to follow their normal flow.

The best place is in the interceptor and how could I do that.

### Proposed solution

.

### Alternatives considered

.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by GlauberF** [comment]
Thanks!
