### ISSUE TITLE
Looking for a way to access/modify angular template parser

### ISSUE THREAD

**Issue by jmwierzbicki** [angular/angular#47905]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler-cli, compiler, core, platform-browser-dynamic, platform-browser, platform-server

### Description

Hello. Is there any way to alter behavior of angular compiler? 

In my project I have a case where we have `translate` directive, and sometimes we provide whole html code in its element body:

```
<div translate>this is some <a href="#">link</a></div>
```
the issue is that such translation blocks may contain some invalid attributes or even directives - because of this we need to always add `ngNonBindable` in such cases. Recently we also found that sometimes our translation logic fails, as there might be some whitespaces trimmed by default. So we have to add another attribute: `ngPreserveWhitespaces` 

I was trying to add such attributes from `translate` directive level, but after studying angular compiler src, it is clear that it can not work, as these attributes are resolved during compilation time.

Another issue that would touch this subject, is that we would like to extract raw html template "as is" before it is compiled, and provide it in attribute like this:
```
<div translate pre-translation-data="this is some <a href="#">link</a>">this is some <a href="#">link</a></div>
```
Being able to do this would be huge help with translation of such texts because now we extract them from `nativeElement` which is not really fail-proof. 
It would also open new way for our QA guys for locating certain elements in their E2E tests, without writing complicated CSS selectors.

If somebody could point me in right direction on how to achieve this, it would be huge help

### Proposed solution

Add possibility to use ngNonBindable and ngPreserveWhitespaces from directive level
Add possibility to access raw html template of directive/component child. 

### Alternatives considered

If such feature is already possible, please add some examples on documentation

**Comment by pkozlowski-opensource** [comment]
At this point we are not considering parser / compiler as the external, public API. I would suggest evaluating Angular built-in translations / i18n and open specific issues against those APIs if they don't cover your use-cases.
