### ISSUE TITLE
Change Detector: Support short circuiting

### ISSUE THREAD

**Issue by vicb** [angular/angular#4790]
We should support short circuiting for:
- the ternary operator (`? :`),
- `&&`,
- `||`

I have a working proto (in dynamic mode only for now).

Todo before the PR:
- [ ] support pregen / jit,
- [ ] add coalesce support

/cc @vsavkin 
/related #4599 #3701

**Comment by pkozlowski-opensource** [comment]
I believe that this one was fixed in master via #4838
