### ISSUE TITLE
Create method to reflect type of Directive and Pipe.

### ISSUE THREAD

**Issue by va-stefanek** [angular/angular#47919]
### Description

Currently we have a method to reflect component type [reflectComponentType](https://angular.io/api/core/reflectComponentType). Unfortunately there is no way to reflect type of Directive and Pipe which might be very useful in case when we want to verify whether they are standalone. Now we are force using method from private api 'ɵisStandalone'.

### Proposed solution

Create similar method for Pipes and Directives.

### Alternatives considered

Create one common method which will verify whether something is standalone or not, eg exposing [isStandalone](https://github.com/angular/angular/blob/87074753410dfe7018afacf7bf346547278f3410/packages/core/src/render3/definition.ts#L742)

**Comment by JeanMeche** [comment]
`isStandalone` is exported as `ɵisStandalone`

So you can use `ɵisStandalone` from '@angular/core'

**Comment by JeanMeche** [comment]
To the lovely folks working on Angular, what's preventing from making `isStandalone` public ? 

Alternatively, I could submit a PR with an implementation of `reflectComponentType`  equivalents for Pipes/Directive if that were what is prefered.

**Comment by va-stefanek** [comment]
I am eager to help as well :)

**Comment by AndrewKushnir** [comment]
> what's preventing from making isStandalone public ?

@JeanMeche we've discussed this question with the team and we are ok to expose the `isStandalone` function as a public API. If someone is interested in contributing the change (the change would also require extra tests for this function) - please let us know via a comment in this thread. Thank you.

**Comment by JeanMeche** [comment]
@AndrewKushnir I'm on it !
