### ISSUE TITLE
No efficient way to evaluate quality/status

### ISSUE THREAD

**Issue by Chealer** [angular/angular#47914]
### Description

_Context: Angular is a large component and project which competes with uncountable alternatives. Before choosing it, moving to it or sticking with it, one needs to evaluate its quality / development status. Even if comparisons with alternatives may be ideal, having a rough idea of Angular's own quality would already help a lot._

While Angular's ITS tracks lots of issues, unfortunately, the project is way too large to efficiently analyze even a small representative sample of its tens of thousands of issues. [The _Issues_ page](https://github.com/angular/angular/issues) shows a list with countless pages. As I write these lines, the one shown by default links to ticket #47905 , which at first sight may not even report an actual Angular issue. On the other hand, top actual issues like #45272 do not feature on that first page at all.

Basically, the sort is random (newest tickets are listed first), and while other sorts are available, none really helps with evaluation.

### Proposed solution

By far the best solution would start by migrating to a proper ITS engine. Most importantly, mature engines provide:

- a way to set a (quite approximate) importance for each issue
- tracking of ticket validity
- tracking of issue resolution

Atlassian Jira and JetBrains Youtrack are certainly the first options to evaluate.

Unfortunately, both of these are proprietary. Bugzilla is another option which is well ahead of GitHub, but - being written in Perl - may never reach maturity.

Once tickets have been migrated, triage of ideally all tickets is of course needed to take advantage of these new possibilities and enable more meaningful sorting and filtering.

### Alternatives considered

Adding a page to the documentation treating Angular's status could also help. Such a page could link to the most important issues.

Otherwise, GitHub provides a way to ["pin" a few issues](https://docs.github.com/en/enterprise-cloud@latest/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository), allowing a most basic distinction between the very worst issues and... all the rest.

**Comment by pkozlowski-opensource** [comment]
As the public, open source project we are not ready, at this point, to move out of GitHub issues to other tools. I generally agree with the sentiment of making issues more visible / actionable and we've got a major initiative going on right now to do just this. Will communicate more in the coming weeks, stay tuned.

**Comment by Chealer** [comment]
Hi @pkozlowski-opensource ,
> As the public, open source project we are not ready, at this point, to move out of GitHub issues to other tools.

That would be unfortunate, but I would appreciate if you could clarify.

> I generally agree with the sentiment of making issues more visible / actionable and we've got a major initiative going on right now to do just this. Will communicate more in the coming weeks, stay tuned.

Thanks in advance
