### ISSUE TITLE
Using NgIf with NgFor throws errors

### ISSUE THREAD

**Issue by brandyscarney** [angular/angular#4792]
When I add `*ng-if` to an element, which also has `*ng-for`, it is causing the variable to be set to null, even though the expression in the `*ng-if` is returning true. I am trying to only show the element if the expression returns true, and not show it at all otherwise.

Plunker reproducing the issue: http://plnkr.co/edit/ozJydSz1XqiNtrVCUfm1?p=preview

Is there a way I can do this?

**Comment by vicb** [comment]
There could be only one template directive per element (`*` directive)

```
// current - invalid
      <div *ng-if="showCategory()" *ng-for="#category of categories">
        Category: {{ category.displayName }}
      </div>

// working - extra div level
      <div *ng-if="showCategory()">
        <div *ng-for="#category of categories">
          Category: {{ category.displayName }}
        </div>
      </div>

// working - single div
      <template [ng-if]="showCategory()">
        <div *ng-for="#category of categories">
          Category: {{ category.displayName }}
        </div>
      </template>
```

The error is in your example but we should report an error here - could you check if there is already a pending issue & close if this is the case ?

**Comment by thelgevold** [comment]
What is the reasoning behind the limitation of one template directive per element?
This is not the case in Angular 1.x and it seems like an unnecessary limitation IMO. It's also an annoyance when converting from Angular 1.x to Angular 2.0 since you now have to change your markup to use a wrapper element.

**Comment by vicb** [comment]
In this particular case, what exactly do you want to do if have 10 categories, but `showCategories()` returns `false`: evaluate the `if` ten times to display nothing in the end or evaluate the `if` first and do not call `for` ?

You probably want the second solution in this trivial case but to solve all the cases things have to be explicit.

**Comment by thelgevold** [comment]
One solution is to give directives priority to dictate evaluation order. In this case ng-if could take precedence over ng-for, so if ng-if === false the execution of the ng-for is skipped all together

**Comment by S-YOU** [comment]
> What is the reasoning behind the limitation of one template directive per element?

May be they don't want to walk the DOM to collect directives like angular 1 does? perf?

**Comment by vicb** [comment]
priorities does not work with 3rd-party directives (they might have different need). Being explicit work all the time.

Perf are not the problem here (and will be much better than angular 1).

**Comment by thelgevold** [comment]
In the end it's not a big deal as long as people are aware of the limitation, but I don't see why an optional directive priority property with a default value would'n't work for custom directives. Priority could then be offset to make sure CORE_DIRECTIVES always take precedence.

**Comment by alexpods** [comment]
I think, it would be very cool if directives are evaluated in the same order as they exist in the markup. For example:
```html
<div *ng-for="#name of people; #isEven=even" *ng-if="isEven">
    {{ name }}
</div>
```
could be desugared into:
```html
<template ng-for #name [ng-for-of]="people" #isEven="even">
  <template [ng-if]="isEven">
    <div>{{ name }}</div>  
  </template>
</template>   
```

while:
```html
<div *ng-if="showNames" *ng-for="#name of people">
    {{ name }}
</div>
```
could be desugared into:
```html
<template  [ng-if]="showNames">
  <template ng-for #name [ng-for-of]="people">
    <div>{{ name }}</div>  
  </template>
</template>   
```
Unfortunately, DOM NamedNodeList [doesn't guarantee to maintain any order](http://www.w3.org/TR/DOM-Level-3-Core/core.html#ID-1780488922). But maybe it's one more reason to implement #4417.

What do you think? @vicb @thelgevold @mhevery @pkozlowski-opensource

**Comment by pkozlowski-opensource** [comment]
Interesting.... This would be clear departure from HTML way of doing things (as mentioned, it doesn't guarantee order of attrs). But IMO this is a slippery path to take - can't put a finger on it, but my gut-feeling screams "no" atm :-)

I think I've got a bigger problem with the de-sugared form (there is no way I could remember / write it correctly from the top of my head...) so I agree that there is a pb to solve here.

**Comment by S-YOU** [comment]
> I think, it would be very cool if directives are evaluated in the same order as they exist in the markup. For example:

as far as I noticed, some versions of internet explorer re-order attributes alphabetically.

**Comment by mhevery** [comment]
We sort of supported this in AngularJS v1, and it created endless sets of issues. So we are not going to support this in Angular 2. There is easy work around to just nest these in a `template` tag.

**Comment by brandyscarney** [comment]
Thanks for the responses! My plunker above was very simple to show the problem. My actual use case is a bit more complex. I need to use one of the properties of the `category` to show/hide the element. 

Wrapping it in a template tag won't work for this as I won't have access to the `category` object. And I am actually using a `button` instead of a `div`, so wrapping the inner content with a NgIf will still show the button itself. 

After reading the above replies, I decided to hide the button with a class. So hopefully I don't run into problems with this approach.

I created a new Plunker to show my more complex use case for anyone that stumbles on this: http://plnkr.co/edit/hht4aH7QXKbF15o3IuSI?p=preview

Let me know if there is a better way to do this, I am still learning Angular 2. :) 

@vicb I created an issue for better error messages here: https://github.com/angular/angular/issues/4817

**Comment by vicb** [comment]
@brandyscarney thanks for creating a new issue.

You are probably looking at something like:
```
      <button *ng-for="#category of categoriesByName('communication')">
          Multi Category: {{ category.displayName }}
      </button>
```

`categoriesByName()`  would be a method on your class returning a list of categories filtered by Name.

There is one important thing: you must not return a new array each time the method is called otherwise the change detection will get confused (ie `return categories.filter(c => c.name === name)` will not work). You should only return a new array when categories have been modified. There are plans to improve this by implementing a `trackBy` functionality.

**Comment by brandyscarney** [comment]
@vicb I actually started doing it that way but thought the NgIf would be the simplest way. Thanks for mentioning it though and letting me know not to return an array each time! I'll probably end up doing it that way. :)

**Comment by lukedupin** [comment]
There is a simple work around.  In my case, I had an array of elements, but I didn't always want to show them all.

Change this:
```
<select>
  <option *ngFor="#v of attr.values" *ngIf="v.selectable" [value]="v.id">{{ v.name }}</option>
</select>
```

To work like this:
```
<select>
  <template ngFor #v  [ngForOf]="attr.values">
    <option *ngIf="v.selectable" [value]="v.id" [selected]="attribute_selected[attr.id] == v.id">{{ v.name }}</option>
  </template>
</select>
```

**Comment by Ferhatos** [comment]
Thanks you @lukedupin, works for me as expected.

**Comment by AmirTugi** [comment]
@lukedupin Why not simplifying it like this:
```
<select>
  <template *ngIf='attr.values'>
    <option *ngfor="attr of attr.values" [value]="index" [selected]="attribute_selected[attr.id] == index">{{ attr.name }}</option>
  </template>
</select>
```

Just guessing here, but this should work, anyway

**Comment by marcj** [comment]
Another way to solve probably the most common one is to improve the ngFor syntax

```
<div *ngFor="let layer of input.children.all() if input"></div>
```

**Comment by ashikjs** [comment]
I got this nice solution from
[stackoverflow Q Answer By Imal hasaranga perera](https://stackoverflow.com/questions/34657821/ngif-and-ngfor-on-same-element-causing-error
)
```
<ng-container *ngFor="let nav_link of defaultLinks" >
   <li *ngIf="nav_link.visible">
       .....
   </li> 
</ng-container>
```
