### ISSUE TITLE
Security Issue - "Forgotten timer or callBack" issue in main.js and runtimejs.

### ISSUE THREAD

**Issue by bapusahebnaik** [angular/angular#47939]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Hi There,
we have a security issue (Penetration test) raised for our application by burp suit for JavaScript SetTimeout() in main.js and runtime.js

main.js:
l=setTimeout(() => {this._callbacks=this._callbacks.filter(h=>h.timeoutId!==l),n(this._didWork,this.getPendingTasks())},s)

runtime.js:
s=setTimeout(b.bind(null,void 0,{type:"timeout",target:t}),12e4)

Defect screen shots:
![image](https://user-images.githubusercontent.com/28300624/199407510-3e992c92-daff-4a3b-9bce-cdf7aa3b17d9.png)

Angular Version used screen shots:
![image](https://user-images.githubusercontent.com/28300624/199407731-2a59c88c-eb7e-4e43-b345-7f7bffa64115.png)

As per our analysis these timeouts are coming from angular framework itself.
- Generate new angular project "ng new projectName"
- compile the code by "ng build --prod". dist folder is geneated with basic js files.
- open main.js search for setTimeout. setTimeout is used for callbacks.
- add one lazy loading router then compile code again with "ng build --prod"
- open runtime.js > setTimeout can be found with bind
Our understanding angular by default uses JavaScript 'strict mode'. And able to use "use strict" in both main.js and runtime.js.

Please suggest any solution or evidence that this will not create any security issue. Thanks

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.2.17
Node: 16.14.2 (Unsupported)
Package Manager: npm 8.5.0
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1202.17 (cli-only)
@angular-devkit/core         12.2.17 (cli-only)
@angular-devkit/schematics   12.2.17 (cli-only)
@schematics/angular          12.2.17 (cli-only)
```

**Comment by JoostK** [comment]
This code comes from

https://github.com/angular/angular/blob/3165fa3f4e439def8815870a217075e35c2684cb/packages/core/src/testability/testability.ts

from the `Testability` implementation. The timeout is only installed if you're using the `whenStable` method with an explicit timeout, which is very unlikely to be the case. Additionally, the timeout is being tracked and cancelled when the stable event occurs before the timeout timer has elapsed, so the timeout does not outlive the lifecycle of the event that is being waited for.
