### ISSUE TITLE
ngDoCheck not invoked by cdr.detectChanges()

### ISSUE THREAD

**Issue by michalgrzegorczyk-dev** [angular/angular#47931]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

**Code example:**
components: (app-child1, app-child2)

**Description:**
I'm running cdr.detectChanges() in some nested child (Child1) that has parent and also another nested child component (Child2).

**Question:**
Why if I will run detectChanges method in Child1 component - only ngDoCheck is invoked in Child2 component? Shouldn't this invoke ngDoCheck in current component (Child1) and DoCheck in Child2? How can I know that current component is also checked? I would expect simple console.log in ngDoCheck in Child1 but it's not there.

### Please provide a link to a minimal reproduction of the bug

I prepared small example: https://github.com/michalgrzegorczyk-dev/change-detection

**Comment by JeanMeche** [comment]
What do you expect `ngDoCheck` to do ? 

This is as designed.

**Comment by pkozlowski-opensource** [comment]
Here is a minimal stackblitz with the scenario, as far as I understand it: https://stackblitz.com/edit/angular-standalone-a4s18z?file=src%2Fmain.ts

**Comment by pkozlowski-opensource** [comment]
While I can see how it could be confusing, this lifecycle execution actually works as designed: `ngDoCheck` hook is only run when a component in question is used in a template.

I'm going to close this issue as the current behaviour is expected and we have no plans of changing it.
