### ISSUE TITLE
Expose _injector from @angular/router Route

### ISSUE THREAD

**Issue by janhommes** [angular/angular#47943]
### Which @angular/* package(s) are relevant/related to the feature request?

@angular/router

### Description

For a micro frontend architecture, we want to archive the same ability of lazy-loaded routes but without defining an actual route in the shell (root module). The idea is, that "plugins" (remotes) can define their routes and are "plugged" into the application (shell) itself without the shell knowing anything about the remote. This works fine by getting all injected routes of the "lazy-loaded" module:
```
const module = await import('./lazy/lazy.module');
const moduleRef = createNgModuleRef(module.LazyModule);
const routes = moduleRef.injector.get(ROUTES, [], InjectFlags.Self);
``` 

However, it turns out that the injector of any component in the `LazyModule` is the root injector.  After a lot of fiddling, I found out that you can set the injector (and I am assuming this is how the lazy-loaded route does it):
```  
const lazyRoute = routes[0][0];
// The injector can be defined by updating this not exposed property
(lazyRoute as any)._injector = moduleRef.injector;
``` 

However, as you can see, the `_injector` is internal and I need to cast the injector. 

Here is a full stackblitz as an example:
https://stackblitz.com/edit/angular-ivy-h4cksn?file=src%2Fapp%2Fapp.component.ts%3AL27

### Proposed solution

Make `_injector` public exposed from the `Route` type and document it. Remove the `_`.

### Alternatives considered

As far as I know, there is no currently defined way of loading a route lazy without defining it in `loadChildren`. So for the above use-case of "plugins", there is no real alternative.

**Comment by atscott** [comment]
We may in the future expose the injector in some capacity to address https://github.com/angular/angular/issues/37095 but I don't think making `_injector` writeable like this would be desirable. That said, from what I understand of your requirements, what you're trying to do can be accomplished instead by setting the `providers` on the route:
`lazyRoute.providers = [importProvidersFrom(module.LazyModule)]`
https://stackblitz.com/edit/angular-ivy-ezm2i2?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fhello.component.ts
