### ISSUE TITLE
Allow to provide function to evaluate state (disabled/enabled) of control every form/control value change.

### ISSUE THREAD

**Issue by va-stefanek** [angular/angular#47946]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

I think that it will be valuable to have possibility to evaluate disable/enabled status dynamically without requirement to subscribe to valueChanges and than based on some condition calling enable(), disable().

### Proposed solution

Here is example how I would see that.

```
this._fb.group<FormModel>({
      IncludeTaxes: [{
        value: false,
        disabled: this.shouldDisableIncludeTaxes(),
      }],
      ...
});


export function shouldDisableIncludeTaxes(): ValidatorFn {
  return (control: AbstractControl) => {
   if(someCondtion) {
      return true;
    }
   return false;
  }
}
```

I expect it to be evaluated every time when form group change. Example function return ValidatorFn - but in my opinion return type should be similar 

### Alternatives considered

Lack of.

**Comment by va-stefanek** [comment]
@alxhub @pkozlowski-opensource I am eager to help :)

**Comment by va-stefanek** [comment]
I can prepare some PR - but before that I would like to know whether my idea how it should work is right in terms of how forms are intended to work:

- FormControl - disable state should be revalidate whenever we call updateValueAndValidity, despite case when we call `reset` without passing `FormState`, `enable`, and `_syncPendingControls`
- FormGroup - disable state should be revalidate whenever we call updateValueAndValidity despite case when we call `enable`. 

    Additionaly in that case method to revalidate disability should be called on each child. I assume that often we would like to disable second control if the first one is invalid - e.g 
    ```
      form = this.fb.group({
        firstControl: [''],
        secondControl: [{value: 'test', disabled: (control: AbstractControl) => {
            return control.parent?.get('firstControl')?.invalid;
          }
        }]
      })
    ```
    
    There is additional concern whether we should ignore revalidating disable state of child controls whenever `enable` is called on `FormGroup`?
- FormArray - disable state should be revalidate whenever we call updateValueAndValidity despite case when we call `enable`. 

We should change the type of `AbstractControlOptions` for `FormGroup` and `FormArray` to allow passing `disabled` option as function or boolean. In case of FormControl it probably can stay as part of `FormControlState`

**Comment by dylhunn** [comment]
To make this work, disabled state would need to take a callback, or possibly an observable. This would introduce major complexity -- e.g. what happens if disabled state depends on the disabled state of a child control, which itself changes dynamically? It's a bit of a `ChangedAfterChecked` footgun.
