### ISSUE TITLE
cssClasses get confused on a reload (perhaps due to command_compiler.mergeAttributeValue())

### ISSUE THREAD

**Issue by LMFinney** [angular/angular#4795]
We are on alpha 42, and we just added the ability to reload a component via CanReuse and router.renavigate(). When we do that, we end up with some CSS getting messed up.

Specifically, we have two button bars on the same component, and we use css to defined the icons for the buttons in the bars. When the component reloads, the buttons end up with the wrong css - they end up sharing styles, so each button has two icon styles, so they all get messed up. (with just one button bar, the effect does not occur)

We think the problem might be from `command_compiler.mergeAttributeValue()`, which looks like it is concatenating styles from two sources, but we're not sure.

If we reload again (or route away and return via the back button), then we end up with three icon styles, etc.

Here is a simplified version of our ButtonBar component.
 ```typescript
    /*
     * Angular 2 decorators and services
     */
    import {Component, View} from 'angular2/angular2';
    
    /*
     * Angular Directives
     */
    import {CORE_DIRECTIVES} from 'angular2/angular2';
    import {ROUTER_DIRECTIVES} from 'angular2/router';
    
    export interface ButtonConfig {
      tooltip?:string;
      cssClass?:string;
    }
    
    export class ButtonInfo {
      constructor(private tooltip:string, private cssClass:string) {
      }
    
      title(): string {
        return this.tooltip ? this.tooltip : '';
      }
    
      cssClasses(): string {
        let result:string = '';
        if (this.cssClass) {
          result += this.cssClass;
        }
        return result;
      }
    }
    
    export function newButtonInfo(buttonInfo:ButtonConfig):ButtonInfo {
      return new ButtonInfo(buttonInfo.tooltip, buttonInfo.cssClass);
    }
    
    @Component({
      selector: 'button-bar-button',
      properties:['info']
    })
    @View({
      template: `<label></label><a href
                                    [title]="info.title()"
                                    [class]="info.cssClasses()"
                                    ></a>`,
      directives: [CORE_DIRECTIVES, ROUTER_DIRECTIVES],
      styles: [require("!raw!less!./buttonBarButton.less")]
    })
    class ButtonCmp {
      info:ButtonInfo;
    
    }
    
    export const BUTTON_SEPARATOR: ButtonInfo = newButtonInfo({
      cssClass: 'icon-separator'
    });
    
    
    @Component({
      selector: 'button-bar',
      properties:['buttons']
    })
    @View({
      template: '<button-bar-button *ng-for="#b of buttons" [info]="b"></button-bar-button>',
      directives: [CORE_DIRECTIVES, ButtonCmp],
      styles: [require("!raw!less!./buttonBar.less")]
    })
    export class ButtonBarCmp {
      buttons: ButtonInfo[];
    }
```

Update: We rewrote our button bar completely, and this no longer happens for us with the new design.

**Comment by btford** [comment]
@LMFinney @mhevery  – sounds like this isn't an issue related to routing at all.

Is this still an issue?

**Comment by LMFinney** [comment]
@btford I don't know if routing is involved - I know that I was able to invoke the problem by reloading through router.renavigate(), but the problem might be in `command_compiler.mergeAttributeValue()`.

We've rewritten that part of our app, so we're not having the problem anymore. The initial implementation used button bars embedded in a bigger component and used Javascript to define the configurations of the buttons, and the new approach extracts the button bar to its own component with the buttons defined in html.

**Comment by tbosch** [comment]
I think this is related to view caching: Angular reuses previously created
DOM elements by default, see https://github.com/angular/angular/issues/4478

You can verify by adding this provider to the providers passed to bootstrap
to deactivate View pooling:
`provide(APP_VIEW_POOL_CAPACITY, {useValue: 0}`

**Comment by pkozlowski-opensource** [comment]
We no longer do view caching so this one is obsolete. Closing.
