### ISSUE TITLE
Add type checking to template input variable

### ISSUE THREAD

**Issue by IvanVoznyi** [angular/angular#47978]
### Which @angular/* package(s) are relevant/related to the feature request?

elements

### Description

![Screenshot from 2022-11-04 21-12-44](https://user-images.githubusercontent.com/60106351/200061456-2fa874a5-203c-4217-bfc8-85b8e3753699.jpg)

![Screenshot from 2022-11-04 21-13-10](https://user-images.githubusercontent.com/60106351/200061520-fbfc9cca-7ccf-4743-9b0e-ad8f86b62274.png)

The main issue is the template variable let-* in typescript recognizes as type any.

Angular: 14.1.0

### Proposed solution

static ngTemplateVariableGuard_* = **ngTemplateVariableGuard_item**

**Comment by JoostK** [comment]
This would indeed be nice to have! It's being tracked in #28731.
