### ISSUE TITLE
Option to use AssemblyScript instead of TypeScript

### ISSUE THREAD

**Issue by TheBlckbird** [angular/angular#47983]
### Which @angular/* package(s) are relevant/related to the feature request?

_I don’t know_

### Description

I don’t know if this is possible, but it would be pretty cool if you could compile into Webassembly instead of JavaScript.

### Proposed solution

https://www.assemblyscript.org/
But I don’t know if this is good enough to use

### Alternatives considered

What should I write here?

**Comment by JeanMeche** [comment]
I think you are mistaking multiple things here : 

- AssemblyScript is a language similar to typescript that can be compiler to wasm.  The synthax is close but this is it. 
- Wasm isn't replacement for Javascript, It doesn't have the same API, in particular, you can't manipulate the DOM from wasm. 


That being said, the subject of wasm was already discussed on #22398, #22470 and #15169

**Comment by TheBlckbird** [comment]
@alxhub Ok thank you
My thought was that wasm is faster than JS
