### ISSUE TITLE
angular.io/errors is incomplete

### ISSUE THREAD

**Issue by Jeremiah-Griffin** [angular/angular#47985]
### Describe the problem that you experienced

I encountered an NG0403 error when refactoring my code. I could not find this on the angular.io/errors site, nor anywhere else on the web. Searching through the codebase  shows there to be a single mention of this error in "packages/core/test/application_ref_spec.ts";

I am not experienced with angular or its internals so i won't venture to make a pull request to the site itself, but there are errors NG0402 - NG0406 that are also listed in this file not found in the errors site. Presumably they may be encountered as well.

### Enter the URL of the topic with the problem

https://angular.io/errors

### If this problem caused an exception or error, please paste it here

```true
ERROR Error: NG0403
    at n._moduleDoBootstrap (main.js:1:104160)
    at main.js:1:103795
    at v.invoke (polyfills.js:1:6530)
    at Object.onInvoke (main.js:1:97278)
    at v.invoke (polyfills.js:1:6470)
    at M.run (polyfills.js:1:1926)
    at polyfills.js:1:16727
    at v.invokeTask (polyfills.js:1:7148)
    at Object.onInvokeTask (main.js:1:97094)
    at v.invokeTask (polyfills.js:1:7069)
```

### Provide any additional information here in as much as detail as you can

Running in edge webview2 with tauri on windows.

**Comment by Jeremiah-Griffin** [comment]
> This page references the errors documents [in here](https://github.com/angular/angular/tree/main/aio/content/errors).

I saw that page, I considered making a PR there but this is the only context given with the error: `NG0403: The module MyModule was bootstrapped, but it does not declare "@NgModule.bootstrap" components nor a "ngDoBootstrap" method. Please define one of these.`

The other messages have similar text.

I don't consider myself knowledgeable enough about the API to recommend a remedy or contribute anything meaningful aside from making a note here.

**Comment by JeanMeche** [comment]
This one is quite trivial, 

In your `main.ts` you probably have `platformBrowserDynamic().bootstrapModule(AppModule)`. 

`AppModule` is the boostrapped module and this module is missing the `boostrap` entry : 


```
@NgModule({
  imports:      [ BrowserModule, FormsModule ], // some imports. 
  declarations: [ AppComponent ], // all the components /
  bootstrap:    [ AppComponent ] // The component at the root at the app that is missing. 
})
```

**Comment by Jeremiah-Griffin** [comment]
> This one is quite trivial,
> 
> In your `main.ts` you probably have `platformBrowserDynamic().bootstrapModule(AppModule)`.
> 
> `AppModule` is the boostrapped module and this module is missing the `boostrap` entry :
> 
> ```
> @NgModule({
>   imports:      [ BrowserModule, FormsModule ], // some imports. 
>   declarations: [ AppComponent ], // all the components /
>   bootstrap:    [ AppComponent ] // The component at the root at the app,  NG403 is triggered when missing. 
> })
> ```

I appreciate your help but again to be clear, I am not looking for assistance, I had already solved the issue for myself. I'm raising an issue that the page which is supposed to document angular's enumerated runtime errors has not done so completely.

Is this not the correct forum to do so?
