### ISSUE TITLE
Should only fire output property once even if both in [outputs] and decorated w/ @Output

### ISSUE THREAD

**Issue by wardbell** [angular/angular#4798]
Consider this component:
```
@Component({
  selector: 'hero-detail',
  inputs: ['hero'],
  outputs: ['deleted'],
  template: `
    <div>
      <b>Hero Detail: {{hero?.fullName}}</b>
      <button (click)="onDelete()">Delete</button>
    </div>
  `
})
class HeroDetailComponent {

  @Input()
  hero: Hero;

  @Output()
  deleted = new EventEmitter();

  onDelete() {
    this.deleted.next(this.hero);
  }
}
```
Now we bind to it:
```
<hero-detail [hero]="currentHero" (deleted)="onDeleted($event)"></hero-detail>
```
When the user clicks the Delete button inside `<hero-detail>`, the parent's `onDeleted` method is called twice.

Remove either the `[outputs]` array or the `@Output` decoration and the  parent's method is called only once.

The number of parent method calls increase by one for each additional `@Output` decoration.

I maintain that any number of mentions as an output > 1  should still mean a single call to the parent method.

**Comment by ericmartinezr** [comment]
FWIW this was reported a few days ago, but it was closed immediatly https://github.com/angular/angular/issues/4611

**Comment by jessegood** [comment]
Is there a use case for having both? I would consider this a mistake in the code and would like the framework to tell me by throwing an exception.

**Comment by mhevery** [comment]
I think we should throw an error when the same event is registered more then once.

**Comment by wardbell** [comment]
That's ok too. I'm more of a "be tolerant in what you accept person" myself but that policy can lead us into trouble and maybe it would here. Lets do something😊
