### ISSUE TITLE
ngc --build does not do anything

### ISSUE THREAD

**Issue by BlindDespair** [angular/angular#47984]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

No

### Description

Running `ngc --build` does not provide the same result as `tsc --build`. It seems like the `--build` option is completely ignored. 
We have a relatively big monorepo with a dozen projects/libraries in Angular and NestJS and we're utilizing `ngc --noEmit` as a tool to verify validity of typescript and templates as automatic check on our pull requests. However that seems to not pickup the `tsconfig` files of all the subprojects. No matter what I do it refuses to recognize cypress types in the e2e test files as it has its own tsconfig, but this same problem is present when simply  running `tsc --noEmit`.

However typescript compiler also provides `references` and `--build` options which allow us to specify the project tree and make `tsc` build each subproject with its own config. This is very desirable but, alas, it seems like `ngc` does not support it.

For example for
```
  "references": [
    {
      "path": "tsconfig.app.json"
    },
    {
      "path": "tsconfig.spec.json"
    }
  ],
```
`tsc --build` provides this result:
![image](https://user-images.githubusercontent.com/15785773/200295966-a1931ca3-2665-40ce-a1e0-49055ce5daf7.png)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.8
Node: 16.15.0
Package Manager: npm 8.5.5
OS: win32 x64

Angular: 14.2.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.8
@angular-devkit/build-angular   14.2.8
@angular-devkit/core            14.2.8
@angular-devkit/schematics      14.2.8
@angular/cli                    14.2.8
@schematics/angular             14.2.8
rxjs                            7.5.7
typescript                      4.7.4
```

**Comment by JoostK** [comment]
`ngc` does not support project references, support for it is being tracked in #37276.
