### ISSUE TITLE
Implement the possibility to nest i18n attributes into Angular

### ISSUE THREAD

**Issue by ElenaLj** [angular/angular#48003]
### Which @angular/* package(s) are relevant/related to the feature request?

localize

### Description

As for what I tested and searched online, nesting of i18n attributes is still not possible in html files. 
However I think this aspect should be taken into consideration because oftentimes developers need to find a workaround or a solution that is not the best one.

Take into consideration this basic example:

```
<header>
  <h1>App Title</h1>
</header>
<div class="container">
  <h2 i18n>The page you requested could not be found</h2>
  <span i18n>Try going to the 
       <a routerLink="#">home page</a>
  </span>
</div>

```
Given this structure and the need to extract and translate _home page_ nested into a _span_ tag, a workaround (not the only one) might be to unnest the _anchor_ tag:

```
<header>
  <h1>App Title</h1>
</header>
<div class="container">
  <h2 i18n>The page you requested could not be found</h2>
  <span i18n>Try going to the</span>
  <a routerLink="#" i18n>home page</a>
</div>

```

although it might seem an irrelevant issue, the workaround above comes with a downside: the need to unnecessarily modify css style and layout to obtain a desired view, when nesting of tags would be sufficient. 

This might apply to my case  only of course, but such implementation, if possible, would ease and improve the development overall.

### Proposed solution

I have not enough experience to propose a valuable solution for this issue

### Alternatives considered

None

**Comment by AndrewKushnir** [comment]
@ElenaLj it should be possible to use HTML tags inside i18n block, i.e. your example should work correctly:
```
  <span i18n>Try going to the 
       <a routerLink="#">home page</a>
  </span>
```
HTML tags would be replaced with placeholders in extracted XMB/XLIFF files and the inner text should be present as is, so you can translate it and use translations afterwards to build localized versions of bundles.

If this doesn't work as expected, please provide a repro and we'll perform further investigation.

We can also consider updating i18n guide (https://angular.io/guide/i18n-common-prepare#mark-text-in-component-template) to mention nested HTML tags as well (if doesn't seem to cover this at this moment). Please let us know if you might be interested in contributing a docs update.

I'm closing this ticket for now, please reopen if nested HTML tags don't work as expected.

**Comment by ElenaLj** [comment]
I am reopening because I am afraid I explained it poorly.

Here is a repro of what I have been trying to achieve: [https://github.com/ElenaLj/i18ndemo]

The issue is not nesting HTML tags in i18n blocks, but nesting translatable sections into one another. 
Would that be possible to implement or am I missing something else?

Tried also to thoroughly read the docs, but couldn't find a possible solution.   
Here is a screenshot of the error I get:

![Uploading Screenshot 2022-11-09 at 23.24.50.png…]()


Thank you in advance for the reply!

**Comment by AndrewKushnir** [comment]
@ElenaLj I've received an email notification with your reply, but I don't see it in this GitHub thread for some reasons.

I took a quick look at the code that you refer to and found [this snippet](https://github.com/ElenaLj/i18ndemo/blob/main/src/app/card/card.component.html#L28-L30) (similar to what you mentioned in your original message):
```
  <p class="text-center" i18n="@@redirect-to">Go back to the
    <a routerLink="#" i18n="@@homepage">home page</a>
  </p>
```
In this scenario you don't need the second (nested) `i18n` attribute, so the code would look like this:
```
  <p class="text-center" i18n="@@redirect-to">Go back to the
    <a routerLink="#">home page</a>
  </p>
```
and after running the `ng extract-i18n` command, an extracted message would contain this:
```
      <trans-unit id="redirect-to" datatype="html">
        <source>Go back to the <x id="START_LINK" ctype="x-a" equiv-text="&lt;a routerLink=&quot;#&quot;&gt;"/>home page<x id="CLOSE_LINK" ctype="x-a" equiv-text="&lt;/a&gt;"/></source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">1,2</context>
        </context-group>
      </trans-unit>
```
The `<source>` tag would contain the entire block and nested HTML tags would be replaced with placeholders (the `<x>` tags). All static text would also be included, so it can be translated.
