### ISSUE TITLE
[FEATURE] Comments on Tutorial Pages

### ISSUE THREAD

**Issue by chriscurnow** [angular/angular#4800]
Your new tutorial pages are extremely well written and easy to follow – albeit with a few typos.

However I ran into trouble in the section "The Hero Editor" when you suggest to add styles. There is an omission here in that the styles value should be an array rather than a string (as shown).

It took me quite a while to work that out.

I'm sure lots of others before me have seen that and worked it out.

It would be great to be able to add comments to the tutorial so people who see an error like this can comment and then new readers could scroll down and see the solution.

**Comment by vicb** [comment]
see https://github.com/angular/angular.io (https://github.com/angular/angular.io/tree/master/public/docs/ts/latest/tutorial). You can open an issue/PR there. Thanks.
