### ISSUE TITLE
router: allow for DI on the @CanActivate decorator

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#4802]
It would be nice if `@CanActivate` decorator would resolve some additional bindings if provided. For instance if the check I want to do during this step depends on some service that I've created, then I could do something like:
```js
@CanActivate((myService: MyService) => { /* here I could use `myService` that was injected */ }, {
    providers: [
        MyService
    ]
})
```
I am aware that there is a `ComponentInstruction` passed to the function, but that is not of much help if I want to use anything else beyond just that.

**Comment by frederikschubert** [comment]
Related to <a href="https://github.com/angular/angular/issues/4112">4112</a>
