### ISSUE TITLE
@angular/forms: enhance reactive forms constructor signature to pass a unique ID

### ISSUE THREAD

**Issue by mikelgo** [angular/angular#48030]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

With this feature request especially the reactive forms should be able to receive an optional unique ID as argument when creating an instance.

This feature would make some advanced use cases easier (and maybe also some existing).

E.g. if you have a dynamic form where several FormControls (in different FormGroups though) have the same key, it is currently not really easy to track down one specific kind of these FormControls.

### Proposed solution

```
formGroup = new FormGroup('my-fg-id' ,{ // fg definition})
formControl = new FormControl('my-formcontrol-id', '')
formArray = new FormArray('my-formarray-id',[])
```

Also a `getById()`-method would be helpful then.

### Alternatives considered

-

**Comment by dylhunn** [comment]
We're aware of the shortcomings with dynamic forms, and this is a big consideration for us in the upcoming forms redesign! We're very unlikely to implement such a foundational change to the existing reactive forms system, but rest assured we have dynamic forms in mind.
