### ISSUE TITLE
FormGroup AsyncValidator doesn't get triggered if nested FormControls have validators

### ISSUE THREAD

**Issue by owehmer** [angular/angular#48043]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

If you have a FormGroup that has an async validator, which itself has two FormControls that have validators, then the async validator won't run until you change both inner values.

If the inner FormControls don't have validators on their own the async validator run without any problem on form creation and also when any value changes.
This is also my expected behavior when there are inner validators.

There might be a connection to [#43369](https://github.com/angular/angular/issues/43369)

```ts
new FormGroup({
  grp: new FormGroup(
    {
      username: new FormControl('', {
        validators: [],
      }),
      password: new FormControl('', {
        validators: [Validators.required], // <-- Remove this to see the expected behavior, e.g. the asyncValidators getting called
      }),
    },
    {
      validators: [
        () => {
          console.warn('is getting triggered instantly');
          return null;
        },
      ],
      asyncValidators: [
        () => {
          console.warn('is getting called after you change two values');
          return of(null);
        },
      ],
    }
  ),
});
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-9e8gwb?file=src/app/app.component.ts

### Please provide the exception or error you saw

```true
The async validator doesn't get triggered.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.9
Node: 16.14.2
Package Manager: npm 8.19.1 
OS: darwin x64

Angular: 14.2.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.9
@angular-devkit/build-angular   14.2.9
@angular-devkit/core            14.2.9
@angular/cli                    14.2.9
rxjs                            7.5.7
typescript                      4.6.4
```

**Comment by jnizet** [comment]
Hi @owehmer 

In your demo, the async validator is called whenever any of the two values change, except if the second value is empty and you change the first value. And that's expected, because if the second value is empty, the form control is known to be invalid due to the sync validator, so the form group is known to be invalid too. Async validators are only called if the sync validators don't make the form control invalid.

See https://angular.io/guide/form-validation#creating-asynchronous-validators:

> Asynchronous validation happens after the synchronous validation, and is performed only if the synchronous validation is successful. This check lets forms avoid potentially expensive async validation processes (such as an HTTP request) if the more basic validation methods have already found invalid input.

**Comment by dylhunn** [comment]
As @jnizet notes, this is working as intended. If you add default values to both controls, the sync validators pass, and the async validator is run.
