### ISSUE TITLE
File Based Routing

### ISSUE THREAD

**Issue by jdgamble555** [angular/angular#48045]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- A new routing module

### Description

The ability to have file based routing, and mix server routes with browser routes. I firmly believe this is the future of frameworks, and it is crazy to me this is not already a feature requests. I specifically chose Angular Universal and not Angular, due to the fact that SSR routes are not easy to create nor use right now.  You have to manually create them, and you cannot use Angular components, only Typescript.  Angular Universal should use Angular on the backend.

The best two ways to look at this are to see what NextJS and SvelteKit are doing.
- https://kit.svelte.dev/docs/routing
- https://beta.nextjs.org/docs/routing/fundamentals#the-app-directory

### Describe the solution you'd like

I am a huge fan in the file based routing system they are using, specifically with the Incremental Static Regeneration.  Angular Universal should at least create a way to use caching.  Again, this is the future.

I would like to see a way to add SSR routes by the means of file based routing. How this is done is not as important as the fact that it can be done. I like a method with `server` in the name, `page` in the name, or `browser` in the name, but any method is doable.

```
page
  page.ts
  page.component.ts
  page.server.component.ts
  page.browser.component.ts
```

I like Angular Universal doing these things for me.

### Describe alternatives you've considered

There are a few alternative packages:
- https://github.com/benwinding/ngext
- https://github.com/analogjs/analog

Any option that gives me SSR routing, browser routing, or a mixture (my choice), but easily, is the important part.

J

**Comment by Phillip9587** [comment]
Take a look at analogjs/analog.

**Comment by atscott** [comment]
As mentioned by @Phillip9587, file-based routing can and is being implemented by the community (shoutout @brandonroberts)  using the existing APIs in Angular. This isn's something we'll be focusing on ourselves at this time.

**Comment by jdgamble555** [comment]
@Phillip9587 @atscott - If you re-read my post, you will see that I already mentioned Analog.  While I thank and agree that @brandonroberts did a great job on this, I am not asking for a meta framework.

This is something that should be implemented into **Angular Universal**.  Nearly ALL other SSR Frameworks (and I can't name one, but it probably exists) support File Based Routing.

At the very lease, a way to do Server Only Routes should be added to Angular Universal, as this is currently impossible without manually coding up the Angular Universal version of express.  This should be EASY and built into the Framework.

I firmly believe this is a huge problem with Angular, causing many people to move away from it.  

Server Routing at the very least, please.

Thanks,

J
