### ISSUE TITLE
Uncaught TypeError: m.values is not a function -- angular2.dev.js:4050

### ISSUE THREAD

**Issue by ulf1** [angular/angular#4804]
I am trying the 5min Quickstart [https://angular.io/docs/ts/latest/quickstart.html]. 
My Chromium Browser throws an error while loading the page. 

Error Message:
Uncaught TypeError: m.values is not a function
in angular2.dev.js:4050

Line 4050
...
return getValues ? Array.from(m.values()) : Array.from(m.keys());
...

Browser:
Chromium 43.0.2357.81 Ubuntu 14.04
(There are no problems when using Firefox)

**Comment by ulf1** [comment]
nevermind. I just figured that I have to load traceur-runtime

**Comment by ericmartinezr** [comment]
@ulf1 they removed traceur, instead you should use es6-shim.

**Comment by ulf1** [comment]
@ericmartinezr thank you for the hint. it works :+1:
