### ISSUE TITLE
Instantiate typed form controls using creator functions

### ISSUE THREAD

**Issue by moniuch** [angular/angular#48049]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

Typed forms seem to only allow typing with this very verbose constructor syntax `new FormControl(...)`. When a form gets really big, the code gets really verbose and ugly because of that.

And while we're at it... let's think again: do we need `FormBuilder`? Maybe we could instead...

### Proposed solution

...have functional instantiations, using creator functions. Just like ngrx has `createEffect` or `createAction`, angular/forms could have `createFormControl`, `createFormArray`, etc.

Developer could then alias those imports to make the code even less verbose, if they wish:

```ts
import { createFormGroup, createFormControl as fc, createFormArray as fa } from `@angular/forms`;

this.form = createFormGroup({
  firstName: fc('', Validator.required, ..., {opts}),
  skills: fa([]),
})
```

 Wouldn't type inference inside get simpler too? (I'm far from being an expert in here)

### Alternatives considered

The alternatives are already in place.

**Comment by dylhunn** [comment]
The recommended solution is to use `FormBuilder`. It's actually pretty concise:

```
fb.nonNullable.group({
  member: ['Alex', Validators.required],
  address: fb.nonNullable.group({
    house: 1234,
    street: 'Valencia St',
  })
});
```

We're not going to replace `FormBuilder` with freestanding functions at this time.
