### ISSUE TITLE
Child forms when marked dirty do not propagate past parent (e.g grandparent, grand grandparent)

### ISSUE THREAD

**Issue by thomas-lohh** [angular/angular#48053]
### Description

When a child form control that is nested past 1 level is marked as dirty with the reactive formControl .markAsDirty(). It only  marks its immediate parent as dirty and not any of the parent's ancestors and so on...

### Proposed solution

Please mark all ancestors that the child is descended from as dirty

### Alternatives considered

an extra config can be passed in to control the marking in the markAsDirty(allAncestors: bool)

**Comment by JeanMeche** [comment]
Can you provide a sample, 

```
export class AppComponent {
  ctrl1 = new FormControl(1);
  ctrl2 = new FormGroup({ ctrl1: this.ctrl1 });
  ctrl3 = new FormGroup({ctrl2: this.ctrl2});

  onClick() {
    this.ctrl1.markAsDirty();
    console.log(this.ctrl1.dirty, this.ctrl2.dirty, this.ctrl3.dirty);
  }
}
```

Does not illustrate what you are describing.

**Comment by JeanMeche** [comment]
I'm closing this as we didn't get any reproduction. Feel free to file a new issue if you can provide a production of the issue.
