### ISSUE TITLE
How can i fix Cannot read properties of null (reading 'injector')

### ISSUE THREAD

**Issue by chenabel** [angular/angular#48062]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

It's not created project with the angular-cli. so i need created the testing framework. but i got an error "Cannot read properties of null (reading 'injector')". How can i fix it.

**Comment by chenabel** [comment]
![image](https://user-images.githubusercontent.com/81562835/201881338-94b21d88-2bdd-4e52-a669-754cd4a41e0c.png)

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
