### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by DevBrunoo** [angular/angular#48060]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

Yes

### Description

Translate the code comments to Portuguese, I would like to be able to use the contents of this repository to write an article

### Please provide a link to a minimal reproduction of the bug

no

### Please provide the exception or error you saw

```true
no
```

### Anything else?

no

**Comment by JoostK** [comment]
Could you elaborate on what you mean by "the code comments"? There is thousands of lines of comments/documentation in the repository.

The Angular team does not provide translations into other languages. [There is some information on angular.io](https://angular.io/guide/localizing-angular) about contributing localized copies of angular.io though.

**Comment by alxhub** [comment]
Apologies, but we definitely don't have the bandwidth to maintain translations of our codebase. Automated translations may be accurate enough, though?
