### ISSUE TITLE
Update @reactivex/rxjs to alpha.6

### ISSUE THREAD

**Issue by ocombe** [angular/angular#4806]
Hello,

You guys should update @reactivex/rxjs to 5.0.0-alpha.6, there is a [typings fix](https://github.com/ReactiveX/RxJS/commit/a501b06) in alpha 5 that should help with compilers. I'd do a PR but it looks like updating dependencies requires a Mac (which I don't have).

Once that's done, you won't have to do `import {Observable} from '@reactivex/rxjs/dist/cjs/Rx';`, a simple `import {Observable} from '@reactivex/rxjs';` will work.

You might want to update your imports once that's done (for example: https://github.com/angular/angular/blob/c3ab20cc87dd016517c8945b8fe0adab455cc6ed/modules/angular2/src/core/facade/async.ts#L6).

Ping @jeffbcross, @alexeagle, @robwormald

**Comment by robwormald** [comment]
Thanks for the reminder - We can actually do the first in alpha 5, but we don't want to as we're attempting to avoid bringing in the whole of Rx. Updating the import is blocked pending https://github.com/angular/angular/issues/4704 resolution

**Comment by ocombe** [comment]
Ah, good to know then, thanks !

**Comment by robwormald** [comment]
See https://github.com/angular/angular/pull/4807

**Comment by mhevery** [comment]
closing as dup of #4807
