### ISSUE TITLE
Improve Routing with Regular Expressions (Angular2)

### ISSUE THREAD

**Issue by hitmands** [angular/angular#4808]
I Think that the *url* property should manage Regular Expressions and default/optional parameters.

**Comment by mhevery** [comment]
Can you provide an example of how you would imagine this to work.

**Comment by hitmands** [comment]
Hey, thanks for the reply, 
in my mind I imagine a simple way to pass a regular expression instead of a string.
I think that should be possible to declare the same route in these ways: 

***"/posts/:id"*** and ***/\posts\/(\d+)\//*** (id = $1)

**Comment by btford** [comment]
This is a reasonable feature request, but it's not super high priority at the moment.

**Comment by hitmands** [comment]
Yep, 
this isn't a high-priority feature, 
just plan for future!

**Comment by blondinh** [comment]
Hello, 
In anguar 1.x, it was possible to have route params like this:
$route.current.templateUrl = '/'+ $routeParams.sr + '-' + $routeParams.ty + '-' + $routeParams.tc;
The dash is important to get the url SEO friendly.
I tried to implement this in Angular2 but without success. Is it possible to do it with present version?
Thank you in advance.

**Comment by btford** [comment]
Not yet.

**Comment by blondinh** [comment]
Thank you for your reply, I will focus on something else for the moment.

**Comment by msklvsk** [comment]
\+ another use-case: In our app we want routes to be like <code>/post_1</code>, <code>/post_2</code> and not <code>/posts/1</code>, <code>/posts/2</code> since there's no page <code>/posts</code>.

**Comment by GlennCavarle** [comment]
+1 , another use-case : __/{category:[a-z-]+}-{product:[a-z-]+}-{id:[0-9]+}__.
This kind of url is very frequently used (and useful) in websites but has not equivalent in present _v2_ (or I did'nt find it). I think this is an important feature, allowing migration from _v1.x_+_ui-router_ to _v2_. It is not yet possible today...

**Comment by rchodava** [comment]
+1 This is important for a few critical use cases in our application

**Comment by zoechi** [comment]
see #7332

**Comment by devCrossNet** [comment]
+1 we have a lot of "seo-friendly" urls too and have to do things like (from ZF2): /(?<country>[A-Z]{2})/(?<city>[-\w]+)/(?<id>[\d]+)/ or  /(?<type>[-\w]+)/(?<city>.*?)-s(?<id>[\d]+)/(?<filters>.*+)

**Comment by msklvsk** [comment]
Does #7332 implement it? where can we find some examples?

**Comment by devCrossNet** [comment]
it is possible now, I wrote something about it in my blog: http://blog.devcross.net/2016/03/25/angular-2-router-and-regular-expressions/

But there is a type issue in the current implementation (when I take the example from the commit: https://github.com/angular/angular/commit/75343eb), I found a workaround.

**Comment by akshayat** [comment]
Is there a way to provide default router. I mean to say route when nothing matches. A 404 kind of route.

**Comment by zoechi** [comment]
`path: /**`

**Comment by akshayat** [comment]
The problem with `path: /**` is that - is makes `useAsDefault` unusable. I overcame by adding another route for home. Say `/home` to `HomeController` and `/` to `HomeController` too.

Tell me if there is a better way.

**Comment by zoechi** [comment]
I don't know another way. I'd create a separate issue for this (after checking that none exists yet ;-) )

**Comment by steven-fernandez** [comment]
Maybe the code logic should say: If path: /** is available then treat useAsDefault for root url only and everything else as 404 ...

**Comment by devCrossNet** [comment]
Is this feature planned for the stable release of the new router?

**Comment by LeiwenL** [comment]
Any news ? :disappointed: I't will be good if we can put Regular Expression in path for the stable release !

**Comment by hitmands** [comment]
did you see the @devCrossNet post at http://blog.devcross.net/2016/03/25/angular-2-router-and-regular-expressions/ ?

**Comment by devCrossNet** [comment]
@hitmands This post is really old (Router beta.9). I never tried that with the new Router implementation.

**Comment by LeiwenL** [comment]
@hitmands @devCrossNet It doesn't work ... :disappointed_relieved: to old!
I would like to have that url for example:` 'products/([0-9]/)*' `  =>  **products/9/5/4 ...**

**Comment by hitmands** [comment]
I think that's all...
```
@RouteConfig([
  {
    name : 'ItemDetail',

    // regex that will match the URL in the href or the URL typed directly by the user
    regex : 'products/([0-9]/)*',

    // serializer is mandatory, but it is used when you have a routerLink with params
    serializer : (params) => {
      
    },
    component : ItemDetail
  }
]);
```

**Comment by madhav5589** [comment]
Any update on this issue with the latest version of angular routing ? I have similar issue of supporting insensitive URL.

**Comment by vicb** [comment]
Could you please re-open a new issue targeting the new router. Thanks

**Comment by matanshukry** [comment]
For anyone interested, although it require an extra class with a custom url matcher, it is currently possible:
https://github.com/angular/angular/issues/12442

**Comment by sushrest** [comment]
The solution may not be very relevant.. but though i would post here 
Using UrlMatcher or matcher:

`export const routes = [
  { matcher: YourMatcherLogic, component: ProductComponent },`

 YourMatcherLogic function

`  // Url matcher for specific logic implementation and extract parameter using regex.
  export function YourMatcherLogic(url: UrlSegment[]) {
      // Implement your logic to parse different url segments and extract value as parameters to pass to the component
      if ((url.length > 1 && url[1].path.endsWith('.html')) {
        let _id = extractIDFromEndsWithHTML(url[1].path);  // extractIDFromEndsWithHTML custom function that extracts id from urls 'hello/3.html'
        // add id parameters
        url[1].parameters = {id: _id};
        return {
          consumed: url
        };
      } else {
        return null;
      }
  }`

**Comment by DzmVasileusky** [comment]
@sushrest 

Somehow this approach transforms 
/properties/GA/Savannah
to 
/properties/GA;firstParam=GA/Savannah;secondParam=Savannah

```
const propertiesSeoMatcher = (url: UrlSegment[]) => {

    if (url.length > 1 && url[0].path === 'properties'
        && (/(?![0-9]+)[\w-~%]+/).test(url[1].path)
    ) {

        const checkSegmentsCount = url.length > 4 ? 4 : url.length;
        const paramsPrefixes = ['first', 'second', 'third'];

        for (let i = 1; i < checkSegmentsCount; i++) {

            url[i].parameters = { [`${paramsPrefixes[i - 1]}Param`]: url[i].path };

        }

        return { consumed: url };

    } else {

        return null;

    }

};
```

I though it would add params to ActivatedRoute not to an url in this strange way

**Comment by DzmVasileusky** [comment]
Fixed this with

```
const propertiesForSeoMatcher = (url: UrlSegment[]) => {

    if (url.length > 1 && url[0].path === 'properties'
        && (/(?![0-9]+)[\w-~%]+/).test(url[1].path)
    ) {

        const checkSegmentsCount = url.length > 4 ? 4 : url.length;
        const paramsPrefixes = ['first', 'second', 'third'];
        const posParams: Record<string, UrlSegment> = {};

        for (let i = 1; i < checkSegmentsCount; i++) {

            posParams[`${paramsPrefixes[i - 1]}Param`] = url[i];

        }

        return { consumed: url, posParams };

    } else {

        return null;

    }

};
```
