### ISSUE TITLE
DomPortalOutlet not supports inner DomPortalOutlet

### ISSUE THREAD

**Issue by SavinSabu** [angular/angular#48081]
### Which @angular/* package(s) are relevant/related to the feature request?

elements

### Description

I planned to create an angular application with lot of DomPortalOutlets I have to create custom layouts like 
```
    <tb-hst-vst>  //which is for top-bottom-horizontal-start-vertical-start
        <div>tesrf</div>
        <div>dse</div>
    </tb-hst-vst>
    <lr-hsa-vst> // left-right-horizontal-space-around-vertical-start
        <div>1</div>
        <div>2</div>
        <div>3</div>
        <div>4</div>
        <div>5</div>
    </lr-hsa-vst>
    <lr-hs-vs>
        <div>1</div>
        <div>2</div>
        <div>3</div>
        <div>4</div>
        <div>6</div>
    </lr-hs-vs>
```
like above individually these DomPortalOutlets are working fine.
But if I use the same like below,
   ``````

 <tb-hst-vst>
        <div>tesrf</div>
        <div>dse</div>
        <lr-hsa-vst>
            <div>1</div>
            <div>2</div>
            <div>3</div>
            <div>4</div>
            <div>5</div>
        </lr-hsa-vst>
        <lr-hs-vs>
            <div>1</div>
            <div>2</div>
            <div>3</div>
            <div>4</div>
            <div>6</div>
        </lr-hs-vs>
    </tb-hst-vst>
```
```
this wont work, 
my exact issue is related to this link
https://stackoverflow.com/questions/58623369/angular-cdk-portal-multiple-portals-to-one-portaloutlet
https://www.reddit.com/r/Angular2/comments/butvzn/using_multiple_undetermined_portals/

### Proposed solution

No

### Alternatives considered

No

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
