### ISSUE TITLE
Renderer2 previousSilbing does not exist.

### ISSUE THREAD

**Issue by Shaharamir** [angular/angular#48098]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I'm using Renderer2, and unfortunately, there is no option for previousSilbing property despite nextSibling is exist.

https://developer.mozilla.org/en-US/docs/Web/API/Node/previousSibling

### Please provide a link to a minimal reproduction of the bug

Try to access renderer previousSilbing, not exist

**Comment by pkozlowski-opensource** [comment]
The `Renderer2` abstraction is in place only to support DOM operations that are needed by the framework - and `previousSilbing` is not one of those operations. 

You can directly use DOM APIs if you are doing low-level DOM manipulation.

Closing as won't fix.
