### ISSUE TITLE
Stage 3 Decorators

### ISSUE THREAD

**Issue by jpike88** [angular/angular#48096]
### Description

It looks like TS is going to be getting stage 3 decorators in 5.0:

https://github.com/microsoft/TypeScript/issues/51362

Will angular need to make changes to how it defines decorators in order to keep up?

### Proposed solution

Review the changes needed to be Stage 3 decorator compliant

### Alternatives considered

none

**Comment by alxhub** [comment]
Good question!

At the moment, we won't be able to use ES decorators as defined by TC39. Angular relies heavily on parameter decorators for its DI system, which is not part of the v1 of the Decorators spec. It's being considered as a [separate proposal](https://github.com/tc39/proposal-decorators/issues/47) but traction seems low.  We'll continue to advocate for this in TC39.

The good news is that TypeScript will not remove support for its experimental implementation of decorators, which will continue to function when the `--experimentalDecorators` flag is set.

So in the short term, there's nothing we need to do - TS 5.0 won't break us. Longer term, if TC39 signals that they're not interested in standardizing parameter decorators, we will need to consider alternatives for DI. There are certain patterns around `inject()` that could work as alternatives.
