### ISSUE TITLE
Make standalone Directive `selector` optional 

### ISSUE THREAD

**Issue by antischematic** [angular/angular#48104]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

With Angular 15 host directives it is now possible to have directives that are only used to augment another component or directive via the directive composition API. These directives are never imported or used in a template, making the selector redundant. It would be nice if the selector could be omitted for this use case.

### Proposed solution

Allow standalone directives to omit the `selector`. This should be valid when the directive is used in `hostDirectives`, but should report a compilation error if you try to import it due to the missing template selector.

```ts
@Directive({ standalone: true })
class PrivateDirective {}

@Component({
  imports: [PrivateDirective], // compilation error
  hostDirectives: [PrivateDirective] // allowed
})
export class AppComponent {}
```

### Alternatives considered

Make up a random selector name so it doesn't conflict with other directives.

**Comment by JoostK** [comment]
Did you test this by any chance? Directives without selector are allowed when I just tested this; we don't report an error for including said directive in `imports` at the moment, that seems like a bug to me.

**Comment by antischematic** [comment]
You're right, I just checked again and it works without the selector. It was just IntelliJ marking the missing selector as an error in the editor 🤦
