### ISSUE TITLE
Inputs not included when using directive composition API in a directive

### ISSUE THREAD

**Issue by wellwind** [angular/angular#48105]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I have a simple standalone directive like:

```typescript
@Directive({
  standalone: true,
  selector: '[appBgColor]'
})
export class BgColorDirective {
  @HostBinding('style.display') display = 'inline-block';
  @Input() @HostBinding('style.background-color') bgColor = 'yellow';
}
```

And another directive compose the directive above using compisition API

```typescript
@Directive({
  selector: '[appMyDirective]',
  standalone: true,
  hostDirectives: [
    {
      directive: BgColorDirective,
      inputs: ['bgColor']
    }
  ]
})
export class AnotherDirective { }
```

Because I have include `bgColor` of `BgColorDirective`, so I ecpect `bgColor` should be also the input of `AnotherDirective`.

But when I using `AnotherDirective` in the `hostDirectives` of component, it's not working when I want to include `bgColor` again.

TS:

```typescript
@Component({
  selector: 'app-my-comp',
  templateUrl: './my-comp.component.html',
  styleUrls: ['./my-comp.component.scss'],
  hostDirectives: [
    {
      directive: AnotherDirective,
      inputs: ['bgColor']
    }
  ]
})
export class MyCompComponent { }
```

HTML using `MyComComponent`:

```html
<app-my-comp bgColor="green"></app-my-comp>
```

After compile I got following error:

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/8186117/202426970-4464efd6-804b-4f4e-962d-47c91d985737.png">

If I just compose `BgColorDirective`, it works well.

A workaround is add `@Input` by myself

```typescript
@Directive({
  selector: '[appMyDirective]',
  standalone: true,
  hostDirectives: [
    {
      directive: BgColorDirective,
      inputs: ['bgColor']
    }
  ]
})
export class AnotherDirective {
  // let bgColor input works
  @Input() bgColor = '';
}
```

### Please provide a link to a minimal reproduction of the bug

https://github.com/wellwind/ng-inputs-not-working-in-directive-composition-api-demo

### Please provide the environment you discovered this bug in (run `ng version`)

```true
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.0.0
Node: 16.17.0
Package Manager: npm 8.15.0
OS: darwin arm64

Angular: 15.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0
@angular-devkit/build-angular   15.0.0
@angular-devkit/core            15.0.0
@angular-devkit/schematics      15.0.0
@schematics/angular             15.0.0
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by JoostK** [comment]
StackBlitz imported from Github: https://stackblitz.com/github/wellwind/ng-inputs-not-working-in-directive-composition-api-demo?file=src%2Fapp%2Fmy-comp%2Fmy-comp.component.ts,src%2Fapp%2Fanother.directive.ts.ts

**Comment by crisbeto** [comment]
This is working as expected. The `bgColor` input doesn't actually exist on `AnotherDirective`, it is sent to the instance of `BgColorDirective` that is applied together with `AnotherDirective`. This is something that I was considering whether to support when I was implementing the new API, but I decided against it because the input doesn't really belong to the host, it belongs to the host directive which `MyCompComponent` doesn't have access to.

**Comment by crisbeto** [comment]
Good point about clarifying it in the documentation. I just want to point out that there's no difference between applying host directives to a component or to a directive. Your example doesn't work, because the component is reaching for an input of a host directive that belongs to another host directive. That won't work, because the `inputs` array only refers to the inputs declared on the class in the `directive` field.

**Comment by wellwind** [comment]
Now I understand my code doesn't works because `bgColor` is not the `@Input` of `AnotherDirective` because of my misunderstanding from document.

But when I just add a `@Input() bgColor = ''` to `AnotherDirective`, I should belongs `AnotherDirective`, not belongs `BgColorColor`, but the style still changed.

```typescript
@Directive({
  selector: '[appMyDirective]',
  standalone: true,
  hostDirectives: [
    {
      directive: BgColorDirective,
      inputs: ['bgColor']
    }
]
})
export class AnotherDirective {
  // bgColor belongs AnotherDirective, 
  // but still affect to the BgColorDirective.bgColor, why?
  @Input() bgColor = '';
}
```

Is it also the expected behavior? I have just update the repo.

**Comment by wellwind** [comment]
I found that I can just remove the `@Input() bgColor` in `AnotherDirective`, when I compose `AnotherDirective` into `MyCompComponent`, I can use `bgColor` directly without pass `bgColor` into `inputs: []`

The complete working code is:

```typescript
@Directive({
  standalone: true,
  selector: '[appBgColor]'
})
export class BgColorDirective {
  @HostBinding('style.display') display = 'inline-block';
  @Input() @HostBinding('style.background-color') bgColor = 'yellow';
}

// compose BgColorDirective into AnotherDirective
@Directive({
  selector: '[appAnotherDirective]',
  standalone: true,
  hostDirectives: [BgColorDirective]
})
export class AnotherDirective { }

// compose AnotherDirective into MyCompComponent
@Component({
  selector: 'app-my-comp',
  // no need to pass inputs:[]
  // BgColorDirective.bgColor still works
  hostDirectives: [AnotherDirective],
  ...
})
export class MyCompComponent { }

// usage of MyCompComponent
@Compontnt({
  template: `<app-my-comp bgColor="blue"></app-my-comp>`,
  ...
})
export class AppComponent
```

I think this is the design of directive composition API?
