### ISSUE TITLE
RouteParams doesn't understand getting arrays in a format that Angular1 understood

### ISSUE THREAD

**Issue by LMFinney** [angular/angular#4811]
Using alpha 42, I'm able to pass an array of strings through query param like this:
`http://127.0.0.1:8080/src/characters?id=foo,bar`. This produces a RouteParams of `{id: ['foo', bar']}`. I would like to be able to produce the same RouteParams using this syntax as well: `http://127.0.0.1:8080/src/characters?id=foo&id=bar`. The reason is that the previous version of our AngularJS app used that syntax for calls from external apps, and we would like to be able to support them with the migrated version.

Unfortunately, it appears that RouteParams doesn't support this syntax. It would be helpful if RouteParams were able to understand `id=foo&id=bar`.

Is this something that might be supported in the future for Angular2? Or do we need to redesign the other apps to use the shorter syntax?

Note: to generate the url at the top of this issue, I was able to use two different router-link formats: `<a [router-link]="['/Characters', {id:['foo','bar']}]" class="router-link">Characters</a>` and `<a [router-link]="['/Characters', {id:'foo,bar'}]" class="router-link">Characters</a>`.

**Comment by btford** [comment]
> Is this something that might be supported in the future for Angular2

Yep, this is a reasonable feature. Just haven't got to it yet.

**Comment by vicb** [comment]
related to the old router
