### ISSUE TITLE
Angular app performance score in Lighthouse ONLY 46!

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [angular/angular#48110]
### Description

In newsly generated standlaone app with Angular 15 lighthouse swos only 46% performance.

### Proposed solution

Improve angular starter

### Alternatives considered

Improve angular starter

**Comment by rogerg93** [comment]
Did you use a production build? Sounds to me like you're testing on localhost.

**Comment by dylhunn** [comment]
I just tried this, and I get a lighthouse score of 100, so you're probably not using a prod build. Please feel free to comment if something else is going on.
