### ISSUE TITLE
Angular 15.0.0 is missing in the "Actively supported versions" table on angular.io

### ISSUE THREAD

**Issue by marcwrobel** [angular/angular#48116]
### Describe the problem that you experienced

Angular `^15.0.0` is missing in the _Actively supported versions_ table on https://angular.io/guide/releases#actively-supported-versions.

### Enter the URL of the topic with the problem

https://angular.io/guide/releases#release-schedule

### Describe what you were looking for in the documentation

I was looking for Angular 15 active and lts support dates.

**Comment by jerryajay** [comment]
I'm facing the same issue. Cannot be added to an angular 15 project.

```
npm install angular-in-memory-web-api --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: angular-tour-of-heroes@0.0.0
npm ERR! Found: @angular/common@15.0.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^15.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^14.0.0" from angular-in-memory-web-api@0.14.0
npm ERR! node_modules/angular-in-memory-web-api
npm ERR!   angular-in-memory-web-api@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by alan-agius4** [comment]
Thanks for brining  this up. Have a PR in flight to address this https://github.com/angular/angular/pull/48173
