### ISSUE TITLE
PLATFORM_ID injection token has incorrect type

### ISSUE THREAD

**Issue by belyan** [angular/angular#48123]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

Correct type should be "string" instead of "Object", because this token returns one of these string values:
https://github.com/angular/angular/blob/main/packages/common/src/platform_id.ts#L9-L12

### Please provide a link to a minimal reproduction of the bug

https://angular.io/api/core/PLATFORM_ID

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.9
Node: 16.14.2
Package Manager: npm 8.5.0
OS: darwin x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1303.9 (cli-only)
@angular-devkit/core         13.3.9 (cli-only)
@angular-devkit/schematics   13.3.9 (cli-only)
@schematics/angular          13.3.9 (cli-only)
```

**Comment by JoostK** [comment]
The `Object` type is indicating that this is an opaque type, not necessarily a string. That it is a string at runtime is an implementation detail.

**Comment by belyan** [comment]
As for me, it is wrong to compare an Object with a string, as doing here:
https://github.com/angular/angular/blob/main/packages/common/src/platform_id.ts#L19

Also ESlint don't like when Object used as type when inject this token:
```ts
@Inject(PLATFORM_ID) private platformId: Object
```

This are reasons why I changed type to `string` in my Angular project:
```ts
@Inject(PLATFORM_ID) private platformId: string
```

**Comment by belyan** [comment]
Every time Angular Team close issues in this way, your framework loses a few points, and here is the result:
https://2021.stateofjs.com/en-US/libraries/front-end-frameworks/

Keep going guys :)
