### ISSUE TITLE
Browser back button not working wtih Standalone components

### ISSUE THREAD

**Issue by AkaashThawani** [angular/angular#48133]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

I upgraded my personal project and saw that browser back button stopped working with standalone components. It works fine if used with NgModule.This bug is present in both V14 and V15.

Stackblitz( Standalone ) :- https://stackblitz.com/edit/angular-ivy-mhlv5j?file=src/app/landing.component.ts

Stackblitz ( NgModule) :- https://stackblitz.com/edit/angular-ivy-kp1ttk?file=src/app/app.module.ts

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-mhlv5j?file=src/app/landing.component.ts

### Please provide the exception or error you saw

```true
The browser URL changes but component does not change.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular/animations 14.0.0

@angular/common 14.0.0

@angular/compiler 14.0.0

@angular/core 14.0.0

@angular/forms 14.0.0

@angular/platform-browser 14.0.0

@angular/platform-browser-dynamic 14.0.0

@angular/router 14.0.0

rxjs 7.5.5

tslib 2.4.0

zone.js 0.11.5
```

**Comment by JoostK** [comment]
You're using the API incorrectly with the setup in Stackblitz. The router should be configured as environment provider, whereas you're using `RouterModule.forRoot` only from an NgModule that is imported using `Component.imports`. This results in the router providers not being configured in the environment injector, but in the component instead.

Updating the StackBlitz reports an error for this setup:

```
Error: NG04007: The Router was provided more than once. This can happen if 'forRoot' is used outside of the root injector. Lazy loaded modules should use RouterModule.forChild() instead.
```

The proper way to make this work is to change `main.ts` using

```ts
bootstrapApplication(AppComponent, {
  providers: [importProvidersFrom(AppRoutingModule)]
})
```

and remove `AppRoutingModule` from `Component.imports` in `AppComponent`.

Confusion around environment providers vs component providers is a problem we are aware of and newly designed APIs like `provideRouter` result in a type-check error when using it incorrectly like in this case, so I'm closing this as not further actionable.
