### ISSUE TITLE
Bloom filter index

### ISSUE THREAD

**Issue by adaico** [angular/angular#48134]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I've just looked through source for my interest and found place that looks more like a bug. I'm talking about the last line of **bloomAdd** function (renderer3/di.ts).
As I understood, **tView.data** has several filters for different injectors. In this case the line should be like 

`(tView.data as number[])[injectorIndex * FILTER_BUCKETS_NUM (8 in this case) + (bloomHash >> BLOOM_BUCKET_BITS)] |= mask;`

If **injectorIndex** is index (incrementing on 1), multiplying on **FILTER_BUCKETS_NUM** will jump over filters of other injectors.

**Comment by JoostK** [comment]
It looks correct to me; `injectorIndex` is not incremented by 1, but corresponds with the start of the bloom filter:

https://github.com/angular/angular/blob/841c8e51386645d7fd26642f41952ed8f0a2dbe5/packages/core/src/render3/di.ts#L158-L161
