### ISSUE TITLE
(not a bug) Font Awesome Attribution when using the free SVG icons in a commercial Angular Project

### ISSUE THREAD

**Issue by dali-trabelsi** [angular/angular#48141]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I didn't know where I can ask this question so I thought I could add it here. 
Its all in the question, I am using Font Awesome **free SVG Icons** in a **commercial angular app** and I we are wondering if or where we should be attributing Font Awesome in our website

Quoting from the Font Awesome free license page at [https://fontawesome.com/license/free](https://fontawesome.com/license/free): 
> Downloaded Font Awesome Free files already contain embedded comments with sufficient attribution, so you shouldn't need to do anything additional when using these files normally.

We wanted to make sure whether we're safe using the SVG icons without having to do anything else.
Thanks in advance.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
