### ISSUE TITLE
core-js package

### ISSUE THREAD

**Issue by us-maksym** [angular/angular#48145]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

No

### Description

As I see, "core-js" package (https://www.npmjs.com/package/core-js) is used in your framework.
But the author of this package is a russian person (https://github.com/zloirock) who supports the invasion of his country in Ukraine.
So I insist on excluding this package from your framework!
Thanks.

**Comment by JeanMeche** [comment]
You seems like [friendly man](https://github.com/zloirock/core-js/issues/1069).

**Comment by dylhunn** [comment]
@mgechev

**Comment by artuska** [comment]
@us-maksym Angular framework, JavaScript, browsers and programming is not meant for nazis, plesae, just do not use those things in your life.

**Comment by us-maksym** [comment]
@artuska Why did you write to me? Just do not spread the shit you wrote.

**Comment by FetterBaby** [comment]
@us-maksym
 **_https://github.com/zloirock/core-js/issues/1069_**
 I guess you were just offended by a harmless disclaimer...
You should mind your own business, and  add this issue in spam
