### ISSUE TITLE
Dependency @reactivex/rxjs version 5.0.0-alpha.4 not available in NPM

### ISSUE THREAD

**Issue by kkchaitu** [angular/angular#4814]
I think package.json need to update with latest version of 
@reactivex/rxjs with 5.0.0-alpha.6

Log:

$npm install angular2
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'reactivex/rxjs' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'angular2'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Darwin 14.5.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "angular2"
npm ERR! cwd /Users/kambhampati/Development/learning/angular2
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! not ok code 0

After updating the version in local copy, stuck with this issue

npm install

> angular-srcs@2.0.0-alpha.44 preinstall /Users/.../angular2/angular
> node tools/npm/check-node-modules --purge

:-( npm dependencies are stale or in an in unknown state!
    purging...

**Comment by Alxandr** [comment]
What version of npm do you have?

**Comment by kkchaitu** [comment]
Earlier npm -v 1.4.28
Just updated the NODE and NPM an hour back. Latest version is 3.3.8. Hope will work now.

Right now - cloneCurrentTree happening

**Comment by mhevery** [comment]
can't repro
