### ISSUE TITLE
[improvement] image optimise directive

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular#48146]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

Angular already released its new [image directive](https://developer.chrome.com/blog/angular-image-directive/), which lazy loads images and do more...
I haven't dug deeply into it, but talking about the lazy-loading part I suggest generalizing the concept to any element that has `src` or `srcSet`

I already implemented a [directive](https://github.com/eng-dibo/dibo/blob/main/packages/lazy-load/index.ts)  that searches for elements that have `src` or `srcset` attributes and uses the `IntersectionObserver` to observe it and load it on the appropriate time.

**Suggestion**
implement a more general Directive like ImageOptimizeDirective but for any element uses the input `ngSrc` or `ngSrcSet`

### Proposed solution

-

### Alternatives considered

-

**Comment by pkozlowski-opensource** [comment]
Thnx for the suggestion @eng-dibo! The current image directive is ... well, tailored to the images and does much more than lazy loading. We don't have plans for generalising this approach to other DOM elements at the moment.

But if you've got directive ready maybe you could publish it as an independent library? This would be great! 
(be sure to profile it first, though as creating many intersection observers isn't totally free).
