### ISSUE TITLE
Framework-Feature to easily load static html

### ISSUE THREAD

**Issue by DeusProx** [angular/angular#4815]
I suggest that angular2 as a framework should have a way to easily include static html files directly into the RouteConfig/Router. Probably every web application has some kind of static data to display. For example some kind of impressum, AGB/Conditions or instructions. As far as I know one would have to create an own class with annotations(@View,@Component) for each html file, and put it into the RouteConfig which ends in unneeded boilerplate code.

ATM I just got a Factory which gets the html files via xmlHttp, creates a component, puts it into a route and returns the route. I just simply instantiate the Factory in my root component and use it in my @RouteConfig. 

```
export class HtmlComponentFactory{

  components: Map<String, Route>;

  constructor(){
    this.components = new Map<String, Route>();
  }

  provideComponent(htmlRoute:HtmlRoute): Route{
    if(!this.components.has(htmlRoute.htmlpath)){
      var xmlHttp = new XMLHttpRequest();
      xmlHttp.open("GET", htmlRoute.htmlpath,false);
      xmlHttp.send(null);

      if(xmlHttp.status!=200) {
        console.error("Couldn't find file " + htmlRoute.htmlpath);
        return null;
      }

      var template = xmlHttp.responseText;
      @Component({ selector: htmlRoute.as.toLowerCase() })
      @View({ template })
      class Cmp {}

      this.components.set(htmlRoute.htmlpath,
        new Route({
          path: htmlRoute.path,
          component: Cmp,
          as: htmlRoute.as
        })
      );
    }

    return this.components.get(htmlRoute.htmlpath);
  }
}

export class HtmlRoute extends Object {

  path: string;
  htmlpath: string;
  as: string;

  constructor(path: string, htmlpath: string , as: string ){
    super();
    this.path = path;
    this.htmlpath = htmlpath;
    this.as = as;
  }
}
```
Now I just do the following in my root component named app:
```
var htmlCF = new HtmlComponentFactory();

@Component({selector: 'app'})
@View({ template:
  `<nav>
    <div class="container">
      <template ng-for #button [ng-for-of]="buttons">
        <a [router-link]="['/'+button]"  class="button {{button}}" >{{button}}</a>
      </template>
    </div>
  </nav>
  <div class="container content">
    <router-outlet></router-outlet>
  </div>`,
  directives: [ROUTER_DIRECTIVES,CORE_DIRECTIVES]
})
@RouteConfig([
 ...
  htmlCF.provideComponent({ path:'/Admin', htmlpath: './admin.html',as: 'Admin' }),
  htmlCF.provideComponent({ path:'/Impressum', htmlpath: './impressum.html',as: 'Impressum' })
])
export class App {

  buttons: String[];
  router: Router;
  loc: Location;

  constructor(router: Router, loc: Location) {
    this.router = router;
    this.loc = loc;
    this.buttons = [....., "Admin", "Impressum"];
  }
}
``` 

Can we introduce something working like this into the framework? I would do it myself and create a pull request but I haven't much experience with javascript/typescript and any angular stuff.

**Comment by fabiosussetto** [comment]
my 2 cents: I think this would belong to an external package and not in the Angular core, as it's something potentially very specific to each app implementation.

**Comment by Chocoloper** [comment]
Whats do you see as specific with this? It should just load a static html (which doesn't depend on any javascript) and have it's on class to easily register it in the @RouteConfig similiar to the existing approaches like Route and AsyncRoute. So at the end you just have put it into the RouteConfig and make a button for it in your View.

I don't mean to put my presented code into angular 2 as it is just some dirty code I hacked without much knowledge. The existing approach would be to just write a class like this for every html-file:
```
@Component({ selector: 'admin' })
@View({ templateUrl: './admin.html' })
class Admin {}
```
Then register them all in RoutConfig with Route and make buttons.

P.S.: Maybe you also talked about how I created my buttons? That's just my own convenient way to it. That shouldn't become part of the framework.

**Comment by gdi2290** [comment]
I can add this feature to universal if it doesn't make it to core. I understand the benefits and it's probably more interesting with server rendering. Then you can section off parts of your app to be server only view etc

**Comment by Chocoloper** [comment]
Well I just saw that i thought way to complicated. I looked into the Route and RouteDefinition one can easily just make the following:
```
export class HtmlRoute implements RouteDefinition {
  data: any;
  path: string;
  component: Type;
  as: string;
  loader: Function;
  redirectTo: string;
  constructor({path, templateUrl, as, data}:
    { path: string, templateUrl: string, as?: string, data?: any }) {
    this.path = path;

    @Component({ selector: as.toLowerCase() })
    @View({ templateUrl })
    class Cmp {}

    this.component = Cmp;
    this.as = as;
    this.loader = null;
    this.redirectTo = null;
    this.data = data;
  }
}
```
```
and use it in the Routeconfig like this:
@RouteConfig([
  new Redirect({ path: '/', redirectTo: '/Home' }),
  new Route({ path: '/Home', component: Home, as: 'Home' }),
......
  new HtmlRoute({ path:'/Admin', templateUrl: './admin.html',as: 'Admin' }),
  new HtmlRoute({ path:'/Impressum', templateUrl: './impressum.html',as: 'Impressum' })
])
```

If this makes it to the angular2 framework it would be a favor for me to create the pull request! :)

**Comment by btford** [comment]
@mhevery @rkirov @vsavkin Regardless of how this is represented as an API, wouldn't this require changes to core?

I'm going to re-tag to reflect this, but if there's a way for the router to do this, I'm happy to own it.

**Comment by mhevery** [comment]
There are two kinds:

1.) Including static data with directives, Most likely we don't want to do this do to security and breaking the mental model of what a template is.
2.) Loading static HTML into doc should be done through  `<div inner-html="html">` the trouble is that this is not safe, and needs to have sanitizer. There are a lot of security implications here.

**Comment by pkozlowski-opensource** [comment]
This is the same discussion as in #7596 - let's centralize the discussion in there.
