### ISSUE TITLE
Suggestion: Functional Components

### ISSUE THREAD

**Issue by ShacharHarshuv** [angular/angular#48150]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

With the latest release of Angular 15, it seems like there is a step in a direction of adopting a more functional programming approach, by enabling to do stuff with functions, that were previously only possible through classes. 
I believe this is a step in the right direction, and that it could be taken a step farther by enabling the creation of components, directives, and services without classes / decorators.

The limitation of using classes + decorators is clear - some reuse techniques (like composition) that are easy to do with functional programming, is hard to do with classes, due to the limiting nature of inheritance. In fact - it seems like most new features in Angular 15 are a way around this fact

### Proposed solution

The idea is to enable an alternative way of creating components, without using classes / decorators:

```ts
const MyComponent = createComponent({
  selector: 'app-comp',
  template: `Hello {{name}}`,
  context: {
    name: 'World',
  },
  inputs: ['name'],
});
```
To create a component. (Then MyComponent can be used in modules, or directly imported)
The "context" property is an object from which the binding will take place. (Basically replaces the class instance). 

This has the advantage of being more flexible, and enabling the developer compose / mix different logic in ways that inheritance is usually too limiting. 
Since the "context" property can be fully typed, from the type checking perspective it should be possible to accomplish.

Please note that the suggestion is to add this option _in addition_ to the existing API, not in place of it. I understand that a lot of people will prefer the class / decorator approach so this should definitely be backward compatible. 

### Alternatives considered

Obviously there are many other ways that the API for this can be built, but the important thing is that you can provide any object / factory function to the context, and not necessary a class. That is what will enable to flexibility of reuse of code that functional programming enables, but OOP does not.

**Comment by mlc-mlapis** [comment]
@ShacharHarshuv But there are also many cases where class inheritance is how to solve them effectively and elegantly. Angular certainly need both ways.

**Comment by ShacharHarshuv** [comment]
> Angular certainly need both ways.

Of course! My suggestion was not to replace the existing API, but to supply an alternative way of doing the same thing.

**Comment by pkozlowski-opensource** [comment]
We do have some work planned around Angular authoring format in 2023. But this is a major project for which we will share RFCs, design etc. 

I'm going to close this issue as there is nothing immediately actionable for us here.

**Comment by ShacharHarshuv** [comment]
@pkozlowski-opensource So what needs to be done to promote this feature request?
