### ISSUE TITLE
State of Javascript 2022

### ISSUE THREAD

**Issue by tayambamwanza** [angular/angular#48165]
### Describe the problem that you experienced

Last year when the state of javascript survey was running, there was a banner on angular.io announcing that it was open.

The survey is once again open here: https://survey.devographics.com/survey/state-of-js/2022?s=09

Even though the data might not represent the entire reality of things, I believe it's still good to get as much data as possible for the survey to be more accurate.

It's only open for a few weeks and I've actually missed it once due to not being on social media at one time.

It might be the name or the hype, but people who are not so aware of  how Angular is doing put a lot of weight behind this survey and it is often cited (in my experience) when Angular is considered for a new project and sometimes even written off from consideration entirely.

**Comment by JoostK** [comment]
Thanks for raising this, there's an open PR in #48160 to add it.

**Comment by tayambamwanza** [comment]
@JoostK, great stuff, although I don't see the banner up yet?

**Comment by tayambamwanza** [comment]
@JoostK from the FAQ of the survey

![Screenshot from 2022-11-25 19-01-41](https://user-images.githubusercontent.com/11971384/204030119-7499a620-7f38-4543-acb5-5ab3cb1e371d.png)

**Comment by JoostK** [comment]
Oh, there seems to have been a mistake in merging #48160 only to minor. It is indeed only up at https://next.angular.io/.

@mgechev FYI
