### ISSUE TITLE
Wrong release dates in the "Actively supported versions" table on angular.io

### ISSUE THREAD

**Issue by marcwrobel** [angular/angular#48184]
### Describe the problem that you experienced

According to the Actively supported versions table on https://angular.io/guide/releases#actively-supported-versions :

* 15.0.0 has been released on 2022-11-18
* 14.0.0 has been released on 2022-06-02
* 13.0.0 has been released on 2021-11-04

But :
* 15.0.0 has been released on 2022-11-16 according to https://blog.angular.io/angular-v15-is-now-available-df7be7f2f4c8.
* 14.0.0 has been released on 2022-06-02 according to https://blog.angular.io/angular-v14-is-now-available-391a6db736af.
* 13.0.0 has been released on 2021-11-04 according to https://blog.angular.io/angular-v13-is-now-available-cce66f7bc296 and 2021-11-03 according to https://github.com/angular/angular/releases/tag/13.0.0.

So :
* 15.0.0 release date should be 2022-11-16
* 14.0.0 release date is correct
* maybe 13.0.0 release date should be 2021-11-03

### Enter the URL of the topic with the problem

https://angular.io/guide/releases#actively-supported-versions

**Comment by dylhunn** [comment]
While this does appear to be off by 1-2 days, it shouldn't have any material impact for most people. It was probably generated by a tool. If it's driving you nuts, feel free to fix it though :)
