### ISSUE TITLE
Router unwraps default imports is getting error

### ISSUE THREAD

**Issue by TanerSaydam** [angular/angular#48192]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I'm trying to export Support for default exports in `loadChildren things but I get an error.

```
{
    path: 'lazy',
    loadComponent: () => import('./app/lazy/lazy.component'),
}
```

error: 
`Type '() => Promise<typeof import("c:/Users/taner/OneDrive/Masa\u00FCst\u00FC/E\u011Fitim Videolar\u0131/Angular 15/Belgeler/my-app/src/app/lazy/lazy.component")>' is not assignable to type '() => Type<unknown> | Observable<Type<unknown> | DefaultExport<Type<unknown>>> | Promise<Type<unknown> | DefaultExport<Type<unknown>>>'.
  Type 'Promise<typeof import("c:/Users/taner/OneDrive/Masa\u00FCst\u00FC/E\u011Fitim Videolar\u0131/Angular 15/Belgeler/my-app/src/app/lazy/lazy.component")>' is not assignable to type 'Type<unknown> | Observable<Type<unknown> | DefaultExport<Type<unknown>>> | Promise<Type<unknown> | DefaultExport<Type<unknown>>>'.
    Type 'Promise<typeof import("c:/Users/taner/OneDrive/Masa\u00FCst\u00FC/E\u011Fitim Videolar\u0131/Angular 15/Belgeler/my-app/src/app/lazy/lazy.component")>' is not assignable to type 'Promise<Type<unknown> | DefaultExport<Type<unknown>>>'.
      Type 'typeof import("c:/Users/taner/OneDrive/Masa\u00FCst\u00FC/E\u011Fitim Videolar\u0131/Angular 15/Belgeler/my-app/src/app/lazy/lazy.component")' is not assignable to type 'Type<unknown> | DefaultExport<Type<unknown>>'.ts(2322)
index.d.ts(2351, 5): The expected type comes from property 'loadComponent' which is declared here on type 'Route'`

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
