### ISSUE TITLE
Updating object member doesn't trigger update event on object

### ISSUE THREAD

**Issue by awiseman** [angular/angular#4821]
It seems that update detection on objects when member values are updated is broken in alpha.38-44.

Simple example: http://plnkr.co/edit/WvtpiIs3oWdFoEIeL2LR?p=preview

Multi-component: http://plnkr.co/edit/edaFIfQIXgutN6nwXuwi?p=preview

**Comment by mhevery** [comment]
The issue is that `JSON` pipe
