### ISSUE TITLE
Localized bundle generation failed: Cannot read properties of undefined (reading 'value’) on try to localize the app 

### ISSUE THREAD

**Issue by avfigueredo** [angular/angular#48221]
### Which @angular/* package(s) are the source of the bug?

localize

### Is this a regression?

No

### Description

I’m trying to build my application using the localization files, but I’m getting the error below when  I run `ng build --prod sport`

`Localized bundle generation failed: Cannot read properties of undefined (reading 'value') `

This is my angular.json file:

`"sport": {
      "projectType": "application",
      "schematics": {
        "@nrwl/angular:component": {
          "style": "scss"
        }
      },
      "root": "apps/sport",
      "sourceRoot": "apps/sport/src",
      "prefix": "athleta",
      "i18n": {
        "sourceLocale": "de",
        "locales": {
          "en": "apps/sport/locale/messages.en.xlf"
        }
      },
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "localize": true,
            "allowedCommonJsDependencies": [
              "localforage-getitems",
              "util",
              "hammerjs",
              "file-saver"
            ],
            "outputPath": "dist/apps/sport",
            "index": "apps/sport/src/index.html",
            "main": "apps/sport/src/main.ts",
            "polyfills": "apps/sport/src/polyfills.ts",
            "tsConfig": "apps/sport/tsconfig.app.json",
            "aot": true,
            "assets": [
              "apps/sport/src/assets",
              "apps/sport/src/pwa-manifest.json",
              "apps/sport/src/silent-renew.html"
            ],
            "styles": [
              "apps/sport/src/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "apps/sport/src/environments/environment.ts",
                  "with": "apps/sport/src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": true,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "10kb"
                }
              ]
            },
            "en": {
              "aot": true,
              "localize":["en"]
            },
            "e2e": {
              "fileReplacements": [
                {
                  "replace": "apps/sport/src/environments/environment.ts",
                  "with": "apps/sport/src/environments/environment.e2e.ts"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "sport:build",
            "port": 4201
          },
          "configurations": {
            "production": {
              "browserTarget": "sport:build:production"
            },
            "e2e": {
              "browserTarget": "sport:build:e2e",
              "port": 0
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "sport:build"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "apps/sport/tsconfig.app.json",
              "apps/sport/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**",
              "!apps/sport/**/*"
            ]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "apps/sport/jest.config.js",
            "tsConfig": "apps/sport/tsconfig.spec.json",
            "passWithNoTests": true,
            "setupFile": "apps/sport/src/test-setup.ts"
          }
        }
      }
    },`

This is my messages.en.xlf

`<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="de" datatype="plaintext" original="ng2.template">
    <body>
      <trans-unit id="ee1725f94bc5d74b045c41d3ee0d4e8392c3dad0" datatype="html">
        <source>Mein Profil</source>
        <target>My Profile</target>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/pages/profile/desktop/profile-desktop.component.html</context>
          <context context-type="linenumber">5</context>
        </context-group>
      </trans-unit>
    </body>
  </file>
</xliff>
`

### Please provide the exception or error you saw

```true
`Localized bundle generation failed: Cannot read properties of undefined (reading 'value') `
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 10.0.8
Node: 16.15.1
OS: darwin arm64

Angular: 10.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cdk                      8.2.3
@angular/cli                      10.0.8
@angular/material                 8.2.3
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.6.7
typescript                        3.9.10
webpack                           4.43.0
```

**Comment by alan-agius4** [comment]
Hi @avfigueredo, 

Angular 10 is no longer supported, see our [Support policy and schedule](https://angular.io/guide/releases#support-policy-and-schedule) guide.

Please update to the most recent version. If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
