### ISSUE TITLE
Change FormBuilder scope to "root"

### ISSUE THREAD

**Issue by angelaki** [angular/angular#48237]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

Not just is the `providedIn: module` syntax deprecated, is there any reason I do not see that it every was provided with the module and not as a singleton?

[FormBuilder](https://github.com/angular/angular/blob/12db49223356e555205257f37a292a9b8579039e/packages/forms/src/form_builder.ts#L110)

### Proposed solution

providedIn: 'root'

### Alternatives considered

-

**Comment by angelaki** [comment]
If there even is a reason it was provided with the module, I'm curious about the new solution? Imho deprecating treeshakable module providers (with no alternative way?) was not a good decision.

**Comment by sr5434** [comment]
How would you import the for builder?

**Comment by angelaki** [comment]
> How would you import the formBuilder?

Why not just provide it in root? Its a singleton / stateless anyway.

**Comment by angelaki** [comment]
So the old module scope was obviously just wrong? Now I got, why you deprecated this possibility.

Never the less - is there still any posibility to provide a tree-shakable service with a module?

**Comment by AndrewKushnir** [comment]
> Never the less - is there still any posibility to provide a tree-shakable service with a module?

You can annotate services with the `@Injectable({providedIn: 'root'})` decorator to make them tree-shakable. Do you have a specific use-case where a connection to an NgModule is required?

**Comment by angelaki** [comment]
> > Never the less - is there still any posibility to provide a tree-shakable service with a module?
> 
> You can annotate services with the `@Injectable({providedIn: 'root'})` decorator to make them tree-shakable. Do you have a specific use-case where a connection to an NgModule is required?

Yeah, your probably right... I actually have none. But isn't the use-case imaginable that a module provides a service that **can** be used but there's no need to use it? Never the less, I'm coming from a module-based approach. And they are getting lesser anyway. Being a component / framework developer, I just don't like the idea of removing feature because they could be misused.

By the way: was there a reason the FormBuilder was provided with the module? Or was this acatually just a misusage?

**Comment by sr5434** [comment]
> By the way: was there a reason the FormBuilder was provided with the module? Or was this acatually just a misusage?

I think it might have been to keep everything organized (if every service was provided in root, the documentation would probably be a mess).

**Comment by AndrewKushnir** [comment]
> By the way: was there a reason the FormBuilder was provided with the module? Or was this acatually just a misusage?

@angelaki as @sr5434 mentioned above, this was mainly for the code and docs organization.

**Comment by angelaki** [comment]
But if I'm not mistaken this would create a new `FormBuilder` instance for every import of the `FormsModule`. Not that this would consume much memory, but ...

**Comment by AndrewKushnir** [comment]
@angelaki changing the `providedIn` to "root" would have no effect: an instance of the `FormBuilder` class would be created once and stored in the root injector. The instance would be reused across an app when injected.

**Comment by angelaki** [comment]
@AndrewKushnir Yeah, sure. Providing it in `root` was my accepted recommendation. I mean the earlier behavior, providing it with the module.
