### ISSUE TITLE
blackbox angular code to work on particular components

### ISSUE THREAD

**Issue by JSmithOner** [angular/angular#48235]
### Which @angular/* package(s) are relevant/related to the feature request?

For future angular releases

### Description

I've seen you've added components without modules and also the possibility to make standalone components.
My concern is that I would like to share my project for other people to work on without having to share with them the whole code.
For example if someone's need to work on a particular component it would be nice if you had a command to obfuscate certain files and make visible others, this way the project project is partially protected and work can be didvided between multiple individuals. I don't know if a wasm or a simple obfuscation would be sufficient. 

### Proposed solution

use an obfuscated wasm module or simply obfuscate code with a command like

`ng sandbox --include * --exclude ./src/app.component.ts

### Alternatives considered

Create another project with mocks to keep the desired unobfuscated component to work. This implies to create a new project for each components then merge it to main repo which seems a heavy task to do.

**Comment by pkozlowski-opensource** [comment]
JavaScript code, obfuscated or not, is visible to others as soon as a browser it able to run it. We are also not planning to compile to wasm at this point.

Thnx for the suggestion but we consider this feature request as outside of Angular's scope.
