### ISSUE TITLE
Angular2 build browserify or webpack

### ISSUE THREAD

**Issue by tamascsaba** [angular/angular#4823]
Which tool is prefered by angular team, and why?

**Comment by pkozlowski-opensource** [comment]
I will be talking about it tomorrow during AngularConnect: http://angularconnect.com/sessions#modularity-and-packaging-for-angular2-applications

The talk will be streamed so you can watch it live tomorrow or later on on YouTube

**Comment by tamascsaba** [comment]
Thanks :) :+1:
