### ISSUE TITLE
Scoped styles per module

### ISSUE THREAD

**Issue by PieterjanDeClippel** [angular/angular#48243]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Now we're only able to write styles per component. These styles are scoped to the component.

I would like to be able to use other UI frameworks (eg. Bootstrap, Tailwind, ...), to write a component library for angular.
At the moment the only way I know to achieve this is like this:

    @Component({
      selector: 'bs-accordion',
      styleUrls: [ './accordion.component.scss' ],
      template: '...'
    })
    export class BsAccordionComponent { }

    @Component({ selector: 'bs-accordion-tab' })
    export class BsAccordionTabComponent { }

accordion.component.scss

```
:host ::ng-deep {
    // Configuration
    @import "~bootstrap/scss/functions";
    @import "~bootstrap/scss/variables";
    @import "~bootstrap/scss/mixins";

    // Layout & components
    @import "~bootstrap/scss/accordion";

    // Custom SCSS
    bs-accordion {
        margin: -1px;
    }
}
```

`::ng-deep` is required for components that need to work together to make the styles work over all these components.
However, using `::ng-deep` indicates that these styles cannot be bundled into the component.js. Because of this, angular will **now** create javascript chunks containing these styles, and bundle them in the main bundle, creating a massive main bundle with component styles that aren't really needed (in the case of a component library).

Atm, we may as well just import `tailwind.css` or `boostrap.css` entirely, but this increases the initial bundle load, which is obviously something we need to avoid.

### Proposed solution no. 1

It would be really useful to support module-scoped `styleUrls`. This way we'd be able to have a module declaring multiple components

```
@NgModule({
  declarations: [
    BsAccordionComponent,
    BsAccordionTabComponent,
    BsAccordionTabHeaderComponent
  ],
  imports [ ... ],
  styleUrls: [ './accordion.module.scss' ],
})
export class BsAccordionModule {}
```

This way styles can be loaded when the module is being loaded, and would reduce initial load time of applications using component libraries.

This would require one of 2 things:
1) An additional scope-attribute on the components declared by the module `...[_ngModule_c25]`
2) Adding component tags to the selectors in the generated css (incremental complexity)

### Proposed solution no. 2
pseudo-code:
```
if (selector.contains(':host')) {
  // Styles must be bundled in component module bundle
  // since :host restricts them to this scope anyway...
} else if (selector.contains('::ng-deep')) {
  // Styles must be bundled in the main bundle
  // to make them work at all time
  // (now the case)
} else {
  // Styles are bundled in the component module bundle
}
```

Don't bundle style chunks in the main bundle when the selector contains a `:host` annotation. Only then bundle style chunks in the main bundle when the selector contains a `::ng-deep` annotation.

I really hope you consider this. It doesn't seem really complex compared to the gains of module-scoped styles.

### Alternatives considered

Using directives as sub-components, but this isn't always possible.

```
<bs-accordion>
  <div bsAccordionTab>...</div>
  <div bsAccordionTab>...</div>
</bs-accordion>
```

This would still require the use of `::ng-deep`, and would only be an option if the sub-components don't contain complex logic.

**Comment by PieterjanDeClippel** [comment]
`::ng-deep` styles are bundled in the main bundle.

But shouldn't `:host ::ng-deep` styles be bundled into the component module bundle?

**Comment by PieterjanDeClippel** [comment]
Hi, it seems that all I had to do is modify my library and provide an entrypoint per component. The webpack chunks in the main bundle are now only the necessary: https://stackoverflow.com/a/74728818/8941307

**Comment by alxhub** [comment]
Closing as the issue was resolved and ended up not being related to style locations.
