### ISSUE TITLE
location: should have a .search() method

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#4824]
I can see that the `Location` service has a `.path()` method which can be used to fetch the path, but how about the search query params? If there isn't already a way to get the params, wouldn't it make sense for the `Location` to have a `.search()` method which would return that?

**Comment by rolandjitsu** [comment]
Probably `RouteParams` already covers this, but will it work in components that are not bound to a route?

**Comment by btford** [comment]
We don't want this. It breaks the encapsulation of the component model.

**Comment by btford** [comment]
@mhevery – please check with me next time before tagging issues like this so that the community doesn't spend time on something fruitless.

**Comment by mhevery** [comment]
@btford sorry about that.
