### ISSUE TITLE
Make FormControlName directive typed

### ISSUE THREAD

**Issue by sharshuv-quotient** [angular/angular#48255]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

the biggest disadvantage of the `FormControlName` directive is that it's not typed. You can pass anything to the name input, regardless if it's in the form group or not, which might cause runtime exception.
I'm wondering if there is a way that can be improved, so this mistake will be caught in build time.

I'm not even sure if that's technically possible - i.e. can we understand the context of the directive in build time? But I thought it might be worth bringing it up as maybe someone with better expertise than me can help answer that. 

### Proposed solution

`FormControlName`'s input should be typed based on the form group used. Not sure exactly if that's possible and how.

### Alternatives considered

the workaround is not using form control name, and always using "formControl" directive. Which is possible but get annoying if you have a long path of nested controls.

**Comment by alxhub** [comment]
The challenge here is that it's not really possible to type this correctly today. `FormControlName` gets the current `FormGroup` from DI, which is entirely determined at runtime. Only looking at a given template, it might not even be possible to determine the current `FormGroup` even as a human reading the code.

I think long term, the better option is not to rely on string keys for linking the control model to its control instance.

**Comment by Harpush** [comment]
> The challenge here is that it's not really possible to type this correctly today. `FormControlName` gets the current `FormGroup` from DI, which is entirely determined at runtime. Only looking at a given template, it might not even be possible to determine the current `FormGroup` even as a human reading the code.
> 
> I think long term, the better option is not to rely on string keys for linking the control model to its control instance.

Won't it bring you to `get` "hell" then? For control name makes template much easier than doing nested gets on large forms.

**Comment by sharshuv-quotient** [comment]
In our source code, we actually deliberately don't use formControlName because of the typing issue. We prefer being more verbose and type safe. I think it's possible to make the "get" method on a FormGroup typed, because the form group should know the type of its controls.

**Comment by fMoro1999** [comment]
Hi! Any update on this?

**Comment by alxhub** [comment]
I'm going to close this feature request, as it's fundamentally not possible for the `FormControlName` directive to do any compile-time validation around the presence or absence of a given control in the `FormGroup`.

**Comment by Harpush** [comment]
@alxhub isn't it just missing compile time type linking using DI. If I inject a parent generic directive and declare myself generic with constrain to keyof it could maybe work with compiler logic?
