### ISSUE TITLE
Angular2 Docs

### ISSUE THREAD

**Issue by TiagoBraga39** [angular/angular#4826]
Hi all!

Probably not the best place to post this, but follow this path.
1. https://angular.io/cheatsheet
2. Title "Directive and component change detection and lifecycle hooks (implemented as class methods)" (use find)
3. afterViewInit() Description.

It says "Called after onContentInit when the component's view has been initialized. Applies to components only.".

Called after afterContentInit() right?

Feel free to close this anytime :)

Stay awesome,
Tiago Braga

**Comment by vicb** [comment]
Thanks for your report, please re-open on https://github.com/angular/angular.io.
