### ISSUE TITLE
router: router.recognize(path) fails if path has query params

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#4827]
It looks like if I try to use the `router.recognize(path)` when `path` is of `/login/;return_url=/account` shape, the path is not recognized.

It would makes sense that the path recongnizer would ignore the query params and look at the path instead, so it would look at `/login/` which will probably be recongnized assuming that there is a route matching that path.

**Comment by btford** [comment]
:+1: Will investigate when I get a change.

**Comment by rolandjitsu** [comment]
great :+1:

**Comment by btford** [comment]
@rolandjitsu – can you show your RouteConfig (or better yet, a runnable example)? This may be improper use of the API.

**Comment by rolandjitsu** [comment]
@btford I tried it in my app available [here](https://github.com/rolandjitsu/ng2-lab), but removed it since it was not working. I could try to make a plunk tonight to illustrate the behaviour. But it basically happens [here](https://github.com/rolandjitsu/ng2-lab/blob/master/src/app/components/app/app.ts#L54) and [here](https://github.com/rolandjitsu/ng2-lab/blob/master/src/app/components/app/app.ts#L61).

Perhaps it is just me wrongly using the API. I also keep getting things like `Cannot reuse an outlet that does not contain a component` when I use the browser back button and the
```js
router.subscribe((path) => {
	router.recognize(path).then((instruction: Instruction) => {
		if (!client.session && !isAuthComponent(instruction)) router.navigate(['/Auth', 'Login']);
	});
});
```
navigates back to the path I was on (the same path `router.navigate(['/Auth', 'Login'])` leads on).

Furthermore, for some reason I could not debug, when the `router.navigate` is invoked and it navigates to some page, change detection seems to not be triggered until I click inside an input and then blur out.

Sorry for just pasting some links in here :)

**Comment by btford** [comment]
This might be the same issue as #4728

**Comment by rolandjitsu** [comment]
@btford maybe ...

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router robust.

It doesn't look like the issue makes sense in the context of the new router. If you think it does, please reopen the issue.

Closing this issue.
