### ISSUE TITLE
Rendering "&nbsp;" in Template Breaks Depending on Ternary Condition

### ISSUE THREAD

**Issue by chezwicker** [angular/angular#48275]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

This may be a regression, I somehow hope so ;-)

The following two expressions lead to different results in a template:

|Input|Rendered|Comment|
|-|-|-|
|`{{(!![] && true) ? ":&nbsp;" : ""}}` | `:&nbsp` | rendered literally |
|`{{(!![]) ? ":&nbsp;" : ""}}` |  `: ` | rendered as a space |

If this is not easy to reproduce, I'll look to create a minimal repro as soon as a have a little more time - please let me know!

### Please provide the exception or error you saw

```true
n/a
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 14.2.11
Node: 16.15.1
NPM: 8.11.0
TS: 4.8.4
OS: MacOs 13.0.1
```

**Comment by JeanMeche** [comment]
It's a dupe of #44827

The problem happens in presence of `&&`.

**Comment by chezwicker** [comment]
Sorry, didn't see that one ;-(
