### ISSUE TITLE
SVG Elements wrapped in ShadowDom Component not focusable using tabindex

### ISSUE THREAD

**Issue by monsterrave** [angular/angular#48277]
### Which @angular/* package(s) are the source of the bug?

common, core, forms

### Is this a regression?

No

### Description

I am trying to make use of the default behaviour when a user presses Tab to iterate over input elements.

I want to make SVG elements focusable by key stroke. The SVG is wrapped inside a component.

```
<parent-component>        
  <input>
  <child-component></child-component>
  <input>
</parent-component>
```

child-component.html

```
<svg>
  <g (click)='doSomething' tabindex='0' focusable='true'></g>
</svg>
```

Can't make it work with tabindex or focusable tho.

I am logging the active/focused element like this

```
@HostListener('document:keydown.tab', ['$event'])
  omitFocusedElement(e: KeyboardEvent) {
    console.log(document.activeElement)    
  }
```

Tabbing order breaks and the element before the nested svg keeps the focus, tabbing does not go any further then

So instead, I tried something else

```
<parent-component>
  <input>
  <svg>
    <g (click)='doSomething' tabindex='0'></g>
  </svg>
  <input>
</parent-component>
```

When the svg is not contained by a component, it becomes focusable.

But I need to make it work, when a svg is wrapped by a component.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.5
Node: 14.16.0
Package Manager: npm 6.14.11
OS: win32 x64

Angular: 13.3.12
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.10
@angular-devkit/build-angular   13.3.5
@angular-devkit/core            13.3.10
@angular-devkit/schematics      13.3.5
@angular/cdk                    13.3.9
@angular/cli                    13.3.5
@angular/compiler-cli           13.3.8
@angular/language-service       13.3.8
@schematics/angular             13.3.5
rxjs                            7.5.7
typescript                      4.6.4
```

**Comment by monsterrave** [comment]
Probably not a bug, sorry

So appearantly the reason that those elements could not receive focus was, that the component which contains the svg was set to ViewEncapsulation.ShadowDom. Because when i removed that, svg elements become focusable.

The downside to this is, that i need to use this encapsulation.

**Comment by pkozlowski-opensource** [comment]
@monsterrave it is not clear to me at this point if you still consider this a bug or not? Could you please share a minimal reproduction scenario in a stackblitz so we can confirm / investigate?

**Comment by monsterrave** [comment]
Seems to work with ViewEncapsulation.Emulated
