### ISSUE TITLE
ngClass broken in standalone components

### ISSUE THREAD

**Issue by nikita-fuchs** [angular/angular#48299]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

When using `[ngClass]` in a standalone component, the compiler complains.
See repro in line 30.

EDIT: It actually seems to break all the input properties of the whole project once you have a standalone component somewhere?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-sdcxjq?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
`Can't bind to 'ngClass' since it isn't a known property of 'a'.`
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.0
Node: 14.20.1
Package Manager: npm 6.14.17
OS: darwin x64

Angular: 15.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0
@angular-devkit/build-angular   15.0.0
@angular-devkit/core            15.0.0
@angular-devkit/schematics      15.0.0
@angular/google-maps            12.1.0
@schematics/angular             15.0.0
rxjs                            6.6.2
typescript                      4.8.4
```

### Anything else?

Looked forward for standalone components so much, please fix this 🙏

**Comment by nikita-fuchs** [comment]
why does this become necessary in a standalone component? Plus, all the other `inputs` for other components suddenly break, too: 
Example:
```
Error: src/app/pages/forms/form-layouts/form-layouts.component.html:21:41 - error NG8002: Can't bind to 'icon' since it isn't a known property of 'nb-icon'.
1. If 'nb-icon' is an Angular component and it has 'icon' input, then verify that it is part of this module.
2. If 'nb-icon' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

21             <nb-icon class="centerIcon" [icon]="'question-mark-circle-outline'" pack="eva" nbPopover="Enter a Name, 'TurboApe' " nbPopoverTrigger="hover" nbPopoverPlacement="right"></nb-icon>
```

This disappears again once making the component non-standalone again.

**Comment by pkozlowski-opensource** [comment]
All standalone components must explicitly import the template dependencies (components, directives and pipes) that they are using - the explicit listing of template dependencies is the very reason of standalone components existence. See the original RFC: https://github.com/angular/angular/discussions/43784
