### ISSUE TITLE
Template does not work in IE/Edge table

### ISSUE THREAD

**Issue by todoubaba** [angular/angular#4830]
IE/Edge does not support `template` in a table, the following code works fine in Chrome and FF.
```typescript
@Component({
  selector: 'my-cmp',
  template: `
  <table border>
    <thead>
      <th>col1</th>
      <th>col2</th>
    </thead>
    <tbody>
      <template ng-for #rx [ng-for-of]="values" #i="index">
        <template ng-for #ry [ng-for-of]="rx.y" #j="index">
          <tr>
            <td *ng-if="j == 0" [attr.rowspan]="rx.y.length">{{rx.x}}</td>
            <td>{{ry}}</td>
          </tr>
        </template>
        <tr><td>sum</td><td>{{sum(rx.y)}}</td>
      </template>
    </tbody>
  </table>
  `,
  directives: [CORE_DIRECTIVES]
})
class MyCmp {
  values = [
    { x: 1, y: [11, 12] },
    { x: 2, y: [21, 22] }
  ];

  sum(y: number[]) {
    let total = 0;
    for(let i = 0; i < y.length; i++) {
      total += y[i];
    }
    return total;
  }
}
```
@diadistis provided a [workaround](http://plnkr.co/edit/4r5rjK5a1c9KhwpE3FtJ?p=preview), but it's not natual for a template/html author. Could ng2 parse the template  in a browser independent fashion, or support something like ng1's `ng-repeat-start` and `ng-repeat-end`?

**Comment by mhevery** [comment]
This should be solved in the new Compiler parser.

**Comment by yaroslavya** [comment]
Not sure if its the same issue or not, but the workaround from the issue above doesnt work in ie any more. Im on windows7 with IE11. And I only see the "loading" message and nothing more. 
I also tried the initial example of angular2 on plunker ( ts, es6 and es5 based ) and none of them work in ie. By none of them work I mean that `my-app` tag is not rendered and remains the `<my-app></my-app>` in the DOM.

**Comment by mexx** [comment]
@yaroslavya 
The `system-polyfills.js` is not present at `https://code.angularjs.org/tools/system-polyfills.js`. `system.js` tries to load it if there is no `URLPolyfill` or `Promise` object declared. See [docs](https://github.com/systemjs/systemjs#polyfills).

**Comment by mexx** [comment]
With `system-polyfills.js` and `system.js` from the `system.js dist` folder it now fails in `_clearValues` value creation in [collection.ts#L45](https://github.com/angular/angular/blob/a31e2f5f4799e9ce20ae508f9f91dfeba05805f2/modules/angular2/src/facade/collection.ts#L45) as `keys` is not provided in IE.

**Comment by ericmartinezr** [comment]
@mexx you must add es6-shim as well (make sure that you put that lib in the first place)

**Comment by mexx** [comment]
@ericcarraway I thought I don't have to manage this dependencies by myself ;)

**Comment by pkozlowski-opensource** [comment]
> I thought I don't have to manage this dependencies by myself ;)

We _might_ make it easier through #5223 where we might produce a bundle with all deps concatenated. But for now a developer is responsible for including all the required polyfills as which polyfills are needed depends on a set of browsers that one needs to support.

Closing this one as I don't think we've got anything actionable here that is not covered in other issues already.

**Comment by mexx** [comment]
@pkozlowski-opensource With the all the shims in place the originally reported error is still present, so I would vote for a reopen ;)

**Comment by yaroslavya** [comment]
@mexx, @pkozlowski-opensource thanks for the info, guys. Im just not sure who should fix the backed in example in plunker. As for now a lot of people who are looking any info on angular2 are opening plunker, choosing the angular2 ts project and it doesnt work in ie. It seems it should work out of the box, so someone should update it. Probably someone should contact the plunker team.

**Comment by pkozlowski-opensource** [comment]
We can reopen, by the compiler refactor that Misko was mentioning just landed in master so I'm pretty positive that this will be fixed in alpha.47

**Comment by pkozlowski-opensource** [comment]
@yaroslavya I'm with you regarding polyfills by default. Will discuss this with the folks in charge of documentation.

**Comment by yaroslavya** [comment]
Heres the corresponding [issue](https://github.com/filearts/plunker/issues/99) in plunker so that ggoodman could update the plunker template(if its needed) after this issue is resolved.

**Comment by pkozlowski-opensource** [comment]
Closing as with a8edc1eb58b2f70b3cb2e427e5b0ee4484fd4ea4 we've got our own HTML parser that should behave consistently across all browsers.
