### ISSUE TITLE
router - Use $routeParams in an Angular 1 application

### ISSUE THREAD

**Issue by vguede** [angular/angular#4831]
How can I use $routeParams in an Angular 1 application (in ES5) ?
```javascript

// (...)
Directive.$routeConfig = [{
  path: '/test/:id',
  component: 'test',
  as: 'Test'
}];
// (...)

TestController = function($routeParams) {
  this.routeParams = $routeParams;
}
```

this.routeParams is always empty ( === {}).

**Comment by brandonroberts** [comment]
@vguede There isn't a way to access them currently through the injector. You can access them in the onActivate method which is called after the constructor.

```
TestController.prototype.$onActivate = function(to, from) {
  this.routeParams = to.params;
}
```

**Comment by vguede** [comment]
@brandonroberts Many thanks !

**Comment by siulung4073** [comment]
Hi. this is not working on the last version published on @angular/router. The $onActivate method is never called. In fact in the https://github.com/brandonroberts/angularjs-component-router repo which has one example of this, it doesn't work either.
thanks!

**Comment by robwormald** [comment]
@siulung4073 the lifecycle hook names have changed in the latest versions. try $routerOnActivate

**Comment by brandonroberts** [comment]
@siulung4073 The repo has been updated with the correct lifecycle hooks. Thanks

**Comment by vguede** [comment]
@brandonroberts Is the templateUrl bug fixed in the router's latest version ?

**Comment by siulung4073** [comment]
Great! Thanks for the help. It wasn't working before because I was using TemplateUrl, and it seems there is a bug there

**Comment by brandonroberts** [comment]
@vguede No it hasn't been fixed yet. The ng1 specific pieces don't get updated as frequently as the ng2 versions. 

@siulung4073 Yea it is a bug. There is a workaround here https://github.com/angular/angular/issues/4633

**Comment by siulung4073** [comment]
I saw that one thanks!

**Comment by eqbalsajadi** [comment]
I have same problem activate method invokes before templateUrl resolves

**Comment by eqbalsajadi** [comment]
you can access route params inside the controller after injecting $router
via: $router._currentInstruction.component.params

**Comment by amritk** [comment]
@eqbalsajadi That is amazing!!! You are the man! Much better than prototyping.

**Comment by eqbalsajadi** [comment]
You are welcome
