### ISSUE TITLE
How can i fix the problem 

### ISSUE THREAD

**Issue by chenabel** [angular/angular#48333]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I got a component, now i want to test it.  the component like this 
![image](https://user-images.githubusercontent.com/81562835/205429979-319c4b8a-7a03-40e2-ae8a-9ac90f3c9ea6.png)
when i run the command "ng test", the angular report a error message to me
![image](https://user-images.githubusercontent.com/81562835/205429875-11552abb-4b82-44ef-a3d9-81e08b968d46.png)

the Test file like this 
![image](https://user-images.githubusercontent.com/81562835/205429951-97437418-3048-4663-8981-468b8994aa12.png)

I want to fix it, but I have not idea.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/cli": "^11.2.19",
"jasmine-core": "~3.6.0",
"jasmine-spec-reporter": "~5.0.0",
"karma": "~6.3.9",
"karma-chrome-launcher": "~3.1.0",
"karma-coverage": "^2.1.1",
"karma-jasmine": "~4.0.0",
"karma-jasmine-html-reporter": "^1.5.0",
"@types/jasmine": "~3.6.0",
"@types/jasminewd2": "^2.0.8",
```

**Comment by chenabel** [comment]
pla help me

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
