### ISSUE TITLE
Size and Lighthouse Issues with hello world app (V15)

### ISSUE THREAD

**Issue by goodmite** [angular/angular#48334]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I just installed Angular v15 to check hello world app size.

I ran this command
`ng s --port 4202 -o --configuration production`

I found out it loads 600kb (non-Gzipped) size. Excluding polyfills its still about 450kb!!

<img width="1747" alt="image" src="https://user-images.githubusercontent.com/16303528/205431688-92968f94-0ad6-4cc5-8ff6-de8c4e8895de.png">

I checked lighthouse score and I got performance score between 50 and 70

<img width="1762" alt="image" src="https://user-images.githubusercontent.com/16303528/205431753-47d7fdd0-c248-420a-8c7b-39f86ba817d8.png">

From [this SO answer](https://stackoverflow.com/a/46084498), I got a flag `build-optimizer`

but when I run 

`ng s --port 4202 -o --configuration production --build-optimizer`

I got error:

`Error: Unknown argument: build-optimizer`

Am I doing something wrong or this is expected? What is the official hello world size?

### Please provide a link to a minimal reproduction of the bug

Hello world app

### Please provide the exception or error you saw

```true
Large size of hello world app
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.1
Node: 16.16.0
Package Manager: yarn 1.22.11
OS: darwin x64

Angular: 15.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.1
@angular-devkit/build-angular   15.0.1
@angular-devkit/core            15.0.1
@angular-devkit/schematics      15.0.1
@schematics/angular             15.0.1
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by goodmite** [comment]
Thanks @geromegrignon
I ran `ng build --stats-json && webpack-bundle-analyzer dist/angular-v15-ngxs/stats.json`
and got leaner files:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/16303528/205447617-d81ee35f-1b2c-49f5-aba6-517894c0626f.png">

**Comment by alan-agius4** [comment]
I am seeing a number of files which are not part of a default Angular CLI project. Like `axe.js`, `installHook.js` and `highlighter.js`. Probably these are added by a chrome extension.

The `build-optimizer` option is only available in the browser builder `ng build`. 

See the docs for more information:
http://angular.io/cli/build
http://angular.io/cli/serve

**Comment by goodmite** [comment]
@alan-agius4 @geromegrignon 
deployed the site. Link: https://angular-hello-world-lighthouse.netlify.app/
And got perfect lighthouse score!
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/16303528/206109590-f5d332fd-89d8-4cee-a998-fa72d374a39a.png">
