### ISSUE TITLE
Make angular 15 compatible with node v19.2.0

### ISSUE THREAD

**Issue by Sravan6969** [angular/angular#48373]
### Is this a bug report or a feature request?

- [ ] Bug Report
- [X] Feature Request

### Description [Feature Request only]

currently Angular 15 doesn't support Node v19.2.0 and I am using M1 Mac apple silicon.
I am unable to downgrade the angular versions or nodeJS version,

### Proposed solution [Feature Request only]

make angular 15 compatible node 19.2.0

**Comment by JeanMeche** [comment]
Angular only supports [active LTS or maintenance LTS](https://angular.io/guide/setup-local), so no node 19 support is expected. 

You can use another version of node with `nvm` for example.

**Comment by alan-agius4** [comment]
Node has a two-track versioning system. Even-numbered versions (14, 18) are stable, and odd-numbered versions (17, 19) are unstable. The stable releases are API-stable and will became LTS. While the unstable versions will become unmaintained (end of life) after ~8 months.

See: https://github.com/nodejs/Release/blob/main/schedule.svg

In general it's best to use even-number versions, unless you are testing or experimenting with new Node.js features.

Closing as per above.
