### ISSUE TITLE
refactor(upgrade): better names for adapter APIs

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#4837]
Currently the `UpgradeAdapter` comes with two APIs to make Angular 1 and Angular 2 components interoperable:

- `upgradeNg1Component('directiveName')` - upgrades an A1 directive to A2 and allows us to define it as directive dependency on an A2 component
- `downgradeNg2Component(Ng2Component)` - downgrades an A2 component to an A1 directive so we can bootstrap it in A1 application.

There are two things that feel a bit weird when using those APIs, mainly because the names don't really fit.

1. The idea of `upgrade` is that we're *upgrading* an Angular 1 app to Angular 2. However, when we take an A2 component and we want to bootstrap in an A1 module, we have to *downgrade* it. While this is technically true, the naming says the total opposite of what we actually wanna do.

2.  During upgrade, an Angular 2 component *always* lives in an A1 module. So even if we have an A2 component that uses A1 directives using `upgradeNg1Component()`, we have to *downgrade* the A2 component again to make it available to the outer A1 module. Again, technically this is all correct, but it feels weird from a naming perspective that we upgrade A1 components in A2 components that will be downgraded again.

Not sure if we should go back to `import/export` or, what @petebacondarwin suggested, "wrapping" an A1 component as A2 component and vice versa.

Another idea that came up by @arvidkahl was sth. "transforming" a component. So maybe `transformNg1Component()` and `transformNg2Component()` although, those two names don't really say what we're transforming to..

Just leaving that here, would love to here your thoughts on this @mhevery

**Comment by wardbell** [comment]
I like "wrapAs".   `wrapAsNg2Component('directiveName')`   and `wrapAsNg1Directive(component)`.

**Comment by mhevery** [comment]
Just a point of personal experience. The original API was `importNg2Component` and `exportNg1Component` (see: https://github.com/angular/angular/commit/059e8faae2ac27b1bea2f7a16f203e2415eb952f) and it turns out that is really confusing, because import/export really depend on from which point you are looking at it.   Wether it is from NG1 or from NG2. It was really making my heads hurt, and I was the one who wrote it. A NG1 component is exported to Ng2, but Ng2 imports Ng1 component. It will give you a headache very quickly.

The reason I like `upgrade`/`downgrade` is that it implies specific direction. It makes no sense to `upgrade` Ng2 Component to Ng1 Component. It only makes sense to `upgrade` Ng1 component to Ng2 component. Which is why we have chosen that name.

@PascalPrecht I am not sure I understand you argument that the names are opposite of what you want to do. I upgrade ng1 so that it can be used in ng2, and you downgrade ng2 so that it can be used in ng1. 

@wardbell `wrapAs` is just as confusing as `import`/`export` because every component is wrapped. It implies no direction.

**Comment by johnpapa** [comment]
I like

[ ] - `morphAs`
[ ] - `wrapAs`
[ ] - `convertTo`

**Comment by wardbell** [comment]
It seems to me that `...AsNg2` and `..AsNg` are pretty clear indicators of direction.  

"Upgrade" and "Downgrade" are slightly pejorative and you have the "now you're up, now you're down" problem that Pascal is talking about. 

I don't have strong feelings about this ... but you asked ;-)

**Comment by johnpapa** [comment]
i dont like the `up` /  `down` terms.

**Comment by webteckie** [comment]
To me upgrade and downgrade feel like a final outcome.  e.g., ng2  compx was downgraded to a ng1 (therefore it cannot longer be used in ng2).  How about `useAsNg1Directive(comp)` and useAsNg2Component(dir)`.

**Comment by petebacondarwin** [comment]
The direction is not needed if you specify what you are wrapping. `wrapAsNg1Component` can only mean that you are taking an ng2 component and making it available to ng1.

**Comment by petebacondarwin** [comment]
`users...` works for me too

**Comment by petebacondarwin** [comment]
I agree that downgrade sounds pejorative

**Comment by PascalPrecht** [comment]
> I am not sure I understand you argument that the names are opposite of what you want to do. I upgrade ng1 so that it can be used in ng2, and you downgrade ng2 so that it can be used in ng1.

@mhevery Yupp, as I said, technically this is all very correct. It's just that the word "downgrade" doesn't really fit into the process of "upgrading". 

I think we have various proposals here now, maybe we can go with one of those?

**Comment by sparty02** [comment]
Another idea is creating an "internal namespace" for the ```UpgradeAdapter```, something like:
```js
import { UpgradeAdapter } from 'angular2/upgrade';

let adapter = new UpgradeAdapter();
let { fromNg1, fromNg2 } = adapter;

// Using ng2 in ng1
app.directive('productDetail', fromNg2.component(ProductDetail));
app.factory('ProductService', fromNg2.provider(ProductService));

// Using ng1 in ng2
@Component({
  ...
  directives: [
    NgFor,
    fromNg1.component('productListItem')
  ],
  template: `
    <h2>Product List</h2>
    ...
  `
})
class ProductList {
  ...
}
```

Consistently using ```from...``` provides a clue to the developer that the API they are working takes arguments that are in the context of ng1 (```fromNg1```) or ng2 (```fromNg2```).  This also makes the adapter's method names less noisy and provides a simple extension for more adapters in either context.

**Comment by PascalPrecht** [comment]
I think we went stuck wit down/upgrade for now. Closing
