### ISSUE TITLE
Rename global namespace `ng` to avoid possible conflicts with minified code of other libraries

### ISSUE THREAD

**Issue by romamatusevich** [angular/angular#48389]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

Actually global namespace name `ng` in development mode (https://angular.io/api/core/global) is not reliable. For instance in case of having other minified libraries it's possible to get name conflict based on minified output.

### Proposed solution

Rename `ng` namespace at least to: `ngDevNamespace`.

### Alternatives considered

Rename to any other not short name of the namespace.

**Comment by jessicajaniuk** [comment]
Most minifiers have reserved namespace settings. Angular has used the prefix `ng` for a very long time, and we recommend adding `ng` as a reserved prefix in your minifier's settings to avoid this problem.
