### ISSUE TITLE
FormBuilder not accepting RawValue of object while creating its FormGroup

### ISSUE THREAD

**Issue by iusamaaziz** [angular/angular#48385]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

I've this custom type FormRawValue that returns the JSON/RawValue of any AbstractControl:

```
import { AbstractControl } from '@angular/forms';
export type FormRawValue<T extends AbstractControl> = T extends AbstractControl<any, infer TRawValue> ? TRawValue : never;
```

and this simple `IPerson` interface:

```
import { FormControl, FormGroup } from '@angular/forms';
import { FormRawValue } from './Forms.type';

export interface IPerson {
  id: FormControl<number>;
  name: FormControl<string>;
}

export type Person = FormRawValue<FormGroup<IPerson>>;
```

In the component code, I've a function that creates a new FormGroup using the JSON rawValue provided to it like this:

```
public map(data: Person) { // Person is simply the rawValue of IPerson

    let group = this._formBuilder.group<IPerson>(data as any); // works fine but bad appraoch
    let group1 = this._formBuilder.group<IPerson>(data); //ERROR here, but it should work because 'data' holds exactly the same thing that formBuilder is expecting.
  }
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-s38dz8?file=src/app/app.component.ts

### Please provide the exception or error you saw

```true
Argument of type '{ id: number; name: string; }' is not assignable to parameter of type 'IPerson'.
Types of property 'id' are incompatible.
Type 'number' is not assignable to type 'FormControl<number>'.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.7
Node: 18.12.0 (Unsupported)
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 14.2.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1402.7
@angular-devkit/build-angular      14.2.7
@angular-devkit/core               14.2.7
@angular-devkit/schematics         14.2.7
@angular/cdk                       14.2.6
@angular/cli                       14.2.7
@angular/material                  14.2.6
@angular/material-moment-adapter   14.2.6
@schematics/angular                14.2.7
rxjs                               7.5.4
typescript                         4.8.4
```

**Comment by jnizet** [comment]
Hi @iusamaaziz 

`Person` is `{ id: number, name: string }`. And you're passing an instance of Person to `this._formBuilder.group<IPerson>()`. The siganture of this method is `group<T extends {}>(controls: T, options?: AbstractControlOptions | null)`. So, since you've set T to `IPerson`, what you're supposed to pass as argument is an `IPerson`, not a `Person`.

You could remove the `<IPerson>`, but I don't really see the point: most of the time, you want to pass other than just the initial value of the controls when defining the: the validators, the async validators, etc.

**Comment by iusamaaziz** [comment]
In case if we only want the initialization of controls (without validations) from raw data coming from a web API, we have to follow a long procedure like this:

1. Creating an initialization function for each entity:
```
public InitializedIPerson() : FormGroup<IPerson>{
    return this._formBuilder.group<IPerson>({
      id : new FormControl<number>(0, {nonNullable: true}),
      name : new FormControl<string>('', {nonNullable: true}),
    })
  }
```
2. Use the `patchValue` to map raw data to controls:
```
let initializedPersonControl = this.InitializedIPerson();
initializedPersonControl.patchValue(data);
```
and this is a painful process when working on enterprise projects with complex and nested models. This should be more handy.

**Comment by jnizet** [comment]
I would argue that only extremely simplistic forms won't need any validator. But anyway, if you really want this, just remove your `<IPerson>`.
See https://stackblitz.com/edit/angular-ivy-pr7xzf?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts
