### ISSUE TITLE
TemplateRef inside Component-Class is not the same as in the Component-Template

### ISSUE THREAD

**Issue by zetti-caletti** [angular/angular#48395]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When using TemplateRefs, the TemplateRef read inside the Component-Class via ViewChild doesn't seem to be the same instance as in the Component-Template.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-ei6gf1?file=src/app/app.component.ts

**Comment by JoostK** [comment]
This is working as designed; `TemplateRef` instances are created as requested and template refs for the same template are not guaranteed to have reference equality.

**Comment by zetti-caletti** [comment]
@JoostK Ok I understand. But are you sure that this behaviour makes sense, having separate TemplateRef-Instances on the SAME component for component class and template? Shouldn't Angular be able to share the TemplateRef-Instances, because this behaviour bloats memory due to unnecessary objects? I will also have twice the numbers of variables in my component when working with TemplateRefs inside the component class and template. So this gets also bloated. And last but not least this behaviour sounds weird to me and doesn't makes sense for me. I needed some time to know what was happening and I think other people get confused too. I mean I don't know the internal framework code but for me I don't know why it should be required to create duplicate TemplateRefs inside the same component. Maybe you can give a short feedback and at least this should be documented in the docs for @ViewChild.

**Comment by JoostK** [comment]
The runtime doesn't maintain shared `TemplateRef` instances; doing so would require some place to store them so it's not necessarily a reduction of memory as you suggest; that depends on the situation.
