### ISSUE TITLE
After conversion to a native app (apk) , a post with multipart/formdata stopped working  

### ISSUE THREAD

**Issue by iruthaya** [angular/angular#48400]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

When sent from a native app, the http request file content is transformed to [object Object]. 

my code as follow

import { HttpClient,HttpHeaders } from "@angular/common/http";

 httpOptions : any = {
        headers: new HttpHeaders({
            'enctype'  : 'multipart/form-data'
        })
    };

public convertBlobToFile = (blb: Blob, f:string): File => {
   return new File(
      [blb as any], // cast as any
      f, 
      {
          lastModified: new Date().getTime(),
          type: blb.type 
      }
    )
  }

let file = this.convertBlobToFile(blob,this.fileName);

 let data = {
          modifiedDoc : file,
          approvalId : this.approvalId
        }

 postModifiedDoc(data:any){  
        let formData: FormData = new FormData();          
        formData.append('modifiedDoc',data.modifiedDoc);
        formData.append('approvalId',data.approvalId);    
        console.log(data);
         return new Promise((resolve,reject)=>{                  
            this.http.post('url',formData,this.httpOptions).subscribe((res:any)=>{
                resolve(res);
            },(err)=>{
                console.log(err)
                reject(err);
            })
         })
      }

### Please provide the exception or error you saw

```true
*Native request header*

Connection: keep-alive
Accept: /
Accept-Encoding: gzip, deflate
Accept-Language: en-IN, en-US; q=0.9, en; q=0.8
Authorization: bearer mykey
Host: IP address
Referer: http://localhost/
User-Agent: Mozilla/5.0 (Linux; Android 12;  model Build/SKQ1.210216.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.61 Mobile Safari/537.36
Origin: http://localhost
X-Requested-With: io.ionic

*Native request content*

------WebKitFormBoundarydF4DbXCJ2VAS57sr
Content-Disposition: form-data; name="modifiedDoc"

[object Object]
------WebKitFormBoundarydF4DbXCJ2VAS57sr
Content-Disposition: form-data; name="approvalId"

127
------WebKitFormBoundarydF4DbXCJ2VAS57sr--


*Web request header*

Connection: keep-alive
Accept: application/json, text/plain, /
Accept-Encoding: gzip, deflate
Accept-Language: en-US, en; q=0.5
Authorization: bearer mykey
Host: IP address
Referer: http://localhost:8100/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0
enctype: multipart/form-data
Origin: http://localhost:8100

*Web request content*


-----------------------------352905997830570644603066510213
Content-Disposition: form-data; name="modifiedDoc"; filename="7fe08a44-72a2-49ae-9481-c452a8642b6e_PolicyDocument.pdf"
Content-Type: application/pdf

%PDF-1.4
%����
1 0 obj
<<
/Title()
/CreationDate(D:20221207125408Z)
/ModDate(D:20221207125409+00'00')
>>
endobj
2 0 obj
<<
/Type/Pages
/Kids[5 0 R 47 0 R 90 0 R 100 0 R]
/Count 4
/ProcSet[/PDF/Text/ImageB/ImageC]
>>
..........................
%%EOF

-----------------------------352905997830570644603066510213
Content-Disposition: form-data; name="approvalId"
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Ionic:

   Ionic CLI                     : 6.18.2 (C:\Users\Admin\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.4
   @angular-devkit/build-angular : 13.3.9
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v18.12.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.19.2
   OS     : Windows 10
```

**Comment by alxhub** [comment]
Hi @iruthaya,

In order to investigate this issue, we'll need a reproduction that doesn't involve Ionic. If this issue only shows up under Ionic, then you should file this as an Ionic bug report instead.

**Comment by iruthaya** [comment]
I apologies, but this is not a plugin issue.
Due to the conversion of blob to file, this occurred.
