### ISSUE TITLE
Change [(ng-model)]="property" to [(value)]="property"

### ISSUE THREAD

**Issue by mhevery** [angular/angular#4841]
In order to support two way data-binding Angular has `ng-model` which is used as so

`<input [(ng-model)]="username">` which desugars to:
`<input [ng-model]="username" (ng-model-changed)="username = $event">`

What the `ng-model` directive does is to impeadence match the `INPUT` element's `change`/`keydown` event with the expected name `ng-model-changed` event.

This is reasonable, but it is not cross-platform. `ng-model` only makes sense in browser, but not in native applications.

## Proposal

remove `ng-model` and move the responsibility to the render layer. So the above code will become:

`<input [(value)]="username">` which desugars to:
`<input [value]="username" (value-changed)="username = $event">`

Here the DOM rendering layer would be intelligent enough to know how to shim the DOM so that when it comes across `INPUT` element and someone registers a `value-change` event, it knows to register a `change`/`keyup` event and extract the value input value from it.

This solution is a lot more cross platform since we can just rely on the render layer to provide the right kinds of shim.

**Comment by iamisti** [comment]
Totally make sense to me, but what is about custom directives? I mean u can still be able to use `ng-model` (correct me if I'm wrong) on your custom directives, and at that point it doesn't really make sense to use the same syntax that you just proposed.

**Comment by mhevery** [comment]
@iamisti there is no need to use `ng-model` with custom directives, since any directive can create property/event pair which will allow it to be bound using `[(...)]` notation.

**Comment by mhevery** [comment]
Will not implement.
