### ISSUE TITLE
some packages doesn't work on latest angular

### ISSUE THREAD

**Issue by robertIsaac** [angular/angular#48421]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

as reported in https://github.com/gilsdav/ngx-translate-router/issues/138
there is a problem between the package with latest version, 15.0.0 works but 15.0.3 doesn't
in this repo https://github.com/robertIsaac/angular-localization
if you cloned it and run `npm i -f` then `ng s` it will work normally, but if you moved back one step `git checkout HEAD~` then run `npm i` and `ng s` you will find it will stop working

### Please provide a link to a minimal reproduction of the bug

https://github.com/robertIsaac/angular-localization

### Please provide the exception or error you saw

```true
ERROR TypeError: Cannot read properties of undefined (reading '__proto__')
    at new LocalizedRouter (gilsdav-ngx-translate-router.mjs:1001:61)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.3
Node: 16.18.1
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 15.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.3
@angular-devkit/build-angular   15.0.3
@angular-devkit/core            15.0.3
@angular-devkit/schematics      15.0.3
@nguniversal/builders           15.0.0
@nguniversal/express-engine     15.0.0
@schematics/angular             15.0.3
rxjs                            7.6.0
typescript                      4.8.4
```

### Anything else?

while this maybe the package problem not Angular, but we expect that updating to same major version of Angular shouldn't break anything

**Comment by JoostK** [comment]
[ngx-translate-router](https://github.com/gilsdav/ngx-translate-router) is extending [LocalizedRouter](https://github.com/gilsdav/ngx-translate-router/blob/bdac7ffc995f992163ade8b7ad952cca4fdf6774/projects/ngx-translate-router/src/lib/localized-router.ts) from the `Router` class, which was recently refactored in #48313 to use `inject` instead of constructor parameters. [Extending classes is not supported](https://github.com/angular/angular/blob/7ec97f31dff30c39792153bd92c65cce9c6fad58/docs/PUBLIC_API.md#extending-angular-classes) and constructors can change in patch versions, as they are not considered as public API.

**Comment by robertIsaac** [comment]
> [ngx-translate-router](https://github.com/gilsdav/ngx-translate-router) is extending [LocalizedRouter](https://github.com/gilsdav/ngx-translate-router/blob/bdac7ffc995f992163ade8b7ad952cca4fdf6774/projects/ngx-translate-router/src/lib/localized-router.ts) from the `Router` class, which was recently refactored in #48313 to use `inject` instead of constructor parameters. [Extending classes is not supported](https://github.com/angular/angular/blob/7ec97f31dff30c39792153bd92c65cce9c6fad58/docs/PUBLIC_API.md#extending-angular-classes) and constructors can change in patch versions, as they are not considered as public API.

Thank you for explaining the problem

Now the author will know what went wrong and will make it easier for him to fix it
