### ISSUE TITLE
installing @angular/localize broke jasmine/types

### ISSUE THREAD

**Issue by kondelik** [angular/angular#48434]
### Which @angular/* package(s) are the source of the bug?

localize

### Is this a regression?

Yes

### Description

When I install `@angular/localize` in newly created angular project, jasmine types (`describe`, `it`, `expect`, `afterAll` etc) are not recognized inside `*.spec.ts`:

To reproduce:
```powershell
ng new Angular15.net
cd Angular15.net
ng add @angular/localize
# code .
```
![image](https://user-images.githubusercontent.com/4945875/206856123-57807a85-1501-49c8-aaf6-743d55f9de18.png)
(these error messages are in czech - see below for english error messages)

### Please provide a link to a minimal reproduction of the bug

```powershell
ng new Angular15.net
cd Angular15.net
ng add @angular/localize
# code .
```

### Please provide the exception or error you saw

describe():
```true
Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha` and then add 'jest' or 'mocha' to the types field in your tsconfig.(2593)
```

it():
```true
Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha` and then add 'jest' or 'mocha' to the types field in your tsconfig.(2593)
```

expect():
```true
Cannot find name 'expect'.(2304)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.3
Node: 18.12.1
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 15.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.3
@angular-devkit/build-angular   15.0.3
@angular-devkit/core            15.0.3
@angular-devkit/schematics      15.0.3
@schematics/angular             15.0.3
rxjs                            7.5.7
typescript                      4.8.4
```

### Anything else?

`yarn add --dev @types/jasmine@4.3.0`: does not help.

`yarn test`: tests are executed successfully:
![image](https://user-images.githubusercontent.com/4945875/206856902-43b024a9-0bcd-4ee0-8ba2-62d619f9ce3d.png)

**Comment by kondelik** [comment]
Workaround:

open `tsconfig.json` and remove
```
 "types": [
      "@angular/localize"
    ]
```
open `tsconfig.app.json` and check if there is
```
```

**Comment by kondelik** [comment]
After discovering the cause, this feels like a duplicate of something, but I can't find any open issue about anything like `"type": []` in `tsconfig.json` is not overriden from `tsconfig.*.json`...

**Comment by kondelik** [comment]
Looking at PR #48502 - workaround right now is:

#### `main.ts`; add:
```
/// <reference types="@angular/localize" />
```

and remove every mention of 
```
types []"@angular/localize"
```
from `tsconfig.json` and `tsconfig.*.json`.

**Comment by alan-agius4** [comment]
"@angular/localize" types should only be removed from the root `tsconfig.json`.
