### ISSUE TITLE
Composing Angular 2 components with Angular 1 directives

### ISSUE THREAD

**Issue by varghesep** [angular/angular#4844]
Can Angular 1 directives work inside Angular 2 components and interact between each other? For example, use an MD directive like [md-autocomplete](https://material.angularjs.org/latest/api/directive/mdAutocomplete) inside an Angular 2 component?

In this snippet, **ProductListComponent** is a Angular2 component. **md-autocomplete** is an Angular1 component.

``` javascript
template: "<ProductListComponent><md-autocomplete><md-autocomplete></ProductListComponent>"
```

**Comment by mhevery** [comment]
yes see: http://angularjs.blogspot.com/2015/08/angular-1-and-angular-2-coexistence.html and https://github.com/angular/angular/blob/master/modules/playground/src/upgrade/index.ts
