### ISSUE TITLE
SSR: form module does not set name attribute to input elements

### ISSUE THREAD

**Issue by albanx** [angular/angular#48449]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

When creating a form using the FormBuilder, FormGroup, you set the form formControlName to every input. When you create a pure SSR app (disabling JS) the form submits fine, but the inputs won't be added to the request (get or POST) because the inputs lack of name attribute.
```
<select _ngcontent-sc151="" formcontrolname="contractType" class="select full ng-untouched ng-pristine ng-valid" value="sale"></select>`
```

Having the name tag autogenerated would add support for SSR full support on forms.

### Please provide the exception or error you saw

```true
none
```

### Anything else?

THis is more like a feature request than a bug, because by adding the name attribute manually it works as expected.

**Comment by pkozlowski-opensource** [comment]
I don't think that reflecting formcontrolname as the name attribute is the reliable way of getting a form that can be submitted as-is to the server:
* we can end up with duplicated names;
* we might have complex controls that are rendered as multiple input elements.

Generally speaking this is not the scenario we are supporting today, you might want to add required name attributes on your end.
