### ISSUE TITLE
RouteReuseStrategy does not update page title and meta tags on cached route

### ISSUE THREAD

**Issue by albanx** [angular/angular#48447]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I am not sure if this is a regression, but the issue is the following:
1. Enable RouteReuseStrategy for a given route 
2. Use the Title Service to set the pages title in the route that has route strategy enabled
3. Navigate to another route and set the title again
4. Go back to the Cached route and the title will not update

In the link https://angular-d9wjnd.stackblitz.io/catalog follow this steps:
1. go to Home page link, title is updated
2. click go to Catalog page (cached route) title is updated
3. go back to home page, title is updated
4. go again to Catalog page (cache kicks in) title is not updated, stays as homepage title

My work around at the moment is something like this in the retrive method:
```
    if ((cmp as any).componentRef.instance.refreshSeoTags) {
      (cmp as any).componentRef.instance.refreshSeoTags();
    }
```

### Please provide a link to a minimal reproduction of the bug

https://angular-d9wjnd.stackblitz.io/catalog

### Please provide the exception or error you saw

```true
No Exception
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.0
Node: 18.12.1
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 15.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0
@angular-devkit/build-angular   15.0.0
@angular-devkit/core            15.0.0
@angular-devkit/schematics      15.0.0
@nguniversal/builders           15.0.0
@nguniversal/express-engine     15.0.0
@schematics/angular             15.0.0
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by atscott** [comment]
This is working as expected. The component ref is saved and re-attached when using the `RouteReuseStrategy` rather than being recreated. `ngOnInit` will not run in this case.

**Comment by albanx** [comment]
But is still a bug, because the route restore does not restore the meta tags.

**Comment by atscott** [comment]
> But is still a bug, because the route restore does not restore the meta tags.

The router does not attempt to manage meta tags at the moment. Any bugs around this management would be application-specific, not a bug in the Angular router.
