### ISSUE TITLE
Angular 15 standalone: Can't bind to 'ngTemplateOutlet' since it isn't a known property of 'ng-container'

### ISSUE THREAD

**Issue by ttakennn** [angular/angular#48445]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

- **AccordionComponent** TS
<img width="455" alt="image" src="https://user-images.githubusercontent.com/20335987/207006840-1c787842-7274-4722-94d5-dd09d54f06ea.png">

- **AccordionComponent** HTML
<img width="326" alt="image" src="https://user-images.githubusercontent.com/20335987/207006948-dcfc82a6-3d14-4480-9a26-689d5ed35946.png">

- **MainComponent**
<img width="134" alt="image" src="https://user-images.githubusercontent.com/20335987/207009754-cb4c380e-110d-4da3-910d-555f3a37d5f0.png">

When I click the open button and see the error message below:

### Please provide the exception or error you saw

```true
accordion.component.html:7 NG0303: Can't bind to 'ngTemplateOutlet' since it isn't a known property of 'ng-container' (used in the 'AccordionComponent' component template).
1. If 'ng-container' is an Angular component and it has the 'ngTemplateOutlet' input, then verify that it is included in the '@Component.imports' of this component.
2. If 'ng-container' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@Component.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@Component.schemas' of this component.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.1
Node: 16.15.0
Package Manager: npm 8.12.1
OS: win32 x64

Angular: 15.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.1
@angular-devkit/build-angular   15.0.1
@angular-devkit/core            15.0.1
@angular-devkit/schematics      15.0.1
@schematics/angular             15.0.1
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

`AccordionComponent` is marked as standalone and does not import `NgTemplateOutlet`, hence it is not available.

**Comment by ttakennn** [comment]
Thanks, @JoostK
