### ISSUE TITLE
Recent change in compiler-cli breaks jest-preset-angular 

### ISSUE THREAD

**Issue by jbjhjm** [angular/angular#48448]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

I'm currently investigating an error that occurs in certain situations when running tests with jest-preset-angular and typescript 4.8. There are several issue reports over at jest-preset-angular, nrwl/nx and possibly others.

### Error description

In short, this code will break jest / jest-preset-angular, throwing `ReferenceError: anywhere_1 is not defined`, when running typescript 4.8.

```ts
import {InterfaceFromInterfaceOnlyModule } from './anywhere' ;
class X {
	@MyDecorator() test():InterfaceFromInterfaceOnlyModule { ... }
}
```

A reproduction is available at https://github.com/jbjhjm/jest28-bug .

The error occurs when following circumstances are given:

- use angular with typescript 4.8 (so ng 15) and jest with jest-preset-angular
- Import nothing but an interface or type from a module
- Use it on a method that is being decorated
- Have emitDecoratorMetadata enabled

It seems like response type of a decorated method somehow "bleeds" into compiled javascript, where it causes an error because the type-only module does not exist anymore, ending up in a ReferenceError.

### Origin of error

jest-preset-angular uses the downlevel_decorators_transform.ts from compiler-cli.
We managed to hunt the error down to a recent change in there.

https://github.com/angular/angular/pull/47167 modified that file in L565, replacing updateClassDeclaration by  createClassDeclaration. 

Here https://github.com/thymikee/jest-preset-angular/issues/1199#issuecomment-1345445251 , @n9niwas has shown a patch reverting that change to make it work as desired again, stating: "Idk for sure, but suspect that calling create* methods instead of update* makes TS program to forget information about whether a particular import is type-only or not."

@crisbeto , your insights might help here a lot.
I am not sure if downlevel_decorators_transform currently generates unexpected code, or if jest-preset-angular needs to update its own implementation to work correctly with the new code.
What's your estimation? Can you explain why `createClassDeclaration` is used now?

---

Related issues:

https://github.com/thymikee/jest-preset-angular/issues/1199
https://github.com/thymikee/jest-preset-angular/issues/1810
https://github.com/nrwl/nx/issues/10660

### Please provide a link to a minimal reproduction of the bug

https://github.com/jbjhjm/jest28-bug

### Please provide the exception or error you saw

```true
jest will throw `ReferenceError: xxx is not defined`
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.2
Node: 16.17.0
Package Manager: npm 8.15.0
OS: win32 x64

Angular: 15.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.2
@angular-devkit/build-angular   15.0.2
@angular-devkit/core            15.0.2
@angular-devkit/schematics      15.0.2
@schematics/angular             15.0.2
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by jbjhjm** [comment]
thanks @crisbeto . If it does not change or break anything on your side, do you think it's feasible to revert it to updateClassDeclaration? This should make jest-preset-angular work again with ng15/ ts 4.8.

**Comment by jbjhjm** [comment]
> Yeah, it should be fine to revert back to it, but ideally we would also have a unit test to ensure that it doesn't regress.

Great, I'll check if we can assist you with more specific input on expected / erroring compilation results.

**Comment by ctacquet** [comment]
Hey guys, do you have any news on this issue ?
We can't upgrade to Angular 15 because of this issue 😞

**Comment by jbjhjm** [comment]
thanks @crisbeto ! Much appreciated!
