### ISSUE TITLE
What gets inserted into DOM before ngOnInit of component

### ISSUE THREAD

**Issue by krp12345** [angular/angular#48451]
### Describe the problem that you experienced

I observed that Angular inserts certain parts of template into DOM **BEFORE** ngOnInit and **AFTER** constructor is invoked.
[Check this demo project](https://stackblitz.com/edit/angular-ivy-spwgln?file=src/app/app.component.html)

I put breakpoint on first line of ngOnInit and observed DOM from DevTools. 

I could see that there are two paragraph element(p tag : \<p\>) got loaded in DOM. 
The first paragraph element was loaded fully with its text content. While second was loaded with no content (means empty paragraph element: \<p\>\</p\>). 

So, it seems that: If there is a text content with interpolation (same as second paragram in my demo app) inside any template element then it does not loaded BEFORE ngOnInit. Am I correct?

### Describe what you were looking for in the documentation

I believe facts and rules about what gets loaded before invocation of NgOnInit should be documented.

### Describe what you want to experience that would fix the problem

Please let me know your thoughts. I can go through each template syntax and find observations for each syntax then paste observations over here and create a PR in angular docs at appropriate place.
 

### Provide any additional information here in as much as detail as you can

```true
I am using Angular version 12.
```

**Comment by atscott** [comment]
This isn't considered part of the public API and there shouldn't be expectations built on top of what's available in the DOM before `ngOnInit`.

**Comment by mlc-mlapis** [comment]
@atscott Sure, there are no expectations, but it still can be interesting to know for a deeper understanding of what's happening. 😄

**Comment by atscott** [comment]
@mlc-mlapis If it's just curiosity, you can look through the code base at how `RenderFlags` are used: https://github.com/angular/angular/blob/e362214924dbb784e5bd0efd96530134f8c91d32/packages/compiler/src/core.ts#L170-L184
There won't be anything beyond internal developer documentation about these implementation details though.

**Comment by krp12345** [comment]
@atscott "there shouldn't be expectations built on top of what's available in the DOM before ngOnInit" --> Why is it the case? What gets loaded at what time is crucial as it will give more predictability. Is not it? I want to understand "Should" part of the statement.

**Comment by atscott** [comment]
@krp12345 Because this isn't considered part of the public API, it could change with internal refactoring like what happened with the View Engine -> Ivy migration. This could break your application's assumptions.

**Comment by krp12345** [comment]
@atscott : Thanks, I got your point. I thought there will be a common specification which will be respected by ViewEngine, Ivy or other future engines that will come if any. 
What will happen if there is such specification? Why ViewEngine and Ivy does different things on DOM before ngOnInit? I just want to deeply understand this. I don't know much deeper on ViewEngine and Ivy. Any docs which I should read to understand more?

**Comment by krp12345** [comment]
@atscott : Should we put a note in docs from your comment "This isn't considered part of the public API and there shouldn't be expectations built on top of what's available in the DOM before ngOnInit."?
