### ISSUE TITLE
Offline documentation

### ISSUE THREAD

**Issue by MickL** [angular/angular#48455]
### Description

It would be great to be able to download the full documentation website for reading it offline. Unfortunately not everywhere in the world we have internet all the time.

There were issues of this topic already from 2018 and 2020, still it hasnt been resolved:
https://github.com/angular/angular/issues/27492

### Proposed solution

Add a download button to download the full built website archived

### Alternatives considered

Download the document repository from Github and build it manually

### Btw
In general I think it is an awful practice by Angular to close all issues due to inactivity. Inactivity doesnt mean the issue has been solved or no one is interested in it anymore! #27492 has been closed "for now" without any reason. Why not leave it open until it has been done? I made a feature request https://github.com/angular/angular/issues/18877 in 2017 that got 243 upvotes and has been close due to inactivity in 2021...

**Comment by jessicajaniuk** [comment]
The process for accessing docs offline is to clone the `angular/angular` repo or your fork of it. Then you can run the docs page locally by going into the `/aio` directory and running `yarn && yarn start`. This will install all the deps, build, and run them on your localhost.
