### ISSUE TITLE
Router fails to generate link for child route with parent route loader

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#4845]
When using the loader function on a route with child routes, the router link directive throws an exception when trying generate a link for the nested route. 

Example plunk: http://plnkr.co/edit/ViL0Jz9HIy8paccTa6Fs?p=preview

**Comment by btford** [comment]
:+1:

**Comment by btford** [comment]
This should be resolved now– I confirm that this problem is fixed in the plunkr when updating to Alpha 47.

If the issue persists, let me know and I'll reopen this. Thanks so much for all the help, @brandonroberts!
