### ISSUE TITLE
[Feature Request] Remove parent's auxiliary routes when navigating to child component

### ISSUE THREAD

**Issue by JasonMan34** [angular/angular#48450]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

Consider a route system:
```ts
const moduleRoutes = [{
  path: 'admin-panel',
  component: AdminPanelPage,
  children: [
    {
      path: 'users',
      component: ManageUsersPage,
    }
   // ... more children, aux routes
  ],
}];
```

If the current url is `http://localhost:4200/admin-panel/(tab:categories)` and we want to switch to `http://localhost:4200/admin-panel/users` there is no way to do that with a single router call or a single [routerLink] directive  
```ts
// Current url is '/admin-panel/(tab:categories)'
this.router.navigate(['/admin-panel/users'], { outlets: { tab: null } });
// url is now `/admin-panel/(users//tab:categories/)
```

It is solvable by doing this ([Relevant stackOverflow question](https://stackoverflow.com/a/74637743)):
```ts
// Current url is '/admin-panel/(tab:categories)'
this.router.navigate(['/admin-panel'], { outlets: { tab: null } }).then(() => {
  this.router.navigate(['/admin-panel/users']);
  // url is now `/admin-panel/users
});
```

However, even this fails if `/admin-panel` has a default tab, e.g.:
```ts
const moduleRoutes = [{
  path: 'admin-panel',
  component: AdminPanelPage,
  children: [
    {
      path: '',
      redirectTo: `/admin-panel/(tab:categories/)`,
      pathMatch: 'full',
    },
    {
      path: 'users',
      component: ManageUsersPage,
    }
   // ... more children, aux routes
  ],
}];
```

### Proposed solution

Add a field in the commands sent to `router.navigate` and [routerLink] directive to modify outlets of the current route

```ts
this.router.navigate(['/admin-panel/users'], { currentOutlets: { tab: null } });
```

Alternatively, if it's difficult to know where the current navigation is being made from, add an option to remove all outlets from all routes in the URL

```ts
this.router.navigate(['/admin-panel/users'], { removeOutlets: true });
```

### Alternatives considered

1. Double navigate as stated in the description - However it fails with a default auxiliary route
2. Add a default redirect in the child component to an absolute URL to remove all auxiliary routes from the url - However this only works if we don't navigate WITH an outlet to the target route

**Comment by atscott** [comment]
There have been requests similar to this in the past, but named outlets are not very common and this is an even less common task within that. There are a lot of existing ways to accomplish what you're looking for so these features would be best built out in a community library. 

Here's a stackblitz that accomplishes what you want by manipulating the `UrlTree`/`UrlSegmentGroup` directly: https://stackblitz.com/edit/close-outlet-from-anywhere-ohkhwc
