### ISSUE TITLE
Range Error when loading Angular2

### ISSUE THREAD

**Issue by cbalit** [angular/angular#4847]
Hi, I've just update my projet from alpha-37 to alpha-44. With the quickstart instructions, i get the following error just by loading angular2

Uncaught RangeError: Maximum call stack size exceeded angular2.dev.js:1068   
obj.addEventListener angular2.dev.js:168 
Zone.addEventListener angular2.dev.js:1092 
obj.addEventListenerangular2.dev.js:168 
Zone.addEventListener......

If i try to see what's happen, i can notice an infinite loop between obj.addEventListener and Zone.addEventListener with the following arguments

- eventName: "open"
- handler: function zoneBoundFn() {
- useCapturing: false

Am i doing something wrong ?

Cyril

**Comment by pkozlowski-opensource** [comment]
> Am i doing something wrong ?

Hard to say just based on the info provided... Could you try to reproduce this problem in a plunker? You can fork one from the documentation site. Thnx!

**Comment by cbalit** [comment]
Ok i got it. The error cames from a livereload behavior provide by a grunt-express task. 
Thanks @pkozlowski-opensource

**Comment by guilhermevrs** [comment]
Hi @cbalit,
Could you please explain what you did to solve this problem?
Because I am having the same issue but my architecture uses gulp with browser-sync and superstatic (not grunt-express).

Thanks

**Comment by cbalit** [comment]
hi @guilhermevrs. In fact i just set the livereload property of the grunt-express config to false.

**Comment by guilhermevrs** [comment]
Hi @cbalit.
I don't think this is my case, I tried to do the same thing with browser-sync, but the result is always the same.
Thanks anyway

**Comment by bvaughn** [comment]
I'm seeing this same issue on the static/dist version of my app- so live reload is definitely not a cause.

**Comment by zoechi** [comment]
New issue created in #7930
