### ISSUE TITLE
Bugged named outlet with lazy-loaded module & empty parent route path 

### ISSUE THREAD

**Issue by juliancarrivick** [angular/angular#48472]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

This is related to an issue that has been extensively discussed in the community for a long time and been attempted to be fixed multiple times with named outlets in lazy loaded routes/parent routes with an empty path:
- https://github.com/angular/angular/issues/10726
- https://github.com/angular/angular/issues/10981 
- https://github.com/angular/angular/issues/13807 
- https://stackoverflow.com/questions/56114291/accessing-children-in-auxiliary-routing-angular
- https://stackoverflow.com/questions/42022382/angular2-routing-on-lazy-loaded-module-with-multiple-named-outlets/42023015
- https://github.com/angular/angular/pull/25483
- https://github.com/angular/angular/pull/30444
- https://github.com/angular/angular/pull/32688
- Alleged fix in 11.0.6: https://github.com/angular/angular/pull/40029

I think this is slightly different behaviour than previously reported: when navigating to the named route outlet the first time the route activates successfully and everything seems happy. However if you do it again the router nests another named route in the URL instead of recognising it is already active. e.g. (from stackblitz) `/shell/content` -> `/shell/(content//help:content)` -> `/shell/(/(content//help:content)//help:content)` etc. Additionally, navigating to `[routerLink]="[{outlets: {help: null}}]"` doesn't clear the named router outlet.

There is a workaround if you make the parent of the named outlet have a non-empty path (this is the previously advertised workaround), but this is not unfortunately a satisfactory solution for me. I don't have time right now to bisect and determine when it regressed but will endeaver to do this in the next few days.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-dsermn?file=src/app/shell/shell.module.ts

### Please provide the exception or error you saw

```true
As described above.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
(Locally I'm running this, but it is still present on 15.0.3 as evidenced by the stackblitz repo)

Angular CLI: 14.2.9
Node: 16.18.1
Package Manager: npm 8.19.2
OS: linux x64

Angular: 14.2.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, upgrade

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.9
@angular-devkit/build-angular   14.2.9
@angular-devkit/core            14.2.9
@angular-devkit/schematics      14.2.9
@angular/cdk                    14.2.7
@angular/cli                    14.2.9
@angular/material               14.2.7
@schematics/angular             14.2.9
rxjs                            7.5.7
typescript                      4.7.4
```

### Anything else?

Present on at least Angular 14 & 15.

**Comment by atscott** [comment]
This is actually a different issue than the ones you have linked to. The ones you linked are related to the route matching algorithm but the problem here is `UrlTree` creation - you can see that the `routerLink` `href` already has the problem with creating crazy URLs before you attempt navigation. 

With that, this issue is (partially) fixed by https://github.com/angular/angular/pull/45877. Unfortunately, there wasn't enough time for me to land it as a breaking change in v15 by swapping out the implementation of `router.createUrlTree` for this fixed behavior. In short, the current behavior is super round-about and is incapable of creating the correct result in many scenarios. I plan to include `createUrlTreeFromSnapshot` as a breaking change to `router.createUrlTree` in v16.

**Comment by juliancarrivick** [comment]
Great, thanks @atscott, it looks like you've been doing lots of great work in this space! :slightly_smiling_face: Shame it didn't make it into v15, but I'm sure I'll blink and v16 will be out!

When you say it's been "partially" fixed, are there any particular scenarios where you know it's broken still?

**Comment by atscott** [comment]
By "partially" I mean that it isn't the default for `router.createUrlTree` (and so it's not fixed for `routerLink`). If it were, you wouldn't have had to file this bug in the first place :)

**Comment by juliancarrivick** [comment]
Ah, so this is just an issue with the generation of the link, not with the routing specifically.

So, if I understand correctly, I should be able to manually craft the URL, or use the new `createUrlTreeFromSnapshot` function to generate the URLTree which I would be able to use directly as a workaround?

**Comment by juliancarrivick** [comment]
Yep, I confirmed this works 😄 

I had to do the navigation on the click event (and preventDefault the event), but it seems to work! I created a helper directive to encapsulate this - hope it helps someone else!
``` typescript
import { Directive, HostBinding, HostListener, Input, OnDestroy } from '@angular/core';
import { ActivatedRoute, createUrlTreeFromSnapshot, NavigationEnd, Router, UrlTree } from '@angular/router';
import { BehaviorSubject, combineLatest, filter, map, startWith, Subscription } from 'rxjs';

@Directive({
    standalone: true,
    selector: '[appHelpRouterLink]',
}) export class HelpRouterLinkDirective implements OnDestroy {
    @Input('appHelpRouterLink') public set helpCommands(commands: unknown[] | null) {
        this.helpCommands$.next(commands);
    }
    private helpCommands$ = new BehaviorSubject<unknown[] | null>(null);

    @HostBinding('href') public href?: string;
    private urlTree?: UrlTree;

    private subscription: Subscription;

    public constructor(
        private router: Router,
        route: ActivatedRoute,
    ) {
        const otherNavigations = this.router.events.pipe(
            filter((e): e is NavigationEnd => e instanceof NavigationEnd),
            map(() => route.snapshot),
            startWith(route.snapshot),
            filter(r => r.outlet !== 'help'),
        );
        this.subscription = combineLatest([
            otherNavigations,
            this.helpCommands$,
        ]).subscribe(([snapshot, commands]) => {
            this.urlTree = createUrlTreeFromSnapshot(snapshot, [{ outlets: { help: commands } }]);
            this.href = this.router.serializeUrl(this.urlTree);
        });
    }

    public ngOnDestroy(): void {
        this.subscription.unsubscribe();
    }

    @HostListener('click', ['$event'])
    public navigate(event: Event) {
        if (!this.urlTree) {
            return;
        }

        event.preventDefault();
        this.router.navigateByUrl(this.urlTree);
    }
}
```
