### ISSUE TITLE
[Alpha 44][Http] Request is sent for every subscribe call.

### ISSUE THREAD

**Issue by binarious** [angular/angular#4848]
When I subscribe multiple times to an Observable created via Http, the request is sent more than once:

```js
let rx = http.get('api/people.json');
rx.subscribe((res) => {});
rx.subscribe((res) => {});
rx.subscribe((res) => {});
// api/people.json is requested 3x (or 6x with browser preflight on complex requests)
```

[Plunkr](http://plnkr.co/edit/JWoa4gyFnvC6YRVhuqf7?p=preview)

Is this the intended behaviour? I'd like to be able to pass the Observable to other services letting them subscribe to the request, too.

**Comment by ericmartinezr** [comment]
Hey @binarious , according to [Observable documentation](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/observable.md) is the inteded behavior. Is push-based, so everytime you `subscribe` to it, it will create a new request.

If you want to pass the same request to different services you can use `share()` (just saw this operator in AngularConnect's talk of Ben Lesh).

So just change this 
```
let rx = http.get('api/people.json');
```
to this
```
let rx = http.get('api/people.json').share();
```
and you'll have Nth subscribers sharing the same result, which looks awesome.

Here's a [plnkr](http://plnkr.co/edit/3mlT5q?p=preview) with an example. Check the network tab and the console.

I hope it helps.

**Comment by binarious** [comment]
Hey @ericmartinezr, great, thanks a lot for the clarification and the example!
