### ISSUE TITLE
Navigation gets cancelled and canDeactivate gets invoked twice when router.navigate is used for redirection

### ISSUE THREAD

**Issue by srirark-cat** [angular/angular#48499]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I am not sure if it is a regression bug. My issue is described below:

I am using the `canDeactivate` guard to check if the page has any unsaved changes and showing a popup asking the user to confirm navigation if there are unsaved changes. I am getting the popup only once when the redirection happens from the left navigation menu. But I have a scenario to redirect to the home page when the cancel button is clicked on the page and I am using `router.navigate` to move to the home page. In this case I am getting the confirm popup twice. I enabled tracing in routes and captured the log, I see the following logs:
<img width="1686" alt="image" src="https://user-images.githubusercontent.com/97504109/207739531-3a9ba3c9-6ab6-4d36-a32f-daa21e878ccd.png">

The navigation id changes after `ActivationStart` and the event gets cancelled. It initiates the `NavigationStart` event again and this time it works.

I tried to reproduce it with minimal setup on stackblitz but couldn't reproduce it yet.

Any idea about why the route guard is invoked twice and what causes the navigation id to change when the navigation is in progress?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.4
Node: 16.16.0
Package Manager: yarn 1.22.19
OS: darwin x64

Angular: 13.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.4
@angular-devkit/build-angular   13.3.4
@angular-devkit/core            13.3.4
@angular-devkit/schematics      13.3.4
@angular/cdk                    12.2.13
@angular/cli                    13.3.4
@angular/elements               13.3.5
@angular/flex-layout            12.0.0-beta.35
@angular/language-service       13.3.5
@angular/localize               13.3.5
@angular/material               12.2.13
@angular/pwa                    0.1102.19
@schematics/angular             13.3.4
ng-packagr                      13.3.1
rxjs                            7.5.5
typescript                      4.5.5
```

**Comment by atscott** [comment]
There’s no runnable reproduction here but based on your description, this is working as expected and documented. Triggering a new navigation cancels the current navigation. The navigation to the home page is also deactivating your component so the deactivation has to run for that navigation as well. You’ll need to add a condition to your guard to handle this case and not show the prompt again.

**Comment by srirark-cat** [comment]
@atscott We are not triggering a new navigation and not sure how it is getting triggered. Do you know if there could be any other reasons why the navigation id changed?

**Comment by atscott** [comment]
Your report states that `router.navigate is used for redirection`. This _is_ a new navigation and would be the cause for the navigation id change.

**Comment by srirark-cat** [comment]
@atscott I am sorry if it was not clear earlier, `router.navigate` is the one that is triggering the navigation and after that the `canDeactivate` guard is invoked twice. The navigation id changes in between when the events from this navigation are still in progress.

**Comment by atscott** [comment]
Without a reproduction, I can't say either what's causing the other navigation. But from the Router's perspective, there is nothing that would trigger a navigation during the activation phase. Likely one of the components you're activating is triggering a new navigation.
