### ISSUE TITLE
trackBy is not ergonomic to use

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#48503]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Adding proper `trackBy` to `ngFor` loops is one of the most important perf optimizations one can make (here is a [stackblitz](https://stackblitz.com/edit/angular-standalone-ks9pkt?file=src%2Fmain.ts) illustrating the point).

Yet, adding `trackBy` is cumbersome in practice:
* Angular template syntax doesn't support arrow functions in expressions so the `trackBy` function needs to be declared on a component instance, "far away" from the usage site;
* the [signature](https://angular.io/api/core/TrackByFunction) of the `trackBy` function is `(index: number, item: T)` - index is the first argument while most of the time we want to do sth with an item; on top of this TS will complain about unused index argument (!).

Opening this issue so we can explore different ways of writing `trackBy` conditions.

**Comment by pkozlowski-opensource** [comment]
Related: #12969

**Comment by myrddraall** [comment]
This doesn't address most of the issue but as far as: 
"on top of this TS will complain about unused index argument (!)"

if you name the params with an underscore at the beginning typescript will not complain about it being unused

```typescript
class MyComponent{

  public function trackBy(_index: number, item: T){
    // ...
  }
}

```

**Comment by joshuamorony** [comment]
Without any respect to the feasibility of the approaches (I have seen the current limitations in the related issue), the "ideal" way that I would want for trackBy to work is:

1) Automatically use the `id` property for the trackBy without specifying it, and create a warning in the console if no `id` is present (basically what React is doing with key properties). Almost every time I create a trackBy and most examples I see from other people it is generally an `id` property being specified in the trackBy.

2) To manually specify a trackBy I would ideally want something like:

```html
<div *ngFor="let item of items; trackBy: item.plu">
```

But I understand that syntax isn't actually feasible at the moment, that's just intuitively how I would want it to work.

**Comment by aksdevac** [comment]
+1 for arrow function support, also it would be nice if template can support template string.
```js
`string text ${expression} string text`
```

**Comment by misha98857** [comment]
My point of view is how it can be done without supporting arrow function in template.
Implement reserved function like "trackByProp()".

Example for some cases:
```typescript
<div *ngFor="let item of items; trackBy: trackByProp('id')">
```
or for nested object
```typescript
<div *ngFor="let item of items; trackBy: trackByProp('contact.id')">
```
Also backward support current realization
```typescript
<div *ngFor="let item of items; trackBy: myFunction">
```

**Comment by misha98857** [comment]
Another idea add "key" like React "key" prop.

For example:
```typescript
<div *ngFor="let item of items" ngForKey="item.id">
```
Also backward support current realization, but will throw error when two type of trackBy was added.

**Comment by hakimio** [comment]
Here is a simple `trackByKey` implementation for those who would like to use it now:

`track-by-key.directive.ts`
```ts
import {Directive, Host, Input} from '@angular/core';
import {NgForOf} from '@angular/common';

@Directive({
    selector: '[ngForTrackByKey]',
    standalone: true
})
export class TrackByKeyDirective<T> {

    @Input('ngForTrackByKey')
    key: string;

    constructor(
        @Host()
        private ngFor: NgForOf<T>
    ) {
        this.ngFor.ngForTrackBy = (index: number, item: T) => item[this.key];
    }

}
```
Usage example:
```html
<div
	*ngFor="let item of items; trackByKey: 'id'"
>
	{{item.name}}
</div>
```

[Gist](https://gist.github.com/hakimio/bc2f89910960073523da37abbbb09f5c)

**Comment by hakimio** [comment]
@joshuamorony you can find a more advanced version which fulfills your requirements on [medium](https://medium.com/gitconnected/trackid-infixing-trackby-capabilities-to-ngfor-in-a-centralised-way-across-your-angular-f1286f703469).

**Comment by JeanMeche** [comment]
In #48696 @pkozlowski-opensource raised a concern that some minifiers could rename class field names thus breaking the tracking when passing only a string.  

Wouldn't that also apply to your directive @hakimio ?

**Comment by hakimio** [comment]
@JeanMeche I am not a bundler/minifier expert, but in my case input name is provided in the decorator (`@Input('ngForTrackByKey')`) and whether you name the property `key`, `k` or `foo` makes no difference. Anyway, it would be interesting to know which minifiers exactly @pkozlowski-opensource is referring to and what output they produce. I've never heard about minifiers causing issues with input names. Is Google `closure` that "advanced" minifier?

**Comment by de-don** [comment]
Maybe the better way to use some input like in `react` and `vue`?
```
<div *ngFor="let item of items" [ngKey]="item.key">
</div>
```

**Comment by pkozlowski-opensource** [comment]
Note: the new @for control flow makes it much easier to specify the expression that computes tracking keys.
