### ISSUE TITLE
Add type casting in the template for a Reactive Form

### ISSUE THREAD

**Issue by robvaneck** [angular/angular#48516]
### Which @angular/* package(s) are relevant/related to the feature request?

14

### Description

I'm always struggling with angular reactive forms in the HTML, because the compiler gives me 
```Property 'controls' does not exist on type 'AbstractControl```

```
        <form [formGroup]="form" novalidate>
            <div formArrayName="arr">
<!-- i already cast formArray, to solve the first issue of AbstractControl```
                <ng-container *ngFor="let formGroup of formArray.controls; let i = index">
                    <div [formGroupName]="i" class="section">
                        <h3>{{ apps[i].name }}</h3>
                        <ng-container *ngFor="let field of fields[i]; let j = index">
                            <div class="form-group">
                                <div class="w-40">
                                    <label>
                                        {{ 'setup.number_of' | translate }}
                                        {{ fields[i][j].label }}
                                    </label>
                                </div>
                                <div class="w-60">
<!-- but inside my formGroup loop... i have to use $any.... else i will get the AbstractControl issue -->
                                    <opt-number-input [control]="$any(formGroup).controls[fields[i][j].name]"></opt-number-input>
                                    <opt-form-errors [control]="$any(formGroup).controls[fields[i][j].name]"></opt-form-errors>
                                </div>
                            </div>
                        </ng-container>
                    </div>
                </ng-container>
            </div>
        </form>

```

I dont want to use ```formControlName```, because then I have to implement ControlValueAccessor to each wrapper component that just holds and ```input``` ... so thats why I use ```[control]```

I cant use a ```get``` inside the formGroup loop, because you cant pass variables to a getter.

I also cant use ```['controls']``` as work around, because this will give me strict template check errors

### Proposed solution

A solution would be if we could cast variables from AbstractControl to FormGroup, FormArray in the template, eg.

```<ng-container *ngFor="let formGroup of $formArray(form.controls.arr).controls; let i = index">```

```<opt-form-errors [control]="$formGroup(formGroup).controls[fields[i][j].name]"></opt-form-errors>```

### Alternatives considered

Reactive Forms type checking in the template, should use FormArray, FormGroup, FormContorl. And not use AbstractControl.

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
