### ISSUE TITLE
Comparison operator not working correctly with getRawValue()

### ISSUE THREAD

**Issue by iusamaaziz** [angular/angular#48514]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

Hello Angular, I've these Person and address classes:

```
export class Person {
  id: FormControl<number>;
  name: FormControl<string>;

  addressList: FormArray<FormGroup<Address>>;
}

export class Address {
  id: FormControl<number>;
  name: FormControl<string>;
}
```
I'm initializing `Person` here:
```
ngOnInit(): void {
    // initialize person
    this.person = this.fb.group<Person>({
      id: new FormControl<number>(1, { nonNullable: true }),
      name: new FormControl<string>('Usama', { nonNullable: true }),

      // initialize addressList
      addressList: this.fb.array<FormGroup<Address>>([
        this.fb.group<Address>({
          id: new FormControl<number>(1, { nonNullable: true }),
          name: new FormControl<string>('Okara', { nonNullable: true }),
        }),

        this.fb.group<Address>({
          id: new FormControl<number>(2, { nonNullable: true }),
          name: new FormControl<string>('Lahore', { nonNullable: true }),
        }),
      ]),
    });

    this. Filter();
  }
```
Please check the below code with comments
```
console.log(this.person.getRawValue() == this.person.getRawValue()); // returns false.

```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-htnd3l?file=src/app/app.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.7
Node: 18.12.1 (Unsupported)
Package Manager: npm 8.19.2
OS: win32 x64

 

Angular: 14.2.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

 

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1402.7
@angular-devkit/build-angular      14.2.7
@angular-devkit/core               14.2.7
@angular-devkit/schematics         14.2.7
@angular/cdk                       14.2.6
@angular/cli                       14.2.7
@angular/material                  14.2.6
@angular/material-moment-adapter   14.2.6
@schematics/angular                14.2.7
rxjs                               7.5.4
typescript                         4.8.4
```

**Comment by sOoN92** [comment]
Hello,
I think that your issue is not related to getRawValue() method.

You are trying to compare two objects with the `==` operator; this will always get you **false** as result.

If you want to compare two objects, you should try to stringify first and then compare them like this:
```javascript
yourFunction(obj1,obj2) {
    return JSON.stringify(obj1) == JSON.stringify(obj2);
}
```
Or you can use lodash isEqual method to compare objects, like so:
```javascript
import { isEqual } from 'lodash-es'
....
yourFunction(obj1, obj2) {
   return isEqual(obj1, obj2);
}
```

**Comment by iusamaaziz** [comment]
I consider the issue is with getRawValue() because the same comparison works fine when using like this?
`this.person.value == this.person.value; // returns true`

Also we have to use rawValue in some other provided functions. For example, indexOf would return -1 in this case:
`this.person.getRawValue().addressList.indexOf(this.person.controls.addressList.controls[0].getRawValue()`

and isEqual function won't help here, similar issues with `find` `lastIndexOf` `findIndex`

**Comment by sOoN92** [comment]
It might be some issue regarding the `getRawValue` return object, but I still don't understand why checking for object equality instead of using an object property, like the id

```javascript
 filter() {
     this.person.getRawValue().addressList.findIndex(
        (val) => val.id == this.person.controls.addressList.controls[1].getRawValue().id);
  }
```

**Comment by Olster** [comment]
> I consider the issue is with getRawValue() because the same comparison works fine when using like this?
> `this.person.value == this.person.value; // returns true`

In the example above you are comparing an object to itself, so it's `true`.
Simplified:
```ts
const obj = {
    a: 'foo',
    b: 'bar'
};

const res: boolean = obj === obj;
console.log(res); // true
```

`getRawValue()` always creates a new object, so reference comparison will alway return true.
Very simplified example:
```ts
function getRawValue() {
    return {
        a: 'foo',
        b: 'bar',
    };
}

const res: boolean = getRawValue() === getRawValue();
console.log(res); // false
```

As @sOoN92 mentioned, you should either compare the IDs or if you need to compare the whole object, use deep equality function from the library of your choice.
