### ISSUE TITLE
Setting variable value from UntypedFormControl Element value creates a pointer (two way binding) for Arrays.

### ISSUE THREAD

**Issue by Gnyblast** [angular/angular#48523]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

I'm having the class variable declaration for an array object as below:
```
public clients: number[] = []
```

then in the `contructor` of the component I'm passing an `UntypedFormGroup` then in the `ngOnInit` setting this `clients` variable value from the form as below:
```
ngOnInit(): void {
    this.clients = this.form.controls.clients.value
```

`clients` variable is also bound to a `select` element with `ngModel` two way binding
```
<mat-select multiple [(ngModel)]="clients">
    <mat-option *ngFor="let client of clients" [value]="client">
        {{client}}
    </mat-option>
</mat-select>
```
I use this `select` element to remove items from `clients` array and another input element push new item to this `clients` array
```
public setNewClient(client: MatAutocompleteSelectedEvent): void {
    this.clients.push(client.option.value)
    this.clientSeachInput = ""
    this.setClientAutoCompleteEmpty()
}
```

Problem starts here: Whenever I change the value of `clients` variable it directly gets reflected to 'this.form.controls.clients.value` without calling any set command for it.

But if I use the below code on `ngOnInit`
```
ngOnInit(): void {
    this.clients = new Array().concat(this.form.controls.clients.value)
```

Everything works well and breaks the two way binding of this `clients` variable to the `this.form.controls.clients.value` which is actually makes no-sense to have there a pointer binding.

### Please provide a link to a minimal reproduction of the bug

It's my local development environment.

### Please provide the exception or error you saw

```true
There is not exception it's a functional bug.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.7
Node: 16.18.1
Package Manager: npm 8.19.2 
OS: linux x64

Angular: 14.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.3
@angular-devkit/build-angular   14.2.3
@angular-devkit/core            14.2.3
@angular-devkit/schematics      14.0.7
@angular/cli                    14.0.7
@angular/fire                   7.4.1
@angular/flex-layout            14.0.0-beta.40
@angular/material               14.2.2
@schematics/angular             14.0.7
rxjs                            7.5.6
typescript                      4.7.4
```

**Comment by JeanMeche** [comment]
An array, like every other object is passed by reference. I don't understand why you would expect something else ?

**Comment by Gnyblast** [comment]
> An array, like every other object is passed by reference. I don't understand why you would expect something else ?

Ohh... I wasn't know that object as passed by reference instead of value in javascript. Then this is an expected behaviour. Sorry for that closing the ticket.
