### ISSUE TITLE
Template rendering error handling

### ISSUE THREAD

**Issue by jchapelle** [angular/angular#48528]
### Which @angular/* package(s) are relevant/related to the feature request?

common, core

### Description

It would be very useful to be able to catch html/view rendering issue via hook lifecycle method.
This would allow to react on unexpected issue without breaking the component or the whole app.
This request is for an equivalent to React 'componentDidCatch' or 'getDerivedStateFromError' hooks.

### Proposed solution

Add a 'ngOnViewError' hook lifecycle method to catch rendering issue.

### Alternatives considered

Not applicable

**Comment by JoostK** [comment]
This is being tracked in #18509.
