### ISSUE TITLE
Changes of files are not clear

### ISSUE THREAD

**Issue by tanb33r** [angular/angular#48536]
### Which @angular/* package(s) are relevant/related to the feature request?

angular.io/start/

### Description

In each step, changes in files are not precise, and one might miss some changes,
Also, other lines are hidden, so it's unclear whether I should remove other lines.

### Proposed solution

Highlight the line changes in each file

### Alternatives considered

GitHub Repos of all stages

**Comment by bob-watson** [comment]
Thanks for the feedback.
We're in the process of updating our tutorials and we'll consider this suggestion.
