### ISSUE TITLE
Events: Using the wrong syntax fails silently

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#4854]
```html
<foo (open)="onOpen"></foo>
```

Fails silently.

```html
<foo (open)="onOpen($event)"></foo>
```

Works.

I'd actually prefer the former working as sugar, but at least an error would be nice.

**Comment by matanlurey** [comment]
The same goes for

```html
[(visible)]="visible"
```

versus

```html
([visible])="visible"
```

**Comment by mhevery** [comment]
I am not sure how we could detect that? Both are valid statements? and it could have side effects. I think thin is won't fix.
