### ISSUE TITLE
Locally debugging unit tests on linux prevents node inspection

### ISSUE THREAD

**Issue by tbondwilkinson** [angular/angular#48557]
### Which @angular/* package(s) are the source of the bug?

bazel

### Is this a regression?

No

### Description

Running tests in debug mode:

```
yarn bazel test //packages/common/test:test --config=debug
```

On linux results in a node environment that is improperly sandboxed by bazel.

### Anything else?

For config=debug, --spawn_strategy=local must be used instead.

**Comment by josephperrott** [comment]
This is no longer an issue.
