### ISSUE TITLE
Race condition in two way databinding can corrupt data

### ISSUE THREAD

**Issue by endash** [angular/angular#4855]
This was pointed out in the gitter by @henriquefm, with the plunker http://plnkr.co/edit/dZMnYHBkL52WtwJbWGJ8?p=preview as a reference. It's the worst sort of heisenbug.

Behaviour:

Very occasionally on desktop, much more often on mobile, clicking on a hero, changing their name, and then clicking on another hero will result in the second hero's name being replaced by the first hero's name.

Reproduction:

Open the plunker. Click "Mr. Nice." Add "Foo" to make it "Mr. Nice Foo." Click "Narco."

Very, very rarely "Narco" will instantaneously change to "Mr. Nice Foo." It could take dozens of reloads on my 2.6ghz/i7 to reproduce. Others in the room reported consistent, immediate reproduction on mobile.

See video attached at the gitter (github doesn't support attaching videos currently): https://files.gitter.im/angular/angular/dMAv/MrNiceFooBug.mov

I reproduced in Chrome 46. With 2.6Ghz/i7 I'd say reproduction rate was 1 attempt out of 30-40. @henriquefm reports better than 1-in-2, with a 2.4Ghz Core 2 Duo. @diadistis reports lack of reproduction on a 3.4Ghz/i7, and 100% reproduction on an HTC M8 (2.3Ghz)

**Comment by henriquefm** [comment]
If I use `stress` to force 100% of CPU load, sometimes I can see it changing. When I click on "Narco", the details section changes to "Narco details!" and a fraction of a second later it changes to "Mr. Nice Foo details!". This has never happened without forcing 100% CPU load.

**Comment by henriquefm** [comment]
I am not reproducing this anymore with 2.0.0-alpha.52. I tried it with `stress` in my laptop and on mobile.
Plunker with Angular 2.0.0-alpha.52: http://plnkr.co/edit/ND6escBz9A9Wh9KU5bhO?p=preview
I can't say if it is solved or simply harder to reproduce.

**Comment by vicb** [comment]
What about closing this issue and re-open if the bug surfaces again ?
