### ISSUE TITLE
FormControl<T> where T happens to be an object with a "value" property messes things up

### ISSUE THREAD

**Issue by bojidaryovchev** [angular/angular#48550]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

please check the codesandbox, basically the problem is that when we declare a FormControl\<T\> and T is an object which has a property called "value" it messes up the typings

### Please provide a link to a minimal reproduction of the bug

https://codesandbox.io/s/eager-blackburn-58gk3h?file=/src/app/app.component.ts

**Comment by alxhub** [comment]
This is unfortunately a known limitation of the forms typings. The constructor API of `FormControl` with its many calling patterns was designed before strict typings, and it just can't be expressed well.

In cases like this where the "flexible" object types don't result in good type inference, I recommend passing explicitly defined controls to avoid any ambiguity:

```typescript
const f = this.fb.group({
  a: this.fb.control<V['a']>(null, []),
  b: this.fb.control<V['b']>(null, []),
});
```

**Comment by alxhub** [comment]
(closing as this is a TypeScript limitation that we can't really control)
