### ISSUE TITLE
Elements bound to reactive form controls not updating disabled state correctly

### ISSUE THREAD

**Issue by jannispl** [angular/angular#48561]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

In my application, I sometimes take advantage of the principle of immutability by creating fresh `FormGroup`s whenever I retrieve new data from my back-end API. This guarantees a predictable state (regarding `dirty`, Validation etc.), without having to imperatively clear any previous state modifications.

Doing this I encountered what seems to be an issue propagating the `disabled` state of the `FormGroup` to the input elements when I swap out the `[formGroup]` binding for a new instance. I noticed that when passing a new instance of a `FormGroup` that is enabled, while the previously bound instance is enabled, my form elements would remain in the disabled state.

Furthermore, I was able to work around this problem by forcing Angular to re-create the relevant form elements in the DOM (in the Stackblitz this is what I do with `asyncFormWithNull$`). This confirms my theory that any updates to the `[formGroup]` binding are not propagated correctly for elements already present in the DOM.

To reproduce the bug in the Stackblitz, first use the button 'Disabled form' to swap out the `[formGroup]` binding for a disabled form group, and then swap back to 'Enabled form'.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-2cfeoj

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular/animations
14.2.12

@angular/cdk
14.2.7

@angular/common
14.2.12

@angular/compiler
14.2.12

@angular/core
14.2.12

@angular/forms
14.2.12

@angular/material
14.2.7

@angular/platform-browser
14.2.12

@angular/platform-browser-dynamic
14.2.12

@angular/router
14.2.12
```

**Comment by kbrilla** [comment]
Hey this is fixed in 15.0.0 with PR: #47576 issue: #35309
15.0.0 (2022-11-16)
setDisabledState will always be called when a ControlValueAccessor is attached. You can opt-out with FormsModule.withConfig or ReactiveFormsModule.withConfig.

**Comment by jannispl** [comment]
> Hey this is fixed in 15.0.0 with PR: #47576 issue: #35309 15.0.0 (2022-11-16) setDisabledState will always be called when a ControlValueAccessor is attached. You can opt-out with FormsModule.withConfig or ReactiveFormsModule.withConfig.

That's good news! I can confirm after updating Stackblitz to v15 the issue is resolved.

**Comment by jannispl** [comment]
Actually, thinking about it, I might be stuck on v14 for a while due to flex-layout being deprecated - I don't know much about the Angular release process, but I would be in favor of a backport for v14.

**Comment by JoostK** [comment]
That change was breaking and can't be backported, plus Angular 14 is LTS and only receiving security related patches. There is no reason to stick to Angular 14 just because of the deprecation of flex-layout; that is still available for Angular 15 as well.
