### ISSUE TITLE
Reusing i18n translations from libraries

### ISSUE THREAD

**Issue by Noeldeveloper** [angular/angular#48562]
### Which @angular/* package(s) are relevant/related to the feature request?

localize

### Description

Nowadays, module federation and microfrontend are being more present. They requires new points of view. In terms of translations, it's possible that one library could be used in some microfrontend applications. Most of cases, from an application, we need to choose if responsability of translations is library or application.

Actually, angular libraries can't extract translations from themselves. Also, we would have many duplicated translations in each application that consumes that library.

I was doing some tests, using localize-extract and importing @angular/localize/init in public_api.ts
But distributed bundle doesn't have $localize property, so we are not able to extract translations like we do in applications.

### Proposed solution

Distribute library with $localize property when importing @angular/localize/init in main public_api.ts
Distribute generated xlf only for libraries.
Application that consumes this library, will have a new field in extract-i18n target in his angular.json
`"extract-i18n" {
    "addTranslationsFrom": [
         "@mylib1",
         "@mylib2"
    ]
}`

Behaviour is add translated fields from @mylib1 and @mylib2 distributed xlf, overwriting that fields on application xlf if exists. 

### Alternatives considered

Importing main library module to his non distributed application, and extract i18n from that application. But this option is not natural and transparent for user. xlf distribution is need to be contemplated too.

**Comment by alan-agius4** [comment]
There is already an [issue](https://github.com/angular/angular-cli/issues/17140) to track i18n in libraries.

Side note: please do not import `@angular/localize/init` in your library this can cause undefined behaviour. (https://github.com/angular/angular/issues/48545 and https://github.com/angular/angular/issues/48544)
