### ISSUE TITLE
Feature request: An "after @ViewQueries are complete" hook.

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#4856]
I have a subcomponent which is, in some use-cases, configured by data passed through a @ViewQuery. However, there is no hook in the subcomponent which runs after the @ViewQuery is complete.

e.g. I can not distinguish between the case where the configuration has not yet arrived and the configuration will never arrive.

Below is a simple repro, when run it prints.

    Initially saw 0 sub components
    Subcomponent onInit
    Subcomponent afterContentInit
    Subcomponent afterViewInit
    Query got a SubComponent
    Setting display text: hangry

I would like some hook to complete _after_ "Query got SubComponent" is printed.

index.dart
```dart
library main;

import 'package:angular2/angular2.dart';
import 'package:angular2/bootstrap.dart';

void main() {
  bootstrap(AppBodyComponent);
}

@Component(selector: 'app-body')
@View(template: '<sub-component></sub-component>', directives: const [SubComponent])
class AppBodyComponent {
  AppBodyComponent(@ViewQuery(SubComponent) QueryList<SubComponent> subComponents) {
    print('Initially saw ${subComponents.length} sub components');
    subComponents.changes.listen((_) {
      subComponents.forEach((subComponent) {
        print('Query got a SubComponent');
        subComponent.displayText = 'hangry';
      });
    });
  }
}

@Component(selector: 'sub-component')
@View(template: '{{displayText}}')
class SubComponent implements OnInit, AfterContentInit, AfterViewInit {
  @override onInit() {
    print('Subcomponent onInit');
  }

  @override afterContentInit() {
    print('Subcomponent afterContentInit');
  }

  @override afterViewInit() {
    print('Subcomponent afterViewInit');
  }

  String _displayText = 'initial';
  get displayText => _displayText;
  set displayText(d) {
    print('Setting display text: $d');
    _displayText = d;
  }
}
```

index.html
```html
<html>

<app-body>
</app-body>

<div style="width:400px">
  <p>
    Please open the Dev console to see the order of operations in this app.
  </p>
  <p>
    The app has two components, AppBodyComponent and SubComponent. AppBodyComponent is using @ViewQuery to provide important configuration information to the subcomponent.
    The subcomponent should be able to delay initialization until all its configuration has been set or the app knows it is not going to set the configuration. This
    is largely the purpose of [onInit]
  </p>
  <p>
    However, in this case, you will notice that SubComponent.onInit is called <b>before</b> the parent component is able to set the configuration through @ViewQuery.
    This is a bug. onInit should be delayed until all queries have been completed.
  </p>
</div>
<script src="index.dart" type="application/dart"></script>
<script src="packages/browser/dart.js"></script>
</html>
```

**Comment by jbdeboer** [comment]
@typotter pointed to @ViewChild, @ViewChildren. They seem to have the same order of operations as @ViewQuery.

**Comment by jbdeboer** [comment]
Internal issue # 25159046

**Comment by vicb** [comment]
I think `afterViewChecked` would do here ?

Note: it gets called multiple times, not sure if you are interested in the first call only ?

**Comment by jbdeboer** [comment]
The first call of ```afterViewChecked``` is the same as ```afterViewInit``, yes? If so, it is called too early in this example.

**Comment by thelgevold** [comment]
I just learned about afterViewChecked, but I am not 100% sure what it really does. Can you provide a quick explanation?

I have built a virtualized spreadsheet component and I use ```afterViewChecked``` to give the current "grid cell" focus based on arrow key based navigation. It appears to work, so I am assuming it something that fires after the model has been updated, but does it fire before or after any view updates as a result of model updates? 
My demo works here: http://www.syntaxsuccess.com/angular-2-samples/#/demo/spreadsheet

http://www.syntaxsuccess.com/viewarticle/virtualized-spreadsheet-component-in-angular-2.0

It does seam to work for me, but just curious about more details about this event and how it relates to timing of view side effects of model updates.

**Comment by vicb** [comment]
@jbdeboer oh wait, I haven't seen that the lifecycle hooks are implemented in the child component (vs the parent component). The result is then expected as the query is ready in the `afterViewInit` hook of the parent component which happen at a later point in time vs the one from the child component. I'm not sure to get what you are trying to do in your use case ?

@thelgevold `afterViewChecked` is called after the view has been checked :) The change detection update the view based on the model, so your response is after.

See doc / runnable examples on:
- https://github.com/angular/angular/blob/master/modules/angular2/src/core/linker/interfaces.ts
- https://angular.io/docs/ts/latest/api/lifecycle_hooks/AfterViewChecked-interface.html

**Comment by jbdeboer** [comment]
I am passing configuration data from the parent to the child using
@ViewQuery. I want / need to avoid the state where the child renders
invalid data (eg the above example should never render 'initial'

From my experimentation, the changes stream fires even after the parent's
afterViewInit so I expect there is more to this issue.

**Comment by thelgevold** [comment]
@vicb Thanks!
Does that mean that the view has "settled" at the time of calling afterViewChecked. Meaning all effects of detected model changes are rendered in the html?

**Comment by vicb** [comment]
yep

**Comment by mhevery** [comment]
Had a discussion with @jbdeboer and we decided that this is not a best use case, instead data should be passed in through DI. Closing as infeasible.
