### ISSUE TITLE
CanReuse guard

### ISSUE THREAD

**Issue by framasev** [angular/angular#48568]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

`RouteReuseStrategy` provides a general solution for route reuse and is not configurable for specific routes. The strategy has a verbose interface, error prone and misunderstood. One of the most effective optimization techniques is not available due to the complexity of implementation and misunderstanding. Custom strategy implementation requires sophisticated and deep knowledge of the details and quirks. Provide a simple and clear approach to route reuse.

### Solution:
Introduce a new kind of guard - `CanReuse` guard.

`CanReuse` is an interface that a class can implement to be a guard deciding if a route can be reused:
```typescript
/**
 * Interface that a class can implement to be a guard deciding if a route can be reused.
 * If all guards return `true`, previously stored route is attached or detached for later reuse (if no stored route found).
 * If any guard returns `false` stored route is erased.
 */
interface CanReuse {
  canReuse(route: ActivatedRouteSnapshot): boolean | Promise<boolean> | Observable<boolean>;
}
```

Extend `Route` interface:
```typescript
/**
 * The signature of a function used as a `canReuse` guard on a `Route`.
 */
export type CanReuseFn = (route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => boolean | Promise<boolean> | Observable<boolean>;

interface Route {
  /**
   * An array of `CanReuseFn` or DI tokens used to look up `CanReuse()`
   * handlers, in order to determine if the current route can be reused.
   */
  canReuse: boolean | Array<CanReuseFn | any>
}
```

### Use case:
```typescript
@NgModule({
  imports: [
    RouterModule.forRoot([
      {
        path: 'foo',
        component: FooComponent,
        canReuse: true
      },
      {
        path: 'bar',
        component: BarComponent,
        canReuse: [FooCanReuse, BarCanReuse]
      }
    ])
  ],
})
export class FooBarRoutingModule {}
```

### Alternatives considered

No alternatives considered.

**Comment by atscott** [comment]
Isn't this achievable in the `RouteReuseStrategy` itself by reading the `data` of `ActivatedRouteSnapshot`?
