### ISSUE TITLE
OnInit is not added to new components any more

### ISSUE THREAD

**Issue by ulfrenman** [angular/angular#48575]
### Describe the problem that you experienced

The linked stackoverflow topic do explain the issue well!
> `ng generate component` does not create ngOnInit and constructor

### Enter the URL of the topic with the problem

https://stackoverflow.com/q/74870515/42580

### Describe what you were looking for in the documentation

I was trying to run the TourOfHeros-tutorial when I could not match my experiance with the tutorial, so after some google-work I found the SO-topic.

**Comment by JeanMeche** [comment]
Thank you for reporting that, I've open a PR to update the tutorial.

**Comment by athirakarakkodath** [comment]
when I create components using ng g c component name , in my ts file ngOnInit and constructor are not creating.. I have to type that manually..using latest angular version..please help me i am new to this angualr

**Comment by JelleBruisten** [comment]
@athirakarakkodath Since the latest angular, this has been removed from the generate component schematic. So you will need to add lifecycle interfaces yourself. ( And also don't need to remove them incase they are not needed )
