### ISSUE TITLE
Support configuring of global Directives/Pipes

### ISSUE THREAD

**Issue by mhevery** [angular/angular#4857]
[Detailed design doc](https://docs.google.com/document/d/1rbVTKTYLz6p2smQNYI8h4-QN-m2PS6F3iQIDmSzn0Ww/edit#heading=h.4zwhxagl5yi)

Allow platform providers a way to load a set of ambient directives and pipes into the compiler. This is not something which we would recommend to the user, but it would be useful for platforms.

Examples:
- `BROWSER` would have `ng-if`, `ng-for`, etc...
- `IONIC` would have `ion-view`, etc..
- `NATIVESCRIPT` would have its own native components.

In each case the user would declare the component as:

```
@Component({
  selector: 'my-comp',
  template: '<ion-view *ng-for>...</ion-view>'
  // no need to import platform directives.
  // directives: [NgFor, IonView]
})
class MyComp {

}

platform(IONIC).application().component(MyComp);
```

**Comment by jessegood** [comment]
How is this different from https://github.com/angular/angular/issues/4275?

**Comment by pkozlowski-opensource** [comment]
@jessegood it is quite a different proposal, as I understand from reading the design doc. #4275 was about inheriting directives throughout the view hierarchy while the new proposal allows you to specify a platform-dependent set of "default" directives

**Comment by tbosch** [comment]
For NativeScript, this might not be needed: NativeScript has an own renderer, and determined by the element name which native component to use (very similar to how the browser does it).

Also, NgIf and NgFor are independent of the environment, relating them to BROWSER seems not correct.

**Comment by tbosch** [comment]
And for Ionic: they will probably soon need to hook into the renderer as well, eg to define what the click event really should do.

**Comment by tbosch** [comment]
As a side note: if we want to introduce this, we need a way to tell Dart
transformers, future JS build tools and IDEs which platform is being used
and which directives are active globally.
This could be a ngconf.json file, similar to a tsconfig.json file from
Tylescript. Tools would locate it by looking in the current directory and
then walking up.
This could also be used for eg configuring the element schema registry...

**Comment by mhevery** [comment]
Done

**Comment by trotyl** [comment]
Would this be re-visited after `NgModule` becomes optional?

<sub>(Possibly too early to ask.)</sub>

**Comment by mhevery** [comment]
Probably not in this form. But we are thinking about ways to make this simpler.
