### ISSUE TITLE
Unable to use workbox-webpack-plugin with angular and typescript

### ISSUE THREAD

**Issue by yelhouti** [angular/angular#48589]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

No

### Description

When I try to create my own service worker (That uses workbox), and have the `workbox-webpack-plugin` be responsible for replacing  the `self.__WB_MANIFEST` it fails while trying to compile the `serviceworker.ts` file saying:
> Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.

It looks like,  trying to apply the workbox plugin:
```
    new WorkboxPlugin.InjectManifest({
      swSrc: './src/main/webapp/serviceworker/serviceworker.ts',
      swDest: 'serviceworker.js',
    })
```
causes ivy to try to compile the ts file, and fails some reason I don't understand.
The advantage of using the plugin, is that all the compile assets are replaced automatically.

I am using:
```
"builder": "@angular-builders/custom-webpack:browser",
"options": {
  "customWebpackConfig": {
    "path": "./webpack/webpack.custom.js"
  },
```

I tried (ab)using the "webWorkerTsConfig" in angular.json but it didn't help.

### Please provide a link to a minimal reproduction of the bug

https://github.com/yelhouti/angular-workbox

### Please provide the exception or error you saw

```true
./src/main/serviceworker/serviceworker.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.3
Node: 16.13.0
Package Manager: npm 8.1.0 
OS: linux x64

Angular: 14.2.3
... cli, common, compiler, compiler-cli, core, forms, localize
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.3
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.2.3
@schematics/angular             14.2.3
rxjs                            7.5.7
typescript                      4.8.3
```

### Anything else?

I also tried returning multiple webpack configs: to compile the `servicworker.ts` using ts-loader separetly, but it doesn't work because angular expect one config when trying to check if ti should enable the dev server.

**Comment by JoostK** [comment]
I am sorry, but custom builders and their configuration options are not supported by the Angular team.

Happy holidays! ⭐

**Comment by yelhouti** [comment]
@JoostK I would rather bot use a custom builder. And the issue I am facing seems to  came from the default build. Do You have any idea how to do what I want with plain angular. Also please reopen.
