### ISSUE TITLE
Content should not be archived

### ISSUE THREAD

**Issue by martinferra** [angular/angular#48593]
### Describe the problem that you experienced

The doc entry at [Navigate the component tree with DI](https://angular.io/guide/dependency-injection-navtree) is marked for archiving, but it is helpful in order to understand how a component can get an instance of its parent component using DI, and no other doc article explains that clearly.

### Enter the URL of the topic with the problem

https://angular.io/guide/dependency-injection-navtree

**Comment by JeanMeche** [comment]
Angular.io is now in maintenance mode. If you feel that the new docs site https://angular.dev is missing some specific docs, feel free to open a new issue.
