### ISSUE TITLE
DomSanitizer.sanitize converts Unicode characters to escape strings

### ISSUE THREAD

**Issue by zijianhuang** [angular/angular#48598]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

`sanitizer.sanitize(SecurityContext.HTML, this.sampleString)` converts `这是中文` to `&#36825;&#26159;&#20013;&#25991;`

With the stackblitz link, make a slight change:
```javascript
  constructor(private sanitizer: DomSanitizer) {
    console.debug(this.sampleString);
    this.sampleString = sanitizer.sanitize(SecurityContext.HTML, this.sampleString);
    console.debug(this.sampleString);
  }
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-issue-repro2-kh52nw?file=src%2Fapp%2Fapp.component.ts

### Please provide the exception or error you saw

```
这是中文
preview-d0bbfde89eb2a.js:2 &#36825;&#26159;&#20013;&#25991;
```

### Anything else?

related to https://github.com/angular/angular/issues/31835 and https://github.com/kolkov/angular-editor/issues/249

**Comment by pkozlowski-opensource** [comment]
@zijianhuang the linked stackblitz is using Angular 6 version which is very old. Also it is not clear to me what changes should be made to reproduce the issue.

Could you please share a minimal reproduction using the latest Angular version?

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
