### ISSUE TITLE
Simple syntax (decorator) for two-way binding

### ISSUE THREAD

**Issue by camiloux** [angular/angular#48605]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

It would be ideal to have a simple syntax to achieve two-way binding for any variable. This is a common need for most basic scenarios, yet, a well implemented solution often requieres unnecessary configuration of getter and setters.

### Proposed solution

A solution could look something like this inside the component class:

`@Bind() show = false;`

This would automatically provide high-quality two-way binding to that variable, inside that component.
Outside the component it could remain the same:

`<app-modal [(show)]="openModal"></app-modal>`

### Alternatives considered

This simple syntax could be equivalent to following code (today required to achieve "real" and functional two-way binding):

```
@Input() 
 set show(val: boolean) { 
    this.showChange.emit(val);
    this._show = val;
  }
  get show() {
    return this._show;
  }

@Output() showChange =  new EventEmitter<boolean>();
```

Often it is necessary to implement reactive forms and complex Control Value Accessors to achieve something that could be resolved with an out-of-the-box  two-way binding decorator.

**Comment by JoostK** [comment]
> ```
> @Input() 
> set show(val: boolean) { 
>    this.showChange.emit(val);
>    this._show = val;
>  }
>  get show() {
>    return this._show;
>  }

This example is interesting, as it is an anti-pattern that violates uni-directional dataflow principles.

**Comment by jmroon** [comment]
Form controls already violate uni-directional dataflow principles. I don't really see a problem with this.

**Comment by pkozlowski-opensource** [comment]
@camiloux thnx for the suggestion. I think that there are multiple things going on here.

First, as @JoostK pointed out emitting from an input setter is an anti-pattern that we don't want to encourage. If we take this out, we are left with the potential sugar syntax for:

```typescript
@Input() show: boolean;
@Output() showChange =  new EventEmitter<boolean>();
```

But the proposed syntax `@Bind() show = false` would "hide" the event emitter (so we couldn't emit new events).

>  Implementing CVA for two way bound ngModel is extremely cumbersome.

@jmroon agreed, we are well aware of it.
