### ISSUE TITLE
DefaultValueAccessor directive should be usable in the hostDirectives array

### ISSUE THREAD

**Issue by mikeandtherest** [angular/angular#48607]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

The `DefaultValueAccessor` directive is not standalone, which means that it cannot be currently used with the `hostDirectives` array of a component.
I have this scenario where it would be very handy for the `ngDefaultControl` directive to be applied on the host element from inside the component's class, leveraging the new `hostDirectives` array from Angular 15.

**Desired code:**
```ts
@Component({
  selector: 'app-input',
  templateUrl: './input.component.html',
  styleUrls: ['./input.component.scss'],
  hostDirectives: [DefaultValueAccessor]
})
export class InputComponent implements OnInit {

  @Input() formControlName!: string;

  group!: FormGroup;

  constructor(@Optional() private formGroupDirective: FormGroupDirective) {
  }

  ngOnInit(): void {
    this.group = this.formGroupDirective?.control;
  }

}
```

The code above throws the following build time error:

```ts
Error: src/app/shared/input/input.component.ts:8:20 - error NG2014: Host directive DefaultValueAccessor must be standalone

8   hostDirectives: [DefaultValueAccessor]
                     ~~~~~~~~~~~~~~~~~~~~
× Failed to compile.
```

### Proposed solution

The `DefaultValueAccessor` directive should be available also as standalone, for the new Angular 15 approaches.

### Alternatives considered

As a workaround, a custom component provider can make the "link" with the `DefaultValueAccessor` directive. But it's still better/easier to use the `hostDirectives` approach for this, since it is more explicative.

**Current workaround:**
```ts
@Component({
  selector: 'app-input',
  templateUrl: './input.component.html',
  styleUrls: ['./input.component.scss'],
  providers: [{
    provide: NG_VALUE_ACCESSOR,
    useClass: DefaultValueAccessor,
    multi: true
  }]
})
export class InputComponent implements OnInit {

  @Input() formControlName!: string;

  group!: FormGroup;

  constructor(@Optional() private formGroupDirective: FormGroupDirective) {
  }

  ngOnInit(): void {
    this.group = this.formGroupDirective?.control;
  }

}
```

**Comment by mikeandtherest** [comment]
@dylhunn I saw the closing comment you've added to the PR created by @JeanMeche. Would you like this issue to be kept open for future reference, or close it and open a new one when time comes?

**Comment by JeanMeche** [comment]
The `DefaultValueAccessor` won't work on custom component. 

* Events are bubling up from the input, so they are caught by the DefaultValueAccessor, this is fine. 
* But the value accessor isn't able to target the input as it will try to write directly on the custom component element (not the component instance). 

https://github.com/angular/angular/blob/main/packages/forms/src/directives/control_value_accessor.ts#L166-L168
