### ISSUE TITLE
A problem with using <ng-template [ngIf]="objectRef">

### ISSUE THREAD

**Issue by mlc-mlapis** [angular/angular#48609]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Using the following template should seem safe, but it's not.
```
<ng-template [ngIf]="hintRef" [ngTemplateOutlet]="hintRef.templateRef"></ng-template>
```
The problem is, that even if the condition `[ngIf]` is `false` (here, in the example, it's `undefined`), its `templateRef` property is evaluated and leads to an error.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/mlc-angular-v15-0-4-templateref

### Please provide the exception or error you saw

```
ERROR TypeError: Cannot read properties of undefined (reading 'templateRef')
    at ParentComponent_Template (parent.component.html:4:32)
    at executeTemplate (shared.ts:529:7)
    at refreshView (shared.ts:400:6)
    at refreshComponent (shared.ts:1648:9)
    at refreshChildComponents (shared.ts:145:3)
    at refreshView (shared.ts:452:41)
    at refreshComponent (shared.ts:1648:9)
    at refreshChildComponents (shared.ts:145:3)
    at refreshView (shared.ts:452:41)
    at detectChangesInternal (shared.ts:1802:1)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```
Angular: 15.0.4
Angular CLI: 15.0.4
OS: any
```

**Comment by JeanMeche** [comment]
I'd say this is expected. The structural directive`*ngIf` prevents from evaluating the other values, but `[ngIf]` doesn't.

**Comment by mlc-mlapis** [comment]
It could be, but can it be improved?

**Comment by JelleBruisten** [comment]
Isn't this exactly why we have the structural directive syntax using *ngIf Which destructs into

`<ng-template [ngIf]="">`

**Comment by mlc-mlapis** [comment]
Yep, it's true. But I can imagine that even the destructured version can use the `ngIf` property exclusively and not enforce additional syntax to ensure safe usage.

**Comment by JelleBruisten** [comment]
That would result in some sort of priority of directive x over directive y, which is how it worked in angularJS which I assume is why there are structural directives and why only one structural directive can be applied to a single tag. 

What do you propose would be a solution for this problem?

For the problem in the description it can just be resolved
`<ng-container *ngIf="hintRef" [ngTemplateOutlet]="hintRef.templateRef"></ng-container>`

Making the `ngIf` resolve before the others on the same tag
