### ISSUE TITLE
Cannot import and use parent standalone component in child standalone component

### ISSUE THREAD

**Issue by sheikalthaf** [angular/angular#48614]
### Which @angular/* package(s) are the source of the bug?

compiler, core

### Is this a regression?

Yes

### Description

I converting my angular application into standalone components, When I have to import parent component in child component then I getting an error. It is works fine with module. In below link I'm importing parent Component in child component after that the app stops working

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-nested-parent-child

### Please provide the exception or error you saw

```true
preview-d0bbfde89eb2a.js:2 ERROR TypeError: Cannot read properties of undefined (reading 'ɵcmp')
    at getComponentDef (container.ts:20:23)
    at extractDirectiveDef (definition.ts:420:6)
    at Array.map (<anonymous>)
    at def.directiveDefs (definition.ts:360:4)
    at createTView (shared.ts:663:4)
    at getOrCreateComponentTView (shared.ts:608:16)
    at addComponentLogic (shared.ts:1422:4)
    at instantiateAllDirectives (shared.ts:1190:4)
    at createDirectivesInstances (shared.ts:561:4)
    at ɵɵelementStart (element.ts:149:6)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular/animations
15.0.2

@angular/common
15.0.2

@angular/compiler
15.0.2

@angular/core
15.0.2

@angular/forms
15.0.2

@angular/platform-browser
15.0.2

@angular/platform-browser-dynamic
15.0.2

@angular/router
15.0.2

rxjs
7.5.7

tslib
2.4.1

zone.js
0.12.0
```

**Comment by sheikalthaf** [comment]
I can able to solve the issue by **forwadRef**. 

```
imports: [forwardRef(() => ParentComponent)]
```

https://angular.io/api/core/forwardRef

But document need more example like this

**Comment by pkozlowski-opensource** [comment]
`forwardRef` is the correct approach here. And yes, we might want to explicitly call it out in our docs: https://angular.io/guide/standalone-components

**Comment by indraraj26** [comment]
@sheikalthaf if you don't mind, Can you write down the use-case. I feel it may lead to infinite loop. I don't feel it is great practice to have two-direction data flow.

**Comment by sheikalthaf** [comment]
@indraraj26 Yes It will lead to infinite loop but i have added a condition to control the recursive component, Another usecase for nested component calling is available in this repo

@pkozlowski-opensource @indraraj26  https://github.com/sheikalthaf/angular-tree
