### ISSUE TITLE
Webp handling for NgOptimizedImage

### ISSUE THREAD

**Issue by goelinsights** [angular/angular#48613]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

I'm not sure if this is a documentation request or a feature request. I'm hoping it's the former.

Attempting to use ngSrc and srcset as part of NgOptimizedImage. It's unclear how to inject multiple file types to allow a browser that doesn't handle webp to fall back to JPG. Generally, that appears to be enabled by a `<picture>` tag that allows for multiple sources with MIME types.

### Proposed solution

1) Documentation to highlight whether webp -> jpg fallback is compatible with NgOptimizedImage as well as team-recommended defaults, i.e.,
a) Webp has enough browser support to just use it without JPG (or point to a relevant polyfill)
b) Example of use of `<picture>` tag that is compatible with NgOptimizedImage use of `<img>` tag with `ngSrc`
c) NgOptimizedImage supports webp + fallback under the hood.

2) Development of a `[fallback]` input that would support a fallback file

### Alternatives considered

Strip out ngSrc from NgOptimizedImage in production and use the `<picture>` + `<source>` approach.
(from https://web.dev/serve-images-webp/)
```
<picture>
  <source type="image/webp" srcset="flower.webp">
  <source type="image/jpeg" srcset="flower.jpg">
  <img src="flower.jpg" alt="">
</picture>
```

**Comment by goelinsights** [comment]
After testing with a webp srcset and ngSrc for the img tag, it looks like everything works (no errors). Closing the issue.

**Comment by spock123** [comment]
@goelinsights afaik, all browsers support webp so not sure fallback would ever occur anyways.

https://caniuse.com/webp
