### ISSUE TITLE
Change detection infinite loop in Firefox

### ISSUE THREAD

**Issue by ComputerWolf** [angular/angular#4861]
I have randomly found that there are some triggers that can cause an infinite change detection loop in Firefox.

I have replicated one on Plunker: http://plnkr.co/edit/VTS89eJkePLrJjuoDzOK

The ScrollToFixed plugin does some basic dom manipulation and applies some styles. However if you scroll the "Main" section and then the "Sidebar" section, you will see that doCheck is called infinitely.

I have also been able to trigger an infinite loop in Firefox by triggering a marker within a Google map to start animating.

The infinite loop does not occur in IE, Safari or Chrome. I am unsure if this is a problem with Angular2 or Firefox, but I cannot find the source of the issue.

**Comment by vicb** [comment]
Seems like the jQuery plugin binds event listener and this could cause the issue: every time a listener is executed, it would trigger the change detection.

If this is the issue, one way to solve it would be to call the plugin outside of the angular zone:

```js
export class App implements DoCheck{
  constructor(ngZone: NgZone)
	{		
		ngZone.runOutsideAngular(() => $('#sidebar').scrollToFixed());
	}
```

I'll check later today if this solves the issue

**Comment by vicb** [comment]
I can not reproduce your issue in Ubuntu / FF 42

Could you please try http://plnkr.co/edit/PzE1LLqhslIDhWpnKc9D?p=preview and report if this helps ?
