### ISSUE TITLE
Loading 50 dynamic Angular Components in *NgFor takes long time to initialize (15 secs)

### ISSUE THREAD

**Issue by ShashankDhasal** [angular/angular#48610]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I am loading 50 angular components in a ngFor loop  
formItemList is a array and has 50 angular components

```
<mat-expansion-panel expanded="true" *ngFor="let item of formItemList; let i = index" id="{{item.id}}"
                class="pad-top-sm, expansion-panel">
                <mat-expansion-panel-header id="{{'mat-header' + i}}">
                    <div>
                        <a id="{{'mat-help' + i}}" href="{{ item.help }}" class="inline" title="help"
                            target="_blank">
                            <s-icon name="help-circle" class="relative active small margin-right-xs">
                            </s-icon>
                        </a>
                        <h3 id="{{'mat-expansion-label' + i}}" class="inline">{{ item.label }}</h3>
                    </div>
                </mat-expansion-panel-header>
                <ng-container app-add-component [component]="item.component"></ng-container>
            </mat-expansion-panel>
```

```
static formItemList: FormItem[] = [
    {
      id: "testId",
      label: "testId",
      help: "https://google.com",
      component: FormComponent
    }];  // has 50 such objects
```

Form Component has no server calls and UI html is an empty html table.  
***app-add-component*** is a directive that creates components

```
@Directive({
    selector: '[app-add-component]',
})
export class AddComponentDirective implements AfterViewInit {

    @Input() component: Type<any> | undefined;
    constructor(public viewContainerRef: ViewContainerRef) {

    }

    ngAfterViewInit() {
        Promise.resolve().then(() => {
            this.viewContainerRef.clear();
            if (this.component)
                this.viewContainerRef.createComponent(this.component);
        });
    }
}
```

This is working but takes almost more than 15 sec to bind the components to the HTML. The scrren is frozen for that time.
How can I make this load faster?

**I have tried trackby in ngFor but I am supplying all the 50 components all at once so this is of no use.**

**_The use case is for all the 50 components should load in under 5 secs_**

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 13
```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

The primary contributor to the slow rendering performance is likely the `Promise.resolve` microtick, resulting in multiple change detection cycles.
