### ISSUE TITLE
Support event type information for tools.

### ISSUE THREAD

**Issue by mhevery** [angular/angular#4862]
Assume that the user has typed:

```
<component (click)="$event.?A?" (open)="$event.?B?"
```

How does the IDE know how to complete the suggestions at `?A?` and `?B?` sites?

Turns out that `?A?` is a DOM event and as such there is no easy way to know what the type of `$event` is other than having the IDE recognize that it is a DOM event. This implies that the IDE needs to have pre-existing schema. Such schema (#3426) is something that Angular2 compiler needs to have as well so that we can properly validate weather or not a particular element can event a particular DOM event. (Examples is `input` element emitting a change event). The goal should be to have the event schema for DOM be declared in a way which is tool-able so that tools can take advantage of it.

Completion on `?B?` is of different kind, it is an event which is fired from the `component` element and which does not bubble. In such a case we have to look at the directive annotation so that we can derive the type for `$event` for completion.

```
@Component({...})
class MyComponent {
  @Output() open: EventEmitter<SomeType> = new EventEmitter();
  @Output() open: Stream<SomeType> = ...;
}
```

For an IDE the resolution logic would be to check the schema and derive the type there. If not found check for the directives on the element and see if they fire such an event and what the type is.

**Comment by scheglov** [comment]
What type should `open` have? `EventEmitter<SomeType>` or `Stream<SomeType>` or ...? What if it is `MyEmitterThatAlsoImplementsStream<int, SomeType, double>`?

**Comment by mhevery** [comment]
All of your examples implement `Stream<T>`, so the analyzer would have to walk the type hierarchy and then figure out what `T` is.

**Comment by mhevery** [comment]
This is related to: #3427

**Comment by scheglov** [comment]
Well, that's the question - what type should event declarations be?
Something implementing `Stream<T>`?
If yes, then sure - extracting the event type `T` is trivial.

**Comment by mhevery** [comment]
> Something implementing Stream<T>?

Yes.

**Comment by scheglov** [comment]
Very good.
Yes, the proposed solution works for me.
Thank you!

**Comment by robwormald** [comment]
FYI, after the refactor to EventEmitter in https://github.com/angular/angular/commit/ca3986f31dba5793b0a141e90c4a5fb17ce8847a it's now generic.

**Comment by scheglov** [comment]
Nice!
Thank you.

**Comment by DzmitryShylovich** [comment]
@chuckjaz does language service cover this use case?

**Comment by chuckjaz** [comment]
Yes. `@angular/language-service` will look at the event type to determine the type of the `$event`. Any deficiency here should be reported as a bug against `langauge-service`. Closing this.
