### ISSUE TITLE
Explicitly pass ControlConfig in FormBuilder#group type breaks in 14.2 with this changes

### ISSUE THREAD

**Issue by Frankitch** [angular/angular#48631]
Explicitly pass ControlConfig in FormBuilder#group type breaks in 14.2 with this changes
Pass in `{ email: ControlConfig<string>; }` will return `FormGroup<{ email: FormControl<string | undefined>; }>` instead of `FormGroup<{ email: FormControl<string>; }>` with NonNullableFormBuilder
[Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYQBYEMB2BzApgEVxlwGMZgJMBlGKdY7ATwBoUJxLdN4BfOAMyjs4AcgACWbAFcANuigB6EtFwiA3AFgAUKEixEcAIIBnRphIA1dDOAATetABimVskq0IMt5n7BsrR2gQbw8ZAKCQoRkaelxwqBAAcSEpMFYAOUp02TkAIxlcQISAISlgGVtcKFYrG3sYJxc4WrsHKGM4PkFhcUlZeQV+ION1bW1gbir+dBJcOAAZCGwJ5ChcSu5ga2MASUxgcmsAJVwZ8gA3QqDkiFTEbTg4XBB0coAuNm4o719sAB5jLQJtgAHyaLQ8MZaBQKJ4AD0gxjmAAUqiBgMZjMBLpFPD8-HAJnAwFJ8sASEZkTsAPzaGCMMAotEYrE49zfSi-P4AFRBcAAvEYoHRGDyAD5FYLszwxYg8kFilr1aD40Hg+mM5rWVoNKCqgVauptZxikxmSza5VQE1K42YADaAF1TaZzLbdc4neDtDC4KiEizsbhcV5OQTLu0KJhxpMoNNZn7mZig4tlphVusuIcZLt9tmTmcg5KbncEA8ni93omA8m2V88WH-oCoMCwdpIVoY8Q4zM5qmVmsNtnjAWyEXrikwPctI9nq8ZB9JSGAUCcG2IVCxG4OJgswAKMszuBIgpkaAfEToMBgAC0QggMBEzHLxHAcmIAFUoAvRAA6BRXmAv7KDuWa-qgMAgDIT7loCjAFF+OYfPaIj-oBwHsJAu7cMBmIiI6z5HiQGA4AQRCkOQlAfGgkhkcQY6UDQdAMIwv4APKYMiUjGKghE8AAlNouAItA8AkHImJGNe25YVm06PCSZIUjISwTMWk6LhOtxgH8-bpoOWZbDmo4XFcCQlmA67lsomDNlIZ5QHuYAtucsRwGs6C2JQMiMAIuQfJkmDZDIeQFJKpTlJUUD8fJjxwDAqAYr+Klpup2kCuWcXxYlxi-vwuS-tgk66ap+mZps2x7AcRkmeO5mTiCB6ZVlFbzshIhPnA9rutAuVrAAjmUg6Oo6zWPAJ3pHo8vr+uitbBtKoY+OGVRYpQzUJUlKVqVpdz8mN2VJflhXFbNgaXHpGZDkZubVccpxjpcaWpI1h4tXFc5VihnXdZabR9bgg3AMNo1TXFE3lh2HZAA) modified from #46570
Switching to PermissiveControlConfig seem to work
Coud PermissiveControlConfig be exposed in public API? or other alternatives?
I need to pass in the type for controls with null or empty array initial value

_Originally posted by @hlmasterchief in https://github.com/angular/angular/issues/47034#issuecomment-1237645541_

**Comment by JeanMeche** [comment]
I'm giving it a shot. 

The problem lies with `ɵElement`

https://github.com/angular/angular/blob/2d0ca73d73b0545a6246060aea843b755eafcd7f/packages/forms/src/form_builder.ts#L64-L93

When doing `[T] extends [PermissiveControlConfig<infer U>] ` which is `[ControlConfig] extends [PermissiveControlConfig<infer U>]` , `U` is infered as `string | undefined` because of the optionals (async)Validators #48793 
https://github.com/angular/angular/blob/2d0ca73d73b0545a6246060aea843b755eafcd7f/packages/forms/src/form_builder.ts#L54

**Comment by dylhunn** [comment]
I don't actually understand the use case for this. Why are you explicitly naming `ControlConfig` in your type? `ControlConfig` *describes* the argument shape accepted by `FormBuilder`:

```
const c = fb.group({foo: ['bar', Validators.required]});
```

You should never be constructing a `FormGroup` with values that are actually `ControlConfigs`.

**Comment by Frankitch** [comment]
@dylhunn , the use case is to type a FormGroup built with FormBuilder like this:
```
interface LoginCredentialsInitialReactiveFormGroup {
  email: ControlConfig<string>;
  password: ControlConfig<string>;
}

@Component({
    ...
})
export class AppComponent {
  public loginFormGroup: FormGroup<LoginCredentialsReactiveFormGroup>;

  constructor(private readonly fb: NonNullableFormBuilder) {
    this.loginFormGroup =
      this.fb.group<LoginCredentialsInitialReactiveFormGroup>({
        email: ['', [Validators.required]],
        password: ['', [Validators.required]],
      });
  }
}
```

**Comment by dylhunn** [comment]
Again, you should _never_ need to use the `ControlConfig` type as a form value. It exists strictly to describe the argument that `FormBuilder` accepts.

Here's how you can achieve your goal. Delete the `LoginCredentialsInitialReactiveFormGroup`, as well as the corresponding explicit type argument, and your example works. Here's the corrected code:

```
interface LoginCredentialsReactiveFormGroup {
  email: FormControl<string>;
  password: FormControl<string>;
}

...

loginFormGroup: FormGroup<LoginCredentialsReactiveFormGroup> =
  this.fb.group({
    email: ['', [Validators.required]],
    password: ['', [Validators.required]],
});
```

**Comment by dylhunn** [comment]
@Frankitch Again, you should _never_ need to use the `ControlConfig` type as a form value. It exists strictly to describe the argument that `FormBuilder` accepts.

Here's how you can achieve your goal. Delete the `LoginCredentialsInitialReactiveFormGroup`, as well as the corresponding explicit type argument, and your example works. Here's the corrected code:

```
interface LoginCredentialsReactiveFormGroup {
  email: FormControl<string>;
  password: FormControl<string>;
}

...

loginFormGroup: FormGroup<LoginCredentialsReactiveFormGroup> =
  this.fb.group({
    email: ['', [Validators.required]],
    password: ['', [Validators.required]],
});
```
