### ISSUE TITLE
duplicate standalone components in app component router-outlet

### ISSUE THREAD

**Issue by sysmat** [angular/angular#48659]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

- on home app components stand alone is doubled, but defined once
- but when routing to child it is only once

![ng_double](https://user-images.githubusercontent.com/69830/211154321-bced4bf5-da34-428c-886b-d922fa7b43d7.png)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-a2blad?file=package.json

### Please provide the exception or error you saw

```true
https://angular-ivy-a2blad.stackblitz.io
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.4        
Node: 18.12.1
Package Manager: npm 8.18.0
OS: win32 x64

Angular: 15.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.4
@angular-devkit/build-angular   15.0.4
@angular-devkit/core            15.0.4
@angular-devkit/schematics      15.0.4
@schematics/angular             15.0.4
rxjs                            7.5.7
typescript                      4.8.4
```
```


### Anything else?

_No response_

**Comment by JoostK** [comment]
You are using `AppComponent` both as bootstrap component and as routed component, so the routed component will be nested within the bootstrapped component, resulting in it being shown twice.

**Comment by sysmat** [comment]
yes, but not very DX
