### ISSUE TITLE
FormGroup typing with partial properties

### ISSUE THREAD

**Issue by mdominiak2** [angular/angular#48666]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

```
interface MyType {
    a?: FormControl<string>;
    b?: FormControl<number>;
}

const form: FormGroup<MyType> = new FormGroup({
    a: new FormControl<string>('', { nonNullable: true }),
});
```

To me, this assign should be correct.

### Please provide the exception or error you saw

```true
Type 'FormGroup<{ a: FormControl<string>; }>' is not assignable to type 'FormGroup<MyType>'.
  Type 'FormControl<string> | undefined' is not assignable to type 'FormControl<string>'.
    Type 'undefined' is not assignable to type 'FormControl<string>'.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 14.2.9
```

**Comment by alxhub** [comment]
The error you're getting from TypeScript is accurate.

For various TypeScript reasons, `FormGroup` is invariant in its generic type. That means that `FormGroup<X>` is not assignable to `FormGroup<Y>`, even if `X` itself is assignable to `Y` (or `Y` to `X`). In your example, that means `FormGroup<{a: FormControl<string>}>` (which is what's inferred by `new FormGroup(...)`) is not assignable to `FormGroup<MyType>`.

Instead, you can override type inference and directly specify the `FormGroup` type you want:
```typescript
const form = new FormGroup<MyType>({...});
```
