### ISSUE TITLE
Bindings does not default deps to const[]

### ISSUE THREAD

**Issue by irfantusneem** [angular/angular#4866]
The following fails
const Binding(MyClass,toFactory: buildMyClass)

The following is successful
const Binding(MyClass,toFactory: buildMyClass, deps: const [])

What is a valid use case for 
const Binding(MyClass,toFactory: buildMyClass, deps: null)?

**Comment by vicb** [comment]
if ` deps`  is null, we can "discover" the dependencies using reflection. 

` null`  => try to firgure out using reflection vs ` []`  => no dependency.

**Comment by vsavkin** [comment]
When deps is not provided, it is set to null. So the following two lines are equivalent: 

```
const Binding(MyClass, toFactory: buildMyClass)
const Binding(MyClass, toFactory: buildMyClass, deps: null)
```

This is what the framework does: `if (deps == null) { useReflectionToGetDeps() }`

Basically, the current default means "use reflection". Using an empty list as a default makes sense only for functions without parameters. For example, assigning an empty list to the following factory is really strange:

const Binding(MyClass, toFactory: (@Inject("initNumber") x) => x + 100)

So we can use [] as a default only if we can get the function's arity, which requires using mirrors. But if you can use mirrors, you would not need to specify dependencies. That is why the default works the way it works.

We could change the API to make null similar to an empty list, but you would still have to explicitly pass null:

```
const Binding(MyClass, toFactory: buildMyClass, deps: null)
const Binding(MyClass, toFactory: buildMyClass, deps: const [])
```

But this one would still mean use reflection:

```
const Binding(MyClass, toFactory: buildMyClass)
```

But I think it might be even more confusing.

**Comment by matanlurey** [comment]
Sorry, than can we change this to give some sort of useful error message?

Right now the error message doesn't make it clear it fails because you are missing `@Injectable()` on the factory function.
