### ISSUE TITLE
HTTP Interceptor getting status as 0

### ISSUE THREAD

**Issue by thanecoder** [angular/angular#48675]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

HTTP Interceptor gets status of 0 when a CORS error comes from Server. This happens mainly for an OPTIONS Preflight request which leads to then further request also not getting the correct status. 

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.2
Node: 14.20.1
Angular: 15.0.0
```

**Comment by JeanMeche** [comment]
That's expected, when the OPTIONS return the wrong header, the browser won't trigger the actual request thus a status 0.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
