### ISSUE TITLE
interface / abstract class naming

### ISSUE THREAD

**Issue by vicb** [angular/angular#4867]
From NAMING.md:
- "Should not end with Impl or any other word which describes a specific implementation of an interface."
- "Should not have I or Interface in the name or any other way of identifying it as an interface."

Current state of the code:

```
abstract class Compiler {}
export class Compiler_ extends Compiler {}
export class RuntimeCompiler_ extends Compiler_ implements RuntimeCompiler {}

export class XHRImpl extends XHR {}

interface PostMessageInterface {}

// TBC
```

IMO we needs to agree on a convention, document it & _enforce it_

**Comment by mhevery** [comment]
Is this still an issue or can we close it?
