### ISSUE TITLE
dynamicComponentLoader can't instantiation out of constructor

### ISSUE THREAD

**Issue by Louis-7** [angular/angular#4868]
Hi Team,

I wanna use dynamicComponentLoader to load my components.

But I found dynamicComponentLoader can only be instantiation in constructor, actually when I instantiation it out of a constuctor, there will be a 'simplistic' version of dynamicComponentLoader. 

I'm so confused, is this a bug? If not, how can I use dynamicComponentLoader in my custom method.

**Comment by todoubaba** [comment]
You can inject dynamicComponentLoader to a service class, see: https://github.com/angular/angular/blob/1aeafd31bd440a4997362e66738926387940fc1e/modules/angular2_material/src/components/dialog/dialog.ts#L41

**Comment by Louis-7** [comment]
@todoubaba  How can I use it in my method?  If I'm not use it in service?

Actually, I wanna know why I can't instantiation it in my method.

**Comment by todoubaba** [comment]
@Louis-7 [`DynamicComponentLoader`](https://github.com/angular/angular/blob/master/modules/angular2/src/core/linker/dynamic_component_loader.ts#L92) is an abstract class, the actural impl class is [`DynamicComponentLoader_`](https://github.com/angular/angular/blob/master/modules/angular2/src/core/linker/dynamic_component_loader.ts#L264) which is internal and you should not use it directly.

**Comment by Louis-7** [comment]
@todoubaba  thx.

**Comment by Louis-7** [comment]
@todoubaba  Hi, sorry t ask again.

If my component have a constructor, I need init some variables in it. So how can I init these variables when I use dynamicloader? Now seems my component doesn't run constructor.

**Comment by todoubaba** [comment]
@Louis-7 You can get component instance through `componentRef.instance`:
```typescript
loader.loadNextToLocation(type, elementRef, resolvedProviders).then((componentRef) => {
  let instance = componentRef.instance;
  ...
}
```
