### ISSUE TITLE
angular路由复用策略使用一段时间,报错Error: Outlet is not activated,导致无法加载路由

### ISSUE THREAD

**Issue by meiwanmeiliaola** [angular/angular#48691]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

实现RouteReuseStrategy接口,使用一段时间,就会出现无法加载路由的错误

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI:13.2.5
Node:14.19.0
```

### Anything else?

![image](https://user-images.githubusercontent.com/45260347/211748739-eba8d0c3-9a1c-4efe-b3f2-4fabdabc7d9a.png)

参考的代码链接:https://www.jianshu.com/p/3357e5e45b92

**Comment by jiangyh1024** [comment]
可以用中文提问？

**Comment by meiwanmeiliaola** [comment]
> 可以用中文提问吗？

你也是用中文回答的啊,怎么不能用中文呢,就看有没有人看这问题了

**Comment by jiangyh1024** [comment]
> > 可以用中文提问吗？
> 
> 你也是用中文回答的啊,怎么不能用中文呢,就看有没有人看这问题了

哈哈 我只是看到你用了。 ng团队能看懂吗

**Comment by meiwanmeiliaola** [comment]
> > > 可以用中文提问吗？
> > 
> > 
> > 你也是用中文回答的啊,怎么不能用中文呢,就看有没有人看这问题了
> 
> 哈哈 我只是看到你用了。 ng团队能看懂吗

让他们用中文翻译,哈哈哈

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
