### ISSUE TITLE
The problem occurs when I need to use the HttpClient within a unit test. Even using the HttpClientTestingModule, my tests can't find it and it ends up breaking in at least 200 tests out of the 6000 we have.

### ISSUE THREAD

**Issue by chandan-bcsg** [angular/angular#48693]
The problem occurs when I need to use the HttpClient within a unit test. Even using the HttpClientTestingModule, my tests can't find it and it ends up breaking in at least 200 tests out of the 6000 we have.

I'll put an example of how we are creating the test instance and the return in the terminal I added in the opening of the issue.

Example:

```typescript
      TestBed.configureTestingModule({
        imports: [PoModalModule, HttpClientTestingModule, PoDynamicModule, RouterTestingModule],
        declarations: [PoLookupModalComponent],
        providers: [LookupFilterService, PoComponentInjectorService],
        schemas: [NO_ERRORS_SCHEMA]
      }).compileComponents();
```

And when I run karma it gives me these errors here

```bash
NullInjectorError: R3InjectorError(DynamicTestModule)[ActivatedRoute -> ActivatedRoute]:
          NullInjectorError: No provider for ActivatedRoute!
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'ActivatedRoute', 'ActivatedRoute' ] })
        NullInjectorError: R3InjectorError(DynamicTestModule)[ActivatedRoute -> ActivatedRoute]:
          NullInjectorError: No provider for ActivatedRoute!

============================== AND ==============================

NullInjectorError: R3InjectorError(DynamicTestModule)[HttpClient -> HttpClient]:
          NullInjectorError: No provider for HttpClient!
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'HttpClient', 'HttpClient' ] })
        NullInjectorError: R3InjectorError(DynamicTestModule)[HttpClient -> HttpClient]:
          NullInjectorError: No provider for HttpClient!
```

It helps?

_Originally posted by @brunoromeiro in https://github.com/angular/angular/issues/47291#issuecomment-1234567165_

**Comment by chandan-bcsg** [comment]
Any Solution to this , I am facing the same issue post upgrading from Angular 13 to  Angular 14 .

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
