### ISSUE TITLE
Angular15 - withInterceptor()

### ISSUE THREAD

**Issue by jiangyh1024** [angular/angular#48692]
### Description

withInterceptor requires a function, but the thing is I wanna use some functions in a service.

I am not sure how to inject the service into the function 

export const myInterceptor = (
    req: HttpRequest<unknown>,
     next: HttpHandlerFn
  ): Observable<HttpEvent<unknown>>  => {}

### Proposed solution

deps? LIKE

    {
      provide: APP_INITIALIZER,
      useFactory: initializeApp,
      deps: [ConfigService],
      multi: true,
    },

### Alternatives considered

use class-based interceptor  & withInterceptorFromDI()
<img width="711" alt="image" src="https://user-images.githubusercontent.com/34930870/211758946-312fe003-170e-4958-9f9b-7bd596548f2c.png">

<img width="798" alt="image" src="https://user-images.githubusercontent.com/34930870/211758987-a6a33c01-4da7-4412-80a1-42e827441347.png">

But there is description on withInterceptorFromDI method saying that withInterceptor is the recommended one

**Comment by jiangyh1024** [comment]
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/34930870/211760029-5d5a92f5-9818-4007-8112-cbdc3889f46f.png">

**Comment by aksdevac** [comment]
Not tried, but I think you should be able to use inject function inside your interceptor function (to import other service).

**Comment by pkozlowski-opensource** [comment]
Yep, the `inject` function is the way to go.

**Comment by jiangyh1024** [comment]
Thx, It's working

  const configService = inject(ConfigService);

  const messageService = inject(MessageService);
