### ISSUE TITLE
Zone doesn't support WebSockets.

### ISSUE THREAD

**Issue by davideast** [angular/angular#487]
When using WebSockets and Angular 2, Zone doesn't pick up any changes in the WebSocket callback. The code below is the work around that is needed to update the view.

Example project can be found here: [https://github.com/davideast/ng2do](https://github.com/davideast/ng2do)

```javascript
import * as ng from 'angular/angular';
import {LifeCycle} from 'core/life_cycle/life_cycle';
import {Injector} from 'di/di';

@Component({
  selector: 'my-app'
})
class MyCmp {

  constructor(injector: Injector) {

    this.todos = [];
    this.text = '';
    this.ref = new Firebase('https://<your-firebase>.firebaseio.com/test');

    // Firebase uses WebSockets to send the data down
    this.ref.on('child_added', function(snap) {
      var lifecycle = injector.get(LifeCycle);
      var todo = snap.val();
      var fireTodo = new FireTodo(new Todo(todo), snap.ref());
      this.todos.push(fireTodo);
      lifecycle.tick(); // Need to tick here to update the view
    }.bind(this));

  }

}
```

**Comment by btford** [comment]
You can track this here – https://github.com/angular/zone.js/issues/35

**Comment by mhevery** [comment]
The issue seems to be that Firebase uses WebSocket `onmessage` rather than `addEventListener` as a way to register the callback. Looking at `zone.js` I don't see where the `onmessage` is patched.

**Comment by naomiblack** [comment]
Brian has a PR for this. Looking good.
