### ISSUE TITLE
Getting NG04014 error about routing configuration although should be fine

### ISSUE THREAD

**Issue by Quake11** [angular/angular#48717]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

After migrating from Angular 13 to Angular 14 and 15, I got some strange error on navigating to dynamic lazy loaded module. Error states that this route doesn't have loadChildren when, in fact, it has loadChildren pointing to a lazy loaded module. Also there is no named outlet anywhere in the app. This code worked on Angular 13, but broke after update to 14 and 15.

Definition of routes from EventRoutingModule:

```
const routes: Routes = [
  {
    path: "",
    component: ModeratorComponent,
    children: [
      {
        path: "",
        pathMatch: "full",
        redirectTo: "event-list",
      },
      {
        path: "event-list",
        loadChildren: () =>
          import("./event-list/event-list.module").then(
            (m) => m.EventListModule
          ),
      },
      {
        path: "event/loading",
        component: EventLoadingComponent,
      },
      {
        path: "event/:eventId",
        loadChildren: () =>
          import("./event/event.module").then((m) => m.EventModule),
        canActivate: [EventStoreGuard],
        canDeactivate: [EventStoreGuard],
      },
      {
        path: "admin",
        loadChildren: () =>
          import("@moderator/admin/admin.module").then((m) => m.AdminModule),
        canLoad: [AdminGuard],
      },
    ],
  },
  {
    path: "help",
    component: ModeratorHelpComponent,
  },
];
```

### Please provide the exception or error you saw

```true
`ERROR Error: Uncaught (in promise): Error: NG04014: Invalid configuration of route 'event/:eventId/': a componentless route without children or loadChildren cannot have a named outlet set
Error: NG04014: Invalid configuration of route 'event/:eventId/': a componentless route without children or loadChildren cannot have a named outlet set`

```

![image](https://user-images.githubusercontent.com/11279501/212101005-967e2b03-7d89-442a-b01b-986807c181db.png)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.5
Node: 18.13.0
Package Manager: npm 8.19.3
OS: win32 x64

Angular: 15.0.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.5
@angular-devkit/build-angular   15.0.5
@angular-devkit/core            15.0.5
@angular-devkit/schematics      15.0.5
@angular/cli                    15.0.5
@angular/flex-layout            14.0.0-beta.41
@schematics/angular             15.0.5
ng-packagr                      15.0.3
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by Quake11** [comment]
> What are the routes in the EventModule? I’m guessing you have an empty path route in there that fails he check. This is a documented breaking change in v14. Previously, lazy loaded routes were not validated like the root routes.

routers in EventModule:

```
const routes: Routes = [
  {
    path: "",
    component: EventComponent,
    canActivate: [ParticipantsStoreGuard],
    canDeactivate: [ParticipantsStoreGuard],
    children: [
      {
        path: "choose_login_type",
        component: ChooseLoginTypePageComponent,
        canActivate: [ChooseLoginTypePageGuard],
        canDeactivate: [ChooseLoginTypePageGuard],
      },
      {
        path: "participants_settings",
        component: ParticipantsSettingsComponent,
      },
      {
        path: "workspace_settings",
        component: WorkspaceSettingsComponent,
      },
      {
        path: "",
        loadChildren: () =>
          import(
            "@moderator/event/activity-details-page/activity-details-page.module"
          ).then((m) => m.ActivityDetailsPageModule),
      },
    ],
  },
];
```

**Comment by atscott** [comment]
Aye, well let's keep going. As long as there are still empty paths, you have to go deeper. The error could be in the routes of ActivityDetailsPageModule. 

Anyhow, based on the description this is working as intended. If you believe there is a bug here, please open a new issue with a minimal reproduction.

**Comment by Quake11** [comment]
Thanks @atscott, I have found a solution. Posting it because someone would find it useful. 
I found code nested deep in a chain of lazily loaded modules that looks like this:

```
    RouterModule.forChild([
      {
        path: "",
        outlet: "something-store",
        canActivate: [SomethingStoreGuard],
        canDeactivate: [SomethingStoreGuard]
      },
    ]),
```

I changed it to this:

```
    RouterModule.forChild([
      {
        path: "",
        outlet: "moderator-store",
        canActivate: [ModeratorStoreGuard],
        canDeactivate: [ModeratorStoreGuard],
        children: [],
      },
    ]),
```

Although this is a bad architecture decision, it fixes the project for now. 

Also the error didn't help much because it doesn't indicate which routing configuration file is broken, presumably due to lazy loading or something else. I wouldn't know that I need to look deep inside nested lazy loaded modules if it wasn't for @atscott's comment. I hope this error could be improved in the future
