### ISSUE TITLE
Named router outlet separator is a reserved character

### ISSUE THREAD

**Issue by phrei** [angular/angular#48728]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

When using named router outlets, the secondary route consists of the outlet name, a colon separator and the path. [Taken from the Guide](https://angular.io/guide/router-tutorial-toh#secondary-route-navigation-merging-routes-during-navigation):

`http://…/crisis-center(popup:compose)`

My main problem is, that IIS will return a Bad Request (HTTP 400) when this route is directly navigated or refreshed as it is an invalid character. The Angular-App works perfectly if navigated on the client (via routerLink).

As far as I was able to find, the colon (":") is a reserved character in a URL [RFC 1738](https://www.rfc-editor.org/rfc/rfc1738) but seems to be permitted in query-params after the "?" (at least on IIS).

My suggestion is: Change the separator for named router outlet name and path **OR** make the separator at least configurable to something else.

I found [this resource](https://www.blinkingcaret.com/2018/04/12/iis-colon-url-angular/) to change the `UrlSanitizer` and will probably resort to this workaround but I think Angular should consider changing this.

### Please provide the exception or error you saw

```true
HTTP 400 - Bad Request
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.5
Node: 16.14.2
Package Manager: npm 8.5.0
OS: win32 x64

Angular: 13.3.6
... animations, cdk, common, compiler, compiler-cli, core, forms
... google-maps, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.4
@angular-devkit/build-angular   13.1.4
@angular-devkit/core            13.1.4
@angular-devkit/schematics      13.3.5
@angular/cli                    13.3.5
@angular/flex-layout            13.0.0-beta.38
@schematics/angular             13.3.5
rxjs                            6.6.7
typescript                      4.5.5
```

```
IIS: v1809 (Windows Server 2019)
```

**Comment by atscott** [comment]
RFC1738 is obsolete and updated by 3986. Looking at the grammar appendix in either [3986](https://www.rfc-editor.org/rfc/rfc3986#appendix-A) or [2396](https://www.rfc-editor.org/rfc/rfc2396#appendix-A), the ":" character is, in fact, valid in a path segment. 
This seems to be an IIS issue. A quick search around shows how to configure ASP.NET to allow colons in the path: https://stackoverflow.com/a/5783607

**Comment by phrei** [comment]
Well I did some "quick" searches too. As .NET-Core is used- this configuration has no effect.

**Comment by atscott** [comment]
That is unfortunate and I would suggest filing an issue with the appropriate Microsoft team since ":" absolutely is a valid character in the path. In the meantime, you already can configure the router to use a different character by implementing and providing your own [UrlSerializer](https://angular.io/api/router/UrlSerializer).
