### ISSUE TITLE
Shared services data is not maintain when reload the browser in Angular

### ISSUE THREAD

**Issue by sivakuber** [angular/angular#48729]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

While reloading the browser of my angular application my shared services data is get cleared. I don't want to use sessionstorage or localstorage for storing the data. But I used Ngrx storage , it's also not maintain the state. Is there any alternative solution to maintain the shared data while refresh the browser.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
