### ISSUE TITLE
Cannot use `attr.disabled` and `ngModel` together to disable fields [ng15]

### ISSUE THREAD

**Issue by juanmendes** [angular/angular#48737]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

Starting in Angular 15, an input field will not be disabled when using  `[attr.disabled]="true" [(ngModel)]="someValue"` when first rendered

We're [using this feature](https://github.com/vmware/vmware-cloud-director-ui-components/blob/master/projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.html#L17-L26) and caught this while updating https://github.com/vmware/vmware-cloud-director-ui-components to ng 15 from [one of our unit tests](https://github.com/vmware/vmware-cloud-director-ui-components/blob/master/projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.spec.ts#L311-L318). Initially, I naively used `[disabled]="shouldBeDisabled"` and it fixed this case but broke[ a bunch of other cases](https://github.com/vmware/vmware-cloud-director-ui-components/blob/master/projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.spec.ts#L320-L325).

It works in [Angular 14](https://stackblitz.com/edit/ng-14-attr-disabled-ngmodel?file=src%2Fapp%2Fapp.component.ts,src%2Fmain.ts) but does not work in [Angular 15](https://stackblitz.com/edit/ng-15-attr-disabled-ngmodel?file=src%2Fmain.ts)

The following code will not disable the text input

```
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `<input [attr.disabled]="true"  [(ngModel)]="myName" /> `,
})
export class AppComponent {
  myName = 'Angular';
}
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/ng-15-attr-disabled-ngmodel?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
The input field does not become disabled. If I toggle its disabledness after rendering, it will work.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Replicated in a simple stackblitz ng 15 starter. Proved that it worked in an ng 14 version.
```

```
[@angular/animations](https://www.npmjs.com/package/@angular/animations)
15.1.0-next.2

[@angular/common](https://www.npmjs.com/package/@angular/common)
15.1.0-next.2

[@angular/compiler](https://www.npmjs.com/package/@angular/compiler)
15.1.0-next.2

[@angular/core](https://www.npmjs.com/package/@angular/core)
15.1.0-next.2

[@angular/forms](https://www.npmjs.com/package/@angular/forms)
15.1.0-next.2

[@angular/platform-browser](https://www.npmjs.com/package/@angular/platform-browser)
15.1.0-next.2

[@angular/platform-browser-dynamic](https://www.npmjs.com/package/@angular/platform-browser-dynamic)
15.1.0-next.2
```

**Comment by JeanMeche** [comment]
Hi, there is already an open issue about this : #48350

**Comment by juanmendes** [comment]
@JeanMeche  I'm not sure that's a better issue. That one is complaining about using `formControlName"` In that case, you shouldn't even be using `[attr.disabled]`, you should be using the reactive form control. I think this is a better issue description of a valid use case, I'm implementing my own `ControlValueAccessor`.

Notice that a lot of the chatter is about the message about how you should be using `formControl.disable()`

**Comment by JeanMeche** [comment]
My bad, for your case I think it's about [this breaking change](https://angular.io/guide/update-to-version-15#setdisabledstate-is-always-called-when-a-controlvalueaccessor-is-attached) brought by #47576. 

The fix is to import the `ReactiveFormsModule` with a config in your module. 

```
ReactiveFormsModule.withConfig({
      callSetDisabledState: 'whenDisabledForLegacyCode',
    }),
```

**Comment by juanmendes** [comment]
Woo hoo! Fixes my problem! I thought it would end up breaking other tests but they all pass.  I remembered seeing that breaking change but didn't realize it was the cause of my problem. Thanks.

**Comment by dylhunn** [comment]
Thanks for your reproduction @juanmendes. This turned out to be a much more impactful change than I realized. The solution _is_ to opt out, and I'm going to follow up with some fixes and a post explaining the nature of the breaking change.
