### ISSUE TITLE
Dot before brackets in a template expression

### ISSUE THREAD

**Issue by adamdport** [angular/angular#48736]
### Describe the problem that you experienced

Angular's form validation docs have the following code example:

```
  <div *ngIf="name.errors?.['required']">
    Name is required.
  </div>
```

Syntax like `name.errors?['required']` I've seen, makes sense.

Syntax like `name.errors?.required` I've seen, makes sense.

Combining the dot with the bracket `name.errors?.['required']"` I haven't seen. It doesn't appear to be valid Javascript, `Uncaught SyntaxError: Unexpected token '['`. 

### Enter the URL of the topic with the problem

https://angular.io/guide/form-validation

**Comment by JoostK** [comment]
[It is valid JavaScript since ES2019](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).
