### ISSUE TITLE
unit testing components with styleUrls fails

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#4873]
It looks like when I try to run a test on a component that has `styleUrls`:
```js
@Component({
	selector: 'glyph',
	encapsulation: ViewEncapsulation.Emulated, // ViewEncapsulation.Emulated, ViewEncapsulation.Native, ViewEncapsulation.None (default)
	template: '',
	styleUrls: [
		'app/components/glyph/glyph.css'
	],
	inputs: [
		'src'
	]
})
```
It [fails](https://travis-ci.org/rolandjitsu/ng2-lab#L662) because it tries to load `app/components/glyph/glyph.css`. Is this expected behaviour and if so is there any way I can avoid this?

The [spec](https://github.com/rolandjitsu/ng2-lab/blob/master/src/app/components/glyph/glyph.spec.ts) has nothing special as I just have a dummy test component:
```js
@Component({
	selector: 'glyph-test'
})
@View({
	template: `<glyph src="glyph.svg"></glyph>`,
	directives: [
		Glyph
	]
})
class GlyphTest {
	glyphs;
	constructor(@Query(Glyph) glyphs:QueryList<Glyph>) {
		this.glyphs = glyphs;
	}
}
```
and during the `it` I create the component using `TestComponentBuilder`:
```js
tcb
	.createAsync(GlyphTest)
	.then((rtc: RootTestComponent) => {});
```

**Comment by rolandjitsu** [comment]
@gdi2290 do you have any input on this? Should I fake the element and not include the styles.

**Comment by juliemr** [comment]
This should work as long as you are serving the css correctly in karma (or whatever your test runner is).
