### ISSUE TITLE
ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by DaSchTour** [angular/angular#48748]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

This PR  #48256 introduce the usage of native TextEncoder and thereby changed the angular dependencies. When using jest with jsdom this seams to breaks unit-tests because TextEncoder is not available in this environment.

**Comment by alan-agius4** [comment]
`TextEncoder` is a standard API which is supported by all browsers and Node.js version that Angular support.

In this case the problem is that JSOM does not yet support  this standard API. There is an open issue which was opened a couple of years ago to add support but has not been actioned. See: https://github.com/jsdom/jsdom/issues/2524

Unfortunately, this is not really actionable from our end.

**Comment by DaSchTour** [comment]
@alan-agius4 yes I know. I just wanted to raise awareness and document this problem. As with 15.1 I have the impression a lot of breaking changes were introduced. There was also another issue with the isStandalone() that is used in ngneat/spectator: https://github.com/ngneat/spectator/issues/598

I hope by documenting this issue the angular team will get a bit more cautious about the impact on their eco-system.

**Comment by alan-agius4** [comment]
The mentioned issued in https://github.com/ngneat/spectator/issues/598 is caused as that mentioned library was using private APIs. 

Such APIs can change without warning in any version.

This change is a refactor, as such it was not part of the changelog. `TextEncoder` APIs are supported by all platforms versions (Node and Browser) that Angular official supports.

**Comment by DaSchTour** [comment]
@alan-agius4 I understand what you are saying. Still it's frustrating when angular team breaks the ecosystem within a patch or minor release. I still remember the update from angular 13.0.2 to 13.0.3 which also broke testing tools as documented in https://github.com/help-me-mom/ng-mocks/issues/1427 and https://github.com/angular/angular/issues/44629

**Comment by Timebutt** [comment]
For other people looking for a workaround, you can use the below code snippet to polyfill `TextEncoder` and `TextDecoder` in a `jsdom` like environment (in my case I had to add this to `setupJest.ts`):

```
import { TextEncoder, TextDecoder } from 'util'
global.TextEncoder = TextEncoder
global.TextDecoder = TextDecoder
```

**Comment by DaSchTour** [comment]
@Timebutt I have used the following as this solution didn't work for me
```ts
import { TextEncoder } from 'util';

Object.defineProperty(window, 'TextEncoder', {
    writable: true,
    value: TextEncoder,
  });
```

TextDecoder is actually not needed. And I wrapped it into a function because I had to add it to multiple projects in a monorepo.

**Comment by TomONeill** [comment]
Super frustrating that this happened in a minor/patch.
Our jest unit tests fail on components that make use of `i18n` in `.html` files.
