### ISSUE TITLE
Is it possible to use a simple way to pass data in ng-content area?

### ISSUE THREAD

**Issue by diuming** [angular/angular#48743]
### Is this a bug report or a feature request?

- [ ] Bug Report
- [X] Feature Request

### Description [Feature Request only]

How do I pass data in `content area` in app.component.html?
I try @ViewChild, local reference, TemplateRef, ElementRef and ComponentRef and more... But did not succeed.
Is it a simple way to pass data into ToolbarComponent.title? like
![Screenshot 2023-01-16 at 11 20 47 AM](https://user-images.githubusercontent.com/39903550/212592195-b14a3f36-2c95-411a-b1a1-93e8b59edc96.png)

thanks

### Toolbar.component.html
```
<div>
  <div>{{ title }}</div>
  <ng-content></ng-content>
</div>
```

### Toolbar.component.ts
```
@component({
  selector: 'my-toolbar'
})
export class ToolbarComponent {
  @Input() title: string;
}
```

### app.component.html
```
<my-toolbar #mmyytoolbar>

  <!-- It's content area and there are a lot of conditions -->

  <ng-container #ngIf="....">
    <ng-container mmyytoolbar.title="Hello Toolbar0"></ng-container>
  </ng-container>

  <ng-container #ngIf="....">
    <ng-container mmyytoolbar.title="Hello Toolbar1"></ng-container>
  </ng-container>
  .
  .
  .
</my-toolbar>
```

**Comment by jessicajaniuk** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
