### ISSUE TITLE
Angular 15 : Class is using Angular features but is not decorated. Please add an explicit Angular decorator.(-992007)

### ISSUE THREAD

**Issue by CodAffection** [angular/angular#48741]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I'm using Angular 15. Created a new Angular component as follows.
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-foo',
  templateUrl: './foo.component.html',
  styleUrls: ['./foo.component.css']
})
export class FooComponent {

}
```
So far no problem, When I implement the OnInit interface,
```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-foo',
  templateUrl: './foo.component.html',
  styleUrls: ['./foo.component.css']
})
export class FooComponent implements OnInit {

  ngOnInit(): void {

  }

}
```
I'm getting the following error.

> Class is using Angular features but is not decorated. Please add an explicit Angular decorator.(-992007)

### Please provide the exception or error you saw

Class is using Angular features but is not decorated. Please add an explicit Angular decorator.(-992007)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.1
Node: 18.13.0
Package Manager: npm 9.1.3
OS: win32 x64

Angular: 15.1.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.1
@angular-devkit/build-angular   15.1.1
@angular-devkit/core            15.1.1
@angular-devkit/schematics      15.1.1
@angular/cli                    15.1.1
@schematics/angular             15.1.1
rxjs                            7.8.0
typescript                      4.9.4
```

**Comment by JoostK** [comment]
This seems to be the output of the language service in an IDE, not the execution result of `ng build`/`ng serve`. Which version of the Angular plugin are you using?

**Comment by CodAffection** [comment]
@JoostK , Thanks for the comment.

After disabling the vs code extension. 'Angular Language Service', problem fixed!.
