### ISSUE TITLE
Angular is not accepting special character inside a string type query parameter

### ISSUE THREAD

**Issue by sayedsadat344** [angular/angular#48754]
### Description

I have an API `that` needs a string-type query parameter i.e.  `http://localhost:8282/api/task/T#0000007427`.
However, angular is parsing this API call as  `http://localhost:8282/api/task/T` only.

### Proposed solution

It has to accept the string as a whole string, which is  `http://localhost:8282/api/task/T#0000007427`

### Alternatives considered

.....

**Comment by JoostK** [comment]
The `#` character has a special meaning in an URL where it is the start of the _fragment_ part. You'll have to URL-encode the path segment to convert the `#` symbol into a percent-encoded sequence.
