### ISSUE TITLE
Angular in iframe is not detected

### ISSUE THREAD

**Issue by DavidMaximaWang** [angular/angular#48760]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I got "Angular application not detected" when I use angular inside iframe

**Comment by walidBouguima** [comment]
Please provide specific context and reproduction details. It is not enough to open an issue with a book title.

**Comment by walidBouguima** [comment]
Please provide context/environment specification and reproduction details including a link to [stackblitz](https://stackblitz.com/). 
It is neither enough nor helpful for you to open an issue with a book-title. 
+The title itself does not make much sense.

**Comment by JeanMeche** [comment]
He's talking about the Angular DevTools extension which displays this error when it can't find an app. 

Why wouldn't you inspect the content of the iFrame directly ?

**Comment by DavidMaximaWang** [comment]
When a button clicked, my app has iframe to load the angular app, then I got 
`ng-validate.ts:26 Uncaught Error: Extension context invalidated.
    at ng-validate.ts:26:20` repeat for ever.

**Comment by DavidMaximaWang** [comment]
> Why wouldn't you inspect the content of the iFrame directly ?

How can I do this?
I did something like close the chrome devtools and then reopen it, click the "Angular" tab in the devtools, then I got  "Angular application not detected."

**Comment by nihiluis** [comment]
@DavidMaximaWang did you find a solution for this?

**Comment by JeanMeche** [comment]
I'll close this as we landed #53934
