### ISSUE TITLE
Bug in ngClass klass property

### ISSUE THREAD

**Issue by PetrJajtner** [angular/angular#48779]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

The setter of ngClass directive named klass accepts value of type string but transpiled code checks only `null` and not `undefined` on https://github.com/angular/angular/blob/main/packages/common/src/directives/ng_class.ts line 77 (committed 5f21c6d on Dec 9, 2022).

`this.initialClasses = value != null ? value.trim().split(WS_REGEXP) : EMPTY_ARRAY;`

Some libraries (especially PrimeNG) sets the initial value to `undefined` and therefore the app is crashing. Is it possible to check parameter `value` explicitly for string type (like ngClass property)?

`typeof value === 'string' ? value.trim().split(WS_REGEXP) ...`

Thanks in advance.

### Please provide a link to a minimal reproduction of the bug

https://pj-angular-ngclass-setting-bug.stackblitz.io

### Please provide the exception or error you saw

```true
ERROR TypeError: value.trim is not a function
    Angular 5
        set klass
        setInputsForProperty
        setDirectiveInputsWhichShadowsStyling
        checkStylingMap
        classMap
    Overlay_div_0_Template ɵcmp.js:75
    Angular 23
        executeTemplate
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.2
Node: 16.18.0
Package Manager: npm 9.3.1
OS: win32 x64

Angular: 15.1.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.2
@angular-devkit/build-angular   15.1.2
@angular-devkit/core            15.1.2
@angular-devkit/schematics      15.1.2
@angular/cli                    15.1.2
@schematics/angular             15.1.2
rxjs                            7.8.0
typescript                      4.9.4
```

**Comment by pkozlowski-opensource** [comment]
It is something that needs to be fixed on the PrimeNG side, see https://github.com/primefaces/primeng/issues/12525#issuecomment-1397543514
