### ISSUE TITLE
Docs: .png images are broken in StackBlitz live samples

### ISSUE THREAD

**Issue by OnkarRuikar** [angular/angular#48773]
### Describe the problem that you experienced

Live samples deployed on StackBlitz have broken `.png` images.

Steps to reproduce:
1. Open page https://angular.io/guide/property-binding
2. Open the live sample link on the page: https://angular.io/generated/live-examples/property-binding/stackblitz.html
3. Let StackBlitz install and run the code
4. In the output you'll see broken images:
![aio_bug](https://user-images.githubusercontent.com/87750369/213392513-bb126d26-d45d-49da-b7f7-05f04f2ed79d.png)

I think following code for Plunker still remained in StackBlitz builder, which is causing the issue:
https://github.com/angular/angular/blob/9e1e5ccdfe1f25a9995f70e3c64ae72551af7562/aio/tools/stackblitz-builder/builder.mjs#L185-L187
The code converts and renames all `.png` files. I think all the live samples on StackBlitz show broken images.

### Enter the URL of the topic with the problem

https://angular.io/guide/property-binding

### Describe what you were looking for in the documentation

Live samples working out of the box.

### Describe the actions that led you to experience the problem

Run live samples containing `.png` images on StackBlitz.

### Describe what you want to experience that would fix the problem

Stop converting to base64. These demos need simple images.
The [offline downloadable code](https://angular.io/generated/zips/property-binding/property-binding.zip) uses original normal images.

**Comment by JeanMeche** [comment]
I just tried to remove the base64 but that break the upload of binary images as [dynamicaly created project don't support binary files](https://developer.stackblitz.com/platform/api/post-api).

We'll have to use svg images to fix this.

**Comment by OnkarRuikar** [comment]
> We'll have to use svg images to fix this. (I count 9 png in example assets).

We have to convert only these images:
```
aio/content/examples/ajs-quick-reference/src/assets/images/hero.png
aio/content/examples/ajs-quick-reference/src/assets/images/ng-logo.png
aio/content/examples/ajs-quick-reference/src/assets/images/villain.png
aio/content/examples/interpolation/src/assets/lamp.png
aio/content/examples/interpolation/src/assets/potted-plant.png
aio/content/examples/property-binding/src/assets/phone.png
aio/content/examples/template-syntax/src/assets/images/hero.png
aio/content/examples/template-syntax/src/assets/images/ng-logo.png
aio/content/examples/template-syntax/src/assets/images/villain.png
```

We could use open source [png2svg tools](https://github.com/xyproto/png2svg) to convert the same images.
