### ISSUE TITLE
$any() type cast function

### ISSUE THREAD

**Issue by filipvh** [angular/angular#48781]
### Describe the problem that you experienced

Normally you try to avoid function/method calls when inside the template (with exception being in the action expression) because angular cannot know for sure the function/method is pure. For that reason it is preferred to use a pipe where one needs to keep it pure or define it is not.

In this documentation the $any() function is called. It is not indicated if this will have any effect on performance, as it seems to have the issue I talk about in the paragraph above. OR is this a "special method" where angular knows it pure and thus has no impact on performance.

### Enter the URL of the topic with the problem

https://angular.io/guide/template-expression-operators#any-type-cast-function

### Describe what you were looking for in the documentation

An indication if (or not) using this method has impact on performance due to it being a method vs. a pipe.

**Comment by JoostK** [comment]
There is no method call in the generated code; the `$any` function is entirely compiled away.

**Comment by filipvh** [comment]
@JoostK  @JeanMeche 
Thanks for the quick response/action!
