### ISSUE TITLE
[Question] TemplateNormalizer & CSS order

### ISSUE THREAD

**Issue by vicb** [angular/angular#4879]
The `TemplateNormalizer` parses styles and push non-resolvable external style sheets to `styleUrls`.

With `styles = ['a{}', '@import "/b.css" c{}']` (b.css contains `b {}`), the final order will be a, c, b (or may be b, a, c - didn't check what goes first).

I think this could cause issues are styles are order sensitive?

**Comment by tbosch** [comment]
According to MDN, `@import` rules need to precede all other rules (see [here](https://developer.mozilla.org/en-US/docs/Web/CSS/@import)). So we should change our current implementation to do the same, i.e. the oder of the example above should be `b, a, c`. I think right now we have the opposite, but am not sure.

**Comment by vicb** [comment]
> `@import` rules need to precede all other rules

I understand it as: in a stylesheet there could be no `@import` rule after any other type of rule which is the case in my example above. Still the expected order is a, b, c.

**Comment by splincode** [comment]
@vicb Is the issue relevant?
