### ISSUE TITLE
Support passing image transformation via query parameters in Image directive via ImageKit loader

### ISSUE THREAD

**Issue by exequiel09** [angular/angular#48800]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

Currently, the ImageKit loader for the `NgOptimizedImage` directive passes transformation in the middle of the URL which is the default way of providing transformation parameters in ImageKit:

https://github.com/angular/angular/blob/b6e3840ed4f52b1fcf564cec642e63ddf358aab8/packages/common/src/directives/ng_optimized_image/image_loaders/imagekit_loader.ts#L43-L49

But, ImageKit also supports passing transformation parameters in the query parameters. Reference: https://docs.imagekit.io/features/image-transformations/resize-crop-and-other-transformations#example-all-padding-on-one-side

I think if we support the query parameter version of ImageKit, developers who use ImageKit would be able to add more transformations via query URL and just add the width by default via the loader function just like what ImgIX loader does.

https://github.com/angular/angular/blob/b6e3840ed4f52b1fcf564cec642e63ddf358aab8/packages/common/src/directives/ng_optimized_image/image_loaders/imgix_loader.ts#L40-L45

### Proposed solution

Support both ways of providing transformation parameters in URL path or query parameter. I also tested, using both query and path part in an image and it doesn't work. So just give the developer the option to use one of the two via configuration options.

### Alternatives considered

For now, just create custom loader for ImageKit that passes transformation via query parameters

**Comment by atcastle** [comment]
I'm starting work on an enhancement to the ngOptimizedImage API that will give it a lot more flexibility: #48826  It doesn't directly address this issue, but will be an important first step.

**Comment by exequiel09** [comment]
Already done in #48907. Also it's backported to v14.3
