### ISSUE TITLE
Dependency @angular/build-tooling points on a non-public commit

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular#48808]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Description

While running unit tests of `compiler-cli`, I stumbled upon the following problem : 

```
error Couldn't find match for "c70bd1895ed5b95dc97cb57f3ef2a0f045d1700c" in "refs/heads/main" for "https://github.com/angular/dev-infra-private-build-tooling-builds.git".
```

That's due to the devDependency @angular/build-tooling" pointing on ` "https://github.com/angular/dev-infra-private-build-tooling-builds.git#c70bd1895ed5b95dc97cb57f3ef2a0f045d1700c"` where `c70bd1895ed5b95dc97cb57f3ef2a0f045d1700c` is not a public commit. 

Is there a solution for this ?

**Comment by JoostK** [comment]
Some commits have been removed from the build snapshot repository out of an abundance of caution due to a CircleCI security incident that happened over Christmas.

You'll have to fix your Yarn cache using

```
rm -Rf $(yarn cache dir)/.tmp
```

to clear its Git caches.

**Comment by JeanMeche** [comment]
Awesome thanks !
