### ISSUE TITLE
Can't get queryParams current value in resolver

### ISSUE THREAD

**Issue by matthieu-hm** [angular/angular#48810]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

Assuming this code:
```ts
export class GetQueryParamsResolver implements Resolve<any> {
  constructor(private route: ActivatedRoute) {}

  resolve(): Observable<any> {
    return this.route.queryParams.pipe(
      tap((params) => console.log(params)),
    );
  }
}
```
- On app init, no matter if there  is or not queryParams in the URL the console.log is always an empty object.
- When navigating with routerLink the console.log is the previous value

exemple:
```
http://localhost:4200/?page=3 // --> {}                 // should be { page: 3 }
http://localhost:4200/?page=1 // --> { page: 3 }        // should be { page: 1 }
http://localhost:4200/?page=2 // --> { page: 1 }        // should be { page: 2 }
http://localhost:4200/?page=3 // --> { page: 2 }        // should be { page: 3 }
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-klmdzz?file=src/app/resolvers/get-query-params.resolver.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.2
Node: 18.13.0
Package Manager: npm 8.19.3
OS: linux x64

Angular: 15.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.2
@angular-devkit/build-angular   15.1.2
@angular-devkit/core            15.1.2
@angular-devkit/schematics      15.1.2
@angular/cli                    15.1.2
@schematics/angular             15.1.2
rxjs                            7.8.0
typescript                      4.9.4
```

**Comment by jnizet** [comment]
Hi.

The `resolve()` method declared in the `Resolve<T>` interface takes an ActivatedRouteSnapshot as argument. You can get the current value of the query parameters from there.

**Comment by matthieu-hm** [comment]
Hi

Ok I didn't know, thank you!
