### ISSUE TITLE
Angular template optional null operator false positive ngtsc 2532

### ISSUE THREAD

**Issue by pmoleri** [angular/angular#48821]
### Which @angular/* package(s) are the source of the bug?

compiler, language-service

### Is this a regression?

No

### Description

After using optional chain operator and reading a nested property I get a false error in the template:

```
interface SomeType {
  a: {
    b: string;
  };
}

@Component(...)
class Component {
    prop?: SomeType = { a: { b: "Me" } };
}

<p>{{ prop?.a.b }}</p>
              ^ error TS2532: Object is possibly 'undefined'.
```

<details>
   <summary>see screen capture -></summary>

![image](https://user-images.githubusercontent.com/12942794/214333552-dec30e7e-4b9e-4321-a4bd-0caf6db8c02e.png)
</details>

### Please provide a link to a minimal reproduction of the bug

https://github.com/pmoleri/angular-ngtsc-2532

### Please provide the exception or error you saw

```true
Error: src/app/app.component.html:2:15 - error TS2532: Object is possibly 'undefined'.

2 <p>{{ prop?.a.b }}</p>
                ~

  src/app/app.component.ts:11:16
    11   templateUrl: './app.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.
```
```


### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.2
Node: 16.15.1
Package Manager: npm 8.11.0
OS: win32 x64
@angular-devkit/architect       0.1501.2
@angular-devkit/build-angular   15.1.2
@angular-devkit/core            15.1.2
@angular-devkit/schematics      15.1.2
@angular/cli                    15.1.2
@schematics/angular             15.1.2
rxjs                            7.8.0
typescript                      4.9.4
```

**Comment by JeanMeche** [comment]
Hi, there is already an opened issue about this :  #37619

**Comment by pmoleri** [comment]
Thanks @JeanMeche I failed to find it, I guess I focused my search on the error code `2532` which wasn't mentioned.
