### ISSUE TITLE
Lazy Loading the Animations Module does not work

### ISSUE THREAD

**Issue by davidstellini** [angular/angular#48836]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

No

### Description

I'm trying to lazy load the angular animations module, as it's not necessary for the app bootstrap, it increases the main.js size, and also adds a lot of javascript to the app that is not necessary for the first page load.

I tried doing this at a later point:

```
    const { BrowserAnimationsModule } = await import('@angular/platform-browser/animations');
    const mapModuleRef =  createNgModuleRef(BrowserAnimationsModule, injector);
```

I don't get any errors but the animations don't seem to play.

Is there any way to lazy load the animations module?

### Please provide the exception or error you saw

```true
No errors, but animations don't work.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 15.1.0
```

**Comment by JeanMeche** [comment]
Hi, did you have a look at #38982 ? 

Since V14.2 there is [provideAnimations](https://angular.io/api/platform-browser/animations/provideAnimations).

**Comment by davidstellini** [comment]
Thanks for that! However I see the example in the docs is loading this before bootstrap though. 
I'm still not entirely sure how to treeshake all of the animations code out of the main.js entirely and have it loaded at runtime.

For example these imports alone:

```
import {
  animate,
  animateChild,
  group,
  query,
  style,
  transition,
  trigger,
} from "@angular/animations";
```

Are adding 30kb to main.js. There is then another problem: if I had to lazy load these, I would need to add them to the component   `animations: [],` at runtime. Is there a way to do that?

**Comment by jessicajaniuk** [comment]
I'm going to close this as the proper way to do this is through the `provideAnimations` method that was mentioned earlier. Those imports are necessary for animations to work, and unfortunately there is no way to lazy load them individually.
