### ISSUE TITLE
[Question] Support for media queries in the style compiler

### ISSUE THREAD

**Issue by vicb** [angular/angular#4884]
The `TemplateNormalizer` push the content of any `<style>` tag to the `styles` List discarding any `media` attribute (the same applies to `<link rel="stylesheet">`).

I guess we want to add support for that ?

This would need some thinking wrt to `@import` rules (i.e. it would not be possible to only add them to `styleUrls` when a media query applies).

**Comment by vicb** [comment]
see https://plnkr.co/edit/M6JnmnNfoy4XwE3AYwo0

**Comment by splincode** [comment]
@vicb Is the issue relevant?

**Comment by jelbourn** [comment]
Duplicate of #6513 (choosing that one since it has more activity)
