### ISSUE TITLE
Angular DevTools Firefox extension breaks XML rendering

### ISSUE THREAD

**Issue by mzatko** [angular/angular#48852]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

install Angular DevTools extension in Firefox and enable it
open any XML(,WSDL,XSD,...) file from web
XML tree is not renderend, only #text elements concatenated are shown

disable Angular DevTools extension
XML tree is renderend correctly (as before Angular DevTools extension was installed)

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

no impact of Angular DevTools to XML tree rendering

**Comment by JoostK** [comment]
Duplicate of #48017.

**Comment by JeanMeche** [comment]
@JoostK Do you maybe now how to release a new version ?

**Comment by JoostK** [comment]
I do not; @AleksanderBodurri might

**Comment by JeanMeche** [comment]
@mzatko  The extension has been updated on Feb 16th ! The fix should be included.
