### ISSUE TITLE
router: URParser.parseParam does not decode key/value

### ISSUE THREAD

**Issue by Krustie101** [angular/angular#4886]
When we have a router link with a query parameter value that contains a space, e.g. hotel="Jurys Inn Dublin Christchurch", the value is properly encoded in the query string:

http://localhost:8080/app/root/reservation/criteria?hotel=Jurys%20Inn%20Dublin%20Christchurch

But when we navigate to this url via the browser address bar, the hotel  parameter is not decoded to 
"Jurys Inn Dublin Christchurch" but stays "Jurys%20Inn%20Dublin%20Christchurch"

**Comment by vicb** [comment]
related to the old router
