### ISSUE TITLE
[Docs] Potential UI/UX issue with edit button

### ISSUE THREAD

**Issue by ghost** [angular/angular#48865]
### Describe the problem that you experienced

Some Angular contributors, including me, have had trouble finding the "edit on GitHub" pencil button on the upper-right corner of the docs. The reason why that button is hard to find is because the button gets hidden when the user scrolls down, and the button blends in very well to the rest of the page, meaning that the user has to be actively looking for the button, which can be hard for people, including me, with low vision or who are legally blind.

### Enter the URL of the topic with the problem

https://angular.io/docs

### Describe the actions that led you to experience the problem

I found a typo in the CLI Builder docs (see PR #48129), and I was having trouble finding the edit button. Because I knew that some libraries and frameworks put their edit links at the bottom of the page, I scrolled down to there; I found nothing, so I scrolled all the way to the top where I found the small, pencil-shaped button. Essentially, I had to find a needle in the haystack, and I found a broken affordance.

### Describe what you want to experience that would fix the problem

I know that Angular can do better with its docs with better utilization of Angular Material. I know that UIs written in Material are of high quality because I have interacted with Google's G Suite apps, including Gmail, Docs, Sheets, and Slides, since 2019. Although there are many ways to update the UI, I would like to give the following suggestions:

1. Make the button's position fixed relative to the browser window; this will make the button easier to see no matter where the user is at on the page.
2. Either add a shadow, an outline, or a contrasting fill to the button for better visibility.
3. Use transitions, animations, and/or structural directives to make the button more noticeable.

**Comment by munierujp** [comment]
FYI: Other library documentation is more explicit, with text links such as "Edit this page".

- https://reactjs.org/docs/getting-started.html
  <img width="352" alt="スクリーンショット 2023-01-27 22 54 14" src="https://user-images.githubusercontent.com/20086673/215103606-b623a41d-ec23-4b4b-86ae-b263ebb8efed.png">
- https://vuejs.org/guide/introduction.html
  <img width="209" alt="スクリーンショット 2023-01-27 22 54 22" src="https://user-images.githubusercontent.com/20086673/215103634-555cd358-f6b9-4202-8103-d6309c81144e.png">

However, this may not be like material design 😅

**Comment by IRod22** [comment]
@munierujp, I think we should continue this conversation in angular/angular-ja#293 while the Angular core team works on more important issues. In the meantime, we can discuss this with other Japanese Angularists; that way, we have many options to choose from and discuss those options with the rest of the Angular community when the core team is ready. What do you think?

**Comment by JeanMeche** [comment]
I'll close this as the button was remove from AIO because it is now in maintenance mode.
