### ISSUE TITLE
ReferenceError: Cannot access 'x' before initialization caused by missing HttpClientModule import

### ISSUE THREAD

**Issue by alvipeo** [angular/angular#48870]
### Description

I just spent an hour researching on a __weird__ bug. I have an app with a just common lazy loaded module which uses HttpClientModule (and HttpClient). While it compiles and works locally (!), when I deploy it and go to that specific route __*nothing happens*__. I mean you click on a button but really nothing happens. There are no errors in the console either!

It's good I have a global error handler which logs all of the errors. So, I found out the error was:
> Error: Uncaught (in promise): ReferenceError: Cannot access 'P' before initialization

First, I thought I had a cyclic reference somewhere... so I checked everything and no, I didn't have it. Then I just added HttpClientModule to my module's `imports` and published the app again. Voila! It works now!

I have to add my app uses i18n, so I build it for different languages. And for default locale it works, but for others it DOES NOT.

### Proposed solution

This must be reported at least in the console. But it better be handled during compilation.

Well, it must be reported SOMEWHERE.

Angular CLI: 15.1.3
Node: 18.13.0
Package Manager: npm 9.4.0
OS: win32 x64

Angular: 15.1.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.3
@angular-devkit/build-angular   15.1.3
@angular-devkit/core            15.1.3
@angular-devkit/schematics      15.1.3
@angular/cli                    15.1.3
@schematics/angular             15.1.3
rxjs                            7.8.0
typescript                      4.9.4

### Alternatives considered

.

**Comment by JoostK** [comment]
Please share a reproduction showcasing this issue, as without one this won't be actionable.

**Comment by alvipeo** [comment]
I can share a private project. Would that work for you?

**Comment by JoostK** [comment]
I'm afraid that it would be too large to analyze; I'd be best if this can be reproduced using a minimal reproduction.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
