### ISSUE TITLE
No provider for HighContrastModeDetector when using JIT compiler at runtime

### ISSUE THREAD

**Issue by hannoquest** [angular/angular#48885]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

I have a simple HTML string which I want to compile to an Angular component:

``` html
<button mat-button>Hello!</button>
```

I am trying to use the JIT compiler to do this:

``` ts
const tmpCmp = Component({ template: html })(class {});

const hostedComponent = this.viewContainerRef.createComponent(tmpCmp, {
    ngModuleRef: createNgModule(TestModule)
});
```

Running this code generates the error.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-5agqzt

### Please provide the exception or error you saw

```true
ERROR: NullInjectorError: NullInjectorError: No provider for HighContrastModeDetector!
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.10
Node: 14.21.1
Package Manager: npm 6.14.17 
OS: win32 x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms     
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------    
@angular-devkit/architect          0.1402.10
@angular-devkit/build-angular      14.2.10
@angular-devkit/core               13.3.8
@angular-devkit/schematics         13.3.8
@angular/cdk                       14.2.7
@angular/cli                       14.2.10
@angular/material                  14.2.7
@angular/material-moment-adapter   14.2.7
@schematics/angular                14.2.10
ng-packagr                         14.2.2
rxjs                               6.5.5
typescript                         4.6.4
```

**Comment by JoostK** [comment]
The problem occurs for `createNgModule(TestModule)`, because `TestModule` imports `MatTabsModule` which requires some a11n services to be available. However, the created instance of `TestModule` is completely independent from the root injector, so those services are not visible to it and hence instantiating the NgModule that requires those services will fail.

By using `createNgModule(TestModule, this.viewContainerRef.injector)` or some other parent injector you do get access to the root injector, resolving the issue.

**Comment by hannoquest** [comment]
Thank you, @JoostK !
Amended the code sample. There is now another problem: Using `*ngIf` in the template string results in the error message:
`Can't bind to 'ngIf' since it isn't a known property of 'div'.
If the 'ngIf' is an Angular control flow directive, please make sure that either the 'NgIf' directive or the 'CommonModule' is a part of an @NgModule where this component is declared.`

This is even though the `TestModule` imports `CommonModule`.

**Comment by JoostK** [comment]
But `TestModule` doesn't declare your component, so the component doesn't have any compilation scope.

**Comment by JoostK** [comment]
You'll likely benefit from marking the test component as `standalone: true` and then managing its imports using `Component.imports`. Standalone components have been designed to avoid some of the pitfalls you're running into with NgModules.

**Comment by JeanMeche** [comment]
Are you sure ? I just ran the stackblitz and I see no errors. 

Btw beware of having dynamic templates/creating the components on the fly, you'll need to ship the JIT compiler in your build.
