### ISSUE TITLE
When using * syntax for <template> directives, inputs also require *

### ISSUE THREAD

**Issue by endash** [angular/angular#4888]
I'm not sure if this is intentional, but this took me a while to puzzle out. I looked for an issue on the topic and found none. Demonstration plunker: http://plnkr.co/edit/YfCiTSnPdSARGwqJ7ifT?p=preview

Basically, when you use

```
<my-component *my-directive></my-component>
```

instead of

```
<template my-directive>
    <my-component></my-component>
</template>
```

any additional inputs also have to be prefaced with `*`:

```
<my-component *my-directive *my-directive-input="something"></my-component>
```

Additionally, the values are bound expressions by default without having to use `[prop]` binding syntax. 

This is in several ways counterintuitive.

**Comment by pkozlowski-opensource** [comment]
@endash this is an interesting one and IMO the example you've got in plunker better illustrates what is going on here. 

So let's say we've got this example: `<foobar *foo="7" [bar]="bar"></foobar>`. If you look closely at it you will see that there are 2 ways of de-sugarring it:
* `<template foo="7" [bar]="bar"><foobar></foobar></template>`
* `<template foo="7"><foobar [bar]="bar"></foobar></template>`

Which one should we choose? It doesn't make sense to take any arbitrary decisions here, this is why you should go with a de-sugared version here.

The only pb I can see is that we don't throw when we see several `*` on the same element, but I think that we've got an issue for this already

**Comment by endash** [comment]
My assumption with the syntax

```
<foobar *foo [bar]="something"></foobar>
```

was that if `Foobar` didn't have a `bar` `input`, but `Foo` did, then `Foo` would get the binding. Similar to how directives/components normally work: it would go to whichever one has the matching `input`. This assumption was reinforced by the fact that it fails silently—you don't get an error saying that neither `bar` or `template` has a matching `input`. Throwing on duplicate `*` doesn't help much, because what you want is a throw on the regular input binding syntax if it can't be disambiguated. Preferably, the compiler/linker/renderer/whatever part of Angular that is handling this would be able to look at `Foo`'s and `Foobar`'s inputs and intelligently route the binding, as is expected of directives and components.

**Comment by pkozlowski-opensource** [comment]
`<foobar *foo [bar]="something"></foobar>` doesn't fail silently, does it? AFAIK only `<foobar *foo bar="something"></foobar>` does, since we don't check for non standard attributes for now (but we will, see https://github.com/angular/angular/issues/3425

> Throwing on duplicate * doesn't help much, because what you want is a throw on the regular input binding syntax if it can't be disambiguated.

`*` is only sugar for common / non-ambiguous cases. If there is risk of confusion, people should be using canonical syntax. I don't think we should be making * any smarter.

**Comment by endash** [comment]
The entire point is there *isn't* a risk of confusion unless *you already know not to do this*. The confusion is entirely hidden and is nonobvious and unintuitive. That's why it needs to error if this isn't supported.

**Comment by pkozlowski-opensource** [comment]
> That's why it needs to error if this isn't supported

We are in agreement here. But we've got issues already opened to tackle this - this is why I've closed this issue.
