### ISSUE TITLE
urlUpdateStrategy: 'eager' - not working

### ISSUE THREAD

**Issue by sam-s4s** [angular/angular#48881]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No (though it is possible this may have worked in a version prior to 13, which is the earliest I have tried it in).

### Description

urlUpdateStrategy: 'eager' does not appear to be working. When I navigate to a route that will throw an error, the url either stays the same as the page I was previously on, or if this page is the first to be navigates to, it goes back to the root route.

Example in stackblitz:
app.module: added { urlUpdateStrategy: 'eager' } into the RouterModule.forRoot ExtraOptions.
second.component: constructor has throw new Error('ded').

What should happen is when you click the link for "second" it should update the url to "https://angular-ivy-vurmdm.stackblitz.io/second" before it even tries to navigate (thus before it even knows there will be an error, it will already have updated the url).

What actually happens is that it seems to completely ignore the urlUpdateStrategy: 'eager' and doesn't update the url until after successful navigation, whereupon the error stops this from happening.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-vurmdm?file=src/app/app.module.ts

### Please provide the exception or error you saw

```true
url is not updated to "second"
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Stackblitz latest version / ivy / 15.0.2

Also same problem with 13.3.0.
```

**Comment by JeanMeche** [comment]
To me, you are observing the expected behaviour  of the `eager` strategy. 

What `eager` allows you to do is having early updates on the new route . 
You can check it with: 
```
  constructor(router: Router, location: Location) {
    router.events.subscribe((e) => {
        console.log(this.location.path());
    });
  }
```

In case of a navigation error, with `deferred` it will only log the old url. 
With `eager` it logs the new url as soons as the router is recognized.  

When you have navigation failure (failed guard (`NavigationCanceled`), exception thrown (`NavigationError`)), the router will always go back to the previous url. Which is what you are observing.

**Comment by atscott** [comment]
As described by @JeanMeche, this is working as expected. The URL is updated as soon as route matching has finished. If the navigation fails, the router restores the URL to the previous one. In the case of an initial navigation, this is the root route ('/')

**Comment by sam-s4s** [comment]
Oh, that is a shame. I interpreted "at the beginning of navigation" to mean before the router attempts to navigate.

Thank you for the clarification.
