### ISSUE TITLE
Label `for` attribute will not associate to the corresponding id of an input element inside another component

### ISSUE THREAD

**Issue by ktschmincke** [angular/angular#48886]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

If I have a component with an input element inside of it, then matching that input's `id` value to a label's `for` value does not create the appropriate associations if that label is outside of the component. As an example:
```
<label for="my-toggle-switch">My Toggle Switch</label>
<toggle-switch id="my-toggle-switch"></toggle-switch>
```

My `toggle-switch` component accepts that id as an input and places it on a `button` like this:
```
<button [id]="id" role="switch" [attr.aria-checked]="state">
```

The outcome is a DOM that looks something like this:
```
<label for="my-toggle-switch">My Toggle Switch</label>
<toggle-switch>
  <div>
    <button id="my-toggle-switch" ...>
      <!-- ... -->
    </button>
  </div>
</toggle-switch>
```

According to the [HTML spec](https://html.spec.whatwg.org/multipage/forms.html#the-label-element), the preceding HTML structure should yield an association between the button and the label. Clicking the label should focus and activate the button, and the button should have an accessible label that matches the label content. 

That is not happening currently when the label exists outside the component. As a test, I placed the label inside the component and the appropriate association was made.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.10
Node: 16.13.2
Package Manager: npm 8.1.2
OS: darwin x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, elements
... forms, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.10
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.2.10
@angular/cdk                    14.2.7
@angular/cli                    14.2.10
@angular/material               14.2.7
@schematics/angular             14.2.10
rxjs                            7.8.0
typescript                      4.6.4
```

**Comment by JeanMeche** [comment]
Are you sure your `id` isn't duplicated on your component and on the button ?

**Comment by ktschmincke** [comment]
> Are you sure your `id` isn't duplicated on your component `toggle-switch` and on the button ?
> 
> The behaviour you are noting only happens when you are using a hard coded attribute (here `my-toggle-switch`) and not component variable.
> 
> Remember, ids have to be unique.

The id is unique. I’ve tried it with hard coded values and with component inputs. I’ve tried the same id on a label inside the component and it works as expected. It’s only when the label is outside of the component. I believe this is a bug with angular.

**Comment by JeanMeche** [comment]
Could you share a stackblitz ? 

I have it working here : https://stackblitz.com/edit/angular-standalone2-wmdxkk?file=src%2Fmain.ts

**Comment by ktschmincke** [comment]
Ahhhh I'm an idiot. You were right @JeanMeche. Because I called my input `id, it was duplicated in the DOM. Changing the id name fixed it
