### ISSUE TITLE
Dynamic form live example: input field for "First name" is not rendered correctly

### ISSUE THREAD

**Issue by an-gu99** [angular/angular#48895]
### Describe the problem that you experienced

input field for "First name" looks the same as input field for "Email" even though there is an explicit CSS rule for input[type="text"] in styles.css

Reason is that the type of QuestionBase - object is '' by default and this is assigned to the [type] of the "\<input>\" element.
"\<input type=''>\" doesn't seem right to me.

On the other hand: the correct rendering ("width: 100%") doesn't look good on a wider viewport.

1st question: should it be changed at all?

In case it should be changed my suggested solution of a pool of possible solutions is:
a) provide type-property when construction 'First name' in question.service.ts and 
d) remove or adapt CSS rule

Happy to do the PR if I know which one is the right solution for Angular.

More possible solutions:
a) provide type-property when constructing 'First name' in question.service.ts
b) add default type to question-textbox.ts
c) add default type in constructor in question-base.ts
d) remove / adapt CSS rule
e) leave it like it is (it looks good)
f) ...

### Enter the URL of the topic with the problem

https://angular.io/guide/dynamic-form

**Comment by JeanMeche** [comment]
I'd say, the displayed result is as expected. 

The stylesheet you see at the root of the project is actually shared across all examples : 

https://github.com/angular/angular/blob/2fc5b70fcedb8ac35b825b245c0ae394dc125244/aio/tools/examples/shared/boilerplate/common/src/styles.css#L78-L82

**Comment by an-gu99** [comment]
I myself tend to believe that the displayed result is fine but I am not sure if the type of the "input"-HTML-element should really be empty.
