### ISSUE TITLE
Specify inputs and outputs via Annotations / decorators

### ISSUE THREAD

**Issue by gionkunz** [angular/angular#4890]
I think it would be very useful to specify intputs and outputs with decorators, similar to the @HostBinding annotation. Having declarative code exactly there where it's used is much cleaner than having one big list of inputs and outputs at the top of the component IMHO.

```javascript
@Component({
  selector: 'task'
})
@View({
  template: template,
  directives: [Task]
})
export default class Task {
  constructor() {
    this._finishedHandler = new EventEmitter();
  }

  @Input('taskData')
  set task(_task) {
    this._task = _task;
  }

  @Output('finished') 
  get finishedHandler() {
    return this._finishedHandler;
  }
}
```

**Comment by gionkunz** [comment]
I just saw a spec that this should be possible: https://github.com/angular/angular/blob/f529236bfc7868c3c53438c1b20d821c12bb8d4a/modules/angular2/test/core/linker/directive_resolver_spec.ts

**Comment by PascalPrecht** [comment]
@gionkunz correct, what you can do is

```
@Component({
  selector: 'task',
  template: template,
  directives: [Task]
})
export class Task {
  @Input('taskData') _task;
  @Output('finished') _finishedHandler = new EventEmitter();

  somethingHappened() {
    this._finishedHandler.next(); // emit event
  }
}
```

Hope this makes things clear.

**Comment by gionkunz** [comment]
Okay, yeah this works already :-) Awesome!
