### ISSUE TITLE
Upgrade module fires error when upgrading ng1 directives without templates.

### ISSUE THREAD

**Issue by tandu** [angular/angular#4891]
I'm trying to use [angular-file-upload](https://github.com/nervgh/angular-file-upload) in angular 2 application.
when I try to upgrade nvFileSelect directive

``` TypeScript
adapter.upgradeNg1Component('nvFileSelect')
```

I get this error:
`Error: Directive 'nvFileSelect' is not a component, it is missing template.`

Are there plans to add support for such directives?

**Comment by PascalPrecht** [comment]
@tandu I don't know what the configuration of your `nvFileSelect` directive looks like, but what I do know is that you can't upgrade directives that aren't components. So basically directives without isolated scopes can't be upgraded using `ngUpgrade`.

**Comment by PascalPrecht** [comment]
Just to confirm: yes, the directive you're using isn't a component directive ~ https://github.com/nervgh/angular-file-upload/blob/master/src/directives/FileSelect.js#L10

So this won't work.

**Comment by tandu** [comment]
`nvFileSelect' is defined here: https://github.com/nervgh/angular-file-upload/blob/master/src/index.js. I see from sources that 'upgrade' only supports directives with templates. I think it is important to add support for directives without templates because they are a common thing in angular. Will it be added in future releases of 'upgrade' module or it will never work with them?

**Comment by PascalPrecht** [comment]
AFAIK they won't be supported.

**Comment by david-gang** [comment]
hi @PascalPrecht , Does this mean that you won't support mdicon of the angular material library?
This is also without template?
>getAdapter().upgradeNg1Component('mdIcon')

gives me 

>Uncaught Error: Directive 'mdIcon' is not a component, it is missing template.UpgradeNg1ComponentAdapterBuilder.compileTemplate @ node_modules\angular2\src\upgrade\angular2\src\upgrade\upgrade_ng1_adapter.ts:142UpgradeNg1ComponentAdapterBuilder.resolve @ node_modules\angular2\src\upgrade\angular2\src\upgrade\upgrade_ng1_adapter.ts:165(anonymous function) @ node_modules\angular2\src\upgrade\angular2\src\upgrade\upgrade_adapter.ts:344invoke @ angular.js:4478(anonymous function) @ angular.js:4299forEach @ angular.js:336createInjector @ angular.js:4299doBootstrap @ angular.js:1657bootstrap @ angular.js:1678(anonymous function) @ node_modules\angular2\src\upgrade\angular2\src\upgrade\upgrade_adapter.ts:349NgZone.run @ node_modules\angular2\src\core\zone\angular2\src\core\zone\ng_zone.ts:313UpgradeAdapter.bootstrap @ node_modules\angular2\src\upgrade\angular2\src\upgrade\upgrade_adapter.ts:349719../angular_upgrade @ app.ts:14s @ _prelude.js:1e @ _prelude.js:1(anonymous function) @ _prelude.js:1
angular.js:10722 POST http://localhost:8000/primo_library/libweb/primoExploreLogout 404 (Not Found)(anonymous function) @ angular.js:10722sendReq @ angular.js:10515serverRequest @ angular.js:10222processQueue @ angular.js:14745(anonymous function) @ angular.js:14761Scope.$eval @ angular.js:15989Scope.$digest @ angular.js:15800(anonymous function) @ angular.js:16028completeOutstandingRequest @ angular.js:5507(anonymous function) @ angular.js:5784

**Comment by PascalPrecht** [comment]
@david-gang any ngUpgrade doesn't support components as the error message states. For Angular Material specifically has a 2.0 branch that ppl are working on.

**Comment by david-gang** [comment]
yes @PascalPrecht . I know people are working on this, but in the last ng-conf @jelbourn stated that maybe in the next conference he will be able to show something, meaning that it won't be production ready for a long time.
 I would expect a better interoperability between the google's angular products, As it is a free product i cannot set any expectations but i am still confused about this. 
I think that many people will want to upgrade and won't find it nice that angular material is hindering them

**Comment by robertye112** [comment]
david-gang i'm in the same situation as you. basically what I'm hearing is, if you use angular 1.x and angular material design, the only thing you can really upgrade using the upgrad adapter are your services (pretty much useless).

**Comment by petebacondarwin** [comment]
It is not possible to support upgrading of non-template directives (i.e. non-components) since we need each framework A1 and A2 to "own" each DOM element. Templateless directives are "decorators" which means that they don't own the element they are on. This creates too many possible places for the frameworks to overlap and would make it impossible to keep track of.

So I am sorry but there will be no support for upgrading this kind of directive.

Of course that doesn't mean that you can't use them. It just means that they must exist in the Angular 1 templates of an upgrade application. Generally it is better to try to upgrade chunks of the UI rather than very fine grain approach.

Also Angular Material for Angular 2 is now in beta and so is pretty close to being ready for your production applications.
