### ISSUE TITLE
standalone option for ng new

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular#48924]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler-cli

### Description

as per [docs](https://angular.io/guide/standalone-components#bootstrapping-an-application-using-a-standalone-component) you can bootstrap the app with a standalone component instead of an NgModule using `bootstrapApplication`

add the option `--standalone` to `ng new` to generate a standalone-based app with `bootstrapApplication(AppComponent)`
and flag `AppComponent` as a standalone, removing NgModule entirely 

### Proposed solution

`ng n $appName --standalone`

### Alternatives considered

.

**Comment by JeanMeche** [comment]
Hi, there is already an open issue for this on the CLI repo : angular/angular-cli#23976

**Comment by JoostK** [comment]
> Hi, there is already an open issue for this on the CLI repo : [angular/angular-cli#23976](https://github.com/angular/angular-cli/issues/23976)

Thanks for the link, this is indeed a duplicate.
