### ISSUE TITLE
wrong display of information on the reactive forms page

### ISSUE THREAD

**Issue by ierrihon** [angular/angular#48926]
### Describe the problem that you experienced

While reading documentation, one form is behind the right side of the page. 
In the paragraph [Using the FormBuilder service to generate controls](https://angular.io/guide/reactive-forms#using-the-formbuilder-service-to-generate-controls), you can't fully read some of the text, changing screen size, f5 or anything else won't help, the only possibility to read is open console, which I sure wasn't intended by developers.
![image](https://user-images.githubusercontent.com/103900301/216347183-7196464f-8db6-4ebf-b517-75f897ba9049.png)

### Enter the URL of the topic with the problem

https://angular.io/guide/reactive-forms#using-the-formbuilder-service-to-generate-controls

### Describe what you were looking for in the documentation

I was learning how to work with Reactive Forms

### Describe the actions that led you to experience the problem

Reading text trough the page

### Describe what you want to experience that would fix the problem

I'm only Junior, but I think that the best and the simplest option would be to adjust the size of this <table> component to the size of the same components of the same page.. 

### Add a screenshot if that helps illustrate the problem

![image](https://user-images.githubusercontent.com/103900301/216347627-3a54d6eb-cfac-4e4f-b5d0-0860fa7f59c1.png)

**Comment by JoostK** [comment]
This is indeed a known issue being tracked in #45121.
