### ISSUE TITLE
EXCEPTION: Error during instantiation of Token Promise<ComponentRef>!. angular2.dev.js:21845

### ISSUE THREAD

**Issue by Yunlong2cn** [angular/angular#4892]
Follow quickstart.html I create a angular2-quickstart and run "npm start", and the browser notice me like this:
EXCEPTION: Error during instantiation of Token Promise<ComponentRef>!.
angular2.dev.js:21835 EXCEPTION: Error during instantiation of Token Promise<ComponentRef>!.BrowserDomAdapter.logError @ angular2.dev.js:21835BrowserDomAdapter.logGroup @ angular2.dev.js:21846ExceptionHandler.call @ angular2.dev.js:4431(anonymous function) @ angular2.dev.js:19642run @ angular2.dev.js:138(anonymous function) @ angular2.dev.js:10644NgZone.run @ angular2.dev.js:10607ApplicationRef_.bootstrap @ angular2.dev.js:19615commonBootstrap @ angular2.dev.js:26650bootstrap @ angular2.dev.js:27475(anonymous function) @ app.js:8(anonymous function) @ app.js:10U @ system.src.js:4573c.execute @ system.src.js:4573i @ system.src.js:4573n @ system.src.js:4573execute @ system.src.js:4573b @ system.src.js:4573w @ system.src.js:4573p @ system.src.js:4573h @ system.src.js:4573(anonymous function) @ system.src.js:4573run @ angular2.dev.js:138zoneBoundFn @ angular2.dev.js:111lib$es6$promise$$internal$$tryCatch @ angular2.dev.js:1507lib$es6$promise$$internal$$invokeCallback @ angular2.dev.js:1519lib$es6$promise$$internal$$publish @ angular2.dev.js:1490(anonymous function) @ angular2.dev.js:219run @ angular2.dev.js:138zoneBoundFn @ angular2.dev.js:111lib$es6$promise$asap$$flush @ angular2.dev.js:1301
angular2.dev.js:21835 ORIGINAL EXCEPTION: No Directive annotation found on AppComponentBrowserDomAdapter.logError @ angular2.dev.js:21835ExceptionHandler.call @ angular2.dev.js:4440(anonymous function) @ angular2.dev.js:19642run @ angular2.dev.js:138(anonymous function) @ angular2.dev.js:10644NgZone.run @ angular2.dev.js:10607ApplicationRef_.bootstrap @ angular2.dev.js:19615commonBootstrap @ angular2.dev.js:26650bootstrap @ angular2.dev.js:27475(anonymous function) @ app.js:8(anonymous function) @ app.js:10U @ system.src.js:4573c.execute @ system.src.js:4573i @ system.src.js:4573n @ system.src.js:4573execute @ system.src.js:4573b @ system.src.js:4573w @ system.src.js:4573p @ system.src.js:4573h @ system.src.js:4573(anonymous function) @ system.src.js:4573run @ angular2.dev.js:138zoneBoundFn @ angular2.dev.js:111lib$es6$promise$$internal$$tryCatch @ angular2.dev.js:1507lib$es6$promise$$internal$$invokeCallback @ angular2.dev.js:1519lib$es6$promise$$internal$$publish @ angular2.dev.js:1490(anonymous function) @ angular2.dev.js:219run @ angular2.dev.js:138zoneBoundFn @ angular2.dev.js:111lib$es6$promise$asap$$flush @ angular2.dev.js:1301
angular2.dev.js:21835 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ angular2.dev.js:21835ExceptionHandler.call @ angular2.dev.js:4443(anonymous function) @ angular2.dev.js:19642run @ angular2.dev.js:138(anonymous function) @ angular2.dev.js:10644NgZone.run @ angular2.dev.js:10607ApplicationRef_.bootstrap @ angular2.dev.js:19615commonBootstrap @ angular2.dev.js:26650bootstrap @ angular2.dev.js:27475(anonymous function) @ app.js:8(anonymous function) @ app.js:10U @ system.src.js:4573c.execute @ system.src.js:4573i @ system.src.js:4573n @ system.src.js:4573execute @ system.src.js:4573b @ system.src.js:4573w @ system.src.js:4573p @ system.src.js:4573h @ system.src.js:4573(anonymous function) @ system.src.js:4573run @ angular2.dev.js:138zoneBoundFn @ angular2.dev.js:111lib$es6$promise$$internal$$tryCatch @ angular2.dev.js:1507lib$es6$promise$$internal$$invokeCallback @ angular2.dev.js:1519lib$es6$promise$$internal$$publish @ angular2.dev.js:1490(anonymous function) @ angular2.dev.js:219run @ angular2.dev.js:138zoneBoundFn @ angular2.dev.js:111lib$es6$promise$asap$$flush @ angular2.dev.js:1301
angular2.dev.js:21835 Error: No Directive annotation found on AppComponent
    at new BaseException (angular2.dev.js:16034)
    at DirectiveResolver.resolve (angular2.dev.js:9953)
    at RuntimeMetadataResolver.getMetadata (angular2.dev.js:12685)
    at TemplateCompiler.compileHostComponentRuntime (angular2.dev.js:24877)
    at RuntimeCompiler_.compileInHost (angular2.dev.js:27391)
    at DynamicComponentLoader_.loadAsRoot (angular2.dev.js:13289)
    at di_1.provide.useFactory (angular2.dev.js:19433)
    at Injector._instantiate (angular2.dev.js:22778)
    at Injector._instantiateProvider (angular2.dev.js:22714)
    at Injector._new (angular2.dev.js:22704)

**Comment by pkozlowski-opensource** [comment]
@Yunlong2cn it is next to impossible to diagnose what is going on just based on the info provided. Could you please ask for help on https://gitter.im/angular/angular providing more context (ideally share your code somewhere). Thnx!
