### ISSUE TITLE
Directive composition: support mapping one input to two different inputs of a host directive 

### ISSUE THREAD

**Issue by jnizet** [angular/angular#48925]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Sometimes, directives offer two inputs that play a similar role, and can receive the exact same value. When using the directive composition API, it would be nice if a single input could be mapped to these two similar inputs of the host directive.

I.e. I would like this test to pass:

```ts
import { Component, Directive, Input } from '@angular/core';
import { TestBed } from '@angular/core/testing';
import { By } from '@angular/platform-browser';

@Directive({
  selector: '[hostDirective]',
  standalone: true
})
class HostDirective{
  @Input() i1?: string
  @Input() i2?: string
}

@Directive({
  selector: '[composedDirective]',
  standalone: true,
  hostDirectives: [
    {
      directive: HostDirective,
      inputs: ['i1: i', 'i2: i']
    }
  ]
})
class ComposedDirective{
}

@Component({
  template: '<div composedDirective i="hello"></div>',
  standalone: true,
  imports: [ComposedDirective]
})
class TestComponent {}

describe('composition', () => {
  it('should map a single input to two host inputs', () => {
    const fixture = TestBed.createComponent(TestComponent);
    fixture.detectChanges();

    const hostDirective = fixture.debugElement.query(By.directive(HostDirective)).injector.get(HostDirective);
    expect(hostDirective.i1).toBe('hello');
    expect(hostDirective.i2).toBe('hello');
  });
})
```

but it currently fails with the following error:

```
Error: ASSERTION ERROR: Conflicting host directive input alias i2. [Expected=> i2 == i1 <=Actual]
```

If there's a good technical reason for this scenario to be unsupported, improving the error message at least would be a good thing, because I find it a hard to understand. 

### Proposed solution

Mapping a single input of the composed directive to several inputs of the host directive would be supported. 

Every time the composed directive input would change (`i` in the above example), then the mapped inputs of the host directive (`i1` and `i2` in the above example) would be set to the new value of the input, and the `ngOnChanges` hook would be executed on the host directive with `i1` and `i2` both listed as changed. 

### Alternatives considered

Leave it as is is, but improve the documentation to mention that limitation, and improve the error message.

**Comment by jnizet** [comment]
@pkozlowski-opensource 

The use-case is to create a reusable typeahead directive by composing the [ng-bootstrap typeahead](https://ng-bootstrap.github.io/#/components/typeahead/examples). 

Let's say that I want to create a `userTypeahead`  directive that allows searching and selecting a user, by composing the `ngbTypeahead` directive.

I still want to be able to customize the way user items are formatted by the typeahead, but I always want to format them the same way in the result and in the input. 

ng-bootstrap's typeahead has a `inputFormatter` input and a `resultFormatter` input. And I would thus like to be able to bind those two inputs at once to the unique input `formatter` f my `userTypeahead`directive: if I pass a `formatter` input to my directive, its value would populate both the `resultFormatter` and the `inputFormatter` inputs of `ngbTypeahead`.

**Comment by pkozlowski-opensource** [comment]
Oh, so we might have misunderstood the use case - it is more about channeling one input into 2 different inputs of a host directive? 

cc @crisbeto
