### ISSUE TITLE
Parser error in *ngFor when casting to FormArray

### ISSUE THREAD

**Issue by johannesmols** [angular/angular#48938]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

I'm trying to iterate over a `FormArray` in my template, but am getting parser errors for the iterator expression:

```
<div *ngFor="let day of (this.representationForm.controls.closedDays as FormArray).controls; let i = index">
  <p>{{day.value}}</p>
</div>
```

The error: `Parser Error: Missing expected ) at column 57 in [let day of (this.representationForm.controls.closedDays as FormArray).controls; let i = index]`. Column 57 is right after "representationForm".

Issue #13184 describes the exact issue I have had, and the solution is suggested to be to use a function to retrieve the controls. This does work, but of course doesn't update when I change the contents of the array in the code. Is there a workaround for that?

I'm submitting this as a bug as it doesn't make sense to me why this should be missing a parenthesis. Adding it also makes no difference. This issue arises when adding the `as FormArray` cast. But unfortunately, one cannot access the last `controls` unless the type is specified like this (using an untyped form group). And without this last one, the error `Error: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.` appears.

### Please provide the exception or error you saw

```true
Parser Error: Missing expected ) at column 57 in [let day of (this.representationForm.controls.closedDays as FormArray).controls; let i = index]`. Column 57 is right after "representationForm
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 14.2.10
Node: 16.13.0
OS: Windows 10
```

**Comment by JeanMeche** [comment]
You can use `$any` : 

`$any(this.representationForm.controls.closedDays).controls`

See Alex's comment in #45468 about why casting isn't possible.

**Comment by JoostK** [comment]
Angular templates do not support casts in expressions; the `as` syntax is invalid.

> Issue https://github.com/angular/angular/issues/13184 describes the exact issue I have had, and the solution is suggested to be to use a function to retrieve the controls. This does work, but of course doesn't update when I change the contents of the array in the code. Is there a workaround for that?

This is the correct approach here; there is no problem with updating the controls compared to writing the expression in the template itself, but by moving it to a component method you get the ability to use casts in TypeScript.

> The error: Parser Error: Missing expected ) at column 57 in [let day of (this.representationForm.controls.closedDays as FormArray).controls; let i = index]. Column 57 is right after "representationForm"

While this error is somewhat unfortunate, column 57 within that expression does correspond with the `as` cast (not `representationForm`) to indicate that something is wrong there. The suggestion to insert a parenthesis is a parser recovery suggestion, which is unfortunately unhelpful in this situation.

**Comment by johannesmols** [comment]
Thank you both, I wasn't aware that you couldn't cast here, even though I suspected it from the error message. `$any` solves this indeed. And @JoostK you're right about the column. The code is indented in reality and VS code showed that the actual column 57 is where I wrote, but the error message displayed the column without the indentation.
