### ISSUE TITLE
Multiple forms with the same name attribute for radio inputs

### ISSUE THREAD

**Issue by xxluke** [angular/angular#48946]
### Which @angular/* package(s) are the source of the bug?

forms

### Description

In HTML radio buttons are grouped by the `name` attribute. Now I moved them to their own component (not in the example), and I need the same radio buttons twice, so I ended up having two sets of radio buttons with the same name. This is not a problem in HTML when they're in different `<form>` tags [working plain HTML example](https://jsfiddle.net/v43py8j1/1/).

However, it seems that Angular doesn't support having independend input groups with the same names [not working Angular example](https://stackblitz.com/edit/angular-e49kbu?file=src%2Fmain.ts,src%2Fmain.html). When you select a radio button from one group, the one from the other group gets selected, too. The value of the form is correct, though. It works as soon as you choose a different name for one of the radio groups, in the example `animal`.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-e49kbu?file=src%2Fmain.ts,src%2Fmain.html

### Please provide the exception or error you saw

When you select a radio button from one group, the one from the other group gets selected, too.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 15.1.1
```

**Comment by JeanMeche** [comment]
There is currently a bug with the radio inputs. You'll need to specify `name` and `formControlName` (with the same value) to achieve the desired behaviour. 

For your example that would be 

```
    name="animal"
    formControlName="animal"
```


See also #45719 and #11757 who are closely related to this issue 👍

**Comment by xxluke** [comment]
Thank you, your workaround works and I'm closing this ticket as it seems to be the same issue as #45719
