### ISSUE TITLE
`ng g @angular/core:standalone` throws when plural syntax is used in template (`TextEncoder is not defined`)

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#48940]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

`ng g @angular/core:standalone` throws when a template uses the plural syntax

```
ng new standalone-migration --defaults
cd standalone-migration
ng update @angular/core@next @angular/cli@next --force
ng add @angular/localize
echo "<div>{ 0, plural, =0 {Nobody} }</div>" > src/app/app.component.html
ng g @angular/core:standalone --defaults
```

### Please provide the exception or error you saw

```true
❯ ng g @angular/core:standalone --defaults
TextEncoder is not defined
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.0-next.3
Node: 16.17.0
Package Manager: npm 8.19.3
OS: darwin arm64

Angular: 15.2.0-next.3
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.0-next.3
@angular-devkit/build-angular   15.2.0-next.3
@angular-devkit/core            15.2.0-next.3
@angular-devkit/schematics      15.2.0-next.3
@schematics/angular             15.2.0-next.3
rxjs                            7.8.0
typescript                      4.9.5
```

### Anything else?

ng serve/build/test are all working fine

**Comment by crisbeto** [comment]
This is a CLI bug. I've sent out https://github.com/angular/angular-cli/pull/24662 to fix it.

**Comment by clydin** [comment]
While the CLI PR does avoid the crash, there may be more to this issue.
Since the schematics are not emitting code via the compiler and the `TextDecoder` instance is lazily initialized, using the AOT compiler for metadata static analysis should probably not be causing an error in this case.
