### ISSUE TITLE
[Alpha 44][Router] Parenthesis in urls

### ISSUE THREAD

**Issue by ocombe** [angular/angular#4895]
I have a problem with parenthesis characters:
`this.router.navigate(['./Show', {id: "The Player (2015)"]);`
---> works on first try
---> doesn't work on page refresh returns "The Player " (instead of "The Player (2015)")

And when I try to URI encode them:
`this.router.navigate(['./Show', {id: encodeURIComponent("The Player (2015)")]);`
---> doesn't works on first try (route params return "The%20Player%20")
---> doesn't work on page refresh returns "The%20Player%20" (instead of "The%20Player%20(2015)")

I guess that the problem is that the router will think that those parenthesis are auxiliary routes when you refresh the app. The router should probably encode those to something else and decode them for the params.
I'll make that myself for now, but it would probably be a good idea to have this implemented within the router himself for all "special" characters that it might use. I shouldn't be limited in any way regarding the characters that I put into the url.

**Comment by Krustie101** [comment]
@ocombe FYI: encodeURIComponent does not encode ( or ). Are you sure that you get "The%20Player%20" in your RouteParams on your first try after encoding? I do not see that behaviour, I get "The%20Player%20(2015)" as expected.

**Comment by ocombe** [comment]
Yes I know that it doesn't encode parenthesis, but I tried it before discovering auxiliary routes, which seems to be the problem here. Because it works until I refresh the page and then the router gets fooled when analyzing the url :-/

**Comment by ocombe** [comment]
OK I temporary fixed this problem by running all my routes through an extended encodeURIComponent function:
```js
encodeURIComponent(str) {
    return encodeURIComponent(str).replace(/[!'()*]/g, function (c) {
        return '%' + c.charCodeAt(0).toString(16);
    });
}
```

Still it would be nice to have this built into the router.

**Comment by kamarouski** [comment]
I have the same issue with Component router in Angular 2 RC1

**Comment by felipedrumond** [comment]
HI ocombe. Did you find a solution for parenthesis on url parameters? This issue still exists in RC4!

**Comment by ocombe** [comment]
I haven't retried since then

**Comment by vicb** [comment]
Could you please open a new issue if the bug still exists. The router is brand new.

**Comment by ericmartinezr** [comment]
@vicb in that case the other one (https://github.com/angular/angular/issues/10280) should be reopened

**Comment by felipedrumond** [comment]
Any updates or workaround for this issue guys?
