### ISSUE TITLE
Importing shared styled in global scss is not working across all application 

### ISSUE THREAD

**Issue by lakshmi2716** [angular/angular#48955]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I am using angular 15. I have created variables.scss and imported that into global style.scss . Without importing variable.scss into each component, i am not able to use it. If i use it i am getting variable is not defined.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
