### ISSUE TITLE
NG 12 AOT cause out of memory error when compile using `ng-packagr`

### ISSUE THREAD

**Issue by duykhang53** [angular/angular#48954]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

No

### Description

Follow up of https://github.com/angular/angular-cli/issues/21041

This behavior still occurs in ~12.2.0

### Reproduction:
```bash
$ npm i -g @angular/cli@v12-lts
$ npx ng new angular-error-sync-async --minimal --routing false --style css
$ cd angular-error-sync-async
$ npx ng generate lib err-lib
```

> projects/err-lib/tsconfig.lib.prod.json
```json
{
  "extends": "./tsconfig.lib.json",
  "compilerOptions": {
    "declarationMap": false
  },
  "angularCompilerOptions": {
    "enableIvy": false,
    "fullTemplateTypeCheck": true
  }
}
```

> projects/err-lib/src/lib/err-lib.module.ts

```typescript
import { ModuleWithProviders, NgModule } from '@angular/core';

import { ErrLibComponent } from './err-lib.component';

@NgModule({})
export class ErrRegisterModule {
  static register(arg: any): ModuleWithProviders<ErrRegisterModule> {
    return { ngModule: ErrRegisterModule };
  }
}

@NgModule({
  declarations: [
    ErrLibComponent
  ],
  imports: [
    ErrRegisterModule.register(() => () => true)
  ],
  exports: [
    ErrLibComponent
  ]
})
export class ErrLibModule { }
```

`$ npx ng b err-lib --configuration production`

### Expected Error
> \------------------------------------------------------------------------------
> Building entry point 'err-lib'
> \------------------------------------------------------------------------------
> × Compiling with Angular in legacy View Engine compilation mode.
> projects/err-lib/src/lib/err-lib.module.ts(17,32): Error during template compile of 'ɵ0'
>   Function expressions are not supported in decorators
>     Consider changing the function expression into an exported function.

### Actual Error
> \------------------------------------------------------------------------------
> Building entry point 'err-lib'
> \------------------------------------------------------------------------------
> × Compiling with Angular in legacy View Engine compilation mode.
> Angular structure loaded both synchronously and asynchronously

### Temporary fix
https://github.com/angular/angular/blob/737f71e3aa763980e4bdc6f0d3f13e2c712b12d9/packages/compiler-cli/src/transformers/program.ts#L702

> node_modules/@angular/compiler-cli/src/transformers/program.js
```diff
        AngularCompilerProgram.prototype._addStructuralDiagnostics = function (error) {
            var diagnostics = this._structuralDiagnostics || (this._structuralDiagnostics = []);
            if (compiler_1.isSyntaxError(error)) {
-                diagnostics.push.apply(diagnostics, tslib_1.__spreadArray([], tslib_1.__read(syntaxErrorToDiagnostics(error, this.tsProgram))));
+                diagnostics.push.apply(diagnostics, tslib_1.__spreadArray([], tslib_1.__read(syntaxErrorToDiagnostics(error, this._tsProgram))));
            }
            else {
                diagnostics.push({
                    messageText: error.toString(),
                    category: ts.DiagnosticCategory.Error,
                    source: api_1.SOURCE,
                    code: api_1.DEFAULT_ERROR_CODE
                });
            }
        };
```

### POV
As I debugged:
- `this.initSync()` didn't called
- Exception in `this.loadNgStructureAsync()` -> `this._createProgramWithBasicStubs()` that cause `this._createCompiler()` raise `this._addStructuralDiagnostics()`
- `this._createProgramOnError()` never called, `this._tsProgram` is never assigned

This issue is related to https://github.com/ng-packagr/ng-packagr

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.2.18
Node: 16.19.0 (Unsupported)
Package Manager: npm 8.19.3
OS: win32 x64

Angular: 12.2.17
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router     

Package                         Version
---------------------------------------------------------  
@angular-devkit/architect       0.1202.18
@angular-devkit/build-angular   12.2.18
@angular-devkit/core            12.2.18
@angular-devkit/schematics      12.2.18
@angular/cli                    12.2.18
@schematics/angular             12.2.18
ng-packagr                      12.2.7
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by JoostK** [comment]
Hello, Angular 12 is no longer supported and the code you're refering has since been superseded by the Ivy compiler, which works differently from the compiler in Angular 12. Please update to a supported version of Angular.
