### ISSUE TITLE
docs-bug(Resolve): Show how to inject services with an in-line ResolveFn.

### ISSUE THREAD

**Issue by stothardj** [angular/angular#48960]
### Documentation Feedback

The use of a class implementing `Resolve<Hero>` shows how to get a hero from the HeroService using `return this.service.getHero(route.paramMap.get('id'));`. The HeroService is injected in the constructor.

The inline function example for how to use a `ResolveFn` only shows how to return a constant hero. This avoids showing how to inject members into the Javascript function, which may not be known to the reader. Changing this example to also retrieve the Hero from a HeroService would help people who want to translate their Resolve class into a ResolveFn.

I'm suggesting replacing:

```ts
export const myHero: Hero = {
  // ...
}

@NgModule({
  imports: [
    RouterModule.forRoot([
      {
        path: 'detail/:id',
        component: HeroComponent,
        resolve: {
          hero: (route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => myHero
        }
      }
    ])
  ],
})
export class AppModule {}
```

with

```ts
@NgModule({
  imports: [
    RouterModule.forRoot([
      {
        path: 'detail/:id',
        component: HeroComponent,
        resolve: {
          hero: (route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => {
            const service = inject(HeroService);
            return service.getHero(route.paramMap.get('id'));
          }
        }
      }
    ])
  ],
})
export class AppModule {}
```

### Affected documentation page

https://angular.io/api/router/Resolve

**Comment by JeanMeche** [comment]
This part of the doc has been updated by #48873. The example you're giving won't exist anymore in the next release.

**Comment by atscott** [comment]
Closing as completed. The `Resolve` interface will be deprecated in v15.2 so expanding the documentation isn't a priority. The `ResolveFn` has an example of injecting a service: https://next.angular.io/api/router/ResolveFn
