### ISSUE TITLE
Custom window properties prefixed with `on` are set to null

### ISSUE THREAD

**Issue by dkimmich-onventis** [angular/angular#48967]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I'm setting custom window properties in my `index.html` file in a script tag, like the following:

```
<script type="text/javascript">
  window.one = 1;
  window.two = 2;
</script>
```

After building and opening the application in the browser, the properties have the following values:

```
console.log(window.one); // -> null
console.log(window.two); // -> 2
```

It seems like custom window properties prefixed with "on" are set to `null` by Angular.

### Please provide a link to a minimal reproduction of the bug

https://github.com/dkimmich-onventis/angular-custom-window-properties-bug

### Please provide the exception or error you saw

```true
No exception or error, but my custom window property is overridden.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.4
Node: 18.14.0
Package Manager: npm 8.19.3
OS: darwin arm64

Angular: 15.1.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.4
@angular-devkit/build-angular   15.1.4
@angular-devkit/core            15.1.4
@angular-devkit/schematics      15.1.4
@angular/cli                    15.1.4
@schematics/angular             15.1.4
rxjs                            7.8.0
typescript                      4.9.5
```

### Anything else?

In Angular v10 and prior it worked fine.

**Comment by alxhub** [comment]
This is due to `zone.js`, which is attempting to monkey-patch all of the `EventTarget`s in the browser, including `window`. Any property starting with `on` is treated as an event. This is a direct consequence of how Zone works - it's not able to distinguish what is or isn't an old-style event property.

A workaround is to tell `zone.js` to ignore your custom properties:

```javascript
window['__Zone_ignore_on_properties'] = [
  {target: window, ignoreProperties: ['one]},
];
```
