### ISSUE TITLE
issue with lazy loading standalone components

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular#48962]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

in NgModule-based apps we can set custom routes like this:
```
const routes: Routes = [
  {
    matcher: (segments: any, group: any, route: any) => { consumed: [] },
    loadChildren: () => import('./feature.module').then(m=>m.FeatureModule),
  },
];
```
this matcher matches all paths for illustrating only,
note that `consumed` has an empty array, so that `Router.url` in the component gives the full URL, instead of only a part of it.

for example when you navigate to "/path1/path2/path3" `Router.url` is the full path
but, if you changed consumed into `{ consumed: segments }`, `Router.url` now is '/'.

to implement the exact same behavior with standalone components (Angular v15), only the second one works, which always gives the same value for Router.url which is "/". I don't want to use `posParams`, I just want `Router.url` to give me the full path

using the lean `Router.url` is much easier than subscribing to any Observable based method such as ActivatedRoute`

returning `{ consumed: [] }` and navigating to any path other than '/' gives the following error
```
Error: Uncaught (in promise): Error: NG04002
Error: NG04002
    at Mc.noMatchError (chunk-YDI57G3S.js:10:43964)
    ....
```

**Comment by atscott** [comment]
Please provide a reproduction. The description doesn't sound like this is related to standalone components at all and I'm also not sure what exactly is being described. Using a standalone component in the loadChildren routes does return the "full" URL https://stackblitz.com/edit/angular-vhroeq?file=src%2Fmain.ts. This should always be the behavior unless you've managed to do something like provide the a second instance of the Router.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template (including a reproduction in either stackblitz or a github repository).
