### ISSUE TITLE
Alter scss/css variables from angular typescript

### ISSUE THREAD

**Issue by shivachaturvedhi9** [angular/angular#48979]
### Description

Able to use typescript variables, which can be rendered or altered through api calls,
these changes needs to be reflected in scss / css files

Right now, only features, could be able to see are:  able to declare fixed values in scss file and then
use them in all other files.
But the scss file , we cannot change using api calls.

Looking for an ability to alter scss variables throuh api calls

### Proposed solution

It is a request. no idea of solution

### Alternatives considered

no idea how to implement

**Comment by JeanMeche** [comment]
SCSS can't be modifed at run time because they are compiled away. 

You'll have to rely on [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties).

**Comment by alan-agius4** [comment]
Closing as explained by @JeanMeche.
