### ISSUE TITLE
Standalone Component DebugElements are missing properties

### ISSUE THREAD

**Issue by GabrielBB** [angular/angular#48978]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

If you use a non standalone `ChildComponent` by its selector and pass an attribute, this will be included inside `DebugElement.properties` . Example: When doing `<child-component [foos]="fooList"/>` then `DebugElement.properties.foos` will contain `fooList` . However, if you add `standalone: true` to `ChildComponent` and import it from `ParentComponent` , at the time of testing `ParentComponent` and querying `child-component`, `DebugElement.properties.foos` will return `undefined` . 

Workaround: If I do `DebugElement.componentInstance.foos` then the value is there, however this requires me to change a lot of tests when migrating my project to standalone.

### Please provide the exception or error you saw

```true
Fails at: `expect(childComponent.properties.foos).toBe([]);`

`Expected undefined to be []`
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.4
Node: 16.14.2
Package Manager: npm 8.5.0
OS: linux x64

Angular: 15.1.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.2
@angular-devkit/build-angular   15.1.3
@angular-devkit/core            15.1.3
@angular-devkit/schematics      15.1.4
@angular/cli                    15.1.4
@schematics/angular             15.1.4
rxjs                            7.5.6
typescript                      4.8.4
webpack                         5.75.0
```

**Comment by pkozlowski-opensource** [comment]
@GabrielBB this sounds odd. Could you please share a minimal reproduction scenario / the exact test case? Thnx!

**Comment by GabrielBB** [comment]
Okay, I will try next week

**Comment by pkozlowski-opensource** [comment]
I'm going to close this issue for now as we haven't heard back with the reproduction scenario.
