### ISSUE TITLE
Documentation about critical inlining styles does not mention impact on CSP

### ISSUE THREAD

**Issue by matrium0** [angular/angular#48984]
### Describe the problem that you experienced

If you use inlineCritical=true (which is the default) your CSP needs to have "unsafe-inline" in their "script-src". This is due to the way critical inline works (with an "onload" event). I think the [CSP documentation](https://angular.io/guide/security#content-security-policy) is lacking, because the default CSP does not work with Angular in any but the most trivial cases.

Honestly having to set unsafe-inline for script-src is such a huge blow to CSP, that you almost might completely deactivate it. 

Anyway: this really should be mentioned in the Security -> CSP area to make this more clear to the user. Ideally this would describe the trade-off involved

### Enter the URL of the topic with the problem

https://angular.io/guide/security#content-security-policy

### Describe what you were looking for in the documentation

CSP documentation should mention what settings you need for your usual Angular application (not just the hello-world example with zero styles)

**Comment by alan-agius4** [comment]
Addressed via https://github.com/angular/angular/pull/49561
