### ISSUE TITLE
Please report about unknown tags

### ISSUE THREAD

**Issue by e-oz** [angular/angular#48986]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

Right now one can forget to import some component to render a tag, and Angular will be completely silent about it, even in runtime.

### Proposed solution

Please generate some warning or error during compilation, if some tag is unknown and there is no component imported with matching selector.

### Alternatives considered

🤷‍♂️

**Comment by JeanMeche** [comment]
Angular reports unknown components at compile time. Do you mean unknown attributes ?

**Comment by e-oz** [comment]
No, I mean unknown tags. I was investigating very weird behavior (list of the training videos was not rendered) until I found that I forgot to import VideosListComponent, so tag `<scs-videos-list>` was simply not rendered.

Angular 15.2.0-next.3 gave no warnings and happily rendered it, just without that part.

**Comment by JeanMeche** [comment]
Do you have `schema: NO_ERRORS_SCHEMA` on your module/standalone component ?

**Comment by e-oz** [comment]
No, I wouldn't bother you if I use special scheme to ignore unknown elements :)

**Comment by e-oz** [comment]
I've tried also, but [can't reproduce it yet](https://stackblitz.com/edit/angular-ivy-kzebcd?file=src/app/example/some-test.component.ts) - here I've tried to reproduce it as close as possible to our code.

I'll keep trying :) It was a real case, so it does exist.

**Comment by e-oz** [comment]
Here is the video (compressed to awful quality because of GitHub limitations) to prove that this case does exist ;)

https://user-images.githubusercontent.com/526352/217270935-d666faa3-4c96-49b8-a355-0604f69de6ef.mov

**Comment by JoostK** [comment]
This happens for elements inside ng-templates, including those created using structural directive syntax (the `*ngIf` in your video). This is only the case if `fullTemplateTypeCheck`/`strictTemplates` is not enabled; in these stricter checking modes you would get an error.

**Comment by e-oz** [comment]
Got it, thanks @JoostK
