### ISSUE TITLE
Compile time error

### ISSUE THREAD

**Issue by DilipV2503** [angular/angular#48994]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

**Hii,
I am getting this error while I connect a web-sdk into our angular project**

![InkedError](https://user-images.githubusercontent.com/83951998/217497916-95de5f1a-c066-4e16-9631-baf499f565f0.jpg)

Please help me out to fix this error.

Thank you.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 10.0.8
Node: 16.15.0
OS: win32 x64

Angular: 10.1.6
... animations, common, compiler, core, forms, language-service
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.8
@angular-devkit/build-angular      0.1000.8
@angular-devkit/build-optimizer    0.1000.8
@angular-devkit/build-webpack      0.1000.8
@angular-devkit/core               10.0.8
@angular-devkit/schematics         10.0.8
@angular/cdk                       10.2.7
@angular/cli                       10.0.8
@angular/compiler-cli              10.2.5
@angular/material                  10.2.7
@angular/material-moment-adapter   11.2.13
@ngtools/webpack                   10.0.8
@schematics/angular                10.0.8
@schematics/update                 0.1000.8
rxjs                               6.6.7
typescript                         3.9.5
webpack                            4.43.0
```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
