### ISSUE TITLE
Problem installing @angular-redux/store in Angular application.

### ISSUE THREAD

**Issue by priyamtheone** [angular/angular#48995]
### Describe the problem that you experienced

I'm new into Angular development and learning how to use Redux. While trying to install Redux using `npm install redux @angular-redux/store --save`, the terminal throws up a bunch of error messages mentioned hereunder.

I tried installing **redux** and **@angular-redux/store** separately. That way, while **redux** is getting installed successfully, **@angular-redux/store** still throws up the same error. I tried checking for solutions, but in most forums, `npm install redux @angular-redux/store --save` is the recommended command to install them. Even [npm](https://www.npmjs.com/package/@angular-redux/store) and the official sites say so.

Even after force install, I can't use `import { NgReduxModule, NgRedux } from '@angular-redux/store';` in `app.module.ts`, neither can I access `NgReduxModule` and `NgRedux` in the `imports` array of `app.module.ts`.

I've also mentioned my development environment trivia below.

So what's wrong with my system? How do I get rid of the errors and can install Redux successfully? Please help as I'm new into it and finding it difficult to figure it out.

### If this problem caused an exception or error, please paste it here

```true
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myapp@0.0.0
npm ERR! Found: @angular/core@14.2.12
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"^14.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"^7.0.0" from @angular-redux/store@10.0.0
npm ERR! node_modules/@angular-redux/store
npm ERR!   @angular-redux/store@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See C:\Users\Admin\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Local\npm-cache\_logs\2023-02-08T07_15_27_253Z-debug-0.log
```
```


### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

```true
My development environment trivia:

1) Node: 18.12.1
2) Package Manager: npm 8.5.5
3) Angular CLI: 14.2.10
4) Angular: 14.2.12
5) OS: Windows 10 win32 x64
```

**Comment by JoostK** [comment]
`@angular-redux/store` hasn't been updated in years and doesn't specify that it supports the latest Angular 15 version, which NPM considers as an error. This can be ignored using `npm install --legacy-peer-deps` , but Angular's official library support only includes libraries that are built no longer than 2 majors ago (so Angular 15 requires libraries that have been built using Angular 13+)

**Comment by priyamtheone** [comment]
@JoostK: Thanks for replying. Yes, while trying to install with `npm install --legacy-peer-deps`, though I could complete the installation, but Angular threw error when I tried to import `NgReduxModule` and `NgRedux` in `app.module.ts`. So, it didn't help either.

So, what do you suggest should I do if I want to learn Redux now? As State, Action and Reducer are important concepts, that are also asked in interviews, I don't want to miss out on them as an Angular developer. Any advice, please?

**Comment by JoostK** [comment]
NgRx is a widely used and well supported library for implementing the Redux pattern.

**Comment by priyamtheone** [comment]
@JoostK: Thanks for the reference. I managed to install NgRx and learn the fundamentals of how to use it from [this](https://www.youtube.com/watch?v=9P5DTlg9oLc&list=PLkGg-M9IbfttjGlG98qid7ctH5wkbVZ65&index=35) tutorial. Now my basic concepts of State, Action, Reducer and Store are clear.
