### ISSUE TITLE
Does Angular cooperate with AMD/CommonJS?

### ISSUE THREAD

**Issue by SetTrend** [angular/angular#4901]
Original issue #4897 has been misunderstood and closed too early.

No, I'm not talking about the scenarios you've been describing. Please read the referenced case. It describes that you cannot utilize AngularJS with RequireJS. Using asynchronous loaders, AngularJS parses the HTML document before all modules have been loaded.

**Comment by robwormald** [comment]
in angular1, you can use angular.bootstrap just fine with any async loader - you just need to remove the `ng-app` declaration from your html.

as angular2 uses that kind of bootstrapping by default, and currently uses SystemJS (which is also an async loader), it would work absolutely fine with any loader you desire.

**Comment by robwormald** [comment]
closing this, but do feel free to ask further questions in this thread if there's still some confusion.
