### ISSUE TITLE
Resolver runs before initializer has completed

### ISSUE THREAD

**Issue by OzMiomni** [angular/angular#49024]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Route resolvers will execute before functions that have been injected as an APP_INITIALIZER have returned if the APP_INITIALIZER is asynchronous. This seems to be a contradiction to the point of an initializer.

The example attached uses angular universal but the issue can be seen both by running dev:ssr or start. No matter what changes I make to the initializer function I cannot get angular to wait to run the resolver.

### Please provide a link to a minimal reproduction of the bug

https://github.com/OzMiomni/resolver-initializer-bug

### Please provide the exception or error you saw

```true
Resolver logs 'resolver running' before initialzer logs 'timeout finished in initializer'
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.5
Node: 18.13.0
Package Manager: npm 8.19.3
OS: linux x64

Angular: 15.1.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.5
@angular-devkit/build-angular   15.1.5
@angular-devkit/core            15.1.5
@angular-devkit/schematics      15.1.5
@angular/cli                    15.1.5
@nguniversal/builders           15.1.0
@nguniversal/express-engine     15.1.0
@schematics/angular             15.1.5
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by atscott** [comment]
`APP_INITIALIZER` executes before the application bootstrap. The router's initial navigation is also an `APP_INITIALIZER` and there are no guarantees about the ordering of them. 
As an alternative, you can disable the initial navigation entirely and manually call `router.initialNavigation` when desired.
