### ISSUE TITLE
After I upgraded Angular from 10.0.11 to 14.2.0, Firefox exits after exporting logs.

### ISSUE THREAD

**Issue by shiyingying** [angular/angular#49033]
### Description

After the Angular is upgraded from 10.0.11 to 14.2.0, after the Firefox browser is opened, logs can be downloaded in a link mode. After the download is successful, when other requests are invoked, the HTTP request header does not contain the token. As a result, the authentication fails and the user exits. Firefox has been tested on versions 65, 79, 100, and 108, and all have the same problem.
Normal scenario: After logs are exported, other requests are normal and the page does not exit.
The Chrome browser is normal.
Angular10-based projects are also normal on Firefox.

The following is the specific display information.
The request header of an interface before the log download interface contains Csrf-Token. The request header is as follows:
    GET /redfish/v1/rich/LogService/DevLogs?$filter=DevType%20eq%20BMC HTTP/1.1
    Host: 9.88.16.246
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
    Accept: application/json, text/plain, */*
    Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
    Accept-Encoding: gzip, deflate, br
    Csrf-Token: Rx5DxdA21WpgSNOmsn1-zVVfq_22sSo9GRftVs0uN14=
    Logintype: web
    Connection: keep-alive
    Cookie: cookieTime="2023-02-11 17:22:06"
    Pragma: no-cache
    Cache-Control: no-cache

Then is the log request(This request does not require Csrf-Token authentication.):
    GET /redfish/v1/rich/LogService/DevLogs/bmc.tar.gz/rHdvR_B2EkSL_4OP?taskId=5667fd18-5a7d-44bc-8e78-f7e892048c05&loginType=web HTTP/1.1
    Host: 9.88.16.246
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
    Accept-Encoding: gzip, deflate, br
    Connection: keep-alive
    Cookie: cookieTime="2023-02-11 17:22:06"
    Upgrade-Insecure-Requests: 1
    Pragma: no-cache
    Cache-Control: no-cache

After the preceding download request, only the subsequent requests do not have the Csrf-Token:
    GET /portal/v1/islogin HTTP/1.1
    Host: 9.88.16.246
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
    Accept: application/json, text/plain, */*
    Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
    Accept-Encoding: gzip, deflate, br
    Csrf-Token: 
    Logintype: 
    Connection: keep-alive
    Cookie: cookieTime="2023-02-11 17:22:06"
    Pragma: no-cache
    Cache-Control: no-cache

Request header parameters are carried through the httpInteceptor of the Angular.The code is as follows:
@Injectable()
export class BaseInterceptor implements HttpInterceptor {
    constructor(
        private sessionStorageService: SessionStorageService,
        private commonService: CommonService,
        private globalConst: GlobalConstService
    ) {}
    private diff = 1;
    intercept(req, next: HttpHandler) {
        const newReq = req.clone({
            url: req.hadBaseurl ? `${req.url}` : `${baseurl}${req.url}`,
        });

        if (!req.cancelToken) {
            newReq.headers = newReq.headers.set('Csrf-Token', this.sessionStorageService.get('csrftoken') || '');
            newReq.headers = newReq.headers.set('Logintype', this.sessionStorageService.get('Logintype') || '');
        }
        // send cloned request with header to the next handler.
        return next.handle(newReq).pipe(
            catchError((error: HttpErrorResponse) => {
                return throwError(this.commonService.errorDataProcessing(error));
            })
        );
    }
}

import { HTTP_INTERCEPTORS } from '@angular/common/http';
/** Http interceptor providers in outside-in order */
export const httpInterceptorProviders = [{ provide: HTTP_INTERCEPTORS, useClass: BaseInterceptor, multi: true }];

### Proposed solution

After logs are exported from the Firefox browser, other requests can be properly processed.

### Alternatives considered

I have no ideas. The Angular14 is required for our products, and the Firefox browser must also support the Angular14. Is there any change in the HTTP request?

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by shiyingying** [comment]
Okay, thank you.

**Comment by shiyingying** [comment]
> Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.
> 
> If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).



> Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.
> 
> If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Okay. Thank you~
