### ISSUE TITLE
Wild card routing for some specific URL not working

### ISSUE THREAD

**Issue by shubham2924** [angular/angular#49034]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

This issue is intended for a special route edge case, citing [official documentation](https://angular.io/guide/router#setting-up-wildcard-routes) for the same.

So I've developed an app with angular and used  inbuilt routing provided by angular. Let me narrate the scenario:
There are various routes in the application in which wild card routing is added at the very end to show desired not-found component page. So URLs are like 

_https://mysite/api/books
https://mysite/api/users_
etc...

so if there is an invalid URLs such as _https://mysite/api/87*hfaabooks_, then not-found component shown correctly as I've added `{ path: '**', component: <not-found-component>, pathMatch: 'full' }` in the array of routes in appRoutingModule. But when an URL is like _https://mysite/65%^dfhapi/books_ , we can observe invalid characters aren't added in the very last route instead with _api_ word in the URL, so in this case it is redirecting to home page but as the URL is still invalid I want user to navigate to not-found-component.

Would like to if I'm missing anything, thanks in advance.
-Shubham

**Comment by JeanMeche** [comment]
Isn't your problem that a parent router doesn't match the `/api/` part of the route thus not triggering the last router where `**` is defined ? 

Could you provide a stackblitz demo reproducing your problem ?

**Comment by shubham2924** [comment]
Hey @JeanMeche thanks for reverting back.
This routing is small part of a huge project.

Yes, main intention is anything after Top level domain(e,g .com/) if there is a discrepancy in a URL at any point I want user to redirect to my not-found-component.
e.g https://github.com/angular/87y8954#@$angular/issues/49034
here if you hit the above URL in browser github shows you a not-found page, this is something I want to achieve but so far docs I've read they only cover part written along with let's say _/49034_ part
Thanks !

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
