### ISSUE TITLE
Allow @import inside ::ng-deep without any warning 

### ISSUE THREAD

**Issue by montella1507** [angular/angular#49031]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

Motivation:
The main motivation for this is better code splitting.  Imagine we have 3rd party component library with huge amount of CSS - which is delivered as 1 SCSS file (component styles are not used in the library)

Examples:
- PrimeNG
- Kendo

You have 2 options how to use their styles to use their components:
- include all used SCSS "partials" to your style.scss - this will ADD 2MB of CSS to your main initial styles chunk
- create a wrapper for particular component (for the instance - a data griad) and import required CSS to component style like this:
```
:host::ng-deep {
  @import "primeng/resources/components/table/table.css";
}
```

So 3rd party style will be loaded on demand, only when needed and  removed from DOM when not required anymore.  It will be packed to JS chunk with our "grid-wrapper" component.

Result:
- it works like a charm
- it is great for initial bundle size 
- it is loaded, parsed and "used" only when it is actually used in portal (in particular view)
- it is great example why WE NEED NG DEEP

Problem:
- we cannot disable ViewEncapsulation, because there are other CSS rules, which have to be encapsulated
- after migration to latest angular,  we got warnings

`
 [WARNING] "@import" is only valid at the top level [invalid-@import]
components/datagrid/datagrid.component.scss:2:2:
      2 │   @import "primeng/resources/components/table/table.css";
        ╵   ~~~~~~~
`

### Proposed solution

Provide a way how to disable this warning, because it is legit and only way how to make this possible

### Alternatives considered

Build this style by angular with { inject: false} and load it manually with some kind of Directive and manually appending to DOM (head). This will be HUGE overhead though.

**Comment by mlc-mlapis** [comment]
Doesn't `::ng-deep` always mean that CSS styles are applied globally? And that's why the warning `@import" is only valid at the top level ...`?

**Comment by montella1507** [comment]
Hi my Friend!

This is why it is inside :host() so it is scoped by component even if there is :: ng-deep coming after.

**Comment by JoostK** [comment]
This warning is reported by esbuild and is legitimate; CSS imports have to be at the top-level.

What you are trying to do requires that the CSS preprocessor, SASS in this case, inlines the `@import` contents into the consuming rule. [SASS is capable of doing this](https://sass-lang.com/documentation/at-rules/import#nesting), but only [if the `@import` does not indicate that CSS semantics are required](https://sass-lang.com/documentation/at-rules/import#plain-css-imports). Your code is using an explicit `.css` extension and hence the `@import` is preserved, but this puts it into an invalid position.

**Comment by montella1507** [comment]
@JoostK Hi! Thanks for the explanation.
