### ISSUE TITLE
Newbie: Angular 2 with Typescript deletes javascript <script> tags

### ISSUE THREAD

**Issue by vicaba** [angular/angular#4903]
I have a template index.html for an angular 2 typescript basic application. This template has javascript 5 in it. For example, it loads some jQuery libraries. The problem is that the tags in the template are not parsed, they are deleted. Is there a way to prevent angular 2 or whatever engine is being used from deleting the tags? Or should I change the tags for something else?

Example Tag: 
```<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>```

Thanks,

**Comment by robwormald** [comment]
script tags should be in `index.html` page, or potentially loaded via a script loader (ie SystemJS) - script tags in templates will not work.

**Comment by thelgevold** [comment]
It's totally fine to load other JS libraries in the same application. In fact I have an example of that in my sample components here: http://www.syntaxsuccess.com/angular-2-samples/#/demo/spreadsheet

Just inspect the DOM and you will see how I am loading, React, jQuery and underscore outside angular 2.0. Just add it in index.html like @robwormald suggests.  The Angular part is basically its own sandbox, so you can do whatever you want outside of it.

**Comment by pkozlowski-opensource** [comment]
@vicaba we are removing `<script>` tags from templates on purpose as you shouldn't use those to load code on demand. 

I hope that others answered your question in more details.

**Comment by tschaka1904** [comment]
@robwormald how would you do that using webpack? Do I've to add the script to the index.html or can I somehow add it to the component? I would like to avoid to add it globally. 

My problem is, that the script is not exposing itself as a module.

**Comment by tagazok** [comment]
What about if I want to add, let say, a twitter follow button in my template ?
The code looks like this but the script tag is removed and though, the button does not appear as it sould :/

```html
<a href="https://twitter.com/olivierleplus" class="twitter-follow-button" data-lang="en" data-show-count="false">Follow @olivierleplus</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```

**Comment by bbottema** [comment]
I too am trying to combine webpack2/angular2+ with externals libraries, which depend on scripts loaded by webpack. 

For example JQuery won't be loaded yet if I put these scripts in the head, but if I nest these scripts in a component's template they are removed by Angular. Now obviously jQuery could be fixed by including it twice in a no-conflict mode, but obviously that's suboptimal. Not to mention other external libraries that cannot be solved this way.

**Comment by res63661** [comment]
This is still an issue for me.  What is the workaround?

**Comment by caztial** [comment]
issue is trying to put JSON-LD properties to the template since it is the recommended way in google

**Comment by res63661** [comment]
I was able to get it to work like this:
1) add some element via sanitizer.bypassSecurityTrustHtml()
```
this.html = sanitizer.bypassSecurityTrustHtml(`<div id="#9284374__uniqueID__"></div>`);
```
2) now that you have a fixed id to index, use js or jquery to index the element and then add additional markup using js
```
    var sDlg = document.createElement("div");
    sDlg.className = "some-class"
    document.getElementById("#9284374__uniqueID__").appendChild(sDlg);
    sDlg.innerHTML = `<more html content>`;
```

**Comment by Mc128k** [comment]
It sounds right to me, as the libraries are to be loaded by the client only, and the code is "compiled" from typescript before being served, there is no way to do it dynamically from TS. So could using the bypass function be considered a "best practice"?

**Comment by hackerunet** [comment]
I'm not very sure, but, I think the bypasssecurity in the sanitizer does not allow <script> tags to be rendered in the template, I have the same issue creating a wordpress angular SPA theme, the WP API returns html with embedded jquery code so this code is not working, is there a way to retrieve html content via http client and run any returned jquery code embedded to the respond??

**Comment by ORESoftware** [comment]
workaround might be to dynamically add the script tag using JavaScript?

```js
    let el = document.createElement('script');
    el.setAttribute('src', 'https://platform.twitter.com/widgets.js');
    document.body.appendChild(el);
```

**Comment by aswinsanakan** [comment]
You could load the dynamic scripts like this in your `component.ts` file: 
```ts
 loadScripts() {
    const dynamicScripts = ['https://platform.twitter.com/widgets.js'];
    for (let i = 0; i < dynamicScripts.length; i++) {
      const node = document.createElement('script');
      node.src = dynamicScripts[i];
      node.type = 'text/javascript';
      node.async = false;
      node.charset = 'utf-8';
      document.getElementsByTagName('head')[0].appendChild(node);
    }
  }
```
and call this method inside the constructor.

Note : For multiple dynamic scripts to be loaded, add them to `dynamicScripts`.

**Comment by trainerbill** [comment]
Is there anyway to disable this?  I don't care about best practices, as I'm not creating a production app. I have an Angular app that I am demoing a library that is to be used in a non Angular environment.  So i am going to record my screen and want the scripts to be present in the elements tab so I can explain them.

```
<script src="..."></script>
<script>
   // Usage
</script>
```

**Comment by MicMicMon** [comment]
> and call this method inside the constructor.

If I'm not mistaken, you add this to the `head` at each component load. Which is not what you want (unless you remove them in `OnDestroy`). You are better off adding this inside an element of your component.
