### ISSUE TITLE
Get a console hint or alternative content when browser is too old

### ISSUE THREAD

**Issue by bttb** [angular/angular#49032]
### Description

After updating angular to 15 some people told me, my website is not working on their browser - users only see a blank page with no more information, not on the website and not on the console. After a while I found out, that this is a problem for iOS browsers (all browsers, not just Safari, but also Chrome etc) on old iPads or old iPhones (these can't get updates for iOS anymore). It took me a while to find a solution, and on the way to the solution I also found issue #48339, an issue with basically the same problem but no solution. But in #48339 I saw, that angular.io is not running on these devices, too. And same with v14.angular.io - but v13.angular.io is running.

### Proposed solution

What I want to have is a hint, why the user gets nothing but a blank page. 

The console hint should be s.th. like "This browser version / iOS version is not supported. For more information, see https://angular.io/guide/build#configuring-browser-compatibility " 

### Alternatives considered

In my index.html I added some pure JavaScript to log s.th. on the console - and this appeared on the console, but nothing more.

The solution I found is descibed under "Configuring browser compatibility" on angular.io: Internally, the Angular CLI uses a browser support configuration, which reads `last 2 iOS major versions`. To override the internal configuration, run `ng generate config browserslist`, which generates a `.browserslistrc` configuration file in the the project directory. Here you can change that line - I changed it to `last 4 iOS major versions`, and I also changed `target` to `ES2020` in my `tsconfig.json`.

**Comment by JeanMeche** [comment]
First question, do you still have this issue after updating to 15.1 ?

**Comment by bttb** [comment]
Yes, my version is 15.1.2

**Comment by pkozlowski-opensource** [comment]
Angular has a well-defined [browser support policy](https://angular.io/guide/browser-support) and applications might require polyffils / other adjustments to support older browsers.

It is not practical for the framework to warn about unsupported browsers. Doing so in the production mode would require shipping mode code (browser detection code, error logging code etc.) and would penalise applications that don't require such warning. 

It would be easier for us to provide such warning in the development mode but I'm not sure how much value it would add given that most developers test with the latest browsers.

All in all: while I can understand and relate to this feature request, I don't think it is feature we would like to support in the framework.
