### ISSUE TITLE
Simplified InnerText access

### ISSUE THREAD

**Issue by jsenaribeiro** [angular/angular#49041]
### Description

When we need get just a innerText in Angular is need <ng-content /> wrapped with hidden element, a elementRef injection and one life-cycle to get the information.

### Proposed solution

ng-inner would be a hidden ng-content alternative just to get the elementRef content

````html
<ng-inner [text]="label" /> // copy inner text to label field in component 
````

### Alternatives considered

An alternative is allow a hidden ng-content and get events to receive its elementRef

````html
<ng-content hidden (on)="label = $event.nativeElement.innerText"  />
````

**Comment by JeanMeche** [comment]
Hi, what would be a use case for that kind of feature ?

**Comment by pkozlowski-opensource** [comment]
We do not have plans for any spacial APIs to read from the DOM - please use the existing browser APIs.
