### ISSUE TITLE
Need to be able to specify providers for standalone Pipes

### ISSUE THREAD

**Issue by Maximaximum** [angular/angular#49043]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Currently there is no way to reuse an existing pipe or service inside a standalone pipe. 

### Proposed solution

We should be able to specify providers for a pipe, just like we do for components and directives

```
@Pipe({
  name: 'formControlValue',
  providers: [DatePipe]
})
export class FormControlValuePipe implements PipeTransform {
  constructor(
    private datePipe: DatePipe
  ) {}

  transform(value: any, type: string) {
    switch (type) {
      case 'date':
        return this.datePipe.transform(value as string);
    }

    return value;
  }
}
```

### Alternatives considered

The only workardound available is using a non-standalone pipe:

```typescript
@NgModule({
  declarations: [FormControlValuePipe],
  exports: [FormControlValuePipe],
  providers: [DatePipe],
})
export class FormControlValueModule {}

@Pipe({
  name: 'formControlValue',
})
export class FormControlValuePipe implements PipeTransform {
  constructor(
    private datePipe: DatePipe
  ) {}

  transform(value: any, type: string) {
    switch (type) {
      case 'date':
        return this.datePipe.transform(value as string);
    }

    return value;
  }
}
```

However, this forces developers to abstain from using standalone pipes and sticking to otherwise redundant `NgModule`s.

**Comment by pkozlowski-opensource** [comment]
One thing that should be noted is that providing a service on a NgModule level is _roughly_ equivalent of providing a service via `@Injectable(providedIn: 'root')`. In other words - providers are _not_ scoped to a NgModule (this is a common misconception I see) but rather _all providers_ are folded into the root injector (!). So you could just register the desired pipe on the root / when bootstrapping an application - this would be equivalent to registering it on a NgModule, really.

Then, pipes are meant to be used as a formatting facility in a template, _not_ as generic providers. We never intended pipes to act as providers. In the particular case of the `DatePipe` you would be better off reusing the [formatDate](https://angular.io/api/common/formatDate) function directly.

I'm going to close this one as I don't think we want to introduce providers on a pipe level. The `NgModule` equivalent behaviour can be achieved today without NgModules and an alternative (arguably better) solution exists for the `DatePipe`

**Comment by Maximaximum** [comment]
@pkozlowski-opensource Thanks for your quick response. However, I'd like to share my feedback:

1. Although what you've written is true, Angular still for whatever reason provides a way to define providers as an option to `@Component()` and `@Directive()` decorator calls. But this is not an option for `@Pipe()` Is there any conceptual reason for why `@Pipe()` should be different?

2. > Then, pipes are meant to be used as a formatting facility in a template, not as generic providers. We never intended pipes to act as providers.

If the Angular team never intended pipes to act as providers, then Angular has an issue that it does not provide a clean way to reuse an existing pipe by another pipe. This issue should be addressed IMO.

3. >  In the particular case of the DatePipe you would be better off reusing the [formatDate](https://angular.io/api/common/formatDate) function directly.

I'd love to be able to use the pipe itself, because `formatDate` is different from `DatePipe`: it has 3 non-optional parameters instead of 1, and in order to be able to use it the same way as `formatDate` I would need to inject even more stuff into my custom pipe.

**Comment by pkozlowski-opensource** [comment]
>  But this is not an option for @Pipe() Is there any conceptual reason for why @Pipe() should be different?

Yes, pipes don't have "children" in a template.

> If the Angular team never intended pipes to act as providers, then Angular has an issue that it does not provide a clean way to reuse an existing pipe by another pipe. This issue should be addressed IMO.

Pipes are really not meant to be composed - same as you can't compose, say, binding syntax. This could be seen as a limitation or a design choice. 

> I'd love to be able to use the pipe itself, because formatDate is different from DatePipe: it has 3 non-optional parameters instead of 1, and in order to be able to use it the same way as formatDate I would need to inject even more stuff into my custom pipe.

Understood - the `formatDate` is more flexible here and while might not be 100% what you are looking for it is a reasonable path forward. 

Thnx for sharing your input / thinking - appreciate it - even if the providers on the pipe level are not what we want to support.

**Comment by Maximaximum** [comment]
> Yes, pipes don't have "children" in a template.

Well, Directives don't have a template neither, but they do have the `providers` property.

> Pipes are really not meant to be composed - same as you can't compose, say, binding syntax. This could be seen as a limitation or a design choice.

Got it, fair enough. Although it could be a point for Angular improvement.

Generally, thanks for your time and appreciation. I just really believe that the Angular mental model could benefit from a simplification by removing unreasonable (IMO) differences like this one.
