### ISSUE TITLE
Import context in standalone

### ISSUE THREAD

**Issue by ziedzayani** [angular/angular#49052]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

**I have this custom directive :** 
import { Directive, HostListener, inject, Input} from '@angular/core';
import { MatTooltip } from '@angular/material/tooltip';

@Directive({
  selector: '[appCustomTooltip]',
  exportAs: 'appCustomTooltip',
  providers: [MatTooltip]
})
export class CustomTooltipDirective{

  @Input('appCustomTooltip') customTooltipText!: string;
  matTooltip = inject(MatTooltip);

  @HostListener('mouseover') mouseover() {
    this.matTooltip.message = this.customTooltipText;
    this.matTooltip.show();
  }
  @HostListener('mouseleave') mouseleave() {
      this.matTooltip.hide();
  }
}

**This worked for me because the custom directive was declared in the module and shares the context of the module (MatTooltipModule was imported in the module).**

Now I am trying to do the same thing with a standalone custom directive but it is not working because we do not have the option to import the **MatTooltipModule** in the context of the custom directive.

**I am trying to do this in order to use my standalone custom directive with the composition API directive.**

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.1.5
Node: 18.12.1
Package Manager: npm 8.19.2
OS: linux x64

Angular: 15.1.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.5
@angular-devkit/build-angular   15.1.5
@angular-devkit/core            15.1.5
@angular-devkit/schematics      15.1.5
@angular/cdk                    13.0.0
@angular/cli                    15.1.5
@angular/material               13.0.0
@schematics/angular             15.1.5
rxjs                            7.5.7
typescript                      4.9.5
```

**Comment by JeanMeche** [comment]
During the [RFC](https://github.com/angular/angular/discussions/43784), it was considered that the `imports` only made sense for components. 

But you are making a compelling argument for it imo.

**Comment by pkozlowski-opensource** [comment]
From what I can understand, here the `MatTooltip` is used as a DI _provider_, which I don't think was intended by the authors - it is a directive meant to be used in a template. Nothing prevents people from registering _providers_ on a directive level - standalone or not.

Providers from the `MatTooltipModule` can still be imported using https://angular.io/api/core/importProvidersFrom, on the application level, if needed.

It sounds like the unsupported, corner case, where some logic is reused in the un-intended way. It _can_ be made working with standalone components, but I don't think that is a compelling argument to revisit the initial design.

**Comment by ziedzayani** [comment]
**Thank you for your reply.** 

The directives used in hostDirectives should be standalone, but (such as Material, PrimeNG ...) have not been migrated to standalone yet. 

Therefore, I am attempting to create a custom standalone directive that extends the functionality of a non-standalone directive, so that it can be used with the composition API Directive.

Is it intended to use non-standalone directives in hostDirectives or is there a workaround?

**Comment by pkozlowski-opensource** [comment]
> Is it intended to use non-standalone directives in hostDirectives or is there a workaround?

There is no work-around and we don't plan on providing one: the intention is that only standalone directives can be used as host directives. We understand that it might take a while before the entire ecosystem catches up and converts most directives to standalone.
