### ISSUE TITLE
Dynamic Components are not working with Projectable Nodes

### ISSUE THREAD

**Issue by anjunar** [angular/angular#49050]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

When doing dynamic Components and using the projectableNodes parameter, the projected Node has no changedetection.

````
export class AppComponent {

  constructor(private viewContainer : ViewContainerRef, private resolver : ComponentFactoryResolver, private injector : Injector) {}

  onClick() {

    let componentFactory = this.resolver.resolveComponentFactory(ChildComponent);
    let componentRef = componentFactory.create(this.injector);
    componentRef.instance.text = "Hello World"
    
    // Must be called to update the Binding. Change detection doesn't work on ChildComponent
    componentRef.changeDetectorRef.detectChanges()

    this.viewContainer.createComponent(ContainerComponent, {projectableNodes : [[componentRef.location.nativeElement]]})

  }

}
````

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.4
Node: 19.6.0 (Unsupported)
Package Manager: npm 9.4.2
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1501.4 (cli-only)
@angular-devkit/core         15.1.4 (cli-only)
@angular-devkit/schematics   15.1.4 (cli-only)
@schematics/angular          15.1.4 (cli-only)
```

### Anything else?

Here is the source code: https://github.com/anjunar/angular2

Here is the Demo: https://anjunar.github.io/angular2

**Comment by JoostK** [comment]
This is working as expected; the dynamically component is not attached to a parent view; it's only its rendered DOM that is passed as projectable node to a child view. This does not associate it with a parent view to inherit its change detector; you have to manually attach the dynamically created components [using `ApplicationRef.attachView(componentRef.hostView)`](https://angular.io/api/core/ApplicationRef#attachView).

**Comment by anjunar** [comment]
@JoostK I am very thankful for the solution.

Is there a way to not use the ComponentFactoryResolver, because it is deprecated?

**Comment by JoostK** [comment]
Using [`createComponent`](https://angular.io/api/core/createComponent)
