### ISSUE TITLE
forwardRef() docs implies it only works for providers

### ISSUE THREAD

**Issue by Jordan-Hall** [angular/angular#49059]
### Describe the problem that you experienced

I had the following issue today regarding circular dependency with standalone components:
`FolderListComponent => OrphanVerificationComponent => MoveCopyRecordModalComponent => FolderListComponent`

I remembered forwardRef fixes issues with constructor but it was unclear that it can be used to resolve standalone imports array

### Enter the URL of the topic with the problem

https://angular.io/api/core/forwardRef

### Describe what you were looking for in the documentation

Currently they two pages that help with this issue

1. https://angular.io/guide/dependency-injection-in-action#break-circularities-with-a-forward-class-reference-forwardref
2. https://angular.io/api/core/forwardRef

However looking at both pages it sounds like this would only work for providers and constructors. It wasn't clear it works in other locations especially imports when we come from module approach

**Comment by JeanMeche** [comment]
@jessicajaniuk You can also close this one 👍

**Comment by Jordan-Hall** [comment]
Been merged. Thank you 💙
