### ISSUE TITLE
Value of class object is lost when performing debug.

### ISSUE THREAD

**Issue by leandrotassi** [angular/angular#49051]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

When I assign the value of an object to a variable and after doing a for each of it, for example, the value is lost and I cannot see the content of the value within the iteration.

This seems to only happen at debug time.

I don't know is it a bug or some configuration that needs to be done.
I started having this problem after configuring "tsconfig.json" so that the code is strongly typed.

### Please provide the exception or error you saw

```true
There is no exception.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.5
Node: 18.13.0
Package Manager: npm 9.2.0
OS: win32 x64

Angular: 15.1.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.5
@angular-devkit/build-angular   15.1.5
@angular-devkit/core            15.1.5
@angular-devkit/schematics      15.1.5
@angular/cli                    15.1.5
@nguniversal/builders           15.1.0
@nguniversal/express-engine     15.1.0
@schematics/angular             15.1.5
rxjs                            7.8.0
typescript                      4.9.4
```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
