### ISSUE TITLE
Angular 15 and typescript 4.8 getting NG0202: This constructor is not compatible with Angular Dependency Injection because its dependency at index 0 of the parameter list is invalid.

### ISSUE THREAD

**Issue by qannoufoualidkaibee** [angular/angular#49069]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Hello,

After upgrading to angular 15 and typescript 4.8 from angular 14 and typescript 4.6, the dependency injection mechanism in my project is no longer working. please follow steps in the link to reproduce.

Thank you

### Please provide a link to a minimal reproduction of the bug

https://github.com/qannoufoualid/NG0202-reproduction

### Please provide the exception or error you saw

```true
NG0202: This constructor is not compatible with Angular Dependency Injection because its dependency at index 0 of the parameter list is invalid.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.5
Node: 16.13.2
Package Manager: pnpm 7.27.0
OS: linux x64

Angular: 15.1.4
... common, compiler, compiler-cli, core, language-service
... platform-browser, platform-browser-dynamic

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.5
@angular-devkit/build-angular   15.1.5
@angular-devkit/core            15.1.5
@angular-devkit/schematics      15.1.5
@angular/cli                    15.1.5
@schematics/angular             15.1.5
ng-packagr                      15.1.2
typescript                      4.8.4
```

**Comment by JoostK** [comment]
Please update `jest-preset-angular` to latest; 12.2.0 does not support Angular 15 and there was a fix in 12.2.1 to support decorators in TypeScript 4.8.
