### ISSUE TITLE
history errors with Angular and Chrome OS when Chrome version > 108

### ISSUE THREAD

**Issue by findsujay** [angular/angular#49066]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

We have an Angular app on Angular 10, which loads within a Chrome packaged app. This setup has been running well so far, but ever since Chrome version 109 (specifically, 109.0.5414.125) we are seeing console errors on Angular. 

The console errors show `history.pushState is not available in packaged apps` and `history.length is not available in packaged apps`. Our app does not use either `history.pushState` or `history.length`; and we suspect the Angular router is causing the issue. 

If we were to not use Angular router, for argument's sake, then the errors go away, further supporting the above suspicion. Of course, we can not forgo the router; so I am hoping we can get some guidance from the Angular dev team here.

To recreate this, I have provided a sample project at https://github.com/findsujay/chrome-packaged-angular-sample. 

**Please note:**
1. The issue does not occur when Chrome OS version is 108 or lower. 
2. This issue occurs in Angular 15 as well, so Angular version is not an issue. We do plan on upgrading to ng15, but that will not help for this issue.
3. We are aware that Chrome packaged apps are on their way out. Google has announced they will sunset support for them in 2024 for Chrome OS, and we will be moving to an alternative platform. Until then we need to keep the production app running.

### Please provide a link to a minimal reproduction of the bug

https://github.com/findsujay/chrome-packaged-angular-sample

### Please provide the exception or error you saw

```true
Please follow the instructions in the provided sample project to build, deploy and test the issue. You will see 2 errors:

Error 1: history.pushState is not available in packaged apps
Error 2: Cannot match any routes. URL Segment: 'index.html'

As observed above, the issue only occurs when Chrome OS version is 109 or higher. When Chrome version is 108 or lower, there are no errors.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 10.0.5
Node: 19.5.0
Package Manager: npm 9.3.1
Build OS: Win32 x64
Deployed OS: Chrome OS 109 and higher
Chrome OS version: 109.0.5414.125

Angular: 10.0.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1000.8
@angular-devkit/build-angular   0.1000.5
@angular-devkit/core            10.0.6
@angular/cli                    10.0.5
ng-packagr                      10.1.2
rxjs                            6.5.5
typescript                      3.9.7
```

**Comment by JeanMeche** [comment]
In #18653, @gkalpak suspected that this warning was triggered by a call to `window.history.pushState;` currently located here : 

https://github.com/angular/angular/blob/2ca49726ca0eaa6d427c5d9121fb9004c8780e88/packages/common/src/location/platform_location.ts#L202-L204

This is indeed used when using the router.

**Comment by atscott** [comment]
Routers for SPA frameworks use the modern history API to perform navigations. The prior art was to update the hash only and you can provide your own `PlatformLocation` that overrides the `pushState` method to just assign the value to the hash:
https://github.com/angular/angular/blob/be21eaa618ad156c83ba9821590ae99093a33ec5/packages/common/src/location/platform_location.ts#L169-L175
i.e. for your application, change the lines there to not even check for `pushState` in the browser if you're only shipping a packaged app or use a similar check to the AngularJS one if you ship your app as a normal web app as well.

**Comment by findsujay** [comment]
Hi @JeanMeche and @atscott,

Thanks for your guidance. I am not an expert at this so I have one more question:
I see errors with history.length as well (`history.length is not available in packaged apps`). And in Angular, history.length is referenced only in packages/common/testing/src/location_mock.ts

Any advice there?
