### ISSUE TITLE
Lifecycle of providers defined in route

### ISSUE THREAD

**Issue by Wykks** [angular/angular#49062]
### Which @angular/* package(s) are the source of the bug?

core, router

### Is this a regression?

No

### Description

Hi!

About this feature : https://angular.io/api/router/Route#providers

Currently, when leaving the route, providers defined in this route are not destroyed. (They're just "scoped" to this route)

This is not the case when we provide anything on component level, as they are destroyed when the component is destroyed.

I'm not sure if this is expected or not, as I'm not able to find any info on this.

My use case is a @ngrx/component-store provided on a route, and I would like to destroy it when leaving the route.
The store could be provided on the component, but this feature allows me to inject the store in guards, which is very convenient.

If this is expected, is there any way manually destroy the providers when leaving the route ?

I tried this : 
```
providers: [provideComponentStore(MyStore)],
canDeactivate: [() => inject(EnvironmentInjector).destroy()],
```

But it work only once, as it won't re-create the EnvironmentInjector next time I activate the route (resulting in "NG0205: Injector has already been destroyed.")

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 15.1.4
```

**Comment by JoostK** [comment]
This is working as designed at the moment, an issue to discuss alternative behavior is #37095.
