### ISSUE TITLE
schematics - publish utils that are internally used by angular

### ISSUE THREAD

**Issue by spike-rabbit** [angular/angular#49073]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

@angular/core has a few useful utilities for writing schematics. Before 15.1.0 they were part of the distributed @angular/core package. Now, they are no longer distributed.

For an angular library, they were quite handy to provide a smooth update experience similar to angular without rewriting the same things again.

### Proposed solution

It would be really awesome, if they could be published again.  If you could consider them as part of the public API would be even better.

### Alternatives considered

Copying code would also work. Existing 3rd party seems to be unmaintained (https://www.npmjs.com/package/schematics-utilities)

**Comment by pkozlowski-opensource** [comment]
We are tracking making schematic utilities as public in https://github.com/angular/angular-cli/issues/24204
