### ISSUE TITLE
Form Array filter issue 

### ISSUE THREAD

**Issue by devayazahmed** [angular/angular#49071]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

On search wrong value in table and then clear filter value we have found messed up in table or form. I gave you a link  
![Before Search](https://user-images.githubusercontent.com/124768996/219034631-c751ccf5-c829-4832-8474-2c9f74097027.PNG)
![image](https://user-images.githubusercontent.com/124768996/219034758-105dbb3d-e0bf-448c-8792-5951042aa3e3.png)
![image](https://user-images.githubusercontent.com/124768996/219034929-03b7bdfe-37c1-4292-931a-6db955f5a9b6.png)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-tcdjco?file=src%2Fapp%2Fapp.component.ts

**Comment by akhil27styles** [comment]
![image](https://user-images.githubusercontent.com/52193850/221395874-3df484b8-d915-4b3d-b727-f908c5767b3e.png)
like this it changing the values?

**Comment by travisbashor** [comment]
This isn't a bug, just a sneaky mistake.

In your template, you iterate over the values returned by your filtered `formArr$` observable but you use the indices from that observable collection to access members of the plain `formArr` on the class.

There are probably a few ways you could do what you're trying to do, but it may be easier to just keep a whitelist of indices up-to-date as the search term is updated, and then ngFor over the whitelist to pick controls to show in the template.

Here's an example: https://angular-tn8tcw.stackblitz.io

**Comment by alxhub** [comment]
Closing as the bug is in user code, not forms.
