### ISSUE TITLE
ApplicationRef's onDestroy method should not be internal

### ISSUE THREAD

**Issue by edusperoni** [angular/angular#49087]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

When developing with NgModules we were able to do:

```
const moduleRef = await platformBrowserDynamic().bootstrapModule(AppModule);
moduleRef.onDestroy(() => { /* some logic */ });
```

The new `bootstrapApplication` now returns a `ApplicationRef`. Although the `onDestroy` method exists in `ApplicationRef`, it's marked as internal and not exposed.

### Proposed solution

Make `ApplicationRef.onDestroy` not internal and part of the public API. This makes sense as well because `.destroy()` and `.destroyed` are part of the public API.

### Alternatives considered

```
(applicationRef as any).onDestroy(() => {});
```

or getting the reference to the first component and using its `onDestroy`.

**Comment by JeanMeche** [comment]
FYI, making `onDestroy` public has been discussed as part of #45624. 

@AndrewKushnir wasn't opposed to making it public if a use case arises !

**Comment by edusperoni** [comment]
@AndrewKushnir if you're fine with it, I can do the PR to expose it. We use it in NativeScript to manage the Angular bootstrap and application launch/exit events.

**Comment by AndrewKushnir** [comment]
@edusperoni yes, that makes sense, feel free to open a PR 👍
