### ISSUE TITLE
Testing guide only partially available

### ISSUE THREAD

**Issue by siritsch** [angular/angular#4908]
Chapters 5 - 9 of the Angular 2 Testing guide are not available through the website. In the menu there are only chapters 1 - 4 available and at the end of chapter 4 “Testing an Angular Pipe“ there is no link to the next chapter. I'm using latest silk browser from a Kindle HD fire tablet.

**Comment by pkozlowski-opensource** [comment]
@siritsch right, dev guides are still work in progress. Those live in https://github.com/angular/angular.io, could we please move the issue in there?
