### ISSUE TITLE
Cancel component's host event

### ISSUE THREAD

**Issue by tbragaf** [angular/angular#4909]
Hi all!

How can I cancel a component's host event?

This is what I need:
```html
<my-button (click)="doSomething()">Click!</my-button>
```

And this is MyButton Component:
```javascript
@Component({
  selector: 'my-button',
  inputs: [
    'disabled: disabled'
  ],
  host: {
    '(click)': 'onClickEvent($event)'
  }
})
export class MyButton {
 onClickEvent(event) {
    if(this.disabled) {
      event.stopPropagation();
    }
  }
}
```

Is there any way I can achieve this?

Thanks in advance,
Tiago Braga

**Comment by todoubaba** [comment]
http://plnkr.co/edit/j9M6VFeb3ZL2kj2AYsWI?p=preview

**Comment by tbragaf** [comment]
@todoubaba I saw your comment you gitter, and forgot to close this ^^
Thank you! :)
