### ISSUE TITLE
Angular version is out of sync

### ISSUE THREAD

**Issue by yuchuan1** [angular/angular#49097]
### Which @angular/* package(s) are the source of the bug?

angular

### Is this a regression?

No

### Description

On [github](https://github.com/angular/angular/tags) , the latest angular cli version is 15.1.5 but on yarnpkg or npm the latest version is 15.1.6

**Comment by JoostK** [comment]
You are probably looking at [the CLI's 15.1.6 version](https://www.npmjs.com/package/@angular/cli?activeTab=versions), versus [the framework's 15.1.5 version](https://www.npmjs.com/package/@angular/core?activeTab=versions). The CLI is independently released from the [angular/angular-cli](https://github.com/angular/angular-cli) repo.
