### ISSUE TITLE
Dart style: annotate methods without return values as void

### ISSUE THREAD

**Issue by kevmoo** [angular/angular#491]

**Comment by alexeagle** [comment]
After poking at this a bit, I run into the problem that many functions in the angular AtScript code don't declare a return type, but have a return statement. That means I can't just check the type info to determine if it is void, but have to peek ahead down the AST to see if there is a return from this scope, to infer if it's truly void.

**Comment by kevmoo** [comment]
Could we annotate methods with `void` per http://www.typescriptlang.org/Handbook#basic-types-void

**Comment by alexeagle** [comment]
Yes, I was discussing that possibility with Tobias.
My concern is it won't be very useful so long as devs are still adding void functions but not declaring them void. I think we need some kind of tooling for this like a linter.

**Comment by kevmoo** [comment]
Make the AtScript compiler yell if one creates a function without a return type definition.

Seriously.

You light up a lot of great analysis from Dart – not to mention making the API/docs a lot more clear for users.

**Comment by alexeagle** [comment]
My personal preference is for more explicit typing. But after discussing with @rkirov I get the sense that the team would rather not explicitly type functions as "void".
Note that even if we did put the void, there is some bug where this doesn't make it through the transpiler into dart. That's probably not fixing unless we intend to start typing AtScript functions as void.

Without types declared in the input, I think it's too hard for the transpiler to infer it.

**Comment by kevmoo** [comment]
I strongly disagree. If a return type is omitted, a user can expect *something* to be returned. Return types *and* argument types should be as explicit as possible.

I have no problem if AtScript is ambivalent about void.

Dart style *absolutely* has an opinion about this. If we're generating a Dart API, it should follow our best practices.

**Comment by rkirov** [comment]
There was a slight misunderstanding here. The proposed solution in #529 was unacceptable as it replacing the lack of return type with 'void'. The lack of type declaration in AtScript source should be left as a lack of type declaration in dart. It is not the transpiler's job to infer and add types.

The bug about `void` being omitted during transpiration is valid and should be fixed.

Finally, I agree with dart's style guide - https://www.dartlang.org/articles/style-guide/#prefer-providing-type-annotations-on-public-apis. However, at the current time it is not clear what exactly is Angular's public API and which APIs will be kept internal (where as @alexeagle said I am ok with omitting types). When we get closer to defining the public API surface, we should annotate all argument and return types (including `void`.)

I will reopen this issue for the time being, but most likely it will be rolled under a larger issue of defining a style guide for Angular2's codebase (and cleaning up the code).

**Comment by kevmoo** [comment]
Awesome. Thanks!

**Comment by yjbanov** [comment]
After chatting with @tbosch about this we agreed on the proposal outlined here: https://github.com/angular/ts2dart/issues/4. In Angular 2 code if anything is returned at all it should have a return type. Lack of type is assumed to be `void` as a matter of style. Of course, specifying `void` explicitly in TypeScript should be ok too. Let's continue the conversation in the ts2dart repo. Closing this one.
