### ISSUE TITLE
Refused to apply inline style  while nonce is available in the Content Security Policy header

### ISSUE THREAD

**Issue by amanplans** [angular/angular#49104]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Line 83 of the file layout.mjs which is part of the Angular CDK throws the following error:

`
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-EinOpauVzQr0n6wq5ptWvkI/' fonts.googleapis.com". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.
`

As you see a nonce is available and layout.mjs still refuses to apply the in inline style.

I have created a separate project to reproduce this issue. It is a .NET Framework 4.8 MVC application with Angular 15 embedded in it. The MVC application creates the nonce and it is retrieved in the Angular SPA by following the workaround in this comment https://github.com/angular/angular/issues/6361#issuecomment-860180755

### Please provide a link to a minimal reproduction of the bug

https://github.com/amanplans/csp-header

### Please provide the exception or error you saw

```true
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-EinOpauVzQr0n6wq5ptWvkI/' fonts.googleapis.com". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```
Angular CLI: 15.1.5
Node: 16.13.2
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 15.1.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.5
@angular-devkit/build-angular   15.1.5
@angular-devkit/core            15.1.5
@angular-devkit/schematics      15.1.5
@angular/cli                    15.1.5
@schematics/angular             15.1.5
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by alan-agius4** [comment]
Addressed via https://github.com/angular/angular/pull/49561
