### ISSUE TITLE
ContentChildren decorator with static flag

### ISSUE THREAD

**Issue by GeorgianStan** [angular/angular#49105]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

The documentation and the type declaration for `ContentChild` states that the `static` flag is not supported. Therefore, writing the following code `@ContentChildren(ChildCmp, { static: true }) childCmps! : QueryList<ChildCmp>;`, will throw an error and the application will not be compiled.

However, if we bypass the error using `//@ts-ignore` and compile the application, the flag `static` does it's job. 

```ts
ngOnInit() {
    console.log(this.childCmps); // static flag works, and childCmps will include the QueryList
  }
```

Looking at the type definition we see 

```ts
/**
 * Type of the ContentChildren metadata.
 *
 *
 * @Annotation
 * @publicApi
 */
export declare type ContentChildren = Query;

/**
 * ContentChildren decorator and metadata.
 *
 *
 * @Annotation
 * @publicApi
 */
export declare const ContentChildren: ContentChildrenDecorator;
```

On one hand `ContentChildrenDecorator` doesn't include the `static` flag, but the type for the `ContentChildren` is `Query`, which includes this option.

Is there a mistake with the data types because the `static` flag actually works?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-s7xwpq?file=src/main.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular/core: 15.5.1
```

**Comment by JeanMeche** [comment]
Hi, there is already an issue about this at #36876.

**Comment by JoostK** [comment]
> Hi, there is already an issue about this at #36876.

You beat me to finding it :-)
