### ISSUE TITLE
Angular 15 breaks browser extensions that rely on __ngContext__ to access view data

### ISSUE THREAD

**Issue by IntiDC** [angular/angular#49102]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

PR [#45051](https://github.com/angular/angular/pull/45051) removes access to `LView`s through accessing an Angular's element `__ngContext__` property through the DOM. The only way for browser extensions to interact with Angular apps' data flow, was to iterate through the component's properties through the `__ngContext__` object, as Chrome extensions run in `production mode` ([source](https://stackoverflow.com/questions/40809192/calling-angular2-component-methods-from-console-in-production-mode)).

It looks like Angular 15 removes access to these `LView`'s, replacing them with a unique ID, yet the mapped list of these `LView`s does not seem to be accessible by browser extensions in `prod` mode, effictively breaking them.

Solution could be to expose the list of `LView`s, through a window object or function, so these extensions can fetch the numeric ID from the __ngContext__ property and then accessing their reference in the mapped list.

### Please provide a link to a minimal reproduction of the bug

javascript:console.log(getAllAngularRootElements()[0].__ngContext__);//now returning 0 instead of actual data

### Please provide the exception or error you saw

```true
N/A, it returns a numberic ID instead of the data needed for these extensions to function, and there does not seem to be any workaround.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 15.1.4
Browser: Chrome
```

**Comment by JoostK** [comment]
`LView` data structures are very much internal implementation details and not designed to be available/interacted with externally.

[The APIs that are public](https://angular.io/api/core/global) are only available in development mode, and per https://github.com/angular/angular/issues/37565#issuecomment-715617387 it's generally impractical to add debugging facilities ad-hoc.

Which extension are you referring to here?

**Comment by IntiDC** [comment]
In this case, it's an internal extension, but I assume that, in general, this means that browser extensions are no longer able to interact with Angular apps?

**Comment by JoostK** [comment]
> In this case, it's an internal extension, but I assume that, in general, this means that browser extensions are no longer able to interact with Angular apps?

Not concerning the Angular view tree, indeed; inspecting the view tree has always relied on APIs that are only present in development builds.

**Comment by atscott** [comment]
Closing. As Joost described, these are internal data structures without official external support.
