### ISSUE TITLE
Angular standalone. Global error handler is not registered unless imported from module.

### ISSUE THREAD

**Issue by gtgpest** [angular/angular#49103]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

As per title.

No dice:
```
export class GlobalErrorHandler implements ErrorHandler {
  handleError(error: any): void {
    console.log("Error from global error handler:", error);
  }  
}

bootstrapApplication(AppComponent, {
 providers: [{ provide: ErrorHandler, useClass: GlobalErrorHandler }]
})
```
Works fine when imported from module:
```
export class GlobalErrorHandler implements ErrorHandler {
  handleError(error: any): void {
    console.log("Error from global error handler:", error);
  }  
}

@NgModule({
  providers: [{ provide: ErrorHandler, useClass: GlobalErrorHandler }],
})
export class GlobalErrorHandlerModule {}


bootstrapApplication(AppComponent, {
 providers: [
 importProvidersFrom([GlobalErrorHandlerModule])
 ]
})
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.6
Node: 18.12.1
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 15.1.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker
```

**Comment by pkozlowski-opensource** [comment]
This is unexpected, definitively the registration method shouldn't make the difference. 

What is the exact error that you are trying to handle? Would you mind sharing a stackblitz with the exact scenario? Thnx!

**Comment by gtgpest** [comment]
> What is the exact error that you are trying to handle? Would you mind sharing a stackblitz with the exact scenario? Thnx!

Tried with simple `throw` new error and with various `http client` request errors.
Will share stackblitz later today.

Cheers

**Comment by gtgpest** [comment]
After further digging, I found that the culprit is in providing
`BrowserAnimationsModule` after `ErrorHandler` in app bootstrap.

I don't know if that is intended behavior or not, but here is [stackblitz](https://stackblitz.com/edit/angular-iutq3w?file=src%2Fmain.ts).

**Comment by JeanMeche** [comment]
Actually, it works when called after `importProvidersFrom()` no matter the arguments ! (an empty call works too !)

**Comment by JeanMeche** [comment]
It's the `BrowserModule` that has an `ErrorHandler` provider. 

https://github.com/angular/angular/blob/be21eaa618ad156c83ba9821590ae99093a33ec5/packages/platform-browser/src/browser.ts#L199-L206

Calling `importProvidersFrom()` after your provider will erase it.

**Comment by gtgpest** [comment]
Well, that sorts it out, thank you.
Going to close this.
