### ISSUE TITLE
router: `The ActivatedRoute has an invalid structure` warning improvements

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#49116]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

#47988 introduced a warning in dev when the ActivatedRoute has an invalid structure

This ends up generating quite a lot of noise when updating existing tests as the warning is outputted several times per test.

For example, consider this small repro https://stackblitz.com/edit/node-1bky4j?file=repro/src/app/home/home.component.spec.ts (run `ng test`)

The template has just a `routerLink`, and the test provides a "fake" ActivatedRoute (usually with params, but the point is that it's partial and thus incomplete).

This ends up generating:

```
✔ Browser application bundle generation complete.
WARN: 'The ActivatedRoute has an invalid structure. This is likely due to an incomplete mock in tests.'
Firefox 109.0 (Mac OS 10.15): Executed 2 of 5 SUCCESS (0 secs / 0.03 secs)
WARN: 'The ActivatedRoute has an invalid structure. This is likely due to an incomplete mock in 
WARN: 'The ActivatedRoute has an invalid structure. This is likely due to an incomplete mock in tests.'
Firefox 109.0 (Mac OS 10.15): Executed 2 of 5 SUCCESS (0 secs / 0.03 secs)
WARN: 'The ActivatedRoute has an invalid structure. This is likely due to an incomplete mock in 
WARN: 'The ActivatedRoute has an invalid structure. This is likely due to an incomplete mock in tests.'
Firefox 109.0 (Mac OS 10.15): Executed 3 of 5 SUCCESS (0 secs / 0.045 secs)
WARN: 'The ActivatedRoute has an invalid structure. This is likely due to an incomplete mock in 
WARN: 'The ActivatedRoute has an invalid structure. This is likely due to an incomplete mock in tests.'
Firefox 109.0 (Mac OS 10.15): Executed 3 of 5 SUCCESS (0 secs / 0.045 secs)
WARN: 'The ActivatedRoute has an invalid structure. This is likely due to an incomplete mock in 
WARN: 'The ActivatedRoute has an invalid structure. This is likely due to an incomplete mock in tests.'
Firefox 109.0 (Mac OS 10.15): Executed 4 of 5 SUCCESS (0 secs / 0.05 secs)
WARN: 'The ActivatedRoute has an invalid structure. This is likely due to an incomplete mock in 
WARN: 'The ActivatedRoute has an invalid structure. This is likely due to an incomplete mock in tests.'
Firefox 109.0 (Mac OS 10.15): Executed 4 of 5 SUCCESS (0 secs / 0.05 secs)
WARN: 'The ActivatedRoute has an invalid structure. This is likely due to an incomplete mock in 
Firefox 109.0 (Mac OS 10.15): Executed 5 of 5 SUCCESS (0.086 secs / 0.054 secs)
```

A few questions:
- is the warning really necessary in that case? It's hard to understand (from the warning alone, and even after looking at #47988) in what way this is an issue
- if the warning is necessary and something needs to be fixed for an upcoming change, maybe the warning could include a bit more information on how to do so? I suppose that most developers that are going to run into it will ask the same question. I'll gladly submit a PR to improve it if I get some guidance on what would need to be changed
- if the warning is necessary, could it be displayed less often? because it is outputted dozens of times on some applications where I tested the RC

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/node-1bky4j?file=repro/src/app

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.0-rc.0
Node: 16.17.0
Package Manager: yarn 1.22.17
OS: darwin arm64

Angular: 15.2.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.0-rc.0
@angular-devkit/build-angular   15.2.0-rc.0
@angular-devkit/core            15.2.0-rc.0
@angular-devkit/schematics      15.2.0-rc.0
@angular/cdk                    15.1.4
@schematics/angular             15.2.0-rc.0
rxjs                            7.8.0
typescript                      4.8.4
```

**Comment by atscott** [comment]
The change which would cause the warning to appear in v15 would have been [this one](https://github.com/angular/angular/pull/48688). The Router code is being updated to generate a URL from an `ActivatedRoute`. A mocked `ActivatedRoute` in a test that doesn't define the entire interface causes this code to throw an error. 

> is the warning really necessary in that case?

I guess that's really up for interpretation. In short, no. The code is able to recover in a way that matches the old behavior. But should it have to? At the moment, it's not really feasible to remove this so the warning should probably be removed unless there's a plan to actually break any tests relying on this behavior.
