### ISSUE TITLE
event 'search' fired twice for input[type=search]

### ISSUE THREAD

**Issue by piotrroda** [angular/angular#49114]
### Which @angular/* package(s) are the source of the bug?

core, forms

### Is this a regression?

No

### Description

Hello,

Component has @Output() called 'search' and <input type="search" (keydown.enter)="test()" /> in template.
Next I typed some text into input and press 'enter' button. After that event 'search' from component was fired twice.
Same situation when after typing test I pressed clear button in input then event 'search' from component fired once.

The problem is the mutual influence of the component and input event.
I only noticed the problem in Chrome.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-2uvx3f

**Comment by piotrroda** [comment]
It doesn't make sense. As I understand Angular events via @Output and native events firing by browser aren't same.
I such situation when I'm looking for name for "my" events I have to know about all events from native html.

**Comment by JeanMeche** [comment]
You'd have the same problem had your emitter been called `click`. Would that had surprised you ? Likely not. 

Angular uses the same syntax to listen to native events and custom events.

**Comment by piotrroda** [comment]
Ok. I understand your explaination. But it is implicit behavior. Maybe in docs should be some remark about that.
I.e here: https://angular.io/guide/inputs-outputs
