### ISSUE TITLE
TypeError: this.route.paramMap.pipe is not a function

### ISSUE THREAD

**Issue by esubbu** [angular/angular#49123]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

I am using activated route in my code as below,
**this.route.paramMap.pipe(
      switchMap((params: ParamMap) =>**

while writing isolated test case i am getting below error
**TypeError: this.route.paramMap.pipe is not a function**

How can i resolve the above issue?

### Please provide the exception or error you saw

```true
TypeError: this.route.paramMap.pipe is not a function
```

**Comment by esubbu** [comment]
I am mocking route object as below,

**Comment by esubbu** [comment]
**const routeSpy = jasmine.createSpyObj<ActivatedRoute>(['paramMap']);**

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by esubbu** [comment]
Thank you
