### ISSUE TITLE
Form controll should listen to the reset event

### ISSUE THREAD

**Issue by todoubaba** [angular/angular#4914]
When click the reset button, the form's value is still unchanged. See http://plnkr.co/edit/oBpDZRRUH7mmZct2hmDH?p=preview.

**Comment by MarkPerryBV** [comment]
Will there also be a way to "reset" the state of the form manually? Typical use case would be a form that stays on the page as you are adding items to a list above.

**Comment by ericmartinezr** [comment]
@MarkPerryBV https://github.com/angular/angular/pull/9974
