### ISSUE TITLE
Now create Karma File

### ISSUE THREAD

**Issue by psubha936** [angular/angular#49159]
### Describe the problem that you experienced

When I generate the karma file (ng g config karma) it's showing an unknown argument: karma, when I saw ng g --help their no config file mentioned. 
![image](https://user-images.githubusercontent.com/89669175/220629523-e8198af3-7e33-4a7a-8dab-3b42a1941861.png)
![image](https://user-images.githubusercontent.com/89669175/220628852-e17da05e-b243-4b47-a184-e0678e6fb99c.png)

### Enter the URL of the topic with the problem

Generating config file

### Describe what you were looking for in the documentation

create a karma file

### Describe the actions that led you to experience the problem

create a karma file

### Add a screenshot if that helps illustrate the problem

![image](https://user-images.githubusercontent.com/89669175/220628852-e17da05e-b243-4b47-a184-e0678e6fb99c.png)

**Comment by JeanMeche** [comment]
You need to run `ng generate config karma`

**Comment by alan-agius4** [comment]
`ng generate config` was introduced in Angular 15.1. Please update.

**Comment by psubha936** [comment]
> You need to run `ng generate config karma`

it's not working... showing the same error.

**Comment by psubha936** [comment]
![image](https://user-images.githubusercontent.com/89669175/220690453-936355e6-be08-4d76-8891-d2d2aa116f67.png)

look at the snapshot there its ng g --help snap here also not mention config.js command.

**Comment by alan-agius4** [comment]
Based on the ng version output shown in the screenshot above, you are using Angular CLI 15.0.5.
