### ISSUE TITLE
Angular tour of heroes 

### ISSUE THREAD

**Issue by MatthieuDelisle** [angular/angular#49162]
### Describe the problem that you experienced

in the tutorial tour of heroes of angular, in section 3, there's a repetition of a line that's not in the right place and very confusing : 
<app-hero-detail [hero]="selectedHero"></app-hero-detail>

we just need to remove that line 

### Enter the URL of the topic with the problem

https://angular.io/tutorial/tour-of-heroes/toh-pt3

**Comment by atscott** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
