### ISSUE TITLE
Tutorial: Tour of Heroes - Part 4: add services. Mistake in a section title

### ISSUE THREAD

**Issue by JanDolenc** [angular/angular#49165]
### Describe the problem that you experienced

I am following the Tour of Heroes tutorial. On part 4 - add services I believe that there is a mistake in the last section title before Final code review. The title says "Add messages to hero service", but the code below is about how to display messages from the hero component. So the title should be "Add messages to hero **component**". The mistake occurs again in the text underneath the code snippet. 

### Enter the URL of the topic with the problem

https://angular.io/tutorial/tour-of-heroes/toh-pt4#add-messages-to-hero-service

### Add a screenshot if that helps illustrate the problem

![image](https://user-images.githubusercontent.com/23385863/220732298-56162194-eb02-4a47-8235-e40eac8e0623.png)

**Comment by JeanMeche** [comment]
I believe the title is right since it is about calling `this.messageService.add` in the component !

**Comment by JanDolenc** [comment]
Can you elaborate a little bit more? I understand that in the code snippet we add a **message service** to the **hero component** and display the messages from it every time the new hero is selected. But I fail to understand how is the **hero service** connected with this.

On the screenshot underneath, I marked the lines that changed since the last code changes in the _heroes.component.ts_ when we subscribe to observable (section Observable data > Subscribe in HeroesComponent). In the snippet below, we didn't change anything about **hero service**, so I still think, that the title is wrong. It should either say "Add messages to **hero component**" or "Add messages with **message service**".

![image](https://user-images.githubusercontent.com/23385863/220857304-bba773e6-723a-4ec1-b422-6bafbb3e4f16.png)

**Comment by Jriera** [comment]
I believe it would be clearer as: Add Messages service to heroes component. 
As it is titled now it could lead into thinking that there is a service called hero

**Comment by AndrewKushnir** [comment]
@Jriera the "Add Messages service to heroes component" title looks like a very good option 👍

**Comment by SarthakT7** [comment]
Can you assign this to me?

**Comment by JanDolenc** [comment]
@Jriera Great suggestion 👏  It makes it very clear what you are about to do and minimal chances for misinterpretation, confusion.

**Comment by JeanMeche** [comment]
Let's go for it then in #49208 !

**Comment by Jriera** [comment]
Thanks @JeanMeche for making the PR  👍
