### ISSUE TITLE
Finally remove (deprecated) `/deep/`, `>>>`, and `::ng-deep`

### ISSUE THREAD

**Issue by Jordan-Hall** [angular/angular#49170]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

/deep, >>> and ng-deep has been deprecated since version 8 or 9. While there can be some genuine use cases such as font-face. The echo system should have moved in by now and provide other forms of styling. Such as scss `@use`. 

If you're using a package that requires the use of ng-deep, then you should submit a ticket/PR to resolve the issue.

### Proposed solution

Complete removal from the compiler. People have had years to remove the functionality, it's dirty and cresting legacy code mess for people to clean up.

**Comment by JeanMeche** [comment]
Hi, there is already an issue about this : #17867

**Comment by AndrewKushnir** [comment]
Closing in favor of https://github.com/angular/angular/issues/25160.
