### ISSUE TITLE
Parent Zone missing with custom Zone fork inside an rxjs Observable operator

### ISSUE THREAD

**Issue by sdedieu** [angular/angular#49178]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

For performance monitoring we built a library combining [zone.js](https://www.npmjs.com/package/zone.js) and the [Javascript native Error stack](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack) which wrapp some functions to keep tracking of the call stack and monitoring their run time.   

We currently struggle using it inside Angular applications because it seems that the angular core do something that make us lose track of our call stack if we use our wrapper around functions that contains rxjs Observables.

## Step for bug reproduction
- Clone this [repository](https://github.com/sdedieu/angular-zone-custom-fork-parent-lost-in-rxjs-operators)
- Run the `npm ci` command to install dependencies
- Run the `ng serve` command to start the project on `http:localhost:4200`
- Open `http:localhost:4200` on a web browser.

### Issue (current behaviour)
Two wrapped functions are called inside the `ngOnInit` method.
- The first one using `rxjs Observable` display in the console: `obs_bar angular`.
- The second one using `Promise` display in the console: `promise_bar promise_foo`.

### Expected behaviour
As the one using `Promise`, the wrapped method using `rxjs Observable` should display in the console: `obs_bar obs_foo`

### Please provide a link to a minimal reproduction of the bug

https://github.com/sdedieu/angular-zone-custom-fork-parent-lost-in-rxjs-operators

### Please provide the exception or error you saw

```true
The wrapped method using `rxjs Observable` display `obs_bar angular` in the console instead of `obs_bar obs_foo`
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.0
Node: 16.15.0
Package Manager: npm 8.5.5
OS: darwin x64

Angular: 15.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.0
@angular-devkit/build-angular   15.2.0
@angular-devkit/core            15.2.0
@angular-devkit/schematics      15.2.0
@schematics/angular             15.2.0
rxjs                            7.8.0
typescript                      4.9.5
```

### Anything else?

Funny thoughts, it works on [this Stackblitz](https://stackblitz.com/edit/angular-mht2rc?file=src%2Fmain.ts)

**Comment by sankeerth125** [comment]
Hi @sdedieu, is anyone working on this?

**Comment by sdedieu** [comment]
Hi @sankeerth125 ! I don't think so, I created the issue 30min ago.
But I have to change the description a little bit, as I don't encounter the issue on Stackblitz, but I do on a "real" angular-cli generated application.
So I'll provide a github repository instead of the Stackblitz link shortly.

**Comment by JeanMeche** [comment]
Isn't the difference that `then` is patched ? 

```
  observableExample() {
    return of(1).pipe(
      tap((_) => {
        console.log(Zone.current.name); // angular
        this.wrapper('obs_bar', this.logger);
      })
    );
  }

  promiseExample() {
    return firstValueFrom(timer(0, 1000)).then((_) => {
      console.log(Zone.current.name) // promise_foo;
      this.wrapper('promise_bar', this.logger);
    });
  }

```

**Comment by sdedieu** [comment]
> Isn't the difference that `then()` is patched ?
> 
> ```
>   observableExample() {
>     return of(1).pipe(
>       tap((_) => {
>         console.log(Zone.current.name); // angular
>         this.wrapper('obs_bar', this.logger);
>       })
>     );
>   }
> 
>   promiseExample() {
>     return firstValueFrom(timer(0, 1000)).then((_) => {
>       console.log(Zone.current.name) // promise_foo;
>       this.wrapper('promise_bar', this.logger);
>     });
>   }
> ```

Yes, you are right. In the Stackblitz example it started to work when I add the `import zone.js/dist/zone-patch-rxjs.js` in the `main.ts` file.

But it does not when I do the same in the `application.component.ts` file of an angular-cli generated project ([repo](https://github.com/sdedieu/angular-zone-custom-fork-parent-lost-in-rxjs-operators)).

**Comment by JeanMeche** [comment]
I don't really know why but it works when importing from `zone.js/plugins/zone-patch-rxjs`

**Comment by glsm4tt** [comment]
> I don't really know why but it works when importing from `zone.js/plugins/zone-patch-rxjs`
> 
> Maybe @JiaLiPassion has an idea why !

It does on the [Stackblitz](https://stackblitz.com/edit/angular-mht2rc?file=src%2Fmain.ts) example yes, but I believe it still does not on my [repo](https://github.com/sdedieu/angular-zone-custom-fork-parent-lost-in-rxjs-operators). 🫤

**Comment by glsm4tt** [comment]
> I don't really know why but it works when importing from `zone.js/plugins/zone-patch-rxjs`
> 
> Maybe @JiaLiPassion has an idea why !

I believe that the `zone.js/plugins/zone-patch-rxjs` script is made to make the current zone persistent through `rxjs` operators. So it make sense that adding it to the page solve the issue. 🙂
But I don't get why it's not working in the [`app.component.ts`](https://github.com/sdedieu/angular-zone-custom-fork-parent-lost-in-rxjs-operators/blob/main/src/app/app.component.ts).🫤

**Comment by JeanMeche** [comment]
> > I don't really know why but it works when importing from `zone.js/plugins/zone-patch-rxjs`
> > Maybe @JiaLiPassion has an idea why !
> 
> It does on the [Stackblitz](https://stackblitz.com/edit/angular-mht2rc?file=src%2Fmain.ts) example yes, but I believe it still does not on my [repo](https://github.com/sdedieu/angular-zone-custom-fork-parent-lost-in-rxjs-operators). 🫤

I got that result locally with the same angular.json config!

**Comment by sdedieu** [comment]
> > > I don't really know why but it works when importing from `zone.js/plugins/zone-patch-rxjs`
> > > Maybe @JiaLiPassion has an idea why !
> > 
> > 
> > It does on the [Stackblitz](https://stackblitz.com/edit/angular-mht2rc?file=src%2Fmain.ts) example yes, but I believe it still does not on my [repo](https://github.com/sdedieu/angular-zone-custom-fork-parent-lost-in-rxjs-operators). 🫤
> 
> I got that result locally with the same angular.json config!

I'm sorry, just to clarify, locally you reproduce the issue and you have `obs_bar angular` in the console, or you have `obs_bar  obs_foo` ?

**Comment by JeanMeche** [comment]
I see:

* `obs_bar obs_foo` with `zone.js/plugins/zone-patch-rxjs`
* `obs_bar angular` with `zone.js/dist/zone-patch-rxjs.js`

**Comment by sdedieu** [comment]
Oh ! Awesome I didn't notice the `plugins` path part in your previous answers ! 
It works on my repo too 🙂.
Thanks ! 🎉

**Comment by sdedieu** [comment]
To me the issue is closed as I have to import `zone.js/plugins/zone-patch-rxjs` instead of `zone.js/dist/zone-patch-rxjs.js` to solve my problem.
Thanks @JeanMeche for the help !
