### ISSUE TITLE
Schematic utils are not available anymore in @angular/core since version 15.1.0

### ISSUE THREAD

**Issue by oliverschuerch** [angular/angular#49177]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

The angular/core schematics utils were available in the npm package @angular/core up to version 15.0.4, for example like so:
`import { getProjectTsConfigPaths } from '@angular/core/schematics/utils/project_tsconfig_paths';`
I depend on them to be able to write custom migrations for a design-system.

Unfortunately, these are no longer available since version 15.1.0.
I could not find any information about this change in the [changelog](https://github.com/angular/angular/blob/main/CHANGELOG.md).
And as it's kind of a breaking change I'm asking myself if this happend intentional?

Utils still there:
https://www.npmjs.com/package/@angular/core/v/15.0.4?activeTab=explore -> /schematics/utils 
Utils gone:
https://www.npmjs.com/package/@angular/core/v/15.1.0?activeTab=explore -> /schematics/???

Would it be possible to reintegrate them in the released package or is there another way to use them from somewhere else?

Thanks for your help!

I even tryed to get an anwer about that on stack-overflow before, but without any success till now: https://stackoverflow.com/questions/75522436/schematic-utils-are-not-available-anymore-in-angular-core-since-version-15-1-0.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.6
Node: 16.19.1
Package Manager: pnpm 7.27.1
OS: win32 x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1501.6
@angular-devkit/core         15.1.0
@angular-devkit/schematics   15.1.0
@schematics/angular          15.1.6
```

**Comment by JeanMeche** [comment]
The team is tracking making schematic utilities as public in angular/angular-cli#24204

**Comment by JoostK** [comment]
Using deep imports in any of Angular's packages is not supported; they rely on the internal code structure and packaging aspects that may change at any time, as did happen in #48521 for this particular case (the migrations are now being bundled, instead of shipping the individual source files).

Exposing schematics utilities as public API is indeed being tracked in https://github.com/angular/angular-cli/issues/24204. For now you will have to adopt these utilities into your own codebase.
