### ISSUE TITLE
Forms: Unable to set FormGroup to null

### ISSUE THREAD

**Issue by zetti-caletti** [angular/angular#49187]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

I have a form to edit a post. The post can have a poll which can be a poll or null.

```
interface CreatePost {
    text: string;
    poll: CreatePostPoll | null;
}

interface CreatePostPoll {
    choices: string[];
    duration: number;
}
```

If the user wants to add a poll then the form is edited with patchValue and the choices and duration are initialized. If the user removes the poll, it should become null. However I am unable to assign null value to a formgroup. After setting the formgroup to null I get the error "Cannot read properties of null (reading 'choices')" I can disable the poll control, however then the whole poll property of the form value gets removed. I thought in Angular Forms the controls and the values are decoupled from each other, so that I can assign a null value to a formgroup, even if the controls of that formgroup still exists. For the poll formgroup I don't have "nonNullable: true", so I thought I can assign a null value?!

```
this.postForm = new FormGroup<PostForm>(
    {
        text: new FormControl(this.post.text || '', {
            validators: [Validators.maxLength(1024)],
            nonNullable: true,
        }),
        poll: new FormGroup({
            choices: new FormControl(['', ''], {
                nonNullable: true,
            }),
            duration: new FormControl(1 * 24 * 60, {
                nonNullable: true,
            }),
        }),
    },
);

get poll() {
    return this.postForm.get('poll') as PostForm['poll'];
}

togglePoll() {
    this.pollOpen = !this.pollOpen;

    if (this.pollOpen) {
        this.poll.patchValue({
            choices: ['', ''],
            duration: 1 * 24 * 60,
        });
    }
    else {
        this.poll.patchValue(null!);
    }
}
```

### Please provide a link to a minimal reproduction of the bug

[https://stackblitz.com/edit/angular-mjzpj1](https://stackblitz.com/edit/angular-mjzpj1)

**Comment by JeanMeche** [comment]
Hi ! 

Is the error thrown by the template ?  Could you share a stackblite repro ?

**Comment by zetti-caletti** [comment]
Hey @JeanMeche 
I have added an example. Now I don't get an error anymore but I am anyway unable to set the value of the formgroup to null. The reason why I want to have the poll to have null value is, that I make a PATCH-Request for partial updates to the server. If I disable the control, then the whole form property "poll" is removed and so doesn't get included in the PATCH-Request. I then would have to manually include "poll: null" if poll is disabled before sending the PATCH-Request. Maybe there any other simple solution to this?

**Comment by zetti-caletti** [comment]
I think the error was thrown because I tried to access to the FormControls in PollEditComponent which I didn't implemented in this demo.

**Comment by AndrewKushnir** [comment]
@zetti-caletti as @JeanMeche mentioned, it'd be helpful to have a repro created using https://stackblitz.com/, so that we can reproduce the issue and perform the necessary investigation.

**Comment by zetti-caletti** [comment]
@AndrewKushnir Sorry I have added the link but it appears that it wasn't saved. Have now added it.

**Comment by zetti-caletti** [comment]
@JeanMeche @AndrewKushnir I saw now in the source code of Angular that it doesn't appear to be a bug. You can only set values to a FormGroup that have the predefined fields when created the FormGroup. So the question is, is it possible to assign otherwise a null value to a FormGroup or not? Should I use the disable method for this and add poll: null manually before saving like I wrote above?

**Comment by JeanMeche** [comment]
Yes, the `FormGroup` doesn't support null values. You can use disable for this use case and transform the group value to match your wanted data structure. Another possibility is to have a FormArray which have 0 or 1 element.

**Comment by zetti-caletti** [comment]
Transform the gorup value to match my wanted data structure, but outside of forms right?

**Comment by JeanMeche** [comment]
Yes, after retrieve the value with `postForm.getValue()` !

**Comment by zetti-caletti** [comment]
Ok. Thanks a lot :)
