### ISSUE TITLE
Unable to import directive ɵNgNoValidate.

### ISSUE THREAD

**Issue by chladog** [angular/angular#49197]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

After updating to @angular/forms@15.2.0 I'm unable to build an app due to following error.
This error appears in standalone component that imports ReactiveFormsModule, if I remove the ReactiveFormsModule from the component then it builds.
With @angular/forms@15.1.3 everything works as expected.

### Please provide the exception or error you saw

```true
Unable to import directive ɵNgNoValidate.
The symbol is not exported from /node_modules/@angular/forms/index.d.ts (module '@angular/forms').
```

**Comment by JoostK** [comment]
Could you please provide a reproduction?

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
