### ISSUE TITLE
[FeatureRequest] Run TypeCheck with ngtsc just like you run tsc --noEmit

### ISSUE THREAD

**Issue by JonWallsten** [angular/angular#49194]
### Command

build, lint

### Description

We would like to create a pre-commit script that check for compiling errors in the changed files in our project.
We do this with `tsc --noEmit file.ts` today and it works well for `ts` errors. But it won't find `ngtsc` errors like this:
![image](https://user-images.githubusercontent.com/5993909/221140302-f87edb63-1b2f-4bad-a6bc-7de918db8ccf.png)

Is it possible to do this today? I have tried the linter, but since it's not a syntax error it won't fail the linter.

### Describe the solution you'd like

It would be nice to be able to type-check specific files without doing a full build.

### Describe alternatives you've considered

We have already tried all solutions we could think of.

**Comment by alan-agius4** [comment]
You can run `ngc --noEmit`.  Although unlike TSC this cannot be done on individual files as the NGC compiler requires a TS program and knowledge of the entire application to emit certain type-checking errors.

**Comment by JonWallsten** [comment]
@alan-agius4 Thank for your quick reply. I had a feeling that was the case. So the `ngc` will compile the full application every time it runs then? Is there any way of speeding it up so it only runs changes since last build or something like that? How would you solve it?

**Comment by alan-agius4** [comment]
@JonWallsten, NGC type-checking relies on the entire application context therefore type-checking for the entire application needs to be performed.

Therefore, it is not possible to type-check a single file. Probably to speed up things a little, you can create your own CLI, that uses the compiler-cli API and request diagnostics only for the changed files. But note, that the compiler-cli APIs are considered private and totally unsupported. I definitely recommend against go down this route. 

In general, such errors are typically surfaced in the CI run when a PR has been opened, as commit hooks can also be easily bypassed.
