### ISSUE TITLE
Very slow in performance, Please make this a compiler like svelte

### ISSUE THREAD

**Issue by riturajshakti** [angular/angular#49195]
### Description

Very slow in performance, Please make this a compiler like svelte

### Proposed solution

Please make this a compiler like svelte. It will become better than react.

### Alternatives considered

No alternatives

**Comment by alan-agius4** [comment]
Closing as this issue does not provide actionable items. 

We care about performance a lot and we will also strive to continue improving the performance of the compiler. 

If you are experiencing a abnormal slow compilation, please open another issue and provide all the necessary information, such as a minimal reproduction or at the very least CPU profiles.
