### ISSUE TITLE
Angular Form in feature module - giving unknown property of 'form'.

### ISSUE THREAD

**Issue by ga2tes** [angular/angular#49196]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

When integrating Angular Form on a feature module, gives error:
`Can't bind to 'formGroup' since it isn't a known property of 'form'.`

even after adding ReactiveFormsModule &  FormsModule

```
  imports: [
    CommonModule,
    HomeRoutingModule,
    ReactiveFormsModule,
    FormsModule
  ]


```

### Please provide a link to a minimal reproduction of the bug

https://github.com/ga2tes/AngularFormTest

### Please provide the exception or error you saw

```true
Error: src/app/home/home/home.component.html:3:9 - error NG8002: Can't bind to 'formGroup' since it isn't a known property of 'form'.

3   <form [formGroup]="MyForm" (submit)="send()">
          ~~~~~~~~~~~~~~~~~~~~
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
NODE: v16.19.0
NPM: 8.19.3
```

### Anything else?

none

**Comment by JeanMeche** [comment]
You forgot to import `HomeModule` in the  `AppModule`.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by ga2tes** [comment]
> Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.
> 
> If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

I did ask on stackoverflow.
https://stackoverflow.com/questions/75556823/angular-15-cant-bind-to-formgroup-since-it-isnt-a-known-property-of-form
but no one seems to care XD

**Comment by ga2tes** [comment]
@JeanMeche if I could not get help in stackoverflow & github, is there any other community where I can ask for help?

**Comment by ga2tes** [comment]
> You forgot to import `HomeModule` in the `AppModule`.

I'm trying to lazyload HomeModule, do I really need to import it in app.module?

**Comment by JeanMeche** [comment]
I gave you an answer on SO.
