### ISSUE TITLE
Dart style: opt for a library with top-level members over classes with only static members

### ISSUE THREAD

**Issue by kevmoo** [angular/angular#492]
e.g.

```dart
class SetWrapper {
  static Set createFromList(List l) {
    return new Set.from(l);
  }
  static bool has(Set s, key) {
    return s.contains(key);
  }
}
```

should be

```dart

library set_wrapper;

Set createFromList(List l) {
  return new Set.from(l);
}

bool has(Set s, key) {
  return s.contains(key);
}
```

In the use site, simply import the library
```dart
import 'set_wrapper.dart' as setWrapper;
```

**Comment by mhevery** [comment]
Can you show me an example? This may be due to way facades work between JS and Dart.

**Comment by kevmoo** [comment]
The DOM facade is a good example
https://github.com/angular/angular/tree/master/modules/facade/src

Could we just get rid of the static class and have top-level members in Dart and in es6, export the functions directly

```javascript
export nextSibling(el):Node {
  return el.nextSibling;
}
```
instead of exporting a class which has the exports?

**Comment by mhevery** [comment]
This is private api so it has no impact on external devs. There are plans to love this to ts2dart so it will be no issues. Closing for now.
