### ISSUE TITLE
Unable to provide services in an abstract Directive

### ISSUE THREAD

**Issue by alastair-todd** [angular/angular#49212]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I don't understand why this does nothing

```typescript
@Directive({
  providers: [CalendarComponentStateService]
})
export abstract class AbstractEventsComponent {

  calendarMonthEventsStateService = inject(CalendarComponentStateService);
```

Other than throw 

> NullInjectorError:
> R3InjectorError(EmployeeHubModule)[CalendarComponentStateService ->
> CalendarComponentStateService -> CalendarComponentStateService ->
> CalendarComponentStateService]:    NullInjectorError: No provider for
> CalendarComponentStateService!

I am required to provide in the concrete component class, which i don't really like.

```typescript
@Component({
  selector: 'app-events-calendar',
  templateUrl: './events-calendar.component.html',
  styleUrls: ['./events-calendar.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [CalendarComponentStateService]
})
export class EventsCalendarComponent extends AbstractEventsComponent {}
```

Angular CLI: 14.2.3
Node: 16.18.0
Package Manager: npm 8.19.2
OS: win32 x64

_No response_

**Comment by JeanMeche** [comment]
For the providers to work, the directive has to be declared in the module. 
The problem is that you can't declare abstract classes in a module. 

You code above will work if your class `AbstractEventsComponent ` isn't abstract and declared in the same module as `EventsCalendarComponent`.

**Comment by JoostK** [comment]
This is because providers are not inherited, which is intentional judging by #27013.
