### ISSUE TITLE
Stackblitz demo is broken: "The dependencies for this project couldn't be resolved."

### ISSUE THREAD

**Issue by simon-mathewson** [angular/angular#49213]
### Describe the problem that you experienced

Stackblitz demo doesn't work.

### Enter the URL of the topic with the problem

https://angular.io/quick-start

### Describe the actions that led you to experience the problem

Go to https://angular.io and click "Try angular".

### Add a screenshot if that helps illustrate the problem

<img width="1395" alt="Screenshot 2023-02-26 at 13 32 31" src="https://user-images.githubusercontent.com/17678744/221410665-e2db2d9e-1cb4-4716-8c39-e95406bd064a.png">

### If this problem caused an exception or error, please paste it here

```
The dependencies for this project couldn't be resolved.
This usually means that a dependency in your package.json is incorrect.
```

**Comment by JeanMeche** [comment]
Thanks for repporting this issue, there was indeed a dependency problem. #49217 should fix this issue.

**Comment by simon-mathewson** [comment]
Thank you!
