### ISSUE TITLE
when working locally in debug getting error of: Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope'

### ISSUE THREAD

**Issue by born2net** [angular/angular#49224]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

Yes

### Description

when working locally in debug getting error of: Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope'
in AOT release it's fine.
anyway to fix this so it won't happen when debugging locally?

![image](https://user-images.githubusercontent.com/5090936/221490508-9d70cf8a-7e69-430a-98eb-1fa4af984dba.png)

we are not using firebase as often the cause when searching google for this issue.

Thanks

Sean

### Please provide a link to a minimal reproduction of the bug

error on import

### Please provide the exception or error you saw

```true
![image](https://user-images.githubusercontent.com/5090936/221490508-9d70cf8a-7e69-430a-98eb-1fa4af984dba.png)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.4
Node: 16.16.0
Package Manager: npm 8.11.0
OS: win32 x64

Angular: 15.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, pwa, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1500.4
@angular-devkit/build-angular      15.0.4
@angular-devkit/core               15.0.4
@angular-devkit/schematics         15.0.4
@angular/cdk                       15.0.3
@angular/google-maps               14.2.7
@angular/material                  15.0.3
@angular/material-moment-adapter   15.0.3
@schematics/angular                13.3.10
rxjs                               7.8.0
typescript                         4.8.4
```

### Anything else?

that's it...

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
