### ISSUE TITLE
Bundle domino in @angular/platform-server package

### ISSUE THREAD

**Issue by josephperrott** [angular/angular#49228]
Since we are not planning to publish our fork of domino to npm, we need to bundle it into the `@angular/platform-server` package rather than having our users depend on it via the repo directly.

In general, I believe that we should not be asking our users to install dependencies (a transitive one in this case) from a github repository rather than an npm registry package. Using a Github repo is a great option for internal packages, testing prior to publishing, etc., but I think we should be encouraging our users, and the ecosystem at large to be using a proper registry.  This is particularly true as we look forward to how [SLSA](https://slsa.dev/) specifications will be coming to the node ecosystem.

**Comment by jessicajaniuk** [comment]
This has been resolved since #49229 has landed.
