### ISSUE TITLE
Async validation in a ControlValueAccessor causes an ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by krausest** [angular/angular#49237]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

I ran into the issue that an ExpressionChangedAfterItHasBeenCheckedError was reported when a component was mounted.
The template that caused the error was the valid property of a FormGroup `{{fg.valid}}` and I don't understand why.
The FormGroup has a Component that implements ControlValueAccessor, Validator and uses async validation as its FormControl.

The two relevant components are AppComponent and CvainputComponent.
CvainputComponent implements ControlValueAccessor, Validator and has a FormControl with an async validator:
```
  fg = new FormGroup({
    name: new FormControl<string>("", { validators:[Validators.required, Validators.min(5), Validators.max(50)], asyncValidators:[asyncEvenLength], nonNullable: true })
  })
```

The AppComponent has a FormGroup that uses the CvainputComponent:
```
  fg = new FormGroup({
    cvainp: new FormControl<ICvainputComponentValue>({name:'example'})
  })
```

The template of the AppComponent displays the validity of the FormGroup:
```
<p>{{fg.valid}}</p>
```
The template prints the validity twice. In this example only the first causes the ExpressionChangedAfterItHasBeenCheckedError. (But if I remember correctly in the original problem moving the expression didn't help).

I'd say the ExpressionChangedAfterItHasBeenCheckedError should not be thrown.

### Please provide a link to a minimal reproduction of the bug

https://github.com/krausest/angular-cva-async-issue

### Please provide the exception or error you saw

```true
ERROR Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'. Find more at https://angular.io/errors/NG0100
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.0
Node: 16.18.0
Package Manager: npm 8.19.2
OS: darwin arm64

Angular: 15.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.0
@angular-devkit/build-angular   15.2.0
@angular-devkit/core            15.2.0
@angular-devkit/schematics      15.2.0
@schematics/angular             15.2.0
rxjs                            7.5.7
typescript                      4.9.5
```

### Anything else?

Due to #41519 the initial validity of the AppComponent gets stuck in the PENDING state. This can be fixed by adding 
```
    setTimeout(() => {
      this.fg.controls['name'].updateValueAndValidity();
    })
```
in `CvainputComponent.ngOnInit`
I removed it from the example to make clear that the issue isn't caused by that update.

**Comment by JeanMeche** [comment]
The error happens because : 

* You display `fg.valid`, which `true` by default because there is no validator on the FG.
* The CVA component gets setup
* The `formControlName` triggers `validate()` on the CVA. 
* The async validation set the `valid` to `false`

The second CD run (with only happens on dev mode), sees the difference on the second run for the first `{{ fg.valid }}` that is now `false` thus triggering the error. 

I'd say this is pretty expected.

**Comment by krausest** [comment]
Thanks for the explanation. I checked and it indeed occurs for synchronous validation also.
Is there a best practice to avoid that error in such a case (calling fg.valid in both places and having a ControlValueAccessor with validation seem rather innocent)?

**Comment by JeanMeche** [comment]
As described above, the issue is "exepected".
