### ISSUE TITLE
Use camelCase instead of dash-case in HTML

### ISSUE THREAD

**Issue by mhevery** [angular/angular#4923]
With the new parser #4417 we should switch to no longer convert `dash-case` to `camelCase` and instead honor the properties as is.

**Comment by Dzeks** [comment]
+1

**Comment by dpsthree** [comment]
Just to clarify, if you write <my-app> or [my-prop] on a template, what identifiers would be expected as the component selector and the input property?

**Comment by Dzeks** [comment]
According to this commit
https://github.com/angular/angular/commit/a8edc1eb58b2f70b3cb2e427e5b0ee4484fd4ea4#diff-c5fff3b58806e478f538ddb77868c5caR919
inputs will be defined as 
```javascript
inputs: ['aProp']
```
but html will look like this
```html
<div [a-prop]="foo | bar"></div>
```
so now it's a bit confusing

**Comment by vicb** [comment]
adressed in #5765
