### ISSUE TITLE
Router that is on a component which is on the second level of nested router-outlets doesn't get all events

### ISSUE THREAD

**Issue by JanHeinemeyer88** [angular/angular#49249]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

You have a root component, a first component and a second component and the root has a router-outlet and the firs-component as well has a router-outlet and you have the following routing:
[{
  path: 'first',
  component: FirstComponent,
  children: [{
    path: 'second',
    component: SecondComponent,
  }],
}]
If you now subscribe in each component to the router events, the router in the second component only gets an Scroll event but not for example the NavigationEnds event.

You can see this on the example i provided.

1. start the app with npm start
2.  Go to this [route](https://nodewtrgsh-gnhr--4200.local-credentialless.webcontainer.io/first/second)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/node-wtrgsh

### Please provide the exception or error you saw

```true
No exception or error, just missing events.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.4
Node: 16.19.1
Package Manager: npm 8.19.3
OS: darwin arm64

Angular: 15.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.4
@angular-devkit/build-angular   15.0.4
@angular-devkit/core            15.0.4
@angular-devkit/schematics      15.0.4
@schematics/angular             15.0.4
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by dolaru-plenty** [comment]
Same issue using standalone implementation: https://stackblitz.com/edit/angular-6mramq?file=src%2Fmain.ts](https://stackblitz.com/edit/angular-r8tkrv?file=src/main.ts .  nothing is emitted from subscribing to the router events in the page1b component

**Comment by atscott** [comment]
This is working as expected. Components are not necessarily constructed during the navigation but rather after the navigation completes and change detection runs.

**Comment by JanHeinemeyer88** [comment]
Thanks for the fast answer.
Okay i understand, but the router of the first component gets way more events then the one of the second component. So the first component gets constructed earlier in the navigation process then the second.
Is this behavior not a bit inconsistent?

**Comment by atscott** [comment]
@JanHeinemeyer88 This happens because the `router-outlet` for the first component is already created before the navigation starts while the outlet in the second level doesn't exist yet. This means the second level outlet needs to initialize during change detection while the first one is already initialized. Because application's aren't static content, it's impossible to make everything absolutely "consistent".
