### ISSUE TITLE
Docs discourage using of NO_ERRORS_SCHEMA

### ISSUE THREAD

**Issue by amakhrov** [angular/angular#49269]
### Describe the problem that you experienced

There are two places in the docs that cover NO_ERRORS_SCHEMA.

1.
The [API page for NO_ERRORS_SCHEMA](https://angular.io/api/core/NO_ERRORS_SCHEMA) says
  > The usage of this schema is generally discouraged because it prevents useful validation and may hide real errors in your template

It sounds like a developer should avoid using it, not mentioning the applicability context (this is true for app code, but less so for unit tests).

2.
The ["Component testing scenarios" page](https://angular.io/guide/testing-components-scenarios). This one has more permissive language and warns about **over-**using it. Yet, it doesn't explain when it's appropriate to use it, so overall it discourages developers from using it in unit tests, again.

Additionally, the justification it provides is "it disables compile-time checks". However, since the full app is still AOT-compiled, and NO_ERRORS_SCHEMA is only used in the component testing scenario, it doesn't sound like a problem to me.

### Enter the URL of the topic with the problem

https://angular.io/guide/testing-components-scenarios

### Describe what you want to experience that would fix the problem

As a developer, I would like to better understand when I should use NO_ERRORS_SCHEMA and when I should not.

**Comment by atscott** [comment]
Closing in favor of the boarder issue https://github.com/angular/angular/issues/48510. Generally we _do_ discourage `NO_ERRORS_SCHEMA` and from the API page is accurate. The linked doc is woefully outdated and certainly doesn't always demonstrate good testing practices.
