### ISSUE TITLE
Extended diagnostics run when angularCompilerOptions.extendedDiagnostics = false

### ISSUE THREAD

**Issue by e-oz** [angular/angular#49286]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

In 16.0.0-next.1, when angularCompilerOptions.extendedDiagnostics = false in tsconfig, I still receive warnings about "NG8107".

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Node v19.7.0
@angular/compiler 16.0.0-next.1
@angular-devkit/build-angular 16.0.0-next.2
```

**Comment by JeanMeche** [comment]
Shouldn't you disable it this config ? 

```
"angularCompilerOptions": {
    "extendedDiagnostics": {
      "checks": {
        "optionalChainNotNullable": "suppress"
      }
    }
  }
```

**Comment by e-oz** [comment]
Thank you @JeanMeche - by your link I found way to turn them off:
```
"extendedDiagnostics": {
      "defaultCategory": "suppress"
 }
```
