### ISSUE TITLE
Insanity warning

### ISSUE THREAD

**Issue by essadji** [angular/angular#493]
(SPOILER ALERT: I'm an angular noob and what follows may just emphasize that very fact ...)
This is what my debugger tells me after throwing an exception:
          // Insanity Warning: scope depth-first traversal
          // yes, this code is a bit crazy, but it works and we have tests to prove it!
          // this piece should be kept in sync with the traversal in $digest
          // (though it differs due to having the extra check for $$listenerCount)
          if (!(next = ((current.$$listenerCount[name] && current.$$childHead) ||
              (current !== target && current.$$nextSibling)))) {
            while (current !== target && !(next = current.$$nextSibling)) {
              current = current.$parent;
            }
Does that mean I have found proof that it IS crazy or at least not working flawlessly?
The actual error in Chrome:
           Uncaught TypeError: Cannot read property '$$nextSibling' of null (angular.js:14714)

**Comment by pkozlowski-opensource** [comment]
@essadji:
* this is wrong repo ( I guess you wanted to open the issue in https://github.com/angular/angular.js)
* you need to provide a live reproduce scenario (using plunker, jsfiddle or similar) if you believe that there is a bug in AngularJS
* if you are not sure that this is a bug but rather looking for general help, please use on of the support forums: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
