### ISSUE TITLE
Angular DevTools causes empty app root

### ISSUE THREAD

**Issue by Gridiron** [angular/angular#49305]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

1. In setting of extensions set "This can read and change site data" to "On all sites"
![image](https://user-images.githubusercontent.com/36860748/222674922-7fd2fd60-c491-4192-ac65-5a2dc3cd6b7e.png)
2. Start the app
I see empty page. My app-root element is empty.
![image](https://user-images.githubusercontent.com/36860748/222675696-6e63120f-8ddb-4609-9611-f4b55bdbe24b.png)

Extension worked perfectly, but I started facing this issue two weeks ago . So I have to remove the extension and without the extension my app works fine. 
But I really want to use the extension so I investigated a little bit further and I found a workaround. If you set "This can read and change site data" to "When you click the extension" it works as usual. And after clicking on the extension it works fine.
But I really want the extension working as before(with "On all sites" option without clicking on the extension) so maybe you have an idea why this happens.
Angular version: 15.0.4. Chrome version: 110.0.5481.178. 

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

Expected behavior: It should start the app as usual with "On all sites" option
Actual behavior: I see empty page and app-root is empty with "On all sites" option

### Please provide a screenshot if possible [Bug Report only]

![image](https://user-images.githubusercontent.com/36860748/222674200-633145cb-04b9-4890-a8fa-56d237cb8ef5.png)

### Please provide the exception or error you saw [Bug Report only]

```true
No errors
```

**Comment by JeanMeche** [comment]
So, the app isn't bootstrapping and you have no errors in the console ?

**Comment by Gridiron** [comment]
Yeah, no errors. 
Yeah, I upgraded the app to 15.2.1 and it didn't help

**Comment by Gridiron** [comment]
> So, the app isn't bootstrapping and you have no errors in the console ? Do you have that issue with a 15.2 app ?

Yeah, no errors.
Yeah, I upgraded the app to 15.2.1 and it didn't help

**Comment by JeanMeche** [comment]
Do you still have this issue ? If so can you provide an repro on Stackblitz or on a github repo ?

**Comment by alxhub** [comment]
Closing as no reproduction was provided.
