### ISSUE TITLE
Element of set data structure can not display in dev-tools ?

### ISSUE THREAD

**Issue by jpeace08** [angular/angular#49312]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

**Comment by JeanMeche** [comment]
OPs ticket isn't very clear, here is a sum up in one image : 


![Screenshot 2023-03-04 at 12 23 21](https://user-images.githubusercontent.com/1300985/222897183-0def4ef7-6190-4ad6-9555-b5a46c7c2896.png)

Arrays or classe instances can be inspected but not Sets.

**Comment by JeanMeche** [comment]
Per #49316, we only display the set size, not the content.
