### ISSUE TITLE
triggerEventHandler does not bubble the event to parent element

### ISSUE THREAD

**Issue by sameerthekhans** [angular/angular#49314]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I have

`app.component.html`
```html
<button (click)="clickButton()">
  <span>Test</span>
</button>
```

`app.component.ts`
```typescript
clickButton() {
  console.log('Clicked...');
}
```

I am trying to click the `span` element which is wrapped inside `button` and wrote the below tests

```typescript
const spanEl = fixture.debugElement.query(By.css('span'));
spanEl.triggerEventHandler('click');

expect(component.clickButton).toHaveBeenCalled(); //clickButton never called
```
The above tests failed

Whereas the below test with native click works

```typescript
const compiled = fixture.nativeElement as HTMLElement;
const spanEl = compiled.querySelector('span') as HTMLSpanElement;
spanEl.click();

expect(component.clickButton).toHaveBeenCalled(); //works
```

Is this a bug?

### Please provide the exception or error you saw

```true
No errors, but the expected function was not invoked
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.5
Node: 14.20.1
Package Manager: npm 6.14.17
OS: darwin x64

Angular: 15.2.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.1
@angular-devkit/build-angular   15.2.1
@angular-devkit/core            15.2.1
@angular-devkit/schematics      15.0.5
@angular/cli                    15.0.5
@schematics/angular             15.0.5
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by JeanMeche** [comment]
Maybe the doc isn't explicit about this but I think that's the expected behaviour , [per the doc](https://angular.io/api/core/DebugElement#triggereventhandler): 

> Triggers the event by its name if there is a corresponding listener in the element's listeners collection.

And that's exactly what the code does: 

https://github.com/angular/angular/blob/e1355e7d16337177866cc1f8654b76381f26dae3/packages/core/src/debug/debug_node.ts#L346-L379

**Comment by pkozlowski-opensource** [comment]
>  I think that's the expected behaviour

It is absolutely by design and something we don't plan on changing.
