### ISSUE TITLE
Over two “< input type=number min= >” element in ngRepeat, just one can  display the number.

### ISSUE THREAD

**Issue by harole** [angular/angular#4932]
### html:
![image](https://cloud.githubusercontent.com/assets/4095799/10751999/56978c52-7cc0-11e5-8778-7e436fe946fc.png)
### js:
![image](https://cloud.githubusercontent.com/assets/4095799/10752021/7d1d6004-7cc0-11e5-92d4-96db6c2ebf9a.png)
### description:
I have three input element with "min" type, and they have same values with the "$scope.data".
### problem:
Just the last one can display in input element. And I don't know why, anybody help me?Thank you!

### sound code:
http://jsbin.com/yewipawiqe/edit?html,js,output

**Comment by gkalpak** [comment]
This repo is for Angular 2. You are looking for: https://github.com/angular/angular.js

**Comment by harole** [comment]
@gkalpak I am sorry for that.
