### ISSUE TITLE
Unable to remove # (Prettier URL) in AngularJs 1.8.2 By Enabled HTML5Mode

### ISSUE THREAD

**Issue by hemavjh** [angular/angular#49321]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

We are trying to use prettier URL in our application using Html5Mode=true in angularjs Version 1.8.2 . But It has not solved the issue
Changes I have made are below,

File Name : _layout.cshtml

<base href="@Url.Content("~/")" />

File Name: app.js
EmpApp.config(['$routeProvider', '$locationProvider', function ($routeProvider, $locationProvider) {
    var baseUrl = $("base").first().attr("href");
   
    $locationProvider.hashPrefix('');
    $locationProvider.html5Mode(true);
    console.log(baseUrl);
    $routeProvider.
        //when('/', {
        //    templateUrl: baseUrl + 'Home/Views/HomePage.html',
        //    controller: 'homeController'
        //}).
    when('/login', {
        templateUrl: baseUrl + 'Login/Views/Login.html',
        controller: 'LoginController'
    }).
    when('/signup/:InstitutionCode', {
        templateUrl: baseUrl + 'Login/Views/Signup.html',
        controller: 'SignupController'
    }).
   when('/home', {
       templateUrl: baseUrl + 'Home/Views/HomePage.html',
       controller: 'homeController'
   }).

My Original URL:
http://localhost:49000/Home/Index#/InstitutionSubscriptionHospitalAdmin_view

After changes Expected URL :

http://localhost:49000/InstitutionSubscriptionHospitalAdmin_view

After changes Actual changes 

http://localhost:49000/#%2Fhome

**Comment by JoostK** [comment]
Hi @hemavjh, this is the repository for Angular, not [angular.js](https://github.com/angular/angular.js). The latter is no longer supported.
