### ISSUE TITLE
Cannot remove outlets from path

### ISSUE THREAD

**Issue by docaohuynh** [angular/angular#49328]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

I have route like this
```
const routes: Routes = [
  {
    path: 'outlet-one',
    loadChildren: () => import('./outlet-one/outlet-one.module').then(m => m.OutletOneModule),
    outlet: 'info'
  },
  {
    path: 'outlet-two',
    loadChildren: () => import('./outlet-two/outlet-two.module').then(m => m.OutletTwoModule),
    outlet: 'info'
  },
  {
    path: 'foo',
    loadChildren: () => import('./foo/foo.module').then(m => m.FooModule),
  },
];
```
When the route http://localhost:4200/(info:outlet-two') is open. I want to go to http://localhost:4200/foo by clicking an anchor
```
<a [routerLink]="['/foo']">Goto Foo component </a>
```
The link will be http://localhost:4200/foo(info:outlet-two)

Expected behavior

Link I want  http://localhost:4200/foo

### Please provide a link to a minimal reproduction of the bug

https://github.com/docaohuynh/angular15-router-test

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.1
Node: 18.14.1
Package Manager: npm 9.3.1
OS: darwin x64

Angular: 15.2.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
```

**Comment by JeanMeche** [comment]
Hi, thanks for reporting that issue. 
See #13523 or #15338, it's not a regression. 

If you want to clear secondary routes, please see [the documentation about it](https://angular.io/guide/router-tutorial-toh#clearing-secondary-routes). 

For your case, you will have to use:  `<a [routerLink]="['/foo', { info: null }]">Goto Foo component </a>`

**Comment by docaohuynh** [comment]
> <a [routerLink]="['/foo', { info: null }]">Goto Foo component </a>

@JeanMeche  I have try both `<a [routerLink]="['/foo', { outlets: { info:null } }]">Goto Foo component </a>`  and `<a [routerLink]="['/foo', { info: null }]">Goto Foo component </a>`
But it not my expect, the url will be `http://localhost:4200/foo(info:outlet-two)` and `http://localhost:4200/foo;info=null(info:outlet-two)`

**Comment by JeanMeche** [comment]
Looks like you need `<a [relativeTo]="route.parent" [routerLink]="['/', {outlets: {'info': null}}]>`. where `route` is the `ActivatedRoute`. 

But keep in mind that @atscott did some work on this and things will change with v16.

**Comment by docaohuynh** [comment]
@JeanMeche I have try but none of this words for me

```
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { Component } from '@angular/core';

@Component({
  standalone: true,
  selector: 'app-outlet-two',
  imports: [RouterModule],
  template: `<p>outlet-two works!</p>
  <a [routerLink]="['/foo', { outlets: { info:null } }]">Goto Foo component </a>
  <br />
  <a [routerLink]="['/foo', { info: null }]">Goto Foo component </a>
  <br />
  <button (click)="gotoFoo()">goto Foo component</button>
  <br />
  <a [relativeTo]="route.parent" [routerLink]="['/foo', {outlets: {'info': null}}]">Goto Foo component </a>
  <br />
  <a [relativeTo]="route.parent" [routerLink]="['/foo', {info: null}]">Goto Foo ActivatedRoute component </a>
  <br />`,
  styleUrls: ['./outlet-two.component.scss']
})
export class OutletTwoComponent {
  constructor(private router: Router, public route: ActivatedRoute) { }
  gotoFoo(): void {
    this.router.navigate(['/foo', { outlets: { info: null } }]);
  }
}

```

**Comment by JeanMeche** [comment]
I imported your project on stackblitz, it only worked when using `/` as first item in the array.

**Comment by docaohuynh** [comment]
@JeanMeche 
I run it on localhost this code still not working
```
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { Component } from '@angular/core';

@Component({
  standalone: true,
  selector: 'app-outlet-two',
  imports: [RouterModule],
  template: `<p>outlet-two works!</p>
  <a [routerLink]="['/', 'foo', { outlets: { info:null } }]">Goto Foo component </a>
  <br />
  <a [routerLink]="['/','foo', { info: null }]">Goto Foo component </a>
  <br />
  <button (click)="gotoFoo()">goto Foo component</button>
  <br />
  <a [relativeTo]="route.parent" [routerLink]="['/', 'foo', {outlets: {'info': null}}]">Goto Foo component </a>
  <br />
  <a [relativeTo]="route.parent" [routerLink]="['/', 'foo', {info: null}]">Goto Foo ActivatedRoute component </a>
  <br />`,
  styleUrls: ['./outlet-two.component.scss']
})
export class OutletTwoComponent {
  constructor(private router: Router, public route: ActivatedRoute) { }
  gotoFoo(): void {
    this.router.navigate(['/', 'foo', { outlets: { info: null } }]);
  }
}

```

**Comment by JeanMeche** [comment]
Yeah, we might be on to something. 

`<a [routerLink]="['/', { outlets: { info: null } }]">Goto Foo component </a>`

Works fine when used on `OutletOneComponent` but not on `OutletTwoComponent`.

**Comment by docaohuynh** [comment]
@JeanMeche 
This code actually close outlets 
`<a [routerLink]="['/', { outlets: { info: null } }]">Goto Foo component </a>`
But when i want to go to another route it not working
`<a [routerLink]="['/', 'another-route', { outlets: { info: null } }]">Goto Foo component </a>`

**Comment by atscott** [comment]
This is working as expected. RouterLink applies commands to the existing ActivatedRoute. When you do not apply commands to an outlet, the existing one is retained. If you’re just trying to navigate to some absolute URL, I would recommend not using RouterLink at all because it will be difficult to clear the outlet. 

Beyond that, this is a support request. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by atscott** [comment]
Remember that where you're applying outlet commands matters a lot. Your outlets are siblings of the `foo` route so you have to apply the outlet clearing on the same level. You weren't achieving consistent results because this wasn't considered. These should all look more like this: `[routerLink]="['/', {outlets: {primary: 'foo', info:null } }]`. And because you're doing absolute navigation, it doesn't actually matter what the `ActivatedRoute` is for `relativeTo`.

**Comment by docaohuynh** [comment]
> [routerLink]="['/', {outlets: {primary: 'foo', info:null } }]

@atscott  tks for your help this code works for me
`[routerLink]="['/', {outlets: {primary: ['foo', 'bar', 'something'], info:null } }]"`

Nice if have function something like this to clear all outlet
`[routerLink]="['/', {outlets: {primary: ['foo', 'bar', 'something'], secondary:null } }]"`
