### ISSUE TITLE
Validate `formControlName` for Typed Forms

### ISSUE THREAD

**Issue by snebjorn** [angular/angular#49334]
### Command

build, lint, serve

### Description

Now that strongly typed forms exists it would be ideal if the template would also be checked.

Currently `formControlName` accepts `string | number | null`. So incorrect values won't result in build or lint errors.

```html
<form [formGroup]="myTypedForm">
  <input formControlName="myControl">
</form>
```

### Describe the solution you'd like

Validate the input to `formControlName` exists on the relevant typed form when `strictTemplates` is turned on.

**Comment by JoostK** [comment]
Duplicate of #48255.
