### ISSUE TITLE
Add possibility to reset Form value and states

### ISSUE THREAD

**Issue by choeller** [angular/angular#4933]
With the current Forms API is not possible to reset states like "dirty" or "pristine". 

A typical scenario would be, to have a form, and on submit add the entry to a database / list. After submitting the value the form should reset to the initial state. Also all flags should be resetted. 

When using the model-driven approach it is currently not possible at all to reset the values - only chance is to create a new form. This plnkr demonstrates the model-driven approach:

http://plnkr.co/edit/vxr48zAIM8g4WFD25Ts8

When using the template driven approach it is possible to reset the ng-model object to some initial state, but in this case the flags like dirty and pristine don't reset:

http://plnkr.co/edit/rkhlr3vFHn7R6oMGTU7v

With this behaviour it is not possible to utilize the form states for something like canDeactive 

IMO there needs to be some way to reset the value and all flags of the form to the initial state. I still have no idea how this could be solved in the ng-model scenario, as there is no dedicated object for the form itself in controller - would it be correct to always reset the flags, when changing the ng-model object programmatically? like this:

`
this.newEntry = {};
`

**Comment by danhalliday** [comment]
+1

**Comment by arozwalak** [comment]
+1

**Comment by basvandenheuvel** [comment]
+1

I've got the same issue with my ControlGroup. You can't set the Controls back to untouched and there is no way to empty all Controls in a ControlGroup using one command. I've created this plnkr http://plnkr.co/edit/Qb6VDTFaEOVZTTTfjl9p?p=preview

**Comment by matthewdenobrega** [comment]
+1 I think AbstractControl should have a reset() method that gets implemented by Control, ControlGroup, and ControlArray. This should set _pristine to true, _touched to false, and re-run validation.

**Comment by Fank** [comment]
+1
For example i have an input field (in a larger form, which saves on blur), but it should only save dirty controls. My workaround is to delete and readd the control to ensure everything is clear.

**Comment by frederikschubert** [comment]
+1

**Comment by benediktberger** [comment]
+1

**Comment by dsebastien** [comment]
+1

**Comment by astec** [comment]
+1

**Comment by basvandenheuvel** [comment]
Since i guess i'm not the only one who has been waiting for this to be fixed for months. I can share my ugly workaround for this issue. I develop my NG2 application using typescript. What i do right now is `control._touched = false;`. Ofcourse this gives a big fat error in my IDE, but once it is compiled to javascript, it does work :)

**Comment by d3lm** [comment]
+1

**Comment by spock123** [comment]
@basvandenheuvel  that is a great solution, will try that.

My IDE has error detection disabled anyway, I use Webpack with resolve/alias which totally confuses VS Code when checking imports :)

I've now spent 3 days porting a large NG1 app to NG2 and I like NG2 more and more .. it's really great.. some syntactical sugar is needed but that will come.. I'm really excited.

**Comment by ajtowf** [comment]
Concider the solution from the angular material team, they introduced

$setUntouched() and
$setPristine()

on the form.

**Comment by MarkPerryBV** [comment]
+1

**Comment by cebor** [comment]
+1

**Comment by gsans** [comment]
Cool. Lars have you considered blogging about your migration experience? It
would be much appreciated by the community. Thanks!

**Comment by moosetraveller** [comment]
+1

**Comment by spock123** [comment]
@gsans  yeah - I'm not quite done yet, exploring the whole observable-pattern thing. It's pretty cool but I need to wrap my pretty little head around a few more things. . But yes, would love to.....

**Comment by basvandenheuvel** [comment]
Currently working on a PR covering this. I'll notify in this issue once the PR has been submitted.

**Comment by basvandenheuvel** [comment]
@/all https://github.com/angular/angular/pull/6679

**Comment by iorlas** [comment]
Guys, it is not even funny or something, I tried to use angular2 and stuck on this. I'd vote for same API as angular1 for has. But just to create property setters, like we already have getter for pristine, dirty, touched.
We don't need any magic right now, just an ability to do things any way.

**Comment by basvandenheuvel** [comment]
@iorlas check my open PR

**Comment by iorlas** [comment]
@basvandenheuvel It looks awesome! But I really want it to be merged before we use it in production. Currently, I can't really afford any time to participate, but I want you to know that you awesome :+1:  :beer:

**Comment by OsoianMarcel** [comment]
+1

**Comment by Balderscape** [comment]
+1

**Comment by simonbrandl** [comment]
+1

**Comment by EdgarArguelles** [comment]
+1

**Comment by markdrake** [comment]
+ 1, we just got stuck in this, looking forward for a solution soon (y)

**Comment by rrgarciach** [comment]
+1

**Comment by zoechi** [comment]
There is already a PR #6679

**Comment by Hongbo-Miao** [comment]
+1

**Comment by deepakgd** [comment]
+1

**Comment by neroniaky** [comment]
+1

**Comment by SimonHawesome** [comment]
+1

**Comment by PascalPrecht** [comment]
Can we stop +1'ing on issues? Thanks!

#6679 does *not* introduce APIs for resetting/clearing a form's state.

**Comment by akhilhhh94** [comment]
onSubmit(value:any):void {
  //send some data to backend
  form.controls.forEach((name, control) => {
    control.updateValue('');
    control.setErrors(null);
  });
}

**Comment by choeller** [comment]
@akhilhhh94 Sorry to say this, but this is way too simple. For a real solution you would e.g. 

- need to deal with boolean or numeric values (e.g. for checkboxes)
- consider the default values from form definition
- deal with nested ControlGroups
- deal with ControlArrays
- ...

**Comment by seenimurugan** [comment]
+1

**Comment by dannylagrouw** [comment]
While we're waiting for the PR to make it through, here's an IDE-friendly (but still ugly) workaround:
```typescript
this.form['_touched'] = false;
StringMapWrapper.forEach(this.form.controls, (control: AbstractControl, name: string) => {
  control['_touched'] = false;
});
```

**Comment by born2net** [comment]
+1

**Comment by deepakgd** [comment]
Please stop doing  +1 or -1. If anyone know how to reset form in proper way mean Please do plunker and share the link. It will be helpful for all developers. Because we guys just now started learning angular2

**Comment by zoechi** [comment]
@deepakgd AFAIK the current workaround is to create a function that creates the form and drop the previous instance and create a new one when you need to reset.

**Comment by deepakgd** [comment]
ok can you please share some example? I have tried but it was not working. Please check this  [link](http://sparkling-development.surge.sh/#/CRUD-only-FE) 

component.ts

```
import {Component} from 'angular2/core';
import {FormBuilder, Validators, ControlGroup} from 'angular2/common';

function emailValidator(control) {
  var EMAIL_REGEXP = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;

  if (!EMAIL_REGEXP.test(control.value)) {
    return {invalidEmail: true};
  }
}

function mobileValidator(control) {
	var MOBIL_REGEXP = /^[0-9]{10}$/;

	if(!MOBIL_REGEXP.test(control.value)){
		return {invalidMobile: true};
	}
}



@Component({
	selector: 'crud',
	templateUrl: 'app/components/CRUD-only-FE/CRUD-only-FE.html'
})

export class CRUDOnlyFE{
	createEmployeeForm;
	createEmployeeJson;
	employees;
	employeeCreate;
	content;
	constructor(public createForm: FormBuilder){
		this.createEmployeeForm = createForm.group({
			employeeName: ["", Validators.required],
			employeeEmail: ["", Validators.compose([emailValidator])],
			employeeMobile: ["", Validators.compose([mobileValidator])]
		});
		this.employees = [{ "employeeName": "asd", "employeeEmail": "asd@asd.com", "employeeMobile": "2342342323", "isEditable": false },];
		this.employeeCreate = {};
		this.content = "fghjk"
	}	
	createEmployee(){
		console.log(this.employeeCreate)
	 	this.createEmployeeJson = this.employeeCreate;
	 	this.employeeCreate.isEditable = false;
		this.employees.push(this.employeeCreate);
	 	console.log(this.employeeCreate)
	 	this.employeeCreate = {};
	 	this.createEmployeeForm.controls["employeeName"].updateValue("")
	 	this.createEmployeeForm.controls["employeeEmail"].updateValue("")
	 	this.createEmployeeForm.controls["employeeMobile"].updateValue("")
	 	console.log(this.createEmployeeForm.controls.employeeName.errors)
	}
	contentChange(){
		this.content = "sample";
	}
	makeEditable(data,index){
	    console.log(data)
	    this.employees[index].isEditable = true;
	}
	updateEditedData(data,index){
		data.isEditable = false;
	}
}

```

html file:

```
<h1>Create Employee</h1>
employee name using dirty and invalid, other fields are touched and invalid
<form (ngSubmit)="createEmployee()" [ngFormModel]="createEmployeeForm" #create='ngForm' novalidate>
	<input type="text" placeholder="Enter Employee Name" ngControl="employeeName" [(ngModel)]="employeeCreate.employeeName">
	<span style="color:red">
		<span *ngIf="create.form.controls.employeeName.dirty && !create.form.controls.employeeName.valid">
			Employee Name Required
		</span>
	</span>
	<input type="text" placeholder="Enter Employee email" ngControl="employeeEmail" [(ngModel)]="employeeCreate.employeeEmail">
	<span style="color:red">
		<span *ngIf="create.form.controls.employeeEmail.touched && !create.form.controls.employeeEmail.valid">
			Employee Email Required
		</span>
	</span>
	<input type="text" placeholder="Enter Employee Mobile" ngControl="employeeMobile" [(ngModel)]="employeeCreate.employeeMobile">
	<span style="color:red">
		<span *ngIf="create.form.controls.employeeMobile.touched && !create.form.controls.employeeMobile.valid">
			Employee Mobile Required
		</span>
	</span>
	<button type="submit">Create</button>
</form>
<div *ngIf="employees">
<br>
<table class="table table-bordered">
	<tr>
	  <th>Emp ID</th>
		<th>Employee Name</th>
		<th>Email</th>
		<th>Mobile</th>
		<th>Action</th>
	</tr>
	<tr *ngFor="#employee of employees #i=index">
		<td>{{i+1}}</td>
		<td [contentEditable]="employee.isEditable">{{employee.employeeName}}</td>
		<td>{{employee.employeeEmail}}</td>
		<td>{{employee.employeeMobile}}</td>
		<td><button class="btn btn-xs btn-primary" (click)="makeEditable(employee,i)" *ngIf="!employee.isEditable">Edit</button><button class="btn btn-xs btn-primary" (click)="updateEditedData(employee,i)" *ngIf="employee.isEditable">Update</button></td>
	</tr>

</table>

<pre>{{employees | json}}</pre>
</div>

<a (click)="contentChange()">{{content}}</a>
```

**Comment by Bretto** [comment]
+1

**Comment by onlyann** [comment]
The only (ugly) work around I found to reset a form is to re-create the `controlGroup`  and to force the destruction of the form element (otherwise, the form directives don't reflect changes in the newly created control group).

Here's a plunker that demonstrates it : https://embed.plnkr.co/kMPjjJ1TWuYGVNlnQXrU/

**Comment by PardeepJain** [comment]
@zoechi I have done the same in my case, drop the instance and create new one by calling function where all validation exist, but this one too did't reset my validation, have you any plunker for your code ? please post it.

**Comment by zoechi** [comment]
@PardeepJain I think calling `form.control['myControl'].updateValueAndValidity();` after recreation of the form for all controls should fix it.

**Comment by latestpost** [comment]
+1

I have tried all examples and validation is not reset

**Comment by irshadmalek11** [comment]
@onlyann - this solution works fine at first, but next time when I enter values in input fields and submit it always shows blank values in my component. Am I missing anything ?

**Comment by JessieWadman** [comment]
@irshadmalek11 The binding on your <form> element won't update to your new ControlGroup after you recreate it. People are using *ngIf on the <form> element to force the form binding to be recreated when they recreate the control group.

Another solution is to hack into the private members of the ControlGroup and Control classes. Not exactly a 'tidy' solution. But it works!

You can see it in action here:
[https://embed.plnkr.co/BGy9znDdSmYRlOkvOzRO/](https://embed.plnkr.co/BGy9znDdSmYRlOkvOzRO/)

Based on the Plunkr from @onlyann 
Notice the FormHelper class there. Feel free to nab that. It doesn't support nested groups, but I'm sure if that's what you're after, it's a good enough starting point.

Why this isn't supported out of the box, by the framework, I cannot understand. You can't reset the form's state, and you can't simply recreate the FormGroup. What's the story here? :-)

You can use that FormHelper as follows:

Assume:
// Super simple form
this.form = fb.group({ color: [], name: [] });

Scneario 1:
// Set initial values and mark form as dirty (you dirty form, you!)
// Useful in CRUD scenarios where you click the "Add" button and want to reuse a form.
// Control names not present in the values argument are set to null (name in this case).
formHelper.updateForm(this.form, { color: "Red" });

Scenario 2:
// Load stuff from server and put all that yummy goodness into the form
var remoteModel = ...
formHelper.updateForm(this.form, remoteModel);  
// Set all the flags to happy happy state
formHelper.markFormAsUntouched(this.form); 
// You can now here detect changes made form initial state.

// In case your remote object doesn't map 1-1 with your control names:
formHelper.updateForm(this.form, { color: remoteModel.colorValue, name: remoteModel.userName });

Scenario 3:
// Save all that awesome user input somewhere
...
// Reset the form to empty values (or initial values, if you prefer)
formHelper.updateForm(this.form, {});
formHelper.markFormAsUntouched(this.form);


Hope this helps!

**Comment by bentolor** [comment]
Just started to suck in the Angular 2 documentation like a champ and liked every bit of it. 

Until I arrived at the [Forms Chapter Section **»Add a hero and reset the form«**](https://angular.io/docs/ts/latest/guide/forms.html#!#add-a-hero-and-reset-the-form) which gave me a biiiiiiig _WTF?!!_

````
  active = true;

  newHero() {
    this.model = new Hero(42, '', '');
    this.active = false;
    setTimeout(() => this.active = true, 0);
  }
````
and
````
<form *ngIf="active">
````

Glad to see that the removal of this workaround is planned for the final milestone. But on skimming this GH issue I did not see any proposal how a reset feature should like like or could be incorporated into the API. Really no constructive ideas yet?

**Comment by zoechi** [comment]
@bentolor forms module is being reworked currently

**Comment by born2net** [comment]
good more API changes... LOL

**Comment by zoechi** [comment]
@born2net sure so you developer guys don't get rusty ;p

**Comment by born2net** [comment]
xD

**Comment by bentolor** [comment]
@born2net  @zoechi I'm rather puzzled to read about that when a software is already declared as RC2 maturity.

Any issue tracking the "forms module rework" for reference?

**Comment by bentolor** [comment]
TIL: Here is the Document describing the [Forms Upcoming Change Proposal](Forms Upcoming Change Proposal): 

> This doc describes the plan for **breaking changes only**.   [...] feature requests, and bug fixes to come that are additive, and thus not included in this doc (e.g. radio buttons, **resetting forms,** etc).  These changes will be described **in an upcoming doc.**

**Comment by MikeMatusz** [comment]
I'm getting a 404 from the link to the change proposal.

**Comment by skreborn** [comment]
@MikeMatusz [Here you go.](https://docs.google.com/document/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub)

**Comment by MarkPerryBV** [comment]
#9974

**Comment by istiti** [comment]
any news here ? because i get problem https://stackoverflow.com/questions/41762240/form-disable-get-errors

**Comment by adrhc** [comment]
The form reset used now (23 Jan 2017) in documentation:
```
<button type="button" class="btn btn-default" (click)="newHero(); heroForm.reset()">New Hero</button>
  newHero() {
    this.model = new Hero(42, 'NOT APPLIED VALUE', ''); -> reset ignores the model's value!!!
  }
```
The new model's value is not used in form fields.

**Comment by adrhc** [comment]
Hm, now (23 Jan 2017) I made it work like this:
```
newHero() {
    return this.model = new Hero(42, 'APPLIED VALUE', '');
}
<button type="button" class="btn btn-default" (click)="heroForm.resetForm(newHero())">New Hero</button>  

```

**Comment by thepixelninja** [comment]
Its not recommended but i managed to do it avoiding compilation errors and ts errors using this method...

`this.yourControlNameHere['_touched'] = false;`

this suppresses the ts errors from tsLint and the compilation errors.

**Comment by kanishkad123** [comment]
you can consider using 
this.formGroup.reset() which resets all the controls in the defined formgroup

**Comment by sandraacha9** [comment]
FormControl resert method does not work with datepicker in my case when the date is manually entered.

--------HTML--------
<input class="form-control" #datePicker name="date" type="text" [(ngModel)]="flightDate" formControlName="date" id="date" bsDatepicker (change)="flightDate = datePicker.value" [bsConfig]="bsConfig">

--------TYPESCRIPT--------
clearDate(input) {
    this.flightDate = null; // ngModel
    input._selected = []; // referencia
    input.inputElementValue = ''; // DOMValue
    input.updateValue(null);
    input.markAsPristine();
    input.reset();
  }

**Comment by Aorewen** [comment]
Is there a way to recheck others inputs validation when an input value change in a template driven form ?
