### ISSUE TITLE
fakeasync not working with await and Jest

### ISSUE THREAD

**Issue by eosgortor** [angular/angular#49365]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

When upgrading to Nx 15 (which means Angular 15.1.2 and Jest 29.5.0) some of our tests stopped working. We found it is the combination of Jest/fakeAsync/await that causes the problems. If a component uses async/await the actions are not awaited by fakeasync.

See the reproduction repo. You can execute the tests with `npm testJest` and `npm testJasmine` to see the difference.

### Please provide a link to a minimal reproduction of the bug

https://github.com/eosgortor/fakeAsyncNotAwaiting

### Please provide the exception or error you saw

```true
The awaited actions are not executed before asserting.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.1
Node: 18.12.1
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 15.2.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.1
@angular-devkit/build-angular   15.2.1
@angular-devkit/core            15.2.1
@angular-devkit/schematics      15.2.1
@schematics/angular             15.2.1
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by JoostK** [comment]
This is due to #38782, where using native async/await cannot be intercepted by Zone.js. You'll need to configure your Jest setup to downlevel async/await to using generators, or target ES2016 for your tests entirely.
