### ISSUE TITLE
feat(router 1.x): Add support for auxiliary routes

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#4937]
The component router for angular 1.x currently only supports unnamed outlets and doesn't include support for creating named outlets for using auxiliary routes.

**Comment by timkindberg** [comment]
What are auxiliary routes anyway?

**Comment by brandonroberts** [comment]
Auxiliary routes are independent routes that can be loaded alongside the primary route. I think they are similar to named views in ui-router. They can have their own URLs and route parameters also though.

**Comment by btford** [comment]
So I'd really like to make headway on this, but I need to get #3813 taken care of first.

The good news is that the refactor to how tests work that I did should make writing these tests for parity much easier, but it does mean that we'll have to add transpilation to the 1.x side of the tests.
