### ISSUE TITLE
RouteReuseStrategy.shouldReuseRoute no routing data

### ISSUE THREAD

**Issue by sysmat** [angular/angular#49375]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

```ts
shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {     
        console.log('shouldReuseRoute.future.reuseComponent=', future.data.reuseComponent); // undefined
        console.log('shouldReuseRoute.curr.reuseComponent=', curr.data.reuseComponent); // undefined
        return future.data.reuseComponent;
    }
```

```ts
{
    path: routePaths.organization,
    canMatch: [authGuard],
    canActivate: [getRoleGuard([ProfileRole.PORTAL_ADMIN]), orgGuard],
    loadChildren: () => import('./components/organization/organization.module').then(m => m.OrganizationModule),
    data: {
      roles: [ProfileRole.PORTAL_ADMIN],
      reuseComponent: false
    },
    runGuardsAndResolvers: 'always'
  }
```

- `{ provide: RouteReuseStrategy, useClass: AppRouteReuseStrategy }`

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.2
Node: 18.12.1
Package Manager: npm 8.18.0
OS: win32 x64

Angular: 15.2.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.2
@angular-devkit/build-angular   15.2.2
@angular-devkit/core            15.2.2
@angular-devkit/schematics      15.2.2
@schematics/angular             15.2.2
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

I forked a stackblitz demo I found, updated to v15, and observed that there _is_ data. https://stackblitz.com/edit/angular-routereusestrategy-demo-avm7vm?file=src%2Fpolyfills.ts,src%2Fapp%2Fmaltsev-reuse.ts

**Comment by sysmat** [comment]
@atscott in your  stackblitz demo you see **shouldReuseRoute** is always with out data, if this is ok? It should be mentioned in documentation, but strange API it is

**Comment by atscott** [comment]
@sysmat It is _not_ always without data. Here's a screenshot of the console log
![image](https://user-images.githubusercontent.com/479713/224377985-68e7045c-88ec-4623-900b-017e8e8e72a7.png)
