### ISSUE TITLE
ERROR Error: NG0900: Error trying to diff '[object Object]'. Only arrays and iterables are allowed

### ISSUE THREAD

**Issue by Brian-urogallo** [angular/angular#49383]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

i have problems to iterate with the *ngFor directive 

### Please provide the exception or error you saw

```true
ERROR Error: NG0900: Error trying to diff '[object Object]'. Only arrays and iterables are allowed
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.1
Node: 19.0.0 (Unsupported)
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 15.2.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router        

Package                         Version
---------------------------------------------------------     
@angular-devkit/architect       0.1502.1
@angular-devkit/build-angular   15.2.1
@angular-devkit/core            15.2.1
@angular-devkit/schematics      15.2.1
@schematics/angular             15.2.1
rxjs                            7.8.0
typescript                      4.9.5
```

### Anything else?

here is the code with im having problems: 

dashboard.component.ts:

import { Component, OnInit } from '@angular/core';
import { Product } from 'src/app/interfaces/product';
import { ProductService } from 'src/app/services/product.service';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit{

  listProduct: Product[] = [];

  constructor (private _productService: ProductService) {}

  ngOnInit(): void {
    this.getProduct();
  }

  getProduct(){
    this._productService.getProduct().subscribe(data =>{
      // const dataArray = Object.values(data);
      this.listProduct = data
      console.log(this.listProduct)
    })
  }

}

dashboard.component.html

<app-navbar></app-navbar>
<div class="container">
    <h1 class="mt-3 text-center">Productos</h1>
    <table class="table text-center">
        <thead>
          <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Descripcion</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let item of listProduct">
            <td>{{ item.name }}</td>
            <td>{{ item.description }}</td>
          </tr>
        </tbody>
      </table>
</div>

**Comment by AndrewKushnir** [comment]
Could you please create a [StackBlitz](https://stackblitz.com/) demo reproducing the problem, so that we can take a look? Also, you mentioned that it's a regression, could you please let us know which version you've used before where the same component worked differently?

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
