### ISSUE TITLE
Add createInjector() with module as parameter to public API

### ISSUE THREAD

**Issue by AndreasHae** [angular/angular#49394]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

This issue bases off the discussion in #37229.

`createInjector` is useful to statically inject providers from lazy-loaded modules. My specific use case is validating my routing config which references lazy-loaded modules.

In [this](https://github.com/angular/angular/issues/37229#issuecomment-881769914) comment, @alxhub mentioned that the function is exposed via `Injector.create`, which is only half-true since only the module name to the function, stripping it from its providers and imports:
```ts
  // https://github.com/angular/angular/blob/main/packages/core/src/di/injector.ts#L110
  static create(
      options: StaticProvider[]|{providers: StaticProvider[], parent?: Injector, name?: string},
      parent?: Injector): Injector {
    if (Array.isArray(options)) {
      return createInjector({name: ''}, parent, options, '');
    } else {
      const name = options.name ?? '';
      return createInjector({name}, options.parent, options.providers, name);
    }
  }
```

### Proposed solution

An overload for `Injector.create` should be added which accepts a module definition and returns its injector, just like the private `createInjector` does.

### Alternatives considered

For now I'll have to use the private `ɵcreateInjector`.

**Comment by JoostK** [comment]
I think you're looking for [`createEnvironmentInjector`](https://angular.io/api/core/createEnvironmentInjector)?

**Comment by AndreasHae** [comment]
This takes an array of providers and a parent injector as parameters. What I'm looking for is a function that takes the module and gives me an injector with all of the module's providers (registered in the module itself as well as its imports), just like the private `createInjector` variant.

**Comment by JoostK** [comment]
That's what [`importProvidersFrom`](https://angular.io/api/core/importProvidersFrom) is for:

```ts
const injector = createEnvironmentInjector([importProvidersFrom(MyModule)], parentInjector);
```

This API expects that the application's injector is provided as parent injector. As of today you could pass `Injector.NULL as EnvironmentInjector` or `null!` there to work around that limitation, but there's no guarantee that it continues to work since the cast/null assertion is unsound.

**Comment by AndreasHae** [comment]
Amazing, that's exactly what I needed. Thanks @JoostK!
