### ISSUE TITLE
[Feature Suggestion - reduce verbosity] No "relativeTo" attribute required when imperative navigation to relative path 

### ISSUE THREAD

**Issue by hannah23280** [angular/angular#49402]
### Description

 Currently, the imperative routing logic to a relative path is as shown
         this.router.navigate(['product'],{relativeTo: this.activatedRoute})

There is no issue with this, except for verbosity.  

### Proposed solution

To cut down verbosity, I would like to suggest the optional need for relativeTo for such scenario.  When the router detects there is a prefix ./  in the url, it should take it to be relative to the current activated route.  This also have a benefit of not requiring to inject an ActivatedRoute into the component class just purely for this purpose. E.g
```
    this.router.navigate(['./product'])  <==notice the ./ prefix
```

### Alternatives considered

Create a new router api
```
this.router.relativeNavigate(['product'])  <--by default, relative to current activated route. 
```

**Comment by atscott** [comment]
This would be great, but unfortunately it's not really possible. The `Router` is an Injectable provided in `root`. There is no way to know what the contextual `ActivatedRoute` is from the call site without passing it in. We do this where possible though (in `RouterLink` https://github.com/angular/angular/blob/7dbe328b282f334734531c67eabb005b20ec38cd/packages/router/src/directives/router_link.ts#L367)
