### ISSUE TITLE
@OnPushInput/Output for components using OnPush change detection

### ISSUE THREAD

**Issue by arthur-clifford** [angular/angular#49403]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

I do a lot with data binding and these days making a new component means I set changeDetection to ChangeDetectionStrategy.OnPush and set a private cdr:ChangeDetectorRef variable in the constructor. 

I then create a Refresh() function that checks if the component is setup and if so will call the cdr.detectChanges() function. 

This is great performance wise because I can change a variety of component properties and trigger Refresh when I want.

The down side is that changes to @Input variables don't necessarily trigger an update.

So I end up having to implement a private variable to hold data in, and use a setter and getter where the setter in addition to setting the variable will trigger a change detection.

```
private _someVar:string = 'helloWorld';
@Input(someVar)
set someVar(value:string) {
  this._someVar = value;
  this.Refresh();
}
get someVar():string {
  return this._someVar;
}
```

I realize that using OnPush means I'm basically signing up for the hassle of these setters.  But it would be nice in an OnPush setup to have an @Input variant that is aware of this setup.

### Proposed solution

My thinking was something along the lines of:

```
private _someVar:string ='Hello World';
@OnPushInput(()=>{this.onRefresh()} ) someVar:string; 
```
or
```
@OnPushInput({onUpdate:()=>{this.onRefresh()}, saveAs:'_someVar'} ) someVar:string; 
```
That would transpile into the equivalent setter and getter for someVar that would store in private variable _someVar. 

The IDEs would ideally recognize someVar in templates as bindable and I would have the option in the controller code to set this._someVar="something" without triggering an update, or setting this.someVar = "something" which would trigger an update.

@OnPushInput would be for when you want input but not necessarily bind output.

@OnPushIO would be an addition evolution of this idea and would do the same thing as @OnPushInput but would additionally internally have a someVarChange:EventEmitter<somevar's type> event emitter which emits this.someVar (getter version) when the setter is used.

The idea would be to have:
```
private _someVar:string = 'HelloWorld';
@OnPushIO({saveAs:'_someVar',onUpdate:()=>{this.Refresh();}) someVar:string;
```
This would mean, setup someVar with a getter/setter and emitter so that it is two-way bindable.

### Alternatives considered

I know javascript has a defineProperty function, but that seems like overkill.

The proposed:
```
private _someVar:string = 'HelloWorld';
@OnPushIO({saveAs:'_someVar',onUpdate:()=>{this.Refresh();}) someVar:string;
```
Right now is:
```
private _someVar:string = 'Hello World';
@Input()
someVar(val:string) {
 this._val = val;
 this.someValChange.emit(this._val);
 this.Refresh();
}
get someVar():string {
 return this._val;
}
@Output()
someValChange = new EventEmitter<string>;
```
One of the rules of thumb in refactoring is if you are doing the same thing three or more times encapsulate the repeated functionality in a function and call it from the same place.

I do apologize if something like this exists, but I have not really seen it referred to in documentation or in discussions about @Input and @Output. Hence the feature request.

**Comment by mlc-mlapis** [comment]
@arthur-clifford It's really unclear what you are trying to do. If @Inputs don't change, why do you need to call their setters?

By the way: There is no guarantee of the order in which @Inputs are evaluated. It is also affected by order of attributes/properties bindings passed in a component template.

**Comment by arthur-clifford** [comment]
Huh? Inputs do change if they are part of binding, I want them to change. I not only know the inputs are not guaranteed to fire in any order, I want them to be dynamic, that’s the point. Its like having multiple sensors as an inputs and events will happen when they happen; that’s part of the power of Angular.


I’m not sure where communication broke down. I need to make sure anybody assigned to this or considering it has my understanding of Angular data binding and how @Input and @Output work. Especially when ChangeDetectionStrategy.OnPush  is used and how that affects data binding. 

 

So, in the spirit of clarity I am going to share my perspective so it can be corrected, understood, or hopefully make sure we’re all on the same page. Apologies in advance for the length, if you implement this perhaps it can be mined for documentation later:

 

ChangeDetectionStrategy.OnPush when set as a component’s changeDetection basically takes the component out of an “are-we-there-yet” mode of constantly checking the bound data, to using an injected ChangeDetectorReference instance that I as a developer must explicity trigger a detectChanges function on; this will then update the component’s template based on the current state of the component. Push is push in the sense of pushing an event rather than pulling/polling for information. 

 

To be clear the change detection only makes changes local to the current component for updating its own template bindings.

 

```

@Component({

  selector: 'app-some-component,

  templateUrl: './some-component.component.html',

  styleUrls: ['./some-component.component.scss'],

  changeDetection: ChangeDetectionStrategy.OnPush

})

export class PagingComponent implements AfterContentInit {

  private _ready:boolean = false;

  constructor(private cdr: ChangeDetectorRef) { }
   
  ngAfterContentInit() {

     this._ready = true;

     this.Refresh();

  }
  

  Refresh() {

     if(!this._ready) return;

     this.cdr.detectChanges();
  }



}

```

 

That is a relatively basic husk of a component using OnPush.  The relevant parts are the changeDetection defined in the @Component, the cdr variable defined in the constructor, and its usage in Refresh. The _ready variable is something I do to make sure it is safe to use cdr.

 

If I define any variables in this component that I want to bind to from its template, for the changes to take effect I must call Refresh().

 

 

Consider the following scenario:

Component A is setup like the component above and defines:

```

@Input() set someInput:string = ‘a default value’;

```

 

ComponentA has a template that binds to someInput

```
<title [innerHTML]=”someInput”></title>

```

Because of the refresh function being called when ngAfterContentInit is called detectChanges is triggered. Also, if the inputs are set when the component is initialized the values will be reflected. By setting ‘a default value’ that will be the initial value displayed if nothing changes it.

 

Component B implements Component A with one-way binding.

```

<componenta [someInput]=”myValue”></componenta>

```

 

Then on some event in Component B, myValue is changed such that ComponentA’s someInput value changes.

 

When the binding is triggered the someInput variable in ComponentA will now have a new value; but nothing will trigger cdr.detectChanges and I have no reasonable way to trigger the template update.

 

The solution: I have no choice but to define a setter and call detectChanges for my input if I want the change to the input to actually update my component’s template.

 

So the input definition changes to:

```

private _someInput:string  = ‘a default value’;

public @Input() set someInput(value:string) {

  this._someInput = value;

 this.Refresh();

}

public get someInput():string { return this._someInput; }

```

Now when ComponentB triggers bindings the setter is called with the new value, and I trigger the update of Component A’s template through Refresh.

 

Note the reason for the private variable:

*	the setter doesn’t store anything so I need to store the value somewhere.
*	I can set the value in the private variable from other functionality if I want without triggering the refresh if I need to do that, which sometimes I do. It is critical to have this option.
*	The getter allows me to bind to the public variable in ComponentA’s template and will reflect the private variable whenever Refresh is ultimately called.
*	The variable could be protected or public, however when using the getter and setter it is common practice to use a private variable.

 

Now, for two-way binding:

 

Component B is changed to refer to:
```

<componenta [(someInput)]=”myValue”>

```

This means it expects changes to myValue to be reflected in ComponentA and it expects changes to someInput to end up in myValue.

 

For that I need to define an output:

 

And my setter has to change to trigger the emitter. So:
private _someInput:string = 'a default value';

@Input()
set someInput(v:value) {

  If(this._someInput === v) return;

  this._someInput = v;

   this.Refresh();

  this.someInputChange.emit(this.someInput);

}

get someInput():string {

  return this._someInput;

}

@Output() someInputChange = new EventEmitter<string>();

 

Notes:

*	The setter has a check to only proceed if there was a change to prevent infinite event loops during the two-way binding.
*	The emitter has been added to notify the two-way binding that there was a change.
*	someInputChange is the actual output, but I don’t necessarily need to see that in my script at coding time as long as it is there after transpilation.
*	Because someInputChange has Change afterward the IDEs know that [(someInput)] is valid.

 

Now that we all see how I understand angular to work …

 

What was I asking for?

 

Ultimately, all I really wanted was a one or two way bindable input variable and the ability to know that it changed so that I can trigger a refresh in my OnPush based component.

 

I don’t want to have to write the same 12 lines of code for a relatively simple operation.

As I see it,  either I will want:

*	an Input with no binding
*	an input with one way binding
*	or an input with two way binding.

 

No-binding, for me anyway, requires nothing new.

 

One-way requires something like the @OnPushInput syntax I was proposing.

```

private _someInput:string = 'a default value';

@OnPushInput( { saveAs: '_someInput', onUpdate: ()=>{ this.Refresh();} });

```

Two-way binding:

```

@OnPushIO( { saveAs: '_someInput', onUpdate: ()=>{ this.Refresh();} });

``` 

Where for IO it sets up someInputChange as an output and the IDE and angular in general know that [(someInput)] is valid. 

 

And where the setter and getter gets defined and the setter will only proceed if the value actually changed and will emit the change event and call onUpdate so I can do my custom thing.

 

And where the parameters passed in are:

*	saveAs, the name of the variable to store values in. If not provided would default to the input variable name with an underscore in front.

*	It would probably be like @Input which gets flagged as a potential issue if defined like @Input(‘someCoolInput) inp:string; Because someCoolInput is not the same as inp. 
*	If the saveAs variable isn’t the name of the input variable name with an _ then it might be reasonable to raise an issue, but it should be possible to do.

*	If not defined it could be programmatically added during transpilation or whatever process @Input currently uses.
*	onUpdate is a developer provided handle, !not a f**g Promise!, that is called if provided when the binding triggers a set. 

 

I should also point out that I want the current functionality to be left alone because if I need more control over the binding process being able to create a more interesting setter and/or getter(s) etc is something I want to be able to do. I just don’t want to do it for the common basic use case.

 

Naming convention is just a suggestion.

 

The names @OnPushInput and @OnPushIO are a recognition that is a problem when using the OnPush change detection strategy. The naming differentiates from normal Input and Output while aiming to providing similar abilities.

 

If you want to just support this kind of functionality for normal @Input and @Output that is fine with me. You can call it whatever you want as long as it makes sense and doesn’t require a developer to rewrite essentially the same 12 lines of code with a different variable name for something simple. I’m fine with those 12 lines being there after transpilation, but for a basic setup I would rather have a short-hand for doing it.

 

It may not seem like a big deal, but if you have even five inputs it starts getting annoying.

 

I’ve made many components using this technique and they work well and aren’t over polling for change detection. I think there must be an easier way that provides the same power without requiring the developer, most selfishly me, to type as much code. I also think this would be an excellent core ability.

**Comment by JeanMeche** [comment]
You seem to have a quite incorrect understanding of how Change detection works with OnPush. 

With OnPush, change detection is triggered : 

* When the input changes (the reference, not a change within the input object). 
* On an explicit call to `detectChanges()`
* On a `ApplicationRef.tick()` on components marked by `markedForCheck()`. `AppRef.tick` is triggered by all  api patched by zone.js for example. 

Check [this great demo](https://danielwiehl.github.io/edu-angular-change-detection/) about this.

**Comment by arthur-clifford** [comment]
I’m happy to be wrong and will confirm whether the external change triggers a change as you are saying here:

*	When the input changes (the reference, not a change within the input object).

If I understand what you are saying correctly, then if an input doesn’t require any special handling when changed , the variable can be bound to and external changes will be reflected because the external change will trigger a changeDetection. 

 

It means that the code I shared is not invalid but not necessary in simpler cases. And is only necessary if I need to do something special in a setter function.

 

Am I closer to understanding correctly?

 

If I am, this begs another question though, what does one have to do to prevent an external change from automatically triggering changeDetection for an OnPush component?

 

Would the functionality I shared be a delegated input in the sense that the setter can determine whether to do changeDetection? Or is it calling detectChanges twice when an external change happens?

 

Or, might there be a need for a @DelegatedInput for this sort of scenario? It would basically negate the automatic detectChanges when the input changes and allow the setter function to determine whether to detectChanges or not.

**Comment by mlc-mlapis** [comment]
@arthur-clifford If a component using the OnPush strategy has an input (object or array) and this input is not a primitive value (string, number, ...), the change detection is controlled by the reference of the object/array. If the reference has not been changed, the component (and all of its children) refresh is skipped (setters are not executed). It's called the immutable principle. If you need to refresh the component (run setters), you need to change the reference, like `{... object}` or `[...array]`.

It means that when you are mutating objects or arrays used for the `@Inputs`, you need to change also their references. And the opposite, if the object/array contains the same data (without mutation), but it's always created as a new object/array, you need to introduce some memorization to keep the reference the same.

**Comment by arthur-clifford** [comment]
I think I do understand that.

 

Miloš, you haven’t dismissed me completely yet, and I hope I’m not unreasonably frustrating you. This has been useful, and I think we are closer to the same page. I’m not asking for what I was originally asking for, but I’m refining what to ask for through this thread. So, please bear with me.

 

I’m assuming by “reference” you are referring to the target of the outer binding. 

Outer component template
[someInput]=”referenceVar”

 

And if  in my component I have

<span [innerHTML]=”someInput”>

 

If referenceVar changes someInput changes and the changeDetection is triggered and the template is updated with the changed value of someInput.

 

I’ve confirmed that this is true and concede I was mistaken and originally misunderstood that changeDetection happened when referenceVar changes. Thank you for the clarifications.

 

If I’ve defined a setter for someInput, it would be called when referenceVar has changed and I can do whatever with it. But either way changeDetection is called.

 

If I defined a getter it too would be called when referenceVar changes because the template referring to someInput would get its new value through the getter. I realize that may not be the exact communication flow, but from a practical perspective the template updates after a changeDetection and “gets” each bound value.

 

One tends to discover the virtue of OnPush when they use a getter with a template because non OnPush change detection calls the getter on every tick to determine if there is a change.

 

With that, if I have one input that I want to trigger changeDetection for automatically and one that I rather not have changeDetection triggered automatically for, I’m out of luck because as you have pointed out input changes trigger changeDetection.

 

So, my NEW question is, what if I want the input to set a value normally but not assume I want to initiate change detection? 

 

Put another way, I want to get the change to referenceVar in someInput but I DO NOT want changeDetection triggered in myComponent unless I trigger it.

 

I want to get the change to someOtherReferenceVar in someOtherInput and I DO want the changeDetection triggered in myComponent.

 

Is there, or how might there, be a way to:

*	configure OnPush so that it either doesn’t trigger a change detection when bound properties are set for the whole component? Which means I have to do things myself even for simple cases
*	Or on an input by input basis how might I be able to differentiate a change detection triggering input? Meaning the setter would be called but automatic changeDetection would not be triggered; thus, if I want change detection to happen I have to trigger it in the setter or through some other component activity.

**Comment by JeanMeche** [comment]
If you want to disable the automatic Change detection you'll have to call `changeDetectorRef.detach()`.  This way, you component will not be affected by change detection. This works the same with `OnPush` or `Default`.

**Comment by arthur-clifford** [comment]
How much is affected by detach?Will inputs still update when reference variables change, do input setters get called etc? Or will I get an error abouit being detached. If I detach can I still call cdr detectChanges and have my template update?Detaching sounds like I’m disabling change detection. I want to be able to receive changes to input “references”. And I want the power to be able to make my template refresh to reflect bindings.Really I just want to disable auto TRIGGERING of the  change  detection for when specific inputs are set with something ***@***.******@***.***() soneInput:string;so that when the input’s reference changes the new value is set and marked as change in my component for when I choose to trigger detection. We’re talking about continuing the evolution of change detection from default always ask,  to onpush ask after a change, to ask when I tell you to. Maybe ChangeDetectionStrategy.OnDemand?Sent from my iPhoneOn Mar 13, 2023, at 6:12 AM, Matthieu Riegler ***@***.***> wrote:﻿
If you want to disable the automatic Change detection you'll have to call changeDetectorRef.detach().  This way, you component will not be affected by change detection. This works the same with OnPush or Default.

**Comment by JeanMeche** [comment]
With `detach()` no change detection will happen outside of an explicit call to `detectChanges()`

Again, check [this demo](https://danielwiehl.github.io/edu-angular-change-detection/) to see what happens in the different cases. Everything is configurable.

**Comment by arthur-clifford** [comment]
Ok I’ll work out what’s going on with the page. And I’ll play with detach. Is it better to call detach in the constructor or in-unit?Sent from my iPhoneOn Mar 13, 2023, at 7:54 AM, Matthieu Riegler ***@***.***> wrote:﻿
With detach() no change detection will happen outside of an explicit call to detectChanges()
Again, check this demo to see what happens in the different cases. Everything is configurable.

**Comment by mlc-mlapis** [comment]
> Is it better to call detach in the constructor or ngOnInit? @arthur-clifford 

It should generally be done in the `ngOnInit` lifecycle.

I am not sure what your case is exactly, but usually, detaching is used when some performance factors are in the play to prevent frequent change detections.

Think about creating a very simple Stackblitz demonstration of your case, the simplest as possible, if you want to explain what you want to get. Actually, your solution looks over-combined in some way, and there is probably a simpler solution that uses standard Angular concepts.

**Comment by arthur-clifford** [comment]
Ok, I’ve confirmed that detach() behaves as expected for the scenario I was thinking of.

 

I would like to point a couple things out:



## Non-obviousness of the capabilities:

https://blog.angular-university.io/onpush-change-detection-how-it-works/

That page never mentions detach as a scenario.

 

I’m confident y’all have thought through more than I have on changeDetection and I’m happy to see these scenarios are considered.

 

The link you keep sending me is interesting, and I’m sure it demonstrates everything we’ve talked about, but it is too your-perspective, with your knowledge, and not the perspective of somebody try to write code.

 

## Detach’s description does not obviously state what it does for me as a developer: 

I would argue that as a developer I would not have looked to detach as a way to accomplish what I wanted. The description in my IDE for detach:



“Detaches this view from the change-detection tree. A detached view is not checked until it is reattached. Use in combination with detectChanges() to implement local change detection checks.

 

Detached views are not checked during change detection runs until they are re-attached, even if they are marked as dirty.”

 

Having been through this thread with you I understand what it is saying. But the average person taking on Angular will not necessarily find that information obvious or useful.

 

The first paragraph is confusing because I would have expected to have to reattach the detector to use detectChanges and I wouldn’t be sure what I’m getting into with constantly attaching and detaching the detector.  



## Same Stuff Different Definition

 

Please consider:
ChangeDetectionStrategy.OnDemand

 

It would basically be OnPush except that when the component is being setup prior to calling the OnInit or OnAfterViewInit lifecycle hooks, a component starting up with this changeDetectionStrategy would call detach on the ChangeDetectorReference for the component, such that if the component has the cdr injected it will already be detached.

 

The advantages over detach in onInit is that it is more declarative, its name is more developer-relative,  and makes it clear what will or won’t happen in the component without having to dig through the component code.

 

ChangeDetectionStrategy.OnDemand

Would be defined as:

An implementation of change detection where updates to the component’s template will not reflect the model until detectChanges is explicitly called. (see detectChanges).

 

 

## OnPush attached changeDetection with exceptions

 

Consider:

@OnDemandInput() someInput:string;

 

This could be used with OnPush to indicate an input-specific detach.

Presumably that would be like asking for  an ability to call cdr.detach(‘inputX’)

 

Except I don’t want to have to do that, I’d rather tag my input as OnDemand and have the fact it is detached close to the input definition rather than in an init function.


And then having the changeDetection tech know not to automatically call detectChanges for that one input. So that for OnPush I can have:

 

@OnDemandInput() someInput:string;

@Input() someOtherInput:string;

 

I could bind to both in a template and changes to the reference for someOtherInput would trigger a change detection, but changes to someInput’s reference would not.

 

In this scenario, I do not want a component-wide detach.

 

Is this clearer?

**Comment by mlc-mlapis** [comment]
@arthur-clifford Without demonstrating your concrete case, it's hard to consider your suggestion. Theoretically, you can discuss everything, but in reality, you must have real arguments for such a new feature.

BTW: With new features coming together with Signals, it seems there will also be new ways around more selective CDs (even without zone.js).

**Comment by pkozlowski-opensource** [comment]
There is lots going on in this thread, most of it being focused on getting to the same, shared understanding of the change detection inner working. 

As @mlc-mlapis pointed out, we are working on the major review / changes to the change detection model based on signals. The change detection should become more granular and predictable.

I'm going to close this issue as I don't see anything immediately actionable here and we are working on the bigger changes already. Stay tuned for the RFC!

**Comment by arthur-clifford** [comment]
I understand.

 

But I want to go on record as saying that it felt from my end that there was little evidence of an attempt to actually read or even try to understand my evolving request. Because if there was, by the end I clearly stated I wanted. Since the ability already exists all I was asking for was a different way to declare it, I shouldn’t have to prove a use case you already figured out in order to ask for an easier way to implement it. 

 

Whatever new thing  you build I hope you will consider that as a developer-user it is more useful to have functionality  named based on what it accomplishes rather than what it does. Like the right pedal in a car is the accelerator not the gas pedal. Pressing it achieves making the car go faster, nobody cares how acceleration is being done, they want to make the car go faster; and in an all electric car it is has nothing to do with gas.

**Comment by mlc-mlapis** [comment]
@arthur-clifford I think you are right only partly. If suggesting a new feature/syntax, you need a very strong argumentation to differentiate it from an exception that is rarely used. And that's the area where you still need to show a clear and concrete demonstration of a real case. As I said before, in such a situation, a simple working example is worth of hundred words. The Angular team always considers a lot whether the proposed functionality is so important that it should be included in the core.
