### ISSUE TITLE
Missing Bazel Documentation

### ISSUE THREAD

**Issue by zachary-svoboda-accesso** [angular/angular#49417]
### Describe the problem that you experienced

[@angular/bazel](https://www.npmjs.com/package/@angular/bazel) does not appear to be documented on angular.io, the closest I've found is [a mention about the builder's deprecation](https://angular.io/guide/deprecations#bazel-builder-and-schematics).

I believe it would be helpful to share the use and purpose or at least the status of this package. It seems it [may be deprecated](https://github.com/angular/angular/pull/37190) which seems accurate according to [this announcement](https://dev.to/bazel/angular-bazel-leaving-angular-labs-51ja).

### Describe what you were looking for in the documentation

Information on the use of `@angular/bazel`

**Comment by alan-agius4** [comment]
Bazel builder and schematics have been from `@angular/bazel` removed and no longer supported. 

`@angular/bazel` mostly contains legacy rules that are needed to build other angular repositories.

The mentioned package is no longer meant to be used by 3rd parties.

**Comment by zachary-svoboda-accesso** [comment]
Thank you very much for your quick reply! I feel that if the [above article](https://dev.to/bazel/angular-bazel-leaving-angular-labs-51ja) is still accurate it would be a valuable to include some cursory guidance in the Angular docs about this alternative build solution.

**Comment by alan-agius4** [comment]
That article was accurate 2 years ago.

That said, the only official supported way to build an Angular application is using the Angular CLI as such I don’t think it should be included in the docs.

**Comment by pkozlowski-opensource** [comment]
Going to close this issue since, as @alan-agius4 pointed out, @angular/bazel was removed and no longer supported.
