### ISSUE TITLE
Public API for setting DOM adapter

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#4942]
Currently there are several places where we need to set a DOM adapter (server-side rendering, web-worker, testing) and we don't have public API for this. What is done today is some variant of:

```javascript
System.import('angular2/src/core/dom/browser_adapter').then(function(browser_adapter) {
  browser_adapter.BrowserDomAdapter.makeCurrent();
})
```

We need to decide upon public API for selecting platform-specific DOM adapter

**Comment by pkozlowski-opensource** [comment]
//cc: @IgorMinar

**Comment by tbosch** [comment]
Eventually, we won't need DomAdapters any more:

1. for parsing, we use our custom html parser which does not need the DOM
at all
2. we should have special renderers for every platform (browser,
serverside, ...)

**Comment by JohannesHoppe** [comment]
FYI

since alpha-47 the
`angular2/src/core/dom/browser_adapter` is now located at
`angular2/src/platform/browser/browser_adapter`

**Comment by pkozlowski-opensource** [comment]
I don't even remember what this one was about and why I've even opened this, so closing for now.

**Comment by cexbrayat** [comment]
@pkozlowski-opensource We have to use this for testing purpose, maybe the idea was to have a cleaner API for this?

**Comment by JohannesHoppe** [comment]
Yes, exactly. Is `browser_adapter.BrowserDomAdapter.makeCurrent();` really the supposed public API?

**Comment by IgorMinar** [comment]
In the past the BrowserDomAdapter was a private api but that got fixed
during the barrel reorganization.
