### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<' after deployment  when user reloads the screen. 

### ISSUE THREAD

**Issue by Shabeena-majeed** [angular/angular#49426]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

My app is working fine locally. When backend engineer uploads build on server it throws an error, "Uncaught SyntaxError: Unexpected token '<'" and UI turns into a blank screen. Now, I'm not sure if this is a front end issue or backend issue.

### Please provide the exception or error you saw

```true
Uncaught SyntaxError: Unexpected token '<'
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"dependencies": {
    "@angular/animations": "^12.2.10",
    "@angular/cdk": "^13.0.3",
    "@angular/common": "^12.2.10",
    "@angular/compiler": "^12.2.10",
    "@angular/core": "^12.2.10",
    "@angular/forms": "^12.2.10",
    "@angular/localize": "^12.2.10",
    "@angular/platform-browser": "^12.2.10",
    "@angular/platform-browser-dynamic": "^12.2.10",
    "@angular/router": "^12.2.10",
    "@ng-bootstrap/ng-bootstrap": "^10.0.0",
    "alasql": "^1.7.3",
    "angular-timezone-selector": "^1.2.1",
    "axios": "^0.23.0",
    "bootstrap": "^4.6.1",
    "chokidar": "^3.5.2",
    "faker": "^5.5.3",
    "file-saver": "^2.0.5",
    "jspdf": "^2.4.0",
    "jspdf-autotable": "^3.5.23",
    "jszip": "^3.7.1",
    "meow": "^11.0.0",
    "moment-timezone": "^0.5.38",
    "ng-pick-datetime": "^7.0.0",
    "ng-recaptcha": "^9.0.0",
    "ngx-bootstrap": "^7.1.0",
    "ngx-infinite-scroll": "^13.0.2",
    "ngx-pagination": "^5.1.1",
    "or": "^0.2.0",
    "popper.js": "^1.16.1",
    "rxjs": "^7.4.0",
    "trim-newlines": "^4.0.2",
    "tslib": "^2.4.1",
    "xlsx": "^0.18.5",
    "zone.js": "^0.11.4"
  }
```

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
