### ISSUE TITLE
Functional Components

### ISSUE THREAD

**Issue by jonathandewitt-dev** [angular/angular#49431]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

So, it is with little controversy and _good intent_ that I start with the biggest business-related reason a change like this should be considered. Angular is not doing so hot on the StackOverflow annual surveys, coming in as the "most dreaded" framework for 3 years in a row and counting. A glance at the npm stats is eye-opening.

![image](https://user-images.githubusercontent.com/55965128/225167579-63b22951-a718-41e1-b9ea-04a3fc476a78.png)

I think this is actually a shame, as Google hires brilliant people and leads the world's internet in almost every other way. I think the Angular team could really benefit from considering changes that would earn some reputation among the developers who are clamoring for a better DX. With the introduction of signals, you've already started seeing some positive light shone on the framework among both the common community and the influential voices in it. Let's capitalize on that while we have the momentum!

The popular trend is moving toward simplified code with less boilerplate, and functional components have been a great way to achieve that. React is the obvious example here, despite some criticisms of its hooks. Vue3 came next with its setup scripts, dramatically reducing its boilerplate. And now we're in a new era of front end frameworks, where Solid is making its debut with functional components that only run once, while subsequent renders are centered around signals.

Angular brings a unique perspective to development that may be overlooked and undervalued, specifically because people don't look long enough to see it. Some of its notable strengths are _prescribed architecture_, _resilience to bugs_, and its _powerful CLI_. Let's see if we can get away with sprinkling a little bit of DX without sacrificing any of that! I think functional components would be a very interesting place to start.

### Proposed solution

The following demonstrates one possible idea for how this could be implemented in Angular. Please keep in mind, this is very raw and unrefined - the primary purpose of the feature request is to get some feedback and discussion brewing in both the Angular team and the greater dev community.

Another note just for transparency, I'm out of practice when it comes to Angular, so a lot of my experience may be more reflective of what I'm used to seeing in React/Next and Vue/Nuxt. If this discussion gains traction, I will be more than happy to refresh myself on the more advanced usage and contribute any way I can.

```ts
import { setupComponent, signal } from '@angular/core';
import { HeroService } from '../../services/hero.service';

export const define = setupComponent({
  selector: 'app-hero-list',
  inject: { heroService: HeroService },
});

const HeroListComponent = ({
  ngInput,
  ngOutput,
  ngComponent,
  heroService,
}) => {

  // I/O
  const title = ngInput<string>('Hero List'); // defines an Input (prop)
  const onSelect = ngOutput<Hero>(); // defines an EventEmitter

  // component state
  const heroes = signal<Hero[]>([]);
  const selectedHero = signal<Hero | null>(null);
  const selectHero = (hero: Hero) => {
    selectedHero.set(hero);
    onSelect.emit(hero);
  };

  // fetch data
  heroService.fetchHeroes().subscribe((resultHeroes: Hero[]) => {
    heroes.set(resultHeroes);
  });

  // provide values to the template and return it
  //  *notes:
  //    - this could be made simpler with JSX or even lit-html, if we forego the Angular templating.
  //    - you could potentially use `templateUrl` here too.
  return ngComponent({
    provide: { title, heroes, selectHero, selectedHero },
    template: `
      <h2>{{ title }}</h2>

      <p><em>Select a hero from the list to see details.</em></p>
      <ul>
        <li *ngFor="let hero of heroes()">
          <button type="button" (click)="selectHero(hero)">
            {{ hero.name }}
          </button>
        </li>
      </ul>

      <app-hero-detail *ngIf="selectedHero()" [hero]="selectedHero()"></app-hero-detail>
    `,
  });

};

export default HeroListComponent;
```

This part could happen under the hood, but it could be important for testing's sake:
```ts
import HeroListComponent, { define } from 'heroList.component';
define(HeroListComponent);
```

I think the code more or less speaks for itself, but here are some things to note:

- The `define` exported function would be replaceable with a mock version, which would inject mock dependencies like that HeroService.
- This component function would be run once like Solid, not repeatedly like React.
- Notice all dependencies are destructured from the params instead of being imported directly. This is intentional, because such a pattern tends to be slightly easier to test.
- Opting out of decorators like this may be more attractive to conscientious devs who don't like the idea of supporting a [non-standard feature](https://github.com/tc39/proposal-decorators) using compiler magic to force it to work across platforms.
- You may even consider supporting JSX here... but on the other side of things, I imagine `templateUrl: './heroList.component.html'` could be an option to maintain the separation as well. Worth noting, I don't think a lot of modern developers value markup separation at this point, because the [concerns are separated differently these days](https://levelup.gitconnected.com/modern-day-separation-of-concerns-74e79ff87767). It does seem to be something that many Angular advocates seem to like, though, so it's a matter of balancing your existing users against appealing to new users.

### Alternatives considered

I don't know how applicable alternatives are in this circumstance, but I suppose the core issue is DX. I do have a laundry list of other items that could make DX a little friendlier.

- Add support for [HOCs](https://reactjs.org/docs/higher-order-components.html)
- Add support for [fallthrough attributes](https://vuejs.org/guide/components/attrs.html)
- Give more control over the root element, for example, with CSS `:host`
- Simplify state management - see [Pinia](https://pinia.vuejs.org/), [MobX](https://mobx.js.org/)
- First class support for [context](https://reactjs.org/docs/context.html)
- Services could be more functional also

With enough discussion, it may warrant opening new issues for any/all of these bullet points...

**Comment by jonathandewitt-dev** [comment]
Worth mentioning, I'm not happy with my own proposed syntax and I'll be revisiting it soon. But im the meantime, please feel free to make suggestions. Remember, the point is functional components in Angular. ;)

**Comment by pkozlowski-opensource** [comment]
Thnx for sharing @jonathandewitt-dev , appreciate it a lot. You will be delighted to hear that we are actively digging into authoring format updates and would be communicating in more details later this year. Many of your suggestions are on a table.
