### ISSUE TITLE
errorOnUnknownElements does not work in combination with ngIf

### ISSUE THREAD

**Issue by demike** [angular/angular#49432]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Test Setup karma / jasmine with NX

if a template looks like

```
...
<my-unknown-component></my-unknown-component>
...
```

the test environment option `errorOnUnknownElements` behaves as expected and fails the test(s) where this component is created.

But if an ngIf is involved and the unknown element in the template is instantiated in some later point in time:

```
...
<my-unknown-component *ngIf="someCondition"></my-unknown-component>
...
```

the error is just logged into console but the Tests do not fail!

This might also be an issue with `errorOnUnknownProperties`

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.5.4
```

**Comment by JoostK** [comment]
`errorOnUnknownElements` is a runtime-only flag, so it is only considered when the template is actually rendered. If `someCondition` is never `true` then you'll never see the error.

**Comment by demike** [comment]
@JoostK 
`someCondition` gets true, and at that point the error gets logged to console, **but** it does not fail the test

**Comment by demike** [comment]
Seams that it was a problem with the test.
The test is finished before the error happens.
Maybe some missing `await` like in this example:

https://stackblitz.com/edit/angularunit-testing-ubbqkc?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fdashboard%2Fdashboard.component.spec.ts%3AL84

the console shows the error but the test is ok
==> enable await to see the test failing
