### ISSUE TITLE
refactor(Location): move out of router package and into platform/browser

### ISSUE THREAD

**Issue by NathanWalker** [angular/angular#4943]
### Summary

Discussion here https://github.com/angular/angular/pull/4905 has brought to light that it would be beneficial for `Location` to exist on it's own and not dependent on the `router` bundle.

### Problem

Users will need to access url query params whether they are using the component router or not.
Sample user story:

> Manager needs a quick form posted on an isolated marketing page that is all on a single page with no routes.
> Developer wants to build the form using Angular2 and plans to process various flows via url query params used across several different links that are emailed via a marketing campaign.
> Developer only wants to use the core bundle as there will be no routes on this page and needs to access the query params easily for various usability/marketing tracking purposes.

### Proposal

Make `Location` a part of `core`. Or any other module that would be included with the main bundle. Thoughts? I can begin working on this in next day.

/cc @mhevery @btford

**Comment by btford** [comment]
I think this is good, but hold off before implementing anything, there are a few major refactors we need to wrap up.

This is the only reason I was hesitant in the other thread– it's not yet pragmatic to make this change until #3563 lands. @matsko and I will pair on that next week, and then if you're eager to help, I'd be happy to guide you through helping out with this.

Thanks!

**Comment by NathanWalker** [comment]
Sounds good @btford I'd love to help, lemme know. If anything else comes up in the `community-help` realm that is falling behind and no one else can get to it, feel free to assign me anything in meantime to assist further.

I'm starting to feel like it's hard to grab just anything from `community-help` due to what I just ran into with https://github.com/angular/angular/issues/4824

**Comment by btford** [comment]
@NathanWalker please don't be discouraged. The problem with #4824 was that Misko tagged it without knowing much about the context. It was a mistake on our part.

Once we have the right organization, we'll definitely need something like #4824 for using a location service without the router.

**Comment by NathanWalker** [comment]
@btford no worries :) In meantime, for my own prowess I was going to at least try and make the build pass on the changes, lol. 

Seems like last hang up is when Dart tries to run the tests I added. 
I notice that if I reference the object like:
```
var result = {key:"value"};
expect(location.search()).toEqual(result);
```
Then Dart tests pass however that of course isn't required for the js tests to pass so I left them like:
```
expect(location.search()).toEqual({key:"value"});
```
Just curious why this is and how best to resolve the remaining issues for the build with tests to pass on Travis:
Stuff like this:
```
dist/dart/angular2:[ERROR] 1 required argument(s) expected, but 0 found (/home/travis/build/angular/angular/dist/dart/angular2/test/router/location_spec.dart, line 97, col 40)
      expect(location.search()).toEqual(key: "value");
                                        ^^^^^^^^^^^^^^
```

**Comment by NathanWalker** [comment]
@btford Following up on some things and last thing I wanted to also ping you about here. If things are close to handling this refactor, I'd be interested in tackling this over next 2-3 weeks.

**Comment by norbertes** [comment]
:+1:

**Comment by NathanWalker** [comment]
It's unfortunate this wasn't given a green light sooner as this change will likely affect many at this point (not to mention plugins that may use `Location` currently); was hoping to have tackled many months before now. This is important enough to me (and my company's current Angular 2 conversion) that I would be willing to dig in to help this refactor *before* ng-conf and before any *final* release.

Looking forward to hearing from a core team member on this.

**Comment by mhevery** [comment]
@NathanWalker A PR would be most welcome!

**Comment by NathanWalker** [comment]
I'll start a branch on the refactor tomorrow. Thanks @mhevery.

**Comment by NathanWalker** [comment]
@mhevery 2 Refactor options exist here now:
https://github.com/angular/angular/pull/7962
