### ISSUE TITLE
Support URL fragment links (like Angular 1's $anchorScroll)

### ISSUE THREAD

**Issue by srawlins** [angular/angular#4944]
Angular 1 had a great service component, [$anchorScroll](https://docs.angularjs.org/api/ng/service/$anchorScroll). We should have something analogous in Angular 2.

The HTML 5 Spec has a section on [Navigating to a Fragment Identifier](http://www.w3.org/html/wg/drafts/html/master/browsers.html#scroll-to-fragid).

**Comment by eplatzek** [comment]
Hello.
This functionality is exactly what I need. Could you please update the status of this issue?

**Comment by bbottema** [comment]
We need this functionality to jump to anchors within a routed view.

**Comment by hartjus** [comment]
+1 for correcting this issue, we really need this functionality!

Are there any alternatives available until the anchorScroll has been implemented?

**Comment by bensgroi** [comment]
@hartjus There's [ng2-page-scroll](https://github.com/Nolanus/ng2-page-scroll), which covers similar territory.

**Comment by vicb** [comment]
related to the former router

**Comment by SteamWind** [comment]
I though this could be fixed in days as described by the tag:
https://github.com/angular/angular/labels/effort2%3A%20medium%20%28days%29
