### ISSUE TITLE
Project initialisation from quick-start guide.

### ISSUE THREAD

**Issue by RKeyIT** [angular/angular#49443]
### Quick-start guide contains old command in a 2 part.

**2. Create a new Angular app.**

 a. Create or navigate to the directory into which you want to create your Angular app.
 b. Run this command to create your new Angular app.
 `npm init @angular myApp`
 When prompted to make a choice, press Enter to accept the default option. This creates a new Angular app in the myApp directory.

**Instead of**:
`ng new angular-tutorial`

### Enter the URL of the topic with the problem

https://angular.io/quick-start

### Describe what you were looking for in the documentation

`ng new angular-tutorial`

### Describe the actions that led you to experience the problem

Angular learning =)

### Add a screenshot if that helps illustrate the problem

![Скриншот 16-03-2023 122148](https://user-images.githubusercontent.com/99531948/225602464-d2735af5-e01f-474c-8633-a3a0a5541619.jpg)

**Comment by alan-agius4** [comment]
The above command is correct. Which NPM version are you using?

**Comment by alan-agius4** [comment]
`npm init @angular myApp` is not an old command. It's just a different way to create an Angular application without needed to install Angular CLI globally. 

`npm init @angular myApp` calls `ng new angular-tutorial` under the hood for you.

**Comment by RKeyIT** [comment]
> npm init @angular myApp

This is my console logs after trying this commands in null project

PS E:\IT\GitHub\sdfsdfds> npm init @angular .
npm ERR! code EUNSUPPORTED
npm ERR! Unrecognized initializer: .
npm ERR! For more package binary executing power check out `npx`:
npm ERR! https://docs.npmjs.com/cli/commands/npx

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Администратор\AppData\Local\npm-cache\_logs\2023-03-17T15_57_40_263Z-debug-0.log
PS E:\IT\GitHub\sdfsdfds> npm init @angular myApp
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/create-myApp - Not found
npm ERR! 404  'create-myApp@*' is not in this registry.
npm ERR! 404 This package name is not valid, because
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Администратор\AppData\Local\npm-cache\_logs\2023-03-17T15_57_55_484Z-debug-0.log
PS E:\IT\GitHub\sdfsdfds> npm init @angular myapp
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/create-myapp - Not found
npm ERR! 404
npm ERR! 404  'create-myapp@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Администратор\AppData\Local\npm-cache\_logs\2023-03-17T15_58_40_304Z-debug-0.log
PS E:\IT\GitHub\sdfsdfds> 

It's just didn't work

**Comment by alan-agius4** [comment]
@RKeyIT if you are using NPM 9 make sure you are on the latest version.

**Comment by RKeyIT** [comment]
> @RKeyIT if you are using NPM 9 make sure you are on the latest version.

Sure, I have 9.5.0 version. Is in it trouble? I can't find options to update this version(
Is it means that peoples can have same troubles with this command? Maybe better way to use ng command? This way Angular novices musts from start use ng cli (without same bugs)?

**Comment by RKeyIT** [comment]
> @RKeyIT if you are using NPM 9 make sure you are on the latest version.

after commands
npm update -g npm 
and
npm i -g npm
I donwload something, but it isn't change my version 9.5.0 to last 9.6.2
