### ISSUE TITLE
Import component, directive or a pipe from template

### ISSUE THREAD

**Issue by Akxe** [angular/angular#49470]
### Which @angular/* package(s) are relevant/related to the feature request?

language-service

### Description

It would be great if Angular could provide a hint a given component (or the other options) is missing and would allow to import it into the module.

### Proposed solution

- [x] 1. When an unrecognized selector or pipe is used
- [x] 2. Angular language service will show an error that the part is missing and that it should be fixed
- [ ] 3. If the selector or pipe is recognized somewhere in the codebase
- [ ] 4. Propose the user with quick fixes (should probably also consider adding the hint into the compiler error)
- [ ] 5. Accepting the quick fix would import the Component, Directive or Pipe into the containing module/standalone imports

### Alternatives considered

Do it manually

**Comment by JoostK** [comment]
This is being tracked in #47737.
