### ISSUE TITLE
Code for exponential in "Practical Observable Usage" uses deprecated rxjs function retryWhen()

### ISSUE THREAD

**Issue by tpischke** [angular/angular#49489]
### Describe the problem that you experienced

The code works fine but results in warnings from static analyzers that discourage the use of deprecated - for good reasons

### Enter the URL of the topic with the problem

https://angular.io/guide/practical-observable-usage

### Describe what you were looking for in the documentation

A simple example of an exponential backoff using non-deprecated code.

### Describe what you want to experience that would fix the problem

Fix will be submitted as PR

**Comment by tpischke** [comment]
working on fix

**Comment by JeanMeche** [comment]
@pkozlowski-opensource  This issue can be closed 👍
