### ISSUE TITLE
URLSearchParams should properly escape keys and values in .toString()

### ISSUE THREAD

**Issue by flyingmutant** [angular/angular#4948]
Right now this is [not the case](https://github.com/angular/angular/blob/master/modules/angular2/src/http/url_search_params.ts#L130), so clients must escape the query manually, which defeats one of the purposes of using `URLSearchParams`.

**Comment by dfsq** [comment]
Does it make sense to simply port [encodeUriQuery](https://github.com/angular/angular.js/blob/f0f6da304c11d0bafcdb962f8ba69cfb719bc243/src/ngResource/resource.js#L457) function from Angular 1.x?

**Comment by mlaval** [comment]
They are now properly escaped: https://github.com/angular/angular/blob/master/modules/%40angular/http/src/url_search_params.ts#L173-L181
