### ISSUE TITLE
CSS   routerLink   fail

### ISSUE THREAD

**Issue by zqzy** [angular/angular#49481]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

Yes

### Description

Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 MQQBrowser/13.7.1 Mobile/15E148 Safari/604.1 QBWebViewUA/2 QBWebViewType/1 WKType/1

### Please provide a link to a minimal reproduction of the bug

angular.io

### Please provide the exception or error you saw

```true
IOS QQ broser fail
```

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
