### ISSUE TITLE
ChunkLoadErrors can occur due to HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by bryanrideshark** [angular/angular#49516]
> If a user is on our website during deployment and they navigate to a lazy loaded feature of the app they get a ChunkLoadError. After refreshing the page everything works fine. Like @karptonite said I'm assuming it's because the module name has changed on the server. 
>
> Is there any way to resolve this issue? We know that we could use the preloadAllModules feature but figured that kinda defeats the purpose of lazy loading.

_Originally posted by @skcarnes in https://github.com/angular/angular/issues/44780#issuecomment-1021577113_
            

We have the same issue, but this time I can reproduce it. If you run on a Windows Server, or another server that engages in the HTTP2_PROTOCOL_ERROR due to bandwidth warnings being tripped; Essentially, if the server detects there is too much outbound traffic, it'll shut down some of those requests without much warning.

To reproduce the error, you could add a setting to the angular-cli or other server which would be flaky intentionally with responses.

What can we do to resolve this? It seems the only thing to do is to reload the app.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
