### ISSUE TITLE
Blank screen on Angular 13 app using Samsung Tizen Web Browser

### ISSUE THREAD

**Issue by JoelAzevedo** [angular/angular#49521]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Previously, my Angular application worked on Samsung Tizen Web Browser when it was running on Angular 12 or lower. However, after updating to Angular 13, the application only shows a blank screen when launched. Despite this, the app still functions in the background, as I am able to send events to it, and it responds accordingly. My app is being run on a KM24A Samsung Kiosk with Tizen OS, which is using the browser to access my application.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.10
Node: 14.20.1
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 13.3.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1303.10
@angular-devkit/build-angular      13.3.10
@angular-devkit/core               13.3.10
@angular-devkit/schematics         13.3.10
@angular/cdk                       13.3.9
@angular/cli                       13.3.10
@angular/flex-layout               13.0.0-beta.38
@angular/material                  13.3.9
@angular/material-moment-adapter   13.3.9
@schematics/angular                13.3.10
rxjs                               7.8.0
typescript                         4.6.4
```

**Comment by JeanMeche** [comment]
Hi, do you have any errors in the console ?

**Comment by JoelAzevedo** [comment]
> Hi, do you have any errors in the console ?

Unfortunately no. When debugging as Tizen Web Application (the Angular app is served inside via an iframe) the devtools inspector also turns blank (it showed logs on Angular <= 12)

**Comment by JoostK** [comment]
According to [the specification](https://displaysolutions.samsung.com/digital-signage/detail/1807/KM24A), the device runs Tizen 4.0 which has a browser [based on Chromium M56](https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html). Angular officially supports the latest two versions of Chrome, whereas Angular 13 was released when Chrome was at v96.

You can use Angular on older version with the appropriate polyfills and ECMAScript target, however this is an unsupported configuration.

**Comment by JoelAzevedo** [comment]
Thanks for the explanation @JoostK
