### ISSUE TITLE
"const productIdFromRoute = Number(routeParams.get('productId'));" is wrong

### ISSUE THREAD

**Issue by eltoro0815** [angular/angular#49526]
### Describe the problem that you experienced

wrong:     productId 

correct:    productID

![image](https://user-images.githubusercontent.com/18168608/226748675-5afabfcd-55a5-4072-bf88-8a104960910a.png)

### Enter the URL of the topic with the problem

https://angular.io/start/start-routing

**Comment by JeanMeche** [comment]
Hi, 

I check the example code for the routing, there is nowhere a `productID` to find. I suppose that is related to the code you wrote. 

You likely wrote 
`{ path: 'products/:productID', component: ProductDetailsComponent },` for your router config. 

The key for your `paramMap` will be the one you used in your route. So if you replace `:productID` by `:productId` you will fix the problem you had.

**Comment by atscott** [comment]
Closing, see https://github.com/angular/angular/issues/49526#issuecomment-1478759480
