### ISSUE TITLE
Is there any way to use jit components in aot compilation mode？

### ISSUE THREAD

**Issue by scarqin** [angular/angular#49532]
### Description

The scene is:
We need to JIT optimize the performance of some components, but the whole project needs to use aot for i18n

### Proposed solution

use jit components in aot compilation mode
```
   @Component({
      jit: true
    })
```

### Alternatives considered

nothing

**Comment by JeanMeche** [comment]
Hi, 

You are mixing up some concepts here, 

The AOT compilation is what you need if want top performance for your components. By doing the computation at the build and not at runtime, you will reduce the workload of the client and the size of your bundle. 

Then, while running your app, the JIT compiler of the <ins>browser</ins> (not the JIT of the <ins>angular</ins> compiler), will optimize the generated JS code at runtime

**Comment by scarqin** [comment]
@JeanMeche Thanks for u reply！
