### ISSUE TITLE
Empty alt attributes on image tags

### ISSUE THREAD

**Issue by taokakao** [angular/angular#49537]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

Empty alt attribute (alt="") is an appropriate value for an image tag. Unfortunately, it gets removed during the build.

### Proposed solution

Leaving alt="" attribute in production build.

### Alternatives considered

No alternatives in my mind.

**Comment by pkozlowski-opensource** [comment]
Going to close this issue for now as we haven't heard back. Happy to reopen if / when there is more info available.
