### ISSUE TITLE
router current navigation is null when Scroll event is emitted

### ISSUE THREAD

**Issue by FDIM** [angular/angular#49541]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

I'm upgrading from Angular v14 to v15 and bumped into this issue. `router.getCurrentNavigation()` is reported as null when `this.router.events` emits `Scroll` event.

Workaround is obvious, but still feels that this is a bug.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-6czuwm?file=src%2Fmain.ts%3AL51

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/router": "15.2.3"
```

### Anything else?

I may update stackblitz, tiny bit later to better illustrate the issue as preview is not working at the office.

**Comment by JeanMeche** [comment]
Hi, that's a change that happen with #46554. 

`router.getCurrentNavigation()` returns `null` once the navigation has ended. Here the scrollEvent is fired after the navigation has ended.

#49235 already provides a new way to access the navigation by adding `lastSuccessfulNavigation` on the Router but it will land in v16.
