### ISSUE TITLE
Preloading of nested lazy modules does not work

### ISSUE THREAD

**Issue by Eugeno** [angular/angular#49558]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

Preload only works for siblings, not children.
For example, there is a structure:
```mermaid
graph LR
pages --> b
pages --> c
b --> b-review
b --> b-detail
b-detail --> b-maintenance
b-detail --> b-additional
```
If you go to `/pages/c` you'll get only `b` preloaded. But you could have a link on `/pages/c` to `pages/b/detail/1/maintenance`. Therefore, I want to get **b-index**, **b-detail-index**, **b-detail-component**, and **b-maintenance** preloaded.

Stackblitz: https://stackblitz.com/edit/angular-uc5bt8

### Please provide a link to a minimal reproduction of the bug

https://github.com/Eugeno/a-f

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.4
Node: 16.14.0
Package Manager: npm 8.3.0
OS: win32 x64

Angular: 15.2.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.4
@angular-devkit/build-angular   15.2.4
@angular-devkit/core            15.2.4
@angular-devkit/schematics      15.2.4
@angular/cli                    15.2.4
@schematics/angular             15.2.4
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by Eugeno** [comment]
Here's a hacky solution for preloading nested lazy routes:
```typescript
const routes: Routes = [
  {
    path: '',
    component: PagesComponent,
    children: [
      /*...*/ // regular children

      // nested routes from another modules
      {
        path: 'fake',
        loadComponent: () => import('./+b/b-index/b-index.component').then((m) => m.BIndexComponent),
        canActivate: [permissionsGuard], // disallow
      },
    ],
  },
];
```

 Thanks to @stevermeister for this idea.

**Comment by atscott** [comment]
There are actually 2 issues here. On is a Router bug (which you can get around by changing `children: [...]` to `loadChildren: () => [...]` but the other in your example is that your preloading function is returning `Observable<Observable<any>>` because of the `map` returning an `Observable`.

**Comment by Eugeno** [comment]
@atscott thanks you so much for your quick response and for proposing a working solution to the issue. Much appreciated!
