### ISSUE TITLE
Request to customize the empty state for combobox in DDF

### ISSUE THREAD

**Issue by HLi-copperleaf** [angular/angular#49573]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Currently some field in DDF as required to customize the empty state, but we can't do this for now.
![image](https://user-images.githubusercontent.com/109186707/227379269-880a5ede-b98f-4357-a70f-7e0e8d2c2a6b.png)

### Proposed solution

Is possible to provide the feature to customize the empty state for combobox in DDF? Thanks!

### Alternatives considered

Sometimes inline notification or tooltip can't explain the current situation, customize empty state will be helpful.

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
