### ISSUE TITLE
guide/http misleading comment on Observable unsubscribe

### ISSUE THREAD

**Issue by r6squeegee** [angular/angular#49586]
### Describe the problem that you experienced

The documentation is slightly misleading / confusing with regards to HttpClient Observable results.

it has a note saying "You should always unsubscribe from an observable when a component is destroyed." which is generally true; however specifically for HttpClient resulting Observables, my understanding is that it is not true. 

Unless I'm horribly mistaken (along with a lot of other people...) you do not have to unsubscribe from httpClient subscribe() calls. So by putting the "you should always unscubscribe" note there, it can make people think you do need to unsubscribe from http client calls. 

### Enter the URL of the topic with the problem

https://angular.io/guide/http

### Describe what you were looking for in the documentation

I wanted precise clarity if you needed unsubscribe from http client subscribe calls or not. 

### Describe what you want to experience that would fix the problem

a specific statement saying if we need or don't need to call unsubscribe on http client requests. 

and if so, include it in the example codes.

**Comment by JoostK** [comment]
This was explicitly changed as such in #47127; the best practice _is_ to always unsubscribe when the component gets destroyed.

The primary reason is that the HTTP response may arrive _after_ the component has already been destroyed, in which case failing to unsubscribe results in incorrectly keeping a reference to a destroyed component.

Additionally, interceptors could be used to implement e.g. automatic refresh functionality, resulting in multiple responses being delivered over time.

> So by putting the "you should always unscubscribe" note there, it can make people think you do need to unsubscribe from http client calls.

This is indeed what the docs encourage you to do.

**Comment by r6squeegee** [comment]
wow that's going to add a lot of extra code to every single angular component... but ok.

**Comment by JoostK** [comment]
> > This was explicitly changed as such in #47127; the best practice _is_ to always unsubscribe when the component gets destroyed.
> 
> > 
> 
> > The primary reason is that the HTTP response may arrive _after_ the component has already been destroyed, in which case failing to unsubscribe results in incorrectly keeping a reference to a destroyed component.
> 
> > 
> 
> > Additionally, interceptors could be used to implement e.g. automatic refresh functionality, resulting in multiple responses being delivered over time.
> 
> > 
> 
> > > So by putting the "you should always unscubscribe" note there, it can make people think you do need to unsubscribe from http client calls.
> 
> > 
> 
> > This is indeed what the docs encourage you to do.
> 
> 
> 
> older days
> 
> Async pipe - You dont need to take care of subscribe/unsubscribe
> 
> 
> 
> Now
> 
> Async Pipe - ultimately as per #47127 that you should not use async pipe and unsubscribe it manually on destroy.
> 
> 
> 
> Now it seems async pipe is useless it may leak

The async pipe does unsubscribe from its observable, either when another observable is provided or when the pipe is destroyed. There is no relation between unsubscribing of HTTP response observables and using the async pipe; the async pipe will do the correct thing.

**Comment by r6squeegee** [comment]
Maybe I shouldn't have closed my issue so hastily, I'm thinking the documentation is still unclear because of all the example code it provides which doesn't do what is required.

as an example : https://angular.io/tutorial/tour-of-heroes/toh-pt6

HeroDetailComponent : hero-detail/hero-detail.component.ts

If I'm hearing this properly, all the code/example code should be amended with roughly the following :
```

   export class HeroDetailComponent implements OnInit, OnDestroy {

   ...

   hero: Hero | undefined;
   myHttpSubscriptions:Subscription[]=[];

   ...

   getHero(): void {
      const id = parseInt(this.route.snapshot.paramMap.get('id')!, 10);
      let s=this.heroService.getHero(id).subscribe(hero => this.hero = hero);
      myHttpSubscriptions.push(s);
   }

   ngOnDestroy(): void {
      for (let s of this.myHttpSubscriptions) {
         s.unsubscribe();
      }
   }
```


is that correct?

**Comment by JoostK** [comment]
That would be in line with the recommendation in https://angular.io/guide/http, indeed.

You don't need an array/for-loop though though:

```ts
 export class HeroDetailComponent implements OnInit, OnDestroy {

   // ...

   private readonly subscriptions = new Subscription();
   hero: Hero | undefined;

   // ...

   getHero(): void {
      const id = parseInt(this.route.snapshot.paramMap.get('id')!, 10);
      this.subscriptions.add(this.heroService.getHero(id).subscribe(hero => this.hero = hero));
   }

   ngOnDestroy(): void {
      this.subscriptions.unsubscribe();
   }
 }
```
