### ISSUE TITLE
Route object - pathMatch

### ISSUE THREAD

**Issue by avri87** [angular/angular#49584]
### Describe the problem that you experienced

I rade the [doc](https://angular.io/api/router/Route#matching-strategy) and also this [article](https://vsavkin.tumblr.com/post/146722301646/angular-router-empty-paths-componentless-routes) about pathMatch.

After I tested it in real, I saw something strange:

Suppose we have only these cases:
1) `RouterModule.forRoot([
      {
        path: 't',
        pathMatch: 'prefix',
        redirectTo: '/g'
      },
      {
        path: 'g',
        component: C0
      },    
    ])`

Now, try:
localhost:4200/t/t --> redirects to localhost:4200/g

**********
2) `RouterModule.forRoot([
      {
        path: 't',
        pathMatch: 'prefix',
        redirectTo: 'g' --> note, no leading slash
      },
      {
        path: 'g',
        component: C0
      },    
    ])`

Now, try:
localhost:4200/t/t --> ERROR,  Cannot match any routes. URL Segment: 't/t'

*************************

Now, I rade this part: "..... Importantly there must still be a config match for each segment of the URL....."
Which is not working ( I guess) for first case above (it should failed also, but it did not).

In second case it seems to be working?

What am I missing here?

The question here, why is the difference? 

### Enter the URL of the topic with the problem

https://angular.io/api/router/Route#matching-strategy

### Provide any additional information here in as much as detail as you can

```true
The example above is taken from a simple angular application, with this package.json:

 "@angular/animations": "^15.1.0",
        "@angular/common": "^15.1.0",
        "@angular/compiler": "^15.1.0",
        "@angular/core": "^15.1.0",
        "@angular/forms": "^15.1.0",
        "@angular/platform-browser": "^15.1.0",
        "@angular/platform-browser-dynamic": "^15.1.0",
        "@angular/router": "^15.1.0",
```

**Comment by atscott** [comment]
This is working as intended. In the first example, `/t` redirected to `/g` correctly. In the second example, `/t/t` redirects to `/g/t` which does not match anything because all segments must match. https://stackblitz.com/edit/angular-ifvqw4?file=src%2Fmain.ts
