### ISSUE TITLE
Using jsdom with angular results in blank element

### ISSUE THREAD

**Issue by pitAlex** [angular/angular#49588]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Hello,
We recently updated from 15.0.4 to 15.2.4 and we notice that is some kind of conflict with angular and jsdom. The code would be like so :
- first use jsdom to instance doompurify:
```
import jsdom  from "jsdom";
import createDOMPurify from 'dompurify';
const { JSDOM } = jsdom;
const window = new JSDOM('').window;
```
- then try to purify a value and set it "innerHTML" property of any element in angular, like :
```
this._html = <any>DOMPurify.sanitize(some_string,{})
this._renderer.setProperty(this._el.nativeElement,"innerHTML",this._html);
```
This will result in the element not having any content. If I remove jsdom things work. Something is causing a conflict here and we can't figure out where the issue is. We had to downgrade because it was a real blocker.
You don't have to use it with dompurify, simply importing "jsdom" in the same file where you do this._renderer.setProperty... makes the element be blank.

**Comment by JoostK** [comment]
This is more of a support request than a bug report, but if you could provide a reproduction with a working setup using 15.0.4 and a broken setup using 15.2.4 we might be able to investigate.

**Comment by pkozlowski-opensource** [comment]
Closing for now as we haven't heard back.
