### ISSUE TITLE
Change detection not happening with async await

### ISSUE THREAD

**Issue by lakshmi2716** [angular/angular#49581]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Dom change detection not happening with async await. 

Inside a *ngIf , i have template and i need to refer the template once i get a API response, but dom reference is not available even after changing the flag. 

Example - 1.showing a loader until API resolvers 
2. After a getting API response, setting the loader flag to false, and trying to read the div inside flag 
3. Flag value is updated but dom is not refreshed, so i dont have reference to a div inside a if condition 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/reactive-form-validation-angular-15-zgnf3n?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Findex.html,src%2Fapp%2Fapp.module.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.5
Node: 14.20.1
Package Manager: npm 6.14.17
OS: win32 x64

Angular: 15.2.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.2
@angular-devkit/build-angular   15.2.2
@angular-devkit/core            15.2.2
@angular-devkit/schematics      15.0.5
@angular/cli                    15.0.5
@schematics/angular             15.0.5
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by JoostK** [comment]
This is working as expected; you are logging `this.widget` immediately after the promise has resolved, whereas Angular would only initiate a change detection cycle after all pending microticks have been executed.

You can force a change detection cycle by awaiting _past_ the pending microticks:

```ts
    await new Promise(r => setTimeout(r))
```
