### ISSUE TITLE
Allow TrackByFunction be null/undefined

### ISSUE THREAD

**Issue by ddubrava** [angular/angular#49593]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

Imagine a complex shared table that works with different data interfaces. It accepts an array of data, configuration, and various business inputs. One of these inputs is a `trackBy` function, which is required since we have different data interfaces. However, there are cases when the default `trackBy` logic suffices and no function is needed. As a result, the `trackBy` input can either be a `TrackByFunction` or `null/undefined`. This presents a problem, as passing a `null/undefined` to `trackBy` in `ngFor` will result in an error.

Here is the reproduction
https://stackblitz.com/edit/optional-track-by

### Proposed solution

It appears that Angular already handles cases where `trackBy` is not valid and null is considered a valid value, as seen in this [code snippet](https://github.com/angular/angular/blob/main/packages/common/src/directives/ng_for_of.ts#L169).

![image](https://user-images.githubusercontent.com/22116465/227736157-4d0e7889-d932-4d17-9ce5-906fd0469c9e.png)

Under the hood, Angular assumes that `TrackByFunction` can be undefined and uses the default implementation when needed, as seen in this [code snippet](https://github.com/angular/angular/blob/main/packages/core/src/change_detection/differs/default_iterable_differ.ts#L55).

![image](https://user-images.githubusercontent.com/22116465/227735588-b4178cff-0abc-40f7-b511-f7e76a2855ce.png)

Therefore, the proposed solution is to extend `TrackByFunction` to accept `null/undefined` values.

### Alternatives considered

There are two potential solutions: assigning a default value for the input or handling the case of null/undefined in the template.

**Comment by pkozlowski-opensource** [comment]
We want to encourage usage of `trackBy` and as such don't want to make it easier to bypass it. You can always use `Object.is` as a default implementation.
