### ISSUE TITLE
Transformers create constructor stubs

### ISSUE THREAD

**Issue by mhevery** [angular/angular#496]
Create a `setupReflection` method which registers constructor stubs.

Given this source:
```
@Component(...)
class MyComponent {
  MyComponent(MyClass dep);
}

@Injectable()
class MyClass {
  MyClass(@Url String name);
}

main() {
  bootstrap(MyComponent);
}
```

generate:

```
import 'package:path/to/above/file' as file1;
import 'package:reflection/reflection.dart' show reflector;

setupReflection() {
  reflector.registerType(
    file1.MyComponent, 
    factory: (file1.MyClass dep) => new file1.MyComponent(dep),
    paramaters: const [cost [file1.MyClass]]
  );
  reflector.registerType(
    file1.MyClass, 
    factory: (String name) => new file1.MyClass(name),
    paramaters: const [cost [Url, String]]
  );
}
```

Only the types which are annotated with: `Component`, `Decorator`, `Template`, and `Inject` need to have the corresponding stubs generated.

**Comment by kegluneq** [comment]
[package:initialize][0] is designed for this situation -- it's being used for [similar things][1] in PolymerDart. We should be able to make it work here also.

[0]: https://pub.dartlang.org/packages/initialize
[1]: https://github.com/dart-lang/web-components/blob/master/lib/custom_element_proxy.dart
