### ISSUE TITLE
Router not working on Ng 1.4

### ISSUE THREAD

**Issue by tbosch** [angular/angular#4960]

**Comment by tbosch** [comment]
This blocks https://github.com/angular/angular/pull/4709

**Comment by btford** [comment]
The router is actually fine AFAIK.

See:
- https://github.com/angular/angular/pull/4709/files#r43214134
- https://github.com/angular/angular/pull/4709/files#r43214153

Please close this issue once you confirm. Thanks!

**Comment by tbosch** [comment]
You are right.
