### ISSUE TITLE
Utterly wrong docs: You are some high level clown and smoke sellers

### ISSUE THREAD

**Issue by Porkechebure** [angular/angular#49602]
### Describe the problem that you experienced

The whole documentation is wrong at the root.
For such a self proclaimed high level mature framework this is ridiculous and sad.

### Enter the URL of the topic with the problem

https://angular.io/start

### Describe what you were looking for in the documentation

What I was looking for? Well, learning angular basics maybe?

### Describe the actions that led you to experience the problem

Thw whole guide is a shit filled with tapeworms.
Don't even try to run the linked stackblitz projects (which are by the way incomplete).

Just try to copy the whole starting tutorial step by step

You will notice some disturbing novice level errors and high negligence.
Just know that the routing tutorial for novice users completely overlooks the <router-outlet></router-outlet> tag need and explanation. I tried 2 hours to run the routing tutorial not understanding what was going on and why routing wasn't working.

You realize you act at some top notch high level business framework used by the big techs around the world and you have the docs that looks like some junior school dropout wrote them?

Are you dumb in the brain core?

### Describe what you want to experience that would fix the problem

Maybe if you try to run the  code you provide in your damn carelessness compiled docs you would notice a simple thing:

THEY DON'T WORK

And maybe you would notice they don't run and that you overlooked the most basic explanations.

### Provide any additional information here in as much as detail as you can

```true
Die and bring in the grave this useless framework.
And don't even start the chore "you should be kind", "Don't talk like that we are a community trying to help etc etc"

I'm so glad AI is overtaking programming altogheter so we don't need to rely on dumbasses who can't code nor write a simple tutorial
```

**Comment by JoostK** [comment]
Hi @Porkechebure,

I'd like to ask you to be considerate in how you choose to report the issues you're experiencing with the docs and follow our [Code of Conduct](https://github.com/angular/angular/blob/main/CODE_OF_CONDUCT.md).
