### ISSUE TITLE
"in" keyword inside NgIf throws error

### ISSUE THREAD

**Issue by zetti-caletti** [angular/angular#49612]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

When using 'foo' in bla it throws an error "Can't bind to 'ngIfIn' since it isn't a known property of 'div'"

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ft5mwg?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
Can't bind to 'ngIfIn' since it isn't a known property of 'div'
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.4
Node: 16.13.0
Package Manager: npm 8.7.0
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1502.4 (cli-only)
@angular-devkit/core         15.2.4 (cli-only)
@angular-devkit/schematics   15.2.4 (cli-only)
@schematics/angular          15.2.4 (cli-only)
```

**Comment by JoostK** [comment]
This happens because the `in` keyword is not supported in Angular's expression syntax. This has been reported in #38560 and is now being tracked in #43485.
