### ISSUE TITLE
Lazy loading components without bound Inputs and Outputs

### ISSUE THREAD

**Issue by knackstedt** [angular/angular#49616]
### Which @angular/* package(s) are relevant/related to the feature request?

core, router

### Description

I am writing a massive Angular application, with over 40 huge discrete components. Given the fact that many are more than 1MB of payload that a client browser needs to download, I want to lazy load as much as possible (within reason of course)

To this end, I needed to make it simple to bind inputs and outputs between things that host lazy content and the lazy-content itself. I also wanted support for making the interface generic enough to work without having to monkey-patch any of the angular core.

Here is my proposed example lazy-loader that is thusofar stable, though I'm sure there are a number of bugs and limitations that I haven't encountered yet.

Given I have a decently stable and working implementation, I wanted to share it with the community.

### Proposed solution

Source of my loader: https://github.com/knackstedt/ngx-lazy-loader

Sample StackBlitz. 
https://stackblitz.com/edit/components-issue-vr4vv7?file=src/app/example-component.html
NOTE: I had to work around an issue with the dynamic import returning an invalid bundle, but it works as described in multiple test applications. This is _only_ an issue in Stackblitz it seems.

### Alternatives considered

I originally used a directive ontop of `<ng-template>` but this approach had multiple issues. I also considered trying to create some injection tokens, but the proposed approach is far simpler in terms of ease-of-use in my opinion.

**Comment by knackstedt** [comment]
For a full-featured sample, you can clone my experiment project
https://github.com/knackstedt/angular-experiments
Open URI to https://localhost:4200/#/LazyTest -- as an additional sample.

**Comment by alxhub** [comment]
The Angular issue tracker is meant for actionable bug reports or feature requests, not for promotion of community libraries. While we appreciate your community spirit, find somewhere else to share your code.
