### ISSUE TITLE
Error: Module not found: ERror package path ./....

### ISSUE THREAD

**Issue by LeonadoRivaldo** [angular/angular#49632]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I creating a custom library and I'm having this issue when using it,
![image](https://user-images.githubusercontent.com/5981900/228603384-dc171bfc-98f9-4596-a695-d991a74326fe.png)
this is the public API
![image](https://user-images.githubusercontent.com/5981900/228603682-f6df66b8-05a9-4d01-81d0-08443c4f46df.png)
PACKAGE json
![image](https://user-images.githubusercontent.com/5981900/228603843-fca973ba-60f2-4f0f-9d6e-474743d9450f.png)
this is the ng-package
![image](https://user-images.githubusercontent.com/5981900/228604003-0a26d244-a305-4e66-a59a-f733b59cff9e.png)

 i just need help figuring this out. Thanks

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by LeonadoRivaldo** [comment]
took the time to review, but could not help ? LOL thas awsome! :)
