### ISSUE TITLE
Angular DatePipe Bug in IPad Device

### ISSUE THREAD

**Issue by dekathomas** [angular/angular#49643]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I have a date with format `yyyy-MM-dd` (ex: 2023-01-31), in all android versions and iPhone, it runs well when I use this code

`currentDate | date: 'dd MMMM yyyy'`

But in iPad device in most versions that I have tried, it will break, and the error is the currentDate format is not valid. So I have to solve the issue by formatting the `currentDate` format to be `yyyy-MM-ddT00:00:00`.

Do you have an answer why this is happen?
Thanks in advance.

**Comment by SarthakT7** [comment]
Can you provide a stackblitz link for the issue? It would be more helpful in solving the problem.

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
