### ISSUE TITLE
Type checking signal call in templates

### ISSUE THREAD

**Issue by edbzn** [angular/angular#49657]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Let's say I omit to call a signal in the template, as we are used to with regular values.

```ts
@Component({
  template: `{{ value }}`,
})
export class AppComponent {
  value = signal('Hello World!')
}
```

No compilation error to prevent this error, resulting in an undesired string rendered to the screen: `function () { [native code] }`.

### Proposed solution

Strict type-checking of signal calls in the template would improve DX, especially for newcomers.

### Alternatives considered

No type checking.

**Comment by JeanMeche** [comment]
I drafted a PR for this. If the team is ready to include this diagnostic, I can finish working on it 👍

**Comment by eneajaho** [comment]
I was thinking what about this: 

```html
{{ mySignal | myPipeThatAcceptsSignal }}
```

How that would behave?

**Comment by JeanMeche** [comment]
> I was thinking what about this:
> 
> ```
> {{ mySignal | myPipeThatAcceptsSignal }}
> ```
> 
> How that would behave?

That's already handled by the typing. For example with a `Signal<number>` and un `Pipe.transform(number)` you'll get : 

`Argument of type 'WritableSignal<number>' is not assignable to parameter of type 'number'.`

**Comment by pkozlowski-opensource** [comment]
With #49660 merged I think that we are in a much better state. Going to close it for now, will see if people bump into other common cases.
