### ISSUE TITLE
Fully initialisation meaning clarification in ngAfterContentInit

### ISSUE THREAD

**Issue by krp12345** [angular/angular#49686]
### Describe the problem that you experienced

Unable to understand meaning of ngAfterContentInit and ngAfterContentChecked life-cycle hook description.

### Enter the URL of the topic with the problem

https://angular.io/api/core/AfterContentInit 
https://angular.io/api/core/AfterContentChecked

### Describe what you were looking for in the documentation

What does "fully initialised"  mean in AfterContentinit and "has completed checking all content" in AfterContentChecked? 

### Describe the actions that led you to experience the problem

I have fully described the issue and experiment I did in [stackoverflow](https://stackoverflow.com/questions/75914528/what-is-the-correct-contract-for-ngaftercontentinit-and-ngaftercontentchecked)
Please check link for full description.

### Describe what you want to experience that would fix the problem

Clarify the docs with profound example.

**Comment by JeanMeche** [comment]
I'll try to sum it up for you: 

`AfterContentInit` is a hook that will run only once : when the projected content is initialized. 

```typescript
@Component({
  selector: 'parent',
  standalone: true,
  template: '<ng-content></ng-content>',
})
class ParentComponent implements AfterContentInit {

  @ContentChild(ChildComponent) content:any;

  ngOnInit(): void {
    console.log('Not init yet:', this.content);
  }

  ngAfterContentInit(): void {
    console.log('content init:', this.content);
  }
}
```

`AfterContentChecked` is a hook that will run after the content has been checked (most of the time it's during a Change Detection cycle). 

```
   ngAfterContentChecked(): void {
    console.log('child val: ', this.content.val);
  }
```
See this small demo I wrote: [Stackblitz](https://stackblitz.com/edit/angular-rtkk8g?file=src%2Fmain.ts)

Maybe you could close this issue here, and we'll continue on StackOverflow, I answered there also.

**Comment by krp12345** [comment]
I added comments to your answer @JeanMeche . Will you please check?

**Comment by krp12345** [comment]
If correct input is given to me, I will raise the PR for angular docs and make docs more beautiful by adding required description:)

**Comment by krp12345** [comment]
After observing source code and playing with life-cycle hooks, I have come to come to conclusion that "content fully initialised" means "content component is ready for change detection by completing all initialisation hooks including ngDoCheck".
There should be NOTE in ngAfterContentInit stating this : "term <i> fully initialised</i> means all the initialisation hooks execution including ngDoCheck is completed and change detection has not run yet on the projected content".
Main thing is it should be clearly stated that change detection on projected content has not run yet when ngAfterContentInit is called.
Is it correct thing to add such note in the doc?
@atscott @JeanMeche
