### ISSUE TITLE
Suggestion - property name mapping to support minification of components

### ISSUE THREAD

**Issue by bryanerayner** [angular/angular#4969]
I have been thinking about how to achieve better minification in our Angular 1.x app. It has been difficult to achieve due to how templates and Angular expressions are interpreted.

For Angular 2.0, could there be an optional property in the `@Component` decorator (or perhaps another decorator, I'm not familiar with the codebase) which would map property names of components, to the names of variables in the template expressions?

**Comment by HerringtonDarkholme** [comment]
You can use [@Input('template-name')](https://angular.io/docs/ts/latest/api/core/Input-var.html). This decorator register the minified variable name to `template-name`

**Comment by pkozlowski-opensource** [comment]
Hopefully @HerringtonDarkholme answer is a sufficient one for your use-case @bryanerayner

**Comment by bryanerayner** [comment]
I think the full intent of what I was suggesting wasn't fully grasped.

Suppose this simple component:

````ts
class TemplateComponent
{
    componentImageSrc: string;
    constructor(){
       this.componentmageSrc = 'www.some.image';
    }

    onClick(){
    // do something
    }
}
````

Given a template as follows, 
````html
<div class = "TemplateComponent" (click)="onClick()">
    <img [src]="componentImageSrc">
</div>
````

and this proposed re-mapping annotation (AFAIK this doesn't exist)
````ts
templateAlias: {
    componentImageSrc: 'a',
    onClick: 'b'
}
```

the template would, when it's compiled, be converted to something looking more like this:

````html
<div class = "TemplateComponent" (click)="b()">
    <img [src]="a">
</div>
````

This would support more advanced minification of the TypeScript output. Should Typescript ever implement the proposed `nameof` operator, this would be a powerful way to minify Angular applications. It also lessens the coupling between templates, and components. Refactoring and code sharing also become easier when a mechanism like this is available.

**Comment by pkozlowski-opensource** [comment]
This indeed sounds like an interesting minification strategy, but should be rather solved on the tooling side, no? Or are you suggesting that ng2 should provide such tools?

**Comment by bryanerayner** [comment]
This would definitely be done in a build step. Minifying Typescript in a satisfactory manner would require some movement from the Typescript team, as I think that's best done in the Typescript compiler.

That said, a big problem in minification, is knowing what you can safely minify, and what you can't. Many times, property names on Angular Component classes can't be minified, because of how Angular binds the templates to these properties. But, if there was a mechanism to also minify/alias the names in the template, I think it would help bridge the gap.

Thinking about it, it might become more complicated than a run-time step, because there might be a property name like `foo.bar`. And if `foo` has been minified, and `bar` has also been minified, there would need to be a way to specify that. My proposal doesn't handle that case.

**Comment by pkozlowski-opensource** [comment]
@bryanerayner I understand what you are trying to achieve and this is very noble goal. having said this I don't think this is sth immediately actionable - sounds like a nice longer-term project though!

**Comment by bryanerayner** [comment]
Agreed.

**Comment by HerringtonDarkholme** [comment]
I think the compression level is not by default supported for most compiler, so practically users are safe to use `Input` decorator. Uglify requires a `--property_mangle` and closure compiler requires advanced mode. AFAIK, TypeScript currently does not have a clear roadmap to support [minification](https://github.com/Microsoft/TypeScript/issues/8).

Property minification needs specific knowledge about the code and the framework. I'm hoping to see further collaboration between TS and Angular team.
