### ISSUE TITLE
Tree shake constructor stubs

### ISSUE THREAD

**Issue by mhevery** [angular/angular#497]
When generating constructor stubs (see #496) the resulting hash map may contain more stubs than is needed for running the application. This will result in retaining too much code during the dart2js tree shaking phase. To correct this the transformer needs to tree shake the stubs and only output the ones which are actually needed.

1) find the [`bootstrap()`](https://github.com/angular/angular/blob/master/modules/examples/src/hello_world/index_common.js#L71) method and find the root component.
2) recursively find all injectable items from the root component
3) Include the whole set in the generated `setupReflection()` method (see #496)

Given a component definition here are the list of items which we need to recurs over recurse on. (Labeled as `Recurse#`)

```
@Component({
  selector: 'hello-app',
  componentServices: [Recurse1, Recurse2],
  lightDomServices: [Recurse3, Recurse4],
  shadowDomServices: [Recurse5, Recurse6],
  template: new TemplateConfig({
    directives: [Recurse7]
  })
})
class MyComponent {
  constructor(Recurse8);
}
```

**Comment by kegluneq** [comment]
As long as requiring the user to specify the entry point isn't a problem, this doesn't seem too different from what Angular and Polymer are doing right now. Once we have #496 this doesn't seem like it should take very long (famous last words).
