### ISSUE TITLE
Double instantiation when getting standalone components in a polymorphic way with ViewChild when they are provided with useClass

### ISSUE THREAD

**Issue by fdeslandes-wk** [angular/angular#49707]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

When exposing a component to be used in a generic way, we are able to add this in their providers array with non-standalone components:

```typescript
@Component({
  ...
  providers: [
    {
      provide: MyGenericClassOrToken,
      useClass: MySpecificComponent,
    },
  ],
})
export class MySpecificComponent {
   ...
}
```

And then access them in a parent component with
```typescript
@ViewChild(MyGenericClassOrToken) myChild?: MyGenericClassOrToken;
```

This works well with non-standalone components.  However, for standalone components, the constructor from "MySpecificComponent" is called twice, and a new instance (non linked to the View) is passed to ViewChild instead.  In that case, we must use "useExisting" instead of "useClass".

I think the behavior should be the same between standalone and non-standalone components, and failing to do so, it should be clearly documented and taken into account in migration guides from non-standalone to standalone.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-sp5iua?file=package.json

### Please provide the exception or error you saw

```true
See the console.  The constructor is called twice.  Also, when adding a "AfterViewInit" to the sub component and setting a variable in it, you can see that the component returned by @ViewChild is not bound to the html template / Angular lifecycle.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 15.2.3

Still there in 15.2.5
```

**Comment by JoostK** [comment]
I converted the StackBlitz to not use standalone components, and the behavior is still the same: https://stackblitz.com/edit/angular-chhqhy?file=src%2Fsubcomponent.ts,src%2Fmain.ts

This behavior makes sense to me, as using `useClass` _should_ instantiate a separate instance.

**Comment by fdeslandes-wk** [comment]
Hum... I did not test converting my minimal repro, but things were working in my actual code base before I switched to standalone, then needed useExisting instead of useClass.  I'll double check, maybe before the standalone components, the component was initialized twice, but the one returned to ViewChild was the right one.

**Comment by fdeslandes-wk** [comment]
Well, I guess it was a code 18 on my side and I converted the code replacing useExisting with useClass. I will close the issue.
