### ISSUE TITLE
Separate package for angular signals

### ISSUE THREAD

**Issue by btoaelbore** [angular/angular#49712]
### Description

Feature Request to separate signals from `@angular/core` like `@angular/signals`

### Proposed solution

have a separate package for signals like `@angular/signals`, this propose solution is only applicable if signals can run or can be use to other libraries outside angular or in plain vanilla javascript

### Alternatives considered

N/A

**Comment by pkozlowski-opensource** [comment]
We don't have immediate plans for doing so, we've covered our reasoning in the FAQ section of https://github.com/angular/angular/discussions/49683

> We did discuss the possibility of publishing an independent signal library but didn't do so initially for the following reasons:
> * it is still in the early stages and we don't want to publish before going through the RFC feedback and settling on the exact API shape
> * there are parts of the library that deeply integrate with the Angular internals (effects scheduling and cleanup is the most notable example)
> * there is some practical friction in publishing a new package

> We will definitely consider publishing a separate NPM package if there is value in it - please leave feedback in the RFC if you would like to see Angular signals library to be available as a separate NPM package.
