### ISSUE TITLE
Make DefaultValueAccessor directive Standalone

### ISSUE THREAD

**Issue by lukaonik** [angular/angular#49720]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

When we want to make a simple custom value accessor, according to the docs, we can use [DefualtValueAccessor](https://angular.io/api/forms/DefaultValueAccessor#using-the-default-value-accessor).

the example:

Let's suppose we have `app-my-custom-control` component

```
@Component({
  selector: 'app-my-custom-control',
  templateUrl: './my-custom-control.component.html',
  styleUrls: ['./my-custom-control.component.scss'],
})
export class MyCustomControlComponent implements OnInit {
  constructor(private ngControl: NgControl) {}
  ngOnInit(): void {
   //testing code
    this.ngControl.valueChanges?.subscribe((data) => {
      console.log(data);
    });
  }
} 
```
We can use app-my-custom-control as Value Accessor One if we add `ngDefaultControl` directive. 

```
@Component({
  selector: 'app-default-custom-control',
  styleUrls: ['./default-custom-control.component.scss'],
  template: `
    <app-my-custom-control
      [(ngModel)]="value"
      ngDefaultControl
    ></app-my-custom-control>
  `,
})
export class DefaultCustomControlComponent implements OnInit {
  value = '2';

  ngOnInit(): void {
    setInterval(() => {
      this.value = new Date().toString();
    }, 3000);
  }
}

```

Which works fine. But we have to add `ngDefaultControl` in all the places we use it.

to avoid duplication, we can add `DefaultValueAccessor` directive in `hostDirectives` property like this:
```

@Component({
  selector: 'app-my-custom-control',
  templateUrl: './my-custom-control.component.html',
  styleUrls: ['./my-custom-control.component.scss'],
  hostDirectives: [DefaultValueAccessor],
})
```

Unfortunately, we can't do this because `DefaultValueAccessor` is not standalone, 

So the proposal is to make it standalone.

### Proposed solution

The proposed solution is to make `DefaultValueAccessor` directive standalone to be able to put it in `hostDirective` property

### Alternatives considered

I don't see any alternative besides that use it as it is right now

**Comment by JeanMeche** [comment]
Hi, there is already an open issue on this : #48607
