### ISSUE TITLE
Setting singals in ngOnChanges cause error when multiple updates happens in one view

### ISSUE THREAD

**Issue by kbrilla** [angular/angular#49721]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

If the signal is set in the ngOnChanges as suggested and implemented by @pkozlowski-opensource we get incorrect result
here original link
https://t.co/wxRaepiLjO
my modified to illustrate more:
https://stackblitz.com/edit/angular-jjhdfj?file=src/main.ts
```
    {
  "id": 1
}
  
    {
  "id": 5
}
  ```

when it should be 
```
    {
  "id": 6
}
  
    {
  "id": 5
}
  ```

what more if we add another 
`  <ng-home [id]="6" />`

all components disappear.

Wrapping them in individual views using `<ng-home *ngIf="true" [id]="6" />` fix the problem.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-jjhdfj?file=src/main.ts

### Please provide the exception or error you saw

```true
ROR Error
    at defaultThrowError (signal.ts:87:5)
    at throwInvalidWriteToSignalError (signal.ts:91:5)
    at WritableSignalImpl.set (untracked.ts:11:1)
    at HomeComponent.ngOnChanges (home.component.ts:29:18)
    at HomeComponent.rememberChangeHistoryAndInvokeOnChangesHook (ng_onchanges_feature.ts:80:10)
    at callHook (hooks.ts:273:15)
    at callHooks (hooks.ts:234:13)
    at executeInitAndCheckHooks (hooks.ts:177:2)
    at selectIndexInternal (contextual.ts:42:1)
    at Object.ɵɵadvance (contextual.ts:15:1)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 16.0.0-next-.6
```

**Comment by atscott** [comment]
This was fixed by https://github.com/angular/angular/pull/49701 and will be in the release later today.

**Comment by pkozlowski-opensource** [comment]
And here is a fixed stackblitz in next.7: https://stackblitz.com/edit/angular-n2baxl?file=src%2Fmain.ts

**Comment by kbrilla** [comment]
Thx @pkozlowski-opensource - that's super fast development :) The link is to next6 but after updating it to next7 works great.  Also forgot to click commit and link I provided was wrong - srx for that and thx for Your work.
