### ISSUE TITLE
ApplicationRef.isStable doesn't wait for all requests finished on SSR with angular 16.

### ISSUE THREAD

**Issue by leo6104** [angular/angular#49730]
### Which @angular/* package(s) are the source of the bug?

platform-server

### Is this a regression?

Yes

### Description

This is regression issue for SSR rendering. 

We trigger several api calls from 30+ components in SSR and it should wait until all response finished. 
However, when the first api call got response from server, it immediately finish ssr render and CommonEngine Promise return partial rendered html. 

It seems ApplicationRef.isStable doesn't wait for all api requests finished. 

There is no changes in our projects and just update to angular 16. (we doesn't apply `provideClientHydration()` option.)

### Please provide a link to a minimal reproduction of the bug

https://github.com/dasom0801/my-universal-app

Component 1 / Component 2 / COmponent 3 each component request api call and only fastest one rendered.

### Please provide the exception or error you saw

```true
the result got from CommonEngine doesn't return fully rendered html string. Only return partially rendered html.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.0-next.6
Node: 16.19.0
Package Manager: npm 8.19.3
OS: darwin x64

Angular: 16.0.0-next.5
... animations, common, compiler, compiler-cli, core, elements
... forms, localize, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0-next.6
@angular-devkit/build-angular   16.0.0-next.6
@angular-devkit/core            16.0.0-next.6
@angular-devkit/schematics      16.0.0-next.6
@angular/bazel                  15.2.4
@angular/cdk                    16.0.0-next.2
@angular/cli                    16.0.0-next.6
@angular/material               16.0.0-next.2
@angular/youtube-player         16.0.0-next.2
@nguniversal/builders           16.0.0-next.0
@nguniversal/common             16.0.0-next.0
@nguniversal/express-engine     16.0.0-next.0
@schematics/angular             16.0.0-next.6
ng-packagr                      16.0.0-next.2
rxjs                            7.8.0
typescript                      5.0.2
```

### Anything else?

Previous angular 15 version we used is here .
```
Angular CLI: 15.2.0-next.4
Node: 16.19.0
Package Manager: npm 8.19.3
OS: darwin x64

Angular: 15.2.0-next.4
... animations, bazel, cli, common, compiler, compiler-cli, core
... elements, forms, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.0-next.4
@angular-devkit/build-angular   15.2.0-next.4
@angular-devkit/core            15.2.0-next.4
@angular-devkit/schematics      15.2.0-next.4
@angular/cdk                    15.2.0-next.0
@angular/material               15.2.0-next.0
@angular/youtube-player         15.2.0-next.0
@nguniversal/common             15.0.0
@schematics/angular             15.2.0-next.4
ng-packagr                      15.1.1
rxjs                            7.6.0
typescript                      4.8.4
```

**Comment by AndrewKushnir** [comment]
@leo6104 thanks for reporting the issue.

It looks like this regression happens between **v16.0.0-next.4** (everything works) and **v16.0.0-next.5** (data is present only partially in SSR'ed output). Looking at [the commits in this range](https://github.com/angular/angular/compare/16.0.0-next.4...16.0.0-next.5), the problem is most likely related to https://github.com/angular/angular/commit/45a6ac09fdd2228fa4bbf5188ba8e67298754e7e.

We'll perform further investigation and provide an update.

// cc @alan-agius4

**Comment by alan-agius4** [comment]
@leo6104, thanks for the reproduction. I will be looking at this on Tuesday.

**Comment by leo6104** [comment]
Thanks for sharing schedule. 😊 

In the commit https://github.com/angular/angular/commit/45a6ac09fdd2228fa4bbf5188ba8e67298754e7e , These test code was removed but it seems still needed for checking pending macrotask exists or not. 

```
    it('requests are macrotasks', waitForAsync(() => {
         const platform = platformDynamicServer(
             [{provide: INITIAL_CONFIG, useValue: {document: '<app></app>'}}]);
         platform.bootstrapModule(HttpClientExampleModule).then(ref => {
           const mock = ref.injector.get(HttpTestingController) as HttpTestingController;
           const http = ref.injector.get(HttpClient);
           ref.injector.get(NgZone).run(() => {
             http.get<string>('http://localhost/testing').subscribe((body: string) => {
               expect(body).toEqual('success!');
             });
             expect(ref.injector.get<NgZone>(NgZone).hasPendingMacrotasks).toBeTruthy();
             mock.expectOne('http://localhost/testing').flush('success!');
             expect(ref.injector.get<NgZone>(NgZone).hasPendingMacrotasks).toBeFalsy();
           });
         });
       }));

```

**Comment by AndrewKushnir** [comment]
@leo6104 thanks again for reporting the issue. We've merged the fix (PR #49776) and the change would be available on NPM later this week as a regular pre-release version of v16 (most likely as 16.0.0-rc.0). Thank you.

**Comment by AndrewKushnir** [comment]
@leo6104 quick update: the `16.0.0-rc.0` version of Angular packages was release to NPM a few minutes ago. Please try to update the app to use that version and let us know if the problem still exists. Thank you.

**Comment by leo6104** [comment]
@AndrewKushnir With new release, it works! 👍👍👍 Thanks for quick updates.
