### ISSUE TITLE
Direct access to DOM (d3.js)

### ISSUE THREAD

**Issue by ziaukhan** [angular/angular#4973]
I have successfully integrated Angular 2 (Alpha 44) with D3.js:
```
<html>
  <head>
    <title>Angular 2 QuickStart</title>
    <script src="../node_modules/systemjs/dist/system.src.js"></script>
    <script src="../node_modules/angular2/bundles/angular2.dev.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js" charset="utf-8"></script>
    <script>
      System.config({
        packages: {'app': {defaultExtension: 'js'}}
      });
      System.import('app/app');
    </script>
  </head>
  <body>
    <my-app>Loading...</my-app>
  </body>
</html>
```

```
/// <reference path="./../../typings/tsd.d.ts" />

import {Component, bootstrap, ElementRef} from 'angular2/angular2';

@Component({
    selector: 'my-app',
    template: '<h1>D3.js Integrated if background is yellow</h1>',
    providers: [ElementRef]
})
class AppComponent { 
    elementRef: ElementRef;
    
    constructor(elementRef: ElementRef) {
        this.elementRef = elementRef;
    }
    
    afterViewInit(){
        console.log("afterViewInit() called");
        d3.select(this.elementRef.nativeElement).select("h1").style("background-color", "yellow");
    }
}
bootstrap(AppComponent);
```

Everything is working fine. But Angular 2 documentation for ElementRef states the following:

>Use this API as the last resort when direct access to DOM is needed. Use templating and data-binding provided by Angular instead. Alternatively you take a look at {@link Renderer} which provides API that can safely be used even when direct access to native elements is not supported. Relying on direct DOM access creates tight coupling between your application and rendering layers which will make it impossible to separate the two and deploy your application into a web worker.

Now the question arises how to integrate D3.js with the Renderer API's? Do we have documentation for Renderer API's or any samples?

**Comment by HerringtonDarkholme** [comment]
For now the best documentation is source code itself. The basic idea is to implement `renderer` interface and feed implementation to dependency injector.

For example, this is the canonical implementation.
https://github.com/angular/angular/blob/master/modules/angular2/src/core/render/dom/dom_renderer.ts

Alternatively, you can take a look at the web worker implementation.
https://github.com/angular/angular/blob/master/modules/angular2/src/web_workers/worker/renderer.ts

And in angular/universal, you can see a server side renderer.

**Comment by hdeshev** [comment]
Implementing an entire renderer just to get the DOM element to D3 looks like overkill. @ziaukhan I'd try using the [Renderer.getNativeElementSync](https://github.com/angular/angular/blob/master/modules/angular2/src/core/render/dom/dom_renderer.ts#L141) API and move the D3-related code to a directive that non-HTML users can opt out of.

You can get a reference to your `Renderer` implementation via an injected constructor parameter. Example here:

https://github.com/angular/angular/blob/master/modules/angular2/src/core/forms/directives/checkbox_value_accessor.ts#L31

**Comment by ziaukhan** [comment]
Thank you so much @hdeshev 
I have number of related questions:
1. The  Renderer.getNativeElementSync method requires a location object. For this purpose I am injecting ElementRef to use as location in this API call. Is there any other way to create a location object which can be of type RenderElementRef or ElementRef? 
2. The Renderer.getNativeElementSync method returns the same object which is returned by ElementRef.nativeElement. So why use Renderer.getNativeElementSync method when you get the same object easily from ElementRef.nativeElement?
3. I did not understand your comment: "move the D3-related code to a directive that non-HTML users can opt out of". Can you please elaborate.

**Comment by hdeshev** [comment]
> 1. The Renderer.getNativeElementSync method requires a location object. For this purpose I am injecting ElementRef to use as location in this API call. Is there any other way to create a location object which can be of type RenderElementRef or ElementRef?

There may be one, but I'm not aware of it. I usually need the root ElementRef for my component and just use a constructor-injected parameter. Maybe you can use a [ViewQuery](https://angular.io/docs/js/latest/api/core/ViewQuery-var.html)

> 2. The Renderer.getNativeElementSync method returns the same object which is returned by ElementRef.nativeElement. So why use Renderer.getNativeElementSync method when you get the same object easily from ElementRef.nativeElement?

Probably not much of a difference. In previous alphas renderers could define their own element refs, and that meant that you could get an object that doesn't have a `nativeElement` property. `Renderer.getNativeElementSync` seems like less likely to change. Of course, I could be wrong here.

> 3. I did not understand your comment: "move the D3-related code to a directive that non-HTML users can opt out of". Can you please elaborate. 

AFAIR the general recommendation to writing platform-specific code is to move it to [directives](https://angular.io/docs/js/latest/api/core/Directive-var.html). This way users that don't need it (or can't use it -- say if running in a non-HTML renderer) can easily disable it in their templates.

**Comment by pkozlowski-opensource** [comment]
Looks like the most questions have been answered here.
