### ISSUE TITLE
styleUrls does not work with root path "/"

### ISSUE THREAD

**Issue by erictsangx** [angular/angular#4974]
``` javascript
styleUrls: ["dist/stylesheet/App.css"] // this works perfectly
styleUrls: ["/dist/stylesheet/App.css"] // this does not work
```

any idea?

**Comment by HerringtonDarkholme** [comment]
https://github.com/angular/angular/blob/master/modules/angular2/src/core/compiler/style_url_resolver.ts#L18

I'm not sure why. It seems Angular2 is agnostic about file path like `./`, `/`.  Is this intended?

**Comment by tbosch** [comment]
Yes, this is a valid bug right now. Thanks for reporting!

**Comment by kevinwestern** [comment]
It is a bit unfortunate because absolute paths work with templateUrls.

I've found this bug is only a problem when I navigate away from index.html and refresh the page. There's not a good way to load the style because it imports relative to the current url. So if I navigate from / -> /user/5, then refresh, the styleUrl requested turns into /usr/app/components/user/user.css.

**Comment by sdir456** [comment]
Same problem here. I'm using version "2.0.0-alpha.45"

**Comment by massanchik** [comment]
Same here. Using beta.1

**Comment by diestrin** [comment]
This was reported again in #6905, anyone know if this is a bug or a feature? and if so, why and how should I handle this?

**Comment by danielrasmuson** [comment]
+1

**Comment by chertpong** [comment]
still be a problem in "2.0.0-beta.7"

**Comment by nlaplume** [comment]
Still seems to be an issue in 2.0.0-beta.11

**Comment by Epimetheus89** [comment]
Still an error in 2.0.0-beta.12

**Comment by rocco-scaramuzzi** [comment]
My workaround is to start my absolute path with the two dots parent directory.

styleUrls: ["/poster-manager-app/asset-management/asset-management.component.css"] // does not work
styleUrls: ["../poster-manager-app/asset-management/asset-management.component.css"] // DOES work by adding "../"

I hope it helps

**Comment by diestrin** [comment]
@rocco-scaramuzzi, that fix doesn't always works, because if you use a router, or the same script in multiple pages with different paths, then the ../ piece sometimes will not be sufficient. I actually ended up writing 
```
getRootRelativePath: function(currentPath = window.location.pathname) {
    let path = currentPath
      .split('/')
      .slice(2)
      .map(() => '..')
      .join('/');

    return path.replace(/^\//, '');
  }
```

But I shouldn't have to write this in order to use css.
I can send a PR with a fix for this, I just need more insight about why did they make this restriction, if it was a mistake or if it's with some logic behind.

**Comment by rocco-scaramuzzi** [comment]
Hi Diego, thanks it makes sense what you said. It solves the problem for my needed until we understand if it is a bug or not. Anyway for my comment I added a note to read your comment since that "workaround" won't work in same cases.

**Comment by iDev0urer** [comment]
@rocco-scaramuzzi 's solution seems to work, but this kinda sucks.

**Comment by chrisbouchard** [comment]
There's a comment in [`extractStyleUrls`](https://github.com/angular/angular/blob/master/modules/%40angular/compiler/src/style_url_resolver.ts#L27):

> Do not attempt to resolve non-package absolute URLs with URI scheme

Which makes me wonder if `isStyleUrlResolvable` needs to differentiate between URLs from `styleUrls` and from `@import`s.

**Comment by VadimDez** [comment]
Still not working, 2.0.0-rc.1

**Comment by NikolaosChasanis** [comment]
If nothing of these answers work for you (it didn't for me) try to use FULL PATH and when i say full path i mean... even the project folder in that full path! 
for example myproject/app/blabla.css and at least for styleUrls will get it right! 
most of the answers start from /app/blabla.css but it wasn't the case for me. 
Hope i helped a fellow!

**Comment by diestrin** [comment]
BTW, I discovered you can also use the **moduleId** property in the component, to give a relative path.
https://angular.io/docs/ts/latest/api/core/index/ComponentMetadata-class.html -> look for moduleId
```
@Component({
  moduleId: module.id,
  styleUrls: ['relativeUrl.css']
})
```

**Comment by luozt** [comment]
still has this problem, 2.0.0-rc.3

**Comment by jrfoxw** [comment]
The problem still occurs in 2.0.0-rc.4
The post @diestrin appears to resolve the problem (Using moduleId: module.id)

**Comment by juliencousineau** [comment]
Trying everything here, still have the problem. I dont have any errors on my console, but the css is not loaded

**Comment by turbo5** [comment]
Same here, I still have the problem.

**Comment by sinedsem** [comment]
+1

**Comment by CCristi** [comment]
+1

**Comment by Neurion** [comment]
Same problem in 2.0.0-rc.7

**Comment by jasonburrows** [comment]
Same problem, final release, 2.0.0.

**Comment by phi293** [comment]
+1, using final release.

**Comment by mswilson4040** [comment]
+1

**Comment by jonnyasmar** [comment]
+1 final release

**Comment by parweennargis** [comment]
for this you do not need to remove any trailing slash or any thing, actually I was also making this mistake and html page was not linking with css file.

Actually I was making silly mistake : html page as :

    <img src="../../assets/images/logo.png" alt="LOGO" class="responsive-img login-logo-width">

css file as :

    login-logo-width {
       width: 260px;
    }3

Error I was getting as : **This inspection detects unknown CSS selectors and provides ability to declare them as a class or an id**

So the htiong which you have to do is : define the parameter to id or class whatever you have declared in the html file as :

    .login-logo-width {
        width: 260px;
    }

**Comment by jonnyasmar** [comment]
I wasn't satisfied with the hack I mentioned in my comment above. So, I've just submitted a change that should close this issue. If approved and merged into master, this change will allow the declaration of a web root relative styleUrl by prefixed it with a `~`.

i.e.
`styleUrls: ["~/dist/stylesheet/App.css"] // this will work perfectly
styleUrls: ["/dist/stylesheet/App.css"] // this will continue to not work`

The pull request can be reviewed here: https://github.com/angular/angular/pull/12741

Please feel free to reach out to me if you have any questions!

**Comment by miguel18alvarado** [comment]
But that happen  only with style urls...
I put the style code inside the html file component and works

**Comment by anantkamath** [comment]
It's 2017 this still isn't fixed!

**Comment by mhevery** [comment]
Re: [angular/angular] fix(compiler): REVERT allow absolute style urls (#14365) (f0575e0)

**Comment by anantkamath** [comment]
Why was the fix reverted?

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/commit/f0575e014c160ff3273c2726c3b5abab39bcf091#commitcomment-20963741 :
> Had to revert as it breaks Google 3.

**Comment by ozrite** [comment]
Its still a bug even in 2017 even in latest version of angular with angular cli. The aboloute paths from within the global css files are not being read for custom font files.
//******************** Global includes **************************
<script type='text/javascript' src ='https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js'></script> <script type="text/javascript" src="js/script.js"></script> <script src="js/bootstrap.min.js"></script>

//****************************** css file from pins-styles.css ****************************
These paths are not being read.
//css file

@charset "UTF-8";

@font-face {
font-family: "pins";
src:url("../pins-fonts/pins.eot");
src:url("../pins-fonts/pins.eot?#iefix") format("embedded-opentype"),
url("../pins-fonts/pins.woff") format("woff"),
url("../pins-fonts/pins.ttf") format("truetype"),
url("../pins-fonts/pins.svg#pins") format("svg");
font-weight: normal;
font-style: normal;

}

I have ported my code to new version of angularCli but after troubleshooting many problems, i found out that the absolute paths are not working. rest of the styles are being loaded.

**Comment by SuEric** [comment]
Still open??

**Comment by tskaiser** [comment]
So I just ran into this while learning Angular. Considering the surprise-factor and longevity of the bug this should be highlighted in the docs until fixed.

**Comment by Yugloocamai** [comment]
I can't believe this bug is still here!!! I can't import my CSS!  This is has been an issue for over a year!

**Comment by Yugloocamai** [comment]
I worked around this problem by using a modified version of systemjs-angular-loader.js

changed line 42 from:
`
 urls.push('"' + basePath + match[2].substr(1) + '"');
`
to:
`
urls.push('"' + basePath.slice(1) + match[2].substr(1) + '"');
`

**Comment by rockeek** [comment]
I think I have found the solution guys!

Don't use styleUrls. **Simply rename the style file with `scss `extension.** The stylesheet will be used automatically!

Therefore, my component's files will be like this, and will work with the style:

```
- mycomponent.ts
- mycomponent.html
- mycomponent.scss
```

**Comment by buchatsky** [comment]
I think the new code leaves out the case when url.length === 0, and simple removing of 
> url[0] == '/'
whold be enough

**Comment by rocker8942** [comment]
Hope this fixed soon.

**Comment by andrevvalle** [comment]
Hope this fixed soon. ( -_-)旦~

**Comment by jonnyasmar** [comment]
Sorry everyone -- I dropped the ball on this fix. However, in the meantime, I've actually stopped using Angular for the most part in favor of React, so I have little motivation to correct this issue.

However, I had a viable fix with this PR https://github.com/angular/angular/pull/12741#issuecomment-306541420, but it was denied because it isn't compatible with AOT compilation in Angular 4/5.

> Add the capability to declare a web root relative path for Component styleUrls by prefixing the url with `~`.

If someone can figure out a way to make this `~/path/to/root/styles` method compile properly it may work. I'm not sure exactly how AOT works in Angular, but I imagine you'd just have to expand the `~` into the full path at compile time.

Anyways, good luck Angular community!

**Comment by splincode** [comment]
@erictsangx Is the issue relevant?

**Comment by mhevery** [comment]
won't implement since absolute absolute paths have different meaning for AoT vs JIT.

**Comment by kylecordes** [comment]
For those who still need a fix to this for JIT (which has fewer and fewer use cases as of 2018...  but I have one of them here), the following monkey patch works:

```
const fs = require('fs');

const fn = 'node_modules/@angular/compiler/compiler.js';

const source = fs.readFileSync(fn, 'utf-8');
const patched = source.replace(
  `if (url == null || url.length === 0 || url[0] == '/')`,
  `if (!url) /* match previous length for source maps */`
);
fs.writeFileSync(fn, patched);
```

**Comment by milottit** [comment]
> won't implement since absolute absolute paths have different meaning for AoT vs JIT.

Can you explain the difference?

**Comment by DzmVasileusky** [comment]
Why the docs says

> One or more relative paths or absolute URLs for files containing CSS stylesheets to use in this component.

if absolute pathes not available?
