### ISSUE TITLE
Upgrade from 13 ~ 15 Error: Emit attempted before Angular Webpack plugin initialization.

### ISSUE THREAD

**Issue by meenamunshi** [angular/angular#49740]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

"dependencies": {
    "@angular/animations": "^15.2.6",
    "@angular/cdk": "^15.2.6",
    "@angular/common": "~15.2.6",
    "@angular/compiler": "~15.2.6",
    "@angular/core": "~15.2.6",
    "@angular/forms": "~15.2.6",
    "@angular/material": "^15.2.6",
    "@angular/platform-browser": "~15.2.6",
    "@angular/platform-browser-dynamic": "~15.2.6",
    "@angular/router": "~15.2.6",
    "@ng-bootstrap/ng-bootstrap": "^14.1.0",
    "@ngrx/effects": "^15.4.0",
    "@ngrx/entity": "^15.4.0",
    "@ngrx/store": "^15.4.0",
    "@ngrx/store-devtools": "^15.4.0",
    "@ngtools/webpack": "^15.2.5",
    "@swimlane/ngx-charts": "^20.1.2",
    "bootstrap": "^5.0.2",
    "echarts": "^5.1.0",
    "jwt-decode": "^3.1.2",
    "ngx-echarts": "^15.0.3",
    "ngx-logger": "^5.0.11",
    "ngx-toastr": "^16.1.0",
    "rxjs": "7.5.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~15.2.5",
    "@angular/cli": "~15.2.5",
    "@angular/compiler-cli": "~15.2.6",
    "@types/d3-scale": "^4.0.2",
    "@types/d3-selection": "^3.0.2",
    "@types/echarts": "^4.9.16",
    "@types/jasmine": "~4.3.1",
    "@types/node": "^18.15.11",
    "angular-persistence": "^1.0.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~4.6.0",
    "jasmine-spec-reporter": "~7.0.0",
    "karma": "~6.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "^2.0.0",
    "protractor": "~7.0.0",
    "rxjs-compat": "^6.6.7",
    "ts-node": "~10.9.1",
    "tslint": "~6.1.0",
    "typescript": "4.8.2"
  }

### Please provide the exception or error you saw

```true
One or more browsers which are configured in the project's Browserslist configuration will be ignored as ES5 output is not supported by the Angular CLI.
Ignored browsers: kaios 2.5, op_mini all
✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |  Raw Size | Estimated Transfer Size
styles.css, styles.js | styles        | 398.39 kB |                57.87 kB
main.js               | main          | 118.77 kB |                29.05 kB
polyfills.js          | polyfills     | 118.77 kB |                29.04 kB
runtime.js            | runtime       |   1.25 kB |               681 bytes

                      | Initial Total | 637.17 kB |               116.61 kB

Build at: 2023-04-06T21:04:06.409Z - Hash: d96d42fe7f3c7221 - Time: 12077ms

Warning: 1 rules skipped due to selector errors:
  legend+* -> Cannot read properties of undefined (reading 'type')



./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.

./src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.

Error: Failed to initialize Angular compilation - The target entry-point "angular-persistence" has missing dependencies:
 - rxjs/Rx
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
```

**Comment by meenamunshi** [comment]
grumpysage > ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.2.5
Node: 14.21.1
Package Manager: yarn 1.22.19
OS: darwin x64

Angular: 15.2.6
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.5
@angular-devkit/build-angular   15.2.5
@angular-devkit/core            15.2.5
@angular-devkit/schematics      15.2.5
@angular/cli                    15.2.5
@ngtools/webpack                15.2.5
@schematics/angular             15.2.5
rxjs                            7.5.0
typescript                      4.8.2
    
grumpysage >

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
