### ISSUE TITLE
Lazy loaded providers expected to not appear in the main bundle

### ISSUE THREAD

**Issue by martinakraus** [angular/angular#49755]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

With the new standalone API we can declare lazy loaded providers inside the `routes.ts` files:

```typescript
export const APP_ROUTES: Routes = [
 ....
  {
    path: 'books',
    loadChildren: () => import('./books/routes'),
    providers: [BookApiService]
  } ]
```

These APP_ROUTES will be registered inside the `provideRouter(APP_ROUTES)` in the `main.ts`

The BookApiService will now be bundled inside the main bundle. Is this a desired behavior? I do understand that the APP_ROUTES holds the reference to this Service and for that, it will already be compiled inside the main bundle.
Previously we could just use the providers Property inside the lazy-loaded module. How is the intended way now?

Should we use the providers Property inside the Child Routes?
Something like this?

```typescript
export default [ {
  path: '',
  component: BookPageComponent,
  providers: [BookApiService],
  children: [{
    path: '',
    component: BookComponent
  }
  ]
} ] as Routes

```

BookApiService without `providedIn('root')`

``` typescript
@Injectable()
export class BookApiService {

...
}
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.0-next.7
Node: 18.14.0
Package Manager: npm 9.3.1
OS: darwin arm64

Angular: 16.0.0-next.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0-next.7
@angular-devkit/build-angular   16.0.0-next.7
@angular-devkit/core            16.0.0-next.7
@angular-devkit/schematics      16.0.0-next.7
@schematics/angular             16.0.0-next.7
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by atscott** [comment]
Yes, this is expected. The providers are not lazy loaded, as they need to be available to the canMatch or CanLoad guards. If you wanted the provider to be lazy loaded, it would need to be in the child routes.
