### ISSUE TITLE
platform-browser.mjs _addStylesToHost function trigger CSP error

### ISSUE THREAD

**Issue by finzero** [angular/angular#49758]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

Yes

### Description

so i have this CSP configuration
`add_header Content-Security-Policy "default-src 'self'; style-src 'self'; font-src *; img-src * data:; script-src 'self'; connect-src https://my.api-url.com";`

but this function in platform-browser.mjs line 372 trigger CSP error:
`_addStylesToHost(styles, host, styleNodes) {
        styles.forEach((style) => {
            const styleEl = this._doc.createElement('style');
            styleEl.textContent = style;
            styleNodes.push(host.appendChild(styleEl));
        });
    }`

is there any workaround for this issue without having to set unsafe-inline in CSP ?

### Please provide the exception or error you saw

```true
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-qTTH3DuzKPmgtKU61WF0JCpnThDceaYDm31rPH7akOE='), or a nonce ('nonce-...') is required to enable inline execution.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.9
Node: 16.15.0
Package Manager: npm 8.5.5
OS: linux x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.9
@angular-devkit/build-angular   13.3.9
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.3.9
@angular/cli                    13.3.9
@schematics/angular             13.3.9
rxjs                            6.6.7
typescript                      4.6.4
```

### Anything else?

this issue related to https://github.com/angular/angular-cli/issues/3430

**Comment by alan-agius4** [comment]
Addressed via https://github.com/angular/angular/pull/49561 which is available in the current v16 prerelease.
