### ISSUE TITLE
[Feature request] Perl 6 style "given" functionality in ng-switch 

### ISSUE THREAD

**Issue by djvs** [angular/angular#4976]
Perl's "given" switch syntax is a godsend, matching against types, regexes, operations on the subject of the switch statement, etc:

https://en.wikibooks.org/wiki/Perl_6_Programming/Control_Structures#Given_.2F_When

Without reviewing the ng2 source I don't know how much of that ties irreparably into its "$parse" equivalent, but I know that directives had to be created for ng1 to bridge the gap in functionality (specifically, ng-if, ng-elif, ng-else). Can a variable be introduced by ng-switch which can be operated upon by ng-switch-when?

The directive, for reference:

https://github.com/angular/angular/blob/d32f58926dd15a5771f5e3a3c2b77ea41c03b98b/modules/angular2/src/directives/ng_switch.ts

**Comment by vicb** [comment]
NgSwitch API will not change.
