### ISSUE TITLE
Quickstart install Documentation package.json issue

### ISSUE THREAD

**Issue by mcpDESIGNS** [angular/angular#4978]
Very minor issue, I just couldn't see where / how to edit the Quickstart documentation.

Right now it states:

    There is also a scripts section. Find and replace it with the following:

    {
      "scripts": {
        "start": "live-server"
      }
    }

It should be changed to the below line, otherwise `npm start` errors out with a `parse JSON` error since the package.json isn't valid JSON.

    "scripts": {
        "start": "live-server"
     }

If there's an easy way/place to make a PR about this I'll do it just let me know!

**Comment by pkozlowski-opensource** [comment]
@mcpDESIGNS all the tutorials live in https://github.com/angular/angular.io - you can open an issue / send a PR in there. Thnx!
