### ISSUE TITLE
DOCS missing for replacing index.html with custom one in Angular configuration

### ISSUE THREAD

**Issue by lukaonik** [angular/angular#49780]
### Describe the problem that you experienced

There is an option in the Angular project configuration to set a different index.html file instead of the default one. It is very handy when you want to have different scripts in HTML per environment, like GTM, for example.
Unfortunately, it is not mentioned anywhere in Angular docs.
So the proposal is to add it in Angular DOCS.

### Describe what you were looking for in the documentation

I was looking for an option that would replace the default index.html file with a different one during build/serve time

### Provide any additional information here in as much as detail as you can

```true
PR for this option:
https://github.com/angular/angular-cli/pull/15010
More Info:
https://stackoverflow.com/questions/59324204/how-to-replace-index-html-in-angular-8-3-depending-on-environment
```

**Comment by lukaonik** [comment]
I could create PR for that @alan-agius4 
we can add an extra column with description below the fileReplacement row,
https://angular.io/guide/workspace-config#extra-build-and-test-options
![image](https://user-images.githubusercontent.com/15605974/231405054-b687704c-a157-4528-ab95-26b28a90460a.png)

**Comment by alan-agius4** [comment]
@lukaonik, yes that does sound the right place to add it. 

We'd also need to add a sub-section like https://angular.io/guide/workspace-config#styles-and-scripts-configuration that better describes all the "index" [options](https://github.com/angular/angular-cli/blob/c6c045b280edf8a3990e90c689b2e8862d298010/packages/angular_devkit/build_angular/src/builders/browser/schema.json#L369-L395)

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular/pull/49813
