### ISSUE TITLE
Missing dynamic formcontrolname in generated html 

### ISSUE THREAD

**Issue by anikets43** [angular/angular#49794]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

When dynamic value for `formControlName` is used, `formcontrolname` attribute is missing from generated html

```  html
<form [formGroup]="form">
   <input [formControlName]="key" />
</form>
```

``` ts
form = new FormGroup({
 name: new FormControl('Angular')
})

key = 'name';
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-mmkf4p?file=src%2Fmain.ts

<img width="1576" alt="image" src="https://user-images.githubusercontent.com/7136799/231287652-70850291-97cc-447e-a72c-187b5cc3f506.png">

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 15.1.2
```

**Comment by JoostK** [comment]
This is working as designed; bindings in Angular templates correspond with property bindings and are not reflected as HTML attribute.
