### ISSUE TITLE
`effect` throws error in zoneless mode

### ISSUE THREAD

**Issue by markostanimirovic** [angular/angular#49798]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

The `effect` function throws an error in zoneless mode on [this line](https://github.com/angular/angular/blob/e9dd7f00280b6d52fa2a21da793521db1a9d7a53/packages/core/src/render3/reactivity/effect.ts#L33).

### Please provide a link to a minimal reproduction of the bug

https://github.com/markostanimirovic/zoneless-ng-16

### Please provide the exception or error you saw

```true
ReferenceError: Zone is not defined
    at EffectManager.create
    at effect
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.0-next.7
Node: 16.16.0
Package Manager: npm 8.11.0
OS: win32 x64
```

**Comment by eneajaho** [comment]
Signals don't work zoneless currently, unfortunately. 

I had the same issue with this: https://stackblitz.com/edit/angular-9cgvy9?file=src%2Fmain.ts

**Comment by maitrungduc1410** [comment]
without NgZone, app doesn't reactive. following by the example  of @markostanimirovic. here's my code:

```ts
import { Component, signal, computed } from '@angular/core';

@Component({
  selector: 'app-profile',
  template: `
    <h1>{{ count() }}</h1>
    <h2>{{ double() }}</h2>

    <button (click)="updateCount()">Increment</button>
  `,
})
export class ProfileComponent {
  count = signal(0);
  double = computed(() => this.count() * 2);

  updateCount() {
    this.count.update((value) => value + 1);
  }
}

```

When clicking the button, UI doesn't change. with NgZone it's fine

**Comment by atscott** [comment]
> without NgZone, app doesn't reactive. following up with the example of @markostanimirovic. here's my code:
> 
> ```ts
> import { Component, signal, computed } from '@angular/core';
> 
> @Component({
>   selector: 'app-profile',
>   template: `
>     <h1>{{ count() }}</h1>
>     <h2>{{ double() }}</h2>
> 
>     <button (click)="updateCount()">Increment</button>
>   `,
> })
> export class ProfileComponent {
>   count = signal(0);
>   double = computed(() => this.count() * 2);
> 
>   updateCount() {
>     this.count.update((value) => value + 1);
>     console.log(this.count()) // prints correct updated count
>   }
> }
> ```
> 
> When clicking the button, UI doesn't change. with NgZone it's fine

Correct, this is expected. There is no real support for Zoneless and yet. This will be coming in future releases.
