### ISSUE TITLE
Transformers include annotations for each constructor stub

### ISSUE THREAD

**Issue by mhevery** [angular/angular#498]
Fill in the annotation information.

Given this source:
```
@Component(
  selector: 'my-component',
  ...
)
class MyComponent {
}

main() {
  bootstrap(MyComponent);
}
```

generate:

```
import 'package:path/to/above/file' as file1;
import 'package:reflection/reflection.dart' show reflector;

setupReflection() {
  reflector.registerType(
    file1.MyComponent, 
    factory: ...,
    paramaters: ...,
   "annotations" : [new Component(selector: 'my-component', ...)]
  );
}
```

**Comment by kegluneq** [comment]
Is this just making sure the annotations aren't lost in the transform, or are we looking to define them in some different way in the final code, similar to how the Js annotations are attached to the constructor object's `.annotations` property?

**Comment by mhevery** [comment]
@kegluneq sorry, i updated the text.
