### ISSUE TITLE
Illegal characters in path error when I run aio project with command "yarn start/start-local" on Windows

### ISSUE THREAD

**Issue by lukaonik** [angular/angular#49806]
### Describe the problem that you experienced

I'm trying to start the development server for aio project, with the following command
`yarn start` (  same for yarn start-local ),
but I get the exception during the build

### Describe the actions that led you to experience the problem

- cloned angular repo
- cd aio
- yarn install
- yarn start

### If this problem caused an exception or error, please paste it here

```true
ERROR: C:/projects/angular/aio/BUILD.bazel:73:16: NpmPackageBin aio/dgeni failed: (Exit 1): dgeni.bat failed: error executing command bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\external\aio_npm\dgeni\bin\dgeni.bat ./bazel-out/x64_windows-fastbuild/bin/aio/tools/transforms/angular.io-package ... (remaining 1 argument skipped)
error:   Error running processor "cleanGeneratedFiles":
Illegal characters in path.
error:   Failed to process the docs
```
```


### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
OS Name	Microsoft Windows 10 Enterprise LTSC
Version	10.0.17763 Build 17763
```

**Comment by lukaonik** [comment]
I went down a bit deeper and found out that this line causes the error:
![image](https://user-images.githubusercontent.com/15605974/231452943-1061c8d1-2234-4887-b5e3-8c249eda69c5.png)
it's inside `aio > tools > transforms > angular.io-package > processors > cleanGeneratedFiles.js`
I commented it out, and the DOCS started successfully.
I'll try to figure out why it causes the error a later.

**Comment by lukaonik** [comment]
Okay so I think I found the issue:
* ( wildcard ) usage was removed in rimraf from v4 ( see https://github.com/isaacs/rimraf/issues/251 for more info ).
so I could fix it with the help of the glob package. Here's the code:

```
const rimraf = require('rimraf');
const glob = require('glob');

module.exports = function cleanGeneratedFiles() {
  return {
    $runAfter: ['writing-files'],
    $runBefore: ['writeFilesProcessor'],
    $process: function () {
      rimraf.sync(glob.sync('src/generated/{docs,*.json}'));
    },
  };
};

```

**Comment by JeanMeche** [comment]
The glob pattern was added back in 4.2 and the bump to 5.0 is ready to be merge in #49757
