### ISSUE TITLE
Refused to apply inline style while nonce is available in the Content Security Policy header in Angular v16.0.0-next.7

### ISSUE THREAD

**Issue by amanplans** [angular/angular#49827]
### Which @angular/* package(s) are the source of the bug?

core, Don't known / other

### Is this a regression?

No

### Description

My previous issue https://github.com/angular/angular/issues/49104 has been closed by @alan-agius4, because https://github.com/angular/angular/pull/49561 should have solved this.

I updated my sample project to make use of Angular v16.0.0-next.7 and the CSP error is now thrown on line 69 of the file layout.mjs which is part of the Angular CDK throws the following error:

Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-EinOpauVzQr0n6wq5ptWvkI/' fonts.googleapis.com". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.

A CSP error is thrown when you add content with a style to a paragraph tag.

```
HTML file
<p [innerHTML]="link"></p>

TS file
link: string = '<a href="https://www.google.com" style="cursor: auto; color: rgb(0, 0, 0); background-color: rgb(250, 250, 250);">Google</a>';
```

Do I have to add a nonce in the paragraph-tag? How can I do that?

### Please provide a link to a minimal reproduction of the bug

https://github.com/amanplans/csp-header

### Please provide the exception or error you saw

```true
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-EinOpauVzQr0n6wq5ptWvkI/' fonts.googleapis.com". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.0-next.7
Node: 18.15.0
Package Manager: npm 9.6.0
OS: win32 x64

Angular: 16.0.0-next.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0-next.7
@angular-devkit/build-angular   16.0.0-next.7
@angular-devkit/core            16.0.0-next.7
@angular-devkit/schematics      16.0.0-next.7
@angular/cdk                    16.0.0-next.5
@angular/material               16.0.0-next.5
@schematics/angular             16.0.0-next.7
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by crisbeto** [comment]
> A CSP error is thrown when you add content with a style to a paragraph tag.

Do you mean that you're creating the `style` tag yourself with the inline style? Currently the `ngCspNonce` is used only when inserting the styles associated with a component.

**Comment by alan-agius4** [comment]
The issue here is that `ngCspNonce` attribute is not being set in the in the [`index.html`](https://github.com/amanplans/csp-header/blob/b29a40dcb994d11f948892166cdc5aefae187d79/CspHeader/CspAngular/src/index.html#L14) which is what the Angular CLI sees. This needs to be set here so that the `nonce` attribute is added when style tag are generated during build time.

**Comment by amanplans** [comment]
> > A CSP error is thrown when you add content with a style to a paragraph tag.
> 
> Do you mean that you're creating the `style` tag yourself with the inline style? Currently the `ngCspNonce` is used only when inserting the styles associated with a component.

I updated my opening post, the example was broken during display. I have changed it to a code-section.

**Comment by crisbeto** [comment]
That case isn't supported by the `CSP_NONCE` token since we don't know what some of code might be in the HTML string. Angular only sets the nonce on styles it creates.

**Comment by amanplans** [comment]
Is it a separate bug then? Shall I create another issue for it? Since layout.mjs throws a CSP error.

**Comment by crisbeto** [comment]
Ah the `cdk/layout` was fixed in https://github.com/angular/components/commit/86000adcfdbeb24cf0ff699ea187df76b2a624c0, but it looks like it wasn't cherry-picked into the proper release branch. I'll make sure it's in next week's release.

**Comment by amanplans** [comment]
@crisbeto, I see @angular/core v16.0.0-rc.1 is available. I updated my repository to use this version and `ng version` gives

Angular CLI: 16.0.0-rc.0
Node: 18.15.0
Package Manager: npm 9.6.0
OS: win32 x64

Angular: 16.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0-rc.0
@angular-devkit/build-angular   16.0.0-rc.0
@angular-devkit/core            16.0.0-rc.0
@angular-devkit/schematics      16.0.0-rc.0
@angular/cdk                    16.0.0-rc.0
@angular/cli                    16.0.0-rc.0
@angular/material               16.0.0-rc.0
@schematics/angular             16.0.0-rc.0
rxjs                            7.8.0
typescript                      4.9.5

The paragraph-tag with styling passed through innerHTML still gives an error.
When the project starts it shows the infamous CSP errror (Refused to apply inline style) in core.mjs for line 7964. After a refresh it shows it for app.component.html on line 52.

Any idea which release candidate will be the one you mentioned before?

**Comment by amanplans** [comment]
Thanks @crisbeto `@angular/cdk` v16.0.0-rc.1 indeed fixes the layout.mjs error. Looking forward to the Angular 16 release!

**Comment by alan-agius4** [comment]
Closing as per above.
