### ISSUE TITLE
trackBy is not reflected in DOM

### ISSUE THREAD

**Issue by JSmithOner** [angular/angular#49831]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

the trackBy is not reflected in the DOM. I suspect this is causing my inputs inside the `*ngFor` loop to be setted back to inital values while the DOM is recreated.

I wasn't able to recreate the input setted back to initial value but you can see n this [stackblitz](https://stackblitz.com/edit/angular-7lzvjn?file=src%2Fmain.ts,src%2Fchild%2Fchild.component.ts,src%2Fchild%2Fchild.component.html,src%2Fchild%2Fchild.component.css,src%2Findex.html)

if you inspect the DOM the `*ngFor` in the `ChildComponent` taking as argument `node.parameters` you will see that the DOM shows

```
<!--bindings={
  "ng-reflect-ng-for-of": "[object Object],[object Object"
}-->
```

looks like it doesn't reflect the trackBy method
while the parent loop shows

```
<!--bindings={
  "ng-reflect-ng-for-track-by": "(index, item) => item"
}-->
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-7lzvjn?file=src%2Fmain.ts,src%2Fchild%2Fchild.component.ts,src%2Fchild%2Fchild.component.html,src%2Fchild%2Fchild.component.css,src%2Findex.html

### Please provide the exception or error you saw

```true
No exception
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.6
Node: 16.17.0
Package Manager: npm 8.15.0
OS: darwin arm64

Angular: 15.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.10
@angular-devkit/build-angular   15.2.6
@angular-devkit/core            15.2.6
@angular-devkit/schematics      15.2.6
@angular/cdk                    15.2.6
@angular/cli                    15.2.6
@angular/fire                   7.5.0
@angular/material               15.2.6
@schematics/angular             15.2.6
rxjs                            6.6.7
typescript                      4.8.4
webpack                         5.76.1
```

**Comment by JSmithOner** [comment]
@JeanMeche Thank you for your answer have you tried it on firefox?

**Comment by AndrewKushnir** [comment]
@JSmithOner I think the best way to validate whether the `trackBy` works is by making sure it's invoked by the framework. You can try adding a `console.log` into the function that you pass to the `trackBy` and see if it gets invoked (if there are any logs in a console).

**Comment by JSmithOner** [comment]
@AndrewKushnir  looks like it's working my bug didn't come from that.closing this issue.Thanks for yout time
