### ISSUE TITLE
 error TS2339: Property 'keyword' does not exist on type 'FormGroup<any>'.

### ISSUE THREAD

**Issue by ihabpalamino** [angular/angular#49841]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

![image](https://user-images.githubusercontent.com/86556941/232016291-c01a07a7-7317-4622-a807-0ca0c32676a9.png)
![image](https://user-images.githubusercontent.com/86556941/232016407-1213de6b-e54e-49b3-ab31-6243b7ea7999.png)
here is my source code please help

### Please provide the exception or error you saw

```true
error TS2339: Property 'keyword' does not exist on type 'FormGroup<any>'.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular cli 15
node js 18
```

**Comment by JeanMeche** [comment]
Hi, for your issue to be investigated, can you share a reproduction on stackblitz instead of screens ? Thx !

**Comment by ihabpalamino** [comment]
import { Component,OnInit} from '@angular/core';
import {TwitterServiceService} from 'src/app/services/twitter-service.service';
import { Twitter} from '../model/Twitter.model';
import {FormBuilder, FormControl, FormGroup, Validators} from '@angular/forms';
@Component({
  selector: 'app-twitter',
  templateUrl: './twitter.component.html',
  styleUrls: ['./twitter.component.css']
})
export class TwitterComponent implements OnInit{
twitter! :Array<Twitter>;
searchFormGroup! : FormGroup;
constructor(private twitterService:TwitterServiceService, private fb: FormBuilder){}
ngOnInit():void{
this.searchFormGroup=this.fb.group({
keyword : this.fb.control(null)
});
this.twitterService.getAllTwitter().subscribe({
next :(data)=>{
this.twitter=data;
}
});

}
handleDeleteTwitter(t:Twitter){
let conf=confirm("etes vous sur de vouloir supprimer")
if(conf==false)return;
this.twitterService.deleteTwitter(t.id).subscribe({
next :(data)=>{
let index=this.twitter.indexOf(t);
this.twitter.splice(index,1);

}
})
}
handleSearchTwitter(){
let keyword =this.searchFormGroup.keyword;
this.twitterService.searchTwitter(keyword).subscribe({
 next :(data)=>{
this.twitter=data;
 }
})
}
}}

**Comment by JeanMeche** [comment]
Your `FormGroup` isn't typed. It sould be something like `FormGroup<{keywords: FormControl<string>}>`.

**Comment by ihabpalamino** [comment]
<div class="card-body">
      {{searchFormGroup.value|json}
      <form [formGroup]="searchFormGroup" (ngSubmit)="handleSearchTwitter()">
        <div class="input-group">
        <label class="input-group-text">keyword</label>
          <input type="text" class="form-control" formControlName="keyword">
          <button class="btn btn-info">
            <i class="bi bi-search"></i>
          </button>
        </div> 
and this is my html code

**Comment by ihabpalamino** [comment]
> Your `FormGroup` isn't typed. It sould be something like `FormGroup<{keywords: FormControl<string>}>`.

where shoul i do it in wich line?

**Comment by JeanMeche** [comment]
Since this isn't a bug but you're looking for help, I will let you ask your question on StackOverflow.

**Comment by ihabpalamino** [comment]
actually i found the solution i had to replace 
let keyword =this.searchFormGroup.keyword
with 
let keyword =this.searchFormGroup.value.keyword

**Comment by ihabpalamino** [comment]
+import { v4 as UUID } from "uuid";


@Injectable({
  providedIn: 'root'
})
export class TwitterServiceService{
  private twitter! : Array<Twitter>;
  constructor() {
   this.twitter=[
               {id:UUID.UUID(),name:"alaoula",caption:"djlqkz",like:150,comments:500},
               {id:UUID.UUID(),name:"alaoula",caption:"malaz",like:250,comments:550},
               {id:UUID.UUID(),name:"alaoula",caption:"djlqkz",like:450,comments:600},
              {id:UUID.UUID(),name:"2mtv",caption:"djlqkz",like:150,comments:500},
              {id:UUID.UUID(),name:"medi1tv",caption:"malaz",like:250,comments:550},
               {id:UUID.UUID(),name:"alaoula",caption:"djlqkz",like:450,comments:600},
               ];}
while using uuid in this code i got this new issue 
![image](https://user-images.githubusercontent.com/86556941/232052740-d00247af-e08a-4e9c-b124-1f6be103ba96.png)
