### ISSUE TITLE
Unable to use removeControl method for a typed FormGroup

### ISSUE THREAD

**Issue by maxpontreau** [angular/angular#49847]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

I have the following form group declare in my typescript file:

`myFormGroup: FormGroup<MyFormInterface>;`

`export interface MyFormInterface {
  id: FormControl<number>;
  type: FormControl<MyType | null>;
  amount: FormControl<number>;
  comment: FormControl<string | null>;
  optional1?: FormControl<string | null>;
  optional2?: FormControl<string | null>;
}`

When I change my type value I want to remove optional1 or optional2 according to the value by running the following code:
`this.myFormGroup.removeControl('optional1');`

But I'm facing an compilation error. To fix it I had to write it that way:
`(this.myFormGroup as FormGroup).removeControl('optional1');`

### Please provide the exception or error you saw

```true
Error: src/app/page-expense-edition/expense-edition-form/expense-edition-form.component.ts:67:9 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(this: FormGroup<{ [key: string]: AbstractControl<any, any>; }>, name: string, options?: { emitEvent?: boolean | undefined; } | undefined): void', gave the following error.
    The 'this' context of type 'FormGroup<ExpenseEditionForm>' is not assignable to method's 'this' of type 'FormGroup<{ [key: string]: AbstractControl<any, any>; }>'.
  Overload 2 of 2, '(name: never, options?: { emitEvent?: boolean | undefined; } | undefined): void', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'never'.
```

**Comment by JeanMeche** [comment]
I could not reproduce your issue with the code you provided, which angular version are you running ? 

Also could you provide a working repo on Stackblitz ?

**Comment by maxpontreau** [comment]
Well I don’t get it.
I created a sample and
