### ISSUE TITLE
Proposal: use NgComponentOutlet in dynamic component loading guide

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#49875]
Currently, the [dynamic component loader guide](https://angular.io/guide/dynamic-component-loader) refers to the ViewContainerRef APIs directly to create a component dynamically. The `NgComponentOutlet` provides simpler APIs and we should consider updating the mentioned guide to use it instead.

Dynamic component loader guide location: https://angular.io/guide/dynamic-component-loader

We can also update the https://angular.io/api/common/NgComponentOutlet docs to do some cleanup and refer to the guide.

**Comment by JeanMeche** [comment]
Hi Andrew, I'm open to provide the updates. You can assign it to me !

**Comment by AndrewKushnir** [comment]
@JeanMeche thanks for the help!

I was looking at the existing code of the current [dynamic component loader example](https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts) and it seems like the reason why NgComponentOutlet wasn't used is that it doesn't allow passing inputs to components. There is a PR #49735 in progress, which should bring an ability to set inputs and it makes sense to land that PR first and update the guide after that.

Meanwhile, we can work on the guide using a forked version of the NgComponentOutlet which would support inputs. Here is a [Stackblitz demo](https://stackblitz.com/edit/angular-gp2ezg?file=src%2Fmain.ts) of how the example code may look like (it'd require some cleanup, applying proper CSS rules, etc). Please let me know what you think.

Thank you.
