### ISSUE TITLE
Mismatch `preserveWhitespaces` in `angularCompilerOptions` between tsconfig.app.json and tsconfig.server.json cause hydration error. 

### ISSUE THREAD

**Issue by leo6104** [angular/angular#49886]
### Which @angular/* package(s) are the source of the bug?

platform-server

### Is this a regression?

No

### Description

Follow-up issue with https://github.com/angular/angular/issues/49849 and https://github.com/angular/angular/pull/49877 

just use below markup can raise hydration error when tsconfig `preserveWhitespaces` config mismatch. 

```
<div>
  {{ test }}
</div>
```

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/7777929/232510155-3f4c633a-6219-4d36-826c-b88f1e05fe80.png">

### Please provide a link to a minimal reproduction of the bug

https://github.com/leo6104/ng-rehydrate-error-repro

### Please provide the exception or error you saw

```true
ROR Error: NG0500: During hydration Angular expected a text node but the node was not found.

Angular expected this DOM:

<app-root _nghost-ng-c1487342652="" _nghost-ng-c1611415899="">
  …
  <div>…</div>
  #text(
)  <-- AT THIS LOCATION
  …
</app-root>

Note: attributes are only displayed to better represent the DOM but have no effect on hydration mismatches.

To fix this problem:
  * check the "AppComponent" component for hydration-related issues
  * or skip hydration by adding the `ngSkipHydration` attribute to its host node in a template. Find more at https://angular.io/errors/NG0500
    at validateMatchingNode (core.mjs:14260:15)
    at locateOrCreateTextNodeImpl (core.mjs:17719:18)
    at Module.ɵɵtext (core.mjs:17693:24)
    at AppComponent_Template (app.component.html:4:1)
    at ReactiveLViewConsumer.runInContext (core.mjs:10311:13)
    at executeTemplate (core.mjs:11069:18)
    at renderView (core.mjs:10889:13)
    at renderComponent (core.mjs:12124:5)
    at renderChildComponents (core.mjs:10747:9)
    at renderView (core.mjs:10914:13)
h
```
```


### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.0-rc.0
Node: 16.19.0
Package Manager: npm 8.19.3
OS: darwin x64

Angular: 16.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0-rc.0
@angular-devkit/build-angular   16.0.0-rc.0
@angular-devkit/core            16.0.0-rc.0
@angular-devkit/schematics      16.0.0-rc.0
@angular/cdk                    16.0.0-rc.0
@angular/cli                    16.0.0-rc.0
@nguniversal/builders           16.0.0-rc.0
@nguniversal/express-engine     16.0.0-rc.0
@schematics/angular             16.0.0-rc.0
rxjs                            7.8.0
typescript                      5.0.4
```

### Anything else?

When `preserveWhitespaces` value has difference, It would be great raise warning/error to notify that `preserveWhitespaces` option between two files `tsconfig.app.json` and `tsconfig.server.json` should be same.

**Comment by jessicajaniuk** [comment]
@leo6104 Thanks for catching this. We'll start by adding it to the hydration guide, so at least there's some documentation there.

**Comment by denisyilmaz** [comment]
I am getting the same error with `&ngsp;` whilte `preserveWhitespaces` is not set in the `tsconfig.json`

**Comment by jessicajaniuk** [comment]
@denisyilmaz Can you please open another issue for that case? That would be very helpful.

**Comment by jessicajaniuk** [comment]
I've created PR #49904 to add the documentation to the hydration guide and compiler pages.

**Comment by denisyilmaz** [comment]
> @denisyilmaz Can you please open another issue for that case? That would be very helpful.

done &rarr;  #49905

**Comment by AndrewKushnir** [comment]
FYI, we've added a note about the `preserveWhitespaces` option to the hydration guide: https://next.angular.io/guide/hydration#preserve-whitespaces-configuration. We'll also be looking at other improvements related to the `preserveWhitespaces` detection, but we do not have any ETA. Closing this ticket for now.

**Comment by AndrewKushnir** [comment]
Just a quick update: there is a PR in progress (in the CLI repo) to add a warning in case the `preserveWhitespaces` option is defined in the `tsconfig.server.json`: https://github.com/angular/angular-cli/pull/25038. This should be helpful in situations that you've described originally.
