### ISSUE TITLE
How to resolve angular application version 15 while launching in Edge browser 

### ISSUE THREAD

**Issue by JKAngular** [angular/angular#49896]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

Dear Team,

While I am hosting my application in  angular version 15 it is working fine Google Chrome . But not working in  Edge browser .

### Please provide a link to a minimal reproduction of the bug

Edge browser not working for Angular 15 version

### Please provide the exception or error you saw

```true
Dear Team,

While I am hosting my application in  angular version 15 it is working fine Google Chrome . But not working in  Edge browser .
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 15.1.3
```

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by JKAngular** [comment]
what are the sufficient information you need?

Only working google chrome  your product only

But Microsoft product not working your product

like edge not working your product
