### ISSUE TITLE
When $scope is injected in a controller it appears to create dependency issues with Angular.mock.inject

### ISSUE THREAD

**Issue by micahblu** [angular/angular#4990]
For example given a controller:
```js
.controller('View1Ctrl', ['$scope', function($scope) {
}]);
``` 

and a test:
```js
describe('myApp.view1 module', function() {

	beforeEach(module('myApp.view1'));

	describe('view1 controller', function() {
		it('should ....', inject(function($controller) {
			//spec body
			var view1Ctrl = $controller('View1Ctrl');
			expect(view1Ctrl).toBeDefined();
		}));
	});
});
```
An error is given:
`Error: [$injector:unpr] Unknown provider: $scopeProvider <- $scope <- View1Ctrl`

The error is no longer present once the `$scope` injection is removed. The issue appears to be specific to `$scope` as other dependencies appear to work.

This can be quickly tested by cloning: `https://github.com/tnajdek/angular-requirejs-seed.git`
then adding the $scope injection in `app/view/view1.js` to see the error.

**Comment by ericmartinezr** [comment]
Hey @micahblu , this repo is for ng2. You are looking for this one https://github.com/angular/angular.js :+1:

**Comment by micahblu** [comment]
@ericmartinezr sorry, thanks :+1:
