### ISSUE TITLE
Using `&ngsp;` throws hydration error NG0500

### ISSUE THREAD

**Issue by denisyilmaz** [angular/angular#49905]
### Which @angular/* package(s) are the source of the bug?

platform-server

### Is this a regression?

No

### Description

Follow-up to issue #49886

With `preserveWhitespaces: false` using `&ngsp;` in the templates results in Angular throwing an error on hydration.

```html
<h1>
  <span>Example Headline</span>&ngsp;
  <span class="small">with extra Text</span>
</h1>
```

<img width="918" alt="image" src="https://user-images.githubusercontent.com/4189607/232817079-3801c1d8-e738-405c-bf4c-c518a2f0e2f4.png">

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.0-rc.0
Node: 16.15.0
Package Manager: npm 8.15.1
OS: darwin arm64

Angular: 16.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                              Version
--------------------------------------------------------------
@angular-devkit/architect            0.1600.0-rc.0
@angular-devkit/build-angular        16.0.0-rc.0
@angular-devkit/core                 16.0.0-rc.0
@angular-devkit/schematics           16.0.0-rc.0
@angular/cdk                         16.0.0-rc.0
@angular/cli                         16.0.0-rc.0
@angular/material                    16.0.0-rc.0
@angular/material-date-fns-adapter   16.0.0-rc.0
@nguniversal/builders                16.0.0-rc.0
@nguniversal/express-engine          16.0.0-rc.0
@schematics/angular                  16.0.0-rc.0
rxjs                                 7.8.0
typescript                           5.0.4
```

**Comment by AndrewKushnir** [comment]
@denisyilmaz thanks for reporting the issue.

The mentioned problem will most likely be resolved by the change in https://github.com/angular/angular/pull/49877 (also see [the test](https://github.com/angular/angular/pull/49877/files#diff-af4c8e2af18bf92515f7cb47ed0e7a8be798116a9ca5c1e15f2ba4c3aa7b79b6R2421) that was added to verify the change). Could you please try to update the `package.json` file in your application and replace the current version of the `@angular/core` with the one mentioned below (this would use a temporary created archive with the mentioned change)?

```
...
"@angular/core": "https://output.circle-artifacts.com/output/job/c84ab27c-ceac-460e-879f-16be4dd70434/artifacts/0/angular/core-pr49877-27721a5e03.tgz"
...
```

Note: you may need to use the `--force` flag during the `npm install` in case of version conflict mismatches.

Please let us know if you see a different behavior with the fix.

Thank you.

**Comment by denisyilmaz** [comment]
@AndrewKushnir great, thanks. I just updated my project and can confirm that the error message disappeared!

**Comment by AndrewKushnir** [comment]
@denisyilmaz the mentioned PR (https://github.com/angular/angular/pull/49877) is now merged and the change would be available later this week as a part of a regular pre-release version (16.0.0-rc.2) on NPM. Thank you.
