### ISSUE TITLE
Deprecated description in DOCUMENT API page

### ISSUE THREAD

**Issue by lukaonik** [angular/angular#49934]
### Describe the problem that you experienced

[DOCUMENT API](https://angular.io/api/common/DOCUMENT) has the following description:
_Note: Document might not be available in the Application Context when Application and Rendering Contexts are not the same (e.g. when running the application in a Web Worker)._
As I'm aware, using Web Worker as a rendering engine is not available anymore in Angular. So it might mislead DEVS. in SSR DOCUMENT is available with its implementation, so I think we can remove this content.

P.S I can work on that if it's a valid issue

### Enter the URL of the topic with the problem

https://angular.io/api/common/DOCUMENT

### Describe what you were looking for in the documentation

DOCUMENT API

### Describe what you want to experience that would fix the problem

remove content from the description tab

**Comment by alan-agius4** [comment]
@lukaonik, thanks for the offer to open a PR but @JeanMeche  already beat to you to it.
