### ISSUE TITLE
polyfills // bcrypt.. in fact lots of other webpackages

### ISSUE THREAD

**Issue by NoLifeVoid** [angular/angular#49933]
### Description

when going for `ng reproduction project --skip-git`

then in the cli go for: `npm i bcryptjs` or `npm i argon2`

for simplicity lets assume we use bcryptjs.

then in then app.compnent.ts go for soomething like:

`let password:string="anypasswordthatssave&5$5"`

`let salt:string=bcrypt.genSalt(10)`

`let hashedpassword=bcrypt.hashSync(password,salt)`

then in the app.component.html

`{{password}}<br>{{salt}}<br>{{hashedpassword}}`
it complains baout polyfill issues.

alike using argon2.. and plenty of other webakckes..
the solution is way beyonf my understanding of the matter.. all i understand now is that alot of compability is gone. not being able to use hashing via webpackage no more.

Any idea..about it? what i did wrong or what i can do to get bcrypt to work? because to me its seem like it has gotten so beginner unfriendly..

this problem is adressed to alot of webpackages.

My current slution is writing an has clas for my own.. but thats a horrible alternative in comparison to the benefits of using hashing webpackahed like bcrypt.

Buttomline: i just started working with angular a few month ago. In terms of an issue. i provided the steps. for me it always results in errors regarding polyfills.
I'm really looking forward to your response. There is always the option of me having misconceptions. being a beginner makes it currently really hard for me.
sadly i cannot fix the issue with what i know. also couldnt find any tutorial or reference in the angular docu i could work with.

if there is a link just anywhere.. that adresses this situation in the best possbile way even a solution. i would love to read it . please dont shut the issue down.. after i did my rerally best to provide code to reproduce the issue.  

### Proposed solution

making angular more compatiable towards webpackages

### Alternatives considered

create an inhoouse angular class for hashing and dehashing things properly.

**Comment by jessicajaniuk** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by NoLifeVoid** [comment]
this is not a support issue. it was working in earlier angular versions.
so its clearly referring to changes being made in angular 15.
thanks though, i will give stackoverflowe a chance : )
