### ISSUE TITLE
Wildcard '**' routes should run canMatch guard

### ISSUE THREAD

**Issue by alienwareone** [angular/angular#49949]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

I would expect that wildcard '**' routes would run the canMatch guard.
```
const routes: Routes = [
  { path: 'path', component: Page1, canMatch: [() => true] },
  {
    path: '**',
    component: Page2,
    canMatch: [(route: Route, segments: UrlSegment[]) => segments.toString() === 'page2']
  },
  {
    path: '**',
    component: Page3,
    canMatch: [(route: Route, segments: UrlSegment[]) => segments.toString() === 'page3']
  },
];
```
Stackblitz sample: https://stackblitz.com/edit/angular-azxep5?file=src%2Fmain.ts

### Proposed solution

Wildcard '**' should run the canMatch guard so we can register multiple wildcard routes (same behavior like the workaround bellow).
(Personally I use this for multiple slug based features without using a prefix path segment.)

### Alternatives considered

To workaround this issue we can provide a matcher that always returns.
```
const routes: Routes = [
  { path: '', component: Page1, canMatch: [() => true] },
  {
    matcher: (segments: UrlSegment[]) => ({ consumed: segments }),
    component: Page2,
    canMatch: [
      (route: Route, segments: UrlSegment[]) => segments.toString() === 'page2',
    ],
  },
  {
    matcher: (segments: UrlSegment[]) => ({ consumed: segments }),
    component: Page3,
    canMatch: [
      (route: Route, segments: UrlSegment[]) => segments.toString() === 'page3',
    ],
  },
];
```
Stackblitz sample: https://stackblitz.com/edit/angular-bg6fca?file=src%2Fmain.ts

**Comment by hamfastgamgee** [comment]
I was all set to write this up myself, too, as I just hit it today.  My case is that the business wants to be able to put marketing messages into some of their URLs with extra slashes (think <url>/landing/Happy/Birthday) so putting in a million different routes to handle this instead of just using the wildcard is extra baggage.  The workaround of using CanActivate isn't too bad, but I was surprised by the behavior.  Thanks!
