### ISSUE TITLE
angular migration 14 to 15

### ISSUE THREAD

**Issue by luis-cosillo** [angular/angular#49942]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

When migrating the MatFormFieldModule module, I placed it as legacy, and until then everything worked fine with Router.navigate, but when changing from MatLegacyInputModule to MatFormFieldModule, Router.navigate stopped working and displayed the error.
 

https://user-images.githubusercontent.com/11168170/233200658-8b8f6050-a834-4395-bc63-255b438a9c46.mp4

### Please provide the exception or error you saw

```true
error:  TypeError: (0 , s[f]) is not a function
    at $p (main.js:23:196577)
    at Yc (main.js:23:196592)
    at Pu (main.js:23:195907)
    at Fu (main.js:23:195935)
    at ov.destroy (main.js:23:228622)
    at lv.destroy (main.js:23:232828)
    at T.deactivate (main.js:23:893499)
    at ho.deactivateRouteAndOutlet (main.js:23:897067)
    at ho.deactivateRouteAndItsChildren (main.js:23:896465)
    at ho.deactivateRoutes (main.js:23:896279)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.6
Node: 18.15.0
Package Manager: npm 9.5.0
OS: win32 x64

Angular: 15.2.7
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, material-moment-adapter, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.6
@angular-devkit/build-angular   15.2.6
@angular-devkit/core            15.2.6
@angular-devkit/schematics      15.2.6
@angular/cli                    15.2.6
@angular/http                   7.2.16
@schematics/angular             15.2.6
rxjs                            7.4.0
typescript                      4.8.4
```

**Comment by atscott** [comment]
I'm sorry but we can't reproduce the problem you are reporting. We require that reported issues have a minimal reproduction that showcases the problem.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template that include info on how to create a reproduction using our template.
