### ISSUE TITLE
Improve hydration error message for invalid HTML cases

### ISSUE THREAD

**Issue by leo6104** [angular/angular#49948]
### Which @angular/* package(s) are the source of the bug?

platform-core

### Is this a regression?

No

### Description

I don't know it is error or correct error handling for Invalid DOM case. 

```
<a>
  <ng-container *ngTemplateOutlet="titleTemplate"></ng-container>
  <ng-content *ngIf="true" select="[adornment]"></ng-content>
</a>

<ng-template #titleTemplate>
  <ng-container *ngIf="true">
    <a>test</a>
  </ng-container>
</ng-template>
```

I know that it is not proper to create `a` tag in `a` tag. When i change `a` tag to `div` in each position, it has no error. 

If it is intentional hydration error, just close the issue. 😅 I just share its template case to be helpful for something angular internal logic missed. 

### Please provide a link to a minimal reproduction of the bug

https://github.com/leo6104/ng-rehydrate-error-repro/tree/ng-issue-49948

See `app.component.html` and `npm run dev:ssr` 

### Please provide the exception or error you saw

```true
in.ts:6 Error: NG0502: Hydration expected an element to be present at this location. Find more at https://angular.io/errors/NG0502
    at validateNodeExists (core.mjs:14326:15)
    at locateOrCreateContainerAnchorImpl (core.mjs:15020:18)
    at Module.ɵɵtemplate (core.mjs:14966:21)
    at AppComponent_Template (app.component.html:2:3)
    at executeTemplate (core.mjs:11074:17)
    at renderView (core.mjs:10888:13)
    at renderComponent (core.mjs:12148:5)
    at renderChildComponents (core.mjs:10747:9)
    at renderView (core.mjs:10913:13)
    at ComponentFactory.create (core.mjs:12995:13)
(
```
<img width="541" alt="image" src="https://user-images.githubusercontent.com/7777929/233315811-fc306650-3286-4fa3-80f3-f76bccb4108d.png">

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.0-rc.1
Node: 16.19.0
Package Manager: npm 8.19.3
OS: darwin x64

Angular: 16.1.0-next.0+sha-7ba01b4
... core

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1600.0-rc.1
@angular-devkit/build-angular       16.0.0-rc.1
@angular-devkit/core                16.0.0-rc.1
@angular-devkit/schematics          16.0.0-rc.1
@angular/animations                 16.0.0-rc.2
@angular/cdk                        16.0.0-rc.0
@angular/cli                        16.0.0-rc.1
@angular/common                     16.0.0-rc.2
@angular/compiler                   16.0.0-rc.2
@angular/compiler-cli               16.0.0-rc.1
@angular/forms                      16.0.0-rc.2
@angular/platform-browser           16.0.0-rc.2
@angular/platform-browser-dynamic   16.0.0-rc.2
@angular/platform-server            16.0.0-rc.2
@angular/router                     16.0.0-rc.2
@nguniversal/builders               16.0.0-rc.0
@nguniversal/express-engine         16.0.0-rc.0
@schematics/angular                 16.0.0-rc.1
rxjs                                7.8.0
typescript                          5.0.4

```

### Anything else?

It use @angular/core to https://github.com/angular/angular/issues/49929#issuecomment-1515610763 case.

**Comment by leo6104** [comment]
If the root cause of above error is Invalid DOM case from `a > a tag usage`, can we catch Invalid DOM case in hydration timing and show different message? 

The error message `Hydration expected an element to be present at this location` treat wide possibility of causes. 
it would be nice to detect these Invalid DOM case and giving other error message. 

In our project, there is two case we have invalid DOM.
- tr tag without `table > tbody` tag depth.
- a tag in a tag 

We can see above error message in same case and the runtime hydration error message didn't catch exact position of the root cause.

**Comment by AndrewKushnir** [comment]
@leo6104 thanks for the repro! I was able to confirm that this is a problem with an invalid HTML structure (in that case, `<a>` inside of an `<a>`). Valid HTML is a requirement for hydration to work (we've also mentioned that in [the guide](https://next.angular.io/guide/hydration#valid-html-dom-structure)).

We would look into improving the error message for these cases to make them more descriptive: include the name of the tag and its location, similar to other hydration mismatch errors (I'll reflect that in the ticket title).

We will also discuss how we can improve this further, but this would happen outside of the context of this ticket.

Thank you.

**Comment by AndrewKushnir** [comment]
Closing this ticket, since the PR https://github.com/angular/angular/pull/49977 (which improves the error message) was merged.
