### ISSUE TITLE
[question] setError on a control removes the validator errors. Is this desired behaviour?

### ISSUE THREAD

**Issue by Krustie101** [angular/angular#4995]
It is a good idea that setting the errors property of a control overrides the errors that arose from the validator? I presume the underlying reasoning is that the manual validation should not have been performed because the control contained a validator error so it does not make a difference.

But what if you have a numeric input with a maxValue validator and there are some other controls in the form and depending on their values, a min value constrained kicks in. I might try to write a validator for this or I might conclude that a manual validation (before submit?) is more appropriate in this case. Then any max value error (message) is lost if the min value constraint is not satisfied.

Not overriding the errors arising from the validator in the control case (combined with clearing of manual errors if the value is updated) would also be more consistent with the group/array behaviour.

Even simpler, a developer can clear all the errors (validator & manual) of a control by calling setError(null). This seems strange.

**Comment by vicb** [comment]
related to the deprecated form module
