### ISSUE TITLE
Angular 15 Not working in Edge 11 

### ISSUE THREAD

**Issue by JKAngular** [angular/angular#49963]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

I have developed one Angular 15 application .After that I have deployed in server But it is working Google Chrome.

Not working in Edge 11

### Please provide a link to a minimal reproduction of the bug

Edge browser not working for Angular 15 version

### Please provide the exception or error you saw

```true
Nothing shows Console and network tab
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI 15.1
```

**Comment by JeanMeche** [comment]
Hi, 

Angular v15 only support everygreen browsers. So pre-chromium Edges are not supported. 

Please have a look at [this documentation page](https://angular.io/guide/browser-support).

**Comment by JoostK** [comment]
By the way, Edge 11 is not a thing as far as my search revealed.

**Comment by JeanMeche** [comment]
By the way, there is no Edge 11. IE 11 was followed by Edge 12. 

IE support was dropped on IE13. You'll have to use Angular v12 if you want to support IE.
