### ISSUE TITLE
angular2.dev.js:4045 Uncaught TypeError: m.values is not a function

### ISSUE THREAD

**Issue by danijar** [angular/angular#4997]
Hi,

the Angular 2 quickstart guide is not working for me. I get the error message with both alpha 44 and 45. The webpage shows `loading...` and the template is not rendered. There is just this single error in the JavaScript console.

    angular2.dev.js:4045 Uncaught TypeError: m.values is not a function

I copied exact folder structure and HTML and TS snippets. `npm start` and `npm run tsc` are running.

Am I doing something wrong or is this a problem with the current beta?

**Comment by ericmartinezr** [comment]
Add `es6-shim` to your index.html

See https://github.com/angular/angular/issues/4751

**Comment by vicb** [comment]
@ericmartinezr is right, the browser you use probably does not support ES6 maps and you need a polyfill.

**Comment by danijar** [comment]
Okay, thanks. It works after running `npm install es6-shim` and including `<script src="../node_modules/es6-shim/es6-shim.js"></script>` in the index.html. Maybe that's worth adding to the quickstart guide?

**Comment by wardbell** [comment]
What browser were you using? Shame on me for only testing in Chrome.

**Comment by danijar** [comment]
I'm using the newest stable Chrome release.

**Comment by JeffMichelson** [comment]
Doesn't work in IE11 either.
