### ISSUE TITLE
<tr> elements are empty while using canonical *ng-for syntax inside <table>

### ISSUE THREAD

**Issue by alexpods** [angular/angular#4998]
See [this plunker](http://plnkr.co/edit/gwGKNQhtrnyEVgsTFeHU?p=preview). I have the next template:
```html
<table>
  <template ng-for #foo [ng-for-of]="foos">
    <tr>first level tr</tr>
    <template ng-for #bar [ng-for-of]="foo.bars">
      <tr>same level as above tr</tr>
    </template>
  </template>
</table>
```
As you can see in plunker `<tr>` s are empty and their contents are rendered outside of them.

 All works fine If I use `<div>`s instead of `<table>` and `<tr>`s. See [this plunker](http://plnkr.co/edit/gwGKNQhtrnyEVgsTFeHU?p=preview)

**Comment by vicb** [comment]
`<tr>`  content could only either be `td` or `th`. See http://www.w3.org/TR/html-markup/tr.html

**Comment by pkozlowski-opensource** [comment]
@vicb you are right, but it sounds like a legit use-case (iterating over sibling `<tr>`s). IMO we need to support this one way or another...

**Comment by todoubaba** [comment]
It works in chrome, maybe @alexpods use IE or Edge, see https://github.com/angular/angular/issues/4830

**Comment by pkozlowski-opensource** [comment]
Right, new compiler (which is not browser-DOM-walking based) should indeed solve this. Let's track the issue as part of #4830 then

**Comment by vicb** [comment]
@pkozlowski-opensource I don't get what you mean here ? is there anything we can "solve" here ? even if we can parse the text node as a child of the tr with the new compiler the output would remain invalid html.

**Comment by todoubaba** [comment]
Use <td></td> wrap the text, see: http://plnkr.co/edit/wjGQ5t6QbF5MGllYKXjs?p=preview

**Comment by alexpods** [comment]
@vicb you're absolutely right. Sorry for being too lazy to check standards before making a fuss :(
