### ISSUE TITLE
Angular `next` should be tagged as `v3.42.0`

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular#49985]
### Description

Since Angular 4, Angular's versioning scheme is very consistent.

For inconsistency's sake, it would nice to fill the gap of Angular 3 with a `v3.0.0` dist tag as an alias for `next`.
Now, given that this would be confusing with `@angular/router@3.0.0`, it would be more intuitive to figure out a more unique dist tag like `v3.42.0`

### Proposed solution

Tag Angular `next` version as `v3.42.0` which would be for Angular, what Sid is for Debian.
The main advantage of this approach is that there are fewer letters to type.

### Alternatives considered

Do not tag Angular `next` version as `v3.42.0` and close this issue before it gains any momentum.

**Comment by alan-agius4** [comment]
Hi @yjaaidi, the `next` tag is currently pointing to the `16.0.0-rc.2`, this tag points to the currently pre-release version and changes every week. 

Are you by any chance referring to the lts tags? IE: `v13-lts`. Overall, any version before 13 are no longer supported and are not guaranteed to work. My 2 cents would be not to add the dist tag as no one should be installing these.

**Comment by yjaaidi** [comment]
Hey Alan! This was just a joke referring to this https://twitter.com/yjaaidi/status/1650485871286648833?s=46&t=jB5pO7bwe3f1jMyVgErJWQ

Sorry for the noise 😉
