### ISSUE TITLE
Custom bundle generated by System.js builder not working.

### ISSUE THREAD

**Issue by majo44** [angular/angular#4999]
I created very simple project setup over system.js loader for, on one side load the application and libraries (angular2) from sources (js sources) and on second side, generate custom application bundle by system.js builder.  I'm using the same configuration:

```
System.config({
    baseURL: ".",
    defaultJSExtensions: true,
    paths: {
        "app*" : "src/app*",
        "angular2*" : "node_modules/angular2*.js",
        "zone.js*" : "node_modules/zone.js/lib/*.js",
        "reflect-metadata*" : "node_modules/reflect-metadata*.js",
        "@reactivex*" : "node_modules/@reactivex/*.js",
        // This is for fixing problem of "isNode" in ng2
        "crypto*" : "fix/crypto*.js"
    }
});
```

for loading the app from sources, and the same configuration is provided to builder.

When application is loading from sources, everything works fine. But in case when I'm loading bundles to browser there are some problems.  I'm trying to use two system.js builder paths

* build just the bundle, in this case application runs but throws Maximum call stack size exceeded,
* generate sfx in this case application doesn't starts, ant there is "Token must be defined!" exception.

The general motivation for such configuration is to generate bundles which contains exactly what app needs (by es6 modules dependencies). Such solution also supports to split application to few bundles, and lazy load modules on demoed.

Repo with whole setup: https://github.com/majo44/angular2-systemjs-builder

**Comment by pkozlowski-opensource** [comment]
@majo44 we still didn't figure out completely our bundling / distribution story so I'm afraid we can't help much with specific setups at the moment. I'm afraid that you will have to dig into it on your end till this problem space stabilizes and we've got more recommendations in this area.

Closing for now, but feel free to re-open if you believe that we've got anything to fix on the ng2 side to make your workflow workable.
