### ISSUE TITLE
Some schematics (PWA) are not compatible with standalone application

### ISSUE THREAD

**Issue by montella1507** [angular/angular#50001]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

1) new solution in NX - standalone components
2) nx add @angular/pwa 

Error:
SchematicsException [Error]: Bootstrap call not found
    at findBootstrapModulePath

Schematics are probably NOT compatible with standalone components - application
=> Trying to bind "bootstrap()" function

**Comment by JeanMeche** [comment]
Hi,

The Nx CLI is made by [Nrwl/nx](https://github.com/nrwl/nx), you should repport that issue to them.

**Comment by alan-agius4** [comment]
These issues been fixed in Angular version 16 which is currently in prerelease.
