### ISSUE TITLE
Some localization pages don't open in firefox

### ISSUE THREAD

**Issue by varun-abine** [angular/angular#50013]
### Describe the problem that you experienced

I am trying to localize an app but can't seem to get these pages open on firefox
https://angular.io/guide/i18n-common-locale-id
https://angular.io/guide/i18n-common-prepare
https://angular.io/guide/i18n-common-format-data-locale
There are a few more haven't checked the full extent

### Enter the URL of the topic with the problem

https://angular.io/guide/i18n-common-prepare#mark-plurals

### Describe what you were looking for in the documentation

i18n mark plurals

### Describe the actions that led you to experience the problem

I wanted to internationalize an app but can't access these pages on firefox works fine on chrome.

### Add a screenshot if that helps illustrate the problem

![image](https://user-images.githubusercontent.com/122767160/234584989-003f1b6e-efeb-49a6-a934-4488e86967df.png)

### If this problem caused an exception or error, please paste it here

```true
Uncaught ReferenceError: assignment to undeclared variable s_om
    <anonymous> Angular
```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Firefox browser 112.0.1 64-bit ubuntu
```

**Comment by JeanMeche** [comment]
Hi, 

Do you have any extensions installed on your Firefox ?

**Comment by JeanMeche** [comment]
I could not reproduce you issue on 112.0.2 on Windows. 

Did you try disable your extensions  ?

**Comment by JeanMeche** [comment]
By curiosity, which one is causing the issue  ?

**Comment by varun-abine** [comment]
Ironvest, password manager, a privacy extension

**Comment by pkozlowski-opensource** [comment]
Good to hear that the culprit was identified!
