### ISSUE TITLE
After upgrading to angular15, only the scroll callback is used to monitor router.event

### ISSUE THREAD

**Issue by my5201314zwl** [angular/angular#50010]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

```ts
const routes: Routes = [{
  path: '', component: AppComponent, children: [
    { path: 'test1', component: Test1Component, data: { title: '1123' } }]
},
];
```

Inject the router in Test1Component, refresh the page only scroll callback.
Before the previous angular14 version, there would be callbacks such as ActivationEnd and NavgationEnd.
Now it is also impossible to get the data value in the sub-routing.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.4
Node: 16.14.0
Package Manager: npm 8.3.1
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1502.4 (cli-only)
@angular-devkit/core         15.2.4 (cli-only)
@angular-devkit/schematics   15.2.4 (cli-only)
@schematics/angular          15.2.4 (cli-only)
```

**Comment by JoostK** [comment]
I updated the report with Google Translate's translation, but I am afraid even then this issue is non-actionable due to missing details.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

it sounds likely this is the documented breaking change found here https://angular.io/guide/update-to-version-15#routeroutlet-instantiates-the-component-after-change-detection
