### ISSUE TITLE
'TransferState' refers to a value, but is being used as a type here. Did you mean 'typeof TransferState'?

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular#50014]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

Yes

### Description

I tested components with new version of angular and found that I have an error when try to serve or build app.
The error: "'TransferState' refers to a value, but is being used as a type here. Did you mean 'typeof TransferState'?"
I see that TransferState is deprecated in platform-browser but it looks like BC (not deprecated). Now I can't update my library to 16 angular and need use 14 or 15 angular

### Please provide the exception or error you saw

```true
The error: "'TransferState' refers to a value, but is being used as a type here. Did you mean 'typeof TransferState'?"
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: next
```

**Comment by alan-agius4** [comment]
No need for a reproduction, I know that is happening here and I should have a fix for this soonish.
