### ISSUE TITLE
Missing Step in Tour of Heroes Tutorial - "npm init -y" after cloning angular2-quickstart

### ISSUE THREAD

**Issue by sambuchl** [angular/angular#5005]
I may be wrong, but I believe there's a missing step at the beginning of the Tour of Heroes tutorial.

After you've cloned the Quickstart directory, you also need to run the "npm init -y" again in the new new Tour-of-Heroes directory to create the new package.json file.

**Comment by pkozlowski-opensource** [comment]
@sambuchl could you please move it over to https://github.com/angular/angular.io where the tutorial lives? Thnx!

**Comment by sambuchl** [comment]
Will do! Thanks for the redirect.
