### ISSUE TITLE
make docs contributions easier (more intuitive)

### ISSUE THREAD

**Issue by Sammeeey** [angular/angular#50075]
### Describe the problem that you experienced

It's great that you have the opportunity to contribute to each page of the docs directly!
I love this & I believe that every great open source project should have something like this.

Even though I've wanted to change a page & have been looking for such a button, I didn't find it.
(So I already started to write an issue to suggest that feature.)
![grafik](https://user-images.githubusercontent.com/49591562/235294637-b8974896-f6e6-4b97-8379-83cef6237b01.png)

This *edit* button is super small and only at the top of the page (where you usually don't want to edit anything.
I'd love to have it bigger, more prominent & maybe sticky somewhere at the bottom of the screen or below the navigation on the right.

And let's maybe even add a *call to action*, like they do it at [docker](https://docs.docker.com/get-started/).
I love that you always see it.
Once you stumble upon a typo or a bug, you'll intuitively report it that way.
And not just having the chance to *edit* a page directly but also having the opportunity to *request a change* (aka. filing an issue to discuss a change) makes it way easier for people to add their ideas and to help improve Angular.🤗
![grafik](https://user-images.githubusercontent.com/49591562/235294848-2244e6ff-0925-4bb9-ac00-7a6536126dac.png)

**Comment by JeanMeche** [comment]
Hi,

A similar issue has already been raised in #48865.

**Comment by pkozlowski-opensource** [comment]
Yes, let's centralize the discussion in https://github.com/angular/angular/issues/48865.
