### ISSUE TITLE
Provide an alternative to `ComponentFixtureNoNgZone` + `ɵNoopNgZone `

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular#50079]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

While there is no official support for Zoneless apps or Zoneless testing, some public APIs are available and other internal APIs are getting used in the wild:

`ComponentFixtureNoNgZone` is undocumented but part of the public API.
I might be missing something but it could be derived from the injected `NgZone` _(if `NgZone` is null or instead of `NoopNgZone` for example)_. Cf.:
https://github.com/angular/angular/blob/02a539cb1420d1941a0bbc79e9110cfc347737b5/packages/core/testing/src/test_bed.ts#L601-L603

In order to provide a no-op NgZone in standalone apps or testing, the common workaround is using the following provider:
```ts
{provide: NgZone, useClass:  ɵNoopNgZone}
```
but `ɵNoopNgZone` is internal API.

### Proposed solution

- Derive `noNgZone` state from the injected `NgZone`.
- Expose `NoopNgZone` as public API _(after all it has the same interface as `NgZone` which is already public so in practice, it will probably never change if `NgZone` doesn't change, but! it could disappear if rendered useless in the future)_
or
_provide_ a `provideNoopNgZone()` function which will probably become useless when Zoneless Angular will happen.

### Alternatives considered

Expose a copy of `NoopNgZone` + some provide functions in an external library

**Comment by alxhub** [comment]
Zoneless testing is a part of the ongoing zoneless effort for the framework. I'm going to close this issue as:

1. We don't want to expand support for `NoopNgZone` at this point.
2. We don't need a separate tracking issue for zoneless in testing.
