### ISSUE TITLE
toSignal(): add destroyRef argument

### ISSUE THREAD

**Issue by e-oz** [angular/angular#50085]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

`toSignal()` must be called in an injection context.

As an alternative, please allow users to send a `destroyRef` argument.

### Reasoning
Suppose your service has some observables, and you would like to create signals as well to allow users to select what they want to use. To do this, you need to call `toSignal()`, which is relatively straightforward. However, it will immediately subscribe to an observable. Therefore, if you want to create signal-based fields for every observable-based field, you will subscribe to all of them instantly.

To prevent this and only subscribe to observables when necessary, you may want to use getters. However, there is no guarantee that getters will be called in an injection context, and it is impossible to use `injector.runInContext()` in this case.

### Proposed solution

It would be possible if we could call `toSignal()` this way:

```ts
  private readonly destroyRef = inject(DestroyRef);

  public get items(): Signal<T[]> {
    return toSignal(this.items$, {initialValue: [] as T[], destroyRef: this.destroyRef});
  }

  public get totalCountFetched(): Signal<number | undefined> {
    return toSignal(this.totalCountFetched$, {initialValue: undefined, destroyRef: this.destroyRef});
  }
```

### Alternatives considered

If there are any workarounds, please let me know.

**Comment by JeanMeche** [comment]
Wouldn't you want your signals be in the component in that case and only use observables in your service ?

**Comment by atscott** [comment]
This has already been addressed in https://github.com/angular/angular/commit/cc89766ceee430631a0a8d67e444b2ed51bf7a83 and will be included in the next release.

**Comment by e-oz** [comment]
thank you! yay 🎉
