### ISSUE TITLE
Language Service should suggest keyboard modified when using keyboard event bindings

### ISSUE THREAD

**Issue by vneogi199** [angular/angular#50081]
### Which @angular/* package(s) are relevant/related to the feature request?

language-service

### Description

From the docs for [binding to keyboard events](https://angular.io/guide/event-binding#binding-to-keyboard-events), it is possible to use key and code from Keyboard Event to target specific keyboard events like the following:`<input (keydown.shift.t)="onKeydown($event)" />`

This is not suggested by the language service currently. It only suggests events like keyup, keydown, keydown but doesn't suggest using these modifiers on typing `(keydown.)`

<img width="778" alt="image" src="https://user-images.githubusercontent.com/20491952/235317503-22b66e9c-13d3-4f85-a094-06b807136229.png">

### Proposed solution

Language Service should suggest modifiers like shift, enter, alt and other key/code from KeyboardEvent so that users can get autocomplete and also prevent typos

### Alternatives considered

Use keyboard modifiers without autocomplete with potential for incorrect usage/typos

**Comment by JeanMeche** [comment]
Hi, 

Key modified events are a feature introduced by the `KeyEventsPlugin` a plugin for `EventManager`. 

If think this issue fall under #40553.

**Comment by JoostK** [comment]
Let's indeed continue tracking this in #40553.
