### ISSUE TITLE
Docs : "See also" links are not always links. 

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular#50097]
### Describe the problem that you experienced

The API documention is very inconsistant about the handling of the "See also" sections. 

This is handled by the `@see` jsdoc tag. 

In the codebase we have several usages with different results : 

1. 
https://github.com/angular/angular/blob/1bc3546c7f99466d3ac57bf06cacb3dc645c0f48/packages/common/http/src/provider.ts#L58-L63

Here the code a navigable in IDEs but not in [the documentation](https://v15.angular.io/api/common/http/provideHttpClient). 

2.

https://github.com/angular/angular/blob/1bc3546c7f99466d3ac57bf06cacb3dc645c0f48/packages/core/src/metadata/di.ts#L78-L81

Here the code is not navigable in IDEs but is in [the documentation](https://v15.angular.io/api/core/Query#see-also).

3.
https://github.com/angular/angular/blob/1bc3546c7f99466d3ac57bf06cacb3dc645c0f48/packages/core/src/change_detection/constants.ts#L14
Here the code is navigable in both IDEs and [the documentation](https://v15.angular.io/api/core/ChangeDetectionStrategy)

----

I propose we migrate step by step the inline documentation to using `@link` to ensure code and online documentation stay navigable. 

This issue will be used to link the several PRs that improve that topic.

**Comment by Naaajii** [comment]
ello @JeanMeche, I can help you if theres any remaining of changes left, lemme know!

**Comment by JeanMeche** [comment]
Hi, thanks for your help !
You can check what's left after #50110 is merged 👍

**Comment by devversion** [comment]
@JeanMeche regarding case 1: It seems like I can click on e.g. `withInterceptors`. Do I miss something? 

> Here the code a navigable in IDEs but not in [the documentation](https://v15.angular.io/api/common/http/provideHttpClient).

**Comment by JeanMeche** [comment]
This one got fixed by #50098 !

Check this one for example : https://angular.io/api/router/IsActiveMatchOptions#see-also
