### ISSUE TITLE
ready-made sample project in StackBlitz: Failed to run start command

### ISSUE THREAD

**Issue by Dou1622** [angular/angular#50099]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Angular - Docs - Getting Started - Try it - Getting Started - Create the sample project - [ready-made sample project in StackBlitz](https://angular.io/generated/live-examples/getting-started-v0/stackblitz.html)

After loading the page, it showed "**Failed to run start command"** with  a following error:
`~/projects/dztar2--run
❯ ng update
Unknown error: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/projects/dztar2--run/node_modules/cliui/node_modules/string-width/index.js from /home/projects/dztar2--run/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /home/projects/dztar2--run/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.`

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Browser: Firefox Web Brower 112.0.1 (64-bit), and Google Chrome Version 112.0.5615.165 (Official Build) (64-bit)
OS: Ubuntu 22.04.2 LTS (64-bit)
```

**Comment by alan-agius4** [comment]
HI @Dou1622, 

I am unable to replicate the mentioned issue. 
<img width="2228" alt="Screenshot 2023-05-02 at 11 07 21" src="https://user-images.githubusercontent.com/17563226/235626055-c618f892-3cfd-4a5a-82cd-db758dfb0f21.png">

**Comment by Dou1622** [comment]
> HI @Dou1622,
> 
> I am unable to replicate the mentioned issue. <img alt="Screenshot 2023-05-02 at 11 07 21" width="2000" src="https://user-images.githubusercontent.com/17563226/235626055-c618f892-3cfd-4a5a-82cd-db758dfb0f21.

It works fo r me now.  Thank you.
