### ISSUE TITLE
Parse HTML templates to extract stubs from expressions & statements, then generate getters/setters stubs for reflection

### ISSUE THREAD

**Issue by mhevery** [angular/angular#501]
Depends on #503

HTML Templates contain expressions and statements. These need to be extracted so that we can generate getters and setter stubs (in subsequent iteration we can generate ChangeDetection classes which are more efficient #502) 

Given HTML such as:
```
{{list.name}}
<ul>
  <li template="for: var i in items">{{item.description}}</li>
</ul>
```

Should generate these getters:
```
reflector.registerGetter({
  "list": (o) => o.list,
  "name": (o) => o.name,
  "items": (o) => o.items,
  "item": (o) => o.item,
  "description": (o) => o.description,
});
```

Angular already has a parser which can extract all of the getters from the template. The parser is part of the Angular [`Compiler`](https://github.com/angular/angular/blob/master/modules/core/src/compiler/compiler.js). Which consumes template and generates [`ProtoView`](https://github.com/angular/angular/blob/master/modules/core/src/compiler/view.js#L247). The `ProtoView` contains [`ProtoChangeDetector`](https://github.com/angular/angular/blob/master/modules/change_detection/src/proto_change_detector.js) which in turn contains [`ProtoRecord`](https://github.com/angular/angular/blob/master/modules/change_detection/src/proto_change_detector.js). The `ProtoRecord` contains `name` field which corresponds to the getter.

The transformer needs to pass the template through the compiler and then iterate over the `ProtoRecord`s to collect all of the getters.

NOTE: The compiler works on DOM API. In order to execute outside the browser we need to create DOM facade so that it can execute in the transformer. See #503.

NOTE: The above example does not have type information added, but such information can be extracted and added in subsequent improvements.

**Comment by kegluneq** [comment]
Closed by 08b56e1c532d23120cdcc86f2fd95de29271bc91
