### ISSUE TITLE
`toSignal()` can not be called inside `computed()`

### ISSUE THREAD

**Issue by e-oz** [angular/angular#50106]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

`toSignal()` can not set internal state ([`state.set()`](https://github.com/angular/angular/blob/main/packages/core/rxjs-interop/src/to_signal.ts#L177) when called from `computed()`, because of NG0600 ("Writing to signals is not allowed in a `computed` or an `effect` by default").

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-hjphb7?devToolsHeight=33&file=src/main.ts

### Please provide the exception or error you saw

```true
ERROR
Error: NG0601: `toSignal()` called with `requireSync` but `Observable` did not emit synchronously.

ERROR
Error: NG0600: Writing to signals is not allowed in a `computed` or an `effect` by default. Use `allowSignalWrites` in the `CreateEffectOptions` to enable this inside effects.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular/core 16.0.0-rc.4
```

### Anything else?

It is reproducible without Component's template, so the issue is not caused by the template: https://stackblitz.com/edit/angular-rbp4uq?devToolsHeight=33&file=src/main.ts

**Comment by pkozlowski-opensource** [comment]
This is by design - the `computed` function should be a simple, pure computation. In this sense the error catches a scenario which we explicitly don't think should be possible.

Having said this I would be curious to hear more about your use-case, specific tasks that you are trying to cover.

**Comment by pkozlowski-opensource** [comment]
Obviously you can always do https://stackblitz.com/edit/angular-hvbbhq?devToolsHeight=33&file=src%2Fmain.ts

**Comment by e-oz** [comment]
I like the design aspect where `compute()` doesn't allow modifying Signals.

I use `compute()` for a simple, pure computation. It's not my "sin" that `toSignal()` uses a Signal under the hood and tries to modify it. It should return a Signal, and this Signal I want to use inside the `computed()` - just to read it, for a simple pure computation.

### My use-case

I have a library, [ngx-collection](https://github.com/e-oz/ngx-collection) (kind of a plugin for NgRx to manage the collections).

It has a lot of observables](https://github.com/e-oz/ngx-collection/blob/main/libs/ngx-collection/src/lib/collection.service.ts#L133)(17), users are supposed to pick just a few of them to use what is needed.

I want to provide signal-based alternatives for every observable. It is better to do this from my side, to don't make users think about things like initial value and injection context.

If I will use `toSignal()` in the field declaration, then it will instantly subscribe to the observable. So I will have 17 subscriptions, and maybe just a couple of them will be actually used.

To avoid that, I use getters:

```ts
export class CollectionService {
  // ...

  public get updatingItems(): Signal<T[]> {
    return toSignal(this.updatingItems$, {initialValue: [] as T[], injector: this.injector});
  }

  public get deletingItems(): Signal<T[]> {
    return toSignal(this.deletingItems$, {initialValue: [] as T[], injector: this.injector});
  }

  public get mutatingItems(): Signal<T[]> {
    return computed(() => ([
      ...this.updatingItems(),
      ...this.deletingItems()
    ]));
  }

  // ...
}
```

As you can see, I do not set any Signals inside the `computed()`, and computation here is pure and simple :)

If I go this way:

```ts
  public get mutatingItems(): Signal<T[]> {
    return toSignal(this.mutatingItems$, {initialValue: [] as T[], injector: this.injector});
  }
```

then by the signature, I'm providing a Signal, and everything is fine... until the user will try to use this signal inside the `computed()` or `effect()` (and maybe even in a template).

If I go this way:

```ts
public readonly updatingItems = toSignal(this.updatingItems$, {initialValue: [] as T[], injector: this.injector});
```

then I'll have 17 subscriptions "just in case".

---

My main idea is: calling `signal.set()` inside the `toSignal()` is limiting its usage.

**Comment by pkozlowski-opensource** [comment]
> As you can see, I do not set any Signals inside the computed(), and computation here is pure and simple :)

The `toSignal()` operation is _not_ pure - as you've noted it setups subscription etc.

**Comment by e-oz** [comment]
> This is one of the fundamental differences between signals and Observables

I'm pretty much aware, it's one of the tradeoffs.

> a signal always needs a value so in this sense it can not be "lazy"

I don't want them to be "lazy", I just want to create them only when it's needed.

> I'm not familiar with the library in question to say which approach is the best

None of them, unfortunately, otherwise I wouldn't have created this issue. But still, thank you for your time and ideas. I'll keep looking for a workaround.

**Comment by e-oz** [comment]
Just in case, all you would need to change is this:
```ts
    next: value => () => state.set({kind: StateKind.Value, value}),
    error: error => () => state.set({kind: StateKind.Error, error}),
```
to this:
```ts
    next: value => untracked(() => state.set({kind: StateKind.Value, value})),
    error: error => untracked(() => state.set({kind: StateKind.Error, error})),
```
😉

**Comment by pkozlowski-opensource** [comment]
You can certainly cache signals returned from the `toSignal` invocations. At this point we don't want to change the `toSignal` implementation - signal instances need to have a value and should be initialized with one - even if converting from observables. Reading signals should be side-effects free, otherwise it becomes less predictable and harder to reason about.

Thnx for sharing the use-case though!
