### ISSUE TITLE
Router: Clicking on [router-link] directives bypasses native 'onHashChange' events

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#5013]
This makes it impossible for third-party code (not aware of Angular) to know when the route has changed. Honestly, I'd prefer for [router-link] to go entirely away or be optional. It's a lot easier and more portable to use plain `<a href="...">` and instead have the router deal with understanding those.

For example, [router-link] only supports clicks. Not keyboard.

**Comment by btford** [comment]
There are two parts to this:

1. Bugs in the behavior of `[router-link]`
2. Intercepting link clicks for external 3rd party code.

For 2, I think it makes more sense for your application to implement a directive. But if you don't have the option to compile the 3rd party code, then intercepting hashchange events makes sense. Again, not sure this makes sense for all Angular apps, you might have to add a listener and add this to routing your self.

We chatted about this in the past, but I'm still thinking through the ideal solution. I'll start work in earnest on this next week.

**Comment by wekiel** [comment]
Hi, Brian, we can't do this via a directive. We need something that works on a global scale (it's not reasonable to track down all required places and add such directive), and also that will notify us when the URL change is done by parts of the app that aren't managed by Angular. 

What we need is for the ng2 router to work seamlessly with the onhashchange, just like the ng1 router does right now: https://github.com/angular/route.dart/blob/master/lib/client.dart

**Comment by btford** [comment]
To be clear, yes, there will be the option to intercept this event seamlessly for your use case. It's just that the router also needs to support other cases as well.

**Comment by btford** [comment]
I just landed a change for the third option in master.

**Comment by matanlurey** [comment]
Thank you guys! :+1:
