### ISSUE TITLE
Parser is not recognizing the "for" attribute

### ISSUE THREAD

**Issue by manekinekko** [angular/angular#5014]
Hi, I'm using alpha-45.
I'm having an issue when using a "label" element with a "for" attribute. Here is the template snippet:
```html
     <li *ng-for="#choice of question?.choices" >
        <label for="switch-{{ index }}" for="switch-{{ index }}">
          <input  type="checkbox" 
                  id="switch-{{ index }}"
                  [checked]="choice.checked"
                  (change)="onCheckedChange($event, choice)"/>
        </label>
      </li>
```

Here is the component definition:

```javascript
@Component({
	selector: 'question-card',
	templateUrl: './components/technology/question-card/question-card.html',
	directives: [NgFor, FORM_DIRECTIVES]
})
```
Am I missing something?

Here is the exception I get:
![image](https://cloud.githubusercontent.com/assets/1699357/10833159/404b6b7c-7e90-11e5-8f01-2d4b650a76e1.png)

**Comment by pkozlowski-opensource** [comment]
for is an attribute, not a property. Try binding to [attr.for]

**Comment by manekinekko** [comment]
Great! Thanks Pawel. 

Indeed, I should bind to attributes like so:
```html
<li *ng-for="#choice of question?.choices; #i = index" >
    <label [attr.for]="'index-'+i" >
   ...
```
