### ISSUE TITLE
What happened with generic ControlValueAccessor / Validator ?

### ISSUE THREAD

**Issue by montella1507** [angular/angular#50146]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

Hi, what happened with this pull request / feature?

https://github.com/angular/angular/pull/31801

### Proposed solution

Allow generic ControlValueAccessor again.

### Alternatives considered

I dont know if there is another way how to type a value which is accepted by ngModel / formControl directives etc..

**Comment by montella1507** [comment]
To have strongly typed [formControl][formControlName] etc.

**Comment by JoostK** [comment]
There is no type-level association between a `FormControl` and the backing `ControlValueAccessor`, so only changing `CVA` to accept a generic type argument is unsound. Improvements in the area of type-safety around `CVA` is being tracked in #45968.
