### ISSUE TITLE
Injector.create to return EnvironmentInjector

### ISSUE THREAD

**Issue by Harpush** [angular/angular#50157]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Currently using `Injector.create` returns `Injector` which is actually `R3Injector` which is `EnvironmentInjector`.
To allow destroying this new injector it must be casted to `EnvironmentInjector`. Some cases require it to allow dynamic injectors creation and destruction.

### Proposed solution

Return `EnvironemtInjector` directly to eliminate the casting.

### Alternatives considered

Cast it myself or maybe this is not the desired behavior?

**Comment by JeanMeche** [comment]
You should consider using `createEnvironmentInjector` if you want a `EnvironmentInjector`.

**Comment by Harpush** [comment]
> Hi, You should consider using `createEnvironmentInjector` if you want an `EnvironmentInjector`.

Oh nice didn't know it exists. Is there any difference though? Seems it uses `NgModuleRef` and view engine stuff inside.

**Comment by AndrewKushnir** [comment]
> Oh nice didn't know it exists. Is there any difference though? Seems it uses NgModuleRef and view engine stuff inside

@Harpush more information about EnvironmentInjectors can be found at: https://angular.io/guide/standalone-components#dependency-injection-and-injectors-hierarchy.
