### ISSUE TITLE
Updating a signal outside zone.js triggers no effect

### ISSUE THREAD

**Issue by divdavem** [angular/angular#50160]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

In the following very simple example, the template stays forever with `mySignal = 0`. I would expect the template to be updated every second.

```ts
import 'zone.js/dist/zone';
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';

const mySignal = signal(0);
setInterval(() => {
  mySignal.update((value) => value + 1);
  console.log('updating signal ' + mySignal());
}, 1000);

@Component({
  selector: 'my-app',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    mySignal = {{ mySignal() }}
  `,
})
export class App {
  mySignal = mySignal;
}

bootstrapApplication(App);
```

Note that the template is correctly updated every second if I move the code that updates the signal to the constructor of the component, like this:

```ts
import 'zone.js/dist/zone';
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';

const mySignal = signal(0);

@Component({
  selector: 'my-app',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    mySignal = {{ mySignal() }}
  `,
})
export class App {
  mySignal = mySignal;
  constructor() {
    setInterval(() => {
      mySignal.update((value) => value + 1);
      console.log('updating signal ' + mySignal());
    }, 1000);
  }
}

bootstrapApplication(App);
```

I find this difference in the behavior very confusing.
Is zone.js still playing a role in this case? It looks like updating a signal outside zone.js does not trigger any effect...

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-bd1auk?file=src/main.ts

### Please provide the exception or error you saw

```true
There is no exception.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.0
Node: 18.15.0
Package Manager: npm 9.5.0
OS: linux x64

Angular: 16.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0
@schematics/angular             16.0.0
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by JoostK** [comment]
This is working as designed for now; signals only mark a component for check and schduling change detection is still done using zone.js.

Full signal components are yet to be implemented.

**Comment by divdavem** [comment]
@JoostK Thank you for your answer. I also thought this is a temporary implementation.

Note that even effects are not triggered:
```
import 'zone.js/dist/zone';
import { ChangeDetectionStrategy, Component, effect, signal } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';

const mySignal = signal(0);
setInterval(() => {
  mySignal.update((value) => value + 1);
  console.log('updating signal ' + mySignal());
}, 1000);

@Component({
  selector: 'my-app',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    mySignal = {{ mySignal() }}
  `,
})
export class App {
  mySignal = mySignal;
  constructor() {
    effect(() => {
      // This is not executed when a signal changes outside zonejs
      console.log("effect mySignal = " + mySignal());
    });
  }
}

bootstrapApplication(App);
```

**Comment by JeanMeche** [comment]
Yes, it's also linked. `EventManager.flush()` is called by the global change detection (AppRef.tick => detectChange()) .

**Comment by alxhub** [comment]
(as others have mentioned, this is by design for zoneful applications - change detection must still be triggered by zones)

**Comment by alxhub** [comment]
(as others have mentioned, this is by design for zoneful applications - change detection must still be triggered by zones)
