### ISSUE TITLE
Angular 15: Interpolation binding throws JIT Compiler exceptions in the console

### ISSUE THREAD

**Issue by fahadash** [angular/angular#50163]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

I have a very simple angular widget that fits into an existing HTML page. It has only one component inside which I have a few SELECT fields. Everything worked fine until I decided to use SplitChunks plugin of webpack to split all the node_modules stuff into a separate vendor bundle and include it separately.

My application is not using any builder, it was never built using any building tool such as angular-cli. I built it from scratch, wrote my own main.ts, module.ts, and app.component.ts, and wrote my own webpack.config.js.

The error I got at runtime was

```
Unhandled Promise rejection: Errors during JIT compilation of template for AppComponent: Sys.ParameterCountException: Sys.ParameterCountException: Parameter count mismatch. 
```

I experimented with the problem and tried to isolate it and here are some interesting findings.

There were a couple of interpolation bindings like the following

```
{{ firstName }}
```
I changed the above to the following and it started working :)

`<span [innerText]="firstName" ></span>`

I added all sorts of crazy things such as *ngFor, *ngIf, banana-in-the-box bindings [()]  and no compiler errors. As soon as there is an interpolation used, it starts to fail in the bootstrap process.

What could cause interpolation to fail with Sys.ParameterCountException?

Any lead on what should I check, or any pointers would be appreciated.

### Please provide the exception or error you saw

```true
("
                <label class="cs-label">User:</label>
            </td>
            [ERROR ->]{{firstname}}
            <td>
                <select [(ngModel)]="user.id" id="ddlUser" name="ddlC"): /Angular/UserWidget/app.component.html@43:3 ; Zone: <root> ; Task: Promise.then ; Value: Error: Errors during JIT compilation of template for AppComponent: Sys.ParameterCountException: Sys.ParameterCountException: Parameter count mismatch. ("
                <label class="cs-label">User:</label>
            </td>
            [ERROR ->]{{firstname}}
            <td>
                <select [(ngModel)]="user.id" id="ddlUser" name="ddlC"): /Angular/UserWidget/app.component.html@43:3
    at parseJitTemplate (compiler.mjs:19736:1)
    at CompilerFacadeImpl.compileComponent (compiler.mjs:19448:43)
    at AppComponent.get (core.mjs:22739:1)
    at getComponentDef (core.mjs:1152:1)
    at verifyDeclarationsHaveDefinitions (core.mjs:22329:1)
    at Array.forEach (<anonymous>)
    at verifySemanticsOfNgModuleDef (core.mjs:22300:1)
    at AppModule.get (core.mjs:22248:1)
    at getInjectorDef (core.mjs:421:1)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular/compiler: ^15.2.8
@angular/core: ^15.2.8
@angular/common: ^15.2.8

System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1270P
    Memory: 11.16 GB / 31.69 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.68)
    Internet Explorer: 11.0.19041.1202
  Packages:
    css-loader: ^6.7.3 => 6.7.3
    style-loader: ^3.3.2 => 3.3.2
    ts-loader: ^9.4.2 => 9.4.2
    webpack-cli: ^5.0.2 => 5.0.2
```

### Anything else?

I am trying really hard to reproduce the issue, will share a plunk if I have any. At this time I can answer questions or share snippets on demand from the proprietary application we are having issues with. This is not a true SPA application, this is a "widget" that fits into a larger HTML page with a few extra things around it.

In fact, this angular application is a body of a bootstrap popup.

**Comment by JoostK** [comment]
This is not actionable from our end without a minimal reproduction. Please keep in mind that custom build pipelines are generally not supported, but I'd be willing to take a look if you have a minimal reproduction (e.g. a Github repo)

**Comment by fahadash** [comment]
@JoostK Thank you for your reply. I narrowed it down to one script that is a server-side script added by ASP.NET Ajax library. I created a test app here and included the script in there called assets/scripts/problem.js
Here is my Github repo: https://github.com/fahadash/AngularError
It is currently working because vendor bundle is not separate. Once I separate the Vendor bundle it will start to bomb out.

**Comment by fahadash** [comment]
I found a temporary fix to this problem. Here is what happens. Microsoft's assembly System.Web.Extensions generate a javascript code snippets and injects it into an ASP.NET Page. That javascript does some smartass thing and tries to intercept in String prototype and adds a validation of parameters to each call. Older version of String prototype probably had only one parameter in StartsWith, so it throws an error if there is more than one.


Angular Compiler uses string.StartsWith and uses 2 parameters which goes to Microsoft's custom generated prototype.


I added the following code in the beginning of my page to make backup of the StartsWith method,

```html
  <script>
        window.saveStringPrototypeStartWith = String.prototype.startsWith;
    </script>
```

then at the end of my page I added the following code


```html
  <script>
          String.prototype.startsWith = window.saveStringPrototypeStartWith ;
    </script>
```

I really don't like what I have to do here but this is very unfortunate.

**Comment by JoostK** [comment]
Oh boy, [that `problem.js` file](https://github.com/fahadash/AngularError/blob/master/angular-error-asp-net/assets/scripts/problem.js) is, let's say, _not ideal_ 🙄 

This is a global script that is patching stuff onto builtin types such as `Function`, `Error`, `Object`, `String`, one of which is likely invoked by the usage of an interpolation pattern. I can't tell which function it is because I don't have a repo, but the "polyfills" in `problems.js` are almost 100% guaranteed non-standard compliant.

Feel free to push another commit that reproduces the error, more so because I'm curious what the _exact_ situation is, but other than that this issue is a caused by incompatible fiddling of standard API, not Angular.
