### ISSUE TITLE
Article mistake

### ISSUE THREAD

**Issue by PiotrZinfWSB** [angular/angular#50166]
### Describe the problem that you experienced

I think there is a samll mistake in the tutorial in:
Step 3 - Add features to HomeComponent
Point 2.
In `app.component.ts`, in @[Component](https://angular.io/api/core/Component), update the template property with this code.

I guess it should be `home.component.ts`

It is a minor mistake, but can be misleading for newbes like me

### Enter the URL of the topic with the problem

https://angular.io/tutorial/first-app/first-app-lesson-02#step-3---add-features-to-homecomponent

**Comment by MukulKolpe** [comment]
Hey @alan-agius4, can I work on this issue?

**Comment by JeanMeche** [comment]
@MukulKolpe You can open a PR if you'd like to fix that issue 😊

**Comment by jamesanderson9182** [comment]
Following the history and looking at the page, it looks like this issue can be closed 😄 
![Screenshot 2023-05-16 at 22 51 28](https://github.com/angular/angular/assets/11311806/3b6c1e3d-672c-4ef3-9f94-877c0f0f1a77)
