### ISSUE TITLE
Passing router data as component inputs not working

### ISSUE THREAD

**Issue by robertIsaac** [angular/angular#50171]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I copied the code snippet from [Angular release blog](https://blog.angular.io/angular-v16-is-here-4d7a28ec680d#398f)

but the input is always undefined no matter how I change it

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-qkwpry?file=src/main.ts

### Please provide the exception or error you saw

```true
it's undefined
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.0
Node: 16.18.1
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 16.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0
@nguniversal/builders           16.0.0
@nguniversal/express-engine     16.0.0
@schematics/angular             16.0.0
rxjs                            7.8.1
typescript                      5.0.4
```

### Anything else?

1. in the article it's written `loadComponent: import('./about'),` but this throw error, I changed it to `loadComponent: () => import('./about'),`
1. the environment provided is from my local setup, as I don't know how to get it from stackblitz, it's same code and same result

**Comment by tomscript** [comment]
ya in the live stream it shows 
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/3085610/236554986-63ebe0b4-ff2f-4643-8306-d78b59d3c4b8.png">
https://www.youtube.com/live/sJzCy8pRU5g?feature=share&t=1107

which produces the horrible red squiggly
<img width="542" alt="image" src="https://user-images.githubusercontent.com/3085610/236555019-f58e1b4a-c4f8-4b35-b12f-5dd47937ed83.png">

```
Type '() => Promise<typeof import("/Users/tomfitzgerald/Documents/projects/auction/mono/user2/src/app/auctions/auctions.component")>' is not assignable to type '() => Type<unknown> | Observable<Type<unknown> | DefaultExport<Type<unknown>>> | Promise<Type<unknown> | DefaultExport<Type<unknown>>>'.
  Type 'Promise<typeof import("/Users/tomfitzgerald/Documents/projects/auction/mono/user2/src/app/auctions/auctions.component")>' is not assignable to type 'Type<unknown> | Observable<Type<unknown> | DefaultExport<Type<unknown>>> | Promise<Type<unknown> | DefaultExport<Type<unknown>>>'.
    Type 'Promise<typeof import("/Users/tomfitzgerald/Documents/projects/auction/mono/user2/src/app/auctions/auctions.component")>' is not assignable to type 'Promise<Type<unknown> | DefaultExport<Type<unknown>>>'.
      Type 'typeof import("/Users/tomfitzgerald/Documents/projects/auction/mono/user2/src/app/auctions/auctions.component")' is not assignable to type 'Type<unknown> | DefaultExport<Type<unknown>>'.ts(2322)
index.d.ts(2521, 5): The expected type comes from property 'loadComponent' which is declared here on type 'Route'
(property) Route.loadComponent?: (() => Type<unknown> | Observable<Type<unknown> | DefaultExport<Type<unknown>>> | Promise<Type<unknown> | DefaultExport<Type<unknown>>>) | undefined
An object specifying a lazy-loaded component.
```

**Comment by JeanMeche** [comment]
You're missing `withComponentInputBinding()` as second param of `provideRouter`

**Comment by tomscript** [comment]
@JeanMeche Thanks for taking a look! yes I am missing it but when I add I still see dredded red squigglies for both syntaxes. any ideas?

https://github.com/tomscript/sturdy-octo-spork/compare/main...router-check

<img width="530" alt="image" src="https://user-images.githubusercontent.com/3085610/236558610-cebb0cd7-a351-4462-86d1-8984a7601e5e.png">

**Comment by JeanMeche** [comment]
Since you don't use a default export, you need to map the value : 

`    loadComponent: () => import("./auctions/auctions.component").then(c => c.AuctionsComponent),`

**Comment by tomscript** [comment]
Ya I used the `.then(...)` method previously but wanted the new hotness to avoid all that, so i'll gladly export default and it worked.
- big thank you!!!

**Comment by JeanMeche** [comment]
@robertIsaac  You can close this issue yourself 😉
