### ISSUE TITLE
After IVY enabled, my components are showing as "not a Known element" at Runtime

### ISSUE THREAD

**Issue by SathiyaGirinathan** [angular/angular#50176]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Im trying to upgrade to Angular 8 to angular 9 with Ivy. 
If we set enableIvy: false in tsconfig.json, it is working fine. But I want to enableIvy and it is showing runtime errors in console like "component is not a known element". 
I'm thinking it is because of abp-ng2-module or gridster module

### Please provide the exception or error you saw

```true
core.js:21445  'cloneChartTitle-component' is not a known element:
1. If 'cloneChartTitle-component' is an Angular component, then verify that it is part of this module.
2. If 'cloneChartTitle-component' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.


core.js:12853  Can't bind to 'WidgetId' since it isn't a known property of 'cloneChartTitle-component'.
warnAboutUnknownProperty @ core.js:12853

core.js:12853  Can't bind to 'cloneChartTitle' since it isn't a known property of 'cloneChartTitle-component'.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 9.1.15
Node: 18.15.0
OS: win32 x64

Angular: 9.1.13
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.15
@angular-devkit/build-angular     0.901.15
@angular-devkit/build-optimizer   0.901.15
@angular-devkit/build-webpack     0.901.15
@angular-devkit/core              9.1.15
@angular-devkit/schematics        9.1.15
@angular/cdk                      9.0.0
@angular/cli                      9.1.15
@angular/http                     8.0.0-beta.2
@ngtools/webpack                  9.1.15
@schematics/angular               9.1.15
@schematics/update                0.901.15
rxjs                              6.6.7
typescript                        3.8.3
webpack                           4.42.0
```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem). 

---

Hello, Angular 9 has not been supported for quite a while, only Angular 14+ is at this moment. Angular 11 was the last to support non-Ivy apps, you may want to migrate to that version before enabling Ivy to at least have latest fixes when you switch over to Ivy.
