### ISSUE TITLE
an alternative way for the proxy.conf.json in the new esbuild builder

### ISSUE THREAD

**Issue by pablomaurer** [angular/angular#50184]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I wanted to try out the new esbuild builder. But it seems to not respect the proxy.conf.json. Is there an alternative?

### Please provide the exception or error you saw

```true
An alterntaive way to declare proxy.conf.json
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
16.0.0
```

**Comment by JeanMeche** [comment]
Hi !
There is already an issue on this in angular/angular-cli#25148

**Comment by JoostK** [comment]
The proxy config is being used with the esbuild builder, however there's an issue where glob patterns are not handled, as reported in https://github.com/angular/angular-cli/issues/25148. This is likely the problem here as well.
