### ISSUE TITLE
 Error: Module parse failed: Unexpected token (1:0) You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by NiranjanKushwaha** [angular/angular#50181]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

i am using some part of react in my angular application and i have installed react-toastify . it was working in Angular version 14.
since i have updated to Angular 15, i am getting the error.
I am not using webpack.config in my angular, i am using Angular CLI.

### Please provide the exception or error you saw

```true
./node_modules/react-toastify/dist/ReactToastify.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .Toastify__toast-container {
|   z-index: 9999;
|   -webkit-transform: translate3d(0, 0, 9999px);
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.8
Node version: 18.16.0
Npm versin: 9.5.1
```

**Comment by JoostK** [comment]
You probably have `import 'react-toastify/dist/ReactToastify.css';` somewhere in your app. CSS imports are not ES standard compliant and not supported with the CLI. It was made an error in Angular 14 in angular/angular-cli#22363. Please move such style imports to `angular.json`.

**Comment by NiranjanKushwaha** [comment]
Thanks , it is working now.
