### ISSUE TITLE
ng-content not work for [textContent]

### ISSUE THREAD

**Issue by hannah23280** [angular/angular#50187]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

I not sure if this is considered a bug, or an intentional.

I have the below template in the parent component
`<child>Test</child>`

I have the below tempalte in the child component
`<div>This is<ng-content></div>`

So far everything works as expected

But if my template in parent component is changed from  
`<child>Test</child>`  to
`<child [textContent]="Test"></child>`

The `<ng-content>` no longer works.

### Please provide the exception or error you saw

```true
There is no exception or error.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16
Node:v18.16.0
Npm: v9.5.1
```

**Comment by drtobal** [comment]
Hi

Inner HTML can be both html elements and strings, and textContent can only be strings.

Not sure about what you are trying, maybe you have to try a different implementation.

**Comment by drtobal** [comment]
I think that If you want to pass a string, you should use an `@Input()`, and use ng-content for innerHTML elements in template

`<child [nameOfTheInput]="Test"></child>`

`<div>This is {{nameOfTheInput}}</div>`

https://docs.angular.lat/guide/inputs-outputs

**Comment by JoostK** [comment]
This is expected; DOM operations outside of Angular (like assigning to `textContent` or `innerHTML`) do not result in content. Only content declared in the template itself is being projected.
