### ISSUE TITLE
Signal - provide a way to know if there is listeners

### ISSUE THREAD

**Issue by GrandSchtroumpf** [angular/angular#50182]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

I've build a library that manage long running subscription on Firebase across the application.
https://github.com/dappsnation/ngfire

It tracks the amount of listeners on a specific query/document, and while there is one, it keeps the firestore subscription open. This is possible thanks to the `share` rxjs operator.
By doing that I optimize the amount of request to Firestore and keep the last value in cache.

I tried to switch to the signal API to reduce my dependency to zone.js (which has some issues with Firebase) but there is no way to track how many elements are listening on the changes of the signal. 

### Proposed solution

Create an API that return the amount of active listeners on a signal. Maybe something like that : 
```typescript
const counter = signal(0);
const listeners = signalListeners(counter); // returns a Signal<number> with value 0 by default
const ref1 = effect(() => console.log(counter())); // `listeners`'s value is now 1
const isEven = computed(() => counter() % 2);
const ref2 = effect(() => console.log(isEven())); // `listeners`'s value is now 2
ref1.destroy();  // `listeners`'s value is now 1
```
Here is how I would use it : 
```typescript
signals: Record<string, WritableSignal> = {};
listeners: Record<string, Signal<number>> = {};
effects: Record<string, EffectRef> = {};

doc(ref: DocumentRef) {
  const isRegistered = ref.path in this.effects;
  this.signals[ref.path] ||= signal(undefined);
  this.listeners[ref.path] ||= signalListeners(this.signales[ref.path]);
  if (!this.effects[ref.path]) {
    let previous = 0;
    let unsubscribe: () => void;
    this.effects[ref.path]effect((cleanup) => {
      const listeners = this.listeners[ref.path]();
      // Start listening on first listener 
      if (!previous && listeners) {
        unsubscribe = onSnapshot(ref, (snap) => this.signals[ref.path].set(snap)).unsubscribe;
      }
      // Stop listening when there is no listeners
      if (previous && !listeners) {
        unsubscribe();
      }
      previous = listeners;
      cleanup(() => unsubscribe());
    }, {
      manualCleanup: true
    });
  }
 return this.signals[ref.path];
}

// Cleanup everything if service is destroy
ngOnDestroy() {
  for (const key in this.effects) {
    this.effects[key].destroy();
  }
}
```

### Alternatives considered

Currently at best I can know how many components have requested a document by adding an `effect` on very request, but there is no way to know if any of these component is actually listening on the signal changes. Also if the signal is used inside an `*ngIf="false"` then we shouldn't listen on Firestore.

**Comment by alxhub** [comment]
A key design goal of signals was that they be side-effect-free. This means that reading a signal in a template should not trigger network requests, backend subscriptions, or other operations. A corollary of this principle is that _not_ reading a signal should also not trigger side effects (like unsubscription).

Signals will not be a good fit for an API that needs to discern interest vs no interest in a value. Instead, such an API should use other mechanisms to subscribe/unsubscribe, and use signals to deliver change notifications during the lifetime of the subscription.

**Comment by GrandSchtroumpf** [comment]
Alright thanks for the feedback. So if I understand correctly, a good solution would be to continue using rxjs, and create a `| toSignal` pipe to replace all the `| async` that currently subscribe to the global firestore subscription.
Like that I won't depend on zone.js ?
