### ISSUE TITLE
Angular update guide does not have instructions for how to actually update via CLI

### ISSUE THREAD

**Issue by stephanietuerk** [angular/angular#50185]
### Describe the problem that you experienced

The [Angular Update Guide](https://update.angular.io/?v=15.0-16.0) no longer/does not provide any instructions for a CLI command, such as `ng update`, to update between versions. 

### Enter the URL of the topic with the problem

https://update.angular.io/?v=15.0-16.0

### Describe what you were looking for in the documentation

The page currently says, "Review these changes and perform the actions to update your application." All of the listed items are things that someone will need to change in their repo either before or after updating. There are no instructions to actually update Angular from one version to another. If `ng update` is all that is needed, I think that would be good to show -- I found it very confusing to not see any actual commands to run.

### Describe the actions that led you to experience the problem

I wanted to update from V15 to V16 and wanted to very carefully follow update instructions, including command line commands.

### Describe what you want to experience that would fix the problem

I would like to be able to see a command line function that tells me exactly what to type to update from v15 to v16. From a UX perspective, I would also suggest removing the "Show me how to update" button after the instructions are displayed, and reinstating it if changes are made to the form above. Because I didn't understand the text below the form as "how to update", I kept pressing this assuming it would possibly open a new tab/modal, or somehow show the information I expected, and my impression was that it was broken.

**Comment by drtobal** [comment]
Hi,

Are you looking for this?

https://angular.io/cli/update

**Comment by stephanietuerk** [comment]
> Hi,
> 
> Are you looking for this?
> 
> https://angular.io/cli/update

Indeed, those are the kind of instructions I expect to see when I see text that tells me "perform these actions to update your application." :) 

Really this issue is a UX issue that I imagine others, especially very new developers, might have a hard time with. This ticket is just to bring it to the team's attention, I managed to update on my own just fine.

**Comment by drtobal** [comment]
You are right,

Repo of update guides is another https://github.com/angular/angular-update-guide
Anyways, Angular team is focused on improve developer experience, and I agree with https://update.angular.io/ can be improved with reference to related cli commands

:D

**Comment by JeanMeche** [comment]
Hi, 
For suggestions to the update site, you should open an issue on the dedicated repo : https://github.com/angular/angular-update-guide.

**Comment by stephanietuerk** [comment]
Thank you @JeanMeche . Closing this issue and opening one there! :)
