### ISSUE TITLE
mobile nav dropdown items are hidden on ios mobile browsers

### ISSUE THREAD

**Issue by windmillcode0** [angular/angular#50186]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

when a users opens the panel on ios they should see the menu items
the user is not seeing the menu items

### Please provide a link to a minimal reproduction of the bug

https://windmillcode.github.io/mobile-dropdown-not-showing-up-on-iphone-browsers/

### Please provide the exception or error you saw

```true
show me how to do debugger in ios and I will attempt
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular-devkit/architect       0.1600.0
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0
@schematics/angular             16.0.0
rxjs                            7.8.1
typescript                      5.0.4
```

### Anything else?

* give me resources to setup a phone debugger
also refer to the actual site https://windmillcodesite.web.app
* try to open in browser  andrioid mobile and ios mobile

**Comment by drtobal** [comment]
Hi,

I think the menu is not visible on any browser, maybe is better to provide a plunkr.
I believe this is not an Angular issue, if you need help with your implementation is better to ask in stackoverflow or similar.

https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-got-a-question-or-problem

Good luck! :D

**Comment by windmillcode0** [comment]
the menu is certainly visible
# Windows Desktop
![image](https://user-images.githubusercontent.com/101383925/236676940-07f60ea0-9568-453d-92f2-2438e7990430.png)
![image](https://user-images.githubusercontent.com/101383925/236677007-f6eaebcb-5c0a-44fc-b49b-319d3a6f59af.png)
![image](https://user-images.githubusercontent.com/101383925/236677052-f513d67c-d196-4087-85ea-c9551f6e126f.png)
![microsoft edge](https://user-images.githubusercontent.com/101383925/236677081-16fc5259-68de-49e2-922b-f09cb8b07ce9.png)

# Pixel
![firefox-pixel](https://user-images.githubusercontent.com/101383925/236678702-dd475182-52b8-449c-b43b-f4bda9723780.png)
![opera-pixel](https://user-images.githubusercontent.com/101383925/236678703-ecddbe90-0ee2-4872-a2b5-6c40ce7e8d9a.png)
![opera-touch-pixel](https://user-images.githubusercontent.com/101383925/236678705-c41ed0a0-5c7e-4914-83ac-ce2a672a7c65.png)
![samsung-pixel](https://user-images.githubusercontent.com/101383925/236678709-b76a3576-0749-4f66-b83f-995d9e12b47c.png)
![vivaldi-pixel](https://user-images.githubusercontent.com/101383925/236678710-6d7cea2d-0f02-4220-a1f9-2efc3a271b11.png)
![yandex-pixel](https://user-images.githubusercontent.com/101383925/236678711-0622f1fb-cd42-4b31-88c3-fde7476c6b71.png)
![chrome-pixel](https://user-images.githubusercontent.com/101383925/236678715-0817ddc0-e42b-4f89-a9ec-e02cdeb61038.png)
![duckduckgo-pixel](https://user-images.githubusercontent.com/101383925/236678717-bfc614c2-ae4d-427a-a169-5a330b6598f6.png)
![edge-pixel](https://user-images.githubusercontent.com/101383925/236678719-f9764ec2-62ee-44d9-8961-9a3f05acf2a3.png)


![safari-ios](https://user-images.githubusercontent.com/101383925/236678708-c5716b00-373e-4f7f-82e8-94a445e0cb99.jpg)
![chrome-ios](https://user-images.githubusercontent.com/101383925/236678713-43937c01-927b-4dcc-ae07-f3f43c9881c8.jpg)
![firefox-ios](https://user-images.githubusercontent.com/101383925/236678720-8de0ee0f-93b2-4416-b535-135914c16687.jpg)

# Pixel

I could not do a plunkr so heres a stack blits
[Actual Site](https://angular-gj7h8v.stackblitz.io/)
[Stack Blitz](https://stackblitz.com/edit/angular-gj7h8v?file=package.json,src%2Fmain.ts,src%2Findex.html,src%2Fapp%2Fapp.component.scss,src%2Fglobal_styles.css)

**Comment by windmillcode0** [comment]
We believe in the angular product the way its taught and all the uncessary features is why React is king right now. I know at google you see the rest of us from mount olympus dont think of use as mortals, even though we dont have DSA we still have plenty of talent!

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by windmillcode0** [comment]
Woah this is not a support request this is a bug from the angular code itself the panel opens on windows and and andrioid but refuses to appear on ios.

**Comment by windmillcode0** [comment]
can we at least have some resources to debug the application

**Comment by JoostK** [comment]
Items are not visible because of styling problems, also reproducible on desktop Safari:

<img width="1774" alt="Screenshot 2023-05-07 at 18 07 27" src="https://user-images.githubusercontent.com/123679/236689029-6cd35100-6e95-44c4-b6e4-a93c2bdaa2db.png">

Since the components are rendered into the DOM but not visible this is an application issue.

**Comment by windmillcode0** [comment]
no no , thats in correct
looks like the latest of the stackblitz was not updated /
I save the changes to app.components.ts now try again 
also view the orginal site along with the miminual reproduction

**Comment by JoostK** [comment]
It's the same situation really; some divs are just not visible because of styling issues. The elements are all there (so Angular did its thing).

<img width="2052" alt="Screenshot 2023-05-07 at 18 37 44" src="https://user-images.githubusercontent.com/123679/236690616-b632230a-ac43-440c-8ebf-98d0e929a6c3.png">

**Comment by windmillcode0** [comment]
the styles are the same were not seeing anything that indicates the container with the menu items are hidden

**Comment by windmillcode0** [comment]
I would think its a safari problem

**Comment by windmillcode0** [comment]
we also know it is for sure with our wml-infinite-dropdown component we created with angular 16 because this mobile nav, also resuses the dropdown. so there is some css feature the cpnt is using that is not compatablit with safari?

**Comment by windmillcode0** [comment]
if you watch this video you will see that what we have done is to replace the option tag with the p tag so it can render, is this an angular thing or safari thing I am suspecting its safari as we would like the code responsible to make the option element in safari appear regardless of what it is surronded by https://www.youtube.com/watch?v=JX_BS68i-q8
