### ISSUE TITLE
Add deps and useClass to injection tokens

### ISSUE THREAD

**Issue by Harpush** [angular/angular#50197]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Currently there are two options to provide class with deps using injection tokens:
Option 1:
```ts
const token = new InjectionToken<A>('Token 1');
const provider: Provider = {
  provide: token,
  useClass: A,
  deps: [BackendService]
};
```
Which works well but requires providing the provider yourself in root which is not tree shakable

Option 2:
```ts
const token = new InjectionToken<A>('Token 2', {
  providedIn: 'root',
  factory: () => new A(inject(BackendService)),
});
```
Which requires manually newing with factory which isn't the best...

### Proposed solution

Adding a third option allowing for easier configuration:
```ts
const token = new InjectionToken<A>('Token 2', {
  providedIn: 'root',
  useClass: A,
  deps: [BackendService]
});
```
This will also allow using Option 1 but without specifying the provide scope manually for root.

### Alternatives considered

Just use factory with manual newing

**Comment by alxhub** [comment]
Option 2 is actually by design - we chose to use that API instead of `useClass` and `deps`. Calling `new` with injected arguments is nicely type-safe, whereas providing the class to instantiate and the constructor argument types separately is extremely unsafe.
