### ISSUE TITLE
Signals: Writing to signals is not allowed in a `computed`

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/angular#50192]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I believe there is a bug in creating computed signal from method returning observable:

```
 constructor(private injector: Injector) {}
  userId: Signal<string> = signal('userA');
  roles = computed(() =>
    toSignal(getRoles(this.userId()), { injector: this.injector })()
  );

//this could be api service sending  http request
const getRoles = (userId: string) => {
  return userId === 'userA' ? of([1, 2, 3]) : of([1]);
};
```
This code throws runtime console error
`Error: NG0600: Writing to signals is not allowed in a `computed` or an `effect` by default. Use `allowSignalWrites` in the `CreateEffectOptions` to enable this inside effects.`

However, that does not seem to be case of writing to signal. I read signal `userId` and I convert observable into signal via `toSignal()` method. No writing anywhere. Am I wrong?

[Stackblitz here](https://stackblitz.com/edit/angular-admqds?file=src/main.ts)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-admqds?file=src/main.ts

### Please provide the exception or error you saw

```true
Error: NG0600: Writing to signals is not allowed in a `computed` or an `effect` by default. Use `allowSignalWrites` in the `CreateEffectOptions` to enable this inside effects.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 16
Nodejs 18.10
```

**Comment by JeanMeche** [comment]
Hi,

You're writing to a signal by creating it with the `toSignal()`  and setting the values on subscribe. 

https://github.com/angular/angular/blob/80fe08be96633171567e30eb91dd1d23c60a2952/packages/core/rxjs-interop/src/to_signal.ts#L168-L181

**Comment by GeorgeKnap** [comment]
> Hi,
> 
> You're writing to a signal by creating it with the `toSignal()` and setting the values on subscribe.
> 
> https://github.com/angular/angular/blob/80fe08be96633171567e30eb91dd1d23c60a2952/packages/core/rxjs-interop/src/to_signal.ts#L168-L181

Thanks for clarification. Is it possible and safe in this case to use `allowSignalWrites` ?

**Comment by JeanMeche** [comment]
`allowSignalWrites` is only for `effect()` and its not a recommended usage case here ([see the documentation](https://angular.io/guide/signals)).  

If you'd like to use a computed here, the `async` pipe is the way to go : `{{roles() | async }` 

With
```
roles = computed(() =>
  getRoles(this.userId())
);
```

**Comment by GeorgeKnap** [comment]
@JeanMeche that would essentially make it `Signal<Observable<any[]>>` - that seems ugly.

how about this?
```
roles$: Observable<any[]>
effect(() => {
  this.roles$ = getRoles(this.userId());
});

```

**Comment by JeanMeche** [comment]
The result is essentially the same thing but with this code you won't have the advantages of relying on signals.

**Comment by GeorgeKnap** [comment]
Alright thanks for help

**Comment by GeorgeKnap** [comment]
I would like to reopen this issue. It might not be bug but a feature request but Id o believe this is and will be a standard use-case that Angular should support.

**Comment by pkozlowski-opensource** [comment]
> this is and will be a standard use-case that Angular should support.

I'm not sure what is the exact use-case that we should support... What is going on in the following code:

```typescript
roles = computed(() =>
    toSignal(getRoles(this.userId()), { injector: this.injector })()
  );
```

is that `toSignal` is called inside a computed. `toSignal` is an operation with side effects while `computed` are expected to be pure functions without any side effects. In this sense this is definitively _not_ the use-case we want to support. 

If anything, we could update an error message here to give more indication of the problematic coding pattern.

It sounds like you want to trigger some effect when a value of a signal changes but  `computed` is not the tool for the job here - `effect` is.

**Comment by GeorgeKnap** [comment]
@pkozlowski-opensource 
Hi and thanks for quick response. The use-case is:

- I have an entity - signal - for example user indentified by id
- I want to create  derived property - also signal - that will depend on changed of the user id and will do HTTP request to fetch user roles and provide them as a signal

another use case:
based on some signal I want to dynamically import component and provide it as another signal.  module import in typescript returns a Promise so it's the same situation => toSignal from Promise.


In the end it does not matter if I use `computed` or `effect`. I want the result to be a signal  and I have to use `toSignal`. That will equally throw runtime error regardless of using `computed` or `effect`.

**Comment by pkozlowski-opensource** [comment]
> In the end it does not matter if I use computed or effect. I want the result to be a signal and I have to use toSignal. That will equally throw runtime error regardless of using computed or effect.

It actually does matter since in effects:
* if the processing is asynchronous the setter runs _outside_ of the effect function where you can set signals;
* there is the `allowSignalWrites` option on effects.

Again, `computed` is _not_ the solution of any of those use-cases. And usage of `effects` also requires attention as we can easily start piling up subscribers: https://stackblitz.com/edit/angular-dtgdxm?file=src%2Fmain.ts

**Comment by GeorgeKnap** [comment]
@pkozlowski-opensource 
Alright I just re-written my [stackblitz demo](https://stackblitz.com/edit/angular-admqds?file=src/main.ts)  to use `effect` instead of `computed`. Still having the same runtime error.

**Comment by pkozlowski-opensource** [comment]
> @pkozlowski-opensource
> Alright I just re-written my [stackblitz demo](https://stackblitz.com/edit/angular-admqds?file=src/main.ts) to use effect instead of computed. Still having the same runtime error.

You are missing the mentioned `allowSignalWrites`: https://stackblitz.com/edit/angular-e5anll?file=src%2Fmain.ts

Having said this the implementation still have several problems:
* subscriptions are piling up (who is going to unsubsribe?)
* I'm not sure there is much value in using `toSignal`, really - it just a fancy way of subscribing to get the last value... Remember that `toSignal` _will_ create a new subscription to get the value from Observable

**Comment by GeorgeKnap** [comment]
> subscriptions are piling up (who is going to unsubsribe?)
isn't that what `toSignal` does automatically? 
```
By default, the subscription will be automatically cleaned up when the current injection context is destroyed. 
```

From what you say I'm getting the impression that signals aren't meant to work with async code. So going back to observables would be better idea? like 
```
roles$ = toObservable(this.userId()).pipe(
   switchMap(userId => getRoles(userId))
)
```

**Comment by pkozlowski-opensource** [comment]
> isn't that what toSignal does automatically?
> By default, the subscription will be automatically cleaned up when the current injection context is destroyed.

The "the subscription will be automatically cleaned up when the current injection context is destroyed" part is the crux - you are creating a new subscription on effect run, while the injection context corresponds to the component lifecycle. The timing is very different and you would be creating and storing many subscriptions, before those are released.

> From what you say I'm getting the impression that signals aren't meant to work with async code

This is not how I would phrase it. Signals are great at synchronizing state that you've got already: `computed` is the real power. Signals are not concerned with data _fetching_ - you can do it in effect or observables - but ultimately you need to write to a signal (reactive graph) _somehow_. 

> So going back to observables would be better idea?

Potentially, if the data fetching layer returns an observable already.

**Comment by GeorgeKnap** [comment]
Maybe the problems would be solved by HttpClient returning a signal instead of observable?

**Comment by pkozlowski-opensource** [comment]
> Maybe the problems would be solved by HttpClient returning a signal instead of observable?

We might review the data fetching layer so it works better with signals but it is definitively more involved that "converting" observable to a signal. This will be part of the follow up work of better integrating signals in the Angular ecosystem.

I'm going to close this issue as at this point it becomes general discussion about the best practices and speculating about the future. We absolutely know and agree that the current integration between data fetching and state expressed in signals is not ideal and we will absolutely make changes to have a better story.

Having said all this the check in `computed` behaves as expected - we _do_ want to prevent writing to signals from there. Plus we might want to disallow `toSignal` calls in `computed` as well.

**Comment by GeorgeKnap** [comment]
Alright. Many thanks. Good chat
