### ISSUE TITLE
Recommended way to conditionally apply directive

### ISSUE THREAD

**Issue by sumigoma** [angular/angular#5019]
I would like to apply a directive conditionally through something like [class.draggable]="someBool" with '.draggable' as the selector on the directive, but this is not supported. What then is the recommended way to conditionally apply a directive on an existing element? Do I use an attribute for the selector and pass in the boolean as an input (i.e. the directive is always "active")? I'd prefer not to use ng-ifs with duplicate elements everywhere. Is there a cleaner way to attach and detach a behavior?

**Comment by pkozlowski-opensource** [comment]
@sumigoma it is hard to give you good answer without full understanding of your use-case but what we are trying to do with ng2 is to make it _predictable_. Among other things it means that you (and tools!) could quickly / easily analyze a template and figure out which directives are active. As such we don't want to support matching directives dynamically, in response to runtime property changes.

I'm going to close this one as there is nothing immediately actionable here, but I would suggest continuing the discussion on https://gitter.im/angular/angular
