### ISSUE TITLE
Feature Request: Reactive @Inputs with signals

### ISSUE THREAD

**Issue by BenniG82** [angular/angular#50190]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

This feature request is pretty much the same as https://github.com/angular/angular/issues/5689 but with signals.

I took a look at Signals and immediately fell in love :heart_eyes: 
But I'm wondering why there is (currently) no way to handle `@Input` with signals. In my opinion this would be a perfect match.
And as you can see in #5689 there is a need for reactive `@Input`
@mgechev closed this issue because it would mean more coupling to RxJS. (Which is totally understandable)

Nowadays both features (`@Input` and `Signal`) reside in @angular/core. So lets get that going

### Proposed solution

Imagine how cool this would be:

```
import { ChangeDetectionStrategy, Component, computed, SignalInput, signal } from '@angular/core';

@Component({
  selector: 'app-demo-input-signal',
  template: `
    <div>
      Sum is {{sum()}}
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class DemoInputSignalComponent {

  @SignalInput()
  num1 = signal<number>(0);
  
  @SignalInput()
  num2 = signal<number>(0);


  sum = computed(() => this.num1() + this.num2());
}
```

I know this is a trivial example, but often times I need to do a calculation or backend-lookup using two `@Input` values. Yes it is possible to pass complex values to `@Input` but thats kinda ugly.

### Alternatives considered

Using Signals for `@Inputs` is currently very verbose:

```
import { ChangeDetectionStrategy, Component, computed, Input, signal } from '@angular/core';

@Component({
  selector: 'app-demo-input-signal',
  template: `
    <div>
      Sum is {{sum()}}
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class DemoInputSignalComponent {

  num1Signal = signal<number>(0);
  num2Signal = signal<number>(0);

  @Input()
  set num1(value: number) {
    this.num1Signal.set(value);
  }

  get num1(): number {
    return this.num1Signal();
  }

  @Input()
  set num2(value: number) {
    this.num2Signal.set(value);
  }

  get num2(): number {
    return this.num2Signal();
  }

  sum = computed(() => this.num1Signal() + this.num2Signal());
}
```

**Comment by JeanMeche** [comment]
Hi 

This has already been intensively discussed as part of the RFC with the Signal based components : https://github.com/angular/angular/discussions/49682

**Comment by BenniG82** [comment]
Thanks for that link. I was unable to find anything about that topic using google and wasn't aware that there already is a discussion.
Now after looking at https://blog.angular.io/angular-v16-is-here-4d7a28ec680d again I'm wondering how I could oversee two paragraphs for this topic. Shame on me :(

If anybody finds this issue while googling, see https://blog.angular.io/angular-v16-is-here-4d7a28ec680d 

> Next steps for signals
Next we’ll be working on [signal-based components](https://github.com/angular/angular/discussions/49682) which have a simplified set of lifecycle hooks, and an alternative, more simple way of declaring inputs and outputs. We will also work on a more complete set of examples and documentation.

> One of the most popular issues in the Angular repository is “[Proposal: Input as Observable](https://github.com/angular/angular/issues/5689).” A couple of months ago we [responded](https://github.com/angular/angular/issues/5689#issuecomment-879474919) that we want to support this use case as part of a larger effort in the framework. We’re happy to share that later this year we’ll land a feature that will enable signal-based inputs — you’ll be able to transform the inputs to observables via the interop package!
