### ISSUE TITLE
Generate Change Detection classes instead of getter setter stubs

### ISSUE THREAD

**Issue by mhevery** [angular/angular#502]
Depends on #501, #503

Executing change detection using getter stubs (see #501) has two issues. 
1) it causes polymorphic calls, which limits the execution speed.
2) it prevents proper tree shaking of dart2js.

To address this instead of generating getters stubs we can generate ChangeDetector class. The changeDetector class is a bit more complicated, but it has significant performance and size impact.

The JS code generation is already working and its implementation can be seen in [`change_detection_jit_generator.es6`](https://github.com/angular/angular/blob/master/modules/change_detection/src/change_detection_jit_generator.es6) The equivalent dart version needs to be implemented in [`change_detection_jit_generator.dart`](https://github.com/angular/angular/blob/master/modules/change_detection/src/change_detection_jit_generator.dart).

While in JS we can run the generator at runtime, the dart version needs to execute at transform time.

**Comment by kegluneq** [comment]
ChangeDetector implementation: 8a3b0b366fe450fb780c38b907002b43e7ad1019

Next up: actually use pre-generated change detectors when they are available
