### ISSUE TITLE
【doc-language zh-TW】angular doc description mistake

### ISSUE THREAD

**Issue by TianMaoJingLingX1** [angular/angular#50205]
### Describe the problem that you experienced

angular zh-TW language document description mistake，should @Input，actual is@Output，the article URL is [https://developer.mozilla.org/zh-TW/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_item_component](url)，建立一個 item 元件 -> 在 ItemComponent 添加邏輯
@Input() ， @Output() 和 EventEmitter 促進兩個元件中的溝通,**一個 @Output() 服務元件做為資料傳進的入口**，然後一個 @Output() 是將元件資料傳到外層。@Output() 必須是 EventEmitter 的類型，資料可以透過事件分享至其他組件.

### Enter the URL of the topic with the problem

https://developer.mozilla.org/zh-TW/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_item_component

### Describe what you were looking for in the documentation

angular zh-TW language document description mistake,should @Input，actual is@Output.

### Describe the actions that led you to experience the problem

looking for quickly started doc.

### Describe what you want to experience that would fix the problem

@Input() ， @Output() 和 EventEmitter 促進兩個元件中的溝通，一個 **@Input()** 服務元件做為資料傳進的入口，然後一個 @Output() 是將元件資料傳到外層。@Output() 必須是 EventEmitter 的類型，資料可以透過事件分享至其他組件。

**Comment by JoostK** [comment]
MDN is not managed by us. There's a "Found a content problem with this page?" section at the bottom of the MDN page with suggestions on what you can do to address the issue.
