### ISSUE TITLE
Linter failing to read angular.json after v16 migration

### ISSUE THREAD

**Issue by Blunderchips** [angular/angular#50202]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

As of Angular v16, the linter is failing to run. Not failing to pass but entirely failing to run. From the error message, it looks to me, it is looking for the `angular.json` in the wrong directory. The linter does run and pass on v15. Interestingly, `ng test` is still working as expected.

When running `ng lint`: (**file not found is to be expected as that is not where the `angular.json` is**)

![image](https://user-images.githubusercontent.com/7081037/236771621-39ed14f6-c24a-4343-b1e8-6843aa11f3b3.png)

The contents of the error file are:

![image](https://user-images.githubusercontent.com/7081037/236772061-6f62e808-41ca-4fbb-9754-0abe57dc996a.png)

### Please provide the exception or error you saw

```true
See above.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.0                                           
Node: 18.15.0                                                 
Package Manager: npm 9.5.0                                    
OS: win32 x64                                                 
                                                              
Angular: 16.0.0                                               
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser               
... platform-browser-dynamic, router, service-worker          
                                                              
Package                         Version                       
---------------------------------------------------------     
@angular-devkit/architect       0.1600.0
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0
@angular/fire                   7.5.0
@angular/flex-layout            14.0.0-beta.41
@schematics/angular             16.0.0
ng-packagr                      16.0.0
rxjs                            7.8.1
typescript                      5.0.4
```

### Anything else?

The project is a yarn berry mono-repo, it looks like the CLI is only looking in the root folder. Failing on both my local machine (windows 10) and out CI/CD pipeline (node 16 alpine).

**Comment by JoostK** [comment]
There's Nx functions in your stacktrace, so this is likely an issue with Nx.
