### ISSUE TITLE
Memory leak with repeated setTimeouts

### ISSUE THREAD

**Issue by BTMorton** [angular/angular#5021]
As part of a project I've been working on, I've found there is an issue with memory leaking when repeatedly calling setTimeout. As an example I simplified my app to the following:

```
@Component({
    selector: 'app'
})
@View({
    template: '<div>{{number}}</div>',
    encapsulation: ViewEncapsulation.None
})
export class App {
    private number = 0;

    constructor() {
        this.loop();
    }
    
    public loop() {
        this.number = (this.number + 1) % 99999999;
        setTimeout(this.loop.bind(this), 20);
    }
}
```

As expected, the number counts up, but looking at Chrome's task manager, the memory usage quickly reaches over 200mb. Using the memory profiler gives the following:

![settimeoutmemory](https://cloud.githubusercontent.com/assets/9026309/10846299/7c7f057e-7f06-11e5-9da9-6912b863a018.png)

When run using requestAnimationFrame, it gives:

![requestanimmemory](https://cloud.githubusercontent.com/assets/9026309/10846312/92ac8358-7f06-11e5-92aa-34e380b89ab9.png)

Obviously, in a case similar to this, using requestAnimationFrame would be the correct approach, but for a longer timeout on a slow running function, for example, this could result in a lot of unnecessary overhead.

**Comment by vicb** [comment]
This is no ;ore be a problem with latest RCs
