### ISSUE TITLE
Standalone components loadChildren() not calling canLoad

### ISSUE THREAD

**Issue by AbdealiLoKo** [angular/angular#50224]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

Moving this [SO question](https://stackoverflow.com/questions/75098592/whats-the-equivalent-of-canload-guard-for-standalone-components) to the angular tracker.

I was trying to use standalone components instead of modules based on the "Virtual NgModule mental model" described in https://github.com/angular/angular/discussions/43784

I had a module which had just 1 component in it, and decided to replace that with the standalone component instead

On doing that, I noticed that the `canLoad` guard was not getting called.
And after some searching saw that in the [`loadComponent` PR](https://github.com/angular/angular/pull/45705#issue-1210264631) the last point mentioned was:
> CanLoad guards do not apply to loadComponent. canActivate should be used instead, just like you would do if it were simply component instead.

I could not find this mentioned anywhere in the documentation, I checked:
 - [Lazy Loading a Standalone Component](https://angular.io/guide/standalone-components#lazy-loading-a-standalone-component)
 - [loadComponent](https://angular.io/api/router/Route#loadComponent)
 - [canLoad](https://angular.io/api/router/CanLoad) / [canLoadFn](https://angular.io/api/router/CanLoadFn)
 - [canMatch](https://angular.io/api/router/CanMatch) / [canMatchFn](https://angular.io/api/router/CanMatchFn)

I couldn't conclude if this is an expected behavior or a bug ...
And if expected is this something planned for standalone components or am I using standalone components for something it should not be using

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-standalone-component-canload

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.2
Node: 16.18.1
Package Manager: npm 9.6.0
OS: linux x64

Angular: 15.2.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.2
@angular-devkit/build-angular   15.2.2
@angular-devkit/core            15.2.2
@angular-devkit/schematics      15.2.2
@schematics/angular             15.2.7
rxjs                            7.8.1
typescript                      4.9.5
```

### Anything else?

NOTE: The original SO post says canMatch does not work either - but seemed to work for me.

Looks like canMatch() works but canLoad() does not work from my experiments in: https://stackblitz.com/edit/angular-standalone-component-canload

**Comment by JeanMeche** [comment]
Just quoting the source code : 

https://github.com/angular/angular/blob/cc286be7af31c7f999d6c469d3fd8f9becb28ce7/packages/router/src/router_preloader.ts#L113C32-L120

**Comment by AbdealiLoKo** [comment]
Understood, should that be documented in the docs ?
Or it doesn't really matter as it's deprecated anyway ?
