### ISSUE TITLE
[Pagespeed] How to reduce unused JavaScript in browser.mjs, core.mjs, router.mjs and forms.mjs?

### ISSUE THREAD

**Issue by Jun711** [angular/angular#50222]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

When I checked my website speed on https://pagespeed.web.dev/, it gave me a suggestion to reduce unused JavaScript in these Angular files to improve on loading speed.

```
…node_modules/@angular/animations/fesm2015/browser.mjs | 17.8 KiB | 14.9 KiB
…node_modules/@angular/core/fesm2015/core.mjs | 32.8 KiB | 14.1 KiB
…node_modules/@angular/router/fesm2015/router.mjs | 20.1 KiB | 11.0 KiB
…node_modules/@angular/forms/fesm2015/forms.mjs | 13.1 KiB | 9.5 KiB
```

Overall performance score
<img width="961" alt="Screen Shot 2023-05-09 at 10 53 05 AM" src="https://github.com/angular/angular/assets/6880939/92977899-c90c-48e0-8546-77e7e6afc4f1">

-----

PageSpeed Suggestion 
<img width="960" alt="Screen Shot 2023-05-09 at 10 30 14 AM" src="https://github.com/angular/angular/assets/6880939/5901ebe8-7b70-4808-bac2-9b7e9199a34d">

### Proposed solution

no idea

### Alternatives considered

These modules seem to be needed at the beginning of page load so I can't defer loading them.

**Comment by alxhub** [comment]
It is very unusual to see jQuery in an Angular application.

This isn't really an actionable issue for us - discussion forums like the [Angular Community Discord](https://discord.com/invite/angular) are a much better place to ask for advice. As a starting point though, make sure you're using [lazy loading](https://angular.io/guide/lazy-loading-ngmodules#lazy-loading-basics) in the Angular router to split components which aren't used in the initial render out into their own lazy loaded chunks.

**Comment by Jun711** [comment]
@alxhub 
Don't mind about the jquery as this is a legacy repo 

yes, I am using lazy loading but these modules are needed at the beginning. 
Are Angular core and routes not needed at the beginning?

**Comment by Jun711** [comment]
@alxhub 
What about Angular documentation page? Is that an actionable issue for you?
https://pagespeed.web.dev/analysis/https-angular-io-docs/ebby37tj3k?form_factor=mobile

core and browser modules were loaded at the beginning too

<img width="963" alt="Screen Shot 2023-05-09 at 4 07 18 PM" src="https://github.com/angular/angular/assets/6880939/d7b30c88-53a9-40a6-916e-346da80cf875">
<img width="961" alt="Screen Shot 2023-05-09 at 4 07 33 PM" src="https://github.com/angular/angular/assets/6880939/a3471739-9e82-49e7-962b-4d6be4563874">
