### ISSUE TITLE
form.find does not find controls in nested ControlGroups

### ISSUE THREAD

**Issue by choeller** [angular/angular#5024]
Having a form defined like:

```
        this.form = fb.group( {
            ...
            notifications: fb.group({
                 email: ["", emailValidator],
                 favorite: [false]
            })
```

When changing the email field to an invalid E-Mail I want to display the error right below the field. Currently I have to iterate deep into the tree, which makes it really difficult to come up with a generic solution for finding the errors for a specific field:

```
 <div class="error-message" *ng-if="!form.find('notifications').controls.email.valid
                                     && form.find('notifications').controls.email.touched">
      <div *ng-if="form.find('notifications').controls.email.hasError('invalidEMail')">
        <div>Email is not valid</div>
     </div>
 </div>
```

This makes it pretty complicated to come up with a generic solution like the one in the forms-example in angular2 repo. Also this is really error prone - especially with deeper structures. 

My suggestion would be to offer a possibilty to make a deep search or to pass the whole path to the find method. Maybe something like this:
```
form.findDeep('email').valid
``` 
or this
```
form.find('notifications.email').valid
```

**Comment by Krustie101** [comment]
Did you try `"notifications/email"` for  your path? You should also be able to use `['notifications','email']`.

**Comment by choeller** [comment]
@Krustie101  Great - thank you. That's totally working for me... So I'm gonna close this one.

**Comment by yuanfeiz** [comment]
FYI, the `find` has been changed to `get` since the final release. To access the errors by the control path, there are two methods:
1. `getError(errorCode, path?: string[])`
2. `hasError(errorCode, path?: string[])`

**Comment by webia1** [comment]
Understanding question: there is still no "deepFind" isn't it ? How can I find a control in a very deep angular reactive form today?
