### ISSUE TITLE
Firebase or PWA is not supporting ng V16

### ISSUE THREAD

**Issue by Anoopkumarseth** [angular/angular#50249]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, core, service-worker, Don't known / other

### Is this a regression?

Yes

### Description

![image](https://github.com/angular/angular/assets/30388576/1b8bcc5c-37ea-4298-b7bf-05b827f8db75)

cant add PWA or Firebase in Application in Ng V16. #firebase #pwa

I have tried to install & uninstall angular 4-5 times but not been fixed. 

### Please provide the exception or error you saw

```true
Anoop Seth@DESKTOP-SVHTELE MINGW64 /f/work/swadspecial (master)
$ ng add @angular/fire
Skipping installation: Package already installed
Package "@angular/fire" was found but does not support schematics.

Anoop Seth@DESKTOP-SVHTELE MINGW64 /f/work/swadspecial (master)
$ ng add pwa
ℹ Using package manager: npm
✔ Found compatible package version: pwa@1.9.7.
✔ Package information loaded.

The package pwa@1.9.7 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
Package "pwa" was found but does not support schematics.
```

### Anything else?

$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.0.1
Node: 18.16.0
Package Manager: npm 9.6.6
OS: win32 x64

Angular: 16.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.1
@angular-devkit/build-angular   16.0.1
@angular-devkit/core            16.0.1
@angular-devkit/schematics      16.0.1
@angular/fire                   0.0.0
@schematics/angular             16.0.1
rxjs                            7.8.1
typescript                      5.0.4

**Comment by alan-agius4** [comment]
There are two problems here. 

- To create a PWA you are using the command. The correct command is `ng add @angular/pwa`. 
- `@angular/fire` does not yet support v16. See https://github.com/angular/angularfire/issues/3353
