### ISSUE TITLE
Signals without ngZone not yet working?

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/angular#50259]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I created small demo for my team to learn signals, but when I turn ngZone off the change detection with signals doesn't work. Not sure if I'm doing something wrong or is it not working yet?
here's a demo: [https://stackblitz.com/edit/angular-qk8yei?file=src/main.ts](https://stackblitz.com/edit/angular-qk8yei?file=src/main.ts)

I'm bootstrapping App component like this: 
```
bootstrapApplication(App, {
  providers: [{ provide: NgZone, useClass: ɵNoopNgZone }],
});
```
I was expecting those signals to still re-render...

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 16
```

**Comment by JeanMeche** [comment]
Yes, signals are still hooked to Zone.js. 

* Updating a signals calls the same code as `markForCheck()`
* `effect()` is hooked on Appref.tick
