### ISSUE TITLE
Prevent duplication of pushState history

### ISSUE THREAD

**Issue by dgreif** [angular/angular#5025]
When the same `[router-link]` is clicked multiple times, multiple history entries are created with the exact same URL.  Would it be possible to compare the current URL of the page to the destination URL, and not call pushState if the URL is already correct?  

From a user perspective, if I am on page A and click a link to page B, then click the link to page B again, I should only have to press the back button once to get back to page A.

**Comment by estsauver** [comment]
Hey @dgreif, I started working on this and am having trouble making a failing test case. I wrote this test case, which i think should capture the behavior you're describing, but it's still passing. 

I'm pretty new to working on Angular though, and so if anyone has a suggestion for where I should be looking, that'd be neat!

```diff
diff --git a/modules/angular2/test/router/router_spec.ts b/modules/angular2/test/router/router_spec.ts
index 1fb2a3f..7efcc56 100644
--- a/modules/angular2/test/router/router_spec.ts
+++ b/modules/angular2/test/router/router_spec.ts
@@ -104,6 +104,20 @@ export function main() {
              });
        }));
 
+    iit('should not push a history change when currentLocation=newLocation',
+      inject([AsyncTestCompleter], (async) => {
+        var outlet = makeDummyOutlet();
+
+         router.registerPrimaryOutlet(outlet)
+             .then((_) => router.config([new Route({path: '/b', component: DummyComponent})]))
+             .then((_) => router.navigateByUrl('/b', false))
+             .then((_) => router.navigateByUrl('/b', false))
+             .then((_) => {
+               expect(location.urlChanges).toEqual(['/b']);
+               async.done();
+             });
+      }));
+
     it('should navigate after being configured', inject([AsyncTestCompleter], (async) => {
          var outlet = makeDummyOutlet();
 ```

**Comment by robwormald** [comment]
@estsauver you may be able to capture this in an e2e test, as it better emulates using this in an actual browser. have a look in the `modules/playground/routing` folder

**Comment by estsauver** [comment]
@robwormald thanks for the suggestion, I'll look into it!

**Comment by ryzy** [comment]
@mhevery should this be re-assigned to beta.03 milestone now, since we already have beta.02 released?

**Comment by dheeran1** [comment]
+1

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router robust.

Since the issue has been fixed in the new router, I'm closing it.
