### ISSUE TITLE
Angular Update Guide missing v16 steps

### ISSUE THREAD

**Issue by drullo** [angular/angular#50265]
### Describe the problem that you experienced

The [Angular Update Guide](https://update.angular.io/?v=15.0-16.0) steps for 15=>16 migration don't include the relevant 'ng update' commands.  There are no instructions in this section of the guide for actually updating the packages.

### Enter the URL of the topic with the problem

https://update.angular.io/?v=15.0-16.0

### Describe what you want to experience that would fix the problem

Documentation should be updated to include the missing steps

**Comment by JoostK** [comment]
Duplicate of https://github.com/angular/angular-update-guide/issues/219
