### ISSUE TITLE
About RouterConfig return 404 page

### ISSUE THREAD

**Issue by Yunlong2cn** [angular/angular#5026]
Just config like this:
@RouteConfig([
	{ path: '/', component: HomeComponent, as: 'HomeComponent' },
	{ path: '/book', component: BookComponent, as: 'BookComponent' },
	{ path: '/found', component: FoundComponent, as: 'FoundComponent' },
	{ path: '/me', component: MeComponent, as: 'MeComponent' },
])

click the link in app.html is good,but when i press F5 or input the url in browser,it show me 404 page,how to solve this kinds of problem?
someone will help me?thanks!

**Comment by pkozlowski-opensource** [comment]
@Yunlong2cn see discussion in https://github.com/angular/angular/issues/4735

**Comment by Yunlong2cn** [comment]
@pkozlowski-opensource sorry,i think i can't understand what the mean about #4735 ,will u give me a simple demo?for eg: http://plnkr.co/edit/iRUP8B5OUbxCWQ3AcIDm

**Comment by pkozlowski-opensource** [comment]
@Yunlong2cn you need to configure your _server_ to return your index.html for 404 requests. The exact configuration will depend on your web server and obviously can't be demonstrated in a plunker.

Please ask support questions on https://gitter.im/angular/angular

**Comment by Yunlong2cn** [comment]
thanks @pkozlowski-opensource ,what ur mean is i should deal this kinds of problems with server by http code (301) ?
