### ISSUE TITLE
signal does not update UI when set in a ResizeObserver callback

### ISSUE THREAD

**Issue by haigha106** [angular/angular#50266]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

when updating a signal inside a ResizeObserver callback, the UI does not update to reflect the new value

`
item = signal<string>('0 x 0');
`

      this.resizeObserver = new ResizeObserver((entry) => {
            const size =  entry[0].contentBoxSize[0].inlineSize + ' x ' + entry[0].contentBoxSize[0].blockSize;
            console.log('AppComponent , items', size);
      
            this.item.set(size);
        });
        this.resizeObserver.observe(this.host.nativeElement);

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-rgdde7?file=src/main.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 16
Node 16.18.1
Package manager: npm
OS: Windows 10
```

**Comment by JoostK** [comment]
This is because `ResizeObserver` is not patched by zone.js by default (you need to import a patch yourself if you want to patch it) and using signals today does not schedule any change detection, that is still done by zone.js.
