### ISSUE TITLE
Docs - wrong component name 

### ISSUE THREAD

**Issue by MohamedMF2** [angular/angular#50277]
### Describe the problem that you experienced

as hightlighted in red in the attched screenshot, 
I could be mistaken or got it wrong 
Is it should be home.component.ts ?

### Enter the URL of the topic with the problem

https://angular.io/tutorial/first-app/first-app-lesson-03

### Describe what you were looking for in the documentation

this could be a typying mistake or me getting it wrong 

### Add a screenshot if that helps illustrate the problem

![Screenshot_2](https://github.com/angular/angular/assets/47474858/857396ae-7c3c-4529-95e2-f1f30f2b3dff)

### If this problem caused an exception or error, please paste it here

```true
No
```

**Comment by JeanMeche** [comment]
Yes you're right !

**Comment by MohamedMF2** [comment]
You're welcome 

Have a good one
