### ISSUE TITLE
Errors in auxiliary route

### ISSUE THREAD

**Issue by yfain** [angular/angular#5027]
Had issues with opening Auxiliary route using the syntax that @btford showed at Angular Connect: `<a [router-link]="['/', ['Chat']] ">Chat</a>`.  It gives syntax errors during the runtime.

@brandonroberts suggested the fix using `<a href="/#/(chat)">Chat</a></div>`.  Now the aux route opens the required component but shows errors in the console and breaks the URLs of the other routes.  When I run it locally (not in the plunker) and open the Chat route, the URL localhost:8080/#(chat) remains unchanged no matter what link I click.The Back button doesn't work either.

Here's the plank: http://plnkr.co/edit/jZv8jj?p=preview.

**Comment by brandonroberts** [comment]
@yfain Using an that aux route in your plunk doesn't exist in alpha 45. Also there isn't a way to generate links for aux routes yet. Here is an updated plunk with a non router-link href that works.

http://plnkr.co/edit/jZv8jj?p=preview

**Comment by yfain** [comment]
Thank you @brandonroberts !

**Comment by yfain** [comment]
The code sample by @brandonroberts navigates to the aux route, but the Dev Tools console shows the  TypeError: "Cannot read property 'component' of undefined" and the Back button on the browser doesn't work. The plunk is the same: http://plnkr.co/edit/jZv8jj?p=preview 

 http://plnkr.co/edit/JsZbuR?p=preview

**Comment by brandonroberts** [comment]
@yfain I believe that bug has already been fixed and won't be there with the next release.

**Comment by yfain** [comment]
As of Alpha 47 the syntax of the aux route changes, and I've updated the plunk at #5122

**Comment by talmog** [comment]
Hi, thank you for the example, it is very useful, but how can you add parameters to an aux route?

**Comment by brandonroberts** [comment]
@talmog you can't add parameters to an aux route currently. Its on the todo list

**Comment by talmog** [comment]
I was actually able to solve this... I kept the path without parameters like so:
{aux:'/mainPanel', name: 'MainPanel',   component: MainPanelComponent}
but passed parameters in the link. that seemed to work...
Why should I not use aux?

**Comment by brandonroberts** [comment]
@talmog they still need a good bit of work. I think its more trouble than its worth to use them at the moment.
