### ISSUE TITLE
After hydration, all http calls are still cached

### ISSUE THREAD

**Issue by elgerm** [angular/angular#50271]
### Which @angular/* package(s) are the source of the bug?

core, Don't known / other

### Is this a regression?

Yes

### Description

Maybe I'm missing something, but, 
setting `provideClientHydration() ` in the app module causes all http requests done with HttpClient to be cached.
I get that this is needed to do rehydration, but after hydradion httpclient should just work as expected, that is not cache requests.

To reproduce:

1. set provideClientHydration() in app module.

2. do some same http requests with httpClient

3. Requests are cached, no actual http call is made.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.1
Node: 18.16.0
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 16.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker, youtube-player

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.1
@angular-devkit/build-angular   16.0.1
@angular-devkit/core            16.0.1
@angular-devkit/schematics      16.0.1
@nguniversal/builders           16.0.1
@nguniversal/express-engine     16.0.1
@schematics/angular             16.0.1
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by AndrewKushnir** [comment]
@elgerm could you please provide a bit more information about the expected vs actual behavior?

By default the `provideClientHydration()` enables HttpClient caching on the server for all requests, transfers the data to the client and in the browser, no duplicate requests are being made (if they were made on the server already). After hydration (once application becomes stable, i.e. when `ApplicationRef.isStable` emits `true`), HttpClient switches back to the regular mode of making requests. If you want to avoid HttpClient request caching altogether, you can use the `withNoHttpTransferCache()` like this: `provideClientHydration(withNoHttpTransferCache())`. Also, I want to link issue #50117 (partially related), which proposes an API to have a fine-grained control on which requests should be cached.

// cc @alan-agius4

**Comment by elgerm** [comment]
Ah, I checked to see if my project becomes 'stable' and it doesn't for some obscure reason (which is quite hard to find out btw). 

But this does mean that angular apps will silently be in an forever cache mode whenever an angular app doesn't become stable. Sure you can test this, but there are many reasons why the app isn't stable (think imported library). So I think, just like the serviceworker registration, there should be an optional observable to be passed that we can complete when we think the app is stable.

**Comment by AndrewKushnir** [comment]
@elgerm thanks for additional information. I've created a new ticket to add a warning that would indicate that the `ApplicationRef.isStable` doesn't emit after some time, see #50285.

> So I think, just like the serviceworker registration, there should be an optional observable to be passed that we can complete when we think the app is stable.

We do have plans to research APIs like this, but there are no ETAs at this moment. We'll be sharing more info as we make more progress on this.
