### ISSUE TITLE
is signal support sharing data between child and parent ?

### ISSUE THREAD

**Issue by dzurrahman** [angular/angular#50299]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

im just update my core library to angulat 16. just wanna know, is signal support sharing data between child and parent right now? cause i got message error 

`Type '{ title: string; showTab: boolean; }[]' is missing the following properties from type 'WritableSignal<dataTitleData[]>': set, update, mutate, asReadonly, [SIGNAL]`

Thanks,

### Proposed solution

-

### Alternatives considered

-

**Comment by JeanMeche** [comment]
Hi, can you share a bit more code to understand what triggered that error ?

**Comment by dzurrahman** [comment]
here's the code

child component
```
export class GdCompTabStepperComponent implements OnInit {

  @Input() dataTitle = signal<dataTitleData[]>([])
  
}
```


parent component
```
@Component({
  selector: 'greatday-gdx-testing',
  templateUrl: `
  <gd-comp-tab-stepper [dataTitle]="dataStepper" >
    </gd-comp-tab-stepper>
  `
})
export class GdxTestingComponent {
  public dataStepper = [
    {
      title: 'sample',
      showTab: true,
    }
}
```

**Comment by JeanMeche** [comment]
There is a type missmatch. `dataStepper` is an array, while `dataTitle ` is waiting for a signal.

**Comment by dzurrahman** [comment]
> There is a type missmatch. `dataStepper` is an array, while `dataTitle ` is waiting for a signal.

Sorry, my mistake, the parent should use signal to for pass the data to child component

```
export class GdxTestingComponent {
  public dataStepper = signal([
    {
      title: 'sample',
      showTab: true,
    }])
}
```

thanks @JeanMeche ,
