### ISSUE TITLE
Enhancement: Event Handling in Effect Function for Angular Signals

### ISSUE THREAD

**Issue by fayeBabacar78** [angular/angular#50300]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

The current implementation of the effect function in Angular lacks a built-in mechanism to hook into specific events within the effect function. This limitation becomes apparent when developers need to track and respond to specific events triggered by changes to the underlying data. It would be beneficial to have a way to register event handlers within the effect function to handle custom events and access relevant data associated with those events.

This would prevent having multiple effect() functions in our constructor if we want to perform side effects whenever our signals change.

`effect(() => {
          console.log("--> fullName is  updated -> " + this.fullName());
    });`

`effect(() => {
      console.log("--> todos updated  -> " + this.todos());
    });`

`effect(() => {
      console.log("--> Side effet contDouble -> " + this.countDouble());
    });`

### Proposed solution

To address this limitation, a new feature could be introduced to enhance the effect function in Angular. This enhancement would allow developers to specify event handlers within the effect function, enabling them to react to specific events triggered by changes to the data. The event handlers would receive relevant data or event-specific parameters as arguments, providing flexibility in handling different types of events. This enhancement would empower developers to write cleaner and more concise code by encapsulating event handling logic within the effect function itself.

Example:

`effect(event => {
  // Handle the data change event
  console.log('Data changed:', event.value);
  // ...
});`

### Alternatives considered

Developers may resort to workarounds such as manual event tracking outside of the effect function or implementing custom event handling mechanisms. However, these alternatives can introduce additional complexity, reduce code maintainability, and hinder the overall developer experience. Having a built-in event handling feature within the effect function would provide a more streamlined and standardized approach, eliminating the need for custom event handling implementations.

**Comment by alxhub** [comment]
By event, do you mean _which_ signal caused the effect to run?

**Comment by fayeBabacar78** [comment]
Yes exactly but also if we could get the value of the updated signal.

Let's have look at this code for exemple:

```ts
 toggleTodo = (todo: Todo, done: boolean) => this.todos.mutate(array => {
    const index = array.findIndex(t => t.id === todo.id);
    if (index >= 0) {
      array[index].done = done;
    }
  });
```ts

It would be nice to get the value of the updated todo directly from the effect. I do not know about the feasibility since an effect is triggered only when the signal it reads is updated.

**Comment by pkozlowski-opensource** [comment]
> Yes exactly but also if we could get the value of the updated signal.

An effect might depend on several signals and only some of those might have changed to trigger the effect so I think that such API would grow more elaborate pretty soon.

Having said this I don't think I understand the motivation... Given the `toggleTodo` example, what is the effect that you are trying to write? Why accessing the current value of the signal is not enough?

> This enhancement would allow developers to specify event handlers within the effect function, enabling them to react to specific events triggered by changes to the data.

I still think that there is confusion around the "event" here. Generally speaking we want effect to fire where data changed and always work with the fresh / current data. Regardless of how this data changed.

> The event handlers would receive relevant data or event-specific parameters as arguments, providing flexibility in handling different types of events. This enhancement would empower developers to write cleaner and more concise code by encapsulating event handling logic within the effect function itself.

Could you please provide code example with the current APIs and illustrate how the proposed enhancement would improve the situation? 

We are happy to add new APIs and improvements but I don't think we've put a finger on the exact scenario just yet. Could you please clarify with the exact code examples?

**Comment by bilalahmed24** [comment]
> By event, do you mean _which_ signal caused the effect to run?

I have recently started using signals. It's really difficult to debug issues within effect since I got no call stack to trace back to the originator of that effect.
For the sake of example, let's I have a signal in a service[serviceA] which is updated by other related services[serviceB, serviceC]. Within a component I have created an effect which uses serviceA signal.

For debugging purpose, determining which service invoked that effect, I got no call stack to trace back to the originator.

**Comment by pkozlowski-opensource** [comment]
@fayeBabacar78 as previously commented I'm not clear on the use-case and we don't want to extend the API surface with the strong justification.

@bilalahmed24 we do have plans on adding support for signals in dev tools to help with debugging.
