### ISSUE TITLE
[Docs] Signals and forms

### ISSUE THREAD

**Issue by ampmonteiro** [angular/angular#50307]
### Describe the problem that you experienced

Why does not any mention how signal will the forms?
How this should work with template driven forms?
Or signals will replace rxjs in reactive forms?

So a simple  experiment that i did was this way:

```js

import { Component, computed, signal } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule],
  template: `
    <form>
      <input [value]="user()" #ur (input)="user.set(ur.value)" />
      <input [value]="last()" #lt (input)="last.set(lt.value)" />
      <button>Send</button>
    </form>
    user: {{ user() }} <br />
    last : {{ last() }} <br />

    joined: {{ fullName() }}
  `,
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  user = signal('');
  last = signal('');

  fullName = computed(() => `${this.user()} ${this.last()}`);
}


```

### Enter the URL of the topic with the problem

https://angular.io/guide/signals

### Describe what you were looking for in the documentation

It should contains the scenarios for the use of the signals.

- if it is for simple things, you should give some examples
- if it is for better communication better parent -> child component ( inputs)
- if it is for better global state management with service
- if you should be using with forms or not

**Comment by dcanevarollo** [comment]
I agree. As the idea is to make reactivity easier, that'd make sense. Besides, in my opinion, a form is a good use case to show how `Signals` will work in a more 'real-life' situation.

**Comment by giacomo** [comment]
Another question here should be, how signals should interact with ngModels?

Is this really the way to go when implementing ngModel?
```
[ngModel]="filter()" (ngModelChange)="filter.set($event)"
```

i was expecting that some magic will happen when used with signals, like:

```
[(ngModel)]="filter"
```

Sort of passing the signal to avoid using ngModelChange.

**Comment by pkozlowski-opensource** [comment]
There is currently no built-in integration of signals with `ngModel` so the only way for now is using `[ngModel]="filter()" (ngModelChange)="filter.set($event)"`

**Comment by ProximaB** [comment]
This is significant especially when using OnPush detection strategy, some better integrations would be welcome

**Comment by dev-anton-ko** [comment]
> There is currently no built-in integration of signals with `ngModel` so the only way for now is using `[ngModel]="filter()" (ngModelChange)="filter.set($event)"`

I could not even imagine this aspect could be missed. I mean two-way binding in general. 
Are there any plans related to this?

**Comment by JeanMeche** [comment]
I'll close this because `model` & double binding with signals are now possible. 

Also signal intergrations into forms is still to be discussed within the team.
