### ISSUE TITLE
remove es5build.js and npm:gulp-traceur

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#5030]
es5build.js is obsolete and only confuses people, once that's gone we can remove gulp-traceur which only bloats our npm dependency tree.

**Comment by pkozlowski-opensource** [comment]
We've got a PR for this one already: https://github.com/angular/angular/pull/4454

**Comment by IgorMinar** [comment]
ah.. I didn't realized that hasn't landed yet. I thought this was a left
over that we missed.

**Comment by pkozlowski-opensource** [comment]
Given that #4454 is blocked I've sent #5144 to remove es5build.js (gulp-traceur is already gone from the dependencies in the published package.json)
