### ISSUE TITLE
Router with component input binding and default values for inputs

### ISSUE THREAD

**Issue by Timmeeeey** [angular/angular#50301]
### Describe the problem that you experienced

When using `withComponentInputBinding()` then inputs with no matching route data are set to `undefined`.
This is described here:

https://github.com/angular/angular/blob/85b4941be137a2fcdc664dc870e408dd72ad7de7/packages/router/src/directives/router_outlet.ts#L384-L386

But not in the documentation in angular.io.

When using default values like `@Input() myInput = 'test';` then this is not working anymore.

What is the recommended way of setting input defaults?
In ngOnInit()?

```typescript
 ngOnInit(): void {
  this.myInput ??= 'test';
}
```

### Enter the URL of the topic with the problem

https://angular.io/guide/router#getting-route-information

**Comment by alxhub** [comment]
Use an input setter which coerces `undefined` to the value you want it to be. This will be easier to implement when the upcoming input transform functionality lands, but for now you can split the input into a getter/setter pair and handle `undefined` in the setter.

**Comment by epelc** [comment]
Perhaps the docs for https://angular.io/api/router/withComponentInputBinding should have something about this as well? Kind of hard to find at the moment.
