### ISSUE TITLE
Not being able to use "effect()" or "takeUntilDestroyed()" inside dynamically created component

### ISSUE THREAD

**Issue by jordimarimon** [angular/angular#50319]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I have searched through the issues and I wasn't able to find anything related to it. Feel free to close this issue if you think it's duplicated.

I updated my project to Angular v16 and I wanted to test a little bit the new Signals API.

I have some components that are created dynamically using the `createComponent()` API.

When I try to use `effect()` or `takeUntilDestroy()` inside these dynamically created components I get an error that I can't use them because I'm not inside an injection context.

I thought a component was a valid injection context.

What is more surprising is the fact that `toSignal()` and `inject()` do work fine inside the component but not `effect()` or `takeUntilDestroy()`. This for me is a surprise because when I look at the source code of `toSignal()` I see that it's being called `assertInInjectionContext` and it doesn't throw any error.

I have attached a codesandbox with the reproduction but I will also explain what it's happening:

- I have the `AppComponent` that has a simple button that when clicked opens a native dialog and inside it, it renders a component.

- The service for creating the component is called `DialogService` and there you can find how the component is created dynamically (feel free to correct me if the way I'm creating the component is not correct).

- Finally we have the `DialogComponent` that is the component that will be rendered inside the native dialog

- Inside the `DialogComponent` as an example I'm using `inject()`, `toSignal()`, `effect()` and `takeUntilDestroy()`

- You can comment the lines of the `effect()` and `takeUntilDestroy()` that are causing the error and leave the `effect()` and `takeUntilDestroy()` that receive as arguments the injector and the `DestroyRef` and you will see that everything now works fine.

### Please provide a link to a minimal reproduction of the bug

CodeSanbox:
https://codesandbox.io/p/sandbox/cold-sunset-csz6b2?file=%2Fsrc%2Fapp%2Fapp.component.ts%3A6%2C20

Github repo:
https://github.com/jordimarimon/test-injection-context-angular

### Please provide the exception or error you saw

```true
ERROR Error: NG0203: effect() can only be used within an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
    at assertInInjectionContext (core.mjs:10490:15)
    at effect (core.mjs:12229:27)
    at ModalComponent.ngOnInit (modal.component.ts:48:15)
    at callHookInternal (core.mjs:3804:14)
    at callHook (core.mjs:3831:13)
    at callHooks (core.mjs:3786:17)
    at executeInitAndCheckHooks (core.mjs:3736:9)
    at refreshView (core.mjs:12417:21)
    at detectChangesInternal (core.mjs:12344:9)
    at RootViewRef.detectChanges (core.mjs:12874:9)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.1
Node: 18.12.1
Package Manager: npm 9.5.1
OS: linux x64

Angular: 16.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.1
@angular-devkit/build-angular   16.0.1
@angular-devkit/core            16.0.1
@angular-devkit/schematics      16.0.1
@schematics/angular             16.0.1
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by JeanMeche** [comment]
Hi, you're not a an injection context in `ngOnInit()`, only the constructor is.

**Comment by jordimarimon** [comment]
You're totally right!

My bad, and I did read a few days ago the documentation you made about injection contexts (https://github.com/angular/angular/blob/148fedb298ca06780132eb0969e1979be86c691f/aio/content/guide/dependency-injection-context.md) and in that moment I didn't catch the fact that lifecycle hooks are not inside an injection context!

Thanks! I will close the issue!
