### ISSUE TITLE
Docs: Tutorial- First Angular app- Missing asset- "example-house.jpg"

### ISSUE THREAD

**Issue by MohamedMF2** [angular/angular#50329]
### Describe the problem that you experienced

- Before the end of each lesson we confirm that  the app is rendered without problems , a missing image in the assets folder with a name which was mentioned in code will cause a problem : 

 `src/app/home/home.component.ts` file -> `HomeComponent ` component class -> `housingLocation` property-> `photo` key
"example-house.jpg" will result in
actual Result:
![Screenshot_4](https://github.com/angular/angular/assets/47474858/33003d30-93f6-4cf8-8142-60acf364f151)

and in console 

 `Failed to load resource: the server responded with a status of 404 (Not Found)`

![Screenshot_5](https://github.com/angular/angular/assets/47474858/e44b3cd2-7642-4bd7-966f-9d2d47df0d34)

while in the following screenshot the Expected Result inthe Docs :
![Screenshot_3](https://github.com/angular/angular/assets/47474858/cd6c6775-1f9d-4d61-b4d7-a29d21ea6757)

### Enter the URL of the topic with the problem

https://angular.io/tutorial/first-app/first-app-lesson-07

### Describe the actions that led you to experience the problem

following the tutorial 

### Describe what you want to experience that would fix the problem

adding the image to the assets would be helpful for the newpies to angular

**Comment by jondomin** [comment]
@JeanMeche the image specified `assets/example-house.jpg` simply doesn't exist in the example code provided in the tutorial.  Can you include that in the source code on lesson 7?
