### ISSUE TITLE
providedIn Component

### ISSUE THREAD

**Issue by sharshuv-quotient** [angular/angular#50337]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Today, when you want to have providers in a component level, you have to add them explicitly to the `providers` list in the `Component` decorator. 

This in unhealthy since it forces the component to "know" of all the providers that wish to register themselves. This encourages code that is not modular and not well split, since:

1. If I want to add a new provider, I have to not only define it on one file, I also have to provide it in another place (the component). before I want to consume it. Ideally - if I can define it in one place, it would make my code more modular. 
2. If I want to split a component-level provider to smaller services - I need to add all of them to the component providers list, which makes for a cumbersome code. It's likely that I will be discouraged from doing so for that reason, even though splitting my code to smaller service might make it easier to manage. 

### Proposed solution

Add support for specifying a component in the `providedIn`, like was done for modules.

For example:

```
@Injectable({
  providedIn: MyComponent
})
class MyService {
  ...
}
```

Or, if I'm using an injection token:
```
const MY_TOKEN = new InjectionToken('MY_TOKEN', {
  providedIn: MyComponent,
  factory: () => { ... }
});
```

### Alternatives considered

The alternative is to explicitly list the the new provider in the component decorator, which is not ideal because of the reason I described above. I could not find any workaround that enable me to accomplish this with the current tools. 

I would be happy to have a go in trying to implement this, if someone with more experience with Angular source code can point me at the right direction.

**Comment by alxhub** [comment]
While this is an interesting idea, it's likely not one we'll implement for a few reasons:

One, `providedIn` is designed to allow services to be tree-shaken away if nothing references them. When a service is provided at the component/directive level, however, it's almost always a key part of how that component or directive functions, and is guaranteed to be used. Tree-shaking is not nearly as impactful for component providers as a result.

Secondly, Angular's component DI is highly optimized, and the set of tokens available on a node injector is fixed when that node is created. Implementation-wise, we don't have a way of adding tokens to this set after it's been created, and we'd have to majorly overhaul our component DI system to do so.
