### ISSUE TITLE
The "Hierarchical injectors" page describes a white flower emoji as yellow on Windows

### ISSUE THREAD

**Issue by garrettld** [angular/angular#50347]
### Describe the problem that you experienced

The `blossom` emoji is a flower with white petals on Windows and a flower with yellow petals on other platforms (see https://unicode.org/emoji/charts/full-emoji-list.html#1f33c), but the "Hierarchical injectors" documentation refers to this emoji as a "yellow flower". This document also uses the sunflower emoji, which could also be described as a yellow flower.

### Enter the URL of the topic with the problem

https://angular.io/guide/hierarchical-dependency-injection

### Describe what you were looking for in the documentation

When following up on #50270 I referenced this document to double check my understanding of the concept of a "host" and how the `Host` flag works, and was confused for a moment when an apparently white flower was called "yellow flower".

### Describe what you want to experience that would fix the problem

A different emoji that can be named consistently and is visually distinct from the other emojis used, on all platforms.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/12160067/cc7186ec-5dc7-44c0-a7c2-4691318ebb48)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
OS: Windows
Browser: any (tested on Chrome, Edge, & Firefox)
```

### Provide any additional information here in as much as detail as you can

```true
I'd be happy to open a PR for this.
```

**Comment by JeanMeche** [comment]
> I'd be happy to open a PR for this.

Go for it 😉
