### ISSUE TITLE
Same component added in same html page not giving error message server stops working. 

### ISSUE THREAD

**Issue by rajthilak04** [angular/angular#50342]
### Which @angular/* package(s) are the source of the bug?

compiler, core, Don't known / other

### Is this a regression?

Yes

### Description

**Html page name:** shopping-list.component.html
**Selector name:** app-shopping-list
Including same selector name in the same html page

&lt;div class="row">
    &nbsp;&nbsp;&nbsp;&nbsp;&lt;div class="col-md-12">
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;app-shopping-list>&lt;/app-shopping-list>
    &nbsp;&nbsp;&nbsp;&nbsp;&lt;/div>
&lt;/div>

Note: Server stops instead of giving error message or alert information.

### Please provide the exception or error you saw

```true
Server stopped working instead of giving error or alert message.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.8
Node: 16.14.0
Package Manager: npm 9.6.4
OS: win32 x64

Angular: 15.2.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router     

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.8
@angular-devkit/build-angular   15.2.8
@angular-devkit/core            15.2.8
@angular-devkit/schematics      15.2.8
@angular/cli                    15.2.8
@schematics/angular             15.2.8
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by rajthilak04** [comment]
https://github.com/rajthilak04/repro-app.git

![image](https://github.com/angular/angular/assets/3745683/0867d712-5f61-4205-a24e-e1333bc0a1f5)

**Comment by JeanMeche** [comment]
You're recursively creating the same component, that cannot work without a condition to stop that recursion.

**Comment by rajthilak04** [comment]
Ok. Can we show error message or alert info for this kind of thing?

**Comment by alan-agius4** [comment]
Hi @rajthilak04,  the error itself does indicate that there is infinite recursion. Improving the error here is tricky as we'd need to have a max depth limit somewhere (i.e. how deep component nesting can be. This depth would also need to be different as the call stack size various between different VMs.
