### ISSUE TITLE
SVG not rendering correctly (xlink)

### ISSUE THREAD

**Issue by ziaukhan** [angular/angular#5034]
The textPath is not showing correctly in Alpha 45:

    @Component({
     selector: 'vbutton',
     template: `<div><svg xmlns="http://www.w3.org/2000/svg"   
     xmlns:xlink="http://www.w3.org/1999/xlink" 
                    version="1.1" height="1000" width="1000">
                    <defs>
                        <path id="myTextPath" d="M 50,100 Q 150,50 250,100" />
                    </defs>

                    <circle cx="100" cy="100" r="40" stroke="white" stroke-width="1" fill-opacity="0" />
                    <text fill="steelblue" font-size="20">
                        <textPath xlink:href="#myTextPath">This is not showing in Alpha 45!</textPath>
                     </text>
                    </svg>
               </div>
                `
    })
    export class VButton{}

**Comment by wfalkwallace** [comment]
see #4506

**Comment by pkozlowski-opensource** [comment]
Fixed in master.
