### ISSUE TITLE
[update.angular.io] missing the command to execute update Angular Material to v16 and rxjs version recommended

### ISSUE THREAD

**Issue by ampmonteiro** [angular/angular#50358]
### Describe the problem that you experienced

Three problems in https://update.angular.io:

1.  missing to show the command responsible to update deeps to v16 ( this was in previous versions)
2.  missing to show the command to update the angular material when checked `i use Angular Material` option
3. It is keeping missing for each update version which version of RxJS should be used

### Enter the URL of the topic with the problem

https://update.angular.io/?v=15.0-16.0

### Describe what you were looking for in the documentation

- Like previous versions of updates, should be a indication of the command to update to version 16
- Also like previous version of updates, shoud be a indicatio of the command to update Angular Material to version 16
- And for each update version should be mention the recommend version of RxJS, similar that it is done for typescript or node (  also already mention in  #47757 issue)

### Describe the actions that led you to experience the problem

choose the version of Angular to be update 15 -> 16
 when checked `i use Angular Material` option

### Describe what you want to experience that would fix the problem

this command should added:
`ng update @angular/core@16 @angular/cli@16`
`ng update @angular/material@16`

And  mention the recommend version of RxJS for each version of Angular, since it is one of core libs like typescript.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/31895754/1eadc252-4f51-4def-8c01-5fbd24dbb2e9)

**Comment by JeanMeche** [comment]
Hi, there is already an issue opened for your first point : angular/angular-update-guide#219

**Comment by JeanMeche** [comment]
Tracked at : 
* angular/angular-update-guide#219
