### ISSUE TITLE
Field read throws Exception in SVG

### ISSUE THREAD

**Issue by ziaukhan** [angular/angular#5035]
Fill read in SVG is throwing an exception in Alpha 45:
<img width="1382" alt="screenshot" src="https://cloud.githubusercontent.com/assets/545458/10858545/aa484c38-7f77-11e5-8ea8-08b14e307026.png">

    @Component({
    selector: 'vbutton',
    template: `<div><svg xmlns="http://www.w3.org/2000/svg"  
                    version="1.1" height="500" width="500">

                    <circle cx="100" cy="100" r="40" stroke="white" stroke-width="1" [fill]="fill" />
                    </svg>
                    <div>{{fill}}</div>
               </div>
                `
    })
    export class VButton { 
     public fill: string = "blue";  
    }

**Comment by ericmartinezr** [comment]
According to MDN documentation [fill](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill) is an attribute, so you must use `[attr.fill]` instead.

**Comment by ziaukhan** [comment]
@ericmartinezr Thank you so much, this solved it.
