### ISSUE TITLE
my library not compatible with Ivy

### ISSUE THREAD

**Issue by jasonliao-cb** [angular/angular#50363]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I have a library built with Angular 11 https://github.com/jasonliao-cb/oneiam-js-library, but it seems not compatible with Angular Ivy. I have tried the settings and commands, but I still can't make it work for Ivy. 

A demo project for testing, https://github.com/jasonliao-cb/oneiam-demo, if import the package from the source code, it works without any error.
if I import it from the package and when running: ng serve, the error comes.

Is there anything I missed or I can't make it a library compatible with Ivy this way? please suggest.

### Please provide a link to a minimal reproduction of the bug

https://github.com/jasonliao-cb/oneiam-demo

### Please provide the exception or error you saw

```true
Error: node_modules/@cb/oneiam/angular/module.d.ts:3:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (@cb/oneiam/angular) which declares OneiamModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

3 export declare class OneiamModule {
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.2.18
Node: 12.22.12
Package Manager: npm 6.14.16
OS: darwin x64
```

### Anything else?

what I have to change to make it work with Ivy? I have to support the Ivy(using Angular 11,12,13,and 14) and View Engine(before Angular 11)

thanks for any suggestion.

**Comment by alan-agius4** [comment]
Angular libraries are typically only backwards compatible for 2 major versions. An Ivy compiled library cannot be used with Angular View Engine.

It also appears that you are using a Webpack to build your library and not the officially supported tools (ng-packagr and the Angular CLI). The Angular team does not provide support for custom tooling.

It is worth mentioning that Angular versions prior to 14 are no longer supported.
