### ISSUE TITLE
After the Angular is upgraded from 14.x to 15.x, browsers of earlier versions of the Chromium 66 kernel are incompatible.

### ISSUE THREAD

**Issue by j821304594** [angular/angular#50361]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

When Angular is upgraded from 14.x to 15.x, earlier versions of Chromium 66 kernel browsers are not compatible. Even if the target attribute in tsconfig.json is changed to es2015, the compilation product still has the optional link of the new ES2020 feature. The optional link (?) .) The browser of an earlier version cannot identify it.

### Please provide the exception or error you saw

```true
The error is:
Uncaught SyntaxError: Unexpected token . main.f25942fbbb79f94f.js:1

The compilation product still has the ES2020 feature optional chain (?.)
E(),o.items=V?.split(",")||[];
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.8
Node: 16.19.0
Package Manager: npm 8.19.3
OS: win32 x64

Angular: 15.2.9
... animations, cdk, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.8
@angular-devkit/build-angular   15.2.8
@angular-devkit/core            15.2.8
@angular-devkit/schematics      15.2.8
@angular/cli                    15.2.8
@schematics/angular             15.2.8
rxjs                            6.6.7
typescript                      4.9.5
```

**Comment by alan-agius4** [comment]
You can try to add support for Chrome 66 by adding this in your browserslist configuration, but this version is not officially supported as officially only the last 2 major versions are supported. 

See: https://angular.io/guide/browser-support#browser-support
