### ISSUE TITLE
Does angular 16 support cordova 11 and android 11?

### ISSUE THREAD

**Issue by winwinkhaing-klw** [angular/angular#50365]
### Does angular 16 support cordova 11 and android 11?

upgrade

### Is this a regression?

Yes

### Description

After upgrading angular 14 to 16, cordova build application doesn't work on android 11. It is working on above 11.
System got syntax error on the below code:

const onLoadStart = () => {

            macroTaskCanceller ??= createBackgroundMacroTask();

          };
We got the error message like the following 

Uncaught SyntaxError SyntaxError: Unexpected token '='
    at (program) (file:///android_asset/www/main.js:81846:34)

### Please provide the exception or error you saw

```true
Uncaught SyntaxError SyntaxError: Unexpected token '='
    at (program) (file:///android_asset/www/main.js:81846:34)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular : 16.0.1
Node : 18
Cordova : 11
Android 11
SDK API : 30
```

**Comment by alan-agius4** [comment]
Hi @winwinkhaing-klw, 

You can try to add support for Android 11 by adding this in your browserslist configuration, but this version is not officially supported as officially only the last 2 Android major versions are supported. 

See: https://angular.io/guide/browser-support#browser-support

**Comment by winwinkhaing-klw** [comment]
Hi @alan-agius4 , I have still issue. Please could you share any document to prove that version is not officially supported?

**Comment by alan-agius4** [comment]
Please see the link in the above comment.
