### ISSUE TITLE
Make a clear learning path

### ISSUE THREAD

**Issue by BerndHme** [angular/angular#50377]
### Describe the problem that you experienced

I'm learning Angular. Went trough the tutorials section.
While they are really hands on with very simple implementation of topics... I miss a clear fundamentals learning path for all of these topics.

### Enter the URL of the topic with the problem

https://angular.io/

### Describe what you were looking for in the documentation

A clear learning path for fundamentals... Deep enough to get creative. 

### Describe the actions that led you to experience the problem

When I start reading "understanding angular"... one time there are links to the "reference" section... other times there are links to other topics in "understanding angular".
This happens when I follow the prerequisites links... which from my understanding are topics you need to read first before moving on at the current page. 
This way the documentation feels like a spaghetti mess to me.

### Describe what you want to experience that would fix the problem

I think it's better to create a clear fundamentals learning path. Where the concepts are explained at a depth that is needed to create some nice apps... and most importantly so you can get creative.

I feel like the tour of heroes is to condensed... but has a good step by step approach... While all other documentation is connected together through links jumping from one part to a completely other part in the documentation... which interrupts your flow and make it feel bloated and chaotic.

**Comment by bencodezen** [comment]
@BerndHme Sorry for the delay in responding to your issue. 

Since you filed this issue, the team has been hard at work and recently released a new set of tutorials: [Angular Tutorials](https://angular.dev/tutorials)

Would love to get your feedback on those and we'll be happy to help iterate on the content to make people's learning journey with Angular as best as it can be.
