### ISSUE TITLE
angular prop doesn't update after getting facebook access token using FB.login() and exchanging it

### ISSUE THREAD

**Issue by Robogram** [angular/angular#50381]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

I don't know what's going on but when I got the access token with FB.login and then I used it to exchange it with a long lived access token and tried to update a prop within the component, the prop doesn't update on the html side

My props is facebookToken and it's initial value is blank. Tried setting the access token to it but it is not updating on the html side.

Any help would be very appreciated

### Please provide the exception or error you saw

```true
loginWithFacebook() {
  FB.login(function(res: any) {
    if (res.status == "connected") {
      let url = "https://graph.facebook.com/v16.0/oauth/access_token?"
      url += "grant_type=fb_exchange_token&"      
      url += "client_id=" + environment.facebookAppId + "&"
      url += "client_secret=" + environment.facebookClientSecret + "&"
      url += "fb_exchange_token=" + res.authResponse.accessToken

      http.get(url, { observe: 'response' })
        .subscribe(function (res: any) {    
          if (res.status == 200) {
            const userAccessToken = res.body.access_token

            this.facebookToken = res.body.access_token // facebookToken doesn't update on the html side
          }
        })
    }
}, { scope: "instagram_basic,instagram_content_publish,instagram_manage_comments,instagram_manage_insights,pages_show_list,pages_read_engagement" })
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.2
Node: 16.20.0
Package Manager: yarn 1.22.19
OS: darwin x64

Angular: 16.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.2
@angular-devkit/build-angular   16.0.2
@angular-devkit/core            16.0.2
@angular-devkit/schematics      16.0.2
@schematics/angular             16.0.2
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by alxhub** [comment]
I'm going to close this issue as it's requesting debugging assistance with your application, which is not a good fit for our issue tracker. I highly recommend the [Angular Community Discord](https://discord.gg/angular) as a place to get help with this kind of issue.

That said, try injecting `NgZone` and wrapping the body of the callback for `FB.login` in `ngZone.run(() => {...})`. I suspect that `FB.login` might be escaping the Angular zone before it calls its callback.

**Comment by Robogram** [comment]
Thank you man:)

**Comment by Robogram** [comment]
> I'm going to close this issue as it's requesting debugging assistance with your application, which is not a good fit for our issue tracker. I highly recommend the [Angular Community Discord](https://discord.gg/angular) as a place to get help with this kind of debugging/troubleshooting.
> 
> That said, try injecting `NgZone` and wrapping the body of the callback for `FB.login` in `ngZone.run(() => {...})`. I suspect that `FB.login` might be escaping the Angular zone before it calls its callback.

Btw, I tried that but ngZone.run(() => {...}) suppose to run after FB.login. Thanks for telling me about NgZone. Very appreciated:)
