### ISSUE TITLE
If form is removed from DOM during submit callback the page is reloaded

### ISSUE THREAD

**Issue by waterplea** [angular/angular#50407]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

There was [this bug a while back](https://github.com/angular/angular/issues/6819), which was closed because author stumbled upon it by accident, trying to actually do a different thing. But the bug is there nonetheless.

If form is submitted and you listen to the submit event, say, as a `(click)` on submit button — it is fired before `ngSubmit`. In that case, if you do something that would cause form to be gone from DOM (like `*ngIf="!submitted"`), it would stop listening to `submit` event and will not call `.preventDefault()`. This would cause the page to reload as a default form submit action.

This can be remedied by listening to `submit` event in capture phase inside `ngSubmit`, this way it would be triggered before any other listener and prevent the default behavior.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-wzkwqq

### Anything else?

It's pretty hard to fix it because Angular does not provide an idiomatic way to listen to events in capture phase. I have circumvented that in my project because I use my library for custom event plugins that allows it:
https://github.com/Tinkoff/ng-event-plugins/blob/master/projects/ng-event-plugins/src/plugins/options.plugin.ts

I wonder if we can have a discussion about including it in vanilla Angular? These plugins are pretty straightforward, and I'm sure ability to write `(click.stop)` or `(submit.capture)` out of the box would be welcomed by the community. But these are just a thoughts outside this actual issue.

**Comment by JeanMeche** [comment]
Hi Alex, are you sure your stackblitz example illustrates your issue ? 
I'm getting a `Form submission canceled because the form is not connected` warning which is expected.

**Comment by waterplea** [comment]
Oh sorry, looks like it is not that straightforward 🤔 I'll try to make a proper reproduction, looks like it has something to do with dynamic components on my side.

**Comment by waterplea** [comment]
I was unable to reproduce it in isolated environment from the ground up so I will close this issue, sorry for bothering you early. But I will try to distill my case to see what's going on and if I succeed — I will reopen it with a proper reproduction.
