### ISSUE TITLE
Angular Universal application throwing "javascript heap out of memory" error after running for a few days

### ISSUE THREAD

**Issue by ppsdang** [angular/angular#50402]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I have an Angular application that has recently been converted to Angular Universal. The application is based on Angular 15. The command used to initiate the server is "npm serve:ssr". The application runs fine for a day or two, but after that, it throws the error "ineffective mark-compacts near heap limit allocation failed - javascript heap out of memory".

To address this issue, I tried increasing the memory by adding the flag "max-old-space-size" to 3072. I modified the "serve:ssr" script in the package.json file to "node --max-old-space-size=3072 {project-name}/server/main.js". However, the problem still persists, causing my server to go down.

Here's the code snippet for the modified "serve:ssr" script in the package.json file

```javascript
"scripts": {
  "serve:ssr": "node --max-old-space-size=3072 {project-name}/server/main.js"
},
``` 

### Please provide the exception or error you saw

```true
ineffective mark-compacts near heap limit allocation failed - javascript heap out of memory.
```

**Comment by JoostK** [comment]
There appears to be a memory leak, but this can originate anywhere in the application. This isn't actionable for us without a reproduction.

**Comment by ppsdang** [comment]
This seems to be an issue with our code, I have fixed it by avoiding the memory leaks, by using strategies described in this link
https://stackoverflow.com/a/70527954/3493655
