### ISSUE TITLE
Effect fires after ngOnChanges

### ISSUE THREAD

**Issue by Eugeno** [angular/angular#50410]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I tried to implement `signals` in my application where appropriate, replacing `combineLatest`, but it broke the logic. In the process of debugging, I discovered a difference - `rxjs` triggers **before** `ngOnChanges`, while effect triggers **after**.
I'm not sure if this is a bug or by design. If the latter, could you explain the motivation behind it, and is it possible to achieve the "as with rxjs" behavior?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-cxsdn7?file=src%2Ftest.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.2
```

**Comment by JeanMeche** [comment]
I think this is pretty much expected. 

Your `subscribe` is sync with the call of `next` while the `effect` is hooked on the `applicationRef.tick` so you'll have to wait for the next CD.

**Comment by Eugeno** [comment]
Yes, indeed, it will trigger **before** `ngOnChanges`, if you write `this.cdr.detectChanges()` after `set()` (although I'm not sure if this is a good idea in general).

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
