### ISSUE TITLE
ngUpgrade does not support using bindToController as object

### ISSUE THREAD

**Issue by gjungb** [angular/angular#5042]
Since 35498d7045ba9138016464a344e2c145ce5264c1 it is possible to use ```bindToController``` in a convenient object notation:

```
bindToController: {
  text: '@text',
  obj: '=obj',
  expr: '&expr'
},
scope: {}
```

This use case doesn't seem to be covered in ```UpgradeNg1ComponentAdapterBuilder```.

**Comment by PascalPrecht** [comment]
This is a dup of https://github.com/angular/angular/pull/4784

**Comment by btford** [comment]
Closing as a dupe

**Comment by gjungb** [comment]
appreciated
