### ISSUE TITLE
Stackblitz URL pattern in Start tutorial wrong

### ISSUE THREAD

**Issue by Sammeeey** [angular/angular#50438]
### Describe the problem that you experienced

The [*Managing Data* part of the *Start* tutorial](https://angular.io/start/start-data#set-up-the-cart-component) described the following:

> ... the URL has the pattern https://getting-started.stackblitz.io/cart, where getting-started.stackblitz.io may be different for your StackBlitz project.

This is not true.
The URL doesn't change.
In a *normal* local development (in a *normal* browser) this would probably be true.
But in stackblitz specifically the URL doesn't change.

## Suggested Docs Change (1)
Just remove the second part of the sentence.
Result:
> Verify the new CartComponent works as expected by clicking the Checkout button. You can see the "cart works!" default text.

## Suggested Docs Change (2)
> Verify the new CartComponent works as expected by clicking the Checkout button. You can see the "cart works!" default text. In a browser (other than the one from StackBlitz) the URL would have the pattern `https://domain.com/cart` 

If one of the suggestions get accepted, I'd be happy to change the docs accordingly.

### Enter the URL of the topic with the problem

https://github.com/angular/angular/blob/6ced5c87796201c199d8c87024943ef29a8f28bc/aio/content/start/start-data.md?plain=1#L132

**Comment by JeanMeche** [comment]
What the sentence means is that each project has a different url on stackblitz.

That being said, the demo behind the given link is old (v6) and plein broken. It should probably be replaced.

**Comment by JoostK** [comment]
This is the URL for me: `https://vygtybrun-q1hi--4200--fc9e1a28.local-credentialless.webcontainer.io`, which is different from `https://getting-started.stackblitz.io/cart` which is what that sentence is trying to communicate.

@JeanMeche note that it's not a link on angular.io, it's only verbatim text. Still, I can see how that sentence doesn't really add anything so I'd be okay with dropping it altogether.

**Comment by bencodezen** [comment]
With the tutorials being updated and migrated to Angular.dev, I'll be closing this issue since the AIO tutorials will be deprecated. 

Please visit [Angular tutorials](https://angular.dev/tutorials) to see what changes have been made and we look forward to any feedback you have on the new tutorials!
