### ISSUE TITLE
feature request: Named Signals

### ISSUE THREAD

**Issue by vitaly-t** [angular/angular#50437]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Signals can become much easier to log and debug, if they were to support optional `name` string on the prototype, similar to ES6 class constructor prototype. We then can easily track named signals, log them, and have a much better picture of what is going on, which includes the production mode.

### Proposed solution

* Extend [CreateSignalOptions](https://angular.io/api/core/CreateSignalOptions) with `name` option:

```ts
interface CreateSignalOptions<T> {
  name?: string;
  equal?: ValueEqualityFn<T>
}
```

* Probably: Extend [Signal](https://angular.io/api/core/Signal) with the same property:

```ts
type Signal<T> = (() => T) & {
    name?: string;
    [SIGNAL]: unknown;
};
```

The name is to be available on the prototype:

```ts
const s1 = signal(1);
const s2 = signal(2, {name: 'second'});

console.log(s1.name); //=> undefined
console.log(s2.name); //=> "second"
```

Internally, it should set the name like this:

```ts
this.name = typeof value === 'string' ? value : JSON.stringify(value);
```

so it is `undefined` only when the name is undefined, and a string for everything else, including `null`, which `JSON.stringify` will make sure of automatically. Even better, with this approach one can even set a name as a serialized object, if needed.

### Alternatives considered

None.

**Comment by dcanevarollo** [comment]
Hi! May I work on this? I'm willing to contribute, although I'm a newcomer rsrs 😄

**Comment by vitaly-t** [comment]
@dcanevarollo I don't think Angular team cares who is working on this, for as long as your PR adheres to their guidelines for coding style, documentation and test coverage 😉 

I have added some code examples above, to make it easier.

**Comment by dcanevarollo** [comment]
Great! Thank you @vitaly-t!

**Comment by vitaly-t** [comment]
As an addition...

Since this a fundamental extension, it would be nice to see signals serialize themselves properly, with the `name` included:

```
const s = signal(123, {name: 'my-signal'});

console.log(signal) //=> signal / "my-signal" (123)
```
i.e. we probably should have `toString()` added also.

**Comment by vitaly-t** [comment]
@dcanevarollo In relation to the commit you made earlier...

The feature request is titled Named Signals, to add a `name`, not an `id`. An `id` implies uniqueness, and `name` doesn't. You can have signals with the same name, if you want.

**Comment by dcanevarollo** [comment]
@vitaly-t, I was struggling to 'override' the `name` prototype of the signal because it is a function, and function already has this property. Anyway, I was kind of 'rushing' because it was my first contribution and wanted to see the whole flow. 😄 

But, have to say, I totally agree with you. In case I want to 'fix' this, should I close the PR and open another one or use the same, but forcing push a 'correct' commit?

**Comment by vitaly-t** [comment]
Yes, you are right, since every signal is a function, we cannot override `name`. That's awkward.

It looks like the only good way to solve this is via manual extension of the signal protocol. Below is an example of such extension for the `signal`:

```ts
interface CreateSignalOptionsExt<T> extends CreateSignalOptions<T> {
  name?: string;
}

interface WritableSignalExt<T> extends WritableSignal<T> {
  ext: CreateSignalOptionsExt<T>;
}

function signalExt<T>(initialValue: T, options?: CreateSignalOptionsExt<T>): WritableSignalExt<T> {
  const s = signal(initialValue, options) as WritableSignalExt<T>;
  s.ext = {
    name: options?.name
  };
  return s;
}
```

This way we can create `ext` property on the function, which we can extend any way we want, and not just `name`.

Usage example:

```ts
const s = signalExt(123, {name: 'hello'});
console.log(s(), s.ext.name); //=> 123 "hello"
```

**Comment by vitaly-t** [comment]
So I created [this tiny repo](https://github.com/vitaly-t/signal-ext) which is good for what I wanted.

**Comment by pkozlowski-opensource** [comment]
I believe that this is fixed in Angular v19: you can pass the `debug` option to a signal creation function.
