### ISSUE TITLE
First App tutorial not working

### ISSUE THREAD

**Issue by davidszkl** [angular/angular#50448]
### Describe the problem that you experienced

Following the steps of the tutorial on a local repository, I create the Home component, which is supposed to be imported in the app component, but there is an error:

'imports' is only valid on a component that is standalone.
Did you forget to add 'standalone: true' to this @Component?

Adding standalone to the app component produces another error: it can't be declared anymore by the app.module, because it's a standalone component. 

### Enter the URL of the topic with the problem

https://angular.io/tutorial/first-app/first-app-lesson-02

### Describe what you were looking for in the documentation

follow the tutorial

### Describe the actions that led you to experience the problem

following the tutorial

### Describe what you want to experience that would fix the problem

following the tutorial and not having errors

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/85517120/7e6ae6d3-4519-4947-87fa-7dcc3dafde11)

### If this problem caused an exception or error, please paste it here

```true
Build at: 2023-05-24T15:47:49.643Z - Hash: 4e45b9db04eb7413 - Time: 570ms

Error: src/app/app.component.ts:6:12 - error NG2010: 'imports' is only valid on a component that is standalone.

6   imports: [HomeComponent],
             ~~~~~~~~~~~~~~~

  src/app/app.component.ts:19:14
    19 export class AppComponent {
                    ~~~~~~~~~~~~
    Did you forget to add 'standalone: true' to this @Component?




✖ Failed to compile.
```

**Comment by garrettld** [comment]
There is no app module in this tutorial, and everything should be standalone from beginning to end. If you've got an app.module.ts file then you don't have the correct files. Are you starting with the files from https://angular.io/tutorial/first-app/first-app-lesson-01?

**Comment by alxhub** [comment]
As @garrettld says, there's no `app.module` file in the starter files for this tutorial - I'd suggest starting from the first lesson again and verifying that you're downloading the standalone starting application.
