### ISSUE TITLE
hammerjs config not working with Angular 15 Standalone components

### ISSUE THREAD

**Issue by wissemchiha** [angular/angular#50447]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

When i upgrade my app to Angular 15, hammerjs config not working with the config below

```
@Injectable()
export class MyHammerConfig extends HammerGestureConfig {
  overrides = <any>{
    swipe: { direction: Hammer.DIRECTION_ALL },
  };
}

if (environment.production) {
  enableProdMode();
}

const routes: Routes = [
  {
    path: "",
    component: GestureSliderComponent,
  },
];

bootstrapApplication(AppComponent, {
  providers: [
    provideRouter(routes),
    provideAnimations(),
    { provide: HAMMER_GESTURE_CONFIG, useClass: MyHammerConfig },
  ],
}).catch((err: any) =>
  console.error("Application Boostrapping Error... ", err)
);
```

GestureSliderComponent html

`<div class="slider-section" (swipe)="onSwipe($event)"></div>`

GestureSliderComponent ts

```
onSwipeRight(event, data) {
  console.log("event => ", event);
}
```

Also i tried to import HammerModule in GestureSliderComponent but didn't work too

### Please provide the exception or error you saw

```true
I don't see any exception but gesture don't work
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 15
```

**Comment by garrettld** [comment]
It looks like you're not importing the HammerModule providers, which wire up the hammerjs events to the angular event manager for you. You just need to add `importProvidersFrom(HammerModule)` to your `boostrapApplication` call, as shown in this example: https://stackblitz.com/edit/angular-1zucpn?file=src%2Fmain.ts
