### ISSUE TITLE
Expose `IMAGE_CONFIG` provider in Angular v14

### ISSUE THREAD

**Issue by exequiel09** [angular/angular#50455]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

Based on the [Angular docs](https://angular.io/guide/image-directive#responsive-images), one can customize the breakpoints using the `IMAGE_CONFIG` token. However, when latest changes on `NgOptimizedImage` landed on v14.3.0, it doesn't include the export for this token as shown in this code https://github.com/angular/angular/blob/14.3.0/packages/common/src/common.ts#L30

In v15+, it's already exported: https://github.com/angular/angular/blob/15.2.9/packages/common/src/common.ts#L30

### Please provide a link to a minimal reproduction of the bug

N/A

### Please provide the exception or error you saw

```true
N/A
```

**Comment by AndrewKushnir** [comment]
Closing this ticket, see https://github.com/angular/angular/pull/50461#issuecomment-1563668412 for more information. Please consider upgrading to the next version of Angular to get the most up-to-date version of the image directive where the token is also available.
