### ISSUE TITLE
The Hero Editor tutorial

### ISSUE THREAD

**Issue by Dekamerron** [angular/angular#5045]
Hello there,
I noticed few things that you can correct in your tutorial "The Hero Editor". One of them is the redundant &lt;/а&gt; tag in the end of the following html:
&lt;span class="badge"&gt;{{hero.id}}&lt;/span&gt; {{hero.name}}&lt;/a&gt;
It stands there in 4 blocks of code in the chapter 2 "Master/Detail".
The second thing is that at the end of the chapter 2, you show a screenshot with list of heroes, but the html is different from the html, you showed us in all 2 chapters get together. The differences are "Dashboard Heroes", "XXXX is my hero" and a "View details" button.

Cheers and keep up the good work.

**Comment by pkozlowski-opensource** [comment]
@Dekamerron the tutorial lives in https://github.com/johnpapa/angular2-tour-of-heroes/commits/master and I believe that the error you are reporting here was fixed via https://github.com/johnpapa/angular2-tour-of-heroes/commit/5f117006b2f4a9e1038944084bd48b53590d1dc9

If you believe that there are still items to be fixed please report them in https://github.com/angular/angular.io (this is where doc live)

Thnx!
