### ISSUE TITLE
provideServerRendering() and provideHttpClient() ordering issue 

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#50454]
### Which @angular/* package(s) are the source of the bug?

platform-server

### Is this a regression?

No

### Description

Currently, when you want to configure HttpClient differently on the server, adding the `provideHttpClient(...)` call in front of the `provideServerRendering()` has no effect. The problem is that the `provideServerRendering()` under the hood adds the `provideHttpClient()` call, which effectively overrides any custom configuration of HttpClient, see:

https://github.com/angular/angular/blob/06b498f67f2ad16bb465ef378bdb16da84e41a1c/packages/platform-server/src/provide_server.ts#L32

This was done for historical reasons to mimic the ServerModule class that imported the HttpClientModule.

The solution is to move the `provideHttpClient(...)` *after* the `provideServerRendering()` call.

Since there is no indication that the configuration was overridden, this leads to hard to debug situations.

I think there are 2 possible options:

- Ideally, we should probably drop the `provideHttpClient()` from the `provideServerRendering()` implementation, especially since we merge the client and server configs on the server (in the `app.config.server.ts`). We can only do that in v17 though, since it would be breaking.
- As a possible solution, we can add some dev-mode only code that would use a trick like the one used with `ROUTER_IS_PROVIDED` and output a warning to mention that custom HttpClient configuration was overridden. We can try to do it in the interim before v17.

// cc @alan-agius4

**Comment by AndrewKushnir** [comment]
// also cc @eneajaho

**Comment by Zefried** [comment]
Can I contribute

**Comment by AndrewKushnir** [comment]
@Zefried thanks for offering the help 👍 It was a quick 1 line change, so I've just created a quick PR, but there are more opportunities to contribute! Please take a look at the issues with the "help wanted" label. Thank you.

**Comment by Zefried** [comment]
okay, great
