### ISSUE TITLE
No change detection inside socket.io events

### ISSUE THREAD

**Issue by ocombe** [angular/angular#5046]
Hello,

when I'm using [socket.io](https://github.com/socketio/socket.io-client) and listen to an event, changing a component property inside the event listener doesn't trigger a change detection and doesn't update the view accordingly...
I guess that it uses a special kind of events that isn't catched by zone :-/

```js
import {Component, Injectable} from 'angular2/angular2';

@Injectable()
@Component({
    selector: 'test',
    template: `
        <div>
            {{scanDone}}
        </div>
	`
})
export class TestComponent {
    static socket = io();
    scanDone: Boolean = false;

    constructor() {
        this.socket.on('scan:status', (status: string) => {
            // gets called
            console.log('status', status);
            // changes the property but doesn't update the view
            this.scanDone = true;
        });
    }
}
```

I wanted to do a plnkr but it requires a socket.io server to work :(

Is there a way to manually trigger the update ? I added a setInterval into the constructor to see, and it triggered the view update but that's not really a good practice :)

**Comment by ericmartinezr** [comment]
Hey @ocombe I do use socket.io too. I don't use its events directly to manipulate the incoming data, I just pass them through a Subject

```
on(evt: string): Subject {
	let subj = new Subject;
	this._io.on(evt, (data) => {
		subj.next(data);
	});
	return subj;
}
```
Then I just subscribe to it

```
// My Component
on('event from socket').subscribe((data) => doSomething());
```
I know you are asking to ng2 to be able to register all kind of events, and I couldn't say nothing about that. But this will surely help you.

**Comment by ocombe** [comment]
Ahh using observables is a great idea, I'll try that thanks :)

**Comment by ocombe** [comment]
Ok found a simpler way: wrap the callback in `zone.bind`:
```js
        this.socket.on('scan:status', zone.bind((status: string) => {
            // changes the property and updates the view
            this.scanDone = true;
        }));
```

And a more complex possibility is to use NgZone: https://angular.io/docs/ts/latest/api/core/NgZone-class.html.

I don't close the issue in case "the socket.io events" is something that you'd want to fix. If not then you can close the issue.

**Comment by cwmrowe** [comment]
@ericmartinezr, I have a similar issue where I am forwarding an OpenLayers map event through an event emitter. The component watching for the event gets its properties updated but its view does not. My code for forwarding the event is like.
```
@Output() pointermove: EventEmitter<any> = new EventEmitter();

...

this.map.on('pointermove', (event) => {
  pointermove.next(event);
}
```

**Comment by gnujeremie** [comment]
I know this issue is closed, but I'm having the problem only with IE11 (angular 2.1.2 / socket.io)

Using zone.run() fixes it though.

**Comment by ljacques** [comment]
can you give me your example with the zone.run()
thanks

**Comment by gnujeremie** [comment]
@ljacques here you go : 
```javascript
constructor(private zone: NgZone)  {}

public connect(options: any) {
    // custom code
   [...]

    // socket event
    this.mainSocket.on('connect_error', (error: any) => {
        this.zone.run(() => {
            this.onConnectError(error);
        });     
    });
}
```

**Comment by ljacques** [comment]
thanks a lot :-)
