### ISSUE TITLE
Structural Directives should be compile errors if the * is missing

### ISSUE THREAD

**Issue by bryanrideshark** [angular/angular#50469]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

Recently, had a 30 minute delay in productivity because of a missing `*` in `*ngIf`.

There was an error message thrown "No Provider for TemplateRef" - Which is fantastic, I get a line number pointing me to the template; but this should be a compile-time error.

Example:
````html
<div *ngIf="thisWorks">
    I work! But the entire TemplateRef will fail due to a syntax error that isn't being reported.
    <div ngIf="thisBreaks">All it takes is one errant keystroke and this will break at runtime.</div>
</div>
````

This is a hairy problem, because for a while, I centered my attention around "thisWorks". I was trying to figure out, is it that I have a ChangeDetectorRef I need to `markForCheck`, is it an issue with the logic powering thisWorks.... It was only after realizing that the TemplateRef error was connected to "thisBreaks", that I recognized my mistake. It didn't tell me that I was missing a *, just that a TemplateRef could not be found.

Having a more clear error message - or ideally, a red squiggly for ngIf's missing *, would be helpful.

### Proposed solution

Make it possible for directives which inject a TemplateRef to optionally require use of the `*` syntax. This should be a compiler error.

I recognize that there may be legitimate circumstances where a TemplateRef is injected on a directive, but you do not expect or require the `*` syntax. However, for things like *ngIf this should be a compiler error.

### Alternatives considered

I could just always type with perfect accuracy. But I've tried that, and it doesn't always work.

**Comment by dylhunn** [comment]
Without the `*`, it could just be an arbitrary attribute, but we can and should catch the special case of `ngIf` with a template diagnostic.

**Comment by jessicajaniuk** [comment]
Closing since we have the new control flow syntax and there are valid cases where using the structural directives without the asterisk.
