### ISSUE TITLE
Reactive form errors are cleared before the async validators are run

### ISSUE THREAD

**Issue by petermenkeepsilon** [angular/angular#50470]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

When a reactive form control is created with an async validator, but no normal validator, it's impossible to access the control's errors from the async validator because the errors are cleared before it is run.

See the code where this happens:
https://github.com/angular/angular/blob/bd4dbdd2bd48760c24fafc6f77aa893e288fde08/packages/forms/src/model/abstract_model.ts#L1057

If the logic of the async validator is dependent on the control's existing errors, the async validator will mistakenly think the control has no errors, since they have already been set to `null`. A workaround is to include a validator that will forward any existing errors (`(control) => control.errors`) to the async validators, but that is nonintuitive.

### Please provide a link to a minimal reproduction of the bug

https://github.com/petermenkeepsilon/angular-form-async-validation-errors-bug

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.2
Node: 16.14.2
Package Manager: npm 8.5.0
OS: darwin x64

Angular: 16.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.2
@angular-devkit/build-angular   16.0.2
@angular-devkit/core            16.0.2
@angular-devkit/schematics      16.0.2
@angular/cli                    16.0.2
@schematics/angular             16.0.2
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by JeanMeche** [comment]
Hi, 

Errors are a state returned by the validators themselves, why would you depend on them ?

**Comment by petermenkeepsilon** [comment]
> Hi,
> 
> Errors are a state returned by the validators themselves, why would you depend on them ?

In my case, to create a validator that only has an effect if a condition is. I need more customizability for when a form is validated beyond the supported "change", "blur", or "submit". The intended behavior would be that if the condition is met, a validator is run, otherwise the validations should not run and the form should keep its existing errors.

See here for an example: https://github.com/petermenkeepsilon/angular-form-async-validation-errors-bug/blob/main/app/src/app/app.component.ts#L5-L16

**Comment by JeanMeche** [comment]
We need to reset the error synchronously. Until the Async validators have returned, there are no known errors and the pending status is here to indicate async validator waiting to return. 

I'll close this as work as expected and as this is an uncommong usecase with a workaround.
