### ISSUE TITLE
Regular Expression Denial of Service (ReDoS)

### ISSUE THREAD

**Issue by norey** [angular/angular#50471]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

https://security.snyk.io/vuln/SNYK-JS-ANGULAR-3373044
https://security.snyk.io/vuln/SNYK-JS-ANGULAR-3373045
https://security.snyk.io/vuln/SNYK-JS-ANGULAR-3373046

### Anything else?

It is not clear if these bugs only affect the older AngularJS or the current one.

**Comment by JeanMeche** [comment]
Hi,

These issues concern AngularJS not Angular (2+).

AngularJS support has ended in [january 2022](https://docs.angularjs.org/misc/version-support-status). Don't expect any updates.

**Comment by alxhub** [comment]
Closing as not relevant to Angular (2.0+)
