### ISSUE TITLE
Example to use router-outlet with Angular 1

### ISSUE THREAD

**Issue by varghesep** [angular/angular#5048]
I'm looking for an example to use **router-outlet** with Angular 1. I have noticed that there have been changes in the area of **router** APIs, so I could not find any documentation or blog that helps me. 

Here there is an [article](http://www.jvandemo.com/a-10-minute-primer-to-the-new-angular-router/) talking about **ng-viewport**. I don't think this is valid anymore.

**Comment by robwormald** [comment]
See the example in the playground: https://github.com/angular/angular/tree/master/modules/playground/src/routing

Please keep Github issues for bugs and actual issues, rather than support requests. Try the [gitter](https://gitter.im/angular/angular) channel for these kinds of things. Thanks!

**Comment by robwormald** [comment]
Derp, Angular 1 question. Disregard the previous link. Point still stands though, try to keep the Github issues for verified issues and try gitter for support requests.

You can read the thru the integration spec here : https://github.com/angular/angular/blob/master/modules/angular1_router/test/integration/navigation_spec.js

**Comment by robwormald** [comment]
http://plnkr.co/edit/jLp9Z7DGMl1Dl09dQwF8?p=preview
