### ISSUE TITLE
Provide a more convenient way to use strict equality with signals

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular#50491]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

In order to enable strict equality in signals holding or computing immutable data, one has to create an ad-hoc strict equality function `signal(..., {equal: (a, b} => a === b})` or import the function from a shared module `signal(..., {equal: strictEqual})`.

It would be nice to provide a more convenient way to use strict equality when needed.

### Proposed solution

A `'strict'` string value as a possible option:

```ts
function signal<T>(value: T, opts: {equal: ValueEqualityFn<T> | 'strict'});

signal(..., {equal: 'strict'});
```

### Alternatives considered

A `strictEqual` option that might be confusing IMO:

```ts
function signal<T>(value: T, opts: {equal: ValueEqualityFn<T>} | {strictEqual: true});

signal(..., {strictEqual: true});
```

**Comment by mikezks** [comment]
I fully agree. Having typical, expectable immutable data handling as opt-in does not feel right.

As we have three different update methods (`set()`, `update()`, `mutate()`), I would like to see at least one (`update()`) to use a correct object reference equal comparison.

**Comment by simeyla** [comment]
It's also very easy to wrongly assume that you get strict equals by default (like with `distinctUntilChanged()`), whereas you only get it for primitive types. This is for a good reason, but should be made clearer [in the guide.](https://angular.io/guide/signals#signal-equality-functions)

**Comment by pkozlowski-opensource** [comment]
With the https://github.com/angular/angular/commit/00128e38538f12fe9bc72ede9b55149e0be5ead0 merged the `Object.is` (a "better version of" `===`) is the default.

**Comment by yjaaidi** [comment]
Thanks @pkozlowski-opensource! This rocks! 🚀
