### ISSUE TITLE
angular vscode remote development, running port cant display on browser 

### ISSUE THREAD

**Issue by qhoirulanwar** [angular/angular#50501]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler, platform-browser

### Is this a regression?

Yes

### Description

i use the vscode remote development for developing my project angular & ionic on my virtual machine
after port is forwarded to local address, but i cant view content on browser after command ng serve

i use the windows 10 for run vscode

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.3
Node: 18.16.0
Package Manager: npm 9.5.1
OS: linux x64

Angular: 16.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.3
@angular-devkit/build-angular   16.0.3
@angular-devkit/core            16.0.3
@angular-devkit/schematics      16.0.3
@schematics/angular             16.0.3
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by JoostK** [comment]
/
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
