### ISSUE TITLE
tell angular to update a component view after updating an array

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#5050]
I am using Firebase as a realtime backend for a sample app and I seem to keep hitting some walls when it comes to view updates after I change the shape of an array.

For example this [plunk](http://plnkr.co/edit/EdjrRQI9EefiVRRIdPrQ?p=preview) illustrates what I am talking about. I am using `setTimeout` to mimic latency and a few delays that I have in my app (a few dependencies are async and I have to wait for them before I create the array), but basically what happens is that the view does not pickup on the changes I made to the array if it already rendered it and I made some changes at a later point.

Maybe I can make the `Chores` class depend on `NgZone` or something that I could use to let Angular know that there has been some updates and that it should run the checks through the views?

**Comment by r-park** [comment]
I think the promise is being resolved with an empty `chores` array, because at this point (inside the factory function) the array hasn't had a chance to load data from Firebase:
```
provide(Chores, {
  useFactory: (promise: Promise<any>) => promise.then((ref: any) => new Chores(ref)),
  deps: [FIREBASE_TODOS_REF]
})
```
Try waiting for the `value` callback to trigger first:
```
ref.once('value', (snapshot) => {
  this[0] = snapshot.val();
  // resolve promise here
})
```
Check out this [modified plunk](http://plnkr.co/edit/Lt2ir6h9Q2iz8gdodNAZ?p=preview)

**Comment by rolandjitsu** [comment]
@r-park the problem is that over time the array may change from the Firebase side and the `Chores` class handles that internally (I haven't show that in the plunk, but it's the same concept of using `ref.once()`) to reflect/sync the changes.

So using a promise is not a solution.

**Comment by DennisRoam** [comment]
I had a hard time going through the way you were using everything so I created this simplified version that connects to firebase with an `on()` call and is correctly updating as expected. [Plunker](http://plnkr.co/edit/D547Esw5vbw2KamhD18m?p=preview)

I'm not sure why are you using a service to inject a ref into an array extension and then calling it, seems like a lot of work but I guess your app needs something similar.. 

Also you should check out the firebase pipe used [here](https://github.com/sararob/angular2base/blob/master/src/firebasepipe.ts)

it may help a bit

**Comment by DennisRoam** [comment]
[Here is an example](http://plnkr.co/edit/IpIYIhgvDGpyHP4Nw09X?p=preview) using the same data but with the firebase info moved into a service and using observers to trigger view updating. NOTE: I added a delay to simulate a long call

**Comment by rolandjitsu** [comment]
@DennisRoam I need to use a service because the url for the Firebase reference is composed base on the data returned from some other service.

I have also create a class that extends the array and syncs any changes (no matter from which side) with Firebase/locally (you can check it out [here](https://github.com/rolandjitsu/ng2-lab/blob/master/src/common/firebase_array.ts)). So I use that array to simply iterate over it's values in the view, but because I need to wait in order to create the Firebase ref, I just made a service for the array.

Anyway, both the plunks you created are not exactly what I am looking for. Perhaps using a pipe would work, I actually considered having the service as an observable that I can use with the `| async` pipe, but the latest release does not seem to support Rx Observables at this point.

**Comment by rosendi** [comment]
@rolandjitsu I'm not sure that it's connected to your question, but I've just extracted firebase logic from one of my project to the separate package. Have a look (https://github.com/rosendi/farel), maybe you'll find something helpful. Especially here - https://github.com/rosendi/farel/blob/master/farel/terminals/on_value_pipe.ts.

**Comment by rolandjitsu** [comment]
@rosendi you should probably take a look at Rx and perhaps use Observable for implementing async pipes.

I was actually thinking of using pipes for something like I described and I actually have a plunk that has a fairly reasonable implementation of a RxPipe that could be adapted to use Firebase queries. But I've been told that there will be a RxPipe implemented in angular2 so I am waiting for that.

**Comment by ericmartinezr** [comment]
@rolandjitsu the *RxPipe* is actually the AsyncPipe. It supports Observables since a46 ._.

**Comment by rolandjitsu** [comment]
@ericmartinezr oh, I haven't noticed that ... I didn't see it in the changelog.

**Comment by pkozlowski-opensource** [comment]
I guess this one was a support question and got resolved. If not please open a new issue following the issue template.
