### ISSUE TITLE
Error: Module '"@angular/core"' has no exported member 'CSP_NONCE'.

### ISSUE THREAD

**Issue by kumaran-is** [angular/angular#50504]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Below code throws Error: Module '"@angular/core"' has no exported member 'CSP_NONCE'.

Reference Anguar official documentation: https://angular.io/guide/security#content-security-policy

import {bootstrapApplication, CSP_NONCE} from '@angular/core';
import {AppComponent} from './app/app.component';

bootstrapApplication(AppComponent, {
  providers: [{
    provide: CSP_NONCE,
    useValue: globalThis.myRandomNonceValue
  }]
});

### Please provide a link to a minimal reproduction of the bug

https://angular.io/guide/security#content-security-policy

### Please provide the exception or error you saw

```true
Error: src/app/core/core.module.ts:1:38 - error TS2305: Module '"@angular/core"' has no exported member 'CSP_NONCE'.
[app] 
[app] 1 import { APP_INITIALIZER, NgModule,  CSP_NONCE } from '@angular/core';
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.1.6
Node: 16.17.0
Package Manager: npm 8.15.0
OS: darwin x64

Angular: 15.1.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.6
@angular-devkit/build-angular   15.1.6
@angular-devkit/core            15.1.6
@angular-devkit/schematics      15.1.6
@angular/cli                    15.1.6
@schematics/angular             15.1.6
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by JoostK** [comment]
You are looking at the docs for Angular 16, where this feature has been introduced. Angular 15 does not provide this functionality.
