### ISSUE TITLE
Error rendering a lazy loaded route that dynamically loads a component on ViewContainerRef

### ISSUE THREAD

**Issue by CarlosTorrecillas** [angular/angular#50513]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] builders
- [X] common
- [ ] express-engine

### Is this a regression?

I think it is, the previous working version I have is Angular 15.2.7

### Description

When rendering a page on a lazy loaded module that dynamically renders a component from another module there is an error and the page does not render. The behavior seems similar to what happened here: https://github.com/angular/angular/issues/37888

## 🔬 Minimal Reproduction

1.- Clone the repo: https://github.com/CarlosTorrecillas/universal-issue
2.- Do `npm i`
3.- Do `npm run dev:ssr`
4.- Navigate to `http://localhost:4200/lazy-loaded` as in the first URL you paste in the browser or hard refresh on that route

## 🔥 Exception or Error

<pre><code>

Compiled successfully.
** Angular Universal Live Development Server is listening on http://localhost:4200, open your browser on http://localhost:4200 **
Running on the server with appId=ng
Angular is running in development mode.
Running on the server with appId=ng
Angular is running in development mode.
./node_modules/@angular/core/fesm2022/core.mjs:9231
            throw new RuntimeError(205 /* RuntimeErrorCode.INJECTOR_ALREADY_DESTROYED */, ngDevMode && 'Injector has already been destroyed.');
                  ^

RuntimeError: NG0205: Injector has already been destroyed.
    at assertNotDestroyed (./node_modules/@angular/core/fesm2022/core.mjs:9231:19)
    at get (./node_modules/@angular/core/fesm2022/core.mjs:9135:14)
    at get (./node_modules/@angular/core/fesm2022/core.mjs:9175:33)
    at get (./node_modules/@angular/core/fesm2022/core.mjs:12979:36)
    at lookupTokenUsingModuleInjector (./node_modules/@angular/core/fesm2022/core.mjs:4417:39)
    at getOrCreateInjectable (./node_modules/@angular/core/fesm2022/core.mjs:4465:12)
    at get (./node_modules/@angular/core/fesm2022/core.mjs:4730:16)
    at get (./node_modules/@angular/core/fesm2022/core.mjs:9175:33)
    at injectInjectorOnly (./node_modules/@angular/core/fesm2022/core.mjs:651:33)
    at Module.ɵɵinject (./node_modules/@angular/core/fesm2022/core.mjs:655:60) {
  code: 205
}

Node.js v18.10.0
A server error has occurred.
node exited with 1 code.

</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 16.0.3
Node: 18.10.0
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 16.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.3
@angular-devkit/build-angular   16.0.3
@angular-devkit/core            16.0.3
@angular-devkit/schematics      16.0.3
@nguniversal/builders           16.0.2
@nguniversal/express-engine     16.0.2
@schematics/angular             16.0.3
rxjs                            7.8.1
typescript                      4.9.5

</code></pre>

**Comment by alan-agius4** [comment]
The root cause appears to be that the `OnInit` life-cycle-hook is being used as an async hook. This hook is actually sync. 

Some what related to https://github.com/angular/angular/issues/50457

**Comment by CarlosTorrecillas** [comment]
Hello @alan-agius4 , did you guys managed to give a priority to this? No pressure - Essentially I want to know whether this is something that can be fixed soon or is it not going to be included in the next patch? Thanks!

**Comment by alan-agius4** [comment]
We are still discussing possible solutions. But it is definitely a priority to address this.

**Comment by CarlosTorrecillas** [comment]
Hello guys, do we know when the new version containing this fix is going out?
