### ISSUE TITLE
ZAP Scan issue against PreconnectLinkChecker

### ISSUE THREAD

**Issue by f2404** [angular/angular#50519]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

ZAP Scan reports a security issue against our Angular app:
```
Medium
Sub Resource Integrity Attribute Missing
Description	
The integrity attribute is missing on a script or link tag served by an external server. The integrity tag prevents an attacker who have gained access to this server from injecting a malicious content.
URL	[redacted]
Method	GET
Parameter	
Attack	
Evidence	<link rel="preconnect" href="${ht.origin}">
Instances	1
Solution	
Provide a valid integrity attribute to the tag.
Reference	https://developer.mozilla.org/en/docs/Web/Security/Subresource_Integrity
CWE Id	[345](https://cwe.mitre.org/data/definitions/345.html)
WASC Id	15
Plugin Id	[90003](https://www.zaproxy.org/docs/alerts/90003/)
```

This seems to be caused by the following piece of code inside PreconnectLinkChecker:
https://github.com/angular/angular/blob/6f5dabe0d25a5660b7c3001041449b4622dd8924/packages/common/src/directives/ng_optimized_image/preconnect_link_checker.ts#L121

1. Would you say this is an issue or a false positive?
2. The comment says PreconnectLinkChecker shouldn't appear in prod build, but I'm still seeing it - is that an issue?

Thanks!

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.11
Node: 18.16.0 (Unsupported)
Package Manager: npm 9.5.1
OS: darwin arm64

Angular: 13.4.0
... animations, common, compiler, compiler-cli, core, elements
... forms, localize, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.11
@angular-devkit/build-angular   13.3.11
@angular-devkit/core            13.3.11
@angular-devkit/schematics      13.3.11
@angular/cdk                    13.3.9
@angular/cli                    13.3.11
@angular/material               13.3.9
@schematics/angular             13.3.11
rxjs                            6.6.7
typescript                      4.6.4
```

**Comment by garrettld** [comment]
The code you reference is an error message and does not actually create a `<link>` element, so if your scanner is picking that up as a security issue then I'd say that is a false positive.

It's true that the PreconnectLinkChecker should be elided in production mode. It's injected here, wrapped in an `if (ngDevMode)` check:

https://github.com/angular/angular/blob/5576b9a5ea442cc98804bbeaeed0e0f11792c6f7/packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts#L396

**Comment by JeanMeche** [comment]
Yup, that's a false positive. Your tool is complaining about a string. It's a false positive.  

I've tested on v16, it doesn't make it to the prod build. You should update your version, v13 is not supported anymore.
