### ISSUE TITLE
When binding eventListener on non-existing @Output, Compiler does not throw error.

### ISSUE THREAD

**Issue by Gnyblast** [angular/angular#50517]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

First of all, I apologize if this is an existing request (which is highly possible) but I could manage to find any ticket that refers to this issue.

I had a child component that was having 2 @Output `EventEmitters`.
```
@Output pageSize: EventEmitter<number> = new EventEmitter<number>()
@Output pageNumber: EventEmitter<number> = new EventEmitter<number>()
```

I had to do a decision and merge these `EventEmitters` into a single one with a better name that reveals what it is in it's name.
```
@Output pageNumberAndSize: EventEmitter<PaginationItem> = new EventEmitter<PaginationItem>()
```

When I was doing this, I was trusting my compiler that it would be throwing compilation errors and tell me where these old 2 event emitters were having bindings so I could go ahead and change them in a large codebase.

But instead it looks like compiler has no event listener checks and we have to discover all the referances by ourselves. I guess on a compiled language you expect to see these kind of checks to be done, in order to prevent loss of functinalities. Because if I miss this on anypoint in the code, then there is no error but triggers won't work which means loss of functionality.

### Proposed solution

Probably implementing some check same as done in @Input bindings?

### Alternatives considered

There seem to be no alternative since this is not a real real error but an improvement that makes our life easier.

**Comment by keeperkan** [comment]
In Angular, the template binding syntax does not provide compile-time checks for event listeners or output bindings. This means that if you change the name of an @Output property in a component, you will need to manually update all the references to that property in your template files.

To ensure that you don't miss any references, you can use your IDE's search functionality to find all occurrences of the old @Output properties (pageSize and pageNumber) in your codebase. This way, you can update the bindings to use the new pageNumberAndSize EventEmitter correctly.
