### ISSUE TITLE
Upgrade command to Angular v16 missing

### ISSUE THREAD

**Issue by vugar005** [angular/angular#50520]
### Describe the problem that you experienced

update.angular.io guide has guide to run script for upgrading angular apps. For instance from v14 to v15.
`ng update @angular/core@15 @angular/cli@15 `

But the guide option from **v15** to **v16,** the below command is missing
`ng update @angular/core@16 @angular/cli@16 `

Same for angular material. Below command is missing:
`ng update @angular/material@16 `

### Enter the URL of the topic with the problem

https://update.angular.io/?l=2&v=15.0-16.0

### Describe what you were looking for in the documentation

Described above.

**Comment by JeanMeche** [comment]
Hi, this issue is tracked at angular/angular-update-guide#219.
