### ISSUE TITLE
'Go to definition' does not work in template files, if component properties are private or protected

### ISSUE THREAD

**Issue by DerZyklop** [angular/angular#50527]
### Which @angular/* package(s) are the source of the bug?

language-service

### Is this a regression?

No

### Description

Lets assume i have a Component like:
```typescript
@Component({
	selector: 'foo',
	templateUrl: './foo.component.html',
})
class FooComponent {
	@Input() public description : string | null = null;

	@Input('icon') private iconInput : string | null = null;

	public get icon() : PlanoFaIconPoolValues | null {
		if (this.iconInput) return this.iconInput;
		…calculate some default icon
	}
}
```

I don't want to make iconInput accessible to `foo.component.html`. The template should only be used by the getter. 

If i use this component like:
```html
<foo
	[icon]="…"
	[description]="…"
/>
```

I can jump to the definition of description but not to the `[definition]` of the `[icon]`. 

In my opinion, the accessibility modifier should not even be taken into account here. It should only be the angular decorator, that decides if I can jump to the definition.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-ktpco8?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.7
Node: 18.16.0
Package Manager: npm 9.5.1
OS: darwin arm64

Angular: 15.2.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.7
@angular-devkit/build-angular   15.2.7
@angular-devkit/core            15.2.7
@angular-devkit/schematics      15.2.7
@angular/cli                    15.2.7
@schematics/angular             15.2.7
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by dylhunn** [comment]
My guess is that this is a shortcoming of how accessibility modifiers affect the typecheck block. But possible it's something simpler and language-service specific.

**Comment by DerZyklop** [comment]
Maybe some conditions have changed in my project, but it seems like this issue has been solved. Can someone confirm with at least Angular 15 and VSCode 1.85.0?
