### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by Mallikharjunataapthi** [angular/angular#50535]
### Is this a bug report or a feature request?

- [ ] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

![image](https://github.com/angular/angular/assets/97084924/bbf11371-b62d-4ccf-807d-f7e2bbbea07e)

**Comment by JoostK** [comment]
This appears to be a very old version of Angular, as well as showing a bundle name as derived from project files, so I am going to close this issue as unactionable.
