### ISSUE TITLE
Overlap of menu items on angular.io

### ISSUE THREAD

**Issue by huynhdev24** [angular/angular#50537]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

![image](https://github.com/angular/angular/assets/124909303/61a62611-1df9-4a7a-92d5-840dc334d268)

**Comment by JeanMeche** [comment]
Hi, I could not reproduce your errors on Chrome M114 and Firefox 113. Which browser did you use ?

**Comment by huynhdev24** [comment]
I use Chrome 113
![image](https://github.com/angular/angular/assets/124909303/2bfc752e-130b-4ded-abec-b1cfe172b593)

**Comment by JeanMeche** [comment]
Do you reproduce it everytime ? Do you have any extensions enabled that may cause this ?

**Comment by jessicajaniuk** [comment]
@huynhdev24 Can you share a bit more information about which browser, version, operating system? We've not been able to reproduce it. Does the issue persist after a full clear cache refresh?

**Comment by huynhdev24** [comment]
> @huynhdev24 Can you share a bit more information about which browser, version, operating system? We've not been able to reproduce it. Does the issue persist after a full clear cache refresh?
Google Chrome: 114.0.5735.134
![image](https://github.com/angular/angular/assets/124909303/5cbbbc45-e9f4-49af-b953-fd32e3c9f995)

OS: Windows 10 Home
![image](https://github.com/angular/angular/assets/124909303/2e2e7812-aa11-4359-adc1-a6c04864a5e7)

**Comment by huynhdev24** [comment]
22/06/2023 I rechecked this and no more errors.
![image](https://github.com/angular/angular/assets/124909303/887831f1-8bf0-4d4f-a79b-8ecaa92b72b9)

**Comment by huynhdev24** [comment]
Thanks for the help!
