### ISSUE TITLE
Cancelling file input dialog emits cancel event

### ISSUE THREAD

**Issue by stevendarby** [angular/angular#50556]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

Pressing cancel on the file picker seems to emit a cancel event even though this isn't hooked up in any way. Is this a bug? If there a workaround?

Link to minimal repro shows the console printing "Cancel" when clicking cancel on dialog that's opened by clicking the text.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-sp4fzz?file=src%2Fapp%2Fapp.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Seen in angular 13
```

**Comment by JoostK** [comment]
Binding a listener using `(cancel)` syntax in a template does create a native DOM listener, and the browser emits a `cancel`  event for this particular action which bubbles up to the component host that has a listener for it.

Related: #4059.
