### ISSUE TITLE
Fails to bindInput in time for SSR to use the input for api's

### ISSUE THREAD

**Issue by sp90** [angular/angular#50550]
### Which @angular/* package(s) are the source of the bug?

platform-browser, platform-server, Don't known / other

### Is this a regression?

Yes

### Description

So just using the barebones implementation of angular with SSR and using `withComponentInputBinding` with a routing config like:

```ts
{
    path: ':id',
    loadComponent: () => import('./home/home.component'),
}
```

And inside the component to look like this

```ts
@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export default class HomeComponent {
  @Input({ required: true }) id!: string;

  title = 'hello world signals';
  $content = toSignal(this.http.get(`${environment.baseUrl}/content/item/${this.id}`));

  constructor(private http: HttpClient) {}
}
```

Here I try to basically use the id which is bound to the component in my service call on the component to avoid using those ngOnInit or Input() set()...

To simplify my code

Note its actually available 

### Please provide a link to a minimal reproduction of the bug

https://github.com/sp90/phantom

### Please provide the exception or error you saw

```true
To start:

1. `npm run api`
2. `npm run dev:ssr`
3. `localhost:4202/123`

It returns undefined but should return the id (123) passed in the url
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.3
Node: 20.0.0 (Unsupported)
Package Manager: npm 9.6.4
OS: darwin arm64

Angular: 16.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
```

### Anything else?

So worth noting is that the input is rendered by the server if put in the template so its something about execution order

**Comment by JoostK** [comment]
This is working as expected; note that `@Input`s are not available immediately upon instantiation of the component, whereas the field initializer for `$content` is. Hence, `$content` is assigned a signal which was created at a time where `this.id` was not yet set.

This cannot be avoided, as the instantiation must have completed before the router is capable of assigning the inputs. Hence, any code that executes during the instantiation can never depend on inputs.

**Comment by sp90** [comment]
While this is working

```
@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export default class HomeComponent {
  private params = inject(ActivatedRoute).snapshot.params;

  $item = toSignal(this.http.get(`http://localhost:4001/api/content/${this.params['id']}`));

  constructor(private http: HttpClient) {}
}
```

So it is available just a bit messy
