### ISSUE TITLE
Impossible to sort by date in a signal computed

### ISSUE THREAD

**Issue by alcaideio** [angular/angular#50563]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I have a list of todos : 
```
 interface Todo {
   id: string;
   text: string;
   creationDate: Date;
   completed: boolean;
}
```
and i would like to sort the list by date 
`const sortByDate = computed(() => todosSignal().sort((a, b) => b.creationDate.getTime() - a.creationDate.getTime()))`
But i have the error getTime is not a function. Normally creationDate (type Date) have getTime function available. 
How is it done?

### Please provide the exception or error you saw

```true
src_app_todos_todo_routes_ts.js:2 ERROR TypeError: a.creationDate.getTime is not a function
    at todos.signal.ts:48:41
    at Array.sort (<anonymous>)
    at ComputedImpl.computation (todos.signal.ts:47:34)
    at ComputedImpl.recomputeValue (core.mjs:2539:29)
    at ComputedImpl.onProducerUpdateValueVersion (core.mjs:2525:14)
    at ComputedImpl.signal (core.mjs:2561:14)
    at TodosComponent_app_todo_list_4_Template (todos.component.ts:17:10)
    at ReactiveLViewConsumer.runInContext (core.mjs:10393:13)
    at executeTemplate (core.mjs:10933:22)
    at refreshView (core.mjs:12443:13)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.3
@angular-devkit/build-angular   16.0.3
@angular-devkit/core            16.0.3
@angular-devkit/schematics      16.0.3
@schematics/angular             16.0.3
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by JeanMeche** [comment]
Hi, how do you create your `todosSignal` ?

**Comment by alcaideio** [comment]
const todosSignal = signal<Todo[]>([]);

**Comment by JeanMeche** [comment]
Could you provide stackblitz repo ?  its seems you have an usage issue.

**Comment by alcaideio** [comment]
No it's works https://stackblitz.com/edit/stackblitz-starters-gk5qtr?file=src%2Fmain.ts
I know it's because of the local storage parsing 
`const INITIAL_TODOS = JSON.parse(localStorage.getItem('todos') || '') || [];
`
Merci ;)
