### ISSUE TITLE
Schematics for library: npm link dist/my-lib command is incorrect

### ISSUE THREAD

**Issue by utamuratov** [angular/angular#50572]
### Describe the problem that you experienced

I have run npm link dist/my-lib to link the library. But the command is incorrect

### Enter the URL of the topic with the problem

https://angular.io/guide/schematics-for-libraries#providing-installation-support

### Describe what you were looking for in the documentation

The right command is  the following: 
npm link dist/my-lib/

**Comment by ManishDait** [comment]
@pkozlowski-opensource I would like to work on these pr
