### ISSUE TITLE
`toSignal` typings are incorrect

### ISSUE THREAD

**Issue by Lonli-Lokli** [angular/angular#50591]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I would like to clarify why toSignal typings are so complicated? I mean there 2 ways to declare signals and one of them is working another one is not, also it depends on the TypeScript settings for strictness

Why don't you want to declare it as a 3rd way (in sample)?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-fngvnl?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
nothing
```

**Comment by alxhub** [comment]
As far as I can tell, the reproduction stackblitz is broken - it doesn't include proper typings for `Observable`, so TS type inference is not working correctly.

See this [stackblitz](https://stackblitz.com/edit/stackblitz-starters-tfivxc?file=src%2Fmain.ts) for an example of the APIs with working typings (at least on my machine...).

**Comment by Lonli-Lokli** [comment]
```ts
interface IUser {
  id: number;
}

const users$: Observable<IUser[]> = of([]);

// Signal<IUser[]|undefined>
const s1 = toSignal(users$);

// Signal<IUser[]>
const s2 = toSignal(users$, { initialValue: [] as IUser[] });

// Signal<IUser[]>
const s3 = toSignal(users$, { requireSync: true });

// Signal<IUser[] | never[]>
const s4 = toSignal(users$, { initialValue: [] });

// not compile
//const s5 = toSignal<IUser[]>(users$, { initialValue: [] });

// not compile
//const s6 = toSignal<IUser[]>(users$, { initialValue: [] as IUser[]});

// Signal<IUser[]>
const s7 = toSignal<IUser[], IUser[]>(users$, { initialValue: [] });

```

So `s5` and `s6` are not compiling, while `s7` is what people usually want under the strict - add the generic to toSignal and eliminate TypeScript error.

I know that TS complains about [] as never[] (https://github.com/Microsoft/TypeScript/issues/18687) but I really would like to `s5` behave like `s7`

**Comment by Lonli-Lokli** [comment]
Also, not sure if it's related, but why angular does not have any type tests? It's typescript project, with sometimes really difficult overrides, and do not have something like this https://github.com/effector/effector/blob/master/src/types/__tests__/effector/forward.test.ts
