### ISSUE TITLE
getCurrentNavigation() is null on Angular 15.. Cannot access nested route state params

### ISSUE THREAD

**Issue by sky0matic** [angular/angular#50595]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

Since Angular 15, we cannot rely on `router.getCurrentNavigation().extras.state` anymore (like describe here in https://github.com/angular/angular/issues/48744), however, the alternative of using `location.getState()` doesn't work with nested childs and `skipLocationChange: true`.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-af332a?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html

1. Go to the StackBlitz.
2. Click the `Trigger error` button.
3. Notice no failure reason is shown.

### Please provide the exception or error you saw

```true
- `router.getCurrentNavigation()` is now `null` in the `constructor`.
- `location.getState()` returns the `FooComponent` state params.

There's no actual way of getting my `failure` state params..
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
`Angular`: 15.0.2 (stackblitz), 15.2.8 (local project)
```

### Anything else?

We have nested routes for error routes and nested routes for "normal" routes in our SPA, before we could rely on `router.getCurrentNavigation().extras.state` to get the `failure` state params which we cannot do anymore..

**Comment by JeanMeche** [comment]
Just a note, if you have the possibility to migrate to v16 there is [`lastSuccessfulNavigation`](https://angular.io/api/router/Router#lastSuccessfulNavigation)

**Comment by sky0matic** [comment]
> Just a note, if you have the possibility to migrate to v16 there is [`lastSuccessfulNavigation`](https://angular.io/api/router/Router#lastSuccessfulNavigation)

Thanks for the quick reply, however, we are due to release really soon and cannot afford to migrate to v16 for now 😞

**Comment by atscott** [comment]
This is working as expected and a documented breaking change in v15 (https://angular.io/guide/update-to-version-15#routeroutlet-instantiates-the-component-after-change-detection). Since you’re accessing state, you should get this from Location.getState rather than relying on exact component activation timing.

**Comment by sky0matic** [comment]
> This is working as expected and a documented breaking change in v15 (https://angular.io/guide/update-to-version-15#routeroutlet-instantiates-the-component-after-change-detection). Since you’re accessing state, you should get this from Location.getState rather than relying on exact component activation timing.

I'm sorry, but I'm already mentionned that using Location.getState doesn't work in my use case and provided an example in the StackBlitz... Am I missing something here ?!

**Comment by sky0matic** [comment]
@atscott Tagging you, because I don't know if you receive replies, but `location.getState()` doesn't work with `skipLocationChange` and nested routes that is my issue

**Comment by atscott** [comment]
@sky0matic there are at least a couple other options for you: 
- fork the RouterOutlet code from pre v15 to maintain the component activation timing you’re looking for
- create a service that subscribes to the navigation events and save the state to a service o you can get it from your component.

**Comment by sky0matic** [comment]
@atscott We'll forget the first one, we don't have the ressources to do and maintain that.
For the service, I've tried to subscribe to the Router.events observable, but I can't seem to find where I would get my state params..

On the `NavigationEnd` one we only get : id, type, url, urlAfterRedirects.

I've tried to check other types of events like `ChildActivationEnd` and `ActivationEnd`, but can't seem to find anything that helps me

**Comment by JoostK** [comment]
Lots of possibilities, it seems: https://stackblitz.com/edit/angular-ivy-3czghp?file=src%2Fapp%2Fapp.module.ts
