### ISSUE TITLE
Special case binding to hidden property.

### ISSUE THREAD

**Issue by mhevery** [angular/angular#506]
Element `hidden` property should mostly work, but we need to special case it for the purposes of animation. Not sure how much work needs to be done here.

**Comment by naomiblack** [comment]
This is needed for Animation, needs a little work to find out what we should actually do.

**Comment by mhevery** [comment]
Dup #754

**Comment by stajs** [comment]
Just wanted to check:

0. is this closed issue about the [`hidden` or `aria-hidden` attribute](http://stackoverflow.com/questions/31107040/whats-the-difference-between-html-hidden-and-aria-hidden-attributes), and
0. that the referenced issue is correct?

If it's about `aria-hidden` I can see a connection, but I followed a [reference from SO](http://stackoverflow.com/a/30746262/2685650) about [`hidden`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden) so just clarifying.
