### ISSUE TITLE
Add change detection strategy for directives

### ISSUE THREAD

**Issue by ziv** [angular/angular#50601]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

While directives are template-less components, they still register the same life cycle.

Components with multiple directives in their templates have mixed change detection strategies. The components use `OnPush` while the directives use the default one and increase the change detection time.

This is another try to start a new vote for this feature:
https://github.com/angular/angular/issues/19098

### Proposed solution

Add change detection strategy for directives to support `onPush`.

### Alternatives considered

Not using directives.

**Comment by pkozlowski-opensource** [comment]
We haven't heard back with more info so I'm going to close this issue for now. Happy to reopen when more info surfaces.
