### ISSUE TITLE
Proposal for testing sugar

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#5060]
A really common pattern in Angular 2 testing is to wrap the entire `it` callback in `injectAsync`. I think that can be sugarized a bit. It can also be a good solution against abusive indentation coming from `clang-format`.

```
it('should show 10 stars by default', injectAsync([TestComponentBuilder], (tcb) => {
     return tcb.createAsync(NgbRating).then((fixture) => {
       fixture.detectChanges();

       const compiled = fixture.debugElement.nativeElement;

       const stars = getStars(compiled);
       expect(stars.length).toBe(10);
     });
   }));
```

Martin at `clang-format` suggested to use a wrapper like:

```
function itIj(msg: string, ...componentOrFn: Function[]) {
  let injectables = componentOrFn.slice(0, -1);
  let testFn = componentOrFn.slice(-1)[0];
  it(msg, injectables, testFn);
}
```

I am not fond of having wrappers like that in my codebase (to workaround a formatter), but since Angular desperately needs lot of sugar around testing, I think this is a good candidate.

Check angular/clang-format#20 for more information.

Cheers.

**Comment by juliemr** [comment]
We should have better syntax once `inject` and `async` are separated.
