### ISSUE TITLE
RouterLinkDirective does not perform navigation to child outlet route after initial navigation

### ISSUE THREAD

**Issue by Marcarrian** [angular/angular#50611]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

When navigating via `RouterLinkDirective` to a child route with a defined outlet, no navigation is performed after the initial navigation.

Following routes setup:
```ts
export const routes: Routes = [
  {
    path: 'list',
    children: [
      {
        path: '',
        component: ListComponent,
      },
      {
        path: ':name',
        outlet: 'details',
        component: DetailsComponent,
      },
    ],
  },
];
```

In `ListComponent` I use the `RouterLinkDirective` to navigate to  `/list/(details:item-1)`:
```html
<a [routerLink]="[{outlets: {details: ['item-1']}}]"></a> // successful navigation
```

The **initial navigation** to `/list/(details:item-1)` **is successful.**

Every subsequent navigation to the child route has no effect. For example:
```html
<a [routerLink]="[{outlets: {details: ['item-2']}}]"></a> // no effect
```
The path is **not** updated with  `/list/(details:item-2)` as expected. Instead, nothing happens and the path stays `/list/(details:item-1)`.

Removing the outlet has no effect either.
```html
<a [routerLink]="[{outlets: {details: null}}]"></a> // no effect
```
Same with passing matrix parameters. No effect.
```html
<a [routerLink]="[{outlets: {details: ['item-2', {foo: 'bar'}]}}]"></a> // no effect
```

***
In contrast, all the cases mentioned work as expected when navigating with **an absolute path**
```html
<a [routerLink]="['list', {outlets: {details: ['item-2']}}]" [relativeTo]="null"></a> // successful navigation
```
**or when navigating with `Router`.**
```ts
this._router.navigate(['list', {outlets: {details: ['item-2']}}]); // successful navigation
this._router.navigate(['list', {outlets: {details: ['item-2', {foo: 'bar'}]}}]); // successful navigation (matrix parameters are passed)
this._router.navigate(['list', {outlets: {details: null}}]); // successful navigation (outlet is removed)
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/github/Marcarrian/angular-16-router-outlet-bug

### Please provide the exception or error you saw

```true
No error or exception. No navigation is performed after initial navigation.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.5
Node: 18.16.0
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 16.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.5
@angular-devkit/build-angular   16.0.5
@angular-devkit/core            16.0.5
@angular-devkit/schematics      16.0.5
@angular/cli                    16.0.5
@schematics/angular             16.0.5
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by sunshuhan** [comment]
hello, just to narrow down the scope, i think the error probably occurs in version 16.0.0,  15.2.x works fine while 16.0.0 has the problem of not switching using relative router-link.  Hope it would help

**Comment by sunshuhan** [comment]
hello, just to narrow down the scope, i think the error probably occurs in version 16.0.0.

@angular/router 15.2.x works fine while 16.0.0 has the problem of not switching using relative routerLink. 

Note that 16.0.0 made quiet a few changes on router module. Hope it would help locate the problem.

**Comment by sunshuhan** [comment]
Hi, i found a warning in the console when using v15.2.9 navigate using relative routerLink :
![image](https://github.com/angular/angular/assets/9651193/e62516b8-fb12-4e2c-9ce9-6ee8b1224979)

The warning occurs within the **create_url_tree_strategy.ts** in v15.2.9: 
```
export class LegacyCreateUrlTree implements CreateUrlTreeStrategy {
  createUrlTree(
      relativeTo: ActivatedRoute|null|undefined, currentState: RouterState, currentUrlTree: UrlTree,
      commands: any[], queryParams: Params|null, fragment: string|null): UrlTree {
    const a = relativeTo || currentState.root;
    const tree = createUrlTree(a, currentUrlTree, commands, queryParams, fragment);
    if (NG_DEV_MODE) {
      const treeFromSnapshotStrategy = new CreateUrlTreeUsingSnapshot().createUrlTree(
          relativeTo, currentState, currentUrlTree, commands, queryParams, fragment);
      if (treeFromSnapshotStrategy.toString() !== tree.toString()) {
        let warningString = `The navigation to ${tree.toString()} will instead go to ${
            treeFromSnapshotStrategy.toString()} in an upcoming version of Angular.`;
        if (!!relativeTo) {
          warningString += ' `relativeTo` might need to be removed from the `UrlCreationOptions`.';
        }
        tree._warnIfUsedForNavigation = warningString;
      }
    }
    return tree;
  }
}
```

LegacyCreateUrlTree is removed in v16.0.0,  and CreateUrlTreeUsingSnapshot strategy is used instead in this pull request: [refactor(router): Remove legacy url creation code #49360](https://github.com/angular/angular/pull/49360)
![image](https://github.com/angular/angular/assets/9651193/8ebdb87c-ee6e-4bb9-a0a3-4284af72dd7b)

But there is no error or warning in the v16.0.0 using relative routerLink while the navigation is not perfomed. If would be better to give some hints if **relativeTo** is not working as expected.




,

**Comment by pkozlowski-opensource** [comment]
Sounds like this is an expected behaviour and we've got an approach that works in the recent version of Angular. Thank you so much @sunshuhan for digging into it and helping others here on GitHub - this is very much appreciated!
