### ISSUE TITLE
Using Hydration with i18n caused duplicated component content

### ISSUE THREAD

**Issue by hijamoya** [angular/angular#50627]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When we enable hydration in our project, we found that if we annotate some nodes with i18n attribute in one component, the component will be rendered twice.

The sample project can fully reproduce this behavior.

### Please provide a link to a minimal reproduction of the bug

https://github.com/hijamoya/i18n-hydration

### Please provide the exception or error you saw

```true
The i18n should work normally as the document said:
Angular would skip hydration for components that use i18n blocks, effectively re-rendering those components from scratch.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.5
Node: 18.16.0
Package Manager: npm 9.5.1
OS: darwin x64

Angular: 16.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.5
@angular-devkit/build-angular   16.0.5
@angular-devkit/core            16.0.5
@angular-devkit/schematics      16.0.5
@nguniversal/builders           16.0.2
@nguniversal/express-engine     16.0.2
@schematics/angular             16.0.5
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by AndrewKushnir** [comment]
@hijamoya thanks for reporting the issue and thanks for a great repro 👍 

We've identified the problem and created a PR https://github.com/angular/angular/pull/50644 to fix it. The fix would be available in one of the upcoming patch releases.

Thank you.
