### ISSUE TITLE
Cannot apply styling to a component

### ISSUE THREAD

**Issue by Arbabian21** [angular/angular#50626]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

You cannot apply styling to components. I made a component called a calculator. I used it's selector in app-module.html.  I went to the CSS for app-module.html and tried to apply styling to the selected app-calculator{} and it did not work properly. Try creating a border around it and you'll see what I'm talking about.

**Comment by JeanMeche** [comment]
Hi, that is expected. Have a look at the [View encapsulation guide](https://angular.io/guide/view-encapsulation).
