### ISSUE TITLE
[Question] Is AsyncPipe compatible with Rx Observable?

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#5062]
I was wondering if the [AsyncPipe](https://angular.io/docs/ts/latest/api/core/AsyncPipe-class.html) is compatible with the Rx [Observable](https://github.com/ReactiveX/RxJS/blob/master/src/Observable.ts), because from the looks of it, it seems not to be.

I have a [plunk](http://plnkr.co/edit/JuFb9Ypoqj9Omkwj7jPb?p=preview) that illustrates how I'm trying to use the pipe and it keeps throwing exceptions.

**Comment by ericmartinezr** [comment]
Not, not yet. AFAIK it works with Promises, but it has been refactored to work with Observables, see https://github.com/angular/angular/issues/4588, so it's just a matter of time until the next release.

**Comment by robwormald** [comment]
Works in master, so you should see this working on the next release. In the interim, there's an Rx pipe you can use instead here : http://plnkr.co/edit/pUfJ0b3Kay59PfkPEBlo?p=preview
