### ISSUE TITLE
[question] Angular2 and app modularity

### ISSUE THREAD

**Issue by artaommahe** [angular/angular#5063]
Angular1 allows to build flexible modular app structure, e.x.(part of current project)
```
├── admin-panel-module
├── auth-module
├── chat-module
│   ├── channels-module
│   ├── history-module
│   │   ├── filter-addressed-module
│   │   ├── filter-user-module
│   ├── text-input-module
│   ├── thirdparty-module
│   │   ├── goodgame-module
│   │   └── twitch-module
│   └── tools-module
├── donate-module
├── stream-module
├── subscribe-module
├── support-module
```
where each module contains directives, services and any other things(e.x. react components). Also each module has index.js file where angular module is declared and directives/services assigned. And this module uses as dependency for another.
```js
// smth-module/index.js
var angular = require('angular');

var smthFactory = require('./provider/smth.factory');
var smthDirective = require('./directive/smth.directive');

var SmthModule = angular.module('SmthModule', []);

SmthModule.factory('smthFactory', smthFactory);
SmthModule.directive('smth', smthDirective);

module.exports = SmthModule;

// app.js
var angular = require('angular');

var SmthModule = require('./smth-module');

var app = angular.module('app', [
  SmthModule,
  ...
]);
```
So we declare all module items in this module, add it as dependency for top level module and can use this module directives/services anywhere in our app.
Bun what with this thing in Angular2? I tried to build small side project with alpha45 and can't find anything about modular structure. For simple two modules
```
main-module
   component
    main
      main.ts
chat-module
  component
    chat
      chat.ts
  service
    chat.ts
```
if i want to use chat component or service in main, i need to import it by whole relative path
```js
import {ChatCmp} from '../../chat-module/component/chat/chat'
import {Chat} from '../../chat-module/service/chat'
```
and so with each component from another module. If modules will be reallocated, i must fix each import to new relative path.
Also if service requires smth like Http
```js
import {Injectable} from 'angular2/angular2';
import {Http} from 'angular2/http';

@Injectable()
export class Chat {
  constructor(private http: Http) {
    //
  }
}
```
it's necessary to inject HTTP_PROVIDERS services on top level of app(```bootstrap.js```) or for each component that uses this service(or depend on components inheritance).
Again this thing breaks modular structure - components/services from ona module knows about path to components/services from other modules and must watch their dependencies. And this easily solves via modules system of Angular1.

Am i missed something or there is any other thing in plans for this cases? I don't see comfortable use of current ng2 app structure anythere except small project without need of modulaity. Thx )

**Comment by evanplaice** [comment]
If you're using System.js you can create map an alias to a particular component.

With the directory tree:
```
main-module
   component
    main
      main.ts
chat-module
  component
    chat
      chat.ts
  service
    chat.ts

Lets say you want to add aliases for:

```
import {ChatCmp} from '../../chat-module/component/chat/chat'
import {Chat} from '../../chat-module/service/chat'
```

config.js
```
...
map: {
    "chat-component": "/chat-module/component/chat/chat",
    "chat-service": "/chat-module/service/chat",
...
```

So your imports would be:
```
import {ChatCmp} from 'chat-component'
import {Chat} from 'chat-service'
```

---

Alternatively, you could do:

config.js
```
...
map: {
    "chat": "chat-module",
...
```

So your imports would be:
```
import {ChatCmp} from '/chat/component/chat/chat'
import {Chat} from '/chat/service/chat'
```

**Comment by artaommahe** [comment]
It solves only paths problem and depends on System.js. Also config map cannot be stored at module level and there is no comfortable cases for adding third-party ng2 module to app.

**Comment by amsingh-qasource** [comment]
hfhfhffg
![koala](https://cloud.githubusercontent.com/assets/5499503/11014041/ac544228-854b-11e5-8335-0f344ce505ea.jpg)

**Comment by schippie** [comment]
@evanplaice This does not answer the final part of @artaommahe question:

> it's necessary to inject HTTP_PROVIDERS services on top level of app(bootstrap.js) or for each component that uses this service(or depend on components inheritance).
Again this thing breaks modular structure - components/services from ona module knows about path to components/services from other modules and must watch their dependencies. And this easily solves via modules system of Angular1.

Which is also a problem i am running into immediately: http://stackoverflow.com/questions/33584763/hot-to-avoid-declaring-all-services-in-the-bootstrap-function

It all comes down to the fact that everything has to be within the bootstrap function. 
I just did some tests and even using the providers on sub-components creates a new instance of the specific @Injectable class. 

This also becomes really annoying when you want to share packages. Lets say i build a module, that module has 10 services those are all nested one below the other or something. The person who grabs my package has to include each and every one of those Classes within the import of his "app"(base) component and add them to the bootstrap function as well. 
If they want to even use the modules. 

Please correct me if i am wrong about it, because this change breaks the way i used to work with Angular1 in which i saw each service as a Singleton that i used throughout my controllers / other services and even sometimes project specific directives. While this is still possible i would now be forced to specify all those services within the bootstrap method to make them available application wide.

**Comment by alexpods** [comment]
@schippie Just create `index.js` files for your modules and export all "public" providers from there. Then import these providers in a main file and use them in `bootstrap` function. (basically it's exactly like what you did in angular1). 

```js
// smth-module/index.js
import { SmthService } from './smth.service');
import { SmthComponent } from './smth.component';

export const SMTH_MODULE = [
    SmthFactory,
    SmthComponent
];

// app.js
import { SMTH_MODULE } from './smth-module';
// other imports...

bootstrap(AppComponent, [SMTH_MODULE /*, other providers */]);

**Comment by schippie** [comment]
@alexpods Okay, I got the same answer on [stackoverflow](http://stackoverflow.com/questions/33584763/hot-to-avoid-declaring-all-services-in-the-bootstrap-function#comment54950638_33584763) the with Core directives example. 
I guess while I have to adjust myself to this new way of writing, it will be very similar to dealing with Polymer components. 

I guess a good way to deal with it is make a base file for each directory (model/ , utils/ , components/) 

Thank you :+1:

**Comment by alexpods** [comment]
@schippie Actually, I think it's the best to have only one base file for a module. This file is a single public interface of your module.

```js
// smth-module/index.js

import { SmthFactory } from './smth.factory';
import { SmthService } from './smth.service';

import { SmthComponent } from './smth.component';
import { SmthDirective } from './smth.directive';

export { SmthComponent }

export const SMTH_MODULE_PROVIDERS = [
    SmthFactory,
    SmthService,
    // ...
];

export const SMTH_MODULE_DIRECTIVES = [
    SmthComponent,
    SmthDirective,
    // ...
]

// 'app-component.js'

import { Component } from 'angular2/core';
import { SmthDirective } from '../smth-module';
// or import { SMTH_MODULE_DIRECTIVES } from '../smth-module';

@Component({
    // ...
    directives: [SmthDirective], // or directives: [SMTH_MODULE_DIRECTIVES]
    template: `<smth-directive></smth-directive>`
})
export class AppComponent() {}

// 'app.js'
import { SMTH_MODULE_PROVIDERS } from '../smth-module';
import { AppComponent } from './app-component.js';

bootstrap(AppComponent, [SMTH_MODULE_PROVIDERS /*, other providers */]);

**Comment by schippie** [comment]
@alexpods Oh no no, my situation that I was describing at the end with the sub-directories had more to do with the fact that within a single project you could run into large file bases as well. At that point since its purely for a project (non public) it would be the way I would handle it.

For modules I or anybody would write having a single file is the only correct way to prevent confusion.

**Comment by artaommahe** [comment]
Ok.. i decied to try again.
Used [angular2-seed](https://github.com/mgechev/angular2-seed) with typescript and babel.

Test app sctructure
```
├── bootstrap.ts
├── graph-module
│   ├── component
│   │   └── line-graph
│   │       └── line-graph.ts
│   └── index.ts
├── index.html
└── page-module
    ├── component
    │   └── page
    │       └── page.ts
    └── index.ts
```

```ts
// bootstrap.ts
...
import {PageCmp} from 'page-module/index';

bootstrap(PageCmp, [
  ...
]);
```

```ts
// page.ts
...
import {LineGraphCmp} from 'graph-module/index';

...
export class PageCmp {}
```

```ts
// line-graph.ts
...
export class LineGraphCmp {}
```

```ts
// graph and page modules indexes like this

export {PageCmp} from './component/page/page';
```

```ts
// also added to System.config()
map: {
	'graph-module': '/graph-module',
	'page-module': '/page-module'
}
```

So i can use `export Smth from 'module/index'` syntax and this is almost what i need. But there is one problem
```
app/bootstrap.ts(4,23): error TS2307: Cannot find module 'page-module/index'.
app/page-module/component/page/page.ts(8,28): error TS2307: Cannot find module 'graph-module/index'.
```
How can i tell Typescript compiler about this modules? Or can i achive this modules usage via other way or modules system?

**Comment by artaommahe** [comment]
this issue solves my problem(when Type script will be updated)
https://github.com/Microsoft/TypeScript/issues/5039
