### ISSUE TITLE
Lazy loaded routes are not rendered in SSR when viewing source

### ISSUE THREAD

**Issue by CarlosTorrecillas** [angular/angular#50634]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

When you navigate to a lazy loaded route the content of it does not get rendered (right click on the page and view source) when running SSR.

2.- Do `npm i`
3.- Do `npm run dev:ssr`
4.- Navigate to `http://localhost:4200/lazy-loaded` as in the first URL you paste in the browser or hard refresh on that route

### Please provide a link to a minimal reproduction of the bug

https://github.com/CarlosTorrecillas/universal-issue

### Please provide the exception or error you saw

```true
There is no exception however the HTML does not get rendered
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 16.0.5
Node: 18.10.0
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 16.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.5
@angular-devkit/build-angular   16.0.5
@angular-devkit/core            16.0.5
@angular-devkit/schematics      16.0.5
@nguniversal/builders           16.0.2
@nguniversal/express-engine     16.0.2
@schematics/angular             16.0.5
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by alan-agius4** [comment]
Same root cause of https://github.com/angular/angular/issues/50513

Zone.js fix has not yet been released.

**Comment by CarlosTorrecillas** [comment]
Hi @alan-agius4 , just for me own benefit, when do I expect to be able to upgrade the whole lot with all the fixes that you guys have been addressing? Every time I see a new release in the Angular packages I try to perform the upgrade and I think if the actual fix for Zone has not been released, the issue should still be open? Anyways that's just my personal feedback when I see issues being closed and new versions released

**Comment by alan-agius4** [comment]
Hi @CarlosTorrecillas, 

We expect the zone.js 0.13.1 to be released earlier next week.

Issues get closed when a PR gets merged in the main branch and not released, this is standard Github workflow.

**Comment by CarlosTorrecillas** [comment]
Cool thanks for the info and the explanation :)

**Comment by CarlosTorrecillas** [comment]
Thanks for this!
