### ISSUE TITLE
Hydration not working on dynamic HTML generation

### ISSUE THREAD

**Issue by CarlosTorrecillas** [angular/angular#50635]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

Yes

### Description

When `provideClientHydration()` is enabled on the `app.module.ts` and I have some HTML that gets generated after an async call, then there is an error and no code is rendered when viewing source

### Please provide a link to a minimal reproduction of the bug

https://github.com/CarlosTorrecillas/universal-issue

### Please provide the exception or error you saw

```true
ERROR Error: NG0500: During hydration Angular expected <div> but found <script>.

Angular expected this DOM:

  <div>…</div>  <-- AT THIS LOCATION
  …


Actual DOM is:

<app-json-ld _ngcontent-ng-c4004535330="" ng-reflect-json-ld-data="[objectObject]">
  <script type="application/ld+json">…</script>  <-- AT THIS LOCATION
  …
</app-json-ld>

Note: attributes are only displayed to better represent the DOM but have no effect on hydration mismatches.

To fix this problem:
  * check the "JsonLdComponent" component for hydration-related issues
  * check to see if your template has valid HTML structure
  * or skip hydration by adding the `ngSkipHydration` attribute to its host node in a template

 Find more at https://angular.io/errors/NG0500
    at validateMatchingNode (core.mjs:14377:15)
    at locateOrCreateElementNodeImpl (core.mjs:15324:18)
    at ɵɵelementStart (core.mjs:15223:20)
    at Module.ɵɵelement (core.mjs:15302:5)
    at JsonLdComponent_div_0_Template (json-ld.component.html:1:1)
    at executeTemplate (core.mjs:10938:17)
    at renderView (core.mjs:12126:13)
    at TemplateRef.createEmbeddedViewImpl (core.mjs:22925:9)
    at ViewContainerRef.createEmbeddedView (core.mjs:23190:37)
    at NgIf._updateView (common.mjs:3316:45)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 16.0.5
Node: 18.10.0
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 16.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.5
@angular-devkit/build-angular   16.0.5
@angular-devkit/core            16.0.5
@angular-devkit/schematics      16.0.5
@nguniversal/builders           16.0.2
@nguniversal/express-engine     16.0.2
@schematics/angular             16.0.5
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by jessicajaniuk** [comment]
This is working as intended, but we didn't have the documentation to cover this use case. Using `innerHTML` and `outerHTML` to set dynamically generated DOM is similar to direct DOM manipulation and most definitely will break hydration since Angular instructions didn't create those nodes. You'll want to use `ngSkipHydration` on this component to bypass hydration to make this component work. We've put up a PR to address this lack of documentation.

**Comment by CarlosTorrecillas** [comment]
Thanks for this. The thing is that I was digging and prior opening this issue I found the ngSkipHydration docs as an option to bypass that. I didn’t know if that was the right thing to do though. It seems so. I wonder, for backwards compatibility whether it would be better that angular skips hydration for tags that contain (inner/outer HTML) automatically. Not sure if that could be possible either.

**Comment by jessicajaniuk** [comment]
It is possible and we've discussed the possibility of adding that behavior. For now the hope is that people will follow the link and with the added documentation, they'll have the info they need. However, if it is a frequently surfacing issue, we may go ahead and add that behavior.

**Comment by CarlosTorrecillas** [comment]
I think it would be nice if you include it as a breaking change in the release notes (if not added already). Thanks for the quick reply!
