### ISSUE TITLE
assets/example-house.jpg is missing from live and download examples

### ISSUE THREAD

**Issue by Russ741** [angular/angular#50647]
### Describe the problem that you experienced

In lesson 4, step 3 (https://angular.io/tutorial/first-app/first-app-lesson-04#step-3---create-a-test-house-for-your-app), a stub HousingLocation object is created with a photo attribute of 'assets/example-house.jpg'.

This attribute is used in lesson 7, but the image it refers to isn't in either the live or downloaded example.

### Enter the URL of the topic with the problem

https://angular.io/tutorial/first-app/first-app-lesson-07

### Describe what you were looking for in the documentation

A copy of the image to save in my local repo.

### Describe the actions that led you to experience the problem

Following the tutorial (see description).

### Describe what you want to experience that would fix the problem

Include example-house.jpg in the .zip for each step and in the StackBlitz environments.

### Add a screenshot if that helps illustrate the problem

![lesson-7](https://github.com/angular/angular/assets/72242656/d20c17a7-8401-404b-89c1-bd7da6c24a5b)

**Comment by JeanMeche** [comment]
Hi, it has been reported by #50329 already but the author closed it. It is closely related to #48773.

Stackblitz doesn't support binary images and the jpgs aren't included in the zips per : 
https://github.com/angular/angular/blob/6f5dabe0d25a5660b7c3001041449b4622dd8924/aio/tools/stackblitz-builder/builder.mjs#L258


I'll leave this issue open to track the issue, thanks for the report 👍

**Comment by rakeshsharma767** [comment]
I am running on local env and not using Stackblitz . Missing image should be there in asset folder. Please let me know how to fix this.

**Comment by JeanMeche** [comment]
It’s the same script generating both the zip you downloaded and the stack blitz content !

**Comment by rakeshsharma767** [comment]
I can see this error on browser console(Edge) and page dont have any details from component. No sure what is wrong with code. I am following the steps in tutorial. Any help?

 _TypeError: Cannot read properties of undefined (reading 'name')
    at HousingLocationComponent_Template (housing-location.component.ts:11:62)
    at ReactiveLViewConsumer.runtext (core.mjs:10393:13)
    at executeTemplate (core.mjs:10933:22)
    at refreshView (core.mjs:12443:13)
    at refreshComponent (core.mjs:12590:13)
    at refreshChildComponents (core.mjs:12637:9)
    at refreshView (core.mjs:12493:13)
    at refreshComponent (core.mjs:12590:13)
    at refreshChildComponents (core.mjs:12637:9)
    at refreshView (core.mjs:12493:13)_

<img width="448" alt="firstApp" src="https://github.com/angular/angular/assets/19954011/234f775e-d4dc-459d-8c21-09ded8d3bf2c">

**Comment by rakeshsharma767** [comment]
> TypeError: Cannot read properties of undefined

My bad - 
This tag was giving error <app-housing-location>[housingLocation]="housingLocation"></app-housing-location>..later corrected and TypeError gone.
I was expecting something related and meaningful error message :)

**Comment by nczempin** [comment]
It looks like now there are neither .jpg nor .svg in the generated .zip file.

https://github.com/angular/angular/tree/main/aio/content/examples/first-app-lesson-00/src/assets from https://github.com/angular/angular/commit/1c7f6902471bcc8654e2db03ec10e33b0f68e504

has the .jpg files, but presumably some build process is ignoring them.

https://github.com/JeanMeche/angular/tree/main/aio/content/examples/first-app-lesson-00/src/assets has the .svg files, but in some issue comment I read "we are going in another direction, we will serve these files".

So now we have neither .jpg nor .svg in the example zip, and the first-app tutorial is thus broken.

my workaround is to grab the jpgs and put them in the unzipped folder (the project is still referencing .jpg), but my expectation would be that the tutorial not be left in this half-finished state.

**Comment by JeanMeche** [comment]
This issue has been fixed by #51014 !
