### ISSUE TITLE
ViewContainer.createComponent inside a directive adds the component as a SIBLING of the element

### ISSUE THREAD

**Issue by yades218** [angular/angular#50659]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I have a requirement of creating a structural directive that creates a child component inside the element where the directive is being called. If I use ViewConainerRef.createComponent, component is injected as a SIBLING of the element where the directive is called. i.e:

@Directive({
  selector: '[s-tooltip]'
})
export class STooltip implements OnInit {

  constructor(private viewContainer: ViewContainerRef) {
   }
  
  showTool(){
        const tool = this.viewContainer.createComponent(ToolTipComponent, {index:0})
   })
}

If I write a directive called s-tooltip, Like this and want to inject <ToolTipComponent>when click the component: 
<div s-tooltip></div>

Here is what it currently outputs:
<div></div>
<TooltipComponent></TooltipComponent>

And what I was expecting was this:
<div>
    <TooltipComponent></TooltipComponent>
</div>

I found the issues in Angular 8， but it still there in Angular15

Thanks.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-insert-component-in-structural-directive?file=app%2Fapp.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/core": "~15.2.0",
Node: 16,
Window: 11
```

**Comment by JeanMeche** [comment]
Hi, this question has been discussed in #8817 and #29448.

**Comment by yades218** [comment]
> Hi, this question has been discussed in #8817 and #29448.

But how can I insert componet into directive hostView?

**Comment by JeanMeche** [comment]
You could do something like that : 

export class MyDirective {
  constructor(private element: ElementRef,
    private viewContainerRef: ViewContainerRef,
    private componentFactoryResolver: ComponentFactoryResolver
  ) { }

  ngOnInit() {
    const componentRef = this.viewContainerRef.createComponent(MyComponent);

    const host = this.element.nativeElement;
    host.insertBefore(componentRef.location.nativeElement, host.firstChild)
  }
}

**Comment by yades218** [comment]
Thanks for Matthieu Riegler's reply， I solve the problem!

Matthieu Riegler: 

You could do something like that :

export class MyDirective {
constructor(private element: ElementRef,
private viewContainerRef: ViewContainerRef,
private componentFactoryResolver: ComponentFactoryResolver
) { }

ngOnInit() {
const componentRef = this.viewContainerRef.createComponent(MyComponent);

const host = this.element.nativeElement;
host.insertBefore(componentRef.location.nativeElement, host.firstChild)
}
}

Thanks a lot!

**Comment by yades218** [comment]
> You could do something like that :
> 
> ```
> export class MyDirective {
>   constructor(private element: ElementRef,
>     private viewContainerRef: ViewContainerRef,
>     private componentFactoryResolver: ComponentFactoryResolver
>   ) { }
> 
>   ngOnInit() {
>     const componentRef = this.viewContainerRef.createComponent(MyComponent);
> 
>     const host = this.element.nativeElement;
>     host.insertBefore(componentRef.location.nativeElement, host.firstChild)
>   }
> } 
> ```

It works! Thanks a lot!
