### ISSUE TITLE
Warning messages for signal

### ISSUE THREAD

**Issue by IsaacSomething** [angular/angular#50658]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

I have currently found 2 instances where signals do not work; for good reason, however there are no warning messages indicating anything is wrong.

scenario 1:
```html
{{ this.mySignal }}
```
```ts
mySignal = this.mySignalService.mySignal();
```
The signal will not work if the parenthesis is not in the template itself.

scenario 2: 
```ts
 effect(() => this.mySignalService.mySignal.set(false));
 ```
 This will obviously cause an infinite loop, but there is no warning messages, it just doesn't work, there is no real indication of any issue.

### Proposed solution

Add console error messages. Might be nice to have something like redux devtools that can monitor the state of all the signals.

### Alternatives considered

none

**Comment by JeanMeche** [comment]
Your 2nd scenario should throw a NG600 (`Error: NG0600: Writing to signals is not allowed in a `computed` or an `effect` by default. Use `allowSignalWrites` in the `CreateEffectOptions` to enable this inside effects.`).

Do you have a repro where this doesn't happen ?
