### ISSUE TITLE
plnkr needs to be updated provider.ts

### ISSUE THREAD

**Issue by jennyraj** [angular/angular#5065]
### Example ([live demo](http://plnkr.co/edit/QsatsOJJ6P8T2fMe9gr8?p=preview))
###^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Looks like it is not the right one, plnkr link has to be fixed.

**Comment by pkozlowski-opensource** [comment]
It is not clear what this issue is all about, closing....
