### ISSUE TITLE
toObservable() completes on Component's destroy, even when it is still used

### ISSUE THREAD

**Issue by MaciejWWojcik** [angular/angular#50684]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

based on this line from [RFC](https://github.com/angular/angular/discussions/49681):
> Observables are designed to manage the lifecycle of the side effects they create. When a toObservable Observable is subscribed, it creates an effect to monitor the signal, which exists until that subscriber unsubscribes.

I assumed that if I have a `signal` created in a Service, and subscribed to it inside that Service using `toObservable` function, the subscription should not be automatically completed on the component's destroy - even though, the signal reference is passed to that component.

Steps to reproduce:
1. create a Service (provided in root) and a property with signal, using `signal()` function
2. in that Service, create an Observable using `toObservable()` function, passing created signal
3. return a reference to the signal to some component, but still keep it and actively use it within the Service
4. destroy the component 
5. Observable is automatically completed

I'm not passing the injector from the component, and I'm actively calling .update() on the signal, so the signal is actively being used as well as the subscription - I see no point in closing the subscription on the component's destroy in this case. 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-ggutng?file=src%2Fcalculation.service.ts

### Please provide the exception or error you saw

```true
-
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Stackblitz environment with Angular CLI 16.0.4
```

**Comment by JeanMeche** [comment]
Hi, 

The way you wrote it, it's totally expected. 

https://github.com/angular/angular/blob/1400e5589da2a381d689d47477a1452d55daf607/packages/core/rxjs-interop/src/to_observable.ts#L54-L57

`toObservable` when called is registering to the `DestroyRef`. Since you called from the context of the component, its when the component gets destroyed that the observable gets completed.

**Comment by MaciejWWojcik** [comment]
oh, okay - somehow I thought that the service method scope will be used for that, but yeah - the method was called from the component, so that makes sense. 

Thanks so much for that, silly me.
