### ISSUE TITLE
HTML Entity code is not rendered correctly in [innerHTML]

### ISSUE THREAD

**Issue by tortuc** [angular/angular#50692]
### Which @angular/* package(s) are the source of the bug?

elements

### Is this a regression?

Yes

### Description

I tried the HTML Entity code sting in Angular template present. 
`"&#60;div&#62;&#8203;dsfdsfsfadfsfdsfsfaf&#60;span&#32;style&#61;&#34;white&#45;space&#58;pre&#34;&#62;&#9;&#60;&#47;span&#62;&#60;&#47;div&#62;"
`
But It doesn't render this dom element correctly, It render like this screen.
![image](https://github.com/angular/angular/assets/65579678/606894e4-2b09-4aa0-93a1-8ee19c50a3ba)

### Please provide the exception or error you saw

```true
https://github.com/angular/angular/assets/65579678/606894e4-2b09-4aa0-93a1-8ee19c50a3ba
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.0
```

**Comment by JoostK** [comment]
It is unclear what your expected behavior is, at first glance this seems to behave as expected to me.

**Comment by pkozlowski-opensource** [comment]
Agree with Jost, the scenario itself is not clear to me. Could you please share a minimal reproduce scenario using stackblitz?

**Comment by tortuc** [comment]
As you can see in the scree, there are html tags, It should render `dsfdsfsfadfsfdsfsfaf` formatted completely.

**Comment by JoostK** [comment]
Why shouldn't the HTML be there? They are present in the original text as encoded entities, so they should show up?

**Comment by pkozlowski-opensource** [comment]
TBH it is not clear to me what the reproduction scenario we are discussing here, but assuming https://stackblitz.com/edit/stackblitz-starters-brqhtu?file=src%2Fmain.ts 

```typescript
@Component({
  selector: 'my-app',
  standalone: true,
  template: `&#60;div&#62;&#8203;dsfdsfsfadfsfdsfsfaf&#60;span&#32;style&#61;&#34;white&#45;space&#58;pre&#34;&#62;&#9;&#60;&#47;span&#62;&#60;&#47;div&#62;`,
})
export class App {
  name = 'Angular';
}
```

If this is the case the observed rendering is very much expected - HTML encoding _is_ here to render required characters.
