### ISSUE TITLE
[router] link to child routes of async route

### ISSUE THREAD

**Issue by Necroskillz** [angular/angular#5071]
As far as I can tell, you can't link to child routes of a component, which itself is loaded with an asynchronous route. I understand the the router can't see the child component routes until it is loaded, so generating a link at that time is hard.

But as it is, you cannot deep link into routes of asynchronously loaded components.

See example: http://plnkr.co/edit/wrjv7cBzDKkxZVEKZavf

If you try to run it you get `EXCEPTION: Could not find route named "Home". in [null]`

Important code:

Main route config (app.ts)
```
@RouteConfig([
    {path: '/', component: Home, as: 'Home'},
    {path: '/lazy/...', loader: () => System.import('lazy').then(c => c['AppComponent']), as: 'Lazy'}
])
```

Main component link
```
<li><a [router-link]="[ '/Lazy', 'Home' ]">Lazy</a></li>
<li><a [router-link]="[ '/Lazy', 'Events' ]">Lazy - Events</a></li>
```

Child route config (lazy.ts)
```
@RouteConfig([
    { path: '/', component: LazyHome, as: 'Home' },
    { path: '/events', component: Events, as: 'Events' }
])
```

**Comment by Necroskillz** [comment]
I mean, I guess I could just use normal url like `/lazy/events`, instead of router-link.

**Comment by btford** [comment]
:+1: @matsko and I have been talking about a refactor that would start to address this.

**Comment by btford** [comment]
This should work now.

**Comment by btford** [comment]
Changing your plunker to use Alpha 47 confirms that this is fixed. Please let me know if you see otherwise. Thanks!
