### ISSUE TITLE
angular signal untracked docs 

### ISSUE THREAD

**Issue by rrkkee015** [angular/angular#50725]
### Describe the problem that you experienced

I read untracked method can prevent a signal read. As a result, reading without tracking dependencies.

[But, I tested it as provided in. the official Angular document, but the dependency did not break](https://stackblitz.com/edit/stackblitz-starters-ncd8mx?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fmain.ts&title=Angular%20Starter)

I think it's because of the position of the variable declaration, but when the variable declaration was made inside the callback function, the dependency could be broken.

So, I think the official document is strange, so I leave it as an issue.

As-is
<img width="1459" alt="스크린샷 2023-06-15 오전 10 23 23" src="https://github.com/angular/angular/assets/135947668/816f17dd-cb84-4758-96a6-430aabfe549d">

To-be
<img width="1552" alt="스크린샷 2023-06-15 오전 10 23 06" src="https://github.com/angular/angular/assets/135947668/c2aaaa2b-aa7f-4d17-874e-01cb7c09bc0e">

### Enter the URL of the topic with the problem

https://angular.io/guide/signals#reading-without-tracking-dependencies

**Comment by pkozlowski-opensource** [comment]
> I read untracked method can prevent a signal read. As a result, reading without tracking dependencies.

This is correct.

> I think it's because of the position of the variable declaration, but when the variable declaration was made inside the callback function, the dependency could be broken.

What matters is a _signal read_. In your particular case the `this.currentUser()` read happens _outside_ of `untracked` so effect _does_ depend on the `currentUser()` value. This works as expected.

> So, I think the official document is strange

Assuming that we are talking about https://angular.io/guide/signals#reading-without-tracking-dependencies - which part was reading strange? Would you have any improvement suggestions?

**Comment by pkozlowski-opensource** [comment]
We haven't heard back from the additional info so I'm going to close this issue for now. Feel free to send a pull request with the suggested documentation changes if things are still not clear.

**Comment by simeyla** [comment]
Looks like the confusion arose by changing the original example:

```
effect(() => {
  const user = currentUser();
  untracked(() => {
    // If the `loggingService` reads signals, they won't be counted as
    // dependencies of this effect.
    this.loggingService.log(`User set to ${user}`);
  });
});
```

to this:

```
effect((onCleanup) => {
  const user = this.currentUser();
  untracked(() => {
    console.log(`${user}`);
  });
});
```

The key point in the docs is that whether or not `loggingService` reads any signals internally, we don't want them tracked and impacting our effect. Using `console.log` instead doesn't get the point across because clearly it doesn't use Angular signals.
