### ISSUE TITLE
Service Worker: Hash mismatch <continued>

### ISSUE THREAD

**Issue by bjornharvold** [angular/angular#50726]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

For the LONGEST time, cache busting used to work in our Angular apps. Then it stopped. As this wasn't mission critical for us and other tasks always got prioritized higher, we didn't look further into it... expecting it would just start working again.

But, we added some extra logging statements in our last release and we saw this coming from our SPA in production. (see error log).

The reason I put `continued` in the title is because legendary @manfredsteyer created a very similar ticket back in April of 2018 here: https://github.com/angular/angular/issues/23613 that is still open but with no real solution.

So I wanted to bump the original issue by creating a new ticket.

### Please provide a link to a minimal reproduction of the bug

https://extranet.wink.travel

### Please provide the exception or error you saw

```true
Failed to install app version '3e2dc9ce1e4ec739e6996b2e896c2ba78148966e': Hash mismatch (cacheBustedFetchFromNetwork): https://extranet.wink.travel/index.html: expected f8b30b4987a2a02191a787fe049f93828c293cc3, got 0b1a9ed0e9e6a1cc29e2117f6b1f20fda1204463 (after cache busting)
Error: Hash mismatch (cacheBustedFetchFromNetwork): https://extranet.wink.travel/index.html: expected f8b30b4987a2a02191a787fe049f93828c293cc3, got 0b1a9ed0e9e6a1cc29e2117f6b1f20fda1204463 (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (https://extranet.wink.travel/ngsw-worker.js:81:277)
    at async PrefetchAssetGroup.fetchFromNetwork (https://extranet.wink.travel/ngsw-worker.js:77:55)
    at async PrefetchAssetGroup.fetchAndCacheOnce (https://extranet.wink.travel/ngsw-worker.js:74:99)
    at async https://extranet.wink.travel/ngsw-worker.js:90:1
    at async https://extranet.wink.travel/ngsw-worker.js:88:309
    at async https://extranet.wink.travel/ngsw-worker.js:88:309
    at async https://extranet.wink.travel/ngsw-worker.js:88:309
    at async https://extranet.wink.travel/ngsw-worker.js:88:309
    at async PrefetchAssetGroup.initializeFully (https://extranet.wink.travel/ngsw-worker.js:88:264)
    at async https://extranet.wink.travel/ngsw-worker.js:139:93
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.0
Node: 18.16.0
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 16.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, router
... service-worker, youtube-player

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.0
@angular-devkit/build-angular   16.1.0
@angular-devkit/core            16.1.0
@angular-devkit/schematics      16.1.0
@schematics/angular             16.1.0
ng-packagr                      16.1.0
rxjs                            7.8.1
typescript                      5.1.3
```

### Anything else?

Team Angular is awesome 🦸🦸🏻‍♀️🦸‍♂️

**Comment by NicFindlay** [comment]
I've also been stuck with this issue and can't figure out a solution

**Comment by bjornharvold** [comment]
Build w Nx and push to Firebase. The artifacts Angular produces are never changed. Release script adds an updated version file in the same directory as environments. 

Which begs the rookie question: What is Angular's own hash strategy?

**Comment by bjornharvold** [comment]
Will give a go. Leaving the ticket open until Team Angular responds.

🙇🏼‍♂️

**Comment by Kartiky246** [comment]
@bjornharvold any update on the issue?

**Comment by bjornharvold** [comment]
Hi @Kartiky246 

This got fixed by disabling Cloudflare JS minimization features. Angular already creates minified bundles and if we let Cloudflare do it a 2nd time, there would be hash mismatches.

Hope this helps.
