### ISSUE TITLE
query params subscription fires twice continously for a single query param change 

### ISSUE THREAD

**Issue by shaikhshehzad** [angular/angular#50731]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

query params subscription fires twice for a single query param change resulting in unnecessary api calls and unwanted execution of code

### Please provide a link to a minimal reproduction of the bug

Saw this behavior while debugging

### Please provide the exception or error you saw

```true
NONE seen
```

### Anything else?

On load things works fine after adding  or removing params issue is replicable 

---

constructor(
    private route: ActivatedRoute,  
    private router: Router,
) { 

this.route.paramMap.subscribe((params) => {
   
          this.fnGetQueryParams();
});

-----

  ngOnInit(): void {}

-----

fnGetQueryParams() {
    this.route.queryParams.subscribe((urlparams) => {
})

}

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
