### ISSUE TITLE
Modules processed by ngcc aren't working (v15)

### ISSUE THREAD

**Issue by DzmVasileusky** [angular/angular#50735]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

We are experiencing a very complicated and strange bug.

What is the problem:
Old non-ivy angular modules aren’t working without triggering errors. Angular renders just empty structural directives and doesn't emit any errors.
Problems were spotted with:
```
@ngui/map
ng2-file-upload
@ngx-gallery/core
```

Important notes:
1. It is working well in case scss loaders group is working slow and reproducable if it is working fast. Basically we uncovered it when reduced our scss loader build time by 50%.
2. It magically started to work after some random build, then was broken again. So it is 99% compilation related. It seems View Engine modules are compiled in a wrong way from time to time.
It may be angular/compiler, webpack, nx, ngcc related.

I've tried to create a minimal reproduction but it was working on a smaller app with exactly same architecture.
So this issue is looking like a race condition. It seems like scss loaders delayed other loaders but now it isn't doing it causing this issue.
Maybe something `ngcc --create-ivy-entry-points` related.

If there are any suggestions or similar issues have been seen it would be great. At least answer on a question: "how and why View Engine angular libraries may stop working silently on Angular 15?" will help a lot

### Please provide the exception or error you saw

```true
No exceptions
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.0
Node: 18.13.0
Package Manager: pnpm 8.5.1
OS: darwin x64

Angular: 15.2.7
... animations, cdk, common, compiler, compiler-cli, core
... elements, forms, google-maps, language-service, localize
... material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.0
@angular-devkit/build-angular   15.2.6
@angular-devkit/core            15.1.0
@angular-devkit/schematics      15.1.0
@angular/cli                    15.2.0
@nguniversal/builders           15.2.1
@nguniversal/express-engine     15.2.1
@schematics/angular             15.1.0
rxjs                            7.8.0
typescript                      4.9.5
webpack                         5.74.0
```

**Comment by JoostK** [comment]
I am afraid that without a reproduction or insight into your build pipeline we won't be able to assist here. Since ngcc is no longer present in Angular 16 and v15 is LTS we won't be able to make any changes to ngcc anymore.

**Comment by DzmVasileusky** [comment]
@JoostK 
I analysed good and bad builds and that's what I found out.
`ngui-map` component in a good build is looking like that (note that it has selector, inputs and outputs exported):
```
...
26634: (qt,X,a)=>{
    let rt = (()=>{
            class st {...}
            return st.\u0275fac = function(Mt) {
                return new (Mt || st)(t.Y36(S),t.Y36(t.SBq),t.Y36(T),t.Y36(L),t.Y36(F),t.Y36(u),t.Y36(t.R0b))
            }
                ,
                st.\u0275cmp = t.Xpm({
                    type: st,
                    selectors: [["ngui-map"]],
                    inputs: {
                        ...
                    },
                    outputs: {
                        ...
                    },
                    features: [t._Bn([F, S, L, T]), t.TTD],
                    ngContentSelectors: O,
                    decls: 2,
                    vars: 0,
                    consts: [[1, "google-map"]],
                    template: function(Mt, ee) {
                        1 & Mt && (t.F$t(),
                            t._UZ(0, "div", 0),
                            t.Hsn(1))
                    },
                    styles: ["\n    ngui-map {display: block; height: 300px;}\n    .google-map {width: 100%; height: 100%}\n  "],
                    encapsulation: 2
                }),
                st
        }
    )();
}
...
```

same component in the bad build (btw bad build is 2/3 lesser and some classes are just missing from it):
```
66757: (qt,tt,a)=>{
    "use strict";
    a.d(tt, {
        ...
        uP: ()=>U
    });
    class U {...} // same class as in the example above, the whole module doesn't have `ngui-map` string mentioned as well as the whole main.js
}
```

Maybe someone who have developed ngcc can take a look, because it is looking like ngcc skipped that module and it was compiled in a wrong way.

**Comment by DzmVasileusky** [comment]
@JoostK 
Your insights are actually very helpful. Understanding of core principles of ngcc is helping me in finding an issue.
I did a clean `pnpm i` with and without `ngcc --create-ivy-entry-points` and found out that results of legacy package are equal. So ngcc hasn't added anything to node_modules for me. 
How does ngcc knows which module to process and which not?

**Comment by JoostK** [comment]
That sounds plausable; ngcc has to have completed before subsequent build steps can be started.

**Comment by DzmVasileusky** [comment]
Solved:
it came out that pnpm and ngcc aren't playing well toghether.
I had to add `node-linker=hoisted` to `.npmrc` to make pnpm to preserve npm like node modules structure which made possible finding modules by ngcc.
`--loglevel=debug` was a real help.

@JoostK thank you for helping with an issue
