### ISSUE TITLE
NG0908 error observed

### ISSUE THREAD

**Issue by stanchev89** [angular/angular#50742]
### Which @angular/* package(s) are the source of the bug?

zone.js, Don't known / other

### Is this a regression?

Yes

### Description

Hey everyone! About a month and a half ago, we included monitoring events in the Angular bootstrap failure events to gain a clearer understanding of all the cases where the app is broken. 
We’re already aware of the typical errors for unsupported (old) browsers like “ut.flat is not a function,” and they’re not a major concern. 
However, in the past 3-4 weeks, we’ve been noticing errors named **NG0908**, and their count has reached around 850 per week.

I’ve been trying to gather more information about this particular error, but there isn’t much available. It’s not documented in the official Angular error list https://angular.io/errors. The only source I found mentioning this error is https://stackoverflow.com/questions/75485862/error-conflict-multiple-chunks-emit-assets-to-the-same-filename-app-js-chunks.

Could you provide assistance in identifying the source of the issue and suggesting appropriate actions to resolve it?

### Please provide the exception or error you saw

```true
Error: NG0908
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular-devkit/architect       0.1502.2
@angular-devkit/build-angular   15.2.2
@angular-devkit/core            15.2.2
@angular-devkit/schematics      15.2.2
@angular/cdk                    15.2.9
@angular/material               15.2.9
@schematics/angular             15.2.2
rxjs                            7.5.7
typescript                      4.9.5


Node: 16.19.1
```

**Comment by leo6104** [comment]
In my case, i got the same error in production and its call stack trace is related with `hydrate` function.

https://github.com/angular/angular/blob/254023a03c3aaa26e2d01c02f9b9933b82fd971e/packages/core/src/di/r3_injector.ts#L387 

<img width="1150" alt="image" src="https://github.com/angular/angular/assets/7777929/4f3db85d-da3a-4361-8661-14a6c4586598">
 
the class implementation we inject through `useFactory` was here. 
```
export class SentryErrorHandler extends ErrorHandler {
  constructor(
    private viewerCountry: ViewerCountryService,
    private translate: TranslateService
  ) {
    super();
  }

    handleError(err: any): void {
       ...
   }
```

```
  {
    provide: ErrorHandler,
    useFactory: (viewerCountry: ViewerCountryService, translate: TranslateService) => {
      return new SentryErrorHandler(viewerCountry, translate);
    },
    deps: [ ViewerCountryService, TranslateService ],
  },
```

 In ViewerCountryService class & TranslateService class, we use `inject` function to get DI classes.

**Comment by jstnjs** [comment]
We also had this issue. Turns out we loaded `main.js` in before `runtime.js` and `polyfills.js`.

**Comment by K5TRL** [comment]
> We also had this issue. Turns out we loaded `main.js` in before `runtime.js` and `polyfills.js`.

I'm pretty new to Angular, could you tell me how you can make sure to run the runtime.js and polyfills.js before the main.js is loaded?

**Comment by jstnjs** [comment]
By changing the order of the scripts in the html.

**Comment by JeanMeche** [comment]
Without a repro this isn't actionable so I'll close this.

Feel free to reopen if you are able to provide a repro 👍
