### ISSUE TITLE
@Input with signals

### ISSUE THREAD

**Issue by rosostolato** [angular/angular#50746]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Sorry for opening another issue to talk about Input and signals but I had to ask about this. I saw discussions about `@Input` and `Signal` in https://github.com/angular/angular/issues/50190 and https://github.com/angular/angular/discussions/49682#:~:text=request%20for%20Angular.-,Signal%2Dbased%20inputs,-In%20signal%2Dbased but they only said about creating a new different decorator for signal inputs or create a totally different component with signal inputs which I think it's not necessary, we can just use what Angular already have and just add an extra option.

### Proposed solution

My proposal is to add one extra prop to the `@Input()` decorator options called `signal` which will tell Angular to not reassign the input but use the current signal reference to `set` the new value. See this rewrite of the RFC proposal:

```ts
@Component({
  standalone: true,
  selector: 'user-profile',
  template: `
    <p>Name: {{ firstName() }} {{ lastName() }}</p>
    <p>Account suspended: {{ suspended() }}</p>
  `,
})
export class UserProfile {
  // Create an optional input without an initial value.
  @Input({ signal: true })
  firstName = signal<string | undefined>(undefined); // Signal<string | undefined>

  // Create an input with a default value
  @Input({ signal: true })
  lastName = signal('Smith'); // Signal<string>

  // Create an input with options.
  @Input({ signal: true, alias: 'disabled' })
  suspended = signal(false); // Signal<boolean>
}
```

### Alternatives considered

The proposed solution would work just like if you had used getter and setter to set a private `Signal` value.

```ts
@Input()
get name(): string {
  return this._name();
}
set name(value: string) {
  this._name.set(value);
}
private _name = signal('');
```

Please, I ask to consider this, I've been waiting for reactive inputs so long, we already have the tools in our hands to make it possible 🙏

**Comment by nartc** [comment]
@rosostolato have you looked at this article? https://itnext.io/how-to-enjoy-signal-based-input-right-now-56efecaeee98

**Comment by rosostolato** [comment]
Thanks, @nartc! That's pretty! If Angular could built that functionality in with the proposed solution above, it would be even better!

**Comment by alxhub** [comment]
The `signal: true` flag for `@Input()` isn't needed - all inputs of a signal component will be signal-based, so having an individual flag per input is superfluous. Secondly, inputs are _not_ plain writable signals (the kind created with `signal()`) - signal inputs are their own thing and created using an `input()` function (or `inputSignal()` or whatever naming you prefer for the example).

So the example would become:

```typescript
@Input() firstName = input<string | undefined>(undefined); // Signal<string | undefined>
```

And the consensus during the RFC discussion is that the `@Input()` is redundant - using `input()` is enough for the compiler to recognize an input declaration.

**Comment by rosostolato** [comment]
Great! With that said, I'm closing this issue.
