### ISSUE TITLE
Migrate from constructor-based dependency injection to inject() function

### ISSUE THREAD

**Issue by MikaStark** [angular/angular#50757]
### Which @angular/* package(s) are relevant/related to the feature request?

upgrade

### Description

Hi Angular team :)

First of all, thanks for the hard work and the wonderful new features (special mentions to signals and input-route binding).

Taking from what was said in the last [Building Games and Q/A](https://www.youtube.com/watch?v=ZR_r1H8-Y_E&t=3370s), I think it could be very great to add a schematics to migrate from constructor-based dependency injection to the new `inject()` function.

Angular team already did something similar in v16 for Standalone APIs and I personally really appreciated what was done.  

### Proposed solution

Add some clarification on the official documentation to expose advantages of `inject()` function usage

### Alternatives considered

Add a schematics to simplify migration from constructor-based injection.

**Comment by ampmonteiro** [comment]
And add a section in the docs why inject function instead of constructor.
thanks.

**Comment by spock123** [comment]
Sounds like a good idea.
I have to say that personally I think the inject() function is so awesome, it really has changed the developer experience to a degree I had not foreseen. 
Sorry for hijacking your issue :)

**Comment by freshgum-bubbles** [comment]
Related to https://github.com/angular/angular/issues/50439

**Comment by rdlabo** [comment]
I created eslint rule of https://www.npmjs.com/package/@rdlabo/eslint-plugin-rules .
This can run auto fixt of fix cunstructor-di to inject-di. Please try!

**Comment by freshgum-bubbles** [comment]
FWIW My issues with this proposal [were well-detailed in my original comment](https://github.com/angular/angular/issues/50439#issuecomment-1586235041).  It may be easier to use, but it obscures the dependencies of classes, and causes a few other (potentially hard-to-debug) issues at runtime.

**Comment by ShawnTalbert** [comment]
Where is the original discussion about moving away from constructor injection towards `inject()`?

**Comment by bjornharvold** [comment]
We have a Angular huge codebase and totally agree that having a migration schematic for this would be uber-cool. inject() makes the code look SOO much cleaner.

**Comment by XavierDupessey** [comment]
Hello,

Since class-based Guards and Resolvers are _deprecated_, we are encouraged to use the `inject()` function for functional-based ones. Therefore, for consistency, I would prefer to use it everywhere (in Components, Directives, Services...) but the lack of automated migration tool make it impossible (given the size of our code-base).

I guess that Google, internally, still use constructors otherwise they would have make the _migration schematic_ public?
So, should we continue with DI constructors everywhere we can? After all, the inejct() function is only described as "another option" in the official documentation cf https://angular.io/guide/dependency-injection#injecting-a-dependency

I would love to have an official answer from Google about this practice :)

**Comment by vmasek** [comment]
I created an Nx generator for migration, there are quite some complex use-cases handled (see the test files).
Even if there is a problem it is usually easy to spot/fix. It's ideal to run it to get 99% done and then fix the rest manually 😄 .

https://github.com/vmasek/nx-toolkit/tree/main/packages/inject-migration

**Comment by theer1k** [comment]
> I created an Nx generator for migration, there are quite some complex use-cases handled (see the test files). Even if there is a problem, it is usually easy to spot/fix. It's ideal to run it to get 99% done and then fix the rest manually 😄 .
> 
> https://github.com/vmasek/nx-toolkit/tree/main/packages/inject-migration

[vmasek](https://github.com/vmasek) YOU ARE THE G.O.A.T!

**Comment by JeanMeche** [comment]
This migration has been shipped in 18.2 ! 

https://angular.dev/reference/migrations/inject-function

**Comment by JeanMeche** [comment]
#60809 will update the style guide with the new recommendation with `inject` for DI.
