### ISSUE TITLE
Hydration is not being applied in my angular project

### ISSUE THREAD

**Issue by hebaibrahim76** [angular/angular#50765]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

No

### Description

I created a new ssr angular project that uses angular version 16, here is the repo to my project https://github.com/hebaibrahim76/my-angular-ssr-project

I added provideClientHydration() in my providers in app.module.ts,  but no console related to hydration showed up

Any ideas on why hydration is not working?

**Comment by hebaibrahim76** [comment]
@JeanMeche i am launching my ssr project by running npm run serve:ssr

**Comment by JeanMeche** [comment]
I started your project, it works as expected.

**Comment by hebaibrahim76** [comment]
@JeanMeche The angular docs say that to confirm hydration is enabled, you should see a message that includes hydration-related stats in the console of the dev tools in your browser, but when I ran my application, I did not see any hydration related message in the console

**Comment by JeanMeche** [comment]
By expected I mean, I saw hydration logs in the console.

**Comment by AndrewKushnir** [comment]
@hebaibrahim76 could you please try running the project using `npm run dev:ssr`? There is a chance that you are running a production build, which is optimized and all dev-mode logs are tree-shaken away.

**Comment by AndrewKushnir** [comment]
Closing this ticket for now, please reopen if the problem still exists.
