### ISSUE TITLE
DynamicComponentLoader: moveNodesAfterSibling causing rendering issues

### ISSUE THREAD

**Issue by mlynch** [angular/angular#5077]
Currently, `DynamicComponentLoader` calls `DomRenderer.attachFragmentAfterElement` in the corresponding `AppViewManager`, which then calls `moveNodesAfterSibling` when creating and adding a new component next to an existing component.

AppViewManager: https://github.com/angular/angular/blob/c02f2bdab07904c36bde8bdfa89ef3dd405274b3/modules/angular2/src/core/linker/view_manager.ts#L333
DomRenderer: https://github.com/angular/angular/blob/c02f2bdab07904c36bde8bdfa89ef3dd405274b3/modules/angular2/src/core/render/dom/dom_renderer.ts#L179

The issue is that `moveNodesAfterSibling` first inserts the new element *before* the target element, and then shuffles it around to be *after* the target element. That seems unnecessary when we *know* the new element is going to come after a target element, and it causes some subtle issues in the browser.

For example, in Ionic, when you *push* a new component into a navigation stack the first component's `scrollTop` is reset. You can see a vanilla HTML/JS example of `insertBefore` causing `scrollTop` to reset here (scroll down in the red area before the 3 second timeout fires): http://plnkr.co/edit/zpexZC8OoxNVLEhoVAKW?p=preview

We can work around it by saving and restoring the `scrollTop` but I also worry about potential flickers and other issues with this method.

It seems like a solution would be to allow for an explicit `insertAfter` using `element.parentNode.insertBefore(nodes[0], element.nextSibling)` to avoid the element detach/reattach and the subsequent issues.

**Comment by mlynch** [comment]
I was able to patch angular to fix the issue. I created a new `moveNodesAfterSibling` that uses `insertAfter`. Going to try putting this into ng proper and running the suite, but for starters here's my code (es5 transpiled):

```javascript
  function moveNodesAfterSibling2(sibling, nodes) {
    var cs = sibling;
    if (nodes.length > 0 && lang_1.isPresent(dom_adapter_1.DOM.parentElement(sibling))) {
      for (var i = 0; i < nodes.length; i++) {
        //dom_adapter_1.DOM.insertBefore(sibling, nodes[i]);
        dom_adapter_1.DOM.insertAfter(cs, nodes[i]);
        cs = nodes[i];
      }
      //dom_adapter_1.DOM.insertBefore(nodes[0], sibling);
    }
  }
```

**Comment by tbosch** [comment]
+1, we should do this

**Comment by tbosch** [comment]
(but maybe without DOM.insertAfter but use the DOM methods insertBefore/appendChild directly)

**Comment by IgorMinar** [comment]
@tbosch can you estimate the effort for this issue and determine if it would require a breaking change and how important is it to get it done before beta.

**Comment by IgorMinar** [comment]
@tbosch can we get this fixed before beta?

**Comment by IgorMinar** [comment]
i'm going to put this on beta.0 list but it might slip until beta.1

**Comment by bradlygreen** [comment]
@mlynch can you guys send a PR for this?

**Comment by mlynch** [comment]
Ah yea, should be incoming this week!

**Comment by mlynch** [comment]
@bradlygreen PR submitted. Wasn't quite sure how you wanted that one @tbosch so I went with the vanilla `insertBefore` DOM call
