### ISSUE TITLE
hgroup is a valid HTML5 element

### ISSUE THREAD

**Issue by martinmcwhorter** [angular/angular#50782]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

In the [original bug report](https://github.com/angular/angular/issues/38831) the rational for not supporting hgroup is that it has been removed from the W3C's definition of HTML5. The problem with that rational is that the WHATWG defines the HTML5 standard, not the W3C. 

In the WHATWG definition, [hgroup](https://html.spec.whatwg.org/dev/sections.html#the-hgroup-element) is a valid HTML5 element. 

As well as being part of the WHATWG official HTML5 standard, it is a living standard as can be seen in the MDN documentation as well as can-i-use browser support: 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup
https://caniuse.com/?search=hgroup

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-vwcpfd?file=src/app/app.component.html

### Please provide the exception or error you saw

```true
'hgroup' is not a known element:
1. If 'hgroup' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
```

**Comment by JoostK** [comment]
It was added in https://github.com/angular/angular/pull/47552
