### ISSUE TITLE
Router - A div wraps the template's content

### ISSUE THREAD

**Issue by vguede** [angular/angular#5078]
Angular 1 Component Router adds a ```<div>``` who wraps the template's content :
```html
<ng-outlet>
    <div component-name="" ng-scope>
        <!--- template content -->
    </div>
</ng-outlet>
```

But this behaviour breaks some CSS rules, for example with angular material.

Why this div is added ? If it is mandatory, how add attributes (who will compiled after) to this div from the template ?

**Comment by vicb** [comment]
This version of the router is deprecated
