### ISSUE TITLE
`REMOVE_STYLES_ON_COMPONENT_DESTROY` breaks :leave animations

### ISSUE THREAD

**Issue by waterplea** [angular/angular#50791]
### Which @angular/* package(s) are the source of the bug?

animations, platform-browser

### Is this a regression?

No

### Description

If you enable `REMOVE_STYLES_ON_COMPONENT_DESTROY`, it does not wait for `:leave` animations to finish, causing components to lose styles before they are gone from DOM.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-ktwdzy

Toggle a simple component with fade animation on/off using `*ngComponentOutlet` on the reproduction link, background disappears before component is gone.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 16.1.1
```

**Comment by alan-agius4** [comment]
This will be addressed by https://github.com/angular/angular/pull/50677

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular/pull/50677.
