### ISSUE TITLE
Router tutorial tour of heroes - doc bug fix suggestion

### ISSUE THREAD

**Issue by zjian107-su** [angular/angular#50794]
### Describe the problem that you experienced

I am new to open source contribution and it is my first issue ticket. I am following the "Router tutorial: tour of heroes". It requires some previous knowledge of the "Tour of Heroes application and tutorial", but I have some suggestions for improvements to the documentation. These enhancements will help beginners follow the tutorial more smoothly so they don't get stuck debugging. 

## First: Inconsistency in the component metadata
**Location**: After “Change the selector to app-hero-list.” in the page

**Suggested change**: Change the `templateUrl` to _./hero-list.component.html_, and Change the `styleUrls` to _./hero-list.component.css_

**Screenshot**
![Inconsistency in the component metadata](https://github.com/angular/angular/assets/35544956/94f09ae5-5041-4e72-b7c9-6745a5e9d31a)

## Second: Import path update
**Location**: After "• Update the relative path import to the message.service in the hero.service.ts file" in the page

**Suggested change**: Update the relative path import to the `message.service` in the "hero-list.component.ts" file. Instead of “../message.service”, it should be “../../message.service”, because now the message.service is under /app folder.

**Screenshot**
![Import path update](https://github.com/angular/angular/assets/35544956/f7aa3034-a6ae-483f-94e8-72fe5e83f0bd)

**Comment by deverten** [comment]
I would be glad to pick this up if a PR hasn't been created yet.

**Comment by vijhhh2** [comment]
I would like to pick this up.

**Comment by JeanMeche** [comment]
@deverten Feel free to open a PR !

**Comment by deverten** [comment]
Sending in a PR. Thank you

**Comment by deverten** [comment]
@zjian107-su can you please add the link to the doc page.

**Comment by zjian107-su** [comment]
@deverten yeah of course. Here is the doc page: https://angular.io/guide/router-tutorial-toh
By searching "Change the selector to app-hero-list.", you can find the first issue
By searching "Update the relative path import to the message.service in the hero.service.ts file", you can find the second issue.

**Comment by deverten** [comment]
Thank you @zjian107-su now I see the issues. As regards the second issue, there is no need importing the `message.service.ts` in the `hero-list` component because it is not directly invoked (we invoke the `Heroservice` instead). The `hero.service.ts` takes care of the import and implementation of the message service.

**Comment by zjian107-su** [comment]
Thank you for your feedback and improvement suggestion.

While there is indeed no direct invocation of `message.service.ts`, it is indirectly utilized through the call to `HeroListComponent.onSelect()` (on line 29), which wraps `this.messageService.add('HeroesComponent: Selected hero id=${hero.id}')`. As such, I believe retaining the import of messageService is necessary for the functionality of the application.

If your suggestion is to replace the function on line 29 with `this.heroService` instead, I see a potential complication. As of this point in the tutorial, `heroService` only has the `getHeros()` method. We would need to update `heroService` to include additional functionality to handle the message service.

The screenshot is attached below:
![Screenshot 2023-06-25 at 11 27 41 AM](https://github.com/angular/angular/assets/35544956/4e0120f7-4838-43d5-b8de-dda1de5548e5)

**Comment by bencodezen** [comment]
At this time, the team is focused on updating and maintaining the new [Angular tutorials](https://angular.dev/tutorials) and will deprecate the Tour of Heroes tutorial. 

Since there hasn't been much activity since July, I'll be closing this issue for now; so we welcome checking out the new tutorials and file a new issue to provide feedback on how we can improve it!
