### ISSUE TITLE
Trigger control validators without valueChange event

### ISSUE THREAD

**Issue by Bogs-123** [angular/angular#50793]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

We miss the ability to trigger validators without triggering ValueChange event.

The only way to trigger the validators is to call **updateValueAndValidity** on form or control. But this also triggers the ValueChange event. Setting **emitEvent** to false, will not trigger the validators.

### Proposed solution

Have a function to trigger validators on form and/or control.

### Alternatives considered

Make a difference between emitEvent**s**, emitValueChangeEvent and emitStatusChangeEvent.

**Comment by pkozlowski-opensource** [comment]
> We miss the ability to trigger validators without triggering ValueChange event.

Would you mind sharing a real-life usage scenario based on your use-cases? We want to limit the API surface and only add new facilities when needed. Maybe we can suggest an alternative approach based on your needs?

**Comment by Bogs-123** [comment]
We have a dynamic form. We get the settings for this form from our backend.
In these settings a configurator can add tiny code snippets that will be executed on specific events. In this example valueChange.
The configurator can also add code snippets that are used as validator.
In our frontend, we don't know what values are used in the validator, so we want to run all validators on the form. But we don't want to trigger all the valueChange events, because most values aren't changed.

Example:
The configurator sends two controls: **username** and **name**. 
In the value change, both controls do some kind of api call. 
**name** has an extra validator. The username can not be the same as the name.

```JSON
{
  "controls": [
    {
      "controlName": "username",
      "valueChange": "() => {makeApiCall()}"
    },
    {
      "controlName": "name",
      "valueChange": "() => {anotherApiCall()}",
      "validator": "(formValue) => {return formValue['username'] !== formValue['name']}"
    }
  ]
}
```

In our frontend code, we need to trigger the validator for **name** when **username** changes. But we don't want to execute the valueChange event of **name** because that value is not changed.

**Comment by JeanMeche** [comment]
I'm going to close this issue with a lack of reproduction. 

`updateValueAndValidity` does run validators wether `emitEvent ` is `false` or `true`. The only things that prevents from running the validators is the control being disabled.

If anyone reading this issue has something similar and can provide a repro, feel free to file a new issue and we'll have a look. Thank you for your understanding.

**Comment by Bogs-123** [comment]
Thank you for the response.
Sorry I didn't add a repo. Didn't know it was needed.

To clarify what we try to achieve:
We only want to trigger the validator, but not the valueChange event.

I created a [Stackblitz as repo](https://stackblitz.com/edit/stackblitz-starters-tbjfrk?file=src%2Fform%2Fform.component.ts).

It includes a simple form where UserName and Name can't be the same.
Every time UserNames value changes, it does an api call.
When the value of Name changes, we want to trigger validator of UserName. But we can't do that without triggering valuChange aswell.

**Comment by JeanMeche** [comment]
Passing `emitEvent: false` does exactly that. 

```
    this.myForm.controls['name'].valueChanges.subscribe(() => {
      this.myForm.controls['userName'].updateValueAndValidity({emitEvent: false);
    });
```

**Comment by Bogs-123** [comment]
Well, I feel stupid.

Sorry for wasting your time
