### ISSUE TITLE
$http: XSRF per RFC 6648: SHOULD NOT prefix their parameter names with "X-"

### ISSUE THREAD

**Issue by arty-name** [angular/angular#508]
[Angular has built-in support for sending XSRF token back in a header](https://docs.angularjs.org/api/ng/service/$http). It uses header `X-XSRF-TOKEN`. [RFC 6648 recommends against using `X-` prefix for non-standard HTTP headers](http://www.ietf.org/rfc/rfc6648.txt). Would be nice of angular to switch to header `XSRF-Token`, recommend its use in the documentation and link to RFC 6648.

This is a copy of angular/angular.js#10903 in case it doesn't make it in 1.x

**Comment by mhevery** [comment]
Data is not part of the core angular. Will be a separate project. Closing
