### ISSUE TITLE
result of resolve function is not passed into the activatedRoute.data stream

### ISSUE THREAD

**Issue by slaesh** [angular/angular#50809]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

my resolved data is not passed into the data-stream.

I have several "strange" observations.

1. the activatedRoute has no `component` set in the first place.
2. afrer the resolved is being resolved, I can find the resolved data within the childs activatedRoute of my current one oO
3. and the `component` property is present too

![image](https://github.com/angular/angular/assets/55546823/1b8a0155-ee36-41b8-b2ad-10296a880f7b)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-npj2rg?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 16.0.1
```

**Comment by JoostK** [comment]
You are using your routed component also as a bootstrap component; the bootstrap component will initialize before the router has resolved the route, hence you're seeing inconsistent behavior. Routed components should not be bootstrapped.
