### ISSUE TITLE
Angular hydration (SSR) for components that use i18n blocks is skipped

### ISSUE THREAD

**Issue by karimzg** [angular/angular#50812]
### Which @angular/* package(s) are the source of the bug?

localize

### Is this a regression?

No

### Description

The benefits of hydration are completely ignored for i18n sites. Most of the content is skipped by hydration and re-rendered

### Please provide the exception or error you saw

```true
Each component with :
`` i18n="@@translationKey" `` 
is ignored by hydratation
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular/cli: "^16.1.0"
@angular/core: "^16.1.1"
Node: v18.13.0
```

**Comment by AndrewKushnir** [comment]
@karimzg thanks for creating a ticket. Currently, components with i18n blocks are skipped by hydration, we've documented it in the [hydration guide](https://angular.io/guide/hydration#i18n). We plan to improve hydration to support components with i18n, but there is no exact ETA yet. I'll keep this ticket open for now and we can use it to collect the signal from the community and share updates from the Angular side.

**Comment by zip-fa** [comment]
We hardly depend in i18n from angular/core, so waiting for hydration to be supported with i18n too

**Comment by mathieu-morchipont** [comment]
me too

**Comment by SebastianKohler** [comment]
Looking very much forward to hydration support for i18n blocks. I was hoping this would have been included in v17 ...

**Comment by pschuler21** [comment]
This would give our SSR SPA a huge boost, would appreciate if this was resolved as soon as possible.

**Comment by psomby** [comment]
Very disappointing that this is not working currently. Would like to see at least an ETA here so we can determine if it is worth making our own solution.

**Comment by AndrewKushnir** [comment]
Adding hydration support for i18n blocks is very high on our list and we'll start looking into this soon. We don't have any ETAs, but we'll keep this thread updated and share more info once we complete an initial research phase.

**Comment by zip-fa** [comment]
> Adding hydration support for i18n blocks is very high on our list and we'll start looking into this soon. We don't have any ETAs, but we'll keep this thread updated and share more info once we complete an initial research phase.

Yes please, give us some ETA! Will wait for your response. We were thinking on switch to ngx translate, but built-in i18n is more elegant in some ways. Please add more support of it

**Comment by atroy** [comment]
Our users, who come from diverse linguistic backgrounds, depend on internationalization (i18n). Its absence is impacting their experience negatively. We hope for a solution the sooner the better!

**Comment by henry-alakazhang** [comment]
I'm kind of curious, actually - what about i18n blocks _doesn't_ work with hydration? My understanding of the default compile-time localization setup is that it builds separate assets for both the browser and server, where each locale is functionally the same as another with different text.

I actually tried patching `@angular/core` to remove the `hasI18n()` check in `hydration/annotate.ts`, and server-side rendering + hydration + i18n still woked fine for my application. Are there specific edge cases that have issues and require it to be disabled?

**Comment by jessicajaniuk** [comment]
@henry-alakazhang i18n adds extra information that complicate the hydration process. We originally did have an error in the case of i18n being detected, but we updated it to check if i18n exists and automatically switch to `ngSkipHydration` for i18n blocks. So you won't see an error, but any nodes that have i18n information are automatically opted out of hydration. There's an ongoing investigation to add real hydration support for i18n. So, feel free to keep watching this bug for updates.

**Comment by muchbetterug** [comment]
+1, please make this happen <3

**Comment by eneajaho** [comment]
Support is coming https://github.com/angular/angular/pull/54823

**Comment by davidroth** [comment]
What is the status of this issue now that #54823 has been merged? Why is it still in backlog?

**Comment by thePunderWoman** [comment]
@davidroth Work is still in progress. That PR was merged to be included in the next major. We'll mark this as fixed when the time is right.

**Comment by devknoll** [comment]
Thank you for your patience, everyone. Now that #55130 has landed, you can enable the developer preview for i18n hydration support in the latest pre-release (v18.0.0-next.4) by using:

```tsx
import {
  bootstrapApplication,
  provideClientHydration,
  withI18nSupport,
} from '@angular/platform-browser';
...
bootstrapApplication(AppComponent, {
  providers: [provideClientHydration(withI18nSupport())]
});
```

Please give it a try and let us know how it goes!

**Comment by AndrewKushnir** [comment]
Closing this ticket as completed. If you come across any issues while testing hydration for i18n blocks, please feel free to create a new ticket. Thank you.
