### ISSUE TITLE
ViewContainerRef populates the component twice on the browser but renders once on view source

### ISSUE THREAD

**Issue by CarlosTorrecillas** [angular/angular#50813]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] builders
- [X] common
- [ ] express-engine

### Is this a regression?

Yes

### Description

When I define an `ng-template` to be handled by a `ViewContainerRef `so that the component tag is not rendered, the view source displays one instance of the content whereas the actual browser shows two instances of it.

## 🔬 Minimal Reproduction

1.- Clone the repo: https://github.com/CarlosTorrecillas/universal-issue
2.- Run `npm i `and `npm run dev:ssr`
3.- Navigate to the URL: `http://localhost:4200/lazy-loaded`
4.- You will see the text: `This should only be rendered once!` twice however if you right clic on the page and go to view source you will only see that once.

## 🔥 Exception or Error

None

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 16.1.0
Node: 18.10.0
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 16.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.0
@angular-devkit/build-angular   16.1.0
@angular-devkit/core            16.1.0
@angular-devkit/schematics      16.1.0
@angular/cli                    16.1.0
@nguniversal/builders           16.1.0
@nguniversal/express-engine     16.1.0
@schematics/angular             16.1.0
rxjs                            7.8.1
typescript                      4.9.5

</code></pre>

**Comment by AndrewKushnir** [comment]
@CarlosTorrecillas could you please create a [Stackblitz](https://stackblitz.com/) example (with minimal amount of code/components) with `<ul>` and `<li>` elements that would understand the question better?

**Comment by CarlosTorrecillas** [comment]
Hi @AndrewKushnir , I have just created the following Stackblitz: https://stackblitz-starters-bmd5kj.stackblitz.io where you can see what I mean. Essentially my requirement is that when you have components that depend logically upon other tags, there has to be the ability to suppress the host tags in order to form correct HTML.

If you take a look at the screenshot taken from the Stackblitz you will see that inside the actual <ul> you would ony expect <li> elements but you have the child element's host tag if that makes sense. With that structure you don't create right lists because there are elements that shouldn't be there. Does that make sense?

![image](https://github.com/angular/angular/assets/648793/258ead5e-5f41-45e4-8aba-5c4a49764ba8)

With the original code in version 15 I was able to remove the host tag and the elements were formed correctly. Now I have the problem where I cannot get them to work.

**Comment by CarlosTorrecillas** [comment]
Hi @AndrewKushnir , do you guys know whether this is something that is going to be prioritized at any point soon or do you happen to have a workaround to have the same behavior?

Thanks!

**Comment by AndrewKushnir** [comment]
@CarlosTorrecillas thanks for the repro.

This behavior is expected, since Angular uses host elements for components. As a result, those extra `<app-my-list-partN>` nodes are preserved in the DOM and are important for hydration. As a possible solution, you can either refactor the code to generate all `<li>` elements in a single component (so that there are no extra nodes under `<ul>`) or opt-out a component from hydration (using `ngSkipHydration` flag, [see additional info here](https://angular.io/guide/hydration#how-to-skip-hydration-for-particular-components)) and use direct DOM manipulation to move elements around.

I'm closing this ticket, since there are no changes required on the framework side.

Thank you.
