### ISSUE TITLE
Confusing logic in getting start example, canClick -> Disabled

### ISSUE THREAD

**Issue by mangelozzi** [angular/angular#50811]
### Describe the problem that you experienced

Learning Angular, so maybe my understanding is wrong.... but I would imagine if `canClick` is `false`, then the `disabled` attribute would be present, not vice a versa.

In this angular example: hello-world-bindings.component.ts: 
```ts
import { Component } from '@angular/core';
 
@Component ({
  selector: 'hello-world-bindings',
  templateUrl: './hello-world-bindings.component.html'
})
export class HelloWorldBindingsComponent {
  fontColor = 'blue';
  sayHelloId = 1;
  canClick = false;
  message = 'Hello, World';
 
  sayMessage() {
    alert(this.message);
  }
}
``` 

hello-world-bindings.component.html:
```ts
<button
  type="button"
  [disabled]="canClick"
  (click)="sayMessage()">
  Trigger alert message
</button>

<p
  [id]="sayHelloId"
  [style.color]="fontColor">
  You can set my color in the component!
</p>

<p>My color is {{ fontColor }}</p>
```

Is not the logic of `canClick = false;` and `[disabled]="canClick"` illogical? If canClick is true, then disabled will be present, which will disable element making it unclickable?

### Enter the URL of the topic with the problem

https://angular.io/guide/what-is-angular

### Describe what you were looking for in the documentation

N/A

### Describe the actions that led you to experience the problem

Trying to understand the example

### Describe what you want to experience that would fix the problem

Reverse the boolean logic

**Comment by MaciejWWojcik** [comment]
I would be happy to pick this up 🙋‍♂️

**Comment by andreyjkee** [comment]
@MaciejWWojcik it's variable naming problem, no need to change logic there, just assing better variable name, e.g. `isButtonDisabled`.
