### ISSUE TITLE
Error in the Angular Tutorial: Tour of Heroes

### ISSUE THREAD

**Issue by Matias-87** [angular/angular#50821]
### Describe the problem that you experienced

It is a simple error that has been previously reported and marked as resolved, although it is still present in the documentation.

In the Dashboard component, in the getHeroes method, there is a problem. The method should display the first four elements of the heroes array, but when using the slice method, it is written as (1, 5) instead of (0, 4). This error is made more than once.

### Enter the URL of the topic with the problem

https://angular.io/tutorial/tour-of-heroes/toh-pt5

### Describe what you were looking for in the documentation

I was doing the Tour of Heroes tutorial, and upon completing it, I noticed this error. I returned to this section of the tutorial to verify if the error was mine or if it was in the documentation.

### Add a screenshot if that helps illustrate the problem

![Screenshot 2023-06-22 180910](https://github.com/angular/angular/assets/126021442/7852d52f-1574-47e4-9705-153c2a3575ee)
![Screenshot 2023-06-22 180925](https://github.com/angular/angular/assets/126021442/3aa83ccc-a2af-4519-ba3a-da647402b28c)

**Comment by sunilbaba** [comment]
Hi All,

If anyone is not looking into this issue already. I want to take up this one

**Comment by JeanMeche** [comment]
@Matias-87 Where do you see that it should return the first four ? 
There is a sentence that says : 
> This getHeroes() returns the sliced list of heroes at positions 1 and 5, returning only Heroes two, three, four, and five.

Which is what the code does.

**Comment by Matias-87** [comment]
> @Matias-87 Where do you see that it should return the first four ? There is a sentence that says :
> 
> > This getHeroes() returns the sliced list of heroes at positions 1 and 5, returning only Heroes two, three, four, and five.
> 
> Which is what the code does.

Yes that is true, but that sentence is also wrong because the code should returns the top heroes and it is skipping the first. The sliced should be (0, 3)

**Comment by JeanMeche** [comment]
Where do you get that it should return the top heroes ? I get that taking 2-5 is a bit abitrary but I see nothing against it.

**Comment by bencodezen** [comment]
Tour of Heroes will be deprecated in the near future.

For the latest Angular tutorials, please use [Angular](https://angular.dev/tutorials) going forward.
