### ISSUE TITLE
Angular 16 (16.04) not updated to the latest (16.1.2) with warning (npm) 

### ISSUE THREAD

**Issue by rsoftwareconcepts** [angular/angular#50836]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

No

### Description

Recent upgrades using ng update all went very well, we are @ 16.04 and want to upgrade to latest (16.1.1 / 16.1.2).
But we get the errors mentioned below, at the end of the update output we get:

npm ERR! notarget No matching version found for critters@0.0.19.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\currentuser\AppData\Local\npm-cache\_logs\2023-06-23T11_05_58_834Z-debug-0.log
Ã— Packages installation failed, see above.

By searching I found the package critter to be a dependency for @angular-devkit\build-angular ("critters": "0.0.16").

### Please provide the exception or error you saw

```true
C:\DEV\myproject>ng update @angular/cli @angular/core
The installed Angular CLI version is outdated.
Installing a temporary Angular CLI versioned 16.1.1 to perform the update.
âˆš Packages successfully installed.
Using package manager: npm
Collecting installed dependencies...
Found 64 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/architect @ "0.1601.1" (was "0.1600.5")...
    Updating package.json with dependency @angular-devkit/build-angular @ "16.1.1" (was "16.0.5")...
    Updating package.json with dependency @angular-devkit/core @ "16.1.1" (was "16.0.5")...
    Updating package.json with dependency @angular/cli @ "16.1.1" (was "16.0.5")...
    Updating package.json with dependency @angular/compiler @ "16.1.2" (was "16.0.4")...
    Updating package.json with dependency @angular/compiler-cli @ "16.1.2" (was "16.0.4")...
    Updating package.json with dependency @angular/core @ "16.1.2" (was "16.0.4")...
    Updating package.json with dependency @angular/language-service @ "16.1.2" (was "16.0.4")...
    Updating package.json with dependency @angular/common @ "16.1.2" (was "16.0.4")...
    Updating package.json with dependency @angular/forms @ "16.1.2" (was "16.0.4")...
    Updating package.json with dependency @angular/platform-browser @ "16.1.2" (was "16.0.4")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "16.1.2" (was "16.0.4")...
    Updating package.json with dependency @angular/router @ "16.1.2" (was "16.0.4")...
UPDATE package.json (3258 bytes)
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: myproject@0.0.1
npm WARN Found: @angular/common@16.0.4
npm WARN node_modules/@angular/common
npm WARN   @angular/common@"^16.1.2" from the root project
npm WARN   6 more (@angular/forms, @angular/platform-browser, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @angular/common@"16.0.4" from @angular/forms@16.0.4
npm WARN node_modules/@angular/forms
npm WARN   @angular/forms@"^16.1.2" from the root project
npm WARN   1 more (@ionic/angular)
npm WARN
npm WARN Conflicting peer dependency: @angular/core@16.1.2
npm WARN node_modules/@angular/core
npm WARN   peer @angular/core@"16.1.2" from @angular/common@16.1.2
npm WARN   node_modules/@angular/common
npm WARN     peer @angular/common@"16.0.4" from @angular/forms@16.0.4
npm WARN     node_modules/@angular/forms
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: myproject@0.0.1
npm WARN Found: @angular/common@16.0.4
npm WARN node_modules/@angular/common
npm WARN   @angular/common@"^16.1.2" from the root project
npm WARN   6 more (@angular/forms, @angular/platform-browser, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @angular/common@"16.0.4" from @angular/platform-browser@16.0.4
npm WARN node_modules/@angular/platform-browser
npm WARN   @angular/platform-browser@"^16.1.2" from the root project
npm WARN   3 more (@angular/forms, @angular/platform-browser-dynamic, @angular/router)
npm WARN
npm WARN Conflicting peer dependency: @angular/core@16.1.2
npm WARN node_modules/@angular/core
npm WARN   peer @angular/core@"16.1.2" from @angular/common@16.1.2
npm WARN   node_modules/@angular/common
npm WARN     peer @angular/common@"16.0.4" from @angular/forms@16.0.4
npm WARN     node_modules/@angular/forms
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: myproject@0.0.1
npm WARN Found: @angular/common@16.0.4
npm WARN node_modules/@angular/common
npm WARN   @angular/common@"^16.1.2" from the root project
npm WARN   6 more (@angular/forms, @angular/platform-browser, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @angular/common@"16.0.4" from @angular/router@16.0.4
npm WARN node_modules/@angular/router
npm WARN   @angular/router@"^16.1.2" from the root project
npm WARN   1 more (@ionic/angular)
npm WARN
npm WARN Conflicting peer dependency: @angular/core@16.1.2
npm WARN node_modules/@angular/core
npm WARN   peer @angular/core@"16.1.2" from @angular/common@16.1.2
npm WARN   node_modules/@angular/common
npm WARN     peer @angular/common@"16.0.4" from @angular/forms@16.0.4
npm WARN     node_modules/@angular/forms
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: myproject@0.0.1
npm WARN Found: @angular/core@16.0.4
npm WARN node_modules/@angular/core
npm WARN   peerOptional @angular/core@"16.1.2" from @angular/compiler@16.1.2
npm WARN   node_modules/@angular/compiler
npm WARN     dev @angular/compiler@"^16.1.2" from the root project
npm WARN     1 more (@angular/compiler-cli)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @angular/core@"16.0.4" from @angular/forms@16.0.4
npm WARN node_modules/@angular/forms
npm WARN   @angular/forms@"^16.1.2" from the root project
npm WARN   1 more (@ionic/angular)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: myproject@0.0.1
npm WARN Found: @angular/core@16.0.4
npm WARN node_modules/@angular/core
npm WARN   peerOptional @angular/core@"16.1.2" from @angular/compiler@16.1.2
npm WARN   node_modules/@angular/compiler
npm WARN     dev @angular/compiler@"^16.1.2" from the root project
npm WARN     1 more (@angular/compiler-cli)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @angular/core@"16.0.4" from @angular/platform-browser@16.0.4
npm WARN node_modules/@angular/platform-browser
npm WARN   @angular/platform-browser@"^16.1.2" from the root project
npm WARN   3 more (@angular/forms, @angular/platform-browser-dynamic, @angular/router)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: myproject@0.0.1
npm WARN Found: @angular/core@16.0.4
npm WARN node_modules/@angular/core
npm WARN   peerOptional @angular/core@"16.1.2" from @angular/compiler@16.1.2
npm WARN   node_modules/@angular/compiler
npm WARN     dev @angular/compiler@"^16.1.2" from the root project
npm WARN     1 more (@angular/compiler-cli)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @angular/core@"16.0.4" from @angular/router@16.0.4
npm WARN node_modules/@angular/router
npm WARN   @angular/router@"^16.1.2" from the root project
npm WARN   1 more (@ionic/angular)
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: myproject@0.0.1
npm WARN Found: @angular/platform-browser@16.0.4
npm WARN node_modules/@angular/platform-browser
npm WARN   @angular/platform-browser@"^16.1.2" from the root project
npm WARN   3 more (@angular/forms, @angular/platform-browser-dynamic, @angular/router)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @angular/platform-browser@"16.0.4" from @angular/router@16.0.4
npm WARN node_modules/@angular/router
npm WARN   @angular/router@"^16.1.2" from the root project
npm WARN   1 more (@ionic/angular)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for critters@0.0.19.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\currentuser\AppData\Local\npm-cache\_logs\2023-06-23T11_05_58_834Z-debug-0.log
Ã— Packages installation failed, see above.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.5

Node: 16.14.0

Package Manager: npm 8.3.1
OS: win32 x64

Angular: 16.0.4

... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
 

Package                         Version

---------------------------------------------------------

@angular-devkit/architect       0.1600.5
@angular-devkit/build-angular   16.0.5
@angular-devkit/core            16.0.5
@angular-devkit/schematics      14.2.7
@angular/cli                    16.0.5
@schematics/angular             14.2.7
rxjs                            6.6.7
typescript                      4.9.5
```

### Anything else?

Here is the output of the search for critters dependency:

C:\DEV\myproject>findstr /R /S critters* C:\DEV\myproject\*.*
C:\DEV\myproject\node_modules\.package-lock.json:        "critters": "0.0.16",
C:\DEV\myproject\node_modules\.package-lock.json:    "node_modules/critters": {
C:\DEV\myproject\node_modules\.package-lock.json:      "resolved": "https://nexus.mynexusserver.com/repository/npm-proxy/critters/-/critters-0.0.16.tgz",
C:\DEV\myproject\node_modules\.package-lock.json:    "node_modules/critters/node_modules/ansi-styles": {
C:\DEV\myproject\node_modules\.package-lock.json:    "node_modules/critters/node_modules/chalk": {
C:\DEV\myproject\node_modules\.package-lock.json:    "node_modules/critters/node_modules/color-convert": {
C:\DEV\myproject\node_modules\.package-lock.json:    "node_modules/critters/node_modules/color-name": {
C:\DEV\myproject\node_modules\.package-lock.json:    "node_modules/critters/node_modules/has-flag": {
C:\DEV\myproject\node_modules\.package-lock.json:    "node_modules/critters/node_modules/supports-color": {
C:\DEV\myproject\node_modules\@angular-devkit\build-angular\package.json:    "critters": "0.0.16",
C:\DEV\myproject\node_modules\@angular-devkit\build-angular\src\utils\index-file\inline-critical-css.js:const Critters = require('critters');
C:\DEV\myproject\node_modules\@angular-devkit\build-angular\src\utils\index-file\inline-critical-css.js:                const crittersMedia = link.getAttribute('onload')?.match(MEDIA_SET_HANDLER_PATTERN);
C:\DEV\myproject\node_modules\@angular-devkit\build-angular\src\utils\index-file\inline-critical-css.js:                if (crittersMedia) {
C:\DEV\myproject\node_modules\@angular-devkit\build-angular\src\utils\index-file\inline-critical-css.js:                    link.setAttribute(CSP_MEDIA_ATTR, crittersMedia[1]);
C:\DEV\myproject\node_modules\@angular-devkit\build-angular\src\utils\index-file\inline-critical-css.js:        const critters = new CrittersExtended({ ...this.options, ...options });
C:\DEV\myproject\node_modules\@angular-devkit\build-angular\src\utils\index-file\inline-critical-css.js:        const content = await critters.process(html);
C:\DEV\myproject\node_modules\@angular-devkit\build-angular\src\utils\index-file\inline-critical-css.js:            errors: critters.errors,
C:\DEV\myproject\node_modules\@angular-devkit\build-angular\src\utils\index-file\inline-critical-css.js:            warnings: critters.warnings,
C:\DEV\myproject\node_modules\critters\package.json:  "name": "critters",
C:\DEV\myproject\node_modules\critters\package.json:  "main": "dist/critters.js",
C:\DEV\myproject\node_modules\critters\package.json:  "module": "dist/critters.mjs",
C:\DEV\myproject\node_modules\critters\package.json:    "import": "./dist/critters.mjs",
C:\DEV\myproject\node_modules\critters\package.json:    "require": "./dist/critters.js",
C:\DEV\myproject\node_modules\critters\package.json:    "default": "./dist/critters.mjs"
C:\DEV\myproject\node_modules\critters\package.json:    "critters",
C:\DEV\myproject\node_modules\critters\package.json:    "url": "https://github.com/GoogleChromeLabs/critters",
C:\DEV\myproject\node_modules\critters\package.json:    "directory": "packages/critters"
C:\DEV\myproject\node_modules\critters\README.md:  <img src="https://i.imgur.com/J0jv1Sz.png" width="240" height="240" alt="critters">
C:\DEV\myproject\node_modules\critters\README.md:## critters [![npm](https://img.shields.io/npm/v/critters.svg)](https://www.npmjs.org/package/critters)
C:\DEV\myproject\node_modules\critters\README.md:*   Integrates with Webpack [critters-webpack-plugin]
C:\DEV\myproject\node_modules\critters\README.md:npm i -D critters
C:\DEV\myproject\node_modules\critters\README.md:yarn add -D critters
C:\DEV\myproject\node_modules\critters\README.md:import Critters from 'critters';
C:\DEV\myproject\node_modules\critters\README.md:const critters = new Critters({
C:\DEV\myproject\node_modules\critters\README.md:const inlined = await critters.process(html);
C:\DEV\myproject\node_modules\critters\README.md:Critters is also available as a Webpack plugin called [critters-webpack-plugin](https://www.npmjs.org/package/critters-webpack-plugin). [![npm](https://img.shields.io/npm/v/critters-webpack-plugin.svg)](https://www.npmjs.org/package/critters-webpack-plugin)
C:\DEV\myproject\node_modules\critters\README.md:The Webpack plugin supports the same configuration options as the main `critters` package:
C:\DEV\myproject\node_modules\critters\README.md:+const Critters = require('critters-webpack-plugin');
C:\DEV\myproject\node_modules\critters\README.md:[critters-webpack-plugin]: https://github.com/GoogleChromeLabs/critters/tree/main/packages/critters-webpack-plugin
C:\DEV\myproject\package-lock.json:        "critters": "0.0.16",
C:\DEV\myproject\package-lock.json:    "node_modules/critters": {
C:\DEV\myproject\package-lock.json:      "resolved": "https://nexus.mynexusserver.com/repository/npm-proxy/critters/-/critters-0.0.16.tgz",
C:\DEV\myproject\package-lock.json:    "node_modules/critters/node_modules/ansi-styles": {
C:\DEV\myproject\package-lock.json:    "node_modules/critters/node_modules/chalk": {
C:\DEV\myproject\package-lock.json:    "node_modules/critters/node_modules/color-convert": {
C:\DEV\myproject\package-lock.json:    "node_modules/critters/node_modules/color-name": {
C:\DEV\myproject\package-lock.json:    "node_modules/critters/node_modules/has-flag": {
C:\DEV\myproject\package-lock.json:    "node_modules/critters/node_modules/supports-color": {
C:\DEV\myproject\package-lock.json:        "critters": "0.0.16",
C:\DEV\myproject\package-lock.json:    "critters": {
C:\DEV\myproject\package-lock.json:      "resolved": "https://nexus.mynexusserver.com/repository/npm-proxy/critters/-/critters-0.0.16.tgz",

C:\DEV\myproject>

**Comment by JoostK** [comment]
[critters 0.19.0 is available on NPM](https://www.npmjs.com/package/critters/v/0.0.19), so this is likely a problem with your environment/Nexus server.
