### ISSUE TITLE
docs: contributing contains link that 404s

### ISSUE THREAD

**Issue by Butterfnger** [angular/angular#50839]
### Describe the problem that you experienced

When visiting the contributing.md (https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines), the link 'samples' should be fixed.

**Comment by sunilbaba** [comment]
Hi @Butterfnger,

 Yes you are correct. I can see samples is pointing to 404 URL. I will try to raise a PR with fix

**Comment by JeanMeche** [comment]
You're pointing to an outdated version of the doc. This issue doesn't exit anymore.
