### ISSUE TITLE
DatePipe: is test `value !== value` really useful?

### ISSUE THREAD

**Issue by enten** [angular/angular#50842]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

Since Angular 5, in `DatePipe`, there is test `value !== value`: **is this test really useful?**

If this test is really useful: can we add a comment which explain its purpose?
If this test is not useful: can we remove it?

https://github.com/angular/angular/blob/5.0.0/packages/common/src/pipes/date_pipe.ts#L138

```ts
@Pipe({name: 'date', pure: true})
export class DatePipe implements PipeTransform {
  // ...
  transform(value: any, format = 'mediumDate', timezone?: string, locale?: string): string|null {
    // QUESTION: Is test `value !== value` really useful?
    if (value == null || value === '' || value !== value) return null;
    // ...
  }
}
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: >=5
```

**Comment by JoostK** [comment]
This is an isNan test; if value is NaN then it's not equal to itself.

I am going to close this since there is no behavioral issue here, but feel free to open a PR to add a comment.
