### ISSUE TITLE
Angular usage note doesn't include usage of required and transform function inside documentation

### ISSUE THREAD

**Issue by sunilbaba** [angular/angular#50840]
### Describe the problem that you experienced

Angular Usage Note Documentation of Input Decoration doesn't include usage of required and transform function. It would be better to add the usage for the new functionality as well.

### Enter the URL of the topic with the problem

https://angular.io/api/core/Input#usage-notes

### Describe what you were looking for in the documentation

Documentation for new features : **Required** and **transform** function inside Input decorator usage notes

**Comment by carlos-ds** [comment]
Seems like `required` is now included on https://angular.io/api/core/Input#usage-notes but adding some more information on `transform` (more specifically: on the `booleanAttribute` and `numberAttribute` functions) is now also mentioned in #50894

**Comment by sunilbaba** [comment]
Hi @carlos-ds 

I don't see latest angular documentation covers the usage of required in the angular.io. do I need to refer the next document ? Or I'm missing something

**Comment by carlos-ds** [comment]
@sunilbaba no, you're right, I was focused on the page itself and not on the usage notes. I edited my comment.

**Comment by bencodezen** [comment]
I believe this has been fixed in the new Angular.dev site:

https://angular.dev/api/core/Input#usage-notes

Feel free to re-open the issue if I'm mistaken.
