### ISSUE TITLE
Large build times for arm64 builds

### ISSUE THREAD

**Issue by Jaskaran-Singh07** [angular/angular#50850]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I am building a multi-architecture docker image for amd64 and arm64. The ``ng build`` command for amd64 takes ~40 seconds while the same command for arm64 is taking ~6 minutes.

Time taken for amd64:
![amd64](https://github.com/angular/angular/assets/133945999/3b05ebe1-5389-469c-9d78-fdb02e9f8294)

Time taken for arm64:
![arm64](https://github.com/angular/angular/assets/133945999/5793dcbd-a4de-4cab-aa8f-46314e3e885b)

I have tried setting various flags in configurations in angular.json, but this has had no effect.
```
"outputHashing": "all",
"optimization": true,
"buildOptimizer": true,
"vendorChunk": false,
"extractLicenses": false,
"sourceMap": false,
"namedChunks": false
```

The npm install command is also taking a lot more time for arm64. However, by caching the node_modules folder, I have reduced the time taken by that step for arm64 to ~50 seconds from ~150 seconds initially; this also reduced the time taken for amd64 from ~28 seconds to ~13 seconds.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.5
Node: 16.15.1
OS: Linux x64
```

**Comment by JoostK** [comment]
This is a question that would be better asked on StackOverflow. It could be that you are caching `node_modules` across the different architectures, resulting in e.g. the native binary for esbuild to be the wrong architecture and falling back to the WASM build, which is a lot slower.
