### ISSUE TITLE
how to compile html into js

### ISSUE THREAD

**Issue by Yunlong2cn** [angular/angular#5085]
i have tried
```
import template from "./home.html"
```
but it makes some misstakes when i compiled with browserify,what the errors are:
```
TypeScript error: src/app/pages/home/home.ts(8,22): Error TS2307: Cannot find module './home.html'.
```
how to solve it ?thanks

**Comment by woppa684** [comment]
I think this is notpossible yet, it is discussed here https://github.com/Microsoft/TypeScript/issues/2709 (as it says here https://github.com/Microsoft/TypeScript/issues/4019).

**Comment by Yunlong2cn** [comment]
@woppa684 thanks , but i have no idea to solve this problem

**Comment by pkozlowski-opensource** [comment]
@Yunlong2cn `import` statement, as specified in ES2015 is for importing JS code only so trying to import HTML won't work here. We might loader specific hooks in the future to enable this (I mean: load + transformation) but this is something that might happen in the future (or not).

What you can do today is one of:
* use `templateUrl` property of a `@Component` / `@View`
* export a template as string (`export const myTpl = "..."`) - then you can import it and use inside `template` property

In the future we are going to have offline template compilation story. We are not here, thought.

I'm going to close this one as there is nothing actionable in this issue. Also, please try not to cross post from gitter - I saw that you got already identical answers for the same question. No need to duplicate questions and efforts to answer them. Thnx!
