### ISSUE TITLE
signal compute not trigger if created in angular shared library

### ISSUE THREAD

**Issue by idanzror100** [angular/angular#50870]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

hello
I have angular project that extend ts.file from angular share library
when the signal is create in "base share library" then compute functions (from signal) not trigger.
it will trigger only when i set "@angular/*" in tsconfig.json:
"compilerOptions": {
        "paths": {
            "@angular/*": [ "./node_modules/@angular/*" ]
        }

is it noraml? can you make it trigger with no add to  tsconfig.json?

thank you.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.0
Node: 18.12.1
Package Manager: npm 9.7.1
OS: win32 x64

Angular: 16.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.0
@angular-devkit/build-angular   16.1.0
@angular-devkit/core            16.1.0
@angular-devkit/schematics      16.1.0
@schematics/angular             16.1.0
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by JoostK** [comment]
Signals require some global state to track signal reads, which require that the signals library is only included once in the bundle. You cannot use multiple occurrences of the signal library, hence it's important that all module imports resolve to the exact same ES modules (which can be accomplished using the tsconfig change you shared)
