### ISSUE TITLE
ControlGroup - [ng-form-model] - the form always is invalid (Childs as input controls)

### ISSUE THREAD

**Issue by danicomas** [angular/angular#5087]
I have two different examples but with the same pattern (parent component and inputs as a child component)

http://plnkr.co/edit/IdgoEJqpIBmr16Ca1zFI?p=preview
http://plnkr.co/edit/bFNqDrH0akyZ4ua0vzHz?p=preview

I don't know how the form could return valid = true

**Comment by webnobushi** [comment]
I've put my solution here .

http://plnkr.co/edit/tH3vQo8Leop0M7mt7K8E?p=preview

**Comment by danicomas** [comment]
The problem is passing ngModel to child component: https://github.com/angular/angular/issues/3076
