### ISSUE TITLE
The Input property for route parameter is not modified when the route changes 

### ISSUE THREAD

**Issue by DeborahK** [angular/angular#50875]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

We can react to changes in a route parameter using code like this:
```
// WORKS
  idA = 0;
  ngOnInit(): void {
    this.route.params.subscribe((data) => {
      this.idA = data['id'];
    });
  }
```
This code still works. But when using the new `Input` property for route parameters, there is no notification when the route parameter changes. The Input property setter does not execute and the ngOnChanges does not respond to a change.
```
  // Using setter
  // DOES NOT WORK
  _idB = '0';
  @Input()
  get idB(): string {
    return this._idB;
  }
  set idB(value: string) {
    this._idB = value;
    console.log(this.idB);
  }

  // Using NgOnChanges
  // DOES NOT WORK
  idC = 0;
  ngOnChanges(changes: SimpleChanges) {
    this.idC = Number(changes.id.currentValue);
    console.log(changes);
  }

```
The expectation is that when using the `Input` property for the route parameters, it should modify the property when the route parameter changes.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-ffcyfm

### Please provide the exception or error you saw

```true
No exception or error, it just doesn't react to changes.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular/animations
16.1.3
@angular/common
16.1.3
@angular/compiler
16.1.3
@angular/core
16.1.3
@angular/forms
16.1.3
@angular/platform-browser
16.1.3
@angular/platform-browser-dynamic
16.1.3
@angular/router
16.1.3
@types/jasmine
4.3.4
rxjs
7.8.1
tslib
2.6.0
zone.js
0.13.1
```

**Comment by atscott** [comment]
Hi @DeborahK, you need to use the `withComponentInputBinding` feature in the `provideRouter`. Also, the input names need to match the parameter name. Here's an updated working example: https://stackblitz.com/edit/stackblitz-starters-bqtphx?file=src%2Fapp%2Fproduct-detail%2Fproduct-detail.component.ts,src%2Fapp%2Fproduct-detail%2Fproduct-detail.component.html,src%2Fapp%2Fapp.config.ts,src%2Fapp%2Fapp.component.ts
