### ISSUE TITLE
Wrong file name mentioned(component instead of module) in lession 2 of Angular tutorial.

### ISSUE THREAD

**Issue by SankesaNikhil** [angular/angular#50876]
### Describe the problem that you experienced

In lesson02: Step 2 - Add the new component to your app's layout :- 

In point 2 and 3, instead of  app.component.ts it should be app.module.ts.

A standalone component cannot be imported to AppComponent.

So it is throwing an error, if we make these changes in app.component.ts file.

Instead if me make same changes in app.module.ts file, it is working fine.

please find the attached screenshot where the file name needs to be changed.

<img width="1381" alt="Screenshot 2023-06-29 at 01 17 34 1" src="https://github.com/angular/angular/assets/30267045/13d1fab5-4b02-4f76-894c-15696e77fd3a">

### Enter the URL of the topic with the problem

https://angular.io/tutorial/first-app/first-app-lesson-02

**Comment by garrettld** [comment]
This tutorial is standalone from beginning to end, so if you've got an `app.module.ts` file then you don't have the up-to-date starting files from step 1. I'd suggest re-downloading the files and trying again: https://angular.io/tutorial/first-app/first-app-lesson-01

**Comment by JeanMeche** [comment]
This is right, the tutorial invites you to start with a standalone app.
