### ISSUE TITLE
Textarea ng-maxlength issues in chrome

### ISSUE THREAD

**Issue by ehog90** [angular/angular#5088]
In chrome, I've made a textarea, with a character number limit. (showing a text: x / 1000 characters left) When there are one or more linebreaks  are in the text, the counter won't reach zero, and i cannot type more to reach it.  (won't go below the linebreaks count) 
The issue is existing on Chrome only, not in IE12.

Angular version: 1.3.6
Chrome version: 46

**Comment by gkalpak** [comment]
This repository is for Angular 2.0.
You are probably looking for https://github.com/angular/material.
