### ISSUE TITLE
Mention booleanAttribute and numberAttribute inside @Input page

### ISSUE THREAD

**Issue by 4javier** [angular/angular#50894]
### Describe the problem that you experienced

Inside `@Input()` decorator page there's no mention of the two function `@angular/core` ships on purpose to be used with it `{transform: fn()}` property.
Since they've been created basically just for that, I think it would be a nice add, considering they're mentioned in other pages.

### Enter the URL of the topic with the problem

https://angular.io/api/core/Input#transform

### Describe what you were looking for in the documentation

The possible functions shipped out-of-the-box by the framework to be used as `transform` value

**Comment by 4javier** [comment]
@JeanMeche 
It's not my first issue opened on Angular docs :-)
I can take care of this if you like it.

**Comment by JeanMeche** [comment]
Sure, every valuable contribution from the community welcome ! Feel free to open a PR 👍

**Comment by 4javier** [comment]
Should I edit metadata for core package's `directives.ts`, or just mention them inside https://angular.io/guide/inputs-outputs linked by the former?

**Comment by JeanMeche** [comment]
I'd say both and even add an example in `coercion.ts` !  So developers don't have to check several pages to understand how to use them !

**Comment by sunilbaba** [comment]
Hi @JeanMeche / @4javier 

There is already a open PR raised by me on updating the documentation of transforming usage. 

 Can we review this PR and add together missing pieces instead of raising new one. 

Pr number : https://github.com/angular/angular/pull/50841

**Comment by 4javier** [comment]
Hi @sunilbaba 
I had checked for already opened issues but didn't find anything about that, so I didn't look for pending PR.
I'll stop my work. 
You should integrate the other changes suggested by JeanMeche in your PR.

**Comment by sunilbaba** [comment]
Hi @JeanMeche 

As suggested you added changes in the input output section as well as coercion.ts. could you please take a look at PR and provide your review on the changes

**Comment by vijayabhaskar95** [comment]
Hi , 
I could work on this issue if it is still open?

**Comment by sunilbaba** [comment]
Hi @vijayabhaskar95 
There is already a open PR on this

**Comment by 4javier** [comment]
@sunilbaba 
You need to fix some linting errors, tho.
Pipeline keep failing.

**Comment by sunilbaba** [comment]
@4javier - sure I will do it

**Comment by sunilbaba** [comment]
This PR was merged into the repository by commit https://github.com/angular/angular/commit/bb0f3bc1250c2505369305b4ad7ee249baed1509.
