### ISSUE TITLE
Stackblitz fails for all samples on Angular.io

### ISSUE THREAD

**Issue by larsm11** [angular/angular#50907]
### Describe the problem that you experienced

Regardless of what sample script is run, if fails on Stackbliz with this message:

_"Error in /turbo_modules/@angular/common@16.1.3/fesm2022/common.mjs (74:155)
Cannot read properties of undefined (reading 'Injectable')"_

### Enter the URL of the topic with the problem

https://stackblitz.com/angular/jxbypvbglbk?file=src%2Fapp%2Fsidenav-position-example.ts

**Comment by JeanMeche** [comment]
The deps are totally messed up. Where did you find that stackblitz ?

**Comment by JeanMeche** [comment]
This is an outdated stackblitz, I'll invite to open the one in the docs : https://material.angular.io/components/sidenav/overview

**Comment by larsm11** [comment]
Angular Material SDK links. https://material.angular.io/components/autocomplete/examples
