### ISSUE TITLE
[bug] ng-repeat + ng-model + input[type=email]

### ISSUE THREAD

**Issue by leitasat** [angular/angular#5090]
Hello!

Have just found a very weird bug: if I use input of `type="email"` instead of `type="text"` inside `ng-repeat`, binding becomes broken. Check out the fiddle http://jsfiddle.net/3L143sn6/ (slightly modified version of this http://jsfiddle.net/jaimem/rnw3u/5/ by jaime from here http://stackoverflow.com/a/13715352/1151950 )

Tried on both 1.2.1 at jsFiddle and 1.4.7 in my project.

Thanks.

**Comment by pkozlowski-opensource** [comment]
Wrong repo - this one is for Angular 2. Try https://github.com/angular/angular.js
