### ISSUE TITLE
SSR Image is not defined

### ISSUE THREAD

**Issue by CarlosTorrecillas** [angular/angular#50904]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When I use the image object on my SSR solution it does fail server side and the image does not get rendered although it gets displayed in the browser.

In order to reproduce the issue, clone the repo in the link and do:
1.- `npm run dev:ssr`
2.- navigate to `http://localhost:4200/image-issue`

### Please provide a link to a minimal reproduction of the bug

https://github.com/CarlosTorrecillas/universal-issue

### Please provide the exception or error you saw

```true
ERROR ReferenceError: Image is not defined
    at ngOnInit (./src/app/image-module/image-component/image-component.component.ts:12:23)
    at callHookInternal (./node_modules/@angular/core/fesm2022/core.mjs:3841:14)
    at callHook (./node_modules/@angular/core/fesm2022/core.mjs:3868:13)
    at callHooks (./node_modules/@angular/core/fesm2022/core.mjs:3823:17)
    at executeInitAndCheckHooks (./node_modules/@angular/core/fesm2022/core.mjs:3773:9)
    at refreshView (./node_modules/@angular/core/fesm2022/core.mjs:12490:21)
    at detectChangesInView (./node_modules/@angular/core/fesm2022/core.mjs:12639:9)
    at detectChangesInEmbeddedViews (./node_modules/@angular/core/fesm2022/core.mjs:12583:13)
    at refreshView (./node_modules/@angular/core/fesm2022/core.mjs:12499:9)
    at detectChangesInView (./node_modules/@angular/core/fesm2022/core.mjs:12639:9)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 16.1.0
Node: 18.10.0
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 16.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.0
@angular-devkit/build-angular   16.1.0
@angular-devkit/core            16.1.0
@angular-devkit/schematics      16.1.0
@angular/cli                    16.1.0
@nguniversal/builders           16.1.0
@nguniversal/express-engine     16.1.0
@schematics/angular             16.1.0
rxjs                            7.8.1
typescript                      4.9.5
```

### Anything else?

I couldn't find anything in the SSR gotchas and this is the first time I use the Image object. I don't know if that can be used on SSR (I would have assumed so) and I don't know if I should be using something else. Essentially I am programmatically scaling an image based on its width and height considering I want a height of 75px.

**Comment by JeanMeche** [comment]
The Image class does not exist in the nodejs runtime. 

You could use the [canvas package](https://www.npmjs.com/package/canvas) for that.

**Comment by JeanMeche** [comment]
The technical reason for the error is that the `Image` constructor only exists in a browser environment and not in nodejs where the ssr runs.

**Comment by CarlosTorrecillas** [comment]
Ok that’s fair enough. I guess that could be included as part of the SSR gotchas or the universal documentation somewhere. To me it wasn’t that obvious - not sure if it is anyway, but I think it would be helpful

**Comment by alucardu** [comment]
And what would be a solution/workaround for this issue?

**Comment by JeanMeche** [comment]
@alucardu One possibility is to run this code only on the client side.

**Comment by alucardu** [comment]
> @alucardu One possibility is to run this code only on the client side.

Yes, but I'm also using Capacitor and I was running into a `document is not defined` & `window is not defined` error (on my server) so I added this to my server.ts
```
const scripts = readFileSync('dist/angular-movieseat/browser/index.html').toString();
const window = createWindow(scripts) as any;
(global as any).window = window;
(global as any).document = window.document;
```
Which resolved the issue, but now this condition `typeof document !== 'undefined'` to check if the app is run in the client doesn't work because (I think) I avoid document being undefined in the server.ts

**Comment by CarlosTorrecillas** [comment]
> @alucardu One possibility is to run this code only on the client side.

This is what I am currently doing and works fine

**Comment by alucardu** [comment]
> > @alucardu One possibility is to run this code only on the client side.
> 
> This is what I am currently doing and works fine

Do you perchance know another way to do this than using `typeof document !== 'undefined'` ?

**Comment by JeanMeche** [comment]
You can use `isPlatformBrowser` :

```
  constructor(injector: Injector, @Inject(PLATFORM_ID) platformId: object) {
    if (isPlatformBrowser(platformId)) {
      customElements.define('app-title-ce', createCustomElement(TitleComponent, {injector}));
    }
  }
```
