### ISSUE TITLE
Docs: FormControl not mentioned as subclass of AbstractControl

### ISSUE THREAD

**Issue by carlos-ds** [angular/angular#50912]
### Describe the problem that you experienced

I was recently browsing through the docs for `AbstractControl` and I noticed that the first line states:

> This is the base class for [FormControl](https://angular.io/api/forms/FormControl), [FormGroup](https://angular.io/api/forms/FormGroup), and [FormArray](https://angular.io/api/forms/FormArray).

Yet, on the same page under [Subclasses](https://angular.io/api/forms/AbstractControl#subclasses), `FormControl` is not mentioned as a subclass. Perhaps I'm missing something here but this seems to contradict? As far as I can tell, `FormControl` is effectively a subclass of `AbstractControl`. 

If someone could confirm this is indeed a mistake, then I'd be happy to open a PR to fix it.

### Enter the URL of the topic with the problem

https://angular.io/api/forms/AbstractControl

**Comment by Jaishree2310** [comment]
@JeanMeche  I am at a beginner level right now and would love to take up this ticket. can you please assign it to me? thanks in advance!

**Comment by JeanMeche** [comment]
@Jaishree2310 Feel free to open a PR directly and reference this issue 😉

**Comment by Rhythm-08** [comment]
Hello, I would like to take this issue.

**Comment by JeanMeche** [comment]
@Rhythm-08 Feel free to open a PR 👍

**Comment by JeanMeche** [comment]
After a short investigation, this content is generated automaticaly by [dgeni](https://github.com/angular/dgeni) but somehow it misses the subclass `FormControl`.

**Comment by luishcastroc** [comment]
> After a short investigation, this content is generated automaticaly by [dgeni](https://github.com/angular/dgeni) but somehow it misses the subclass `FormControl` because of uncommon the definition :
> 
> ```
> export interface FormControl<TValue = any> extends AbstractControl<TValue> {
> ...
> }
> 
> 
> export interface ɵFormControlCtor {
>   new(): FormControl<any>;
>   ...
> }
> 
> export const FormControl: ɵFormControlCtor =     (class FormControl<TValue = any> extends AbstractControl<TValue> implements FormControlInterface<TValue> { ... }
> ```

I see the good first issue label is no longer there I was actually digging on this one do you think it will require something a lot more complicated? I'm in on giving a try as I mentioned on the discord

**Comment by JeanMeche** [comment]
Yes it's much more complicated that I expected. 

The change has to be made in the dgeni repo.

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
