### ISSUE TITLE
ProvidedIn: 'any' in Angular 14+ is deprecated. What is the alternative when using an angular standalone component?

### ISSUE THREAD

**Issue by jasonc08** [angular/angular#50918]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Based on my understanding, it seems that Angular currently doesn't offer a means to inject a unique instance into a service.

If I want to inject a unique instance similar to the following code, how can I achieve that when using an angular standalone component?

```
@Injectable({
  providedIn: 'root'
})
export class MyService {
  constructor(private uniqueInstanceA: UniqueInstance, private uniqueInstanceB: UniqueInstance) {
      uniqueInstanceA.setUrl("/api/abc");
      uniqueInstanceB.setUrl("/api/def");
  }
```

```
@Injectable({
  providedIn: 'any'
})
export class UniqueInstance{
  url: string = "";
  constructor(private http: HttpClient) { } 
  
  setUrl(url:string) {
      this.url = url;
  } 
```
 

### Proposed solution

Is it possible to use the 'any' option in the 'providedIn' property again?

### Alternatives considered

no

**Comment by JeanMeche** [comment]
If you want a unique instance, use the `@Self` decorator in the constructor or `inject(MyService, {self: true})`

**Comment by JeanMeche** [comment]
What you are describing is not dependency injection. 

What you are probably looking for is injecting a factory which will then create a new instance at every call. 

This has already been discussed here #40262.

**Comment by jasonc08** [comment]
thx
