### ISSUE TITLE
Location.prepareExternalUrl does not prepend '/' if 'useHash' is enabled

### ISSUE THREAD

**Issue by vslipchenko** [angular/angular#50917]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

According to https://angular.io/api/common/Location#prepareexternalurl, it is assumed that slash is prepended in cases when `useHash` (HashLocationStrategy) is enabled, but it doesn't happen.

`location.prepareExternalUrl('user')` results in `#/user` if `{useHash: true}`, but if `{useHash: false}` the result is  `/user` .
It is expected to be  `/#/user` as if it were normalized.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.2
Node: 18.12.1
Package Manager: npm 9.2.0
OS: win32 x64

Angular: 15.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.2
@angular-devkit/build-angular   15.1.2
@angular-devkit/core            15.1.2
@angular-devkit/schematics      15.1.2
@angular/cli                    15.1.2
@angular/material               15.1.0
@schematics/angular             15.1.2
rxjs                            7.8.0
typescript                      4.9.4
```

**Comment by JeanMeche** [comment]
This works like expected, the hash is added after the '/' is added (that's what `joinWithSlash` does). 

https://github.com/angular/angular/blob/125fe19086e3c845816d46c990899fd3edc1ebbe/packages/common/src/location/hash_location_strategy.ts#L74-L77
