### ISSUE TITLE
Specify extra effect dependencies without using them inside the effect function

### ISSUE THREAD

**Issue by ghazi-git** [angular/angular#50916]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Allow specifying dependencies without the need to call them inside the effect. That is needed whenever we need to react to a signal change without needing to use the value of that signal inside the effect. For example:
```javascript
// log the below message whenever a task is completed (assuming we have a `completedTasksCount` signal)
effect(() => {
    console.log("Congratulations on completing the task!!")
})
```

### Proposed solution

add `extraDependencies` to [CreateEffectOptions](https://angular.io/api/core/CreateEffectOptions). It will be a list of signals that trigger re-execution of the effect even though they are not used inside the effect.

```javascript
effect(() => {
    console.log("Congratulation on completing the task!!")
}, {extarDependencies: [completedTasksCount]})
```

I also thought this new option fits best as the last piece that complements what angular currently has:
- automatic tracking of signals used inside the effect
- ability to [untrack](https://angular.io/guide/signals#reading-without-tracking-dependencies) specific signals even though though they are used inside the effect

#### Add `dependencies` to [CreateEffectOptions](https://angular.io/api/core/CreateEffectOptions).
The new option will handle both: untracking of signals used inside the effect and tracking of signals not used inside the effect. When `dependencies` is specified, angular should disable its default behavior and only track signals specified in `dependencies`. I actually think this is a better alternative if the feature is approved for implementation. That's because it provides one API for tracking and untracking as opposed to checking the `extraDependencies` to know what forces re-execution of the effect and checking the effect body to see which signals are wrapped inside `untracked`.

#### tracked(completedTasksCount)
much like there is `untracked(counter)`, add `tracked(counter)` to trigger re-execution of the effect. My problem with it is that it can be called anywhere inside the effect. So, there is no one place to check what forces re-execution of the effect.

#### Check other frontend libraries/frameworks
- Solidjs [on](https://www.solidjs.com/docs/latest/api#on): I went to check if solidjs has sth to deal with these use cases and `on` seemed to be the closest thing. To be honest, I didn't quite understand if it solves the same issue, so I'm only mentioning it here in case it's helpful.
- Preact [effect](https://github.com/preactjs/signals#effectfn): seems like it doesn't allow re-execution of the effect unless a signal is accessed.
- Svelte: the `$:` seems to re-execute only when one of the values referenced inside changes
- Qwik [useTask$](https://qwik.builder.io/docs/guides/qwik-nutshell/#usetask----): doesn't run into the problem because it is explicit about what the effect tracks `taskContext.track(() => page.value)`
- React `useEffect`: doesn't run into the problem because it is explicit about what the effect tracks through `dependencies`

**Comment by zip-fa** [comment]
That would confuse existing devs and newcomers.
Why do we need that many approaches to do the same thing?
How you will find your dependency after large fn body?
How many use-cases you will find when you dont need value of changed signal to compute something?
Will you use different approaches inside the same cmp, or is it better to stick to one “the best” approach?

testEffect = effect(() => console.log(`hi ${ this.name() }`));

test2 = effect(() => this.computeSmth(), [this.dep]); 



Thats looks like something reactish and is antipattern for me personally

**Comment by pkozlowski-opensource** [comment]
I'm not sure I see much difference / added value of:

```typescript
effect(() => {
    console.log("Congratulation on completing the task!!")
}, {extarDependencies: [completedTasksCount]})
```

as compared to sth that is supported today:

```typescript
effect(() => {
    // extarDependencies: 
   completedTasksCount();
    console.log("Congratulation on completing the task!!")
})
```

We would have to have really good reasoning here, before introducing new public API and "another way of doing the same thing".

@ghazi-git do you have additional info / arguments that would help us asses value of the proposal in the light of the above comment?

**Comment by ghazi-git** [comment]
> That would confuse existing devs and newcomers.
> Why do we need that many approaches to do the same thing?
> How you will find your dependency after large fn body?
> How many use-cases you will find when you dont need value of changed signal to compute something?
> Will you use different approaches inside the same cmp, or is it better to stick to one “the best” approach?
>
> testEffect = effect(() => console.log(`hi ${ this.name() }`));
> 
> test2 = effect(() => this.computeSmth(), [this.dep]);

@zip-fa I think there is some confusion about the proposal. I'm suggesting that angular adds `extraDependencies` to the `effect` API to make it clear when there is a signal that will trigger the effect but it is not used inside the effect. If a signal is already used inside the effect, there is no need to add it to `extraDependencies`. Angular can add a warning to notify the developer about that (or it can become a linting rule).
The other approaches are alternatives that were considered before submitting the proposal. Also, after reading your comment, I think what you said is valid criticism of the first alternative. Adding `dependencies` (rather than `extraDependencies`) means angular will have 2 ways to do the same thing.

> Thats looks like something reactish and is antipattern for me personally

I wouldn't worry about things looking reactish or not. I think what's more important if the change has an added value to the framework or not. Angular showed us in the past few months that it will not shy away from getting the good ideas from other frontend libraries (signals started in solidjs, the signal function names are the same as in [preact](https://github.com/preactjs/signals#guide--api) and the new [control flow syntax](https://github.com/angular/angular/discussions/50719) is similar to svelte)

**Comment by ghazi-git** [comment]
@pkozlowski-opensource the main argument for adding `extraDependencies` is that angular will provide a clear way of triggering an effect in response to a signal when we don't need to use the signal inside the effect. The example you added does the trick but it is implicit. It relies on the comment to be there so that it clarifies the need for referencing the signal without actually using it. Without the comment, the next developer reading the code might remove the signal since it seems unused. Adding an API for this use case makes the purpose of the signal obvious without the need for a comment.

I wouldn't say it's "another way of doing the same thing" because the API is for signals that are not used inside of the effect (angular can add a warning to remove the extra dependency if it is used inside the effect).

**Comment by wartab** [comment]
I think what you want would be abusing what signals are used for.

I recommend using the rxjs-interop that Angular has shipped along with signals for this:

```ts
import {toObservable} from "@angular/core/rxjs-interop";


constructor() {
    this.completedTasksCount = signal(0);

    toObservable(this.completedTasksCounts)
        .subscribe(completedTasksCounts=> {
            console.log(completedTasksCounts);
        });
}

```

You don't even have to unsubscribe manually as Angular does this for you upon component cleanup.

**Comment by ghazi-git** [comment]
that is a good point @wartab, this case can be handled using observables. I guess interoperability with observables is one of the strong points of signals in angular. Still, `toSignal` is the one that [automatically unsubscribes](https://angular.io/guide/rxjs-interop#manualcleanup) (but [`takeUntilDestroyed`](https://angular.io/api/core/rxjs-interop/takeUntilDestroyed) makes it easy enough to unsubscribe).

Let's see what others have to say about it

**Comment by wartab** [comment]
toObservable() does automatically unsubscribe:
https://github.com/angular/angular/blob/main/packages/core/rxjs-interop/src/to_observable.ts

**Comment by pkozlowski-opensource** [comment]
> the main argument for adding extraDependencies is that angular will provide a clear way of triggering an effect in response to a signal when we don't need to use the signal inside the effect.

But this is precisely the design we did _not_ choose - signals automatically track their dependencies and this is one of their main strengths. 

I'm going to close this issue for now as:
* there are existing ways of achieving the desired functionality;
* the ideas in this proposal contradict our design goals.

**Comment by ghazi-git** [comment]
got it @pkozlowski-opensource, still thanks for considering the proposal.

and thank you @wartab for the note about `toObservable`. I didn't know that before

**Comment by simeyla** [comment]
I've had the similar feeling myself - that the dependency feels like it's orphaned.
I kind of wanted something that was the opposite of `untracked`, like `track` or `touch`.

```
effect(() => {
   touch(completedTasksCount);
   console.log("Congratulation on completing the task!!")
})
```

If you really wanted this you could just write it yourself, but it would be somewhat pointless. 

I concluded that writing a comment above the extra dependencies made it clearer and feel less 'orphaned'.
