### ISSUE TITLE
Docs search results have invalid links 

### ISSUE THREAD

**Issue by kullmanp** [angular/angular#50926]
### Describe the problem that you experienced

In https://angular.io/docs search for "HttpClientTestingModule" (for example). 
One of the results in the api section with this url: https://angular.io/api/common/http/testing/HttpClientTestingModule

This url is not accessible. It displays: 
REQUEST FOR DOCUMENT FAILED
We are unable to retrieve the "api/common/http/testing/HttpClientTestingModule" page at this time.
Please check your connection and try again later.

**Comment by JeanMeche** [comment]
I can't reproduce. Can you reproduce that issue across multiple browsers ?

**Comment by pkozlowski-opensource** [comment]
Was just trying to reproduce as well but things seem to work as expected. We will need more details to diagnose but indeed sounds like sth linked to a specific environment.

**Comment by kullmanp** [comment]
Oh, indeed: This happens only on my chrome. When I try the same with Edge it works as expected. 
And now, after clearing the browser cache it also works on chrome again.
