### ISSUE TITLE
@HostListener('window:beforeunload') not firing any more

### ISSUE THREAD

**Issue by DywiTom** [angular/angular#50935]
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

Yes

### Description

The event beforeunload is not firing anymore
My code in app.component.ts the is following code snippet:

```
  @HostListener('window:beforeunload', ['$event'])
  handleClose(): boolean { return !environment.production; }
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/animations": "^16.1.3",
"@angular/cdk": "^16.1.3",
"@angular/common": "^16.1.3",
"@angular/compiler": "^16.1.3",
"@angular/core": "^16.1.3",
"@angular/forms": "^16.1.3",
"@angular/material": "^16.1.3",
"@angular/material-luxon-adapter": "^16.1.3",
"@angular/platform-browser": "^16.1.3",
"@angular/platform-browser-dynamic": "^16.1.3",
"@angular/router": "^16.1.3",
"zone.js": "^0.13.1",
```
```


### Anything else?

_No response_

**Comment by Gortyser** [comment]
I wasn't able to reproduce the issue. Tested it with package versions specified in the latest Chrome/Firefox/Opera.
Can you provide more details?
1. What are you trying to achieve with this code?
2. You're saying it 'is not firing anymore'. What version you've used when it worked?

Code that worked for me:
```ts
@HostListener('window:beforeunload', ['$event'])
handleClose(e: BeforeUnloadEvent): void {
  console.log('test');
  e.preventDefault();
  e.returnValue = 'test';
}
```
I could not show a custom message, but the event fired in every browser, that's for sure.

**Comment by DywiTom** [comment]
It seems there is an other problem in my project. thanks for help!

**Comment by grafanauser** [comment]
@Gortyser 
your code works for me. But in Angular 15 you could simply return false/true without using .preventDefault() and it would still work. That seems to not work anymore in Angular 16.

**Comment by Gortyser** [comment]
@grafanauser good to know, haven't checked it in Angular 15!
