### ISSUE TITLE
DatePipe transforms incorrectly

### ISSUE THREAD

**Issue by sanjaymaurya-apaar** [angular/angular#50934]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

Hello team,

Let me try to explain using snippets. Let us import the DatePipe class first.

`import { DatePipe } from '@angular/common'`

Then let Angular handle DI for the class instantiation using class constructor.

`constructor(private datepipe: DatePipe){}`

Now, if we pass any of following into date transformation, we get incorrect result:

`this.datepip.transform('2021-01-01', 'YYYY-MM-dd')`

This returns `2020-01-01` instead of `2021-0-01`.

I tried passing date object, the result remained the same.

`let dt = new Date('2021');
this.datepip.transform(dt , 'YYYY-MM-dd')`

Angular Package version: `@angular/common: 15.2.0`

Thank you,

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.6
Node: 18.16.0
OS: win32 x64

Angular: 15.2.7
typescript: 4.9.5
```

**Comment by JeanMeche** [comment]
`YYYY` is the "week numbering year" which is for very special cases.. You need to use `yyyy`.

**Comment by sanjaymaurya-apaar** [comment]
Thanks for the update. It worked for me.
