### ISSUE TITLE
Missing house images in assets folder of pre-built app provided in "Create Your First Angular App" tutorial.

### ISSUE THREAD

**Issue by rajeshuser** [angular/angular#50939]
### Describe the problem that you experienced

The "First Angular app lesson 1 - Hello world" provides a pre-built app to start with to follow the "Create Your First Angular App" tutorial. But, "Lesson 7 - Add an interpolation to a component’s template" and "Lesson 8 - Use *ngFor to list objects in component" expects some images to be present in assets folder of the pre-built app. When the app is run without the necessary images in assets folder, the images appear to be broken in the rendered app.

### Enter the URL of the topic with the problem

https://angular.io/tutorial/first-app/first-app-lesson-08

### Describe what you were looking for in the documentation

I am looking for images in the pre-built app required for app being constructed in the "Create Your First Angular App" tutorial to render correctly.

### Describe the actions that led you to experience the problem

Mainly, by following the lesson "Lesson 8 - Use *ngFor to list objects in component", I have encountered the problem.

### Describe what you want to experience that would fix the problem

Provide images in the pre-built app required for app being constructed in the "Create Your First Angular App" tutorial to render correctly.

### Add a screenshot if that helps illustrate the problem

![Screenshot (1750)](https://github.com/angular/angular/assets/112754709/35ed8640-2c65-4e49-ad46-21c785d3dbf5)

### If this problem caused an exception or error, please paste it here

```true
example-house.jpg:1 
GET http://localhost:4200/assets/example-house.jpg 404 (Not Found)
```
```


### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
The problem is not specific to any browser.
```

**Comment by JeanMeche** [comment]
Hi, 

We are tracking this issue at #50647.

**Comment by RQuadros** [comment]
Hi everybody,

I've faced the same issue and I think this might help.

In a previous chapter, when we hard-code the housingLocationList on the "housing.service.ts" file, it is added the logic to concatenate the baseUrl of each photo: 

_`${this.baseUrl}/bernard-hermant-CLKGGwIBTaY-unsplash.jpg`,_

And after, when this data is moved to the "db.json" file, the baseUrl is removed:

_"photo": "/assets/bernard-hermant-CLKGGwIBTaY-unsplash.jpg",_

The final URL of an image needs to be like this:

_https://angular.io/assets/images/tutorials/faa/bernard-hermant-CLKGGwIBTaY-unsplash.jpg_

Best regards!
