### ISSUE TITLE
Can toSignal be used in ngOnInit?

### ISSUE THREAD

**Issue by anisabboud** [angular/angular#50947]
### Describe the problem that you experienced

The documentation of rxjs-interop https://angular.io/guide/rxjs-interop states that `toSignal` "can be used anywhere":
> The [toSignal](https://angular.io/api/core/rxjs-interop/toSignal) function creates a signal which tracks the value of an Observable.
> It behaves similarly to the [async](https://angular.io/api/common/AsyncPipe) pipe in templates, but is more flexible and **can be used anywhere in an application**.

But when using `toSignal` inside `ngOnInit() { ... }`, I encountered a runtime error [`NG0203`](https://angular.io/errors/NG0203): `toSignal() can only be used within an injection context` (Angular version `16.1.3` latest):

![image](https://github.com/angular/angular/assets/5672108/b974ff25-2f94-49fa-a902-c9085889628e)

---

I.e., the documentation states that [`toSignal`](https://angular.io/guide/rxjs-interop#tosignal) can be used anywhere, but the runtime error states that it needs to run in an injection context. Can you please clarify which one is correct?

The documentation of [`toObservable`](https://angular.io/guide/rxjs-interop#injection-context) states clearly that "toObservable by default needs to run in an injection context".
So I'm guessing the same is true for its sister function `toSignal`?

**Comment by JeanMeche** [comment]
I would personally go with #2, less code for the same result but I would understand #1 for those who like to keep the DI in the constructor. Both are perfectly fine !

**Comment by anisabboud** [comment]
Ran into another issue with this: Since component inputs are not yet defined in the constructor (or in the class initialization), you cannot use `mySignal = toSignal(this.myService.loadData(this.myInput));` since `this.myInput` would still be undefined. In ngOnInit, the inputs will be initialized and can be used.

There must be some more ergonomic way to use `toSignal`...

**Comment by JeanMeche** [comment]
The ergonomics you are looking for will be provided with the signal components presented in the [recent RFC](https://github.com/angular/angular/discussions/49682) !

**Comment by pkozlowski-opensource** [comment]
> The ergonomics you are looking for will be provided with the signal components (which feature inputs as signals) presented in the https://github.com/angular/angular/discussions/49682 !

Exactly this! I think that @JeanMeche answered all the questions here. Thnx for play with signals @anisabboud !

**Comment by anisabboud** [comment]
I.e., how to translate the following code to use `toSignal`, without an injection context boilerplate?

```typescript
  @Input({ required: true }) itemId!: string;

  myService = inject(MyService);
  myObservable!: Observable<MyModel>;

  ngOnInit() {
    this.myObservable = this.myService.loadData(itemId);
  }
```

I would like to simply convert the observable into a signal like so:
```typescript
  this.mySignal = toSignal(this.myService.loadData(itemId));
```
But:
- You cannot call `toSignal` in `ngOnInit` since that's not an injection context, and 
- You cannot call `toSignal` in the `constructor` if you rely on an `Input` as that would be undefined when the constructor runs ([Angular inputs are not yet initialized](https://stackoverflow.com/questions/33561845/cannot-access-inputs-from-my-controller-constructor))...

So where to call `toSignal`?

Seems like for now we should stick to Observables and `async` pipe, and wait for the proposed "Signal-based inputs" to land...

**Comment by pkozlowski-opensource** [comment]
Currently the best option for your use-case is to use injection context. Also note that `ngOnInit` might not be enough as an input might change (depending on your component of course, speaking about a general case) - in this case `ngOnChanges` would be more appropriate.

But yes, those friction points are temporary - reactive inputs will make it easier.

**Comment by anisabboud** [comment]
Thank you @pkozlowski-opensource and nice work on the Signals API 👍

To summarize, for now we can use an `InjectionContext` to use `toSignal`:
```typescript
  injector = inject(EnvironmentInjector);
  myService = inject(MyService);
  mySignal!: Signal<MyModel>;

  ngOnInit() {
    runInInjectionContext(this.injector, () => {
      this.mySignal = toSignal(this.myService.loadData());
    });
  }
```
And I'm guessing once "Signal-based inputs" arrive, we can safely reference "signal inputs" in the constructor or the field initializers without them being undefined (to reduce the injector boilerplate).

**Comment by vespertilian** [comment]
@anisabboud 

Your example was helpful, thanks.

A small note on your implementation: `EnvironmentInjector` is **not the components injector** and if you create a signal in this context **it will not be unsubscribed from when the component is destroyed**, it will only be unsubscribed from when the "Environment" is destroyed (I don't even know when that happens). 

You need to use `injector = inject(Injector)` if you want the signal to unsubscribe from the observable when the component is destroyed.

**Comment by anisabboud** [comment]
Thank you for the clarification, @vespertilian!
I wish it was more clearly documented that `inject(Injector)` is the component's injector...

https://angular.io/api/core/Injector
> Concrete injectors implement this interface. Injectors are configured with [providers](https://angular.io/guide/glossary#provider) that associate dependencies of various types with [injection tokens](https://angular.io/guide/glossary#di-token).

https://angular.io/api/core/EnvironmentInjector 
> An Injector that's part of the environment injector hierarchy, which exists outside of the component tree.
