### ISSUE TITLE
when using node v18.10.0 , package.json engines can't prevent using npm install dependencies

### ISSUE THREAD

**Issue by yanyunchangfeng** [angular/angular#50948]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

git clone this repository ,then using npm i
<img width="758" alt="截屏2023-07-05 21 26 34" src="https://github.com/angular/angular/assets/25072040/678939e1-fb8c-4702-937f-74c0c1e97025">

it should throw Error like package.json engine npm : "Please use yarn instead of NPM to install dependencies"
however it never throw Error

### Please provide the exception or error you saw

```true
install: rely on engines to prevent using npm for dependency install
```

**Comment by JeanMeche** [comment]
Hi, 
This issue is not related to Angular but npm. Please ask these kind of question on Stackoverflow. [This answer](https://stackoverflow.com/a/61911013/884123) might help you.
