### ISSUE TITLE
node v18.10.0 can't prevent using npm install dependencies

### ISSUE THREAD

**Issue by yanyunchangfeng** [angular/angular#50940]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

build: rely on engines to prevent using npm for dependency install #22643

### Please provide the exception or error you saw

```true
git clone this respository then using npm i for node v18.10.0
```

**Comment by JoostK** [comment]
I don't understand. The engine specification requests Node >= 18.10.0, so 18.10 is okay.

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
