### ISSUE TITLE
How to get access to View dependency

### ISSUE THREAD

**Issue by cajoy** [angular/angular#5095]
Currently I am getting access to DOM element by using elementRef

```
constructor(@Inject(ElementRef) elementRef: ElementRef) {
            var autocomplete = UIkit.autocomplete(elementRef.nativeElement, {});
}
```

What looks like not the right way to go.

For 3rd party plugin integration I need to get DOM reference to the component

I think I may be able to get it from dependency such as @View or @Component.

But how can access this dependency from the constructor?

```
constructor() {
var ref = this.View.elementRef;
}
```

**Comment by PascalPrecht** [comment]
@cajoy not sure I can follow. `this` should be the component, whereas `elementRef` is the corresponding DOM element.

**Comment by pkozlowski-opensource** [comment]
Closing as was answered by @PascalPrecht
