### ISSUE TITLE
Interpolation should return undefined instead of null

### ISSUE THREAD

**Issue by alinmateut** [angular/angular#50969]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Interpolation should return undefined instead of null when trying to access a property of an empty object. For the following component
```
@Component({ ... })
export class App {
  o: any;
  obj: any = {};
}
```
the result of `{{o === undefined}}` is true
the result of `{{obj?.x === undefined}}` is true
the result of `{{obj?.x?.y === undefined}}` is false.
(See [stackblitz](https://stackblitz.com/edit/stackblitz-starters-rtrxpo?file=src%2Fmain.ts))

This is completely unintuitive and can cause bugs and console errors. For example, if I have the component
```
<app-fancy-component *ngIf="serverObject?.stuff?.displayFancyComponent !== undefined" [serverObject]=[serverObject] />
```
console errors are thrown when I'm trying to use the interpolation `{{serverObject.stuff.someThings}}` inside the `app-fancy-component`'s template.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-rtrxpo?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"dependencies": {
    "rxjs": "7.8.1",
    "tslib": "2.6.0",
    "zone.js": "0.13.1",
    "@angular/core": "16.1.3",
    "@angular/forms": "16.1.3",
    "@types/jasmine": "4.0.3",
    "@angular/common": "16.1.3",
    "@angular/router": "16.1.3",
    "@angular/compiler": "16.1.3",
    "@angular/animations": "16.1.3",
    "@angular/platform-browser": "16.1.3",
    "@angular/platform-browser-dynamic": "16.1.3"
  }
```

**Comment by JeanMeche** [comment]
Hi, this is a known issue that is tracked at #34385
