### ISSUE TITLE
Compilation error as a result of type missmatch when creating directives in all Angular 15 versions and not Angular 16

### ISSUE THREAD

**Issue by eyoeldefare** [angular/angular#50965]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

This issue seems to be only present in Angular 15 versions (I only tested it in angular 15 versions for now) and not Angular 16. The problem is with the `InputMap` type inside `ɵɵDirectiveDeclaration` type declaration. In Angular 15 versions, this `InputMap` value type is string`{[key: string]: string}` while in Angular 16 versions it can be string or objects like so `{[key: string]: string|{alias: string|null, required: boolean}}`. Now the issue is, it throws compile time error because the data returned as `InputMap` during compilation is mismatched with the expected type of string, because an object is being returned instead of string and Angular 15 versions expect string type for `InputMap` map value. As I see it, the issue can be solved either by changing the `InputMap` type to accept objects like the Angular 16 versions or changing the returned type to comply with `{[key: string]: string}` type for Angular 15 versions.

### Please provide a link to a minimal reproduction of the bug

https://github.com/MurhafSousli/ngx-gallery/issues/563

### Please provide the exception or error you saw

```true
node_modules/ng-gallery/lightbox/lightbox.directive.d.ts:16:84 - error TS2344: Type '{ index: { alias: "lightbox"; required: false; }; id: { alias: "gallery"; required: false; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
Property '"index"' is incompatible with index signature.
Type '{ alias: "lightbox"; required: false; }' is not assignable to type 'string'.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Node: v18.12.1
Package Manager: npm 9.8.0
OS: window x64
Angular/common: "^15.0.0",
Aangular/cli: "~15.0.2",
Angular/core: "^15.0.0"
```

### Anything else?

Now I should note, I was able to solve this issue by tampering with the compiled index.d.ts file. All I had to do was change the `InputMap` type to accept types of {} as well as string. Eg:

`InputMap extends {
    [key: string]: string;
}
` to `InputMap extends {
    [key: string]: string | {};
}
` inside `ɵɵDirectiveDeclaration` type. 

Like I said, Angular 16 doesn't have this issues because InputMap type extended with `[key: string]: string | {}`

**Comment by JoostK** [comment]
Sounds like you're using a library compiled with Angular 16 in an Angular 15 app, which is not supported.

**Comment by eyoeldefare** [comment]
But I am using Angular/core 15

**Comment by eyoeldefare** [comment]
Hey thanks there.
