### ISSUE TITLE
HttpClient with fetch backend triggers too much change detection

### ISSUE THREAD

**Issue by zip-fa** [angular/angular#50979]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

Same request, same response. If you need saved profile or something else just let me know.

<img width="2212" alt="image" src="https://github.com/angular/angular/assets/61551308/21779f9e-bd0f-48f7-aff8-3b30dc0b32ae">
<img width="2216" alt="image" src="https://github.com/angular/angular/assets/61551308/1adc677d-b9e9-4145-9912-bfceb12d6a33">

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.1.3
Node: 20.3.0 (Unsupported)
Package Manager: npm 9.6.7
OS: darwin arm64

Angular: 16.1.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.3
@angular-devkit/build-angular   16.1.3
@angular-devkit/core            16.1.3
@angular-devkit/schematics      16.1.3
@nguniversal/builders           16.1.1
@nguniversal/express-engine     16.1.1
@schematics/angular             16.1.4
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by JeanMeche** [comment]
Hi could you be more specific be providing an reproduction on stacklbitz with the several CD triggered ? Do you use progress report ? 

With a single call, here is what I get. 
![Screenshot 2023-07-09 at 16 03 09](https://github.com/angular/angular/assets/1300985/8b000871-e3a9-48f2-8eb3-327992a1396a)

**Comment by JeanMeche** [comment]
Here is the culprit: 
https://github.com/angular/angular/blob/2b0850331105f72d9128e63dfffbb1d8af883525/packages/common/http/src/fetch.ts#L111-L118

**Comment by zip-fa** [comment]
That was too fast. Thank you.
You didn’t give me a chance to build some basic repro on stackblitz
