### ISSUE TITLE
Error in tests when updating zone.js

### ISSUE THREAD

**Issue by mcfdez** [angular/angular#50997]
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

Yes

### Description

Hello,

I have recently upgraded the zone.js package to version **0.13.1** of my Angular application and several tests that worked with version **0.13** are now throwing this error.

```
Cannot redefine property: isPlatformBrowser
at Function.defineProperty (<anonymous<)
jest.spyOn(fromNgCommon, 'isPlatformBrowser').mockReturnValue(false);
^
```

The test is implemented like this:

```
import * as fromNgCommon from '@angular/common';
jest.spyOn(fromNgCommon, 'isPlatformBrowser').mockReturnValue(false);
```

If we revert the version, the tests work correctly again.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 16.1.3
Node 18.12.1
```

**Comment by JeanMeche** [comment]
Hi, this has been discussed previously. Please take a look at #50756 !
