### ISSUE TITLE
Potential Bug with URL Hash being decoded (Tested on Angular 1.4.2 & 1.4.7)

### ISSUE THREAD

**Issue by dgwaldo** [angular/angular#5099]
After browsing the code and reading http://tools.ietf.org/html/rfc3986#section-2.4 I'm still not sure if this is intended behavior.  This is happening for us in one specific instance where we have Angular  being used by a component on our page.  A 3rd party script sets window.location.hash, and Angular's $locationWatch picks up the url and the url is decoded...  When the 3rd party js script grabs the window.location.hash value, its now decoded and the third party script expects it to be encoded still which creates a bug.  The reason it occurs in this case is that the third party script is splitting on the "/" character, so 942520H PROCAT SE KOHLER CV680 W/52 SIDE DISCHARGE gets encoded to /s/TPI/942502G_PROCAT_26HP_KAW_W%2F%2F61_SIDE_DISCHARGE//1
Angular modifies it to /s/TPI/942502G_PROCAT_26HP_KAW_W//61_SIDE_DISCHARGE//1.  Which is put into json to send over the wire...  So the decoding in the hash breaks that process...

Here is an example setting the window.location.hash = "%27" notice that it gets decoded...

![bug-in-angularjs](https://cloud.githubusercontent.com/assets/7613342/10915874/5a84f580-821e-11e5-8df0-555485426a96.png)

Is this intended behavior and if so why?  
 
From what I could glean from the spec this shouldn't happen... 

 "The characters slash ("/") and question mark ("?") are allowed to
   represent data within the fragment identifier.  Beware that some
   older, erroneous implementations may not handle this data correctly
   when it is used as the base URI for relative references (Section
   5.1)."

**Comment by dgwaldo** [comment]
Additional info:  We also seem to be hitting this line of code...

} else {
      // - reloadLocation is needed as browsers don't allow to read out
      //   the new location.href if a reload happened.
      // - the replacement is a workaround for https://bugzilla.mozilla.org/show_bug.cgi?id=407172
      return reloadLocation || location.href.replace(/%27/g,"'");
    }

**Comment by ericmartinezr** [comment]
This repo is for ng2, are you sure this goes here? I'm asking because AFAIK ng2's router works with ng1 or viceversa.

**Comment by dgwaldo** [comment]
Yah that'd be a no, sorry wrong repo I guess :dizzy_face:

**Comment by ericmartinezr** [comment]
Hahaha, it's fine. This repo is for ng1 https://github.com/angular/angular.js
