### ISSUE TITLE
[transpiler] Output of Dart constructors should be checked

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#510]
Force of habit made me write the following AtScript code:

```
class Foo {
  Foo() {}
}
```

Here I meant to define a `constructor`. ES6 will treat `Foo()` as a method, but in Dart it becomes a constructor. The transpiler should fail when it sees this.

**Comment by mhevery** [comment]
:+1:

**Comment by mhevery** [comment]
Moved to: https://github.com/angular/ts2dart/issues/268
