### ISSUE TITLE
Continuous delivery to npm and pub (per-commit publishing)

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#5100]
In order to be able to test Angular builds quickly and providing hot-fixes outside of scheduled releases we should start publishing Angular 2 to npm and pub after every green master build.

With this change the release will become just a blessing ceremony where a commit is picked and marked as `alpha.xx` and release notes are drafted for the release.

In order for consumers to install the release builds via npm/pub we need to adhere to version scheme that distinguishes non-blessed and blessed builds. I propose that we use semver conventions already used by Angular 1. The convention is as follows:
- each green master build is published as: `2.0.0-build.<TRAVIS_BUILD_ID>+sha.<GIT_SHA>`
- each blessed "release" build is published also as: `2.0.0-alpha.<ALPHA_ID>`

To implement this we will need (at least) the following:
- [ ] store npm/pub credentials as encrypted secrets in travis
- [ ] during a build update package.json and pubspec.yaml with the the per-commit version string
- [ ] setups travis deploy script that deploys artifacts to npm
- [ ] setups travis deploy script that deploys artifacts to pub

While we are at it, we should also consider automating releases. In Angular 1 we use ci.angularjs.org for this. I wonder if we could come up with a way to trigger a release via travis when travis receives an authorized signal to cut a release.

**Comment by yjbanov** [comment]
@munificent, @kevmoo: could you please sanity check this proposal w.r.t. to pub? I'm interested in knowing whether something like this is against pub's philosophy in general, and whether there might be difficulties with implementation of this plan (e.g. authentication from Travis, a cap on number of published versions per day).

Off the top of my head I see one issue - pub lists all versions in a linear fashion ([example](https://pub.dartlang.org/packages/angular2)). This means if we start publishing every SHA the "Versions" tab will become useless as it will contain a lot of noise.

@IgorMinar could you provide more details on rationale? I'm not sure how status quo prevents us from testing Angular builds quickly or provide hot-fixes. Any examples?

**Comment by kevmoo** [comment]
Another option: create an "angular-dart-compiled" org on GitHub and repos for each of the packages.

Then push to each repo on release + tag – with each dependent package pointing to the correct version of its "friends".

You also get the nice benefit of being able to easily see the Dart code deltas between builds – without creating a pile of turds on the pub site.

**Comment by IgorMinar** [comment]
@yjbanov wrt rationale: in order to verify that the published artifacts work correctly, I want to be able to have a few e2e tests that install angular via package managers. this might be more important for npm than for pub, because through npm we deliver not only build artifacts but also typings and transitive dependencies and there is no good way to test those without a proper package.

there are additional reasons for setting this up:
- bisecting angular when looking for a culprit commit will become trivial
- we can use this channel to make hot fixes available outside of a regular release schedule
- we can get feedback/bug reports from external users before a regular release occurs (making this a canary channel)

@kevmoo brought up an interesting alternative to publishing these to npm/pub - both npm/pub support pulling packages from github, so we could setup two repos (js and dart) where we'll push build artifacts. Nice benefit of this is that we can see the diffs on github. Slight downside is that git dependencies are usually slower to install, but it might not be significant.

**Comment by yjbanov** [comment]
@kevmoo, we discussed your idea and decided to try it first. Thanks!

So the plan is:

- create two new repos
  - angular/angular2builds.js
  - angular/angular2builds.dart
- on green full Travis build we commit both TS and Dart code to their respective build repo
- a top-level file `SOURCE_SHA` will contain the SHA in the angular/angular repo from which the build artifacts were produced
- to support pub/npm git dependencies each repo will contain only one package, `angular2`. For now we will continute publishing `benchpress` and `angular2_material` straight to npm/pub.

**Comment by kevmoo** [comment]
@yjbanov Cool!

My idea was a bit more aggressive – create a new GitHub Org with many repos for each package.

But this is a good start. :smile:

**Comment by yjbanov** [comment]
@kevmoo we only have one package, but we might do that once we have more.

**Comment by IgorMinar** [comment]
@yjbanov another thought: rather than creating new repos, we could reuse `angular/angular` and create orphan branches (one for js and one for dart). This way the dependency is going to point back to the right repo and since the tags already contain `build` in the name, it's obvious that these are build artifacts.

Orphan branches will prevent from people pulling this stuff down when casually cloning the repo.

Additional benefit is if someone creates a custom build that they want to share, they can use this setup as a precedence (e.g. `yjbanov/angular#v2.0.0-alpha.50+experimental-di`).

**Comment by yjbanov** [comment]
@IgorMinar using the main repo for this makes me worried about several things:

- operating on our main repository risks ruining it and halting development
- the increased size of the repository that would lead to longer `git clone`s, `git pull`s and `git fetch`es (because git won't be able to reuse any objects)
- discoverability (it takes more knowledge and steps to get the code)
- the fact that the branch contains completely different things from what master contains, leading to cross-pollution when switching branches

What do you mean by "the dependency is going to point back to the right repo"? What would we the wrong repo?

**Comment by munificent** [comment]
+1 for "publishing" these using Git.

There are no technical limitations in pub.dartlang.org prohibiting this, but you will very likely slow down the constraint solver and `pub get` if you have a package with thousands of versions.

If you want to be able to put packages out there but only a very small set of users will consume them, putting them off to the side in Git seems like the right choice for me. It's still very straightforward for users to depend on them and it avoids cluttering up the user experience of most users with a pile of versions they don't care about.

**Comment by IgorMinar** [comment]
This landed as https://github.com/angular/angular/commit/406ace9b251aa99b690037782ebfd72eca87b3d9, but there is a problem. We tag each commit so that it can be fetched by pub/npm using a human-friendly reference, but these tags leak the orphan branch and make the commits participate in git clone/fetch/etc.

I looked briefly but couldn't come up with a way around this in git.

A hacky way would be to use branches rather than tags for human-friendly reference, but I'm not sure what are the consequences of having tens thousands of branches in a repo.

**Comment by PascalPrecht** [comment]
@IgorMinar technically, tags and branches are both just pointers. The only difference is that a branch moves with HEAD if it's checked out (which you all surely know).

So I don't think that it'd make a difference (at least technically). Semantically, tags would surely be better since those are static.

**Comment by IgorMinar** [comment]
@PascalPrecht tags would be better, but they are leaky. The solution with branches would rely on branching off before each new commit.

**Comment by trotyl** [comment]
Obsolete?

**Comment by IgorMinar** [comment]
Yup. Thanks
