### ISSUE TITLE
not getting child route data in router.routerState.snapshot.root;

### ISSUE THREAD

**Issue by belotesagar** [angular/angular#51019]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

below is route from my routing

`// meeting app
  {
    path: 'meetings-landing',
    loadComponent: () => import('./Components/Meetings/meetings-landing/meetings-landing.component').then(m => m.MeetingsLandingComponent),
    data: { breadcrumb: 'Vergaderen', contextType: 'Tenant', isFromOverview: true },
    resolve: { context: ContextResolver },
    children: [
      {
        path: "meetings",
        loadComponent: () => import('./Components/Meetings/meeting-overview/meeting-overview.component').then(m => m.MeetingOverviewComponent),
        data: { breadcrumb: 'Vergaderen', contextType: 'Tenant', isFromOverview: true },
        resolve: { context: ContextResolver },
      },
      //relation meeting details
      {
        path: "relation/meetings/details/#/:id",
        loadComponent: () => import('./Components/Meetings/meeting-details/meeting-details.component').then(m => m.MeetingDetailsComponent),
        canActivate: [RoutePermissionResolver],
        resolve: { vergadering: VergaderingResolver, supplier: SupplierResolver, context: ContextResolver },
        data: { permission: Permission.meetingRead, breadcrumb: 'Vergaderen', contextType: 'Relation', isFromOverview: false, type: 'supplier' }
      },
      //relation meeting edit
      {
        path: "relation/meetings/#/:id",
        loadComponent: () => import('./Components/Meetings/meeting-edit/meeting-edit.component').then(m => m.MeetingEditComponent),
        resolve: { vergadering: VergaderingResolver, supplier: SupplierResolver, context: ContextResolver },
        canActivate: [RoutePermissionResolver],
        data: { permission: Permission.meetingRead, breadcrumb: 'Vergaderen', contextType: 'Relation', isFromOverview: false, type: 'meeting' }
      },

      {
        path: '', redirectTo: '/meetings-landing/meetings', pathMatch: 'full',
      }
    ]
  },` 
  
  I am accessing each route's data in my breadcrumb component to show the breadcrumb as below way
  `
export class BreadCrumbComponent implements OnInit {
constructor(
    private router: Router,
    private activatedRoute: ActivatedRoute,
  ) { }

ngOnInit() {
    this.router.events.pipe(
      filter(event => event instanceof NavigationEnd)
    ).subscribe(() => {
      this.updateBreadcrumb();
    });
  }
 public updateBreadcrumb() {
    this.items = [];

    this.items.push({
      text: "My AddVue",
      title: "My AddVue",
      icon: "fa-sharp fa-solid fa-house fa-sm",
      url: "/"
    })

    const root = this.router.routerState.snapshot.root;

    root.children.forEach(route => {

      const dynamicData = route.data[route.data['type']];

      console.log("route data in breadcrumb ##", route.data);

      console.log("dynamicData in breadcrumb", dynamicData);

      if (route.data["isFromOverview"]) {
        this.currentRoute = this.navigationItemsArray.find(obj => obj.title === "Overview");
        if (this.currentRoute) {
          this.items.push(this.currentRoute);
          this.items = [...this.items];
        }
      }

      if (!route.data["isFromOverview"] && route.data['contextType'] === "Tenant") {
        this.currentRoute = this.navigationItemsArray.find(obj => obj.title === "Admin Console");
        if (this.currentRoute) {
          this.items.push(this.currentRoute);
          this.items = [...this.items];
        }
      }

      if (route.data['contextType'] === "Relation") {
        if (dynamicData?.relation) {
          this.currentRelation = {
            text: dynamicData?.relation.supplierName,
            title: dynamicData?.relation.supplierName,
            icon: 'fa-solid fa-user',
            url: dynamicData?.relation.relationUrl,
            supplierId: dynamicData?.relation.supplierId
          }
        }
        else if (route.data['type'] === 'supplier') {
          this.currentRelation = {
            text: dynamicData?.supplierName,
            title: dynamicData?.supplierName,
            icon: 'fa-solid fa-user',
            url: dynamicData?.relationUrl,
            supplierId: dynamicData?.supplierId
          }
        }
        this.items.push(this.currentRelation);
        this.items = [...this.items];
      }

      if (route.data['contextType'] === "Collaboration") {
        if (route.data['type'] != 'contract') {
          if (dynamicData?.relation) {
            this.currentRelation = {
              text: dynamicData?.relation.supplierName,
              title: dynamicData?.relation.supplierName,
              icon: 'fa-solid fa-user',
              url: dynamicData?.relation.relationUrl,
              supplierId: dynamicData
            }
            this.items.push(this.currentRelation);
            this.items = [...this.items];
          }
          if (!dynamicData?.relation) {
            this.items.push(this.currentRelation);
            this.items = [...this.items];
          }

          if (dynamicData?.collaboration) {
            this.currentCollaboration = {
              text: dynamicData?.collaboration.collaborationName,
              title: dynamicData?.collaboration.collaborationName,
              icon: 'fa-solid fa-bookmark',
              url: dynamicData?.relation.relationUrl,
              collaborationId: dynamicData?.collaboration.contractId
            }
            this.items.push(this.currentCollaboration);
            this.items = [...this.items];
          }
          if (!dynamicData?.collaboration) {
            this.items.push(this.currentCollaboration);
            this.items = [...this.items];
          }
        }
        else if (route.data['type'] === 'contract') {
          this.currentRelation = {
            text: dynamicData?.supplierName,
            title: dynamicData?.supplierName,
            icon: 'fa-solid fa-user',
            url: dynamicData?.relationUrl,
            supplierId: dynamicData
          }
          this.items.push(this.currentRelation);
          this.items = [...this.items];

          this.currentCollaboration = {
            text: dynamicData?.contractName,
            title: dynamicData?.contractName,
            icon: 'fa-solid fa-bookmark',
            url: dynamicData?.collaborationUrl,
            collaborationId: dynamicData?.contractId
          }
          this.items.push(this.currentCollaboration);
          this.items = [...this.items];
        }
      }

      if (route.data["breadcrumb"]) {
        this.currentRoute = this.navigationItemsArray.find(obj => obj.title === route.data["breadcrumb"]);

        if (this.currentRoute) {
          this.items.push(this.currentRoute);
          this.items = [...this.items];
        }
      }

      if (!route.data["breadcrumb"]) {
        let path = route.routeConfig.path.split("/")[0];
        this.currentRoute = this.navigationItemsArray.find(obj => obj.title === path);

        if (this.currentRoute) {
          this.items.push(this.currentRoute);
          this.items = [...this.items];
        }
      }

      // console.log("updated items", this.items);

      localStorage.setItem("currentRelation", JSON.stringify(this.currentRelation));
      localStorage.setItem("currentCollaboration", JSON.stringify(this.currentCollaboration));

    });
  }
}
`
here in  console.log("route data in breadcrumb ##", route.data); getting only child routes data not current routes data.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.8
Node: 16.14.2
Package Manager: npm 8.4.1
OS: win32 x64

Angular: 15.2.9
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.8
@angular-devkit/build-angular   15.2.8
@angular-devkit/core            15.2.8
@angular-devkit/schematics      15.2.8
@angular/cli                    15.2.8
@schematics/angular             15.2.8
rxjs                            7.5.7
typescript
```

### Anything else?

let me know if I am wrong somewhere.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
