### ISSUE TITLE
Docs: call out CanDeactivate breaking change in v15 update guide

### ISSUE THREAD

**Issue by davimiku** [angular/angular#51037]
### Describe the problem that you experienced

The 4th parameter (`nextState`) of CanDeactivate is optional in v14 and required in v15, this is a breaking change and should be called out in the Angular Update Guide.

https://v14.angular.io/api/router/CanDeactivate
https://v15.angular.io/api/router/CanDeactivate

### Enter the URL of the topic with the problem

https://update.angular.io/?l=3&v=14.0-15.0

### Describe what you were looking for in the documentation

One of the items in the Angular Update Guide list to call this out.

### Describe the actions that led you to experience the problem

While updating from v14 to v15, previously compiling code now fails to compile.

**Comment by JoostK** [comment]
For context, this changed as a fix in a patch release in #48038, where it was deemed as a non-breaking change (also determined by the impact on all code in g3).

I suppose you are manually calling into `canDeactivate` from your tests to reveal this change as a new compilation error?

**Comment by davimiku** [comment]
Yeah, any time a public function adds a required parameter or converts an optional parameter to required it is a breaking change, as existing code will now fail to compile.

And yep, we are calling `canDeactivate` (in production code, not tests). I can't say why that's being done because I'm new to this codebase, but I'm just the person assigned to do the v15 upgrade and came across this case.

**Comment by JoostK** [comment]
Yeah I agree with you on this having been a breaking change, I am surprised this didn't raise any problems in g3 back when it was merged (g3 is usually a pretty good indication of how breaking a change would be).

**Comment by JeanMeche** [comment]
I'm going to close it as the breakage seams realy minor and the issue didn't gain any traction.
