### ISSUE TITLE
(custom-event)="handler()" syntax doesn't trigger directive selector

### ISSUE THREAD

**Issue by StacyGay** [angular/angular#5104]
I'm trying to add a custom event to elements using a directive but when an attribute is wrapped in parenthesis "()" the directive isn't bound to the element.
Example:

    @Directive({
        selector: '[animation-listener]',
        events: [
            'listener: animation-listener'
        ],
        host: {
            '(animationend)': 'triggerAnimationEnded()'
        }
    })
    export class AnimationListener {
        listener: EventEmitter = new EventEmitter();
    
        constructor() {
            console.log("listener created");
        }
        
        triggerAnimationEnded(): void {
            console.log("listener triggered");
            this.listener.next(null);
        }
    }
    
	@Component({
		selector: 'demo'
	})
	@View({
		template: `<modal class="fade-in" [modal-title]="modalTitle" 
					[modal-body]="modalBody" 
					[close-text]="closeText" #modal 
					(animation-listener)="log()"></modal>`,
		directives: [ 
			AnimationListener]
	})
	export class DemoComponent {
		log():void{
			console.log('Animation has ended');
		}
	}

Here I'm trying to use (animation-listener) as the directive selector and as the event binding to log().  The directive is not attaching to the modal element.  I could use a different selector from the event attribute, but that isn't as elegant as a single event attribute.

**Comment by Agamnentzar** [comment]
Here's plunker with this issue: http://plnkr.co/edit/VtnEywOTEAKXwWpYWXRy?p=preview
But this one work fine: http://plnkr.co/edit/fXDtQcTQITaCCBx3NQg8?p=preview

**Comment by bennylut** [comment]
Any solution to this one?

**Comment by gdi2290** [comment]
> attribute is wrapped in parenthesis "()"

I'm not sure if you can query for the `()` syntax but if we switch to the `on-` syntax http://plnkr.co/edit/R9474hMJdEdat9IJWiyL?p=preview then it works. the problem is with the selector in the Test component. If it's unable to find the event then it won't decorate it (think of  the selector as `document.querySelector(selector)`

**Comment by vicb** [comment]
It does now
