### ISSUE TITLE
Angular documentation UI is cut off

### ISSUE THREAD

**Issue by fredowashere** [angular/angular#51041]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

![image](https://github.com/angular/angular/assets/117639221/1cbaae45-0aaa-4ca1-a0d3-d4b81a50a89f)

I've tested also with a colleague of mine and it happen on his machine too.

![image](https://github.com/angular/angular/assets/117639221/1074d31f-e92b-4cd5-841e-55a871eeda6a)

As you can see there is text underneath the element.

### Please provide a link to a minimal reproduction of the bug

https://angular.io/guide/reactive-forms

### Please provide the exception or error you saw

```true
Read the description, it should be clear.
```

**Comment by JeanMeche** [comment]
Hi, this is basically the issue described in #45121. 

I'll close this one, we'll be tracking this issue in #45121 !
