### ISSUE TITLE
NullInjectorError: No provider for CurrencyPipe!

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [angular/angular#51057]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Here is closed issue: https://github.com/angular/angular/issues/51056#issuecomment-1637053550
But I ahve added my standalone pipe into component but getting same issue

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.0
Node: 16.15.0
Package Manager: npm 8.5.5
OS: darwin x64

Angular: 15.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0
@angular-devkit/build-angular   15.0.0
@angular-devkit/core            15.0.0
@angular-devkit/schematics      15.0.0
@angular/fire                   7.5.0
@nguniversal/builders           15.1.0
@nguniversal/express-engine     15.0.0
@schematics/angular             15.0.0
rxjs                            7.5.7
typescript                      4.8.2
```

**Comment by JeanMeche** [comment]
Please do not recreate issues even if they have been closed. 

This is pretty much like #51056. 

In your case the work arround is to provide the CurrencyPipe in a module or in the component using your pipe. Either way what your are currently doing with the pipe, is not recommanded.

**Comment by vytautas-pranskunas-** [comment]
hi for sure i would not as soon as i get an aswer :)
I am not using modules thats whole point of standalone components.
So what is teh recommendet way then in order to avoid using remoteConfigService in every place? :)

**Comment by vytautas-pranskunas-** [comment]
ok i used formatCurrency directly

```
export class SenioCurrencyPipe implements PipeTransform {
    constructor(private remoteConfigService: RemoteConfigService, @Inject(LOCALE_ID) private locale: string) {}

    transform(value: any): string | null {
        return value ? formatCurrency(value, this.locale, this.remoteConfigService.settings.currencyCode) + ' ' : '';
    }
}
```

**Comment by JeanMeche** [comment]
Much better ! 👍
