### ISSUE TITLE
[Docs] Backfill CHANGELOG.md with the following BREAKING CHANGES

### ISSUE THREAD

**Issue by evanplaice** [angular/angular#5105]
**2.0.0-alpha.46 (2015-11-11) 7d83959**

This is a rename to make routing concepts easier to understand.

Before:
```
@RouteConfig([
  { path: '/', component: MyCmp, as: 'Home' }
])
```

After:
```
@RouteConfig([
  { path: '/', component: MyCmp, name: 'Home' }
])
```

**2.0.0-alpha.45 (2015-10-29) b87da8f**

The ROUTE_DATA token has been removed and replaced with a type RouteData.

Before:
```
    constructor(routeParams: RouteParams, @Inject(ROUTE_DATA) routeData) {
      let id = routeParams.get('id');
      let name = ROUTE_DATA.name;
    }
```

After:
```
    constructor(routeParams: RouteParams, routeData: RouteData) {
      let id = routeParams.get('id');
      let name = routeData.get('name');
    }
```

The documentation for the following breaking changes are missing from `CHANGELOG.md`. 

**2.0.0-alpha.38 (2015-10-03) 5298eb0**

Constraint added. The Route 'as' parameter should be CamelCase

**2.0.0-alpha.36 (2015-08-31) ccfadb9**

- `routerDirectives` => `ROUTER_DIRECTIVES`
- `routerInjectables` => `ROUTER_BINDINGS`
- `ELEMENT_PROBE_CONFIG` => `ELEMENT_PROBE_BINDINGS`

**2.0.0-alpha.36 (2015-08-31) 3963e0a**

- `HTML5LocationStrategy` -> `PathLocationStrategy`

**Comment by michalstepien** [comment]
Please close, outdated.
