### ISSUE TITLE
Revising the "@angular/platform-webworker" and "@angular/platform-webworker-dynamic" packages deprecation

### ISSUE THREAD

**Issue by PatrikHorvatic** [angular/angular#51053]
### Description

**Hello awesome developers!**

For start you will have to excuse my imprecise english. I was just reading about @angular/platform-webworker deprecated package and it's possiblities. It was an really awesome feature and developers were really happy about it. Why did Angular team decide to deprecate it?

Bootstraping Angular app in web worker could really improve mobile app development experience for developers who use for example: Ionic framework with Angular and Capacitor to bring their code to iOs and Android devices. Implementing some heavy computation code can be really challenging if you have complex logic and interface. Of course, you can use Web Workers and controll change detection with NgZone, but sometimes this is not enough so animations become janky, slow and it ruins UX on slower devices.

In my experience Angular is fast and extremely reliable, but I humbly think it can do better on mobile. Revitalizing those packages or adding simmilar feature would be awesome.

### Proposed solution

Revitalizing @angular/platform-webworker and @angular/platform-webworker-dynamic packages or creating different solution.

### Alternatives considered

Currently not.

**Comment by JeanMeche** [comment]
Hi, the webworker platform was deprecated in v8. You should have a look as the rationnale in https://github.com/angular/angular/commit/ccc76f74988deafb993dff241bf9cbfabb3afe88:

> platform-webworker has been around since the initial release of Angular
> version 2. It began as an experiment to leverage Angular's rendering
> architecture and try something different: to run an entire web application
> in a web worker.
> 
> We've learned a lot from this experiment, and have come to the conclusion
> that pushing entire applications to run in a web worker is not a recipe for
> success for most applications. This is due to a number of unresolved issues,
> including:
> 
> * Poor or non-existent support for web worker APIs in web crawlers/indexers.
> * Poor support in build and bundling tooling.
> 
> As a result, as of Angular version 8, we are deprecating the
> `platform-webworker` APIs in Angular. This consists of both NPM packages,
> `@angular/platform-webworker` and `@angular/platform-webworker-dynamic`.
> 
> Going forward, we will focus our efforts related to web workers around their
> primary use case of offloading CPU-intensive but not critical work.

There is not much to win by running angular in the webworker outside of CPU heavy computations. These are still possible by running non-framework code.
