### ISSUE TITLE
NullInjectorError: No provider for CurrencyPipe!

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [angular/angular#51056]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

While trying to use currencyPipe within standalone pipe got error: "NullInjectorError: No provider for CurrencyPipe!"
```
@Pipe({
    name: 'myCurrency',
    standalone: true,
})
export class MyCurrencyPipe implements PipeTransform {
    constructor(private currencyPipe: CurrencyPipe) {}

    transform(value: any): string | null {
        return value ? this.currencyPipe.transform(value, 'EUR') : '';
    }
}

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.0
Node: 16.15.0
Package Manager: npm 8.5.5
OS: darwin x64

Angular: 15.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0
@angular-devkit/build-angular   15.0.0
@angular-devkit/core            15.0.0
@angular-devkit/schematics      15.0.0
@angular/fire                   7.5.0
@nguniversal/builders           15.1.0
@nguniversal/express-engine     15.0.0
@schematics/angular             15.0.0
rxjs                            7.5.7
typescript                      4.8.2
```

**Comment by JeanMeche** [comment]
You should add `MyCurrencyPipe` in the `imports` of your component. 

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).

**Comment by vytautas-pranskunas-** [comment]
Indeed i did! But still same issue

**Comment by vytautas-pranskunas-** [comment]
![Screenshot 2023-07-16 at 13 23 36](https://github.com/angular/angular/assets/3918999/75f39f81-89f7-49c1-9bba-72a78c61d9c3)
