### ISSUE TITLE
Node v20 compatibility

### ISSUE THREAD

**Issue by crfrolik** [angular/angular#51067]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Node v20 is released and is LTS. Angular should support it.

### Proposed solution

Add "node": ">=20" to "engines" in package.json. Fix any issues that arise due to upgrade.

### Alternatives considered

N/A

**Comment by JoostK** [comment]
Node 20 is not yet LTS, only from 24th October of this year. We will add support for Node 20 in due time, once it has become LTS (likely with Angular 17).
