### ISSUE TITLE
inputs that have a reference variable don't cause change detection

### ISSUE THREAD

**Issue by ronniebarker** [angular/angular#51061]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

If you have an input (say a checkbox): `<input type="checkbox" #myCheckbox>` and then you use that checkbox reference variable in a conditional: `<div *ngIf="myCheckbox.checked">Hello, World</div>` then checking the checkbox (keyboard or mouse) does not cause any change detection so the binding to the div visibility never updates.

Adding any `onClick` (even something that doesn't bind to anything like `onClick="null"` causes change detection to happen and the value binds to the conditional.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.4
Node: 18.16.1
Package Manager: npm 9.5.1
OS: darwin arm64

Angular: 16.1.5
... animations, cdk, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
```

**Comment by JeanMeche** [comment]
This is kind of expected, to understand this you have to dive into how change detection works. 

Angular uses `zone.js` to patch multiple APIs to detect any changes that my happen of the screen. `addEventListener` is one off them. By adding `(click)` you are effectively calling `addEventListener`, which means Angular will detect every click on this input and then fire the change detection. 

Have a look at [this demo](https://danielwiehl.github.io/edu-angular-change-detection/) to understand a bit more have the change detection works in angular !

**Comment by ronniebarker** [comment]
I understand that - but isn't it a bit counter-intuitive to have set up a dependency between a checkbox and a reference variable to not detect the changes? Could there not be an automatic (hidden?) attachment of one of the patches to detect the change? 

Clearly, there has been a change on the screen that hasn't been detected - which, in my opinion, constitutes a failure in the framework to accurately detect the change and run the change detection.

At the very least, there should be something in the reference variable section of the documentation explaining that the binding to an element will not fire change detection without some other patchable API present.

Is It just `addEventListener`? Is there a recommended / better way than an empty `onClick` handler?

**Comment by mlc-mlapis** [comment]
The `onClick` event just invokes the re-checking of the entire tree from top to bottom, and that's why an empty handler is enough. Without such an event (`onClick` or any other), something like the same should be created on the global level as the `document` object.

**Comment by ronniebarker** [comment]
I don't think I realised that any click event causes the whole tree to be checked!

On that demo you sent a link to, I am confused as to why the dirty check colouring (does that represent an `ngDoCkeck()` being called?) manages to make it past an `OnPush` component to it's children. My tests (and, I believe, the documentation) says that it shouldn't propagate that far...

**Comment by JeanMeche** [comment]
The click triggers the same code internally as `markForCheck()`. This means every non-onpush component + every marked component will run CD.
