### ISSUE TITLE
feature request: Dynamic Language Translation Support using JSON

### ISSUE THREAD

**Issue by giosueDelgado** [angular/angular#51065]
### Description

Currently, Angular does not natively support dynamic language translations using a simple JSON file. To achieve such functionality, developers have to rely on external libraries such as ngx-translate or transloco.

We could argue that if libraries such as transloco and ngx-translate were not necessary, they wouldn't have achieved such success. This is indicative of the need for this feature in the Angular ecosystem.

### Proposed solution

I propose that Angular introduces a feature for dynamic language translations using simple JSON files. This could greatly simplify the process for developers and remove the need for external libraries. The feature should also allow developers to dynamically switch between languages at runtime.

### Alternatives considered

Right now, developers have to use external libraries such as ngx-translate or transloco for this functionality. While these libraries do provide the desired feature, they also introduce additional dependencies to projects and potentially increase the bundle size. Having this feature natively supported by Angular could result in a cleaner and more efficient solution.

**Comment by zip-fa** [comment]
No, please. Just use ngx-translate or transloco.
Angular's i18n is about performance and flicker-free rendering

**Comment by JeanMeche** [comment]
Hi, I'll close this as it's almost the same as #45467.

**Comment by giosueDelgado** [comment]
Ok, @JeanMeche  thanks.

In response to you @zip-fa I don't think is the correct way to use third libraries just because angular does not provide a fully needed feature.
In 90% percent of my work, the angular projects that I see use ngx-translate or transloco so I think something is missing in the angular i18n.

**Comment by zip-fa** [comment]
> Ok, @JeanMeche thanks.
> 
> In response to you @zip-fa I don't think is the correct way to use third libraries just because angular does not provide a fully needed feature. In 90% percent of my work, the angular projects that I see use ngx-translate or transloco so I think something is missing in the angular i18n.

Making angular all-in-one framework for every possible use is not a good choice i think. Angular’s team must concentrate on something bigger, like reactivity & performance, than making these changes to load json translations

**Comment by giosueDelgado** [comment]
Nono sure I agree with you but if the major people that I see replace the i18n structure (that is provided from angular) I think we can think about if is correct or no managed in this way :)
