### ISSUE TITLE
Broken Links in HTTP documentation

### ISSUE THREAD

**Issue by RumbleballTheReal** [angular/angular#51066]
### Describe the problem that you experienced

Broken Links

### Enter the URL of the topic with the problem

https://angular.io/guide/http-setup-server-communication

### Describe what you were looking for in the documentation

![image](https://github.com/angular/angular/assets/41473331/72c32a26-9155-460d-8e9c-443d9e9d0a07)
These links are broken

### Describe the actions that led you to experience the problem

Clicking the links

### Describe what you want to experience that would fix the problem

Working Links

**Comment by JeanMeche** [comment]
There is already a PR for this #51063 !
