### ISSUE TITLE
right-hand side of 'instanceof' is not an object after updating to angular 16

### ISSUE THREAD

**Issue by ahmadallw** [angular/angular#51072]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

After updating the project from angular 15 to angular 16 the following error appears without changing anything in the code

`right-hand side of 'instanceof' is not an object`

This error appears when running `ng build` only & it works normally  if we run `ng serve` 

package.json
`{
  "name": "project-name",
  "sideEffects": false,
  "version": "1.0.0",
  "scripts": {
    "ng": "ng",
    "start": "node dist/ta-web-app/server/main.js"
  },
  "main": "dist/ta-web-app/server/index.js",
  "private": true,
  "dependencies": {
    "@angular-eslint/schematics": "^16.1.0",
    "@angular/animations": "^16.1.5",
    "@angular/cdk": "^16.1.5",
    "@angular/common": "^16.1.5",
    "@angular/compiler": "^16.1.5",
    "@angular/core": "^16.1.5",
    "@angular/fire": "^7.5.0",
    "@angular/forms": "^16.1.5",
    "@angular/material": "^16.1.5",
    "@angular/material-date-fns-adapter": "^16.1.5",
    "@angular/platform-browser": "^16.1.5",
    "@angular/platform-browser-dynamic": "^16.1.5",
    "@angular/platform-server": "^16.1.5",
    "@angular/router": "^16.1.5",
    "@googlemaps/js-api-loader": "^1.13.2",
    "@iplab/ngx-file-upload": "^16.0.1",
    "@mediapipe/face_mesh": "^0.4.1633559619",
    "@ng-select/ng-select": "^11.0.0",
    "@ngrx/effects": "^16.1.0",
    "@ngrx/store": "^16.1.0",
    "@ngrx/store-devtools": "^16.1.0",
    "@nguniversal/builders": "^16.1.1",
    "@nguniversal/express-engine": "^16.1.1",
    "@ngx-translate/core": "^15.0.0",
    "@ngx-translate/http-loader": "^8.0.0",
    "@stripe/stripe-js": "^1.54.1",
    "@types/google.maps": "^3.47.2",
    "@typescript-eslint/eslint-plugin": "^5.59.2",
    "@typescript-eslint/parser": "^5.59.2",
    "angularx-qrcode": "^16.0.0",
    "compression": "^1.7.4",
    "cookie-parser": "^1.4.6",
    "date-fns": "^2.30.0",
    "dayjs": "^1.11.4",
    "domino": "^2.1.6",
    "express": "^4.15.2",
    "firebase-admin": "^11.7.0",
    "flag-icons": "^6.0.1",
    "libphonenumber-js": "^1.9.44",
    "lodash-es": "^4.17.21",
    "ngrx-store-localstorage": "^16.0.0",
    "ngx-stripe": "^16.1.2",
    "prompts": "^2.4.2",
    "quill-delta-to-html": "^0.12.1",
    "rxjs": "~7.8.0",
    "smartbanner.js": "^1.19.0",
    "source-map-explorer": "^2.5.2",
    "swiper": "^7.3.1",
    "ts-node": "^10.8.1",
    "tslib": "^2.3.0",
    "webpack": "^5.76.0",
    "zone.js": "^0.13.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.1.4",
    "@angular-eslint/builder": "^16.1.0",
    "@angular-eslint/eslint-plugin": "^16.1.0",
    "@angular-eslint/eslint-plugin-template": "^16.1.0",
    "@angular-eslint/template-parser": "^16.1.0",
    "@angular/cli": "^16.1.4",
    "@angular/compiler-cli": "^16.1.5",
    "@nrwl/angular": "^16.5.2",
    "@types/compression": "^1.7.2",
    "@types/cookie-parser": "^1.4.3",
    "@types/estree": "^1.0.0",
    "@types/express": "^4.17.0",
    "@types/fs-extra": "^9.0.13",
    "@types/jasmine": "~3.10.0",
    "@types/lodash-es": "^4.17.6",
    "@types/md5": "^2.3.2",
    "@types/node": "^16.11.7",
    "@types/node-fetch": "^2.6.2",
    "@types/prompts": "^2.0.14",
    "eslint": "^8.39.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-html": "^6.2.0",
    "eslint-plugin-import": "^2.25.3",
    "eslint-plugin-jsdoc": "^37.0.3",
    "eslint-plugin-prefer-arrow": "^1.2.3",
    "eslint-plugin-prettier": "^4.0.0",
    "first-input-delay": "^0.1.3",
    "fs-extra": "^10.0.0",
    "git-commit-count": "^1.1.3",
    "jasmine-core": "~3.10.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "karma-sonarqube-unit-reporter": "^0.0.23",
    "md5": "^2.3.0",
    "prettier": "^2.4.1",
    "typescript": "~5.1.3"
  },
  "browser": {
    "path": false,
    "fs": false
  }
}
`

We not able to find were is the issue & why does it appear just after update from angular 15 to 16

Any idea how can we find a solution for this issue?

**Comment by JeanMeche** [comment]
Hi, this issue is being track on the CLI repo : angular/angular-cli#25529
