### ISSUE TITLE
lifecycle event should works if we create component as Embedded View Instead of HostView

### ISSUE THREAD

**Issue by harshpatel147** [angular/angular#51083]
```
[ ] Regression
[ ] Bug report
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
```

### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Feature Request: Support for Lifecycle Events in Dynamically Loaded Components as Embedded Views

Dear Angular Core Module Developer Community,

I would like to request enhanced support for lifecycle events in dynamically loaded components when they are used as embedded views. Currently, Angular provides ways to dynamically load components using ViewContainerRef and ComponentFactoryResolver, but lifecycle events such as ngOnInit, ngAfterViewInit, and ngOnDestroy are not automatically triggered for these dynamically loaded components when used as embedded views.

As per [this issue](https://github.com/angular/angular/issues/18877), many people have requested a feature to enable creating components without its host wrapper tag also (embedded view). However, from 2017 to the current year 2023, this feature has not been provided by the Angular development community.

I understand that Angular's current behavior aligns with its design principles and that lifecycle events are meant to be triggered for components created declaratively in the template. However, there are use cases where dynamically loaded components as embedded views are necessary, such as in a Page Builder project or when fully dynamic components with flexbox properties need to be created.

As an example, let's consider a Page Builder project where users can drag and drop elements and enable flexbox properties through input fields. To take advantage of flexbox properties, the components need to be dynamically loaded as embedded views. However, the lack of lifecycle event support in embedded views poses challenges. For instance, @HostBinding and @HostListener decorators do not work with embedded views. This requires developers to resort to alternative approaches like manually adding event listeners or manipulating classes and attributes using pure JavaScript (e.g., Renderer2 or element.classList).

Furthermore, the absence of lifecycle event support hinders the proper initialization and view initialization of dynamically loaded components as embedded views. This means that ngOnInit and ngAfterViewInit are not fired, preventing the execution of necessary initialization code or interaction with the component's view.

Here is an example of a directive called DynamicComponentLoaderDirective that illustrates the current workaround for dynamically loading components as embedded views:

```
import { ComponentFactoryResolver, ComponentRef, Directive, Injector, Input, OnInit, Type, ViewContainerRef } from '@angular/core';

@Directive({
  selector: '[appDynamicComponentLoader]'
})
export class DynamicComponentLoaderDirective implements OnInit {
  @Input() type!: Type<any>;
  componentRef!: ComponentRef<any>;

 constructor(private componentFactoryResolver: ComponentFactoryResolver, private viewContainerRef: ViewContainerRef, private injector: Injector) { }

  ngOnInit(): void {
    this.loadComponent();
  }

  loadComponent() {
     const componentFactory = this.componentFactoryResolver.resolveComponentFactory(this.type);
    if (componentFactory) {
      // this.componentRef = this.viewContainerRef.createComponent(componentFactory); // create component & inserts its host view into this container
      this.componentRef = componentFactory.create(this.injector); // create component.
      // this.componentRef.instance.elementData = this.data;

      if (this.componentRef.instance.childComponentTemplateRef) {
        this.viewContainerRef.createEmbeddedView(this.componentRef.instance.childComponentTemplateRef);
      }
    }

  }
}

```

& use this directive in html for dynamically component load as embedded view

`
          <ng-template [type]="componentType" [data]="elmData" appDynamicComponentLoader>
        </ng-template>
`

To see this workaround in action, you can visit [the following StackBlitz link: Angular Dynamic Component as EmbeddedView Example](https://stackblitz.com/edit/angular-version-hhnrtf?devToolsHeight=33&file=src%2Fapp%2FpageBuild%2Fdirectives%2Fdynamic-component-loader.directive.ts)

Hence, I kindly request the Angular Core Module Developer Community to consider providing support for lifecycle events, at the very least for ngOnInit, ngAfterViewInit, and ngOnDestroy, in components loaded as embedded views. This enhancement would greatly improve the flexibility and usability of Angular in scenarios that require dynamic component loading and manipulation of flexbox properties.

I currently use Angular version 12, but I urge you to consider implementing this lifecycle event support in future versions.

Thank you for your attention to this feature request. I appreciate the hard work and dedication of the Angular team and the community in continuously improving the framework.

### Proposed solution

In that case, if you need to load components as embedded views and still have access to Angular lifecycle events, one possible approach is to create a custom implementation for triggering these lifecycle events manually.

You can define a separate interface or base class that includes the necessary lifecycle methods (`ngOnInit`, `ngAfterViewInit`, etc.). Then, when dynamically creating the component as an embedded view, you can instantiate it using this custom interface or base class and manually invoke the corresponding lifecycle methods.

Here's an example of how you can modify the `DynamicComponentLoaderDirective` to implement this approach:

```typescript
import { ComponentFactoryResolver, ComponentRef, Directive, Input, OnInit, Type, ViewContainerRef } from '@angular/core';
import { CustomLifecycleEvents } from './custom-lifecycle-events';

@Directive({
  selector: '[appDynamicComponentLoader]'
})
export class DynamicComponentLoaderDirective implements OnInit {
  @Input() type!: Type<any>;
  componentRef!: ComponentRef<any>;

  constructor(private componentFactoryResolver: ComponentFactoryResolver, private viewContainerRef: ViewContainerRef) { }

  ngOnInit(): void {
    this.loadComponent();
  }

  loadComponent() {
    const componentFactory = this.componentFactoryResolver.resolveComponentFactory(this.type);
    if (componentFactory) {
      this.componentRef = this.viewContainerRef.createComponent(componentFactory);
      const componentInstance = this.componentRef.instance as CustomLifecycleEvents;
      if (componentInstance && componentInstance.ngOnInit) {
        componentInstance.ngOnInit();
      }
      if (componentInstance && componentInstance.ngAfterViewInit) {
        componentInstance.ngAfterViewInit();
      }
    }
  }
}
```

In this example, `CustomLifecycleEvents` is an interface or base class that defines the necessary lifecycle methods. You should replace `CustomLifecycleEvents` with the appropriate name in your implementation.

By casting the component instance to `CustomLifecycleEvents`, you can invoke the lifecycle methods if they exist in the loaded component. This way, you can manually trigger the lifecycle events and ensure that the necessary initialization and view-related logic is executed.

Please note that this is a workaround solution and may require additional customization based on your specific requirements. It's important to carefully test and verify the behavior of the dynamically loaded components with the manually triggered lifecycle events.

I hope this updated solution provides a possible approach to address the issue of Angular lifecycle events not working when loading components as embedded views.

### Alternatives considered

Using HostView instead of EmbeddedView: Angular recommends using HostView for components rather than EmbeddedView. In this approach, components are loaded using createComponent without using createEmbeddedView. This allows the components to participate in the regular Angular lifecycle and have access to the lifecycle events. However, this approach introduces a host wrapper tag in the DOM structure, which may not be desirable in some scenarios, such as when aiming for a more streamlined and simplified DOM structure.

otherwise, please provide support of Life cycle event for component which is loaded as Embedded View.

**Comment by ajay-jadav** [comment]
We want featured option related to load the component as embedded view Please provide this feature as soon as possible.

**Comment by garrettld** [comment]
I'm fairly certain this has come up in a feature request or bug report before, but I can't find it. I did find this somewhat-related feature request that was declined: https://github.com/angular/angular/issues/18877.

You may be able to accomplish your goals today by leveraging attribute selectors. For example:

```typescript
@Component({ selector: 'app-label', template: `<ng-template><label>{{ content }}</label></ng-template>` })
export class LabelCmp { ... }
```
vs
```typescript
@Component({ selector: 'label[app-label]', template: `{{ content }}` })
export class LabelCmp { ... }
```

This strategy checks all the boxes -- host bindings & listeners work normally, lifecycle events work, you get the semantic markup you need, and there's no requirement to use the renderer API. I've simplified and reworked your StackBlitz to show an example of this approach here: https://stackblitz.com/edit/angular-version-dhncdb?file=src%2Fapp%2FpageBuild%2Fdirectives%2Fdynamic-component-loader.directive.ts,src%2Fapp%2FpageBuild%2Fcomponents%2Flabel%2Flabel.component.ts

There are a couple of caveats:

1. This strategy breaks down if you have multiple root elements in a single view that you want to render (e.g., a `<label>` and an `<input>` together in one dynamic component). Based on the description of your use case it seems like this may not be a problem? Usually this level of coupling means they should be styled together, and you'll want a wrapper element for that anyway.
2. While playing around with this I noticed that the styles weren't being applied at first. The version of Angular that your StackBlitz is on apparently doesn't support camelCase property names in a `[style]` binding without Ivy? Enabling Ivy or updating to a supported version of Angular fixes that issue.

I hope this helps!

**Comment by harshpatel147** [comment]
> I'm fairly certain this has come up in a feature request or bug report before, but I can't find it. I did find this somewhat-related feature request that was declined: #18877.
> 
> You may be able to accomplish your goals today by leveraging attribute selectors. For example:
> 
> ```ts
> @Component({ selector: 'app-label', template: `<ng-template><label>{{ content }}</label></ng-template>` })
> export class LabelCmp { ... }
> ```
> 
> vs
> 
> ```ts
> @Component({ selector: 'label[app-label]', template: `{{ content }}` })
> export class LabelCmp { ... }
> ```
> 
> This strategy checks all the boxes -- host bindings & listeners work normally, lifecycle events work, you get the semantic markup you need, and there's no requirement to use the renderer API. I've simplified and reworked your StackBlitz to show an example of this approach here: https://stackblitz.com/edit/angular-version-dhncdb?file=src%2Fapp%2FpageBuild%2Fdirectives%2Fdynamic-component-loader.directive.ts,src%2Fapp%2FpageBuild%2Fcomponents%2Flabel%2Flabel.component.ts
> 
> There are a couple of caveats:
> 
> 1. This strategy breaks down if you have multiple root elements in a single view that you want to render (e.g., a `<label>` and an `<input>` together in one dynamic component). Based on the description of your use case it seems like this may not be a problem? Usually this level of coupling means they should be styled together, and you'll want a wrapper element for that anyway.
> 2. While playing around with this I noticed that the styles weren't being applied at first. Angular v.12.2.17 apparently doesn't support camelCase property names in a `[style]` binding without Ivy? Enabling Ivy or updating to a supported version of Angular fixes that issue.
> 
> I hope this helps!

hey @garrettld thank you for your time & replying to me. I looked your change & your StackBlitz example. & then I tried it but there are may be some issues. [See this new stackblitz example](https://stackblitz.com/edit/angular-version-gybjed?devToolsHeight=33&file=src%2Fapp%2FpageBuild%2Fcomponents%2Fpage-container%2Fpage-container.component.ts) . in this example I tried your way which one suggected by you. by using your way this will make template's first element as a Host Tag instead of separate host wrapper tag. but in my example url, there are facing style appling issue from dynamic style object data. 

& I have another Query in your suggestion. 
for example currentyle I have template html content as like below

```
<ng-template #childComponentTemplateRef>
<label 
    appSelectable
    appDropable 
    [eleData]="eleData" 
    [parentEleData]="parentEleData" 
    [ngStyle]="elementData?.style?.computedStyle | jsonStrParse">
    {{ elementData?.config?.text }}
</label>
<ng-template>
```
& you suggest me 
``` 
@Component({ selector: 'label[app-label]', template: `{{ content }}` })
```
as per your suggesting <label app-lable> tag will be host tag. 
but my query is if I made my template's first element as a Host Tag then how can I apply Directive and Pipe to that first host element?

**Comment by harshpatel147** [comment]
> I'm fairly certain this has come up in a feature request or bug report before, but I can't find it. I did find this somewhat-related feature request that was declined: #18877.
> 
> You may be able to accomplish your goals today by leveraging attribute selectors. For example:
> 
> ```ts
> @Component({ selector: 'app-label', template: `<ng-template><label>{{ content }}</label></ng-template>` })
> export class LabelCmp { ... }
> ```
> 
> vs
> 
> ```ts
> @Component({ selector: 'label[app-label]', template: `{{ content }}` })
> export class LabelCmp { ... }
> ```
> 
> This strategy checks all the boxes -- host bindings & listeners work normally, lifecycle events work, you get the semantic markup you need, and there's no requirement to use the renderer API. I've simplified and reworked your StackBlitz to show an example of this approach here: https://stackblitz.com/edit/angular-version-dhncdb?file=src%2Fapp%2FpageBuild%2Fdirectives%2Fdynamic-component-loader.directive.ts,src%2Fapp%2FpageBuild%2Fcomponents%2Flabel%2Flabel.component.ts
> 
> There are a couple of caveats:
> 
> 1. This strategy breaks down if you have multiple root elements in a single view that you want to render (e.g., a `<label>` and an `<input>` together in one dynamic component). Based on the description of your use case it seems like this may not be a problem? Usually this level of coupling means they should be styled together, and you'll want a wrapper element for that anyway.
> 2. While playing around with this I noticed that the styles weren't being applied at first. Angular v.12.2.17 apparently doesn't support camelCase property names in a `[style]` binding without Ivy? Enabling Ivy or updating to a supported version of Angular fixes that issue.
> 
> I hope this helps!

hey @garrettld  Bro. I tested your answer. but I have one query about the directives. how can I apply the Custom Directive to Host element?

for e.g. current we have template  `@Component({ selector: 'app-label', template: `</ng-template><label appSelectable [elemData]="elemData"></label></ng-template>` })`   now If I use as like `@Component({ selector: 'label[app-label]', template: `{{ content }}`,   host: { '[style]': 'eleData?.style' } })` then how can I apply Directive to the Host Element (Label Element)?

**Comment by JeanMeche** [comment]
@harshpatel147 You can set `hostDirectives` in the decorator since v15 !

**Comment by harshpatel147** [comment]
> @harshpatel147 You can set `hostDirectives` in the decorator since v15 !

[as per angular doc](url) Directives used in hostDirectives must be standalone: true. please read my issue you can test it on stackbliz which is i given in PR description

**Comment by alxhub** [comment]
I think the description here is a bit misleading - this has nothing to do with embedded views, really. Instead, the problem in the example is that when the component instance is created via `componentFactory.create(...)`, its `hostView` is never attached to the change detection tree. The host view is responsible for running the lifecycle of the component itself.

```typescript
loadComponent() {
   const componentFactory = this.componentFactoryResolver.resolveComponentFactory(this.type);
  if (componentFactory) {
    this.componentRef = componentFactory.create(this.injector); // create component.

    // Attach the host view of the component to the main change detection tree, so that its lifecycle
    // hooks will run.
    this.applicationRef.attachView(this.componentRef.hostView);

    this.componentRef.instance.elementData = this.data;

    if (this.componentRef.instance.childComponentTemplateRef) {
      this.viewContainerRef.createEmbeddedView(this.componentRef.instance.childComponentTemplateRef);
    }
  }
}
```

**Comment by alxhub** [comment]
Closing as I believe my comment above is the right fix - lifecycle events work when the host view is attached to the change detection tree.
