### ISSUE TITLE
Use Universal for angular.io

### ISSUE THREAD

**Issue by BenLune** [angular/angular#51084]
### Describe the problem that you experienced

Angular.io is the core doc and showcase place to explain what Angular is.
It is built with Angular, great.
But why don't we have an Angular Universal version? SSR/SSG is part of web best practices and Angular.io doesn't have it.
It would be great to get it, to 1. as a best practice for itself, 2. as an example for developers who get difficulties to make it work.

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
