### ISSUE TITLE
Vulnerable dependencies (indirect security issues ??) 

### ISSUE THREAD

**Issue by RahatFatimah** [angular/angular#51080]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Hello maintainers,

I wanted to bring to your attention that after installing the package, I ran a vulnerability scan with vulert abom on the lock file and discovered that there are over 15 vulnerable dependencies present. As these vulnerabilities can potentially impact the security of the entire project, I am unsure whether to report this under responsible disclosure.

For your reference, here is a link to the report of the package-lock file I scanned: https://vulert.com/vuln-scan/list/a149f3bc-5d76-452e-ae70-68f40d385bfd

I recommend that we take immediate action to address these vulnerabilities and ensure the security of the project. Please let me know if you require any further information.

P.S. this is the lock file i scanned: https://github.com/angular/angular/blob/main/yarn.lock

Thank you.

**Comment by AndrewKushnir** [comment]
// cc @josephperrott

**Comment by JeanMeche** [comment]
About the [`vm2` vulnerability](https://github.com/advisories/GHSA-cchq-frgv-rjh5) : 

We have several deps pulling it : 
* FW : 
```
├─┬ firebase-tools@12.4.0
│ └─┬ proxy-agent@5.0.0
│   └─┬ pac-proxy-agent@5.0.0
│     └─┬ pac-resolver@5.0.1
│       └─┬ degenerator@3.0.4
│         └── vm2@3.9.19
└─┬ karma-sauce-launcher@4.3.6
  └─┬ webdriverio@6.12.1
    └─┬ @types/puppeteer-core@5.4.0
      └─┬ @types/puppeteer@7.0.4
        └─┬ puppeteer@20.7.3
          └─┬ @puppeteer/browsers@1.4.2
            └─┬ proxy-agent@6.2.1
              └─┬ pac-proxy-agent@6.0.3
                └─┬ pac-resolver@6.0.1
                  └─┬ degenerator@4.0.3
                    └── vm2@3.9.19 deduped
```
AIO:
```
├─┬ firebase-tools@12.4.0
│ └─┬ proxy-agent@5.0.0
│   └─┬ pac-proxy-agent@5.0.0
│     └─┬ pac-resolver@5.0.1
│       └─┬ degenerator@3.0.4
│         └── vm2@3.9.19
└─┬ puppeteer-core@20.7.3
  └─┬ @puppeteer/browsers@1.4.2
    └─┬ proxy-agent@6.2.1
      └─┬ pac-proxy-agent@6.0.3
        └─┬ pac-resolver@6.0.1
          └─┬ degenerator@4.0.3
            └── vm2@3.9.19 deduped
```

* For Firebase I've opened an issue : firebase/firebase-tools#6150
* For Puppeteer a local PR : angular/angular#51086

**Comment by JeanMeche** [comment]
I propose that we can close this issue once both PR fixing the `vm2` deps are merged. 

The `loader-utils` issue is older and less of an issue.

**Comment by JeanMeche** [comment]
I propose that we can close this issue once both PR fixing the `vm2` deps are merged. 

The `loader-utils` issue is older and less of an issue.
