### ISSUE TITLE
Directives: [style.height.px]="contentHeight" leaves a value even if contentHeight is nulled

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#5110]
Assume the following template:

```html
<div [style.height.px]="contentHeight"></div>
```

When `contentHeight` is `100`:

```html
<div style="height: 100px"></div>
```

When `contentHeight` is `0`:

```html
<div style="height: 0px"></div>
```

*However*, when `contentHeight` transitions from a non-null value to null/undefined...

Expected:

```html
<div style=""></div>
```

Actual:

```html
<!-- Either 0 or whatever the previous value was -->
<div style="height: 0px"></div>
```

@vsavkin Is this possibly CD related?

Workaround is to use `[style.height]` and manage your own String.

**Comment by matanlurey** [comment]
It looks like this also occurs actually without the magical `[.px]` sugar, but you do have an option to make the String `''`, which is the workaround today.

**Comment by pkozlowski-opensource** [comment]
@matanlurey @tbosch sent a PR for this (#5114), please review

**Comment by tbosch** [comment]
LGTM, marked the PR for merge.

**Comment by matanlurey** [comment]
@pkozlowski-opensource wow thanks for the fast change, I appreciate it!

**Comment by todoubaba** [comment]
@pkozlowski-opensource [`class`] has the same issue, should be removed when exp is `null` or `undefined`.
```typescript
@Component({
  selector: 'my-app',
  styles: ['.c {color: red}'],
  template: `
  <h1 [class]="v1">v1</h1>
  <h1 [class]="v2">v2</h1>
  <h1 [class]="v3">v3</h1>`
})
export class MyApp {
  v1: string = "c";
  v2: string = null;
  v3: string;
}

bootstrap(MyApp);
```
Generated HTML:
```html
<h1 class="c">v1</h1>
<h1 class="null">v2</h1>
<h1 class="undefined">v3</h1>
```

**Comment by pkozlowski-opensource** [comment]
@todoubaba this is sth entirely different. The comparable syntax would be `[class.foo]="null"` which AFAIK works correctly.

What you are raising here is binding to the `className` property, so equivalent of:

```javascript
var myDiv = document.createElement('div');
myDiv.className = null;
```

which produces `<div class="null"></div>` (at least in Chrome). So this is not Angular really, but a browser doing type casting / conversion.

Feel free to open a separate issue for this, but it is disputable is we should be fixing this.

**Comment by todoubaba** [comment]
@pkozlowski-opensource I think they are different, `[class.foo]` can only be assigned a boolean value. User cannot provide a dynamic class name by `[class.foo]`.

BTW, if the exp is a array, the behaviour seems inconsistent, `null` array element will be evlauted to nothing.
```typescript
<h1 [class]="[v1, v2]">v1</h1>
```
Generated HTML:
```
<h1 class="c,">v2</h1>
```

**Comment by pkozlowski-opensource** [comment]
@todoubaba there is no point of continuing this discussion in a closed issue. You are discussing different code path so this is not related to this issue here.

If you believe that there is sth to fix here please open a new issue.
