### ISSUE TITLE
Massive delays with Template XHR in Mobile Safari when there are images

### ISSUE THREAD

**Issue by wlingke** [angular/angular#5112]
I have to preface this with the fact that this is a very weird issue but it could be affecting a large number of apps.

The issue is in Mobile Safari (latest version though could be affecting other versions), template XHR calls (such as those from ng-include) are somehow delayed by a significant time when there are multiple images from the same origin on the page. To rephrase - ng-include and other directives that use `templateUrl` do not load the HTML for many seconds when loaded alongside multiple images from the same source in mobile safari. To make it worse, this behavior is not consistent. It happens sometimes and not other times. I am also not sure how many images are needed for this issue to occur. I've noticed that with fewer (like 3-4) images, I do not see this issue.

I am fairly sure this is not a server issue. I use NodeJS and put up a very standard and basic server and I am able to see that my server is responding to requests immediately. In the dev console, I see that the HTML is downloaded in a short amount of time but for some reason that download process doesn't being for a long time. Additionally, in all other browsers (including mobile chrome and desktop safari), everything works normally. It leads me to think this is a front end and not back end issue.

I have attempted to replicate this issue. Here are some examples:
1) http://ovidlife-staging.herokuapp.com - this page is a bare bones example of the issue. It includes latest angularjs script, a bunch of images from the same origin, and one ng-include. (the page takes a few moments to load because its on a free heroku server which needs spinup time). Now remember what I said about this not being consistent. You may have to refresh a few times - I am usually able to replicate it after 1-3 refreshes but sometimes it takes up to 10.

2) http://ovidlife-staging.herokuapp.com/index2 - this is the same page except the images are loaded from a different origin. Note that there is NO PROBLEM on this page no matter how many times you refresh.

3) www.ovidlife.com - this is our main site. You can also see that the issue from 1) also occurs here (note the nav bar does not appear because it uses `templateUrl` for a good 30 seconds)

Sorry I'm unable to make a plunkr or codepen to show this example because of the issue related to serving the images from the same origin. You may have to write a simple server to really be able to reproduce this problem.

**Comment by pkozlowski-opensource** [comment]
Wrong repo, I guess you are looking for https://github.com/angular/angular.js

Having said this it more looks like you are hitting a limit of parallel downloads from a given server (browsers limit those). I would be very surprised if this turns out AngularJS issue - have you tried to reproduce this pb with vanilla HTML + JS (XHR)? I would expect the same pb to occur.

**Comment by wlingke** [comment]
apologies - thanks for the tip
