### ISSUE TITLE
Template unit test coverage

### ISSUE THREAD

**Issue by ice-blaze** [angular/angular#51130]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

It would be nice to see the coverage also for the templates (`.html`). Sometimes components typescript are empty and all the business logic exist only in the html file.

### Proposed solution

Test coverage should say 50% branch coverage for this kind of template

```Typescript
@Component({
  selector: 'ng-if-simple',
  template: `
    <div *ngIf="show === true">First 50% code coverage</div>
    <br>
    <div *ngIf="show === false">Last 50% code coverage</div>
`
})
export class NgIfSimple {
  show = true;
}
```

### Alternatives considered

Maybe the problem lies in Jest or Istanbul. The idea of this feature proposal is to see if someone in the community has an idea of where is best to start this feature, maybe it doesn't lie in angular's hands.

**Comment by JoostK** [comment]
Please find your issue in the CLI repo: angular/angular-cli#25563
