### ISSUE TITLE
Error in doc about ViewChild 

### ISSUE THREAD

**Issue by qmarquez** [angular/angular#51142]
### Describe the problem that you experienced

The documentation about [ViewChild](https://angular.io/api/core/ViewChild#usage-notes), let it clear about when the viewchild it's available, in the AfterViewInit method. But in the example about [Dinamyc Components](https://angular.io/guide/dynamic-component-loader) the ViewChild it's used in the [ngOnInit method](https://github.com/angular/angular/blob/4120a0380589aba48d0867f35a9937c07a8ee3b9/aio/content/examples/dynamic-component-loader/src/app/ad-banner.component.ts#L25-L32) and in the code example works perfectly but don't exaplain why or how.

### Describe what you were looking for in the documentation

Inconsistencies

### Describe the actions that led you to experience the problem

Just read the docs

### Describe what you want to experience that would fix the problem

The documentation about ViewChild be consistent

### Add a screenshot if that helps illustrate the problem

<img width="526" alt="image" src="https://github.com/angular/angular/assets/18141238/4345c442-cbf2-481a-b22a-aa412d8b1501">
<img width="511" alt="image" src="https://github.com/angular/angular/assets/18141238/903e3c22-275b-451b-b91a-04124807c0aa">

**Comment by JeanMeche** [comment]
I'll take a look to clarify this. 

The sentence is mostly correct, the ViewChild is init just before `AfterViewInit` except when `static: true`. In this 2nd case it's init before before change detection, so it's available int `OnInit`.

**Comment by qmarquez** [comment]
> I'll take a look to clarify this.
> 
> The sentence is mostly correct, the ViewChild is init just before `AfterViewInit` except when `static: true`. In this 2nd case it's init before before change detection, so it can accessed from `OnInit` onwards.

Hey Jean! I understood the same, but in my project (angular v16.1.4) the ViewChild decorator imported from @angular/core, with the static option true, don´t work as it, I need to use the ngAfterViewInit method to work

**Comment by JeanMeche** [comment]
Could you provide a stackblitz repro where it's not available in `ngOnInit` ?

**Comment by qmarquez** [comment]
https://stackblitz.com/edit/stackblitz-starters-3apz5z?file=src%2Fmain.ts here it's, codign this for you I guess I found the error, it's commented on code L:39

**Comment by JeanMeche** [comment]
@qmarquez I was expecting this. You're using an structural directive, here `*ngIf`, this means you need to wait for the CD for it to be renderered ! 

Let me know what you think about the changes I propose in #51146. Does make it clearer for you ?

**Comment by qmarquez** [comment]
@JeanMeche, thank you so much! I really appreciate your help. Now everything is much clearer. I noticed that it's the code metadata, and it would be fantastic if the docs (angular.io) could be updated too. Personally, I find a lot of valuable information there. Thanks again for everything!
