### ISSUE TITLE
Compile-time checking for ViewChild decorated property

### ISSUE THREAD

**Issue by hydroper** [angular/angular#51145]
### Description

I've seen that you can accidentally type `@ViewChild('someEl') someEl!: ElementRef` as `@ViewChild('someEl') someEl!: Element`. This is confusing since `someEl` in the template is used as an `Element` and not as an `ElementRef`.

More information: https://stackoverflow.com/q/76749265/19692949

TLDR: there should be a little clarification for DOM elements when using `@ViewChild` for them.

### Proposed solution

A compile-time error indicating you used the wrong type for `@ViewChild`, specially for DOM elements. I suppose that this is possible because Angular transforms the TypeScript code (including by using its Compiler API).

### Alternatives considered

N/A

**Comment by JeanMeche** [comment]
I'll be closing this. Decorators are known to not be the best for typesafty. 
In v17.2 Angular introduced signal view queries which are better are ensuring typesafety.
