### ISSUE TITLE
multilevel object with multiple ng-for not working

### ISSUE THREAD

**Issue by kalinicm** [angular/angular#5115]
In PHP I have multilevel array (with keys and values),  which resembles Object structure in JS. I use simple foreach to loop thru any subbranch of that multilevel array, all works perfectly and easily.

In Angular2 when I give ng-for in template and Object it loops as expected. 

But when I try to use second ng-for inside the first ng-for loop it does not work, but it should. I've built a Pipe that has to convert Object to Array in order to execute that second ng-for.

Is this a bug or missing feature or I am doing something completely wrong? It is intuitive to use multiple ng-for on the same object but it does not work, and this could be very critical functionality especially there is a "Falcor" which handles really large multilevel Object data which will need to iterate well in Angular2.

Here is the stackexchange topic on the matter with example:
http://stackoverflow.com/questions/33335569/angular2-multidimensional-array-ng-for-not-working

**Comment by pkozlowski-opensource** [comment]
> Is this a bug or missing feature or I am doing something completely wrong?

Impossible to say based on the info provided. Send a plunk with a reproduce scenario, otherwise this is not actionable.

**Comment by kalinicm** [comment]
Ok, no problem. Just to create it and I will post the link here.

**Comment by kalinicm** [comment]
I do not know if I made it well, but here is the link:
http://plnkr.co/edit/hDTYfYxrZuH3dr0KIuBh?p=preview

Just goto app.ts and look at the defined Object and two ng-for.

**Comment by pkozlowski-opensource** [comment]
@kalinicm in your second `for` you are trying to iterate over object properties which isn't (and won't be) supported. `ng-for` only knows how to iterate over arrays.

**Comment by kalinicm** [comment]
Ok. I made a Pipe for that and it works.

Thank you for fast response and clear information.


import { Pipe } from 'angular2/angular2';
@Pipe({
     name: 'objToArr',
     pure: false
})
export class ObjToArr {
     transform(object:any) {
          var newArray = []
          for (var key in object) {
               newArray.push(object[key]);
          }
          return newArray;
     }
}

**Comment by pkozlowski-opensource** [comment]
OK, glad it is clarified.

**Comment by flyingmutant** [comment]
@pkozlowski-opensource can you please explain why `ng-for` will not support objects? How should one iterate key-value pairs from a map?

**Comment by kalinicm** [comment]
I would like to see ng-for handle both arrays and objects, no matter. 
Second thing would be that ng-for has keys and values to pass on. 

In PHP I can use this, not so much in Angular2 or am I missing something:

   foreach($array as $key1 => $value1){
       print "the level1 key is:".$key1;
       foreach($value1 as $key2 => $value2){
               print "the level2 key is:".$key2." and the value of key2 is ".$value2;
       } 
   }
