### ISSUE TITLE
I can't see all template errors during build

### ISSUE THREAD

**Issue by roma2341** [angular/angular#51155]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When i run "npm run start" or "npm run build" i see some errors like:
'mat-icon' is not a known element (used in the 'TeamDealReportComponent' component template):
Then after fixing them i met them again in some places of my application but this time in the browser.
Is there are any way to detect forgotten imports of modules on the build phase ?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/core": "16.1.6",
node v18.12.1
```

**Comment by alxhub** [comment]
Hello @roma2341,

Without knowing the details of your application, your build, etc. we can't determine whether this is a bug in Angular or expected behavior. Can you share a reproduction scenario where your local build succeeds and you still see errors at runtime?

**Comment by roma2341** [comment]
After hours of investigation i found that i can find these errors using strictTemplates option in tsconfig.

**Comment by JeanMeche** [comment]
Yes, this is the recommended setting for this !

**Comment by roma2341** [comment]
And also if you run Angular inspections in IDEA it will show more errors (e.g forgotten import of mat-icon module) than angular compiler. (it helped me a lot to remove material modules from shared module)
