### ISSUE TITLE
Attribute with default value doesn't accept undefined as value

### ISSUE THREAD

**Issue by PhiLhoSoft** [angular/angular#51164]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

In an Angular 16 project with strictTemplates option on, I get numerous errors in templates about the attributes.

My point in this issue is that when I have `<some-component [size]="size"/>` with the `size` attribute defined as: `@Input() size: string = DEFAULT_SIZE;` for example, I get the following error: "_TS2322: Type 'string | undefined' is not assignable to type 'string'_".

But Angular converts undefined values to the default value in such case, that's the point of the whole mechanism.
I workaround the problem with `<some-component [size]="size!"/>` but it doesn't feel right.
It worked before (v. 14), because the template compiler was less strict?

Can Angular template compiler detect such cases and avoid this error?
Thanks.

### Please provide the exception or error you saw

```true
error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.5
Node: 20.3.1 (Unsupported)
Package Manager: npm 9.6.7
OS: win32 x64

Angular: 16.1.6
... common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.5
@angular-devkit/build-angular   16.1.5
@angular-devkit/core            16.1.5
@angular-devkit/schematics      16.1.5
@angular/cdk                    16.1.5
@angular/cli                    16.1.5
@schematics/angular             16.1.5
ng-packagr                      16.1.0
rxjs                            7.8.1
zone.js                         0.13.1
```

**Comment by JeanMeche** [comment]
You won't get these warnings if you set `strictNullChecks:false` into the `tsconfig`.

**Comment by JoostK** [comment]
> But Angular converts undefined values to the default value in such case, that's the point of the whole mechanism.

This is not the case, actually. Angular will always bind a value into the corresponding field, overwriting any default value. You'll need a setter or input transform function to convert a `null`/`undefined` value to a default value, if desired.

Hence, the `strictTemplates` option is correctly reporting this as an error.

**Comment by PhiLhoSoft** [comment]
@JeanMeche I can also disable strictTemplates, but that's not the point!
@JoostK OK, I went on a bad assumption, indeed I saw in the code I maintain that a default value is also attributed if undefined. So much for me, and sorry for the noise.
