### ISSUE TITLE
signal - effect() not always triggered when the signal is updated

### ISSUE THREAD

**Issue by rlejeune** [angular/angular#51180]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Not sure if this is a bug, or if I use effect() wrong.

 I have this effect in the constructor, I tried with patchValue too btw same result.
```
effect(() => {
   this.organizationForm?.controls['name'].setValue(this.organization().name);
});

```

And this code which is called when the form is saved, which should trigger the effect but it does not
```
const organization = await this.service.saveOrg();
this.organization.update(() => organization);

```

If I change the code in the effect for this, then it is triggered. 
```
effect(() => {
   const name = this.organization().name;
   this.organizationForm?.controls['name'].setValue(name);
});

``` 

Any reason why assigning the signal value to a const first before setting the form value works, but not if used directly?

Thank you!

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.5
Node: 16.16.0
Package Manager: npm 9.7.2
OS: linux x64

Angular: 16.1.7
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.5
@angular-devkit/build-angular   16.1.5
@angular-devkit/core            16.1.5
@angular-devkit/schematics      16.1.5
@angular/cli                    16.1.5
@schematics/angular             16.1.5
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```

**Comment by rlejeune** [comment]
While trying to reproduce it, it looks like the problem is caused by a third party lib, ng-zorro-antd. 

I cannot reproduce it without the lib

Sorry for your time and thanks!

**Comment by JoostK** [comment]
To provide some additional insight:

> `this.organizationForm?.controls['name'].setValue(this.organization().name);`

The above usage of optional chaining may bail the execution of the remainder of the expression (if `this.organizationForm` is undefined/null) which prevents the argument list to `setValue` from being evaluated. As such, the signal would not be read and no dependency would be registered, hence the `effect` would never rerun.
