### ISSUE TITLE
withFetch() and router guard create random bug

### ISSUE THREAD

**Issue by tomer953** [angular/angular#51181]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I have a fully functional app using Angular 16.1.4 (standalone) and Electron 25. I am using the new experimental option for the `provideHttpClient()` - `withFetch()`, and the ng-select package (latest version 11.0.0) inside my app's navbar to search for users from the API (autocomplete).

Today, I added a router guard (functional guard) to my main page. The guard is something like:
 `return inject(AuthService).login()`, which creates an HTTP request to the backend. The guard is working as expected, and I've been using this approach for years.

However, the combination of `withFetch()` and the `authGuard` is causing a strange bug: The ng-select component is not working properly - it doesn't show a list of items (even though the API calls appear in the network tab), the CSS is a bit off (the input is on top of the placeholder), among other strange behaviors.

Just by removing either `withFetch()` or the authGuard, everything works as expected. So, it seems the combination of the two is creating side effects on the ng-select component.

I updated to Angular 16.1.6, but the bug persists. I have another app that works with ng-select, Angular 16, and authGuard without any issues. I have a lot of experience with Angular, and this is a strange one. I'm not sure if anyone will know the cause, especially without a reproduction of the bug. But if no one has a clue, I'll do my best to reproduce it.

### Please provide the exception or error you saw

```true
No errors on the console at all.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 16.1.4 \ 6
Node: 16.19.1

Electron: 25
```

### Anything else?

I am running angular inside electron app, but this is not releated to Electron in my opinion, since I can also run the angular app in the browser directly (localhost:4200) and I see the same behaviour.

- Everything is working as expected without the guard
- If the guard is not using http request (ie, just returns of(true)) - no problem
- No errors in the console, the http requests for the guard and the ng-select autocomplete is working and getting valid respones (200) using fetch api

**Comment by JeanMeche** [comment]
Hi, this is quite hard to investigate without a repro. Could you maybe try to create a repro on stackblitz and forward it to us ? That'd be great !

**Comment by tomer953** [comment]
I tried to reproduce it without Electron, in a brand new project, and I can't.

something is causing a problem but I did not managed to find it for now.
so by now I will comment out the `withFetch()` option for this project.

I close this for now, I will open If ill find a way to reproduce.
