### ISSUE TITLE
Outdated note about standalone custom-elements?

### ISSUE THREAD

**Issue by haraldreingruber-dedalus** [angular/angular#51187]
### Describe the problem that you experienced

The note in https://github.com/angular/angular/blob/3a59de681fd9899a40c49b3bce6f101d3d1b95cd/aio/content/guide/elements.md?plain=1#L22-L24 seems outdated.

Can standalone components (introduced in Angular 14) used for that purpose? It sounds like a combination of custom elements and standalone components could achieve this goal.

### Enter the URL of the topic with the problem

https://angular.io/guide/elements

### Describe what you want to experience that would fix the problem

It's probably an ongoing effort for updating the docs and tutorials for standalone components. But maybe there are some intermediate resources to point to until the docs/tutorials are ready for folks who already want to try out the dev-preview version.

### More information

Please let me know if I should provide more details, or if there is anything I can help improve. 
Thanks for all the effort that is put into this project  🙏

**Comment by ferrorenan** [comment]
Hey @haraldreingruber-dedalus, how are you?!

Could you give me more details on what we can do?! I'd really like to resolve this!

**Comment by JeanMeche** [comment]
We're looking to deprecate angular.io in favor of https://angular.dev. 

Feel free to open an issue for improvements toward the new site, thank you.
