### ISSUE TITLE
NavigationEnd not triggering on page reload inside constructor

### ISSUE THREAD

**Issue by todorpavlovic** [angular/angular#51185]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

Subscription on router events inside constructor on reload was working fine, after upgrade from Angular version 14 to 16 event is not being triggered.

```
constructor() {
    this.router.events
      .pipe(filter((event) => event instanceof NavigationEnd))
      .subscribe((event) => {
            console.log(event); //nothing on page reload
      });
}

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.1.5
Node: 18.16.1
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 16.1.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.5
@angular-devkit/build-angular   16.1.5
@angular-devkit/core            16.1.5
@angular-devkit/schematics      16.1.5
@angular/cdk                    16.1.5
@angular/cli                    16.1.5
@angular/material               16.1.5
@schematics/angular             14.2.12
ng-packagr                      14.2.2
rxjs                            7.5.7
typescript                      4.9.3
webpack                         5.88.2
zone.js                         0.11.8
```

**Comment by JoostK** [comment]
This is because of the following breaking change in Angular 15:

> Previously, the RouterOutlet would immediately instantiate the component being activated during navigation. Now the component is not instantiated until the change detection runs. This could affect tests which do not trigger change detection after a router navigation. In rarer cases, this can affect production code that relies on the exact timing of component availability.

**Comment by todorpavlovic** [comment]
I have array of objects, one of properties on these objects is url. Then on every route change I'm getting urlAfterRedirects and matching object with current url.
```

  toolbarConfigurationSettings = [
    {
      url: '/page/list',
      toolbarHeaderName: 'List',
      showAddButton: true,
      addButtonText: 'Add new',
      showViewChangeButton: true,
      addButtonEvent: () => {
        this.router.navigateByUrl('page/create');
      },
    }]
```

```
        const currentConfiguration =
          this.toolbarService.toolbarConfigurationSettings.find(
            (setting) =>
              event.urlAfterRedirects.startsWith(setting.url)
          );
```

**Comment by JoostK** [comment]
Could you move the event subscription into an NgModule constructor or `APP_INITIALIZER`?

**Comment by todorpavlovic** [comment]
It's working on NgModule level, in some situations I can replace. The issue is when I have 4-5 subscriptions to events in one module.

```
    this.router.events
      .pipe(filter((event) => event instanceof NavigationEnd), startWith(this.router.url))
```

I guess this will do the job for now.
