### ISSUE TITLE
CanActivateFn Does Not Retrieve The Latest Signal Value After Being Redirected By Guard

### ISSUE THREAD

**Issue by AlvinStefanus** [angular/angular#51196]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

So this weird behavior only occurs when I open the website for the first time. After I refresh the website it works fine. 

The injection inside `CanActivateFn` function does not retrieve the latest signal value after the signal is updated.

This is the `CanActivateFn`:

```
export const RegisteredGuard: CanActivateFn = (route, state) => {
  return inject(AuthService).isUserInRoles(['registered']) ? true : inject(NavigationService).router.createUrlTree(['/login']);
};

export const AllContentGuard: CanActivateFn = (route, state) => {
  return !environment.protectAllContentWithAuthentication ? true :
    inject(AuthService).isUserInRoles(['registered']) ? true : inject(NavigationService).router.createUrlTree(['/login']);
};
```

This is the `AuthService`:

```
export class AuthService {
  auth: WritableSignal<IAuth | undefined>;

  constructor(
    private cookieService: CookieService,
    private nav: NavigationService,
    private notification: NotificationService
  ) {
    this.auth = this.initAuth();
  }

  private initAuth() {
    return signal(this.getCookieAuth());
  }

  private getCookieAuth() {
    const auth = this.cookieService.get('auth');
    return auth ? JSON.parse(auth) : undefined;
  }

  setAuth(auth: IAuth) {
    // Set cookie to expire in 30 days
    this.cookieService.set(
      'auth',
      JSON.stringify(auth),
      environment.authExpiresAfter
        ? new Date(Date.now() + environment.authExpiresAfter)
        : undefined
    );
    this.auth.set(auth);
  }

  removeAuth() {
    this.cookieService.delete('auth');
    this.auth.set(undefined);
  }

  logout() {
    this.removeAuth();
    this.notification.success('You have been logged out');
    this.nav.navigateByUrl('/login');
  }

  isUserInRoles(roles: string[]) {
    return this.auth()?.roles?.some((r) => roles.includes(r)) ?? false;
  }
}
```

This is my `app-route`:

```
export const routes: Routes = [
  ...accountRoute,
  {
    path: '',
    component: LayoutComponent,
    children: [
      {
        path: '',
        component: IndexPageComponent,
        pathMatch: 'full',
      },
      {
        path: 'index',
        component: IndexPageComponent,
      },
      {
        path: 'account',
        component: ProfilePageComponent,
      }
    ],
    canActivate: [AllContentGuard],
  },
];
```

The idea here is that all of my content is guarded by `AllContentGuard`. The user has to be logged in to be able to see the content. The problem here is that this code:

```
  isUserInRoles(roles: string[]) {
    return this.auth()?.roles?.some((r) => roles.includes(r)) ?? false;
  }
```

Does not get the `this.auth()` values correctly. It gives me `undefined`, even after I set the auth from this `login-page.component.ts`:

```
  async login() {
    this.loading.set(true);
    const res = await this.http.post<IAuth>('/login', null, {
      email: this.email(),
      password: this.password(),
    });
    this.loading.set(false);

    if (res) {
      if (res.error) {
        this.notification.error(res.msg);
      } else if (res.data) {
        this.auth.setAuth(res.data);

        // If user is not confirmed, redirect to confirm email page
        if (!res.data.confirmed) {
          this.notification.warning(this.str()('emailNotConfirmed'));
          setTimeout(() => this.nav.navigateByUrl('/confirm-email'), 1000);
        } else {
          this.notification.success(this.str()('loginSuccess'));
          this.nav.navigateToIndex();
        }
      }
    }
  }
```

I even tried to setup the navigation wrapped in `setTimeout()` to see if there is delay for the signal updates, but it is the same.

The problem only occurs when I go to `http://localhost:4201` as my app is hosted. If I refresh the page immediately after I open the website, it works fine, but not when first opening the web.

-----

The problem occurs only when I go to `http://localhost:4201`, which is redirected to `http://localhost:4201/login`. If I go by typing `http://localhost:4201/login`, it works fine.

So the flow is like this:

First open website -> go to `http://localhost:4201` -> got redirected for the first time from `CanActivateFn` by `AllContentGuard` to `http://localhost:4201/login` -> login and sets the auth -> Then the guard always retrieves undefined auth.

-----

**UPDATE**

Ok so, after getting redirected by the guard `AllContentGuard`, the guard loses the connection to the auth signal. It is no longer able to get the update from the signal.

Does redirecting using this:

```
inject(NavigationService).router.createUrlTree(['login'])
```
removes the connection with the signal? I am not sure

-----

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.6
Node: 16.15.1
Package Manager: npm 8.11.0
OS: darwin arm64

Angular: 16.1.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.3
@angular-devkit/build-angular   16.1.3
@angular-devkit/core            16.1.3
@angular-devkit/schematics      16.0.6
@angular/cli                    16.0.6
@nguniversal/builders           16.1.1
@nguniversal/express-engine     16.1.1
@schematics/angular             16.0.6
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by AlvinStefanus** [comment]
The bug is that, after the initial page loading, if the first-page loading got redirected by the guard (CanActivateFn), all of the injected services do not have the correct value. They don't synchronize with the real Services.
