### ISSUE TITLE
Impact of Object.observe() removal from TC39 standard?

### ISSUE THREAD

**Issue by tapas4java** [angular/angular#5119]
Angular2 is heavily invested on Object.observe. What would be the roadmap now after removal of this feature from TC39 standard?

**Comment by pkozlowski-opensource** [comment]
> Angular2 is heavily invested on Object.observe. 

Why are you saying so? Angular 2 never used O.o as it has own change detection algorithm / infrastructure. Could you point to the source of this claim?

> What would be the roadmap now after removal of this feature from TC39 standard?

There is no roadmap, as the impact of this decision on the ng2 design / code-base is equal to _zero_. Once again Angular2 doesn't use and never used O.o.

**Comment by tapas4java** [comment]
I was confused between Observables and Object.observe :)

**Comment by olivvv** [comment]
But wasn't it supposed to make angular super fast ?
https://plus.google.com/+AngularJS/posts/cWhqjs8PYAc

That promise is not resolving in the end
