### ISSUE TITLE
'html5' mode for links (<a>)

### ISSUE THREAD

**Issue by Necroskillz** [angular/angular#5120]
In angular 1 you can use the [`$locationProvider`](https://docs.angularjs.org/api/ng/provider/$locationProvider) to set html5mode. This causes all internal links to not trigger a full refresh and instead change route in angular.

I didn't find similar functionality in angular 2.

Currently I know of 2 ways to change the url in angular 2 app so the route changes without full page reload:
- `router-link` attribute
- `router.navigateByUrl`

In the company I'm working for, our app gets some content from CMS, which may contain links to other parts of the application, so I can't use router-link for them.

I quickly tried to create a directive that would help with normal link (`<a href="/en/page"></a>`). Am I supposed to do that or did I miss something?

```
@Directive({
    selector: 'a:not([router-link])',
    properties: ['href'],
    host: {
        '(click)': 'go($event)'
    }
})
class ADirective{
    href: string;
    
    constructor(private router: Router) {
    }
    
    go(e: MouseEvent){
        e.preventDefault();
        
        this.router.recognize(this.href).then(instruction => {
            if(instruction !== null){
                this.router.navigateByInstruction(instruction);
            } else {
                window.location.href = this.href;
            }
        });
    }
}
```

**Comment by btford** [comment]
See `PathLocationStrategy`

**Comment by Necroskillz** [comment]
I don't understand. `PathLocationStrategy` is not used when you just click on a link like `<a href="/en/page">link</a>`.

**Comment by btford** [comment]
Ah, sorry, I misunderstood.

You can add this feature yourself with event delegation and by injecting `Router` and calling `router.navigateByUrl(...)`.

If this functionality is commonly needed, we can talk about adding it to core, but I suspect there will be subtle differences in requirements between apps that want this.
