### ISSUE TITLE
HostDirectives doesnt provide the hosted directives when inherited

### ISSUE THREAD

**Issue by iRoyPeleg** [angular/angular#51203]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Hi,

I have encountered an issue where `hostDirectives` doesn't provide with inheritance:

1. Create a standalone `CustomDirective`:
![image](https://github.com/angular/angular/assets/24734513/6bf040a9-a075-4565-a530-9bb77f98ce91)

2. Create `BaseComponent` that uses the `CustomDirective` via `hostDirectives`:
![image](https://github.com/angular/angular/assets/24734513/a6d353e9-58ca-46d9-9847-a7ee257c683c)

3. Inject the `CustomDirective` in BaseClass via `inject()` method:
![image](https://github.com/angular/angular/assets/24734513/76923787-3d7b-40dc-8c65-062da1d03a85)

4. Create `ExtendsComponent` that extends via inheritence the `BaseComponent`:
![image](https://github.com/angular/angular/assets/24734513/35b05746-71a5-4a5c-a505-1eef9c2ab3f9)

If you try to run the application, it complains about missing provision for said directive:
![image](https://github.com/angular/angular/assets/24734513/427c6b7e-d76d-45f8-80e7-1a2aa92518b2)

If manually provides the CustomDirective inside the `ExtendsComponent` it works:
![image](https://github.com/angular/angular/assets/24734513/fbdddace-bb74-4375-914e-45e86fb4f031)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz-starters-icp5kn.stackblitz.io

### Please provide the exception or error you saw

```true
ERROR NullInjectorError: R3InjectorError(Standalone[App])[CustomDirective -> CustomDirective -> CustomDirective]: 
  NullInjectorError: No provider for CustomDirective!
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.4
Node: 18.16.1
Package Manager: npm 6.14.17
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1601.4
@angular-devkit/core         16.1.4
@angular-devkit/schematics   16.1.4
@schematics/angular          16.1.4
```

**Comment by crisbeto** [comment]
This currently works as expected, because host directives aren't set up to be inherited.

**Comment by iRoyPeleg** [comment]
> This currently works as expected, because host directives aren't set up to be inherited.

Thanks for the response.
This is actually quite confusing, as there's no documentation that it is indeed by design / limitation.

Are there any plans to allow hostDirectives inheritance it in the future? Because I see valid use-cases for this scenario where this will be very beneficial.

Thanks.

**Comment by crisbeto** [comment]
Enabling it is basically a one-liner, but there's a discussion to be had if we should support it since it's mixing two different ways of composing directives.

**Comment by raudzi** [comment]
It would allow for better composition of directives which would be neat.
