### ISSUE TITLE
Argument of type 'MouseEvent' is not assignable to parameter of type 'PointerEvent'

### ISSUE THREAD

**Issue by tautvydasp** [angular/angular#51210]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

`$event` type on `(click)="handleClick($event)"` is shown as `MouseEvent` in component's template:
![Screenshot from 2023-07-31 11-26-58](https://github.com/angular/angular/assets/13319188/a36fef13-1545-49ba-bcbb-65cdb2f6b837)

But when I log event into console with:
```
handleClick(event: any) {
    console.log('event', event);
}
```
It logs `PointerEvent` events:
![image](https://github.com/angular/angular/assets/13319188/114e5ce7-3bda-4bd8-a407-206a78bf5c29)

And if add correct type to argument of `handleClick` function:
```
handleClick(event: PointerEvent) {
    console.log('event', event);
}
```
Error is thrown saying that `MouseEvent` is not assignable to `PointerEvent`.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-yi6g8c?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
Argument of type 'MouseEvent' is not assignable to parameter of type 'PointerEvent'.
Type 'MouseEvent' is missing the following properties from type 'PointerEvent': height, isPrimary, pointerId, pointerType, and 8 more.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.6
Node: 18.17.0
Package Manager: npm 9.6.7
OS: linux x64

Angular: 16.1.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.6
@angular-devkit/build-angular   16.1.6
@angular-devkit/core            16.1.6
@angular-devkit/schematics      16.0.6
@angular/cli                    16.0.6
@schematics/angular             16.0.6
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by JeanMeche** [comment]
`PointerEvent` inherits from `MouseEvent` not the otherway arround. So this is expected.
