### ISSUE TITLE
Installing angular_1_router.js as part of a package

### ISSUE THREAD

**Issue by varghesep** [angular/angular#5121]
I'm using **Angular 1** and the [angular router 1](https://github.com/angular/angular/blob/master/modules/angular1_router/test/integration/navigation_spec.js). I assume this is the router I should be using with **Angular 1**. 

I have currently copied the file **angular_1_router.js** and have not installed through any package. How can I install this router package only if I want to use with **Angular 1**?

**Comment by vguede** [comment]
You can see angular/angular.js#12926

**Comment by btford** [comment]
it's on npm now as `@angular/router`.
