### ISSUE TITLE
Router requires redirectTo in Child Components for it's root view

### ISSUE THREAD

**Issue by DennisRoam** [angular/angular#5123]
**Version:** Alpha 45
**Overview:**
When using a component that has child components you have to use redirectTo to let the `[router-link]` work correctly when trying to link to the "root" of a child route. I assumed just using "/" and defining a default component would work but its throwing an error. If I put a "redirectTo" in it works as expected but doesn't make sense to me why this is required. I should be able to define a component for "/"

**Example**
App has a home and cars main set of routes
The Cars route has three child routes (default, list, detail)

In app.ts:
```javascript
<a [router-link]="['/Cars']"><span></span>Cars</a>
```
**Currently works with redirectTo**
In cars.ts
```javascript
@RouteConfig([
    { path: '/', redirectTo: '/default' },
    { path: '/default', as: 'Default', component: CarsDefault },
    { path: '/list', as: 'List', component: CarsList },
    { path: '/detail', as: 'Detail', component: CarsDetail }
])
```
Plunker: http://plnkr.co/edit/TF4L6ujxtVua2JXYwr3T?p=preview

**What I expected to work**
````javascript
@RouteConfig([
    { path: '/', as: 'Default', component: CarsDefault },
    { path: '/list', as: 'List', component: CarsList },
    { path: '/detail', as: 'Detail', component: CarsDetail }
])
````

**Throws Error:**
`EXCEPTION: Link "["Cars"]" does not resolve to a terminal or async instruction. in [null]` from app component

Plunker: http://plnkr.co/edit/6fVwFwDLCW0NSajtG6Bv?p=preview

I'm not sure if I'm doing something incorrectly, but to me I should be able to just link to /Cars and load the "/" route as the default, not redirect to a different path.

**Comment by ericmartinezr** [comment]
As reference what you are seeing is a fix for the error reported here https://github.com/angular/angular/issues/3979 it have changed a little bit since then, i.e. the error message is slightly different.

**Comment by Necroskillz** [comment]
This would work with the second `RouteConfig`:
```
<a [router-link]="['/Cars', 'Default']"><span></span>Cars</a>
```

Not sure if it was intended this way, but it makes sense that the default route (`/`) could be recognized automatically.

**Comment by DennisRoam** [comment]
Thank you Necroskillz! I don't know why I didn't try that for my workaround. 

That is working as a temporary work around but I agree, I think if I just pass `['/Cars']` it should go to the default instead of having to be `['/Cars', 'Default']`

**Comment by DennisRoam** [comment]
Ok I've worked out how to get this to work right and why I was struggling with it. Hopefully this can help other newbs like me get it...

Plunker from above now working: [here](http://plnkr.co/edit/qlFvZT7VYi3uYlVeCz9D?p=preview)

**TL/DR** I got confused about how the URL and route names are bound. All child routes require names...
**I've seen people do examples without the "as" field but none of my plunkers or code let that fly, maybe I'm doing something wrong?**

**Full**
 The issue is even though within an <a> the route-link **IS NOT** bound to the URL path which my brain did not understand. When reading examples/tutorials/guides you always used the same naming convention but the two are not bound. 

Consider this child component config for a "Pets" component:
```javascript
@RouteConfig([
    { path: '/', as: 'Apples', component: Pets },
    { path: '/cats', as: 'Oranges', component: Cats },
    { path: '/dogs', as: 'Bananas', component: Dogs },
])
```
In a browser you could go to http://site.com/pets and it would be fine. You could go to http://site.com/pets/dogs and it would also be fine. 

**BUT** when you do this: `<a router-link="['./Dogs']">Dogs</a>` it does not work because technically the NAME of the route is **Bananas** so the correct "router-link" is  `<a router-link="['./Bananas']">Dogs</a>`

I felt stupid once I realized my confusion and what the issue ultimately was. When I called `['/Cars']` my brain saw it as resolving to http://site.com/cars **but** the router is told to expect children at that route `path: 'cars/...'` so it goes to the "Cars" component looking for it's children. I assumed the **URL PATH of "/"** would tell the router that it was the main item but it doesn't look at the path, it looks at the alias. When I didn't pass what child route to load it threw an error. What I needed to do was name it, and pass that.

**So:**

```javascript
//config
    { path: '/', as: 'Root', component: RootCmp }
//link
<a router-link="['/Cars', 'Root']">Cars</a>
//WORKS
```

Two take aways:
**1.** The closeness of the path/alias/router-link is a bit confusing. At some point it would be a bonus to use it like this:
```javascript
    { path: '/', component: Pets }, //or even a FALSE so it only shows when passed like for aux routes
    { path: '/cats', component: Cats },
//Links
<a router-link="['/pets']">Pets</a>
<a router-link="['/pets/cats']">Cats</a> //THIS ALREADY WORKS as /Pets/Cats
```
Where it reads the path value first if there is no "as" alias _(I've seen some code written this way but it never works for me)_

**2.** At least consider some name changes to clear up what's actually happening. 
Change "as" to "name" or "alias". 
Change `router-link` to `router-nav` or `router-target` to clarify that it's not referencing the URL string but the config.
Change "path" to "url" as that's what that is actually effecting. _(like UI-Router)_

```javascript
//config
    { name: 'Root', url: '/', component: RootCmp }
    { name: 'Dogs', url: '/dogs/:petId', component: DogCmp }
//link
<a router-target="['/Pets', 'Root']">Pets</a>
//or
<a router-nav="['/Pets', 'Dogs',{petId: 123}]">My Dog</a>
```

Again, I'm not an expert and maybe I'm not understanding 100% but I spent a ton of time messing with this and didn't get it..

**Comment by DennisRoam** [comment]
didnt mean to close it, id like to have it open as a discussion

**Comment by btford** [comment]
@DennisRoam thanks for the feedback, and sorry for the frustration. A bit part of the problem is that the documentation around how route links work is still poor. We'll be improving this shortly.

I'll try and address some of your suggestions below.

> Change "as" to "name" or "alias". 

I agree and have already implemented this change in master.

It's important to keep the concept of `path` and `name` distinct. A path can have more than one segment, so your suggestion of defaulting to the value of `path` when `name` is empty will not work.

There's an existing thread here about planned improvements to the linking DSL that may be of interest: https://github.com/angular/angular/issues/2845

I don't think that your other name suggestions are better than `router-link` or `path`. I think URL is even more misleading, since nested components only have part of the path, rather than a full URL. I don't see why `target` suggests a non-url value any more than `link`.

**Comment by DennisRoam** [comment]
Hey Brian, thank you for your reply. I was a bit frustrated so I wrote a ton. I appreciate all the hard work you're doing so thanks for even looking at it.
