### ISSUE TITLE
ServiceWorker causes erroneous 504 on SSO sign-in flow

### ISSUE THREAD

**Issue by Andrewknackstedt** [angular/angular#51245]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

No

### Description

We have an app that uses OpenID to perform a handshaked sign-in via server redirects. 
On our /login call and redirect, the user is sent to the Idp correctly, and can sign-in. When the user is redirected back to our site (`/api/auth/login`), the serviceworker shows an empty 504 screen

### Please provide the exception or error you saw

![image](https://github.com/angular/angular/assets/47012541/e040e4dc-93ae-4d11-aedd-560a147b7919)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.9
Node: 16.20.1
Package Manager: npm 8.19.2
OS: linux x64

Angular: 15.2.9
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.9
@angular-devkit/build-angular   15.2.9
@angular-devkit/core            15.2.9
@angular-devkit/schematics      15.2.9
@schematics/angular             15.2.9
rxjs                            7.5.7
typescript                      4.8.4
```

### Anything else?

This could very-well be a configuration issue, but we followed the angular.io docs and we aren't really sure how to proceed. This is impacting our ability to use serviceworker caching in production.

Our failover method is going to be using ngsw-bypass, but I don't think that's really an ideal solution

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Andrewknackstedt** [comment]
Thanks
