### ISSUE TITLE
"Template reference variables" topic does not have active state in navigation

### ISSUE THREAD

**Issue by tkolok** [angular/angular#51242]
### Describe the problem that you experienced

When you visit the [Template reference variables](https://angular.io/guide/template-reference-variables) topic, its related link is not active in the navigation (The `.selected` class is missing).

### Enter the URL of the topic with the problem

https://angular.io/guide/template-reference-variables

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/12582532/24edcf85-003a-4a8c-8f2c-f8ac40ed0065)

**Comment by JeanMeche** [comment]
I can't reproduce that issue on a Chrome M115. 

Do you have this issue on navigation or on a fresh loading (F5).

**Comment by JoostK** [comment]
It happens because the page is referenced from the main menu twice, first under "Understanding Angular > Templates -> Template reference variables" (as seen in the screenshot in the issue) vs the second occurrence under "Reference > Conceptual reference > Angular concepts > Template variables".
