### ISSUE TITLE
Router Link Parameters Not Optional

### ISSUE THREAD

**Issue by DennisRoam** [angular/angular#5124]
**Version:**45

When using child routes and passing parameters you are required to pass a value in `[router-link]`

**Use Case**
A Home and Cars main route. When going to Cars it loads a list of cars (site.com/cars) If I pass a ID it would load info for just that car (site.com/cars/1234)

Currently if you try to go to "/Cars" it throws an error:
`EXCEPTION: Route generator for 'carId' was not included in parameters passed. in [null]`
http://plnkr.co/edit/u9b03dFEAslMASYe7QBj?p=info

If I pass a "Filler" value it works
Plunker: http://plnkr.co/edit/UBtRLav23vOCutBVJf6X?p=preview

I expected the parameter to be optional but it's not..

_NOTE:Both examples don't use the route params in the components but even if they did it throws the same error_

**Comment by btford** [comment]
This is working as expected.

You probably want to remove the parameter from the `Cars` route:
```
@RouteConfig([
    { path: '/', redirectTo: '/home' },
    { path: '/home', as: 'Home', component: Home },
    { path: '/cars/...', as: 'Cars', component: Cars } // removed ":carId" here
])
export class App {
```

And move it to a route within the `Cars` component:

```
@RouteConfig([
    { path: '/', component: SomeIndex },
    { path: '/:carId/detail', as: 'Detail', component: CarsDetail }
])
export class Cars {
```

Alternatively, you can break apart the hierarchy into three components for your case, or you could create separate routes with and without the params in the top-level component.

There's an open issue for optional params here: #3525

**Comment by DennisRoam** [comment]
Thank you Brian, I got confused by a the path and the router-link a bit... 
One thing, I haven't been able to do a route without the alias and use a router link..

If anyone wants to see an updated plunker its [here](http://plnkr.co/edit/gLX484wY2YhyqCnSVpGi?p=preview)
