### ISSUE TITLE
Async pipe used inside an HTML template does not get the latest values

### ISSUE THREAD

**Issue by ddamiankowalski** [angular/angular#51244]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

When I am trying to subscribe to an Observable  using an async pipe, the template does not seems to be subscribing correctly. However, when I am subscribing to the very same Observable in the imperative way (calling the subscribe method in the constructor of the same component), the values are emitted correctly. 

Could this be some sort of regression or am I making a stupid mistake somewhere that I have yet not been able to notice? In other projects that run on Angular v15 I have been using 'async' pipe in similar scenarios very frequently. Could this be some sort of regression?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-jjmsrq?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___     
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|    
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |     
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |     
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|    
                |___/


Angular CLI: 16.1.6
Node: 18.13.0
Package Manager: npm 8.19.3
OS: win32 x64

Angular: 16.1.7
... animations, common, compiler, compiler-cli, core, forms      
... language-service, platform-browser, platform-browser-dynamic 
... router

Package                         Version
---------------------------------------------------------        
@angular-devkit/architect       0.1601.6
@angular-devkit/build-angular   16.1.6
@angular-devkit/core            16.1.6
@angular-devkit/schematics      16.1.6
@angular/cli                    16.1.6
@schematics/angular             16.1.6
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```

**Comment by JoostK** [comment]
This is because `ResizeObserver` is not patched by ZoneJS by default, see #48890, #45105 and #31695.

You could load the `ResizeObserver` patch as a polyfill yourself, or ensure that `next`'ing into the subject from within the `ResizeObserver` callback uses `NgZone.runInAngular` to reenter the Angular zone and trigger change detection as a result.
