### ISSUE TITLE
Add a `provideTranslation` function to the framework (plus add a guideline to create `withXxx` features from third-party libs like ngx-translate

### ISSUE THREAD

**Issue by LcsGa** [angular/angular#51264]
### Which @angular/* package(s) are relevant/related to the feature request?

localize

### Description

With a colleague of mine, we've made a provideTranslation function today that can be used like this
```ts
...
providers: [
    ...
    provideTranslation('fr-FR', localFr)
]
```
This function would do two main things:
- set the `LOCAL_ID` to the locale passed as arg
- `registerLocaleData` within an APP_INITIALIZER, with the localeData passed as an argument

> It's the very first step, we could probably improve it a lot by providing more options like an autoDetect option, or even a factory that should return languages based on some logic or anything else I can't think of right now.

In addition, we've added rest arguments that take a `translationFeatures` (not sure about the name yet) that could be used by any third-party libraries to provide a way to configure their features.
As we use ngx-translate, we've made a `withNgxTranslate(...)` function that can be used like this:
```ts
...
providers: [
    ...
    provideTranslation('fr-FR', localFr, withNgxTranslate(
        { path: './assets/i18n', extension: '.json', namespace: 'app' },
        { ... }
    ))
]
```
> I'm not sure yet if it could be implemented like this today in the framework but for every apps we have in our organization, that's what we'd currently use. If we moved to transloco, we would then implement a `withTransloco` function to work the same way.

If things like this could be added to the framework, I think it'd be a great addition and it could provide a sort of _guideline_ for third-party libs maker (just like there is a guideline from RxJS to create your custom operators)

> I've never used the i18n package made by angular so, as we currently made it, it may be incomplete or not adapted yet but, with the help of the community we could finally have an easy way to set up translations in our apps

> If this feature request harvests all the features specs needed for such a providefn and withXxx functions, it could be my very first contribution on angular :smile: (plus I could also open PRs on third-party libs like ngx-translate to make the withXxx functions)

### Proposed solution

Like I said above, a `provideTranslation` function with, for example a `locale` and `localeData` arguments.

In addition add a `...transaltionFeatures: TranslationFeature[]` to let third-party libraries maker create their `withXxx` functions to configure their lib (like `withNgxTranslate` for example)

### Alternatives considered

Instead of the first two arguments we could pass an object of options in wich we could either :
- add the locale / localeData
- or an autoDetect `boolean` option
- or even a factory to provide locales based on a specific logic
- or anything else I could not think of

**Comment by alxhub** [comment]
I'm going to close this as something we don't plan to implement. The feature described is a little vague, and it's unclear what use cases it would enable or improve.

Also see #36757.
