### ISSUE TITLE
Clarification on @ContentChild Selector Documentation

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular#51272]
### Describe the problem that you experienced

In some places the documentation says we can use element selectors and in other places it says we have to use a Template tag.

We explored the issue in this Stackoverflow post.
https://stackoverflow.com/questions/76831170/getting-a-projected-header-element-using-contentchild/76831840?noredirect=1#comment135451487_76831840

### Enter the URL of the topic with the problem

https://stackoverflow.com/questions/76831170/getting-a-projected-header-element-using-contentchild/76831840?noredirect=1#comment135451487_76831840

### Describe the actions that led you to experience the problem

We've summarized it in this Stackoverflow post
https://stackoverflow.com/questions/76831170/getting-a-projected-header-element-using-contentchild/76831840?noredirect=1#comment135451487_76831840

### Describe what you want to experience that would fix the problem

https://stackoverflow.com/questions/76831170/getting-a-projected-header-element-using-contentchild/76831840?noredirect=1#comment135451487_76831840

### Add a screenshot if that helps illustrate the problem

https://stackoverflow.com/questions/76831170/getting-a-projected-header-element-using-contentchild/76831840?noredirect=1#comment135451487_76831840

### If this problem caused an exception or error, please paste it here

```true
https://stackoverflow.com/questions/76831170/getting-a-projected-header-element-using-contentchild/76831840?noredirect=1#comment135451487_76831840
```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
https://stackoverflow.com/questions/76831170/getting-a-projected-header-element-using-contentchild/76831840?noredirect=1#comment135451487_76831840
```

### Provide any additional information here in as much as detail as you can

```true
https://stackoverflow.com/questions/76831170/getting-a-projected-header-element-using-contentchild/76831840?noredirect=1#comment135451487_76831840
```

**Comment by JoostK** [comment]
Would #51195 provide a sufficient clarification?

**Comment by JeanMeche** [comment]
It has been renamed "locator" in the new docs : https://angular.dev/guide/components/queries
