### ISSUE TITLE
FormGroup validators setting

### ISSUE THREAD

**Issue by genopapashvili** [angular/angular#51284]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

I thought to make clean code and did this:
 `this.formGroup = fb.group({
      input1: [""],
      input2: [""]
    }, {validators: [Validators.required]})`
but it does not works properly.

I thought not to make the same validations on the  each of the FormControl and instead did it on FormGroup, I thought in this way I bound each of them but either I don't understand something or there is a **bug**. I am learning Angular  and it might be my mistake

html:
`<form (ngSubmit)="onSubmit()" [formGroup]="formGroup">
  <input type="text" formControlName="input1">
  <input type="text" formControlName="input2">
  <button [disabled]="formGroup.invalid">Click Me</button>
</form>`

**if the fields are empty or have texts the view of the button is the same** 

### Please provide the environment you discovered this bug in (run `ng version`)

```true
node --version
v18.17.0

npm --version
9.8.1
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.1.4
Node: 18.17.0
Package Manager: npm 9.8.1
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1601.4 (cli-only)
@angular-devkit/core         16.1.4 (cli-only)
@angular-devkit/schematics   16.1.4 (cli-only)
@schematics/angular          16.1.4 (cli-only)
```

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
