### ISSUE TITLE
feat(test): ability to configure providers on a per-spec basis

### ISSUE THREAD

**Issue by btford** [angular/angular#5128]
Right now, the only way to configure DI in tests is to use `beforeEachProvider`. I need the ability to configure providers on a per-spec basis for routing (currently I have to create extraneous `describe` blocks to overcome this limitation).

The `inject` helper could be extended to include this functionality, for instance.

**Comment by juliemr** [comment]
Syntax proposal:

```js
      it('should set up a provider for just one test', inject([A, B], (a, b) => {
        // do stuff
      }, () => [provide(A, {useValue: 'a'}), provide(B, {useClass: BImpl})]));
```

or

```js
      it('should set up a provider for just one test', withProviders(
        () => [provide(A, {useValue: 'a'}), provide(B, {useClass: BImpl})]
      ).inject([A, B], (a, b) => {
        // do stuff
      }));
```

Thoughts? I'm partial to option 2 because the providers come first and it's more explicit what they're doing.

**Comment by btford** [comment]
I also like option 2

**Comment by juliemr** [comment]
An additional thing to think about: eventually, when TS supports it, we'd like to be able to do:

```js
it("should do stuff", @Inject() (someInjectable: SomeInjectable) => {
});
```

I'm not sure if there'd be a nice way to fit per-spec providers in to that.

**Comment by btford** [comment]
I can think of several ways to add providers there, but none of them stick out as particularly nice. :/

**Comment by juliemr** [comment]
What about:

```js
// For now
it('should set up a provider for just one test', withProviders(
  () => [provide(A, {useValue: 'a'}), provide(B, {useClass: BImpl})]
).inject([A, B], (a, b) => {
  // do stuff
}));

// In the future of TS
it('should set up provider for just one test', withProviders(
  () => [provide(A, {useValue: 'a'}), provide(B, {useClass: BImpl})]
).run(@Inject(A) a, @Inject(B) b) => {
 // do stuff
}));
```

**Comment by btford** [comment]
Works for me. I'm not too picky about the implementation.

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166505.
------------------------------------------------------------------------------------------------------------


[[e1e10113c369bf5e01e0202663b1e48fe486cafd-673073913]]
