### ISSUE TITLE
Add possibility to have global directives

### ISSUE THREAD

**Issue by yurakis** [angular/angular#51297]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Now that standalone components feature is released, it is a good idea to get rid of modular architecture.

But that idea is coming with a requirement: we need to import everything what is needed right to standalone components. At first glance it sounds attractive, we import only something what is needed in that component. But what about global directives?

For example, let's imagine directive like `@Directive({ selector: 'form' })` which does something to each form element.

In modular architecture this directive is imported to some shared module which will be imported into feature modules.
In module-less architecture we would need to import it into each standalone component.

The main concern here is that it can be easily missed. There won't be any compilation or runtime error and IDE will not highlight it.

### Proposed solution

Extend `Directive` decorator with `providedIn` property like in `Injectable`. E.g.
```typescript
@Directive({
  selector: 'form',
  providedIn: 'root',
})
```

### Alternatives considered

The alternative way is to create a module with global directives and import it to each standalone component even if it is not used there.

**Comment by spock123** [comment]
I am not sure I understand the question.
Nothing prevents you from making a shared "global" index-file, exporting all the commonly used components and pipes.

So if you want a global pipe, make a /global/index.ts where you export an array with the components/pipes you want. Then just do `import { MyGlobalStuff } from '@global'` and import that.

**Comment by JeanMeche** [comment]
It looks like @yurakis doesn't want to add those directives in the components `imports`. That would go against the philosophy of standalone components.

**Comment by yurakis** [comment]
@JeanMeche Yeah, that is not about imports. I was asking about the way to affect all matching selectors automatically without importing it directly to components.

**Comment by mlc-mlapis** [comment]
@yurakis But selective imports on a component level in the standalone components world were one of the default assumptions when leaving the NgModules concept. You are turning the rudder opposite and creating some NgModule V2.😄

**Comment by pkozlowski-opensource** [comment]
> @JeanMeche Yeah, that is not about imports. I was asking about the way to affect all matching selectors automatically without importing it directly to standalone components.

@yurakis standalone components were design to have explicit dependencies. We've explicitly called out NgModules "hidden" dependencies as the problem in the [original RFC](https://github.com/angular/angular/discussions/43784):

> reading component code isn’t sufficient to understand the component behavior:
a reader must track down the component’s NgModule to understand the component’s dependencies.

I'm going to close this issue as the original design goals and thinking still hold today - we want to be explicit about dependencies in a template.

**Comment by yurakis** [comment]
@pkozlowski-opensource Got it. Thank you for an explanation!
