### ISSUE TITLE
New tag

### ISSUE THREAD

**Issue by danilokorber** [angular/angular#51305]
### Which @angular/* package(s) are relevant/related to the feature request?

animations, bazel, common, compiler-cli, compiler, core, elements, forms, language-service, localize, platform-browser-dynamic, platform-browser, platform-server, router, service-worker, upgrade

### Description

I am currently using the tag `latest` to be always up-to-date. But when a major version comes out I am being updated to this new major version, which can be problematic.

### Proposed solution

My suggestion is to already add the tag v16-lts to the latest v16 version, as it is done for older version. So when 17 comes out, I will not be updated automatically to the new major version.

### Alternatives considered

Use "^16.0.0", but in this case I always have to run `npm install` and `npm update` to ensure that I am on the latest version.

**Comment by JoostK** [comment]
I don't understand; what is `latest` supposed to refer to if it isn't the active version? To me, requesting `latest` is deliberately selecting the latest version, including majors.

**Comment by JeanMeche** [comment]
Yes and why wouldn't `^16.0.0` fit your needs ?

**Comment by alxhub** [comment]
> Use "^16.0.0", but in this case I always have to run `npm install` and `npm update` to ensure that I am on the latest version.

Is this not true for `latest` or `v16-lts` as well? I don't think tagged versions have any different behavior in Node than version ranges.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
