### ISSUE TITLE
Add a mechanism to reload a component

### ISSUE THREAD

**Issue by darius-iko** [angular/angular#51302]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

App.component.html:
`<div><child-component></child-component></div>`

Add a mechanism to reload child component in app component so that the child component can be recreated and go through the initial lifecycle.

### Proposed solution

1. By adding ViewChild to refer to the child component and call ParentComponent.reloadView(childComponent).
2. By adding a key to the child component. If the key is changed, then the component will be auto-reload like the one in React. 

### Alternatives considered

App.component.html:
`<div><child-component *ngIf="refreshFlag"></child-component></div>`

App.component.ts:
`
this.refreshFlag = false;
setTimeout(() => {
    this.refreshFlag = true;
}, 0);
`

**Comment by alxhub** [comment]
Hi @darius-iko,

Can you give some detail on what problem(s) or use cases you would expect this feature to address?

**Comment by darius-iko** [comment]
Hi @alxhub 

Sometimes the child component from a third-party library initializes the view information in the ngOnInit or constructor, and the changes to the value of the model binding to the component are not reflected directly in the view, and because of that, we need to reload the component to make it reflected.

**Comment by darius-iko** [comment]
Sometimes when the component is very complicated (contains filter and sort form, table and pagination), to reset the component, we have to reset everything in the component one by one. It is just more efficient if we just reload the component to reset the state.

**Comment by mlc-mlapis** [comment]
@darius-iko It seems all the reasons imply only solving problems in the conceptual design of an application or third-party components.

**Comment by darius-iko** [comment]
For third-party components, it will take years for them to fix it to allow handling for any model changes. So the only workaround is to refresh the component.

**Comment by pkozlowski-opensource** [comment]
> For third-party components, it will take years for them to fix it to allow handling for any model changes. 

Some of the projects are well maintained and pretty responsive so I would suggest opening issues on the relevant projects. And considering alternatives for ones that don't work correctly and / or are not well maintained.

> So the only workaround is to refresh the component.

I don't think we want to build such workarounds into the framework. You can always inject `ChangeDetectorRef` and call `detectChanges` on it to refresh a given component and all its children - the work-around exists but again, this is not the solution for questionable design.
