### ISSUE TITLE
styles are not rendering via innerHTML

### ISSUE THREAD

**Issue by ilapavuluri** [angular/angular#51304]
### Which @angular/* package(s) are the source of the bug?

elements

### Is this a regression?

No

### Description

Hi Team,

I am using angular 13.3.7.

I create my own custom build(https://ckeditor.com/ckeditor-5/online-builder/), get the ckeditor.js and add it on my angular project.
My problem is that all the style from fontColor plugins or Alignment plugins works only on the editor, not in the output.

import * as Editor from '../../../ckeditor.js'
import { ChangeEvent } from '@ckeditor/ckeditor5-angular/ckeditor.component';

export class TestComponent implements OnInit {
    public editor = Editor;
    public editorData = '';

    config: any = {
      fontColor: {
            colors: [
                {
                    color: 'hsl(0, 0%, 0%)',
                    label: 'Black'
                },
                {
                    color: 'hsl(0, 0%, 30%)',
                    label: 'Dim grey'
                },
                {
                    color: 'hsl(0, 0%, 60%)',
                    label: 'Grey'
                },
                {
                    color: 'hsl(0, 0%, 90%)',
                    label: 'Light grey'
                }
            ]
        },
	toolbar: [
	    'heading',
	    'fontSize',
	    '|',
	    'bold',
	    'underline',
	    'italic',
	    'link',
	    'fontColor',
	    'bulletedList',
	    'numberedList',
	    '|',
	    'alignment',
	    'indent',
	    'outdent',
	    '|',
	    'undo',
	    'redo'
	]
    };

    public onChange( { editor }: ChangeEvent ) {
	const data = editor.getData();
	this.editorData = data
        console.log("DATA =>", this.editorData );
    }

the console.log prints all the data with styles:

h4 style="text-align:center;"
<span class="text-small">DESCRIPTION</span>
/h4
h4<br>Contexte/h4
p style="text-align:right;">
<br>
<span style="color:hsl(0,0%,0%);">Dans le cadre du ...</span>
/p

But on my template where I print the data:

div [innerHtml]="testData">div

the testData wont have any styles:
div _ngcontent-c1="">
<h4><span class="text-small">DESCRIPTION</span></h4>
<h4><br>Contexte</h4>
<p><br>
<span>Dans le cadre du...</span>
</p>
/div

How I can keep all the styles?

**Using bypassSecurityTrustHtml resolved the issue, but this will bypass the sanitization is there a better way to handle this?**
Appreciate your help, without  this I can't use fontColor plugin at all.

Thanks
Ashok.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
