### ISSUE TITLE
Spanish Locale - dots is missing from month name for 'medium' (MMM) month format

### ISSUE THREAD

**Issue by patwaswapnil** [angular/angular#51317]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I recently upgraded my application from angular 11 to angular 14. 

It seems there's an issue with the medium format for Spanish language where the dot is missing from the month name.

This worked correctly in Angular 11.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-14-demo-z2jd6t Angular 14

### Please provide the exception or error you saw

```true
Working correctly 
https://stackblitz.com/edit/angular-11-new-yrcbht Angular 11
Expression: {{ '2024-08-06T18:30:00.000Z' | date: 'medium':undefined:'es-ES' }} 
Output: Date - 7 ago. 2024 0:00:00

Issue with 
https://stackblitz.com/edit/angular-14-demo-z2jd6t Angular 14
Expression: {{ '2024-08-06T18:30:00.000Z' | date: 'medium':undefined:'es-ES' }} 
Output: Date - 7 ago 2024 0:00:00
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.8
Node: 14.21.3
Package Manager: npm 6.14.18
OS: win32 x64

Angular: 14.3.0
... core

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1402.8
@angular-devkit/build-angular       14.2.8
@angular-devkit/core                14.2.8
@angular-devkit/schematics          14.2.8
@angular/animations                 14.2.9
@angular/cdk                        14.2.6
@angular/cli                        14.2.8
@angular/common                     14.2.12
@angular/compiler                   14.2.9
@angular/compiler-cli               14.2.9
@angular/flex-layout                14.0.0-beta.41
@angular/forms                      14.2.9
@angular/language-service           14.2.9
@angular/material                   14.2.6
@angular/material-moment-adapter    14.2.6
@angular/platform-browser           14.2.9
@angular/platform-browser-dynamic   14.2.9
@angular/router                     14.2.9
@schematics/angular                 14.2.8
rxjs                                7.5.7
typescript                          4.8.4
```

### Anything else?

Working correctly in angular material datepicker:
![image](https://github.com/angular/angular/assets/12543693/62d9b571-41f0-4399-9b29-741bb034bfcd)

**Comment by JeanMeche** [comment]
FWIW, the native API `new Date().toLocaleDateString('es-ES', {month: 'short'})` returns `ago`.

**Comment by JoostK** [comment]
Angular sources its localization data from the CLDR repository, where version 38 has removed the trailing dot in Spanish month abbreviations. I can't find the original ticket on CLDRs side for the reasoning of these changes, but they are outside of Angular's control.
