### ISSUE TITLE
input type=radio not updating form value

### ISSUE THREAD

**Issue by Briareos** [angular/angular#5133]
I couldn't find an open issue about radio inputs. Some said that radios are not implemented at all, others that it's a bug.

I've created a plunker to demonstrate it http://plnkr.co/edit/lAt5GvVXS2qJguxlRGW4?p=preview

**Comment by donskifarrell** [comment]
I'm having the same problem. He's another plunkr example to demonstrate:
http://plnkr.co/edit/N1kUB2AJiJv0HN2VYEA5
