### ISSUE TITLE
Bootstrap multiple standalone components

### ISSUE THREAD

**Issue by emeryao** [angular/angular#51331]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

bootstrap multiple standalone components is now not supported whille it can be done with `NgModule`

there is `index.html` like below
```html
<html>
<body>
    <some-ng-component></some-ng-component>
    <app-root></app-root>
</body>
</html>
```

both the `app-root` and `some-ng-component` are components declared by `@Component`

with `NgModule` both the components can be bootstrap at the same time by `app.module.ts` and `main.ts`
```typescript
// app.module.ts
@NgModule({
    bootstrap: [
        AppComponent,
        SomeNgComponent,
    ],
})
export class AppModule { }

// main.ts
platformBrowserDynamic().bootstrapModule(AppModule)
    .catch(err => console.error(err));
```

but with standalone components it can only bootstrap one componet at a time
```typescript
// main.ts
bootstrapApplication(AppComponent, appConfig)
    .catch(err => console.error(err));
```

### Proposed solution

multiple standalone components can be bootstrapped in `main.ts`

may be a component array will be accepted in the `bootstrapApplication` function like
```
// main.ts proposed
bootstrapApplication([AppComponent, SomeNgComponent], appConfig)
    .catch(err => console.error(err));
```

### Alternatives considered

the other component I want to bootstrap with AppComponent may often has some non-biz logic like `titlebar` or `action bar` or a welcome screen that should be initialized at the earliest time

---

Sorry for my poor English 😅

**Comment by pkozlowski-opensource** [comment]
You can still do this: 

```typescript
const appRef = await bootstrapApplication(AppComponent, appConfig);
appRef.bootstrap(SomeNgComponent)
```


The API might be less convenient but allows start multiple components as part of one application. Would this work for you?

ref.: https://angular.io/api/core/ApplicationRef#bootstrap

**Comment by emeryao** [comment]
Thanks for you reply @pkozlowski-opensource 

I have tried with codes below
```typescript
// main.ts
bootstrapApplication(AppComponent, appConfig)
    .then(appRef => {
        appRef.bootstrap(SomeNgComponent);
    })
    .catch(err => console.error(err));
```

```html
<!-- index.html -->
<html>
<body>
    <some-component [someInput]="'input-value'"></some-component>
    <app-root></app-root>
    <some-component [someInput]="'input-value'"></some-component>
</body>
</html>
```

and there is only one (the first one) SomeNgComponent has been rendered and the `@Input` decorator seems not working on the first `<some-component>` and the last `<some-component>` seems not rendered at all

```html
<!-- rendered index.html -->
<html>
<body>
    <some-component [someInput]="'input-value'" _nghost-ng-cXXXXXX ng-version="16.2.0">
        <!-- content in SomeNgComponent -->
    </some-component>
    <app-root _nghost-ng-cXXXXXX="" ng-version="16.2.0">
        <!-- content in SomeNgComponent -->
    </app-root>
    <some-component [someInput]="'input-value'">
        <!-- no content / no nghost / no ng-version -->
    </some-component>
</body>
</html>
```

**Comment by emeryao** [comment]
I have another trial using `NgModule` with the codes above and it seems the same that the last `<some-component>` is not rendered
