### ISSUE TITLE
Can we check if the new version is updated or not while using the service worker 

### ISSUE THREAD

**Issue by moon-web75** [angular/angular#51349]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

#1 When i upload new build we only get first-time version update message but we need second-time version update message

#2 Can we get every time which version is old and new

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by moon-web75** [comment]
@JoostK Thanks

#2 Can we get every time which version is old and new ?
