### ISSUE TITLE
Date Pipe Format issue

### ISSUE THREAD

**Issue by sauravgaursmith** [angular/angular#51348]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

Using angular date pipe like this :
TS File:

`dateVar = Date.now();`

Template File: 
`<span> {{ dateVar | date:'MMM dd, yyyy at hh:mm a' }}</span>`

Output (example): 

`Aug 14, 2023 AMt 12:17 AM` --Notice **AMt** in place of **at**

It should be like this - `Aug 14, 2023 at 12:17 AM`

### Please provide a link to a minimal reproduction of the bug

NA

### Please provide the exception or error you saw

```true
Nothings
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.9
Node: 14.15.5
Package Manager: npm 6.14.11
OS: linux x64

Angular: 13.3.9
... animations, cli, common, compiler, compiler-cli, core, forms
... google-maps, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.9
@angular-devkit/build-angular   13.3.9
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.3.9
@angular/cdk                    13.3.7
@angular/flex-layout            13.0.0-beta.38
@angular/language-service       13.3.11
@angular/material               13.3.7
@schematics/angular             13.3.9
ng-packagr                      13.3.1
rxjs                            7.5.5
typescript                      4.6.4
```

### Anything else?

Feature to get AM / PM in smaller case base on A or a is passed in format.

**Comment by JoostK** [comment]
You can use

```
"MMM dd, yyyy 'at' hh:mm a"
```

This should be clarified in the docs.

**Comment by sauravgaursmith** [comment]
Thanks for response @JoostK . It helped.

**Comment by Nabagata** [comment]
I can take this up!

**Comment by JeanMeche** [comment]
Feel free to open a PR !

**Comment by hirowf** [comment]
> You can use
> 
> ```
> "MMM dd, yyyy 'at' hh:mm a"
> ```
> 
> ([StackBlitz](https://stackblitz.com/edit/stackblitz-starters-c5uozt))
> 
> This should be clarified in the docs.

I think it'd be cool to add this info to the Custom Format Options on https://angular.io/api/common/DatePipe. Such a cool find!

**Comment by JoostK** [comment]
Done in #51359
