### ISSUE TITLE
feature: throw an error in case of `afterRender` misuse. 

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular#51343]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

It'd be great if we could throw an error if a patched API is called within an `afterRender()` callback

For example : 

`afterRender(() => setTimeout(() => { ...}, 1000);`  will run into an infinte render loop

Currently, NG102 is only thrown when a new CD cycle is fired from the context of an `afterRender` (for example `afterRender(() => cd.detectChanges())`

### Proposed solution

Throw an error to prevent an infinite loop. 

### Alternatives considered

¯\\_(ツ)_/¯ let the dev close his browser tab and hope (s)he learns from his own mistake.

**Comment by alxhub** [comment]
I wonder if `afterRender` should automatically run outside the Angular zone, so it doesn't trigger new rounds of change detection. That's worth thinking about.

**Comment by AndrewKushnir** [comment]
Closing since PR https://github.com/angular/angular/pull/51385 is now merged.
