### ISSUE TITLE
Cannot listen to an event multiple times on a single element

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular#51344]
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

No

### Description

See this repro : 

```
@Component({
  selector: "my-app",
  standalone: true,
  template: `<button #button id="toggle">click</button>`,
})
export class App implements AfterViewChecked {
  @ViewChild("button") button!: ElementRef<HTMLElement>;
  render$$ = new Subject<void>();

  ngAfterViewInit() {
    this.render$$
      .pipe(switchMap(() => fromEvent(this.button.nativeElement, "click")))
      .subscribe(() => console.log("--- click 1 ---"));
    this.render$$
      .pipe(switchMap(() => fromEvent(this.button.nativeElement, "click")))
      .subscribe(() => console.log("--- click 2 ---"));
  }

  ngAfterViewChecked() {
    this.render$$.next();
  }
}

bootstrapApplication(App);
```

`--- click 2 ---` is never logged. 

This is likely related to the zone.js patching because there is no issue when providing `ɵNoopNgZone`. 

But I also noted that I cannot reproduce this issue without firing an RxJS observable from a lifecycle methods like `ngAfterViewChecked`, `ngDoCheck` or from the new `afterRender()` hook. 

I really can't explain what's happening. 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-htmdky?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

On v16.2 and zone `0.13.1`

**Comment by JoostK** [comment]
I haven't looked into it, but I do have an explanation as to why this happens: Angular evaluates its event listeners in the Angular zone, and each individual `NgZone.run` call triggers change detection. Therefore, the `render$$` subject emits, causing the `switchMap` to unsubscribe from the event listener that is still pending, effectively cancelling the event.

This problem can be avoided by turning on event coalescing, such that change detection only runs after all event listeners have been invoked.

**Comment by JeanMeche** [comment]
Right on point Joost ! I'll close this as "work as intended" !
