### ISSUE TITLE
Refenced link does not exist Finding the current version of Angular

### ISSUE THREAD

**Issue by akib1997** [angular/angular#51366]
### Describe the problem that you experienced

The page does not exist in https://github.com/angular/angular/blob/main/aio/content/guide/updating.md#finding-the-current-version-of-angular. Here the link  [Angular documentation](https://github.com/angular/angular/blob/main/aio/content/guide/docs) does not exist.

### Enter the URL of the topic with the problem

https://github.com/angular/angular/blob/main/aio/content/guide/updating.md#finding-the-current-version-of-angular

### Describe what you were looking for in the documentation

I was Finding the current version of Angular.

### Describe what you want to experience that would fix the problem

Adding this link  [Releases](https://github.com/angular/angular/releases) can be a solution and this link also be helpful https://angular.io/guide/releases#actively-supported-versions.

**Comment by JeanMeche** [comment]
The documentation is meant to be read on https://angular.io not the repo directly.
