### ISSUE TITLE
Refused to apply inline style because it violates the following CSP nonce-xxx in platform-browser.mjs

### ISSUE THREAD

**Issue by sssunsha** [angular/angular#51365]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

No

### Description

I have updated my angular project to V16.1.0, followed the pr(https://github.com/angular/angular/pull/49444) to enable the `CSP_NONCE` token, and replaced the 'unsafe-inline' in  style-src with `nonce-UZQyMzNkM2IyMjQxNjE5NTlhNzFmZmI5NzI5ZTA1NjE=` for example. And add `<app-root ngCspNonce="UZQyMzNkM2IyMjQxNjE5NTlhNzFmZmI5NzI5ZTA1NjE="></app-root>`. However, I still found `Refused to apply inline style` issues in platform-browser.mjs

### Please provide the exception or error you saw

```true
platform-browser.mjs:591 
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-UZQyMzNkM2IyMjQxNjE5NTlhNzFmZmI5NzI5ZTA1NjE='". Either the 'unsafe-inline' keyword, a hash ('sha256-biLFinpqYMtWHmXfkA1BPeCY0/fNt46SAZ+BBk5YUog='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.0
Node: 18.10.0
Package Manager: npm 8.19.2
OS: darwin x64

Angular: 16.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.0
@angular-devkit/build-angular   16.1.0
@angular-devkit/core            13.3.10
@angular-devkit/schematics      13.3.10
@schematics/angular             16.1.0
rxjs                            7.8.1
typescript                      4.9.5
```

### Anything else?

<img width="1785" alt="image" src="https://github.com/angular/angular/assets/11864511/63396596-29bb-4ac0-bffb-944ad8f1b803">

<img width="845" alt="image" src="https://github.com/angular/angular/assets/11864511/5851ecb4-641e-493b-933e-2f05863adda5">

**Comment by crisbeto** [comment]
We have information in the Security guide on how to provide a nonce when your app is using CSP: https://angular.io/guide/security#content-security-policy

**Comment by sssunsha** [comment]
yes, I have read this doc and followed the steps, and most parts of inline styles can work well with nonce attributes, however, only the one file still has errors.

**Comment by crisbeto** [comment]
Can you see what styles are in the problematic style tag? E.g. is it component styles or something else?

**Comment by sssunsha** [comment]
not a component style, the error was pointed to `el.steAttribute(name, value)` of `platform-browser`, please check the attachments. Thanks.

**Comment by Peter-Zakharevich** [comment]
I can confirm that this behavior reproducing. We've also migrated our application to Anguar 16, configurate nonce to work via `ngCspNonce` attribute and can observe the same behavior, in console we can see a lot of errors that pointing to main bundle and 
 error is on the line `Mt.setAttribute(gt, We)` inside of it

**Comment by damienbod** [comment]
I have the same problem, works locally but when I build the production, the *ngCspNonce* gets replaced with ngcspnonce

Kind regards Damien

**Comment by JoostK** [comment]
> I have the same problem, works locally but when I build the production, the **ngCspNonce** gets replaced with **ngcspnonce**

HTML attributes are not case-sensitive, that replacement does not affect the ability to extract the CSP nonce.

**Comment by damienbod** [comment]
Thanks, still a bug, just with a different cause then, this does not work with the mention problem in the issue

**Comment by JoostK** [comment]
Please provide a reproduction for this issue to become actionable.

**Comment by gs-scooter** [comment]
@sssunsha - I would recommend checking any third party UI packages that you have in your project. I'm encountering the same problem, and in the call stack I was able to see that the CSP issue was triggered by our using Infragistics' IgniteUI package for Angular. There's a section in their grid cell component that contains a template which has an inline style defined. I haven't figured out a resolution as of yet.

**Comment by alxhub** [comment]
I'm going to close this issue as without a reproduction, it's not something we can act on. Please feel free to open a new issue with a minimal reproduction if you're still encountering the problem.
