### ISSUE TITLE
bug: Firefox reload the page when issuing a http request subscribe

### ISSUE THREAD

**Issue by heuism** [angular/angular#51362]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Ionic Framework Version
v7.x

Current Behavior
call the http request (for example in this case: login) and the app just immediately reload (or the page) like you haven't even triggered the button click to send request

Expected Behavior
call http request subscribe for the return data then will return the data and trigger other part of the code and move forward

Steps to Reproduce
Have directive to call for submit
override onSubmit(formGroup: WrapFormGroup) {
this._state.next('pending');

const formData = formGroup.value as FormData;

const req$ = this.onRequest(formData, formGroup);
req$.pipe(takeUntil(this.destroy$)).subscribe({
  next: (res) => {
    this._state.next('success');
    this._data.next(res);
    this.onSuccess?.(formData, res, formGroup);
  },
  error: (err: unknown) => {
    this._state.next('error');
    if (err instanceof HttpErrorResponse) {
      const errors = this.onMapError?.(formData, err) ?? err.error?.errors;
      this._errors.next(errors);
    }
    this.onError?.(formData, err, formGroup);
  },
});
}

3. the code didn't pass the subscribe to go to next or error but just reload the page (or the app) in Firefox

### Ionic Info

Ionic 7.1.1

### Additional Information

Hi guys,

I am running into an issue in Firefox and potentially in Edge.

We are calling subscribe on a HttpRequest that will return data from BE and we use directive for this approach

I have done some debug and in the pipe().subscribe() the code keep waiting and doing some checking then it triggers page reload or something in a similar sense and the page is back to the original state (maybe?)

Video issue on Firefox

https://www.loom.com/share/dcb4ffa0a8164bdb94796a60c074dac6

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.2.8
Node: 18.16.0 (Unsupported)
Package Manager: npm 9.5.1 
OS: darwin arm64

Angular: 14.2.8
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.8
@angular-devkit/build-angular   14.2.8
@angular-devkit/core            14.2.8
@angular-devkit/schematics      14.2.8
@angular/cdk                    14.2.5
@schematics/angular             14.2.8
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
