### ISSUE TITLE
Release notes on blog not tagged since Angular 10

### ISSUE THREAD

**Issue by ddebree** [angular/angular#51363]
### Describe the problem that you experienced

Reading the updating documentation (https://github.com/angular/angular/blob/main/aio/content/guide/updating.md) it refers to the release notes/announcements. Following that link (https://blog.angular.io/tagged/release%20notes) you are taken to a page that hasn’t been updated to reflect any releases since angular 10. I suspect it is just due to the releases not being tagged correctly. 

### Describe what you were looking for in the documentation

It should show all major releases

**Comment by JeevanMahesha** [comment]
hi @ddebree thanks for sharing I will pickup this and raise the PR

**Comment by alxhub** [comment]
This is resolved on angular.dev.
