### ISSUE TITLE
Not possible to navigate away from the named outlet

### ISSUE THREAD

**Issue by usarskyy** [angular/angular#51373]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

I have an app with complex routing structure where named outlets are used extensively. [Accordingly to the official documentation](https://angular.io/guide/router-tutorial-toh#clear-secondary-routes) I should be able to navigate away from the named outlet by simply null-ying it's navigation path:

```
closePopup() {
  // Providing a `null` value to the named outlet
  // clears the contents of the named outlet
  this.router.navigate([{ outlets: { popup: null }}]);
}
```

Unfortunately this is not possible at all unless I use *a parent route* of a route where named outlet is located.

Maybe the problem is that a named outlet is used not on the app's root level but inside a lazy-loaded module? Or that the parent of the named outlet has an empty path?

![image](https://github.com/angular/angular/assets/1206777/a00fbeda-f1bb-40db-aaa2-7d15b78bb29f)

If this is expected behavior I would be thankful for an explanation why the code from the official documentations doesn't work in my case and what is going on underneath. Why a parent route is required in this case?

### Please provide a link to a minimal reproduction of the bug

https://github.com/usarskyy/angular-named-outlet-bug

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.5
Node: 16.13.0
Package Manager: npm 8.19.0
OS: win32 x64

Angular: 15.2.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.9
@angular-devkit/build-angular   15.2.9
@angular-devkit/core            15.2.9
@angular-devkit/schematics      15.0.5
@angular/cli                    15.0.5
@schematics/angular             15.0.5
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by atscott** [comment]
This is working as expected. Commands are applied relative to a particular point in the activated route tree. The documentation had been updated in https://github.com/angular/angular/pull/40272 to clarify the nature of the example and why it works but unfortunately it looks like this information got lost along the way. I will send a new PR to update the documentation again.

**Comment by usarskyy** [comment]
@atscott Thx for a quick answer!

_Commands are applied relative to a particular point in the activated route tree_

This I understand and made necessary changes in the code but your answer doesn't answer the main question: why is *parent* of the route required?
![image](https://github.com/angular/angular/assets/1206777/c8ec1efb-c2a0-40ff-a059-846a1d1f1048)

A named outlet is a child of ShellComponent's route (see a screnshot in my previous comment), I use ShellComponent's route to navigate to the named outlet BUT a parent of the ShellComponent's route is required to close it. If `close2()` would have worked, it would be completely logical behavior but it didn't.

**Comment by usarskyy** [comment]
@pkozlowski-opensource could you please reopen this issue. The documentation is broken for sure, so above mentioned fix is required. But in my opinion even the new version of the docs doesn't explain why my example doesn't work as expected.

**Comment by usarskyy** [comment]
@atscott @pkozlowski-opensource I managed to create a better example that shows the root problem. Please check my repository, branches v2 and v3.

I thought that Angular Router operates like a browser rendering engine with shadow DOM but I was wrong (at least in this particular case). My initial implementation had URLs in the following format: `http://localhost:59312/admin/finances/(1/details/i-want-more//sidebar:notifications)`. It looks okay but in fact you don't see one additional level here:
![image](https://github.com/angular/angular/assets/1206777/8530478a-e57e-4f2a-96b3-1c08500046c0)

That is why your corrected example won't work (see v2 branch). The reason is that **a named outlet is attached to the first route in the hierarchy that has a name** and not to its direct parent like expected! Because of this I have to use ShellComponent's parent route (which as I wrote previously is completely against any logic).

If I artificially rename the module1's root route (see v3 branch) then suddenly your example starts working, as well as ShellComponent's route! Magic :))
![image](https://github.com/angular/angular/assets/1206777/1c856b9a-1957-407c-aab9-dd8a190a57e1)

IMHO, current router's implementation is broken because it requires knowledge about complete routing structure. Of course inside a single module this is still manageable, even though every update of your routes can potentially break navigation.

But what if a parent module changes it's routes? In the branch `v4` you can find a new commit that I personally would consider as a safe change since it doesn't change visible URL structure:
![image](https://github.com/angular/angular/assets/1206777/b8ae14c3-9d0b-4fe6-aaeb-fe4bd4514617)
But as appears it breaks navigation in named outlets (again!), since now one would require to use `.parent.parent` to exit the outlet.

**Comment by atscott** [comment]
>This I understand and made necessary changes in the code but your answer doesn't answer the main question: why is parent of the route required?

The parent route is the one that would have the reference to the named outlet. From itself, you're already inside the tree applying commands to the named outlet itself.

> a named outlet is attached to the first route in the hierarchy that has a name

Yes, there's nowhere else for it to go. Empty paths don't who up in the URL but the named outlet has to go _somewhere_.

> IMHO, current router's implementation is broken because it requires knowledge about complete routing structure. Of course inside a single module this is still manageable, even though every update of your routes can potentially break navigation.

I appreciate your opinion but it's not broken, though it can be difficult to use in some scenarios. The PR updates the docs to mention that you can close outlets from anywhere by directly modifying the `UrlSegmentGroup` for cases like this.

**Comment by usarskyy** [comment]
@atscott 
> The parent route is the one that would have the reference to the named outlet. 

Okay but this still doesn't answer the question: why a parent depends on the name of the route?

Also in this case we are talking about two types of parenting: one is the static direct parent defined in routes config (in my case this is a ShellComponent route) and second is a "runtime parent" that can change depending on your routes configuration (in the branch v2 the parent route is outside of my module, in v3 branch it is like expected). Sometimes they match, sometimes they don't and there is no explanation why.

> Yes, there's nowhere else for it to go. Empty paths don't who up in the URL but the named outlet has to go somewhere.

It is like you said when we are talking solely about the visual/text representation of the routes tree. Visual representation doesn't give you enough information about the exact routes configuration BUT a router works with virtual tree (that is a result of parsing of a URL matched with the routes config) and not just an array of strings, so a named outlet can be attached to an empty route.

For example, here is a URL `http://localhost:4200/admin/finances/1/details/i-want-more`. If a router's logic worked like you said I wouldn't see a node with an empty path because visually it is not represented in the URL. But it is there, it is in the the list `ActivatedRoute.pathFromRoot` and has all the attributes like `routeConfig` as expected:
![image](https://github.com/angular/angular/assets/1206777/cb65055d-57b9-45b4-a6b0-d9c7f8970b6b)

So, a router definitely knows about the correct full path to the outlet but by some reason doesn't attach this outlet to the correct parent.

> The PR updates the docs to mention that you can close outlets from anywhere by directly modifying the UrlSegmentGroup for cases like this

This is a workaround. Yes, it works but an expected behavior (opening and closing of an outlet with the same `ActivatedRoute`) is still broken.

**Comment by atscott** [comment]
> visual representation doesn't give you enough information about the exact routes configuration BUT a router works with virtual tree (that is a result of parsing of a URL matched with the routes config) and not just an array of strings, so a named outlet can be attached to an empty route.

Indeed, this is/was a big problem. The router has to deal with _both_ representations because the virtual representation has to be able to be represented as a concrete URL.

If you update your example to version 16, then each of your last 3 buttons in the v2 example actually work to close the outlet (Close (using ActivatedRoute.Parent), Close (using Shell's ActivatedRoute), and Close (using Shell's ActivatedRoute parent)). Pre-v16 the router would apply the commands against the router's URL tree, which was only the real representation of the URL as it appears in the browser bar. In v16 and beyond, the commands apply against the `ActivatedRoute` instead. 

For reference, the PR that made this change was https://github.com/angular/angular/pull/48508 and the related bugs were https://github.com/angular/angular/issues/42191, https://github.com/angular/angular/issues/38276, https://github.com/angular/angular/issues/22763,
and https://github.com/angular/angular/issues/48472. These things are _really_ difficult to change and the solution to this problem began in 2020 and involved several breaking changes in major versions along the way.

**Comment by usarskyy** [comment]
@atscott 

> These things are really difficult to change and the solution to this problem began in 2021 and involved several breaking changes in major versions along the way.

I can imagine this is not an easy 15 minutes walk in the park (( And as a person that [unfortunately] remembers a number of home-grown jQuery-based frameworks that preceded Angular, I really appreciate all your efforts, guys!

> If you update your example to version 16, then each of your last 3 buttons in the v2 example actually work to close the outlet

I've upgraded my sample to v16.2 and can confirm that it works almost as expected. If it worked like this in pre-v16 I certainly wouldn't have noticed anything wrong.
Why I say "almost"? Because as you wrote `last 3 buttons in the v2 example actually work` but it had to be just two buttons: one that uses `activatedRoute.parent` and `shellActivatedRoute`.
Latest router implementation still attaches a named outlet to the (in my opinion) wrong node but now it hides this issue, so it looks fine. Here is a screenshot of the routes:
![image](https://github.com/angular/angular/assets/1206777/e419564d-bf39-40ef-b004-d02ad0e7415c)

Currently I can't imagine any real world use-case where one could potentially notice that the outlet is not on its place, so case is closed :))

I sincerely tank you for your time and efforts!
