### ISSUE TITLE
http still has direct dependency on @reactivex

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#5137]
After a9b1270a5abea7bbbe34a9c357036a6bf3240ae4 landed, http no longer imports `Observable` from `@reactivex` but rather uses one exported by `angular2/angular2`. This is good since it limits http dependency.

Unfortunately we still got a place where Rx is dependent upon directly: in [mock_backend.ts](https://github.com/angular/angular/blob/f54ba3cc1bc6d8f489ff8b56d05e2f47d416c16e/modules/angular2/src/http/backends/mock_backend.ts#L8-L9)

mock_backend imports `Subject` and `ReplaySubject`. While we re-exporting `Subject` on `angular2\angular2` this is not the case for `ReplaySubject`. The current situation means that we need to either bundle entire RxJS with http or approach it as an external dependency: neither of the 2 is ideal.

@robwormald do you see any quick-wins here?

**Comment by pkozlowski-opensource** [comment]
Meh, even if we solve the above pb we still duplicate facades in each and every bundle and since `facade/async.ts` has dependency on RxJS we are pulling it in anyway....

So, I'm afraid that Rx needs to be an external dependency...

**Comment by robwormald** [comment]
Mock backend isn't imported anywhere, as far as I can tell, and so
shouldn't be built into a bundle, no?

**Comment by pkozlowski-opensource** [comment]
Yeh, it is probably a side effect of Rx being imported from the async facade.... And mock backend should move out of http anyway: https://github.com/angular/angular/pull/4031

Soooo, it seems like facades are to blame here... And this in turns means that Rx either needs to be an external dependency or that we should re-export it from core...

**Comment by pkozlowski-opensource** [comment]
OK, so @robwormald is right here - Rx is not pulled by mock backend but rather by an async facade. Since we duplicate facades we duplicate Rx as well.

The only way of solving this for now I can think of is by marking Rx as an external dependency and this is what I'm going to do in my PR for CJS bundles.
