### ISSUE TITLE
Angular 16 standalone url always routs to home page

### ISSUE THREAD

**Issue by morsagmon** [angular/angular#51372]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

My Angular 16 app is pure standalone, no ng modules at all. I configured routes, and when used within components as links (e.g.: routerLink="/team") it routes to the correct page, and the URL changes accordingly. However, trying to reach a page directly from the URL (for example, by just refreshing the localhost:4200/team page) - renders the home page. The URL does not even change - /team still appears as the URL, but the rendered page is the home page.

These are the relevant files:

**app.component.html:**

```
<app-top-nav></app-top-nav>
<router-outlet></router-outlet>
<app-footer></app-footer>
```

(If I remove the app-top-nav and app-footer, then the behavior does not change, only the URL indeed changes to /home as well).

**app.component.ts:**

```
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterOutlet } from '@angular/router';
import { HttpClientModule } from '@angular/common/http';
import { DatabaseService, EmailService } from 'src/app/services';
import { UnsubscribeGroup } from './interfaces/unsubscribe-group.enum';
import { FilterMatchMode, PrimeNGConfig } from 'primeng/api';
import { TopNavComponent } from "./components/top-nav/top-nav.component";
import { FooterComponent } from "./components/footer/footer.component";
import { CookieHandlerService} from "./services/cookie.service"

@Component({
    selector: 'app-root',
    standalone: true,
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss'],
    imports: [CommonModule, RouterOutlet, HttpClientModule, TopNavComponent, FooterComponent]
})
export class AppComponent {

  constructor(private databaseService: DatabaseService, private emailService: EmailService, private cookie: CookieHandlerService, public primengConfig: PrimeNGConfig, private router: Router) {}

  async ngOnInit() {
    this.primengConfig.ripple = true;
    
    this.primengConfig.zIndex = {
      modal: 1100,    // dialog, sidebar
      overlay: 1000,  // dropdown, overlaypanel
      menu: 1000,     // overlay menus
      tooltip: 1100   // tooltip
    };

    this.primengConfig.filterMatchModeOptions = {
      text: [FilterMatchMode.STARTS_WITH, FilterMatchMode.CONTAINS, FilterMatchMode.NOT_CONTAINS, FilterMatchMode.ENDS_WITH, FilterMatchMode.EQUALS, FilterMatchMode.NOT_EQUALS],
      numeric: [FilterMatchMode.EQUALS, FilterMatchMode.NOT_EQUALS, FilterMatchMode.LESS_THAN, FilterMatchMode.LESS_THAN_OR_EQUAL_TO, FilterMatchMode.GREATER_THAN, FilterMatchMode.GREATER_THAN_OR_EQUAL_TO],
      date: [FilterMatchMode.DATE_IS, FilterMatchMode.DATE_IS_NOT, FilterMatchMode.DATE_BEFORE, FilterMatchMode.DATE_AFTER]
    };

this.router.navigate(['/home']);
  } 
}
```

Trying to remove the last line: this.router.navigate(['/home']); has no effect.

**main.ts:**

```
import { bootstrapApplication } from '@angular/platform-browser';
import { AppComponent } from './app/app.component';
import { environment } from 'src/environments/environment';
import { enableProdMode, importProvidersFrom  } from '@angular/core';
import { 
  PreloadAllModules, 
  provideRouter, 
  withDebugTracing, 
  withPreloading, 
  withRouterConfig 
} 
from '@angular/router';
import { appConfig } from './app/app.config';

if (environment.production) {
  enableProdMode();
}

bootstrapApplication(AppComponent, appConfig)
  .catch((err) => console.error(err));
```

**app.config:**

```
import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { 
  PreloadAllModules, 
  provideRouter, 
  withDebugTracing, 
  withPreloading, 
  withRouterConfig 
} 
from '@angular/router';
import { provideHttpClient } from '@angular/common/http';


import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [provideRouter(routes), provideHttpClient() ]
};
```

**app.routes:**

```
import { Routes } from '@angular/router';
import { HomeComponent } from './pages/home/home.component';
import { TeamComponent } from './pages/team/team.component';
import { SignupComponent } from './pages/signup/signup.component';
import { TermsComponent } from './pages/terms/terms.component';
import { PrivacyComponent } from './pages/privacy/privacy.component';

export const routes: Routes = [
    { path: 'home', component: HomeComponent }, 
    { path: 'signup', component: SignupComponent }, 
    { path: 'team', component: TeamComponent }, 
    { path: 'terms', component: TermsComponent },  
    { path: 'privacy', component: PrivacyComponent },  
    { path: '', redirectTo: 'home', pathMatch: 'full' },
    { path: '**', redirectTo: 'home' }
];
```

**index.html:**

```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>MyDreamTeam</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
<body>
  <app-root></app-root>
</body>
</html>
```

I had this open in SO for few days now, to no avail, so I assume this is all configured correctly on my end, and probably a bug.

### Please provide the exception or error you saw

```true
There are no errors at all, the dev console is clean.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.4
@angular-devkit/build-angular   16.1.4
@angular-devkit/core            16.1.4
@angular-devkit/schematics      16.1.6
@angular/cli                    16.1.6
@schematics/angular             16.1.6
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```

### Anything else?
I also enabled ivy in tsconfig.json:

```
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "ES2022",
    "module": "ES2022",
    "useDefineForClassFields": false,
    "allowSyntheticDefaultImports": true,
    "lib": [
      "ES2022",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true,
    "enableIvy": true
  }
}
```

Reproduced in Stackblitz:

https://stackblitz.com/edit/stackblitz-starters-kvfyb5?file=src%2Fmain.ts

https://stackblitz-starters-kvfyb5.stackblitz.io/

_No response_

**Comment by akib1997** [comment]
If provide a Stackblitz link would be better to understand well.

**Comment by morsagmon** [comment]
> If provide a Stackblitz link would be better to understand well.

I'm afraid the nature of this issue will not show on Stackblitz, as the URL is occupied by Stackblits itself... :)
Thank you for your support!

**Comment by JoostK** [comment]
Without a reproduction we'd be unable to investigate. This is very likely a configuration issue somewhere, but we can't tell without a repro.

**Comment by morsagmon** [comment]
I managed to reproduce in Stackblitz:

https://stackblitz.com/edit/stackblitz-starters-kvfyb5?file=src%2Fmain.ts

https://stackblitz-starters-kvfyb5.stackblitz.io

Type in the URL: /privacy or /terms - it will always render HOME.

**Comment by atscott** [comment]
@morsagmon  `AppComponent` calls `this.router.navigate(['/home']);` in the `ngOnInit` so this is working as expected. You mentioned previously that removing that navigation would have no effect but removing it in the stackblitz example does indeed allow navigations directly to places other than the `home` route.

Closing this as not reproducible. If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template that include info on how to create a reproduction using our template.

**Comment by morsagmon** [comment]
@atscott 
Thanks for checking.
I can see in Blitz it is working as expected. However, in my local app, removing this line makes no change. I tried many time. I reloaded without browser cache - nothing.
So, I may not know how to reproduce this in Blitz, but it is still not routing for me, as described. What to do??

**Comment by JeanMeche** [comment]
You could share your issue on a github repo.

**Comment by morsagmon** [comment]
I think I observed something odd.
Whenever I navigate directly to any page (e.g. /terms), the ngOnInit in the app.component.ts kicks in. I placed a console log command and it is fired on every navigation. I'm not sure, but maybe it has to do with that? why would app.component run its ngOnInit on every navigation to any page?

As mentioned, I removed the `this.router.navigate(['/home']);` and removed also the import or Router completely in the app component, so it is definitely not the cause of this.
I also removed (for testing) the catch-all routing in app routes:
```
    { path: '', redirectTo: 'home', pathMatch: 'full' },
    { path: '**', redirectTo: 'home' }
```

It's not this...

**Comment by JoostK** [comment]
`AppComponent` is being bootstrapped and is responsible for showing the router outlet, so it's always rendered.

**Comment by morsagmon** [comment]
Problem solved!
In my top-nav.component.ts, I was importing this module: 
`import { BrowserAnimationsModule } from '@angular/platform-browser/animations';`

Removing this import (from the imports array of the component) - solved the problem!

You can see this in the stackblitz provided above. URL:

https://stackblitz.com/edit/stackblitz-starters-kvfyb5?file=src%2Fmain.ts

https://stackblitz-starters-kvfyb5.stackblitz.io/

Remove the BrowserAnimationsModule  import in the top-nav component - and the problem goes away.
This works in my local implementation as well now.

In Stackblitz, you can see that the console throws this error if this import exists:
`Error: NG05100: Providers from the `BrowserModule` have already been loaded. If you need access to common directives such as NgIf and NgFor, import the `CommonModule` instead.`

Problem is, in my local setup, this error is not showing in the console, so I had no idea!
So, couple of takeaways:
1. Some errors are not showing locally, while they do show in Stackblitz
2. This BrowserAnimationsModule  probably conflicts with something and cannot be used in some situations. See in Stackblitz...
