### ISSUE TITLE
Invalid URL: Scheme not starting with alphabetic character when using @angular-devkit/build-angular:browser-esbuild

### ISSUE THREAD

**Issue by arambazamba** [angular/angular#51381]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

In Angular 16.2 when changing the builder from the default to @angular-devkit/build-angular:browser-esbuild in angular.json using a custom theme gives the following build err:

![image](https://github.com/angular/angular/assets/16348023/276e84da-ffed-45c4-9b4a-d91bd05c5940)

When changing back to @angular-devkit/build-angular:browser everything works as expected

### Please provide a link to a minimal reproduction of the bug

https://github.com/arambazamba/style-test

### Please provide the exception or error you saw

```true
![image](https://github.com/angular/angular/assets/16348023/276e84da-ffed-45c4-9b4a-d91bd05c5940)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.0
Node: 16.15.0
Package Manager: npm 8.5.5
OS: win32 x64

Angular: 16.2.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.0
@angular-devkit/build-angular   16.2.0
@angular-devkit/core            16.2.0
@angular-devkit/schematics      16.2.0
@schematics/angular             16.2.0
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```

**Comment by JeanMeche** [comment]
Hi, this issue is discussed at angular/angular-cli#25660

**Comment by LorinRenodeyn** [comment]
It started happening even before the 16.2.0 version
I just ran into this issue and tried with the angular-builder & cli at 16.1.8 and it already exhibited this issue.
Looking at the release notes, it might have been present from 16.1.4 ? Though this is only a guess.
