### ISSUE TITLE
Angular 16 with Chromium M47

### ISSUE THREAD

**Issue by manuelm-fl** [angular/angular#51406]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Currently we have one app which is running fine with Angular 11 over Tizen browser: 

- Ref: https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html
- model 2017, Tizen 3.0 with Chromium M47

After trying to update to the latest version of Angular for the same model many of the features are not working properly also for a 2019  (Chromium M69) model we have some other issue like the attached image

![2019-trace](https://github.com/angular/angular/assets/74257311/d24fff3e-753f-4f9b-957a-fe1a025af727)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.1
Node: 18.16.0
Package Manager: npm 9.5.1
OS: linux x64

Angular: 16.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.1
@angular-devkit/build-angular   16.0.1
@angular-devkit/core            16.0.1
@angular-devkit/schematics      16.0.1
@schematics/angular             16.0.1
rxjs                            7.8.1
typescript                      5.0.4
```

### Anything else?

is there any detail about the minimal polyfills required for this environment (versions) ? 

here is the polyfills defined in this project:

- import 'classlist.js';
- import 'web-animations-js';
- import 'zone.js';
- import 'abortcontroller-polyfill';
- import 'es7-object-polyfill';

**Comment by JoostK** [comment]
Angular only supports the latest 2 versions of Chrome, any older versions are not supported. You might be able to request support for older browsers using a particular browserslist configuration (as supported by the CLI), but I don't think ES5 emit is supported anymore so I doubt that you'd be able to make it work for versions that are that old.

**Comment by manuelm-fl** [comment]
hi @JoostK thanks for the explanation

**Comment by shanmugapriyak1788** [comment]
@JoostK We have our product developed in angular. Several OTT LG /Samsung Fire TV applications are running in angular 11 for our existing customers. 
Could you please suggest an alternative for this?
We included the polyfills in the polyfill.ts file. Yet we get a blank screen.
