### ISSUE TITLE
Angular Deprecation Warnings  In chrome and Edge browsers

### ISSUE THREAD

**Issue by HarikrishnaPunamalliTR** [angular/angular#51419]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Hi Team, We are getting the warnings for angular application.

**zone.js:1878 [Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.**

In the Zone.js file below Code showing warning.

 **return nativeAddEventListener.call(taskData.target, taskData.eventName, taskData.capture ? globalZoneAwareCaptureCallback : globalZoneAwareCallback, taskData.options);**

Please check and any one help me how to solve the warnings.

### Please provide the exception or error you saw

```true

**zone.js:1878 [Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.**

In the Zone.js file below Code showing warning.

return nativeAddEventListener.call(taskData.target, taskData.eventName, taskData.capture ? globalZoneAwareCaptureCallback : globalZoneAwareCallback, taskData.options);
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.8
Node: 18.16.0
Package Manager: npm 8.13.2
OS: win32 x64

Angular: 15.2.9
```

**Comment by JoostK** [comment]
Angular/zone.js does not register event listeners for the `DOMNodeInserted` event itself, you'll have to find the source of this event listener in your application. zone.js is present in the stacktrace since it intercepts _all_ event listeners.
