### ISSUE TITLE
ngModel not updating with input type="search" clear button in IE

### ISSUE THREAD

**Issue by aderowbotham** [angular/angular#5141]
When using an input type="search" field with AngularJS in IE 9, 10 or 11: When you click the search clear / cancel button rendered inside the field in Internet Explorer the model value does not reset to '' or undefined.

Example HTML:

    <input ng-model="searchVal" type="search">
    <p>searchVal = {{ searchVal }}</p>

http://plnkr.co/edit/zE2qMMfaJK11KYfUWZzr?p=preview

Tested with Angular 1.4.7. t works fine in Chrome and Safari.

**Comment by pkozlowski-opensource** [comment]
Wrong repo, I guess you are looking for https://github.com/angular/angular.js
This one is for Angular2

**Comment by aderowbotham** [comment]
@pkozlowski-opensource 

I was indeed. You can see how it's easy to confuse the two though.
