### ISSUE TITLE
Directive compile broken when using @Input transform

### ISSUE THREAD

**Issue by johncrim** [angular/angular#51424]
### Which @angular/* package(s) are the source of the bug?

compiler or ng-packagr

### Is this a regression?

Not sure, I just tried @Input + transform. It's not a regression for our code base.

### Description

When a standalone directive in a library uses `@Input({ transform: ..})`, the compiler output is broken such that the class isn't recognized as a directive, resulting in errors like those listed in the next section, which state that the class is missing an Angular decorator (which is clearly wrong - it has the `@Directive` decorator).

The bug can be reproduced by:

```sh
git clone https://github.com/johncrim/bug-ng16-input-transform
yarn
yarn build:all
```

The compile error is:
```
------------------------------------------------------------------------------
Building entry point 'ui-components/sticky'
------------------------------------------------------------------------------
✖ Compiling with Angular sources in Ivy partial compilation mode.
libs/ui-components/sticky/src/Sticky.component.ts:10:5 - error NG2012: Component imports must be standalone components, directives, pipes, or must be NgModules.

10     MirrorWidthDirective
       ~~~~~~~~~~~~~~~~~~~~

error Command failed with exit code 1.
```

This error is caused by the use of `@Input({transform: ...})` in `MirrorWidthDirective`. The problem is that the use of the input transform feature breaks the build output: The contents of `dist\ui-components\fesm2022\ui-components-mirror-size.mjs` show that `class MirrorWidthDirective` is missing the static `ɵdir` and `ɵfac` properties:

```js
let MirrorWidthDirective = class MirrorWidthDirective {
  // ... (class properties and methods)
};
__decorate([
    Input({ alias: 'ui-mirror-width', required: true, transform: coerceElement })
], MirrorWidthDirective.prototype, "source", void 0);
MirrorWidthDirective = __decorate([
    Directive({
        selector: '[ui-mirror-width]',
        standalone: true,
        exportAs: 'ui-mirror-width'
    })
], MirrorWidthDirective);
```

The similar directive `MirrorHeightDirective` is equivalent but omits use of the `@Input transform`. It is in the same project, but the compiler output (in `dist\ui-components\fesm2022\ui-components-mirror-size.mjs`) is:

```js
class MirrorHeightDirective {
  // ... (class properties and methods)
    static { this.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "16.2.1", ngImport: i0, type: MirrorHeightDirective, deps: [], target: i0.ɵɵFactoryTarget.Directive }); }
    static { this.ɵdir = i0.ɵɵngDeclareDirective({ minVersion: "14.0.0", version: "16.2.1", type: MirrorHeightDirective, isStandalone: true, selector: "[ui-mirror-height]", inputs: { source: ["ui-mirror-height", "source"] }, exportAs: ["ui-mirror-height"], usesOnChanges: true, ngImport: i0 }); }
}
i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "16.2.1", ngImport: i0, type: MirrorHeightDirective, decorators: [{
            type: Directive,
            args: [{
                    selector: '[ui-mirror-height]',
                    standalone: true,
                    exportAs: 'ui-mirror-height'
                }]
        }], propDecorators: { source: [{
                type: Input,
                args: [{ alias: 'ui-mirror-height', required: true }]
            }] } });
```

The second directive can be imported, but the first one can't, b/c the second is recognized as a directive b/c `static ɵdir` exists.

### Please provide a link to a minimal reproduction of the bug

https://github.com/johncrim/bug-ng16-input-transform

### Please provide the exception or error you saw

```true
When imported in a component:

error NG2012: Component imports must be standalone components, directives, pipes, or must be NgModules.

or when imported in a module:

error NG6002: 'MirrorWidthDirective ' does not appear to be an NgModule class.
error NG6003: 'MirrorWidthDirective ' does not appear to be an NgModule, Component, Directive, or Pipe class.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.0
Node: 18.10.0
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 16.2.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.0
@angular-devkit/build-angular   16.2.0
@angular-devkit/core            16.2.0
@angular-devkit/schematics      16.2.0
@angular/cli                    16.2.0
@schematics/angular             16.2.0
ng-packagr                      16.2.0
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```

**Comment by johncrim** [comment]
I should add that this is a pretty severe bug - the error messages and side-effects are completely misleading. While there's a workaround (don't use transforms), diagnosing that problem took quite a while - it definitely lead to some loss of hair. The only reason this isn't a bigger deal is that @Input transforms probably aren't widely used in the wild, given their newness.

**Comment by crisbeto** [comment]
It looks like the actual error is this: 

```
node_modules/external/index.d.ts:4:57 - error NG3004: Unable to import type HTMLElement.
  The symbol is not exported from /node_modules/typescript/lib/lib.dom.d.ts.

4           export declare function externalToNumber(val: HTMLElement | ElementRef<HTMLElement>): HTMLElement;
                                                          ~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:10102:13
    10102 declare var HTMLElement: {
                      ~~~~~~~~~~~~~~
    10103     prototype: HTMLElement;
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    10104     new(): HTMLElement;
          ~~~~~~~~~~~~~~~~~~~~~~~
    10105 };
          ~
    The type is declared here.
```

It's unclear why only the error after it gets logged though, I suspect it might be a CLI issue.

**Comment by johncrim** [comment]
Thanks for the investigation @crisbeto . I don't see that error, and the `coerceElement()` function works fine if I use it elsewhere. I added use of the `coerceElement` fn in the property setter for the comparable directive (MirrorHeightDirective - no Input transform) that works fine - `git pull` for that change.

Here's the build output I see:

```
  yarn build:all 
yarn run v1.22.19
$ ng build util && ng build ui-components
Building Angular Package

------------------------------------------------------------------------------
Building entry point 'util'
------------------------------------------------------------------------------
✔ Compiling with Angular sources in Ivy partial compilation mode.
✔ Generating FESM bundles
✔ Copying assets
✔ Writing package manifest
✔ Built util

------------------------------------------------------------------------------
Built Angular Package
 - from: C:\temp\bug-ng16-input-transform\libs\util
 - to:   C:\temp\bug-ng16-input-transform\dist\util
------------------------------------------------------------------------------

Build at: 2023-08-23T07:21:45.092Z - Time: 1461ms

Building Angular Package

------------------------------------------------------------------------------
Building entry point 'ui-components'
------------------------------------------------------------------------------
✔ Compiling with Angular sources in Ivy partial compilation mode.
✔ Writing FESM bundles
✔ Copying assets
✔ Writing package manifest
✔ Built ui-components

------------------------------------------------------------------------------
Building entry point 'ui-components/mirror-size'
------------------------------------------------------------------------------
✔ Compiling with Angular sources in Ivy partial compilation mode.
✔ Generating FESM bundles
✔ Built ui-components/mirror-size

------------------------------------------------------------------------------
Building entry point 'ui-components/sticky'
------------------------------------------------------------------------------
✖ Compiling with Angular sources in Ivy partial compilation mode.
libs/ui-components/sticky/src/Sticky.component.ts:10:5 - error NG2012: Component imports must be standalone components, directives, pipes, or must be NgModules.

10     MirrorWidthDirective
       ~~~~~~~~~~~~~~~~~~~~

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Further, the MirrorWidthDirective class/file is compiled into the output .mjs file, it's just missing the normal annotations in the build output as described above. If there was a compile error referencing the lib function, I would expect that the class wouldn't be in the build output.

**Comment by crisbeto** [comment]
There are a few things going on:
1. Angular won't compile a class if it contains errors. That's why it was failing later on saying that `imports` must contain directives or pipes.
2. The class compilation fails, because the compiler needs to be able to reference the type of the first parameter in the `transform` function. It fails here, because `HTMLElement` is an ambient type and our code wasn't accounting for such types. I've sent out #51474 to fix it.
3. It's unclear why the error for `HTMLElement` wasn't being logged, but my best guess is that the CLI is suppressing it since I could see the error when I moved your use case into the compiler's unit tests.

**Comment by johncrim** [comment]
Thank you for the explanation and fix @crisbeto. I'm thinking there are more bugs than just the input transform function not handling ambient types. But I don't know enough about them to create the bug reports + repro cases:

* Why does the compiler write `class MirrorWidthDirective` to `dist\ui-components\fesm2022\ui-components-mirror-size.mjs` in a broken state? It seems like it should not be in the output file if compiling the class failed.
* Why is the error not being reported?

I'm concerned that just fixing the transform error will leave these as latent problems that will bite users later.

**Comment by crisbeto** [comment]
1. `MirrorWidthDirective` is being written by TypeScript. Angular doesn't write its metadata if there are errors. We probably don't want to go and omit the class ourselves because it might be referenced elsewhere.
2. I'm not sure why the error isn't being reported, because I am seeing it in unit test. My guess is that the CLI's error logging only shows the bottom error in the stack.

**Comment by johncrim** [comment]
Thank you @crisbeto. Both of those seem like problems. Should there at least be a bug for #2?

**Comment by johncrim** [comment]
@CSchulz  - can you report the compile error you're getting? Is it the same as I reported in this issue, or is it less misleading?

**Comment by CSchulz** [comment]
It is the same compile error. I have checked also your repro and it seems to have the same root cause:

```
Error: slider.component.ts:26:95 - error NG2012: Component imports must be standalone components, directives, pipes, or must be NgModules.

26  imports: [LongpressDirective],
              ~~~~~~~~~~~~~~~~~~


Error: longpress.directive.ts:41:20 - error NG3004: Unable to import type Record.
  The symbol is not exported from node_modules/.pnpm/typescript@5.1.6/node_modules/typescript/lib/lib.es5.d.ts.

41   transform: (obj: Record<keyof LongpressOptions, unknown> | '') => {
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/.pnpm/typescript@5.1.6/node_modules/typescript/lib/lib.es5.d.ts:1599:1
    1599 type Record<K extends keyof any, T> = {
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1600     [P in K]: T;
         ~~~~~~~~~~~~~~~~
    1601 };
         ~~
    The type is declared here.
```

**Comment by johncrim** [comment]
At least you're seeing the second error - that's progress.
