### ISSUE TITLE
Please export testingEffect, flushEffects, resetEffects in @angular/core/testing

### ISSUE THREAD

**Issue by e-oz** [angular/angular#51429]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Please consider exporting utility functions for testing `effect()`.
They internally import `Watch`, and I doubt you are going to export `Watch`, but the functions themselves are quite handy.

### Proposed solution

Part of public API of @angular/core/testing

### Alternatives considered

Copy-pasting `Watch` just to recreate these functions, but it's an awful idea.

**Comment by pkozlowski-opensource** [comment]
We've just landed https://github.com/angular/angular/pull/51049 that introduces the `flushEffects()` method on `TestBed`. In our view it should be enough to tests effects under TestBed - please give it a try and let us know how testing goes!

In the future we think of introducing a first-class effect scheduler interface with a specific implementation for tests. This would allow even easier testing, outside of `TestBed`.

**Comment by e-oz** [comment]
Thank you so much!
