### ISSUE TITLE
The status of FormControl with async validator is stuck on PENDING after running updateValueAndValidity despite promise resolving

### ISSUE THREAD

**Issue by ShacharHarshuv** [angular/angular#51463]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

Reproduction steps:

* Create a `FormControl` with an async validator
* Bind the `FormControl` to the view using `FormControlDirective`
* Run `updateValueAndValidity`

Expected: The status should change to PENDING and then to VALID (or INVALID) as soon as the validation completes / resolves. 

Actual: We only get the PENDING status, despite the validation completed successfully. 

Minimal reproduction code example:

```ts
@Component({
  selector: 'my-app',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  template: `
    <input [formControl]="formControl">
  `,
})
export class App {
  formControl = new FormControl(null, {
    asyncValidators: async () => {
      return null;
    },
  });

  constructor() {
    this.formControl.statusChanges.subscribe(console.log); // Expected 'PENDING' and 'VALID', only logs 'PENDING'
    this.formControl.updateValueAndValidity();
  }
}
```

Note that:
- If there is no view binding, this works as expected
- If using synced validator instead that works as expected
- If not running `updateValueAndValidity` that works as expected

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-eherug?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
N/A
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.3
Node: 16.14.2
@angular-devkit/build-angular      16.1.3
@angular-devkit/core               16.1.3
@angular-devkit/schematics         16.1.3
@angular/cdk                       15.2.9
@angular/material                  15.2.9
@angular/material-moment-adapter   15.2.9
@schematics/angular                16.1.3
ng-packagr                         16.1.0
rxjs                               7.4.0
typescript                         4.9.3
```

**Comment by JeanMeche** [comment]
Hi, this issue is discussed at #41519
