### ISSUE TITLE
Calling a node module function in a webworker

### ISSUE THREAD

**Issue by alpha027** [angular/angular#51482]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

The webworker documentation provides minimal working example of how to call a function in a webworker.
However, when trying to import a function from some node module, the same example does not work anymore.

Basically what I am trying to do that does not work is the following:

```
import { add_one } from 'node-module';

addEventListener('message', ({ data }) => {
  const response = add_one(data.param.N_data);

  postMessage(response);
});

```
This did not work, however when I write explicit code of the function inside the worker.ts file, the webworker works, however I am only interested in calling node module functions in the webworker.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/cli": "~16.1.5",
node version: v16.14.2
OS Linux, Ubuntu 22.04
```

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
