### ISSUE TITLE
Dark mode > White text is to bright

### ISSUE THREAD

**Issue by BerndHme** [angular/angular#51494]
### Describe the problem that you experienced

When you set the docs in dark-mode, the white text hurts your eyes.
I think it would be much better to soften the pure white text to light grey.

Please save our eyes.

![image](https://github.com/angular/angular/assets/132269491/05cc1ac8-baf1-4031-b15d-fbc74c427b51)

VS

![image](https://github.com/angular/angular/assets/132269491/f2bb6a98-4da3-42be-9101-bd75b325f112)

### Enter the URL of the topic with the problem

https://angular.io/guide/architecture

**Comment by ferrorenan** [comment]
@jessicajaniuk @pkozlowski-opensource @BerndHme 

Hey guys, I made a PR to resolve this! 

If you can take a look, PR link: https://github.com/angular/angular/pull/52125

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
