### ISSUE TITLE
createComponent function example not work on 16.2.1

### ISSUE THREAD

**Issue by hiepxanh** [angular/angular#51492]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

The document wrong: https://angular.io/api/core/createComponent
``` 
const componentRef = [createComponent](https://angular.io/api/core/createComponent)(HelloComponent, {host, environmentInjector});

host was change to hostElement, should become this
const componentRef = [createComponent](https://angular.io/api/core/createComponent)(HelloComponent, {hostElement, environmentInjector});

```

Btw it just not work.

### Please provide a link to a minimal reproduction of the bug

[this one work]
https://stackblitz.com/edit/angular-anxyrb?file=src%2Fmain.ts,src%2Findex.html 
[not work version]
https://codesandbox.io/p/sandbox/relaxed-feather-27fv8y?file=/src/app/app.component.ts:63,6

### Please provide the exception or error you saw

```true
NG0912: Component ID generation collision detected. Components 'HelloComponent' and 'HelloComponent' with selector 'hello-component' generated the same component ID. To fix this, you can change the selector of one of those components or add an extra host attribute to force a different ID. Find more at https://angular.io/errors/NG0912
```

### Anything else?

ng version result:

![image](https://github.com/angular/angular/assets/16970990/6ab0f856-56bc-4b78-8c01-cf4aa9ebf33a)

**Comment by JeanMeche** [comment]
FYI the missing bit is the missing CD. 
Calling  `componentRef.changeDetectorRef.detectChanges();` fixed your issue.

**Comment by hiepxanh** [comment]
@JeanMeche  I just try to copy the document to make sure it follow tutorial. it's still not work sir, I updated as your suggest but it still the same

![image](https://github.com/angular/angular/assets/16970990/146825fd-b38d-4a46-830d-ff407930b2f9)

![image](https://github.com/angular/angular/assets/16970990/7a564143-d2b4-4fa6-b628-41f3bc76f056)

**Comment by JeanMeche** [comment]
You're missing `import 'zone.js'`. (`bootstrapApplication()` throws silently)

**Comment by hiepxanh** [comment]
I created PR to update this

**Comment by hiepxanh** [comment]
anyway, lazy is so bad, that repo is not complex enough. I think the current situation should look like this example repo:
https://codesandbox.io/p/sandbox/relaxed-feather-27fv8y?file=/src/app/app.component.ts:63,6
@JeanMeche 

refer from this issue: https://github.com/angular/angular/issues/51491

**Comment by hiepxanh** [comment]
the dynamic 1 and dynamic 2 should jump to here: 
![image](https://github.com/angular/angular/assets/16970990/4cb7c4c2-bc3e-4ad4-8f89-ff8e46935c5a)

**Comment by hiepxanh** [comment]
> Thank you so much sir, it work and really interesting. I think this is a little trick and should be more clear on the document. Do you think can I add one more example to document?



> @hiepxanh thanks for creating a repro. The problem is that you've used a binding value that would always be different for each change detection cycle, i.e. `<div [innerHTML]="domSanitizer.bypassSecurityTrustHtml(content)"></div>`. The `bypassSecurityTrustHtml` would return a new object each time it's invoked. You can try adding a new property to a class that would store a reference to the function call result and use it in a template instead. For example:
> 
> ```
> @Component({
>   standalone: true,
>   selector: 'my-app',
>   template: `<div [innerHTML]="sanitizedContent"></div>`,
> })
> export class AppComponent {
>   domSanitizer = inject(DomSanitizer);
> 
>   content = `<h1> hello world 1</h1>  
>     <dynamic1> </dynamic1> 
>     <dynamic2> </dynamic2>  
>     <h1> hello world 2</h1>`;
> 
>   // Store a reference to the computed result and use it in a template
>   sanitizedContent = this.domSanitizer.bypassSecurityTrustHtml(this.content);
> ```
> 
> Thank you.


copy from https://github.com/angular/angular/issues/51491#issuecomment-1694127351 

dynamic1 can render successful with variable reference instead of function because it's new object everytime
solve the issue I'm facing now. 

I will add an example about this in the document

**Comment by hiepxanh** [comment]
Hello sir, hope you are doing well. @AndrewKushnir  I think this may be my last issue about this problem. I can have a perfect reproduction on our issue. I created on a new issue here: https://github.com/angular/angular/issues/51535
