### ISSUE TITLE
View not updating when new value emitted from Rx.Observable

### ISSUE THREAD

**Issue by youknowriad** [angular/angular#5150]
Hi,

I have a simple angular2 application like so : 

````typescript
import {Component, bootstrap} from 'angular2/angular2';

@Component({
    selector: 'mainroot',
    template: `test: {{ test }}`,
    directives: []
})

class RootComponent{
  test: string = 'no';
  constructor() {
    Rx.Observable.just(1).delay(1000).subscribe(() => {
      console.log('yes');
      this.test = 'yes';
    });
  }
}

bootstrap(RootComponent, []);
````
When the observable emits a new value, I update a model "test", but the change is not reflected in the view. Is this a bug related to Zone.js or something like that ?

Thanks,

Here is a plunker reproducing the bug :

http://plnkr.co/edit/w4B77nmTWdJUNPN0ZrqO?p=preview

**Comment by robwormald** [comment]
Could you try this with RxJS 5? Angular2 uses this version - it's installable via npm `@reactivex/rxjs` -though it should be installed by default.

See http://plnkr.co/edit/7A8hoNtanpmTBJtgWYJ6?p=preview

Unless there's something specific you need from 4, you'd be best to use the new library, as the API has changed (eg `.onNext(value)` -> `.next(value)` ) and features like Angular2 pipes and Http use the new API.

There's definitely a few outstanding issues WRT to zones and Observables, but this simple case should work.

**Comment by youknowriad** [comment]
thanks @robwormald I used the version 5 as you suggested and It's works well now. I am going to stick with that now.

Thanks a lot
