### ISSUE TITLE
Tests fail for library project that contains a node_modules directory

### ISSUE THREAD

**Issue by bleistift-zwei** [angular/angular#51507]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

In order to create a library, the [developer guide](https://angular.io/guide/creating-libraries) instructs us to create a wrapper project. We then create the library therein. This works as expected. The auto-generated tests inside the library pass.

Suppose the library requires an npm module to function, so we install it as a dependency for the library. This creates another node_modules directory in the library directory (as a sibling to tsconfig.lib.json). This causes the tests to fail.

The linked reproduction repository was created by executing this script.

```shell
ng new wrapper --create-application=false --commit
cd wrapper
ng generate library inner
git add . && git commit -m "add library"
npm run test inner # Tests pass
cd projects/inner
npm install is-even
echo 'node_modules' > .gitignore
cd ../..
git add . && git commit -m "Add dependency to inner project"
npm run test inner # Tests fail
```

### Please provide a link to a minimal reproduction of the bug

https://github.com/bleistift-zwei/angular-library-test-repro

### Please provide the exception or error you saw

```
Error: Need to call TestBed.initTestEnvironment() first
    at TestBedImpl.compiler (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/testing.mjs:26918:19)
    at TestBedImpl.configureTestingModule (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/testing.mjs:26830:14)
    at Function.configureTestingModule (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/testing.mjs:26662:37)
    at UserContext.apply (http://localhost:9876/_karma_webpack_/webpack:/projects/inner/src/lib/inner.service.spec.ts:9:13)
    at _ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:368:26)
    at ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:273:39)
    at _ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:367:52)
    at Zone.run (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:129:43)
    at runInTestZone (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:555:34)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:570:20)
```
```


### Please provide the environment you discovered this bug in (run `ng version`)

```
Angular CLI: 16.2.0
Node: 16.20.2
Package Manager: npm 8.19.4
OS: linux x64

Angular: 16.2.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.0
@angular-devkit/build-angular   16.2.0
@angular-devkit/core            16.2.0
@angular-devkit/schematics      16.2.0
@angular/cli                    16.2.0
@schematics/angular             16.2.0
ng-packagr                      16.2.1
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```


### Anything else?

I understand that using “hard” dependencies in libraries is discouraged, and we should use peer dependencies. However, given that “whitelisting” dependencies is explicitly supported, I think this is a bug.

If the solution is to install all dependencies in the “wrapper” project, then the “inner” package.json wouldn’t get updated unless I edit it manually. Is this the way to go? What if the wrapper is the parent to multiple libraries which depend on different versions of the same dependency?

I can’t tell if this is a regression. I’ve tried the steps above at CLI versions 13 through 15 and they fail, too, but with different error messages.

Version 15 exhibits the same behaviour as version 16.

Version 14:

```
Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `EnvironmentInjector#runInContext`. Find more at https://angular.io/errors/NG0203 in http://localhost:9876/_karma_webpack_/vendor.js (line 40107)
error properties: Object({ code: -203 })
injectInjectorOnly@http://localhost:9876/_karma_webpack_/vendor.js:44625:11
ɵɵinject@http://localhost:9876/_karma_webpack_/vendor.js:44633:59
ApplicationModule_Factory@http://localhost:9876/_karma_webpack_/vendor.js:68876:39
factory@http://localhost:9876/_karma_webpack_/vendor.js:107444:32
hydrate@http://localhost:9876/_karma_webpack_/vendor.js:107362:29
get@http://localhost:9876/_karma_webpack_/vendor.js:107263:23
injectInjectorOnly@http://localhost:9876/_karma_webpack_/vendor.js:103575:29
ɵɵinject@http://localhost:9876/_karma_webpack_/vendor.js:103579:59
useValue@http://localhost:9876/_karma_webpack_/vendor.js:107058:33
resolveInjectorInitializers@http://localhost:9876/_karma_webpack_/vendor.js:107303:9
NgModuleRef@http://localhost:9876/_karma_webpack_/vendor.js:120034:22
finalize@http://localhost:9876/_karma_webpack_/vendor.js:152965:26
get testModuleRef@http://localhost:9876/_karma_webpack_/vendor.js:153903:43
inject@http://localhost:9876/_karma_webpack_/vendor.js:153813:20
inject@http://localhost:9876/_karma_webpack_/vendor.js:153682:33
1040/</<@http://localhost:9876/_karma_webpack_/main.js:87:78
invoke@http://localhost:9876/_karma_webpack_/vendor.js:6534:158
onInvoke@http://localhost:9876/_karma_webpack_/vendor.js:4309:33
invoke@http://localhost:9876/_karma_webpack_/vendor.js:6534:46
run@http://localhost:9876/_karma_webpack_/vendor.js:6317:35
runInTestZone@http://localhost:9876/_karma_webpack_/vendor.js:4588:28
6895/</wrapTestInZone/<@http://localhost:9876/_karma_webpack_/vendor.js:4603:14
<Jasmine>
invokeTask@http://localhost:9876/_karma_webpack_/vendor.js:6561:171
runTask@http://localhost:9876/_karma_webpack_/vendor.js:6363:37
drainMicroTaskQueue@http://localhost:9876/_karma_webpack_/vendor.js:6732:23
```

Version 13

Won’t even compile.

```
✔ Browser application bundle generation complete.

Error: projects/inner/src/test.ts:21:3 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(ngModule: Type<any> | Type<any>[], platform: PlatformRef, options?: TestEnvironmentOptions | undefined): void', gave the following error.
    Argument of type 'import("/home/bleistift2/tmp/wrapper-13/node_modules/@angular/core/core").PlatformRef' is not assignable to parameter of type 'import("/home/bleistift2/tmp/wrapper-13/projects/inner/node_modules/@angular/core/core").PlatformRef'.
      Types have separate declarations of a private property '_injector'.
  Overload 2 of 2, '(ngModule: Type<any> | Type<any>[], platform: PlatformRef, aotSummaries?: (() => any[]) | undefined): void', gave the following error.
    Argument of type 'import("/home/bleistift2/tmp/wrapper-13/node_modules/@angular/core/core").PlatformRef' is not assignable to parameter of type 'import("/home/bleistift2/tmp/wrapper-13/projects/inner/node_modules/@angular/core/core").PlatformRef'.

21   platformBrowserDynamicTesting(),
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by JoostK** [comment]
Unfortunately this is how NPM module resolution works; having nested `node_modules` that both contain `@angular/core` will undesirably result in multiple copies of `@angular/core`. This is a problem, as those copies will not be aware of each other's state.

I left some more details in https://github.com/angular/angular/issues/47823#issuecomment-1285612443. That situation is slightly different since it considered a real dependency, not just a peer dependency. This reveals an interesting (and somewhat unexpected to me) difference between NPM and Yarn/pnpm: NPM _does_ install the peer dependencies into `node_modules`, where Yarn and pnpm do not (which is the more reasonable behavior, if you ask me).

I would _highly_ recommend against using nested node_modules that are not governed by an NPM/Yarn workspace. Unfortunately this behavior is outside of Angular's control.
