### ISSUE TITLE
@Input decorator fowards value to Subject/Signals

### ISSUE THREAD

**Issue by muhamedkarajic** [angular/angular#51519]
### Description

Recently Angular introduced a feature regarding such as
```typescript
@Input({ transform: (value: any) => Number(value) }) myNumber: number = 0;
```

### Proposed solution

I propose we consider adding a way to do this but in such a way that we foward the value using the .next or .set for Subjects / Signals.

This would make developer life easier. Maybe it could even be in such a way that you don't have to write the boiler plate at all.
```typescript
@Input({ fowards: true ) myNumber = new BehaviorSubject<number>(0);
@Input({ fowards: true ) myNumber = signal(0);
```

### Alternatives considered

How it could work is that it just checks when setting the new value if the object is a subject or a signal and based on that calls .next() or .set().

**Comment by JeanMeche** [comment]
Hi ! 

Basically you want signal inputs. These have been discussed as part of the Signal RFC and are on the roadmap ! Stay tuned !
