### ISSUE TITLE
withComponentInputBinding()   support for loadComponent object

### ISSUE THREAD

**Issue by Abdulali97** [angular/angular#51512]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

Enables binding information from the Router state directly to the inputs of the component in Route configurations for 
loadComponent 

### Proposed solution

```typescript
 {
    path: '',
    loadComponent: () =>
      import('./account.component').then((m) => m.AccountComponent),
      data: { title: 'Account' }  // <-----   Ex
  },
}
```

### Alternatives considered

or for all children  components   at once
```typescript
{
    path: 'account',
    loadChildren: () =>
      import('./features/account/account.component').then(
        (m) => m.AccountRoute
      ),
      data: { title: 'Account' }  // <-----   Ex
  },

```

**Comment by JeanMeche** [comment]
I'm going to close this, `withComponentInputBinding()` already works as expected. Entries in `data` are already binded to the inputs on lazy loaded components and their children.

**Comment by Abdulali97** [comment]
@JeanMeche  
hi jean , 
I had tried with loadComponent and loadChilidren  and  it's seems not work 

```typescript

 {
    path: 'account',
    loadChildren: () =>
      import('./features/account/account.component').then(
        (m) => m.AccountRoute
      ),
      data: { title: 'Account' },  // <----  not work 
  },


  {
    path: '',
    loadComponent: () =>
      import('./account.component').then((m) => m.AccountComponent),
      data: { title: 'Account' }, // <-- not work 
  },


  {
    path: 'admin',
    component: AdminComponent,
    data : { title: 'Admin' }, // <----  works fine
  }
{
```
and in appComponent 

```typescript

  template : ` title her {{title}}} `
 ....
 
export class AppComponent {
  @Input() title?:string ;
}
  ```
  i get undefined  with  loadChildren and loadComponent 
  
  what i miss , or did i made it wrong 
  
  
  thank you

**Comment by JeanMeche** [comment]
It will bind on the `AccountComponent` but not the `AppComponent`.
