### ISSUE TITLE
Question: Null and the Expression-Syntax

### ISSUE THREAD

**Issue by manfredsteyer** [angular/angular#5151]
Hi,

I've noticed, that Angular2 shows an error message, when a binding expression tries to use a property of an object that is null. For instance, if you have

   {{ x.y.z }}

and x is null, there will be an error. Is there a way to prevent this error? I think, there are many situations, where you have null-values from time to time or until some bindings happens and in this cases, it would be great if Angular2 just ignored such error and evaluated them to null or "". I think, that is the semantic in Angular1 as well as in other similar template-engines.

Wishes,
Manfred

**Comment by otodockal** [comment]
try elvis operator {{ x?.y.z }}

https://angular.io/docs/ts/latest/guide/template-syntax.html#sts=The Elvis Operator ( ?. ) and null property paths

**Comment by pkozlowski-opensource** [comment]
Thnx @otodockal !

**Comment by manfredsteyer** [comment]
Thx for this fast reply.
