### ISSUE TITLE
Control Flow - Shorter '@' syntax for deferred loading

### ISSUE THREAD

**Issue by xXNickznXx** [angular/angular#51526]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

Since its no longer possible to comment on the RFCs for Control Flow & Deferred Loading, Im opening this issue to make a suggestion / ask a question.

### Proposed solution

Wouldnt it be possible to do the deferred loading with the '@' syntax like this:

```
@defer on viewport {
  <heavy-cmp />
} @placeholder {
  <img src="ph.png">
} @loading {
  <loading-spinner />  
}
```

That way the argument for block syntax:
- `#defer` is lighter weight
  - No need to name the "main" content block

would no longer be an argument.

### Alternatives considered

-

**Comment by JeanMeche** [comment]
Hi, the deferred syntax will be the same as the control flow syntax. 

The team is currently gathering feedbacks and weighing pros & cons on which syntax to choose for the new control flow. 

Stay tuned !

**Comment by xXNickznXx** [comment]
I know that its still open which syntax should be chosen. I just wanted to add another argument for the '@' syntax or rather to invalidate an argument for the block syntax.

**Comment by xXNickznXx** [comment]
@JeanMeche ?
