### ISSUE TITLE
Docs > Navigation Pane > Indentations of topics > Cluttered overview

### ISSUE THREAD

**Issue by BerndHme** [angular/angular#51524]
### Describe the problem that you experienced

Cluttered overview in the navigation pane.  
I think it would be better to enlarge the indentation of nested topics.  
... now it's hard to keep track of where you are in the navigation.

Example > https://angular.io/guide/pipes-overview
![image](https://github.com/angular/angular/assets/132269491/157ea065-71c5-410d-863f-dd6f367d60db)

Example (right and left) > https://angular.io/tutorial/tour-of-heroes/toh-pt4
![image](https://github.com/angular/angular/assets/132269491/0578637a-42b1-49ff-87cc-995103a83b4e)

Example (better) > https://learn.microsoft.com/en-us/aspnet/core/mvc/overview?view=aspnetcore-7.0
![image](https://github.com/angular/angular/assets/132269491/f0657920-e439-4854-9fae-1bdb8804ee47)

**Comment by selehadin-cyber** [comment]
@BerndHme by "enlarge the indentation" do you mean like instead of 2 spaces for indenting 4 spaces(or more)

**Comment by BerndHme** [comment]
@selehadin-cyber Yup... exactly that.

Also, now looking back at the pictures... I think the spacing (vertical) between the topics may be less also.

I know they are little things
... but (at least for me) it helps to maintain a nice overview when learning Angular and jumping around topics.  
Often there are links in the docs for navigating a prerequisite or more detailed topic.
... but you get easily lost when the navigation is not that clear.

Thanks for responding!

**Comment by selehadin-cyber** [comment]
before

![image](https://github.com/angular/angular/assets/69892114/925370cb-4f44-4944-afed-7301af3ae3d6)

after

![image](https://github.com/angular/angular/assets/69892114/a20ea563-dcf3-480c-bca9-3e2ba1980db8)

what to you reckon?

**Comment by BerndHme** [comment]
To me that's better :) (at all levels of course)
... also I think the right side could benefit from more indentation.

Also I think a big benefit would be to reduce the vertical spacing
... maybe that's even the bigger issue
... because you lose track more easily with bigger spacing.

**Comment by selehadin-cyber** [comment]
dude/ette, you are actually right. reducing the vertical spacing by half makes a whole lot of a difference make it more easily navigatable

before

![image](https://github.com/angular/angular/assets/69892114/5c3dc055-1176-4fc5-affb-07045a8c4800)

after

![image](https://github.com/angular/angular/assets/69892114/fe3a9e78-997c-4fab-be3d-817ccf4ba95b)

**Comment by BerndHme** [comment]
Wel look at that :).
Yeah maybe on the right the biggest issue also is vertical spacing.
(it's dude)

Well done!

**Comment by selehadin-cyber** [comment]
made a pull request with the changes

i closed the first two pull requests because there was an issue with the "cla agreement" and the test for it fails. the issue is solved with the last pull request
