### ISSUE TITLE
date pipe uses us format for "shortDate" and "en-GB" locale

### ISSUE THREAD

**Issue by martiesim** [angular/angular#51534]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

The DatePipe uses the american date format for the format "shortDate", if the locale "en-GB" is given.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-4pnynj?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
The date is shown with american format with month before day and not in the british format with day before month.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.8
Node: 16.18.1
Package Manager: yarn 1.22.17
OS: linux x64

Angular: 15.2.9
... animations, cdk, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker
```

**Comment by JeanMeche** [comment]
The corresponding locale is not loaded by default, you need to do it yourself. 

```
import localeEnGB from '@angular/common/locales/en-GB';
registerLocaleData(localeEnGB );
```
