### ISSUE TITLE
bindToComponentInputs does not work for components not in routes

### ISSUE THREAD

**Issue by NRaf** [angular/angular#51531]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

If I have a component that is not defined in the `routes`, I can't access router params using component inputs (with `paramsInheritanceStrategy` and `bindToComponentInputs` both enabled).

I can access the variables if I load that same component using a `router-outlet`. The documentation isn't very clear on this point.

e.g. 
![image](https://github.com/angular/angular/assets/292355/2af8402a-bc23-40ec-9e87-d277415d5ee2)

There is no clear reference to this here: https://angular.io/guide/router#getting-route-information

The closest reference I've found is this, however this isn't very easy to understand:
![image](https://github.com/angular/angular/assets/292355/d96c94dd-b074-4cdf-9fef-0c230c6980f1)
https://angular.io/api/router/ExtraOptions

I'm not sure if this is a limitation or a bug.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-wy6vp7?file=src%2Fparent.ts,src%2Fmain.ts,src%2Findex.html

### Please provide the exception or error you saw

```true
The route params do not work when the component inputs are in a component that isn't defined in a route configuration.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.0
Node: 18
```

**Comment by JoostK** [comment]
This is certainly working as expected. The router only manages components that it mounts into `route-outlet`s.

**Comment by JeanMeche** [comment]
This is behavior is expected. `bindToComponentInputs` will only impact component that are created by the router.
