### ISSUE TITLE
Expose HTTP_INTERCEPTOR_FNS in public api

### ISSUE THREAD

**Issue by jsaguet** [angular/angular#51539]
### Which @angular/* package(s) are relevant/related to the feature request?

common/http

### Description

Http interceptor functions are currently provided by two injection tokens: `HTTP_INTERCEPTOR_FNS` and `HTTP_ROOT_INTERCEPTOR_FNS`. None of which are available as public APIs.

Instead, we have to use 
```typescript
provideHttpClient(withInterceptors(...interceptors))
```

Let's say we have an application that use a set of interceptors. We will use them like that:
```typescript
provideHttpClient(
    withInterceptors([
	commonInterceptor1,
	commonInterceptor2,
    ])
)
```

Now let's say we import a library and this library needs to provide another interceptor to work.

The only way to provide an additional interceptor from the library would be to do:
```typescript
export function provideAdditionalFeature() {
    return makeEnvironmentProviders([
	...featureProviders,
	provideHttpClient(withInterceptors([additionalInterceptor])),
    ]),
}
```

We need to provide again the http client even though we only want to provide a new interceptor.

If we had access to the underlying `HTTP_INTERCEPTOR_FNS`, we could avoid providing again the http client by doing this:
```typescript
export function provideAdditionalFeature() {
    return makeEnvironmentProviders([
	...featureProviders,
	{
	    provide: HTTP_INTERCEPTOR_FNS,
	    useValue: additionalInterceptor,
	    multi: true
	},
    ]),
}
```

This is exactly what is done internally for the `provideClientHydration()` (except that it uses another token but it's equivalent)

```typescript
export function withHttpTransferCache(): Provider[] {
  return [
    ...
    {
      provide: HTTP_ROOT_INTERCEPTOR_FNS,
      useValue: transferCacheInterceptorFn,
      multi: true,
      deps: [TransferState, CACHE_STATE]
    },
    ...
  ];
}
```

### Proposed solution

Export `HTTP_INTERCEPTOR_FNS` in public API.

### Alternatives considered

I can see 3 alternatives:
The first one, I already talked about it, is to keep providing http client everytime we want to provide an interceptor.

The second one I see is to keep using the old `HTTP_INTERCEPTOR` token.
With this solution, we're forced to use `withInterceptorsFromDi()` and this `HTTP_INTERCEPTOR` token is already considered a legacy API as we can see in the angular code:
```typescript
export function withInterceptorsFromDi(): HttpFeature<HttpFeatureKind.LegacyInterceptors> {
  return makeHttpFeature(HttpFeatureKind.LegacyInterceptors, [
    {
      provide: LEGACY_INTERCEPTOR_FN,
      useFactory: legacyInterceptorFnFactory,
    },
    {
      provide: HTTP_INTERCEPTOR_FNS,
      useExisting: LEGACY_INTERCEPTOR_FN,
      multi: true,
    }
  ]);
}
```

The third option I see is to expose the interceptor from the library and let the consumer import it in `withInterceptors()`. 
But this causes a problem with encapsulation.

**Comment by JeanMeche** [comment]
Hi, you can have a look at #51303 which explains the current design choice.
