### ISSUE TITLE
Add the latest version of Angular on the toolbar of angular.io website

### ISSUE THREAD

**Issue by akuma8** [angular/angular#51548]
### Describe the problem that you experienced

It would be nice to have the latest version of Angular on the toolbar of https://angular.io so we don't need to visit the github repository to have that information.

### Enter the URL of the topic with the problem

https://angular.io

**Comment by selehadin-cyber** [comment]
Hi

that information is available on the footer of the website

**Comment by JeanMeche** [comment]
@selehadin-cyber This is only partially true. Currently the footer shows 16.2.3 while it hasn't been released yet (it's the next patch version to come).

**Comment by ferrorenan** [comment]
Hey guys, how are you?!

I implemented a possible solution to this issue and it's available for approval in the PR.

PR link: https://github.com/angular/angular/pull/51789

**Comment by JeanMeche** [comment]
We're looking at deprecating angular.io in favor of https://angular.dev/, so we're only landing this for the new doc site. 

This has been done with #54161
