### ISSUE TITLE
Chrome toolbar icon reports wrong app mode in Firebase Console

### ISSUE THREAD

**Issue by bampakoa** [angular/angular#51565]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

1. Navigate to Firebase Console
2. Click on the Extensions button and pin Angular DevTools
3. Click the Angular DevTools button in the Chrome toolbar

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

The message displayed should indicate that the application is running in production mode:

>Angular application running in production mode. We recommend using DevTools with apps in dev mode, running ng serve.

Instead it says:

>Angular application running development mode. Open developer tools, and select the Angular tab.

### Please provide a screenshot if possible [Bug Report only]

![image](https://github.com/angular/angular/assets/7170892/29d366c5-d0dd-4ee2-b285-832b92a1cddf)

**Comment by JeanMeche** [comment]
https://console.firebase.google.com/ exposes a global `ng` object that is not our object ! 

cc @AleksanderBodurri
