### ISSUE TITLE
Changing variable doesn't update CSS class

### ISSUE THREAD

**Issue by rsmith31415** [angular/angular#5156]
There is small issue after changing a variable in order to set a CSS class. This is better explained using an example:

[Demo](http://plnkr.co/edit/0dtRMNxqb0hQmOPLLSsH?p=preview)

The idea is that after clicking one of the words, the property that controls a CSS class will be updated to reflect the selected word.

```
<div ng-click="changeStatus(button)" ng-repeat="button in buttons" ng-class="{value: button.status}">
        {{ button.name }}
</div>
```

So there are a couple of objects in an array called `buttons` and we want to show a different color for the element with class `value` which is set if the property `button.status` is `true`.

The problem is that if you alternate between clicking on "button1" and "button2" several times, eventually you will find that the recently clicked element doesn't change color as it should. However, modifying something in the browser or moving the mouse over other elements in the page triggers the appropriate change. As far as I can tell, this only happens in Chrome dev. I tested in Firefox and Chrome stable (on Ubuntu 15.10) and I believe this problem doesn't occur (although maybe I'm not repeating the process enough times). 

I initially thought this was due to the digest cycle not being triggered immediately, but I'm not sure why this only occurs occasionally and other browsers seem to be producing the correct behavior. Any ideas?

**Comment by amsingh-qasource** [comment]
![photo1](https://cloud.githubusercontent.com/assets/5499503/10990038/d1f3d4d0-8474-11e5-9e91-30c633662f97.png)
hghfghfghgfh

**Comment by robwormald** [comment]
@rsmith31415 this repo is for angular2 - you want https://github.com/angular/angular.js 

Thanks!

**Comment by amsingh-qasource** [comment]
hfghfghfgh
![photo1](https://cloud.githubusercontent.com/assets/5499503/10990309/9ac7c41e-8477-11e5-8b4b-e71a1f814826.png)

**Comment by rsmith31415** [comment]
Oh, sorry about that. Is there some way to migrate it or just copy and paste?
