### ISSUE TITLE
Directive input prevents default html button attribute from being set

### ISSUE THREAD

**Issue by mkhodan** [angular/angular#51567]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I have a directive `LoggerDirective` which has an input `disabled` and I want to attach it to default html button. Also in order to disable button on condition the only way to do it is to add `[disabled]="condition"` to it. This way button attribute and directive input with same name collide and as a result only input is compiled while button attribute is ignored and as a result the button is not disabled.

If I add directive then only input metadata is added to actual html element:
`<button logger ng-reflect-disabled="true">Click on me!</button>`
If I don't add directive then button attribute is added correctly:
`<button disabled>Click on me!</button>`

I would expect both to be present like this:
`<button logger disabled ng-reflect-disabled="true">Click on me!</button>`

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-input-collision

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Please see stackblitz with all details.
```

### Anything else?

I understand that this is not the best practice to give an input the same name as default attribute but I'm using 3rd party provided directive and can't change it's input name from `disabled` to `isDisabled` or something similar.

**Comment by JeanMeche** [comment]
This works as expected the input is "overriding" the default attribute. 

The workaround for this is to use `attr.disabled`
