### ISSUE TITLE
No mention or explanation of `implements OnInit`

### ISSUE THREAD

**Issue by bassamanator** [angular/angular#51586]
### Describe the problem that you experienced

Under `step 2` of [View product details](https://angular.io/start/start-routing#view-product-details) section, the class `ProductDetailsComponent` implements `OnInit`, however, there is no mention of adding `implements OnInit` in the documentation.

```ts
export class ProductDetailsComponent implements OnInit {

  product: Product | undefined;
  /* ... */
}
```

### Enter the URL of the topic with the problem

https://angular.io/start/start-routing#view-product-details

### Describe what you were looking for in the documentation

There should be some mention and explanation of `implements OnInit` at this step.

### Describe the actions that led you to experience the problem

I'm following along with the official Angular documentation to learn Angular.

I have not skipped any steps, and have started from the very begining.

### Describe what you want to experience that would fix the problem

Please mention this change to the file `src/app/product-details/product-details.component.ts`.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/61985779/1b37f771-6327-4212-bfd9-a1aae5f91847)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
N/A.
```

**Comment by sascha10000** [comment]
Hey I would challenge if that is really an issue as OnInit is shown in the code (I believe most people just use the copy button) and it is a super basic lifecycle hook. Anyways if it should be mentioned I would say it should happen in Step 4 where ngOnInit is implemented.

![image](https://github.com/angular/angular/assets/6839449/ce7ebdeb-f7c8-4929-bf96-0759c1e4b7bb)

**Comment by bassamanator** [comment]
Thus far, all the changes that the user is required to make are explicitly mentioned.

This change is not.

**Comment by sascha10000** [comment]
True if it is so detailed than it should be added. But if you use `ng g component`, as far as I have it in mind right now, it always autmatically adds `implements OnInit`. Anyways if these automatically generated code parts are also explained, it should be added.

**Comment by simlw** [comment]
According to practical experience, if some initialization work needs to do after Angular has initialized, you can implement the `ngOnInit()` method of the `OnInit` interface. Otherwise, you may not use it. 

If you want to know more abort `OnInit`, you can see the comments。
```
/**
 * @description
 * A lifecycle hook that is called after Angular has initialized
 * all data-bound properties of a directive.
 * Define an `ngOnInit()` method to handle any additional initialization tasks.
 *
 * @see `AfterContentInit`
 * @see [Lifecycle hooks guide](guide/lifecycle-hooks)
 *
 * @usageNotes
 * The following snippet shows how a component can implement this interface to
 * define its own initialization method.
 *
 * {@example core/ts/metadata/lifecycle_hooks_spec.ts region='OnInit'}
 *
 * @publicApi
 */
export declare interface OnInit {
    /**
     * A callback method that is invoked immediately after the
     * default change detector has checked the directive's
     * data-bound properties for the first time,
     * and before any of the view or content children have been checked.
     * It is invoked only once when the directive is instantiated.
     */
    ngOnInit(): void;
}
```

**Comment by sascha10000** [comment]
That is true, but we are discussing about the documentation it self not the comments in the code, therefore that seems to be not relevant.

**Comment by akib1997** [comment]
Working on it.

**Comment by nathanejbrown** [comment]
It appears that the documentation does give an explanation as to the usage of `implements`. Perhaps I'm misunderstanding you and looking in the wrong place? 
![image](https://github.com/angular/angular/assets/18193876/2d9a9830-9572-42d9-b395-e6f8d2f0a18a)

**Comment by JeanMeche** [comment]
The doc has been updated by #51634, you're actually seeing the changes !
