### ISSUE TITLE
Add support for HTMLSelectlistElement

### ISSUE THREAD

**Issue by Totati** [angular/angular#51596]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler, forms

### Description

[Developer previews](https://css-tricks.com/the-selectmenu-element/) [started](https://developer.chrome.com/blog/whats-new-css-ui-2023/#selectmenu) [to pop up](https://microsoftedge.github.io/Demos/selectlist/index.html) for the new [HTMLSelectListElement](https://open-ui.org/components/selectlist/) (previously HTMLSelectMenuElement), which allows developers to create more customizable selects. Selectlist is currently available under "Experimental Web Platform features" and Angular does not support it. Angular will throw an exception with `CUSTOM_ELEMENTS_SCHEMA` as this new native element's name does not contain dash (as native elements never), `NO_ERRORS_SCHEMA` has to be used for obvious reasons. Setting `NO_ERRORS_SCHEMA` hides the error but because of missing `NG_VALUE_ACCESSOR` for the selectlist it does not work with Angular forms.

### Proposed solution

Add `selectlist` to `SCHEMA` and implement `NG_VALUE_ACCESSOR` for it.

### Alternatives considered

None

**Comment by JeanMeche** [comment]
Since this only works on Chromium browsers and only with a flag enabled, I don't think the framework should support them.

**Comment by Totati** [comment]
I'm aware of this, but in the long run it will be needed. As Google started to "promote" it with features as "landed recently or are coming soon", I think this means they are committed to it. Of course the other browsers can delay the implementation, but for tracking this issue is good to have.
