### ISSUE TITLE
Custom form control with NG_VALIDATORS does not update parent form status if inside FormArrray

### ISSUE THREAD

**Issue by ReviakinAleksey** [angular/angular#51598]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

I created `CustomNumberComponent` component that is implementing ControlValueAccessor, Validator interfaces.
This simple component includes simple validation (value > 0).

**Case 1** of provided example used to demo correct behavior. In this case FormGroup initialized with invalid value `-1` and then rendered using `CustomNumberComponent`
`
 this.formOne = new UntypedFormGroup({
      simple: new UntypedFormControl(-1),
    });
`
formOne behaved as expected and show `INVALID` status right from start.

**Case 2**  I use `NumbersArrayComponent` (also  implementing ControlValueAccessor, Validator interfaces) to build array of  `CustomNumberComponent` inside. FormGroup that was initialized with array having invalid value `-2`:

`
   this.formTwo = new UntypedFormGroup({
      numbers: new UntypedFormControl([-2, 2, 3]),
    });
`
In this case formTwo has initial status  **VALID** and this behavior's looks like a bug, because once I change input with value -2 to another negative value via UI formTwo change status to `INVALID`.

**Case 3** provided to check how form behaves if no custom ControlValueAccessor/Validator is used, form is initialized having incorrect value `-3` in one of `UntypedFormArray` element.
`
 this.formThree = new UntypedFormGroup({
      numbers: new UntypedFormArray(
        [-3, 2, 3].map((v) => new UntypedFormControl(v, [Validators.min(0)]))
      ),
    });
`
In this case formThree is in `INVALID` status right from the start as expected.

And **Case 4** is provided to simplify error reproduce case, this example does not use `NumbersArrayComponent`  and just use 
standard `UntypedFormArray` and `CustomNumberComponent` inside view.
This form also initialized  with array included value `-4` that does not valid for `CustomNumberComponent`
`
this.formFour = new UntypedFormGroup({
      numbers: new UntypedFormArray(
        [-4, 2, 3].map((v) => new UntypedFormControl(v))
      ),
    });
`
`formFour ` initially shown as `VALID` but in this case changing values inside this form vie UI does not update `formFour` status unlike **Case 2**

Summarizing:  FormGroup that have FormArray inside filled and then rendered using custom form control that is implements ControlValueAccessor and Validator interfaces  should honor these custom form control Validator results in parent FormGroup.
I.e. if one of custom form control initialized with invalid value parent FormGroup shoudl be invalid too.

### Please provide a link to a minimal reproduction of the bug

https://angular-playground-v16-bug.stackblitz.io

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Please see playground.
```

**Comment by MikeMatusz** [comment]
It seems like in general, errors from inside a FormArray don't propagate up to make the top-level form invalid, I'm able to reproduce with just `Validators.required` on a control in a FormGroup inside an array.  If I initialize the form with values so everything is valid, then clear out the required control, the FormArray is invalid, but the top-level FormGroup is still valid.

It changes to invalid if I call `updateValueAndValidity()`, but then if I enter a value to make the FormArray valid, the top-level FormGroup stays invalid unless I `updateValueAndValidity()` on it again.

**Comment by Totati** [comment]
@ReviakinAleksey You have an error in line 52. Changing `this.formThree` to `this.formFour` fixes the demo.
I would simplify your template to
```html
<div [formGroup]="formFour">
  <div
    formArrayName="numbers"
    *ngFor="let item of numbersFour.controls; let i = index"
  >
      <custom-number [formControlName]="i"></custom-number>
  </div>
</div>
```

Using `formControlName` is way less error prone.

**Comment by JeanMeche** [comment]
Same as what @Totati said, this is mostly an issue with the demo. 
If you have a similar issue with a repro, feel free to file a new issue. Thank you for your understanding.
