### ISSUE TITLE
Standalone ViewChild unit test mocks do not get @Input() properties set on them

### ISSUE THREAD

**Issue by conner-fallone** [angular/angular#51603]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When testing a standalone component that has a standalone ViewChild, and then trying to mock the ViewChild, the input bindings do not get set at all on the ViewChild component. I would expect any Inputs passed to the mocked component to be set on the component itself, but instead the properties are non-existent. The only properties that appear to exist on the mocked component are any initialized properties on the mock itself.

Steps to Reproduce:
1. Create a standalone parent component that has a standalone child component
2. Add a ViewChild in the parent component for the child component
3. Write a unit test that uses .overrideComponent to mock the child component, and then expect the parent component's child component public property from the Input() bining to be set, and notice that it is never set. 

If you get rid of the parent/child components being standalone, and just declare them in the test, it will work as expected.

Broken Example - https://stackblitz.com/edit/stackblitz-starters-kue3py?file=src%2Fapp.component.ts
Working Example (removed standalone) - https://stackblitz.com/edit/stackblitz-starters-x4dkjz?file=src%2Fapp.component.ts,src%2Fapp.component.html,src%2Fmain-testing.ts,src%2Fapp.component.spec.ts

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-kue3py?file=src%2Fapp.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 16.1.6
```

### Anything else?

This appears to be related to standalone components, as when standalone is taken out of the equation for the parent and child components, all @Input() properties appear to be set on the ViewChild component.

**Comment by JoostK** [comment]
The `MockChildComponent` is using `useClass` to proxy itself as a `ChildComponent`, but this is not the correct thing to do. It should be using `useExisting`, at which point the broken example starts to work.

It works in the non-standalone example because you _are_ using the actual `ChildComponent` there, since the override is still targeting `Component.imports` but it's the `NgModule.declarations` that is actually being used.
