### ISSUE TITLE
Unsubscribe from service's EventEmitter observer when a component has been destroyed

### ISSUE THREAD

**Issue by rosendi** [angular/angular#5160]
Please, have a look at the plunk - http://plnkr.co/edit/Xv02Px?p=preview.

There is an `Item` component that subscribes to the `DataService` events and unsubscribes when it has been destroyed using the `onDestroy` callback.

```
constructor(private data: DataService) { 
  this.observer = this.data.on((someData) => {
    console.log("onData");  
  })
}
  
onDestroy() {
  this.observer.unsubscribe();
}
```
Is there any better way to achieve the same result or is it completely a wrong way to create a service which emits some events? Could the cancelling subscription logic be moved to the `DataService` which automatically cancels out the component's subscription?

Something like:

```
class Item {
  constructor(private data: DataService) { 
    this.data.on((someData) => { ... })
  }
}

class DataService {
  ...

  on(next: (data: string) => void) {
    let observer = this.event.observer({ next: next });

    // observer.unsubscribe() is called when a component whose required subscription has been destroyed

    return observer;
  }
}
```

**Comment by robwormald** [comment]
This is a pretty good use case for the `async` pipe, assuming you're going to be rendering something to the view, or a custom pipe that does something similar - they will automatically clean up subscriptions when the component is destroyed.

Note that the EventEmitter's 'observer' method will disappear in the next release, and stick closer to Observable semantics:

```js

class MyDataService {
  event: new EventEmitter()
}

class MyComponent {
  constructor(dataService: MyDataService){
    this.event = dataService.event
  }
}

```
```html
<!--subscribe happens inside the pipe -->
<div>{{event | async }}</div>

```

**Comment by rosendi** [comment]
@robwormald Thank you! I've just refactored my data service, found the PR - #4893.
