### ISSUE TITLE
add alphanum validators `{ Validators } from '@angular/forms';`

### ISSUE THREAD

**Issue by Vic-rider** [angular/angular#51614]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

On password input, we can add alphanum validator to make sure that the password contain at least 01 letter and 01 number.

### Proposed solution

Create a validators `Validators.alphanum`

### Alternatives considered

manual alphanum validators

**Comment by JoostK** [comment]
The intention of the Angular forms validations is to align with the available HTML . Alphanum validation logic can be achieved using the `pattern` validator.

**Comment by AndrewKushnir** [comment]
I'm closing this PR based on what Joost mentioned above. Please create a custom validator to handle this use-case. You can use one of the built-in validators as a pattern for the custom one.
