### ISSUE TITLE
add link validators `{ Validators } from '@angular/forms'`;

### ISSUE THREAD

**Issue by Vic-rider** [angular/angular#51617]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

Sometimes we need to control an input that will contain a link. So, imagine a Validator that can help you know if what typed is a `http` link or `https` link.

### Proposed solution

The link Validator, can : 

- check if the input text star `http://` or `https://` or `www`
- check that the input text must not contain space ` `

### Alternatives considered

Set a man made validator

**Comment by AndrewKushnir** [comment]
Thanks for creating a feature request. We do not plan to add new validators at this moment and the best approach for now would be to create a custom validator, see https://github.com/angular/angular/issues/51614#issuecomment-1702915189 for additional details.
