### ISSUE TITLE
Problem with service worker in handling notifications

### ISSUE THREAD

**Issue by vladosamerikos** [angular/angular#51625]
### Which @angular/* package(s) are relevant/related to the feature request?

service-worker

### Description

We are currently using a service worker in our Angular application to handle push notifications. We have noticed that the `handlePush` function of the service worker is parsing notifications in a non-standard way, which could lead to compatibility issues and maintain less maintainable code.

The current handlePush function has the following form:
```
async handlePush(data) {
    await this.broadcast({
        type: "PUSH",
        data
    });
    if (!data.notification || !data.notification.title) {
        return;
    }
    const desc = data.notification;
    let options = {};
    NOTIFICATION_OPTION_NAMES.filter((name) => desc.hasOwnProperty(name)).forEach((name) => options[name] = desc[name]);
    await this.scope.registration.showNotification(desc["title"], options);
}
```

This implementation uses a non-standard object structure for notifications and performs unnecessary checks.

### Proposed solution

We propose a more standardized way of handling push notifications in the `handlePush` function. Here is the proposed new implementation:
```
async handlePush(data) {
    await this.broadcast({
        type: "PUSH",
        data
    });
    if (!data || !data.title) {
        return;
    }
    const desc = data;
    let options = {};
    NOTIFICATION_OPTION_NAMES.filter((name) => desc.hasOwnProperty(name)).forEach((name) => options[name] = desc[name]);
    await this.scope.registration.showNotification(desc["title"], options);
}
```

### Alternatives considered

This new implementation eliminates the need to check for the existence of the "notification" key and simplifies the code.

**Comment by alxhub** [comment]
What is the standard that you're referencing for the shape of a push notification? Which services implement notifications this way?

**Comment by pkozlowski-opensource** [comment]
Closing this issue as we haven't heard back with the additional info.
