### ISSUE TITLE
feat(Component) Simple syntax for dynamically creating child components

### ISSUE THREAD

**Issue by alexfluger** [angular/angular#5162]
On my project I need to put a component into a container component based on some application state. I am aware about DynamicComponentLoader, but its syntax is to complex and require additional services to be injected. Also there is a problem to bind values to a dynamically inserted component. 

I think that it would be a nice to have a method that will allow us to insert child components dynamically in a very easy way, something like this:

```cmp.appendChildFromTemplate('<some-dynamic-component [bind-prop1]="someValue" [(bind-prop2)]="someOtherValue"></some-dynamic-component>')```

Something like [ReactDOM.render](https://facebook.github.io/react/docs/top-level-api.html#reactdom.render)

**Comment by webteckie** [comment]
+1 instead of a string input i would be more inclined to suggest a config object with properties like template or templateUrl, input/output bindings, etc.

**Comment by jorgeunimicro** [comment]
We al miss $compile from angular1

**Comment by ericmartinezr** [comment]
I'm with @webteckie in this one. This looks really weird and unintuitive
```
dcl.loadIntoLocation(SomeCmp, elementRef, anchor).then((ref) => {
   ref.instance.someProp = 'value';
});
```
I would rather a syntax like this
```
// First and second params
dcl.loadIntoLocation(SomeCmp, {
   inputs : [...],
   templateUrl : ''
}, elementRef, anchor);

// Or array
var cmp = [SomeCmp, { /* data */ }]
dcl.loadIntoLocation(cmp, elementRef, anchor);

// Or someway to create an inline component
var cmp = Component.create({/* data */}); // or Component.compile({...});
dcl.loadIntoLocation(cmp, elementRef, anchor);
```

**Comment by pkozlowski-opensource** [comment]
> cmp.appendChildFromTemplate('<some-dynamic-component [bind-prop1]="someValue" [(bind-prop2)]="someOtherValue"></some-dynamic-component>')

This would require compiler during runtime. I agree that we can do better when it comes to higher-level API and I believe that part of what is being asked here was either covered by API changes to DCL or will be covered by #8164
