### ISSUE TITLE
HTML and CSS intellisense is not working in Inline component.

### ISSUE THREAD

**Issue by sheikalthaf** [angular/angular#51621]
### Which @angular/* package(s) are relevant/related to the feature request?

language-service

### Description

I prefer to have a single file for my component but HTML and css intellisense not working. So we have to write all the code manually. For HTML we getting suggestion but it is very slow. For styles we are not even getting any suggestions. Please fix this issue.

I feel like Inline component is highly underrated because of this.

### Proposed solution

We need some developer experience like Html and css file.

### Alternatives considered

For now good

**Comment by DAVIAMERICO242** [comment]
Same problem 1 year later, non inline styles implies "do components to anything even simple as hell" and specifity bugs to large projects

**Comment by JeanMeche** [comment]
Without more details, this isn't actionable to us. 

Inline templates are supported by the Angular Language Service extension.

**Comment by DAVIAMERICO242** [comment]
problem is angular accepts a  generic object for stylying so n o intellisense
