### ISSUE TITLE
XSS Attacks Prevention 

### ISSUE THREAD

**Issue by Vasanthvivi** [angular/angular#51633]
### Description

Hi team,, angular is not supporting the Xss Attacks prevention when we use the 'require-trusted-types-for 'types';' in the Content Security Policy header especially while dealing with the lazy loaded modules...

### Proposed solution

Angular has to support the require-trusted-types-for,, even that is experimental still, it has to support.

### Alternatives considered

NA

**Comment by JeanMeche** [comment]
Angular has support for trusted types. Did you check [the docs](https://angular.io/guide/security#enforcing-trusted-types) ?

**Comment by jessicajaniuk** [comment]
@Vasanthvivi As @JeanMeche said, Angular has supported Trusted Types for quite a while. Can you clarify what the issue is here?
