### ISSUE TITLE
Circular dependency in DI

### ISSUE THREAD

**Issue by tomer953** [angular/angular#51639]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Using standalone components, I found a use-case where I need to provide a service inside component (and not globally).
I also wanted to try to inject some data to each service instance, via the component instance, instead of using something like:

```ts
@Input({ required: true}) title: string;

service = inject(MyService);

ngOnInit() {
 this.service.setTitle(this.title);
}
```

I wanted to convert title to inject token inside the service, and provide its value here in the component.
```ts
export const TITLE = new InjectionToken<string>('title');
...
  providers: [
    {
      provide: TITLE,
      useFactory: () => inject(MyComponent).title,
    },
    MyService,
  ],
```

however this leads to circular dependency  (component -> service -> title -> component)
I did not managed to fix it via `forwaredRef()`.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/rrabnq-a1f89x?file=src%2Fexample%2Fapp.component.ts

### Please provide the exception or error you saw

```true
Error: NG0200: Circular dependency in DI detected for TableRowComponent. Find more at https://angular.io/errors/NG0200
    at throwCyclicDependencyError (vendor.js:31682:9)
    at getNodeInjectable (vendor.js:35988:7)
    at searchTokensOnInjector (vendor.js:35936:12)
    at lookupTokenUsingNodeInjector (vendor.js:35888:26)
    at getOrCreateInjectable (vendor.js:35819:19)
    at ɵɵdirectiveInject (vendor.js:41921:10)
    at ɵɵinject (vendor.js:32098:59)
    at inject (vendor.js:32180:10)
    at Object.useFactory (main.js:53:76)
    at NodeInjectorFactory.factory (vendor.js:40554:32)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.0
Node: 16.20.0
Package Manager: yarn 1.22.19
OS: linux x64

Angular: 16.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.0
@angular-devkit/build-angular   16.1.0
@angular-devkit/core            16.1.0
@angular-devkit/schematics      16.1.0
@angular/cli                    16.1.0
@schematics/angular             16.1.0
rxjs                            7.4.0
typescript                      5.0.3
```

### Anything else?

as shown in the Stackblitz example,
the actual use case is to use separate component for each table row,
each table row has its own item data and actions, I want a new instance of service for each table row, to manage its state locally in the scope of the row only.

in a side note to the question \ bug, I wonder if what I'm trying to do is a best practice, or should I just call the service with `.setTitle()`  after init for example

**Comment by JoostK** [comment]
This is a true DI cycle. forwardRef does not apply to DI cycles, only import cycles.

DI cycles can be broken by pulling some work outside of the construction of instances, so `setTitle` could be a viable option.
