### ISSUE TITLE
[docs] Version compatibility guide: TypeScript versions listed for Angular 8.2 + Angular CLI 8.2/8.3 are incorrect

### ISSUE THREAD

**Issue by LayZeeDK** [angular/angular#51643]
### Describe the problem that you experienced

TypeScript support is unclear for Angular 8.2.x.

#31615 included TypeScript 3.5 support in Angular 8.2.0. Looking at Angular changelogs, it is unclear if TypeScript 3.4 support was dropped in Angular 8.2.0. However, it is clear that both TypeScript 3.4 and 3.5 support was dropped in Angular 9.0.0.

The *Version compatibility* guide is missing an upper version range for the Angular 8.2.x + Angular CLI 8.2.x entry.

### Enter the URL of the topic with the problem

https://angular.io/guide/versions#before-v9

### Describe what you were looking for in the documentation

I was looking for the supported versions of TypeScript in an Angular 8.x application.

### Describe the actions that led you to experience the problem

- The Angular 8.2.x + Angular CLI 8.2.x entry lists TypeScript support as `>=3.4.2` (notice no upper limit)
- The Angular 8.2.x + Angular CLI 8.3.x entry lists TypeScript support as `>= 3.5.3 <3.6.0` - is TypeScript 3.4.x not supported by this combination?

### Describe what you want to experience that would fix the problem

- An upper limit on the Angular 8.2.x + Angular CLI 8.2.x entry's TypeScript version range
- Clarification on whether TypeScript 3.5 support was dropped in Angular 8.2.x and Angular CLI 8.2.x or 8.3.x

### Add a screenshot if that helps illustrate the problem

<img width="493" alt="Angular 8.x version compatibility matrix" src="https://github.com/angular/angular/assets/6364586/70a4ba50-6c00-4dcc-8852-074b2c9cd2a9">

### Provide any additional information here in as much as detail as you can

My original work in https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3 suggests that Angular CLI 8.3.x only supports TypeScript 3.5.x. This was likely based on the defaults in a freshly generated Angular CLI 8.3.x workspace.

I am willing to submit an Angular.io PR when details on version ranges are clarified.

**Comment by JoostK** [comment]
Minors have never dropped support for TypeScript, since that would be breaking change.

**Comment by JeanMeche** [comment]
We likely should merge those 2 lines (CLI 8.2/8.3)  since the TS versions should be the same

**Comment by alan-agius4** [comment]
Closed via RouterConfigLoader
