### ISSUE TITLE
`ngOnChanges` can be out of sync

### ISSUE THREAD

**Issue by waterplea** [angular/angular#51642]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I have previously used directives to override default values for inputs in components. I do that in constructor so that it happens before inputs are processed. This way if somebody explicitly passed some value to the input – it is used instead of my directive override of default value.

I have discovered that it is broken for one-time string bindings. `ngOnChanges` then reports incorrect value. This used to work sometime ago, but maybe in ViewEngine as it's been a while since I touched that code. Check out the link with the most basic reproduction.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/ngonchange-issue

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 16
```

**Comment by JoostK** [comment]
This is ultimately because of #34227.`ngOnChanges` represents the _binding_ value, not the component's property value (it may have been transformed or not stored at all).

**Comment by waterplea** [comment]
@pkozlowski-opensource your last comment to that issue states that:

1) we should not use setters on inputs which is a really really weird request that has never surfaced before in all my time working with Angular
2) we should rely on ngOnChanges which is inconsistent in my example

It was pretty handy that there was a time before inputs were processed (constructor) and after (hook) which allowed for things like I described — having directives to implement certain presets.

We use that a lot in Taiga UI. There's also an article by Netanel Basal using similar practice:
https://netbasal.com/leverage-angulars-element-injector-to-make-dry-inputs-827e3b84bf10

Although he is using ngOnInit there to enforce directive value, kind of the opposite of what I'm struggling with here )

**Comment by alxhub** [comment]
Angular is working as intended here, with the intention being that you cannot rely on the exact timing of when inputs are set.

`ngOnChanges` is a lifecycle hook which observes changes to bound inputs of a component/directive. In `ngOnChanges` you can rely on all changed binding values having been written to their corresponding input properties. This lifecycle hook is executed when the parent template is being checked, when Angular stabilizes the binding to `value`.

The `Dir` directive in the example observes a different point in time (its construction) and _also_ writes to the input property for `value`.

Thus, the `value` input property has two competing writers:

* the parent template, via the binding to `value`
* the `Dir` directive, via its constructor

Given that Angular has an optimization for static inputs which sets them earlier than dynamic ones, this creates an observable difference depending on whether `Dir` executes its constructor and writes to the input property before the binding is set or vice versa. This nicely illustrates that it's never safe to directly write to an input property.

To accomplish the same effect, I would suggest using DI to provide default values from the directive that are injected into the component. This will ensure that any template-bound values take precedence over the configured defaults.
