### ISSUE TITLE
Zone.js node patches - Error: Uncaught (in promise): TypeError: setInterval(...).unref is not a function

### ISSUE THREAD

**Issue by matthewjh** [angular/angular#51653]
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

No

### Description

The Zone.js node patch appears to omit a bunch of Node.js `Timeout` methods, such as unref. 

https://nodejs.org/api/timers.html#class-timeout

In consequence, use of the Zone node patches with any code that uses these methods will error out:

````
 Error: Uncaught (in promise): TypeError: setInterval(...).unref is not a function
    TypeError: setInterval(...).unref is not a function
        at setupConnectionsTracking (node:_http_server:503:84)
        at new Server (node:_http_server:540:3)
        at Object.createServer (node:http:63:10)
        at ExpressAdapter.initHttpServer
````

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Zone.js 0.13.1
```

cc @JiaLiPassion

**Comment by arturovt** [comment]
Could you provide a reproducible example? zone.js supports `unref`.

**Comment by alxhub** [comment]
Closing as no reproduction was provided.
