### ISSUE TITLE
Reference pages on angular.io not showing up in Google search results

### ISSUE THREAD

**Issue by Yogu** [angular/angular#51657]
### Describe the problem that you experienced

I noticed that pages from the "Reference" section of angular.io (e.g. documentation of classes and functions) rarely or never show up for Google search queries, even if these queries are explicitly naming one of these APIs (e.g. "NgZone" or "ResolveFn"). The results that show up instead are less relevant to the topic than the reference page would be. It seems like these pages are not included at all.

If you search for e.g. [site:https://angular.io/api/core/](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fangular.io%2Fapi%2Fcore%2FNgZone), it says "No information is available for this page", with a link to [No page information in search resutls](https://support.google.com/webmasters/answer/7489871?hl=en).

> It means that the website prevented Google from creating a page description, but didn't actually hide the page from Google.

I find that frustrating because it forces me to go to angular.io manually, type in the symbol name there, wait for the search to complete (it actually takes a second or two) and then find the top result in that search result box.

### Enter the URL of the topic with the problem

https://angular.io/api/core/NgZone

### Describe what you were looking for in the documentation

I want to look up the API documentation of a very specific symbol that I already know the exact name of

### Describe the actions that led you to experience the problem

Search on Google for the exact name -> do not get relevant results

### Describe what you want to experience that would fix the problem

I want the API pages to show up, ideally as first Google search result

**Comment by JeanMeche** [comment]
I think we can track this at #33760. 

Currently angular.io doesn't benefit from SSR nor prerendering.
