### ISSUE TITLE
Error has no exported member using  @angular/localize

### ISSUE THREAD

**Issue by zinebAme** [angular/angular#51664]
### Which @angular/* package(s) are the source of the bug?

localize

### Is this a regression?

Yes

### Description

Hello
I use angular V16 with  "@angular/localize": "^16.2.2",
but I got this error in my console

Error: node_modules/@locl/core/lib/core.module.d.ts:1:22 - error TS2724: '"@angular/localize"' has no exported member named 'ɵTargetMessage'. Did you mean 'TargetMessage'?

1 import { ɵMessageId, ɵTargetMessage } from '@angular/localize';

If anyone had any ideas how to resolve that?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.1
Node: 18.10.0
Package Manager: npm 8.19.2
OS: darwin arm64

Angular: 16.2.3
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.1
@angular-devkit/build-angular   16.2.1
@angular-devkit/core            16.2.1
@angular-devkit/schematics      16.2.1
@angular/cli                    16.2.1
@schematics/angular             16.2.1
rxjs                            7.8.1
typescript                      5.0.4
zone.js                         0.13.1
```

**Comment by JoostK** [comment]
`@locl/core` is using private API, which is no longer available as such in Angular 16. Looking at [the issue tracker of locl](https://github.com/loclapp/locl/issues) that library is no longer maintained.
