### ISSUE TITLE
Improve `inject()`/`Injector.get()` typings with a `multi:true` provider

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular#51675]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When using `inject()`/`Injector.get()` on a `multi: true` provider, the function returns `T` instead of `T[]`. 

If we add a parameter to expect a multiple values, we could already throw a runtime exception. 

I know there is a workaround when using `InjectionToken` by defining the generic part as an Array (That's we already do for `HTTP_INTERCEPTORS` for example), but that's isn't great either. 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-inject-multi?file=src%2Fmain.ts

**Comment by JoostK** [comment]
The favored approach to this problem would be similar to #28778, e.g. having a `MultiInjectionToken<T> extends InjectionToken<readonly T[]>` that would then tell Angular all providers are effectively `multi: true` on top of ensuring that the types are correct.

This avoids situations where providers may diverge in specifying `multi: true` (which results in a runtime error), or worse when there is only a single provider for a multi token that does not use `multi: true`, in which case injecting the token does not actually result in an array.

I would personally _not_ try to workaround the problem further by introducing additional options to consuming tokens, when there is a potential design that avoids all those pitfalls.

**Comment by JeanMeche** [comment]
@AndrewKushnir Do you remember why you closed #28778 without any comments ? 

`MultiInjectionToken` looks like an interesting feature to solve that issue !

**Comment by AndrewKushnir** [comment]
@JeanMeche the mentioned issue was closed as a part of the feature triage process - that issue had insufficient upvotes.

**Comment by yjaaidi** [comment]
💯 !

My 2 cents.

In addition to the issues raised above, here are some additional reasons:
- `multi: true` adds cognitive load to the user.
- It is a common issue to forget `multi: true` when providing some injection tokens.
- Token can be mistakenly overwritten if `multi: true` is forgotten.
- It is decoupled from the injection token and thus requires the user to know whether the token is expected to be multi or not from its usage (or the docs if token is properly documented).

`MultiInjectionToken` or `InjectionToken(name: string, opts: {multi: boolean})` could be an interesting alternative.

That said, this would require either:
- new "multi" alternatives to existing injection token: `MULTI_NG_VALUE_ACCESSOR`
- or a breaking change and a migration that renames old tokens to `LEGACY_NG_VALUE_ACCESSOR` just in case someone is using a multi token without multi on purpose and providing an array (I've seen that in some Angular Core tests but not in apps/libs yet)

**Comment by JeanMeche** [comment]
I'll close this in favor of #55555
