### ISSUE TITLE
USD currency symbol ($) missing in italian, hungarian locale.

### ISSUE THREAD

**Issue by tenlekdan** [angular/angular#51671]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

Currency symbol '$' for USD is missing when the locale is set to italian or hungarian.
Instead of symbol the currency code itself is shown i.e USD

This is working in angular/common: 5.0.0

Please note that this could also be happening for other currencies and other locale as well.

The version i am using is angular/common: 15.2.0

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-currency-pipe-yfzb8d?file=package.json

### Please provide the exception or error you saw

```true
NA
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.0
Node: 14.21.2
Package Manager: npm 6.14.17
OS: darwin x64

Angular: 15.2.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.0
@angular-devkit/build-angular   15.2.0
@angular-devkit/core            15.2.0
@angular-devkit/schematics      15.2.0
@angular/flex-layout            13.0.0-beta.38
@angular/service-worker         16.1.2
@schematics/angular             15.2.0
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by JeanMeche** [comment]
This display format is correct per the CLDR : https://github.com/unicode-org/cldr-json/blob/f93780d69dbd62550cd0a3eb64aa3c73b2c45e91/cldr-json/cldr-numbers-full/main/it/currencies.json#L1112C18-L1112C18
