### ISSUE TITLE
Closing file upload picker causes stepper dialog to close

### ISSUE THREAD

**Issue by Tharrington86** [angular/angular#51706]
### Which @angular/* package(s) are the source of the bug?

common, Don't known / other

### Is this a regression?

No

### Description

I have a stepper dialog that contains a file upload component. After the file picker launches, if the cancel button is clicked, the file picker and my stepper completely close and all entered data is lost.  I am assuming that an event is firing and that event is closing both items but I am unsure why (if this is expected behavior) and how to prevent this. Any ideas?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.9
Node: 18.16.1
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 15.2.9
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.14
@angular-devkit/build-angular   15.2.9
@angular-devkit/core            12.2.14
@angular-devkit/schematics      13.3.11
@angular/flex-layout            15.0.0-beta.42
@schematics/angular             15.2.9
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by JoostK** [comment]
/
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
