### ISSUE TITLE
Updating a signal during template or host binding execution is not allowed

### ISSUE THREAD

**Issue by roma2341** [angular/angular#51710]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Why does this error happen?
My code is simple:
```
...
mycomponent{
 mySignal = signal(false);
 @Input({required: true})
  set value(val: value){
  this.mySignal.set(val);
  }
}
```
I had to remove all usages of signals because of this issue. What is interesting - I got this error not for all signals. Error is not clear at all.

### Please provide the exception or error you saw

```true
Updating a signal during template or host binding execution is not allowed
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/core": "16.1.6",
node v18.12.1
```

**Comment by JeanMeche** [comment]
Hi, can you provide a repro, the basic usage of a setter to a signal does not trigger this mentionned error.

**Comment by roma2341** [comment]
In any case, signals are not as simple and cool as they are written about and depend on the life cycle of the components, although this is not mentioned anywhere.

**Comment by roma2341** [comment]
only things I'm using are **signals,** **computed**, **effects** and it looks like:
myComponent{
mySignal =...
computed=...
constructor(){effect(..)}
}

**Comment by pkozlowski-opensource** [comment]
@roma2341 we really need a runnable reproduction scenario in https://stackblitz.com/ - otherwise it is not actionable for us.

**Comment by ionut-gheorghe** [comment]
Same issue, changed a Subject to a WritableSignal and the error is thrown

![image](https://github.com/angular/angular/assets/54311614/3199e675-96c8-4011-b503-af540c5b06c2)

latestValue is the signal

![image](https://github.com/angular/angular/assets/54311614/026f906e-cfc6-40b3-8cec-779a03e6779e)

**Comment by roma2341** [comment]
Maybe it incorrectly handles null values.. because it writes than null != null

**Comment by pkozlowski-opensource** [comment]
I was spending a bit more time today looking into potential root-causes for this issue and couldn't pin-point anything obvious that could trigger the mentioned error. Here are my attempts: https://stackblitz.com/edit/stackblitz-starters-z31gfj?file=src%2Fmain.ts

The only thing that comes to my mind is the version of Angular being used - @ionut-gheorghe @roma2341 - could you please test your application with the latest Angular (v16.2.6) and see if this error still happens?

If so, please open another issue with a reproduce scenario or at least the full stack trace - it is really next to impossible to diagnose the situation without additional info.

**Comment by roma2341** [comment]
I personally don't use NGRX
