### ISSUE TITLE
Confusion on Deprecation docs page regarding in which Angular version things are removed

### ISSUE THREAD

**Issue by karptonite** [angular/angular#51729]
### Describe the problem that you experienced

The [Deprecation page](https://angular.io/guide/deprecations) of the Angular docs is sometimes unclear about if and when deprecated features etc are/will be actually removed.

It seems to be clear and consistent when it indicates when something was deprecated, but as for removal, it only tells you when something "may be removed", which is often a previous version of Angular. This is especially a problem for features which are not, in fact, removed.

The example that brought me here was the `deployUrl` option, in the [Deprecated CLI APIs and Options](https://angular.io/guide/deprecations#deprecated-cli-apis-and-options) section, which says it "may be removed in v15." Obviously, this did not happen in v15, nor did it happen in v16, nor does it seem that it is scheduled for v17, as far as I can tell.

I'd like it to be clear on this page whether deprecated features have actually been removed, and when. If they have not been removed, I would like to know when they may be removed. If the original estimate of when something might be removed has passed, I would like it to be updated to the latest estimate, or if there is no estimate, it should indicated that there are no plans to remove it.

### Enter the URL of the topic with the problem

https://angular.io/guide/deprecations

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
