### ISSUE TITLE
Init Setter execution order depends on order in class

### ISSUE THREAD

**Issue by muhamedkarajic** [angular/angular#51732]
### Description

If I may I like to raise a interesting suggestion based on an error I had recently. Sometimes you have the case that you have a few setters which depend on each other.

However the logic of the setter may cause that the other setter has a different logic based on the order which the properties are provided.

What I would like is that the setter dont dependon the order of the HTML but rather that that dependeny belongs to the component based on the order of the setters you write in the component.

That would protect developers who use your component from misusing it.

### Proposed solution

```html
<my-button 
      [type]="'link'"
      [link]="'/work'"
/>
```
and

```html
<my-button 
      [link]="'/work'"
      [type]="'link'"
/>
```

are executed the same.

### Alternatives considered

Maybe for backwards compatibility there could be a flag to enable this feature.

**Comment by JoostK** [comment]
This is how it was handled before Ivy, but Ivy's locality principles meant that this was changed.

FWIW, inputs that depend on each other should be dealt with in `ngOnChanges`, as otherwise you'll potentially miss updates when only one of the binding expressions changes. Hence, even if input assignment were to follow input declaration order you'd still not want to handle dependent updates only in the last setter.

**Comment by JeanMeche** [comment]
@alxhub gave a thorough explanation here : https://github.com/angular/angular/issues/40007#issuecomment-742707510

**Comment by muhamedkarajic** [comment]
> ...inputs that depend on each other should be dealt with in ngOnChanges...
I'm sorry but I think this is a misunderstanding I'm not looking for a workaround I'm proposing a feature request cause for me this volitiles encapsulation.  

Based on how the developer provides the inputs the functionality of my component will be different.

All workarounds I'm aware of are half baked solutions and I think this is something most developers don't know about and don't understand.

The resposibility which order of setters to execute belong to the component/class which defines them not the HTML.

**Comment by muhamedkarajic** [comment]
> @alxhub gave a thorough explanation on the current behavior here : [#40007 (comment)](https://github.com/angular/angular/issues/40007#issuecomment-742707510)

I'm sorry but for me its not acceptable that you force developers to relay on NgChanges because of the previously already explained points.

NgChanges is terrible for multiple of reasons and I really think its clear why I'm opening this feature request. If the Angular comunity simply dosen't want to implement that feature thats ok but then please just state it that way.

How is ngChanges solving for me anything when I use observables. Again really the HTML should not have the ability to define how to execute the order of setters I think this is a fundamental flaw.

**Comment by atscott** [comment]
This is working as intended and the relevant duplicate discussions have been linked above.
