### ISSUE TITLE
Unwanted dependency created by Angular SSR compiler

### ISSUE THREAD

**Issue by PRR24** [angular/angular#51734]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

Angular SSR compiler creates unwanted lazy chunk for xhr2.

Looking back on changelog, I guess it is connected to https://github.com/angular/angular/pull/50095

Please add a way not to be dependant on additional files either by
a) being able to disable lazy-loading of the xhr2 or
b) lazy-load the xhr2 from the main (vendor) bundle instead of from separate file.

Reasoning: keep simple, robust and reliable self-contained server for SSR.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 16.2.4
Node 18.17.1
Ubuntu 22.04
```

**Comment by alan-agius4** [comment]
@PRR24, I am not understanding why having an extra file is a problem and how not having an extra file will make SSR more simple, robust and self contained. 

SSR bundle was never meant to be a single self contained file, in fact this we always strongly recommend that lazy-loading. Chunk splitting is also more aggressive when using the esbuild based application builder which is currently experimental.

**Comment by PRR24** [comment]
Lazy loading is often a perfect approach on the client side.
But on server side, I see little benefit of it:
* Server is a long-lasting process, so its startup time is mostly irrelevant.
* As all the modules need to fit into memory anyways, why not load the code immediately and have everything ready when needed.

On the other hand, having single-file fully contained server has several benefits:
* If server is launched from network share, there is no impact, if the share should become temporarily unavailable.
* Cross-version conflicts (software from one version loads a chunk from other version) are not possible.
* Because of the above, updating such server is very easy -- just overwrite the file and restart server(s).

Of course, the same can be achieved by using different means, but in case of single file, you don't have to.

**Comment by alan-agius4** [comment]
Cde splitting is still important on the server. Though in this case the extra chunk is to avoid loading XHR code being parsed and evaluated when the platform does support it.

- Startup time is still very valuable especially considering the shift towards serverless and pay by use options were the server is spawned up only when needed as the requests comes in.
- Some Cloud provides also have size limits on how big each server file is especially when using Edge Workers. Thus as the application grows code splitting is a paramount.

With regards to the benefits you mentioned, mask other problems like instability of the network, deployments were the old files are not purged or server is not restarted after deployment.

Ultimately, if you want a single server file, it's trivial enough to do using a 3rd party bundle such as esbuild or rollup.
