### ISSUE TITLE
provideClientHydration does not wait for a waterfall of requests for caching

### ISSUE THREAD

**Issue by intellix** [angular/angular#51741]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

So the way that our application works, we kind of have a waterfall of requests due to needing to visit multiple sources for some information:
- A) go to CMS to get list of campaigns for guest users
- B) go to API to fetch information about those campaigns
- C) go back to CMS to fetch the content for the bonuses associated with those campaigns (interpolation purposes etc)

So you end up with requests like so:
```
A.....
       B.....
              C......... (fully ready)
```

Obviously we have caching within our CDN so it's not TOO slow, but when delivering a response from Universal SSR you kind of get this: appReady: false..... true....... false....... true.

We've been using TransferState to cache things like so:
```ts
return cmsCache.has(CACHE_KEY) ? cmsCache.get(CACHE_KEY) : cmsService.fetchSomething(...);
```

We sent that data to the browser and re-hydrated like so:
```ts
export const CACHE_STATE_KEY = makeStateKey<any>('api-cache.state');
export const apiCache = new Map<ApiCacheKey | string, any>();

...

// SSR hydration and dehydration of the cache
if (transferState.hasKey(CACHE_STATE_KEY)) {
  const state = transferState.get(CACHE_STATE_KEY, {});
  for (const key of Object.keys(state)) {
    apiCache.set(key, state[key]);
  }
} else {
  transferState.onSerialize(CACHE_STATE_KEY, () => Object.fromEntries(apiCache.entries()));
  apiCache.clear();
}
```

Now since Angular 16 there's experimental DOM Hydration and automatic HTTP Caching I thought great, I can delete most of my custom code and just use that.

After testing it, it mostly looked good but I noticed that there are a few API requests being made in both server and client. If I add logging to those, I can see them being made in both places but they never get added to TransferState. After some digging I found the culprits:

https://github.com/angular/angular/blob/main/packages/common/http/src/transfer_cache.ts#L170C1-L172C14

https://github.com/angular/universal/blob/main/modules/common/src/transfer_http.ts#L82-L89

For caching and transferState to be used, the application needs to do everything before the first ready state and can't be: unready/ready/unready/ready (as more requests/pending tasks are discovered).

Is there any reaason for it to work like this? It can't be correct because Universal still doesn't return the response until all of that is 100% settled anyway, so shouldn't the caching/transferstate also work the same way?

In my opinion, either:
 - The logic for when universal should stop what it's doing and deliver the response, should be the same as when cache and TransferState stop recording
 - Cache and TransferState shouldn't stop recording until Universal is fully ready and delivers the response

I'm assuming there's something I'm missing here for why it works the way it does.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.1
Node: 16.14.0
Package Manager: yarn 1.22.17
OS: darwin arm64

Angular: 16.2.3
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.1
@angular-devkit/build-angular   16.2.1
@angular-devkit/core            16.2.1
@angular-devkit/schematics      16.2.1
@angular/cdk                    16.2.2
@angular/cli                    16.2.1
@angular/flex-layout            15.0.0-beta.42
@angular/material               16.2.2
@nguniversal/builders           16.2.0
@nguniversal/express-engine     16.2.0
@schematics/angular             16.2.1
rxjs                            7.8.1
typescript                      5.0.4
webpack                         5.88.2
zone.js                         0.13.2
```

### Anything else?

As it stands, the only way for me proceed is to either:
- Copy/Paste all logic and provide it myself using the private APIs
- Hack my application to force all 3x requests (A, B, C) to be in a single observable and wait for it, instead of letting universal discover when it's ready based on what appears in the DOM and what is newly discovered.

**Comment by alan-agius4** [comment]
Hi @intellix,

I am actually surprised that in this case the rendered view is correct as rendering also happens as soon as the application is stable for the first time. See: 
https://github.com/angular/angular/blob/59387ee476dff1a893a01fe5cbee3c95b93c0cdb/packages/platform-server/src/utils.ts#L68-L74


Would you be able to patch `node_modules/@angular/core/fesm2022/core.mjs` with the change in https://github.com/angular/angular/pull/51754/files and see if this mitigates the problem?

**NB**: if you are have build cache enabled make sure to disable or clean it. See https://angular.io/cli/cache for more information.

**Comment by alan-agius4** [comment]
@intellix, did you have time to check the above please?

**Comment by ggarg2** [comment]
Hi @alan-agius4 

I have also observed this case in my application. Let me share one video. I am using hydration but one API is hitting on both client and server.

One hint is: My component is dynamically loading using *ngComponentOutlet and my dynamic component is making a rest api call twice at both places (Server and Client).

Please also have a look at the video. I am still seeing flickering issue after using hydration. Not sure what is the issue.

https://github.com/angular/angular/assets/6575592/4b871c59-f34b-49aa-8f16-edf992e4aed8

I am also attaching the screenshot of server response. In the response I am able to fetch whole HTML document from the server itself.

![image](https://github.com/angular/angular/assets/6575592/db82ca87-e8c5-4f80-a3a0-85ac55102992)

Thanks,

**Comment by alan-agius4** [comment]
@ggarg2, have you try the above mentioned patch? If the problem persists after the patch is applied please provide a minimal reproduction that we can investigate.

**Comment by ggarg2** [comment]
Hi @alan-agius4,

I have not tried the patch. I will try.

But Alan, Why there is a blank screen when the whole HTML document is coming from the server? 

I will also try to create the small application to reproduce the issue.

**Comment by JeanMeche** [comment]
> the main issue that I had was because my ApolloLink was different between server and browser. The server one was a straight up GET call with graphql, but in the browser I was using APQ (createPersistedLink from Apollo Angular). That means in the server it made the normal call but in the browser it was trying to send just the hash of the query, so the cache keys didn't match.

This would be related to #50117 then, the HTTP Cache Transfer isn't configurable ATM.

**Comment by JeanMeche** [comment]
Are those call made by with the `HttpClient` ?

**Comment by alan-agius4** [comment]
@intellix, is the request a `GET`, the HTTP Cache transfer only caches `GET` and `HEAD` requests.

**Comment by ggarg2** [comment]
> @intellix, is the request a `GET`?, the HTTP Cache transfer only caches `GET` and `HEAD` requests.

@alan-agius4 In my case, Some of the API's are POST that's why it is not caching.

**Comment by alan-agius4** [comment]
In that case let’s continue tracking this in https://github.com/angular/angular/issues/50117

**Comment by ahmadalsadder** [comment]
i think there is a problem when you have multiple module inside the application , consider you have two application A, B where A is the Main one (contains the App.Module)
and have http request , this will fully render on server side , but B.Module will always keep making the request twice -on server and on client - , i have downloaded multiple examples but all of them are working the same , also i have tried to provide the provideClientHydration() in every module and it still the same issue
