### ISSUE TITLE
Angular 16 Email validation error using pattern 

### ISSUE THREAD

**Issue by anoop-mobi** [angular/angular#51753]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

public repo: https://github.com/anoop-mobi/template-drivan-email-pattern

Email Validation using the pattern is throwing error on console 

i have Installed fresh angular 16 to check it. in the given public repo you can see the code 
**Error**
<img width="955" alt="image" src="https://github.com/angular/angular/assets/28626409/5cf42487-74fb-41a1-88f2-8fb4038b15de">

component.ts
<img width="438" alt="image" src="https://github.com/angular/angular/assets/28626409/1c0a4bfb-fdec-4c67-9dfd-1f77272ff8ee">

component.html
<img width="542" alt="image" src="https://github.com/angular/angular/assets/28626409/b6328816-3cfc-40f0-96b6-3ba9538aa735">

### Please provide a link to a minimal reproduction of the bug

Pattern attribute value ^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$ is not a valid regular expression

### Please provide the exception or error you saw

```true
Pattern attribute value ^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$ is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$/v: Invalid character in character class
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.1
Node: 18.17.1
Package Manager: npm 9.6.7
OS: win32 x64

Angular: 16.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.1
@angular-devkit/build-angular   16.2.1
@angular-devkit/core            16.2.1
@angular-devkit/schematics      16.2.1
@angular/cli                    16.2.1
@schematics/angular             16.2.1
rxjs                            7.8.1
typescript                      4.9.5
zone.js                         0.13.3
```

### Anything else?

I saw that in angular 16 and 15 not sure about prev

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).

**Comment by anoop-mobi** [comment]
> 

Thankyou for you valuable Response. But same regex works fine with reactive form. but not with pattern

**Comment by anoop-mobi** [comment]
> Hello, this issue is not related to angular, your regex throws in standard HTML.
> 
> You should ask your question on stackoverflow if you need some help.
> 
> Edit: BTW it's related to the [switch to the v flag for input patterns](https://github.com/whatwg/html/pull/7908).

Thankyou
this worked for me

pattern="[a-z0-9._%+\-]+@[a-z0-9.\-]+\.[a-z]{2,}$"
