### ISSUE TITLE
Unexported classes as host directives is an error in Angular Language Service

### ISSUE THREAD

**Issue by Nvveen** [angular/angular#51758]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I was messing around with using host directives to abstract some behavior, where I used inheritance on external library directives that aren't marked as standalone, and not exporting them. Using those as host directives works for the Angular compiler, but recently (?) the Angular Language Service marks this as an error.
I would rather not export them because their only use is to mark as standalone, preserve their behavior and use them as host directives.
The provided reproduction does not give a warning like my editor does, but it gives the general impression.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ttxx81?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
MyDirective must be a standalone directive to be used as a host directive
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.1.4
Node: 16.20.2
Package Manager: npm 8.19.4
OS: linux x64

Angular: 16.1.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.4
@angular-devkit/build-angular   16.1.4
@angular-devkit/core            16.1.4
@angular-devkit/schematics      16.1.4
@schematics/angular             16.1.4
rxjs                            7.8.1
typescript                      5.1.6
```

**Comment by JeanMeche** [comment]
Hi, 

There is already an open issue about this : #49874
