### ISSUE TITLE
angular2 $routeChangeStart , $routeChangeSuccess ,$routeChangeError

### ISSUE THREAD

**Issue by mashaly100200** [angular/angular#5175]
i was trying to get equivalent of these angular1 events $routeChangeStart , $routeChangeSuccess ,$routeChangeError

- if i use OnActivate, OnDeactivate  events , it need to add it to every component  :(

- also i tried to implement my own RouterOutlet but i can't access previous instruction on activate , deactivate events, also i couldn't know how to handle route Change Error

- also router.subscribe gave me the name only , but i want to get the current and next instruction objects to change some properties 
 
my target is:
1- show loading indicator when start change page , and hide it when finish change page.
2- make  transition animation rtl or ltr for current and next instruction

**Comment by brandonroberts** [comment]
@mashaly100200 the router exposes a navigating property that you can use to check when routing starts and finishes. There isn't currently a way that produces some type of indication of a route change error.

**Comment by mashaly100200** [comment]
for any one face this problem , you can make your own RouterOutlet directive which inherit from RouterOutlet

**Comment by vicb** [comment]
related to the old router
