### ISSUE TITLE
Img src relative to component

### ISSUE THREAD

**Issue by ziaukhan** [angular/angular#5176]
It would be nice if we could bundle images with components. Each component will be in a separate directory with an images subdirectory. Right now I have to give the full path and if I move the component directory it breaks the path. Is there a way to give the path relative to the component.ts file?  
Note: The same applies to styleUrls

**Comment by choeller** [comment]
I think this is the issue you're looking for: https://github.com/angular/angular/issues/2383

**Comment by mashaly100200** [comment]
i'm facing  the same problem

**Comment by pkozlowski-opensource** [comment]
Same as https://github.com/angular/angular/issues/6637
