### ISSUE TITLE
Bug when set property in FormGroup

### ISSUE THREAD

**Issue by midogoss** [angular/angular#51778]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

this code in my component:

```ts
console.log("professNew Old: ", this.formClient.controls['professNew'].value)
this.formClient.controls['professNew'].setValue("Administration System")
console.log("professNew New: ", this.formClient.controls['professNew'].value)
```
The output of the above code is:
professNew Old:  Professor
main.js:18553
professNew New:  null

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.9
Node: 18.12.1
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 15.2.9
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router
```

**Comment by akib1997** [comment]
Please, share the full form or online link?

**Comment by midogoss** [comment]
```
 this.formClient = this.formBuilder.group({
      civility: [this.clientInput.civility, Validators.required],
      adressProf: [this.clientInput.adressProf],
      profession: [this.clientInput.profession],
      StatutProf: [this.clientInput.StatutProf],
      newStatutProf: [this.clientInput.StatutProf],
      professNew: [this.clientInput.profession, Validators.required]
    });
```
And I try this code :

      ```
      console.log("newStatutProf Old: ", this.formClient.controls['newStatutProf'].value)
            this.formClient.controls['newStatutProf'].setValue("My New Profess Status")
            console.log("newStatutProf New: ", this.formClient.controls['newStatutProf'].value)
            console.log("professNew Old: ", this.formClient.controls['professNew'].value)
            this.formClient.controls['professNew'].setValue("my new profess")
            console.log("professNew New: ", this.formClient.controls['professNew'].value)
```

The output of the above code is:
```
newStatutProf Old:  My Old Status
newStatutProf New:  My New Profess Status
professNew Old:  My Old Profess
professNew New:  null
```

it was work whith Angular 13 but after the upgrade to 15 I see this bug

**Comment by Gennad-r** [comment]
@midogoss  pls try get value with another way:
`this.formClient.get('controlName').value`

**Comment by midogoss** [comment]
I was try it some result and I try setControl also some result

**Comment by pkozlowski-opensource** [comment]
@midogoss please share a minimal reproduction scenario using  https://stackblitz.com/ - otherwise this issue is not actionable and will be closed.

**Comment by midogoss** [comment]
its a part of big project, it was working well with the version 13 of Angular but after the upgrade to 15 the formGroup not working well, really I dont know why it not working I guess something wrong in this version of Angular 15

**Comment by BojanKogoj** [comment]
This is Angular 16 example, but seems like it's working fine for me: https://stackblitz.com/edit/stackblitz-starters-o2zfni?file=src%2Fmain.ts

**Comment by alxhub** [comment]
Closing as this is reported working with v16. Feel free to reopen with a reproduction if this isn't the case!
