### ISSUE TITLE
Add imports for standalone directives.

### ISSUE THREAD

**Issue by roma2341** [angular/angular#51773]
### Description

I need to display a modal window containing components from my directive. However, I cannot import modules with these components directly into my directive because it does not have "imports". I'm using this directive within the hostDirectives section of certain components. I initially believed that directives were template-less components, but I now understand that the key distinction is that standalone components can have imports, whereas standalone directives cannot.

### Proposed solution

To add imports to standalone directives.

### Alternatives considered

I attempted to create a module for directives, but I found that I could only use standalone directives as hostDirectives.

**Comment by roma2341** [comment]
For example, I want to show the material modal from the directive:
`let dialogRef = dialog.open(UserProfileComponent, {
  height: '400px',
  width: '600px',
});`
Can I do it or do directives not allow me to do this?

**Comment by JeanMeche** [comment]
It should be working, what have you tried ?

**Comment by roma2341** [comment]
For example, we have:
MyModal.module.ts
MyModal.component.ts
StandaloneModalCaller.directive.ts
StandaloneModalCaller.component.ts

standaloneModalCaller directive wan to call MyModal. But how can it do it if it doesn't know anything about MyModal.module.ts ?

**Comment by roma2341** [comment]
So i have to add MyModal.module.ts as an import to StandaloneModalCaller.component.ts and other components that have my directive in hostDirectives?

**Comment by JeanMeche** [comment]
Please provide a [stackblitz](https://stackblitz.com/) repro to help us understand how exactly you want to do this.

**Comment by roma2341** [comment]
For example this:
https://stackblitz.com/edit/angular-ksg5kh?file=src%2Fapp%2Fapp.component.ts

![image](https://github.com/angular/angular/assets/7004017/a2cbb4ed-51d0-4abd-b994-68abb268e135)
MyDirective can't inject MatDialog, forcing me to add MatDialogModule to MyComponent(standalone) imports

**Comment by JeanMeche** [comment]
This is a providers issue, you'll need to add the module to the imports of your AppModule.

**Comment by roma2341** [comment]
Ok sorry, fixed
https://stackblitz.com/edit/angular-nx3kfb?file=src%2Fapp%2Fmy-component%2Fmy-modal%2Fmy-modal.ts
