### ISSUE TITLE
Angular 15 can't be build with es2022 and static members

### ISSUE THREAD

**Issue by v1nger125** [angular/angular#51770]
### Which @angular/* package(s) are the source of the bug?

compiler, core

### Is this a regression?

Yes

### Description

Hi angular,

I see 2 main issues related to this problem
https://github.com/angular/angular/issues/48764
which is referenced to
https://github.com/microsoft/TypeScript/issues/52004

Typescript fix is ready, but it is available only in

version 5.1.0+

while angular 15 have engines

"typescript": ">=4.8.2 <5.0"

main build target is replaced according to browserslist so probably it is not a big problem, but test build isn't(maybe some other builds neither), also i expect main build will be failed if i will configure browserslist for ES2022

could you clarify are we expecting fix for that, both issues your and typescript marked as closed, but in general the problem is not solved.

### Please provide a link to a minimal reproduction of the bug

see https://github.com/angular/angular/issues/48764

### Please provide the exception or error you saw

```true
see https://github.com/angular/angular/issues/48764
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
see https://github.com/angular/angular/issues/48764
```

### Anything else?

i can replace target for test build to ES2020 and all will be ok, but the warning still will appear, is it expected?

TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022" and "false" respectively by the Angular CLI. To control ECMA version and features use the Browerslist configuration. For more information, see https://angular.io/guide/build#configuring-browser-compatibility
    NOTE: You can set the "target" to "ES2022" in the project's tsconfig to remove this warning.

**Comment by JoostK** [comment]
TypeScipt 5.1 support has been added in Angular 16. This will not be backported to Angular 15, so you'd have to change your browserslist configuration as mentioned in the warning to force outputting ES2020, or update to Angular 16.

Since this is no longer an issue with Angular 16 I am going to close this.
