### ISSUE TITLE
Angular should support View Transition API

### ISSUE THREAD

**Issue by muhamedkarajic** [angular/angular#51788]
### Description

I would like the Angular team to consider using the transitions view API.

https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API

### Proposed solution

Make it integrated with the current animations.

### Alternatives considered

Maybe a custom flag to enable it instead of the current animations.

**Comment by otodockal** [comment]
https://github.com/angular/angular/issues/49401
