### ISSUE TITLE
Component Input Binding gets param as undefined

### ISSUE THREAD

**Issue by pvsplunter** [angular/angular#51800]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No (initially I accidentally set this to yes)

### Description

**Behavior**
Component Input Binding will bind params from the parent segments to the child component initially, but will bind to undefined after navigating.

**How to reproduce**
1. Create a new standalone project using `ng new reproduction --standalone` (I'm currently using CLI version 16.2.2)
2. In app.config.ts change line 7 to `providers: [provideRouter(routes, withComponentInputBinding())]` (or at least add withComponentInputBinding() to provideRouter)
3. add the folder `src/app/components` with the following two files:
parent.component.ts:
```ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-parent',
  standalone: true,
  imports: [CommonModule, RouterOutlet],
  template: `<p>p: {{p}}</p>
    <router-outlet></router-outlet>`,
  styles: []
})
export default class ParentComponent {
  @Input() p!: string;
}
```
child.component.ts:
```ts
import { Component, Input, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';

@Component({
  selector: 'app-child',
  standalone: true,
  imports: [CommonModule],
  template: `
    <p>p: {{p}}<br/>c: {{c}}</p>
    <button (click)="changeC()">Update C only</button><button (click)="changeP()">Update P only</button><button (click)="changePC()">Update P and C</button>`,
  styles: []
})
export default class ChildComponent {
  @Input() p!: string;
  @Input() c!: string;

  router = inject(Router);

  changeC() {
    this.router.navigate([this.p, Math.random()]);
  }

  changeP() {
    this.router.navigate([Math.random(), this.c]);
  }

  changePC() {
    this.router.navigate([Math.random(), Math.random()]);
  }
}
```
4. replace the content of app.route.ts with (redirectTo is added for convenience, not required to reproduce the issue):
```ts
import { Routes } from '@angular/router';

export const routes: Routes = [
    {
        path: ':p',
        loadComponent: () => import('./components/parent.component'),
        children: [
            {
                path: ':c',
                loadComponent: () => import('./components/child.component')
            }
        ]
    },
    {
        path: '',
        redirectTo: 'initial/value',
        pathMatch: 'full'
    }
];
```
5. run `ng serve --open`

Notice when you click any of the buttons to navigate, ChildComponent gets undefined as a value for `p`, even though it initially got the correct value from the route. Hitting F5 will also cause ChildComponent to get the correct value again.

**work-around**
If you are sure that the child component is only rendered when the params are provided, you can rewrite it to this to work around this issue:
```
/// imports and decorator.
export default class ChildComponent {
    private _p: string = '';
    @Input() 
    get p(): string {return this._p; }
    set p(p: string) {
        if(p !== undefined) {
            this._p = p; // avoid setting undefined, keeping the initial value (this is the work around)
        }
    }
    
    // etc...
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.2
Package Manager: npm 9.8.1
Node: v18.16.1
Node Version Manager: nvm 1.1.10
OS: Windows 11
Angular: 16.2.0 (only the default packages are required to reproduce)
```

**Comment by JeanMeche** [comment]
Hi, looks like you're missing `paramsInheritanceStrategy : 'always'` in the routes options !

**Comment by pvsplunter** [comment]
This indeed fixes the issue! Thanks!

It feels a little bit embarrassing, since this setting isn't new, but I didn't figure out that I needed it with the new component input binding feature as well.

**Comment by JeanMeche** [comment]
We've added that note only 2 month ago ! 😉

**Comment by pvsplunter** [comment]
> We've added that note only 2 month ago ! 😉

Thanks for sharing 😄 Then it is actually likely that I started using it, before this was documented 😅
