### ISSUE TITLE
Angular change detection was triggered by window addEventListeners

### ISSUE THREAD

**Issue by sunilbaba** [angular/angular#51803]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

Every event listeners that was there under a page trigger change detection cycle in angular application. If a application page is nested deep the amount of change detection triggered were so many. We are not able to combine multiple change detection triggered by event listeners to single change detection with in a single animation frame. 

Reproducible steps:

 Add angular devtool extension in chrome browser. Within any angular application you can looks for change detection profiles in angular devtools

**Comment by JoostK** [comment]
You are looking for https://angular.io/api/core/BootstrapOptions#ngZoneEventCoalescing

**Comment by sunilbaba** [comment]
@JoostK,
1) Do we want to trigger change detection for every event listeners in the application ?
2) if a textarea is having three event listeners like blur, focus,onChange - we are triggering three change detection cycle in the application. Can't we have single cycle in this scenario ?
3) for every ngstyle, ngclass updates in the application there is a change detection cycle which was triggered by event listeners - visibilityChange

**Comment by JeanMeche** [comment]
1. Yes, this is part of the automatic CD strategy has by default 
2. You can coalesce these with [eventCoalescing](https://angular.io/api/core/NgZoneOptions)  if the callbacks are run in the same macro tasks 
3.

**Comment by sunilbaba** [comment]
@JeanMeche 
 Thanks for the reply. 

My question are as follows
1) Though we set change detection strategy as onpush (or) we add eventCoalescing / zoneCoalescing options in to the application. We are not able to control the CD extra cycles triggered by event listeners. 
2) Because of this extra cycle this is always a continuous repaints happens on the heavy application. Is there any better way to control this changes which were doing extra rendering of application ?
3) Before chrome browser v115 we don't see this much of extra cycle. Starting from v116 of chrome we are seeing lot of CD triggered by source : eventListeners . Is there any changes specifically on chrome browser ?

**Comment by JeanMeche** [comment]
1. You could go for unpatched `addEventListener`, those wouldn't trigger any CD as they are run outside the angular zone. RxAngular has something handy for that : https://www.rx-angular.io/docs/template/api/unpatch-directive 
2. See above
3. Where do you see that ? Is it in the angular devtools profiler ? Is it linked to a 'message' event ?

**Comment by sunilbaba** [comment]
Hi @JeanMeche ,

Thanks for the suggestions. I will take a look at it. 

For point 3: Yes I see those CD cycles under angular devtools profiles tab.
