### ISSUE TITLE
How would I write a router-link for a route like this '/users/:id/messages'

### ISSUE THREAD

**Issue by zorthgo** [angular/angular#5181]
On all of the examples that I've seen so far for the new component router, the parameter is always at the end of the route. Like this:

`@RouteConfig([
    {path: '/email/:id', component: email, as: 'email'},
])`

Which you would need a router-link like this to access it:

`<a [router-link] = "['./email', {id:1234}">Emails</a>`

My question is, how would I write my router-link if my parameter were in the middle of my route. With a format like this:

`@RouteConfig([
    {path: '/user/:id/messages', component: messages, as: 'messages'},
])`

When I manually type '/user/1234/messages' into my address bar I can successfully get to the page. But I can't seem to figure out the router-link format that will do the same thing. I do not wish to use a child route. Is this possible?

Thanks! :smile:

I am using Alpha 45

**Comment by brandonroberts** [comment]
I don't know what alpha you are using, but the format is the same.

```js
<a [router-link] = "['./messages', {id:1234}">Messages</a>
```

**Comment by zorthgo** [comment]
Hi Brandon, thanks for the reply! 

If I am not mistaken, the router-link that you proposed would work in the case where "messages" is a child route of "user". So the router parser would first check "user" than continue to "messages" and fill in the parameter with 1234. But I am trying to get the route working without using a child route. Messages is it's own page, with it's own route. Not a child of users. There's must be a way to construct the router-link in a way that I can have multiple parameters sprinkled within the route without using a child route.  :smile:

**Comment by behzadeshan** [comment]
We are using the standard href syntax and it works in our SPA app. So try this:
<a href="#/messages/1234/messages">Messages</a>
What's advantage of using [router-link]?

**Comment by e-oz** [comment]
@behzadeshan without [router-link] page will be reloaded.

**Comment by behzadeshan** [comment]
@e-oz  no it's not reloading even it's cashes server rendered views too.

**Comment by brandonroberts** [comment]
@zorthgo Sorry about the bad explanation earlier. What I was trying to say is that you can have a main route that has the same path as your parent/child route, but is more specific. In this case, you don't have to nest the route in order to generate the correct router link.

Here is a plunk demonstrating what I think you are trying to accomplish: 

http://plnkr.co/edit/y7iPNjFDkt2bWNCBQpg9?p=preview

**Comment by zorthgo** [comment]
@brandonroberts  Thanks for the plunker!... This was exactly was I was looking for. Your example has made so many things click about this new component router. Thanks A LOT for the help! ;0)

**Comment by zorthgo** [comment]
@behzadeshan Thanks for the reply! If I understand router-link correctly (now a little bit better than before), the main advantage that I see of using router-link, is that if you refactor your link, you would only need to make changes to one place, your RouteConfig. If you were to use a regular href, and you had to make a change to the structure of your link, you would have to modify all places where you've used that href. In my opinion, it's a nice step towards a more decoupled application.  :smiley:

**Comment by behzadeshan** [comment]
@zorthgo good point, thanks.
