### ISSUE TITLE
computed() is not being recomputed when the dependencies are conditional

### ISSUE THREAD

**Issue by e-oz** [angular/angular#51812]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Starting from 17.0.0.next-3:

Reproduction:
https://stackblitz.com/edit/stackblitz-starters-wejrta?devToolsHeight=33&file=src%2Fmain.ts

Please note my comment on line 43.

In short, this version works wrong:

```ts
isProcessing = computed(
    () =>
      this.isMutating() || this.isReading() || this.refreshingItems().length > 0
  );
```

and this works fine:
```ts
isProcessing = computed(() => {
    const isMutating = this.isMutating();
    const isReading = this.isReading();
    const isRefreshing = this.refreshingItems().length > 0;
    return isMutating || isReading || isRefreshing;
  });
```

I suppose it's caused by the fact that `this.isReading()` dependency is being removed dynamically from the graph (in the first function).

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-wejrta?devToolsHeight=33&file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Everything: 17.0.0-next.4 (please see package.json in repro)
```

**Comment by JeanMeche** [comment]
That's a pure JS issue. If `this.isMutating()  is `true`, `this.isReading() || this.refreshingItems().length > 0` won't be evaluated and the graph won't know it's dependencies.

**Comment by e-oz** [comment]
@JeanMeche 
`this.isMutating()` has value "false" in the last iteration.

**Comment by e-oz** [comment]
isMutating() becomes true once, after that other dependencies are removed, but they should be re-attached when isMutating() brings a new value ("false").

**Comment by JeanMeche** [comment]
Isn't the issue that it's being tracked again but after the value has been changed ?

**Comment by pkozlowski-opensource** [comment]
@e-oz you've marked this issue as a regression - do you happen to know what is the last "good" version where it worked for you?

**Comment by e-oz** [comment]
@pkozlowski-opensource 17.0.0-next.0:
https://stackblitz.com/edit/stackblitz-starters-3vvwb2?devToolsHeight=33&file=src%2Fmain.ts,package.json
I'll update the issue with the correct version.

**Comment by e-oz** [comment]
Amazing, thanks a lot @pkozlowski-opensource !
