### ISSUE TITLE
Default values for `templateUrl` and `styleUrls` fields in component.

### ISSUE THREAD

**Issue by tandu** [angular/angular#5183]
I'm using [angular2-seed](https://github.com/mgechev/angular2-seed) and throughout my project each component has `html` and `css` file with the same name as component `ts` file.

```
├── about
│   ├── about.html
│   ├── about.ts
│   └── about.css
```

where component `ts` file is:

``` typeScript
import {Component} from 'angular2/angular2';

@Component({
  selector: 'about',
  templateUrl: './components/about/about.html',
  styleUrls: ['./components/about/about/about.css']
})
export class About {}
```

Can you make `templateUrl` and `styleUrls` to be optional and if either of that field is absent the default value is generated for template/css, but only in case the file with that name exists. I.e.

``` typeScript
let file = "'" + <component file name> + '.html'";
if(hasFile(file)) templateUrl = file; // templateUrl: ['component file name.html']
```

``` typeScript
let file = "'" + <component file name> + '.html'";
if(hasFile(file)) styleUrls = file; // styleUrls: ['component file name.css']
```

Having these fields be optional will save a lot of dummy typings and make components code look clearer.

What do you think?

**Comment by Gillespie59** [comment]
:-1:  And how you would implement the `hasFile` method by an extra request, that will probably fail ?

**Comment by tandu** [comment]
It should check for the file existence during compilation stage. There is no requests at that time. The example related to `hasFile` is abstract just to explain the idea.

**Comment by manekinekko** [comment]
@tandu beware of blackmagic! In your situation, please use snippets code. Every editor has this feature now. It's easy to use and doesn't need any extra effort from the core framework.

**Comment by tandu** [comment]
I think I better had to not put this code lines of explanations at the bottom of my post at all. I don't know internals of angular 2, so I can't quickly produce PR to explain my idea. Do you think that using default values for those fields is black magic? I think angular2 has a lot of things that hide complexity the way that can be named black magic and everyone are happy that they can write simpler code.

**Comment by manekinekko** [comment]
sorry @tandu didn't want to upset you bro ^^
_If this could make you relax: I didn't read your code at the bottom of your post my response was about the general proposal_

Angular cannot guess which type of template you're using. Angular 2 is not meant for browser only, you could also write native and universal apps, which don't always use html templates. So defaulting this to "html" based templates could make things unpredictable.

**Comment by zamamohammed** [comment]
@manekinekko since @tandu is asking about compile time can't we have a configuration file which can have the specifics about the system the project will use and then compile it properly to what was specified in the configuration file.

**Comment by manekinekko** [comment]
@zamamohammed could you give an example explaining your idea?

**Comment by tandu** [comment]
I understand it so that angular should read from config file something like `isWebApplication` or `useDefaultHtmlUrl`, `useDefaultStyleUrl` to be able to correctly handle defaults for only web development.

**Comment by choeller** [comment]
@tandu I like the idea of stripping boilerplate from the annotation. 

When they introduced the "new component router" in Angular 1.x the also showed a mechanism, where you would only pass the component name, and the template url was automatically calculated. In this case the offered the possiblilty to register an own template-location strategy to overwrite the default behaviour. IMO something like this could fit here too. 

To make the idea clear, this is a snippet I just found about this new A1 Router - never used it, so I'm not sure if it is actually working:

```
$componentMapperProvider.setTemplateMapping(function (name) {
    // name == component name
    return name + '.html';
  });
```

There is also a similar issue, that would need to be solved first I guess - so currently a component has no idea about its location in the filesystem. Here is the other issue: https://github.com/angular/angular/issues/2383

**Comment by splincode** [comment]
@tandu Is the issue relevant?

**Comment by tandu** [comment]
I don't know, it was long time ago

**Comment by splincode** [comment]
@tandu maybe you close it?

**Comment by tandu** [comment]
Ok


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Max Ivanov <notifications@github.com> Date: 7/26/18  20:23  (GMT+03:00) To: angular/angular <angular@noreply.github.com> Cc: Maksim <maksick@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [angular/angular] Default values for `templateUrl` and `styleUrls` fields in component. (#5183) 
@tandu maybe you close it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/angular/angular","title":"angular/angular","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/angular/angular"}},"updates":{"snippets":[{"icon":"PERSON","message":"@splincode in #5183: @tandu maybe you close it?"}],"action":{"name":"View Issue","url":"https://github.com/angular/angular/issues/5183#issuecomment-408171486"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/angular/angular/issues/5183#issuecomment-408171486",
"url": "https://github.com/angular/angular/issues/5183#issuecomment-408171486",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [angular/angular] Default values for `templateUrl` and `styleUrls` fields in component. (#5183)",
"sections": [
{
"text": "",
"activityTitle": "**Max Ivanov**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@splincode",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"angular/angular\",\n\"issueId\": 5183,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"angular/angular\",\n\"issueId\": 5183\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/angular/angular/issues/5183#issuecomment-408171486"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 108561427\n}"
}
],
"themeColor": "26292E"
}
]
