### ISSUE TITLE
Embrace "controlled components" idea from react

### ISSUE THREAD

**Issue by alexpods** [angular/angular#5184]
Look [here in the react docs](https://facebook.github.io/react/docs/forms.html#controlled-components) to better understand what "controlled components" are. Actually, I've thought that angular2 already works exactly the same. But it appears to be wrong.

Let's assume that I have some component with an `<input>` element. I want to prevent users from entering white spaces into it. So I've wrote the next lines of code (see [this plunk](http://plnkr.co/edit/4jWWfLm5ediamioOOS21?p=preview)):

``` js
@Component({
  selector: 'my-app',
  template: `
    <input [value]="content" (input)="onInput($event.target.value)" />
  `
})
export class App {
  content: string = '';

  onInput(newContent) {
    this.content = newContent
      .replace(/\s+/g, '') // removes not right after entering
      .replace(/l/g, 'm')  // replaces right after entering
  }
}
```

I've expected that when user enter some whitespace character, it'll be immediately removed. But it doesn't work. When I enter white spaces into the `<input>` element they'll be removed only if I enter non-white space character after them.

[Here is a plunk with react.js](http://plnkr.co/edit/KOyCAWtJzgSh1xXsRTgO?p=preview) implementation so you can compare the behaviors.

Another example. What'll happen if I bind input value to some string literal. For example (see [this plunk](http://plnkr.co/edit/Ran0G7HR4xfG4OKpI76P?p=preview)):

``` js
@Component({
  selector: 'my-app',
  template: `<input [value]=" 'sometext' " />`
})
export class App {}
```

I think, in this case user shouldn't have any ability to enter anything into the `<input>`. It's already bound to `sometext` and must always remain so.

[Here is a plunk with react.js](http://plnkr.co/edit/h07itnb19dJl61oaZjFc?p=preview) implementation for this example so you can compare the behaviors.

@vsavkin @tbosch

**Comment by thelgevold** [comment]
I am assuming removing the whitespace "cancels" the change, so that the change detection doesn't see it as a change from the original value.

Not sure what the cleanest solution is, but maybe there could be a concept of ng-model options baked into the [(ng-model)] syntactic sugar? 

```<input [(ng-model)]="sometext" />```

Otherwise I am thinking we would have to manually use keydown events and returning false in order to cancel the undesired input.

**Comment by alexpods** [comment]
@thelgevold 
React does a simple thing: when some `<input>` element is being mounted it creates handler which will be called on every `<input>` change (see it [here](https://github.com/facebook/react/blob/v0.14.2/src/renderers/dom/client/wrappers/ReactDOMInput.js#L76)). This handler will update `value` of the `<input>` element if there is some value bound to it (see it [here](https://github.com/facebook/react/blob/v0.14.2/src/renderers/dom/client/wrappers/ReactDOMInput.js#L123), [here](https://github.com/facebook/react/blob/v0.14.2/src/renderers/dom/client/wrappers/ReactDOMInput.js#L27) and [here](https://github.com/facebook/react/blob/v0.14.2/src/renderers/dom/client/wrappers/ReactDOMInput.js#L106)). As a result we have  **single point of truth** - this "bound value" (the value of the rendered element will always reflect the "bound value"). Playing with this value we have full control over the UI.

I'd like that angular2 have something like that, though I don't know how good it can be fit into angular2 change detection. `ng-model-pattern` is maybe a good solution, but I don't think it should be in a core.

**Comment by gionkunz** [comment]
Well, I'd consider it absolutely normal that if you change a primitive value to the exact same value again, change detection will not trigger. 

```javascript
'11   1      1  1'.replace(/\s+/g, '') === '  111    1 1   '.replace(/\s+/g, ''); // true
```

There's no way angular can detect a change and therefore the property binding does not trigger. It would also have a negative performance impact if there'd be a mechanism that would allow this to trigger.

You could create a small `StringWrapper` class, so you can work with object references in change detection:

```javascript
import {Component} from 'angular2/angular2';

class StringWrapper {
  constructor(value) {
    this._value = value;
  }
  
  toString() {
    return this._value;
  }
}

@Component({
  selector: 'app'
  template: `
    <input [value]="wrapper" (input)="onInput($event.target.value)" />
  `
})
export class App {
  wrapper = new StringWrapper('');

  onInput(newContent) {
    this.wrapper = new StringWrapper(
      newContent
        .replace(/\s+/g, '')
        .replace(/l/g, 'm')
    );
  }
}
```

**Comment by alexpods** [comment]
@gionkunz Even easier, we already have string wrapper in javascript - it's `String`:
```js
const a = new String('asdfas'); // or just: const a = Object('asdf');
typeof a === 'object';
a instanceof String === true
```

But this issue is not about that I have any problem (I haven't). I just think that "controlled components" is a really cool idea and I'd like to see it in angular2.

**Comment by alexpods** [comment]
@gionkunz Simple implementation of "controlled" input (see [this plunk](http://plnkr.co/edit/jqahndPg1tvkP1ZGoexr?p=preview)):

```ts
@Directive({
  selector: 'input',
  host: { '(input)': 'null' }
})
class InputDirective implements DoCheck {
  @Input() value: string;

  constructor(
    public renderer: Renderer, 
    public elementRef: ElementRef
  ) {}

  doCheck() {
    this.renderer.setElementProperty(this.elementRef, 'value', this.value);
  }
}
```
This can be optimized by not running change detection for entire application on every user input. So, I think, it's possible to achieve quite insignificant impact on performance.

**Comment by kemsky** [comment]
Change detection has a lot of overhead compared to direct property manipulation leading to be less responsive, i bet this example will never work.

A more general case is *input masking* and *input filtering*, *input(display) formatting* and *input parsing (i.e. date)*.  All this features are not `ngModel` friendly.

**Comment by splincode** [comment]
@alexpods Is the issue relevant?

**Comment by alexpods** [comment]
@splincode No, I think
