### ISSUE TITLE
RouterOutlet does not clear DOM immediately

### ISSUE THREAD

**Issue by panda-byte** [angular/angular#51849]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

Basically same issue as #17499 from 2017, which was closed due to a lack of a minimal reproduction of the bug.

When navigating using the router, the router outlet content in the DOM is not immediately cleared. Even though the previously displayed component's `ngOnDestroy` was already called, the DOM is still intact in the `ngAfterViewInit` hook of the newly displayed component, which was very surprising to me. However, after a short delay (1 ms `setTimeout`) the DOM is cleared. Is this the expected behavior? It affects the computed bounding box of `ViewChild` elements evaluated in `ngAfterViewInit`. This caused some issues for me, because I wanted to use a canvas element for a library and dynamically change its size based on its initial position upon initialization (make it fill the remaining screen space taking layout elements outside of the router outlet into account).

The minimal reproduction uses two components, `TestComponent` ('/test') and `HomeComponent` ('/home'), where the user can switch between the two by using a button which calls the router. When loading '/test' initially, the router outlet is empty (as seen by the output of the document body's `innerHTML`), and the computed bounding box of the `ViewChild` button element is as expected. But when loading `HomeComponent` first and then switching to `TestComponent`, the router outlet still contains the content of `HomeComponent` when `ngAfterViewInit` of `TestComponent` is called. The output of the innerHTML during `ngAfterViewInit` and after a 1 ms delay as well as the top coordinate of the button's bounding rect is displayed on the page.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-k7fvz1?file=src%2Fapp%2Ftest.component.ts

### Please provide the exception or error you saw

```true
As seen by the output on the page, the DOM is not cleared from previous content when entering the `AfterViewInit` lifecycle hook of the newly loaded component, and the bounding boxes of `ViewChild` elements are affected.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.0
Node: 18.16.0
Package Manager: npm 9.5.1
OS: darwin x64

Angular: 16.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0
@angular/flex-layout            15.0.0-beta.42
@schematics/angular             14.2.11
rxjs                            7.5.7
typescript                      4.9.5
```

**Comment by atscott** [comment]
Yes, this is "expected" behavior and not limited to the `RouterOutlet` but due to when animations (even no-op) are flushed. The root cause is here: https://github.com/angular/angular/issues/19742

**Comment by panda-byte** [comment]
Thanks a lot for clearing this up! I didn't expect the `BrowserAnimationsModule` would change rendering so fundamentally even if no animation is actually used. Is this behavior documented anywhere? I couldn't find anything about this, which made debugging really hard.

**Comment by atscott** [comment]
@panda-byte I don't believe it's really documented anywhere. I think it's considered more of an implementation detail that rarely has any impact that requires any specific callout.
