### ISSUE TITLE
Angular should provide support for both ESM and CommonJS

### ISSUE THREAD

**Issue by rkeithhill-keysight** [angular/angular#51853]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Maybe I'm interpreting this wrong but somewhere around Angular 13, it appears that Angular dropped support for CommonJS according to this [issue comment](https://github.com/angular/angular/issues/44096#issuecomment-962436958).

Looking at issues in the Electron repo, it seems that Electron does not support ESM (even to this day) according to this Electron [issue](https://github.com/electron/electron/issues/21457). It only supports CommonJS. 

So if we have an Electron-based application that uses Angular, it appears we are stuck on an old version of Angular. Our app currently uses ng 10, so I know that works.  But our attempts to upgrade to 13 have failed.

### Proposed solution

Provide both mjs and cjs assets in the npm packages i.e. support both ESM and CommonJS.

### Alternatives considered

I'd love to know of a way to make Angular 13 (even 15) work in Electron, but I haven't found it yet.

**Comment by JoostK** [comment]
Shipping CJS adds considerable overhead to the package size, as well as adding processing time to creating those packages.

It is possible to convert ESM into CJS in build infrastructure, so this can be made to work if desired. The Electron issue you linked has been marked as resolved btw, see https://github.com/electron/electron/issues/21457#issuecomment-1700096956, so there is movement on their side to adopt ESM.
