### ISSUE TITLE
NG0912 error after migrating to Angular 16 for library with secondary entrypoint

### ISSUE THREAD

**Issue by wwjhu** [angular/angular#51850]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

If a library has a secondary entrypoint (for example a `testing` entry) and references components, directives or services from the main entrypoint, then including a module from the secondary entrypoint in the tests will cause the NG0912 warning for every component exported from the main entrypoint.

```shell
~/W/g/test-ng0912 main > ng test lib-ng0912 --reporters=dots --browsers=ChromeHeadless                     32s 18:04:58
✔ Browser application bundle generation complete.
21 09 2023 18:05:08.217:WARN [karma]: No captured browser, open http://localhost:9876/
21 09 2023 18:05:08.226:INFO [karma-server]: Karma v6.4.2 server started at http://localhost:9876/
21 09 2023 18:05:08.226:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
21 09 2023 18:05:08.228:INFO [launcher]: Starting browser ChromeHeadless
21 09 2023 18:05:08.539:INFO [Chrome Headless 117.0.5938.88 (Mac OS 10.15.7)]: Connected on socket LPuROnq0muxFDX_bAAAB with id 65017970
WARN: 'NG0912: Component ID generation collision detected. Components 'FeatureComponent' and 'FeatureComponent' with selector 'lib-feature' generated the same component ID. To fix this, you can change the selector of one of those components or add an extra host attribute to force a different ID. Find more at https://angular.io/errors/NG0912'
.
Chrome Headless 117.0.5938.88 (Mac OS 10.15.7): Executed 1 of 1 SUCCESS (0.023 secs / 0.021 secs)
```

Confirmation that this is a bug in the core, or any advice to overcome this problem is welcome.

### Please provide a link to a minimal reproduction of the bug

https://github.com/wwjhu/test-ng0912

### Please provide the exception or error you saw

```true
WARN: 'NG0912: Component ID generation collision detected. Components 'FeatureComponent' and 'FeatureComponent' with selector 'lib-feature' generated the same component ID. To fix this, you can change the selector of one of those components or add an extra host attribute to force a different ID. Find more at https://angular.io/errors/NG0912'
```
```


### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.3
Node: 18.15.0
Package Manager: npm 9.8.1
OS: darwin arm64

Angular: 16.2.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.3
@angular-devkit/build-angular   16.2.3
@angular-devkit/core            16.2.3
@angular-devkit/schematics      16.2.3
@angular/cli                    16.2.3
@schematics/angular             16.2.3
ng-packagr                      16.2.3
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
```

**Comment by JeanMeche** [comment]
This likely means that your symbols get duplicated in the process (you end up with 2 FeatureComponent classes). This would make it an import issue, do related to angular. 

Can you make a full of your issue to confirm that ?

**Comment by wwjhu** [comment]
> Can you make a full of your issue to confirm that ?

A full what 😄?

**Comment by JeanMeche** [comment]
A full Reproduction 😊👍

**Comment by wwjhu** [comment]
See https://github.com/wwjhu/test-ng0912

Or do you refer to something else?

**Comment by wwjhu** [comment]
Changing the import in the spec file in the sample from

```
import { FeatureModule } from './feature.module';
```

to 

```
import { FeatureModule } from 'lib-ng0912';
```

makes the warning go away. But importing all code under test from the built version of the library does not feel like the right approach to me.

**Comment by alan-agius4** [comment]
What is happening here is that you have 2 instances of the same component which is caused because some of the features in tests are being consumed from the build library and some are consumed directly.  This causes references to modules, components and services not to be the same and thus having multiple references for the same thing.

There are a 2 solutions for this;
1. Use always the build library in tests. IE: use absolute imports as you mentioned above.
```ts
import { FeatureModule } from 'lib-ng0912';
```
Or

2. For tests, use TypeScript path mappings to point to library source-code instead of the built version.
`tsconfig.spec.json`
```json
{
    "extends": "../../tsconfig.json",
    "compilerOptions": {
        "outDir": "../../out-tsc/spec",
        "types": ["jasmine"],
        "paths": {
          "lib-ng0912": ["src/public-api.ts"],
          "lib-ng0912/testing": ["testing/src/public_api.ts"]
      },
    },
    "include": ["**/*.spec.ts", "**/*.d.ts"]
}

```

**Comment by wwjhu** [comment]
I tested both approaches. 

The first solution, using the built library in all tests, can be made to work. It is, however, an extremely tedious task for a larger codebase. Missing one import will result in all components to be reported with the NG0912 warning without any clue which import in what source file is the culprit. Additionally I ran into injection errors caused by 'local' components not exported through the library's API and ones coming from the built library. Adding those API resolved at least some of the problems but is obviously not what you want.

The second approach is far less work to implement and has no side-effects (so far). Please note that to make it work, you need to add an `index.ts` next to the `public-api.ts` / `public_api.ts` and the paths need to be from the root.

`index.ts`:

```ts
export * from './public-api';
```

`tsconfig.spec.json`: 

```json
{
    "extends": "../../tsconfig.json",
    "compilerOptions": {
        "outDir": "../../out-tsc/spec",
        "types": ["jasmine"],
        "paths": {
          "lib-ng0912": ["projects/lib-ng0912/src"],
          "lib-ng0912/testing": ["projects/lib-ng0912/testing/src"]
      },
    },
    "include": ["**/*.spec.ts", "**/*.d.ts"]
}
```
