### ISSUE TITLE
@Input('class.name') binding doesn't work

### ISSUE THREAD

**Issue by SebastianPodgajny** [angular/angular#51852]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

Angular compiler doesn't generate input binding instruction for `<my-cmp [class.xyz]="true"/>`

Compilation result
```
ɵɵclassProp('xyz', true);
```
expected result
```
ɵɵclassProp('xyz', true);
ɵɵproperty('class.xyz', true);
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-5nar3p?file=src%2Fmain.ts

**Comment by JoostK** [comment]
I wonder about the practical use-case for this; I'm inclined to report an error on the `@Input` for using a name that conflicts with class binding syntax, _not_ generate additional runtime instructions _for each and every_ class binding in an application.

**Comment by SebastianPodgajny** [comment]
Component can easily react to class changes from parent, instead of
```html
<my-cmp [class.active]="variable" [isActive]="variable"/>
```
you can have
```html
<my-cmp [class.active]="variable">
```
```ts
@Input('class.active') public isActive;
```
which can be used to show/hide elements etc, also this can help sync classes if component uses renderer and you want to force some class from parent that is also managed internally by add/removeClass

Other than that this is a valid syntax if `[abc.xyz]="true"` works as expected IMO `[class.xyz]="true"` and `[attr.xyz]="true"` should also work.
I don't understand the part about generating runtime instruction for each and every class binding in application, this should behave like any other input if component doesn't have matching `@Input('class.name')` instruction will not be generated compiler shouldn't assume `[class.xyz]="expr"` is only class prop binding but also check for inputs with matching name

**Comment by JoostK** [comment]
> I don't understand the part about generating runtime instruction for each and every class binding in application, this should behave like any other input if component/directive doesn't have matching @Input('class.name') instruction will not be generated

This, unfortunately, is not true today. Angular's directive/input binding is deferred until runtime, so every input binding always generates an instruction regardless of whether there is a corresponding directive input.

**Comment by SebastianPodgajny** [comment]
So maybe good solution it would be to check in `checkStylingProperty` instruction if input is shadowed by class binding same as with `checkStylingMap`
https://github.com/angular/angular/blob/0a4f18a419ba68a7c8a2d22da85a7f88bd217840/packages/core/src/render3/instructions/styling.ts#L209
https://github.com/angular/angular/blob/0a4f18a419ba68a7c8a2d22da85a7f88bd217840/packages/core/src/render3/instructions/styling.ts#L233-L235
