### ISSUE TITLE
Coverage page is not up to date

### ISSUE THREAD

**Issue by sschoorens** [angular/angular#51859]
### Describe the problem that you experienced

https://github.com/angular/angular/blob/main/aio/content/guide/testing-code-coverage.md

Hi that page still use `--code-coverage` in the command and `codeCoverage` in the configuration.
Currently it should be `--coverage`

### Enter the URL of the topic with the problem

https://angular.io/guide/testing-code-coverage

### Describe what you were looking for in the documentation

The coverage argument

### Describe the actions that led you to experience the problem

`ng test --code-coverage`

### Describe what you want to experience that would fix the problem

Update the documentation

### If this problem caused an exception or error, please paste it here

```true
`Error: Unknown argument: code-coverage`
```

**Comment by alan-agius4** [comment]
`--code-coverage` is the correct flag for the default builder.  See: https://angular.io/cli/test
Are you using a 3rd party builder?

**Comment by sschoorens** [comment]
Yes sorry I've done a `ng test --help` and thinking it was a mistake in the documentation but i'm using the jest builder
`builder": "@angular-builders/jest:run",`  I'm closing that issue thanks for the answer.
