### ISSUE TITLE
Structural directives not imported in standalone components don't break compilation

### ISSUE THREAD

**Issue by aleesaan** [angular/angular#51861]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When I don't import a standalone component before using it, the compilation will break.  
However, I can have non-imported structural directives in the template and the compilation will not break.   

I noticed the following, which you can see in the reproduction repo I linked:
- if the directive has no input, it just doesn’t render its host element;
- if it has an input, it doesn’t render the host element and throws an error in the console;

I randomly noticed this during the migration to standalone, but it's quite an annoying bug as it can easily be missed, since the compilation doesn't break.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-structural-directive-repro?file=src%2Fapp.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)
```
Angular CLI: 16.2.2
Node: 18.17.1
Package Manager: npm 9.6.7
OS: darwin arm64
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.2
@angular-devkit/build-angular   16.2.2
@angular-devkit/core            16.2.2
@angular-devkit/schematics      16.2.2
@angular/cli                    16.2.2
@schematics/angular             16.2.2
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
```

**Comment by pkozlowski-opensource** [comment]
This is fundamentally the same issue as #46351

**Comment by aleesaan** [comment]
Isn't it kind of different though? Structural directives starting with `*` could not be an unknown attribute, right?  
We already get an error in the console when that directive has an input - couldn't we instead get the error during compilation?

**Comment by JeanMeche** [comment]
I'd say It more related to #37322, @pkozlowski-opensource do you agree ?

**Comment by aleesaan** [comment]
Yes that's exactly it @JeanMeche, I hadn't seen that issue before :)

**Comment by JeanMeche** [comment]
I'll close this one as a dup then ! We can continue the discussion over there !

**Comment by pkozlowski-opensource** [comment]
> I'd say It more related to https://github.com/angular/angular/issues/37322, @pkozlowski-opensource do you agree ?

Yes and no :-) 

Structural directives are just syntax sugar that resolves to directives being matched by attributes. The underlying issue is that our compiler can't detect missus of such directives since we don't know that those are directives.

We might be able to improve situation in #37322 but the fundamental problem is directive matching on attribute selectors.

**Comment by aleesaan** [comment]
Thanks for the input all! Hopefully we can fix it 🤞
