### ISSUE TITLE
Angular 16.2.4 breaks when activating Firestore with Angular/Fire (standalone app)

### ISSUE THREAD

**Issue by spock123** [angular/angular#51869]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

We are using the @angular/fire package to communicate with Firebase.

When upgrading from Angular 16.2.3 -> 16.2.4 we noticed an error that occurs as soon as Firestore is initialized.
The app is a standalone app. 

```
const firebaseProviders: EnvironmentProviders = importProvidersFrom([
    provideFirebaseApp(() => initializeApp(environment.firebase)),
    provideFirestore(() => getFirestore()), // THIS LINE NOW BREAKS!!
    provideAuth(() =>
        initializeAuth(getApp(), {
            persistence: [browserSessionPersistence, browserLocalPersistence],
            popupRedirectResolver: browserPopupRedirectResolver
        })
    )
]);
```

### Please provide a link to a minimal reproduction of the bug

Unfortunately our repo is private and part of larger monorepo so cannot give access but can maybe try if the fix is not obvious

### Please provide the exception or error you saw

```true
NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (core.mjs:731:15)
    at ɵɵinject (core.mjs:744:42)
    at Object.FirebaseAppModule_Factory [as useFactory] (angular-fire-app.js:57:42)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.0
Node: 18.15.0
Package Manager: pnpm 8.1.0
OS: darwin arm64

Angular: 16.2.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.3
@angular-devkit/build-angular   16.2.0
@angular-devkit/core            16.0.3
@angular-devkit/schematics      16.0.3
@angular/cli                    16.2.0
@angular/fire                   7.6.1
@schematics/angular             16.0.3
rxjs                            7.5.6
typescript                      5.0.4
zone.js                         0.13.0
```

### Anything else?

Update to Angular 16.2.4+ and Firestore gives the error when initializing.

**Comment by JoostK** [comment]
This indicates to me that you have multiple copies of `@angular/core` in your app bundle, each having their own, separate runtime state.

**Comment by spock123** [comment]
@JoostK Yes that was also what I read, nevertheless I tried every single version (16.2.1, etc etc) and it only broke from 16.2.4 and onwards.

But you might be right, as I use pnpm as package manager and there can be issues with that. For now I have locked onto using 16.2.3 and it works, I guess I'll leave it there for now, until next feature release (or V17).

Thanks for your quick reploy, cheers

**Comment by JoostK** [comment]
Could be due to various package version constraints that pnpm decides to duplicate packages to satisfy all ranges. You can probably get some more insights using `pnpm why @angular/core`.

**Comment by spock123** [comment]
thank you @JoostK , I don't wanna take more your time. Cheers, I'll close this issue as it sounds like it's a local issue in my end.
