### ISSUE TITLE
Promise returned from function causes endless loop when used in view with AsyncPipe

### ISSUE THREAD

**Issue by gionkunz** [angular/angular#5187]
Hi guys

I've noticed that if I'm returning a Promise from a function and use the function within my view using the `AsyncPipe`, I'll run into an endless loop.

```javascript
import {Component} from 'angular2/angular2';

@Component({
  selector: 'app'
  template: `
    <p>Promise Member Variable: {{asyncTest | async}}</p>
    <p>Promise from Member Function: {{asyncTestFn() | async}}</p>
  `
})
export class App {
  asyncTest = new Promise(resolve => resolve('Hey There!'));
  asyncTestFn() {
    // Uncomment to reproduce. Warning, browser will freeze!
    // return new Promise(resolve => resolve('Hey There!'));
  }
}
```

http://plnkr.co/edit/C1Zaw6i6SK3N5YgasLyD?p=info

**Comment by gionkunz** [comment]
Is angular doing the change diff on the Promise or on the value the promise is resolving to?

**Comment by gionkunz** [comment]
Here's an other use case with a function modifying some async data by using Promise chains. Of course there'll be a new promise every time the function is called, but I'd expect angular to be smart enough to handle this use case:

```javascript
import {Component} from 'angular2/angular2';

const data = [1, 2, 3, 5, 8, 13, 21];

function provideDataAsync() {
  return new Promise(resolve => resolve(data));
}

function minValue(min) {
  return value => value >= min;
}

@Component({
  selector: 'app'
  template: `
    <p>Sync Filtered: {{syncTest(5)}}</p>
    <p>Sync Filtered: {{asyncTest(5)}}</p>
  `
})
export class App {
  asyncData = provideDataAsync();
  
  syncTest(min) {
    return data.filter(minValue(min));
  }
  
  asyncTest(min) {
    // Uncomment to reproduce. Warning, will freeze browser
    // this.asyncData.then(values => values.filter(minValue(min)));
  }
}
```

http://plnkr.co/edit/nL70ofK5eIBVVRZFX5gs?p=info

**Comment by gionkunz** [comment]
I'm questioning if the async object should even be considered within change detection.

https://github.com/angular/angular/blob/b0009f03d510370d9782cf76197f95bb40d16c6a/modules/angular2/src/common/pipes/async_pipe.ts#L92-L95

Why should we consider the exchange of an async container as a change? Wouldn't it be sufficient enough to only consider something to be changed if we compare the references / primitives of resolved values?

**Comment by ericmartinezr** [comment]
@gionkunz did you see the example in the file you referenced? It's using Observables. In the latest master it has been refactored (https://github.com/angular/angular/issues/4588). I don't think it will work with Promises anymore. So you could give it another try but with the latest master.

**Comment by robwormald** [comment]
Promises and Observables should be supported by the async pipe. 

That said, I'm not totally clear on what the use case is in this specific example. This usage looks like a Bad Idea - every time the function runs, it's going to return a new instance of a promise, which is going to resubscribe in the async pipe, and then when it resolves, it's going to trigger change detection, which will call the function again, return a new instance of a promise, resubscribe, trigger change detection, etc.

Typically, change detection should not produce side effects - this code has side effects, as each time the cycle runs, you're going to get a new Promise. that's bad news bears. 

I extended your plunker with a few different ways of thinking about this: http://plnkr.co/edit/TOIjqHJrZAoJ2D1FAEz1?p=preview

If you could explain further what you're trying to do here, I'd be happy to have a further look.

**Comment by robwormald** [comment]
As far as "the change of the async container" - this goes back to the basic fact of Promises, that they will only *ever* resolve once, and thus doing a reference check is a safe and fast way of knowing that a new value will be arriving. You can't get a new value without a new Promise.

**Comment by gionkunz** [comment]
@robwormald you're totally right. Returning a new Promise every time the function is called is probably a very bad idea. However, I was somehow expecting that Angular would manage it by doing change detection only on the resolved value rather than the async container reference.

Thanks for the example! In my case I think I'll go with an observable which will generate new values.

Cheers
Gion

**Comment by robwormald** [comment]
Good stuff. One neat pattern with Observables (there are many ways to do this kind of thing) is here - http://plnkr.co/edit/dVMfcrB8yucSyf7SVt1x?p=preview

In effect - two streams, one of the current max value, one of the current dataset, run the combine fn whenever either changes.

**Comment by gionkunz** [comment]
Cool. Nice example! Will the `rx` Pipe land in master soon? Or will the current `async` Pipe support Rx Observables ?

**Comment by robwormald** [comment]
The Rx pipe there is just a workaround, next release has the async pipe
functional with Observables

**Comment by gionkunz** [comment]
Cool, keep up the great work! Cheers
