### ISSUE TITLE
Template binding does not recognize the 'inert' property.

### ISSUE THREAD

**Issue by examan** [angular/angular#51879]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

The 'inert' property under HTMLElement can be accessed correctly in TypeScript, but it cannot be used with template binding.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/i7jj8y?file=src%2Fapp%2Fapp.component.html

### Please provide the exception or error you saw

```true
error NG8002: Can't bind to 'inert' since it isn't a known property of 'a'.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.3
Node: 16.20.0
Package Manager: npm 9.4.2
OS: linux x64

Angular: 16.2.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.3
@angular-devkit/build-angular   16.2.3
@angular-devkit/core            16.2.3
@angular-devkit/schematics      16.2.3
@angular/cli                    16.2.3
@schematics/angular             16.2.3
rxjs                            7.8.1
typescript                      4.9.5
zone.js                         0.13.3
```

**Comment by mfarhani** [comment]
Try `[attr.inert]` instead `[inert]`:
`<a href="http://angular.io/" [attr.inert]="disabled">Disabled link</a>`
it will work.

**Comment by examan** [comment]
> Try `[attr.inert]` instead `[inert]`: `<a href="http://angular.io/" [attr.inert]="disabled">Disabled link</a>` it will work.

I know this works, but I think this is a workaround and should be fixed, thank you

**Comment by chsagar236** [comment]
in app.component.html 
use like this 
<div inert>
  <a src="http://angular.io/">Disabled link</a>
</div>

and in app.component.css  add css like this

[inert], [inert] * {
  opacity: 0.5;
  pointer-events: none;
  cursor: default;
  user-select: none;
}


![image](https://github.com/angular/angular/assets/46953211/040e022e-c590-4817-a7b3-4b1da30b795e)
