### ISSUE TITLE
multi:true token no injected in NgModule when boostraping a standalone component

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular#51888]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Suppose we have a token, that is provided multiple times with `multi:true` : 

```ts
const TOKEN = new InjectionToken<number[]>('test');

@Component({ selector: 'test', template: 'Tokens: {{tokens}}' })
export class TestComponent {
  constructor(@Inject(TOKEN) public tokens: number[]) {}
}

@NgModule({
  declarations: [TestComponent],
  exports: [TestComponent],
  providers: [{ provide: TOKEN, useValue: 'foo', multi: true }],
})
export class MyModule {}

@Component({
  selector: 'my-app',
  standalone: true,
  imports: [MyModule],
  template: `
    Expects foo & bar values but ....

    <test />
  `,
})
export class App {}

bootstrapApplication(App, {
  providers: [{ provide: TOKEN, useValue: 'bar', multi: true }],
});
```
In the case of a standalone app, the `TestComponent` will only display `foo`. 

But if we bootstrap an NgModule instead of the standalone component, 

```ts
@NgModule({
  declarations: [App],
  bootstrap: [App],
  imports:[MyModule, BrowserModule,],
  providers: [{ provide: TOKEN, useValue: 'bar', multi: true }],
})
export class AppModule {}

platformBrowserDynamic().bootstrapModule(AppModule)
```
the `TestComponent`  will display `foo, bar`. 

I understand this is likely related to #47460 but I'm kind of surprised that we have 2 different behaviors for something seemingly equivalent. 

Wdty ? 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-multi-provider-standalone?file=src%2Fmain.ts

**Comment by JoostK** [comment]
This is working as designed and as documented in https://angular.io/guide/standalone-components#standalone-injectors
