### ISSUE TITLE
DI instantiate dependencies from the wrong injector

### ISSUE THREAD

**Issue by vicb** [angular/angular#519]
It seems like the DI instantiate the dependencies using the injector where the binding has been resolved instead of the requesting injector.

If the dependency is only present in the requesting injector, it would fail with `Error: No provider for Engine! (Car -> Engine)`

```
      it('should resolve deps', function () {
        var parent = new Injector([Car])
        var child = parent.createChild([
          bind(Engine).toClass(TurboEngine)
        ]);

        var carFromChild = child.get(Car);

        expect(carFromChild.engine).toBeAnInstanceOf(TurboEngine);
      });
```

and it is not possible to override a dep in a child injector (expect fails, returns an `Engine`)

```
      it('should resolve deps', function () {
        var parent = new Injector([Car, Engine])
        var child = parent.createChild([
          bind(Engine).toClass(TurboEngine)
        ]);

        var carFromChild = child.get(Car);

        expect(carFromChild.engine).toBeAnInstanceOf(TurboEngine);
      });
```

**Comment by vsavkin** [comment]
This is a known issue. We talked about it with Misko and Vojta and did not come with a good solution (the one that is easy to understand and performs well).

**Comment by vicb** [comment]
Note: I need this fix for the TemplateLoader PR which makes the shadow DOM strategy global. The strategy is injected in the Compiler (both bindings are declared in the root bindings). This fix enables overriding the strategy at bootstrap time (in the application injector). Without the fix, the strategy would always be retrieved from the root injector and impossible to override.

**Comment by tbosch** [comment]
I am thinking about a merge operation for lists of bindings. Driven by the
config for benchpress to provide defaults. I think this might be easier
than using a child injector. Let's talk about this in person

**Comment by tbosch** [comment]
Actually more along the lines that a binding can provide default bindings
for the dependencies it uses

**Comment by rkirov** [comment]
@vicb it sounds like the natural thing for you would be if a child rebinds a dependency of A, that would invalidate the instance of A that lives in the parent. However consider this.
 
```
      it('should resolve deps', function () {
        var parent = new Injector([Car, Engine])
        var child = parent.createChild([
          bind(Engine).toClass(TurboEngine)
        ]);

        var carFromChild = child.get(Car);

        expect(carFromChild.engine).toBeAnInstanceOf(TurboEngine);
      });
```

Just trying to convince you that this is not a bug but rather a design decision among different options each with messy sematics.

**Comment by rkirov** [comment]
@tbosch We do guarantee that the last binding wins if you have a repeated binding in the same injector https://github.com/angular/angular/blob/master/modules/di/test/di/injector_spec.js#L152

**Comment by mhevery** [comment]
@vsavkin  will add the test case to show this is intentional behavior.

**Comment by mhevery** [comment]
Consider this rule:  Parent Injector can not have a reference to child Injector. 

We need to this to be able to reason about lazy loaded code and to unload unused child injectors. If the above rule is broken than the order of loading child injector will matter, and we want to explicitly not allow this. Creating a child injector should not in any way effect someone who only has a reference to the parent injector.

The above rule prevents what you are asking for. :-(

**Comment by vsavkin** [comment]
I've created a PR adding a test case showing the intentional behavior:
https://github.com/angular/angular/pull/546
