### ISSUE TITLE
NG8102 incorrectly raised when indexing a Record<string, string>

### ISSUE THREAD

**Issue by c-harding** [angular/angular#51906]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Given the following minimal reproduction, the error `NG8102: The left side of this nullish coalescing operation does not include 'null' or 'undefined' in its type, therefore the '??' operator can be safely removed.` is emitted.

```ts
@Component({
  selector: 'my-app',
  standalone: true,
  template: `
    {{object[key] ?? key}}
  `,
})
export class App {
  object: Record<string, string> = {};
  key = 'key';
}
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-b5cmok?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
NG8102: The left side of this nullish coalescing operation does not include 'null' or 'undefined' in its type, therefore the '??' operator can be safely removed.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
> ng "version"


     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.2.1
Node: 18.14.2
Package Manager: pnpm 7.33.3
OS: darwin x64

Angular: 16.2.3
... animations, common, compiler, compiler-cli, core, elements
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.8
@angular-devkit/build-angular   16.2.1
@angular-devkit/core            16.2.1
@angular-devkit/schematics      16.2.1
@angular/cdk                    16.2.2
@angular/cli                    16.2.1
@schematics/angular             16.2.1
rxjs                            7.5.7
typescript                      5.1.6
webpack                         5.86.0
zone.js                         0.13.1
```

### Anything else?

Reproduction in StackBlitz uses version 16.2.6

**Comment by c-harding** [comment]
https://github.com/angular/angular/issues/44859 is similar, but this refers to a Record rather than an Array.

**Comment by JoostK** [comment]
This is expected if TypeScript's `noUncheckedIndexedAccess` is not set. The diagnostic is purely driven by TypeScript's type information and without this flag, indexed accesses do not include `undefined`.

**Comment by c-harding** [comment]
@JoostK is it possible to suppress this warning?

**Comment by c-harding** [comment]
Solved: https://angular.io/extended-diagnostics/NG8107#what-if-i-cant-avoid-this
