### ISSUE TITLE
route_recognizer: bad alias message, "CamelCase"

### ISSUE THREAD

**Issue by wardbell** [angular/angular#5190]
Message in [route_recognizer](https://github.com/angular/angular/blob/master/modules/angular2/src/router/route_recognizer.ts#L43) should say "Route aliases should be TitleCase like ..."

**Comment by tyleranton** [comment]
I'll make a PR with this fix.

**Comment by evanplaice** [comment]
FYI, `Title Case` maintains spaces between words. The 'correct' term should be `PascalCase`.

[Source: Wikipedia - CamelCase](https://en.wikipedia.org/wiki/CamelCase)

**Comment by wardbell** [comment]
That is true. But in my wanderings, more people understand what I really mean when I say "TitleCase" than when I say the correct PascalCase.  

I'm leaving it as is for now ... and closing the comment. 

Thanks for the feedback though. Keep it coming.
