### ISSUE TITLE
Hydration "provideClientHydration()" does not provide feature as TransferHttpCacheModule ?? 

### ISSUE THREAD

**Issue by imvikasdeep** [angular/angular#51904]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

in some components i want to call the api on ngOnInit() while switching route, but the data is provided from http caching due to provideClientHydration().

is there any solution for this ??

**Comment by alan-agius4** [comment]
Hi, 

I am not fully understanding your question. 

Are you asking if you can disable or filter out requests from being cached in the HTTP cache?

**Comment by imvikasdeep** [comment]
yes i want to filter out requests from being cached in some components conditionally.

**Comment by alan-agius4** [comment]
That is currently not possible. Please see: https://github.com/angular/angular/issues/50117
