### ISSUE TITLE
router/path_location_strategy: doc should mention base element option

### ISSUE THREAD

**Issue by wardbell** [angular/angular#5191]
[Current documentation](https://github.com/angular/angular/blob/master/modules/angular2/src/router/path_location_strategy.ts#L15-L17) says that we must supply `APP_BASE_HREF`

But also OK if dev adds `<base>` to index.html, e.g., 
```
<head>
  <base href="/">
  ...
</head>
```

See also error message [here](https://github.com/angular/angular/blob/b0009f03d510370d9782cf76197f95bb40d16c6a/modules/angular2/src/router/location.ts#L90)

**Comment by btford** [comment]
We originally had this option, but it actually makes things more complicated to tie the app base to the base href.

The fix should be to update the error message here.

**Comment by wardbell** [comment]
Ah.  That will break Tour of Heroes.  I'll tell John.

**Comment by wardbell** [comment]
Is there a reason we can't default this to the base url (e.g., `http://example.com`)?  This is another of the paper cuts that piss people off. They'd understand why they have to do it if it isn't the base url. But it feels like it should work out-of-the-box.

**Comment by btford** [comment]
We probably could, but I'm weary of hiding intrinsic complexity from users.

@IgorMinar thoughts?

**Comment by wardbell** [comment]
I get that. But to have an instant failure on first use ... that seems harsh.  And what's wrong with the base url anyway? Isn't that a common default? What would you change it too? Why?

I'm all for teaching the options ... in due time. I'm also for having great defaults in the beginning so people have a chance to experience the joy of A2 ... and learn at a reasonable pace.

**Comment by vsavkin** [comment]
Fixed here 
https://github.com/angular/angular/pull/10082
