### ISSUE TITLE
Type safety isssue with Angular dependency injection

### ISSUE THREAD

**Issue by alcaidio** [angular/angular#51927]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I lose typing when I use Angular's dependency injection. I don't know why? Can someone explain and find a solution to use DI while having strict typing? I'm using a service to strictly type local storage, here's some context:

I use a class with a generic type.

```
@Injectable()
export class LocalStorageService<T> implements iStorageService<T> {
// ...

  constructor(@Inject(LOCAL_STORAGE_NAMESPACE) private namespace: string) {}


  set<K extends keyof T>(key: K, value: T[K]) {
    if (this.storage) {
      this.storage.setItem(
        this.namespace + key.toString(),
        JSON.stringify(value)
      );
    }
  }

// ...
}
```
and at consumer level :

  ```
providers: [
    {
      provide: LOCAL_STORAGE_NAMESPACE,
      useValue: 'dumbnamespace',
    },
    LocalStorageService<LocalStorageModel>,
  ],
```
I tried too :

 ```
 providers: [
    {
      provide: 'LocalStorageService',
      useFactory: () => new LocalStorageService<LocalStorageModel>('namespace'),
    },
  ],
```
with LocalStorageModel fir instance:

```
interface LocalStorageModel {
  [LocalStorageKey.Name]: string;
}
```
And in the component :

  `private testTypeChecking = inject(LocalStorageService).set(LocalStorageKey.City, 22);`
No error here when it should be :(

Doing it this way works (we have an error, number is not a string), but without using Angular's DI.

```
const testTypeChecking = () => {
  const localStorageService = new LocalStorageService<LocalStorageModel>('id');
  localStorageService.set(LocalStorageKey.Name, 22);
};
```
Does anyone have an explanation?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.6
Node: 16.15.0
Package Manager: npm 8.5.5
OS: darwin x64

Angular: 16.2.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.3
@angular-devkit/build-angular   16.2.3
@angular-devkit/core            16.2.3
@angular-devkit/schematics      16.0.6
@angular/cdk                    16.2.5
@angular/cli                    16.0.6
@nguniversal/builders           16.2.0
@nguniversal/express-engine     16.2.0
@schematics/angular             16.0.6
rxjs                            7.8.1
typescript                      5.0.4
```

### Anything else?

I don't think it's a bug, but here I think someone will have the answer.

**Comment by JeanMeche** [comment]
When you call `inject(LocalStorageService)` the generic isn't specified so this is expected. 

Since the generic can't be inferred you will have to specify it yourself : `inject(LocalStorageService< LocalStorageModel>)`

**Comment by alcaidio** [comment]
Thanks a lot! 
It doesn't work with inject, is that normal? In the constructor it's fine ;)

```
private localStorage = inject(LocalStorageService<LocalStorageModel>);
// VS
constructor(private localStorage: LocalStorageService<LocalStorageModel>) {}
```
