### ISSUE TITLE
RouterLink only working on Root App component

### ISSUE THREAD

**Issue by mfrancis107** [angular/angular#5192]
I can only seem to get RouterLink to work  on the root component. As of 2.0.0-alpha.45

With some debugging I find that the changes parameter is undefined when using RouterLink on sub components. It almost seems this issue is not directly related to RouterLink.

```javascript
  set routeParams(changes: any[]) {
    this._routeParams = changes;
    this._navigationInstruction = this._router.generate(this._routeParams);

    var navigationHref = stringifyInstruction(this._navigationInstruction);
    this.visibleHref = this._location.prepareExternalUrl(navigationHref);
  }
```

I tried setting up a plunkr. But am having difficulty getting the router to work with plunkr.

**Comment by yfain** [comment]
Works for me, but I use TypeScript. 

RootComponent:

`@Component({
    selector: 'basic-routing',
    template: `<a [router-link]="['/Home']">Home</a>
               <a [router-link]="['/ProductDetail', {id: 1234}, 'ProductDescription']">Product Details</a> 
               <router-outlet></router-outlet>`,
    directives: [ROUTER_DIRECTIVES]})
@RouteConfig([
    {path: '/',                component: HomeComponent,          as: 'Home'},
    {path: '/product/:id/...', component: ProductDetailComponent, as: 'ProductDetail'}]) 
class RootComponent{}`

ProductDetailComponent:

`@Component({
    selector: 'product',
    template: `<div class="product">
                 <h1>Product Detail for Product: {{productID}}</h1>
                 <router-outlet></router-outlet> 
                 <a [router-link]="['./SellerInfo', {id: 123}]">Seller Info</a> 
               </div>` ,
    styles: ['.product {background: cyan}'],
    directives: [ROUTER_DIRECTIVES]})
@RouteConfig([
    {path: '/', component: ProductDescriptionComponent, as: 'ProductDescription'  }, 
    {path: '/seller', component: SellerInfoComponent, as: 'SellerInfo'  }]) 
export class ProductDetailComponent {
    productID: string;
    constructor(params: RouteParams){
        this.productID = params.get('id');
    }
}`

**Comment by mfrancis107** [comment]
After building the latest Angular2 I'm not having any problems. I believe this can be closed.
