### ISSUE TITLE
Developer docs Bazel extension url is naviagting to deprecated version

### ISSUE THREAD

**Issue by MrJithil** [angular/angular#51924]
### Describe the problem that you experienced

The "Install Bazel" in developer document is navigating to a deprecated version of Bazel. The extension page asking a developer to migrate the extension.

### Enter the URL of the topic with the problem

https://github.com/angular/angular/blob/c7127b98b555449f99e24a81c828ab7b1c6c4a4e/docs/DEVELOPER.md#vs-code-1

### Describe what you were looking for in the documentation

Setting up the local setup of angular to contribute 

### Describe the actions that led you to experience the problem

Used the active release of new Bazel extension

### Describe what you want to experience that would fix the problem

Modify the documentation with an updated url. 

### Add a screenshot if that helps illustrate the problem

<img width="991" alt="Screenshot 2023-09-27 at 9 02 52 pm" src="https://github.com/angular/angular/assets/26359740/ade004de-fe37-43a5-aefc-838fb9cf5d86">

### Provide any additional information here in as much as detail as you can

```true
**New Extension Details

Name: Bazel
Id: BazelBuild.vscode-bazel
Description: Bazel BUILD integration
Version: 0.7.0
Publisher: The Bazel Team
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=BazelBuild.vscode-bazel
```

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular/pull/51925
