### ISSUE TITLE
It always creates a singleton service - Angular 14

### ISSUE THREAD

**Issue by danilobatistaqueiroz** [angular/angular#51930]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

When a service is applied using providers to any module, which is not imported by AppModule, it will be singleton.

I created the **list-courses.module** that inject the **courses.service**, but this module is imported only by **orders.module**, not by **AppModule**.  
If I inject the service in a constructor's component the singleton instance will be used.  (in the example: **create-courses.component**)

As Angular guide says:   
> Providing a singleton service.
> There are two ways to make a service a singleton in Angular:
> 
> Set the providedIn property of the @Injectable() to "root"
> Include the service in the AppModule or in a module that is only imported by the AppModule
 

![image](https://github.com/angular/angular/assets/32627919/6dc03683-ce35-47a7-a558-ca758633ec36)

![image](https://github.com/angular/angular/assets/32627919/13867f21-eed8-4cab-8531-81c2f2f4d2a8)

![image](https://github.com/angular/angular/assets/32627919/eee65634-2234-42d5-8802-081483d2a6fd)

![image](https://github.com/angular/angular/assets/32627919/356c0031-8fd6-45bd-9b12-16ed0a1bbd53)

![image](https://github.com/angular/angular/assets/32627919/d22391c0-283a-4b0c-beda-e4989f2f0a74)

### Please provide a link to a minimal reproduction of the bug

https://github.com/danilobatistaqueiroz/ng-singleton-service  

### Please provide the exception or error you saw

```true
The instance is singleton sharing the same data and the same instance.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.6
Node: 16.17.0
Package Manager: pnpm 8.7.5 
OS: linux x64

Angular: 14.2.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.1
@angular-devkit/build-angular   14.2.6
@angular-devkit/core            16.2.1
@angular-devkit/schematics      16.2.1
@angular/cli                    14.2.6
@schematics/angular             16.2.1
rxjs                            7.5.0
typescript                      4.7.2
```

**Comment by JeanMeche** [comment]
I think you are misunderstanding the meaning of singleton here : It means that accross the app, it's the same instance that will be injected. Which is what you are observing. 

It works as expected. 

If you want a difference instance, you'll have to add the service to the providers at the component level.

**Comment by JeanMeche** [comment]
I've already answered you on StackOverflow. It the same thing if it's a transitive import. The `OrdersModule` ends up being imported by the `AppModule`. If it we're for that provider, you'd have `NullInjectorError: No provider for` everywhere it's injected. 


The doc maybe isn't very clear about it.
