### ISSUE TITLE
Child route data is not inherited from parent unless 'runGuardsAndResolvers' returns true

### ISSUE THREAD

**Issue by Erbenos** [angular/angular#51934]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

While I was figuring out a way to trigger resolver only for certain route on route navigation (see https://github.com/angular/angular/issues/31843), I found this bug (see linked stackblitz), when even though Angular invokes the resolver as expected, the children won't get their @Input() bound to the new value until the resolver for the specific child runs.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-exaecl?file=src%2Fmain.ts

1) goto route "a/b"
2) click "Route B"'s "refresh route A resolver", which navigates to route "a/b" and custom RunGuardsAndResolvers strategy causes route's "A" resolver to run
3) observe that component of "a/b" doesn't obtain the new value, but component of "a" does.
4) click "Route B"'s "refresh route B resolver", which navigates to route "a/b" and custom RunGuardsAndResolvers strategy causes route's "B" resolver to run
5) observe that component of "a/b" obtains both new value for "resolver B" AND new value for "resolver A" (cause only now the value gets updated even though "resolver A" isn't run anew)

### Please provide the exception or error you saw

```true
There is no error.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 16.0.1

Not sure how I can run the ng version on stackblitz, can't provide more info.
```

**Comment by atscott** [comment]
Updated title to indicate that this is an issue with the route data only getting updated if `runGuardsAndResolvers` is `true`. That's the root cause and the input binding is just a result of that.

Simpler reproduction: https://stackblitz.com/edit/angular-pmzfx5?file=src%2Fmain.ts

**Comment by Erbenos** [comment]
Suppose this should be a relatively easy fix then? Can give it a shot if you give me some pointers.

**Comment by atscott** [comment]
> Suppose this should be a relatively easy fix then?

 😅 

>  Can give it a shot if you give me some pointers.

Data resolution / inheriting data from the parent happens here:
https://github.com/angular/angular/blob/main/packages/router/src/operators/resolve_data.ts

That, however, depends on an aggregation of guards/resolvers in a previous step:
https://github.com/angular/angular/blob/e1728a2a392aa7fa237a50561469f99eb201a24c/packages/router/src/utils/preactivation.ts#L102C11-L105

**Comment by Erbenos** [comment]
Think the preactivation.ts and its shouldRunGuardsAndResolvers seem fine (since the resolvers are being run correctly as is), rather, the data population is incorrect in the resolve_data.ts, since it doesn't propagate the data to any child routes, which it probably should.

The way I see it now, runResolve function will need to be changed so that it only computes the _resolvedData (the resolved data of just the route that owns the resolver) and resolveData function will need to be changed so that it does a second pass after calculating all _resolvedData so that it goes through all the routes which just got their _resolvedData recalculated and all their children down until it reaches leaves of and extends routes' data according to paramsInheritanceStrategy as it traverses down.

Still don't see where the activatedRoute.data gets invalidated though.
