### ISSUE TITLE
NgForm stops tracking the value of an eagerly rendered NgModel control if it has been "swapped" using ng-template via an equally named but lazy rendered one

### ISSUE THREAD

**Issue by Den-dp** [angular/angular#51940]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

Switching between eager and lazy-loaded (ng-template) material tabs both of which have equally named NgModel control, makes ngForm stop tracking the value/validity of the first control.

```html
<form #form="ngForm">

  <mat-tab-group>

    <mat-tab label="eager tab with lightweight editor">
      <input [(ngModel)]="model.foo" name="foo" />
    </mat-tab>

    <mat-tab label="lazy tab with heavy editor">
      <ng-template matTabContent>
        <!-- heavy lazy-loaded visualization for the same model -->
        <input [(ngModel)]="model.foo" name="foo" />
      </ng-template>
    </mat-tab>

  </mat-tab-group>
</form>

<pre>form.value: {{ form.value | json }}</pre>
```

More detailed steps in my stackblitz

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/ngform-issue-with-ngmodel?file=src%2Fapp.component.html

### Please provide the exception or error you saw

https://github.com/angular/angular/assets/1770529/a22a03a0-871f-415f-acf9-9bfff1ef1a09

### Please provide the environment you discovered this bug in (run `ng version`)

```true
I tried it with both angular 13 and 16.1.1
```

**Comment by JeanMeche** [comment]
This is basically the same as #51239, you currently can't the same name form multiple directives, lets continue tracking the issue over there.
