### ISSUE TITLE
Replace twitter logo with 'X' logo in the homepage of Angular

### ISSUE THREAD

**Issue by aialok** [angular/angular#51967]
### Describe the problem that you experienced

It is not a problem. Just little amendment in twiiter logo with X logo on the homepage of angular 

### Add a screenshot if that helps illustrate the problem

![twitter logo should change on homepage](https://github.com/angular/angular/assets/66772290/c933dce5-0b77-4b20-b2e1-42affeca3789)

**Comment by vaidyajayesh** [comment]
@aialok : I would like to contribute on this task if you are ok.

**Comment by aialok** [comment]
Sorry, I already working on this issue.

**Comment by srinathsree66** [comment]
#51716

**Comment by aialok** [comment]
twitter logo was got resolved in docs only but the issue is still on the angular homepage.

I am new to open source. I thought of contributing to it.

**Comment by aialok** [comment]
sorry,  when I created the issue twitter logo is not updated. 
Thank you !
