### ISSUE TITLE
Explain how angular2 is built/compiled

### ISSUE THREAD

**Issue by Ludo09** [angular/angular#5197]
Hi folks,

I tried to figure it by myself but I'm not quite sure to get it right: how angular2 is built from Typescript and bundled into JS.

I guess TS is transpiled into ES5/commonjs bundle. 
* But how/where do you explicitly indicate that this particular function or class must be available (exported) through the public API?
* How come that I can use import {Component, bootstrap} from 'angular2/angular2'? What does the path angular2/angular2 refer to and how Typescript can figure out where to look in my app.ts?

Thanks for your help!
Ludo

**Comment by pkozlowski-opensource** [comment]
@Ludo09 public API is re-exported from few entry point files, ex.: https://github.com/angular/angular/blob/master/modules/angular2/angular2.ts or https://github.com/angular/angular/blob/master/modules/angular2/http.ts

Bundles are built using the same entry points. Our bundling story is still work in progress so any information I could share right now will be probably outdated in a matter of days.

**Comment by Ludo09** [comment]
Ok thanks. But once ts files are transpiled into es5, which tool does the bundling afterwards? When I look at gulp config file it's not clear to me.

**Comment by pkozlowski-opensource** [comment]
As of today we are using https://github.com/systemjs/builder for bundling. But as I've said, our bundling story is work in progress so it might change in the (very) near future.

> When I look at gulp config file it's not clear to me.

There is so much movement in this repo and the bundling area that you need to be prepared to dive into the code if you need more detailed info at this point....
