### ISSUE TITLE
Router params cut at first '&'

### ISSUE THREAD

**Issue by simonh1000** [angular/angular#5199]
Is the following deliberate? I have this routing
```
@RouteConfig([
  { path: '/',         component: HomeCmp, as: 'Home' },
  { path: '/:filters', component: HomeCmp, as: 'Filters' }
])
```
load this Url `http://localhost:5555/american&fine-dining`, but all that comes out in `filters` in `params` is 'american'. With UI-router 1.0 I used to get 'american&fine-dining', which is what I need.

**Comment by btford** [comment]
Question: is `&` meant to be read as `american & fine-dining`, or are you expecting to use a param `&fine-dining`?

I think you should URL encode the &; otherwise this just looks like a malformed URL.

**Comment by simonh1000** [comment]
i take the string and split it at the `&` and use then both terms

**Comment by btford** [comment]
Is there a specific reason you do it this way, or this is to support some legacy URL scheme that you have no control over?

**Comment by simonh1000** [comment]
legacy - it worked with UI-router and produced what i thought were nice enough Urls. As it happens our main SEO interest is really only in those pages with one parameter in the url, i.e. where no `&` is needed. So I've switched to `+` for the time being

**Comment by btford** [comment]
Right, semantically, I think using `&` like is problematic.

I'm happy to support a way to recognize routes with `&` used this way, but I think it should do so in a way that redirects to a canonical URL with (for instance) `+` used instead. I think it would be bad for the router to be producing URLs like `/foo&bar`.

**Comment by vicb** [comment]
related to the old router
