### ISSUE TITLE
@for with async - Object is possible null

### ISSUE THREAD

**Issue by arambazamba** [angular/angular#51993]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

I tried using the new control flow with the async pipe and got the err that the Object is possible 'null'. Voucher$ is a simple array in combination with of(arr)

        @for (v of vouchers$ | async; track v) {
          <tr>
            <td>{{ v.ID }}</td>          
          </tr>
        }

### Please provide the exception or error you saw

```true
[ERROR] NG1: Object is possibly 'null'. [plugin angular-compiler]
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.0.0-next.6
Node: 18.17.1
Package Manager: npm 9.6.7
OS: win32 x64

Angular: 17.0.0-next.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-next.6
@angular-devkit/build-angular   17.0.0-next.6
@angular-devkit/core            17.0.0-next.6
@angular-devkit/schematics      17.0.0-next.6
@angular/cdk                    17.0.0-next.5
@angular/fire                   7.6.1
@angular/material               17.0.0-next.5
@schematics/angular             17.0.0-next.6
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

**Comment by JeanMeche** [comment]
`AsyncPipe` returns `T|null` so this kind of expected, 

https://github.com/angular/angular/blob/32cfbb4306c56ad0b498fb2ae599c8f0929844c6/packages/common/src/pipes/async_pipe.ts#L118-L121

But `ngFor` was accepting `null` as input, 

https://github.com/angular/angular/blob/32cfbb4306c56ad0b498fb2ae599c8f0929844c6/packages/common/src/directives/ng_for_of.ts#L145-L148

I don't know if that's intentional or not (there no test convering that)

**Comment by crisbeto** [comment]
I chatted with @pkozlowski-opensource about this. We should support null/undefined in the expression since the runtime accounts for it already.
