### ISSUE TITLE
Publish AngularDart to `pub`

### ISSUE THREAD

**Issue by mhevery** [angular/angular#520]
All of the AngularDart needs to be published as a single module to https://pub.dartlang.org/packages/angular as `v2.0.0-alpha.0`

**Comment by naomiblack** [comment]
We should create a new package "angular2" for this phase of development

**Comment by rkirov** [comment]
Document to track all publishing/releasing decisions https://docs.google.com/document/d/15IlXYv01BDkJVtblKff_iHikNRksgwdjsPbFIvqOI9o/

**Comment by naomiblack** [comment]
Live on pub! See https://pub.dartlang.org/packages/angular2
