### ISSUE TITLE
Router: link to child component should go to default child route if no child route name

### ISSUE THREAD

**Issue by wardbell** [angular/angular#5200]
In many cases, the `Parent` component will display links to the child components. The parent doesn't know about the child's own routes and shouldn't have to know *in this scenario*.

For example, suppose that we have a "Hero Employment Agency" that matches hero employees to crises.

The `AppComponent` is the parent and it is a shell with links across the top to go to child "feature" components, `CrisisCenterComponent` and `HeroesComponent`, each dealing with its own concern (managing crises, managing heroes), each with its own rats-nest of sub-components and routes.

Assume
```
@Component({
  selector:'my-app',
  template:  `
    <h1 class="title">Hero Employment Agency</h1>
    <a [router-link]="[...]" >Crisis Center</a>
    <a [router-link]="[...]" >Heroes</a>
    <router-outlet></router-outlet>
  `,
  directives: [ROUTER_DIRECTIVES]
})
@RouteConfig([
  {path: '/crisis-center/...', as: 'CrisisCenter', component: CrisisCenterComponent},
  {path: '/heroes/...',  as: 'Heroes', component: HeroesComponent}
]))
export class AppComponent { ... }
```

And 
```
@Component({ ... })
@RouteConfig([
  {path:'/',    as: 'CrisisCenter', component: CrisisListComponent},
  {path:'/:id', as: 'CrisisDetail', component: CrisisDetailComponent}
])
export class CrisisCenterComponent { }
```

And
```
@Component({ ... })
@RouteConfig([
  {path:'/',    as: 'Heroes', component: HeroListComponent},
  {path:'/:id', as: 'HeroDetail', component: HeroDetailComponent}
])
export class HeroesComponent { }
```

Right now, the `AppComponent` template's link bar has to look something like this:
```
<a [router-link]="['CrisisCenter', 'CrisisCenter']" >Crisis Center</a>
<a [router-link]="['Heroes', 'Heroes']" >Heroes</a>
```

That's silly. Worse, it obliges the `AppComponent` to know about at least one of the route names for each child feature.

I'd rather it be:
```
<a [router-link]="['CrisisCenter']" >Crisis Center</a>
<a [router-link]="['Heroes']" >Heroes</a>
```

At present, this raises a complaint about a non-terminal route. But what if the child component had a default route? Then the router would know how to keep working it's way toward a terminal route.

I can think of ways to identify a default route:

1. A "default" property (only one allowed per configuration)
1. A child route with the path `\`

The other constraint would be that a default route cannot have a parameters object ... because there would be no way to specify it. We could live with that.

# Corollary

The `{path: '/crisis-center/...', ` syntax seems unnecessary if the target component has configured routes, one of which is the default.

I don't think this is a big deal. But if we could omit it, then `AppComponent` would never have to know that `CrisisCenterComponent` has its own routes.

That seems like a win to me.

**Comment by DennisRoam** [comment]
I agree, I was having issues with this as well as I assumed `['/Child']` was enough but there currently isnt any sort of "default" for child components. 

I figured out that this works though(bit of a hack)

```javascript

//link
<a [router-link]="['/Cars']">Cars</a>

//config
{ path: '/', redirectTo: '/' },
{ path: '/', as: 'Default', component: CarsDefault },

```
[Plunker](http://plnkr.co/edit/SaXhUXokvmypF8NafILi?p=preview)

It hit's the redirect to and then pulls the next value.. Super hacky but it works without throwing the error...

**Comment by wardbell** [comment]
That is  ***so clever***!

Lets hope we don't have to name this maneuver after you!

**Comment by tandu** [comment]
I'm using stub component:

```typeScript
@Component({selector: '', template: ''}) class Stub {}

@Component(...)
@RouteConfig([
  { path: '/', component: Stub },
  { path: '/gallery/:id', component: Gallery, as: 'Gallery' }
])
export class Home {}
```

**Comment by wardbell** [comment]
I believe that this will be addressed satisfactorily in a version of the router coming "very very soon".

**Comment by btford** [comment]
Yes. Very very soon.

**Comment by jimulle** [comment]
Does this change remove the need to use the `/...` syntax for nested routes?

Example:

```
@RouteConfig([
  {path: '/heroes/...',  as: 'Heroes', component: HeroesComp}
])
export class AppComp { ... }

@RouteConfig([
  {path:'/',    as: 'Heroes', component: HeroListComp},
  {path:'/:id', as: 'HeroDetail', component: HeroDetailComp}
])
export class HeroesComp { }
```

becomes

```
@RouteConfig([
  {path: '/heroes',  as: 'Heroes', component: HeroesComp}  //no '/...' ?
])
export class AppComp { ... }

@RouteConfig([
  {path:'/',    as: 'Heroes', useAsDefault: true, component: HeroListComp},
  {path:'/:id', as: 'HeroDetail', component: HeroDetailComp}
])
export class HeroesComp { }
```

**Comment by ericmartinezr** [comment]
@jimulle nope, that's necessary to indicate the route that it has children, otherwise is a terminal route. What it changed was the way you call it from your router-link

Previous this change
```
// Parent
{path: '/parent/...', name : 'Parent, ...}
// Child
{path: 'child', name : 'Child, ...}
// Link
<a [router-link]="['/Parent', 'Child']">...</a> <-- Had to specify at least one child :'( !!
```
Became
```
// Parent
{path: '/parent/...', name : 'Parent, ...}
// Child
{path: 'child', name : 'Child, useAsDefault: true, ...}
// Link
<a [router-link]="['/Parent']">...</a>   <--- No more 'Child'
```
It redirects you automatically to the default route.
