### ISSUE TITLE
Reactive forms - overflowed content

### ISSUE THREAD

**Issue by tkolok** [angular/angular#52015]
### Describe the problem that you experienced

Some content of "Using the FormBuilder service to generate controls" section in "Reactive forms" topic are overflowed, so the text cannot be read. Furthermore, due to this, a horizontal scrollbar appears at the bottom of the document.

### Enter the URL of the topic with the problem

https://angular.io/guide/reactive-forms#using-the-formbuilder-service-to-generate-controls

### Add a screenshot if that helps illustrate the problem

The left side of the content
![image](https://github.com/angular/angular/assets/12582532/29deba54-af3f-4b01-983d-21283a131c46)

The right side of the content
![image](https://github.com/angular/angular/assets/12582532/4025d53b-7ffe-4f4f-989f-b49094ceaa54)

**Comment by JeanMeche** [comment]
This is basically #45121. Let's continue to track this over there.
