### ISSUE TITLE
Defer block doesn't chunk components inside forwardRef

### ISSUE THREAD

**Issue by eneajaho** [angular/angular#52014]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Defer block won't chunk the components that are used with a forwardRef. 

```ts
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [forwardRef(() => DeferMeCmp)],
  template: `
    <button (click)="show.set(!show())">show</button>
    <div>
      @if (show()) { 
         @defer (on immediate) {
           <defer-me />
         }
      }
    </div>
  `,
})
export class AppComponent {
  show = signal(false);
}


// defer-me.cmp.ts

@Component({
  selector: 'defer-me',
  template: ` <div>Defered!</div> `,
  standalone: true,
})
export class DeferMeCmp {}
```

**Comment by alxhub** [comment]
This component is defined in the same file anyway, so it can't be defer-loaded.

**Comment by eneajaho** [comment]
> This component is defined in the same file anyway, so it can't be defer-loaded.

I've added the name of the other cmp file as a comment 😅

**Comment by eneajaho** [comment]
> This component is defined in the same file anyway, so it can't be defer-loaded.

This case would be great addition for documentation.
