### ISSUE TITLE
Angular 16 does not run on chrome 58.0.3029.125 (android 8)

### ISSUE THREAD

**Issue by hiagodotme** [angular/angular#52026]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

When creating an application using @angular/cli it is not loaded in Chrome 58.0.3029.125 (Android 8).

It doesn't show anything in the error console. I only noticed because people using old devices reported not being able to access the application. For testing, I created an application from scratch using the CLI and tried to access it on an Android emulator.

Only a blank screen is presented with the page title.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.2.0
Node: 16.19.0
Package Manager: npm 8.19.3
OS: linux x64

Angular: 16.2.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.0
@angular-devkit/build-angular   16.2.0
@angular-devkit/core            16.2.0
@angular-devkit/schematics      16.2.0
@angular/cli                    16.2.0
@schematics/angular             16.2.0
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```

**Comment by JeanMeche** [comment]
Chrome 58 is over 6 years old and isn't part of the scope of supported browsers. 

Your best luck is to try adding it into your browserlist to see if this could fix your issue.

**Comment by hiagodotme** [comment]
@JeanMeche Is the only solution for this to downgrade Angular?

**Comment by JeanMeche** [comment]
First try editing the browserlist and add the browsers you want to support.

**Comment by hiagodotme** [comment]
@JeanMeche Where do I do this?
