### ISSUE TITLE
Inconsistency in bootstrapping an application using a standalone component

### ISSUE THREAD

**Issue by Magnuti** [angular/angular#52048]
### Describe the problem that you experienced

On this page [Bootstrapping an application using a standalone component](https://angular.io/guide/standalone-components#bootstrapping-an-application-using-a-standalone-component) the docs say this `An Angular application can be bootstrapped without any NgModule by using a standalone component as the application's root component.`.

While on this page [Prerequisites](https://angular.io/guide/bootstrapping#prerequisites) the doc says this `Every application has at least one Angular module, the root module, which must be present for bootstrapping the application on launch.`.

So which one is correct? Are modules required for bootstrapping the application or not?

### Enter the URL of the topic with the problem

https://angular.io/guide/standalone-components#bootstrapping-an-application-using-a-standalone-component

### Describe what you were looking for in the documentation

I was looking into how to bootstrap the application with standalone components.

### Describe the actions that led you to experience the problem

Reading through the documentation.

### Describe what you want to experience that would fix the problem

Consistent documentation.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/43852515/16354ce9-4408-42a5-8b95-6b18e8078435)
![image](https://github.com/angular/angular/assets/43852515/cb81d953-4416-4119-add0-78f7c7baeccf)

**Comment by khalilswdp** [comment]
Can I also help with this? It seems interesting

**Comment by yousefalaqra** [comment]
What is the status of this issue? do we still need someone to open pr and send a fix?

**Comment by JeanMeche** [comment]
Hi, we're looking to deprecate angular.io in favor of https://angular.dev. 

The new doc site has been updated to be standalone oriented. I'll close this as resolved.
