### ISSUE TITLE
Upgrade from 14 to 16 randomly breaks production build in CI

### ISSUE THREAD

**Issue by stefan-willems-beech** [angular/angular#52044]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Currently we build our Angular application inside the CI and after an upgrade to version 16 it starts to behave weirdly through failing the build like 30 percent of the times.   
  

### Please provide the exception or error you saw

```true
Unknown error: TypeError: (0 , rxjs_1.map) is not a function
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.4
Node: 18.10.0
Package Manager: yarn 1.22.19
OS: linux x64

Angular: 16.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.4
@angular-devkit/build-angular   16.2.4
@angular-devkit/core            16.2.4
@angular-devkit/schematics      16.2.4
@angular/cdk                    16.2.6
@angular/cli                    16.2.4
@angular/material               16.2.6
@schematics/angular             16.2.4
rxjs                            7.8.1
typescript                      4.9.5
zone.js                         0.13.3
```

### Anything else?

The command being ran:  
  
`ng build --configuration production`

**Comment by JeanMeche** [comment]
Hi, without a reproduction repo this isn't actionable by us.

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
