### ISSUE TITLE
APP_INITIALIZER usage in context of standalone components

### ISSUE THREAD

**Issue by phalgunv** [angular/angular#52058]
### Describe the problem that you experienced

The example in [APP_INITIALIZER's usage notes](https://angular.io/api/core/APP_INITIALIZER#usage-notes) are for NgModules.

### Enter the URL of the topic with the problem

https://angular.io/api/core/APP_INITIALIZER#usage-notes

### Describe what you were looking for in the documentation

There should be an example of configuring APP_INITIALIZER token in context of standalone components. 

For example:

```
function initializeAppFactory(httpClient: [HttpClient](https://angular.io/api/common/http/HttpClient)): () => Observable<any> {
 return () => httpClient.get("https://someUrl.com/api/user")
   .pipe(
      tap(user => { ... })
   );
}

@Component({
  selector: 'my-app',
  standalone: true,
  imports: [CommonModule],
  template: `
    <h1>Hello from {{ name }}!</h1> `,
})
export class App {
  name = 'Angular';
}

bootstrapApplication(App, {
  providers: [
    provideHttpClient(),
    {
      provide: APP_INITIALIZER,
      useFactory: initializeAppFactory,
      multi: true,
      deps: [HttpClient],
    },
  ],
});
```

**Comment by phalgunv** [comment]
I would like to pick this up.

**Comment by JeanMeche** [comment]
Feel free to open a PR with the changes if you want !

**Comment by phalgunv** [comment]
Should this instead be a section in [Bootstrapping an application using a standalone component](https://angular.io/guide/standalone-components#bootstrapping-an-application-using-a-standalone-component) section instead?

**Comment by twerske** [comment]
This PR was merged into the repository by commit https://github.com/angular/angular/commit/644f3f22411e96db512670e5a84f89fd4ad5c896.
