### ISSUE TITLE
Can't resolve all parameters for setupPlatform: (?, [object Object], [object Object]) error on ionic serve

### ISSUE THREAD

**Issue by ansh218** [angular/angular#52055]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

I have updated from Angular 7 to Angular 8, and after updating when I am trying to run ionic serve, it gives me an error for SetupPlatfrom, I tried searching for DOCUMENT import we have not used that import, anyother help will be appreciated  

<img width="598" alt="Screenshot 2023-10-05 233306" src="https://github.com/angular/angular/assets/58247122/6a7ff988-f1a2-4020-ab5f-7abd1614f6d7">

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
