### ISSUE TITLE
Last item in a dropdown always initially selected in Edge

### ISSUE THREAD

**Issue by ersommer** [angular/angular#5206]
I'm trying to use `ngModel` to bind to the value of a select dropdown menu in a form. The options are generated via `ngFor`. The model is bound to some variable like `selectedOption`. 

``` html
<p>Selected: {{selectedOption}}</p>
<select [(ng-model)]="selectedOption">
  <option *ng-for="#option of items"  [value]="option">{{option}}</option>
</select>
```

In Chrome, the value of `selectedOption` is set to the right value, and the UI shows the right value in the dropdown selected. 

In Edge, the value of `selectedOption` becomes the last value added via the `ngFor`. The UI sometimes selects the right value, sometimes selects the last one (not 100% on this behavior yet). I attached an event listener for the `ng-model-change` event, and as each item in the `ngFor` is added, a change event is being fired. So `selectedOption` is updated to be whatever value was last added.

Here's a plnkr with the repo: http://plnkr.co/edit/HLDNWDS3pZZxHf9ZLhlm?p=preview

After loading everything should say "Test2"  (both dropdowns and both "Selected" texts) as that's what I set the initial value to. In Chrome, it works as expected. In Edge, the "Selected" texts say "Test3". Additionally, Edge has a bunch of change events showing it going from selecting Test2 (as expected) to Test1 --> Test2 --> Test3

I've tried with the alpha39 and alpha 45 versions of Angular2.

**Comment by pcroc** [comment]
We're hitting this too, is there any workaround?

**Comment by simonleclerc** [comment]
Same problem here. My workaround is to add ``[disabled]="myVariable"`` to the options with ``myVariable`` to ``true`` on the initialisation which do not fire those strange edge change, then put ``myVariable`` to ``false``. If options are changed after initialisation, I implement this : 
````
constructor(public cdr: ChangeDetectorRef) {}
ngOnChanges() {
        this.myVariable = true;
    }
    ngAfterViewChecked() {
        if(this.myVariable === true) {
            setTimeout(()=> {
                this.myVariable = false;
                this.cdr.detectChanges();
            }, 10);
        }
    } ````

**Comment by DzmitryShylovich** [comment]
@ersommer is this still an issue? can u update your plunkr?

**Comment by jdalton** [comment]
I cannot repro this issue via the plunkr in Edge 15.

**Comment by DzmitryShylovich** [comment]
cool. close the issue pls. thx
