### ISSUE TITLE
NG0203: inject() must be called from an injection context such as a constructor

### ISSUE THREAD

**Issue by JonWallsten** [angular/angular#52067]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

This is most likely not a bug in Angular per se. But hopefully I can t least get some context from you guys, and then you can feel free to close this if you feel it's a bug outside of Angular's responsibility.
I'm trying to load a remote module with loadChildren, but end up with this error. The stack trace ten pages long with repeating patterns, so it's hard to actually see where the injection context is lost. 
But the clear thing is that the injection-context is never passed to the remote module when it's loaded.
Is there any way of debugging where it's lost? 

It seems like the module is at least loaded:
![image](https://github.com/angular/angular/assets/5993909/67c3665b-006a-4e1e-a00d-ae6394fb9f34)

The parent injector:
![image](https://github.com/angular/angular/assets/5993909/12a09344-35f4-4939-a1f7-2d5d461b1aa9)

And this is we're it begins to fail:
`this._r3Injector.resolveInjectorInitializers();`

### Please provide a link to a minimal reproduction of the bug

https://github.com/JonWallsten/nx-repro/tree/dynamic

### Please provide the exception or error you saw

```true
core.mjs:11458 ERROR Error: Uncaught (in promise): Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (core.mjs:731:15)
    at Module.ɵɵinject (core.mjs:744:60)
    at Object._class21_Factory [as useFactory] (router.mjs:425:84)
    at Object.factory (core.mjs:9511:38)
    at core.mjs:9412:43
    at runInInjectorProfilerContext (core.mjs:694:9)
    at R3Injector.hydrate (core.mjs:9411:17)
    at R3Injector.get (core.mjs:9281:33)
    at injectInjectorOnly (core.mjs:738:40)
    at ɵɵinject (core.mjs:744:60)
    at resolvePromise (zone.js:1193:31)
    at resolvePromise (zone.js:1147:17)
    at zone.js:1260:17
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:10655:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:10655:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:10968:33)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:173:47)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.1
Node: 18.14.1
Package Manager: npm 9.3.1
OS: win32 x64

Angular: 16.2.4
... animations, common, compiler, compiler-cli, core, forms     
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------       
@angular-devkit/architect       0.1602.1
@angular-devkit/build-angular   16.2.1
@angular-devkit/core            16.2.1
@angular-devkit/schematics      16.2.1
@angular/cli                    16.2.1
@schematics/angular             16.2.1
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.2
```

### Anything else?
It works perfectly fins on Mac, but not Windows!

**Comment by JeanMeche** [comment]
I see that you initially open an issue here on the Nx repo nrwl/nx#19121, but it went nowhere.

**Comment by JonWallsten** [comment]
@JeanMeche That is correct! I wanted to see if I could get to understand the issue from Angulars perspective instead.

**Comment by JoostK** [comment]
This hints at multiple copies of `@angular/core` being loaded, each with their own runtime state. An injection context from one runtime will not be visible to calls that originate from a bundle that _sees_ a different copy of `@angular/core`.

**Comment by JonWallsten** [comment]
> This hints at multiple copies of `@angular/core` being loaded, each with their own runtime state. An injection context from one runtime will not be visible to calls that originate from a bundle that _sees_ a different copy of `@angular/core`.

@JoostK Interesting! I guess it would make sense since each remote can also be run as a standalone application. It's just different modules being loaded. AppModule vs RemoteEntryModule. I would guess then that @angular/core is being bundled with the remote as well. I'll try to analyze the bundles on monday.

**Comment by JonWallsten** [comment]
@JoostK You seem to be a 100 % correct!
I compared the dist from the two different versions on Nx:
![image](https://github.com/angular/angular/assets/5993909/c19b1945-5e7a-44b5-9e30-df48a3723534)
![image](https://github.com/angular/angular/assets/5993909/b228b648-1723-4762-9490-a50157f0d7fe)

I'll close this and let the Nx guys look at it.
