### ISSUE TITLE
ViewContainer: Operations fail when you move content elsewhere.

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#5207]
`Failed to execute 'insertBefore' on 'Node': The new child element contains the parent. in [null]`

Occurs in the following:

```html
<popup [visible]="isVisible">
  <div *ng-if="isVisible">Hello</div>
</popup>
```

In this case, the `<popup>` component moves its content to another floating div.

**Comment by matanlurey** [comment]
To clarify, the implementation looks something like this:

```dart
@Component(
  selector: 'popup' 
)
@View(
  template: r'''
    <!-- This gets move elsewhere in the DOM by a PopupService -->
    <template popup-ref>
      <ng-content></ng-content>
    </template>
  '''
)
```

**Comment by tbosch** [comment]
I could not reproduce this issue (also not with the internal test case).
The Ng2 compiler quite a bit and this issue is old.
Please reopen when we have a good reproduction case again.
