### ISSUE TITLE
Add support for typescript 5.2.x

### ISSUE THREAD

**Issue by aljaznuncic** [angular/angular#52074]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler-cli

### Description

Please add support for typescript 5.2.x (5.2.2)

### Proposed solution

Please add support for typescript 5.2.x (5.2.2)

### Alternatives considered

Please add support for typescript 5.2.x (5.2.2)

**Comment by JeanMeche** [comment]
TS 5.2 support is already merged will land with v17.
