### ISSUE TITLE
Abuse allowSignalWrites in effect with timeouts

### ISSUE THREAD

**Issue by zip-fa** [angular/angular#52078]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Hi. I am not sure if this should be fixed, but is it allowed to abuse effects with setTimeout / timer / interval (rxjs)?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-velxdv?file=src%2Fmain.ts

**Comment by pkozlowski-opensource** [comment]
Writing to a signal in a separate stack-frame (here created by setTimeout) is totally fine. Moreover our "safety checks" are here to enforce general guidelines and can't catch all the problematic usage scenarios.

I'm leaning towards closing it as "works as designed" but will keep it open for a bit to see what others think.

**Comment by pkozlowski-opensource** [comment]
Closing based on https://github.com/angular/angular/issues/52078#issuecomment-1752653400
