### ISSUE TITLE
🐞 (Angular - Forms.Validators.email)

### ISSUE THREAD

**Issue by Vic-rider** [angular/angular#52079]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

I thought the `Forms.Validators.email` accept when it matches `a@b.c` format but it's not exactly like that.

I use this  : **`admin.gmail@com`** and it's accepted as correct email.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/7sqmmj?file=src%2Fexample%2Fform-field-error-example.html

### Please provide the exception or error you saw

```true
I use this : **admin.gmail@com** or **example@com** and it's accepted as correct email.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.0
Node: 18.12.1
Package Manager: npm 8.12.1
OS: win32 x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1600.0 (cli-only)
@angular-devkit/core         16.0.0 (cli-only)
@angular-devkit/schematics   16.0.0 (cli-only)
@schematics/angular          16.0.0 (cli-only)
```

**Comment by JeanMeche** [comment]
From the spec perspective `admin.gmail@com` and `example@com` are both valid email address. 

The domain doesn't necessarly have a TLD.
