### ISSUE TITLE
`provideAnimationsAsync` and defer makes the build size increases

### ISSUE THREAD

**Issue by robertIsaac** [angular/angular#52086]
### Which @angular/* package(s) are the source of the bug?

animations, common

### Is this a regression?

No

### Description

the Initial Total size
no defer and `provideAnimations` 583.94 kB
defer and `provideAnimations` 591.13 kB
no defer and `provideAnimationsAsync` 592.47 kB
defer and `provideAnimationsAsync` 597.98 kB

### Please provide a link to a minimal reproduction of the bug

https://github.com/robertIsaac/first-look-at-angular-defer

### Please provide the exception or error you saw

```true
Initial Chunk Files   | Names         |  Raw Size | Estimated Transfer Size
chunk-PXT5SPC3.js     | -             | 154.29 kB |                27.74 kB
chunk-2VGQDYKM.js     | -             | 126.82 kB |                38.48 kB
main-OT7PTX2M.js      | main          | 107.40 kB |                20.61 kB
styles-3IGLJIDF.css   | styles        |  84.44 kB |                 8.09 kB
chunk-MTVICLBQ.js     | -             |  65.19 kB |                16.95 kB
polyfills-4UVFGIFL.js | polyfills     |  32.85 kB |                10.68 kB
chunk-UT6J3HP2.js     | -             |  26.55 kB |                 7.19 kB
chunk-2XJVAMHT.js     | -             | 449 bytes |               449 bytes

                      | Initial Total | 597.98 kB |               130.18 kB

Lazy Chunk Files      | Names         |  Raw Size | Estimated Transfer Size
chunk-5MKLAA5U.js     | -             | 899 bytes |               899 bytes
chunk-3N6WBVPE.js     | -             | 643 bytes |               643 bytes
chunk-DUNWNBS2.js     | -             | 186 bytes |               186 bytes
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0-next.7
Node: 18.16.0
Package Manager: npm 9.6.7
OS: win32 x64

Angular: 17.0.0-next.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-next.7
@angular-devkit/build-angular   17.0.0-next.7
@angular-devkit/core            17.0.0-next.7
@angular-devkit/schematics      17.0.0-next.7
@angular/cdk                    17.0.0-next.6
@angular/material               17.0.0-next.6
@schematics/angular             17.0.0-next.7
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

**Comment by AndrewKushnir** [comment]
@robertIsaac thanks for creating a ticket and providing a repro.

I took a quick look and found out that the code of the `AddCommentComponent` class is extracted into a separate chunk, but it's included into the initial load. As a result, the chunk that is loaded when `@defer` triggers becomes quite small (just re-exports the code from already loaded chunk).

When I modify a couple files to drop an unused reference to `AddCommentComponent` and use dynamic loading for routes (see the diff below) - I see the following:

```
Initial Chunk Files   | Names         |  Raw Size | Estimated Transfer Size
chunk-4MO5HZOE.js     | -             | 128.56 kB |                38.81 kB
styles-3IGLJIDF.css   | styles        |  84.44 kB |                 8.09 kB
main-JGMAUDDQ.js      | main          |  65.64 kB |                16.47 kB
polyfills-4UVFGIFL.js | polyfills     |  32.85 kB |                10.68 kB
chunk-IZ5HOMUN.js     | -             |  26.55 kB |                 7.19 kB
chunk-WODTINHC.js     | -             |  11.75 kB |                 3.77 kB
chunk-2XJVAMHT.js     | -             | 449 bytes |               449 bytes

                      | Initial Total | 350.24 kB |                85.45 kB

Lazy Chunk Files      | Names         |  Raw Size | Estimated Transfer Size
chunk-5AJI6LTJ.js     | -             | 142.67 kB |                24.50 kB
chunk-WSTQB4HE.js     | -             |  65.19 kB |                17.01 kB
chunk-KZ7JWJRZ.js     | -             |  21.16 kB |                 4.28 kB
chunk-6F3MAOD2.js     | -             |  21.06 kB |                 4.26 kB
chunk-HVQ6JG7Q.js     | -             | 899 bytes |               899 bytes
chunk-HGKDZEOI.js     | -             | 634 bytes |               634 bytes
chunk-DWXGXWTH.js     | -             | 209 bytes |               209 bytes
```

We will perform further investigation on why the `AddCommentComponent` was included into the initial load and let you know.

Here is the diff that I've used to get the results mentioned above:
```
diff --git a/src/app/app.routes.ts b/src/app/app.routes.ts
diff --git a/src/app/app.component.ts b/src/app/app.component.ts
index 441da67..8a6daae 100644
--- a/src/app/app.component.ts
+++ b/src/app/app.component.ts
@@ -1,11 +1,10 @@
 import { Component } from '@angular/core';
-import { AddCommentComponent } from './add-comment/add-comment.component';
 import { RouterLink, RouterOutlet } from '@angular/router';
 
 @Component({
   selector: 'app-root',
   standalone: true,
-  imports: [AddCommentComponent, RouterOutlet, RouterLink],
+  imports: [RouterOutlet, RouterLink],
   templateUrl: './app.component.html',
   styleUrls: ['./app.component.scss']
 })

diff --git a/src/app/app.routes.ts b/src/app/app.routes.ts
index 740ca6a..c764514 100644
--- a/src/app/app.routes.ts
+++ b/src/app/app.routes.ts
@@ -1,14 +1,12 @@
 import { Routes } from '@angular/router';
-import { BundleSizeExampleComponent } from './bundle-size-example/bundle-size-example.component';
-import { HttpRequestExampleComponent } from './http-request-example/http-request-example.component';
 
 export const routes: Routes = [
   {
     path: 'bundle-size-example',
-    component: BundleSizeExampleComponent,
+    loadComponent: () => import('./bundle-size-example/bundle-size-example.component').then(m => m.BundleSizeExampleComponent),
   },
   {
     path: 'http-request-example',
-    component: HttpRequestExampleComponent,
+    loadComponent: () => import('./http-request-example/http-request-example.component').then(m => m.HttpRequestExampleComponent),
   },
 ];
```

**Comment by JeanMeche** [comment]
I looks like an "expected" behavior (or at least a known limitation) where the bundler isn't able to handle the code splitting because it is referenced in 2 eagerly loaded files.

Even if you had `app-add-comment` used only in `BundleSizeExampleComponent`, it was imported by both `BundleSizeExampleComponent` and `HttpRequestExampleComponent`. 
I've already seen situation when if you have 2 separate imports in the main bundle, the bundlers (esbuild & webpack) aren't able to split the code correctly. 

If you just remove the unused import of `AddCommentComponent` in `HttpRequestExampleComponent` your main bundle size jumps from `591.08 kB` to `387.68 kB` (every import in the defered views land correctly in the lazy chunck files)  

The best workaround for this is what Andrew already mentionned : lazy-load every component in the router so the imports aren't in the same bundle ! 


@clydin will probably be able to confirm this.

**Comment by robertIsaac** [comment]
hi @AndrewKushnir and @JeanMeche 
it was unintentional mistake that the component was imported in the app component, thank you for pointing it out yes it make sense now why everything was loaded

**Comment by robertIsaac** [comment]
the total size now after removing the unused imports

defer and provideAnimationsAsync 390.18 kB
defer and provideAnimations 450.63 kB
no defer and provideAnimations 583.93 kB
no defer and provideAnimationsAsync 592.46 kB

so I'm closing it as it's a problem in my code
the other problem about unused import is already reported in https://github.com/angular/angular/issues/46766
