### ISSUE TITLE
Multiple control flow issues: NG5002: Unclosed block ""

### ISSUE THREAD

**Issue by zip-fa** [angular/angular#52082]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler

### Is this a regression?

No

### Description

I just broke new @-template syntax. Just look at my repro

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-at-nsbzgp?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
src/main.ts:8:5 - error NG5002: Invalid ICU message. Missing '}'.
src/main.ts:7:30 - error NG5002: Unclosed block ""
src/main.ts:8:5 - error NG5002: Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.)
```

**Comment by JeanMeche** [comment]
This is expected, you have to escape the `@` (`&#64;`) character when using the new @-syntax.

**Comment by zip-fa** [comment]
But what if i don't want to use new syntax? Imagine i just want to update to v17 without need to use new control flow.
Can you explain why i should escape @ here:

`template: `test: support@test.com``

**Comment by zip-fa** [comment]
Also, this template breaks:

```
   template: `<a class="link">@{{ test }}
 </a>`,
```

while this one doesn't:

```
   template: `<a class="link">
   @{{ test }}
 </a>`,
```

**Comment by JeanMeche** [comment]
I think you got lucky on the one that didn't break. 

Having to escape `@` is one of the tradeoffs that was deemed acceptable when they chose the @-syntax over the #-syntax. 

That being said, work is still on-going on improving the detection of issues with the new syntax (#52047  landed yesterday for example).

**Comment by zip-fa** [comment]
@JeanMeche i tried multiple ways to escape, as you mentioned before, but had no luck:

```
template: `support\@test.com`,
```

gives this:

```
Error: src/main.ts:11:21 - error NG5002: Unclosed block "test"
Error: src/main.ts:11:27 - error NG5002: Unexpected character "."
```

This one gives the same error:
```
 template: `support@\comail.com`,
```

This one too:

```
  template: `support@@omail.com`,
 ```
 
 This one too:
 
```
template: `support\\@omail.com`,
```

This works :)), but renders with backslash:

```
  template: `support@/gomail.com`,
  ```

**Comment by JeanMeche** [comment]
It's an html escape code that you need, I mentioned it in a previous message : `&#64;`

**Comment by zip-fa** [comment]
I still think that this doesn't work as expected, maybe better to leave this issue open and fix parsing of blocks?

**Comment by JeanMeche** [comment]
I see no issung with `support&#64;comail.com` in the template.

**Comment by AndrewKushnir** [comment]
@zip-fa using HTML entities for `@` and `}` characters is the recommended way at this moment (you can also use `&commat;` to replace `@` char). This is pretty common in HTML as well, where you need to use HTML entities for symbols that are load bearing for parsing, for example `<` or `>` - you'd need to use `&lt;` and `&gt;` instead.

We've improved the error message in https://github.com/angular/angular/commit/a90d85ad40080636909f9c6ad98b7dc7a37207fc to mention the origin of the problem and a possible fix. We'll be collecting feedback over time, but there are no changes planned to the parsing logic at this moment.
