### ISSUE TITLE
@defer: mat-slider not detecting changes when component is OnPush

### ISSUE THREAD

**Issue by zip-fa** [angular/angular#52094]
### Which @angular/* package(s) are the source of the bug?

core, Don't known / other

### Is this a regression?

No

### Description

Using `@defer` with ChangeDetectionStrategy.OnPush will lead to "broken" state in mat-slider

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-at-bloxey?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0-next.7
Node: 18.18.0
Package Manager: yarn 1.22.19
OS: linux x64

Angular: 17.0.0-next.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-next.7
@angular-devkit/build-angular   17.0.0-next.7
@angular-devkit/core            17.0.0-next.7
@angular-devkit/schematics      17.0.0-next.7
@angular/cdk                    17.0.0-next.5
@angular/material               17.0.0-next.6
@schematics/angular             17.0.0-next.7
rxjs                            7.4.0
typescript                      5.2.2
zone.js                         0.13.0
```

**Comment by JeanMeche** [comment]
Hi, thanks for reporting that. 

The issue is that change detection isn't run on the deferred view when instantiated. This will require a fix.

**Comment by AndrewKushnir** [comment]
@zip-fa thanks for reporting the issue. I've created a PR with the fix, see https://github.com/angular/angular/pull/52095. We were no marking views that represent defer block states as dirty, thus they were not picked up by change detection.

@JeanMeche thanks for the help to narrow down the repro.

**Comment by zip-fa** [comment]
@AndrewKushnir can you please take a look at this too: https://github.com/angular/angular/issues/52082
I think it needs to be reviewed
