### ISSUE TITLE
async animations: NullInjectorError: No provider for AnimationBuilder!

### ISSUE THREAD

**Issue by zip-fa** [angular/angular#52096]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

Yes

### Description

It works when using non-async animations.
@JeanMeche i think this one for you.

offtop: feeling myself like a beta-tester of v17

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-at-jxpv8x?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
vendor.js:38033 ERROR NullInjectorError: R3InjectorError(Standalone[App])[AnimationBuilder -> AnimationBuilder -> AnimationBuilder]: 
  NullInjectorError: No provider for AnimationBuilder!
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 17.0.0-next.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-next.7
@angular-devkit/build-angular   17.0.0-next.7
@angular-devkit/core            17.0.0-next.7
@angular-devkit/schematics      17.0.0-next.7
@angular/cdk                    17.0.0-next.5
@angular/material               17.0.0-next.6
@schematics/angular             17.0.0-next.7
rxjs                            7.4.0
typescript                      5.2.2
zone.js                         0.13.0
```

**Comment by JeanMeche** [comment]
Thank you @zip-fa for logging this. There is still something we need to do about this. 

Currently if you import `BrowserAnimationBuilder` from `@angular/platform-browser/animations` it will effectivily break the code splitting and thus the lazy loading. We can cannot import from `@angular/platform-browser/animations` if we want to lazy-load the animations. This is why `provideAnimationsAsync` has been located in a separate entry : `@angular/platform-browser/animations/async`

**Comment by zip-fa** [comment]
So there is no way to use AnimationBuilder with async animations for now? Any ETA?
I shaved off my build 175kb today with your async realisation and feeling good about this to be honest

**Comment by JeanMeche** [comment]
Let me take a look at it so we can hopefully land this for v17.
