### ISSUE TITLE
HttpClient params urlEncode is not satisfied rfc3986 

### ISSUE THREAD

**Issue by quanbetter** [angular/angular#52098]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

http://localhost:8080/app/api/timeoutConfig?apiType=CONSUMER&cluster=default&name=risk-gateway-api@/gateway?api=risk.order.subsidy&apiVersion=1.0.0
编码为
http://localhost:8080//app/api/timeoutConfig?apiType=CONSUMER&cluster=default&name=risk-gateway-api@/gateway?api=risk.order.subsidy%26apiVersion=1.0.0'

**Comment by JoostK** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
