### ISSUE TITLE
PRINT PDF IN ANGULAR WITH ARABIC FONT

### ISSUE THREAD

**Issue by zezo2020alborhi** [angular/angular#52104]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

We tried many ways to print pdf in angular but there is no way it only show some and wanted characters in the printed document 

### Proposed solution

add library to angular to allow us to print pdf in arabic mode 

### Alternatives considered

only and this library to angular so it will enhance the powerful of the language

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
