### ISSUE TITLE
@if and async pipe throws with `No provider for _ChangeDetectorRef!`

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#52102]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

When using the new control flow syntax with an async pipe in an `@if` block, the application throws at runtime.

component:
```ts
import { Component } from '@angular/core';
import { AsyncPipe } from '@angular/common';
import { of } from 'rxjs';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [AsyncPipe],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  condition$ = of(true);
}
```

template:
```html
@if (condition$ | async) {
  Hello
}
```

The following repro is a basic cli app showcasing the issue

### Please provide a link to a minimal reproduction of the bug

https://github.com/cexbrayat/if-async-change-detector-ref

### Please provide the exception or error you saw

```true
NullInjectorError: R3InjectorError(Environment Injector)[_ChangeDetectorRef -> _ChangeDetectorRef]: 
  NullInjectorError: No provider for _ChangeDetectorRef!
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0-next.7
Node: 18.16.0
Package Manager: npm 9.7.1
OS: darwin arm64

Angular: 17.0.0-next.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-next.7
@angular-devkit/build-angular   17.0.0-next.7
@angular-devkit/core            17.0.0-next.7
@angular-devkit/schematics      17.0.0-next.7
@schematics/angular             17.0.0-next.7
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

**Comment by JeanMeche** [comment]
It's weird, I didn't have that issue on my @-syntax demo. https://stackblitz.com/edit/angular-at

It turns out this issue only happens when the `@if` block isn't wrapped, for example in a div. 

This template throws:
```
@if (condition$ | async) {
  Hello
}
```

This one doesn't: 


```
<div>
    @if (condition$ | async) {
      Hello
    }
</div>
```

**Comment by pkozlowski-opensource** [comment]
This is a confirmed bug in a compiler. For the described situation the generated code is (example):

```javascript
function CondComponent_Template(rf, ctx) {
    if (rf & 1) {
        jit___pipe_4(0, 'async');
        jit___template_5(1, CondComponent_Conditional_1_Template, 1, 0);
    }
    if (rf & 2) {
        jit___advance_6(1);
        jit___conditional_7(1, (jit___pipeBind1_8(0, 1, ctx.condition$) ? 1 : -1));
    }
}
```

Notice that the `pipe` instruction is generated before any other instructions. This in practice means that we don't have any active TNode. 

We should swap the order of the pipe / template instructions in that case.

Thnx for reporting @cexbrayat
