### ISSUE TITLE
Route data is inherited from non-empty route when paramsInheritanceStrategy is 'emptyOnly' when route's own resolvers are run

### ISSUE THREAD

**Issue by Erbenos** [angular/angular#52108]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

As the title says, parent route's data is inherited when paramsInheritenceStrategy is 'emptyOnly' when route's own resolvers get run even when the parent route is non-empty. 

See the atached stackblitz.

1) Use 'Child' link to trigger root route's resolver. See its data change.
2) Use one of the 'Granchild' links to trigger (or not) child route's resolver. See its data change when resolvers are run by ALSO inheriting whatever parent's data was.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-73915v?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
No error.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 16.2.8
```

**Comment by atscott** [comment]
@Erbenos Can you confirm what you're expecting to see here? The middle route inherits parent data because its path is empty. The documentation around `emptyOnly` may be poor, but the behavior is that it inherits parent data if the route _itself_ is empty path or its _parent_ does not have a component. So in the reproduction, the middle route inherits parent data correctly because it's an empty path route.

**Comment by Erbenos** [comment]
I see, they way I understood emptyOnly up until now is that it makes it so that routes inherit data from empty (empty path or no component) ancestors up until first non-empty one.

The stackblitz demo routing:

A (child) -> B ('') -> C (child). Where X -> Y means that X is parent of Y. I thought that the fact that B inherits the data from A when B's resolvers get run is incorrect, but since you explained `...that it inherits parent data if the route itself is empty path or...` I see thats not the case. Can be closed, sorry for the false issue.

**Comment by atscott** [comment]
@Erbenos No worries. To be honest, I didn't really understand `emptyOnly` either and generally have worked under the assumption that the strategy is "always". I was surprised to (re)learn that the default is `emptyOnly`.
