### ISSUE TITLE
Benchmarks: benchpress reports 0 for all categories for (gcTime, scriptTime, etc) in Dartium

### ISSUE THREAD

**Issue by hterkelsen** [angular/angular#5210]
I think this has to do with different tracing categories for old versions of Chrome. This is preventing us from running the benchmarks on Golem.

cc @tbosch @yjbanov

**Comment by mhevery** [comment]
I don't think Dartium supports these items. Not sure there is a way to make this work.

**Comment by hterkelsen** [comment]
Sorry, forgot to close this bug. This was fixed in #5209
