### ISSUE TITLE
Custom transformers not run during static analysis 

### ISSUE THREAD

**Issue by marcus-sa** [angular/angular#52100]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

Why aren't custom transformers being run during ngtsc static analysis?
We're trying to add @Inject() decorators to component constructor parameters using a custom transformer which works fine, but Angular AOT doesn't work because the decorators are missing during static analysis.

**Comment by JoostK** [comment]
Transformers are applied after the binding phase, meaning that symbol information for transformed/synthetic nodes is not available.

Performing source-file modifications through transformers is not supported by the compiler.

**Comment by marcus-sa** [comment]
> Transformers are applied after the binding phase, meaning that symbol information for transformed/synthetic nodes is not available.
> 
> Performing source-file modifications through transformers is not supported by the compiler.

Why isn't it supported? Was it decided or simply not implemented?
