### ISSUE TITLE
Allow to alias the `@else if` blocks in control flow syntax

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#52103]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

Currently, the control flow syntax only allows to alias the first if condition.
It would be handy to be able to alias the `else if` blocks as well:

```html
@if (condition1; as condition1Result) {
  Hello1 {{ condition1Result }}
} @else if (condition2; as condition2Result) {
  Hello2 {{ condition2Result }}
} @else {
  Default
}
```

Throws:
```
NG5002: "as" expression is only allowed on the primary @if block [plugin angular-compiler]

    src/app/app.component.html:3:24:
      3 │ } @else if (condition2; as condition2Result) {
        ╵                         ~~~~~~~~~~~~~~~~~~~
```

It looks like this was implemented then reverted but the reasons are not clearly explained (https://github.com/angular/angular/commit/eb1faa8f87edc6ddd9dd855752a3b2b8a626b09b)

### Proposed solution

`@else if` blocks could allow aliasing the condition

### Alternatives considered

It's possible to work around that by using nested `@if`, but it's a bit sad as we now have `else if`:

```html
@if (condition1; as condition1Result) {
  Hello1 {{ condition1Result }}
} @else {
  @if (condition2; as condition2Result) {
    Hello2 {{ condition2Result }}
  } @else {
    Default
  }
}
```

**Comment by crisbeto** [comment]
We were discussing this some time ago, but decided not to support it, because the alias is there only for backwards compatibility with `ngIf`.

**Comment by alxhub** [comment]
We discussed this particular point extensively during the design of control flow, and decided against expanding support for `as`. In particular `@if` in signal components will not support it at all, because it's incompatible with signal data flow.

`as` is effectively a local variable declaration, similar to `let inner = outer.expression;`. If you imagine the outer expression reads signals, then the inner expression is caching the resulting value in order to use it in a child template. This "loses reactivity" - the child template would never update because it isn't doing the signal reads itself. Instead, computed signals solve this problem in a much more canonical way.

**Comment by e-oz** [comment]
>  In particular @if in signal components will not support it at all

That's really sad. Sometimes you need to use the result of a signal dozens of times in the template. Should we replace all of it with signal reads? To create dozens of new nodes in the template? Why not update that local variable every time the signal is updated and mark the underlying view as dirty? 

I’m pretty sure this limitation will spark again the old feature request of local variables.

**Comment by pkozlowski-opensource** [comment]
> Should we replace all of it with signal reads? To create dozens of new nodes in the dependency graph?

Signal read does no create a new node in a reactive graph - in this sense we don't need to limit ourselves to the number of signal reads in a template.

**Comment by Harpush** [comment]
I am not sure it is related as I didn't check control flow yet - but what about signal read in @elseif narrowing? Without the `as` I guess further signal reads won't be affected

**Comment by pkozlowski-opensource** [comment]
@Harpush would you mind elaborating? I'm not sure I see any issue with else if and signals...

**Comment by e-oz** [comment]
> Signal read does no create a new node in a reactive graph

Sorry, looks like I misunderstood [this part](https://github.com/angular/angular/tree/main/packages/core/primitives/signals#dynamic-dependency-tracking):

> When a reactive context operation (for example, an effect's side effect function) is executed, the signals that it reads are tracked as dependencies.

**Comment by Harpush** [comment]
> @Harpush would you mind elaborating? I'm not sure I see any issue with else if and signals...

Considering a model:
```ts
test: {type: 'a', value: number} | {type: 'b', name: string} = {type: 'a', value: 8};
```
And template:
```html
@if (test.type === 'a') {
  {{test.value}}
} @else if (test.type === 'b') {
  {{test.name}}
} @else {
  ...
}
```
Everything works great.

But when using signals nothing compiles:
Model:
```ts
test = signal<{type: 'a', value: number} | {type: 'b', name: string}>({type: 'a', value: 8});
```
And template:
```html
@if (test().type === 'a') {
  {{test().value}}
} @else if (test().type === 'b') {
  {{test().name}}
} @else {
  ...
}
```

On another thought I am pretty sure now it isn't related to the else if `as` but a problem on its own...

**Comment by e-oz** [comment]
If a signal has type `T | undefined`, ngIf alias also allows us to not add “?” every time we access the variable.

**Comment by ValentinFunk** [comment]
I'm sure I'm fundamentally misunderstanding something here, but could the `as` compile to a `computed()`? What mental model can help understand why this is not a problem for the local var declaration inside of loops? (`@for (item of list)`)

**Comment by pkozlowski-opensource** [comment]
> I'm sure I'm fundamentally misunderstanding something here, but could the as compile to a computed()?

This would work if a conditional expression reads a signal. For regular expressions (without any signal read) a computed would never update. This show fundamental difference between reading a signal and a regular zone-based components. We want to minimize those differences.
