### ISSUE TITLE
Is this behavior working as intended?

### ISSUE THREAD

**Issue by b-rohan** [angular/angular#52101]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

When I build my application, the stack trace takes me to a line which takes me to this code. This just returns a null object which messes up any form validation when it tries to reference _rawvalidators. Should this be returning null? I am not a js expert so I want to know what it is for.

### Anything else?

I don't know why it doesn't show the file in the UI, but I am talking about: packages/forms/src/model/abstract_model.ts line 1382.

**Comment by JoostK** [comment]
Yes, this is intended. Subclasses implement this logic as needed. The `_rawValidators` field is not public API so you probably shouldn't be using it.

Closing as this is otherwise not actionable (there is _very_ little information provided in this issue).
