### ISSUE TITLE
Improve Http ergonomics for JSON usage

### ISSUE THREAD

**Issue by robwormald** [angular/angular#5211]
Such as:
- developers using JSON 99.93% of the time and avoiding having to JSON.stringify things manually.
- adding appropriate content-type headers when sending JSON.
- possibly adding an operator like `.json() ` as sugar for `.map(res => res.json())`

**Comment by robwormald** [comment]
@jeffbcross thoughts on making a JSON focused injectable that sugars this away, and having a separate service for more low level things?

**Comment by gdi2290** [comment]
:+1: 
Time to JSON

**Comment by thelgevold** [comment]
```possibly adding an operator like .json() as sugar for .map(res => res.json())```
+1 for sure!

**Comment by robwormald** [comment]
This issue was moved to angular/http#61
