### ISSUE TITLE
ComponentMirror interface: Should say if an input is required or not

### ISSUE THREAD

**Issue by PowerSupply** [angular/angular#52117]
### Which @angular/* package(s) are relevant/related to the feature request?

core

_No response_

### Description

Since Angular 16 you may annotate an input as required. It would be useful if this information was available in the `ComponentMirror` object returned by the `reflectComponentType` function.

### Proposed solution

Type of inputs in ComponentMirror should be changed from:
```
get inputs(): ReadonlyArray<{
    readonly propName: string;
    readonly templateName: string;
    readonly transform?: (value: any) => any;
}>;
```

to:
```
get inputs(): ReadonlyArray<{
    readonly required: boolean;
    readonly propName: string;
    readonly templateName: string;
    readonly transform?: (value: any) => any;
}>;
```

### Alternatives considered

None. This is the natural way to solve it since all other [@Input decorator](https://angular.io/api/core/Input#transform) metadata is available.

**Comment by alxhub** [comment]
Required inputs are a compile-time type-checking feature. There's no runtime information about whether an input is required or not at all.

**Comment by PowerSupply** [comment]
No discussion? Why not add it to support reflection? 

My use case: I am dynamically creating a component and need to  know what inputs are required or not. How do you motivate that [all other input metadata](https://angular.io/api/core/Input#input) is available but not `required`?
