### ISSUE TITLE
Google map marker clicks not properly propagated to other components

### ISSUE THREAD

**Issue by simonh1000** [angular/angular#5212]
I can set up a Google map marker with a click event. Let's say the map is in child1. When clicked, I pass a message up to the parent, and from there down to another component. However, there is no re-rendering of this component with the new data. If I cause the same message from child1 with a button click then the result is rendered. See: http://plnkr.co/edit/EPbOsfa5z89rLsvKzPW1?p=preview

I can work around by adding `this.ngZone.run( () => this.select.next(i) );` into the marker call back closure

I think this is a very (too) subtle event handling difference

**Comment by DzmitryShylovich** [comment]
@simonh1000 sounds like zone.js issue. Can you pls update the plunkr?

**Comment by pkozlowski-opensource** [comment]
This is a super-old issue for which we don't have reproduce issue any more. @simonh1000 please re-open with a new plunker / stackblitz if this is still an issue.
