### ISSUE TITLE
Translation Issue

### ISSUE THREAD

**Issue by syoho** [angular/angular#52128]
### Describe the problem that you experienced

Hello, I'd like to raise a translation query.

In the Chinese version of the Angular site, the original English sentence:

`Add the product descriptions. On a <p> element, use an *ngIf directive so that Angular only creates the <p> element if the current product has a description.`

has been translated as 

`添加产品说明。在 <p> 元素上使用 *ngIf 指令，以便 Angular 只让当前产品有描述 <p> `

However, considering the context, would it be more fitting to translate it as 

`添加产品说明。在 <p> 元素上使用 *ngIf 指令，以便Angular只有在当前产品有描述时才会创建这个<p>元素"?`

I look forward to hearing from you.

Best regards.

### Enter the URL of the topic with the problem

https://angular.cn/start

**Comment by JoostK** [comment]
Angular.cn is not maintained by the Angular team, but over at https://github.com/ng-docs/angular-cn.

**Comment by syoho** [comment]
Thank you for your response.
