### ISSUE TITLE
Feature Request: Add input signal and router params signal

### ISSUE THREAD

**Issue by MunMunMiao** [angular/angular#52139]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Currently, if you want to set the input value to the component's signal in the component, the best practice is:

```ts
export class MyComponent {
  @Input('id')
  set inputId(value: number){
    this.id.set(value)
  }
  id = signal<number | null>(null)

  constructor(){
    effect(() => {
      // do something...
    })
  }
}
```

This will bring some problems

1. this will cause us to repeatedly define setters with similar or duplicate names and it cannot be well combined with signal.
2. if function component is supported in the future, this decorator will become invalid.
3. cannot directly use intpu value in effect because it cannot be responded to when the input value changes.

### Proposed solution

> In class component
```ts
export class MyComponent {
  id = input()
  // or
  id = input('myId')
  // or
  id = input({
    alias: 'myId'
    ...
  })
}
```

> In function component
```ts
export const MyComponent = component(() => {
  id = input()
  // or
  id = input('myId')
  // or
  id = input({
    alias: 'myId'
    ...
  })
})
```

The input signal here is a readonly signal

### Alternatives considered

no

**Comment by MunMunMiao** [comment]
Related to it are also router path params and router query params. In this way, we can get rid of the dependency of rxjs.

**Comment by pkozlowski-opensource** [comment]
Input as signals are definitively on top of our priority list. We did describe them in a RFC and those are happening sooner than later.

> Related to it are also router path params and router query params.

This will work out of the box as soon as inputs can be expressed as signals since router can already set inputs based on various data from a route (including query params).

**Comment by srukshan98** [comment]
Do we have a ETA for this?
