### ISSUE TITLE
Building and testing angular2 locally

### ISSUE THREAD

**Issue by vijquick** [angular/angular#5213]
Hello All

Please can someone add proper documentation for building and testing angular2 locally. Angular1.x
has good [documentation](https://docs.angularjs.org/misc/contribute) on this. 

Thanks
Vijay

**Comment by ericmartinezr** [comment]
There you go
https://github.com/angular/angular/blob/master/DEVELOPER.md

**Comment by vijquick** [comment]
Thank you. That's exactly what I am looking for. Believe me, I googled for it, went through angular.io and couldn't find link to that any where. Thanks again
