### ISSUE TITLE
[style.background]="" [style.backgroundSize]="" don't work together well

### ISSUE THREAD

**Issue by aleksander351** [angular/angular#52131]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Angular is combinig those two styles together into the background style.

background: repeating-linear-gradient(45deg, rgb(147, 236, 166), rgb(147, 236, 166) 50%, rgb(234, 208, 102) 50%, rgb(234, 208, 102));
background-size: 20px 20px;

then becomes >>

background: repeating-linear-gradient(45deg, rgb(147, 236, 166), rgb(147, 236, 166) 50%, rgb(234, 208, 102) 50%, rgb(234, 208, 102)) 0% 0% / 20px 20px;
}

In principle this is not a big issue, the problem is, it's not working all the time.

### Please provide a link to a minimal reproduction of the bug

coming soon

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 15
```

**Comment by JoostK** [comment]
This isn't Angular doing this, it's the browser.

```ts
const el = document,createElement('div');
el.style.background = 'repeating-linear-gradient(45deg, rgb(147, 236, 166), rgb(147, 236, 166) 50%, rgb(234, 208, 102) 50%, rgb(234, 208, 102))';
el.style.backgroundSize = '20px 20px';
```

results in combining `backgroundSize` into the compound `background` style.

**Comment by aleksander351** [comment]
> This isn't Angular doing this, it's the browser.
> 
> ```ts
> const el = document,createElement('div');
> el.style.background = 'repeating-linear-gradient(45deg, rgb(147, 236, 166), rgb(147, 236, 166) 50%, rgb(234, 208, 102) 50%, rgb(234, 208, 102))';
> el.style.backgroundSize = '20px 20px';
> ```
> 
> results in combining `backgroundSize` into the compound `background` style.

so basically what you are saying is _[style.background]="" [style.backgroundSize]=""_ should not be used like this.

**Comment by JoostK** [comment]
I can't say, it's not clear to me what `it's not working all the time` actually means. `background` is a [shorthand property](https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties) and the [CSSOM](https://www.w3.org/TR/cssom-1/) that Angular uses to write styles has particular merging behavior when combining shorthand properties with individual proprties.

**Comment by aleksander351** [comment]
.example {
  width: 600px;
  height: 600px;
  background: radial-gradient(27% 29% at right, #0000 83%, yellow 85% 99%, #0000 101%) calc(16px / 2) 16px,
              radial-gradient(27% 29% at left, #0000 83%, yellow 85% 99%, #0000 101%) calc(16px / -2) 16px,
              radial-gradient(29% 27% at top, #0000 83%, yellow 85% 99%, #0000 101%) 0 calc(16px / 2),
              radial-gradient(29% 27% at bottom, #0000 83%, yellow 85% 99%, #0000 101%) 0 calc(16px / -2) purple;
  background-size: 32px 32px;
}

gets computed in the browser to this:

radial-gradient(27% 29% at right center, rgba(0, 0, 0, 0) 83%, rgb(255, 255, 0) 85%, rgb(255, 255, 0) 99%, rgba(0, 0, 0, 0) 101%) calc(8px) 16px, radial-gradient(27% 29% at left center, rgba(0, 0, 0, 0) 83%, rgb(255, 255, 0) 85%, rgb(255, 255, 0) 99%, rgba(0, 0, 0, 0) 101%) calc(-8px) 16px, radial-gradient(29% 27% at center top, rgba(0, 0, 0, 0) 83%, rgb(255, 255, 0) 85%, rgb(255, 255, 0) 99%, rgba(0, 0, 0, 0) 101%) 0px calc(8px), radial-gradient(29% 27% at center bottom, rgba(0, 0, 0, 0) 83%, rgb(255, 255, 0) 85%, rgb(255, 255, 0) 99%, rgba(0, 0, 0, 0) 101%) 0px calc(-8px), rgb(128, 0, 128)

https://codepen.io/aleksander351/pen/ZEVwxre?editors=1100
