### ISSUE TITLE
Http request subscribe with try catch finally clause

### ISSUE THREAD

**Issue by tbragaf** [angular/angular#5214]
Hi all!

In alpha 44, subscribing to an http request with try catch finally, does not trigger the Finally clause if an error is thrown.
In my example, the API it correctly throws a 404, triggering the Catch clause but the Finally clause does not trigger (only triggers after a successful subscription).

Can anyone help on this?

Best regards,
Tiago Braga

**Comment by robwormald** [comment]
try/catch/finally is an idiom for synchronous code, and thus won't work with async code.

http's interface is Observable: `http.get(url).subscribe(next, error, complete)` - Observables will *either* error or complete, but never both.

**Comment by tbragaf** [comment]
@robwormald Thank you for the help and for the heads up :)

**Comment by yannickadam** [comment]
@robwormald Is there any counter indication to using the following:

    http.get(url).
    finally( finalMethod ).
    subscribe(next, error, complete);
