### ISSUE TITLE
The change detection cycle is run 4 times on startup

### ISSUE THREAD

**Issue by adriancuadrado** [angular/angular#52154]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

The change detection cycle is run 4 times on startup

### Please provide a link to a minimal reproduction of the bug

https://stackblitz-starters-d8tfcw.stackblitz.io

I don't understand why the stackblitz link takes forever to load, so here is the code anyways:

```typescript
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: '{{ obj.foo }}'
})
export class AppComponent {
  obj = {
    get foo() {
      console.log(
        'This log demonstrates that the change detection cycle is run 4 times.'
      );
      return 'Hello world!';
    },
  };
}
```

### Please provide the exception or error you saw

```true
You can see in the console a message being displayed each time the change detection cycle is run, which is 4 times instead of 2 as expected.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.5
Node: 20.8.0 (Unsupported)
Package Manager: npm 10.1.0
OS: win32 x64

Angular: 16.2.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.5
@angular-devkit/build-angular   16.2.5
@angular-devkit/core            16.2.5
@angular-devkit/schematics      16.2.5
@angular/cli                    16.2.5
@schematics/angular             16.2.5
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
```

### Anything else?

[This StackOverflow post](https://stackoverflow.com/a/45412670/5744858) illustrates where in the source code this problem is originated, but not why. Because I was unable to find a single proper explanation of this phenomenon anywhere, I am proceeding to report this as a bug.

**Comment by adriancuadrado** [comment]
These are the StackOverflow posts I've gone through:
* [Angular change detection runs eight times instead four](https://stackoverflow.com/questions/45412199/angular-change-detection-runs-eight-times-instead-four): This is the one I linked above.
* [Why is a child component called four times on initial loading of the parent component?](https://stackoverflow.com/questions/64404358/why-is-a-child-component-called-four-times-on-initial-loading-of-the-parent-comp): He explains that the cycle is run twice **_for some reason_** and that in dev mode it's twice as many to check if any bound value changed during the actual change detection. But really, **why** is it run twice on startup to begin with? What is that reason?
* [Why the angular binding run 4 times?](https://stackoverflow.com/questions/69423283/why-the-angular-binding-run-4-times): One of the answers is wrong because he says the cycle is run every couple of seconds and the other is also wrong for another reason I explained in the comments.
* [Why is change detection called twice?](https://stackoverflow.com/questions/56785866/why-is-change-detection-called-twice): One answer just explains that in dev mode the cycle runs twice for the reason I already mentioned, other explains what happens with OnPush, and the last one doesn't really explain the problem because it assumes it is caused by data being rendered somewhere else, which is obviously not.

I am so fucking done with all these explanations that don't explain the thing I need to know and spending so much time reading so many articles about the change detection cycles that I decided to come here and report this as a bug and see what happens.

**Comment by atscott** [comment]
As you've noted, when running in dev mode, templates are executed twice: once during regular change detection and again to check that no changes to the template bindings happened. So we can remove this double checking by calling `enableProdMode`. The second change detection happens here because of `ZoneJS`. There are several Promises that resolve during bootstrapping which cause the zone to become "unstable" and then stable again, triggering a second change detection.

Here's the example with no ZoneJS and prod mode showing only one execution of the binding: https://stackblitz.com/edit/stackblitz-starters-dw5f16?file=src%2Fmain.ts

Closing as working as expected.

**Comment by adriancuadrado** [comment]
These are the contents of atscott's stackblitz link, just for reference:

```typescript
import 'zone.js/dist/zone';
import {
  Component,
  enableProdMode,
  isDevMode,
  NgZone,
  provideZoneChangeDetection,
  ɵNoopNgZone,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { bootstrapApplication } from '@angular/platform-browser';

@Component({
  selector: 'my-app',
  standalone: true,
  imports: [CommonModule],
  template: '{{ obj.foo }}',
})
export class App {
  obj = {
    get foo() {
      console.log(
        'This log demonstrates that the change detection cycle is run 4 times.'
      );
      return 'Hello world!';
    },
  };
}

bootstrapApplication(App, {
  providers: [{ provide: NgZone, useClass: ɵNoopNgZone }],
});

enableProdMode();
```
