### ISSUE TITLE
Children Components ID

### ISSUE THREAD

**Issue by tbragaf** [angular/angular#5215]
Hi all!

Is it possible to access to child and view components with ID?
As:
```html 
<my-cmp #someId></my-cmp>
```
```javascript
// initialize viewChilds with @ViewChild
var myCmp = this.viewChilds.get('someId');
```

Best regards,
tbragaf

**Comment by mhevery** [comment]
See https://angular.io/docs/js/latest/api/core/ViewChild-var.html

**Comment by tbragaf** [comment]
@mhevery How does that help?
My problem is not access view child or children, but:
given a set of children, how do I access to a specific one?

**Comment by mhevery** [comment]
I see the documentation is lacking, but this should work:

```
@Component({
  selector: 'someDir',
  templateUrl: 'someTemplate',
  directives: [ItemDirective]
})
class SomeDir {
  @ViewChild("#someId") viewChild:ItemDirective;
  afterViewInit() {
    // viewChild is set
  }
}```

**Comment by tbragaf** [comment]
@mhevery I may have missed something then.
Trying that when I get back to work!

Thank you very much!

**Comment by flyingmutant** [comment]
I believe it should be `<something #some-id></something>` + `@ViewChild('someId')` currently (note `#some-id` vs `someId`).

**Comment by tbragaf** [comment]
@mhevery @flyingmutant Thank you both for your help!

It does work with @ViewChild('someId') :+1:

**Comment by PascalPrecht** [comment]
I think this is kind of unintuitive. I would expect it to work with
`#someId`. Any reasons why this is not the case, or can we change this?

**Comment by ericmartinezr** [comment]
You can see the examples of this under [di.ts](https://github.com/angular/angular/blob/master/modules/angular2/src/core/metadata/di.ts#L90)

**Comment by PascalPrecht** [comment]
Yeap, thanks Eric. But still, in other cases these decorators work with
element names. So I think it'd be more intuitive if we'd need to use # for
finding elements my id
