### ISSUE TITLE
Update parent component

### ISSUE THREAD

**Issue by akorchev** [angular/angular#5216]
Is there any way to trigger update of a parent component from a child one? 

The following code works but skips a "digest":

```
  constructor(@Host() list: ListComp) {
    list.count ++;
  }
```

Here is a reproduction: http://plnkr.co/edit/9xb71HUOa02dG9P5G7EI?p=preview

Click the "add" button. The counter will be displayed one step behind.

**Comment by pkozlowski-opensource** [comment]
We definitivelly don't want to circular change detection checks. Having said this your pb can be solved much simpler without keeping any intermediate state and coupling of the 2 directives: http://plnkr.co/edit/hCWSoitTNljFNN3TQ6UQ?p=preview

More generally, I don't think it is a good idea to maintain any type of children counters as this list is dynamic (for example, children can by removed by ngIf) so you would have hard time keeping your internal counter up-to date with the children list in UI.

**Comment by akorchev** [comment]
Thanks @pkozlowski-opensource, I see the point in avoiding circular change detection. Do you know why it works initially?

**Comment by mhevery** [comment]
you can cause a new CD by scheduling a microtask using Promise. Not a best practice.
