### ISSUE TITLE
Missing import does not break in compile time but crash in runtime

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/angular#52175]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

When you forget to import standalone directive into standalone component your app breaks in runtime. This should be handled by compiler.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-v3xxjr?file=src%2Ffoo.directive.ts

### Please provide the exception or error you saw

app builds and serves without error but then you get runtime error
`Can't bind to 'foo' since it isn't a known property of 'code' (used in the 'App' component template).`

This should happen already during build time.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.6
Node: 18.18.0
Package Manager: npm 10.1.0
OS: win32 x64

Angular: 16.2.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.6
@angular-devkit/build-angular   16.2.6
@angular-devkit/core            16.2.6
@angular-devkit/schematics      16.2.6
@angular/cli                    16.2.6
@schematics/angular             16.2.6
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
```

**Comment by JeanMeche** [comment]
Hi this issue has already been raised at #46351  / #46351, let's continue track this issue over there !
