### ISSUE TITLE
Interpolation on data attributes strips "data-" prefix

### ISSUE THREAD

**Issue by ahmed-dardery** [angular/angular#52190]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

Under specific conditions, angular strips **data-** prefix of data attributes, specifically this happens if the attribute is set using interpolation on the attribute. Specifically:

```
<div data-id="some-value-1">Div 1</div>
<div data-id="{{'some-value-2'}}">Div 2</div>
<div [attr.data-id]="'some-value-3'">Div 3</div>
```
* div1 is set using "native html".
* div2 is set using interpolation
* div3 is set using property binding, `attr` is necessary because `data-id` is not an input.

I'd believe all 3 should be identical, yet the html output of this is:

```
<div data-id="some-value-1">Div 1</div>
<div id="some-value-2">Div 2</div>
<div data-id="some-value-3">Div 3</div>
```
Notice that `data-` is stripped from the second div.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-binbax?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.6
Node: 18.18.0
Package Manager: npm 9.4.2
OS: linux x64

Angular: 16.2.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.6
@angular-devkit/build-angular   16.2.6
@angular-devkit/core            16.2.6
@angular-devkit/schematics      16.2.6
@angular/cli                    16.2.6
@schematics/angular             16.2.6
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
```

**Comment by JoostK** [comment]
This is a long standing inconsistency in data bindings, as tracked in #26406.
