### ISSUE TITLE
Better documentation for SSR with provideHttpClient

### ISSUE THREAD

**Issue by aleesaan** [angular/angular#52200]
### Describe the problem that you experienced

When using `provideServerRendering` with `provideHttpClient` we need to use `withInterceptorsFromDi` together with the `TransferHttpCacheModule`, or the requests done on the server will not be cached and will be done again in the browser. This is because the  [TransferHttpCacheModule](https://github.com/angular/universal/blob/main/modules/common/src/transfer_http.ts#L155) provides a class-based `TransferHttpCacheInterceptor` interceptor, so it won't work without using `withInterceptorsFromDi`. This is not documented anywhere and it took me some debugging to understand, I think it would be good to specify it in the SSR documentation.

### Describe the actions that led you to experience the problem

I migrated from the `HttpClientModule` to the new `provideHttpClient` API in my SSR app and noticed that it started repeating requests in the client.

### Describe what you want to experience that would fix the problem

Better documentation on using SSR with the new APIs would be great, but at least we should mention that to use `provideServerRendering` with `provideHttpClient` we need to also use `withInterceptorsFromDi`. Maybe it won't be necessary later, when the `provideClientHydration` is out of dev preview, but either way it should be better documented.

**Comment by alan-agius4** [comment]
@aleesaan, the mentioned API is deprecated in favor of `provideClientHydration`.  In version 17 which is currently in prerelease and will be released as stable later next month, the `TransferHttpCacheModule` API has been removed and `provideClientHydration` is out of developer preview. 

Therefore, at this point I don't think that `TransferHttpCacheModule` warrants to be included in the docs.

**Comment by aleesaan** [comment]
Yea indeed I mentioned that was the case but I think it would be good to mention for people using v16 for example. Otherwise we can just hope they bump in this thread and won't waste time figuring out the issue with the duplicate requests like I did 😬

**Comment by CarlosTorrecillas** [comment]
In my opinion, the overall documentation for SSR configuration should be reviewed since we are moving towards standalone components. Its true you can take info from here and there but the official docs should contain the example to provide the minimal working solution for SSR using SA components both client and server side. AFAIK such documentation is not available in the Angular site and the final example to be downloaded is set up using modules - last time I downloaded was like that at least. 

Don't get me wrong, the example is good, but perhaps we are lacking of another example if we want to take the SA approach.

**Comment by alan-agius4** [comment]
@CarlosTorrecillas, all the docs will be updated to standalone by default in version 17 which will be released later next week. As part of this, the SSR and Prerendering docs have also undergone an overhaul.

**Comment by CarlosTorrecillas** [comment]
@alan-agius4 I supposed si because I saw a couple of commits about it. Looking forward to update all the stuff to the latest greatest 🙌🏼
