### ISSUE TITLE
The documentation doesn't mention you need to add the new component in app.module.ts

### ISSUE THREAD

**Issue by adriancuadrado** [angular/angular#52201]
### Describe the problem that you experienced

The documentation doesn't mention you need to add the new component in app.module.ts

### Enter the URL of the topic with the problem

https://angular.io/guide/component-overview#creating-a-component-manually

### Describe what you were looking for in the documentation

I wanted to know how to creating a component manually

### Describe the actions that led you to experience the problem

I tried the steps from the provided link

### Describe what you want to experience that would fix the problem

I want the documentation to include what I said

### If this problem caused an exception or error, please paste it here

```true
Error: src/app/app.component.html:1:46 - error NG8001: 'app-child' is not a known element:
1. If 'app-child' is an Angular component, then verify that it is part of this module.
2. If 'app-child' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```
```


### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

**Comment by srukshan98** [comment]
I assume including the below will be sufficient for this.

## Adding the component to Module or Marking it as standalone

Once you've defined and styled your Angular component, it's essential to either include it within a module or designate it as standalone. This will enable Angular to recognize and utilize the component in the context of your application.

### Adding the component to Module

To integrate a component into a module, incorporate it into the `declarations` array found in the `@NgModule` decorator.
`
@NgModule({

    declarations: [

        ... // Existing Components

        ComponentOverviewComponent

    ],

     // rest of the module content

})
`

### Marking the component as standalone

There might be instances where a component is required to operate independently, without being part of a specific module. In such cases, you can mark the component as standalone. To do this, append the `standalone` flag to the `@Component` decorator.

`
@Component({

    selector: 'app-component-overview',

    template: '<h1>Hello World!</h1>',

    styles: ['h1 { font-weight: normal; }'],
  
    standalone: true

})
`

With these steps completed, your Angular component is ready for integration and use within your application. Remember to always refer to the Angular documentation and follow best practices to ensure the efficient and smooth functioning of your components.

**Comment by ferrorenan** [comment]
@pkozlowski-opensource Hey, Could you assign this issue to me?! I'm already working on a possible solution and will soon create the Pull Request!

**Comment by ferrorenan** [comment]
Hey @pkozlowski-opensource @adriancuadrado 

Structure implemented and PR created: https://github.com/angular/angular/pull/52282

If you need anything, I'm available!
