### ISSUE TITLE
Can we add .peek() to read the value without subscribing it

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#52210]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

This .peek() is available in knockoutjs and preact-signal too. With this it will be helpful and you do not need to add untracked fn every time. Also it will be align with other framework.

```
  foo = signal('');
  bar = signal('');
  
// this effect will run whenever you will change foo
 effect(() => {
   const value = foo() + bar.peek() + 'Awesome'
   bar(value);
 });
``` 

### Proposed solution

N/A

### Alternatives considered

N/A

**Comment by Erbenos** [comment]
I think this is already covered by `untracked`, see https://angular.io/guide/signals#reading-without-tracking-dependencies.

**Comment by JeanMeche** [comment]
`untracked` already allows this : `untracked(() => bar())`. 

 effect(() => {
   const value = foo() + untracked(() => bar()) + 'Awesome'
   bar.set(value);
 });

**Comment by indraraj26** [comment]
Thank you for your reply.

I know we can use untracked fn. but .peek() does the same WITHOUT passing any callback. Also with .peek() it will be align with other frameworks such as preact-signal and knockoutjs.

anyway as you say, we can stay with untrackedfn

**Comment by pkozlowski-opensource** [comment]
> I know we can use untracked fn. but .peek() does the same WITHOUT passing any callback. Also with .peek() it will be align with other frameworks such as preact-signal and knockoutjs.

All above it true and `.peek` would be a convenience method. Convenience is always good / appreciated, but it would have the following downsides:
* it would add to code size / runtime overhead for everyone, even people not using it (it would be a method on a signal getter that is not tree-shakable);
* it would make it less obvious that a signal is read in a non-reactive way - we were making the assumption that non-reactive reads would be pretty rare (and I'm curious about the use-case).

Given all the above we've decided _not_ to add `.peek()` as a method. We _could_ add a `peek` utility function, which would be really sth like:

```typescript
function peek<T>(signal: Signal<T>): T {
    return untracked(() => signal());
}
```

but I'm not sure if it is worth it given the simplicity of such utility and extended API surface.

**Comment by JoostK** [comment]
Note that you can do `untracked(signal)` as is; a signal is a zero-arg function, so no need to wrap it in another closure.
