### ISSUE TITLE
TypeScript Error TS2345 when using Request

### ISSUE THREAD

**Issue by chenkie** [angular/angular#5222]
I've implemented a custom request which is pretty much the same as the [example from the docs](https://angular.io/docs/ts/latest/api/http/Request-class.html). Everything works, but I'm running into a TypeScript error.

**Implementation**
```js
...

request(method:RequestMethods, url:string, body?:string) {
  return this.http.request(new Request({
    method: method,
    url: url,
    body: body
  }));
}
...

get(url:string) {
  return this.request(RequestMethods.Get, url);
}

post(url:string, body:string) {
  return this.request(RequestMethods.Post, url, body);
}
```

**Error**
```console
error TS2345: Argument of type '{ method: RequestMethods; url: string; body: string; }' is not assignable to parameter of type 'RequestOptions'.
Property 'headers' is missing in type '{ method: RequestMethods; url: string; body: string; }'.
```

I've got an almost identical custom Request in another spot that attaches a `header`, and I noticed that the error message for that one says `Property 'search' is missing type ... `. If I pass `headers`, `search`, and `merge` and set them to `null`, the error goes away.

The error seems to pop up any time I do a `new Request`.

Thanks!

cc @robwormald

**Comment by zamamohammed** [comment]
In the documentation I see type of method to be RequestMethods.GET but you have it as RequestMethods only

**Comment by chenkie** [comment]
Sorry, I should have provided more code for context. I updated the snippet. I'm passing in the specific RequestMethods in my individual get, post, etc methods :)

**Comment by jeffbcross** [comment]
@chenkie I think this is because right now, `http.request` and `new Request()` require an actual `RequestOptions` instance, and can't accept an object shaped like request options. This was done as part of a refactor of `Http` to add dart support, but we should fix it since `Http` no longer supports Dart.

In the meantime, you could actually create a `RequestOptions` instance to pass to `http.request()`

**Comment by chenkie** [comment]
Perfect, that works. Thanks @jeffbcross!
