### ISSUE TITLE
Bundles publication strategy

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#5223]
As a follow up to the closed PR #5149 and in particular to the [comments on the downside of the approach taken](https://github.com/angular/angular/pull/5149#issue-115358880) here is a new proposal:

* let's produce 2 UMD bundles:
  * core + RxJS
  * core + http + router + RxJS
* those bundles, being UMD, should be usable via a `<script>` tag and CJS-based tooling (WebPack etc.)
* those bundles won't contain "truly" external dependencies (zone, reflect-metadata, shims) - we are going to publish a separate file with those

@jeffbcross @robwormald @vsavkin - feel free to comment.

//cc.: @IgorMinar @rkirov

**Comment by robwormald** [comment]
Just to confirm, this will work with SystemJS as the current bundles do? 

eg:
```html
//index.html
<script src="ng-polywhatever.js"></script>
<script src="system.js"></script>
<script src="angular2-megabundle.js"></script>
<script>
  System.import('./myapp');
</script>
```
```js
//myapp.js
import {Component} from 'angular2/angular2'

//etc
```
I'lll totally defer to your knowledge gained through the struggle, but that seems strange, as it's not going to "populate" the System registry.

**Comment by pkozlowski-opensource** [comment]
> Just to confirm, this will work with SystemJS as the current bundles do?

No. What I've meant is that it _will_ work with SystemJS but not the same way. Ng2 would have to be pulled by SystemJS:

```html
//index.html
<script src="ng-polywhatever.js"></script>
<script src="system.js"></script>
<script>
  System.import('./myapp');
</script>
```

This might require additional SystemJS configuration, depending on a file name / exported names from mega-bundle.

This is why I don't think we should kill our SystemJS bundles (not at this point at least) as this would invalidate a lot of plunkers / doc examples. So in my mind we would keep current SystemJS bundles till we figure out the whole story. At the same time I would kill SFX bundles we are publishing.

**Comment by robwormald** [comment]
ah groovy, OK. :+1:

**Comment by rkirov** [comment]
What about testing and webworkers? Webworkers I can see as more experimental, but don't like that we decided to drop testing.

> those bundles, being UMD, should be usable via a `<script>` tag and CJS-based tooling (WebPack etc.)

How would RX work in this case? Is it:

* completely internal to ng2, so everything reexported is angular wrappers (like EventEmitter)
or
* the bundle exports `window.rx`, thus possible to reuse the lib in client code?

**Comment by robwormald** [comment]
Currently Observable and Subject are re-exported from the facade... so a user can import {Observable} from angular2/angular2

**Comment by robwormald** [comment]
@pkozlowski-opensource should we at the same time streamline the SystemJS bundles to match? We're building 9 (!) of them at the moment, so that could probably be cut down to match the suggestion above.

**Comment by pkozlowski-opensource** [comment]
@robwormald we don't have the same pb for bundles in the System.register format as we don't have to duplicate any code in those. I don't want to touch existing bundles while working on this issue as it would probably break tons of docs / examples. But we will get there :-)

**Comment by rolandjitsu** [comment]
Is it necessary to have Rx bundled with Angular? If for some reason the user is stuck on some version of Rx and and angular is way ahead what then? Which Rx version would win and is it advisable to have two different versions loaded?

Probably the version bundled by angular might be under the `System.register()` closure, but still, this would lead to extra bytes.

Just an opinion ...

**Comment by pkozlowski-opensource** [comment]
>  If for some reason the user is stuck on some version of Rx and and angular is way ahead what then? Which Rx version would win and is it advisable to have two different versions loaded?

@rolandjitsu this will be always a concern for any 3rd party deps that ng2 chooses to use. I could flip back a question: what if the RxJS version the user is stuck with doesn't work with ng2 that a given user wants to use?

Those are hard pbs and there are no perfect answers in the browser world where we kind of want to have multiple versions but don't pay the price (in bytes) of it.

I've got the impression that we are having this discussion partly because RxJS is quite heavy right now. But @robwormald has some ideas here, right Rob? :-) 

> Probably the version bundled by angular might be under the System.register() closure 

This issue is about CJS / UMD bundles - the discussion here won't have impact on the existing bundles (at least not for now).

**Comment by rolandjitsu** [comment]
@pkozlowski-opensource I have a question:
- How would I use the UMD files (from the alpha 47 release within `bundles`) with SystemJS? Is there any example somewhere that shows how the SystemJS config should look like?
