### ISSUE TITLE
HTTP_INTERCEPTOR_FNS di token is not exported from package

### ISSUE THREAD

**Issue by dadadcko** [angular/angular#52243]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

I want to dynamically register interceptors (e.g. in library), but don't want to call `provideHttpClient(withInterceptors([...]))`, because it can potentially override previous app configuration of HttpClient.

Currently, it is not possible to dynamically add functional interceptors to DI container, since `HTTP_INTERCEPTOR_FNS` token, under which those f. interceptors are registered, **is not exported** from `@angular/common/http` package.

The new token `HTTP_INTERCEPTOR_FNS` should be exported the same way as `HTTP_INTERCEPTORS` token is currently exported.
It would allow to dynamically add functional interceptors without worrying of accidentally overriding existing HttpClient configuration.

**Comment by JoostK** [comment]
This is intentional, please see #51539
