### ISSUE TITLE
[BUG?] Undefined Import when barrel-rolling (circular-dependencies?)

### ISSUE THREAD

**Issue by nawlbergs** [angular/angular#52251]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler, core, Don't known / other

### Is this a regression?

No

### Description

So... I keep running into a `runtime error` (not a compile error) in my large angular app:
`Uncaught TypeError: Cannot read properties of undefined (reading ...)`.   I often get it when I try to re-structure files.

(Not sure if this is an angular cli issue... a webpack issue.. or both.. but if nothing else... a better error would be great)

I've narrowed it down to the fact that I have been `barrel-rolling` my features and directories in my libraries...
For example:
```js
// myLib/features/user/index.ts
export * from './api/af-user.api';
export * from './af-user.manager';
export * from './af-user-initials.pipe';
```
and one of my components in a different part of the lib is importing the pipe.
```js
// myLib/shared/ui/af-user-avatar.component.ts
import { AfUserInitialsPipe } from '../../features/user';   // <--- BREAKS (at runtime, NOT on compile)
import { AfUserInitialsPipe } from '../../features/user/af-user-initials.pipe';  // <--- WORKS
```

If I import from `../../features/user` (the default import) the app successfully compiles... but wont run....
If I import directly from the file... its fine.

I'm assuming because the `../../features/user` import also pulls in the other items exported in the user feature and something is coming full circle  (circular dependency?)

I've been barrel-rolling like mad... because I really liked the pattern when I saw it... and thought most people do it..  but now I'm feeling like I need to remove all the barrel rolls and just deal with individual imports ect... because everytime this occurs... its a 1-2 hour nightmare of trying to find out which import is causing it... (because the error it generates sucks)

What's worse... is that the compiler succeeds... so you can be doing work for a couple hours... then when you run it... its broken... and you have to scour all your code changes to try and figure out whats wrong.

Here's the full error for the current issue.... you'll notice it doesnt even show `af-user-avatar` in the error.
```
af-api-utils.service.ts:18 Uncaught TypeError: Cannot read properties of undefined (reading 'AfApiRest')
    at Module.AfApiRest (af-api-utils.service.ts:18:33)
    at 15693 (af-user.api.ts:7:32)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at 35421 (af-user.api.ts:6:33)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at 3806 (af-table-basic.component.ts:24:25)
```

Anyone have thought on barrel-rolling... or do-and-don'ts....

### Please provide the exception or error you saw

```true
Uncaught TypeError: Cannot read properties of undefined (reading 'AfApiRest')
    at Module.AfApiRest (af-api-utils.service.ts:18:33)
    at 15693 (af-user.api.ts:7:32)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at 35421 (af-user.api.ts:6:33)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at 3806 (af-table-basic.component.ts:24:25)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Node   : 18.13.0
   OS     : win32-x64
   npm    : 9.8.0

   nx                 : 16.8.1
   @nx/js             : 16.8.1
   @nx/jest           : 16.8.1
   @nx/linter         : 16.8.1
   @nx/workspace      : 16.8.1
   @nx/angular        : 16.8.1
   @nx/cypress        : 16.8.1
   @nx/devkit         : 16.8.1
   @nx/eslint-plugin  : 16.8.1
   @nx/express        : 16.8.1
   @nx/node           : 16.8.1
   @nrwl/tao          : 16.8.1
   @nx/web            : 16.8.1
   @nx/webpack        : 16.8.1
   nx-cloud           : 16.4.0
   typescript         : 5.1.5
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.13.0
   @ngrx/component-store            : 16.0.0
   @ngrx/effects                    : 16.0.0
   @ngrx/entity                     : 16.0.0
   @ngrx/router-store               : 16.0.0
   @ngrx/store                      : 16.0.0
   @ngrx/store-devtools             : 16.0.0
```

### Anything else?

im running nx... i've also posted this in their angular help forum.

Thanks for all the hard work.. I love angular.

**Comment by JoostK** [comment]
Indeed, this is due to cycles. It's not a compile time error because ESM allows cycles, at the cost of possible runtime errors when top-level statements depend on other top-level statements to have been evaluated (which may no longer be the case in the presence of cycles).

There are various linting tools to detect cycles statically. Barrel files can be a common source for cycles, since the import graph that you reach into becomes larger, therefore increasing the chance of introducing a cycle.

This is not an Angular bug, but rather a common pitfall with ESM and cycles.
