### ISSUE TITLE
 Ambiguous abbreviation with formBuilder

### ISSUE THREAD

**Issue by ice-blaze** [angular/angular#52260]
### Describe the problem that you experienced

In the documentation, we can see `fb` abbreviation for the formBuilder. According to the Google javascript style guide, it is bad practice to use abbreviations https://google.github.io/styleguide/jsguide.html#naming-rules-common-to-all-identifiers.

### Enter the URL of the topic with the problem

~~https://angular.io/guide/reactive-forms#using-the-formbuilder-service-to-generate-controls~~ (fixed)
https://angular.dev/guide/forms/reactive-forms#define-a-formarray-control

**Comment by ice-blaze** [comment]
Commit was merged into main https://github.com/angular/angular/commit/cfd89b0833538d88aa51f064893a69e364ee9a68

**Comment by ice-blaze** [comment]
Saw that the new angular.dev documentation has still the old style.

**Comment by csvn** [comment]
Maybe https://angular.dev is not yet deployed from `main` at this repo? It was just recently open sourced 🤔

**Comment by JeanMeche** [comment]
Yes, deployement isn't wired yet. It's WIP.

**Comment by ice-blaze** [comment]
@csvn  I forgot to close this issue since it has been merged into `main`. My bad. It will come I guess at the next release of angular.dev stay tuned 📻.
