### ISSUE TITLE
TestComponentBuilder - surface ApplicationRef.tick

### ISSUE THREAD

**Issue by juliemr** [angular/angular#5228]
For applications that need more than just `detectChanges`

**Comment by juliemr** [comment]
I'm sorry, we discussed this offline a week ago and I've realized I don't know what the motivation for this is. @rkirov do you happen to know?

**Comment by rkirov** [comment]
`ApplicationRef.tick` has only one extra feature over detectChanges - protection against recursive calls. https://github.com/angular/angular/blob/master/modules/angular2/src/core/application_ref.ts#L446

I think when we initially talked I was mistaken that `tick()` does more like - resolving any scheduled microtasks. Do we have an API for that (or an existing issue)?

**Comment by juliemr** [comment]
As discussed offline - this doesn't really describe the issue. Opened a fresh clean issue: https://github.com/angular/angular/issues/5468
