### ISSUE TITLE
Service worker not working in MAC

### ISSUE THREAD

**Issue by moon-web75** [angular/angular#52296]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

I have used service worker in our web app and we want to use web view in mac app but service worker is not working on MACOS v14. but given this below error

![Serivce worker issue](https://github.com/angular/angular/assets/95608631/a2235fc1-4163-4cf7-a501-bee2f75075d7)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.7
Node: 16.15.1
Package Manager: npm 8.11.0
OS: win32 x64

Angular: 13.3.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1303.7
@angular-devkit/build-angular      13.3.7
@angular-devkit/core               13.3.7
@angular-devkit/schematics         13.3.7
@angular/cdk                       12.2.13
@angular/cli                       13.3.7
@angular/fire                      7.6.1
@angular/material                  12.2.13
@angular/material-moment-adapter   13.3.9
@angular/pwa                       13.3.7
@angular/service-worker            13.3.12
@schematics/angular                13.3.7
rxjs                               6.5.5
typescript                         4.6.4
```

**Comment by JeanMeche** [comment]
It's the same issue as #50378, let continue to track this over there !

**Comment by moon-web75** [comment]
@JeanMeche Why is this closed ?

When loading my app in Flutter as a website we have seen a blank page and above attached SS error so can you please check

**Comment by moon-web75** [comment]
> It's the same issue as #50378, let continue to track this over there!

Also, you have this attached link in his safari  related issue but why facing in flutter web view app
