### ISSUE TITLE
Defer block is does not lazy load component if the component's class name is referenced within the component.

### ISSUE THREAD

**Issue by ChellappanRajan** [angular/angular#52307]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Is it expected that when using ViewChildren to query a LazyLoadedComponent, the lazy chunk is not generated if the component class name is referred to inside the component?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-at-s6ox1c?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"dependencies": {
    "@angular/animations": "next",
    "@angular/common": "next",
    "@angular/compiler": "next",
    "@angular/core": "next",
    "@angular/cdk": "next",
    "@angular/material": "next",
    "@angular/forms": "next",
    "@angular/platform-browser": "next",
    "@angular/platform-browser-dynamic": "next",
    "@angular/router": "next",
    "moment": "^2.18.1",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.0"
  }
```

**Comment by crisbeto** [comment]
Yes, this is working as expected. The problem is that if we were to drop the import to the component, it would result in a compilation error in the place where it's referenced.

**Comment by alxhub** [comment]
`@defer` gives the compiler the opportunity to defer-load dependencies, it doesn't guarantee it. If the component is eagerly referenced directly in other ways, then it will get bundled into the parent bundle regardless. This is the same as any other lazy-loading operation - it only works if _all_ of the references to the module are lazy.
