### ISSUE TITLE
Defer block with prefetch on viewport throws because IntersectionObserver is not defined

### ISSUE THREAD

**Issue by eneajaho** [angular/angular#52304]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description
With SSR enabled on ng serve I get `ERROR ReferenceError: IntersectionObserver is not defined` 
![CleanShot 2023-10-20 at 22 54 49@2x](https://github.com/angular/angular/assets/25394362/a44cf5e3-e523-4ed2-b3cc-c4f8e0255d52)

**Comment by AndrewKushnir** [comment]
@eneajaho thanks for reporting the issue 👍 

This regression was introduced by https://github.com/angular/angular/commit/9d8af457e34f209b7112532c7cc9e38f23901f45. We'd need to make sure we have tests to prevent this from happening (for ex. a test in platform-server that would have a defer block with DOM-specific triggers).
