### ISSUE TITLE
feat(router): Allow child routes to have a URL alias

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#5231]
Currently if you have a parent/child route, the URL path is constructed as /parent/child. There isn't a way to have /parent/child represented as /child in the URL. This would allow the convenience of nested outlets, without having to construct long URL paths in order to access those routes.

**Comment by ericmartinezr** [comment]
+1 this would be awesome

**Comment by astec** [comment]
Especially useful if there are more than 1 way to navigate to a child and we want to have an unique URL for it.

**Comment by DennisRoam** [comment]
Please forgive me, I'm trying to understand your use case. 
So if you have the URL **www.site.com/cars/manage/1234** you would like to have www.site.com/cars/1234 that knows to use the manage component?

Or are you saying you want to declare that url: /manage goes to child component cars and then it's manage component?

**Comment by brandonroberts** [comment]
@DennisRoam Both. I want to use nested outlets to group a set of routes, but want the option for the child route URLs to be shorter.

Lets say I have a Account component with a with child routes for Registration, Settings, etc. If I want a URL for registration using it would be something like http://www.site.com/account/register and settings would be http://www.site.com/account/settings. What I would like is for the account registration route to be represented as http://www.site.com/register.

**Comment by evanplaice** [comment]
:+1:

**Comment by ewinslow** [comment]
+1 for decoupling component/render hierarchy from url structure
