### ISSUE TITLE
Flag to ban old control flow directive (ngFor, ngIf etc)

### ISSUE THREAD

**Issue by jpike88** [angular/angular#52318]
### Description

After migrating to new control flow logic, any developer can just accidentally start using the old syntax again. 

### Proposed solution

Have a flag that allows instances of `*ngFor`, `*ngIf` to be banned from use and have this flagged in the compiler and vscode extension.

### Alternatives considered

n/a

**Comment by flevi29** [comment]
This sounds like a job for [Angular ESLint](https://github.com/angular-eslint/angular-eslint).

**Comment by jpike88** [comment]
It sounds like a deprecation warning for angular... why would a linter enforce a framework specific change?

Side note: I avoid eslint like the plague due to its terrible performance profile and use biomejs instead

**Comment by spock123** [comment]
> It sounds like a deprecation warning for angular... why would a linter enforce a framework specific change?
> 
> Side note: I avoid eslint like the plague due to its terrible performance profile and use biomejs instead

Omg that project looks awesome, why didn't I know about this? Sorry for the spam guys

**Comment by JeanMeche** [comment]
@spock123 It's a fork of Rome.

**Comment by json-derulo** [comment]
According to the RFC (see #50719), Angular plans to deprecate and eventually remove the "old" directives in favor of the control flow. However there is no timeline yet. For sure it will not be deprecated before Angular v18, as the control flow is currently in developer preview.

If you want to ban control flow today, and are willing to use ESLint, you can use the [`@angular-eslint/template/prefer-control-flow` rule from Angular ESLint](https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin-template/docs/rules/prefer-control-flow.md).

**Comment by pkozlowski-opensource** [comment]
A ESLint rule, as suggested by @json-derulo is what we would recommend if you want prevent a project from using directive-based control flow after migration.
