### ISSUE TITLE
Docs Bug Report

### ISSUE THREAD

**Issue by syoho** [angular/angular#52340]
### Describe the problem that you experienced

Hello.

I'd like to raise a documentation concern. 

In the provided Angular tutorial page, the original sentence, `The getHeros() method taps into the flow of observable values and sends a message, using the log() method, to the message area at the bottom of the page.` seems to have a typo. 

Should `getHeros()` be corrected to `getHeroes()`? 

Based on the context of the tutorial, the method should be `getHeroes()`.

I look forward to your response.

Best regards.

### Enter the URL of the topic with the problem

https://angular.io/tutorial/tour-of-heroes/toh-pt6

**Comment by BojanKogoj** [comment]
I believe this is fixed?
