### ISSUE TITLE
Signals doesn't work with type guards

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular#52346]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When using signals **we lost the power of type guards in typescript:**

```ts
import { signal } from "@angular/core";

interface Base {
  type: 'a' | 'b'
}

interface A extends Base {
  type: 'a';
  foo: number;
}

interface B extends Base {
  type: 'b';
  bar: string;
}

const s = signal<A | B>({
  type: 'a',
  foo: 1
})


if(s().type === 'a') {
  s().foo // doesn't work
} 

// works fine
const simple: A | B = {
  type: 'a',
  foo: 1
}

if(simple.type === 'a') {
  simple.foo = 1
}
```

This is a big issue in my opinion. How can we solve it?

**Comment by JeanMeche** [comment]
This is how typescript works, there is no narrowing on the returned value of a function. 

The alternative is to create a variable : 

```
let value = s(); 
if(value.type === 'a') {
  value.foo // ok 
} 
```

**Comment by ArielGueta** [comment]
I know but first it forces us to create a redundant variable. Second, how do you manage it in the template?

**Comment by JeanMeche** [comment]
About the narrowing in template we already have #49161. Let's continue over there.

**Comment by ArielGueta** [comment]
```
<div *ngIf="value().type === 'a'">
  ??
</div>
```
