### ISSUE TITLE
zone-testing is not exported from package with zone.js 0.14.0

### ISSUE THREAD

**Issue by atomicrobokid** [angular/angular#52345]
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

Yes

### Description

With `zone.js: 0.13.*` karma tests ran absolutely fine, no issue, since upgrading to `0.14.0` they all fail with the following:

`zone-testing is not exported from package`

It is imported as recommended in the docs:

`import 'zone.js/zone-testing';`

Testing is missing from `package.json` exports, if this has been removed, where are the docs on how to replicate the functionality needed for things like `fakeAsync()`

### Please provide the exception or error you saw

```true
` Error: Module not found: Error: Package path ./zone-testing is not exported from package /Users/**/**/**/node_modules/zone.js (see exports field in /Users/**/**/**/node_modules/zone.js/package.json)
`
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.7
Node: 18.16.0
Package Manager: npm 9.5.1
OS: darwin arm64

Angular: 16.2.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.7
@angular-devkit/build-angular   16.2.7
@angular-devkit/core            16.2.7
@angular-devkit/schematics      16.2.7
@angular/cli                    16.2.7
@schematics/angular             16.2.6
ng-packagr                      16.2.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

**Comment by JeanMeche** [comment]
Where you see `import 'zone.js/zone-testing';` as recommandation in the docs ?
