### ISSUE TITLE
Http response do not include headers

### ISSUE THREAD

**Issue by bruno-quintanilha** [angular/angular#5237]
Maybe i am doing something wrong but when i make a request with Http i can see on the Network tab on chrome that the response include a custom header called 'Authorization' used to refresh the JWT. But when i try to access the response.headers it prints empty on the console.

```
return this.http.request(req).map((res: Response) => console.log(res.headers.values()));
```
![image](https://cloud.githubusercontent.com/assets/2547604/11095736/63197538-888e-11e5-895e-c50165ccaa35.png)

the same behaviour when printing keys().

the request headers, on the other hand, do print all the custom headers i add to the request.

**Comment by bruno-quintanilha** [comment]
Hey guys, i have found where the problem is and changed to get what i need.

In Http.dev.js on line 10645 aprox. i have added this basic (noob code ?) snipet:
```
var arrayOfLines = _xhr.getAllResponseHeaders().match(/[^\r\n]+/g);
          var headers = new headers_1.Headers();
          for(var i = 0; i < arrayOfLines.length; i++){
            var line = arrayOfLines[i];
            var name = line.substr(0,line.indexOf(':')).trim();
            var val = line.substr(line.indexOf(':')+1).trim();

            headers.append(name,val);
          }

          responseOptions.headers = headers;
```
sorry i did not do it in typescript because i was lazy to recompile.

also, of course, had to add the headers to the dependencies array and required it. I hope it helps.

Thanks

**Comment by wintouch** [comment]
Hi all, I'm having this same issue in alpha.44. I can't access the response header information that are supposed to be present in the headers map of the response. Example:

var req = new Request({
  url: `localhost/api/products`,
  method: RequestMethods.Get
});

this.http.request(req).subscribe(
  res => {
	// Can't access the headers of the response here.... res.headers is empty
  },
  error => { ... },
  _ => {}
);

If I check the network traffic in the browser's dev tools, the response headers are present...

**Comment by cangosta** [comment]
Hi all, I'm having this same issue in alpha.44. I can't access the response header information that are supposed to be present in the headers map of the response. Example:

var req = new Request({
  url: `localhost/api/products`,
  method: RequestMethods.Get
});

this.http.request(req).subscribe(
  res => {
	// Can't access the headers of the response here.... res.headers is empty
  },
  error => { ... },
  _ => {}
);

If I check the network traffic in the browser's dev tools, the response headers are present...

**Comment by bruno-quintanilha** [comment]
See my edit. I have a workaround to this issue untill they fix it.

Hope it helps you

**Comment by cangosta** [comment]
Hi @bruno-quintanilha, thanks for your suggestion. 

After some diving into angular2 code (and yours too), I realize that not all response headers are present when I invoke _xhr.getAllResponseHeaders(). Actually, only a couple of them are present!

Here follow the real response headers:

![image](https://cloud.githubusercontent.com/assets/848857/11144947/ca556bd8-89f8-11e5-9f9d-bba6b1972f11.png)

And the result of the _xhr.getAllResponseHeaders():

"Content-Language: pt-PT Content-Type: application/json; charset=utf-8"

Are there any suggested workaround?

**Comment by bruno-quintanilha** [comment]
Hi there,

try access directly to your custom header with: _xhr.getResponseHeader('x-total-count');

Maybe some checking if it exists.

But i can tell you that  i am able to access all response headers with the previous sugestion.

Hope it helps

**Comment by bruno-quintanilha** [comment]
BTW. Aqui da ilha da Madeira!  @cangosta

**Comment by tbragaf** [comment]
Hi all!

My custom headers are not being retrieved, for they do not appear it the headers map...

Anyone with the same problem?

tbragaf

**Comment by machi1990** [comment]
I have the same problem. Tried the workaround, with no success.

**Comment by robwormald** [comment]
we're simply grabbing headers from the raw XHR object, so if they don't appear there, there's not a whole lot we can do about it, unless there's something else we're missing. for those having issues, if you do a manual XHR request (see: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest ) - are you able to access the headers you're looking for?

**Comment by tbragaf** [comment]
My API was used in an NG1 app, so yes.
Also it was tested with this: https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo

tbragaf

**Comment by machi1990** [comment]
I am using the alpha46, and still not able to retrieve the response headers. Testing my WS with the REST Client, response headers are there. I can even see them in the browser developer's console, but not just on the my angular2 response object.

**Comment by tbragaf** [comment]
Alpha46 doesnt Support headers on response, it is a bug.
Still nothing with alpha48

**Comment by machi1990** [comment]
Ah I see. I had an issue with RxJs when upgrading to alpha48, so I have not tried it yet. As of current, I am still on alpha46 and retrieving the headers using the fetch API while waiting for the bug fix.

**Comment by robwormald** [comment]
@tbragaf http://plnkr.co/edit/FJj4Zqze6xpBCcH2M5Bl?p=preview <- this is with alpha 50, and i believe has been like this since 46 or 47. Could you look at the plunker please and see if you're doing things differently?

**Comment by tbragaf** [comment]
@robwormald Make sure you test this under the limit of 24 hours :)
http://plnkr.co/edit/V6RkITHxtwOLiwWJlezI?p=preview

The result should be ```x-total-count:42 ```

That header is not present, but you can see it if you go to the "Network" tab

**Comment by robwormald** [comment]
I can confirm they don't appear, but as I said above, its not something we have any control over. See this demo using vanilla XMLHttpRequest: http://plnkr.co/edit/u2YWls1U5Rw5eS74CQWA?p=preview

That throws an error : `Refused to get unsafe header "x-total-count"` - note that is the browser rejecting access, outside of angular entirely.

**Comment by tbragaf** [comment]
@robwormald 
Adding 'access-control-expose-headers' : 'x-total-count' on the API solves it :)

Thank you,
tbragaf

**Comment by robwormald** [comment]
:+1:

**Comment by jppellerin** [comment]
yup!  Thanks @tbragaf.  That's the issue I was having.

**Comment by midroid** [comment]
@tbragaf 
thanks, that helped. (Y)

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166447.
------------------------------------------------------------------------------------------------------------


[[9236266e571c9ae07a5224a6630f7ddfdc72e20b-673073311]]

**Comment by virtualvoid** [comment]
Still not working for me. Angular 2.0.0-beta14

**Comment by ashokshetty1970** [comment]
The workaround doesn't help. The inspection on Web Developer tool says that all the headers are there. However, the Response object doesn't get you the value. Even using jquery returns all the headers properly. Somewhere Angular 2 is messing up.

**Comment by garysui** [comment]
@tbragaf I am having similar result as @ashokshetty1970 . 
Symptom:
1. Using postman rest client do the request, all headers show just fine!
2. Using angular 2  http, ONLY one header entry shows:
"Content-Type" "application/json; charset=utf-8"

**Comment by tbragaf** [comment]
@ashokshetty1970 @garysui 
That is very odd. Not the fact that postman is able to correctly show headers. But that angular2 http is not. 

Have you specifically added the header on your API? 
Warning: `'access-control-expose-headers' : '*'` does not work for security reasons, I assume.

**Comment by garysui** [comment]
@tbragaf :+1: It works now without using '*'. In my case, I am using sails framework and I added `exposeHeaders: 'what-ever-header'` in cors.js file and the sails version has to be 0.12 and above.

**Comment by asanzdiego** [comment]
Hello I have the same issue with angular2-rc.1:

I can 'see' the headers in the 'network tab' of the Chromium browser, but if I do a console.log(response.headers) I don't see the same headers.

```
RESPONSE HEADERS FROM 'NETWORK TAB' OF CHROMIUM BROWSER:

Access-Control-Allow-Headers:Authorization, Content-Type, Accept, Cache-Control
Access-Control-Allow-Methods:POST, GET, OPTIONS, DELETE, PUT
Access-Control-Allow-Origin:*
Access-Control-Expose-Headers:*
Access-Control-Max-Age:3600
Cache-Control:no-cache, no-store, max-age=0, must-revalidate
Content-Type:application/json;charset=UTF-8
Date:Fri, 13 May 2016 13:53:27 GMT
Expires:0
Pragma:no-cache
Server:Apache-Coyote/1.1
Transfer-Encoding:chunked
X-Content-Type-Options:nosniff
X-Frame-Options:DENY
X-XSS-Protection:1; mode=block
```

```
console.log(response.headers)

Cache-Control:no-cache, no-store, max-age=0, must-revalidate
Content-Type:application/json;charset=UTF-8
Expires:0
Pragma:no-cache
```

Thanks

**Comment by pkozlowski-opensource** [comment]
@asanzdiego this is not an Angular issue - Angular gives you all the headers that XHR gives users. Try your example with vanilla https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest ans see what happens.

It is simply that some headers are meant to be interpreted by a browser only and not exposed to the users directly.

If, by any chance, you are getting different results with vanilla XMLHttpRequest please open a new issue with the exact reproduce scenario.

**Comment by asanzdiego** [comment]
@pkozlowski-opensource Exactly, this is not an Angular issue. Is an API problem. With the header `'access-control-expose-headers' : 'name-of-expose-header'` works fine.

The problem is that this doesn't work with the header `'access-control-expose-headers' : '*'`. You can't use `*` and you have to put explicity the name of the headers that you want to expose.

**Comment by tchoulihan** [comment]
Can anyone explain why its the case why this header is necessary? If I can see it in my browser, then its already exposed, so why can't angular2 or rx.js see it?

**Comment by zoechi** [comment]
@tchoulihan that's not related to Angular2 http://stackoverflow.com/questions/10143093/origin-is-not-allowed-by-access-control-allow-origin

**Comment by albanx** [comment]
Maybe it can help. My solution was to add this in the backend:
```
...
header("Access-Control-Allow-Methods: GET, POST, OPTIONS");
header("Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization, X-Custom-header");
header("Access-Control-Expose-Headers: X-Custom-header");
header("X-Custom-header: $some data");
```

Then on front end this worked fine:
```
this._http.get(url, options).toPromise()
            .then(res => {
                var data = res.headers.get('X-Custom-header');
                console.log(data);
                return res;
            })
```

**Comment by amin-RFarzin** [comment]
The trick is to use "Access-Control-Expose-Headers"
(e.g., <response-header name="Access-Control-Expose-Headers" header-name="Access-Control-Expose-Headers" header-value="accept, authorization, content-type, x-requested-with, jwt"/>)

**Comment by rmunozfu** [comment]
The explication about this problem is here.
[](https://developer.mozilla.org/es/docs/Web/HTTP/Headers/Access-Control-Expose-Headers)

**Comment by ymallikreddy521** [comment]
Hi.

Fixed by adding below code in webapi controller.
  returnValue.Content.Headers.Add("x-filename", "File.doc");
                    returnValue.Content.Headers.Add("access-control-expose-headers", new[] { "x-filename" });

**Comment by shivarajnaidu** [comment]
How can i get the full response object...?
```js
 this.http.get(url, options)
  .toPromise()
  .then(data => {
     console.log(data) // getting response body but not response object with headers and body
   })
```

**Comment by trotyl** [comment]
@shivarajnaidu https://angular.io/guide/http#reading-the-full-response

```typescript
this.http.xxx(url, { observe: 'response' })
```

**Comment by bhupal4all** [comment]
How Can I read Response Header (Content-Disposition)? 

When I check at either Postman or Google Chrome Network tab, I can see 'Content-Disposition' at the response headers section, but able to read at Angular Code.

```
// Node - Server JS
app.get('/download', function (req, res) {
  var file = __dirname + '/db.json';
  res.setHeader("Content-Disposition",'attachment; filename=' + req.body.filename);
  res.set({
    'Content-Type': 'text/plain',
    'Content-Disposition': 'download-file.json'
  })
  res.download(file); // Set disposition and send it.
});


// Angular5 Code

 saveFile() {
    const headers = new Headers();
    headers.append('Accept', 'text/plain');
    this.http.get('http://localhost:8090/download', { headers: headers })
      .subscribe(
        (response => this.saveToFileSystem(response))
      );
  }

  private saveToFileSystem(response) {
    const contentDispositionHeader: string = response.headers.get('Content-Disposition'); // <== Getting error here, Not able to read Response Headers
    const parts: string[] = contentDispositionHeader.split(';');
    const filename = parts[1].split('=')[1];
    const blob = new Blob([response._body], { type: 'text/plain' });
    saveAs(blob, filename);
  }

```

**Comment by bhupal4all** [comment]
Thanks @trotyl , I set 'Access-Control-Expose-Headers' at Node Js Server and am able to read 'Content-Disposition' at Angular code.

**Comment by rsbrum** [comment]
In case there still is someone having trouble with this, I'll leave my solution for both the backend and frontend. 

Heres how you set the headers: https://github.com/rsbrum/NodeJS-RESTAPI-JWTAuth/blob/master/jwt-auth.js

Heres how you access the header on the client side: https://github.com/rsbrum/Angular6-JWT-Auth/blob/master/src/app/shared/interceptor/interceptor.service.ts

**Comment by bhumin3i** [comment]
i'm getting error while send x-auth-token in header.

  if (token != ''){
            
              this.global.headerData['x-access-token'] = token; //allow get data from server 
  this.global.headerData['x-auth-token'] = token; //this is not allow give me error **Response with status: 0 for URL: null**
            } 
              
            let headers = new Headers(this.global.headerData);
            let options = new RequestOptions({ headers: headers });

**Comment by santiagomolinadecastro** [comment]
I have the same problema. I'm invoking an Identity Server service and i hope that it return Authorization header. This header is coming ok but from JavaScript when i make getAllResponseHeaders i can't get it.

Then, i found this topic and reading it, i tried send Expose-Headers:

req.setRequestHeader('Access-Control-Expose-Headers', 'Authorization');

But i get the same result: 

"pragma: no-cache
cache-control: no-cache, no-store, max-age=0, must-revalidate
expires: 0
"

It not returns authorization header. Can you helpme with another idea?

Thanks!!

**Comment by trotyl** [comment]
@santiagomolinadecastro `Access-Control-Expose-Headers` is a response header, not request header. It must be set on the same response of where `Authorization` is.

**Comment by santiagomolinadecastro** [comment]
Thanks for your help @trotyl

**Comment by santiagomolinadecastro** [comment]
The question is. Why i can see the header in my browser (in network section) and i can't see this header in my JavaScript code? The service returns that header but from JavaScript i can't get it. The question is, Why?

**Comment by trotyl** [comment]
@santiagomolinadecastro Because Web is secure, same reason for why I cannot get HTTP-only cookie in JavaScript.

**Comment by santiagomolinadecastro** [comment]
@trotyl thanks!!!

**Comment by bhuvizerobug** [comment]
Expected to form you a next to no word to thank you once more with respect
to the decent recommendations you have contributed here.
It has been simply incredibly generous with you to provide openly
what exactly many individuals would’ve marketed for an eBook to end
up making some cash for their end, primarily given that you could
have tried it in the event you wanted.
Visit Us: http://www.zerobugacademy.com/angularjs-training-in-chennai

**Comment by Waseem-farooqui** [comment]
In my case in the `POST` response I want to have the `authorization header` because I was having the `JWT Token` in it.
So what I read from [this][1] post is the header I we want should be added as an `Expose Header` from the back-end.
So what I did was added the `Authorization` header to my **Exposed Header** like this in my `filter class`.

    response.addHeader("Access-Control-Expose-Headers", "Authorization");
    response.addHeader("Access-Control-Allow-Headers", "Authorization, X-PINGOTHER, Origin, X-Requested-With, Content-Type, Accept, X-Custom-header");
    response.addHeader(HEADER_STRING, TOKEN_PREFIX + token); // HEADER_STRING == Authorization

And at my Angular Side

In the Component.

    this.authenticationService.login(this.f.email.value, this.f.password.value)
      .pipe(first())
      .subscribe(
        (data: HttpResponse<any>) => {
          console.log(data.headers.get('authorization'));
        },
        error => {
          this.loading = false;
        });
At my Service Side.

    return this.http.post<any>(Constants.BASE_URL + 'login', {username: username, password: password},
      {observe: 'response' as 'body'})
      .pipe(map(user => {
           return user;
      }));


  [1]: https://github.com/angular/angular/issues/5237#issuecomment-239174349

**Comment by meitix** [comment]
> 
> 
> @pkozlowski-opensource Exactly, this is not an Angular issue. Is an API problem. With the header `'access-control-expose-headers' : 'name-of-expose-header'` works fine.
> 
> The problem is that this doesn't work with the header `'access-control-expose-headers' : '*'`. You can't use `*` and you have to put explicity the name of the headers that you want to expose.

it's working, god after 2 fucking days, just for the fucking header

**Comment by bhumin3i** [comment]
@meitix @pkozlowski-opensource  correct brother this is API problem.

**Comment by gabhiiaf93** [comment]
I have got a fix,
try adding 
{
  "/api/v1/login": {
    "target": "http://localhost:8000/api/v1/login",
    "secure": false,
    "logLevel": "debug",
    "changeOrigin": "true"
  }
}
 in proxy.config.json and add the proxy config in the angular.json.
try running the application now and you will get the cookies if you have set cookie in the response headers

**Comment by nhhockeyplayer** [comment]
meitix 
please fix your language before you fix typescript

**Comment by kofindien** [comment]
API (Node Js):
    res.header("access-control-expose-headers", "name-of-expose-header");
    res.setHeader('name-of-expose-header', "your-value");
Frontend(Angular):
    response.headers.get('name-of-expose-header')

Ex:  You can replace name-of-expose-header by etag.
