### ISSUE TITLE
NgFor seems confused when the underlying array contains identical references

### ISSUE THREAD

**Issue by qkjerome** [angular/angular#5238]
We are encountering an issue with NgFor when the array we iterate over contains multiple times the same object reference and is being modified after an event raised by a sub-component.

I believe that I re-created the scenario here: http://plnkr.co/edit/cwIBif0pHY60u3Qbmv8x?p=preview Please try to change the selection in the first select. 

From my point of view, what seems to happen is NgFor somehow updating the wrong sub-component when two elements in the iterable are pointing to the same object and the first one is being replaced to point to something else.

context: Angular2 alpha 45 / typescript 1.6.2

**Comment by qkjerome** [comment]
updater plunker to no longer crash on firefox: http://plnkr.co/edit/cwIBif0pHY60u3Qbmv8x?p=preview

**Comment by pkozlowski-opensource** [comment]
I guess you need to use `trackBy`: https://angular.io/docs/ts/latest/api/core/index/TrackByFn-interface.html
