### ISSUE TITLE
Validator is executed before pipes are run causing validation errors on correct data and correct regex.

### ISSUE THREAD

**Issue by arizon-dread** [angular/angular#52396]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

When using (somewhat simplified, see stackblitz for an example that demonstrates it more elaborately)
```
<form [formGroup]="accountingFg">
   <input formControlName="amount" pattern="^-?\d{1,3}( \d{3})*(\.[0-9]{2})?$" [value]="accountingFg.get('amount')?.value.toString() | customPipe" />
</form>
```

Where the pipe manipulates the content to be according to a specific format, the validator runs before the pipe, which makes the validator validate a value that is not yet manipulated into the correct format (see stackblitz link).

As I see it, pipes and validators are an integral part of angular and it is not unreasonable to suggest that they should be run in such an order that the validation occurs after the value has been manipulated in the pipe, or am I at fault here?

![image (7)](https://github.com/angular/angular/assets/24667970/4e80056c-a856-411b-89da-743b9039d9a0)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-umgsce?devToolsHeight=33&file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
pattern:
{requiredPattern: '/^-?\\d{1,3}( \\d{3})*(\\.[0-9]{2})?$/', actualValue: '5 5555'}
actualValue:
'5 5555'
requiredPattern:
'/^-?\\d{1,3}( \\d{3})*(\\.[0-9]{2})?$/'
---
The pipe will correct the format of the digits to the correct format: 55 555. However, the validator runs before the pipe.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.3
Node: 18.16.0
Package Manager: npm 9.5.1
OS: linux x64

Angular: 16.2.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.3
@angular-devkit/build-angular   16.2.3
@angular-devkit/core            16.2.3
@angular-devkit/schematics      16.2.3
@angular/cdk                    16.2.5
@angular/cli                    16.2.3
@angular/material               16.2.5
@schematics/angular             16.2.3
rxjs                            7.5.7
typescript                      4.9.5
zone.js                         0.13.3
```

### Anything else?

I was able to work around this with a more forgiving regex, which however, is not actually correct to the format I really want to have. As the pipe manipulates the format, it is forgivable in this case, but one of my main issues with this is that it was very hard to find. My initial impression was that the implementation of the regex in the validator was buggy since the regex worked fine on regex101.com and regexr.com with my test input data, however, the "error" was in fact the order in which pipe and validator is run. 

I don't fully understand what you mean by "Is this a regression" so I might have answered it incorrectly.

Please don't suggest using the currencyPipe, it completely crapped the bed when setting it to SEK and the spaces used in swedish locale for thousand delimiters. The currencyPipe was my initial idea for this but I decided to abandon it because it just didn't work.

**Comment by JoostK** [comment]
This is mixing reactive forms with setting a value declaratively from the template. The `[value]` binding is a raw DOM value binding, which is fighting with the value that is stored in the `FormControl`. The validation result is driven by the form control's value, _not_ the DOM input's value.

The `value` binding in the template is effectively conflicting with the binding from the form control. With reactive forms, you'll have to update the form state by updating the reactive form controls.

**Comment by arizon-dread** [comment]
Thanks @JoostK for your insights.
I removed the `[value]` binding and added this in the ngOnInit lifecycle hook instead:
```
this.accountingFg.controls['amount'].valueChanges.pipe(takeUntilDestroyed(this.destroyRef)).pipe(distinctUntilChanged()).subscribe((value) => {
      this.accountingFg.controls['amount'].patchValue(this.comma2dot.transform(this.thousandSeparatorPipe.transform(value)), {emitEvent: false});
      this.accountingFg.controls['amount'].updateValueAndValidity();
    });
```

Which seems to be working with the correct regex. I'm leaving this here in case somebody else stumbles across this.
