### ISSUE TITLE
non-JS module files deprecated. 

### ISSUE THREAD

**Issue by Gregoire75017** [angular/angular#52391]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Hello,

I just create a angular project with ng new testProject, go in the project, and launch the project with ng serve, and I had this error : crbug/1173575, non-JS module files deprecated.

I have this error, with all my projects angular and Ionic.

So I created testProject, just to check, and even if did not import any package, or write any code, I have this error.

And I am tring to understand, why it s working when I do ng serve --host 127.0.0.1

I know I put a issue on it yesterday, but the given solution did not work, or I did not do something right. 

I really sorry to insist, but on my collegues computers, everything work. And the last time I had this error, I needed to reboot my computer after spent 1 week to try to solve this. I really do not want to do this again ! 

Thanks !!
<img width="954" alt="cd53ce40-650f-48e9-bde7-4398e84f2397" src="https://github.com/angular/angular/assets/84898809/2dca0264-625d-49ba-b02d-0abb4096e782">
<img width="1280" alt="Capture d'écran 2023-10-26 103611" src="https://github.com/angular/angular/assets/84898809/a9cb1914-2c44-425b-a24a-6ca91b9762df">

### Please provide the exception or error you saw

```true
crbug/1173575, non-JS module files deprecated.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.7
Node: 18.17.1
Package Manager: npm 10.2.0
OS: win32 x64

Angular: 16.2.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.7
@angular-devkit/build-angular   16.2.7
@angular-devkit/core            16.2.7
@angular-devkit/schematics      16.2.7
@angular/cli                    16.2.7
@schematics/angular             16.2.7
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
```

### Anything else?

I am chrome, but I tried on other browser, still got the same error...

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

Please see [this StackOverflow question](https://stackoverflow.com/questions/67191286/crbug-1173575-non-js-module-files-deprecated-chromewebdata-index%EA%9E%89530595551) for possible solutions.
