### ISSUE TITLE
:host-context in ViewEncapsulation.Emulated translates to invalid css

### ISSUE THREAD

**Issue by Necroskillz** [angular/angular#5239]
See http://plnkr.co/edit/axV1SxuBNydCf3BK82kx?p=preview

A component using `:host-context` in `styles` property renders css like this:
```
[_nghost-txm-2]div span, div [_nghost-txm-2] span {
    color: red;
}
```

The first selector is invalid, so the whole definition doesn't do anything.

**Comment by Necroskillz** [comment]
This is still an issue in alpha.46

**Comment by tbosch** [comment]
Yes,
this does not work right now if the selector contains an element name.
However, it does work if the selector only contains attributes / class names.

See e.g. http://plnkr.co/edit/zLZNfvJhkC170EQct6op?p=preview

**Comment by vicb** [comment]
fixed
