### ISSUE TITLE
Wrong peerDependencies resolution when installing Angular 16.2.10 and 16.2.11

### ISSUE THREAD

**Issue by mlc-mlapis** [angular/angular#52406]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Starting with Angular 16.2.10 (also confirmed in 16.2.11), some problems with peer dependencies have been appearing.

### Please provide the exception or error you saw

```
npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: zerops@1.8.12
npm ERR! Found: @angular/animations@16.2.9
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"16.2.11" from the root project
npm ERR!   peer @angular/animations@"^16.0.0 || ^17.0.0" from @angular/material@16.2.10
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"16.2.10" from the root project
npm ERR!   2 more (@angular/platform-browser, @zerops/project-diagram)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @angular/animations@"16.2.11" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/core@16.2.11
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"16.2.11" from @angular/animations@16.2.11
npm ERR!   node_modules/@angular/animations
npm ERR!     @angular/animations@"16.2.11" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```
Angular: 16.2.9
Node   : 18.18.2
OS     : Windows x64 / Ubuntu 20.04.6 LTS
npm    : 9.8.1
```

**Comment by JoostK** [comment]
I don't have sufficient insight into your project (`zerops` is not a package available on NPM) to really tell what's going on, but this is unlikely to be a problem with Angular's package versions. I'd recommend wiping your lockfile to reinstall from scratch,

Notably, this line indicates that you request `@angular/animations@16.2.11` in your `package.json`, while `zerops` appears to be pulling in `16.2.9`. Looking at [`@zerops/project-diagram`](https://unpkg.com/browse/@zerops/project-diagram@0.1.1/package.json) which _is_ available on NPM it requests a dependency (not a peer dependency, which it should be) of `^16.2.9`, i.e. the installed version 16.2.11 does satisfy that range so NPM should be able to resolve this tree. I don't have insight into `zerops` though, perhaps that's where the problem originates.

Anyway, without a full reproduction this is not actionable for us. I'll close for now but feel free to comment with additional insights and I can reopen if needed.
