### ISSUE TITLE
Event handling intercepted

### ISSUE THREAD

**Issue by princemaple** [angular/angular#52412]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

I have something like this:

```
<input ... /> Pure text input, can be input or textarea

<image-upload (document:paste)="canPaste && handlePaste($event) ... />
```

This has been working fine for a long time. Recently (within a few weeks) it started to intercept event bubbling when `canPaste` is false. So `Ctrl+V` / `Right click + Paste` in text input stopped working, simply got ignored.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-izh8md?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
Pasting into the text input does nothing.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.8
Node: 18.18.1
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 16.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.8
@angular-devkit/build-angular   16.2.8
@angular-devkit/core            16.2.8
@angular-devkit/schematics      16.2.8
@angular/cdk                    16.2.10
@angular/cli                    16.2.8
@angular/material               16.2.10
@schematics/angular             16.2.8
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
```

### Anything else?

Of course this can be worked around by moving the condition check into the `handlePaste` method.

I did an `ng update` after discovering the issue, so the real issue might be introduced a couple patch release earlier.

I hope this is not a case of Mandela Effect... Did it use to work, or not :) ??

**Comment by JoostK** [comment]
Which version was being used that you think it still worked? The current behavior seems to make sense to me.

**Comment by princemaple** [comment]
Hmm, I went back to 16.0.0 on stackblitz and it still didn't work. 2 of my users immediately caught this bug after I pushed out a new version, so I thought it must be in a recent angular version bump. Otherwise I'd have been told about it much earlier.

Now I'm not sure.
