### ISSUE TITLE
Allow @ContentChildren to be filled by subviews

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#5241]
#3922 contains the sentence `Both query mechanisms do not go into further into component subviews.`, but I would like that to be available.

I have grouped a couple of `[router-link]` and want to decide in a parent element if any of those links `isRouteActive`. However, not all those links are built directly within the component, but some are built up dynamically by separate components (after doing a HTTP request). Right now, the `QueryList` remains empty and doesn't have any observable changes in those cases.

Here is what I'm doing now

```typescript
@Directive({
    selector: '[parent-is-route-active]',
    host: {'[class.router-link-active]': 'isRouteActive'}
})
export class ParentIsRouteActive implements AfterContentChecked {
    public isRouteActive: boolean;

    @ContentChildren(RouterLink, { descendants: true }) routerLinks: QueryList<RouterLink>;

    constructor(router: Router) {
        router.subscribe((x) => this.routeChanged(x));
    }

    public afterContentChecked() {
        ObservableWrapper.subscribe(this.routerLinks.changes, (_) => {
            console.log("change detected");
        });
    }

    private routeChanged(x: string) {
        var activeRoutes = this.routerLinks.filter(x=> x.isRouteActive);
        this.isRouteActive = activeRoutes.length > 0;
    }
}
```

**Comment by mhevery** [comment]
This is by design, since we view the implementation of any one component as opaque, and we don't want to leak its inner implementation to the outside world. (There would also be a performance penalty for what you are asking)

Could you chose a different mechanism of achieving your goal?

My initial thought is that we don't want to support this.

**Comment by Tragetaschen** [comment]
Right now, I have slightly enlarged the scope of the inner component to include the outer, collecting element. That way I can use `@ContentChildren` as expected. But that means I didn't split the components where I thought it would make sense :)

I, too, don't want to know any implementation detail of the inner component, but `RouterLink` is known to both and reflecting over it's mere existence anywhere down the tree doesn't mean any implementation detail is exposed. For example I wouldn't want to know which component exactly used that directive.

It has only been a two-week journey in angular2 for me yet, but couldn't DI be used to intercept the creation of `RouterLink`s in child components and replace those by a proxy that registers/deregisters their existence on construction/destruction at the "root"?

**Comment by vicb** [comment]
You can use `@ContentChildren(..., {descendants: true})`
