### ISSUE TITLE
HttpClient: when using 'Authorization': 'Basic user:password' header with responseType: 'text', it doesn't work

### ISSUE THREAD

**Issue by dminovski0** [angular/angular#52428]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

When I send a request to a website's HTML page with:
```
const httpOptions = {
  headers: new HttpHeaders({
    'Authorization': 'Basic ' + btoa('username:password')
  }),
  withCredentials: true
};
this.http.get(url, httpOptions).subscribe();
```

The authorization works, but it returns an error:
`error: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON at JSON.parse`

I need to get authorized on the website, and it doesn't return a JSON response. With the above code, the error needs to be caught with catchError(), and it can work.

Adding responseType: 'text' to not catch the error shows another error:
`401 (Unauthorized)`
I can't get authorized.

### Please provide the exception or error you saw

```true
The error is `401 (Unauthorized)`.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 15.2.9
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.8
@angular-devkit/build-angular   15.2.8
@angular-devkit/core            15.2.8
@angular-devkit/schematics      15.2.8
@angular/cli                    15.2.8
@schematics/angular             15.2.8
rxjs                            6.6.7
typescript                      4.9.5
```

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).

Ps: You need to change the response type to `text`.

**Comment by dminovski0** [comment]
@JeanMeche When I change the responseType to `text`, then it doesn't authorize. WIthout it, it does, but then it returns the error with the syntax. I can catch that error in catchError(), but it seems like a workaround.

**Comment by dminovski0** [comment]
@JeanMeche 
I tried with `fetch`

```
const response = await fetch(loginUrl, {
  headers: {
    'Authorization': 'Basic ' + btoa('username:password')
  },
  credentials: 'include'
})
let res = await response.text();
```
And it works. It seems that in Angular, using `responseType` affects the `withCredentials` parameter or some other part of the request.

**Comment by JeanMeche** [comment]
Just to be sure, can you give us the call you used with the HttpClient + text responseType  ?

**Comment by dminovski0** [comment]
The code that shows 401 Unauthorized is:

```
const httpOptions = {
headers: new HttpHeaders({
  'Authorization': 'Basic ' + btoa('username:password')
}),
withCredentials: true
responseType: 'text'
}

return this.http.get(url, httpOptions);
```

By removing the `responseType` parameter, then authorizes, but expects a JSON and I catch that error with:

```
let res = this.http.get(l, httpOptions).pipe(
catchError((err) => {
  if (err.status === 200) {

  } else {
    
  }
  return of();
})).subscribe((data) => {

  });
```

**Comment by JeanMeche** [comment]
Could you compare the outgoing request in the devtools. 
How are they different depending on the `responseType` ?

**Comment by dminovski0** [comment]
With `responseType`, in the Dev Tools -> Request Headers, the Authorization is Bearer and it has a longer string. Without it, Authorization is Basic with a shorter string.

**Comment by dminovski0** [comment]
@JeanMeche There is interceptor in the code that changes the Authorization type, it's not from Angular.
