### ISSUE TITLE
don't allow arbitrary ES6 APIs usage

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#5242]
Right now we use eg. `string.startsWith` in our code. This requires that users include an ES6 polyfill library like es6-shim when running Angular.
We should avoid adding more of these. We can hand-write a typings file describing the APIs we use already, but not type-check against all of `es6-shim.d.ts`, which gives us too broad a surface to target at runtime.

**Comment by pkozlowski-opensource** [comment]
+1

**Comment by rkirov** [comment]
+1 es6 feature usage should be monitored (as it has implications for ie9 users etc, that we agreed to support) and a custom d.ts would allow us to track those easily.

**Comment by vicb** [comment]
On the other hand wouldn't that penalize newer browsers as they would have to include unrequired polyfills/facades ?

**Comment by ewinslow** [comment]
+1 to vicb comment. If you need the functionality, you might as well provide the shim yourself?

**Comment by alexeagle** [comment]
If the user targets a runtime where more APIs are available, they can bring
typings for those.
But Angular's usage of these APIs forces all users to target such
environments or shim the behavior.
I think Rado knows better why we don't just bundle es6-shim with angular...

**Comment by mhevery** [comment]
+1 for not using ES6 features in angular. User can always decide, but we should not force.

**Comment by ewinslow** [comment]
I guess I'm not clear on the alternative. Provide custom implementations? Doesn't that bloat the source size just as much as shimming?

**Comment by alexeagle** [comment]
Just don't use the new APIs. Note that we can use ES6 syntax that
TypeScript de-sugars, just not things that require runtime shims. Evan, is
there a particular API you think we should be using?

**Comment by ewinslow** [comment]
I'm OK with whatever as long as we don't bloat the source size for folks that don't need the old browser support.

**Comment by evmar** [comment]
This bug is closed, but es6-subset.d.ts still exists:
https://github.com/angular/angular/blob/master/modules/es6-subset.d.ts

If this bug is fixed, shouldn't this file go away?

**Comment by alexeagle** [comment]
Discussed with @IgorMinar  this morning. His preference is for Angular to take a dependency on all of ES6, with the observation that users can be responsible for polyfills of anything not in the target browser. But g3 users don't get all those polyfills for free with Closure Compiler, and in fact I believe that Angular 2.0.0 already fails in old browsers because of missing String#startsWith,endsWith etc.

@mhevery has said that we should avoid requiring ES6 shims other than promise and collections. My view is that it makes it harder for them to ship small apps (esp. because the polyfills are probably not tree-shaken by rollup/webpack2? @robwormald can confirm?)

**Comment by evmar** [comment]
Array.find in es6-subset.d.ts returns a T, while in the TypeScript definition it returns T|undefined.
This definition bled into a Google3 build and led to me puzzling over some code that shouldn't have compiled (it failed to check the return value of find).

**Comment by robwormald** [comment]
@alexeagle correct, in general tools see polyfill files as one gigantic side-effect

**Comment by alexeagle** [comment]
So I believe the best fix would be to remove `es6-subset.d.ts` and use ES5 APIs in angular. Of course this would have to be non-breaking change and should not increase the binary size/performance noticeably.
I'm already doing similar work to remove some facade methods so this is a good time to do it.

**Comment by DzmitryShylovich** [comment]
Is this still relevant?`Object`.keys` is everywhere, for example.

**Comment by alexeagle** [comment]
Still relevant. The question is, which es6 polyfills are mandatory? Equivalently, which browser/versions are supported without polyfills?

**Comment by IgorMinar** [comment]
this is no longer relevant.
