### ISSUE TITLE
IE11 method keys issue

### ISSUE THREAD

**Issue by selten** [angular/angular#5243]
Internet Explorer 9-11
Method keys aren't supported by this object
angular2.dev.js
if ((new exports.Map()).keys().next) {

```
SCRIPT438: De eigenschap of methode keys wordt niet ondersteund door dit object
angular2.dev.js (4025,5)
```

**Comment by ericmartinezr** [comment]
Hey @selten you must include `es6-shim` in your project , see https://github.com/angular/angular/issues/4997

**Comment by pkozlowski-opensource** [comment]
@ericmartinezr is right. In the future we are going to better monitor usage of ES6-specific APIs, see #5242
