### ISSUE TITLE
Router min bundle is not being distributed

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular#5244]
As you can see here [code angular a46](https://code.angularjs.org/2.0.0-alpha.46/) there's no minified bundle of router, nor using npm, while it was in [code angular a45](https://code.angularjs.org/2.0.0-alpha.45/) (`router.dev.min.js`).

I've ran both `build.js` and `bundles.js` against the latest master and router.min.js is created under `build/` folder and it's alone there, while everything else is under `bundle/`. 

I tried tracking the building process in gulpfile but I got lost easily, lol.

Is this intentional?

**Comment by pkozlowski-opensource** [comment]
Yeh, this is a side effect of my re-organization of the bundle-creation logic. Sent the PR #5253 to fix it.

**Comment by ericmartinezr** [comment]
Thanks :+1:
