### ISSUE TITLE
Feature(language-service): new control flow syntax colouring

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#52443]
### Which @angular/* package(s) are relevant/related to the feature request?

language-service

### Description

It would be awesome to have "colouring" of new control flow syntax like when you have regular code in typescript.

Right now it looks like plain text, and it kinda melts together.

Great work anyway :)

### Proposed solution

colouring of "keywords" (@if, @for, @switch, @defer)
colouring of "variables"
colouring of method invocations

use colouring depending of used theme in vscode :), just like in typescript.

### Alternatives considered

or any colouring that would at least make some visual comfort for developer.

**Comment by JoostK** [comment]
This has already been done in angular/vscode-ng-language-service#1926, pending a release of the v17 VSCode plugin.
