### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedException does not contain the binding when used with Dart transformers

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#5245]
ExpressionChangedAfterItHasBeenCheckedException should contain the binding that caused a problem. It should also contain the component name which template contains the binding.

This works in JS (dynamic/jit) and Dart (dynamic).

**Comment by kegluneq** [comment]
@tbosch 

This is a mismatch between how change detectors are being configured in TS vs Dart.

- [In TS](https://github.com/angular/angular/blob/master/modules/angular2/src/compiler/compiler.ts#L32), `genDebugInfo` is always `true` (the third parameter)
- [In Dart](https://github.com/angular/angular/blob/master/modules_dart/transform/lib/src/transform/template_compiler/generator.dart#L50), `genDebugInfo` is always `false`

Should these both be set to `assertionsEnabled()`?

**Comment by kegluneq** [comment]
Whoops, silly non-named parameters -- it looks like `genDebugInfo` is set to `assertionsEnabled()` in both languages.

Are you certain this is not working when `assertionsEnabled()` returns true? If it is still failing, please provide repro instructions so I can investigate further.
