### ISSUE TITLE
Implementing Dynamic Theme Colors via SCSS Variables

### ISSUE THREAD

**Issue by asadakkhan** [angular/angular#52467]
common

### Description

I set up a global style scss root color.I wish to modify our ts file's style scss variable. I want to avoid adding any inline styles to the project.
The backend api decides the theme color. 
Which methods work best for doing that?
I would like to use a SCSS variable to add many themes.

Our project requires dynamic theming based on backend API responses. The theme color is determined by the API and needs to be reflected across the application's styles without using inline styles.

### Proposed solution

Implement a system where SCSS variables are used to define the root color of the application. These variables should be dynamically updated based on the backend API's response, allowing seamless theming throughout the project without the need for inline styles.

### Alternatives considered

Global SCSS Variable: Set up a global SCSS variable for the root color that can be easily modified.
Dynamic Theme Switching: Implement a mechanism to update the global SCSS variable dynamically based on the theme color received from the backend API.
Avoiding Inline Styles: Ensure that no inline styles are added to the project to maintain a clean and maintainable codebase.
Multiple Themes: Design the system in a way that allows for easy addition of multiple themes, each with its unique color scheme, using SCSS variables.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
