### ISSUE TITLE
Implementing Dynamic Theme Colors via SCSS Variables

### ISSUE THREAD

**Issue by asadakkhan** [angular/angular#52469]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

Our project requires dynamic theming based on backend API responses. The theme color is determined by the API and needs to be reflected across the application's styles without resorting to inline styles.

Global SCSS Variable: Set up a global SCSS variable for the root color that can be easily modified.
Dynamic Theme Switching: Implement a mechanism to update the global SCSS variable dynamically based on the theme color received from the backend API.
Avoiding Inline Styles: Ensure that no inline styles are added to the project to maintain a clean and maintainable codebase.
Multiple Themes: Design the system in a way that allows for easy addition of multiple themes, each with its unique color scheme, using SCSS variables.

**Comment by JoostK** [comment]
This is outside the scope of the framework, as well as duplicating #52467.
