### ISSUE TITLE
i18n: documentation clarification on what is the plural placeholder/interpolation word should be

### ISSUE THREAD

**Issue by sroucheray** [angular/angular#52471]
### Describe the problem that you experienced

There seems to be two ways to indicate the value to use in plural forms.
One is by using an interpolation as indicated in [this documentation](https://v12.angular.io/guide/i18n-common-prepare#mark-plurals):
![image](https://github.com/angular/angular/assets/169818/a32735af-d158-413e-ab5c-b3591480b29f)

the other is to use the `#` character as indicated in [this documentation](https://angular.io/api/common/I18nPluralPipe):
![image](https://github.com/angular/angular/assets/169818/72b5715b-4fcf-4228-b8a2-aff1af09bcb7)

I18n is hard enough that, IMHO, there should be at least a clarification on what we should use in what condition and if both forms are interchangeable.

**Comment by davideTheCap** [comment]
In my understanding, the first format is inline interpolation whereas, the second one is applying the i18nPluralPipe and is not really related to the #. The # is part of the outcoming message for case '_other_' meaning a generic number. --> # other
As the example in the [pipe documentation](https://angular.io/api/common/I18nPluralPipe) states:
`{{ value_expression | i18nPlural : pluralMap [ : locale ] }}`
pluralMap is the map you provide to the pipe as in the below example messageMapping is.

The only option I see to make it clearer is to avoid the inline interpolation of the first example and use always the map as in the second.
Nevertheless, I also find it useful, to have specified somewhere how the inline interpolation works with an example.

**Comment by JeanMeche** [comment]
As Davide said, those 2 differents ways to handle plural in angular : Using interpolation only with an ICU expression and using a `I18nPluralPipe ` which takes a pluralMap that can be defined in js/ts. 

They are complementary.
