### ISSUE TITLE
Implementing Dynamic Theme Color #52469

### ISSUE THREAD

**Issue by asadakkhan** [angular/angular#52470]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

Yes

Description
Our project requires dynamic theming based on backend API responses. The theme color is determined by the API and needs to be reflected across the application's styles without resorting to inline styles.

Global SCSS Variable: Set up a global SCSS variable for the root color that can be easily modified.
Dynamic Theme Switching: Implement a mechanism to update the global SCSS variable dynamically based on the theme color received from the backend API.
Avoiding Inline Styles: Ensure that no inline styles are added to the project to maintain a clean and maintainable codebase.
Multiple Themes: Design the system in a way that allows for easy addition of multiple themes, each with its unique color scheme, using SCSS variables.

Please provide a link to a minimal reproduction of the bug
No response

Please provide the exception or error you saw
No response

Please provide the environment you discovered this bug in (run ng version)
No response

Anything else?
No response

**Comment by JoostK** [comment]
I am sorry but this is not the right place for this request, as mentioned in the other two issues.
