### ISSUE TITLE
Integration with Protractor. Need to expose Protractor Testing API.

### ISSUE THREAD

**Issue by mhevery** [angular/angular#525]

**Comment by juliemr** [comment]
[] Provide a way for Protractor to know when the application is stable (no pending requests or promises)
[] Provide a testability API that exposes useful ways of finding elements (to be compatible with existing Protractor, this would be by model and by binding, but we should rethink what the best options are for Angular 2)

[] Decide whether Angular 2 should be compatible with Protractor as it exists now, or whether we should create a new branch of Protractor for it

**Comment by mhevery** [comment]
@juliemr Please, can you update the status of this issues.

**Comment by juliemr** [comment]
In progress - see the work in progress pr https://github.com/angular/angular/pull/726

**Comment by naomiblack** [comment]
@juliemr can you spin off smaller issues from this that we can assign to upcoming milestones? This is too big a chunk to triage and assign.

**Comment by juliemr** [comment]
Done - issues linked above, and I'm removing the milestone.

**Comment by siddharthjain210** [comment]
I want to integrate protractor in my application. Is there any help guide that can help me setting up protractor?
Also i need to know whether phantomjs would work with protractor for angular2 application?

**Comment by naomiblack** [comment]
obsolete. actual work has sub-issues filed.
