### ISSUE TITLE
Local template variables requires event to trigger change detection.

### ISSUE THREAD

**Issue by jamcoupe** [angular/angular#5250]
In order to get this example to work I had to add `(change)="null"` to the checkbox input. As this is [expected behaviour](https://github.com/angular/angular/issues/992) should `<input (change) />` be valid?

Currently we have to do the following to get this example to work:
```
@Component({
    selector: 'login',
    template: `
        <input value="pass" [type]="show.checked ? 'text' : 'password'"/>
        <input type="checkbox" #show (change)="null" />
    `
})
export class LoginComponent {}
```

Would it be possible in the future to get rid of the `="null"` part so the above would become:
```
@Component({
    selector: 'login',
    template: `
        <input value="pass" [type]="show.checked ? 'text' : 'password'"/>
        <input type="checkbox" #show (change) />
    `
})
export class LoginComponent {}
```

**Comment by pkozlowski-opensource** [comment]
> Would it be possible in the future to get rid of the ="null" part

Nope. We should probably also make `(change)="null"` an error.

The problem with your approach is that you are trying to read DOM properties (`show.checked`) on each change detection. This is slow and not very angular-like where we are supposed to work off the model, not the DOM.

One possible solution would be:

```html
<input value="pass" [type]="show ? 'text' : 'password'"/>
<input type="checkbox" (change)="show = $event.target.checked" />
```

Another option is to simply use `ng-model`.
