### ISSUE TITLE
rename recommended-devcontainer.json in devcontainer.json in repo

### ISSUE THREAD

**Issue by trukhinyuri** [angular/angular#52509]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Need rename recommended-devcontainer.json in devcontainer.json in repo. recommended–devcontainer is not valid file.
Users cant build devcontainer from repo without it in IntelliJ IDEA 2023.3 and another IDEs!
https://containers.dev/implementors/spec/

[devcontainer.json](https://containers.dev/implementors/spec/#devcontainerjson)
While the structure of this metadata is critical, it is also important to call out how this data can be represented on disk where appropriate. While other representations may be added over time, metadata can be stored in a JSON with Comments file called devcontainer.json today. Products using it should expect to find a devcontainer.json file in one or more of the following locations (in order of precedence):

.devcontainer/devcontainer.json
.devcontainer.json
.devcontainer/<folder>/devcontainer.json (where <folder> is a sub-folder, one level deep)
It is valid that these files may exist in more than one location, so consider providing a mechanism for users to select one when appropriate.

### Please provide a link to a minimal reproduction of the bug

https://github.com/angular/angular/blob/main/.devcontainer/recommended-Dockerfile

### Please provide the exception or error you saw

```true
Need rename recommended-devcontainer.json in devcontainer.json in repo. recommended–devcontainer is not valid file.
Users cant build devcontainer from repo without it in IntelliJ IDEA 2023.3 and another IDEs!
https://containers.dev/implementors/spec/

[devcontainer.json](https://containers.dev/implementors/spec/#devcontainerjson)
While the structure of this metadata is critical, it is also important to call out how this data can be represented on disk where appropriate. While other representations may be added over time, metadata can be stored in a JSON with Comments file called devcontainer.json today. Products using it should expect to find a devcontainer.json file in one or more of the following locations (in order of precedence):

.devcontainer/devcontainer.json
.devcontainer.json
.devcontainer/<folder>/devcontainer.json (where <folder> is a sub-folder, one level deep)
It is valid that these files may exist in more than one location, so consider providing a mechanism for users to select one when appropriate.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Need rename recommended-devcontainer.json in devcontainer.json in repo. recommended–devcontainer is not valid file.
Users cant build devcontainer from repo without it in IntelliJ IDEA 2023.3 and another IDEs!
https://containers.dev/implementors/spec/

[devcontainer.json](https://containers.dev/implementors/spec/#devcontainerjson)
While the structure of this metadata is critical, it is also important to call out how this data can be represented on disk where appropriate. While other representations may be added over time, metadata can be stored in a JSON with Comments file called devcontainer.json today. Products using it should expect to find a devcontainer.json file in one or more of the following locations (in order of precedence):

.devcontainer/devcontainer.json
.devcontainer.json
.devcontainer/<folder>/devcontainer.json (where <folder> is a sub-folder, one level deep)
It is valid that these files may exist in more than one location, so consider providing a mechanism for users to select one when appropriate.
```

**Comment by JeanMeche** [comment]
Per the [readme](https://github.com/angular/angular/blob/main/.devcontainer/README.md), these files are meant to be renamed.
