### ISSUE TITLE
@Input and @Output annotations do not work on setters or getters respectively

### ISSUE THREAD

**Issue by TedSander** [angular/angular#5251]
Transformer only works with fields and will not work with setters and getters when using the @Input and @Output annotations.

**Comment by TedSander** [comment]
Looks to be an easy fix. Just need to add logic in directive_metadata_reader.dart to visit the method declarations and look for the relevant setter/getter. I'll put together a pull request tomorrow.

**Comment by TedSander** [comment]
cc: @vsavkin

**Comment by vsavkin** [comment]
>>  I'll put together a pull request tomorrow.

@TedSander Awsome. Please, assign me as a reviewer. I'll review it asap.

**Comment by TedSander** [comment]
Closed by #5259
