### ISSUE TITLE
Build error after upgrade to angular 16

### ISSUE THREAD

**Issue by NavneetVaid** [angular/angular#52520]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Hi, I am facing a build error with unclear message after upgrading to angular 16, in angular 15 all worked fine 

Below is the error 

./apps/bunsen/src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity i5.ɵj to symbol

./apps/bunsen/src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity i5.ɵj to symbol

Can you somebody help me in understanding what i am missing ? is this is because of some dependency or what ?

I am using NX and its a monorepo

This is specifically failing in production build, Is there any way to get a detailed error message ? We don't have angular.json

### Please provide the environment you discovered this bug in (run `ng version`)

```true
/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.2.0
Node: 18.17.0
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 16.2.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1602.0
@angular-devkit/build-angular      16.2.0
@angular-devkit/build-ng-packagr   0.1002.0
@angular-devkit/build-optimizer    0.1302.1
@angular-devkit/build-webpack      0.1602.0
@angular-devkit/core               16.2.0
@angular-devkit/schematics         16.2.0
@schematics/angular                14.2.10
ng-packagr                         16.2.0
rxjs                               7.8.1
typescript                         4.9.3
zone.js                            0.11.8
```

**Comment by JoostK** [comment]
This can typically happen when a dependency of a package is not available to that package, e.g. where a `.d.ts` file contains an `import ... from 'some-module'` where `'some-module'` is not within a `node_modules` directory that is in scope.

The error comes from here:

https://github.com/angular/angular/blob/63777d20d99ca6206420d545182a754b8f2dc2d8/packages/compiler-cli/src/ngtsc/reflection/src/typescript.ts#L522

and you can get more insight by inserting something like

```js
console.log(type.getSourceFile().fileName);
```

just above the `throw` statement. The code is located in one of the chunk files in `node_modules/@angular/compiler-cli/bundles`.

**Comment by NavneetVaid** [comment]
> This can typically happen when a dependency of a package is not available to that package, e.g. where a `.d.ts` file contains an `import ... from 'some-module'` where `'some-module'` is not within a `node_modules` directory that is in scope.
> 
> The error comes from here:
> 
> https://github.com/angular/angular/blob/63777d20d99ca6206420d545182a754b8f2dc2d8/packages/compiler-cli/src/ngtsc/reflection/src/typescript.ts#L522
> 
> and you can get more insight by inserting something like
> 
> ```js
> console.log(type.getSourceFile().fileName);
> ```
> 
> just above the `throw` statement. The code is located in one of the chunk files in `node_modules/@angular/compiler-cli/bundles`.

@JoostK I cannot find the typescript.ts file i can only see the declaration file inside the specified path

**Comment by JoostK** [comment]
The relevant JavaScript chunk files are within the `bundles` directory of `node_modules/@angular/compiler-cli`.

**Comment by NavneetVaid** [comment]
@JoostK  Thanks, Cool i am able to see the file which if throwing error, so basically the file which is throwing error might have some module imports which are not present in my node_modules is what you are saying ?

import { ModuleWithProviders } from '@angular/core';
import * as i0 from "@angular/core";
import * as i1 from "@angular/common";
import * as i3 from "@ngxs/storage-plugin";
import * as i4 from "@ngxs/logger-plugin";
import * as i5 from "@ngxs/store"; -- And i guess this is giving error ? because it says i5.ej ? i am on  "@ngrx/store": "16.2.0" ---- is this version not compatible with Angular 16 ?
import * as i6 from "@ngxs/devtools-plugin";

Has something deprecated in angular 16 ?

**Comment by JoostK** [comment]
From what package is that file (what is the path of the file) and which version of that package is being used? You're mentioning `@ngrx/store` but the import is for `@ngxs/store`, which is different from `@ngrx/store`. What version of `@ngrx/store` is being used?

**Comment by NavneetVaid** [comment]
Sorry i mentioned it wrong i figured out what is going wrong probably this changed from 3.7.6 to 3.8.1 

We used ngxsStore.ej for importing the NgxsRootModule but i guess now in 3.8.1 we would need to use it via className

typeof i3.NgxsStoragePluginModule, typeof i4.NgxsLoggerPluginModule, **typeof i5.ɵj**, typeof i6.NgxsReduxDevtoolsPluginModule], never>;

so if you see this ej is basically NgxsRootModule - we need to probably change the way we using it now

**Comment by JoostK** [comment]
The `ɵ` in `ɵj` does indicate that the symbol is private (by convention), you shouldn't be using that symbol (although it's not entirely clear to me if you are using it, or if other code is importing it).

**Comment by NavneetVaid** [comment]
The other code is importing it and i guess they wish to import NgxsRootModule, i am not sure how they will import it now and why they used this weird ej
