### ISSUE TITLE
"The the"

### ISSUE THREAD

**Issue by aquinum6** [angular/angular#5252]
In the guide is says "the the". Link: https://angular.io/docs/ts/latest/guide/forms.html

![untitled-1](https://cloud.githubusercontent.com/assets/1774702/11120728/1ae056dc-8952-11e5-8a9d-5b36151b7d16.jpg)

**Comment by ericmartinezr** [comment]
Hey @aquinum6 this repo is for ng2, you can report this issue here https://github.com/angular/angular.io (this one is for the webiste) :+1:

**Comment by aquinum6** [comment]
Thanks,

I have reported this over there.

Peter

2015-11-12 15:35 GMT+01:00 ericmartinezr <notifications@github.com>:
