### ISSUE TITLE
Dependency Injection Route Not Working

### ISSUE THREAD

**Issue by adarshdhital007** [angular/angular#52539]
### Describe the problem that you experienced

Upon visiting the Angular website at https://angular.dev/roadmap, you'll notice an array of intriguing options to explore. In the 'Explore Modern Angular' section, you'll come across a tantalizing link labeled '<a href="di">Try out Inject</a>'. However, it appears that clicking on this link doesn't yield the expected result.

### Enter the URL of the topic with the problem

https://angular.dev/di

### Describe what you were looking for in the documentation

When I ventured to the Angular website at https://angular.dev/roadmap, my intent was to delve into the world of Dependency Injection. The 'Explore Modern Angular' section enticed me with a promising opportunity, labeled '<a href="di">Try out Inject</a>'. 

### Describe the actions that led you to experience the problem

When I clicked on the, Try Out Inject title.

### Describe what you want to experience that would fix the problem

To resolve the issue and achieve the desired experience, I would expect the '<a href="di">Try out Inject</a>' link to lead me to an interactive and informative tutorial or sandbox environment. 

### Add a screenshot if that helps illustrate the problem

https://i.imgur.com/9DsHjP7.png
https://i.imgur.com/prPbGrB.png

**Comment by adarshdhital007** [comment]
Still, the changes are not reflected.

**Comment by twerske** [comment]
> Still, the changes are not reflected.

The issue and PR are still open. 

Thanks for reporting the typo! Once the PR merges, it'll still be a bit before the changes are reflected. We're currently in the process of migrating the full docs app to open source so we can deploy from this source code. Give us a little bit of time and this fix will be reflected on angular.dev.
