### ISSUE TITLE
Page Not Found 

### ISSUE THREAD

**Issue by ddellacqua97** [angular/angular#52549]
### Describe the problem that you experienced

If I navigate to the link below, I receive a not found page

https://angular.dev/cli/commands
![IMG_0110](https://github.com/angular/angular/assets/147511113/39b04a43-36f0-4fa1-91a8-7139bb25cd50)

### Enter the URL of the topic with the problem

https://angular.dev/cli/commands

**Comment by praveeno** [comment]
reproducible steps
visit https://angular.dev/tools/cli
under commands reference card, click on learn more
it will redirect to broken page.

I guess it should redirect to https://angular.dev/cli instead of https://angular.dev/cli/commands

**Comment by twerske** [comment]
PR merged
