### ISSUE TITLE
New docs too clicky - including most important get started

### ISSUE THREAD

**Issue by Jordan-Hall** [angular/angular#52547]
### Description of the Issue:

I've encountered navigation and visibility issues on the Angular documentation website, which seem to make the user experience less intuitive, particularly on mobile devices.

### URL of the Affected Page:

[Angular.dev](https://angular.dev)

### Detailed Feedback:

1. **Visibility of Key Information:**
   - The critical command `ng new` is not immediately visible. For comparison, the NX documentation features their equivalent command prominently on the homepage. A direct link to the [guides](https://angular.dev/overview) and [reference](https://angular.dev/api) sections is provided, but the formatting makes it easy to overlook.

2. **General Navigation Concerns:**
   - On mobile, navigating the documentation is cumbersome. After selecting a menu item, the menu closes, and reopening it is necessary to continue to sub-sections, which is not user-friendly.

3. **Documentation Flow:**
   - The "Start Coding" section redirects to a tutorial, which is unexpected. It would be more logical to present `ng new` at this stage.
   - The tutorials page at [First App Tutorial](https://angular.dev/tutorials/first-app) does not mention the `ng new` command. Additionally, it's unclear whether installing Angular globally is still the recommended practice.

4. **Tutorial Navigation:**
   - The dropdown menus in the tutorial section feel clunky. A dual-mode navigation system, allowing users to switch between tutorial steps and direct access to topics, could enhance the experience.

I appreciate the sleek design of the site, but it seems there are opportunities to refine the UX to better support developers. This is a subjective perspective, and I apologize for the brevity of my feedback. I am open to discussing these points further and would be happy to contribute to improving the user experience.

**Comment by twerske** [comment]
Thank you for your feedback to the beta Angular.dev! We're collecting all subjective feedback in a doc and this will be recorded there.

I'd like to add some context for each of your points in addition:

1. Based on learning research, we're prioritizing people being shown Angular concepts first before presenting them the local development experience. We are considering a "Quick start" guide of sorts that may address this point.
2. Mobile navigation for docs is generally not the best given the length of page content. A collapsing menu is standard here. We can consider a "next" button on mobile, but this is just a possible exploration.
3. See point 1, we are highlight prioritizing concept introduction here, Quick start addition may address the other points.
4. Tutorial navigation does include the "next" points. In the future we hope to further ensure docs and tutorials serve unique and more defined purposes with clear separation of concerns (learning versus doing.)

Thanks again!
