### ISSUE TITLE
'set-cookie' on http response seems to be ignored

### ISSUE THREAD

**Issue by driak** [angular/angular#5254]
Angular2 Http seems to ignore 'set-cookie' http response headers:
When making a simple call to a service with the angular2 Http module and the server responds with a 'set-cookie' header like this: 

set-cookie:ldapid=koen; Domain=.localhost; Expires=Sat, 14-Nov-2015 16:32:06 GMT; Path=/
set-cookie:voucher=b71d3c81-97bb-4833-a3dd-55b3eff07554; Domain=.localhost; Expires=Sat, 14-Nov-2015 16:32:06 GMT; Path=/

Any subsequent calls to the service (same host / same path) seem to ignore the fact that the server has set these cookies for that domain because the relevant cookies do not show up on the headers of the outgoing http requests. (according to http trace seen in browser and on the network)

... or am I missing something?

**Comment by e-oz** [comment]
@driak it's browser's work to create cookie when this header received. Angular can't create cookie file on client's device.

**Comment by robwormald** [comment]
@driak thanks for reporting. as @e-oz says, the browser handles the setting, but it is a valid bug as currently we're ignoring `credentials:true` (which would use the saved cookie) - we've already got an open issue for this - https://github.com/angular/angular/issues/4231 - so I'm going to close this as a duplicate, and you can track that one.

**Comment by driak** [comment]
Ok, thanks for clarifying. 
I did try a couple of configurations for managing security tokens using cookies that worked well in angular1, but somehow I missed #4231 (which also explains some of the other behavior I've been running into).

Great job by the way... can't wait for Angular2 to reach release status. 
Even in its current beta stage it is very tempting to start using it for production projects.

**Comment by jnah** [comment]
did you find the solution ?

**Comment by sk-aravind** [comment]
Having the same problem where, I can't seem to view the "set-cookie" of the header. I can read the header and it's content type only.

**Comment by driak** [comment]
It's been some time, but I believe we worked around the issue by obtaining the required token using a separate rest call returning the token as json in the response body, then cache the token and set it on each outgoing call at application level.

Not sure this type of workaround is still needed (would be surprised if it was), did you take a look at the 'withCredentials' setting as outlined in https://github.com/angular/angular/pull/7281 ?

**Comment by jnah** [comment]
Yeah i just added withCredentials=true, it's work now :)

**Comment by SimoneMSR** [comment]
I use withCredentials=true but it often does not work. Often means 99% of times

**Comment by anil1712** [comment]
Yeah `options.withCredentials = true` worked for me in angular2.
Thanks for saving my life
