### ISSUE TITLE
Why template-expressions documentation disappear?

### ISSUE THREAD

**Issue by hittten** [angular/angular#52551]
### Describe the problem that you experienced

On the page https://angular.io/guide/template-statements I am missing the template-expression documentation. I don't know why it disappeared from version 14.

You can see this in version 13 https://v13.angular.io/guide/interpolation#template-expressions. In the current version, if you search, you can find it: https://angular.io/guide/understanding-template-expr-overview. But it is not in the menu tree.

Also, if you visit https://angular.io/guide/template-statements#syntax, you can read: "Like [template expressions](https://angular.io/guide/interpolation), template statements ", but the link does not go to the correct page.

### Enter the URL of the topic with the problem

https://angular.io/guide/understanding-template-expr-overview.

### Describe what you were looking for in the documentation

to see the "template-expressions" in the "text interpolation" page https://angular.io/guide/interpolation like version 13. And the broken links in https://angular.io/guide/template-statements#syntax

### Describe the actions that led you to experience the problem

I'm teach angular with the official documentation and I teach to my students to use the documentation page.

**Comment by JeanMeche** [comment]
We're looking at deprecating the angular.io documentation in favor of https://angular.dev. 

Feel free to open an issue dedicated for the new doc site if you have suggestions, thank you.
