### ISSUE TITLE
Error in link “type inference in typescript”

### ISSUE THREAD

**Issue by LouMauriege** [angular/angular#52553]
### Describe the problem that you experienced

On the page "https://angular.dev/tutorials/learn-angular/updating-the-component-class" the link **[type inference in TypeScript](https://angular.dev/typescript.org/type-inference)** contain an error. Should remove the "angular.dev" from it.

**Comment by twerske** [comment]
This PR was merged into the repository by commit https://github.com/angular/angular/commit/cb5c6fc53027327b5b0b78962dc9afb690c6b894.
