### ISSUE TITLE
Page not found "Angular's version compatibility"

### ISSUE THREAD

**Issue by rajguru827** [angular/angular#52562]
### Describe the problem that you experienced

Angular's version compatibility documentation is missing and navigating the user to page not found.

https://angular.dev/tools/cli/setup-local

![image](https://github.com/angular/angular/assets/17214716/ec37b378-2014-416b-8771-d389adab2ff1)

### Enter the URL of the topic with the problem

https://angular.dev/versions

**Comment by sasidharansd** [comment]
I would like to work on this to fix it

**Comment by twerske** [comment]
This PR was merged into the repository by commit https://github.com/angular/angular/commit/68f89b00a54f044638ac5fb2a814ad67b39423d8.
