### ISSUE TITLE
Angular.dev - Inconsistent preference of @HostBinding/@HostListener and host property

### ISSUE THREAD

**Issue by spfuller** [angular/angular#52561]
### Describe the problem that you experienced

On the Components / Host Elements page, it states that the host property is preferred over <span>@</span>HostBinding and 
<span>@</span>HostListener.

However in the Best Practices / Style Guide page it states that <span>@</span>HostBinding and <span>@</span>HostListener are preferred over the host property (Style 06-03).

Which is the preferred method?

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/host-elements

### Add a screenshot if that helps illustrate the problem

Components / Host Elements page:
![image](https://github.com/angular/angular/assets/32622986/ba1bcf14-2b34-4304-abda-558a5fc03029)

Best Practices /Style Guide page:
![image](https://github.com/angular/angular/assets/32622986/cf80d5f5-1007-42d4-ae55-09d085d6fb0b)

**Comment by KlausEverWalkingDev** [comment]
This also got me. If backwards compatibility was the case, why not put a "deprecated" decorator on **host** self-documentation?

**Comment by rlmestre** [comment]
The components repo [coding standards](https://github.com/angular/components/blob/main/CODING_STANDARDS.md#host-bindings) document has also suggested preferring the host property for a while.

Are we looking to update the style guide with the new preference? Does angular.io need updating as well? If so, I could contribute the changes. I've been interested in this happening for a while 😄 

cc @twerske @jelbourn

**Comment by csvn** [comment]
For `@angular/eslint-plugin` [the rule `no-host-metadata-property`](https://github.com/angular-eslint/angular-eslint/tree/main/packages/eslint-plugin#suggestions) is also enabled in the recommended configuration. After docs are up-to-date, It would be great to reflect this best practice in the linting as well.

**Comment by JeanMeche** [comment]
@csvn This is done on another repo : github.com/angular-eslint/angular-eslint 
cc @JamesHenry

**Comment by csvn** [comment]
Yeah, I knew that, but I thought it was premature to create issue in https://github.com/angular-eslint/angular-eslint before docs are consistent about the correct usage to avoid confusion 🙂

**Comment by JamesHenry** [comment]
Thanks for the heads up folks, it's a shame that this 180 missed the major version release, I will have a think about the best way to encourage the newly preferred approach and deprecated the rule as it exists today

**Comment by homj** [comment]
I'm not sure this is the right place to start a discussion about the motivations behind this, but the explanation for this style change according to the [coding standards](https://github.com/angular/angular/issues/52561) of angular/components seems kinda "weird" to me to break with such an integral part of Angular and now recommend the previously discouraged `host` property instead.

Are there any plans for new APIs for host binding that don't rely on the host property?

**Comment by majies** [comment]
@homj from reading the RFCs when this was first discussed it seems there are no plans for new APIs, if that has changed now who knows. 

You can read the specific thread https://github.com/angular/angular/discussions/49682#discussioncomment-5515138

**Comment by homj** [comment]
Thanks @majies! I came to the same conclusion and decided to create a library that does just what I need in the meantime. If you want to check it out: https://github.com/bynaryDE/angular-extensions/tree/main/libs/composables

**Comment by jelbourn** [comment]
I'm planning to reconcile this conflicting guidance by the time angular.dev leaves beta.

**Comment by JeanMeche** [comment]
Hi, we will track this under the #54284 umbrella issues, thank you for your suggestions !
