### ISSUE TITLE
Reptition of text on the Angular.dev webite.

### ISSUE THREAD

**Issue by ESE-MONDAY** [angular/angular#52575]
### Describe the problem that you experienced

On the website angular.dev, the page: anatomy of a componet, there is a repitition of

 " You provide Angular-specific information for a component by adding a [@Component](https://angular.dev/api/core/Component) [decorator](https://www.typescriptlang.org/docs/handbook/decorators.html) on top of the TypeScript class: You provide Angular-specific information for a component by adding a [@Component](https://angular.dev/api/core/Component) [decorator](https://www.typescriptlang.org/docs/handbook/decorators.html) on top of the TypeScript class: "

### Enter the URL of the topic with the problem

https://angular.dev/guide/components

**Comment by DimitriTsikaridze** [comment]
if no one is on it, I'd like to take this. it'll be my first PR to this repo and good first issue/exercise

**Comment by twerske** [comment]
This PR was merged into the repository by commit https://github.com/angular/angular/commit/9dff1fe8917d497781b91fb60519ff2014eaded4.
