### ISSUE TITLE
docs: support prefers-reduced-motion in View Transitions API

### ISSUE THREAD

**Issue by grubeninspekteur** [angular/angular#52571]
### Describe the problem that you experienced

Navigating between documentation pages, especially if they load as quickly as they do on angular.dev, should be instant. The fading effect used both for the menu as well as the content is making me feel dizzy. This is contrary to how basically the majority of the web is presented (Wikipedia etc.)

### Describe what you want to experience that would fix the problem

Either get rid of the animation in general, or at least honor the[ `prefers-reduced-motion` media feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) and disable the animation then.

**Comment by lacolaco** [comment]
+1 on respecting the user preference of `prefers-reduced-motion`.

**Comment by bbdaniell** [comment]
Would really appreciate this, especially as the site actually does respect `prefers-reduced-motion` (at least in firefox), just not enough. Currently, the "reduced" setting replaces the slidey transitions with the fade/flash mentioned above, which is at least usable for me, but it'd be better if that just turned animations off completely

**Comment by JeanMeche** [comment]
I will take a look on this once the infra is in place. Likely next week.

**Comment by twerske** [comment]
Thanks @JeanMeche ! We do have some `prefers-reduced-motion` support but I agree that the experimental View Transitions API should better support this. Thanks for reporting this issue!

**Comment by Erbenos** [comment]
Rather than adding an option like "respectPreferReducedMotion" to ViewTransitionsFeatureOptions wouldn't it make more sense to let consumers conditionally add the withViewTransitions feature by checking the prefer reduced motion settings themselves? This would mirror the way NoopAnimationsModule and BrowserAnimationsModule are supposed to be used as well.

**Comment by atscott** [comment]
@Erbenos this is a big for the docs website, not a feature request to add an option to the feature itself. It’s already possible to respect the user options correctly with the API as it is - we just aren’t doing it on angular.dev yet.
