### ISSUE TITLE
angular.dev: Concerns about new color palette

### ISSUE THREAD

**Issue by t-mish** [angular/angular#52574]
### Describe the problem that you experienced

Angular always had a recognisable color for its self positioning. We had blue for React, green for Vue, orange for Svelte ... and **red** for Angular. Every one could say that this is Angular just by looking at its logo. Now I can't say which color Angular has because I don't understand which color it has (no, really. Is it red, purple, pink? :))

I am suggesting to keep its main color the same as it was before without any (red, pink, purple, etc) gradients. I think it would help to keep some succession to its previous versions and continue providing strong association with framework.

### Describe what you want to experience that would fix the problem

I am suggesting to keep its main color the same as it was before without any (red, pink, purple, etc) gradients.

**Comment by twerske** [comment]
Thank you for sending in your feedback @t-mish! We appreciate your engagement in the Angular community.

Angular's new brand is an expansion on the existing colorspace. We're still red, we're just also pink and purple as well now!
