### ISSUE TITLE
Template interfering with an Array it displays

### ISSUE THREAD

**Issue by jgenchik** [angular/angular#5258]
A simple template is using <code>*ng-for</code> to iterate over an Array. When a function removes everything from this Array using <code>forEach(() => myArray.pop())</code>, some entries are still left in the Array.

This is the link to the Plunker that demonstrates this: http://plnkr.co/edit/OSvGaJ6IdHg4mYa7iQh4

**Comment by ericmartinezr** [comment]
@jgenchik that's a problem with your approach. I can reproduce the same behavior using plain javascript.
See this [es6fiddle](http://www.es6fiddle.net/igwounn8/) and this [fiddle](http://jsfiddle.net/592jrzrg/). This not related to ng2. 

Anyway, you can clear your array super easily : `this.people = [];`

**Comment by wesleycho** [comment]
If you don't want to break the reference to your array, another way to clear the array is
```
while (myArray.length) {
  myArray.shift();
}
```

**Comment by gkalpak** [comment]
Another popular alternative (that's also retaining the reference) is `myArray.length = 0`.

**Comment by pkozlowski-opensource** [comment]
OK, hopefully this gives @jgenchik few ways of clearing an array :-)
