### ISSUE TITLE
Realistic migration path?

### ISSUE THREAD

**Issue by samdoeswork** [angular/angular#52583]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

Yes

### Description

Is there a realistic way to upgrade from Angular 12?

It's totally unworkable for *real world* apps outside of Google. (Realistically I am sure it involved a lot of hand-holding inside Google also).

Please don't take this as criticism. It's a **sincere** attempt to inform you of what things are like for a typical app outside Google.

First - with every major release ~30% of all community packages are unsupported. So every single version increment involves removing and replacing multiple packages.

Second - following the upgrade guide and running ng upgrade, it still lands on internally incompatible releases. I suspect the path from older versions became broken at some point since it was current. There's several @angular packages which all have peer-dependencies on each other and following the upgrade guide still cannot get them to compile.

Many migrations fail with errors. When they fail they cannot be retried. There is no "here's how to do this manually" link.

After 12 hours of trying to do the upgrade, there's hundreds of issues, I've manually replaced 6 dead packages, and webpack appears to completely not understand CSS any longer. It's not realistic to open dozens of individual issues.

I believe this is the typical experience of an Angular user trying to upgrade. But the reason this never reaches your attention is people don't make this kind of post - they just quiet quit (and stop maintaining their packages).

If I upgrade React or Vue, nothing breaks. And it's one package. You can import parts from that package.

For the (many) people who simply cannot upgrade, is there some realistic advice (create a new app with x recommended settings, and try and copy things component-by-component, fixing issues as they arise?)

I think realistically without the engineering resources & direct support which Google gets - most people are realistically unable to do the upgrades.

Maybe there's some tooling to help people start with a clean-sheet app and copy & upgrade their components? The current path isn't just too painful it's flatly not possible.

Please take this in the spirit it's intended: firstly as a notice of what it's really like for a long-term user, and secondly as a plea for some kind of help. It would be really nice to be on V17 as it looks super nice. At a minimum you should consider surveying what %age of people succeed in their migration path. I suspect I am the common case & the biggest driver of abandonment on the framework is that upgrading is not possible.

### Please provide a link to a minimal reproduction of the bug

NA

### Please provide the exception or error you saw

```true
Hundreds...

Failing migrations that cannot be retried. Peer dependencies between internal Angular packages which cannot resolve. Imports between Angular packages which are broken at every step. Webpack complaining that there's no loader which can understand CSS. And ofc the expected breaking changes.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 12 and upwards.
```

### Anything else?

NA

**Comment by spock123** [comment]
If I were you I'd try to do it step by step. Instead of upgrading 12->V16(17), upgrade from 12->13, take it step by step.

**Comment by mgechev** [comment]
Hey @samdoeswork, we understand that third-party dependencies are on the critical path for each update. Our goal is to make it as simple as possible to keep up to date with the releases of the framework and `ng update` already does everything on Angular's side.

We're exploring and thinking about how we can support the rest of the ecosystem and until we have a better solution, I'd recommend being very picky on what third-party dependencies you introduce in your apps. If they don't demonstrate a healthy support model, you they'll probably be a bad fit for your project.

I'll close this issue because there's nothing immediately actionable on our end, but definitely consider it as one more data point that we need to think how to more effectively move the ecosystem forward with the smooth update path we currently have.
