### ISSUE TITLE
angular.dev: Change word standaone to standalone

### ISSUE THREAD

**Issue by ddelavega** [angular/angular#52596]
### Describe the problem that you experienced

In docs, inside pipe decorator, in the first block of code:

@Pipe({
  standaone: true,
  name: 'star',
})

The word "standalone" is misspelled.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/create-a-pipe

### Describe what you were looking for in the documentation

The word "standalone" is misspelled.

### Describe the actions that led you to experience the problem

Change word "standaone" to "standalone"

**Comment by atscott** [comment]
duplicate of https://github.com/angular/angular/issues/52595
