### ISSUE TITLE
angular.dev: Remove backtick after ReversedPipe word

### ISSUE THREAD

**Issue by ddelavega** [angular/angular#52594]
### Describe the problem that you experienced

In title of step 1: "Create..."  there is a backtick after ReversePipe word: 

Create the `ReversePipe

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/create-a-pipe#create-the-reversepipe

### Describe what you want to experience that would fix the problem

Remove backtick after ReversedPipe word or modify md.

**Comment by twerske** [comment]
This PR was merged into the repository by commit https://github.com/angular/angular/commit/0ffa228165f2d34ed92b01765961998444c3d54b.
