### ISSUE TITLE
Upgrade path from v12 is broken (ng update fails with conflicting internal packages from Angular itself)

### ISSUE THREAD

**Issue by samdoeswork** [angular/angular#52599]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

Yes

### Description

On v12 of angular running the recommended **ng update @angular/core@13 @angular/cli@13** I get the following:

The installed Angular CLI version is outdated.
Installing a temporary Angular CLI versioned 13.3.11 to perform the update.
√ Package successfully installed.
Using package manager: 'npm'
Collecting installed dependencies...
Found 137 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/build-angular @ "13.3.11" (was "12.2.18")...
    Updating package.json with dependency @angular-devkit/core @ "13.3.11" (was "12.2.18")...
    Updating package.json with dependency @angular-devkit/schematics @ "13.3.11" (was "12.2.18")...
    Updating package.json with dependency @angular/compiler-cli @ "13.4.0" (was "12.2.17")...
    Updating package.json with dependency ng-packagr @ "13.3.1" (was "12.2.7")...
    Updating package.json with dependency typescript @ "4.6.4" (was "4.2.4")...
    Updating package.json with dependency @angular/animations @ "13.4.0" (was "12.2.17")...
    Updating package.json with dependency @angular/cli @ "13.3.11" (was "12.2.18")...
    Updating package.json with dependency @angular/common @ "13.4.0" (was "12.2.17")...
    Updating package.json with dependency @angular/compiler @ "13.4.0" (was "12.2.17")...
    Updating package.json with dependency @angular/core @ "13.4.0" (was "12.2.17")...
    Updating package.json with dependency @angular/forms @ "13.4.0" (was "12.2.17")...
    Updating package.json with dependency @angular/localize @ "13.4.0" (was "12.2.17")...
    Updating package.json with dependency @angular/platform-browser @ "13.4.0" (was "12.2.17")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "13.4.0" (was "12.2.17")...
    Updating package.json with dependency @angular/router @ "13.4.0" (was "12.2.17")...
  UPDATE package.json (7228 bytes)
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: my-project-name@0.0.0
npm ERR! Found: @angular-devkit/build-angular@12.2.18
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"^13.3.11" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"^13.3.11" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/compiler-cli@13.4.0
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   peer @angular/compiler-cli@"^13.0.0 || ^13.3.0-rc.0" from @angular-devkit/build-angular@13.3.11
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"^13.3.11" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

It is my understanding that all files involved here are Angular internal files. I've tried this 3 times (each time reverting to a working version of v12, remove package-lock and npm modules, reinstall, and attempt upgrade).

Seems like the versions the v13 migration chooses just self-conflict.

I did try forcing and that led to issues.

### Please provide the exception or error you saw

```true
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: instant-extension@0.0.0
npm ERR! Found: @angular-devkit/build-angular@12.2.18
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"^13.3.11" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"^13.3.11" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/compiler-cli@13.4.0
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   peer @angular/compiler-cli@"^13.0.0 || ^13.3.0-rc.0" from @angular-devkit/build-angular@13.3.11
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"^13.3.11" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Sam\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sam\AppData\Local\npm-cache\_logs\2023-11-07T20_27_59_165Z-debug-0.log
× Package install failed, see above.


The referenced log file:
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install',
0 verbose cli   '--quiet'
0 verbose cli ]
1 info using npm@8.5.5
2 info using node@v16.15.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:C:\apps\jaf\client\.npmrc Completed in 1ms
10 timing config:load:project Completed in 6ms
11 timing config:load:file:C:\Users\Sam\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\Sam\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 15ms
19 timing npm:load:configload Completed in 15ms
20 timing npm:load:setTitle Completed in 0ms
21 timing config:load:flatten Completed in 2ms
22 timing npm:load:display Completed in 3ms
23 verbose logfile C:\Users\Sam\AppData\Local\npm-cache\_logs\2023-11-07T20_27_59_165Z-debug-0.log
24 timing npm:load:logFile Completed in 4ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 24ms
28 timing arborist:ctor Completed in 1ms
29 silly logfile start cleaning logs, removing 8 files
30 timing idealTree:init Completed in 1173ms
31 timing idealTree:userRequests Completed in 0ms
32 silly idealTree buildDeps
33 silly fetch manifest @angular/animations@^13.4.0
34 http fetch GET 200 https://registry.npmjs.org/@angular%2fanimations 127ms (cache revalidated)
35 silly fetch manifest @angular/core@^13.4.0
36 http fetch GET 200 https://registry.npmjs.org/@angular%2fcore 66ms (cache revalidated)
37 silly fetch manifest rxjs@^6.5.5
38 http fetch GET 200 https://registry.npmjs.org/rxjs 6ms (cache hit)
39 silly fetch manifest zone.js@^0.11.4
40 http fetch GET 200 https://registry.npmjs.org/zone.js 42ms (cache revalidated)
41 silly fetch manifest @angular/cli@^13.3.11
42 http fetch GET 200 https://registry.npmjs.org/@angular%2fcli 8ms (cache hit)
43 silly fetch manifest @angular/common@^13.4.0
44 http fetch GET 200 https://registry.npmjs.org/@angular%2fcommon 55ms (cache revalidated)
45 silly fetch manifest @angular/compiler@^13.4.0
46 http fetch GET 200 https://registry.npmjs.org/@angular%2fcompiler 98ms (cache revalidated)
47 silly fetch manifest @angular/forms@^13.4.0
48 http fetch GET 200 https://registry.npmjs.org/@angular%2fforms 72ms (cache revalidated)
49 silly fetch manifest @angular/platform-browser@^13.4.0
50 http fetch GET 200 https://registry.npmjs.org/@angular%2fplatform-browser 59ms (cache revalidated)
51 silly fetch manifest @angular/localize@^13.4.0
52 http fetch GET 200 https://registry.npmjs.org/@angular%2flocalize 95ms (cache revalidated)
53 silly fetch manifest @angular/compiler-cli@^13.4.0
54 http fetch GET 200 https://registry.npmjs.org/@angular%2fcompiler-cli 62ms (cache revalidated)
55 silly fetch manifest typescript@~4.6.4
56 http fetch GET 200 https://registry.npmjs.org/typescript 81ms (cache revalidated)
57 silly fetch manifest @angular/platform-browser-dynamic@^13.4.0
58 http fetch GET 200 https://registry.npmjs.org/@angular%2fplatform-browser-dynamic 72ms (cache revalidated)
59 silly fetch manifest @angular/router@^13.4.0
60 http fetch GET 200 https://registry.npmjs.org/@angular%2frouter 77ms (cache revalidated)
61 silly fetch manifest @angular-devkit/build-angular@^13.3.11
62 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2fbuild-angular 85ms (cache revalidated)
63 silly fetch manifest @angular/service-worker@^13.0.0 || ^13.3.0-rc.0
64 http fetch GET 200 https://registry.npmjs.org/@angular%2fservice-worker 1394ms (cache revalidated)
65 silly fetch manifest karma@^6.3.17
66 http fetch GET 200 https://registry.npmjs.org/karma 52ms (cache revalidated)
67 silly fetch manifest ng-packagr@^13.3.1
68 http fetch GET 200 https://registry.npmjs.org/ng-packagr 43ms (cache revalidated)
69 silly fetch manifest tslib@^2.0.0
70 http fetch GET 200 https://registry.npmjs.org/tslib 5ms (cache hit)
71 silly fetch manifest protractor@~7.0.0
72 http fetch GET 200 https://registry.npmjs.org/protractor 76ms (cache revalidated)
73 silly fetch manifest tailwindcss@^2.0.0 || ^3.0.0
74 http fetch GET 200 https://registry.npmjs.org/tailwindcss 43ms (cache revalidated)
75 silly fetch manifest @angular-devkit/core@^13.3.11
76 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2fcore 7ms (cache hit)
77 silly fetch manifest chokidar@^3.5.2
78 http fetch GET 200 https://registry.npmjs.org/chokidar 4ms (cache hit)
79 silly fetch manifest @angular-devkit/schematics@^13.3.11
80 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2fschematics 6ms (cache hit)
81 timing idealTree Completed in 4057ms
82 timing command:install Completed in 4063ms
83 verbose stack Error: could not resolve
83 verbose stack     at PlaceDep.failPeerConflict (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\place-dep.js:546:25)
83 verbose stack     at PlaceDep.place (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\place-dep.js:197:21)
83 verbose stack     at new PlaceDep (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\place-dep.js:71:10)
83 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:964:31
83 verbose stack     at Array.map (<anonymous>)
83 verbose stack     at Arborist.[buildDepStep] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:964:8)
83 verbose stack     at async Arborist.buildIdealTree (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:216:7)
83 verbose stack     at async Promise.all (index 1)
83 verbose stack     at async Arborist.reify (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:153:5)
83 verbose stack     at async Install.exec (C:\Program Files\nodejs\node_modules\npm\lib\commands\install.js:159:5)
84 verbose cwd C:\apps\jaf\client
85 verbose Windows_NT 10.0.22621
86 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--quiet"
87 verbose node v16.15.0
88 verbose npm  v8.5.5
89 error code ERESOLVE
90 error ERESOLVE could not resolve
91 error
92 error While resolving: instant-extension@0.0.0
92 error Found: @angular-devkit/build-angular@12.2.18
92 error node_modules/@angular-devkit/build-angular
92 error   dev @angular-devkit/build-angular@"^13.3.11" from the root project
92 error
92 error Could not resolve dependency:
92 error dev @angular-devkit/build-angular@"^13.3.11" from the root project
92 error
92 error Conflicting peer dependency: @angular/compiler-cli@13.4.0
92 error node_modules/@angular/compiler-cli
92 error   peer @angular/compiler-cli@"^13.0.0 || ^13.3.0-rc.0" from @angular-devkit/build-angular@13.3.11
92 error   node_modules/@angular-devkit/build-angular
92 error     dev @angular-devkit/build-angular@"^13.3.11" from the root project
92 error
92 error Fix the upstream dependency conflict, or retry
92 error this command with --force, or --legacy-peer-deps
92 error to accept an incorrect (and potentially broken) dependency resolution.
92 error
92 error See C:\Users\Sam\AppData\Local\npm-cache\eresolve-report.txt for a full report.
93 verbose exit 1
94 timing npm Completed in 4388ms
95 verbose unfinished npm timer reify 1699388879485
96 verbose unfinished npm timer reify:loadTrees 1699388879489
97 verbose unfinished npm timer idealTree:buildDeps 1699388880662
98 verbose unfinished npm timer idealTree:#root 1699388880663
99 verbose code 1
100 error A complete log of this run can be found in:
100 error     C:\Users\Sam\AppData\Local\npm-cache\_logs\2023-11-07T20_27_59_165Z-debug-0.log
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 12
NPM 8.5.5
Node 16.15.0
```

### Anything else?

Thank you for your work on this framework

**Comment by JoostK** [comment]
I don't see anything out of the ordinary in those logs. Particularly, the ERESOLVE error doesn't make sense:

```
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"^13.3.11" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/compiler-cli@13.4.0
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   peer @angular/compiler-cli@"^13.0.0 || ^13.3.0-rc.0" from @angular-devkit/build-angular@13.3.11
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"^13.3.11" from the root project
```

None of those versions are conflicting. This may be an NPM peer dependency resolution bug; NPM 8.5.5 is quite old. You could try updating NPM, or alternatively you'll have to `--force`. You mentioned that you experienced issues with that flag but the specifics of those problems are not specified, so I cannot comment on that.

Anyway, Angular 12 and 13 no longer receive updates at this point.

**Comment by JoostK** [comment]
Using NPM 9.9.1 I tried the following:

```
npx @angular/cli new ng52599
cd ng52599
npm run ng update @angular/core@13 @angular/cli@13
```

This fails with the ERESOLVE error you observe.

_However_, removing the `package-lock.json` file then allows `npm i` to succeed. That is an NPM bug to me; the conflicting package is being updated in `package.json` so surely NPM shouldn't be constrained by what is currently in the lockfile for that package.

You'll have to use `--force` (or an alternative package manager) to workaround the NPM bug.

**Comment by samdoeswork** [comment]
Thanks @JoostK .
Using --force (and using --force to uninstall/change versions on some packages also) I was able to get to version 13 and compile. Changing NPM version didn't help but that was a good suggestion.

Unfortunately when I try to go to 14 one of the migrations fails. Not sure if you'd prefer me to close this and open a new issue?

** Executing migrations of package '@angular/cli' **

> Remove 'defaultProject' option from workspace configuration.
  The project to use will be determined from the current working directory.
UPDATE angular.json (5333 bytes)
  Migration completed.

> Remove 'showCircularDependencies' option from browser and server builders.
  Migration completed.

> Replace 'defaultCollection' option in workspace configuration with 'schematicCollections'.
  Migration completed.

> Update Angular packages 'dependencies' and 'devDependencies' version prefix to '^' instead of '~'.
√ Packages installed successfully.
  Migration completed.

> Remove 'package.json' files from library projects secondary entrypoints.
  Migration completed.

> Update TypeScript compilation target to 'ES2020'.
× Migration failed: Path "tsconfig.spec.json" does not exist.

/src/tsconfig.spec.json is actually there so this seems like a bug or there's something odd about my setup.


Obviously I can manually change the target to ES2020 - but I don't know if this is the last migration or if there's other steps which didn't run because this failed (seeing the upgrade fail with an error makes me nervous).

**Comment by JeanMeche** [comment]
You likely have a `tsconfig.spec.json` entry in your `angular.json` but that file doesn't exist. 
Can you confirm ?

**Comment by atscott** [comment]
Closing as the original issue has been identified as a problem with npm.
