### ISSUE TITLE
angular.dev: Change word "standaone" to "standalone"

### ISSUE THREAD

**Issue by ddelavega** [angular/angular#52595]
### Describe the problem that you experienced

Inside the first step Create the ReversePipe, in the block of code: 

@Pipe({
    standaone: true,
    name: 'reverse'
})

The word "standalone" is misspelled.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/create-a-pipe#create-the-reversepipe

### Describe what you were looking for in the documentation

The word "standalone" is misspelled.

### Describe what you want to experience that would fix the problem

Change word "standaone" to "standalone"

**Comment by AnthonyFr75** [comment]
Hi,
I believe I can handle this seemingly impossible task.

**Comment by atscott** [comment]
> Hi,
I believe I can handle this seemingly impossible task.

I look forward to reviewing your PR and accompanying design doc.
