### ISSUE TITLE
docs: Add missing "deprecated" indicator on API reference

### ISSUE THREAD

**Issue by mvdluit** [angular/angular#52603]
### Describe the problem that you experienced

There is no clear indication when an API reference is deprecated.

Example: `provideRoutes` has a clear deprecated label on [angular.io/api/router/provideRoutes](https://angular.io/api/router/provideRoutes) and provides an alternative in the text,  while on [angular.dev/api/router/provideRoutes](https://angular.dev/api/router/provideRoutes) there's only an easy to miss ~~provideRoutes~~ in the codeblock indicating that it's deprecated. No alternative to the deprecated API is provided here. 

### Describe the actions that led you to experience the problem

Direct link to the API reference provided by the Angular Community Discord bot, bypassing the API overview page where a (easy to miss) deprecation indicator is shown.

### Describe what you want to experience that would fix the problem

- A label similar to the type label, indicating that the reference is deprecated would be very useful.
- Mention of an alternative API if available

**Comment by twerske** [comment]
Thanks for the issue report! @jelbourn @9kubczas4 it looks like some forms of API methods are not being marked as deprecated. Can we look into this?

**Comment by 9kubczas4** [comment]
Hi @twerske,
Please assign this issue to me, I know how to fix it.

**Comment by mvdluit** [comment]
@9kubczas4 I found a similar issue for API references currently in developer preview. Marked as developer preview on angular.io, but no mention on angular.dev. example: `toObservable` in the `core/rxjs-interop` package. https://angular.io/api/core/rxjs-interop/toObservable vs https://angular.dev/api/core/rxjs-interop/toObservable

Not sure if this falls under the same issue. If not I'd be happy to make a separate issue for it.

**Comment by 9kubczas4** [comment]
Thank you @mvdluit, I think would be nice to create a separate issue for the `developer preview` label.

**Comment by mvdluit** [comment]
@9kubczas4 done #52734

**Comment by mvdluit** [comment]
Completed in https://github.com/angular/dev-infra/pull/1794.
