### ISSUE TITLE
Change Detection wont run if a singal's value gets updated from within a `ResizeObserver`

### ISSUE THREAD

**Issue by TomTomB** [angular/angular#52610]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

As visible inside the Stackblitz, the DOM wont reflect the latest DomRect as a json string. Manually running `detectChanges()` fixes this issue, but I think this should work out of the box without having to inject the change detector ref. 
This issue probably applies to `ContentObserver ` and `IntersectionObserver` as well, but that was not tested.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-k3nbkh?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
No error ocurred
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.9
Node: 18.18.2
Package Manager: yarn 4.0.1
OS: linux x64

Angular: 16.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.9
@angular-devkit/build-angular   16.2.9
@angular-devkit/core            16.2.9
@angular-devkit/schematics      16.2.9
@angular/cdk                    16.2.11
@angular/cli                    16.2.9
@schematics/angular             16.2.9
ng-packagr                      16.2.3
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.14.2
```

**Comment by JeanMeche** [comment]
Hello, 

This is expected, `ResizeObserver` is not patched by `zone.js` by default : The callback is run outside the Angular zone.

If you want to patch this API you can add `import 'zone.js/plugins/zone-patch-resize-observer';` to the polyfill. 
Or you can run the whole callback in the zone with `ngZone.run(() => { ...  })`
