### ISSUE TITLE
angular.dev: API reference code hard to read with scroll

### ISSUE THREAD

**Issue by jnizet** [angular/angular#52614]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I tried using the reference documentation in angular.dev for the first time to look at the documentation of HttpClient, and found the following issues:

1. I don't understand the point of the "Featured" section. It seems to show randomly chosen classes, and there's no way I found to change the selection or to hide the section.
2. The featured section really gets in the way when you use the filter above it to find a class: the found results should be the only ones being displayed, instead of appearing after the irrelevant features section. At first I even thought the filter didn't filter at all.
3. The HttpClient methods appearing in the central zone are not all visible, and scrolling to the remaining is not possible. Only `request()` overloads and part of the `delete()` overloads are visible.
4. Distinguishing the various overloads is not practical at all: everything is written on a single line, not formatted like actual code would be, and you need to scroll horizontally to see all the signature and the return type
5. In Firefox it's even worse: the central part disappears when scrolling down rather than staying visible 
6. The reference doc in angular.io has an extremely useful link to go to the source in github. I couldn't find it in adev.

**Comment by VictorDev200** [comment]
About point 5. 

The docs-code is using 93vh to set the container max height giving trouble at height < 768px 

```css
.adev-reference-api-tab>.docs-code {
  width:100%;
  max-height:93vh;
  overflow:hidden;
  padding:0
}
```

**Comment by Farbfetzen** [comment]
Addition to point 4: Scrolling horizontally is difficult for me because there doesn't seem to be a scrollbar for that. I have to highlight and drag the text to see the rest.

**Comment by twerske** [comment]
Thanks for the feedback!

I think this issue would be better tackled if we split it up into several issues about the various bugs and requests included:

1-2. We plan to move the Featured section above the filter to address the issues you're brought up. Please see: https://github.com/angular/angular/issues/52705

3-5. code readability of HttpClient in API reference. @jelbourn may have more info here.

6. GitHub links. This is in progress and the motivation of moving the code to open source. Once the app is running and deploying from this repo fully, we'll be able to add back in the GitHub links that are current temporarily removed. See https://github.com/angular/angular/issues/52641

Let's narrow focus of this issue to points #3-5 which are not being tracked elsewhere

**Comment by twerske** [comment]
Since 3-5 are all subjective feedback, we're collecting this internally when looking at the overall API design. Since HttpClient is the hardest page to read on Angular.io, it's unlikely the sleek design is going to completely fix that the API itself is hard to read.

As stated, I've included this in internal design feedback and we will continue to look at this, including horizontal scroll.

Thanks again for the feedback!

**Comment by jelbourn** [comment]
Yeah, WRT the `HttpClient` specifically, it has a wild number of overloads, and the signatures are all long and complicated. I'm interested in someday finding a neater way to display/format them all, but it's very much an outlier among all of the API surfaces, so a bit of a lower priority. I'm just happy it's more legible than the aio version, which I've always found unreadable.
