### ISSUE TITLE
bug (docs): Bad recommendation to export standalone component groups as `readonly` array

### ISSUE THREAD

**Issue by hakimio** [angular/angular#52615]
### Describe the problem that you experienced

["Standalone components for library authors"](https://angular.io/guide/standalone-components#standalone-components-for-library-authors) section of the docs recommends exporting standalone component groups as `readonly` array, but readonly arrays can not be used in `NgModule` imports and language service does not recognize `readonly` arrays when they are imported in standalone component imports.
Related issue #48089 which hasn't been resolved for a year now.

### Enter the URL of the topic with the problem

https://angular.io/guide/standalone-components#standalone-components-for-library-authors

### Describe what you were looking for in the documentation

Good recommendation how to handle standalone component groups in a library.

### Describe the actions that led you to experience the problem

Tried to use `readonly` array of standalone components in `NgModule` and standalone component imports. When used in `NgModule` imports it leads to compilation error and when used in standalone component imports it leads to language service errors.

### Describe what you want to experience that would fix the problem

Do not recommend to export standalone component groups as `readonly` array. Non-readonly array works but readonly one does not.

### Provide any additional information here in as much as detail as you can

There was a PR #48106 opened to support readonly array imports in `NgModule` a year ago but it was never merged.
@pkozlowski-opensource

**Comment by JoostK** [comment]
I don't think we should be changing the doc; this should work and #48106 deserves some love to fix the problem. Closing for #48089.

**Comment by hakimio** [comment]
But it does NOT work now and it doesn't seem that the PR will be merged any time soon.

**Comment by pkozlowski-opensource** [comment]
> and it doesn't seem that the PR will be merged any time soon.

We should merge this PR, will try to pick it up in the coming days.
