### ISSUE TITLE
every component hits twice in angular 14 version

### ISSUE THREAD

**Issue by jashwin264** [angular/angular#52622]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
