### ISSUE TITLE
docs: remove DI_token link

### ISSUE THREAD

**Issue by amilamen** [angular/angular#52621]
### Describe the problem that you experienced

In this page (https://angular.dev/api/core/ANIMATION_MODULE_TYPE), when I click on **DI_token** link, it redirects me to (https://angular.dev/overview) and the attribute [href] equals to (https://angular.dev/docs).

### Enter the URL of the topic with the problem

https://angular.dev/api/core/ANIMATION_MODULE_TYPE

**Comment by twerske** [comment]
@JeanMeche is this a known missing API?

**Comment by JeanMeche** [comment]
This issue is about a broken link on an API page ! 
We could likely remove that link, no other InjectionToken page has a link in it.

**Comment by Dhoni77** [comment]
Hi @twerske I would like to work on this

**Comment by JeanMeche** [comment]
We're still looking for a PR for this !

**Comment by amilamen** [comment]
I'll do it !

**Comment by amilamen** [comment]
@JeanMeche I got a little hot, but that's okay!
