### ISSUE TITLE
Angular DevTools are not working in Brave Browser

### ISSUE THREAD

**Issue by k3nsei** [angular/angular#52623]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

- Install Brave Browser (chromium based browser)
- Open browser
- Install Angular DevTools
- Open angular project in new tab
- Open brave DevTools

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

Angular DevTools tab should be visible in Brave DevTools

### Please provide a screenshot if possible [Bug Report only]

![image](https://github.com/angular/angular/assets/190422/54d62512-b710-4d0e-81d6-fe50ffda9cd1)

![image](https://github.com/angular/angular/assets/190422/02c2093e-dbb6-41ce-8873-360f3c66e2b1)

### Please provide the exception or error you saw [Bug Report only]

```true
N/A
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version. [Bug Report only]

```true
Yes, as Brave is Chromium based this extension should work. But for me it is only working in Chrome (shame google to force your browser on users).
```

**Comment by sasidharansd** [comment]
Hi @k3nsei , could you please provide steps to replicate. I tried to run a angular app in my local in the BRAVE browser and I could see the angular devtools. 

<img width="1440" alt="Screenshot 2023-11-08 at 7 29 31 PM" src="https://github.com/angular/angular/assets/47988127/92c670d5-acc2-428c-b4f0-0d1de49291d0">

**Comment by k3nsei** [comment]
I think the source of this problem could be an automatic browser update at some point. When I restored the default devtools options after clicking the button shown in the screenshot provided. It worked again.

![image](https://github.com/angular/angular/assets/190422/d3ca80e0-2497-4c82-ab66-234059f09030)
