### ISSUE TITLE
docs: Remove link pill in dynamic component page

### ISSUE THREAD

**Issue by amilamen** [angular/angular#52620]
### Describe the problem that you experienced

Dynamic Component link ([https://angular.dev/guide/components/](https://angular.dev/guide/components/)) redirect to Page Not Found.

You can also try this link ([https://angular.dev/api/core/ComponentFactory](https://angular.dev/api/core/ComponentFactory)) and click on Dynamic Component.

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/

**Comment by twerske** [comment]
@JeanMeche is this a known missing API page?

**Comment by JeanMeche** [comment]
This is linking issue. 
Since it is a deprecated API entry, I'd simply remove the pill.

**Comment by twerske** [comment]
This PR was merged into the repository by commit https://github.com/angular/angular/commit/867161f2048bcff7873350ff76ce86540b41d4c2.
