### ISSUE TITLE
docs-infra: add update.angular.io to angular.dev

### ISSUE THREAD

**Issue by twerske** [angular/angular#52633]

**Comment by patHyatt** [comment]
@twerske Not sure if you are the right person here but it looks `ngbot` is causing repetitive tagging. 
It looks like it's trying to alpha sort tags and conflicting with the original order

![image](https://github.com/angular/angular/assets/296125/88474439-2f0f-48f0-a35b-7cd785f68c87)

**Comment by twerske** [comment]
> @twerske Not sure if you are the right person here but it looks `ngbot` is causing repetitive tagging. It looks like it's trying to alpha sort tags and conflicting with the original order
> 
> ![image](https://user-images.githubusercontent.com/296125/281594234-88474439-2f0f-48f0-a35b-7cd785f68c87.png)

Yeah it's fixed now - you'll see this on a bunch of issues :)

**Comment by JeevanMahesha** [comment]
Hi @twerske , I'm interested in taking on the issue of adding update.angular.io to angular.dev. Do you mind providing some more context on what we're looking to do here?

**Comment by twerske** [comment]
sure - I think this is blocked until Anguler.dev can be built locally from this repo. After that, we'd like to move https://github.com/angular/angular-update-guide into the angular.dev/update page

**Comment by danieljancar** [comment]
Hey, seems like the time for this is now, I'd like to work on it.

For clarification:
- Change the theme, layout and styling of `update.angular.io`, which was completely Angular Material based,  to the Angular.dev preset?
- Integrate the Application fully into `adev` as a new feature folder?

Thanks for some more detail and feedback. 😄

**Comment by twerske** [comment]
> Hey @twerske and everyone else
> 
> Seems like the time for this is now, I'd like to work on it.
> 
> For clarification:
> 
> * Change the theme, layout and styling of `update.angular.io`, which was completely Angular Material based,  to the Angular.dev preset?
> * Integrate the Application fully into `adev` as a new feature folder?
> * Route should be `angular.dev/update`, which is already used in docs?
> 
> Thanks for some more detail and feedback. 😄

Sorry for the late reply! My notifications are a mess...

Yes option 2 is what was intended - pulling the guide into the ADEV website (should be a single guide page with dynamic json loaded based on user selection of the versions they're migrating and targeting.)
