### ISSUE TITLE
docs: template reference variable page doesn't exist

### ISSUE THREAD

**Issue by amilamen** [angular/angular#52634]
### Describe the problem that you experienced

When I tried to navigate to template reference variable page (https://angular.dev/guide/glossary#template-reference-variable) from this section (https://angular.dev/guide/defer#on-viewport), I got page not found error.

I then tried to navigate to the glossary (https://angular.dev/guide/glossary) and got same error.

The same applies to (https://angular.dev/guide).

### Enter the URL of the topic with the problem

https://angular.dev/guide/glossary#template-reference-variable

**Comment by twerske** [comment]
The glossary has been removed for Angular.dev - these links should be removed and cleaned up! This is a great contributors first issue!

**Comment by amilamen** [comment]
> The glossary has been removed for Angular.dev - these links should be removed and cleaned up! This is a great contributors first issue!

Alright !
Thank you so much @twerske !

**Comment by JeevanMahesha** [comment]
I will pick up this @twerske
