### ISSUE TITLE
docs-infra: a11y improvement suggestion in Property Binding tutorial

### ISSUE THREAD

**Issue by alyssamichelle** [angular/angular#52639]
# Property Binding tutorial
### [Bind to contentEditable](https://angular-dev-site.web.app/tutorials/learn-angular/property-binding#bind-to-contenteditable)

My screenreader is skipping over the `[]` completely. I thought about different options to have it announce them and I think the best would be to change the copy and put their title inline for all to see. This could help people using assistive technology but also beginners who don't know what to reference this syntax as.
![image](https://github.com/angular/blossom/assets/1058831/0af50086-8d57-4442-867c-1bc4ae95c28e)

Current:
```
Next, bind the contentEditable attribute of the div to the isEditable property by using the [] syntax.
```

Suggested Fix:
```
Next, bind the contentEditable attribute of the div to the isEditable property by using the square brackets syntax [].
```

Alternatively you could have a hidden element that labels the `<code>[]<code/>` block with aria-labeledby?

**Comment by dmmishchenko** [comment]
I can work on this. I suggest to change code to `<code aria-label="square brackets">[]</code>`
@alyssamichelle what are you thinking?

**Comment by dmmishchenko** [comment]
PR created: https://github.com/angular/angular/pull/52807

**Comment by twerske** [comment]
This PR was merged into the repository by commit https://github.com/angular/angular/commit/4d868a3df9d2eff886e23e41381cc52cef18ec0d.
