### ISSUE TITLE
docs: Investigate yarn for embedded editor instead of npm

### ISSUE THREAD

**Issue by twerske** [angular/angular#52642]
suggested by @crisbeto https://github.com/angular/blossom/pull/799#discussion_r1372117381

**Comment by MikaelSvanasbakken** [comment]
Just wanted to inform that the URL is dead.

**Comment by JeanMeche** [comment]
Confirming what @leoortizz saw, in the webcontainers npm is the fastest compared to yarn/pnpm. 
At this with the projects we run in them.
