### ISSUE TITLE
docs-infra: migrate to eslint

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#52651]
It should be migrated to typescript-eslint.

**Comment by millerraycell** [comment]
I was looking this request, and checked that there's some custom tslint rules in use, will these rules still be used? on the eslint rules we might have the case for the coverage of the cases

**Comment by JeanMeche** [comment]
The whole repo relies on using TSLint and this is an issue that dates back prior to opensourcing this project. 

This will be migrated with the whole repo.
