### ISSUE TITLE
docs-infra: Setup testing infrastructure for docs generation pipeline

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#52653]
Currently, the code in the `prerender` folder (which contains docs generation pipeline) doesn't have tests, which makes it quite brittle to add/modify logic there. It'd be great to setup test infrastructure around that subsystem to avoid regressions.

**Comment by JeanMeche** [comment]
We have a minimal setup, far from perfect but we can build on top of this when we fix bugs in that future. 
We'll make sure bugfixes introduce a better coverage to prevent future regressions.
