### ISSUE TITLE
docs: rename existing file in editor

### ISSUE THREAD

**Issue by ExactlyNoSense** [angular/angular#52652]
Clicking on the code editor's tab doesn't spawn an input to change the file name. The only way to do it right now is to remove the file and create a new one

[cast.webm](https://github.com/angular/blossom/assets/5513289/b7edbc16-9745-48e3-b53d-3f2d5764910d)

**Comment by mikalcallahan** [comment]
Not sure if anyone is working on this but I've got a fix on local. I need to swap the icon for a proper "rename" icon but if this is the general functionality we're going for I'll cleanup and create a PR

https://github.com/angular/angular/assets/14881167/864a9819-26fe-4322-b057-fd9c9d77b6c7
