### ISSUE TITLE
docs: Implement API reference

### ISSUE THREAD

**Issue by twerske** [angular/angular#52663]
- [x] mark deprecated methods/props in the card - https://github.com/angular/blossom/pull/727
- [x] internal method is visible E.g. https://angular.dev/api/core/OutputEmitterRef
- [x] improve scrolling UX/UI
- [x] github link - https://github.com/angular/blossom/pull/853
- [x] support `const` - https://github.com/angular/blossom/pull/650
- [x] support `decorator`- https://github.com/angular/blossom/pull/822
- [x] support `directive`
- [x] support `element` - https://github.com/angular/blossom/pull/952
- [x] support `block` (control flow and defer) - https://github.com/angular/blossom/pull/952
- [x] support `enum` - https://github.com/angular/blossom/pull/665
- [x] support `function` - https://github.com/angular/blossom/pull/670
- [x] support `interface` - https://github.com/angular/blossom/pull/667
- [x] support `pipe` - https://github.com/angular/blossom/pull/673
- [x] support `ngModule` - https://github.com/angular/blossom/pull/673
- [x] support `Type Alias` - https://github.com/angular/blossom/pull/807
- [x] Polish the code displayed
- [x] Scroll snap of the methods
- [x] Remove the package reference pages (and links to core packages on each page)
- [x] append `abstract` keyword as prefix for abstract classes in `docs-code` - https://github.com/angular/blossom/pull/808
- [x] featured APIs - https://github.com/angular/blossom/pull/809
- [x] display navigation list - https://github.com/angular/blossom/pull/918 or https://github.com/angular/blossom/pull/815
- [x] support prerendering - waiting for release angular-cli fix - https://github.com/angular/blossom/pull/871
- [x] `<code-example path="common/pipes/ts/lowerupper_pipe.ts" region=LowerUpperPipe>` - old ExampleViewer occurences in the descriptions - should we remove them? - https://github.com/angular/blossom/pull/880
- [x] https://docs.google.com/spreadsheets/d/1scJOt19SVcXPypTu3NBsib8ywuiTKCNO_yoRPbSYOIQ/edit#gid=0 - https://github.com/angular/blossom/pull/727
- [x] support block (@if etc) - https://github.com/angular/blossom/pull/855
- [x] remove `%20` from url - https://github.com/angular/blossom/pull/865
- [x] links in https://angular-dev-site.web.app/api/router/RouterLink rendering weirdly - I think it should be fixed by https://github.com/angular/blossom/pull/855
- [x] usage note lists and elements incorrect styling - 855 and https://github.com/angular/blossom/pull/872
- [x] https://github.com/angular/blossom/issues/915
- [x] https://github.com/angular/blossom/issues/911
- [ ] `{@link...}` - blocked due to current JSON structure
- [ ] `{@example...}` - blocked due to current JSON structure
- [x] Add link to code in repo 
- [x] Fix card overflowing (cf https://angular.dev/api/platform-browser/withHttpTransferCacheOptions) 
- [x] Some pipes are reported a classes (`AsyncPipe`, `KeyValuePipe`) 
- [x] Replace `<div class="alert">` with mardown alerts.  Ex: [afterNextRender](https://angular.dev/api/core/afterNextRender?tab=description)
- [x] Display deprecation message on deprecated entries
- [x] Package page (cf `PACKAGE.md`), ex: https://angular.io/api/localize 
- [ ] Signatures not readable: https://angular.dev/api/core/EventEmitter
- [x] Overloads not showing up (https://angular.dev/api/core/contentChildren)
- [ ]  Have a filter for developer preview (would probably depend on how we move on from #52979)

**Comment by JeanMeche** [comment]
Added: removing html alerts blocks.

**Comment by JeanMeche** [comment]
Added: Currently we don't display the deprecation message for deprecated entries.

**Comment by JeanMeche** [comment]
Added: We don't have page for the root of each package, like AIO had. For example : https://angular.io/api/localize

**Comment by JeanMeche** [comment]
Note: I unchecked the `internal` item. For example `ngMetadataName` is visible here: https://angular.dev/api/core/InjectionToken

**Comment by JeanMeche** [comment]
We should probably have a way to filter dev preview items like the filter we have on AIO.
