### ISSUE TITLE
docs: Add Angular.io Glossary terms added to Algolia search index in Angular.dev

### ISSUE THREAD

**Issue by twerske** [angular/angular#52667]

**Comment by johnnygerard** [comment]
Should [aio/content/guide/glossary.md](https://github.com/angular/angular/blob/18929040704828bf4caf76797ab141ca101c4b5f/aio/content/guide/glossary.md) be migrated to [adev/src/content/guide](https://github.com/angular/angular/tree/18929040704828bf4caf76797ab141ca101c4b5f/adev/src/content/guide)?
