### ISSUE TITLE
(bug) (angular.dev): StaticProvider page doesn't exist in new angular doc (https://angular.dev/api/core/StaticProvider)

### ISSUE THREAD

**Issue by amilamen** [angular/angular#52669]
### Describe the problem that you experienced

When I tried to navigate to StaticProvider page ((https://angular.dev/api/core/StaticProvider) from this section (https://angular.dev/api/core/Injector), I got page not found error.

### Enter the URL of the topic with the problem

https://angular.dev/api/core/StaticProvider

**Comment by twerske** [comment]
@JeanMeche is this a known missing API?

**Comment by JeanMeche** [comment]
Yes, this one is a known missing API.

**Comment by twerske** [comment]
Closing as known missing - you can track this in #52663
