### ISSUE TITLE
docs: Image assets do not load in `preview` on `docs-code`

### ISSUE THREAD

**Issue by twerske** [angular/angular#52666]
Code examples with the preview should be able to load relevant images in their `src`

**Comment by bencodezen** [comment]
This still an issue as referenced in https://github.com/angular/angular/issues/55163#issuecomment-2033077238

**Comment by JeanMeche** [comment]
My Bad, this particular issue is resolved, It was about this images in the markdown files. 
But we still have an issue with the images in the webcontainers app.
