### ISSUE TITLE
docs: Replace really ugly images

### ISSUE THREAD

**Issue by twerske** [angular/angular#52661]
The docs have a lot of old (ugly) images!

Our new docs [enable Mermaid charts to make beautiful charts with code!](https://angular.dev/guide/di/hierarchical-dependency-injection) (at the bottom for example)
Pick an image (on any docs page) and convert it to Mermaid!

**Comment by nektobit** [comment]
@twerske page not found
https://angular-dev-site.web.app/kitchen-sink#charts-amp-graphs

**Comment by JeanMeche** [comment]
I've replaced the link !

**Comment by reafernandes10** [comment]
@josephperrott I would like to work on this issue. Could you please tell me why have you commented out your Mermaid flowchart and marked it as todo? I see this for most of the flowcharts present in the Angular docs.

<img width="565" alt="image" src="https://github.com/angular/angular/assets/150733676/797bb25c-c0ef-4de8-9451-bd76a14b11b7">

**Comment by JeanMeche** [comment]
Without any specific image to replace, I'll close this.
