### ISSUE TITLE
docs: Bad redirection in core Injector page for providers link

### ISSUE THREAD

**Issue by amilamen** [angular/angular#52670]
### Describe the problem that you experienced

In this page (https://angular.dev/api/core/Injector), when I click on providers link, it redirects me to (https://angular.dev/overview) and the attribute [href] equals to (https://angular.dev/docs).

### Enter the URL of the topic with the problem

https://angular.dev/api/core/Injector

**Comment by twerske** [comment]
@JeanMeche is this a known missing API?

**Comment by amilamen** [comment]
@twerske I can help to fix this issue.
