### ISSUE TITLE
Is it possible to enable multi-language support on the official website documentation?

### ISSUE THREAD

**Issue by fantasy0v0** [angular/angular#52672]
### Describe the problem that you experienced

The translations are currently dispersed across different websites.

Is it possible to leverage Angular Internationalization?

### Enter the URL of the topic with the problem

https://angular.dev/

**Comment by twerske** [comment]
Thanks for your feedback! We're currently in the process of researching and creating a new path for how we localize our docs. See https://github.com/angular/angular/issues/52706 which is tracking this issue!
