### ISSUE TITLE
(bug) (angular.dev): Bad redirection in core Injector page for injection tokens link

### ISSUE THREAD

**Issue by amilamen** [angular/angular#52671]
### Describe the problem that you experienced

In this page (https://angular.dev/api/core/Injector), when I click on injection tokens link, it redirects me to (https://angular.dev/overview) and the attribute [href] equals to (https://angular.dev/docs).

### Enter the URL of the topic with the problem

(https://angular.dev/api/core/Injector

**Comment by twerske** [comment]
@JeanMeche is this a known missing API?

**Comment by JeanMeche** [comment]
This is a linking issue. 
The 2 brokens links were pointing to glossary. We could like point them to the DI guide.

**Comment by JeanMeche** [comment]
Let's close this in favor of #52670, it's the same API page that has a broken link.
