### ISSUE TITLE
Angular.dev website usability issues

### ISSUE THREAD

**Issue by SebastianEShelby** [angular/angular#52681]
### Describe the problem that you experienced

I have some small gripes with the new [angular.dev](https://angular.dev/) website. It has a few UX issues compared to the older version

- The first page is slow to load and slow to navigate due to new animated design
- The side menu is now difficult to navigate and no longer offers a birds eye view when opening nested links. It also now shows a longer animation when opening a sub-menu item which is less practical.

Please reconsider the UI of the new website. I would prefer to see better speeds and responsiveness while navigating the docs.

### Enter the URL of the topic with the problem

[angular.dev](https://angular.dev/)

### Describe what you were looking for in the documentation

simply navigating through different documentation pages is now slow and cumbersome

### Describe the actions that led you to experience the problem

Reviewing the new website

### Describe what you want to experience that would fix the problem

- Remove all unnecessary animations from the website. Use fast (but not jittery) transitions instead
- Allow a bird's eye view of the navigation menu when opening sub-menu items instead of navigating away from the top-level menu items
- Overall prioritize website responsiveness over using animations

**Comment by twerske** [comment]
Thank you for your feedback to the beta Angular.dev! We're collecting all subjective feedback in a doc and this will be recorded there.

The initial page is mostly meant for marketing. FWIW we're worked with Chrome and the performance score is 100% due to it's progressive enhanced animation. Besides scrolling the animation for fun, it's not critical that users load it before moving to the actual Docs and Tutorials tabs. 

If you prefer less animation, I'd suggest using `prefer-reduced-motion` on your browser for the experience you are aiming to have.

**Comment by SebastianEShelby** [comment]
> Thank you for your feedback to the beta Angular.dev! We're collecting all subjective feedback in a doc and this will be recorded there.
> 
> The initial page is mostly meant for marketing. FWIW we're worked with Chrome and the performance score is 100% due to it's progressive enhanced animation. Besides scrolling the animation for fun, it's not critical that users load it before moving to the actual Docs and Tutorials tabs.
> 
> If you prefer less animation, I'd suggest using `prefer-reduced-motion` on your browser for the experience you are aiming to have.

Thanks for your response. I would highly suggest the Angular team performs an extensive review of the website's performance (mainly docs section) based on developer use cases. In a larger sample of users I can assure you the issues won't be as "subjective" and a 100% performance score doesn't mean anything when in reality the website is just... slow. The docs section of [angular.io](angular.io) is much snappier than the new [angular.dev](angular.dev)
