### ISSUE TITLE
Some examples in Angualr.dev are not rendering properly

### ISSUE THREAD

**Issue by dwilches** [angular/angular#52684]
### Describe the problem that you experienced

In [this page](https://angular.dev/api/router/CanActivateFn?tab=description), instead of the example's code, I can see placeholders like:

    {@example router/route_functional_guards.ts region="CanActivateFn"}

![image](https://github.com/angular/angular/assets/3975401/dc7730f2-3e75-4c1f-ab18-490279b01ed6)

In the Angular.io site, the examples are rendered ok:

![image](https://github.com/angular/angular/assets/3975401/81fda7fa-5103-4e66-900f-8d71aa3f92f0)

### Enter the URL of the topic with the problem

https://angular.dev/api/router/CanActivateFn?tab=description

**Comment by twerske** [comment]
This is still in progress and being tracked in #52663
