### ISSUE TITLE
Angular's compatibility version with node.js is missing the new entry for Angular v17

### ISSUE THREAD

**Issue by Julien-Marcou** [angular/angular#52686]
### Describe the problem that you experienced

https://github.com/angular/angular/blob/3f2501ecbdfc11010b9b54c485ac6914697cd277/aio/content/guide/versions.md?plain=1#L11-L13

In this table, there is no entry for the compatibility between Angular v17 and Node.js v20

As stated in this commit: https://github.com/angular/angular/commit/19a426d54e8bb4c8fdfb1b66dadbccc4bafbfb29
Angular v17 is now supporting Node.js `^v20.9.0`, which is the new Node.js LTS

### Enter the URL of the topic with the problem

https://angular.io/guide/versions#actively-supported-versions

### Describe what you were looking for in the documentation

I was looking at the compatibility between Angular v17 and Node.js v20

### Describe the actions that led you to experience the problem

I wanted to know if I could upgrade my project to use Node.js 20 with Angular v17

### Describe what you want to experience that would fix the problem

Add a new entry for Angular v17 that explicitly states it's supporting Node.js v20

### Provide any additional information here in as much as detail as you can

I tried to search for the same information on the new angular.dev website, and on this page https://angular.dev/tools/cli/setup-local#dependencies, I clicked on the "Angular's version compatibility" link, which redirected me to this page https://angular.dev/versions, but this page does not exist ^^

**Comment by JoostK** [comment]
This was addressed in #51443 just now.
