### ISSUE TITLE
`effect` and `computed` throws circular dependency when `ErrorHandler` creates `effect` `computed` during construction (or one of its dependencies does)

### ISSUE THREAD

**Issue by blueiceprj** [angular/angular#52680]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

After upgrade to 17 signal objects not working properly

```
Injectable({ providedIn: 'root' })
export class PrincipalService {
    _loginCompleted = signal<boolean>(false);
    _token = signal<string>(null);
    user = signal<SessionState>(createInitialSessionState());
    user$ = toObservable(this.user);
```

```
apiCount = signal<number>(0);
constructor() {
        effect(() => {
            setTimeout(() => {
                this.visible.set(this.apiCount() != 0);
            }, 0);
        }, {
            allowSignalWrites: true
        });
    }
```

### Please provide the exception or error you saw

```true
Error: NG0200: Circular dependency in DI detected for ErrorHandler. Find more at https://angular.io/errors/NG0200
    at throwCyclicDependencyError (core.mjs:292:11)
    at R3Injector.hydrate (core.mjs:6158:13)
    at R3Injector.get (core.mjs:6033:33)
    at effect (core.mjs:14259:35)
    at toObservable (rxjs-interop.mjs:48:27)
    at new PrincipalService (principal.service.ts:22:25)
    at Object.PrincipalService_Factory [as factory] (ɵfac.js:1:1)
    at core.mjs:6164:43
    at runInInjectorProfilerContext (core.mjs:867:9)
    at R3Injector.hydrate (core.mjs:6163:17)



Error: NG0200: Circular dependency in DI detected for ErrorHandler. Find more at https://angular.io/errors/NG0200
    at throwCyclicDependencyError (core.mjs:292:11)
    at R3Injector.hydrate (core.mjs:6158:13)
    at R3Injector.get (core.mjs:6033:33)
    at effect (core.mjs:14259:35)
    at new FuseProgressBarService (progress-bar.service.ts:24:15)
    at Object.FuseProgressBarService_Factory [as factory] (ɵfac.js:1:1)
    at core.mjs:6164:43
    at runInInjectorProfilerContext (core.mjs:867:9)
    at R3Injector.hydrate (core.mjs:6163:17)
    at R3Injector.get (core.mjs:6033:33)

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0
Node: 18.18.2
Package Manager: npm 9.8.1
OS: darwin x64

Angular: 17.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1700.0
@angular-devkit/build-angular      17.0.0
@angular-devkit/build-ng-packagr   0.1002.0
@angular-devkit/core               17.0.0
@angular-devkit/schematics         17.0.0
@angular/cdk                       16.2.12
@angular/flex-layout               15.0.0-beta.42
@angular/material                  16.2.12
@angular/material-moment-adapter   16.2.12
@angular/youtube-player            16.2.12
@schematics/angular                17.0.0
rxjs                               7.8.1
typescript                         5.2.2
zone.js                            0.14.2
```

**Comment by atscott** [comment]
Can you provide a reproduction? The `effect` implementation attempts to inject `ErrorHandler` so I'm assuming you are using an `effect` inside a class that your custom `ErrorHandler` also injects.

**Comment by blueiceprj** [comment]
Sorry! Its a huge project. Thats just part of code I shared. They are just root injected services. But these services call by custom error handler.

**Comment by blueiceprj** [comment]
Ok. I figure out that. Same error. https://stackblitz.com/edit/stackblitz-starters-ppn9ig?file=src%2Fmain.ts

**Comment by blueiceprj** [comment]
Still not working with last version. Is there any news?

**Comment by pkozlowski-opensource** [comment]
We can mitigate this situation by getting the `ErrorHandler` on-demand in the effect. Marking it as a bug than we can fix.

**Comment by blueiceprj** [comment]
Fixed. Thanks guys

**Comment by blueiceprj** [comment]
However, if you use ErrorHandler, there is a problem with this too. A simple data type, string, boolean etc. If I use them, it works, but when I change the data type with a complex interface like in this example, effect doesn't work.

Please check this example https://stackblitz.com/edit/stackblitz-starters-2fvmzs?file=src%2Fmain.ts

@atscott

**Comment by atscott** [comment]
@blueiceprj I don't understand what your demo is trying to show or what you're saying isn't working. Can you explain this more?

**Comment by blueiceprj** [comment]
Same example. But I changed signal object from primitive type to object type like string to LoginState 
```
export interface UserState {
  loggedIn: boolean;
  username: string;
}
```

And try to change properties of this class (loggedIn, username) like that. 

```
effect(
      () => {
        console.log('Changed', this.loginState());
      },
      {
        allowSignalWrites: true,
      }
    );
.............................
.......................
login() {
    this.loginState.update((v) => {
      /* BUT IT DOESN'T WORK */
      /*
      v.loggedIn = true;
      v.username = 'anyone';
      return v;
    */
      /* BUT IT WORKS */
      const newLogin = { ...v };
      newLogin.loggedIn = true;
      newLogin.username = 'anyone';
      return newLogin;
    });
  }
```
First Version

<img width="538" alt="Ekran Resmi 2024-01-11 23 10 32" src="https://github.com/angular/angular/assets/1829975/f94cb80d-8dc8-460f-88a6-8b32d12c4aa5">

Second version

<img width="509" alt="Ekran Resmi 2024-01-11 23 09 30" src="https://github.com/angular/angular/assets/1829975/07957ee9-4575-4e2b-b612-09ba5185ab1b">

Result : I always need to copy of signal value to trigger effect function.

**Comment by atscott** [comment]
> Result : I always need to copy of signal value to trigger effect function.

Ah, I see - I was expecting this to be related to the `ErrorHandler` again. This is about signal updates and mutability. The default equality function for signals is comparing by reference. If you want a mutable signal, you have to change its equality function. I've updated the example [here](https://stackblitz.com/edit/stackblitz-starters-uhmmhe?file=src%2Fmain.ts)

**Comment by blueiceprj** [comment]
Ok. I see. Thanks.
