### ISSUE TITLE
Invalid target element for this operation in IE9

### ISSUE THREAD

**Issue by wikimo** [angular/angular#5268]
How about "Invalid target element for this operation" in IE9， angular 1.4.1， 
the error happend in code like this

```
<tr ng-repeat="item in data.items  | filter:query " ng-include="item.is_query ? 'views/user/query.show.html':'views/user/query.item.html'"></tr>
```

search with google get some info 

* innerHTML is read only in tbody so the error happend

* http://stackoverflow.com/questions/4729644/cant-set-innerhtml-on-tbody-in-ie

* http://stackoverflow.com/questions/28316096/invalid-target-element-for-this-operation-ngtable

* https://github.com/esvit/ng-table/issues/667

say there is no resolution.

what should i do, thanks for your help.

**Comment by woppa684** [comment]
You're in the wrong repo I guess? This repo is about Angular2. Angular 1.x is on https://github.com/angular/angular.js

**Comment by wikimo** [comment]
i'm sorry, closed it.
