### ISSUE TITLE
Too much contrast in Angular.dev's dark mode

### ISSUE THREAD

**Issue by dwilches** [angular/angular#52682]
### Describe the problem that you experienced

In the new Angular.dev site the contrast between the foreground and background is so high that it makes reading difficult when using dark mode:

![image](https://github.com/angular/angular/assets/3975401/6d1c5e8e-f143-4134-931c-2c4311c9c00b)

Compare that with the previous site, it was easier on the eyes:
![image](https://github.com/angular/angular/assets/3975401/0d8813d0-662e-4275-a26c-46587b0f9fb3)

### Enter the URL of the topic with the problem

https://angular.dev/

**Comment by byjokese** [comment]
I would say it's too much a personal preference. I do enjoy more the new one. See GitHub in dark mode for example.

**Comment by twerske** [comment]
Thank you for your feedback to the beta Angular.dev! We're collecting all subjective feedback in a doc and this will be recorded there.

We're aiming for high accessibility and following best practice of modern web dark theming here :)
