### ISSUE TITLE
docs: make the first page of the interactive tutorial clear for new developers

### ISSUE THREAD

**Issue by DavidJournot** [angular/angular#52695]
### Describe the problem that you experienced

The interactive tutorial in angular.dev is excellent, I love it.

I found the first page of this tutorial to be very misleading though.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular#ready-to-explore-more-of-angular

### Describe what you were looking for in the documentation

I wanted to test the interactive tutorial, as if I was new to angular.

### Describe the actions that led you to experience the problem

First I read "You can also learn more in our guides and reference, or ng new.". 
This sentence had me wondering if i was at the right place. Why suggesting me to do something else now?

Then i read "Ready to explore more of Angular?", with four links:
- What is angular?
- Angular Roadmap
- Playground
- Angular youtube course

My first reaction was: oh nice, the tutorial is actually divided in four sections! (Yes... I'm stupid ^^)
I clicked one of the links and got kicked out of the tutorial instantly. Bad UX

### Describe what you want to experience that would fix the problem

Remove misleading links and suggest people to click on the right-arrow button to go to the next step of the tutorial.

Maybe those "learn more" links may be suggested at the very end of the tutorial.

**Comment by twerske** [comment]
I think this is a super valid point - thank you! We'll look into it!

**Comment by bencodezen** [comment]
Closed by https://github.com/angular/angular/pull/55051
