### ISSUE TITLE
createEmbeddedView crashes if it inserts a view with a component that uses effect on angular 17

### ISSUE THREAD

**Issue by neo3587** [angular/angular#52690]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

When upgrading to angular 17, if a embeddedView that contains a component with effect is inserted through createEmbeddedView, the application crashes despite the effect is called in the constructor.

After some testing it seems that it was still working fine until 17.0.0-rc.1 and started failing at 17.0.0-rc.2.

This error doesn't happen in angular 16.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-bk2ny7?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
Error: NG0602: effect() cannot be called from within a reactive context. Call `effect` outside of a reactive context. For example, schedule the effect inside the component constructor. Find more at https://angular.io/errors/NG0602
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0
Node: 18.18.0
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 17.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0
@angular-devkit/build-angular   17.0.0
@angular-devkit/core            17.0.0
@angular-devkit/schematics      17.0.0
@schematics/angular             17.0.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by neo3587** [comment]
Update: 

After digging a bit today, I found that this only happens when `createEmbeddedView` is called inside an `effect`, using it outside or even a "dirty hack" like `setTimeout(() => this.vcref.createEmbeddedView(template))` will consider that the `effect` of the inserted component is within a injection context again.

Also note that this only happens with when the inserted component uses `effect`, other functions that must be run within a injection context like `inject` or `takeUntilDestroyed` runs fine.

**Comment by fen89** [comment]
I encountered this issue when opening a modal from @ng-bootstrap/ng-bootstrap (which calls `createEmbeddedView` under the hood when creating a modal from a template).

If i wrap the call to open the modal inside a `setTimeout` as per suggestion from @neo3587 everything is working again without an error.

**Comment by filipkranjec** [comment]
Maybe try placing createEmbeddedView inside afterFirstRender instead of effect because you should not access vcr before ngAfterViewInit has been called.

So the could would go something like this: 
```
afterNextRender(() => {
      if (this.svc.open())
        this.vcref.createEmbeddedView(this.template);
      else
       this.vcref.clear();
    });
    
```

**Comment by neo3587** [comment]
@filipkranjec 

That would leave the `open` signal outside the `effect`, which would break all the wanted reactivity, also it's not a lifecycle issue, you can use the `ViewContainerRef` even in the constructor itself without issues.

You could even do something like:
```
let can_insert = false;
afterNextRender(() => can_insert = true);
effect(() => {
    const is_open = this.svc.open(); // called early because the the next if condition
    if (!can_render)
        return;
    if (is_open)
        this.vcref.createEmbeddedView(this.template);
    else
        this.vcref.clear();
});
```
and you would be facing the same error.

Also note that this exclusively happens when the inserted component has an `effect` too.


BTW: seems like using `untracked(() => this.vcref.createEmbeddedView(this.template));` doesn't trigger the error... and it's less dirty than using the `setTimeout`.

**Comment by kewur** [comment]
this is happening to my directive as well, I've tried the setTimeout and untracked() workarounds as suggested with no luck. here's my implementation of the directive. only showing some css animations if the condition is true. It's supposed to work exactly like ngIf plus hte loading animation

[stackblitz](https://angular-rtgu1a.stackblitz.io)

**Comment by neo3587** [comment]
Angular v17.3.0 fixed this issue (probably as a side-effect)
