### ISSUE TITLE
The defer block doesnt work properly with @defer (when condition)

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#52707]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

As per the docs (https://angular.io/guide/defer#triggers) the syntax or the `@defer when` is:

```
@defer (when cond) {
  <calendar-cmp />
}
```

But the below code doesnt work:

```
@defer (when (emailConfirmed && !resumeExists))
{
<app-dialog disableClose="true">
......
</app-dialog>
}
```

Whereas this works perfectly fine:

Component:
```
  isVisible() {
    return (this.emailConfirmed && !this.resumeExists);
  }

```

Template:
```
@defer (when isVisible()){
{
<app-dialog disableClose="true">
......
</app-dialog>
}

```

### Please provide a link to a minimal reproduction of the bug

The above code added in any component should reproduce same behavior

### Please provide the exception or error you saw

```true
No exception is thrown but it doesnt work as expected.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0-rc.4
Node: 18.18.2
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 17.0.0-rc.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... google-maps, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.4
@angular-devkit/build-angular   17.0.0-rc.4
@angular-devkit/core            17.0.0-rc.4
@angular-devkit/schematics      17.0.0-rc.4
@angular/cli                    17.0.0-rc.4
@angular/fire                   16.0.0
@angular/pwa                    17.0.0-rc.4
@schematics/angular             17.0.0-rc.4
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

**Comment by AndrewKushnir** [comment]
@naveedahmed1 I've just tested this behavior using [Stackblitz](https://stackblitz.com/edit/stackblitz-starters-lcpuie) and it seems to be working as expected. I've also checked the generated code for the condition (to make sure there are no issues with parsing/compiling) and it looks good too (`ɵɵdeferWhen(ctx.emailConfirmed && !ctx.resumeExists)`). Could you please create a minimal repro so that we can perform further investigation? Thank you.

**Comment by AndrewKushnir** [comment]
> No exception is thrown but it doesnt work as expected.

Could you please also share what's the expected vs observed behavior that you are seeing?

**Comment by naveedahmed1** [comment]
Thank you Andrew for your quick response. I think you are right. I just read the docs again, and its mentioned there:

> Note: if the when condition switches back to false, the defer block is not reverted back to the placeholder. The swap is a one-time operation. If the content within the block should be conditionally rendered, an if condition can be used within the block itself.

In my case `emailConfirmed` is fetched from global variable, whereas `resumeExists` is false by default when user arrives on this page its  updated through an http call.

So, in case `emailConfirmed` is `true` it pick ups the default value of `resumeExists` and rendered the view. When the http response is received it does make `resumeExists` true but since the view is already rendered, we continue seeing the dialog.

**Comment by naveedahmed1** [comment]
I think we can close this issue, since its a coding error.
