### ISSUE TITLE
[ADEV] The extended diagnostic NG8109 page is missing 

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular#52709]
### Describe the problem that you experienced

The entry is missing in the index page : https://angular.dev/extended-diagnostics
But also the entire page is also missing: https://angular.dev/extended-diagnostics/NG8109

**Comment by Dhoni77** [comment]
Hi @twerske I would like to work on this

**Comment by sasidharansd** [comment]
If no one else is working on it, I would love to take this.

**Comment by heloproc** [comment]
The page is not missing. It is available at https://angular.dev/guide/extended-diagnostics.

The entry is missing in the index page because the page is not listed under the "Guides" section. It is listed under the "Advanced" section. 😂

**Comment by sasidharansd** [comment]
@JeanMeche  I have raised a PR adding the NG8109 page. Let me know if any any content needs to be added or changed. Thanks!

**Comment by JeanMeche** [comment]
@sasidharansd Thank for your help !

**Comment by twerske** [comment]
This PR was merged into the repository by commit https://github.com/angular/angular/commit/154f286d554f7be8a3d8b34b9e33d6715df71016.
