### ISSUE TITLE
Tour of Heroes > Display A List > "Standalone" Configuration Leads to Error

### ISSUE THREAD

**Issue by benclarkdev** [angular/angular#52702]
### Describe the problem that you experienced

In the ["Display a List"](https://angular.io/tutorial/tour-of-heroes/toh-pt2) section of the Tour of Heroes tutorial, the `standalone:true` configuration seems a bit misleading. 

The [live example on StackBlitz](https://stackblitz.com/run?file=src%2Fapp%2Fheroes%2Fheroes.component.html) shows that `app.module.ts` has been deleted, though there is no mention of it in the docs.

If you keep it as is, you get this problem:

```
Error: src/app/app.module.ts:11:5 - error NG6008: Component HeroesComponent is standalone, 
and cannot be declared in an NgModule. Did you mean to import it instead?

11     HeroesComponent
```

If I'm correct in seeing this as an error, it seems that you could either:
1. explain the benefits of configuring things as `standalone`, make a explicit instruction to delete `app.module.ts` (seemingly temporarily, as it returns later in the tutorial)
2. leave the `standalone` configuration off of it and edit the StackBlitz

I would love to write the changes, though I am not sure which direction you'd want to go.

### Enter the URL of the topic with the problem
https://angular.io/tutorial/tour-of-heroes/toh-pt2

### If this problem caused an exception or error, please paste it here
```true
Error: src/app/app.module.ts:11:5 - error NG6008: Component HeroesComponent is standalone,
and cannot be declared in an NgModule. Did you mean to import it instead?

11     HeroesComponent
```

**Comment by justin98m** [comment]
I also ran into this issue when following the **Tour of Heroes** tutorial on my local machine. In[ pt 1](https://angular.io/tutorial/tour-of-heroes/toh-pt1) of the tutorial when you verify that you code aligns in the  final code review section and then strictly follow [pt2's](https://angular.io/tutorial/tour-of-heroes/toh-pt2) instructions it will lead to the same error listed by @benclarkdev . 

I chose not to delete my app.module.ts  , then import `NgFor` in my app.module.ts instead of my `heroesComponent `and to not set standalone to true in `heroesComponent`. Having instructions to do so would greatly benefit the next tutorial goer.

**Comment by mas2405** [comment]
I faced the same issue while following up on the Tour of Heroes tutorial. I too chose not to delete the app.module.ts file as @justin98m 
Thanks @benclarkdev  @justin98m

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.

**Comment by wences44** [comment]
> I also ran into this issue when following the **Tour of Heroes** tutorial on my local machine. In[ pt 1](https://angular.io/tutorial/tour-of-heroes/toh-pt1) of the tutorial when you verify that you code aligns in the final code review section and then strictly follow [pt2's](https://angular.io/tutorial/tour-of-heroes/toh-pt2) instructions it will lead to the same error listed by @benclarkdev .
> 
> I chose not to delete my app.module.ts , then import `NgFor` in my app.module.ts instead of my `heroesComponent `and to not set standalone to true in `heroesComponent`. Having instructions to do so would greatly benefit the next tutorial goer.

Thank you @justin98m for your comment, I also ran into this issue the same way you did, and your comment help me solve it, following the same solution you shared.  Your post was very helpful!!!

**Comment by dungtranleapvn** [comment]
> I also ran into this issue when following the **Tour of Heroes** tutorial on my local machine. In[ pt 1](https://angular.io/tutorial/tour-of-heroes/toh-pt1) of the tutorial when you verify that you code aligns in the final code review section and then strictly follow [pt2's](https://angular.io/tutorial/tour-of-heroes/toh-pt2) instructions it will lead to the same error listed by @benclarkdev .
> 
> I chose not to delete my app.module.ts , then import `NgFor` in my app.module.ts instead of my `heroesComponent `and to not set standalone to true in `heroesComponent`. Having instructions to do so would greatly benefit the next tutorial goer.

Thanks. I followed your solution and it worked. Got kinda frustrated a little.

**Comment by farkalit76** [comment]
Thanks @justin98m It is working without any error.

----------Here is the app.modules.ts -->

import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { NgFor, NgIf, UpperCasePipe } from '@angular/common';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { HeroesComponent } from './heroes/heroes.component';

@NgModule({
  declarations: [
    AppComponent,
    HeroesComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    FormsModule,
    NgFor,
    NgIf,
    UpperCasePipe
  ],
  providers: [],
  bootstrap: [AppComponent]
})

export class AppModule { }

------------And here is herores.component.ts   ---------->
import { Component } from '@angular/core';
import { Hero } from '../hero';
import { HEROES } from '../mock-heroes';

@Component({
  //standalone: true,
  selector: 'app-heroes',
  templateUrl: './heroes.component.html',
  styleUrls: ['./heroes.component.scss']
})
export class HeroesComponent {
  heroes = HEROES;
  selectedHero?: Hero;

  onSelect(hero: Hero): void {
    this.selectedHero = hero;
  }

  hero: Hero = {
    id: 1,
    name: 'Windstorm'
  };
}
