### ISSUE TITLE
ngUpgrade question about angular.bootstrap definition

### ISSUE THREAD

**Issue by sclausen** [angular/angular#5270]
The definition of angular.bootstrap requires an `Element`, but `document.body`, like in the example, is of type `HTMLElement` which extends `Element`.

``` typescript
bootstrap(element: Element, modules?: any[], config?: angular.IAngularBootstrapConfig): UpgradeAdapterRef;
```

Why do I get the error `Argument of type 'HTMLElement' is not assignable to parameter of type 'Element'.`?

**Comment by PascalPrecht** [comment]
@sclausen can you provide a plunk that demonstrates the error?

**Comment by sclausen** [comment]
@PascalPrecht I have severe difficulties to set up a angular2 + typescript plunkr.
Unfortunately every plunkr with angular2 I could found is either outdated, or a js-setup.

But besides that, I might have a really messed up project setup and should work around that.
A modified [mgechev/angular2-seed](https://github.com/mgechev/angular2-seed) didn't complain about incompatible typings…
For future bugs, it would be great to have a working plunkr for basic angular2+typescript. Do you know any resources?
