### ISSUE TITLE
docs-infra: move Features APIs above the filter section & rename to "Most Common"

### ISSUE THREAD

**Issue by twerske** [angular/angular#52705]
Move the Feature APIs above the filter and rename to indicate what it is more clearly

This will also help with the section persists filtering and toggles

**Comment by Morad-m11** [comment]
Is this still open? I'd take it

**Comment by JeanMeche** [comment]
Feel free to drop a PR !

**Comment by Gortyser** [comment]
Isn’t it blocked? As I understand, `@angular/docs` is not open-sourced yet and we can’t build adev project.
This is a small issue yet it would be a bad idea to merge it without checking.
@twerske @JeanMeche correct me if I’m wrong.

**Comment by JeanMeche** [comment]
You're definitly right. I didn't double check the content of the issue.

**Comment by Morad-m11** [comment]
I got missing file errors whenever I tried to serve... Is that the reason?

**Comment by Gortyser** [comment]
Yes. There is no `@angular/docs` package, README is empty and probably there's more, I haven't dug too deep. It should be changed in the following weeks, you can try to check recent issues for more details.
Right now we can change the docs, but anything more complex will have to wait. Even CI/CD process is not finalized, but I could be wrong about this one.

**Comment by mvdluit** [comment]
From the previous discussion here i'm not sure if this is the case, but I would like to exclude deprecated references from the featured block **regardless** of the show `@deprecated` toggle. It does not make sense to feature references people should stop using.

**Comment by Gortyser** [comment]
> From the previous discussion here i'm not sure if this is the case, but I would like to exclude deprecated references from the featured/most common block **regardless** of the show `@deprecated` toggle. It does not make sense to feature references people should stop using.

That was my point as well in https://github.com/angular/angular/issues/52749, but I'm not sure it's still valid since we're renaming it to 'Most common'.

**Comment by twerske** [comment]
Thank you for your excitement in contributing - we're still working on making the app build in the monorepo with Bazel - stay tuned for when this issue is unblocked!
