### ISSUE TITLE
ngUpgrade - Infinite loop when not initialising template's bound object

### ISSUE THREAD

**Issue by yanivefraim** [angular/angular#5271]
**Edit**: It seems that the first issue is solved on alpha 46, see [this plunker](http://plnkr.co/edit/ougmat?p=preview).
 
I was playing with `ngUpgrade` module and getting an infinite loop when not initialising an object that is bound to a a template. While trying to isolate the issue (using Angular 2.0 without ngUpgrade) I got another error. I'm not sure if they are related, but I'll put both here (with plunker for both):

#### Issue 1: Infinite loop when using 'ngUpgrade' and not initialising template's bound object first:

```javascript```
import {Component, View, bootstrap, Input} from 'angular2/angular2';
import DataService from './data-service';

@Component({
    selector: 'app-cmp'
})
@View({
	template: `<div style="margin: 20px 0"><span>{{data.login}}</span> | <span> {{userData.name}}</span> <span><img style="height:100px;width:100px;vertical-align:middle;margin: 0 20px;" src="{{userData.avatar_url}}"><span></div>`
})
export default class NamesComponent {
  @Input() data: any;
  userData: any;
  constructor(private dataService: DataService) {
    this.userData = {};//if you put this in comment you get an infinite loop!!!
  }
  
  onInit() {
    //calling an ng1 service to get data:
    this.dataService.getUserNames(this.data.login).then((response) => {
      this.userData = response.data;
    });
  }
}
```

If I remove the following line `this.userData = {};` from the constructor I will get an infinite loop (be careful, it'll crash your browser). `dataService` is an ng1 service used by both ng1 and ng2.

[Plunker](http://plnkr.co/edit/psW53h?p=info) (I removed the call to github api and calling http://blabla.com because I do not want to make the infinite loop calling github's api) 
 
#### issue 2: NG2 Error if initialising an object inside constructor (will not happen if initialised on object's declaration) 

While trying to isolate the first (ngUpgrade) problem, using ng2 example, I saw that if I initialise an object that is bound to a template on the constructor, I will get a javascript error: 

`EXCEPTION: TypeError: Cannot read property 'properyName' of undefined in [null]`

If I initialise it on declaration, the error disappear.

See [plunker](http://plnkr.co/edit/EIQjA00QnaGnC7LyAqu9?p=preview) for full example.

Code (the relevant part is where I'm initialising `peopleData` object). 

```javascript```
import {Component, View, EventEmitter, Input} from 'angular2/angular2'
import {PeopleService} from './peopleService'

@Component({
  selector: 'my-person',
  inputs: ['name'],
  outputs: ['hello']
})
@View({
  template: `
    <div>
      <span>{{name}} -> {{peopleData.age}}</span>
      <button (click)="sayHello()">Say Hello</button>
    </div>
  `
})
export class Person {
  hello = new EventEmitter();
  @Input() data: any;
  peopleData: any;// = {age: 0};  ->when uncommenting this and commenting constructor content, the error disappears
  constructor(private peopleService:PeopleService) {
    peopleData = {age: 0};
  }
  
  sayHello(e) {
    this.hello.next(this.name);
  }
  onInit() {
    this.peopleService.getPeopelData().subscribe((people) => {
     people.filter((p) => this.data.id === p.id)[0]});
  }
}
```

**Comment by astec** [comment]
Regards **issue 2**. Probably you should use `this.` in constructor?
```
export class Person {
  peopleData: any;
  constructor(private peopleService:PeopleService) {
    this.peopleData = {age: 0};
  }
```

**Comment by yanivefraim** [comment]
Yep, 10x (my mistake).

I am closing this issue (the major one is fixed on alpha 46 and the second one was my mistake)
