### ISSUE TITLE
I'm testing angular 17 with SSR. I got the below error when using DOCUMENT in a component file.

### ISSUE THREAD

**Issue by exovus** [angular/angular#52713]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

RuntimeError: NG0210: The document object is not available in this context. Make sure the DOCUMENT injection token is provided.

 [vite] Internal server error: NG0210: The document object is not available in this context. Make sure the DOCUMENT injection token is provided.

I have injected the same in component constructor like this @Inject(DOCUMENT) private _document: Document but still the error is thrown. Do we need to add anything in serve config or app config file ?

**Comment by AndrewKushnir** [comment]
@exovus could you please let us know whether this is a new project or a project that you've upgraded to v17? If it was upgraded and added SSR support later, please let us know which Angular-related commands did you use.

Most likely there is some misconfiguration in your project and the server support is not enabled properly. Please make sure that the [provideServerRendering()](https://angular.io/api/platform-server/provideServerRendering) call is included into the `providers` array at bootstrap time. If the problem still exists, please create a minimal repro (in a form of GitHub repository), so that we can take a look.

**Comment by heloproc** [comment]
There are a few things that could be causing this error.

* **You may not have the `DOCUMENT` token registered in your app's root injector.** To check this, open your app's `app.module.ts` file and look for the following line:

```
import { DOCUMENT } from '@angular/common';

@NgModule({
  declarations: [...],
  imports: [...],
  providers: [
    DOCUMENT,
  ],
})
export class AppModule {}
```

If you don't see this line, add it and try again.
* **You may not be using the `DOCUMENT` token correctly.** Make sure that you are injecting the `DOCUMENT` token into your component constructor like this:

```
@Inject(DOCUMENT) private _document: Document;
```

* **You may be using the `DOCUMENT` token in a context where it is not available.** For example, you cannot use the `DOCUMENT` token in a component that is rendered outside of the browser.

If you are still getting this error after checking these things, please provide a more detailed description of your problem and we will be happy to help.﻿

**Comment by draylegend** [comment]
Not sure whether I should create new issue. But I ask here first.

I've created a new ng17 project with `ssr` and added a button that increments a counter:

```ts
@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'app-root',
  standalone: true,
  template: `<button (click)="count.set(count() + 1)">{{ count() }}</button>`,
})
class AppComponent {
  count = signal(0);
}
```

But the counter doesn't increase. What am I doing wrong?

angular 17.0.1

**Comment by JeanMeche** [comment]
@draylegend This should work fine. Please open another issue if you're able to provide a repro (on stackblitz.com for example).

**Comment by heloproc** [comment]
You are using the `OnPush` change detection strategy, which means that
the component
will only be re-rendered when its inputs or outputs change. In your case, the
`count` variable is not an input or output of the component, so it will not be
re-rendered when you click the button.
To fix this, you can either change the change detection strategy to `Default`
or you can make `count` an input or output of the component.
To change the change detection strategy, you can update the `changeDetection`
property of the ***@***.***` decorator:
```
@Component({
changeDetection: ChangeDetectionStrategy.Default,
...
})
class AppComponent {
...
}
```
To make `count` an input or output of the component, you can add the ***@***.***`
or ***@***.***` decorator to the variable:
```
@Component({
...
})
class AppComponent {
@Input() count = 0;
...
}
```
Once you have made this change, the counter should increase when you click the
button.

**Comment by AndrewKushnir** [comment]
Closing this ticket for now, please reopen once there is a repro, we'll perform further investigation. Thank you.
