### ISSUE TITLE
New documentation issue

### ISSUE THREAD

**Issue by OrestVanForest** [angular/angular#52719]
### Describe the problem that you experienced

https://angular.dev/guide/components/outputs

![image](https://github.com/angular/angular/assets/116964046/6b34cd54-ff6d-4def-9823-fad1b3207032)

Should be:

@Component({...})
export class CustomSlider {
  @**Output**('valueChanged') changed = new EventEmitter<number>();
}

**Comment by sasidharansd** [comment]
A PR has been already raised to fix this. FYI: https://github.com/angular/angular/pull/52673

**Comment by twerske** [comment]
closed as solved
