### ISSUE TITLE
Yarn install fails, Cannot find module './generate-tutorials.ts'

### ISSUE THREAD

**Issue by brampeirs** [angular/angular#52725]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

when running yarn install (v1.22.19) inside the adev folder I get an error from the post install script: `Cannot find module './generate-tutorials.ts'`

<img width="1170" alt="yarn install error" src="https://github.com/angular/angular/assets/2495032/bbb5f560-efdf-4a3b-a43a-a9907998de4c">
<img width="1129" alt="no scripts folder" src="https://github.com/angular/angular/assets/2495032/90dc8742-ff47-4f7e-9563-899b69068c70">

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

yarn install does not throw an error

**Comment by JeanMeche** [comment]
Hi this is a known issue that is being worked on. The infra setup isn't ready for Angular.dev, the project can't be started right now. 
Stay tuned !

**Comment by twerske** [comment]
As @JeanMeche stated - please give us some time to open source the repo - it's not yet buildable from this repo.

You can track the README in the `adev` folder which will have instructions on building locally once it's possible!
