### ISSUE TITLE
Angular 17: doesn't works on https://stackblitz.com/

### ISSUE THREAD

**Issue by cesco69** [angular/angular#52722]
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

Yes

### Description

https://stackblitz.com/edit/stackblitz-starters-5k4msv
```
Error in src/main.ts
The entrypoint for 'zone.js' could not successfully be resolved. The file '/turbo_modules/zone.js@0.14.2/dist/zone' does not exist. Please log an issue with the package author or check for an updated version of the package.
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-5k4msv

### Please provide the exception or error you saw

```true
Error in src/main.ts
The entrypoint for 'zone.js' could not successfully be resolved. The file '/turbo_modules/zone.js@0.14.2/dist/zone' does not exist. Please log an issue with the package author or check for an updated version of the package.
```
```


### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 17.0.1
```

**Comment by JoostK** [comment]
Where does this StackBlitz template come from? [zone.js 0.14 has a documented breaking change](https://github.com/angular/angular/blob/main/packages/zone.js/CHANGELOG.md#breaking-changes) for the `dist` folder no longer being exposed.

**Comment by cesco69** [comment]
I have started from Angular 16 template and updated them.

**Comment by JoostK** [comment]
Then this is a matter of adapting for the breaking change in zone.js 0.14. Updating the zone.js import resolves the problem.

**Comment by JeanMeche** [comment]
We're currently working with the Stackblitz team to update the default template to v17. Until then, please do the change mentionned by Joost !
