### ISSUE TITLE
docs: Add missing "developer preview" indicator on API reference

### ISSUE THREAD

**Issue by mvdluit** [angular/angular#52734]
### Describe the problem that you experienced

I found a similar issue to #52603 for API references currently in developer preview. They are labeled as developer preview on angular.io, but there's no mention of developer preview on angular.dev. 

example: `toObservable` in the `core/rxjs-interop` package. https://angular.io/api/core/rxjs-interop/toObservable vs https://angular.dev/api/core/rxjs-interop/toObservable

### Describe what you want to experience that would fix the problem

Display a label indicating the API reference is in developer preview.

**Comment by neilsoult** [comment]
+1 from me on this issue

**Comment by twerske** [comment]
This is a good idea. The infrastructure is likely the same as deprecated and we can take a look at including this. Since this will include some changes in the API extractor, we'll need a few weeks while we get everything up and running here before this is possible to take on!

If you're interested, this is definitely within the scope of a more medium-sized community contribution (once the docs are open sourced)!

**Comment by mvdluit** [comment]
@twerske I will keep an eye on the API extractor progress. 

Does it make sense to also add a property `isDeveloperPreview: boolean`  to manifest.json? That way developer previews can also be shown on the overview page. Ideally I would also like to see a `path` property in manifest.json (like in api-list.json for .io), but that might be a big ask since it's not needed for angular.dev 😬

**Comment by twerske** [comment]
The manifest is extracted and created automatically from the API generate process, so this would need to be added to the extractor to show up in the manifest to then be styled and shown on the overview and details pages.

**Comment by mvdluit** [comment]
> The manifest is extracted and created automatically from the API generate process, so this would need to be added to the extractor to show up in the manifest to then be styled and shown on the overview and details pages.

@twerske @JeanMeche This issue no longer appears to be blocked since ADEV is buildable, but a developer preview field still needs to be added to the manifest in order to create a PR for this issue. Is adding a developer preview field to the API manifest something that is already tracked internally, or should I create a separate issue for it?

**Comment by JeanMeche** [comment]
Both this issue and #52603 require changes in the `dev-infra` repo as the `docs-viewer` component lives there.

**Comment by mvdluit** [comment]
I'll close this issue as it's completed in https://github.com/angular/dev-infra/pull/1794. Thanks for picking this up @JeanMeche!
