### ISSUE TITLE
Property 'json' does not exist on type '{}'

### ISSUE THREAD

**Issue by arozwalak** [angular/angular#5273]
after update to alpha.46 I get error on http request 'Property 'json' does not exist on type '{}'
my code looks like this:

```
this.http.get('path/to/json/file') 
.map(res => res.json())
.subscribe(
    data => doSomething(data)
)
```

**Comment by todoubaba** [comment]
```typescript
this.http.get('path/to/json/file') 
.map((res: Response) => res.json())
.subscribe(
    data => doSomething(data)
)
```

**Comment by DawidMyslak** [comment]
import {Http, Response} from 'angular2/http';

.map((res: Response) => res.json());

**Comment by PascalPrecht** [comment]
As @todoubaba and @DawidMyslak pointed out, you have to add a type annotation.

Can this be closed then?

**Comment by arozwalak** [comment]
yes, it's working now
