### ISSUE TITLE
Featured block does not respect 'Show deprecated' setting

### ISSUE THREAD

**Issue by Gortyser** [angular/angular#52749]
### Describe the problem that you experienced

In [API reference page](https://angular.dev/api) I'm able to see an item marked as deprecated even if 'Show deprecated' toggle is disabled.
It can be intended, but it's still a weird behavior for a couple of reasons:
1. Looks confusing as 'Featured' is the first block I see after filters. And deprecated items should be filtered out, but they're here.
2. Why do we ever need deprecated items in the featured block? They're deprecated & not cool.
3. What is the point of the Featured block at all? Are they just commonly used things?

And another confusing thing not directly related to deprecated items:
featured items are marked with star icon in the list. And that icon has `cursor:pointer` so it looks like it's not just an icon but some interactive element. Favorite button or something.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/30402802/4dc867b6-a3f9-42cf-8322-07b8ca339283)

**Comment by twerske** [comment]
This will be addressed by https://github.com/angular/angular/issues/52705! Closing as duplicate.
