### ISSUE TITLE
ng new does not generate  app.module.ts in the src root folder Angular CLI 17.0.0

### ISSUE THREAD

**Issue by anukiransolur** [angular/angular#52751]
### Command

new

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v16.0.5

### Description

I ran the command "ng new my-blog --routing --style=scss" to create a new angular project using Angular CLI version 17.0.0 and could not find the app.module.ts file automatically generated by the CLI. 

In the documentation "https://angular.io/guide/file-structure" it says 

app/app.module.ts | Defines the root module, named AppModule, that tells Angular how to assemble the application. Initially declares only the AppComponent. As you add more components to the app, they must be declared here. This file is not generated when using --no-standalone option.

I did not use the --no-standalone option so I was expecting this file to be generated by Angular CLI v17.0.0. Is this something new to be added by developer going forward.

### Minimal Reproduction

```
ng new my-blog --routing --style=scss
? Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? No
CREATE my-blog/README.md (1060 bytes)
CREATE my-blog/.editorconfig (274 bytes)
CREATE my-blog/.gitignore (548 bytes)
CREATE my-blog/angular.json (2771 bytes)
CREATE my-blog/package.json (1038 bytes)
CREATE my-blog/tsconfig.json (909 bytes)
CREATE my-blog/tsconfig.app.json (263 bytes)
CREATE my-blog/tsconfig.spec.json (273 bytes)
CREATE my-blog/.vscode/extensions.json (130 bytes)
CREATE my-blog/.vscode/launch.json (470 bytes)
CREATE my-blog/.vscode/tasks.json (938 bytes)
CREATE my-blog/src/main.ts (250 bytes)
CREATE my-blog/src/favicon.ico (15086 bytes)
CREATE my-blog/src/index.html (292 bytes)
CREATE my-blog/src/styles.scss (80 bytes)
CREATE my-blog/src/app/app.component.scss (0 bytes)
CREATE my-blog/src/app/app.component.html (20887 bytes)
CREATE my-blog/src/app/app.component.spec.ts (919 bytes)
CREATE my-blog/src/app/app.component.ts (369 bytes)
CREATE my-blog/src/app/app.config.ts (227 bytes)
CREATE my-blog/src/app/app.routes.ts (77 bytes)
CREATE my-blog/src/assets/.gitkeep (0 bytes)
✔ Packages installed successfully.
```

### Your Environment

```text
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.0
Node: 20.9.0
Package Manager: npm 10.1.0
OS: darwin x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1700.0 (cli-only)
@angular-devkit/core         17.0.0 (cli-only)
@angular-devkit/schematics   17.0.0 (cli-only)
@schematics/angular          17.0.0 (cli-only)
```

**Comment by millerraycell** [comment]
I would like to work on this issue

**Comment by JeanMeche** [comment]
@millerraycell feel free to open a PR !

**Comment by lucasluizss** [comment]
@JeanMeche  made the change on #52761

**Comment by anukiransolur** [comment]
Thanks for the info. I will use --no--standalone to generate the app module.

**Comment by lati57** [comment]
Bonjour, Je suis en formation développeur Web et j'entame la partie Angular.Lorsque j'installe Angular cli il me met la version 17.0.0
Cette version differe de ce qui m'est présenté dans mes cours. Je n'a pas les fichiers app.module.ts et app.modules.routing.ts.
Je retrouve app.config.ts et app.module.ts, comment dois-je aborder ces fichiers, dois-je les considérer correspondant à app.module.ts et app.module.routing.ts
J'ai essayé d'adapter mon code à cette situation. 
Mais je suis bloqué par une erreur NULLINJECTORERROR. No provider HttpClient. Alors que j'ai bien import HttpClientModule et placé HttpClientModule dans provider de config.ts
Pourriez-vous m'éclairer quant à la façon de procéder. Merci par avance

**Comment by lati57** [comment]
Hello, I am in web developer training and I am starting the Angular part. When I install Angular cli it gives me version 17.0.0
This version differs from what is presented to me in my classes. I don't have the app.module.ts and app.modules.routing.ts files.
I find app.config.ts and app.module.ts, how should I approach these files, should I consider them corresponding to app.module.ts and app.module.routing.ts
I tried to adapt my code to this situation.
But I'm stuck with a NULLINJECTORERROR error. No HttpClient provider. While I imported HttpClientModule and placed HttpClientModule in the config.ts provider
Could you enlighten me on how to proceed? Thanks

**Comment by mvdluit** [comment]
@lati57 You can use the following command to generate a project that has `app.module.ts` and `app-routing.module.ts`:

`ng new my-app --no-standalone --routing --ssr=false`

**Comment by lati57** [comment]
ok thank you but should I use app.config.ts and app routes.ts

**Comment by mvdluit** [comment]
> ok thank you but should I use app.config.ts and app routes.ts

@lati57 If you run the command I mentioned, you will not have a `app.config.ts` in your project. `app.config.ts` only exists in an application without modules. Since you were taught to use modules, it's probably best to stick with those for your assignment. So in this case you will have to define your routes in `app-routing.module.ts`.

If you have more questions, I'd suggest you join the [Angular Community Discord](https://discord.gg/angular), as an issue is not really a good place to answer questions.

**Comment by lati57** [comment]
thank you very much

**Comment by Vaishnavi-ambati** [comment]
how can I use app.module.ts file if the project is already created?

**Comment by ProgammingGuy** [comment]
new to angular too. so, if you've created a project that doesn't have the app.moduel.ts and it''s whatever accompanying files from a barebone project from created from the CLI, can you add those files into the exisiting project with the app.routes.ts and the app.config.ts?

**Comment by mvdluit** [comment]
@ProgammingGuy Please read the comment above yours, it answers your question. Alternatively, give standalone a try as it's the modern way of writing Angular apps: [https://angular.dev/tutorials](https://angular.dev/tutorials)

@twerske Is there a way to lock this issue for new comments? The question about missing `app.module.ts` has been asnwered in this issue, and the [Angular Discord](https://discord.gg/angular) is a better place to provide support for questions related to personal projects.
