### ISSUE TITLE
Missing Link to Upgrade Instructions for Angular v17 in Documentation

### ISSUE THREAD

**Issue by hittten** [angular/angular#52750]
### Describe the problem that you experienced

I've noticed that the official Angular v17 documentation is currently missing the link to the new upgrade instructions. Users looking to update their applications to the latest version could face difficulties without these guidelines.

https://angular.io/guide/update-to-version-16

### Enter the URL of the topic with the problem

https://angular.io/guide/update-to-version-16

### Describe what you were looking for in the documentation

Navigate to the Angular v17 official documentation page.
Look for the section on upgrading to Angular v17.
Observe that there is a mention of upgrade instructions for old link https://angular.io/guide/update-to-version-16

I was looking for https://angular.io/guide/update-to-version-17 and see the same page, but with version 17.

**Comment by nivaaa** [comment]
@hittten you can use have a look on this link -
[https://update.angular.io/?l=3&v=16.0-17.0](url)
Hope this link will help you.

**Comment by JeanMeche** [comment]
Per above see : https://update.angular.io/?l=3&v=16.0-17.0
