### ISSUE TITLE
Add missing Angular Resources page on new Angular.dev

### ISSUE THREAD

**Issue by dustineichler** [angular/angular#52768]
### Describe the problem that you experienced

The Angular Resources page is missing from the latest version of Angular.dev.

### Enter the URL of the topic with the problem

https://angular.dev/resources

### Describe what you were looking for in the documentation

For links to the most popular libraries

### Describe what you want to experience that would fix the problem

I want to see a list of links to the most popular libraries

**Comment by Ansh101112** [comment]
will submit PR asap.

**Comment by twerske** [comment]
We have intentionally removed the resources page and pointed to Google's https://devlibrary.withgoogle.com/products/angular?sort=added instead as it is more easily kept up to date.
