### ISSUE TITLE
Angular.dev link to source code 

### ISSUE THREAD

**Issue by GuillaumeNury** [angular/angular#52764]
### Description

One of my favourite features of angular.io/API is the ability to quickly go from symbol documentation to its implementation in angular source code.

I cannot find a similar link in angular.dev.

### Proposed solution

Brink back the "go to source code" link 🙏

### Alternatives considered

I can use angular.io or GitHub search.

**Comment by JeanMeche** [comment]
Hi Guillaume, I'll close this in favor of #52663. This is something that we have on our post-MVP todo list =)

**Comment by GuillaumeNury** [comment]
Thank you Matthieu!
