### ISSUE TITLE
docs-infra: fix IDE error panel visibility

### ISSUE THREAD

**Issue by Alan-TheGentleman** [angular/angular#52760]
### Describe the problem that you experienced

I've encountered a usability issue in the IDE, specifically when handling errors in the code at certain screen zoom levels. The trouble arises when an error panel overlaps with the text input, hindering the visibility and editing of the code.

This overlap creates a cumbersome user experience and makes it challenging to identify and correct errors. To improve the usability, I'd like to suggest two potential solutions:

Display the error directly under the mouse, similar to how TypeScript errors are handled. This would avoid any overlap with the code and enable the user to see the error without obstructing the code view.

Alternatively, the error panel could be placed on the side of the IDE. This would keep the coding area clear and allow for easier access to error details.

Please look into this issue to enhance the error handling experience and the overall useability of the IDE.

Thank you.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/

### Add a screenshot if that helps illustrate the problem

*ISSUE*

![image](https://github.com/angular/angular/assets/6935240/b8ad1dfd-c796-4245-98f2-b43d19babc12)

*RECOMMENDATION 1 - Under the mouse* 

![image](https://github.com/angular/angular/assets/6935240/e2d74429-2f3b-4331-8c59-25e2ad3253ad)

*RECOMMENDATION 2 - To the side*

![image](https://github.com/angular/angular/assets/6935240/4b587bcd-0ab7-4928-819e-f9983cb7b7f1)

**Comment by twerske** [comment]
I believe we set a max height on the error panel - your window for code looks quite small, what is the device you're using?

**Comment by AppleLAN** [comment]
> Thanks for the feedback!
> 
> I believe we set a max height on the error panel - your window for code looks quite small, what is the device you're using?

Hi ! 
I was streaming the tutorial over Twitch using a 1080 resolution with 150% zoom level as people wouldn’t see it clear enough otherwise. Also tried with 125% but the result was the same. 
Apart from that I found that the panel opens really quick not giving enough time to fix the code, getting on top of it and if you have multiple errors they start stacking resulting in worse visibility.

**Comment by twerske** [comment]
We've experimented with inline errors instead of an error box. I guess I'm wondering since we have a max-width on the container this is:

![Screenshot 2023-11-09 at 3 32 26 PM](https://github.com/angular/angular/assets/15061394/63563365-445a-4d7d-bb87-8ee65aab6c33)

**Comment by AppleLAN** [comment]
> We've experimented with inline errors instead of an error box. I guess I'm wondering since we have a max-width on the container this is:
> 
> ![Screenshot 2023-11-09 at 3 32 26 PM](https://user-images.githubusercontent.com/15061394/281910414-63563365-445a-4d7d-bb87-8ee65aab6c33.png)

Tomorrow I’ll provide some images so you guys can see how it looks. Just in case this is the stream if you want to see what i mean live : 

Minute: 1:30:51 

https://www.twitch.tv/?tt_medium=mobile_web_share&tt_content=vod

**Comment by AppleLAN** [comment]
Hi ! 

Here's a screenshot of how it looks during my stream, I really think this could be a really specific use case but it can also be something that gets in the middle of delivering quality and good publicity through these kind of media.

<img width="2425" alt="image" src="https://github.com/angular/angular/assets/6935240/6db0f3ea-72c3-4720-8eb0-e6c98f24e997">

**Comment by AppleLAN** [comment]
Hi ! 

Here's a screenshot of how it looks during my stream, I really think this could be a really specific use case but it can also be something that gets in the middle of delivering quality and good publicity through these kind of media and events.

**Comment by AppleLAN** [comment]
Hi ! 

Here's a screenshot of how it looks during my stream, I really think this could be a really specific use case but it can also be something that gets in the middle of delivering quality and good publicity through these kind of media and events.

<img width="2424" alt="image" src="https://github.com/angular/angular/assets/6935240/dab40008-6731-4e5a-9ecd-f5440852ba9a">

**Comment by twerske** [comment]
> Hi !
> 
> Here's a screenshot of how it looks during my stream, I really think this could be a really specific use case but it can also be something that gets in the middle of delivering quality and good publicity through these kind of media and events.
> 
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/6935240/282049743-6db0f3ea-72c3-4720-8eb0-e6c98f24e997.png">

Yeah, I think the solution is setting a max height as a percentage instead - marking this for contributors to help with!

**Comment by vladboisa** [comment]
I hope my [PR fix ](https://github.com/angular/angular/pull/54128)will help to this issue

**Comment by vladboisa** [comment]
> > Hi !
> > Here's a screenshot of how it looks during my stream, I really think this could be a really specific use case but it can also be something that gets in the middle of delivering quality and good publicity through these kind of media and events.
> > <img alt="image" width="2000" src="https://user-images.githubusercontent.com/6935240/282049743-6db0f3ea-72c3-4720-8eb0-e6c98f24e997.png">
> 
> Yeah, I think the solution is setting a max height as a percentage instead - marking this for contributors to help with!

I hope my [PR fix ](https://github.com/angular/angular/pull/54128)will help to this issue
