### ISSUE TITLE
Page Not Found for CLI COmmands

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/angular#52779]
### Describe the problem that you experienced

From the left menu I clicked Angular CLI > Command Reference 

https://angular.dev/cli/commands

And it says page Not found

### Enter the URL of the topic with the problem

https://angular.dev/cli/commands

### Describe what you were looking for in the documentation

CLI command line options

### Describe the actions that led you to experience the problem

From the left menu I clicked Angular CLI > Command Reference 

### Describe what you want to experience that would fix the problem

Page to show CLI command line options

### Add a screenshot if that helps illustrate the problem

![Screenshot 2023-11-10 at 6 55 30 AM](https://github.com/angular/angular/assets/1870060/9ecb5815-da3a-4991-bb87-4be513ba0ddf)

### If this problem caused an exception or error, please paste it here

```true
Page Not Found 🙃
```

**Comment by JeanMeche** [comment]
Hi, thank you for raising that issue. It has already been fixed by #52589.

Since the infra isn't ready for angular.dev, the changes aren't reflected on the site yet. We expect it to be ready in the upcoming couple of weeks.
