### ISSUE TITLE
Update README.md links to the new documentation

### ISSUE THREAD

**Issue by sdedieu** [angular/angular#52771]
### Describe the problem that you experienced

The current README.md has several links that redirect on https://angular.io/. 
To ensure the adoption of the new documentation, I believe it can be better that most of the links redirect on https://angular.dev/ instead.

### Enter the URL of the topic with the problem

https://github.com/angular/angular

### Describe what you were looking for in the documentation

In the following screenshots, every links underlined in red redirect to the "old" documentation (https://angular.io/) instead of the new (https://angular.dev/)

### Add a screenshot if that helps illustrate the problem

<img width="958" alt="Screenshot 2023-11-10 at 07 55 01" src="https://github.com/angular/angular/assets/57216011/7243fc93-617c-4dc2-91ab-a42f0d098c15">
<img width="1007" alt="Screenshot 2023-11-10 at 07 55 11" src="https://github.com/angular/angular/assets/57216011/944927f9-d95b-42e5-8bf7-134be4c2da1a">
<img width="961" alt="Screenshot 2023-11-10 at 07 55 22" src="https://github.com/angular/angular/assets/57216011/aea9552a-1cdb-4d59-b379-36052d1dcb29">

**Comment by sdedieu** [comment]
FYI: I'm on it 😃

**Comment by twerske** [comment]
This PR was merged into the repository by commit https://github.com/angular/angular/commit/f51ce68bf5a27da7b18f49f9292722ff1374a9b3.
