### ISSUE TITLE
Angular 17 new control flow code formatting  issue with prettier.

### ISSUE THREAD

**Issue by sachinkannaujiya98** [angular/angular#52770]
### Description

Angular 17 new control flow code formatting  issue with prettier.
```html
      @if(STATUS.SPEAKING === status && content){ @for(word of content.split('
      '); track word; let i = $index){
      <div class="word" [class.highlight]="i === index">
        {{ word }}
      </div>
      } }
```
As you can see ```content.split(' ')``` after formatting got issue because it get to next line.

### Proposed solution

i think need a plugin for prettier to fix it.

### Alternatives considered

or any other solution for proper formatting

**Comment by JeanMeche** [comment]
This issue is tracked by prettier directly prettier/prettier#14991.
