### ISSUE TITLE
Typo in angular.dev site 'Create a custom pipe section'

### ISSUE THREAD

**Issue by sametcelikbicak** [angular/angular#52778]
### Describe the problem that you experienced

Angular dev web site Create a custom pipe section has a typo for pipe standalone keyword. It should be `standalone` but in the example definition is _**standaone**_
```typescript
import {Pipe, PipeTransform} from '@angular/core';
@Pipe({
  standaone: true,
  name: 'star',
})
export class StarPipe implements PipeTransform {
  transform(value: string): string {
    return `⭐️ ${value} ⭐️`;
  }
}
```
Also some problem in **Create the `ReversePipe`** section both standalone and ReversePipe highlight typo with missing `
```typescript
@Pipe({
    standaone: true,
    name: 'reverse'
})
```

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/create-a-pipe

**Comment by JeanMeche** [comment]
Hi, thank you for raising that issue. It has already been fixed by #52602. 

Since the infra isn't ready for angular.dev, the changes aren't reflected on the site yet. We expect it to be ready in the upcoming couple of weeks.
