### ISSUE TITLE
Control Flow Migration Bug in Nx Workspace

### ISSUE THREAD

**Issue by Coly010** [angular/angular#52787]
### Command

generate

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Control Flow Migration Fails despite a valid path being provided in an Nx Workspace.

It fails with the following error:

```
SchematicsException [Error]: Could not find any files to migrate under the path /<snip>/ng-control-flow-mig-repro/libs/mylib. Cannot run the control flow migration.

```

The schematic finds an incorrect tsconfig file for the path provided.

Expected:
1. Allow a path to a tsconfig to be provided --tsconfigPath
2. Find the closest tsconfig file to the path

### Minimal Reproduction

Clone Repo: https://github.com/Coly010/ng-control-flow-mig-repro

Run `nx generate @angular/core:control-flow-migration --path=libs/mylib`

### Exception or Error

```text
SchematicsException [Error]: Could not find any files to migrate under the path /<snip>/ng-control-flow-mig-repro/libs/mylib. Cannot run the control flow migration.

```
```


### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.0.0
Node: 18.14.0
Package Manager: npm 9.4.2
OS: darwin x64

Angular: 17.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0
@angular-devkit/build-angular   17.0.0
@angular-devkit/core            17.0.0
@angular-devkit/schematics      17.0.0
@angular/cli                    17.0.0
@angular/ssr                    17.0.0
@schematics/angular             17.0.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

```
 >  NX   Report complete - copy this into the issue template

   Node   : 18.14.0
   OS     : darwin-x64
   npm    : 9.4.2

   nx (global)        : 16.0.0-beta.6
   nx                 : 17.1.1
   @nx/js             : 17.1.1
   @nx/jest           : 17.1.1
   @nx/linter         : 17.1.1
   @nx/eslint         : 17.1.1
   @nx/workspace      : 17.1.1
   @nx/angular        : 17.1.1
   @nx/cypress        : 17.1.1
   @nx/devkit         : 17.1.1
   @nx/eslint-plugin  : 17.1.1
   @nrwl/tao          : 17.1.1
   @nx/web            : 17.1.1
   @nx/webpack        : 17.1.1
   typescript         : 5.2.2
```
```


### Anything else relevant?

_No response_

**Comment by jessicajaniuk** [comment]
You can alternatively use --path and pass in a specific file path / sub directory

**Comment by g-cheishvili** [comment]
> You can alternatively use `--path` and pass in a specific file path / sub directory

That part does not work

**Comment by jessicajaniuk** [comment]
@g-cheishvili Could you elaborate a bit more as to what's not working with `--path`?

**Comment by g-cheishvili** [comment]
> @g-cheishvili Could you elaborate a bit more as to what's not working with `--path`?

During the iterations, it takes the set, outside of the given path and naturally it can not find anything which would fall under given path and throws an error. Take @Coly010 example and debug it

**Comment by Coly010** [comment]
@jessicajaniuk my reproduction says to use `—path`. It’s precisely this usage that has the issue.

I’ve provided a reproduction repo with the steps provided and identified that the tsconfig file being used by the schematic is incorrect.

**Comment by jessicajaniuk** [comment]
I was just able to successfully run it with `./` as the path, essentially just the default value. It updated the file at `/libs/mylib/src/lib/mylib/mylib.component.html`. I'm going to test further though. It may have nothing to do with it being an nx workspace.

**Comment by jessicajaniuk** [comment]
I found the issue. It wasn't an issue with nx workspaces, but a bug in how we were handling the passed in paths.

**Comment by g-cheishvili** [comment]
> I found the issue. It wasn't an issue with nx workspaces, but a bug in how we were handling the passed in paths.

AWESOME, fixing that will help a lot of the developers adopt functionality gradually and not all at once, which in our case proved to be destructive

**Comment by markusfalk** [comment]
Same with `npx nx g @angular/core:standalone`

**Comment by jessicajaniuk** [comment]
@markusfalk Can you file a new issue for that? That would be really helpful for the team.
