### ISSUE TITLE
docs: typo in tutorials -> enabling routing

### ISSUE THREAD

**Issue by azeek21** [angular/angular#52797]
### Describe the problem that you experienced

In section 2, point 3: `providerRouter` should be `provideRouter`

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/enable-routing

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/91887882/af01d547-427a-4fd6-a7a1-14a62105b0eb)

**Comment by Mohamed-Morad-11** [comment]
I'll take it

**Comment by twerske** [comment]
This PR was merged into the repository by commit https://github.com/angular/angular/commit/15a825c113701583773fa028259518b63760c3b4.
