### ISSUE TITLE
angular.dev incorrect link to versions page in CLI local set-up

### ISSUE THREAD

**Issue by MBDesu** [angular/angular#52809]
### Describe the problem that you experienced

https://angular.dev/tools/cli/setup-local links to https://angular.dev/versions rather than the presumably intended https://angular.dev/reference/versions

### Enter the URL of the topic with the problem

https://angular.dev/tools/cli/setup-local

### Describe what you were looking for in the documentation

A version matrix describing the compatible versions of Node.js and npm with Angular 17.

### Describe the actions that led you to experience the problem

Checking angular.dev for compatible Node.js and npm versions with Angular 17 after failing to find them listed anywhere on the Internet.

### Describe what you want to experience that would fix the problem

I would like the link on the local set-up page to go to the correct versions page

### Add a screenshot if that helps illustrate the problem

https://user-images.githubusercontent.com/39097222/282232032-11bade3d-1961-4d44-85ae-4e73f41089c2.png

**Comment by sasidharansd** [comment]
Hey @MBDesu , think its available under reference side menu. 
You can access that through : https://angular.dev/reference/versions

**Comment by MBDesu** [comment]
> Hey @MBDesu , think its available under reference side menu. You can access that through : https://angular.dev/reference/versions

Ah, then the real issue is that the link found on [this page](https://angular.dev/tools/cli/setup-local) (screenshot below) goes to the wrong URL (the one in the issue).
![image](https://github.com/angular/angular/assets/39097222/11bade3d-1961-4d44-85ae-4e73f41089c2)

**Comment by ArneCaluwe** [comment]
Good morning @JeanMeche, is it possible that this issue has already been solved in this pull request: #52585 ?

**Comment by MBDesu** [comment]
Ah, this is indeed a duplicate of #52562 and was fixed in #52585, but was not merged.

**Comment by JeanMeche** [comment]
Yes I has been fixed but not deployed yet. Thx for the help !

**Comment by MBDesu** [comment]
> Yes I has been fixed but not deployed yet. Thx for the help !

Thank you! Apologies for the duplicate 😅

**Comment by JoostK** [comment]
#52585 was merged, but our merge tooling unfortunately doesn't result in Github reporting the PR as having been merged (the commits are rebased on top of `main`, not merged, and GH doesn't support closing a PR with a `merged` status unfortunately)

Thanks for the report in any case!
