### ISSUE TITLE
Angular Library - Importing default export from an Enum gets wrapped with "default" key.

### ISSUE THREAD

**Issue by Gnyblast** [angular/angular#52805]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I'm using "timezone-enum" library to get all the timezones that I can display in a select input. It was working ok in my project and I was using: `public timeZoneList: string[] = Object.values(Timezone);` to get all the enums into an array that I can iterate.
 I was importing the timezones with `import Timezone from 'timezone-enum';` and this was also working ok in my main app project.

Then I had to re-use this in my secondary project, so I decided to move this implementation to my own angular library that I consume locally by my other app projects.

import is same `import Timezone from 'timezone-enum';`
usage is same `public timeZoneList: string[] = Object.values(Timezone);`
I have these in my `tsconfig.json`:
```
compilerOptions{
   "esModuleInterop": true,
   "resolveJsonModule": true,
   "allowSyntheticDefaultImports": true,
}
```

but what ever I tried I'm still getting the `Timezone` like `{ default: {...}, _esModule: true}` and thus `Object.values(Timezone)` is an array of single object then if I want to get actual expected result, I should cast `Timezone` as `any` and then use`Object.values((Timezone as any).default)` to prevent compiler error and get the expected result. This doesn't look good and whatever I search and tried worked for my library. 

In angular application this behaviour does not exists when I add above compiler options but angular library I can't seem to overcome this which makes me think that this is a bug.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.7
Node: 16.20.0
Package Manager: npm 8.19.4 
OS: linux x64

Angular: 14.3.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.11
@angular-devkit/build-angular   14.2.11
@angular-devkit/core            14.2.11
@angular-devkit/schematics      14.0.7
@angular/cli                    14.0.7
@angular/fire                   7.5.0
@angular/material               14.2.7
@schematics/angular             14.0.7
ng-packagr                      14.2.2
rxjs                            6.6.7
typescript                      4.7.4
```

**Comment by alxhub** [comment]
This is a TypeScript question, not really an Angular question (Angular doesn't control default exports in many ways), so I'm going to close this ticket as it's not relevant for us. Just looking at the problem though, I would check whether you're using the same version of `timezone-enum` across both projects, and check the `.d.ts` files that it declares to see what the export structure is.
