### ISSUE TITLE
adev - API-reference : Featured section shows deprecated api-items with `show-deprecated` switch disabled

### ISSUE THREAD

**Issue by ArneCaluwe** [angular/angular#52813]
### Describe the problem that you experienced

When navigating to API-reference on the angular.dev documentation,  deprecated items were shown in the featured section.

This is confusing as in other sections of the api-reference, deprecated items were not shown.

### Enter the URL of the topic with the problem

https://angular.dev/api

### Describe what you were looking for in the documentation

Not applicable

### Describe the actions that led you to experience the problem

`CanActivate` was featured, and shown in featured section, even when show-deprecated was disabled

### Describe what you want to experience that would fix the problem

Deprecated api-items should only be shown in the featured section when `show-deprecated` is enabled

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/47561535/9219d006-d27b-4779-bedd-fabfa2aa6413)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
This problem does not seem to be browser specific. Observed on Chrome and Firefox latest version.
```

### Provide any additional information here in as much as detail as you can

```true
time of observation: Sat Nov 11 2023 11:06:33 GMT+0100 (Central European Standard Time) 
api-item in question: CanActivate
```

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this, we're already tracking this issue at #52705.
