### ISSUE TITLE
Regression TestBed.overrideComponent in Angular 17

### ISSUE THREAD

**Issue by satanTime** [angular/angular#52817]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

`TestBed.overrideComponent` doesn't override standalone components if the components have been used in other tests before. Might be related to https://github.com/angular/angular/issues/48432.

To reproduce, run the next test in any Angular 17 project.
It looks like there is a race, something isn't awaited properly.
The first test is skipped with `x`, remove `x` to reproduce the issue.
If you've got success, simply add `x` back and remove it again.
In this case, you can see that the 2nd test fails time to time because `overrideComponent` wasn't applied.

```ts
import { TestBed } from '@angular/core/testing';
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: '<router-outlet></router-outlet>',
  standalone: true,
  template: 'mock',
})
export class MockRouterOutlet {}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  template: '<router-outlet></router-outlet>',
})
export class AppComponent {
  title = 'a17';
}

describe('AppComponent with real router', () => {
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [AppComponent],
    }).compileComponents();
  });

  // REMOVE "x" TO REPRODUCE THE ISSUE
  xit('should create the app', () => {
    const fixture = TestBed.createComponent(AppComponent);
    expect(fixture.nativeElement.innerHTML).toEqual('<router-outlet></router-outlet><!--container-->');
  });
});

describe('AppComponent with mock router', () => {
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [AppComponent],
    }).overrideComponent(AppComponent, {
      set: {
        imports: [MockRouterOutlet],
      }
    }).compileComponents();
  });

  it('should create the app', () => {
    const fixture = TestBed.createComponent(AppComponent);
    expect(fixture.nativeElement.innerHTML).toEqual('<router-outlet>mock</router-outlet>');
  });
});
```

### Please provide the exception or error you saw

```true
No errors, `TestBed.overrideComponent` doesn't simply do anything.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
ngular CLI: 17.0.0
Node: 20.9.0
Package Manager: npm 10.1.0
OS: darwin x64

Angular: 17.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0
@angular-devkit/build-angular   17.0.0
@angular-devkit/core            17.0.0
@angular-devkit/schematics      17.0.0
@angular/cli                    17.0.0
@schematics/angular             17.0.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by PieterjanDeClippel** [comment]
This is extremely blocking...

**Comment by ben-hamida** [comment]
This issue is blocking us from upgrading to Angular 17. The P2 label indicates that there is a workaround. What is it? Converting all our tests from shallow to deep component tests?

**Comment by BarlamEPS** [comment]
It really is a blocker, since ng-mock is not working with Angular 17.

**Comment by AndrewKushnir** [comment]
Thanks for reporting the issue. We were able to reproduce it and are working on a fix. We'll keep this thread updated once we have more info.

**Comment by AndrewKushnir** [comment]
FYI, I've created a PR with the fix: https://github.com/angular/angular/pull/52916. It will go through the regular pipeline (code review, tests, etc) and I'll post an update once the fix is released.

**Comment by satanTime** [comment]
I can confirm with my tests that the issue has been fixed. However, unfortunately, this doesn't fix #48432.

**Comment by AndrewKushnir** [comment]
> I can confirm with my tests that the issue has been fixed. However, unfortunately, this doesn't fix https://github.com/angular/angular/issues/48432.

@satanTime thanks for checking the behavior. The issue described in #48432 would require an additional investigation. There is PR #52918 in progress that might resolve it and if not - we will perform further investigation once PR #52918 lands.

**Comment by AndrewKushnir** [comment]
Quick update: Angular v17.0.3 was released, the release contains the fix to the issue reported in this ticket.

**Comment by satanTime** [comment]
Cool! Thanks a lot!
