### ISSUE TITLE
Page Not Found Error

### ISSUE THREAD

**Issue by ashleychootim** [angular/angular#52812]
### Describe the problem that you experienced

The link to the following url responds with Page Not Found:

https://angular.dev/guide/http/making-requets

Clicked : 
https://angular.dev/guide/http

### Enter the URL of the topic with the problem

https://angular.dev/guide/http/making-requets

### Describe the actions that led you to experience the problem

Clicked the 'Making Http Requests' button under What's next.

### Describe what you want to experience that would fix the problem

Discovered that there is a typo in the url. Please update the url to:

https://angular.dev/guide/http/making-requests

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/65932199/79bfad84-0c12-4ee6-83ba-e5a626bb9e9f)

**Comment by JeanMeche** [comment]
Hi thank you for reporting this issue, we're already tracking this at #52542.
