### ISSUE TITLE
docs: exclude deprecated API references from the featured section on API overview page

### ISSUE THREAD

**Issue by mvdluit** [angular/angular#52819]
### Describe the problem that you experienced

Deprecated API references can still show up in the featured section on [angular.dev/api](https://angular.dev/api). (see screenshot)

It makes little sense to me to feature deprecated references.

### Describe what you want to experience that would fix the problem

Exclude API references that are deprecated.

### Add a screenshot if that helps illustrate the problem

![featured_deprecated](https://github.com/angular/angular/assets/3525053/125067f3-5b26-4d6c-8513-e44d62a3d82f)

**Comment by JeanMeche** [comment]
Hi Michael, thanks for raising that issue. We're already tracking it at #52705, let continue the discussion over there !
