### ISSUE TITLE
Docs (angular.dev): Minor typo in Property Binding tutorial

### ISSUE THREAD

**Issue by VictorPerezAsuaje** [angular/angular#52825]
# Property Binding tutorial

The last sentence of this tutorial has a minor typo on the word "documentation".

Current:
If you'd like to learn more checkout the Angular **documention**.

Suggested Fix:
If you'd like to learn more checkout the Angular **documentation**.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/property-binding

**Comment by twerske** [comment]
Solved in a merged PR!
