### ISSUE TITLE
link not working.

### ISSUE THREAD

**Issue by milar7** [angular/angular#52828]
### Describe the problem that you experienced

hi.
in this section there is a link that navigate you to not found page.
https://angular.dev/guide/components/programmatic-rendering#using-ngcomponentoutlet
the link:
[NgComponentOutlet API reference](https://angular.dev/api/core/NgComponentOutlet)

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/programmatic-rendering#using-ngcomponentoutlet

### Describe what you were looking for in the documentation

fix the link

**Comment by twerske** [comment]
This PR was merged into the repository by commit https://github.com/angular/angular/commit/282a49c019ba7ac52c5923e7c0100f37d7e0d306.
