### ISSUE TITLE
docs: Typo on section Components#customizing-output-names

### ISSUE THREAD

**Issue by axeleguia** [angular/angular#52827]
### Describe the problem that you experienced

Minor typo on section [Components#customizing-output-names](https://angular.dev/guide/components/outputs#customizing-output-names)

```
@Component({...})
export class CustomSlider {
  @Input('valueChanged') changed = new EventEmitter<number>();
}
```

Wrong decorator

`@Input('valueChanged')` -> `@Output('valueChanged')`

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/outputs#customizing-output-names

**Comment by sasidharansd** [comment]
Hey @JeanMeche , think we can close this one, as there is PR merged to fix this https://github.com/angular/angular/pull/52673

**Comment by JoostK** [comment]
Thanks for the report! This has indeed already been addressed but awaiting deployment.
