### ISSUE TITLE
angular.dev sidenav is not responsive on mobile

### ISSUE THREAD

**Issue by rdechiara** [angular/angular#52823]
### Describe the problem that you experienced

The side menu is not displayed properly due to the text of the menu items being covered by the sidebar.This problem occurs on mobile, specifically using Firefox 119 for Android 13 as the browser.

### Enter the URL of the topic with the problem

https://angular.dev/overview

### Describe what you were looking for in the documentation

From angular.dev/overview I was checking the list of contents from the side menu.

### Describe the actions that led you to experience the problem

To reproduce this issue just follow these steps:

>  Visit angular.dev

> Click on "Docs" from the sidebar to visit angular.dev/overview

> Now expand the collapsed sidebar to reveal the list of contents

> You'll notice the left part of the list of contents is covered by the sidebar

### Describe what you want to experience that would fix the problem

Check if there are CSS rules which are not supported by Firefox 119 for Android. The issue is not reproducible with Chrome 118 for Android (on the same smartphone).

### Add a screenshot if that helps illustrate the problem

![Screenshot_2023-11-09-09-10-27-75_3aea4af51f236e4932235fdada7d1643](https://github.com/angular/angular/assets/79670539/08045558-6daf-4511-8948-9d5dafd6e173)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
OS: Android 13
Browser: Firefox for Android v119
Device: Realme 8 5G
```

**Comment by SahulKola** [comment]
Hey, @twerske assign it to me, I will work on it.

**Comment by TECHMONSTER21** [comment]
Seems like this issue is referenced elsewhere and apparently closed.
