### ISSUE TITLE
Error hot reload

### ISSUE THREAD

**Issue by jasbel** [angular/angular#52834]
### Which @angular/* package(s) are the source of the bug?

core, zone.js

### Is this a regression?

Yes

### Description

DOMException: Failed to execute 'querySelector' on 'Document': '5-root' is not a valid selector.
    at DefaultDomRenderer2.selectRootElement

### Please provide the exception or error you saw

```true
DOMException: Failed to execute 'querySelector' on 'Document': '5-root' is not a valid selector.
    at DefaultDomRenderer2.selectRootElement
```

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
