### ISSUE TITLE
Latest DevTools version 1.0.8 not working with projects running on Angular 16

### ISSUE THREAD

**Issue by 4javier** [angular/angular#52835]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

Just run DevTools on an Angular 16 project, and try to click on an element in the components tree.

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

I'd expect the tool to show selected component's properties as always, and instead it shows nothing and print an error in console, always the same no matter the component.
Tested on two different NG16 projects where previous version was working flawlessly.

### Please provide a screenshot if possible [Bug Report only]

![immagine](https://github.com/angular/angular/assets/459381/8ce42e46-3623-4e78-af23-4b5f3f29ef62)

### Please provide the exception or error you saw [Bug Report only]

```true
Uncaught TypeError: F().\u0275getInjectorMetadata is not a function
    rt component-tree.ts:61
    Jo component-tree.ts:436
    De component-tree.ts:234
    i component-tree.ts:105
    nn component-tree.ts:104
    bi client-event-subscribers.ts:102
    n same-page-message-bus.ts:41
    invokeTask zone.js:402
    runTask zone.js:173
    invokeTask zone.js:483
    invokeTask zone.js:1631
    globalCallback zone.js:1674
    globalZoneAwareCallback zone.js:1695
    customScheduleGlobal zone.js:1779
    scheduleTask zone.js:389
    scheduleTask zone.js:216
    scheduleEventTask zone.js:242
    makeAddListener zone.js:1934
    on same-page-message-bus.ts:44
    <anonymous> backend.ts:20
    <anonymous> backend.ts:44
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version. [Bug Report only]

```true
Replicated on latest Firefox and Chromium releases
```

**Comment by JoostK** [comment]
Thanks for the report, this has been addressed in #52791, pending a release.

**Comment by 4javier** [comment]
My bad.
I didn't check among closed tickets.

**Comment by matrix-compute** [comment]
> ### Is this a bug report or a feature request?
> * [x]  Bug Report
> * [ ]  Feature Request
> 
> ### Please provide the steps to reproduce the issue [Bug Report only]
> Just run DevTools on an Angular 16 project, and try to click on an element in the components tree.
> 
> ### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]
> I'd expect the tool to show selected component's properties as always, and instead it shows nothing and print an error in console, always the same no matter the component. Tested on two different NG16 projects where previous version was working flawlessly.
> 
> ### Please provide a screenshot if possible [Bug Report only]
> ![immagine](https://user-images.githubusercontent.com/459381/282298252-8ce42e46-3623-4e78-af23-4b5f3f29ef62.png)
> 
> ### Please provide the exception or error you saw [Bug Report only]
> ```
> Uncaught TypeError: F().\u0275getInjectorMetadata is not a function
>     rt component-tree.ts:61
>     Jo component-tree.ts:436
>     De component-tree.ts:234
>     i component-tree.ts:105
>     nn component-tree.ts:104
>     bi client-event-subscribers.ts:102
>     n same-page-message-bus.ts:41
>     invokeTask zone.js:402
>     runTask zone.js:173
>     invokeTask zone.js:483
>     invokeTask zone.js:1631
>     globalCallback zone.js:1674
>     globalZoneAwareCallback zone.js:1695
>     customScheduleGlobal zone.js:1779
>     scheduleTask zone.js:389
>     scheduleTask zone.js:216
>     scheduleEventTask zone.js:242
>     makeAddListener zone.js:1934
>     on same-page-message-bus.ts:44
>     <anonymous> backend.ts:20
>     <anonymous> backend.ts:44
> ```
> 
> ### Is this a browser-specific issue? If so, please specify the device, browser, and version. [Bug Report only]
> ```
> Replicated on latest Firefox and Chromium releases
> ```
> 
> ### Description [Feature Request only]
> _No response_
> 
> ### Proposed solution [Feature Request only]
> _No response_
> 
> ### Alternatives considered [Feature Request only]
> _No response_

**Comment by matrix-compute** [comment]
__
