### ISSUE TITLE
Observable Payload Reduction Plan

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#5283]
Two goals: 
 * Reduce bytes in the core of Angular
 * Get back to our original Observable goal of relying more on functions than prototypes when composing Observable operators. i.e. `map.call(source, input => mapped)` or `source::map(input => mapped)` if we can have proposed [JS function bind syntax](https://github.com/zenparsing/es-function-bind).

Tasks
 * Export an RxJS `Observable` and `Subject` that only include `map`, `filter`, `flatMap` operators.
 * In API docs and Guides, show examples of importing and using more advanced operators from RxJS.

Later on, we can consider more things we can do to let users patch or override the observable provided by Angular, but that doesn't need to happen pre-beta.

This should achieve about a 75% reduction in the size of the Rx dependency, which is about 30KB when minified and gzipped.

**Comment by jeffbcross** [comment]
The Rx.js output with just the things we'd need vs what we currently export:

| Optimization | Current dist | New lite dist | Change    |
|------------------|------------------|------------------|-----------------|
| None            | 407KB      | 51KB           |  -356KB (-87%) |
| Basic Uglify  | 315KB      | 37KB           | -278KB (-88%) |
| Uglify+Gzip | 36KB        | 6KB              | -30KB (-83%) |

My method was to use browserify against `@reactivex/rxjs/dist/cjs/Rx.js` to get numbers for our current distribution, and run browserify against this file I created to test the new distribution:
```js
require('@reactivex/rxjs/dist/cjs/Observable');
require('@reactivex/rxjs/dist/cjs/Subject');
require('@reactivex/rxjs/dist/cjs/operators/map');
require('@reactivex/rxjs/dist/cjs/operators/filter');
require('@reactivex/rxjs/dist/cjs/operators/reduce');
require('@reactivex/rxjs/dist/cjs/operators/mergeMap');
```

And in case you're wondering what the size is without any operators: 27KB, 18KB(min), and 4KB(gzip).

CC @IgorMinar

**Comment by nosachamos** [comment]
This is fantastic!

**Comment by robwormald** [comment]
implemented initial step in https://github.com/angular/angular/pull/5288

Delta with *no* operators:
`angular2.dev.js` - 1,480KB -> 1071KB  :  Δ -409KB ( -27% )
`angular2.min.js` - 793KB -> 588KB : Δ -205KB ( -25% )


I will follow up with separate PR's as I add operators to track changes to weight. Note that this is likely to cause some initial confusion as RxJS includes *all* of the interfaces on the Observable: https://github.com/ReactiveX/RxJS/blob/master/src/Observable.ts#L158-L243 and so this will expose autocompletion with operators that are not actually included. 

`map/reduce/filter/mergeMap` are too bare of an implementation, IMHO. We should consider basic parity with the Dart Stream API: https://api.dartlang.org/133672/dart-async/Stream-class.html#instance-methods, and also `.toPromise()`  needs to be included.

**Comment by robwormald** [comment]
I've added `.map()` and `.filter()` to the PR:
`angular2.dev.js` - 1,071KB -> 1077KB  :  Δ +6KB ( +.5% )
`angular2.min.js` - 588KB -> 592KB : Δ +4KB( +.6% )

**Comment by robwormald** [comment]
#### Comparison / Matching Operators with Dart API

Not all of these are 1-1, and I may have a couple of them mismatched. @vsavkin probably knows better than I do here. 

Ones marked (spec) are on the core Observable and therefore included by default.
Ones marked :star: are imho necessary for inclusion as they are either likely to be commonly used, difficult to compose, or generally lead to a poor user experience without.

#### Dart Stream => Rx Observable

#### Static Methods
- `Stream.empty()` => `Observable.empty()`
- `Stream.eventTransformed()` => `Observable.fromEvent()`
- `Stream.fromFuture()` => `Observable.fromPromise()` :star:
- `Stream.fromIterable()` => `Observable.from()`
- `Stream.periodic()` => `Observable.interval()` :star:

#### Instance Methods:
- `any()` => ???
- `asBroadcastStream()` => `multicast()` (i think?) :star: 
- `onCancel()` => ???
- `asyncExpand()` => `mergeMap()` 
- `asyncMap()` => `mergeMap()`:star:
- `contains()` => `any()`
- `distinct()` => `distinctUntilChanged()`
- `drain()` => no equivalent as far as I can tell.
- `elementAt()` => `elementAt()`
- `every()` => `every()`
- `expand()` => `mergeMap()` (Rx's expand is more like 'recurse')
- `firstWhere()` => `first()`
- `fold()` => `scan()` :star:
- `forEach()` => `forEach()` (spec)
- `handleError()` => `catch()` :star:
- `join()` => no exact equivalent
- `lastWhere()` => `last()`
- `listen()` => `subscribe()` (spec)
- `map()` => `map()` :star:
- `pipe()` => `subscribe()` (sort of, subscribe(observer) is similar)
- `reduce()` => `reduce()` :star:
- `singleWhere()` => `first()`
- `skip()` => `skip()`
- `skipWhile()` => `skipWhile()`
- `take()` => `take()`
- `takeWhile()` => `takeWhile()`
- `timeout()` => `timeout()`
- `toList()` => `toArray()`
- `toSet()` => none yet
- `transform()` => `bufferToggle()` is the closest i can tell
- `where()` => `filter()` :star:

-----
:star: operators not in Dart (use case)
- `debounceTime()` (forms)
- `retry()` / `retryWhen()` (http)
- `switchMap()` (http)
- 'toPromise()` (http)

With *all* of these operators in (not saying this is a good idea, just FYI)
`angular2.dev.js` - 1071KB ->  1197KB:  Δ +126KB ( +11% )
`angular2.min.js` - 588KB  -> 657KB: Δ +69KB ( +11% )

With just :star: operators
`angular2.dev.js` - 1071KB ->  1170KB:  Δ +99KB ( +9% )
`angular2.min.js` - 588KB  -> 642KB: Δ +54KB ( +9% )

**Comment by robwormald** [comment]
Ooo, as the hunt continues, I get 20KB (unminified) for free simply by turning off emitted helpers - see https://github.com/angular/angular/issues/5293

**Comment by PascalPrecht** [comment]
Don't eat the whole pizza!

**Comment by kylecordes** [comment]
I am is in favor as everyone else of keeping the Angular 2 core size small. But I have a concern in the other direction, perhaps worth a few minutes thought. It appears to me that Observables and manipulations thereof are going to end up pervasive in Angular 2 applications. Stripping too many of those features out to save some bytes, might delay or reduce the extent to which Angular 2 developers embrace this future. Strip with care.

**Comment by jeffbcross** [comment]
@kylecordes thanks for the note. We're working on determining the best short-term, mid-term, and long-term solutions, and have a good handle on what we can do to have the best of both worlds (small payload with composable, chainable operators). I'll add some notes on this issue.

**Comment by arlair** [comment]
Cycle.js is a UI framework based around RxJS. It moved from having Rx as internal:

    import {Rx} from '@cycle/core';

to a peer dependency:

    import Rx from 'rx';

I'm not sure what the reasoning was, but it makes more sense to me. You might be able to bug Andre Staltz for more info, he is part of the RxJS 5 team.

RxJS is trying to become more modular. I think it would be great if the user can choose to import a minimal or more full featured Rx to fit their needs.
