### ISSUE TITLE
Docs (angular.dev): Allow for version selection in the Angular Playground

### ISSUE THREAD

**Issue by pBouillon** [angular/angular#52833]
### Describe the problem that you experienced

When using the [Angular Playground editor](https://angular.dev/playground) I can chose between multiple templates, but not between multiple versions.

### Enter the URL of the topic with the problem

https://angular.dev/playground

### Describe what you were looking for in the documentation

I would like to be able to navigate between versions of Angular

### Describe what you want to experience that would fix the problem

Similarily to the dropdown to chose a template, I would have like to be able to chose between some versions of Angular (like only the majors, majors + minors, or else)

It could also be nice if I can see the version of the dependencies used by the current Angular version without having to download the sources.

**Comment by twerske** [comment]
The playground will work along with the version selector that will be added with v18 (once there are multiple versions of the site).

Angular.dev will support v17+ so once there's a future version, we'll also have a selector!

**Comment by pBouillon** [comment]
Awesome, can't wait for it! 🚀
