### ISSUE TITLE
Resumability as new SSR technique and others

### ISSUE THREAD

**Issue by Oidlichtnwoada** [angular/angular#52832]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

Hi,
I am developing with Angular for a year now and I would like to tell you my thoughts on how to make Angular the frontend king:
- before introducing Signals, more careful considerations should have been made on how to make the developer experience better by using signals (thinking E2E and how to remove non-reactive component code), e.g. signals as component inputs and events, such that you can use the same system to subscribe to changes to make the whole code more reactive in style - in the current framework version, subscribing to input changes cannot be done without much boilerplate code ... it is not enough to only use signals in the internal component logic, you should also think about how signals can flow also through inputs and output events (I know that for output events there is no default first state) ...
- Instead of investing manpower to make the hydration feature better by reusing more stuff computed by the server instead of recomputing everything on the client side, it would have been better to invest into resumability like the one introduced in Qwik (maybe the code can be ported with reasonable effort), this would be a major advantage against React and Vue
- The biggest advantages of Angular are its stability, its "batteries-included style" (except NGRX, please merge it to an angular repo), its testability and superior separation-of-concerns architecture

Thanks for providing us with such a great framework, I really want Angular to be the most-used framework 👍 

Fine-grained reactivity is there, let's get resumability ^^

### Proposed solution

- signals for component inputs and outputs (events)
- resumability instead of hydration

### Alternatives considered

- using another framework (not feasible since the Angular ecosystem is great)

**Comment by jnizet** [comment]
Something like this? https://github.com/angular/angular/discussions/49682

**Comment by Oidlichtnwoada** [comment]
Jep, ok thx for the pointer @jnizet ...
Is resumability also tracked with an RFC?

**Comment by pkozlowski-opensource** [comment]
@Oidlichtnwoada all the improvements that you've mentioned are items we are very well aware of and part of our roadmap already: https://angular.io/guide/roadmap 

Some of the discussed improvements are larger-scale efforts and not a good fit for tracking as issues. I'm going close this one here as this is work in progress / planned work and not something we want to track as an issue.
