### ISSUE TITLE
Router.navigateByUrl("url") not working inside onmessage event from child window in angular13.

### ISSUE THREAD

**Issue by osamasynergy** [angular/angular#52845]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Parent window listening for a message from a child window. but when a message is received I call the router.navigateByUrl("url") function to redirect the user to the dashboard but my parent window gets stuck and does not respond.

I want to redirect the user to the 'dashboard' after getting the message from the child window but when I call router.navigatebyurl('/dashboard') then my parent window gets stuck and is not responding.

This is the submit function calling on the login button.

`async onSubmit() {
    const logonUri = await this.authService.logon('0').toPromise();

    // Listening for the message
    window.addEventListener('message', (event) => {
      if (!event.data) {
        return;
      }

      let res = AccessTokenViewModel.fromJS({
        access_token: event.data.accessToken,
        expires_in: event.data.expiresIn,
        issued_at: event.data.issuedAt,
      });

      console.log("token response :: ", res);

      // use to process the token response object
      this.onSuccess(res);
    });

    const windowWidth = 500;
    const windowXpos = window.outerWidth / 2 - windowWidth / 2;
    const windowHeight = 700;
    const windowYpos = window.outerHeight / 2 - windowHeight / 2;

    const params = `width=${windowWidth},height=${windowHeight},top=${windowYpos},left=${windowXpos},toolbar=no,location=no,directories=no,status=no,menubar=no,resizable=no,copyhistory=no`;

    // opening new popup browser window
    this.loginWindow = window.open(logonUri, 'InternalLoginWindow', params);
  }`
  
This is onSuccess function which is processing token response.

`private onSuccess(response: AccessTokenViewModel) {
    this.loader.addState('Login');

    try {
      const helper = new JwtHelperService();
      const decodedToken = helper.decodeToken(response.access_token);
      const user = JSON.parse(decodedToken.UserInfo);
      if (user != null) {
        this.store.dispatch(new SetUserToken(response));
        this.store.dispatch(new SetUserInfo(user));
        const formValue = this.loginForm.value;
        if (formValue) {
          const department = this.departments?.find(
            (x) => x.departmentId === +formValue.department
          );
          this.store.dispatch(new SetSelectedDepartment(department));
        }

        // redirect user to the dashboard
        this.navigateToOtherComponent();
      }
    } catch {
      this.helperService.notify(
        Enums.notificationMessageHeader.error,
        'Brugerens e-mail eller adgangskode er forkert',
        Enums.messageType.Error,
        3000
      );
    } finally {
      this.loader.removeState('Login');
    }
  }
`

This below function is used to navigate the user but I'm getting 'Navigation failed or blocked'.

` navigateToOtherComponent() {
    this.router
      .navigateByUrl(this.returnUrl)
      .then((navigated: boolean) => {
        if (navigated) {
          console.log('Successfully navigated to /other-component');
        } else {
          console.log('Navigation failed or blocked');
        }
      })
      .catch((error) => console.error('Error during navigation:', error));
  }`

I've tried a lot of different options but still, I'm not able to redirect the user to other components in the parent window when I get the message from the child window. I don't know what the issue is here.

I also redirect the user with window.location.href but it is also not working. parent window not responding.

![not responding error](https://github.com/angular/angular/assets/145320395/d2468b0e-510b-4a8d-9289-21db4fab61a6)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.2
Node: 19.6.0 (Unsupported)
Package Manager: npm 9.4.0
OS: win32 x64

Angular: 13.1.1
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cdk                    13.1.3
@angular/cli                    13.1.2
@angular/material               13.1.3
@schematics/angular             13.1.2
rxjs                            6.6.7
typescript                      4.5.4
```

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
