### ISSUE TITLE
Standalone provider example should use AppConfig

### ISSUE THREAD

**Issue by sdedieu** [angular/angular#52846]
### Describe the problem that you experienced

Following #52766, if we agree on that change philosophy, I think we should modify every standalone provider examples in the doc that currently providing inside the `main.ts` file instead of the `app.config.ts`.

### Add a screenshot if that helps illustrate the problem

<img width="960" alt="Screenshot 2023-11-13 at 10 57 14" src="https://github.com/angular/angular/assets/57216011/1cd05e57-3df2-4a4d-a9bc-1eac65abd42c">
<img width="953" alt="Screenshot 2023-11-13 at 10 59 47" src="https://github.com/angular/angular/assets/57216011/3ffa92c6-b200-4f38-8eb6-703436fee9af">

**Comment by Jad31** [comment]
Hi, i'd like to take this issue!
