### ISSUE TITLE
Page not found 🙃

### ISSUE THREAD

**Issue by bielmc11** [angular/angular#52847]
### Describe the problem that you experienced

On the route; https://angular.dev/guide/defer#on-viewport, if you click on the link: _template reference variable_, (found in the "view port" seciton), you will be redirected to https://angular.dev/guide/glossary#template-reference-variable where you'll  encounter: PAGE NOT FOUND ERROR 🙃.

Perhaps the correct route is: https://angular.dev/guide/templates/reference-variables.

### Enter the URL of the topic with the problem

https://angular.dev/guide/defer#on-viewport

**Comment by sdedieu** [comment]
On it 😃

**Comment by sdedieu** [comment]
It appears that on the current documentation source code, the link has been removed (see: https://github.com/angular/angular/blob/main/adev/src/content/guide/defer.md)

**Comment by JeanMeche** [comment]
Yup it was fixed by #52743
