### ISSUE TITLE
Angular Roadmap in angular.dev

### ISSUE THREAD

**Issue by devOfJava** [angular/angular#52843]
### Describe the problem that you experienced

Hi.

There is a gramatical mistake in angular roadmap.

current:
As an open source project, Angular’s daily commits, PRs and momentum is all trackable GitHub. 

suggested fix:
As an open source project, Angular’s daily commits, PRs and momentum is all trackable on GitHub. 

### Enter the URL of the topic with the problem

https://angular.dev/roadmap

Add a screenshot if that helps illustrate the problem
![image](https://github.com/angular/angular/assets/119279908/aff3dc35-bcfa-4feb-bf70-10914298975f)

**Comment by twerske** [comment]
fixed in https://github.com/angular/angular/pull/52850
