### ISSUE TITLE
Angular.dev docs: Customizing output names section typo error

### ISSUE THREAD

**Issue by sleptsov** [angular/angular#52844]
### Describe the problem that you experienced

1. In the Customizing output names section, the example copy/paste panel specifies `@Input` decorator but should be `@Output`
2. In the Specify outputs in the `@Component` decorator section, the second copy/paste panel has a confusing comment (typo error). It should be `valueChanged` instead of `disabled`

### Enter the URL of the topic with the problem

1. https://angular.dev/guide/components/outputs#customizing-output-names
2. https://angular.dev/guide/components/outputs#specify-outputs-in-the-component-decorator

### Add a screenshot if that helps illustrate the problem

<img width="729" alt="Screenshot 2023-11-13 at 11 39 59" src="https://github.com/angular/angular/assets/8719719/92d58879-a5ba-434e-aa6a-6fdbf71c8dfc">
<img width="720" alt="Screenshot 2023-11-13 at 11 48 06" src="https://github.com/angular/angular/assets/8719719/cc1c0518-c872-4b94-ba20-797bf2b86037">

**Comment by JoostK** [comment]
Thanks for the report, this was addressed in #52673 but has not yet been deployed.
