### ISSUE TITLE
Docs (angular.dev): Typo in tutorials -> Component composition

### ISSUE THREAD

**Issue by ikefakis** [angular/angular#52857]
### Describe the problem that you experienced

In section 1, the second sentence says "Be sure to add `AppComponent ` to the imports array of AppComponent" instead of "Be sure to add `UserComponent` to the imports array of AppComponent"

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/composing-components

### Add a screenshot if that helps illustrate the problem

![Screenshot_1](https://github.com/angular/angular/assets/28840965/3204a260-6f15-4039-9d22-01368b76a699)

**Comment by sasidharansd** [comment]
Fixed with the PR: https://github.com/angular/angular/pull/52677

**Comment by JoostK** [comment]
Thanks for the report, closing per the above.
