### ISSUE TITLE
Angular 17:  Cannot find module '@angular/platform-browser/animations-async' or its corresponding type declarations.

### ISSUE THREAD

**Issue by cesco69** [angular/angular#52858]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

No

### Description

```ts
import 'zone.js';
import { Component } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import { provideAnimationsAsync } from '@angular/platform-browser/animations-async';

@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <h1>Hello from {{ name }}!</h1>
    <a target="_blank" href="https://angular.dev/overview">
      Learn more about Angular
    </a>
  `,
})
export class App {
  name = 'Angular';
}

bootstrapApplication(App, { providers: [provideAnimationsAsync()] });
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-am19g9

### Please provide the exception or error you saw

```true
Error in src/main.ts (4:40)
Cannot find module '@angular/platform-browser/animations-async' or its corresponding type declarations.
```

**Comment by JeanMeche** [comment]
There is a typo the package is `@angular/platform-browser/animations/async`

**Comment by cesco69** [comment]
@JeanMeche Yep, the typo come from "Introducing Angular v17" of @mgechev  https://blog.angular.io/introducing-angular-v17-4d7033312e4b

![image](https://github.com/angular/angular/assets/6096678/6c69ca71-608a-48f1-a228-54acf23b2ff6)
