### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by SagiHalevy** [angular/angular#52860]
### Describe the problem that you experienced

There is a typo:
"boostrapApplication" is written, instead of "bootstrapApplication"

### Enter the URL of the topic with the problem

https://angular.dev/guide/http/setup#providing-httpclient-through-dependency-injection

**Comment by JeanMeche** [comment]
We also have the same issue in `http/security.md`.

**Comment by Dhoni77** [comment]
Hi @JeanMeche I would like to work on this

**Comment by JeanMeche** [comment]
Feel free to drop a PR !

**Comment by TECHMONSTER21** [comment]
Why this is still not closed?

**Comment by JoostK** [comment]
It is now! Addressed in https://github.com/angular/angular/pull/52803, pending deployment.
