### ISSUE TITLE
feat(angular_1_router): Add class to active ng-link

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#5286]
Add a class to the ng-link when it is the current active route.

**Comment by vguede** [comment]
+1

**Comment by ericmartinezr** [comment]
Is this related to https://github.com/angular/angular/issues/4532?

**Comment by brandonroberts** [comment]
Naa. An active link class is already added in the Angular 2 version.

**Comment by brandonroberts** [comment]
@petebacondarwin is this coming to the ng1 router?

**Comment by petebacondarwin** [comment]
Let's do it!

**Comment by brandonroberts** [comment]
This has been merged
