### ISSUE TITLE
The repo link is still pointing toward angular.io

### ISSUE THREAD

**Issue by Leiloukou** [angular/angular#52871]
### Describe the problem that you experienced

The repo's website link is still pointing toward angular.io, while the README points to angular.dev

### Enter the URL of the topic with the problem

https://github.com/angular/angular

### Describe what you were looking for in the documentation

Not applicable 

### Describe the actions that led you to experience the problem

I went to the GitHub repo and clicked the link

### Describe what you want to experience that would fix the problem

Change the link

### Provide any additional information here in as much as detail as you can

```true
It's not actually a docs problem, but I don't know what other category to put it in.
```

**Comment by Leiloukou** [comment]
Sorry if this inconsistency was intentional. 😐

**Comment by JeanMeche** [comment]
We already changed the link in the readmebut for this one we'll need an admin. I'll tag devRel !

**Comment by twerske** [comment]
We will look at this and update before the site is stable in v18 at the latest!

**Comment by Leiloukou** [comment]
Oh, I'm sorry. I didn't know the new docs weren't stable yet... whoops.
