### ISSUE TITLE
@defer on scroll

### ISSUE THREAD

**Issue by andrei-agdo** [angular/angular#52888]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Currently, the @ defer don't have anything about load the block/component/whatever on scroll the page/block.

I think this feature can be useful in specific cases where I can have a condition to show only if i scroll until some part of page, or percentage os block/page.

I know this code can be made currently with `@defer( when topScrollValueOfDiv < (page.scrollPosition + page.size + 50) ) ` and create a listner to update page.scroll position and etc, but I think a native solution is better in all cases, developer experience and performance.

An important point to be considered, the `@defer( on hover(divAbove))` maybe can't be considered on fast scrolls, mobile and etc.

### Proposed solution

`
< div > a huge div bigger than screen size ( width or height ) < /div>

@ defer ( on scroll ) { < div > div out of view that loads when almost scroll position is coming < /div> }
`

### Alternatives considered

In my opinion, my proposed solution is simple for Developer Experience, but any alternative you decide on is excellent.

**Comment by jessicajaniuk** [comment]
I would agree with @JeanMeche. This is exactly what IntersectionObserver is meant to address, which is what the viewport trigger uses. Event listeners on scroll are heavy performance hits, typically.

**Comment by andrei-agdo** [comment]
Thanks a lot for reply @JeanMeche and @jessicajaniuk!   
I think the viewport trigger is a great solution, but I think in something more related of "prefetch", because the viewport starts load only when block is on viewport, and I think something more "prefetch before the block shows on viewport", because the block that "waiting" to load, can be a huge size and just start when user comming to the part where block are, causing a small (or maybe large) delay in the user flow until block finish download and render.
But if has some alternative like "viewport(number_of_pixels_or_percentage_below)" can be great too
I know can be a "hard working to small gain", it's just (my first) a little idea to try help the Angular's grow.

Thanks  again!

**Comment by andrei-agdo** [comment]
Yea @jessicajaniuk!!, event listeners on scroll are terrible performance, this is why I have opened this issue

**Comment by JeanMeche** [comment]
@andrei-agdo There is no magic, Angular would have to do the same costly operation under the hood.

**Comment by jessicajaniuk** [comment]
@andrei-agdo We've discussed having configuration for the viewport trigger for padding above / below the element to address the exact thing you mentioned. I think that's ultimately a better solution to the issue. We'll discuss.

**Comment by andrei-agdo** [comment]
@jessicajaniuk , searching more about padding above and below I have founded another issue https://github.com/angular/angular/issues/52799, so I will close this one.
But thanks a lot for your attention!
