### ISSUE TITLE
Change name of input from withComponentInputBinding

### ISSUE THREAD

**Issue by zygarios** [angular/angular#52883]
### Description

Currently, it is difficult to distinguish between the Input decorator that comes from the URL using withComponentInputBinding and the standard one that is passed from the parent component. Sometimes it can be difficult to find and understand that, for example, the @Input() decorator with the property id:string is actually taken from the path. Currently, this forces the use of its own non-standard naming convention, which can be too different depending on the context and team. Example:
`import {
    Component,
    ChangeDetectionStrategy,
    Input as RouteInput,
} from '@angular/core';`
 In this case, in my opinion, it would be better for Angular to impose conventions in this case. 

### Proposed solution

The solution I propose would be to change the name of the decorator to @RouteInput or @InputRoute, or possibly @Route to clearly indicate that the content received in it will come from the URL. At the same time, it would be good if its functionality only consisted of this and did not accept normal data passed from the parent. It is about a clear separation of the function it fulfills, and at the same time it would be immediately visible by looking at the component from what sources their data comes from. It may be a good option to include such a change as part of the upcoming inputrach based on signals, i.e. for example queryparam = routeInput(), similarly to how it will be in the case of customData = input() in future versions.

### Alternatives considered

An alternative option would be to add an additional option to @Input or input() that specifies its purpose, such as @Input({type: 'routeInput'}) or input({type: 'routeInput'}), which would change the behavior of the input. Instead of waiting for data from the parent, it would then also accept or only those originating from the URL address.

**Comment by JoostK** [comment]
With signal based inputs in the pipeline, my personal feeling is that `withComponentInputBinding` could perhaps be superseded by an alternative to `input`, e.g. `routeParameter()`. That wouldn't be an input in that case, just an accessor for a route parameter and nothing else.

**Comment by atscott** [comment]
+1 to what Joost said. There’s not really a way to do what you want for inputs. This would have to be an entirely new feature that’s not an input at all.

**Comment by eneajaho** [comment]
Hi @zygarios 
Maybe you are interested in a helper util like this one: https://github.com/nartc/ngxtension-platform/pull/149

**Comment by georgmu** [comment]
finding a solution for this (via separate decorator or signal) would also help with #52946.
