### ISSUE TITLE
@for ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by sysmat** [angular/angular#52885]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

- after changing from `*ngFor` to `@for` control flow I get error: ExpressionChangedAfterItHasBeenCheckedError

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-jx5weg?file=demo%2Fsrc%2Fapp%2Fapp.component.ts

### Please provide the exception or error you saw

```true
instrument.js:123 Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0
Node: 18.18.2
Package Manager: npm 10.0.0
OS: win32 x64

Angular: 17.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0
@angular-devkit/build-angular   17.0.0
@angular-devkit/core            17.0.0
@angular-devkit/schematics      17.0.0
@angular/cli                    17.0.0
@schematics/angular             17.0.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else?

# reproduction https://stackblitz.com/edit/stackblitz-starters-jx5weg?file=demo%2Fsrc%2Fapp%2Fapp.component.ts
- in terminal cd demo
- in terminal pnpm install
- in terminal pnpm run start
- in browser open dev console and see the error

**Comment by JeanMeche** [comment]
Hummm, this looks like a compiler issue with a missing `ɵɵadvance()`,  if any expert can confirm. 

If you add whatever interpolation before the for loop, the error vanishes (An `ɵɵadvance()` correctly added to the compiled template).

**Comment by sysmat** [comment]
@JeanMeche this is then a bug in `@for`  but yes it is strange when empty interpolation is added error is gone

**Comment by atscott** [comment]
Simplified reproduction: https://stackblitz.com/edit/stackblitz-starters-uenxzz
