### ISSUE TITLE
https://angular.dev/typescript.org/type-inference link from the tutorial returns Page not found

### ISSUE THREAD

**Issue by florinteodorescu** [angular/angular#52886]
### Describe the problem that you experienced

I clicked on the '[type inference in TypeScript](https://angular.dev/typescript.org/type-inference)' link in the page: https://angular.dev/tutorials/learn-angular/updating-the-component-class, but I got a Page not found error.

### Enter the URL of the topic with the problem

https://angular.dev/typescript.org/type-inference

### Describe what you were looking for in the documentation

I was expecting to see a page with more details about type inference in TypeScript.

### Describe the actions that led you to experience the problem

I was doing the Angular tutorial and clicked one of the links to get more details about a topic.

### Describe what you want to experience that would fix the problem

I was expecting to see a page with more details about type inference in TypeScript.

**Comment by JeanMeche** [comment]
Hi, this has been fixed by #52714 and is pending deployment.
