### ISSUE TITLE
Child directive events swallowed when destroyed by directives using viewContainer.remove

### ISSUE THREAD

**Issue by gionkunz** [angular/angular#5289]
I came across a behaviour when using `NgIf` and `NgFor` that I'd not expect. When child directives are removed by `NgIf` or `NgFor` using `ViewContainer.remove()`, any event produced by them just prior to the removal will be swallowed and not be conveyed to the parent directive.

I've created this little example that illustrates the behaviour: http://plnkr.co/edit/9F1I7HRe9Hzpo1qZOHMG?p=preview

The problem does not occur when they are moved by `NgFor` as the reordering of the data list shows. However, when children get removed (numbers exceed 4), their event is swallowed.

I guess this is a reference problem as children are operating on the data from the parent. At the time when a child directive is updating the data of the parent, the parent will probably kick in with change detection and removes the element before the event was captured. However, I'd expect that, any event that was sent prior removal using `ViewContainer` will be visible to the parent.

**Comment by mhevery** [comment]
could you better explain how to use the plnkr? What should I click on and what should the expected behavior be rather then what the actual behavior is.

**Comment by gionkunz** [comment]
Try clicking any of the components increment buttons until they reach the number 5. They will be removed from the parent as they do not meet the conditions to live any longer within the view of the parent. The child components emit an event when they are clicked and increment their value. Because of the imperative data structure the data within the parent will be affected directly by the action in the child components. As the parent is removing the components if they reach the number 5, the event the children emitted does never reach the parent component. I hope this makes any sense.

**Comment by birkskyum** [comment]
Also, the EventEmitter.next() is about to be renamed EventEmitter.emit() in #5302

**Comment by blesh** [comment]
Rx Subjects next _synchronously_ and dove-tail with Observables ... just saying. ;)

**Comment by pkozlowski-opensource** [comment]
Events are sync now so this one should be solved as well.
