### ISSUE TITLE
The "Making HTTP requests" link in https://angular.dev/guide/http is broken

### ISSUE THREAD

**Issue by nagashimam** [angular/angular#52890]
### Describe the problem that you experienced

The "Making HTTP requests" link in https://angular.dev/guide/http (CSS selector: "body > adev-root > div.adev-app-main-content > adev-docs > docs-viewer > nav > a:nth-child(2)") is linked to https://angular.dev/guide/http/making-requets/, not requests. 

It seems the intended URL is https://angular.dev/guide/http/making-requests/

### Enter the URL of the topic with the problem

https://angular.dev/guide/http

### Describe what you were looking for in the documentation

I was looking for how to make requests with HttpClient.

### Describe the actions that led you to experience the problem

Click the link.

### Describe what you want to experience that would fix the problem

Fix href attribute of the link

**Comment by JeanMeche** [comment]
Hi, this has been fixed by #52541 and is pending deployment.
