### ISSUE TITLE
defer `when` is not imperative

### ISSUE THREAD

**Issue by e-oz** [angular/angular#52897]
### Describe the problem that you experienced

https://github.com/angular/angular/blob/main/adev/src/content/guide/defer.md

This document has the phrase:   
> `when` specifies an imperative condition as an expression that returns a boolean.

But `when` (fortunately) is as declarative as `on` - they both declare how this part of the template should behave under certain conditions.

### Enter the URL of the topic with the problem

https://angular.dev/guide/defer

### Describe what you want to experience that would fix the problem

Please consider removing this part: "an imperative" - that would fix the issue completely.

**Comment by AndrewKushnir** [comment]
Closing since PR https://github.com/angular/angular/pull/52899 was merged.
