### ISSUE TITLE
docs :error in the code

### ISSUE THREAD

**Issue by SandeepBhartiya** [angular/angular#52896]
### Describe the problem that you experienced

When I am going through the documentation of angular 17. I Came to know that in the Component Section of Documentation at the **Custom events with outputs** tab, there is an error in the code.

Instead of @Output, we use @Input for EventEmitter which I think an error.

@Component({...})
export class CustomSlider {
  @Input('valueChanged') changed = new EventEmitter<number>();
}

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/outputs#emitting-event-data

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/101499022/2cf00800-f5d3-4cfd-86e4-ed282e88ad5d)

**Comment by JeanMeche** [comment]
Hi, this has been fixed by #52673 and is pedding deployement !
