### ISSUE TITLE
angular.dev module-based lazy loading guide is missing `--no-standalone` in app generation command

### ISSUE THREAD

**Issue by CondensedMilk7** [angular/angular#52909]
### Describe the problem that you experienced

[This line](https://github.com/angular/angular/blob/main/adev/src/content/guide/ngmodules/lazy-loading.md?plain=1#L61) is missing the `--no-standalone` flag. As a result, a standalone application is generated with no `app-routing.module.ts`.

### Enter the URL of the topic with the problem

https://angular.dev/guide/ngmodules/lazy-loading#step-by-step-setup

**Comment by muhammadawaisshaikh** [comment]
Hey 👋 I am looking forward to fix this issue, kindly assign it to me. Thanks

**Comment by g-cheishvili** [comment]
> Hey 👋 I am looking forward to fix this issue, kindly assign it to me. Thanks

The issue author already provided PR fixing the issue
