### ISSUE TITLE
Miss redirect for ngComponentOutlet

### ISSUE THREAD

**Issue by Fabricio-developer** [angular/angular#52915]
### Describe the problem that you experienced

I've been looking for the API references of ngComponentOutlet, but the link that redirects me doesn't find their content. 

References below:
https://angular.dev/guide/components/programmatic-rendering#using-ngcomponentoutlet
and click at **NgComponentOutlet API reference**

### Enter the URL of the topic with the problem

https://angular.dev/api/core/NgComponentOutlet

### Describe what you were looking for in the documentation

Ways to properly pass data using ngComponentOutlet

**Comment by JeanMeche** [comment]
Hi this has been fixed by #52829 and is pending deployement.
