### ISSUE TITLE
[SSR] Possibility of using a customized server

### ISSUE THREAD

**Issue by mcfdez** [angular/angular#52913]
### Describe the problem that you experienced

I recently tried migrating our application from Angular 16 to Angular 17, to test the new integrated SSR system.

We have seen that when a new application is generated using the CLI, a "server.ts" file is generated which is the express server on which to start the client application with SSR.

In our case we work on a monorepo in which we have two applications, one for the client and one for the server.

We have not seen anything in the documentation on how to configure a custom server, we have only found references to the "entry" configuration in the configuration file.

Is there any way or possibility to configure and use a custom server?

Thanks

**Comment by JeanMeche** [comment]
Hi, we're tracking this on the CLI repo angular/angular-cli#26323
