### ISSUE TITLE
(observable | async) does not subscribe to the observable in some circumstances

### ISSUE THREAD

**Issue by flyingmutant** [angular/angular#5291]
Try commenting/uncommenting «magic line» in app.ts, and note the difference in behavior when you have only entered one character into input box.

http://plnkr.co/edit/7cnZExkMqOraT7If4Iqu?p=preview

From my understanding, since observable is shared, and async pipe subscribes to it, extra subscription should not have any effect — but it does.

It very well may be something stupid I am missing here.

**Comment by mhevery** [comment]
@jeffbcross / @vsavkin can you comment?

**Comment by robwormald** [comment]
I dug into this a bit, I think its upstream from Rx. there's been a bunch of change in the share()/multicast() etc semantics this week.

@flyingmutant can you pull the latest version of RxJS in and try it with that? (just replace your Http call with a mock observable returning an array or similar.)

**Comment by flyingmutant** [comment]
I've played with this a bit more, and believe this is actually angular's issue.

1) The bug is still present without `.share()`
2) If you look into the console, there is not `reacting to new suggestions` message after entering the first symbol. That means that nobody has tried to subscribe to the observable yet (with 5 instances of the async pipe already in component).

Can it be related to the way `ng-for` works, maybe?

Please see the updated plunker: http://plnkr.co/edit/7cnZExkMqOraT7If4Iqu?p=preview

**Comment by flyingmutant** [comment]
Also, I've noticed that sometimes (but not always) the plunkr starts working after changing the active tab/window. Does that kick in some mechanism (change detection?) that forces everything to work?

**Comment by robwormald** [comment]
I'll dig deeper into this, as it definitely feels a bit wonky. That said - I think overall, this pattern is not a great idea, as you have a lot of subscriptions constantly being torn up and down. 

Rather than trying to match two async actions together in the view, the more idiomatic Reactive way would be something like this - http://plnkr.co/edit/WvAshfCfSx8tp8wvED08?p=preview - that is, doing all your async work and leveraging what Rx is good at (combinators), and keeping the view relatively logicless. Thoughts?

cc @jeffbcross

**Comment by flyingmutant** [comment]
With `.share()`, an extra subscription is nothing more than one callback being added to existing observable. I can't imagine this being a bottleneck unless dealing with *lots* of them.

As for if this an idiomatic Reactive way or not... I am not an expert on Rx, but I feel that my code is more direct and declarative.

With all other code being the same in both variants, I'll trade this imperative block (whose only purpose is to massage data in some arbitrary view-specific way)
```typescript
    this.suggestions = ng.Observable.combineLatest(searchSuggestions, myIndex, (suggestions, idx) => {
      return suggestions.map((suggestion, i) => {
        let selected = i === idx;
        return {suggestion, selected};
      });
    });
```
```html
<li *ng-for="#s of (suggestions | async)"
    [class.selected]="s.selected">
```

for this declarative one

```html
<li *ng-for="#s of (suggestions | async), #i = index"
    [class.selected]="i == (myIndex | async)">
```

any day.

**Comment by vicb** [comment]
please re-open if still an issue
