### ISSUE TITLE
Add REST API Endpoint to Universal

### ISSUE THREAD

**Issue by jdgamble555** [angular/angular#52929]
### Which @angular/* package(s) are relevant/related to the feature request?

Angular Universal

### Description

Angular Universal needs to be able to run custom Rest API easily just like every other SSR framework.  Then you could call it with the `http` function to get what you need.

React has `serverSideProps` (before server components), for example, and every single framework has their way of doing this.  This is a must.

The Angular Resolver could also call this api url (which could work on both server and client).

### Proposed solution

Allow the ability to POST, PUT, GET etc on the router when loading Angular, not outside of Angular itself.

This would require removing express dependencies:

https://github.com/angular/angular-cli/issues/25718#issuecomment-1801710144

...which needs to be done anyway in order for Angular to support Edge functions and other different hosting environments.

### Alternatives considered

File Based Routing would also solve this with server only paths.

**Comment by spock123** [comment]
@jdgamble555  Have you considered looking into Analog?

**Comment by jdgamble555** [comment]
@spock123 - I don't want the overhead, I don't need Vite, and I really don't care about File Based Routing.  Analog also doesn't use Angular Universal at all from my understanding.

I just want the ability to create server only routes that I can use inside my Angular App.  This is an absolute necessity for any server application.  Not all code needs to be available on the client.

Again, every other SSR Framework handles this out of the box.

J

**Comment by spock123** [comment]
@jdgamble555  I think I understand. Anything that keeps you from adding express endpoints to the generated server.ts code? I'm sorry if there's something I have missed.

**Comment by ElectroluxV2** [comment]
The thing is that new dev serve server does not support endpoints nor static providers per session.

**Comment by jdgamble555** [comment]
@ElectroluxV2 - I'm not sure I follow. What dev server? If you can have different routes, there is not reason you can't have different endpoints. I wrote a hack for this:

https://dev.to/jdgamble555/angular-universal-rest-api-endpoints-23fj

And here is my post to hopefully get the Angular Team and Community involved in this:

https://dev.to/jdgamble555/angular-is-much-better-but-is-angular-universal-57nb

J

**Comment by ElectroluxV2** [comment]
When you run ng serve while using angular 17 the server.ts file is ignored.

**Comment by jdgamble555** [comment]
@ElectroluxV2 - If you're using the latest version, it uses `app.config.server.ts` and `main.server.ts`, but either way, the general way the app gets bootstrapped would have to be updated.

**Comment by alan-agius4** [comment]
Hi @jdgamble555, I am not really following what is the problem that needs to be solved with this feature request. Can you please elaborate?

**Comment by jdgamble555** [comment]
Hey @alan-agius4 - Sure. How do you create endpoints with @angular/ssr? Endpoints are necessary for many reasons, but mainly to quickly fetch data on the server and to safely fetch data without exposing database credentials. The way Angular seems to work right now, is all code is run on the server and browser.

There needs to be `server-only` routes for `get`, `post`, etc. so the user can protect their data. I kind of made a [hack version](https://dev.to/jdgamble555/angular-universal-rest-api-endpoints-23fj) of this a while back, but this should be built in so that you can easily create endpoints. I'm honestly not sure what this would look like in Angular SSR, but it is a necessity for any Server Framework. I wouldn't think there would be much to this, as it is a routing problem really. 

J

**Comment by alan-agius4** [comment]
I don't agree that this is a routing problem as the endpoints are outside of the scope of the Angular router. At the moment, API creation is a the desecration of the user, users can add the APIs as part of their Express setup, can use Nest.js and Nitro. We will however be looking to provide easier integration in the future.

When it comes to server only API routes, this seems to be more of a security and access issue that needs to be configured at an API not Angular level. And in the case, that users want to hit different end-points on the server and browser. Interceptors are the recommended approach. 

That said, I am curios for the use-case to why you'd want to have 2 different APIs end-points to populate the same data Ie: for the server and for the browser when the users navigates to another page within the app that is client side rendered.

**Comment by jdgamble555** [comment]
We are really talking about two different problems here:

## 1. Endpoints

> I don't agree that this is a routing problem as the endpoints are outside of the scope of the Angular router. At the moment, API creation is a the desecration of the user, users can add the APIs as part of their Express setup, can use Nest.js and Nitro.

Ultimately an endpoint is a route. [Express as a dependency](https://github.com/angular/angular-cli/issues/25718) is a problem as we have discussed too. It doesn't have to be configured with File Based Routing, it could be Angular Router, but it needs to be allowable somehow, or just easily creatable at the very top level. **ALL** other SSR frameworks do this:

- SvelteKit - [API Route](https://kit.svelte.dev/docs/routing#server)
- NextJS - [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/route-handlers)
- Remix - [Resource Routes](https://remix.run/docs/en/main/guides/resource-routes#handling-different-request-methods)
- NuxtJS - [Server Endpoints](https://nuxt.com/docs/getting-started/server#server-endpoints-middleware)
- SolidStart - [API Routes](https://start.solidjs.com/core-concepts/api-routes)
- Qwik City - [Endpoints](https://qwik.builder.io/docs/endpoints/)
- Astro - [Server Endpoints](https://docs.astro.build/en/core-concepts/endpoints/#server-endpoints-api-routes)

This does not get into **Server Actions** or **server$** (for just importing data directly -- creates endpoints under the hood). I didn't feel like finding those links, there are many variations, but premise is the same.

> At the moment, API creation is a the desecration of the user...  

Which is why I have a feature request for this.

> When it comes to server only API routes, this seems to be more of a security and access issue that needs to be configured at an API not Angular level. And in the case, that users want to hit different end-points on the server and browser. Interceptors are the recommended approach.

I'm not following. You can use interceptors with HttpClient / fetch to (pre/post)-process your data, but all of these frameworks expect you to handle XSRF and Content Security Policies on your own. 

> That said, I am curios for the use-case to why you'd want to have 2 different APIs end-points to populate the same data Ie: for the server and for the browser when the users navigates to another page within the app that is client side rendered.

I think you misunderstood this. Right now, there is no way to separate your server-only code from your browser-only code with out using `isPlatformBrowser` or some kind of `if` statement.  Some code I don't want to run twice. I ONLY want it to run on the server. I don't want my server-only code to be in the browser bundles at all, creating extra overhead. 

## 2. Pre-loading Data

This brings me to the related problem. If we want to pre-load data, we generally use Resolvers or `APP_INITIALIZER`. But if you're using SSR, you're going to want to load server only data. Here is a Drizzle example to be clear of why you need this, but it could be any database connection with sensitive information:

```ts
const queryClient = postgres("postgres://postgres:adminadmin@0.0.0.0:5432/db");
const db = drizzle(queryClient);
await db.select().from(...).leftJoin()...
```
Not only do I not want my login credentials visible to the server, but I also don't want my database schema etc. Sure you could use an external REST API with NestJS or something, by why would you make that extra call for no reason?
```
Browser Request --> Angular SSR --> NestJS Endpoint --> Database --> Angular SSR --> Browser
```
Why create an extra endpoint, then have to secure it for no reason when you're already on the server? 

#### Client Navigation
There is a caveat here. If the initial load is all loaded from the server, what happens when you click a link? SvelteKit solved this problem by creating a custom `fetch` function. When the fetch function is actually ran on the server and calling the same server it is being ran on, it simply turns in to an RPC function so there is no extra extra extraneous call. If the fetch is called from the browser, it works just like a normal fetch would.

All SSR frameworks use `load` functions for this, or something similar with a different name. Again, I don't feel like finding more links, but you get the point. A load function is basically Angular's equivalent to a resolver, but it has server-only options (client, server, or both). The implementations can vary, but premise is the same.

___

This is absolutely something a modern framework needs. It saves client code size, adds security, would be easier to implement, and would load quicker. This would open the door for "Form Actions" (which everyone agrees is a good idea), and potentially these `server$` rpc functions later (Rich Harris is against, but I disagree with him).

I think the reason Analog was created, because Angular did not get any love in the server space at all (and Vite). But Angular honestly doesn't need a meta-framework because it has SSR built in. What kind of SSR framework does it plan to be? If features like endpoints and server-only code execution are not at the top of the list, there is no need for half an SSR Framework, and Analog is the way to go. 

Thanks for looking at this,

J

**Comment by jdgamble555** [comment]
@alan-agius4 - Are you guys understanding the issue here? Should I create a new issue for loading data (# 1 here)? It is really two issues:
1. Loading Data initially from the server only on page load (usually because can't expose credentials to client)
2. Loading Data From Endpoint (Rest, server$, form actions)

Here is a new video from Misko Hevery about # 1
https://twitter.com/mhevery/status/1729973597702381602?s=20

J

**Comment by alan-agius4** [comment]
For the first item at the moment and this can be done by using DI. See https://github.com/angular/angular/issues/53168. Maybe we need a different way? 

With regards to the second item, this feels like a completely separate feature and thus I recommend that you do open a new feature request.

**Comment by jdgamble555** [comment]
@alan-agius4 - Yes, technically that works. I also found a work-around for the [Rest API Endpoints](https://dev.to/jdgamble555/angular-universal-rest-api-endpoints-23fj). The problem is that both solutions create a lot of boilerplate, but there does seem to be a solution.  Good to know.

The [Vercel Edge Issue](https://github.com/angular/angular-cli/issues/25718#issuecomment-1833956739) does not have a workaround at all, and is more important.  Please create a fix for this.

You can close this issue, but I hope that your team can work on ways to remove the boilerplates for this in the future.

J
