### ISSUE TITLE
Views attached inside OnPush components are not checked in some circumstences

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#52928]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Currently attaching a view doesn't mark ancestor views for check. This means that there is no way to get to a new view, even if it is dirty initally.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/onpush-dynamic-creation-qxpe1m?file=src%2Fmain.ts

### Please provide the exception or error you saw

There is no error but the newly inserted view is not change detected.

**Comment by xliu-alterdomus** [comment]
Which release can solve this issue? I face the same issue in Angular 16.

**Comment by trinhtuanvy** [comment]
> ### Which @angular/* package(s) are the source of the bug?
> 
> core
> 
> ### Is this a regression?
> 
> No
> 
> ### Description
> 
> Currently attaching a view doesn't mark ancestor views for check. This means that there is no way to get to a new view, even if it is dirty initally.
> 
> ### Please provide a link to a minimal reproduction of the bug
> 
> https://stackblitz.com/edit/onpush-dynamic-creation-qxpe1m?file=src%2Fmain.ts
> 
> ### Please provide the exception or error you saw
> 
> There is no error but the newly inserted view is not change detected.
> 
> ### Please provide the environment you discovered this bug in (run `ng version`)
> 
> _No response_
> 
> ### Anything else?
> 
> _No response_

**Comment by trinhtuanvy** [comment]
Fix help thanks
