### ISSUE TITLE
canDeactivate Guard Working After Browser Has Already Changed URL On Backward Navigation

### ISSUE THREAD

**Issue by martincoutts** [angular/angular#52924]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

In our code we have a canDeactivate guard which checks if a form is dirty on a page and if so displays a dialog asking the user if they want to discard their changes. If they click “discard” the navigation will continue, if they click cancel then they remain on that page and the prompt is dismissed.

We have a back button which uses location.back to navigate to the previous page. When the user clicks the back button the URL changes to that of the previous page before the canDeactivate guard can intervene and prevent the URL being changed, although the navigation does not take place the URL is incorrect. This is an issue as when the “dirty prompt” is displayed the URL is incorrect until the user clicks “cancel”. If the app refreshes while the dialog is open and the user has not clicked "cancel" then it will open on the previous page. This also happens if backwards navigation is done by history.back. It seems the native browser navigation methods execute before the canDeactivate guard does.

The desired behaviour would be that the URL would not be changed until the canDeactivate guard returns true.

To reproduce:

1. Make sure you are on the homepage (/home).
2. Navigate to the object component using the link on the homepage.
3. Navigate back using one of the "Navigate Back" buttons.
4. The URL will change to /home and then an alert from the route guard will be displayed.
5. The URL will be "/home" and when you dismiss the alert the URL will switch back to "/object”.

### Please provide a link to a minimal reproduction of the bug

https://github.com/martincoutts/angular-route-guard-bug

### Please provide the exception or error you saw

```true
The URL is altered to previous page by location.back before the canDeactivate guard can prevent the URL changing.

The desired behaviour would be that the URL would not be changed until the canDeactivate guard returns true.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0
Node: 18.17.0
Package Manager: npm 9.6.7
OS: darwin x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1700.0 (cli-only)
@angular-devkit/core         17.0.0 (cli-only)
@angular-devkit/schematics   17.0.0 (cli-only)
@schematics/angular          17.0.0 (cli-only)
```

**Comment by atscott** [comment]
What you’re looking for is here: https://angular.io/api/router/RouterConfigOptions#canceledNavigationResolution

**Comment by martincoutts** [comment]
Already tried using canceledNavigationResolution: 'computed' in our codebase and also in the minimum reproduction and it does not fix the issue.

**Comment by atscott** [comment]
Oh, I didn't read what your exact request was: 

> The URL is altered to previous page by location.back before the canDeactivate guard can prevent the URL changing.
> The desired behaviour would be that the URL would not be changed until the canDeactivate guard returns true.

This is not actually possible. The URL changing on back button click is browser behavior.

**Comment by martincoutts** [comment]
Thank you for replying and for letting me know.

**Comment by martincoutts** [comment]
@atscott would it not be possible for the router to push the URL state back to what it was before guards run? Currently, the guard has not decided whether the navigation should be cancelled or not and the URL has acted like it has. Guards currently don’t work well with this dirty prompt dialog use-case as a result.

**Comment by atscott** [comment]
> @atscott would it not be possible for the router to push the URL state back to what it was before guards run? Currently, the guard has not decided whether the navigation should be cancelled or not and the URL has acted like it has. Guards currently don’t work well with this dirty prompt dialog use-case as a result.

Yes and no. You can try to do a bunch of things but at the time that the Router can observe the navigation, the browser has already traversed locations its history. The only possible thing would be to traverse back (this operation is not synchronous), ignore this new `popstate` event, then traverse again after the navigation is ready to commit. This state juggling with the browser isn't really reasonable with the current APIs available to us.

**Comment by atscott** [comment]
Note that this sort of thing was discussed a lot in the design for the new browser navigation API and was specifically designed as a non-goal to disallow trapping a user on a page: 
* https://github.com/WICG/navigation-api#security-and-privacy-considerations
* https://github.com/WICG/navigation-api#goals

**Comment by martincoutts** [comment]
@atscott thanks for the your help.
