### ISSUE TITLE
angular_1_router, angular1 & angular2 in the same app not working.

### ISSUE THREAD

**Issue by varghesep** [angular/angular#5292]
I'm using **angular 1.4.7** and **angular_1_router** in an app. It works fine. Into this mix, I added **angular2 alpha.46** version.

What I'm trying to do is use angular1 for some legacy code and angular2 in some areas where there is a new UI.

I have described this problem in two questions on Stackoverflow:

1. [module not found error when using system module](http://stackoverflow.com/questions/33712265/gulp-typescript-giving-module-not-found-error-for-angular2)
2. [compiles fine with commonjs but causes a runtime error](http://stackoverflow.com/questions/33709802/decorator-is-not-a-function-error-when-angular1-angular2-angular-1-router-u).

**Comment by brandonroberts** [comment]
#1. Do you have @reactivex/rxjs installed? 

#2 This is a bug in the angular 1 router build. The Injectable function doesn't return a function which is used by the decorator. If you want to manually edit your angular 1 router build file, Update the following code in your angular_1_router.js file.

```js
var exports = {Injectable: function () {}};
```

to 

```js
var exports = {Injectable: function () {
  return (function(target) {
    return target;
  });
}};
```

**Comment by varghesep** [comment]
1. Please see the attached image. It is installed under angular2.

2. The issue is resolved after I made the change that you suggested.

![rxjs](https://cloud.githubusercontent.com/assets/12233474/11167168/5544e132-8b1c-11e5-80e8-6944c09aa918.png)

**Comment by mhevery** [comment]
won't fix
