### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by vasnimartin** [angular/angular#52937]
### Describe the problem that you experienced

When I click the the link, https://angular.dev/typescript.org/type-inference this url page not found

### Enter the URL of the topic with the problem

https://angular.dev/typescript.org/type-inference

### Describe what you were looking for in the documentation

omit the type because of [type inference in TypeScript](https://angular.dev/typescript.org/type-inference).

### Describe the actions that led you to experience the problem

Explain omit the type because of [type inference in TypeScript]

**Comment by JoostK** [comment]
Thanks for the report, this has been fixed in #52714 which is pending deployment.
