### ISSUE TITLE
Angular.dev Tutorial "Updating the Component Class Section"

### ISSUE THREAD

**Issue by denilson32** [angular/angular#52936]
### Describe the problem that you experienced

The link to "type inference in TypeScript" leads to Page Not Found.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/updating-the-component-class

### Describe what you were looking for in the documentation

Expecting to see the documentation page that explains the type inference in TypeScript topic.

### Describe the actions that led you to experience the problem

By doing the tutorial, I wanted to read more about the type inference in TypeScript topic.

### Describe what you want to experience that would fix the problem

I want to navigate to the documentation page about the above topic.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/54433176/73dba8a2-a0bd-40a0-b906-31723530faf8)

**Comment by JoostK** [comment]
Thanks for the report, this has been fixed in https://github.com/angular/angular/pull/52714 which is pending deployment.
