### ISSUE TITLE
'FormsModule' does not appear to be an NgModule class.(-996002)

### ISSUE THREAD

**Issue by diyxiaoshitou** [angular/angular#52948]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

'FormsModule' does not appear to be an NgModule class.(-996002)
form_providers.d.ts(4, 19): This likely means that the library (@angular/forms) which declares FormsModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

### Please provide the exception or error you saw

```true
'FormsModule' does not appear to be an NgModule class.(-996002)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.1
Node: 16.18.0
Package Manager: npm 8.19.2
OS: darwin arm64

Angular: 4.3.6
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1500.1 (cli-only)
@angular-devkit/core         15.0.1 (cli-only)
@angular-devkit/schematics   15.0.1 (cli-only)
@angular/cdk                 2.0.0-beta.12
@schematics/angular          15.0.1 (cli-only)
rxjs                         5.0.3
typescript                   2.2.2
webpack                      3.12.0
```

**Comment by JoostK** [comment]
Based on the version output, this is mixing Angular 4 (hello 2017 👋) with Angular 15, which is incapable to work.
