### ISSUE TITLE
Missing app.modules.ts when creating new project

### ISSUE THREAD

**Issue by KIK22670** [angular/angular#52944]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

Jedes mal wenn ich ein neues angular projekt erstellt habe, hat mir einiges in app/src gefehlt. Ich habe von allem die neuste Version und habe es auch in den unterschiedlichsten Verzeichnissen ausprobiert.

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
