### ISSUE TITLE
Dependencies - See Angular's version compatibility

### ISSUE THREAD

**Issue by JohnStamatelos** [angular/angular#52959]
### Describe the problem that you experienced

The link '[Angular's version compatibility](https://angular.dev/versions)' embeded in `https://angular.dev/tools/cli/setup-local#dependencies` redirects to a `Page Not Found`

### Enter the URL of the topic with the problem

https://angular.dev/tools/cli/setup-local#dependencies

### Describe what you were looking for in the documentation

I was looking to be redirected to a page which has the Angular compatibility with node and npm.

### Describe the actions that led you to experience the problem

I created a new application locally to test and play with ng17 and the `ErrorHandler` class.
Once `ng new` completed, I saw my local version and that of the new app was 15. 

Then i went to the cool new angular.dev website and started to read and make myself familiar with it so i could understand if my local versions of `node` and `npm` are compatible with angular 17

### Describe what you want to experience that would fix the problem

I'd be happy to assist in fixing the problem, just now sure how i would go about figuring out what the intended site needs to be so that when a user clicks on `[Angular's version compatibility](https://angular.dev/versions)` they will be routed to the correct page instead of a `Page Not Found`

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/19415914/d03e2c80-cd01-4771-88a4-a100f90db050)

### If this problem caused an exception or error, please paste it here

```true
I copied the error and warning form the dev tools console, however i don't think it is relevant here.


main-PYD4EFEI.js:6 
        
        
       GET https://www.googletagmanager.com/gtag/js?id=G-XB6NEVW32B net::ERR_BLOCKED_BY_CLIENT
_installGlobalSiteTag @ main-PYD4EFEI.js:6
t @ main-PYD4EFEI.js:6
t.ɵfac @ main-PYD4EFEI.js:6
hydrate @ chunk-FKRGFWI2.js:7
get @ chunk-FKRGFWI2.js:7
lm @ chunk-FKRGFWI2.js:4
Ge @ chunk-FKRGFWI2.js:4
O @ chunk-FKRGFWI2.js:4
Oe @ main-PYD4EFEI.js:6
(anonymous) @ chunk-FKRGFWI2.js:7
hydrate @ chunk-FKRGFWI2.js:7
get @ chunk-FKRGFWI2.js:7
lm @ chunk-FKRGFWI2.js:4
Ge @ chunk-FKRGFWI2.js:4
O @ chunk-FKRGFWI2.js:4
sE @ chunk-FKRGFWI2.js:7
r @ chunk-FKRGFWI2.js:7
hydrate @ chunk-FKRGFWI2.js:7
get @ chunk-FKRGFWI2.js:7
lm @ chunk-FKRGFWI2.js:4
Ge @ chunk-FKRGFWI2.js:4
O @ chunk-FKRGFWI2.js:4
t @ chunk-FKRGFWI2.js:7
t.ɵfac @ chunk-FKRGFWI2.js:7
hydrate @ chunk-FKRGFWI2.js:7
get @ chunk-FKRGFWI2.js:7
lm @ chunk-FKRGFWI2.js:4
Ge @ chunk-FKRGFWI2.js:4
O @ chunk-FKRGFWI2.js:4
t @ chunk-FKRGFWI2.js:7
t.ɵfac @ chunk-FKRGFWI2.js:7
hydrate @ chunk-FKRGFWI2.js:7
get @ chunk-FKRGFWI2.js:7
lm @ chunk-FKRGFWI2.js:4
Ge @ chunk-FKRGFWI2.js:4
O @ chunk-FKRGFWI2.js:4
useFactory @ chunk-FKRGFWI2.js:7
r @ chunk-FKRGFWI2.js:7
hydrate @ chunk-FKRGFWI2.js:7
get @ chunk-FKRGFWI2.js:7
lm @ chunk-FKRGFWI2.js:4
Ge @ chunk-FKRGFWI2.js:4
Bi @ chunk-FKRGFWI2.js:4
o.factory @ chunk-FKRGFWI2.js:7
hydrate @ chunk-FKRGFWI2.js:7
get @ chunk-FKRGFWI2.js:7
resolveInjectorInitializers @ chunk-FKRGFWI2.js:7
(anonymous) @ chunk-FKRGFWI2.js:7
invoke @ polyfills-JQKAGIZ6.js:1
onInvoke @ chunk-FKRGFWI2.js:7
invoke @ polyfills-JQKAGIZ6.js:1
run @ polyfills-JQKAGIZ6.js:1
run @ chunk-FKRGFWI2.js:7
uA @ chunk-FKRGFWI2.js:7
Et @ chunk-6N6GUM5C.js:1
(anonymous) @ main-PYD4EFEI.js:7
versions:1 The resource https://angular.dev/assets/textures/gradient.jpg was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.```
```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
I get the same `Page Not Found` on both Chrome and Firefox
```

**Comment by JeanMeche** [comment]
Hi, this issue has been fixed by #52585 and is pending deployement !
