### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by m-aouzal** [angular/angular#52967]
### Describe the problem that you experienced

whe click to the link it saud that the page is not found

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/updating-the-component-class

**Comment by sdedieu** [comment]
Hi @m-aouzal ! Is the link you are mentionning `type inference in Typescript` ?
<img width="556" alt="Screenshot 2023-11-16 at 17 39 04" src="https://github.com/angular/angular/assets/57216011/d3e1e371-23d6-4cf0-86a8-a5878b959040">

(I'm on it)

**Comment by sdedieu** [comment]
EDIT: Already fixed in https://github.com/angular/angular/pull/52714/files
