### ISSUE TITLE
page not found: https://angular.dev/api/common#pipes

### ISSUE THREAD

**Issue by JaydevVadachhak** [angular/angular#52968]
### Describe the problem that you experienced

Steps to regenearte

1. go to **in-depth guides** -> **pipes**
2. Click on a link [pipes API documentation](https://angular.dev/api/common#pipes).
![Pipes-•-Overview-•-Angular](https://github.com/angular/angular/assets/60188810/8fa1f005-c086-4615-9031-bcea6d2919e0)
3. This gives an error of **page not found**
![Screenshot from 2023-11-16 21-55-25](https://github.com/angular/angular/assets/60188810/b642497a-4740-4c6a-bc28-3d9bbbe5b829)

### Enter the URL of the topic with the problem

https://angular.dev/api/common#pipes

**Comment by sdedieu** [comment]
I think that the correct link should be [https://angular.dev/api](https://angular.dev/api) with the Pipe button filter as active.
Sadly the active filters are not stored in the URL. 
One way of improving this [https://angular.dev/api](https://angular.dev/api) page and fix this issue would be to store the active filters as queryParams in the URL.

(I volunteer to do it by the way)

**Comment by fredsa** [comment]
Note the `.dev` and `.io` domains:

Broken:
- https://angular.dev/guide/pipes#built-in-pipes --> to https://angular.dev/api/common#pipes --> 404

The correct documentation can be found:
- https://angular.io/api/common#pipes --> https://v17.angular.io/api/common#pipes --> Yay!
