### ISSUE TITLE
Typo in Component Communication with @Input Docs

### ISSUE THREAD

**Issue by denilson32** [angular/angular#52960]
### Describe the problem that you experienced

In the app.commponent.ts file, the class is UserComponent instead of AppComponent.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/input#define-an-input-property

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/54433176/3fa56e5e-9b68-4b3b-bb38-a4371b65f894)

**Comment by satyakideshpande** [comment]
Can you explain this issue a little more. I want to solve this issue but would need some more information. 
Thanks

**Comment by JoostK** [comment]
This has already been addressed in #52964
