### ISSUE TITLE
tutorials

### ISSUE THREAD

**Issue by stbn1699** [angular/angular#52961]
### Describe the problem that you experienced

The command `ng new` in angular 17 needs to have '--no-standalone' for the `ng new` to create the app.module.ts and app-routing.module.ts files.

In this tutorial https://angular.io/tutorial/tour-of-heroes/toh-pt0, when we have to run the command `ng new angular-tour-of-heroes`, it doesn't say that we have to specify '--no-standalone'

### Enter the URL of the topic with the problem

https://angular.io/tutorial/tour-of-heroes/toh-pt0

### Describe what you were looking for in the documentation

just add '--no-standalone' for users that are in angular 17

### Describe the actions that led you to experience the problem

doing the tutorial

**Comment by spock123** [comment]
That's because new users are encouraged not to use ngModules, as the user experience and product is vastly inferior with modules, compared to without (think @defer)

**Comment by JeanMeche** [comment]
@aparzi Feel free to drop à PR !

**Comment by aparzi** [comment]
@JeanMeche ok thanks. When create a project with `ng new` I add a message for create a project as old structure (no standalone) ok?

Example:
For create a project with no standalone scaffolding execute:
`ng new [project-name] --no-standalone`

**Comment by aparzi** [comment]
Hi @JeanMeche, which file should I change?

**Comment by aparzi** [comment]
Hi @JeanMeche this PR may be closed, because PR #53117 update the ToH doc
