### ISSUE TITLE
Page https://angular.dev/api/core/NgComponentOutlet is Not Found

### ISSUE THREAD

**Issue by nishanthvallambatla** [angular/angular#52965]
### Describe the problem that you experienced

The URL https://angular.dev/api/core/NgComponentOutlet for new angular documentation site throws "Page Not Found" error.

### Enter the URL of the topic with the problem

https://angular.dev/api/core/NgComponentOutlet

**Comment by sasidharansd** [comment]
It's available in the link: https://angular.dev/api/common/NgComponentOutlet

**Comment by JeanMeche** [comment]
Where did you get that URL @nishanthvallambatla ?
