### ISSUE TITLE
Correct approach for search/filter operations on translated strings

### ISSUE THREAD

**Issue by sedax90** [angular/angular#52963]
### Which @angular/* package(s) are relevant/related to the feature request?

localize

### Description

I would like to understand what is the correct approach for solving this problem (who I imagine a lot of people has encountered on big applications).

We are currently using this approach for string translations:
- translations are stored on our server
- there is a pipe `translate` who change the original string with the translated string fetched async from a service.

Now consider a simple MatTable with an input filter for searching rows, if we filter data on our datasource we have to search on original strings for matching values, otherwise we don't get the correct results.

A basic solutions could be to preprocess all data strings on our component.ts, and pass translated data to the table datasource. This solution does not seems very good, because when a user change language (and our translation pipe is fired and we correctly have our content translated), we have to re process all data and update the table datasource accordly.

There is a better approach? What are the alternatives?

thanks.

### Proposed solution

Nothing

### Alternatives considered

None

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
