### ISSUE TITLE
ControlGroup, Control doesn't work with Polymer Iron and Paper elements

### ISSUE THREAD

**Issue by tejainece** [angular/angular#5297]
Angular material elements are not ready yet. Also, there seem to be no good UI widget library for Angular 2 yet.

So I tried Polymer Dart 1.0. Basic property and event bindings work. but I couldn't get ControlGroup and Control to work.

I am not sure, if it is problem with polymer or angular. But since these two libraries are from Google, shouldn't users expect them to inter-operate?

Thanks!

**Comment by antonmoiseev** [comment]
There is no a value accessor for `<paper-input>` elements. Try explicitly adding the default one by attaching `ng-default-control` directive:

```html
<paper-input
    label="Username"
    ng-control="username"
    ng-default-control>
</paper-input>
```

**Comment by mlaval** [comment]
Please add a repro if this is still an issue
