### ISSUE TITLE
Angular Dev Components

### ISSUE THREAD

**Issue by PrabhuTeja-Dasari** [angular/angular#52987]
### Description

Hii Team, Please provide Angular Dev Components for advanced like animations related to angular Materials and angular.io components related to angular materials and please develop the components of angular.dev related to angular Dev components

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
