### ISSUE TITLE
View Encapsulation page does not exist

### ISSUE THREAD

**Issue by TerranceKhumalo-absa** [angular/angular#52989]
### Describe the problem that you experienced

The view encapsulation page does not exist. When clicking the link it directs to this page: https://angular.dev/guide/components/view-encapsulation

### Enter the URL of the topic with the problem

https://angular.dev/guide/animations/complex-sequences

### Describe what you were looking for in the documentation

Details about the view encapsulation. Can you add advanced features of angular not just the basics to many places teaching the basics?
like how to use:
--web workers in angular
--Common angular design patterns like how to use the bridge pattern etc

**Comment by AndrewKushnir** [comment]
Closing as completed, PR #52995 is merged.
