### ISSUE TITLE
Broken reference link in Angular's 'Learn Angular' Docs > Updating the Component Lesson

### ISSUE THREAD

**Issue by dontpanicux** [angular/angular#53007]
### Describe the problem that you experienced

On the [Updating the Component Class](https://angular.dev/tutorials/learn-angular/updating-the-component-class) page in step 1 'Add a property called city', there's a link titled ['type interface in Typescript'](https://angular.dev/typescript.org/type-inference) that leads to a 'page not found'

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/updating-the-component-class

### Describe what you want to experience that would fix the problem

Seeing the correct documentation page as a result of clicking the 'type interface in Typescript' link

### Add a screenshot if that helps illustrate the problem

![angular-docs-issue](https://github.com/angular/angular/assets/17131736/82724f13-13e6-4a55-8251-d17cd1c3401c)

**Comment by sasidharansd** [comment]
Fixed with the PR: https://github.com/angular/angular/pull/52714. This issue can be closed.
