### ISSUE TITLE
Disable Dark Reader extension on angular.dev for better readability

### ISSUE THREAD

**Issue by danielalexis** [angular/angular#53003]
### Describe the problem that you experienced

When having the Dark Reader extension it makes several texts disappear on the new angular.dev documentation since the website is already dark.

### Describe what you were looking for in the documentation

https://angular.dev/ -> Notices on the top disappear
https://angular.dev/overview -> Sidebar textbar basically disappears
and more

### Describe the actions that led you to experience the problem

Having the Dark Reader extension on by default

### Describe what you want to experience that would fix the problem

This can be easily fixed by adding 
```html
<meta name="darkreader-lock">
```
to the `<head>`
See: https://github.com/darkreader/darkreader/blob/main/CONTRIBUTING.md#disabling-dark-reader-on-your-site

### Add a screenshot if that helps illustrate the problem

![imagem](https://github.com/angular/angular/assets/23124576/4ade15ca-5acc-472e-aa0a-551d7eda42b6)
![imagem](https://github.com/angular/angular/assets/23124576/bad9fb5c-a0e4-497f-a4d4-1545d1ab2dc1)

### If the problem is browser-specific, please specify the device, OS, browser, and version
Only happens due to Dark Reader not being disabled on angular.dev

**Comment by danielalexis** [comment]
The dark reader extension isn't a reader extension but rather an extension that turns websites into dark mode, so its safe to disable on angular.dev I think

**Comment by JeanMeche** [comment]
We won't support customization by external tools. Since angular.dev provides a dark theme, you should disable your extension for this site.
