### ISSUE TITLE
Keyboard accessiblity on the main page

### ISSUE THREAD

**Issue by stot3** [angular/angular#53016]
### Describe the problem that you experienced

Skips to footer after you click learn angular. 

### Enter the URL of the topic with the problem

angular.dev

### Describe the actions that led you to experience the problem

click on the content area, and tab through the home page

### Describe what you want to experience that would fix the problem

Each slide on the homepage needs to be keyboard tabable.

**Comment by JeanMeche** [comment]
Hi, can you give a more precise descrition of the issue you're having. This isn't really clear to us.

**Comment by santoshyadavdev** [comment]
I will take this up.

**Comment by santoshyadavdev** [comment]
@stot3 to understand the issue, can you see the video and let me know if this is exactly the issue you are referring to.

Steps:
- Open doc
- click inside the area where we have logo
- click tab and it skips entire animation ---> this is the problem?


https://github.com/angular/angular/assets/11923975/3793026d-5158-414d-9146-fdf326f3ae72

**Comment by stot3** [comment]
Yes, and when you shift tab, it completely erases the tab order. You got it.Sent from my iPhoneOn Dec 5, 2023, at 3:30 PM, Santosh Yadav ***@***.***> wrote:﻿
@stot3 to understand the issue, can you see the video and let me know if this is exactly the issue you are referring to.
Steps:

Open doc
click inside the area where we have logo
click tab and it skips entire animation ---> this is the problem?

https://github.com/angular/angular/assets/11923975/3793026d-5158-414d-9146-fdf326f3ae72

**Comment by JeanMeche** [comment]
Tab allows to skil the animation entirely.
