### ISSUE TITLE
Support input string in styleUrls 

### ISSUE THREAD

**Issue by viniciusschuelter** [angular/angular#53014]
### Which @angular/* package(s) are relevant/related to the feature request?

common, core

### Description

Like happen in styles property, would be great if can just pass a string of file path in styleUrls

### Proposed solution

Exactly like styles property string | string[] 

### Alternatives considered

Probably implement this like styles property is the best way, but if it not possible maybe include another property like 'styleUrl'

**Comment by crisbeto** [comment]
There's a `styleUrl` property in v17 that supports a single string.

**Comment by viniciusschuelter** [comment]
wow, this is kinda embarrassing, I promise to read the documentation better in the next one.
