### ISSUE TITLE
Can withViewTransitions provide an API for custom animation when jumping to a specific route?

### ISSUE THREAD

**Issue by huajian123** [angular/angular#53024]
### Which @angular/* package(s) are relevant/related to the feature request?

animations, router

### Description

I used RouteReuseStrategy, and then when I right-click the refresh button of the tab, I want to refresh it partially. My plan is to first save the current routing status (path and parameters), then jump from the current route to the "/" route, and then jump back to the current route based on the previously saved status. As a result, the animation of the route jump is visible to the naked eye. The page first returns to the login page, and then returns to the current route. I hope to hide the animation of the route jump at this time.
this is my source code:https://github.com/huajian123/ng-ant-admin
Right-click the refresh button of the tab to see the effect.
The picture below is the key code
![image](https://github.com/angular/angular/assets/31737260/f3e3f6b8-395f-4888-a091-f21f4d19250c)

### Proposed solution

Provide an API to specify the animation of jumping to a certain route, or not setting the animation of a certain route

### Alternatives considered

null

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
