### ISSUE TITLE
Page titles are not distinguishable 

### ISSUE THREAD

**Issue by stot3** [angular/angular#53020]
### Describe the problem that you experienced

The home page, should let the user know where they are at via the title tag. 

### Enter the URL of the topic with the problem

angular.dev

### Describe what you were looking for in the documentation

Angular | Home

### Describe the actions that led you to experience the problem

Inspecting the Page title. 

### Describe what you want to experience that would fix the problem

You should Append the location to the end of the title.

**Comment by JeanMeche** [comment]
Every page on angular.dev has a different title. I don't really get what you issue is here. 

Could you provide a more precise description of your issue  ?

**Comment by jnizet** [comment]
Not sure what the OP means, but titles could indeed be improved. For example, the home page, the Playground and the Tutorials page are all titled "Angular".

**Comment by aramirezj** [comment]
So, adev cannot be compiled still, but I think I know where should be changes applied so the titles would be

- Home: Home * Angular
- Playground: Playground * Angular
- Tutorials: Tutorials * Angular
I am gonna try to do a PR, but its not tested since adev not being able to compile yet.

**Comment by JeanMeche** [comment]
Fixed by #53026
