### ISSUE TITLE
Repeated list item in angular.dev's Anatomy of components page

### ISSUE THREAD

**Issue by racz16** [angular/angular#53029]
### Describe the problem that you experienced

In angular.dev, in the `In-depth Guides` / `Components` / `Anatomy of components` page, in the beginning, there is a list with 4 items, but the 3rd and the 4th items are exactly the same: 
> A [CSS selector](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors) that defines how the component is used in HTML

### Enter the URL of the topic with the problem

https://angular.dev/guide/components

### Describe what you want to experience that would fix the problem

In the `Essentials` / `Composing with Components` page, there is a similar list, where the 1st item is:
> A [@Component](https://angular.dev/api/core/Component)[decorator](https://www.typescriptlang.org/docs/handbook/decorators.html) that contains some configuration

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/19560859/6d90b1d4-5a2a-4e83-b0ae-9dce6b6b0762)

**Comment by aramirezj** [comment]
Seems like it is already fixed by https://github.com/angular/angular/pull/52587

**Comment by JoostK** [comment]
Closing as fixed, but pending deployment.
