### ISSUE TITLE
Multiple CSS Animations are not prefixed during build

### ISSUE THREAD

**Issue by laurenzfiala** [angular/angular#53038]
### Command

build, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

unknown

### Description

I use Angular 16.2 and wanted to add multiple CSS animations to one of my CSS rules.
It seems only the first animation name is prefixed properly, the following ones are not. This only applies to the production build: `ng build` or `ng s -c production`. Normal `ng serve` works fine.

`ng s`:
![image](https://github.com/angular/angular-cli/assets/22824759/4f15914e-670d-4c3c-a6e5-a42750aa7e94)

All animations are applied correctly.

`ng s -c production` (also `ng build`):
![image](https://github.com/angular/angular-cli/assets/22824759/c9b17fef-48e5-4df5-993b-36bd7e4f44c9)

Only the first animation is applied correctly.

I also ran `ng update` to Angular 17 on the reproduction repo and the issue was still reproducible.

### Minimal Reproduction

https://github.com/laurenzfiala/ng16-animations-repro

You can check the commits, I added only a few lines of CSS for a working reproduction.

### Your Environment

```text
Angular CLI: 16.2.10
Node: 18.18.2
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 16.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.10
@angular-devkit/build-angular   16.2.10
@angular-devkit/core            16.2.10
@angular-devkit/schematics      16.2.10
@angular/cli                    16.2.10
@schematics/angular             16.2.10
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
```

**Comment by Denigt** [comment]
If you disable the optimization on the production configuration the animations works properly (but the bundle is bigger and in the browser's console appears the message "Angular is running in development mode")
Also other option is use the development configuration until the bug will be solved

You can disable the optimization here:
`angular.json > projects > your_project_name > architect > build > configurations > production`

```json
          "production": {
              "optimization": false, // <-- here
              "budgets": [
                {
                    "type": "initial",
                    "maximumWarning": "500kb",
                    "maximumError": "1mb"
                },
                {
                    "type": "anyComponentStyle",
                    "maximumWarning": "2kb",
                    "maximumError": "4kb"
                }
              ],
              "outputHashing": "all"
          },
```

**Comment by laurenzfiala** [comment]
Any update on this?

**Comment by zouyi100** [comment]
Any update on this?

**Comment by faklyasgyuri** [comment]
For me, after changing angular.json optimalization properties, it worked properly. But I wasn't satisfied with the solution, so I refactored my code using [Angular Animations ](https://angular.io/guide/animations). With this, my page works perfect, and it's easier to maintain, and don't have to change angular.json, so I offer you this way.

**Comment by guillermodelagala** [comment]
Same problem here. Optimization false do the trick but that is not a solution at all.

**Comment by asphub** [comment]
I'm also facing the same issue. Only the development configuration for Angular is functioning properly. In short, problems arise when the optimization option is set to true.

**Comment by svchostdotexe** [comment]
up, same issue

**Comment by misicode** [comment]
I had the same issue. The only thing I could do was encapsulate my html element with the two animations in another <div> to separate the CSS animations.

**Comment by kschaefe** [comment]
I have a simple loading animation that is isolated to a small component.  I was able to work around the problem by setting the view encapsulation to `None`. This is a suboptimal fix, but better than reconfiguring the optimization settings.

**Comment by laurenzfiala** [comment]
I just retested this and it is still reproducible in v17.3.11 and v18.0.4.

@kschaefe The best solution i know of is to put the animations in the global stylesheet (and using a unique name). Disabling view encapsulation makes it very hard to debug selector collisions and leads to frustration.

**Comment by puckowski** [comment]
I believe I have a solution in PR #56800 

I will support PR change requests made by the Angular team and hopefully we can resolve this issue in a future release.
