### ISSUE TITLE
Repetitive line on the component anatomy page

### ISSUE THREAD

**Issue by octagony** [angular/angular#53049]
### Describe the problem that you experienced

repetitive line on the component anatomy page in angular.dev

![image](https://github.com/angular/angular/assets/56512747/779e598e-879b-45b1-a010-077c019f9f53)

### Enter the URL of the topic with the problem

https://angular.dev/guide/components

**Comment by JoostK** [comment]
Thanks for the report, already addressed in https://github.com/angular/angular/pull/52587 but pending deployment.
