### ISSUE TITLE
The @Output is misspelt as @Input in the output decorator docs.

### ISSUE THREAD

**Issue by veerakumar2k** [angular/angular#53044]
### Describe the problem that you experienced

in the angular.dev output decorator docs page below CustomSlider component sample @Output is misspelt as @Input

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/outputs

### Describe what you were looking for in the documentation

@Output decorator

### Add a screenshot if that helps illustrate the problem

<img width="1428" alt="Screenshot 2023-11-20 at 1 13 13 PM" src="https://github.com/angular/angular/assets/84136744/594c3578-e2df-445b-bc7e-66f91db6c7a4">

**Comment by JoostK** [comment]
Thanks for the report, this was addressed in https://github.com/angular/angular/pull/52673 but has not yet been deployed.
