### ISSUE TITLE
Missing asset URL for tutorial app

### ISSUE THREAD

**Issue by BrittanyLouviere** [angular/angular#53041]
### Describe the problem that you experienced

The tutorial wants me to use this url (https://angular.dev/assets/tutorials/common) to retrieve images and data for the tutorial application. When run on my local machine, the console says the data is uninitialized. When I try to access the page directly in my web browser I get a "Page not found" error. The project seems to run fine in the IDE that's integrated into the tutorial page but not outside of that. I think the page may not be set to be public facing.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app/dynamic-template-values

### Describe what you were looking for in the documentation

A functional link.

### Describe the actions that led you to experience the problem

I am working through the tutorial on my local machine instead of the IDE embedded on the tutorial page. Otherwise, I am following the tutorial to the letter.

### Describe what you want to experience that would fix the problem

I would like the link to work outside of the embedded IDE.

### Add a screenshot if that helps illustrate the problem

![Screenshot_20231120_172020](https://github.com/angular/angular/assets/67611757/8186a15f-e6fa-4f3b-9978-d3ba4322165c)

![Screenshot_20231120_172054](https://github.com/angular/angular/assets/67611757/76c7e0c1-5d50-4041-bca4-7db45992c8c6)

### If this problem caused an exception or error, please paste it here

```true
main.ts:8 ERROR TypeError: Cannot read properties of undefined (reading 'name')
    at HousingLocationComponent_Template (housing-location.component.html:2:62)
    at executeTemplate (core.mjs:12156:9)
    at refreshView (core.mjs:13396:13)
    at detectChangesInView (core.mjs:13621:9)
    at detectChangesInViewIfAttached (core.mjs:13584:5)
    at detectChangesInComponent (core.mjs:13573:5)
    at detectChangesInChildComponents (core.mjs:13634:9)
    at refreshView (core.mjs:13446:13)
    at detectChangesInView (core.mjs:13621:9)
    at detectChangesInViewIfAttached (core.mjs:13584:5)
```
```


### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Tested on Brave and Firefox. Both give a "Page not found". I do not think it is browser-specific.
```

**Comment by santoshyadavdev** [comment]
Hey @twerske I can take this up, is this part of new docs?

**Comment by santoshyadavdev** [comment]
Hi @BrittanyLouviere,

when you are using it locally can you share src/app/home/home.component.ts code.

the image is accessible from outside too, looks like the data is not passed properly on home.component.ts, once you share the code we can help.

eg: https://angular.dev/assets/tutorials/common/example-house.jpg this image is accessible from anywhere

**Comment by BrittanyLouviere** [comment]
@santoshyadavdev 

Sorry, I just looked back at my code and realized I left off the `[housingLocation]="housingLocation"` attribute for the `app-housing-location` tag. Once I added that in, it was able to grab the image. Thank you though!
