### ISSUE TITLE
ng0100 error while running test case after Angular upgrade

### ISSUE THREAD

**Issue by NavneetVaid** [angular/angular#53046]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Our few test cases has started failing suddenly after angular 16 upgrade, we are basically getting issues with change detection, even though we are using onPush in components we are facing issue and triggering detect changes manually in spec files still the values are not getting updated 

Consider a scenario - We have one variable based on which if we set it to true we disable the component and vice versa, when we try to test it from spec file and set the variable to true to disable the component and then take component instance it still have the old value with it

The second error which i am getting in terminal although no test case is failing because of this ---  
console.error
    Error: Could not parse CSS stylesheet

We are using JEST framework 

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.2.8
Node: 18.17.0
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 16.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, upgrade

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1602.8
@angular-devkit/build-angular      16.2.8
@angular-devkit/build-ng-packagr   0.1002.0
@angular-devkit/build-optimizer    0.1302.1
@angular-devkit/build-webpack      0.1602.8
@angular-devkit/core               16.2.8
@angular-devkit/schematics         16.2.8
@angular/cdk                       16.2.0
@angular/cli                       16.2.8
@schematics/angular                14.2.10
ng-packagr                         16.2.3
rxjs                               7.8.1
typescript                         5.1.6
zone.js                            0.14.1
```

**Comment by JoostK** [comment]
It is not clear what the problem here could be, without a reproduction this won't be actionable.

**Comment by NavneetVaid** [comment]
@JoostK  The setup we have is pretty complicated and i am not sure how the exact stuff would be replicated but i can help you with some more specific details if you want ? 

The detailed error message - 
    NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'ng-pristine': 'true'. Current value: 'false'. Expression location: BunsenInputSelectComponent component. Find more at https://angular.io/errors/NG0100

Has something changed as part of change detection in angular 16 ??

**Comment by JoostK** [comment]
We'd need a minimum reproduction to proceed.

**Comment by NavneetVaid** [comment]
I understand, i will try if i can reproduce, but can you help me with this if something has changed as part of angular 16 upgrade in terms of change detection as the test case failing now with dreaded error expression has been changed after it was checked was not coming earlier

**Comment by alxhub** [comment]
I'm going to close this, as without a reproduction we can't really investigate any further (nor can we be certain the change is related to `@angular/core` and not a third-party library).
