### ISSUE TITLE
Angular.dev tutorial typo: Be sure to add AppComponent to the imports array of AppComponent

### ISSUE THREAD

**Issue by fleckc3** [angular/angular#53051]
### Describe the problem that you experienced

I think its meant to be: Be sure to add UserComponent to the imports array of AppComponent

![image](https://github.com/angular/angular/assets/56199927/ca5df177-72ac-44dd-9d16-02f07f5e75bf)

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/composing-components

**Comment by aramirezj** [comment]
Fixed already but still not deployed I think

**Comment by JoostK** [comment]
Thanks for the report, this is being addressed in #52604

**Comment by JeanMeche** [comment]
Fixed by  #52677
