### ISSUE TITLE
Need clarification around inheritance of OnPush strategy

### ISSUE THREAD

**Issue by antoninklopp** [angular/angular#53057]
### Describe the problem that you experienced

[In the change detection strategy documentation](https://angular.io/api/core/ChangeDetectionStrategy), for OnPush, there is written `This strategy applies to all child directives and cannot be overridden.`

Reading this, I would expect that when setting the OnPush change detection strategy, all the children from the tree would have the OnPush strategy. It does not seem to be the case. 
In [this stackblitz](https://stackblitz.com/edit/test-change-detection-xdu?file=src%2Ftest.component.ts), you can set and unset `OnPush` change detection strategy in the test component and it behaves as expected regarding the strategy (not changing on OnPush, changing on default), however the component remains the child of a component with `OnPush` set and thus the child **does not inherit from the strategy of the parent**. 

Would it be possible to clarify what is meant by "child" here and the inherited behavior of OnPush? 

Thank you!

### Enter the URL of the topic with the problem

https://angular.io/api/core/ChangeDetectionStrategy

**Comment by JeanMeche** [comment]
Let's continue the discussion in #50943.
