### ISSUE TITLE
Can't use more conditions in new control flow (@switch) in Angular 17

### ISSUE THREAD

**Issue by dagarint** [angular/angular#53050]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Hello,

if I use more than one condition in control flow (@case) Angular skip and ignore the second condition. In the example below, it ignores "caseC" - like if there isn't condition "caseC".

I use in Angular 17.

Thanks for the reply.

By, Tomaž

### Please provide the exception or error you saw

```true
@switch (condition) {
  @case (caseA || caseC) {
    Case A.
  }
  @case (caseB) {
    Case B.
  }
  @default {
    Default case.
  }
}
```

**Comment by JeanMeche** [comment]
Hi, we're already tracking this issue in #14659
