### ISSUE TITLE
Page Not Found for Platform Browser API

### ISSUE THREAD

**Issue by Tayuelo** [angular/angular#53060]
### Describe the problem that you experienced

I was reading the guide for animations in the new angular.dev and found a link that should redirect to the resource for provideAnimationsAsync but instead shows the Page Not Found.

![Screenshot 2023-11-20 at 1 23 06 PM](https://github.com/angular/angular/assets/42228251/c3587512-1b87-4632-a228-ae872a2ce971)

### Enter the URL of the topic with the problem

https://angular.dev/api/platform-browser/animations/provideAnimationsAsync

### Describe what you were looking for in the documentation

I was looking for information about the provideAnimationsAsync function.

### Describe the actions that led you to experience the problem

- Open this link https://angular.dev/guide/animations
- Scroll to https://angular.dev/guide/animations#enabling-the-animations-module
- Click the link for provideAnimationsAsync
- Page Not Found

### Describe what you want to experience that would fix the problem

I would love to be able to access the documentation for provideAnimationsAsync from angular.dev

### Add a screenshot if that helps illustrate the problem

![Screenshot 2023-11-20 at 1 25 58 PM](https://github.com/angular/angular/assets/42228251/0cd9c2b8-6f1e-428d-a9b3-6bc1bd8186ab)
![Screenshot 2023-11-20 at 1 26 31 PM](https://github.com/angular/angular/assets/42228251/68986b3c-9293-4b85-9aa9-790df6845754)

### Provide any additional information here in as much as detail as you can

```true
In angular.io we don't find the corresponding documentation for provideAnimationsAsync either.
```

**Comment by JeanMeche** [comment]
Note there are 2 issues here: 

* The reference should point to `platform-browser/animations/async/provideAnimationsAsync`
* The missing API entry for `provideAnimationsAsync` is part of #52663

**Comment by JeanMeche** [comment]
There is still some work to do on our side. Some API entries are still missing (like this one). 
I'll let you know when it's done !

**Comment by JeanMeche** [comment]
The `provideAnimationsAsync` has been added #54517. 
Also the reference is not a link anymore.
