### ISSUE TITLE
Import reflect-metadata

### ISSUE THREAD

**Issue by radek-holy** [angular/angular#5306]
I tried to add a unit test of a controller into my test suite that is executed by Protractor. Protractor fails with `reflect-metadata shim is required when using class decorators`. It turned out that there is [a workaround](https://github.com/angular/benchpress-tree/issues/4) (`import "reflect-metadata";`).
I don't actually understand what is going on but I believe that this import should be somewhere in Angular so that people writing their unit tests does not need to do that. After all, it's Angular what requires us to use class decorators...

Please note that I understand that Protractor is neither designed to run unit tests nor it supports Angular 2 but I believe that this issue is not related to Protractor nor to my wrong usage of it. I believe that any test runner that does not use class decorators (and thus imports reflect-metadata) will report the same error.

A simple reproducer follows:
angular2@2.0.0-alpha.46
```typescript
// spec.ts
import * as controller from "./controller";

describe("", () => {
    it('', () => {
        let instance = new controller.Controller();
    });
});
```
```typescript
// controller.ts
import * as ng from "angular2/angular2";

@ng.Component({})
export class Controller {
}
```

**Comment by pkozlowski-opensource** [comment]
>  It turned out that there is a workaround (import "reflect-metadata";).

Reflect-metadata is a shim and as any other shim you shouldn't try to _import_ it but rather make sure that the corresponding file is included in a browser for a test runner (via `script` tag or otherwise).

This is the same mechanism as for any other shim - you just need to load them as soon as possible not import them.

**Comment by radek-holy** [comment]
@pkozlowski-opensource what about those "non-browser" test runners? I mean, in my case, the test runner is not running in a browser and I guess that Mocha or others aren't as well.

**Comment by pkozlowski-opensource** [comment]
> what about those "non-browser" test runners? I mean, in my case, the test runner is not running in a browser and I guess that Mocha or others aren't as well.

What is your testing environment then? In any case adding reference to reflect metadata doesn't differ from adding any other JS code for any other shim. This is not angular-specific.

**Comment by radek-holy** [comment]
@pkozlowski-opensource, I use Protractor, a command-line testing framework for Angular applications. Does it answer your question? I don't see any other way to include a file other than importing files from "spec" files.

**Comment by pkozlowski-opensource** [comment]
>  I use Protractor

But in this case reflect-metadata should be part of your application, not test, right? And protractor just tests an app that is loaded in a browser. 

Are you saying that you need reflect-metadata in your Protractor _tests_? This would be very strange.

I've got an impression that you are trying to use Protractor as a unit-test runner - a job that it wasn't designed for. If you need an example of a unit-testing setup with Karma have a look at https://github.com/juliemr/ng2-test-seed

**Comment by radek-holy** [comment]
OK, I'll report back in three days.

**Comment by radek-holy** [comment]
> But in this case reflect-metadata should be part of your application, not test, right? And protractor just tests an app that is loaded in a browser.

Yes, it *should*. And since Angular requires me to use class decorators, I believe that it should be part of Angular (and thus *transitively* part of my application).

> Are you saying that you need reflect-metadata in your Protractor tests? This would be very strange.

Yes, I do. Sorry, for not being clear. This is the workaround:
```diff
diff --git a/spec.ts b/spec.ts
index 9849109..adc4d08 100644
--- a/spec.ts
+++ b/spec.ts
@@ -1,4 +1,5 @@
 // spec.ts
+import "reflect-metadata";
 import * as controller from "../src/controller";
 
 describe("", () => {
```

> I've got an impression that you are trying to use Protractor as a unit-test runner - a job that it wasn't designed for. If you need an example of a unit-testing setup with Karma have a look at https://github.com/juliemr/ng2-test-seed

I cannot reproduce it with ng2-test-seed. Anyway, I've tried another test runner. Mocha is designed to run unit tests, right? With Mocha, I am able to reproduce it. Here is the reproducer:

```typescript
// src/controller.ts
import * as ng from "angular2/angular2";

@ng.Component({})
export class Controller {
}
```
```typescript
// test/spec.ts
import "reflect-metadata";
import * as controller from "../src/controller";

describe("", () => {
    it('', () => {
        let instance = new controller.Controller();
    });
});
```
```json
// package.json
{
  "dependencies": {
    "angular2": "^2.0.0-alpha.46"
  },
  "devDependencies": {
    "mocha": "^2.3.4",
    "typescript": "^1.6.2"
  }
}
```
```json
// tsconfig.json
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "noImplicitAny": true,
    "sourceMap": true,
    "target": "es5"
  },
  "exclude": [
    "node_modules"
  ]
}
```
```console
$ npm install
$ ./node_modules/.bin/tsc
$ ./node_modules/.bin/mocha
/tmp/unit/node_modules/angular2/src/core/util/decorators.js:157
    throw 'reflect-metadata shim is required when using class decorators';
    ^
reflect-metadata shim is required when using class decorators
```

This patch represents the workaround:
```diff
diff --git a/package.json b/package.json
index 5b618c3..af0eefc 100644
--- a/package.json
+++ b/package.json
@@ -4,6 +4,7 @@
   },
   "devDependencies": {
     "mocha": "^2.3.4",
+    "reflect-metadata": "^0.1.2",
     "typescript": "^1.6.2"
   }
 }
diff --git a/test/spec.ts b/test/spec.ts
index 84f264e..6b7f708 100644
--- a/test/spec.ts
+++ b/test/spec.ts
@@ -1,3 +1,4 @@
+import "reflect-metadata";
 import * as controller from "../src/controller";
 
 describe("", () => {
```

I guess, this issue deserves reopening. What do you think, @pkozlowski-opensource?

**Comment by VaJoy** [comment]
I have been thinking whether perhaps we can set the `reflect-metadata` as a loader in webpack conf?
I do NOT like to import this module each time I build a new App :(
