### ISSUE TITLE
Routes children not work 

### ISSUE THREAD

**Issue by troquatte** [angular/angular#53064]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

I'm trying to use child routes and it doesn't load the component.

```
export const routes: Routes = [
  {
    path: 'first-component',
    component: FirstComponent, 
    children: [
      {
        path: 'child-a', 
        component: ChildAComponent, 
      },
    ],
  },
];
```

### Please provide a link to a minimal reproduction of the bug

https://angular.dev/guide/routing/common-router-tasks

### Please provide the environment you discovered this bug in (run `ng version`)

17.0.0

**Comment by jnizet** [comment]
You probably forgot to add the `<router-outlet />` element in the template of FirstComponent (and to add the RouterOutlet directive to the `imports` of FirstComponent).

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by troquatte** [comment]
> You probably forgot to add the `<router-outlet />` element in the template of FirstComponent (and to add the RouterOutlet directive to the `imports` of FirstComponent).

@jnizet  It really seems like a bug to me, I added everything you said.

Thank you very much.

**Comment by jnizet** [comment]
@troquatte post a question on stackoverflow or elsewhere. I think the thousands of applications where child routes are used would have noted such a bug.
