### ISSUE TITLE
Incorrect link in angular.dev's Control flow page

### ISSUE THREAD

**Issue by racz16** [angular/angular#53075]
### Describe the problem that you experienced

In angular.dev, in the **In-depth Guides** / **Template Syntax** / **Control flow** page, the `developer preview` link, in the `IMPORTANT` box has the wrong URL.

### Enter the URL of the topic with the problem

https://angular.dev/guide/templates/control-flow

### Describe what you want to experience that would fix the problem

Link to an existing page.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/19560859/19e43743-d33a-4136-901c-609edf50904e)
After clicking:
![image](https://github.com/angular/angular/assets/19560859/4b543c27-2e3a-4d93-9f1c-e11df23839e7)

**Comment by JeanMeche** [comment]
Hi, this has been fixed by #52693 and is pending deployment on our side !
