### ISSUE TITLE
router: navigateByUrl doesn't navigate by relative URL

### ISSUE THREAD

**Issue by Necroskillz** [angular/angular#5307]
The documentation on `navigateByUrl` states following:

```
   * If the given URL begins with a `/`, router will navigate absolutely.
   * If the given URL does not begin with `/`, the router will navigate relative to this component.
```

Since this method in the child router just delegates to the root router, the relative part cannot work (as far as I tested it).

On the other hand `recognize` is executed on the child router, but you can't use the instruction to navigate, because again `navigateByInstruction` delegates to the root router (right now it seems `recognize` generates instructions from the child down, not from root).

/cc @btford

**Comment by btford** [comment]
Oops. This is a mistake in the docs.

> On the other hand recognize is executed on the child router, but you can't use the instruction to navigate, because again navigateByInstruction delegates to the root router (right now it seems recognize generates instructions from the child down, not from root).

Yes you can. An instruction always includes the full component hierarchy. Have you tried, or is this just an assumption from looking at the code?

**Comment by Necroskillz** [comment]
Only the root router `recognize` returns full hierarchy. See http://plnkr.co/edit/aa1ln4TT6y3T7GRfSwpX?p=preview (console output when you click on the links).

If `navigateByUrl` should only navigate by absolute url, then `recognize` should also be delegated to the root router.

**Comment by btford** [comment]
yep, you're right. that's a problem.

**Comment by jimbasilio** [comment]
Any plans on fixing this issue?

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router robust.

It doesn't look like the issue makes sense in the context of the new router. If you think it does, please reopen the issue.
