### ISSUE TITLE
Router generates url with NULL

### ISSUE THREAD

**Issue by cajoy** [angular/angular#5308]
I have following router configuration:

```
@RouteConfig([
    { path: '/', as: 'HomeController', component: HomeController },
    { path: '/perks', as: 'PerksPlannerController', component: PerksPlannerController }
])
```

and template:

```
                <ul class="uk-navbar-nav uk-hidden-small">
                    <li>
                        <a [router-link]="['/HomeController']">Terminal Unlock</a>
                    </li>
                    <li>
                        <a [router-link]="['/PerksPlannerController']">Level up planner</a>
                    </li>
                </ul>
```

As you see on following screenshot in status bar it generates route like http://falloutlab.com/null/perks

But actually when you click on it it shows right url in browser and redirects to right controller and generates correct data.

![issue](https://cloud.githubusercontent.com/assets/1035148/11183586/89d43932-8c40-11e5-8eed-a6b1d2728e47.png)

**Comment by ericmartinezr** [comment]
@cajoy see https://github.com/angular/angular/issues/5028, for now you could stick to `HashLocationStrategy` (that would add a `#`, ofc) if you prefer a `#` over a `null` :P

**Comment by cajoy** [comment]
HaslLocation is not the way I want go. But I may wait for fix. Thanks.

**Comment by valdirviana** [comment]
@cajoy are you solve this issue? How? Can you explain to me please? Thanks
