### ISSUE TITLE
[angular.dev] Algolia search is very bad (Ctrl+K)

### ISSUE THREAD

**Issue by anisabboud** [angular/angular#53088]
### Describe the problem that you experienced

Angular.dev is super awesome and pretty ✨

But the search function is completely useless/broken:
1. Search "NgModule" -> shows Selectors, even though there's an entire page on NgModules!
2. Search "Routing" -> shows Accessibility, even though there's an entire page on Routing!
3. Search "i18n" -> shows Hydration...
4. Search "Signals" -> shows Zone...
5. Search "standalone" -> shows Directive Composition API!
6. Search for "control flow" -> shows Testing
7. Search "@for" -> shows Authoring Schematics - a page without any "@for" at all, and doesn't show the 3 pages which talk about @for loop.

As you can see, searching for basic stuff doesn't work. 
Attaching screenshots for the 7 examples below. For each example a screenshot of the irrelevant search output, and screenshots of relevant pages that "should have been" returned.

I think the indexing is missing the page titles!
And Google search doesn't work on angular.dev either.

### Enter the URL of the topic with the problem

https://angular.dev/

### Describe what you were looking for in the documentation

Everything

### Describe the actions that led you to experience the problem

Ctrl+K

### Describe what you want to experience that would fix the problem

Algolia search should index page titles (and sidebar content) properly.

## Example 1: "NgModule"
![image](https://github.com/angular/angular/assets/5672108/78efaca2-cf54-416c-97e1-5d7a7e612e8c)
![image](https://github.com/angular/angular/assets/5672108/a36b1a7a-3ef5-4391-99a9-5a5b715a4f6d)

## Example 2: "Routing"
![image](https://github.com/angular/angular/assets/5672108/8243a04c-89f0-4063-873e-ade5d7c6208e)
![image](https://github.com/angular/angular/assets/5672108/b31811df-2d63-44bc-b9b5-4b6173e85b55)

## Example 3: "i18n"
![image](https://github.com/angular/angular/assets/5672108/85e50072-adf4-4e84-be47-b30427d54654)
![image](https://github.com/angular/angular/assets/5672108/3703c8e4-8de9-4663-92ca-580541c34294)

## Example 4: "signals"
![image](https://github.com/angular/angular/assets/5672108/33ec0660-0f77-41a1-b0ef-382c6030a630)
![image](https://github.com/angular/angular/assets/5672108/069d0df2-4fba-4c86-908e-82e936fa1551)

## Example 5: "standalone"
![image](https://github.com/angular/angular/assets/5672108/1cea64fc-eb0c-4cf2-88d4-003b7e99f834)
![image](https://github.com/angular/angular/assets/5672108/e43e73ad-3ec5-40ae-9714-bb0d17d4ceb3)
![image](https://github.com/angular/angular/assets/5672108/1e7d3d62-dd99-43d5-b239-5472f10791e4)
![image](https://github.com/angular/angular/assets/5672108/1dca7e0b-4588-4be9-a2a7-5ca6aaae094d)

## Example 6: "control flow"
![image](https://github.com/angular/angular/assets/5672108/b4e2a164-b420-44ab-a1a9-f20f154b9092)
![image](https://github.com/angular/angular/assets/5672108/4a72fd41-dda4-42f3-a195-89e982965875)
![image](https://github.com/angular/angular/assets/5672108/1d85aaa1-dc58-457b-97e0-ea406bc11c45)

## Example 7: "@for"
![image](https://github.com/angular/angular/assets/5672108/038bbd7d-c8bc-45e1-a932-d54c8cd7a5cf)
![image](https://github.com/angular/angular/assets/5672108/a83305ec-1489-485b-9789-124d208256a6)
![image](https://github.com/angular/angular/assets/5672108/28bfb2d8-fdee-49e0-be2a-618fcff08637)
![image](https://github.com/angular/angular/assets/5672108/14023df8-83ff-4a54-b879-ef836e653900)

**Comment by cloudinfra** [comment]
I am the founder of ExpertRec search and we use angular a lot.  I would be happy to offer our search for angular.dev.
please reach out to me at new@expertrec.com.  our search ranking is very easy to control and get the most relevant results.
https://www.expertrec.com/

**Comment by twerske** [comment]
Thank you for the feedback - we are collecting subjective feedback in an internal doc.

We are still working on improving the search indexing and can look at these examples to better improve the Algolia indexing in the future. Thanks!

**Comment by anisabboud** [comment]
This is not subjective feedback.

The search indexing seems to be missing page titles and main navigation, making it dysfunctional.

Go to angular.dev and try searching for basic stuff like NgModule, Routing, i18n, Signals, Standalone, Control flow, for.
