### ISSUE TITLE
Typo in Code: 'boostrapApplication' should be 'bootstrapApplication'

### ISSUE THREAD

**Issue by AntonioCait** [angular/angular#53094]
### Describe the problem that you experienced

I noticed a small misspelling in the code while learning about the HttpClient. The function boostrapApplication appears to be a typo and should be corrected to bootstrapApplication. Below is the corrected code:

```
bootstrapApplication(AppComponent, {providers: [
    provideHttpClient(),
  ]}).catch((err) => console.error(err));
```
The corrected function name is bootstrapApplication.
This typo could potentially lead to confusion and errors while working with the httpClient.

### Enter the URL of the topic with the problem

https://angular.dev/guide/http/setup

### Describe what you were looking for in the documentation

How to set up HttpClient

### Describe the actions that led you to experience the problem

Copying the code to my editor

**Comment by JoostK** [comment]
Thanks for the report! 👻 This was fixed in https://github.com/angular/angular/pull/52803 and pending deployment.
