### ISSUE TITLE
When we use formControlName in the <select tag> in reactive form then it behaves asynchronously.

### ISSUE THREAD

**Issue by ajaysingh-25** [angular/angular#53091]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

When we use formControlName in the <select tag> in reactive form then it behaves asynchronously. For example, I have used the reactive form and on the html side I have used the <select> and <option> tags. When I write selected in the option tag, it will not reflect on the browser, the dropdown remains empty, but when I remove the formControlName form the <select> tag, the default selected option value will reflect on the dropdown.
![image_2023_11_21T13_09_16_538Z]([](https://github.com/angular/angular/assets/81799657/b2a6705b-633f-470a-8f27-835f38ba24e7))

**Comment by ajaysingh-25** [comment]
[](https://github-production-user-asset-6210df.s3.amazonaws.com/81799657/284591535-621aecc4-87ac-4826-ba59-932c890a44d2.png)

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
