### ISSUE TITLE
Angular.dev home page scroll animation not working on linux machine with chrome

### ISSUE THREAD

**Issue by fleckc3** [angular/angular#53096]
### Describe the problem that you experienced

When I visit Angular.dev on chrome on my linux laptop I don't get any of the cool scroll animation and css. I can see this functionality when I use Firefox however. 

Chrome - Version 119.0.6045.123 (Official Build) (64-bit)
![image](https://github.com/angular/angular/assets/56199927/5279a57b-d695-4222-8fef-18fab112be56)

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/56199927/7e190644-213f-4918-b484-15f6fee9f396)
[Screenshare - 2023-11-21 5_17_26 PM.zip](https://github.com/angular/angular/files/13429289/Screenshare.-.2023-11-21.5_17_26.PM.zip)
[angular.dev-1700587288372.log](https://github.com/angular/angular/files/13429313/angular.dev-1700587288372.log)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Chrome - Version 119.0.6045.123 (Official Build) (64-bit)
![image](https://github.com/angular/angular/assets/56199927/5279a57b-d695-4222-8fef-18fab112be56)
```

**Comment by JoostK** [comment]
Is there any information in chrome://gpu/ that might shed some light on this? Can you download that report and share it here?

**Comment by fleckc3** [comment]
[about-gpu-2023-11-22T09-13-47-917Z.txt](https://github.com/angular/angular/files/13436469/about-gpu-2023-11-22T09-13-47-917Z.txt)

**Comment by JoostK** [comment]
Lots of hardware acceleration is disabled on this system, which likely explains why animations are not working. I suspect Chrome identifies that it is infeasible to run animations using the software renderer.

**Comment by fleckc3** [comment]
Ah ok makes sense, I'll try and fiddle with the hardware settings to see if I can get it working.

**Comment by JeanMeche** [comment]
Here is the related code btw 

https://github.com/angular/angular/blob/c62b2dae8c4653996969df992e8f88887e7c83c4/adev/src/app/features/home/home.component.ts#L76-L81
