### ISSUE TITLE
Extra closing parenthesis in code examples of Angular Signals

### ISSUE THREAD

**Issue by Gharantes** [angular/angular#53095]
### Describe the problem that you experienced

Happens thrice in "Injection Context". Doesn't cause any errors, but eh. 

Code-block example:

```ts
@Component({...})
export class EffectiveCounterCmp {
  readonly count = signal(0);
  constructor() {
    // Register a new effect.
    effect(() => {
      console.log(`The count is: ${this.count()})`);
    });
  }
}
```

The extra parenthesis is here:
```ts
console.log(`The count is: ${this.count()})`);
```

### Enter the URL of the topic with the problem

https://angular.io/guide/signals#injection-context

**Comment by Gharantes** [comment]
Seems like it happens at https://angular.dev/guide/signals#injection-context as well

**Comment by aramirezj** [comment]
Nice eye! I also saw a few backticks wrong, I did a PR for this issue ^^

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular/pull/53098
