### ISSUE TITLE
Angular/versions doesn't exists

### ISSUE THREAD

**Issue by budzichd** [angular/angular#53099]
### Describe the problem that you experienced

There is a text with link "See [Angular's version compatibility](https://angular.dev/versions) guide for more information." on the page https://angular.dev/tools/cli/setup-local.

Unfortunately, the page that is pointed inside the link is not found. (https://angular.dev/versions)
![image](https://github.com/angular/angular/assets/57658152/3c55e200-ec7a-48d6-8d52-55148822cfc7)

**Comment by JeanMeche** [comment]
Hi, this has been fixed by #52585 and is pending deployment !
