### ISSUE TITLE
Delayed ngModel Binding with es6-shim

### ISSUE THREAD

**Issue by SebastianStehle** [angular/angular#5310]
Hello,
I have a small application (https://github.com/SebastianStehle/BLS_Angular2) with angular 2.0 and some routes and a form on the first page.

    export class Home {
      public model = ModelFactory.createModel();
    }

I preselect some values which works fine on my machine. To reduce the requests count I use browserify for bundling. To include some additional modules I made a separate bootstrap-bundled.ts file and added the imports there:

    import 'zone.js';
    import 'es6-shim'
    import 'reflect-metadata';

    import './bootstrap';

But when I add es6-shim I have a very strange issues. I see the preselected values for my forms only after focusing the first input field. I also have some custom directives and recognized that the onChanges method is not called.

            <input type="text" required
                   [(ng-model)]="model.departure"/>

I have no short repro yet but you can test it with my code. Unfortunantly it needs asp.net vnext. You need to run before you run the kestrel server.

cd wwwroot
npm install

cd..
npm install
gulp install
gulp scripts:rebuild
gulp styles:rebuild

**Comment by SebastianStehle** [comment]
It work when I add import 'es6-shim' to the top. Very strange nevertheless.

**Comment by pkozlowski-opensource** [comment]
@SebastianStehle you should _not_ try to bundle / import shims (zone, reflect, es6) - those scripts are doing all kind of crazy things that might interfere with module packagers / loaders.

Just stick those in a `<script>`  tag. You might concatenate those files, just don't use bundlers. BTW, we are going to provide a bundle with all 3rd party deps needed by ng2, see #5223

Closing this one as we are going to have bundles you are looking for through #5223. At the same time we can't investigate each and every setup and every developer could have.
