### ISSUE TITLE
broken url found on tutorials/learn-angular/updating-the-component-class

### ISSUE THREAD

**Issue by anthonychavis** [angular/angular#53105]
### Describe the problem that you experienced

On page https://angular.dev/tutorials/learn-angular/updating-the-component-class, within "1 Add a property called city" there is an _anchor element_ wrapping the text "type inference in TypeScript" that has an invalid _href_ value.

When clicking "type inference in TypeScript" I expected to go to a page containing information about type inference in typescript. However, the page that opened was https://angular.dev/typescript.org/type-inference, which is a 404.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/updating-the-component-class#add-a-property-called-city

### Describe what you were looking for in the documentation

I was going through the "Learn Angular in your browser via the Playground" tutorial. 

When clicking "type inference in TypeScript" I expected to go to a page containing information about type inference in typescript.

### Describe the actions that led you to experience the problem

To reproduce the problem:

- navigate to https://angular.dev/tutorials/learn-angular/updating-the-component-class
- scroll to the "1 Add a property called city" section
- click "type inference in TypeScript" found in the paragraph following the example code
- the resulting page is https://angular.dev/typescript.org/type-inference

### Describe what you want to experience that would fix the problem

When clicking "type inference in TypeScript" I expected to go to a page containing information about type inference in typescript.

Possible fix:

- change the _href_ value of the anchor tag to https://www.typescriptlang.org/docs/handbook/type-inference.html#handbook-content, or
- if it should route to a page within the project, adjust the path to reflect the desired page
- currently the _href_ value is "_typescript.org/type-inference_"

### If this problem caused an exception or error, please paste it here

```true
related console messages:


The resource https://angular.dev/assets/textures/gradient.jpg was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

```
/typescript.org/type-inference:1 The resource https://angular.dev/assets/textures/gradient.jpg was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```
```


### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

**Comment by anthonychavis** [comment]
handled
https://github.com/angular/angular/pull/52714
https://github.com/angular/angular/commit/cb5c6fc53027327b5b0b78962dc9afb690c6b894

**Comment by JoostK** [comment]
Thanks for the report, closing per the above.
