### ISSUE TITLE
Broken link to  Angular's version compatibility

### ISSUE THREAD

**Issue by csnsw-igor** [angular/angular#53108]
### Describe the problem that you experienced

Clicked on link : [Angular's version compatibility](https://angular.dev/versions) got:

Page Not Found 🙃
If you think this is a mistake, please [open an issue](https://github.com/angular/angular/issues/new?template=3-docs-bug.yaml) so we can fix it.

### Enter the URL of the topic with the problem

https://angular.dev/tools/cli/setup-local

**Comment by sasidharansd** [comment]
Fixed with PR: https://github.com/angular/angular/pull/52585. Issue can be closed.

**Comment by JoostK** [comment]
Thanks for the report, closing per the above.
