### ISSUE TITLE
Search/filter documentation with a query param

### ISSUE THREAD

**Issue by tjlav5** [angular/angular#53123]
### Describe the problem that you experienced

I have a custom site-search macro wired up in chrome for [angular.io](http://angular.io/), where I can type ng in the omnibar and search angular docs for whatever. The site-search maps to `https://angular.io/api?query=%s`. With the new site though, it doesn't seem like there is a URL that actually maps to search? It seems to all be backed by algolia in a fetch. 99% of my use case would be covered if the input field here mapped to a query param 🙏

![image](https://github.com/angular/angular/assets/1452216/c430d0de-901b-48ee-8e65-ca317d97b5fa)

### Enter the URL of the topic with the problem

https://angular.dev/api

**Comment by JeanMeche** [comment]
Hi, this is being adressed by #52979
