### ISSUE TITLE
Track Dart bundle size

### ISSUE THREAD

**Issue by kegluneq** [angular/angular#5312]
See https://github.com/angular/angular/pull/5294 for pointers

**Comment by IgorMinar** [comment]
- [ ] we should replicate the internal hello world project
- [ ] run that in a separate travis job
- [ ] add analytics
- [ ] consider implementing (in a follow up PR) a mechanism that would compare the current payload size with current master size and fail the build if more than X%. this will require storing the master payload size somewhere which complicates the matters. maybe we could use firebase for this?

**Comment by yjbanov** [comment]
+1 on @IgorMinar's proposals. I think it's reasonable to cap incremental increases. We still need the absolute <100kb gzipped and <300kb minified caps, as that's our SLA for internal customers, and also without them no matter what incremental percentage we choose it is still exponential.

**Comment by mark1010** [comment]
https://github.com/angular/angular/issues/5311 Duplicate Output may be related. I see the same issue in the js build, and some level of duplication in the generated js, which may be impacting code size.

**Comment by ochafik** [comment]
Note: no need to store the build size anywhere, you could just checkout the master branch (or the previous commit if `$TRAVIS_BRANCH == "master" `)

(then just build all the playground examples, find the outputs and print their gzipped size into some json, do this once again for the branch's version and compare with a tiny node.js script)
