### ISSUE TITLE
Singleton Services with Standalone Component

### ISSUE THREAD

**Issue by ManjuRSree** [angular/angular#53120]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Singleton services seems to be working different in Standalone components when compared to normal components imported in a module. This is in continuation of the issue: https://github.com/angular/angular/issues/48242

* If a Standalone component imports a module that has a service added in its providers array, then instead of using the existing singleton instance it creates a new instance of the service. This is contrary to the behavior of a normal module where even if we import a module that has a service added in its providers array, the existing singleton instance is injected into it.
* If a component has two or more standalone components, one of which imports a module with the service in the providers array and the other does not, then, automatically the one without the import also uses the new service instance instead of using the global singleton instance. 

Any help to understand how services behave differently in Standalone components when compared to a normal module would be much appreciated.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-h2fwrj

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Tested with angular 14.2
```

**Comment by JoostK** [comment]
This is working as designed and [documented here](https://angular.io/guide/standalone-components#standalone-injectors).
