### ISSUE TITLE
wrong typescript docs url in angular.dev guide.

### ISSUE THREAD

**Issue by DimitriTsikaridze** [angular/angular#53137]
### Describe the problem that you experienced

in angular dev tutorial at this [section](https://angular.dev/tutorials/learn-angular/updating-the-component-class) there is wrong anchor href tag '**type inference in TypeScript.**' that points to "typescript.org/type-interface"which doesn't exist. correct link would be "https://www.typescriptlang.org/docs/handbook/type-inference.html" this, with https:// in front because in current version there isn't even that so it tries to load "https://angular.dev/typescript.org/type-inference"

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/updating-the-component-class

**Comment by JeanMeche** [comment]
Hi, this has been fixed by #52714 and is pending deployment on our side !
