### ISSUE TITLE
Page Not Found: https://angular.dev/cli/commands

### ISSUE THREAD

**Issue by OszkarOlah** [angular/angular#53132]
### Describe the problem that you experienced

Page Not Found
https://angular.dev/cli/commands

### Enter the URL of the topic with the problem

https://angular.dev/cli/commands

**Comment by saiprasad2595** [comment]
Hi @OszkarOlah How did you get that URL? Did you click on any hyperlink which navigated to that URL?

I think the right URL is [](https://angular.dev/cli)

**Comment by JoostK** [comment]
Thanks for the report, closing as duplicate of #52549.

**Comment by OszkarOlah** [comment]
Hi,

From this page:
https://angular.dev/tools/cli

[image: image.png]
