### ISSUE TITLE
NpmPackageBin aio/src/generated/ngsw-config.json failed: build-runfiles.exe failed

### ISSUE THREAD

**Issue by recruitment-developer** [angular/angular#53131]
### Describe the problem that you experienced

When I am trying  yarn start-local angular.io docs
getting an error
![Screenshot (48)](https://github.com/angular/angular/assets/124894786/749890b5-2080-4a16-b939-35a601086f9f)
is there any solution for this issue

**Comment by JeanMeche** [comment]
Hi, which command did you run ?

**Comment by recruitment-developer** [comment]
yarn start-local

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
