### ISSUE TITLE
Dart: add starting app size test

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#5314]
We should measure the size of minified and minified+gzipped 'hello world' app and make sure the sizes meet our targets (<90kb gzipped, <300kb minified). This is in response to a recent regression we introduced and didn't notice until the code made it to customers.

**Comment by kegluneq** [comment]
Similar: https://github.com/angular/angular/issues/5312

**Comment by kegluneq** [comment]
fyi, I believe the size is currently ~105K, so our initial limit will need to be above the targets, but we can shrink them down as we improve.
