### ISSUE TITLE
ngModel in hidden input causes app stuck

### ISSUE THREAD

**Issue by kochetkovSergeY** [angular/angular#53145]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

We are migrating from angular 7 to angular 15 and saw this problem  "ngModel in hidden input causes app stuck"

    <input type="hidden" [ngModel]="getValueAsModel()" #model="ngModel" [required]="isRequired()">

### Please provide a link to a minimal reproduction of the bug

we have promise that resolves model from backend when it setting value this construction stucks

    <input type="hidden" [ngModel]="getValueAsModel()" #model="ngModel" [required]="isRequired()">

### Please provide the exception or error you saw

```true
No exception, it stcuks...
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.10
Node: 14.21.1
Package Manager: npm 6.14.17
OS: windows x64

Angular: 15.2.10
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
  "@angular-devkit/build-angular": "15.2.10",
  "@angular/cli": "15.2.10",
  "@angular/compiler-cli": "15.2.10",
  "@angular/platform-server": "15.2.10",
  "typescript": "4.9.5",
  "zone.js": "0.14.2"
  "rxjs": "7.8.1",
```

**Comment by JeanMeche** [comment]
Hi, could you provide a reproduction on stackblitz ?

**Comment by kochetkovSergeY** [comment]
I'll try

**Comment by dev-niiaddy** [comment]
I

**Comment by kochetkovSergeY** [comment]
I can't reproduce it in simple example, it's occusrs in heavy production app, simple example works fine, but problem exists and we already removed this construction from our code and page start working fine

**Comment by pkozlowski-opensource** [comment]
@kochetkovSergeY it is next to impossible for us to progress on this issue without a reproduction scenario. Please open a new issue when you manage to reproduce in isolation.
