### ISSUE TITLE
Outdated link in AOT documentation on both angular.dev and angular.io

### ISSUE THREAD

**Issue by Gurran** [angular/angular#53146]
### Describe the problem that you experienced

![image](https://github.com/angular/angular/assets/42462633/45a0837c-f5af-454a-9fa3-61bfef8b4fc9)
Link to schema https://github.com/angular/angular/blob/main/packages/compiler-cli/src/metadata/schema.ts
is outdated

### Enter the URL of the topic with the problem

https://angular.dev/tools/cli/aot-compiler#metadata-restrictions

### Describe what you were looking for in the documentation

Looking for the file the link points to

### Describe the actions that led you to experience the problem

Read the documentation

### Describe what you want to experience that would fix the problem

A working link

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/42462633/a5ff2cf3-eb00-4ade-b115-f627a755ae57)

**Comment by TECHMONSTER21** [comment]
I assume this is the correct link?

https://github.com/angular/angular/blob/main/packages/core/src/metadata/schema.ts

Can anybody confirm?

**Comment by davideTheCap** [comment]
As mentioned in the PR comment [here](https://github.com/angular/angular/pull/53158#issuecomment-1826348296) I guess this issue is also obsolete

**Comment by Gurran** [comment]
Should the file not be removed from the angular.dev site? If it is outdated why still show it, especially on the new docs site.
