### ISSUE TITLE
[Angular.dev] Missing page for control-flow migration

### ISSUE THREAD

**Issue by anisabboud** [angular/angular#53147]
### Describe the problem that you experienced

There should be a page on https://angular.dev/reference/migrations -> https://angular.dev/reference/migrations/control-flow mentioning the `ng generate @angular/core:control-flow` migration mentioned in the [blog post](https://blog.angular.io/introducing-angular-v17-4d7033312e4b).

**Comment by santoshyadavdev** [comment]
HI Team, let me know if I can take this up?

**Comment by pkozlowski-opensource** [comment]
This was fixed in #53375 (than you @santoshyadavdev!) and docs are live at https://angular.dev/reference/migrations/control-flow
