### ISSUE TITLE
"Making requests" page in new documentation does not work

### ISSUE THREAD

**Issue by ZakharKholboev** [angular/angular#53140]
### Describe the problem that you experienced

1. Go to [https://angular.dev/guide/http](https://angular.dev/guide/http)
2. Click on "Making HTTP Requests" button in the "What's next" section
3. See the result: Page not found

### Add a screenshot if that helps illustrate the problem

![NG_docs_error](https://github.com/angular/angular/assets/47420653/b6ef39fe-5f2f-453b-813f-b6cefd3c0ef1)

**Comment by JoostK** [comment]
Thanks for the report! This is a duplicate of https://github.com/angular/angular/issues/52542.
