### ISSUE TITLE
CSS property can not be appended/set using Renderer2 

### ISSUE THREAD

**Issue by DevJaGz** [angular/angular#53142]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Why the Renderer2 does not work to set a CSS property?. I use the following line of code to try to modify the value of the CSS property:

```typescript
this._renderer.setStyle(this.caret, '--_duration', `${this.duration}ms`);
```

On the other hand, when I manipulate the DOM directly it works, look:
```typescript
  this.caret.style.setProperty('--_duration', `${this.duration}ms`);
```

However, based on the Angular documentation, it is not a good practice to manipulate the DOM directly.

Below, I provide you a replicate of the bug using a simple example of rotating a Caret Icon. The logic is shown in a component to make it easier, however, all the logic must be in a Directive, with the creation logic of the Caret as a child HTML element where the directive is applied.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-wleffp?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
NA
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
{
  "name": "stackblitz-starters-wleffp",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "@angular/animations": "^17.0.4",
    "@angular/common": "^17.0.4",
    "@angular/compiler": "^17.0.4",
    "@angular/core": "^17.0.4",
    "@angular/forms": "^17.0.4",
    "@angular/platform-browser": "^17.0.4",
    "@angular/router": "^17.0.4",
    "rxjs": "^7.8.1",
    "tslib": "^2.6.2",
    "zone.js": "^0.14.2"
  },
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.4",
    "@angular/cli": "~11.0.4",
    "@angular/compiler-cli": "~11.0.4",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}
```

**Comment by JeanMeche** [comment]
You need to pass `RendererStyleFlags2.Dashcase` because of the leading dashed. 

`this._renderer.setStyle(this.caret, '--_duration', `${this.duration}ms`, RendererStyleFlags2.DashCase);`

**Comment by DevJaGz** [comment]
> RendererStyleFlags2

Thanks you so much! @JeanMeche it works!
