### ISSUE TITLE
ResolveFn Examples not displaying as intended

### ISSUE THREAD

**Issue by RobinMeow** [angular/angular#53141]
### Describe the problem that you experienced

Pretty sure these examples are supposed to be code snippets. 

### Enter the URL of the topic with the problem

https://angular.dev/api/router/ResolveFn?tab=description

### Describe what you were looking for in the documentation

code snippets

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/111490292/d31c6387-d655-44bc-b835-7e6c06dd6474)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
I was using Google Chrome to view the website
```

**Comment by JeanMeche** [comment]
I'm closing this as we are tracking this issue in #52663
