### ISSUE TITLE
Elements removed from DOM using @for and SSR

### ISSUE THREAD

**Issue by davidjohanssson** [angular/angular#53163]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Elements are removed from the DOM when they are reordered using the Material DragDropModule.

It seems like this issue only occurs when using the new `@for` syntax in conjunction with SSR enabled.

So, if I use `*ngFor` or disable SSR this issue does not occur.

The reordering example is the same as on the official docs: https://material.angular.io/cdk/drag-drop/overview#reordering-lists

There's no error in the console.

https://github.com/angular/angular/assets/24542784/732cf74d-e221-48cc-88e9-bc5bf5028268

### Please provide a link to a minimal reproduction of the bug

[DragDropBug](https://github.com/davidjohanssson/drag-drop-bug)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.3
Node: 20.9.0
Package Manager: npm 10.1.0
OS: win32 x64

Angular: 17.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.3
@angular-devkit/build-angular   17.0.3
@angular-devkit/core            17.0.3
@angular-devkit/schematics      17.0.3
@angular/cdk                    17.0.1
@angular/cli                    17.0.3
@angular/material               17.0.1
@angular/ssr                    17.0.3
@schematics/angular             17.0.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JeanMeche** [comment]
Could you share a repro on a github ? 
I did reuse the same example on a `ng new --ssr` project and couldn't reproduce that issue.

**Comment by davidjohanssson** [comment]
@JeanMeche Here's a reproduction, https://github.com/davidjohanssson/drag-drop-bug
