### ISSUE TITLE
Async redirectTo in router

### ISSUE THREAD

**Issue by rosendi** [angular/angular#5316]
**Overview:**

Now `redirectTo` can be only a string. It would be great if it could be a `Promise` as well.

**Example:**

Common scenario. The app has two routes called `items/new` as `New` and `items/:id` as `Show`. With the async redirection the home route could redirect to `New` if items hasn't been created yet or it could redirect to the first item of asynchronously fetched items.

**Comment by btford** [comment]
See also #4170

**Comment by rosendi** [comment]
I'm not sure but should `redirectTo` and `loader` allow to use DI same as `CanActivate`? https://github.com/angular/angular/issues/4112

```
@RouteConfig([
  { ...loader: (service: Service) => },
  { ...redirectTo: (service: Service) => }
])

**Comment by btford** [comment]
@rosendi maybe, but that's another issue. I'd be open to discussing if you file a separate issue.

I consider this original issue resolved. Please see the changes in #4170 for more details. Thanks!

**Comment by rosendi** [comment]
@btford Sorry... I'm late. I'll look into. Thank you!
