### ISSUE TITLE
need a way to globally import components when using standalone component

### ISSUE THREAD

**Issue by dricercar** [angular/angular#53161]
### Description

need a way to globally import components when using standalone component.
before standalone component, we can create a shared module and import it in the root module.
but now when using standalone components, it is necessary to import many module like CommonModule and FormsModule in each standalone component.

### Proposed solution

importProvidersFrom([FormsModule, CommonModule) to import components globally

### Alternatives considered

or supply another api like importProvidersFrom to import components globally

**Comment by JeanMeche** [comment]
Hi, this has been discussed in #51297. 
Standalone components were design to have explicit dependencies
