### ISSUE TITLE
Broken link in the docs

### ISSUE THREAD

**Issue by jorgeperezlara** [angular/angular#53164]
### Describe the problem that you experienced

In the page for "Optimizing images", there's a link for more information on LCP optimization that is linked to _https://web.dev/articles/optimize-lcp)]_.

This link should instead be _https://web.dev/articles/optimize-lcp_.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/optimizing-images

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Firefox 120 on Fedora 39.
```

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52580 and is pending deployement on ourside !
