### ISSUE TITLE
https://angular.dev/api/core/NgComponentOutlet getting page not found

### ISSUE THREAD

**Issue by rkvpratapreddy** [angular/angular#53166]
### Describe the problem that you experienced

When I click on NgComponentOutlet link from https://angular.dev/guide/components/programmatic-rendering (the link is "See the NgComponentOutlet API reference for more information on the directive's capabilities.")

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/programmatic-rendering

### Describe what you were looking for in the documentation

Need to provide correct link for it.

![image](https://github.com/angular/angular/assets/24549971/cc70b119-686c-466a-9c7a-44d35c748135)

**Comment by JoostK** [comment]
Thanks for the report, this was addressed in https://github.com/angular/angular/pull/52829
