### ISSUE TITLE
UI Loading twice when using SSR with default angular 17 app 

### ISSUE THREAD

**Issue by amitdixit** [angular/angular#53162]
### Which @angular/* package(s) are the source of the bug?

core, platform-browser, platform-server

### Is this a regression?

No

### Description

1. Created a new angular 17 app (my-app) with all default
2. npm run build
3. npm run "serve:ssr:my-app"

Code attached for reference
The UI show show the component twice along with CSS rendered as plain text on the UI.

![image](https://github.com/angular/angular/assets/33697366/86f0de7e-9880-413a-a899-6a0b195064cd)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 17
```
[app.zip](https://github.com/angular/angular/files/13463208/app.zip)

**Comment by amitdixit** [comment]
[app.zip](https://github.com/angular/angular/files/13463207/app.zip)

**Comment by amitdixit** [comment]
Fixed it, I passed **provideHttpClient(withFetch())** in app.config.server.ts

**Comment by stanislavromanov** [comment]
What if the project is updated and is still using modules? HTTP Client is just provided as a module import in that case. Changed nothing in my case.

Do you guys even test things before deploying? This seems such a trivial oversight, literally new base project does not work.

**Comment by JeanMeche** [comment]
I cannot reproduce this issue on a Node18 nor on a Node20 environment. 
Can you share more about your config ?

**Comment by amitdixit** [comment]
code shared in my issue

**Comment by amitdixit** [comment]
> I cannot reproduce this issue on a Node18 nor on a Node20 environment. Can you share more about your config ?
code shared in my issue
[app.zip](https://github.com/angular/angular/files/13464451/app.zip)

**Comment by JeanMeche** [comment]
That's the code I tried it with. This does not reproduce the issue consistantly.

**Comment by amitdixit** [comment]
> That's the code I tried it with. This does not reproduce the issue consistently.

Consistently ? does it means the same code is always running fine at your end?

**Comment by JeanMeche** [comment]
Yes, your project runs fine. 
This is why I'm looking for more infos from your environment. Can you run `ng version` ?

**Comment by amitdixit** [comment]
> Yes, your project runs fine. This is why I'm looking for more infos from your environment. Can you run `ng version` ?

![image](https://github.com/angular/angular/assets/33697366/6d4b19ba-0e7e-4ea1-aeb9-e2edf85aaf5a)

 node -v
v18.18.0

tsc -v
Version 5.3.2

**Comment by JeanMeche** [comment]
And what is your browser ?

**Comment by amitdixit** [comment]
> And what is your browser ?

Chrome

**Comment by amitdixit** [comment]
I don't know what was the issue, I created another application , Bravo it rendered correctly.

**Comment by amitdixit** [comment]
> I have the same problem, but it isn't consistent. Sometimes it renders fine, other times it is duplicated. I haven't found a pattern.

Yes you are right. That's why I had closed the issue since its not consistent.
