### ISSUE TITLE
Docs - HTTP Client Request redirects to incorrect url

### ISSUE THREAD

**Issue by Klobbix** [angular/angular#53177]
### Describe the problem that you experienced

While on this URL and clicking 'Making HTTP Requests' at the bottom: https://angular.dev/guide/http

It navigates to https://angular.dev/guide/http/making-requets, when it should be
https://angular.dev/guide/http/making-reque**s**ts

### Enter the URL of the topic with the problem

https://angular.dev/guide/http

### Provide any additional information here in as much as detail as you can

```true
Update the link to point to the correct page.
```

**Comment by JeanMeche** [comment]
Hi, thank you for reporting this issue. This issue has been fixed in #52541 and is pending deployment on our side.
