### ISSUE TITLE
Router wildcard/catch-all as component input parameter 

### ISSUE THREAD

**Issue by alexcibotari** [angular/angular#53179]
### Description

As a developer, I have a route with a wildcard path, and I would like to read path parameters as array

```ts
 {
    path: '**',
    component: MainComponent,
  }
```

### Proposed solution

Catch those catch-all path use cases

Configuration :
```ts
 {
    path: ':slugs**',
    component: MainComponent,
  }
```
Component :
```ts

  @Input({required: true})
  readonly slugs: string = '';

or

  @Input({required: true})
  readonly slugs: string[] = [];

```

### Alternatives considered

Read from `ActivatedRoute.path`

**Comment by atscott** [comment]
This is possible with a resolver: https://stackblitz.com/edit/stackblitz-starters-4xdnp7

Closing since this request is covered by existing APIs.
