### ISSUE TITLE
Angular.dev first-app hello-world typo

### ISSUE THREAD

**Issue by BitFlippa27** [angular/angular#53170]
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x]  The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ]  Tests for the changes have been added (for bug fixes / features)
- [x]  Docs have been added / updated (for bug fixes / features)

## PR Type

- [ ]  Bugfix
- [ ]  Feature
- [ ]  Code style update (formatting, local variables)
- [ ]  Refactoring (no functional changes, no api changes)
- [ ]  Build related changes
- [ ]  CI related changes
- [x]  Documentation content changes
- [ ]  angular.io application / infrastructure changes
- [ ]  Other... Please describe:

## What is the current behavior?
There is a  typo in the first-app hello-world tutorial at the 3rd step at 2.1.3
![typo](https://github.com/angular/angular/assets/32537389/07d6f1c0-18e8-462b-8126-843a203a3f9e)

## What is the new behavior?
start should be starts

## Does this PR introduce a breaking change?

- [x] No 
- [ ] Yes 

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app/hello-world

**Comment by bencodezen** [comment]
This PR was merged into the repository by commit https://github.com/angular/angular/commit/186190990dd03715a1a61e878d56e1e023b3a518.
