### ISSUE TITLE
Angular signals can not notify the consumers when used inside asynchronous operators like (setTimeout, Promise)

### ISSUE THREAD

**Issue by usmanmustafa33** [angular/angular#53181]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Angular signals can not notify the consumers when used inside asynchronous operators like (setTimeout, Promise)

![carbon (3)](https://github.com/angular/angular/assets/15308039/e5998020-ce3c-487e-8ac0-995dacb3f331)

![Screenshot 2023-11-26 at 18 42 25](https://github.com/angular/angular/assets/15308039/cae15421-12bb-426e-9c13-b9fe3d2710e5)

The reason that it's not working is the way angular is handling `activeConsumer`which you can find here 
https://github.com/angular/angular/blob/main/packages/core/primitives/signals/src/graph.ts#L19

is this intrinsic design limitation, which has already known?
maybe this should be mentioned in the [signals angular docs](https://angular.dev/guide/signals), signal should not be used inside   asynchronous operators like (setTimeout, Promise) , which I already have shown in the stackblitz example 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-cmalh8?file=src%2Fmain.ts

**Comment by JoostK** [comment]
This is expected behavior. The code that reads the signals is not executing in the context of an `effect`, it was only spawned from one. Unlike zone.js which attempts to retain the active zone across async boundaries, `effect` does not have the same behavior.
