### ISSUE TITLE
make ctrl-click, cmd-click or middle-button-click open new tab on routerLink

### ISSUE THREAD

**Issue by yelhouti** [angular/angular#53183]
### Description

As explained by others before me including @wiegell  in #39936 , web users are often using ctrl+click or middle click on links and buttons to try to open the links in a new tab. 
This works great on a-tags but doesn't work on buttons, cards...

### Proposed solution

make onClick in routerLink use window.open with target: `_blank` if middle click or ctrl/cmd is used.
As @wiegell suggested, this behavior can enabled using a config in the router and won't break what users expect, after all if you are using ctrl+click you are clearly expecting something different from just a click.

### Alternatives considered

- Wrap `<button>` in `<a>`:  breaks keyboard navigation (button click using space only possible after the second tab) breaks screen readers.
- style `<a>` as buttons: breaks keyboard navigation with `space` to click button, breaks css :enabled.

**Comment by Sushant-Kat0ch** [comment]
Hi can you put me on this issue

**Comment by JeanMeche** [comment]
This is the intended behaviour. Please have a look at #39936
