### ISSUE TITLE
Angular 2 "routerInjectables" not found

### ISSUE THREAD

**Issue by EgyTechnology** [angular/angular#5319]
Hello I'm new in Angular 2 and I trying to create application that's support routing.
I Using ASP.NET 5 as base framework for my application and I have been attache and setup all files that's I think I need.
That's how my setup look like:
![capture](https://cloud.githubusercontent.com/assets/6942742/11194579/94015bf4-8cb5-11e5-98f1-a8f80f8472b5.PNG)
I have been get debug error said 
"Build: Module '"C:/Users/EgyTe/documents/visual studio 2015/Projects/TypescriptAndAgnular2/src/TypescriptAndAgnular2/node_modules/angular2/router"' has no exported member 'routerInjectables'."
And That's is code where I face the error:
![capture1](https://cloud.githubusercontent.com/assets/6942742/11194702/4ab1e8c8-8cb6-11e5-87c2-c9984ebaf2d7.PNG)

**Comment by PascalPrecht** [comment]
What version of Angular 2 are you using?

`routerInjectables` are now `ROUTER_PROVIDERS`

**Comment by EgyTechnology** [comment]
I use last version alpha  44

**Comment by PascalPrecht** [comment]
Okay, then try `ROUTER_PROVIDERS`

**Comment by pkozlowski-opensource** [comment]
> I use last version alpha 44

Actually the latest, as of time of writing, is alpha 46

**Comment by PascalPrecht** [comment]
@EgyTechnology can you verify so we can close this?

**Comment by EgyTechnology** [comment]
I have been trying ```ROUTER_PROVIDERS```.
But i get error list say: 
![capture2](https://cloud.githubusercontent.com/assets/6942742/11206017/e0526368-8d14-11e5-97ee-21cb167c8f5e.PNG)
This code that I use:
App.ts:
```typescript
///<reference path="../../typings/angular2/angular2.d.ts"/>

import {bootstrap, Component, View, bind} from 'angular2/angular2';
import {
ROUTER_DIRECTIVES,
ROUTER_PROVIDERS,
RouteConfig
} from 'angular2/router';

import { HomeComponent } from './Home/home';

@Component({
    selector: 'app',
    directives: [ROUTER_DIRECTIVES]
})

    @View({
        template: '<router-outlet></router-outlet>'
})

@RouteConfig([
    { path: '/Home', component: HomeComponent }
])

class AppComponent { }
bootstrap(AppComponent, [ROUTER_PROVIDERS]);
```

Home.ts:
```typescript
///<reference path="../../typings/angular2/angular2.d.ts"/>

import {Component, View, bootstrap} from 'angular2/angular2';

@Component({
    selector: 'home'
})
@View({
    template: 'Hello'
})
export class HomeComponent { }

//bootstrap(HomeComponent);
```

Files structure: 
![capture4](https://cloud.githubusercontent.com/assets/6942742/11206117/aa9cfb24-8d15-11e5-84e5-6f15f50514ea.PNG)

**Comment by ericmartinezr** [comment]
@EgyTechnology you should put angular related scripts below systemjs and typescript. Also remove traceur.

**Comment by EgyTechnology** [comment]
@ericmartinezr I have been did what you say but I get message 404 on "home" script
```GET http://localhost:5000/Scripts/home 404 (Not Found) - Systemjs```

**Comment by PascalPrecht** [comment]
@EgyTechnology I think we're kind of getting into support questions here. The original issue is solved by changes `routerInjectables` to `ROUTER_PROVIDERS`.

You should checkout http://gitter.im/angular/angular to ask these kind of questions! :)

Can we close this?

**Comment by EgyTechnology** [comment]
I hop you not upset from me Mr @PascalPrecht because i'm new with this kind of stuff.
I want to thank you and Mr @ericmartinezr for help me.
Thanks again

**Comment by PascalPrecht** [comment]
@EgyTechnology oh, not at all! I hope I didn't give you that feeling
