### ISSUE TITLE
Router.navigate resolves before component inputs are bound when using withComponentInputBinding

### ISSUE THREAD

**Issue by Erbenos** [angular/angular#53195]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I would assume that router with withComponentInputBinding should make it so that router.navigate blocks until those inputs are bound and ngOnChanges gets run with the them.

It seems however that current behavior is NOT waiting for the hooks. Is this intended or a bug?

expected:

router.navigate called
component gets its ngOnChanges ran
router.navigate resolves

actual:

router.navigate called
router.navigate resolves
component gets its ngOnChanges ran

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-ayscsz?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
No error.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Copied from stackblitz:

@angular/animations
17.0.4

@angular/common
17.0.4

@angular/compiler
17.0.4

@angular/core
17.0.4

@angular/forms
17.0.4

@angular/platform-browser
17.0.4

@angular/router
17.0.4

rxjs
7.8.1

tslib
2.6.2

zone.js
0.14.2
```

**Comment by atscott** [comment]
Correct, this is and always has been the timing of the navigation promise resolve. This is unrelated to component input bindings. The promise resolves immediately after outlets are activated and deactivated. 

Angular has not (and really still doesn’t) have a mechanism to wait for the next change detection before doing something so this is technically not entirely possible without manually calling ApplicatiomRef.tick. 

NavigationEnd has the same timing - it emits before change detection and therefore before components have fully rendered.

**Comment by Erbenos** [comment]
To make sure I understand, when the logic is as follows:

- component A sources an entity through the input binding
- component A initializes a process which results in navigation to self which causes the entity to be re-resolved
- component A wants to continue such process with the input prop assumed to be changes.

If I understand correctly I can just force the change detection to run via appRef.tick right after the navigation promise has been resolved to "re-run" the lifecycle hooks (cause they run only when the change detection happens) - since they are all synchronous, it would guarantee the desired order of execution even though the actual:

actual:

router.navigate called
router.navigate resolves
component gets its ngOnChanges ran

will still hold

**Comment by Erbenos** [comment]
I tested it and it works for the stackblitz case and such, hence this can be closed thank you.

For my real-world scenario however things aren't so simple, as the navigation also goes through a redirect - which one of the underlying route guards does via navigate instead of by a way of creating a url tree - because I need to pass "state" (see NavigationExtras).

When redirecting via navigate, the follow up appRef.tick does not ensure the lifecycle hook gets called. When redirecting via urlTree, it does make sure that the lifecycle hook gets called. Related #27148 . Will need to find other workaround :/

**Comment by Erbenos** [comment]
Seems like something I should be able to construct some less hacky solution from than what I currently have in place. Thank you.
