### ISSUE TITLE
Code snippets are not selectable

### ISSUE THREAD

**Issue by fadamakis** [angular/angular#53192]
### Describe the problem that you experienced

Text inside the code element is not selectable by the user. For example selecting `npm install -g @angular/cli` [here](https://angular.dev/tutorials/first-app#install-the-latest-version-of-angular) is not possible.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app#install-the-latest-version-of-angular

**Comment by OBe95** [comment]
This is related to the pseudo-element used to display the background on `code` elements
I pushed a suggestion to fix it

**Comment by OBe95** [comment]
I believe @JeanMeche's PR is a better fix (closing mine), you should maybe apply to the other 2 similar css blocks
