### ISSUE TITLE
Drop ng- prefix from all angular directives and rename NgRepeat to Foreach

### ISSUE THREAD

**Issue by mhevery** [angular/angular#532]
- [ ] `NgRepeat` => `Foreach`
- [ ] `NgSwitch` => `Switch`
- [ ] `NgIf` => `If`

**Comment by gdi2290** [comment]
+1

**Comment by gkalpak** [comment]
I am kind of late to the party, but I am curious: What is the reasoning behind this change ?
Is there a public explanation/discussion somewhere (github issue/forum/google doc) ?

**Comment by cburgdorf** [comment]
I'm also interested in the reasoning behind this change. Isn't it that if we drop the `ng-`  prefix we are less future proof? What if in html6 they decide to come up with a native `if` attribute?

//cc @PascalPrecht

**Comment by mhevery** [comment]
There is no value in having `NgIf` since ES6 has proper import statements. There is a separate debate to be had if we should prefix the `ng-if` attribute in HTML. Given that each component has its own directive registry, I think it would be unlikely that we would have collision. I think a better solution would be to allow specifying prefix during the directive import. #868.
