### ISSUE TITLE
Form: action request is not sent using action attribute

### ISSUE THREAD

**Issue by VPusher** [angular/angular#5320]
Hello,

I'm trying to make a simple login form works with an `action` attribute. The issue here is the request to `/login` is never sent. Copying and pasting the form HTML in the DOM using the dev tools make it works.

This was working in alpha 39. Then, I moved to alpha 46 breaking this sample.

```typescript
@View({
  template: `
      <form class="ui large form" action="/login" method="post" (submit)="onSubmit()">
        <div class="ui segment">
          <div class="field">
            <div class="ui left icon input">
              <i class="user icon"></i>
              <input type="text" id="personalNumber" name="personalNumber" placeholder="Personal Number" pattern="[0-9]*" required autofocus>
            </div>
          </div>
          <div class="field">
            <div class="ui left icon input">
              <i class="lock icon"></i>
              <input type="password" id="password" name="password" placeholder="Password" required>
            </div>
          </div>
          <button type="submit" [class.loading]="loading" class="ui fluid large primary button">Login</button>
        </div>
      </form>
  `
})
```

I guess angular is catching the request somewhere or prevent the default behavior of the form...
The thing is that I initially avoid to use angular stuff (NgForm, NgFormControl, NgFormModel, ..) to build my form because of this issue. Now, my workaround is broken. 

Any idea ?

**Comment by mhevery** [comment]
You can not have `action` and `(submit)` on the same form. `(submit)` will prevent the form from submitting if it does not return `false`

**Comment by VPusher** [comment]
Even without `(submit)`, the action request is not sent.

**Comment by VPusher** [comment]
@mhevery, here is a sample illustrating the issue: http://plnkr.co/edit/F3w0nmIVLrD29KWrX4SM?p=preview
