### ISSUE TITLE
Investigate using zones to avoid the need for injectAsync

### ISSUE THREAD

**Issue by juliemr** [angular/angular#5322]
Can we just always use zones, and remove the need for `injectAsync` at all? (everything would be `inject`)

**Comment by nosachamos** [comment]
This would be really awesome, thanks @juliemr !

**Comment by mhevery** [comment]
@juliemr I don't think I understand you proposal here. Could you provide more background?

**Comment by juliemr** [comment]
@mhevery instead of having the user specify `inject` or `injectAsync` and return a promise in the latter case, we could wrap each test case in a zone and declare it complete when all asynchronous tasks are done. PR #5375 implements a first version of this.

This would be for the public testing library for the moment.

**Comment by jesperronn** [comment]
Can this be closed now that #5375 and 0c9596ae2b31135711fba1d132f8e5d349a1e095 landed?

**Comment by juliemr** [comment]
Yup.
