### ISSUE TITLE
Multiple broken links in Page "https://angular.dev/guide/http/testing"

### ISSUE THREAD

**Issue by JulienWDev** [angular/angular#53227]
### Describe the problem that you experienced

In the section "Setup for testing", broken links to "provideHttpClientTesting" and "HttpTestingController".

### Enter the URL of the topic with the problem

https://angular.dev/guide/http/testing#setup-for-testing

### Describe what you were looking for in the documentation

The doc for HttpTestingController.

### Add a screenshot if that helps illustrate the problem

![Issue-AngularDoc](https://github.com/angular/angular/assets/2076505/940598d6-a2aa-44b4-b39f-1561d0567030)

![PageNotFound](https://github.com/angular/angular/assets/2076505/961bf7d6-fbf1-42f4-9a0e-fb294e1463fa)

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this, we tracking this issue at #52663
