### ISSUE TITLE
Component not watch for object properties

### ISSUE THREAD

**Issue by cajoy** [angular/angular#5325]
I have component what injects simple object with some properties.
So the issue I see is change listeners. onChange event never fired when injected object property changes.

But if I set interval - I can get changed object properties.

The question: is it bug? or expected behavior. if expected then how to make component to listen for object property changes?

Component:
```ts
export class PerksPlannerComponent {
    playerModel: CurrentPlayerModel;

    constructor(@Inject(CurrentPlayerModel) currentPlayerModel: CurrentPlayerModel) {
        this.playerModel  = currentPlayerModel;

//        setInterval(() => this.isCurrentModelChanged(), 2000);
    }

    isCurrentModelChanged() {
        console.log(this.currentPlayerModel.someValue);
    }

    onChanges(data) {
        console.log(data);
    }
}
```

Simple Object:
```ts
@Injectable()

export class CurrentPlayerModel {
    someValue:string;

    constructor(modelData?: any) {
        if (modelData) {
            this.someValue = modelData.someValue;
        }
    }
}
```

**Comment by gionkunz** [comment]
The `OnChanges` lifecycle hook will be called if input properties of your component change, not arbitrary properties on your component. This lifecycle was designed to specifically address `@Input` bindings. Also, what binding do you create in your view? That's not visible in your example. If you're binding to `{{curentPlayerModel.someValue}}` then you need to change the value of this property within the player model. Angular does change detection by using reference checks, so if you're referencing a complex object in `someValue`, you might want to switch to a more immutable way of modifying your data (changing your object references / creating copies on changes).

Check this example too see that angular does only react on changes that change object references. http://plnkr.co/edit/Kci8NlGFzr8wR6h8CirG?p=preview

**Comment by pkozlowski-opensource** [comment]
@cajoy as @gionkunz pointed out there is no direct equivalent of ng1 `$watch` functionality where you can observe anything. It is hard to provide you with a proper solution in ng2 since you are not exposing your (functional) use-case.

In any case general support questions should be directed to an appropriate support channel (we want to keep GitHub for bug reports / feature requests). I would suggest starting discussion on https://gitter.im/angular/angular

**Comment by cajoy** [comment]
The idea is to have shared user information between controllers and different services. This user information may contain some specific data what might be altered by different components, and then processed (without view changes) by others.

I can implement this features by

1) using simple event emitters and listeners,
2) or create component in bootstrap file and inject it in each route like 
```
 <a [router-link]="['/SomeController', {user: User}]">Manage Breweries</a>
```
3) using hidden widgets <some-widget [(user)]="user">

but all of that is just workarounds compare to simple watch or observe implementation.

In future I am going to use gitter for discussions
