### ISSUE TITLE
Difference between Detached and Checked change detection strategy

### ISSUE THREAD

**Issue by gionkunz** [angular/angular#5326]
The documentation says that a component set to `Checked` will remain so until set to `CheckOnce` where it will fall back to `Checked` after it was checked again I guess.

What process is setting the component into `CheckOnce` state again? Is it even possible that this happens automatically?

Also, depending on the answer to this question, whats the difference of switching between `Checked` and `CheckOnce` or switching between `Detached` and `CheckOnce`.

Thanks for your time to answer this question for me. I'm happy to make a pull request with some extended documentation for the `ChangeDetectionStrategy.ts` file if you help me understand this better.

**Comment by mhevery** [comment]
your component will programmatically say `CheckOnce` to let the system know that the component is dirty and needs rendering.
