### ISSUE TITLE
Angular attempts to subscribe to Event stream more than once

### ISSUE THREAD

**Issue by typotter** [angular/angular#5327]
In a simple component with an Output as follows:

    @Output() final trigger = new LazyEventEmitter<String>();

This error is thrown:
"Bad state: Stream has already been listened to."

Under the hood, the component uses a LazyEventEmitter (which is just a wrapper of Stream/Stream Controller), but it is __not broadcast__. Changing the controller to instantiate a broadcast stream fixes this, but up until now, we have been able to expect only one subscription from Angular framework.

    @Output() final trigger = new LazyEventEmitter<String>.broadcast();

**Comment by typotter** [comment]
Figured this out, but maybe a worthwhile thing to check in the framework:

We had the output both annotated (@Output), and in the @Component annotation list (i.e. outputs: [ ... ]).

**Comment by ericmartinezr** [comment]
@typotter see https://github.com/angular/angular/issues/4798

**Comment by typotter** [comment]
Thanks @ericmartinezr 
Duplicate of #4798
