### ISSUE TITLE
Wrong link to NgComponentOutlet API

### ISSUE THREAD

**Issue by HymanZHAN** [angular/angular#53275]
### Describe the problem that you experienced

Wrong link:

> See the [NgComponentOutlet API reference](https://angular.dev/api/core/NgComponentOutlet) for more information on the directive's capabilities.

Should be:

> See the [NgComponentOutlet API reference](https://angular.dev/api/common/NgComponentOutlet) for more information on the directive's capabilities.

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/programmatic-rendering#using-ngcomponentoutlet

**Comment by srinathsree66** [comment]
Hi, this this was addressed in #52829

**Comment by sasidharansd** [comment]
Hi @JoostK, think we can close this one as it is a duplicate of https://github.com/angular/angular/issues/52828 and it is completed.

**Comment by JoostK** [comment]
@sasidharansd Thanks!
