### ISSUE TITLE
docs: Wrong template string placeholder delimiter

### ISSUE THREAD

**Issue by kabrunko-dev** [angular/angular#53280]
### Describe the problem that you experienced

I've been studying the new Angular.dev documentation and I spotted a syntax error at a template string in the "**Component**" section. Currently the delimiter is parenthesis and not curly braces.

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/inputs#type-checking

### Add a screenshot if that helps illustrate the problem

![syntax-error](https://github.com/angular/angular/assets/142346548/ae3bf6a5-8524-4095-8980-6593c216eddb)

**Comment by Jad31** [comment]
Hi, I would like to help on this one

**Comment by Vishal-Yadav-001** [comment]
Hi, @kabrunko-dev 
I think we can replace ( ) with { } to make it a valid template string.
I wish to help on this, Please assing this fix to me.
Thanks

**Comment by srinathsree66** [comment]
Hi, this was addressed in #53286  and  merged into the repository by commit https://github.com/angular/angular/commit/1e3bcfecbab260fb66a1ac50e77192bb98cc0f3e
