### ISSUE TITLE
API tab is not tall enough

### ISSUE THREAD

**Issue by e-oz** [angular/angular#53294]
### Describe the problem that you experienced

Only part of the API is rendered, and this area is non-scrollable:
<img width="1133" alt="Screenshot 2023-11-30 at 20 55 31" src="https://github.com/angular/angular/assets/526352/7d0e7885-8b98-4026-baf6-fdb9471796e8">

### Enter the URL of the topic with the problem

https://angular.dev/api/forms/FormGroup?tab=api

### Describe the actions that led you to experience the problem

Try to find `statusChanges()` description in the API tab.

**Comment by tieppt** [comment]
I doubt this change will have an impact on other places.

<img width="1541" alt="image" src="https://github.com/angular/angular/assets/7151365/29d0b485-c5d3-45d8-9eab-48c29f1e2a1c">
