### ISSUE TITLE
Create ExceptionService

### ISSUE THREAD

**Issue by mhevery** [angular/angular#533]
- [ ] Create `ExceptionHandler` Service (See https://docs.angulardart.org/#angular/angular-core.ExceptionHandler)
- [ ] Fix this todo: https://github.com/angular/angular/blob/master/modules/core/src/life_cycle/life_cycle.js#L17

**Comment by pkozlowski-opensource** [comment]
The actual link to the mentioned TODO: https://github.com/angular/angular/blob/92afad6ebcb7d375bfffdd9c72017d6438351035/modules/angular2/src/core/life_cycle/life_cycle.js#L18
