### ISSUE TITLE
feat(router): Provide child routes access to parent route information

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#5330]
When using nested routes, I would like to set params at the top level and be able to access those params or other information in the child routes instead of adding the same params/data in each of the child routes. 

```js
@RouteConfig([
    { path: '/users/:id/...', component: Users, as: 'Users' }
])
class App {
}

@RouteConfig([
    { path: '/', component: Profile, as: 'Profile' },
    { path: '/stats', component: Stats, as: 'Stats' }
])
class Users {
    constructor(params: RouteParams) {
        // need access to Users ID route param
        this.id = params.parent.get('id');
    }
}
```

Plunk displays how its handled today.

http://plnkr.co/edit/v1Np3niVn3WNTZBvHQLf?p=preview

**Comment by rosendi** [comment]
I think this may be useful angular/angular#4452

**Comment by brandonroberts** [comment]
Thanks. For your example you could use your store to glue your components together

http://plnkr.co/edit/Ch7Uxxuz29RDqMNe6dkk?p=preview

**Comment by rosendi** [comment]
Thanks. My example is a special case of more complex generic data store that I currently use. But, yep the temporary solution uses another helper service to track the app state.

**Comment by brandonroberts** [comment]
@btford are there any plans for handling this use case?

**Comment by rosendi** [comment]
@btford I have the same question. It would be great to know...

**Comment by rosendi** [comment]
Why does `SkipSelf() params: RouteParams` not work?

**Comment by koodikindral** [comment]
+1

**Comment by brandonroberts** [comment]
This can be achieved by traversing up the injector. Closing this one for now.

Example: http://plnkr.co/edit/MsZc2bcUXgAABBzK8C0c?p=preview

**Comment by rosendi** [comment]
@brandonroberts Can you please comment on your plunk? I can't understand how it solves the issue (access parent params in the child components).

**Comment by brandonroberts** [comment]
@rosendi Sure. As I understand it, each component gets its own "injector" and it has a parent injector leading all the way up to the top of the injector hierarchy. I injected the child component's injector, which has a reference to its parent injector. I had to traverse back up the injector's parent twice since there are multiple injectors between the parent and the child route components. Once I have a reference to the parent route's injector, it will get me access to its RouteParams. 

Here is what I believe the injector tree looks like from where I was.

* Parent route
  * Element Injector (injector.parent.parent) (Parent RouteParams available here)
  * Proto Injector (injector.parent)
    * Child Route
      * Element Injector (Child RouteParams available here)

I'm sure this would only get longer once you add more nested routes, but for this example I was only one level deeper.

Someone can clarify if I misspoke.

**Comment by rosendi** [comment]
@brandonroberts Thank you! Are you sure that the link (http://plnkr.co/edit/MsZc2bcUXgAABBzK8C0c?p=preview) to the plunk is correct? There is nothing about injector. And why this way the `SkipSelf() params: RouteParams` approach doesn't work? It should also query a dependency from the parent injector. Sorry, apparently I missed something.

**Comment by gionkunz** [comment]
@brandonroberts why did you close this issue? Are you satisfied with injecting the injector and traversing manually? I think that's not a sufficient solution. The router tree is coexisting with the component tree and this solution does require me to mix both trees together. I think it would be much nicer if the `RouteParams` object would have a parent property that refers to the `RouteParams` object of the next higher configured component. This way I only need to reflect the route configuration tree but not the component tree.

**Comment by gionkunz** [comment]
So currently I see the following solutions:
- Inject the parent component and obtain the route parameters stored on the parent component. This will closely couple my component to the parent component, which might not be the best thing.
- Inject the injector and travers up until I found the injector that might contain the RouteParams im looking for. This solution is closely coupled to the component tree structure and as I might change that, I also need to make changes to the way how I find the params.

Both approaches are not really ideal and having a parent property on the route params object would be very nice. For the second approach above I could come up with something like this:

```javascript
getAllRouteParams(injector) {
    let params = null;
    while(injector) {
      const routeParams = injector.getOptional(RouteParams);
      if (routeParams) {
        if (params === null) {
          params = {};
        } else {
          params = Object.create(params);
        }

        Object.assign(params, routeParams.params);
      }
      injector = injector.parent;
    }
    return params;
  }
```

This would at least decopule me from the component / injector tree and provide hierarchy of prototypes that are shadowing possible parameter name overlaps.

**Comment by brandonroberts** [comment]
@gionkunz No, ultimately I'm not satisfied with the solution. I would like to have a `parent` with `RouteParams` also, but I think it couples the components together too much. The route components shouldn't have explicit knowledge of who their parent is, which is why I think most of that logic is in the router. 

Your second approach would would work well also. You would run into problems if you have routes with the same parameter names like a parent route with `path: '/parent/:id/...'` and a child route with `path: '/child/:id'` though. Maybe do the same thing you're doing, but build your own `parent` into your params object as your traversing up the injector tree.

**Comment by gionkunz** [comment]
Well, you can do params.__proto__.id if you're running into shadowing problems

**Comment by brandonroberts** [comment]
Another option if you don't want to get the injector involved is to subscribe to the root router, get the full instruction for the route and traverse down the instruction children and get all the params also. I think that's closer to what you want as far as not coupling to the injector/component tree and using the router tree.

```js
// Singleton service for storing router information
@Injectable()
export class RouterState {
  _current: Instruction;
  _last: Instruction;
  
  constructor(public router: Router) {
    // subscribe to router url updates
    router.subscribe((url) => {
      // convert the current url into an instruction
      this._getInstruction(url);
    });
  }
  
  getAllParams() {
    let params = {};
    let instruction = this.router._currentInstruction;
    
    while (instruction) {
      Object.assign(params, instruction.component.params);
      
      instruction = instruction.child;
    }

    return params;
  }
  
  private _getInstruction(url) {
    this.router.recognize(url).then((ins) => {
      if (ins) {
        // Store the current route instruction
        this._last = this._current;
        this._current = ins;
      }
    });
  }
  
  current() {
    // return current instruction
    return this._current;
  }
  
  last() {
    // return last instruction
    return this._last;
  }
}

```

**Comment by gionkunz** [comment]
Good stuff :+1: Although, still a workaround :-)
