### ISSUE TITLE
Making HTTP request documentation page not found

### ISSUE THREAD

**Issue by Wilson-Barbosa** [angular/angular#53302]
### Describe the problem that you experienced

I was reading throughout the Angular Documentation and the page that should display information on how to make HTTP requests in the http guide was deemed not found. Maybe it's because of the new version and the documentations that are being updated, but i wished to post it here, since it's quite the important topic. This is my first issue like this, sorry if I did a poor job explaining it!

### Enter the URL of the topic with the problem

https://angular.dev/guide/http/making-requets

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/133286305/5d90a8a2-9878-4670-8db6-c3b1f83669ba)

**Comment by tieppt** [comment]
Comment from another issue:
> This issue has been fixed in #52541 and is pending deployment on our side.

https://github.com/angular/angular/issues/53177#issuecomment-1826824001
