### ISSUE TITLE
ng build for angular ssr projects create redundant index.html file for every router link

### ISSUE THREAD

**Issue by mpricu** [angular/angular#53320]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I created an angular ssr project with the latest 17.0.5 version. I created some components and some routes for those components. 
When I run the ng build command the resulted "dist/browser" directory contained directories for every route (even for the load-lazy routes).
Inside each directory there was an index.html file identical with the index.html file from the main directory "dist/browser".
I think these files are redundant.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.5
Node: 18.18.0
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 17.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.5
@angular-devkit/build-angular   17.0.5
@angular-devkit/core            17.0.5
@angular-devkit/schematics      17.0.5
@schematics/angular             17.0.5
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by mpricu** [comment]
I created a public repository to reproduce the issue:
https://github.com/mpricu/angular-17-ssr

**Comment by JeanMeche** [comment]
You have the `prerender` option set to `true`. This is expected, since you're prerendering every page of your app.
