### ISSUE TITLE
Promise returning function with AsyncPipe in expression binding template

### ISSUE THREAD

**Issue by leonelvsc** [angular/angular#53323]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Could a template expression binding statement that contains a function call that returns a `new Promise` each time bounded to an AsyncPipe be detected by the expression evaluator and throttle down that expression call avoiding crashes or infinite loops? Of course, emitting console warnings or errors in such cases

https://github.com/angular/angular/blob/acd6100960a17e5425f3895883bc91f1499ecb28/packages/compiler/src/output/output_ast.ts#L1246

https://github.com/angular/angular/blob/acd6100960a17e5425f3895883bc91f1499ecb28/packages/compiler/src/template/pipeline/src/instruction.ts#L317

I know that Angular is working as expected here as each function call returns a new reference. 

### Proposed solution

At least if the expression contains an `AsyncPipe`, it somehow should alert the evaluator that the expression contains a PromiseStrategy somehow injecting the ExpressionContext or similar (I don't know about the internals of Angular )

If we can detect that at some point the expression returned a new Promise reference at that point we could throttle down the expression evaluation

### Alternatives considered

none

**Comment by alxhub** [comment]
This is tricky / not feasible to detect as a bug: there are many _legitimate_ cases where an expression changes frequently when evaluated. Cases where a `new Promise` is returned on every evaluation already result in `ExpressionChangedAfterItHasBeenChecked` (although this may be masked by `OnPush` components).

**Comment by leonelvsc** [comment]
I see, well I saw some expressions like `biding="newPromiseEveryTime() | async"`  killing the browser I suppose because every time it's evaluated it triggers a new detection cycle or by pushing every time to the microtaskQueue it results in a never-ending never draining queue. 
I don't know if wrapping the resolve in a setTimeout(fn, 0) will avoid this crash ( if pushing always to the microtaskQueue is the cause ).

But anyway thanks for answering Alex @alxhub

**Comment by alxhub** [comment]
The right solution is to not create a new promise on every evaluation of the template - don't call `newPromiseEveryTime()` from the template.

**Comment by leonelvsc** [comment]
Yes of course I know, it just makes some noise for devs starting to use Angular between the support of promises from `AsyncPipe` they go ahead without knowing the side effects of the expression but i know it's intended **and correct** behaviour.

Sorry for the trouble and thank you again
