### ISSUE TITLE
Allow conditionally applying directive to component

### ISSUE THREAD

**Issue by matgray** [angular/angular#5332]
Currently, there is no way to conditionally apply a directive to a component.  

I need to apply the ng-form-control directive only if there is a control present, and the template ends up looking like:

```
<some-component
    *ng-if="control != null"
  [...]
    [ng-form-control]="control"
  [...]>
</some-component>
<some-component
    *ng-if="control == null"
   [...]>
</some-component>
```

It would be nice if the directive wasn't applied when `control` was null to prevent duplicated code.

**Comment by pkozlowski-opensource** [comment]
> It would be nice if the directive wasn't applied when control was null to prevent duplicated code.

What would be a proposed syntax here? 

Please keep in ind that we are trying to know as much as possible about directives that are active in a given template so we can do perf optimizations and enable better tooling.

**Comment by astec** [comment]
How about 
```
[ng-form-control]?="control"
```

**Comment by mhevery** [comment]
I think the way we plan to support this is that directive is always applied, but it becomes inactive if there is no secondary directive present. 

It is too specialized to have its own syntax.
