### ISSUE TITLE
Error in Angular tutorial Lesson 3?

### ISSUE THREAD

**Issue by GoSpursGoNL** [angular/angular#53336]
### Describe the problem that you experienced

I'm completely new to learning Angular, so I'm following the online tutorial.
Lesson 1 and 2 went smooth.
Lesson 3 fails for me at step 2.3 

There it says:
```
imports: [
  CommonModule,
  HousingLocationComponent
],
```
If I do that, VSC reports 'Cannot find name 'CommonModule'.ts(2304)'

If instead I do:
```
imports: [
    HousingLocationComponent
],
```
Then it works fine and I can make it to lesson 4.
Is there an error in the tutorial, or am I doing something wrong?

### Enter the URL of the topic with the problem

https://angular.io/tutorial/first-app/first-app-lesson-03#step-2---add-the-new-component-to-your-apps-layout

**Comment by GoSpursGoNL** [comment]
In lesson 4 at some point you are instructed to verify the contents of home.component.ts
It is supposed to have:
`import { CommonModule } from '@angular/common';`

Then I would have expected that step to be part of lesson 2, where you create that home.component.ts ?
https://angular.io/tutorial/first-app/first-app-lesson-02

But that is not mentioned. Was that line supposed to be generated automatically when home.component.ts was generated through
`ng generate component home --inline-template --skip-tests`

For me that was not the case.

**Comment by JoostK** [comment]
If I run

> ng generate component home --inline-template --skip-tests

In the StackBlitz starter (mentioned at the top of Lesson 1), I do get `imports: [CommonModule]` present in `src/app/home/home.component.ts`

**Comment by GoSpursGoNL** [comment]
Ah! That then also explains the error message at the first step of lesson 1 actually.
You are instructed to download the starting code zip, extract, and run npm install in the IDE in the right folder.

That fails with:
`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: angular.io-example@0.0.0
npm ERR! Found: @angular/common@17.0.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"17.0.0" from the root project
npm ERR! `

**Comment by JeanMeche** [comment]
We're planning to deprecate angular.io in favor of https://angular.dev. 

Feel free to open an issue for any issue you might encounter on the new doc site.
