### ISSUE TITLE
Http: doesn't work in a worker

### ISSUE THREAD

**Issue by robwormald** [angular/angular#5333]
It's pulling some imports directly from angular/angular2. Figure out how to best avoid this.

**Comment by pkozlowski-opensource** [comment]
> It's pulling some imports directly from angular/angular2. Figure out how to best avoid this.

IMO this is part of the bigger questions on how to share code between core and other bundles. There should be just one place for "public" exports from core on which http / router / others can depend.

**Comment by jteplitz602** [comment]
We're in the process of reworking import paths so that nothing imports from `angular2/angular2` and code is more portable (#4834). Now that dom render is not in core I believe `angular2/core` is WebWorker safe. I'll take a look and try to fix the http imports.

**Comment by robwormald** [comment]
@jteplitz602 cool. This mostly my fault as i'm importing directly from angular2/angular2, so assuming the worker bundle includes angular2/core, that should sort it.

**Comment by jteplitz602** [comment]
@robwormald ah, I see. Yeah, the new worker bundle will include all of angular2/core.

**Comment by jteplitz602** [comment]
@robwormald I believe this is closed now, can you double check?

**Comment by robwormald** [comment]
:+1:
