### ISSUE TITLE
Angular v17 Vite not serving server.ts on development even when ssr: true

### ISSUE THREAD

**Issue by alexandresebrao** [angular/angular#53347]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I'm migrating from Webpack to Vite, but I got stucked with SSR and server.ts

On my angular.json i set this.

 ```
"development": {
              "buildOptimizer": false,
              "optimization": false,
              "extractLicenses": false,
              "sourceMap": true,
              "ssr": true,
              "namedChunks": true
            }
```

but ng serve is not using server.ts as development so I can't make request to custom endpoints that I need to execute on my project, any help is really appreciated!

### Please provide the environment you discovered this bug in (run `ng version`)

Angular: 17.0.4
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

**Comment by JeanMeche** [comment]
Hi, 
This issue is tracked on the CLI repo : angular/angular-cli#26323
