### ISSUE TITLE
router-link-active not working for nested routes

### ISSUE THREAD

**Issue by choeller** [angular/angular#5334]
When working with nested routes, all links to routes under a common root-path get the router-link-active class. E.g having two links like this:
```
<li>
    <a [router-link]="['/Tasks', 'List']" class="link">Task Overview</a>
</li>
<li>
     <a [router-link]="['/Tasks', 'NewTask']" class="link">New Task</a>
</li>
```

navigating to "#/tasks/lists" results in the following DOM:

```
<li _ngcontent-sno-1="">
      <a class="link router-link-active" _ngcontent-sno-1="" href="#/tasks/list">Task Overview</a>
</li>
    
<li _ngcontent-sno-1="">
     <a class="link router-link-active" _ngcontent-sno-1="" href="#/tasks/new">New Task</a>
</li>
```

**Comment by choeller** [comment]
So here is a plnkr demonstrating the behaviour: http://plnkr.co/edit/wAzoCIWB23KQLGWw1EGB?p=preview

**Comment by zoechi** [comment]
I think this can be closed. This router is deprecated and this works differently in the new router.

**Comment by choeller** [comment]
Yeah, as of https://github.com/angular/vladivostok/issues/24 there might be a new solution for this, so I'll close this one...

**Comment by cchapman900** [comment]
I had a similar issue where my `routerLinkActive` wasn't being activated because I had my `routerLink` as `/projects/{{project?._id}}` in which case the project was originally starting as null.

I wrapped everything in a `<div *ngIf="project">` and removed the `?` and not it's working correctly.
