### ISSUE TITLE
Feature Request for New Control Flow Syntax: @include, @input in Angular Templates

### ISSUE THREAD

**Issue by ferhado** [angular/angular#53352]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler-cli, compiler, core

### Description

The new Control Flow in Angular enhances template management, but it lacks a direct way to include external HTML files with scope binding. An `@include` feature, like `@include('./example.html', item)`, would enable including 'example.html' in the template, using the local `item` variable.

### Proposed solution

Introduce an `@include` directive in Angular:

```html
@include('./example.html', {item: someItem, item2: otherItem})
```

In 'example.html', use an `@input(){}` block to bind to `item`:

```html
@input(item) {
  <h1>{{ item.title }}</h1>
  <p>{{ item.description}}</p>
}

@input(item2) {
  <h1>{{ item2.title }}</h1>
  <p>{{ item2.description}}</p>
}
```

This allows directly including HTML content with scope binding, without creating a full component.

### Alternatives considered

The current method involves creating full components for reusable sections. This can be overkill for simple template parts, leading to unnecessary complexity.

**Comment by pkozlowski-opensource** [comment]
This is essentially a request for a lighter-weight component authoring format. While it is true that the new control flow _syntax_ gives us more options, the changes to the component authoring needs much more thinking. Those changes are part of our roadmap so I'm going to close this issue as there is nothing immediately actionable for us here.
