### ISSUE TITLE
docs : (fix) Broken Markdown Link References in bootstrapping.md File

### ISSUE THREAD

**Issue by VishalPawar1010** [angular/angular#53365]
### Describe the problem that you experienced

While going through documentation in adev :  https://github.com/angular/angular/blob/main/adev/src/content/guide/ngmodules/bootstrapping.md file. There are several broken Markdown Link References in files (e.g. Angular CLI, components, directives).
Also code snippets visualisation need to be updated.

### Enter the URL of the topic with the problem

https://github.com/angular/angular/blob/main/tools/cli does not points to Angular CLI readme file

### Describe what you were looking for in the documentation

Looking/navigating through reference markdown documents in folder: https://github.com/angular/angular/tree/main/adev/src/content/guide

### Describe the actions that led you to experience the problem

Click on any .md document references

### Describe what you want to experience that would fix the problem

Please update all the broken references or add required file if it's not there. 

### Add a screenshot if that helps illustrate the problem

![Screenshot from 2023-12-05 20-30-20](https://github.com/angular/angular/assets/118156462/857d0105-5804-451b-8277-c931ada50825)

### If this problem caused an exception or error, please paste it here

```true
404 - page not found
The main branch of angular does not contain the path tools/cli.
```
```


### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
NA
```

**Comment by JoostK** [comment]
The documentation pages are authored to be read on angular.dev, not from Github.

**Comment by VishalPawar1010** [comment]
Thank you for clarification @JoostK . Closing the issue.
