### ISSUE TITLE
misspelling

### ISSUE THREAD

**Issue by ChristianJSd** [angular/angular#53364]
### Describe the problem that you experienced

description for router-outlet tag inaccurate

### Enter the URL of the topic with the problem

https://angular.io/api/router/RouterOutlet#description

### Describe what you were looking for in the documentation

Description
Each outlet can have a unique name, determined by the optional name attribute. The name cannot be set or changed dynamically. If not set, default value is "primary".

**Comment by sasidharansd** [comment]
Hey @ChristianJSd , can you explain more on what's inaccurate ?

**Comment by JeanMeche** [comment]
Without any futher details, I'm closing this.
