### ISSUE TITLE
Pressing the escape button in Angular makes the website hangs for two seconds

### ISSUE THREAD

**Issue by Alhajras** [angular/angular#53367]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I am using Angular 15 and PrimeNG, I have an application and one of the views uses two tables. One table contain 200 row and the other 10 rows. Each row has children components. 

The website works fine but one user found a bug. When I press on escape, this is what I get: the next stack shown in the screenshot, and the site hangs for two seconds.

![image](https://github.com/angular/angular/assets/36598060/70128f71-c014-46f2-849c-bac79b547da1)

The solution I tried and worked on was to listen to the escape button and stop the propagation of the event. However, this means I have to implement an extra service to handle the default escape behavior like Closing a dialog, closing an overlay, unfocusing an input button, and so on. THis handeling feels like an extra effort that I would be surprised I would have to do myself for somthing I feel a mistake I made.

Note: changing the detection strategy did not work!

### Please provide the exception or error you saw

```true
[Violation] 'keydown' handler took 2577ms
```

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
