### ISSUE TITLE
Standalone injectors do not seem to be completely isolated

### ISSUE THREAD

**Issue by simpleman383** [angular/angular#53369]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Actually, this is more like a Stackoverflow question. But I'd appreciate if someone could help me and shed some light on this topic 😅

Just getting familiar with the concept of standalone components and now I'm a little curious about standalone injectors.

[The official documentation](https://angular.io/guide/standalone-components#standalone-injectors) says that such injectors are created in order to isolate the providers imported by a standalone component from the rest of an application. Indeed, that sounds right to me - especially in terms of "self-contained components". 

However, It seems that different standalone injectors are not fully isolated from each other in some cases ([stackblitz](https://stackblitz.com/edit/stackblitz-starters-zgv74k)). 

In the provided example the optional presense of providers at the routing configuration level deeply affects the entire tree of environment injectors.

1. When you define the "`providers`" property in the routing config (even if you leave it empty), Angular creates the corresponding `EnvironmentInjector` for a router scope and the outcome hierarchy has the following shape. As we can see, `Standalone[_AppComponent]` and `Standalone[_ChildComponent]` injectors are completely isolated and cannot affect each other.

![image](https://github.com/angular/angular/assets/17178718/a0c8c41e-78fd-420a-91fd-123ca6c3c0f2)
(isolated injectors)

2. However, if you don't define providers in the routing configuration, the hierarchy looks completely different. Now `Standalone[_AppComponent]` and `Standalone[_ChildComponent]` injectors are chained one by one and dependencies from `Standalone[_AppComponent]` are suddenly available inside the scope of `ChildComponent`. This looks like quite the opposite thing to what the official documentation initially states.

![image](https://github.com/angular/angular/assets/17178718/93622ce5-aad9-4730-b6e5-34603a1b3e5c)
(not isolated injectors)

Is this correct behaviour? And if it was added intentionally - what was supposed to be achieved? 

I admit that I may be misunderstanding the concept of standalone injectors. But for me it looks like that some dependencies provided in parent standalone components might unexpectedly leak to its child component injector's scope. Please explain me if I'm wrong 😅 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-zgv74k

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.5
Node: 20.10.0
Package Manager: yarn 1.22.21
OS: darwin arm64

Angular: 17.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.5
@angular-devkit/build-angular   17.0.5
@angular-devkit/core            17.0.5
@angular-devkit/schematics      17.0.5
@schematics/angular             17.0.5
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by alxhub** [comment]
This structure _is_ a little bit surprising to me - I would've expected that in the absence of `providers` in the child route, that the routed component is created with the root injector as its environment parent, not the `AppComponent` standalone injector (which must've come from the `RouterOutlet`). This could be interpreted as a bug in the router.

In general though, it's normal for standalone injectors to stack like this, or even for multiple standalone components to coalesce providers in one injector. The "isolation" mentioned in the docs is talking about the separation between `bootstrapApplication` providers and providers in the standalone `AppComponent`, not about the isolation between different standalone components in the injector tree.
