### ISSUE TITLE
Wrong route for the "Making HTTP requests" button

### ISSUE THREAD

**Issue by ionescu-valentin** [angular/angular#53378]
### Describe the problem that you experienced

the "Making HTTP requests" button below "Understanding communicating with backend services using HTTP" redirects to "/making-requets" instead of "/making-requests"

### Enter the URL of the topic with the problem

https://angular.dev/guide/http

### Describe what you were looking for in the documentation

HTTP Requests

**Comment by JoostK** [comment]
Thanks for the report, this has been fixed by https://github.com/angular/angular/pull/52541 and is pending deployment.
