### ISSUE TITLE
Update the typings for selenium-webdriver or remove them

### ISSUE THREAD

**Issue by radek-holy** [angular/angular#5337]
When I install Angular using `npm`, I can see Webdriver TypeScript definitions in `node_modules/angular2/typings`. For some reason `tsc` includes them when compiling my application. This effectively prevents me from installing the most recent Webdriver typings from DefinitelyTyped and thus from using newer features of Webdriver.

Why does Angular bundle typings for Protractor/Webdriver if it does not depend on these modules? Can you remove them?

If not, do you know how can I exclude them locally? I have already excluded the whole `node_modules` directory in `tsconfig.json`...

If not, can you please update them? But I believe that your users should have the possibility to choose their preferred version of other modules...

**Comment by radek-holy** [comment]
OK, as a workaround, I can cast the particular functions to `any` but then I loose the benefits of TypeScript.

**Comment by robwormald** [comment]
Are you using ///ref imports at all? Typically, as long as you're not importing from those files, tsc should only reference what you directly `import` in your source.

**Comment by radek-holy** [comment]
No. Should I? Why? None of Angular's docs examples nor Plunkers nor Julie's ng2-test-seed do. So far, `tsd` and `tsc` worked without any problem...

**Comment by alexeagle** [comment]
We removed the bundling of `selenium-webdriver` and other dependencies typings, try with beta.6

**Comment by radek-holy** [comment]
Cool, thank you!
