### ISSUE TITLE
Tutorial link - 404 page

### ISSUE THREAD

**Issue by raylablue** [angular/angular#53373]
### Describe the problem that you experienced

On the Angular getting started tutorial 
[angular.dev/tutorials/learn-angular/updating-the-component-class](https://angular.dev/tutorials/learn-angular/updating-the-component-class) 
there is a link to Type inference in TypeScript that has the address of [angular.dev/typescript.org/type-inference]( https://angular.dev/typescript.org/type-inference) but only displays a page not found. 

### Enter the URL of the topic with the problem

https://angular.dev/typescript.org/type-inference

### Describe what you were looking for in the documentation

I was looking for information about type inference

### Describe the actions that led you to experience the problem

clicking the link to open in a new tab, or copy/pasting the link in a new tab, or opening in the same tab. 

### Describe what you want to experience that would fix the problem

Ideal experience would be for the page to be found.

**Comment by santoshyadavdev** [comment]
checking

**Comment by JeanMeche** [comment]
This was fixed by #52714 and is pending deployement on our side. 

Thanks for reporting it though !

**Comment by santoshyadavdev** [comment]
found the same 😅
