### ISSUE TITLE
Basic question about .d.ts files

### ISSUE THREAD

**Issue by rlegrand** [angular/angular#5338]
Hi,

Sorry for this basic question but:
* Your **.d.ts** files are not anymore synchronized on the *DefinitelyTyped*
* The resolution mechanism which uses node modules depends on a **typings** field in *package.json*
(https://github.com/alexeagle/angular2-distro/blob/master/README.md , https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages)

Here, this field only contains **angular2.d.ts**, so what about **router.d.ts** for example? 

Thanks in advance

**Comment by robwormald** [comment]
@rlegrand see https://github.com/angular/angular/issues/5248#issuecomment-156886060

doing `import {Router, etc} from 'angular2/router' ` will give you what you want, if you use the npm style detailed there.
