### ISSUE TITLE
Publicly export PendingTasks to enable delaying SSR for WebSockets, etc

### ISSUE THREAD

**Issue by epelc** [angular/angular#53381]
### Description

Can `InitialRenderPendingTasks` be exported so that we can easily add tasks when processing websocket data similar to how http client works to delay rendering SSR responses until all requests have settled?

There appears to be no api to do this at the moment despite the large recent push for SSR upgrades in v17.

### Proposed solution

Publicly export `InitialRenderPendingTasks`

### Alternatives considered

Document an alternative to delaying SSR responses until asynchronous tasks are complete.

**Comment by epelc** [comment]
Looks like this was renamed to `PendingTasks` in https://github.com/angular/angular/commit/7780712553a2bec2dc446b6c05fe7faa51159927

Can this please be considered? There is currently no good way to delay SSR besides this. It seems like a pretty basic api to support in a SSR scenario. Anything async that isn't using prebuilt angular apis requires this.

**Comment by atscott** [comment]
@epelc there will absolutely be something provided that allows you to control the application stability for SSR. This is required for Zoneless. The exact shape of that API is yet to be determined.

**Comment by epelc** [comment]
@atscott Thanks! Happy to hear something is coming. I was reading some of your other comments about Zoneless.

I wonder what the thoughts are on "application is stable" vs "application is ready to send SSR data" apis and if it makes sense to have a difference. ie is it faster to load more data on server side or just load initial data to get something rendered out to client quickly. There are some interesting use cases for us where we have to delay SSR output until most of the page data is available in our ecommerce seo setting(ie you want full product data loaded for google).
