### ISSUE TITLE
@Host decorator doesn't work

### ISSUE THREAD

**Issue by laco0416** [angular/angular#5339]
**expected behavior**

API doc: https://angular.io/docs/ts/latest/api/core/index/Host-decorator.html

As the doc says, `@Host` works well in `@Directive`.

**current behavior**

not works. it returns `undefined`

**plunker**
http://plnkr.co/edit/9IBTMUaT9pmYepSujoCx

**steps to reproduce**
Open plunker and look at the console logs.

**Comment by choeller** [comment]
This still seems to be broken in Beta.15. As @ericmartinezr found out @Host works, when using `viewProviders` instead of `providers`: 

http://plnkr.co/edit/eObFOR98veqW6M9ZuvIi?p=preview

**Comment by choeller** [comment]
@pkozlowski-opensource Does the "docs"-label mean "works as expected"? IMO `@Host` also makes sense, for normal providers...

**Comment by laco0416** [comment]
Unfortunately, Still broken in 2.0.0. 😭 

a new repro here.
http://plnkr.co/edit/9IBTMUaT9pmYepSujoCx

In this example, I used `@Host` in `ParentCmp` component and it seems working well.

If really **this is a docs issue**, the current behavior says that `@Host` cannot be used in `@Directive`.
Then, what is the difference between `@Host` and `@Self`?

@pkozlowski-opensource I'd like to hear your current opinion.

**Comment by vicb** [comment]
@laco0416 please update the initial description with
- expected behavior
- current behavior
- plunker
- steps to reproduce

**Comment by laco0416** [comment]
@vicb done!

**Comment by vicb** [comment]
> steps to reproduce

I have looked at the logs, they are nice !

**Comment by choeller** [comment]
@vicb Looking at the logs I see an exception:

```
TypeError: Cannot read property 'name' of null
    at ChildDirective.ngOnInit (app.ts:27)
    at DebugAppView._View_ParentCmp0.detectChangesInternal (ParentCmp.ngfactory.js:38)
```
so this perfectly demonstrates, that the injection is not working with `@Host` Decorator.  Tbh I find it quite strange to only complain about the form of the ticket instead of dealing with the actual problem...

**Comment by vicb** [comment]
Given the number of new issues created every day we can not spend time trying to figure out what users are trying to do.

The issues with a clear description and a repro are usually resolved very quickly.

**Comment by vicb** [comment]
works as expected, see https://angular.io/docs/ts/latest/api/core/index/Host-decorator.html

**Comment by choeller** [comment]
@vicb Exactly this example code is not working, so I really can't understand why you simple close this issue. 

This plnkr contains the exact code from the docs and prints:

```
os is null null
hs is NOT null null // this is wrong / buggy!
```
http://plnkr.co/edit/cSE4vNtty72q5UuEF250?p=preview

To me just saying "we are getting to many issues so we are not having the time to really look at the things people are having problems with" seems super disrespectful. According to the docs this *is* a bug and given the time it took to argument what is wrong about the ticket it would have been perfectly possible to just check if maybe the reporter is not wrong. (btw. @mhevery already added the label "bug" so I'm having an even harder time to understand why this was just closed without having a further look)

**Comment by vicb** [comment]
If you think this is still an issue, please re-open a ticket with a proper description. Thanks.

**Comment by choeller** [comment]
@vicb It's not that "I think" its still an issue, it definitely is still an issue and both plnkrs (mine and @laco0416) perfectly demonstrate the problem. Creating an issue at least takes 10 minutes so why can't you just reopen this one again? On the one hand you say "We are getting too many issue so we can't have a close look" and on the other hand it's ok that we are supposed to redo the work we already did to re-create issues. Seems quite awkward to me...
