### ISSUE TITLE
Http Client Testing: include provideHttpClient()

### ISSUE THREAD

**Issue by GeorgeHulpoi** [angular/angular#53390]
### Describe the problem that you experienced

Is not enough to use `provideHttpClientTesting()` for HTTP Client Testing, it will throw a dependency injection error. Instead, both `provideHttpClient()` and `provideHttpClientTesting()`. Seems like the docs don't say anything about this, not even in examples...

**Comment by reafernandes10** [comment]
@GeorgeHulpoi Can I take this issue as my "#goodfirstissue"? I will try to reproduce the dependency error and use provideHttpClient() to fix it and update the docs with the information.

**Comment by JeanMeche** [comment]
Yes it's up for grab until someone lands a PR !

**Comment by doggy8088** [comment]
@JeanMeche This PR https://github.com/angular/angular/pull/53716 seems okay. Can you review and approve?
