### ISSUE TITLE
Angular datePipe at 31.12.2023 23:59:59 returns date 31. Dec 2023 inestead of 2023

### ISSUE THREAD

**Issue by AdamKundracik** [angular/angular#53399]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Having date 
Sun Dec 31 2023 23:59:59 GMT+0100 (stredoeurópsky štandardný čas)

in template ` {{ selectedPeriod?.end | date: 'd. MMMM. YYYY '}}`

pipe 'date' returns 31. Dec 2024 instead of 2023.

**Comment by JeanMeche** [comment]
Hi, it's the same issue as #49861. 

`YYYY` is the week numbering year. You should be using the lower case version : `yyyy`

**Comment by AdamKundracik** [comment]
@JeanMeche Perfect, thanks a lot. Helped! Weird why it does this kind of stuff :)
