### ISSUE TITLE
Module boundaries for standalone components

### ISSUE THREAD

**Issue by chaosmonster** [angular/angular#53406]
### Description

The goal of the feature request should be to describe a behavior that was (partially) possible with NgModules.

For this proposal the word “bundle” will be used to describe a concept, of components, directives, pipes and/ or services combined in one unit. This is not not meant as a goal, but as a semantic/ technical detail to talk about in this proposal.

As a developer in a large Angular code base I want to combine components, directives, pipes, and services to a bundle (in the past NgModule). 
The goal should be to enforce some form of boundaries, to avoid duplicate imports of components and define an API for a bundle in the form of components, directives, pipes and services that can be accessed from other parts of the application. With this concept we can logically isolate parts of the application (e.g. for lazy features) and import a bundle of components.
The boundaries would prevent code quality problems like spaghetti code, especially in larger teams/ projects. Developers define the intended use of larger chunks of components, directives, pipes and services by making clear what is exposed.

 NgModules solved this problem partially.

As we want to avoid NgModules in favor of Standalone Components in the future, we need to find a different alternative, that is not adding the same overhead of NgModules in a different way.

### Proposed solution

This is open for discussion, as a solution is not obvious yet

### Alternatives considered

An alternative to enforce the boundary problem is currently possible is to use Nx’s Standalone Application setup, which allows one application to have multiple libraries and define the API interface of those libraries by defining an index.ts file for each library. This is supported by the @nx/enforce-module-boundaries eslint rule, which allows other libraries and the application to only import components, directives, pipes, and services that are defined in the index.ts file. This way we can define and enforce a clear API for other developers for a semantically connected bundle of components, directives, pipes, and services, without actually defining, developing, and deploying separate libraries.

**Comment by chaosmonster** [comment]
thanks @tomastrajan  for the input

**Comment by rainerhahnekamp** [comment]
An Angular CLI (and Nx) compatible solution is to use https://github.com/softarc-consulting/sheriff. It comes in the form of an eslint plugin and doesn't require you to setup a full-blown library just to have modules with boundaries.

**Comment by Waterstraal** [comment]
To enforce boundaries, I use [eslint-plugin-boundaries](https://github.com/javierbrea/eslint-plugin-boundaries). Works similar to @nx/enforce-module-boundaries. 
But of course that still doesn't solve the case of bundling logically grouped components, directives, services and pipes. 🤔 

Maybe in a future version of Angular if [directly importing components](https://twitter.com/mgechev/status/1725601445234569698) is supported, we could make barrel files to solve this issue?

**Comment by mikezks** [comment]
> To enforce boundaries, I use [eslint-plugin-boundaries](https://github.com/javierbrea/eslint-plugin-boundaries). Works similar to @nx/enforce-module-boundaries. But of course that still doesn't solve the case of bundling logically grouped components, directives, services and pipes. 🤔
> 
> Maybe in a future version of Angular if [directly importing components](https://twitter.com/mgechev/status/1725601445234569698) is supported, we could make barrel files to solve this issue?

You need to create libraries for that. This is not a proper solution within your `src/app` folder.

**Comment by hakimio** [comment]
You can just export an array of components, directives, pipes, etc and then just import the array without the "spread" operator in your standalone component:
```ts
export const ACCORDION_COMPONENTS = [
    AccordionComponent,
    AccordionItemComponent
];
```

```ts
@Component({
    // ...
    standalone: true,
    imports: [
        ACCORDION_COMPONENTS
    ]
})
export class MyComponent {}
```

**Comment by Waterstraal** [comment]
> > To enforce boundaries, I use [eslint-plugin-boundaries](https://github.com/javierbrea/eslint-plugin-boundaries). Works similar to @nx/enforce-module-boundaries. But of course that still doesn't solve the case of bundling logically grouped components, directives, services and pipes. 🤔
> > Maybe in a future version of Angular if [directly importing components](https://twitter.com/mgechev/status/1725601445234569698) is supported, we could make barrel files to solve this issue?
> 
> You need to create libraries for that. This is not a proper solution within your `src/app` folder.

No, you don't need to create "libraries" for this... I'm not sure what you mean?... You can configure it on a directory level inside your src/app folder... No need for Nx as well

**Comment by mikezks** [comment]
> > > To enforce boundaries, I use [eslint-plugin-boundaries](https://github.com/javierbrea/eslint-plugin-boundaries). Works similar to @nx/enforce-module-boundaries. But of course that still doesn't solve the case of bundling logically grouped components, directives, services and pipes. 🤔
> > > Maybe in a future version of Angular if [directly importing components](https://twitter.com/mgechev/status/1725601445234569698) is supported, we could make barrel files to solve this issue?
> > 
> > 
> > You need to create libraries for that. This is not a proper solution within your `src/app` folder.
> 
> No, you don't need to create "libraries" for this... I'm not sure what you mean?... You can configure it on a directory level inside your src/app folder... No need for Nx as well

I misinterpreted your first message, sorry for that. I thought you were talking about Nx. 👍

**Comment by alxhub** [comment]
I don't think this is a problem that should be solved by Angular. Enforcing architectural patterns like this (who can import what) isn't limited to directives or pipes, it should apply to services, utility functions, normal classes, and other language level declarations.

Others have mentioned patterns around ESLint plugins, NX module boundaries, etc. which all solve this problem at a general level. Angular shouldn't provide a custom solution that only works for directive and pipe usage in templates.
