### ISSUE TITLE
feat(router): Allow _skipLocationChange when using navigate method

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#5340]
Right now if I want to navigate without changing the URL I have to do this.

```js
    router.navigateByInstruction(router.generate(['/ErrorPage']), true);
```

What I'd like to be able to do

```js
    router.navigate(['/ErrorPage'], true);
```

**Comment by mhevery** [comment]
Are you only requesting shorter syntax? Or is there a new capability?

**Comment by brandonroberts** [comment]
I'm only requesting shorter syntax. The capability already exists, its just not exposed on that method.
