### ISSUE TITLE
Discrepancies in Tour of Heroes tutorial

### ISSUE THREAD

**Issue by juliecorsaires** [angular/angular#53420]
### Describe the problem that you experienced

Hello,

I'm trying to follow the Tour of Heroes tutorial, but it seems that from one step to another, the project mode changes. 

#### First step : ####
At first we're asked to create a project with default options, which is standalone. 
Then we're asked to amend a app.module.ts file, which is not created since it's a standalone project. 
When checking the final code review of the first step, I can see it's a no-standalone project. 

So I began again with a no-standalone project. Now I've got my app.module.ts project and I can add stuff in it. 

#### Step two : ####
The components are standalone again, and the project can't build with the modifications added. 

If I check the final code available there (https://angular.io/generated/live-examples/toh-pt0/stackblitz.html), I see that components are standalone and that there's no app.module.ts file. 

#### Final steps : ####
The modules are back and components are no longer standalone. At this stage, my app builds with no errors but routes don't work. 

#### Comments ####
I'm very confused about this tutorial, and cannot find a way to make it work by following every step described. 

Did I misunderstood something, or is the app.module part deprecated ? Or the standalone part ? The tutorial keeps jumping from one to the other depending on the part, and the code provided does not show all the files.

Thanks a lot.

### Enter the URL of the topic with the problem

https://angular.io/tutorial/tour-of-heroes

### If this problem caused an exception or error, please paste it here

```true
✘ [ERROR] NG8001: 'app-heroes' is not a known element:
1. If 'app-heroes' is an Angular component, then verify that it is part of this module.
2. If 'app-heroes' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. [plugin angular-compiler]

    src/app/app.component.html:2:0:
      2 │ <app-heroes></app-heroes>
        ╵ ~~~~~~~~~~~~

  Error occurs in the template of component AppComponent.

    src/app/app.component.ts:5:15:
      5 │   templateUrl: './app.component.html',
```
If I set app component in standalone mode to declare app-heroes component, the error is the following : 

```
✘ [ERROR] TS-996008: Component AppComponent is standalone, and cannot be declared in an NgModule. Did you mean to import it instead? [plugin angular-compiler]

    src/app/app.module.ts:10:4:
      10 │     AppComponent,
```

**Comment by mvdluit** [comment]
@juliecorsaires In Angular v17 projects are generated with standalone by default. The tour of heroes tutorial seems to only partly be updated and still has references to modules (e.g. https://angular.io/tutorial/tour-of-heroes/toh-pt1#appmodule). 

As removing all these module references will take some time (PR + review), I think it's better if you try the tutorials on the new docs website [angular.dev](https://angular.dev). These all use standalone, which is the modern way of writing Angular apps 

FYI, modules are currently not deprecated, and will likely remain supported for legacy apps. If you want to use modules, you can simply add the `--no-standalone` flag to your `ng new` command.

**Comment by juliecorsaires** [comment]
Thanks for this response! I will check the tutorials on the new website.
