### ISSUE TITLE
Broken link to https://angular.dev/guide/releases

### ISSUE THREAD

**Issue by ahmadshahwan** [angular/angular#53424]
### Describe the problem that you experienced

The link to "developer preview" in [this page](https://angular.dev/guide/templates/control-flow) is broken. The link refers to https://angular.dev/guide/releases#developer-preview and leads to Page Not Found.

### Enter the URL of the topic with the problem

https://angular.dev/guide/templates/control-flow

### Describe what you were looking for in the documentation

Built-in control flow

### Describe the actions that led you to experience the problem

Click on the link "developer preview" in the above-mentioned page.

### Describe what you want to experience that would fix the problem

Landing on a page that describes what is developer preview, how to activate it or deactivate, etc.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/9466737/6c01b0c4-70f0-4bb9-af3c-e9417973c556)
![image](https://github.com/angular/angular/assets/9466737/245d4c62-2f35-4913-9694-3862b0a28395)

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue. It has already been fixed and is pending deployement on our side !

**Comment by ahmadshahwan** [comment]
Thanks for your reactivity.
