### ISSUE TITLE
Fresh system and clone of repo setup: Error: Cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by NathanWalker** [angular/angular#5343]
```
> node tools/analytics/build-analytics success install npm-install-net && node tools/analytics/build-analytics start install npm-postinstall && node tools/npm/copy-npm-shrinkwrap && node tools/chromedriverpatch.js && webdriver-manager update && bower install && gulp pubget.dart && tsd reinstall --overwrite --clean --config modules/angular2/tsd.json && tsd reinstall --overwrite --clean --config tools/tsd.json && tsd reinstall --overwrite --config modules/angular1_router/tsd.json && node tools/analytics/build-analytics success install npm-postinstall && node tools/analytics/build-analytics success install npm-install

module.js:339
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

**Comment by pkozlowski-opensource** [comment]
Make sure that you've got required node / npm versions:

requiredNpmVersion: '>=2.14.7 <3.0.0',
requiredNodeVersion: '>=4.2.1

**Comment by NathanWalker** [comment]
Thanks @pkozlowski-opensource I have node 5.0.0.... but npm version was correct.
Guess I will uninstall 5.x and install 4.2.1? hmm.

**Comment by NathanWalker** [comment]
You mentioned '>=4.2.1' so I assume 5.0.0 should be fine. Very frustrating error.

**Comment by ericmartinezr** [comment]
@NathanWalker 

In [Developer guide](https://github.com/angular/angular/blob/master/DEVELOPER.md) you can see  under **Prerequisite software**
>Node.js, (version >=4.2.1 <5)

**Comment by NathanWalker** [comment]
Thanks @ericmartinezr ... installing 4.2.1 now.... turns out also for some reason another version of `npm` (3.4.0) was installed somewhere else... ergh, node sometimes.

**Comment by vlastikcz** [comment]
With Node 5.0.0, you have to move 'fs-extra' from the 'devDependencies' to 'dependencies'. I don't know what causes this behavior though.

**Comment by corysimmons** [comment]
@vlastikcz Thanks. Worked for me on a completely unrelated project.
