### ISSUE TITLE
NG library : share code between entry points is not working

### ISSUE THREAD

**Issue by MGX-CODING** [angular/angular#53431]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Here is the structure of my library : 

![image](https://github.com/angular/angular/assets/116268534/981ac27f-b51f-46a3-bb11-f4f930d14483)

The `utils` folder contains code that I would like to reuse between my entry points (currently I have a single one, `buttons`). 

When I try to import code from `utils` like so : 

```typescript
import { InputToClasses } from '../utils/decorators/input-to-classes';
```

At build time, I get the following error : 

```
projects/mylib/buttons/button.directive.ts:2:32 - error TS6059: 
File '/home/max/projects/mylib/projects/mylib/utils/decorators/input-to-classes.ts' 
is not under 'rootDir' '/home/max/projects/mylib/projects/mylib/buttons'. 
'rootDir' is expected to contain all source files.

import { InputToClasses } from '../utils/decorators/input-to-classes';
```

I have tried several approaches (adding `rootDir` to my ts config, using includes, files, importing with custom paths ...) but nothing does it. 

Is it possible to have reusable code between entry points ? 

### Please provide the exception or error you saw

```
projects/mylib/buttons/button.directive.ts:2:32 - error TS6059: 
File '/home/max/projects/mylib/projects/mylib/utils/decorators/input-to-classes.ts' 
is not under 'rootDir' '/home/max/projects/mylib/projects/mylib/buttons'. 
'rootDir' is expected to contain all source files.

import { InputToClasses } from '../utils/decorators/input-to-classes';
```

### Please provide the environment you discovered this bug in (run `ng version`)

```
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.0.6
Node: 20.10.0
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                          Version
----------------------------------------------------------
@angular-devkit/architect        0.1700.6
@angular-devkit/build-angular    17.0.6
@angular-devkit/core             17.0.6
@angular-devkit/schematics       17.0.6
@angular-devkit/schematics-cli   17.0.6
@angular/cdk                     17.0.2
@schematics/angular              17.0.6
ng-packagr                       17.0.2
rxjs                             7.8.1
typescript                       5.2.2
zone.js                          0.14.2
```

**Comment by JoostK** [comment]
Cross entry-point imports must use absolute module specifiers, not relative ones. Entry-points are bundled into packages at arbitrary paths, so relative imports become inaccurate. Sharing code does therefore really require an independent entry-point of its own.

---

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
