### ISSUE TITLE
Customizing output names

### ISSUE THREAD

**Issue by enirtak** [angular/angular#53430]
### Describe the problem that you experienced

In Customizing output names section, the example is decorated with an @Input decorator.
Should it be @Output decorator instead?

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/outputs#customizing-output-names

**Comment by JoostK** [comment]
Thanks for the report, this was addressed in https://github.com/angular/angular/pull/52673 but has not yet been deployed.
