### ISSUE TITLE
Router info property isn't available in the child route component

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular#53450]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I have the following routes:

```ts
export const routes: Routes = [
  {
    path: 'todos',
    component: TodosComponent,
    children: [
      {
        path: ':id',
        component: TodoComponent,
      },
    ],
  },
];
```

From `AppComponent` I run:

```ts
  go() {
    this.router.navigateByUrl('/todos/1', { info: { message: 'Hello' } });
  }
```

The `info` is available only in `TodosComponent` and not in `TodoComponent`. I'm expecting it to be available in both or at least in this case in `TodoComponent`.

**Comment by atscott** [comment]
I’m assuming by available you mean the component constructor with Router.getCurrentNavigation? Navigation completes before change detection runs so this belabor is expected.

**Comment by ArielGueta** [comment]
> I’m assuming by available you mean the component constructor with Router.getCurrentNavigation?

Yes.

So there is no way to read this data in TodoPageComponent?

**Comment by JeanMeche** [comment]
There is [`Router.lastSuccessfulNavigation`]( https://angular.io/api/router/Router#lastSuccessfulNavigation)

**Comment by ArielGueta** [comment]
It's also not clear what's the difference with the state property. It seems that they behave the same.

**Comment by atscott** [comment]
> It's also not clear what's the difference with the state property. It seems that they behave the same.

The first sentence of the documentation explains how it is different from `state`:

> Use this to convey transient information about this particular navigation, such as how it happened. In this way, it's different from the persisted value state that will be set to `history.state`.

`info` is not persisted to `history.state`. It is only transient navigation information.
