### ISSUE TITLE
Can't style component that is inserted by router-outlet with ViewEncapsulation.Emulated

### ISSUE THREAD

**Issue by tandu** [angular/angular#5345]
```typeScript
@Component({
  selector: 'stub',
  template: 'stub'
})
class Stub {}

@Component({
  'selector': 'home',
  style: `
    stub, router-outlet + * {
      color: red;
    }
  `,
  template: 'Welcome to Home!<router-outlet></router-outlet>'
})
@RouteConfig([
  { path: '/', component: Stub }
])
export class Home {}
```
I understand it so that components that are added asynchronously don't get `_ng_content-<id>` attribute being assigned to them. It looks like a bug.

**Comment by silentHoo** [comment]
It seems to be broken since 2.0.0-final. With RC's before it worked.

Please see #11595 too which may be the better option for the future.

**Comment by vicb** [comment]
obsolete - old router

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
