### ISSUE TITLE
fix(router): incorrect type coercion of value `1` in RouteParam

### ISSUE THREAD

**Issue by wardbell** [angular/angular#5346]
When query parameter value is the number 1, e.g., `[ROUTE_NAMES.crisisCenter, {id: 1}] ` the resulting URL is `http://127.0.0.1:8080/src/#/crisis-center/;id` and `routeParams.get('id')` returns`true` instead of `1`.

Cause appears to be coercion of `1` to `true`

**Comment by vlastikcz** [comment]
How to reproduce this? I tried http://plnkr.co/edit/tiONceaWrHgaYLFvGBNi?p=preview, but unsuccessfully.

**Comment by garethdn** [comment]
Reproduced [here](http://plnkr.co/edit/bYXXDM55ZELKwOsXds0U?p=preview). It will need to be opened in a separate window in order to update the url. Click the square blue button in the top right of the preview window

**Comment by bkyarger** [comment]
@wardbell @btford I've got a PR attached for this, although I'm not 100% sure changing the truthy test doesn't break something else.  If there's another way you'd prefer to see this coercion prevented let me know and I'll update the PR.

**Comment by bkyarger** [comment]
@wardbell @btford is there anything that I can do to move this along?  Not sure what next steps would be to get my [PR](https://github.com/angular/angular/pull/6286) merged with a fix for this issue.
