### ISSUE TITLE
FEATURE: configurable signals change detection method

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#53484]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

I would like to have options/possibility to create signals with option that allows to set type of change detection that should be used when signal changes, especially for components or directives.

Right now there are two ways how to run change detection. `MarkForCheck` which is asynchronous way or `DetectChanges` which is synchronous way.

First one is currently used with signals. That means if signal has changed, it will automatically mark component for check. But if you detach component from change detection it is pointless and it does nothing and signals does not provide any advantage over regular value properties.

Maybe it is not directly connected to signals but to 'tracking context' which watches for changes of signals in component template. If so maybe it should be another configuration property for `@Component` which will allow to change what change detectors method should be used.

About immediately running DetectChanges after change of single signal is not right way, because there can be many singnals changed during one change detection cycle, but there could be solution in configuring how to run it, whether at the end of change detection or immediately.

This would add another benefit to signals :)

Thank you for consideration of this.

### Proposed solution

Proposed solution was mention above.

Some way of configuring this for component or signal itself.

### Alternatives considered

Only alternative now is explicitly call DetectChanges, which means you dont have to use 'signal' for it and just use regular value property.

**Comment by atscott** [comment]
> That means if signal has changed, it will automatically mark component for check. But if you detach component from change detection it is pointless and it does nothing and signals does not provide any advantage over regular value properties

Could you describe what you’re trying to accomplish a bit more? I’m really not sure what that is. What you've described is intended behavior (though parts of it are slightly inaccurate). Updating a signal absolutely should mark the component for check. Detaching something from change detection does prevent it from being refreshed during regular change detection traversal. 

What do you want the “configurable change detection” for signals to do? Only check the component that is reading the signal? Are you wanting this to run automatically when signals change or not? If not, when do you want it to refresh? Why doesn’t the detach/attach work for this?

**Comment by kukjevov** [comment]
Thanks for response. Sorry did not have time answer because this needs longer explanation.

Well reason why we need something like this and why i started thinking about this was that we have a bit specific situation. We are creating library that will generate content completely dynamically based on metadata. These metadata are loaded asynchronously (on demand). It will create whole page of content, it is already working but we found out problems with async/await with combination angular change detection system because Angular hooks are not waiting for async/await. It was working but in some situations it was behaving quite not deterministic since async await that were loding data especially in NgOnChanges were continuing its execution when loading of async await finished and we were not be able to await NgOnChanges call. There came an idea to detach component from Angular ChangeDetection and write our "own" calls of NgOnInit, NgOnChanges and so on so we would await these calls. This is working so far quite well and explicit calling of detect changes is also working and now its deterministic (order of execution and rendering).

But these dynamic components itself are now detached from change detection and we have to call DetectChanges manually. And i was thinking about signals whether they can help somehow. But right know using signals does not help. So the idea is that changes of signals registers calling of detectChanges in component after some changes in signals. From performance point of view it would be best to run it after "several" changes in signals occur. So not to call it after each change if multiple signals change during execution but when i dont know event listener execution has finished. I dont know whether it is possible, not even whether is something like this viable but it would help. If not we can still call explicitly detectChanges just like right now.

I can even provide example of our application if you need to see it. Anyway thanks for considerations. :)

**Comment by kukjevov** [comment]
And answers to your questions are:

> Only check the component that is reading the signal?

yes

> Are you wanting this to run automatically when signals change or not? If not, when do you want it to refresh? 

yes, but only once per execution of event handler, when component becomes idle

> Why doesn’t the detach/reattach work for this?

because reattaching cause run of Angular lifecycle hook methods without awaiting their calls

**Comment by atscott** [comment]
@kukjevov An example would be really helpful. It does sound like you should be able to just detach the view when you don't want it refreshed and then attach it again instead of calling `detectChanges`. It's a bit unclear to me still what more control you would need beyond that.

**Comment by pkozlowski-opensource** [comment]
Going to close this issue for now as we haven't heard back with the additional, requested info. Happy to re-open when new info surfaces.
