### ISSUE TITLE
Support the same number of child components as was supported in earlier versions (Angular 7 for example)

### ISSUE THREAD

**Issue by kochetkovSergeY** [angular/angular#53489]
### Description

There was an issue https://github.com/angular/angular/issues/53245 where the problem was described

### Proposed solution

Stop ignoring the problem -  resolve issue https://github.com/angular/angular/issues/53245

### Alternatives considered

-

**Comment by JeanMeche** [comment]
Please do not open multiple issues.

**Comment by kochetkovSergeY** [comment]
@JeanMeche Can you please give me a little explanation why both issues were closed?
