### ISSUE TITLE
BUG: syntax coloring for new block syntax, not working with Allman formatting

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#53483]
### Which @angular/* package(s) are the source of the bug?

language-service

### Is this a regression?

Yes

### Description

Following syntax is not colored correctly

```
@if(cond)
{
}
@else
{
}
```

also for 
```
@for(x of xxx; track x)
{
}
@empty
{
}
```

First block is colored that is ok, but second block is always as plain white text.

This is regression, because first version of new block syntax coloring (last beta or first rc, dont remember exactly) was working correctly. This is valid syntax that works, just is not colored correctly. 

Since it was working i dont think that there is any reason why it should not work anymore.

Thank you.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 17.0.6
Node: 18.17.1
NPM: 9.6.7
Angular Language Service VSCode Extension: 17.0.3
```

**Comment by atscott** [comment]
Unfortunately this is a trade off we had to make. See the context here: https://github.com/angular/vscode-ng-language-service/commit/075047ae31fefddc77364b466484dc825f192cec

Closing as working as expected.

**Comment by atscott** [comment]
Actually I’m going to reopen until we’re sure this is the trade off we want.

 Another option here would be to make the syntax highlighting work on the specific block names we support today. This would mean a small bit of extra maintenance burden with needing to keep the syntax highlighting up to date with the block names but it’s quite trivial. It could be a better option, at least for the moment while there’s a limited set of block types with no new ones on the roadmap.
