### ISSUE TITLE
"npm install angular2" fails

### ISSUE THREAD

**Issue by StephenC16** [angular/angular#5349]
Error report says that Reactivex/rxjs is a dependency that has not been published.

**Comment by robwormald** [comment]
@StephenC16 you likely need to update your version of NPM - you'll need at least version 3.

**Comment by gkalpak** [comment]
@robeormald, I think angular2 needs an npm vetsion `<3.0.0` atm.

**Comment by robwormald** [comment]
derp, @gkalpak is right -  `npm (version >=2.14.7 <3.0)`

**Comment by pkozlowski-opensource** [comment]
Yes, this is most probably an issue with npm / node version. Closing this one as it seems to be npm-related and we've got no way of debugging / troubleshooting this one.

**Comment by StephenC16** [comment]
I’m using npm -v 3.3.6.
