### ISSUE TITLE
select get null failed in filters

### ISSUE THREAD

**Issue by elvis-macak** [angular/angular#535]
<select ng-option='...' ng-model='myFilter.username'>
    <option value="">default</option>
    </select>

when i choose the default, `myFilter.username` is null. but what I want is an empty string.

so when I use it for filter:

    1. <li ng-repeat="user in users | filter:myFilter.username"></li>
    2. <li ng-repeat="user in users | filter:{username:myFilter.username}"></li>
    3. <li ng-repeat="user in users | filter:myFilter"></li>

the 1st  will get my correct answer, but 2nd and 3rd are not

**Comment by pkozlowski-opensource** [comment]
@elvis-macak this is wrong repo, you are probably looking for https://github.com/angular/angular.js
But frankly, this is kind of a support question that should be asked elsewhere, see: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
