### ISSUE TITLE
Link to type inference not working

### ISSUE THREAD

**Issue by srmnq** [angular/angular#53504]
### Describe the problem that you experienced

On this Site https://angular.dev/tutorials/learn-angular/updating-the-component-class under point **1** . The link to [type inference in TypeScript](https://angular.dev/typescript.org/type-inference). Links to a "Page not found" Error Page. 

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/updating-the-component-class

### Describe what you were looking for in the documentation

Link to type inference documentation

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by ##52714 and is pending deployement on ourside !
