### ISSUE TITLE
replaceUrl not preserved in redirect

### ISSUE THREAD

**Issue by stephenbunch** [angular/angular#53503]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

If I call `router.navigate` with `replaceUrl: true`, and if I have a `CanActivateFn` that returns a `UrlTree`, the resulting redirect loses the `replaceUrl` setting.

The relevant code is here:

https://github.com/angular/angular/blob/e3a6bf9b6c3bef03df9bfc8f05b817bc875cbad6/packages/router/src/router.ts#L196-L201

I can fix the issue by using `replaceUrl` setting if it's defined:

```ts
const extras = {
  // ...
  replaceUrl: currentTransition.extras.replaceUrl ?? (this.urlUpdateStrategy === 'eager' ||
  isBrowserTriggeredNavigation(currentTransition.source))
};
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-ih775l?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
In the demo app I provided, when you click "Replace: Baz -> Bar", you should see "replace: /bar" in the history, but instead you just see "/bar".
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"dependencies": {
  "rxjs": "7.8.1",
  "tslib": "2.6.2",
  "zone.js": "0.14.2",
  "@angular/core": "17.0.6",
  "@angular/forms": "17.0.6",
  "@angular/common": "17.0.6",
  "@angular/router": "17.0.6",
  "@angular/compiler": "17.0.6",
  "@angular/animations": "17.0.6",
  "@angular/platform-browser": "17.0.6"
},
```

**Comment by atscott** [comment]
Indeed, this is also true of all the other properties in `NavigationBehaviorOptions`. Based on the comment here https://github.com/angular/angular/issues/27148#issuecomment-442265173, it seems like this was considered but not done. This was before my time as the router caretaker. I noticed this when adding the `info` and `browserUrl` properties and decided the properties _should_ be carried over by default.

Changing this behavior would need to land in a major version. We would also need to do some preliminary tests to determine how breaking it is and decide if the change is worth making based on the results.

**Comment by atscott** [comment]
I ran tests inside google and found that updating `replaceUrl` value to be carried over for the redirect [passed all tests](https://fusion2.corp.google.com/presubmit/587142060/OCL:587142060:BASE:587110432:1701498674956:caf6af67/targets). This change should be easy to land for v18.

**Comment by blathers16** [comment]
Hi, @atscott I have pushed a pull request for this, please let me know if it needs any changes.
