### ISSUE TITLE
In-depth Guides: Http Client - invalid href to Making HTTP Requests section

### ISSUE THREAD

**Issue by Kerlione** [angular/angular#53509]
### Describe the problem that you experienced

When walking through the HTTP Client docs, the next step shortcut for **Making HTTP Requests** has an incorrect relative path, resulting in 404 error

### Enter the URL of the topic with the problem

https://angular.dev/guide/http#whats-next

### Describe what you were looking for in the documentation

Wanted to navigate to the **Making HTTP Requests** page via the [What's Next](https://angular.dev/guide/http#whats-next) section.

### Describe the actions that led you to experience the problem

Clicked on the **Making HTTP Requests** button in What's Next section

### Describe what you want to experience that would fix the problem

The issue is caused by a typo in the href:
1. Expected: href="/guide/http/making-**requests**"
1. Actual: href="guide/http/making-**requets**" _missing **s**_

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52541 and is pending deployement on ourside !
