### ISSUE TITLE
Be able to use Observable and toSignal inside a computed call

### ISSUE THREAD

**Issue by sdedieu** [angular/angular#53519]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Using the `toSignal` function inside a `computed` function lead to the following error: `Error: NG0602: toSignal() cannot be called from within a reactive context. Invoking `toSignal` causes new subscriptions every time. Consider moving `toSignal` outside of the reactive context and read the signal value where needed. Find more at https://angular.io/errors/NG0602`.

I understand the risk of having multiple subscritpions generated by the change of a signal value into the `computed` function.
But on the other hand it make sense to have a signal to store data that is build from a computed calls which contains the server call like this: 
```
product = computed(() =>
   toSignal(this.productService.getProduct(this.productId() /* <- a signal */), {
      initialValue: null,
  })()
);
```

Here `this.productId` can be a signal comming from an `input` or a route param.

At the moment, we would have to write something like this:
```
product = toSignal(
    toObservable(this.productId)
    .pipe(
      switchMap(productId => this.productService.getProduct(productId))
    )
  , { initialValue: null })
```

Would it be possible to have Angular compiling the first showed code into the second one ?

I've created a [stackblitz](https://stackblitz.com/edit/stackblitz-starters-nqf5mn?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fmain.ts,package.json&title=Angular%20Starter) as a playground.

### Proposed solution

I'm definetly not an expert with tools like babel or so...
So I asked chatGPT few questions and he suggested me a solution which can be a good start for a line of thought (even if the proposed solution is not generic).

```
const babel = require('@babel/core');

// Original code as a string
const originalCode = `
  computed(() => toSignal(this.productService.getProduct(this._productId()), { initialValue: null })())
`;

// Modify code using Babel
const modifiedCode = babel.transformSync(originalCode, {
  plugins: [
    // Use a custom Babel plugin to modify the AST
    function ({ types }) {
      return {
        visitor: {
          // Visit ArrowFunctionExpression nodes
          ArrowFunctionExpression(path) {
            // Check if the arrow function is part of the computed function
            if (
              path.parent.type === 'CallExpression' &&
              path.parent.callee.name === 'computed'
            ) {
              // Replace the arrow function with a new one
              path.replaceWith(
                types.arrowFunctionExpression(
                  path.node.params,
                  // Create a new AST for the desired modified code
                  types.callExpression(
                    types.identifier('toSignal'),
                    [
                      types.callExpression(
                        types.identifier('toObservable'),
                        [path.node.body.arguments[0].object.property]
                      ),
                      types.objectExpression([
                        types.objectProperty(
                          types.identifier('initialValue'),
                          types.nullLiteral()
                        ),
                      ]),
                    ]
                  )
                )
              );
            }
          },
        },
      };
    },
  ],
}).code;

// Log the modified code
console.log(modifiedCode);

```

### Alternatives considered

I know that in the vue ecosystem, there is the [vueuse](https://vueuse.org/) which exposes a [computedAsync](https://vueuse.org/core/computedAsync/#computedasync) function which broadly does what we want.

**Comment by JeanMeche** [comment]
Did you have a look at ngxtensions's [`computedFrom`](https://ngxtension.netlify.app/utilities/signals/computed-from/). 

It looks like this is what you are looking for.

**Comment by sdedieu** [comment]
> Did you have a look at ngxtensions's [`computedFrom`](https://ngxtension.netlify.app/utilities/signals/computed-from/).

Yes it is interesting for sure.
But I believe there is still to many rxjs operators involved in the example.

If I understand correctly the API, the above example will be

```
let product = computedFrom(
  [this.productId],
  pipe(
    switchMap(
      ([productId]) =>
        this.productService.getProduct(productId))
    ),
  ),
);
```

Right ?

**Comment by alxhub** [comment]
This code seems like exactly what you'd _want_ to write to do this:

```typescript
product = toSignal(
    toObservable(this.productId)
    .pipe(
      switchMap(productId => this.productService.getProduct(productId))
    )
  , { initialValue: null })
```

Converting the `productId` signal to an Observable for the async derivation, and converting the result back to a signal in the end. Computeds should be pure, synchronous functions - they're not a place for async work.
