### ISSUE TITLE
test injector should work smoothly with new bundles

### ISSUE THREAD

**Issue by juliemr** [angular/angular#5351]
With the new platform bundles, you can import directly from what you need for different platforms:

`import {bootstrap} from {'angular2/platform/browser'};`

However, the test injector is currently hardwired to only work for the browser platform. We need a smooth way of writing unit tests with an injector for a different platform. cc @vsavkin

**Comment by juliemr** [comment]
The default should be the same thing that you get with `bootstrap` - ready for use in the browser and with platform directives set up.

**Comment by juliemr** [comment]
Proposal:

Just like an application, Angular2 unit tests are going to need a bootstrap which will vary depending on the platform they are written for. Let's mirror the method of exporting different lists of providers by platform for tests as well, and export a setup function. These will live in `modules/angular2/platform/testing/*.ts`.

Unlike a real application, in tests there is no reason to distinguish between platform and application providers. A new injector is created for each test case - so just export one list of suggested providers. Name them `TEST_BASE_<PLATFORM>_PROVIDERS`.

The test injector, and by extension `angular2/testing`, will export a `setBaseTestProviders` function. This will need to be called by the test framework before any tests are run. This is not a huge burden because we already required some initialization, to set up the current dom adapter, which will be replaced. For example, in Angular's internal test suite the setup in `test-main.js` will change.

Breaking changes: This is a breaking change for tests, because of the change to the setup function.

In-progress CL coming soon!

**Comment by juliemr** [comment]
Design CL: https://github.com/angular/angular/pull/5975

There's still some clean-up to do, but it's a working prototype. cc @IgorMinar @alxhub @pkozlowski-opensource for design thoughts.

**Comment by cexbrayat** [comment]
I hope you don't mind, I have 2 questions.

I scrolled through your PR and I couldn't figure if the `COMMON_DIRECTIVES` and `COMMON_PIPES` would be included in `TEST_BROWSER_PLATFORM_PROVIDERS` or `TEST_BROWSER_APPLICATION_PROVIDERS`? 

I was also wondering if it was considered to include something for the `EVENT_MANAGER_PLUGINS`, to get rid of `provide(EVENT_MANAGER_PLUGINS, {useClass: KeyEventsPlugin, multi: true})` in tests?

**Comment by juliemr** [comment]
@cexbrayat these things are all included. `TEST_BROWSER_APPLICATION_PROVIDERS` => `BROWSER_APP_PROVIDERS` => `BROWSER_APP_COMMON_PROVIDERS` ([here](https://github.com/angular/angular/blob/3191fd144016c0873de4e3e24f0d8695a7d101c2/modules/angular2/src/platform/browser_common.ts#L70)) which includes common directives, common pipes, and event manager plugins.

**Comment by cexbrayat** [comment]
Ha great, that was the bit I missed! Thx @juliemr , I look forward to test this.

**Comment by naomiblack** [comment]
@alxhub could you review?

**Comment by juliemr** [comment]
Note that this is based on top of https://github.com/angular/angular/pull/5920 - it would be great to get that in first and it makes the review cleaner.

**Comment by jonnysamps** [comment]
Looks like the exports for `TEST_BROWSER_PLATFORM_PROVIDERS` and `TEST_BROWSER_APPLICATION_PROVIDERS` didn't make it into the bundles.  Is the on purpose?

**Comment by ericmartinezr** [comment]
@jonnysamps saw the same today. I modify @brandonroberts  plnkr and added manually everything needed http://plnkr.co/edit/mHx5yXmvnwpaf0ZICJ7l?p=info (skip everything on the top, you'll freak out).

**Comment by jonnysamps** [comment]
Good tip @ericmartinezr!  Thanks
