### ISSUE TITLE
Link to CLI command reference broken

### ISSUE THREAD

**Issue by brian-w-smith** [angular/angular#53527]
### Describe the problem that you experienced

From the CLI documentation page, the link to the command reference is broken. it currently points to https://angular.dev/cli/commands
With further browsing, looks like the correct URL should be https://angular.dev/cli

### Enter the URL of the topic with the problem

https://angular.dev/tools/cli

### Describe what you were looking for in the documentation

The command reference

### Describe the actions that led you to experience the problem

clicking the link

**Comment by JoostK** [comment]
Thanks for the report, closing as duplicate of https://github.com/angular/angular/issues/52549.
