### ISSUE TITLE
angular devtools: allow changing of signal value inside devtools

### ISSUE THREAD

**Issue by DimitriTsikaridze** [angular/angular#53528]
### Description

currently there is no way to change signal value in angular devtools, signal has this getter value which just links to its source code, where as if I assign value directly to a class property I can update it normally.
![image](https://github.com/angular/angular/assets/56136563/02002599-6ef1-4de6-86f8-b1abb1c756e5)

### Proposed solution

no proposed solution

### Alternatives considered

no alternatives considered

**Comment by JoostK** [comment]
This would indeed be nice, this is being tracked in #50944.
