### ISSUE TITLE
Overwrite functions like afterRender etc

### ISSUE THREAD

**Issue by muhamedkarajic** [angular/angular#53520]
### Description

I have a website framework which allowes me to build a website quick and easy however I have a problme that I'm using locomotive scroll and I need to let Angular render the hole DOM and after that I want to execute the refresh function of the locomotive scroll so it calculates how long the scrolling is etc. 

In order for me to do this in a efficient way I would like to have a way to overwrite the afterRender function to extend a default behavior for all components in my app but still keep the chance to extend the functionality for an individual component.

When I try the following:
```typescript
let original = afterRender;
(afterRender as any) = function(callback: VoidFunction, options?: AfterRenderOptions) {
  console.log('afterRender overwritten');
  original(callback, options);
}
```

I'm getting the following result:
```
⠹ Changes detected. Rebuilding...✘ [ERROR] Cannot assign to import "afterRender"

    src/app/initial-loading/initial-loading.component.ts:9:0:
      9 │ afterRender = function (callback, options) {
        ╵ ~~~~~~~~~~~
Imports are immutable in JavaScript. To modify the value of this import, you must export a setter function in the imported file (e.g. "setAfterRender") and then import and call that function here instead.
```

### Proposed solution

Allow me if possible to overwrite aka extend the current behavior of the afterRender.

### Alternatives considered

Not sure what else to consider.

**Comment by alxhub** [comment]
It's very unclear to me what feature you're requesting and what the use case for it is. Clearly, Angular can't change the behavior of ES modules and make imports mutable.

`afterRender` is a good tool for calculating things like scrolling heights. If you have common behavior that you want to share between components, can't you create your own wrapper?

**Comment by alxhub** [comment]
Closing as this is not actionable for us. In particular, it seems like the desired behavior can be achieved by wrapping `afterRender` through composition.

**Comment by muhamedkarajic** [comment]
> `afterRender` is a good tool for calculating things like scrolling heights. If you have common behavior that you want to share between components, can't you create your own wrapper?

Hi, yea I would like e.g. to have a common behavior to all components and be able to quickly add that behavior but also be able to extend it. How would I do that? Would I have to call the afterRender then call inside that after render the other function and provide the inputs or is there a better way?
