### ISSUE TITLE
Using the browser-esbuild builder requires one more additional step which is not mentioned in docs.

### ISSUE THREAD

**Issue by haladamateusz** [angular/angular#53524]
### Describe the problem that you experienced

I was not able to run `ng build` after changing builder to `browser-esbuild` which should be the only step to make, according to [documentation](https://angular.dev/tools/cli/esbuild#using-the-browser-esbuild-builder)

### Enter the URL of the topic with the problem

https://angular.dev/tools/cli/esbuild#using-the-browser-esbuild-builder

### Describe what you were looking for in the documentation

I came to [this topic](https://github.com/angular/angular-cli/issues/26304#issuecomment-1817233019) and tried to follow the guidance from angular.dev documentation. I changed the "builder" property to `"@angular-devkit/build-angular:browser-esbuild"`. Then, upon running `ng build` I received an error `Data path "" must have required property 'main'`. Then I realized, I need to exhchange `browser` property to `main` in order to get it work.

### Describe the actions that led you to experience the problem

I wanted to deploy a new angular 17 app to one of many cloud providers. Surprisingly, after running `ng build` my code is not outputted to location from `outputPath` property in angular.json. It's nested in additional `browser/` folder. 

### Describe what you want to experience that would fix the problem

Add extra paragraph to docs, where the property update (from `browser` to `main`)  is mentioned.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/26378632/46882182-8146-4a1e-8c24-f6e628665a5f)

**Comment by JoostK** [comment]
The documentation should be correct. It's the `application` builder that needs further updates, `browser-esbuild` should not.

> I wanted to deploy a new angular 17 app to one of many cloud providers. Surprisingly, after running ng build my code is not outputted to location from outputPath property in angular.json. It's nested in additional browser/ folder.

This is another hint that the `application` builder is being used, not `browser-esbuild`.

**Comment by haladamateusz** [comment]
@JoostK 
Okay, one more time. Steps for reproducing the error:

1. `ng new app`
2. go to `angular.json` and change builder to `browser-esbuild`
3. try to run `ng build`
4. Error occured:
<img width="575" alt="image" src="https://github.com/angular/angular/assets/26378632/d67bf6b3-a348-4a13-8804-111017831366">

Webstorm is also giving me a suggestion, that `browser` property is not valid for `browser-esbuild` builder.
<img width="703" alt="image" src="https://github.com/angular/angular/assets/26378632/61ccbc2b-b871-437b-bf5b-7363fdf06c35">

Solution: rename `browser` property to  `main`. Then the app builds without any problem. This step is missing in the documentation.

**Comment by JoostK** [comment]
A new app generated with `ng new app` will use the `application` builder, for which the documentation does not apply:

> You can try out the new build system for applications that use the browser builder. If using a custom builder, please refer to the documentation for that builder on possible migration options.

**Comment by cjosue15** [comment]
> A new app generated with `ng new app` will use the `application` builder, for which the documentation does not apply:
> 
> > You can try out the new build system for applications that use the browser builder. If using a custom builder, please refer to the documentation for that builder on possible migration options.

event if i don't want to enable the SSR mode?

<img width="914" alt="image" src="https://github.com/angular/angular/assets/51803643/1d40920b-bb6f-43a5-82a4-916bf6616ab1">

**Comment by JoostK** [comment]
> event if i don't want to enable the SSR mode?
> 
> 
> 
> <img width="914" alt="image" src="https://github.com/angular/angular/assets/51803643/1d40920b-bb6f-43a5-82a4-916bf6616ab1">

Yes, the application builder will then be configured not to enable SSR.

**Comment by alan-agius4** [comment]
The `browser-esbuild` is a compatibility builder that allows users to switch back and forth from the webpack to the esbuild based builder. 

For new projects there is no reason why users should switch to `browser-esbuild` as `application` builder is the preferred builder. 

Regarding the customization of the output path, this will be mitigated with https://github.com/angular/angular-cli/pull/26675 which will be part of 17.1.0 that will be released as stable in January 2024. That said, most of the cloud providers do support located the files in `/browser`.
