### ISSUE TITLE
Multiple event sent on ".next()"

### ISSUE THREAD

**Issue by Peekmo** [angular/angular#5353]
Hello,

I want to apologize first if someone ask it before, I did a lot of searches, and I didn't find an answer, so.. as I don't know if that's an issue or not, I post it there.

I have, for many events (but not all) the following issue : 
My listeners are called 2 times whereas I only send it once (I'm sure about it, I did a lot of tests) when I call next({}).

An example ?
The call : https://github.com/Peekmo/angular2-leap/blob/master/src/app/components/link-element/link-element.ts#L38
The template that call the component : https://github.com/Peekmo/angular2-leap/blob/master/src/app/components/page/page.html#L7
The function that is called twice for one .next() : https://github.com/Peekmo/angular2-leap/blob/master/src/app/components/page/page.ts#L23 (note : I'm forced to do that ugly timeout to avoid to do 2 times the same thing)

Is that normal ? Do I do something wrong ? (I have some listener in the same app that are only called once, and other twice so that's weird..)
If you never heard about that, that's probably an issue into my app.

Thank you ! :+1:

**Comment by DennisRoam** [comment]
Hey Peekmo, I'm not sure but I bet its related to this #5284 and #4768 
Seem's like a few folks have noticed similar behavior even though getting there different ways.

**Comment by robwormald** [comment]
@Peekmo you should use *either* `@Output() someEvent` or `outputs : []` - adding them both gets them registered twice :)

**Comment by robwormald** [comment]
Ref: https://github.com/angular/angular/issues/4798

**Comment by Peekmo** [comment]
Oh it was that simple... Thank you very much and sorry, 'cause it was a duplicate as I can see :(

**Comment by robwormald** [comment]
no worries, glad its working for you :+1:
