### ISSUE TITLE
Typo in Github label description 'help wanted'

### ISSUE THREAD

**Issue by danieljancar** [angular/angular#53548]
### Describe the problem that you experienced

The issues label 'help wanted' has a typo in the label description, it mistakenly says:

> An issue that ***it*** suitable for a community contributor (based on its complexity/scope).

While it should say:

> An issue that ***is*** suitable for a community contributor (based on its complexity/scope).

### Enter the URL of the topic with the problem

https://github.com/angular/angular/labels?q=help+wanted

### Describe the actions that led you to experience the problem

I saw the typo when I was searching for possible easy issues to work on in the angular/angular issues tab.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/112062588/f5a39bb4-fe45-497c-a038-21a2460760b3)

**Comment by alan-agius4** [comment]
Thanks, the description has been fixed.
