### ISSUE TITLE
CHANGELOG oversights aren't to be corrected?

### ISSUE THREAD

**Issue by lebedev** [angular/angular#53545]
### Describe the problem that you experienced

Hi! There's a duplicate entry in CHANGELOG.md about some public API removal. I opened a [PR](https://github.com/angular/angular/pull/53471) to correct that, but it was closed with words
> This is the changelog not a documentation page. It's not ment to be amended.

I'm confused about that and would appreciate if someone clears up my confusion.

Is it a recent rule? Does that mean that [the `changelog` scope](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#scope) isn't applicable anymore and is obsolete? I can see some amendments were made to CHANGELOG in the past, e.g. [this typo fixing](https://github.com/angular/angular/commit/0881daf690236ea01a07a9e1c1837eb7a0986ada).

The duplication in question:
![289294566-03ff2447-3fae-4348-8da9-2083f7effcb5](https://github.com/angular/angular/assets/5000549/2ad08f93-0b0e-4fb7-8255-4f53a8a3838c)

**Comment by JeanMeche** [comment]
I'll reopen the issue ! It wasn't clear to me that is just removed duplication.
