### ISSUE TITLE
Angular CLI 'Command Reference' card link is invalid

### ISSUE THREAD

**Issue by wtygibbs** [angular/angular#53560]
### Describe the problem that you experienced

The card titled "Command Reference" has a link to the url: 'https://angular.dev/cli/commands', which results in a Page Not Found, prompting the user to open an issue for the problem.

### Enter the URL of the topic with the problem

https://angular.dev/cli/commands

### Describe what you were looking for in the documentation

The Angular CLI commands and option flags.

### Describe the actions that led you to experience the problem

General browsing of the new angular.dev site.

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52589 and is pending deployement on ourside !
