### ISSUE TITLE
Cannot access 'trackBySignal' inside of a track expression.

### ISSUE THREAD

**Issue by zip-fa** [angular/angular#53572]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

This won't work:

```
@if(trackBy(); as trackBySignal) {
  @for(item of data; track item[trackBySignal]) {
    <p>
    #{{ item.id }} &mdash; {{ item.name }}
    </p>
  }
}
```

This will work:

```
@for(item of data; track item[trackByNonSignal]) {
  <p>
  #{{ item.id }} &mdash; {{ item.name }}
  </p>
}
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-dxjcrp?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
Cannot access 'trackBySignal' inside of a track expression. Only 'item', '$index' and properties on the containing component are available to this expression.
```

**Comment by JoostK** [comment]
This is working as designed; the `trackBy` function is not allowed to change, so cannot originate from a template variable.

**Comment by zip-fa** [comment]
So i modified my code to actually change trackBy with setInterval, and it still works:

```
type TestType = {
  id: number;
  name: string;
};

@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    Current trackBy: {{ trackByNonSignal }}

    <!-- THIS WORKS -->
    @for(item of data; track item[trackByNonSignal]) {
      <p>
      #{{ item.id }} &mdash; {{ item.name }}
      </p>
    }

    <!-- @if(trackBy(); as trackBySignal) {
      @for(item of data; track item[trackBySignal]) {
        <p>
        #{{ item.id }} &mdash; {{ item.name }}
        </p>
      }
    } -->
  `,
})
export class App {
  public data = [
    { id: 123, name: 'test' },
    { id: 456, name: 'test2' },
  ];

  public trackByNonSignal: keyof TestType = 'id';
  public trackBy = signal<keyof TestType>('id');

  constructor() {
    let tick = 0;

    setInterval(() => {
      this.trackByNonSignal = tick % 2 === 0 ? 'id' : 'name';
      tick++;
    }, 1000);
  }
}
```

Example on stackblitz updated too. Take a look @JoostK

**Comment by JoostK** [comment]
While that doesn't report any errors, it results in unstable identities which `for` does not account for.

**Comment by zip-fa** [comment]
I didn't want to change trackBy dynamically, that's not my initial idea.
Maybe allow devs to put something to trackBy from template-variable, and throw an error when its value changes?

**Comment by JoostK** [comment]
We decided not to support referencing template variables because it results in runtime overhead, as it requires dynamic lookup during change detection.

It is unclear to me what you _are_ trying to achieve, if it isn't for changing the value dynamically.

**Comment by zip-fa** [comment]
I am building universal table, which loads data from server.
Since this table supports different entities with different columns, i must put inside trackBy an existing key from entity. 
The only solutions for now:
1) use $index, but perforance will go down with table-sorting etc
2) use class variable, but cmon, why do i have to make proxy-variable? 

Example entity interfaces:
```
type Entity1 = {id: 123};
type Entity2 = {uuid: 'sdf-sdf-sdf'};

type RepeatableResponse<T> = {
results: T[];
primaryKey: string;
pagination: ...;
}
```

Pseudocode:

ts:

```
@Input()
set endpoint(endpoint: string) {
this.apiPath.set(endpoint);
}

public response = toSignal(this.responseObs);

private responseObs = computed<Observable<RepetableResponse<T>>>(() => {
return this.someService.getResults(this.apiPath());
});

```

html:
```
@if(response(); as response) {
<table>
<tbody>
@for(result of response.results; trackBy[response.primaryKey]) {
...
}
</tbody>
</table>
}
```

**Comment by JoostK** [comment]
I see. Yes, that would require referencing a component member.
