### ISSUE TITLE
A2 Forms - Deciding Input Types

### ISSUE THREAD

**Issue by dbarbour** [angular/angular#5358]
re:
http://angularjs.blogspot.com/2015/03/forms-in-angular-2.html

In review of the code, I did not see any means to choose the html tags which would be used.

In other words, all text is a one-line input <input type='text'>?  Never <textarea>?

**Comment by pkozlowski-opensource** [comment]
> In review of the code, I did not see any means to choose the html tags which would be used.
In other words, all text is a one-line input ? Never ?</p>

@dbarbour I'm sorry but it is not clear what is your concern... Did you try something that didn't work? Or just worried based on reading the mentioned blog post?

What is the type of HTML you would like to write that you think "won't work"?

**Comment by michalstepien** [comment]
Pls close :)
