### ISSUE TITLE
`URLSearchParams` body Content-Type incorrectly detected as 'application/json'

### ISSUE THREAD

**Issue by ElectronicRU** [angular/angular#53588]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

When passing `URLSearchParams` into `HttpClient.post`, it is serialized correctly, however, Content-Type detection incorrectly results in 'application/json' (because typeof URLSearchParams is object and there's no checking for it).
Probably should be another branch returning `null` in `http/request` `detectContentTypeHeaders`.

### Please provide the exception or error you saw

```true
The POST request in browser has content-type 'application/json'. Naturally the backend freaks out.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.10
Node: 16.20.2
Package Manager: npm 8.19.4
OS: linux x64

Angular: 15.2.10
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, router
```

**Comment by ElectronicRU** [comment]
P.S. I did swap it out for `HttpParams` and it works now, but this kind of half-support for it is IMO a bug.

**Comment by JeanMeche** [comment]
This is the code responsible for inferring the content type from the body. 

https://github.com/angular/angular/blob/18929040704828bf4caf76797ab141ca101c4b5f/packages/common/http/src/request.ts#L362

What would you content-type would you expect ?

**Comment by e-oz** [comment]
You can just set the needed content type, that's it. This feature isn't worth breaking the existing code.

**Comment by ElectronicRU** [comment]
@e-oz I find it hard pressed to believe that someone deliberately relies on `application/json` content-type for `URLSearchParams` body. This is not a new feature - it's a bug.

@JeanMeche the correct thing would be to return `null` - since `URLSearchParams` is passed as-is to XHR/fetch, the browser can infer the right content-type and encoding by itself - like what the code does for `FormData`.

**Comment by ElectronicRU** [comment]
Oh my bad - this is a duplicate of #36317 which has already been fixed.
