### ISSUE TITLE
Docs > Template syntax > Class and style binding > What’s next > Component styles - Page not found

### ISSUE THREAD

**Issue by EliasAlvarez22** [angular/angular#53582]
### Describe the problem that you experienced

Page not found

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/component-styles

**Comment by sasidharansd** [comment]
Can you provide the link/page from which you accessed this link ?

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52715and is pending deployement on ourside !
