### ISSUE TITLE
miss spelled link

### ISSUE THREAD

**Issue by Micah-L18** [angular/angular#53583]
### Describe the problem that you experienced

the link to making http requests is miss spelt

https://angular.dev/guide/http has a button labeled "Making HTTP Requests" 

it wrongly links to 
https://angular.dev/guide/http/making-requets

should be
https://angular.dev/guide/http/making-requests

**Comment by sasidharansd** [comment]
Duplicate of : https://github.com/angular/angular/issues/52542

**Comment by JoostK** [comment]
Thanks for the report, this has been fixed by #52541 and is pending deployment.
