### ISSUE TITLE
Add new code flow `@comment` syntax to annotate html code internally

### ISSUE THREAD

**Issue by moniuch** [angular/angular#53593]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

In some cases you might want to leave some comments in HTML template, but keep them internal and not render out into the browser, therefore something different than the regular HTML comments `<!-- -->` would be needed.

### Proposed solution

Let's leverage the new code-flow syntax to produce comments that get stripped out from the final build during compilation:

![image](https://github.com/angular/angular/assets/681956/5100089d-7b1a-420a-bc8b-dbdd46edc95f)

### Alternatives considered

One could use `ng-template` or some nasty tricks with `*ngIf="false"` to achieve that, but it's not really an alternative.

**Comment by JeanMeche** [comment]
Hi, 
Comment nodes are striped from template during the compilation. If you see them in the debugger it's likely because you're shipping the sourcemaps.
