### ISSUE TITLE
angular.dev doc bug

### ISSUE THREAD

**Issue by ManonLoki** [angular/angular#53602]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

[url](https://angular.dev/guide/components/outputs#customizing-output-names)

```
@Component({...})
export class CustomSlider {
  @Input('valueChanged') changed = new EventEmitter<number>();
}
```

this is @Output not @Input

**Comment by JoostK** [comment]
Thanks for the report, this was addressed in https://github.com/angular/angular/pull/52673 but has not yet been deployed.
