### ISSUE TITLE
Third party controls like Polymer & Value accessor error

### ISSUE THREAD

**Issue by robisim74** [angular/angular#5360]
Hi,

I see here https://github.com/angular/angular/commit/f21e78244f5c282b924b5290b5d7261ab69a4a55 that has been added a Value Accessor for ng-controll. Well, but it is required also for ng-model in two-way data binding. In fact, with Polymer paper-input i see this error:
`EXCEPTION: No value accessor for '' in [null]`
If I change in https://github.com/angular/angular/blob/f21e78244f5c282b924b5290b5d7261ab69a4a55/modules/angular2/src/core/forms/directives/default_value_accessor.ts this line:
`'input:not([type=checkbox])[ng-control],textarea[ng-control],input:not([type=checkbox])[ng-form-control],textarea[ng-form-control],input:not([type=checkbox])[ng-model],textarea[ng-model],[ng-default-control]'`
with this (I added `[ng-model]` at the end of line):
`'input:not([type=checkbox])[ng-control],textarea[ng-control],input:not([type=checkbox])[ng-form-control],textarea[ng-form-control],input:not([type=checkbox])[ng-model],textarea[ng-model],[ng-default-control],[ng-model]'`
the error is fixed.

cc @alxhub

**Comment by Zyzle** [comment]
@robisim74 You can add the `ng-default-control` directive to your `paper-input` that should work? I think the real way to handle this may be to write a value accessor for the polymer component though.

**Comment by robisim74** [comment]
Thanks again @Zyzle! This works. I had not seen the comment of @alxhub to your issue.
But I believe it is not intuitive to do this:
`<paper-input ng-default-control [(ng-model)]="address">`
I reference https://github.com/angular/angular/issues/3011 and I close this issue.

**Comment by zoechi** [comment]
Just for reference PolymerElements/paper-input#298
