### ISSUE TITLE
Page not Found while clicking on NgZone in angular new docs (angular.dev)

### ISSUE THREAD

**Issue by Satpal777** [angular/angular#53608]
### Describe the problem that you experienced

While going through angular.dev docs (https://angular.dev/best-practices/zone-pollution#run-tasks-outside-ngzone). There is a link for NgZone and on clicking it I was redirected to (https://angular.dev/guide/zone) it's show me **page not found.**

### Enter the URL of the topic with the problem

https://angular.dev/guide/zone

### Describe the actions that led you to experience the problem

While going through documentation if user clicks that link to know about NgZone that it should be redirected to proper page.

### Describe what you want to experience that would fix the problem

Fix the issue and redirect to proper page of documentation 

### Add a screenshot if that helps illustrate the problem

Screenshot marking link it was clicked
![Screenshot_20231217-114226~2](https://github.com/angular/angular/assets/85938637/41308146-76bf-42de-af14-429a2daf421b)

**Screenshot of page it was redirected to**
![Screenshot_20231217-113948~2](https://github.com/angular/angular/assets/85938637/7a0fc8b3-15d6-415f-90b5-e8656fdc1f9f)

**Comment by PauloKoglin** [comment]
Hi everyone :) it would be a pleasure to fix this one, can you please assign it to me?

**Comment by JeanMeche** [comment]
This has been fixed by #53667
