### ISSUE TITLE
Error handling for NgOptimizedImage

### ISSUE THREAD

**Issue by chriswoodie** [angular/angular#53617]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

In our current application we have a custom image component which uses `HttpClient` to fetch images, to allow showing a "broken image" icon for when the image fails to load. This should be supported in `NgOptimizedImage` to provide a cleaner UI when images fail to load properly.

### Proposed solution

Allow us to pass an alternative url as an `@Input` to the `NgOptimizedImage`, and set metadata on the `img` element so developers can know if the placeholder image is rendered or not, and style it accordingly if needed. 

### Alternatives considered

With the new control-flow syntax, perhaps it could be possible to have something like `@image/@error` blocks, allowing you to pass custom elements altogether if the image fails to load. This way would allow more control than the previously suggested idea. Something like:

```
@image {
  <img ngSrc="cat.jpg" />
}
@error {
  <my-fallback-component>
    <app-icon icon="broken-image" />
    The image could not be loaded :(
  </my-fallback-component>
}
```

**Comment by JeanMeche** [comment]
Hi, this is basically #18509. Let's continue the discussion over there !
