### ISSUE TITLE
angular.dev/cli/commands links to "Not Found"

### ISSUE THREAD

**Issue by ebmtz** [angular/angular#53614]
### Describe the problem that you experienced

https://angular.dev/cli/commands is linking to "Not Found"

### Enter the URL of the topic with the problem

https://angular.dev/cli/commands

### Describe what you were looking for in the documentation

Angular CLI reference

### Describe the actions that led you to experience the problem

Clicked on "Command Reference" link in https://angular.dev/tools/cli, which re-directed to https://angular.dev/cli/commands , but the page is not found.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/5950349/90c064da-4e52-43e2-a3ef-45bebe572cbb)

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52549 and is pending deployement on ourside !
