### ISSUE TITLE
The page links on the angular.dev website are broken

### ISSUE THREAD

**Issue by wangyingang** [angular/angular#53615]
### Describe the problem that you experienced

When I look at the `Command Reference` for `Angular CLI`, the page shows `Page Not Found`.

### Enter the URL of the topic with the problem

https://angular.dev/cli/commands

### Add a screenshot if that helps illustrate the problem

<img width="1720" alt="Screenshot 2023-12-18 at 16 34 36" src="https://github.com/angular/angular/assets/783997/02030f29-6b8a-4a70-aefb-10dc7c9b5747">

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52549 and is pending deployement on ourside !

**Comment by wangyingang** [comment]
I'm glad to see that!
