### ISSUE TITLE
While loading Huge data(2000 data & above) in table Using ngFor web Application is freezed

### ISSUE THREAD

**Issue by vinothAusweg** [angular/angular#53627]
### Which @angular/* package(s) are the source of the bug?

core, Don't known / other

### Is this a regression?

Yes

### Description

1.I have try trackBy function in ngFor. But it's not work.
2.cdk-virtual-scroll-viewport this is repeated same data's while scroll to see that much of data.

<img width="947" alt="Screenshot 2023-12-15 153342" src="https://github.com/angular/angular/assets/131762645/95eac431-a5ee-4540-8f4e-ac60954b8096">

### Please provide a link to a minimal reproduction of the bug

ngFor

### Please provide the exception or error you saw

```true
Web application is freezed
```

**Comment by vinothAusweg** [comment]
https://stackoverflow.com/questions/77665350/while-loading-huge-amount-of-data-in-table-use-ngfor-web-application-is-freeze?noredirect=1#comment136923694_77665350

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by vinothAusweg** [comment]
I asked StackOverflow also, i did't get solution there. so I post this issue here.Please give me any solution on this.

**Comment by JeanMeche** [comment]
Can you give us the output of `ng version` ?

**Comment by vinothAusweg** [comment]
> Can you give us the output of `ng version` ?

Angular CLI: 15.0.5
Node: 18.15.0
Package Manager: npm 9.5.0
OS: win32 x64

Angular: 15.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect            0.1502.4
@angular-devkit/build-angular    15.2.4
@angular-devkit/core                   15.2.4
@angular-devkit/schematics        15.0.5
@angular/cli                                  15.0.5
@schematics/angular                    15.0.5
rxjs                                                 7.5.7
typescript                                       4.8.4

**Comment by vinothAusweg** [comment]
Please reply or give any solution on this

**Comment by vinothAusweg** [comment]
> Can you give us the output of `ng version` ?


Please reply or give any solution on this
