### ISSUE TITLE
type-inference page is missing

### ISSUE THREAD

**Issue by karthikeyan993** [angular/angular#53655]
### Describe the problem that you experienced

This [link](https://angular.dev/typescript.org/type-inference) from updating the component documentation is broken.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/updating-the-component-class

**Comment by JoostK** [comment]
Thanks for the report, this is a duplicate of https://github.com/angular/angular/issues/52553 for which the fix is pending deployment.
