### ISSUE TITLE
Documentation on pipes missing

### ISSUE THREAD

**Issue by dionis-d** [angular/angular#53657]
### Describe the problem that you experienced

While clicking the link:
![image](https://github.com/angular/angular/assets/31817527/67908f49-c190-46a9-9c09-01450b753b6f)
from here:
https://angular.dev/guide/pipes#built-in-pipes
It redirects to another page that is not found:
https://angular.dev/api/common#pipes

### Enter the URL of the topic with the problem

https://angular.dev/api/common#pipes

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/31817527/a1a345ef-f607-402e-8361-4797718e70f0)

**Comment by JoostK** [comment]
Thanks for the report, closing as duplicate of https://github.com/angular/angular/issues/52968.
