### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by babaknabiee** [angular/angular#53658]
### Describe the problem that you experienced

https://angular.dev/versions

### Enter the URL of the topic with the problem

https://angular.dev/versions

### Describe what you were looking for in the documentation

Compatibale versions of Nodejs with current Angular version

**Comment by JoostK** [comment]
The page does exist under a different URL: https://angular.dev/reference/versions

If you found a link to https://angular.dev/versions somewhere please let us know, but closing for now.
