### ISSUE TITLE
AssetReader to be available as part of Angular's public API?

### ISSUE THREAD

**Issue by srawlins** [angular/angular#5366]
We're using [AssetReader](https://github.com/angular/angular/blob/master/modules_dart/transform/lib/src/transform/common/asset_reader.dart) which has just been marked as part of the private API. Any plans to make it part of the public API?

Also, I've opened dart-lang/barback#66 because I think that AssetReader should just be part of the barback package.

cc @yjbanov @IgorMinar

**Comment by IgorMinar** [comment]
@yjbanov can you please determine if this should be Angular's public api? I'm a bit suspicious, but I'm happy to hear arguments for making it public.

**Comment by yjbanov** [comment]
Yeah, we should make it public. It is needed to support custom code generators that do not use pub transformers.

**Comment by naomiblack** [comment]
We're closing this -- will not fix for Angular 2 release. However, if a compelling/urgent use case exists, please escalate to Misko.
