### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by danPwiz** [angular/angular#53663]
### Describe the problem that you experienced

Using NgComponentOutLet section has a link to a non existing page.

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/programmatic-rendering#using-ngcomponentoutlet

### Describe what you were looking for in the documentation

More information on `ngComponentOutletContent`

### Describe the actions that led you to experience the problem

Clicked a link

### Describe what you want to experience that would fix the problem

The link should lead to a page with relevant content 

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/135688952/2af42d45-a72e-4406-a8eb-6dee7737754d)
![image](https://github.com/angular/angular/assets/135688952/2e23d558-56c7-40ec-8d1e-9944c67a8d73)

**Comment by JoostK** [comment]
Thanks for the report, closing as a duplicate of https://github.com/angular/angular/issues/52828
