### ISSUE TITLE
Service doesn't mantain its state when inject on canActivateFn

### ISSUE THREAD

**Issue by MrCrafterman** [angular/angular#53671]
### Which @angular/* package(s) are the source of the bug?

router

### Description

I have a canActivateFn, I inject it a service that, at some point in my app, I change its property values. But, on canActivateFn doesn't get the updated values, seems like it creates a new instance service instead get singleton instance

### Please provide a link to a minimal reproduction of the bug

For example

```
@Injectable({ providedIn: 'root' })
export class MyService {
  propertyA: string | null
}
```

```
export const canActivateFn: CanActivateFn = (next: ActivatedRouteSnapshot, state: RouterStateSnapshot) => {
  const myService = inject(MyService)

  console.log(myService.propertyA) // Always null
}
```

at some point, I execute `doStuff()` function

```
export class SomeService {
  myService = inject(MyService)

  doStuff () {
    myService.propertyA = 'Hello World!';
  }
}
```

```
export const routes: Routes = [
  {
    path: '',
    loadComponent: () => import('...'),
    canActivate: [otherGuard],
    children: [
      {
        path: 'path1',
        loadComponent: () => import('...')
      },
      {
        path: 'path2',
        canActivate: [canActivateFn], // this is the guard
        loadComponent: () => import('...')
      }
    ]
  }
]
```

### Please provide the environment you discovered this bug in (run `ng version`)

```
Angular CLI: 15.2.9
Node: 20.10.0 (Unsupported)
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 15.2.9
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.9
@angular-devkit/build-angular   15.2.9
@angular-devkit/core            15.2.9
@angular-devkit/schematics      15.2.9
@angular/fire                   7.5.0
@schematics/angular             15.2.9
rxjs                            7.8.1
typescript                      4.9.5
```

### Anything else?

I tried use service insted function, I mean:

```
@Injectable({ providerIn: 'root' })
export class MyGuard {
  myService = inject(MyService)
  canActivate (...) {
    console.log(this.myService.propertyA) // Allways null
  }
}
```

I got same result

I tried to inject service on providers `app.config.ts`:
```
@Injectable()
export class MyService {
  propertyA: string | null
}
```
```
export const appConfig: ApplicationConfig = {
  providers: [
    ...
    MyService
  ]
}
```

I got same result

**Comment by JeanMeche** [comment]
Hi, could you provide a working repro on stackblitz ?

**Comment by Tweniee** [comment]
can you give me more info

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.

Attempted reproduction shows things working as expected: https://stackblitz.com/edit/stackblitz-starters-euwftp
