### ISSUE TITLE
angular.dev URL fragment links broken on api pages.

### ISSUE THREAD

**Issue by dvalentine314** [angular/angular#53679]
### Describe the problem that you experienced

I was looking at the [Angular animations documentation for transitions](https://angular.dev/api/animations/transition?tab=api) on angular.dev and I noticed a link about State Change Expressions. Clicking the link redirected me to the root of the site instead of to a section of Usage Notes.

It appears this link works correctly on the [old site](https://angular.io/api/animations/transition).

After some research I have determined that the old site had all information about the function in a flat structure on the page where as "angular.dev" has a tabular view separating the API from the Usage Notes which causes the URL fragment links to break.

### Enter the URL of the topic with the problem

https://angular.dev/api/animations/transition?tab=api

### Describe what you were looking for in the documentation

I was specifically looking for for documentation on Angular animations State Change expressions.

### Describe what you want to experience that would fix the problem

I believe this link should have directed me from:
   https://angular.dev/api/animations/transition?tab=api
 to: 
   https://angular.dev/api/animations/transition?tab=usage-notes#state-change-expression

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
(likely doesn't matter but it occurs on Chrome 120.0.6099)
```

**Comment by aryanvarma7272** [comment]
I am familiar with the problem you are facing but after finding the "State Change Expression" in source code , I founded the line of code which is :
=>  @param stateChangeExpr A string with a specific format or a function that specifies when the
 * animation transition should occur (see [State Change Expression](#state-change-expression)).
 
after this I am not getting a way for solution, I can't get the link "https://angular.dev/api/animations/transition?tab=api" ? 
Any assistance provided would be highly appreciated!

**Comment by JeanMeche** [comment]
This is due to the url remapper cf angular/dev-infra#1944. I'll close it as it is a wip
