### ISSUE TITLE
Remove outdated information about service worker and ng serve

### ISSUE THREAD

**Issue by Hafnernuss** [angular/angular#53689]
### Describe the problem that you experienced

The sentence:
```
The Angular development server (ng serve) doesn't support service worker applications.
```
Is outdated. According to [this](https://twitter.com/angular/status/1562938202482102273) tweet, it's supported since 14.2. (Interestingly, I didn't find it in the changelog or other release notes). 

I can use `ng serve` with production configuration and have a service worker up and running.

### Enter the URL of the topic with the problem

https://angular.io/guide/service-worker-getting-started#service-worker-in-action-a-tour

### Describe what you were looking for in the documentation
How to use a service worker when using `ng serve` in local development

### Describe what you want to experience that would fix the problem

Simply remove this sentence, and maybe add a hint that the configuration `production` is necessary for local `ngsw` support

**Comment by Varad-VK** [comment]
I want to work on this issue. Kindly assign it to me

**Comment by Narendherraj** [comment]
![image](https://github.com/angular/angular/assets/44496526/18c6de92-8dca-43c3-ad49-2b1b639e7414)
Should the same fix be applied to another part of the Service Worker documentation where **ng serve** isn't suggested ? As pointed out by @Hafnernuss now we can directly run the command **ng serve --configuration production** without the npx http-server steps as with Angular 14.2 the support has been added .

**Comment by Hafnernuss** [comment]
I think, it even works without production mode.

**Comment by JeanMeche** [comment]
We're looking at deprecating angular.io in favor of https://angular.dev. 

The service worker guide has been updated: https://angular.dev/ecosystem/service-workers

Feel free to open a new issue if you have suggestions, thank you.
