### ISSUE TITLE
Null Injector

### ISSUE THREAD

**Issue by Math7Guitar** [angular/angular#53680]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I created a TemplateModule, to componentize navbar and footer, but none of them are rendred on app.component.html, after imported to app.component.ts, all i got is blank page.

The ng serve compiles the code and point no error. I did test the import of TemplateModule's components, and it's working. If I remove module's import,  it shows an error, so components are imported, but not rendered on browser.

The only clue i found is the null injector pointed in Angular DevTools plugin.

ps: app.component.ts is a standalone component.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.7
Node: 18.15.0
Package Manager: npm 9.5.0
OS: linux x64
```

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
