### ISSUE TITLE
Any ways to run component outside ssr angular 17

### ISSUE THREAD

**Issue by W014ara** [angular/angular#53698]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler-cli, core, platform-browser-dynamic, platform-browser, platform-server

### Description

Is there a way to bypass SSR for individual pages. Previously, before version 17 of Angular, this could be done by specifying the following code:

`
server.get("/no-ssr", (req, res) => { res.sendFile(browserFolder + "/index.html"); });
`

How can this be done now?

### Proposed solution

Use old option which was described in Description Section or new functionality

### Alternatives considered

Use old option which was described in Description Section or new functionality

**Comment by JeanMeche** [comment]
You already opened the same issue on the CLI repo where it belongs. angular/angular#26747
