### ISSUE TITLE
sessionStorage is not defined | localStorage is not defined

### ISSUE THREAD

**Issue by debascoguy** [angular/angular#53699]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Both sessionStorage and localStorage  keeps generating the not defined error message. I discovered this error whenever I generated the angular project with server side rendering and config using angular version 17. 

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.8
Node: 20.10.0
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 17.0.8
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.8
@angular-devkit/build-angular   17.0.8
@angular-devkit/core            17.0.8
@angular-devkit/schematics      17.0.8
@schematics/angular             17.0.8
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by dlq84** [comment]
You can not use browser specific API:s in server side rendered components.

**Comment by debascoguy** [comment]
> You can not use browser specific API:s in server side rendered components.

But I am working on both client and server side. I have the browser route config and server config both bootstrapped. I would think the server side should not be blocking functionalities needed on the client browser side.

**Comment by jnizet** [comment]
Read this: https://angular.io/guide/ssr#authoring-server-compatible-components

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
