### ISSUE TITLE
`toSignal` could potentially be renamed to `toComputed` ?

### ISSUE THREAD

**Issue by jsgoupil** [angular/angular#53693]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

The concept of `Signal` and `WritableSignal` types is not "obvious" and usually "hidden" to the user. Because these types are not written in code.

So when we do `signal()` we get a `WritableSignal`.
When we do `computed()` we get a `Signal`.

But when calling `toSignal`, we get a `Signal`, so for a moment, I was searching for `toComputed`.

I find the naming a bit confusing

### Proposed solution

Rename `toSignal` to `toComputed` ?

### Alternatives considered

Live with it.

**Comment by atscott** [comment]
`toSignal` definitely does not return a `computed` so renaming to `toComputed` wouldn't make sense. Non-writable signals will also be returned by the signal input functions. I suspect the various behaviors for signals will become more familiar as the APIs are used more frequently. Closing as expected.
