### ISSUE TITLE
Not all Router Event typedefs extend RouterEvent

### ISSUE THREAD

**Issue by FiniteLooper** [angular/angular#53690]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

There are 17 `RouterEvent` types listed in the `EventType` enum. For each typedef of these events I would have expected them all to be marked with `extends RouterEvent`. 10 of them are, but the following 7 are not:

* [`ActivationEnd`](https://github.com/angular/angular/blob/d315e2c4fa178dfbd41bc25259605bb999fa302e/packages/router/src/events.ts#L564)
* [`ActivationStart`](https://github.com/angular/angular/blob/d315e2c4fa178dfbd41bc25259605bb999fa302e/packages/router/src/events.ts#L544)
* [`ChildActivationEnd`](https://github.com/angular/angular/blob/d315e2c4fa178dfbd41bc25259605bb999fa302e/packages/router/src/events.ts#L524)
* [`ChildActivationStart`](https://github.com/angular/angular/blob/d315e2c4fa178dfbd41bc25259605bb999fa302e/packages/router/src/events.ts#L505)
* [`RouteConfigLoadEnd`](https://github.com/angular/angular/blob/d315e2c4fa178dfbd41bc25259605bb999fa302e/packages/router/src/events.ts#L486)
* [`RouteConfigLoadStart`](https://github.com/angular/angular/blob/d315e2c4fa178dfbd41bc25259605bb999fa302e/packages/router/src/events.ts#L468)
* [`Scroll`]()

---------------

When unit testing code that used the `RouterConfigLoadStart` event I provided a mock router and passed this event in, but it produces an error that `'RouteConfigLoadStart' is not assignable to parameter of type 'RouterEvent'`

```ts
let app: AppComponent;
let fixture: ComponentFixture<AppComponent>;
let routerEventReplaySubject: ReplaySubject<RouterEvent>;

beforeEach(() => {
  routerEventReplaySubject = new ReplaySubject<RouterEvent>(1);

  TestBed.configureTestingModule({
    imports: [RouterTestingModule.withRoutes([]), HttpClientTestingModule, AppComponent],
    providers: [
      {
        provide: Router,
        useValue: { events: routerEventReplaySubject.asObservable() },
      },
    ],
  });
  fixture = TestBed.createComponent(AppComponent);
  app = fixture.componentInstance;
});

it('should show a loader instead of the router outlet when starting loading a route config', () => {
  fixture.detectChanges(); //triggers ngOnInit

  routerEventReplaySubject.next(new RouteConfigLoadStart({}));
  //                      ERROR ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // Argument of type 'RouteConfigLoadStart' is not assignable to parameter of type 'RouterEvent'.
  //   Type 'RouteConfigLoadStart' is missing the following properties from type 'RouterEvent': id, urlts(2345)

  fixture.detectChanges();

  expect(app.isLoadingRouteConfig).toBeTrue();
  expect(fixture.debugElement.query(By.css('[data-test-id="route-config-loader"]'))).not.toBeNull();
});
```

And here is my temp workaround to make my tests pass
```ts
 const event = new RouteConfigLoadStart({});
//@ts-expect-error The typedefs for RouteConfigLoadStart should be extending RouterEvent, but they do not
routerEventReplaySubject.next(event as RouterEvent);
```

### Please provide the exception or error you saw

```true
Argument of type 'RouteConfigLoadStart' is not assignable to parameter of type 'RouterEvent'.
  Type 'RouteConfigLoadStart' is missing the following properties from type 'RouterEvent': id, urlts(2345)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.8
Node: 18.15.0
Package Manager: npm 9.6.2
OS: win32 x64

Angular: 17.0.8
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.8
@angular-devkit/build-angular   17.0.8
@angular-devkit/core            17.0.8
@angular-devkit/schematics      17.0.8
@angular/cdk                    17.0.4
@schematics/angular             17.0.8
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JoostK** [comment]
The type of `Router.events` is `Observable<Event>`, _not_ `Observable<RouterEvent>`, where `Event` is imported from `@angular/router`.

**Comment by FiniteLooper** [comment]
Whoops, you're right. Thanks for pointing that out.
