### ISSUE TITLE
Virtual scroll positioning

### ISSUE THREAD

**Issue by ilyakonrad** [angular/angular#53704]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

I wish I knew the steps. I just use the devtools, click around, use "inspect element" etc.
I also use Redux Devtools. Not frequently, but it's installed.

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

I expect to not have layout issues with the devtools. However often times it ends up looking like this.
When I scroll, the tree is scrolled but the visible area stays the same. I suppose you have issues with virtual scroller.
Works fine after reload.

### Please provide a screenshot if possible [Bug Report only]

<img width="704" alt="image" src="https://github.com/angular/angular/assets/25200186/2e859c86-b4d7-40e8-90e2-b812209bac07">

### Is this a browser-specific issue? If so, please specify the device, browser, and version. [Bug Report only]

```true
I did not test in other browsers. This issue has been observed for a while now in Chrome.
So Windows 10/11, Chrome any recent version.
```

**Comment by JeanMeche** [comment]
Hi, could you check if there are any errors thrown by the extension in the console ?
