### ISSUE TITLE
Make FormArray and other examples useful

### ISSUE THREAD

**Issue by ilyakonrad** [angular/angular#53705]
### Describe the problem that you experienced

There's no example of how to use FormArray in the template.
What you can see on the screenshot or by opening the link is simply not enough to get an immediate grasp of how to set up the form.

### Enter the URL of the topic with the problem

https://angular.dev/api/forms/FormArray?tab=usage-notes

### Describe what you were looking for in the documentation

I was looking for a template syntax.

### Describe what you want to experience that would fix the problem

I want a lot of different examples, like on Angular Material site, where you have more than one example for every component and all of the code is shown.
If not a lot, I want at least one but super-descriptive example.
In the end of the day, the form is not only about the typescript, half of it is about the template.

### Add a screenshot if that helps illustrate the problem

<img width="600" alt="image" src="https://github.com/angular/angular/assets/25200186/ea1cd0b3-31cf-4a2d-960b-55539a5dd2b6">

**Comment by JeanMeche** [comment]
Hi, did you take a look at the [Reactive forms guide](https://angular.dev/guide/forms/reactive-forms#acesss-the-formarray-control) ?

**Comment by ilyakonrad** [comment]
Hmm, apparently no. Thanks!
Still finding my ways around the new docs. Though I see that the old docs are structured the same way.
Always felt it can be improved and wonder if I'm the only one confused where to look for stuff in the docs 🤔

**Comment by surajy93** [comment]
Assign to me I will provide good example 🕺

**Comment by twerske** [comment]
Hi all - closing as this seems resolved by the conversation on Reactive forms guides
