### ISSUE TITLE
Unable to use $index as a local variable when it is also used in track by

### ISSUE THREAD

**Issue by kai1992cool** [angular/angular#53706]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

When I set the track by to be using the for loop item, I am able to use $index. Stackblitz below

https://stackblitz.com/edit/stackblitz-starters-fdjyay

When I set the track by to be using $index, I am not able to use $index for a local variable. Stackblitz below

https://stackblitz.com/edit/stackblitz-starters-dtf5q1

The error I am getting!

    Property '$index' does not exist on type 'App'.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-dtf5q1

### Please provide the exception or error you saw

```true
Property '$index' does not exist on type 'App'.
```

### Please provide the environment you discovered this bug in (run `ng version`)

17.0.8

**Comment by JeanMeche** [comment]
Hi, this issue has already been reported in #52528.

**Comment by kai1992cool** [comment]
@JeanMeche Thanks!
