### ISSUE TITLE
Missing Pipes API documentation 

### ISSUE THREAD

**Issue by iki007** [angular/angular#53726]
### Describe the problem that you experienced

Navigating on https://angular.dev/guide/pipes and clicked on Note: For a complete list of built-in pipes, see the [pipes API documentation](https://angular.dev/api/common#pipes).

The information is missing from:
https://angular.dev/api/common#pipes

### Enter the URL of the topic with the problem

https://angular.dev/api/common#pipes

### Describe what you were looking for in the documentation

it seems that the https://angular.dev/api/common page is missing

**Comment by JoostK** [comment]
Thanks for the report, closing as duplicate of https://github.com/angular/angular/issues/52968. The fix is still awaiting deployment.
