### ISSUE TITLE
Dead link in documentation for HttpClientTestingModule

### ISSUE THREAD

**Issue by oluijks** [angular/angular#53728]
### Describe the problem that you experienced

Page not found for links to HttpClientTestingModule

### Enter the URL of the topic with the problem

https://angular.dev/api/common/http/HttpClientTestingModule

### Describe what you were looking for in the documentation

Info on HttpClientTestingModule

### If this problem caused an exception or error, please paste it here

```true
Page Not Found 🙃
If you think this is a mistake, please open an issue so we can fix it.
```

**Comment by JoostK** [comment]
For reference, the links occur [on this page](https://angular.dev/guide/testing/services#httpclienttestingmodule).

Interestingly, none of the `@angular/common/http/testing` entry-point is included in the API reference.

**Comment by JeanMeche** [comment]
I'll close this a part of #52663.
