### ISSUE TITLE
Defer, cancelIdleCallback = not working on safari?

### ISSUE THREAD

**Issue by montella1507** [angular/angular#53721]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

In production build, the application does not work in Safari when defer  @defer (on idle) {} is used. 

![image](https://github.com/angular/angular/assets/10418323/7568e634-d258-4854-8dee-31bca80aaf54)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
macos m2 air
Safari Version 17.2 (19617.1.17.11.9)
"executor": "@angular-devkit/build-angular:browser",

  "@angular/animations": "17.0.5",
    "@angular/cdk": "17.0.1",
    "@angular/common": "17.0.5",
    "@angular/compiler": "17.0.5",
    "@angular/core": "17.0.5",
    "@angular/forms": "17.0.5",
    "@angular/localize": "17.0.5",
    "@angular/platform-browser": "17.0.5",
    "@angular/platform-browser-dynamic": "17.0.5",
    "@angular/router": "17.0.5",
    "@angular/service-worker": "17.0.5",
    "@hakimio/ngx-google-analytics": "^15.0.0",
    "@ngneat/falso": "^6.1.0",
    "@ngrx/component": "^17.0.1",
    "@ngrx/component-store": "^17.0.1",
    "@ngrx/effects": "^17.0.1",
    "@ngrx/router-store": "^17.0.1",
    "@ngrx/store": "^17.0.1",
    "@ngrx/store-devtools": "^17.0.1",
    "@nx/plugin": "^17.1.3",
    "@swimlane/ngx-charts": "^20.1.2",


```

**Comment by montella1507** [comment]
DEV build (serve)
![image](https://github.com/angular/angular/assets/10418323/b1e5b2cd-6532-48d0-8d64-78e03e4707f1)

![image](https://github.com/angular/angular/assets/10418323/0df003cf-857e-4e28-a2a8-056dc1233942)

**Comment by JeanMeche** [comment]
Hi ! 
Thanks for the report, that guard looks wrong !

**Comment by montella1507** [comment]
Thank you very much, feel free to close the issue.

**Comment by JeanMeche** [comment]
Thx ! We'll do that once that PR is merged !

**Comment by JoostK** [comment]
Something is off here. Safari 17.2 only has `requestIdleCallback` behind an experimental flag, as it's still a preview feature not yet released as stable:

<img width="800" alt="Screenshot 2023-12-29 at 12 27 27" src="https://github.com/angular/angular/assets/123679/1af8766a-6635-43ed-86bb-5e4556bedb26">

Do you have an incomplete polyfill or something that causes this behavior?

**Comment by montella1507** [comment]
![image](https://github.com/angular/angular/assets/10418323/1b2060c1-9d85-44e9-b9fc-8e614ba5b314)

import 'zone.js'; // Included with Angular CLI.
import '@angular/localize/init';

this is all i have in polyfills.ts

**Comment by montella1507** [comment]
The same behavior is on the latest iphone with latest IOS.

**Comment by montella1507** [comment]
@JoostK 
![image](https://github.com/angular/angular/assets/10418323/8f0f564a-c0ab-4a50-9966-ddc2077df2e3)
Yeah it is not defined on any other webstie, so it must be polyfilled but, something... let me check :-)

**Comment by JoostK** [comment]
I tested with 17.2.1. Without the experiment enabled, both variables are undefined, and enabling results in both being defined with `native code`. So your screenshots do indicate an incomplete polyfill being present.

**Comment by montella1507** [comment]
I have found the polyfill in @sinonjs/fake-timers as a dependency  of @jest/fake-timers, but dont know hwy it is in built polyfill file... it is not referenced from our solution

**Comment by montella1507** [comment]
How is polyffils generated?I thought it is based ony on 
 "polyfills": "apps/portal/src/polyfills.ts"
 
 polyfilled function lands in polyffils chunk.

**Comment by montella1507** [comment]
Ok i have a winner :-)
![image](https://github.com/angular/angular/assets/10418323/87c37a73-c438-4cd3-83df-c6de9a4c293c)
 smartlook SDK :-)

**Comment by JoostK** [comment]
>  the solution is to improve guard, right?

I would say no. The guard is to detect support for idle callback support, which should come in pairs (if `requestIdleCallback` is present then `cancelIdleCallback` should also be present).

I'd suggest to polyfill `cancelIdleCallback` yourself until Smartlook fixes their polyfills. Their implementation doesn't look like it can be cancelled, so you could consider polyfilling both functions.

**Comment by montella1507** [comment]
@JoostK  so i should close this issue probably as far as it is considered from your side unnecessary.

**Comment by JoostK** [comment]
SGTM
