### ISSUE TITLE
Currency pipe doesn't follow the CLDR. 

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular#53720]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

`{{5.1234| currency: 'USD':'code'}}` outputs `USD5.12` but the [CLDR specifies](https://github.com/unicode-org/cldr-json/blob/858baad63c1d51e1d576ef99dccc229d92cedda4/cldr-json/cldr-numbers-full/main/en/numbers.json#L110) a space before. 

`Intl.NumberFormat` does it right. 

[Stackblitz](https://stackblitz.com/edit/angular-yhj2fz?file=src%2Fmain.ts,tsconfig.json)

### Anything else?

Instead of regularly updating the CLDR, we should like rely on the `Intl.NumberFormat` API. (cf #49143)

**Comment by JoostK** [comment]
This is a duplicate of #33803.
