### ISSUE TITLE
@Input decorator used instead of @Output in Custom events with outputs guide

### ISSUE THREAD

**Issue by ankurinfoniti** [angular/angular#53732]
### Describe the problem that you experienced

It should be @Output decorator not @Input in customizing output names section of documentation.

```
@Component({...})
export class CustomSlider {
  @Input('valueChanged') changed = new EventEmitter<number>();
}
```

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/outputs#customizing-output-names

### Describe what you were looking for in the documentation

I am looking for Custom events with outputs tutorial.

### Describe what you want to experience that would fix the problem

Change this code snippet
```
@Component({...})
export class CustomSlider {
  @Input('valueChanged') changed = new EventEmitter<number>();
}
```

to 

```
@Component({...})
export class CustomSlider {
  @Output('valueChanged') changed = new EventEmitter<number>();
}
```

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52673 and is pending deployement on ourside !
