### ISSUE TITLE
Improve ng-content

### ISSUE THREAD

**Issue by sedrac-calupeteca** [angular/angular#53736]
### Description

ng-content is not reliable to use when working with multiple slots. As an example, if I have a template with three ng-content and each one has its own selector identifier and when I call this template and indicate the identifiers of each selector and its contents, all content will always be inserted in the last ng-content.

### Proposed solution

Improving the functioning of NG-Content

### Alternatives considered

I have nothing to suggest

**Comment by JeanMeche** [comment]
Hi, could you share a stackblitz repro of the issue you're talking about ?

**Comment by spock123** [comment]
@sedrac-calupeteca  fwiw, I don't have any issues with this and I use it pretty extensively.

**Comment by sedrac-calupeteca** [comment]
I was working on a project with angular (https://github.com/sedrac-slc/eimath_frontend.git) that uses this api made in Spring boot (https://github.com/sedrac-slc/eimath_backend.git)
I noticed a problem working with ng-content in the module that creates (src/app/template/dashboard) in your html I declared more than one ng-content with its selectors then
I imported the dashboard module defining all slots and only displays the last one declared.
In those days I did a simple project and the situation didn't happen, so I'm reviewing what could be causing the problem in this angular project
