### ISSUE TITLE
Code written in plain text

### ISSUE THREAD

**Issue by hssanbzlm** [angular/angular#53739]
### Describe the problem that you experienced

While exploring Angular docs, in Dependency Injection under injection context (Stack frame in context). I found a code block written in plain text what makes it unclear and interfere with text.

### Enter the URL of the topic with the problem

https://angular.dev/guide/di/dependency-injection-context#stack-frame-in-context

**Comment by JoostK** [comment]
Thanks for the report, this is a duplicate of #53526, the fix is pending deployment.
