### ISSUE TITLE
feat(router): need a way to handle lazy loading of components without loading the entire tree on first load

### ISSUE THREAD

**Issue by lurock** [angular/angular#5373]
Currently the splat (...) syntax causes you to download everything up front because when you import 
ProfileComponent which in turn imports both OverviewComponent and LoginDetailsComponent. It would be really nice in large application to only download feature sections of the application as needed.

```
@RouteConfig([{
     path: '/profile/...', 
     component: ProfileComponent, 
     as: 'Profile'
}]
class AppComponent {
}

@RouteConfig([
    {
        path: '/', 
        component: OverviewComponent, 
        as: 'Overview'
    },
    {
        path: '/details', 
        component: LoginDetailsComponent, 
        as: 'LoginDetails'
    },
]
class ProfileComponent {
}

```

I have tried some other stuff with not very much luck:
```
path: '/profile/...', 
loader: () => return System.import('[pathToComponent]').then(m => m.ProfileComponent);
```

**Comment by ewinslow** [comment]
+1 for built in lazy loading

**Comment by evanplaice** [comment]
Possible dupe #5071

**Comment by btford** [comment]
This is already implemented. You can provide a `loader` (function that returns a promise that resolves to a component type) instead of `component` in a route config.
