### ISSUE TITLE
Wrong URL for Unicode CLDR

### ISSUE THREAD

**Issue by martinmolema** [angular/angular#53734]
### Describe the problem that you experienced

In the website `https://angular.dev/guide/i18n/locale-id` there are URLs to the Unicode CLDR : `https://cldr.unicode.org/development/core-specification#h.vgyyng33o798/`  and `https://cldr.unicode.org/development/core-specification`. They both result in a 404 due to new setup

### Enter the URL of the topic with the problem

https://angular.dev/guide/i18n/locale-id

### Describe what you were looking for in the documentation

The unicode CLDR for dutch

### Describe the actions that led you to experience the problem

I clicked the URL 

### Describe what you want to experience that would fix the problem

Find the correct link

### Add a screenshot if that helps illustrate the problem

![Schermafdruk van 2024-01-01 09-29-53](https://github.com/angular/angular/assets/3585494/dd5bdff6-81a3-470d-a204-b756f42791f5)

**Comment by NurRehman** [comment]
@JeanMeche Please assign it to me, I would like to contribute on that issue as my first Angular contribution. Thanks.

**Comment by JeanMeche** [comment]
@NurRehman Feel free to directly drop a PR ! 👍
