### ISSUE TITLE
adev: Monospace Links are rendererd wrong (ex. Chapter "Using DOM APIs")

### ISSUE THREAD

**Issue by TimJ0212** [angular/angular#53744]
### Describe the problem that you experienced

Links in monospace are not rendered correctly. Instead there is a gray box around the internal markdown text.

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/dom-apis

### Describe the actions that led you to experience the problem

Open the given page

### Add a screenshot if that helps illustrate the problem

![Bildschirmfoto 2024-01-01 um 20 19 35](https://github.com/angular/angular/assets/72557759/ab9d6fd0-2d92-4284-aca6-8edc2df68c3e)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
CHROME VERSION: 120.0.6099.129
OS VERSION: Mac OS X: 14.2.1
cpu_arch: x86-64
```

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52688 and is pending deployement on ourside !
