### ISSUE TITLE
Problem with Formatting Dates for 2023-12-31 (YYYY-MM-dd) with formatDate Method

### ISSUE THREAD

**Issue by StefanKruk** [angular/angular#53754]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

A customer is able to input a Date in the format `YYYY-MM-dd` to send it to our Backend we need to format the date to `YYYY-MM-ddTHH:mm:ss+0000`
For this we are using the `formatDate` Method https://github.com/angular/angular/blob/d315e2c4fa178dfbd41bc25259605bb999fa302e/packages/common/src/i18n/format_date.ts#L64

**Input:** 2023-12-31
**Expcted:** 2023-12-31T00:00:00+0000
**Actual:** 2024-12-31T00:00:00+0000

This can be reproduced by using the following code snippet.

```typescript
const defaultDateFormat = 'YYYY-MM-ddTHH:mm:ss+0000';
const defaultLocale = 'en_GB';
const defaultTimezone = 'en';

let formattedDate = formatDate(new Date('2023-12-31'),defaultDateFormat, defaultLocale, defaultTimezone);
console.log(formattedDate)
```

**ROOT CAUSE**
To get the Year the Method https://github.com/angular/angular/blob/d315e2c4fa178dfbd41bc25259605bb999fa302e/packages/common/src/i18n/format_date.ts#L432-L439
is used.
In this Method the Method 
https://github.com/angular/angular/blob/d315e2c4fa178dfbd41bc25259605bb999fa302e/packages/common/src/i18n/format_date.ts#L402-L406

is called, which creates a new Date from which the Year is then taken.
the Date is created via: `createDate(2023, 12, 31 (4 - 0))` => `createDate(2023, 12, 35)`

As the December do not have 35 Days the Month is incremented to 13.
As a Year do not have 13 Months the Year is incremented to 2024.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.2.11
Node: 16.20.0
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 16.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.11
@angular-devkit/build-angular   16.2.11
@angular-devkit/core            16.2.11
@angular-devkit/schematics      16.2.11
@angular/cli                    16.2.11
@schematics/angular             16.2.11
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
```

**Comment by JeanMeche** [comment]
Hi ! 
`YYYY` is the "week numbering year", you should be using `yyyy`. 

See #49861
