### ISSUE TITLE
Broken Link: If you would like to learn more, please consider completing some of Angular's other developer (tutorials)[https://angular.dev/tutorial]

### ISSUE THREAD

**Issue by BinaryGeometry** [angular/angular#53758]
### Describe the problem that you experienced

Link to further tutorials is broken here

"Congratulations! You've successfully completed this tutorial and are ready to continue your journey with building even more complex Angular Apps.

If you would like to learn more, please consider completing some of Angular's other developer [tutorials](https://angular.dev/tutorial) "

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app/http

### Describe what you were looking for in the documentation

Link to tutorials

### Describe the actions that led you to experience the problem

Clicked the link, was presented with the `broken link report issue` page.

### Describe what you want to experience that would fix the problem

The link to lead to further tutorials.

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #53125 and is pending deployement on our side !
