### ISSUE TITLE
Docs: interceptors example not working because of not existing method next on HttpHandler

### ISSUE THREAD

**Issue by jase88** [angular/angular#53771]
### Describe the problem that you experienced

the docs mentions the following example
```typescript
@Injectable()
public class LoggingInterceptor implements HttpInterceptor {
  intercept(req: HttpRequest<any>, handler: HttpHandler): Observable<HttpEvent<any>> {
    console.log('Request URL: ' + req.url);
    return handler.next(req);
  }
}
```

But `HttpHandler` has no `next` Method.
Probably `return handler.handle(req);` is meant?

### Enter the URL of the topic with the problem

https://angular.dev/guide/http/interceptors#di-based-interceptors

### Describe what you were looking for in the documentation

HTTP Interceptors in general

### Describe the actions that led you to experience the problem

Copy pasting code and seeing that `next()` does not exist on HttpHandler :)

### Describe what you want to experience that would fix the problem

Probably should be `return handler.handle(req);` instead of `return handler.next(req);`

**Comment by Mishra-Pravin** [comment]
@JeanMeche if this is still open, can you please assign it to me?
