### ISSUE TITLE
Issue with new lines in templates and web components

### ISSUE THREAD

**Issue by akorchev** [angular/angular#5377]
I found an odd issue related to new lines in `<template>` when used with web components (not sure if it is caused by web components though).

Here are two plunkrs: [working](http://plnkr.co/edit/y94pwZoVd0oXwAwEoCyk?p=preview), [not working](http://plnkr.co/edit/ijea64Z5tCS995BnB12A?p=preview) (load and press the *add* button - the second example shows empty items).

The only difference is this (in src/app.ts):

Working:
```       
<template var-person><x-person [text]="person.name">
          Content of {{person.name}}
          </x-person>
</template>
```

Not working:
```
<template var-person><x-person [text]="person.name">
    Content of {{person.name}}
    </x-person></template> <!-- no new line>
```

**Comment by vicb** [comment]
Please re-open if still an issue
