### ISSUE TITLE
docs: broken example in afterNextRender

### ISSUE THREAD

**Issue by zip-fa** [angular/angular#53775]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Hi. Example is broken on new angular.dev website, while it’s not on old one.

### Please provide a link to a minimal reproduction of the bug

https://angular.dev/api/core/afterNextRender?tab=usage-notes

**Comment by JeanMeche** [comment]
Looks like we have the same issue with `afterRender` : https://angular.dev/api/core/afterNextRender?tab=usage-notes

**Comment by JeanMeche** [comment]
The example works fine when changing the tabs.

**Comment by JeanMeche** [comment]
Actually I described the issue in #56569. Example has an issue because there are decorators
