### ISSUE TITLE
Pipes API documentation is not opening.

### ISSUE THREAD

**Issue by Chamanjaiswal** [angular/angular#53782]
### Describe the problem that you experienced

When I open this page it's not open.

### Enter the URL of the topic with the problem

https://angular.dev/api/common#pipes

**Comment by JeanMeche** [comment]
This issue is on : https://angular.dev/guide/pipes

**Comment by JoostK** [comment]
Thanks for the report, closing as duplicate of https://github.com/angular/angular/issues/52968. The fix is still awaiting deployment.
