### ISSUE TITLE
An unhandled exception occurred

### ISSUE THREAD

**Issue by LMS5413** [angular/angular#53786]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Hi! Im trying usage angular js but this error appears An unhandled exception occurred: require() of ES Module dir\node_modules\strip-ansi\index.js from dir\node_modules\ora\index.js not supported.
Instead change the require of dir\node_modules\strip-ansi\index.js in dir\node_modules\ora\index.js to a dynamic import() which is available in all CommonJS modules.
This error appears when install any modules.

### Please provide a link to a minimal reproduction of the bug

Install any packages.

### Please provide the exception or error you saw

```true
An unhandled exception occurred: require() of ES Module dir\node_modules\strip-ansi\index.js from dir\node_modules\ora\index.js not supported.
Instead change the require of dir\node_modules\strip-ansi\index.js in dir\node_modules\ora\index.js to a dynamic import() which is available in all CommonJS modules.
This error appears when install any modules.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.2
Node: 18.18.2
Package Manager: yarn 1.22.18
OS: win32 x64

Angular: 17.0.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.9
@angular-devkit/build-angular   17.0.9
@angular-devkit/core            17.0.9
@angular-devkit/schematics      17.0.9
@angular/cli                    17.0.9
@angular/ssr                    17.0.9
@schematics/angular             17.0.9
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JoostK** [comment]
This is likely an issue with your `package.json` or `node_modules` directory. You may attempt to remove `node_modules` and your lockfile to reinstall from scratch. Please also watch for peer dependency warnings.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
