### ISSUE TITLE
Angular request caching - cache payload with POST requests

### ISSUE THREAD

**Issue by benjaminbekes** [angular/angular#53781]
### Which @angular/* package(s) are relevant/related to the feature request?

platform-browser

### Description

I think that in applications where GET requests are not widely used, it could be great to have cached POST methods with their bodies (payloads) as well. Also could be nice to specify only which requests should be cached and not the entire project requests where some requests can be filtered out.

### Proposed solution

Include payloads of the POST requests to the cache.
Provide an opposite way to specify only specific requests to be cached.

### Alternatives considered

Not used

**Comment by JeanMeche** [comment]
Hi,

If you're talking about caching in general, this can be implemented on top of Angular via state management or libraries like tanstack-query. 

If you're talking about SSR Transfercache, this is already possible in v17, with `provideClientHydration(withHttpTransferCacheOptions(includePostRequests: true))`.
