### ISSUE TITLE
Unit test a service that uses effect and injects ChangeDetectorRef

### ISSUE THREAD

**Issue by ShacharHarshuv** [angular/angular#53796]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I'm not sure if that's actually a bug or if I just don't understand how I am supposed to do it. I couldn't find any related information in the docs. 

The problem is when trying to unit test a service that looks like this:

```ts
@Injectable()
export class MyService {
  readonly eff = effect(() => {});

  constructor(cdf: ChangeDetectorRef) {}
}
```

When doing the basic setup:

```ts
describe('MyService', () => {
  let service: MyService;

  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [MyService],
    });
    service = TestBed.inject(MyService);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });
});
```
You get the exception: 
```
NullInjectorError: R3InjectorError(DynamicTestModule)[MyService -> ChangeDetectorRef -> ChangeDetectorRef]: 
  NullInjectorError: No provider for ChangeDetectorRef!
```

My understanding is that you're supposed to create your own mock for the ChangeDetectorRef like so:

```ts
providers: [
  {
    provide: ChangeDetectorRef,
    useValue: {
      detectChanges: () => {},
    },
  },
  MyService,
]
```
However, when you do that, you get this cryptic exception:

```
TypeError: Cannot read properties of undefined (reading '2')
```

I managed to narrow it down to line 293 in effect.ts: `if (!cdr || !(cdr._lView[FLAGS] & LViewFlags.FirstLViewPass)) {`, where the `ChangeDetectorRef` is being injected, but it gets the mock instead, so `cdr._lView` is undefined, which is not properly handled. 

I believe that's a bug in the `effect` function, as it should allow consumers to mock `ChangeDetectorRef` without breaking (it works if it's not provided at all...)

If this is the intended behavior, please tell me how am I supposed to fix it from my side.

### Please provide the exception or error you saw

```true
TypeError: Cannot read properties of undefined (reading '2')
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.0-next.2
Node: 18.13.0
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: undefined
...

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.0-next.2+sha-9d7d136
@angular-devkit/architect-cli   0.1700.7
@angular-devkit/build-angular   17.1.0-next.2+sha-9d7d136
@angular-devkit/core            17.1.0-next.2+sha-9d7d136
@angular-devkit/schematics      17.1.0-next.2
@angular/animations             17.0.7
@angular/build-tooling          0.0.0-2ec28a960001deacf7a54952e5dcfbbdd810deca
@angular/cdk                    17.1.0-next.2
@angular/cli                    17.1.0-next.2
@angular/docs                   0.0.0-e00986799c9f15a3d8f264fdca07de8ef338c3ad
@angular/material               17.1.0-next.2
@angular/ng-dev                 <error>
@bazel/bazelisk                 1.18.0
@bazel/buildifier               6.3.3
@bazel/concatjs                 5.8.1
@bazel/esbuild                  5.8.1
@bazel/ibazel                   v0.16.2
@bazel/jasmine                  5.8.1
@bazel/protractor               5.8.1
@bazel/rollup                   5.8.1
@bazel/runfiles                 5.8.1
@bazel/terser                   5.8.1
@bazel/worker                   5.8.1
@schematics/angular             17.1.0-next.2
rxjs                            7.8.1
typescript                      5.3.2
```

**Comment by pkozlowski-opensource** [comment]
> My understanding is that you're supposed to create your own mock for the ChangeDetectorRef

No, as a general rule you shouldn't mock framework internals to test application code.

Also, would love to hear more about "service that injects ChangeDetectorRef" - ChangeDetectorRef is really linked to the component concept so likely shouldn't be used in services.

**Comment by MurhafSousli** [comment]
Could you update when you find the answer? I cannot find any example or tutorial for testing signals or effects anywhere!

**Comment by pkozlowski-opensource** [comment]
I'm going to close this one for now:
* as mentioned the `ChangeDetectorRef` is a concept from the component world and likely shouldn't be used in global services;
* testing of effects is possible (note: calling detectChanges on the TestBed fixture will flush effects as well).

**Comment by sharshuv-quotient** [comment]
Hey, I was able to rewrite my code to avoid using the `ChangeDetectorRef` in a service (and use it in the component instead) and informed my team of this "rule". 
Thanks!

**Comment by sharshuv-quotient** [comment]
Hey, I was able to rewrite my code to avoid using the `ChangeDetectorRef` in a service (and use it in the component instead) and informed my team of this "rule".
Thanks!

**Comment by ShacharHarshuv** [comment]
Hey, I was able to rewrite my code to avoid using the `ChangeDetectorRef` in a service (and use it in the component instead) and informed my team of this "rule".
Thanks!
