### ISSUE TITLE
NavigationEnd event not firing on constructor

### ISSUE THREAD

**Issue by dr-ananthakrishna** [angular/angular#53791]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

Hi,
I am using the following snippet for performing a check in a route, it goes like:
```javascript
const routeSubscription = this.router.events.subscribe(event => {
      if (event instanceof NavigationEnd) {
       console.log('here');
        // Perform an operation     
      }
});
```
This is inside a `constructor`. But the event is not firing on first load. It was happening till my Angular version was 11, now after upgrade to 15, it stopped.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.10
Node: 16.17.0
Package Manager: npm 8.15.0
OS: darwin x64
```

**Comment by JeanMeche** [comment]
Yes, this is a breaking change introduced in v15, see [more details here](https://angular.io/guide/update-to-version-15#routeroutlet-instantiates-the-component-after-change-detection).
