### ISSUE TITLE
Signal components: Why call the constructor before the required inputs and static child queries are ready?

### ISSUE THREAD

**Issue by inmativ** [angular/angular#53804]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

I'm late to the discussion on signal components, which was done at this link: https://github.com/angular/angular/discussions/49682
However, I would like to offer my thoughts for your consideration.

A recurring problem for me is the optionality of fields. I always use the strictPropertyInitialization flag. Therefore, in ngOnInit you have to either check for the presence of inputs, or suppress typing using the definite assignment assertion operator (prop!: Type). It's messy and sometimes unsafe.

Signal components may or may not solve this problem. If we initialize mandatory inputs with "type | undefined", then this is no different from the previous approach. We will still have to have multiple checks to exclude undefined from the type.

### Proposed solution

But what if we wait for mandatory inputs, as well as for static viewChild, until the initial values ​​for them are passed and only then call the constructor?

### Alternatives considered

As I understand it, my proposal is late. Probably, development is already underway in a different direction. In this case, the issue should be closed or marked as a question.

**Comment by JoostK** [comment]
Angular components are rendered in two phases: the first pass only creates elements/components, but does _not_ process template bindings. One reason for this is that e.g. template references can capture an element forwards in the template.

The proposed input syntax does avoid the problem with `strictPropertyInitialization` though, as fields are always assigned using `field = input.required<string>()`, of which the type is `string` because `.required` was used.

**Comment by inmativ** [comment]
Thank you for your reply. I didn't know about such nuances with the template.

What happens if you use such a mandatory input in the constructor? Will the values ​​be ready by then? Or will an error be thrown? Will we be able to initialize other fields in the constructor using the values ​​of the required inputs?

**Comment by pkozlowski-opensource** [comment]
> What happens if you use such a mandatory input in the constructor? Will the values ​​be ready by then? Or will an error be thrown?

In the current proposal it will throw.

> Will we be able to initialize other fields in the constructor using the values ​​of the required inputs?

No. But you will be able to use those in a reactive context (ex. `computed` or a direct reference in a template).

**Comment by inmativ** [comment]
Understood. Overall this is a good compromise.
Thank you for your time!
