### ISSUE TITLE
Typo on angular.dev

### ISSUE THREAD

**Issue by JasinRefiku** [angular/angular#53805]
### Describe the problem that you experienced

On outputs' section, 'customizing output names' on angular.dev's documentation, an example is presented with an `@Input` decorator instead of an `@Output`. 
![image](https://github.com/angular/angular/assets/93801443/cd7397d8-6669-4cd0-bcb1-8ee26bbe60f4)

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/outputs

**Comment by JoostK** [comment]
Thanks for the report, this was addressed in https://github.com/angular/angular/pull/52673 but has not yet been deployed.
