### ISSUE TITLE
Docs: don't recommend using `$index` as a good default

### ISSUE THREAD

**Issue by d-koppenhagen** [angular/angular#53800]
### Describe the problem that you experienced

In the docs (angular.io / angular.dev), the following sentence is written:

>  Because of the potential for poor performance, the track expression is required for the @for loops. When in doubt, using track $index is a good default.

See references: https://github.com/search?q=repo%3Aangular%2Fangular+%22is+a+good+default.%22&type=code

In my opinion tracking the `$index` isn't a good tracking criteria at all since the index may changes and in conclusion this can result in unexpected behavior.

I created a Stackblitz Demo project to simulate this behavor:
https://stackblitz.com/edit/angular-track-list-comp?file=src%2Fmain.ts

### Enter the URL of the topic with the problem

https://angular.dev/api/core/@for

### Describe what you were looking for in the documentation

https://github.com/search?q=repo%3Aangular%2Fangular+%22is+a+good+default.%22&type=code

### Describe what you want to experience that would fix the problem

The recommendation should be changed.
There are also situations which should be discussed such as how to handle tracking a non-unique string array?
e.g. `['apple', 'pea', 'orange', 'pea']`

**Comment by JeanMeche** [comment]
Performance wize `$index` is a reasonable default. It is indeed not suited when the dom is stateful, A focused input is a good example. 

Here is another example where, it's not a good fit : DOM manipulation : https://stackblitz.com/edit/angular-track-index?file=src%2Fmain.ts

**Comment by d-koppenhagen** [comment]
Maybe it should be changed like this: 

> Because of the potential for poor performance, the track expression is required for the @for loops. When in doubt, using track $index is a good default for stateless lists. Keep in mind, tracking $index may cause side effects when the lists are stateful. We recommend to track on a unique attribute when available.

**Comment by d-koppenhagen** [comment]
A fix will probably make #46980 obsolete or include it.

**Comment by pkozlowski-opensource** [comment]
Re-wording was proposed in #53806 - happy to discuss more if needed but for now I would consider this one closed.
