### ISSUE TITLE
Conflicting paragraph in `Component host elements` doc page

### ISSUE THREAD

**Issue by andresmq** [angular/angular#53809]
### Describe the problem that you experienced

In this page there is the following parapraph:

> Always prefer using the host property over [@HostBinding](https://angular.dev/api/core/HostBinding) and [@HostListener](https://angular.dev/api/core/HostListener). These decorators exist exclusively for backwards compatibility.

On the other hand, in the [Angular coding style guide](https://angular.io/guide/styleguide#hostlistenerhostbinding-decorators-versus-host-metadata) (Style 06-03) we found this:

> Consider preferring the @[HostListener](https://angular.io/api/core/HostListener) and @[HostBinding](https://angular.io/api/core/HostBinding) to the host property of the @[Directive](https://angular.io/api/core/Directive) and @[Component](https://angular.io/api/core/Component) decorators.

Which one is the correct?

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/host-elements#the-hostbinding-and-hostlistener-decorators

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue, we're tracking it at #52561 !
