### ISSUE TITLE
angular.dev documentation has wrong sentence

### ISSUE THREAD

**Issue by Abodawoud** [angular/angular#53818]
### I found in the documentation a _wrong sentence_ at the end of the [if-block](https://angular.dev/essentials/conditionals-and-loops#if-block) section 

![image](https://github.com/angular/angular/assets/109487123/f19ce507-9a80-402b-8dec-24624ac15178)

It said:
In this example, Angular only renders the `<section>` element if the `isAdmin` property is true. Otherwise, it does not appear page.

**The sentence is wrong as it should be `<button>` element  instead of `<section>` element** 

### Enter the URL of the topic with the problem

https://angular.dev/essentials/conditionals-and-loops#if-block

**Comment by JoostK** [comment]
Thanks for the report, this issue has been fixed by #52586 and is pending deployement.
