### ISSUE TITLE
ISO week-numbering year incorrect for some years

### ISSUE THREAD

**Issue by chucknelson** [angular/angular#53813]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

When using the ISO week-numbering year format in a date pipe (e.g., 'YYYY' format string), for some years it seems to calculate incorrectly versus other common date libraries and other external sources like various calculators on the web.

Below is a quick summary looking at the calendar year and ISO week-numbering years as calculated by different implementations for December 31st (one of the days where the ISO week-number year often differs from the calendar year). The yellow rows are examples of years where the date pipe seems to be incorrect.

<img width="500" alt="image" src="https://github.com/angular/angular/assets/110720/1c339380-25c3-441b-ac94-de815367c919">

This was sanity checked against independent sources on the web, such as:
* https://myweb.ecu.edu/mccartyr/isowdcal.html
* https://planetcalc.com/8540/?week=1&day=1&year=2024&date=2023-12-31%2000%3A00%3A00
* https://www.calendar-12.com/week_number

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-tdkfa6?file=src%2Fmain.ts

> Note that the reproduction uses the most current versions of packages at this time, including Angular 17.

### Please provide the exception or error you saw

```true
See description for examples of the issue.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.10
Node: 16.20.2
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 15.2.10
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.10
@angular-devkit/build-angular   15.2.10
@angular-devkit/core            15.2.10
@angular-devkit/schematics      13.3.11
@schematics/angular             15.2.10
rxjs                            7.8.1
typescript                      4.9.5
```

### Anything else?

Versions of other date libraries:
* date-fns@2.29.3
* luxon@3.4.4

As noted above, the reproduction in StackBlitz uses the most current versions of packages at this time, including Angular 17.

**Comment by chucknelson** [comment]
FYI added a link to a reproduction in StackBlitz - just the simple code that generates the table in the description screenshot.

**Comment by JeanMeche** [comment]
Quick investigation, this issue happens every year where Dec 31st is a sunday. 
Looks like there is a bug in our algorithm.

**Comment by JeanMeche** [comment]
It looks like to boil down to: What do we consider the start of the week ? 

Should it be sunday like in the US ? Or should it be monday like defined by ISO 8106. 
Angular currenlty implements the former. 

Repro : https://stackblitz.com/edit/angular-zcyztw?file=src%2Fmain.ts

**Comment by JeanMeche** [comment]
Also want to add about this topic. 

I believe the definition of the week numbering year / end of week if unclear. 

In the case of `date-fns`, it has 2 functions `getISOWeek()` and  `getWeek()`. The Former is `ISO` based while the latter is `Locale` based. 

In both cases Angular has a bug, the concept of week is neither locale based (the dedicated function doesn't rely on a locale or the dedicated function we have [https://angular.io/api/common/getLocaleFirstDayOfWeek](`getLocaleFirstDayOfWeek`)) nor ISO based (is assumes the week starts on Sunday).

**Comment by chucknelson** [comment]
Thanks @JeanMeche for looking into this.

Good catch on the "local" vs "ISO" week year - I didn't even notice local options in formatting and assumed week years was entirely from an ISO perspective.
Using the "local week numbering year" in both `date-fns` and `luxon` matches what `DatePipe` is doing if I use the US locale (which is where I am) - which makes sense considering you're saying Angular is using the US-type definition of "start of week = Sunday). Using other locales like French (👍), though, matches the ISO week year as expected, since the start of the week is Monday.

Not that I have much say in how you all proceed, but I guess it seems like Angular is all about honoring the locale of the browser/system, so maybe defaulting to "local" week behavior for day of week, week number and week-numbering year makes the most sense?

I guess it would also make sense to add formatting string options for the "local" vs "ISO" week items also?

**Comment by chucknelson** [comment]
Maybe I spoke to soon - it looks like there is still a discrepancy in how `date-fns` and `luxon` handle local week years versus `DatePipe`.

Added the local week year's to the repro link, and right in 2020 you can see they differ from the `DatePipe`...but I was thinking since `Angular` was assuming Sunday as the start of week, they'd match. 🤔  

<img width="639" alt="image" src="https://github.com/angular/angular/assets/110720/0fc196f9-f7da-47f9-9fff-6a41b477bc82">

**Comment by JeanMeche** [comment]
Well, change the locale and you'll be surprised to see other changes... 

`Settings.defaultLocale = "fr";`

Luxon returns 2020 where date-fns returns 2021.

**Comment by JeanMeche** [comment]
Yes, I have a pending PR at #53813, we'll check accross Google's codebase to see how breaking the fix is consideredd !
