### ISSUE TITLE
live example of Building a template-driven form is not completed

### ISSUE THREAD

**Issue by MichalSasula** [angular/angular#53823]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

I tried to read "Building a template-driven form" but there is no initial html template provided there is only final version and it is also not completed, there are TODOS and some haos. As a beginner I had problems to understand what was going there.

**Comment by JeanMeche** [comment]
Please have a looks at the new tutorials we have at https://angular.dev/tutorials/learn-angular ! 

This is the new official documentation site !
