### ISSUE TITLE
Broken link on @angular/router RunGuardsAndResolvers

### ISSUE THREAD

**Issue by pBouillon** [angular/angular#53821]
### Describe the problem that you experienced

The [`RunGuardsAndResolvers` docs page](https://angular.dev/api/router/RunGuardsAndResolvers) suggests the following link:
![image](https://github.com/angular/angular/assets/22640284/42f93c32-9550-490c-bd42-65161e75cea2)

Which redirects to: `https://angular.dev/api/router/RouterunGuardsAndResolvers`

That is not a proper page:
![image](https://github.com/angular/angular/assets/22640284/e5a07608-143d-40ef-99bb-0cb14f5fe328)

It seems that the JS Doc `@link` is not properly parsed:
![image](https://github.com/angular/angular/assets/22640284/aabe068d-520b-4835-bc4b-67fd7cd69d89)

### Enter the URL of the topic with the problem

https://angular.dev/api/router/RouterunGuardsAndResolvers

**Comment by JeanMeche** [comment]
Hi, Thansk for reporting this ! 

API references on adev needs some work and this is tracked by #52663.

**Comment by pBouillon** [comment]
> Hi, Thansk for reporting this ! This is a global issue with every inline link.
> 
> API references on adev needs some work and this is tracked by #52663.

Indeed I noticed it happened on `{@link ... }` but wasn't sure if this was local or global, thanks for the update!
