### ISSUE TITLE
docs: Repeated word `when`

### ISSUE THREAD

**Issue by zxywftr** [angular/angular#53827]
### Describe the problem that you experienced

![image](https://github.com/angular/angular/assets/70423865/a37aa8bb-3e28-4cb2-b705-a36767645446
<img width="861" alt="PixPin_2024-01-08_17-05-26" src="https://github.com/angular/angular/assets/70423865/a33bb9b3-d8bf-4850-8bfc-771f2ac52cf5">

### Enter the URL of the topic with the problem

https://angular.dev/guide/http/interceptors#configuring-interceptors

**Comment by zxywftr** [comment]
There is a misspelling of a word.  prefeching →  prefetch.

<img width="895" alt="PixPin_2024-01-08_17-08-25" src="https://github.com/angular/angular/assets/70423865/c6e21913-2c66-4b5e-91db-dd0113afa717">

**Comment by gleb-28** [comment]
added PR: https://github.com/angular/angular/pull/53828
