### ISSUE TITLE
Change detection not triggered when Signal.set() called from Observable subscription

### ISSUE THREAD

**Issue by joeskeen** [angular/angular#53841]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I have a component which interacts with an Observable at some point after its creation. I want any values coming out of the Observable to be set on a Signal. So this is how I set it up:

```ts
// any used here since the type doesn't really matter in this example
readonly position = signal<any>(undefined);

...

positionStrategy.positionChanges
      .pipe(tap(console.log))
      .subscribe((x) => this.position.set(x));
```

I display a value in the template derived from this signal, for example:

```html
<div>Position: {{position() | json}}</div>
```

When the Observable (`positionChanges`) emits a value, I see the value output to `console.log`, but in the template, nothing is rendered for `position()`. I would expect since the `position()` signal is referenced in the template, that whenever the value is changed, the template would re-render. I also tried referencing the value in a `computed`, but it still doesn't update.

I did finally find one way to get it to update. Put the following code into the `constructor`:

```ts
effect(() => this.position());
```

Then it renders to the view as expected:

```
Position: { "connectionPair": { "originX": "center", "overlayX": "center", "originY": "top", "overlayY": "bottom" }, "scrollableViewProperties": { "isOriginClipped": false, "isOriginOutsideView": false, "isOverlayClipped": false, "isOverlayOutsideView": false } }
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-hwrgyh?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.9
Node: 18.17.1
Package Manager: npm 9.8.1
OS: linux x64

Angular: 17.0.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.9
@angular-devkit/build-angular   17.0.9
@angular-devkit/core            17.0.9
@angular-devkit/schematics      17.0.9
@angular/cdk                    17.0.4
@angular/cli                    17.0.9
@schematics/angular             17.0.9
ng-packagr                      17.0.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JeanMeche** [comment]
`positionStrategy.positionChanges` emits outside the Angular zone. if you run the callback with ngZone.run it will fix the change detection issue.

**Comment by joeskeen** [comment]
OK, I understand running it in Zone, but I'm left a little confused. I was under the impression that the future of Angular we are working towards is being able to remove Zone completely, and use Signals instead. Am I misunderstanding? Will Signals trigger change detection in the future?

**Comment by JeanMeche** [comment]
Much like `markForCheck`, Signals in zone apps, do not trigger CD. 
[This demo](https://jeanmeche.github.io/angular-change-detection/) illustrates that well. 

In zoneless apps, with a new change detection scheduler, you can expect signals to trigger CD but we're not there yet !

**Comment by atscott** [comment]
I've been pushing for signal updates (along with other APIs) to always trigger change detection, even for zone-based applications and created a master tracking issue here: #53844
