### ISSUE TITLE
DI: new Provider(Foo, () => '') should work, instead throws

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#5384]
The following provider does not actually work:

```dart
const fooToken = const OpaqueToken('fooToken');

Injector.resolveAndCreate([
  new Provider(fooToken, useFactory: () => 'Bar')
]);
```

Instead, it only works if you change the signature to

```dart
new Provider(fooToken, useFactory: () => 'Bar', deps: const [])
```

Can the default be `deps: const []` instead of failing?

**Comment by PascalPrecht** [comment]
But this is a Dart-only problem, righ?

**Comment by vsavkin** [comment]
Closing because it is a duplicate of https://github.com/angular/angular/issues/4866
