### ISSUE TITLE
Eliminate the need for change detection when observing @Output properties in child components?

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular#53849]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler-cli, core

### Description

Currently if we are using / "Observing" `@Output` state in child components initialized in `AfterViewInit`we have to call `cdr.detectChanges` within the parent component like this:

```
ngAfterViewInit() {
    this.onGreetingChange.emit('Hola');
    this.cdr.detectChanges();
  }
```

However it's "Odd" that we have to do this.  It seems like the child component should be capable of detecting the state change without error since the state is "Observable".

I seems like a the semantics of `EventEmitter` and `BehaviorSubject` should be roughly the same, and so we should be able to call `EventEmitter.emit("SomeState")` in the `constructor` or `OnInit` ... etc. and have that state be picked up or observed by any client of the `Observable` ...

More details here:
https://stackoverflow.com/questions/77782679/observing-output-event-emitters-in-child-components

### Proposed solution

It seems like we should be able to do just this:

```
ngAfterViewInit() {
    this.onGreetingChange.emit('Hola');
 }
```

### Alternatives considered

A state service like:
https://www.npmjs.com/package/@fireflysemantics/slice

Or just a simple `BehaviorSubject`.

**Comment by JoostK** [comment]
There is some context missing here, as the `[greeting]="onGreetingChange | async"` binding should mark the component as dirty _if_ the output was reflected back as input. If that is _not_ the case, then this is working as desired, as `markForCheck` would be needed to reflect that internal data was changed.

**Comment by atscott** [comment]
This looks like it's generally covered by `model` inputs (two way bindings for signals) and using signals in general for state. I've updated the stackblitz example from the StackOverflow link to use a signal instead of `AsyncPipe`: https://stackblitz.com/edit/stackblitz-starters-vqvtg2

When signals are not used, you must follow the [unidirectional data flow](https://angular.io/guide/glossary#unidirectional-data-flow) rule.
