### ISSUE TITLE
No pipe found with name 'paginate'.

### ISSUE THREAD

**Issue by AHA-Technocrats** [angular/angular#53850]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

Yes

### Description

Actually , I am trying to use **ngx-pagination** in v17 but it's telling= _No pipe found with name 'paginate'.ngtsc(-998004)
blog-list.component.ts(21, 36): . I have registered **NgxPaginationModule** but still the same error which is perfectly working in v16

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).

**Comment by AHA-Technocrats** [comment]
Thank you so much @JeanMeche for your prompt response
