### ISSUE TITLE
Link missing

### ISSUE THREAD

**Issue by manimau01** [angular/angular#53870]
### Describe the problem that you experienced

On the page **https://angular.dev/tools/cli/setup-local#dependencies** the link to 'Angular's version compatibility (https://angular.dev/versions)' is missing. It produces Page Not Found page.

### Enter the URL of the topic with the problem

https://angular.dev/tools/cli/setup-local#dependencies

### Describe what you were looking for in the documentation

A link to angular and nodejs version compatibility

### Describe the actions that led you to experience the problem

Clicked the link and it produced Page Not Found page.

### Describe what you want to experience that would fix the problem

Go to the page with compatibility information.

### If this problem caused an exception or error, please paste it here

```true
Page Not Found
```

**Comment by JoostK** [comment]
Thanks for the report, this is a duplicate of https://github.com/angular/angular/issues/52562 and has since been addressed, but is pending a deployment.

**Comment by manimau01** [comment]
Oh, thanks for the information.
