### ISSUE TITLE
A pipe used in a host attribute is not found unless registered in parent component

### ISSUE THREAD

**Issue by mhelvens** [angular/angular#5388]
When I use a pipe in the context of a host attribute, as in the example below, it cannot be found even if I register it in that component:

```javascript
@Component({
  selector: '[with-parenthesized-text]',
  host: {
    '[inner-html]': ' myText | parenthesize ' // <-- (1) using pipe here
  },
  pipes: [Parenthesize], // <-- (2) but registering it here is not enough
  template: ``
})
```

It results in the error: `Cannot find pipe 'parenthesize'.` It seems the pipe needs to be registered in the parent component. I suspect this is not intended behavior.

Here is a simple [plunker](http://plnkr.co/edit/22hRgxTmzCP4rl4YEbjJ?p=preview) to illustrate the issue.

**Comment by QuentinFchx** [comment]
+1

**Comment by pkozlowski-opensource** [comment]
Pipes are not supported in host attributes any more. One should use a getter instead.

**Comment by QuentinFchx** [comment]
I might sound stupid, but why ?
Pipes are just here to transform data, why would it be forbidden to use them to pass data to the host component ?
