### ISSUE TITLE
Matrix params persist after navigation

### ISSUE THREAD

**Issue by thatcort** [angular/angular#53885]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

When navigating away from a URL that has matrix parameters, the router incorrectly appends those parameters to the end of the new URL.

For example for browser URL `https://blah.com/something/or/other;t=12;m=27` there is a component with a routerlink:

```<div [routerLink]="['/']" routerLinkActive="active" [queryParams]="{}">...</div>```

When I click the link the browser loads the root, which is then routed to another URL. The redirects are fine, but I end up at the new URL with the matrix parameters still there, e.g. `https://blah.com/another/place;t=12;m=27`

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.6
Node: 16.20.2
Package Manager: npm 8.19.4
OS: linux x64

Angular: 16.2.9
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.6
@angular-devkit/build-angular   16.2.6
@angular-devkit/core            16.2.6
@angular-devkit/schematics      16.2.6
@angular/cdk                    16.2.8
@angular/cli                    16.2.6
@angular/material               16.2.8
@schematics/angular             16.2.6
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
```

**Comment by atscott** [comment]
Could you please provide a reproduction? I was not able to reproduce this behavior myself. Here's my attempt: https://stackblitz.com/edit/stackblitz-starters-7qmzkz

**Comment by thatcort** [comment]
I found the bug in my code causing this issue. It's not an Angular bug.
