### ISSUE TITLE
Control flow @for with nested for and mandatory track

### ISSUE THREAD

**Issue by VincentClair** [angular/angular#53882]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

We have a list of static sections. For each of sections, we loop over a device properties to display their values.
As sections are statics, the nested loop is not re-rendered when we change input item.

```html
@for (section of deviceData.sections; track section.title) {
    <section>
      @for (property of section.properties; track deviceId + '.' + property) {
        <app-section-item ...></app-section-item>
      }
    </section>
  }
```

We have tried to change expression used by track :
```
track deviceId + '.' + section.title
```
but deviceId seems to be not taken into account.

As suggested in blog https://blog.angular-university.io/angular-for/#what-is-the-for-tracking-function, we also tried to just pass the name of a function, without argument (is is an error of the blog and video angular university ?) : 
```html
track itemId
```

```ts
itemId(index, section) {
   return section.title;
}
```

As suggested in doc, we tried full call of a function : 
```html
track itemId(deviceId, section)
```

```ts
itemId(deviceId, section) {
   return section.title;
}
```
but not working.

We tried with "this" to access to device : 
```html
track itemId(section)
```

```ts
itemId(section) {
   return this.deviceId +'.'+ section.title;
}
```
but re-rendered not working

Finally, we generate section id directly in store selector. But I don't understand why : 
- i need to generate an id on section so the inner list is re-rendered
- "this" is not resolved when calling a trackBy method
- any concat method is not resolved dynamically or take care of context and inputs changes

Is there something we missed ?
Thanks for your help.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.10
Node: 20.10.0
Package Manager: npm 10.2.3
OS: darwin arm64

Angular: 17.0.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
```

**Comment by JoostK** [comment]
Please share a runnable reproduction

**Comment by JoostK** [comment]
> As suggested in blog https://blog.angular-university.io/angular-for/#what-is-the-for-tracking-function, we also tried to just pass the name of a function, without argument (is is an error of the blog and video angular university ?) :

Yes, that is an error in their blog.

**Comment by VincentClair** [comment]
We have found our misunderstand of the trackBy : it acts as a "pointer" on web element, if i'm explained it well. It does not act as a "cache" on this element.

We changed onInit by onChanges of sub-element (<app-section-item> in my example) and it refreshes as expected.
It works before because it was a new element, when there is no trackBy method.
