### ISSUE TITLE
adev: no guide about lazy loading

### ISSUE THREAD

**Issue by jnizet** [angular/angular#53903]
### Describe the problem that you experienced

I couldn't find any guide about lazy loading

### Enter the URL of the topic with the problem

https://angular.dev/guide/routing/common-router-tasks#lazy-loading

### Describe what you were looking for in the documentation

The section tells the reader to "see the dedicated guide lazy loading". But it doesn't link to it, and I couldn't find any such dedicated guide.

### Describe the actions that led you to experience the problem

I was trying to help someone on the Angular discord by giving them a link to the documentation about lazy loading, and couldn't do it.

### Describe what you want to experience that would fix the problem

Have a link to a dedicated guide about lazy loading components and routes, without using NgModules.

**Comment by nikvarma** [comment]
ideally, it should have a link.

link for lazy-loading module
https://angular.dev/guide/ngmodules/lazy-loading#add-another-feature-module

**Comment by AnmolSirola** [comment]
@bencodezen Can I work on this issue.

**Comment by Narendherraj** [comment]
A PR has been opened to address this issue https://github.com/angular/angular/pull/54113
