### ISSUE TITLE
Provide a way to not watch some signals in an effect

### ISSUE THREAD

**Issue by jsgoupil** [angular/angular#53902]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

I am trying to do something like this.
```
effect(
  onCleanup => {
    // A signal that I need in the subscribe.
    const viewData = this.viewData();
    if (this.finalize() === '1') {
      const subscription = this.billingsService.getCurrent().subscribe(billing => {
        this.viewData.set({
          ...viewData,
          billing
        });
      });

      onCleanup(() => subscription.unsubscribe());
    }
  },
  { allowSignalWrites: true }
);
```

However, this will loop pretty much forever because the viewData() will trigger a re-entering inside the `effect`.

In React, when we have such effect, we indicate if we want to "watch" some variables. I don't think this is possible in Angular at moment. If this is not planned, maybe a documentation about how to achieve this.

### Proposed solution

I have to move the signal inside the subscribe and everything works... but it's a bit a hidden hack and I feel you might break this in the future?

```
effect(
  onCleanup => {
    if (this.finalize() === '1') {
      const subscription = this.billingsService.getCurrent().subscribe(billing => {
        const viewData = this.viewData();
        this.viewData.set({
          ...viewData,
          billing
        });
      });

      onCleanup(() => subscription.unsubscribe());
    }
  },
  { allowSignalWrites: true }
);
```

### Alternatives considered

Have a way to say to not watch some signals.

**Comment by alxhub** [comment]
You want `untracked`: https://angular.io/guide/signals#reading-without-tracking-dependencies :)
