### ISSUE TITLE
Tour of Heroes application and tutorial no working with Angular 17

### ISSUE THREAD

**Issue by dineshsiprtc** [angular/angular#53905]
### Describe the problem that you experienced

I have tried Tour of Heroes  on Angular 17 and its not working

### Enter the URL of the topic with the problem

https://angular.io/tutorial/tour-of-heroes/toh-pt1

### Describe what you were looking for in the documentation

app.module.ts has been removed form Angular 17 and ngModel should work. but after following step getting issue

### Describe the actions that led you to experience the problem

⠼ Building...
✘ [ERROR] NG8001: 'app-heroes' is not a known element:
1. If 'app-heroes' is an Angular component, then verify that it is included in the '@Component.imports' of this component.
2. If 'app-heroes' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@Component.schemas' of this component to suppress this message. [plugin angular-compiler]

    src/app/app.component.html:2:0:
      2 │ <app-heroes></app-heroes>
        ╵ ~~~~~~~~~~~~

  Error occurs in the template of component AppComponent.

    src/app/app.component.ts:9:15:
      9 │   templateUrl: './app.component.html',
        ╵                ~~~~~~~~~~~~~~~~~~~~~~

### Describe what you want to experience that would fix the problem

unable to run application

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/150108336/53e66932-916a-4266-88db-fbd11cf2085e)

**Comment by JoostK** [comment]
Thanks, this is being addressed in #51577

**Comment by DineshGuptaa** [comment]
Thanks for your response. I am unable to understand what discussion is going on. I just started via tutorial and not working when moving through step by steps. Please help me what need to to for this or provide me link.

**Comment by MelinaLanvermann** [comment]
I think I had a similar problem, in the beginning of the tutorial it says you're supposed to generate the new project with '--no-standalone', but the tutorial itself is working with standalone = true. It worked for me after generating the project new without the '--no-standalone' option and importing the components in the imports-array of the parent-component, where needed

**Comment by bencodezen** [comment]
Apologies for the confusion. We're in the midst of updating our docs and there's a bit of friction right now between the two doc sites.

For those looking to go through tutorials on Angular 17+, we recommend going through the new tutorials on https://angular.dev/tutorials.
