### ISSUE TITLE
Angular.dev tutorial uses `fetch` for HTTP requests, but this doesn't seem to work well with Interceptors

### ISSUE THREAD

**Issue by pythonweb2** [angular/angular#53911]
### Describe the problem that you experienced

In the new tutorial for Angular 17 on https://angular.dev/, the _Build your first Angular app_ tutorial uses the `fetch` api in the _Add HTTP Communication_ section. However, as I am looking into building things like interceptors into my app, they don't seem to play well with the fetch API.

Could a note be added about the downsides of using the fetch API? Or, if I am missing something about interceptors (and other features that are included with the HttpClient) can notes be added to the tutorial about how to use these features?

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app/http

### Describe what you were looking for in the documentation

More insight on the pros/cons of the `fetch` api vs `HttpClient`

### Describe the actions that led you to experience the problem

Following the tutorial

### Describe what you want to experience that would fix the problem

Better documentation

**Comment by JeanMeche** [comment]
Interceptors should work perfectly with fetch. 
Feel free to drop a stackblitz repro of your issue !

**Comment by JoostK** [comment]
The docs suggest using native `fetch`, not the `fetch` backend for ` HttpClient`. I think it's a fair point to have more info on the distinction.

And indeed, interceptors are specific to using `HttpClient`.
