### ISSUE TITLE
aio, adev: provideAnimationsAsync does not appear in the reference documentation

### ISSUE THREAD

**Issue by jnizet** [angular/angular#53912]
### Describe the problem that you experienced

In [angular.io](https://angular.io/api), and in [angular.dev](https://angular.dev/api), the `provideAnimationsAsync` function doesn't appear. And the link that points to it in the [Animations guide on adev](https://angular.dev/guide/animations) leads to a 404.

### Enter the URL of the topic with the problem

https://angular.io/api, https://angular.dev/api

### Describe what you were looking for in the documentation

The reference documentation of `provideAnimationsAsync`

### Describe the actions that led you to experience the problem

I tried to help someone on the Angular discord by pointing to the documentation

**Comment by JeanMeche** [comment]
Hi ! 
I've opened #53914 to fixe the issue for AIO and for ADEV we are already tracking this as part of #52663.
