### ISSUE TITLE
Crazy bootstrap phase error when injecting $rootScope and assigning to value in service

### ISSUE THREAD

**Issue by vance** [angular/angular#5392]
Not sure if this is an ng issue or not.... Maybe it is user error =) The entire details are preserved here: http://stackoverflow.com/questions/33814040/how-do-i-inject-scope-using-typescript-static-injector-pattern/33815440#33815440
```
10angular.js:12314 Error: [ng:cpws] Can't copy! Making copies of Window or Scope instances is not supported. 
http://errors.angularjs.org/1.4.1/ng/cpws
```
Injecting $scope or $rootScope and assigning to a local reference property seems to work fine, in a controller but not a service. I also notice that you cannot import $scope into a service at all, perhaps the angular team meant to also prevent injecting $rootScope but neglected to do so.

The error itself is baffling; my best conjecture is that there is an artifact from compilation (deep in the bowels of Angular) wherein instantiation of the service tries to deep copy the $rootScope property instead of shallow copy if and only if it is assigned to property on the service object.

**Comment by ericmartinezr** [comment]
Hey @vance this repo is for ng2, you are looking for this one https://github.com/angular/angular.js :+1:
