### ISSUE TITLE
Page not found: https://angular.dev/cli/commands

### ISSUE THREAD

**Issue by aamirmukaram** [angular/angular#53924]
### Describe the problem that you experienced

On clicking learn more in the command reference section on this URL: https://angular.dev/tools/cli

Page not found appears

<img width="522" alt="image" src="https://github.com/angular/angular/assets/12094879/1ea3a78d-3b79-457f-b627-e16b55968ebc">

### Enter the URL of the topic with the problem

https://angular.dev/tools/cli

### Describe what you were looking for in the documentation

Angular CLI commands

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52549  and is pending deployement on our side !
