### ISSUE TITLE
Angular CLI page not found

### ISSUE THREAD

**Issue by Omiced** [angular/angular#53926]
### Describe the problem that you experienced

Al hacer click en el vinculo para la documentacion de los comandos del angular cli me mando un not found

### Enter the URL of the topic with the problem

https://angular.dev/cli/commands

### Describe what you were looking for in the documentation

CLI commands

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52549  and is pending deployement on our side !
