### ISSUE TITLE
Clean / reliably possibility to detect template issues

### ISSUE THREAD

**Issue by angelaki** [angular/angular#53932]
### Description

If I'm not mistaken, there is no clean solution to determine runtime template errors (I tried to find a solution via [Stackoverflow](https://stackoverflow.com/questions/77821169/angular-how-to-detect-equal-template-errors/77821381)). I can only check the stack for keywords and compare two errors' stacks to tell they are equal.

I'm using a custom error handler to show runtime errors in the client. If the error is caused by the template (e.g. null pointer reference), I end up in an endless loop because the dialog (mat snack) triggers the templating engine again.

### Proposed solution

Mark the thrown error as a template error (or create a custom error class to tell it apart by its type) and pass it some kind of Id that identifies the error.

### Alternatives considered

Maybe there already is a solution for this? A link to the code handling template errors would be great.

**Comment by angelaki** [comment]
Just found the `RuntimeError` class with it's enum types. So way to go would be: wrap the error in a runtime error. Easy as that, isn't it?

**Comment by angelaki** [comment]
Hey @dylhunn, could you please let me know if a PR for this would be welcome / have serious chance in a fast merging? Imho this is a pretty interesting one! And almost costs no effort! But touches some core enums - so I'm not quite sure if a PR would be considered?

**Comment by JoostK** [comment]
As noted in https://github.com/angular/angular/pull/54857#issuecomment-2374291141 this isn't the direction we'd want to take regarding errors that occur during template execution.

**Comment by angelaki** [comment]
Hey @JoostK, too bad but never mind! Any alternatives planed? Or no possibility to detect template errors in runtime planned?

**Comment by JoostK** [comment]
No, nothing in particular. Template errors are reported to the `ErrorHandler` as you mention and there's no source information there. Note that there is an open issue for tracking the infinite change detection behavior in #17010.

**Comment by angelaki** [comment]
@JoostK oh wow. Don't get me wrong, but ... this issue is like 7 years old? I served a solution on a silver platter and you decided to drop it because of negative impacts? Many errors are already handled the exact some way! So what's wrong with one, handlung 100+ already the same way? And even no difference, if no template-errors occur?

No offense! Just asking! Don't get me wrong :) Was just hoping for a solution and the answer is: check this 7 year old issue 👎

**Comment by JoostK** [comment]
I don't think it's a solution to that problem, wrapping the exception would still result in initiating a new change detection cycle. I'm linking #17010 here because you mentioned this behavior in the issue text.

**Comment by angelaki** [comment]
Oh sorry, wasn't aware of that! Everytime an Exception (a stacktrace) is created, a change detection cycle starts? So yeah, in this case we'd still have an infinite loop.

**Comment by JoostK** [comment]
Not quite; but if the change detection cycle that was underway has scheduled a new change detection cycle (e.g. to update some animated state or used `Promise.resolve` to initiate a secondary CD cycle to avoid ExpressionChangedAfterItHasBeenChecked) then there will be a subsequent CD execution. This will try to evaluate the template once again, retriggering the error. If the error is shown in a snackbar and if that snackbar has a tendency to request a new CD cycle, you have arrived at the never-ending CD interaction.

**Comment by angelaki** [comment]
Yeah, ok - that's totally right. But that's actually what I need it for! Right now every error gets shown in a snack. So a template-error in runtime gets the application stuck in an infinit loop! If I could tell template- and other errors apart I would just push template errors in the console. Sure that's still not "super satisfying" for the user. But al least the broweser won't get stuck in a loop. Right now I try to detect if the current error already existed in the last errors thrown.
