### ISSUE TITLE
Cannot use Mocha to write angular2 tests

### ISSUE THREAD

**Issue by rosendi** [angular/angular#5395]
If I use Mocha as a testing framework I'm getting the error message:

```
/Projects/firebase-pipes/node_modules/angular2/typings/jasmine/jasmine.d.ts(13,18): error TS2300: Duplicate identifier 'it'.
/Projects/firebase-pipes/node_modules/angular2/typings/jasmine/jasmine.d.ts(14,18): error TS2300: Duplicate identifier 'it'.
/Projects/firebase-pipes/node_modules/angular2/typings/jasmine/jasmine.d.ts(17,18): error TS2300: Duplicate identifier 'xit'.
/Projects/firebase-pipes/node_modules/angular2/typings/jasmine/jasmine.d.ts(18,18): error TS2300: Duplicate identifier 'xit'.
typings/mocha/mocha.d.ts(37,13): error TS2300: Duplicate identifier 'describe'.
typings/mocha/mocha.d.ts(38,13): error TS2300: Duplicate identifier 'xdescribe'.
typings/mocha/mocha.d.ts(43,13): error TS2300: Duplicate identifier 'it'.
typings/mocha/mocha.d.ts(44,13): error TS2300: Duplicate identifier 'xit'.
```
Is it necessary to propagate Angular with Jasmine typings?

https://github.com/angular/angular/blob/master/modules/angular2/manual_typings/globals-es6.d.ts#L9.

**Comment by dsebastien** [comment]
+1, it would be nice to be able to choose between mocha and jasmine :)

**Comment by manland** [comment]
:+1:

**Comment by yizhan** [comment]
:+1 
We are running Angular 1 and Angular 2 at same time, but we can not do testing at same time.

We started Angular 1 with Jasmine1 testing, and now Angular 2 has built in with Jasmine 2 testing right?
It seems have same typing issue.

**Comment by dsebastien** [comment]
@robwormald Any idea how we could move forward without having to fiddle with typings files manually? Or is this resolved by a48 or going to be with a49?

**Comment by rosendi** [comment]
@dsebastien Can you confirm that mocha plays nicely with angular 2 (I switched to jasmine)? Testing library wraps jasmine methods and in the angularconnect session @juliemr said that currently it doesn't support mocha and other testing frameworks.

**Comment by juliemr** [comment]
That's correct, currently, only Jasmine 2 is fully supported. I'll be working on making this more generic once testing works great with Jasmine 2.

**Comment by dsebastien** [comment]
No I can't, I was just about to try it out. Good to know that it does not work, thanks for the info! ;-)

**Comment by laco0416** [comment]
:+1:

**Comment by japhar81** [comment]
I'm sure @juliemr will let us know when this is officially supported, but in the meantime, I've found two ways to make it work pretty well -- writeup here: http://www.codeitall.com/?p=144

**Comment by laco0416** [comment]
In beta.2, this issue looks solved to me.

https://github.com/angular/angular/commit/a4b5cb837682ce61f8c07eabd7ae8c4dc3ba80a7

**Comment by japhar81** [comment]
Typings do appear fixed, but the tests still fail under mocha -- i guess that's expected :)

**Comment by laco0416** [comment]
@juliemr Any plans to enable to use Mocha or other testing frameworks with "angular2/testing" ?

I'll be happy if that module will separate to "angular2/testing/common" and "angualr2/testing/jasmine"

**Comment by wesleycho** [comment]
This should be fairly easy to create separate adapters - basically one would need to duplicate the logic in https://github.com/angular/angular/blob/master/modules/%40angular/core/testing/testing.ts but for the specific platform one chooses. The logic is thin, so this is a pretty accessible task IMO.

**Comment by juliemr** [comment]
This is now possible in RC4.

**Comment by jakeNiemiec** [comment]
👌 https://github.com/angular/angular/pull/9562
