### ISSUE TITLE
Signal inputs not getting highlighted on mouse over in element

### ISSUE THREAD

**Issue by sheikalthaf** [angular/angular#53967]
### Which @angular/* package(s) are the source of the bug?

language-service

### Is this a regression?

No

### Description

Signal inputs are not getting highlighted on mouseover and also it is not navigating to the source on ctrl click on it

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.1.0
Node: 18.16.0
Package Manager: pnpm 8.7.0
OS: darwin arm64

Angular: 17.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.0
@angular-devkit/build-angular   17.1.0
@angular-devkit/core            17.1.0
@angular-devkit/schematics      17.1.0
@angular/fire                   16.0.0
@angular/pwa                    17.0.1
@schematics/angular             17.1.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JoostK** [comment]
What version of the Angular extension are you using?

**Comment by Nividica** [comment]
Also ran into this on ALS Version `17.1.0`
Attempting to go to definition via F12 results in `No definition found for 'name'`, and no tooltip on hover.
![image](https://github.com/angular/angular/assets/1585989/8121ce84-6b47-4ec4-84fe-34af0d438623)

However, attempting to assign an incorrect type does yield the expected error.
![image](https://github.com/angular/angular/assets/1585989/8d0bad92-3800-424e-8c20-1bdb48e03f1d)

**Comment by Enngage** [comment]
We see the same behavior after upgrading to `17.1.0` as well.

**Comment by devversion** [comment]
This should be resolved as of recent language service releases.
