### ISSUE TITLE
untracked enables devs to skip effect { allowSignalWrites: true }

### ISSUE THREAD

**Issue by eneajaho** [angular/angular#53986]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

In the docs the `untracked` function says that it is used to read a function not in a reactive context, so this way it's not registered as a dependency on the signals graph. 

But, it looks like this also allows us to not run the set/update method in a reactive context too. 

So, this code works fine: 
```ts
  count = signal(0);
  logs = signal<number[]>([]);

  constructor() {
    effect(
      () => {
        const count = this.count();
        this.logs.update((x) => [...x, count]);
      },
      { allowSignalWrites: true }
    );
  }
```

This other one works fine too: 

```ts
  count = signal(0);
  logs = signal<number[]>([]);

  constructor() {
    effect(() => {
        const count = this.count();
        untracked(() => this.logs.update((x) => [...x, count]));
     });
  }
```

Is this a feature or a bug 😄? 

Should I send a PR to update the docs if it's an undocumented feature? 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-apaoat?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fmain.ts&title=Angular%20Starter

**Comment by pkozlowski-opensource** [comment]
`untracked` removes the reactive context and as a consequence it also removes some checks / restrictions. This works as intended currently but we might revisit it in the feature. I'm not sure if updating the docs is the best next steps since this is more of a quirk / side-effect of implementation choices rather than something that was designed explicitly.

**Comment by zip-fa** [comment]
Please dont change this behavior🙏🏻
It’s very helpful in some conditions

**Comment by RobbyRabbitman** [comment]
The [async pipe](https://github.com/angular/angular/blob/main/packages/common/src/pipes/async_pipe.ts) uses it aswell for exactly that reason.

**Comment by JeanMeche** [comment]
As discussed within the team, this is the designed behavior and we'd like to keep it that way !
