### ISSUE TITLE
Typo error word mentioned as boostrapApplication  instead of bootstrapApplication

### ISSUE THREAD

**Issue by admister** [angular/angular#54003]
### Describe the problem that you experienced

the code on this page has typo error
correct word is bootstrapApplication instead of boostrapApplication 

### Enter the URL of the topic with the problem

https://angular.dev/guide/http/setup#providing-httpclient-through-dependency-injection

### Describe what you were looking for in the documentation

i was looking for httpClient documentation

### Describe the actions that led you to experience the problem

i copied the code in the code editor and realized the typo error

### Describe what you want to experience that would fix the problem

just need to correct the name of the Helper function , change to correct spelling

**Comment by JoostK** [comment]
Thanks for the report! 👻 This was fixed in https://github.com/angular/angular/pull/52803 and pending deployment.
