### ISSUE TITLE
Standalone Component pattern forRoot & forFeature

### ISSUE THREAD

**Issue by vladyslavom** [angular/angular#54004]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Use forFeature/forRoot patterns to create modules return typeError. It only exists in a standalone component. When I do the same in NgModule everything works correctly. I'm testing this for RouterModule, same error

### Please provide a link to a minimal reproduction of the bug

https://bitbucket.org/color-commerce/forrootforfeaturepatternsstandalonecomponent17.1.0/src/main/

### Please provide the exception or error you saw

```true
TS2322: Type ModuleWithProviders<TestModule> is not assignable to type readonly any[] | Type<any>
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.1.0
Node: 18.14.2
Package Manager: npm 9.5.0
OS: darwin x64

Angular: 17.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.0
@angular-devkit/build-angular   17.1.0
@angular-devkit/core            17.1.0
@angular-devkit/schematics      17.1.0
@schematics/angular             17.1.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

### Anything else?

NgModule.imports?: (any[] | Type<any> | ModuleWithProviders<{}>)[] | undefined
Component.imports?: (readonly any[] | Type<any>)[] | undefined

**Comment by JoostK** [comment]
This is an explicit design choice for standalone components: `ModuleWithProviders` is a concept to include dynamic providers in _module injectors_, whereas components do not provide a module injector themselves (only a component injector, a.k.a. node injector). [Please see the docs for details](https://angular.io/guide/standalone-components#dependency-injection-and-injectors-hierarchy).
