### ISSUE TITLE
Checkboxes lose state when initialized by localStorage, yet model remains correct

### ISSUE THREAD

**Issue by jeremybradbury** [angular/angular#5400]
This will create a value in LS (which i have also tested non-programmatically... editing chrome Resources), then initialize the controller. When grabbing true from local storage it doesn't check the checkbox. Yet the button which is based on the same model is visible. And the console log is true.

http://jsfiddle.net/vgzxw7mt/1/

I even tried using "true" and "false" as strings:

http://jsfiddle.net/vgzxw7mt/2/

Also adding ng-checked to the same value as the model doesn't help because it makes the value always checked:

http://jsfiddle.net/vgzxw7mt/3/

I just want to save some checkbox values to localStorage and have my app remember which boxes are checked. Looks like I am going to have code a unique and creative solution for these broken boxes. 

Am I completely missing something here? Shouldn't this be fairly simple to implement?

If not, can/will this be fixed in the future?

**Comment by robwormald** [comment]
See http://plnkr.co/edit/bnoplg2dvPGJ5BLFlurE?p=preview for a working solution. Also, this is the Angular2 repo, so if you have further issues, please open it on https://github.com/angular/angular.js
