### ISSUE TITLE
angular input isn't working with query params

### ISSUE THREAD

**Issue by robertIsaac** [angular/angular#54010]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

query param doesn't get binded to component input

I'm not sure if that's a bug or a feature

but I read again multiple sources include the official [Angular blog post](https://blog.angular.io/angular-v16-is-here-4d7a28ec680d#398f) and they all mention that query param is supported, but I find it only work with path params

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-c6zucc?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
the `the.query` is undefined, while it should equal the other `console.log`
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.0
Node: 20.11.0
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.0
@angular-devkit/build-angular   17.1.0
@angular-devkit/core            17.1.0
@angular-devkit/schematics      17.1.0
@schematics/angular             17.1.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by JeanMeche** [comment]
This is only true for components defined in the routes. Your example is a bare root component.

**Comment by robertIsaac** [comment]
> `withComponentInputBinding` works for components defined in the routes (and rendering via `router-outlet`). Your example is a bare root component.

well in my real project it's used in a component defined in the route
but after updating my reproduction example it works now, so now I'm back to square 1
in my real project
```
  // this works
  protected readonly query2 = toSignal(
    inject(ActivatedRoute).queryParamMap.pipe(
      map((params) => params.get('query')),
    ),
  );
  // this doesn't work
  protected readonly query = input<string>();
```

and I can't understand why

**Comment by robertIsaac** [comment]
after further investigating I'm able to reproduce it
https://stackblitz.com/edit/stackblitz-starters-c6zucc?file=src%2Fhome%2Fhome.component.ts
the thing is that, if I'm using a nested component, it won't work
I guess I have to pass it from the parent component or to use `ActivatedRoute` instead
can I switch this to be a feature request, that all nested components to have access to the params as inputs?

**Comment by JoostK** [comment]
> that all nested components to have access to the params as inputs?

This isn't feasible, as the router doesn't control the rendering of those components. It would also introduce complexity around which binding would take precedence, as well as making it more unclear where an input's value could originate from (IMO, `withComponentInputBinding` is already too implicit in where those input receive their values from).

You could make this work using a function that represents a `Signal` (or keep the `Observable` if you prefer):

```ts

function routeParameter(name: string): Signal<string | null> {
  const value = inject(ActivatedRoute).queryParamMap.pipe(map((params) => params.get(name)));
  return toSignal(value, { requireSync: true });
}
```

This makes it very explicit where the value comes from and doesn't require the router to manage the component's inputs.

**Comment by robertIsaac** [comment]
> > that all nested components to have access to the params as inputs?
> 
> This isn't feasible, as the router doesn't control the rendering of those components. It would also introduce complexity around which binding would take precedence, as well as making it more unclear where an input's value could originate from (IMO, `withComponentInputBinding` is already too implicit in where those input receive their values from).
> 
> You could make this work using a function that represents a `Signal` (or keep the `Observable` if you prefer):
> 
> ```ts
> function routeParameter(name: string): Signal<string | null> {
>   const value = inject(ActivatedRoute).queryParamMap.pipe(map((params) => params.get(name)));
>   return toSignal(value, { requireSync: true });
> }
> ```
> 
> This makes it very explicit where the value comes from and doesn't require the router to manage the component's inputs.

okay thanks for your feedback
this is a new world for me, and I'm sure with time I will get used to the way things work
