### ISSUE TITLE
Declare private members as private instead of using /** internal */ comment

### ISSUE THREAD

**Issue by martinmcwhorter** [angular/angular#5402]
I have noticed in many places in the code base private members are underscore prefixed and marked with an /** internal */ comment instead of being marked with the idiomatic TypeScript `private` declaration. 

Is there a reason for this? Possibly Dart transformation? Documentation generation? 

Would a pull request be accepted to clean these up?

**Comment by nesukun** [comment]
Maybe they are intended as *protected*

**Comment by martinmcwhorter** [comment]
Ok. I realized this is a TypeScript option to prevent the member from being added to the definition. Like the `internal` keyword in C#. It is public within Ng2 but private to all consumers.
