### ISSUE TITLE
standalone misspelt 'standaone' in angular.dev tutorial

### ISSUE THREAD

**Issue by carl-neuriot** [angular/angular#54033]
### Describe the problem that you experienced

In the [custom pipes](https://angular.dev/tutorials/learn-angular/create-a-pipe) section of the tutorial on angular.dev, the code in step 1 misspells standalone as 'standaone'.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/create-a-pipe

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52677 and is pending deployement on our side !
