### ISSUE TITLE
HTML parser incorrectly assumes that <tr> must be inside <tbody>

### ISSUE THREAD

**Issue by tiziano88** [angular/angular#5403]
See https://github.com/angular/angular/blob/adb87562bba0e5acce7d22e18ee92df460b486b3/modules/angular2/src/compiler/html_tags.ts#L54 . In reality, `<tr>` may be inside `<thead>` instead, but the current version transforms

```html
<table>
  <thead>
    <tr>...</tr>
  </thead>
</table>
```

into

```html
<table>
  <thead>
    <tbody>
      <tr>...</tr>
    </tbody>
  </thead>
</table>
```

which does not makes sense.

**Comment by todoubaba** [comment]
+1

Please fix this ASAP, alpha.47 breaks many table app.

**Comment by stavro** [comment]
+1 This is causing some difficulties for me as well
