### ISSUE TITLE
Assets provider

### ISSUE THREAD

**Issue by michaelkrog** [angular/angular#54046]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

Loading asset file content programmatically works differently across SSR, pre-rendering and client side rendering.

For example, if I want to render markdown from the assets folder and I want to load the markdown in a Components ngOnInit, I won't be able to reach the file during pre-rendering. But it works fine in in client side rendering.

```
ngOnInit() {
  this.data = await firstValueFrom(this.http.get('/assets/test.md', {responseType: 'text'}));   
}

<markdown [data]="data"></markdown>
```

### Proposed solution

I propose a form of a provider that can retrieve asset file content relative to the app no matter which rendering type is being used.

## Interface suggestion
```
type File = {name: string, type: 'File' | 'Folder'};

interface AssetProvider {
  readFile(path: string): Promise<Blob>;
  listFiles(path: string): Promise<File[]>;
}
```

## Server-side rendering
When rendering is performed runtime on the server, the provider should provide files directly from the filesystem using node's fs-package and be dynamic so that changes to the asset folder are reflected in the asset provider at runtime.

## Client-side rendering
When rendering is done client side, assets can be provided by resolving via the Http-client. For the purpose of listing files/directories, a type of index file could be generated in the assets folders (one file on each).

**Index file example (.ng-index)**
```
{
  "files": ["test.md"],
  "folders": ["my-first-folder", "my-second-folder"]
}
```

## Prerender
When the application is pre-rendered, the asset provider for server-side rendering should be used during rendering. After rendering and during runtime, assets can be resolved as in Client-side rendering.

### Alternatives considered

I have looked through many examples that tries to work around the lack of a unified asset provider by creating fx. httpinterceptors for resolving files, booting up web servers during prerendering for loading files remotely and more.

All of them are hacks that's stems from the fact, that there are no unified way of resolving assets during rendering.

**Comment by alan-agius4** [comment]
Hi @michaelkrog, 

The above mentioned approach `this.http.get('/assets/test.md', {responseType: 'text'})` works when using prerendering in version 17 when using the HTTP client fetch backend.
