### ISSUE TITLE
Subscribing to a ChildRouter has no effect

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#5405]
`ChildRouter` is a `Router` and thus has a subscribe method. However, all navigate requests are forwarded to the parent, the ChildRouter's EventEmitter is never used and all subscribed methods remain uncalled in case of a route change.

**Comment by btford** [comment]
:+1:  We need this feature for an app at Google as well.

**Comment by tiziano88** [comment]
Note that, possibly related, using the `onActivate` or `onReuse` hooks results in the corresponding methods being called, but the instructions received by them not having any params set, so currently there is literally no way of getting parameters of non-root routes AFAICT.

Personally I feel this should be treated as P1 (and effort is possibly more than one day), but I'll leave that to you to decide.

**Comment by btford** [comment]
(effort: day means "on the order of days")

I'm fine with bumping this to P1.

**Comment by Namek** [comment]
+1. Wanted to use as a DIRTY workaround for not having access to child component's `@Output` emitter. Related to #5875

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router robust.

It doesn't look like the issue makes sense in the context of the new router because it does not have the concept of child routers. 

Closing this issue.

**Comment by Tragetaschen** [comment]
I agree :-)
