### ISSUE TITLE
No image for @for + @if Select component example

### ISSUE THREAD

**Issue by Serpentarius13** [angular/angular#54061]
### Describe the problem that you experienced

At https://angular.dev/guide/directives#hosting-a-directive-without-a-dom-element section, there is 404 image link for example of ```  @for and @if directives ```

### Enter the URL of the topic with the problem

https://angular.dev/guide/directives#hosting-a-directive-without-a-dom-element

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/112726943/780092d8-2793-4267-b92f-ec601a25a8da)

### Provide any additional information here in as much as detail as you can

```true
I believe there is just no file for this yet here: https://github.com/angular/angular/tree/main/aio/content/images/guide/built-in-directives
```

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #53048 and is pending deployement on our side !
