### ISSUE TITLE
Throw an error when a zone is nested within another zone

### ISSUE THREAD

**Issue by adamdbradley** [angular/angular#5406]
While it's possible to have a zone running from within another zone, it's more than likely that there's something wrong with the app's or ng2's code. This would be similar to the `$digest already in progress` error seen in 1x.

**Comment by vicb** [comment]
@adamdbradley could you expand on your use case ?

a `setTimeout` callback actually runs in a child zone of the zone where `setTimeout` was called (the same goes for event handlers, microtasks, ...)

**Comment by mhevery** [comment]
I think the issue is that we are cause double digest. I am not sure why it is happening, but I know how to reproduce this.

**Comment by mhevery** [comment]
Blocked on new Zone implementation.

**Comment by IgorMinar** [comment]
this was resolved with zone.js 0.6
