### ISSUE TITLE
Syntax correction: Custom events with outputs section 

### ISSUE THREAD

**Issue by govindappaarun** [angular/angular#54064]
### Describe the problem that you experienced

I see a correction in the example given at this section https://angular.dev/guide/components/outputs#customizing-output-names
where in example its decorated as Input parameter for valueChanged, as its supposed to be Output 

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/outputs#customizing-output-names

**Comment by TarsisDragomir** [comment]
Seems to be fixed 2 months ago => https://github.com/angular/angular/blame/main/adev/src/content/guide/components/outputs.md

But it's not live yet, not sure when that is planned
