### ISSUE TITLE
Broken link in HTTP overview page

### ISSUE THREAD

**Issue by geertjansen** [angular/angular#54067]
### Describe the problem that you experienced

Right under the `What's next` heading is a button `Making HTTP requests` that leads to a page not found.

### Enter the URL of the topic with the problem

https://angular.dev/guide/http

### Describe what you were looking for in the documentation

HTTP client

### Describe the actions that led you to experience the problem

I did a global search for the HTTP keyword

### Describe what you want to experience that would fix the problem

The button should link to the correct page.

### Provide any additional information here in as much as detail as you can

```true
The link is broken because of a typo and can be corrected like this:

- https://angular.dev/guide/http/making-requets
+ https://angular.dev/guide/http/making-requests
```

**Comment by JoostK** [comment]
Thanks for the report, this has been fixed by https://github.com/angular/angular/pull/52541 and is pending deployment.
