### ISSUE TITLE
Reactive forms - cursor jumping to the end of the input box on form control update.

### ISSUE THREAD

**Issue by goncard** [angular/angular#54073]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

I created a simple form that has a single input text. In my app.component I'm subscribing the valueChanges observable and calling a method that calls the formControl setValue() method to update the formControl value with the current value uppercased.
**Cursor is jumping to the end of the input box after typing lowercase characters in the middle of the text.**

Stackblitz link is attached.

How to reproduce:
- Type any text on the input.
- Type any lowercase character in the middle of the previously typed text.
- Cursor will jump to the end of the input box only when we type a lowercase character. The bug doesn't happen when we type numbers or a uppercase character.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-zrs5kt?file=src%2Fapp%2Fapp.component.ts

**Comment by JeanMeche** [comment]
You're changing the value of the input, this is a native browser behavior. This is definitely not a recommanded way to uppercase an input. 

@spierala is suggesting a better alternative [on Stackoverflow](https://stackoverflow.com/a/74111888/884123) with a custom Value Accessor. 

See a related demo : https://stackblitz.com/edit/angular-input-field-to-accept-only-numbers-czivy3?file=src%2Fapp%2Fto-uppercase.directive.ts

**Comment by goncard** [comment]
> You're changing the value of the input, this is a native browser behavior. This is definitely not a recommanded way to uppercase an input.
> 
> @spierala is suggesting a better alternative [on Stackoverflow](https://stackoverflow.com/a/74111888/884123) with a custom Value Accessor.
> 
> See a related demo : https://stackblitz.com/edit/angular-input-field-to-accept-only-numbers-czivy3?file=src%2Fapp%2Fto-uppercase.directive.ts

Absolutely, thanks for your comment. Sorry for the not a bug issue 😅, I wasn't aware it was a native browser behaviour.
