### ISSUE TITLE
In local npm test working fine but in jenkins giving below error, please help here.

### ISSUE THREAD

**Issue by DJ-991** [angular/angular#54089]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler, Don't known / other

### Is this a regression?

Yes

### Description

Getting this issue in pipeline while running in npm test phase in build

### Please provide the exception or error you saw

```true
![image](https://github.com/angular/angular/assets/21131291/e13dfe4c-5287-49d5-ab15-1e412058a6ff)

jenkins config:
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 11.2.7
Node: 16.13.1
OS: win32 x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes
```

### Anything else?

![image](https://github.com/angular/angular/assets/21131291/2e30db46-22f5-4819-ac09-863c7cf89032)
jenkins config:

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
