### ISSUE TITLE
Docker container is not able to make HTTP requests anymore SSR

### ISSUE THREAD

**Issue by CarlosTorrecillas** [angular/angular#54085]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Before upgrading to Angular 17.1.1, I have been running my Angular app on Angular 16 on a Docker container without any issues. Now that I moved to ESBuild I have the project running locally however when I pack it up on a Docker image the HTTP requests stopped working. Note that I run the same command on my local machine it works: `"serve:ssr": "node dist/my-website/server/server.mjs",`

My node version is 18.13.0 and I could verify it on both my local machine and the container itself (in the container I also specify the actual version to use but I can also inspect it to confirm it).

I don't know if there is anything else to be installed on the actual image but to me that should be something that should work as it does when I run the same command locally.

### Please provide the exception or error you saw

Http requests don't seem to complete / wait to finish and I get failures on the server but the browser processes the content as expected. This behavior does not happen on the local environment if run ng build && npm run serve-ssr.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.1.1
Node: 18.13.0
Package Manager: npm 8.19.3
OS: win32 x64

Angular: 17.1.1
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

### Anything else?

My Dockerfile that has been working for several versions is quite straighforward:

```
FROM node:18.13-alpine
COPY dist dist
COPY ./package.json package.json
EXPOSE 4000
CMD npm run serve:ssr
```

**Comment by alan-agius4** [comment]
You mentioned that you are getting failures on the server, what sort of failures are you getting? Can you please provide the actual error?

**Comment by CarlosTorrecillas** [comment]
I do apologize for this, I think we can close it. To me it seems like a newer version of Docker does not allow me to resolve localhost as a host and therefore I get the errors. I need to investigate that further but from the Angular point of view everything seems to be OK. That's why it was working when executing the app from the local machine itself as opposed to the local container.

To be honest I don't know when that happened, but tried a couple of versions and I couldn't get it to work.
