### ISSUE TITLE
Deeply nested recursion causes issues in core.mjs getComponentDef

### ISSUE THREAD

**Issue by selezovic-asee** [angular/angular#54092]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Problem occurs where there is a possibility of a deep nested recursion. 
RootComponent->ChildComponent->ChildComponent->
ChildComponent->injectsService->service tries to open dialog with RootComponent

What is really weird is that this happens regardless of the service using the RootComponent.
Actually, if i just import the RootComponent and do anything with it, I get the same behaviour.
For example if I write const test = [RootComponent] I will get the same error even though said component is not being used in angular.

Whenever I try to render RootComponent I get this behaviour:
```
ERROR TypeError: Cannot read properties of undefined (reading 'ɵcmp')
    at getComponentDef (core.mjs:2096:12)
    at extractDirectiveDef (core.mjs:1985:12)
    at core.mjs:2159:21
    at Array.map (<anonymous>)
    at core.mjs:2159:10
    at createTView (core.mjs:12383:63)
    at getOrCreateComponentTView (core.mjs:12332:28)
    at addComponentLogic (core.mjs:13085:19)
    at instantiateAllDirectives (core.mjs:12887:9)
    at createDirectivesInstances (core.mjs:12295:5)
```

### Please provide a link to a minimal reproduction of the bug

Link not possible 

### Please provide the exception or error you saw

```
ERROR TypeError: Cannot read properties of undefined (reading 'ɵcmp')
    at getComponentDef (core.mjs:2096:12)
    at extractDirectiveDef (core.mjs:1985:12)
    at core.mjs:2159:21
    at Array.map (<anonymous>)
    at core.mjs:2159:10
    at createTView (core.mjs:12383:63)
    at getOrCreateComponentTView (core.mjs:12332:28)
    at addComponentLogic (core.mjs:13085:19)
    at instantiateAllDirectives (core.mjs:12887:9)
    at createDirectivesInstances (core.mjs:12295:5)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
angular-cli 17.1.1
node 18.1.0
npm 10.2.3
os win32 x64

@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1

   "@angular/animations": "17.0.0",
    "@angular/cdk": "17.0.0",
    "@angular/common": "17.0.0",
    "@angular/compiler": "17.0.0",
    "@angular/core": "17.0.0",
    "@angular/forms": "17.0.0",
    "@angular/material": "17.0.0",
    "@angular/material-moment-adapter": "^17.0.0",
    "@angular/platform-browser": "17.0.0",
    "@angular/platform-browser-dynamic": "17.0.0",
    "@angular/router": "17.0.0",
```

**Comment by JeanMeche** [comment]
Hi, without a reproduction this is hardly actionable for us. Could you try to reproduce that in on stackblitz repro ?

**Comment by selezovic-asee** [comment]
I'll create a similar app to reproduce it then and link you stackblitz repo.

**Comment by JoostK** [comment]
This is because of a cyclic import in your application, which needs to be broken in some way. The result is that some import bindings are `undefined` during initialization of a module, such that Angular sees an `undefined` value instead of a class instance.

This is ultimately an issue in your application that might be avoided using `forwardRef`.

**Comment by selezovic-asee** [comment]
@JoostK 
This doesn't solve the issue
doesn't work:
  standalone: true,
  imports: [
    CommonModule,
    forwardRef(() => TokenGridComponent),
    forwardRef(() => UserGridComponent),
    forwardRef(() => AuditLogGridComponent)
  ],

works:
 standalone: true,
  imports: [
    CommonModule,
    // forwardRef(() => TokenGridComponent),
    // forwardRef(() => UserGridComponent),
    // forwardRef(() => AuditLogGridComponent)
  ],

**Comment by JoostK** [comment]
I cannot comment as to what the solution could be without reproduction.

**Comment by selezovic-asee** [comment]
@JoostK 
I managed to solve it using forwardRef. 
Problem was not on for example TokenGridComponent but on it's child <data-grid>. 
By using forwardRef on the grid the problem went away.
Do you maybe know what could be the reason for recursion causing issue on data-grid but not on it's parent? 

Thank you for your help.
