### ISSUE TITLE
There is a typo in @Output documentation

### ISSUE THREAD

**Issue by gautam3189** [angular/angular#54093]
### Describe the problem that you experienced

I am attaching the screenshot

![angular-doc-error](https://github.com/angular/angular/assets/37847010/0fb37de1-9e14-4e7a-9a55-f33965f079d6)

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/outputs

**Comment by JoostK** [comment]
Thanks for the report, this was addressed in https://github.com/angular/angular/pull/52673 but has not yet been deployed.
