### ISSUE TITLE
Sass mixins applied on parent overrides child host styles

### ISSUE THREAD

**Issue by Passeriform** [angular/angular#54095]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

If a mixin applied on a parent is setting styles for child elements, the native style on the child element is overridden.

Checking the produced DOM shows the component style being overridden by the mixin style.

Ideally, a component style should override the style set by the parent component.

This causes an issue when trying to define a style for the parent and unset it for the child like `pointer-events`, as the child can no longer define their own styles.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-6juqq9

### Please provide the exception or error you saw

```true
No error from CLI, the issue is in the order of styles applied.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.1
Node: 20.9.0
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 17.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

### Anything else?

When observing the browser, the styles set by the child (`background-color: green`) is overridden by the parent (`background-color: red`).
![image](https://github.com/angular/angular/assets/32395996/dc1ea873-3ca1-44c8-acb2-659ef6f3660b)

I think this is an Angular-specific issue, given that it's adding an invalid selector in place of `*` as written in Sass. If this is a problem with Sass, I'll move this issue there

**Comment by JoostK** [comment]
This is working as expected; the `:host` selector targets the host element, which can also be styled from outside the component. Since the outside selector is more specific (standard CSS specificity comes into play here), it is preferred over the component's host style.
