### ISSUE TITLE
Just a little typo

### ISSUE THREAD

**Issue by Silvaindj** [angular/angular#54105]
### Describe the problem that you experienced

Last paragraph :

```
Great job learning these core concepts of working with forms in Angular. If you want to learn more, be sure to refer to the [Angular forms documenation](https://angular.dev/guide/forms/form-validation).
```

documenation -> documentation

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/forms-validation

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52901 and is pending deployement on our side !
