### ISSUE TITLE
Multi-Project File Structure, Library suggestion for CSS and Assets

### ISSUE THREAD

**Issue by n614cd** [angular/angular#54119]
### Describe the problem that you experienced

There is no documentation I could find which actually linked and provided information on how to expose standalone CSS and other assets from a library project.

### Enter the URL of the topic with the problem

https://angular.io/guide/file-structure#multiple-projects

### Describe what you were looking for in the documentation

Either a link to https://github.com/ng-packagr/ng-packagr/blob/main/docs/copy-assets.md 
or a working example implementing a shared library with the standalone CSS or Assets.

**Comment by 4javier** [comment]
The link you're looking for is mentioned at the second line of the assets paragraph in the page for library creation.
https://angular.io/guide/creating-libraries#managing-assets-in-a-library
That page in turn links the multi-project one.
Maybe a crosslinking between the two could be advisable.

**Comment by n614cd** [comment]
I have idea how many times I read the multi-project page, or had a couple of other devs from my team read it, and we all totally missed that.
Not sure what else the team could have done.
