### ISSUE TITLE
Page Not Found for See the NgComponentOutlet API reference for more information on the directive's capabilities.

### ISSUE THREAD

**Issue by ankurinfoniti** [angular/angular#54110]
### Describe the problem that you experienced

Programmatically rendering components tutorial has wrong link for NgComponentOutlet API reference. It goes to page not found.

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/programmatic-rendering

### Describe what you were looking for in the documentation

I am learning dynamic component rendering.

### Describe what you want to experience that would fix the problem

The link should be this:
`https://angular.dev/api/common/NgComponentOutlet`

**Comment by JoostK** [comment]
Thanks for the report, closing as a duplicate of https://github.com/angular/angular/issues/52828 for which the fix is pending deployment.
