### ISSUE TITLE
Best Practice for Base Component or Abstract Component

### ISSUE THREAD

**Issue by n614cd** [angular/angular#54118]
### Describe the problem that you experienced

Over the years, the advice has changed on how to declare a base or abstract root component that is extended by other components. The base component (I prefer that they be marked abstract) does not have an actual template, but does implement Angular features, such as OnInit. 

### Describe what you were looking for in the documentation

What is the current suggested and best practice to implement an abstract base component. Call it a Directive and mark it with @Directive or @Component....
Ideally, the page would include information on previous recommendations.

**Comment by pkozlowski-opensource** [comment]
We don't have specific guidance here - extending classes is one way of organizing code and you should feel free to use it as it fits your team and project needs. I don't think Angular should prescribe anything here.

**Comment by n614cd** [comment]
@pkozlowski-opensource 

If you extend a component, the parent component has a compile failure with Typescript set to strict. Even when the parent class is marked abstract.
The failure is "Class is using Angular features but is not decorated. Please add an explicit Angular decorator."

Previous versions of Angular have been inconsistent in what method should be used to address this compile error.
