### ISSUE TITLE
ngComponentOutlet

### ISSUE THREAD

**Issue by dh05011984** [angular/angular#54123]
### Describe the problem that you experienced

on clicking this page not found error received.
please find the below url
https://angular.dev/api/core/NgComponentOutlet

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/programmatic-rendering

**Comment by JoostK** [comment]
Thanks for the report, closing as a duplicate of https://github.com/angular/angular/issues/52828 for which the fix is pending deployment.
