### ISSUE TITLE
Export ChangeDetectionScheduler and ChangeDetectionSchedulerImpl

### ISSUE THREAD

**Issue by e-oz** [angular/angular#54125]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Please consider exporting ChangeDetectionScheduler and ChangeDetectionSchedulerImpl.

When providing custom noop zone implementation, we also need to provide ChangeDetectionScheduler.
Angular code does this:
```ts
export function provideZonelessChangeDetection(): EnvironmentProviders {
  return makeEnvironmentProviders([
    {provide: ChangeDetectionScheduler, useExisting: ChangeDetectionSchedulerImpl},
    {provide: NgZone, useClass: NoopNgZone},
  ]);
}
```

I would like to do the same, with my own NgZone implementation.

### Proposed solution

Please make ChangeDetectionScheduler and ChangeDetectionSchedulerImpl part of public API.

### Alternatives considered

I have to do this dirty hack for now:
```ts
export function provideZonelessChangeDetectionX(): EnvironmentProviders {
  const envProviders = (ɵprovideZonelessChangeDetection() as any);
  const providers = envProviders['ɵproviders'];
  providers[1] = { provide: NgZone, useClass: NoopNgZoneX };
  return envProviders;
}
```
I hope it's temporary :)

**Comment by atscott** [comment]
Fully custom schedulers with custom zone implementations at this level are not really something we plan to support. We are investigating a scheduler that works _with_ ZoneJs/NgZone and that is generally tracked by https://github.com/angular/angular/issues/53844. 

Could describe what you’re trying to accomplish rather than jumping to a proposed solution? As far as this direct request goes, that’s unlikely to happen.

**Comment by e-oz** [comment]
I need it to provide a custom implementation of NgZone (zoneless app). I use a dirty workaround right now to copy the functionality of `ɵprovideZonelessChangeDetection()`.

I described how I use it here:
https://github.com/angular/angular/issues/54126

**Comment by atscott** [comment]
Okay, thanks for the additional detail. That’s what I assumed this was about. 

We are considering an option in the provider itself that would emit these events _as a very last resort_ and even then, it would only be available as a temporary solution while libraries migrate away from onStable/onMicrotaskEmpty. 

Our goal is to find replacements for these APIs. Having an NgZone interface for notifications related to timing just doesn’t make that much sense in a Zoneless world. We can and plan to do better. 

Thanks for continuing to experiment with Zoneless and providing valuable feedback. The implementation is still evolving, as are the other APIs to support it, so please be patient while we work out the details.
