### ISSUE TITLE
Custom events with outputs

### ISSUE THREAD

**Issue by dh05011984** [angular/angular#54124]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

"Customizing output names" Title

@Component({...})
export class CustomSlider {
  **@Input('valueChanged') changed = new EventEmitter<number>();**
}
**Here instead of @Input() there should be @Output()**

### Please provide a link to a minimal reproduction of the bug

https://angular.dev/guide/components/outputs

### Please provide the exception or error you saw

```true
"Customizing output names" Title

@component({...})
export class CustomSlider {
@input('valueChanged') changed = new EventEmitter();
}
Here instead of @input() there should be @output()
```

**Comment by JoostK** [comment]
Thanks for the report, this was addressed in https://github.com/angular/angular/pull/52673 but has not yet been deployed.
