### ISSUE TITLE
Angular Universal 17.1.1 Express REST API not working

### ISSUE THREAD

**Issue by blackat** [angular/angular#54132]
### Which @angular/* package(s) are the source of the bug?

express-engine

### Is this a regression?

No

### Description

Hello,
I have started a new project with Angular Universal from the CLI.
I would like to redirect the /api/** endpoints to a different server, but I am facing some issues.

I have seen the host is setup in the header of the requests, I change it in the following way:
```
// Example Express Rest API endpoints
  server.get('/api/**', (req, res, next) => {
    req.headers.host = 'http://localhost:3000'
    next();
  });
```

but I get the following error (the endpoint works, I have just copy/pasted the url I and I can get the results):
```
ERROR G [Error]: NG04002: 'localhost:3000/api/news'
    at na.noMatchError (file:///Users/xxxxxx/Development/GitHub/xxxxxx/dist/xxxxxx/server/chunk-JY4VO6WS.mjs:2:39383)
    at file:///Users/xxxxxx/Development/GitHub/xxxxxx/dist/xxxxxx/server/chunk-JY4VO6WS.mjs:2:40078
    at file:///Users/xxxxxx/Development/GitHub/xxxxxx/dist/xxxxxx/server/chunk-RGNQT4QR.mjs:4:21085
```
later in the log I see
```
status: 200,
  statusText: 'OK',
  url: 'http://localhost:4000/api/news',
  ok: false,
  name: 'HttpErrorResponse',
  message: 'Http failure during parsing for http://localhost:4000/api/news',
  error: SyntaxError: Unexpected token < in JSON at position 0
```
as the URL has never been changed.
In the Angular guide I have not seen any example, could you please suggest how to set the rewrite of the host?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.1
Node: 18.13.0
Package Manager: npm 8.19.3
OS: darwin arm64

Angular: 17.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser
... platform-browser-dynamic, platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by JoostK** [comment]
Reassigning the host header is not sufficient to initiate a proxied redirect. There exists proxy middleware for Express, but this is outside's the CLI's scope.

**Comment by blackat** [comment]
Thanks a lot for your answer.
I see, so I can use something like http-proxy-middleware to proxify /api/**, is this something fine for production as well?
