### ISSUE TITLE
Repetition of Sentence in Documentation

### ISSUE THREAD

**Issue by yousefalaqra** [angular/angular#54137]
### Describe the problem that you experienced

On the [Angular Components page](https://angular.dev/guide/components), there is a repetition of the sentence explaining how Angular-specific information is provided for a component using the @Component decorator. The sentence is duplicated, which may lead to confusion for readers. The redundant sentence appears to be:

"You provide Angular-specific information for a component by adding a @Component decorator on top of the TypeScript class."

### Enter the URL of the topic with the problem

https://angular.dev/guide/components

### Describe what you were looking for in the documentation

I was educating myself and find out what's latest about angular 

### Describe the actions that led you to experience the problem

Open angular.dev then go to docs in the left side menu, then go components views

### Describe what you want to experience that would fix the problem

The ideal fix for this issue involves removing the duplicated sentence that explains how Angular-specific information is provided for a component using the @Component decorator. The documentation should maintain clarity while avoiding unnecessary repetition

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/56271934/c490dfaa-7b7f-4974-a8f4-36a949a06aec)

**Comment by yousefalaqra** [comment]
I'd love to work and fix this issue, please assign to me once approved! thanks!

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by  #52587  and is pending deployement on our side !

**Comment by yousefalaqra** [comment]
That's cool! thanks!
