### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by L0ki7778** [angular/angular#54136]
### Describe the problem that you experienced

[template reference variable](https://angular.dev/guide/glossary#template-reference-variable) - link isn´t working within the docs(deferable->on viewport)

Page not found.

### Enter the URL of the topic with the problem

https://angular.dev/guide/defer#on-viewport

### Describe what you were looking for in the documentation

I was looking for a way to change the threshold.

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #53084 and is pending deployement on our side !
