### ISSUE TITLE
preserveWhitespaces attribute doesn't work

### ISSUE THREAD

**Issue by EPolishchuk** [angular/angular#54133]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

According to https://angular.io/api/core/Component#preserving-whitespace, when I need to preserve whitespaces in a specific part of a template, all I need to do is add attribute `ngPreserveWhitespaces`

But in Angular 15/17 it doesn't work. Whitespaces is collapsed into one.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-store-17-ezumzw?file=src%2Fapp%2Fhello.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.9
Node: 20.6.1 (Unsupported)
Package Manager: npm 10.1.0
OS: darwin arm64

Angular: 15.2.9
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router
```

**Comment by JoostK** [comment]
The whitespace is retained just fine:

<img width="759" alt="Screenshot 2024-01-28 at 20 54 12" src="https://github.com/angular/angular/assets/123679/79cfb71b-560b-4c41-a33a-4936c1406659">

(the second occurrence is one I added without `ngPreserveWhitespaces`). You'll still need to use CSS's `white-space: pre;` (or a variant thereof, there's a couple of choices) to actually make the whitespace significant to how a browser shows the text.
