### ISSUE TITLE
Brand new app failing with: NG0203: inject() must be called from an injection context such as a constructor

### ISSUE THREAD

**Issue by dansoper** [angular/angular#54147]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I've created a brand-new Angular 17.1 app, and it doesn't load in the browser. In the console, I get the `NG0203: inject() must be called from an injection context such as a constructor` error.

### Please provide the exception or error you saw

```true
NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.1
Node: 20.11.0
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by JoostK** [comment]
This typically happens when there's multiple copies of `@angular/core` present, as tracked in #35586. I don't have sufficient insight into your situation to judge whether this is the case here as wel, so please provide a runnable reproduction.

**Comment by maequise** [comment]
I agree with @JoostK, I had a similar issue when I was testing and linking the framework repo with the local repo during my tests.

**Comment by dansoper** [comment]
Thanks for the replies. I have worked out what is causing it in my environment, but not sure if there's a resolution.

I have a persisted SUBST 'drive' in my machine (https://en.wikipedia.org/wiki/SUBST#Registry_(DOS_Devices))

This means that files at C:\Users\Me\Documents\Source are also at S:\

When I run the Angular app by `ng serve` from the S: drive, it fails. When I run it from the C: drive, it succeeds. So it's something to do with this symbolic link.  It only affects `ng serve` - not `ng build`. It hasn't previously been a problem, but I guess there's something new in the build/serve code?

I have a workaround, but it would be good to know of a proper solution.

**Comment by JoostK** [comment]
I am not familiar with drive-mapped directories, but if they behave like symlinks then the `preserveSymlinks` option may affect how this works.

**Comment by dansoper** [comment]
Yes, thank you, setting `preserveSymlinks` to true in my angular.json (at `projects.my-project.architect.build.options.preserveSymlinks`) seems to have solved it.
