### ISSUE TITLE
Page not found.

### ISSUE THREAD

**Issue by developedbyrb** [angular/angular#54143]
### Describe the problem that you experienced

I am looking for the page which is redirected from this URL: https://angular.dev/tools/cli/setup-local#dependencies to see Angular's version compatibility guide and in response I got a page not found with a 404 error code.

### Enter the URL of the topic with the problem

https://angular.dev/versions

### Describe what you were looking for in the documentation

I am looking for the angular version compatibility guide.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/70124802/1e6f982e-2f8e-4442-9a98-cfa543d47e90)

### If this problem caused an exception or error, please paste it here

Page Not Found

### If the problem is browser-specific, please specify the device, OS, browser, and version

checking on Windows OS, chrome(Version 120.0.6099.225)

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52585 and is pending deployement on our side !
