### ISSUE TITLE
Incorrect Link in Angular Documentation for :host-context Pseudo Class - Update Required

### ISSUE THREAD

**Issue by yousefalaqra** [angular/angular#54141]
### Describe the problem that you experienced

the Angular documentation involves an incorrect link for the :host-context pseudo class. In the documentation, the link provided for :host-context directs users to https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context(), which is an invalid link and results in a "Page Not Found" error. The correct link for :host-context is https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context.

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/styling

### Describe what you were looking for in the documentation

Learning about component styling 

### Describe the actions that led you to experience the problem

Opne docs=>components=>styling

### Describe what you want to experience that would fix the problem

To resolve this issue, the documentation should be updated to provide the accurate link for the :host-context pseudo class, ensuring that users can access the relevant information without encountering broken links.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/56271934/226d8c25-d8be-4596-b6b0-ca9b40651cd4)

**Comment by yousefalaqra** [comment]
I'd be happy to create PR for this, please assign to me if the issue approved

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52966 and is pending deployement on our side !
