### ISSUE TITLE
Angular 15.2.10 sudden build failure (Subsequent variable declarations must have the same type.  Variable 'crypto' must be of type 'Crypto', but here has type 'Crypto')

### ISSUE THREAD

**Issue by Wisdomb33r** [angular/angular#54144]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Since today monday 29 january, our Angular 15 builds are failing, both locally and on CI server. Our software have a currently productive version which is running Angular 15 (I'll refer to this branch as "support" from now). Our next version, planned to be released around april, is upgraded to Angular 16, and this branch build (called "dev" branch) is running fine as of now.

Our support branch did not have any commits since a week so I can exclude a code change being the source of the break. Last week our nightly builds were completely fine. Since this morning, they fail.

As long as a developer does not remove their "node_modules" from the project, they can build the software fine. As soon as they delete the folder and run `npm install` again (I ran this process on my personal laptop today), they are stuck and cannot perform any of these : 
 - npm run start
 - npm run test
 - npm run build

It seems a transitive dependency of something was updated and broke our builds. But what I cannot say, the error message is completely obscure.

Here is my complete `package.json` file : 

```
{
  "name": "XXXX",
  "version": "YYY.30.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.conf.json",
    "build": "ng build --configuration production --base-href /frontend/",
    "test": "ng test --browsers Chrome",
    "test-ci": "ng test --watch=false --browsers ChromeHeadless",
    "test-cc": "ng test --watch=false --browsers ChromeHeadless --code-coverage --source-map"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "15.2.10",
    "@angular/cdk": "15.2.9",
    "@angular/common": "15.2.10",
    "@angular/compiler": "15.2.10",
    "@angular/core": "15.2.10",
    "@angular/forms": "15.2.10",
    "@angular/material": "15.2.9",
    "@angular/platform-browser": "15.2.10",
    "@angular/platform-browser-dynamic": "15.2.10",
    "@angular/router": "15.2.10",
    "@auth0/angular-jwt": "5.1.2",
    "@ngx-translate/core": "14.0.0",
    "@ngx-translate/http-loader": "7.0.0",
    "ch-plate-lib": "YYY.10.1", // an internal Angular library
    "class-transformer": "0.5.1",
    "file-saver": "2.0.5",
    "ngx-extended-pdf-viewer": "15.2.2",
    "ngx-mask": "15.1.0",
    "reflect-metadata": "0.1.13",
    "rxjs": "7.5.7",
    "tslib": "2.4.1",
    "zone.js": "0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "15.2.10",
    "@angular/cli": "15.2.10",
    "@angular/compiler-cli": "15.2.10",
    "@angular/language-service": "15.2.10",
    "@types/file-saver": "2.0.5",
    "@types/jasmine": "4.3.1",
    "jasmine-core": "4.5.0",
    "karma": "6.4.1",
    "karma-chrome-launcher": "3.1.1",
    "karma-coverage": "2.2.0",
    "karma-jasmine": "5.1.0",
    "karma-jasmine-html-reporter": "2.0.0",
    "ncp": "2.0.0",
    "typescript": "4.8.4"
  }
}
```
Any help or idea would be highly appreciated. We currently cannot release our Angular software anymore.

### Please provide the exception or error you saw

```true
PS D:\workspaces\caring\cari-ng> npm run build

> XXXX@YYY.30.0 build
> ng build --configuration production --base-href /frontend/

√ Browser application bundle generation complete.

Error: node_modules/@types/node/ts4.8/crypto.d.ts:4477:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'crypto' must be of type 'Crypto', but here has type 'Crypto'.

4477         var crypto: webcrypto.Crypto;
                 ~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:18033:13
    18033 declare var crypto: Crypto;
                      ~~~~~~
    'crypto' was also declared here.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.10
Node: 18.17.1
Package Manager: npm 9.6.7
OS: win32 x64

Angular: 15.2.10
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.10
@angular-devkit/build-angular   15.2.10
@angular-devkit/core            15.2.10
@angular-devkit/schematics      15.2.10
@angular/cdk                    15.2.9
@angular/material               15.2.9
@schematics/angular             15.2.10
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

This is a good example of _always_ including lockfiles in version control. The error is reported by TypeScript for a declaration conflict, where a declaration from `@types/node` is conflicting with TypeScript's builtin declarations.

You can try using `npm why @types/node` to potentially learn more about which dependency versions are being used, but this is outside of Angular's scope.
