### ISSUE TITLE
Angular UI didn’t pickup data model change when the project has BrowserAnimationsModule

### ISSUE THREAD

**Issue by Justin01Wu** [angular/angular#54140]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

No

### Description

My project have a page to select a program. It works perfectly until I add BrowserAnimationsModule into my project.

The page has a button “change to Program A”. It is always working correctly no matter how many time you click this button.

Please see [correct program selector](http://www.justa999.com/multiple/#/program-selector)

But it will set to “Empty Program” on the second click after BrowserAnimationsModule is added into this project. But the data model is already set to correct program which I printed on the page.

Please see [broken program selector](http://www.justa999.com/brokenMultiple/#/program-selector)

This page itself didn’t use BrowserAnimationsModule. The code is exact the same on both link except broken one has BrowserAnimationsModule in the project.

I tried Firefox and Edge, both have the same issue.

I also tried Angular version 12 and 15, both have the same issue.

Current implementation is using FormControl. I also tried [(ngModel)] and get the same issue.

Both links have source map and can debug on the source. Please use browser console to see them.

I saw someone mentioned [a bug](https://github.com/angular/angular/issues/18430) on BrowserAnimationsModule. But seems it was fixed.

### Please provide a link to a minimal reproduction of the bug

http://www.justa999.com/brokenMultiple/#/program-selector

### Please provide the exception or error you saw

```true
I didn't see the exception, but the UI didn’t pickup data model change
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.2.18
Node: 16.20.0 (Unsupported)
Package Manager: npm 8.19.4
OS: win32 x64

Angular: 12.2.17
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.18
@angular-devkit/build-angular   12.2.18
@angular-devkit/core            12.2.18
@angular-devkit/schematics      12.2.18
@angular/cli                    12.2.18
@angular/material               12.2.13
@schematics/angular             12.2.18
ng-packagr                      12.2.7
rxjs                            6.5.5
typescript                      4.3.5
```

**Comment by alxhub** [comment]
Hi @Justin01Wu,

Without a minimal reproduction (including the source code) it's very difficult for us to investigate issues like this.

I _suspect_ what's happening is that animations are delaying the existence of the `<option>` for your "Program A", and thus when you try to set the value of the `<select>` it's not considered valid. But I can't know for sure without a running reproduction (ideally on Stackblitz).

**Comment by JeanMeche** [comment]
I updated you demo from v12 to v17 and your issue doesn't reproduce.

**Comment by JeanMeche** [comment]
Without any feedbacks from you, we're going to close this issue. If another problem arises, feel free to open a new issue. Thank you.
