### ISSUE TITLE
ReferenceError   intersectionObserver(@angular/core/fesm2022/core)

### ISSUE THREAD

**Issue by bjornharvold** [angular/angular#54152]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Team Angular,

Guessing this has something to do with the new lazy loading feature. 

We are making healthy use of Angular lazy loading on this page but we are not able to replicate.

Sentry notifying us of this error.
![screencapture-wink2travel-sentry-io-issues-4925478902-2024-01-30-12_26_40](https://github.com/angular/angular/assets/641791/5197155d-e3a5-4abf-97e3-d515a4482e9a)

### Please provide a link to a minimal reproduction of the bug

https://ota.wink.travel/hotel/hotel-sensai-chiang-mai-thailand

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.1
Node: 20.11.0
Package Manager: yarn 1.22.21
OS: darwin arm64

Angular: 17.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, router
... service-worker, youtube-player

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1
ng-packagr                      17.1.2
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by JoostK** [comment]
That's strange, `IntersectionObserver` is documented to be available since Safari 12.2. I do read reports of it being listed as experimental and can therefore be disabled or unavailable in embedded web views. I don't have access to a Safari 16 installation to check, but I couldn't find such feature flag in Safari 17.

**Comment by JeanMeche** [comment]
I just tested on a Safari 15.6.1, the developer menu allows to disable the `IntersectionObserver` and throws that exact error when trying to use it (in a webpack/stackblitz, no error is thrown when done in the console).

**Comment by bjornharvold** [comment]
Great detective work @JeanMeche. Will ignore this error as it's a user opt-in on Safari's end. 🍻
