### ISSUE TITLE
InputSignal with booleanAttribute cannot be used as an attribute

### ISSUE THREAD

**Issue by MurhafSousli** [angular/angular#54165]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Using `input` with `booleanAttribute` enforces giving a boolean value

```ts
 disableSensor: InputSignal<boolean> = input<boolean, boolean>(false, {
    transform: booleanAttribute
  });
```

It throws an error when I use the directive as an attribute

```html
<my-component disableSensor/>
```

### Please provide the exception or error you saw

```true
Type "" is not assignable to type boolean
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.1
Node: 20.2.0
Package Manager: npm 9.6.1
OS: win32 x64

Angular: 17.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1
ng-packagr                      17.1.2
zone.js                         0.14.3
```

**Comment by JeanMeche** [comment]
By defining the types of your signal as `input<boolean, boolean>` you're telling the compiler that input should take a `boolean` and return a `Signal<boolean>`. 

You likely want to have `input<boolean, unknown>` which means input is `unknown` and the signal is a `boolean`. 

That being said, I'd suggest you let the inference do its job a use: 

```
  disableSensor = input(false, {
    transform: booleanAttribute,
  });
```

**Comment by MurhafSousli** [comment]
Thanks, it worked!
