### ISSUE TITLE
Angular SSR 17 providers and GET calls not working

### ISSUE THREAD

**Issue by BeCaDRI** [angular/angular#54170]
### Which @angular/* package(s) are the source of the bug?

core, platform-server

### Is this a regression?

No

### Description

Hey,

I'm trying to generate a simple Angular SSR App, but it looks like it does not work.

NOTE: I know there is a bug with ng serve and SSR (as the VITE dev server does not handle the server.ts) - as of that I talk explicitly about ng build + node dist/server/server.js commands!

When you generate a new Angular App with `ng new --ssr` command you will get a SSR ready app.

What I want to achieve:
Read the query params of a URL and provide it to the Angular App. From my understanding the renderer on server side should be capable to handle this query params and render the query params into the HTML output.
e.g. I call the url localhost:4000?name=test?email=test@test.com the app.component should display the name and email without using any additional Angular execution on client side.
Background: If someone disabled JS script in his browser the side should already contain all information he needs.

What I tried in the app.component contructor:
```typescript
@Optional() @Inject(new InjectionToken('query-params'))
              public queryParams: { email: string, name: string, lang: string }
``` 

in server.ts 
```typescript
// pre-render hooks
  server.get('*', (req, res, next) => {
    const { protocol, originalUrl, baseUrl, headers } = req;
    queryParams = req.query;
    commonEngine
      .render({
        bootstrap,
        documentFilePath: indexHtml,
        url: `${protocol}://${headers.host}${originalUrl}`,
        publicPath: browserDistFolder,
        providers: [
          { provide: APP_BASE_HREF, useValue: baseUrl },
          {
            provide: 'query-params',
            useValue: queryParams
          }
        ]
      })
      .then((html) => {
        console.log(html);
        res.send(html);
      })
      .catch((err) => next(err));
  });
``` 
Result: queryparams are always null when I open the above mentioned URL with query params. The server logs the the params correctly

2nd approach: 
Make a get call to the express API:
```typescript
 server.get('/api/query-params', (req, res, next) => {
    console.log(queryParams);
    res.send(queryParams);
  });

``` 
The queryparams are set when the base URL is called. I'm not sure if this is even possible as the timing should be a factor here. 
The API GET will be called in the ngOnInit function. 
This works, but the API call will be done in the client, not before server side rendering.

Another strange behavior in this case:
When I run ng build, there is an error that the api route is not available. I didn't expect that the ng-build command executes the code but this should be done at runtime?!

So there are three questions: 
1. Why are the providers always null?
2. Is there an option to make the GET call based on the URL and render it on server side?
3. Why does ng-build execute API calls?!

I'am new to Angular SSR, but the rare documentation for the new Angular 17 SSR functionality and the not working providers make me struggle.
If there are any better approaches to solve this? There is the possibility to manually manipulate the HTML output, but this would be the last option I want to approach.

Thanks in advance.

### Please provide a link to a minimal reproduction of the bug

https://angular.io/guide/ssr

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.1
Node: 18.18.0
Package Manager: npm 9.8.1
OS: linux x64

Angular: 17.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.3
```

**Comment by JeanMeche** [comment]
Hi, this issue is being tracked at angular/angular-cli#26323

**Comment by alexcmoss** [comment]
There is an issue with your example.

`'query-params' !== new InjectionToken('query-params')`

Try creating a single injection token instance and using it in both AppComponent and server.ts as below.

in app.component.ts
```ts
export const QUERY_PARAMS = new InjectionToken('query-params');
...
@Optional() @Inject(QUERY_PARAMS)
              public queryParams: { email: string, name: string, lang: string }
```


in server.ts
```ts
import { QUERY_PARAMS } from './src/app/app.component';

// pre-render hooks
  server.get('*', (req, res, next) => {
    const { protocol, originalUrl, baseUrl, headers } = req;
    queryParams = req.query;
    commonEngine
      .render({
        bootstrap,
        documentFilePath: indexHtml,
        url: `${protocol}://${headers.host}${originalUrl}`,
        publicPath: browserDistFolder,
        providers: [
          { provide: APP_BASE_HREF, useValue: baseUrl },
          {
            // provide: 'query-params',
            provide: QUERY_PARAMS,
            useValue: queryParams
          }
        ]
      })
      .then((html) => {
        console.log(html);
        res.send(html);
      })
      .catch((err) => next(err));
  });
```

**Comment by BeCaDRI** [comment]
@alexcmoss thanks, but this is still not working using the latest Angular 17 SSR. I've tried it with APP_BASE_HREF or REQUEST  and RESPONSE to make sure that not only custom token providers are working - same result

As far as I read and understand you have to use the extra Angular 16 builder for browser and server in angular.json to make it work?!
To reproduce just create a new Angular SSR project with Angular CLI and try to use any provider in app.component. 
It is just not working - no matter how I try to use providers or how I configure my app.
As a workaround you can fetch the data on client from the node backend with an API route, but this breaks the whole intention to use specific url params to identify which user/email we have to handle...

**Comment by gnibeda** [comment]
Is there any news? InjectionToken not working in Angular 17 SSR. If someone have working demo, please share.
It not works even if you build app and serve SSR as usual. Simply InjectionToken are ignored.
