### ISSUE TITLE
Cron Job

### ISSUE THREAD

**Issue by venuguggillavv** [angular/angular#54174]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

unable to hit the API using setInterval after multiple components created (HttpClient )

### Please provide the exception or error you saw

```true
the error I saw => created the project with a basic app component. 
I can hit API on setInterval on ngoninit, AfterViewInit, or click event. 
once my project is grown up with multiple components, now API is not triggering on ngoninit or AfterViewInit but it is working fine with click event.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.0
Node: 20.10.0
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 17.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.0
@angular-devkit/build-angular   17.1.0
@angular-devkit/core            17.1.0
@angular-devkit/schematics      17.1.0
@schematics/angular             17.1.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
