### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError when setting value of signal in `ngOnInit`

### ISSUE THREAD

**Issue by ValentinBossi** [angular/angular#54197]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Having two components which sets a value in `ngOnInit` ends in a `NG0100 ExpressionChangedAfterItHasBeenCheckedError`.

Im coming from the same issue when using NgRx in `ngOnInit` https://github.com/ngrx/platform/issues/3989

It is working though, when the code is moved to the constructor. but applying this "constructor rule" feels like its against the angular documentation https://angular.io/guide/lifecycle-hooks#oninit which says doing things in the constructor should be done in `ngOnInit`.
Coming from the above NgRx issue, there the NG100 error is exactly triggered when in `ngOnInit` an action is dispatched which triggers an effect which uses `HttpClient`. what essentially is the described case in the angular docs not doing in the constructor (http fetch).

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-om9ryw?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 17.1.1
```

### Anything else?

I mean giving the advise not using fetch and therefore not being coupled to fetch in the constructor is good. but when dispatching an action which is an application of a loosely coupled design is valid in the constructor.
if you also have this opinion it would be worth mention this A) in the angular documentation (its ok to do loosely coupled things in the constructor) and B) in the NgRx documentation (do your dispatching in the constructor, its ok). @brandonroberts

**Comment by JoostK** [comment]
This _is_ a ECAIHBC situation. Signals don't currently affect how change detection is handled, it's only a reactive envelope around a value at the moment. If that value has already been read in a template before its value is being updated during the same change detection cycle (in `ngOnInit`) then the previously checked template becomes out-of-date, violating Angular's top-down data flow requirements.

The details of how this work with signals may change in the future, but as of right now this is working as designed.

**Comment by JeanMeche** [comment]
That being said, this can be solved by using OnPush which will run local change detection an prevent NG0100.

**Comment by atscott** [comment]
> Why doesn't afterNextRender work here?

`afterNextRender` did not support updating state until https://github.com/angular/angular/commit/432afd1ef41e0bfd905e71e8b15ec7c9ab337352 which just missed the release this week

**Comment by rainerhahnekamp** [comment]
@atscott, thanks for the clarification!

**Comment by atscott** [comment]
I'm also going to close this as fixed by https://github.com/angular/angular/commit/432afd1ef41e0bfd905e71e8b15ec7c9ab337352. That PR addressed the issue where updating a signal that's read in another view attached to `ApplicationRef` would not work and still cause `NG0100`.
