### ISSUE TITLE
Angular 2 tutorial dead link in docs

### ISSUE THREAD

**Issue by jsec516** [angular/angular#5420]
Link for form chapter is dead
https://angular.io/docs/ts/latest/guide/forms
which is found in the following url:
https://angular.io/docs/ts/latest/tutorial/toh-pt1.html

**Comment by brunobelarmino** [comment]
hey man, 
This issue should be open at https://github.com/angular/angular.io

**Comment by jsec516** [comment]
@brunobelarmino thanks for your reply.

**Comment by robwormald** [comment]
closed in https://github.com/angular/angular.io/issues/402
