### ISSUE TITLE
Simplify the navigation for in-depth guides

### ISSUE THREAD

**Issue by mgechev** [angular/angular#54203]
### Describe the problem that you experienced

Currently the list contains an overwhelming amount of topics and we should consider simplifying it.

**Comment by danieljancar** [comment]
Hey @mgechev, 
You're absolutely right, feel like a more nested navigation based on the categories would be helpful.

**Comment by surajy93** [comment]
Assign to me I can surely resolve this,🫣

**Comment by danieljancar** [comment]
Hey @surajy93,
I think @bencodezen already works on it, otherwise you can just create your own fork/pull request with suggestions on how to improve the in-depth navigation. 😉

**Comment by bencodezen** [comment]
Appreciate the enthusiasm @surajy93! The issue is already in PR, but we'd welcome your contributions on other issues you see in the queue!
