### ISSUE TITLE
Documentation Out of Date

### ISSUE THREAD

**Issue by dp-swdev** [angular/angular#54209]
### Describe the problem that you experienced

As of 02/01/2024, when using the docs menu, the "Update Angular to the latest version" option under "Updates and releases" is still pointing to the Angular 16 documentation rather than Angular 17.

![image](https://github.com/angular/angular/assets/22719391/842e117e-c6c3-43f5-b178-4c55c1b3f785)

This occurs with the stable version of documentation selected.
![image](https://github.com/angular/angular/assets/22719391/8890dc66-77bf-44d7-ba78-9b5ed3cad9f5)

This occurs in both Chrome and Edge.

### Enter the URL of the topic with the problem

https://angular.io/guide/update-to-version-16

### Describe what you were looking for in the documentation

Expected to have information about the latest version of Angular, which would be version 17.

**Comment by JeanMeche** [comment]
Hi, this issue is tracked at #52750
