### ISSUE TITLE
Unhelpful Error Message when attempting to Inject a Class with a Private Constructor

### ISSUE THREAD

**Issue by briggsPriscilla** [angular/angular#5421]
We are getting the error below because we were injecting a class with a private constructor, but the error message would have been more helpful if it had told us that the problem was a private constructor or at least tell us which injected class was the problem.  

Internal Bug: b/25818169

**Comment by pkozlowski-opensource** [comment]
Was it happening in Dart only? if so this issue would be obsolete.

**Comment by vicb** [comment]
Probably i don't think TS private ctor have been released yet but for sure not 8 months ago.
