### ISSUE TITLE
@Input decorator instead of @output

### ISSUE THREAD

**Issue by keyurpanchal** [angular/angular#54218]
### Describe the problem that you experienced

Issue at : Customizing output names https://angular.dev/guide/components/outputs#customizing-output-names

Hello folks, Newbie to Angular correct me if I'm missing something :)

As from given image ang can verify from link that expected template/example should be:

_@Component({...})
export class CustomSlider {
  @Output('valueChanged') changed = new EventEmitter<number>();
}_

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/outputs#customizing-output-names

### Add a screenshot if that helps illustrate the problem

![Untitled](https://github.com/angular/angular/assets/20878387/91b4c056-ee12-4dff-beaf-82e6cf32f886)

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52673 and is pending deployement on our side !

**Comment by keyurpanchal** [comment]
Cool. Thanks @JeanMeche
