### ISSUE TITLE
The delay in the http request in Angular 16.

### ISSUE THREAD

**Issue by prajapatiomkar** [angular/angular#54211]
### Which @angular/common/http are the source of the bug?

common

### Is this a regression?

Yes

### Description

I create simple app client (Angular 16) server (NodeJs) (ExpressJs). when i make delete request from client to server. In chrome it show stalled time 20 sec and, It working fine in firefox. I could not able to understand.

## In chrome
![Screenshot from 2024-02-02 15-20-26](https://github.com/angular/angular/assets/72141037/4e3ec157-6b2d-4406-a282-174db26ac960)

## In Firefox
![Screenshot from 2024-02-02 15-35-15](https://github.com/angular/angular/assets/72141037/80078034-30f9-4091-b3ee-0f1bbed5d7da)

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
