### ISSUE TITLE
Link to 'Try out Inject' in Roadmap page

### ISSUE THREAD

**Issue by adamnik101** [angular/angular#54215]
### Describe the problem that you experienced

Link to 'Try out Inject' in Roadmap page withing 'Explore modern Angular' doesn't work. It redirects to Page not found.

### Enter the URL of the topic with the problem

https://angular.dev/di

### Describe what you were looking for in the documentation

Inject

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Windows 11
Brave browser
```

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52541 and is pending deployement on our side !
