### ISSUE TITLE
`RouterLinkWithHref` API not marked deprecated

### ISSUE THREAD

**Issue by johnnygerard** [angular/angular#54212]
### Describe the problem that you experienced

The `RouterLinkWithHref` API is deprecated as indicated in the [source code](https://github.com/angular/angular/blob/17.1.2/packages/router/src/directives/router_link.ts#L370C23-L370C41) but not marked as such in the API documentation.

### Enter the URL of the topic with the problem

https://angular.dev/api/router/RouterLinkWithHref
https://angular.io/api/router/RouterLinkWithHref

**Comment by JeanMeche** [comment]
Becaues `RouterLinkWithHref` is just a re-export of `RouterLink`, the deprecation isn't picked up, even in IDEs. 

https://github.com/angular/angular/blob/bdf6927125d17a09c49e42f523781547aa5a8b2d/packages/router/src/directives/router_link.ts#L362-L370

**Comment by JeanMeche** [comment]
Since there isn't much we can do, I'll close this. 
We'll probably look into providing a migration in the next major to remove `RouterLinkWithHref` entirely.
