### ISSUE TITLE
ngUpgrade fails to instantiate ROUTER_PROVIDERS

### ISSUE THREAD

**Issue by cur3n4** [angular/angular#5423]
I am trying to add the ROUTER_PROVIDERS to an angular 1 application via ngUpgrade:

```
var adapter: UpgradeAdapter = new UpgradeAdapter();

adapter.addProvider(HTTP_PROVIDERS);
adapter.addProvider(ROUTER_PROVIDERS);

adapter.bootstrap(document.body, ['angular-legacy']);
```

But when I try to use the routing config anywhere It fails with the following message:

`Error: Bootstrap at least one component before injecting Router `

**Comment by brandonroberts** [comment]
@cur3n4 You can't bootstrap an Angular 2 app while using ngUpgrade. If you want to use the component  router, you can use the Angular 1 version.

**Comment by cur3n4** [comment]
@brandonroberts Am I bootstraping the Angular 2 app? I thought I was just registering the providers for my Angular 2 components, but bootstrapping Angular 1. Is there any other limitation with using ngUpgrade or is it the main one around the routing?

**Comment by brandonroberts** [comment]
No, you're not bootstrapping Angular 2. In order to use ROUTER_PROVIDERS, you must bootstrap an Angular 2 component first, which you don't do at all while using ngUpgrade.

**Comment by PascalPrecht** [comment]
> which you don't do at all while using ngUpgrade.

This is not true. ngUpgrade bootstraps multiple Angular 2 components inside your Angular 1 module.

@cur3n4 Providers from Angular 2 world need to be downgraded in order to be used in A1 modules. However, as @brandonroberts mentioned, there's an A1 version of the component router that should be used for this particular use case.

I do think however, that you should be able to use `HTTP_PROVIDERS`.

**Comment by PascalPrecht** [comment]
Also, I don't see any A2 component in the snippet where any of those are used, which could also cause problems I guess.

**Comment by cur3n4** [comment]
Thanks a lot for that @brandonroberts and @PascalPrecht.

One question, all my components are currently Angular2 components and they work fine in Angular2. My intention is to be able to use a few Angular1 directives within the A2 components (i.e. the foo directive inside the AppComponent). I am not sure I understand what is the best way of doing this. Do I need to downgrade the A2 components even if they are never going to be required by A1 directives?  

The bootstrapping is more or less like this:

```
angular.module('angular-legacy',[]);
angular.module('angular-legacy').directive('foo', 
    function() {
      return {
        restrict: 'EAC',
        require: '?ngModel',
        link: function($scope, element, attrs, controller) {
          var controllerOptions, options;
          element.text('FOO');
        }
      };
    }
  );

var adapter: UpgradeAdapter = new UpgradeAdapter();

angular.module('angular-legacy').directive('app', adapter.downgradeNg2Component(AppCompnent));
 
adapter.addProvider(HTTP_PROVIDERS);
adapter.addProvider(ROUTER_PROVIDERS);

adapter.bootstrap(document.body, ['angular-legacy']);
```

And then AppComponent has something like:
```
template : `<foo></foo>`
directives:[new UpgradeAdapter().upgradeNg1Component('foo')]
```

**Comment by brandonroberts** [comment]
@cur3n4 if everything inside of your AppComponent is A2, you shouldn't need to downgrade those components also. Here is an example plunk with an A2 component inside AppComponent which was downgraded

http://plnkr.co/edit/QUVHavYN21ZGaeTdbFoc?p=preview

**Comment by cur3n4** [comment]
Great! Thanks a lot @brandonroberts .

Closing this issue and off to find out more about the new router.

**Comment by jusefb** [comment]
Just in case someone stumbles upon this please refer to the following issue to see how to use angular 2 router together with ngUpgrade [`Can not use Angualr 2 router in a component when using ngUpgrade`](https://github.com/angular/angular/issues/7147#issuecomment-185707020)

**Comment by ptomaszi** [comment]
@jusefb This solution no longer works for Angular 2 RC 4 as they changed how the router works. Any idea how to get that working on the latest release?
