### ISSUE TITLE
ADEV: do not show "On this page" section if there is only 1 item available

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#54236]
For example, see https://angular.dev/errors/NG0507 - it contains only 1 section and the "On this page" block looks redundant. The proposal is to update the code to show "On this page" if there is more than one item in that list.

**Comment by JeanMeche** [comment]
PR is open on the `dev-infra` repo.

**Comment by AndrewKushnir** [comment]
@JeanMeche thank you!

**Comment by twerske** [comment]
Closed by the linked PR!
