### ISSUE TITLE
Typo in Configuring interceptors

### ISSUE THREAD

**Issue by DevWedeloper** [angular/angular#54238]
### Describe the problem that you experienced

There's an extra when in

> [Configuring interceptors](https://angular.dev/guide/http/interceptors#configuring-interceptors)
You declare the set of interceptors to use when when configuring [HttpClient](https://angular.dev/api/common/http/HttpClient) through dependency injection, by using the [withInterceptors](https://angular.dev/api/common/http/withInterceptors) feature:

### Enter the URL of the topic with the problem

https://angular.dev/guide/http/interceptors#configuring-interceptors

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by  #53828  and is pending deployement on our side !
