### ISSUE TITLE
Link from In-dept guide on HttpClient on angular.dev leads to Page Not found

### ISSUE THREAD

**Issue by kabetai** [angular/angular#54244]
### Describe the problem that you experienced

Clicking on a link to [provideHttpClientTesting](https://angular.dev/api/common/http/provideHttpClientTesting) on [Test requests](https://angular.dev/guide/http/testing#testing-error-handling) in section Setup for testing leads to correct URL but it displays Page not found message instead of API documentation for provideHttpClientTesting() function.

### Enter the URL of the topic with the problem

https://angular.dev/guide/http/testing#testing-error-handling

### Describe what you were looking for in the documentation

Documentation for mocking HttpClient for testing.

### Describe the actions that led you to experience the problem

1. Navigate to [Test requests] (https://angular.dev/guide/http/testing#testing-error-handling) page
2. Scroll down to section Setup for testing 
3. Click on link to provideHttpClientTesting in sentence "To begin testing usage of [HttpClient](https://angular.dev/api/common/http/HttpClient), configure [TestBed](https://angular.dev/api/core/testing/TestBed) and include [provideHttpClientTesting](https://angular.dev/api/common/http/provideHttpClientTesting) in your test's setup."

### Describe what you want to experience that would fix the problem

Display API documentation for provideHttpClientTesting() function under the URL of https://angular.dev/api/common/http/provideHttpClientTesting

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/158306730/0fc9b197-c1b6-483d-81f9-f67ab1e95894)

### Provide any additional information here in as much as detail as you can

```true
For context, even if that's most likely irrelevant, this occurred on Firefox Browser 121.0.1 (64-bit)
```

**Comment by JeanMeche** [comment]
Hi, thank you for reporting that issue. We're tracking this under #52663 as some APIs entries are globally missing.
