### ISSUE TITLE
In the API documentation, many directives are labeled `class` instead of `directive`.

### ISSUE THREAD

**Issue by johnnygerard** [angular/angular#54249]
### Describe the problem that you experienced

For example, [NgIf](https://angular.dev/api/common/NgIf) has the `class` label in angular.dev instead of the `directive` label (see [NgIf](https://angular.io/api/common/NgIf) in angular.io).

Having the wrong label affects filtering as well. Angular.dev lists only two directives in the common package:

![angular dev_api](https://github.com/angular/angular/assets/57420910/25440fe5-1ff0-4aec-8009-641a407ffb9e)

Angular.io directives:

![angular io_api_type=directive](https://github.com/angular/angular/assets/57420910/0f6b31bc-3718-4292-8efa-f0eb6d7421d5)

**Comment by JeanMeche** [comment]
Hi, thank you for reporting this issue, we're already tracking this one via #52663.
