### ISSUE TITLE
computed signal does not recalculate when depending signal uses equality function

### ISSUE THREAD

**Issue by rearl** [angular/angular#54254]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Given the following simplified component:
```typescript
@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <h1>dynamic count that works : {{ list().length }}!</h1>
    <h2>computed doesn't update : [{{count()}}]</h2>
    <h2>effect does update : [{{countProp.length}}]</h2>
    <button (click)="add()">add</button>
  `,
})
export class App {
  list = signal<string[]>(['a', 'b'], {
    equal: (arr1: string[], arr2: string[]) => arr1.length === arr2.length,
  });
  count = computed(() => this.list().length);
  countProp: string[] = [];

  constructor() {
    effect(() => (this.countProp = this.list()));
  }

  add() {
    this.list.update((list) => {
      list.push('a');
      return list;
    });
    // it always works if a new array is created
    // this.list.update((list) => [...list, 'a']);
  }
}
```
The signal `count` is not recalculated even though the signal `list` is updated (due to the custom equality function it even emits if an item is added to the array). This is shown with the property `countProb` which is updated in the `effect()` (you can also add a `console.log()` inside `computed()` and `effect()` to see the issue on the console).

If a new array is created (instead to update the existing) the computed signal `count` is updated. As such, I assume the `computed()` function somehow still uses a "short-circuit" equality check which was (partially?) removed in  #53446.

**Please note that in my real use-case I don't have an array within the signal, but a `Map`**

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-6bxkei

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.2
Node: 20.9.0
Package Manager: pnpm 8.15.1
OS: win32 x64

Angular: 17.1.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.2 (cli-only)
@angular-devkit/build-angular   17.1.2
@angular-devkit/core            17.1.2
@angular-devkit/schematics      17.1.2
@schematics/angular             17.1.2
ng-packagr                      17.1.2
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by alxhub** [comment]
Your example is attempting to update `list` mutably, but the custom equality function doesn't handle mutable updates.

```typescript
this.list.update((list) => {
      list.push('a');
      return list;
    });
```

This call to `update` returns the same instance of the array (after pushing a new item). This will call `list.equal` with the _same instance of the array_ as `arr1` and `arr2`. Since the implementation compares `arr1.length === arr2.length` it will return `true`, which makes `list` assume nothing has changed (and not propagate a notification).

**Comment by rearl** [comment]
@alxhub thanks for your reply and explanation, which makes totally sense (embarrassing I didn't see that myself).
As a consequence, we must always provide a new instance for `set()` and `update()` for signals. After realising the issue, it is clear to me. Nevertheless, I think it would be helpful to add this to the [Signal guide](https://angular.io/guide/signals) - it should be especially mentioned in the section [Signal equality functions](https://angular.io/guide/signals#signal-equality-functions) which was misleading me (I see that the example is to show that two different instances with the same content should be considered equal).
