### ISSUE TITLE
Add comments to new control flow template syntax

### ISSUE THREAD

**Issue by itslenny** [angular/angular#54263]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

I've been converting my project to mostly use the new control flow template syntax and I'm really loving it. However, I find myself wanting to add comments to explain logic, and my only option is to use html comment syntax which winds up in the final rendered page, and I'd really love an option to have a comment syntax that does not show up in the rendered page, and it seems easy to add using the new `@` syntax.

### Proposed solution

I think just using `@//` makes a lot of sense

```
@// this is my comment explaining why this logic is here
@if (some complex logic) {
  <div>Some content</div>
} @else {
  <div>Some other content</div>
}
```

### Alternatives considered

I think `//` is the best, most obvious solution, but if `@//` causes parsing issues it could be `@comment` or similar.

**Comment by JeanMeche** [comment]
Comment nodes are striped from templates during the compilation, you shouldn't be seeing them.
