### ISSUE TITLE
possibly include system-polyfills.js in cdn

### ISSUE THREAD

**Issue by tenowg** [angular/angular#5426]
Microsoft Edge (and likely any other version of IE) requires system-polyfills.js from systemjs. It would be nice to have this included out of the box for those poor people that try to use Edge/IE.

If this can't be included, please at least note that you will need to install systemjs yourself and use your own dist for viewing in Edge/IE in the 5 minute quickstart.

thanks

**Comment by robwormald** [comment]
seems reasonable. Tracking over here : https://github.com/angular/code.angularjs.org/issues/30

**Comment by pkozlowski-opensource** [comment]
The thing is that SystemJS will try to download polyffils for things like Promise etc. (which I really don't think it should be doing...). But it won't do it if things are needed are already available. 

So imo a "proper" way of solving this is to include es6 shim _before_ SystemJS - you will need those for IE anyway and it will prevent SystemJS from firing its XHR little thingy thus saving one round-trip to a server.

Deploying system-polyfills.js won't hurt but it might put users on sub-optimal track. So I would rather vote for deploying es6 shim.

**Comment by tenowg** [comment]
I will attempt again later, but I did look at the appendix on the 5 minute
quick start, and tried to include es6shim and it still required
system-polyfills and would fail to load the app.
