### ISSUE TITLE
Typo on 'Helpful Note'

### ISSUE THREAD

**Issue by dbhaduri** [angular/angular#54279]
### Describe the problem that you experienced

The note reads 'For information on binding to properties, see Event binding.'

Should read 'For information on binding to properties, see Property binding.'

### Enter the URL of the topic with the problem

https://angular.dev/guide/templates/event-binding

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/3266002/87217edc-d33a-4ea1-abac-345961638a9b)

**Comment by eslammahgoub** [comment]
Hi 👋  can I take this?

**Comment by JeanMeche** [comment]
The issue has already been solved but thank you for proposing your help !
