### ISSUE TITLE
Repeted text (typo) In Component In-depth guide

### ISSUE THREAD

**Issue by dbhaduri** [angular/angular#54278]
### Describe the problem that you experienced

Repeated text (appears 2x in the first few lines of the doc):

A [CSS selector](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors) that defines how the component is used in HTML
You provide Angular-specific information for a component by adding a [@Component](https://angular.dev/api/core/Component) [decorator](https://www.typescriptlang.org/docs/handbook/decorators.html) on top of the TypeScript class:

### Enter the URL of the topic with the problem

https://angular.dev/guide/components

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/3266002/ab738123-28aa-42a0-b36c-6dc8814d7e56)

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52587 and is pending deployement on our side !
