### ISSUE TITLE
Allow setting the equal function on signal inputs

### ISSUE THREAD

**Issue by eiswind** [angular/angular#54270]
### Description

I am missing a way to set a custom equal on signal inputs. This is relevant when refetching content from a backend, where a deep equal should be cheaper then updating the signal if the model object has not changed but is actually a new instance.

### Proposed solution

Allow  equal function to be set on the input({ equal: fn})

### Alternatives considered

Did I miss something here?

**Comment by JoostK** [comment]
Duplicate of #54111
