### ISSUE TITLE
Querying ViewChild(ren) within currently active `@switch` case

### ISSUE THREAD

**Issue by moniuch** [angular/angular#54285]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

I've been trying to get to work a simple study case on how to dynamically load components using the new `@switch` syntax. I have never done it before, so I lack expertise to tell whether this is just the control flow being too fresh atm, or I'm missing some bits to make it work.

### Stackblitz:
https://stackblitz.com/edit/stackblitz-starters-xepthd?file=src%2Fmain.ts
(the code can be messy, I was just exploring different approaches)

### Shortly:
I dynamically load a component, based on user `mode` selection, each of the components that I expect to load, has to implement a specific abstract class, so that I can safely call their method no matter which one is loaded.

Here, let me paste the main html file which should demonstrate what I am after

```html
<div>
  <select (change)="selectTemplate(templateSelect.value)" #templateSelect>
    <option value="one">One</option>
    <option value="two">Two</option>
  </select>

  <section #vcr #components>
    @switch(mode){
      @case('one'){
        <app-form-one #component />
      }
      @case('two'){
        <app-form-two #component />
      }
    }
  </section>

  <button (click)="submit()">Submit</button>
</div>
```

### Proposed solution

It is difficult for me to suggest proposed solutions (maybe it's already solved?) but as a developer I find this scenario way too complex, and I think the new control flow syntax might also feature some ways to accomplish that.

I would like to be able to easily get a reference of the currently loaded component within the `@switch` block:
- either via `ViewContainerRef` and `read` query (by the class implemented),
- or via `@ViewChild` + `read` query,
- or `@ViewChildren` + read query
- or a method to call on VCR to get the component/implemented class on demand (here: in the submit method)

I think in this case the most intuitive way would be via `@ViewChildren` and accessing `first`, but maybe the `@switch` syntax could also be extended to always map the current case to a variable.

Maybe there are other ways to achieve same goal, but I think various components implementing an abstract class is pretty clean and legit to pursue in this scenario.

### Alternatives considered

None comes to mind.

**Comment by alxhub** [comment]
I don't fully understand what you're suggesting is not working in your example, but I see two problems:

1. The `@ViewChild` query you have is marked as `static: true`, which means it resolves at creation time (before the `@switch` is ever executed). Switching it to `static: false` causes the query to start picking up the current `#component` as the `@switch` changes.

2. The `@ViewChildren` query is trying to `{read: SubmittableComponent}`. `read` is a DI concept, but there are no providers for `SubmittableComponent`. To make this work, each component you want to match the query needs to actually provide this token (probably using itself as implementation). For example:

```typescript
@Component({
  // ...
  providers: [
    {
      provide: SubmittableComponent,
      useExisting: forwardRef(() => FormOneComponent),
    },
  ],
})
export class FormOneComponent
  implements OnInit, SubmittableComponent<FormOneValue>
{...}
```

**Comment by moniuch** [comment]
@alxhub Thank you, the provider hint is what I was missing, now with `multi: true` it's now working. Can be closed.
