### ISSUE TITLE
Library for messaging between disconnected components

### ISSUE THREAD

**Issue by varghesep** [angular/angular#5428]
I'm future proofing a angular2 project, and has to decide on what messaging framework/library I can use with Angular2. What I'm looking for is a pub-sub with a mediator like EventEmitter, so disconnected components can subscribe and publish messages on a local message bus. 

I looked at Flux, RxJS, Redux etc... I can use one of them or something that comes natively with Angular2. Is there a natively supported reactive library in Angular2?

**Comment by robwormald** [comment]
Angular2 uses RxJS, and the `async` supports it and any other Observable that implements the ES specification. That said, any JS based pubsub system will work.
