### ISSUE TITLE
refactor(linker): Expose PipeResolver to public api

### ISSUE THREAD

**Issue by rosendi** [angular/angular#5429]
Expose PipeResolver from `core/linker/pipe_resolver.ts`.

https://github.com/rosendi/angular/blob/refactor-linker-expose-PipeResolver-to-public-api/modules/angular2/src/core/linker.ts#L14

Affects `public_api_spec.ts` @mhevery

**Comment by pkozlowski-opensource** [comment]
`PipeResolver` is an internal API and as we inch towards the final release APIs are frozen. It won't be made public unless there are _very_ good reasons.

I'm going to close this issue but happy to re-open when you've got a killer use-case that would make us to re-consider.

**Comment by remmeier** [comment]
all kinds of UI components need customizations, there are two possiblities:

1. getting a template with @ContentChild
2. passing a pipe as @Input

the later seems simpler/easier/sufficient for many typical use cases. Note that people usually do not want to apply the pipe in NgModel, only the representation needs to be "piped", not the model that potentially is sent to event subscribers.

I assume such a pipe input would be of type string? And then there should be a possiblity to obtain the pipe as requested by this ticket.
