### ISSUE TITLE
Host styles incorrectly applied to components in child router outlets

### ISSUE THREAD

**Issue by jgosar** [angular/angular#54304]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I have two `router-outlet`s in a view. Each is supposed to show a different child component, according to the routes configuration.

Each of the child components has a `:host` style, which is supposed to be applied to it. The components are using `encapsulation: ViewEncapsulation.Emulated`.

I would expect each of the child components to have its own style applied. But instead both components are using the style of the first one.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-rhnecp

### Please provide the exception or error you saw

```true
In this example the component `router-outlet-1` is supposed to have a reddish color:

:host{
  background-color: #f88;
}
```

And `router-outlet-2` is supposed to have a bluish color:
```
:host{
  background-color: #88f;
}
```

Instead both components appear red.

In the example above, both injected components have the same HTML attribute (`_nghost-ng-c1318069141`) in the DOM, so that's why the same styles are applied to them:
```
<app-slots-view _nghost-ng-c3610984434="">
  This is a view with some child routes
  <br _ngcontent-ng-c3610984434="">
  <router-outlet _ngcontent-ng-c3610984434="" name="slotA" ng-reflect-name="slotA">
  </router-outlet>
  <ng-component _nghost-ng-c1318069141=""><
    I am Router outlet 1
  </ng-component>
  <!--container-->
  <br _ngcontent-ng-c3610984434="">
  <router-outlet _ngcontent-ng-c3610984434="" name="slotB" ng-reflect-name="slotB">
  </router-outlet>
  <ng-component _nghost-ng-c1318069141="">
  I am Router outlet 2
  </ng-component>
  <!--container-->
</app-slots-view>
```

And the generated style:
```
[_nghost-ng-c1318069141] {
    background-color: #f88;
}
```
I believe that there should be a difference between both host elements, so that different styles could be applied to them.
```


### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.1.2
Node: 18.13.0
Package Manager: npm 8.19.3
OS: linux x64

Angular: 17.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.2
@angular-devkit/build-angular   17.1.2
@angular-devkit/core            17.1.2
@angular-devkit/schematics      17.1.2
@schematics/angular             17.1.2
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

### Anything else?

A workaround is to add `selector`s to both components as in this example: https://stackblitz.com/edit/stackblitz-starters-gs1pji

But I don't think selectors should be required for components that are only used in `router-outlet`s.

**Comment by JoostK** [comment]
This is explained by the reported warning:

> NG0912: Component ID generation collision detected. Components 'RouterOutlet1Component' and 'RouterOutlet2Component' with selector 'ng-component' generated the same component ID. To fix this, you can change the selector of one of those components or add an extra host attribute to force a different ID. Find more at https://angular.io/errors/NG0912

Please find more info in #50158; I'd suggets introducing a difference in metadata using the `exportAs` property.

**Comment by jgosar** [comment]
Thanks for your response @JoostK . I haven't noticed the warning, which does explain the problem.

However I think that this warning should only appear when the developer manually configures the same `selector` on two different components. If no `selector` is specified, the framework should have some other mechanism to tell the two components apart.

At a minimum I think the help page for this warning should mention that this can happen if you specify no `selector`, not just when you specify the same one in different components.

**Comment by JeanMeche** [comment]
> If no selector is specified, the framework should have some other mechanism to tell the two components apart.
As explained in #50158, the framework already uses what it can. Class names can't be used because of class name mangling in prod builds. (Which can/will be different on client/server builds with SSR).
