### ISSUE TITLE
Observing an input changes

### ISSUE THREAD

**Issue by behzadeshan** [angular/angular#5430]
I have a filter-form for filtering a datagrid's data, so I need to observe all of its inputs' change. I used (change) event but it's not working correctly, I also used Object.observe. Is there a better way for doing this? except that I don't want to create a component class for each of inputs to use `OnChange` hook or `EventEmitter`.

**Comment by robwormald** [comment]
Use the form builder to create a control group: http://plnkr.co/edit/HyQ16kTOE3cBxQA5MExM

**Comment by robwormald** [comment]
alternately, use the (keyup) or (input) event, as (change) will only fire when the input blurs. See http://plnkr.co/edit/9XXVcWDVMz7te6odAbtT

Please ask these sorts of questions on gitter, and reserve Github issues for actual issues and bug reports. Thanks!

**Comment by behzadeshan** [comment]
@robwormald isn't there another way? because I hate writing extra code, for example with jQuery or even with the first version of Angular I am able to write only one callback for handling such a thing, now I think creating a form builder is an extra code. By the way I think it is an actual issue, because lack of Angular 2 `watch` feature effects simplicity of my code.

**Comment by robwormald** [comment]
You have 3 options:
- use a single callback with (keyup) or (input)
- individually create `Control` instances and observe individual values.
- observe an entire group with `FormBuilder` and observe it all at once. 

`Object.observe` is dead, and it is unlikely Angular will implement anything along those lines. `FormBuilder` gives you the option to Observe all values at the same time, including validation, with a minimum amount of code. Is there something more concise you'd like to see?

**Comment by behzadeshan** [comment]
It's not just about being concise.  it's also about simplicity and separation of concepts. Also these ways are not concise at all in comparison to Angular 1.
* using (input) or (keyup) means adding something to markup, while the reason that I have choose Angular over jQuery is elimination of markup manipulation when writing its logic.
* creating `Control` or `FormBuilder` means extra code and also means manipulating markup again. while I think in MVVM we should interact with model(only ng-model) not with control that should be attached to markup with an extra attribute(`ng-control`). Why shouldn't we be able to observe model instead of input? Isn't Angular 2 MVVM anymore?
These ways effects markup too much. It should add only an ng-model to markup normally like other MVVM framework. What will be happened when I want to rebuild my markup and use for example zurb foundation instead of bootstrap? I should care about my markup because it's tightly bounded to my Angular logic.
I am thinking in Knockout and Angular 1 MVVM way. I think Angular 2 is totally going a different way, and it seems to me like writing code in a decade ago fashion. Honestly Angular 2.0 seems to me like a new version of jQuery not a MVVM framework that should eliminate relation between markup and its logic.
