### ISSUE TITLE
Doc is not understandable and duplicate topics

### ISSUE THREAD

**Issue by thanhtutzaw** [angular/angular#54312]
### Describe the problem that you experienced

I was reading doc and doing the route link . 
Here is the same topic but different content . I mean it should provide screenshot just like this photo
**Angular Providing import code**
![Screenshot (597)](https://github.com/angular/angular/assets/71011043/f35d28f7-44d8-464b-8fcd-83e6cb8f3b35)

**Without providing a screenshot**
![Screenshot (598)](https://github.com/angular/angular/assets/71011043/f421da01-b71d-4cf2-b114-d77fe385bb4f)

### Enter the URL of the topic with the problem

https://angular.io/guide/router-tutorial

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating the angular.io docs in favor of https://angular.dev. 

Did you take a look at the router docs : https://angular.dev/guide/routing ? Are they more clear to you ?

**Comment by JeanMeche** [comment]
Closing as the docs have been re-written for adev.
