### ISSUE TITLE
SSR issue with page reload upon child routes

### ISSUE THREAD

**Issue by stanchev89** [angular/angular#54310]
### Which @angular/* package(s) are the source of the bug?

platform-browser, platform-server

### Is this a regression?

Yes

### Description

Hello everyone,

I'm aware of this issue https://github.com/angular/angular-cli/issues/26323, but I believe my situation differs slightly. I'm currently facing challenges with investigating our upcoming potential Server-Side Rendering (SSR) migration. I'm struggling to identify the source of the problem.

Here's the scenario: We aim to trigger an API call from the server based on a query parameter, requiring us to provide the REQUEST from the server. Then, within the APP_INITIALIZER, we check the server environment and make the API call based on the query parameter. Everything functions correctly, but only for the '/' main route. When navigating to another path and reloading the page, we observe that the REQUEST is labeled as 'unknown'. Shouldn't the behavior be consistent, distributing the REQUEST and APP_INITIALIZER action independent of the current path?

Another peculiar observation is that I've logged 'APP_INITIALIZER -> SERVER' for each server iteration within the app initializer. Strangely, when the issue arises, this log isn't displayed. However, the handler is triggered, suggesting that the initializer is indeed executed.

You can find the repository with a prepared reproduction below:
[](https://github.com/stanchev89/ng-ssr-issue)

1. Install dependencies.
2. Run "npm run watch" (ng build --watch --configuration production).
3. Run "npm run serve:ssr:test-ssr" (node dist/test-ssr/server/server.mjs).

### Please provide a link to a minimal reproduction of the bug

https://github.com/stanchev89/ng-ssr-issue

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular-devkit/architect       0.1701.0
@angular-devkit/build-angular   17.1.0
@angular-devkit/core            17.1.0
@angular-devkit/schematics      17.1.0
@schematics/angular             17.1.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.3
```

**Comment by alan-agius4** [comment]
What is happening in this case is that pages are being static generated (prerendering) and served as a static page. If you need these pages to be server rendered you can disable prerendering by setting `"prerender": false` in your `angular.json`

**Comment by stanchev89** [comment]
Thank you, Alan!
