### ISSUE TITLE
RouterLink Import Error not complain

### ISSUE THREAD

**Issue by thanhtutzaw** [angular/angular#54313]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

I need to see error message if I missed a import for RouterLink in html template file . 

![image](https://github.com/angular/angular/assets/71011043/fe60227e-d164-44cf-a08c-a1a61d803a4f)

**Comment by JoostK** [comment]
This is due to #3425, where Angular doesn't check attributes on an element.
