### ISSUE TITLE
Command Reference Link redirect to 404

### ISSUE THREAD

**Issue by Krizald18** [angular/angular#54321]
### Describe the problem that you experienced

In docs under "The Angular CLI", the link to "Command Reference" redirects to a 404 page.

### Enter the URL of the topic with the problem

https://angular.dev/tools/cli

### Describe what you were looking for in the documentation

The Command Reference page

### Describe the actions that led you to experience the problem

Once clicked the link got me to a 404 page.

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52549  and is pending deployement on our side !
