### ISSUE TITLE
inject docs 404 bad link

### ISSUE THREAD

**Issue by dolanmiu** [angular/angular#54328]
### Describe the problem that you experienced

When clicking on "Try out Inject" in:

https://angular.dev/roadmap#:~:text=in%20control%20flow-,Try%20out%20Inject,-New%20CDK%20directives

it gives a "Page Not Found 🙃" message

### Enter the URL of the topic with the problem

https://angular.dev/roadmap

### Describe what you were looking for in the documentation

I was looking for inject guides

### Describe what you want to experience that would fix the problem

I would like the page to navigate to: https://angular.dev/guide/di

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52541 and is pending deployement on our side !
