### ISSUE TITLE
Locale is not loaded automatically when using ng build, but it is when using ng serve

### ISSUE THREAD

**Issue by JustDoItSascha** [angular/angular#54320]
The corresponding locale is not loaded by default, you need to do it yourself. 

```
import localeEnGB from '@angular/common/locales/en-GB';
registerLocaleData(localeEnGB );
```

_Originally posted by @JeanMeche in https://github.com/angular/angular/issues/51534#issuecomment-1695606412_
            
We had the same error like in the issue above. When I look into the current docs, there is no mentioning of registerLocaleData anymore. How should one know that this is still necessary?

**Comment by JeanMeche** [comment]
`registerLocaleData` is required if you don't leverage the CLI to setup i18n. 

Do you mind sharing a github repo repro of a project with the mentionned issue.

**Comment by JustDoItSascha** [comment]
The issue is not in a project. The issue is, that the information "registerLocaleData is required if you don't leverage the CLI" is not documented in the angular docs. The `registerLocaleData` is not mentioned a single time.

The i18n section of angular docs is just focussing on the translation part, which is still more than bad in angular. But it's not mentioning a way to just change the locale which I think is a more important feature.

**Comment by alan-agius4** [comment]
Let’s continue tracking this as part of https://github.com/angular/angular/issues/46851
