### ISSUE TITLE
Angular About page is missing

### ISSUE THREAD

**Issue by sonukapoor** [angular/angular#54330]
### Describe the problem that you experienced

The "Angular About" page is missing.

Links:

[angular.io page](https://angular.io/about)

I am happy to contribute to port this page over. 

@twerske Please take a look at this.

**Comment by JeanMeche** [comment]
From what I remember this page was dropped from the MVP but it was suggested that I with add it back we would pull infos from GitHub (like pictures etc) for maintenance reasons.

**Comment by twerske** [comment]
This was intentional in its removal since the angular.io page is not kept up to date and has low traffic. 

Alternatively we now link to the GDE roster in the footer and could add the team contributors via GitHub. 

Closing this as not planned!
