### ISSUE TITLE
main.ts:5 ERROR FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call initializeApp() first (app/no-app).

### ISSUE THREAD

**Issue by lakhveer02** [angular/angular#54332]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

Yes

### Description

![Screenshot from 2024-02-08 12-25-36](https://github.com/angular/angular/assets/145571717/d1ab92ff-e2fa-4f14-943a-c4db06dcb448)

### Please provide a link to a minimal reproduction of the bug

zcz

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.2
Node: 20.3.0
Package Manager: npm 9.6.7
OS: linux x64

Angular: 17.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr
```

### Anything else?

![Screenshot from 2024-02-08 12-25-36](https://github.com/angular/angular/assets/145571717/0dd2b7dd-ab0b-428c-af64-c8adba738846)

**Comment by lakhveer02** [comment]
![Uploading Screenshot from 2024-02-08 12-25-36.png…]()

**Comment by lakhveer02** [comment]
![Uploading Screenshot from 2024-02-08 12-25-36.png…]()

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
