### ISSUE TITLE
Ambient directives and unit tests with TestComponentBuilder

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#5433]
Spotted by @teropa and confirmed on my side in the ng2 directives for Bootstrap project (see: https://github.com/ng-bootstrap/core/pull/115):

> I'm getting errors about platform directives like ng-for when using TestComponentBuilder. Seems like they're not "ambient" in the unit tests like they are during normal execution.  I can fix it by including CORE_DIRECTIVES in the component, but that seems backward. Any ideas how to make them available?

**Comment by tbosch** [comment]
Same is true for platform pipes

**Comment by juliemr** [comment]
Related to https://github.com/angular/angular/issues/5351

There's a fix in https://github.com/angular/angular/pull/5937

**Comment by juliemr** [comment]
Note the design at #5351

I'm not closing this as a duplicate since it's a more precise issue than the one that #5351 tries to solve, and is easier to search for.

**Comment by stefanocke** [comment]
As a workaround, the following worked for me: 
```
beforeEachProviders(() => [  provide(PLATFORM_DIRECTIVES, {useValue: CORE_DIRECTIVES, multi: true})]);
```
So one can at least avoid to add the core directives in the components and keep the workaround in the test files.

**Comment by juliemr** [comment]
This is fixed with b0cebdba6b65c1e9e7eb5bf801ea42dc7c4a7f25

**Comment by Foxandxss** [comment]
That is not released yet, right?

**Comment by pkozlowski-opensource** [comment]
> That is not released yet, right?

Nope, just landed in master, will be part of beta.2
