### ISSUE TITLE
Allow `computed` computation function to access previous value

### ISSUE THREAD

**Issue by rlmestre** [angular/angular#54339]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

A long, interesting, and possibly unfinished [discussion](https://github.com/angular/angular/discussions/49683#discussioncomment-5598532) developed in sub-RFC 2 about signal APIs, pure functions, and [hysteresis](https://github.com/angular/angular/discussions/49683#discussioncomment-5612162).

Can, and should, `computed` computation functions have access to their previous computation's result?

I haven't personally run into an use-case for this, and I don't have enough knowledge to post an opinion, but figured we could resurface this, whether it's to continue the discourse or for visibility into why it can't (or won't) be done.

Resources:
- Sub-RFC 2: https://github.com/angular/angular/discussions/49683
- Thread in RFC (again): https://github.com/angular/angular/discussions/49683#discussioncomment-5598532
- Comment where @alxhub says this is "worth considering" 😬: https://github.com/angular/angular/discussions/49683#discussioncomment-5612162
- SO question: https://stackoverflow.com/questions/77689615/is-there-a-way-to-use-the-previous-value-of-a-computed-angular-signal
- `ngxtension-platform`'s since-deprecated `computedExtended`: https://github.com/nartc/ngxtension-platform/blob/main/libs/ngxtension/computed/src/computed.ts

### Proposed solution

Pass the value to the computation function. I realize it's not as straightforward as this; I'm just trying to bring forth all the information I've gathered.

https://github.com/angular/angular/blob/ca239e8b62017b8460d73e58085d0f1c53a642ff/packages/core/primitives/signals/src/computed.ts#L110-L117

```ts
type SomeUnsetRepresentation = undefined; // or UNSET which is currently not exported?
export declare function computed<T>(
  computation: (previousValue: T | SomeUnsetRepresentation) => T, 
  options?: CreateComputedOptions<T>
): Signal<T>;
```

### Alternatives considered

Lots of potential solutions were proposed in [that thread](https://github.com/angular/angular/discussions/49683#discussioncomment-5598532) of the sub-RFC but none are ideal. (using RxJS; delaying computed; tracking the values independently; etc.)

**Comment by JoostK** [comment]
This sounds a bit scary to me; it would mean that computeds are no longer a derivation of the state, but potentially about how the state was _changed_. To me, the beauty of signals is how all state "falls out" the recorded facts (`WritableSignal`)

**Comment by alxhub** [comment]
Yep - this adds "hysteresis" to computeds, which drastically changes mental model of state derivation. It could also be _very_ confusing since computeds are not guaranteed to be re-evaluated for every state change, so code like this _looks_ reasonable but doesn't work at all:

```typescript
const sum = computed((prev) => prev + value());
```

I think we would like to understand what the use cases are where having access to the previous value makes something possible that was hard to do without it.

**Comment by pfeileon** [comment]
I'd argue that this is one of the situations where you want to use a stream and not a signal. Imho this is exactly why signals don't replace rxjs and that's not a bad thing.

**Comment by anhallbe** [comment]
I know this issue is closed. But has anybody figured out a solution for this (without changing the current `computed`)?

My use-case is I have a model that can take on different types, and I want to keep track of the last selected value of each type. Think:

```ts
type Product = { fruit: string } | { vegetable: string };

function reduce<T>(fn: (prev: T) => T) {
  // Magic
}

const selectedProduct = signal<Product>(...);
const lastSelectedFruit = reduce(prev => selectedProduct().fruit ?? prev);
const lastSelectedVegetable = reduce(prev => selectedProduct().vegetable ?? prev);
```

I can solve by keeping track of the "lastSelectedX" as separate variables and changing them with an `effect()`, but it feels a bit wrong... Especially since the value of "lastSelectedX" are supposed to be used in a template.

**Comment by pfeileon** [comment]
The clean solution is to use a stream instead of a signal.

**Comment by Harpush** [comment]
@anhallbe I would do something like that:
```ts
export interface SignalWithPrev<T> extends WritableSignal<T> {
  previousSignal: Signal<T | undefined>;
}

export function signalWithPrev<T>(
  initialValue: T,
  options?: CreateSignalOptions<T>
): SignalWithPrev<T> {
  const currentSignal = signal(initialValue, options);
  const previousSignal = toSignal(
    toObservable(currentSignal).pipe(
      startWith(undefined),
      pairwise(),
      map(([prev]) => prev)
    )
  );

  Object.defineProperty(currentSignal, 'previousSignal', {
    value: previousSignal,
    configurable: true,
  });

  return currentSignal as SignalWithPrev<T>;
}
```
Usage later:
```ts
const a = signalWithPrev(2);

effect(() => console.log(a.previousSignal(), a()));

a.set(5); // No log
a.set(6); // No log
a.update((x) => x + 1); // No log
a.set(2); // No log

setTimeout(() => a.set(3)); // Logs - 2, 3

// Before setTimeout runs logs - undefined, 2 once
```

**Comment by anhallbe** [comment]
I ended up with this:

```ts
function computedWithPrev<T>(computation: (prev: T | undefined) => T): Signal<T> {
	let previous: T;
	return computed(() => {
		const newValue = computation(previous);
		previous = newValue;
		return newValue;
	})
}

```

It's possible that I'm missing something, but I think it works pretty well.

Usage (based on the fruits example above):

```ts
lastSelectedFruit = computedWithPrev(prev => selectedProduct().fruit ?? prev);
```
