### ISSUE TITLE
Some styles rules are missing in the new angular.dev Style Guide

### ISSUE THREAD

**Issue by Puigcerber** [angular/angular#54341]
### Describe the problem that you experienced

Hi! When checking the new https://angular.dev/style-guide I'm missing some style rules that were present in https://angular.io/guide/styleguide but not sure if this was intended tho, as some of the rules seem still valid.

### Enter the URL of the topic with the problem

https://angular.dev/style-guide

### Describe what you were looking for in the documentation

In my particular case I was looking for the https://angular.io/guide/styleguide#member-sequence 

#### Style 05-14

<div class="s-rule do">

**Do** place properties up top followed by methods.

</div>

<div class="s-rule do">

**Do** place private members after public members, alphabetized.

</div>

<div class="s-why-last">

**Why**? <br />
Placing members in a consistent sequence makes it easy to read and
helps instantly identify which members of the component serve which purpose.

</div>

https://github.com/angular/angular/blob/ca239e8b62017b8460d73e58085d0f1c53a642ff/aio/content/guide/styleguide.md#member-sequence 

### Describe what you want to experience that would fix the problem

Clarification if this and other styles are not longer valid, or restoring the previous; happy to help in this case.

**Comment by JeanMeche** [comment]
Thank you for you're suggestions., 
We're planning to rewrite the style guide for v18. We're tracking this under the following umbrela issue : #54284
