### ISSUE TITLE
Update Angular.dev Docs: Address 'card-title' and 'card-body' Error in Multiple Content Placeholders Example

### ISSUE THREAD

**Issue by surajchopra1234** [angular/angular#54343]
### Example:

This is an example from the Angular.dev docs demonstrating [Multiple content placeholders](https://angular.dev/guide/components/content-projection#multiple-content-placeholders)

```
<!-- Component template -->
<div class="card-shadow">
  <ng-content select="card-title"></ng-content>
  <div class="card-divider"></div>
  <ng-content select="card-body"></ng-content>
</div>
```
```
<!-- Using the component -->
<custom-card>
  <card-title>Hello</card-title>
  <card-body>Welcome to the example</card-body>
</custom-card>
```

### Error:

'card-title' is not a known element:
1. If 'card-title' is an Angular component, then verify that it is included in the '@Component.imports' of this component.
2. If 'card-title' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@Component.schemas' of this component to suppress this message.ngtsc(-998001).

'card-body' is not a known element:
1. If 'card-body' is an Angular component, then verify that it is included in the '@Component.imports' of this component.
2. If 'card-body' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@Component.schemas' of this component to suppress this message.ngtsc(-998001).

### Missing Example:

There is no example about **Conditional Content Projection**.

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/content-projection#multiple-content-placeholders

### Describe what you were looking for in the documentation

I'm looking for information about **multiple content placeholders** in components and **conditional content projection** in Angular.dev new documentation.

**Comment by geromegrignon** [comment]
This guide is not meant to be a tutorial in my mind. The related snippet acts as an example.

Adding content to create both components would just create noise in this guide.
