### ISSUE TITLE
Hydration does not work when the root component is self-closing.

### ISSUE THREAD

**Issue by SIM128** [angular/angular#54355]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Hello,

I've observed a bug that prevents hydration from taking effect without any notice.

**Actual Behavior:**
When running an SSR app and the page is loaded, hydration does not take effect (there's no console output like "Angular hydrated...").

**Expected Behavior:**
It should work with self-closing tags.
Alternatively, I would expect a clear error message indicating that self-closing tags are not supported for hydration.

**Steps to Reproduce the Issue:**
1. Create a new SSR project with `ng new --ssr`.
2. Replace `<app-root></app-root>` with `<app-root />` in index.html.
3. Serve the app with `ng serve`.

### Please provide a link to a minimal reproduction of the bug

see above.

### Please provide the exception or error you saw

```true
n/a
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 17
```

**Comment by JeanMeche** [comment]
Hi, thank you for reporting this issue. It has been reported in #52922, lets continue the discussion over there.
