### ISSUE TITLE
Unable to bind to 'for' property of <label> element

### ISSUE THREAD

**Issue by pcroc** [angular/angular#5435]
I'm creating a reusable form control incorporating a `<label>` element, and I want to use the 'for' attribute to associate the label with the control:

Neither of these works:

```html
<label for="{{ fieldId }}" class="form-control-label col-sm-6">{{ label }}</label>
<label [for]="fieldId" class="form-control-label col-sm-6">{{ label }}</label>
```
(fieldId is automatically generated).

This produces an error in the browser:
**EXCEPTION: Template parse errors:
Can't bind to 'for' since it isn't a known native property in TextField > div:nth-child(1) > label:nth-child(1)[for={{ fieldId }}]**

or:
**EXCEPTION: Template parse errors:
Can't bind to 'for' since it isn't a known native property in TextField > div:nth-child(1) > label:nth-child(1)[[for]=fieldId]**

**Comment by PascalPrecht** [comment]
@pcroc the problem is that there is no `for` property on the native label element. It only has a `for` attribute. So you need to use `<label [attr.label]="{{fieldId}}">`

**Comment by pkozlowski-opensource** [comment]
@PascalPrecht is totally right! 

@mhevery this one comes quite often, maybe we should alias `for` => `attr.for`? I know it would create a special case, but since this is so common....

**Comment by select** [comment]
Thanks for the answers, I was stuck at exactly this. The current solution is not very intuitive so +1 for another solution.
I tried `<input id="{{item._id}}+c1" type="checkbox"><label for="{{item._id}}+c1"></label>` and was quite confused why `id` worked but `for` failed

**Comment by select** [comment]
Thanks for the answers, I was stuck at exactly this. The current solution is not very intuitive so +1 for another solution.
I tried `<input id="{{item._id}}+c1" type="checkbox"><label for="{{item._id}}+c1"></label>` and was quite confused why `id` worked but `for` failed

**Comment by Lanayx** [comment]
`<label [attr.for]="{{item._id}}c1"></label>` doesn't work as well. 
What is works currently (beta7) is `<label [attr.for]="item._id+'c1'"></label>`

**Comment by zoechi** [comment]
`<label attr.for="{{item._id}}c1"></label>` would work. If you have `{{...}}` don't use `[...]`

**Comment by Lanayx** [comment]
Thank you, that's true, valuable comment.

**Comment by poke** [comment]
The DOM *property* is called [`htmlFor`](https://developer.mozilla.org/en/docs/Web/API/HTMLLabelElement) so you can also bind to that instead of the attribute:

```
<label htmlFor="{{item.id}}">…</label>
<input id="{{item.id}}" />
```
