### ISSUE TITLE
Layout error in 'Injection context"

### ISSUE THREAD

**Issue by dbhaduri** [angular/angular#54368]
### Describe the problem that you experienced

codeblock "CanActivateFn = (route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => { return inject(PermissionsService).canActivate(inject(UserToken), route.params.id); };" (following the phrase "Here is an example for CanActivateFn"... is rendered as plain paragraph text.  It should be in a code block.

### Enter the URL of the topic with the problem

https://angular.dev/guide/di/dependency-injection-context

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #53531 and is pending deployement on our side !
