### ISSUE TITLE
Add banner linking to new docs on old documentation site

### ISSUE THREAD

**Issue by daniela-bonvini** [angular/angular#54361]
### Describe the problem that you experienced

Nowhere in the old documentation is cited the new docs site

### Enter the URL of the topic with the problem

https://angular.io/

### Describe the actions that led you to experience the problem

When searching for "Angular docs" on a search engine (I tried with Google, Firefox and Edge), the first result is very likely to be angular.io instead of the newer angular.dev

### Describe what you want to experience that would fix the problem

 Since there is the new angular.dev documentation and the old one is going to be deprecated in the near future, I suggest implementing at the top of the old doc site a banner saying that there is a newer site to reference, with a link to it

**Comment by JeanMeche** [comment]
Currently Angular.dev isn't indexed as it's still in a beta status (cf https://angular.dev/robots.txt)

**Comment by twerske** [comment]
We will be adding a redirect in v18 for people to automatically be brought to Angular.dev starting the next release!
