### ISSUE TITLE
Proposal: Create new <ng-host> html element as root element in template for more native hostBinding

### ISSUE THREAD

**Issue by dentiman** [angular/angular#54374]
General idea is to keep host binding properties as attributes for new root <ng-host> element in
component template instead of using @HostBinding and @HostListener decorators or host metadata property in @Component decorator.

### Current host binding
```typescript
@Component({
  selector: 'app-button',
  templateUrl: './app-button.component.html',
  host: {
    '[class]': 'class',
    '(click)': 'handleClick()',
    '[attr.disabled]': 'disabled'
  }
})
```

### Proposal host binding
```typescript
@Component({
  selector: 'app-button',
  template: `
        <ng-host class="..." (click)="handleClick()" [disabled]="disabled"  >
            <div>Content</div>
        </ng-host>
`
})
```

### Benefits:
- Attribute autocomplete better in html than in .ts file
- better readability, especially when we have long static css class  list
- no need to use @HostBinding and @HostListener decorators or host property in @Component decorator

related to https://github.com/angular/angular/issues/19119

**Comment by JoostK** [comment]
This is the idea behind #19119 (as you linked), so I am going to close this as a duplicate.
