### ISSUE TITLE
retain ngOnChanges on signal components

### ISSUE THREAD

**Issue by robertIsaac** [angular/angular#54372]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

it's mentioned in the [RFC 3: Signal-based Components](https://github.com/angular/angular/discussions/49682) that ngOnChanges  will not be retained

> ngOnChanges - is used to observe changes to inputs. As inputs are signal-based, computed can be used to derive new values, or effect to react side-effectfully.

but there is a limitation of signals compared to the ngOnChanges
1. you can't know if it's the first change or not like how it works now with the `ngOnChanges`
2. you can't get the old values of the input

### Proposed solution

to retain `ngOnChanges` life alongside `ngOnInit` and `ngOnDestroy`

### Alternatives considered

to provide a function that takes signal input and return observable with object from [SimpleChange](https://angular.io/api/core/SimpleChange) class

I know that pairwise will return the old values, but it won't emit the first value ever, so it's not that easy but I think it's possible

**Comment by spock123** [comment]
Could you not handle "first change" by having a local signal tracking this? 
```

myInput = input();
myInputHistory = signal([]);
effect(  () => {
   
   // Track all previous input values - not sure why but you could
    this.myInputHistory.update ( prev => [ ...prev, this.myInput() ] );
   
  // Also check if it's the first value
   if (this.myInputHistory().length === 1) {
      console.log('First value received', this.myInput() );
  }

}
```

**Comment by robertIsaac** [comment]
@spock123 
this I think will work, but when you have multiple inputs can get complicated very easily
and I believe this isn't DX friendly, it's literally much better DX the current ngOnChanges hook, for me I think it's more important than keeping `ngOnInit`
I'm trying to switch on one personal project and I could literally remove all of the `ngOnInit` (not much around 10) in the project in less time one `ngOnChanges`

**Comment by pkozlowski-opensource** [comment]
> you can't know if it's the first change or not like how it works now with the ngOnChanges

Would _love_ to hear more about the use-case. 

> you can't get the old values of the input

Similarly, would love to learn more about the real-life use-cases. 

Sharing use-cases is important as the listed limitations apply to any signal - not only inputs. So if we miss an important mechanism, it would have to be added to signals, most likely, instead of retaining `ngOnChanges` on signal components.

**Comment by spock123** [comment]
@robertIsaac  I think it maybe would be even simpler if we use `computed` instead, like this: 

```
myInput = input();
myInputHistory = computed( () => [ ...untracked(this.myInputHistory(), myInput() ]);

constructor() { 

    effect(  () => {
     if (this.myInputHistory().length === 1) {
        console.log('First value received', this.myInput() );
      }
   })

}



```

**Comment by robertIsaac** [comment]
@pkozlowski-opensource 
**the cases about old values**
now it's not possible inside effect to know which signal has changed
we need that inside some of the components to determine if we should re render manually our chart or not
for our table to determine if we should call the API or not, for example if the user wants to see the id or the name in the table header we don't need to, but if he changed the date then we need to call the API to get the new data

**the cases about the first change**
it happens when the old value is undefined, we need to know if it's because the component has just been rendered or because has unset it before and now he set it again

if you need more details I can search our code base for `SimpleChange` and give you all the cases

**Comment by robertIsaac** [comment]
here is simplified code for pagination
```
  ngOnChanges(changes: Record<string, SimpleChange | undefined>): void {
    if (changes['filter'] && !changes['filter'].firstChange) {
      this.page = 0;
      this.load(this.filter, this.page);
      return;
    }

    this.load(this.filter, this.page);
  }
```

**Comment by alxhub** [comment]
> now it's not possible inside effect to know which signal has changed

Effects can absolutely hang on to previous values of things, and check if they're different. It's probably possible to rebuild `ngOnChanges` in its entirety as an effect using this technique.

**Comment by robertIsaac** [comment]
> > now it's not possible inside effect to know which signal has changed
> 
> Effects can absolutely hang on to previous values of things, and check if they're different. It's probably possible to rebuild `ngOnChanges` in its entirety as an effect using this technique.

Are you saying it's a feature will be added?
Or it's something that currently exist?

**Comment by tomastrajan** [comment]
Example of a use case I encountered today, where something like `effect((isFirstRun) => {})` would be very useful...

1️⃣ effect always runs initially (to build dep graph)
2️⃣ effect run injection ctx / at constructor time (by default)
3️⃣ inputs are set at ngOnChanges (or whatever it will be with signals: true) (after constructor)
4️⃣ effect + output overwrite data in parent before it was consumed by input

Wouldn't it be great to get something like isFirstRun (similar to ngOnChanges, isFirstChange?) to solve it ?

Other ways to solve it, run in ngOnInit (and add injection ctx) or use explicit flag....

![image](https://github.com/angular/angular/assets/3764868/2be8950d-1b5e-4c12-a027-6db1b1dc2421)

**Comment by alxhub** [comment]
> > > now it's not possible inside effect to know which signal has changed
> > 
> > 
> > Effects can absolutely hang on to previous values of things, and check if they're different. It's probably possible to rebuild `ngOnChanges` in its entirety as an effect using this technique.
> 
> Are you saying it's a feature will be added? Or it's something that currently exist?

Effects can close over whatever state object(s) are needed:

```typescript
prevA = null;
prevB = null;

pseudoOnChanges = effect(() => {
  const a = this.a();
  const b = this.b();
  if (a !== this.prevA) { ... }
  if (b !== this.prevB) { ... }
  
  this.prevA = a;
  this.prevB = b;
});
```

**Comment by e-oz** [comment]
@robertIsaac try to do it in a declarative way and you will not need `effect()` at all 😎
In this example, I use imperative code only in side effects:

```ts
export class ExampleComponent {
  private readonly api = inject(Api);

  protected readonly $page = signal(0);
  // from route
  private readonly $initialFilter = input('name', { alias: 'filter' });
  private readonly $mutableFilter = signal<string | undefined>(undefined);
  protected readonly $filter = computed(() =>
    this.$mutableFilter() ?? this.$initialFilter()
  );

  protected readonly $posts = toSignal(combineLatest([
    toObservable(this.$filter),
    toObservable(this.$page),
  ]).pipe(
    switchMap(([filter, page]) => this.api.getPosts(filter, page))
  ), { initialValue: [], rejectErrors: true });

  // side effect
  protected setPage(page: number) {
    this.$page.set(page);
  }

  // side effect
  protected setFilter(filter: string) {
    this.$mutableFilter.set(filter);
    this.$page.set(0);
  }
}
```

**Comment by e-oz** [comment]
[do not use](https://stackblitz.com/edit/stackblitz-starters-8xzgwj?file=src%2Fmain.ts)

**Comment by pkozlowski-opensource** [comment]
@robertIsaac it is still not clear to me what is the exact scenario - having a stackblitz with code corresponding to your use-case would be very helpful.

> the cases about old values
now it's not possible inside effect to know which signal has changed
we need that inside some of the components to determine if we should re render manually our chart or not
for our table to determine if we should call the API or not, for example if the user wants to see the id or the name in the table header we don't need to, but if he changed the date then we need to call the API to get the new data

While it is true that we don't know in the effect which exact signal changed, I think that your use-case can by covered by two separate effects. That is, instead of: 
```typescript
effect(() => {
   doSomethingToTheHeader(id(), name());
   callApi(data());
});
```
try:

```typescript
const data = newSignal([]);
// effect that takes care of data
effect(() => {
   callApi(date()).then(data => data.set(data));
});

// effect that takes care of header rendering
effect(() => {
   doSomethingToTheHeader(id(), name(), data());
});
```

**Comment by pkozlowski-opensource** [comment]
Again, hard to speculate without exact code - happy to iterate more when you've got a stackblitz with code similar to your actual use-case.

**Comment by pkozlowski-opensource** [comment]
Linkinking #54339 which is about previous value (in computed, but the same reasoning applies to effects)

**Comment by robertIsaac** [comment]
hi @pkozlowski-opensource I will provide a full reproduction, but since it needs some effort probably it won't happen soon, probably after 2-3 weeks

**Comment by robertIsaac** [comment]
While trying to create the reproduction
I found a solution for the pagination problem 
I'm still not sure about the other cases, but I don't have a reproduction for now

**Comment by alxhub** [comment]
Closing as the original use case for still needing `ngOnChanges` doesn't seem to be valid. If anyone does have a use case where they can't solve their problem without `ngOnChanges`, feel free to open a new issue with a description of the problem :)
