### ISSUE TITLE
Getting started with Angular - in this page command to generate component may need to chanegd

### ISSUE THREAD

**Issue by SaravanakumaarR** [angular/angular#54405]
### Describe the problem that you experienced

Getting started with Angular - (https://angular.io/start#getting-started-with-angular)
in this page 

Below piece of information may needs to be changed.

" In the new terminal, generate a new component named product-alerts by running the following command:

ng generate component product-alerts "

This command creates the standalone component in the stackblitz project.
which causes the app to fail .

### Enter the URL of the topic with the problem

https://angular.io/start#pass-data-to-a-child-component

### Describe what you were looking for in the documentation

Update the command to generate non standalone component or whichever you feel right for beginners

**Comment by KhizerRehan** [comment]
This command should generate normal component which is not standalone

ng generate component <Component_Name> --standalone false --module <Module_Name>

**Comment by SaravanakumaarR** [comment]
If we update that in docs that will use full for beginners .
if  team decides to update the command there are few other place as well under try out section , there as well similar changes needs to be done.

**Comment by JeanMeche** [comment]
We're looking to deprecate angular.io in favor of the new https://angular.dev. 
For the new tutorials please have a look at https://angular.dev/tutorials which are fully standalone, thank you.
