### ISSUE TITLE
Conditional Rendering should Easy !

### ISSUE THREAD

**Issue by thanhtutzaw** [angular/angular#54404]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

If we want conditional rendering , we have to import ngIf in component . Then use it in template . If there a other solution or ....

### Proposed solution

`{ conditional && <ShowButton /> }`

**Comment by JeanMeche** [comment]
Angular v17 introduced the new [control flow syntax](https://angular.dev/guide/templates/control-flow). 
The `@if()` block doesn't require to import any directive.

**Comment by mlc-mlapis** [comment]
@JeanMeche Since I wasn't sure, I tried to find some mentions in the documentation about how the new Control Flow elements are handled from the point of view of their implicit/explicit availability and possible differences in this direction with the existing directives NgIf, NgFor, ... in fact. 😄

**Comment by JeanMeche** [comment]
They are a compiler feature, this is why they don't require any import. 

They also generic slightly different template instructions. You read about it [here](https://angularindepth.com/posts/1525/diving-into-the-new-angular-control-flow-internals).

**Comment by mlc-mlapis** [comment]
It is OK to understand how they work or what they are; I only mentioned that there is no formal recapitulation in the official docs.
