### ISSUE TITLE
Signal Queries: contentChild/contentChildren throws error if it doesn't match any selector

### ISSUE THREAD

**Issue by chintankavathia** [angular/angular#54410]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

using contentChild/contentChildren will throw console error if there is no match for given selector/provideToken.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-urfw9d?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=another.component.ts,src%2Fmain.ts,two.component.ts,src%2Findex.html,node_modules%2F%40angular%2Fcore%2Findex.d.ts&title=Angular%20Starter

### Please provide the exception or error you saw

```true
TypeError: Cannot read properties of null (reading 'length')
    at materializeViewResults
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular/animations 17.2.0-rc.1
@angular/common 17.2.0-rc.1
@angular/compiler 17.2.0-rc.1
@angular/core 17.2.0-rc.1
@angular/elements 17.2.0-rc.1
@angular/forms 17.2.0-rc.1
@angular/platform-browser 17.2.0-rc.1
@angular/router 17.2.0-rc.1
rxjs 7.8.1
tslib 2.6.2
zone.js 0.14.3
```

**Comment by JoostK** [comment]
Thanks for the report, this has already been fixed and will be in the next release
