### ISSUE TITLE
Typo in link on page "https://angular.dev/guide/http"

### ISSUE THREAD

**Issue by rolanddeboer** [angular/angular#54416]
### Describe the problem that you experienced

Under the section "What's next" on `https://angular.dev/guide/http` there is a link called "Making HTTP Requests" to `https://angular.dev/guide/http/making-requets`
That is a typo: should be `.../making-requests`. That link actually exists.

### Enter the URL of the topic with the problem

https://angular.dev/guide/http

### Describe what you were looking for in the documentation

A working link

### Describe the actions that led you to experience the problem

Clicking on the link and getting a 404

### Describe what you want to experience that would fix the problem

Not having the typo in the link

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by #52541 and is pending deployement on our side !
