### ISSUE TITLE
Being able to set http status of responses from Angular 17

### ISSUE THREAD

**Issue by Gold3nFox** [angular/angular#54415]
### Description

In older angular version if you wanted your not found page to return with 404 status code on SSR you could use the following code:
<img width="1003" alt="Screenshot 2024-02-13 at 4 17 57 PM" src="https://github.com/angular/angular/assets/25108979/fb33488b-c6ba-4415-9003-06938f5527bd">
Or you could handle some redirects on Angular app like this:
<img width="799" alt="Screenshot 2024-02-13 at 4 18 40 PM" src="https://github.com/angular/angular/assets/25108979/f1dbd1d0-3d27-4130-b863-27b7029eb05b">
If you are wondering why these are important for me and I can't handle them on backend, the first answer is that I don't want the load of thousands redirects to be on our backend and this way I could know if I need to redirect the page on SSR on certain pages. the second answer is that I'm using angular to create a website builder and I'm creating routes of my project like test.com/hire/:id with this builder. So when an page url is sent to Angular which is test.com/hire/angular I need to check with backend through an API to see if a page with name angular is created and when It's not created I need to be able to send 404 status code.

### Proposed solution

Being able to use RESPONSE and REQUEST like we could use in Angular Universal `import { REQUEST } from '@nguniversal/express-engine/tokens';`

### Alternatives considered

Being able to set status code for returned pages in server.ts

**Comment by JeanMeche** [comment]
Hi, this issue is being tracked on the CLI repo. Please have a loot at angular/angular-cli#26323 thank you.
