### ISSUE TITLE
NgSelectOption writes a object.toString() as value instead of object

### ISSUE THREAD

**Issue by otoense** [angular/angular#5441]
I tried to use NgSelectOption as described in the angular2 doc:
https://angular.io/docs/ts/latest/api/core/NgSelectOption-directive.html

Unfortunately "value" is not filled with a City object as expected but with city.toString() (as I guess, since the result is a string '[object] object')

To reproduce and isolate I created a plunker for this:
http://plnkr.co/edit/8RvhSnvA3IuVN6fiCJ7V

**Comment by lexon0011** [comment]
I have the same issue. Is there already a solution for this problem? Thanks!

**Comment by zoechi** [comment]
Dup of #4843 ?

**Comment by kara** [comment]
Yeah, closing as a duplicate of #4843. Thanks for reporting, though!  Follow the issue on the other thread.
