### ISSUE TITLE
Problemas con angular y iphone o safari

### ISSUE THREAD

**Issue by pabloarleguialvarado** [angular/angular#54424]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Hola como estan?? Tengo un sitio de cotizaciones donde a través de php y angular genera un pdf que se descarga automáticamente, en la web de escritorio funciona bien, pero al abrir el link en el iPhone no descarga el archivo. Saben que puede ser?? Dejo el link donde deberia descargar ese mismo sitio pero en pdf.

https://www.meatlovers.cl/jarvis/cot/nor/index.html?&id=11721

Muchas gracias

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
