### ISSUE TITLE
Why remove this if statement?  if (supportsState()) Without it, it is causing issues with office.js and Angular

### ISSUE THREAD

**Issue by jimbarrett33** [angular/angular#54420]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

**code BEFORE:**
[https://github.com/angular/angular/blob/15.0.x/packages/common/src/location/platform_location.ts#L180C3-L186C4](https://github.com/angular/angular/blob/15.0.x/packages/common/src/location/platform_location.ts#L180C3-L186C4)

`
override replaceState(state: any, title: string, url: string): void {
    if (supportsState()) {
      this._history.replaceState(state, title, url);
    } else {
      this.location.hash = url;
    }
  }
`

**code NOW:**
[https://github.com/angular/angular/blob/16.0.x/packages/common/src/location/platform_location.ts#L165](https://github.com/angular/angular/blob/16.0.x/packages/common/src/location/platform_location.ts#L165)
  `override replaceState(state: any, title: string, url: string): void {
    this._history.replaceState(state, title, url);
  }`

What harm was the `supportsState()` method causing? It's seems like nice defensive programming. Instead, now it is breaking office.js add-ins that use Angular without some awful workarounds.

Please put it back unless there is some harm that I am missing other than saving a few bytes in the package.

### Please provide a link to a minimal reproduction of the bug

not possible it's inside office add-in

### Please provide the exception or error you saw

```true
Uncaught TypeError: this._history.replaceState is not a function
    at BrowserPlatformLocation.replaceState (common.mjs:132:23)
    at HashLocationStrategy.replaceState (common.mjs:423:32)
    at Location.replaceState (common.mjs:588:32)
    at HistoryStateManager.setBrowserUrl (router.mjs:4997:27)
    at HistoryStateManager.handleRouterEvent (router.mjs:4971:26)
    at SafeSubscriber._next (router.mjs:5233:39)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183:16)
    at SafeSubscriber.next (Subscriber.js:122:22)
    at Subscriber._next (Subscriber.js:72:26)
    at Subscriber.next (Subscriber.js:49:18)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/common": "17.1.3",
    "@angular/compiler": "17.1.3",
    "@angular/core": "17.1.3",

 "@angular/cli": "~17.1.0",

  "typescript": "5.3.3",
```

**Comment by jnizet** [comment]
The commit message says:

> Drop `supportsState` as its supported by evergreen browsers.

You're apparently using a non-supported browser. You could upgrade your browser, or stick to an Angular version that supported the browser you're using.

**Comment by json-derulo** [comment]
`window.history.replaceState()` is [widely supported by the browsers](https://caniuse.com/mdn-api_history_replacestate). The problem seems to be that office.js overrides the `window.history` API, see https://github.com/OfficeDev/office-js/issues/429. Angular is not the issue here.

**Comment by jimbarrett33** [comment]
@jnizet @json-derulo I understand all your points but it IS causing some issues for production code bases using the latest version of Angular. My point was that it wasn't harming anything and now it is.

Just FYI, I'm trying keep Angular and other code updated to latest version of things to fix/prevent npm audit issues. Keeping older code can causes security issues. I have no control over office-js or the internals of Outlook add-ins runtime.

All of the above said, thanks for responding. You can close the issue as I'm not expecting any action to be taken now.

**Comment by alxhub** [comment]
I don't know anything about `office.js` or what JavaScript environment it offers, but Angular's [browser support](https://angular.dev/reference/versions#browser-support) is pretty simple: we support the last 2 versions of evergreen browsers.

Often parts of the framework will function in other environments, and we try not to break that support without a good reason. However, we have to balance those efforts with accumulation of checks like `supportsState`. These checks create overhead, both in terms of bytes in the bundle and for our ability to maintain and evolve the framework.

In this particular case, you could use DI to provide an implementation of `PlatformLocation` that's better suited to the environment in which you're trying to run.

**Comment by kbrilla** [comment]
```typescript
  //before bootstrapApplication

  // in office add-ins those are replaced with null and cause router to crash, so we set them to empty functions
  window.history.replaceState = window.history.replaceState ?? (() => {});
  window.history.pushState = window.history.pushState ?? (() => {});
```
I found this solution in office.js support page and it does ok. 

I also recomend adding  this in browserlistrc, as in Office for Mac there is some hard to debug error otherwise. 
```browserlistrc
last 4 Chrome version
last 4 Firefox version
last 4 Edge versions
last 2 Safari major versions
last 2 iOS major versions
```
or set min versions even lower depending on what your app supports.

**Comment by alxhub** [comment]
(closing as we don't support office.js development directly, and there are several suggested workarounds)
