### ISSUE TITLE
Provide a way of registering to `ModelSignal` changes programmatically

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular#54426]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

There is no explicit programmatic/imperative way of registering to `ModelSignal` changes from the parent except using an `effect`. Use case examples: dynamically created components and testing.

This also means that replacing two-way binding (an input + output with `Change` suffix) with `ModelSignal` will cause a breaking change to anything that programmaticaly/imperatively subscribes to the old output. 

### Proposed solution

- warn users in documentation that replacing input + output combination with `ModelSignal` should be considered a breaking change
- add a method to `ComponentRef` (e.g. `registerListener`)

### Alternatives considered

Using an `effect` or an util like `toObservable`:

```ts
class ChildCmp {
  name = model('');
}

// parent

const child = viewChild(ChildCmp)

effect(() => {
  console.log(child().name())
});

// or
toObservable(child().name).subscribe(...);
```

The other way would be using `.subscribe()` method but it is deprecated.

**Comment by yjaaidi** [comment]
Cool! Thanks Paul!
By the way, shouldn't we avoid `subscribe` as a keyword to avoid the wrong assumption that it only works with observables?

**Comment by alxhub** [comment]
Since `model()` is conceptually declaring an `output()` it should provide the same API as `output()` for manual "subscription". That's currently in design :)

**Comment by yjaaidi** [comment]
Perfect!
We'll have to highlight the "Change" suffix in the docs or ideally make the output name type safe everywhere. 
I'm pretty sure you have this planned but just in case it wasn't written anywhere, here it is 😊

It's also a hint for 3rd party testing tools.

**Comment by alxhub** [comment]
Closing as resolved - `ModelSignal` extends `OutputRef` which offers a non-deprecated `.subscribe()`.
