### ISSUE TITLE
Misspelling in example code - Setting up HttpClient

### ISSUE THREAD

**Issue by jessicafrenkel** [angular/angular#54433]
### Describe the problem that you experienced

The sample code misspelled bootstrapApplication under 'Providing HttpClient through dependency injection'

### Enter the URL of the topic with the problem

https://angular.dev/guide/http/setup

### Describe what you were looking for in the documentation

Reading the docs on Setting up HttpClient.

### Describe the actions that led you to experience the problem

Copying and pasting the sample code in my sample project.

### Describe what you want to experience that would fix the problem

Correct the spelling in the sample code.

### Add a screenshot if that helps illustrate the problem

![bootstrap-misspelling](https://github.com/angular/angular/assets/67281977/7e325dfe-17c6-46a7-bb1a-00507453ac7b)

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by  #52806 and is pending deployement on our side !
