### ISSUE TITLE
docs: angular dev tutorial description change

### ISSUE THREAD

**Issue by sathish-thangavel** [angular/angular#54431]
### Describe the problem that you experienced

Noticed a description error in the angular dev website. Instead of `UserComponent` in the description, it's typed as `AppComponent`

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/composing-components#add-a-reference-to-usercomponent

### Describe what you were looking for in the documentation

The following changes need to be made to documentation 

Be sure to add `UserComponent` to the imports array of `AppComponent`, this makes it available for use in the AppComponent template.

### Describe the actions that led you to experience the problem

NA

### Describe what you want to experience that would fix the problem

Please change to the correct description.

### Add a screenshot if that helps illustrate the problem

![docs-error](https://github.com/angular/angular/assets/152856660/b5fd40cf-c06b-4879-bdaf-7b2ae44fc829)

### If this problem caused an exception or error, please paste it here

```true
NA
```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
NA
```

### Provide any additional information here in as much as detail as you can

```true
NA
```

**Comment by ilirbeqirii** [comment]
This issue seems fixed in the code but has not been deployed yet.

**Comment by JeanMeche** [comment]
Hi, thanks for reporting this issue !
It has been fixed by  #52677and is pending deployement on our side !
