### ISSUE TITLE
We Need angular 17 cli command  Document

### ISSUE THREAD

**Issue by Sabareesh98421** [angular/angular#54454]
### Describe the problem that you experienced

after install the ng17 I can't use the normal ng command because it generate the standalone components,
so I tried the `ng new projectName --standalone false` it works fine but tailwind and some other libraries doesn't support. so, I delete the project and try in common way to create that project. I fell that I forced use the stand alone.
As a beginner in angular I need those the cli commands, I tried surfing in internet but not satisfied.
I accept that I don't know how to play with standalone, but non-standalone feature is easier to learn angular.   
 because ng17's default support is standalone component, but I don't need that for most projects kindly provide the detailed documents for the cli command in both angular.io and angular.dev thanks in advance. 
I apologies if spoke anything wrong.

### Describe what you were looking for in the documentation

Detailed Documentation of Angular CLI command line like ng s or ng serve , ng new projectName --standalone false 
like this. Kindly consider this ticket as valuable. 

### Describe the actions that led you to experience the problem
Default standalone components

### Describe what you want to experience that would fix the problem
Provide the detailed angular 17's cli command line list or make the standalone is not default

**Comment by anisabboud** [comment]
Angular CLI documentation: 
https://angular.dev/cli
https://angular.dev/cli/new
https://angular.dev/tools/cli

**Comment by alan-agius4** [comment]
Plentiful documentation exists for using Angular, whether you opt for the standalone or the ngModule APIs. Tailwind CSS is applied in a standalone application or ngmodule remains unchanged as Tailwind functions solely as a CSS processing library.
Furthermore, NgModule-based libraries can seamlessly integrate with standalone applications, thus compatibility concerns should not arise in this scenario.

**Comment by Sabareesh98421** [comment]
> Plentiful documentation exists for using Angular, whether you opt for the standalone or the ngModule APIs. Tailwind CSS is applied in a standalone application or ngmodule remains unchanged as Tailwind functions solely as a CSS processing library.
> Furthermore, NgModule-based libraries can seamlessly integrate with standalone applications, thus compatibility concerns should not arise in this scenario.
> 
> 
> 
> 
> 

Thanks mam but I tried this morning but it didn't work that was why I raised a ticket. Any ways thanks man 😁
