### ISSUE TITLE
Reference link url is empty

### ISSUE THREAD

**Issue by rpalival** [angular/angular#54451]
### Describe the problem that you experienced

In learn angular documentation under updating the component lesson,
step 1: Add a property called class , there is a mention of "The city property is of type string but you can omit the type because of [type inference in TypeScript](https://angular.dev/typescript.org/type-inference)."
This particular reference link when clicked, leads to "Error 404: Page not found"

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/updating-the-component-class

### Describe what you were looking for in the documentation

[type inference in TypeScript](https://angular.dev/typescript.org/type-inference), this is the reference link I was looking for.

### Describe the actions that led you to experience the problem

1. Adding a property called city to the App component
2. This property is string data type
3. there was a mention of how typescript works here as there is no need to mention the string data type
`export class AppComponent {
  city = 'San Francisco';
}`

### Describe what you want to experience that would fix the problem

https://angular.dev/typescript.org/type-inference this particular link should lead me to the right resource and not empty page.

### If this problem caused an exception or error, please paste it here

```true
`Page Not Found`
```

**Comment by JeanMeche** [comment]
Hi, thank you for reporting this issue !
It has been fixed by #52714 and is pending deployment on our side !
