### ISSUE TITLE
Showing deprecated dependency

### ISSUE THREAD

**Issue by the-dev-adonis** [angular/angular#54458]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

No

### Description

npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.0
Node: v18.16.1
Package Manager: NPM 9.5.1
```

**Comment by JoostK** [comment]
Angular 15 is LTS and only receives security updates; this dependency has since been updated in newer versions of Angular.
