### ISSUE TITLE
Adding a Option: @insert()

### ISSUE THREAD

**Issue by TheRealIndianBoi** [angular/angular#54453]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

With the new In-Built Control flow, this 'problem' occurs:
<div *ngif ="something" else maker>{...}</div>
<ng-template #maker>{...}</ng-template>

Changing it to:
@if (something) {<div>{...}</div>}
@else { @insert(maker) }

In this case @insert is not necessary because maker is only called ones, but if there are multiple divs who call maker if there value is set false, then it should be possible to call maker to be inserted in @else.

### Proposed solution

See above

### Alternatives considered

We could use *ngif, but in-built control flow is faster.

**Comment by JeanMeche** [comment]
What limitations do you encounter if you use a [template outlet](https://angular.io/api/common/NgTemplateOutlet) for your use case ?

**Comment by TheRealIndianBoi** [comment]
You are right. My bad.
