### ISSUE TITLE
High Priority! Outage ! Issue running with Ubuntu 20/22

### ISSUE THREAD

**Issue by cyberiumchain** [angular/angular#54467]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Today(Feb/15/2024) the angular is not running fine in Ubuntu 20 & 22.
The 3 packages of @angular-devkit/build-angular, @angular/compiler-cli & typescript  are not uninstalling at all.

### Please provide a link to a minimal reproduction of the bug

>ng new

### Please provide the exception or error you saw
Create a new app: ng new

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.2.0
Node: 20.11.1
Package Manager: npm 10.2.4
OS: linux x64

Angular: 17.2.1
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.0 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            17.2.0 (cli-only)
@angular-devkit/schematics      17.2.0 (cli-only)
@angular/cli                    17.2.0 (cli-only)
@angular/compiler-cli           <error>
@angular/ssr                    17.2.0
@schematics/angular             17.2.0 (cli-only)
rxjs                            7.8.1
typescript                      <error>
zone.js                         0.14.4
```

### Anything else?

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

**Comment by JoostK** [comment]
It's entirely unclear what doesn't work. Without more information, we'd be unable to provide any actionable suggestions. That said, installation problems are typically due to environmental problems or possibly NPM or NPM registry issues, unrelated to Angular.

**Comment by cyberiumchain** [comment]
The three libraries are not working in Ubuntu.
@angular-devkit/build-angular   <error>
@angular/compiler-cli           <error>
typescript                      <error>

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by cyberiumchain** [comment]
I have already mentioned the ways to reproduce.
Just generate a new app,'ng new' and see for yourself. Use the OS of Ubuntu 20 or 22. What is not clear?

**Comment by dgp1130** [comment]
I just tested out `ng new` on Ubuntu 22.04 and a Debian machine, both worked fine as expected.

Without any more details about the error or anyone else to confirm that this is a widespread issue, I think it is likely something wrong with your setup or maybe some corruption which occurred during `npm install`.

**Comment by cyberiumchain** [comment]
I understand. It is happening in Azure cloud. It may not be widespread issue.
