### ISSUE TITLE
bindToComponentInputs does not work when using RouterTestingModule

### ISSUE THREAD

**Issue by wawyed** [angular/angular#54461]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

it looks like the code in RouterTestingModule does not take into account bindToComponentInputs  so having Input for resolvables results in failing unit tests even if you define the correct resolves in the route definition.

I'd expect something similar to RouterModule:

```config?.bindToComponentInputs ? withComponentInputBinding().ɵproviders : [],```

in https://github.com/angular/angular/blob/main/packages/router/testing/src/router_testing_module.ts#L88

```
export class RouterTestingModule {
  static withRoutes(
    routes: Routes,
    config?: ExtraOptions,
  ): ModuleWithProviders<RouterTestingModule> {
    return {
      ngModule: RouterTestingModule,
      providers: [
        {provide: ROUTES, multi: true, useValue: routes},
        {provide: ROUTER_CONFIGURATION, useValue: config ? config : {}},
        ...config?.bindToComponentInputs ? withComponentInputBinding().ɵproviders : [], <--- this is missing
      ],
    };
  }
}
```

**Comment by alxhub** [comment]
`RouterTestingModule` does set up a specific configuration of the router. It's not strictly necessary - you can also use `provideRouter()` directly in your tests with whatever configuration you'd like.

**Comment by wawyed** [comment]
But the fact still remains that RouterTestingModule has a second argument with router config which does include bindToComponentInputs, so I'd thought it should support such behaviour

**Comment by atscott** [comment]
As @alxhub mentioned, you can and should be using `RouterModule` or `provideRouter` directly in tests. `RouterTestingModule` is no longer needed or maintained so I've created a PR to officially deprecate it.
