### ISSUE TITLE
Standalone Component Schemas Not An Array

### ISSUE THREAD

**Issue by dpwzone** [angular/angular#54468]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Trying to create a standalone component, but getting an error stating an array of schemas in not an array of schemas.  

Code:
-----------------------------------------------------------------------------------------------------------------
import { NO_ERRORS_SCHEMA } from '@angular/compiler';
import { Component } from '@angular/core';

@Component({
  standalone: true,
  selector: 'app-test',
  templateUrl: './test.component.html',
  styleUrl: './test.component.css',
  schemas: [ NO_ERRORS_SCHEMA ]
})
export class TestComponent {
...
}
-----------------------------------------------------------------------------------------------------------------

### Please provide a link to a minimal reproduction of the bug

Above in the description

### Please provide the exception or error you saw

```true
error NG1010: Component.schemas must be an array of schemas
  Value is of type '[NO_ERRORS_SCHEMA]'.
   schemas: [ NO_ERRORS_SCHEMA ]
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.2
Node: 18.16.0
Package Manager: npm 9.5.1
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1701.2 (cli-only)
@angular-devkit/core         17.1.2 (cli-only)
@angular-devkit/schematics   17.1.2 (cli-only)
@schematics/angular          17.1.2 (cli-only)
```

**Comment by JoostK** [comment]
You're importing `NO_ERRORS_SCHEMA` from `@angular/compiler`, but it must be imported from `@angular/core`.

**Comment by dpwzone** [comment]
The error presented was misleading then, as the array did contain schemas, just not the type angular was looking for.

Perhaps having better error messaging would help devs not waste time running down false messages.
