### ISSUE TITLE
Docs: all content images are not displayed in adev

### ISSUE THREAD

**Issue by 9kubczas4** [angular/angular#54472]
### Describe the problem that you experienced

There is missing image below this section: https://angular.dev/best-practices/slow-computations.

It exists in angular.io: https://angular.io/guide/change-detection-slow-computations#identifying-slow-computations

I discovered that **all** images in adev are not displayed. For example: https://angular.dev/best-practices/slow-computations.

### Enter the URL of the topic with the problem

https://angular.dev/best-practices/slow-computations

**Comment by 9kubczas4** [comment]
Fixed in this code change: https://github.com/angular/angular/pull/54474.

**Comment by AndrewKushnir** [comment]
// cc @josephperrott as it might be related to ADEV deployment.

**Comment by murali-krishna-sv** [comment]
I noticed adev-root loaded is twice when I oped in the image in new tab. Try this link - https://angular.dev/assets/content/images/best-practices/runtime-performance/slow-computations.png

**Comment by sonukapoor** [comment]
> I noticed adev-root is loaded twice when I oped in the image in new tab. Try this link - https://angular.dev/assets/content/images/best-practices/runtime-performance/slow-computations.png

This has been reported here: https://github.com/angular/angular/issues/54506
