### ISSUE TITLE
Click on heading in the docs does not trigger scroll

### ISSUE THREAD

**Issue by 9kubczas4** [angular/angular#54473]
### Describe the problem that you experienced

Click on heading in the docs does not trigger scroll. For example:
1. Open https://angular.dev/overview
2. Click on `Features that power your development` heading.

Expected behavior:
Scroll into the section of clicked heading should happen.

### Enter the URL of the topic with the problem

https://angular.dev/overview

### If this problem caused an exception or error, please paste it here

```true
No console errors.
```

**Comment by sonukapoor** [comment]
@9kubczas4 I clicked in the right sidebar and the page scrolled to the section. I am using Chrome Version 121.0.6167.184.
What browser are you using?

**Comment by 9kubczas4** [comment]
Hi @sonukapoor,

Table of contents works fine, however click on headings in the contents should trigger the scroll as well.
I'm talking about this headings:
<img width="819" alt="image" src="https://github.com/angular/angular/assets/43759569/42e91a4b-cfa3-4f21-b7e4-9c3584432dc7">

It was working in adev previously.

**Comment by 9kubczas4** [comment]
I think it's standard behaviour for most of the docs.

For example:

https://github.com/angular/angular/assets/43759569/38bd4535-4f43-4fb2-af43-effbcaaf8647

https://github.com/angular/angular/assets/43759569/c47a7861-0325-401c-933e-c9e39487b634

It's useful once the heading is on the bottom of the page.

**Comment by sonukapoor** [comment]
That makes sense @9kubczas4

**Comment by 9kubczas4** [comment]
@sonukapoor I can take a look at it, and try to resolve this issue.

**Comment by sonukapoor** [comment]
@9kubczas4 go for it 👍

**Comment by hansireit** [comment]
@sonukapoor I found the issue in `angular/dev-infra`, is there a documentation on how to build/link the code from `dev-infra` and use it in the `angular` repository?

Basically, the heading from [heading.ts](https://github.com/hansireit/dev-infra/blob/edcf0a3ad1c242f1ba1eabcda95afcffe7d9965c/docs/markdown/guides/tranformations/heading.ts#L35) should wrap the anchor as well. Like here:

```ts
<h${level} id="${link}">${label}
  <a href="#${link}" class="docs-anchor" tabindex="-1" aria-label="Link to ${label}"></a>
</h${level}>
```

Also the [hover selector](https://github.com/hansireit/dev-infra/blob/38044ff3de472a5f67cc2e11c9c847528d711e5a/docs/components/viewers/docs-viewer/docs-viewer.component.scss#L55) for the `.docs-anchor` should be directly contained and not inside the `::after`.

I will create a PR for this.

**Comment by sonukapoor** [comment]
@hansireit I am not sure if there is any official guide for that.

**Comment by vladboisa** [comment]
> I think it's standard behaviour for most of the docs.
> 
> For example:
> 
>  Screen.Recording.2024-02-20.at.14.11.02.mov 
>  Screen.Recording.2024-02-20.at.14.11.15.mov 
> It's useful once the heading is on the bottom of the page.

@sonukapoor , @9kubczas4 
For me anchor's work's fine, like on example below:

https://github.com/angular/angular/assets/60569670/0eb5e410-58ef-416c-b391-ab78192daaf2

**Comment by sonukapoor** [comment]
@vladboisa I see it working as well.

**Comment by 9kubczas4** [comment]
@vladboisa @sonukapoor I can confirm that it works now.

**Comment by sonukapoor** [comment]
@9kubczas4 feel free to close the issue then.

**Comment by 9kubczas4** [comment]
Issue was resolved by other code changes.
