### ISSUE TITLE
Attaching directive to an image prevents it to be loaded by interpolation

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular#5448]
*Sorry for the long title*

I have this code currently

```
<img src="path/to/my/{{image}}.jpg" />
```

This works correctly, but when I add a Directive to grab the image element the interpolation doesn't work anymore and the image isn't loaded.

```
@Directive({selector : 'img', exportAs : 'ea' }) {}
<img #ea="ea" src="path/to/my/{{image}}.jpg" /> 
```
*This doesn't work anymore*.

If I remove the interpolation and I write the image name directly it works, so I'm guessing it must be something with the interpolation being interpreted later in time and the directive hijacking the element behavior, or something like that.

Here's a [plnkr](http://plnkr.co/edit/0Idh3NyIRkRhBlfnhj8k), to reproduce

- Load it and will show no image, but the image path will be correctly printed in the console.

Is this the expected behavior?  Am I doing right? I asked in gitter but the timezone makes everything more difficult.

**Comment by ericmartinezr** [comment]
Ok, this has nothing to do with interpolation, like I was told [here](https://gitter.im/angular/angular?at=5653aeb2ad9684883d78641d) the problem is another one, this was a tricky one. Closing. Still a little bit confused (if somebody can/wants to expand a little bit more on the subject I will appreciate it :D)

**Comment by Krustie101** [comment]
In the full code of @ericmartinezr, there is also an input with name `src` on the directive:
```
@Directive({
  selector: 'img',
})
class Image {
  @Input('src') src: string ;
}
```
Apparently, this hijacked the assignment of the interpolated `src` property to the native `img` because replacing `@Input('src')`by `@Input('my-src')` resulted in the image being visible again.

**Comment by pkozlowski-opensource** [comment]
This is by design, see https://github.com/angular/angular/pull/3419 for more details
