### ISSUE TITLE
support scroll position in Scroll Event for imperative navigation

### ISSUE THREAD

**Issue by codingnuclei** [angular/angular#54496]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

Currently when using the `withInMemoryScrolling` the provided `RouterScroller`  seems to purposely only add a scroll position in the scroll event if the last source was a `popstate`

https://github.com/angular/angular/blob/d9a1a7dd07497768b1c70fe698b1547bd1f8488e/packages/router/src/router_scroller.ts#L114-L120

As this seems explicit I was wanting to understand if anyone knows a reason?

I see value in adding the position for imperative navigations too.

### Proposed solution

Look at the impacted of removing this check.

### Alternatives considered

Define a user provided service, that subscribes to the router and manually track the scroll state and navigation i.e replicate the RouterScroller functionality

**Comment by atscott** [comment]
> As this seems explicit I was wanting to understand if anyone knows a reason?

the service is used for scroll restoration when returning to a previous page by traversing through browser history. This is completely separate from scrolling in another way when navigating to a new page.

**Comment by codingnuclei** [comment]
> There is nothing to restore when navigating imperatively to a new page.

I think my thoughts was more along the idea of ()imperative or declarative):

1. loading the browser at `/feed`
2. scroll down the feed
3. use `routerLink="./home"`
4. routerLink="./feed"
5. ideally would like have the scroll position from from step 2

Sorry should have put this in the original post.  

Makes sense the above does not work if this service is for browser history navigation.  I will look to router events as a solution  👍
