### ISSUE TITLE
Doc (.dev): Code snippets don't render

### ISSUE THREAD

**Issue by lnksz** [angular/angular#54497]
### Describe the problem that you experienced

On https://angular.dev/guide/testing/services the code snippets don't render, whereas on they do https://angular.io/guide/testing-services.

### Enter the URL of the topic with the problem

https://angular.dev/guide/testing/services

### Describe what you were looking for in the documentation

Code snippets

### Describe the actions that led you to experience the problem

Open the URL (tested with Firefox 122.0 and Google Chrome 121.0.6167.184 on Manjaro )

### Describe what you want to experience that would fix the problem

See the snippets similar to https://angular.io/guide/testing-services

### Add a screenshot if that helps illustrate the problem

On beta:
![image](https://github.com/angular/angular/assets/15908859/a8e8aa42-6c8d-44c7-a09d-ec05f22540a0)

![image](https://github.com/angular/angular/assets/15908859/3767f580-8770-49b8-8195-fbf5043f547c)

On .io:
![image](https://github.com/angular/angular/assets/15908859/feaab650-c323-4582-a1df-d81f03bb69fa)

**Comment by JeanMeche** [comment]
Hi, thank you for bring this issue up. We're aware there is global issue with code blocks. It was initially reported on #54471 so let's continu tracking the issue over there.
