### ISSUE TITLE
Angular Dev: UI duplicated on navigation

### ISSUE THREAD

**Issue by l1337xto** [angular/angular#54506]
### Describe the problem that you experienced

![image](https://github.com/angular/angular/assets/89231810/c79f9370-1c5a-4389-aa26-d45d632564d1)
![image](https://github.com/angular/angular/assets/89231810/b0c224ef-3c94-4113-92cd-f0cbc278a8bb)

Getting duplicated root of the app when navigating to the above URL

### Enter the URL of the topic with the problem

https://angular.dev/guides/providers

### Describe what you were looking for in the documentation

Trying to get some info in the providers implementation for standalone modules and on navigation it created a duplicate UI which closed on navigation

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Running on latest chrome
```

**Comment by JeanMeche** [comment]
Hi, how did you landed on that page ?

**Comment by sonukapoor** [comment]
@JeanMeche Just click the URL provided by @l1337xto

**Comment by JeanMeche** [comment]
@sonukapoor I was looking for the page that pointed toward `guides/providers`, I found none.

**Comment by sonukapoor** [comment]
I see what you are saying. All routes that are not matched have this issue, so it's not related to that specific route. I tried a few that don't exist and can see the duplicate sidebar.

**Comment by andy-bond** [comment]
I can also reproduce with another link. Also, hi @sonukapoor! :)

I arrived here from: https://angular.dev/guide/i18n/manage-marked-text
Then I clicked on the `$localize` link near the top of that page.

![image](https://github.com/angular/angular/assets/10934345/78d6f9eb-2b39-4bb1-ae1d-0e20899fe538)

**Comment by sonukapoor** [comment]
Hey @andy-bond - Good to see you. 

Thanks for confirming this.

**Comment by JeanMeche** [comment]
@andy-bond We're tracking this in #54388 👍

**Comment by andy-bond** [comment]
Sounds good @JeanMeche.

To @sonukapoor's point, it seems like you are mostly concerned with fixing any missing links. But shouldn't the actual "duplicated UI" be investigated? Otherwise won't this same issue re-occur anytime you have a broken link? Wouldn't a "Page Not Found" be more appropriate?

**Comment by sonukapoor** [comment]
@andy-bond yes. 100%. All issues should be fixed. I was just pointing out that this behaviour can be seen through invalid routes. A 404 page would be better.
