### ISSUE TITLE
To aid debugging: ExceptionHandler messages should be tagged as from the ExceptionHandler

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#5450]
e.g. In my compiled Dart app, I am seeing the following exception:

"EXCEPTION: Instance of 'ProgressEvent'", source: http://ins185:19973/fe3/web/main.dart.js (37501)
"STACKTRACE:", source: http://ins185:19973/fe3/web/main.dart.js (37493)
"null", source: http://ins185:19973/fe3/web/main.dart.js (37493)

Examining the source revealed that this message is printed from Angular's ExceptionHandler. However, the source was not obvious and we spent debugging time looking at a different exception handler.

Instead, of printing "EXCEPTION", it would be better if the ExceptionHandler printed:

"EXCEPTION caught in Angular's ExceptionHandler: Instance of 'ProgressEvent'"

**Comment by mlaval** [comment]
obsolete
