### ISSUE TITLE
Angular.dev docs Expand doesn't work

### ISSUE THREAD

**Issue by csm31** [angular/angular#54513]
### Describe the problem that you experienced

In angular.dev, the expand to see example of code doesn't work anywhere.

### Enter the URL of the topic with the problem

https://angular.dev/guide/templates/interpolation#:~:text=Use%20interpolation%20to%20display%20the%20value%20of%20this%20variable%20in%20the%20corresponding%20component%20template%3A

### Describe the actions that led you to experience the problem

I click on the expand arrow, nothing happens.

### Describe what you want to experience that would fix the problem

An expand to show the code when I click on the expand arrow.

### Add a screenshot if that helps illustrate the problem

https://github.com/angular/angular/assets/69980143/3a32365d-6e80-4d68-a1ea-d34a368aca18

**Comment by JeanMeche** [comment]
Hi, thank you for bring this issue up. We're aware there is a global issue with code blocks. It was initially reported on https://github.com/angular/angular/issues/54471 so let's continu tracking the issue over there.
