### ISSUE TITLE
Angular Dev: Improvement UI snippet "docs-code"

### ISSUE THREAD

**Issue by Til0r** [angular/angular#54520]
### Describe the problem that you experienced

On section 'Example custom loader' i can't see all code because the copy button hides the end part of text.
This issue is present in every "docs-code" element.

### Enter the URL of the topic with the problem

https://angular.dev/guide/image-optimization#using-fill-mode

### Add a screenshot if that helps illustrate the problem

![Screenshot 2024-02-20 at 15 48 28](https://github.com/angular/angular/assets/24627876/d390f467-2210-4852-bb51-e1ac4592999b)
![Screenshot 2024-02-20 at 15 48 41](https://github.com/angular/angular/assets/24627876/b7565017-e1c4-4581-acc0-30db77bff716)

**Comment by JeanMeche** [comment]
Let's track this issue with #53119.
