### ISSUE TITLE
Docs: angular.dev/guide/testing missing image

### ISSUE THREAD

**Issue by ma-altaf** [angular/angular#54537]
### Describe the problem that you experienced

I experience the issue on the angular.dev website testing/overview page (https://angular.dev/guide/testing) it seems like the image src is pointing to a folder that may not exist. 
![image](https://github.com/angular/angular/assets/79712014/1cc7841d-e790-4769-a61e-db1db86efecb)
I know that src/assets is copied into dist folder on ```ng build```. So I was wondering if we copied the images folder from the content folder (adev/src/content/images) and add it into the src/assets folder, i.e src/assets/content/images if that would fix the issue.
![adev_img](https://github.com/angular/angular/assets/79712014/861e8127-4be8-4b91-8811-df3218d8c56f)

I am new to angular, and could not test it locally, since I could not get ```ng serve``` for adev to work on my pc, so I don't know if that would really work.

### Enter the URL of the topic with the problem

https://angular.dev/guide/testing

**Comment by JoostK** [comment]
Thanks for the report, there is indeed an issue with image deployment currently. This is being tracked in #54472.
