### ISSUE TITLE
Docs: Improve Syntax Highlighting

### ISSUE THREAD

**Issue by niklas-wortmann** [angular/angular#54536]
### Describe the problem that you experienced

Angular leverages embedded languages (have a combination of HTML, Typescript and CSS) in one file. A lot of syntax highlighter are not necessarily good with embedded language, this includes also highlighter js which is used in the new documentation.

### Enter the URL of the topic with the problem

https://angular.dev/guide/components

### Describe what you were looking for in the documentation

I'd expect HTML code to have HTML highlighting (+angular syntax for control flow syntax), the examples shown on that very page have Typescript syntax highlighting but not HTML for the template part.

### Describe the actions that led you to experience the problem

Look at code examples in the new docs

### Describe what you want to experience that would fix the problem

<img width="723" alt="image" src="https://github.com/angular/angular/assets/6104311/80ad9209-5e35-4952-afde-675539a262c8">

vs proper highlighting of the same code

<img width="694" alt="image" src="https://github.com/angular/angular/assets/6104311/412e1b83-d419-4239-a9e2-673d5565bd68">

### Provide any additional information here in as much as detail as you can

```true
I think this problem could be nicely solved by using [shiki](https://github.com/shikijs/shiki) which uses the textmate grammar files of the angular language server. It actually fetches the grammar files regular to be always up to date, in case there are additions (e.g. control flow)/fixes.
Shiki also comes with commonly used themes and has easy mechanisms to provide a custom theme.
```

**Comment by niklas-wortmann** [comment]
I integrated Shiki now in various projects, so I'd be more than happy to take care of that, if interested

**Comment by bencodezen** [comment]
Thanks for filing the issue @niklas-wortmann! I'll chat with the team to see what the plan is for this. Happy to loop you in if the plan is to use shiki or something.

**Comment by bencodezen** [comment]
Closing this issue in favor of consolidating into https://github.com/angular/angular/issues/52654
