### ISSUE TITLE
"Angular Devtools only supports Angular versions 12 or above" on new Angular 17 SSR application

### ISSUE THREAD

**Issue by tsteuwer-accesso** [angular/angular#54534]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

I just created an application, installed SSR, and doing some basic HTTP requests and rendering a navigation component. When opening the dev tools, all I see is "Angular Devtools only supports Angular versions 12 and above."

![image](https://github.com/angular/angular/assets/32495798/c77578c0-12a8-4e26-bec6-f6784677e2a7)

![image](https://github.com/angular/angular/assets/32495798/5fc35726-0078-4232-ba7a-f0c354f0fb92)

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

I expect to be able to debug my application.

### Please provide the exception or error you saw [Bug Report only]

```true
![image](https://github.com/angular/angular/assets/32495798/c77578c0-12a8-4e26-bec6-f6784677e2a7)
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version. [Bug Report only]

```true
Ubuntu 20.04
Chrome Version 121.0.6167.160 (Official Build) (64-bit)

Angular CLI: 17.1.3
Node: 20.10.0
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.3
@angular-devkit/build-angular   17.1.3
@angular-devkit/core            17.1.3
@angular-devkit/schematics      17.1.3
@schematics/angular             17.1.3
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by JeanMeche** [comment]
Hi, could you provide a stackblitz repo where we could reproduce this error ? Without that this issue is hardly actionnable to us. Thank you.

**Comment by tsteuwer-accesso** [comment]
@JeanMeche , I actually found out it's because I'm using APP_INITIALIZER. I am going to go ahead and close this in favor of #54546
