### ISSUE TITLE
Enable long stack traces in NgZone by default

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#5453]
More information is always better, especially when you are beginning to develop your app.

**Comment by yjbanov** [comment]
Originally I wanted to enable long stack traces based on Dart's `--checked` option. Run in checked mode and you get long stacks. Run in prod mode and you get short stacks. `dart2js` supports it too and it is able to tree shake based on it, so there's no code size impact. However, there have recently been some changes to how we specify dev mode. I need a refresher on the status quo.

**Comment by naomiblack** [comment]
Will not do this as a default. too expensive at runtime.
