### ISSUE TITLE
Angular SSR does full page refresh from server when using APP_INITIALIZER

### ISSUE THREAD

**Issue by tsteuwer-accesso** [angular/angular#54546]
### Which @angular/* package(s) are the source of the bug?

core, platform-server

### Is this a regression?

Yes

### Description

When using an `APP_INITIALIZER`  that returns a promise pages refreshes always end up being requested from the server. I also noticed that it breaks dev tools.

### Please provide a link to a minimal reproduction of the bug

https://github.com/tsteuwer-accesso/angular-ssr-issue/

### Please provide the exception or error you saw

```true
Clone the repository, `npm ci` then run the app with `npx ng s`.

Open the browser to http://localhost:4200

Open the network tab, click Route 1. Notice it does a full page refresh.
Click Route 2. Notice it does a full page refresh.

Now, open up `app.config.ts` and comment-out `provideAppEnvironment()` from the providers. Refresh the page and everything starts working. It no longer does full page refreshes from the server and dev tools works.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.2.0
Node: 20.10.0
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.2.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.0
@angular-devkit/build-angular   17.2.0
@angular-devkit/core            17.2.0
@angular-devkit/schematics      17.2.0
@angular/cli                    17.2.0
@angular/ssr                    17.2.0
@schematics/angular             17.2.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

### Anything else?

This also break dev tools somehow.

**Comment by JeanMeche** [comment]
This is a hydration issue due to your `EnvironmentService`. 

On the client your `loaded$` observable emit synchronously on the client. Since it doesn't replay on subscribe your  `appEnvironmentFactory` never resolves the promise. 

Replace your `Subject` with a `ReplaySubject(1)` and your apps works fine.

**Comment by JeanMeche** [comment]
Actually I might keep it open because the stable timeout doesn't seems to fire ([NG0506](https://angular.dev/errors/NG0506).  cc @AndrewKushnir

**Comment by AndrewKushnir** [comment]
@JeanMeche we use the `APP_BOOTSTRAP_LISTENER` [here](https://github.com/angular/angular/blob/main/packages/core/src/hydration/api.ts#L171) to init the check, which throws [NG0506](https://angular.dev/errors/NG0506) after a timeout. The `APP_INITIALIZER` handling happens earlier, so if one of the Promises never resolves, the whole application would be in a "broken" state and we never make it into hydration code. I'm wondering if we should have a similar check (console.warn after a timeout), but for `APP_INITIALIZER`s. What do you think?

**Comment by tsteuwer-accesso** [comment]
@JeanMeche , is there a way to figure out what observable causes this issue? We're running to it again and our app is rather large now, and looking for some guidance on this.
