### ISSUE TITLE
Code example not displayed on Testing sections

### ISSUE THREAD

**Issue by cailliaud** [angular/angular#54541]
### Describe the problem that you experienced

There is multiple pages from the Testing documentation that does not display the code.

The code block is expended but the code is not displayed.
During the page loading the doc will appear during 1 sec et after the block is empty but still expanded

![image](https://github.com/angular/angular/assets/19285360/9008a691-05e5-41ea-99cc-51123c1c9e1f)

THe problem does not occure on the following pages:
- Overview
- Code coverage
- Testing Pipes
- Testing Attribute Directives

But it is present on pages:
- Testing services
- Basics of testing components
- Component testing scenarios

### Enter the URL of the topic with the problem

https://angular.dev/guide/testing/services

### Describe what you were looking for in the documentation

I was looking for some example of code to see how to test my components.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/19285360/53b844f2-a3d4-49fc-bc4e-9703cf3084ae)

### Provide any additional information here in as much as detail as you can

```true
I tried to access the documentation using Chrome (121.0.6167.185 (Build officiel) (64 bits)) and Firefox (122.0 (64 bits)) but no changes
```

**Comment by JeanMeche** [comment]
Hi, this issue will be fixed when #54528 is merged.
