### ISSUE TITLE
routeParams.params doesn't decodeURIComponent

### ISSUE THREAD

**Issue by mbalex99** [angular/angular#5455]
If your routeParam was read by the browser to be a URI encoded,
routeParams still returns a URI encoded string

I think routeParams should return a decoded URI string. Otherwise, I think there should be some sort of setting to decode or encode by default.

Example, 

I have a url of `http://localhost:7000/handle/rm%7Copenworld`

The route pattern looks like 

`handle/:handleId`

thus

`routeParams.params["handleId"] ==  'rm%7Copenworld'`

However the decodedURI that was given to the browser is `rm|openworld`

**Comment by zhura** [comment]
+1

**Comment by NathanWalker** [comment]
I have a PR https://github.com/angular/angular/pull/4905 which adds a shared platform function to do uri decoding (`dart` and `js`) for supporting a `.search()` method to `Location`.

I could add the decoding desired above to solve this issue in that PR simply.
Or could open a separate PR to add support for this, but would recommend it be done after this PR https://github.com/angular/angular/pull/4905 lands.

/cc @btford

**Comment by vicb** [comment]
this is related to the old router

**Comment by kellyrmilligan** [comment]
was this ever fixed in the `new` router?
