### ISSUE TITLE
Tutorial editor fails with "SyntaxError: Unexpected token '<'..."

### ISSUE THREAD

**Issue by hansireit** [angular/angular#54568]
### Describe the problem that you experienced

Visit the [documentation page](https://angular.dev/tutorials/learn-angular/components-in-angular).

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/components-in-angular

### Describe what you were looking for in the documentation

The preview was stuck at "Starting" forever because the of an error in the console.

### Describe the actions that led you to experience the problem

Just visit the mentioned tutorial.

### Describe what you want to experience that would fix the problem

A working example of the code.

### Add a screenshot if that helps illustrate the problem

<img width="3360" alt="Screenshot 2024-02-22 at 17 09 17" src="https://github.com/angular/angular/assets/19170734/27ca98c2-f9a8-4aa7-b416-9a6bb4dac22d">

### If this problem caused an exception or error, please paste it here

```true
main-FMRUV77V.js:35 SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
MacOS 14.2.1 (23C71)
Google Chrome Version 122.0.6261.57
```

**Comment by josephperrott** [comment]
This has been fixed by updating the upstream dependency.
