### ISSUE TITLE
Fixed peerDependency in @angular/compiler 17.2.1 to @angular/core@17.2.1 causes peer depency conflicts in new projects

### ISSUE THREAD

**Issue by rehdie** [angular/angular#54564]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

There is a new version of @angular/core (Version 17.2.2).

But there is no new version of the @angular/compiler (latest available version is still 17.2.1).

The @angular/compiler has the following peer-depency:

```
  "peerDependencies": {
    "@angular/core": "17.2.1"
  },
```

If you create a new project using the CLI this fixed Version of 17.2.1 causes peer dependency conflicts.

**Comment by JeanMeche** [comment]
You must be having some cache issues, all framework are released at the same time (there from the same build). 

`@angular/compiler` 17.2.2 is available : https://www.npmjs.com/package/@angular/compiler?activeTab=versions
