### ISSUE TITLE
how to import referece of html in ts file?

### ISSUE THREAD

**Issue by AnushkaSingh1** [angular/angular#54576]
### Is this a bug report or a feature request?

- [X] Bug Report
- [X] Feature Request

### Description [Feature Request only]

<div class="search-container">
    <div class="search-icon" (click)="parent?.openSearchDialog()">
        <i class="fa fa-search"></i>
    </div>
    <ng-template #searchDialogTpl>
        <div class="search-dialog" #searchDialog [style.height]="parent?.searchDialogHeight">
            <div class="close-icon" (click)="parent?.closeSearchDialog()">
                <i class="fa fa-times"></i>
            </div>
            <div class="search-input-wrapper">
            <input type="text" class="form-control" placeholder="Search" [(ngModel)]="model" [ngbTypeahead]="parent.search" [resultTemplate]="rt"
                [inputFormatter]="parent.formatter" (selectItem)="parent?.navigateToItem($event)" />
                <span (click)="parent.clearInput()" class="clear-icon" *ngIf="parent?.model?.length > 0">
                  
                </span>
              </div>
                <div class="search-results">
                  <div class="dropdown-container">
                  <ng-template #rt let-r="result" let-t="term">
                    <div class="list-of-objects-container" *ngIf="r !== []">
                      <div class="list-of-objects">[object Object]</div>
                  </div>
                  </ng-template>
                </div>
              </div>
                <div class="grid-container" #gridContainer *ngIf="parent?.searchResults && parent?.searchResults.length > 0" appCustomScrollbar>
                    <div class="grid-item" *ngFor="let result of searchResults">
                        <div class="item-content" (click)="parent?.navigateToItem(result)">
                          <div class="image-container">
                            <img [src]="result.attributes?.item_image[0]?.location" alt="{{ result.attributes?.item_name[4]?.values }}">
                          </div>
                            <div class="item-name">{{ result.attributes?.item_name[4]?.value }}</div>
                        </div>
                    </div>
                </div>
                <div class="no-results" *ngIf="parent?.searchResults && parent?.searchResults.length === 0 && parent?.model && parent?.model.trim() !== ''">No results found</div>
        </div>
    </ng-template>
</div>

What is the correct way to import this reference in my parent ts file so that all function can work properly without any warnings or errors - #searchDialogTpl
this html is a child html file.

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
