### ISSUE TITLE
Add $log like functionality to Angular 2

### ISSUE THREAD

**Issue by juristr** [angular/angular#5458]
Directly writing `console.log` statements throughout the apps codebase is bad as you don't have any possibility to centrally deactivate it.

Are there any plans on integrating a `$log` like feature in Angular2, or even something a bit more advanced. I've quickly seen [diary.js](https://github.com/angular/diary.js/tree/master) but it seems abandoned.

**Comment by robwormald** [comment]
Not bad idea. Diary is a pretty simple lib, and should still work (with a bit of tinkering) - might be worth bringing into the main repo (and adding Dart support?) @IgorMinar ?

**Comment by jamesmorgan** [comment]
I am surprised I couldn't find a `$log` equalivant in angular? +1 for adding this feature.

**Comment by zoechi** [comment]
In Dart it's `print()` and it can be redefined in zones.

**Comment by blaster151** [comment]
I concur, this is needed.

**Comment by cviccaro** [comment]
+1 I would like to see this as well.  Currently I am using my own LogService.. anyone see a better, more efficient way of doing this or one that is more in line with best practices?  Is this all Angular1's $log is essentially doing?   On that note I suppose I'll go take a look at $log's source.

```
export class LogService {

	enabled = true;

	constructor() {
		this.enabled = '<%= ENV %>' === 'prod';
	}

	assert(message) {
		if (this.enabled) {
			console.assert(message);
		}
	}
	debug(message, ...args) {
		if (this.enabled) {
			console.debug(message, args);
		}
	}
	error(message, ...args) {
		if (this.enabled) {
			console.error(message, args);
		}
	}
	info(message, ...args) {
		if (this.enabled) {
			console.info(message, args);
		}
	}
	log(message, ...args) {
		if (this.enabled) {
			console.log(message, args);
		}
	}
	trace(message, ...args) {
		if (this.enabled) {
			console.trace(message, args);
		}
	}
	warn(message, ...args) {
		if (this.enabled) {
			console.warn(message, args);
		}
	}
}
```

**Comment by sebastianovide** [comment]
+1 for $log equivalent

**Comment by jstuparitz** [comment]
+1 for $log

**Comment by seenimurugan** [comment]
+1 for $log equivalent

**Comment by juristr** [comment]
I didn't look into what diary.js does, yet, but given the reactions from people we should maybe revive it? @robwormald ?

**Comment by danielmhair** [comment]
+1 for $log equivalent

**Comment by marcalj** [comment]
Use the thumbs up button on first comment please!

**Comment by simpss** [comment]
After finding this request, I walked the internets and found this little library: https://github.com/koroandr/log4ts The docs aren't that good, but the source is easy to understand.

`npm install log4ts --save`

created a small wrapper around it. For some reason ngOnInit didn't fire so the initialization has to be called manually for now.

```typescript
import {Injectable} from '@angular/core';

import Logger from "log4ts/build/Logger"
import LoggerConfig from "log4ts/build/LoggerConfig"
import BasicLayout from "log4ts/build/layouts/BasicLayout";
import ConsoleAppender from "log4ts/build/appenders/ConsoleAppender";
import {IAppender} from "log4ts/build/IAppender";
import {ILayout} from "log4ts/build/ILayout";
import {LogLevel} from "log4ts/build/LogLevel";

@Injectable()
export class LogService{

    public log: Logger;

    private appender: IAppender;
    private layout: ILayout;
    private config: LoggerConfig;

    constructor() {

    }

    init(){
        this.layout = new BasicLayout();
        this.appender = new ConsoleAppender();
        this.appender.setLayout(this.layout);
        this.config = new LoggerConfig(this.appender);
        this.config.setLevel(LogLevel.ALL);
        this.log = new Logger();
        Logger.setConfig(this.config);
    }
}
```

and usage:
```typescript
this.logService.log.debug("Something that interests you");
this.logService.info.debug("Something that interests you");
this.logService.fatal.debug("Something that interests you");
this.logService.error.debug("Something that interests you");
this.logService.debug.debug("Something that interests you");
this.logService.warn.debug("Something that interests you");
this.logService.trace.debug("Something that interests you");
```

**Comment by astec** [comment]
@simpss too many dots to call, probably would be better if usage was something like:

```
this.logInfo("Something that interests you");
this.logFatal("Something that interests you");
this.logError("Something that interests you");
this.logDebug("Something that interests you");
this.logWarn("Something that interests you");
this.logTrace("Something that interests you");
```

**Comment by gorilla77** [comment]
@cviccaro You can use this to get the "correct" line number:
```
info = console.info.bind(console);
info("Log me");
```

**Comment by cviccaro** [comment]
@gorilla77 Thanks!  I used it like this:

```typescript
export class LoggerService {
	get log() {
		return console.log.bind(console);
	}
```

It was the only way I found I could get the appropriate line number to show up.  I didn't realize what you wanted to do is to return the bound function from the logger service.  I was, at first, trying to return an anonymous function like Angular1's logger.

**Comment by juristr** [comment]
Ben Nadel (@BenNadel) just published an article about this topic. Might be interesting for some of you: http://www.bennadel.com/blog/3129-implementing-a-log-inspired-logging-service-in-angular-2-rc-4.htm

**Comment by skdhir** [comment]
So is this feature implemented and available in new version, not very clear from comments.

**Comment by MickL** [comment]
@cviccaro Sorry i don't get it. How can you log a string without any arguments in log()?

I tried: 

log(message) {
   // Server-side logging here
    return console.log(console);
  }

But i dont see correct line numbers.

**Comment by cviccaro** [comment]
@MickL Sorry, that was a bit old.  Try this approach to get correct line numbers:

```typescript
import { Injectable } from '@angular/core';

@Injectable()
export class LoggerService {
	enabled = true;
	noop = () => {};

	constructor() {
                // You can do a check on your environment or some other flag to 
                // enable/disable logging
		// if ((<any>'<%= ENV %>') === 'prod') this.enabled = false;
	}

	get debug() {
		if (this.enabled) return console.debug.bind(console);
		return this.noop;
	}

	get error() {
		if (this.enabled) return console.error.bind(console);
		return this.noop;
	}

	get log() {
		if (this.enabled) return console.log.bind(console);
		return this.noop;
	}

	get info() {
		if (this.enabled) return console.info.bind(console);
		return this.noop;
	}

	get warn() {
		if (this.enabled) return console.warn.bind(console);
		return this.noop;
	}

}

**Comment by MickL** [comment]
I still dont get it. How can you call `this.logger.log('HELLO WORLD');` if this is only a get function without any arguments?

**Comment by cviccaro** [comment]
@MickL Javascript can have properties with getters.  So when you instantiate the LoggerService, the log is actually a property of it, which returns a properly bound console.log function ready to be used.  So.. LoggerService.log returns a function.  To clarify, a simple example component:

```typescript
export class SomeComponent {

constructor(private logger: LoggerService) {}

ngOninit() {
// Log variable will now be properly bound console.log function.  If you console.log this variable, you'll see the function outputted as a string.
let log = this.logger.log;

// The variable can then be used as a function
log('SomeComponent has initialized', this);

// But you'll use it this way.  The previous 2 lines of code were to help clarify how it works.
this.logger.log('SomeComponent has initialized.', this);


}

}

**Comment by MickL** [comment]
Oh i target ES5 :/

**Comment by cviccaro** [comment]
@MickL That's my mistake, it works for ES5, too.  Are you receiving errors when trying to use that code or are you just a little unclear on how it works?

**Comment by MickL** [comment]
Oh wow its actually working. But how do i get the inserted string?

```
get log() {
    this.serverLogger.debug(message); // HOW ?
    return console.log.bind(console);
  }
```

**Comment by cviccaro** [comment]
@MickL The inserted string never actually hits the code within LoggerService.  LoggerService.log is just a property, just as if you had a regular object with a property with a value i.e. { property: 'value' }.  But in this case, it only has a getter.  It does not have a setter, so the property is read-only.  The only thing LoggerService does is return to you a function ready-to-be used, which is different than if the property itself was a function.  I hope that's not confusing.

So you wouldn't be able to access the inserted string from within that code.  

Are you trying to tie together two debuggers, one for console and one to log to the server?  Because that's an interesting problem I've not tried to solve yet.  My first inclination would be to write another service, like DebugService or something, that wraps around the LoggerService, and create another service for the server debugging, and call both from within the DebugService.  But right now I'm not sure how you'd handle returning to any of your components a properly-bound console function to ensure the file & line numbers are outputted correctly.  

As a horrible workaround for now, you can create another logger service for the server debugger, and just call both, but I don't like that idea.

Maybe someone else in this thread has a better idea how you'd handle that, but I'll try to think up a solution if I can.

**Comment by MickL** [comment]
Yes. Currently i want to have two loggers in one. Also i want hide console.log on production and maybe do more stuff later. I tried alot and googled alot but didn't find any solution to show the line numbers.

**Comment by uberspeck** [comment]
@cviccaro , i've implemented your logger and I'm getting an error...

```
undefined is not an object (evaluating '_this.logger.log')
```

My implementation...

```typescript
import { Pipe, PipeTransform } from '@angular/core';

import { LoggerService } from '../../../logger/logger.service';

@Pipe({
  name: 'afterDate'
})
export class AfterDatePipe implements PipeTransform {

  constructor(
    private logger: LoggerService
  ){ }

  transform(items:Array<any>, date): Array<any> {
    return items.filter( (item, index, array) => {
      this.logger.log('testing', this);
    });
  }

}

```

**Comment by leshin** [comment]
+1 for $log equivalent

**Comment by k1r0s** [comment]
Hey guys, just keep an eye on this, it could be use to loggin, but many many use cases too

https://stackoverflow.com/questions/39407298/how-to-implement-aop-in-angular-2/44290042#44290042

**Comment by samudurand** [comment]
any update on a logging service in Angular 2 ?

**Comment by MGray55** [comment]
👍 +1 would be nice

**Comment by harikrishnan-u01** [comment]
Is there any fix planned for implementing $log as part of Angular 5 release?

**Comment by jesujcastillom** [comment]
+1

**Comment by mtpultz** [comment]
Can you please stop using +1 and just hit subscribe, and/or add an emote to peoples responses where you agree or disagree.  This +1-itis drives everyone crazy with useless notifications while we all patiently wait for features that are marked for implementation at some point based on the issues labels.  This is why subscribe and emotes were added.  Yes, everyone wants this feature you're not adding any weight to the conversation unless you're providing some sort of insight into implementation.  Lets try and make the next notification for this feature be the actual closing of the issue.

**Comment by Toxicable** [comment]
The implementation of this issue is currently blocked on the fact that Services are not easily tree shakable see here:
https://github.com/angular/angular/pull/17399#pullrequestreview-49350645
Feel free to suggest a designed where these issues have been reduce if you want to seee this in core sooner.

**Comment by Anish895** [comment]
how to generate .log extension in angular 4 .. Is there any possible way to create and use??

**Comment by splincode** [comment]
@juristr Is the issue relevant?

**Comment by ocombe** [comment]
@splincode please stop spamming old issues asking if they are still relevant, I assume that you have good intentions, but it's annoying.

**Comment by splincode** [comment]
@ocombe I just wanted to know whether to close the old tasks, if they are not relevant

**Comment by juristr** [comment]
It's somehow relevant but it's an old issue and I think ppl have found other ways (i.e. external libs or custom impl) and moved ahead. I'm closing this as there are way more important features to be implemented 🙂

**Comment by splincode** [comment]
@juristr Thank you for having responded, I am grateful to you!!!

Also I develop an improved version of the logging for Angular
https://github.com/splincodewd/client-logger

**Comment by msalehisedeh** [comment]
looks like this conversation halted back in July and i am a late comer in this conversation. But, checkout @sedeh/smart-counsole on npm and let me know what you think.
Live demo is on [https://smart-console.stackblitz.io/](https://smart-console.stackblitz.io/)
