### ISSUE TITLE
Container CSS Queries don't work with ::ng-deep

### ISSUE THREAD

**Issue by linelson** [angular/angular#54582]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Container CSS queries (https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries) don't seem to work with ::ng-deep. I know ::ng-deep is technically deprecated, but there isn't a great alternative and it's been in a weird zombie state for years per https://github.com/angular/angular/issues/25160.

I would expect that ::ng-deep would either work with @container queries or documentation would state that ::ng-deep is not expected to work with container CSS queries.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/e7uwsy?file=src%2Fapp%2Fencapsulation.css

### Please provide the exception or error you saw

```true
Expected: Using ::ng-deep with an @container query works **or** documentation for ::ng-deep states that it is not expected to work with container queries

Actual: ::ng-deep combined with @container query doesn't work.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
I'm running into this with a google-internal Angular app.
Also see linked stackblitz with Angular 17.1.3
```

**Comment by JoostK** [comment]
This doesn't work as `::ng-deep` is not considered as selector of its own, but it does work when `::ng-deep` and `*` are combined into a single level: `::ng-deep *`.

I haven't checked yet if we can address this. I'd expect that SCSS compiles the leveled CSS into flattened rules, in which case there wouldn't be a difference.

**Comment by linelson** [comment]
Ah, I missed that the demo I forked was using CSS rather than sass, which made me think I had a repro of the issue I was seeing when I didn't.

This appears to be working as expected.
