### ISSUE TITLE
A typo in a SVG file

### ISSUE THREAD

**Issue by PavelTurk** [angular/angular#54592]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

There is a typo in file https://github.com/angular/angular/blob/main/aio/content/images/guide/dependency-injection/injectors.svg 
(extra single quote) at 1:143
```
<style>@import url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css");'</style>
                                                                                                ^
```
                   

### Anything else?

It doesn't mean I have nothing to do. I can't validate this file.

**Comment by awais4088** [comment]
ggod
