### ISSUE TITLE
Type definition conflict with jQuery TSD

### ISSUE THREAD

**Issue by teropa** [angular/angular#5459]
When trying to compile a TypeScript file that imports something from `angular2` (2.0.0-alpha.46) and also references the TSD type definitions for jQuery, I get the following error from the TypeScript compiler:

    node_modules/angular2/typings/angular-protractor/angular-protractor.d.ts(1679,13): error TS2403:
    Subsequent variable declarations must have the same type.  Variable '$' must be of type
    'JQueryStatic', but here has type 'cssSelectorHelper'.

The app itself doe not refer to Protractor in any way. The types are pulled in by Angular 2 internally, it seems.

Use case: Running a hybrid Angular 1+2 app during upgrade. The Angular 1 type definitions from TSD  also pull in jQuery type definitions, and I suspect they'll be commonly used during upgrades.

Minimal repo that reproduces the problem: https://github.com/teropa/ng2-jquery-type-conflict

Suggested fix: Don't include Protractor type definitions unless the user asks for them?

**Comment by dsebastien** [comment]
There's a common theme here: https://github.com/angular/angular/issues/5395 :)

**Comment by ericmartinezr** [comment]
There's another issue related https://github.com/angular/angular/issues/4725

**Comment by gdi2290** [comment]
[typings](https://github.com/typings/typings) fixes this (the TSD replacement)
related [The State of Typescript Packages](https://angularclass.com/the-state-of-typescript-packages/)

**Comment by dsebastien** [comment]
Thanks for the links @gdi2290, I'll check that out! There's indeed still room for improvement in TS typings land ;-)

**Comment by episodeyang** [comment]
@gdi2290 I tried to install jquery and angular2 using typings. DId this **just** came out today?

**Comment by blakeembrey** [comment]
@episodeyang Those typings are not in the registry. If you would like to create them and contribute them to the registry, you're welcome to! You should have seen this message when you tried to use it:

```
➜  typings git:(master) typings i angular -S
TypeError: Unable to find "angular" from "npm" in the registry. If you can contribute this typing, please help us out - https://github.com/typings/registry
```

**Comment by yizhan** [comment]
I had the same problem when i upgrade angular. We do not use angular-protractor.d.ts, but it has been added in there when import as angular/angular. Is angular-protractor compulsory?

I tried to comment angular-protractor.d.ts out which also fix this problem. That would not be a solution, because it is a part of package. 

In the end, I have to commented

    declare module "jquery" {
        export = $;
    }

    declare var $: JQueryStatic;

**Comment by episodeyang** [comment]
Hi, this problem still persists in alpha.47.

**Comment by Demurgos** [comment]
Thank you @gdi2290, `typings` seems really promising. It would be great if angular's definition would not leak as described in the article.

**Comment by laco0416** [comment]
I have the same problem in angular2-beta.0 and angularjs-1.4.8

**Comment by laco0416** [comment]
@IgorMinar Hi, what do you think this?  Due to this, I cannot do a migration from ng1 to ng2.

**Comment by gdi2290** [comment]
@laco0416 you should switch to `typings`. I recommend deleing the types in the angular2 repo and manage it with `typings` outside. You should also have a config for each environment. For an example see https://github.com/angular/universal-starter/commit/cfb7b52b12e1da9de7ee7c2a452e7636c93aaa09

**Comment by IgorMinar** [comment]
We are working on resolving this. Part of the solution landed already:
https://github.com/angular/angular/pull/6262

The final part of the solution is in works now.

**Comment by NikGovorov** [comment]
It seems to work in beta2.

**Comment by alexeagle** [comment]
I believe this is fixed. Note that angular-protractor.d.ts and jquery.d.ts still conflict on the definition of `$`, see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/2734
