### ISSUE TITLE
console.log d'ont display anything in google or edge inspector

### ISSUE THREAD

**Issue by pdeleg** [angular/angular#54607]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

console.xxx() d'ont work on some contexts.
It run if we put it on a ngOnInit()
But it never work if we put it in a called method() form a (click) event.

### Please provide the exception or error you saw

```true
There isn't any exception or message
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
angular/cli": "^17.1.0",
Node : 20.11.0
ng-bootstrap": "^16.0.0"
Windows 11
```

**Comment by alxhub** [comment]
Without a working reproduction, we won't be able to investigate this issue at all. Please post a running reproduction in Stackblitz in order for us to be able to diagnose what might be happening.

`console.log` is a browser feature, though - as long as the line of code runs, it will log to the console.

**Comment by pdeleg** [comment]
We have found the origin of the problem.
This deviant behavior is linked to the inclusion of a JavaScript library offering accessibility solutions
