### ISSUE TITLE
undefined also removes the class binding

### ISSUE THREAD

**Issue by arpitmehrotra** [angular/angular#54601]
### Describe the problem that you experienced

In the angular.dev/angular.io documentation, its mentioned that "Angular adds the class when the bound expression, onSale is truthy, and it removes the class when the expression is falsy—with the exception of undefined." under the section **Binding to a single CSS**

### Enter the URL of the topic with the problem

https://angular.dev/guide/templates/class-binding

### Describe what you were looking for in the documentation

It basically removes the class binding, even when the expression evaluates to __undefined__.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/5306277/a6cf3949-cbee-470b-a3fc-9bc02e625565)

**Comment by JeanMeche** [comment]
The phrasing probably isn't great but `undefined` has a specific behavior. 

`<div [class.foo]="true" [class.foo]="false"></div>` will result in an empty `class` attribute on the `div`

where `[class.foo]="true" [class.foo]="undefined"` will result in `class="foo"`.

**Comment by alxhub** [comment]
Note also that this seems silly when all of the bindings are in one place, but this also affects the behavior when multiple bindings to the same class exist across different directives on an element.
