### ISSUE TITLE
chore(http): remove all private imports from http

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#5460]
Some parts of http are importing from private paths (`angular2/src/....`), but should only import from public "barrels". 

@vsavkin how do we enable the automatic restriction for this module?

@robwormald can you lump this in whenever you get back to http work?

**Comment by pkozlowski-opensource** [comment]
From my last checks htttp only imports from:
*  `angular2/angular2` (and this should be changed to imports from `angular2/core`, see: https://github.com/angular/angular/pull/5431)
* facades

**Comment by pkozlowski-opensource** [comment]
From my last discussion with @vsavkin imports from facades should be allowed, so we might not have much to do here apart from merging #5431- unless something have changed here :-)

**Comment by jeffbcross** [comment]
@pkozlowski-opensource cool, thanks. I think @vsavkin actually is in the process of correcting that one import in a PR he's working on, so perhaps this issue is a no-op. 

@vsavkin if that's true, can you just enable the enforcement of no private imports?

**Comment by vsavkin** [comment]
Yes. We allow importing from facades.

You can enable the enforcement here angular/tools/broccoli/broccoli-check-imports.ts. You probably want to add something like this:

` "angular2/src/http": ["angular2/core", "angular2/src/facade", "angular2/src/http"]`

**Comment by pkozlowski-opensource** [comment]
@jeffbcross @vsavkin opened https://github.com/angular/angular/pull/5510 to enforce import checks on the http module level.

The only "suspicious" import is `import {ReplaySubject} from '@reactivex/rxjs/dist/cjs/Rx';` in mock_backend.ts - I'm not sure if we can get rid of this one.
