### ISSUE TITLE
Flickering when changing API tabs 

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular#54613]
### Describe the problem that you experienced

When changing from description to Usage notes there is a slight flickering due do a layout shift 

Here is a screenshort exported from a performance audit (sorry for the low res).

![image](https://github.com/angular/angular/assets/1300985/66d1040a-f283-47ad-805c-5066a44bafe5)

### Enter the URL of the topic with the problem

https://angular.dev/api/core/afterNextRender

**Comment by jakehockey10** [comment]
I don't notice it on mobile, for what that's worth

**Comment by veera20k** [comment]
<img width="775" alt="Screenshot 2024-02-27 at 11 31 13 AM" src="https://github.com/angular/angular/assets/84136744/6e3e52e0-3284-4d7b-a2ce-52e7fd9dee19">
not able to reproduce the flickering issue. But where are the description contents? Is that an issue?. I just reloaded the page.

**Comment by naaajii** [comment]
I can't also seem to see tabs content on initial page load

https://github.com/angular/angular/assets/54370141/98ea125e-48b2-4b57-869d-28e802fff474

122.0.6261.70 (Official Build) (64-bit) (cohort: Stable)

**Comment by danieljancar** [comment]
Hey everyone,
I can confirm the flickering (video below). Seems like the footer isn't correctly positioned on the bottom at first? I'll dig into it further. 

Uploading Screen Recording 2024-02-27 at 10.03.25.mov…

**Comment by ilirbeqirii** [comment]
[ng-screen-record.webm](https://github.com/angular/angular/assets/24731032/7ed688bc-fed3-4b8e-8629-264f990c7064)

As far as I can see its this "display: contents" CSS property that is making this issue show up. If you use the default display of block then seems no issue is there.
