### ISSUE TITLE
Duplicate string containing an @

### ISSUE THREAD

**Issue by Pxngel** [angular/angular#54617]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When I try to display an email or any value that contains an @ and immediately after contains text:
Let's say
" aaaaddddda.com@" + "adad.com"
The value is always doubled when displayed in the html.

<img width="398" alt="image" src="https://github.com/angular/angular/assets/28811770/ba670ea9-13c7-450e-ba08-43b2731e1831">

<img width="398" alt="image" src="https://github.com/angular/angular/assets/28811770/12cbc9bc-5541-4297-acce-2451c77edbaa">

<img width="398" alt="image" src="https://github.com/angular/angular/assets/28811770/4801ddf4-5f03-41ef-a270-0e267df0d4dd">

(

### Please provide a link to a minimal reproduction of the bug

https://seo.neixtmedia.com/

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.2.1
Node: 18.14.0
Package Manager: npm 9.3.1
OS: darwin arm64

Angular: 17.2.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.1
@angular-devkit/build-angular   17.2.1
@angular-devkit/core            17.2.1
@angular-devkit/schematics      17.2.1
@angular/cli                    17.2.1
@angular/ssr                    17.2.1
@schematics/angular             17.2.1
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.4
```

**Comment by JeanMeche** [comment]
Hello, your app is using SSG with hydration.
It looks like you have a script that is messing we the DOM ahead of the hydration. The DOM should be altered ahead of hydration.

**Comment by Pxngel** [comment]
> Hello, your app is using SSG with hydration. It looks like you have a script that is messing we the DOM ahead of the hydration. The DOM should not be altered ahead of hydration.
> 
> You probably have an error logged in the console when running the app in debug mode.

Hello, thank you for answering, I was checking and I did not detect any type of error when compiling, I attach the code that I am testing

https://github.com/Pxngel/error-duplicaded-angular

**Comment by JeanMeche** [comment]
Interesting, it seems like it is something enabled by cloudflare. It detects an inline email address an obfuscates it to prevent it from being collected. 

see: https://developers.cloudflare.com/waf/tools/scrape-shield/email-address-obfuscation/

**Comment by Pxngel** [comment]
Thank you very much, that was it.
