### ISSUE TITLE
Angular Application not detected

### ISSUE THREAD

**Issue by Dxhxm88** [angular/angular#54628]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

After updating Chrome to Version 122.0.6261.69. The Angular Devtools not able to detect the application anymore. I even ask my team to check and they also got the same issues.

Application Angular version: 10.2.3

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

Expected: Angular Devtools able to detect the angular application

Actual: Angular Application not detected

### Is this a browser-specific issue? If so, please specify the device, browser, and version. [Bug Report only]

```true
Macbook Air M1 2020, MacOS 14.2.1 (23C71)
Chrome Version 122.0.6261.69
```

**Comment by JeanMeche** [comment]
Hi, thank you for reporting this issue. We're aware of it and tracking it in #53953. Let continue over there for the follow up, thank you.

**Comment by Dxhxm88** [comment]
Hi @JeanMeche, thank you for the follow up.
