### ISSUE TITLE
Way to get a list of routes for lazy navigation

### ISSUE THREAD

**Issue by Amaratsu** [angular/angular#54641]
### Description

Hello, please add a way to get a list of routes for lazy navigation

### Proposed solution

Hello, please add a way to get a list of routes for lazy navigation

### Alternatives considered

Hello, please add a way to get a list of routes for lazy navigation

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
