### ISSUE TITLE
Input option declared with an alias in a custom directive stopped working in v17.1.0 onwards

### ISSUE THREAD

**Issue by AbdiasM** [angular/angular#54655]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Up until v17.0.9, an Input option declared with an alias was working fine. Upon upgrading to v17.1.0, the Input option isn't working anymore and shows the error - Can't bind to '<input option name>' since it isn't a known property of 'ng-template'.

`@Directive({
    selector: '[testDirective]',
    inputs: ['testDirective', 'testOption: testAlias'],
    exportAs: 'testDirective',
    providers: [{ provide: 'tcomponent', useExisting: forwardRef(() => TestDirective)}]
})
export class TestDirective implements ngCore.OnInit, ngCore.OnDestroy {
    testDirective: any;
    testOption: string;
    testAlias: CustomEnumType;
}

@NgModule({
    imports: [CommonModule],
    declarations: [TestDirective],
    exports: [TestDirective],
})
export class TestModule {
}`

### Please provide the exception or error you saw

```true
Can't bind to 'testAlias' since it isn't a known property of 'ng-template'
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI : 17.1.0
Node : 20.11.0
Package Manager : npm 9.6.5
OS : Windows 10
```

**Comment by JoostK** [comment]
I tried to reproduce this but wasn't able to: [StackBlitz repro works](https://stackblitz.com/edit/node-kj1ihu?file=test%2Fsrc%2Fapp%2Fapp.component.ts).

Please provide a runnable reproduction that shows the issue.

**Comment by AbdiasM** [comment]
@JoostK Thanks for checking this. This is the modified [StackBlitz repro](https://stackblitz.com/edit/node-z7jldx?file=test%2Fsrc%2Fapp%2Fapp.component.ts). The alias is actually a custom enum type.

**Comment by JoostK** [comment]
That works fine, once all (unrelated) compilation errors are addressed?

**Comment by alxhub** [comment]
Closing as not reproducible.
