### ISSUE TITLE
error code 5 with `withViewTransitions()` on Chrome

### ISSUE THREAD

**Issue by JSmithOner** [angular/angular#54679]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I have a multi-project project.
When switching from a route to another I get an `error 5` on Chrome but not on Firefox.
The 2 routes uses components of different inner projects.
when removing `withViewTransitions()` the error disappears 

### Please provide the exception or error you saw

```true
`error 5`
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.8
Node: 18.13.0
Package Manager: npm 8.19.3
OS: darwin arm64

Angular: 17.0.8
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.8
@angular-devkit/build-angular   17.0.8
@angular-devkit/core            17.0.8
@angular-devkit/schematics      17.0.8
@angular/material               17.0.4
@schematics/angular             17.0.8
rxjs                            7.5.7
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else?

one of the route uses WebMIDI API and MediaDevices

**Comment by JeanMeche** [comment]
Error 5 is a Chrome crash likely not related to the framework itself. View transitions are an environment feature, so bugs can happen.

I'd recommand to open the issue on Chrome itself.

**Comment by atscott** [comment]
Agreed with @JeanMeche, there’s no indication that this is a framework bug so I’d recommend reporting this as a Chrome bug instead.
