### ISSUE TITLE
Page Not found issue

### ISSUE THREAD

**Issue by leethi** [angular/angular#54673]
### Describe the problem that you experienced

https://angular.dev/tutorials/learn-angular/components-in-angular.
<img width="924" alt="pageNotFound" src="https://github.com/angular/angular/assets/29910651/08941828-028b-4a97-81e5-e3cc34c2a5fc">

**Comment by JeanMeche** [comment]
Hi, thank you for reporting this issue, someone already opened a PR, so this will be fixed soon. 

See #54669.
