### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by akhi799** [angular/angular#54678]
### Describe the problem that you experienced

https://angular.dev/tutorials/learn-angular/components-in-angular

This path is saying path not found for tutorials

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/components-in-angular

### Describe what you were looking for in the documentation

I am begining to learn angular. I was looking for tutorials.

**Comment by JeanMeche** [comment]
Hi, we're aware of this issue and a PR (#54669) is already pending. We're looking into merging early next week, thank you.
