### ISSUE TITLE
@placeholder vs @loading

### ISSUE THREAD

**Issue by eluchsinger** [angular/angular#54685]
### Describe the problem that you experienced

Reading the [@defer](https://angular.io/guide/defer#blocks) documentation, the two sub blocks `@placeholder` and `@loading` are mentioned.

But there is no guidance on when to use which one and what the differences are. Both blocks seem to do the same thing and accept the same parameters. A loading spinner can also be a placeholder.

How should each one of these sub blocks be used? Is this just a semantic difference?

### Enter the URL of the topic with the problem

https://angular.io/guide/defer#blocks

### Describe what you want to experience that would fix the problem

Expand on when to use `@loading` vs `@placeholder`. There seems to be no difference in functionality.

**Comment by eluchsinger** [comment]
Sorry - I must have missed that first paragraph. I agree that the sentence in the `@placeholder` sub block makes it quite clear. But the second sentence only makes sense after realizing that there are three states in a `@defer` block:

1. Waiting: The `@defer` block has not been triggered; conditions not met. The content is **not** loading.
2. Loading: The `@defer` is triggered (conditions are met). The deferred content is loading. The `@placeholder` block is now hidden and the `@loading` block is showing).
3. Loaded/Ready: The deferred content is loaded and shown. Other sub blocks disappear.

**Comment by ducin** [comment]
IMO adding a simple sentence would help a lot:

> The `@loading` block is an optional block that allows you to declare content that will be shown during the loading of any deferred dependencies. **_The `@loading` block replaces the @placeholder block once loading has been triggered._** For example, you could show a loading spinner. Similar to `@placeholder`, the dependencies of the `@loading` block are eagerly loaded.

**Comment by eluchsinger** [comment]
I have created a PR for your change @ducin. I think it's a small enough change so that it's hopefully not complicated to merge it 👍 . Let's see what happens!

**Comment by AndrewKushnir** [comment]
Closing this issue, since PR #54779 was merged.
