### ISSUE TITLE
Angular 17 Tutorial - Build your first Angular app - Application bundle generation failed

### ISSUE THREAD

**Issue by regiss** [angular/angular#54683]
### Describe the problem that you experienced

Missing images in tutorial - CSP issue?

Application bundle generation failed. [9.293 seconds]
✘ [ERROR] Could not resolve "./app/app.component"

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app

### Add a screenshot if that helps illustrate the problem

<img width="933" alt="image" src="https://github.com/angular/angular/assets/198265/bf3f2428-9c6f-4af4-b4e7-f7448a73041e">

**Comment by sonukapoor** [comment]
Related PR #54694

**Comment by bencodezen** [comment]
This is now fixed.
