### ISSUE TITLE
Tests need a way to handle asynchronous behavior that happens through the template

### ISSUE THREAD

**Issue by juliemr** [angular/angular#5468]
Until zones for unit tests work completely (see #5515), asynchronous tests need to return a promise so that they run to completion and catch all errors. This is difficult when the asynchronous event comes through the template, because it's hard to get hold of a promise. For example:

```js
@Component({
  selector: 'my-cmp',
  template: `<button (click)="enter()">Enter</button>`
})
export class MyComponent {
  pending: Promise<any>; // This is a terrible solution!! This is stored ONLY for tests.

  enter() {
    this.pending = getAPromiseSomehow().then(doStuff);
  }
}
```

A current test would look like:

```js
  it('does stuff', injectAsync([TestComponentBuilder], (tcb) => {
    return tcb.createAsync(MyComponent).then((fixture) => {
      fixture.detectChanges();
      var compiled = fixture.debugElement.nativeElement;

      compiled.querySelector('button').click();

      // We shouldn't need to use the property `pending` here.
      return fixture.debugElement.componentInstance.pending.then(() => {
        fixture.detectChanges();
        doExpectations();
      });;
    });
  }));
```

cc @rkirov

**Comment by rkirov** [comment]
+1 The proposed solution would have to be an async method (asyncTick) on test fixture that would resolve all microtasks queued up in the angular zone.

`return fixture.asyncTick(() => doExpectations())`

**Comment by juliemr** [comment]
Hm, I'm not sure that's possible, since we still don't have a hold of the promise anywhere (without hacking Promise). That means there'd be no way to report on uncaught promise rejections.

**Comment by juliemr** [comment]
This will be fixed with https://github.com/angular/angular/issues/7472

**Comment by juliemr** [comment]
Done with 8490921
