### ISSUE TITLE
Unable to react to an API response.

### ISSUE THREAD

**Issue by ht990332** [angular/angular#54686]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Hi. I am having an issue with the following code. I posted on stackoverflow and it was suggested this is a bug that I should post here:

```
export class HeaderComponent implements OnInit {

  authService = inject(AuthService)

  isLoggedIn$ = new BehaviorSubject<Boolean>(false);

  ngOnInit(): void {
    console.log('IS INIT');
    this.authService.authStatus().pipe(
      tap( console.log ),
      tap( res => {
          this.isLoggedIn$.next(!!res?.body)
      } )
    ).subscribe(
      () => {},
      ( err ) => {
        console.log( err );
        this.isLoggedIn$.next( false );
      }
    )
  }
}
```

```
  authStatus(): Observable<HttpResponse<object>> {
    return this.http.get(`${apiUrls.authServiceApi}/status`,
      { observe: 'response', withCredentials: true });
  }
```

then in the template:

 ```
   <ng-container *ngIf="!(isLoggedIn$ | async)">
      <span
        [routerLink]="['/login']"
        routerLinkActive="router-link-active"
        class="text-xl cursor-pointer text-gray-200 font-bold m-3 hover:underline hover:text-indigo-200"
        >Login</span
      >
      <span
        [routerLink]="['/register']"
        routerLinkActive="router-link-active"
        class="text-xl cursor-pointer text-gray-200 font-bold m-3 hover:underline hover:text-indigo-200"
        >Register</span
      >
    </ng-container>
```

However, the header template is not immediately updated on logging in (logging in correctly saves an httponly cookie, then used to poke the api through the header component). it's only updated after a page refresh to hide the login/register links.

stackoverflow link: https://stackoverflow.com/questions/78096543/monitoring-api-response-from-angular/78099204

### Please provide the environment you discovered this bug in (run `ng version`)

```true
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.2.2
Node: 20.11.1
Package Manager: yarn 1.22.21
OS: linux x64

Angular: 17.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.2
@angular-devkit/build-angular   17.2.2
@angular-devkit/core            17.2.2
@angular-devkit/schematics      17.2.2
@angular/cli                    17.2.2
@schematics/angular             17.2.2
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

**Comment by JoostK** [comment]
This isn't actionable without a runnable reproduction. There's probably something wrong _somewhere_, but that's not apparent from these code snippets.

**Comment by ht990332** [comment]
I'll look at how to do that. In the meantime, I'll attach my code just in case something is immediately visible.

**Comment by ht990332** [comment]
[client.zip](https://github.com/angular/angular/files/14481832/client.zip)

**Comment by chabb** [comment]
Subscribe is going to be always called, so `isLoggedIn$` is always going to be `false`

**Comment by ht990332** [comment]
On Mon, 2024-03-04 at 05:11 -0800, Chabbey François wrote:
> Subscribe is going to be always called, so isLoggedIn$ is always
> going to be false
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>

Ok, if that's the case, could you please guide me on what I should
learn to use in order to fix this?
This is essentially only me trying to learn this.

**Comment by JoostK** [comment]
```ts
import { Observable } from 'rxjs/internal/Observable';
import { BehaviorSubject } from 'rxjs/internal/BehaviorSubject';
import { tap } from 'rxjs/internal/operators/tap';
```

those `internal` imports are definitely not meant to be used. May not be relevant to the cause, but something to address anyway.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
