### ISSUE TITLE
RangeError: Maximum call stack size exceeded when adding listener to WebSocket in Chrome browser

### ISSUE THREAD

**Issue by starjumper30** [angular/angular#5469]
If Angular2 is loaded, then I can't add an event listener to a WebSocket without getting an infinite loop from zone.js. 

I am of course having this issue in an actual ng2 app. However, in this [plunk](http://plnkr.co/edit/bc5r6Y0pUWxKENTgwLM9?p=preview), I have simplified it down to just loading the angular libraries. If the angular script tag is removed, the WebSocket works.

I get the error when I run this example in Chrome but not in Firefox.

**Comment by robwormald** [comment]
@starjumper30 this doesn't fail for me in Chrome (v46, OS X) 

I've also used WebSockets with great success in Angular2 already, so perhaps you could post a sample of the code you're using in context?

**Comment by starjumper30** [comment]
I was using Chrome version 40 on Windows 7. I just now installed version 46 and the plunk works. So, the problem must be specific to earlier versions of Chrome.

**Comment by umdstu** [comment]
I'm on Chrome 55 macOS, with angular 1.x, and I get the same error.

Uncaught RangeError: Maximum call stack size exceeded
    at $WebSocket.<anonymous>
    at applyAsyncOrDigest
    at $WebSocket._onMessageHandler
    at WebSocket.<anonymous>
