### ISSUE TITLE
Twitter name Changing 

### ISSUE THREAD

**Issue by Sakthi1112** [angular/angular#54709]
### Describe the problem that you experienced

Twitter name has to be change as X, since the organization have changed its name to X but in angular.io application its not changed in the footer and also need to change the X  icons note when hover on the top rigth
![Screenshot 2024-03-05 225034](https://github.com/angular/angular/assets/91306041/f055988d-5e25-4dc3-960b-565112e40255)
![Screenshot 2024-03-05 225055](https://github.com/angular/angular/assets/91306041/5c4e3b32-66fd-4c66-b2c5-12fe17c68847)

### Enter the URL of the topic with the problem

https://angular.io/

**Comment by alxhub** [comment]
angular.io is in maintenance mode. angular.dev is the upcoming new docs site, and uses the language "X (formerly Twitter)".
