### ISSUE TITLE
Copy button of code example on angular.dev blocks the code

### ISSUE THREAD

**Issue by JoepKockelkorn** [angular/angular#54716]
### Describe the problem that you experienced

While browsing [the signals guide on angular.dev](https://angular.dev/guide/signals) I cannot read the full code example(s), because the copy button is blocking it.

### Enter the URL of the topic with the problem

https://angular.dev/guide/signals

### Describe what you were looking for in the documentation

A clear, readable code example.

### Describe the actions that led you to experience the problem

Reading the page, trying to understand the code (regarding signals in this case).

### Describe what you want to experience that would fix the problem

The copy button should either not have a grey background but a transparent one, or the code example should have more vertical padding so the code is not behind the copy button. Decreasing the copy button size is not really an option, because the touch target becomes too small.

### Add a screenshot if that helps illustrate the problem

<img width="2292" alt="image" src="https://github.com/angular/angular/assets/12891645/5029c529-b347-42f7-97b9-cbd5e86782e1">

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Device: Macbook Pro 2019 (Intel)
OS: MacOS Sonoma 14.3.1
Browser: Google Chrome 122.0.6261.94
```

**Comment by danieljancar** [comment]
Maybe we should only display the copy button in the code boxes when hovering inside of them?

**Comment by JoepKockelkorn** [comment]
Hmm, then the user doesn't know when he does not hover.

**Comment by danieljancar** [comment]
You're right, for mobile devices this might be useless and would need to be solved otherwise to also fix this issue. But personally I'd prefer the hiding of the copy button on computer and desktop screens to clean up the documentation contents a bit. 🙈
