### ISSUE TITLE
Angular 13 to 14 migration issue running widgets

### ISSUE THREAD

**Issue by genaro-pinson-gh** [angular/angular#54725]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Our child angular applications are run as **widget** on top of a parent angular application and the widgets are mostly built on **Angular 14** while our parent angular application is built on Angular 6.1.0. 

Our child angular widgets are dynamically added/removed on the page with the following lines of code appended/removed to the html:

```
   <div class="calc"><app-root-widget>loading ....</app-root-widget></div>

    <script src="http://localhost:4200/assets/scripts/widget.js" defer=""></script>
    <script src="http://localhost:4200/runtime.js?build=1709600028" type="module"></script>
    <script src="http://localhost:4200/polyfills.js?build=1709600028" type="module"></script>
    <script src="http://localhost:4200/styles.js?build=1709600028" type="module"></script>
    <script src="http://localhost:4200/scripts.js?build=1709600028" defer=""></script>
    <script src="http://localhost:4200/vendor.js?build=1709600028" type="module"></script>
    <script src="http://localhost:4200/main.js?build=1709600028" type="module"></script>  
```

We've decided to update the parent angular application starting from version 6, 7, 8  up to version 13 and so far everything still works and our **dynamically added widgets render successfully.** 

Then we hit an issue with our **widget failing to render updating the parent application from Angular 13 to 14**. We've already tried many things and our widget still seems to fail to render on top of an Angular 14 application.

Can someone please help advice what we need to do or check in order for our child angular widget/application to successfully run on top of an Angular 14 application. The weird thing is that there's no errors being thrown and our widget just fail to render which successfully renders up to Angular 13! 

Thanks in advance!

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by genaro-pinson-gh** [comment]
Thanks for the speedy advice anyway.
