### ISSUE TITLE
Using Self-Closing Tags on root-element (app-root) breaks SSR

### ISSUE THREAD

**Issue by endlacer** [angular/angular#54720]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I am using Angular 17.1 with "@angular/ssr": "17.1.1"
I switched to self closing tags on the root-element (eg <app-root/>) and it broke angular SSR hydration for some reason.
I saw no error. Hydration just did not work. The server rendered the content correctly, but client angular did not take over apparently.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.1
Node: 18.18.2
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 17.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by JeanMeche** [comment]
Hi, thank you for reporting this issue. It has been reported in #52922, lets continue the discussion over there.
