### ISSUE TITLE
The sentence on the document confuses me

### ISSUE THREAD

**Issue by Captain-Tom-CL** [angular/angular#54742]
### Describe the problem that you experienced

![image](https://github.com/angular/angular/assets/54521529/1b32cc07-389c-4808-ac61-7265edd79d4f)
i think here is not javascript but typescript which makes sence.

### Enter the URL of the topic with the problem

https://angular.io/docs#assumptions

**Comment by JeanMeche** [comment]
Hi, angular.io is in maintenance mode, please refer to the new doc site https://angular.dev.
