### ISSUE TITLE
@Input({ required: true }) - Required inputs do not throw errors at build time

### ISSUE THREAD

**Issue by ddamiankowalski** [angular/angular#54747]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

The application uses nx and @angular/core version 16.2.12, I am trying to use new features introduced in Angular version 16, specifically required inputs. When I try to do so, the component gets highlighted in my IDE with the message as I hover saying:

```
Missing binding for required input (name of input) of component (name of component)
```

Hovewer, the build is still successfull, and the application compiles successfully.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: v16.2.12
Node: v18.12.1
```

**Comment by JoostK** [comment]
Required inputs are only checked when using the AOT compiler, and only if `strictTemplates` or at least `fullTemplateTypeCheck` is enabled.

**Comment by JoostK** [comment]
Can you confirm this is the case for you as well? If not, this would require a reproduction.

**Comment by ddamiankowalski** [comment]
This is a case for me. I am very much sorry and thank you for the prompt reply. Switching the `strictTemplates` option to true absolutely solves my problem.
