### ISSUE TITLE
Doc is contradictory about :host vs @HostBinding and @HostListener

### ISSUE THREAD

**Issue by massi08** [angular/angular#54762]
### Describe the problem that you experienced

Hello,

On https://angular.dev doc there is a confusion about what is encouraged to use :host or @HostBinding and @HostListener.
The style guides encourages to use @HostBinding and @HostListener while the specific doc about @HostBinding and @HostListener discourages their usage and states 

> Always prefer using the host property over @HostBinding and @HostListener. These decorators exist exclusively for backwards compatibility.

https://angular.dev/guide/components/host-elements#the-hostbinding-and-hostlistener-decorators

Screenshot:

<img width="746" alt="Screenshot 2024-03-08 at 11 48 01" src="https://github.com/angular/angular/assets/17096495/3a370056-f085-4645-abbe-56597777cd6f">

https://angular.dev/style-guide#hostlistener-hostbinding-decorators-versus-host-metadata

Screenshot:

<img width="1792" alt="Screenshot 2024-03-08 at 11 50 06" src="https://github.com/angular/angular/assets/17096495/84ecea8d-91ef-401a-92f8-90cb9559ba8d">

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/host-elements#the-hostbinding-and-hostlistener-decorators

### Describe what you were looking for in the documentation

Clear guidelines on what to use when it comes to host bindings

### Describe the actions that led you to experience the problem

Looking for guidelines on what's best to use

### Describe what you want to experience that would fix the problem

A clear guideline on usage

**Comment by JeanMeche** [comment]
Hi, thank you for reporting this issue. We intend to update the style guide for the next major version (v18) to make the recommendations more consistant. To answer your question, the recommendation will go toward what adev states : use the `host` property.

Upcomming style guide updates is tracked by https://github.com/angular/angular/issues/54284.

**Comment by massi08** [comment]
Thank you
