### ISSUE TITLE
Action request is not sent using action attribute [Form]

### ISSUE THREAD

**Issue by herau** [angular/angular#5476]
Closed issue #5320 still reproductible (2.0.0-alpha.46)

[Code sample](http://plnkr.co/edit/F3w0nmIVLrD29KWrX4SM?p=preview)

**Comment by VPusher** [comment]
Still reproducible with Angular 2.0.0-beta.1. Any workaround ?

**Comment by VPusher** [comment]
Here is an updated [plunker](http://plnkr.co/edit/TLGzrCN7ICPYzSLGc96O?p=preview) showing the issue.

**Comment by herau** [comment]
it's work with an `ngNoForm ` attribute on the form:

```
<form ngNoForm action="https://www.google.com" target="_blank" method="POST">
  <input name="q" value="test">
  <button type="submit">Search</button>
</form>
```
