### ISSUE TITLE
CLI sub commands are not listed correctly in adev

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#54768]
### Describe the problem that you experienced

Sub commands of the Angular CLI are not listed in adev

Example

|ADEV|AIO|
|------------------------------	|-------------	|
| https://angular.dev/cli/generate | https://angular.io/cli/generate|
|https://angular.dev/cli/cache | https://angular.io/cli/cache|
|https://angular.dev/cli/analytics |  https://angular.io/cli/cache|

**Comment by alan-agius4** [comment]
Note: whilst https://github.com/angular/dev-infra/pull/1831 did try to fix listing the sub-commands, as the sub-commands options are not displayed (On the left hand side). 

//cc @JeanMeche

**Comment by alan-agius4** [comment]
Couple of other things related to sub-commands:

- the sub-command aliases are not being displayed
- Sub-commands snippet is not correct. Ex: https://angular.io/cli/generate#component and https://ng-dev-previews-fw--pr-angular-angular-54794-adev-prev-lnuocgx4.web.app/cli/generate#module

<img width="762" alt="Screenshot 2024-03-12 at 17 27 40" src="https://github.com/angular/angular/assets/17563226/c06590e9-0da8-4ca9-bb83-0406768f49a3">

<img width="865" alt="Screenshot 2024-03-12 at 17 27 47" src="https://github.com/angular/angular/assets/17563226/72ebdb30-3c45-46c9-a9b8-631de4897590">

**Comment by JeanMeche** [comment]
Started working of it with angular/dev-infra#1945
