### ISSUE TITLE
Input property not set when decorator on the setter is used

### ISSUE THREAD

**Issue by hristokostov** [angular/angular#5477]
Input property is not set when the `@Input` annotation on the setter is used and both the getter and setter are present. If only the setter is available - everything is OK. Also, it works if we use the `inputs` property of the `@Component` annotation.

The plunk: http://plnkr.co/edit/rNmLP20hcxDi0jpve5Mh

**Comment by pkozlowski-opensource** [comment]
Hmm, an interesting one. It also works if you define getter _after_ a setter: http://plnkr.co/edit/MBKMCpYWFxRgHbbwWYnx?p=preview

**Comment by pmowrer** [comment]
Thanks for the workaround, @pkozlowski-opensource!

**Comment by vicb** [comment]
already fixed
