### ISSUE TITLE
Broken Link on Angular.IO

### ISSUE THREAD

**Issue by m-henderson** [angular/angular#54787]
### Describe the problem that you experienced

Clicking the link to Node.js is showing 404
![image](https://github.com/angular/angular/assets/16070192/66d1f799-5cc1-4476-ae79-7fb4995dd8d1)

Navigates to: 
![image](https://github.com/angular/angular/assets/16070192/3d253fe2-4298-41b6-bfea-a998a48ef87d)

### Enter the URL of the topic with the problem

https://angular.io/guide/setup-local#install-the-angular-cli

### Describe the actions that led you to experience the problem

1. Navigate to https://angular.io/guide/setup-local#install-the-angular-cli
2. Click on "active LTS or maintenance LTS" node link
3. 404 not found

### Describe what you want to experience that would fix the problem

Could be an issue with Nodes site/servers being down but clicking the link should present me with node.js install options. 

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Microsoft Edge Version 122.0.2365.66 (Official build) (64-bit)
```

**Comment by JoostK** [comment]
This should arguably be reported with the Node site maintainers, as the URL was changed to be locale-aware (it's now https://nodejs.org/en/about/previous-releases) and this change has caused all incoming links to the old URLs to break.

**Comment by twerske** [comment]
Fixed by https://github.com/angular/angular/pull/54793
