### ISSUE TITLE
Getting started tutorial does not seem to work 

### ISSUE THREAD

**Issue by ojas-kaushal** [angular/angular#54786]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

I was following online tutorials of Getting Started in Angular. 
with stackblitz, 
The point where it asks to create a new comment product-alerts
it starts through errors, 
that it's a standalone component and it can not be added in the declaration. 
I checked with bard and it mentioned that in angular 14 they had some updates regarding the standalone. 
However their tutorials are perhaps still following the order techniques. 

Could not complete the tutorials, because of these errors. 
infact the routs part don't work either, anymore. 
I would request the angular team to try the getting stated with the stackblitz themself and see if their tutorial or stackblitz build needs an upgrade. 

### Please provide a link to a minimal reproduction of the bug

it's actually in stackblitz

### Please provide the exception or error you saw

```true
https://angular.io/start

Please provide the steps to reproduce the issue
Open the stackblitz starter for https://angular.io/start
right-click the app-folder and select Angular generator -> Component.
Enter the component name (for example product-alerts
Add ProductAlertComponent to the declarations in app.module (this step is actually missing in the tutorial page)
The app should not work anymore
Remove the new declaration, the error should persist
```

**Comment by JeanMeche** [comment]
Hi, Angular.io is in maintenance mode. We recommend you have a look at the new doc site which also has updated tutorials: https://angular.dev
