### ISSUE TITLE
document.createElement('canvas') fails out of the box

### ISSUE THREAD

**Issue by toddhd** [angular/angular#54785]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Angular CLI: 17.0.5
Node: 20.10.0
Package Manager: npm 10.5.0
OS: win32 x64

ng new test

Select SCSS for CSS
Select Yes for SSR

cd test

Edit app.component.ts to match this:

import { Component, AfterViewInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent implements AfterViewInit {
  title = 'test';

  ngAfterViewInit(): void {
    const canvas = document.createElement('canvas');
  }
}

Save the project

from the command line, run the app:

ng s --o

ERROR ReferenceError: document is not defined

### Please provide the exception or error you saw

```true
ERROR ReferenceError: document is not defined
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.5
Node: 20.10.0
Package Manager: npm 10.5.0
OS: win32 x64
```

### Anything else?

I've tried importing Document, @Injecting Document, tried making a "phony" Document.

The really weird thing is, even though the error occurs, I CAN STILL USE THE DOCUMENT. For example, in my app, I continue on getting the context from the document, and then creating a composite image from it. It works. But the darn error keeps popping up. Is it me, or Angular?

**Comment by jnizet** [comment]
It's you.
You've chosen to enable SSR. That means that your code is executed on the server, whee there is no `document`, and then executed in the browser (where there is a `document`).
See https://angular.io/guide/ssr#authoring-server-compatible-components

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).

**Comment by toddhd** [comment]
Ok thank you. I was not aware of the repercussions of using SSR.
