### ISSUE TITLE
Change interpolation characters in the @component decorator

### ISSUE THREAD

**Issue by kyroluskamal** [angular/angular#54789]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

When I changed interpolation characters in the @component decorator, it works fine.

<img width="417" alt="image" src="https://github.com/angular/angular/assets/37916625/b0459e50-5295-42e9-abac-466466e214c9">![image](https://github.com/angular/angular/assets/37916625/87c6b0ab-ad38-4b90-9211-8c3a81ed21d8)

This means that I can use {{}} freely without any errors, however, it show the following error
<img width="383" alt="image" src="https://github.com/angular/angular/assets/37916625/81a79668-66ae-4996-a9d5-7375a389904b">
![image](https://github.com/angular/angular/assets/37916625/8a5d10f9-d826-4d75-beb1-60a67ecff40f)

even if I tried to use one { only,
![image](https://github.com/angular/angular/assets/37916625/040cd8dc-323c-4047-b659-42ff7e70e771)
<img width="394" alt="image" src="https://github.com/angular/angular/assets/37916625/43f5bbd4-478d-4982-9f9b-18c1379f1aa0">

### Please provide the exception or error you saw

```true
Application bundle generation failed. [0.054 seconds]
X [ERROR] NG5002: Invalid ICU message. Missing '}'. [plugin angular-compiler]

    src/app/app.component.ts:10:24:
      10 │               <h1>{</h1>`,
         ╵                         ^


X [ERROR] NG5002: Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.) [plugin angular-compiler]

    src/app/app.component.ts:10:24:
      10 │               <h1>{</h1>`,
         ╵                         ^
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.3
Node: 20.10.0
Package Manager: npm 10.2.5
OS: win32 x64

Angular: 17.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.3
@angular-devkit/build-angular   17.1.3
@angular-devkit/core            17.1.3
@angular-devkit/schematics      17.1.3
@schematics/angular             17.1.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JoostK** [comment]
ICUs are not interpolations, so their syntax remains unchanged when setting the interpolation pattern. AFAICS it's not currently possible to disable ICU parsing.

**Comment by kyroluskamal** [comment]
OK. But changing interporlation characters, with avoiding to use curly braces is useless.

**Comment by JeanMeche** [comment]
The feature will deprecated by #55778
