### ISSUE TITLE
Blocks @defer breaks Server Side Rendering and Static Site Generation

### ISSUE THREAD

**Issue by lemito** [angular/angular#54797]
### Which @angular/* package(s) are the source of the bug?

core, platform-server

### Is this a regression?

Yes

### Description

I tried creating different components and came across one interesting feature (or maybe it's just that I didn't understand how defer works) and couldn't find any mention of it anywhere: defer blocks "kill" SSG and SSR. 

For example, here are two templates of the same component, working under absolutely identical conditions with one exception: the first one uses @defer, the second one does not. 

If you open Chrome DevTools, the Network tab and look at the document content, it will appear unrendered, despite the fact that all content is static and can be rendered. If you comment (or delete) two lines of code, the buttons appear in index.html on the test server, and they load much faster. 

### Please provide a link to a minimal reproduction of the bug

https://gist.github.com/lemito/d5c40f6cb458ee30d62a199810aa4a19

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.2.3
Node: 20.11.1
Package Manager: yarn 4.0.2
OS: linux x64

Angular: 17.3.0-rc.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                          Version
----------------------------------------------------------
@angular-devkit/architect        0.1702.3
@angular-devkit/build-angular    17.2.3
@angular-devkit/core             17.2.3
@angular-devkit/schematics       17.2.3
@angular/cdk                     17.2.2
@angular/cli                     17.2.3
@angular/fire                    17.0.1
@angular/material                17.2.2
@angular/material-experimental   17.2.2
@angular/ssr                     17.2.3
@schematics/angular              17.2.3
rxjs                             7.8.1
typescript                       5.4.2
zone.js                          0.14.4
```

### Anything else?

It may not be a bug at all 🫠 
But then please specify it in the documentation, that you should not use defer and SSR/SSG together, you should choose one strategy

**Comment by JeanMeche** [comment]
Hi, this is explicitly being stated in [the docs](https://angular.dev/guide/defer#behavior-with-server-side-rendering-ssr-and-static-site-generation-ssg): 

> When rendering an application on the server (either using SSR or SSG), defer blocks always render their @placeholder (or nothing if a placeholder is not specified). Triggers are ignored on the server.


Note, this particular feature (rendering `@defer` blocks on the server)  is being investigated for the next major version.

**Comment by lemito** [comment]
> Hi, this is explicitly being stated in [the docs](https://angular.dev/guide/defer#behavior-with-server-side-rendering-ssr-and-static-site-generation-ssg):
> 
> > When rendering an application on the server (either using SSR or SSG), defer blocks always render their @Placeholder (or nothing if a placeholder is not specified). Triggers are ignored on the server.
> 
Hi. Thanks for the documentation, I've read the documentation several times, but only now I realized what this paragraph is about :)

So, do I understand correctly that this is normal behavior for @defer or will this be fine-tuned in future versions? 
> Note, this particular feature (rendering `@defer` blocks on the server) is being investigated for the next major version.

Then what is the correct way to proceed for the examples? What should the @placeholder be filled with or @defer is inappropriate in this case?

**Comment by JeanMeche** [comment]
This behavior is normal and expected with the implementation of the defer block we have in v17. 

The gist you shared twice the same blocks, maybe if you update it I can give you a complete answer for your issue.

**Comment by lemito** [comment]
> The gist you shared twice the same blocks, maybe if you update it I can give you a complete answer for your issue.
Oops... Sorry, I didn't realize.
Pieces of code fixed.

**Comment by JeanMeche** [comment]
As the docs say, SSR/SSG will only render the `@placeholder` block in v17.

If you need SSG/SSR to render that block you will need to drop the `@defer` until this is supported.

**Comment by lemito** [comment]
Hmmm... Okay, well, thanks for your help.

**Comment by JeanMeche** [comment]
Closing as work as intented for the moment.
