### ISSUE TITLE
allow disabled formgroup at initialization

### ISSUE THREAD

**Issue by alex36077** [angular/angular#54790]
### Description

Currently to disable a formgroup. You first initialize it and then call form.disable().

### Proposed solution

It would be interesting to move the disabled property to the AbstractControlOptions interface to allow for example to disable a formgroup at initialization.

### Alternatives considered

No alternatives

**Comment by geromegrignon** [comment]
I would be happy to contribute if/when this request is accepted.

**Comment by JeanMeche** [comment]
I'm not sure we'd like to widden the API surface for this. What you are looking is already achievable via the `FormBuild` that accepts a `FormControlState`.
