### ISSUE TITLE
@alan-agius4 For the supported versions, is the mentioned issue fixed because they have mentioned that all versions above 1.3.0 would have this issue. If that's the case updating the version wouldn't help us.

### ISSUE THREAD

**Issue by joelrichardvitrana** [angular/angular#54809]
@alan-agius4 For the supported versions, is the mentioned issue fixed because they have mentioned that all versions above 1.3.0 would have this issue. If that's the case updating the version wouldn't help us.

![image](https://github.com/angular/angular/assets/131009370/e3b6fa2d-d7d3-484e-a3da-417dc41b555d)

![image](https://github.com/angular/angular/assets/131009370/31a831bf-f0a3-4c0a-a01d-5eb57e6d3a39)

_Originally posted by @joelrichardvitrana in https://github.com/angular/angular/issues/54807#issuecomment-1988208706_

**Comment by JoostK** [comment]
This is concerning angular.js, not Angular. angular.js is not supported anymore.
