### ISSUE TITLE
use createComponent and ApplicationRef.attachView, the primary router outlet will to be replaced if the dynamically created component contains router-outlet

### ISSUE THREAD

**Issue by why520crazy** [angular/angular#54806]
### Which @angular/* package(s) are the source of the bug?

core, router

### Is this a regression?

Yes

### Description

In a router component, using `createComponent` to dynamically create a component, after creation, use `applicationRef.attachView` attach to applicationRef, if the dynamically created component contains `router-outlet`, the current router component will be rendered in dynamically created components, It seems that the primary router-outlet has been replaced.

```ts
  
@Component({
  selector: 'app-with-router-outlet',
  standalone: true,
  imports: [RouterOutlet],
  template: '<p>with-router-outlet</p> <router-outlet />',
})
export class WithRouterOutletComponent {}

@Component({
  selector: 'app-dashboard',
  standalone: true,
  template: `
    <button (click)="useCreateComponent()">Create component contains router-outlet use createComponent</button>

    <div class="container" #container>
      Container:
    </div>
  `,
})
export class Dashboard {
  applicationRef = inject(ApplicationRef);

  container = viewChild<ElementRef>('container');

  componentRef!: ComponentRef<WithRouterOutletComponent>;

  useCreateComponent() {
    this.componentRef = createComponent(WithRouterOutletComponent, {
      environmentInjector: this.applicationRef.injector,
    });
    this.applicationRef.attachView(this.componentRef.hostView);
    (this.container()?.nativeElement as HTMLElement).appendChild(
      (this.componentRef.hostView as EmbeddedViewRef<any>)
        .rootNodes[0] as HTMLElement
    );
  }

  ngOnDestroy() {
    if (this.componentRef) {
      this.applicationRef.detachView(this.componentRef.hostView);
      this.componentRef.destroy();
    }
  }
}
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/ng-create-component-with-outer-outlet

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.4
Node: 18.18.0
Package Manager: npm 9.8.1
OS: darwin arm64

Angular: 15.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.4
@angular-devkit/build-angular   15.2.4
@angular-devkit/core            15.2.4
@angular-devkit/schematics      15.2.4
@angular/cdk                    15.2.2
@angular/cli                    15.2.4
@angular/material               15.1.2
@schematics/angular             15.2.4
ng-packagr                      15.1.1
rxjs                            6.6.7
typescript                      4.9.5
webpack                         5.76.1
```

### Anything else?

1. It is ok using `viewContainerRef.createComponent`
2. This issue appearing in version 16. x, it's ok in 15.x

**Comment by JeanMeche** [comment]
Hi, is there a reason you're adding `createComponent` + `applicationRef.attachView` instead of `viewContainerRef.createComponent`. Because there is no issue in the latter.

**Comment by why520crazy** [comment]
> Hi, is there a reason you're using `createComponent` + `applicationRef.attachView` instead of `viewContainerRef.createComponent`. Because there is no issue in the latter. 

Yes

**Comment by JeanMeche** [comment]
What would be the particular usecase your are looking to address with this?

**Comment by atscott** [comment]
Closing as expected. This is effectively the same thing as having two router outlets.

**Comment by alxhub** [comment]
Note that as @atscott mentions, this _is_ effectively replacing the primary router outlet, as it's created as a root-level outlet.

To create it as a child outlet of the root outlet instead, you would need to create the new component as a DI child of the parent `RouterOutlet`. This is done by passing `elementInjector` as well as `environmentInjector` when calling `createComponent`.

**Comment by why520crazy** [comment]
@alxhub @atscott @JeanMeche thank you very much for providing the solution.
1. Firstly, the current expectation is for version 16.0 to appear, in 15.x it don't replacing the primary router outlet 
2. We are using `createComponent` + `applicationRef.attachView` when using a micro front-end for cross application rendering, App1 renders component of another application (App2), App1 can only obtain the applicationRef of App2, If `elementInjector` can be passed, then simply use `viewContainerRef. createComponent` instead of the global `createComponent`
3. If this is a expected behavior, are there other alternative solutions besides passing `elementInjector`

**Comment by atscott** [comment]
> Firstly, the current expectation is for version 16.0 to appear, in 15.x it don't replace the primary router outlet, it looks like a breaking change.

Your example seems to have the same behavior in 15: https://stackblitz.com/edit/angular-3eqbcp

> App1 renders component of another application (App2), App1 can only obtain the applicationRef of App2

This seems a bit sketchy. Why is this the case and why aren't the `ApplicationRef` instances the same? Regardless, I'm not really following why App1 cannot create the App2 component and always pass the `elementRef` so that the `ElementRef` hierarchy is preserved for `RouterOutlet`. This is required to avoid same-name collisions of outlets. 

> If this is a expected behavior, are there other alternative solutions besides passing elementInjector.

There should be other workarounds. For example, preventing App2 from rendering another outlet with the same name.

**Comment by why520crazy** [comment]
> Your example seems to have the same behavior in 15: https://stackblitz.com/edit/angular-3eqbcp
Sorry for my mistake, i only test it use NgModule in 15 : https://stackblitz.com/edit/angular-3tn8ws,  I didn't expect that standalone component application would be inconsistent with NgModule app.

> This seems a bit sketchy. Why is this the case and why aren't the ApplicationRef instances the same? Regardless, I'm not really following why App1 cannot create the App2 component and always pass the elementRef so that the ElementRef hierarchy is preserved for RouterOutlet. This is required to avoid same-name collisions of outlets.
App1 and App2 are different angular application, they all have independent AppModule and router. I found that the cause of this problem is due to using the example of `@worktile/planet`, I open http://planet.ngnice.com/app1/projects after the page, when navigate to App2 again, a blank page appears:
<img width="1000" alt="image" src="https://github.com/angular/angular/assets/3959960/a20cd1bc-de1c-4ea0-b386-16a2562d4208">

because the `/app1/projects` page renders a component of App2, and the component template of App2  includes a router-outlet.


> There should be other workarounds. For example, preventing App2 from rendering another outlet with the same name.
I think this is a good idea
