### ISSUE TITLE
angular accidentally calls a method in the project's two-party library

### ISSUE THREAD

**Issue by tmx-502** [angular/angular#54804]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

My project is angular15, using two-party library for angular13, because using npm i --legacy-peer-deps installation, so in node_modules two-party library shared the parent project angular15 dependencies, The setDisabledState method in the two-party library was accidentally called when the project was running, causing an internal error in my two-party library that the image could not be served due to network problems. After I changed the name of the setDisabledState method in the two-party library code, the program returned to normal. I suspect that there is a problem with angular's code isolation. Is it because my two-party library is referencing a dependency in @angular/core that calls an external setDisabledState method? Because I see a lot of setDisabledState calls in angular15.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.2.10
Node: 20.11.0 (Unsupported)
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 15.2.10
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.10
@angular-devkit/build-angular   15.2.10
@angular-devkit/core            15.2.10
@angular-devkit/schematics      15.2.10
@angular/cdk                    15.2.9
@schematics/angular             15.2.10
rxjs                            6.6.7
typescript                      4.9.5
```

### Anything else?

3

**Comment by alxhub** [comment]
I don't think we'll be able to investigate this issue unless you're able to provide a minimal reproduction of the problem, unfortunately.

**Comment by alxhub** [comment]
Closing as no reproduction was provided.
