### ISSUE TITLE
DynamicComponentLoader: Ability to load components w/ same context as hostLocation elementRef

### ISSUE THREAD

**Issue by adamdbradley** [angular/angular#5481]
Both `loadNextToLocation` and `loadIntoLocation` allow you to pass providers that the newly created component will use, which works great.

However, it'd also be useful if you could specify that the newly created component uses the same context as the hostLocation elementRef, which the new component is going next to. Possibly an additinional arg in these methods?

With this functionality we'd be able to automatically generate a modal/dialog service, and when the user creates a new modal it could use the same context as the user's root component.

cc @IgorMinar @tbosch

**Comment by naomiblack** [comment]
This will be covered as part of the compiler rewrite that @tbosch has in progress.

**Comment by drew-moore** [comment]
@naomiblack is there a design doc for that rewrite floating around somewhere I can look at?

**Comment by marinhomoreira** [comment]
Any news on this issue/compiler rewriting?

**Comment by v7r7** [comment]
Hey this issue is really important to the success of my organization.  I would really appreciate attention was spent addressing this.  Thank you so much I really appreciate all the work this community does.

**Comment by pkozlowski-opensource** [comment]
I believe that this one is solved with new APIs replacing DCL. @adamdbradley is this still an issue for you?

**Comment by adamdbradley** [comment]
Yes this is solved now. Thanks!

**Comment by discodane** [comment]
When I debug into the navController.present function I'm still seeing 
`if (rootNav['_tabs']) {
            // TODO: must have until this goes in
            // https://github.com/angular/angular/issues/5481
        void 0;
        return;
    }`

Do I need to update the release or is this still going on specifically for projects with the "tabs" feature
