### ISSUE TITLE
How to working with files in Angular 2

### ISSUE THREAD

**Issue by EgyTechnology** [angular/angular#5482]
Hi guys.
I'm working in project that's support Angular 2 and I want to upload images directly to API.
How could I use Angular to do similar job ?
I tried using [(ng-model)] with input type file. and I get path look like ```C:/fakepath/imagename.png```.

**Comment by sturdynut** [comment]
This is a duplicate from angular 1.*: https://github.com/angular/angular.js/issues/1375

The resolution is that the functionality is not core to angular.  You'd be better off building a directive to achieve what you'd like, there are plenty of examples in the issue referenced above.
