### ISSUE TITLE
zone.js throws TypeError when passing AbortController as options to addEventListener

### ISSUE THREAD

**Issue by zzmp** [angular/angular#54831]
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

No

### Description

`window.addEventListener` takes an options argument, which can be shaped as `{ signal: AbortSignal }`. `AbortController` satisfies this interface, and can be passed to `addEventListener` in the native implementation:

    window.addEventListener('keydown', () => {}, new AbortController)

However, `zone.js` is clever with passing the `signal`, and un-assigns and re-assigns it to `taskData.options` avoid passing it internally. `taskData.options` is initialized to the original options argument, so it is initialized to an instance of `AbortController`, for which `signal` is a getter. This results in a `TypeError`. Instead, for this to work in `zone.js`, you need to destructure:

    window.addEventListener('keydown', () => {}, { signal: (new AbortController).signal })

`zone.js` should not be using the original options argument (to save memory) _and_ assigning to it, as it is of an unknown type and the options properties may not be writable.

### Please provide a link to a minimal reproduction of the bug

N/A - see explanation for one-liners

### Please provide the exception or error you saw

```true
TypeError: Cannot set property signal of [object AbortController] which has only a getter
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
zone.js: 0.14.4
Google Chrome: 122.0.6261.94 (Official Build) (arm64)
```

**Comment by JeanMeche** [comment]
Hi, thank you for reporting this issue, this is already being tracked at #54142.
