### ISSUE TITLE
Router deactivate failure results in page reload in computed mode

### ISSUE THREAD

**Issue by joeldhenry** [angular/angular#54835]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

with routerModule as default, a deactivate failure, would still remove the history state causing issues with back button and swipe back on mobile. 

as per instructions, i changed to `RouterModule.forRoot(AppRoutes, { canceledNavigationResolution: 'computed' })`
which results in history being reset on deactivate failure, however the page also refreshes causing form data and state to be reset. my understanding is that default deferred update strategy and sameURLNavigation 'ignore' should have caused the route to not be reloaded, however this is not the case.

### Please provide the exception or error you saw

```true
routerModule as default:

Route Page 1 -> Page 2
Route Page 2 -> Page 3
Back & deactivate Failure = history state Page 2

canceledNavigationResolution 'computed':

Route Page 1 -> Page 2
Route Page 2 -> Page 3
Back & deactivate Failure = history state Page 3, but refresh page 3
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.6
Node: 18.18.0
Package Manager: npm 9.8.1
OS: darwin arm64

Angular: 16.1.7
... animations, common, compiler-cli, core, language-service
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.6
@angular-devkit/build-angular   16.1.6
@angular-devkit/core            16.1.6
@angular-devkit/schematics      16.1.6
@angular/cli                    16.1.6
@schematics/angular             16.1.6
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```

**Comment by atscott** [comment]
> my understanding is that default deferred update strategy and sameURLNavigation 'ignore' should have caused the route to not be reloaded, however this is not the case.

not quite in this case because the URL _is_ changing so the route is processed. This now depends on what you’re doing with the `RouteReuseStrategy`. Can you provide a reproduction?

**Comment by yashnsharma** [comment]
I am facing simililar issue with my application after using `canceledNavigationResolution: 'computed'` Flag. 

The application has two routes, one route displays a reactive form other route embeds an iframe.
When the user lands on the iframe route and uses the browser back button to navigate back, Instead of navigating the application just reloads on the same page. Basically after that the user is stuck.

Also this issue was not observed while developing on localhost, It was observed when It's hosted behind our testing domain which uses nginx as a load balancer.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
