### ISSUE TITLE
NG5002: Allow referencing of expression results in `@else if` block (control flow)

### ISSUE THREAD

**Issue by danielkleebinder** [angular/angular#54833]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

The new Angular control flow has been a great addition to the ecosystem so far. However, the `@else if` block does not allow referencing of expression results thus far. This is a minor bump in the road of Angular DX. An example of correct referencing is listed below:

```typescript
@if (animals$ | async; as animals) {
  {{ animals.length }}
} @else if (pets$ | async) {
  {{ (pets$ | async).length }}
}
```

The easier to read and maintain version, however, is currently not supported / allowed:

```typescript
@if (animals$ | async; as animals) {
  {{ animals.length }}
} @else if (pets$ | async; as pets) {
  {{ pets.length }}
}
```

This template would yield the following error:

```bash
X [ERROR] NG5002: "as" expression is only allowed on the primary @if block [plugin angular-compiler]

    src/app/list/list.component.html:3:27:
      3 │ } @else if (pets$ | async; as pets) {
        ╵                            ~~~~~~~
```

Not allowing this construct might force developers in creating _creative_ workarounds, such as:

```typescript
@if (animals$ | async; as animals) {
  {{ animals.length }}
} @else{
  @if (pets$ | async; as pets) {
    {{ pets.length }}
  }
}
```

Which is semantically equivalent, but less maintainable and extensible than other solutions.

### Proposed solution

Allow referencing of expression results in `@else if` blocks:

```typescript
@if (animals$ | async; as animals) {
  {{ animals.length }}
} @else if (pets$ | async; as pets) {
  {{ pets.length }}
}
```

### Alternatives considered

Add syntax that allows developers to reference the results of multiple expressions or the creation of view models:

```typescript
@viewModel (animals$ | async as animals; pets$ | async as pets) {
  @if (animals) {
    {{ animals.length }}
  } @else if (pets) {
    {{ pets.length }}
  }
}
```

This approach, however, increases cognitive complexity and is counteracting the lazy evaluation of `@else if` blocks.

**Comment by JeanMeche** [comment]
Hi, this issue has been discussed a few month back in #52103.

**Comment by danielkleebinder** [comment]
@JeanMeche Thank you very much for your quick response. I am sorry for the duplication!
