### ISSUE TITLE
@Input and @Output syntax is not consistent

### ISSUE THREAD

**Issue by rkj** [angular/angular#5487]
In the dart file having this:
```@Input('foo-value') fooValue;```
does work and I can use it like:
```<my-cmp [foo-value]="foo">```
but this:
```@Output('foo-event') fooEvent;```
does not work, it must be:
```@Output('fooEvent') fooEvent;```

I would love if both annotations would handle the html casing as it makes much easier to copy paste properties/events from component code into html.

**Comment by vicb** [comment]
This should be fixed when we fix #4923

**Comment by vicb** [comment]
closed by #5765
