### ISSUE TITLE
Working with Normal routes and child routes together

### ISSUE THREAD

**Issue by sagarora77** [angular/angular#54871]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

Is there a way in which we can work with normal routes and child routes in a hybrid way?

### Proposed solution

I am expecting if some part of the application supports normal routes and other part of application supports outlet routes or secondary routes.

### Alternatives considered

Need some approach to work with both types of routes seemlessly.

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
