### ISSUE TITLE
FormControl.markAsTouched does not work with OnPush Change Detection

### ISSUE THREAD

**Issue by SebastianPost1996** [angular/angular#54873]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

Calling `markAsTouched()` will not trigger change detection in implementations of `ControlValueAccessor` that have change detection set to `OnPush`.

For example when wanting to display an error tooltip:

```html
<mat-form-field
  [matTooltip]="errorMessage"
  [matTooltipDisabled]="ngControl.untouched"   <-- will not update
...
```

Where ngControl is injected via OnInit:

```ts
public ngOnInit(): void {
  this.ngControl = this.injector.get(NgControl, null);
}
```

This is because currently [markAsTouched is just setting a variable](https://github.com/angular/angular/blob/main/packages/forms/src/model/abstract_model.ts#L799), so the component is not marked for check.

My proposed solution would be for the current form state api (touched, untouched, pristine, ...) to use Signals internally.

**Comment by italosll** [comment]
I also have been experiencing the same problem, and been unable to use onPush strategy in components where i need to use the form touched property consistently. 

I agree with the proposed solution by @SebastianPost1996  and only complement with the line where the touched variable is declared: [https://github.com/angular/angular/blob/main/packages/forms/src/model/abstract_model.ts#L630](url).

**Comment by JeanMeche** [comment]
There a global issue when with Forms and the `OnPush` strategy, let's have a centralised discussion about this in #44295.
