### ISSUE TITLE
adev is broken on Firefox after xtermjs is loaded and table of contents item clicked

### ISSUE THREAD

**Issue by lukasmatta** [angular/angular#54894]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

How to reproduce:
1. Go to https://angular.dev using Firefox
2. Go to page that loads `xtermjs` (either https://angular.dev/playground or scroll down on the landing page)
3. Go to Docs -> click on any item in the "On this page" section on the right
4. Left sidebar is not visible anymore.

Repro video:
https://drive.google.com/file/d/12GHRIDE3GidLv_kASuid0cA0I9euEu2v/view

`xtermjs` seems to be inserting absolutely positioned elements that affect viewport width in Firefox.

![image](https://github.com/angular/angular/assets/4323927/788685da-b06a-4255-9c95-e433198b74c9)

Related to https://github.com/xtermjs/xterm.js/issues/4805

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Firefox 123.0.1 on macOs 14.3.1
```

**Comment by JeanMeche** [comment]
Hi, we appreciate you took the time to investigate the issue.
#54897 will land the fix.
