### ISSUE TITLE
`withComponentInputBinding()` for route resolves

### ISSUE THREAD

**Issue by tijsmoree** [angular/angular#54909]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

I don't know if this fits in the Angular philosophy, but maybe it would be nice to make the route resolves available over the `input` signals like the parameters are when adding `withComponentInputBinding()` to the router config.

### Proposed solution

Make the resolves available in the `input` signals with `withComponentInputBinding()` enabled as well as the data it already does. Then a resolve named `foo` could be acquired as:
```
readonly foo = input.required<Foo>();
```

### Alternatives considered

Right now I created a separate utility function:
```
export const resolve = <T>(key: string) =>
  signal<T>(inject(ActivatedRoute).snapshot.data[key]);
```
It can be used to achieve the same thing:
```
readonly foo = resolve<Foo>('foo');
```

**Comment by eneajaho** [comment]
Hi,
In `ngxtension` library we already have a function for this [injectRouteData](https://ngxtension.netlify.app/utilities/injectors/inject-route-data/)

We also include: 
- injectParams
- injectQueryParams

Thought it may interest you.

**Comment by atscott** [comment]
I’m a bit confused here because data from resolvers is already bound to routed components when this feature is enabled. Can you provide a reproduction?

**Comment by alxhub** [comment]
Yep, this should work out of the box with `withComponentInputBinding()`.

**Comment by tijsmoree** [comment]
Whoops! I made an error during testing. The feature I described above already works like I wanted it to.
