### ISSUE TITLE
Signals nullability checks horribly broken

### ISSUE THREAD

**Issue by TimUnderhay** [angular/angular#54906]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I'm writing this to flag https://github.com/angular/angular/issues/49161 for an Angular team response -- what the author describes as "not a big deal" but I and evidently many others think should be regarded as fairly major.  The fact that signal value unwrapping is function-based breaks Typescript's nullability checking in a fairly major way, especially in templates.  This leads to either duplicate nullability checks, use of !'s to quell the compiler, or people switching off null checks altogether.

It's a very poor developer experience.

That issue has been open for more than a year with no response I can find from the Angular team.  Some engagement would be greatly appreciated.

PLEASE, PLEASE!

### Plagiarised original issue:

The current implementation of signals uses a function to access the value, and TypeScript has issues with type guards in that case:

```
const count = signal(null as null | number);
const total: number = count() !== null ? count() : 0;
// Error: Type `number | null` is not assignable to type `number`
```
This can be workaround by storing the value in a temporary variable or with an explicit cast, but this could be a bit cumbersome, as I imagine the same would happen with ngIf in templates:

```
const count = signal(null as null | number);
const value = count();
const total: number = value !== null ? value : 0;
// Works
```

### My own additional colour
```typescript
someSignal = signal<number | undefined>(undefined);
ngOnInit() {
  this.someSignal.set(1)
}
```

```html
@if (someSignal() !== undefined) {
  {{someSignal() + 1}}
}
<!-- Object is possibly 'undefined' -->
```

```html
@if (someSignal(); as someSignal) {
  @if (someSignal !== undefined) {
    {{someSignal + 1}}
  }
}
<!-- Works, but this is a horrible developer experience -->
```

```html
@if (someSignal()) {
  {{someSignal()! + 1}}
}
<!-- Techincally works, but makes nullability checking useless -->
```

### Anything else?

This entire issue would be moot were Signals to use getters rather than functions to unwrap the inner value.  Please see the discussion on #49161

**Comment by JeanMeche** [comment]
The team is fully aware of this issue and actively investigating solutions to improve DX. 
We'll continue tracking this issue and provide updates in the original isssue.

**Comment by TimUnderhay** [comment]
@JeanMeche can one expect some kind of response there in the near future?  More than a year of silence is a long time

**Comment by JeanMeche** [comment]
@TimUnderhay You'll find answer in the mentionned issue 👍

**Comment by TimUnderhay** [comment]
@JeanMeche thank you!
