### ISSUE TITLE
JavaScript Proxy construct trap stopped to work since version 15

### ISSUE THREAD

**Issue by danielk997** [angular/angular#54915]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I was using JavaScript Proxy to add some functionality to component via decorator:
```typescript
function proxyDecorator(target: any) {
    return new Proxy(target, {
        construct(target: any, argArray: any[], newTarget: Function): object {
            console.log(`proxy constructor`);
            return Reflect.construct(target, argArray, newTarget);
        }
    });
}

@proxyDecorator
@Component({
    selector: 'app-root',
// rest of component
```

The problem is it stopped to work since version 15. To reproduce the issue I created sample app via @angular/cli@14.0.0 and @angular/cli@15.0.0. You can see the result below:

![image](https://github.com/angular/angular/assets/91020875/d1d3d638-3d4e-48b3-8bfe-793dfc43ab36)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.0
Node: 18.13.0
Package Manager: npm 8.19.3
OS: Windows 11

Angular: 15.2.10
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, router
```

**Comment by JoostK** [comment]
Please see https://github.com/angular/angular/issues/53156#issuecomment-1826329117

**Comment by JoostK** [comment]
Without a reproduction I can't tell for sure (I don't have insight into e.g. your tsconfig), but the above is likely the culprit. Reverting to es2021 may be your best course of action.
