### ISSUE TITLE
Animation not initialized when using ZonelessChangeDetection

### ISSUE THREAD

**Issue by keatkeat87** [angular/angular#54919]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

No

### Description

a simple reproduction 

app.config.ts
```
export const appConfig: ApplicationConfig = {
  providers: [provideAnimationsAsync(), ɵprovideZonelessChangeDetection()]
};
```

app.component.ts
```
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  animations: [
    trigger('highlight', [
      state('false', style({ 'background-color': 'red', color: 'white' })),
    ])
  ]
})
export class AppComponent {
  highlight = signal(false);
}
```

app.component.html
`<h1 [@highlight]="highlight()">Hello World</h1>`

results:
if no apply ɵprovideZonelessChangeDetection()
![image](https://github.com/angular/angular/assets/8691013/66059f3d-e8ec-4bcb-a520-b06cab8ad80d)
if apply ɵprovideZonelessChangeDetection()
![image](https://github.com/angular/angular/assets/8691013/21962849-c69a-4e43-a3a0-af5e745156e8)

### Please provide a link to a minimal reproduction of the bug

https://github.com/keatkeat87/zoneless-animation-issue

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.0
Node: 20.11.1
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 17.3.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.0
@angular-devkit/build-angular   17.3.0
@angular-devkit/core            17.3.0
@angular-devkit/schematics      17.3.0
@schematics/angular             17.3.0
rxjs                            7.8.1
typescript                      5.4.2
zone.js                         0.14.4
```

**Comment by atscott** [comment]
Async animations currently relies on the import promise being detected by ZoneJS and triggering another round of change detection.
