### ISSUE TITLE
HttpRequest.clone forgets transferCache

### ISSUE THREAD

**Issue by cclausen** [angular/angular#54924]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

When cloning the HttpRequest, like keycloak does in it's interceptor, the clone-method forgets the transferCache-property.
```
req.transferCache = true;
this.keycloak.addTokenToHeader(req.headers).pipe(mergeMap(headersWithBearer => {
      const kcReq = req.clone({
        headers: headersWithBearer
      });
      return next.handle(kcReq);
    }));
req.transferCache === true;
kcReq.transferCache === undefined;
```

The HttpRequest-constructor expects the transferCache to be set in the options-parameter, but the clone-method does not provide it.

This code should fix the problem.

`
const transferCache = update.transferCache || this.transferCache ;

    // Finally, construct the new HttpRequest using the pieces from above.
    return new HttpRequest(method, url, body, {
      params,
      headers,
      context,
      reportProgress,
      responseType,
      withCredentials,
     transferCache ,
    });`

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.0
Node: 20.9.0
Package Manager: npm 10.1.0
OS: win32 x64

Angular: 17.3.0
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.0
@angular-devkit/build-angular   17.3.0
@angular-devkit/core            17.3.0
@angular-devkit/schematics      17.3.0
@schematics/angular             17.3.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

**Comment by sunilbaba** [comment]
Hi All,
I want to give a try on this one.

**Comment by lazybobcat** [comment]
> Hi All, I want to give a try on this one.

Tell me if you need any help with this :)

**Comment by mlz11** [comment]
Hello 👋🏻 

I have opened PR https://github.com/angular/angular/pull/54939 that should fix the issue 🙂

Thanks for your help reviewing it !
