### ISSUE TITLE
toSignal does not unsubscribe when combined with shareReplay

### ISSUE THREAD

**Issue by IceBjerg** [angular/angular#54927]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Recently I have found a strange error when using the built-in `toSignal` function from the `@angular/core/rxjs-interop` package. 

Everything works as expected unless the source observable has an additional `shareReplay` operator.

When `shareReplay` is used, the signal stays subscribed to the observable, even after the component is destroyed.  

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-16-starter-3ew8m4

### Please provide the exception or error you saw

```true
When I use the `tap` operator on the source observable + `shareReplay` operator, I will still see the console logs even after the component is destroyed (if the observable is emitting new values).
```

### Anything else?

When inspecting the provided stackblitz page, please open the console and look for logs. Once the toggle button is pressed, the component should be destroyed, and the logs should no longer appear. However, if the `shareReplay` operator is present, the logs continue to appear.

**Comment by poczepeter** [comment]
same issue

**Comment by kbrilla** [comment]
https://rxjs.dev/api/index/function/shareReplay#reference-counting

> By default [shareReplay](https://rxjs.dev/api/index/function/shareReplay) will use refCount of false, meaning that it will not unsubscribe the source when the reference counter drops to zero,


Setting `refCount: false` solves the problem

https://stackblitz.com/edit/angular-16-starter-5wonlb?file=src%2Fsub.component.ts

**Comment by kbrilla** [comment]
This is default behawior of `shareReplay` operator. 
[Documentation](https://rxjs.dev/api/index/function/shareReplay#reference-counting) mention:

> By default [shareReplay](https://rxjs.dev/api/index/function/shareReplay) will use refCount of false, meaning that it will not unsubscribe the source when the reference counter drops to zero, i.e. the inner [ReplaySubject](https://rxjs.dev/api/index/class/ReplaySubject) will not be unsubscribed (and potentially run for ever). This is the default as it is expected that [shareReplay](https://rxjs.dev/api/index/function/shareReplay) is often used to keep around expensive to setup observables which we want to keep running instead of having to do the expensive setup again.

Using `shareReplay({ refCount: true, bufferSize: 1 })` solves the issue

https://stackblitz.com/edit/angular-16-starter-5wonlb?file=src%2Fsub.component.ts

**Comment by IceBjerg** [comment]
Thanks! 

I did not know that!
