### ISSUE TITLE
HTTP Guide don't have a security page

### ISSUE THREAD

**Issue by vladboisa** [angular/angular#54922]
### Describe the problem that you experienced

When switching to the [HTTP CLient's guides](https://angular.dev/guide/http), there is no page to switch for the Security tab, but in the existing code base [structure](https://github.com/angular/angular/blob/f50afb10c37f19133053e2ea56c9b404e15916be/adev/src/content/guide/http/security.md)  Markdown for the tab is presence, which results in an Issue #54918 

### Enter the URL of the topic with the problem

https://angular.dev/guide/http

**Comment by bencodezen** [comment]
This should be resolved now!
