### ISSUE TITLE
Docs: missing closing tag in logical structure of the template

### ISSUE THREAD

**Issue by smoothjjuu** [angular/angular#54938]
### Describe the problem that you experienced

There are missing closing tags on the last code example. 
https://angular.dev/guide/di/hierarchical-dependency-injection#logical-structure-of-the-template

it should be:
<code-example format="html" language="html">
&lt;app-root&gt;
  &lt;#VIEW&gt;
    &lt;app-child&gt;
    &lt;#VIEW&gt;
      &hellip;content goes here&hellip;
    &lt;/#VIEW&gt;
    &lt;/app-child&gt;
  &lt;/#VIEW&gt;
&lt;/app-root&gt;
</code-example>

And I wanted to push my PR but it seems that I don't have permission to the project. Could you help me to how to contribute as well?

**Comment by nickjfrench** [comment]
@smoothjjuu are you forking the project then creating a PR that way?

**Comment by allanbees** [comment]
@smoothjjuu have you checked the [contributing guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md)?

**Comment by smoothjjuu** [comment]
Thank you all :) I missed signing [Contributor License Agreement (CLA)](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#cla) before sending PRs

**Comment by mlz11** [comment]
Should the issue be closed as https://github.com/angular/angular/pull/54954 was merged ?
