### ISSUE TITLE
ngModel example does not work in Windows 10 Edge

### ISSUE THREAD

**Issue by varghesep** [angular/angular#5494]
The [ngModel](https://angular.io/docs/js/latest/api/core/NgModel-directive.html) [Plunker Example](http://plnkr.co/edit/R3UX5qDaUqFO2VYR0UzH?p=preview) does not work in Windows 10 Edge browser.

**Comment by ericmartinezr** [comment]
It does if you add `systemjs-polyfills`

```
  <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.33.13/es6-shim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.18.4/system-polyfills.js"></script>
  <script src="https://code.angularjs.org/tools/system.js"></script>
  <script src="https://code.angularjs.org/tools/typescript.js"></script>
```

See https://github.com/angular/angular/issues/5426

**Comment by tenowg** [comment]
that issue was redirected too https://github.com/angular/code.angularjs.org/issues/30, and the pull request has been made to include system-polyfills in angular code cdn

pull request: https://github.com/angular/code.angularjs.org/pull/31

as a side note, es6-shim may not be required for Edge

**Comment by pkozlowski-opensource** [comment]
Sounds like a support / docs request that was resolved already. Closing.
