### ISSUE TITLE
Missing `tbody` in HTML thows a hydration missmatch error. 

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular#54943]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When a template has a table without a `tbody` node, browsers adds them dynamincally. 

This throws a hydration missmatch error. 

The workaround is obvious : adding the `tbody` after the `table` node. 

* Should we produce a template warning here ? 
* There are probably other cases where browsers dynamically change the dom when loading the HTML. Should have a more global approach on this. 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/fork/github/JeanMeche/ssr-hydration-demo/tree/tbody?template=node

### Please provide the environment you discovered this bug in (run `ng version`)

```true
v17.
```

**Comment by alxhub** [comment]
We should likely special-case these things in the hydration code path.

**Comment by JeanMeche** [comment]
Dupe of #56392
