### ISSUE TITLE
Images not loading for angular tutorial

### ISSUE THREAD

**Issue by cadoud** [angular/angular#54955]
### Describe the problem that you experienced

Assets for angular v17 tutorial including housing list not loading photos when using HousingLocationList provided in tutorial.

### Enter the URL of the topic with the problem

'https://angular.dev/assets/tutorials/common/assets/bernard-hermant-CLKGGwIBTaY-unsplash.jpg'

### Describe what you were looking for in the documentation

A photo

### Describe the actions that led you to experience the problem

No photo

### Describe what you want to experience that would fix the problem

Show a photo

**Comment by JeanMeche** [comment]
Hi, thank you for reporting this issue. We're already tracking it in issue #52666
