### ISSUE TITLE
Directive with 2way binding?

### ISSUE THREAD

**Issue by panKt** [angular/angular#5495]
I'm trying to create reusable **text-input** component for our set of forms. So right now I'm able to show data from model in that **text-input** component, but I can't make it have 2 way binding to change **model.name** whenever I type

![Screencast](http://i.piccy.info/i9/174a0ef95ec702e3f6d5f1af67cb69ab/1448579402/33752/975631/model_not_been_updated.gif)

Here is how I did it (plunker here http://plnkr.co/edit/HVXUUfuWEmJqDK7QYKCq?p=preview ):

**Form component**
```
import { Component, OnInit, CORE_DIRECTIVES, FORM_DIRECTIVES } from 'angular2/angular2'
import { TextInput                                           } from '../../widgets/form/text-input'

@Component({
  selector   : 'form-edit',
  directives : [CORE_DIRECTIVES, FORM_DIRECTIVES, TextInput],
  template   : `
    {{model | json}}
    <form class='form-horizontal'>
    <fieldset>
      <text-input id='name' label='Name' [(value)]='model.name' required></text-input>
    </fieldset>
    </form>
  `
})
export class FormEditComponent {
  public model = { id: 10, name: 'ABC' }
}
```

**text-input**
```
import { Component, View, Input, CORE_DIRECTIVES } from 'angular2/angular2'

@Component ({ selector   : 'text-input' })
@View      ({ directives : [CORE_DIRECTIVES],
              template   : `
              <label class='col-sm-1 control-label' [attr.for]='id'>{{label}}</label>
              <input id           = '{{id}}'
                     name         = '{{id}}'
                     [(ng-model)] = 'value'
              /> `
})
export class TextInput {
  @Input() id    : string
  @Input() label : string
  @Input() value : string
}
```

**Comment by robwormald** [comment]
Your `text-input` component needs to notify the outside world the value has changed. See http://plnkr.co/edit/GGdD95tDQY3PzVFsoyRa?p=preview for a working implementation.

**Comment by robwormald** [comment]
Also, as of .46 you no longer need to manually include CORE_DIRECTIVES and FORM_DIRECTIVES - they are included automatically :+1:

**Comment by panKt** [comment]
@robwormald That's awesome, thanks :+1:  :)
