### ISSUE TITLE
routerLinkActive doesn´t set the active class correctly

### ISSUE THREAD

**Issue by MeMeMax** [angular/angular#54978]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I use the router to have different layouts applied to different sections of my app. Therefore I have e.g. a route "with-frame" and children below it like this:

```
const routes: Routes = [
  {
    path: 'with-frame',
    component: LayoutComponent,
    children: [
      { path: '', redirectTo: 'container-queries/dashboard', pathMatch: 'full' },
      { path: 'container-queries/dashboard', component: DashboardComponent },
      { path: 'css-grid/dashboard', component: DashboardCssGridComponent }
    ]
  }
];
```

With this construct multiple routes are marked as active (as you can see in my demo repo).

For reproduction:
- Get the demo repo
- Execute npm i
- Execute npm start

### Please provide a link to a minimal reproduction of the bug

https://github.com/MeMeMax/router-link-active-bug

### Please provide the exception or error you saw

```true
No exception. Just wrong behaviour as seen in the reproduction demo. When initially opening the app multiple routes are marked as active in the top navigation. When I click around, they disappear as I visit every route once.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.0
```

**Comment by atscott** [comment]
You have `active` class on your elements already. The `RouterLinkActive` does not remove classes if there was no change to its active state. Since it starts as inactive and remains inactive, it doesn't attempt to remove the 'active' class: https://github.com/MeMeMax/router-link-active-bug/blob/main/apps/responsive-layout-in-frame/src/app/core/components/navbar/navbar.component.html#L6

Closing as expected.

**Comment by MeMeMax** [comment]
Oh shoot, that was dumb. Sorry for wasting your time 🤦🏻‍♂️

**Comment by atscott** [comment]
@MeMeMax no worries. It took me a bit to figure out as well. Even though this is technically "working as expected" I still created a PR to update the behavior such that the classes will be removed.
