### ISSUE TITLE
ControlGroup.controls returns AbstractControl

### ISSUE THREAD

**Issue by basvandenheuvel** [angular/angular#5497]
I'm currently working with ControlGroup and Control.
When i get a Control within my ControlGroup like this `this.patientForm.controls["id"]` i get an AbstractControl. The problem with this is that i can't use the `updateValue` method on an AbstractControl since this is a method of the Control class.

Because of this i get an error within my IDE. Compiling and running the code anyway, does work. Since at runtime it actually receives a Control and not an AbstractControl.

**Comment by Krustie101** [comment]
The controls map can contain Control instances, (nested) ControlGroup instances and ControlArray instances so the typescript compiler / ide cannot know which type you will get back when you ask an instance by key. In your case, you can add a cast to Control, using <Control>.
Of course, the name 'controls' is a bit misleading in this setting.
