### ISSUE TITLE
Showcasing a counter as a signal example in playground

### ISSUE THREAD

**Issue by gokulrajdevarajan** [angular/angular#54990]
### Describe the problem that you experienced

In angular playground, signal example could have been more simple like showcasing a counter.

### Enter the URL of the topic with the problem

https://angular.dev/playground

### Describe what you were looking for in the documentation

I want to learn about angular signals. I looked for simple example.

### Describe the actions that led you to experience the problem

Simple example might be helpful.

### Describe what you want to experience that would fix the problem

A simple counter-example would be sufficient.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/104135617/2d33e19d-fbd0-43d8-8d6d-94bbe471624b)

**Comment by bencodezen** [comment]
Seconded on the sentiments that @jnizet expressed regarding playground which is meant for more exploratory coding.

That said, we'll work on making sure the tutorial for signals will be beginner friendly. Thanks for the issue @gokulrajdevarajan!
