### ISSUE TITLE
Whats the reason behind the frequent snapshot releases?

### ISSUE THREAD

**Issue by sclausen** [angular/angular#5499]
Almost three weeks ago, @yjbanov started with frequently releasing angular2 snapshots.
My question is: Whats the reason behind this?
With my **limited perception**, I find this annoying, because you can't see directyl in github what's the current alpha-release. Its not a severe problem, because you can still view it in package.json, or look at npmjs.com, but what's the reason behind flooding the repo with tags/releases?

**Comment by brandonroberts** [comment]
See https://github.com/angular/angular/issues/4671. This is part of an effort to get the latest builds available quicker, but it isn't fully complete yet.

**Comment by sclausen** [comment]
Ah, thanks for the info! :smile:
