### ISSUE TITLE
Try out Inject page not found

### ISSUE THREAD

**Issue by sergiopd** [angular/angular#54994]
### Describe the problem that you experienced

From the page [Angular Roadmap](https://angular.dev/roadmap) in the section [[Explore modern Angular](https://angular.dev/roadmap#explore-modern-angular)], if you click "Try out inject" the link https://angular.dev/tutorials/learn-angular/inject-based-di has a Page not found message

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/inject-based-di

### Describe what you were looking for in the documentation

Update the knowledge from Angular 15 to Angular 17

### Describe the actions that led you to experience the problem

Click the link "Try out inject"

### Describe what you want to experience that would fix the problem

Found the info about inject

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/9003985/03ba9b0b-e1db-4fa7-b90b-8787c74b3e26)

**Comment by bencodezen** [comment]
Closed by https://github.com/angular/angular/pull/54997
