### ISSUE TITLE
docs(rxjs-interop): toSignal injection context

### ISSUE THREAD

**Issue by ApplY3D** [angular/angular#54995]
### Describe the problem that you experienced

The rxjs-interop documentation does not specify whether toSignal should be called within an injection context.

https://github.com/angular/angular/issues/50947#issuecomment-1621756214

**Comment by ApplY3D** [comment]
https://github.com/angular/angular/pull/54996

**Comment by twerske** [comment]
Closed by https://github.com/angular/angular/pull/54996
