### ISSUE TITLE
Wrong url in app creation

### ISSUE THREAD

**Issue by Aharonyan-Narek** [angular/angular#55009]
### Describe the problem that you experienced

in our tutorial: https://angular.dev/tutorials/first-app/07-dynamic-template-values, 
we have this code
`readonly baseUrl = 'https://angular.dev/assets/tutorials/common';`
this URL is wrong, the full code is
export class HomeComponent {
  readonly baseUrl = 'https://angular.dev/assets/tutorials/common';

  housingLocation: HousingLocation = {
    id: 9999,
    name: 'Test Home',
    city: 'Test city',
    state: 'ST',
    photo: `${this.baseUrl}/example-house.jpg`,
    availableUnits: 99,
    wifi: true,
    laundry: false,
  };
}

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app/07-dynamic-template-values

**Comment by JeanMeche** [comment]
Hi, believe you're talking the issue with the images not loading. 
We're already tracking it in issue  #52666
