### ISSUE TITLE
Component not completely recreated when using canReuse

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#5500]
I might be misunderstanding the purpose of canReuse, but I am noticing that my component is not recreated from scratch when navigating back to it by route. The radio button retains its value when returning. It was my impression that canReuse with a return value of false would recreate the entire component - DOM and all....?

```
Template
<input #male name="gender" type="radio" value="Male" (click)="gender = male.value" />

TypeScript
canReuse(next: ComponentInstruction, prev: ComponentInstruction) { return false; }
```

Code:https://github.com/thelgevold/angular-2-samples/blob/master/demo-page.ts
Demo: http://www.syntaxsuccess.com/angular-2-samples/#/demo/input

Steps to reproduce 
1) Select a gender
2) Navigate away to a different component
3) Navigate back and observe that the selected gender from step 1) is retained despite canReuse returning false

**Comment by btford** [comment]
There was a bug with this that was recently fixed; can you try with Alpha 47?

**Comment by thelgevold** [comment]
I have upgraded the listed samples to 47, but it appears to still be an issue after the upgrade.

**Comment by btford** [comment]
`routerCanReuse` should be on the component itself (in this case the `InputControls` component), not on the parent.

**Comment by thelgevold** [comment]
Ok, it definitely makes more sense to add it to the component itself.
However, after making that change I still see the same behavior. I noticed that there is a canReuse example in the Angular source, but it's not the same scenario since the canReuse method returns true. 
I guess it could be just a problem with my implementation, but from what I can tell it looks correct after I made the change you suggested.

**Comment by btford** [comment]
Your implementation looks correct.

Hm, this only happens with the radio button. I'm seeing the rest of the state reset– try doing the same with the input box, for instance. And actually, when you navigate back, I see `Selected gender is (blank)`.

I'm guessing this is just goofy browser behavior, or some side-effect of reusing DOM for `<input type="radio">`.

@vsavkin @tbosch – have you seen this before with radio buttons?

**Comment by thelgevold** [comment]
Looks like the checkboxes also retain their state when navigating back.

**Comment by btford** [comment]
Looks like this is similar to #5188.

**Comment by varadero** [comment]
@btford The problem exists for checkbox, text field, select element - actually everything that is input not bound to component controller.

Plunker demonstrating checkbox, text field and select (from #6148).

From the console it is also visible, that "routerCanReuse" is called only if the user clicks on the router link while he is already on that route but not when he goes away from it. Anyway, returning false does not "vanish" the cache for that template.

http://plnkr.co/edit/bOVcoful8zS3lz6KHcrg?p=preview

**Comment by tbosch** [comment]
The reason for this is Angular's viewpool. With #5993 this will go away,
i.e. all DOM nodes will be recreated properly then.

**Comment by ericmartinezr** [comment]
@tbosch 
>With #5993 this will go away, i.e. all DOM nodes will be recreated properly then.

May ask if that means that the DOM will always be recreated? Will there be some way to cache the view? I think using APP_VIEW_POOL_CAPACITY is a good idea, letting the user to choose if his component's DOM can be reused or not. Or will the refactor remove completely the necessity for the user to handle it?

**Comment by thelgevold** [comment]
Thanks, guys!
This has been fixed in beta 1.
Confirmed that selections are no longer retained here: 
http://www.syntaxsuccess.com/angular-2-samples/#/demo/input

**Comment by VladimirAmiorkov** [comment]
I have upgraded to RC2 and `canReuse` is not longer working. Has anyone found a way to disable the reuse of the Component with the latest RC2 or RC3?
