### ISSUE TITLE
After upgrading to v17 unable to see imported components

### ISSUE THREAD

**Issue by Synectron** [angular/angular#55000]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

Yes

### Description

I upgraded my project to v17 but now all the imported components are not loading. I even did standalone false to all components, and also tried doing standalone true and imported all necessary components but to no avail. This was working in v16.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.0
Node: 18.15.0
Package Manager: npm 9.6.7
OS: win32 x64

Angular:17.3.0
... animations, cli, common, compiler, compiler-cli, core, form
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker

Package                     Version
------------------------------------------------------
@angular-devkit/architect    0.1703.0 
@angular-devkit/core         17.3.0 
@angular-devkit/schematics   17.3.0  
@schematics/angular          17.3.0 
@angular-devkit/build-angular17.3.0
ng-packagr                   17.3.0
rxjs                         7.8.1
typescript                   5.4.2
zone.js                      0.14.4
```

**Comment by JoostK** [comment]
Without a runnable reproduction this won't be actionable, unfortunately.

**Comment by JeanMeche** [comment]
Hi, without feedback from you we'll close this issue. 
If you have a reproduction of this issue, feel free to open a new issue.
