### ISSUE TITLE
Number inputs with a dynamic type always return strings

### ISSUE THREAD

**Issue by jeffrey-thompson-fdx** [angular/angular#55002]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

With a form control, if you have an `<input type=number>` with an attached formControl, when the input is changed from user interaction, the type of the value that's given is a number.  However, if the input type is dynamically set (`<input [type]="dynamicInputType" />`), the value accessor that would normally apply doesn't apply, even if `dynamicInputType` is 'number', whether changed later or the initial value.  This means that values returned from this control are strings instead of numbers.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-bf5qsf?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.13
Node: 16.20.0
Package Manager: npm 8.19.4 
OS: linux x64

Angular: 14.3.0
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
... upgrade

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.13
@angular-devkit/build-angular   14.2.13
@angular-devkit/core            14.2.13
@angular-devkit/schematics      14.2.13
@angular/cdk                    14.2.7
@angular/cli                    14.2.13
@schematics/angular             14.2.13
rxjs                            7.8.1
typescript                      4.8.4
webpack                         5.81.0

This was replicated in Angular 17 using the stackblitz demo setup.
```

**Comment by JoostK** [comment]
This is a limitation of value accessors, which are determined statically. This is being tracked in #13243.
