### ISSUE TITLE
i can see the web of animation api's of angular.

### ISSUE THREAD

**Issue by JehielL** [angular/angular#55005]
### Describe the problem that you experienced

i can see the web of animation api's of angular.

### Enter the URL of the topic with the problem

https://angular.dev/api/animations

### Describe what you were looking for in the documentation

![Captura de pantalla 2024-03-23 003901](https://github.com/angular/angular/assets/122569500/fe60c0c1-00f7-4b9d-a6fa-4e81ac9f928d)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
edge.
```

**Comment by JeanMeche** [comment]
Hi, thank you for reporting this issue. We're already tracking it with #52663. (None of the packages has a direct entry yet)
