### ISSUE TITLE
NG0952: Input is required but no value is available yet.

### ISSUE THREAD

**Issue by sysmat** [angular/angular#55010]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

NG0952 Input is required but no value is available yet.

### Please provide the exception or error you saw

```true
export class UserComponent {
user = input.required<User>();
expired = signal<Date>(this.user()? this.user().expired: null);

changeExpired(){
  this.expired.set(new Date());
}
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.1
Node: 20.11.1
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.3.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.1
@angular-devkit/build-angular   17.3.1
@angular-devkit/core            17.3.1
@angular-devkit/schematics      17.3.1
@schematics/angular             17.3.1
rxjs                            7.8.1
typescript                      5.4.3
zone.js                         0.14.4
```

### Anything else?

if I try effect then I can not use `this.expired.set`

**Comment by JeanMeche** [comment]
Hi, required inputs can only be read after the component is init (after `ngOnInit()`).  By invoking `user` in the property initialization you're accessing a signal that hasn't been set yet. 

In your case it looks like `expired` should be a computed input.

**Comment by sysmat** [comment]
- this is very bad, con not use declarative programming
- computed signal dos not have `set` or `update` function

**Comment by JeanMeche** [comment]
Nested Signals (like `DeepSignal` from the [signal Store](https://ngrx.io/guide/signals/signal-store)) might me a good fit for you.
