### ISSUE TITLE
Photos are not available

### ISSUE THREAD

**Issue by moelleking** [angular/angular#55024]
### Describe the problem that you experienced

If I do the Angular Tutorial and come to the point of implement the Photos with an Array, the pictures are not visible and the URL to the source of the pictures became an issue.

### Enter the URL of the topic with the problem

https://angular.dev/assets/tutorials/common

**Comment by sonukapoor** [comment]
Somehow the page doesn't work for me. I am seeing a Page not found.

**Comment by JeanMeche** [comment]
Hi, thank you for reporting this issue. We're already tracking it in issue #52666
