### ISSUE TITLE
Bug: Child Routers on Root Components with path '/' must throw pushstate error

### ISSUE THREAD

**Issue by Batch1211** [angular/angular#5502]
If you have your RootRouter in your app.ts configured like this, where the path '/' redirects to a child router:
<pre>
<code>
@RouteConfig([
  {path: '/...', loader: () => System.import('./components/index/index').then(m => m.IndexComponent), as: 'Index'}
])
</code>
</pre>
and your Child Component (in this case the IndexComponent) configured like this:
<pre>
<code>
@RouteConfig([
  {path: '/', loader: () => System.import('./components/home/index').then(m => m.HomeComponent), as: 'Home'},
  {path: '/listing', loader: () => System.import('./components/listing/index').then(m => m.ListingComponent), as: 'Listing'},
  {path: '/detail', loader: () => System.import('./components/detail/index').then(m => m.DetailComponent), as: 'Detail'}
])
</code>
</pre>
Then your links in the IndexComponent's template 
<pre>
<code>
<a [router-link]="['Home']" class="home">Home</a>
    <a [router-link]="['Listing']" class="listing">Listing</a>
    <a [router-link]="['Detail']" class="detail">Detail</a>
</code>
</pre>
will always throw the following error:
<pre>
<code>
EXCEPTION: SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'http://listing/' cannot be created in a document with origin
</code>
</pre>
This is because of the double slashes in front of the href-link the angular2 router translates the route to:
<pre>
<code>
<a class="listing router-link-active" href="//listing">Listing</a>
</code>
</pre>
Why is it doing that?
In the RootRouter.commit method, it automatically prefixes a slash to the emitPath, because it assumes that the emitPath cannot possible already have an leading '/':
<pre>
<code>
if (emitPath.length > 0) {
      emitPath = '/' + emitPath;
}
</code>
</pre>
However, when the path to the ChildComponent is only '/', this is actually possible.
emitPath is defined as:
<pre>
<code>
var emitPath = stringifyInstructionPath(instruction);
</code>
</pre>
and the stringifyInstructionPath method is defined as:
<pre>
<code>
export function stringifyInstructionPath(instruction: Instruction): string {
  return instruction.component.urlPath + stringifyAux(instruction) +
         stringifyPrimaryPrefixed(instruction.child);
}
</code>
</pre>
where in our use case instruction.component.urlPath is empty, stringifyAux(instruction) is empty and stringifyPrimaryPrefixed has a leading '/'

I propose to fix this bug, by checking in the RootRouter.commit method, whether the emitPath has a leading slash, and only if this is not the case, it adds another one.

**Comment by brandonroberts** [comment]
See if this helps https://github.com/angular/angular/issues/5218

**Comment by oubushixb** [comment]
same question, replace routeConfig '/...' to '/anything/...' it will work

**Comment by matteosuppo** [comment]
I created a repository that can reproduce the bug: https://github.com/matteosuppo/angular2-routing-issue

I tried to create a test case in the angular source but I couldn't make it fail.

**Comment by chrisgreeff** [comment]
+1

**Comment by Batch1211** [comment]
+1 Yes. Can't reproduce it with the current beta either.

**Comment by user414** [comment]
I can still reproduce this in the beta1, but solve it by using @oubushixb suggestion with a redirect
```
  { path: "/", as: "Main", redirectTo: ["/MainScreenApp"], useAsDefault: true},
  { path: "/main/...",      as: "MainScreenApp",      component: MainScreenBootstrapComponent },
```

**Comment by Batch1211** [comment]
I reproduced this bug in this Plunk
http://plnkr.co/edit/OjXZK9

You will not get errors thrown displayed in the console while running in Plunkr so here is the exact same code on our servers
http://test.loop-one.de/

The error still exists
