### ISSUE TITLE
HttpTransferCache should allow caching of requests with auth headers

### ISSUE THREAD

**Issue by tylerstarcher** [angular/angular#55031]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

Previously, we were able to use hydration/http caching with all of our requests from the server to the client. With 17.3.0 (https://github.com/angular/angular/pull/54746) caching was killed for all requests with authorization headers, but with enterprise applications, this is almost always the case. Therefore, hydration does not occur properly and the application behaves poorly. 

### Please provide the environment you discovered this bug in (run `ng version`)

17.3.0

### Anything else?

A solution would be to revert this behavior, or to add a configurable bit to the withHttpTransferCacheOptions config. As is, this prevents myself and likely others from upgrading past 17.2

**Comment by alan-agius4** [comment]
Had a chat with @AndrewKushnir, and we will be reverted the above mentioned change.
