### ISSUE TITLE
Proposal for convention to export PROVIDERS in Angular 2 libraries

### ISSUE THREAD

**Issue by jvandemo** [angular/angular#5503]
As a consumer of third-party Angular 2 libraries it may not be immediately really clear which providers to load after including a library.

#### An example

When installing a third-party library like [ng2-translate](https://github.com/ocombe/ng2-translate):

```bash
$ npm install ng2-translate --save
```
the consumer of the library must know which providers to load without knowing the inner workings of the library:
```javascript
// We must know what to import
import {TranslateService} from 'ng2-translate/ng2-translate';

// and specify the required providers
bootstrap(AppComponent, [
    TranslateService
]);
```
Can we make this easier?

#### Proposal for `PROVIDERS` convention

What if there was a convention for Angular 2 libraries to export a `PROVIDERS` property that includes all providers that need to be loaded by default:

```javascript
// We can simply import PROVIDERS and alias it
import {PROVIDERS as NG2-TRANSLATE-PROVIDERS} from 'ng2-translate/ng2-translate';

// We load the providers the library author specified
bootstrap(AppComponent, [
  NG2-TRANSLATE-PROVIDERS
]);
```
This would help consumers to immediately load all providers without knowing the inner workings of the library.

#### No loss in flexibility

The consumer can still choose to ignore the default `PROVIDERS` export and specify individual providers if needed.

#### Prior art

The Angular team already uses a similar approach in the Angular libraries:

```javascript
import {ROUTER_PROVIDERS} from 'angular2/ROUTER_PROVIDERS';

bootstrap(AppComponent, [
  ROUTER_PROVIDERS
]);
```

#### What's next?

- How do others feel about this?
- Can we add this to an Angular 2 styleguide (if there already is one)?

**Comment by PascalPrecht** [comment]
While I'm always up for making things easier for the consumer, I'm not entirely sure if this proposal is really such a big win.

@jvandemo as you stated, the platform already exposes providers such as `ROUTER_PROVIDERS` and `HTTP_PROVIDERS`. However, you still need to know that those providers exists in order to make your code work. This doesn't really change if all providers are exported as `PROVIDERS`. You would still need to know that `ng2-translate` exports `PROVIDERS` to make use of them.

In some cases, just importing a predefined list of providers isn't even enough. E.g. if you want to use a different location strategy in the router, you need to set up your own provider anyway:

```
bootstrap(App, [
  ROUTER_PROVIDERS,
  provide(LocationStrategy, {useClass: HashLocationStrategy})
]);
```

In this case, again you'd need to know what is exported and what is needed to setup this particular provider.

In addition to that, I'm not sure if this would cause a problem in ES5 land when all providers are exported as `PROVIDERS`. ES2015 modules allow us to import them with an alias, but do we have an equivalent way for this in ES5?

I'd also like to add that we definitely need to figure out some kind of best practices when it comes to things like building libraries. Those can never be enforced but maybe this can be part of a global styleguide that almost everyone agrees with.

**Comment by robwormald** [comment]
Thoughts:
- everybody exporting the same named thing is probably a bad idea.
- libraries might also export directives and pipes 
- typescript autocomplete solves this problem nicely
- ES5 users are going to have to read the docs regardless.
- maybe a ng2-library-seed is a good idea (from the community) - i know @ocombe has worked through these issues.
- definitely needs more consideration and a good design.

@jvandemo definitely agree this needs to be solved, but not sure this covers it quite yet.

**Comment by ocombe** [comment]
I think that you can already do that with:
```js
import * as ng2Translate from 'ng2-translate/ng2-translate';
// --> ng2Translate.TranslateService
```

For the angular2 library seed, that's a good idea, I'll make a repository for that.
And we should definitely work on good practices as well.

**Comment by jvandemo** [comment]
Thank you all for the great feedback.

I think the usefulness of a shorthand property becomes more clear when there are multiple providers exported by a library.

Suppose there is a third-party library called `super-heroes` that exports 7 providers:

- `heroService`
- `heroesService`
- `swordService`
- `knightService`
- `weaponService`
- `gameService`
- `scoreService`

#### Without a shorthand property

```javascript
// We must know what to import
// We could read this from the 3d party library docs
import {heroService, heroesService, swordService, knightService, weaponService, gameService, scoreService} from 'super-heroes/super-heroes';

// and specify the required providers
bootstrap(AppComponent, [
  heroService,
  heroesService,
  swordService,
  knightService,
  weaponService,
  gameService,
  scoreService
]);
```

#### With a shorthand property

```javascript
import {PROVIDERS as SUPER-HERO-PROVIDERS} from 'super-heroes/super-heroes';

bootstrap(AppComponent, [
  SUPER-HERO-PROVIDERS
]);
```

#### Property name `PROVIDERS`

I think the actual name is not relevant, as long as there is a convenient way to grab all providers using one property name. I originally proposed `PROVIDERS` as it is easy, short and self-explanatory but it could be any name that the library author chooses.

The author could choose to export `SUPER-HERO-PROVIDERS` instead of `PROVIDERS`:

```javascript
import {SUPER-HERO-PROVIDERS} from 'super-heroes/super-heroes';

bootstrap(AppComponent, [
  SUPER-HERO-PROVIDERS
]);
```

making the alias obsolete if there is no collision. If there is a collision with another library, we can still alias it.

The important aspect would be that there **is** a shorthand key available, not what it's called.

#### Directives and pipes

A similar convention could be used for directives and pipes. Suppose the `super-hero` library exports 12 directives and 3 pipes, then the library could export `DIRECTIVES` and `PIPES`, to quickly get access to them in a component definition.

#### Easier upgradability

If the library features new services, directives and/or pipes in newer releases, the consumer using the shorthand properties would automatically have access to them without having to update the bootstrap code.

#### Goal

Ultimately the goal is to provide maximum convenience for library consumers.

It would be great if we could establish a *best practice* for library authors to start with, based on the experiences of people that already are working on libraries.

This would make the *interface* of new libraries more consistent, which is a good thing at the start of a whole new ecosystem of Angular 2 libraries.

It is not a good thing if there is an explosion of Angular 2 libraries that are inconsistent to consume as it would indirectly make Angular 2 apps harder to set up and maintain.

Although it may be premature to think about this while Angular is still in *Alpha*, I think this topic is really important for the Angular 2 ecosystem as it will probably start growing exponentially in the next couple of months.

Thanks for all the great input! Really enlightening to hear so many different opinions!

**Comment by Foxandxss** [comment]
Not set in stone yet, but we follow a similar convention on [ng-bootstrap](https://github.com/ui-bootstrap/core). We export a `NGB_DIRECTIVES` and for providers I proposed `NGB_BINDINGS`. Then you can override some strategies (or Engines in our case) as @PascalPrecht said.

So I feel like libraries should export a package when it makes sense. Not sure if it always does, we are in an early stage on this angular 2 community and we need to see how things evolve.

I like the library-seed idea. I have 3 seeds right now and I plan to write two mores for angular 2 (libraries, apps). Perhaps I should run my own workflow organization :P

**Comment by NathanWalker** [comment]
I'm for prepending `PROVIDERS` with the library 'short' name as mentioned by several above however I would stick with underscores as the convention like the framework does:
`SUPER_HERO_PROVIDERS`
`SUPER_HERO_DIRECTIVES`

...etc.

**Comment by jvandemo** [comment]
I have been working on a Yeoman generator to create the boilerplate for an Angular 2 library based on [@Ocombe's article](https://medium.com/@OCombe/how-to-publish-a-library-for-angular-2-on-npm-5f48cdabf435):

https://github.com/jvandemo/generator-angular2-library

I have added support for `PROVIDERS`, `DIRECTIVES` and `PIPES` in a similar way as the Angular team does (using `CONST_EXPR`), for example in: https://github.com/jvandemo/generator-angular2-library/blob/master/generators/app/templates/src/directives.ts

The bundle names can easily be changed by the library author if he/she wishes to prepend them with a prefix.

Thanks for all the great feedback so far!

**Comment by pkozlowski-opensource** [comment]
I think that with introduction of `@NgModule` this is obsolete.
