### ISSUE TITLE
`yarn devtools:build:chrome` failed

### ISSUE THREAD

**Issue by dreampasssser** [angular/angular#55047]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

1. Several days ago, I checked out the latest main branch(SHA: 0461bff) to build a devtools for chrome.
2. I did all the things in [prerequisite-software](https://github.com/angular/angular/blob/main/docs/DEVELOPER.md#prerequisite-software) in `DEVELOPER.md`. And add `C:\msys64\usr\bin` to the `PATH` environment variable(Win11 system).
3. Then I excuted `yarn --frozen-lockfile` in `git-bash`. In order to complete it successfully, I deleted one line(`"sauce-connect": "https://saucelabs.com/downloads/sc-4.9.1-linux.tar.gz",`) in `package.json`. I known it's for test, so I think it's no matter, I just want to build a devtools.
4. Then I changed system to developer mode and excuted `yarn devtools:build:chrome`, and it returned me `BazelWorkspaceStatusAction stable-status.txt failed: Failed to determine workspace status: Process exited with status 1`.

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

It is expected that  I excute `yarn devtools:build:chrome` successfully.

### Please provide a screenshot if possible [Bug Report only]

![image](https://github.com/angular/angular/assets/24749464/8fe649bb-a9f1-44df-8842-eb017c9c0fe3)

### Please provide the exception or error you saw [Bug Report only]

```true
In the screenshot above
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version. [Bug Report only]

```true
no
```

**Comment by AleksanderBodurri** [comment]
Thanks for the report 🙏 Could you run `yarn --frozen-lockfile && yarn bazel clean --expunge` and then try to build DevTools again?

If that still fails try out the --verbose_failures flag to see if the error message surfaces

**Comment by dreampasssser** [comment]
@AleksanderBodurri  

Wow~, it works, but it cannot to be packed into a `devtools-chrome.zip` when I run `(cd dist/bin/devtools/projects/shell-browser/src/prodapp && zip -r ~/devtools-chrome.zip *)`. There is no `devtools-chrome.zip` to be generated. And the screenshot is below:

![屏幕截图 2024-03-30 092548](https://github.com/angular/angular/assets/24749464/5999d978-d38b-40dd-a287-35d6b7aea2b5)

**Comment by JeanMeche** [comment]
zip generation looks fine. Did look in the right directory ? 

Anyway this issue is solved now.

**Comment by dreampasssser** [comment]
@JeanMeche  @AleksanderBodurri 

Oh, I'm so sorry, I did looked in a wrong directory. Thank you!

**Comment by AleksanderBodurri** [comment]
No worries at all 😁
