### ISSUE TITLE
Calling markAllAsTouched() on parent form doesn't mark ControlContainer controls as touched

### ISSUE THREAD

**Issue by eltaro** [angular/angular#55046]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

1. Have a component with ControlContainer that is looking at a FormGroup in the parent form.
2. From the parent component, call form.markAllAsTouched().
3. Use devtools to observe the behavior. In the actual FormGroup object, the controls are correctly marked as touched, however, in the DOM, you will be able to see the controls inside the ControlContainer component aren't touched.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-control-container-subform-markallastouched-bug?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
-
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.2
Node: 18.18.0
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.3.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.2
@angular-devkit/build-angular   17.3.2
@angular-devkit/core            17.3.2
@angular-devkit/schematics      17.3.2
@angular/cli                    17.3.2
@schematics/angular             17.3.2
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

**Comment by JeanMeche** [comment]
You're issue is due to the `OnPush` strategy. CD isn't triggered on your CVA because your component isn't marked dirty in any way.
