### ISSUE TITLE
feat(router): allow components to be null/undefined

### ISSUE THREAD

**Issue by cburgdorf** [angular/angular#5505]
I'm currently working on some kind of contacts app and ran into a use case that I haven't found a satisfying solution for yet. So here is the thing. I have my `AppComponent` that basically only holds a `<router-outlet>` to display other views.

```
┌────────────────────────────────────────┐
│                                        │
│              AppComponent              │
│                                        │
│    <router-outlet></router-outlet>     │
│                                        │
│                                        │
│                                        │
│                                        │
└────────────────────────────────────────┘
```

One of those views is a view that I call `ComposeViewComponent` because it combines a list of contacts and a detail view of a contact. So the contact list is always shown whereas the details view can either be empty (if no contact is loaded) or show the details of a contact from the list.

```
┌────────────────────────────────────────────┐
│                                            │
│           ComposeViewComponent             │
│┌───────────────────┐ ┌───────────────────┐ │
││                   │ │                   │ │
││                   │ │                   │ │
││                   │ │                   │ │
││  <contact-list>   │ │  <router-outlet>  │ │
││  </contact-list>  │ │ </router-outlet>  │ │
││                   │ │                   │ │
││                   │ │                   │ │
││                   │ │                   │ │
││                   │ │                   │ │
│└───────────────────┘ └───────────────────┘ │
└────────────────────────────────────────────┘
```

The template of that `ComposeViewComponent` looks like this:

```html
  <contact-list></contact-list>
  <router-outlet></router-outlet>
```

In my root component I created this route.

```ts
@RouteConfig([
  { path: '/...', component: ComposeViewComponent }
])
```

And in my `ComposeViewComponent` I created the following child routes.

```ts
@RouteConfig([
{ path: '/', component: DummyComponent, name: 'List' },
{ path: '/contact', component: ContactDetailComponent, name: 'Contact' }
])
```

**So what is `DummyComponent` here?**

So, here is the thing. I want to be able to load the `ComposeViewComponent` either with the `<router-outlet>` being filled with the `ContactDetailComponent` or not. It would be filled when we know which contact to display but it would be empty otherwise. When it's empty, my expectation would be that we can still route to the `ComposeViewComponent` but it would only display the list of contacts. For now, the only way that I found to achieve that is to create a `DummyComponent` with an empty template and create a route that uses that `DummyComponent` to fill the `<router-outlet>` with life.

**What do I expect?**

I'd expect that I can create a route that either leaves out the component part or sets it `null`. So in my vision this would work.

```ts
@RouteConfig([
{ path: '/', name: 'List' },
{ path: '/contact', component: ContactDetailComponent, name: 'Contact' }
])
```

Not sure if it makes sense or not. In a real world app we would probably have some sort of "dummy" component that displays a text "Please click on a contact to load it" anyways but I wonder if there's a strong reason that prevents us from showing components which have `<router-outlet>`'s that empty.

I have a plunkr that demonstrates the problem: http://plnkr.co/edit/Xs7x00QQJC3u7TMzeXnV?p=preview

**Comment by cburgdorf** [comment]
So I talked to @brandonroberts about this and it seems this behavior is by design. However, if it's illegal to route to a component that has "unfulfilled" `<router-outlet>`'s I may see this "Dummy Pattern" becoming a thing in Angular 2.

Think about a component that has 5 different <router-outlet>'s which are basically little boxes that can be filled with contextual info blocks (a weather box, upcoming concerts blabla) but for some states only three of those little boxes can be used. In order to still be able to route to this component (with some boxes being just empty nodes) I would have to fill the other <router-outlet>'s with dummy components.

**Comment by brandonroberts** [comment]
@cburgdorf You can also have multiple routes to the same component to avoid having dummy routes http://plnkr.co/edit/Li7Rr9aK03L8B7u3hRS2?p=info

**Comment by cburgdorf** [comment]
Yep, I know. Speaking in abstract terms that means make your leaf components dummy-able so when you have a `<router-outlet>` that is optional you can reuse one of your existing components to act as a dummy. Depending on the case that may be a good thing or may feel like abusing an existing component.

**Comment by brandonroberts** [comment]
@cburgdorf Good point
