### ISSUE TITLE
Dead link leads to 404

### ISSUE THREAD

**Issue by jomaendle** [angular/angular#55058]
### Describe the problem that you experienced

- Coming from here: https://angular.dev/guide/http/setup#withxsrfconfiguration
- Clicking on [security guide](https://angular.dev/guide/http/security)
- Results in "Page not found"
<img width="659" alt="image" src="https://github.com/angular/angular/assets/32535140/9cebd2c8-207a-44e2-bcd6-9372e957ce91">

### Enter the URL of the topic with the problem

https://angular.dev/guide/http/setup#withxsrfconfiguration

### Describe the actions that led you to experience the problem

Clicking the mentioned link

### Describe what you want to experience that would fix the problem

Linking to correct page

### Add a screenshot if that helps illustrate the problem

<img width="659" alt="image" src="https://github.com/angular/angular/assets/32535140/9cebd2c8-207a-44e2-bcd6-9372e957ce91">

**Comment by twerske** [comment]
I believe this is caused by moving the security guide. The new url link should be https://angular.dev/best-practices/security - 

We should find and replace this link more broadly across the repo since we moved the guide!
cc @bencodezen

**Comment by jomaendle** [comment]
Thanks for the fast response and instant fix! 🙏
