### ISSUE TITLE
Version compatibility not updated / does not include recent versions

### ISSUE THREAD

**Issue by ssams** [angular/angular#55063]
### Describe the problem that you experienced

The "Version compatibility" page seems not to be up-to-date, does not contain information about the recent 17.2 and 17.3 releases.

In particular, Typescript 5.4 is listed as _not_ supported, although it seems to be supported (https://github.com/angular/angular/blob/17.3.1/packages/compiler-cli/package.json#L57, and listed in the Changelog for 17.3 via https://github.com/angular/angular/pull/54414) and the CLI update command even automatically installs a 5.4 version at the moment.

### Enter the URL of the topic with the problem

* https://next.angular.io/guide/versions
* https://angular.dev/reference/versions

### Describe what you were looking for in the documentation

Compatible versions of dependencies.

### Describe what you want to experience that would fix the problem

Ideally, that version table would be automatically updated (not sure how it is created at the moment, but I suppose manually update?), so this is always consistent and includes all releases.

**Comment by alxhub** [comment]
Note that angular.io is no longer maintained, but the equivalent angular.dev page (https://angular.dev/reference/versions) has the same issue.

**Comment by ssams** [comment]
> Note that angular.io is no longer maintained [...]

according to the information I could find it still should be? The [announcement](https://blog.angular.io/announcing-angular-dev-1e1205fa3039) stated:

> Angular.io will continue to be supported as a legacy resource for documentation through v17, and to ensure all old links remain functional. In v18, after collecting feedback and continuing to stabilize the site, we plan to make Angular.dev the official home for all Angular development.

-> I'd expect it to right now still be correct, at least regarding recent releases. Even if now things are not actively added anymore, but adding information would be different from not maintaining something at all? Also, angular.dev still says "beta docs" in the title icon, so that's not what I'd expect to be the _primary_ source of information already.

Anyway, as you mentioned, the new page has the same issue, so applies in any case. I can update the description to also reference this.

**Comment by JeanMeche** [comment]
#54882 will fix this. I should be merged soon.
