### ISSUE TITLE
ngOnInit(): void breaks shipping.component.ts

### ISSUE THREAD

**Issue by goodwinchris** [angular/angular#55066]
### Describe the problem that you experienced

When following along with the getting started tutorial, I'm prevented from moving forward with the following error:

```
Type 'void' is not assignable to type 'Observable<{ type: string; price: number; }[]>'.
```

### Enter the URL of the topic with the problem

https://angular.io/start/start-data#configuring-the-shippingcomponent-to-use-cartservice

### Describe the actions that led you to experience the problem

Just following along with the tutorial.

### Describe what you want to experience that would fix the problem

I'd like a change to the code which resolves the issue or an explanation about how I can resolve it myself. 

### Add a screenshot if that helps illustrate the problem
<img width="607" alt="Screenshot 2024-03-27 at 11 06 10 AM" src="https://github.com/angular/angular/assets/791670/ed88df29-fcff-423c-b7b0-65f7df33a681">
<img width="599" alt="Screenshot 2024-03-27 at 11 06 15 AM" src="https://github.com/angular/angular/assets/791670/3504aecf-70d4-438d-968c-19be033efdbd">

### If this problem caused an exception or error, please paste it here

```true
Type 'void' is not assignable to type 'Observable<{ type: string; price: number; }[]>'.(2322)
(property) ShippingComponent.shippingCosts: Observable<{
    type: string;
    price: number;
}[]>
```
```


### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

**Comment by alxhub** [comment]
The code in the tutorial is correct. TypeScript is correctly telling you that in your code, `this.cartService.getShippingPrices()` is returning `void` which is not assignable to the `Observable`. It has nothing to do with `ngOnInit` or its return type - you likely did not return anything from `getShippingPrices()`.

**Comment by goodwinchris** [comment]
You are correct, it appears I missed the return in `getShippingPrices()`. Thank you for the reply.
