### ISSUE TITLE
Improve Async Pipe's support for Rx

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#5509]
1. We use this check to determine if an object is an observable `static isObservable(obs: any): boolean { return obs instanceof RxObservable; }`. We should change it to `static isObservable(obs: any): boolean { return !!obs.subscribe; }`. The reason is that async pipe does not depend on anything Rx specific and can be used for all observables that implement the same protocol. For instance, it can be used for a different version of Rx.

2. 
  - Create a sync BehaviorSubject
  - Bind it to the template like this `subj|async`. 
  - You will see that instead of showing the first value, it will show null. To fix it, we need to change

```
if (isBlank(this._obj)) {
   if (isPresent(obj)) {
     this._subscribe(obj);
   }
  return null;
}
```

to

```
if (isBlank(this._obj)) {
   if (isPresent(obj)) {
     this._subscribe(obj);
   }
  return this._latestValue;
}
```

**Comment by IgorMinar** [comment]
Looks like this was fixed by #5624
