### ISSUE TITLE
this.router.getCurrentNavigation().extras.state used to return undefined for the 1st navigation after reload the page

### ISSUE THREAD

**Issue by vupham30** [angular/angular#55106]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

this.router.getCurrentNavigation().extras.state used to return undefined for the 1st navigation after reload the page. After upgrade to angular17, looks like it can cache the state from previous navigation and provide it after reload the page.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.2.3
Node: 20.10.0
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 17.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1702.3
@angular-devkit/build-angular      17.2.3
@angular-devkit/core               17.2.2
@angular-devkit/schematics         17.2.3
@angular/cdk                       17.2.1
@angular/cli                       17.2.3
@angular/elements                  17.2.3
@angular/flex-layout               15.0.0-beta.42
@angular/localize                  17.2.3
@angular/material                  17.2.1
@angular/material-moment-adapter   17.2.1
@angular/router                    17.1.0
@schematics/angular                17.2.3
rxjs                               7.8.1
typescript                         5.3.3
zone.js                            0.14.4
```

**Comment by atscott** [comment]
> After upgrade to angular17, looks like it can cache the state from previous navigation and provide it after reload the page.

Yes, this is the correct behavior. I'm not sure what version you're coming from, but this was fixed in v15 in https://github.com/angular/angular/commit/cb6d73a84ef060a013d022b7696c68d343f62103

**Comment by vupham30** [comment]
I see, I come from angular14, any suggestions of how to solve this ? any other indicator that I can use to check if it's a 1st load after refresh the page ?

**Comment by atscott** [comment]
You should have several alternatives, including https://angular.io/api/router/Router#lastSuccessfulNavigation. If that’s not what you want, I would recommend asking a question on stackoverflow to get help.
