### ISSUE TITLE
Minor mistake in "Image optimization" guide page (aio)

### ISSUE THREAD

**Issue by johnnygerard** [angular/angular#55117]
### Describe the problem that you experienced

Under [Resource hints](https://angular.io/guide/image-directive#resource-hints), `rel="preload"` should be `rel="preconnect"`.

I wanted to open a pull request for this minor issue but I could not find the source page.

### Enter the URL of the topic with the problem

https://angular.io/guide/image-directive#resource-hints

**Comment by sonukapoor** [comment]
Hi @johnnygerard, the angular.io docs are no longer maintained. Everything has been ported over to Angular.dev. Here is the link to the NgOptimzedImage page: https://angular.dev/guide/image-optimization#add-resource-hints. It seems the issue is already fixed there.

**Comment by johnnygerard** [comment]
Thank you @sonukapoor. That makes sense.
