### ISSUE TITLE
Output Signal works, but parent says event is not emitted...

### ISSUE THREAD

**Issue by dreamstar-enterprises** [angular/angular#55120]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

<img width="833" alt="Screenshot 2024-03-29 at 16 36 14" src="https://github.com/angular/angular/assets/39380005/878ab207-0f93-42bc-85cd-82955d064d53">

### Please provide a link to a minimal reproduction of the bug

No need - see picture above

### Please provide the exception or error you saw

```true
CHILD CODE  
  /* data properties */
  public iconClick = output<void>()

  PARENT CODE
  see picture above
```

**Comment by JeanMeche** [comment]
This is a webstorm issue, it doesn't not support the new output function yet. 

Btw, the new `output()` is unrelated to signals. It is a new way of defining an output without using a decorator.

**Comment by dreamstar-enterprises** [comment]
Thank you for clarifying! I'll wait for the webstorm update.
