### ISSUE TITLE
Scrolling on angular.dev API reference page is not working well

### ISSUE THREAD

**Issue by atscott** [angular/angular#55131]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

The scrolling on the API reference page is currently not working well (example page: https://angular.dev/api/router/Router). There are a couple issues:

* Clicking on a public field does not scroll to the detailed explanation of the item. It looks like the scroll starts but is aborted almost immediately
* On mobile, the header interferes with the scroll position. I believe the ViewportScroller offset needs to be set correctly (https://github.com/angular/angular/blob/main/packages/common/src/viewport_scroller.ts#L38)
* On mobile, after scrolling to a specific detailed view of an item, trying to scroll back up through the list of items is frustrating. There seems to be some "snap" behavior that attempts to snap the cards to the top but this feels pretty unhelpful

### Please provide a link to a minimal reproduction of the bug

https://angular.dev/api/router/Router

**Comment by 9kubczas4** [comment]
Hi @JeanMeche,

I think this PR: https://github.com/angular/angular/pull/55133 could resolve this issue.

**Comment by atscott** [comment]
Fixed by #55133
