### ISSUE TITLE
No link to sources from reference documentation on angular.dev

### ISSUE THREAD

**Issue by jnizet** [angular/angular#55136]
### Description

angular.io has a `<>` link at the top of each page of the reference documentation, linking to the source code on github. This is extremely useful (to me at least) to discover/learn how things work.
I haven't found this link in the angular.dev documentation

### Proposed solution

Add that link back in the angular.dev documentation

### Alternatives considered

Go to github, search for the symbol and navigate through all the search results until the file containing the definition is found

**Comment by JoostK** [comment]
Thanks for the report, this is a valid point. I found #52636 for the same thing, which refers to #52663 where the item "Add link to code in repo" is still pending.
