### ISSUE TITLE
Possible Bug - Type Narrowing works with Strings (Class and Template), but not with Enums (only works in Class, but not Template)

### ISSUE THREAD

**Issue by dreamstar-enterprises** [angular/angular#55149]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

See here: https://stackoverflow.com/questions/78251202/angular-type-guard-not-narrowing-types/78251370?noredirect=1#comment137960210_78251370

Also stackblitz:
https://stackblitz.com/edit/stackblitz-starters-6eped6?file=src%2Fcmp%2Fcmp.component.ts

I use enums a lot in my code, for better organisation and modularisation, but am struggling to get type narrowing to work with enums in the template (e.g. in @if, or @switch blocks). It works with strings, but I want to move away from strings to enums. 

Also, I can't do a type checking function like this (the casting, object is A_DTO, doesn't work.. but this may be my lack of knowledge) :

```
   function isTypeA(object: AnyDTO): object is A_DTO {
      return object != undefined && object.type === 'Type_A';
    }
```

With this set up:

```
enum Types {
  Type_A = "Type_A",
  Type_B = "Type_B"
}

interface A_DTO {
  type: string;
  commonProperty: string;
  uniquePropertyA: string;
}

interface B_DTO {
  type: string;
  commonProperty: string;
  uniquePropertyB: string;
}
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-6eped6?file=src%2Fcmp%2Fcmp.component.ts

### Please provide the exception or error you saw

```true
Cannot recognise unique properties, when type is an enum (not sure if Typescript bug, or Angular bug). Works with strings no problem
```

### Anything else?

No

**Comment by dreamstar-enterprises** [comment]
Sorry, I think there is a workaround. 
You can't use Enum directly in Templates (only strings). 
Creating a shallow copy, seemed to be a good workaround, for type narrowing to work in the template.
` protected readonly TypesCopy = { ...Types };`

https://stackblitz.com/edit/stackblitz-starters-6eped6?file=src%2Fcmp%2Fcmp.component.ts

**Comment by JoostK** [comment]
I am confused, the StackBlitz works fine even without the `TypesCopy` indirection, using `Types` also works.

**Comment by dreamstar-enterprises** [comment]
Types didn't working in the 'template' for me, only TypesCopy.

**Comment by JoostK** [comment]
Please show that in StackBlitz, because it did for me when I tried.

**Comment by dreamstar-enterprises** [comment]
I've closed the issue. I'm sure it wasn't working for me this morning, in both IntelliJ, and StackBlizt. 
But, you're right, it works just fine. 
https://stackblitz.com/edit/stackblitz-starters-6eped6?file=src%2Fcmp%2Fcmp.component.ts
(this morning, enum types didn't work, but I may have been doing something wrong...)
Closing issue

**Comment by dreamstar-enterprises** [comment]
I still have the issue though in intellJ Idea
<img width="492" alt="Screenshot 2024-04-01 at 12 46 28" src="https://github.com/angular/angular/assets/39380005/2d9c60b2-cfbb-45ab-96d9-92e0629d9b49">

**Comment by dreamstar-enterprises** [comment]
In IntellJ, I had to declare the types like this, to resolve it. 

```
interface A_DTO {
  type: Types.Type_A;
  commonProperty: string;
  uniquePropertyA: string;
}

interface B_DTO {
  type: Types.Type_B;
  commonProperty: string;
  uniquePropertyB: string;
}

type AnyDTO = A_DTO | B_DTO;

Not like this

interface A_DTO {
  type: string;
  commonProperty: string;
  uniquePropertyA: string;
}

interface B_DTO {
  type: string;
  commonProperty: string;
  uniquePropertyB: string;
}

type AnyDTO =
  | ({ type: Types.Type_A } & A_DTO)
  | ({ type: Types.Type_B } & B_DTO);

```

**Comment by JoostK** [comment]
IntelliJ has its own type inference, on top of its Language Service support. The approach you have switched to is the typical pattern with union types, a simplification compared to how `AnyDTO` used to be declared 👍
