### ISSUE TITLE
 [$injector:unpr] Unknown provider: translateFilterProvider <- translateFilter

### ISSUE THREAD

**Issue by Hsinky** [angular/angular#55147]
### Which @angular/* package(s) are the source of the bug?

compiler, core

### Is this a regression?

No

### Description

error:` [$injector:unpr] Unknown provider: translateFilterProvider <- translateFilter`
translate.pipe.ts:
```
import { Pipe, PipeTransform } from '@angular/core';
@Pipe({
  name: 'translate'
})
export class TranslatePipe implements PipeTransform {
  transform(value: string): any {
    return value + 111
  }
}
```

app.module.ts:
```
import { TranslatePipe } from '../services/translate.pipe';
@NgModule({
  imports: [
    BrowserModule
  ],
  declarations: [TranslatePipe],
  entryComponents: [],
})
export class ManagementModule {}
```
html:
```
{{'hello'|translate}}
```

### Please provide the exception or error you saw

```true
[$injector:unpr] Unknown provider: translateFilterProvider <- translateFilter
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/cli": "12.2.3",
"@angular/cdk": "12.2.3",
"@angular/common": "12.2.3",
"@angular/compiler": "12.2.3",
"@angular/core": "12.2.3",

"node": "^16.10",
"npm": "^7.24"
```

**Comment by JoostK** [comment]
This appears to be a View engine error, which is obsolete in latest Angular. Please update to a supported version of Angular.

**Comment by Hsinky** [comment]
> This appears to be a View engine error, which is obsolete in latest Angular. Please update to a supported version of Angular.
我认为这可能不是过时了，但是还是希望您能帮我解决这个问题，很急!
