### ISSUE TITLE
Typescript 'user' is possibly 'undefined' Error in angular-compiler

### ISSUE THREAD

**Issue by surajchopra1234** [angular/angular#55146]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

```
type User = { role: "guest-user" | "user" | "none" };

public user = signal<User | undefined>(undefined);

public user$ = toObservable(this.user).pipe(filter((user) => user !== undefined));
```

```
this.authService.user$.subscribe((user) => {
    if (user.role === "guest-user" || user.role === "user") { }
}
```

Vs code doesn't give any error from typescript

### Please provide a link to a minimal reproduction of the bug

null

### Please provide the exception or error you saw

```true
X [ERROR] TS18048: 'user' is possibly 'undefined'. [plugin angular-compiler]

    src/app/product-page/product-page.component.ts:186:16:
      186 │             if (user.role === "guest-user" || user.role === "user...
          ╵                 ~~~~

X [ERROR] TS18048: 'user' is possibly 'undefined'. [plugin angular-compiler]

    src/app/product-page/product-page.component.ts:186:46:
      186 │ ...        if (user.role === "guest-user" || user.role === "user") {
          ╵                                              ~~~~
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
angular 17.3
```

**Comment by pankajd24** [comment]
Please provide https://stackblitz.com/ link of  this code

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).

**Comment by JoostK** [comment]
The code in

```ts
public user$ = toObservable(this.user).pipe(filter((user) => user !== undefined));
```

does _not_ result in `users$` being of type `User`, as the `filter` operator is not a type-guard. Only from TypeScript 5.5 onwards would the `user !== undefined` return expression result in inferring a type-guard of `user is User`, but TS 5.5 has not yet been released so the currently inferred return type is just `boolean`, causing the Observable to retain the `User | undefined` type.
