### ISSUE TITLE
Angular new website is down!

### ISSUE THREAD

**Issue by romeollangozi** [angular/angular#55140]
### Describe the problem that you experienced

I don't know if this is the right place for this issue but tried today to go to [Angular](url) new website and it's down

<img width="1680" alt="Screenshot 2024-03-31 at 5 38 22 PM" src="https://github.com/angular/angular/assets/109810675/eb74ead7-236f-4b45-9aa1-54f3749c268a">

### Add a screenshot if that helps illustrate the problem

<img width="1680" alt="Screenshot 2024-03-31 at 5 38 22 PM" src="https://github.com/angular/angular/assets/109810675/4021df1e-55fd-4d18-9b3b-9e3d3f91d7a2">

**Comment by chrisjdj** [comment]
Hi @romeollangozi , 

Do you face the same issue on an Incognito tab or a different browser?

**Comment by romeollangozi** [comment]
@chrisjdj
Just tried with incognito and safari i am facing the same issue

**Comment by alxhub** [comment]
Are you sure this is not just your local setup/internet? https://downforeveryoneorjustme.com/angular.dev

**Comment by romeollangozi** [comment]
@alxhub it says it is down just for me i tried clearing all cookies and still can't connect this is odd

**Comment by alxhub** [comment]
Given that angular.dev is still up (no one else is reporting issues), I'm going to close this issue. Judging from your screenshot, this is a DNS error of some kind - your ISP/DNS service can't resolve angular.dev.
