### ISSUE TITLE
Page Not Found 🙃

### ISSUE THREAD

**Issue by VivekDChenimane** [angular/angular#55153]
### Describe the problem that you experienced

Got the link from Angular project readme in github, clicking it took me to the page not found.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/components-in-angular

### Describe what you were looking for in the documentation

components-in-angular

### Describe the actions that led you to experience the problem

https://github.com/angular/angular -> [Components and Templates](https://angular.dev/tutorials/learn-angular/components-in-angular)

### Describe what you want to experience that would fix the problem

Correct link to redirect.

**Comment by michael-small** [comment]
Looks like the link in the same area of the `README.md` to forms 404s as well

https://github.com/angular/angular -> [Forms](https://angular.dev/tutorials/learn-angular/forms)

**Comment by A-Annan** [comment]
Can I work on it ?
