### ISSUE TITLE
docs: 404 in i18n documentation

### ISSUE THREAD

**Issue by johnnygerard** [angular/angular#55169]
### Describe the problem that you experienced

The [What's next](https://angular.dev/guide/i18n/add-package#whats-next) section of the [Add the localize package](https://angular.dev/guide/i18n/add-package) page has two links.  
The first link is broken: [@angular/localize API](https://angular.dev/api/localize).

### Enter the URL of the topic with the problem

https://angular.dev/api/localize

**Comment by JeanMeche** [comment]
Hello, thank you for reporting this issue.
We're currently tracking the missing elements of the API page in #52663. We'll continue the tracking over there.
