### ISSUE TITLE
feat(http): improve ergonomics of search params

### ISSUE THREAD

**Issue by cburgdorf** [angular/angular#5516]
Currently one has to construct `URLSearchParams` by hand like this.

```
search (term: string) {
    var params = new URLSearchParams()
    params.set('action', 'opensearch');
    params.set('search', term);
    params.set('format', 'json');
    return this.jsonp.get('http://en.wikipedia.org/w/api.php?callback=JSONP_CALLBACK', {
      search: params
    });
  }
```

I think we should improve ergonomics here so that one can write just this.

```
search (term: string) {
    return this.jsonp.get('http://en.wikipedia.org/w/api.php?callback=JSONP_CALLBACK', {
      search: {
        action: 'opensearch',
        search: term,
        format: 'json'
      }
    });
  }
```

/cc @jeffbcross @robwormald

**Comment by wwjhu** [comment]
One (intermediate) way of dealing with this is to have the URLSearchParams constructor accept an object besides a string.

**Comment by mhov** [comment]
Since querystring params can legally be repeated maybe something (for those familiar with solr) supporting array values
```
{ 
    search:{
        q: "test",
        fq: ["value1:1", "value2:2"]
    }
}
```
yielding `q=test&fq=value1:1&fq=value2:2`

**Comment by robwormald** [comment]
This issue was moved to angular/http#60
