### ISSUE TITLE
docs: code example missing in PercentPipe documentation page

### ISSUE THREAD

**Issue by johnnygerard** [angular/angular#55170]
### Describe the problem that you experienced

- [PercentPipe Usage Notes in angular.io](https://angular.io/api/common/PercentPipe#usage-notes)
- [PercentPipe Usage Notes in angular.dev](https://angular.dev/api/common/PercentPipe?tab=usage-notes)

Note: On angular.dev, the usage notes tab does not load on direct navigation.

### Enter the URL of the topic with the problem

https://angular.dev/api/common/PercentPipe?tab=usage-notes

**Comment by JeanMeche** [comment]
It looks like we have a regression on the API reference examples, `{@example ...}` also don't work anymore.

**Comment by JeanMeche** [comment]
Let's continue tracking this with #56321
