### ISSUE TITLE
feat(http): allow body to take an object 

### ISSUE THREAD

**Issue by cburgdorf** [angular/angular#5517]
Currently the `body` of the request params needs to be a string. This should also allow to pass an object and stringify automatically.

/cc @jeffbcross @robwormald

**Comment by thelgevold** [comment]
+1

**Comment by Abrissirba** [comment]
+1

**Comment by llCorvinSll** [comment]
+1

**Comment by tamascsaba** [comment]
+1

**Comment by juergenzimmermann** [comment]
+1

**Comment by PascalPrecht** [comment]
Can we please stop +1'ing on issues?

**Comment by robwormald** [comment]
This issue was moved to angular/http#59

**Comment by himanshuupadhyay** [comment]
Waiting for this....

**Comment by DzmitryShylovich** [comment]
@himanshuupadhyay it's already implemented. Type of the body is `any`
