### ISSUE TITLE
angular.dev : tutorial : (line: 1:24) Cannot find module '@angular/core' or its corresponding type declarations.

### ISSUE THREAD

**Issue by ThierryDuchatel** [angular/angular#55195]
### Describe the problem that you experienced

When I try to use each tutorial, I have an error and loading is pending : "(line: 1:24) Cannot find module '@angular/core' or its corresponding type declarations."
![angula dev_error](https://github.com/angular/angular/assets/40796210/d024db11-3b13-4ef7-89a2-c5107df0c057)

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app

**Comment by JoostK** [comment]
Please see https://github.com/angular/angular/issues/53151#issuecomment-1832438524

**Comment by ThierryDuchatel** [comment]
Hi @JoostK ,
I have seen the comments you have mentionned. But no answer is proposed... or I don't understand it !

**Comment by JoostK** [comment]
The comment refers to #52649 which is still open.
