### ISSUE TITLE
Unit test fails for Pipes that use an effect and inject ChangeDetectorRef

### ISSUE THREAD

**Issue by kreuzerk** [angular/angular#55191]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

We currently have a Unit Test that uses an `effect` and also injects the `ChangeDetectorRef`. Since we not only inject services and the `ChangeDetectorRef` we are want to mock away the services. Therefore we are using a `TestBed`. 

With this setup we always run into the following error:

```
TypeError: Cannot read properties of undefined (reading '2')
```

The error originates from the `effect.ts` - if (!cdr || !(cdr._lView[FLAGS] & LViewFlags.FirstLViewPass)) {, where the ChangeDetectorRef is being injected, but it gets the mock instead, so cdr._lView is undefined, which is not properly handled.

I already found this issue here which seems to be related: https://github.com/angular/angular/issues/53796

In the mentioned issue they inject the `ChangeDetectorRef` inside a service which is not the place to use the change detector since its tied to the component concept. However I think it is valid to use the `ChangeDetectorRef` inside a pipe. In the end this is also what the `async` pipe does under the hood.

@pkozlowski-opensource mentioned that we should not mock framework internals for our own test. Generally I think this is a good thing, but I could also see how someone wants to ensure that some critical `markForCheck` is guaranteed to be there.  This could be easily achieved by mocking the `cdr` and writing a test that the method is called.

The second point here is that if you do not mock the `ChangeDetectorRef` your test will fail with the following error:

```
NullInjectorError: R3InjectorError(DynamicTestModule)[DemoPipe -> ChangeDetectorRef -> ChangeDetectorRef]: 
  NullInjectorError: No provider for ChangeDetectorRef!
```

I created a small reproduction example which I pushed here: https://github.com/kreuzerk/effect-test-pipe

The error can be reproduced with the following steps:
- Checkout repo
- npm i
- npm run test

### Please provide a link to a minimal reproduction of the bug

https://github.com/kreuzerk/effect-test-pipe

### Please provide the exception or error you saw

```true
When mocking the `ChangeDetectorRef` you get this error:


TypeError: Cannot read properties of undefined (reading '2')
```

If you do not mock the `ChangeDetectorRef` you get this error
```
NullInjectorError: R3InjectorError(DynamicTestModule)[DemoPipe -> ChangeDetectorRef -> ChangeDetectorRef]: 
  NullInjectorError: No provider for ChangeDetectorRef!```
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.3
Angular: 17.3.2
```

**Comment by JeanMeche** [comment]
Just for the sake of sharing, this is what the `AsyncPipe` unit test does. 

https://github.com/angular/angular/blob/f5773196ec4bbe46f35bbf96bb6d3ba123275119/packages/common/test/pipes/async_pipe_spec.ts#L18-L25

**Comment by kreuzerk** [comment]
Hi @atscott thx a lot for the reply. maybe my description was not really clear. In my case I am not using the `async` pipe at all. I just refered to the `async` pipe as an example of a pipe that internally uses the `ChangeDetectorRef`. In my case I have my own pipe which is injecting the `ChangeDetectorRef`. I think the reroduction example here should clearify things: 

- Pipe: https://github.com/kreuzerk/effect-test-pipe/blob/main/src/app/demo.pipe.ts
- Spec: https://github.com/kreuzerk/effect-test-pipe/blob/main/src/app/demo.pipe.spec.ts

**Comment by alxhub** [comment]
Mocking Angular classes is certain to cause issues like this. If you want to ensure your code is calling `markForCheck`, you can abstract `ChangeDetectorRef` behind a different interface which you then mock, instead of providing a mock directly for `ChangeDetectorRef`.

**Comment by atscott** [comment]
>  maybe my description was not really clear. In my case I am not using the async pipe at all. I just refered to the async pipe as an example of a pipe that internally uses the ChangeDetectorRef

Yes, I understand. I'm using `AsyncPipe` as an example as well. 

> but I could also see how someone wants to ensure that some critical markForCheck is guaranteed to be there. This could be easily achieved by mocking the cdr and writing a test that the method is called.

The call to `markForCheck` is not the critical behavior you should be testing. This is an implementation detail. If we released an API that allowed you to mark for check in a more efficient way and you wanted to use it, your test would fail even though the outcomes are still correct (the thing that uses the pipe is updated when change detection runs). 

We also found that `markForCheck` was not necessary in some cases for `AsyncPipe` and removed the call (https://github.com/angular/angular/pull/54554). This should not cause any tests to fail because `markForCheck` did not need to be called in order for the template to display the correct information.

Another example: What if the behavior of `markForCheck` changed such that your template no longer updated correctly (#55099, https://github.com/angular/angular/pull/55099/files#diff-48884166d82efbef3314285ebf91c4e7c8da9d57b352cc2178ac1f762387caf1R491-R514)? You wouldn't have a test that failed because it was only asserting that `markForCheck` was called rather than the final outcome.

**Comment by kreuzerk** [comment]
Hi @atscott and @alxhub thx a lot for the reply. I agree that the `markForCheck` is not the behaviour to test here. I guess my question is how can I provide the `ChangeDetectorRef` without mocking it? If I just use the `TestBed` and do not provide any mock for the `ChangeDetectorRef` I get the following error:

```
NullInjectorError: R3InjectorError(DynamicTestModule)[DemoPipe -> ChangeDetectorRef -> ChangeDetectorRef]: 
  NullInjectorError: No provider for ChangeDetectorRef!
```

if I try to mock it and provide the service I run into this error.

```
TypeError: Cannot read properties of undefined (reading '2')
```

I am curious how to test a Pipe that uses an effect and also injects the `ChangeDetectorRef`?

**Comment by kreuzerk** [comment]
@JeanMeche proposed a working solution here. https://stackblitz.com/edit/github-cdpnsq?file=package.json,src%2Fapp%2Fdemo.pipe.ts&template=node

While this solution is elegant I am not the biggest fan of it since I would need to evolve that interface whenever the `ChangeDetectorRef` evolves furthermore I would want to avoid to introduce some productive code just to enable testing.

Thx @JeanMeche for showing me this approach 👍

**Comment by kreuzerk** [comment]
Hey @alxhub thx a lot for taking a look at this issue and your reply. I am fine with not mocking the `ChangeDetectorRef` here, but I am wondering what the alternative is, if I do not mock the `ChangeDetectorRef` I get a `NullInjector` error. So I don't think we can close this issue yet since I currently don't see a way of testing a pipe that uses an `effect` and injects the `ChangeDetectorRef` but maybe I am missing something. Thx for your help

**Comment by yjaaidi** [comment]
Hey Kevin!

By getting closer to implementation details (i.e. providing a test double for CDR):
- the test becomes **structure sensitive**:  future changes to Angular or the code would break the test. Also, the test should be resilient to whether you are using an effect or any custom scheduling/coalescing mechanisms. 
- the test becomes **over-specifying**: the test goes beyond specifying the behavior of the pipe and starts specifying how and when change detection should be triggered.  
- the test is less of a doc in this case: **tests are docs** so the closer they are to “real-life” usage, the better
- the test will not fail if someone replaces the name of the pipe (by mistake after some “replace all” :innocent:)

That is why, I’d recommend either using a wrapping component or wrapping that component in a testing util function.

```ts
@Component({
  standalone: true,
  imports: [DemoPipe],
  template: `{{ value() | demo }}`
})
class Wrapper {
  value = input.required();
}

const fixture = TestBed.createComponent(Wrapper);
fixture.componentRef.setInput('value', '...');
fixture.autoDetectChanges();
await fixture.whenStable();

expect(fixture.nativeElement.textContent).toBe('...);
```

or less boilerplate using Angular Testing Library (or similar / or custom util):

```ts
const { container } = await render('{{ value | demo }}', {
  declarations: [DemoPipe],
  componentProperties: {value: 42}
});
expect(container.textContent).toBe(...); // or expect(container).toHaveTextContent()
```

**Comment by kreuzerk** [comment]
This is the solution that worked for us! Thx for sharing @yjaaidi 💪
