### ISSUE TITLE
Not all API documentation is visible

### ISSUE THREAD

**Issue by atscott** [angular/angular#55196]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

The information in JSDoc tags is not available in the API reference page. It appears that only the main documentation is presented. 

<img width="1321" alt="image" src="https://github.com/angular/angular/assets/479713/daea93ae-95e6-4745-8619-bbc4c10ab2db">
The APIs are deprecated but the description of why is not visible
<img width="716" alt="image" src="https://github.com/angular/angular/assets/479713/43c22492-c65e-4053-bfeb-44def3d3f15f">

<img width="1278" alt="image" src="https://github.com/angular/angular/assets/479713/121ca8cf-9ee9-44a8-b691-b700a5314775">
`navigateByUrl` is missing the `@usageNotes` information
<img width="804" alt="image" src="https://github.com/angular/angular/assets/479713/0bef114b-2a5c-4ee6-b267-2921347c3b5e">

**Comment by JeanMeche** [comment]
angular/dev-infra#1955 added the usage notes, angular/dev-infra#1964 should add the deprecation messages.
