### ISSUE TITLE
Ancors on page doesn't lead to specific id's

### ISSUE THREAD

**Issue by Frazeny** [angular/angular#55219]
### Describe the problem that you experienced

List of `ng-generate` sub-commands anchors do not lead to corresponding subcommand description

Reason: The subcommand `h3` tags are missing `id` property

### Enter the URL of the topic with the problem

https://angular.dev/cli/generate

### Describe what you want to experience that would fix the problem

Clicking on the list of anchors would lead to corresponding section on the page

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/53953882/ea85c3ad-9c50-487c-8b9e-9c2dd9f2210d)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
No
```

**Comment by JeanMeche** [comment]
Hi, API pages are still a WIP and this particular issue around CLI commands is tracked by #54768.

**Comment by Frazeny** [comment]
Okey, thank you!
