### ISSUE TITLE
`ActivatedRoute` doesn't work in angular elements (web component)

### ISSUE THREAD

**Issue by pchabros** [angular/angular#55213]
### Which @angular/* package(s) are the source of the bug?

elements

### Description

This component works as expected inside Angular app - after manually appending `/?foo=bar` to URL I can see `bar` printed in the console.

```ts
export class ActivatedRouteComponent implements OnInit {
  route = inject(ActivatedRoute);

  ngOnInit() {
    this.route.queryParamMap.subscribe((paramMap) =>
      console.log(paramMap.get('foo')),
    );
  }
}
```

But after exporting it as web component using angular-elements it doesn't work - `null` printed once.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.2.3
Node: 20.11.0
Package Manager: npm 10.2.4
OS: linux x64

Angular: 17.2.4
... animations, common, compiler, compiler-cli, core, elements
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.3
@angular-devkit/build-angular   17.2.3
@angular-devkit/core            17.2.3
@angular-devkit/schematics      17.2.3
@angular/cdk                    17.2.2
@angular/cli                    17.2.3
@angular/language-server        17.2.2
@angular/material               17.2.2
@schematics/angular             17.2.3
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

### Anything else?

Is it expected, or `ActivatedRoute` should work in web component?

**Comment by JoostK** [comment]
This is expected, as `ActivatedRoute` comes from the `router-outlet` (more specifically, the injector created by `router-outlet` for the routed component), whereas the custom element is typically created using the root injector.

**Comment by pchabros** [comment]
I'm not sure if I fully understand, but if it comes to reading query params in Angular it works even without `router-outlet`. To get param like `:id` - yes, I have to specify a route in `Routes` array that points to given component and add `router-outlet`, but query params works without all of that.

**Comment by JoostK** [comment]
You can only access `Router.routerState.snapshot` (i.e. inject `Router`), not `ActivatedRoute` from within a custom element, since the custom element can only access DI things from the injector that was provided during its creation (`createCustomElement` [takes an `injector` as option](https://angular.dev/api/elements/NgElementConfig))

**Comment by pchabros** [comment]
`Router.routerState.snapshot` also doesn't return anything - `Route(url:'', path:'')`.

**Comment by JoostK** [comment]
Likely because it's the root route, not the route that corresponds with the `router-outlet` level.

**Comment by atscott** [comment]
Yes, `ActivatedRoute` is re-provided by `RouterOutlet`. In order to get something other than the root `ActivatedRoute`, injectors must be children of the outlet injector.

Closing as working as expected.
