### ISSUE TITLE
access  template variable in the level of its parents

### ISSUE THREAD

**Issue by dreambo8563** [angular/angular#5523]
in the doc https://angular.io/docs/ts/latest/guide/user-input.html
it is said "We can access the newHero variable from any sibling or child of the <input> element."

Actually ,we can access the newHero in the level of its parents. I am not sure if here is a bug...

here is my code

```javascript
@Component({
    selector: 'little-tour',
    template: `
    <h4>Little Tour of Heroes</h4>
    <div>
        <input #new-hero class="aa"
        (keyup.enter)="addHero(newHero)"
         (blur)="addHero(newHero)">
        <button (click)=addHero(newHero)>Add</button>
        <ul>
            <li *ng-for="#hero of heroes">{{hero}}
            </li>
        </ul>
    </div>
    <div>
    {{newHero.className}}
    </div>
  `,
    directives: [CORE_DIRECTIVES]
})
export class LittleTour {
    heroes = ['Windstorm', 'Bombasto', 'Magneta', 'Tornado'];
    addHero(newHero) {
        if (newHero.value) {
            this.heroes.push(newHero.value);
            newHero.value = null; // clear the newHero textbox
        }
    }
}
```

**Comment by michaelbromley** [comment]
Here is a plunker demo, using beta.15: http://plnkr.co/edit/OOrn2nA1qqKeU1OijgFW?p=preview

**Comment by pkozlowski-opensource** [comment]
> in the doc https://angular.io/docs/ts/latest/guide/user-input.html
it is said "We can access the newHero variable from any sibling or child of the element."

This would be a documentation bug. Could you please open at https://github.com/angular/angular.io if still not fixed? Thnx!
