### ISSUE TITLE
angular tutorial

### ISSUE THREAD

**Issue by mastakimm** [angular/angular#55236]
### Describe the problem that you experienced

I'm on the first angular tutorial and the images URLs given results nowhere.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app/08-ngFor

### Describe what you were looking for in the documentation

tutorial images URLs

### Describe the actions that led you to experience the problem

tutorial

**Comment by JeanMeche** [comment]
Hi, thank you for repporting this issue, we're already tracking it in #55163.
