### ISSUE TITLE
angular signal not updating when using afterNextRender()

### ISSUE THREAD

**Issue by fredtma** [angular/angular#55238]
### Which @angular/* package(s) are the source of the bug?

core, zone.js

### Is this a regression?

No

### Description

I have to manually trigger a change detection when updating/setting a signal inside the `afterNextRender` method.

```typescript
    afterNextRender(() => {      
       this.someAPI.then((items) => {
         this.items.set(items); // <-- set signal
         this.ref.detectChanges(); // <--- trigger change detection
       });       
    });
```

```html
            <tbody>
              @for(item of items(); track item.id) {
                <tr>
                  <td class="text-success"><strong>{{item.name}}</strong></td>
                </tr>
              }
            </tbody>
```

There is no mention in the documentation that this function runs outside zone.js.<br/>
So I am not sure if this is the way it is suppose to run.

### Please provide a link to a minimal reproduction of the bug

https://stackoverflow.com/questions/78280552/angular-signal-not-updating-afternextrender

### Please provide the exception or error you saw

```true
No error
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 17.2
Node: 18
Package manager: yarn
Os: Linux
```

### Anything else?

none

**Comment by JeanMeche** [comment]
Hi, this was introduced explicitly by #51385. I agree this is not explicit in the docs.

**Comment by fredtma** [comment]
Thank you, was not aware of [this](https://github.com/angular/angular/pull/51385).
Can be closed

**Comment by atscott** [comment]
This should already work in v18 though. Change detection will be rerun if a signal is updated in render hooks.
