### ISSUE TITLE
how to handle "document is not defined" in ng17 ssr

### ISSUE THREAD

**Issue by ohabash** [angular/angular#55254]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I am using [QuillJs](https://github.com/quilljs/quill) ... After installing it SSR stops working. I tried JSDOM and other advices online. Looking for the most modern advice. Please see my reproduction of the issue.

### Please provide a link to a minimal reproduction of the bug

https://github.com/ohabash/ng-ssr-quill

https://stackoverflow.com/questions/78295372/angular-17-ssr-document-is-not-defined-when-using-quilljs

### Please provide the exception or error you saw

```true
> [vite] Error when evaluating SSR module /main.server.mjs:
|- ReferenceError: document is not defined
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.3
Node: 20.9.0
Package Manager: npm 10.1.0
OS: darwin arm64

Angular: 17.3.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.3
@angular-devkit/build-angular   17.3.3
@angular-devkit/core            17.3.3
@angular-devkit/schematics      17.3.3
@schematics/angular             17.3.3
rxjs                            7.8.1
typescript                      5.4.4
zone.js                         0.14.4
```

**Comment by JeanMeche** [comment]
Hi, 
The common recommandation is to wrap client only library invocation inside `afterNextRender()` or with `if(isPlatformBrowser())` which will run  the code only on the client and not on the server.

**Comment by ohabash** [comment]
Please dont give up on this topic. Look at my repo. the error is caused by simply having the imort in a component. so in the repo how would you apply that advice of `afterNextRender ` & `if(isPlatformBrowser())`

**Comment by JeanMeche** [comment]
This means you'll likely need to import your library dynamicaly. (via a dynamic import).

**Comment by ohabash** [comment]
Is something like this what you had in mind?

![Screenshot 2024-04-09 at 10 12 26 AM](https://github.com/angular/angular/assets/15847500/01771c98-d537-44c7-9cc6-d36136d796c1)

please. I need to know how to do this and other sources are not helping.

**Comment by JeanMeche** [comment]
You're using a default export here, you need to access that constructor. 
```
const module = await import('quill');
this.editor = new module.Quill(...)

```

**Comment by ohabash** [comment]
That seems to work. Thank you

**Comment by ohabash** [comment]
That seems to work. I updated the repo https://github.com/ohabash/ng-ssr-quill

**Comment by bxbdev** [comment]
> That seems to work. I updated the repo https://github.com/ohabash/ng-ssr-quill

Thanks, it's worked!!!
