### ISSUE TITLE
feat(http): add support for withCredentials flag

### ISSUE THREAD

**Issue by cburgdorf** [angular/angular#5525]
The `withCredentials` flag on the `XHR` object is important to allow sending cookies in a CORS scenario. It doesn't seem to be supported currently.

Here's a reference to the Angular 1 codebase regarding it's implementation:
https://github.com/angular/angular.js/blob/d077966ff1ac18262f4615ff1a533db24d4432a7/src/ng/httpBackend.js#L117-L119

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/4231

**Comment by cburgdorf** [comment]
Oops
