### ISSUE TITLE
Router navigate on page refresh

### ISSUE THREAD

**Issue by tbragaf** [angular/angular#5526]
Hi all!

I came across a weird behaviour with router navigation with child routers.

Parent Router:
```js
@RouteConfig([
  { path: 'child/...', as: 'Child', component: Child }
])
```

Child Router:
```js
@RouteConfig([
  { path: '/', redirectTo: '/favorites' },
  { path: ':category', as: 'Category', component: Category }
])
```

If I use the router navigation API, this navigation seems not to be working:
```
this.router.navigate('child');
```

Neither does refresh the page work (refresh with '#/child' does not even instanciate the Child router).

Child Router redirect seems to be only working with Router Link:
```html
<a [router-link]="['Child']">Home</a>
```

Is it possible this is occuring since the url does not match the pattern '/...' ?

Can anyone confirm this?

Best regards,
tbragaf

**Comment by brandonroberts** [comment]
@tbragaf Are you getting any errors? I would think you would get an error that your Child component does not have a terminal instruction.

**Comment by tbragaf** [comment]
@brandonroberts No, I am not.
But neither is the child component is instanciated if I refresh the page with the url
```
#/child/
```

**Comment by brandonroberts** [comment]
@tbragaf can you reproduce in this plunk? http://plnkr.co/edit/VTvO9FxFCNaRgGkP1pUF?p=info

**Comment by tbragaf** [comment]
@brandonroberts One of the errors I came across is related to page refreshes.
You may want to reproduce it here: https://github.com/tbragaf/ng2-typescript/tree/features/tb-router

**Comment by brandonroberts** [comment]
@tbragaf In your example, in your goTo method you have

```js
  goTo(path : string) {
    this.router.navigateUrl(path);
  }
```

And you're using `goTo('Home')` in your template. If you want to use the router DSL, you should have

```js
  goTo(path : string) {
    this.router.navigate(path);
  }
```

And use `goTo(['Home'])` in your template

**Comment by tbragaf** [comment]
@brandonroberts That was just me trying something else.
Fixed by now, but the issue persists.

**Comment by brandonroberts** [comment]
@tbragaf Ok, I see. If you want to navigate by url, you'll need the full URL path.

```html
<button (click)="goTo('/home/favorites')">Home</button>
```

**Comment by tbragaf** [comment]
@brandonroberts Well, that's bad. But thank you for the heads up!

I need to use navigateByUrl because the urls come from a json :/

Anyway, did you try to refresh the page with the given url?
```
#/home
```
In my local app, that does not render to the Home component.

**Comment by brandonroberts** [comment]
@tbragaf Yea, I saw that. There are two different issues. You want /home to redirect to /home/favorites. I think that is a bug, since the redirect is not being recognized inside the child route. The other issue is you don't have component defined for the home route. A workaround would be to add your redirect in your parent route config.

Parent:

```js
@RouteConfig([
  { path: 'home/...', as: 'Home', component: Home },
  { path: 'home', redirectTo: '/home/favorites' } // this is so the redirect works
])
```

Child:
```js
@RouteConfig([
  { path: '/', redirectTo: '/favorites' }, // this is so the router link works
  { path: ':category', as: 'Category', component: Category }
])
```

If you want the button to work, you need to use navigate

```js
  goTo(path : any[]) {
    this.router.navigate(path);
  }
```

In your template

```
goTo(['Home'])
```

These bugs may be fixed in the latest refactor, but we'll have to wait for the next release.

**Comment by tbragaf** [comment]
@brandonroberts That 'recognize' method actually solves my problem with routing via js, thank you!

Regarding to the RouteConfig workaround, I simply can't work with that in production, so, if you don't mind, I'll keep this openned until it is solved.

Thank you very mcuh!
tbragaf

**Comment by brandonroberts** [comment]
:+1:

**Comment by btford** [comment]
Note that the behavior of redirects has changed significantly. See: #5352

**Comment by tbragaf** [comment]
@btford Well, waiting for beta0 then.
Fine for me :)

But how would that work with params?
Redirect like this?
```
['Category', { category: 'favorites' }]
```

That would be sweet!

Thank you,
tbragaf

**Comment by brandonroberts** [comment]
@tbragaf it will work if you put it in the parent route config. You can't use redirect routes to generate links though.

```js
@RouteConfig([
  { path: 'child/...', as: 'Child', component: Child },
  { path: 'child', redirectTo: ['Child', 'Category', {category: 'favorites'}] }
])
```

**Comment by tbragaf** [comment]
@brandonroberts 
It seems a nice workaround, but the parent shouldn't have to know the child router behaves...
But for now, it seems good!

Thank you!

**Comment by brandonroberts** [comment]
@tbragaf I misspoke. That will work, but generating links from that will not.

Parent
```js
@RouteConfig([
  { path: 'child/...', as: 'Child', component: Child }
])
```

Child
```js
@RouteConfig([
  { path: '/', redirectTo: ['./Category', {category: 'favorites'}] },
  { path: '/:category', component: Category, name: 'Category' }
])
```

**Comment by tbragaf** [comment]
Great!
Now that's something :)

Regarding to the page refresh (url path as #child), would you rather close this issue now, or wait until that is solved?
Feel free to close it.

Thank you!

**Comment by btford** [comment]
@tbragaf you probably want `useAsDefault`, not `Redirect`. See #5352.

**Comment by tbragaf** [comment]
@btford I don't know about that.
(But first of all, the router is getting so awesome, good job!)

I simply need to '/favorites' as a default route. What I expected to have:
```js
@RouteConfig([
  { path: ' ', redirectTo: ['Category', {category: 'favorites'}] },
  { path: ':category', component: Category, name: 'Category' }
])
```

Your proposal:
@RouteConfig([
  { path: 'favorites', component: Category, useAsDefault: true, name: 'Favorites' },
  { path: ':category', component: Category, name: 'Category' }
])

With that I need to redefine my Category component and I will need another router DSL, which I don't need.

I understand the purpose of the router ```code useAsDefault ``` and it may work for other purposes, but I simply need one path with multiple values, which I then use ```code RouteParams ``` to get the given param.

If I specify the route like that, I won't be able to get ```code RouteParams ```

Thank you!

**Comment by tbragaf** [comment]
Just upgraded to newest alpha and all issues I refered are now closed.

Closing, good job! :)
