### ISSUE TITLE
Computed signal and effect don't recompute if non signal boolean value included in computation as first check in condition.

### ISSUE THREAD

**Issue by YanGeruch** [angular/angular#55261]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Computed signal and effect don't recompute if non signal boolean value included in computation as first check in condition.

Here is a simple example. 2 computed signals (flag1 and flag2) with same condition but different order of boolean conditions.
interval switches 2 conditions every 2 seconds, flag 1 is updated and re-rendered normally on UI, Flag 2 is not updated despide signal it depends on changing, effect for flag2 only fires once.

this is very unintuitive behaviour and shouldn't work like this when documentation states ant computed signal will recompute when signal inside changes. There are not special clauses that normal variables should follow some rules when used inside computed signals.

`import 'zone.js';
import {Component, computed, effect, signal} from '@angular/core';
import {bootstrapApplication} from '@angular/platform-browser';

@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <h1>Hello from {{ name }}!</h1>
    <a target="_blank" href="https://angular.dev/overview">
      Learn more about Angular
    </a>
    <div>Flag1: {{flag1()}}</div>
    <div>Flag2: {{flag2()}}</div>
  `,
})
export class App {
  name = 'Angular';
  booleanSignal = signal(false);
  boolean = false;
  flag1 = computed(() => this.booleanSignal() && this.boolean)
  flag2 = computed(() =>  this.boolean && this.booleanSignal())
  constructor() {
    effect(() => console.log('signal second', this.boolean && this.booleanSignal()))
    setInterval(() => {
      this.boolean = !this.boolean;
      this.booleanSignal.update(x => !x)
    }, 2000)
  }
}

bootstrapApplication(App);
`

![angular bug](https://github.com/angular/angular/assets/92332304/3170e6fd-21ef-47ea-a91b-410a77a4a8b5)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-4w398k?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.1       
Node: 18.18.2
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 17.3.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.0
@angular-devkit/build-angular   17.3.0
@angular-devkit/core            17.3.0
@angular-devkit/schematics      17.3.1
@schematics/angular             17.3.1
rxjs                            7.8.1
typescript                      5.4.2
zone.js                         0.14.2
```

**Comment by YanGeruch** [comment]
![angular bug](https://github.com/angular/angular/assets/92332304/3170e6fd-21ef-47ea-a91b-410a77a4a8b5)

**Comment by YanGeruch** [comment]
> > this is very unintuitive behaviour and shouldn't work like this when documentation states ant computed signal will recompute when signal inside changes.
> 
> This should be nuanced with the statement that "computed signal will recompute when _accessed_ signal inside changes". In your second example there is no signal read at all at we were considering a warning in such cases.

Hi, booleanSignal i being read in both cases. && operators have to read and evaluate both conditions.
` computed(() => this.boolean && this.booleanSignal())`

**Comment by pkozlowski-opensource** [comment]
> Hi, booleanSignal i being read in both cases. && operators have to read and evaluate both conditions.
 computed(() => this.boolean && this.booleanSignal())

This is not the case - if the first condition is false, the subsequent expression will _not_ be evaluated: https://stackblitz.com/edit/vitejs-vite-gy878w?file=main.js&terminal=dev

**Comment by alxhub** [comment]
In that sense, this is "working as intended" from an Angular perspective. However, it does raise the question of whether `computed` prohibit (or perhaps warn about) the degenerate case of no dependencies?

**Comment by msmallest** [comment]
> However, it does raise the question of whether computed prohibit (or perhaps warn about) the degenerate case of no dependencies?

Are you speaking in terms of like, the language service or compiler giving a warning/error? If so, I think that would be nice.

**Comment by pkozlowski-opensource** [comment]
> Are you speaking in terms of like, the language service or compiler giving a warning/error? If so, I think that would be nice.

It can't be compiler, any potential warning would have be runtime
