### ISSUE TITLE
ng-invalid class is being added when required is set to false or null

### ISSUE THREAD

**Issue by williamdstuart** [angular/angular#5527]
When binding the required DOM property of an input element, the ng-invalid class is always added.  

    <input type="text" [required]="false" #x [(ng-model)]="title"></input>{{ x.required + "-" + x.className }}

    <input type="text" [required]="true" #y [(ng-model)]="title"></input>{{ y.required + "-" + y.className }}

**Comment by greg-md** [comment]
In beta.1 remains the same problem!

If element is not required, or checkbox is not selected, you get invalid in ngForm.

**Comment by slintes** [comment]
Hi, I have the same problem, I'm setting `required` and `readonly` based on a checkbox value, see this example:

http://plnkr.co/edit/XM8QTwkr3B4nzc40gEpx?p=preview

**Comment by zoechi** [comment]
Boolean properties are only removed on `null`, not on `false`

    [required]="truthy ? true : null" (where `truthy` is any value other than `null`/`undefined`)

**Comment by williamdstuart** [comment]
@zoechi  I tried both of the statements below, and the ng-invalid class is still added.

<input type="text" [required]="null" #x [(ngModel)]="title" />{{ x.required + "-" + x.className }}

<input type="text" [required]="1 === 2 ? true : null" #x [(ngModel)]="title" />{{ x.required + "-" + x.className }}

**Comment by Celebes** [comment]
I have the same problem, I defined conditional required attribute in input: `[required]="isRequired ? 'true' : null"`. Not setting "isRequired" makes "required" attribute not present, but class `ng-invalid` is still added.

**Comment by johannesjo** [comment]
This is probably related:  The `ng-valid-required` class is applied initially when using `ng-required`.

See:
http://plnkr.co/edit/nqPhJkmag3AQdntFRbEN?p=preview
https://github.com/johannesjo/ng-fab-form/issues/90

**Comment by pkozlowski-opensource** [comment]
This should be fixed by 0b665c0ece816fa5a54de9a778bf29122e32267d
