### ISSUE TITLE
Type for @NgModule.imports is not compatible with recommended standalone group export

### ISSUE THREAD

**Issue by distante** [angular/angular#55278]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

The documentation of [Standalone components for library authors](https://angular.io/guide/standalone-components#standalone-components-for-library-authors) states:

> As an alternative to publishing a [NgModule](https://angular.io/api/core/NgModule), library authors might want to export an array of cooperating directives:
> ```
>export const CAROUSEL_DIRECTIVES = [ImageCarouselComponent, ImageSlideComponent] as const;
>```
> Such an array could be imported by applications using [NgModule](https://angular.io/api/core/NgModule)s and added to the @[NgModule.imports](https://angular.io/api/core/NgModule#imports). Please note the presence of the TypeScript’s as const construct: it gives Angular compiler additional information required for proper compilation and is a recommended practice (as it makes the exported array immutable from the TypeScript point of view).

But following that recommendations triggers Typescript warnings in strict mode because a `readonly any[]` is not compatible with `any[]`

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.3
Node: 20.11.0
Package Manager: npm 10.2.4
OS: darwin arm64

Angular: 17.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, ssr

Package                              Version
--------------------------------------------------------------
@angular-devkit/architect            0.1701.3
@angular-devkit/build-angular        17.1.3
@angular-devkit/core                 17.1.3
@angular-devkit/schematics           17.1.3
@angular/cdk                         17.1.2
@angular/material                    17.1.2
@angular/material-date-fns-adapter   17.1.2
@schematics/angular                  17.1.3
ng-packagr                           17.1.2
rxjs                                 7.8.1
typescript                           5.3.3
webpack                              5.90.1
zone.js                              0.14.3
```

### Anything else?

I think  `@NgModules.import` should not take `any[]` but `Readonly<any[]>`.

**Comment by JeanMeche** [comment]
Hi, thank you for reporting this issue, It is been discussed in #48089 and there is (was ?) a pending PR for this in #48106.
