### ISSUE TITLE
Disable dev tools by code?

### ISSUE THREAD

**Issue by ivan-shaban-godel** [angular/angular#55279]
### Is this a bug report or a feature request?

- [ ] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

I have a react based web application and if user has enabled "Angular dev tools" extension it hang up whole browser.

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

I expect that "Angular dev tools" wouldn't affect react based applications.

### Is this a browser-specific issue? If so, please specify the device, browser, and version. [Bug Report only]

```true
No, it is independ from browser.
```

### Proposed solution [Feature Request only]

If would be greate if i can setup some global variable to disable angular dev tools extension, e.g.:
```window.__DISABLE_ANGULAR_DEVTOOLS__ = true;```

**Comment by JeanMeche** [comment]
This pretty much looks like the same issue as #49518

**Comment by oleg-vasilyev** [comment]
Solution that avoids the need to disable devtools
https://github.com/angular/angular/issues/49518#issuecomment-2088436998

**Comment by JeanMeche** [comment]
Without any feedback from the author, I'll close it.
