### ISSUE TITLE
Clear terminal when running projects

### ISSUE THREAD

**Issue by suaracost** [angular/angular#55276]
### Description

When I run a program made in angular in the terminal it will show me errors or if everything is ok, when I do big changes many errors might appear and it might get messy.

The terminal will be full of things and different things so it's difficult to keep track.

I'm using angular 16.2.12, don't know if it was already implemented in newer versions.

### Proposed solution

Clear when running, every time the user saves the document that it's being modified do a console clear or something so only the things from that "run" will appear.

### Alternatives considered

Nothing

**Comment by JoostK** [comment]
This has been implemented in angular/angular-cli#27018 when using the new application builder
