### ISSUE TITLE
Make font of the documentation bigger

### ISSUE THREAD

**Issue by maksat-mad** [angular/angular#55280]
### Description

I have a bad eyesight and I find it difficult to read the Angular 17 documentation because the font is too small for me

### Proposed solution

Could you please make a button which increases/decreases font?

### Alternatives considered

I do not have any alternatives, just make a button which increases/decreases font

**Comment by jnizet** [comment]
`Ctrl +` (or `Cmd +` on Mac) will zoom and make things more readable for you, in case you don't know.
IMHO, it's easier to use than using a custom button. And it works everywhere.
