### ISSUE TITLE
Rename QueryList to something not mentioning Query

### ISSUE THREAD

**Issue by rkirov** [angular/angular#5529]
Since the Query annotation is deprecated is it odd that the type of @ContentChildren and @ViewChildren is QueryList.

A good name should not contain any imperative verbs like query, search, find, etc.

**Comment by wardbell** [comment]
How about `childList<T>` for the results of both `viewChildren` and `contentChildren`?
Or `childComponentList<T>` if we want to be very clear about the nature of the return values.

**Comment by filipesilva** [comment]
`ChildComponentList` or even just `ComponentList` seem the most straightforward.  As far as I can tell, it always queries for and returns instantiated components.

**Comment by pkozlowski-opensource** [comment]
> ChildComponentList or even just ComponentList

AFAIK you can query for both components and directives, so I don't think we should have "component" anywhere in the name

**Comment by wardbell** [comment]
@vsavkin says "`childList<T>` is better cause the list can actually contain element refs too"

**Comment by PascalPrecht** [comment]
Maybe it's even good to have the information in there that it's an observable? `ObservableChildList`

**Comment by pkozlowski-opensource** [comment]
@rkirov is this rename still a thing? I would say now or never. But this would be massive breaking change so not sure it makes sense at this point...

**Comment by mhevery** [comment]
Do you guys have an opinion? @IgorMinar @tbosch @vsavkin. I am fine with what it is today.

**Comment by wardbell** [comment]
I prefer `childList<T>` but it's too late.  Water under the bridge. Let be.
