### ISSUE TITLE
Router Outlet won't work if router link is in ngTemplate

### ISSUE THREAD

**Issue by dreamstar-enterprises** [angular/angular#55305]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

The following HTML does not work, when you navigate to the parent component from another parent component (URL changes, but target child component doesn't load)

      
      @switch(projectSignal().dtoType){
        @case (ProjectTypes.TypeA) {
          <ng-container  *ngTemplateOutlet="typeA"></ng-container>
        }
        @case (ProjectTypes.TypeB {
          <ng-container *ngTemplateOutlet="typeB"></ng-container>
        }
        @default {
          <ng-container *ngTemplateOutlet="invalidProjectList"></ng-container>
        }
      }

      <div>
        
        <router-outlet></router-outlet>
      </div>

The following does however work (embedding the router outlet in each ng-template)

```
<ng-template #typeA>
 ....
      <a [routerLink]="[project._id]">{{ someText }}</a>

      <div>
        <!-- Router outlet for modal content -->
        <router-outlet></router-outlet>
      </div>

</ng-template>
```

Is this a bug?

### Please provide a link to a minimal reproduction of the bug

See above

**Comment by alxhub** [comment]
There is not enough code in your example for us to investigate the issue you're trying to describe. Please include a _runnable_ minimal example (ideally a Stackblitz) that clearly demonstrates the problem.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
