### ISSUE TITLE
Angular.dev show v0 instead of the latest version v17

### ISSUE THREAD

**Issue by marianocodes** [angular/angular#55303]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Dropdown to select the version is showing "v0" instead of the latest version "v17"

![Screenshot 2024-04-11 at 7 04 45 AM](https://github.com/angular/angular/assets/16544451/2bdd27de-446b-445f-aa54-a6fd483ae955)

### Please provide a link to a minimal reproduction of the bug

https://angular.dev/

**Comment by sumitparakh** [comment]
Can I take this up?

**Comment by JeanMeche** [comment]
This is probably a regression introduced by #55282

**Comment by devversion** [comment]
Thanks for the report. The PR mentioned by @JeanMeche actually fixed the version from `HEAD` to be picked up, and now surfaces that we deploy angular.dev always from `main`- without a proper versioned deployment

**Comment by devversion** [comment]
@JeanMeche we should probably keep an issue open for tracking of the deployment root cause?

**Comment by JeanMeche** [comment]
We can keep it open for it, yes !
