### ISSUE TITLE
NullInjectorError in combination with standAlone is very unclear?

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angular#55304]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler, core

### Is this a regression?

Yes

### Description

We're looking into moving to standalone, but while doing that, components that aren't provided the correct tokens are very hard to debug:
![image](https://github.com/angular/angular/assets/1098243/903bca35-9b93-4ed1-91df-59cebcbb1d1d)
sending us on wild goose chases providing anything & the kitchen sink to find out what's actually wrong

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.3
Node: 20.10.0
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 17.3.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, google-maps, language-service, material
... material-date-fns-adapter, platform-browser
... platform-browser-dynamic, router, service-worker
... youtube-player

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.3
@angular-devkit/build-angular   17.3.3
@angular-devkit/core            17.3.3
@angular-devkit/schematics      17.3.3
@angular/fire                   17.0.1
@schematics/angular             17.3.3
rxjs                            7.8.1
typescript                      5.4.4
zone.js                         0.14.4
```

**Comment by JeanMeche** [comment]
Hi, the error log is from a prod build. You should run you app in dev mode for more informations on the issue.

**Comment by JoostK** [comment]
All Angular symbols are not minified, it's just the `_a` identifier that appears to be minified, so this is indeed a development build. 

You may be able to figure out what `_a` is by clicking on the `fac.js:1:1` link at the bottom of the stack trace in the error. Alternatively, setting a debugger statement at the place where the error is thrown (click the `core.mjs:1654:27` link at the top of the stack trace) and reloading the page would allow you to inspect the stack trace interactively.

**Comment by alxhub** [comment]
Is it possible you can share a minimal reproduction (which could shed some light on how a minified name is used in a debug build?)

**Comment by LanderBeeuwsaert** [comment]
Hi @alxhub , since then we've continued on our refactor to standalone and haven't encountered it anymore. So I'm actually not sure how to repro it myself. I propose I/we close this?

**Comment by pkozlowski-opensource** [comment]
Yeh, sadly without a reproduction scenario we can only close...
