### ISSUE TITLE
NullInjectorError: No provider for Firestore2!

### ISSUE THREAD

**Issue by CrissCriss-01** [angular/angular#55309]
### Describe the problem that you experienced

I created a new Angular 17 project from scratch. Then integrated Firebase just to see if it is working -> it works! 
Then I added all my files and components, all are standalone: true
When running ng serve from vs code, now I get this error: 

R3InjectorError(Standalone[_AppComponent])[Firestore2 -> Firestore2 -> Firestore2]: 
  NullInjectorError: No provider for Firestore2!

Attached my app.component.ts file

<img width="555" alt="appComponent" src="https://github.com/angular/angular/assets/157888959/109c12fc-f11b-40bd-831a-4e8a0cafcbc4">

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
