### ISSUE TITLE
Angular 17 @for has memory leak

### ISSUE THREAD

**Issue by btiller123** [angular/angular#55316]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I have several lists of size 20 - 100 using mat-select that are auto refreshed every 30 seconds with a small amount of new data added each time.  When using @for, after several auto-refreshes the browser begins to exponentially increase ram usage to the point that the web page becomes inoperable.  When I replace @for with the previous *ngFor the problem goes away.  I've upgraded to package 17.3.4 and the problem still exists.
```
<mat-select class="selection-text" (selectionChange)="onAppContextSelectionChange($event)"(closed)="onAppContextDropdownClosed()"
                     formControlName="appContextControl" placeholder="Select context(s)"  panelWidth="fit-content" multiple>
                 <mat-select-trigger>
                      {{form.controls['appContextControl'].value?.[0] || ''}}
                     <span *ngIf="(form.controls['appContextControl'].value?.length || 0) > 1" class="additional-selection">
                      (+{{(form.controls['appContextControl'].value?.length || 0) - 1}} {{form.controls['appContextControl'].value?.length === 2 ? 'other' : 'others'}})
                      </span>
                 </mat-select-trigger>
 <!--- this @for causes memory leak -->
                  @for(context of appContextNameList; track context.name) {
                   <mat-option [disabled]="context.disabled" class="selection-text"[value]="context.name">{{context.name}}</mat-option>
                  }
<!-- problem goes away when I replace @for with this loop control 
                 <mat-option *ngFor="let context of appContextNameList" [disabled]="context.disabled" class="selection-text"[value]="context.name">{{context.name}}</mat-option>
 -->
</mat-select>
```

### Please provide a link to a minimal reproduction of the bug

See above

### Please provide the exception or error you saw

```true
See above
```

### Anything else?

The ts code is using promises to get various lists and process data in the order needed.  That said I had no issues with function/memory until I migrated the html to use the latest loop syntax @for.

**Comment by JeanMeche** [comment]
Hi, could you provide a working reproduction of this issue, either via a github repo or a stackblitz repro ?

**Comment by JoostK** [comment]
Closing as we haven't received a reproduction. Please open a new issue (or comment with a repro if this issue hasn't been autoclosed yet) with more information to help us investigate.
