### ISSUE TITLE
`swPush.requestSubscription` never resolves on Arc browser (mac os)

### ISSUE THREAD

**Issue by zip-fa** [angular/angular#55330]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

I use latest arc browser:

```
Version 1.38.0 (48670)
Chromium Engine Version 123.0.6312.123
MacOS Sonoma 14.4.1 (23E224)
```

My never-resolving promise:

```ts
  private readonly swPush = inject(SwPush, { optional: true });
  
  try {
  const sub = await this.swPush.requestSubscription({ serverPublicKey: publicKey }); // never resolves
        const jsonResult = sub.toJSON();
        } catch (err) {
        console.error(err); // never throws
        }
```
       
This code works correctly on any other chromium-based browser (chrome, vivaldi), but not on Arc.
Also tested on safari and firefox - everything works as expected.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/animations": "17.2.4",
    "@angular/cdk": "17.2.2",
    "@angular/common": "17.2.4",
    "@angular/compiler": "17.2.4",
    "@angular/core": "17.2.4",
    "@angular/forms": "17.2.4",
    "@angular/platform-browser": "17.2.4",
    "@angular/platform-browser-dynamic": "17.2.4",
    "@angular/platform-server": "17.2.4",
    "@angular/router": "17.2.4",
    "@angular/service-worker": "17.2.4",
    "@angular/ssr": "17.2.3",
```

**Comment by JoostK** [comment]
Arc is not among the officially supported browsers. I would suggest reporting this upstream with Arc, given that other browsers do work.
