### ISSUE TITLE
Angular 15 - router.events are empty with nested router outlets on page refresh

### ISSUE THREAD

**Issue by surigorantla** [angular/angular#55357]
### Which @angular/* package(s) are the source of the bug?

router, upgrade

### Is this a regression?

No

### Description

0

I have the following structure:

App component with router outlet. Layout component with router outlet (created in outlet of app component). Customers component

App component -> router outlet -> Layout component -> router outlet -> Customers component

When the user navigates from orders to customers then router.events are not empty it has the following events

NavigationStart
ChildActiationStart
ChildActivationEnd
NavigationEnd
But on Page refresh (/customers) router.events are empty

this is working fine with angular 14.3.0 . It is not working since angular 15.0.0. This is only happening with router-outlet inside router-outlet. I have a use case where i have to find subscribe to router events and look for router config path and outlet.

stackblitz url to replicate - https://stackblitz.com/edit/stackblitz-starters-9kou58?file=src%2Fapp%2Fcustomers%2Fcustomers.component.ts

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-9kou58?file=src%2Fapp%2Fcustomers%2Fcustomers.component.ts

### Please provide the exception or error you saw

```true
there is no exception but router.events are empty
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular - 15.2.0 (but this issue exists since 15.0.0)
node - 18.20.2
windows
```

**Comment by JoostK** [comment]
This is due to the following breaking change, from the [15.0 release notes](https://github.com/angular/angular/blob/main/CHANGELOG.md#1500-2022-11-16):

> Previously, the RouterOutlet would immediately instantiate the component being activated during navigation. Now the component is not instantiated until the change detection runs. This could affect tests which do not trigger change detection after a router navigation. In rarer cases, this can affect production code that relies on the exact timing of component availability.

In other words, the component can't observe its own navigation events.

The navigation from orders to customers shows the same behavior for the _first_ navigation to customers. Subsequent navigations work because of the stale subscription from the prior instance that was never unsubsribed.

Per the breaking change this is working as expected.
