### ISSUE TITLE
Angular attributes produce HTML validation errors

### ISSUE THREAD

**Issue by johnnygerard** [angular/angular#55354]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Angular uses non standard attributes which produce HTML validation errors such as:

- Attribute `_ngcontent-ng-c3135559882` not allowed on element [input](https://html.spec.whatwg.org/multipage/#the-input-element) at this point.
- Attribute `ng-reflect-model` not allowed on element [input](https://html.spec.whatwg.org/multipage/#the-input-element) at this point.

Why not use `data-*` attributes?

**Comment by JoostK** [comment]
There have been numerous issues around this, e.g. #15891 and #25355, with #40595 as an attempt to change the `_ngcontent` attributes into data attributes. Note that `ng-reflect` attributes are dev-only.

With the rise of SSR I can see some point of addressing it, but this is may not to be just a matter of changing the attribute names due to potential breakages.

**Comment by JoostK** [comment]
Labeling as "server" since this should only be relevant for SSR, as normally only the DOM has these attributes.

**Comment by johnnygerard** [comment]
My issue is not about SSR but really about HTML validation.

The argument I read in your mentioned issues is that HTML validation does not apply to the DOM, but only the source HTML.

If we agree that valid HTML is desirable, even for an Angular application, then the question becomes:
How to best validate the Angular templates?

**Comment by jelbourn** [comment]
So there's two things to think about here:
1. Should Angular templates _as authored_ be spec-valid HTML?
2. Should Angular _produce_ spec-valid HTML?

For the first, Angular templates are _based-on_ HTML syntax, but they are not "real" HTML document. An Angular template is compiled into JavaScript rendering code; Angular templates are never served directly to a browser. So, in this context, we don't consider it to be a goal for templates to be spec-valid HTML. We've even added features that are explicitly not spec-valid HTML, such as allowing self-closing elements. We think it's necessary to the evolution of the framework to be able to evolve the authoring format over time without being constrained by the syntactic space of HTML.

For the second, this is only a consideration for server-side rendering. When client-side rendering, Angular exclusively uses DOM APIs like `createElement` and `setAttribute` to produce a rendered DOM. (this is true today, but it's worth noting that this could always change in the future). When doing SSR, Angular _does_ produce an HTML document that is directly served to a browser. And for this, it's reasonable to consider whether we should strictly produce spec-valid HTML.

We've had conversations about this occasionally over the years, and the conclusion we always arrive upon is that there's just not enough of a value proposition to emitting spec-valid HTML to be worth the cost. Cost, in this context, would be:
* The churn involved with changing the existing attributes 
* The extra bytes on the wire for the `data-` prefix. 

Obviously compression can reduce concern about the bytes, but even then, we don't really see a strong enough value proposition to make spec-valid HTML an explicit goal. As a data point, [none of the top 100 sites on the internet have strictly valid HTML.](https://meiert.com/en/blog/html-conformance-2023). 

None is this is to say, of course, that we want to produce wildly out-of-spec HTML; we do want the framework to produce outputs that are as valid as is reasonable. We also want to make make sure that developers write templates that render to valid DOM structures (e.g. enforcing matching closing tags). For custom attribute names specifically, though, we don't think there's enough benefit to appending `data-` to be worthwhile.

It's also worth mentioning that there's a long (_long long long_)-running [thread on WHATWG](https://github.com/whatwg/html/issues/2271) discussing a proposal to bless a pattern for custom attribute names; it this ends up coming to fruition, it's something we would probably look into being compatible with.
