### ISSUE TITLE
 Renderer2 method that allows you to set signal inputs

### ISSUE THREAD

**Issue by StepaKyznetsov** [angular/angular#55350]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

When switching from `@Input()` to signal inputs I encountered a problem. Dynamic components created using Renderer2 and previously setting properties using the `setProperty` method throw an error. As far as I know at the moment Renderer2 does not have a method that allows you to set signal inputs of dynamic components.

### Proposed solution

add new method to Renderer2 class:
`this.renderer.setSignalInput(...)`

..or change the implementation of the `setProperty` method:
`this.renderer.setProperty(...)`

### Alternatives considered

none

**Comment by JeanMeche** [comment]
Hi, can you share a stackblitz reproduction of what you were doing ?

**Comment by JeanMeche** [comment]
Is there a reason you're not using a ViewComponentRef.createComponent instead of using the renderer ? 
The renderer is a low level API to interact with the DOM it's not meant to create compoentn.

**Comment by StepaKyznetsov** [comment]
This is how it happened historically. Thanks for feedback.

**Comment by StepaKyznetsov** [comment]
done
