### ISSUE TITLE
Improve the angular.dev dark mode

### ISSUE THREAD

**Issue by surajchopra1234** [angular/angular#55376]
### Describe the problem that you experienced

![dark](https://github.com/angular/angular/assets/126001538/69c9b5d3-2a35-43b8-b3f4-f471540dc884)

- Angular.dev docs have too low **contrast** between the text and the background.
- The background is **pitch black**, which is very irritating to the eyes.
- The links are not visually distinct enough to be easily recognizable as clickable elements.
- The blue color isn't bright enough to differentiate between itself and the pink in the code block.

**In conclusion, the dark color scheme of Angular.dev hinders readability.**

What the contrast improvement look like :

![improve](https://github.com/angular/angular/assets/126001538/ad28b89f-dd37-4e3d-9c5f-61ae90809a94)

### Enter the URL of the topic with the problem

n.a

### Describe what you were looking for in the documentation

n.a

### Describe the actions that led you to experience the problem

n.a

### Describe what you want to experience that would fix the problem

n.a

### Add a screenshot if that helps illustrate the problem

n.a

### If this problem caused an exception or error, please paste it here

```true
n.a
```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
n.a
```

### Provide any additional information here in as much as detail as you can

```true
n.a
```

**Comment by JeanMeche** [comment]
Hi, let's continue this discussion over at #52654.
