### ISSUE TITLE
ActivatedRoute in Directive: Snapshot.params are not getting updated

### ISSUE THREAD

**Issue by spirosdi** [angular/angular#55393]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

When injecting `ActivatedRoute` in a directive and trying to get the route params calling `this.activatedRoute.snapshot.params`, the `params` returned are not the ones of the current route, but the ones from the first route visited. The issue appeared after updating `@angular/core` and `@angular/router` from `17.2.2` to `17.3.1`. In `17.2.2` it works as expected, the `params` returned are the ones of the current route.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.5
Node: 20.9.0
Package Manager: npm 10.1.0
OS: darwin x64

Angular: 17.3.5
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.5
@angular-devkit/build-angular   17.3.5
@angular-devkit/core            17.3.5
@angular-devkit/schematics      17.3.5
@schematics/angular             17.3.5
rxjs                            7.5.7
typescript                      5.3.3
zone.js                         0.14.4
```

**Comment by JoostK** [comment]
Please include a runnable reproduction.

**Comment by naveedahmed1** [comment]
In my case it seems that the query string parameters are case sensitive now

```
this.queryStringSub = this._activatedRoute.queryParams.subscribe((data) => {
      console.log('Query String:', data);
      console.log('countryId:', data['countryId']);
      console.log('countryid:', data['countryid']);
});

```
Output:

```
Query String: { countryid: '162' }
countryId: undefined
countryid: 162
```

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
