### ISSUE TITLE
Produced DOM contains </input> closing tags

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#5541]
Check out this plunker: http://plnkr.co/edit/8uMBMinR6usJT4HE0QYA?p=preview

The color names show next to the radio buttons in alpha.46.  They're still in the DOM in alpha.47 but they don't display.

The apparent reason is that alpha.47 is wrapping the color names in an enclosing `</input>` tag that it generates.

alpha.46 does not generate the closing tag.

I believe that `<input>` does not require a closing tag.

This looks like a bug introduced by our custom html parser.

// reported by @wardbell

**Comment by IgorMinar** [comment]
@tbosch can you please fix this. I believe @vicb is out doing training for one more day.

**Comment by vicb** [comment]
Dup of #5528 closed by #5532
