### ISSUE TITLE
No compile time error/warning in HTML template when Signals variable used without parenthesis 

### ISSUE THREAD

**Issue by Yiding-Aya** [angular/angular#55425]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Currently, it is very error prone to use signals in template especially when refactor existing code to signal based component. It is very easy to miss adding '()' after the migration/refactoring and result issues during runtime.

`<div *ngIf="isLoadingSignal">Loading...</div>`
No compile error or warning. And it is always true. Hence Loading... always show.

Intended/Correct usage: 
`<div *ngIf="isLoadingSignal()">Loading...</div>`

I propose adding support for a compile time error or warning. This would prevent unintended usage of signal variable in HTML template.

### Proposed solution

Give a compile time error or warning as hint when signal is used in HTML template without adding (). 

### Alternatives considered

N/A

**Comment by JeanMeche** [comment]
Hi, this has been discussed in #49660 when implementing the extended diagnostic. 

There are valid cases for signals not being invoked in templates. One of them is in case of [2-way binding](https://angular.dev/guide/templates/two-way-binding) where you  pass an non-invoked signal.

**Comment by Yiding-Aya** [comment]
Thanks @JeanMeche just FYI based on my use cases - with signal based input() I never have the need to pass signal directly in template.
