### ISSUE TITLE
Fail to load docs

### ISSUE THREAD

**Issue by Ekeneuduike** [angular/angular#55431]
### Describe the problem that you experienced

every request made to api/* returns request for document failed

### Enter the URL of the topic with the problem

https://angular.io/api/elements

### Add a screenshot if that helps illustrate the problem

![Screenshot (23)](https://github.com/angular/angular/assets/112905408/4bf9cd76-8a98-4bb0-bb78-578640fd8919)

**Comment by JeanMeche** [comment]
Hi, angular.io is now in maintenance mode. We recommend you have a look at our new docs at https://angular.dev ! 

Feel free to file a new issue if you have any suggestions. Thank you for you understanding.
