### ISSUE TITLE
Broken links on ng-template reference page

### ISSUE THREAD

**Issue by FrankCoder** [angular/angular#55442]
### Describe the problem that you experienced

Clicking links to "[Structural directives](https://angular.dev/guide/structural-directives)." and "[standard template variables](https://angular.dev/guide/template-reference-variables#how-angular-assigns-values-to-template-variables)" bring up the "Page No Found 🙃" page.

### Enter the URL of the topic with the problem

https://angular.dev/api/core/ng-template#mat-tab-content-108-0

**Comment by bencodezen** [comment]
Closed via https://github.com/angular/angular/pull/55443
