### ISSUE TITLE
[tour-of-heroes/toh-pt1][Format with the UppercasePipe] adding pipe {{hero.name | uppercase }} requires "CommonModule"

### ISSUE THREAD

**Issue by k3b** [angular/angular#55445]
### Describe the problem that you experienced

i had to add CommonModule  to heroes.component.ts to make this work:

**import { CommonModule } from '@angular/common';**
...
**imports: [CommonModule],**

```
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { Hero } from '../hero';

@Component({
  selector: 'app-heroes',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './heroes.component.html',
  styleUrl: './heroes.component.css'
})
export class HeroesComponent {
  hero : Hero = {
    id: 1,
    name: 'Windstorm'
  };

}

```

I am using node v20.12.2 with "@angular/cli": "^17.3.5",

### Enter the URL of the topic with the problem

https://angular.io/tutorial/tour-of-heroes/toh-pt1

### Describe what you were looking for in the documentation

The tutorial should produce working code

**Comment by JeanMeche** [comment]
Hi, the Tour of Hero tutorial wasn't migrated to standalone. 

Also, please note that angular.io is now in maintenance mode. We recommend you having a look at the new doc site https://angular.dev. 

Thank you for your understanding.
