### ISSUE TITLE
@angular/common documentation is missing in Workspace npm dependencies' Default Dependencies section

### ISSUE THREAD

**Issue by pankajd24** [angular/angular#55458]
### Describe the problem that you experienced

I was going through the @angular/animations documentation is missing in Workspace npm dependencies's Default Dependencies section(https://angular.dev/api/common)

However, after clicking on the link, I was greeted with an empty content/404 page.

### Enter the URL of the topic with the problem

https://angular.dev/api/common

### Describe what you were looking for in the documentation

A valid documentation page should be opened

### Describe the actions that led you to experience the problem

When i clicked on this link -  @angular/common documentation is missing in Workspace npm dependencies's Default Dependencies section

<img width="901" alt="image" src="https://github.com/angular/angular/assets/164315475/d20951b3-d942-4e4f-b010-9edb537d23db">

then following 404 error is coming

<img width="899" alt="image" src="https://github.com/angular/angular/assets/164315475/1b303c21-715f-436b-b81c-9cb969d4eba0">

**Comment by JeanMeche** [comment]
We should be able to fix those links once #55338 is merged.
