### ISSUE TITLE
Consider adding the HTML entities from w3scools

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#5546]
I picked up 2.0.0-alpha.47 and immediately stumbled over en exception that `&copy;` was an unknown entity, but [w3scools](http://www.w3schools.com/html/html_entities.asp) as the top link of a search contained that entity.

Consider adding at least those entities from w3schools to [the list](https://github.com/angular/angular/blob/36a423fac8866e8a849cf3ab1c4a15d08b0ccb8c/modules/angular2/src/compiler/html_tags.ts#L7)

**Comment by PascalPrecht** [comment]
@Tragetaschen could you provide a plunk that demonstrates the error?

How about sending a PR to fix this? :)

**Comment by Tragetaschen** [comment]
Whoops, I just realized the error message actually contains the hint…

**Comment by Tragetaschen** [comment]
Going through my application, I stumble upon more occurrences. This is a rather frustrating uphill battle :-/

Plunkr: http://plnkr.co/edit/aWRgOIg6cGhrgeXVxcut?p=preview

I really get the argument for keeping the list and thus the file size small, but I also have to tell my web designer colleague that he cannot use the HTML entities he knows.

**Comment by PascalPrecht** [comment]
Correct:

```
Unknown entity "copy" - use the "&#<decimal>;" or  "&#x<hex>;" syntax ("<div>[ERROR ->]&copy;&euro;&times;</div>")
```

says that you need to use either the decimal or hexadecimal representation of the html entity. I'm sure there's a reason why alphabetic representations aren't supported. Angular has now its own HTML parser, maybe this is to support more entities instead of maintaining all possible alphabetic version.

Maybe @vsavkin can tell what the reasoning is.

**Comment by jnizet** [comment]
I just had that problem too. I understand that this looks to be a feature and not a bug, but it is **very** disappointing. 

Angular is supposed to be "HTML enhanced for web apps!", and this clearly does not enhance HTML. 

Not only `&times;` or `&quot;` are valid HTML, but they're also much easier to remember, read, understand and maintain than `&#215;` and `&#34;`. 

So, I just hope this is a temporary limitation, and not a final feature. Can anyone from the team confirm?

**Comment by vicb** [comment]
The reasoning is that we want to keep the parser size reasonable. The table of all entities would probably be bigger than the parser itself. 

That being said, we are open to adding the most common ones.

**Comment by pkozlowski-opensource** [comment]
> That being said, we are open to adding the most common ones.

Awesome, this is what i wanted to suggest :+1: 

And as soon as we gain offline compilation super-powers the parser size will be less of a concern

**Comment by PascalPrecht** [comment]
Yes, sounds very good to me too! Although "most common ones" can be very relative to everyone. How can we get stats about this?

**Comment by vicb** [comment]
I'm creating a list based on wikipedia + some other sources, hopefully it will be good enough.

**Comment by Tragetaschen** [comment]
Yay! I skimmed through the list and found the entities I missed before.
