### ISSUE TITLE
Missing built-in Pipes API page

### ISSUE THREAD

**Issue by vaurat** [angular/angular#55484]
### Describe the problem that you experienced

the page https://angular.dev/api/common#pipes leads to a HTTP 404.

The click was made on this page : https://angular.dev/guide/pipes

### Enter the URL of the topic with the problem

https://angular.dev/api/common#pipes

### Describe what you were looking for in the documentation

Pipes list.

### Describe what you want to experience that would fix the problem

Seeing a page like this one : https://angular.io/api/common#pipes.

**Comment by JeanMeche** [comment]
Hi, thank you for reporting this issue, it is already been reported at #52968
