### ISSUE TITLE
The update.angular.io does not show how to update angular material although the checkbox is checked

### ISSUE THREAD

**Issue by vajahath** [angular/angular#55482]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Although the material checkbox is checked, the steps don't include the update guide of angular material.

Check: https://update.angular.io/?l=2&v=16.0-17.0

Only this command is shown: `ng update @angular/core@17 @angular/cli@17`
Missing this step: `ng update @angular/cdk @angular/material`

![image](https://github.com/angular/angular/assets/12165822/b85ca8ba-0c4e-487f-9a7c-bc086f0c98c0)

### Please provide a link to a minimal reproduction of the bug

Check the https://update.angular.io/?l=2&v=16.0-17.0

**Comment by JoostK** [comment]
Thanks for the report, the update guide is maintained in https://github.com/angular/angular-update-guide and there's an open issue over there: https://github.com/angular/angular-update-guide/issues/259
