### ISSUE TITLE
can't get the images to show

### ISSUE THREAD

**Issue by AronFa** [angular/angular#55481]
### Describe the problem that you experienced

while following the [tutorial on your the angular website](https://angular.dev/tutorials/first-app/08-ngFor) i can't get the images to show in the app and when trying manually (in the browser i just get a 404

### Enter the URL of the topic with the problem

https://angular.dev/assets/tutorials/common/*

**Comment by JeanMeche** [comment]
Hi, this is basically the same issue as #55163, let's continue to track this issue over there.
