### ISSUE TITLE
Angular's web components not working inside AngularJS structural directives

### ISSUE THREAD

**Issue by madman-maverick** [angular/angular#55483]
### Which @angular/* package(s) are the source of the bug?

elements

### Is this a regression?

No

### Description

Custom web components created using Angular's '**createCustomElement**' do not render inside AngularJs's structural directives like ng-repeat and ng-if.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/typescript-ufccb5?file=index.ts,index.html

### Please provide the exception or error you saw

```true
In the provided stackblitz link, the Angular's web component renders correctly for the first time.

Now click on the ADD button.

The Angular's web component is removed completely from the DOM. In contrast, the web component created using just the native HTML works fine.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
The issue can be replicated with Angular 15 as well
```

### Anything else?

It was observed that ng-repeat and ng-if directives have transclude property set to 'element' (https://docs.angularjs.org/api/ng/service/$compile#known-issues). If we modify this to transclude: true, the issue is fixed.
This may not be the proper fix for the issue but might provide some initial direction on where the actual issue lies. Thanks!

**Comment by JeanMeche** [comment]
Hi, 
this is an AngularJS issue. As you probably already know, AngularJS has reached End-Of-life on Dec. 31st 2021.

The angular team does not provide any updates, security fixes or support for this framework anymore. 

Thank you for you understanding.

**Comment by madman-maverick** [comment]
The web component created using just the native HTML works fine. Only the web component created using Angular's '**createCustomElement**' has issues. So isn't this an issue with Angular's web elements ?
