### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by davijuniorn5x** [angular/angular#55496]
### Describe the problem that you experienced

When  navigating throught https://angular.dev/api/core/ng-template page, the link in the section about Template Variable is not working. Instead, leads to a Page Not Found error.

> Template Variables
> 
> <ng-template> elements can be referenced in templates using [standard template variables](https://angular.dev/guide/template-reference-variables#how-angular-assigns-values-to-template-variables).

Page Not Found 🙃
If you think this is a mistake, please [open an issue](https://github.com/angular/angular/issues/new?template=3-docs-bug.yaml) so we can fix it.

### Enter the URL of the topic with the problem

https://angular.dev/api/core/ng-template

### Describe what you were looking for in the documentation

The correct page about Template Variables.

### Describe the actions that led you to experience the problem

1. Go to https://angular.dev/api/core/ng-template;
2. On Template Variables section, click on the link [standard template variables](https://angular.dev/guide/template-reference-variables#how-angular-assigns-values-to-template-variables);
3. You might be redirected to Page Not Found error.

### Describe what you want to experience that would fix the problem

The correct page about Template Variables.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/164062333/b5a47423-19b6-4d6b-9795-837325d3abf7)

**Comment by JeanMeche** [comment]
Hi, thank you for reporting this issue. this has already been reported by  #55442 and will be fixed by #55446 when merged.
