### ISSUE TITLE
angular2/bootstrap not available under angular2.js bundle

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#5549]
I just tried out alpha `47` and it seems like `angular2/bootstrap` is not available. I am not sure where to load it from, is it àngular2/common` or `angular2/core` that I should be loading it from?

**Comment by tapas4java** [comment]
@rolandjitsu bootstrap is available at 'angular2/platform/browser'

**Comment by rolandjitsu** [comment]
@tapas4java thanks, that seems to be about right :+1:
