### ISSUE TITLE
NgZoneSchedulingMode not exported

### ISSUE THREAD

**Issue by kreuzerk** [angular/angular#55493]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

We are currently playing around with `provideZoneChangeDetection` and the new `NgZoneSchedulingMode` but it seems like the `NgZoneSchedulingMode` is not exported.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.0-next-3
Angular: 18.0.0-next-5
```

**Comment by eneajaho** [comment]
Instead of `NgZoneSchedulingMode` you can use: `ignoreChangesOutsideZone` field. 

So this can be closed.
