### ISSUE TITLE
Transpile to ES6: merge patches into traceur upstream and remove them

### ISSUE THREAD

**Issue by tbosch** [angular/angular#555]
See https://github.com/google/traceur-compiler/issues/1699
See https://github.com/google/traceur-compiler/issues/1700

Patches are added to our transpile run in https://github.com/angular/angular/blob/master/tools/transpiler/index.js and should be removed once the changes land in upstream traceur.

**Comment by tbosch** [comment]
See https://github.com/google/traceur-compiler/issues/1705 as well

**Comment by tbosch** [comment]
See https://github.com/google/traceur-compiler/issues/1706 as well

**Comment by tbosch** [comment]
See https://github.com/google/traceur-compiler/issues/1707 as well

**Comment by tbosch** [comment]
See https://github.com/google/traceur-compiler/issues/1708 as well

**Comment by tbosch** [comment]
See https://github.com/google/traceur-compiler/issues/1042 as well

**Comment by mhevery** [comment]
Obsolete
