### ISSUE TITLE
HTML Parser: "<" is not allowed in a text node

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#5550]
So in the past I could do:

```
{{ a < b ? a : b }}
```

Not anymore, it raises an issue on the `:` which makes me think that is all about b6ec238.

We need that on `ng-bootstrap` (lot of conditionals we have in there).

Check this [plunker](http://plnkr.co/edit/UM8sBfoHIirUwcouj6Qz?p=preview). If you put it on .46 it works.

**Comment by pkozlowski-opensource** [comment]
Yes, this looks like a pretty severe regression, IMO we need to fix this one before beta.

**Comment by vicb** [comment]
@yjbanov could you take a look ?

**Comment by yjbanov** [comment]
Yep, I'll take a look.

**Comment by yjbanov** [comment]
Confirmed that this is not a bug in quoted expressions. This seems to be a bug in the new HTML parser. It seems to choke on the `<` operator (likely expecting a tag there). Here's a [plunker](http://plnkr.co/edit/oYLMMqF2oxIyECiReUfa?p=preview) showing that if you move `<` into a getter the conditional expression still works.

**Comment by vicb** [comment]
Yep definitely a Parser issue - the error msg is clear about that:

```
ORIGINAL EXCEPTION: Template parse errors:
Unexpected character "'" ("
    <div>{{val1 < val2 ? [ERROR ->]'Lower' : 'Greater'}}</div>
  "): MyApp@1:25
```
