### ISSUE TITLE
https://angular.dev/guide/security not found

### ISSUE THREAD

**Issue by talesofatlantis** [angular/angular#55510]
### Describe the problem that you experienced

Came from https://angular.dev/guide/templates referring to https://angular.dev/guide/security , target not found.

![image](https://github.com/angular/angular/assets/128462239/d45f88f4-8351-4df8-87d4-ba6c3cb4b96b)

### Enter the URL of the topic with the problem

https://angular.dev/guide/security

**Comment by bencodezen** [comment]
Thanks for filing the issue @talesofatlantis! I'll make sure this is taken care of today.

**Comment by bencodezen** [comment]
Closed via https://github.com/angular/angular/pull/55514
