### ISSUE TITLE
@angular/compiler `parseTemplate` fn does not properly parse `HTML` string element text content containing `@`

### ISSUE THREAD

**Issue by watkins-joe** [angular/angular#55520]
### Is this a bug report or a feature request?

- [X] Bug Report

### Please provide the steps to reproduce the issue [Bug Report only]

1. Import the @angular/compiler package
2. Call the `parseTemplate` function with a simple HTML example like `<p>@</p>`
3. Expect `ParsedTemplate.nodes` to be empty, having not parted the HTML correctly.
4. Call the `parseTemplate` function with a simple HTML example like `<p>Test</p>`
5. Expect `ParsedTemplate.nodes` to not be empty, having parsed the HTML correctly.

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

Expected behavior:

The HTML string `<p>@</p>` should be parsed as valid HTML.

Actual behavior:

The HTML string `<p>@</p>` fails to parse correctly, as it is valid HTML.

**Comment by JeanMeche** [comment]
Since v17, the `@` character needs to be escaped as `&#64;` as it is part of the new control flow blocks.

**Comment by alxhub** [comment]
> The HTML string `<p>@</p>` should be parsed as valid HTML.

Just as a note, the Angular templating language has a lot of overlap with HTML, but it's not a goal that all valid HTML is valid template syntax, or vice versa.
