### ISSUE TITLE
foo = signal(''): if string is empty, !!foo () returns false

### ISSUE THREAD

**Issue by Kateriine** [angular/angular#55544]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

If I write this code:

```
  test = signal('');
  test2 = signal('some text');

  constructor() {
    console.log(!!this.test(), !!this.test2());
  }
```

 !!test returns false, !!test2 returns true. Sorry if my bug report is not made according to any rule, don't hesitate to tell me how to improve it, I do it rarely.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-zyuun5?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
No error. Both should return true
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.0        
Node: 18.19.0
Package Manager: npm 10.2.3
OS: win32 x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1701.0 (cli-only)
@angular-devkit/core         17.1.0 (cli-only)
@angular-devkit/schematics   17.1.0 (cli-only)
@schematics/angular          17.1.0 (cli-only)
```

**Comment by JeanMeche** [comment]
Empty string is falsy, this is not related to signals.
