### ISSUE TITLE
Form input mask provided by the framework

### ISSUE THREAD

**Issue by guiseek** [angular/angular#55552]
### Which @angular/* package(s) are relevant/related to the feature request?

@angular/forms

### Description

Except for tiny apps, practically all others need to mask form inputs, such as currency, phone number, identity documents, etc.

the framework could offer this feature and help teams stop wasting time choosing third-party libraries, as few actually do a good job, in addition to many of them abandoning the project and contributing to the project becoming legacy

### Proposed solution

It could be a directive within the @angular/forms package. I don't know, here's my suggestion as a long-time dev in the community

thank you for your attention

### Alternatives considered

An alternative would be for the framework to choose a third, but official, library, as has already been done with other packages, such as flex layout, universal, etc.

**Comment by JeanMeche** [comment]
Hi, this kind of components is part of the scope of CDK/Material. 

There is already a related issue on the repo : angular/components#7645

**Comment by guiseek** [comment]
> Hi, this kind of components is part of the scope of CDK/Material.
> 
> There is already a related issue on the repo : [angular/components#7645](https://github.com/angular/components/issues/7645)

Did you close my issue because another one was open almost 8 years ago? really?

**Comment by JeanMeche** [comment]
We don't keep duplicate issues and refer to the oldest one. Thank you for your understanding.

**Comment by guiseek** [comment]
> We don't keep duplicate issues and refer to the oldest one. Thank you for your understanding.

I don't see these as duplicate issues, from what I understand, that issue refers to date, and as far as I know, @angular/material's Datepicker already has ways to resolve these cases.

I have not mentioned dates at any point, as in my view this is not a problem. Values such as currency, number of phones, etc. are a real problem and there is no alternative provided by the framework, as is the case with datepicker

https://github.com/angular/angular/assets/5638096/b895bcbf-a2e8-49df-af70-04894f0dbbed

**Comment by JeanMeche** [comment]
OP mentionned dates, but the issue covers any kind of text-mask.

**Comment by guiseek** [comment]
OK, I understand and agree. but this is something trivial for a framework, right?

I could give it the attention that something so used would deserve :)
