### ISSUE TITLE
Set ViewEncapsulation per module

### ISSUE THREAD

**Issue by heitorgiacomini** [angular/angular#55567]
### Description

Set ViewEncapsulation per module

### Proposed solution

Set ViewEncapsulation per module

### Alternatives considered

Set ViewEncapsulation per module

**Comment by JoostK** [comment]
Please see all prior discussions around this topic:

- https://github.com/angular/angular/issues/12251#issuecomment-872613835
- https://github.com/angular/angular/issues/18346#issuecomment-881054664
- https://github.com/angular/angular/issues/53285#issuecomment-1838545692

Closing as this isn't something we'd want to pursue at the moment, as it contradicts with local compilation goals.

**Comment by heitorgiacomini** [comment]
@JoostK All were closed.
