### ISSUE TITLE
ErrorNG8001 ${element} is not know element

### ISSUE THREAD

**Issue by KyryllSokolov** [angular/angular#55576]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler

### Is this a regression?

Yes

### Description

This is not my first time having pretty stupid ERROR using new Angular CLI 17.3.5

Here is my package.json
```javascript
{
  "name": "restaurants-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^17.2.0",
    "@angular/common": "^17.2.0",
    "@angular/compiler": "^17.2.0",
    "@angular/core": "^17.2.0",
    "@angular/forms": "^17.2.0",
    "@angular/platform-browser": "^17.2.0",
    "@angular/platform-browser-dynamic": "^17.2.0",
    "@angular/router": "^17.2.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.2.3",
    "@angular/cli": "^17.2.3",
    "@angular/compiler-cli": "^17.2.0",
    "@types/jasmine": "~5.1.0",
    "autoprefixer": "^10.4.19",
    "jasmine-core": "~5.1.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.3",
    "typescript": "~5.3.2"
  }
}
``` 
I am not using standalone components , just regular NgModule with standard configuration, here is my module code( this is the only module and there is no other components) 
```typescript
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from "@angular/router";
import { BrowserModule } from "@angular/platform-browser";
import { MainComponent } from './pages/main/main.component';
import { CatalogComponent } from './pages/catalog/catalog.component';
import { RestaurantTileComponent } from './components/restaurant-tile/restaurant-tile.component';
import { ProductComponent } from './components/product/product.component';
import { PageLoaderComponent } from "./components/page-loader/page-loader.component";
import { routes } from "./app.routes";



@NgModule({
  declarations: [
    MainComponent,
    CatalogComponent,
    RestaurantTileComponent,
    ProductComponent,
    PageLoaderComponent
  ],
  imports: [
    CommonModule,
    BrowserModule,
    RouterModule.forRoot(routes)
  ]
})
export class AppModule { }
``` 
Here is a code of template where I have an error: 
```html
<div class="w-full">
  <ng-container *ngIf="isLoading | async">
    <app-page-loader></app-page-loader>
  </ng-container>

  <ng-container *ngIf="!(isLoading | async)">
    <div>Hello</div>
  </ng-container>
</div>
``` 
```typescript
import { Component, OnInit } from '@angular/core';
import { RestaurantsService } from "../../services/restaurants.service";
import { PageLoaderService } from "../../services/page-loader.service";
import { Observable } from "rxjs";

@Component({
  selector: 'app-main',
  templateUrl: './main.component.html',
  styleUrl: './main.component.scss'
})
export class MainComponent implements OnInit {
  isLoading: Observable<boolean>;
  constructor(
    private restaurantsService: RestaurantsService,
    private pageLoader: PageLoaderService
  ) {
    this.isLoading = this.pageLoader.getLoader();
  }

  ngOnInit() {
    this.restaurantsService
      .getRestaurantsList()
      .subscribe(res => {
      console.log(res);
    });
  }

}
``` 
There is nothing wrong I believe with the module structure or with component itself, everything looks fine but when I try to run dev server with ng serve - I have this strange error which makes no sense
`✘ [ERROR] NG8001: 'app-page-loader' is not a known element:
1. If 'app-page-loader' is an Angular component, then verify that it is part of this module.
2. If 'app-page-loader' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. [plugin angular-compiler]

    src/app/pages/main/main.component.html:3:4:
      3 │     <app-page-loader></app-page-loader>
        ╵     ~~~~~~~~~~~~~~~~~

  Error occurs in the template of component MainComponent.

    src/app/pages/main/main.component.ts:8:15:
      8 │   templateUrl: './main.component.html',
        ╵`

I have doble checked everything and literally don't know what is wrong with this place, if the component is provided. Would really appreciate any ideas or instructions, thanks in advance!

### Please provide the exception or error you saw

```true
`✘ [ERROR] NG8001: 'app-page-loader' is not a known element:
1. If 'app-page-loader' is an Angular component, then verify that it is part of this module.
2. If 'app-page-loader' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. [plugin angular-compiler]

    src/app/pages/main/main.component.html:3:4:
      3 │     <app-page-loader></app-page-loader>
        ╵     ~~~~~~~~~~~~~~~~~

  Error occurs in the template of component MainComponent.

    src/app/pages/main/main.component.ts:8:15:
      8 │   templateUrl: './main.component.html',
        ╵`
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.5
Node: 20.11.1
Package Manager: npm 10.2.4
```

**Comment by KyryllSokolov** [comment]
@JoostK Good part of the day Joost, here is a content of the PageLoaderComponent 
```html
<div class="flex w-full h-full">
  <div>
    <h1 class="text-3xl">Loading data</h1>
  </div>
  <div>
    <span class="loader"></span>
  </div>
</div>
``` 
```typescript
import { Component } from '@angular/core';

@Component({
  selector: 'app-page-loader',
  templateUrl: './page-loader.component.html',
  styleUrl: './page-loader.component.scss'
})
export class PageLoaderComponent {

}
``` 

literally nothing inside. I have many years of experience working with Angular and this kind of thing is happening only with 17th version. All the stuff generated using Angular CLI and actually there is nothing much inside of components yet , that's why actually I am confused what is going on. Could you please advise me how should I provide you something to reproduce it on your side?

**Comment by JoostK** [comment]
That looks okay. A Github repo with minimal amount of code necessary to reproduce would be appreciated.

Also, what OS are you using? May not be relevant but it's not included in the issue, and it may make a difference.

**Comment by KyryllSokolov** [comment]
I am using MacOS Sonoma 14.2.1, here is my repo with the same code I have right now https://github.com/KyryllSokolov/restaurants

@JoostK it's really looks fine, coz there is almost nothing inside

**Comment by geromegrignon** [comment]
Hello @KyryllSokolov , the problem is due to **AppModule**: it's never used in your application.
You probably noticed there was no AppModule file by creating your project, as it used to work with `ng new`.

This file was consumed in the `main.ts` entry file.
But by creating new Angular projects, it now uses the Standalone API now, both for components and the whole application.
It removes the requirement to use Modules in the applications ,relying on the Standalone API to define the context for each piece of the application.

AppModule is never used in your application, so any change upon it won't resolve your situation.

Here the problem appears because AppComponnt doesn't know PageLoaderComponent.
You can fix it by adding this component to the **imports** array of your AppComponent:

```ts
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'restaurants-app';
}
```

**Comment by JoostK** [comment]
Oooh, I see, you're not actually using `AppModule` anywhere and since `tsconfig.app.json` specifies `"files": ["main.ts"]`, the "app.module.ts" file is never included into the compilation at all and Angular has no knowledge that it exists. This isn't an error because components are not required to be declared in an NgModule even if no `standalone: true` prop is present.

So this is working as expected, unfortunately.

**Comment by KyryllSokolov** [comment]
@geromegrignon Thanks a lot for the explanation , didn't know that about new way of doing things. Could you please explain me why you would not recommend using Modules anymore ? I understand the pros why standalone components are good in many cases, especially when you want to have some component in several modules , but I didn't get the point about the recommendation.

**Comment by JoostK** [comment]
Is there such recommendation?

**Comment by KyryllSokolov** [comment]
Yeap , before the code for main.ts there is a comment "If you want to stick with Modules (**which i would not recommend**), you need to update your main.ts file to consume your AppModule"

**Comment by geromegrignon** [comment]
Besides the pros you highlighted, Composition APi and defer features are only made available to standalone elements.

**Comment by KyryllSokolov** [comment]
@geromegrignon Thanks a lot mate , you really helped, @JoostK thank you too for your time and desire to help. Really love how our community is built. Btw it was really nice intro to Angular 17th ;) 
The problem is solved.
