### ISSUE TITLE
Missing code blocks in usage notes. 

### ISSUE THREAD

**Issue by HymanZHAN** [angular/angular#55572]
### Describe the problem that you experienced

Usage notes/examples are missing in `Injector`'s API doc.

### Enter the URL of the topic with the problem

https://angular.dev/api/core/Injector?tab=usage-notes

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/26806995/07a41d1c-146e-4a9b-bb6a-fdc75bd7a1ea)

**Comment by JeanMeche** [comment]
I've renamed this issue as it is global to any API doc that relies of the external  code example files.

**Comment by JeanMeche** [comment]
Let's continue tracking this with #56068
