### ISSUE TITLE
ErrorHandler docs don't have standalone alternative

### ISSUE THREAD

**Issue by mgechev** [angular/angular#55579]
### Describe the problem that you experienced

We haven't added docs on how to use ErrorHandler without NgModules https://angular.dev/api/core/ErrorHandler?tab=usage-notes

Add documentation on how to use ErrorHandler without NgModules in the app config:

```ts
export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    { provide: ErrorHandler, useClass: GlobalHandler },
  ],
};
```

**Comment by fredsa** [comment]
Please also document how to add an `ApplicationConfig` to an app that doesn't have one.
- https://angular.dev/api/platform-browser/ApplicationConfig# is deprecated, but doesn't link to its replacement
- https://angular.dev/api/core/ApplicationConfig# doesn't say how to add one.

**Comment by JeanMeche** [comment]
@fredsa  While better linking would indeed be better, what you are looking for is here : https://angular.dev/api/platform-browser/bootstrapApplication
