### ISSUE TITLE
Page not found for https://angular.dev/assets/tutorials/common

### ISSUE THREAD

**Issue by mazzelman** [angular/angular#55596]
### Describe the problem that you experienced

Following the "Build your first Angular App" tutorial i should see the picture of the example-house.jpg. But the page is not found. The direct link says page not found, and also https://angular.dev/assets/tutorials/common/.

### Enter the URL of the topic with the problem

https://angular.dev/assets/tutorials/common/example-house.jpg

**Comment by JeanMeche** [comment]
Hi, this issue has already been reported, let's continue the tracking with #52794.
