### ISSUE TITLE
optionalChainNotNullable does not seems to work

### ISSUE THREAD

**Issue by vupham30** [angular/angular#55604]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I enable `optionalChainNotNullable: 'errors'` but it does not seems to catch the errors. When I build it, there is no errors, also vscode does not show any errors or warning.

### Minimal Reproduction

Define an schema with optional property, try to access that property in html template.

### Your Environment

```text
Angular CLI: 17.2.3
Node: 20.10.0
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 17.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1702.3
@angular-devkit/build-angular      17.2.3
@angular-devkit/core               17.2.2
@angular-devkit/schematics         17.2.3
@angular/cdk                       17.2.1
@angular/cli                       17.2.3
@angular/elements                  17.2.3
@angular/flex-layout               15.0.0-beta.42
@angular/localize                  17.2.3
@angular/material                  17.2.1
@angular/material-moment-adapter   17.2.1
@schematics/angular                17.2.3
rxjs                               7.8.1
zone.js                            0.14.4
```

**Comment by JeanMeche** [comment]
Extended diagnostics will emit when strictTemplates is enabled. Can you check if this is the case ?

**Comment by vupham30** [comment]
@JeanMeche yes I did enable strictTemplates, here is my configurations: 

`"angularCompilerOptions": {
    "strictTemplates": true,
    "extendedDiagnostics": {
      "checks": {
        "optionalChainNotNullable": "error",
      }
    }
  }`

**Comment by JoostK** [comment]
Please provide actual code for which you expect an error to be reported. Without it, we have no insight into what is going on making this issue unactionable.

**Comment by vupham30** [comment]
So in the component I define a property like this: 

`params: {
    id: string
    name: string
    address?: {
      street: string,
      city: string
    }
  } = {
    id: '1',
    name: 'John'
  };`

and in the template I have this `{{params.address.street}}`.

Neither compiler or VSCode raise any errors but the page is crashed and nothing can display.

**Comment by JoostK** [comment]
That's the opposite of what `optionalChainNotNullable` is for, the extended diagnostics only detects unnecessary usages of `?.` operators.

You may not have `strictNullChecks` enabled (a TypeScript option).

Please do share a reproduction if you think there is a problem, as just snippets are not sufficient to determine what is going on.
