### ISSUE TITLE
Router config "enableViewTransitions" and "Aw, Snap!" error

### ISSUE THREAD

**Issue by blueiceprj** [angular/angular#55627]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

A few weeks ago, we enabled a new feature in Angular, "enableViewTransitions", and a few days later, our users reported that they started receiving the following error in many browsers. "Aw, Snap!" error with the code "5". We initially investigated whether there was a software error and could not see any messages or errors on either the console or the network on devtools. I encountered this error 1-2 times in the development environment. That's why we thought it was a browser-related error and suggested solving the problem with f5. But it was annoying. Then we noticed this change and decided to roll it back. After the change, we did not receive any messages from users that they no longer received this error and the problem was resolved.

### 

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.3.6
Node: 18.18.2
Package Manager: npm 9.8.1
OS: darwin x64

Angular: 17.3.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                              Version
--------------------------------------------------------------
@angular-devkit/architect            0.1703.6
@angular-devkit/build-angular        17.3.6
@angular-devkit/build-ng-packagr     0.1002.0
@angular-devkit/core                 17.3.6
@angular-devkit/schematics           17.3.6
@angular/cdk                         17.3.6
@angular/cli                         17.3.6
@angular/material                    17.3.6
@angular/material-date-fns-adapter   17.3.6
@angular/youtube-player              17.3.6
@schematics/angular                  17.3.6
rxjs                                 7.8.1
typescript                           5.4.5
zone.js                              0.14.5
```

**Comment by JeanMeche** [comment]
View Transition are an experimental browser feature. `Code 5` is the Chromium browser crashing. You should repport that issue to the chromium browser.

**Comment by blueiceprj** [comment]
I know their answer about that. There was no message or error. Suddenly this error appeared. I just shared an experience I had. I didn't think it could be this much of a problem.

Google answer:

https://support.google.com/chrome/answer/95669?hl=en&co=GENIE.Platform%3DDesktop

**Comment by atscott** [comment]
As @JeanMeche mentioned, this error is thrown by the browser. Without any additional information or reproduction, we can’t help any further than pointing you to the [correct place to file an issue against view transitions](https://github.com/w3c/csswg-drafts/labels/css-view-transitions-1). Note that they’re likely going to need a reproduction as well to make any progress on an investigation. 

Closing, as this issue is outside of Angular.
