### ISSUE TITLE
Dead area for scrolling: Column for right hand menu

### ISSUE THREAD

**Issue by bjornte** [angular/angular#55649]
Compare [angular.io](https://angular.io/guide/what-is-angular) to [getbootstrap.com](https://getbootstrap.com/docs/5.3/getting-started/introduction/) while on a widescreen desktop: On angular.io, when mousing over the column that holds the right hand menu, you can not scroll while using a touchpad (two finger gesture on a Mac).

Motivation to fix: Angular is for creating front ends, so the angular.io web site should showcase best practices.

URL: [what-is-angular](https://angular.io/guide/what-is-angular)

**Comment by JeanMeche** [comment]
Angular.io is now in maintenance mode, we won't make any content or structural change to it. 

Feel free to have a look at the news docs at https://angular.dev and if you have some suggestion, please open a new issue. Thank you.
