### ISSUE TITLE
Error messages are not descriptive

### ISSUE THREAD

**Issue by yfain** [angular/angular#5564]
On multiple occasions I've seen messages that are not giving a clue to what was the reason of the error.

Just now I got the runtime message  "EXCEPTION: Error trying to diff '[object Object]' in [null]".  Go figure.  After googling I found three cases with similar messages in Angular's test classes and one in the executable code. All of them had something to do with collections, for example:

```    if (!isListLikeIterable(collection)) {
      throw new BaseException(`Error trying to diff '${collection}'`);
    }```

I got this error in my app that was processing a collection, but it was not clear from the original error message. In this case the error message should include the word  "collection".

This was just one case, but error handling in Angular clearly has room for improvement.

**Comment by thosakwe** [comment]
I agree. Usually when I get this message, it's when I'm using ngFor on something that is not a collection, i.e. an object or null.

**Comment by zoechi** [comment]
See also #7481

**Comment by pkozlowski-opensource** [comment]
General error message improvement is currently tracked in #7481.

@yfain @thosakwe if you've got specific error messages that you think should be improved please open separate, focused issues, describing:
* condition under an error with confusing error message is thrown
* proposed error message.

Thank you!

**Comment by Sironmani** [comment]
while I am using primeng Multiselect dropdown ...I got this error  (Error trying to diff '') ..i can't bind the data from service.Please give me solution as early as possible

**Comment by zoechi** [comment]
@Sironmani You can hardly expect any support for almost no information.
This is the wrong place to ask anyway.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
