### ISSUE TITLE
More user testing of angular.io

### ISSUE THREAD

**Issue by bjornte** [angular/angular#55650]
I'm new to Angular, which assumedly makes me a primary audience member for [angular.io/start](https://angular.io/start).
For my purposes, the documentation is a little “buggy”, indicating that it is not thoroughly user tested. E.g.:

- Running the suggested script `ng generate component product-alerts ` yields two lines with `standalone` and `imports` that must be commented out.
- In [start-routing](https://angular.io/start/start-routing), when adding the `ngOnInit()` method, it is not stated that this must be inside `export class ProductDetailsComponent`. E.g., this could be indicated by adding a comment such as `// The ngOnInit() method goes here` in the preceding code snippet.

But in general, as with the [previous issue](https://github.com/angular/angular/issues/55649) I just reported, this indicates that the site could benefit from some additional user testing. So my feedback is not specifically about the two points above, but rather to recruit novice Angular users (akin to myself) and have them run through the tutorials as part of the documentation process.

(Also, the stackblitz.com code yields a lot of console errors; this would be nice to avoid in order to focus on the mistakes I am personally responsible for 😊)

URL: [angular.io/start](https://angular.io/start)

**Comment by eneajaho** [comment]
Hello @bjornte 
Angular has new docs that you can find at [angular.dev](https://angular.dev) which should include a revamped getting started guide and rewritten guides for all the angular topics for devs new to Angular.

**Comment by JeanMeche** [comment]
Also, angular.io is now in maintenance mode, we won't provide any changes (like standalone based docs). 

If you have any suggestion on the new docs, feel free to open issues, thank you for your understanding.

**Comment by bjornte** [comment]
Thanks for the feedback, most appreciated. Perchance angular.io could more prominently suggest that users can migrate to angular.dev? E.g. consider the way Bootstrap has legacy documentation, but uses a banner to make users aware of more recent versions.

**Comment by JeanMeche** [comment]
This will be added very soon, alonside the v18 later this month.
