### ISSUE TITLE
external typings are not referenced anymore

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#5565]
Probably this is by design, but typing such as zone.js, es6-shim and so on are not referenced anymore. You can easily get around this by installing these typings yourself, but there seems to be some issues with a `BrowserNodeGlobal` that is missing and zone.js referencing a es6-promise which if installed will conflict with es6-shim.

**Comment by IgorMinar** [comment]
I believe that this was fixed in a48. Can you confirm or provide steps to reproduce with a48?

**Comment by rolandjitsu** [comment]
Yeah, it has been fixed :+1: 

Just one note here, because Angular 2 already includes things like es6-promise and because I do not import `angular2/core` anywhere in my e2e tests, the TS compiler is throwing errors about missing typings. Of course, if I do include the typings, then I get the duplicate typings messages.

**Comment by alexeagle** [comment]
The duplicate identifier problems were fixed as of beta.6. You indicated this is fixed, so closing.
