### ISSUE TITLE
Pass components through a properties

### ISSUE THREAD

**Issue by Aetet** [angular/angular#5566]
In react there's usefull mechanism which allow you to pass any type of View element  inside another element:
```js
// And dropdown draw userlist, after that dropdown just composite view elements together
<Dropdown list={UserList} state={state} />
```

Or even more powerfull:
```js
function getUserList(state, filter) {
   return <UserList state={state.users} filter={filter} />
}
<Dropdown list={getUserList} state={state} />
```

This composition much helps to build reusable view libraries. 

How to achieve the same behaviour with Angular 2? Working code examples would be very pleased.

**Comment by pkozlowski-opensource** [comment]
You can pass `ComponentFactory` and inside your component:
* call `create()` 
* attach created component into a `ViewContainer`

So it is very much doable with ng2 today.

**Comment by zoechi** [comment]
My answer at http://stackoverflow.com/questions/36325212/angular-2-dynamic-tabs-with-user-click-chosen-components/36325468#36325468 demonstrates such a use case with Plunker.
