### ISSUE TITLE
angular tutorial image file missing

### ISSUE THREAD

**Issue by robidas** [angular/angular#55670]
### Describe the problem that you experienced

I am following the Angular 17 tutorial, and an image URL is provided, but it results in a Page Not Found error. The image URL in the tutorial is https://angular.dev/assets/tutorials/common/example-house.jpg
The tutorial step is at this URL https://angular.dev/tutorials/first-app/06-property-binding

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app/06-property-binding

### Describe what you were looking for in the documentation

I am following a tutorial at https://angular.dev/tutorials/first-app

### Describe the actions that led you to experience the problem

I'm attempting to add interpolation to a components template as described here https://angular.dev/tutorials/first-app/07-dynamic-template-values

### Describe what you want to experience that would fix the problem

please provide the images at the expected locations so that I can complete the tutorial

**Comment by JeanMeche** [comment]
Hi, this is basically the same issue as #55163, let's continue to track this issue over there.
