### ISSUE TITLE
signal(Observable<T>) to signal<T>() operator

### ISSUE THREAD

**Issue by MGX-CODING** [angular/angular#55675]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Here is a quick example of the requested feature (of course it has no value in itself) : 

```typescript
  $control = signal(new FormControl(''));

  $valueChanges$ = computed(() => this.$control().valueChanges);

  valueChanges$ = toObservable(this.$valueChanges$).pipe(switchMap((v) => v));

  $valueChanges = toSignal(this.valueChanges$);
```

[STACKBLITZ](https://stackblitz.com/edit/stackblitz-starters-j5yhr8?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fmain.ts%3AL19&template=node&title=Angular%20Starter)

### Proposed solution

```typescript
  $control = signal(new FormControl(''));
  $valueChanges = transmuted(() => this.$control().valueChanges);
```

### Alternatives considered

The code of the example itself.

This is not the first time I have the need for something like this, and as far as I'm aware, there is no easy way to do something similar (please correct me if I'm wrong)

**Comment by jnizet** [comment]
I personally find using toSignal() and toObservable() perfectly reasonable here since you precisely want to transform a signal to an observable and vice-versa.

The code could be simplified to

```
const control = signal(new FormControl(''));
const value = toSignal(toObservable(control).pipe(switchMap(c => c.valueChanges)));
```

**Comment by MGX-CODING** [comment]
> I personally find using toSignal() and toObservable() perfectly reasonable here since you precisely want to transform a signal to an observable and vice-versa.
> 
> The code could be simplified to
> 
> ```
> const control = signal(new FormControl(''));
> const value = toSignal(toObservable(control).pipe(switchMap(c => c.valueChanges)));
> ```

It is indeed clearer, thank you for that, but still, don't you think it looks complicated ?

**Comment by jnizet** [comment]
No. It's very explicit.

**Comment by MGX-CODING** [comment]
Well on that we agree, maybe I should have said concise then ... Can this issue remain open, just to have more opinions ?

(Thanks again for the more concise way !)

**Comment by kbrilla** [comment]
@MGX-CODING  mayby this will cover Your needs https://ngxtension.netlify.app/utilities/signals/derived-async/

**Comment by JoostK** [comment]
We were discussing just now and our interpretation is that 1) this particular case is because the forms API does not provide a signal for the current value, and 2) that it's more appropriate to convert to RxJS earlier in this case to avoid the awkward `switchMap` transform:

```ts
  $valueChanges = toSignal(toObservable(this.$control).pipe(
    switchMap(control => control.valueChanges),
  ));
```

That has the same output type.

We don't otherwise see the need for a flattening operator from `Signal<Observable<T>>` to `Signal<T>`.

**Comment by MGX-CODING** [comment]
Just so we're clear, this was one example amongst others, this is not related to form controls in any way, shape or form. 

But thank you for the feedback on the proposition still, much appreciated !
