### ISSUE TITLE
Add WritableComputed to allow computed with write operations

### ISSUE THREAD

**Issue by Harpush** [angular/angular#55673]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Revival with use case of #50498

Currently `signal` produces a writable signal.
Currently `computed` produces a non writable signal.
What I am missing is a `writableComputed`.

Use case example:
I have a required input called `value` but inside the component I can edit this value without affecting the outside. At the end an apply button is clicked and I emit the new value via an output.
Something like this:
```ts
class Test {
  value = input.required<string>();
  tempValue = signal(/*??*/);
  commit = output<string>()

  onEdit(newValue: string) {
    this.tempValue.set(newValue);
  }

  onApply() {
    this.commit.emit(this.tempValue());
  }
}
``` 
The first problem is `tempValue` isn't based on `value`.
The second problem is when `value` is changed from outside. At this point I wish to discard  `tempValue` and start fresh with the new `value`.
If I had `writableComputed` I could do:
```ts
tempValue = writableComputed(() => this.value());
```
Which means anytime `value` changes it becomes the new `tempValue` value. If `tempValue` is edited the new edit is the `tempValue` new value until something gets changed in `value`.

### Proposed solution

A new `writableComputed` which tracks the value inside based on the writeable part and will get reset each time the computed function runs to what it creates.
Examples:
```ts
const a = signal(7);
const b = writableComputed(() => a() + 1);
// b is 8
```
```ts
const a = signal(7);
const b = writableComputed(() => a() + 1);
b.set(9);
// A design question - 8 or 9
```
```ts
const a = signal(7);
const b = writableComputed(() => a() + 1);
a.set(11);
b.set(9);
// A design question - 12 or 9
```
```ts
const a = signal(7);
const b = writableComputed(() => a() + 1);
// b is 8
// Later
b.set(10)
// b is 10
// Later
a.set(20);
// b is 21
```

### Alternatives considered

Using effect. The downside is with required inputs.
```ts
tempValue = signal<string | undefined>(undefined);
effect(() => this.tempValue.set(this.value()), {allowSignalWrites: true});
```
This will result in `tempValue` having `undefined` initially and for example in `ngOnInit` it will still have `undefined` although `value` already have the actual value set. Also a computed will have its value set too.
using `writableComputed` in `ngOnInit` will have the correct computed value.

Another option is that scenario hints that something I am doing is wrong from the basis and I would like to hear better suggestions how to handle it.

**Comment by json-derulo** [comment]
Did you also consider splitting up your computation and writing logic? Something like the following:

```typescript
class Test {
  value = input.required<string>();
  writableValue = signal<string | undefined>(undefined);
  computedValue = computed(() => this.writableValue() ?? this.value() + 1);
}
```

IMHO Angular shouldn't offer a signal which is both computed and writable. It leads to ambiguity, you will never know whether the current value  of the signal comes from the computation or from a signal write. Also when the input is updated, the previously set value will be reset, which I assume would be an unintended side effect.

**Comment by Harpush** [comment]
> Did you also consider splitting up your computation and writing logic? Something like the following:
> 
> ```ts
> class Test {
>   value = input.required<string>();
>   writableValue = signal<string | undefined>(undefined);
>   computedValue = computed(() => this.writableValue() ?? this.value() + 1);
> }
> ```
> 
> IMHO Angular shouldn't offer a signal which is both computed and writable. It leads to ambiguity, you will never know whether the current value of the signal comes from the computation or from a signal write. Also when the input is updated, the previously set value will be reset, which I assume would be an unintended side effect.

This won't reset neither `writableValue` nor `computedValue` when `value` changes though...
I will still need an effect to reset `writableValue` when `value` changes.

**Comment by alxhub** [comment]
```typescript
class Test {
  value = input.required<string>();
  writableInnerValue = computed(() => signal(this.value()));

  // helper to get rid of the double read
  innerValue = () => this.writableInnerValue()();
  
  setInnerValue(value: string): void {
    this.writableInnerValue().set(value);
  }
}
```

**Comment by JoostK** [comment]
Or pulled out into a helper function:

```ts
interface MirrorSignal<T> {
  (): T;

  set(value: T);
}

function mirror<T>(outer: Signal<T>): MirrorSignal<T> {
  const inner = computed(() => signal(outer()));
  const mirror: MirrorSignal<T> = () = inner()();
  mirror.set = (value: T) => untracked(inner).set(value);
  return mirror;
}
```

**Comment by Harpush** [comment]
Thanks @alxhub and @JoostK! 
That seems to answer it mostly although that's not a real signal and I need to implement update fn too.
But it's probably the best I can get :)

**Comment by mauriziocescon** [comment]
Hey! 

Well, I assume the most updated answer to this issue would be something like: [once this PR](https://github.com/angular/angular/pull/56501) is merged, just use `effect` to sync the your `signal` with your `input` changes. 

- `effect` will run before `ngOnInit`, 
- no need to have `allowSignalWrites: true`, 
- we can retain all the benefits of using `signals` (compared to the helper func). 

So the code would be something like: 
```typescript
class Test {
  value = input.required<string>();

  tempValue = signal('');
  valueWatcher = effect(() => this.tempValue.set(this.value()));  // tempValue defined in onInit

  // ...
}
```


Assuming what I wrote is more or less correct, I still have the feeling we might miss something... as soon as (for example) the input(s) gets more complicated. Here is a basic example: 

```typescript
@Component({
  template: `

    // User (potential complex object)
    <div>user: {{ user() | json }}</div>

    <input type="text" [ngModel]="name()" (ngModelChange)="changeName($event)"/>
    <div>{{ name() }}</div>

    <input type="text" [(ngModel)]="signalName"/>
    <div>{{ signalName() }}</div>
  `,
})
export class ViewEditUser {
  user = signal<{ name: string }>({ name: 'John' }); // consider it readOnly

  name = mirror(() => this.user().name); // helper func above

  signalName = signal('');
  signalNameWatcher = effect(() => this.signalName.set(this.user().name); // already adapted
  
  // ...
}
```
https://stackblitz.com/edit/stackblitz-starters-bw7fmd?file=src%2Fmain.ts

Just to make things easier, I'm using a simple `ngModel` (but you can mentally replace it with a component having a `model input`... so, we're not in ng-form land). 

In such cases, I'd basically like to define a writable signal that gets updated any time `user` (or something else) changes, ideally with one assignment. As I see it: 
- helper func: it's not a signal (no signal benefits), 
- effect: yeah, it works... but imagine splitting `user` in many parts: you'll end up with lots of annoying code. 

Just for clarity: this is not a big problem... it's mostly adding some practical reasons in favour of considering `writableComputed` (or any other name) for not trivial cases. I'm quite sure it would be handy. 

As usual thanks a lot!

**Comment by eneajaho** [comment]
> Or pulled out into a helper function:
> 
> ```ts
> interface MirrorSignal<T> {
>   (): T;
> 
>   set(value: T);
> }
> 
> function mirror<T>(outer: Signal<T>): MirrorSignal<T> {
>   const inner = computed(() => signal(outer()));
>   const mirror: MirrorSignal<T> = () = inner()();
>   mirror.set = (value: T) => untracked(inner).set(value);
>   return mirror;
> }
> ```

Probably this will copied over to ngxtension 😅

**Comment by mauriziocescon** [comment]
I guess you can support `update` as well: 

``` typescript
interface MirrorSignal<T> {
  (): T;
  set(value: T): void;
  update(updateFn: (value: T) => T): void;
  // asReadonly(): Signal<T>; ??? once you call it, you get one signal(expression())
}

function mirror<T>(expression: () => T): MirrorSignal<T> {
  const inner = computed(() => signal(expression()));
  const mirror: MirrorSignal<T> = () => inner()();
  mirror.set = (value: T) => {
    const newS = untracked(inner);
    return newS.set(value);
  };
  mirror.update = (updateFn: (value: T) => T) => {
    const newS = untracked(inner);
    return newS.update(updateFn);
  };
  return mirror;
}
```

But don't think there's a way for `asReadonly` (a bit tired here... so I could be completely wrong). If there's no way, you end up with a hybrid thing! 😅

And not totally sure `asReadonly` would be the only difference compared to a regular `(w)signal`! 

My 2 cents!

**Comment by pkozlowski-opensource** [comment]
Update for anyone tracking this issue - we do see number of use-cases (similar to the [originally exposed one](https://github.com/angular/angular/issues/55673#issue-2279005463)) and thinking of adding a new utility / primitive.

The exact naming TBD (currently hesitating between `derivedSignal`, `derivedState` or `writableComputed`) but the functionality would be similar to https://github.com/angular/angular/issues/55673#issuecomment-2094350490 

Conceptually it is a signal (with all the signal methods: set, update, asReadonly) that has its state initialized and _reset_ based on some other reactive state (computed).

**Comment by mauriziocescon** [comment]
Thanks a lot for the great news! 

Seems like in svelte they called it `link`... haven't checked the details, but (high level) it's more or less the same idea of `writableComputed`! 

Strictly personal: regarding the name, I like `derived`... even though a svelte developer would probably disagree. Maybe  `linked` could be a good fit as well! 

So, something like: 
- `signal`, 
- `computed`, 
- `effect`, 
- `derived` / `linked`.

I'd stay away from `state` / `writable` (and maybe even `signal`) in the name. 

Just my 2 (not requested) cents! 😅

https://x.com/joyofcodedev/status/1825986171924525450

**Comment by mauriziocescon** [comment]
Oops PR reverted (apologise for the spamming then)... 😅

The follow up discussion is anyway interesting! 
`https://github.com/sveltejs/svelte/pull/12943`

**Comment by mauriziocescon** [comment]
Hey! 

Coming back to the topic (I know: "him, again!!!" 😅). 

So, after the recent [TechStackNation video from Alex ](https://www.youtube.com/watch?v=aKxcIQMWSNU) and the 1M X-discussions regarding effects, I took a look at what we're doing in a large application (the usage of signals is limited to a small fraction of the code, but still). Just FYI: the part I checked is in a good shape! 

Points: 
- effects were almost always used to either connect reactive-to-not-reactive code or as business-effects, 
- the potential usage of a wComputed (or sandwich) was covered by effects and accounted to a small percentage of the total, 
- any wComputed case was related to inputs (no exception): a wSignal that depends on user-interaction and input(s) changes. 

Surprisingly (or maybe not), there were 2 different cases around the "wComputed" area: 
- a reset of the wSignal, 
- a conditional change of the wSignal with fallback on the current value, 

and they were equally frequent (50% each)! 

Here is a basic example (derived from the one above where the "sandwich" can be used): https://stackblitz.com/edit/stackblitz-starters-bazylb?file=src%2Fmain.ts 

```ts
export class App {
  user = signal<{ name: string; ts: number }>({ name: 'John', ts: 1 });
  name = signal(this.user().name);

  userWatcher = effect(() => {
    const user = this.user();
    
    untracked(() => {
      if (user.ts % 2) {
        // changes only when odd
        this.name.set(this.user().name);
      }
    });
  });

  sandwich = computed(() => ({ name: signal(this.user().name) }));

  timer = setInterval(() => {
    // simulating input changes
    this.user.update((u) => ({ name: `John ${Date.now()}`, ts: Date.now() }));
  }, 10000);
}
```

Of course, a computed has no access to the "current value" (https://github.com/angular/angular/issues/54339). This is just to report some concrete data and feedback... which IMHO could be summarised like this: 
- derived some signal state from inputs without effects is not straightforward (but it's a common pattern), 
- a wComputed can solve some cases, but probably not all! 

As usual: thanks a lot!

**Comment by pkozlowski-opensource** [comment]
@mauriziocescon thnx for sharing, this is helpful since we are in the process of designing the new reactive primitive that would represent state derived / reset based on changes in the other signal. We should have more details soon-ish. 

And yes, access to previous values is important in some real-life use-cases. 

Stay tuned.
