### ISSUE TITLE
easier access to untracked function for more readability

### ISSUE THREAD

**Issue by RobinAraCom** [angular/angular#55682]
### Description

when writing effects and you dont want the reading of the signal to be tracked, but untracked instead, you can wrap it into an untracked block.

Example (where costunit and locationType are both required inputs using signals): 
![image](https://github.com/angular/angular/assets/150449781/a349a85e-b8a5-4f1e-bd5c-dcde0c8da2e8)

### Proposed solution

Rather than putting it into a seperate function each time with a callback, just allow access with a function. (But keep the function)

`const costunit = this.costunit.untracked();`

![image](https://github.com/angular/angular/assets/150449781/3b3a0e7e-6e5d-4704-8f8e-0f356758929c)

Pros: 
- Improves readability
- Seperation of concern _(including my operations/side effects within the untracked block is not related to the "untracked" itself. It is only related to the reading of the signal._
- less code

Cons: 
- Single point of truth: do keep the untracked() importable function, because sometimes you simple want to invoke instance methods, which maybe read signals whose reactivity is not desired. Therefore you now have two variants to to the same thing, which could, if ever so slightly increase learning curve.

### Alternatives considered

- using the variant provided in the exmaple screenshot, to make use of the untracked() function being able to return a value.
- create a wrapper class and implement the function yourself and hope it doesnt mess with the engine or the schemantics

**Comment by JeanMeche** [comment]
Hi, this subject has been discussed in #52210. I'll close this as a duplicate.
