### ISSUE TITLE
ControlGroup can't be set to pristine

### ISSUE THREAD

**Issue by basvandenheuvel** [angular/angular#5568]
Once a controlgroup is marked as dirty you can't mark it as pristine anymore.
There is a `markAsDirty` method, it doesn't expect a parameter so it can only be used to set it to dirty. There is also a `pristine` property, but it seems to be a getter and not a setter.

In short: once dirty, it can't be set to pristine no more.

**Comment by antonmoiseev** [comment]
Sounds like a subset of this issue https://github.com/angular/angular/issues/4933

**Comment by ajtowf** [comment]
Concider the solution from the angular material team, they introduced

$setUntouched() and
$setPristine()

on the form.

**Comment by basvandenheuvel** [comment]
Closing because of https://github.com/angular/angular/issues/4933

**Comment by born2net** [comment]
+1
