### ISSUE TITLE
ViewRef broken "Change detection usage" link doesn't work

### ISSUE THREAD

**Issue by vladboisa** [angular/angular#55687]
### Describe the problem that you experienced

Clicking link "[Change detection usage](https://angular.dev/api/core/ChangeDetectorRefusage-notes)" in "[ViewRef](https://angular.dev/api/core/ViewRef)" bring up the "Page No Found 🙃" page.

### Enter the URL of the topic with the problem

https://angular.dev/api/core/ViewRef

**Comment by alxhub** [comment]
Fixed as the PR was merged
