### ISSUE TITLE
Angular.dev: Missing Overview Page for Components

### ISSUE THREAD

**Issue by ToneyPK** [angular/angular#55685]
### Describe the problem that you experienced

All other topics in the 'Docs' have an 'Overview' page except the https://angular.dev/guide/components page.
I think that we should add one to fit the existing structure but also to have a more welcoming page for beginners instead of going straight into the 'Anatomy of a component' topic.

The one from the old website https://angular.io/guide/component-overview is quite good in my opinion but could be also improved and added to the angular.dev website.

I also volunteer to write the page if we agree that this is a good idea.

### Enter the URL of the topic with the problem

https://angular.dev/guide/components

### Describe what you want to experience that would fix the problem

Have an 'Overview 'page for 'Components' topic.

**Comment by JeanMeche** [comment]
AFAIK anatomy of a componet acts as an overview with multiple link to dedicated pages.

**Comment by ToneyPK** [comment]
> AFAIK anatomy of a componet acts as an overview with multiple link to dedicated pages.

Yes there are links but if you compare the old vs the new one I think you get what I am trying to say.
Also in the new docs, all other topics start by first briefly explaining what is the purpose of that particular topic, what it is and so on.

I just think that there is a missing intro paragraph that leads people to all the links and other existing content by addressing main questions about the topic. 
I felt somehow just thrown into the _Every component must have:_ sentence.

If this is intentional (maybe the _Essentials_ page is supposed to cover this part) feel free to close this issue but I wanted to say that I found this weird and not as nice as in the old docs.

**Comment by bencodezen** [comment]
Thanks for the feedback @ToneyPK!

I can see how that isn't consistent across the guides. I'll work on making sure that consistency exists in the Component section as well while leveraging the work we've done in the Essentials guide.

**Comment by JeanMeche** [comment]
I suggest we close this following the recent changes.
