### ISSUE TITLE
Dynamically added CKEditors inside *ng-for loop break

### ISSUE THREAD

**Issue by martinsik** [angular/angular#5569]
I'm having an issue with dynamically added CKEditors rendred via `NgFor` with `angular@2.0.0-alpha.44`.  I'm not 100% sure it's an issue and maybe it's more related to CKEditor than Angular2. 

[Live demo is available here.](http://plnkr.co/edit/wHPV4rOTVK4lLTEZHxif?p=preview)

When you open the link above you see three CKEditors on the right. They all work correctly. Click the "Add" button at the bottom to add a new editor. This should result to:

1. editor: works
2. editor: works
3. editor: doesn't work, throws exception on any action
4. editor: works

Then add another editor:

1. editor: works
2. editor: works
3. editor: doesn't work, throws exception on any action
4. editor: doesn't work, throws exception on any action
5. editor: works

... and so on. 

```typescript
@Directive({
    selector: 'textarea'
})
class CKEditor {
    constructor(_elm: ElementRef) {
        CKEDITOR.replace(_elm.nativeElement);
    }
}

@Component({
    selector: 'my-app',
})
@View({
    directives: [NgFor, CKEditor],
    template: `
          <div *ng-for="#item of items">
            {{ item }}: <textarea>{{ item }}</textarea>
          </div>
          <button (click)="addItem()">Add</button>`
})
class AppComponent {
    items = ['default_0', 'default_1'];

    constructor() {
        this.addItem();
    }

    addItem() {
        var id = 'ckeditor_inst_' + this.items.length;
        this.items.push(id);
    }
}
```

It seems like Angular2 somehow manipulates with the last element which breaks the CKEditor.  

The same issue is with [`angular@2.0.0-alpha.47`](http://plnkr.co/edit/6YnDmqU7P6bX4Sy0P9fg?p=preview), I also tried using `@Component` instead of `@Directive` but [the result is the same](http://plnkr.co/edit/CXDtKw7ysD6R4cWWEKAv?p=preview).

I first spotted this issue when using CKEditor in a component created using `DynamicComponentLoader` and I thought it's related to it but `*ng-for` demo behaves exactly the same.

**Comment by michalstepien** [comment]
In Angular 2 beta 15 it works. Example:
[http://plnkr.co/edit/X5whPqDhLS6RjTR2N8hT?p=preview](http://plnkr.co/edit/X5whPqDhLS6RjTR2N8hT?p=preview)

Please close.

**Comment by pkozlowski-opensource** [comment]
Thnx @michalstepien ! Closing.

**Comment by martinsik** [comment]
Very nice, thanks!
