### ISSUE TITLE
html parser issues

### ISSUE THREAD

**Issue by genereux** [angular/angular#5571]
after migration to alpha 47, we have issues with html parser, with couple of tags like 
```<img>, <thead>, <tbody>```
I'll add more, when I'll find them

**Comment by sklyukin** [comment]
Same issue, parser created second `<tbody>` inside `thead`. To fix it in my case I just removed `thead`.

**Comment by vicb** [comment]
I think those have already been fixed (to be released), see:
- "fix(HtmlParser): close void elements on all node types" #5532 for void elements (`<img>`, ...)
- "fix(HtmlParser): do not add a tbody parent for tr inside thead & tfoot" #5417

Feel free to re-open if the issue persits after the next release or if your use case is not covered.

Thanks
