### ISSUE TITLE
Allow style URL to use absolute paths

### ISSUE THREAD

**Issue by mangelozzi** [angular/angular#55714]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

When defining style URLs it can get ridiculous:
```
@Component({
    selector: "wc-foo",
    templateUrl: "./foo.component.html",
    styleUrls: ["../../../../../../../../shared/styles/ui-form.styles.css], // <-- Let's play check the file path 10 times!
})
export class FooComponent {}
```

Knowing how many levels to go up is so tedious, and not reusability, it has to be calculated everytime

### Proposed solution

Allow style urls to be defined relative to the `src` of the project like the typescript files can. If it does not start with `.` then treat it as an absolute path relative to the project root.

```
@Component({
    selector: "wc-foo",
    templateUrl: "./foo.component.html",
    styleUrls: ["src/shared/styles/ui-form.styles.css],  // <-- Much better
})
export class FooComponent {}
```

Now the style can be copied and pasted

### Alternatives considered

- Configuring a `@src/*` in `tsconfig.json`
- `@import 'src/shared/styles/ui-form.styles.css';` but the file is downloaded and parsed every time.
- Can't include it in global imports because it's a large file that must only be loaded for certain components.
- Crying

**Comment by JeanMeche** [comment]
This feature has been declined in the past, see #4974. 
Also see angular/angular-cli#20162
