### ISSUE TITLE
Bug: Event 'afterViewChecked' is fired many times

### ISSUE THREAD

**Issue by DeShadow** [angular/angular#5572]
In angular2@2.0.0-alpha.45 version and previous versions the event 'afterViewChecked' was fired 1 time after changes in model. But in angular2@2.0.0-alpha.46 and 47 versions this event is fired once or twice.

Short example:
```typescript
import {bootstrap, Component, AfterViewChecked} from 'angular2/angular2';

@Component({
    selector: 'my-app',
    template: `<div (click)="check()">Test</div>`
})
class AppComponent implements AfterViewChecked {
   afterViewChecked(){
        console.log("After view checked");
    }

    check(){
        console.log("check!");

        setTimeout(function(){
            console.log("timer!");
        }, 1000);
    }
}

bootstrap(AppComponent);
```

I load my application, click button, wait 2 seconds, click another time.
The console output of angular2@2.0.0-alpha.45 version:
```
After view checked
After view checked
After view checked
After view checked
check!
After view checked
timer!
After view checked
```

And it is predictable.

But in angular2@2.0.0-alpha.46 and next version the console output after the same actions:
```
After view checked
After view checked
After view checked
After view checked
After view checked
check!
After view checked
timer!
After view checked
After view checked
check!
After view checked
timer!
After view checked
After view checked
```

As you can see,  event 'afterViewChecked' was fired twice after timeout. The same situation when i try to use socket.io in my application. This event is fired twice after callback.

It is problem, because officially TTL = 1 and this event is must fired only one time after user event. 
I want to manipulate with DOM-elements after changes (to change scroll position) and want to do it only one time after changes.

**Comment by demetrio812** [comment]
Hello, having the same problem with 2.0.0-rc.1, is this a normal behaviour?

**Comment by pkozlowski-opensource** [comment]
@demetrio812 could you:
* tell us if you are using prod mode or debug mode?
* provide a minimal plunker with a reproduce scenario? 

It is hard to say / do anything about this issue without the above info. Thnx!

**Comment by demetrio812** [comment]
Hello @pkozlowski-opensource and thanks for replying, 
the same thing that @DeShadow has done is giving the same problem with the latest version.

Here a plunker to test it, check the console after it runs: [http://plnkr.co/edit/GDZIIPqdMOA7GvnhZib2?p=preview](http://plnkr.co/edit/GDZIIPqdMOA7GvnhZib2?p=preview)

I've tried in development mode...

Thanks a lot,
Dem

**Comment by pkozlowski-opensource** [comment]
I guess we are talking about the initial rendering only, as things seem to be in order for the subsequent change detections: http://plnkr.co/edit/h015q8vqjfW80hgG72TJ?p=preview

**Comment by demetrio812** [comment]
Yes I can only reproduce it on the initial rendering...

**Comment by felimartina** [comment]
having same problem here

**Comment by vicb** [comment]
Could you please provide a plunker on the last RC ?

**Comment by cartant** [comment]
@vicb I came across this issue when looking into multiple `afterViewChecked` calls for a `select` element in a unit test (using RC5).

I'm not sure whether or not the behaviour is related to this issue - or whether or not multiple calls is the expected behaviour for `select` elements - but if it's useful, there is a Plunker [here](https://plnkr.co/edit/WOr9QRlhQjuNiGjSGGdr) that demonstrates the behaviour in 2.0.0 final.

**Comment by vicb** [comment]
@cartant could you please re-open this issue for 2.0.0. Thanks.

**Comment by cartant** [comment]
@vicb Done #11895

**Comment by vicb** [comment]
thanks !
