### ISSUE TITLE
Code snippets: issue with string highlight

### ISSUE THREAD

**Issue by CH4R4F** [angular/angular#55733]
### Describe the problem that you experienced

a single quote string highlights the code in a weird style, the close single quote acts as a start quote and the code after is is highlighted in a yellow like color, **even in comments**

### Enter the URL of the topic with the problem

https://angular.dev/guide/testing/services

### Describe what you want to experience that would fix the problem

sometimes, code highlighting helps me read code faster as I skip reading the whole strings placeholder, detect the variable and function declarations etc, it would be better if the code highlighting is clean and makes sense

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/74823355/9307e325-ee40-4c26-b59d-2e277c963e74)

**Comment by JeanMeche** [comment]
Hi, we're looking at improving the highlighting, let's merge the discussing in #52654.
