### ISSUE TITLE
Support for using input function within component’s provider

### ISSUE THREAD

**Issue by examan** [angular/angular#55744]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

After Angular introduced the new signal input, like the inject function, its usage should be more flexible. However, the input function is not yet supported for use within the component’s provider. This usage allows descendants to directly access the upper-level input without going through layers of input or service.

### Proposed solution

```typescript
@Component({
  ...
  providers: [
    {
      provide: ID,
      useFactory: () => input.required<string>({ alias: 'id' }),
    },
  ],
})
```

### Alternatives considered

Using ‘name’ instead of ‘alias’ might be more appropriate for the naming in this context.

```typescript
@Component({
  ...
  providers: [
    {
      provide: ID,
      useFactory: () => input.required<string>({ name: 'id' }),
    },
  ],
})
```

**Comment by alxhub** [comment]
Would this be a significant improvement over:
```typescript
@Component({
  ...
  providers: [
    {
      provide: ID,
      useFactory: () => inject(Cmp).id,
    },
  ],
})
class Cmp {
  readonly id = input.required<string>();
}
```

**Comment by alxhub** [comment]
Note that additionally, it's possible for downstream components to inject `Cmp` directly and have access to its input signals if desired.

**Comment by alxhub** [comment]
(going to close this as the existing featureset covers this use case pretty well without adding new complexity to declaring inputs)
