### ISSUE TITLE
[http] enums should not be plurals

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#5574]
`RequestMethods`, `RequestStates` and `ResponseTypes` would make more sense if not plurals:
`let method: RequestMethods` looks a bit weird, `let method: RequestMethod` would be better IMHO. 

Other enums in the code base are singular (`ChangeDetectionStrategy` for example).
If you agree with this change I can submit a PR.

**Comment by pkozlowski-opensource** [comment]
+1

**Comment by jeffbcross** [comment]
Sure, PR welcome @cexbrayat!

**Comment by jeffbcross** [comment]
Can you mention me when you open the PR so I see the notification?

**Comment by cexbrayat** [comment]
@jeffbcross done in #5584 ;)
