### ISSUE TITLE
transparent text on chrome 109

### ISSUE THREAD

**Issue by A-So-Nya** [angular/angular#55763]
### Describe the problem that you experienced

Links and code are transparent on chrome 109.0.5414.168, which is the latest that works on Windows versions prior to 10, the selector that does that for links is `.docs-faceted-list-item a, .docs-faceted-list-item button:not(.docs-expanded-button)` and `code:not(pre *)` for code blocks. It's reproducible in Incognito mode without extensions.
Also buttons on cookie banner are broken.

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/advanced-configuration

### Describe what you want to experience that would fix the problem

I'd like `<a>` and `<code>` tags to be readable on chrome on windows 8.1, though not sure if it's the one that required to be supported on angular.dev

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/7118699/0e735cc6-799c-4c42-8892-a94fd29f4268)
![image](https://github.com/angular/angular/assets/7118699/a8d01f38-b695-4bfc-8c2a-8657445d7368)
![image](https://github.com/angular/angular/assets/7118699/84f3b48e-dc03-4b32-ae1e-e2bfdb8eef2f)
![image](https://github.com/angular/angular/assets/7118699/d32e8a78-d7c0-467d-9aa3-f1340bf89ea3)
![image](https://github.com/angular/angular/assets/7118699/9711a51b-a18b-4b44-9c8a-fb24fe078f3d)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Windows 8.1 (Build 9600.21075), Google Chrome 109.0.5414.168 (Official build) (x64)
```

**Comment by JeanMeche** [comment]
Note: this is basically the same issue than #52598. 

`oklch` and `color-mix` support landed in M111.

**Comment by bencodezen** [comment]
This should be resolved now. If you still see issues, please let us know!
