### ISSUE TITLE
Scope of template local variables in Angular @if() block seems wrong

### ISSUE THREAD

**Issue by alcfeoh** [angular/angular#55783]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

If I declare a local template variable in an @if() block, such variable is available in the @if() block but not in the @else() block, which seems like a bug. See `cartContents` below is not available in my @else block (see variable name in red below):

![Screenshot 2024-05-13 124310](https://github.com/angular/angular/assets/4699771/08e98108-c778-4e40-9acf-8f1c3ecbf18b)

### Please provide a link to a minimal reproduction of the bug

Screenshot has an example

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.0
Node: 18.17.1
Package Manager: npm 10.5.1
OS: win32 x64

Angular: 17.3.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.0
@angular-devkit/build-angular   17.3.0
@angular-devkit/core            17.3.0
@angular-devkit/schematics      17.3.0
@schematics/angular             17.3.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.4
```

**Comment by JeanMeche** [comment]
Hi, this is as designed. Have a look at [the RFC](https://github.com/angular/angular/discussions/50719). Also note that aliasing is only supported because of the backward compatibility with `*ngIf`. 

What you are looking for is the longly awaited template variable declaration #15280.

**Comment by alcfeoh** [comment]
Ok. Now that the syntax looks like regular `if—then—else` blocks, my expectation was that this would behave just like in other programming languages. I guess that's one more reason to use Signals instead of Observables.
