### ISSUE TITLE
Improve SEO of angular.dev

### ISSUE THREAD

**Issue by JPtenBerge** [angular/angular#55804]
### Describe the problem that you experienced

The new home of Angular's docs, angular.dev, does not seem to get indexed by search engines.

Searching for anything on the old and new Angular documentation websites using both Google and Bing:

Old site:
- [Searching on Bing](https://www.bing.com/search?q=site%3Aangular.io) - multiple pages of results
- [Searching on Google](https://www.google.com/search?q=site%3Aangular.io) - multiple pages of results

New site:
- https://www.bing.com/search?q=site%3Aangular.dev - just 1 result, the landing page, not even a description
- https://www.google.com/search?q=site%3Aangular.dev - same 1 result, the landing page, no description

This is not strange of course, as their [robots.txt](https://angular.dev/robots.txt) clearly disallows indexing. I could somewhat understand this when they first launched the site, but seeing as [the other doc site is being shut down](https://www.infoworld.com/article/3715328/angular-18-will-arrive-next-week.html), isn't it time to open up indexing?

**Comment by JeanMeche** [comment]
Hi, 

Currently Angular isn't indexed (see https://angular.dev/robots.txt) but will be when we promote it to stable with the release of v18.
