### ISSUE TITLE
Bounds attributes [attr.xxx] do not trigger directives 

### ISSUE THREAD

**Issue by Miedziaq** [angular/angular#55807]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

This is duplicate of #11716 because the original topic is closed, but the problem still exists, and linked substitute solution is not fixing the core of problem.

As long as directives supports selecting ATTRIBUTES that should works also with BOUNDED ATTRIBUTES

Still it isn't possible to apply directive on 
<span [attr.xxx]="cond ? true : null">xxx</span>

I have to bind directive  to dom element depends on some condition, and its stupid to done it by ngif else and makes boilerplate code.

As long as its not working there is a BUG in my opinion, because directives with attrubites selector works only PARTIALLY

### Please provide a link to a minimal reproduction of the bug

https://plnkr.co/edit/WiCrCxlNrUgaBCXkEQkm?p=preview&preview

### Please provide the exception or error you saw

```true
Angular CLI: 16.2.9
Node: 20.13.1 (Unsupported)
Package Manager: npm 10.5.2
OS: win32 x64

Angular: 16.2.11
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.9
@angular-devkit/build-angular   16.2.9
@angular-devkit/core            16.2.9
@angular-devkit/schematics      16.2.9
@angular/cli                    16.2.9
@schematics/angular             16.2.9
ng-packagr                      16.2.3
rxjs                            7.5.7
typescript                      4.9.5
zone.js                         0.13.3
```

**Comment by JeanMeche** [comment]
You're looking for conditional directives. Directive matching needs the selector to be static so this isn't at all supported and currently works as designed. 
 
The alternative here is to handle the condition in the directive itself by passing an input.

**Comment by JoostK** [comment]
We discussed this issue just now and this is working as intended, with no plans to change the behavior.

Our reasoning is that an `attr.` binding results in a conditional attribute, as the attribute is being removed if the binding evaluates to `null`.

If you want to achieve this behavior, you can setup an attribute mirror from a bound property:

```ts
@Component({
  host: {
    '[attr.mirror]': 'mirror',
  }
})
export class MyCmp {
  @Input()
  mirror: string;
}
```

which is then set using a property binding instead of an explicit attribute binding.

**Comment by Miedziaq** [comment]
But this will work only with components. What if i need to apply it on span 🤦.

**Comment by JoostK** [comment]
> But this will work only with components. What if i need to apply it on span 🤦.

I don't follow. If you have e.g. `<span [trimmed]="trimmed"></span>` and a directive:

```ts
@Directive({
  selector: '[trimmed]',
  host: { '[attr.trimmed]': 'trimmed' }
})
export class MyDir {
  @Input() trimmed: boolean;
}
```

that should do the trick?

**Comment by Miedziaq** [comment]
i will check this thx. but still looks like shoot a fly with a cannon :)
