### ISSUE TITLE
Recursion bug in Angular (child in defer block) 

### ISSUE THREAD

**Issue by dreamstar-enterprises** [angular/angular#55810]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler, core

### Is this a regression?

Yes

### Description

I cannot reproduce this behaviour on StackBlitz... 

With this,

```
<!-- project navigation bar -->
<app-project-navigation></app-project-navigation>

@defer(when isDataLoaded()) {

  <!-- project container -->
  <div class="fadeIn">

    @if(!hasErrorSignal()){
      
      <!-- project-container page router -->
      <router-outlet></router-outlet>

    } @else {

      <p>Error in making Http request(s).</p>

    }

</div>

}
```

Loads child component **once**, as expected 

<img width="880" alt="Screenshot 2024-05-15 at 15 13 23" src="https://github.com/angular/angular/assets/39380005/11f95823-c89f-4b32-bcfe-c0cbea1ca1df">

 .
.
But with this, making the **one** change, putting the child nav component, in the defer block,

```
@defer(when isDataLoaded()) {

  <!-- project container -->
  <div class="fadeIn">

    @if(!hasErrorSignal()){

      <!-- project navigation bar -->
      <app-project-navigation></app-project-navigation>

      <!-- project-container page router -->
      <router-outlet></router-outlet>

    } @else {

      <p>Error in making Http request(s).</p>

    }

</div>

}
```

I get this, 

<img width="1396" alt="Screenshot 2024-05-15 at 15 13 45" src="https://github.com/angular/angular/assets/39380005/f134a80c-b397-4000-ba22-1f30afd9718e">

This looks like an Angular 17 "@angular/core": "^17.3.8", - bug?

Happy to try and post this elsewhere or do further work, to try and understand the root cause.

Thanks in advance

### Please provide the exception or error you saw

```true
See above
```

**Comment by atscott** [comment]
The screenshot of your app looks pretty simple. Are you able to share a github repository with the reproduction?

**Comment by dreamstar-enterprises** [comment]
Hi Scott, 

I'll see what I can do, I'd rather not share my entire app... (is there a way I can share a few components?)

**Comment by atscott** [comment]
> is there a way I can share a few components?)

yes, you can keep removing more and more things from your application. You should be able to get the app down to just a few components that are able to reproduce the problem.

**Comment by dreamstar-enterprises** [comment]
ok, give me a few hours... I'll get back to you

**Comment by dreamstar-enterprises** [comment]
I cloned the package, and tested it, and it worked. So, then did a fresh install of everything

npm update
ng update

And it worked. Must have been some stability issue with a recent Angular update

This is now what works for me:

```
"dependencies": {
    "@angular/animations": "^17.3.2",
    "@angular/cdk": "^17.3.1",
    "@angular/common": "^17.3.2",
    "@angular/compiler": "^17.3.2",
    "@angular/core": "^17.3.2",
    "@angular/forms": "^17.3.2",
    "@angular/material": "^17.3.1",
    "@angular/material-experimental": "^17.3.9",
    "@angular/material-moment-adapter": "^17.3.9",
    "@angular/platform-browser": "^17.3.2",
    "@angular/platform-browser-dynamic": "^17.3.2",
    "@angular/router": "^17.3.2",
    "@material/web": "^1.1.1",
    "@ngrx/operators": "^17.2.0",
    "@ngrx/signals": "^17.2.0",
    "@types/lodash": "^4.17.1",
    "lodash": "^4.17.21",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"
  },
```

Closing issue
