### ISSUE TITLE
Is there a way of renaming input component bindings

### ISSUE THREAD

**Issue by dreamstar-enterprises** [angular/angular#55814]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Can I rename

id = input<string>() 

to projectID, in my class, without creating an extra variable?

id above matches the :id parameter in my route config file

I don't think aliased names can be used in the component class.

### Proposed solution

See above

### Alternatives considered

See above

**Comment by JeanMeche** [comment]
If you have an input `  val = input('', { alias: 'id' });`, it will match the `:id` route parameter.

**Comment by dreamstar-enterprises** [comment]
Thank you, I got this the wrong way round, after reading the in preview docs.
