### ISSUE TITLE
Angular localstorage not working with SSR inside Authguard

### ISSUE THREAD

**Issue by satheshsat** [angular/angular#55822]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

Angular using SSR localstorage is not defined inside authguard

### Please provide the exception or error you saw

```true
ERROR ReferenceError: localStorage is not defined
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.7
```

### Anything else?

sample code
https://github.com/satheshsat/angularssr

**Comment by alan-agius4** [comment]
This is expected as `localStorage` is a browser feature.
