### ISSUE TITLE
Subject: Feature Request: Restore Reset Functionality for contentChildren Signal API

### ISSUE THREAD

**Issue by ChristianKlima** [angular/angular#55823]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Dear Angular Team,

I hope this message finds you well. I'm reaching out to request a feature enhancement regarding the recent changes in the Angular framework.

Previously, the @ContentChildren decorator provided a QueryList which included a useful reset() function. This function allowed developers to modify the order of elements within the QueryList. However, with the introduction of the new Signal API contentChildren(), the returned result is now a read-only array, devoid of the reset() functionality.

I understand that the Signal API offers advantages, but the absence of the reset() function has caused inconvenience in scenarios where dynamic manipulation of the query list order is required.

Hence, I kindly request considering the restoration of the reset() functionality for the contentChildren() Signal API in future Angular releases. This feature would greatly enhance the flexibility and usability of the framework for developers.

Thank you for considering my request. I appreciate your ongoing efforts to improve Angular and look forward to seeing its continued evolution.

Best regards,

Christian

### Proposed solution

Possibility to change order of query-result

### Alternatives considered

---

**Comment by JoostK** [comment]
The signal APIs reflect the _factual_ query state and is not meant to be mutated. If you need to influence their ordering, you'll have to derive a second state value from the query signal.

`QueryList.reset` itself wasn't really intended to public either, it is an implementation detail that that ended up being public.

**Comment by pkozlowski-opensource** [comment]
I would very much like to echo @JoostK [message](https://github.com/angular/angular/issues/55823#issuecomment-2114491552) - the `QueryList.reset` ended up in the public API by an unfortunate accident - it never _meant_ to be public / used by application developers.

As @JoostK mentioned one way of going about re-ordering of results would be to use a `computed` signal. Having said this I'm curious about the exact use-case that you are trying to address - would you mind share more info on _why_ the re-ordering is needed?

**Comment by ChristianKlima** [comment]
Thank you for the response, I understand. The use case was a Carousel component where the position of the contents needs to be swapped, all without triggering the ChangeDetection. I believe I might find an alternative solution for this. I just wanted to inquire if there was a replacement for the reset function. Since it's not intended to be public anyway, I'll have to find a different approach. Many thanks, and greetings to the Angular Team!
