### ISSUE TITLE
Not found images from tutorial

### ISSUE THREAD

**Issue by MrPemu** [angular/angular#55849]
### Describe the problem that you experienced

Not found images from tutorial **Build your first Angular app locally via npm**

https://angular.dev/assets/tutorials/common/bernard-hermant-CLKGGwIBTaY-unsplash.jpg
https://angular.dev/assets/tutorials/common//brandon-griggs-wR11KBaB86U-unsplash.jpg
etc...

### Enter the URL of the topic with the problem

https://angular.dev/assets/tutorials/common/bernard-hermant-CLKGGwIBTaY-unsplash.jpg

**Comment by JeanMeche** [comment]
Hi, this is basically the same issue as #55163, let's continue to track this issue over there.
