### ISSUE TITLE
PLATFORM_DIRECTIVES not defined in tests

### ISSUE THREAD

**Issue by alxhub** [angular/angular#5585]
`createTestInjector` uses bindings that are missing `PLATFORM_DIRECTIVES`.

This means that if a user defines a component that uses `NgIf` for example but doesn't specify an explicit dependency via `@Component({directives})`, it will work in the app but fail in tests.

**Comment by juliemr** [comment]
See also https://github.com/angular/angular/issues/5351

**Comment by pkozlowski-opensource** [comment]
This is duplicate of #5433

**Comment by juliemr** [comment]
Can I close this as a dupe? There's a fix design in #5351 - please continue discussion there! :)
