### ISSUE TITLE
Animation trigger can be bound using @HostBinding and not using the host property

### ISSUE THREAD

**Issue by sbarfurth** [angular/angular#55852]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

No

### Description

One can use the `@HostBinding` decorator to add an animation trigger to a host element. This works perfectly fine. However, trying to add the same trigger using the `host` property fails with `NG05105`. Considering everything works correctly with `@HostBinding` the error appears to be incorrect.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-qqh3bq?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
NG05105: Unexpected synthetic property @state found. Please make sure that:
  - Either `BrowserAnimationsModule` or `NoopAnimationsModule` are imported in your application.
  - There is corresponding configuration for the animation named `@state` defined in the `animations` field of the `@Component` decorator (see https://angular.io/api/core/Component#animations).
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.7
Node: 18.18.0
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.3.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.7
@angular-devkit/build-angular   17.3.7
@angular-devkit/core            17.3.7
@angular-devkit/schematics      17.3.7
@angular/cli                    17.3.7
@schematics/angular             17.3.7
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.6
```

### Anything else?

It appears this issue is present with both `provideAnimations()` and `BrowserAnimationsModule`. The issue seems to vanish with `provideAsyncAnimations()`. This is sadly not an option for me at this time.

**Comment by JeanMeche** [comment]
>  This is sadly not an option for me at this time.
Care to give a bit of insight on why this is not an option for you. Is your project below v17 ?

**Comment by JoostK** [comment]
`@HostBinding`'s are always interpreted as bindings, whereas the `host` property differentiates between bindings and values. Bindings require bracketed syntax using `'[@openClose]'`

**Comment by alxhub** [comment]
Closing as resolved - @JoostK's explanation is exactly accurate.

**Comment by sbarfurth** [comment]
> Closing as resolved - @JoostK's explanation is exactly accurate.

Help me understand why the same logic works with the async animation model then? It's not like I need to bind animation triggers in templates.

```html
<div @openClose></div>
```

I am just wondering why we need to bind explicitly only with the host attribute here and why the behavior is different with the async animation module.
