### ISSUE TITLE
Feature Request: Allow Non-Blocking Mode for strictTemplates

### ISSUE THREAD

**Issue by tomer953** [angular/angular#55868]
### Which @angular/* package(s) are relevant/related to the feature request?

language-service

### Description

We are working on a large-scale Angular project and are interested in adopting the `strictTemplates` option to improve our type safety and overall code quality. However, enabling strictTemplates currently flags a significant number of errors due to our existing codebase size, making an immediate adoption impractical as it would halt our build processes.

### Proposed solution

Implement an option within `angularCompilerOptions` where `strictTemplates` can be enabled in a non-blocking mode. This mode would allow developers to see warnings instead of errors for strict template checks, preventing them from blocking the build process. This feature would be incredibly beneficial for large projects wanting to gradually adopt strict type checking in their templates without disrupting their development workflow.

### Alternatives considered

Incremental Adoption \ Directive/Component Specific Flagging

**Comment by tomer953** [comment]
related to: https://github.com/angular/vscode-ng-language-service/pull/1646

Seems like VSCode extension allow to force strictTemplates without effecting the build process, However:
- its only works with VSCode, other IDEs don't have this flag
- Its an optional choice by the developer, and can't be enforced by a project setting.

**Comment by JoostK** [comment]
I'd recommend to adopt different `tsconfig.json` files for this pattern. I suspect that IDEs typically use the closest `tsconfig.json`, so having a `tsconfig.app.json` which extends the base `tsconfig` would allow you to have different compiler options for builds vs IDE.

**Comment by spock123** [comment]
@JoostK  We're in the same boat as @tomer953  and feeling quite stupid not having thought of that... thanks!

**Comment by tomer953** [comment]
Can someone provide an example of that workaround when using angular workspace with multiple projects? We already have some base.tsconfig in the root and `tsconfjg.json` and `tsconfig.app.json` for every project (the later extends the first)

So basically if I try to add the `strictTemplate: true` option to either on of them its effecting both IDE and ng build

**Comment by tomer953** [comment]
The workaround its not the easiest on large project, I had to change every tsConfig in the `angular.json` and create new tsconfig files for each project

I hope we will have some option to force strict template option on the language service, so I'll keep this issue open.

**Comment by alxhub** [comment]
We've discussed this question and decided that we shouldn't try to support any kind of warning mode for `strictTemplates`, for a few significant reasons:

1. `tsconfig.json` is already a standard way of applying different configurations to different parts of your codebase.

This is how TypeScript rolls out new strictness flags - at the granularity of the tsconfig options. It's also possible to configure two `tsconfig.json`s: one for the actual build, and one which enables new flags for experimentation.

2. Angular already has [incremental ratcheting flags](https://angular.dev/tools/cli/template-typecheck#troubleshooting-template-errors) for type-checking strictness.

3. The way template type-checking works really isn't conducive to lifting specific types of checks into warnings.

Template type-checking works by generating TypeScript code representing the template, and feeding it to TypeScript's checker. The diagnostics we get back are (for the most part) real TypeScript diagnostics produced by `tsc`. Therefore we can't really know per-diagnostic _why_ it was produced, only that TypeScript found something wrong in the template block. Sometimes we can correlate specific lines with specific types of checks, but mostly this is not the case.
