### ISSUE TITLE
Missing photos from tutorial

### ISSUE THREAD

**Issue by JuanJoseToroCh** [angular/angular#55862]
### Describe the problem that you experienced

The photos in 

https://angular.dev/assets/tutorials/common/example-house.jpg

Are no longer available to complete the tutorial.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app/07-dynamic-template-values

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/63673589/f7f6ac10-c127-4d95-b36b-7a0fbf768e7c)

**Comment by JeanMeche** [comment]
Hi, thank you for reporting this issue. We're already tracking it in issue #52666
