### ISSUE TITLE
Dart: urls in `part` files resolved relative to the compilation unit they are a `part of`

### ISSUE THREAD

**Issue by kegluneq** [angular/angular#5587]
Example:

maindir/main.dart
```dart
library main;

part 'subdir/foo.dart';
```

maindir/subdir/foo.dart
```dart
part of main;

@Component(..., templateUrl: 'template.html')
class MyComponent {}
```

The transformer will look for template.html in maindir/, not maindir/subdir/

Workarounds:
* Do not place part files in subdirectories
* Use absolute uris to specify `templateUrl` / `styleUrls`

**Comment by kegluneq** [comment]
/cc @yjbanov 

My first thought for fixing this is to add some dummy syntax that include the absolute `part` uri when we inline, like so:

```dart
library main;

import 'a.dart';

/* INLINER_CURRENT_URI: asset:angular2/lib/maindir/subdir/foo.dart */

@Component(..., templateUrl: 'template.html')
class MyComponent {}

/* INLINER_CURRENT_URI: asset:angular2/lib/maindir/main.dart */

// Contents of main.dart
```

Then as we parse `codeWithParts` [here][], we update our "current" uri whenever we encounter one of those annotations.

Thoughts?

[here]: https://github.com/angular/angular/blob/master/modules_dart/transform/lib/src/transform/directive_processor/rewriter.dart

**Comment by yjbanov** [comment]
We want to make sure that we do not change the `AssetId` that we pass to the `AnnotationMatcher` as we go from one current URI to the next. Also, I think we could use real annotations instead of specially formatted comments and let `parseCompilationUnit` parse it for us (it doesn't resolve imports so we can use any annotation we like).

Other than that, this proposal LGTM!

**Comment by kegluneq** [comment]
How about using a funky local variable? You're right that it would be nice to not need to parse the comment:

```dart
library main;

import 'a.dart';

String __inlinerCurrentUri;
__inlinerCurrentUri = 'asset:angular2/lib/maindir/subdir/foo.dart';

@Component(..., templateUrl: 'template.html')
class MyComponent {}

__inlinerCurrentUri = 'asset:angular2/lib/maindir/main.dart';

// Contents of main.dart
```

**Comment by kegluneq** [comment]
Copied from PR #5620:

It appears we have some tests that run on Dart > Js code but which do not use the transformer. Unfortunately, `ClassMirror#location` is not implemented in dart2js, so these tests are failing.

To resolve this, we could:

<ol>
<li>Abandon this change
<li>Update those tests to:
<ol>
<li>Use the transformer
<li>Run in Dartium
</ol><li>Implement in dart2js
</ol>

Re: 1 above, @sigmundch made the good point that currently the location of a `part` file does not affect the semantics of the code at all. This is one reason that `import` statements are not allowed in `part` files. Maybe we should maintain this for Angular2.

**Comment by yjbanov** [comment]
As of https://github.com/angular/angular/commit/ac85cbb28afc39b4ea2bd95484f616e29755c9d5 all our playground examples use transformers.

**Comment by kegluneq** [comment]
Even if all other roadblocks were out of the way, I'm not convinced we should make this change. Unless we have a *very* strong reason for it, I'd vote against breaking with Dart's `part` semantics, especially given the added complexity.

Rather than this, I would rather implement support for defining `templateUrl` & `styleUrls` values in `const` values in the same library. Then authors could do something like:

main.dart
```dart

part 'parts/this_component.dart';

const thisComponentTemplateUrl = 'templates/this_component.html';
```

parts/this_component.dart
```dart
@Component(
   templateUrl: thisComponentTemplateUrl
)
```

Which, while not optimal, would clarify which file the urls are relative to without hurting readability.

**Comment by yjbanov** [comment]
All good points. Let's close.
