### ISSUE TITLE
incorrect link in browser platform location

### ISSUE THREAD

**Issue by DimitriTsikaridze** [angular/angular#55884]
### Describe the problem that you experienced

wrong link at BrowserPlatformLocation documentation,` Instead, use {@link Location }.`

### Enter the URL of the topic with the problem

https://angular.dev/api/common/BrowserPlatformLocation

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/56136563/882a30e0-d541-41f5-ba92-04ef1813980b)

**Comment by JeanMeche** [comment]
Thank you for reporting this issue, 

FYI we do have a fix ready (see #55888) but we're stucked with a TS parsing issue
*  microsoftTypeScript#58584
