### ISSUE TITLE
Angular control flow fails during certain cases

### ISSUE THREAD

**Issue by laijuthomas** [angular/angular#55882]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

I have a if else block in my html page which was working fine until I upgraded to angular 17 control flow

`@if(!isMobile){}` 
this is how I added the condition, the condition is to show some html based on a boolean variable (which is set using a behaviorsubject). This fails while reloading the page. but when I add an empty @else block, this works without any issue

any idea why this happens?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.6
Node: 20.11.1
Package Manager: npm 10.2.4
OS: darwin arm64

Angular: 17.3.6
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.6
@angular-devkit/build-angular   17.3.6
@angular-devkit/core            17.3.6
@angular-devkit/schematics      17.3.6
@schematics/angular             17.3.6
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

**Comment by JoostK** [comment]
Please provide a runnable reproduction, as without it we cannot investigate.

**Comment by pkozlowski-opensource** [comment]
Going to close this one for now as we haven't heard back with the reproduction scenario.
