### ISSUE TITLE
Route.useAsDefault does not change the URL

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#5590]
# Reproduction case:

Add the following HTML and Dart:
```html
<a href="/meetings">Go to meetings</a>
```

## Root component:

```dart
@RouteConfig(const [
  const Route(name: 'Meetings', path: '/meetings/...', loader: ...)
])
```

## Child component:

```dart
@RouteConfig(const [
  const Route(name: 'Coverage', path: 'coverage', useAsDefault: true, component: ...)
])
```
## Intended behavior

Clicking the anchor tag navigates to `meetings/coverage` component. URL reflects the change.

## Actual behavior

The component *is* loaded, but the URL stays as `meetings` (missing `/coverage`).

**Comment by btford** [comment]
I'm not opposed to this change, but this means that your links generate different URLs depending on whether or not stuff has loaded, which I think is a bit surprising.

Can you expand a bit about why this functionality would be preferred?

**Comment by matanlurey** [comment]
My main reason for wanting this is if you are shared a URL, e.g.

`http://myapp.com/meetings`, the router picks up `useAsDefault`, and changes the URL to `http://myapp.com/meetings/coverage`. However, if you click on a link within the application this doesn't happen.

**Comment by btford** [comment]
Got it. Makes sense. :+1:

**Comment by btford** [comment]
Looks like this only happens for links triggering changes outside of Angular, like `<a href="#/meetings">` and not using the RouterLink directive.

**Comment by matanlurey** [comment]
Yes, you are correct.
