### ISSUE TITLE
Unable to configure Hammerjs?

### ISSUE THREAD

**Issue by zachrip** [angular/angular#5594]
I'm attempting to use the tap event from hammerjs, however, it appears that there's no way to configure settings for these events? I'm specifically speaking about Touch Action, it interferes with my application and using native click events is not really an optimal solution.

Here is the touch action documentation: http://hammerjs.github.io/touch-action/ as well as an example from the hammerjs tests: https://github.com/hammerjs/hammer.js/blob/master/tests/manual/touchaction.html

**Comment by vicb** [comment]
You can inject a configuration for hammerjs
