### ISSUE TITLE
Comments break if else chains

### ISSUE THREAD

**Issue by Ookamini95** [angular/angular#55954]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Don't known / other

### Description

```
    @if(foo1) {
      // something
    }
    <!-- TODO: totally legit todo -->
    @else if (foo2) {
       // something
    }
```

i get error:
@else if block can only be used after an @if or @else if block.

expected behaviour : ignores comment

### Please provide the exception or error you saw

```true
@else if block can only be used after an @if or @else if block.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.2
Node: 20.10.0
Package Manager: npm 10.3.0
OS: win32 x64

Angular: 17.3.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.2
@angular-devkit/build-angular   17.3.2
@angular-devkit/core            17.3.2
@angular-devkit/schematics      17.3.2
@schematics/angular             17.3.2
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

### Anything else?

If pointed to the right file i may be able to provide a pr (beginner here)

**Comment by JoostK** [comment]
It would likely be similar to #52449, but I suppose @crisbeto has a fix faster than the blink of an eye.

**Comment by Ookamini95** [comment]
> It would likely be similar to #52449, but I suppose @crisbeto has a fix faster than the blink of an eye.

Thanks for the fast response, and sorry for the duplicate, it's my first actual bug report and was eager to share.
