### ISSUE TITLE
FormControl values to signal

### ISSUE THREAD

**Issue by alexandresebrao** [angular/angular#55989]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

Sometimes I want to use the FormControl values on computed signals, but is a bit sad that I need to make this code everytime I use it:

```
formControl = new FormControl()
formControl = toSignal(this.formControl.valueChanges)
```

### Proposed solution

I would prefer to use something like that

`computed(() => this.formControl.signalValue())`

### Alternatives considered

Keep using toSignal.

**Comment by JeanMeche** [comment]
Hi, let's continue tracking signal integration into forms in #53485.
