### ISSUE TITLE
[windows][dart][alpha.47] pub get transformer errors

### ISSUE THREAD

**Issue by avoivo** [angular/angular#5599]
On windows 8 , when i run 'pub get' , i am geeting large set of transformer errors :

    Resolving dependencies...
    Got dependencies!
    Precompiling dependencies...
    Loading source assets...
    Loading observe and smoke/src/default_transformer transformers...
    Loading angular2 transformers...
    [DirectiveProcessor]:
      Failed with 23 errors
    Error 1: line 1, column 1 of lib\animate\PaxHeader\testing.dart and parts: Expected a method, getter, setter or operator
     declaration
    14 uid=263934
    ^^
    Error 2: line 1, column 1 of lib\animate\PaxHeader\testing.dart and parts: Unexpected token '14'
    14 uid=263934
    ^^
    Error 3: line 1, column 4 of lib\animate\PaxHeader\testing.dart and parts: Variables must be declared using the keywords
     'const', 'final', 'var' or a type name
    14 uid=263934
       ^^^
    Error 4: line 1, column 8 of lib\animate\PaxHeader\testing.dart and parts: Expected to find ';'
    14 uid=263934
           ^^^^^^
    Error 5: line 2, column 1 of lib\animate\PaxHeader\testing.dart and parts: Expected a method, getter, setter or operator
     declaration
    20 ctime=1449001811
    ^^
    Error 6: line 2, column 1 of lib\animate\PaxHeader\testing.dart and parts: Unexpected token '20'
    20 ctime=1449001811
    ^^
    Error 7: line 2, column 4 of lib\animate\PaxHeader\testing.dart and parts: Variables must be declared using the keywords
     'const', 'final', 'var' or a type name
    20 ctime=1449001811
       ^^^^^
    Error 8: line 2, column 10 of lib\animate\PaxHeader\testing.dart and parts: Expected to find ';'
    20 ctime=1449001811
             ^^^^^^^^^^
    .....
    .....
    .....

I also have an ubuntu installation and it seems to work fine.

**Comment by jrote1** [comment]
I am also having the same issue, should be fixed before first beta release.

**Comment by jrote1** [comment]
@avoivo This issue seems to be fixed in the latest release

**Comment by avoivo** [comment]
Thanx @jrote1.

Fixed on alpha48
