### ISSUE TITLE
templateUrl does not work with fakeAsync

### ISSUE THREAD

**Issue by LasseNisted** [angular/angular#5601]
In tests I have run into an issue with fakeAsync and creation of components with templateUrl.

The following code illustrates the problem via the ng2-test-seed project updated to angular angular2@2.0.0-alpha.47.
```
@Component({
  template: '',
  directives: [BorderComponent]
})
class TestComponent {
}

describe('fancy border injectAsync', () => {
  it('fancy border injectAsync works', injectAsync([TestComponentBuilder], (tcb) => {
    return tcb.overrideTemplate(TestComponent, '<my-fancy-border>Content</my-fancy-border>')
        .createAsync(TestComponent).then((fixture) => {
          fixture.detectChanges();
          var compiled = fixture.debugElement.nativeElement;

          expect(compiled).toContainText('Content');
        });
  }));
  
  it('fancy border fakeAsync', inject([TestComponentBuilder], fakeAsync((tcb) => {
    var fixture;
    tcb.overrideTemplate(TestComponent, '<my-fancy-border>Content</my-fancy-border>')
        .createAsync(TestComponent).then((rootFixture) => {
          fixture = rootFixture;
        });
    // Create component-tick (initializes fixture variable)
    tick();
    // Invoke ngOnInit etc. after @Input etc. has been set.
    // Fails on the following:
    fixture.detectChanges();
/*  Irrelevant for bug report, but what we would conceptually like to do and why we cannot use injectAsync
    // Let promise in ngOnInit complete.
    tick();
    // Let view update from model.
    fixture.detectChanges();
    
    var compiled = fixture.debugElement.nativeElement;
    expect(compiled.querySelector('someTag')).toContainText("someText");
*/
  })));
});
```

First first test works as expected. The second test fails with "Failed: Cannot read property 'detectChanges' of undefined".

My limited debugging seems to indicate that TemplateNormalizer.normalizeTemplate calls _xhr.get but the promise does not resolve in the fakeAsync context.

If the templateUrl and styleUrls are commented out (in border-component.ts) and an inline template is supplied, then it works.

This may be related to #5468 and possibly #2835 could provide a workaround.

**Comment by cangosta** [comment]
I'm facing the same issue here. Check the following stackoverflow question: http://stackoverflow.com/questions/34741775/angular2-testing-with-fakeasync

**Comment by cangosta** [comment]
I've also created a github repo that reproduces the problem: https://github.com/cangosta/ng2_testing_fakeasync

**Comment by rbnzdave** [comment]
oh god. you mean its not just my use of it. I'd assumed i was doing it wrong.

**Comment by mithun-daa** [comment]
I am facing a similar issue too and I came across one approach for a temporary solution here:
https://github.com/angular/material2/blob/master/src/components/sidenav/sidenav.spec.ts#L71-L87

**Comment by vikerman** [comment]
We are close to providing a solution for this. The idea would be to use Karma plugin to build a template cache that can be loaded by the tests without doing an XHR. Similar to the test here  - https://github.com/vikerman/angular/blob/cached_xhr/modules/angular2/test/platform/browser/xhr_cache_spec.ts#L60

Will provide a full example with Karma plugin as part of https://github.com/juliemr/ng2-test-seed

Please follow #4051 for further details. Closing this one as duplicate.
