### ISSUE TITLE
adev: Window title does not represent current page in reference

### ISSUE THREAD

**Issue by rveerd** [angular/angular#56026]
### Describe the problem that you experienced

For every page in the reference, the window/tab title is "Angular".

This makes it impossible to find the correct window or tab for a specific page. Or to find a specific page in the browser history.

The title should reflect the current page.

### Enter the URL of the topic with the problem

https://angular.dev/api/core/testing/TestBed

### Describe what you were looking for in the documentation

The title should reflect the current page. Not "Angular" but something like "TestBed - Angular".

### Describe the actions that led you to experience the problem

Go to any page in the reference.

### Describe what you want to experience that would fix the problem

The title should reflect the current page. Not "Angular" but something like "TestBed - Angular".

**Comment by crutchcorn** [comment]
PR made for this issue:

https://github.com/angular/angular/pull/56840
