### ISSUE TITLE
Link to update guide to the application builder in medium blog post is not working

### ISSUE THREAD

**Issue by czogran** [angular/angular#56021]
### Describe the problem that you experienced

After clicking the link to "our update guide" in the Minko 18 release blog, I was redirected to a "Page not found" error.

I wasn't sure where to report this issue, so please feel free to close it if this is not the appropriate place. 

### Enter the URL of the topic with the problem

https://blog.angular.dev/angular-v18-is-now-available-e79d5ac0affe

### Add a screenshot if that helps illustrate the problem

https://github.com/angular/angular/assets/26524922/637bf228-af11-4abd-a002-00c870657402

![image](https://github.com/angular/angular/assets/26524922/5f578312-fe1c-4fdd-9a23-68888a446f08)

**Comment by MarkTechson** [comment]
This has been updated. Let us know if you experience anything else and thank you so much for contributing this issue.
