### ISSUE TITLE
Missing Automatic Polyfills as Described in Docs

### ISSUE THREAD

**Issue by Char2sGu** [angular/angular#56020]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v8?

### Description

As described at https://angular.dev/tools/cli/build#configuring-browser-compatibility, polyfills should be automatically added based on the browserslist configuration:

> The Angular CLI uses [Browserslist](https://github.com/browserslist/browserslist) to ensure compatibility with different browser versions. Depending on supported browsers, Angular will automatically polyfill and transform certain JavaScript and CSS features to ensure the built application does not use a feature which has not been implemented by a supported browser.

Angular V8 used to add core-js polyfills automatically according to StackOverflow discussions at https://stackoverflow.com/questions/56892243/is-not-core-js-needed-anymore:

> The difference with core-js in ng8 is that, since the CLI is handling polyfills, core-js is a dependency of the CLI. So even if you uninstall core-js as part of upgrading to ng8, you'll see it's still in your node_modules folder, but you won't have to manage which version is installed.

However, currently no core-js dependencies are found and also no core-js polyfills are automatically added. Angular CLI uses `@babel/preset-env` when building Angular applicaitons, which has [built-in support of automatic polyfilling based on core-js](https://babeljs.io/docs/babel-preset-env#usebuiltins), but this feature is not enabled:

https://github.com/angular/angular-cli/blob/c7205ea182f6c38231ce8fe8ab358dc7eab58d65/packages/angular_devkit/build_angular/src/tools/babel/presets/application.ts#L215-L224

### Minimal Reproduction

N/A

### Your Environment

```text
Angular CLI: 17.3.0
Node: 18.19.0
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.3.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, localize, material, platform-browser
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.0
@angular-devkit/build-angular   17.3.0
@angular-devkit/core            17.3.0
@angular-devkit/schematics      17.3.0
@schematics/angular             17.3.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by Char2sGu** [comment]
Alright then. I understand the design concerns, although do not fully agree.
Did any previous Angular version ever support automatic polyfills? According to historical community discussions, automatic polyfilling was once supported.

**Comment by alan-agius4** [comment]
No we never supported automatic polyfilling.
