### ISSUE TITLE
HttpClient won’t accept type parameters when its functions are accessed via ['bracket'] syntax

### ISSUE THREAD

**Issue by mwaibel-go** [angular/angular#56024]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

This used to work in Angular@16:

```
this.http[ booleanFlag ? 'post' : 'put']<MyModel>('http://api.com/test', {})
```

As of version 17, typescript throws the error below.

I care about this because I find this much more ergonomic than a lengthy if/else statement when the only thing that changes is the HTTP verb to use.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-2h5vsg?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
TS2558: Expected 0 type arguments, but got 1.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
❯ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.3.8
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.3.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8
@angular-devkit/schematics      17.3.8
@angular/cli                    17.3.8
@schematics/angular             17.3.8
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.6
```

### Anything else?

Reproduction of this working in v16: https://stackblitz.com/edit/stackblitz-starters-fydnsx?file=src%2Fmain.ts

**Comment by jnizet** [comment]
My suggestion would be to use 

```
    this.http.request<MyModel>(
      this.flag ? 'post' : 'put',
      'http://api.com/test',
      {}
    );
```

**Comment by mwaibel-go** [comment]
For the Googlers: When sending data, the invocation

`this.http[ booleanFlag ? 'post' : 'put']<MyModel>('http://api.com/test', theData, options)`

becomes

`this.http.request<MyModel>(booleanFlag ? 'post' : 'put', 'http://api.com/test', {body: theData, ...options})`

Note that the data you’re sending becomes part of the options.
