### ISSUE TITLE
Integrate Angular 2 in Visual Studio 2015 with TypeScript

### ISSUE THREAD

**Issue by SamPaul007** [angular/angular#5602]
Hi There,

What is the best approach for integrate Angular 2 in Visual Studio 2015 MVC6 with TypeScript.

Thanks!

Best Regards,
Sam

**Comment by michalstepien** [comment]
For example: http://www.mithunvp.com/angular-2-in-asp-net-5-typescript-visual-studio-2015/
Please close.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
