### ISSUE TITLE
Cant't fing image

### ISSUE THREAD

**Issue by furtivite** [angular/angular#56032]
### Describe the problem that you experienced

In the tutorial, I need to insert a picture into the test house. The picture is missing.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app/07-dynamic-template-values

### Describe what you were looking for in the documentation

[here](https://angular.dev/tutorials/first-app/04-interfaces) is code for this pic.

### Add a screenshot if that helps illustrate the problem

![Снимок экрана 2024-05-23 в 13 15 36](https://github.com/angular/angular/assets/50330458/4977cd1d-d897-4c92-80c8-38d1b07f88b9)

**Comment by JeanMeche** [comment]
Hi ! 
Let's continue tracking this issue in #52794
