### ISSUE TITLE
docs: CLI command to update Material missing from 16/17/18

### ISSUE THREAD

**Issue by msmallest** [angular/angular#56045]
### Describe the problem that you experienced

For the updates to Angular 16 and 17 and 18, the https://angular.dev/update-guide guide does not give the CLI commands to update Material and run the schematics. This is despite checking "I use Angular Material" and clicking "Show me how to update!".

### Enter the URL of the topic with the problem

https://angular.dev/update-guide

### Describe what you were looking for in the documentation

Checking "I use Angular Material" and clicking "Show me how to update!" should show a command like `ng update @angular/material@x` where `x` is either 16 or 17 or 18, or some variation.

### Describe the actions that led you to experience the problem

Using the upgrade guide. I have also seen a few people have issues from following the official update guide but manually bumping their Material versions because they did not see the Material CLI command.

### Describe what you want to experience that would fix the problem

A checkbox with the respective `ng update @angular/material@x` for 16 and 17 and 18

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/85510853/2ea01df4-fa84-45a8-8083-c0eb7400105a)

### Provide any additional information here in as much as detail as you can

```true
Consistent on Chrome and Firefox (desktop, MacOS)

I do not see any notion of it in `angular/adev/src/app/features/update
/recommendations.ts` for these affected versions https://github.com/angular/angular/blob/825023801baf8dbd0bd87b7ec46a65e869e08adb/adev/src/app/features/update/recommendations.ts#L2192, provided this is what I assume the updater reads from.
```

**Comment by msmallest** [comment]
Thank you

**Comment by JeanMeche** [comment]
Also added 16/17. Thanks for the reminder.

**Comment by pkozlowski-opensource** [comment]
@JeanMeche is this issue fixed now based on [your comment](https://github.com/angular/angular/issues/56045#issuecomment-2127626147)
