### ISSUE TITLE
How to render Angular components dynamically using selector  ?

### ISSUE THREAD

**Issue by trinath-katari** [angular/angular#56058]
Is it possible to render an Angular component dynamically? For example, I have component selector names in my .ts file. When I bind the variable in the .html file using interpolation and innerHTML, the component is not rendering. How can I achieve this?
My component selector names structure ->
<app-assessmentitem>
  <app-responsedeclaration >
    <app-correct-response>
    </app-correct-response>
  </app-responsedeclaration>
</app-assessmentitem>

**Comment by JoostK** [comment]
The only way to make this work is using custom elements (`@angular/elements`), but these have caveats of their own.

---

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
