### ISSUE TITLE
old url in hydration warning

### ISSUE THREAD

**Issue by DimitriTsikaridze** [angular/angular#56050]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

angular.io doesn't have this page. angular.dev has

`NG05000: Angular detected that hydration was enabled for an application that uses a custom or a noop Zone.js implementation. This is not yet a fully supported configuration. Find more at https://angular.io/errors/NG05000`

![image](https://github.com/angular/angular/assets/56136563/9d85097f-aa70-4119-bccd-3fa4935afc4c)

**Comment by JeanMeche** [comment]
Hi, this issue was already fixed by #55554 and will be shiped with the next patch release.
