### ISSUE TITLE
first-app.zip missing essential files

### ISSUE THREAD

**Issue by vinibiavatti1** [angular/angular#56064]
### Describe the problem that you experienced

In the [Download the default app](https://angular.dev/tutorials/first-app/01-hello-world#download-the-default-app) step of the Angular tutorial, we must click on code editor's download button to get the default app code and start learning. However, the downloaded zip folder does not contain some necessary files (like package.json), in which is listed in the third step: [Review the files in the project](https://angular.dev/tutorials/first-app/01-hello-world#review-the-files-in-the-project). Without these files, the application cannot be built.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app/01-hello-world#download-the-default-app

### Describe what you were looking for in the documentation

Tutorial to learn Angular

### Describe the actions that led you to experience the problem

1. Access the Angular Tutorial at angular.dev;
2. At [Download the default app](https://angular.dev/tutorials/first-app/01-hello-world#download-the-default-app) section, click on the code editor download button to get the source code for tutorial;
3. At [Test the default app](https://angular.dev/tutorials/first-app/01-hello-world#test-the-default-app), try to perform `npm install` command.
4. The command will not work since the `package.json` file is missing.

I also tried using the source code from the tutorial introduction page (https://angular.dev/tutorials/first-app) but it also doesn't have the necessary files.

### Describe what you want to experience that would fix the problem

The listed files in [Review the files in the project](https://angular.dev/tutorials/first-app/01-hello-world#review-the-files-in-the-project) should be present in the zip file downloaded from code editor.

**Comment by geromegrignon** [comment]
I can't reproduce it myself (Chrome/MacOS) but we got multiple people asking for related help on Angular Discord server.

**Comment by brandon-sia** [comment]
having the same issue here, the problem is the downloaded zip file does not contain the package.json. This experience can be very frustrating for beginners. 
![image](https://github.com/angular/angular/assets/67773189/a75b320a-51cd-44a6-a8d5-77bbb26d5fe4)

**Comment by geromegrignon** [comment]
@brandon-sia I uploaded all files on this repo to help you: https://github.com/geromegrignon/first-app_01-hello-world

**Comment by brandon-sia** [comment]
@geromegrignon Thanks you're a legend!

**Comment by vinibiavatti1** [comment]
@geromegrignon Thanks for help. I solved this by using the `ng new` command and moving some files to my repo. I noticed that other files are missing: 
- `package.json`
- `angular.json`
- `tsconfig.json`

**Comment by Drexel2k** [comment]
The download button doesn't work for me at all, tried Chrome, Firefox and Edge. On Windows 11 and Ubuntu (the first two browser)...
