### ISSUE TITLE
Links refer to non-existent web endpoints

### ISSUE THREAD

**Issue by atiris** [angular/angular#56066]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When the cli reports any documentation links, it refers to angular.io. For example in this demo https://angular.io/errors/NG05000

However, there will be a remeasurement to the address https://v17.angular.io/errors/NG05000 and that's the end of it. No other redirection and only shows Page is not available. Expected link is https://angular.dev/errors/NG05000

Please edit the links to angular.dev.  
I suppose that a redirect to angular.dev can be done as a temporary solution, but I believe that the solution is to fix the code in the cli.

The link is from this message, but I assume it will be the same for any documentation link. `NG05000: Angular detected that hydration was enabled for an application that uses a custom or a noop Zone.js implementation. This is not yet a fully supported configuration. Find more at https://angular.io/errors/NG05000`

### Minimal Reproduction

In this case you can create app with `ng new xyz --ssr true` and continue according to https://angular.dev/guide/experimental/zoneless. Then start with `ng serve` but I thing this is more general bug.

### Your Environment

```text
Angular CLI: 18.0.1
Node: 20.13.1
Package Manager: npm 10.8.0
OS: win32 x64

Angular: 18.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.1
@angular-devkit/build-angular   18.0.1
@angular-devkit/core            18.0.1
@angular-devkit/schematics      18.0.1
@angular/cli                    18.0.1
@angular/ssr                    18.0.1
@schematics/angular             18.0.1
rxjs                            7.8.1
typescript                      5.4.5
```

**Comment by JeanMeche** [comment]
Hi, it looks like there is an issue with the service work. It you clean your cache, you'll be fine.

**Comment by alan-agius4** [comment]
These errors are generated by the framework runtime and not by the Angular CLI.

**Comment by atiris** [comment]
Hi. Thank you both for the guidance.  
If i could ask you nicely, could you tell me more precisely which cache it is? I tried this:

```cmd
npm cache clean --force
rmdir /s node_modules
npm i
ng cache clean
# close and open command line window
ng serve -o
... but still ... Find more at https://angular.io/errors/NG05000
```

This is new project (not after ng update).

**Comment by atiris** [comment]
I clicked "Clear site data" on "http://localhost:4200/", "https://angular.dev/" and "https://github.com" just to be sure (which logged me out 🙄). This was not possible for angular.io, which immediately redirected me to angular.dev, so i couldn't open devtools for angular.io domain.

![image](https://github.com/angular/angular/assets/10474618/48a6bff2-df02-4c5a-aa64-45efce21f3e1)

However, after launch I still see it like this.

![image](https://github.com/angular/angular/assets/10474618/5695bf22-fb68-4828-9627-4a4fb045707b)

Then I tried this setting in chrome on the url: chrome://settings/content/all?searchSubpage=angular and delete all content for localhost, angular.io and angular.dev and close and open browser

![image](https://github.com/angular/angular/assets/10474618/9aad2dae-edab-4afe-92b4-59acf4d8aa0d)

After run ng server again, message is still: **Find more at https://angular.io/errors/NG05000** with angular.io.  
Then, click on it, it redirects me to https://v17.angular.io/docs not to angular.dev.  
It's still not ok, but at worst I won't end up with a non-existent site.

**Comment by JeanMeche** [comment]
You need clear it when on  `https://v17.angular.io/docs`

Also, we fixed the url in the logs, they will be shipped with the next patch version.

**Comment by atiris** [comment]
Ok, now (after clear) https://angular.io/errors/NG05000 redirects to https://v17.angular.io/docs  
Then (I assume) that the application for v17 (v17.angular.io) is cached again and when I enter the url (https://angular.io/errors/NG05000) second time, it is processed differently, in case of a second attempt to open this url I get no redirect but "canceled" and "CORS policy error". Tested in incognito mode.

![image](https://github.com/angular/angular/assets/10474618/a550519d-bee2-4482-a88d-ceb4ebee1441)

Can you confirm this (that second time is link from cli unavailable)?  
But this issue is about links from cli that still points to angular.io like _Find more at https://angular.io/errors/NG05000_  
So if you already fixed this in cli next patch version, we can wait and ignore this strange behavior on the second visit to the url redirected from angular.io to v17.angular.io. Since it doesn't look like a bug in the cli, but in the processing of the redirect in the application v17.angular.io.

And you can close this bug report also when it is already fixed internally and it will be published in the next patch.

Thank you all.

**Comment by sasidharansd** [comment]
Hi @JeanMeche , Does this related to the same issue? Accessed the link 'https://v17.angular.io/api/common/NgTemplateOutlet'  posted on one of the recent issue. Getting site can't be reached message.  This also occurs to few of my aio bookmarked links as well. 

<img width="1440" alt="image" src="https://github.com/angular/angular/assets/47988127/4b094722-a385-4ed6-bbbf-ec6b8befe088">

**Comment by alxhub** [comment]
Closing as the service worker issues were resolved, and the runtime does correctly generate angular.dev links now.
