### ISSUE TITLE
httpclient doesnot work after updating v17 >> v18

### ISSUE THREAD

**Issue by aristotekean** [angular/angular#56077]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

Hi everyone, thanks for your amazing work developing angular v18. I was working with the version 17.3.0 and updated it to the version 18.0.1 following the guide on https://angular.dev/update-guide?v=17.0-18.0&l=1, the clasic ng update @angular/core@18 @angular/cli@18, my app compiles without problems but the calls to my backend stopped working, I have my production app working with angular v17 and it works well but in my local with the version v18 it doesn't work.

<img width="917" alt="image" src="https://github.com/angular/angular/assets/12689339/82695a2e-0a40-427f-aa75-10d6b063358f">

<img width="1276" alt="image" src="https://github.com/angular/angular/assets/12689339/187b717b-ccea-4a18-8c1b-f70215faae70">

### Please provide the exception or error you saw

```true
No problems have been detected in the visual studio code or the terminal
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.1
Node: 20.12.1
Package Manager: npm 10.5.0
OS: darwin arm64

Angular: 18.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.1
@angular-devkit/build-angular   18.0.1
@angular-devkit/core            18.0.1
@angular-devkit/schematics      18.0.1
@angular/cli                    18.0.1
@schematics/angular             18.0.1
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.4
```

### Anything else?

I added the provideExperimentalZonelessChangeDetection API but even if I don't use it, it is still not working

**Comment by JeanMeche** [comment]
Hi, this is hardly actionable to us without a repro. Could you provide a narrowed down repro on stackblitz or a github repro ?

**Comment by aristotekean** [comment]
Sorry, I cleaned everything and then I did a rollback to v17 and then I updated it again to v18 and it works

**Comment by aristotekean** [comment]
I found the problem, it happens when you activate the experimental provideExperimentalZonelessChangeDetection to work without zone.js

`bootstrapApplication(App, {
  providers: [
    provideExperimentalZonelessChangeDetection()
  ]
});`

No problem, it's experimental :)
