### ISSUE TITLE
New Control Flow with optional braces

### ISSUE THREAD

**Issue by hannah23280** [angular/angular#56084]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

As an example

```
@if(xxxx){
       <li>true</li>
} @else{
    <li>false</li>
}
```

Problem: adding the opening and closing braces seem to clutter the html code, when there is only one line of "statement" for each control flow. This applies to other control flow such as @for and @else if ,  @empty as well.

### Proposed solution

make opening and closing braces optional when there is only one line of html code under each control flow structure
```
@if(xxxx)
       <li>true</li>
@else
    <li>false</li>

```
similar to control flow in typical programming language
```
if(xxx)
     console.log("true")
else
    console.log("false")

```
Of course, if developer writes as shown below , error should be thrown.  
```
@if(xxxx)
       <li>true1</li>
      <li>true2</li>   <-- cause error, just like in a typical programming language
@else
    <li>false</li>
```

### Alternatives considered

NA

**Comment by JoostK** [comment]
We've discussed this and decided not to go this route. In Angular templates it's less clear what constitutes a statement, e.g.

```html
@if (condition)
  Hello world
  <br>
```

Here, would you expect the `br` to be within the `@if`-block, or outside of it? Whitespace makes this even more muddled.
