### ISSUE TITLE
Dart: Router: routerCanReuse not called

### ISSUE THREAD

**Issue by mark1010** [angular/angular#5608]
I'm attempting to use the router re-use methods under Dart. Looking at the docs I expect `routerCanReuse` to be called to determine whether a component can be reused. (I'd expect this to occur 'early' in the lifecycle management). In practice the `routerCanReuse` doesn't seemed to be called at all.

The example below is based on https://angular.io/docs/ts/latest/api/router/CanReuse-interface.html, with MyCmp plugged into the playground/routing example.

angular2: "2.0.0-alpha.47"

```
@RouteConfig(const [...,
  const Route(path: '/my-cmp/:name', component: MyCmp, name: 'MyCmp'),
  ]
)
```
 ```
import 'package:angular2/angular2.dart';
import 'package:angular2/router.dart';
import 'package:logging/logging.dart';

@Component(selector: 'my-cmp'
)
@View(
    encapsulation: ViewEncapsulation.None,
    template: """
    Hello {{name}}
    """,
    directives: const [
    ])
class MyCmp implements OnInit, OnDestroy, CanReuse, OnReuse {
  final Logger _logger = new Logger('MyCmp');

  String name = '';

  MyCmp() {
    _logger.fine('MyCmp()');
  }

  ngOnInit() {
    _logger.fine('ngOnInit');
  }

  ngOnDestroy() {
    _logger.fine('ngOnDestroy');
  }


  routerCanReuse(ComponentInstruction nextInstruction,
      ComponentInstruction prevInstruction) {
    _logger.fine('routerCanReuse');
    return true;
  }


  routerOnReuse(ComponentInstruction nextInstruction,
      ComponentInstruction prevInstruction) {
    _logger.fine('routerOnReuse nextInstruction: $nextInstruction, prevInstruction: $prevInstruction');
    this.name = nextInstruction.params['name'];
  }
}
```
log output, switching routes between MyCmp -> RouteOneCmp -> MyCmp, I expected to see a call to `routerCanReuse`, and MyCmp to be reused.
```
FINE: 2015-12-04 17:14:02.800: MyCmp: MyCmp()
FINE: 2015-12-04 17:14:02.813: MyCmp: ngOnInit
FINE: 2015-12-04 17:14:06.718: MyCmp: ngOnDestroy
FINE: 2015-12-04 17:14:06.725: RouteOneCmp: RouteOneCmp()
FINE: 2015-12-04 17:14:06.726: RouteOneCmp: routerOnActivate
FINE: 2015-12-04 17:14:06.728: RouteOneCmp: ngOnInit
FINE: 2015-12-04 17:14:14.248: RouteOneCmp: ngOnDestroy
FINE: 2015-12-04 17:14:14.249: MyCmp: MyCmp()
FINE: 2015-12-04 17:14:14.250: MyCmp: ngOnInit
```

**Comment by btford** [comment]
This is not how CanReuse works– CanReuse only deals with the case where a component would be reinstantiated as part of a navigation (for instance, MyCmp -> MyCmp, but with different route params).

The router currently does not support something like this directly.

What's the motivation for this use?

**Comment by mark1010** [comment]
In this instance I was trying to figure out how the api behaved, thanks for clarifying.

(I have a file system like browser with /fs/123/456/../../789, where /123/456/.. would be folders ids and 789 a file. I think CanReuse may help there.)

**Comment by btford** [comment]
Gotcha. Can this issue be closed, then? :)

**Comment by mark1010** [comment]
Yes.
