### ISSUE TITLE
reference documentation on angular.io advises readers to read current documentation on angular.io

### ISSUE THREAD

**Issue by jnizet** [angular/angular#56082]
### Describe the problem that you experienced

I went to https://v17.angular.io/api/forms/FormControl, and got the following alert:

<img width="822" alt="Capture d’écran 2024-05-26 à 16 46 14" src="https://github.com/angular/angular/assets/1608223/68af0c5d-6e3a-4ee6-9a01-29345e46349a">

Clicking the link navigates to the same page.

### Enter the URL of the topic with the problem

https://v17.angular.io/api/forms/FormControl

### Describe what you were looking for in the documentation

NA

### Describe the actions that led you to experience the problem

NA

### Describe what you want to experience that would fix the problem

The link should advise the reader to go to angular.dev, and the link should point to angular.dev.

**Comment by jnizet** [comment]
@JeanMeche Man, you're fast.

![Picture of Lucky Luke, the man who shoots faster than hiw own shadow](https://www.searchamateur.com/pictures/lucky-luke.jpg)

**Comment by LynnColgrove** [comment]
Is V17 documentation available? If I go to https://angular.dev/overview and try to change the version drop down on the upper left side from V18 to V17, I am routed to https://v17.angular.io/docs. I get an error that the site is not found.  I can go to https://v16.angular.io/docs without a problem.

**Comment by JeanMeche** [comment]
The v17 doc site has currently service worker issues. We are looking into it. The previous doc site are all meant to be accessible 👍

**Comment by LynnColgrove** [comment]
Thank you, V17 documentation is accessible now.
