### ISSUE TITLE
Angular version 18 not compatible with @swimlane/ngx-charts version 20.4.1

### ISSUE THREAD

**Issue by M-Muddasir** [angular/angular#56099]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Angular version 18 not compatible with @swimlane/ngx-charts version 20.4.1

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular Cli: 18
Node: 22
```

**Comment by JeanMeche** [comment]
Please see directly with the maintainer of this library.
