### ISSUE TITLE
FEATURE: angular effects untracked SkipInitial

### ISSUE THREAD

**Issue by ScriptType** [angular/angular#56098]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

The effect has to do an Initial run to keep track of the used signal, If we have untracked inside of it it would be nice to skip the Initial run.

### Proposed solution

```typescript
constructor() {
  effect(() => {
      const someSignalValue = this.signalStuff()
      untracked(() => {
         this.doSomethingWithValue(someSignalValue)
      },{skipInitial: true});
    });
}
```

### Alternatives considered

```typescript
constructor() {
let skipInitial = true;
  effect(() => {
      const someSignalValue = this.signalStuff()
      untracked(() => {
         if (skipInitial) {
             skipInitial = false;
             return;
         }
         this.doSomethingWithValue(someSignalValue)
      });
    });
}
```

**Comment by JeanMeche** [comment]
`effect` needs that first run to register its producers. Without it, there won't subsequent runs when the signals are updated. 

You could even argue that the framework should throw if the effect has no registred producers on the first run.

**Comment by pkozlowski-opensource** [comment]
> would be nice to skip the Initial run

Could you tell us more about the real-life use-case? Why would the "initial run" be any special?

**Comment by ScriptType** [comment]
In A Custom Form Component i use signals and effect´s to call onChange. The Problem with the initial run is the component directly becomes pristine === false .

**Comment by e-oz** [comment]
I don't get the idea, but curios to see a real example on StackBlitz.

**Comment by pkozlowski-opensource** [comment]
Agree with @e-oz - it is hard to understand the real-life use-case here. We really need code example in a stackblitz - otherwise it is not actionable for us.

**Comment by pkozlowski-opensource** [comment]
I'm going to close this one since we didn't get more concrete info besides

> In A Custom Form Component i use signals and effect´s to call onChange. The Problem with the initial run is the component directly becomes pristine === false .

In this case the effect could skip processing under specific conditions. Again, hard to say more given the available information.
