### ISSUE TITLE
NG0955 and NG0956 pages rendered incorrectly

### ISSUE THREAD

**Issue by json-derulo** [angular/angular#56090]
### Describe the problem that you experienced

When entering the detail page for error NG0955 and NG0956, the page is not rendered properly. There should be a title, edit button etc. It seems like the meta info of the error is not handled correctly. See the screenshot below.

### Enter the URL of the topic with the problem

https://angular.dev/errors/NG0955

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/18580672/3945b6b9-8f39-4736-a88d-84fdd9f8368b)

It should look like this:

![image](https://github.com/angular/angular/assets/18580672/9b48d38c-1c58-4e40-a69b-d499e069147f)

**Comment by JeanMeche** [comment]
Hi, this is being addressed by #55706.
Thank you for reporting this issue.
