### ISSUE TITLE
Let `@Input({ transform })` function change the type of the data

### ISSUE THREAD

**Issue by DzmVasileusky** [angular/angular#56104]
### Description

`transform` function in the `@Input` decorator was introduced as a replacement of the `@Input() set`, but it doesn't allow to change the data type.
Before we did
```
interface UserData { name: string; surname: string; title: string; };

...

@Input() set user (data: UserData) {

    this.fullName = `${title} ${name} ${surname}`;

}

fullName: string;
```

So the data is shaped from one type to another one. While doing it in transform function causes strict templates errors.

### Proposed solution

```
interface UserData { name: string; surname: string; title: string; };

...

function toFullName (data: UserData): string {

  return `${title} ${name} ${surname}`;

}

...

@Input({ transform: toFullName }) user: UserData: 
```

### Alternatives considered

-

**Comment by JeanMeche** [comment]
This is one of the issue of decorator inputs. Decorators have no influence on typing. 

If you want fully typed inputs please use signal inputs that we introduced in v17.1.

**Comment by DzmVasileusky** [comment]
@JeanMeche that works, thank you
