### ISSUE TITLE
Dead link in update guide

### ISSUE THREAD

**Issue by mwaibel-go** [angular/angular#56101]
### Describe the problem that you experienced

The update guide on [angular.dev/update-guide for the v14→v15 migration](https://angular.dev/update-guide?v=14.0-15.0&l=3) has this link:

> Make sure to use decorators in base classes with child classes that inherit constructors and use dependency injection. Such base classes should be decorated with either @Injectable or @Directive or the compiler returns an error. [Read further](https://angular.io/guide/update-to-version-15#v15-bc-05)

which just redirects to https://v17.angular.io/docs

### Enter the URL of the topic with the problem

https://angular.dev/update-guide?v=14.0-15.0&l=3

**Comment by JeanMeche** [comment]
The correct link should be: https://v15.angular.io/guide/update-to-version-15

**Comment by Neil-Runcie** [comment]
It looks like all of the links on the https://angular.dev/update-guide?v=14.0-15.0&l=3 page redirect to the https://v17.angular.io/docs. Can I take this issue? @JeanMeche

**Comment by JeanMeche** [comment]
@Neil-Runcie feel free to drop a PR !
