### ISSUE TITLE
test `firefox extension should measure performance` is flaky

### ISSUE THREAD

**Issue by tbosch** [angular/angular#5611]

**Comment by jelbourn** [comment]
Example of this flake manifesting: https://travis-ci.org/angular/angular/jobs/94747809#L838

**Comment by hankduan** [comment]
There was a previous attempt to fix this: https://github.com/angular/angular/pull/4985, but I guess it didn't work. I'll investigate again around week of 12/14

**Comment by pkozlowski-opensource** [comment]
Yeh, saw it today as well

**Comment by vicb** [comment]
I can see it every week for the past months

**Comment by IgorMinar** [comment]
if we can't get this fixed tomorrow, we should disable the test ASAP. the productivity lost is too big.

**Comment by IgorMinar** [comment]
@hankduan we can't wait until 12/14, @tbosch can you please submit a workaround tomorrow?

**Comment by tbosch** [comment]
Ok, created a PR, will be merged soon.

**Comment by hankduan** [comment]
See https://github.com/angular/angular/pull/6161

**Comment by hankduan** [comment]
Now that #6161 is submitted, the flake should be gone. Let me know if it is still an issue.
