### ISSUE TITLE
Server side rendering doesn't wait for API calls on route resolvers or guards to finish

### ISSUE THREAD

**Issue by quedicesebas** [angular/angular#56110]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I'm trying to set the SEO tags (title and metatags) dinamically depending on domain my app is loaded. I am providing the request hostname to achieve that, and calling an API in my route resolver:
Resolver:
```
export const seoResolver: ResolveFn<NgxSeo | undefined> = (
  route: ActivatedRouteSnapshot,
  state: RouterStateSnapshot,
) => inject(MainService).store$?.pipe(map((store?: Store) => store?.seo));
```
Route. I'm used ngx-seo, so title and metatags are set from `seo` data field. Before using a api call, everithing was working:
```
  {
    path: '',
    component: HomePageComponent,
    resolve: { seo: seoResolver },
  },
```

I also tried using a canActivate guard.
Guard:
```
export const seoGuard: CanActivateFn = (route, state) => {
  const hostname = inject(MainService).hostname;
  const titleService = inject(Title);

  // calling our API service like we would usually do but instead of a subscribe, we do a pipe map.
  return inject(MainService).store$.pipe(
    map((store?: Store) => {
      if (store?.seo.title) {
        titleService.setTitle(store?.seo.title);
      }
      return true;
    }),
  );
};
```
Route:
```
  {
    path: '',
    component: HomePageComponent,
    canActivate: [seoGuard],
  },
```

None of the above works for me.
My problem is that crawlers as whatsapp, facebook, an others, always saw the rendered html before the resolver finish, so I'm not getting the required tags and previews for my app. For example in [facebook](https://developers.facebook.com/tools/debug/echo/?q=https%3A%2F%2Fssr--la-comanda-co.us-central1.hosted.app%2F). 
Or checking the [source in Chorme](view-source:https://ssr--la-comanda-co.us-central1.hosted.app/).
I'm deploying on the new Firebase App Service. I tried with and without prerendering and the same thing happens.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.0
Node: 20.12.1
Package Manager: npm 10.5.1
OS: win32 x64

Angular: 18.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.0
@angular-devkit/build-angular   18.0.0
@angular-devkit/core            18.0.0
@angular-devkit/schematics      18.0.0
@schematics/angular             18.0.0
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.4
```

**Comment by JeanMeche** [comment]
Server rendering relies on application stability to send the rendered HTML back to the client. 
If the HTML generated doesn't includes the expected HTML, it means that your app became stable before the store returned the data. 
By default the HttpClient maintains the app unstable while there are pending requests. I don't think the store expose the same behavior. 
If you need to explicitly keep your app unstable, there different possibilities: 
* In zone apps (with zone.js loaded), you can create a pending promise that you can resolve when the data has been retrieved. 
* In zoneless apps, you'll yo rely on the [ExperimentalPendingTasks](https://angular.dev/api/core/ExperimentalPendingTasks) service. 
That being said, this behavior you are observing is expected.

**Comment by quedicesebas** [comment]
I didn't understand this: "If the HTML generated doesn't includes the expected HTML, it means that your app became stable before the store returned the data." And also, yoy said thaty HttpCliente keeps de app unstable, and I'm suing HttpCLlent in my requests.
I managed to make it work deploying on the new App Hosting in Firestore, using prerrender: false in the angular json.
