### ISSUE TITLE
Property Binding gets affected (not working) due to order of elements in the HTML

### ISSUE THREAD

**Issue by sumit87dgp** [angular/angular#56126]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Property Binding stopped working when the html element was placed after the nested elements in the html page. But it worked fine when the html element with property binding was defined before the nested elements.

_**component.html that did not work**_

`<p>servers works!</p>
<app-server></app-server>
<app-server></app-server>
<button type="button" class="btn btn-primary" [disabled]="!allowNewServers">Add New Server</button>`

**_component.html that did work fine_**

`<p>servers works!</p>
<button type="button" class="btn btn-primary" [disabled]="!allowNewServers">Add New Server</button>
<app-server></app-server>
<app-server></app-server>`

**_component.ts file which remains unchanged for both versions of the html file._**

`import { Component, OnInit } from '@angular/core';
@Component({
  selector: 'app-servers',
  templateUrl: './servers.component.html',
  styleUrl: './servers.component.css'
})
export class ServersComponent implements OnInit {
  allowNewServers = false;

  constructor(){
    setTimeout(()=>{
      this.allowNewServers = true;
    },2000)

  }
  ngOnInit() {
    throw new Error('Method not implemented.');
  }
}
`

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.7
Node: 20.13.1
Package Manager: npm 10.5.2
OS: linux x64

Angular: 17.3.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.7
@angular-devkit/build-angular   17.3.7
@angular-devkit/core            17.3.7
@angular-devkit/schematics      17.3.7
@angular/cli                    17.3.7
@schematics/angular             17.3.7
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.6
```

**Comment by JoostK** [comment]
If anything, this is likely an ExpressionChangedAfterItHasBeenChecked situation. Throwing an error from `ngOnInit` is also suspicious. Please provide a runnable reproduction as otherwise this isn't actionable to us.

**Comment by JeanMeche** [comment]
Rendering throws, this will prevent the expected behavior. 
Remove your exception and it works fine.

**Comment by sumit87dgp** [comment]
@JeanMeche,
Removed the exception still it is the same issue.

**Comment by sumit87dgp** [comment]
Ahh!! I got the error...
My Bad...
