### ISSUE TITLE
[adev] v18 Version compatibility

### ISSUE THREAD

**Issue by geromegrignon** [angular/angular#56121]
### Describe the problem that you experienced

The Version compatibility reference (https://angular.dev/reference/versions) does not list v18.

If based on the root package.json engine rules (https://github.com/angular/angular/blob/main/package.json#L11), the values should be the same as 17.3

### Enter the URL of the topic with the problem

https://angular.dev/reference/versions

**Comment by JoostK** [comment]
This is being addressed in #56034

**Comment by JeanMeche** [comment]
Closing as a dupe of #56033
