### ISSUE TITLE
ComponentRef.setInput is not using the type information from the ComponentRef

### ISSUE THREAD

**Issue by JonWallsten** [angular/angular#56120]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When writing unit tests for components with InputSignal I have to use ComponentRef.setInput to set the value.
But the setInput parameter `name` is using the type `string` so I don't get any feedback when entering the wrong property name
![image](https://github.com/angular/angular/assets/5993909/9b4eb825-dd30-4b44-97c9-6b4c6022787e)

It could be fixed by using `keyof C` instead of `string` but I'm not sure about the consequences of that change.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-y2i6u1?file=src%2Ftest.ts

### Please provide the exception or error you saw

```true
No error is thrown when entering the wrong parameter.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.1
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.1
@angular-devkit/build-angular   18.0.1
@angular-devkit/core            18.0.1
@angular-devkit/schematics      18.0.1
@angular/cli                    18.0.1
@schematics/angular             18.0.1
rxjs                            7.8.1
typescript                      5.4.5
zone.js
```

**Comment by JeanMeche** [comment]
Hi, please have a look at #51878, this is not straight forward as aliases have to be supported.
