### ISSUE TITLE
API references not showing Usage Notes examples

### ISSUE THREAD

**Issue by lucaspottersky** [angular/angular#56136]
### Describe the problem that you experienced

The doc reads "The following example shows the result of transforming various strings into title case.", but shows nothing below.

### Enter the URL of the topic with the problem

https://angular.dev/api/common/TitleCasePipe?tab=usage-notes

### Describe what you were looking for in the documentation

Something like https://v13.angular.io/api/common/UpperCasePipe

```
Transforms text to all upper case.

{{ value_expression | [uppercase] }}
```

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/1385118/8fa368ca-e185-4abb-b002-52c5d4b99daa)

**Comment by JeanMeche** [comment]
Let's continue tracking this issue with #56068 as it's the same root cause.
