### ISSUE TITLE
JSONP JSON_CALLBACK Undefined

### ISSUE THREAD

**Issue by btormey** [angular/angular#5613]
**Overview**
When making a JSONP request, I expected to be able to set a `callback` parameter in the query string set to `JSON_CALLBACK` (as per this issue https://github.com/angular/angular/issues/4663) and have Angular unwrap the response without any extra configuration. However, when doing this an exception of 

> Uncaught ReferenceError: JSON_CALLBACK is not defined
> EXCEPTION: TypeError: JSONP injected script did not invoke callback

is thrown. The only way around this I have found is to set the `callback` parameter equal to `__ng_jsonp__.__req0.finished`. However, that seems a bit hacky. I noticed this issue had been noted a few times in Angular 1.x with users having to set the `callback` parameter to `angular.callbacks._0`.

**Angular Version(s)**
Found in 2.0.0-alpha.44

**Browsers and Operating System**
Tested in Chrome 42 and IE 11

**Reproduce the Error**
Working JSONP (Angular 1.x) http://jsfiddle.net/subhaze/a4Rc2/114

Not working Angular 2
```
import {bootstrap, Component} from 'angular2/angular2';
import {Jsonp, JSONP_PROVIDERS} from 'angular2/http';

@Component({
    selector: 'search',
    templateUrl: 'app/search.html'
})
class SearchComponent { 
    jsonp:Jsonp;
      
    constructor(jsonp: Jsonp) {
        this.jsonp = jsonp;
        this.search();
    }
  
    search() {
        var url = 'http://public-api.wordpress.com/rest/v1/sites/wtmpeachtest.wordpress.com/posts?callback=JSON_CALLBACK';
        this.jsonp.get(url).subscribe(results => console.log(results));
    }
}

bootstrap(AppComponent, [Jsonp, JSONP_PROVIDERS]);
```

**Comment by btormey** [comment]
Ah! I found the issue. It slipped my eye the first time I looked at the code, but it looks like Angular 2 is searching the url for 'JSONP_CALLBACK' whereas Angular 1.x was searching for 'JSON_CALLBACK'. 

https://github.com/angular/angular/blob/master/modules/angular2/src/http/backends/jsonp_backend.ts#L45-L50

I guess it's just a matter now as to whether or not to leave it as 'JSONP_CALLBACK' or change it to 'JSON_CALLBACK' to match Angular 1.x.

**Comment by jeffbcross** [comment]
Thanks for reporting, @btormey! I think we should change it for consistency.

**Comment by PascalPrecht** [comment]
That's a good catch! But honestly, I find that `JSONP_CALLBACK` makes technically more sense.

**Comment by btormey** [comment]
@PascalPrecht I tend to agree that it makes more sense, however I'm not sure if it's worth changing to `JSONP_CALLBACK` in exchange for decreased consistency since it's just an arbitrary string token.

Either way, this piece of code still deserves a look. I'm not sure why the `if/else if` is needed here as I believe we could achieve the same thing with
```
let url: string = StringWrapper.replace(req.url, '=JSONP_CALLBACK', `=${callback}`);
```
It also seems like this should be done *after* the request returns. If you are using something like OAuth where the signature is generated from the parameters, you will get "Invalid Signature" every time since the request was signed with `callback=JSON_CALLBACK`, but the request passed in contains something like `callback=__ng_jsonp__.__req#.finished` It appears that's what is being done in Angular 1.x (https://github.com/angular/angular.js/blob/master/src/ng/httpBackend.js#L68-L72), correct me if I am interpreting that wrong, though.

**Comment by Barryrowe** [comment]
I'm probably missing something, but is there any reason that ```callback=JSON(P)_CALLBACK``` should be required to be appended to the url if deferring to Jsonp for automatically setting up the callback function? If the url does not contain "callback=" this default could be appended prior to the request.

This threw me for a loop, and I was running into the error:

    JSONP injected script did not invoke callback.

I added the callback parameter with JSONP_CALLBACK and everything was good. Seems like an unnecessary burden on the consumer of Jsonp to remember to add this "magic parameter" when you're not providing your own callback function name.

**Comment by Barryrowe** [comment]
I'm thinking something like this:

```JavaScript
   if (url.indexOf('callback=') < 0){
       let delimiter = url.indexOf("?") < 0 ? "?" : "&";
       url = url.concat(`${delimiter}callback=${callback}`);
   } else if (url.indexOf('=JSONP_CALLBACK&') > -1) {
        url = StringWrapper.replace(url, '=JSONP_CALLBACK&', `=${callback}&`);
   } else if (url.lastIndexOf('=JSONP_CALLBACK') === url.length - '=JSONP_CALLBACK'.length) {
        url = url.substring(0, url.length - '=JSONP_CALLBACK'.length) + `=${callback}`;
   }
```

**Comment by robwormald** [comment]
This issue was moved to angular/http#57

**Comment by playground** [comment]
I know I shouldn't have to be doing this.  If I changed the function name in my json file to be __ng_jsonp__.__req0.finished({...}), it works.  What am I missing?
