### ISSUE TITLE
ActivatedRoute in Directive: Snapshot.params are not getting updated

### ISSUE THREAD

**Issue by spirosdi** [angular/angular#56157]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

When injecting ActivatedRoute in a directive and trying to get the route params calling this.activatedRoute.snapshot.params, the params returned are not the ones of the current route, but the ones from the first route visited. The issue appeared after updating @angular/core and @angular/router from 17.2.2 to 17.3.1. In 17.2.2 it works as expected, the params returned are the ones of the current route.

I provide a link to a minimal reproduction repo. In order to reproduce the issue is important to follow these steps:
1. Navigate to http://localhost:4200/id-1/child 
2. Click the '/id-2' link to route to http://localhost:4200/id-2
3. Click the '/id-2/child' link to route to http://localhost:4200/id-2/child
4. Click the "Click and check console" button
5. The params logged in the console are `{id: 'id-1'}` but they should be `{id: 'id-2'}`

### Please provide a link to a minimal reproduction of the bug

https://github.com/spirosdi/activated-route-bug-reproduction

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.8
Node: 20.9.0
Package Manager: npm 10.1.0
OS: darwin x64

Angular: 17.3.2
... animations, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8
@angular-devkit/schematics      17.3.8
@angular/cli                    17.3.8
@schematics/angular             17.3.8
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.6
```

**Comment by JeanMeche** [comment]
Hi, luckily this has already been fixed by #55374 and landed in 18.0.
