### ISSUE TITLE
Post V17 deprecations not found

### ISSUE THREAD

**Issue by moueza** [angular/angular#56162]
### Describe the problem that you experienced

https://angular.dev/guide/deprecations : but this location is 404 error

### Describe what you were looking for in the documentation

I was searching for V18 deprecations. So I found previous https://v17.angular.io/guide/deprecations linking to https://angular.dev/guide/deprecations : but this location is 404 error

**Comment by JeanMeche** [comment]
In an effort to reduce the maintenance work around the deprecation page, it was decided to not port it to the new documentation. 

Deprecations are thoroughly listed in our release notes. 

Check for example the entries for v18 : https://github.com/angular/angular/releases/18.0.0#Deprecations
