### ISSUE TITLE
Syntax highlighting on angular.dev should have better contrast 

### ISSUE THREAD

**Issue by mgechev** [angular/angular#56163]
### Is this a regression?

Yes (regression compared to aio).

### Description

Here the string and the expression inside if it have very similar color that doesn't meet contrast standards:

![unnamed](https://github.com/angular/angular/assets/455023/32a7b7f8-8ba2-485d-9554-c4fe8a69907f)

### Please provide a link to a minimal reproduction of the bug

https://angular.dev/guide/signals#computed-signal-dependencies-are-dynamic

**Comment by JeanMeche** [comment]
This issue has already been raised, let's continue tracking this issue in #52654.

**Comment by mgechev** [comment]
This seems like a regression compared to aio, that's why I opened it as a separate issue.

@JeanMeche would you update the issue you referenced to make sure contrast takes a more prominent place and we don't miss it by mistake?

**Comment by JeanMeche** [comment]
I'll make sure of it !
