### ISSUE TITLE
Inconsistent Back/Forward Button behaviour with Angular Fragment Routing

### ISSUE THREAD

**Issue by mohammedsahl** [angular/angular#56166]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description
I encounter unexpected behaviour with Angular routing when using anchor tags with fragments (#) for in-page navigation.

- Using routerLink='.' fragment='fragment-id' allows in-page navigation with fragments, but the browser back button functionality is broken (I think?).
- Navigating directly to a fragment URL (e.g., http:localhost:4200/crisis-list#section1) and then using internal fragment links works as expected (mimics vanilla HTML behaviour).
- The issue lies specifically with navigating between fragments on the same page using internal links when the initial page load includes a fragment and the back/forward button is used. This creates inconsistencies in the Angular router stack.

Is this expected behaviour?

Here's a video describing the situation (please excuse the idling 😅). The relevant parts are 1:22 onwards where I navigate from /crisis-list#top to /crisis-list#section1 by typing it out and pressing enter and then pressing the back button. But everything before that is important too I guess.

https://github.com/angular/angular/assets/32067562/cd0549da-583d-4ee9-95e6-abc953bf5312

### Expected Behavior
Clicking the back button after navigating between fragments using internal links should return to the previous fragment state.

### Actual Behavior
Clicking the back button after navigating between fragments using internal links results in unexpected behavior and an inconsistent router stack.

### Please provide a link to a minimal reproduction of the bug

https://github.com/mohammedsahl/angular-routing-sandbox

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.0
Node: 20.12.1
Package Manager: npm 10.5.0
OS: darwin x64

Angular: <error>
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.0 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            17.3.0 (cli-only)
@angular-devkit/schematics      17.3.0 (cli-only)
@angular/cli                    17.3.0 (cli-only)
@schematics/angular             17.3.0 (cli-only)
rxjs                            7.8.1 (cli-only)
typescript                      <error>
zone.js                         <error>
```

**Comment by atscott** [comment]
From what I'm understanding, this isn't an issue with browser back/forward and history, but a problem with the scroll restoration, is that correct? If so, then yes, this is working as expected. 

The scroll history is stored in the application memory (`withInMemoryScrolling`), so by typing a new URL in the address bar, you're reloading the application and losing the scroll history. The native scroll restoration doesn't work well with SPAs but we have a long term goal of using native scroll restoration from the new Navigation API at some point.

**Comment by mohammedsahl** [comment]
Yes that is correct.

Thank you for the clarification @atscott.

**Comment by atscott** [comment]
Okay, thanks for confirming. I'm going to close this as working as expected.
