### ISSUE TITLE
docs: contradictory guidelines for use of `host`, `@HostListener` and `@HostBinding`

### ISSUE THREAD

**Issue by johnnygerard** [angular/angular#56170]
### Describe the problem that you experienced

The following guidelines contradict each other:

[Style 06-03](https://angular.dev/style-guide#style-06-03)
> Consider preferring the @HostListener and @HostBinding to the host property of the @Directive and @Component decorators.

[The @HostBinding and @HostListener decorators](https://angular.dev/guide/components/host-elements#the-hostbinding-and-hostlistener-decorators)
> Always prefer using the host property over @HostBinding and @HostListener. These decorators exist exclusively for backwards compatibility.

**Comment by JeanMeche** [comment]
Hi, thank you for reporting this issue. We intend to update the style guide  soon to make the recommendations more consistant. To answer your question, the recommendation will go toward the latter : use the host property.

Upcomming style guide updates is tracked by https://github.com/angular/angular/issues/54284.
