### ISSUE TITLE
HTML tokenization does not handle CR correctly

### ISSUE THREAD

**Issue by wardbell** [angular/angular#5618]
After upgrading from alpha46 to alpha47, there seems to be some extra spacing added when projecting elements via `ng-content` or using anything `<template>` related (`ng-if`, `ng-switch`, `ng-for`).

[copied from [Filipe's issue #440 registered in angular.io](https://github.com/angular/angular.io/issues/440) ]

plunker alpha46: http://plnkr.co/edit/698ShxZ0FhziYHxCu3t3?p=preview
![image](https://cloud.githubusercontent.com/assets/4172079/11558932/4e129a04-99ad-11e5-9e88-a2544edbb60c.png)

plunker alpha47: http://plnkr.co/edit/R8biozWaYxy1VcKJLqiQ?p=preview
![image](https://cloud.githubusercontent.com/assets/4172079/11558939/5ceec480-99ad-11e5-9ee0-2687ffd1aec7.png)

**Comment by vicb** [comment]
Probably linked to the content of the text node ("HQ alerts: no alerts, everything normal.")

On alpha 47 it is (char codes): 13-10-32-32-72-81

On alpha 46 it is: 10-32-32-72-81-...

Notice the extra CR on alpha 47.

Probably related to the new parser. I'll have to investigate more next week. 

/cc @tbosch

**Comment by vicb** [comment]
The clue might be http://www.w3.org/TR/html5/syntax.html#preprocessing-the-input-stream

_"CR" (U+000D) characters and "LF" (U+000A) characters are treated specially. All CR characters must be converted to LF characters, and any LF characters that immediately follow a CR character must be ignored. Thus, newlines in HTML DOMs are represented by LF characters, and there are never any CR characters in the input to the tokenization stage._

(related: LF has a special handling after `textarea, pre & listing`).

**Comment by vicb** [comment]
I have updated the title of the issue to better reflect what the bug is (the one described in my previous message).

It should not be too hard to solve but it's not too easy either (as we want to preserve the source location while parsing the html - ie it is not a simple as a "find & replace").

**Comment by vicb** [comment]
Actually I think we can convert CRLF to CR then CR to LF and preserving source position should not be a problem. I'll try to PR soon.

**Comment by filipesilva** [comment]
@vicb I've created bundles from your branch and replaces the ones in my code. It seems to fix the issue. Thanks!

The `ng-content` text node ("HQ alerts: no alerts, everything normal.") is aligned with the header above, and the space between template instances is also gone.

![image](https://cloud.githubusercontent.com/assets/4172079/11608477/69427482-9b62-11e5-8308-8ce1cc298641.png)

**Comment by vicb** [comment]
Great, thank you so much for having tested !

**Comment by filipesilva** [comment]
Thank you for fixing it :p
