### ISSUE TITLE
App using ngmodule does not get localeid set after upgrade to 18

### ISSUE THREAD

**Issue by michaelkrog** [angular/angular#56182]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

My app is still using ngModules. After upgrading from 17.3 to 18.0.1, I no longer have the correct LOCALE_ID set when using `ng serve`. Instead LOCALE_ID contains en-US no matter which locale I am serving.

I am able to reproduce it only if I refer to a component in a library under a library.

I am linking to a small reproduction of the bug. The project contains:
* An app
* A library (projects/lib)
* A sub-library (projects/lib/sublib)

The sublibrary contains a standalone component. When that component is referenced in the app, the LocaleId is not set.

It seems to only happen when serving. When building it is still fine.

### Please provide a link to a minimal reproduction of the bug

https://github.com/michaelkrog/wrong-locale

### Please provide the exception or error you saw

```true
No error or exception.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.2
Node: 18.20.2
Package Manager: npm 10.5.0
OS: darwin arm64

Angular: 18.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.2
@angular-devkit/build-angular   18.0.2
@angular-devkit/core            18.0.2
@angular-devkit/schematics      18.0.2
@angular/cli                    18.0.2
@schematics/angular             18.0.2
ng-packagr                      18.0.0
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.6
```

**Comment by JeanMeche** [comment]
Hi, can you provide the repro on angular/angular-cli#27722, which reports the same issue ? 
I'll this one as a duplicate as it is most likely a CLI issue.

**Comment by michaelkrog** [comment]
Thanx @JeanMeche.

I had tried to look for duplicates, but didn't find that one. 
Thank you for handling it.

I'll add my repo there.
