### ISSUE TITLE
Not able to redirect to Angular V17 Page

### ISSUE THREAD

**Issue by mayurpatil5953** [angular/angular#56180]
### Describe the problem that you experienced

Page is missing while hitting to - https://v17.angular.io/guide/releases

### Enter the URL of the topic with the problem

https://v17.angular.io/guide/releases

**Comment by Totati** [comment]
Sometimes I have the same issue.
![image](https://github.com/angular/angular/assets/17689719/2b22e2e9-d3bd-4a26-af23-d32b892c6007)
Then I'm hitting F5, or closing and reopening the tab, then it loads
![image](https://github.com/angular/angular/assets/17689719/891ddca9-be75-46b9-a765-baed4e4cf832)

**Comment by JeanMeche** [comment]
The issue has been fixed.
