### ISSUE TITLE
computed() re evaluation issue(?)

### ISSUE THREAD

**Issue by bellostom** [angular/angular#56185]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Hi all

Below is a simplified example of an issue we run into, regarding how computed is functioning.
Quoting the documentation from 
https://angular.dev/guide/signals#computed-signals

_The doubleCount signal depends on the count signal. Whenever count updates, Angular knows that doubleCount needs to update as well._

My assumption is that in order for a computed to re evaluate, one needs to explicitly update the writable signal, the computed is reading.

However, is seems that the computed re evaluates even if any other signal updates that is included in the original one. 

https://stackblitz.com/edit/angular-vt1rc7?file=src%2Fservice.ts,src%2Fmain.ts,src%2Feven.model.ts

In the example, although the **events** signal is never explicitly updated nor its reference changed, the **computed re evaluates** in every invocation from setInterval. 

Is such behavior expected, since from the documentation this is not clear at all and may lead to performance issues, if the computed is doing expensive operations.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-vt1rc7?file=src%2Fservice.ts,src%2Fmain.ts,src%2Feven.model.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 17.0.1
```

**Comment by alxhub** [comment]
The computed in question in the reproduction is effectively:
```typescript
computed(() => this.events().map(ev => ev.name);
```

`this.events()` reads a signal of an `Array<EventModel>`. `EventModel.name` is a getter which reads an internal signal `event().name`.

The interval mutates the internal `event` signals of both `EventModel`s, triggering the computed to rerun.

This is working as intended from a reactivity perspective - the computed depends on 3 signals, 2 of which change on every interval.

**Comment by bellostom** [comment]
Hi @alxhub 

This was a simplified example of a much more complex codebase.
In the actual use case, **processEvents** is much more complex and again it is not accessing any of the properties that are being updated.

I get the point that it works as expected based on the reactivity model, however, the documentation should be updated to reflect more complex scenarios, that could potentially lead to expensive re computations
