### ISSUE TITLE
If our product used angular13,when vulnerabilities or importante bugs were found, will you fix them for patch on version 13.x?

### ISSUE THREAD

**Issue by reggiechen31** [angular/angular#56198]
### Description

Now Angular 13.x is end of surpport, we need sometime to upgrade 17. Before we have done the upgration, how to deal with bugs or security problems? 
Hope your suggestion, thank you.

### Proposed solution

when vulnerabilities or importante bugs were found, patched for old versions such as 13.x

### Alternatives considered

Should Angular team provides commercial support?

**Comment by JoostK** [comment]
Please see https://angular.dev/reference/releases for the support policy. Only Angular 16+ at the time of writing is eligible for security fixes.

**Comment by json-derulo** [comment]
If you are looking to buy support for Angular versions which are not officially supported anymore, you can check herodevs: https://www.herodevs.com/support/nes-angular

However they are not affiliated with the official Angular team or Google, it's a third party solution.
