### ISSUE TITLE
Add an optional selector argument to the http methods

### ISSUE THREAD

**Issue by blesh** [angular/angular#5619]
In RxJS, it's common to provide optional resultSelector arguments for operators that will commonly have a `map` right after them. This is done to avoid incurring an additional subscription for the `map` operator, since it's really likely to be the next thing to happen.

I'm proposing changing [this line](https://github.com/angular/angular/blob/d388c0ae62cced3550f775ccaba11d58958ac49c/modules/angular2/src/http/http.ts#L101) and others like it to:

```
request<R>(url: string | Request, options?: RequestOptionsArgs, resultSelector?: (res: Response) => R): Observable<R> {
```

With appropriate handling. Which means:

You'll want to do the mapping *before* you pump the value into the observable. I think this means you'll have to pass the mapping to the backend and handle it in there.

Also, you'll want to send any errors that occur in the mapping function down the Observable's error path.

**Comment by robwormald** [comment]
@blesh i like this idea, i'll implement it as part of #4472. :+1:

**Comment by robwormald** [comment]
saw this - https://github.com/angular/angular/issues/5876#issuecomment-168127333 

@blesh does it make sense here (like the selector in mergeMap) to pass both the req and the res into the selector? eg:
```typescript
http.get(someReq, (req, res) => { return res.json() }) 
```

**Comment by benjamingr** [comment]
I don't understand why this can't be optimized away from the Rx side.

**Comment by blesh** [comment]
> I don't understand why this can't be optimized away from the Rx side.

It's a non-trivial optimization. Also, resultSelector arguments are common in RxJS, so this design would be second-nature to those familiar with the library. Any RxJS-side optimization that addressed this would likely need to know something about the source observable in order to collapse that functionality, so one way or another some sort of change would need to be made on this end.

**Comment by robwormald** [comment]
This issue was moved to angular/http#56
