### ISSUE TITLE
An Angular.io page seems to be down

### ISSUE THREAD

**Issue by QualityWebDev** [angular/angular#56206]
### Describe the problem that you experienced

- I tried to go to this page in angular.io: [https://v17.angular.io/guide/routing-overview](https://v17.angular.io/guide/routing-overview)
- I received this error: 
![Screenshot 2024-05-31 141907](https://github.com/angular/angular/assets/168010775/d18b28d6-5119-4452-8e19-4d5e94328f27)

### Enter the URL of the topic with the problem

https://v17.angular.io/guide/routing-overview

### Describe the actions that led you to experience the problem

I was trying to look at the routing documentation.

### Describe what you want to experience that would fix the problem

I want the page to work.

### If the problem is browser-specific, please specify the device, OS, browser, and version

I'm using the brave browser on a windows 11 pro os.

**Comment by jelbourn** [comment]
@QualityWebDev does this resolve if you clear your browser cache?

**Comment by QualityWebDev** [comment]
No. I'm afraid not.

**Comment by jelbourn** [comment]
https://github.com/angular/angular/pull/56167 should fix this

**Comment by QualityWebDev** [comment]
Thanks.

**Comment by JeanMeche** [comment]
It should be fixed now.

**Comment by QualityWebDev** [comment]
Thank you.

Sent with [Proton Mail](https://proton.me/) secure email.
