### ISSUE TITLE
Standalone from a global config

### ISSUE THREAD

**Issue by VASHvic** [angular/angular#56203]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

Having to declare `standalone:true` in each component makes sense if a project is migrating from an old version to a more modern aproach but it doesn't from a new developer or a new project point of view.

### Proposed solution

Declaring  `standalone:true` in the angular.json once and the compiler taking charge of the rest by making all components standalone.

### Alternatives considered

No

**Comment by JeanMeche** [comment]
Hi, please have a look at #49667, this topic has already been adressed.
