### ISSUE TITLE
Tutorial assets unavailable

### ISSUE THREAD

**Issue by HawkinsR** [angular/angular#56208]
### Describe the problem that you experienced

When attempting to build the tutorial project, any resource that is supposed to be available at "https://angular.dev/assets/tutorials/common/" is not found. This is problematic as the tutorial describes what resources should be found.
This was particularly noticeable on "Use *ngFor in templates", as it should include several linked resources that are not available. For example:
- https://angular.dev/assets/tutorials/common/example-house.jpg
- https://angular.dev/assets/tutorials/common/bernard-hermant-CLKGGwIBTaY-unsplash.jpg

### Enter the URL of the topic with the problem

https://angular.dev/assets/tutorials/common/

### Describe what you were looking for in the documentation

Images to complete the tutorial projects.

### Describe the actions that led you to experience the problem

Attempting to follow and complete the tutorial projects.

### Describe what you want to experience that would fix the problem

The images that are referenced should be hosted where they are listed in the tutorials.

### Add a screenshot if that helps illustrate the problem

There's not really a screen shot of something NOT being where it's supposed to be. Instead, here's me not finding the resources O.O

**Comment by HawkinsR** [comment]
Just realized this is a duplicate of issue [#52749](https://github.com/angular/angular/issues/52794) which is much better documented.

Apologies for the for the duplication. The link on Angular.dev leads straight to new issue creation, might be worth linking to the issues page, and adding a reminder to search for similar issues before creating a new one?

**Comment by JeanMeche** [comment]
Closing this as we're tracking it with #52749
