### ISSUE TITLE
Access to options object in ControlValueAccessor's writeValue method

### ISSUE THREAD

**Issue by ashehata277** [angular/angular#56214]
### Description

When using a custom form control that implements the ControlValueAccessor interface, there is currently no way to access the options object passed to `patchValue` or `setValue` inside the custom form control.

This is a limitation when trying to control the emission of `valueChanges` events from within the custom form control. For example, when patching the form control value with `{emitEvent: false}`, the `valueChanges` event is still emitted because the `writeValue` method in the custom form control does not receive the options object and cannot prevent the event from being emitted.

writeValue(value: number): void {
  // There is no way to access the options object here
}

### Proposed solution

The `writeValue` method should receive the options object passed to `patchValue` or `setValue`, or there should be another way to access this object inside the custom form control.

### Alternatives considered

1. Create a custom form control that implements the ControlValueAccessor interface.
2. In the `writeValue` method, try to access the options object passed to `patchValue` or `setValue`.
3. Notice that the `writeValue` method only receives the new value and not the options object.

**Comment by jnizet** [comment]
Hi @ashehata277 

The CVA doesn't need to access the options. The contract of `writeValue()` is to change the value of the control, from the outside. And that's all. The responsibility to fire a valueChange event when `setValue()` or `patchValue()` is being called is the responsibility of the FormControl, and it does that without needing any help from the CVA component.

See https://stackblitz.com/edit/stackblitz-starters-zwpbss?file=src%2Fmain.ts for a demo (Open the browser console to see the events being emitted).
