### ISSUE TITLE
Issue with code preview on Angular tutorial page (1-components-in-angular and 9-output)

### ISSUE THREAD

**Issue by dalotv** [angular/angular#56219]
### Describe the problem that you experienced

The code preview feature in the Angular documentation is not working properly, preventing me from following along with the coding examples.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/9-output

### Describe what you were looking for in the documentation

I was trying to follow the coding examples and instructions for component communication using @Output, but the code previews are not rendering anything.

### Describe the actions that led you to experience the problem

I navigated to the provided URL and tried to view the code previews as I followed the tutorial steps, but the code snippets are not rendering properly.

### Describe what you want to experience that would fix the problem

I want the code preview functionality to work correctly so that I can view and interact with the coding examples as intended in the tutorial.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/22773114/099b6fd5-e1d2-4647-b593-bb7a91faa1b8)
![image](https://github.com/angular/angular/assets/22773114/bcf9ba5e-0fe8-449a-a558-c1be17bf08ad)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
I'm experiencing the issue with the latest versions of both Google Chrome and Microsoft Edge browsers on my Windows 11 desktop computer. The code preview functionality is not working properly in the Angular documentation site with either of these two up-to-date browsers.
```

**Comment by JeanMeche** [comment]
Hi, 
We're aware of this issue, the fix is pending review in #56217.
