### ISSUE TITLE
Signal in Service not working

### ISSUE THREAD

**Issue by geezz07** [angular/angular#56215]
### Which @angular/* package(s) are the source of the bug?

core

### Description

The effect() and computed() does not fire when signal is in a service. 

```ts 
@Injectable({
    providedIn: 'root'
})
export class ThemeService {
    private _mode = signal<'dark' | undefined>('dark');
    readonly mode = this._mode.asReadonly();

    toggleTheme() {
        if (this.mode() == 'dark') {
            this._mode.set(undefined);
            localStorage.removeItem('theme');
        } else {
            this._mode.set('dark');
            localStorage.setItem('theme', 'dark');
        }
    }
}
```

```ts
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, HeaderComponent],
  providers: [ThemeService],
  templateUrl: 'app.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AppComponent {
  private doc: Document = inject(DOCUMENT);
  private _themeService: ThemeService = inject(ThemeService);

  constructor() {
    const localStorage = this.doc.defaultView?.localStorage;
    const bodyEl = this.doc.querySelector('body');

    effect(() => {
      if (this._themeService.mode() == 'dark') {
        bodyEl?.classList.add('dark');
      } else {
        bodyEl?.classList.remove('dark');
      }
    });

  }
}

```
Note: I have a button on the screen that triggers toggleTheme() from my service.

Note: If I refactor my code to use the following. The effect and computed gets fired no problem
```ts
const _mode = signal<'dark' | undefined>('dark');
export const mode = _mode.asReadonly();
export const toggleTheme = () => {
    if (mode() == 'dark') {
        _mode.set(undefined);
        localStorage.removeItem('theme');
    } else {
        _mode.set('dark');
        localStorage.setItem('theme', 'dark');
    }
}
```

### Please provide the exception or error you saw

```true
No exceptions. Just behavior is not what is expected.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.2
Node: 20.10.0
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 18.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.2
@angular-devkit/build-angular   18.0.2
@angular-devkit/core            18.0.2
@angular-devkit/schematics      18.0.2
@angular/cli                    18.0.2
@schematics/angular             18.0.2
rxjs                            7.5.7
typescript                      5.4.5
zone.js                         0.14.6
```

**Comment by jnizet** [comment]
Hi @geezz07 

You didn't provide a minimal repro as a stackblitz. I created one: https://stackblitz.com/edit/stackblitz-starters-4cqmrt?file=src%2Fmain.ts, but as you can see, everything works perfectly.

So you should ask your question in the Angular Discord or on Stackoverflow and provide a complete minimal reproduction this time, because it's most probably a bug in your code. A big smell is that your service is `providedIn: 'root'`, but you're providing it a second time on your component, and probably a third time in the component which toggles the theme. So you probably have several instances of the service: one is used by the app component reading the mode, and another is used by whatever toggles the theme.

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
