### ISSUE TITLE
Incomplete docs for NgComponentOutlet directive

### ISSUE THREAD

**Issue by leo-battin** [angular/angular#56229]
### Describe the problem that you experienced

Examples are incomplete in the usage notes tab.

### Enter the URL of the topic with the problem

https://angular.dev/api/common/NgComponentOutlet?tab=usage-notes

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/134740741/f4551665-02b9-4ead-bed8-b6e92dcbffd2)

**Comment by JeanMeche** [comment]
Let merge the issues about the missing example block with `@example` togther => #56321
