### ISSUE TITLE
Missing RouterCreateURL

### ISSUE THREAD

**Issue by AyolaM** [angular/angular#56223]
### Describe the problem that you experienced

last paragraph on this link: https://angular.dev/api/router/RouterLink?tab=description send you to this broken link: https://angular.dev/api/router/RoutercreateUrlTree

### Enter the URL of the topic with the problem

https://angular.dev/api/router/RoutercreateUrlTree

### Describe what you were looking for in the documentation

Learning

**Comment by JeanMeche** [comment]
This is due to an upstream issue microsoft/TypeScript#58259 that will be fixed with TS 5.5 which is expected later this month.
