### ISSUE TITLE
contentChildren signal value changes before child components are initialised

### ISSUE THREAD

**Issue by jamesbrobb** [angular/angular#56224]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I'm in the process of converting an existing project from decorators to signals. The following contrived example demonstrates the issue i've come across.

[Example 1](https://stackblitz.com/edit/stackblitz-starters-ve86vi?file=src%2Fmain.ts) using Input and ContentChildren decorators

```ts
import { Component } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import 'zone.js';
import { BookListComponent } from './components/book-list/book-list.component';
import { BookComponent } from './components/book/book.component';


@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    BookListComponent,
    BookComponent
  ],
  template: `
    <book-list>
      <book title='title 1'></book>
      <book title='title 2'></book>
      <book title='title 3'></book>
    </book-list>
  `,
})
export class App {
  name = 'Angular';
}

bootstrapApplication(App);
```

[BookListComponent](https://stackblitz.com/edit/stackblitz-starters-ve86vi?file=src%2Fcomponents%2Fbook-list%2Fbook-list.component.ts)

```ts
import { Component, ContentChildren, QueryList } from '@angular/core';
import { BookComponent } from '../book/book.component';

@Component({
  selector: 'book-list',
  standalone: true,
  templateUrl: './book-list.component.html',
  styleUrl: './book-list.component.scss',
})
export class BookListComponent {
  @ContentChildren(BookComponent)
  books?: QueryList<BookComponent>;

  ngAfterContentInit() {
    console.log('ngAfterContentInit::BookListComponent');
    this.books?.forEach((book) => {
      console.log('Book innerTitle:', book.innerTitle);
    });
    console.log('=====================================');
  }
}
```

[BookComponent](https://stackblitz.com/edit/stackblitz-starters-ve86vi?file=src%2Fcomponents%2Fbook%2Fbook.component.ts)

```ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'book',
  standalone: true,
  templateUrl: './book.component.html',
  styleUrl: './book.component.scss',
})
export class BookComponent {
  @Input({ required: true }) title?: string;

  innerTitle?: string;

  ngOnInit() {
    console.log('ngOnInit::BookComponent');
    this.innerTitle = `inner title - ${this.title}`;
  }
}
```

As expected, all content children are initialised first before `ngAfterContentInit` is run in the `BookListComponent` so `BookComponent.innerTitle` has been set and is available for inspection within the `BookListComponent`. 

```
ngOnInit::BookComponent
ngOnInit::BookComponent
ngOnInit::BookComponent
ngAfterContentInit::BookListComponent
Book innerTitle: inner title - title 1
Book innerTitle: inner title - title 2
Book innerTitle: inner title - title 3
=====================================
```
----------------------

[This example](https://stackblitz.com/edit/stackblitz-starters-aaoahu?file=src%2Fmain.ts) implements the same functionality but the decorators have been replaced with `input` and `contentChildren` signals.

[BooklistComponent](https://stackblitz.com/edit/stackblitz-starters-aaoahu?file=src%2Fcomponents%2Fbook-list%2Fbook-list.component.ts)

```ts
import { Component, contentChildren, effect } from '@angular/core';
import { BookComponent } from '../book/book.component';

@Component({
  selector: 'book-list',
  standalone: true,
  templateUrl: './book-list.component.html',
  styleUrl: './book-list.component.scss',
})
export class BookListComponent {
  books = contentChildren(BookComponent);

  constructor() {
    effect(() => {
      console.log('effect:contentChildren::BookListComponent');
      this.books()?.forEach((book) => {
        console.log('Book innerTitle:', book.innerTitle);
      });
      console.log('=====================================');
    });
  }

  ngAfterContentInit() {
    console.log('ngAfterContentInit::BookListComponent');
    this.books()?.forEach((book) => {
      console.log('Book innerTitle:', book.innerTitle);
    });
    console.log('=====================================');
  }
}

```

[BookComponent](https://stackblitz.com/edit/stackblitz-starters-aaoahu?file=src%2Fcomponents%2Fbook%2Fbook.component.ts)

```ts
import { Component, effect, input } from '@angular/core';

@Component({
  selector: 'book',
  standalone: true,
  templateUrl: './book.component.html',
  styleUrl: './book.component.scss',
})
export class BookComponent {
  title = input.required<string>();

  innerTitle?: string;

  constructor() {
    effect(() => {
      console.log('effect:input::BookComponent');
      this.innerTitle = `inner title - ${this.title()}`;
    });
  }

  ngOnInit() {
    console.log('ngOnInit::BookComponent');
  }
}
```

As you can see in the following output, the child component signal `input` value does not change before the `contentChildren` signal value changes. So at the point access to the content children components executes (within the `effect` in the `BookListComponent` constructor), `BookComponent` has not yet been initialised.

```
ngOnInit::BookComponent
ngOnInit::BookComponent
ngOnInit::BookComponent
=====================================
ngAfterContentInit::BookListComponent
Book innerTitle: undefined
Book innerTitle: undefined
Book innerTitle: undefined
=====================================
effect:contentChildren::BookListComponent
Book innerTitle: undefined
Book innerTitle: undefined
Book innerTitle: undefined
 =====================================
effect:input::BookComponent
effect:input::BookComponent
effect:input::BookComponent
``` 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-aaoahu?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.2
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.2
@angular-devkit/build-angular   18.0.2
@angular-devkit/core            18.0.2
@angular-devkit/schematics      18.0.2
@angular/cli                    18.0.2
@schematics/angular             18.0.2
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.6
```

**Comment by jnizet** [comment]
I'd say that what you're seeing is normal and expected, since you're using an effect to initialize the inner title, and effects run during change detection, and change detection runs from top to bottom.

An equivalent way of doing what you're doing in the decorator-based example would be to use a [computed signal for the inner title](https://stackblitz.com/edit/stackblitz-starters-sgom5j?file=src%2Fcomponents%2Fbook%2Fbook.component.ts,src%2Fcomponents%2Fbook-list%2Fbook-list.component.ts), or even [keep using ngOnInit](see https://stackblitz.com/edit/stackblitz-starters-17wge1?file=src%2Fcomponents%2Fbook%2Fbook.component.ts,src%2Fcomponents%2Fbook-list%2Fbook-list.component.ts).

**Comment by jamesbrobb** [comment]
@jnizet thanks for the examples, that's very interesting.

This is probably something i've missed, but everything i've read about signals seems to be pushing/promoting them as a replacement for the decorators and lifecycle hooks, so i didn't realise the input signal initial values are actually available to access in `ngOnInit`. Is this mentioned anywhere in the docs?

Do you think it's an issue that the solutions you've suggested are actually a requirement in order to get more complex uses cases of `contentChildren` to work correctly, but unlike `ngAfterContentInit`, are not explicit when switching from `@ContentChildren` to use `contentChildren`? Would it be worth me submitting a PR to add these examples to the docs?

**Comment by pkozlowski-opensource** [comment]
Before updating any documentation (which wouldn't be very obvious as there is subtle timing here) I would very much like to second @jnizet suggestion of using `computed` - in many cases this is the best way forward.

**Comment by jamesbrobb** [comment]
[This](https://stackblitz.com/edit/stackblitz-starters-6ulu4z?file=src%2Fmain.ts) is a better representation of the code that i'm refactoring.

```html
<div collector>
  <div aDirective='yes'></div>
  <div bDirective='no'></div>
  <div cDirective='maybe'></div>
</div>
```

```ts
import { ContentChildren, Directive, QueryList } from '@angular/core';
import { ThirdPartyObject } from './third-party-object.factory';
import { THIRD_PARTY_TOKEN } from './third-party.token';

@Directive({
  selector: '[collector]',
  standalone: true,
})
export class CollectorDirective {
  @ContentChildren(THIRD_PARTY_TOKEN)
  children?: QueryList<ThirdPartyObject>;

  ngAfterContentInit() {
    this.children?.forEach((child: ThirdPartyObject) => {
      console.log(
        `${child.getSomeValue()} is initialised: ${child.isInitialised()}`
      );
    });
  }
}
```
```ts
import { Directive, ElementRef, Inject, Input, OnInit } from "@angular/core";
import { thirdPartyTokenProvider, THIRD_PARTY_TOKEN } from "./third-party.token";
import { ThirdPartyObject } from "./third-party-object.factory";


@Directive({
  selector: '[aDirective]',
  standalone: true,
  providers: [
    thirdPartyTokenProvider
  ]
})
export class ADirective implements OnInit {

  @Input({alias: 'aDirective', required: true})
  someValue!: string

  constructor(
    private _element: ElementRef<HTMLElement>,
    @Inject(THIRD_PARTY_TOKEN) private _thirdPartyObject: ThirdPartyObject
  ) {}

  ngOnInit() {
    this._thirdPartyObject.initialise(this._element.nativeElement, this.someValue)
  }
}
```

Although `ADirective`, `BDirective` and `CDirective` are identical in the example code, they're not within my actual code. Each directive creates a different third party UI object (that are initialised in many different ways) and the directives role is simply as a container to supply input values and the required html element to initialise the UI object. The third party UI object is also non Angular.

And [here](https://stackblitz.com/edit/stackblitz-starters-oa83ye?file=src%2Fmain.ts) is the refactored example using `input` signals and `contentChildren`.

Being fairly new to signals, at first glance i'm not sure how this problem would be solved using `computed`?

**Comment by jamesbrobb** [comment]
@pkozlowski-opensource 

> there is subtle timing here

Isn't this the reason something _should_ be explicitly documented?

**Comment by jamesbrobb** [comment]
I've attempted to solve the problem using signals instead of having the initialisation of each child directive in `ngOnInit`.

[Code](https://stackblitz.com/edit/stackblitz-starters-91prmh?file=src%2Fmain.ts)

I've removed the imports in the following example code for brevity.

```html
<div collector doSomethingWithCollection>
    <div aDirective='yes'></div>
    <div bDirective='no'></div>
    <div cDirective='maybe'></div>
</div>
```

There's a new `BaseDirective` which exposes a signal:

```ts
@Directive({
  selector: '[baseDirective]',
  standalone: true
})
export class BaseDirective {
  thing = signal<ThirdPartyObject | null>(null);
}
```

This is then declared as a host directive of each child directive (aDirective, bDirective and cDirective)

```ts
@Directive({
  selector: '[aDirective]',
  standalone: true,
  providers: [
    thirdPartyTokenProvider
  ],
  hostDirectives: [
    BaseDirective
  ]
})
export class ADirective {

  someValue = input.required<string>({alias: 'aDirective'});

  readonly #element = inject(ElementRef<HTMLElement>);
  readonly #thirdPartyObject = inject(THIRD_PARTY_TOKEN);
  readonly #base = inject(BaseDirective);

  constructor() {
    effect(() => {
      this.#thirdPartyObject.initialise(this.#element.nativeElement, this.someValue())
      untracked(() => this.#base.thing.set(this.#thirdPartyObject))
    });
  }
}
```

The `CollectorDirective` then collects the `BaseDirective`'s and exposes a signal

```ts
@Directive({
  selector: '[collector]',
  standalone: true,
})
export class CollectorDirective {

  readonly children = contentChildren<BaseDirective>(BaseDirective);

  readonly things: Signal<ThirdPartyObject[]> = computed(() => this.children()
      .map((child: BaseDirective) => child.thing())
      .filter((arg): arg is ThirdPartyObject => !!arg)
  );
}
```

That can be used by interested parties to access all `ThirdPartyObject`'s

```ts
@Directive({
  selector: '[doSomethingWithCollection]',
  standalone: true
})
export class DoSomethingWithCollectionDirective {

  readonly #collection = inject(CollectorDirective);

  constructor() {
    effect(() => {
      const coll = this.#collection.things();

      console.log(coll);
      
      coll.forEach((thing) => {
        console.log(`${thing.getSomeValue()} is initialised: ${thing.isInitialised()}`);
      });
    });
  }
}
``` 
---
It works, but the `BaseDirective` signal is set within an effect. I couldn't think of a way to accomplish this solution without this, any ideas?

```ts
effect(() => {
    this.#thirdPartyObject.initialise(this.#element.nativeElement, this.someValue())
    untracked(() => this.#base.thing.set(this.#thirdPartyObject))
});
```

**Comment by pkozlowski-opensource** [comment]
> It works, but the BaseDirective signal is set within an effect. I couldn't think of a way to accomplish this solution without this, any ideas?

@jamesbrobb the usage of `effects` seems legit here - essentially you are doing an imperative API call (`thirdPartyObject.initialise`) in response to signal changes. And _then_ you do some more logic based on the initialised values. So it sounds like you are crossing the reactive boundaries back and forth.

I don't know enough about your use-case but an alternative approach would consist of staying in the "reactivity land" as long as possible, something along those lines: https://stackblitz.com/edit/stackblitz-starters-w3uvw9 - again I don't know enough about your use-case to know if this is helpful / applicable.

I'm going to close this issue for now as it turns into a more general discussion about modeling certain situations with reactivity. We are going to document timing of effects a bit more while stabilizing its API.
