### ISSUE TITLE
404 link -> https://angular.dev/guide/cheatsheet

### ISSUE THREAD

**Issue by TomPrint** [angular/angular#56220]
### Describe the problem that you experienced

Hello Angular Team, coming from google results to https://v17.angular.io/guide/cheatsheet and visiting reference link https://angular.dev/guide/cheatsheet gives 404.

### Enter the URL of the topic with the problem

https://angular.dev/guide/cheatsheet

### Describe what you were looking for in the documentation

cheat sheet

**Comment by JeanMeche** [comment]
Hi,
The cheatsheet wasn't ported to angular.dev. The broken link will be fixed by #56082 (and redirect to the homepage as there is no corresponding target).
