### ISSUE TITLE
Link does not work.

### ISSUE THREAD

**Issue by AlekseiBud** [angular/angular#56238]
### Describe the problem that you experienced

I follow the link 'https://angular.dev/api/localize/init/$localize' and I see the note 'Page Not Found 🙃'.

**Comment by moniuch** [comment]
Same when following the banner link "Your watching archived 17..." for RouterLinkActive. It tries to land me at `https://angular.devhttps//angular.dev/api/router/RouterLinkActive` (https concatenated)

**Comment by JeanMeche** [comment]
Dupe of #54388
