### ISSUE TITLE
HTTP client - Test requests heads to wrong angular.dev link

### ISSUE THREAD

**Issue by imaliouris** [angular/angular#56233]
### Describe the problem that you experienced

In https://v17.angular.io/guide/http-test-requests page the "head to angula.dev" anchor button should have an href="https://angular.dev/guide/http/testing" instead of href="https://angular.dev/guide/http/security"

### Enter the URL of the topic with the problem

https://v17.angular.io/guide/http-test-requests

### Describe the actions that led you to experience the problem

Press "head to angula.dev" anchor button

### Describe what you want to experience that would fix the problem

It should navigate to https://angular.dev/guide/http/testing

**Comment by JeanMeche** [comment]
This will be fixed by #56222.
