### ISSUE TITLE
Missing docs about effect and change detection phase 

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular#56249]
### Describe the problem that you experienced

It's hard to tell from the docs **when exactly an effect runs in terms of change detection phase** and whether it's safe/make-sense to update template variable inside of it.

**Comment by json-derulo** [comment]
I disagree, for me the [effects docs](https://angular.dev/guide/signals#effects) contain sufficient and clear information.

> An effect is an operation that runs whenever one or more signal values change. [...]
> When an effect runs, it tracks any signal value reads.
> Whenever any of these signal values change, the effect runs again.

> **When not to use effects**
> Avoid using effects for propagation of state changes.
> This can result in ExpressionChangedAfterItHasBeenChecked errors, infinite circular updates, or unnecessary change detection cycles.
>
> Because of these risks, Angular by default prevents you from setting signals in effects.
> It can be enabled if absolutely necessary by setting the allowSignalWrites flag when you create an effect.
>
> Instead, use computed signals to model state that depends on other state.

**Comment by ArielGueta** [comment]
Updated the question

**Comment by JeanMeche** [comment]
Effect have been updated in v19. 

https://next.angular.dev/api/core/effect?tab=description

Long story short, `effect` run before CD in component. For effect after CD please refer to [`afterRenderEffect())`](https://next.angular.dev/api/core/afterRenderEffect)
