### ISSUE TITLE
RouterLinkActive doesn't work on an ancestor element as claimed by the docs

### ISSUE THREAD

**Issue by moniuch** [angular/angular#56244]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

It's either docs mistake or a bug - you decide.
The [docs](https://angular.dev/api/router/RouterLinkActive?tab=description) say:

> You can apply the RouterLinkActive directive to an ancestor of linked elements. 

and gives an example with a `div` element. This is exactly what I am after. It doesn't work though.
I hope this is how we want it to work, because when you have a bunch of static menu links (static = not generated by a `@for` loop), this leads to unnecessarily verbose template.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-8ck9jz

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 18.0.0
```

**Comment by JeanMeche** [comment]
This works like expected, the class is applied to the host element of the `routerLinkActive` directive. 
This feature is meant to toggle a class when a link is nested deeper in the DOM.
