### ISSUE TITLE
Link to Location not shown properly in API Reference page

### ISSUE THREAD

**Issue by Rajendran-Balaji** [angular/angular#56250]
### Describe the problem that you experienced

![image](https://github.com/angular/angular/assets/88931771/c700fb34-23cc-43bd-a579-b73c2b26b6ac)

It is showing {@link Location } instead of [Location](https://angular.dev/api/common/Location)

### Enter the URL of the topic with the problem

https://angular.dev/api/common/PathLocationStrategy

**Comment by Rajendran-Balaji** [comment]
Also please note that clicking on `LocationStrategy` goes to 404 page

**Comment by JeanMeche** [comment]
Hi, thank you for this, we'll fix this with #55840.
