### ISSUE TITLE
Why doesn't my computer call the api to update, but someone else's computer calls the api to update?

### ISSUE THREAD

**Issue by tuanmeo01** [angular/angular#56268]
### Which @angular/* package(s) are the source of the bug?

common, compiler, core, elements, Don't known / other

### Is this a regression?

Yes

### Description

I deployed the code to the server, but on my computer, after adding a data field, the api did not call back to update the interface, but on other computers, it still called the api to update the interface.

![41be4494-6a8c-44bf-bf2c-1b1385549404](https://github.com/angular/angular/assets/90205276/9e58491a-fe65-4f99-8dd3-f9d52b1fe511)
![image](https://github.com/angular/angular/assets/90205276/06c20f54-a7f4-4335-9ea2-b8de5babf6fc)
![image](https://github.com/angular/angular/assets/90205276/52cff4a0-6bef-4d07-9509-d92b67da4d71)
![image](https://github.com/angular/angular/assets/90205276/36c5ded6-57d4-4f83-995b-5467879b4e5b)

### Please provide the exception or error you saw

```true
no error in console log
```

**Comment by tuanmeo01** [comment]
anyone  help me :(

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
