### ISSUE TITLE
docs: link with extra whitespace in NgComponentOutlet

### ISSUE THREAD

**Issue by naaajii** [angular/angular#56263]
### Describe the problem that you experienced

404 page on clicking "Component" link in NgComponentOutlet API page.

### Enter the URL of the topic with the problem

https://angular.dev/api/common/NgComponentOutlet

**Comment by JeanMeche** [comment]
Hi, thank you for reporting this issue. 
This is an upstream issue microsoft/TypeScript#58584, it will be fix when we update to TS 5.5 later this month.
