### ISSUE TITLE
baseUrl link broken

### ISSUE THREAD

**Issue by rmill019** [angular/angular#56262]
### Describe the problem that you experienced

Working through the Angular tutorial (https://angular.dev/tutorials/first-app/04-interfaces), the link for baseUrl is broken, leads to "Page Not Found"

Base Url: https://angular.dev/assets/tutorials/common

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app/04-interfaces

### Describe the actions that led you to experience the problem

I was following the tutorial but when running the app locally the image would not load. 

### Describe what you want to experience that would fix the problem

This link should load an image: https://angular.dev/assets/tutorials/common/example-house.jpg

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/12501555/94f40a3a-854a-4f40-a8a9-a1a9c407df22)

**Comment by JeanMeche** [comment]
Hi !
Let's continue tracking this issue in https://github.com/angular/angular/issues/52794
