### ISSUE TITLE
Documentation is not reproducing descriptions associated with JSDoc @returns tag in angular.dev site

### ISSUE THREAD

**Issue by stephanietuerk** [angular/angular#56277]
### Describe the problem that you experienced

Comments in the codebase that are provided as part of a JSDoc `@returns` tag are not being rendered in the new Angular.dev documentation. This makes it challenging for users to understand how to work with anything that is returned. 

_Example_
In the Renderer2 class, there is important context in the comments in the codebase for what is returned from the `listen` method:
![image](https://github.com/angular/angular/assets/13357861/910df0d3-0637-40e5-b812-f86a7c5b5b1f)

However, this information ("An unlisten function...", this is a screenshot from your `main` branch) doesn't make it into the documentation on Angular.dev: https://angular.dev/api/core/Renderer2
![image](https://github.com/angular/angular/assets/13357861/1b7d3bed-a455-44b4-966a-6f08d47fb9bf)

I confirmed that this is occurring for classes outside of Renderer2 -- also a problem for HttpHeaders.

### Enter the URL of the topic with the problem

https://angular.dev/api/core/Renderer2
https://angular.dev/api/common/http/HttpHeaders

### Describe what you were looking for in the documentation

Information about what is returned from Angular methods that return something to the user.

### Describe the actions that led you to experience the problem

I needed to confirm what is returned by `Renderer2.listen` and could not without consulting the source code.

### Describe what you want to experience that would fix the problem

The documentation renders comments from JSDoc `@returns` tags.

### Add a screenshot if that helps illustrate the problem

See above.

**Comment by JeanMeche** [comment]
Note, extraction works fine, this is something to address on the dev-infra repo.
