### ISSUE TITLE
Assets for Tutorial to angular no longer exist

### ISSUE THREAD

**Issue by reeceeric82** [angular/angular#56271]
### Describe the problem that you experienced

Going through the angular tutorial, the link to the assets no longer work

### Enter the URL of the topic with the problem

https://angular.dev/assets/tutorials/common

### Describe what you were looking for in the documentation

I was going through the tutorial to learn angular basics and noticed this link leads no where

### Describe the actions that led you to experience the problem

Working through the tutorial

### Describe what you want to experience that would fix the problem

Update the path for the images link or adjust the tutorial documentation

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/65454356/d356c6f8-493d-4784-84c4-72b0c3384270)
![image](https://github.com/angular/angular/assets/65454356/06bbb0a9-065a-4a82-8f0e-cfe001a77fae)

**Comment by JeanMeche** [comment]
Hi !
Let's continue tracking this issue in https://github.com/angular/angular/issues/52794
