### ISSUE TITLE
Page not opening properly

### ISSUE THREAD

**Issue by CliffyMk** [angular/angular#56273]
### Describe the problem that you experienced

Head over to https://angular.dev/guide/security

the page is loading like below

![image](https://github.com/angular/angular/assets/6140896/886a9ee8-6ad1-4423-b327-4d667b316f90)

### Enter the URL of the topic with the problem

https://angular.dev/guide/security

### Describe what you were looking for in the documentation

The page to load relevant information.

### Describe the actions that led you to experience the problem

Head over to the given URL

**Comment by pkozlowski-opensource** [comment]
Were you looking for https://angular.dev/best-practices/security# ? 

How did you get the https://angular.dev/guide/security link?

**Comment by JeanMeche** [comment]
@pkozlowski-opensource It's probably the AIO redirect : https://v17.angular.io/guide/security
