### ISSUE TITLE
Add $inject function inside template

### ISSUE THREAD

**Issue by splincode** [angular/angular#56283]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler-cli

### Description

```ts
export const MY_PAGES = new InjectionToken('MyPages', {
 factory: () => ['Home', 'About']
});
```

```ts
@Component({
    standalone: true,
    selector: 'my',
    template: `
      <div *ngFor="let page of pages">
         {{ page }}
      </div>
    `
})
export class MyComponent {
  pages = inject(MY_ROUTES);
}
```

### Proposed solution

```ts
export const MY_PAGES = new InjectionToken('MyPages', {
 factory: () => ['Home', 'About']
});
```

```ts
@Component({
    standalone: true,
    selector: 'my',
    template: `
      <div *ngFor="let page of $inject('MyPages')">
           {{ page }}
      </div>
    `
})
export class MyComponent {}
```

### Alternatives considered

Maybe this would be useful

**Comment by JeanMeche** [comment]
By using a function in the template, it would be executed at each CD cycle. This isn't particularly recommended. 
You'd be better of, having that inject in your component.

**Comment by splincode** [comment]
@JeanMeche sure, you agree

**Comment by alxhub** [comment]
I see you closed this yourself, but I wanted to add my agreement with @JeanMeche. I do think we would consider this an anti-pattern for several reasons:

* executing an unnecessary operation each CD cycle
* coupling the template with knowledge of the DI system
* the need to also expose DI tokens to the template (`string` tokens from the example are not actually supported)
