### ISSUE TITLE
component-tree.ts:352 Angular DevTools: Could not serialize injector.

### ISSUE THREAD

**Issue by test-mhrana** [angular/angular#56298]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

![image](https://github.com/angular/angular/assets/142661189/0b037227-830d-4849-b072-56f2f34307cd)
in my angular 17 application i  use nexted route. For that i need to use router-outlet on different component and imoport router-oulet com app layout and settings component. but when i use that . angular dev tools show an error 
![image](https://github.com/angular/angular/assets/142661189/11764815-94cb-481e-b91d-1a0266c19a58)
Injector error . 

application ss
![image](https://github.com/angular/angular/assets/142661189/9abc52f8-2762-412b-8d76-378cb37f43c4)

what is possible problem in nexted route. how can solve this.??

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

Add router module as root on standalone project. or resolve chainedInjector.

**Comment by JoostK** [comment]
Please update to the latest Angular 17 release. You haven't provided information on which exact version you're using but there has been a fix at some point for this error.
