### ISSUE TITLE
ComponentFixture.whenStable doesn't detect event emitted from async output in zoneless CD

### ISSUE THREAD

**Issue by jnizet** [angular/angular#56290]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

In zoneless mode (i.e. with `provideExperimentalZonelessChangeDetection()`), a test using autoDetectChanges does not detect the changes caused by the emission of an event by a child output using an async EventEmitter (i.e. `new EventEmitter(true)`).

To make things clearer, use the minimal reproduction (see below), and execute the following commands in the terminal:

- `cd app`
- `npm install`
- `ng serve`

Note at this point that clicking the two buttons works as expected: the associated "hello" message becomes "world".

Now run `ng test`.

The test for the "Async" section fails. The difference between the first and the second section is that the first one reacts to a sync output from the child component, whereas the second one reacts to an async output.

Using async outputs might seem weird (BTW, this option deoesn't exist with the new `output()` function), but this issue comes from a real use-case where it is actually used (ng-bootstrap's pagination component).

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-c2ydkj?file=app%2Fsrc%2Fapp%2Fapp.component.spec.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.2
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.2
@angular-devkit/build-angular   18.0.2
@angular-devkit/core            18.0.2
@angular-devkit/schematics      18.0.2
@angular/cli                    18.0.2
@schematics/angular             18.0.2
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.6
```

**Comment by JeanMeche** [comment]
In Zone apps this was a side-effect of having Zone handling your stability (an AsyncEmitter wrapped the emit with a `setTimeout()`. 

The new output doesn't allow async emition. I'm not sure this should be support.

**Comment by jnizet** [comment]
@JeanMeche That was my intuition too, but I wonder why the change is being detected in the application, which is zoneless, then. It's only the test that fails.

**Comment by JeanMeche** [comment]
@jnizet You're updating a signal, which schedules the CD :)

**Comment by alxhub** [comment]
> Given that EventEmitter is an Angular thing, and that it is the thing that does the setTimeout, couldn't it trigger a CD / mark the listening component for check?

It does. But the event isn't emitted until after a timeout/delay, so the receiving component doesn't get marked until after that delay. The problem is that the application is currently stable until this happens, so when the test does `await whenStable` it doesn't have anything to wait for. This is a pretty typical kind of pattern we've seen with the experimental zoneless APIs.

The fix would be to make the async `EventEmitter` block stability until the event is fired, which we can look into. I could see that being a bit breaking, though, so we'll have to test it out.

**Comment by jnizet** [comment]
Thank you @JeanMeche and @alxhub for your great explanations.

I see that adding a `await firstValueFrom(timer(1))` after the click in the test does make the test pass. 
It's not easy to figure out though because nothing except the source code indicates whether an output is synchronous or not, and I needed your explanations to realize what that implies regarding the stability.
