### ISSUE TITLE
Link broken in the Angular Tutorial Example

### ISSUE THREAD

**Issue by lingibelli** [angular/angular#56297]
### Describe the problem that you experienced

In the page shown in the image below, the URL is broken. the correct URL is "https://angular.io/assets/images/tutorials/faa/example-house.jpg" as per the old tutorial page. URL highlighted [Yellow.] . Please update to the correct URL. Thank you.

![image](https://github.com/angular/angular/assets/11011076/2b432d0c-e377-4eab-8a97-4089b8ba31cc)

### Enter the URL of the topic with the problem

https://angular.dev/assets/tutorials/common/example-house.jpg

**Comment by Tweniee** [comment]
Can you give more info?

**Comment by lingibelli** [comment]
Hi Tweniee,
                    I was following the instruction in the tutorial page [https://angular.dev/tutorials/first-app/06-property-binding]. As per the code/instructions, the resultant page of the code should show the image. But the image is not shown as the link used in the code is broken. I have highlighted the broken link in the image I attached in the description. Could you please elaborate what more information you need? Thank you.

**Comment by lingibelli** [comment]
@Tweniee , As per the tutorial, the preview page should display images in every blue square. But for me no image is shown. In the screenshot attached below, I have highlighted the broken path to the images and the preview page for your reference. 

![image](https://github.com/angular/angular/assets/11011076/4d5e0f78-a1d6-4592-9c0d-96cfb9e2e039)

**Comment by lingibelli** [comment]
The expected output should be like the below image. But due to the broken link, the images are not displayed.

![image](https://github.com/angular/angular/assets/11011076/1094fce9-62d6-46e7-b314-18163c34b40d)

**Comment by JeanMeche** [comment]
Let's continue tracking this issue in https://github.com/angular/angular/issues/52794
