### ISSUE TITLE
Add `TouchedEvent` to form events observable that broadcasts all "touched" events

### ISSUE THREAD

**Issue by chronospatian** [angular/angular#56304]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

I want to be notified each time a user touches a field so I have more control over the timing of value or status change emissions without changing the control update strategy to 'onblur'.

```ts
const control = new FormControl()

control.valuesChanges.pipe(
  audit(() => control.events.pipe(filter(event => event instanceof TouchedEvent))),
).subscribe((value) => {
  // Do something with the value each time the user touched the field.
})
```

This would also be useful for delegating control value accessors to a reactive form control

```ts
// CVA host directive
@Directive({ standalone: true })
class MyValueAccessor implements ControlValueAccessor {
  // Use this in component template
  control = new FormControl()

  writeValue(value) {
    this.control.setValue(value)
  }

  registerOnChange(fn) {
    this.onChange = fn
  }

  registerOnTouched(fn) {
    this.onTouched = fn
  }

  next(event: ControlEvent) {
    if (event instanceof ValueChangeEvent) {
      this.onChange?.(event.source.value)
    }
    if (event instanceof TouchedEvent) {
      this.onTouched?.()
    }
  }

  constructor() {
    this.control.events.subscribe(this)
  }
}
```

### Proposed solution

Add a new event type `TouchedEvent` that is similar to `TouchedChangeEvent` except it emits every time the user "touched" a field, irrespective of the touched state.

### Alternatives considered

For now I am decorating `markAsTouched` to create a stream of touch events.

```ts
const touchedEvents = new Subject()
const control = new FormControl()
const markAsTouched = control.markAsTouched
control.markAsTouched = function (opts) {
  markAsTouched.call(this, opts)
  touchedEvents.next({ source: this })
}
```

**Comment by chronospatian** [comment]
> This is already provided by the PristineEvent, just negate its value.

PristineEvent only emits when the pristine state changes from true to false or vice-versa. What I want is an event notification that fires **every time**  `markAsTouched` is called on an AbstractFormControl.

**Comment by JeanMeche** [comment]
Sorry I should have said, check for TouchedChangeEvent. I mixed up our events.

**Comment by chronospatian** [comment]
@JeanMeche TouchedChangeEvent only fires when the touched state changes, not every time time the form field is touched. I want to observe touched events even if the field is already touched.
