### ISSUE TITLE
Allow omitting "()" in event bindings with no parameters passed

### ISSUE THREAD

**Issue by haqer1** [angular/angular#56305]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Fairly frequently event bindings pass no parameters:
```html
<button id="createAccountButton" (click)="newAccount()">New Account</button>
```
In this case, "()" after method name could be considered redundant.

### Proposed solution

Consider allowing shorter syntax ("marginally optimizing" disk usage):
```html
<button id="createAccountButton" (click)="newAccount">New Account</button>
```
(compiling to the same code) (because obviously the only thing doable with the method (in absence of assignment operator as well) is calling it, as already kind of reflected by "()" around the event name (click)).

### Alternatives considered

In the continuum of more automated to more manual the approaches could be listed as:
1) defaulted calling with no extended diagnostics
2) defaulted calling with extended diagnostics warning
3) defaulted calling with extended diagnostics info message (this being dependent on https://github.com/angular/angular/issues/56307)
4) no defaulted calling with extended diagnostics error (as in https://github.com/angular/angular/issues/56293 mentioned in https://github.com/angular/angular/issues/56305#issuecomment-2152702676)

And 1 doesn't exclude the other. Simpler more common cases could be treated according to approach 1., difficult cases could be treated according to approach 4., those in between according to approach 2. or 3. I.e., approach 1. in general, could go along with approach 4. sometimes, & even possibly in combination with quirk support (as mentioned in https://github.com/angular/angular/issues/56305#issuecomment-2152888433), but that quirk is a separate issue, it appears.

**Comment by pkozlowski-opensource** [comment]
This suggests _opposite_ thing to #56293

**Comment by haqer1** [comment]
> This suggests _opposite_ thing to #56293

Yes, i had just thought of tooling diagnostic error detecting this as alternative, but turns out this had already been suggested 18 hours ago.
These are not 100% exclusive.

The quirk suggested there[1], could be treated as suggested there, whereas defaulted calling could come from here.

P.S.
[1] 
```html
<button (click)="void incrementAndLaterDecrement()">Increment</button>

<button (click)="incrementAndLaterDecrement();">Increment</button>
```

**Comment by haqer1** [comment]
One could even consider combining defaulted calling from here with a diagnostic **warning** (rather than error suggested in https://github.com/angular/angular/issues/56293)

**Comment by JoostK** [comment]
Extended diagnostics are configurable w.r.t. being an error, warning or skipped altogether.

**Comment by haqer1** [comment]
OK, i updated my comment to mention **warning** only for now.

P.S. Although **info** could be another feature. :)

**Comment by haqer1** [comment]
I updated **Alternatives considered** section in the OP, to make the issue more legible.

**Comment by alxhub** [comment]
I think an extended diagnostic is probably the right answer here.

Trying to detect whether an expression in an event listener should be auto-called by the framework is a blurry proposition. For example:

```typescript
(foo)="bar" // probably meant to call it
(foo)="bar.baz" // probably meant to be a call, but also is a method tearoff if strictly interpreted
(foo)="a && b" // also a side-effect free expression, but did you mean (a && b)() or a() && b()
(foo)="getCallback()" // you probably wanted getCallback()() but that's super hard to infer
```

Instead, I think it's better to report an error when we detect that an expression evaluates to a callable type but is not called.

**Comment by haqer1** [comment]
> I updated **Alternatives considered** section in the OP, to make the issue more legible.
Twice.

**Comment by haqer1** [comment]
That's i've been saying they are not 100% exclusive. Considering continuum of 4 approaches i listed in **Alternatives considered** in the OP a few minutes ago:
> (foo)="bar" // probably meant to call it

approach 1.
> ```ts (foo)="bar.baz" // probably meant to be a call, but also is a method tearoff if strictly interpreted ```

iff you are saying we can't reliably conclude that this means bar.baz() (but is there a real use-case of that?), (then it won't be approach 1.,) but (rather can be) approach 4.
> (foo)="a && b" // also a side-effect free expression, but did you mean (a && b)() or a() && b()

approach 4
> (foo)="getCallback()" // you probably wanted getCallback()() but that's super hard to infer

That's a separate issue out of scope of this issue (because they are "()"), but mentioned as a quirk previously (https://github.com/angular/angular/issues/56305#issuecomment-2152888433): it should it's treatment should be discussed separately (should probably even be split off of https://github.com/angular/angular/issues/56293, because it's not the main thing discussed there, but a fringe case).

**Comment by haqer1** [comment]
Although not exactly the same, i'd like to point out that lambda expressions & just function names can work equivalently in standard JS. E.g., 
a. https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event#examples
```js
function doSomething() {
  console.info("DOM loaded");
}

if (document.readyState === "loading") {
  // Loading hasn't finished yet
  document.addEventListener("DOMContentLoaded", doSomething);
} else {
  // `DOMContentLoaded` has already fired
  doSomething();
}
```
b. https://jsfiddle.net/haqer/8Lpganh5/76/
```js
document.getElementById("add").addEventListener("click", handleNew);
```

**Comment by haqer1** [comment]
Different area, but perhaps there is a similarity in this seeming example of approach 2 from gpg domain:
```
gpg -o test.pdf test.pdf.gpg
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
...
File 'test.pdf' exists. Overwrite? (y/N) y
...
```

P.S. The similarity is in automated deducted action (in this case with a notification).

**Comment by JeanMeche** [comment]
Like it been pointed, we're choosing to go in the opposite direction cf #56293 (WIP implementation #56295). 

Also the example about `addEventListener` is different. It expect a function, not something you could or not invoke.
