### ISSUE TITLE
Some public APIs are not properly displayed in Angular.dev

### ISSUE THREAD

**Issue by amayer42** [angular/angular#56310]
### Describe the problem that you experienced

I was looking at the documentation for [ActivatedRouteSnapshot](https://angular.dev/api/router/ActivatedRouteSnapshot) and noticed that the `params` class field was not shown.

I can confirm that it is part of the public API from looking at the [ActivatedRouteSnapshot source code](https://github.com/angular/angular/blob/main/packages/router/src/router_state.ts#L321-L423) and from looking at the shipped `d.ts` file for the Angular router. The only suspicious thing is that the `constructor` is marked with `/** Internal */` which I suspect causes the `public` members declared within the `constructor` to be excluded from the generated documentation.

I posted this as [a question on the Angular Community Discord](https://discord.com/channels/748677963142135818/1247955511245148160) originally and @JeanMeche confirmed that this seemed like an issue:

### Enter the URL of the topic with the problem

https://angular.dev/api/router/ActivatedRouteSnapshot

### Describe what you want to experience that would fix the problem

I think that the `public` class fields declared within the `constructor` should be exposed in the generated documentation.

**Comment by JeanMeche** [comment]
Internal doesn't seem to be at cause here, our API extractor doesnt extract constructor declared properties.

**Comment by JeanMeche** [comment]
Actually we weren't extracting the public properties defined in the constructor, #56315 should fix this.

**Comment by amayer42** [comment]
Thanks a bunch, I took a look through your PR and it makes sense to me. Appreciate it!
