### ISSUE TITLE
docs: diagrams have wrong colors on angular.dev

### ISSUE THREAD

**Issue by darya-startsava** [angular/angular#56314]
### Describe the problem that you experienced

Compare the diagram on angular.dev page with GH Markdown version:
[angular.dev](https://angular.dev/best-practices/skipping-subtrees#an-event-is-handled-by-a-component-with-default-change-detection):
![image](https://github.com/angular/angular/assets/86919538/8d124c9d-03a3-4e08-a4b0-129d966cfb73)

[GH Markdown](https://github.com/angular/angular/blob/main/adev/src/content/best-practices/runtime-performance/skipping-subtrees.md#an-event-is-handled-by-a-component-with-default-change-detection):
![image](https://github.com/angular/angular/assets/86919538/38d35b13-d013-45c1-8314-d97c36cc56f7)

All diagrams are supposed to be displayed in color as specified in the Markdown file.

### Enter the URL of the topic with the problem

https://angular.dev/best-practices/skipping-subtrees#using-onpush

**Comment by JeanMeche** [comment]
If someone is interested to pick this issue, It might be interesting to try different shapes instead of different colors. 
Mermaid.js supports different shapes and it would make the chart compatible with different theme colors.

**Comment by vincent-agi** [comment]
Hi i am interresting to do this'issue as my first. Can you assign this task to me please ?

**Comment by JeanMeche** [comment]
@vincent-agi Feel free to directly drop a PR, thank you !

**Comment by vincent-agi** [comment]
@JeanMeche hi i am happy to exchange with you i know you from angular devs france 

Okay thanks a lot, i will do that next week.

**Comment by vincent-agi** [comment]
response to 

@JeanMeche Hi which shapes would i choose for which element ?

> If someone is interested to pick this issue, It might be interesting to try different shapes instead of different colors. Mermaid.js supports different shapes and it would make the chart compatible with different theme colors.

@JeanMeche Hi which shapes would i choose for which element ? I think it's good idea mix shapes for disable people color-blind.

**Comment by JeanMeche** [comment]
Feel free to get inspired 👍

**Comment by vincent-agi** [comment]
i have choosen to keep rectangle and add circle shape.

I've learned how to format commit and make PR.

Thank you for you help
