### ISSUE TITLE
[alpha.48] npm install failed

### ISSUE THREAD

**Issue by todoubaba** [angular/angular#5633]
npm install angular2@2.0.0-alpha.48

npm ERR! shasum check failed
npm ERR! Expected: 87ebfd9f24eb769289730f96ef6f81a02601227d
npm ERR! Actual:   17fc7c7e1d9a21ad271f170d23a7e4e5cdbedba0
npm ERR! From:     https://registry.npmjs.org/angular2/-/angular2-2.0.0-alpha.48.tgz

Env:
windows 10
nodejs v4.2.1
npm v.2.14.7

**Comment by ericmartinezr** [comment]
@todoubaba I don't know the reason, but try this

```
npm cache clean

// Option 1
npm install angular2@2.0.0-alpha.48
// Option 2
npm install angular2@latest
// Option 3
npm install angular/angular#builds-js
```

**Comment by todoubaba** [comment]
@ericmartinezr Thanks, it works.

```
npm cache clean
npm install angular2
```
