### ISSUE TITLE
Not possible to update Angular verrsion globally and locally

### ISSUE THREAD

**Issue by AAlex-11** [angular/angular#56330]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

I installed latest node version 22.2.0 and can not update Angular version to 18. My Typescript version is 5.1.6
My environment: I have global Angular in folder D:\Angular, and folder D:\Angular\node_modules.bin\ set in my system Path variables.
Attempt to Update Angular globally give me trash result "Error: This command is not available when running the Angular CLI outside a workspace." Why global updating need a workspace? I want to update exactly globally, without workspace! This is first unexpected answer from Angular framework.

![Angular-06082024_113248_1](https://github.com/angular/angular/assets/138773344/cc867467-f90d-493c-aff9-1d97b82b2ac8)

I have folder with my project E:\NativeScript\MyVault\MyVault - I have no any root project - this is separate folder. However, if I try to understand my version on project folder - I receive even more unexpected result - I have Angular 18 after attempt to install Angular locally with options --save, but parts of Angular is version 16 - why? I don't specify in any place Angular 16, why Angular 16 stick to my Angular 18 version? How to fully replace Angular 16 to Angular 18 in my project folder?
Attempt to install local version Angular 18 get more strange and unexpected result - "ERESOLVE unable to resolve dependency tree" and I receive something trash message about "root project" - what is the conception of root project at all? I have no any root project, I have one folder with project and one folder with Global installation.

![Angular-06082024_113745_1](https://github.com/angular/angular/assets/138773344/3c000839-8e5f-47f3-a2dd-a68ee30510cf)

![Angular-06082024_114237_1](https://github.com/angular/angular/assets/138773344/248e7fb0-1d50-457c-9294-a8ff5afd79eb)

### Please provide the exception or error you saw

```true
I see 3 strange trouble with Angular - I can not update global version of Angular without workspace, I want fully delete any Angular 16 in my project folder and can not forbid ancient Angular version in project folder. I can not understand what is Root project in my computer.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
What is Angular environment you require?
My global environment is 15 and and I can not change it to 18.
My local environment is mix of 18 and 16 and I can not change it to 18.
```

### Anything else?

npm list -g
D:\nodejs
+-- @angular/cli@18.0.3
+-- @ngtools/webpack@18.0.3
+-- corepack@0.28.1
`-- npm@10.8.1

**Comment by JeanMeche** [comment]
There is no concept of "global" version for angular itself. 

You can have a version installed globally for the Angular CLI (so you can run `ng new` anywhere you want). 

But each Angular project needs to have it's own versions defined in the `package.json` file. So you need to update each of your project independently (and independently of you global CLI install).
