### ISSUE TITLE
Infinite money glitch

### ISSUE THREAD

**Issue by joeskeen** [angular/angular#56342]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

I discovered while testing one of my applications that when displaying currency, if the value passed to `formatCurrency` is `undefined`, Angular will display it as infinite money.

```
import { Component, LOCALE_ID, inject } from '@angular/core';
import { formatCurrency, getCurrencySymbol } from '@angular/common';
import { bootstrapApplication } from '@angular/platform-browser';
import 'zone.js';

@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <h1>It will cost you {{money}}</h1>
  `,
})
export class App {
  private readonly locale = inject(LOCALE_ID);
  money = formatCurrency(
    undefined as any,
    this.locale,
    getCurrencySymbol('USD', 'narrow'),
    'USD'
  );
}

bootstrapApplication(App);
```

Output:

# It will cost you $∞

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-x9bsga?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
No errors or warnings are displayed in the console, and the function does not throw an error.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.3
Node: 20.12.0
Package Manager: pnpm 8.15.5
OS: linux x64

Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1703.3 (cli-only)
@angular-devkit/core         17.3.3 (cli-only)
@angular-devkit/schematics   17.3.3 (cli-only)
@schematics/angular          17.3.3 (cli-only)
```

### Anything else?

I'm not certain what the proper fix would be for this, but it is definitely unexpected. This appeared on a page prior to the customer checking out. The funny thing is that the test I was running should have yielded a subtotal of `$0.02`, but due to a logic error on my part the value passed was undefined so instead it showed `$∞`. 

Would it be better to display `NaN` or `undefined` instead of `∞`? 

Would it be better to throw an error?

I honestly don't know, but I feel like silently failing by converting `undefined` to `∞` seems off.

Edit: Looks like `Intl.NumberFormat` would display it as `$NaN`:

```ts
new Intl.NumberFormat(this.locale, {
    style: 'currency',
    currency: 'USD',
  }).format(undefined as any)
```

**Comment by JeanMeche** [comment]
You likely have a typing issue. `formatCurrency` only accepts numbers. Using `undefined` is outside the scope of the function.
