### ISSUE TITLE
Page not found in documentation on Vite

### ISSUE THREAD

**Issue by cpi-Ishrat** [angular/angular#56341]
### Describe the problem that you experienced

 link broken / page not found at -> https://angular.dev/overview -> work at any scale -> EsBuild and Vite -> https://angular.dev/tools/cli/esbuild

### Enter the URL of the topic with the problem

https://angular.dev/tools/cli/esbuild

### Describe what you were looking for in the documentation

details on vite

### Describe the actions that led you to experience the problem

Navigation from https://angular.dev/overview -> work at any scale -> EsBuild and Vite -> https://angular.dev/tools/cli/esbuild lead to page not found

**Comment by JeanMeche** [comment]
If anyone wants to take this, we might want to replace the link with https://angular.dev/tools/cli/build-system-migration

**Comment by risqiromadhoni** [comment]
> If anyone wants to take this, we might want to replace the link with https://angular.dev/tools/cli/build-system-migration

Hi @JeanMeche, it would be an honor for me to contribute to the development of a library that I love, can I work on this issue?
