### ISSUE TITLE
Angular.dev is missing a lot of information

### ISSUE THREAD

**Issue by anisabboud** [angular/angular#56349]
### Describe the problem that you experienced

Compare:
- https://angular.dev/api/common/CurrencyPipe
- https://v17.angular.io/api/common/CurrencyPipe

The angular.io page provides a detailed explanation for each parameter as well as a code sample.
The angular.dev page is missing parameter explanations and also missing the code sample. 

### Enter the URL of the topic with the problem

https://angular.dev/api/common/CurrencyPipe

### Describe what you want to experience that would fix the problem

Angular.dev should have been ready for production (QA) before it was made the default.

### Add a screenshot if that helps illustrate the problem

https://github.com/angular/angular/assets/5672108/7193f41c-fb2c-4e03-aef3-336b28d00b87

![image](https://github.com/angular/angular/assets/5672108/0e08796b-df3d-43ba-a35d-e37be83e06a0)

### Provide any additional information here in as much as detail as you can

Related: https://github.com/angular/angular/issues/56321

**Comment by anisabboud** [comment]
This is partially fixed - thanks!
But not completely fixed. Please reopen.

## Pipe syntax is missing:
![Image](https://github.com/user-attachments/assets/bd450956-bbea-4ec9-a17b-33c48e705fde)

## Code examples under Usage Notes are still missing
![Image](https://github.com/user-attachments/assets/2d9c7e99-623d-41e7-be21-6164b6e5926c)

**Comment by JeanMeche** [comment]
We'll track this with #58185, thank you for raising the issue.
