### ISSUE TITLE
validator with access to another control

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#5635]
I was just testing the validators this morning and I created a simple validator that tests for the equality of values from two controls:
```js
import {provide, Directive, Attribute, Input} from 'angular2/core';
import {NG_VALIDATORS, Control, Validators, Validator} from 'angular2/common';

import {isPresent} from '../../common/lang';

@Directive({
	selector: '[equal-to][ng-control],[equal-to][ng-form-control],[equal-to][ng-model]',
	providers: [
		provide(NG_VALIDATORS, {
			useExisting: EqualToValidator,
			multi: true
		})
	]
})

export class EqualToValidator implements Validator {
	@Input('equalTo') target: Control;
	constructor() {
		// this.target.valueChanges.subscribe((...args) => {
		// 	console.log(args);
		// });
	}
 	validate(control: Control): {[key: string]: any} {
		if (isPresent(Validators.required(control))) return null;
		console.log(control);
 		return this.target.value !== control.value
			? {'equalTo': true}
			: null;
	}
}
```
And you would use it as:
```html
<input
		#newPassword
		type="password"
		class="form-control change-form-newpassword"
		id="new-password"
		name="newPassword"
		ng-control="newPassword"
		[(ng-model)]="credentials.newPassword"
		[disabled]="isChanging"
		placeholder="New Password"
		autocomplete="off"
		required>
	<input
		#retypeNewPassword
		type="password"
		class="form-control change-form-retypenewpassword"
		id="retype-new-password"
		name="retypeNewPassword"
		ng-control="retypeNewPassword"
		[disabled]="isChanging"
		placeholder="Retype New Password"
		autocomplete="off"
		[equal-to]="newPassword"
		required>
```
It seems to work just fine, but there is one issue. If the user types in the `newPassword`, the validation on `retypeNewPassword` will not pick up on that and that makes perfect sense since there is nothing that links it to it.
But that is something I would like to have and that is why I tried to use:
```js
this.target.valueChanges.subscribe((...args) => {
	console.log(args);
});
```
Where `this.target` should point to the other control. The problem is that when the constructor of the `[equal-to]` gets initialized, `this.target` is `undefined`. So I got stuck there. I am not sure if that is a bug or if that is something that is just not possible.

I was also think of using `Query` to lookup the control, but the issue with that is that I can only look at children, or so I think.

Is there any way this could be achieved?

**Comment by taylorjb** [comment]
+1

**Comment by taylorjb** [comment]
I am also looking for a solution to validate a password confirmation against a password within a sign-up form using best practices.

Upon further investigation, I found this:

```javascript
import {Directive, provide, Input} from 'angular2/core';
import {Validator, Control, NG_VALIDATORS} from 'angular2/common';

@Directive({
  selector: '[equalTo][ngControl],[equalTo][ngFormControl],[equalTo][ngModel]',
  providers: [provide(NG_VALIDATORS, {useExisting: EqualToValidator, multi: true})]
})
export class EqualToValidator implements Validator {
  validate(c: Control): {[key: string]: any} {
    console.log(c._parent.controls);
    return false;
  }
}
```

In my console, I see the control group output:
```
Object {email: Control, password: Control, password_confirmation: Control}
```

Which I could then use to evaluate:
```
c._parent.controls.password.value == c_parent.controls.password_confirmation.value
```

While this works, my TypeScript compiler is complaining:
```
error TS2341: Property '_parent' is private and only accessible within class 'AbstractControl'.
```

Any thoughts?

**Comment by taylorjb** [comment]
I am also looking for a solution to validate a password confirmation against a password within a sign-up form using best practices.

Upon further investigation, I found this:

```javascript
import {Directive, provide} from 'angular2/core';
import {Validator, Control, NG_VALIDATORS} from 'angular2/common';

@Directive({
  selector: '[equalTo][ngControl],[equalTo][ngFormControl],[equalTo][ngModel]',
  providers: [provide(NG_VALIDATORS, {useExisting: EqualToValidator, multi: true})]
})
export class EqualToValidator implements Validator {
  validate(c: Control): {[key: string]: any} {
    console.log(c._parent.controls);
    return false;
  }
}
```

In my console, I see the control group output:
```
Object {email: Control, password: Control, password_confirmation: Control}
```

Which I could then use to evaluate:
```
c._parent.controls.password.value == c_parent.controls.password_confirmation.value
```

While this works, my TypeScript compiler is complaining:
```
error TS2341: Property '_parent' is private and only accessible within class 'AbstractControl'.
```

Any thoughts?

**Comment by taylorjb** [comment]
Here's an additional example:

```javascript
import {Directive, provide, Input} from 'angular2/core';
import {Validator, Control, NG_VALIDATORS} from 'angular2/common';

@Directive({
  selector: '[equalTo][ngControl],[equalTo][ngFormControl],[equalTo][ngModel]',
  providers: [provide(NG_VALIDATORS, {useExisting: EqualToValidator, multi: true})]
})
export class EqualToValidator implements Validator {
  @Input('equalTo') compareTo: Control;
  constructor() {}

  validate(c: Control): {[key: string]: any} {
    if( c._parent.controls[this.compareTo.toString()].value == c.value ){
      console.log('Equal!');
    } else {
      console.log('Not equal')
    }

    return false;
  }
}
```

Would it be possible to make `.parent` a publicly accessible method?

**Comment by taylorjb** [comment]
Here's an additional example:

```javascript
import {Directive, provide, Input} from 'angular2/core';
import {Validator, Control, NG_VALIDATORS} from 'angular2/common';

@Directive({
  selector: '[equalTo][ngControl],[equalTo][ngFormControl],[equalTo][ngModel]',
  providers: [provide(NG_VALIDATORS, {useExisting: EqualToValidator, multi: true})]
})
export class EqualToValidator implements Validator {
  @Input('equalTo') compareTo: string;
  constructor() {}

  validate(c: Control): {[key: string]: any} {
    if( c._parent.controls[this.compareTo].value == c.value ){
      console.log('Equal!');
    } else {
      console.log('Not equal')
    }

    return false;
  }
}
```

Is it possible to make `.parent` publicly accessible?

**Comment by antonmoiseev** [comment]
Have you considered wrapping these two fields in a single `ControlGroup` and validate it for equality? Here is the plunk that illustrates the idea http://plnkr.co/edit/BjuL3Ezrx2kSTlmwjyfP.

There are two fields - password and password confirmation, they are wrapped into a `ControlGroup`. A custom validator that requires all controls in the group to be equal is attached to the `ControlGroup`. When you start typing in the password field the error message appears next to the confirmation field. When the values are equal the message is hidden.

Does it work for you? If no, could you explain why?

**Comment by taylorjb** [comment]
Your solution does work for me and perhaps NgModel isn't appropriate for a registration form.  Thanks!

In terms of extending the Validator class for other applications, would the Control not benefit from having access to its parent ControlGroup?  What is the reasoning for keeping it private?

**Comment by awerlang** [comment]
@antonmoiseev nice idea to attach validator to a control group, that is probably the best approach as of beta.7.

**Comment by kara** [comment]
As @antonmoiseev mentioned, the best way to conduct validations that require multiple sibling controls is on the parent group level.

**Comment by oliverjanik** [comment]
Here's a counterpoint:

If you do you validator on the parent group, the errors will be created on the parent group, on a large form that has cross depended validations like that could mean the errors are potentially generated on the root ControlGroup.

However I would like my errors very close to the input where the user can actually rectify the situation.

The propopsed workaround only works for very simple scenarios. I our case the forms could span 100s of fields and support for defining cross dependencies would be greatly appreciated.

**Comment by e-cloud** [comment]
@antonmoiseev your solution is good for reactive forms, but not for template-driven forms.

**Comment by finalxcode** [comment]
thanks,  https://angular.io/docs/ts/latest/api/forms/index/FormGroup-class.html

**Comment by ammar91** [comment]
@antonmoiseev Is there a good way to do similar in template-driven forms?

**Comment by Fogetti** [comment]
I am also struggling with making this work in template-driven forms. Any workaround for that?

Some background: I was implementing custom form controls which show input fields and possible error messages bundled together and instead of inserting 6+ template elements into the form, I can just include a single line of code (actually I am using Ionic 3 not pure angular but that doesn't matter IMO).

Now this all worked fine until I had to implement cross-control custom validators.

**Comment by taylorjb** [comment]
Here's what I'm currently doing in `@angular 4.2.6` for e-mail & e-mail confirmation validation for user registration. The same method applies to password & password confirmation.

./register/register.html
```html
<div class="input-group">
  <label for="email">E-mail Address</label>
  <input type="email" name="email" class="form-control" required email="true"
    [(ngModel)]="user.email" #email="ngModel" equalTo="{{email_confirm.value}}">
</div>
<app-form-error-message [control]="email" [value]="email.value"
[messages]="validationMessages"></app-form-error-message>

<div class="input-group">
  <label for="email_confirm">E-mail Address Confirmation</label>
  <input type="email" name="email_confirm" class="form-control" required email="true"
    [(ngModel)]="user.email_confirm" #email_confirm="ngModel" equalTo="{{email.value}}">
</div>
<app-form-error-message [control]="email_confirm" [value]="email_confirm.value"
[messages]="validationMessages"></app-form-error-message>
```

./equal-to-validator-directive.ts
```typescript
/* tslint:disable:directive-selector */

import { Directive, Input, OnChanges, SimpleChanges } from '@angular/core';
import { AbstractControl, NG_VALIDATORS, Validator, ValidatorFn, Validators } from '@angular/forms';

export function equalToValidator(val: string): ValidatorFn {
  return (control: AbstractControl): {[key: string]: any} => {
    /* this is where you want to put all your custom validation logic
       REMINDER: returning null means valid, so check for invalid */
    if (control.value !== val && val !== '') {
      return {'equalTo': control.value};
    }
    return null;
  };
}

@Directive({
  selector: '[equalTo]',
  providers: [{provide: NG_VALIDATORS, useExisting: EqualToValidatorDirective, multi: true}]
})
export class EqualToValidatorDirective implements Validator, OnChanges {
  @Input() equalTo: string;
  private valFn = Validators.nullValidator;

  ngOnChanges(changes: SimpleChanges): void {
    const change = changes['equalTo'];
    if (change) {
      this.valFn = equalToValidator(change.currentValue);
    } else {
      this.valFn = Validators.nullValidator;
    }
  }

  validate(control: AbstractControl): {[key: string]: any} {
    return this.valFn(control);
  }
}
```

Also notice within `./register/register.html` I have an additional component `app-form-error-message` which is bound to the form control itself so error messages can be accessed within it via `this.control.errors` and triggered with `OnChanges` watching `changes['value']` with custom messaged passed in via `validationMessages` as an object.

**Comment by axmad22** [comment]
I find it better to keep the rule on the controller it self and not on the whole form group, 

```JavaScript
passwordVerifyTest(): ValidatorFn {
    return (control: AbstractControl): ValidationErrors | null => {
      const verifyPassword = control.value;
      if (verifyPassword) {
        const newPassword = control.root.get('newPassword').value;

        if (verifyPassword !== newPassword) {
          return {PasswordVerify: true};
        }
      }

      return null;
    };
  }
````

and the form group 

```JavaScript
    this.form = fb.group({
      'newPassword': ['', Validators.required],
      'verifyPassword': ['', Validators.compose([Validators.required, passwordValidator.passwordVerifyTest()])]
    });

    this.newPassword = this.form.controls['newPassword'];
    this.verifyPassword = this.form.controls['verifyPassword'];
```

**Comment by vijaybabu4589** [comment]
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/35931662/64188732-8eecb200-ce90-11e9-990b-4c85bba86879.png">
