### ISSUE TITLE
Not able to view https://angular.dev/tools/cli/esbuild 

### ISSUE THREAD

**Issue by chandrakommi** [angular/angular#56350]
### Describe the problem that you experienced

i am not able to view the docs for esbuild cli options from the url `https://angular.dev/tools/cli/esbuild`

### Enter the URL of the topic with the problem

https://angular.dev/tools/cli/esbuild

### Describe the actions that led you to experience the problem

![image](https://github.com/angular/angular/assets/136074986/46175fd6-5185-4c5e-ac50-67d0117e16a3)

**Comment by JeanMeche** [comment]
Hi, this issue has already been reported by #56341.
