### ISSUE TITLE
`effect()` should have an option to run outside of an injection context

### ISSUE THREAD

**Issue by lifaon74** [angular/angular#56357]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Angular's signals (`signal`, and `computed`) are not bound to any injection context, however `effect` as well as `toSignal` and `toObservable` are.

Thus we have to use these functions inside an `runInInjectionContext`, which is not really possible (nor wanted), when we have to create parts of an application based on another framework (or vanilla-js), but using (at least partially) some signals.
Here, we may imagine a web-component accepting signals as input, thus, requiring an `effect` but outside of any injection context.

[Currently](https://github.com/angular/angular/blob/main/packages/core/src/render3/reactivity/effect.ts#L250) the injection context is used to: 
- get a scheduler (`APP_EFFECT_SCHEDULER`)
- get optionally a DestroyRef
- get optionally a ChangeDetectorRef
- get optionally an `ErrorHandler`
 
 Thus, I think it would be great to add more options to allow `effect`s outside of any context, but defaulting on the `injector`, only if we are inside an injection context. Hence, having  `effect`s working everywhere, just like signals.

And, if we consider that developers are not "warned enough" / safe, we may add a property like: `runOutsideOfInjectionContext: boolean`.

### Proposed solution

```ts
export interface CreateEffectOptions {
  injector?: Injector;
  manualCleanup?: boolean;
  allowSignalWrites?: boolean;
  scheduler?: EffectScheduler;
}

export function effect(
  effectFn: (onCleanup: EffectCleanupRegisterFn) => void,
  { allowSignalWrites = false, manualCleanup = false, injector, scheduler }: CreateEffectOptions,
): EffectRef {
  if (isInInjectionContext()) {
    const injector = injector ?? inject(Injector);
    const destroyRef = manualCleanup ? null : injector.get(DestroyRef);

    const handle = new EffectHandle(
      scheduler ?? injector.get(APP_EFFECT_SCHEDULER),
      effectFn,
      typeof Zone === 'undefined' ? null : Zone.current,
      destroyRef,
      injector,
      allowSignalWrites,
    );

    const cdr = injector.get(ChangeDetectorRef, null, {
      optional: true,
    }) as ViewRef<unknown> | null;
    if (!cdr || !(cdr._lView[FLAGS] & LViewFlags.FirstLViewPass)) {
      handle.watcher.notify();
    } else {
      (cdr._lView[EFFECTS_TO_SCHEDULE] ??= []).push(handle.watcher.notify);
    }

    return handle;
  } else {
    return new EffectHandle(
      scheduler ?? DEFAULT_EFFECT_SCHEDULER, // NOTE => we provide a default scheduler
      effectFn,
      null,
      null,
      null,
      allowSignalWrites,
    );
  }
}
```

### Alternatives considered

provide a `watch` function like:

```ts
export function watch(
  effectFn: (onCleanup: EffectCleanupRegisterFn) => void,
  { allowSignalWrites = false }: Pick<CreateEffectOptions, 'allowSignalWrites'> = {},
): EffectRef {
  let scheduled = false;
  return createWatch(
    (onCleanup: WatchCleanupRegisterFn) => effectFn(onCleanup),
    (watch: Watch): void => {
      if (!scheduled) {
        scheduled = true;
        queueMicrotask((): void => {
          scheduled = false;
          watch.run();
        });
      }
    },
    allowSignalWrites,
  );
}
```

**Comment by JeanMeche** [comment]
You can pass an injector to the effect, which allows it to run outside an injection context.

**Comment by lifaon74** [comment]
> You can pass an injector to the effect, which allows it to run outside an injection context.

Yes, and no:

- yes you can capture an injector from an angular component and pass it (with the signals) to the "outside context" code. But this is not practical, and this require a component as a stating point. However, this is not always correct. For example, we may imagine a "modal" web-component which is located at the top level, like the the app component, and sometimes even higher. Thus, it won't truly  be independent of the angular app. We'll need to "init" it with an injection context which is not really elegant.
- no because `APP_EFFECT_SCHEDULER` as well as `EffectScheduler` are not public, thus, we cannot provide our own scheduler. Currently, we're forced to use the angular scheduler inside an angular context which is not great when using framework agnostic external libraries.

**Comment by JeanMeche** [comment]
Effects are an integral part of the framework and their scheduling is tied with internals. You can see them as a framework specific helpers built on-top of the `watch` signal primitive. 

If you're looking for framework agnostic alternatives, you can build them on top of the exisiting primitives.

**Comment by pkozlowski-opensource** [comment]
As @JeanMeche mentioned, `effects` are very much tied to the internals of the framework so we can't expect it to fully function outside of the framework context.
