### ISSUE TITLE
feat: make ControlGroup.find instance method an observable

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#5637]
This is because of [5635](https://github.com/angular/angular/issues/5635), but it would be nice to have the [.find()](https://github.com/angular/angular/blob/3fa287aae2ce19ad74d044c3267e4d64242d638f/modules/angular2/src/common/forms/model.ts#L196) method on a `ControlGroup` as an observable. Because if the controls have not been initialized yet you cannot find them. So for example, having this custom validator:
```js
import {
	provide,
	Directive,
	Attribute,
	Input,
	Host
} from 'angular2/core';
import {
	NG_VALIDATORS,
	NgForm,
	ControlGroup,
	AbstractControl,
	Control,
	Validators,
	Validator
} from 'angular2/common';

import {isPresent} from '../../common/lang';

@Directive({
	selector: '[equal-to][ng-control],[equal-to][ng-form-control],[equal-to][ng-model]',
	providers: [
		provide(NG_VALIDATORS, {
			useExisting: EqualToValidator,
			multi: true
		})
	]
})

export class EqualToValidator implements Validator {
	target: AbstractControl;
	constructor(@Host() formDir: NgForm, @Attribute('equal-to') target: string) {
		let form: ControlGroup = formDir.form;

		this.target = form.find(target);
		
		console.log(form, target, this.target, form.find);
		
		// this.target.valueChanges.subscribe((...args) => {
		// 	console.log(args);
		// });
	}
 	validate(control: Control): {[key: string]: any} {
		if (isPresent(Validators.required(control))) return null;
		// console.log(control, this.targetControlPath, this.targetControl);
 		return this.target.value !== control.value
			? {'equalTo': true}
			: null;
	}
}
```
Even though the `formDir` is fetched and the `target` is also set to the right value when the constructor is invoked, the controls have not been set on the `formDir.form`. So if I try to call `formDir.form.find(target)` I will get null.

This may be by design or maybe it's a bug, but it makes it kind of impossible to set a watcher on the value changes of another control as I am trying to do. So having the `.find()` method async (I think as an Observable) would solve that issue. Something like the following:
```js
constructor(@Host() formDir: NgForm, @Attribute('equal-to') target: string) {
	let form: ControlGroup = formDir.form;

	this.target = form.find(target);
	this.target.subscribe((control: Control) => { ... /* finally found the control */ });	
}
```

Or if there are other ways of creating a subscription on the value changes of some control this feature would be of course not needed.

**Comment by vicb** [comment]
this is related to the old form module
