### ISSUE TITLE
Vulnerability in package: @angular/localize > fast-glob > micromatch > braces

### ISSUE THREAD

**Issue by surecloud-tstafford** [angular/angular#56376]
### Which @angular/* package(s) are the source of the bug?

localize

### Is this a regression?

No

### Description

Unfixed patch for the following vulnerability available: https://github.com/advisories/GHSA-grv7-fg5c-xmjg

### Please provide a link to a minimal reproduction of the bug

https://github.com/advisories/GHSA-grv7-fg5c-xmjg

### Please provide the exception or error you saw

```true
Need to take the latest patch from braces lib.
```

**Comment by JeanMeche** [comment]
fast-glob & micromatch don't have pinned dependencies so you can update this yourself. 

The easy way is to delete the lock file and the node modules.
