### ISSUE TITLE
alpha.48: tbody should not wrap tr in template

### ISSUE THREAD

**Issue by todoubaba** [angular/angular#5638]
```typescript
@Component({
  selector: 'my-cmp',
  template: `
  <table border>
    <thead>
      <th>col1</th>
      <th>col2</th>
    </thead>
    <tbody>
      <template ng-for #rx [ng-for-of]="values">
        <tr>
          <template ng-for #ry [ng-for-of]="rx">
            <td>{{ry}}</td>
          </template>
        </tr>
      </template>
    </tbody>
  </table>
  `
})
class MyCmp {
  values = [
    [11, 12],
    [21, 22]
  ];
}
```

![table](http://qpic.cn/SwWR93zOa)
![Elements](http://qpic.cn/ikyiNsRQE)

http://plnkr.co/edit/ZXV6pLI44IqFQbIEX4zj?p=preview

**Comment by udos86** [comment]
Yep, should not be a default behavior. It pollutes semantically correct table markup and therefore quickly breaks anticipated rendering, especially when working with external css libraries(e.g. Bootstrap). Thanks for fixing!

**Comment by vicb** [comment]
Two way we can fix this:
- never explicitly add a `<tbody>`,
- add a `<tbody>` only if the `<tr>` has a parent (ie is not a fragment).

The first solution would produce consistent result whether rows are in the master template or added as fragment.

@tbosch what do you think ?

**Comment by tbosch** [comment]
Let's do it this way:
Never add an implicit parent when the parent element is a `template` element.

**Comment by cur3n4** [comment]
I am also experimenting the issue with tr in thead being wrapped with a tbdoy.

**Comment by cur3n4** [comment]
It doesn't happen in alpha 51. So all good
