### ISSUE TITLE
Inect not working in normal function

### ISSUE THREAD

**Issue by shiv-2810** [angular/angular#56386]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

export const JobHandler: Handler = async () => {
  const module = await import(`@nova/components`);
  const viewContainer = inject(ViewContainerRef);
  viewContainer.createComponent(module['LoaderComponent']);
  console.log('JobHandler is working');
  return true;
};

### Please provide the exception or error you saw

```true
Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.3.3
Node: 21.7.3 (Unsupported)
Package Manager: npm 10.5.0
OS: darwin arm64

Angular: 17.3.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.3
@angular-devkit/build-angular   17.3.3
@angular-devkit/core            17.3.3
@angular-devkit/schematics      17.3.3
@schematics/angular             17.3.3
rxjs                            7.8.1
typescript                      5.4.4
zone.js                         0.14.4
```

**Comment by JoostK** [comment]
`inject` cannot be used after an `await` point, as that executes in a new event tick outside of the current stack. Consequently, any injection context that was available when the function began executing is no longer available after an `await`.
