### ISSUE TITLE
[http] MockBackend is no longer exported (alpha.48)

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#5639]
It looks like the `MockBackend` is no longer exported in the `http` module since c635a73ed9492e056acc04c199df9c1222b00e2c 

The docs still refer to `angular2/http` as its package, and it's not listed as a breaking change in the release notes, so I may be missing something, but it does break dozen of tests in my apps...

Maybe @robwormald has an answer?

**Comment by robwormald** [comment]
this is on purpose (sort of) as we don't want to ship it as part of the http distro. It *should* be available from `angular2/http/testing` - can you check that @cexbrayat ?

**Comment by cexbrayat** [comment]
Right, it indeed works with `angular2/http/testing`! 

If this is going to be the definitive package, I'll let the issue opened, as the docs should reference the correct package (and maybe add a breaking change in the release notes).

**Comment by robwormald** [comment]
@cexbrayat mind opening an issue over in https://github.com/angular/angular.io/issues ? - should be doc'ed over there. Added a PR to add this to the changelog here.

**Comment by cexbrayat** [comment]
I was talking about the internal reference in the code base : 

https://github.com/angular/angular/search?utf8=%E2%9C%93&q=MockBackend

**Comment by robwormald** [comment]
SIGH. ;-)

PR's welcome :-p

**Comment by cexbrayat** [comment]
No pb, I was working on it :)
