### ISSUE TITLE
requestAnimationFrame not work´s

### ISSUE THREAD

**Issue by BtoGarciaHdz** [angular/angular#56395]
### Is this a bug report or a feature request?

- [ ] Bug Report
- [X] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

Hello Community.
I'm doing an exercise using Angular v-22; it involves capturing video frames from the webcam and rendering them using "getContext" and replicating them with "requestAnimationFrame".

The fact is that I have already consulted the documentation and everything seems to be in order, but I can't get the webcam video to show.

Excuse me in advance if the content is in order; It's my first query.

-Angular v18
- CS code v1.90.0
- Firefox for developers v127.0b9 (64-bit)
- Microsoft Edge v125.0.2535.92

### Description [Feature Request only]

I attach the .component.html:

<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="">Login - FaceApi</a>
</nav>

<div class="container">
    <div class="row">

        <div class="col-4"></div>
        <div class="col-4" style="margin-top: 150px;">
            <div class="jumbotron bg-dark" style="color:white; text-align: center;">
                <h3> <i class="fa fa-video-camera"></i> Login - Face</h3>
                <hr class="my-4">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#staticBackdrop">Login</button>
            </div>
        </div>
        <div class="col-4"></div>
    </div>
</div>

<div class="modal fade mt-5" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header bg-dark">
          <h1 class="modal-title fs-5" id="staticBackdropLabel" style="color: white;">Identicicación facial</h1>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="card text-white bg-dark mb-3">
            <div class="card-header bg-secondary">Cámara de identifiación</div>
            <video style="position: absolute; top: 0;   visibility: hidden; left: 0; opacity: 0;" width="640" height="480" autoplay muted #videoContainer></video>
            <canvas width="640" height="480" autoplay class="js-canvas" #myCanvas></canvas><br>

          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" (click)="detectar()">Detectar rostro</button>
          <button type="button" class="btn btn-danger" (click)="removerVideo()">Close</button>
        </div>
      </div>
    </div>
  </div>
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

and I attach the .comonent.ts:

import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import * as faceapi from 'face-api.js'

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss'
})
export class LoginComponent implements OnInit {

  @ViewChild('videoContainer', {static: true}) videoContainer!: ElementRef;
  @ViewChild('myCanvas', {static: true}) myCanvas!: ElementRef;

  public context!:CanvasRenderingContext2D;

  constructor(){}

  ngOnInit(): void {

  }

  main = async()=>{

    this.context = this.myCanvas.nativeElement.getContext('2d');
    var video = await navigator.mediaDevices.getUserMedia({video: true});

    let stream = this.videoContainer.nativeElement;

    stream.scrcObjet = video;

    const reDraw = async()=>{
      this.context.drawImage(stream, 0, 0, 640, 480);
      requestAnimationFrame(reDraw);
    }

    requestAnimationFrame(reDraw);

  }

  detectar(){

    this.main();

  }

  removerVideo(){}

}

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
