### ISSUE TITLE
We detected an application built with production configuration. Angular DevTools only supports development build.

### ISSUE THREAD

**Issue by sbma24** [angular/angular#56399]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

I use a nx-workspace (nx Version 18.2.0) and I don't have an angular.json. Within the angular app is only a project.json which replaces the angular.json and contains all configurations of the angular project. 

I serve the angular app with the dev-configuration but I always get the message: **"We detected an application built with production configuration. Angular DevTools only supports development build."** with the notification **"A dev build is when the `optimization` flag is set to `false` in the angular.json config file."** in the console.

![image](https://github.com/angular/angular/assets/166792864/dc50332f-da5f-421e-bcdf-a70680816370)

The development config of the project.json set optimization to false:
`
"configurations": {
        "production": {
          "optimization": {
            "fonts": true,
            "styles": true,
            "scripts": true
          },
        "development": {
          "buildOptimizer": false,
          "optimization": false,
          "vendorChunk": true,
          "extractLicenses": false,
          "sourceMap": true,
          "namedChunks": true
        }
      },
`

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

Angular DevTools should see that this is a dev environment and work.

**Comment by JeanMeche** [comment]
Check you console, if your application doesn't expose a `ng` global, then your app is not in developement mode. 
Do you maybe have a `enableProdMode()` call in your app ?

**Comment by sbma24** [comment]
Thank you @JeanMeche. 

In the main.ts, the enableProdMode() is called but there was an error in my if-statement. There I checked if the value of the .env-File is true. But it's a string and it always run into true.

So I checked explicitly whether process.env['NX_PRODUCTION'] equals string 'true'

```

if (process.env['NX_PRODUCTION'] === 'true') {
  enableProdMode();
}
```
