### ISSUE TITLE
Signal Pipes

### ISSUE THREAD

**Issue by MillerSvt** [angular/angular#56407]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

It would be cool to add the ability to return signals from pipe, and automatically read them. Some pipes can change the result over time (because of a timer, or some data in the dependent service has changed, etc.). It is not very good to make them impure, as this can affect performance. Pipe can now return signals, but their use looks ugly. I would like native support.

### Proposed solution

countdown.pipe.ts
```typescript
import type {PipeTransform, Signal} from '@angular/core';
import {Pipe, computed} from '@angular/core';
import {toSignal} from '@angular/core/rxjs-interop';
import {interval} from 'rxjs';

const tickTimeout = 100;

@Pipe({
    name: `countdown`,
    standalone: true,
})
export class CountdownPipe implements PipeTransform {
    readonly #tick = toSignal(interval(tickTimeout), {
        initialValue: -1,
    });

    public transform(value: number, stepInterval = 1000): Signal<number> {
        const startTick = this.#tick();

        return computed(() =>
            Math.ceil(value - ((this.#tick() - startTick) * tickTimeout) / stepInterval),
        );
    }
}
```

app.component.html
```
{{ 20 | countdown }}
```

Also need add support for the pipes chain, some of which may be signal-pipe, and some may not:
```
{{ value | signalPipe | plainPipe | otherSignalPipe }}
```

### Current workaround

app.component.html
```
{{ (20 | countdown)() }}
```

```
{{ ((value | signalPipe)() | plainPipe | otherSignalPipe)() }}
```

**Comment by alxhub** [comment]
This is already possible today. There's no need to return a signal from a pipe, just read it within the pipe `transform` and it'll be tracked in the template. Here's a [simpler example](https://stackblitz.com/edit/signal-in-pipe) for a `timeout` pipe.
