### ISSUE TITLE
Example for CanMatchFn does not exist.

### ISSUE THREAD

**Issue by IceMikl** [angular/angular#56400]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

A new version of documentation for the CanMatchFn function does not contain an example of a function usage.
https://angular.dev/api/router/CanMatchFn?tab=description

The old version has an example.
https://v17.angular.io/api/router/CanMatchFn

### Please provide a link to a minimal reproduction of the bug

https://angular.dev/api/router/CanMatchFn?tab=description

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular Documentation version 18.
```

**Comment by JeanMeche** [comment]
Hi !
Let's continue tracking this issue with https://github.com/angular/angular/issues/56068 as it's the same root cause.
