### ISSUE TITLE
Compiling different parts of an Angular app in separate passes?

### ISSUE THREAD

**Issue by wwwillchen** [angular/angular#56413]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Hi - I'm developing Mesop (https://github.com/google/mesop) a Python UI framework built on top of Angular, and we're currently [proposing a solution](https://github.com/google/mesop/issues/95) for Mesop app developers to build their own custom web components.

I wanted to understand whether it's possible to compile the Angular app in separate passes.

For example, would it be possible to compile the core Mesop framework into a JS bundle (which is distributed as a pip package), and then _later_ (in a separate compilation run) to compile other Angular components?

IIUC, Angular's compilation model seems to be that everything should be compiled in a single pass (which can result in multiple JS bundles/splits).

Another consideration is that we'd like to support multiple versions of Angular in the same application because the core Mesop framework may want to upgrade Angular but the ecosystem of custom Mesop components could take more time to upgrade to the latest Angular version. IIUC, this is quite hairy because Angular has a global runtime which monkeypatches globals (e.g. zone.js) and having multiple versions of the runtime could cause issues. Is that right?

### Proposed solution

I don't have a proposed solution, just wanted to clarify my understanding.

### Alternatives considered

n/a

**Comment by alxhub** [comment]
👋 hey Will!

👋 hey Will!

The pattern you're describing is essentially "i want my application to load and link code that wasn't compiled with it", which is not a unique problem to Angular. There are a few popular solutions in the JavaScript ecosystem, such as [Module Federation](https://module-federation.io/guide/start/index.html#-what-is-module-federation). While the Angular CLI doesn't have first-party support for this mode of operation, our community has built [third-party integrations](https://www.npmjs.com/package/@angular-architects/module-federation).

There are different architectures possible here, with different tradeoffs, but the most common / sensible one would be that Mesos is the host application, and selects the Angular runtime version. Plugins (custom components) are built separately, and use the runtime from the host application. This is technically possible, although tricky to implement and has a few caveats (mostly related to `NgModule`s not working properly).

Things get easier if it's possible to compile the host application and all the custom components together, of course.

> Another consideration is that we'd like to support multiple versions of Angular in the same application because the core Mesop framework may want to upgrade Angular but the ecosystem of custom Mesop components could take more time to upgrade to the latest Angular version. IIUC, this is quite hairy because Angular has a global runtime which monkeypatches globals (e.g. zone.js) and having multiple versions of the runtime could cause issues. Is that right?

I don't think this is really a problem. In Angular, an application using version X can reliably use libraries built with a minimum version of X - 2 - this is the backwards compatibility guarantee we provide. So if you think of the custom components as libraries, it's fine for them to fall behind the main application in their Angular version.

The opposite isn't true - you can't write such a component using version X + 1 and expect it to work in an application running Angular X. It's easy to see why this is the case: such a component could make use of features of Angular X+1 that wouldn't be supported by the runtime used in the application.

**Comment by wwwillchen** [comment]
Thanks for the responses - appreciate the detailed explanation. I'll revisit the option of compiling everything together in one pass as that seems like the recommended approach.
