### ISSUE TITLE
Broken link - Error: NG0952

### ISSUE THREAD

**Issue by ddx001** [angular/angular#56424]
### Describe the problem that you experienced

I got this error:

Error: NG0952: Model is required but no value is available yet. Find more at https://angular.dev/errors/NG0952

But url is not found.

### Enter the URL of the topic with the problem

https://angular.dev/errors/NG0952

**Comment by JeanMeche** [comment]
Actually we don't have any dedicated docs for this error. #56441 will remove the link from the error.
