### ISSUE TITLE
v18, routerLink not working

### ISSUE THREAD

**Issue by milanbella** [angular/angular#56430]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

follow the steps in router doc https://angular.dev/guide/routing/common-router-tasks

`routerLink` renders as plain text, no click possible

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.3
Node: 20.12.2
Package Manager: npm 10.7.0
OS: win32 x64

Angular: 18.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.3
@angular-devkit/build-angular   18.0.3
@angular-devkit/core            18.0.3
@angular-devkit/schematics      18.0.3
@schematics/angular             18.0.3
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

### Anything else?

![image](https://github.com/angular/angular/assets/4014265/26d70081-6f4e-4139-bc04-cb9d516dc400)

**Comment by json-derulo** [comment]
Read carefully, seems like you missed the second part of step 3:

> You also need to add the `RouterLink`, `RouterLinkActive`, and `RouterOutlet` to the imports array of `AppComponent`.

**Comment by atscott** [comment]
this appears to be working as expected. As mentioned, it’s likely you missed the final step of importing the directive.

**Comment by milanbella** [comment]
I added, thanks a lot, it works now!

[image: image.png]

[image: image.png]
