### ISSUE TITLE
Bad rxjs import in facade/async.js

### ISSUE THREAD

**Issue by SonofNun15** [angular/angular#5643]
In `angular2@2.0.0-alpha.48`:

`facade/async.js` line 19 calls `require('rxjs/operators/toPromise');`

As of `rxjs@5.0.0-alpha.12` this folder was renamed to `operator/toPromise.js`.

The result is that a jspm install of angular 2 without bundling gets the following error:
```
GET http://localhost:8080/jspm_packages/npm/rxjs@5.0.0-alpha.12/operators/toPromise.js 404 (Not Found)
```

The rxjs version should either fixed at version `alpha.10` or this reference udpated to `operator/toPromise.js`

**Comment by SonofNun15** [comment]
Looks like `alpha.10` is not compatible either because it has an `observables` folder when `async.js` line 18 calls `require('rxjs/observable/fromPromise')`.

**Comment by SonofNun15** [comment]
Is the import on line 19 supposed to be `operators/toPromise`?

Reference: `facade/toPromise.ts` line 13.

**Comment by SonofNun15** [comment]
Pretty simple to reproduce this issue:
* create a new directory, init an empty npm repository, `npm install jspm --save-dev`
* enter `jspm init`
* enter `jspm install angular2`
* add a simple index.html:
```
<html>
	<head>
		<script src="/jspm_packages/system.js"></script>
		<script src="/config.js"></script>
		<script>
			System.import('app');
		</script>
	</head>
</html>
```
main.ts:
```
import { bootstrap } from 'angular2/angular2';
import { AppComponent } from './app';

bootstrap(AppComponent);
```
app.ts:
```
import { Component } from 'angular2/angular2';

@Component({
    selector: 'set-manager-pro',
    template: `
        <h1>Set Manager Pro</h1>
		<p>{{title}}</p>
    `,
})
export class AppComponent {
    public title: string = 'My First Angular 2 App';
}
```
config.js (SystemJS config):
```
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "typescript",
  typescriptOptions: {
    "module": "commonjs",
    "emitDecoratorMetadata": true
  },
  paths: {
    "npm:*": "jspm_packages/npm/*",
    "github:*": "jspm_packages/github/*"
  },

  packages: {
    "app": {
      "main": "main",
      "defaultExtension": "ts"
    }
  },

  map: {
    "app": "source",
    // maps configured by jspm
  },
});
```

**Comment by robwormald** [comment]
crud, yep. lot of churn between these two libs in the past couple of days, so this definitely should have been locked.

@jeffbcross are we done shifting things around in rxjs for the moment do we think?

**Comment by SonofNun15** [comment]
Thanks for the prompt action on this. Really excited with the direction things are going in Angular 2!

**Comment by kylecordes** [comment]
I hadn't noticed this error in a full day of work with the bundles shipped in the angular2 NPM module, but as noted above it appears immediately with a trivial app using JSPM, and I experienced the same error testing Alpha 48 with Webpack. Maybe the A2 build/test suite should try running/building a couple of example apps, with at least a couple of tools often used for that purpose?
