### ISSUE TITLE
consider new pipe syntax `|` to `|>` from es7 proposal 

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#5645]
the `|>` es7 proposal reminds me of angular 1's filter syntax
https://github.com/mindeavor/es-pipeline-operator

```es6
function doubleSay (str) {
  return str + ", " + str;
}
function capitalize (str) {
  return str[0].toUpperCase() + str.substring(1);
}
function exclaim (str) {
  return str + '!';
}

var result = exclaim(capitalize(doubleSay("hello")));
result //=> "Hello, hello!"

var result = "hello"
  |> doubleSay
  |> capitalize
  |> exclaim;

result //=> "Hello, hello!"
```

**Comment by PascalPrecht** [comment]
What kind of "consideration" do you mean here?

**Comment by kylecordes** [comment]
I am not the original poster; but the obvious consideration would be: if ESn actually adopts |> as a function chaining operator, extend the Angular expression syntax, which already has something very similar in function ("|"), to also accept the new operator as a synonym.

One downside of this would be to further confuse Angular expression with JavaScript expressions; they are similar in appearance but don't have quite the same semantics, so making the syntax ever more similar could be a step in the wrong direction.

**Comment by PascalPrecht** [comment]
> I am not the original poster; but the obvious consideration would be: if ESn actually adopts |> as a function chaining operator, extend the Angular expression syntax, which already has something very similar in function ("|"), to also accept the new operator as a synonym.

Is it really that obvious? TBH I thought we should consider using that **language** feature inside Angular. Which is where we have to wait for TS to implement this first I think..

**Comment by vicb** [comment]
we'll see if the proposal gets accepted
