### ISSUE TITLE
Allow Angular Templates to use the html template function from Lit?

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular#56458]
### Description

The [Lit Element](https://github.com/lit/lit-element) is very similar to Angular in a lot of ways and it produces pure web components.

Just if Angular could use the Lit `html` tag function to produce templates that are compatible with Lit?

### Proposed solution

Closer integration with Lit and Angular

### Alternatives considered

Use Angular the way it is.  It's pretty phenomenal already ...

**Comment by alxhub** [comment]
I don't think this is very likely. Angular and Lit are separate frameworks with very different component models. Even if such an interop were technically possible, it would be very low on our priority list compared to our [other planned efforts](https://angular.dev/roadmap) to evolve Angular.
