### ISSUE TITLE
Issues using angular cdk drag and drop with angular form array

### ISSUE THREAD

**Issue by sandeepsuvit** [angular/angular#56468]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Hi I was trying to implement a sorting screen using cdk drag and angular form array. After adding the form array elements dynamically (say 3 elements) i tried to sort it (3 item moved to the top) but the order of the items got jumbled up. Its happening only on the ui side and not with the form value. The form value data is displaying like I intended it to be. 

Attaching the screenshot of the steps followed

1. <img width="588" alt="Screenshot 2024-06-15 at 5 03 12 PM" src="https://github.com/angular/angular/assets/4330496/b6984c59-1725-4877-a678-fc861b6420be">
2. <img width="705" alt="Screenshot 2024-06-15 at 5 04 12 PM" src="https://github.com/angular/angular/assets/4330496/36b81514-62c7-4cd6-b58b-8c317ac0e713">
3. <img width="725" alt="image" src="https://github.com/angular/angular/assets/4330496/13d6766d-21ae-46ab-a61b-b0365e461a76">

In the 3rd screenshot you can see that the ui is showing `Sub task 2` as the top most element, but I tried dragging the `Sub task 3` to the top. You can also see the json data has correctly captured the data with `Sub task 3` being at the top.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-nhwqqw

### Please provide the exception or error you saw

```true
There is no exception, but the order of items is jumbled and not according to the order it was intended.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.1
Node: 20.13.1
Package Manager: npm 10.8.0
OS: darwin x64

Angular: 18.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.1
@angular-devkit/build-angular   18.0.1
@angular-devkit/core            18.0.1
@angular-devkit/schematics      18.0.1
@angular/cli                    18.0.1
@schematics/angular             18.0.1
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.6
```

**Comment by JoostK** [comment]
This is essentially the same as #56467, so closing as a duplicate.
