### ISSUE TITLE
Control Flow - Allow wrapping element for `@for`

### ISSUE THREAD

**Issue by pBouillon** [angular/angular#56463]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

With its current form, it's hard to wrap a sequence of element resulting of the enumeration of `@for` while having a different template for the `@empty` block.

For instance, let's consider a todo list:

```html
<ul>
  @for (item of todoItems; track item.id) {
    <li>{{ item.description }}</li>
  }
  @empty  {
    <p>No item yet</p>
  }
</ul>
```

In this template, the previous code would result in this template for an empty `todoItems`:

```html
<ul>
  <p>No item yet</p>
</ul>
```

Which is not what I would like if I only want to have the message.

On the other hand, I can also do the following:

```html
@if (todoItems.length > 0) {
  <ul>
    @for (item of todoItems; track item.id) {
      <li>{{ item.description }}</li>
    }
  </ul>
}
@else {
  <p>No item yet</p>
}
```

Unfortunately, I'm losing the advantage of `@empty` (along with its semantic clarity) and nesting everything if I am proceeding like this.

### Proposed solution

I honestly don't know what a solution could look like but it feels like the `@empty` block lacks of flexibility for such cases that prevent its usage.

### Alternatives considered

Wrapping the whole collection in an `@if` and checking if its empty or not before enumerating does the same thing, despite being less clear than the meaning `@empty` immediately conveys, and more verbose.

**Comment by alxhub** [comment]
I think wrapping the whole collection in `@if` is exactly the right solution if you want to display an entirely different UI. There can be an arbitrary amount of structure around the `@for` that you want to remove if the list has no items, and I don't think we should complicate `@for` to be capable of that.
