### ISSUE TITLE
The reset method of FormControl is setting the value to null instead of setting it to the initial value.

### ISSUE THREAD

**Issue by patrick095** [angular/angular#56473]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

When I call the reset `method` of the `FormControl` class, the FormControl's value becomes null. Shouldn't the initial value be selected instead when an initial value is passed during class instantiation?

### Proposed solution

- Save the InitialValue during `FormControl` class instantiation
- Set the initialValue when call reset method

### Alternatives considered

In all my projects, I create a class that extends `FormControl` and manually adjust this behavior. However, I believe this could be the default behavior in Angular.

**Comment by destus90** [comment]
You should use `nonNullable` option.

https://github.com/angular/angular/blob/ee8ecfaef06c9acafa17c69884c15921419b9684/packages/forms/src/model/form_control.ts#L170

**Comment by JoostK** [comment]
[Or use `NonNullableFormBuilder`](https://angular.dev/guide/forms/typed-forms#formbuilder-and-nonnullableformbuilder). Closing as this is already possible.
