### ISSUE TITLE
The `@angular/localize API` link directs to a 404

### ISSUE THREAD

**Issue by dario-piotrowicz** [angular/angular#56479]
### Describe the problem that you experienced

On https://angular.dev/guide/i18n/add-package if you click the `@angular/localize API` link in the [What's next](https://angular.dev/guide/i18n/add-package#whats-next) section you get redirected to a 404 Page:
![Screenshot 2024-06-17 at 18 37 22](https://github.com/angular/angular/assets/61631103/b46ca315-b400-47cb-9c7b-336ee3c8fbf1)

### Enter the URL of the topic with the problem

https://angular.dev/guide/i18n/add-package

**Comment by ViktorTyultinov** [comment]
@JeanMeche I would love to fix this one

**Comment by JeanMeche** [comment]
@ViktorTyultinov We don't have the corresponding page anymore, If you want to make the change, you could probably just remove the link.

**Comment by ViktorTyultinov** [comment]
Okay I am on it
