### ISSUE TITLE
Missing documentation for global `ng` variable

### ISSUE THREAD

**Issue by BaerMitUmlaut** [angular/angular#56488]
### Describe the problem that you experienced

The global `ng` variable is quite useful when debugging without using an extension, but the only mention I could find of it is [here](https://angular.dev/tools/cli/deployment#development-only-features):
> Additional debugging utilities such as the global ng variable and [Angular DevTools](https://angular.dev/tools/devtools) support.

However, there is no mention of what it can do and how to use it.

### Enter the URL of the topic with the problem

https://angular.dev/tools/cli/deployment#development-only-features

### Describe what you were looking for in the documentation

Documentation of the functions the `ng` global provides.

**Comment by JeanMeche** [comment]
What you are looking for is probably https://angular.dev/api#core-global, maybe we would link to this section.
