### ISSUE TITLE
Link gets broken with space character in its end

### ISSUE THREAD

**Issue by isaque-dantas** [angular/angular#56482]
### Describe the problem that you experienced

In [this page](https://angular.dev/api/forms/FormControlOptions?tab=description), the link named "AbstractControlOptions " (attention to the white space after) goes to a [non-existent page](https://angular.dev/api/forms/AbstractControlOptions%20). It's just because the white space character "%20" after the link itself. The page, properly, is all right.

### Enter the URL of the topic with the problem

https://angular.dev/api/forms/FormControlOptions?tab=description

### Describe what you want to experience that would fix the problem

1. Setup some filter for don't let white space characters in the end of links.
2. Build a automated searcher for white space characters inside HTML anchor tags across the whole documentation. The searcher can do that once a week, once a month, for example.

**Comment by JeanMeche** [comment]
Thank you for reporting this issue,

This is due to microsoft/TypeScript#58584, this will be fixed once we update the repo to TS 5.5
