### ISSUE TITLE
Missing documentation for InjectionToken

### ISSUE THREAD

**Issue by rush1818** [angular/angular#56495]
### Describe the problem that you experienced

angular.dev site is missing the examples for InjectionToken

### Enter the URL of the topic with the problem

https://angular.dev/api/core/InjectionToken?tab=usage-notes

### Describe what you were looking for in the documentation

The examples from the earlier site should be displayed here: https://v17.angular.io/api/core/InjectionToken

### Bug:

![image](https://github.com/angular/angular/assets/17676675/210426a8-3a7a-4c75-9437-7c5120e1ee04)

### Working examples in old site:

![image](https://github.com/angular/angular/assets/17676675/e2f941b8-39b4-409d-9f48-cd4b40438eef)

**Comment by JeanMeche** [comment]
Hi !
Let's continue tracking this issue with https://github.com/angular/angular/issues/56068 as it's the same root cause.
