### ISSUE TITLE
Some examples not showing in router API docs page

### ISSUE THREAD

**Issue by esteban389** [angular/angular#56490]
### Describe the problem that you experienced

I was reading some of the API reference docs pages and noticed that some of the examples are not showing as they should it's not in just one, i noticed three but i'm not sure if there might be others somewhere else.

### Enter the URL of the topic with the problem

https://angular.dev/api/router/CanDeactivateFn?tab=description

### Describe what you were looking for in the documentation

An example of how to use some function signatures for guards on a Route

### Describe the actions that led you to experience the problem

I was trying to learn more about guards by reading the API reference on but some examples are not displayed

### Describe what you want to experience that would fix the problem

In the screenshots i uploaded the second, from the CanActivateFn reference is the behavior I expected.

### Add a screenshot if that helps illustrate the problem

![Captura de pantalla 2024-06-18 082203](https://github.com/angular/angular/assets/103962731/6be44d54-3c01-4aec-add4-67b4579ddd33)
![Captura de pantalla 2024-06-18 082244](https://github.com/angular/angular/assets/103962731/e05386da-9b6a-4ac8-9aef-294db1d45dcd)

**Comment by JeanMeche** [comment]
Hi !
Let's continue tracking this issue with https://github.com/angular/angular/issues/56321 as it's the same root cause.
