### ISSUE TITLE
Cannot run test with ChromeHeadless in Continuous Integration

### ISSUE THREAD

**Issue by alaindeurveilher** [angular/angular#56492]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Hello,

I am trying to make my CICD work with GitLab CICD runner, but the test job fails.

I followed the instructions on the documentation:
https://angular.dev/guide/testing#testing-in-continuous-integration

So, in my .gitlab-ci.yml I configured my job as so:

```yml
test:
  image: artifactory.my-organisation/docker/node:20
  before_script:
    - yarn install
  script:
    - yarn test:cicd
```

where the test script is defined as so in the package.json:

```json
  "scripts": {
    "test": "yarn generate:libs:local && ng test",
    "test:once": "yarn test --no-watch",
    "test:cicd": "yarn test:once --no-progress --browsers=ChromeHeadless",
  },
```

So that ultimately the following command in executed in my node container:
`ng test --no-watch --no-progress --browsers=ChromeHeadless`

But the job fails with the following error, which is not documented in the testing section of the Angular documentation:

```
ERROR [launcher]: No binary for ChromeHeadless browser on your platform.
  Please, set "CHROME_BIN" env variable.
error Command failed with exit code 1.
```

What would be the correct setup please?

### Please provide the exception or error you saw

```true
ERROR [launcher]: No binary for ChromeHeadless browser on your platform.
  Please, set "CHROME_BIN" env variable.
error Command failed with exit code 1.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/core": "^17.3.11",
"karma": "~6.4.0",
"karma-chrome-launcher": "~3.2.0",

Docker image: node:20
```

**Comment by alan-agius4** [comment]
Likely this is caused because the image that you are using does not include Chrome installed.
See: https://stackoverflow.com/questions/65837359/docker-container-gives-no-binary-for-chrome-browser-on-your-platform
