### ISSUE TITLE
Support VSCode intellisense for `@Attribute` / `HostAttributeToken` usage.

### ISSUE THREAD

**Issue by maximLyakhov** [angular/angular#56504]
### Which @angular/* package(s) are relevant/related to the feature request?

language-service

### Description

`@Attribute` decorator is already banned by [angular-eslint/no-attribute-decorator](https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin/docs/rules/no-attribute-decorator.md).

Instead we have `HostAttributeToken` which lacks support for:

- Passing generic primitive type (string | number | boolean) or primitive union ('some' | 'thing') (as in inputs)
- Transform property (with use of *Attribute functions from `@angular/core`) (as in inputs)
- Language service intellisense respecting allowed types (as in inputs)
- Update docs to point to `one-time binding` capabilities.

### Proposed solution

Completing bullets above would allow to close feature requests for one-time inputs: [#14033](https://github.com/angular/angular/issues/14033) [#55581](https://github.com/angular/angular/issues/55581) and the need of detaching the view from changeDetection runs as a workaround.

Such approach to `HostAttributeToken` usage would then make easy to switch to `inject` / `signal` / `non-reactive value` / `@Input` / `input` if a framework user would need it because of preserving typings during rewrite. 

Library developers and advanced users would benefit from it from performance and bundle size perspective.

### Alternatives considered

Only alternative is typed `@Input` or `input()`.
But this approach creates unnecessary bindings for expected-as-one-time inputs with primitive values, in the end makes bundle bigger and client app work more every cd run, instead of making `language-service` to work a tiny bit more.

**Comment by maximLyakhov** [comment]
@pkozlowski-opensource thanks for clarification. Sorry for messed explanation.

The main point was adding property intellisense for `@Attribute` / `HostAttributeToken` in templates.
Will it make sense to open PR with this scope only at `language-service`?

**Comment by pkozlowski-opensource** [comment]
> The main point was adding property intellisense for @Attribute / HostAttributeToken in templates.
Will it make sense to open PR with this scope only at language-service?

Depending on what you've got in mind in terms of intellisense

**Comment by maximLyakhov** [comment]
@pkozlowski-opensource 
Autocompleting property name (which has marked by `HostAttributeToken`) in template and hinting that it accepts string.

Such as

```
@Component({selector: 'child-with-attributes'})
class ChildComponent {
  public color = inject(new HostAttributeToken('color'));
}
```

```
@Component({
  template: `
    <child-with-attributes co... /> // here we get hint: color=""
  `
})
class ParentComponent {}
```

or visually:

<img width="340" alt="Screenshot 2024-06-20 at 15 30 10" src="https://github.com/angular/angular/assets/75264285/d7f22532-edeb-496b-a67a-4412e16c1e11">

But without `[property]=""` notation.

**Comment by maximLyakhov** [comment]
@pkozlowski-opensource is aforementioned feature appropriate framework-wise for implementing in language service?
