### ISSUE TITLE
ChangeDetection is not triggered after http put when using provideExperimentalZonelessChangeDetection on Angular 18

### ISSUE THREAD

**Issue by asanoic** [angular/angular#56513]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

my code is pretty simple like
```typescript
  itemDetail = model<any>(XXXXComponent.EMPTY_DETAIL);
  treeNodes = signal(new Map<string, any>(), { equal: () => false });
  
  public async saveClicked(): Promise<void> {
    const result = await this.apiEntity.updateEntity(this.itemDetail()); // comment this line ui will change
    this.treeNodes().get(this.itemDetail().id).name = this.itemDetail().name;
    // this.cd.markForCheck();                                           // or add this line to force CD.
  }
```

updateEntity just a http put call:
```typescript
  async updateEntity(item: any): Promise<any> {
    const { result } = await firstValueFrom(this.http.put<any>(`${environment.apiUrl}/item`, item));
    return result;
  }
```

my target code is Firefox 70, because my browser does not support `Nullish coalescing operator`

### Please provide a link to a minimal reproduction of the bug

SORRY

### Please provide the exception or error you saw

```true
No exception
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.4
Node: 22.3.0
Package Manager: npm 10.8.1
OS: linux x64

Angular: 18.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.4
@angular-devkit/build-angular   18.0.4
@angular-devkit/core            18.0.4
@angular-devkit/schematics      18.0.4
@angular/cli                    18.0.4
@schematics/angular             18.0.4
rxjs                            7.8.1
typescript                      5.4.5
webpack                         5.92.0
```

**Comment by jnizet** [comment]
AFAIK, that's completely expected. You're supposed to update signals (or call markForCheck()) in order for Angular to change the DOM, since there is no ZoneJS anymore to tell Angular that some asynchronous event was handled.

**Comment by JeanMeche** [comment]
Yes, this is the expected behavior. in zoneless apps, CD is fired on signal updates, AsyncPipe values and when template listeners fire.

**Comment by asanoic** [comment]
@JeanMeche @jnizet could you explain more, why everything works when I just removed that http put request? that http request is even not related to ui update. Do you mean when I use zoneless, I have to add CD manually for all async/await call?

**Comment by jnizet** [comment]
@asanoic When you remove that http request, you have a synchronous change caused by an event listener added through event binding in the template, which schedules a CD. 
OTOH, when you add that http request, the change happens after an asynchronous http response that Angular is unaware of, since... you chose to use the experimental zoneless change detection.
Choosing zoneless CD is not something you can do without much much care: every change you make must be known by Angular. And the easiest way to do that is to use signals or the async pipe (like in OnPush components): if the code, whene receiving the http response, makes all the changes in the state by updating signals that are read by templates of components, then Angular will know that these components must be checked.

> that http request is even not related to ui update

Well, it is indirectly, since you update the name of a tree node only after you receive the response to the http request.

**Comment by asanoic** [comment]
I got it, even I just change http request line to `await firstValueFrom(timer(0));`, UI is still not get updated.

Do you have any suggestion or best practice about how to handle this case? just simple add a manual CD?
for example, I have a tree component, and only load the children (from new http request) when user click it. all structure is store in a map (key is id, and unique for all tree node). before I use signal and zoneless, I just simple stored the json which I get from http, but now, if I want to trigger CD, I have to convert json to a signal version like

from
```typescript
{
  id : string;
  name : string;
  children: string[];
  opened: boolean;
}
```
to
```typescript
{
  id : WritableSignal<string>;
  name : WritableSignal>string>;
  children: WritableSignal<WritableSignal<string>[]>;
  opened: WritableSignal<boolean>;
}
right?

**Comment by jnizet** [comment]
A single signal containing an object (with id, name, children and opened) is probably sufficient, as long as you don't mutate the object, but create a new one that you store in the signal. 
But I have far too few information on what your tree is supposed to do to provide a definitive answer.
