### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Alamin-Ahammed** [angular/angular#56511]
### Describe the problem that you experienced

I was studying the tutorial, below the part 
"Your first Angular app
Add dynamic values to templates" at "For more information about the topics covered in this lesson, visit:" 
[Template syntax](https://angular.dev/guide/templates/interpolation)
[Displaying values with interpolation](https://angular.dev/guide/templates/template-syntax)
is saying page not found. I think the routing is wrong here. please fix it.

### Enter the URL of the topic with the problem

https://angular.dev/guide/templates/template-syntax

**Comment by jdegand** [comment]
Think it should be pointing to `https://angular.dev/guide/templates`.  

Difference between old docs and new docs is that the overview route does not change the URL on `.dev`.
