### ISSUE TITLE
@else if and signals narrowing

### ISSUE THREAD

**Issue by oleks12345** [angular/angular#56516]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Hi, 
I've seen the discussion in #52103  but I'm not sure how to handle this case
```
@if(loading()) {
    <message/> 
} @else if(item().steps as steps) { // this throws the error
    <external-component-not-accepting-undefined [steps]="steps" /> 
}
```

**Comment by JeanMeche** [comment]
Unfortunately narrowing in template doesn't work at the moment.
You can follow #49161 for updates on that topic.
