### ISSUE TITLE
Provide a option to print an error report in the browser if Angular failed to launch due to a JS error 

### ISSUE THREAD

**Issue by mattiLeBlanc** [angular/angular#56510]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

We have build a solution for our customers that is used on many different devices, including TV's and their browsers, or smartboards.
The problem I am running into is that some of these devices do fail to setup the angular app and since it is a device with no development toolbars or any access into what caused the error, I am blind as to watch is causing the issue.

I am using an App Error Handler, which can report errors to our slack channel, but that only works if the Angular app was launched correctly.

I created a little mini project to try report an error in the browser if the JS fails to load, but that is not a complete reflection of our product. 
With that I found that some TV's don't like Nullish_coalescing_assignment operator (??=) and I could use browserlistrc to force Safari >= 13 which get's rid of that operator.
But now I am facing another error which results in a white screen.

### Proposed solution

Solution: it would be great it Angular had some kind of try/catch mechanism which could report on errors that occur trying to load the angular app and it can be printed in the window. 
I know it will be crude, but at least it is better than a white screen.
It could show that the angular app failed to load because of this specific reason and show the stack trace if possible.

### Alternatives considered

Maybe the consensus is that this is not Angular's responsibility  and it should be dealt with by the developer.
But then it would be nice to maybe create a blog about this with pointers for others so we can deal with the nightmare of supporting a wide range of devices.

**Comment by JeanMeche** [comment]
You should be able to do this by catcing the error on bootstraping : 

`bootstrapApplication(AppComponen).catch((error) => alert(error));`

**Comment by mattiLeBlanc** [comment]
@JeanMeche Would that included errors like when web-animations are not supported or some Core JS Functions are missing?

**Comment by JeanMeche** [comment]
Anything that throws an error on bootstrap. 
Else you'll probably want to attach an ErrorHandler : https://angular.dev/api/core/ErrorHandler

**Comment by JoostK** [comment]
Note that syntax errors will prevent the script from executing at all, so you can only catch those from a different script that sets up a global error handler (a browser error handler, not Angular's error handler).

This is outside the scope of Angular as a framework, though.

**Comment by mattiLeBlanc** [comment]
@JoostK Hi Joost, I am mainly concerned about things like lack of support for Nullish_coalescing_assignment in a browser on a TV.
That would be treated as a syntax error because that TV browser doesn't support it and would result in a white screen.
I don't think that would be caught in the bootstrap Catch function.

So I need 2 levels of reporting: one one syntax errors which I am currently doing by listening to `window.addEventListener("error", function (event) {` and trying to report that to the screen.

And second, it would be lack of support of for example web-animations or core-js functions (like array from I believe).
IF that would be caught by the bootstrap Catch clause, that would be great, but I am not sure of that.

**Comment by alan-agius4** [comment]
@mattiLeBlanc, as @JoostK mentioned, these errors are beyond Angular's control because they prevent the script from running altogether. The issue may depend on whether `Array.from` is used in a local or global scope.

That said, it appears you are using Angular on browsers that aren't officially supported. You can check the list of supported browsers here: https://angular.dev/reference/versions#browser-support.

**Comment by mattiLeBlanc** [comment]
@alan-agius4 The problem I am facing is that our customers, facilities, use it one devices beyond our control.
And one device was working on Angular 17 but it stopped working on Angular 18. There could be many reasons for that, but all I get from them is that they now see a white screen.

So I am trying to find ways to collect error information.

I am very much aware of browser support but I I think Angular is pretty much relying on running on modern devices.
But I have to support dodgy TV OS Browsers, there are so many flavours it is hard to track down.

But anyway, I understand it is not part of Angular's scope or responsibility. However, if Angular is relying on modern browsers, it would be great it there is some tooling around to help developers debug why this current version of the Angular app is not running.

The `catch` of the bootstrap function may be helpful, that is if something is breaking within Angular, like perhaps `web-animations` not being supported on that device. 
But if it is things like null coalescing operator not being supported in the  JS dist files, that is harder to catch. But I can try a higher level error listner on the window object to catch those, perhaps.
