### ISSUE TITLE
ng update does not migrate the asset folder to the new public folder

### ISSUE THREAD

**Issue by jdiemke** [angular/angular#56515]
### Which @angular/* package(s) are relevant/related to the feature request?

upgrade

### Description

Since Angular 18 the asset folder does not exist anymore. This is not documented in the migration guide and also not done automatically when using ng update.

### Proposed solution

Add to migration guide or ask during ng update whether this should be done automatically.

### Alternatives considered

do nothing.

**Comment by JeanMeche** [comment]
Exisiting apps should continue to work as before. 
The `public` directory is only created on new project. 

Which issue did you encounter ?

**Comment by jdiemke** [comment]
There is no issue. Everything works as expected. I just want to migrate my project to the newest recommendations. I can adjust this myself of course.

**Comment by JeanMeche** [comment]
Our schematics and migration guide are here to migrate the breaking changes. 
Feel free to update your project as suits you.
