### ISSUE TITLE
App crash  when using ngFor with mapped data and a routerLinkActive directive inside the loop.

### ISSUE THREAD

**Issue by AdrLeon** [angular/angular#56536]
### Which @angular/* package(s) are the source of the bug?

common, core, router

### Is this a regression?

Yes

### Description

The application crashes when creating a selector with ngFor where the data is transformed using a map function. Additionally, when utilizing navigation within the component inside the loop that includes the routerLinkActive directive, the application crashes. It also crashes if navigation is performed directly.

### Please provide a link to a minimal reproduction of the bug

https://github.com/AdrLeon/devextreme-routing/tree/angular-routerLinkActive-map

### Please provide the exception or error you saw

```true
No error shown.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular cli: ^18.0.4
Node: 18.20.2
OS: windous x64

Angular: ^18.0.0
```

**Comment by jnizet** [comment]
Your code creates a new Routes array with new objects inside at each change detection, by calling the `secondaryRoute()` function from the template.
You shouldn't do that. Instead, create the Routes array once and for all and store it in a property. Then use that property inside the template.
