### ISSUE TITLE
FetchBackend expects case sensitive 'Content-Type'

### ISSUE THREAD

**Issue by wduminy** [angular/angular#56539]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

Yes

### Description

The snippet below creates a request with header `content-type: image/jpeg, application/json`
```ts
   let headers = new HttpHeaders();
    headers = headers.set('content-type', 'image/jpeg');
    const req = new HttpRequest("PUT", somePutUrl, { data: someData }, {
         headers,
         reportProgress: true,
         responseType: "text",
    });
   return this.client.request(req);
 ```
Change the case and I get the expected behaviour:
```ts
   let headers = new HttpHeaders();
    headers = headers.set('Content-Type', 'image/jpeg');
    const req = new HttpRequest("PUT", somePutUrl, { data: someData }, {
         headers,
         reportProgress: true,
         responseType: "text",
    });
   return this.client.request(req);
 ```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.0
Node: 18.16.0
Package Manager: npm 9.5.1
OS: darwin arm64

Angular: 17.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.0
@angular-devkit/build-angular   17.1.0
@angular-devkit/core            17.1.0
@angular-devkit/schematics      17.1.0
@angular/cdk                    17.0.1
@angular/material               17.0.1
@schematics/angular             17.1.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else?

The problem could be [here](https://github.com/angular/angular/blob/29ca6d10cc3cd75ebdf64658dafcb3ce579af343/packages/common/http/src/fetch.ts#L164)

**Comment by JeanMeche** [comment]
It looks like the behavior is consistent with how the XhrBackend is behaving. Although I agree headers should be case insensitive.

**Comment by diesieben07** [comment]
The XhrBackend behaves differently. It uses `HttpHeaders#has`, which is a case-insensitive check.

**Comment by JeanMeche** [comment]
Right, I must have missed something in my tests. 

#56539 will provide the fix for this. Thank you for the investigation.

**Comment by wduminy** [comment]
@JeanMeche Quick update: In the code I reported above I used JSON data; but when I used binary data -- a more realistic use case -- the problem did not occur -- i.e. `application/json` was not inserted.  

So case sensitivity might be a problem; but the use-case here is certainly "contrived by accident".

**Comment by diesieben07** [comment]
@wduminy The reason that binary data doesn't exhibit the same behavior is that Angular doesn't have a content type to infer.
