### ISSUE TITLE
Documentation on Content Projection

### ISSUE THREAD

**Issue by davidnaumann-bastian** [angular/angular#56548]
### Describe the problem that you experienced

I think that the documentation here could lead to some false assumptions on how ng-content works when using a component selector.

In the example for multiple content placeholders was working on the pretenses that <card-header> doesn't need to be defined as a custom component (which is almost true as when rendering it'll work but will fail in testing).

I think it is missing v17 examples for doing it as a class selector and directive selector as well.

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/content-projection#multiple-content-placeholders

### Describe what you were looking for in the documentation

This block should callout that <card-header> is needed to be defined as a component to avoid getting an error logged in the console (and possibly errors generated during testing).

![image](https://github.com/angular/angular/assets/99202780/786a7e1c-283a-4928-be9b-a6d76e5b2f27)

### Describe the actions that led you to experience the problem

Possibly just a misunderstanding on how ng-content works that was further worsened by reading the documentation for it.

### Describe what you want to experience that would fix the problem

I think further specification of how to use the selector for components that don't exist (or that they need to be defined) should be included in the documentation.

I think that examples from v17 on how to do class selector and directive selector for v18 should be included.

### Add a screenshot if that helps illustrate the problem

Shortened button.html looks like this:
```
<button>
    <ng-content select="button-text"></ng-content>
</button>
```

Using it within shortened drawer.html:

```
<nav>
  <common-ui-button>
    <button-text>Test</button-text>
  </common-ui-button>
</nav>
```

### If this problem caused an exception or error, please paste it here

```true
Using my button component in the drawer component:

Error: NG0304: 'button-text' is not a known element (used in the 'DrawerComponent' component template):
        1. If 'button-text' is an Angular component, then verify that it is included in the '@Component.imports' of this component.
        2. If 'button-text' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@Component.schemas' of this component to suppress this message.
```

### Provide any additional information here in as much as detail as you can

```true
Angular CLI: 18.0.5
Node: 20.12.2
Package Manager: npm 10.5.2
OS: win32 x64
Angular: 18.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.5
@angular-devkit/build-angular   18.0.5
@angular-devkit/core            18.0.5
@angular-devkit/schematics      18.0.5
@angular/cli                    18.0.5
@schematics/angular             18.0.5
```

**Comment by davidnaumann-bastian** [comment]
https://v17.angular.io/guide/content-projection ,here is the v17 angular documentation as example for the missing examples that don't currently exist in angular.dev

**Comment by JeanMeche** [comment]
This is an component declaration problem. It is assumed that readers have basic understanding of how components can by used by others. 

I'll close this.

**Comment by JeanMeche** [comment]
I'm not sure to understand which part of the v17 docs is less ambiguous on the issue you're describing.
