### ISSUE TITLE
'Must never be called in production mode'

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angular#56558]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

We log errors our users are getting. Since a few weeks (+- around the time of upgrading to ng18) a new error has popped up.
It happens approximately 10 times per day on a userbase of +-8000 users per day.

We cannot reproduce it ourselves, but it seems to be a combination of lazy loading/defer loading + loss of internet connection.

Error: "ASSERTION ERROR: Must never be called in production mode"
stack trace: vu@https://www.acro-companion.com/chunk-HPX2AJVJ.js:4:392dv@https://www.acro-companion.com/chunk-HPX2AJVJ.js:7:40140@https://www.acro-companion.com/chunk-HPX2AJVJ.js:7:90570onInvoke@https://www.acro-companion.com/chunk-HPX2AJVJ.js:7:64426run@https://www.acro-companion.com/polyfills-XYXPKSL4.js:1:1733@https://www.acro-companion.com/polyfills-XYXPKSL4.js:2:556onInvokeTask@https://www.acro-companion.com/chunk-HPX2AJVJ.js:7:64246runTask@https://www.acro-companion.com/polyfills-XYXPKSL4.js:1:2348x@https://www.acro-companion.com/polyfills-XYXPKSL4.js:1:9079promiseReactionJob@[native code]

interesting is that +-95% is on iPhone, so possibly something to do with loading of javascript during minimized?

If I search through node modules this error seems to originate from angular core:
![image](https://github.com/angular/angular/assets/1098243/4be3c00d-5f4d-414a-a919-a8217968eac3)

our configuration for production is nothing special:
![image](https://github.com/angular/angular/assets/1098243/b6af2f5e-10a6-4084-94b9-d3b3e160b280)
![image](https://github.com/angular/angular/assets/1098243/c69a5ba7-cc4e-4799-9a1b-77a4b2ca22e9)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.4
Node: 20.13.1
Package Manager: npm 10.6.0
OS: win32 x64

Angular: 18.0.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... google-maps, language-service, material
... material-date-fns-adapter, platform-browser
... platform-browser-dynamic, router, service-worker
... youtube-player

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.4
@angular-devkit/build-angular   18.0.4
@angular-devkit/core            18.0.4
@angular-devkit/schematics      18.0.4
@angular/cli                    18.0.4
@angular/fire                   18.0.1
@schematics/angular             18.0.4
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

**Comment by JeanMeche** [comment]
These errors were added in v18 you're right, but they are guarded by a devMode only flag. 

Are you doing anything specific with your build ? The flag should be set to false and the code stripped when optimizations are enabled.

**Comment by LanderBeeuwsaert** [comment]
@JeanMeche ok thank you that confirms my suspicion. No I can't really think of us doing something unexpected/specific. I would be able to send you package.json and angular.json and the base modules easily in a zip if that could help. However a reproduction will be considerably more involved (it's a huge project so stripping it down to the core will take time).

**Comment by LanderBeeuwsaert** [comment]
We use angularFire which has the tendency to use some internals of Angular

**Comment by JeanMeche** [comment]
Oh actually it looks like the framework is calling code that it should in production. 

https://github.com/angular/angular/blob/49b2e65bfb097b25da09870ca8a07650812e3d68/packages/core/src/defer/instructions.ts#L926-L936

The function at like `getTemplateLocationDetails()` should be devonly but is called when a defer loading fails. 
This could explain why you mostly have this issue on phones, there are more inclined to network errors.

**Comment by LanderBeeuwsaert** [comment]
@JeanMeche jep, great! Glad it isn't on our side doing something stupid ;-)

**Comment by JeanMeche** [comment]
I've open #56559 to prevent the error from happening. 
Also one suggestion, this code is called when your defer block as no `@error` block. 
You should probably add one for your users but it will also act as a workaround this bug ;)

**Comment by LanderBeeuwsaert** [comment]
Hehe very fair point. Thanks for the help!
