### ISSUE TITLE
Question: Why ist redirectTo in the router Definition an array?

### ISSUE THREAD

**Issue by fr3dm4n** [angular/angular#5655]
Hey together,
I am playing with Typescript, Angular2 (alpha 48) and Polymer. Referring to the [TypeDefs](https://github.com/angular/angular/blob/master/modules/angular2/src/router/route_definition.ts#L19), `redirectTo` should be an array.

This code works well:

~~~ js
@RouteConfig([
    {path: '/', redirectTo: '/gmap'},
    {path: '/gmap', as: 'Gmap', component: MapComponent},
    {path: '/chuck', as: 'Chuck', component: ChuckComponent},
])
~~~

But with this the router stopped working without any error message

~~~ js
@RouteConfig([
    {path: '/', redirectTo: ['/gmap']},
    {path: '/gmap', as: 'Gmap', component: MapComponent},
    {path: '/chuck', as: 'Chuck', component: ChuckComponent},
])
~~~

Did I got something wrong or is it a slight mistake?

**Comment by ericmartinezr** [comment]
Check https://github.com/angular/angular/issues/4170

**Comment by wardbell** [comment]
To be specific, the strings in a *link parameters array* **always refer to route names**, not paths, even though they *look like* paths when we prepend slashes and dots.

You may also find that the leading `/` on `/Gmap` is unnecessary; I'll bet `['Gmap']` works fine.  I prefer to omit the slashes and dots unless I really need them to disambiguate routes with the same route name.

**Comment by zoechi** [comment]
@wardbell Does this mean the array elements are a route and sub-routes like `redirectTo: ['Gmap', 'SubRoute1', 'SubRoute2']`?

**Comment by wardbell** [comment]
Yes. Your example describes a 3-deep link with no route parameter objects meaning none of the three routes (parent, child, grandchild] require router parameters.

See the discussion of the [link parameters array](https://angular.io/docs/ts/latest/guide/router.html#!#link-parameters-array)

**Comment by zoechi** [comment]
@wardbell thanks a lot :)

**Comment by wardbell** [comment]
@fr3dm4n If we have answered your question, would you please close this issue?

**Comment by fr3dm4n** [comment]
@wardbell I was waiting to try it with beta.0 cause in alpha it didn't work for me.
All is fine now, thx for your time and explanation
