### ISSUE TITLE
Allow transform functions into input signals

### ISSUE THREAD

**Issue by MGX-CODING** [angular/angular#56560]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Allow the use of transform functions into input signals

### Proposed solution

```typescript
import { Directive, booleanAttribute, input } from '@angular/core';

@Directive({ selector: 'input' } })
export class InputDirective {
  public required = input<boolean>(false, { transform: booleanAttribute });
}

```

### Alternatives considered

Manually making it for now

**Comment by JeanMeche** [comment]
This already works with either : 

* `input(false, { transform: booleanAttribute });`
* `input<boolean, unkown>(false, { transform: booleanAttribute });`
