### ISSUE TITLE
API pages examples with decorators are cut

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular#56569]
### Describe the problem that you experienced

When there is a decorator in an api doc example (ex https://angular.dev/api/core/afterNextRender?tab=usage-notes), the example is cut at the level of the decorators. 

The root cause is upstream as Typescript still considers lines starting with `@` in code blocks to be a new JsDoc tag. 

* See microsoft/typescript#58992

### Enter the URL of the topic with the problem

https://angular.dev/api/core/afterNextRender?tab=usage-notes

**Comment by JelleBruisten** [comment]
Seems like clicking on another tab like `api` then coming back to `usage-notes` fixes it, just not when initially going to that tab

**Comment by JeanMeche** [comment]
This is a separate issue, that should taken care by angular/components#29220

**Comment by JeanMeche** [comment]
The fix is already visible here : https://next.angular.dev/api/router/Data

**Comment by JeanMeche** [comment]
We actually had a work around in place but didn't handle the view queries decorator. 

Fix will land with #56794
