### ISSUE TITLE
this URL of tutorial creating your first Angular APP

### ISSUE THREAD

**Issue by ph360** [angular/angular#56564]
### Describe the problem that you experienced

This URL https://angular.dev/assets/tutorials/common show Page Not Found.   I believe that this resource is important for do the practice

### Enter the URL of the topic with the problem

https://angular.dev/assets/tutorials/common

### Describe what you were looking for in the documentation

the develop the example de create an interface

### Describe the actions that led you to experience the problem

When validate this url show Page Not Found

### Describe what you want to experience that would fix the problem

I may to have url that show me the resources for develop the practice

### Add a screenshot if that helps illustrate the problem

![Captura de pantalla 2024-06-23 210758](https://github.com/angular/angular/assets/163641295/9e18ebef-0495-4282-b750-4caba6add29f)

### If this problem caused an exception or error, please paste it here

```true
Page Not Found
```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Chrome Versión 126.0.6478.63 (Build oficial) (64 bits)
```

**Comment by geromegrignon** [comment]
Even if the URL is missing the last part to target the image, the image itself is not exposed by angular.dev.

It was exposed by angular.io and the URL changed with #52536 but the image itself has not been moved from aio to adev.

### Solution

- grab the image from an old version of the repo were it still existed
- create a **tutorials/common** folder in `adev/src/assets` and place the image there.

**Comment by JeanMeche** [comment]
Let's continue tracking this issue in https://github.com/angular/angular/issues/52794

**Comment by ph360** [comment]
thank you very much
