### ISSUE TITLE
Angular 17 SSR host

### ISSUE THREAD

**Issue by Dev-Mohit-1220** [angular/angular#56585]
### Describe the problem that you experienced

I am using **angular 17 SSR** app, in that I am **using meta tags, in local it's working.**
But when I am **hosting app in the vercel it's not working**.

What path I actually have to give, bit confusion in that.

### Describe what you were looking for in the documentation

Looking for SSR host documentation, So

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).

**Comment by Dev-Mohit-1220** [comment]
Can you share proper documentation, how to host Angular 17 SSR app

**Comment by Dev-Mohit-1220** [comment]
my repo: https://github.com/Dev-Mohit-1220/Angular18_SSR
my hosted link: https://angular18-ssr.vercel.app/

In my this app SSR og tag not working on live environment.
