### ISSUE TITLE
RFC: rename exportAs: 'form' to exportAs: 'ngForm'

### ISSUE THREAD

**Issue by vicb** [angular/angular#5658]
Most angular core directives start with the "ng" prefix to avoid name collision.

What about renaming "form" to "ngForm" for the same reason.

/cc @vsavkin

**Comment by user414** [comment]
I understand that we might not have time to update the angular.io site immediately, like in this case the hero form here

https://angular.io/docs/ts/latest/guide/forms.html

where it reference the old "form" but can we maybe tie them together with this in someway to keep track of them? On a side note beside looking at all the commits is there a way to find out non backward compatible commit such has this one? Could we perhaps add a label on the issue of commits so we could somehow easily extract a list of those for each alpha release? Thanks.

**Comment by pkozlowski-opensource** [comment]
> On a side note beside looking at all the commits is there a way to find out non backward compatible commit such has this one? 

See https://github.com/angular/angular/blob/master/CHANGELOG.md and pay attention to the "Breaking changes" section

**Comment by user414** [comment]
Great thanks, exactly what I was looking for, was in a too obvious place:-)

**Comment by user414** [comment]
So is the subsequent task to update the angular.io somewhere else as well and I can't see it?

**Comment by user414** [comment]
If it is someone can just mark the one I opened as duplicate, thanks.
