### ISSUE TITLE
Effect is triggering all the signals to notify

### ISSUE THREAD

**Issue by AlexandraMadalina** [angular/angular#56593]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Hello,

It seems like an effect can trigger signals to notify.

In the example I have an effect that is watching  a signal(`id`) which is initialised with a value and it never changes, and makes a call to `resetFilters`.  But whenever `emitFilterChanges` is triggered the `id` notifies, thus `resetFilters` is called again.

Can someone help me understand what is happening?
```
@Component({
  selector: 'app-root',
  standalone: true,
  template: `

    <button  (click)="onClick()">
        click me 
    </button>
  `,
})
export class App {

  activeFilter = signal<string>('');
  id = signal('123');

  onClick() {
    this.activeFilter.set('filter active');
    this.emitFilterChanges();
  }

  resetFilters() {
    this.activeFilter.set('filter reset');
    const activeFilter = this.activeFilter();
    console.log(activeFilter);
  }

  emitFilterChanges() {
    const activeFilter = this.activeFilter();

    console.log('emitFilterChanges', activeFilter);
  }
  constructor() {
    effect(
      () => {
        if (this.id()) {
          this.resetFilters();
        }
      },
      { allowSignalWrites: true }
    );
  }
}

```
###  Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-jx9d1b?file=src%2Fmain.ts

**Comment by JeanMeche** [comment]
This is works as defined, if you need to not track some signals have a look at [`untracked`](https://angular.dev/guide/signals#reading-without-tracking-dependencies)

**Comment by AlexandraMadalina** [comment]
thank you
