### ISSUE TITLE
Illegal Invocation / Infinite Digest on deep $watch of a property is a DOM or jQuery object.

### ISSUE THREAD

**Issue by iamchairs** [angular/angular#566]
Example JSBin:

http://jsbin.com/favorinava/6/edit

Steps to reproduce:

* Create a scope.
* Set a property on the scope to a DOM element.
* Create a $watch on the scope and set the objectEquality property to true.

```
angular.module('app', [])
  .controller('SomeCtrl', function($scope) {
    $scope.data = {
      test: document.body
    };

    // No problem
    $scope.$watch('data', function(newVal) {}, false);
  
    // Problem
    $scope.$watch('data', function(newVal) {}, true);
  })
```

**Comment by pkozlowski-opensource** [comment]
Wrong repo: https://github.com/angular/angular.js

**Comment by iamchairs** [comment]
Moved: https://github.com/angular/angular.js/issues/11001
