### ISSUE TITLE
Invalid name: "@reactivex/rxjs"

### ISSUE THREAD

**Issue by brendonco** [angular/angular#5666]
When execute "npm i angular2@2.0.0-alpha.44 systemjs@0.19.2 --save --save-exact", I got below errors.

using these steps to install Angular2
https://angular.io/docs/js/latest/quickstart.html

```
npm i angular2@2.0.0-alpha.44 systemjs@0.19.2 --save --save-exact
npm WARN engine @reactivex/rxjs@5.0.0-alpha.4: wanted: {"npm":"~2.0.0"} (current: {"node":"5.0.0","npm":"3.3.6"})
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "angular2@2.0.0-alpha.44" "systemjs@0.19.2" "--save" "--save-exact"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! Invalid name: "@reactivex/rxjs"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by jeffbcross** [comment]
@robwormald is working on updating the changelog with breaking changes that slipped past our script.

**Comment by robwormald** [comment]
this is usually an issue with an older version of NPM, or using a third party npm registry. @brendonco can you do `npm -v` and check the version you're using, and compare it to https://github.com/angular/angular/blob/master/DEVELOPER.md#prerequisite-software

**Comment by brendonco** [comment]
Let me check later the npm version I'm using.

**Comment by robwormald** [comment]
@brendonco this is out of date in beta0 - the path/ install is now just `rxjs`

**Comment by brendonco** [comment]
@robwormald  I tried in a new machine, install node.  Seems to work now.
