### ISSUE TITLE
ng.Observable.fromArray not present in alpha48

### ISSUE THREAD

**Issue by lburkovsky** [angular/angular#5667]
following code doesn't work in 48

    import * as ng from 'angular2/angular2';
    ng.Observable.fromArray([15]).delay(800)

**Comment by ericmartinezr** [comment]
In alpha 48 you shouldn't import Observable from angular2, but from rxjs/Observable. Related https://github.com/angular/angular/issues/5632

**Comment by jeffbcross** [comment]
@robwormald is working on updating the changelog with breaking changes that slipped past our script.

**Comment by jeffbcross** [comment]
Closed via ad481694e1c4d8ac48fe3d11970247ca16088eed
