### ISSUE TITLE
Browser back button does not work when page is refreshed several times.

### ISSUE THREAD

**Issue by machi1990** [angular/angular#5670]
I'm using the angular2 router and I have a strange behaviour when I refresh my page. Suppose you are located on a certain url ( xxxx, having yyyy as the previous page), ion normal case, going back to yyyy requires just one click of the back button. 
Strangely, when you refresh the xxxx page "N" times, you would have then to clikc the back button "N+1" times to get back to yyyy page. 

I am using the HashLocationStrategy for my route configuration. I would say the behaviour I got is to be expected as the the implementation of the class, on line 87, pushes the state on each refresh. Well, now is there any workaround I need to implement, so that no matter how many times the user refreshes the page under url xxxx, he can always go back to yyyy page with a single click of the back button.

Thanks.

**Comment by vangorra** [comment]
+1 I've noticed the same behavior.

I can navigate my app normally. While on a page, if I refresh, that page is still loaded. Pressing back however appears to load the page I'm currently on. Pressing back again actually goes back. The number of times I have to press back in a row is equal to the number of times you press refresh in a row.

Very odd.

**Comment by zoechi** [comment]
I think #6069 is what should fix this.

**Comment by pkozlowski-opensource** [comment]
I believe that this is fixed in master.
