### ISSUE TITLE
Alpha 47/48 Custom Elements CSS Style

### ISSUE THREAD

**Issue by tbragaf** [angular/angular#5671]
Hi all!

After upgrading to the referred angular2 versions, I realised my css had an odd behaviour.
Now, my custom elements (components) also have line-height?
The body has line-height: 1.5, but with alpha-46 it didn't affect custom elements.

Can anyone confirm this?

Best regards,
tbragaf

**Comment by vicb** [comment]
Hard to say what's going on without a proper repro case. Could you attach a plunker and describe the expected vs actual behavior ?

**Comment by tbragaf** [comment]
@vicb This is no longer an issue in alpha 49/50, so I'm closing this.

Thank you!

**Comment by vicb** [comment]
Thanks for reporting
