### ISSUE TITLE
fix(changelog): include refactor commits

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#5672]
The Changelog seems to omit any refactor commits, even those with breaking changes. For example: https://github.com/angular/angular/commit/5514dc19d9779fb6b0d7bbae8268dc21dd1dde39

^^^
That commit was not included

CC @robwormald

**Comment by pkozlowski-opensource** [comment]
It is kind of reasonable since refactor shouldn't have impact on the functionality as seen by an user (in our case those are framework users). Perhaps commit should reflect _why_ we even doing this change, from a user point of view?

**Comment by jeffbcross** [comment]
> It is kind of reasonable since refactor shouldn't have impact on the functionality as seen by an user (in our case those are framework users).

In angular reality though, refactors almost always have some kind of user-impacting change, breaking or not. When I, and I think most other contributors, think of "fix", I think of it as a solution to an obvious bug. When I think of refactor, it's usually to either improve performance or developer experience. Like the lifecycle hook refactor wasn't in response to a "bug", but a potential problem with the current design. And the recent `Observable` refactor was mostly a performance improvement (byte reduction). Same with the upcoming kebab-case refactor.

> Perhaps commit should reflect why we even doing this change

Agreed

**Comment by vicb** [comment]
Concrete example: https://github.com/angular/angular/pull/5709 should really be a `refactor` but as it is also a breaking change, I've labelled it as fix.

**Comment by jeffbcross** [comment]
I think probably a better solution to this problem would be to include any commit that is a breaking change.

**Comment by pkozlowski-opensource** [comment]
> I think probably a better solution to this problem would be to include any commit that is a breaking change.

:+1:

**Comment by jeffbcross** [comment]
@pkozlowski-opensource @vicb a PR is ready https://github.com/angular/angular/pull/5762

I considered changing the angular preset upstream, in the conventional-changelog repo. Not sure if this problem is general enough that others would want it though.

@ajoslin do you think it'd be worth adding logic to the angular preset in conventional-changelog that would include any commit that contains a `BREAKING CHANGE` note, regardless of its type?

**Comment by ajoslin** [comment]
That sounds reasonable. @stevemao is currently maintaining conventional-changelog. Steve, what do you think?

**Comment by stevemao** [comment]
Sounds good to me.

**Comment by laco0416** [comment]
Still in beta.16, many breaking changes with refactor commit are out. 

e.g.

- https://github.com/angular/angular/commit/b602bd8c835ef33f9d0c44e2595558471462fec5
- https://github.com/angular/angular/commit/9092ac79d49edee5e58cf26d890209766885753f

It's not good for the users and community. 
Any update on this? 

@jeffbcross 
cc/ @mhevery @IgorMinar

**Comment by stevemao** [comment]
This is already fixed in conventional-changelog a few versions back. Unfortunately no one is looking at #3455 yet.

**Comment by StephenFluin** [comment]
@jeffbcross Still seems to ignore the refactor breaking changes as of me generating the changelog this morning. I can show you what happens if that would help

**Comment by jeffbcross** [comment]
Impossible!

**Comment by jeffbcross** [comment]
Re-closing since the commit in question didn't actually have `BREAKING CHANGE:` included in the message. 40b907a657ec6aeb72d0661707a7842a867ac572
