### ISSUE TITLE
Question: Is there a way to attach a Validator directive via a dynamically computed selector

### ISSUE THREAD

**Issue by frederikschubert** [angular/angular#5673]
I have a couple of Validators that I am adding to `PLATFORM_DIRECTIVES` in order to have them available in all templates. Now when I want to implement a custom input component that has a control attached to it, the validators are only set if their selector is a constant. This this plunk for an example:
http://plnkr.co/edit/20Ssi7jJGcTZMZIMbESc?p=streamer
The problem is that the validator is only correctly applied when I set a fixed input type property.
What I want is for both input fields to be validated the same way.

**Comment by zoechi** [comment]
dup of dup of #6970

**Comment by pkozlowski-opensource** [comment]
dup of #6970
