### ISSUE TITLE
Broken Url to Simple Change Page 

### ISSUE THREAD

**Issue by Nurudeen21** [angular/angular#56734]
### Describe the problem that you experienced

clicking on the simple change reference link on the page below navigate to a not found instead of the appropriate page due to mistake in the redirected url (https://angular.dev/api/core/SimpleChange%200

### Enter the URL of the topic with the problem

https://angular.dev/api/core/SimpleChanges

**Comment by JeanMeche** [comment]
This has already been fixed cf https://next.angular.dev/api/core/SimpleChanges 
And is waiting for the 18.1 release to be deployed.
