### ISSUE TITLE
Router: For diagnostics, how to retrieve the currently active route?

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#5674]
In Angular 1.0 Dart, it was possible to inject the `Router` and retrieve the `activePath`:

```dart
FooComponent(Router router) {
  List<String> activePath = router.activePath; // Example: ['contact', 'overview'].
}
```

This allowed it to be added to diagnostics/logs or as part of a unique key for a component. I see there is a private `_currentInstruction` in Angular2, but no public interface or something similar to above.

**Comment by goodfield** [comment]
@matanlurey you can inject the router and subscribe to changes:
```
@Inject(Router)
export class NavigationComponent {
    private _currentView: string;

    constructor(private _router: Router) {
        this._router.subscribe( (view) => {
            this._currentView = view;
        });
    }
}
```

**Comment by matanlurey** [comment]
That only works if the route changes. How do I get the current view without subscribing?

**Comment by brandonroberts** [comment]
@matanlurey you could use the Location to get the current path

```js
@Inject(Router)
export class NavigationComponent {
    private _path: string;

    constructor(location: Location) {
        this._path = location.path();
    }
}
```

**Comment by matanlurey** [comment]
Settled as good enough. Thanks all.
