### ISSUE TITLE
Refused to apply the inline style because it violates the following CSP nonce-xxx in platform-browser.mjs

### ISSUE THREAD

**Issue by joaosemrif** [angular/angular#56749]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

Yes

### Description

tyle-src-attr |   | platform-browser.mjs:590 | bloqueado
style-src-attr |   | ng-icons-core.mjs:433 | bloqueado

![image](https://github.com/angular/angular/assets/45321218/28ceb8f1-cd2d-4a8e-9c9b-b138c5ce44b6)

**Comment by thePunderWoman** [comment]
@joaosemrif Can you provide us with a minimal reproduction? Without that, there's nothing actionable for us.

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back with a reproduction scenario.
