### ISSUE TITLE
No indentation or syntax highlighting in control flow examples

### ISSUE THREAD

**Issue by calebegg** [angular/angular#56745]
### Describe the problem that you experienced

There's no indentation or syntax highlighting

![image](https://github.com/angular/angular/assets/782920/e2a93523-809f-4894-8d4f-db7442ea9650)

### Enter the URL of the topic with the problem

https://angular.dev/guide/templates/control-flow

**Comment by atscott** [comment]
I created https://github.com/angular/angular/pull/56748 to fix the indentation. Syntax highlighting issues are tracked by https://github.com/angular/angular/issues/52654

**Comment by calebegg** [comment]
Thanks. For some reason I can't comment on that PR but line 11 also needs a two space indent

**Comment by calebegg** [comment]
Also, I'm a little confused by the syntax highlighting -- other pages have it, why doesn't this one?

**Comment by calebegg** [comment]
Oh disregard, I understand the syntax highlighting issue now
