### ISSUE TITLE
pollyfill.io vulnerability issue affect any angular applications ? is there any pollyfill configuration changes required in angular.json?

### ISSUE THREAD

**Issue by nagendra-cn** [angular/angular#56760]
### Is this a bug report or a feature request?

- [x] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

We are using pollyfill configuration in angular.json file with just zone.js as below. 

**"pollyfills":["zone.js"]**

1. Currently polyfill.io is having **vulnerability** issues, do we need to remove the polyfill configurations in angular.json ? or it's not required to make any changes in pollyfill configuration. (Our application support web only)

2. If we try to remove the polyfill configuration in angular.json file then we will get the zone.js required error.
 **(Angular version : 16)**

3. In case if we need to remove the pollyfill configuration in angular.json file to overcome vulnerability issue, then what's the solution to fix the zone.js required error ?

**Comment by JoostK** [comment]
I suppose you're referring to polyfill.io as a CDN service, per https://www.sonatype.com/blog/polyfill.io-supply-chain-attack-hits-100000-websites-all-you-need-to-know. Angular's polyfill section is unrelated to this service, as is zone.js

**Comment by nagendra-cn** [comment]
Thanks for the confirmation @JoostK

**Comment by LizethMdz** [comment]
How could I solve this vulnerability or to find out my project has it?
