### ISSUE TITLE
Safari problem

### ISSUE THREAD

**Issue by DinnerPlain** [angular/angular#56775]
### Which @angular/* package(s) are the source of the bug?

platform-browser-dynamic, platform-browser

### Is this a regression?

No

### Description

My ski club the Australian Alpine Club use a booking system built on the Angular framework.
Everything works well except one aspect of the booking service where in all browsers EXCEPT Apple Safari, the room numbers, which should appear on the left hand side of the screen, don't show up as in the attached PDF document.
[1 DinnerPlain Booking page - no room numbers.pdf](https://github.com/user-attachments/files/16044617/1.DinnerPlain.Booking.page.-.no.room.numbers.pdf)

The second pdf shows a screen shot using Firefox on a MAC with the room numbers appearing correctly.
HELP - we have lots of members who do use Safari - the latest version and can't easily access the room numbers without a bit of fuss.

[1 DinnerPlain Booking page - WITH room numbers.pdf](https://github.com/user-attachments/files/16044645/1.DinnerPlain.Booking.page.-.WITH.room.numbers.pdf)

### Anything else?

All help appreciated.
Your Browser support page states that Angular DOES support Safari - but my experience is contrary to that statement.
Regards
David Perry
Dinner Plain Committee Chair

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
