### ISSUE TITLE
Proposal to Angular Quickstart: Add distance information to hyperlinks

### ISSUE THREAD

**Issue by SetTrend** [angular/angular#5677]
From my point of view the Angular documentation is very well done.

Yet, when I read it and hit a sentence containing a [Hyperlink](https://angular.io/docs/ts/latest/quickstart.html#final-structure) (if you follow this Hyperlink, scroll three lines up to see the actual Hyperlink in the documentation), I'm confused about where the information will be found. I find myself asking: Will it be found in another file or will it be found within this current document? Did I already read the referenced information or will I get to it next?

Many times I find myself Control-clicking a Hyperlink for it to open in a new tab so I won't forget to read its content in time. Then, later, I see that the new tab just displays the next paragraph of the same document I just read because the Hyperlink was no more but a fragment identifier.

To avoid confusion I suggest to have "in-document" hyperlinks' text being followed by the term "below" or "above", resp. This will make clear whether a Hyperlink is rather comfort than necessary to reveal information. And it'll make clear whether the hyperlinked information has already been read (when the information is above the current hyperlink on the page) or whether the information will be revealed next (when the information is below the current hyperlink on the page).

My concern is also true for cases when the document is supposed to be printed for being read without hardware, or for readers for the blind.

My suggestion will help to identify whether the hyperlinked information will be revealed within the current document or not, whether it has already been read and whether action needs to be taken to read the referenced information.

Here are three examples (bold face added only for the sake of clarity):

 * This is explained [in another document](#).
 * This is explained [in detail](#) **below**.
 * This is explained [in detail](#) **above**.

**Comment by PascalPrecht** [comment]
Hey @SetTrend would you mind opening this issue at http://github.com/angular/angular.io? I think this is where it belongs. Despite that I think it is a valid point!

**Comment by SetTrend** [comment]
Oops ... Sure, of course. Sorry for using the wrong target here :blush:

**Comment by PascalPrecht** [comment]
No probs at all, thanks for reporting this!
