### ISSUE TITLE
Lazy Loading in Angular V18, Page Not Found Error Displayed.

### ISSUE THREAD

**Issue by Jugalsingh026** [angular/angular#56777]
### Describe the problem that you experienced

Hello Team,
My Name is Jugal pratap Singh, I am trying to read all docs related to Angular v17.
I am reading LazyLoading Concepts using this link https://v17.angular.io/guide/lazy-loading-ngmodules.
On the header section there is a button which says , this page does not longer updated. to check latest docs please click on the 
given link.
So as I Clicked to read the latest doc info about LazyLoading, there is an error Page Not Found Displayed.
Please check, and Update if the latest doc related to lazyloading.asap
Thanks
![s1](https://github.com/angular/angular/assets/140891611/df4f0ff4-4477-4b46-96b2-240e38ba4970)
![S2](https://github.com/angular/angular/assets/140891611/1fc85350-7fd0-4aa1-b581-1e59c86c4a84)

### Enter the URL of the topic with the problem

https://angular.dev/guide/lazy-loading-ngmodules

### Describe what you were looking for in the documentation

Looking for Lazy Loading Concepts.

### Describe the actions that led you to experience the problem

Page Not Found

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/140891611/fbc2a59a-0435-4743-96ae-3b6765e576bd)

**Comment by JeanMeche** [comment]
The page you're looking for is https://angular.dev/guide/ngmodules/lazy-loading and #56778 should fix that.
