### ISSUE TITLE
Clicking on a link does not change content

### ISSUE THREAD

**Issue by yosefHesham** [angular/angular#56780]
### Describe the problem that you experienced

I was reading in guide (components section), when i click on 'Accepting Data with input properties, content is not changed and the nav menu hides'

### Enter the URL of the topic with the problem

https://angular.dev/guide/components

### Describe what you were looking for in the documentation

I wanted to read Accepting data with input properties section where it found in Components subRoute.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/45171920/b1c15c0e-93b3-4623-ae38-695a9a9c5256)

when i click on Accepting data with input properties, content remains the same.

### Provide any additional information here in as much as detail as you can

```true
I actually wanted to solve the issue myself and create a PR for this, but its my first angular-day
Still Learning :) btw the docs are awesome.
```

**Comment by JeanMeche** [comment]
This works fine, you likely had a connection issue when loading the page.

**Comment by yosefHesham** [comment]
@JeanMeche  click on components -> Accepting data with input properties.
The content remains the same.
ex: My current path is on: components/output()function.
if i click on Accepting data with input properties, it does not work.
however, all other links work pretty well.

**Comment by JeanMeche** [comment]
What happens if you click access https://angular.dev/guide/components/inputs ?

**Comment by yosefHesham** [comment]
@JeanMeche  it works now, i was saying its not a connection issue cuz all the other links were working pretty well except for that one.
@JeanMeche
