### ISSUE TITLE
Make HostAttributeToken more modern like new input/output

### ISSUE THREAD

**Issue by grizlizli** [angular/angular#56788]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

While I was working with the new inputs & outputs, I have encountered a small inconsistency when defining input and Host Attribute Token.

Consider this:
`label = inject(new HostAttributeToken('label'));`
`options = input<any[]>();`

HostAttributeToken is kind OOP way and the input is more functional way.

Why not make it consistent and use functional way for both input and HostAttributeToken?

### Proposed solution

Given the function declaration for the inject and HostAttributeToken, I have come up with this solution.

```
export function hostAttributeToken(attributeName: string, optional?: boolean): string | null {
  if (optional === true) {
    return inject(new HostAttributeToken(attributeName), { optional }) as string | null;
  }
  else if (optional === false) {
    return inject(new HostAttributeToken(attributeName), { optional }) as string;
  }
  else {
    return inject(new HostAttributeToken(attributeName)) as string;
  }
}
```

Using it will be more natural in my opinion.
`label = hostAttributeToken('label');`

This is the type definition.
```
**
 * @param token A token that represents a static attribute on the host node that should be injected.
 * @returns Value of the attribute if it exists.
 * @throws If called outside of a supported context or the attribute does not exist.
 *
 * @publicApi
 */
export declare function inject(token: HostAttributeToken): string;

/**
 * @param token A token that represents a static attribute on the host node that should be injected.
 * @returns Value of the attribute if it exists, otherwise `null`.
 * @throws If called outside of a supported context.
 *
 * @publicApi
 */
export declare function inject(token: HostAttributeToken, options: {
    optional: true;
}): string | null;

/**
 * @param token A token that represents a static attribute on the host node that should be injected.
 * @returns Value of the attribute if it exists.
 * @throws If called outside of a supported context or the attribute does not exist.
 *
 * @publicApi
 */
export declare function inject(token: HostAttributeToken, options: {
    optional: false;
}): string;
```

### Alternatives considered

Well, the existing approach. :)

**Comment by JoostK** [comment]
This was discussed during the design of `HostAttributeToken`. The consensus was that we want to avoid having a multitude of `inject` variants, as having a single pattern makes it clear that this is about injecting a token value.

Having the proposed function does make sense _if_ static attributes are a higher-level thing, similar to inputs. Please see https://github.com/angular/angular/issues/56504#issuecomment-2180112447 for a recent comment on our thoughts here. From that perspective we do see a gap in Angular's current support for attributes/static values, which is being tracked in #14033.

**Comment by grizlizli** [comment]
Thank you for your detailed eloboration. 

Wish you a good day!
