### ISSUE TITLE
Content of a tab in adev-reference-page is hidden on reload

### ISSUE THREAD

**Issue by lukasmatta** [angular/angular#56786]
### Describe the problem that you experienced

When you directly visit tab other than `api`, its content is first rendered but then it is hidden. E.g. https://angular.dev/api/forms/AbstractControl?tab=description

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Version 126.0.6478.127 (Official Build) (arm64)
```

**Comment by JeanMeche** [comment]
Hi, this is a material bug, there is a pending PR angular/components#29220
