### ISSUE TITLE
toObservable doesn't make input signals synchronous

### ISSUE THREAD

**Issue by conblem** [angular/angular#56797]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hello Everybody

I have some code which uses input signals and then turns them into observables and back again.
The code below is a minimal repro of the issue im facing and can also be accesed via the CodeSandbox.
Using toObservable on a required input signal does not make it a synchronous observable it seems.
![Code in question](https://github.com/angular/components/assets/19853857/59a04293-9845-4979-8d36-fcf4e1c4cd4d)

The best case for me would be if this also works, but that seems even less probable, as inputs get assigned onInit.
Maybe this is just the problem of having decided signals should have a synchronous value, which does not work for inputs.
Hence the "hack" of having them throw exceptions when called e.g. in constructors or in my case.
![My dream](https://github.com/angular/components/assets/19853857/3872a950-58df-40b4-a403-04d849609bfd)

### Reproduction

CodeSandbox link: [https://codesandbox.io/p/devbox/requiresyncerrorrepro-wp34cy](https://codesandbox.io/p/devbox/requiresyncerrorrepro-wp34cy)
Steps to reproduce:
1. Open link
2. Open console

### Expected Behavior

No error in the console

### Actual Behavior

![error](https://github.com/angular/components/assets/19853857/94ca441d-7faa-4228-aff8-8f422c9f5e1a)

### Environment

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.3.0
Node: 20.9.0
Package Manager: npm 9.8.1
OS: linux x64

Angular: 17.3.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.0
@angular-devkit/build-angular   17.3.0
@angular-devkit/core            17.3.0
@angular-devkit/schematics      17.3.0
@schematics/angular             17.3.0
rxjs                            7.8.1
typescript                      5.4.2
zone.js                         0.14.4

**Comment by JeanMeche** [comment]
This works as designed. 
`toObservable` relies on an effect to be notified on signal value changes. 

In the context of components, the effect scheduling is tied to Change Detection. 
To prevent forbidden read of a signal (like required signals), effect will only  run when the component is init. 

Therefore the effect cannot be synchronous and the toObservable cannot be sync either. 
However, since `toObservable` isn't lazy, it is possible that if the subscription happens later, the subscription might recieve a value synchronously. 

https://angular.dev/guide/signals/rxjs-interop#timing-of-toobservable
