### ISSUE TITLE
Navigation problem 

### ISSUE THREAD

**Issue by marioriguera** [angular/angular#56792]
### Describe the problem that you experienced

I clicked on 'See **RoutercreateUrlTree** for more information..' 
Origin url: 'https://angular.dev/api/router/RouterLink?tab=description' 
Destination url: 'https://angular.dev/api/router/RoutercreateUrlTree'

### Enter the URL of the topic with the problem

https://angular.dev/api/router/RoutercreateUrlTree

### Describe what you were looking for in the documentation

The typical not found page appears:

Page Not Found 🙃
[edit](https://github.com/angular/angular/edit/main/adev/src/content/error.md)
If you think this is a mistake, please [open an issue](https://github.com/angular/angular/issues/new?template=3-docs-bug.yaml) so we can fix it.

**Comment by JeanMeche** [comment]
Hi, this has already been fixed and is pending deployement (with 18.1 release next week). 

Please see https://next.angular.dev/api/router/Router#createUrlTree
