### ISSUE TITLE
https://v17.angular.io/guide/signal-inputs routes to 404 - https://angular.dev/guide/signal-inputs

### ISSUE THREAD

**Issue by mlau-anet** [angular/angular#56826]
### Describe the problem that you experienced

old docs had broken link to new docs.

### Enter the URL of the topic with the problem

https://v17.angular.io/guide/signal-inputs

### Describe what you were looking for in the documentation

whether signals are still in dev preview

### Describe the actions that led you to experience the problem

searched google to see status of signals in dev preview, got linked to old docs

### Describe what you want to experience that would fix the problem

not to have broken links

**Comment by JeanMeche** [comment]
Hi, this already beeing addressed by #56825.
