### ISSUE TITLE
Router bindToComponentInputs/withComponentInputBinding for route data as well

### ISSUE THREAD

**Issue by ivan-artkod** [angular/angular#56832]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

The current behavior of `bindToComponentInputs`/`withComponentInputBinding` is very convenient as it removes the need to use instance of `ActivatedRoute` and pretty clunky code to extract data from it (pick your flavor: `prop` + `ngOnInit` + `subscribe`, observable `prop$` + `@if` + `asnyc` ...).

Could we also have similar functionality for route data?
And not just static data, but also those resolved via route resolve.

One thing to consider is potential race condition between route param updating vs async resolve function that may come about when using custom `RouteReuseStrategy`.

### Proposed solution

When using withComponentInputBinding() featue, have it accept additional flag to include data.

I.e.
```ts
// app.module.ts or app.config.ts
..
providers: [provideRouter(routes, withComponentInputBinding({bindData: true})]
..
```

```ts
// routes.ts
...
{
   path: 'example/:id',
   component: ExampleComponent,
   data: { static: 'foo' },
   resolve: {
      dynamic: (route: ActivatedRouteSnapshot) => inject(HttpClient).get(`/api/example/${route.params.id}`))
   }
}
...
```

```ts
// example.component.ts
...
@Component({
  selector: 'app-example',
  standalone: true,
  template: `
     <p>ID: {{id}}</p>
     <h1>{{ data.dynamic.title }}</h1>
     <p>static: {{ data.static }}</p>
  `
})
export class ExampleComponent {
  @Input() id: string; // mapped from :id param in route
  @Input() data: any; // mapped from both static and resolved route data
}
...
```

### Alternatives considered

Currently my component looks like this:

```ts
// example-view.component.ts
@Component({
  selector: 'app-example-view',
  standalone: true,
  imports: [CommonModule],
  template: `
  <article>
    <p>ID: {{id}}</p>
    @if(data$ | async; as data) {
      <h1>{{ data.dynamic.title }}</h1>
      <p>static: {{ data.static }}</p>
    }
  </article>
  `
})
export class ExampleViewComponent {
  @Input() id!: string; // binded directly from route :id param
  protected data$: Observable<any> = this.route.data; // and this is observable

  constructor(private route: ActivatedRoute){}
}
...
```
Notice the amount of extra bits both in component and in template just to deal with async nature of ActivatedRoute.data

**Comment by JoostK** [comment]
This should already be the case:

https://github.com/angular/angular/blob/c8e2885136b08981333a336b7b2ba553266eba63/packages/router/src/directives/router_outlet.ts#L452

**Comment by ivan-artkod** [comment]
Yes, you are right.

I have tried binding to `@Input() data: any;` it and it didn't work
`ERROR TypeError: Cannot read properties of undefined (reading 'dynamic')`

What I should have done is bind to `@Input() static: string;`and `@Input() dynamic: any;`.
