### ISSUE TITLE
DOCUMENTATION - Link to https://angular.dev/api/forms broken

### ISSUE THREAD

**Issue by DanNisenson** [angular/angular#56846]
### Describe the problem that you experienced

https://angular.dev/guide/forms/reactive-forms#reactive-forms-api-summary

there's a link here to the API ref for [Forms package](https://angular.dev/api/forms), which is broken

### Enter the URL of the topic with the problem

https://angular.dev/guide/forms/reactive-forms#reactive-forms-api-summary

### Describe what you were looking for in the documentation

FormArray API reference

**Comment by JeanMeche** [comment]
If someone wants to pick it up, please replace the link with `https://angular.dev/api#forms`

**Comment by DanNisenson** [comment]
Fixing the issue I've run into another one.

https://github.com/angular/angular/blob/main/contributing-docs/building-and-testing-angular.md

**Comment by DanNisenson** [comment]
Fixing the issue I've run into another one.
In the testing instructions there's another broken link:

https://github.com/angular/angular/blob/main/contributing-docs/building-and-testing-angular.md#running-tests-locally
"...please refer to the Bazel [Testing Angular](https://github.com/angular/angular/blob/main/contributing-docs/BAZEL.md#testing-angular) section."

Not sure where that link should point and how to run the tests

**Comment by JeanMeche** [comment]
The tests for the docs site can be run with `yarn bazel test //adev:test`.

**Comment by ashishnd** [comment]
Hey, I would like to try to solve this documentation issue. Can you please assign it to me?
