### ISSUE TITLE
Bad link on https://angular.dev/api/elements/NgElementConstructor

### ISSUE THREAD

**Issue by fredsa** [angular/angular#56857]
### Describe the problem that you experienced

https://angular.dev/api/elements/NgElementConstructor contains a bad link:

- Link text: `createCustomElement createCustomElement() function`
- Link href: `https://angular.dev/api/elements/createCustomElement%20createCustomElement()%20function`

### Enter the URL of the topic with the problem

https://angular.dev/api/elements/NgElementConstructor

**Comment by JeanMeche** [comment]
The link actually a valid markdown link but adev doesn't handle it correctly. 

https://github.com/angular/angular/blob/e7da8c2b02ae454f377cfa8a854f669cbdde034c/packages/elements/src/create-custom-element.ts#L21
