### ISSUE TITLE
Bad link on https://angular.dev/api/service-worker/VersionEvent

### ISSUE THREAD

**Issue by fredsa** [angular/angular#56858]
### Describe the problem that you experienced

https://angular.dev/api/service-worker/VersionEvent contains a bad link:

- Link text: `api /service-worker/SwUpdate#versionUpdates SwUpdate#versionUpdates`
- Link href: `https://angular.dev/api/service-worker/api%20/service-worker/SwUpdate#versionUpdates%20SwUpdate#versionUpdates`

### Enter the URL of the topic with the problem

https://angular.dev/api/service-worker/VersionEvent

**Comment by ashishnd** [comment]
I would like to try to solve this issue. Can you provide me with the correct link to which this text should point to? @JeanMeche

**Comment by JeanMeche** [comment]
The fix should be to have 

```
/**
 * A union of all event types that can be emitted by
 * {@link SwUpdate#versionUpdates}.
 *
 * @publicApi
 */
```

Feel free to drop a PR @ashishnd. !

**Comment by AndrewKushnir** [comment]
Closing this ticket, since the fix (PR https://github.com/angular/angular/pull/56870) has landed.
