### ISSUE TITLE
Bad link on https://angular.dev/api/upgrade/static/downgradeModule

### ISSUE THREAD

**Issue by fredsa** [angular/angular#56856]
### Describe the problem that you experienced

https://angular.dev/api/upgrade/static/downgradeModule contains a bad link, with both link text and link href having broken values

- Link text: `downgradeComponent downgraded component`
- Link URL: `https://angular.dev/api/upgrade/static/downgradeComponent%20downgraded%20component`

### Enter the URL of the topic with the problem

https://angular.dev/api/upgrade/static/downgradeModule

**Comment by JeanMeche** [comment]
This an docs infra issue, it will be addressed by angular/dev-infra#2154
