### ISSUE TITLE
Bad link on https://angular.dev/api/elements/createCustomElement

### ISSUE THREAD

**Issue by fredsa** [angular/angular#56855]
### Describe the problem that you experienced

https://angular.dev/api/elements/createCustomElement contains this corrupt href link:

```
<a class="docs-pill" href="guide/elements &quot;Turning Angular components into custom elements&quot;">Angular Elements Overview</a>
```

### Enter the URL of the topic with the problem

https://angular.dev/api/elements/createCustomElement

**Comment by JeanMeche** [comment]
Duplicate of #56857
