### ISSUE TITLE
Broken link /api/animations/NoopAnimationPlayer for `ɵAnimationGroupPlayer`

### ISSUE THREAD

**Issue by fredsa** [angular/angular#56850]
### Describe the problem that you experienced

On https://angular.dev/api/animations/NoopAnimationPlayer, `AnimationGroupPlayer` links to non-existent URL:
- `https://angular.dev/api/animations/%C9%B5AnimationGroupPlayer`

Decoded, this URL can be viewed as:
- `https://angular.dev/api/animations/ɵAnimationGroupPlayer`

### Enter the URL of the topic with the problem

https://angular.dev/api/animations/NoopAnimationPlayer

**Comment by JeanMeche** [comment]
We should remove that link, the symbol is private and no documented.
