### ISSUE TITLE
v18.angular.dev redirects to next.angular.dev

### ISSUE THREAD

**Issue by Yogu** [angular/angular#56868]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

If you choose "v18" in the version dropdown on angular.dev, it navigates you to v18.angular.dev, which redirects to next.angular.dev. As a result, you can't go back to the stable docs version from the navigation menu.

### Please provide a link to a minimal reproduction of the bug

https://v18.angular.dev

**Comment by ashishnd** [comment]
I will be happy to try to fix this issue. @JeanMeche
