### ISSUE TITLE
docs: Signals > Queries as signals > Results availability timing docs are confusing

### ISSUE THREAD

**Issue by benelliott** [angular/angular#56866]
### Describe the problem that you experienced

Hi, I am trying to read the "Results availability timing" section of the ["Queries as signals" documentation](https://angular.dev/guide/signals/queries) and I am quite stumped by the following lines:

> A signal query authoring functions will be executed as part of the directive instance construction. This happens before we could create a query instance and execute the template’s creation mode to collect any matches.

I am new to Signals so don't feel super confident suggesting improvements to this -- maybe it intends to say something along the lines of:

>  Signal queries are executed while the directive is instantiated.  As a consequence, there is a period of time where... [ctd]

### Enter the URL of the topic with the problem

https://angular.dev/guide/signals/queries#results-availability-timing

### Describe what you were looking for in the documentation

An understandable explanation of query signal result availability timing

**Comment by JeanMeche** [comment]
The signals are created during the class construction, we're talking about the signal instances here. 

The value that will be wrapped by the signal will be available latter, for example wheb the `ngAfterViewInit` hook runs.
