### ISSUE TITLE
Static class property adds leading underscore to instance name in v18.

### ISSUE THREAD

**Issue by maxtorchel** [angular/angular#56869]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

If we have class with static property:
`
class F {
static a = 'a';
}
`
and then instantiate it, we get instance _F:
`console.log((new F()).constructor.name)`
 In previous versions all works good.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-jamadn?file=src%2Fapp%2Fapp.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.7
Node: 22.3.0
Package Manager: npm 10.8.1
OS: linux x64
Angular: 18.0.6
Typescript 5.5.3
```

**Comment by JoostK** [comment]
Class names are not supposed to be relied on, not even in development builds. This is therefore not supported by the CLI.
