### ISSUE TITLE
@let support await / @loading / @error

### ISSUE THREAD

**Issue by DingWeizhe** [angular/angular#56862]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

When developing web applications,
it is often necessary to present dynamically loaded information on the view,
and provide different display methods during the loading process and when error.
However, currently Angular does not provide a simple method for this type of application.
In 8.1 I saw the new @let control flow, I thought it was a great syntax, but I think it could be better when it can use @loading / @error (consistent with @defer)

### Proposed solution

```typescript
class DemoComponent {
  user$ = this.httpClient.get("/user");
}
```

```html
@let user = await user$; {
  <div>
    <div class="h-2">{{ user.name }}</div>
  </div>

} @loading {
  <div class="animate-pulse">
    <div class="h-2 bg-slate-700 rounded"></div>
  </div>

} @error {
  <div class="bg-red-500 text-white font-bold rounded-t px-4 py-2">
    something warning {{ user.errorMessage }} 
  </div>
}
```

### Alternatives considered

Now we need to define additional state variables to make judgments
```typescript

class DemoComponent {
  userStatus = "PENDING";
  user$ = this.httpClient.get("/user").then(user => {
    this.userStatus = "RESOLVED";
    return user;
  }).catch(error => {
    this.userStatus = "ERROR";
    return error;
  });
}
```

```html
@switch (userStatus) {
  @case ("RESOLVED") {
    @let user = user$ | async;
    <div>
      <div class="h-2">{{ user.name }}</div>
    </div>
  }

  @case ("PENDING") {
    <div class="animate-pulse">
      <div class="h-2 bg-slate-700 rounded"></div>
    </div>
  }

  @case ("ERROR") {
    @let user = user$ | async;
    <div class="bg-red-500 text-white font-bold rounded-t px-4 py-2">
      something warning {{ user.errorMessage }} 
    </div>
  }
}
```

**Comment by pkozlowski-opensource** [comment]
We've seen similar requests in the past and decided that this is too much logic in a template - suggest dealing with error conditions and loading indicators in the TS code instead.
