### ISSUE TITLE
Easier union type narrowing in Angular control statements ('in' / `typeof` operator)

### ISSUE THREAD

**Issue by johnameyer** [angular/angular#56875]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler, core

### Description

If I have a union of types i.e. `{ one: number } | { two: number } | { three: number }`, it can be a bit onerous to narrow the type in my actual template description.

Attempting to write the template exactly as I might in a pure typescript file,

```
@if('one' in obj) {
    {{ obj.one }}
}
```
results in
```
Parser Error: Unexpected token 'in' at column 10 in ['one' in obj] in ...
```

[The documentation](https://angular.dev/guide/templates/binding#syntax) does mention these operators are not supported, but chalks it up to side effects when these operators are pure.

> You can't use JavaScript expressions that have or promote side effects, including:
> * Assignments (=, +=, -=, ...)
> * Operators such as new, typeof, or instanceof
> * Chaining expressions with ; or ,
> * The increment and decrement operators ++ and --
> * Some of the ES2015+ operators

Naturally, I could write out a type predicate `function hasOne(obj: object): obj is { one: number}` on my class, but this is a little verbose and can lead to a component having many such functions.

### Proposed solution

If / else control expressions support `in` / `typeof` / `instanceof` operators like the other standard algebraic comparison operations.

### Alternatives considered

Helper function like `$any()` that apply the proper type narrowing.

Do not throw errors for accessing property if one member of union contains that property.

**Comment by JoostK** [comment]
I think this makes sense. There's a similar issue #38560 that has been rolled into #43485, I'm adding this one to that list as well.
