### ISSUE TITLE
setting autoDetectChanges to false explicitly changes the fixture behavior

### ISSUE THREAD

**Issue by jnizet** [angular/angular#56878]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

As far as I understand, a `ComponentFixture` has two ways of working: with, or without changes auto-detection.

In reality, setting `autoDetectChanges` to `false` (even though it's supposed to already be `false` by default) has the same (partial) effect as setting it to `true`.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-uxmdfx?file=repro%2Fsrc%2Fapp%2Ffoo%2Ffoo.component.spec.ts

### Please provide the exception or error you saw

In the above repro, you'll find three similar tests, for an OnPush component.
- the first one doesn't call `fixture.autoDetechChanges()` at all (so it leaves it to false)
- the second one call `fixture.autoDetechChanges(false)`
- the third one call `fixture.autoDetechChanges(true)`

My expectation is that the second one should pass: it should behave exactly like the first one, because setting autoDetectChanges to false when it's already false (by default) shouldn't change anything.

But the second one fails for the same reason as the third one.

You can run the repro by doing 

```
cd repro
npm i
ng test
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.7
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.0.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.7
@angular-devkit/build-angular   18.0.7
@angular-devkit/core            18.0.7
@angular-devkit/schematics      18.0.7
@angular/cli                    18.0.7
@schematics/angular             18.0.7
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

### Anything else?

In general, I think the behavior of autoDetectChanges, and the way to correctly write tests with autoDetectChanges set to true, is not documented well enough. And with zoneless CD coming, the testing story could benefit from a redesign.

**Comment by JeanMeche** [comment]
To me this looks like working as expected. 

Calling `autoDetectChanges()` runs the first CD for you. 
Subsequent CD cycles are conditionned by the component being dirty (because of OnPush). 
If you either remove OnPush or replace the property change by a `setInput()`, the tests pass as they should.

**Comment by jnizet** [comment]
Thanks Matthieu.

In the second test, I'm setting it to *false*. So IMHO, it should *not* auto detect changes and should behave as if I hadn't called it at all, shouldn't it? Or do you mean that there are actually three modes but it's impossible to actually set the default one:

1. the method is never called, and you must call detectChanges() so that the DOM is updated
2. the method is called with true, and you must do something to make the component dirty and wait for the DOM to be updated (but what precisely? Is awaiting stability needed? When?) 
3. the method is called with false, and you must do something to make the component dirty and wait for the DOM to be updated (but what precisely? Is awaiting stability needed? When? Is it needed to call detectChanges? When?)

**Comment by JeanMeche** [comment]
It's not that there are 3 modes, calling `autoDetectChanges` does triggers CD for you : 

https://github.com/angular/angular/blob/229dd8355e91388f97523fc085197cf06d2fda65/packages/core/testing/src/component_fixture.ts#L273-L288

Also the "run detection" part is documented : 

https://github.com/angular/angular/blob/229dd8355e91388f97523fc085197cf06d2fda65/packages/core/testing/src/component_fixture.ts#L109-L114

https://angular.dev/api/core/testing/ComponentFixture#autoDetectChanges

**Comment by jnizet** [comment]
OK. Thanks.
Quite weird that asking not to auto detect changes causes an automatic change detection, but at least it's documented.

**Comment by atscott** [comment]
> causes an automatic change detection

Depends what you consider “automatic”. Arguably this is an “explicit” or “manual” change detection run as part of the method. 

Closing as working as documented (I don’t particularly think it _should_ call detectChanges but that’s what it does and changing it is not worth the breaking change and churn).
