### ISSUE TITLE
Documentation Not Found for service-worker API

### ISSUE THREAD

**Issue by tauhidpatel** [angular/angular#56879]
### Describe the problem that you experienced

I visited the URL https://angular.dev/api/service-worker but encountered a "Page Not Found" error instead of the expected documentation for the service-worker API.

### Enter the URL of the topic with the problem

https://angular.dev/api/service-worker

### Describe what you were looking for in the documentation

I was looking for a detailed documentation on how to implement service workers in Angular applications, including configuration options and usage examples.

### Describe the actions that led you to experience the problem

Navigated to https://angular.dev/api/service-worker from the previous angular.io expecting to find service worker documentation.

### Describe what you want to experience that would fix the problem

I would like to access the correct documentation for the service-worker API

### Add a screenshot if that helps illustrate the problem

![angular-service-issue](https://github.com/angular/angular/assets/43630196/d309eac2-300b-4e79-9441-270c780d0623)

### Provide any additional information here in as much as detail as you can

```true
The rest of the Angular documentation seems accessible, but this specific page appears to be missing or incorrectly linked.
```

**Comment by JeanMeche** [comment]
Where did you come from to access this page ?

**Comment by sasidharansd** [comment]
@JeanMeche I guess the reporter should have navigated through the node banner from angular.io website from the section: https://v17.angular.io/api/service-worker

**Comment by JeanMeche** [comment]
@sasidharansd Good catch, #56881 will fix all the API packages links.
