### ISSUE TITLE
FormRecord links to `api/forms/FormGroup ` with an extra space at the end.

### ISSUE THREAD

**Issue by sharth** [angular/angular#56872]
### Describe the problem that you experienced

Looking at the description of FormRecord, it links to FormGroup, however, this goes to a 404 due to an errant %20 being included in the link.

### Enter the URL of the topic with the problem

https://angular.dev/api/forms/FormRecord

### Describe the actions that led you to experience the problem

In the description, there's the string: `FormRecord is very similar to FormGroup`. FormGroup has the following HTML:

```
<a href="api/forms/FormGroup "><code>FormGroup </code></a>
```

![Screenshot 2024-07-05 7 27 19 PM](https://github.com/angular/angular/assets/116754/74fb6ef8-a4f2-4b15-8160-a11c4805f2da)

### Describe what you want to experience that would fix the problem

Rather than linking to `api/forms/FormGroup `, we should link to `api/forms/FormGroup` without the errant space.

**Comment by JeanMeche** [comment]
Check your cache, this has already been fixed !

**Comment by JeanMeche** [comment]
This has already been fixed see : https://next.angular.dev/api/forms/FormRecord?tab=description
The fix will land on the main site with the 18.1 release.
