### ISSUE TITLE
Missing/incorrect details in usage note tab for ngComponentOutlet api reference

### ISSUE THREAD

**Issue by Rajendran-Balaji** [angular/angular#56873]
### Describe the problem that you experienced

The syntax section is missing the `inputs`, `injector`, `ngModule` expressions and examples are also missing in the new website.

### Enter the URL of the topic with the problem

https://angular.dev/api/common/NgComponentOutlet?tab=usage-notes

### Add a screenshot if that helps illustrate the problem

New
![image](https://github.com/angular/angular/assets/88931771/f404ef4e-54ea-47dc-9fea-71b10cd803e1)

Old
![image](https://github.com/angular/angular/assets/88931771/422b2ca8-290e-40ae-9365-df9ca8bfa07b)

**Comment by JeanMeche** [comment]
This looks like a bug with highlight.js, the example is fully present in the DOM but not visible.
